### PR TITLE
Fix snapshot bug

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3065)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3065** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3065" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/3065?utm_source=stack-comment).

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3065)* status: 2 of 25 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 249 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3065#-NUujweLBVON6Svcnlg8:-NUujweLBVON6Svcnlg9:b77ym37) ([raw file](https://github.com/starkware-libs/cairo/blob/a03e3762170047820246963bb5efc25a04e23b82/crates/cairo-lang-lowering/src/lower/context.rs#L249)):*
> ```XML
>                 if let LoweredExpr::Member(member_path, _location) = &*expr {
>                     builder.update_ref(ctx, member_path, original);
>                 }
> ```

don't we need the rebind?



_Code quote:_
```XML
                if let LoweredExpr::Member(member_path, _location) = &*expr {
                    builder.update_ref(ctx, member_path, original);
                }
```
___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 208 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3065#-NUujo233G6A20dWwNOm:-NUujo233G6A20dWwNOn:b-sw7log) ([raw file](https://github.com/starkware-libs/cairo/blob/1055afb89020f638fc694439facf381f80268d12/crates/cairo-lang-sierra-generator/src/local_variables.rs#L208)):*
> ```XML
>             if alias == var {
>                 return var;
>             }
> ```

how can this happen?



_Code quote:_
```XML
            if alias == var {
                return var;
            }
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3065)* status: 2 of 25 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 249 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3065#-NUujweLBVON6Svcnlg8:-NUukszr3ZLOiZmf_pxA:batop34) ([raw file](https://github.com/starkware-libs/cairo/blob/a03e3762170047820246963bb5efc25a04e23b82/crates/cairo-lang-lowering/src/lower/context.rs#L249)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

don't we need the rebind?
</blockquote></details>

In generators.rs, I changed the output variable to be the same as the input variable

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3065)* status: 2 of 25 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 208 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3065#-NUujo233G6A20dWwNOm:-NUumYKo5FjTJ0L8uCfo:bo7834u) ([raw file](https://github.com/starkware-libs/cairo/blob/1055afb89020f638fc694439facf381f80268d12/crates/cairo-lang-sierra-generator/src/local_variables.rs#L208)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

how can this happen?
</blockquote></details>

Seems like this is the wrong fix:( Refixing...

**Pull request closed without merging**
