### PR TITLE
Added segmentation parameter for consts.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4873)

### CODE REVIEW

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4873)* status: all files reviewed, 11 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4873#-NopO6QW0pVVakOmhcH6:-NopO6QW0pVVakOmhcH7:b-gx0nsx) ([raw file](https://github.com/starkware-libs/cairo/blob/466cfba540b2daba8bba5ec705ccf9470a0255bd/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L115)):*
> ```XML
>             panic!("`ret` instruction should be a single word.")
>         };
>         for segment in self.consts_info.segments.values() {
> ```

What happens if I create a huge const?

(e.g., `a = (0, 0)`, `b = (a, a)`, `c = (b, b)`, ...)
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4873#-NopPZ2m2b7qMvcnaJ_o:-NopPZ2m2b7qMvcnaJ_p:b-2g8qqy) ([raw file](https://github.com/starkware-libs/cairo/blob/466cfba540b2daba8bba5ec705ccf9470a0255bd/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L159)):*
> ```XML
> #[derive(Debug, Eq, PartialEq, Default, Clone)]
> pub struct ConstsInfo {
>     pub segments: OrderedHashMap<u32, ConstSegment>,
> ```

Why have `OrderedHashMap` rather than go over this map in a sorted way?
E.g. you can sort in `ConstsInfo::new`.
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4873#-NopQdMh-WZ7T2ODtIJE:-NopQdMh-WZ7T2ODtIJF:b-alp8nu) ([raw file](https://github.com/starkware-libs/cairo/blob/466cfba540b2daba8bba5ec705ccf9470a0255bd/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L181)):*
> ```XML
>             }
>         }
>         let mut total_segments_size = 0;
> ```

Put a blank line above this line.
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 184 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4873#-NopQjisCXzexCotXNKv:-NopQjisCXzexCotXNKw:b-qlctz8) ([raw file](https://github.com/starkware-libs/cairo/blob/466cfba540b2daba8bba5ec705ccf9470a0255bd/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L184)):*
> ```XML
>         for (_, segment) in segments.iter_mut() {
>             segment.segment_offset = total_segments_size;
>             total_segments_size += 1 + segment.values.len();
> ```

```
// Add 1 for the `ret` instruction.
```
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 196 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4873#-NopQYf61Bp5zjdjCtAI:-NopQYf61Bp5zjdjCtAJ:b-7clwsu) ([raw file](https://github.com/starkware-libs/cairo/blob/466cfba540b2daba8bba5ec705ccf9470a0255bd/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L196)):*
> ```XML
>     pub values: Vec<BigInt>,
>     /// The offset of each const within the segment.
>     pub const_offset: OrderedHashMap<ConcreteTypeId, usize>,
> ```

Ordered needed?
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 197 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4873#-NopQ5_42lL2wcvtgC0W:-NopQ5_42lL2wcvtgC0X:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/466cfba540b2daba8bba5ec705ccf9470a0255bd/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L197)):*
> ```XML
>     /// The offset of each const within the segment.
>     pub const_offset: OrderedHashMap<ConcreteTypeId, usize>,
>     /// The offset of the segment after the program.
> ```





_Suggestion:_
```XML
/// The offset of the segment relative to the end of the code segment.
```
___
*[`crates/cairo-lang-sierra-to-casm/src/relocations.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4873#-NopT2Gk1Lo2zYJsxkfP:-NopT2Gl0ogk-ah7eAgB:bptg7vw) ([raw file](https://github.com/starkware-libs/cairo/blob/466cfba540b2daba8bba5ec705ccf9470a0255bd/crates/cairo-lang-sierra-to-casm/src/relocations.rs#L47)):*
> ```XML
>             }
>             Relocation::ConstStart(segment_index, ty) => {
>                 let segment = consts_info.segments.get(segment_index).expect("Segment not found.");
> ```

Copy this line to the previous match branch.
___
*[`crates/cairo-lang-sierra-to-casm/src/relocations.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4873#-NopTMMXDm-6btqCFVbW:-NopTMMXDm-6btqCFVbX:b-wg5tm2) ([raw file](https://github.com/starkware-libs/cairo/blob/466cfba540b2daba8bba5ec705ccf9470a0255bd/crates/cairo-lang-sierra-to-casm/src/relocations.rs#L49)):*
> ```XML
>                 let segment = consts_info.segments.get(segment_index).expect("Segment not found.");
>                 *statement_offsets.last().unwrap()
>                     + segment.segment_offset
> ```

Maybe segment_offset should include the code length?
___
*[`crates/cairo-lang-starknet/src/contract_segmentation.rs` line 189 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4873#-NopUN4Z3-rJEMQ6D-2j:-NopUN4Z3-rJEMQ6D-2k:bc0m9h6) ([raw file](https://github.com/starkware-libs/cairo/blob/466cfba540b2daba8bba5ec705ccf9470a0255bd/crates/cairo-lang-starknet/src/contract_segmentation.rs#L189)):*
> ```XML
>         .segments
>         .values()
>         .map(|segment| const_segment_offset + segment.segment_offset)
> ```

Here this would also be helpful to have `segment_offset` -> `segment_start` (from the beginning of the program)
___
*[`crates/cairo-lang-starknet/src/contract_segmentation_test_data/find_segment` line 88 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4873#-NopSPsp4RLJ6V29M8UZ:-NopSPsp4RLJ6V29M8U_:b4acw50) ([raw file](https://github.com/starkware-libs/cairo/blob/466cfba540b2daba8bba5ec705ccf9470a0255bd/crates/cairo-lang-starknet/src/contract_segmentation_test_data/find_segment#L88)):*
> ```
> 
> libfunc const_as_box<Const<felt252, 5>> = const_as_box<Const<felt252, 5>, 0>;
> libfunc const_as_box<Const<felt252, 17>> = const_as_box<Const<felt252, 17>, 1>;
> ```

Add another const that will join one of the existing segments.
___
*[`tests/e2e_test_data/libfuncs/consts` line 332 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4873#-NopVZny0s1rlTIs4Yhr:-NopVZny0s1rlTIs4Yhs:b-pfvufo) ([raw file](https://github.com/starkware-libs/cairo/blob/466cfba540b2daba8bba5ec705ccf9470a0255bd/tests/e2e_test_data/libfuncs/consts#L332)):*
> ```
>         const_as_box::<Const<felt252, 100>, 0>(),
>         const_as_box::<Const<felt252, 200>, 1>(),
>         const_as_box::<Const<felt252, 300>, 0>(),
> ```

(to check the ordering)



_Suggestion:_
```
        const_as_box::<Const<felt252, 100>, 2>(),
        const_as_box::<Const<felt252, 200>, 1>(),
        const_as_box::<Const<felt252, 300>, 2>(),
```

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4873)* status: all files reviewed, 12 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 240 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4873#-Nopc2CtD5K9snwpzSuS:-Nopc2CtD5K9snwpzSuT:bm9oxz0) ([raw file](https://github.com/starkware-libs/cairo/blob/466cfba540b2daba8bba5ec705ccf9470a0255bd/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L240)):*
> ```XML
>                         values.extend(itertools::repeat_n(
>                             BigInt::zero(),
>                             full_enum_size - variant_size - 1,
> ```

Add above this line: `// Subtract 1 due to the variant selector.`

Use `(n_variants - index).checked_mul(2).ok_or(InvocationError::IntegerOverflow)? - 1` in `get_variant_selector`.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4873)* status: all files reviewed, 12 unresolved discussions (waiting on @gilbens-starkware and @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4873#-NopO6QW0pVVakOmhcH6:-Nopd5Xi4PJeyVpqpaac:b-k6zpxr) ([raw file](https://github.com/starkware-libs/cairo/blob/466cfba540b2daba8bba5ec705ccf9470a0255bd/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L115)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

What happens if I create a huge const?

(e.g., `a = (0, 0)`, `b = (a, a)`, `c = (b, b)`, ...)
</blockquote></details>

it would be blocked by `u15` (general struct size)
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4873#-NopPZ2m2b7qMvcnaJ_o:-NopdUtnBnJrwTqvJ9KP:bngkw6z) ([raw file](https://github.com/starkware-libs/cairo/blob/466cfba540b2daba8bba5ec705ccf9470a0255bd/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L159)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Why have `OrderedHashMap` rather than go over this map in a sorted way?
E.g. you can sort in `ConstsInfo::new`.
</blockquote></details>

so - Ordered by segment index - but with possible holes?
currently it is just ordered by the order of added segments.
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4873#-NopQdMh-WZ7T2ODtIJE:-NopdPeNB68QFsc5QrGz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/466cfba540b2daba8bba5ec705ccf9470a0255bd/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L181)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Put a blank line above this line.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 184 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4873#-NopQjisCXzexCotXNKv:-NopdPCQ2L1eG0Mc8R1y:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/466cfba540b2daba8bba5ec705ccf9470a0255bd/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L184)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

```
// Add 1 for the `ret` instruction.
```
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 196 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4873#-NopQYf61Bp5zjdjCtAI:-NopeNil3PT4y4qf-f7J:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/466cfba540b2daba8bba5ec705ccf9470a0255bd/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L196)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Ordered needed?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 197 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4873#-NopQ5_42lL2wcvtgC0W:-NopeNF80D18cGCkSOfe:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/466cfba540b2daba8bba5ec705ccf9470a0255bd/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L197)):*
> ```XML
>     /// The offset of each const within the segment.
>     pub const_offset: OrderedHashMap<ConcreteTypeId, usize>,
>     /// The offset of the segment after the program.
> ```

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 240 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4873#-Nopc2CtD5K9snwpzSuS:-NopeMbs8Gf0_ISxYveA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/466cfba540b2daba8bba5ec705ccf9470a0255bd/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L240)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Add above this line: `// Subtract 1 due to the variant selector.`

Use `(n_variants - index).checked_mul(2).ok_or(InvocationError::IntegerOverflow)? - 1` in `get_variant_selector`.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/relocations.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4873#-NopT2Gk1Lo2zYJsxkfP:-NopeeOIEC1ZvteWUwyA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/466cfba540b2daba8bba5ec705ccf9470a0255bd/crates/cairo-lang-sierra-to-casm/src/relocations.rs#L47)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Copy this line to the previous match branch.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/relocations.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4873#-NopTMMXDm-6btqCFVbW:-NopehTE7dSo5WYpcH47:bb6t0iq) ([raw file](https://github.com/starkware-libs/cairo/blob/466cfba540b2daba8bba5ec705ccf9470a0255bd/crates/cairo-lang-sierra-to-casm/src/relocations.rs#L49)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Maybe segment_offset should include the code length?
</blockquote></details>

i think this would be less clear all around.
___
*[`crates/cairo-lang-starknet/src/contract_segmentation.rs` line 189 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4873#-NopUN4Z3-rJEMQ6D-2j:-NopfTAYCURPqFE6Fh59:b212ekq) ([raw file](https://github.com/starkware-libs/cairo/blob/466cfba540b2daba8bba5ec705ccf9470a0255bd/crates/cairo-lang-starknet/src/contract_segmentation.rs#L189)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Here this would also be helpful to have `segment_offset` -> `segment_start` (from the beginning of the program)
</blockquote></details>

not sure i understand the comment - refactored a bit.
___
*[`crates/cairo-lang-starknet/src/contract_segmentation_test_data/find_segment` line 88 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4873#-NopSPsp4RLJ6V29M8UZ:-NopgHW90MPiJFG906ld:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/466cfba540b2daba8bba5ec705ccf9470a0255bd/crates/cairo-lang-starknet/src/contract_segmentation_test_data/find_segment#L88)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Add another const that will join one of the existing segments.
</blockquote></details>

Done.
___
*[`tests/e2e_test_data/libfuncs/consts` line 332 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4873#-NopVZny0s1rlTIs4Yhr:-Nopg8II3scPqepmD7zD:b-ueodvj) ([raw file](https://github.com/starkware-libs/cairo/blob/466cfba540b2daba8bba5ec705ccf9470a0255bd/tests/e2e_test_data/libfuncs/consts#L332)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

(to check the ordering)
</blockquote></details>

added another one - as i want to see the merge as well.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4873)* status: 7 of 10 files reviewed, 14 unresolved discussions (waiting on @gilbens-starkware and @liorgold2)

___
*[`tests/e2e_test_data/libfuncs/consts` line 381 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4873#-NovqTuv6lAwL_RnYWOW:-Now-vZT741NR_nvYT1f:b-2iexkb) ([raw file](https://github.com/starkware-libs/cairo/blob/60ac2f881544ec2e31ba98c5f991c23fa0d9583a/tests/e2e_test_data/libfuncs/consts#L381)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Consider adding a test with the same const in two different segments.
</blockquote></details>

added more to this test, as it seems more straightforward here.
___
*[`tests/e2e_test_data/libfuncs/consts` line 383 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4873#-NovqOnC4f_DSRoUEczk:-NovzUiiB_FjWUoe2Vms:b-v13onz) ([raw file](https://github.com/starkware-libs/cairo/blob/60ac2f881544ec2e31ba98c5f991c23fa0d9583a/tests/e2e_test_data/libfuncs/consts#L383)):*
> ```
> //! > ==========================================================================
> 
> //! > const segmentation
> ```

i don't know what this means - this is the testing of segmentation in general.
this test does not focus on ordering - as there is none.

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 5 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4873)* status: 9 of 10 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4873)* status: 9 of 10 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 9 files at r1, 2 of 7 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4873#-:-NpEbVcxCyQcUVXYJGnc:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @liorgold2)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4873)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4873#-NopPZ2m2b7qMvcnaJ_o:-NpEgsDZ9Izp0-uiB6KL:b-jgxrmk) ([raw file](https://github.com/starkware-libs/cairo/blob/466cfba540b2daba8bba5ec705ccf9470a0255bd/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L159)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

so - Ordered by segment index - but with possible holes?
currently it is just ordered by the order of added segments.
</blockquote></details>

Let's reorder by segment indices (I think this is what we said f2f, right?)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4873)* status: 5 of 10 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4873#-NopPZ2m2b7qMvcnaJ_o:-NpEvQHg3od3CR1mRWw1:b-syh3al) ([raw file](https://github.com/starkware-libs/cairo/blob/466cfba540b2daba8bba5ec705ccf9470a0255bd/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L159)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Let's reorder by segment indices (I think this is what we said f2f, right?)
</blockquote></details>

for now - enforced definition is in sorted ordered, as well as there are no holes.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4873)* status: 5 of 10 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 66 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4873#-NpKHsAA6CvPybes5ma0:-NpKHsAB5dnZgJBuS5RD:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c5bb1ed59972f2417f42e3e9387ede43f64f8df9/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L66)):*
> ```XML
>     UnsupportedConstType,
>     #[error("Const segments must appear in ascending order without holes.")]
>     ConstSegmentsOutofOrder,
> ```





_Suggestion:_
```XML
    ConstSegmentsOutOfOrder,
```

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4873)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 190 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4873#-NpKIete3P04AEIZAPH3:-NpKIete3P04AEIZAPH4:b9qful5) ([raw file](https://github.com/starkware-libs/cairo/blob/c5bb1ed59972f2417f42e3e9387ede43f64f8df9/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L190)):*
> ```XML
>             .any(|(i, segment_id)| i != segment_id.into_or_panic::<usize>())
>         {
>             return Err(CompilationError::ConstSegmentsOutofOrder);
> ```

Add a test.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4873)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 66 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4873#-NpKHsAA6CvPybes5ma0:-NpKIw4lDMhRvhRz99bL:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c5bb1ed59972f2417f42e3e9387ede43f64f8df9/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L66)):*
> ```XML
>     UnsupportedConstType,
>     #[error("Const segments must appear in ascending order without holes.")]
>     ConstSegmentsOutofOrder,
> ```

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 190 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4873#-NpKIete3P04AEIZAPH3:-NpKMvIrD2pV6fMrHtrL:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c5bb1ed59972f2417f42e3e9387ede43f64f8df9/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L190)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Add a test.
</blockquote></details>

Done.

**Review by liorgold2 — APPROVED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4873)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4873#-:-NpKPVAs3os22Yib9o9q:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
