### PR TITLE
LS: Add a command to inspect analyzed crates

### PR DESCRIPTION
**Pull request by mkaput**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5987)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 11 of 16 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5987)* status: all files reviewed, 3 unresolved discussions (waiting on @Draggu and @mkaput)

___
*[`crates/cairo-lang-language-server/src/lang/inspect/crates.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5987#-O1QR9Yc77beGls3MnMJ:-O1QR9Yc77beGls3MnMK:bb7f2bf) ([raw file](https://github.com/starkware-libs/cairo/blob/e160b04ed8389462826802f4e50e5c9fe1fae07f/crates/cairo-lang-language-server/src/lang/inspect/crates.rs#L27)):*
> ```XML
> }
> 
> fn inspect_crate(cr: Crate) -> String {
> ```

doc.
___
*[`crates/cairo-lang-language-server/src/lang/inspect/crates.rs` line 39 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5987#-O1QRAXs2XDFnBVqbKW4:-O1QRAXs2XDFnBVqbKW5:bq7qonf) ([raw file](https://github.com/starkware-libs/cairo/blob/e160b04ed8389462826802f4e50e5c9fe1fae07f/crates/cairo-lang-language-server/src/lang/inspect/crates.rs#L39)):*
> ```XML
> }
> 
> fn indent(text: String) -> String {
> ```

there's an existing crate for this function:
`indent::indent_by`.
___
*[`crates/cairo-lang-language-server/tests/e2e/support/normalize.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5987#-O1QSKm56NucduYJUKJj:-O1QSKm56NucduYJUKJk:b-xr8ayo) ([raw file](https://github.com/starkware-libs/cairo/blob/e160b04ed8389462826802f4e50e5c9fe1fae07f/crates/cairo-lang-language-server/tests/e2e/support/normalize.rs#L12)):*
> ```XML
>     fn inner(fixture: &Fixture, data: String) -> String {
>         normalize_well_known_paths(fixture, normalize_paths(data))
>     }
> ```

why use an inner function?



_Code quote:_
```XML
    fn inner(fixture: &Fixture, data: String) -> String {
        normalize_well_known_paths(fixture, normalize_paths(data))
    }
```

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5987)* status: 12 of 18 files reviewed, 3 unresolved discussions (waiting on @Draggu and @orizi)

___
*[`crates/cairo-lang-language-server/src/lang/inspect/crates.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5987#-O1QR9Yc77beGls3MnMJ:-O1Q_y9B3FVbOqFkaqrQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e160b04ed8389462826802f4e50e5c9fe1fae07f/crates/cairo-lang-language-server/src/lang/inspect/crates.rs#L27)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lang/inspect/crates.rs` line 39 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5987#-O1QRAXs2XDFnBVqbKW4:-O1QZ8sJ3EZBBpLn6DD5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e160b04ed8389462826802f4e50e5c9fe1fae07f/crates/cairo-lang-language-server/src/lang/inspect/crates.rs#L39)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

there's an existing crate for this function:
`indent::indent_by`.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/tests/e2e/support/normalize.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5987#-O1QSKm56NucduYJUKJj:-O1QYOfQ0BP9NdIX3OGU:b7z95f6) ([raw file](https://github.com/starkware-libs/cairo/blob/e160b04ed8389462826802f4e50e5c9fe1fae07f/crates/cairo-lang-language-server/tests/e2e/support/normalize.rs#L12)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why use an inner function?
</blockquote></details>

Ah, I applied the [following pattern](https://matklad.github.io/2021/09/04/fast-rust-builds.html#Keeping-Instantiations-In-Check) habitually, yet it's non-effective here. Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5987#-:-O1Qmy_6EMPsz87iA2Yb:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Draggu)

**Review by Draggu — APPROVED** [review]
:lgtm:

> Reviewed 9 of 16 files at r1, 3 of 6 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5987#-:-O1REqSH5EwY9VgVt0BH:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Pull request merged**
