### PR TITLE
Refactored bounded-int tests using ignored post impl generics.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #5405
- #5393
- #5389
- #5401 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5401)

### CODE REVIEW

**Review by TomerStarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5401#-:-NvB39a8E-m9Bzlb4_96:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by TomerStarkware — APPROVED** [review]
:lgtm:

> Reviewed 21 of 44 files at r2, 1 of 45 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5401#-:-NvBQ0ti6qa1M-g-9HTe:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 45 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5401#-:-NvBTXYUASSCfBllBOe5:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 44 of 45 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5401)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5401)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @orizi)

**Pull request merged**
