### PR TITLE
Improve snippets description.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4431)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4431)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`vscode-cairo/snippets/cairo.json` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4431#-Njh1iaT5nMpaNAJIdTj:-Njh1iaT5nMpaNAJIdTk:bejw5kj) ([raw file](https://github.com/starkware-libs/cairo/blob/3610ba208c243afd16097ec1f06a52891050185b/vscode-cairo/snippets/cairo.json#L56)):*
> ```JSON
>       "}"
>     ],
>     "description": "Creates an event dictionary"
> ```

fix the other name and this one into something more sensible.

**Review by TomerStarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4431)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`vscode-cairo/snippets/cairo.json` line 226 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4431#-Njh5HQtC8PQggQg0ayW:-Njh5HQtC8PQggQg0ayX:b-468n8m) ([raw file](https://github.com/starkware-libs/cairo/blob/3610ba208c243afd16097ec1f06a52891050185b/vscode-cairo/snippets/cairo.json#L226)):*
> ```JSON
>     "prefix": "panic!",
>     "body": ["panic!(\"$1\");"],
>     "description": "Creates panic! macro"
> ```

a panic! macro

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4431)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi and @TomerStarkware)

___
*[`vscode-cairo/snippets/cairo.json` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4431#-Njh1iaT5nMpaNAJIdTj:-Njh7LQlCq1Rq9fXZO1r:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3610ba208c243afd16097ec1f06a52891050185b/vscode-cairo/snippets/cairo.json#L56)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix the other name and this one into something more sensible.
</blockquote></details>

Done.
___
*[`vscode-cairo/snippets/cairo.json` line 226 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4431#-Njh5HQtC8PQggQg0ayW:-Njh7VcR3LTYyTCKE5Tf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3610ba208c243afd16097ec1f06a52891050185b/vscode-cairo/snippets/cairo.json#L226)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

a panic! macro
</blockquote></details>

Done.

**Review by TomerStarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4431#-:-Njh8COf4xYGOdfPZH18:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @orizi)

**Pull request merged**
