### PR TITLE
Added implementation for divmod for signed ints.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #5761
- #5760
- #5759
- #5753
- #5752
- #5736 ⬅
- #5751

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5736)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5736)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/integer.cairo` line 2133 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5736#-Nzx-WBr436S8Lwz8Bgi:-Nzx-WBsADGqJDJiJrk1:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c49c0afd5eb06a04bdb530239de7ef89fca950fb/corelib/src/integer.cairo#L2133)):*
> ```Cairo
>         impl NPDR: DivRemHelper<MH::Result, CH::HighT>,
>         impl PNDR: DivRemHelper<CH::HighT, MH::Result>,
>         impl NNDR: DivRemHelper<MH::Result, MH::Result>,
> ```





_Suggestion:_
```Cairo
        // positive/positive.
        impl PPDR: DivRemHelper<CH::HighT, CH::HighT>,
        // negative/positive.
        impl NPDR: DivRemHelper<MH::Result, CH::HighT>,
        // positive/negative.
        impl PNDR: DivRemHelper<CH::HighT, MH::Result>,
        // negative/negative.
        impl NNDR: DivRemHelper<MH::Result, MH::Result>,
```
___
*[`corelib/src/integer.cairo` line 2153 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5736#-Nzx1PZA1-qfoOfJ3ldN:-Nzx1PZA1-qfoOfJ3ldO:b-40kwvj) ([raw file](https://github.com/starkware-libs/cairo/blob/c49c0afd5eb06a04bdb530239de7ef89fca950fb/corelib/src/integer.cairo#L2153)):*
> ```Cairo
>                             let (q, r) = bounded_int_div_rem(minus(lhs_lt0), nz_minus(rhs_lt0));
>                             (
>                                 super::downcast(q).expect('attempt to divide with overflow'),
> ```

what does that mean?



_Code quote:_
```Cairo
super::downcast(q).expect('attempt to divide with overflow'),
```

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/integer.cairo` line 2154 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5736#-Nzx6kr_32teKtfPLrLq:-Nzx6kra5fnkN9qswdje:b-90drlr) ([raw file](https://github.com/starkware-libs/cairo/blob/c49c0afd5eb06a04bdb530239de7ef89fca950fb/corelib/src/integer.cairo#L2154)):*
> ```Cairo
>                             (
>                                 super::downcast(q).expect('attempt to divide with overflow'),
>                                 super::upcast(minus(r))
> ```

Why is this negative?



_Code quote:_
```Cairo
 super::upcast(minus(r))
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5736)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5736)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/integer.cairo` line 2133 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5736#-Nzx-WBr436S8Lwz8Bgi:-NzxZ9m8Az6Hr4Bh2nfa:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c49c0afd5eb06a04bdb530239de7ef89fca950fb/corelib/src/integer.cairo#L2133)):*
> ```Cairo
>         impl NPDR: DivRemHelper<MH::Result, CH::HighT>,
>         impl PNDR: DivRemHelper<CH::HighT, MH::Result>,
>         impl NNDR: DivRemHelper<MH::Result, MH::Result>,
> ```

Done.
___
*[`corelib/src/integer.cairo` line 2153 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5736#-Nzx1PZA1-qfoOfJ3ldN:-NzxZAZx4Um_t_XGPJMV:b-rp51sc) ([raw file](https://github.com/starkware-libs/cairo/blob/c49c0afd5eb06a04bdb530239de7ef89fca950fb/corelib/src/integer.cairo#L2153)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what does that mean?
</blockquote></details>

we had a calculation overflow.
___
*[`corelib/src/integer.cairo` line 2154 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5736#-Nzx6kr_32teKtfPLrLq:-Nzx_Bg59ZQmhIXxpdv4:bed31dq) ([raw file](https://github.com/starkware-libs/cairo/blob/c49c0afd5eb06a04bdb530239de7ef89fca950fb/corelib/src/integer.cairo#L2154)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why is this negative?
</blockquote></details>

as discussed - this is the remainder operator.
any confusing reducing suggestions?

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5736#-:-O--mrym9whYVmRppown:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
