### PR TITLE
Add parser support for logical operators.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3308)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3308)* status: all files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-parser/src/parser_test_data/logical_operator` line 8 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3308#-NXEgD-U1bre7NWJ4eq8:-NXEgD-U1bre7NWJ4eq9:boc8bjs) ([raw file](https://github.com/starkware-libs/cairo/blob/cb4966f4ef548853f49314e4dffed59da6464ad0/crates/cairo-lang-parser/src/parser_test_data/logical_operator#L8)):*
> ```
> //! > cairo_code
> fn foo(a: bool, b: bool, c: bool) {
>     (a && b) || c
> ```

to test precedence



_Suggestion:_
```
a && b
```
___
*[`crates/cairo-lang-semantic/src/expr/test_data/logical_operator` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3308#-NXEhF_B2YcWoa6Gs4sz:-NXEhF_B2YcWoa6Gs4t-:b-s8vk0b) ([raw file](https://github.com/starkware-libs/cairo/blob/cb4966f4ef548853f49314e4dffed59da6464ad0/crates/cairo-lang-semantic/src/expr/test_data/logical_operator#L1)):*
> ```
> //! > Incompatible types in if blocks.
> ```

change
___
*[`crates/cairo-lang-semantic/src/expr/test_data/logical_operator` line 8 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3308#-NXEgzVFAc20KounZPIr:-NXEgzVFAc20KounZPIs:b6p6m60) ([raw file](https://github.com/starkware-libs/cairo/blob/cb4966f4ef548853f49314e4dffed59da6464ad0/crates/cairo-lang-semantic/src/expr/test_data/logical_operator#L8)):*
> ```
> //! > function
> fn foo(a: bool, b: bool, c: bool) {
>     (a && b) || c
> ```

remove ()
___
*[`crates/cairo-lang-semantic/src/expr/test_data/operators` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3308#-NXEhIuL7GDX9D0Wh6t5:-NXEhIuL7GDX9D0Wh6t6:b-al1ke6) ([raw file](https://github.com/starkware-libs/cairo/blob/cb4966f4ef548853f49314e4dffed59da6464ad0/crates/cairo-lang-semantic/src/expr/test_data/operators#L94)):*
> ```
> //! > ==========================================================================
> 
> //! > Test lazy bool operator.
> ```

how is this test different than the one in /logical_operator?
Also - how would it test the laziness?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3308)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser_test_data/logical_operator` line 8 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3308#-NXEgD-U1bre7NWJ4eq8:-NXElxeJ8cBK6GGSOnu6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cb4966f4ef548853f49314e4dffed59da6464ad0/crates/cairo-lang-parser/src/parser_test_data/logical_operator#L8)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

to test precedence
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/logical_operator` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3308#-NXEhF_B2YcWoa6Gs4sz:-NXEm3kOD0eD9q0s-fKG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cb4966f4ef548853f49314e4dffed59da6464ad0/crates/cairo-lang-semantic/src/expr/test_data/logical_operator#L1)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

change
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/logical_operator` line 8 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3308#-NXEgzVFAc20KounZPIr:-NXEm6ZPB8dXAWhpn32a:b-vq2znm) ([raw file](https://github.com/starkware-libs/cairo/blob/cb4966f4ef548853f49314e4dffed59da6464ad0/crates/cairo-lang-semantic/src/expr/test_data/logical_operator#L8)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

remove ()
</blockquote></details>

I'm ok with removing it, but I'n general I prefer to have `()` when I don't remember the precedence by heart.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/operators` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3308#-NXEhIuL7GDX9D0Wh6t5:-NXEmM8o8PWBocqemh29:brpmqc3) ([raw file](https://github.com/starkware-libs/cairo/blob/cb4966f4ef548853f49314e4dffed59da6464ad0/crates/cairo-lang-semantic/src/expr/test_data/operators#L94)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

how is this test different than the one in /logical_operator?
Also - how would it test the laziness?
</blockquote></details>

removed.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 10 of 11 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3308#-:-NXEmcp-0pfQ2XIQCxaa:bnfp4nl)* status: 10 of 11 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 721 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3308#-NXEmMTt0MI03CNS6g4O:-NXEmMTt0MI03CNS6g4P:b6b69sj) ([raw file](https://github.com/starkware-libs/cairo/blob/cb4966f4ef548853f49314e4dffed59da6464ad0/crates/cairo-lang-parser/src/parser.rs#L721)):*
> ```XML
>     /// Returns a GreenId of the operator or None if the operator is a unary-only operator.
>     fn try_parse_binary_operator(&mut self) -> Option<BinaryOperatorGreen> {
>         // Note that if this code is not reached you might need to add the operator to
> ```

I don't understand this comment

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-parser/src/parser.rs` line 721 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3308#-NXEmMTt0MI03CNS6g4O:-NXFEb_U0xRsxoy7_4y6:b-cjvvme) ([raw file](https://github.com/starkware-libs/cairo/blob/cb4966f4ef548853f49314e4dffed59da6464ad0/crates/cairo-lang-parser/src/parser.rs#L721)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I don't understand this comment
</blockquote></details>

I've added 
  SyntaxKind::TerminalAndAnd => self.take::<TerminalAndAnd>().into(),
next to 
  SyntaxKind::TerminalAnd => self.take::<TerminalAnd>().into(),

and it didn't work.

It turned out that this code is unreachable if there is not precedence for the operator.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3308#-:-NXFcrNlByATjqL5hp69:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-parser/src/parser_test_data/logical_operator` line 8 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3308#-NXFcHaf7ScvnKzYUX6G:-NXFcHagDLEa1_28sD2o:b-28grq0) ([raw file](https://github.com/starkware-libs/cairo/blob/c4a2c8b2ec3d9c7a5ecc64bb413c472c91f65fec/crates/cairo-lang-parser/src/parser_test_data/logical_operator#L8)):*
> ```
> //! > cairo_code
> fn foo(a: bool, b: bool, c: bool) {
>     a && b || c
> ```

Sorry for nagging - can you please add another && so that we know the precedence is not order dependent?
___
*[`crates/cairo-lang-semantic/src/expr/test_data/logical_operator` line 8 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3308#-NXEgzVFAc20KounZPIr:-NXFcf-885UJpvC1PT9W:b6fma18) ([raw file](https://github.com/starkware-libs/cairo/blob/cb4966f4ef548853f49314e4dffed59da6464ad0/crates/cairo-lang-semantic/src/expr/test_data/logical_operator#L8)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I'm ok with removing it, but I'n general I prefer to have `()` when I don't remember the precedence by heart.
</blockquote></details>

I agree in general. In this test I think it's better like that, to test the expected behavior.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3308)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser_test_data/logical_operator` line 8 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3308#-NXFcHaf7ScvnKzYUX6G:-NXFhLHD1PMsBi6S5pmP:b-7hbprb) ([raw file](https://github.com/starkware-libs/cairo/blob/c4a2c8b2ec3d9c7a5ecc64bb413c472c91f65fec/crates/cairo-lang-parser/src/parser_test_data/logical_operator#L8)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Sorry for nagging - can you please add another && so that we know the precedence is not order dependent?
</blockquote></details>

wdym?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3308)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser_test_data/logical_operator` line 8 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3308#-NXFcHaf7ScvnKzYUX6G:-NXFiq6B0ADp0jJXakZS:b-j5fr1l) ([raw file](https://github.com/starkware-libs/cairo/blob/c4a2c8b2ec3d9c7a5ecc64bb413c472c91f65fec/crates/cairo-lang-parser/src/parser_test_data/logical_operator#L8)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

wdym?
</blockquote></details>

can you give that test case that you want?

**Comment by yuvalsw** [comment]
*[`crates/cairo-lang-parser/src/parser_test_data/logical_operator` line 8 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3308#-NXFcHaf7ScvnKzYUX6G:-NXFy9QA8FKRCBiE4IVY:b3osl6v) ([raw file](https://github.com/starkware-libs/cairo/blob/c4a2c8b2ec3d9c7a5ecc64bb413c472c91f65fec/crates/cairo-lang-parser/src/parser_test_data/logical_operator#L8)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

can you give that test case that you want?
</blockquote></details>

a && b || c && d

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3308#-:-NXGH-szCAKNDNDDwb3X:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

**Pull request merged**
