### PR TITLE
Made array's external signature more extended, and simplified the code.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:0145fab1

---

**Stack**:
- #1369
- #1368
- #1367
- #1366
- #1365
- #1364
- #1349 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 13 of 14 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1349#-:-NJLYNV_7VQJaoRmm1hH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 14 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1349)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1349#-NJZIEO62lC40mBsbU7B:-NJZIEO76M_ZlWUuv8T2:bivmi2j) (no related file):*
Change (probably in a pre-PR) one of the examples to have two consecutive `array_append`.

___

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1349)* status: 11 of 14 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1349#-NJZIEO62lC40mBsbU7B:-NJZnw_lCzV5KoK8lULl:b-6e0hb8) (no related file):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Change (probably in a pre-PR) one of the examples to have two consecutive `array_append`.
</blockquote></details>

https://reviewable.io/reviews/starkware-libs/cairo/1375

___

**Review by liorgold2 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1349)* status: 11 of 14 files reviewed, all discussions resolved (waiting on @orizi)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 14 files at r1, 2 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1349)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1349#-NJ_5v-c9Q7ghxMkLYox:-NJ_5v-d5IR7lpfkhHPW:b5ci8rg) (no related file):*
@ilyalesokhin-starkware Please check `invocations/array.rs`.

___
___
*[`tests/test_data/fib_array.casm` line 15 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1349#-NJ_5m0j0A6RgDYn9Cl7:-NJ_5m0k-lhzBT1SPoRj:b-83sjoh) ([raw file](https://github.com/starkware-libs/cairo/blob/cccfbe73673cfca54cdc77b951e9a2406a24b12b/tests/test_data/fib_array.casm#L15)):*
> ```
> ret;
> [fp + -7] = [[fp + -3] + 0];
> [fp + -7] = [[fp + -3] + 1];
> ```

Nice!

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 2 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1349)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1349)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by liorgold2 — APPROVED** [review]
:lgtm: (didn't review `invocations/array.rs`)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1349#-:-NJ_6BeF7A9dRzMGrHlv:bgeq3u6)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by liorgold2 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1349)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
