### PR TITLE
Added unary operator semantic support.

### PR DESCRIPTION
**Pull request by Alon-Ti**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1148)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1148)* status: all files reviewed, 9 unresolved discussions (waiting on @Alon-Ti)

___
*[`crates/semantic/src/corelib.rs` line 224 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1148#-NI2D36J9qo6Kh-YcGph:-NI2D36J9qo6Kh-YcGpi:bjidtw8) ([raw file](https://github.com/starkware-libs/cairo/blob/9f982cf4f7c245c08310bc6976a128074b593722/crates/semantic/src/corelib.rs#L224)):*
> ```XML
>     ty: TypeId,
> ) -> Result<FunctionId, SemanticDiagnosticKind> {
>     let felt = core_felt_ty(db);
> ```

felt_ty



_Code quote:_
```XML
felt
```
___
*[`crates/semantic/src/corelib.rs` line 231 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1148#-NI2Cop7CFgECSAU4XCv:-NI2Cop7CFgECSAU4XCw:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/9f982cf4f7c245c08310bc6976a128074b593722/crates/semantic/src/corelib.rs#L231)):*
> ```XML
>     let function_name = match unary_op {
>         UnaryOperator::Minus(_) if ty == felt => "felt_neg",
>         UnaryOperator::Minus(_) => return unsupported_operator("+"),
> ```





_Suggestion:_
```XML
-
```
___
*[`crates/semantic/src/diagnostic.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1148#-NI2FL57777gtHDv8_Nh:-NI2FL58DN1RTFrRrfMG:borsd3l) ([raw file](https://github.com/starkware-libs/cairo/blob/9f982cf4f7c245c08310bc6976a128074b593722/crates/semantic/src/diagnostic.rs#L57)):*
> ```XML
>             SemanticDiagnosticKind::Unsupported => "Unsupported feature.".into(),
>             SemanticDiagnosticKind::UnknownLiteral => "Unknown literal.".into(),
>             SemanticDiagnosticKind::UnknownUnaryOperator => "Unknown unary operator.".into(),
> ```

Is this ever used?
___
*[`crates/semantic/src/diagnostic_test_data/tests` line 121 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1148#-NI2EsjiE8mQVyruB24U:-NI2EsjiE8mQVyruB24V:b-ju7r6z) ([raw file](https://github.com/starkware-libs/cairo/blob/9f982cf4f7c245c08310bc6976a128074b593722/crates/semantic/src/diagnostic_test_data/tests#L121)):*
> ```
>       ^
> 
> //! > ==========================================================================
> ```

1. Add tests for successful use of the unary operators.
2. Split this test, or at least have the 2 errors in separate statements.
___
*[`crates/semantic/src/diagnostic_test_data/tests` line 123 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1148#-NI2EeMIC_SWwvzznVrx:-NI2EeMIC_SWwvzznVry:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9f982cf4f7c245c08310bc6976a128074b593722/crates/semantic/src/diagnostic_test_data/tests#L123)):*
> ```
> //! > ==========================================================================
> 
> //! > Test unsupported operators
> ```





_Suggestion:_
```
//! > Test unsupported unary operators
```
___
*[`crates/semantic/src/diagnostic_test_data/tests` line 146 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1148#-NI2F3i32ZxvuiKgFhUq:-NI2F3i32ZxvuiKgFhUr:bnqiyym) ([raw file](https://github.com/starkware-libs/cairo/blob/9f982cf4f7c245c08310bc6976a128074b593722/crates/semantic/src/diagnostic_test_data/tests#L146)):*
> ```
>             ^
> 
> error: Binary operator '+' is not supported for types '<missing>' and '<missing>'.
> ```

I believe we don't want this? Maybe need to add logic to not raise this if one of the types is missing?
(This should be in a separate test and probably a separate PR)
___
*[`crates/semantic/src/expr/compute.rs` line 196 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1148#-NI2DUBo5si9smQeJI3j:-NI2DUBo5si9smQeJI3k:bvp12do) ([raw file](https://github.com/starkware-libs/cairo/blob/9f982cf4f7c245c08310bc6976a128074b593722/crates/semantic/src/expr/compute.rs#L196)):*
> ```XML
>     syntax: &ast::ExprUnary,
> ) -> Option<Expr> {
>     let db = ctx.db;
> ```

no need for this var



_Code quote:_
```XML
let db = ctx.db;
```
___
*[`crates/semantic/src/expr/compute.rs` line 199 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1148#-NI2ES3lA2XnFORF7vxu:-NI2ES3lA2XnFORF7vxv:b-2fkep5) ([raw file](https://github.com/starkware-libs/cairo/blob/9f982cf4f7c245c08310bc6976a128074b593722/crates/semantic/src/expr/compute.rs#L199)):*
> ```XML
>     let syntax_db = db.upcast();
> 
>     let stable_ptr = syntax.stable_ptr().into();
> ```

Can't this be inlined?
___
*[`crates/semantic/src/expr/compute.rs` line 202 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1148#-NI2Dv8Z9srwfaHjjUVS:-NI2Dv8Z9srwfaHjjUVT:b-pb44rm) ([raw file](https://github.com/starkware-libs/cairo/blob/9f982cf4f7c245c08310bc6976a128074b593722/crates/semantic/src/expr/compute.rs#L202)):*
> ```XML
>     let unary_op = syntax.op(syntax_db);
> 
>     let expr_syntax = &syntax.expr(syntax_db);
> ```

inline

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1148)* status: 0 of 6 files reviewed, 6 unresolved discussions (waiting on @Alon-Ti and @yuvalsw)

___
*[`crates/semantic/src/corelib.rs` line 231 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1148#-NI2Cop7CFgECSAU4XCv:-NI2GQcX558eXiCYlF9L:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9f982cf4f7c245c08310bc6976a128074b593722/crates/semantic/src/corelib.rs#L231)):*
> ```XML
>     let function_name = match unary_op {
>         UnaryOperator::Minus(_) if ty == felt => "felt_neg",
>         UnaryOperator::Minus(_) => return unsupported_operator("+"),
> ```

Done.
___
*[`crates/semantic/src/diagnostic.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1148#-NI2FL57777gtHDv8_Nh:-NI2GdmP-Au0FxubRUov:b-4gi06) ([raw file](https://github.com/starkware-libs/cairo/blob/9f982cf4f7c245c08310bc6976a128074b593722/crates/semantic/src/diagnostic.rs#L57)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Is this ever used?
</blockquote></details>

Not currently, will readd if ever relevant.
___
*[`crates/semantic/src/diagnostic_test_data/tests` line 121 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1148#-NI2EsjiE8mQVyruB24U:-NI2H0erCIsmibe8S8IA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9f982cf4f7c245c08310bc6976a128074b593722/crates/semantic/src/diagnostic_test_data/tests#L121)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

1. Add tests for successful use of the unary operators.
2. Split this test, or at least have the 2 errors in separate statements.
</blockquote></details>

Done.
___
*[`crates/semantic/src/diagnostic_test_data/tests` line 123 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1148#-NI2EeMIC_SWwvzznVrx:-NI2IGKt3wtHcW4ooJgE:bn0py0t) ([raw file](https://github.com/starkware-libs/cairo/blob/9f982cf4f7c245c08310bc6976a128074b593722/crates/semantic/src/diagnostic_test_data/tests#L123)):*
> ```
> //! > ==========================================================================
> 
> //! > Test unsupported operators
> ```

Added a couple of binary cases.
___
*[`crates/semantic/src/diagnostic_test_data/tests` line 146 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1148#-NI2F3i32ZxvuiKgFhUq:-NI2JQEPBvRmV51zzO6Y:b-bo9fob) ([raw file](https://github.com/starkware-libs/cairo/blob/9f982cf4f7c245c08310bc6976a128074b593722/crates/semantic/src/diagnostic_test_data/tests#L146)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I believe we don't want this? Maybe need to add logic to not raise this if one of the types is missing?
(This should be in a separate test and probably a separate PR)
</blockquote></details>

Will do this next.
___
*[`crates/semantic/src/expr/compute.rs` line 202 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1148#-NI2Dv8Z9srwfaHjjUVS:-NI2K6ftESpPTqbG6aL7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9f982cf4f7c245c08310bc6976a128074b593722/crates/semantic/src/expr/compute.rs#L202)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

inline
</blockquote></details>

Done.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1148)* status: all files reviewed, 2 unresolved discussions (waiting on @Alon-Ti)

___
*[`crates/semantic/src/diagnostic_test_data/tests` line 121 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1148#-NI2EsjiE8mQVyruB24U:-NI2u-EW2K-7nHf3z8LZ:b-sbfgnu) ([raw file](https://github.com/starkware-libs/cairo/blob/9f982cf4f7c245c08310bc6976a128074b593722/crates/semantic/src/diagnostic_test_data/tests#L121)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I only saw a positive test for -, not for !.
___
*[`crates/semantic/src/diagnostic_test_data/tests` line 129 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1148#-NI2t1KQ29zWF1iql35A:-NI2t1KQ29zWF1iql35B:b-b04po4) ([raw file](https://github.com/starkware-libs/cairo/blob/08f3b995f4883b54398aae0089057f009e99d10c/crates/semantic/src/diagnostic_test_data/tests#L129)):*
> ```
> 
> //! > expr_code
> !17
> ```

Why is this here as opposed to the rest?
___
*[`crates/semantic/src/expr/compute.rs` line 196 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1148#-NI2DUBo5si9smQeJI3j:-NI2tA9L4OImCyIQuode:bgh3lvb) ([raw file](https://github.com/starkware-libs/cairo/blob/9f982cf4f7c245c08310bc6976a128074b593722/crates/semantic/src/expr/compute.rs#L196)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

no need for this var
</blockquote></details>

You removed both. Please do extract syntax_db to not upcast twice.

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1148)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/semantic/src/diagnostic_test_data/tests` line 121 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1148#-NI2EsjiE8mQVyruB24U:-NI2y98g0JvtbsdY5hAh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9f982cf4f7c245c08310bc6976a128074b593722/crates/semantic/src/diagnostic_test_data/tests#L121)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I only saw a positive test for -, not for !.
</blockquote></details>

Done.
___
*[`crates/semantic/src/diagnostic_test_data/tests` line 129 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1148#-NI2t1KQ29zWF1iql35A:-NI2xSjO9f_thWDLVtKk:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/08f3b995f4883b54398aae0089057f009e99d10c/crates/semantic/src/diagnostic_test_data/tests#L129)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Why is this here as opposed to the rest?
</blockquote></details>

Done.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1148#-:-NI3KQ5X3NENQSVgpblB:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Alon-Ti)

___
*[`crates/semantic/src/diagnostic_test_data/tests` line 129 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1148#-NI2t1KQ29zWF1iql35A:-NI3K13o4aSnFXG3XO0B:bxudwq0) ([raw file](https://github.com/starkware-libs/cairo/blob/08f3b995f4883b54398aae0089057f009e99d10c/crates/semantic/src/diagnostic_test_data/tests#L129)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please use test_function_diagnostics

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1148)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/semantic/src/diagnostic_test_data/tests` line 129 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1148#-NI2t1KQ29zWF1iql35A:-NI3MN9E2ezAH-VOe4vv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/08f3b995f4883b54398aae0089057f009e99d10c/crates/semantic/src/diagnostic_test_data/tests#L129)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Please use test_function_diagnostics
</blockquote></details>

Done.



_Code quote:_
```
-(1 == 2);
!17;
```

**Review by Alon-Ti — COMMENTED** [review]
> Dismissed @yuvalsw from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1148)* status: 5 of 7 files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by Alon-Ti — COMMENTED** [review]
> Dismissed @yuvalsw from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1148)* status: 5 of 7 files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by Alon-Ti — COMMENTED** [review]
> Reviewed 3 of 6 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1148)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Alon-Ti)

**Pull request merged**
