### PR TITLE
Update VarUsage documentation.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3424)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3424)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/objects.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3424#-NXz3uuKBVnPO6Bugm6B:-NXz3uuKBVnPO6Bugm6C:bvmg5zm) ([raw file](https://github.com/starkware-libs/cairo/blob/f7abcb3d50a862b6e98798228154c0296c4f4cee/crates/cairo-lang-lowering/src/objects.rs#L62)):*
> ```XML
> pub struct VarUsage {
>     pub var_id: VariableId,
>     pub location: ObjectOriginId,
> ```

SourceLocation was renamed to ObjectOrigin.

This has an impact on the terminology that I failed to account for :(.



_Code quote:_
```XML
ObjectOriginId
```

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3424)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/objects.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3424#-NXzJ4Vq8GyiJMHiV96I:-NXzJ4Vq8GyiJMHiV96J:b-v3hdh0) ([raw file](https://github.com/starkware-libs/cairo/blob/7595f2ebdc96d2c6bd7ce95b9f4f6f233c6d6ebc/crates/cairo-lang-lowering/src/objects.rs#L27)):*
> ```XML
> ///
> /// This struct provides details about the object's origin, such as the original
> /// user code that caused the object to be created.
> ```

Please add here something like:
"If the object is not originated by some user code, for example if it is generated by the compiler, the location points to the most relevant user code"
___
*[`crates/cairo-lang-lowering/src/objects.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3424#-NXzK3q3EvTnaeD5Xoy3:-NXzK3q3EvTnaeD5Xoy4:bpwfza) ([raw file](https://github.com/starkware-libs/cairo/blob/7595f2ebdc96d2c6bd7ce95b9f4f6f233c6d6ebc/crates/cairo-lang-lowering/src/objects.rs#L52)):*
> ```XML
> ///
> /// Note usage origin is not the origin of the variable.
> /// The origin of var_id points to the defintion:
> ```

This sentence confuses me.



_Code quote:_
```XML
The origin of var_id points to the defintion:
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3424)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/objects.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3424#-NXzJ4Vq8GyiJMHiV96I:-NXzPGTsArXRz03c5lJy:b-iq51gf) ([raw file](https://github.com/starkware-libs/cairo/blob/7595f2ebdc96d2c6bd7ce95b9f4f6f233c6d6ebc/crates/cairo-lang-lowering/src/objects.rs#L27)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Please add here something like:
"If the object is not originated by some user code, for example if it is generated by the compiler, the location points to the most relevant user code"
</blockquote></details>

I'll try, but I'm not sure there is a clear distinction between user generated code and compiler generated code.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3424)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/objects.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3424#-NXzJ4Vq8GyiJMHiV96I:-NYCCGEu0JAEsxdoczDk:bnyj1el) ([raw file](https://github.com/starkware-libs/cairo/blob/7595f2ebdc96d2c6bd7ce95b9f4f6f233c6d6ebc/crates/cairo-lang-lowering/src/objects.rs#L27)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I'll try, but I'm not sure there is a clear distinction between user generated code and compiler generated code.
</blockquote></details>

I feel It is a bit redundant, but I've added it,
___
*[`crates/cairo-lang-lowering/src/objects.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3424#-NXzK3q3EvTnaeD5Xoy3:-NYCGpQk4kEYukYQzqBF:b-nlf0hx) ([raw file](https://github.com/starkware-libs/cairo/blob/7595f2ebdc96d2c6bd7ce95b9f4f6f233c6d6ebc/crates/cairo-lang-lowering/src/objects.rs#L52)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

This sentence confuses me.
</blockquote></details>

rephrased.

**Comment by ilyalesokhin-starkware** [comment]
I'ved decided to rename ObjectOrigin to Location.

**Comment by ilyalesokhin-starkware** [comment]
https://reviewable.io/reviews/starkware-libs/cairo/3435#-

**Review by yuvalsw — APPROVED** [review]
Do you keep this PR for the changes in comments? If so, please update the title.

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3424#-:-NYDbf1_9aWpeF74yBOt:bl222mq)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/objects.rs` line 47 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3424#-NYDb9W38GUETIj8hE2L:-NYDb9W43YkT2of2DaLX:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7e6d251558b5cdcc6c4bb4eaee5d2b4a979ac5d1/crates/cairo-lang-lowering/src/objects.rs#L47)):*
> ```XML
> /// }
> ///
> /// Then the right hand side of the tail expression `1 + a` a VarUsage Object with
> ```





_Suggestion:_
```XML
 a` is a VarUsage object with
```
___
*[`crates/cairo-lang-lowering/src/objects.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3424#-NYDbJ_EEk1Crjs_30_s:-NYDbJ_EEk1Crjs_30_t:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7e6d251558b5cdcc6c4bb4eaee5d2b4a979ac5d1/crates/cairo-lang-lowering/src/objects.rs#L51)):*
> ```XML
> ///     1 + a
> ///         ^
> /// Note that the location assosiated with the variable that was assigned to 'a' is
> ```





_Suggestion:_
```XML
 location associated with the varia
```

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3424#-:-NYDboN87L5QS_3RJRHj:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

**Review by yuvalsw — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3424)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
