### PR TITLE
Core Lib Documentation: `array` module

### PR DESCRIPTION
**Pull request by TAdev0**
This PR documents the `array` module in the core library.

### CODE REVIEW

**Comment by mkaput** [comment]
image

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6610)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @TAdev0)

___
*[`corelib/src/array.cairo` line 713 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6610#-OBKjhzy9bVh_W6hm5Vs:-OBKjhzy9bVh_W6hm5Vt:bbx9ef1) ([raw file](https://github.com/starkware-libs/cairo/blob/7ee6e1df54a5802795436e600a6db5d8c895b05f/corelib/src/array.cairo#L713)):*
> ```Cairo
> 
> extern fn tuple_from_span<T, impl Info: FixedSizedArrayInfo<T>>(
>     span: @Array<Info::Element>,
> ```

remove only the part of the doc that is wrong.



_Suggestion:_
```Cairo
/// Returns a box of struct of members of the same type from a span.
extern fn tuple_from_span<T, impl Info: FixedSizedArrayInfo<T>>(
    span: @Array<Info::Element>,
```
___
*[`corelib/src/array.cairo` line 806 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6610#-OBKjP_682TDMn0jorBb:-OBKjP_682TDMn0jorBc:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7ee6e1df54a5802795436e600a6db5d8c895b05f/corelib/src/array.cairo#L806)):*
> ```Cairo
>     type Item = @T;
>     // Advances the iterator and returns the next value. Returns `Option::None` when iteration is
>     // finished.
> ```





_Suggestion:_
```Cairo
    /// Advances the iterator and returns the next value. Returns `Option::None` when iteration is
    /// finished.
```
___
*[`corelib/src/array.cairo` line 836 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6610#-OBKjN642U90RVziG7tV:-OBKjN642U90RVziG7tW:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7ee6e1df54a5802795436e600a6db5d8c895b05f/corelib/src/array.cairo#L836)):*
> ```Cairo
>     type Item = T;
>     // Advances the iterator and returns the next value. Returns `Option::None` when iteration is
>     // finished.
> ```





_Suggestion:_
```Cairo
    /// Advances the iterator and returns the next value. Returns `Option::None` when iteration is
    /// finished.
```
___
*[`corelib/src/array.cairo` line 844 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6610#-OBKjUc2B4bVYtLR9tud:-OBKjUc2B4bVYtLR9tue:b-guvj0s) ([raw file](https://github.com/starkware-libs/cairo/blob/7ee6e1df54a5802795436e600a6db5d8c895b05f/corelib/src/array.cairo#L844)):*
> ```Cairo
> impl ArrayIntoIterator<T> of crate::iter::IntoIterator<Array<T>> {
>     type IntoIter = ArrayIter<T>;
>     /// The kind of iterator we are turning this into.
> ```

in general - not sure this is a useful doc (all around) - since it is just a copy of the traits doc.



_Code quote:_
```Cairo
    /// The kind of iterator we are turning this into.
```

**Comment by TAdev0** [comment]
@orizi  addressed comments

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6610#-:-OBQ7uvd1E-zonbUuziw:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TAdev0)

**Pull request merged**
