### PR TITLE
Change match to be a block-end instead of a Lowering statement

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2317)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 20 of 62 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2317)* status: 20 of 62 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`tests/test_data/fib_array.sierra` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2317#-NPQnSUv4htAge6eeh4r:-NPQnSUv4htAge6eeh4s:brmt18x) ([raw file](https://github.com/starkware-libs/cairo/blob/20317ac5702be1eb20eb57d5d0b2c79253044b87/tests/test_data/fib_array.sierra#L1)):*
> ```
> type felt = felt;
> ```

Can you explain the changes in this file?

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 42 of 62 files at r1, 3 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2317)* status: 52 of 62 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 108 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2317#-NPSerYs-h70h7nD3mKd:-NPSerYs-h70h7nD3mKe:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/87d855e206f861a9a709a8c6b6f59bd4f6c1d39b/crates/cairo-lang-lowering/src/inline/mod.rs#L108)):*
> ```XML
>         | FlatBlockEnd::Goto(..)
>         | FlatBlockEnd::Fallthrough(..)
>         | FlatBlockEnd::Match { .. } => {}
> ```





_Suggestion:_
```XML
        FlatBlockEnd::Return(_)
        | FlatBlockEnd::Unreachable => {}
        | FlatBlockEnd::Goto(..)
        | FlatBlockEnd::Fallthrough(..)
        | FlatBlockEnd::Match { .. } => { return Ok(false); }
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 108 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2317#-NPSerYs-h70h7nD3mKd:-NPSkqguAWAgdEfBKzlh:bh19f37) ([raw file](https://github.com/starkware-libs/cairo/blob/87d855e206f861a9a709a8c6b6f59bd4f6c1d39b/crates/cairo-lang-lowering/src/inline/mod.rs#L108)):*
> ```XML
>         | FlatBlockEnd::Goto(..)
>         | FlatBlockEnd::Fallthrough(..)
>         | FlatBlockEnd::Match { .. } => {}
> ```

actually, unreachable on the root block should panic.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2317)* status: 43 of 63 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 108 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2317#-NPSerYs-h70h7nD3mKd:-NPSq2bs5T2w5QGlXZx_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/87d855e206f861a9a709a8c6b6f59bd4f6c1d39b/crates/cairo-lang-lowering/src/inline/mod.rs#L108)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

actually, unreachable on the root block should panic.
</blockquote></details>

Done.
___
*[`tests/test_data/fib_array.sierra` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2317#-NPQnSUv4htAge6eeh4r:-NPSq3ZrCYc53jsRlV74:bjlaisq) ([raw file](https://github.com/starkware-libs/cairo/blob/20317ac5702be1eb20eb57d5d0b2c79253044b87/tests/test_data/fib_array.sierra#L1)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Can you explain the changes in this file?
</blockquote></details>

Turned out to be a bug in should_inline. Fixed.

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 4 of 13 files at r2, 14 of 16 files at r3, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2317)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2317#-:-NPStHAs-v-VKsFNcIb9:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by yuvalsw — COMMENTED** [review]
> Dismissed @ilyalesokhin-starkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2317)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
