### PR TITLE
Split u128_wide_mul to two libfuncs to allow sharing code with other libfuncs.

### PR DESCRIPTION
**Pull request by liorgold2**
**Stack**:
- #2986
- #2983
- #2980 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2980)

### CODE REVIEW

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2980#-:-NUHHwGy3J62vVIcca6x:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware, @liorgold2, and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 525 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2980#-NUHGHyN8ppRMqFXJlW-:-NUHGHyN8ppRMqFXJlW0:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e8585370837b451633cb84d6db1c69c30d6fa151/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L525)):*
> ```XML
>         }
>         Uint128Concrete::GuaranteeMul(_) => {
>             vec![ConstCost { steps: 1, holes: 0, range_checks: 0 }]
> ```





_Suggestion:_
```XML
        Uint128Concrete::GuaranteeMul(_) => {
            vec![steps(1)]
        }
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned128.rs` line 217 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2980#-NUHGsgY6PMs2ARa2S8d:-NUHGsgY6PMs2ARa2S8e:bse1nil) ([raw file](https://github.com/starkware-libs/cairo/blob/e8585370837b451633cb84d6db1c69c30d6fa151/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned128.rs#L217)):*
> ```XML
>     let [range_check_ref, guarantee] = builder.try_get_refs()?;
>     let [range_check] = range_check_ref.try_unpack()?;
>     let [a, b, upper_uint128, lower_uint128] = guarantee.try_unpack()?;
> ```

Consider renaming to res_high/res_low to be consistent.



_Code quote:_
```XML
upper_uint128, lower_uint128
```

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 11 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2980)* status: all files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @liorgold2)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 729 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2980#-NUHI-Hq9EQ24xq1vNQi:-NUHI-Hq9EQ24xq1vNQj:b-tb718d) ([raw file](https://github.com/starkware-libs/cairo/blob/e8585370837b451633cb84d6db1c69c30d6fa151/crates/cairo-lang-runner/src/casm_run/mod.rs#L729)):*
> ```XML
>             let rhs_val = get_val(vm, rhs)?.to_biguint();
>             let prod = lhs_val * rhs_val;
>             insert_value_to_cellref!(vm, high, Felt252::from(prod.clone() / pow_2_128.clone()))?;
> ```

Can you do this with shifts instead? For efficiency.



_Code quote:_
```XML
 / pow_2_128.clone()
```
___
*[`tests/e2e_test_data/libfuncs/u128` line 144 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2980#-NUHIrtl3UA9x0tbSibE:-NUHIrtl3UA9x0tbSibF:bwl3eij) ([raw file](https://github.com/starkware-libs/cairo/blob/e8585370837b451633cb84d6db1c69c30d6fa151/tests/e2e_test_data/libfuncs/u128#L144)):*
> ```
> [ap + 0] = [fp + -4], ap++;
> [ap + 0] = [fp + -3], ap++;
> [ap + 0] = [ap + -4], ap++;
> ```

Can you explain these?



_Code quote:_
```
[ap + 0] = [fp + -4], ap++;
[ap + 0] = [fp + -3], ap++;
[ap + 0] = [ap + -4], ap++;
[ap + 0] = [ap + -4], ap++;
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2980)* status: all files reviewed, 5 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/int/unsigned128.rs` line 208 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2980#-NUHK_Zb8uM_38FKWft9:-NUHK_Zb8uM_38FKWftA:b8pt476) ([raw file](https://github.com/starkware-libs/cairo/blob/e8585370837b451633cb84d6db1c69c30d6fa151/crates/cairo-lang-sierra/src/extensions/modules/int/unsigned128.rs#L208)):*
> ```XML
>                     // here.
>                     ref_info: OutputVarReferenceInfo::Deferred(DeferredOutputKind::Generic),
>                 },
> ```

document the args.



_Code quote:_
```XML
                OutputVarInfo {
                    ty: u128_type.clone(),
                    ref_info: OutputVarReferenceInfo::NewTempVar { idx: Some(0) },
                },
                OutputVarInfo {
                    ty: u128_type,
                    ref_info: OutputVarReferenceInfo::NewTempVar { idx: Some(1) },
                },
                OutputVarInfo {
                    ty: context.get_concrete_type(U128MulGuaranteeType::id(), &[])?,
                    // TODO(lior): Add `OutputVarReferenceInfo::SimpleDerefs` variant and use it
                    // here.
                    ref_info: OutputVarReferenceInfo::Deferred(DeferredOutputKind::Generic),
                },
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2980)* status: 8 of 13 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 729 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2980#-NUHI-Hq9EQ24xq1vNQi:-NUHMV4OCQCIuheeiYD1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e8585370837b451633cb84d6db1c69c30d6fa151/crates/cairo-lang-runner/src/casm_run/mod.rs#L729)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Can you do this with shifts instead? For efficiency.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/int/unsigned128.rs` line 208 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2980#-NUHK_Zb8uM_38FKWft9:-NUHMh4S7loOym6qoqfB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e8585370837b451633cb84d6db1c69c30d6fa151/crates/cairo-lang-sierra/src/extensions/modules/int/unsigned128.rs#L208)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

document the args.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 525 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2980#-NUHGHyN8ppRMqFXJlW-:-NUHMqf-11UanqinnA9u:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e8585370837b451633cb84d6db1c69c30d6fa151/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L525)):*
> ```XML
>         }
>         Uint128Concrete::GuaranteeMul(_) => {
>             vec![ConstCost { steps: 1, holes: 0, range_checks: 0 }]
> ```

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned128.rs` line 217 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2980#-NUHGsgY6PMs2ARa2S8d:-NUHN-vz3PRP5DK5Z1Yu:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e8585370837b451633cb84d6db1c69c30d6fa151/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned128.rs#L217)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Consider renaming to res_high/res_low to be consistent.
</blockquote></details>

Done.
___
*[`tests/e2e_test_data/libfuncs/u128` line 144 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2980#-NUHIrtl3UA9x0tbSibE:-NUHN1GlENyS4N8tMKI3:bt2vr1b) ([raw file](https://github.com/starkware-libs/cairo/blob/e8585370837b451633cb84d6db1c69c30d6fa151/tests/e2e_test_data/libfuncs/u128#L144)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Can you explain these?
</blockquote></details>

Fixed.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 13 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2980#-:-NUHObjI9Wgo9dKkWMsB:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2980#-:-NUHVWRC2hrJ1ZjhrtRw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2980)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
