### PR TITLE
Added events to contracts

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1710)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/plugin.rs` line 494 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1710#-NLLZkVS3tK8gD-yBspg:-NLLZkVS3tK8gD-yBsph:bp9w46c) ([raw file](https://github.com/starkware-libs/cairo/blob/6dfd4f80ee8789ce240c16e9d1454b84f88a7156/crates/cairo-lang-starknet/src/plugin.rs#L494)):*
> ```XML
>             RewriteNode::Modified(ModifiedNode {
>                 children: vec![
>                     RewriteNode::Trimmed(function_ast.declaration(db).as_syntax_node()),
> ```

I think you should copy the attribute



_Code quote:_
```XML
                children: vec![
                    RewriteNode::Trimmed(function_ast.declaration(db).as_syntax_node()),
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/plugin.rs` line 494 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1710#-NLLZkVS3tK8gD-yBspg:-NLLZzDJDHFPW7wAWkgH:bh18dvg) ([raw file](https://github.com/starkware-libs/cairo/blob/6dfd4f80ee8789ce240c16e9d1454b84f88a7156/crates/cairo-lang-starknet/src/plugin.rs#L494)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I think you should copy the attribute
</blockquote></details>

And skip such functions when creating a dispatcher.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/plugin.rs` line 424 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1710#-NLL_eVgCKWrzLzWCeW_:-NLL_eVgCKWrzLzWCeWa:b5vw0s6) ([raw file](https://github.com/starkware-libs/cairo/blob/6dfd4f80ee8789ce240c16e9d1454b84f88a7156/crates/cairo-lang-starknet/src/plugin.rs#L424)):*
> ```XML
>             });
> 
>             continue;
> ```

remove.

Otherwise the language server will not display the `Could not find serialization for type` message.



_Code quote:_
```XML
  continue;
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1710)* status: all files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 398 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1710#-NLLYuy-6rCCoJu9PccT:-NLLYuy-6rCCoJu9PccU:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6dfd4f80ee8789ce240c16e9d1454b84f88a7156/crates/cairo-lang-starknet/src/plugin.rs#L398)):*
> ```XML
> }
> 
> /// Generates an event function.
> ```





_Suggestion:_
```XML
Generates a function to emit an event and the corresponding ABI item.
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1710)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 398 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1710#-NLLYuy-6rCCoJu9PccT:-NLQxnIqD4uhGkVLvg9p:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6dfd4f80ee8789ce240c16e9d1454b84f88a7156/crates/cairo-lang-starknet/src/plugin.rs#L398)):*
> ```XML
> }
> 
> /// Generates an event function.
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 424 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1710#-NLL_eVgCKWrzLzWCeW_:-NLRA9HG2Z2aQiiZJE3N:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6dfd4f80ee8789ce240c16e9d1454b84f88a7156/crates/cairo-lang-starknet/src/plugin.rs#L424)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

remove.

Otherwise the language server will not display the `Could not find serialization for type` message.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 494 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1710#-NLLZkVS3tK8gD-yBspg:-NLRIrcFAtu_M7CA7afb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6dfd4f80ee8789ce240c16e9d1454b84f88a7156/crates/cairo-lang-starknet/src/plugin.rs#L494)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

And skip such functions when creating a dispatcher.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1710#-:-NLU_Ifv3hCod-sObmzx:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 429 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1710#-NLUZlkm2SxTB67b610m:-NLUZlkm2SxTB67b610n:b-h0oczf) ([raw file](https://github.com/starkware-libs/cairo/blob/754a0ee3c9122f53560f8448f3eae0ac8e78d4a4/crates/cairo-lang-starknet/src/plugin.rs#L429)):*
> ```XML
>                 message: "`ref` parameters are not supported in contract events.".to_string(),
>             });
>             skip_param = true;
> ```

I don't understand what the name means,

consider the following:
param_skipped
skip_generation
errors_encountered



_Code quote:_
```XML
skip_param
```
___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 508 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1710#-NLU_6fi5trnRvxKDUeW:-NLU_6fi5trnRvxKDUeX:bwzpzy9) ([raw file](https://github.com/starkware-libs/cairo/blob/754a0ee3c9122f53560f8448f3eae0ac8e78d4a4/crates/cairo-lang-starknet/src/plugin.rs#L508)):*
> ```XML
>             RewriteNode::Modified(ModifiedNode {
>                 children: vec![
>                     RewriteNode::Text("#[event]\n        ".to_string()),
> ```

consider copying the original node.



_Code quote:_
```XML
#[event]\n
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1710)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 429 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1710#-NLUZlkm2SxTB67b610m:-NLUxgpx0ItMS0BqJB86:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/754a0ee3c9122f53560f8448f3eae0ac8e78d4a4/crates/cairo-lang-starknet/src/plugin.rs#L429)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't understand what the name means,

consider the following:
param_skipped
skip_generation
errors_encountered
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 508 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1710#-NLU_6fi5trnRvxKDUeW:-NLUxoqoC1buSXfjCirW:b-wgj5in) ([raw file](https://github.com/starkware-libs/cairo/blob/754a0ee3c9122f53560f8448f3eae0ac8e78d4a4/crates/cairo-lang-starknet/src/plugin.rs#L508)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

consider copying the original node.
</blockquote></details>

I thought it doesn't really matter as there can't be errors there. Also - at least for now, if it has details, e.g. #[event(bla)], then I think I don't want to copy them. In the ABI I only want to know whether it's an event or not.
WDYT?

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1710#-:-NLVBBzF3KoDaP7frNN2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
