### PR TITLE
Added bin ops for u256.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:8d8eaded

---

**Stack**:
- #1423
- #1421 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1421)* status: all files reviewed, 9 unresolved discussions (waiting on @orizi)

___
*[`corelib/test.cairo` line 200 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1421#-NJoQwHkE4_1p7DBB0pw:-NJoQwHkE4_1p7DBB0px:bqa92ka) ([raw file](https://github.com/starkware-libs/cairo/blob/7970382c38494a72694c3cd0bf4b360fb8c91a61/corelib/test.cairo#L200)):*
> ```Cairo
>     assert(
>         (as_u256(2_u128, 2_u128) | as_u256(1_u128, 2_u128)) == as_u256(3_u128, 2_u128),
>         '2.2|2.1==2.3'
> ```

the short description strings are swapped here



_Code quote:_
```Cairo
    assert(
        (as_u256(2_u128, 2_u128) | as_u256(1_u128, 2_u128)) == as_u256(3_u128, 2_u128),
        '2.2|2.1==2.3'
    );
    assert(
        (as_u256(2_u128, 2_u128) | as_u256(2_u128, 1_u128)) == as_u256(2_u128, 3_u128),
        '2.2|1.2==3.2'
    );
```
___
*[`corelib/test.cairo` line 208 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1421#-NJoR9adCThMcEA3xMl-:-NJoR9adCThMcEA3xMl0:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7970382c38494a72694c3cd0bf4b360fb8c91a61/corelib/test.cairo#L208)):*
> ```Cairo
>     assert(
>         (as_u256(1_u128, 2_u128) & as_u256(2_u128, 2_u128)) == as_u256(0_u128, 2_u128),
>         '1.2&2.2==3.2'
> ```





_Suggestion:_
```Cairo
'1.2&2.2==0.2'
```
___
*[`corelib/test.cairo` line 212 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1421#-NJoR7dU-S1TdvHaghfg:-NJoR7dU-S1TdvHaghfh:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7970382c38494a72694c3cd0bf4b360fb8c91a61/corelib/test.cairo#L212)):*
> ```Cairo
>     assert(
>         (as_u256(2_u128, 1_u128) & as_u256(2_u128, 2_u128)) == as_u256(2_u128, 0_u128),
>         '2.1&2.2==2.3'
> ```





_Suggestion:_
```Cairo
'2.1&2.2==2.0'
```
___
*[`corelib/test.cairo` line 216 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1421#-NJoRN-KD53QXWS3SB3L:-NJoRN-KD53QXWS3SB3M:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7970382c38494a72694c3cd0bf4b360fb8c91a61/corelib/test.cairo#L216)):*
> ```Cairo
>     assert(
>         (as_u256(2_u128, 2_u128) & as_u256(1_u128, 2_u128)) == as_u256(0_u128, 2_u128),
>         '2.2&2.1==2.3'
> ```





_Suggestion:_
```Cairo
'2.2&1.2==0.2'
```
___
*[`corelib/test.cairo` line 220 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1421#-NJoRR6E1fzbpngsF_IO:-NJoRR6E1fzbpngsF_IP:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7970382c38494a72694c3cd0bf4b360fb8c91a61/corelib/test.cairo#L220)):*
> ```Cairo
>     assert(
>         (as_u256(2_u128, 2_u128) & as_u256(2_u128, 1_u128)) == as_u256(2_u128, 0_u128),
>         '2.2&1.2==3.2'
> ```





_Suggestion:_
```Cairo
'2.2&2.1==2.0'
```
___
*[`corelib/test.cairo` line 224 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1421#-NJoRUX9AG-aCI1FAkw8:-NJoRUX9AG-aCI1FAkw9:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7970382c38494a72694c3cd0bf4b360fb8c91a61/corelib/test.cairo#L224)):*
> ```Cairo
>     assert(
>         (as_u256(1_u128, 2_u128) ^ as_u256(2_u128, 2_u128)) == as_u256(3_u128, 0_u128),
>         '1.2^2.2==3.2'
> ```





_Suggestion:_
```Cairo
'1.2^2.2==3.0'
```
___
*[`corelib/test.cairo` line 228 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1421#-NJoRXDY1DoZl9_Lby2u:-NJoRXDY1DoZl9_Lby2v:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7970382c38494a72694c3cd0bf4b360fb8c91a61/corelib/test.cairo#L228)):*
> ```Cairo
>     assert(
>         (as_u256(2_u128, 1_u128) ^ as_u256(2_u128, 2_u128)) == as_u256(0_u128, 3_u128),
>         '2.1^2.2==2.3'
> ```





_Suggestion:_
```Cairo
'2.1^2.2==0.3
```
___
*[`corelib/test.cairo` line 232 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1421#-NJoRbAXBAgojcHvnsTB:-NJoRbAXBAgojcHvnsTC:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7970382c38494a72694c3cd0bf4b360fb8c91a61/corelib/test.cairo#L232)):*
> ```Cairo
>     assert(
>         (as_u256(2_u128, 2_u128) ^ as_u256(1_u128, 2_u128)) == as_u256(3_u128, 0_u128),
>         '2.2^2.1==2.3'
> ```





_Suggestion:_
```Cairo
'2.2^1.2==3.0'
```
___
*[`corelib/test.cairo` line 236 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1421#-NJoRgyh3JraLYN-ofiK:-NJoRgyh3JraLYN-ofiL:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7970382c38494a72694c3cd0bf4b360fb8c91a61/corelib/test.cairo#L236)):*
> ```Cairo
>     assert(
>         (as_u256(2_u128, 2_u128) ^ as_u256(2_u128, 1_u128)) == as_u256(0_u128, 3_u128),
>         '2.2^1.2==3.2'
> ```





_Suggestion:_
```Cairo
'2.2^2.1==0.3'
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1421)* status: all files reviewed, 9 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`corelib/test.cairo` line 200 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1421#-NJoQwHkE4_1p7DBB0pw:-NJoXafu9ZmYeV-tD19d:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a54010f469f45f67ee59c54d4e299e4412072eb7/corelib/test.cairo#L200)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the short description strings are swapped here
</blockquote></details>

Done.
___
*[`corelib/test.cairo` line 208 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1421#-NJoR9adCThMcEA3xMl-:-NJoXbA68bL8jI5uuoRg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a54010f469f45f67ee59c54d4e299e4412072eb7/corelib/test.cairo#L208)):*
> ```Cairo
>     assert(
>         (as_u256(1_u128, 2_u128) & as_u256(2_u128, 2_u128)) == as_u256(0_u128, 2_u128),
>         '1.2&2.2==3.2'
> ```

Done.
___
*[`corelib/test.cairo` line 212 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1421#-NJoR7dU-S1TdvHaghfg:-NJoXbT707NEyHXdRBsT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a54010f469f45f67ee59c54d4e299e4412072eb7/corelib/test.cairo#L212)):*
> ```Cairo
>     assert(
>         (as_u256(2_u128, 1_u128) & as_u256(2_u128, 2_u128)) == as_u256(2_u128, 0_u128),
>         '2.1&2.2==2.3'
> ```

Done.
___
*[`corelib/test.cairo` line 216 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1421#-NJoRN-KD53QXWS3SB3L:-NJoXbpYDjI3Ze3oi1cI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a54010f469f45f67ee59c54d4e299e4412072eb7/corelib/test.cairo#L216)):*
> ```Cairo
>     assert(
>         (as_u256(2_u128, 2_u128) & as_u256(1_u128, 2_u128)) == as_u256(0_u128, 2_u128),
>         '2.2&2.1==2.3'
> ```

Done.
___
*[`corelib/test.cairo` line 220 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1421#-NJoRR6E1fzbpngsF_IO:-NJoXcCrC-DpiiXIFpwU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a54010f469f45f67ee59c54d4e299e4412072eb7/corelib/test.cairo#L220)):*
> ```Cairo
>     assert(
>         (as_u256(2_u128, 2_u128) & as_u256(2_u128, 1_u128)) == as_u256(2_u128, 0_u128),
>         '2.2&1.2==3.2'
> ```

Done.
___
*[`corelib/test.cairo` line 224 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1421#-NJoRUX9AG-aCI1FAkw8:-NJoXcds5r4tm67PGH_0:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a54010f469f45f67ee59c54d4e299e4412072eb7/corelib/test.cairo#L224)):*
> ```Cairo
>     assert(
>         (as_u256(1_u128, 2_u128) ^ as_u256(2_u128, 2_u128)) == as_u256(3_u128, 0_u128),
>         '1.2^2.2==3.2'
> ```

Done.
___
*[`corelib/test.cairo` line 228 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1421#-NJoRXDY1DoZl9_Lby2u:-NJoXcxD6minZDRw3YMm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a54010f469f45f67ee59c54d4e299e4412072eb7/corelib/test.cairo#L228)):*
> ```Cairo
>     assert(
>         (as_u256(2_u128, 1_u128) ^ as_u256(2_u128, 2_u128)) == as_u256(0_u128, 3_u128),
>         '2.1^2.2==2.3'
> ```

Done.
___
*[`corelib/test.cairo` line 232 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1421#-NJoRbAXBAgojcHvnsTB:-NJoXdJb7ReZkZx7ZXXl:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a54010f469f45f67ee59c54d4e299e4412072eb7/corelib/test.cairo#L232)):*
> ```Cairo
>     assert(
>         (as_u256(2_u128, 2_u128) ^ as_u256(1_u128, 2_u128)) == as_u256(3_u128, 0_u128),
>         '2.2^2.1==2.3'
> ```

Done.
___
*[`corelib/test.cairo` line 236 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1421#-NJoRgyh3JraLYN-ofiK:-NJoXdbq04S4oW0Ggr_q:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a54010f469f45f67ee59c54d4e299e4412072eb7/corelib/test.cairo#L236)):*
> ```Cairo
>     assert(
>         (as_u256(2_u128, 2_u128) ^ as_u256(2_u128, 1_u128)) == as_u256(0_u128, 3_u128),
>         '2.2^1.2==3.2'
> ```

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1421)* status: all files reviewed, 9 unresolved discussions (waiting on @orizi)

___
*[`corelib/test.cairo` line 200 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1421#-NJoQwHkE4_1p7DBB0pw:-NJogilG1mlPYx-IJHLz:b-lsa1tf) ([raw file](https://github.com/starkware-libs/cairo/blob/a54010f469f45f67ee59c54d4e299e4412072eb7/corelib/test.cairo#L200)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Done.
</blockquote></details>

did you push? i don't see changes

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1421)* status: 3 of 4 files reviewed, 9 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`corelib/test.cairo` line 200 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1421#-NJoQwHkE4_1p7DBB0pw:-NJoiW-Q265KhwXF-7gq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a54010f469f45f67ee59c54d4e299e4412072eb7/corelib/test.cairo#L200)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

did you push? i don't see changes
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1421#-:-NJoj7wiDxyQ4ianvmhe:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
