### PR TITLE
Generate implementations of StorageAccess for abi Dispatchers

### PR DESCRIPTION
**Pull request by maciejka**
Adds implementations of `StorageAccess` for `Dispatchers` generated by #[abi].

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2804)

### CODE REVIEW

**Review by spapinistarkware — COMMENTED** [review]
Can you please add a test under cairo-lang-starknet/cairo_level_tests/lib.cairo? Perhaps in a new submodule?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2804#-:-NTSunmy8oZg6wT2or0F:byxs5tb)* status: 0 of 2 files reviewed, all discussions resolved

**Comment by maciejka** [comment]
> Can you please add a test under cairo-lang-starknet/cairo_level_tests/lib.cairo? Perhaps in a new submodule?
> 
> > _[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2804#-:-NTSunmy8oZg6wT2or0F:byxs5tb)_ status: 0 of 2 files reviewed, all discussions resolved

Added tests, not sure if the modules are structured the way you would like it.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2804)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @maciejka)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo` line 284 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2804#-NTsb9bR1e9WZiZdQtwL:-NTsb9bR1e9WZiZdQtwM:bltm6gf) ([raw file](https://github.com/starkware-libs/cairo/blob/ad73bace76e101e2242764a2d317174a8def1697/crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo#L284)):*
> ```Cairo
>     let event = MyEventEnum::A(event);
>     event_serde_tester(event.clone());
> }
> ```

Add a newline

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2804)* status: all files reviewed, 1 unresolved discussion (waiting on @maciejka)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2804#-:-NTscg3Q6CDSBQKohqkC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciejka)

**Pull request merged**
