### PR TITLE
Improve MissingColonColon diagnostic.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5926)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/tests` line 752 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5926#-O0hoftvCJ9rR6AdI13_:-O0hoftvCJ9rR6AdI13a:b-vivhyt) ([raw file](https://github.com/starkware-libs/cairo/blob/37645bd0f34277480ecd38cb2b1e60857a20edef/crates/cairo-lang-semantic/src/diagnostic_test_data/tests#L752)):*
> ```
> 
> //! > expected_diagnostics
> error: Expected variable or constant, found function.
> ```

This is generated here:
https://github.com/starkware-libs/cairo/blob/37645bd0f34277480ecd38cb2b1e60857a20edef/crates/cairo-lang-semantic/src/expr/compute.rs#L2677

I'm not sure that getting a function when resolving a path is actually wrong, I guess the issue is that we don't have types for functions.



_Code quote:_
```
error: Expected variable or constant, found function.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/tests` line 762 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5926#-O0hpCdo2ZgBUwKTnZNL:-O0hpCdo2ZgBUwKTnZNM:b-ii8wnb) ([raw file](https://github.com/starkware-libs/cairo/blob/37645bd0f34277480ecd38cb2b1e60857a20edef/crates/cairo-lang-semantic/src/diagnostic_test_data/tests#L762)):*
> ```
>                  ^
> 
> error: Type annotations needed. Failed to infer ?0.
> ```

I'm looking into where this is generated.



_Code quote:_
```
error: Type annotations needed. Failed to infer ?0.
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5926#-:-O0hsXINC6q1dceTy2yd:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/tests` line 752 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5926#-O0hoftvCJ9rR6AdI13_:-O0hrzbr5DbNv0MYwg6Q:b-80usl) ([raw file](https://github.com/starkware-libs/cairo/blob/37645bd0f34277480ecd38cb2b1e60857a20edef/crates/cairo-lang-semantic/src/diagnostic_test_data/tests#L752)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

This is generated here:
https://github.com/starkware-libs/cairo/blob/37645bd0f34277480ecd38cb2b1e60857a20edef/crates/cairo-lang-semantic/src/expr/compute.rs#L2677

I'm not sure that getting a function when resolving a path is actually wrong, I guess the issue is that we don't have types for functions.
</blockquote></details>

`function` will be a type of a constants if we have an `Fn` sort of trait. but that is not currently the case.
It makes sense to me this will change when we go though the process of adding closures.
___
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/tests` line 762 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5926#-O0hpCdo2ZgBUwKTnZNL:-O0hsVTW7GLHz7U2CBM4:b-7s4s80) ([raw file](https://github.com/starkware-libs/cairo/blob/37645bd0f34277480ecd38cb2b1e60857a20edef/crates/cairo-lang-semantic/src/diagnostic_test_data/tests#L762)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I'm looking into where this is generated.
</blockquote></details>

cool.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/tests` line 762 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5926#-O0hpCdo2ZgBUwKTnZNL:-O0hvjJNC4oV5Kpl2jay:bq62pz2) ([raw file](https://github.com/starkware-libs/cairo/blob/37645bd0f34277480ecd38cb2b1e60857a20edef/crates/cairo-lang-semantic/src/diagnostic_test_data/tests#L762)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

cool.
</blockquote></details>

It is generated here:
https://github.com/starkware-libs/cairo/blob/8b30213094a8d846fc26a969b961c34bb26fe102/crates/cairo-lang-semantic/src/corelib.rs#L476

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5926)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/tests` line 762 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5926#-O0hpCdo2ZgBUwKTnZNL:-O0hy0720mZKOxeM2fxC:b-o83ecd) ([raw file](https://github.com/starkware-libs/cairo/blob/37645bd0f34277480ecd38cb2b1e60857a20edef/crates/cairo-lang-semantic/src/diagnostic_test_data/tests#L762)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

It is generated here:
https://github.com/starkware-libs/cairo/blob/8b30213094a8d846fc26a969b961c34bb26fe102/crates/cairo-lang-semantic/src/corelib.rs#L476
</blockquote></details>

it seems that there is some "missing" propagation.
but it makes sense to me for this to go to a following PR.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 813 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5926#-O0iDfZJEyN9HwCjDoFD:-O0iDfZJEyN9HwCjDoFE:b-upj1rk) ([raw file](https://github.com/starkware-libs/cairo/blob/37645bd0f34277480ecd38cb2b1e60857a20edef/crates/cairo-lang-semantic/src/diagnostic.rs#L813)):*
> ```XML
>                 }
>             }
>             SemanticDiagnosticKind::MissingColonColon => "Are you missing a `::`?.".into(),
> ```

Should I rename it to:
MaybeMissingColonColon
?



_Suggestion:_
```XML
MaybeMissingColonColon
```

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5926)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 813 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5926#-O0iGuW4BZ6XbH0YWcIm:-O0iGuW4BZ6XbH0YWcIn:bic51k2) ([raw file](https://github.com/starkware-libs/cairo/blob/37645bd0f34277480ecd38cb2b1e60857a20edef/crates/cairo-lang-semantic/src/diagnostic.rs#L813)):*
> ```XML
>                 }
>             }
>             SemanticDiagnosticKind::MissingColonColon => "Are you missing a `::`?.".into(),
> ```

this is total nitpick from my side, but I don't like using questions as diagnostics

to given an example, this is what Rust does here:

```
use `::<...>` instead of `<...>` to specify lifetime, type, or const arguments
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=41b500ebab6cad26b18da195036848e5

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5926)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 813 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5926#-O0iDfZJEyN9HwCjDoFD:-O0iILFU6JM9m4lMXFAc:b8uqcah) ([raw file](https://github.com/starkware-libs/cairo/blob/37645bd0f34277480ecd38cb2b1e60857a20edef/crates/cairo-lang-semantic/src/diagnostic.rs#L813)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Should I rename it to:
MaybeMissingColonColon
?
</blockquote></details>

Yeah, makes sense

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 813 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5926#-O0iGuW4BZ6XbH0YWcIm:-O0iILnVBAxDC25FL2__:by71eww) ([raw file](https://github.com/starkware-libs/cairo/blob/37645bd0f34277480ecd38cb2b1e60857a20edef/crates/cairo-lang-semantic/src/diagnostic.rs#L813)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

this is total nitpick from my side, but I don't like using questions as diagnostics

to given an example, this is what Rust does here:

```
use `::<...>` instead of `<...>` to specify lifetime, type, or const arguments
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=41b500ebab6cad26b18da195036848e5
</blockquote></details>

The issue is that it is not clear what the error is.

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5926)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 813 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5926#-O0iGuW4BZ6XbH0YWcIm:-O0iK5LkCn-nnnxUY809:bclys5i) ([raw file](https://github.com/starkware-libs/cairo/blob/37645bd0f34277480ecd38cb2b1e60857a20edef/crates/cairo-lang-semantic/src/diagnostic.rs#L813)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

The issue is that it is not clear what the error is.
</blockquote></details>

yeah you're right

what about?

```
invalid path syntax, use `::<...>` instead of `<...>` to specify...
```

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5926)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 813 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5926#-O0iGuW4BZ6XbH0YWcIm:-O0iKH6mA6rP4U18L7Ms:b6rvfyg) ([raw file](https://github.com/starkware-libs/cairo/blob/37645bd0f34277480ecd38cb2b1e60857a20edef/crates/cairo-lang-semantic/src/diagnostic.rs#L813)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

yeah you're right

what about?

```
invalid path syntax, use `::<...>` instead of `<...>` to specify...
```
</blockquote></details>

though I do not want to block this, so we can ignore this comment

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 813 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5926#-O0iGuW4BZ6XbH0YWcIm:-O0iOKb8617CcVgIPluJ:b-j2k6dc) ([raw file](https://github.com/starkware-libs/cairo/blob/37645bd0f34277480ecd38cb2b1e60857a20edef/crates/cairo-lang-semantic/src/diagnostic.rs#L813)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

though I do not want to block this, so we can ignore this comment
</blockquote></details>

Are you confident that if you have
a < b 
and you can't resolve 'a', then the issue is missing `::`?

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5926)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5926)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 813 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5926#-O0iGuW4BZ6XbH0YWcIm:-O0iOqYC46O2M-92KMpc:bsvseif) ([raw file](https://github.com/starkware-libs/cairo/blob/37645bd0f34277480ecd38cb2b1e60857a20edef/crates/cairo-lang-semantic/src/diagnostic.rs#L813)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Are you confident that if you have
a < b 
and you can't resolve 'a', then the issue is missing `::`?
</blockquote></details>

hmm, no I cannot be certain. there would have to be a matching `>` to be certain I think

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 813 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5926#-O0iGuW4BZ6XbH0YWcIm:-O0iSPZ13AjRIEHDoCAD:b-j5auje) ([raw file](https://github.com/starkware-libs/cairo/blob/37645bd0f34277480ecd38cb2b1e60857a20edef/crates/cairo-lang-semantic/src/diagnostic.rs#L813)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

hmm, no I cannot be certain. there would have to be a matching `>` to be certain I think
</blockquote></details>

I think we will have to change the parser to be sure about the error here.

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5926)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 813 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5926#-O0iGuW4BZ6XbH0YWcIm:-O0iUgYe7Bown4p5C68s:bwbq2o4) ([raw file](https://github.com/starkware-libs/cairo/blob/37645bd0f34277480ecd38cb2b1e60857a20edef/crates/cairo-lang-semantic/src/diagnostic.rs#L813)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I think we will have to change the parser to be sure about the error here.
</blockquote></details>

makes sense. ignore my comment then

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5926)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 813 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5926#-O0iDfZJEyN9HwCjDoFD:-O0lwMvQDxG07WksgWkt:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/37645bd0f34277480ecd38cb2b1e60857a20edef/crates/cairo-lang-semantic/src/diagnostic.rs#L813)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Yeah, makes sense
</blockquote></details>

done

**Pull request merged**
