### PR TITLE
LS: Add submitting issues section

### PR DESCRIPTION
**Pull request by Arcticae**

### CODE REVIEW

**Review by piotmag769 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6532)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Draggu, @mkaput, and @orizi)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6532#-:-OANY_Il7dgu32q_8b3y:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Draggu and @mkaput)

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6532)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae and @Draggu)

___
*[`vscode-cairo/README.md` line 99 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6532#-OANeRZm4-SdJGhoyziG:-OANeRZm4-SdJGhoyziH:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/4d6bb7dacad0e800a50b2692788b0b0fb387ae03/vscode-cairo/README.md#L99)):*
> ```Markdown
>    - Scarb version (which version or which nightly?), or commit reference (if built locally)
>    - Relevant `Cairo` extension VSCode configuration
>    - `Cairo` extension version
> ```





_Suggestion:_
```Markdown
5. Do not forget to attach context like:
   - Scarb version (which version or which nightly?), or commit reference (if built locally),
   - relevant `Cairo` extension VSCode configuration,
   - `Cairo` extension version.
```

**Review by Arcticae — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6532)* status: all files reviewed, 1 unresolved discussion (waiting on @Draggu and @mkaput)

___
*[`vscode-cairo/README.md` line 99 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6532#-OANeRZm4-SdJGhoyziG:-OAO0G0x0qISywiuvZYF:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4d6bb7dacad0e800a50b2692788b0b0fb387ae03/vscode-cairo/README.md#L99)):*
> ```Markdown
>    - Scarb version (which version or which nightly?), or commit reference (if built locally)
>    - Relevant `Cairo` extension VSCode configuration
>    - `Cairo` extension version
> ```

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6532)* status: all files reviewed, 1 unresolved discussion (waiting on @Draggu and @mkaput)

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6532#-:-OAONa169MNtb2WTp6lW:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Draggu)

**Pull request merged**
