### PR TITLE
Fix stack tracking bug.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4263)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4263)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/state.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4263#-NgrLPFE4ycGyi9yFo6h:-NgrLPFE4ycGyi9yFo6i:b-g9f5u6) ([raw file](https://github.com/starkware-libs/cairo/blob/f61e967a668ec1a1e43148cf498a2df3d660db26/crates/cairo-lang-sierra-generator/src/store_variables/state.rs#L121)):*
> ```XML
>                 match &arg_states[*param_idx] {
>                     VarState::TempVar { .. } => {
>                         if matches!(
> ```

the original code is here:
https://github.com/starkware-libs/cairo/blob/76d37bc6214d207fb437e5fbb7c15d43da270562/crates/cairo-lang-sierra-generator/src/store_variables/state.rs#L112



_Code quote:_
```XML
  if matches!(
```

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4263)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/state.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4263#-NgrLPFE4ycGyi9yFo6h:-NgsoYJX5V92a9k4_2hp:b-n1k913) ([raw file](https://github.com/starkware-libs/cairo/blob/f61e967a668ec1a1e43148cf498a2df3d660db26/crates/cairo-lang-sierra-generator/src/store_variables/state.rs#L121)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

the original code is here:
https://github.com/starkware-libs/cairo/blob/76d37bc6214d207fb437e5fbb7c15d43da270562/crates/cairo-lang-sierra-generator/src/store_variables/state.rs#L112
</blockquote></details>

add some documentation here as to why you are doing this.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4263#-:-NgwOhLECbD7KNfFujSP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4263)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
