### PR TITLE
Add function to compile prepared db with debug info

### PR DESCRIPTION
**Pull request by barabanovro**
This PR adds the `compile_prepared_db_with_debug_info` function to `cairo-lang-compiler`, allowing the compilation of programs and the retrieval of debug information.

This PR will enable [cairovm.codes](https://cairovm.codes/) to display Cairo function names in a callstack.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5157)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5157)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @barabanovro)

___
*[`crates/cairo-lang-compiler/src/lib.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5157#-NrkGB-o-OZmbgFZKJ-1:-NrkGB-o-OZmbgFZKJ-2:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/2b706db9eaf9a80838066634955764db61edc919/crates/cairo-lang-compiler/src/lib.rs#L104)):*
> ```XML
>         compile_prepared_db_with_debug_info(db, main_crate_ids, compiler_config)?;
> 
>     Ok(sierra_program)
> ```

.



_Suggestion:_
```XML
    Ok(compile_prepared_db_with_debug_info(db, main_crate_ids, compiler_config)?.sierra_program)
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5157#-:-Nro42oo7suKyQRTCdqv:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barabanovro)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5157#-Nro44cv09BJiuNBP9Y9:-Nro44cv09BJiuNBP9YA:bpx0xxa) (no related file):*
@yuvalsw for 2nd eye.

___

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5157)* status: all files reviewed, 1 unresolved discussion (waiting on @barabanovro)

___
*[`crates/cairo-lang-compiler/src/lib.rs` line 115 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5157#-NsI6LUg74IgZP_tbvkR:-NsI6LUg74IgZP_tbvkS:b-eoj83f) ([raw file](https://github.com/starkware-libs/cairo/blob/635180d3578a053c5fab58116e8249152f5086a4/crates/cairo-lang-compiler/src/lib.rs#L115)):*
> ```XML
> /// * `Ok(SierraProgramWithDebug)` - The compiled program with debug info.
> /// * `Err(anyhow::Error)` - Compilation failed.
> pub fn compile_prepared_db_with_debug_info(
> ```

"with debug info" sounds like it gets it as an additional input.
I'd just call it `compile_prepared_db_ex`.

Also, please add in the beginning of the comment something like "same as `compile_prepared_db`, but returns all the raw debug info".

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5157)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)

___
*[`crates/cairo-lang-compiler/src/lib.rs` line 115 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5157#-NsI6LUg74IgZP_tbvkR:-NsN3ER080CFobdkONH-:bpvbery) ([raw file](https://github.com/starkware-libs/cairo/blob/635180d3578a053c5fab58116e8249152f5086a4/crates/cairo-lang-compiler/src/lib.rs#L115)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I disagree with the `_ex` prefix. Sounds very WinAPI-style and it doesn't convey any meaning IMO.

I think what ultimately would be much better, is simply return debug info from the main function, and let downstream users pick what they need. I know this is a breaking change, but we allow ourselves to do them in our APIs, aren't we?
</blockquote></details>

Calling this function with the original name is ok. I wouldn't worry about the breaking change but if there are many calls to the existing function it would be nice for them to have a wrapper/selector that takes only the program.
I am ok with other names, just "with_debug_info_ sounds like it's another input to the compilation rather than an output.

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5157)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-compiler/src/lib.rs` line 115 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5157#-NsI6LUg74IgZP_tbvkR:-NsN4Jiv28Sxj3_QUpw3:b-ote0k3) ([raw file](https://github.com/starkware-libs/cairo/blob/635180d3578a053c5fab58116e8249152f5086a4/crates/cairo-lang-compiler/src/lib.rs#L115)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Calling this function with the original name is ok. I wouldn't worry about the breaking change but if there are many calls to the existing function it would be nice for them to have a wrapper/selector that takes only the program.
I am ok with other names, just "with_debug_info_ sounds like it's another input to the compilation rather than an output.
</blockquote></details>

Perhaps having a `impl From<SierraProgramWithDebug> for SierraProgram` could do the job?

**Comment by mazurroman** [comment]
Thank you @mkaput and @yuvalsw for your reviews and feedback. Please note @barabanovro is currently off and will get back to this after March 18th.

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5157)* status: all files reviewed, 1 unresolved discussion (waiting on @barabanovro)

**Review by barabanovro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5157)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mkaput, @orizi, and @yuvalsw)

___
*[`crates/cairo-lang-compiler/src/lib.rs` line 115 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5157#-NsI6LUg74IgZP_tbvkR:-NtFM3hA4MPCDCDK65Ar:b-ovtf6m) ([raw file](https://github.com/starkware-libs/cairo/blob/635180d3578a053c5fab58116e8249152f5086a4/crates/cairo-lang-compiler/src/lib.rs#L115)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I like it less, but I'll leave you guys to choose the names, I am ok with anything that makes sense.
One suggestion could be calling the original one "compile_prepared_db_program" and this one "compile_prepared_db", if you like it.
</blockquote></details>

I have renamed functions to `compile_prepared_db_program` and `compile_prepared_db` as @yuvalsw  suggested.

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5157#-:-NtGJG0x3hLjvJ-GQ-RJ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barabanovro)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5157)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @barabanovro, @mkaput, and @yuvalsw)

___
*[`crates/cairo-lang-compiler/src/lib.rs` line 106 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5157#-NtL8T0FA9uQ_cO81GM-:-NtL8T0G--0puQu7E-Jv:b2ni2qw) ([raw file](https://github.com/starkware-libs/cairo/blob/8baf0a299dc20c9fac9a2e45726b2bda32c8ea29/crates/cairo-lang-compiler/src/lib.rs#L106)):*
> ```XML
> /// Runs Cairo compiler.
> ///
> /// Similar to `compile_prepared_db_program`, but this function returns all the raw debug information.
> ```

fmt



_Code quote:_
```XML
/// Similar to `compile_prepared_db_program`, but this function returns all the raw debug information.
```

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5157)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barabanovro)

**Pull request merged**
