### PR TITLE
Broader impl lookup

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1870)

### CODE REVIEW

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1870#-:-NMXc-5FC3xJxi0nU4Wk:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @liorgold2, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 445 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1870#-NMXbuFz7nQjy4jBUhMa:-NMXbuFz7nQjy4jBUhMb:b-gqplcy) ([raw file](https://github.com/starkware-libs/cairo/blob/e9695c6311211e0089d5db5f0a320ec1ec775987/crates/cairo-lang-semantic/src/items/imp.rs#L445)):*
> ```XML
> 
>     let mut impls = db.module_impls_ids(module_id)?;
>     for use_id in db.module_uses_ids(module_id)? {
> ```

This code repeats iteself, shouldn't we have a query that resolves all the use_ids?



_Code quote:_
```XML
for use_id in db.module_uses_ids(module_id)
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1870)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ilyalesokhin-starkware, @liorgold2, and @orizi)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 445 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1870#-NMXbuFz7nQjy4jBUhMa:-NMXloXe7zim85vCIhMQ:b8ndym0) ([raw file](https://github.com/starkware-libs/cairo/blob/e9695c6311211e0089d5db5f0a320ec1ec775987/crates/cairo-lang-semantic/src/items/imp.rs#L445)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

This code repeats iteself, shouldn't we have a query that resolves all the use_ids?
</blockquote></details>

We should, definitely, eventually..

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1870)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1870#-:-NMXm74s9XkNGPdbwHYN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1870)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
