### PR TITLE
Added resolution of trait functions to the relevant impl function.

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1794)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1794)* status: 3 of 8 files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 309 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1794#-NM30p95-JhCLetW5C1X:-NM30p95-JhCLetW5C1Y:bwvjttt) ([raw file](https://github.com/starkware-libs/cairo/blob/cd84dd4eee02fee0067ad1d44035d6d3b434b134/crates/cairo-lang-semantic/src/db.rs#L309)):*
> ```XML
>     /// Returns the function with the given name of the given impl, if exists.
>     #[salsa::invoke(items::imp::impl_function_by_name)]
>     fn impl_function_by_name(
> ```

I would rather we use ids rather than names when possible. So, instead of name, maybe get a TraitFunctionId?
___
*[`crates/cairo-lang-semantic/src/resolve_path.rs` line 430 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1794#-NM31RwG54_Gr0Ouhtdp:-NM31RwH4YG5UOgFo4Ql:b-dghkl2) ([raw file](https://github.com/starkware-libs/cairo/blob/cd84dd4eee02fee0067ad1d44035d6d3b434b134/crates/cairo-lang-semantic/src/resolve_path.rs#L430)):*
> ```XML
>                 }
>             }
>             ResolvedConcreteItem::Trait(concrete_trait_id) => {
> ```

I tihnk we shoudl resolve the trait sooner. There shouldnt be a ResolvedConcreteItem::Trait (just for generic). When the concrete resolving reaches a trait, it should already try to resolve the impl at that point.

Also note that we have 2 lookbacks, for generic and for concrete.
The generic should be resolved to the trait, and the concrete to the impl (I imagine that would translate to a "Goto definition" vs "Goto declaration" in the language server).



_Code quote:_
```XML
ResolvedConcreteItem::Trait
```
___
*[`crates/cairo-lang-semantic/src/resolve_path.rs` line 431 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1794#-NM31-BB9vmO4NZeRNMQ:-NM31-BB9vmO4NZeRNMR:b2x1t3y) ([raw file](https://github.com/starkware-libs/cairo/blob/cd84dd4eee02fee0067ad1d44035d6d3b434b134/crates/cairo-lang-semantic/src/resolve_path.rs#L431)):*
> ```XML
>             }
>             ResolvedConcreteItem::Trait(concrete_trait_id) => {
>                 // No need to check that the function exists in the trait, it is previously verified
> ```

I tihnk we should first get the TraitFunctionId from the trait.
Consider the case of associated types and constant. We first need to understand what kind of assocaited item is this inside the trait, then understand how to resolve it.

Also, I think it;s kind of dangerous to rely on the impl being compatible with the trait, as it can be not the case. We are in the semantic model, and we want as much information as possible even if some things are wrong.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1794)* status: 3 of 8 files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/resolve_path_test.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1794#-NM32AYu9OTDgp4ZPFd0:-NM32AYu9OTDgp4ZPFd1:bkca7ym) ([raw file](https://github.com/starkware-libs/cairo/blob/cd84dd4eee02fee0067ad1d44035d6d3b434b134/crates/cairo-lang-semantic/src/resolve_path_test.rs#L114)):*
> ```XML
>     let test_module = setup_test_module(
>         db,
>         indoc! {"
> ```

Super cool!

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1794)* status: 3 of 8 files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 238 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1794#-NM32VN9EpQyjXTUEsve:-NM32VN9EpQyjXTUEsvf:b32w5f8) ([raw file](https://github.com/starkware-libs/cairo/blob/cd84dd4eee02fee0067ad1d44035d6d3b434b134/crates/cairo-lang-semantic/src/items/imp.rs#L238)):*
> ```XML
>     .ok();
> 
>     // TODO(yuval): verify that all functions of `concrete_trait` appear in this impl.
> ```

1. Do we want verify the impl-trait compatibility and report already?
2. Make sure to still return as much valid informaton as possible. So, if the impl has some of the correct functions, return them.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1794)* status: 3 of 8 files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 238 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1794#-NM32VN9EpQyjXTUEsve:-NM32jkS6_fxwYq3zCDW:b-k00kir) ([raw file](https://github.com/starkware-libs/cairo/blob/cd84dd4eee02fee0067ad1d44035d6d3b434b134/crates/cairo-lang-semantic/src/items/imp.rs#L238)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

1. Do we want verify the impl-trait compatibility and report already?
2. Make sure to still return as much valid informaton as possible. So, if the impl has some of the correct functions, return them.
</blockquote></details>

1. I meant, "Don't we have this already"?

**Review by spapinistarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1794)* status: 3 of 8 files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1794)* status: 3 of 8 files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 309 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1794#-NM30p95-JhCLetW5C1X:-NM4-N8mBX1mn5irI1rh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cd84dd4eee02fee0067ad1d44035d6d3b434b134/crates/cairo-lang-semantic/src/db.rs#L309)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I would rather we use ids rather than names when possible. So, instead of name, maybe get a TraitFunctionId?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/resolve_path.rs` line 430 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1794#-NM31RwG54_Gr0Ouhtdp:-NM4-SC92JBRN6UifQOK:bn4629l) ([raw file](https://github.com/starkware-libs/cairo/blob/cd84dd4eee02fee0067ad1d44035d6d3b434b134/crates/cairo-lang-semantic/src/resolve_path.rs#L430)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I tihnk we shoudl resolve the trait sooner. There shouldnt be a ResolvedConcreteItem::Trait (just for generic). When the concrete resolving reaches a trait, it should already try to resolve the impl at that point.

Also note that we have 2 lookbacks, for generic and for concrete.
The generic should be resolved to the trait, and the concrete to the impl (I imagine that would translate to a "Goto definition" vs "Goto declaration" in the language server).
</blockquote></details>

As discussed, we decided to move the resolution to later rather than sooner. Done.
___
*[`crates/cairo-lang-semantic/src/resolve_path.rs` line 431 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1794#-NM31-BB9vmO4NZeRNMQ:-NM4-_TZ2DbHglb6i9bj:b2nhb2c) ([raw file](https://github.com/starkware-libs/cairo/blob/cd84dd4eee02fee0067ad1d44035d6d3b434b134/crates/cairo-lang-semantic/src/resolve_path.rs#L431)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I tihnk we should first get the TraitFunctionId from the trait.
Consider the case of associated types and constant. We first need to understand what kind of assocaited item is this inside the trait, then understand how to resolve it.

Also, I think it;s kind of dangerous to rely on the impl being compatible with the trait, as it can be not the case. We are in the semantic model, and we want as much information as possible even if some things are wrong.
</blockquote></details>

Ack
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 238 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1794#-NM32VN9EpQyjXTUEsve:-NM4-j2N1IbN0M_hZ-i6:b-lyubp8) ([raw file](https://github.com/starkware-libs/cairo/blob/cd84dd4eee02fee0067ad1d44035d6d3b434b134/crates/cairo-lang-semantic/src/items/imp.rs#L238)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

1. I meant, "Don't we have this already"?
</blockquote></details>

We don't have this AFAICT. This remains a TODO in This PR. I have a separate PR for this verification. But maybe I need to rethink it in regards to default trait function implementations.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 8 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1794#-:-NM4ABHW9frpdbBVsGT7:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 272 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1794#-NM4A8_hDOcKB6dSk95Y:-NM4A8_hDOcKB6dSk95Z:bf60gvj) ([raw file](https://github.com/starkware-libs/cairo/blob/535b98bcd5f7bd40c8e1388b9b6ef231b0dc1381/crates/cairo-lang-semantic/src/diagnostic.rs#L272)):*
> ```XML
>                     all_impl_ids.iter().map(|imp| imp.full_path(db.upcast())).join(", ");
>                 format!(
>                     r#"Function `{function_name}` of trait `{trait_path}` has multiple implementations, in: {impls_str}"#,
> ```

Line too long

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 3 of 8 files at r1, 7 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1794)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by yuvalsw — COMMENTED** [review]
> Dismissed @spapinistarkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1794)* status: 7 of 11 files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 1 of 8 files at r1, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1794)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
