### PR TITLE
Added uint256 mul.

### PR DESCRIPTION
**Pull request by orizi**
Fixing nopanic and implicits to be minimal in the corelib.
commit-id:93e958a8

---

**Stack**:
- #1232
- #1231 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1231)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @spapinistarkware)

___
*[`corelib/integer.cairo` line 163 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1231#-NIaj07K4TAw_8pVzhlR:-NIaj07K4TAw_8pVzhlS:br1areg) ([raw file](https://github.com/starkware-libs/cairo/blob/b513ada4ff689278de0f9575c82d85586ffcb83a/corelib/integer.cairo#L163)):*
> ```Cairo
> 
> // TODO(orizi): Change to extern when added.
> func uint128_eq(a: uint128, b: uint128) -> bool implicits(RangeCheck) nopanic {
> ```

why is range check needed here?



_Code quote:_
```Cairo
implicits(RangeCheck)
```
___
*[`corelib/integer.cairo` line 207 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1231#-NIakhpY2US3SJvhB8SF:-NIakhpY2US3SJvhB8SG:b-gb1utv) ([raw file](https://github.com/starkware-libs/cairo/blob/b513ada4ff689278de0f9575c82d85586ffcb83a/corelib/integer.cairo#L207)):*
> ```Cairo
>     let u0 = uint128_from_felt_or(0, a.low);
>     let (low, high1) = uint128_wide_mul(a.low, b.low);
>     let (high2, overflow1) = uint128_wide_mul(a.low, b.high);
> ```

calling this `overflow1` is misleading IMO, because it looks like you meant to call `uint128_overflow_mul`. Maybe `overflow_value1`?
ditto on `overflow2`



_Code quote:_
```Cairo
let (high2, overflow1) = uint128_wide_mul(a.low, b.high);
```
___
*[`corelib/test.cairo` line 199 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1231#-NIamHhw6g2WkFyT5xh-:-NIamHhw6g2WkFyT5xh0:bj72qc8) ([raw file](https://github.com/starkware-libs/cairo/blob/b513ada4ff689278de0f9575c82d85586ffcb83a/corelib/test.cairo#L199)):*
> ```Cairo
> #[should_panic]
> func test_uint256_mul_overflow() {
>     as_uint256(1, 1) * as_uint256(1, 2);
> ```

consider adding a test where at least on of the `high`s is zero but there is still overflow



_Code quote:_
```Cairo
#[test]
#[should_panic]
func test_uint256_mul_overflow() {
    as_uint256(1, 1) * as_uint256(1, 2);
}
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1231)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1231)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @ilyalesokhin-starkware, and @spapinistarkware)

___
*[`corelib/integer.cairo` line 207 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1231#-NIakhpY2US3SJvhB8SF:-NIavEEF9LdQAjd3LQ-x:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c1e9eb6751fe5328a41631d8baa07ea2b9014727/corelib/integer.cairo#L207)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

calling this `overflow1` is misleading IMO, because it looks like you meant to call `uint128_overflow_mul`. Maybe `overflow_value1`?
ditto on `overflow2`
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1231)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware, @orizi, and @spapinistarkware)

___
*[`corelib/test.cairo` line 205 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1231#-NIb0nFg6yxN1KV-2TMX:-NIb0nFg6yxN1KV-2TMY:buqzk4l) ([raw file](https://github.com/starkware-libs/cairo/blob/00e16da41339c71f23d4c798d1414a65512b0fac/corelib/test.cairo#L205)):*
> ```Cairo
> #[should_panic]
> func test_uint256_mul_overflow_2() {
>     as_uint256(0, 170141183460469231731687303715884105728) * as_uint256(2, 0);
> ```

pow_2_127_plus(0)



_Suggestion:_
```Cairo
pow_2_127_plus(0)
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1231)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @ilyalesokhin-starkware, and @spapinistarkware)

___
*[`corelib/test.cairo` line 205 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1231#-NIb0nFg6yxN1KV-2TMX:-NIbTtP95Mv8A0fZIO75:b1hl9ey) ([raw file](https://github.com/starkware-libs/cairo/blob/fc1b0498d89edd36ca14011220199ac50bd41e87/corelib/test.cairo#L205)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

pow_2_127_plus(0)
</blockquote></details>

it returns a uint - not a felt - will solve after literals.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1231#-:-NIbhZuC3Axy_cWj4c3H:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware and @spapinistarkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1231)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware and @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1231)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ilyalesokhin-starkware and @spapinistarkware)

**Pull request merged**
