### PR TITLE
Feat: support format!("{:x}") notation for hexadecimal formatting

### PR DESCRIPTION
**Pull request by remybar**
Proposal for issue https://github.com/starkware-libs/cairo/issues/6261.

This PR adds a `LowerHex` trait as existing in Rust, to be able to format integer values to hexadecimal using the `{:x}` notation. Rust also provides a `UpperHex` trait to format the string in upper case but I don't know if it's really useful.

This PR also implements this trait for:
- unsigned integers (from `u8` to `u256`),
- felt252
- `NonZero`
- common Starknet types such as `ContractAddress` and `ClassHash` using the existing `into_felt252_based` module.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6297)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6297)* status: 3 of 8 files reviewed, 4 unresolved discussions (waiting on @remybar)

___
*[`Cargo.lock` line 241 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6297#-O5MViZy1bvt_FIIyVbV:-O5MViZy1bvt_FIIyVbW:b9sid17) ([raw file](https://github.com/starkware-libs/cairo/blob/449ab330c99c9b2f7a772370edb04ab4c6e14859/Cargo.lock#L241)):*
> ```TOML
> ]
> 
> [[package]]
> ```

revert file.
___
*[`corelib/src/fmt.cairo` line 320 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6297#-O5MVLe15bYs91RR0fI9:-O5MVLe15bYs91RR0fIA:b-yot0wz) ([raw file](https://github.com/starkware-libs/cairo/blob/449ab330c99c9b2f7a772370edb04ab4c6e14859/corelib/src/fmt.cairo#L320)):*
> ```Cairo
> > of LowerHex<T> {
>     fn fmt(self: @T, ref f: Formatter) -> Result<(), Error> {
>         f.buffer.append(@"0x");
> ```

shouldn't be part of it. same as rust.



_Code quote:_
```Cairo
        f.buffer.append(@"0x");
```
___
*[`crates/cairo-lang-semantic/src/inline_macros/write.rs` line 142 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6297#-O5MUxKo6WSAbSvyh6Cw:-O5MUxKo6WSAbSvyh6Cx:b8d7f80) ([raw file](https://github.com/starkware-libs/cairo/blob/449ab330c99c9b2f7a772370edb04ab4c6e14859/crates/cairo-lang-semantic/src/inline_macros/write.rs#L142)):*
> ```XML
>         WriteMacro::NAME
>     }
> }
> ```

run the same rust fmt as the CI.
(`./script/rust_fmt.sh`)



_Code quote:_
```XML
fn get_macro_name(with_newline: bool) -> &'static str {
    if with_newline {
        WritelnMacro::NAME
    } else {
        WriteMacro::NAME
    }
}
```
___
*[`crates/cairo-lang-semantic/src/inline_macros/write.rs` line 527 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6297#-O5MUa670pMCYcf4cXvk:-O5MUa68ETtOT5iyLUZ2:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/449ab330c99c9b2f7a772370edb04ab4c6e14859/crates/cairo-lang-semantic/src/inline_macros/write.rs#L527)):*
> ```XML
>     } else {
>         return Err("Unsupported formatting trait: only `Display` and `Debug` are supported");
>     };
> ```





_Suggestion:_
```XML
    let fmt_type = match formatting_spec.as_str() {
        "" => FormattingTrait::Display,
        "?" => FormattingTrait::Debug,
        "x" => FormattingTrait::LowerHex,
        _ => return Err("Unsupported formatting trait: only `Display`, `Debug` and `LowerHex` are supported"),
    };
```

**Comment by remybar** [comment]
Hi @orizi !

Thanks for the review. I did the required changes.

**Review by orizi — COMMENTED** [review]
please view at reviewable: https://reviewable.io/reviews/starkware-libs/cairo/6297#-

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6297#-:-O5NsEauBsJajRGYA-7t:b2oxppm)* status: 4 of 8 files reviewed, 1 unresolved discussion (waiting on @remybar)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6297#-:-O5NsxhACs6JpLP92vBl:bnfp4nl)* status: 4 of 8 files reviewed, 1 unresolved discussion (waiting on @remybar)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6297#-O5Nsy503rqDs7oCW8bY:-O5Nsy503rqDs7oCW8bZ:b-uuj1x0) (no related file):*
@gilbens-starkware for 2nd eye.

___

**Comment by remybar** [comment]
> why not match?

Because I didn't noticed the `match` but just the change related to the error message... 🫣
Sorry, I also replaced the if/else by a match as suggested ;-)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6297#-:-O5OZGcE97bwEF9_O1Eg:bnfp4nl)* status: 4 of 8 files reviewed, 1 unresolved discussion (waiting on @orizi and @remybar)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 8 files at r1, 1 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6297)* status: all files reviewed, 1 unresolved discussion (waiting on @remybar)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6297)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @remybar)

**Review by orizi — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6297)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @remybar)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6297)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @remybar)

**Pull request merged**
