### PR TITLE
Add dict_squash libfunc to Sierra

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1101)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1101)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/sierra/src/extensions/modules/dict_felt_to.rs` line 166 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1101#-NHxGVkTB9UOx6kZSgPv:-NHxGVkU12Bm6a2pzZxF:b-rba5z0) ([raw file](https://github.com/starkware-libs/cairo/blob/c397c81f07882c197b66885f4768ef6450ad6f77/crates/sierra/src/extensions/modules/dict_felt_to.rs#L166)):*
> ```XML
>                 ref_info: OutputVarReferenceInfo::Deferred(DeferredOutputKind::Generic),
>             }],
>             SierraApChange::Known(1),
> ```

pretty sure, as this is a function with loops.



_Suggestion:_
```XML
Unknown
```
___
*[`crates/sierra_gas/src/core_libfunc_cost_base.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1101#-NHxGEKD0IrR9FTW4rxJ:-NHxGEKEDVkxYkTVlJEM:b8737q9) ([raw file](https://github.com/starkware-libs/cairo/blob/c397c81f07882c197b66885f4768ef6450ad6f77/crates/sierra_gas/src/core_libfunc_cost_base.rs#L80)):*
> ```XML
>         }
>         DictFeltTo(DictFeltToConcreteLibFunc::Squash(_)) => {
>             // TODO(Gil): add the cost of dict squash, it's complicated since it depands on the size
> ```

the cost is indeed 0 - we pay for it while performing new read and write.
squash should always be callable.



_Code quote:_
```XML
            // TODO(Gil): add the cost of dict squash, it's complicated since it depands on the size
            // of the dict, but maybe we want to just amortize it with read and write.
```

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1101)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/sierra/src/extensions/modules/dict_felt_to.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1101#-NHxRrBx6BWcjfJ4buls:-NHxRrBy6qMKJoi0KSmn:brozln6) ([raw file](https://github.com/starkware-libs/cairo/blob/98a1c66a7593ff7739c403295fda13338f1d1336/crates/sierra/src/extensions/modules/dict_felt_to.rs#L163)):*
> ```XML
>             vec![dict_ty.clone()],
>             vec![OutputVarInfo {
>                 ty: dict_ty,
> ```

i believe the correct return type is a sorted Array<(key, value)>
or something of that sort - in anyway - not a dict.



_Code quote:_
```XML
dict_ty
```
___
*[`crates/sierra/src/simulation/core.rs` line 193 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1101#-NHxRiEu2KJG62K-gyU-:-NHxRiEv3A8CQkVg3_w6:b-zc8vwo) ([raw file](https://github.com/starkware-libs/cairo/blob/98a1c66a7593ff7739c403295fda13338f1d1336/crates/sierra/src/simulation/core.rs#L193)):*
> ```XML
>             _ => Err(LibFuncSimulationError::WrongNumberOfArgs),
>         },
>         CoreConcreteLibFunc::DictFeltTo(DictFeltToConcreteLibFunc::Squash(_)) => todo!(),
> ```

as long as you know what it actually returns - sim should be easy.



_Code quote:_
```XML
todo!()
```
___
*[`crates/sierra_gas/src/core_libfunc_cost_base.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1101#-NHxGEKD0IrR9FTW4rxJ:-NHxSDXR03Pq0BtcS04T:b-5k4mmj) ([raw file](https://github.com/starkware-libs/cairo/blob/c397c81f07882c197b66885f4768ef6450ad6f77/crates/sierra_gas/src/core_libfunc_cost_base.rs#L80)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

I changed the comment to add this with the casm since it'll be much easier to follow the casm once it'll be integrated with the rest of the functions.
</blockquote></details>

still a 0 here - add the todo to update.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1101)* status: 2 of 8 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/sierra/src/extensions/modules/dict_felt_to.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1101#-NHxRrBx6BWcjfJ4buls:-NI37cpt4pThrGKAkiKl:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/98a1c66a7593ff7739c403295fda13338f1d1336/crates/sierra/src/extensions/modules/dict_felt_to.rs#L163)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i believe the correct return type is a sorted Array<(key, value)>
or something of that sort - in anyway - not a dict.
</blockquote></details>

Done.
___
*[`crates/sierra/src/simulation/core.rs` line 193 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1101#-NHxRiEu2KJG62K-gyU-:-NI37fTGCxHqiqXztfdx:b-cuegnq) ([raw file](https://github.com/starkware-libs/cairo/blob/98a1c66a7593ff7739c403295fda13338f1d1336/crates/sierra/src/simulation/core.rs#L193)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

as long as you know what it actually returns - sim should be easy.
</blockquote></details>

I'll know it exactly only after the casm implementation.
___
*[`crates/sierra_gas/src/core_libfunc_cost_base.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1101#-NHxGEKD0IrR9FTW4rxJ:-NI37tS46sHNnOSxrlBX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c397c81f07882c197b66885f4768ef6450ad6f77/crates/sierra_gas/src/core_libfunc_cost_base.rs#L80)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

still a 0 here - add the todo to update.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1101)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/sierra/src/simulation/core.rs` line 193 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1101#-NHxRiEu2KJG62K-gyU-:-NI3Xxu61FfkgAQjPw3-:b-shg19m) ([raw file](https://github.com/starkware-libs/cairo/blob/98a1c66a7593ff7739c403295fda13338f1d1336/crates/sierra/src/simulation/core.rs#L193)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

I'll know it exactly only after the casm implementation.
</blockquote></details>

just return the same underlying dictionary - it is a good enough sim for the squashed dict.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1101)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/sierra/src/simulation/core.rs` line 193 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1101#-NHxRiEu2KJG62K-gyU-:-NI6gLhW-OxWwHEReNXM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/98a1c66a7593ff7739c403295fda13338f1d1336/crates/sierra/src/simulation/core.rs#L193)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

just return the same underlying dictionary - it is a good enough sim for the squashed dict.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1101#-:-NI6pCTi6lQ-_xNG1WjN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
