### PR TITLE
LS supports inline modules and starknet

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1567)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1567#-:-NKSbq-L25_mDFDBpPmM:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-starknet/src/db.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1567#-NKSbl7lDGUkERdxKPHT:-NKSbl7lDGUkERdxKPHU:b-my4i5w) ([raw file](https://github.com/starkware-libs/cairo/blob/d9fd65bd844500d6df394c180b93e0b7cde575c5/crates/cairo-starknet/src/db.rs#L12)):*
> ```XML
> use crate::plugin::StarkNetPlugin;
> 
> pub fn get_database() -> RootDatabase {
> ```

Doc what is special about the db here.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1567)* status: 6 of 9 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware, @orizi, and @yuvalsw)

___
*[`crates/cairo-starknet/src/db.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1567#-NKSbl7lDGUkERdxKPHT:-NKScNaV8EpbpwJloKV6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d9fd65bd844500d6df394c180b93e0b7cde575c5/crates/cairo-starknet/src/db.rs#L12)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Doc what is special about the db here.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1567)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware and @yuvalsw)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 6 of 9 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1567)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware, @orizi, and @yuvalsw)

**Pull request merged**
