### PR TITLE
dev: Result unwrap_or, unwrap_or_default

### PR DESCRIPTION
**Pull request by milancermak**
Adds `unwrap_or` and `unwrap_or_default` to `Result`.

Also a full unit test suite for `Result`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4815)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4815)* status: all files reviewed, 1 unresolved discussion (waiting on @milancermak)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4815#-NoLRCf91NsrTQeoXnsV:-NoLRCf91NsrTQeoXnsW:bk3gsrs) (no related file):*
@ilyalesokhin-starkware for 2nd eye

___

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4815)* status: all files reviewed, 2 unresolved discussions (waiting on @milancermak)

___
*[`corelib/src/result.cairo` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4815#-NoMj5m_99-KDY3Cn2sx:-NoMj5maDLI8hfT-bbbm:b-fuz4yd) ([raw file](https://github.com/starkware-libs/cairo/blob/769587d7c549aeb395ebe64212f3896c056b3597/corelib/src/result.cairo#L36)):*
> ```Cairo
>     fn unwrap_or_default<+Drop<T>, +Drop<E>, +Default<T>>(self: Result<T, E>) -> T {
>         self.unwrap_or(Default::default())
>     }
> ```

`Drop<T>` is not really needed.



_Suggestion:_
```Cairo
    fn unwrap_or_default<+Drop<E>, +Default<T>>(self: Result<T, E>) -> T {
        match self {
            Result::Ok(x) => x,
            Result::Err(_) => Default::default(),
        }
    }
```

**Review by milancermak — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4815)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`corelib/src/result.cairo` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4815#-NoMj5m_99-KDY3Cn2sx:-NoMqOpa7t43lzG2xw_z:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/769587d7c549aeb395ebe64212f3896c056b3597/corelib/src/result.cairo#L36)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

`Drop<T>` is not really needed.
</blockquote></details>

Done.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4815#-:-NoN0pM32G0qtJc5Sjrm:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @milancermak)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4815#-:-NoNAkiY4OcH3DjcC84M:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @milancermak)

**Pull request merged**
