### PR TITLE
Added a constructor submodule.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:9e9c2934

---

**Stack**:
- #1866
- #1864
- #1863
- #1862
- #1860
- #1857
- #1855 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1855#-NMS8GA25Xbbu92ZrH04:-NMS8GA25Xbbu92ZrH05:b-a7utbq) ([raw file](https://github.com/starkware-libs/cairo/blob/8d73fd50dacccab622407004d17299d49a7741ce/crates/cairo-lang-starknet/src/contract_class.rs#L112)):*
> ```XML
>         external: get_entry_points(db, &external_functions, &replacer)?,
>         l1_handler: vec![],
>         constructor: get_entry_points(db, &constructor_functions, &replacer)?,
> ```

we should check that the length of this list <= 1
and that if its 1 than the selector is get_selector_from_name('constructor').



_Code quote:_
```XML
get_entry_points(db, &constructor_functions, &replacer)?
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1855)* status: 1 of 12 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/contract.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1855#-NMS6wcS0OEXfjtDosdA:-NMS6wcS0OEXfjtDosdB:bcr7qzx) ([raw file](https://github.com/starkware-libs/cairo/blob/8d73fd50dacccab622407004d17299d49a7741ce/crates/cairo-lang-starknet/src/contract.rs#L63)):*
> ```XML
> }
> 
> /// Returns the list of generated functions for a given contract generated module.
> ```

There is nothing here that depends on the code being generated.



_Suggestion:_
```XML
Returns the list of functions in a given module.
```
___
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1855#-NMS7PNR-7CMxrz3laWL:-NMS7PNR-7CMxrz3laWM:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8d73fd50dacccab622407004d17299d49a7741ce/crates/cairo-lang-starknet/src/contract_class.rs#L127)):*
> ```XML
> fn get_entry_points(
>     db: &mut RootDatabase,
>     external_functions: &[ConcreteFunctionWithBodyId],
> ```





_Suggestion:_
```XML
 entry_point_ids/ entry_point_function.
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 4 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1855)* status: 5 of 12 files reviewed, 3 unresolved discussions (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1855)* status: 5 of 12 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/contract.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1855#-NMS6wcS0OEXfjtDosdA:-NMSEux04hSIovft3J4o:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a2294ac81ea40470c941693417e636a3cc4bcc22/crates/cairo-lang-starknet/src/contract.rs#L63)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

There is nothing here that depends on the code being generated.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1855#-NMS8GA25Xbbu92ZrH04:-NMSFNae35CeJ9Ph5Hpu:be5vil) ([raw file](https://github.com/starkware-libs/cairo/blob/a2294ac81ea40470c941693417e636a3cc4bcc22/crates/cairo-lang-starknet/src/contract_class.rs#L112)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

we should check that the length of this list <= 1
and that if its 1 than the selector is get_selector_from_name('constructor').
</blockquote></details>

is there always only one constructor? this is a vector in the json as well.

anyway - added todo.

about naming - i'm not sure we should enforce.
___
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1855#-NMS7PNR-7CMxrz3laWL:-NMSEzOqCSu8VOFSY3_b:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a2294ac81ea40470c941693417e636a3cc4bcc22/crates/cairo-lang-starknet/src/contract_class.rs#L127)):*
> ```XML
> fn get_entry_points(
>     db: &mut RootDatabase,
>     external_functions: &[ConcreteFunctionWithBodyId],
> ```

Done.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 12 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1855)* status: 7 of 12 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1855#-NMS8GA25Xbbu92ZrH04:-NMSG3PDDN5ptW0Kno4H:b8bhuoq) ([raw file](https://github.com/starkware-libs/cairo/blob/a2294ac81ea40470c941693417e636a3cc4bcc22/crates/cairo-lang-starknet/src/contract_class.rs#L112)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is there always only one constructor? this is a vector in the json as well.

anyway - added todo.

about naming - i'm not sure we should enforce.
</blockquote></details>

We currently only support one constructor and the selector is enforce in the os.

I agree that you  can different name in the high level code.

Where is the todo?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1855)* status: 7 of 12 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1855#-NMS8GA25Xbbu92ZrH04:-NMSHqr866BQTrepJv1g:bc7wt0v) ([raw file](https://github.com/starkware-libs/cairo/blob/a2294ac81ea40470c941693417e636a3cc4bcc22/crates/cairo-lang-starknet/src/contract_class.rs#L112)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

We currently only support one constructor and the selector is enforce in the os.

I agree that you  can different name in the high level code.

Where is the todo?
</blockquote></details>

got missed in the push - there now.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 12 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1855#-:-NMSqCUs91NpTLHgKxvc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1855#-NMS8GA25Xbbu92ZrH04:-NMSqA1bD5Na7Zaw95kk:bdr1cug) ([raw file](https://github.com/starkware-libs/cairo/blob/a2294ac81ea40470c941693417e636a3cc4bcc22/crates/cairo-lang-starknet/src/contract_class.rs#L112)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

got missed in the push - there now.
</blockquote></details>

it also need to have the right selector.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1855)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1855#-NMS8GA25Xbbu92ZrH04:-NMTNE5mAQdxpSqM5DZv:b6noc4v) ([raw file](https://github.com/starkware-libs/cairo/blob/a2294ac81ea40470c941693417e636a3cc4bcc22/crates/cairo-lang-starknet/src/contract_class.rs#L112)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it also need to have the right selector.
</blockquote></details>

where would that be enforeced?

**Review by orizi — COMMENTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1855)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1855)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
