### PR TITLE
Added OutputBuiltin and output_felt252 libfunc.

### PR DESCRIPTION
**Pull request by yuvalsw**
The first builtin+libfunc actually being tested on starknet before being submitted!

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2605)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 7 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2605)* status: 7 of 25 files reviewed, 1 unresolved discussion (waiting on @liorgold2, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/builtin_cost.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2605#-NRTlrax1a9fv_jQwdSa:-NRTlrax1a9fv_jQwdSb:b-y0zsp) ([raw file](https://github.com/starkware-libs/cairo/blob/875bf4f50f2f8cb5ab53e141a3116bee7157c1d9/crates/cairo-lang-sierra/src/extensions/modules/builtin_cost.rs#L32)):*
> ```XML
>     EcOp,
>     /// One invocation of the Output builtin.
>     Output,
> ```

Should this really have a cost? This doesn't really have an effect, it is just a specially marked buffer

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2605)* status: 6 of 27 files reviewed, 1 unresolved discussion (waiting on @liorgold2, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/builtin_cost.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2605#-NRTlrax1a9fv_jQwdSa:-NRTnl7J-0JR-AMYJVe_:b-ju7c8p) ([raw file](https://github.com/starkware-libs/cairo/blob/875bf4f50f2f8cb5ab53e141a3116bee7157c1d9/crates/cairo-lang-sierra/src/extensions/modules/builtin_cost.rs#L32)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Should this really have a cost? This doesn't really have an effect, it is just a specially marked buffer
</blockquote></details>

Done.
Although I am not sure this is the right thing to do. We probably not, but we may, change things in the future. Then it'll be impossible to change the cost. For all the other builtins we have costs, right?

**Review by spapinistarkware — COMMENTED** [review]
I don't want output builtin to be an implciit. It adds impureness to the language.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2605#-:-NRWPmTQDYRVXDqubo2M:bed804w)* status: 6 of 27 files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @orizi)

**Review by spapinistarkware — COMMENTED** [review]
Also, why do we need output builtin, when we can return data from main?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2605#-:-NRWoGV34PdgtwuakGDp:b-av340x)* status: 6 of 27 files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @orizi)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2605)* status: 13 of 27 files reviewed, 2 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/allowed_libfuncs_lists/experimental_v0.1.0.json` line 70 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2605#-NRbPP28Esh3R-tK019i:-NRbPP28Esh3R-tK019j:bf32kcm) ([raw file](https://github.com/starkware-libs/cairo/blob/920aa22997432b15d9f64ae2d4c283006bd2816e/crates/cairo-lang-starknet/src/allowed_libfuncs_lists/experimental_v0.1.0.json#L70)):*
> ```JSON
>         "nullable_from_box",
>         "pedersen",
>         "output_felt252",
> ```

Above `pedersen`.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 25 files at r1, 1 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2605)* status: 16 of 27 files reviewed, 4 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/output_test.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2605#-NRbQ02_2GZi2CrmAVsL:-NRbQ02_2GZi2CrmAVsM:b6gpia9) ([raw file](https://github.com/starkware-libs/cairo/blob/920aa22997432b15d9f64ae2d4c283006bd2816e/crates/cairo-lang-sierra-to-casm/src/invocations/output_test.rs#L1)):*
> ```XML
> use cairo_lang_casm::ap_change::ApChange;
> ```

Remove this test. Use the e2e libfunc tests to test this libfunc without adding rust code.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2605)* status: 17 of 27 files reviewed, 5 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/casm_contract_class.rs` line 231 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2605#-NRbQC9W0RvKJTpi8WZ2:-NRbQC9W0RvKJTpi8WZ3:b-zuzgp) ([raw file](https://github.com/starkware-libs/cairo/blob/920aa22997432b15d9f64ae2d4c283006bd2816e/crates/cairo-lang-starknet/src/casm_contract_class.rs#L231)):*
> ```XML
>             [
>                 RangeCheckType::id(),
>                 OutputBuiltinType::id(),
> ```

Don't think it should be mentioned in a Starknet file.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2605)* status: 18 of 27 files reviewed, 6 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/db.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2605#-NRbQGkQBW5dukBnYvr0:-NRbQGkQBW5dukBnYvr1:brhumzt) ([raw file](https://github.com/starkware-libs/cairo/blob/920aa22997432b15d9f64ae2d4c283006bd2816e/crates/cairo-lang-starknet/src/db.rs#L17)):*
> ```XML
>         // Override implicit precedence for compatibility with the Starknet OS.
>         let precedence = [
>             "OutputBuiltin",
> ```

Same here.

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 2 of 25 files at r1, 1 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2605)* status: 26 of 27 files reviewed, 7 unresolved discussions (waiting on @orizi and @yuvalsw)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2605)* status: 26 of 27 files reviewed, 10 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`corelib/src/lib.cairo` line 397 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2605#-NRbneHE7wEezVCRZmeV:-NRbneHE7wEezVCRZmeW:bnwbua4) ([raw file](https://github.com/starkware-libs/cairo/blob/920aa22997432b15d9f64ae2d4c283006bd2816e/corelib/src/lib.cairo#L397)):*
> ```Cairo
> // Output.
> mod output;
> use output::output_felt252;
> ```

I suggest removing the aliases, since this is not common enough.
___
*[`corelib/src/output.cairo` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2605#-NRbnshn28M-F8HF4JwU:-NRbnshn28M-F8HF4JwV:b-6n94ph) ([raw file](https://github.com/starkware-libs/cairo/blob/920aa22997432b15d9f64ae2d4c283006bd2816e/corelib/src/output.cairo#L1)):*
> ```Cairo
> use traits::Into;
> ```

Remove uses.
___
*[`corelib/src/output.cairo` line 7 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2605#-NRbnzWV2ttwZAk-2moT:-NRbnzWV2ttwZAk-2moU:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/920aa22997432b15d9f64ae2d4c283006bd2816e/corelib/src/output.cairo#L7)):*
> ```Cairo
> extern type OutputBuiltin;
> 
> extern fn output_felt252(a: felt252) implicits(OutputBuiltin) nopanic;
> ```





_Suggestion:_
```Cairo
extern fn output_felt252(value: felt252) implicits(OutputBuiltin) nopanic;
```

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 4 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2605)* status: all files reviewed, 10 unresolved discussions (waiting on @orizi and @yuvalsw)

**Pull request closed without merging**
