### PR TITLE
Tomerc/adding erc20 mini

### PR DESCRIPTION
**Pull request by Tomer-StarkWare**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5975)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5975)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/components/erc20_mini.cairo` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5975#-O1HDLdMAeY0j7NUr3j5:-O1HDLdMAeY0j7NUr3j6:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/20053c48055ca1cc67d70d9769d6ca158baacc12/crates/cairo-lang-starknet/cairo_level_tests/components/erc20_mini.cairo#L46)):*
> ```Cairo
>     total_supply: u256,
>     balances: Map::<ContractAddress, u256>,
>     allowances: Map::<(ContractAddress, ContractAddress), u256>,
> ```





_Suggestion:_
```Cairo
    balances: Map<ContractAddress, u256>,
    allowances: Map<(ContractAddress, ContractAddress), u256>,
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5975)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/components/erc20_mini.cairo` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5975#-O1HDLdMAeY0j7NUr3j5:-O1HKTxF6pjknLfhjFwD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/20053c48055ca1cc67d70d9769d6ca158baacc12/crates/cairo-lang-starknet/cairo_level_tests/components/erc20_mini.cairo#L46)):*
> ```Cairo
>     total_supply: u256,
>     balances: Map::<ContractAddress, u256>,
>     allowances: Map::<(ContractAddress, ContractAddress), u256>,
> ```

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5975)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5975#-:-O1LAfry-EGsAnQlfuOm:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Tomer-StarkWare)

**Pull request merged**
