### PR TITLE
Added more types for range reduction.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #4596
- #4587 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4587)

### CODE REVIEW

**Review by TomerStarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4587)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/range_reduction.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4587#-NlwLoq47pQeKQSHmKAN:-NlwLoq47pQeKQSHmKAO:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/dc5f3b2763b103c9d759a37a3f1dade276564b7e/crates/cairo-lang-sierra/src/extensions/modules/range_reduction.rs#L59)):*
> ```XML
>         }
>         (id, []) if *id == Uint8Type::id() => {
>             Ok(Range { lower: u8::MIN.into(), upper: u8::MAX.into() })
> ```





_Code snippet:_
```XML
(id, []) if *id == Uint8Type::id() => {
            Ok(Range { lower: u8::MIN.into(), upper: u8::MAX.into() + 1})
        }
        (id, []) if *id == Uint16Type::id() => {
            Ok(Range { lower: u16::MIN.into(), upper: u16::MAX.into() + 1 })
        }
        (id, []) if *id == Uint32Type::id() => {
            Ok(Range { lower: u32::MIN.into(), upper: u32::MAX.into() + 1 })
        }
        (id, []) if *id == Uint64Type::id() => {
            Ok(Range { lower: u64::MIN.into(), upper: u64::MAX.into() + 1})
        }
        (id, []) if *id == Uint128Type::id() => {
            Ok(Range { lower: u128::MIN.into(), upper: u128::MAX.into() + 1})
        }
        (id, []) if *id == Sint8Type::id() => {
            Ok(Range { lower: i8::MIN.into(), upper: i8::MAX.into() + 1})
        }
        (id, []) if *id == Sint16Type::id() => {
            Ok(Range { lower: i16::MIN.into(), upper: i16::MAX.into() + 1})
        }
        (id, []) if *id == Sint32Type::id() => {
            Ok(Range { lower: i32::MIN.into(), upper: i32::MAX.into() + 1})
        }
        (id, []) if *id == Sint64Type::id() => {
            Ok(Range { lower: i64::MIN.into(), upper: i64::MAX.into() + 1})
        }
        (id, []) if *id == Sint128Type::id() => {
            Ok(Range { lower: i128::MIN.into(), upper: i128::MAX.into() + 1})
        }
        (id, []) if *id == Bytes31Type::id() => {
            Ok(Range { lower: 0.into(), upper: BigInt::from(2).pow(248) + 1})
        }
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4587)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/range_reduction.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4587#-NlwLoq47pQeKQSHmKAN:-Nlwym4XDWt74sJHCtX3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/dc5f3b2763b103c9d759a37a3f1dade276564b7e/crates/cairo-lang-sierra/src/extensions/modules/range_reduction.rs#L59)):*
> ```XML
>         }
>         (id, []) if *id == Uint8Type::id() => {
>             Ok(Range { lower: u8::MIN.into(), upper: u8::MAX.into() })
> ```

Done.

**Review by TomerStarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4587#-:-NlwzsmxAA1bgLphHZql:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/range_reduction.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4587#-Nlwuqqd6MkIEA17Wpga:-Nlwuqqd6MkIEA17Wpgb:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/dc5f3b2763b103c9d759a37a3f1dade276564b7e/crates/cairo-lang-sierra/src/extensions/modules/range_reduction.rs#L56)):*
> ```XML
>     match (&ty_info.long_id.generic_id, &ty_info.long_id.generic_args[..]) {
>         (id, []) if *id == Felt252Type::id() => {
>             Ok(Range { lower: 0.into(), upper: Felt252::prime().into() })
> ```

**Review by TomerStarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4587)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
