### PR TITLE
Add dict squash gas calculations.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2026)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2026)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-casm/src/builder.rs` line 516 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2026#-NNHLCLbAzPypmeXZBY3:-NNHLCLbAzPypmeXZBY4:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/67a318cca25996751ae6ef262429ce18fa6cf6d3/crates/cairo-lang-casm/src/builder.rs#L516)):*
> ```XML
>     }
> 
>     /// The state at the last added statement.
> ```





_Suggestion:_
```XML
    /// The number of steps at the last added statement.
```
___
*[`crates/cairo-lang-casm/src/builder.rs` line 521 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2026#-NNHLFj710opQmmqsN3k:-NNHLFj710opQmmqsN3l:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/67a318cca25996751ae6ef262429ce18fa6cf6d3/crates/cairo-lang-casm/src/builder.rs#L521)):*
> ```XML
>     }
> 
>     /// The state at the last added statement.
> ```





_Suggestion:_
```XML
    /// Resets the steps counter.
```
___
*[`crates/cairo-lang-casm/src/builder.rs` line 802 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2026#-NNHLR2CBqZgmJLeP6Oc:-NNHLR2CBqZgmJLeP6Od:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/67a318cca25996751ae6ef262429ce18fa6cf6d3/crates/cairo-lang-casm/src/builder.rs#L802)):*
> ```XML
>     // Steps tracking section.
>     ($builder:ident, validate steps == $count:expr; $($tok:tt)*) => {
>         assert_eq!($builder.steps(), $count);
> ```





_Suggestion:_
```XML
    // Steps tracking section.
    ($builder:ident, validate steps == $count:expr; $($tok:tt)*) => {
        assert_eq!($builder.steps(), $count);
        $crate::casm_build_extend!($builder, $($tok)*)
    };
    ($builder:ident, reset steps; $($tok:tt)*) => {
        $builder.reset_steps();
        $crate::casm_build_extend!($builder, $($tok)*)
    };
    ($builder:ident, add steps to $counter:ident; $($tok:tt)*) => {
        $counter += $builder.steps() as i32;
        $crate::casm_build_extend!($builder, $($tok)*)
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2026)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/dict_felt_to.rs` line 125 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2026#-NNHLq4G1B0U9j0XUlNi:-NNHLq4G1B0U9j0XUlNj:b-3kgmgn) ([raw file](https://github.com/starkware-libs/cairo/blob/67a318cca25996751ae6ef262429ce18fa6cf6d3/crates/cairo-lang-sierra-to-casm/src/invocations/dict_felt_to.rs#L125)):*
> ```XML
>     let [range_check_ptr, gas_builtin, dict_manager_ptr, dict_end_address] =
>         builder.try_get_single_cells()?;
>     let mut fixed_cost: i32 = 0;
> ```

this are all steps - right?
if so - call them so.



_Code quote:_
```XML
    let mut fixed_cost: i32 = 0;
    let mut repeated_access_cost: i32 = 0;
    let mut unique_key_cost: i32 = 0;
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2026)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-casm/src/builder.rs` line 516 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2026#-NNHLCLbAzPypmeXZBY3:-NNHQWqQ21tS26BqmH-f:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/67a318cca25996751ae6ef262429ce18fa6cf6d3/crates/cairo-lang-casm/src/builder.rs#L516)):*
> ```XML
>     }
> 
>     /// The state at the last added statement.
> ```

Done.
___
*[`crates/cairo-lang-casm/src/builder.rs` line 521 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2026#-NNHLFj710opQmmqsN3k:-NNHQX8t6Ud3v6SBrVmB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/67a318cca25996751ae6ef262429ce18fa6cf6d3/crates/cairo-lang-casm/src/builder.rs#L521)):*
> ```XML
>     }
> 
>     /// The state at the last added statement.
> ```

Done.
___
*[`crates/cairo-lang-casm/src/builder.rs` line 802 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2026#-NNHLR2CBqZgmJLeP6Oc:-NNHQXbL60QWuQgclD4d:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/67a318cca25996751ae6ef262429ce18fa6cf6d3/crates/cairo-lang-casm/src/builder.rs#L802)):*
> ```XML
>     // Steps tracking section.
>     ($builder:ident, validate steps == $count:expr; $($tok:tt)*) => {
>         assert_eq!($builder.steps(), $count);
> ```

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/dict_felt_to.rs` line 125 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2026#-NNHLq4G1B0U9j0XUlNi:-NNHQZHi6MMe_4_xaF01:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/67a318cca25996751ae6ef262429ce18fa6cf6d3/crates/cairo-lang-sierra-to-casm/src/invocations/dict_felt_to.rs#L125)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this are all steps - right?
if so - call them so.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2026#-:-NNHcI4UCm4VPOzOtJ9D:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2026)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-casm/src/builder.rs` line 805 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2026#-NNHcOCM59E6KVyFosCR:-NNHcOCM59E6KVyFosCS:b-mpz5ou) ([raw file](https://github.com/starkware-libs/cairo/blob/02a5153a4757c1cde8e2e9c7e3ef6e293112cff4/crates/cairo-lang-casm/src/builder.rs#L805)):*
> ```XML
>     };
>     ($builder:ident, reset steps; $($tok:tt)*) => {
>         $builder.reset_steps();
> ```

consider merging these - this way you may check that every step is actually counted SOMEWHERE



_Code quote:_
```XML
    ($builder:ident, reset steps; $($tok:tt)*) => {
        $builder.reset_steps();
        $crate::casm_build_extend!($builder, $($tok)*)
    };
    ($builder:ident, add steps to $counter:ident; $($tok:tt)*) => {
        $counter += $builder.steps() as i32;
        $crate::casm_build_extend!($builder, $($tok)*)
    };
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2026)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-casm/src/builder.rs` line 805 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2026#-NNHcOCM59E6KVyFosCR:-NNV6opu9iKmOZDQhEC0:bs9d163) ([raw file](https://github.com/starkware-libs/cairo/blob/02a5153a4757c1cde8e2e9c7e3ef6e293112cff4/crates/cairo-lang-casm/src/builder.rs#L805)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

consider merging these - this way you may check that every step is actually counted SOMEWHERE
</blockquote></details>

It was merged originally. I can't check that all steps are counted somewhere since intersected branches will have their steps handled in the  main branch (unless resetting in the intersection, but this seems dangerous to me).

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2026)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-casm/src/builder.rs` line 805 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2026#-NNHcOCM59E6KVyFosCR:-NNV95mX3zuIJWKuAua8:b-ja4n0g) ([raw file](https://github.com/starkware-libs/cairo/blob/02a5153a4757c1cde8e2e9c7e3ef6e293112cff4/crates/cairo-lang-casm/src/builder.rs#L805)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

It was merged originally. I can't check that all steps are counted somewhere since intersected branches will have their steps handled in the  main branch (unless resetting in the intersection, but this seems dangerous to me).
</blockquote></details>

i think in the case for intersected branches you have to count it in the main branch.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2026)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-casm/src/builder.rs` line 805 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2026#-NNHcOCM59E6KVyFosCR:-NNf1qBr75OMMCpJu8zM:b-3vkm9e) ([raw file](https://github.com/starkware-libs/cairo/blob/02a5153a4757c1cde8e2e9c7e3ef6e293112cff4/crates/cairo-lang-casm/src/builder.rs#L805)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i think in the case for intersected branches you have to count it in the main branch.
</blockquote></details>

It is counted in the main branch, it just means that I can't loop over the states and assert that all have 0 steps.
Anyway, I made add steps to reset the step counter.
Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2026)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/dict_felt_to.rs` line 287 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2026#-NNf2iV98YcJZH9oOHIF:-NNf2iV98YcJZH9oOHIG:blm2lku) ([raw file](https://github.com/starkware-libs/cairo/blob/47862d660a750ae128e1e3cea12a1fbd0f312ccc/crates/cairo-lang-sierra-to-casm/src/invocations/dict_felt_to.rs#L287)):*
> ```XML
>             tempvar returned_squashed_dict_start = squashed_dict_start;
>             tempvar returned_squashed_dict_end = squashed_dict_end;
>             validate steps == 11;
> ```

remove.
also all other validations that you sum into counters and check.



_Code quote:_
```XML
            validate steps == 11;
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2026)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/dict_felt_to.rs` line 287 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2026#-NNf2iV98YcJZH9oOHIF:-NNf4Zun0hHRiK7PPB5B:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e11017e106e5de39fbbf35745c900d90cce35db4/crates/cairo-lang-sierra-to-casm/src/invocations/dict_felt_to.rs#L287)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove.
also all other validations that you sum into counters and check.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2026)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/dict_felt_to.rs` line 309 at r6](https://reviewable.io/reviews/starkware-libs/cairo/2026#-NNf6igZ9jGuHDyiOV5R:-NNf6igZ9jGuHDyiOV5S:b-421428) ([raw file](https://github.com/starkware-libs/cairo/blob/781dbb032e55b73142375be3b37f7f3d2d008fcf/crates/cairo-lang-sierra-to-casm/src/invocations/dict_felt_to.rs#L309)):*
> ```XML
>             // (value before and value after) which summarizes all the changes to that key.
>             SquashDict:
>             validate steps == 0;
> ```

as discussed - add some prefix to the macro so it would be obvious this isn't code gen.



_Code quote:_
```XML
            validate steps == 0;
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2026)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/dict_felt_to.rs` line 309 at r6](https://reviewable.io/reviews/starkware-libs/cairo/2026#-NNf6igZ9jGuHDyiOV5R:-NNf7V4R4VSH01S8eqz0:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/781dbb032e55b73142375be3b37f7f3d2d008fcf/crates/cairo-lang-sierra-to-casm/src/invocations/dict_felt_to.rs#L309)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

as discussed - add some prefix to the macro so it would be obvious this isn't code gen.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2026#-:-NNfCXXc03_XotcZIIsu:bnfp4nl)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/dict_felt_to.rs` line 316 at r8](https://reviewable.io/reviews/starkware-libs/cairo/2026#-NNfCKrLEINdmcXYFeui:-NNfCKrLEINdmcXYFeuj:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8d03edfef0b481a7d2078c4712a5c40efa9d12cc/crates/cairo-lang-sierra-to-casm/src/invocations/dict_felt_to.rs#L316)):*
> ```XML
>             tempvar returned_squashed_dict_end = squash_dict_arg_squashed_dict_start;
>             // SquashDict on empty dict is cheaper than not empty dict. Steps disregarded.
>             #{ reset steps; }
> ```





_Suggestion:_
```XML
            #{ steps = 0; }
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2026)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/dict_felt_to.rs` line 316 at r8](https://reviewable.io/reviews/starkware-libs/cairo/2026#-NNfCKrLEINdmcXYFeui:-NNfD0VC-C7B9ze7wYG6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8d03edfef0b481a7d2078c4712a5c40efa9d12cc/crates/cairo-lang-sierra-to-casm/src/invocations/dict_felt_to.rs#L316)):*
> ```XML
>             tempvar returned_squashed_dict_end = squash_dict_arg_squashed_dict_start;
>             // SquashDict on empty dict is cheaper than not empty dict. Steps disregarded.
>             #{ reset steps; }
> ```

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2026)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2026)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
