### PR TITLE
Orizi/merge v2.0.2 into main

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3647)

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
> Reviewed 25 of 54 files at r1, 29 of 29 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3647)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware and @yuvalsw)

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 21 of 22 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3647#-:-N_2fN07CjialcIlP893:bnfp4nl)* status: 54 of 55 files reviewed, all discussions resolved (waiting on @gilbens-starkware, @orizi, and @yuvalsw)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 22 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3647)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware and @yuvalsw)

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 2 of 54 files at r1, 15 of 22 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3647)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3647#-:-N_2faJy9hSYSpNHqk6X:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
