### PR TITLE
"Enforce" consuming inference errors only once

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5276)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 20 of 22 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5276)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 395 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5276#-NtGL4zEC8JrEKg2bbpO:-NtGL4zEC8JrEKg2bbpP:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c8d249800d07447527de48333a67586100c4a4d5/crates/cairo-lang-semantic/src/expr/inference.rs#L395)):*
> ```XML
>     }
> 
>     // Getter for a type var assignment.
> ```





_Suggestion:_
```XML
    /// Getter for a type var assignment.
```
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 532 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5276#-NtGLDNK-HL9OSHONrAk:-NtGLDNK-HL9OSHONrAl:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c8d249800d07447527de48333a67586100c4a4d5/crates/cairo-lang-semantic/src/expr/inference.rs#L532)):*
> ```XML
> 
>     /// Finalizes an inference by inferring uninferred numeric literals as felt252.
>     // pub fn finalize(&mut self) -> Option<(Option<SyntaxStablePtrId>, InferenceError)> {
> ```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5276)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 395 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5276#-NtGL4zEC8JrEKg2bbpO:-NtGo09r3spe99mfWqdU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c8d249800d07447527de48333a67586100c4a4d5/crates/cairo-lang-semantic/src/expr/inference.rs#L395)):*
> ```XML
>     }
> 
>     // Getter for a type var assignment.
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 532 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5276#-NtGLDNK-HL9OSHONrAk:-NtGo-Ro5q1rQ3OGT-oE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c8d249800d07447527de48333a67586100c4a4d5/crates/cairo-lang-semantic/src/expr/inference.rs#L532)):*
> ```XML
> 
>     /// Finalizes an inference by inferring uninferred numeric literals as felt252.
>     // pub fn finalize(&mut self) -> Option<(Option<SyntaxStablePtrId>, InferenceError)> {
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5276#-:-NtH8mue-Z4SldgtUypb:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Review by orizi — APPROVED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5276)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Review by orizi — APPROVED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5276)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 11 of 12 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5276)* status: 29 of 30 files reviewed, 3 unresolved discussions (waiting on @mkaput and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1191 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5276#-NtviCA62L7njZTjfjAE:-NtviCA62L7njZTjfjAF:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/2790156171ccc8d4af2c239d9ad349ce91c063bc/crates/cairo-lang-semantic/src/expr/compute.rs#L1191)):*
> ```XML
>         ctx.diagnostics.report(syntax, IncompatibleIfBlockTypes { block_if_ty, block_else_ty })
>     };
>     // TODO(yg): move the closure to the ctor.
> ```

.
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 817 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5276#-NtviSzm398L9mz2-wTp:-NtviSzn3T6VNxa41OfA:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/2790156171ccc8d4af2c239d9ad349ce91c063bc/crates/cairo-lang-semantic/src/expr/inference.rs#L817)):*
> ```XML
>     // ======================
> 
>     // TODO(yg): fix doc
> ```

.
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 829 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5276#-NtviVBh-cugE5sE9-10:-NtviVBh-cugE5sE9-11:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/2790156171ccc8d4af2c239d9ad349ce91c063bc/crates/cairo-lang-semantic/src/expr/inference.rs#L829)):*
> ```XML
>             return ErrorSet;
>         }
>         // assert!(self.error_status.is_ok(), "Can't overwrite the error");
> ```

.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5276#-:-NtvyC2V1lj5OIkqJ5cA:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5276)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Pull request merged**
