### PR TITLE
Update cairo-vm version.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3334)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3334)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi and @spapinistarkware)

**Review by elintul — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3334#-:-NXPZYZ99CGBjOxDwkh8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi and @spapinistarkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3334)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5, @orizi, and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3334#-NXPZfKF87npMNiU-5QB:-NXPZfKF87npMNiU-5QC:bu4glp3) (no related file):*
wonder why you aren't [getting my errors](https://reviewable.io/reviews/starkware-libs/cairo/3278)...
probably because you didn't run `cargo update`, but I'm not sure if it's required.
@spapinistarkware / @orizi ?

___

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3334#-:-NXPbDWSDMW6xlriILw_:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5, @orizi, and @spapinistarkware)

**Pull request merged**
