### PR TITLE
Moved new diagnostics from enabled at edition to warning.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4462)

### CODE REVIEW

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 20 of 47 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4462)* status: 20 of 47 files reviewed, 1 unresolved discussion (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/inline_macros` line 285 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4462#-NjwOtb492KerLPHJDZ2:-NjwOtb492KerLPHJDZ3:b3k6aa8) ([raw file](https://github.com/starkware-libs/cairo/blob/f8e30914d9794f73c28f3bfe11120b15357f224b/crates/cairo-lang-semantic/src/expr/test_data/inline_macros#L285)):*
> ```
>  --> lib.cairo:3:8
>    let ba: ByteArray = "hello";
>        ^^
> ```

It is used, maybe it isn't recognised since it is inside another block?



_Code quote:_
```
error: Unused variable. Consider ignoring by prefixing with `_`.
 --> lib.cairo:3:8
   let ba: ByteArray = "hello";
       ^^
```

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 23 of 47 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4462)* status: 44 of 47 files reviewed, 1 unresolved discussion (waiting on @mkaput and @orizi)

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 1 of 47 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4462)* status: 45 of 47 files reviewed, 1 unresolved discussion (waiting on @mkaput and @orizi)

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 1 of 47 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4462)* status: 46 of 47 files reviewed, 1 unresolved discussion (waiting on @mkaput and @orizi)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4462#-:-NjwSKSE7ahqGYGUo4gF:bnfp4nl)* status: 46 of 47 files reviewed, all discussions resolved (waiting on @mkaput)

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4462)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Review by mkaput — APPROVED** [review]
> Reviewed 44 of 47 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4462)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4462)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
