### PR TITLE
Expose functions/macros/vars for custom hint processors

### PR DESCRIPTION
**Pull request by karol-bisztyga**
This is a follow-up for https://github.com/starkware-libs/cairo/pull/3283

We need some functions/macros to be exposed in order to work properly with a custom hint processor.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3485)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3485)* status: all files reviewed, 1 unresolved discussion (waiting on @karol-bisztyga)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3485#-NYbjlsh5v2acGr3Xjxp:-NYbjlsh5v2acGr3Xjxq:bm1koz0) ([raw file](https://github.com/starkware-libs/cairo/blob/35b21421d565dba223628bfe4a87c15edfb593ab/crates/cairo-lang-runner/src/lib.rs#L141)):*
> ```XML
>     type_sizes: TypeSizeMap,
>     /// The casm program matching the Sierra code.
>     pub casm_program: CairoProgram,
> ```

I'd prefer adding a getter, the ability to edit is a bit more dangerous IMO.
If you need it to be editable, you need some further refactoring here.

**Comment by karol-bisztyga** [comment]
*[`crates/cairo-lang-runner/src/lib.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3485#-NYbjlsh5v2acGr3Xjxp:-NYqeD298FIvTZ7KJqXt:bp05qzi) ([raw file](https://github.com/starkware-libs/cairo/blob/35b21421d565dba223628bfe4a87c15edfb593ab/crates/cairo-lang-runner/src/lib.rs#L141)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I'd prefer adding a getter, the ability to edit is a bit more dangerous IMO.
If you need it to be editable, you need some further refactoring here.
</blockquote></details>

getter's fine

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3485#-:-NYqeoq6-yhiLgsmFR5e:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @karol-bisztyga)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3485#-NYqektfE4sUJcQ_UpK7:-NYqektfE4sUJcQ_UpK8:b-4tvlbn) (no related file):*
@yuvalsw - for second eye.

___

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3485#-:-NYrgSG8E6mB3cqgwLe6:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @karol-bisztyga)

**Comment by karol-bisztyga** [comment]
Cool, thanks for the review 🙌 I am not able to merge this, can you please do this?

**Comment by mkaput** [comment]
here you are 😉

**Pull request merged**
