### PR TITLE
Added estimated gas to test result.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #3715
- #3714
- #3709 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3709)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-runner/src/lib.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3709#-N_hnCHID6ufDUdGewUJ:-N_hnCHID6ufDUdGewUK:b-aflr8e) ([raw file](https://github.com/starkware-libs/cairo/blob/41cc68f309d3c10ca58e1d18b1b18a8c8bdfa512/crates/cairo-lang-runner/src/lib.rs#L97)):*
> ```XML
> fn token_gas_cost(token_type: CostTokenType) -> usize {
>     match token_type {
>         CostTokenType::Const => 1,
> ```

what is this?



_Code quote:_
```XML
CostTokenType::Const => 1,
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3709)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3709#-N_hnCHID6ufDUdGewUJ:-N_i-GRXAJ58veC46nXE:bzdey2k) ([raw file](https://github.com/starkware-libs/cairo/blob/41cc68f309d3c10ca58e1d18b1b18a8c8bdfa512/crates/cairo-lang-runner/src/lib.rs#L97)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what is this?
</blockquote></details>

the non-builtin token type.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-runner/src/lib.rs` line 501 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3709#-N_i-lEQBqjEUlzqfg5n:-N_i-lEQBqjEUlzqfg5o:bws8jcx) ([raw file](https://github.com/starkware-libs/cairo/blob/41cc68f309d3c10ca58e1d18b1b18a8c8bdfa512/crates/cairo-lang-runner/src/lib.rs#L501)):*
> ```XML
> 
>         // In case we don't have any costs - it means no equations were solved - so the gas builtin
>         // is irrelevant, and we can return any value.
> ```

when does this happen?



_Code quote:_
```XML
        // In case we don't have any costs - it means no equations were solved - so the gas builtin
        // is irrelevant, and we can return any value.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-runner/src/lib.rs` line 501 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3709#-N_i-lEQBqjEUlzqfg5n:-N_i0-Sf6WrqE-sI5KLX:blahmoy) ([raw file](https://github.com/starkware-libs/cairo/blob/41cc68f309d3c10ca58e1d18b1b18a8c8bdfa512/crates/cairo-lang-runner/src/lib.rs#L501)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

when does this happen?
</blockquote></details>

Can you improve the comment?


"Testing code that has no gas constraints. This is used internally for testing code that wasn't generated from sierra"

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3709)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 501 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3709#-N_i-lEQBqjEUlzqfg5n:-N_i3F174sp-dHbeOnW-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/41cc68f309d3c10ca58e1d18b1b18a8c8bdfa512/crates/cairo-lang-runner/src/lib.rs#L501)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Can you improve the comment?


"Testing code that has no gas constraints. This is used internally for testing code that wasn't generated from sierra"
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 2 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3709#-:-N_iE8-6-paa8RsYEkOq:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3709)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3709)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
