### PR TITLE
LS: Expand Macro tests

### PR DESCRIPTION
**Pull request by Draggu**
commit-id:c4af1b81

---

**Stack**:
- #6076 ⬅
- #6075
- #6074

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6076)

### CODE REVIEW

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6076)* status: all files reviewed, 1 unresolved discussion (waiting on @Draggu and @orizi)

___
*[`crates/cairo-lang-language-server/tests/test_data/macro_expand.txt` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6076#-O2ie5RSCCVkkTgRlVA_:-O2ie5RSCCVkkTgRlVAa:bi08ica) ([raw file](https://github.com/starkware-libs/cairo/blob/8a72ca7923b608d833023ddf4c99910dd072fa8f/crates/cairo-lang-language-server/tests/test_data/macro_expand.txt#L1)):*
> ```help
> //! > MacroExpand
> ```

hmmm, starknet macros tend to be often changed which will become cumbersome, because this test will end up being constantly CAIRO_FIX_TESTSed :/

I think it'd be better to test this on some trivial derives and `array!`/`format!` macros. Can you rewrite this?

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6076)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @Draggu and @orizi)

___
*[`crates/cairo-lang-language-server/tests/test_data/macro_expand.txt` line 1 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6076#-O2jbQpD5Gcj_RCMfgAc:-O2jbQpD5Gcj_RCMfgAd:b9m279k) ([raw file](https://github.com/starkware-libs/cairo/blob/75d072b9fe538f7812e42de060c86090b860385c/crates/cairo-lang-language-server/tests/test_data/macro_expand.txt#L1)):*
> ```help
> //! > MacroExpand
> ```

sorry for nitpicking

I sense you can also vastly reduce size of this file be chopping it into several tests (just separate them with `//! > ===========` or smth like that) that have small `cairo_code` sections. There's a lot of noise caused by full-file expansion.

You can also hardcode cairo_project.toml in the test runner to reduce this further.

**Review by mkaput — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6076)* status: all files reviewed, 1 unresolved discussion (waiting on @Draggu and @orizi)

**Review by mkaput — CHANGES_REQUESTED** [review]
I love this

> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6076#-:-O3Dl0Ay5U2TZr0O1vSU:bqgqats)* status: all files reviewed, 1 unresolved discussion (waiting on @Draggu and @orizi)

___
*[`crates/cairo-lang-language-server/tests/test_data/macro_expand/derive.txt` line 29 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6076#-O3Dknww09t-iLG6OXZM:-O3Dknww09t-iLG6OXZN:b-dzhvg1) ([raw file](https://github.com/starkware-libs/cairo/blob/abeef90d6b51af7c39d37b402d8f89229a8865b4/crates/cairo-lang-language-server/tests/test_data/macro_expand/derive.txt#L29)):*
> ```help
> struct A {
>     a: felt252
> } // impls
> ```

looks like you're missing some `\n\n` here

**Review by Draggu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6076)* status: 7 of 10 files reviewed, 1 unresolved discussion (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-language-server/tests/test_data/macro_expand/derive.txt` line 29 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6076#-O3Dknww09t-iLG6OXZM:-O3HfJm24eM45k85m9bU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/abeef90d6b51af7c39d37b402d8f89229a8865b4/crates/cairo-lang-language-server/tests/test_data/macro_expand/derive.txt#L29)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

looks like you're missing some `\n\n` here
</blockquote></details>

Done.

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6076#-:-O3IYmfzCgSwJBc6VFbg:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 9 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6076#-:-O3R5QH43ddhEHu8wkS4:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Draggu)

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6076)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Draggu)

**Review by mkaput — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6076)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @piotmag769)

**Review by Arcticae — APPROVED** [review]
> Reviewed 7 of 9 files at r4, 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6076)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @piotmag769)

**Review by Arcticae — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6076)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @piotmag769)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6076)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @piotmag769)

**Review by piotmag769 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6076#-:-O3n9sWIDVbRdsKNXHH2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
