### PR TITLE
Add macro call in snippet

### PR DESCRIPTION
**Pull request by clint419**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4378)

### CODE REVIEW

**Comment by clint419** [comment]
@orizi 
Hi, I've added some macro call methods to the snippet in vscode-cairo to see if you can merge them. Thank you

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4378)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @clint419)

___
*[`vscode-cairo/snippets/cairo.json` line 217 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4378#-NimqyYr7rRKLaqKtyMU:-NimqyYs-Zh8kUe-pFv5:bbfwsc3) ([raw file](https://github.com/starkware-libs/cairo/blob/95e2d9cdd3ca1fdcae020a7b71be43c2ace02722/vscode-cairo/snippets/cairo.json#L217)):*
> ```JSON
>     "body": ["assert!($1, '$2');"],
>     "description": "Creates an simple test"
>   },
> ```

I think - as it can work without - and in any case - `"` instead of `'`



_Suggestion:_
```JSON
  "Creates an assertion with macro": {
    "prefix": "assert",
    "body": ["assert!($1);"],
    "description": "Creates an simple test"
  },
```
___
*[`vscode-cairo/snippets/cairo.json` line 222 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4378#-NimrBMz14aSkE7QsEx-:-NimrBMz14aSkE7QsEx0:bbfwsc3) ([raw file](https://github.com/starkware-libs/cairo/blob/95e2d9cdd3ca1fdcae020a7b71be43c2ace02722/vscode-cairo/snippets/cairo.json#L222)):*
> ```JSON
>     "body": ["assert_eq!($1, $2, '$3');"],
>     "description": "Creates an simple test"
>   },
> ```

I think - as it can work without - and in any case - `"` instead of `'`



_Suggestion:_
```JSON
  "Creates an equality assertion with macro": {
    "prefix": "assert",
    "body": ["assert_eq!($1, $2);"],
    "description": "Creates an simple test"
  },
```
___
*[`vscode-cairo/snippets/cairo.json` line 227 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4378#-NimrEte34ipyP4H4sH6:-NimrEte34ipyP4H4sH7:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/95e2d9cdd3ca1fdcae020a7b71be43c2ace02722/vscode-cairo/snippets/cairo.json#L227)):*
> ```JSON
>     "body": ["panic!($1);"],
>     "description": "Creates panic"
>   },
> ```





_Suggestion:_
```JSON
  "Creates panic": {
    "prefix": "panic",
    "body": ["panic!(\"$1\");"],
    "description": "Creates panic"
  },
```
___
*[`vscode-cairo/snippets/cairo.json` line 232 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4378#-NimrJT63psUDdgDOMA6:-NimrJT63psUDdgDOMA7:b-jmcoit) ([raw file](https://github.com/starkware-libs/cairo/blob/95e2d9cdd3ca1fdcae020a7b71be43c2ace02722/vscode-cairo/snippets/cairo.json#L232)):*
> ```JSON
>     "body": ["format!('$1', $2);"],
>     "description": "Creates a String using interpolation of expressions"
>   },
> ```

and in all other direct formats styles - as only the string format arg is a must.



_Suggestion:_
```JSON
  "Creates a String using interpolation of expressions": {
    "prefix": "format",
    "body": ["format!("$1");"],
    "description": "Creates a String using interpolation of expressions"
  },
```
___
*[`vscode-cairo/snippets/cairo.json` line 262 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4378#-Nimrd7p-jypmRaXwCqU:-Nimrd7p-jypmRaXwCqV:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/95e2d9cdd3ca1fdcae020a7b71be43c2ace02722/vscode-cairo/snippets/cairo.json#L262)):*
> ```JSON
>     "body": ["selector!($1);"],
>     "description": "Creates a selector"
>   },
> ```





_Suggestion:_
```JSON
  "Creates a selector": {
    "prefix": "selector",
    "body": ["selector!(\"$1\");"],
    "description": "Creates a selector"
  },
```
___
*[`vscode-cairo/snippets/cairo.json` line 267 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4378#-NimrmhS8Jgwm1MCz_1R:-NimrmhS8Jgwm1MCz_1S:by0g7su) ([raw file](https://github.com/starkware-libs/cairo/blob/95e2d9cdd3ca1fdcae020a7b71be43c2ace02722/vscode-cairo/snippets/cairo.json#L267)):*
> ```JSON
>     "body": ["component!($1, $2);"],
>     "description": "Creates a component"
>   },
> ```

note this is not in statement context - so i'm not sure if this should behave differently.



_Suggestion:_
```JSON
  "Declares a component usage": {
    "prefix": "component",
    "body": ["component!(path: $1, storage: $2, event: $3);"],
    "description": "Declares a component usage"
  },
```
___
*[`vscode-cairo/snippets/cairo.json` line 277 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4378#-NimsIanE8wGckqe0UU9:-NimsIanE8wGckqe0UUA:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/95e2d9cdd3ca1fdcae020a7b71be43c2ace02722/vscode-cairo/snippets/cairo.json#L277)):*
> ```JSON
>     "body": ["get_dep_component_mut!($1, $2);"],
>     "description": "Get a mutable component"
>   }
> ```





_Suggestion:_
```JSON
  "Get a mutable component": {
    "prefix": "get_dep_component_mut",
    "body": ["get_dep_component_mut!(ref $1, $2);"],
    "description": "Get a mutable component"
  }
```

**Comment by clint419** [comment]
@orizi 
Thank you for your suggestion. In PR, some changes need to be made, and now, it has been adjusted according to the suggestions

**Review by clint419 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4378)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @orizi)

___
*[`vscode-cairo/snippets/cairo.json` line 217 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4378#-NimqyYr7rRKLaqKtyMU:-Ninvgt-Aqv4YMFiGu3H:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/95e2d9cdd3ca1fdcae020a7b71be43c2ace02722/vscode-cairo/snippets/cairo.json#L217)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I think - as it can work without - and in any case - `"` instead of `'`
</blockquote></details>

Done.
___
*[`vscode-cairo/snippets/cairo.json` line 222 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4378#-NimrBMz14aSkE7QsEx-:-NinvplP44N2qgFgKA_C:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/95e2d9cdd3ca1fdcae020a7b71be43c2ace02722/vscode-cairo/snippets/cairo.json#L222)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I think - as it can work without - and in any case - `"` instead of `'`
</blockquote></details>

Done.
___
*[`vscode-cairo/snippets/cairo.json` line 227 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4378#-NimrEte34ipyP4H4sH6:-NinwF6Q4nycGxCMhqp2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/95e2d9cdd3ca1fdcae020a7b71be43c2ace02722/vscode-cairo/snippets/cairo.json#L227)):*
> ```JSON
>     "body": ["panic!($1);"],
>     "description": "Creates panic"
>   },
> ```

Done.
___
*[`vscode-cairo/snippets/cairo.json` line 232 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4378#-NimrJT63psUDdgDOMA6:-NinwFjG6JwHXlwzC2yI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/95e2d9cdd3ca1fdcae020a7b71be43c2ace02722/vscode-cairo/snippets/cairo.json#L232)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

and in all other direct formats styles - as only the string format arg is a must.
</blockquote></details>

Done.
___
*[`vscode-cairo/snippets/cairo.json` line 262 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4378#-Nimrd7p-jypmRaXwCqU:-NinwHf41SVKsWog4AOa:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/95e2d9cdd3ca1fdcae020a7b71be43c2ace02722/vscode-cairo/snippets/cairo.json#L262)):*
> ```JSON
>     "body": ["selector!($1);"],
>     "description": "Creates a selector"
>   },
> ```

Done.
___
*[`vscode-cairo/snippets/cairo.json` line 267 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4378#-NimrmhS8Jgwm1MCz_1R:-NinwIsqE3JKl168XAAe:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/95e2d9cdd3ca1fdcae020a7b71be43c2ace02722/vscode-cairo/snippets/cairo.json#L267)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

note this is not in statement context - so i'm not sure if this should behave differently.
</blockquote></details>

Done.
___
*[`vscode-cairo/snippets/cairo.json` line 277 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4378#-NimsIanE8wGckqe0UU9:-NinwKA89_6ufY1tw71c:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/95e2d9cdd3ca1fdcae020a7b71be43c2ace02722/vscode-cairo/snippets/cairo.json#L277)):*
> ```JSON
>     "body": ["get_dep_component_mut!($1, $2);"],
>     "description": "Get a mutable component"
>   }
> ```

Done.

**Review by clint419 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4378)* status: all files reviewed, 7 unresolved discussions (waiting on @orizi)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4378#-:-NinygZM10j7Y356490X:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @clint419)

**Pull request merged**
