### PR TITLE
Add CostInfoProvider.circuit_info

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5566)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5566)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 562 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5566#-NxwLeGy26AfZYcthaub:-NxwLeGy26AfZYcthauc:b-1kvwm9) ([raw file](https://github.com/starkware-libs/cairo/blob/34f0d6d60ac25fec634d642902006197d260999f/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L562)):*
> ```XML
> 
>     fn circuit_info(&self, _ty: &ConcreteTypeId) -> &CircuitInfo {
>         unimplemented!("circuits are not supported");
> ```

also up.



_Suggestion:_
```XML
        unimplemented!("circuits are not supported for old gas solver");
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5566)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 562 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5566#-NxwLeGy26AfZYcthaub:-NxwW5eTAK7D60ZA0ZId:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/34f0d6d60ac25fec634d642902006197d260999f/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L562)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

also up.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5566)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 122 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5566#-NxwX7Fe1izN4L9rDU3i:-NxwXSKB156NFElJ8R34:bbth5oo) ([raw file](https://github.com/starkware-libs/cairo/blob/a97aa97f64a69be465928aad77785ef6e91ea3cb/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L122)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Is this also used only by the old gas solver
</blockquote></details>

i think so.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5566#-:-NxwYDW59QpmsSor7GWL:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
