### PR TITLE
Added i*_diff and Ord.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #3625
- #3624
- #3623
- #3622 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3622)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3622)* status: 0 of 24 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/integer.cairo` line 1945 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3622#-Na6ezdhCGAFz2Dyk-uf:-Na6ezdhCGAFz2Dyk-ug:b-bqc88o) ([raw file](https://github.com/starkware-libs/cairo/blob/4fba349c855943a21e0a101e22ffdb0d1910d826/corelib/src/integer.cairo#L1945)):*
> ```Cairo
> }
> 
> extern fn i8_diff(lhs: i8, rhs: i8) -> Result<u8, u8> implicits(RangeCheck) nopanic;
> ```

Doc the return type. Also possible: Add a new enum for the return type and doc there.

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 24 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3622)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3622)* status: 18 of 24 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`corelib/src/integer.cairo` line 1945 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3622#-Na6ezdhCGAFz2Dyk-uf:-Na7MY_r3PfFcP2Sqe0y:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c83806e2e36efca3a153500925271e8190608a70/corelib/src/integer.cairo#L1945)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Doc the return type. Also possible: Add a new enum for the return type and doc there.
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3622#-:-NaCRGxO6B1uFysViBrG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
