### PR TITLE
Add diagnostic when the root block of an inlined funciton in unreacha…

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
…ble.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2027)

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
why is this worse than any other early return?

> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2027#-:-NNHbHu_D3wXkYd1QV4A:b-r8nw7o)* status: 1 of 3 files reviewed, all discussions resolved

**Comment by ilyalesokhin-starkware** [comment]
We don't consider it as an early return and it ceashes the compiler.

**Review by orizi — COMMENTED** [review]
but why?
supposedly - we inject the code, and then handle the returns as gotos back to the caller 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2027#-:-NNHcmFBDGsfA7guYGV0:b-xaxscb)* status: 1 of 3 files reviewed, all discussions resolved

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2027)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/inline/test_data/inline_diagnostics` line 191 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2027#-NNHdOphCDgyGU1mdP5D:-NNHdOphCDgyGU1mdP5E:b-ky2q3e) ([raw file](https://github.com/starkware-libs/cairo/blob/5825bc2aa08cfccadc1df8822d9511f3871ee04a/crates/cairo-lang-lowering/src/inline/test_data/inline_diagnostics#L191)):*
> ```
> //! > semantic_diagnostics
> error: Missing token TerminalSemicolon.
>  --> lib.cairo:4:13
> ```

i'm assuming this isn't the actual issue



_Code quote:_
```
error: Missing token TerminalSemicolon.
 --> lib.cairo:4:13
    return 1
            ^
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2027)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2027)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2027#-:-NNHkyy494vMGiSWA6Im:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2027)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2027)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2027)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 117 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2027#-NNHnBBr3TR7iSsfdPbU:-NNHp5949SRCYsRyKvgB:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/a9f43decdca114c56caac1fd35af59b8042635f3/crates/cairo-lang-lowering/src/inline/mod.rs#L117)):*
> ```XML
>             }
>             FlatBlockEnd::Unreachable => {
>                 // TODO(ilya): Remove the folloing limitation.
> ```

done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2027)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
