### PR TITLE
Added diagnostics for attributes not declared in plugins.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4096)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 25 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4096)* status: all files reviewed, 19 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-defs/src/db.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-NempXWLAPFxotGDYvN5:-NempXWLAPFxotGDYvN6:b-3tb27j) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-defs/src/db.rs#L75)):*
> ```XML
>     fn inline_macro_plugins(&self) -> Arc<OrderedHashMap<String, Arc<dyn InlineMacroExprPlugin>>>;
> 
>     /// Returns the set of allowed attributes.
> ```

in what scope?



_Code quote:_
```XML
allowed attributes.
```
___
*[`crates/cairo-lang-defs/src/db.rs` line 179 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-NemppJTDMcBlZxgHOKK:-NemppJTDMcBlZxgHOKL:bt1mcgf) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-defs/src/db.rs#L179)):*
> ```XML
>         "implicit_precedence".into(),
>         // TODO(orizi): Remove this once `starknet` is removed from corelib.
>         "starknet::interface".into(),
> ```

why isn't this part of the starknet plugin attrs?
___
*[`crates/cairo-lang-defs/src/db.rs` line 304 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-Nemq8KE9sk2KKWtGSA0:-Nemq8KFB7kjTX90E_7y:b-xb6dhq) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-defs/src/db.rs#L304)):*
> ```XML
>     let syntax_db = db.upcast();
>     let module_file = db.module_main_file(module_id)?;
>     let allowed_attributes = db.allowed_attributes();
> ```

move right before its use.
___
*[`crates/cairo-lang-defs/src/db.rs` line 519 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-NemqYCG3J7oUW1jEfCc:-NemqYCG3J7oUW1jEfCd:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-defs/src/db.rs#L519)):*
> ```XML
> }
> 
> /// Validates that all attributes on an item are in the allowed set or adds diagnostics.
> ```





_Suggestion:_
```XML
 on the given item are in the allowed set or adds diagnostics.
```
___
*[`crates/cairo-lang-defs/src/db.rs` line 542 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-NemrOGc0nat-xyO0f23:-NemrOGc0nat-xyO0f24:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-defs/src/db.rs#L542)):*
> ```XML
> 
> /// Validates that all attributes on an the items in an element list are in the allowed set or adds
> /// diagnostics.
> ```





_Suggestion:_
```XML
/// Validates that all attributes on all items in the given element list are in the allowed set or adds
/// diagnostics.
```
___
*[`crates/cairo-lang-defs/src/db.rs` line 556 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-NemtBQuCIq07RsoNXLy:-NemtBQuCIq07RsoNXLz:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-defs/src/db.rs#L556)):*
> ```XML
> 
> /// Validates that all attributes on an item or on items contained within it are in the allowed set
> /// or adds diagnostics.
> ```





_Suggestion:_
```XML
/// Validates that all attributes on an item and on items contained within it are in the allowed set
/// or adds diagnostics.
```
___
*[`crates/cairo-lang-defs/src/db.rs` line 564 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-NemrhQp5MIERZacac-B:-NemrhQp5MIERZacac-C:bqsp5tq) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-defs/src/db.rs#L564)):*
> ```XML
>     plugin_diagnostics: &mut Vec<(ModuleFileId, PluginDiagnostic)>,
> ) {
>     validate_attributes_flat(db, allowed_attributes, module_file_id, item_ast, plugin_diagnostics);
> ```

consider



_Suggestion:_
```XML
fn validate_attributes_recursive(
    db: &dyn SyntaxGroup,
    allowed_attributes: &OrderedHashSet<String>,
    module_file_id: ModuleFileId,
    item_ast: &ast::Item,
    plugin_diagnostics: &mut Vec<(ModuleFileId, PluginDiagnostic)>,
) {
    validate_attributes(db, allowed_attributes, module_file_id, item_ast, plugin_diagnostics);
```
___
*[`crates/cairo-lang-defs/src/db.rs` line 579 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-Nems63zAJbDpJxE1u6V:-Nems63zAJbDpJxE1u6W:b-gy78pb) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-defs/src/db.rs#L579)):*
> ```XML
>         ast::Item::Impl(item) => {
>             if let ast::MaybeImplBody::Some(body) = item.body(db) {
>                 validate_attributes_element_list(
> ```

can you move the call to after the match expr? return the item list from each arm, and `return` from the `_` arm.
___
*[`crates/cairo-lang-defs/src/plugin.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-NemtXBwEsfmO1ZkCXaW:-NemtXBwEsfmO1ZkCXaX:bnjyta6) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-defs/src/plugin.rs#L77)):*
> ```XML
> 
>     /// Attributes this plugin uses.
>     /// Attributes no plugin declares will cause a compilation error for unknown attribute.
> ```

This is not accurate as you manually added `inline` and `implicit_precedence`



_Code quote:_
```XML
Attributes no plugin declares w
```
___
*[`crates/cairo-lang-defs/src/plugin.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-Nemtn6-E4hxTCP3KkWC:-Nemtn6-E4hxTCP3KkWD:b-lk415o) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-defs/src/plugin.rs#L78)):*
> ```XML
>     /// Attributes this plugin uses.
>     /// Attributes no plugin declares will cause a compilation error for unknown attribute.
>     fn used_attributes(&self) -> Vec<String>;
> ```

or "allowed"



_Suggestion:_
```XML
fn udeclared_attributes(&self) -> Vec
```
___
*[`crates/cairo-lang-plugins/src/plugins/derive/mod.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-NemuhMOA3xgtJgn53I5:-NemuhMOA3xgtJgn53I6:bjja7hb) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-plugins/src/plugins/derive/mod.rs#L61)):*
> ```XML
> 
>     fn used_attributes(&self) -> Vec<String> {
>         vec![DERIVE_ATTR.to_string(), default::DEFAULT_ATTR.to_string()]
> ```

where is it used in this plugin?



_Code quote:_
```XML
default::DEFAULT_ATTR.to_string()
```
___
*[`crates/cairo-lang-plugins/src/test_data/generate_trait` line 83 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-NemuuHr7vPJYZcqHXRL:-NemuuHr7vPJYZcqHXRM:be3hc9e) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-plugins/src/test_data/generate_trait#L83)):*
> ```
> 
> //! > test_runner_name
> test_expand_plugin(expect_diagnostics: true)
> ```

I think the purpose of this test was to show a success scenario. This way it loses the point of expect_diagnostics. Can you change it to use allowed attributes?

Or - maybe wort adding a test utility to add more "allowed" attrs.
___
*[`crates/cairo-lang-semantic/src/items/free_function_test.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-NemvL-z0KixwtBX7RoY:-NemvL-z0KixwtBX7RoZ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-semantic/src/items/free_function_test.rs#L19)):*
> ```XML
>         db,
>         indoc::indoc! {"
>             // Just to have an allowed attribute.
> ```





_Suggestion:_
```XML
// "inline" is used just to have an allowed attrib
```
___
*[`crates/cairo-lang-semantic/src/items/structure_test.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-NemvbCL2Op5NplDE9Kc:-NemvbCL2Op5NplDE9Kd:bos4jzb) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-semantic/src/items/structure_test.rs#L18)):*
> ```XML
>         db,
>         indoc::indoc! {"
>             #[contract(MyImpl1, MyImpl2)]
> ```

same. Change to a supported attr or manually "support" it in this test.
___
*[`crates/cairo-lang-semantic/src/items/trt_test.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-Nemvjw77S8Z5OFszHc4:-Nemvjw77S8Z5OFszHc5:b-92jqxc) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-semantic/src/items/trt_test.rs#L17)):*
> ```XML
>         db,
>         indoc::indoc! {"
>             // Just to have an allowed attribute.
> ```

same, rephrase as in the other comment.
___
*[`crates/cairo-lang-starknet/src/abi_test.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-NemwB8VCEOw0d89vUie:-NemwB8VCEOw0d89vUif:b-3k25bw) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-starknet/src/abi_test.rs#L22)):*
> ```XML
>         .with_inline_macro_plugin(SelectorMacro::NAME, Arc::new(SelectorMacro))
>         .build()
>         .unwrap();
> ```

consider adding a param `extra plugins`to SemanticDatabaseForTesting::new_empty() and use it.



_Code quote:_
```XML
    let db = &mut RootDatabase::builder()
        .detect_corelib()
        .with_macro_plugin(Arc::new(StarkNetPlugin::default()))
        .with_inline_macro_plugin(SelectorMacro::NAME, Arc::new(SelectorMacro))
        .build()
        .unwrap();
```
___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 140 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-Nemwq7-1mv0x5N0FXIa:-Nemwq7-1mv0x5N0FXIb:b-plcdxo) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-starknet/src/plugin/events.rs#L140)):*
> ```XML
>     let is_nested = member.has_attr(db, NESTED_ATTR);
>     let is_key = member.has_attr(db, KEY_ATTR);
>     let is_serde = member.has_attr(db, "serde");
> ```

SERDE_ATTR



_Code quote:_
```XML
"serde"
```
___
*[`crates/cairo-lang-starknet/src/plugin/mod.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-Nemx-MADNnn92g1kwSb:-Nemx-MBDmFP0AZkp6Ee:b-p0d2i5) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-starknet/src/plugin/mod.rs#L59)):*
> ```XML
> 
>     fn used_attributes(&self) -> Vec<String> {
>         vec![
> ```

1. add serde
2. consider sorting.
3. I think you should also add the deprecated attributes: #[abi] and #[contract]
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 1984 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-NemxipS5Ww7TB546ued:-NemxipS5Ww7TB546uee:b-8e2dkk) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L1984)):*
> ```
>  --> lib.cairo:6:1
> #[abi]
> ^****^
> ```

continuing #3 from previous comment - I think this should't be added, the existing ones suffice.



_Code quote:_
```
error: Plugin diagnostic: Unsupported attribute.
 --> lib.cairo:1:1
#[contract]
^*********^

error: Plugin diagnostic: The 'contract' attribute was deprecated, please use `starknet::contract` instead.
 --> lib.cairo:1:1
#[contract]
^*********^

error: Plugin diagnostic: Unsupported attribute.
 --> lib.cairo:6:1
#[abi]
^****^
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4096)* status: all files reviewed, 14 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-defs/src/db.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-NempXWLAPFxotGDYvN5:-Nen-c4Q0EH5iZ4PVor4:bv7dqs3) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-defs/src/db.rs#L75)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

in what scope?
</blockquote></details>

any scope.
___
*[`crates/cairo-lang-defs/src/db.rs` line 179 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-NemppJTDMcBlZxgHOKK:-Nen-dhf7UyOEKlhy_o8:bt4o567) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-defs/src/db.rs#L179)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

why isn't this part of the starknet plugin attrs?
</blockquote></details>

it is - but as stated in the comment above - this is used in the corelib - so it now crashes without the starknet plugin always.
___
*[`crates/cairo-lang-defs/src/db.rs` line 304 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-Nemq8KE9sk2KKWtGSA0:-Nen-ooE6Mc2tXxy-s7a:b-c6m7ab) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-defs/src/db.rs#L304)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

move right before its use.
</blockquote></details>

it is used in the loop.
___
*[`crates/cairo-lang-defs/src/db.rs` line 556 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-NemtBQuCIq07RsoNXLy:-Nen0C_X-YoFpIRXQB6p:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-defs/src/db.rs#L556)):*
> ```XML
> 
> /// Validates that all attributes on an item or on items contained within it are in the allowed set
> /// or adds diagnostics.
> ```

Done.
___
*[`crates/cairo-lang-defs/src/db.rs` line 564 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-NemrhQp5MIERZacac-B:-Nen0GTz5O72QXfScJAy:b1c0m74) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-defs/src/db.rs#L564)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

consider
</blockquote></details>

recursive sounds like it is about implementation - this just validates attributes under this specific item.
___
*[`crates/cairo-lang-defs/src/db.rs` line 579 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-Nems63zAJbDpJxE1u6V:-Nen0V6iDtiGOnQpNsNC:bz03bva) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-defs/src/db.rs#L579)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

can you move the call to after the match expr? return the item list from each arm, and `return` from the `_` arm.
</blockquote></details>

no - not the same type - so these are 4 different concrete functions.
___
*[`crates/cairo-lang-plugins/src/plugins/derive/mod.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-NemuhMOA3xgtJgn53I5:-Nen13yM8fYsfBWuBITo:b-57q1ul) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-plugins/src/plugins/derive/mod.rs#L61)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

where is it used in this plugin?
</blockquote></details>

in the default derive.
___
*[`crates/cairo-lang-plugins/src/test_data/generate_trait` line 83 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-NemuuHr7vPJYZcqHXRL:-Nen1B1L7ZJVwmTzH2Rk:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-plugins/src/test_data/generate_trait#L83)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I think the purpose of this test was to show a success scenario. This way it loses the point of expect_diagnostics. Can you change it to use allowed attributes?

Or - maybe wort adding a test utility to add more "allowed" attrs.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/structure_test.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-NemvbCL2Op5NplDE9Kc:-Nen1lUx1eKZfK2O19kB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-semantic/src/items/structure_test.rs#L18)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

same. Change to a supported attr or manually "support" it in this test.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/abi_test.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-NemwB8VCEOw0d89vUie:-Nen2vbY7on6Ff1qFekF:btge8ua) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-starknet/src/abi_test.rs#L22)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

consider adding a param `extra plugins`to SemanticDatabaseForTesting::new_empty() and use it.
</blockquote></details>

the use of `SemanticDatabaseForTesting` here was kinda weird to begin with IMO.
___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 140 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-Nemwq7-1mv0x5N0FXIa:-Nen3IXR8p1KEqAbuwfm:bwyw5ls) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-starknet/src/plugin/events.rs#L140)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

SERDE_ATTR
</blockquote></details>

Done.
but not adding this to the list, as it is currently disallowed in any case.
___
*[`crates/cairo-lang-starknet/src/plugin/mod.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-Nemx-MADNnn92g1kwSb:-Nen3nHJ9DCyKW-P3JNi:b-yxedtz) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-starknet/src/plugin/mod.rs#L59)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

1. add serde
2. consider sorting.
3. I think you should also add the deprecated attributes: #[abi] and #[contract]
</blockquote></details>

1. not adding serde - as it is only disallowed currently.
2. Done.
3. I think I'm ok with have the general error as well as the specific (otherwise you would be able to put it in unrelated locations, despite them not making sense anywhere)
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 1984 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-NemxipS5Ww7TB546ued:-Nen4HgJBytZ985cPNH4:b1bqd9z) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L1984)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

continuing #3 from previous comment - I think this should't be added, the existing ones suffice.
</blockquote></details>

I still think the same.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4096)* status: all files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-defs/src/db.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-NempXWLAPFxotGDYvN5:-NenfpSK6Vrjbi_d-e7D:bmfq026) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-defs/src/db.rs#L75)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

any scope.
</blockquote></details>

I meant - write it, that it's globally.
___
*[`crates/cairo-lang-defs/src/db.rs` line 304 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-Nemq8KE9sk2KKWtGSA0:-NengHq25ZSRZvJhMGlB:b-d5wkot) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-defs/src/db.rs#L304)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it is used in the loop.
</blockquote></details>

yes, move it right before it. After `let item_asts = match module_id` which may exit the scope.
___
*[`crates/cairo-lang-defs/src/db.rs` line 564 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-NemrhQp5MIERZacac-B:-NengYqIEBmKMHpCBsFm:bdg68tw) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-defs/src/db.rs#L564)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

recursive sounds like it is about implementation - this just validates attributes under this specific item.
</blockquote></details>

I don't insist, but:
1. recursive doesn't sound to me like it's about implementation. It's about what it does, which is a recursive validation.
2. flat sounds to me like something else.

All this would be more relevant if we have attrs for modules.
___
*[`crates/cairo-lang-defs/src/plugin.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4096#-NenhI4K2tEvy2p2OHOj:-NenhI4K2tEvy2p2OHOk:bfo2a1k) ([raw file](https://github.com/starkware-libs/cairo/blob/ed27cdc2ebfffee09a07701d18972f3dc49414a9/crates/cairo-lang-defs/src/plugin.rs#L77)):*
> ```XML
> 
>     /// Attributes this plugin uses.
>     /// Attributes the plugin uses without declaring here will cause a compilation error for unknown
> ```

It may accidentally be one of the "reserved" ones.
Unless we add a logic that prevents using the "reserved" ones



_Suggestion:_
```XML
 might
```
___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 140 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-Nemwq7-1mv0x5N0FXIa:-NenhoJD-rrEhwJh8u_y:b-up27jw) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-starknet/src/plugin/events.rs#L140)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Done.
but not adding this to the list, as it is currently disallowed in any case.
</blockquote></details>

OK, add a TODO then

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4096)* status: 17 of 25 files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-defs/src/db.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-NempXWLAPFxotGDYvN5:-NeqlEHABelvN9AyXszQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-defs/src/db.rs#L75)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I meant - write it, that it's globally.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-defs/src/db.rs` line 304 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-Nemq8KE9sk2KKWtGSA0:-Neqlcsd5QcjmxTmbzBm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-defs/src/db.rs#L304)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

yes, move it right before it. After `let item_asts = match module_id` which may exit the scope.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-defs/src/db.rs` line 564 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-NemrhQp5MIERZacac-B:-NeqlfaWBdpxWSsg76Ej:b-w5ulsu) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-defs/src/db.rs#L564)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I don't insist, but:
1. recursive doesn't sound to me like it's about implementation. It's about what it does, which is a recursive validation.
2. flat sounds to me like something else.

All this would be more relevant if we have attrs for modules.
</blockquote></details>

recursive sounds to me like it would go recursively into modules - this simply also checks for the subitems of impls, traits, structs and enum - just a single layer.
___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 140 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4096#-Nemwq7-1mv0x5N0FXIa:-NeqmdSUEjwVyRdCD-zH:b-cenqu8) ([raw file](https://github.com/starkware-libs/cairo/blob/fdc99e994fde7036c58b61ed479458ee5b68f870/crates/cairo-lang-starknet/src/plugin/events.rs#L140)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

OK, add a TODO then
</blockquote></details>

to me sounds like a TODO that is likely to remain - basic test will fail when this is added - so the writter would have to fix the missing declaration.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4096#-:-Ner-fQ9Bk70zHpvNJes:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-defs/src/db.rs` line 75 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4096#-Ner-0AmAOgbnifOaDGO:-Ner-0AmAOgbnifOaDGP:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b28a0889ae1f542bf6e0fb677c90c133302b169b/crates/cairo-lang-defs/src/db.rs#L75)):*
> ```XML
>     fn inline_macro_plugins(&self) -> Arc<OrderedHashMap<String, Arc<dyn InlineMacroExprPlugin>>>;
> 
>     /// Returns the set of allowed attributes allowed anywhere.
> ```





_Suggestion:_
```XML
he set of attributes allowed anywhere.
```
___
*[`crates/cairo-lang-defs/src/plugin.rs` line 80 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4096#-Ner-Lfz9XEBLNGuMpaU:-Ner-Lfz9XEBLNGuMpaV:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b28a0889ae1f542bf6e0fb677c90c133302b169b/crates/cairo-lang-defs/src/plugin.rs#L80)):*
> ```XML
>     /// for unknown attribute.
>     /// Note: They may not cause a diagnostic if some other plugin declares such attribute, but
>     /// plugin writters should not rely on that.
> ```





_Suggestion:_
```XML
writers should not rely 
```

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4096)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
