### PR TITLE
LS: Fix hover on definition

### LINKED ISSUE #5826: Hovers on identifiers *defining* the item/variable are not working
## Summary

When hovering over identifiers which **define** items/variables, user expects to get the same hover information as one produced when hovering over identifiers which **reference** these elements.

See examples:

| Expected | Actual |
|---|---|
| Image | Image _This case shows no hovers at all._ |
| Image image | Image _This is the legacy hover implementation that we aim to remove._ |

## Proposed solution

This logic only looks for references and completely ignores cases when the identifier under the cursor is actual _name_ of the item/variable. Such condition should be added to this code:

https://github.com/starkware-libs/cairo/blob/4646ad819521338ccd92b8ebef76b96770b46ce1/crates/cairo-lang-language-server/src/lang/inspect/defs.rs#L40-L46

### PR DESCRIPTION
**Pull request by Draggu**
fix #5826

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6255)

### CODE REVIEW

**Review by piotmag769 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6255)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/tests/test_data/hover/basic.txt` line 216 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6255#-O4q7QjiBWsvcMVWNlxh:-O4q7QjiBWsvcMVWNlxi:b-dx1h0g) ([raw file](https://github.com/starkware-libs/cairo/blob/ca54664d89c33e5a1bc98bd872ab9809de14ecb0/crates/cairo-lang-language-server/tests/test_data/hover/basic.txt#L216)):*
> ```help
> ```
> ```cairo
> fn main()
> ```

Well xD Seems like it doesn't work :c

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6255#-:-O4sw08l32m4TgRFha4H:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, and @mkaput)

**Review by piotmag769 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6255)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/tests/test_data/hover/basic.txt` line 323 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6255#-O4zyoZYEQZOQz_cC1mQ:-O4zyoZYEQZOQz_cC1mR:bxpynhr) ([raw file](https://github.com/starkware-libs/cairo/blob/590e171ddc2c3eb993e22b077abf6ae3c04f4352/crates/cairo-lang-language-server/tests/test_data/hover/basic.txt#L323)):*
> ```help
> ```
> ```cairo
> impl RectangleImpl of RectangleTrait
> ```

This one seems wrong

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6255)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, and @mkaput)

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6255)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, and @piotmag769)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6255#-O5DLTHP-EjbzBxaSrxX):*




_Suggestion:_
```
- 590e171: LS: Fix hover on definition

  fix #5826

  commit-id:7654b189
```
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 999 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6255#-O5DNv7Q5j579351DvNT:-O5DNv7R6DWkbdQBdlZH:b-98omoe) ([raw file](https://github.com/starkware-libs/cairo/blob/590e171ddc2c3eb993e22b077abf6ae3c04f4352/crates/cairo-lang-language-server/src/lib.rs#L999)):*
> ```XML
>     }
> 
>     for lookup_item_id in lookup_items.iter().rev().copied() {
> ```

please add a comment stating that you're looking for variable definitions here
___
*[`crates/cairo-lang-language-server/tests/test_data/hover/basic.txt` line 323 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6255#-O4zyoZYEQZOQz_cC1mQ:-O5DOYL39NdMrq2KmLw8:b-p8q3ci) ([raw file](https://github.com/starkware-libs/cairo/blob/590e171ddc2c3eb993e22b077abf6ae3c04f4352/crates/cairo-lang-language-server/tests/test_data/hover/basic.txt#L323)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

This one seems wrong
</blockquote></details>

I'm not sure. Technically, it is because we're inside an `impl` so we are in a concrete context. But UX-wise, it would also be nice to get trait info alongside. Topic for a separate issue nonetheless.

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6255)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 1000 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6255#-O5EFHPT1bUmytgx875C:-O5EFHPT1bUmytgx875D:b-7jer0l) ([raw file](https://github.com/starkware-libs/cairo/blob/483847dbab4fa9e0419f423dd25925add389fddb/crates/cairo-lang-language-server/src/lib.rs#L1000)):*
> ```XML
>     }
> 
>     // Skip variable definition.
> ```

skip?
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 1021 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6255#-O5EEzn_5aJLYg0sfN9F:-O5EEzn_5aJLYg0sfN9G:ban5pms) ([raw file](https://github.com/starkware-libs/cairo/blob/483847dbab4fa9e0419f423dd25925add389fddb/crates/cairo-lang-language-server/src/lib.rs#L1021)):*
> ```XML
>     } else {
>         None
>     }
> ```

let's stick with single style of returning



_Suggestion:_
```XML
    // Skip variable definition.
    if db.first_ancestor_of_kind(identifier.as_syntax_node(), SyntaxKind::StatementLet).is_none() {
        let item = match lookup_items.first().copied()? {
            LookupItemId::ModuleItem(item) => {
                ResolvedGenericItem::from_module_item(db, item).to_option()?
            }
            LookupItemId::TraitItem(trait_item) => {
                if let TraitItemId::Function(trait_fn) = trait_item {
                    ResolvedGenericItem::TraitFunction(trait_fn)
                } else {
                    ResolvedGenericItem::Trait(trait_item.trait_id(db))
                }
            }
            LookupItemId::ImplItem(impl_item) => {
                ResolvedGenericItem::Impl(impl_item.impl_def_id(db))
            }
        };

        return Some((ResolvedItem::Generic(item.clone()), resolved_generic_item_def(db, item)?));
    }
    
    None
```

**Review by Draggu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6255)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @mkaput, @orizi, and @piotmag769)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6255#-O5DLTHP-EjbzBxaSrxX):*
Done.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 999 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6255#-O5DNv7Q5j579351DvNT:-O5EEAOO3uoA8qPEkNBc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/590e171ddc2c3eb993e22b077abf6ae3c04f4352/crates/cairo-lang-language-server/src/lib.rs#L999)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

please add a comment stating that you're looking for variable definitions here
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/tests/test_data/hover/basic.txt` line 323 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6255#-O4zyoZYEQZOQz_cC1mQ:-O5EEBcb9vDw3VNSKdkL:b-kc93rl) ([raw file](https://github.com/starkware-libs/cairo/blob/590e171ddc2c3eb993e22b077abf6ae3c04f4352/crates/cairo-lang-language-server/tests/test_data/hover/basic.txt#L323)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I'm not sure. Technically, it is because we're inside an `impl` so we are in a concrete context. But UX-wise, it would also be nice to get trait info alongside. Topic for a separate issue nonetheless.
</blockquote></details>

Not a simple fix. Track it here https://github.com/starkware-libs/cairo/issues/6287

**Review by mkaput — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6255)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae and @piotmag769)

**Review by piotmag769 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 1 of 3 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6255#-:-O5ELuCf0n1wcCGDC8-0:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, and @mkaput)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 1007 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6255#-O5ENz5i7nJwo4TFUC4p:-O5ENz5i7nJwo4TFUC4q:b-yfezis) ([raw file](https://github.com/starkware-libs/cairo/blob/483847dbab4fa9e0419f423dd25925add389fddb/crates/cairo-lang-language-server/src/lib.rs#L1007)):*
> ```XML
>             }
>             LookupItemId::TraitItem(trait_item) => {
>                 if let TraitItemId::Function(trait_fn) = trait_item {
> ```

Why is it here, but in the `impl` we don't do it?
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 1021 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6255#-O5EEzn_5aJLYg0sfN9F:-O5EMrKh9QWN343SrtPc:b-v5smtw) ([raw file](https://github.com/starkware-libs/cairo/blob/483847dbab4fa9e0419f423dd25925add389fddb/crates/cairo-lang-language-server/src/lib.rs#L1021)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

let's stick with single style of returning
</blockquote></details>

Imo the one you proposed is worse

**Review by Arcticae — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6255#-:-O5IFdRCBcBQjSydVip8:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Draggu)

**Review by Draggu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6255)* status: all files reviewed, 2 unresolved discussions (waiting on @mkaput and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 1000 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6255#-O5EFHPT1bUmytgx875C:-O5II9nS7q5ls0ByKEet:b-yfbvoh) ([raw file](https://github.com/starkware-libs/cairo/blob/483847dbab4fa9e0419f423dd25925add389fddb/crates/cairo-lang-language-server/src/lib.rs#L1000)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

skip?
</blockquote></details>

If this check is missing we would get parent `ModuleItem` for variable.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 1007 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6255#-O5ENz5i7nJwo4TFUC4p:-O5IEkHUEIyebuhML41i:ba3jung) ([raw file](https://github.com/starkware-libs/cairo/blob/483847dbab4fa9e0419f423dd25925add389fddb/crates/cairo-lang-language-server/src/lib.rs#L1007)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Why is it here, but in the `impl` we don't do it?
</blockquote></details>

Because `ResolvedGenericItem` has only 1 variant for `Impl` and 2 for `Trait`.

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6255)* status: all files reviewed, 2 unresolved discussions (waiting on @Draggu and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 1000 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6255#-O5EFHPT1bUmytgx875C:-O5IJR3U3kmIdj28qmfZ:bcs00rq) ([raw file](https://github.com/starkware-libs/cairo/blob/483847dbab4fa9e0419f423dd25925add389fddb/crates/cairo-lang-language-server/src/lib.rs#L1000)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

If this check is missing we would get parent `ModuleItem` for variable.
</blockquote></details>

please leave this information in code as a comment

**Review by piotmag769 — APPROVED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6255)* status: all files reviewed, 1 unresolved discussion (waiting on @Draggu)

**Review by Draggu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6255)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @mkaput and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 1000 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6255#-O5EFHPT1bUmytgx875C:-O5IR9Pt2NiJ3B6OZU5z:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/483847dbab4fa9e0419f423dd25925add389fddb/crates/cairo-lang-language-server/src/lib.rs#L1000)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

please leave this information in code as a comment
</blockquote></details>

Done.

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6255#-:-O5IRUaA-0M0uV61CCuw:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Draggu)

**Pull request merged**
