### PR TITLE
Formatter: Simplify the break line points types (Formatter temporary broken).

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1267)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1267)* status: all files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/formatter/src/formatter.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJ6BaUU8emF4F0Ytpc2:-NJ6BaUU8emF4F0Ytpc3:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/48fc99ca62dac03f50ceafd1e447ada51ab78d0c/crates/formatter/src/formatter.rs#L27)):*
> ```XML
>     /// List breaks are similar to non-dangling points, but have a non-indented trailing suffix.
>     /// Should only be used for separated lists.
>     /// For example, struct c`tor:
> ```





_Suggestion:_
```XML
struct c'tor:
```
___
*[`crates/formatter/src/formatter.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJ6J2Sz4ppZk4EKh4SL:-NJ6J2Sz4ppZk4EKh4SM:bnaqog6) ([raw file](https://github.com/starkware-libs/cairo/blob/48fc99ca62dac03f50ceafd1e447ada51ab78d0c/crates/formatter/src/formatter.rs#L70)):*
> ```XML
>     Leading,
>     /// A break line point which appears between two children of a node.
>     Internal,
> ```

I don't see any use of internal - is it added in a following PR?
___
*[`crates/formatter/src/formatter.rs` line 259 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJ6CT6S-Jsp52hteJgb:-NJ6CT6S-Jsp52hteJgc:b-s6fbe) ([raw file](https://github.com/starkware-libs/cairo/blob/48fc99ca62dac03f50ceafd1e447ada51ab78d0c/crates/formatter/src/formatter.rs#L259)):*
> ```XML
>             return vec![self.clone()];
>         }
>         let mut break_line_point_type = if let LineComponent::BreakLinePoint(properties) =
> ```

Unrelated to this pr but you could use here extract_matches!



_Code quote:_
```XML
        let mut break_line_point_type = if let LineComponent::BreakLinePoint(properties) =
            &self.children[breaking_positions[0]]
        {
            properties.break_type.clone()
        } else {
            unreachable!("Index is taken from a break line points positions vector.");
        };
```
___
*[`crates/formatter/src/formatter.rs` line 515 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJ6G_uBAjM4EhhC3xdy:-NJ6G_uBAjM4EhhC3xdz:bvhp9w4) ([raw file](https://github.com/starkware-libs/cairo/blob/48fc99ca62dac03f50ceafd1e447ada51ab78d0c/crates/formatter/src/formatter.rs#L515)):*
> ```XML
> 
>             if let Some(break_properties) =
>                 syntax_node.get_break_line_point_properties(self.db, BreakingPosition::Internal)
> ```

Call this once - outside the if



_Code quote:_
```XML
            if let Some(break_properties) =
                syntax_node.get_break_line_point_properties(self.db, BreakingPosition::Internal)
```
___
*[`crates/formatter/src/formatter.rs` line 518 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJ6GnfJDu7kyFbSe5mH:-NJ6GnfJDu7kyFbSe5mI:b-kibn9t) ([raw file](https://github.com/starkware-libs/cairo/blob/48fc99ca62dac03f50ceafd1e447ada51ab78d0c/crates/formatter/src/formatter.rs#L518)):*
> ```XML
>             {
>                 match break_properties.break_type {
>                     BreakLinePointType::SeparatedListBreak if i % 2 == 1 && i != n_children - 1 => {
> ```

extract to a var `is_last_child` or similar



_Code quote:_
```XML
i != n_children - 1
```
___
*[`crates/formatter/src/node_properties.rs` line 169 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJ6FDOc853E3trdiqji:-NJ6FDOc853E3trdiqjj:b4jsunu) ([raw file](https://github.com/starkware-libs/cairo/blob/48fc99ca62dac03f50ceafd1e447ada51ab78d0c/crates/formatter/src/node_properties.rs#L169)):*
> ```XML
>         match self.kind(db) {
>             SyntaxKind::ExprList => Some(BreakLinePointProperties {
>                 precedence: 6,
> ```

I don't like the global precedence. Let's discuss



_Code quote:_
```XML
precedence: 6
```
___
*[`crates/formatter/src/node_properties.rs` line 186 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJ6IMx32ia7n6Ks6bG2:-NJ6IMx32ia7n6Ks6bG3:b-5kb41w) ([raw file](https://github.com/starkware-libs/cairo/blob/48fc99ca62dac03f50ceafd1e447ada51ab78d0c/crates/formatter/src/node_properties.rs#L186)):*
> ```XML
>                         break_type: BreakLinePointType::Dangling,
>                     })
>                 } else {
> ```

same below



_Suggestion:_
```XML
            (SyntaxKind::TokenPlus | SyntaxKind::TokenMinus) if position == BreakingPosition::Leading => {
                Some(BreakLinePointProperties {
                    precedence: 10,
                    break_type: BreakLinePointType::Dangling,
                })
            }
```

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1267)* status: all files reviewed, 18 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/formatter/src/formatter.rs` line 11 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJEkfo41-7uGn--a1DO:-NJEkfo41-7uGn--a1DP:b-4wftub) ([raw file](https://github.com/starkware-libs/cairo/blob/0ca5e6680abc3f661fe7fe50207dbf67c3cae37f/crates/formatter/src/formatter.rs#L11)):*
> ```XML
> use crate::FormatterConfig;
> 
> #[derive(Clone, Debug)]
> ```

Add Copy, remove clone()s across the code.



_Code quote:_
```XML
g)]
```
___
*[`crates/formatter/src/formatter.rs` line 14 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJEjGPr8MZ33RrYnFQO:-NJEjGPr8MZ33RrYnFQP:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0ca5e6680abc3f661fe7fe50207dbf67c3cae37f/crates/formatter/src/formatter.rs#L14)):*
> ```XML
> /// Defines the break point behaviour.
> /// Defined in get_break_line_point_properties.
> pub enum BreakLinePointType {
> ```





_Suggestion:_
```XML
BreakLinePointIndentation
```
___
*[`crates/formatter/src/formatter.rs` line 233 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJEjn5e4O69hmgQYeV9:-NJEjn5e4O69hmgQYeVA:bndnftk) ([raw file](https://github.com/starkware-libs/cairo/blob/0ca5e6680abc3f661fe7fe50207dbf67c3cae37f/crates/formatter/src/formatter.rs#L233)):*
> ```XML
>     /// Breaks the LineTree into a vector of LineTrees
>     /// according to the lowest precedence break line point found in the LineTree.
>     fn to_broken_tree(&self, tab_size: usize) -> Vec<LineBuilder> {
> ```

1. rename to break_line_tree or similar.
2. rephrase documentation - is it breaking only once according to the lowest precedence? is it doing it repeatedly until each line tree fits in a line?

(also - maybe the right term is the highest precedence, and you can add in parens that this is the lowest number).



_Code quote:_
```XML
    /// Breaks the LineTree into a vector of LineTrees
    /// according to the lowest precedence break line point found in the LineTree.
    fn to_broken_tree(&self, tab_size: usize) -> Vec<LineBuilder> {
```
___
*[`crates/formatter/src/formatter.rs` line 234 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJEluId32WIOr3XbW6w:-NJEluId32WIOr3XbW6x:b-l6mkjh) ([raw file](https://github.com/starkware-libs/cairo/blob/0ca5e6680abc3f661fe7fe50207dbf67c3cae37f/crates/formatter/src/formatter.rs#L234)):*
> ```XML
>     /// according to the lowest precedence break line point found in the LineTree.
>     fn to_broken_tree(&self, tab_size: usize) -> Vec<LineBuilder> {
>         let mut breaking_positions = self.get_preceding_break_points_indices();
> ```

rename



_Code quote:_
```XML
get_preceding_break_points_indices
```
___
*[`crates/formatter/src/formatter.rs` line 238 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJEkKn11qTWLJbuQT7r:-NJEkKn11qTWLJbuQT7s:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0ca5e6680abc3f661fe7fe50207dbf67c3cae37f/crates/formatter/src/formatter.rs#L238)):*
> ```XML
>             return vec![self.clone()];
>         }
>         let break_line_point_type =
> ```





_Suggestion:_
```XML
break_line_point_indentation
```
___
*[`crates/formatter/src/formatter.rs` line 241 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJEkoIP569Hz6DoT1P2:-NJEkoIP569Hz6DoT1P3:bck65tk) ([raw file](https://github.com/starkware-libs/cairo/blob/0ca5e6680abc3f661fe7fe50207dbf67c3cae37f/crates/formatter/src/formatter.rs#L241)):*
> ```XML
>             extract_matches!(&self.children[breaking_positions[0]], LineComponent::BreakLinePoint)
>                 .break_type
>                 .clone();
> ```

remove after deriving Copy.



_Code quote:_
```XML
.clone()
```
___
*[`crates/formatter/src/formatter.rs` line 245 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJEneI8A8h2qpSh_dWA:-NJEneI8A8h2qpSh_dWB:b-9v8c11) ([raw file](https://github.com/starkware-libs/cairo/blob/0ca5e6680abc3f661fe7fe50207dbf67c3cae37f/crates/formatter/src/formatter.rs#L245)):*
> ```XML
>         // TODO(Gil): Support empty lines break points where allowed.
>         if *breaking_positions.last().unwrap() == self.children.len() - 1 {
>             breaking_positions.pop();
> ```

1. change to loop
2. check if last child is breakpoint.



_Code quote:_
```XML
        if *breaking_positions.last().unwrap() == self.children.len() - 1 {
            breaking_positions.pop();
        }
```
___
*[`crates/formatter/src/formatter.rs` line 249 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJEpRJn4Gf8VBbgdlK_:-NJEpRJn4Gf8VBbgdlKa:b9hgdh1) ([raw file](https://github.com/starkware-libs/cairo/blob/0ca5e6680abc3f661fe7fe50207dbf67c3cae37f/crates/formatter/src/formatter.rs#L249)):*
> ```XML
>         let base_indent = self.get_leading_indent();
>         let mut trees: Vec<LineBuilder> = vec![LineBuilder::new()];
>         trees.last_mut().unwrap().push_indent(base_indent);
> ```

build directly with the "changed" item.
___
*[`crates/formatter/src/formatter.rs` line 251 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJEqvlYA-1osou0SYbT:-NJEqvlYA-1osou0SYbU:b3vsik8) ([raw file](https://github.com/starkware-libs/cairo/blob/0ca5e6680abc3f661fe7fe50207dbf67c3cae37f/crates/formatter/src/formatter.rs#L251)):*
> ```XML
>         trees.last_mut().unwrap().push_indent(base_indent);
>         let mut added_indent = 0;
>         let mut prev_position = 0;
> ```

better name and/or document.
___
*[`crates/formatter/src/formatter.rs` line 253 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJEpdtJ3GhePdSX2H1D:-NJEpdtJ3GhePdSX2H1E:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0ca5e6680abc3f661fe7fe50207dbf67c3cae37f/crates/formatter/src/formatter.rs#L253)):*
> ```XML
>         let mut prev_position = 0;
>         if matches!(
>             break_line_point_type,
> ```





_Suggestion:_
```XML
        let mut prev_position = 0;
        let mut added_indent = match break_line_point_type {
            BreakLinePointType::Indented | BreakLinePointType::IndentedWithTail => tab_size,
            BreakLinePointType::NotIndented => 0,
        };
```
___
*[`crates/formatter/src/formatter.rs` line 259 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJEq3dZ628l7urrrVOK:-NJEq3dZ628l7urrrVOL:bk9z3eq) ([raw file](https://github.com/starkware-libs/cairo/blob/0ca5e6680abc3f661fe7fe50207dbf67c3cae37f/crates/formatter/src/formatter.rs#L259)):*
> ```XML
>         }
> 
>         breaking_positions.push(self.children.len()); // Dummy break line point, simplifies the loop.
> ```

move comment above line



_Code quote:_
```XML
 // Dummy break line point, simplifies the l
```
___
*[`crates/formatter/src/formatter.rs` line 259 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJEqFoz0m_RywM2Bxtx:-NJEqFoz0m_RywM2Bxty:bfc50nj) ([raw file](https://github.com/starkware-libs/cairo/blob/0ca5e6680abc3f661fe7fe50207dbf67c3cae37f/crates/formatter/src/formatter.rs#L259)):*
> ```XML
>         }
> 
>         breaking_positions.push(self.children.len()); // Dummy break line point, simplifies the loop.
> ```

extract to a var before the first use in this function.



_Code quote:_
```XML
self.children.len()
```
___
*[`crates/formatter/src/formatter.rs` line 263 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJErPCDDvvK9j8Z6syG:-NJErPCDDvvK9j8Z6syH:bnslef1) ([raw file](https://github.com/starkware-libs/cairo/blob/0ca5e6680abc3f661fe7fe50207dbf67c3cae37f/crates/formatter/src/formatter.rs#L263)):*
> ```XML
>         // Iterate over the break line points and collect each part between them into one new
>         // LineBuilder.
>         for (i, position) in breaking_positions.iter().enumerate() {
> ```

Another option ( I think it might be clearer) is to iterate only i (0..breaking_positions.len()) and then set start and end of the current sector with i, i+1 or i-1, i.
___
*[`crates/formatter/src/formatter.rs` line 269 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJEt2_Y3IkgUOCJuQCv:-NJEt2_Y3IkgUOCJuQCw:b78k3m8) ([raw file](https://github.com/starkware-libs/cairo/blob/0ca5e6680abc3f661fe7fe50207dbf67c3cae37f/crates/formatter/src/formatter.rs#L269)):*
> ```XML
>                     LineComponent::Space => {
>                         // Ignore spaces at the start of a line
>                         if !trees.last_mut().unwrap().is_only_indents() {
> ```

why mut?



_Code quote:_
```XML
last_mut
```
___
*[`crates/formatter/src/formatter.rs` line 277 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJEuMCu4Y7eQ0fKkRoe:-NJEuMCu4Y7eQ0fKkRof:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0ca5e6680abc3f661fe7fe50207dbf67c3cae37f/crates/formatter/src/formatter.rs#L277)):*
> ```XML
>             }
>             if *position < self.children.len() {
>                 if matches!(break_line_point_type, BreakLinePointType::IndentedWithTail)
> ```





_Suggestion:_
```XML
break_line_point_type == BreakLinePointType::IndentedWithTail
```
___
*[`crates/formatter/src/formatter.rs` line 277 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJEuPLS0fiUo_wwVtdG:-NJEuPLS0fiUo_wwVtdH:b-5pc2q) ([raw file](https://github.com/starkware-libs/cairo/blob/0ca5e6680abc3f661fe7fe50207dbf67c3cae37f/crates/formatter/src/formatter.rs#L277)):*
> ```XML
>             }
>             if *position < self.children.len() {
>                 if matches!(break_line_point_type, BreakLinePointType::IndentedWithTail)
> ```

please document.
+separate ifs if possible.
___
*[`crates/formatter/src/formatter.rs` line 354 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJEvel36RiQx_nLk4UI:-NJEvel36RiQx_nLk4UJ:bdrh1vz) ([raw file](https://github.com/starkware-libs/cairo/blob/0ca5e6680abc3f661fe7fe50207dbf67c3cae37f/crates/formatter/src/formatter.rs#L354)):*
> ```XML
>                 LineComponent::Indent(indent) => leading_indent += *indent,
>                 _ => {
>                     break;
> ```

I think you can change this to while with .next()
___
*[`crates/formatter/src/formatter.rs` line 411 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJEw3aE4-zQZLJsSqeI:-NJEw3aE4-zQZLJsSqeJ:bwcd9bq) ([raw file](https://github.com/starkware-libs/cairo/blob/0ca5e6680abc3f661fe7fe50207dbf67c3cae37f/crates/formatter/src/formatter.rs#L411)):*
> ```XML
>         &self,
>         db: &dyn SyntaxGroup,
>     ) -> (Option<BreakLinePointProperties>, Option<BreakLinePointProperties>);
> ```

Consider a struct



_Code quote:_
```XML
Option<BreakLinePointProperties>, Option<BreakLinePointProperties>
```

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1267)* status: all files reviewed, 10 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/formatter/src/formatter.rs` line 51 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJFhnVQ0SnoKKpgUlGU:-NJFhnVQ0SnoKKpgUlGV:b-v9psrs) ([raw file](https://github.com/starkware-libs/cairo/blob/c72010930d1ec08e10a9885b92fb4a43fb916eb9/crates/formatter/src/formatter.rs#L51)):*
> ```XML
>     pub precedence: usize,
>     /// The breaking behaviour type.
>     pub break_type: BreakLinePointIndentation,
> ```

rename to indentation and adjust comment.



_Code quote:_
```XML
break_type
```
___
*[`crates/formatter/src/formatter.rs` line 125 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJFixzq0cRSMiiYSnq1:-NJFixzr5QjaeDCHgI3q:b-iu48qj) ([raw file](https://github.com/starkware-libs/cairo/blob/c72010930d1ec08e10a9885b92fb4a43fb916eb9/crates/formatter/src/formatter.rs#L125)):*
> ```XML
>     }
>     /// Creates a new line builder initialized with an indent component.
>     pub fn new_with_indent(indent_size: usize) -> Self {
> ```

consider renaming to default and new respectively.



_Code quote:_
```XML
    pub fn new() -> Self {
        Self { children: vec![], is_open: true, break_line_points_buffer: vec![] }
    }
    /// Creates a new line builder initialized with an indent component.
    pub fn new_with_indent(indent_size: usize) -> Self {
```
___
*[`crates/formatter/src/formatter.rs` line 148 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJFjhmX9NifMBvpPsBu:-NJFjhmX9NifMBvpPsBv:b-ryjyhg) ([raw file](https://github.com/starkware-libs/cairo/blob/c72010930d1ec08e10a9885b92fb4a43fb916eb9/crates/formatter/src/formatter.rs#L148)):*
> ```XML
>     /// All subsequent children will be added to this sub builder until set as closed.
>     fn open_sub_builder(&mut self) {
>         let active_builder = self.get_active_builder();
> ```

consider renaming to ..._mut. This is confusing without it.



_Code quote:_
```XML
get_active_builder
```
___
*[`crates/formatter/src/formatter.rs` line 149 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJFjy_56WHmVty9WqiR:-NJFjy_56WHmVty9WqiS:b-fmy746) ([raw file](https://github.com/starkware-libs/cairo/blob/c72010930d1ec08e10a9885b92fb4a43fb916eb9/crates/formatter/src/formatter.rs#L149)):*
> ```XML
>     fn open_sub_builder(&mut self) {
>         let active_builder = self.get_active_builder();
>         active_builder.push_buffered_break_line_points();
> ```

rename to flush_pending...



_Code quote:_
```XML
.push_buffered_break_line_points
```
___
*[`crates/formatter/src/formatter.rs` line 161 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJFkO74DB5ky0lNRNj_:-NJFkO74DB5ky0lNRNja:bkr4gx3) ([raw file](https://github.com/starkware-libs/cairo/blob/c72010930d1ec08e10a9885b92fb4a43fb916eb9/crates/formatter/src/formatter.rs#L161)):*
> ```XML
>     /// Adds a line component as the next child. If the last child is an open LineBuilder the child
>     /// is recursively appended to the sub builder.
>     fn push_child(&mut self, new_comp: LineComponent) {
> ```

or just `component`



_Suggestion:_
```XML
new_component
```
___
*[`crates/formatter/src/formatter.rs` line 164 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJFkdJp22JTpvzmvbyn:-NJFkdJp22JTpvzmvbyo:b-bo5zwj) ([raw file](https://github.com/starkware-libs/cairo/blob/c72010930d1ec08e10a9885b92fb4a43fb916eb9/crates/formatter/src/formatter.rs#L164)):*
> ```XML
>         match new_comp {
>             LineComponent::BreakLinePoint(_) => {
>                 if !self.is_only_indents() {
> ```

move as arm guard
___
*[`crates/formatter/src/formatter.rs` line 169 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJFktxK6yxae5TNHvU8:-NJFktxK6yxae5TNHvU9:b-jkvbu4) ([raw file](https://github.com/starkware-libs/cairo/blob/c72010930d1ec08e10a9885b92fb4a43fb916eb9/crates/formatter/src/formatter.rs#L169)):*
> ```XML
>             }
>             _ => {
>                 let active_builder = self.get_active_builder();
> ```

move this to outside the match and use it also in the first arm.
___
*[`crates/formatter/src/formatter.rs` line 187 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJFl22o3sKLC0j87A0Q:-NJFl22o3sKLC0j87A0R:bfqe7f7) ([raw file](https://github.com/starkware-libs/cairo/blob/c72010930d1ec08e10a9885b92fb4a43fb916eb9/crates/formatter/src/formatter.rs#L187)):*
> ```XML
>         self.push_child(LineComponent::BreakLinePoint(properties));
>     }
>     /// Appends all break line points in the buffer to the builder.
> ```

1. Flush.
2. explain why it's needed and where it should be used.
___
*[`crates/formatter/src/formatter.rs` line 436 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJFswem496NgFqDuH7A:-NJFswem496NgFqDuH7B:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c72010930d1ec08e10a9885b92fb4a43fb916eb9/crates/formatter/src/formatter.rs#L436)):*
> ```XML
>     ) -> WrappingBreakLinePoints;
>     /// Returns true if the node is protected from breaking unless no other break points exists.
>     /// For example break points inside ExprParenthesized should only be used if there are no break
> ```





_Suggestion:_
```XML
    /// Returns true if the node is protected from breaking unless no other break points exist.
    /// For example break points inside ExprParenthesized should only be used if there are no break
    /// points outside the parentheses. Only applicable for internal nodes.
```
___
*[`crates/formatter/test_data/cairo_files/linebreaking.cairo` line 13 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJFtK5p1CMTp8WeFwtx:-NJFtK5p1CMTp8WeFwty:blak8km) ([raw file](https://github.com/starkware-libs/cairo/blob/c72010930d1ec08e10a9885b92fb4a43fb916eb9/crates/formatter/test_data/cairo_files/linebreaking.cairo#L13)):*
> ```Cairo
>     }
> 
> func bar(first_arg: T, second_arg: T, third_arg: T, fourth_arg: T, fifth_arg: T, sixth_arg: T, seventh_arg: T,) -> T {
> ```

Why is this comma added? Did you add it manually? If so - why?



_Code quote:_
```Cairo
,
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1267)* status: all files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/formatter/src/formatter.rs` line 164 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJFkdJp22JTpvzmvbyn:-NJFyEwL-OmZKed5mqmE:b-pgtu1i) ([raw file](https://github.com/starkware-libs/cairo/blob/c72010930d1ec08e10a9885b92fb4a43fb916eb9/crates/formatter/src/formatter.rs#L164)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

move as arm guard
</blockquote></details>

But then the else case will go to the default arm
___
*[`crates/formatter/src/formatter.rs` line 169 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJFktxK6yxae5TNHvU8:-NJFxw2n4fn1NnxRWuVb:bmeh718) ([raw file](https://github.com/starkware-libs/cairo/blob/c72010930d1ec08e10a9885b92fb4a43fb916eb9/crates/formatter/src/formatter.rs#L169)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

move this to outside the match and use it also in the first arm.
</blockquote></details>

It prevents the use of "is_only_indents" since it mutably borrows self.
___
*[`crates/formatter/test_data/cairo_files/linebreaking.cairo` line 13 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJFtK5p1CMTp8WeFwtx:-NJFybedE0blyusX_Lwx:banfexi) ([raw file](https://github.com/starkware-libs/cairo/blob/c72010930d1ec08e10a9885b92fb4a43fb916eb9/crates/formatter/test_data/cairo_files/linebreaking.cairo#L13)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Why is this comma added? Did you add it manually? If so - why?
</blockquote></details>

Manually, to cover the case of two consecutive break points.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1267#-:-NJJvuVuAWtiUACmY4nQ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/formatter/src/formatter.rs` line 164 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1267#-NJFkdJp22JTpvzmvbyn:-NJJuUIi3keM0pKNNv2y:b-t2p3xm) ([raw file](https://github.com/starkware-libs/cairo/blob/c72010930d1ec08e10a9885b92fb4a43fb916eb9/crates/formatter/src/formatter.rs#L164)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

But then the else case will go to the default arm
</blockquote></details>

You can have another empty arm without the guard. But in that case it's not super important - your call.

**Pull request merged**
