### PR TITLE
Update statements functions

### PR DESCRIPTION
**Pull request by piotmag769**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5630)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5630)* status: all files reviewed, 1 unresolved discussion (waiting on @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5630#-NyfDMfCDk9wQcMOkBvX:-NyfDMfD9LLvX_ImCXEz:b5bcy3x) (no related file):*
can you add a simple example test at `crates/cairo-lang-sierra-generator/src/statement_location_test_data/simple`?

___

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5630)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5630#-NyfDMfCDk9wQcMOkBvX:-NyfKrOa2GD2-FRpVRdw:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can you add a simple example test at `crates/cairo-lang-sierra-generator/src/statement_location_test_data/simple`?
</blockquote></details>

Done.

___

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5630)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5630#-NyfDMfCDk9wQcMOkBvX:-NyfL2Ii6NJusoBoRFzA:bdpbwlk) (no related file):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You can see there is no `In function: (...)` for `Self::eq(lhs, rhs)` parts of code

___

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5630#-:-NyfMuvdA2gHayvqAGJH:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @piotmag769)

**Review by piotmag769 — COMMENTED** [review]
Ready to be merged

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5630#-:-NykAQdm557MEmDkKWHP:b-rtuu0q)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @piotmag769)

**Review by piotmag769 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5630#-:-NykA_-W19svg5BWy8eC:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @piotmag769)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5630)* status: all files reviewed, 1 unresolved discussion (waiting on @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5630#-NylIOBJDXaxb14d38MR:-NylIOBJDXaxb14d38MS:b3u1qab) (no related file):*
this causes the runner to fail.

___

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5630)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5630#-NylIOBJDXaxb14d38MR:-NyoWgUr2CYYNIcX0-2u:b-71tuuw) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this causes the runner to fail.
</blockquote></details>

Should be fixed now. For corelib the first stable location may point to the `Self::eq(lhs, rhs)` (which makes sense).

___

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5630#-:-NyofdwQ4sFGTJX0mJaq:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @piotmag769)

**Pull request merged**
