### PR TITLE
refacto: add no_std compatible crate cairo-lang-straknet-casm-contract-class

### PR DESCRIPTION
**Pull request by tdelabro**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4790)

### CODE REVIEW

**Comment by tdelabro** [comment]
@orizi Can you give it a look, please?
It should be the last one required to have the cairo-vm run cairo1 in no_std

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4790)* status: 6 of 15 files reviewed, 1 unresolved discussion (waiting on @tdelabro)

___
*[`crates/cairo-lang-starknet-casm-contract-class/Cargo.toml` line 2 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4790#-Nny90ST7FWjj0pyGrWp:-Nny90ST7FWjj0pyGrWq:b-cu1eto) ([raw file](https://github.com/starkware-libs/cairo/blob/b87cb1e9bc847240c30bee548279fd2303d4da8b/crates/cairo-lang-starknet-casm-contract-class/Cargo.toml#L2)):*
> ```TOML
> [package]
> name = "cairo-lang-starknet-casm-contract-class"
> ```

Other contract classes would never be required?
What else would you expect to need in the low level structure?
Wondering if to just move all starknet defintions into a new crate

**Review by tdelabro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4790)* status: 6 of 15 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-starknet-casm-contract-class/Cargo.toml` line 2 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4790#-Nny90ST7FWjj0pyGrWp:-NnyPiVd31vMVian8eAi:b6os6ce) ([raw file](https://github.com/starkware-libs/cairo/blob/b87cb1e9bc847240c30bee548279fd2303d4da8b/crates/cairo-lang-starknet-casm-contract-class/Cargo.toml#L2)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Other contract classes would never be required?
What else would you expect to need in the low level structure?
Wondering if to just move all starknet defintions into a new crate
</blockquote></details>

https://github.com/search?q=repo%3Alambdaclass%2Fcairo-vm%20cairo_lang_starknet%3A%3A&type=code

Those were the only symbols used by the VM 6 months ago and still are.
Others may become required too in the future, but it seems pretty stable so far.

What other types were you thinking about? What are the main public types exposed by cairo-lang-starknet?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4790)* status: 6 of 15 files reviewed, 1 unresolved discussion (waiting on @tdelabro)

___
*[`crates/cairo-lang-starknet-casm-contract-class/Cargo.toml` line 2 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4790#-Nny90ST7FWjj0pyGrWp:-No2RA6t7xzK8zUcLTmS:bwxtrrt) ([raw file](https://github.com/starkware-libs/cairo/blob/b87cb1e9bc847240c30bee548279fd2303d4da8b/crates/cairo-lang-starknet-casm-contract-class/Cargo.toml#L2)):*
<details><summary><i>Previously, tdelabro (Timothée Delabrouille) wrote…</i></summary><blockquote>

https://github.com/search?q=repo%3Alambdaclass%2Fcairo-vm%20cairo_lang_starknet%3A%3A&type=code

Those were the only symbols used by the VM 6 months ago and still are.
Others may become required too in the future, but it seems pretty stable so far.

What other types were you thinking about? What are the main public types exposed by cairo-lang-starknet?
</blockquote></details>

separating the plugin + abi generator (including the non-casm ContractClass creation) makes more sense.
Creating a crate that i would like to get rid of, is not as good.

especially with a mouthful name such as `starknet-casm-contract-class`.

So seperation should be more in the venue of:
Plugin + ABI generation
The constructs (ContractClass, CasmContractClass, ABI definition)

Names suggestion(?):
starknet
starknet-definitions

**Comment by tdelabro** [comment]
superseded by #4811

**Pull request closed without merging**
