### PR TITLE
cairo-vm v0.6

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3441)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
split PRs

> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3441#-:-NYHlSSX9KLju1I7zEec:b-7uh22i)* status: 0 of 39 files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by dorimedini-starkware — COMMENTED** [review]
[Here's a PR](https://reviewable.io/reviews/starkware-libs/cairo/3443) for bumping the version.
And why over 2.0.0-rc2 branch? Shouldn't new versions come from `main`?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3441#-:-NYHuPI3EgWKJ5ZX8g-9:b-49nyg7)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware and @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 36 of 39 files at r3, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3441)* status: 37 of 40 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 39 of 39 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3441#-:-NYIE9F-36K0SaO13enm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
