### PR TITLE
LS: Hide amount of parallelism as internal detail of `thread::Pool`

### PR DESCRIPTION
**Pull request by mkaput**
**Stack**:
- #6508
- #6507
- #6506
- #6505
- #6504 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by piotmag769 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6504#-:-O9oD8VB9Ll4KXzw4G4n:bnfp4nl)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/src/server/schedule/thread/pool.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6504#-O9oDP9Q0nNCq5FHTkd2:-O9oDP9RD1qzwsPaYvHH:bh6hhyv) ([raw file](https://github.com/starkware-libs/cairo/blob/fe45ade79ac10024f04bad26651802e59278de37/crates/cairo-lang-language-server/src/server/schedule/thread/pool.rs#L52)):*
> ```XML
>         const INITIAL_PRIORITY: ThreadPriority = ThreadPriority::Worker;
> 
>         let threads = std::thread::available_parallelism().map(usize::from).unwrap_or(1);
> ```

Should be `unwrap_or(4)`

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6504)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/server/schedule/thread/pool.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6504#-O9oDP9Q0nNCq5FHTkd2:-O9oJhMC-EXHZxxEo9U4:bihc1x3) ([raw file](https://github.com/starkware-libs/cairo/blob/fe45ade79ac10024f04bad26651802e59278de37/crates/cairo-lang-language-server/src/server/schedule/thread/pool.rs#L52)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Should be `unwrap_or(4)`
</blockquote></details>

why 4 though? I could not trace the source of this arbitrary value.

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6504)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, and @piotmag769)

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6504)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, and @mkaput)

___
*[`crates/cairo-lang-language-server/src/server/schedule/thread/pool.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6504#-O9oDP9Q0nNCq5FHTkd2:-O9osqJF86cZjwS-_k7p:b213cjk) ([raw file](https://github.com/starkware-libs/cairo/blob/fe45ade79ac10024f04bad26651802e59278de37/crates/cairo-lang-language-server/src/server/schedule/thread/pool.rs#L52)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

why 4 though? I could not trace the source of this arbitrary value.
</blockquote></details>

Tbh it's like whatever, but I guess the 4 will have a better UX if we have more threads switching contexts

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6504)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/server/schedule/thread/pool.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6504#-O9oDP9Q0nNCq5FHTkd2:-O9sK_rs4BAqdeoSpZix:b3z1f9p) ([raw file](https://github.com/starkware-libs/cairo/blob/fe45ade79ac10024f04bad26651802e59278de37/crates/cairo-lang-language-server/src/server/schedule/thread/pool.rs#L52)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Tbh it's like whatever, but I guess the 4 will have a better UX if we have more threads switching contexts
</blockquote></details>

OK. I've read this function's docs, and it looks like it (almost) always if there are missing permissions. So I think it might be more probable that a multicore machine lacks permissions than single-core one does, nowadays. Done.

**Review by piotmag769 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6504)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @orizi)

**Review by piotmag769 — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6504)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @orizi)

**Review by Draggu — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6504#-:-O9t4k7G1mqPfqsFp59O:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @orizi)

**Pull request merged**
