### PR TITLE
Removed workspace resolver warning

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4023)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
please check why the udeps ci failed.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4023#-:-NdiH4d81fPMFAw-0gT_:b-gcs58y)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4023)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/felt252.rs` line 147 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4023#-NdjEI6b5ji9rR2SI_em:-NdjEI6c9GM88WTxyhb2:b-jghuzv) ([raw file](https://github.com/starkware-libs/cairo/blob/fecf2b507f2336803527db5066c4932f4ff13da3/crates/cairo-lang-sierra/src/extensions/modules/felt252.rs#L147)):*
> ```XML
>         Self { operator }
>     }
>     const ADD: &'static str = "felt252_add_const";
> ```

is this related to the resolved change?



_Code quote:_
```XML
onst ADD: &'static str = "felt252_add_const";
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4023)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/felt252.rs` line 147 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4023#-NdjEI6b5ji9rR2SI_em:-NdjzVm0-dZ0peIbLhQK:b5kx7wr) ([raw file](https://github.com/starkware-libs/cairo/blob/fecf2b507f2336803527db5066c4932f4ff13da3/crates/cairo-lang-sierra/src/extensions/modules/felt252.rs#L147)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

is this related to the resolved change?
</blockquote></details>

udeps showed me those as errors, so I fixed.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
now this PR now longer 

> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4023#-:-Ndk-PdnABb0cd3lB_4z:b-swp01q)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`Cargo.toml` line 5 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4023#-Ndk-W0N52cmg97mpnhD:-Ndk-W0N52cmg97mpnhE:b3nm2zu) ([raw file](https://github.com/starkware-libs/cairo/blob/d47d438c08406013a894cde3bb9d521e5408eb67/Cargo.toml#L5)):*
> ```TOML
> 
> [workspace]
> resolver = "2"
> ```

why did you revert this change?



_Code quote:_
```TOML
resolver = "2"
```

**Comment by ilyalesokhin-starkware** [comment]
sorry ignore my comment above.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4023)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`Cargo.toml` line 5 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4023#-Ndk-W0N52cmg97mpnhD:-Ndk7V8L6FTip4rtpeyS:b11mmqy) ([raw file](https://github.com/starkware-libs/cairo/blob/d47d438c08406013a894cde3bb9d521e5408eb67/Cargo.toml#L5)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why did you revert this change?
</blockquote></details>

good catch, probably a rebase. Re-added it.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4023#-:-Ndz8deA3Xi_rG9uH1T6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Comment by yuvalsw** [comment]
change traget

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 5 files at r2, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4023)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4023)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
