### PR TITLE
Introduce `QueryAttrs::query_attr` and `QueryAttrs::find_attr`

### PR DESCRIPTION
**Pull request by mkaput**
**Stack**:
- #2731
- #2730
- #2738
- #2737
- #2736
- #2732
- #2729 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2729)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2729)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @mkaput and @yuvalsw)

___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2729#-NSJvR5U3wD6cNiNhuAz:-NSJvR5U3wD6cNiNhuB-:bhzxptc) ([raw file](https://github.com/starkware-libs/cairo/blob/c33322fbc946798fd25164f9d493f3f61f481c1a/crates/cairo-lang-plugins/src/plugins/config.rs#L21)):*
> ```XML
>     fn generate_code(&self, db: &dyn SyntaxGroup, item_ast: ast::Item) -> PluginResult {
>         let cfg_set = db.cfg_set();
>         if let Some(attr) = item_ast.find_attr(db, "cfg") {
> ```

What if there are multiple attrs for "cfg"?

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2729)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @mkaput and @yuvalsw)

___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2729#-NSJvR5U3wD6cNiNhuAz:-NSKDO4PAiRBms6kXlbr:b-x6z0f5) ([raw file](https://github.com/starkware-libs/cairo/blob/40126d50c8c7b79f0de3e2274a18a0bb6e9a7e0f/crates/cairo-lang-plugins/src/plugins/config.rs#L21)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

What if there are multiple attrs for "cfg"?
</blockquote></details>

:100: that's a good catch!

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2729)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2729#-NSJvR5U3wD6cNiNhuAz:-NSKN3F_8E3Tn7bJZPTG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/40126d50c8c7b79f0de3e2274a18a0bb6e9a7e0f/crates/cairo-lang-plugins/src/plugins/config.rs#L21)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

:100: that's a good catch!
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2729#-:-NSM0VNK4JjiTTeasXQn:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware and @yuvalsw)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2729)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2729#-:-NSZ_Nal7w28Dqy_GCwY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2729)* status: all files reviewed, 2 unresolved discussions (waiting on @mkaput)

___
*[`crates/cairo-lang-plugins/src/plugins/panicable.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2729#-NS_0E2IEPNPTBa0cbko:-NS_0E2IEPNPTBa0cbkp:b-z2h8oy) ([raw file](https://github.com/starkware-libs/cairo/blob/562484a84f9ff944953300e02f58c373dad45c01/crates/cairo-lang-plugins/src/plugins/panicable.rs#L50)):*
> ```XML
> ) -> PluginResult {
>     let remove_original_item = false;
>     if let Some(attr) = attributes.find_attr(db, "panic_with") {
> ```

This means that if there are multiple "panic_with", we take the first one.
I assume we don't have it anywhere, but worth noting, and also considering if we don't want the last instead.
WDYT?
___
*[`crates/cairo-lang-syntax/src/node/helpers.rs` line 138 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2729#-NS_-swK8xc4v2Y3O_Z-:-NS_-swL-E0Y5o8fjs57:b9ehmng) ([raw file](https://github.com/starkware-libs/cairo/blob/562484a84f9ff944953300e02f58c373dad45c01/crates/cairo-lang-syntax/src/node/helpers.rs#L138)):*
> ```XML
>     }
> 
>     fn has_attr(&self, db: &dyn SyntaxGroup, attr: &str) -> bool {
> ```

please doc functions.



_Code quote:_
```XML
    fn query_attr(&self, db: &dyn SyntaxGroup, attr: &str) -> Vec<Attribute> {
        self.attributes_elements(db).into_iter().filter(|a| a.attr(db).text(db) == attr).collect()
    }

    fn find_attr(&self, db: &dyn SyntaxGroup, attr: &str) -> Option<Attribute> {
        self.query_attr(db, attr).into_iter().next()
    }

    fn has_attr(&self, db: &dyn SyntaxGroup, attr: &str) -> bool {
```

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2729#-:-NS_0gwhE_pO3cMHvwOl:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @mkaput)

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2729)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mkaput)

___
*[`crates/cairo-lang-plugins/src/plugins/panicable.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2729#-NS_0E2IEPNPTBa0cbko:-NSjOMFB6GJzBVxuMX1c:bwg3uui) ([raw file](https://github.com/starkware-libs/cairo/blob/562484a84f9ff944953300e02f58c373dad45c01/crates/cairo-lang-plugins/src/plugins/panicable.rs#L50)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

This means that if there are multiple "panic_with", we take the first one.
I assume we don't have it anywhere, but worth noting, and also considering if we don't want the last instead.
WDYT?
</blockquote></details>

#2732 leaves a TODO for this
___
*[`crates/cairo-lang-syntax/src/node/helpers.rs` line 138 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2729#-NS_-swK8xc4v2Y3O_Z-:-NSjOQRe2nVKrZTAAxux:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/562484a84f9ff944953300e02f58c373dad45c01/crates/cairo-lang-syntax/src/node/helpers.rs#L138)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

please doc functions.
</blockquote></details>

Done

**Pull request merged**
