### PR TITLE
Moved corelib to edition2023_11.

### PR DESCRIPTION
**Pull request by orizi**
Includes removing visibility from code that shouldn't be used.

---

**Stack**:
- #4403
- #4400
- #4399 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4399)

### CODE REVIEW

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4399)* status: 0 of 57 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/cairo_project.toml` line 5 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4399#-NjCrhSyE_8oyfIFP5xr:-NjCrhSyE_8oyfIFP5xs:bz9y2dk) ([raw file](https://github.com/starkware-libs/cairo/blob/533b9ce1f98ecdff3b6845070be1ecb9e37f4c44/corelib/cairo_project.toml#L5)):*
> ```TOML
> 
> [config.global]
> edition = "2023_11"
> ```

please also update `Scarb.toml`

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4399)* status: 0 of 57 files reviewed, 1 unresolved discussion (waiting on @mkaput)

___
*[`corelib/cairo_project.toml` line 5 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4399#-NjCrhSyE_8oyfIFP5xr:-NjD74Bs4IhhjN-_fSvU:b-v4uv3k) ([raw file](https://github.com/starkware-libs/cairo/blob/533b9ce1f98ecdff3b6845070be1ecb9e37f4c44/corelib/cairo_project.toml#L5)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

please also update `Scarb.toml`
</blockquote></details>

add some base version there for scarb if you wish to add it.
if you haven't added it somewhere it is not relevant for this PR.

**Review by mkaput — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4399)* status: 0 of 57 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/cairo_project.toml` line 5 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4399#-NjCrhSyE_8oyfIFP5xr:-NjDHogv8tJ7OJ1Vjojr:bd690n3) ([raw file](https://github.com/starkware-libs/cairo/blob/533b9ce1f98ecdff3b6845070be1ecb9e37f4c44/corelib/cairo_project.toml#L5)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add some base version there for scarb if you wish to add it.
if you haven't added it somewhere it is not relevant for this PR.
</blockquote></details>

https://github.com/starkware-libs/cairo/pull/4401

**Review by mkaput — COMMENTED** [review]
> Reviewed 1 of 57 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4399)* status: 2 of 58 files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 53 of 57 files at r1, 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4399)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/ec.cairo` line 133 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4399#-NjIWfuN9cy3L77KvZIx:-NjIWfuN9cy3L77KvZIy:b-yyiezh) ([raw file](https://github.com/starkware-libs/cairo/blob/6627d6df2e9280204adda195c234512a3c757d62/corelib/src/ec.cairo#L133)):*
> ```Cairo
> }
> 
> impl EcPointNeg of Neg<EcPoint> {
> ```

Aren't the operator impls useful?
___
*[`corelib/src/fmt.cairo` line 8 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4399#-NjI_yJp0cfE4eLE5WWl:-NjI_yJp0cfE4eLE5WWm:b-4chdfm) ([raw file](https://github.com/starkware-libs/cairo/blob/6627d6df2e9280204adda195c234512a3c757d62/corelib/src/fmt.cairo#L8)):*
> ```Cairo
> pub struct Formatter {
>     /// The pending result of formatting.
>     pub buffer: ByteArray,
> ```

Not sure it should be pub, but I don't strongly object.



_Code quote:_
```Cairo
pub buffer: ByteArray,
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4399)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`corelib/src/ec.cairo` line 133 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4399#-NjIWfuN9cy3L77KvZIx:-NjIut5rCn8BCfB_ZB79:b-45ma13) ([raw file](https://github.com/starkware-libs/cairo/blob/6627d6df2e9280204adda195c234512a3c757d62/corelib/src/ec.cairo#L133)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Aren't the operator impls useful?
</blockquote></details>

instead i'm removing pubs from all impls that are near the trait or type for now.
if we decide to actually remove the ability to use.
___
*[`corelib/src/fmt.cairo` line 8 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4399#-NjI_yJp0cfE4eLE5WWl:-NjIvFYx7Pqb9rUTU6ok:b50badh) ([raw file](https://github.com/starkware-libs/cairo/blob/6627d6df2e9280204adda195c234512a3c757d62/corelib/src/fmt.cairo#L8)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Not sure it should be pub, but I don't strongly object.
</blockquote></details>

has to be pub for `format!` and others to work.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 27 of 27 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4399#-:-NjMPJ4I18nmY3F4m_b7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
