### PR TITLE
Use array! anywhere possible.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3502)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3502)* status: 1 of 14 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3502#-NYmv8E31cCoQPEBkJRR:-NYmv8E31cCoQPEBkJRS:b1rmgm3) (no related file):*
remove `mut`s and inline wherever possibl.e

___
___
*[`corelib/src/lib.cairo` line 281 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3502#-NYmuSyx7EqxzoSt-15T:-NYmuSyyE1Zz3Z60BK_I:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/70e43807d8bbae313d5364065691ee40aabf6884/corelib/src/lib.cairo#L281)):*
> ```Cairo
> fn panic_with_felt252(err_code: felt252) -> never {
>     let mut data = array!(err_code);
>     panic(data)
> ```





_Suggestion:_
```Cairo
    panic(array!(err_code))
```
___
*[`corelib/src/test/array_test.cairo` line 10 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3502#-NYmul212JaIc4noo4wP:-NYmul212JaIc4noo4wQ:b-ovylxj) ([raw file](https://github.com/starkware-libs/cairo/blob/70e43807d8bbae313d5364065691ee40aabf6884/corelib/src/test/array_test.cairo#L10)):*
> ```Cairo
>     let mut arr = array!(10, 11, 12);
>     arr
> }
> ```

remove entirely.



_Code quote:_
```Cairo
fn test_array_helper() -> Array<felt252> {
    let mut arr = array!(10, 11, 12);



    arr
}
```

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 5 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3502)* status: 5 of 14 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3502)* status: 5 of 14 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @spapinistarkware)

___
*[`corelib/src/test/keccak_test.cairo` line 43 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3502#-NYqF-o69RFX2nZ8-CXE:-NYqF-o69RFX2nZ8-CXF:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/70e43807d8bbae313d5364065691ee40aabf6884/corelib/src/test/keccak_test.cairo#L43)):*
> ```Cairo
>     assert_eq(@res.low, @0x6510e6fd534f267a01086462df912739, 'Wrong hash value7');
>     assert_eq(@res.high, @0x2d9982dfaf468a9ddf7101b6323aa9d5, 'Wrong hash value8');
> }
> ```





_Suggestion:_
```Cairo
fn test_keccak_hash() {
    let res = keccak::keccak_u256s_le_inputs(array![1].span());
    assert_eq(@res.low, @0x587f7cc3722e9654ea3963d5fe8c0748, 'Wrong hash value1');
    assert_eq(@res.high, @0xa5963aa610cb75ba273817bce5f8c48f, 'Wrong hash value2');

    let res = keccak::keccak_u256s_be_inputs(array![1].span());
    assert_eq(@res.low, @0x326a7e71fdcdee263b071276522d0eb1, 'Wrong hash value3');
    assert_eq(@res.high, @0xf60cfab7e2cb9f2d73b0c2fa4a4bf40c, 'Wrong hash value4');

    let res = keccak::keccak_u256s_le_inputs(array![1, 2, 3, 4].span());
    assert_eq(@res.low, @0x845f8e9f5191367fb5181e74f6eb550d, 'Wrong hash value5');
    assert_eq(@res.high, @0x17a2126cf7391a26b41c36a687090cc5, 'Wrong hash value6');

    let res = keccak::keccak_u256s_be_inputs(array![1, 2, 3, 4].span());
    assert_eq(@res.low, @0x6510e6fd534f267a01086462df912739, 'Wrong hash value7');
    assert_eq(@res.high, @0x2d9982dfaf468a9ddf7101b6323aa9d5, 'Wrong hash value8');
}
```

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3502)* status: 8 of 14 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @spapinistarkware)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3502)* status: 0 of 20 files reviewed, 4 unresolved discussions (waiting on @orizi and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3502#-NYmv8E31cCoQPEBkJRR:-NYsJDbu1e2rHMErvqg6:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove `mut`s and inline wherever possibl.e
</blockquote></details>

Done.

___
___
*[`corelib/src/lib.cairo` line 281 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3502#-NYmuSyx7EqxzoSt-15T:-NYt758Y5pfsSOD1CcBY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/70e43807d8bbae313d5364065691ee40aabf6884/corelib/src/lib.cairo#L281)):*
> ```Cairo
> fn panic_with_felt252(err_code: felt252) -> never {
>     let mut data = array!(err_code);
>     panic(data)
> ```

Done.
___
*[`corelib/src/test/array_test.cairo` line 10 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3502#-NYmul212JaIc4noo4wP:-NYt8UW_AVHCn9cjzZ5M:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/70e43807d8bbae313d5364065691ee40aabf6884/corelib/src/test/array_test.cairo#L10)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove entirely.
</blockquote></details>

Done.
___
*[`corelib/src/test/keccak_test.cairo` line 43 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3502#-NYqF-o69RFX2nZ8-CXE:-NYt8TKP28hSD4G99Y4-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/70e43807d8bbae313d5364065691ee40aabf6884/corelib/src/test/keccak_test.cairo#L43)):*
> ```Cairo
>     assert_eq(@res.low, @0x6510e6fd534f267a01086462df912739, 'Wrong hash value7');
>     assert_eq(@res.high, @0x2d9982dfaf468a9ddf7101b6323aa9d5, 'Wrong hash value8');
> }
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 7 of 20 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3502)* status: 7 of 20 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware and @spapinistarkware)

___
*[`corelib/src/debug.cairo` line 25 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3502#-NYtIGTX4FgnAX9yxWKq:-NYtIGTX4FgnAX9yxWKr:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7fbbc805ffd86fbb9ca1870d51153be27e64002d/corelib/src/debug.cairo#L25)):*
> ```Cairo
> fn print_felt252(message: felt252) {
>     let mut arr = array![message];
>     print(arr);
> ```





_Suggestion:_
```Cairo
    print(array![message]);
```
___
*[`corelib/src/starknet/secp256_trait.cairo` line 143 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3502#-NYtISoNBr-pqJCmoaad:-NYtISoNBr-pqJCmoaae:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7fbbc805ffd86fbb9ca1870d51153be27e64002d/corelib/src/starknet/secp256_trait.cairo#L143)):*
> ```Cairo
>     let mut keccak_input = array![x, y];
>     // Keccak output is little endian.
>     let point_hash_le = keccak_u256s_be_inputs(keccak_input.span());
> ```





_Suggestion:_
```Cairo
    // Keccak output is little endian.
    let point_hash_le = keccak_u256s_be_inputs(array![x, y].span());
```
___
*[`corelib/src/test/array_test.cairo` line 10 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3502#-NYtIe6AEuzfowPikG-0:-NYtIe6AEuzfowPikG-1:bwz265r) ([raw file](https://github.com/starkware-libs/cairo/blob/7fbbc805ffd86fbb9ca1870d51153be27e64002d/corelib/src/test/array_test.cairo#L10)):*
> ```Cairo
> fn test_array() {
>     // TODO(Gil): Fix the inference of literals.
>     let arr = array![10_felt252, 11, 12];
> ```

also everywhere else where required.



_Suggestion:_
```Cairo
    let arr: Array<felt252> = array![10, 11, 12];
```
___
*[`corelib/src/test/keccak_test.cairo` line 9 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3502#-NYtIz5h1pc6ZDeGKXxv:-NYtIz5h1pc6ZDeGKXxw:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7fbbc805ffd86fbb9ca1870d51153be27e64002d/corelib/src/test/keccak_test.cairo#L9)):*
> ```Cairo
> #[available_gas(100000)]
> fn test_keccak_syscall() {
>     let mut input = array![1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17];
> ```





_Suggestion:_
```Cairo
fn test_keccak_syscall() {
    let input = array![1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17];
```
___
*[`crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo` line 103 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3502#-NYtJJKs4SL7WA4MvPf9:-NYtJJKs4SL7WA4MvPfA:by7jwmt) ([raw file](https://github.com/starkware-libs/cairo/blob/7fbbc805ffd86fbb9ca1870d51153be27e64002d/crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo#L103)):*
> ```Cairo
> fn test_wrapper_too_many_enough_args() {
>     let mut calldata = array![1, 2];
>     TestContract::__external::get_plus_2(calldata.span());
> ```

also everywhere else.



_Suggestion:_
```Cairo
    TestContract::__external::get_plus_2(array![1, 2].span());
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3502)* status: 5 of 20 files reviewed, 7 unresolved discussions (waiting on @orizi and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3502#-NYmv8E31cCoQPEBkJRR:-NYtQbDs9ZmRIkdeSARZ:b-9d744x) (no related file):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

And now with the push. Done.

___
___
*[`corelib/src/debug.cairo` line 25 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3502#-NYtIGTX4FgnAX9yxWKq:-NYtLy_v6l79SlfUsNSO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7fbbc805ffd86fbb9ca1870d51153be27e64002d/corelib/src/debug.cairo#L25)):*
> ```Cairo
> fn print_felt252(message: felt252) {
>     let mut arr = array![message];
>     print(arr);
> ```

Done.
___
*[`corelib/src/starknet/secp256_trait.cairo` line 143 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3502#-NYtISoNBr-pqJCmoaad:-NYtMTix4jCfCVSfOZPw:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7fbbc805ffd86fbb9ca1870d51153be27e64002d/corelib/src/starknet/secp256_trait.cairo#L143)):*
> ```Cairo
>     let mut keccak_input = array![x, y];
>     // Keccak output is little endian.
>     let point_hash_le = keccak_u256s_be_inputs(keccak_input.span());
> ```

Done.
___
*[`corelib/src/test/array_test.cairo` line 10 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3502#-NYtIe6AEuzfowPikG-0:-NYtPrQL1kXWhaLfLNCU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7fbbc805ffd86fbb9ca1870d51153be27e64002d/corelib/src/test/array_test.cairo#L10)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

also everywhere else where required.
</blockquote></details>

Done.
___
*[`corelib/src/test/keccak_test.cairo` line 9 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3502#-NYtIz5h1pc6ZDeGKXxv:-NYtPsZfDnBiukX2bin2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7fbbc805ffd86fbb9ca1870d51153be27e64002d/corelib/src/test/keccak_test.cairo#L9)):*
> ```Cairo
> #[available_gas(100000)]
> fn test_keccak_syscall() {
>     let mut input = array![1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17];
> ```

Done.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo` line 103 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3502#-NYtJJKs4SL7WA4MvPf9:-NYtPtYN5qu2LOkqtG-N:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7fbbc805ffd86fbb9ca1870d51153be27e64002d/crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo#L103)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

also everywhere else.
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 20 files at r2, 5 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3502)* status: 11 of 20 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 20 files at r2, 5 of 10 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3502#-:-NZ-ljPcBUD9BEskJXAU:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3502)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3502)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 19 of 20 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3502)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Pull request merged**
