### PR TITLE
LS: Support multi-root-workspaces

### PR DESCRIPTION
**Pull request by Arcticae**
This PR adds support for opening multiple scarb workspaces in one vscode window, like so:
image

Example diagnostics:
image

This solution, in contrast to the previous one, uses only one LS instance - so the resolved scarb versions must align, otherwise it won't work.

### CODE REVIEW

**Review by Draggu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6645)* status: 0 of 2 files reviewed, 12 unresolved discussions (waiting on @Arcticae)

___
*[`vscode-cairo/src/cairols.ts` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6645#-OB_6vwk8yxsYJRYKRaX:-OB_6vwl2E_8ym-_v7YF:b-ym1rpx) ([raw file](https://github.com/starkware-libs/cairo/blob/599ad03e75d0fd867bc6521fb4e73a20e3e063d9/vscode-cairo/src/cairols.ts#L32)):*
> ```XML
> 		return true;
> 	}
>   let primaryExecutable = executables[0]!;
> ```

`const` is equal to `let` in rust and `let` is equal to `let mut`



_Suggestion:_
```XML
const
```
___
*[`vscode-cairo/src/cairols.ts` line 34 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6645#-OB_4kQr7V_ob11oDCZL:-OB_4kQr7V_ob11oDCZM:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/599ad03e75d0fd867bc6521fb4e73a20e3e063d9/vscode-cairo/src/cairols.ts#L34)):*
> ```XML
>   let primaryExecutable = executables[0]!;
> 	
> 	return executables.slice(1).find((x) => primaryExecutable.run.command !== x.run.command) ? false : true;
> ```





_Suggestion:_
```XML
.every((x) => primaryExecutable.run.command === x.run.command)
```
___
*[`vscode-cairo/src/cairols.ts` line 38 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6645#-OB_89k_3nB0xO3dwmUn:-OB_89k_3nB0xO3dwmUo:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/599ad03e75d0fd867bc6521fb4e73a20e3e063d9/vscode-cairo/src/cairols.ts#L38)):*
> ```XML
> 
> export async function setupLanguageServer(ctx: Context): Promise<lc.LanguageClient> {  
>   let executables = await Promise.all(
> ```





_Suggestion:_
```XML
const
```
___
*[`vscode-cairo/src/cairols.ts` line 40 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6645#-OB_5YMz38R6dsBmYXQe:-OB_5YN-DtLABZzB21TE:b7xolkj) ([raw file](https://github.com/starkware-libs/cairo/blob/599ad03e75d0fd867bc6521fb4e73a20e3e063d9/vscode-cairo/src/cairols.ts#L40)):*
> ```XML
>   let executables = await Promise.all(
>     (vscode.workspace.workspaceFolders || []).map(
>       async (workspaceFolder) => await getLanguageServerExecutable(workspaceFolder, ctx)
> ```

In current js versions this does not matter (in older ones it did), but more readable.



_Suggestion:_
```XML
(workspaceFolder) => getLanguageServerExecutable(workspaceFolder, ctx)
```
___
*[`vscode-cairo/src/cairols.ts` line 41 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6645#-OB_5NoQ1gzn9QJF876i:-OB_5NoQ1gzn9QJF876j:b-c3qk2o) ([raw file](https://github.com/starkware-libs/cairo/blob/599ad03e75d0fd867bc6521fb4e73a20e3e063d9/vscode-cairo/src/cairols.ts#L41)):*
> ```XML
>     (vscode.workspace.workspaceFolders || []).map(
>       async (workspaceFolder) => await getLanguageServerExecutable(workspaceFolder, ctx)
>     ).filter((x) => !!x)
> ```

Also this filter should be after `Promise.all`, currently it is non effective as you check if `Promise` is truthy that is always true, we should check on `Promise` value instead.



_Suggestion:_
```XML
Boolean
```
___
*[`vscode-cairo/src/cairols.ts` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6645#-OB_9hsmD-QvPaWprx-t:-OB_9hsn4L4fs5xgYNbp:bq10q1m) ([raw file](https://github.com/starkware-libs/cairo/blob/599ad03e75d0fd867bc6521fb4e73a20e3e063d9/vscode-cairo/src/cairols.ts#L42)):*
> ```XML
>       async (workspaceFolder) => await getLanguageServerExecutable(workspaceFolder, ctx)
>     ).filter((x) => !!x)
>   ) as LSExecutable[];
> ```

`.filter()` in correct place should make this cast unnecessary.
___
*[`vscode-cairo/src/cairols.ts` line 49 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6645#-OB_7Dx98PK4mF-HqfYU:-OB_7Dx98PK4mF-HqfYV:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/599ad03e75d0fd867bc6521fb4e73a20e3e063d9/vscode-cairo/src/cairols.ts#L49)):*
> ```XML
> 
>    // First one is good as any of them since they should be all the same at this point
>   let lsExecutable = executables[0];
> ```





_Suggestion:_
```XML
const
```
___
*[`vscode-cairo/src/cairols.ts` line 53 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6645#-OB_6UP65SNXjBxjH7xA:-OB_6UP65SNXjBxjH7xB:b-iub52v) ([raw file](https://github.com/starkware-libs/cairo/blob/599ad03e75d0fd867bc6521fb4e73a20e3e063d9/vscode-cairo/src/cairols.ts#L53)):*
> ```XML
>   if (!lsExecutable) {
>     throw new Error("Failed to start Cairo LS");
>   }
> ```

https://nodejs.org/api/assert.html#assertvalue-message

this wil make type guard like if too



_Suggestion:_
```XML
  assert(lsExecutable, "Failed to start Cairo LS");
```
___
*[`vscode-cairo/src/cairols.ts` line 54 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6645#-OB_7ODz7oQDBQQloyFJ:-OB_7ODz7oQDBQQloyFK:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/599ad03e75d0fd867bc6521fb4e73a20e3e063d9/vscode-cairo/src/cairols.ts#L54)):*
> ```XML
>     throw new Error("Failed to start Cairo LS");
>   }
>   let { run, scarb } = lsExecutable; 
> ```





_Suggestion:_
```XML
const
```
___
*[`vscode-cairo/src/cairols.ts` line 189 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6645#-OB_7ZaL7a1jWdIvOtKo:-OB_7ZaL7a1jWdIvOtKp:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/599ad03e75d0fd867bc6521fb4e73a20e3e063d9/vscode-cairo/src/cairols.ts#L189)):*
> ```XML
> 
> async function getLanguageServerExecutable(workspaceFolder: vscode.WorkspaceFolder | undefined, ctx: Context): Promise<LSExecutable | undefined> {
>   let scarb = await findScarbForWorkspaceFolder(workspaceFolder, ctx);
> ```





_Suggestion:_
```XML
const
```
___
*[`vscode-cairo/src/cairols.ts` line 191 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6645#-OB_7lEVEP6d03qrjRRH:-OB_7lEVEP6d03qrjRRI:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/599ad03e75d0fd867bc6521fb4e73a20e3e063d9/vscode-cairo/src/cairols.ts#L191)):*
> ```XML
>   let scarb = await findScarbForWorkspaceFolder(workspaceFolder, ctx);
>   try {
>     let provider = await determineLanguageServerExecutableProvider(
> ```





_Suggestion:_
```XML
const
```
___
*[`vscode-cairo/src/cairols.ts` line 200 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6645#-OB_7o75BwVK0Vck5WW1:-OB_7o76-SqGWqv59f3S:b3kun7w) ([raw file](https://github.com/starkware-libs/cairo/blob/599ad03e75d0fd867bc6521fb4e73a20e3e063d9/vscode-cairo/src/cairols.ts#L200)):*
> ```XML
>     ctx.log.error(`${e}`);
>   }
>   return undefined;
> ```

No need for explicit `undefined` but if you see it clearer im ok with keeping it.



_Suggestion:_
```XML
return;
```

**Review by Arcticae — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6645)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`vscode-cairo/src/cairols.ts` line 34 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6645#-OB_4kQr7V_ob11oDCZL:-OBaJ364EgxnMqa31rSm:b-q144hi) ([raw file](https://github.com/starkware-libs/cairo/blob/599ad03e75d0fd867bc6521fb4e73a20e3e063d9/vscode-cairo/src/cairols.ts#L34)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

It's not less optimal
</blockquote></details>

I meant that `find` would stop after the first match of a different version, that's why i chose it
___
*[`vscode-cairo/src/cairols.ts` line 42 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6645#-OB_uyA43Y4qGA-riucb:-OBaI-xy2Dgi_3jkrhOe:b-uvgula) ([raw file](https://github.com/starkware-libs/cairo/blob/4ab2920170e93d51a1b61be06993861a630c41a8/vscode-cairo/src/cairols.ts#L42)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

Array adapters are eager, this is not rust iterator. we check here if all elements are equal so we an compare first with first, this will lead to 1 more compare and 1 less array allocation.
</blockquote></details>

It seems more logical to me this way but i'm not 
___
*[`vscode-cairo/src/cairols.ts` line 56 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6645#-OB_zx9Q1U7MBVO3o9UP:-OBaGlz-5qgkPWbFJW1Y:bgwr24) ([raw file](https://github.com/starkware-libs/cairo/blob/4ab2920170e93d51a1b61be06993861a630c41a8/vscode-cairo/src/cairols.ts#L56)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

Checked and it works without cast, maybe it was confusing with `Boolean` constructor that in fact won't type guard here (my mistake).
</blockquote></details>

No, it doesn't work


(IDE doesn't complain but TS does)
___
*[`vscode-cairo/src/cairols.ts` line 194 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6645#-OB_wZ4BAYrDSlyVs-uf:-OBaH1iJDEdzOf-qWRPK:bd21tl2) ([raw file](https://github.com/starkware-libs/cairo/blob/4ab2920170e93d51a1b61be06993861a630c41a8/vscode-cairo/src/cairols.ts#L194)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

Don't like the name here, but no idea for better. We add scarb here and keep type name of `run` field, it is confusing whenever we uses one with scarb or not
</blockquote></details>

I can change provider's method `languageServerExecutable` to just `executable` if that makes things clearer

**Review by Draggu — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6645#-:-OBeYZ6o1I-oIDXmE2Hr:bnfp4nl)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @mkaput, @orizi, and @piotmag769)

___
*[`vscode-cairo/src/cairols.ts` line 34 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6645#-OB_4kQr7V_ob11oDCZL:-OBeX_0W2Iafvil8kLXd:bjfx00r) ([raw file](https://github.com/starkware-libs/cairo/blob/599ad03e75d0fd867bc6521fb4e73a20e3e063d9/vscode-cairo/src/cairols.ts#L34)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

I meant that `find` would stop after the first match of a different version, that's why i chose it
</blockquote></details>

`every` stops on first `false`
___
*[`vscode-cairo/src/cairols.ts` line 56 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6645#-OB_zx9Q1U7MBVO3o9UP:-OBeY4q07PRMJXhyAoNy:b-b67q2l) ([raw file](https://github.com/starkware-libs/cairo/blob/4ab2920170e93d51a1b61be06993861a630c41a8/vscode-cairo/src/cairols.ts#L56)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

No, it doesn't work


(IDE doesn't complain but TS does)
</blockquote></details>

TS version problem, in `5.3.3` there is no overload for this.
___
*[`vscode-cairo/src/cairols.ts` line 194 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6645#-OB_wZ4BAYrDSlyVs-uf:-OBeYMNP7YyLsLdMTdAM:bc66ypc) ([raw file](https://github.com/starkware-libs/cairo/blob/4ab2920170e93d51a1b61be06993861a630c41a8/vscode-cairo/src/cairols.ts#L194)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

I can change provider's method `languageServerExecutable` to just `executable` if that makes things clearer
</blockquote></details>

```ts
interface LSExecutable {
  run: lc.Executable;
```

this part is confusing for me, but leaving it to you

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6645)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @orizi, and @piotmag769)

___
*[`vscode-cairo/src/cairols.ts` line 42 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6645#-OBfTfLSEIxekCBY9B1w:-OBfTfLSEIxekCBY9B1x:b-1qeiie) ([raw file](https://github.com/starkware-libs/cairo/blob/1475ee3f45087e04c0edd850fb6035d998d4beef/vscode-cairo/src/cairols.ts#L42)):*
> ```XML
> 
>     return versions.every((x) => x === versions[0]);
>   }
> ```

Shouldn't you just ensure `executable.run.command`are the same (+/- environment, maybe even `deepEqual` entire executable object)?

1. You wouldn't need to rely on passing `scarb` instance around and do costly version checks.
2. I have suspicions that Scarb version output is not enough because this will at least not catch out-of-tree builds.
3. You will make this code also work in non-scarb contexts.



_Code quote:_
```XML
  // If every executable is scarb based, check if the versions match
  if (executables.every((v) => !!v.scarb)) {
    const versions = await Promise.all(executables.map((v) => v.scarb!.getVersion(ctx)));

    return versions.every((x) => x === versions[0]);
  }
```
___
*[`vscode-cairo/src/cairols.ts` line 57 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6645#-OBfSk6E8lxe3s_HaJXt:-OBfSk6E8lxe3s_HaJXu:bbkkuwp) ([raw file](https://github.com/starkware-libs/cairo/blob/1475ee3f45087e04c0edd850fb6035d998d4beef/vscode-cairo/src/cairols.ts#L57)):*
> ```XML
> 
>   const sameProvider = await allFoldersHaveSameLSProvider(ctx, executables);
>   assert(sameProvider, "Multiple versions of scarb in one workspace is not supported");
> ```

By using assertions, you will basically crash the extension, aren't you? This would be bad UX. Let's log an error + show a notification and bail out nicely by ignoring workspace, perhaps.

**Review by Arcticae — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6645)* status: all files reviewed, 2 unresolved discussions (waiting on @mkaput, @orizi, and @piotmag769)

___
*[`vscode-cairo/src/cairols.ts` line 42 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6645#-OBfTfLSEIxekCBY9B1w:-OBkGV1t58LOnok2zqmV:b-agxvs8) ([raw file](https://github.com/starkware-libs/cairo/blob/1475ee3f45087e04c0edd850fb6035d998d4beef/vscode-cairo/src/cairols.ts#L42)):*
> I have suspicions that Scarb version output is not enough

It's necessary because of the shim having the same executable path
There is a case where you could break it so i will add `deepEquality` based comparison here as well.
___
*[`vscode-cairo/src/cairols.ts` line 57 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6645#-OBfSk6E8lxe3s_HaJXt:-OBkGoO1DRh05Gbn3Tdy:bkoc0yy) ([raw file](https://github.com/starkware-libs/cairo/blob/1475ee3f45087e04c0edd850fb6035d998d4beef/vscode-cairo/src/cairols.ts#L57)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

By using assertions, you will basically crash the extension, aren't you? This would be bad UX. Let's log an error + show a notification and bail out nicely by ignoring workspace, perhaps.
</blockquote></details>

Ignoring workspace, vs. loading first folder? Can do either. WDYT?

**Review by Draggu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6645)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @Arcticae, @mkaput, @orizi, and @piotmag769)

___
*[`vscode-cairo/src/cairols.ts` line 38 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6645#-OBkd7N7DXjL6tbBldiR:-OBkd7N7DXjL6tbBldiS:b-7afitt) ([raw file](https://github.com/starkware-libs/cairo/blob/0b29faee6a3a91979e5d6128ca5a43afab23270b/vscode-cairo/src/cairols.ts#L38)):*
>without throwing an error

So without or not?

Just remove `instanceof` check, `deepStrictEqual` can throw something different only if its 3rd argument (not provided here) is `Error`
___
*[`vscode-cairo/src/cairols.ts` line 89 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6645#-OBkdah-1UHNg3PaB_yE:-OBkdah-1UHNg3PaB_yF:b-qv327y) ([raw file](https://github.com/starkware-libs/cairo/blob/0b29faee6a3a91979e5d6128ca5a43afab23270b/vscode-cairo/src/cairols.ts#L89)):*
> ```XML
>   const lsExecutable = executables[0];
> 
>   assert(lsExecutable, "Failed to start Cairo LS");
> ```

https://reviewable.io/reviews/starkware-libs/cairo/6645#-OBfSk6E8lxe3s_HaJXt

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6645)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @orizi, and @piotmag769)

___
*[`vscode-cairo/src/cairols.ts` line 81 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6645#-OBxbpUA7a3u3hBPHvFG:-OBxbpUA7a3u3hBPHvFH:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/0b29faee6a3a91979e5d6128ca5a43afab23270b/vscode-cairo/src/cairols.ts#L81)):*
> ```XML
>   if (!sameProvider) {
>     await vscode.window.showErrorMessage(
>       "Multiple versions of scarb in one workspace is not supported",
> ```





_Suggestion:_
```XML
      "Using multiple Scarb versions in one workspace are not supported.",
```

**Review by Arcticae — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6645)* status: all files reviewed, 3 unresolved discussions (waiting on @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`vscode-cairo/src/cairols.ts` line 38 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6645#-OBkd7N7DXjL6tbBldiR:-OByuLj536aae26kc1qo:b-f2dik2) ([raw file](https://github.com/starkware-libs/cairo/blob/0b29faee6a3a91979e5d6128ca5a43afab23270b/vscode-cairo/src/cairols.ts#L38)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

>without throwing an error

So without or not?

Just remove `instanceof` check, `deepStrictEqual` can throw something different only if its 3rd argument (not provided here) is `Error`
</blockquote></details>

I'd rather keep it extra safe without the additional assumptions
___
*[`vscode-cairo/src/cairols.ts` line 89 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6645#-OBkdah-1UHNg3PaB_yE:-OByuwxzBB2tQKWiUz3g:bmf1w5u) ([raw file](https://github.com/starkware-libs/cairo/blob/0b29faee6a3a91979e5d6128ca5a43afab23270b/vscode-cairo/src/cairols.ts#L89)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

https://reviewable.io/reviews/starkware-libs/cairo/6645#-OBfSk6E8lxe3s_HaJXt
</blockquote></details>

This would fail anyway on the previous version. Why handle it now? It's out of scope
___
*[`vscode-cairo/src/cairols.ts` line 81 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6645#-OBxbpUA7a3u3hBPHvFG:-OByv5gg6lPsDznYFHIO:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/0b29faee6a3a91979e5d6128ca5a43afab23270b/vscode-cairo/src/cairols.ts#L81)):*
> ```XML
>   if (!sameProvider) {
>     await vscode.window.showErrorMessage(
>       "Multiple versions of scarb in one workspace is not supported",
> ```

Done

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6645#-:-OBz6O2q8SCXrR112adk:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Draggu, @orizi, and @piotmag769)

**Review by Draggu — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6645#-:-OBzDM9uAW9hNQRUVy1R:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @orizi, and @piotmag769)

___
*[`vscode-cairo/src/cairols.ts` line 38 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6645#-OBkd7N7DXjL6tbBldiR:-OBzCuF1D4EocWxjOY38:b-3dq38k) ([raw file](https://github.com/starkware-libs/cairo/blob/0b29faee6a3a91979e5d6128ca5a43afab23270b/vscode-cairo/src/cairols.ts#L38)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

I'd rather keep it extra safe without the additional assumptions
</blockquote></details>

This is not additional assumption, it is part of its interface described in doc.
___
*[`vscode-cairo/src/cairols.ts` line 76 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6645#-OBzD7ko9a_jTkiYe3k-:-OBzD7ko9a_jTkiYe3k0:b-80b5bf) ([raw file](https://github.com/starkware-libs/cairo/blob/e5f1ee403739d6ada5c8bec598d51af3acbb7498/vscode-cairo/src/cairols.ts#L76)):*
> ```XML
>       ),
>     )
>   ).filter((x) => !!x) as LSExecutable[];
> ```

Leave TODO here to remove cast when ts version is upgraded

**Review by Arcticae — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6645)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`vscode-cairo/src/cairols.ts` line 76 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6645#-OBzD7ko9a_jTkiYe3k-:-OBzGOnvDgVRLcF9lgEI:b-896fjx) ([raw file](https://github.com/starkware-libs/cairo/blob/e5f1ee403739d6ada5c8bec598d51af3acbb7498/vscode-cairo/src/cairols.ts#L76)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

Leave TODO here to remove cast when ts version is upgraded
</blockquote></details>

Done

**Review by piotmag769 — COMMENTED** [review]
:lgtm:
This language hurts my soul

> Reviewed 1 of 2 files at r1, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6645#-:-OCdax7o42znv52eu42S:bkhj8q4)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
