### PR TITLE
Added u256_sqrt

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2866)

### CODE REVIEW

**Comment by orizi** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2866** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo2/2866" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo2/2866?utm_source=stack-comment).

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2866)* status: 3 of 11 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/uint256.rs` line 375 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2866#-NTSXejE17kHOSHw_zEL:-NTSXejE17kHOSHw_zEM:b-r6fj5) ([raw file](https://github.com/starkware-libs/cairo/blob/52fcbdd0231027272019d0db98af59cd19c4bd19/crates/cairo-lang-sierra-to-casm/src/invocations/uint256.rs#L375)):*
> ```XML
> 
>         // Making sure `2 * root - remainder >= 0`.
>         tempvar shifted_remainder_high = remainder_high * u128_limit;
> ```

Can't remainder overflow here (for a malicious prover) ?

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2866)* status: 3 of 11 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/uint256.rs` line 375 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2866#-NTSXejE17kHOSHw_zEL:-NTSXqf02s51BtzlEZGl:bmp09th) ([raw file](https://github.com/starkware-libs/cairo/blob/52fcbdd0231027272019d0db98af59cd19c4bd19/crates/cairo-lang-sierra-to-casm/src/invocations/uint256.rs#L375)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Can't remainder overflow here (for a malicious prover) ?
</blockquote></details>

Maybe you should explicitly verify that remainder_high <= 2

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2866)* status: 3 of 11 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/uint256.rs` line 375 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2866#-NTSXejE17kHOSHw_zEL:-NTSdeScAGldVi_8Pc2I:b-p3phfk) ([raw file](https://github.com/starkware-libs/cairo/blob/52fcbdd0231027272019d0db98af59cd19c4bd19/crates/cairo-lang-sierra-to-casm/src/invocations/uint256.rs#L375)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Maybe you should explicitly verify that remainder_high <= 2
</blockquote></details>

I actually even know it is 0 or 1 since I know that it should be smaller than root*2, but indeed maybe I need to replace the range check with 'x*(x-1) = 0'
(Will do after flight)
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/uint256.rs` line 381 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2866#-NTSY8KhECNZ9YwhKeEQ:-NTSeC6L4WlfMolvJUbF:brjbrgr) ([raw file](https://github.com/starkware-libs/cairo/blob/52fcbdd0231027272019d0db98af59cd19c4bd19/crates/cairo-lang-sierra-to-casm/src/invocations/uint256.rs#L381)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This is true for completeness, not soundness, right?
</blockquote></details>

I think somewhere in the middle - the prover *can* always convince me that a number is in the range (completeness), and that is enough for me to be convinced the number is positive (soundness)

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2866)* status: 2 of 11 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/uint256.rs` line 323 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2866#-NTdrGQI3OMWVdzCs72K:-NTdrGQI3OMWVdzCs72L:bxnpvdk) ([raw file](https://github.com/starkware-libs/cairo/blob/494202e695af1d03833a272e5b2250a7019dbc4b/crates/cairo-lang-sierra-to-casm/src/invocations/uint256.rs#L323)):*
> ```XML
>         // Assert that remainder_high is 0 or 1. Possible since remainder should be smaller than
>         // 2 * sqrt, so it should be smaller than 2**129.
>         tempvar remainder_high_minus_1 = remainder_high - one;
> ```

assert remainder_high = remainder_high*remainder_high

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2866#-:-NTdrP6N8A52SZZ1RfIr:bnfp4nl)* status: 2 of 11 files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2866#-:-NTdreMS2ikhfRau7dNw:bnfp4nl)* status: 2 of 11 files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 2 of 11 files at r1, 2 of 4 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2866)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2866)* status: 7 of 11 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/uint256.rs` line 323 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2866#-NTdrGQI3OMWVdzCs72K:-NTgdoYE1MJcJIiUT-tN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/494202e695af1d03833a272e5b2250a7019dbc4b/crates/cairo-lang-sierra-to-casm/src/invocations/uint256.rs#L323)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

assert remainder_high = remainder_high*remainder_high
</blockquote></details>

Done.

**Pull request merged**
