### PR TITLE
Added resolve of type aliases.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:1e81a1e0

---

**Stack**:
- #1508
- #1504
- #1503
- #1498 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 11 files at r1, 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1498)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @orizi, @spapinistarkware, and @yuvalsw)

___
*[`crates/semantic/src/items/type_alias.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1498#-NKI__KF4o-kkQJFhfwe:-NKI__KF4o-kkQJFhfwf:bn6wz00) ([raw file](https://github.com/starkware-libs/cairo/blob/566450277bae4be882259b016b83cf86818a6577/crates/semantic/src/items/type_alias.rs#L34)):*
> ```XML
>     // TODO(spapini): Add generic args when they are supported on structs.
>     let module_data = db.module_data(module_file_id.0)?;
>     let type_alias_ast = module_data.type_aliases.get(&type_alias_id).to_maybe()?;
> ```

Shouldn't we avodi using to_maybe in new code?

don't you need to add diagnostic if it is missing?



_Code quote:_
```XML
to_maybe()
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1498)* status: 9 of 11 files reviewed, 3 unresolved discussions (waiting on @orizi, @spapinistarkware, and @yuvalsw)

___
*[`crates/semantic/src/items/type_alias.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1498#-NKI_oE25M-HEW2UOyYK:-NKI_oE25M-HEW2UOyYL:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/566450277bae4be882259b016b83cf86818a6577/crates/semantic/src/items/type_alias.rs#L40)):*
> ```XML
>         &mut diagnostics,
>         module_file_id,
>         &type_alias_ast.generic_params(db.upcast()),
> ```





_Suggestion:_
```XML
syntax_db
```
___
*[`crates/semantic/src/items/type_alias.rs` line 71 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1498#-NKIa4T5Esw8Mlvr1fGv:-NKIa4T5Esw8Mlvr1fGw:b1r3th1) ([raw file](https://github.com/starkware-libs/cairo/blob/566450277bae4be882259b016b83cf86818a6577/crates/semantic/src/items/type_alias.rs#L71)):*
> ```XML
>         &mut diagnostics,
>         module_file_id,
>         &type_alias_ast.generic_params(db.upcast()),
> ```

syntax_db



_Code quote:_
```XML
db.upcast()
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1498)* status: 9 of 11 files reviewed, 4 unresolved discussions (waiting on @orizi, @spapinistarkware, and @yuvalsw)

___
*[`crates/semantic/src/items/tests/type_alias` line 122 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1498#-NKIbcTr8t_PZQsgYXo9:-NKIbcTs86RCIpicCtUb:b9yzvax) ([raw file](https://github.com/starkware-libs/cairo/blob/566450277bae4be882259b016b83cf86818a6577/crates/semantic/src/items/tests/type_alias#L122)):*
> ```
> 
> //! > function
> fn foo(a: A::<bool>) -> felt {
> ```

Can you add a test with

A::<5>
?



_Code quote:_
```
A::<bool>
```

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 8 of 11 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1498)* status: all files reviewed, 12 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @spapinistarkware)

___
*[`crates/languageserver/src/lib.rs` line 399 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1498#-NKIWVux6Orwzt4yCszm:-NKIWVux6Orwzt4yCszn:bhpi5fo) ([raw file](https://github.com/starkware-libs/cairo/blob/566450277bae4be882259b016b83cf86818a6577/crates/languageserver/src/lib.rs#L399)):*
> ```XML
>                     generic_type.untyped_stable_ptr(defs_db),
>                 ),
>                 ResolvedGenericItem::GenericTypeAlias(type_alias_id) => (
> ```

to be consistent with the rest here



_Suggestion:_
```XML
type_alias
```
___
*[`crates/semantic/src/db.rs` line 145 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1498#-NKIX56SCsbBECPIxIaf:-NKIX56SCsbBECPIxIag:b-nf27mg) ([raw file](https://github.com/starkware-libs/cairo/blob/566450277bae4be882259b016b83cf86818a6577/crates/semantic/src/db.rs#L145)):*
> ```XML
>         type_alias_id: TypeAliasId,
>     ) -> Diagnostics<SemanticDiagnostic>;
>     /// Returns the semantic diagnostics of a type alias.
> ```

unrelated to this function



_Code quote:_
```XML
    /// Returns the semantic diagnostics of a type alias.
```
___
*[`crates/semantic/src/diagnostic.rs` line 118 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1498#-NKIYelVBknmzDUzViGX:-NKIYelVBknmzDUzViGY:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/566450277bae4be882259b016b83cf86818a6577/crates/semantic/src/diagnostic.rs#L118)):*
> ```XML
>             }
>             SemanticDiagnosticKind::TypeAliasCycle => {
>                 "Cycle detected while resolving 'type' aliases items.".into()
> ```





_Suggestion:_
```XML
resolving 'type alias' items
```
___
*[`crates/semantic/src/resolve_path.rs` line 450 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1498#-NKIaVkV2jsi41464ti-:-NKIaVkV2jsi41464ti0:bws2u6l) ([raw file](https://github.com/starkware-libs/cairo/blob/566450277bae4be882259b016b83cf86818a6577/crates/semantic/src/resolve_path.rs#L450)):*
> ```XML
>                 // This checks if there's a cycle in this type alias definition.
>                 // TODO(orizi): Handle this without using `priv_type_alias_semantic_data`.
>                 self.db.priv_type_alias_semantic_data(type_alias_id)?.resolved_type?;
> ```

remove? You ignore the result, and it seems like you do the todo below...



_Code quote:_
```XML
                // TODO(orizi): Handle this without using `priv_type_alias_semantic_data`.
                self.db.priv_type_alias_semantic_data(type_alias_id)?.resolved_type?;
```
___
*[`crates/semantic/src/items/type_alias.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1498#-NKIbdFv7y75pkcoyOH6:-NKIbdFv7y75pkcoyOH7:b7qak3b) ([raw file](https://github.com/starkware-libs/cairo/blob/566450277bae4be882259b016b83cf86818a6577/crates/semantic/src/items/type_alias.rs#L18)):*
> ```XML
> pub struct TypeAliasData {
>     diagnostics: Diagnostics<SemanticDiagnostic>,
>     pub resolved_type: Maybe<TypeId>,
> ```

Can you remove the pub?



_Code quote:_
```XML
pub
```
___
*[`crates/semantic/src/items/tests/type_alias` line 80 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1498#-NKId_5eCybomXD8jD6o:-NKId_5eCybomXD8jD6p:bgh3x9z) ([raw file](https://github.com/starkware-libs/cairo/blob/566450277bae4be882259b016b83cf86818a6577/crates/semantic/src/items/tests/type_alias#L80)):*
> ```
> fn foo(a: OptionFelt) -> felt {
>     match a {
>         Option::Some(v) => v,
> ```

shouldn't this be OptionFelt too?



_Code quote:_
```
Option
```
___
*[`crates/semantic/src/items/tests/type_alias` line 102 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1498#-NKIdnfHBrxyrqbIo05V:-NKIdnfHBrxyrqbIo05W:bkdbmg9) ([raw file](https://github.com/starkware-libs/cairo/blob/566450277bae4be882259b016b83cf86818a6577/crates/semantic/src/items/tests/type_alias#L102)):*
> ```
> //! > function
> fn foo(a: RenamedTuple::<u128>) -> felt {
>     let (v, _) = a;
> ```

can you return the second item (u128) here for it to be more interesting.
Or maybe even return (felt, u128) and just return the received param.



_Code quote:_
```
fn foo(a: RenamedTuple::<u128>) -> felt {
    let (v, _) = a;
    v
}
```
___
*[`crates/semantic/src/items/tests/type_alias` line 122 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1498#-NKIeIEA-_b51hEZEO3y:-NKIeIEA-_b51hEZEO3z:bu9z0tf) ([raw file](https://github.com/starkware-libs/cairo/blob/566450277bae4be882259b016b83cf86818a6577/crates/semantic/src/items/tests/type_alias#L122)):*
> ```
> 
> //! > function
> fn foo(a: A::<bool>) -> felt {
> ```

Again, can you return a as is, and change the return type to (felt, u128, bool)?



_Code quote:_
```
fn foo(a: A::<bool>) -> felt {
    let (v, _, _) = a;
    v
}
```
___
*[`crates/semantic/src/items/tests/type_alias` line 153 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1498#-NKIekaD1xpYjcgzWugt:-NKIekaD1xpYjcgzWugu:bo3ukua) ([raw file](https://github.com/starkware-libs/cairo/blob/566450277bae4be882259b016b83cf86818a6577/crates/semantic/src/items/tests/type_alias#L153)):*
> ```
> //! > module_code
> type A = B;
> type B = A;
> ```

Can you please add a test for cycle of size 1? "type A = A"



_Code quote:_
```
type A = B;
type B = A;
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1498)* status: 9 of 11 files reviewed, 12 unresolved discussions (waiting on @ilyalesokhin-starkware, @spapinistarkware, and @yuvalsw)

___
*[`crates/semantic/src/resolve_path.rs` line 450 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1498#-NKIaVkV2jsi41464ti-:-NKIfJ270y3ERMM6y2r0:b32yrr8) ([raw file](https://github.com/starkware-libs/cairo/blob/566450277bae4be882259b016b83cf86818a6577/crates/semantic/src/resolve_path.rs#L450)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

remove? You ignore the result, and it seems like you do the todo below...
</blockquote></details>

no - this line is a must - note the comment above the todo.
___
*[`crates/semantic/src/items/type_alias.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1498#-NKIbdFv7y75pkcoyOH6:-NKIfYkvArDGj-7a0WqK:b-pcer0p) ([raw file](https://github.com/starkware-libs/cairo/blob/566450277bae4be882259b016b83cf86818a6577/crates/semantic/src/items/type_alias.rs#L18)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Can you remove the pub?
</blockquote></details>

no - because of the check.
___
*[`crates/semantic/src/items/tests/type_alias` line 80 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1498#-NKId_5eCybomXD8jD6o:-NKIfbMf3A7SBUT0ooe6:b69krxe) ([raw file](https://github.com/starkware-libs/cairo/blob/566450277bae4be882259b016b83cf86818a6577/crates/semantic/src/items/tests/type_alias#L80)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

shouldn't this be OptionFelt too?
</blockquote></details>

no - variants currently can only work on the name of the generic type.
___
*[`crates/semantic/src/items/tests/type_alias` line 102 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1498#-NKIdnfHBrxyrqbIo05V:-NKIfmS8AE2OBiK0shIr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/566450277bae4be882259b016b83cf86818a6577/crates/semantic/src/items/tests/type_alias#L102)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

can you return the second item (u128) here for it to be more interesting.
Or maybe even return (felt, u128) and just return the received param.
</blockquote></details>

Done.
___
*[`crates/semantic/src/items/tests/type_alias` line 122 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1498#-NKIeIEA-_b51hEZEO3y:-NKIgp2n4OxfMI8cO8HE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/566450277bae4be882259b016b83cf86818a6577/crates/semantic/src/items/tests/type_alias#L122)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Again, can you return a as is, and change the return type to (felt, u128, bool)?
</blockquote></details>

Done.
___
*[`crates/semantic/src/items/tests/type_alias` line 153 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1498#-NKIekaD1xpYjcgzWugt:-NKIhGbg8lNFeIwpQUyX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/566450277bae4be882259b016b83cf86818a6577/crates/semantic/src/items/tests/type_alias#L153)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Can you please add a test for cycle of size 1? "type A = A"
</blockquote></details>

Done.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1498)* status: all files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @spapinistarkware)

___
*[`crates/semantic/src/resolve_path.rs` line 450 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1498#-NKIlcEB7fG5sfi9-iLf:-NKIlcEB7fG5sfi9-iLg:b6zwkvw) ([raw file](https://github.com/starkware-libs/cairo/blob/2846c87eb668381085146742544cb1241c77c4a4/crates/semantic/src/resolve_path.rs#L450)):*
> ```XML
>                 // This checks if there's a cycle in this type alias definition.
>                 // TODO(orizi): Handle this without using `priv_type_alias_semantic_data`.
>                 self.db.priv_type_alias_semantic_data(type_alias_id)?.resolved_type?;
> ```

Suggestion. This would have been much clearer to me.



_Suggestion:_
```XML
                // Check for cycles in this type alias definition. Result is ignored on purpose.
                // TODO(orizi): Handle this without using `priv_type_alias_semantic_data`.
                self.db.priv_type_alias_semantic_data(type_alias_id)?.resolved_type?;
                
                // Now actually get the resolved type to use.
                let ty = self.db.type_alias_resolved_type(type_alias_id)?;
                let mut generic_args = generic_args.unwrap_or_default();
                let generic_params = self.db.type_alias_generic_params(type_alias_id)?;
```
___
*[`crates/semantic/src/items/type_alias.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1498#-NKIbdFv7y75pkcoyOH6:-NKImAUb9otKIZbr3bpR:bkaqzn9) ([raw file](https://github.com/starkware-libs/cairo/blob/566450277bae4be882259b016b83cf86818a6577/crates/semantic/src/items/type_alias.rs#L18)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no - because of the check.
</blockquote></details>

Please add a TODO. In the end this should be private.
___
*[`crates/semantic/src/items/tests/type_alias` line 80 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1498#-NKId_5eCybomXD8jD6o:-NKImcLD6QE32X5yumpx:b-h4u732) ([raw file](https://github.com/starkware-libs/cairo/blob/566450277bae4be882259b016b83cf86818a6577/crates/semantic/src/items/tests/type_alias#L80)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no - variants currently can only work on the name of the generic type.
</blockquote></details>

(unrelated to this PR then)
This seems like something we should fix?
I do see Option::<felt>::None and Option::<felt>::Some in the code, but indeed not as enum variants in match statements.
___
*[`crates/semantic/src/items/tests/type_alias` line 138 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1498#-NKInSXH87XfZ3YV-Cnd:-NKInSXH87XfZ3YV-Cne:b-kq9hkt) ([raw file](https://github.com/starkware-libs/cairo/blob/2846c87eb668381085146742544cb1241c77c4a4/crates/semantic/src/items/tests/type_alias#L138)):*
> ```
> 
> //! > Test type alias wrong generic argument.
> ```

what's wrong about it?



_Code quote:_
```
 Test type alias wrong generic argument
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1498)* status: 9 of 11 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware, @spapinistarkware, and @yuvalsw)

___
*[`crates/semantic/src/items/tests/type_alias` line 80 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1498#-NKId_5eCybomXD8jD6o:-NKIrP681n9MJgmwxx3Y:b7jismg) ([raw file](https://github.com/starkware-libs/cairo/blob/566450277bae4be882259b016b83cf86818a6577/crates/semantic/src/items/tests/type_alias#L80)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

(unrelated to this PR then)
This seems like something we should fix?
I do see Option::<felt>::None and Option::<felt>::Some in the code, but indeed not as enum variants in match statements.
</blockquote></details>

probably - following up on monday.
___
*[`crates/semantic/src/items/tests/type_alias` line 138 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1498#-NKInSXH87XfZ3YV-Cnd:-NKIrUzYEPlVQNw4do2P:b-nzof0g) ([raw file](https://github.com/starkware-libs/cairo/blob/2846c87eb668381085146742544cb1241c77c4a4/crates/semantic/src/items/tests/type_alias#L138)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

what's wrong about it?
</blockquote></details>

it is a number.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1498#-:-NKIynHC-sMfK0Rr8Ico:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware and @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1498#-:-NKIz0Eh23NDhOb4zOKg:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/semantic/src/items/type_alias.rs` line 26 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1498#-NKIy2DZ8BjM3uS-fpqK:-NKIy2DZ8BjM3uS-fpqL:bqsp5tq) ([raw file](https://github.com/starkware-libs/cairo/blob/2ce618069f91512520ffa68ed251f3adc538dbf8/crates/semantic/src/items/type_alias.rs#L26)):*
> ```XML
>     // TODO(orizi): Remove this function when cycle validation is not required through a type's
>     // field.
>     pub fn check_not_cycle(&self) -> Maybe<()> {
> ```

consider



_Suggestion:_
```XML
check_no_cycle
```
___
*[`crates/semantic/src/items/tests/type_alias` line 154 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1498#-NKIya_d7bntkG4u7nvS:-NKIya_d7bntkG4u7nvT:b-x5dopf) ([raw file](https://github.com/starkware-libs/cairo/blob/2ce618069f91512520ffa68ed251f3adc538dbf8/crates/semantic/src/items/tests/type_alias#L154)):*
> ```
> //! > module_code
> type A<P4> = B::<felt, P4, 9>;
> type B<P1, P2, P3> = (P1, P3, P2);
> ```

I suggest this to make the test more specific (minimal test that captures the error you look for)



_Suggestion:_
```
//! > function
// TODO(orizi): Add diagnostics for this case.
fn foo(a: A::<5>) -> felt {
    let (v, _) = a;
    v
}

//! > function_name
foo

//! > module_code
type A<T> = (felt, T);
```

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1498)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1498)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
