### PR TITLE
Add location to return statements.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5155)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/return_optimization.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5155#-NrifpxZ65o4STCuZTJU:-NrifpxZ65o4STCuZTJV:b-p4wguj) ([raw file](https://github.com/starkware-libs/cairo/blob/2023a59770e615ce35d05473654834e3f8b79ee1/crates/cairo-lang-lowering/src/optimizations/return_optimization.rs#L94)):*
> ```XML
> 
>             if let Some(prev_info) = &opt_last_info {
>                 if prev_info != &curr_info {
> ```

Note that i need to ignore the location when doing the comparison here.



_Code quote:_
```XML
 if prev_info != &curr_info {
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 10 of 17 files at r1, 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5155)* status: 11 of 18 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/return_optimization.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5155#-NrifpxZ65o4STCuZTJU:-NrjAgUYATU3t-znDpyl:b-l2d8my) ([raw file](https://github.com/starkware-libs/cairo/blob/2023a59770e615ce35d05473654834e3f8b79ee1/crates/cairo-lang-lowering/src/optimizations/return_optimization.rs#L94)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Note that i need to ignore the location when doing the comparison here.
</blockquote></details>

isn't this change now makes the `(None, None)` option return None (and before it wouldn't have?
___
*[`crates/cairo-lang-lowering/src/optimizations/return_optimization.rs` line 109 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5155#-Nrj9mTP8KIcNFGSASJz:-Nrj9mTP8KIcNFGSASK-:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/43463e99142efceccdc821f5f977a2498dd09308/crates/cairo-lang-lowering/src/optimizations/return_optimization.rs#L109)):*
> ```XML
>                 _ => return None,
>             }
>         }
> ```





_Suggestion:_
```XML
            match curr_info.opt_return_info {
                Some(return_info) if opt_last_info.map(|x|x.returned_vars == return_info.returned_vars).unwrap_or(true) => {
                    opt_last_info = Some(return_info)
                }
                _ => return None,
            }
        }
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 17 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5155)* status: 16 of 18 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/ap_tracking` line 2 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5155#-NrjBqSs7d75Dq4eJPsQ:-NrjBqSs7d75Dq4eJPsR:b43czo5) ([raw file](https://github.com/starkware-libs/cairo/blob/43463e99142efceccdc821f5f977a2498dd09308/crates/cairo-lang-sierra-generator/src/function_generator_test_data/ap_tracking#L2)):*
> ```
> //! > test inlined function.
> ```

how is this related?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/return_optimization.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5155#-NrifpxZ65o4STCuZTJU:-NrjLo1-5byYjZy06bt_:b-zalv71) ([raw file](https://github.com/starkware-libs/cairo/blob/2023a59770e615ce35d05473654834e3f8b79ee1/crates/cairo-lang-lowering/src/optimizations/return_optimization.rs#L94)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

isn't this change now makes the `(None, None)` option return None (and before it wouldn't have?
</blockquote></details>

the `if !curr_info.early_return_possible()` guarantees that curr_info.opt_return_info not None

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5155#-:-NrjT4D_ARA1hnv4RhPc:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
