### PR TITLE
Fixed formatting of tuples with a single item in lowering format

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1129)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1129)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/semantic/src/types.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1129#-NHyr2Fg95CoGZoc8H2D:-NHyr2Fg95CoGZoc8H2E:b-k27a0s) ([raw file](https://github.com/starkware-libs/cairo/blob/76a32a03c4722d6d30cec2213870d005accba0f6/crates/semantic/src/types.rs#L52)):*
> ```XML
>             TypeLongId::Tuple(inner_types) => {
>                 if inner_types.len() == 1 {
>                     format!("({},)", inner_types[0].format(db))
> ```

in type clauses - (felt) is already a tuple - this is only required for construction.



_Code quote:_
```XML
                if inner_types.len() == 1 {
                    format!("({},)", inner_types[0].format(db))
                } else {
                    format!("({})", inner_types.iter().map(|ty| ty.format(db)).join(", "))
                }
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1129)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/semantic/src/types.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1129#-NHyr2Fg95CoGZoc8H2D:-NI1V-7p9E7D0RUld214:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/76a32a03c4722d6d30cec2213870d005accba0f6/crates/semantic/src/types.rs#L52)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

in type clauses - (felt) is already a tuple - this is only required for construction.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1129)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1129#-:-NI28pj63yacSWILj4NF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1129)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
