### PR TITLE
fix: use child trait

### PR DESCRIPTION
**Pull request by jujube**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5369)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5369#-:-NuwJ0TG4yy0vbSGOqJq:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5369)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jujube)

**Comment by jujube** [comment]
Node: GraphNode + ComputeScc
may be update
Node:  ComputeScc?

**Comment by jujube** [comment]
@orizi

**Comment by orizi** [comment]
If this looks better and works - sure.
In any case - these sort of PRs are not a must, as unless it was a wide spread, or a readability issue, it won't affect us too much.

**Pull request merged**
