### PR TITLE
Limited the options for the number of words per felt

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2693)

### CODE REVIEW

**Comment by orizi** [comment]
Current dependencies on/for this PR:
* 03-30-Packing_code_words_by_divmod_not_aligning_to_bits
  * **PR #2693** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo2/2693" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo2/2693?utm_source=stack-comment).

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2693)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/felt252_vec_compression.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2693#-NS5cz6I-jxZvEExduJY:-NS5cz6I-jxZvEExduJZ:b8cfwbk) ([raw file](https://github.com/starkware-libs/cairo/blob/79058d7a0af9e22e531e9d675f2a1733f1ea27c4/crates/cairo-lang-starknet/src/felt252_vec_compression.rs#L16)):*
> ```XML
>         code.entry(&value.value).or_insert(idx);
>     }
>     // Limiting the number of possible encodings by working only on powers of 2, as well as only
> ```

what is the motivation for this change?



_Code quote:_
```XML
    // Limiting the number of possible encodings by working only on powers of 2, as well as only
    // starting at 256 (or 8 bits per code word).
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2693)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/felt252_vec_compression.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2693#-NS5cz6I-jxZvEExduJY:-NSZkuGl3JNlxzynNwn9:b-bigknf) ([raw file](https://github.com/starkware-libs/cairo/blob/79058d7a0af9e22e531e9d675f2a1733f1ea27c4/crates/cairo-lang-starknet/src/felt252_vec_compression.rs#L16)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what is the motivation for this change?
</blockquote></details>

so when implementing this in cairo for efficiency - we'd only need a few sizes impls, and not enumerating over all.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2693#-:-NSZtjUS5GZ_7I6B8c5s:bnfp4nl)* status: 1 of 7 files reviewed, all discussions resolved

**Review by orizi — COMMENTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2693)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
