### PR TITLE
store_variables: Support SameAsParam in libfunc outputs.

### PR DESCRIPTION
**Pull request by liorgold2**
commit-id:0f3ef23a

---

**Stack**:
- #1459
- #1454
- #1458 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1458)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/sierra_generator/src/store_variables/state.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1458#-NK4jKf_7jbS2LdggsA0:-NK4jKf_7jbS2LdggsA1:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/27e278958f11bd86ffba48db4bf7f9a6dd018fe3/crates/sierra_generator/src/store_variables/state.rs#L87)):*
> ```XML
> 
>         if let OutputVarReferenceInfo::SameAsParam { param_idx } = &output_info.ref_info {
>             if let Some(deferred_info) = self.deferred_variables.get(&args[*param_idx]) {
> ```





_Suggestion:_
```XML
    /// Register an output variable of a libfunc.
    ///
    /// If the variable is marked as Deferred output by the libfunc, it is added to
    /// [Self::deferred_variables]. Similarly for [Self::temporary_variables].
    fn register_output(
        &mut self,
        res: sierra::ids::VarId,
        output_info: &OutputVarInfo,
        args: &[sierra::ids::VarId],
    ) {
        let mut is_deferred: Option<DeferredVariableKind> = None;

        self.deferred_variables.swap_remove(&res);
        self.temporary_variables.swap_remove(&res);
        self.known_stack.remove_variable(&res);

        match &output_info.ref_info {
            OutputVarReferenceInfo::Deferred(kind) => {
                is_deferred = Some(match kind {
                    DeferredOutputKind::Const => DeferredVariableKind::Const,
                    DeferredOutputKind::AddConst { .. } => DeferredVariableKind::AddConst,
                    DeferredOutputKind::Generic => DeferredVariableKind::Generic,
                });
            }
            OutputVarReferenceInfo::SameAsParam { param_idx } = {
                if let Some(deferred_info) = self.deferred_variables.get(&args[*param_idx]) {
                    is_deferred = Some(deferred_info.kind);
                }
            }
            OutputVarReferenceInfo::NewTempVar { idx } => {
                if let Some(idx) = idx {
                    self.known_stack.insert(res.clone(), *idx);
                }
                self.temporary_variables.insert(res, output_info.ty.clone());
            }
            OutputVarReferenceInfo::NewLocalVar => {}
        }

        if let Some(deferred_variable_info_kind) = is_deferred {
            self.deferred_variables.insert(
                res.clone(),
                DeferredVariableInfo {
                    ty: output_info.ty.clone(),
                    kind: deferred_variable_info_kind,
                },
            );
        }
    }
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1458)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/sierra_generator/src/store_variables/state.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1458#-NK4jKf_7jbS2LdggsA0:-NK7nhZoA3tbXDGi70hW:bm5iny1) ([raw file](https://github.com/starkware-libs/cairo/blob/27e278958f11bd86ffba48db4bf7f9a6dd018fe3/crates/sierra_generator/src/store_variables/state.rs#L87)):*
> ```XML
> 
>         if let OutputVarReferenceInfo::SameAsParam { param_idx } = &output_info.ref_info {
>             if let Some(deferred_info) = self.deferred_variables.get(&args[*param_idx]) {
> ```

Done partially.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1458)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1458#-:-NK7yObp7irDtBjsjI7I:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
