### PR TITLE
Change duplicateable to copyable in the high level compiler.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5210)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5210)* status: 4 of 18 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5210#-NsJJ3gw4Tci5SBd1Bv-):*
Fix

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5210)* status: 4 of 18 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5210#-NsJJ3gw4Tci5SBd1Bv-):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Fix
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 7 of 18 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5210#-:-NsJNboTAxJe-I8RoGoH:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 996 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5210#-NsJNG9N9JyAeXeuI4y1:-NsJNG9O-Rdt5XhExR1w:b2nhf0o) ([raw file](https://github.com/starkware-libs/cairo/blob/5a2bc17e7a42e5925a40d390de5fd260883ed55c/crates/cairo-lang-lowering/src/lower/mod.rs#L996)):*
> ```XML
>                 .to_usize()
>                 .unwrap();
>             // If there are multiple elements, the type must be copyable as we copy the var
> ```

Fmt

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5210)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 996 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5210#-NsJNG9N9JyAeXeuI4y1:-NsJOGko9I0230aqq-HO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5a2bc17e7a42e5925a40d390de5fd260883ed55c/crates/cairo-lang-lowering/src/lower/mod.rs#L996)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Fmt
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5210#-:-NsJRdLwBNXJuRp839fY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
