### PR TITLE
Check generic impl param's trait

### PR DESCRIPTION
**Pull request by spapinistarkware**
commit-id:39bf2a7e

---

**Stack**:
- #2056
- #2054 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2054)* status: 6 of 9 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2054#-NNfzFwh6P9HbL97NTfJ:-NNfzFwh6P9HbL97NTfK:b-jbdf1p) ([raw file](https://github.com/starkware-libs/cairo/blob/284920f1ef357fe8251700079ff732b600b3b609/crates/cairo-lang-semantic/src/items/generics.rs#L109)):*
> ```XML
>     pub id: GenericParamId,
>     pub concrete_trait: Maybe<ConcreteTraitId>,
> }
> ```

pub for cycle detection?



_Code quote:_
```XML
    pub id: GenericParamId,
    pub concrete_trait: Maybe<ConcreteTraitId>,
```
___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 508 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2054#-NNfykh27-LO93AB_Mdt:-NNfykh27-LO93AB_Mdu:bjbwq1j) ([raw file](https://github.com/starkware-libs/cairo/blob/f10460ca7f88985868b922bc4a364c88c2793113/crates/cairo-lang-semantic/src/items/tests/trait#L508)):*
> ```
> 
> //! > comments
> TODO(yuval): there should be a diagnostic about repeating generic params.
> ```

shouldn't there be diagnostics?



_Code quote:_
```
//! > comments
TODO(yuval): there should be a diagnostic about repeating generic params.

//! > test_function_name
```
___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 536 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2054#-NNfycph8oQnMU0Z7I_Y:-NNfycph8oQnMU0Z7I_Z:b-k8s73t) ([raw file](https://github.com/starkware-libs/cairo/blob/f10460ca7f88985868b922bc4a364c88c2793113/crates/cairo-lang-semantic/src/items/tests/trait#L536)):*
> ```
> 
> //! > comments
> TODO(yuval): fix - the diagnostics here should be different - about already used generic param.
> ```

where are the repeating params here?



_Code quote:_
```


//! > comments
TODO(yuval): fix - the diagnostics here should be different - about already used generic param.
```

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2054)* status: all files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2054)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2054#-NNfzFwh6P9HbL97NTfJ:-NNg4O541y7KSRZHZ2Sn:bcp9kyj) ([raw file](https://github.com/starkware-libs/cairo/blob/31b59cb56b23a4da2e6ca02561f1279d436d3aef/crates/cairo-lang-semantic/src/items/generics.rs#L109)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

pub for cycle detection?
</blockquote></details>

Just because it is the public API object, this is the "semantic model" if a generic param. I only encountered the missing pub now though.
___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 508 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2054#-NNfykh27-LO93AB_Mdt:-NNg4Yd14byhAOuJa01x:b-jsa5tm) ([raw file](https://github.com/starkware-libs/cairo/blob/ccdcfb45903d3e408c3ae591be80524be2308727/crates/cairo-lang-semantic/src/items/tests/trait#L508)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

shouldn't there be diagnostics?
</blockquote></details>

I think not. Currently, generic params are shadowing, like in rust. Maybe we can consider adding a warning in the future.
___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 536 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2054#-NNfycph8oQnMU0Z7I_Y:-NNg4fegE096qvCcDCSv:byelryt) ([raw file](https://github.com/starkware-libs/cairo/blob/ccdcfb45903d3e408c3ae591be80524be2308727/crates/cairo-lang-semantic/src/items/tests/trait#L536)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

where are the repeating params here?
</blockquote></details>

```trait Identity<T> {
   fn foo<T>(a: T);
}
```
T shadows T

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2054#-:-NNgFlyIEWWyYL-g4I8S:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
