### PR TITLE
Made ap-change be calculated without LP.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #4373
- #4250 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4250)

### CODE REVIEW

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4250)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-sierra-ap-change/src/compute.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4250#-Nh3HP1OE3yycfXWds11:-Nh3HP1OE3yycfXWds12:bcptege) ([raw file](https://github.com/starkware-libs/cairo/blob/81916e11e994c82f6e97898fa97fc807bf27247c/crates/cairo-lang-sierra-ap-change/src/compute.rs#L54)):*
> ```XML
> }
> 
> /// Helper to implement the `InvocationApChangeInfoProvider` for the equation generation.
> ```

Wrong doc.
___
*[`crates/cairo-lang-sierra-ap-change/src/compute.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4250#-Nh3Nyez6KDy9BvDGRpm:-Nh3Nyez6KDy9BvDGRpn:b-izt04b) ([raw file](https://github.com/starkware-libs/cairo/blob/81916e11e994c82f6e97898fa97fc807bf27247c/crates/cairo-lang-sierra-ap-change/src/compute.rs#L134)):*
> ```XML
>                 | ApChange::Known(_)
>                 | ApChange::DisableApTracking => {
>                     if let Some(locals) = self.locals.get(&idx) {
> ```

Consider changing it to `locals_count`.



_Code quote:_
```XML
locals
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4250)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @liorgold2)

___
*[`crates/cairo-lang-sierra-ap-change/src/compute.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4250#-Nh3HP1OE3yycfXWds11:-Nh4rKpoDbNr0mtvcoHN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/81916e11e994c82f6e97898fa97fc807bf27247c/crates/cairo-lang-sierra-ap-change/src/compute.rs#L54)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Wrong doc.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-ap-change/src/compute.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4250#-Nh3Nyez6KDy9BvDGRpm:-Nh4rNUF9q6ML69dFhog:b-pdcs7f) ([raw file](https://github.com/starkware-libs/cairo/blob/81916e11e994c82f6e97898fa97fc807bf27247c/crates/cairo-lang-sierra-ap-change/src/compute.rs#L134)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Consider changing it to `locals_count`.
</blockquote></details>

it isn't count - it is size. Done.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4250#-:-Nh6Hq_a245Eh-Sl2SwE:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-sierra-ap-change/src/compute.rs` line 319 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4250#-Nh6HIWd4rLmk8i2XHky:-Nh6HIWd4rLmk8i2XHkz:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/cf9605b4dacb6cf25ede174b6303983e2e50cbc9/crates/cairo-lang-sierra-ap-change/src/compute.rs#L319)):*
> ```XML
>     }
> 
>     /// Returns the locals count for a statement.
> ```





_Suggestion:_
```XML
e locals size
```
___
*[`crates/cairo-lang-sierra-ap-change/src/compute.rs` line 354 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4250#-Nh6HVgB87nVCUPcIa2X:-Nh6HVgB87nVCUPcIa2Y:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/cf9605b4dacb6cf25ede174b6303983e2e50cbc9/crates/cairo-lang-sierra-ap-change/src/compute.rs#L354)):*
> ```XML
> }
> 
> /// Calculates gas information for a given program.
> ```





_Suggestion:_
```XML
/// Calculates the ap change information for a given program.
```
___
*[`crates/cairo-lang-sierra-ap-change/src/lib.rs` line 54 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4250#-Nh6HodpAqdAvc5JWsZt:-Nh6HodpAqdAvc5JWsZu:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/cf9605b4dacb6cf25ede174b6303983e2e50cbc9/crates/cairo-lang-sierra-ap-change/src/lib.rs#L54)):*
> ```XML
> }
> 
> /// Calculates gas information for a given program.
> ```





_Suggestion:_
```XML
ap change
```

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4250)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4250)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4250)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4250)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4250)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
