### PR TITLE
Add inlining of small functions.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5067)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 82 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5067)* status: 1 of 82 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5067#-NqbkursBXo8D5oZoZDX:-NqbkursBXo8D5oZoZDY:b-54611v) ([raw file](https://github.com/starkware-libs/cairo/blob/69e78f92c391dfb2690ec640446a170933251946/crates/cairo-lang-lowering/src/inline/mod.rs#L100)):*
> ```XML
>         let num_of_statements: usize =
>             lowered.blocks.iter().map(|(_, block)| block.statements.len()).sum();
>         if num_of_statements < 7 {
> ```

extract 7 into a constant (defined in the funciton) and add a todo to replace with reading from the main crate configuration.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5067)* status: 1 of 82 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5067#-NqbkursBXo8D5oZoZDX:-NqblCJbCFfavXSohPZM:b-4yf8h7) ([raw file](https://github.com/starkware-libs/cairo/blob/69e78f92c391dfb2690ec640446a170933251946/crates/cairo-lang-lowering/src/inline/mod.rs#L100)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

extract 7 into a constant (defined in the funciton) and add a todo to replace with reading from the main crate configuration.
</blockquote></details>

or more exactly - already extract it into the optimization_config.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5067)* status: 0 of 82 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5067#-NqbkursBXo8D5oZoZDX:-NqcC-mJDxQal85WgiQq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/69e78f92c391dfb2690ec640446a170933251946/crates/cairo-lang-lowering/src/inline/mod.rs#L100)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

or more exactly - already extract it into the optimization_config.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 7 of 82 files at r1, 3 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5067)* status: 10 of 82 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 430 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5067#-NqcDPLLErFwvF9c1Yr9:-NqcDPLLErFwvF9c1YrA:b-driy66) ([raw file](https://github.com/starkware-libs/cairo/blob/071a6fb92786ac793405e2368f9e9a8b4eef7272/crates/cairo-lang-lowering/src/inline/mod.rs#L430)):*
> ```XML
> }
> 
> pub fn inline_small_functions_threshold(db: &dyn LoweringGroup) -> usize {
> ```

doc.
and use above.
___
*[`crates/cairo-lang-lowering/src/optimizations/config.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5067#-NqcDoKqDSrRkyaeDvnV:-NqcDoKqDSrRkyaeDvnW:biuh473) ([raw file](https://github.com/starkware-libs/cairo/blob/071a6fb92786ac793405e2368f9e9a8b4eef7272/crates/cairo-lang-lowering/src/optimizations/config.rs#L24)):*
> ```XML
> 
> impl OptimizationConfig {
>     pub fn with_moveable_functions(mut self, moveable_functions: Vec<String>) -> Self {
> ```

doc all functions.
___
*[`crates/cairo-lang-lowering/src/optimizations/config.rs` line 41 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5067#-NqcDrhO1hK1DGSvgu41:-NqcDrhO1hK1DGSvgu42:bn0hcab) ([raw file](https://github.com/starkware-libs/cairo/blob/071a6fb92786ac793405e2368f9e9a8b4eef7272/crates/cairo-lang-lowering/src/optimizations/config.rs#L41)):*
> ```XML
>         }
>     }
> }
> ```

revert the default.



_Code quote:_
```XML
    fn default() -> Self {
        Self {
            moveable_functions: vec![],
            inline_small_functions_threshold: DEFAULT_INLINE_SMALL_FUNCTIONS_THRESHOLD,
        }
    }
}
```
___
*[`crates/cairo-lang-lowering/src/test_data/call` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5067#-NqcDzW9B889q7yoK-rT:-NqcDzW9B889q7yoK-rU:b-nh1leg) ([raw file](https://github.com/starkware-libs/cairo/blob/071a6fb92786ac793405e2368f9e9a8b4eef7272/crates/cairo-lang-lowering/src/test_data/call#L1)):*
> ```
> //! > Test function call.
> ```

make the test actually test as stated.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5067)* status: 21 of 84 files reviewed, 12 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 430 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5067#-NqcDPLLErFwvF9c1Yr9:-NqwOuc909tBC9uWnrdO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/071a6fb92786ac793405e2368f9e9a8b4eef7272/crates/cairo-lang-lowering/src/inline/mod.rs#L430)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc.
and use above.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/optimizations/config.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5067#-NqcDoKqDSrRkyaeDvnV:-NqwP6cb1GljPz79qOqO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/071a6fb92786ac793405e2368f9e9a8b4eef7272/crates/cairo-lang-lowering/src/optimizations/config.rs#L24)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc all functions.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/optimizations/config.rs` line 41 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5067#-NqcDrhO1hK1DGSvgu41:-NqwPZGC46Roktb3HbWC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/071a6fb92786ac793405e2368f9e9a8b4eef7272/crates/cairo-lang-lowering/src/optimizations/config.rs#L41)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

revert the default.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/test_data/call` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5067#-NqcDzW9B889q7yoK-rT:-NqwV4G_E7G62XfuqP7L:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/071a6fb92786ac793405e2368f9e9a8b4eef7272/crates/cairo-lang-lowering/src/test_data/call#L1)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

make the test actually test as stated.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/test_data/loop` line 26 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5067#-NqcF2FB88tlgjVBAizc:-NqwUiMW09plqKEVQmNW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/071a6fb92786ac793405e2368f9e9a8b4eef7272/crates/cairo-lang-lowering/src/test_data/loop#L26)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix test.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/test_data/loop` line 57 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5067#-NqcF5dN9Y4nHOOe3-rY:-NqwUi2gEbz8QytYjj6b:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/071a6fb92786ac793405e2368f9e9a8b4eef7272/crates/cairo-lang-lowering/src/test_data/loop#L57)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix test.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/test_data/snapshot` line 54 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5067#-NqcFMBj4EfbnILA9u1L:-NqwSwTJBS9uQJGocuSd:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/071a6fb92786ac793405e2368f9e9a8b4eef7272/crates/cairo-lang-lowering/src/test_data/snapshot#L54)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

inline never.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/program_generator_test.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5067#-NqcGyjG98FNok15rZhD:-NqwR1Az3VBi1XXBk8P_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/071a6fb92786ac793405e2368f9e9a8b4eef7272/crates/cairo-lang-sierra-generator/src/program_generator_test.rs#L40)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add never inline instead.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/stack_tracking` line 21 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5067#-NqcHO4xCS3JlZGEQ3AS:-NqwSGBZ7DhMmbFWz9F1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/071a6fb92786ac793405e2368f9e9a8b4eef7272/crates/cairo-lang-sierra-generator/src/function_generator_test_data/stack_tracking#L21)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add inline never.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/stack_tracking` line 99 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5067#-NqcHRiD68z3Z2VIr2W_:-NqwSFxA5Om0n4WXC72K:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/071a6fb92786ac793405e2368f9e9a8b4eef7272/crates/cairo-lang-sierra-generator/src/function_generator_test_data/stack_tracking#L99)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add inline never.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/local_variables_test_data/e2e` line 270 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5067#-NqcHWu49bJv6I1hbcBV:-NqwRz9n0_jankhAwxGg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/071a6fb92786ac793405e2368f9e9a8b4eef7272/crates/cairo-lang-sierra-generator/src/local_variables_test_data/e2e#L270)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add inline never.

and everywhere else to avoid actual test changes.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-ap-change/src/compute.rs` line 318 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5067#-NqcGr0U5W4RpIwN_ozP:-NqwSyn6499EHLsJNay2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/071a6fb92786ac793405e2368f9e9a8b4eef7272/crates/cairo-lang-sierra-ap-change/src/compute.rs#L318)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

revert
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 82 files at r1, 7 of 41 files at r3, 10 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5067)* status: 33 of 84 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-lowering/src/test_data/logical_operator` line 16 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5067#-NqwqwWA4YbTjK4YmtVN:-NqwqwWA4YbTjK4YmtVO:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2dae7825f9421486aad641f2ac9b44c212140f12/crates/cairo-lang-lowering/src/test_data/logical_operator#L16)):*
> ```
> //! > module_code
> extern fn extern_get_bool() -> bool nopanic;
> fn get_bool() -> bool {
> ```





_Suggestion:_
```
extern fn extern_get_bool() -> bool nopanic;
#[inline(never)]
fn get_bool() -> bool {
```
___
*[`crates/cairo-lang-sierra-generator/src/program_generator_test_data/function_call` line 22 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5067#-NqwrVPP1weaikm-Jvep:-NqwrVPP1weaikm-Jveq:b-18y3hi) ([raw file](https://github.com/starkware-libs/cairo/blob/d342723f06e6e706a0a563e5193dfda86332016e/crates/cairo-lang-sierra-generator/src/program_generator_test_data/function_call#L22)):*
> ```
> libfunc const_as_immediate<Const<felt252, 5>> = const_as_immediate<Const<felt252, 5>>;
> libfunc store_temp<felt252> = store_temp<felt252>;
> libfunc function_call<user@test::bar> = function_call<user@test::bar>;
> ```

test should still test function call.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 41 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5067)* status: 34 of 84 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/config.rs` line 27 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5067#-NqwsU5X2HVE194H4xC0:-NqwsU5Y87nQUdJpS9vm:bnp7z7g) ([raw file](https://github.com/starkware-libs/cairo/blob/2dae7825f9421486aad641f2ac9b44c212140f12/crates/cairo-lang-lowering/src/optimizations/config.rs#L27)):*
> ```XML
> impl OptimizationConfig {
>     /// Creates a new OptimizationConfig with the given moveable functions and default threshold.
>     pub fn new(moveable_functions: Vec<String>) -> Self {
> ```

feel free to make it into a default - did not notice it was a builder pattern.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5067)* status: 29 of 84 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/test_data/logical_operator` line 16 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5067#-NqwqwWA4YbTjK4YmtVN:-Nr-WRRQ4iDjsNCB2F_N:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2dae7825f9421486aad641f2ac9b44c212140f12/crates/cairo-lang-lowering/src/test_data/logical_operator#L16)):*
> ```
> //! > module_code
> extern fn extern_get_bool() -> bool nopanic;
> fn get_bool() -> bool {
> ```

Done.
___
*[`crates/cairo-lang-sierra-generator/src/program_generator_test_data/function_call` line 22 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5067#-NqwrVPP1weaikm-Jvep:-Nr-WOIj7WQkaDz7pQl-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d342723f06e6e706a0a563e5193dfda86332016e/crates/cairo-lang-sierra-generator/src/program_generator_test_data/function_call#L22)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

test should still test function call.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 18 of 82 files at r1, 31 of 41 files at r3, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5067)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`tests/e2e_test_data/libfuncs/coupon` line 345 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5067#-Nr-cV4F0LvfXEfKRGDE:-Nr-cV4F0LvfXEfKRGDF:b-h849pn) ([raw file](https://github.com/starkware-libs/cairo/blob/d342723f06e6e706a0a563e5193dfda86332016e/tests/e2e_test_data/libfuncs/coupon#L345)):*
> ```
> 
> //! > casm
> [ap + 0] = [fp + -4], ap++;
> ```

revert using never.
___
*[`tests/e2e_test_data/libfuncs/snapshot` line 19 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5067#-Nr-bvfbBKoQx0GReDxm:-Nr-bvfbBKoQx0GReDxn:b-h849pn) ([raw file](https://github.com/starkware-libs/cairo/blob/d342723f06e6e706a0a563e5193dfda86332016e/tests/e2e_test_data/libfuncs/snapshot#L19)):*
> ```
> [ap + 0] = [fp + -4], ap++;
> [ap + 0] = [fp + -3], ap++;
> call rel 5;
> ```

revert using never.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5067#-:-Nr-hO0cA2cqqhjCXurR:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5067)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
