### PR TITLE
feat(cairo-format): allow using module items sorting

### PR DESCRIPTION
**Pull request by LucasLvy**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3991)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3991#-:-Nd6FT-I7wnR2umVpY50:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @LucasLvy)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 12 of 36 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3991)* status: 13 of 37 files reviewed, 2 unresolved discussions (waiting on @LucasLvy)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3991#-Nd6MEhR4lBUjSSrYxbM:-Nd6MEhR4lBUjSSrYxbN:b3u7s5j) (no related file):*
@yuvalsw 2nd eye.

___
___
*[`corelib/src/test/byte_array_test.cairo` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3991#-Nd6M1tfA53dJoQocNJ4:-Nd6M1tg6zK2AMJ70n7I:b-502rv7) ([raw file](https://github.com/starkware-libs/cairo/blob/1be3499173d51b6e539b12db0b76a3f766769d0a/corelib/src/test/byte_array_test.cairo#L1)):*
> ```Cairo
> // ========= Test helper functions =========
> ```

move the comment back.



_Code quote:_
```Cairo
// ========= Test helper functions =========
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 36 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3991)* status: 19 of 37 files reviewed, 6 unresolved discussions (waiting on @LucasLvy)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3991#-Nd6Muv50BdE-pm7Wri8:-Nd6Muv50BdE-pm7Wri9:bluxjap) (no related file):*
Add extra empty line between `mod`s and `use`s

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3991#-Nd6N0z6DZMIJoibl9wP:-Nd6N0z6DZMIJoibl9wQ:bx7asf) (no related file):*
separate to another PR enabling this in this repo.

___
___
*[`corelib/src/lib.cairo` line 52 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3991#-Nd6MM6Y4EkOjZ0XqmkJ:-Nd6MM6Y4EkOjZ0XqmkK:b-9e8oi9) ([raw file](https://github.com/starkware-libs/cairo/blob/1be3499173d51b6e539b12db0b76a3f766769d0a/corelib/src/lib.cairo#L52)):*
> ```Cairo
> // Option.
> mod option;
> ```

remove space
___
*[`corelib/src/lib.cairo` line 82 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3991#-Nd6Maym0sKTZVlfdCXJ:-Nd6Mayn3LFG-UWxCUyD:b-cn63j1) ([raw file](https://github.com/starkware-libs/cairo/blob/1be3499173d51b6e539b12db0b76a3f766769d0a/corelib/src/lib.cairo#L82)):*
> ```Cairo
> mod traits;
> 
> // Zeroable.
> ```

remove useless comments.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 36 of 36 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3991#-:-Nd9u01Z1g52dwh7C8_R:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @LucasLvy)

**Comment by mkaput** [comment]
*[`crates/bin/cairo-format/src/main.rs` line 186 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3991#-Nd9vSnt0TdmQjMu9m5n:-Nd9vSnt0TdmQjMu9m5o:b-lxjgml) ([raw file](https://github.com/starkware-libs/cairo/blob/500db22e2b63aa9494e9a6240102504fd76b9d23/crates/bin/cairo-format/src/main.rs#L186)):*
> ```XML
> 
>     let args = FormatterArgs::parse();
>     let config = FormatterConfig::default().sort_module_level_items(args.sort_mod_level_items);
> ```

protip



_Suggestion:_
```XML
let config = FormatterConfig { sort_module_level_items: args.sort_mod_level_items, ..FormatterConfig::default() };
```

**Review by LucasLvy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3991)* status: all files reviewed, 1 unresolved discussion (waiting on @LucasLvy)

___
*[`crates/bin/cairo-format/src/main.rs` line 186 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3991#-Nd9vSnt0TdmQjMu9m5n:-Nd9yCNj61tlnMRUEHgp:bac7t71) ([raw file](https://github.com/starkware-libs/cairo/blob/500db22e2b63aa9494e9a6240102504fd76b9d23/crates/bin/cairo-format/src/main.rs#L186)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

protip
</blockquote></details>

the fields are private so no :cry:

**Comment by mkaput** [comment]
*[`crates/bin/cairo-format/src/main.rs` line 186 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3991#-Nd9vSnt0TdmQjMu9m5n:-NdET1iy0hDP3QddIFqm:b-4m3xjf) ([raw file](https://github.com/starkware-libs/cairo/blob/500db22e2b63aa9494e9a6240102504fd76b9d23/crates/bin/cairo-format/src/main.rs#L186)):*
<details><summary><i>Previously, LucasLvy (Lucas @ StarkWare) wrote…</i></summary><blockquote>

the fields are private so no :cry:
</blockquote></details>

I don't see anything against adding them. We can do that in #3999

**Pull request merged**
