### PR TITLE
LS: Proc macro plugins

### PR DESCRIPTION
**Pull request by Draggu**
**Stack**:
- #6706
- #6705
- #6704
- #6638
- #6703
- #6702 ⬅
- #6637

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6702)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, and @orizi)

___
*[`crates/cairo-lang-language-server/src/lang/db/mod.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6702#-OCCcCdJA-IPxlNjFOl0:-OCCcCdJA-IPxlNjFOl1:b-tfuvl3) ([raw file](https://github.com/starkware-libs/cairo/blob/61485e069b28ee39c54329e4647ec7f744c0d63e/crates/cairo-lang-language-server/src/lang/db/mod.rs#L62)):*
> ```XML
>             get_default_plugin_suite(),
>             starknet_plugin_suite(),
>             // test_plugin_suite() TODO(#6551)
> ```

this comment will not be detected by TODO comment indexers, the `TODO` keyword must go first
___
*[`crates/cairo-lang-language-server/src/lang/db/mod.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6702#-OCCcPZQ4p-RRDUARMzF:-OCCcPZQ4p-RRDUARMzG:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/61485e069b28ee39c54329e4647ec7f744c0d63e/crates/cairo-lang-language-server/src/lang/db/mod.rs#L104)):*
> ```XML
>     ///
>     /// Plugins are considered equal if they use the same [`Arc`].
>     pub(crate) fn replace_plugin_suite(
> ```





_Suggestion:_
```XML
pub fn replace_plugin_suite(
```
___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/plugins/mod.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6702#-OCCcMpD6HF6H5SYXFEf:-OCCcMpD6HF6H5SYXFEg:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/61485e069b28ee39c54329e4647ec7f744c0d63e/crates/cairo-lang-language-server/src/lang/proc_macros/plugins/mod.rs#L7)):*
> ```XML
> use scarb_proc_macro_server_types::methods::defined_macros::DefinedMacrosResponse;
> 
> pub(crate) fn proc_macro_plugin_suite(defined_macros: DefinedMacrosResponse) -> PluginSuite {
> ```





_Suggestion:_
```XML
pub fn proc_macro_plugin_suite(defined_macros: DefinedMacrosResponse) -> PluginSuite {
```

**Review by Draggu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6702)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @integraledelebesgue, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lang/db/mod.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6702#-OCCcCdJA-IPxlNjFOl0:-OCDUW5X5tLkb53cXhqd:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/61485e069b28ee39c54329e4647ec7f744c0d63e/crates/cairo-lang-language-server/src/lang/db/mod.rs#L62)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

this comment will not be detected by TODO comment indexers, the `TODO` keyword must go first
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/plugins/mod.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6702#-OCCcMpD6HF6H5SYXFEf:-OCDXnkv7HZEQwOFX0Pk:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/61485e069b28ee39c54329e4647ec7f744c0d63e/crates/cairo-lang-language-server/src/lang/proc_macros/plugins/mod.rs#L7)):*
> ```XML
> use scarb_proc_macro_server_types::methods::defined_macros::DefinedMacrosResponse;
> 
> pub(crate) fn proc_macro_plugin_suite(defined_macros: DefinedMacrosResponse) -> PluginSuite {
> ```

Done.
___
*[`crates/cairo-lang-language-server/src/lang/db/mod.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6702#-OCCcPZQ4p-RRDUARMzF:-OCDUYbp9zGv4jQEv6oN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/61485e069b28ee39c54329e4647ec7f744c0d63e/crates/cairo-lang-language-server/src/lang/db/mod.rs#L104)):*
> ```XML
>     ///
>     /// Plugins are considered equal if they use the same [`Arc`].
>     pub(crate) fn replace_plugin_suite(
> ```

Done.

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6702)* status: all files reviewed, 7 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, and @orizi)

___
*[`crates/cairo-lang-language-server/src/lang/db/mod.rs` line 63 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6702#-OCHbW2_AucJ2Bgr2Vp-:-OCHbW2_AucJ2Bgr2Vp0:b-q41yb) ([raw file](https://github.com/starkware-libs/cairo/blob/f294bd8044c6b3efd3fd0a49cf952ca2b07dcfc1/crates/cairo-lang-language-server/src/lang/db/mod.rs#L63)):*
> ```XML
>             starknet_plugin_suite(),
>             // TODO(#6551)
>             // test_plugin_suite()
> ```

missing description



_Suggestion:_
```XML
            // TODO(#6551): Restore this.
            // test_plugin_suite()
```
___
*[`crates/cairo-lang-language-server/src/lang/db/mod.rs` line 104 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6702#-OCHbxwR5yA1XRAXp5hJ:-OCHbxwR5yA1XRAXp5hK:bddfxjr) ([raw file](https://github.com/starkware-libs/cairo/blob/f294bd8044c6b3efd3fd0a49cf952ca2b07dcfc1/crates/cairo-lang-language-server/src/lang/db/mod.rs#L104)):*
> ```XML
>     ///  - retains other plugins present in the db.
>     ///
>     /// Plugins are considered equal if they use the same [`Arc`].
> ```

this doc comment does not follow the 

```
<one sentence/line summary>

<detailed description>
```

format



_Code quote:_
```XML
    /// Modifies plugins in the db:
    ///  - removes plugins from `plugins_to_remove`,
    ///  - adds plugins from `plugins_to_add`,
    ///  - retains other plugins present in the db.
    ///
    /// Plugins are considered equal if they use the same [`Arc`].
```
___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/plugins/mod.rs` line 7 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6702#-OCHaTCw6tDLFzppqNOg:-OCHaTCw6tDLFzppqNOh:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/f294bd8044c6b3efd3fd0a49cf952ca2b07dcfc1/crates/cairo-lang-language-server/src/lang/proc_macros/plugins/mod.rs#L7)):*
> ```XML
> use scarb_proc_macro_server_types::methods::defined_macros::DefinedMacrosResponse;
> 
> pub fn proc_macro_plugin_suite(defined_macros: DefinedMacrosResponse) -> PluginSuite {
> ```

doc
___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/plugins/mod.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6702#-OCHaPSB7IuXOkRrsi24:-OCHaPSB7IuXOkRrsi25:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/f294bd8044c6b3efd3fd0a49cf952ca2b07dcfc1/crates/cairo-lang-language-server/src/lang/proc_macros/plugins/mod.rs#L26)):*
> ```XML
> 
> #[derive(Debug)]
> struct ProcMacroPlugin {
> ```

doc
___
*[`crates/cairo-lang-language-server/src/lang/db/swapper.rs` line 126 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6702#-OCHaiQ02aEymrt4Vwxs:-OCHaiQ02aEymrt4Vwxt:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/f294bd8044c6b3efd3fd0a49cf952ca2b07dcfc1/crates/cairo-lang-language-server/src/lang/db/swapper.rs#L126)):*
> ```XML
> 
>         // TODO(#6646) probably this should not be part of migration as it will be ever growing.
>         // But diagnostics going crazy every 5 minutes are no better.
> ```





_Suggestion:_
```XML
        // TODO(#6646): Probably this should not be part of migration as it will be ever growing,
        //   but diagnostics going crazy every 5 minutes are no better.
```
___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/db.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6702#-OCHbMOD0T3P3OldJ99D:-OCHbMOD0T3P3OldJ99E:buegr3d) ([raw file](https://github.com/starkware-libs/cairo/blob/f294bd8044c6b3efd3fd0a49cf952ca2b07dcfc1/crates/cairo-lang-language-server/src/lang/proc_macros/db.rs#L14)):*
> ```XML
>     /// Allows access to client from compiler plugins `.generate_code()` methods.
>     #[salsa::input]
>     fn attribute_macro_resolution(&self) -> FxHashMap<ExpandAttributeParams, ProcMacroResult>;
> ```

why FxHashMap? why standard HashMap is not enough?
___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/db.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6702#-OCHbPEx-ERZNMtfWUzj:-OCHbPEx-ERZNMtfWUzk:bxd9z1l) ([raw file](https://github.com/starkware-libs/cairo/blob/f294bd8044c6b3efd3fd0a49cf952ca2b07dcfc1/crates/cairo-lang-language-server/src/lang/proc_macros/db.rs#L14)):*
> ```XML
>     /// Allows access to client from compiler plugins `.generate_code()` methods.
>     #[salsa::input]
>     fn attribute_macro_resolution(&self) -> FxHashMap<ExpandAttributeParams, ProcMacroResult>;
> ```

Wrap result in Arc

**Review by Arcticae — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6702#-:-OCIIrzH3tHrV2HtylT0:bg7igkv)* status: all files reviewed, 8 unresolved discussions (waiting on @Draggu, @integraledelebesgue, and @orizi)

___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/controller.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6702#-OCIGS6sCP6lHeDer7l1:-OCIGS6sCP6lHeDer7l2:b2bfpsv) ([raw file](https://github.com/starkware-libs/cairo/blob/f294bd8044c6b3efd3fd0a49cf952ca2b07dcfc1/crates/cairo-lang-language-server/src/lang/proc_macros/controller.rs#L105)):*
> ```XML
>                 let new_plugin_suite = proc_macro_plugin_suite(defined_macros);
> 
>                 // Store current plugins for identity comparison, so we can remove them if we
> ```

Where do we store it? I think it's misleading comment unless i don't understand the replacing logic

**Review by Draggu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6702)* status: 1 of 6 files reviewed, 7 unresolved discussions (waiting on @Arcticae, @integraledelebesgue, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/src/lang/db/mod.rs` line 63 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6702#-OCHbW2_AucJ2Bgr2Vp-:-OCIqS1aDrbSalqWsZWQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f294bd8044c6b3efd3fd0a49cf952ca2b07dcfc1/crates/cairo-lang-language-server/src/lang/db/mod.rs#L63)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

missing description
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lang/db/mod.rs` line 104 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6702#-OCHbxwR5yA1XRAXp5hJ:-OCIrOIl-UHUgDwtGI5U:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f294bd8044c6b3efd3fd0a49cf952ca2b07dcfc1/crates/cairo-lang-language-server/src/lang/db/mod.rs#L104)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

this doc comment does not follow the 

```
<one sentence/line summary>

<detailed description>
```

format
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/controller.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6702#-OCIGS6sCP6lHeDer7l1:-OCIVTBT5mh14Jcs7_gF:bst63u9) ([raw file](https://github.com/starkware-libs/cairo/blob/f294bd8044c6b3efd3fd0a49cf952ca2b07dcfc1/crates/cairo-lang-language-server/src/lang/proc_macros/controller.rs#L105)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

Where do we store it? I think it's misleading comment unless i don't understand the replacing logic
</blockquote></details>

https://doc.rust-lang.org/std/option/enum.Option.html#method.replace
___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/db.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6702#-OCHbMOD0T3P3OldJ99D:-OCIrviV7wqPGPimP8-g:b-wswgfu) ([raw file](https://github.com/starkware-libs/cairo/blob/f294bd8044c6b3efd3fd0a49cf952ca2b07dcfc1/crates/cairo-lang-language-server/src/lang/proc_macros/db.rs#L14)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

why FxHashMap? why standard HashMap is not enough?
</blockquote></details>

It's enough. `FxHashMap` is used widely in the compiler, so I copied it from there. It is a standard `HashMap` with a faster hash function. Can use a regular one but don't see why would we.
___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/db.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6702#-OCHbPEx-ERZNMtfWUzj:-OCIsLI3-z5YShGPIcRC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f294bd8044c6b3efd3fd0a49cf952ca2b07dcfc1/crates/cairo-lang-language-server/src/lang/proc_macros/db.rs#L14)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Wrap result in Arc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/plugins/mod.rs` line 7 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6702#-OCHaTCw6tDLFzppqNOg:-OCItK169m5y3o6a8XKp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f294bd8044c6b3efd3fd0a49cf952ca2b07dcfc1/crates/cairo-lang-language-server/src/lang/proc_macros/plugins/mod.rs#L7)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/plugins/mod.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6702#-OCHaPSB7IuXOkRrsi24:-OCItKLZBP-DVT7hFBLT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f294bd8044c6b3efd3fd0a49cf952ca2b07dcfc1/crates/cairo-lang-language-server/src/lang/proc_macros/plugins/mod.rs#L26)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lang/db/swapper.rs` line 126 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6702#-OCHaiQ02aEymrt4Vwxs:-OCIrZn-1nskVTn4Gwbv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f294bd8044c6b3efd3fd0a49cf952ca2b07dcfc1/crates/cairo-lang-language-server/src/lang/db/swapper.rs#L126)):*
> ```XML
> 
>         // TODO(#6646) probably this should not be part of migration as it will be ever growing.
>         // But diagnostics going crazy every 5 minutes are no better.
> ```

Done.

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6702)* status: all files reviewed, 1 unresolved discussion (waiting on @Draggu, @integraledelebesgue, and @orizi)

___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/db.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6702#-OCHbMOD0T3P3OldJ99D:-OCXkGJh03nota-Nvs7s:b-75iezv) ([raw file](https://github.com/starkware-libs/cairo/blob/f294bd8044c6b3efd3fd0a49cf952ca2b07dcfc1/crates/cairo-lang-language-server/src/lang/proc_macros/db.rs#L14)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

It's enough. `FxHashMap` is used widely in the compiler, so I copied it from there. It is a standard `HashMap` with a faster hash function. Can use a regular one but don't see why would we.
</blockquote></details>



I would rather use std HashMap or our OrderedHashMap and eradicate FxHashMap from the codebase to reduce amount of dependencies

**Review by Draggu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6702)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @integraledelebesgue, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/db.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6702#-OCHbMOD0T3P3OldJ99D:-OCY7oCh4n7VaGyEzFpB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f294bd8044c6b3efd3fd0a49cf952ca2b07dcfc1/crates/cairo-lang-language-server/src/lang/proc_macros/db.rs#L14)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>



I would rather use std HashMap or our OrderedHashMap and eradicate FxHashMap from the codebase to reduce amount of dependencies
</blockquote></details>

Done.

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 4 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6702)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
