### PR TITLE
Refund gas in dict_squash.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1739)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1739)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/dict_felt_to.rs` line 209 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1739#-NLWTsJ71aK52TArWupp:-NLWTsJ71aK52TArWupq:b-4l9p7b) ([raw file](https://github.com/starkware-libs/cairo/blob/d777d0a838479e0a7353e0cc2a0d0b55848944eb/crates/cairo-lang-sierra-to-casm/src/invocations/dict_felt_to.rs#L209)):*
> ```XML
>             tempvar squashed_dict_len = returned_squashed_dict_end - returned_squashed_dict_start;
>             tempvar accesses_len_minus_squashed_len = dict_accesses_len - squashed_dict_len;
>             tempvar n_refunded_accesses = accesses_len_minus_squashed_len / dict_access_size;
> ```

doc the optimization



_Code quote:_
```XML
            tempvar n_refunded_accesses = accesses_len_minus_squashed_len / dict_access_size;
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1739#-:-NLWTyjBArUaazjg_BMb:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1739)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/dict_felt_to.rs` line 209 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1739#-NLWTsJ71aK52TArWupp:-NM4Z-LmB0cjWUaDo97s:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d777d0a838479e0a7353e0cc2a0d0b55848944eb/crates/cairo-lang-sierra-to-casm/src/invocations/dict_felt_to.rs#L209)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc the optimization
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1739)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1739)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
