### PR TITLE
Add uint128_eq support for immediates

### PR DESCRIPTION
**Pull request by amosStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1479)

### CODE REVIEW

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1479)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @amosStarkware)

___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 431 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1479#-NKIAmMIALmiRbiHEJ8m:-NKIAmMJABJOqCGpcXHl:b-jr8jj9) ([raw file](https://github.com/starkware-libs/cairo/blob/d2ab291693538a58b42cfe78454851fb12694468/crates/sierra_to_casm/src/invocations/uint128.rs#L431)):*
> ```XML
> 
>             // diff = a - b => (diff == 0) <==> (a == b)
>             const _diff = diff;
> ```

Is it ok that there is an additional casm line (and an additional ap increase) when a,b are both immediates?



_Code quote:_
```XML
const _diff = diff;
```

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1479)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 430 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1479#-NKIDCNv4nIS2HuWunYL:-NKIDCNv4nIS2HuWunYM:b4k59eu) ([raw file](https://github.com/starkware-libs/cairo/blob/69544b63259c75f5465505f555166e6195e91741/crates/sierra_to_casm/src/invocations/uint128.rs#L430)):*
> ```XML
> 
>         casm_build_extend! {casm_builder,
>             // This line is needed because a tempvar does not accept (only) an immediate in the rhs.
> ```

is this correct?



_Code quote:_
```XML
// This line is needed because a tempvar does not accept (only) an immediate in the rhs.
```

**Review by amosStarkware — COMMENTED** [review]
+reviewer:@dorimedini-starkware

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1479#-:-NKIDv1l7YumIETK5aCU:bavka44)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1479)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 398 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1479#-NKJCCzl4dLLBEYNEI5X:-NKJCCzl4dLLBEYNEI5Y:bfznjke) ([raw file](https://github.com/starkware-libs/cairo/blob/69544b63259c75f5465505f555166e6195e91741/crates/sierra_to_casm/src/invocations/uint128.rs#L398)):*
> ```XML
>     builder: CompiledInvocationBuilder<'_>,
> ) -> Result<CompiledInvocation, InvocationError> {
>     let mut casm_builder = CasmBuilder::default();
> ```

I suggest you use Rust's `if let` pattern to check if `a` or `b` are immediates; also, I would first check if `a` is immediate and if so swap between `a` and `b`. Then, you can check if the "new" `a` is immediate, and if so, both are immediate.
```
if let DerefOrImmediate::Immediate(_) = a {
    [a, b] = [b, a];
}
if let DerefOrImmediate::Immediate(_) = a {
    // Both are immediate...
}
```

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1479)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 398 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1479#-NKJCCzl4dLLBEYNEI5X:-NKJN1Wq8ZRCuV6sQ-sM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/69544b63259c75f5465505f555166e6195e91741/crates/sierra_to_casm/src/invocations/uint128.rs#L398)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I suggest you use Rust's `if let` pattern to check if `a` or `b` are immediates; also, I would first check if `a` is immediate and if so swap between `a` and `b`. Then, you can check if the "new" `a` is immediate, and if so, both are immediate.
```
if let DerefOrImmediate::Immediate(_) = a {
    [a, b] = [b, a];
}
if let DerefOrImmediate::Immediate(_) = a {
    // Both are immediate...
}
```
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1479)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware)

___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 431 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1479#-NKIAmMIALmiRbiHEJ8m:-NKJORMf8DBDRYdzFtv8:b-8lofl2) ([raw file](https://github.com/starkware-libs/cairo/blob/d2ab291693538a58b42cfe78454851fb12694468/crates/sierra_to_casm/src/invocations/uint128.rs#L431)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

Is it ok that there is an additional casm line (and an additional ap increase) when a,b are both immediates?
</blockquote></details>

This `const` doesn't touch AP AFAIK, it is a helper line for the CASM builder. @orizi amiright?
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 430 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1479#-NKIDCNv4nIS2HuWunYL:-NKJOO216JgWXRdZTzEr:b31209v) ([raw file](https://github.com/starkware-libs/cairo/blob/69544b63259c75f5465505f555166e6195e91741/crates/sierra_to_casm/src/invocations/uint128.rs#L430)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

is this correct?
</blockquote></details>

Looks like it
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 433 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1479#-NKJOsHl6vjcATP_1UY0:-NKJOsHl6vjcATP_1UY1:b7tyje6) ([raw file](https://github.com/starkware-libs/cairo/blob/20f6e946f26d3c61bee7a946dea48495075a346a/crates/sierra_to_casm/src/invocations/uint128.rs#L433)):*
> ```XML
>         DerefOrImmediate::Deref(_) => {
>             let a = match a {
>                 DerefOrImmediate::Deref(cell_ref_a) => {
> ```

does this work?



_Suggestion:_
```XML
        DerefOrImmediate::Deref(cell_ref_a) => {
            let a = casm_builder.add_var(ResOperand::Deref(cell_ref_a));
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1479)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 431 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1479#-NKIAmMIALmiRbiHEJ8m:-NKJQkek40LAVxCl1u0v:b-vcheou) ([raw file](https://github.com/starkware-libs/cairo/blob/d2ab291693538a58b42cfe78454851fb12694468/crates/sierra_to_casm/src/invocations/uint128.rs#L431)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

This `const` doesn't touch AP AFAIK, it is a helper line for the CASM builder. @orizi amiright?
</blockquote></details>

yet - only tempvar is a write to an actual mem cell.
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 446 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1479#-NKJRD3R501Fwug3xsac:-NKJRD3R501Fwug3xsad:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/20f6e946f26d3c61bee7a946dea48495075a346a/crates/sierra_to_casm/src/invocations/uint128.rs#L446)):*
> ```XML
>                 DerefOrImmediate::Immediate(big_int_b) => {
>                     casm_builder.add_var(ResOperand::Immediate(big_int_b))
>                 }
> ```





_Suggestion:_
```XML
fn build_u128_eq(
    builder: CompiledInvocationBuilder<'_>,
) -> Result<CompiledInvocation, InvocationError> {
    let mut casm_builder = CasmBuilder::default();
    let [expr_a, expr_b] = builder.try_get_refs()?;
    let a = expr_a.try_unpack_single()?;
    let b = expr_b.try_unpack_single()?;
    // The target line to jump to if a != b.
    let target_statement_id = get_non_fallthrough_statement_id(&builder);
    let (a, b) = match (a, b) {
        (CellExpression::Deref(a), CellExpression::Deref(b)) => (ResOperand::Deref(a), ResOperand::DerefOrImmediate(deref_or_immediate!(b))),
        (CellExpression::Deref(a), CellExpression::Immediate(b)) => (ResOperand::Deref(a), ResOperand::DerefOrImmediate(deref_or_immediate!(b))),
        (CellExpression::Immediate(a), CellExpression::Deref(b)) => (ResOperand::Deref(b), ResOperand::DerefOrImmediate(deref_or_immediate!(a))),
        (CellExpression::Immediate(a), CellExpression::Immediate(b)) => {
                casm_build_extend! {casm_builder,
                    const diff = a - b;
                    tempvar diff = diff
                    // diff = a - b => (diff == 0) <==> (a == b)
                    jump NotEqual if diff != 0;
                    jump Equal;
                NotEqual:
                };
                Ok(builder.build_from_casm_builder(
                    casm_builder,
                    [("Fallthrough", &[], None), ("Equal", &[], Some(target_statement_id))],
                ))
            
        }
        _ => InvocationError::InvalidReferenceExpressionForArgument,
    }

    casm_build_extend! {casm_builder,
        // diff = a - b => (diff == 0) <==> (a == b)
        tempvar diff = a - b;
        jump NotEqual if diff != 0;
        jump Equal;
    NotEqual:
    };
    Ok(builder.build_from_casm_builder(
        casm_builder,
        [("Fallthrough", &[], None), ("Equal", &[], Some(target_statement_id))],
    ))
```

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1479)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @orizi)

___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 433 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1479#-NKJOsHl6vjcATP_1UY0:-NKNK2049TpXQ5YU6fHt:b-etbufo) ([raw file](https://github.com/starkware-libs/cairo/blob/20f6e946f26d3c61bee7a946dea48495075a346a/crates/sierra_to_casm/src/invocations/uint128.rs#L433)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

does this work?
</blockquote></details>

Changed, thanks
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 446 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1479#-NKJRD3R501Fwug3xsac:-NKNXHGp7IVhZP41BL0v:bw3ylif) ([raw file](https://github.com/starkware-libs/cairo/blob/20f6e946f26d3c61bee7a946dea48495075a346a/crates/sierra_to_casm/src/invocations/uint128.rs#L446)):*
> ```XML
>                 DerefOrImmediate::Immediate(big_int_b) => {
>                     casm_builder.add_var(ResOperand::Immediate(big_int_b))
>                 }
> ```

I did a couple of changes and the code is shorter - are you sure the change you suggested is needed? @orizi

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1479)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @orizi)

___
*[`crates/cairo-sierra-to-casm/src/invocations/uint128.rs` line 415 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1479#-NKNhAbA3G5Te1Cujnta:-NKNhAbA3G5Te1Cujntb:b-5ua6f4) ([raw file](https://github.com/starkware-libs/cairo/blob/024443670ba11c5b3ef0bdda46e73fc523cc6e52/crates/cairo-sierra-to-casm/src/invocations/uint128.rs#L415)):*
> ```XML
>         DerefOrImmediate::Immediate(big_int_a) => {
>             let big_int_b = match b {
>                 DerefOrImmediate::Immediate(big_int_b) => big_int_b,
> ```

Try the `let else` pattern?
```
let DerefOrImmediate::Immediate(big_int_b) = b else { panic!("a & b should have been switched.") }
```



_Code quote:_
```XML
            let big_int_b = match b {
                DerefOrImmediate::Immediate(big_int_b) => big_int_b,
                DerefOrImmediate::Deref(_) => {
                    panic!("a & b should have been switched.");
                }
            };
```

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1479)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @orizi)

___
*[`crates/cairo-sierra-to-casm/src/invocations/uint128.rs` line 415 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1479#-NKNhAbA3G5Te1Cujnta:-NKNhvEO2I9YtqDsCSxu:b-gncgko) ([raw file](https://github.com/starkware-libs/cairo/blob/024443670ba11c5b3ef0bdda46e73fc523cc6e52/crates/cairo-sierra-to-casm/src/invocations/uint128.rs#L415)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Try the `let else` pattern?
```
let DerefOrImmediate::Immediate(big_int_b) = b else { panic!("a & b should have been switched.") }
```
</blockquote></details>

why is it better though?
I didn't like having two `let` in the same line

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1479)* status: all files reviewed, 5 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/cairo-sierra/src/extensions/lib_func.rs` line 296 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1479#-NKNhSrY4huaqww4YWid:-NKNhSrY4huaqww4YWie:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/024443670ba11c5b3ef0bdda46e73fc523cc6e52/crates/cairo-sierra/src/extensions/lib_func.rs#L296)):*
> ```XML
> /// Information regarding a parameter of the libfunc.
> #[derive(Clone)]
> pub struct ParamSignature {
> ```

remove



_Code quote:_
```XML
#[derive(Clone)]
```
___
*[`crates/cairo-sierra/src/extensions/modules/uint128.rs` line 361 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1479#-NKNhV9gAHniCtg5FVF_:-NKNhV9gAHniCtg5FVFa:b-fogta3) ([raw file](https://github.com/starkware-libs/cairo/blob/024443670ba11c5b3ef0bdda46e73fc523cc6e52/crates/cairo-sierra/src/extensions/modules/uint128.rs#L361)):*
> ```XML
>             })
>             .collect();
>         let param_signature = ParamSignature {
> ```

currently just write it twice.



_Code quote:_
```XML
        let param_signature = ParamSignature {
            ty: u128_ty,
            allow_deferred: false,
            allow_add_const: false,
            allow_const: true,
        };
```
___
*[`crates/cairo-sierra-to-casm/src/invocations/uint128.rs` line 427 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1479#-NKNk0c_55EAuMVyenp7:-NKNk0ca2eZPfOTOtvw-:b4i62g6) ([raw file](https://github.com/starkware-libs/cairo/blob/024443670ba11c5b3ef0bdda46e73fc523cc6e52/crates/cairo-sierra-to-casm/src/invocations/uint128.rs#L427)):*
> ```XML
>                 // rhs.
>                 const _diff = diff;
> ```

_ means unused.
Rename.

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1479)* status: 3 of 6 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @orizi)

___
*[`crates/cairo-sierra/src/extensions/modules/uint128.rs` line 361 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1479#-NKNhV9gAHniCtg5FVF_:-NKNo5eK0PW9BVEtDpqh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/024443670ba11c5b3ef0bdda46e73fc523cc6e52/crates/cairo-sierra/src/extensions/modules/uint128.rs#L361)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

currently just write it twice.
</blockquote></details>

Done.
___
*[`crates/cairo-sierra-to-casm/src/invocations/uint128.rs` line 427 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1479#-NKNk0c_55EAuMVyenp7:-NKNpPsLB7vBk1FM2AhF:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/024443670ba11c5b3ef0bdda46e73fc523cc6e52/crates/cairo-sierra-to-casm/src/invocations/uint128.rs#L427)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

_ means unused.
Rename.
</blockquote></details>

Done
___
*[`crates/cairo-sierra/src/extensions/lib_func.rs` line 296 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1479#-NKNhSrY4huaqww4YWid:-NKNm9G51vHWTo36ul6_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/024443670ba11c5b3ef0bdda46e73fc523cc6e52/crates/cairo-sierra/src/extensions/lib_func.rs#L296)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 446 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1479#-NKJRD3R501Fwug3xsac:-NKO9ObA0pEwqHDjwMh9:bcp0io1) ([raw file](https://github.com/starkware-libs/cairo/blob/20f6e946f26d3c61bee7a946dea48495075a346a/crates/sierra_to_casm/src/invocations/uint128.rs#L446)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

I did a couple of changes and the code is shorter - are you sure the change you suggested is needed? @orizi 
</blockquote></details>

I took your suggestion, thanks

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1479#-:-NKOB3qz-N4aHK8FtZ_X:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-sierra-to-casm/src/invocations/uint128.rs` line 443 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1479#-NKOAnTZ3GRvxxRCp8pC:-NKOAnTZ3GRvxxRCp8pD:b-hk4rpo) ([raw file](https://github.com/starkware-libs/cairo/blob/5571bcd25369b2af6f306dbdea44a8f425410bcc/crates/cairo-sierra-to-casm/src/invocations/uint128.rs#L443)):*
> ```XML
>     casm_build_extend! {casm_builder,
>         // diff = a - b => (diff == 0) <==> (a == b)
>         tempvar diff = a - b;
> ```

didn't know you could do that... I though you had to do
```
tempvar diff;
assert a = diff + b;
```



_Code quote:_
```XML
tempvar diff = a - b;
```

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1479)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1479#-:-NKOOUPW2lUpUHknucbZ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware)

___
*[`crates/cairo-sierra-to-casm/src/invocations/uint128.rs` line 436 at r6](https://reviewable.io/reviews/starkware-libs/cairo/1479#-NKOO4rY5tZKZ9H1amZt:-NKOO4rY5tZKZ9H1amZu:b-ydbts8) ([raw file](https://github.com/starkware-libs/cairo/blob/4a5891c661dae3817148e4ed8418d60f5c19169e/crates/cairo-sierra-to-casm/src/invocations/uint128.rs#L436)):*
> ```XML
>         }
>         _ => {
>             panic!("a & b can only be deref or immediate.");
> ```

Return InvocationError:: that means the argument is not in the valid form instead of panicking

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1479)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @orizi)

___
*[`crates/cairo-sierra-to-casm/src/invocations/uint128.rs` line 436 at r6](https://reviewable.io/reviews/starkware-libs/cairo/1479#-NKOO4rY5tZKZ9H1amZt:-NKOV-f51AwjNvhwZIFt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4a5891c661dae3817148e4ed8418d60f5c19169e/crates/cairo-sierra-to-casm/src/invocations/uint128.rs#L436)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Return InvocationError:: that means the argument is not in the valid form instead of panicking
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1479)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1479)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1479)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
