### PR TITLE
Clean up panics in lowering

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1565)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1565)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lowering/src/lower.rs` line 649 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1565#-NKS0BKv9F5yxpYetfsX:-NKS0BKv9F5yxpYetfsY:b-qjvh2s) ([raw file](https://github.com/starkware-libs/cairo/blob/ee2f0c5bae8b8dbc728a2deeb02f8834dbdab78f/crates/cairo-lowering/src/lower.rs#L649)):*
> ```XML
>                             ctx.diagnostics.report(expr.stable_ptr.untyped(), UnsupportedMatch)
>                         })?;
>                         // TODO(spapini): Convert to a diagnostic.
> ```

is the TODO still relevent?



_Code quote:_
```XML
// TODO(spapini): Convert to a diagnostic.
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1565)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @orizi, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lowering/src/lower/implicits.rs` line 126 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1565#-NKS0UeLDmpyl9Vl-5Y7:-NKS0UeLDmpyl9Vl-5Y8:bm5uf20) ([raw file](https://github.com/starkware-libs/cairo/blob/ee2f0c5bae8b8dbc728a2deeb02f8834dbdab78f/crates/cairo-lowering/src/lower/implicits.rs#L126)):*
> ```XML
>         self.db
>             .free_function_definition_direct_free_function_callees(self.free_function_id)
>             .unwrap_or_default()
> ```

why does default makes sense here?

consider adding a todo.



_Code quote:_
```XML
_or_default
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1565)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @yuvalsw)

___
*[`crates/cairo-lowering/src/lower/implicits.rs` line 126 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1565#-NKS0UeLDmpyl9Vl-5Y7:-NKS0fk8-smQef4iRXIR:ba2rzri) ([raw file](https://github.com/starkware-libs/cairo/blob/ee2f0c5bae8b8dbc728a2deeb02f8834dbdab78f/crates/cairo-lowering/src/lower/implicits.rs#L126)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why does default makes sense here?

consider adding a todo.
</blockquote></details>

Becase if I call an unknown function, I can't deduce it's implciits. It is probably best to just not consider, and a diagnostics is reported in another place anyway.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1565)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @yuvalsw)

___
*[`crates/cairo-lowering/src/lower.rs` line 649 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1565#-NKS0BKv9F5yxpYetfsX:-NKS0zWmCr5F2eJj4Lhl:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ee2f0c5bae8b8dbc728a2deeb02f8834dbdab78f/crates/cairo-lowering/src/lower.rs#L649)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

is the TODO still relevent?
</blockquote></details>

Done.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1565)* status: all files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lowering/src/lower.rs` line 647 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1565#-NKS69dw5inyiCBlbVgq:-NKS69dw5inyiCBlbVgr:bqsp5tq) ([raw file](https://github.com/starkware-libs/cairo/blob/51bd7e910b6138f77e64585f088196b841ee457e/crates/cairo-lowering/src/lower.rs#L647)):*
> ```XML
>                         )
>                         .ok_or_else(|| {
>                             ctx.diagnostics.report(expr.stable_ptr.untyped(), UnsupportedMatch)
> ```

consider



_Suggestion:_
```XML
UnsupportedMatchArm
```
___
*[`crates/cairo-lowering/src/lower.rs` line 656 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1565#-NKS6_sm5Iz2ROI_mQDE:-NKS6_sm5Iz2ROI_mQDF:b2uye8v) ([raw file](https://github.com/starkware-libs/cairo/blob/51bd7e910b6138f77e64585f088196b841ee457e/crates/cairo-lowering/src/lower.rs#L656)):*
> ```XML
>                         }
>                         // TODO(spapini): Make a better diagnostic.
>                         if arm_inputs.len() != 1 {
> ```

This means a bug in the compiler, not the compiled cairo code , as the input of length 1 is defined above here in this function:
`let input_tys = vec![concrete_variant.ty];`

Do we want to add diagnostics on our bugs or panic on them?

(same in lower_optimized_extern_match)



_Code quote:_
```XML
 if arm_inputs.len() != 1 {
```
___
*[`crates/cairo-lowering/src/lower.rs` line 728 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1565#-NKS6GohCsAHBW4-kxY4:-NKS6GohCsAHBW4-kxY5:bdkys98) ([raw file](https://github.com/starkware-libs/cairo/blob/51bd7e910b6138f77e64585f088196b841ee457e/crates/cairo-lowering/src/lower.rs#L728)):*
> ```XML
>                     // Create a scope for the arm block.
>                     merger.run_in_subscope(ctx, input_tys, |ctx, subscope, mut arm_inputs| {
>                         // TODO(spapini): Convert to a diagnostic.
> ```

modify TODOs here and below



_Code quote:_
```XML
// TODO(spapini): Convert to a diagnostic.
```
___
*[`crates/cairo-lowering/src/lower.rs` line 886 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1565#-NKS73cxDhzDvkfzqyZa:-NKS73cxDhzDvkfzqyZb:b-aa0bjh) ([raw file](https://github.com/starkware-libs/cairo/blob/51bd7e910b6138f77e64585f088196b841ee457e/crates/cairo-lowering/src/lower.rs#L886)):*
> ```XML
>     if expr.arms.len() != concrete_variants.len() {
>         return Err(LoweringFlowError::Failed(
>             ctx.diagnostics.report(expr.stable_ptr.untyped(), UnsupportedMatch),
> ```

This is the only one that should be `UnsupportedMatch`. The others should be UnsupportedMatchArm



_Code quote:_
```XML
UnsupportedMatch
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1565)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @yuvalsw)

___
*[`crates/cairo-lowering/src/lower.rs` line 656 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1565#-NKS6_sm5Iz2ROI_mQDE:-NKSAjjo2ZLFePm7G1jo:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/51bd7e910b6138f77e64585f088196b841ee457e/crates/cairo-lowering/src/lower.rs#L656)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

This means a bug in the compiler, not the compiled cairo code , as the input of length 1 is defined above here in this function:
`let input_tys = vec![concrete_variant.ty];`

Do we want to add diagnostics on our bugs or panic on them?

(same in lower_optimized_extern_match)
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1565#-:-NKSCtto2_UHrgUSDlcn:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @yuvalsw)

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 5 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1565#-:-NKSCuXSBqX7EiLvQS5v:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 3 of 5 files at r1, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1565)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1565#-:-NKSPMAF5PP7Vt4kqBOo:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lowering/src/lower.rs` line 662 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1565#-NKSPG4pDaMTK3_Dfesq:-NKSPG4pDaMTK3_Dfesr:b-b7m8ed) ([raw file](https://github.com/starkware-libs/cairo/blob/13501aa5c9d20e38630049f7f2fc8d37bf887b35/crates/cairo-lowering/src/lower.rs#L662)):*
> ```XML
>                                 .report(expr.stable_ptr.untyped(), UnsupportedMatchArm));
>                         }
>                         assert_eq!(arm_inputs.len(), 1);
> ```

Please add a comment that this assertion is OK

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1565)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
