### PR TITLE
Corrupt root if there is an inlining issue.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1975)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1975#-:-NN1YgzrBpWo0AqWUXaJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1975#-:-NN1iKcU4mc7Gp_uwoBw:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 180 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1975#-NN1hudu0AClOgXTpTvd:-NN1hudvBscLuEmh0J6Q:b364mug) ([raw file](https://github.com/starkware-libs/cairo/blob/1922f24df963fa71b13c4c5a327e8c3213287a69/crates/cairo-lang-lowering/src/inline/mod.rs#L180)):*
> ```XML
>     /// stack for statements that require rewriting.
>     statement_rewrite_stack: StatementStack,
> ```

Revert blank line?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1975)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 180 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1975#-NN1hudu0AClOgXTpTvd:-NN1mk9e3XSXF2ZfbuRh:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/1922f24df963fa71b13c4c5a327e8c3213287a69/crates/cairo-lang-lowering/src/inline/mod.rs#L180)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Revert blank line?
</blockquote></details>

done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1975)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1975)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`-- commits` line 5 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1975#-NN60dg81PnfrwX_ZLSM):*
what is there to add here?



_Code quote:_
```
- b0e6936: wip
```

**Review by orizi — APPROVED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1975)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1975)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`-- commits` line 5 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1975#-NN60dg81PnfrwX_ZLSM):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

what is there to add here?
</blockquote></details>

removed

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1975)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
