### PR TITLE
Return module items in ast order.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1914)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1914)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-defs/src/db.rs` line 403 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1914#-NMgtSag3q75VyU_2MYd:-NMgtSag3q75VyU_2MYe:bbpfuf5) ([raw file](https://github.com/starkware-libs/cairo/blob/e3cc1965ce9489f2dbc9d60d3b1a149f9ca11db2/crates/cairo-lang-defs/src/db.rs#L403)):*
> ```XML
>                 }
>             };
>             items.push(module_item);
> ```

I got connot borrow arc as mutable when I tried

res.items.push(module_item);



_Code quote:_
```XML
 items.push(module_item);
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1914#-:-NMgwewVEhzp5PhhWNty:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1914#-:-NMhhqcd10u9IdaH7PZd:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1914)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Pull request merged**
