### PR TITLE
match_optimizer.rs: Small refactor.

### PR DESCRIPTION
**Pull request by liorgold2**
**Stack**:
- #6337
- #6339
- #6338
- #6341 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6341)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 292 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6341#-O5w57y33-sGVexC5acr:-O5w57y33-sGVexC5acs:b-ywrlsa) ([raw file](https://github.com/starkware-libs/cairo/blob/6d58bb63a3311be24417302242024440c45508c0/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L292)):*
> ```XML
>             infos.map(|info| (info.demand, info.reachable_blocks)).unzip();
> 
>         let arm_demands_with_arm_var = zip_eq(match_info.arms(), &arm_demands)
> ```

why with_arm_var?

maybe 
_without_arm_var?



_Suggestion:_
```XML
arm_demands
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6341)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 292 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6341#-O5w57y33-sGVexC5acr:-O5wRpAA9-LhLsLE44-x:b97dul5) ([raw file](https://github.com/starkware-libs/cairo/blob/6d58bb63a3311be24417302242024440c45508c0/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L292)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why with_arm_var?

maybe 
_without_arm_var?
</blockquote></details>

demand.variables_introduced does not add variables, it removes them.

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6341)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 292 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6341#-O5w57y33-sGVexC5acr:-O5wSMQ73j9n16czrwCZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6d58bb63a3311be24417302242024440c45508c0/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L292)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

demand.variables_introduced does not add variables, it removes them.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6341#-:-O5wUBUD8DshL1NaK7d5:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
