### PR TITLE
Fix destructure location.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6069)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 956 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6069#-O2d5NNg4uyUd_eCTNU_:-O2d5NNg4uyUd_eCTNUa:b-7jmhyu) ([raw file](https://github.com/starkware-libs/cairo/blob/34581608e95a7ea1956c09a497557700b104e738/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L956)):*
> ```
>   () <- test::consume(v2{`x.b`})
> End:
>   Return(v0)
> ```

before the fix



_Suggestion:_
```
//! > lowering_diagnostics
error: Variable was previously moved.
 --> lib.cairo:12:5
    y
    ^
note: variable was previously used here:
  --> lib.cairo:10:9
    let y = x;
        ^
note: Trait has no implementation in context: core::traits::Copy::<test::MyStruct>.

//! > lowering
Parameters: v0: test::MyStruct
blk0 (root):
Statements:
  (v1: core::felt252, v2: test::NonCopy) <- struct_destructure(v0{`y`})
  () <- test::consume(v2{`x.b`})
End:
  Return(v0)
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 956 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6069#-O2d5aZODNETIHxHQpDZ:-O2d5aZPDmcpX2jXE2qg:b-27pdd1) ([raw file](https://github.com/starkware-libs/cairo/blob/34581608e95a7ea1956c09a497557700b104e738/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L956)):*
> ```
>   () <- test::consume(v2{`x.b`})
> End:
>   Return(v0)
> ```

If I return x instead of y, then it is reconstructed rather than returning v0.



_Suggestion:_
```
Parameters: v0: test::MyStruct
blk0 (root):
Statements:
  (v1: core::felt252, v2: test::NonCopy) <- struct_destructure(v0{`x.b`})
  () <- test::consume(v2{`x.b`})
  (v3: ()) <- struct_construct()
  (v4: test::MyStruct) <- struct_construct(v1{`x`}, v2{`x`})
End:
  Return(v4, v3)
```

**Review by orizi — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6069)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 956 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6069#-O2d5NNg4uyUd_eCTNU_:-O2d6lnb0UoH4xDv_z0n:bguriru) ([raw file](https://github.com/starkware-libs/cairo/blob/34581608e95a7ea1956c09a497557700b104e738/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L956)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

before the fix
</blockquote></details>

isn't the previous one more correct?
the move of `y` is when it is assigned to `x` - isn't it?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 956 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6069#-O2d5NNg4uyUd_eCTNU_:-O2dKOV82UFUNsLPTA22:b-ip7aq7) ([raw file](https://github.com/starkware-libs/cairo/blob/34581608e95a7ea1956c09a497557700b104e738/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L956)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

isn't the previous one more correct?
the move of `y` is when it is assigned to `x` - isn't it?
</blockquote></details>

why does
y = x 
move y?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6069)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 956 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6069#-O2d5NNg4uyUd_eCTNU_:-O2dWK_4ABPmxHhacY1K:b-8cdoji) ([raw file](https://github.com/starkware-libs/cairo/blob/34581608e95a7ea1956c09a497557700b104e738/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L956)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why does
y = x 
move y?
</blockquote></details>

Doesn't it? Try using y.b after let x = y

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 956 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6069#-O2d5NNg4uyUd_eCTNU_:-O2dXDNr6RYzIcN5g00Y:b7s2l8d) ([raw file](https://github.com/starkware-libs/cairo/blob/34581608e95a7ea1956c09a497557700b104e738/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L956)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Doesn't it? Try using y.b after let x = y
</blockquote></details>

it is 
let y = x
not 
let x = y.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6069)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 956 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6069#-O2d5NNg4uyUd_eCTNU_:-O2dYMJp7QiiAHFFWlT1:b-uatgbi) ([raw file](https://github.com/starkware-libs/cairo/blob/34581608e95a7ea1956c09a497557700b104e738/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L956)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it is 
let y = x
not 
let x = y.
</blockquote></details>

oh right, but what happens if you return x without the consume call instead?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 956 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6069#-O2d5NNg4uyUd_eCTNU_:-O2daR8p1O5ijZ9LIE9X:bufnmj2) ([raw file](https://github.com/starkware-libs/cairo/blob/34581608e95a7ea1956c09a497557700b104e738/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L956)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

oh right, but what happens if you return x without the consume call instead?
</blockquote></details>

it compiles.
let y = x 
just maps y to the same variable as x.
As we don't have to rename in the lowering.

maybe we should add it.



_Code snippet:_
```
fn foo(x: MyStruct) -> MyStruct {
    let y = x;
    x
}

//! > lowering_diagnostics

//! > lowering
Parameters: v0: test::MyStruct
blk0 (root):
Statements:
End:
  Return(v0)
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6069#-:-O2db8CP1j3aIB8kJYSn:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6069#-:-O2jBOcl6dquF6yFKFk4:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
