### PR TITLE
Change prepare_libfunc_argument to return VarState for all the argume…

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
…nts.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4182)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4182)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 250 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4182#-Nfl9Bml95E3xto9OkQV:-Nfl9Bml95E3xto9OkQW:beugg9m) ([raw file](https://github.com/starkware-libs/cairo/blob/c7afff9c1a7b4773d616c42466225381e51364d1/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L250)):*
> ```XML
>                                         VarState::TempVar { ty: deferred_info.ty.clone() }
>                                     } else {
>                                         VarState::LocalVar
> ```

can `store_deferred` already return the `VarState`?



_Code quote:_
```XML
                                    return if self.store_deferred(arg, deferred_info.clone()) {
                                        VarState::TempVar { ty: deferred_info.ty.clone() }
                                    } else {
                                        VarState::LocalVar
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 349 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4182#-Nft3jAvBBhNtouF3cPK:-Nft3jAvBBhNtouF3cPL:b-1f8u8c) ([raw file](https://github.com/starkware-libs/cairo/blob/c7afff9c1a7b4773d616c42466225381e51364d1/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L349)):*
> ```XML
>                     self.state()
>                         .variables
>                         .insert(var.clone(), VarState::TempVar { ty: ty.clone() });
> ```

This is already done inside `self.store_deferred_ex`



_Code quote:_
```XML
                    self.state()
                        .variables
                        .insert(var.clone(), VarState::TempVar { ty: ty.clone() });
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 349 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4182#-Nft3jAvBBhNtouF3cPK:-Nft43zp6F2LpZS9oDtj:b-z9n0sc) ([raw file](https://github.com/starkware-libs/cairo/blob/c7afff9c1a7b4773d616c42466225381e51364d1/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L349)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

This is already done inside `self.store_deferred_ex`
</blockquote></details>

nvm, I'm wrong, it is done for `var_on_stack` not `var`

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4182)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 250 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4182#-Nfl9Bml95E3xto9OkQV:-Nft4aVN5neDI_SBpSRT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c7afff9c1a7b4773d616c42466225381e51364d1/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L250)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can `store_deferred` already return the `VarState`?
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4182)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 298 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4182#-NftSlEz8Dt0MZgvxaAM:-NftSlEz8Dt0MZgvxaAN:b-fxccnf) ([raw file](https://github.com/starkware-libs/cairo/blob/14f5f009488fdc99689d4c72e33944c0a6acaf92/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L298)):*
> ```XML
>         } else {
>             self.store_temp(var, var_on_stack, &deferred_info.ty);
>             VarState::TempVar { ty: deferred_info.ty.clone() }
> ```

why is the clone required?



_Code quote:_
```XML
deferred_info.ty.clone(
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4182)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 298 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4182#-NftSlEz8Dt0MZgvxaAM:-NftX4oZ-sqQ7Goe4omE:bw9gb6c) ([raw file](https://github.com/starkware-libs/cairo/blob/14f5f009488fdc99689d4c72e33944c0a6acaf92/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L298)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why is the clone required?
</blockquote></details>

you are right, it wasn't required.

In any case, I've decided no to pass `deferred_info` as only the type is requred.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4182#-:-NftZbhJ0y234u_9nwnG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
