### PR TITLE
Added support for constant being refereneced bu another constant.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5088)

### CODE REVIEW

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5088)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/constant` line 219 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5088#-Nr0BQ__EP5tUs_IBpqS:-Nr0BQ__EP5tUs_IBpqT:b9dj5na) ([raw file](https://github.com/starkware-libs/cairo/blob/5b23d0937cfd1ed21fa95646c1328ea6adde8ebc/crates/cairo-lang-semantic/src/expr/test_data/constant#L219)):*
> ```
> 
> //! > module_code
> const A: i8 = A;
> ```

Add indirect cycle.



_Suggestion:_
```
const A: i8 = A;
const B: i8 = C;
const C: i8 = B;
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5088)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/constant` line 219 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5088#-Nr0BQ__EP5tUs_IBpqS:-Nr0x0rl9ACl3wVH5bdE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b58a8fb629f5f411aed7662e349029095cd6d6a6/crates/cairo-lang-semantic/src/expr/test_data/constant#L219)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Add indirect cycle.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 180 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5088#-Nr0CZu32eSUGY42pEET:-Nr0wD0n1Ia_9nMphDo1:b5pflxs) ([raw file](https://github.com/starkware-libs/cairo/blob/b58a8fb629f5f411aed7662e349029095cd6d6a6/crates/cairo-lang-semantic/src/items/constant.rs#L180)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Doc that in case of a cycle we continue as usual and the cycle will be detected in `priv_constant_semantic_data`.
btw nice trick, we can probably use it in other places where we have long cycles and each function got its own cycle handler.
</blockquote></details>

Done
PR's already open on main for all others.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5088#-:-Nr4ejoq3nGynaPWD1kL:bnfp4nl)* status: 2 of 5 files reviewed, all discussions resolved

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5088)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
