### PR TITLE
Docs: describe usage of Scarb in vscode extension

### PR DESCRIPTION
**Pull request by maciektr**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3281)

### CODE REVIEW

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3281)* status: all files reviewed, 1 unresolved discussion (waiting on @maciektr and @spapinistarkware)

___
*[`vscode-cairo/README.md` line 57 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3281#-NWqd2hA83e6sT1nGvLG:-NWqd2hA83e6sT1nGvLH:b-o9lgqs) ([raw file](https://github.com/starkware-libs/cairo/blob/d5941f22eb32de730caff9f4dc8882088a57bbb1/vscode-cairo/README.md#L57)):*
> ```Markdown
> 
> In case you have installed both Scarb with bundled language server and standalone language server,
> Scarb will decide which one to used based on the type of project you run.
> ```

It's VSCode extension which decides, isn't it?

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3281)* status: all files reviewed, 2 unresolved discussions (waiting on @maciektr)

___
*[`vscode-cairo/README.md` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3281#-NWrEDnUDsWOGxO3QugV:-NWrEDnV6qevjPwGuVTz:b-v0rgdx) ([raw file](https://github.com/starkware-libs/cairo/blob/d5941f22eb32de730caff9f4dc8882088a57bbb1/vscode-cairo/README.md#L59)):*
> ```Markdown
> Scarb will decide which one to used based on the type of project you run.
> 
> If your project includes the Scarb manifest file (`scarb.toml`), the one bundled with scarb will be used.
> ```

Keep lines under 100chars

**Comment by maciektr** [comment]
*[`vscode-cairo/README.md` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3281#-NWrEDnUDsWOGxO3QugV:-NWrh5xmDvTN0_PiHjCx:b-cuv3rg) ([raw file](https://github.com/starkware-libs/cairo/blob/d5941f22eb32de730caff9f4dc8882088a57bbb1/vscode-cairo/README.md#L59)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Keep lines under 100chars
</blockquote></details>

Thanks!  I've rewritten this.

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3281#-:-NWunppt8uwdb7enUzbn:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3281#-:-NX9CF_10Ng6ygDBeQ6F:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciektr)

**Pull request merged**
