### PR TITLE
Fixed the cases of the extra store bugs for non-duplicatable types.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:4369c122

---

**Stack**:
- #1369
- #1368
- #1367
- #1366
- #1365
- #1364
- #1349
- #1348 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1348)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1348#-:-NJLW_meBo-FqtZXFDkI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1348)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/sierra_generator/src/store_variables/mod.rs` line 206 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1348#-NJZEmQjCSwLIMUiOJPc:-NJZEmQjCSwLIMUiOJPd:bnr28jp) ([raw file](https://github.com/starkware-libs/cairo/blob/dc1eb271c103a1f358db2bbc0379f02039e2ca47/crates/sierra_generator/src/store_variables/mod.rs#L206)):*
> ```XML
>                 }
>             };
>             if !self
> ```

```
// In this case, the deferred value can be used directly by the libfunc and does not
// require a store statement.
// If its type is not duplicatable, we remove it from the deferred_variables map to
// ensure it won't be stored later.
```

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1348)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1348)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @liorgold2)

___
*[`crates/sierra_generator/src/store_variables/mod.rs` line 206 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1348#-NJZEmQjCSwLIMUiOJPc:-NJZHTFX0Z_GFBISeebU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/dc1eb271c103a1f358db2bbc0379f02039e2ca47/crates/sierra_generator/src/store_variables/mod.rs#L206)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

```
// In this case, the deferred value can be used directly by the libfunc and does not
// require a store statement.
// If its type is not duplicatable, we remove it from the deferred_variables map to
// ensure it won't be stored later.
```
</blockquote></details>

Done.

**Review by liorgold2 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1348)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1348#-:-NJZRgqT9MpC4R37YmuC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
