### PR TITLE
Add AllocateDictFeltTo to the hint_processor.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1666)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1666#-:-NLFqETN75Wrx_Po95nj:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-casm/src/dict_manager.rs` line 30 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1666#-NLFpcoq4teaPsfYpml_:-NLFpcoq4teaPsfYpmla:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ebeb454438a4a1253167e0c269a23ea96f8ae67b/crates/cairo-lang-casm/src/dict_manager.rs#L30)):*
> ```XML
> 
> impl DictManagerExecScope {
>     /// Allocates a new segment for a new dictionary and return the start of the segment.
> ```





_Suggestion:_
```XML
    /// Allocates a new segment for a new dictionary and return the start of the segment.
    pub fn new_default_dict(&mut self, vm: &mut VirtualMachine) -> Relocatable {
        let dict_segment = vm.add_memory_segment();
        assert!(
            !self.trackers.contains_key(&dict_segment.segment_index),
            "Segment index already in use."
        );
        self.trackers
            .insert(dict_segment.segment_index, DictTrackerExecScope::new(self.trackers.len()));
        dict_segment
    }
    
    /// Returns a reference for a dict tracker corresponding to a given pointer to a dict segment.
    fn get_dict_tracker(&self, dict_end: Relocatable) -> &DictTrackerExecScope {
        self.trackers
            .get(&dict_end.segment_index)
            .expect("The given value does not point to a known dictionary.")
    }
    
    /// Returns a mut reference for a dict tracker corresponding to a given pointer to a dict
    /// segment.
    fn get_dict_tracker_mut(&mut self, dict_end: Relocatable) -> &mut DictTrackerExecScope {
        self.trackers
            .get_mut(&dict_end.segment_index)
            .expect("The given value does not point to a known dictionary.")
    }
    
    /// Returns the index of the dict tracker corresponding to a given pointer to a dict segment.
    pub fn get_dict_infos_index(&self, dict_end: Relocatable) -> usize {
        self.get_dict_tracker(dict_end).idx
    }
    
    /// Inserts a value to the dict tracker corresponding to a given pointer to a dict segment.
    pub fn insert_to_tracker(&mut self, dict_end: Relocatable, key: BigInt, value: BigInt) {
        self.get_dict_tracker_mut(dict_end).data.insert(key, value);
    }
    
    /// Gets a value from the dict tracker corresponding to a given pointer to a dict segment.
    /// None if the key does not exist in the tracker data.
    pub fn get_from_tracker(&self, dict_end: Relocatable, key: BigInt) -> Option<BigInt> {
        self.get_dict_tracker(dict_end).data.get(&key).cloned()
    }
```
___
*[`crates/cairo-lang-casm/src/dict_manager.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1666#-NLFpOoV2WX9BV--XmOJ:-NLFpOoV2WX9BV--XmOK:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ebeb454438a4a1253167e0c269a23ea96f8ae67b/crates/cairo-lang-casm/src/dict_manager.rs#L35)):*
> ```XML
>         assert!(
>             !self.trackers.contains_key(&dict_segment.segment_index),
>             "Segment index already in use."
> ```





_Suggestion:_
```XML
        assert!(
            self.trackers
            .insert(dict_segment.segment_index, DictTrackerExecScope::new(self.trackers.len())).is_none(),
            "Segment index already in use."
        );
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1666)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-casm/src/dict_manager.rs` line 30 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1666#-NLFpcoq4teaPsfYpml_:-NLGNQVHA5EUyEgHzTpl:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ebeb454438a4a1253167e0c269a23ea96f8ae67b/crates/cairo-lang-casm/src/dict_manager.rs#L30)):*
> ```XML
> 
> impl DictManagerExecScope {
>     /// Allocates a new segment for a new dictionary and return the start of the segment.
> ```

Done.
___
*[`crates/cairo-lang-casm/src/dict_manager.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1666#-NLFpOoV2WX9BV--XmOJ:-NLGOBfz15xNCThRTD4k:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ebeb454438a4a1253167e0c269a23ea96f8ae67b/crates/cairo-lang-casm/src/dict_manager.rs#L35)):*
> ```XML
>         assert!(
>             !self.trackers.contains_key(&dict_segment.segment_index),
>             "Segment index already in use."
> ```

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1666)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1666)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
