### PR TITLE
Added option decide on ranking of the variables minimization.

### PR DESCRIPTION
**Pull request by orizi**
Using it for gas solver to solve cases where a caller function
minimization is inactive (as in contracts entrypoints, which always take
10000), so that the minimization remains valid. previously since the function
had a constant price, calling another function created space to allow
claiming the inner function has a higher cost, to reduce the cost of
several following branch aligns.
first minimizing the function costs, and only then minimizing branch
aligments solve this.

---

**Stack**:
- #2471
- #2470
- #2469 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2469)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2469)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2469#-NQVAirc9xnf0hMdJ_D8):*
why is it inactive for contract entry points?



_Code quote:_
```
  Using it for gas to solve cases where a caller function minimization is
  inactive (as in contracts entrypoints) - so that the minimization
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2469)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 152 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2469#-NQVAuF1E0xx7IJGx_qv:-NQVAuF1E0xx7IJGx_qw:b-hfpv1m) ([raw file](https://github.com/starkware-libs/cairo/blob/db27fa04e2a4f5ca27d4973230794f71fd42a382/crates/cairo-lang-sierra-gas/src/lib.rs#L152)):*
> ```XML
>         let function_vars = all_vars
>             .clone()
>             // .filter(|v| matches!(v, Var::StatementFuture(_, _)))
> ```

remove?



_Code quote:_
```XML
  // .filter(|v| matches!(v, Var::StatementFuture(_, _)))
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2469)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-eq-solver/src/lib.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2469#-NQVCm884m4b4lVK9dbO:-NQVCm884m4b4lVK9dbP:b-6iy1c3) ([raw file](https://github.com/starkware-libs/cairo/blob/db27fa04e2a4f5ca27d4973230794f71fd42a382/crates/cairo-lang-eq-solver/src/lib.rs#L61)):*
> ```XML
>         }
>     }
>     let target: Expression = target_vars.iter().map(|v| *orig_to_solver_var.get(v).unwrap()).sum();
> ```

can you do this out side of this function and pass
target to minimize?

I think it is easier to explain then ` minimization_vars`



_Code quote:_
```XML
    let target: Expression = target_vars.iter().map(|v| *orig_to_solver_var.get(v).unwrap()).sum();
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-eq-solver/src/lib.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2469#-NQVTx2N2RK0eenf-a9b:-NQVTx2N2RK0eenf-a9c:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/db27fa04e2a4f5ca27d4973230794f71fd42a382/crates/cairo-lang-eq-solver/src/lib.rs#L40)):*
> ```XML
> /// # Arguments
> /// * `equations` - The equations to solve.
> /// * `target_vars` - Vars to minimize.
> ```





_Suggestion:_
```XML
minimize the sum of those variables.
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2469)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2469#-NQVAirc9xnf0hMdJ_D8):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why is it inactive for contract entry points?
</blockquote></details>

oh - it is inactive since we require a constant amount.
___
*[`crates/cairo-lang-eq-solver/src/lib.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2469#-NQVTx2N2RK0eenf-a9b:-NQVWYDc1aU2nepu7bCV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/db27fa04e2a4f5ca27d4973230794f71fd42a382/crates/cairo-lang-eq-solver/src/lib.rs#L40)):*
> ```XML
> /// # Arguments
> /// * `equations` - The equations to solve.
> /// * `target_vars` - Vars to minimize.
> ```

Done.
___
*[`crates/cairo-lang-eq-solver/src/lib.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2469#-NQVCm884m4b4lVK9dbO:-NQVW_Px8OU6SKhQ2rpK:b-qubpkp) ([raw file](https://github.com/starkware-libs/cairo/blob/db27fa04e2a4f5ca27d4973230794f71fd42a382/crates/cairo-lang-eq-solver/src/lib.rs#L61)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

can you do this out side of this function and pass
target to minimize?

I think it is easier to explain then ` minimization_vars`
</blockquote></details>

it occurs on the actual solver vars - so not really - as discussed f2f
___
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 152 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2469#-NQVAuF1E0xx7IJGx_qv:-NQVWnNv5inlYZ4-Lsfz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/db27fa04e2a4f5ca27d4973230794f71fd42a382/crates/cairo-lang-sierra-gas/src/lib.rs#L152)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

remove?
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2469)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @orizi)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2469#-NQVAirc9xnf0hMdJ_D8):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

oh - it is inactive since we require a constant amount.
</blockquote></details>

The commit message is unclear.
please rephrase.



_Code quote:_
```
  Using it for gas to solve cases where a caller function minimization is
  inactive (as in contracts entrypoints) - so that the minimization
  remains valid.
```
___
*[`crates/cairo-lang-eq-solver/src/lib.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2469#-NQVTx2N2RK0eenf-a9b:-NQVVp-k7JTMSZOD-G4T:bb7p4yc) ([raw file](https://github.com/starkware-libs/cairo/blob/db27fa04e2a4f5ca27d4973230794f71fd42a382/crates/cairo-lang-eq-solver/src/lib.rs#L40)):*
> ```XML
> /// # Arguments
> /// * `equations` - The equations to solve.
> /// * `target_vars` - Vars to minimize.
> ```

the

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2469)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-eq-solver/src/lib.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2469#-NQVTx2N2RK0eenf-a9b:-NQVgRbk8D3NSUGEUwej:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/db27fa04e2a4f5ca27d4973230794f71fd42a382/crates/cairo-lang-eq-solver/src/lib.rs#L40)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

the 
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2469)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2469#-NQVAirc9xnf0hMdJ_D8):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

The commit message is unclear.
please rephrase.
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-eq-solver/src/lib.rs` line 29 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2469#-NQVk8GeBFr9UfbmfNEr:-NQVk8GeBFr9UfbmfNEs:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5db9857bf89989d602dd5dd40803a9301d498957/crates/cairo-lang-eq-solver/src/lib.rs#L29)):*
> ```XML
>         let layer_solution = try_solve_equations_iteration(&equations, target_vars)?;
>         // Adding equations for variables that were already solved.
>         for v in target_vars {
> ```





_Suggestion:_
```XML
 // Add constraints for the solutions that we found for the target variables.
```

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2469#-:-NQVlG_OBSag_ubbYoj8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
