### PR TITLE
Add ECDSA verification.

### PR DESCRIPTION
**Pull request by liorgold2**
commit-id:dde28e32

---

**Stack**:
- #1921
- #1920 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1920)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1920)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @Alon-Ti and @liorgold2)

___
*[`corelib/ecdsa.cairo` line 71 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1920#-NMhOquwCRj__YNNOXFi:-NMhOquwCRj__YNNOXFj:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b4618258c4bb952abef763d0961f91d0527a5415/corelib/ecdsa.cairo#L71)):*
> ```Cairo
> 
>     let zG: Option::<EcPoint> = ec_mul(gen_point, message_hash);
>     let rQ: Option::<EcPoint> = ec_mul(public_key_point, signature_r);
> ```





_Suggestion:_
```Cairo

    let sR: Option::<EcPoint> = ec_mul(signature_r_point, signature_s);
    let sR_x = match sR {
        Option::Some(pt) => {
            let (x, y) = ec_point_unwrap(pt);
            x
        },
        Option::None(()) => {
            return false;
        },
    };
    
    let zG: Option::<EcPoint> = ec_mul(gen_point, message_hash);
    let rQ: Option::<EcPoint> = ec_mul(public_key_point, signature_r);

    match zG + rQ {
        Option::Some(pt) => {
            let (x, y) = ec_point_unwrap(pt);
            if (x == sR_x) {
                return true;
            }
        },
        Option::None(()) => {
        },
    };

    match zG - rQ {
        Option::Some(pt) => {
            let (x, y) = ec_point_unwrap(pt);
            if (x == sR_x) {
                return true;
            }
        },
        Option::None(()) => {
        },
    };

    return false;
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1920#-:-NMhP9CpCH-2h9c_aVKB:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Alon-Ti and @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1920)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @Alon-Ti and @orizi)

___
*[`corelib/ecdsa.cairo` line 71 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1920#-NMhOquwCRj__YNNOXFi:-NMhR1cL2NryDriGxoia:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b4618258c4bb952abef763d0961f91d0527a5415/corelib/ecdsa.cairo#L71)):*
> ```Cairo
> 
>     let zG: Option::<EcPoint> = ec_mul(gen_point, message_hash);
>     let rQ: Option::<EcPoint> = ec_mul(public_key_point, signature_r);
> ```

Done.

**Review by Alon-Ti — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1920#-:-NMhRWJa0Q7dDX6i9y5F:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1920)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Comment by liorgold2** [comment]
Closing pull request: commit has gone away

**Pull request closed without merging**
