### PR TITLE
Fixed parsing of impl items

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2892)

### CODE REVIEW

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2892)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2892#-NTU3yhg6Zi6oM8UF-3Z:-NTU3yhg6Zi6oM8UF-3_:b-3yf84a) (no related file):*
change target branch

___

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, 11 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2892)* status: 12 of 17 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/ec.cairo` line 108 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2892#-NUHZaLqBNPXRmDQBx3I:-NUHZaLr0BmuQDGNK1-2:bcprh4p) ([raw file](https://github.com/starkware-libs/cairo/blob/425fba8abd86f04ea4c3c5af877b56ae5d61368d/corelib/src/ec.cairo#L108)):*
> ```Cairo
> }
> 
> impl EcPointAdd of Add<EcPoint> { /// Computes the sum of two points on the curve.
> ```

Fix formatting: comments and newlines

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2892)* status: 5 of 17 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`corelib/src/ec.cairo` line 108 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2892#-NUHZaLqBNPXRmDQBx3I:-NUuXCni8xgwPYtieYzT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/425fba8abd86f04ea4c3c5af877b56ae5d61368d/corelib/src/ec.cairo#L108)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Fix formatting: comments and newlines
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2892#-:-NUvAhNhDLFl3rPzEM9t:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
