### PR TITLE
Enabled inlining extern only.

### PR DESCRIPTION
**Pull request by orizi**
Currently disabled using minor hack.

commit-id:65d53a8a

---

**Stack**:
- #2086
- #2091 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/dict.cairo` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2091#-NNr-WwkEhrnMpG7oDkl:-NNr-WwkEhrnMpG7oDkm:b8sge15) ([raw file](https://github.com/starkware-libs/cairo/blob/481ce7fd79ac8063485255648ae2fc854b988cfd/corelib/dict.cairo#L32)):*
> ```Cairo
>         // TODO(ilya): Currently prevents inlining. remove after adding #[inline(never)].
>         let r = dict_felt_to_squash(self);
>         r
> ```

This result in 1 statement in lowering.

But I think it is enough to have a TODO to add #[inline(never)]



_Code quote:_
```Cairo
        // TODO(ilya): Currently prevents inlining. remove after adding #[inline(never)].
        let r = dict_felt_to_squash(self);
        r
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2091)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`corelib/dict.cairo` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2091#-NNr-WwkEhrnMpG7oDkl:-NNr14qxBBFT4FTDz08k:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/481ce7fd79ac8063485255648ae2fc854b988cfd/corelib/dict.cairo#L32)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

This result in 1 statement in lowering.

But I think it is enough to have a TODO to add #[inline(never)]
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 10 of 11 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2091#-:-NNr1GG26wssaJsjZtt-:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2091)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
