### PR TITLE
Derive StorageAccess impl for enums

### PR DESCRIPTION
**Pull request by maciejka**
Btw should it be:
`#[derive(storage_access::StorageAccess)]`
or:
`#[derive(starknet::StorageAccess)]`
or just:
`#[derive(StorageAccess)]`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3460)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3460)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @maciejka)

___
*[`crates/cairo-lang-starknet/src/plugin/mod.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3460#-N_96lC1-btIjvqts_rp:-N_96lC1-btIjvqts_rq:b-xegu2f) ([raw file](https://github.com/starkware-libs/cairo/blob/4136d61d1ffe6ebbd10e9947854a10cdaa68264e/crates/cairo-lang-starknet/src/plugin/mod.rs#L51)):*
> ```XML
>                 storage_access::handle_enum(db, enum_ast)
>             }
>             ast::Item::Enum(enum_ast) => handle_enum(db, enum_ast),
> ```

remove `use ..::handle_enum`(similar to how the struct is handled)

**Review by orizi — COMMENTED** [review]
`#[derive(starknet::StorageAccess)]` AFAIK - if it is different it is a bug.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3460#-:-N_A7wuW0l90PllD_iQ8:bx4g0lr)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @maciejka)

**Comment by maciejka** [comment]
> > Reviewed 1 of 3 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3460)_ status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @maciejka)
> 
> _[`crates/cairo-lang-starknet/src/plugin/mod.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3460#-N_96lC1-btIjvqts_rp:-N_96lC1-btIjvqts_rq:b-xegu2f) ([raw file](https://github.com/starkware-libs/cairo/blob/4136d61d1ffe6ebbd10e9947854a10cdaa68264e/crates/cairo-lang-starknet/src/plugin/mod.rs#L51)):_
> 
> > ```
> >                 storage_access::handle_enum(db, enum_ast)
> >             }
> >             ast::Item::Enum(enum_ast) => handle_enum(db, enum_ast),
> > ```
> 
> remove `use ..::handle_enum`(similar to how the struct is handled)

Fixed.

**Comment by maciejka** [comment]
> `#[derive(starknet::StorageAccess)]` AFAIK - if it is different it is a bug.
> 
> > _[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3460#-:-N_A7wuW0l90PllD_iQ8:bx4g0lr)_ status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @maciejka)

It was 'storage_access::StorageAccess', changed to 'starknet::StorageAccess'. It will break early adopters contracts who tried v2.0.0.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 10 files at r3, 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3460)* status: 6 of 10 files reviewed, 2 unresolved discussions (waiting on @maciejka)

___
*[`crates/cairo-lang-starknet/src/plugin/storage_access.rs` line 186 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3460#-N_Cppb13lvJnLKdaibd:-N_Cppb26nOQ2PwRZ8-T:b-yz91sm) ([raw file](https://github.com/starkware-libs/cairo/blob/f80795c44dc2f7d4834d196613ab6fbf3c9ad356/crates/cairo-lang-starknet/src/plugin/storage_access.rs#L186)):*
> ```XML
>                 tc.ty(db).as_syntax_node().get_text_without_trivia(db)
>             }
>         };
> ```

instead of special type handling - just add a normal impl for empty tuples StorageAccess in the corelib.



_Code quote:_
```XML
        let variant_type = match variant.type_clause(db) {
            ast::OptionTypeClause::Empty(_) => "()".to_string(),
            ast::OptionTypeClause::TypeClause(tc) => {
                tc.ty(db).as_syntax_node().get_text_without_trivia(db)
            }
        };
```
___
*[`crates/cairo-lang-starknet/src/plugin/storage_access.rs` line 290 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3460#-N_Cob2a5S-Fe5xACXy7:-N_Cob2a5S-Fe5xACXy8:b-6ym4yv) ([raw file](https://github.com/starkware-libs/cairo/blob/f80795c44dc2f7d4834d196613ab6fbf3c9ad356/crates/cairo-lang-starknet/src/plugin/storage_access.rs#L290)):*
> ```XML
>                 match value {{
>                     {match_size}
>                 }}
> ```

we are probably going to make it `size` and remove the `internal` - as well as make the function a const.

so i suggest not actually being inner value dependent:
1 + max(field1.size_internal(), max(field2.size_internal(), max(field3.size_internal(), field4.size_internal())))



_Code quote:_
```XML
            fn size_internal(value: {enum_name}) -> u8 {{
                match value {{
                    {match_size}
                }}
```

**Review by orizi — COMMENTED** [review]
i understand - but this is required.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3460#-:-N_Cxh_Y2KzUuj7UguBE:b9rkw83)* status: 6 of 10 files reviewed, 2 unresolved discussions (waiting on @maciejka)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3460)* status: 6 of 10 files reviewed, 2 unresolved discussions (waiting on @maciejka)

___
*[`crates/cairo-lang-starknet/src/plugin/storage_access.rs` line 186 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3460#-N_Cppb13lvJnLKdaibd:-N_E6sUV2rbQKOM3Te6p:b-nuxhiv) ([raw file](https://github.com/starkware-libs/cairo/blob/f80795c44dc2f7d4834d196613ab6fbf3c9ad356/crates/cairo-lang-starknet/src/plugin/storage_access.rs#L186)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

instead of special type handling - just add a normal impl for empty tuples StorageAccess in the corelib.
</blockquote></details>

automatic implementation up to size 4 now is on main.
___
*[`crates/cairo-lang-starknet/src/plugin/storage_access.rs` line 290 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3460#-N_Cob2a5S-Fe5xACXy7:-N_E6yC4Ebg1d6IvKE7k:b2tn3v8) ([raw file](https://github.com/starkware-libs/cairo/blob/f80795c44dc2f7d4834d196613ab6fbf3c9ad356/crates/cairo-lang-starknet/src/plugin/storage_access.rs#L290)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

we are probably going to make it `size` and remove the `internal` - as well as make the function a const.

so i suggest not actually being inner value dependent:
1 + max(field1.size_internal(), max(field2.size_internal(), max(field3.size_internal(), field4.size_internal())))
</blockquote></details>

this was changed in main to size.

**Comment by maciejka** [comment]
> Previously, orizi wrote…
> this was changed in main to size.

Updated implementation according to your suggestions.
Would would please share the resoning behind making `size` function a const?
Not sure why `clippy` on CI complains. Locally it works just fine.

**Review by orizi — COMMENTED** [review]
The size issue:
Assume you have a field with non const size, and after it another field: any change to the first field, may cause changes to the second one just because of offsets, where this could have been avoided.
Therefore each field should have its own span in the actual strip of 256 felts.

The clippy issue? I would assume there was some stable rust version update, will check tomorrow.

> Reviewed 3 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3460#-:-N_GWsBnABqPvMHkyhPR:bstqskq)* status: 5 of 10 files reviewed, 2 unresolved discussions (waiting on @maciejka)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3460)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @maciejka)

___
*[`crates/cairo-lang-starknet/src/plugin/storage_access.rs` line 177 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3460#-N_K97oH0lo3Cf56wBYs:-N_K97oI0keAHBNYZV7V:bw1gjqu) ([raw file](https://github.com/starkware-libs/cairo/blob/bae0d2fbc1bd3aeea1c9d996dfb7ee5644754673/crates/cairo-lang-starknet/src/plugin/storage_access.rs#L177)):*
> ```XML
> 
>         match_idx.push(format!(
>             "if idx == {i} {{ \
> ```

use formatdoc instead of all the '\'

**Comment by maciejka** [comment]
> > _[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3460)_ status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @maciejka)
> 
> _[`crates/cairo-lang-starknet/src/plugin/storage_access.rs` line 177 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3460#-N_K97oH0lo3Cf56wBYs:-N_K97oI0keAHBNYZV7V:bw1gjqu) ([raw file](https://github.com/starkware-libs/cairo/blob/bae0d2fbc1bd3aeea1c9d996dfb7ee5644754673/crates/cairo-lang-starknet/src/plugin/storage_access.rs#L177)):_
> 
> > ```
> >         match_idx.push(format!(
> >             "if idx == {i} {{ \
> > ```
> 
> use formatdoc instead of all the ''

Replaced format with formatdoc, generated code is more readble but I had to add one more depencency (indent).

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3460#-:-N_OE34z7ehpGbOAR1-4:bnfp4nl)* status: 12 of 13 files reviewed, all discussions resolved

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3460)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @maciejka)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3460#-:-N_SRapu1SJ7ODICrVwD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciejka)

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3460)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciejka)

**Pull request merged**
