### PR TITLE
Added db to profiler

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4978)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 4 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4978)* status: 5 of 10 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/cairo-lang-runner/src/profiling.rs` line 303 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4978#-Npo8QR94_IGi-2Xbu5C:-Npo8QR94_IGi-2Xbu5D:brdettz) ([raw file](https://github.com/starkware-libs/cairo/blob/7e8e965dca1babaa615fee99575e2b8f1475651a/crates/cairo-lang-runner/src/profiling.rs#L303)):*
> ```XML
>                     },
>                     |x, y| x + y,
>                     &0,
> ```

is there any difference in reality between the runs?



_Code quote:_
```XML
            let db =
                self.db.expect("DB must be set with `process_by_original_user_function=true`.");
            for (orig_name, weight) in user_functions
                .aggregate_by(
                    |idx| {
                        let lowering_function_id = db.lookup_intern_sierra_function(
                            self.sierra_program.funcs[*idx].id.clone(),
                        );
                        lowering_function_id.semantic_full_path(db.upcast())
                    },
                    |x, y| x + y,
                    &0,
```
___
*[`crates/cairo-lang-runner/src/profiling.rs` line 344 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4978#-Npo6XO11ZAg4QPKmyhj:-Npo6XO11ZAg4QPKmyhk:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/7e8e965dca1babaa615fee99575e2b8f1475651a/crates/cairo-lang-runner/src/profiling.rs#L344)):*
> ```XML
>             sierra_statements_weights,
>             stack_trace_weights,
>             // TODO(yg): separate PR: these should be none if the relevant flag is false.
> ```

?
___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 337 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4978#-Npo7s_k5sSSUZN-w23Y:-Npo7s_k5sSSUZN-w23Z:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7e8e965dca1babaa615fee99575e2b8f1475651a/crates/cairo-lang-test-runner/src/lib.rs#L337)):*
> ```XML
>             });
>     } else {
>         println!("Note: Tests don't run in parallel when running with a database.");
> ```





_Suggestion:_
```XML
        eprintln!("Note: Tests don't run in parallel when running with a database.");
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4978)* status: 5 of 10 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-runner/src/profiling.rs` line 303 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4978#-Npo8QR94_IGi-2Xbu5C:-NpoAy8F7jsAKp5IwaDK:b-7zi8tj) ([raw file](https://github.com/starkware-libs/cairo/blob/7e8e965dca1babaa615fee99575e2b8f1475651a/crates/cairo-lang-runner/src/profiling.rs#L303)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is there any difference in reality between the runs?
</blockquote></details>

WDYM?
___
*[`crates/cairo-lang-runner/src/profiling.rs` line 344 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4978#-Npo6XO11ZAg4QPKmyhj:-NpoAzrk5h6O3b_6_Bk-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7e8e965dca1babaa615fee99575e2b8f1475651a/crates/cairo-lang-runner/src/profiling.rs#L344)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 337 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4978#-Npo7s_k5sSSUZN-w23Y:-NpoB9Du7ymJ1PNuD1MF:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7e8e965dca1babaa615fee99575e2b8f1475651a/crates/cairo-lang-test-runner/src/lib.rs#L337)):*
> ```XML
>             });
>     } else {
>         println!("Note: Tests don't run in parallel when running with a database.");
> ```

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 3 of 8 files at r2, 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4978)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4978)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-runner/src/profiling.rs` line 303 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4978#-Npo8QR94_IGi-2Xbu5C:-NpoZlULDChOYcuF8-NV:blavet1) ([raw file](https://github.com/starkware-libs/cairo/blob/7e8e965dca1babaa615fee99575e2b8f1475651a/crates/cairo-lang-runner/src/profiling.rs#L303)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

on the data when using the db and when not. (no including the `expect` call)
</blockquote></details>

Still not clear to me.
You can't specify `process_by_original_user_function=true` but not set the db, as this flag's computation uses the db. If you run without a db, you must specify false for it.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4978)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/cairo-lang-runner/src/profiling.rs` line 303 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4978#-Npo8QR94_IGi-2Xbu5C:-Npoe3Kc7AxVwJFzeZp0:b-g6hvdt) ([raw file](https://github.com/starkware-libs/cairo/blob/7e8e965dca1babaa615fee99575e2b8f1475651a/crates/cairo-lang-runner/src/profiling.rs#L303)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Still not clear to me.
You can't specify `process_by_original_user_function=true` but not set the db, as this flag's computation uses the db. If you run without a db, you must specify false for it.
</blockquote></details>

the previous implementation without db - would it have ever not worked? that is my question.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4978)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-runner/src/profiling.rs` line 303 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4978#-Npo8QR94_IGi-2Xbu5C:-NpoiDnh2tSrWB3W0rB9:b-4blofh) ([raw file](https://github.com/starkware-libs/cairo/blob/7e8e965dca1babaa615fee99575e2b8f1475651a/crates/cairo-lang-runner/src/profiling.rs#L303)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the previous implementation without db - would it have ever not worked? that is my question.
</blockquote></details>

It only relied on the heuristic that generated functions are named with [expr...]. If this assumption is not true it wouldn't work.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4978#-:-NpolsPLEQGxFUI9RKww:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
