### PR TITLE
Move sierra version into program serialization.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2219)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 11 files at r1, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2219)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/src/felt_serde.rs` line 58 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2219#-NOnp0INC7AO-Zc7MHpx:-NOnp0INC7AO-Zc7MHpy:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/10a88db14f076abb560154262b1ee0fa734ead26/crates/cairo-lang-starknet/src/felt_serde.rs#L58)):*
> ```XML
> /// Deserializes a Sierra program from a slice of felts.
> pub fn sierra_from_felts(felts: &[BigIntAsHex]) -> Result<(VersionId, Program), FeltSerdeError> {
>     let (version_id, felts) = VersionId::deserialize(felts)?;
> ```





_Suggestion:_
```XML
pub fn sierra_from_felts(felts: &[BigIntAsHex]) -> Result<(VersionId, Program), FeltSerdeError> {
    let (version_id, program_part) = VersionId::deserialize(felts)?;
    Ok((version_id, Program::deserialize(program_part)?.0))
}
```
___
*[`crates/cairo-lang-starknet/src/felt_serde.rs` line 495 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2219#-NOnpKqqB1sobWRcU1SK:-NOnpKqqB1sobWRcU1SL:b-hgjqi6) ([raw file](https://github.com/starkware-libs/cairo/blob/10a88db14f076abb560154262b1ee0fa734ead26/crates/cairo-lang-starknet/src/felt_serde.rs#L495)):*
> ```XML
>     fn serialize(&self, output: &mut Vec<BigIntAsHex>) -> Result<(), FeltSerdeError> {
>         assert!(
>             self.version.len() < SHORT_STRING_BOUND,
> ```

use error - not assert.



_Code quote:_
```XML
        assert!(
            self.version.len() < SHORT_STRING_BOUND,
            "VersionId string must fit within a short string."
        );
```
___
*[`crates/cairo-lang-starknet/src/sierra_version.rs` line 8 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2219#-NOnpTSN9rpq1DmXsNyl:-NOnpTSN9rpq1DmXsNym:b-dwa4h1) ([raw file](https://github.com/starkware-libs/cairo/blob/10a88db14f076abb560154262b1ee0fa734ead26/crates/cairo-lang-starknet/src/sierra_version.rs#L8)):*
> ```XML
> impl VersionId {
>     pub fn current_version_id() -> Self {
>         Self { version: "1".into() }
> ```

let us still keep the semantics.



_Suggestion:_
```XML
    pub fn current_version_id() -> Self {
        Self { version: "0.1.0".into() }
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2219#-:-NOnt0_c4M3JKRhsc2CI:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/src/felt_serde.rs` line 43 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2219#-NOnsqOC-wP4f7tlRKqN:-NOnsqOC-wP4f7tlRKqO:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ce06a4046c18f0728039b8f74bd4680cc972979b/crates/cairo-lang-starknet/src/felt_serde.rs#L43)):*
> ```XML
>     #[error("Invalid function declaration for serialization.")]
>     FunctionArgumentsMismatchInSerialization,
>     #[error("THe sierra version is too long and can not fit with a short string.")]
> ```





_Suggestion:_
```XML
    FunctionArgumentsMismatchInSerialization,
    #[error("The sierra version is too long and can not fit within a felt.")]
    VersionIdTooLongForSerialization,
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2219)* status: 3 of 11 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/felt_serde.rs` line 58 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2219#-NOnp0INC7AO-Zc7MHpx:-NOnr2nY1_s1FZb6Q0-N:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/10a88db14f076abb560154262b1ee0fa734ead26/crates/cairo-lang-starknet/src/felt_serde.rs#L58)):*
> ```XML
> /// Deserializes a Sierra program from a slice of felts.
> pub fn sierra_from_felts(felts: &[BigIntAsHex]) -> Result<(VersionId, Program), FeltSerdeError> {
>     let (version_id, felts) = VersionId::deserialize(felts)?;
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/felt_serde.rs` line 495 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2219#-NOnpKqqB1sobWRcU1SK:-NOnr35x4vckKezRWKuN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/10a88db14f076abb560154262b1ee0fa734ead26/crates/cairo-lang-starknet/src/felt_serde.rs#L495)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

use error - not assert.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/felt_serde.rs` line 43 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2219#-NOnsqOC-wP4f7tlRKqN:-NOnvPx28faqirmm5kJX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ce06a4046c18f0728039b8f74bd4680cc972979b/crates/cairo-lang-starknet/src/felt_serde.rs#L43)):*
> ```XML
>     #[error("Invalid function declaration for serialization.")]
>     FunctionArgumentsMismatchInSerialization,
>     #[error("THe sierra version is too long and can not fit with a short string.")]
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/sierra_version.rs` line 8 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2219#-NOnpTSN9rpq1DmXsNyl:-NOnvQmj-gj2OJfkJWhm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/10a88db14f076abb560154262b1ee0fa734ead26/crates/cairo-lang-starknet/src/sierra_version.rs#L8)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

let us still keep the semantics.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2219#-:-NOnwOEy7wZQZFBsQYvJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2219)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
