### PR TITLE
Ilya/upgrade vm

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5579)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-utils/src/byte_array.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5579#-NyKWOMi1KiVd4KDZbC1:-NyKWOMi1KiVd4KDZbC2:b-l6366l) ([raw file](https://github.com/starkware-libs/cairo/blob/d85dfaacf60ec5e548fd04db60e85ec1bfec8db4/crates/cairo-lang-utils/src/byte_array.rs#L9)):*
> ```XML
> pub fn felt_from_str(val: &str, radix: u32) -> Felt252 {
>     Felt252::from(num_bigint::BigInt::from_str_radix(val, radix).expect("Couldn't parse bytes"))
> }
> ```

I added this function because without it it was unclear where to put the
`use num_traits::Num;`



_Code quote:_
```XML
pub fn felt_from_str(val: &str, radix: u32) -> Felt252 {
    Felt252::from(num_bigint::BigInt::from_str_radix(val, radix).expect("Couldn't parse bytes"))
}
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5579)* status: 0 of 36 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-utils/src/byte_array.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5579#-NyKWGsW7wGOxlwWobkS:-NyOwA9h08ocmrOrTXYK:bpvx2ne) ([raw file](https://github.com/starkware-libs/cairo/blob/d85dfaacf60ec5e548fd04db60e85ec1bfec8db4/crates/cairo-lang-utils/src/byte_array.rs#L12)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Where should I put this?

should I get rid of this macro?
</blockquote></details>

i think there's some normal macros for creating felts in the felt lib.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-utils/src/byte_array.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5579#-NyKWGsW7wGOxlwWobkS:-NyPasOb6upqnZVGwPWh:bad4ziu) ([raw file](https://github.com/starkware-libs/cairo/blob/d85dfaacf60ec5e548fd04db60e85ec1bfec8db4/crates/cairo-lang-utils/src/byte_array.rs#L12)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i think there's some normal macros for creating felts in the felt lib.
</blockquote></details>

This replaces
cairo_felt::Felt252;felt_str.

**Review by orizi — COMMENTED** [review]
> Reviewed 25 of 36 files at r1, 1 of 2 files at r2, 3 of 5 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5579)* status: all files reviewed, 8 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 186 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5579#-NyPuJQBBAMrFOIZTaes:-NyPuJQBBAMrFOIZTaet:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/e95d927931752bfcd7d50e01fd5f21bb886f4498/crates/cairo-lang-runner/src/lib.rs#L186)):*
> ```XML
>         hint_offset += instruction.body.op_size();
>     }
>     eprintln!("Hints dict: {:?}", hints_dict.keys().sorted().collect::<Vec<_>>());
> ```

.
___
*[`crates/cairo-lang-runner/src/lib.rs` line 799 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5579#-NyPuMMi-xkipgzwpaIS:-NyPuMMi-xkipgzwpaIT:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/e95d927931752bfcd7d50e01fd5f21bb886f4498/crates/cairo-lang-runner/src/lib.rs#L799)):*
> ```XML
>     let builtin_cost_segment = vm.add_memory_segment();
>     for token_type in CostTokenType::iter_precost() {
>         eprintln!("offset: {}", token_type.offset_in_builtin_costs());
> ```

.
___
*[`crates/cairo-lang-runner/src/lib.rs` line 808 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5579#-NyPuO6Q4VcKmRcXFukK:-NyPuO6Q4VcKmRcXFukL:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/e95d927931752bfcd7d50e01fd5f21bb886f4498/crates/cairo-lang-runner/src/lib.rs#L808)):*
> ```XML
> 
>     eprintln!("pc: {}", vm.get_pc());
>     eprintln!("data_len: {}", context.data_len);
> ```

.



_Code quote:_
```XML
    eprintln!("pc: {}", vm.get_pc());
    eprintln!("data_len: {}", context.data_len);
```
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 2203 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5579#-NyPuei02_NAD5LZ2KZ6:-NyPuei02_NAD5LZ2KZ7:bxntbzx) ([raw file](https://github.com/starkware-libs/cairo/blob/e95d927931752bfcd7d50e01fd5f21bb886f4498/crates/cairo-lang-runner/src/casm_run/mod.rs#L2203)):*
> ```XML
>     pub used_resources: ExecutionResources,
>     /// The runner.
>     pub runner: CairoRunner,
> ```

why not return the memory in the same way as before?



_Code quote:_
```XML
    /// The runner.
    pub runner: CairoRunner,
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs` line 221 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5579#-NyPvBO646axgsiRirtc:-NyPvBO646axgsiRirtd:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e95d927931752bfcd7d50e01fd5f21bb886f4498/crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs#L221)):*
> ```XML
>         // Note that `1/2 (mod PRIME) = (PRIME + 1) / 2 = ceil(PRIME / 2)`.
>         // Thus, `y < 1/2 (mod PRIME)` if and only if `y < PRIME / 2`.
>         &(Felt252::from(1).field_div(&NonZeroFelt::TWO)).to_biguint().to_bigint().unwrap(),
> ```





_Suggestion:_
```XML
        &(Felt252::ONE.field_div(&NonZeroFelt::TWO)).to_biguint().to_bigint().unwrap(),
```
___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 435 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5579#-NyPvV8V3NR5d9BG7bSt:-NyPvV8V3NR5d9BG7bSu:bp7qom4) ([raw file](https://github.com/starkware-libs/cairo/blob/e95d927931752bfcd7d50e01fd5f21bb886f4498/crates/cairo-lang-test-runner/src/lib.rs#L435)):*
> ```XML
> }
> 
> fn print_resource_map(m: impl ExactSizeIterator<Item = (String, usize)>, name: &str) {
> ```

move to after the using function and add doc.
___
*[`crates/cairo-lang-test-utils/src/lib.rs` line 88 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5579#-NyPvcDh4fbo_CBZ0FlT:-NyPvcDh4fbo_CBZ0FlU:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/e95d927931752bfcd7d50e01fd5f21bb886f4498/crates/cairo-lang-test-utils/src/lib.rs#L88)):*
> ```XML
> }
> 
> // TODO(ilya): Remove the following macro.
> ```

.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 2203 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5579#-NyPuei02_NAD5LZ2KZ6:-NyPwn9s7xyrD-i6f1pQ:bhsb57l) ([raw file](https://github.com/starkware-libs/cairo/blob/e95d927931752bfcd7d50e01fd5f21bb886f4498/crates/cairo-lang-runner/src/casm_run/mod.rs#L2203)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why not return the memory in the same way as before?
</blockquote></details>

it is owned by the runner, do you want to clone it?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5579)* status: 31 of 37 files reviewed, 7 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 186 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5579#-NyPuJQBBAMrFOIZTaes:-NyPyQYFEk5sK_5O2i7Q:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e95d927931752bfcd7d50e01fd5f21bb886f4498/crates/cairo-lang-runner/src/lib.rs#L186)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runner/src/lib.rs` line 799 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5579#-NyPuMMi-xkipgzwpaIS:-NyPwjiE0sgcXAwCe-sg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e95d927931752bfcd7d50e01fd5f21bb886f4498/crates/cairo-lang-runner/src/lib.rs#L799)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runner/src/lib.rs` line 808 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5579#-NyPuO6Q4VcKmRcXFukK:-NyPwk024O_qrOZ_vNxh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e95d927931752bfcd7d50e01fd5f21bb886f4498/crates/cairo-lang-runner/src/lib.rs#L808)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs` line 221 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5579#-NyPvBO646axgsiRirtc:-NyPy_XM633414sZa9yA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e95d927931752bfcd7d50e01fd5f21bb886f4498/crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs#L221)):*
> ```XML
>         // Note that `1/2 (mod PRIME) = (PRIME + 1) / 2 = ceil(PRIME / 2)`.
>         // Thus, `y < 1/2 (mod PRIME)` if and only if `y < PRIME / 2`.
>         &(Felt252::from(1).field_div(&NonZeroFelt::TWO)).to_biguint().to_bigint().unwrap(),
> ```

Done.
___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 435 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5579#-NyPvV8V3NR5d9BG7bSt:-NyPya8d7097i5ak--Eg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e95d927931752bfcd7d50e01fd5f21bb886f4498/crates/cairo-lang-test-runner/src/lib.rs#L435)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

move to after the using function and add doc.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-test-utils/src/lib.rs` line 88 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5579#-NyPvcDh4fbo_CBZ0FlT:-NyPycCD8FEPokCxU3J6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e95d927931752bfcd7d50e01fd5f21bb886f4498/crates/cairo-lang-test-utils/src/lib.rs#L88)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5579)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 2203 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5579#-NyPuei02_NAD5LZ2KZ6:-NyPzOLA9huH7ybWFOoO:bmecoa4) ([raw file](https://github.com/starkware-libs/cairo/blob/e95d927931752bfcd7d50e01fd5f21bb886f4498/crates/cairo-lang-runner/src/casm_run/mod.rs#L2203)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it is owned by the runner, do you want to clone it?
</blockquote></details>

you no longer need the runner at this point - so just move it out.
if it requires a clone - it is still an interface issue there, and no reason to make additional changes just to handle that issue.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs` line 221 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5579#-NyPvBO646axgsiRirtc:-NyPzyyw6YT9rygzqPkZ:b-r1cnvf) ([raw file](https://github.com/starkware-libs/cairo/blob/e95d927931752bfcd7d50e01fd5f21bb886f4498/crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs#L221)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`ONE` doesn't work?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs` line 221 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5579#-NyPvBO646axgsiRirtc:-NyQ-alQ71Rl5G3oYhyH:bpdrt41) ([raw file](https://github.com/starkware-libs/cairo/blob/e95d927931752bfcd7d50e01fd5f21bb886f4498/crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs#L221)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

`ONE` doesn't work?
</blockquote></details>

it caused more changes.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 2203 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5579#-NyPuei02_NAD5LZ2KZ6:-NyQ0SmYAdnhjD8906i1:bc6rscj) ([raw file](https://github.com/starkware-libs/cairo/blob/e95d927931752bfcd7d50e01fd5f21bb886f4498/crates/cairo-lang-runner/src/casm_run/mod.rs#L2203)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you no longer need the runner at this point - so just move it out.
if it requires a clone - it is still an interface issue there, and no reason to make additional changes just to handle that issue.
</blockquote></details>

I need the runner here:
https://github.com/starkware-libs/cairo/blob/ae7a63466f93d5dc7fa6abcccac605040d87be9c/crates/cairo-lang-runner/src/lib.rs#L466

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 2203 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5579#-NyPuei02_NAD5LZ2KZ6:-NyQ1rZpA_q1QdyXe0-B:bf4ua1f) ([raw file](https://github.com/starkware-libs/cairo/blob/e95d927931752bfcd7d50e01fd5f21bb886f4498/crates/cairo-lang-runner/src/casm_run/mod.rs#L2203)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I need the runner here:
https://github.com/starkware-libs/cairo/blob/ae7a63466f93d5dc7fa6abcccac605040d87be9c/crates/cairo-lang-runner/src/lib.rs#L466
</blockquote></details>

i can try moving the reloacated trace as well.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5579#-:-NyQ4FfHDJW-R8YoBGZX:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
