### PR TITLE
added semantic error for mismatch types on match with literal bool

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4651)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4651)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1261 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4651#-NmVaygr9d6RcMFWCSBs:-NmVaygr9d6RcMFWCSBt:bsq5baj) ([raw file](https://github.com/starkware-libs/cairo/blob/337360fe098fc659dd7c07279fc63717cd84501b/crates/cairo-lang-semantic/src/expr/compute.rs#L1261)):*
> ```XML
>                 ty,
>                 stable_ptr: enum_pattern.stable_ptr().into(),
>             })
> ```

extract into function and include true and false as input somehow.



_Code quote:_
```XML
            // Peel all snapshot wrappers.
            let (n_snapshots, long_ty) = peel_snapshots(ctx.db, ty);

            // Check that type is an enum, and get the concrete enum from it.
            let concrete_enum = try_extract_matches!(long_ty, TypeLongId::Concrete)
                .and_then(|c| try_extract_matches!(c, ConcreteTypeId::Enum))
                .ok_or(())
                .or_else(|_| {
                    // Don't add a diagnostic if the type is missing.
                    // A diagnostic should've already been added.
                    ty.check_not_missing(ctx.db)?;
                    Err(ctx.diagnostics.report(enum_pattern, UnexpectedEnumPattern { ty }))
                })?;

            // Extract the enum variant from the path syntax.
            let path = enum_pattern.path(syntax_db);
            let item = ctx.resolver.resolve_generic_path(
                ctx.diagnostics,
                &path,
                NotFoundItemType::Identifier,
            )?;
            let generic_variant = try_extract_matches!(item, ResolvedGenericItem::Variant)
                .ok_or_else(|| ctx.diagnostics.report(&path, NotAVariant))?;

            // Check that these are the same enums.
            if generic_variant.enum_id != concrete_enum.enum_id(ctx.db) {
                return Err(ctx.diagnostics.report(
                    &path,
                    WrongEnum {
                        expected_enum: concrete_enum.enum_id(ctx.db),
                        actual_enum: generic_variant.enum_id,
                    },
                ));
            }
            // TODO(lior): Should we report a diagnostic here?
            let concrete_variant = ctx
                .db
                .concrete_enum_variant(concrete_enum, &generic_variant)
                .map_err(|_| ctx.diagnostics.report(&path, UnknownEnum))?;

            // Compute inner pattern.
            let inner_ty = wrap_in_snapshots(ctx.db, concrete_variant.ty, n_snapshots);

            let inner_pattern = match enum_pattern.pattern(syntax_db) {
                ast::OptionPatternEnumInnerPattern::Empty(_) => None,
                ast::OptionPatternEnumInnerPattern::PatternEnumInnerPattern(p) => {
                    let pattern = compute_pattern_semantic(ctx, &p.pattern(syntax_db), inner_ty);
                    Some(pattern.id)
                }
            };

            Pattern::EnumVariant(PatternEnumVariant {
                variant: concrete_variant,
                inner_pattern,
                ty,
                stable_ptr: enum_pattern.stable_ptr().into(),
            })
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4651)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1464 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4651#-NmVhachESDsJdqJoWwI:-NmVhachESDsJdqJoWwJ:bl9168a) ([raw file](https://github.com/starkware-libs/cairo/blob/5cbfdc269b49fb766079f6778b1ed5bb1c9d63ca/crates/cairo-lang-semantic/src/expr/compute.rs#L1464)):*
> ```XML
> /// Creates a local variable pattern.
> fn create_variable_pattern(
>     ctx: &mut ComputationContext<'_>,
> ```

and doc



_Suggestion:_
```XML
        .map_err(|err| err.report(ctx.diagnostics, stable_ptr))?;
    Ok(pattern)
}

fn validate_enum_pattern_type(
    ctx: &mut ComputationContext<'_>,
    pattern: &ast::Pattern,
    ty: TypeId,
    enum_id: EnumId,
) -> Maybe<(ConcreteEnumId, usize)> {
    // Peel all snapshot wrappers.
    let (n_snapshots, long_ty) = peel_snapshots(ctx.db, ty);

    // Check that type is an enum, and get the concrete enum from it.
    let concrete_enum = try_extract_matches!(long_ty, TypeLongId::Concrete)
        .and_then(|c| try_extract_matches!(c, ConcreteTypeId::Enum))
        .ok_or(())
        .or_else(|_| {
            // Don't add a diagnostic if the type is missing.
            // A diagnostic should've already been added.
            ty.check_not_missing(ctx.db)?;
            Err(ctx.diagnostics.report(pattern, UnexpectedEnumPattern { ty }))
        })?;
    // Check that these are the same enums.
    if enum_id != concrete_enum.enum_id(ctx.db) {
        return Err(ctx.diagnostics.report(
            pattern,
            WrongEnum { expected_enum: concrete_enum.enum_id(ctx.db), actual_enum: enum_id },
        ));
    }
    Ok((concrete_enum, n_snapshots))
}

/// Creates a local variable pattern.
fn create_variable_pattern(
    ctx: &mut ComputationContext<'_>,
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4651)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1469 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4651#-NmVkcvtCgXxTEMqLzKh:-NmVkcvtCgXxTEMqLzKi:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c02f745599cfd70375976f614dd945adb9bb8901/crates/cairo-lang-semantic/src/expr/compute.rs#L1469)):*
> ```XML
> }
> /// Creates a local variable pattern.
> fn create_variable_pattern(
> ```





_Suggestion:_
```XML
    Ok((concrete_enum, n_snapshots))
}

/// Creates a local variable pattern.
fn create_variable_pattern(
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4651)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4651)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1469 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4651#-NmVkcvtCgXxTEMqLzKh:-NmVyIMZ7VjJTl7oTzfL:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c02f745599cfd70375976f614dd945adb9bb8901/crates/cairo-lang-semantic/src/expr/compute.rs#L1469)):*
> ```XML
> }
> /// Creates a local variable pattern.
> fn create_variable_pattern(
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4651#-:-NmWBRV12m1MaVK7jA9k:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
