### PR TITLE
Add Span type.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2165)

### CODE REVIEW

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2165)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2165#-NOPEs8XEoqt6BCUydmr:-NOPEs8XEoqt6BCUydms:b-empa0t) (no related file):*
Are ouy missing span.cairo?

___

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2165)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2165#-NOPEs8XEoqt6BCUydmr:-NOPLUn2-8J006vHXI5s:bb7f2mf) (no related file):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Are ouy missing span.cairo?
</blockquote></details>

done

___

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2165#-:-NOYqpNz2BX0PuRtnBvH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`corelib/span.cairo` line 4 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2165#-NOYqjI2Ds532hnogipe:-NOYqjI2Ds532hnogipf:b2jt0io) ([raw file](https://github.com/starkware-libs/cairo/blob/7ee3daa8615a98cf36c5f763c1865e5005f2154a/corelib/span.cairo#L4)):*
> ```Cairo
>     snapshot: @Array::<T>
> }
> ```

Remove extra space?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2165)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
