### PR TITLE
Added option for hex print on Debug.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4563)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4563)* status: all files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/test/fmt_test.cairo` line 74 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4563#-NlqvGDDDNqpHyvuFIMb:-NlqvGDE7r390wXFolk0:bdyfoj7) ([raw file](https://github.com/starkware-libs/cairo/blob/8ad41f8b742266f1bc612fd1370445b88c682b0a/corelib/src/test/fmt_test.cairo#L74)):*
> ```Cairo
>     assert(format!("{:x?}", 10) == "a", 'bad basic hex fmt');
>     assert(
>         format!("{:x?}", EnumExample::FeltValue(40)) == "EnumExample::FeltValue(28)",
> ```

I prefer an example with a a-f character to make it clearer



_Code quote:_
```Cairo
(28)
```
___
*[`crates/cairo-lang-semantic/src/inline_macros/write.rs` line 328 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4563#-Nlr4SMG3pUy63qMY1ak:-Nlr4SMG3pUy63qMY1al:b-2isf7l) ([raw file](https://github.com/starkware-libs/cairo/blob/8ad41f8b742266f1bc612fd1370445b88c682b0a/crates/cairo-lang-semantic/src/inline_macros/write.rs#L328)):*
> ```XML
>             builder.add_modified(RewriteNode::interpolate_patched(
>                 &format!("$f$.base = {base_change}_u8;\n"),
>                 &patches,
> ```

why not with a single interpolate_patched?



_Code quote:_
```XML
            self.add_indentation(builder, *ident_count);
            builder.add_modified(RewriteNode::interpolate_patched(
                "let __write_macro_prev_base__ = $f$.base;\n",
                &patches,
            ));
            self.add_indentation(builder, *ident_count);
            builder.add_modified(RewriteNode::interpolate_patched(
                &format!("$f$.base = {base_change}_u8;\n"),
                &patches,
```
___
*[`crates/cairo-lang-semantic/src/inline_macros/write.rs` line 338 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4563#-Nlr2TQ_08MJQZWAvnxX:-Nlr2TQ_08MJQZWAvnxY:b-3el3gm) ([raw file](https://github.com/starkware-libs/cairo/blob/8ad41f8b742266f1bc612fd1370445b88c682b0a/crates/cairo-lang-semantic/src/inline_macros/write.rs#L338)):*
> ```XML
>         *ident_count += 1;
>         self.add_indentation(builder, *ident_count);
>         builder.add_str("core::result::Result::Ok(_) => {\n");
> ```

1. where is the closing }?
2. Why not in a single interpolate_patched?
3. It's really hard to review without an expansion test, I think we need to make it work before submitting this PR or any other formatting PR.



_Code quote:_
```XML
 {\n");
```
___
*[`crates/cairo-lang-semantic/src/inline_macros/write.rs` line 346 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4563#-Nlr3MZF1igTYq37wN8B:-Nlr3MZF1igTYq37wN8C:b-p2w505) ([raw file](https://github.com/starkware-libs/cairo/blob/8ad41f8b742266f1bc612fd1370445b88c682b0a/crates/cairo-lang-semantic/src/inline_macros/write.rs#L346)):*
> ```XML
>                 &patches,
>             ));
>         }
> ```

I don't like the use of all patches even when they aren't needed.



_Suggestion:_
```XML
        let arg_patch = ("arg".to_string(), arg);
        let formatter_patch = ("f".to_string(), self.formatter_arg_node.clone());
        let patches =
            [("arg".to_string(), arg), ("f".to_string(), self.formatter_arg_node.clone())].into();
        self.flush_pending_chars(builder, pending_chars, *ident_count);
        if let Some(base_change) = fmt_type.base_change() {
            self.add_indentation(builder, *ident_count);
            builder.add_modified(RewriteNode::interpolate_patched(
                "let __write_macro_prev_base__ = $f$.base;\n",
                &[formatter_patch].into(),
            ));
            self.add_indentation(builder, *ident_count);
            builder.add_modified(RewriteNode::interpolate_patched(
                &format!("$f$.base = {base_change}_u8;\n"),
                &[formatter_patch].into(),
            ));
        }
        self.add_indentation(builder, *ident_count);
        builder.add_modified(RewriteNode::interpolate_patched(
            &format!("match core::fmt::{}::fmt($arg$, ref $f$) {{\n", fmt_type.trait_name()),
            &[arg_pathc, formatter_patch].into(),
        ));
        *ident_count += 1;
        self.add_indentation(builder, *ident_count);
        builder.add_str("core::result::Result::Ok(_) => {\n");
        *ident_count += 1;
        if fmt_type.base_change().is_some() {
            self.add_indentation(builder, *ident_count);
            builder.add_modified(RewriteNode::interpolate_patched(
                "$f$.base = __write_macro_prev_base__;\n",
                &[formatter_patch].into(),
            ));
        }
```
___
*[`crates/cairo-lang-semantic/src/inline_macros/write.rs` line 391 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4563#-Nlr02Eu08htW94sE_tW:-Nlr02Eu08htW94sE_tX:brpl4rn) ([raw file](https://github.com/starkware-libs/cairo/blob/8ad41f8b742266f1bc612fd1370445b88c682b0a/crates/cairo-lang-semantic/src/inline_macros/write.rs#L391)):*
> ```XML
> 
> /// The format type to use.
> enum FormatType {
> ```

Maybe the name should now change to Format{Indicator,Details,Config,something of the spirit}?



_Code quote:_
```XML
num FormatType {
```

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4563)* status: all files reviewed, 5 unresolved discussions (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4563)* status: all files reviewed, 5 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/inline_macros/write.rs` line 338 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4563#-Nlr2TQ_08MJQZWAvnxX:-NlsHD8F4WZW9THKgLVC:bm3be2d) ([raw file](https://github.com/starkware-libs/cairo/blob/8ad41f8b742266f1bc612fd1370445b88c682b0a/crates/cairo-lang-semantic/src/inline_macros/write.rs#L338)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

1. where is the closing }?
2. Why not in a single interpolate_patched?
3. It's really hard to review without an expansion test, I think we need to make it work before submitting this PR or any other formatting PR.
</blockquote></details>

1. in the closer - the generated code is of the format:
```
match fmt_expr1 {
    Ok(()) => match fmt_expr2 {
       Ok(()) => match fmt_expr3 {
          Ok(()) => Ok(()),
          Err(_) => Err(Error {}),
       },
    Err(_) => Err(Error {}),
}
```
2. Unrelated to this PR - feel free to refactor - but i dont see this making this any more readable.
3. The testing (as they are for macros in rust) are through usage - as expansion is rather problematic to implement.
___
*[`crates/cairo-lang-semantic/src/inline_macros/write.rs` line 346 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4563#-Nlr3MZF1igTYq37wN8B:-NlsI9Ce3JTkqwg9ueVi:blx3ljt) ([raw file](https://github.com/starkware-libs/cairo/blob/8ad41f8b742266f1bc612fd1370445b88c682b0a/crates/cairo-lang-semantic/src/inline_macros/write.rs#L346)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I don't like the use of all patches even when they aren't needed.
</blockquote></details>

i don't like creating the same map 4 times.
___
*[`crates/cairo-lang-semantic/src/inline_macros/write.rs` line 391 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4563#-Nlr02Eu08htW94sE_tW:-NlsIIXP-7fc7dEKste0:bbx2gin) ([raw file](https://github.com/starkware-libs/cairo/blob/8ad41f8b742266f1bc612fd1370445b88c682b0a/crates/cairo-lang-semantic/src/inline_macros/write.rs#L391)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Maybe the name should now change to Format{Indicator,Details,Config,something of the spirit}?
</blockquote></details>

Maybe it should - but that refactor should probably come with before additional features.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4563)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/test/fmt_test.cairo` line 74 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4563#-NlqvGDDDNqpHyvuFIMb:-NlsJ-IQ6YZzv5mGGFeJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8ad41f8b742266f1bc612fd1370445b88c682b0a/corelib/src/test/fmt_test.cairo#L74)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I prefer an example with a a-f character to make it clearer
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/inline_macros/write.rs` line 328 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4563#-Nlr4SMG3pUy63qMY1ak:-NlsJ1wf3nCxy85gveii:b-g582w2) ([raw file](https://github.com/starkware-libs/cairo/blob/8ad41f8b742266f1bc612fd1370445b88c682b0a/crates/cairo-lang-semantic/src/inline_macros/write.rs#L328)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

why not with a single interpolate_patched?
</blockquote></details>

how would you do the indentation part otherwise?

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4563)* status: all files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/inline_macros/write.rs` line 328 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4563#-Nlr4SMG3pUy63qMY1ak:-Nlwsg6H72L1EKVhTmLF:b3fkieb) ([raw file](https://github.com/starkware-libs/cairo/blob/8ad41f8b742266f1bc612fd1370445b88c682b0a/crates/cairo-lang-semantic/src/inline_macros/write.rs#L328)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

how would you do the indentation part otherwise?
</blockquote></details>

With indoc/formatdoc as in other macros. Or am I missing something?
Anyway it's hard to review without an expansion test (as said in another comment, so let's keep the discussion there).
___
*[`crates/cairo-lang-semantic/src/inline_macros/write.rs` line 338 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4563#-Nlr2TQ_08MJQZWAvnxX:-NlwtW1d0MoTbjEdn3vp:bqoz4e6) ([raw file](https://github.com/starkware-libs/cairo/blob/8ad41f8b742266f1bc612fd1370445b88c682b0a/crates/cairo-lang-semantic/src/inline_macros/write.rs#L338)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

1. in the closer - the generated code is of the format:
```
match fmt_expr1 {
    Ok(()) => match fmt_expr2 {
       Ok(()) => match fmt_expr3 {
          Ok(()) => Ok(()),
          Err(_) => Err(Error {}),
       },
    Err(_) => Err(Error {}),
}
```
2. Unrelated to this PR - feel free to refactor - but i dont see this making this any more readable.
3. The testing (as they are for macros in rust) are through usage - as expansion is rather problematic to implement.
</blockquote></details>

1. Hmm this is hard to read. Also, the doc for this function is not accurate in that regard: it should say something like:
"This includes opening a new match and a OK arm within it, both are only closed at the end of the whole macro handling."
3. why is it problematic to impl? Isn't it similar to the expansion test for non-inline macros we have? Also - while we don't have it, indentation is not important, is it?
___
*[`crates/cairo-lang-semantic/src/inline_macros/write.rs` line 346 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4563#-Nlr3MZF1igTYq37wN8B:-NlwwDLx767pO-5aOjX-:b-fddqsr) ([raw file](https://github.com/starkware-libs/cairo/blob/8ad41f8b742266f1bc612fd1370445b88c682b0a/crates/cairo-lang-semantic/src/inline_macros/write.rs#L346)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i don't like creating the same map 4 times.
</blockquote></details>

Adding a new suggestion in a separate comment.
___
*[`crates/cairo-lang-semantic/src/inline_macros/write.rs` line 391 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4563#-Nlr02Eu08htW94sE_tW:-NlwsPYj3Grq-DFUzVTK:b-krz0el) ([raw file](https://github.com/starkware-libs/cairo/blob/8ad41f8b742266f1bc612fd1370445b88c682b0a/crates/cairo-lang-semantic/src/inline_macros/write.rs#L391)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Maybe it should - but that refactor should probably come with before additional features.
</blockquote></details>

I changed it in my PR to FormattingTrait, the name Rust uses. We can consider FormattingSpec as it contains more details, but the main branch is the trait itself.
___
*[`crates/cairo-lang-semantic/src/inline_macros/write.rs` line 341 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4563#-NlwwQdI5n6xzFdR_REU:-NlwwQdI5n6xzFdR_REV:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/afe427ebe12d747cbf73e6b73d930043eb98159e/crates/cairo-lang-semantic/src/inline_macros/write.rs#L341)):*
> ```XML
>                 &patches,
>             ));
>         }
> ```





_Suggestion:_
```XML
        let arg_patch = ("arg".to_string(), arg);
        let formatter_patch = ("f".to_string(), self.formatter_arg_node.clone());
        let formatter_patch_map = [formatter_patch].into();
        self.flush_pending_chars(builder, pending_chars, *ident_count);
        if let Some(base_change) = fmt_type.base_change() {
            self.add_indentation(builder, *ident_count);
            builder.add_modified(RewriteNode::interpolate_patched(
                "let __write_macro_prev_base__ = $f$.base;\n",
                &formatter_patch_map,
            ));
            self.add_indentation(builder, *ident_count);
            builder.add_modified(RewriteNode::interpolate_patched(
                &format!("$f$.base = {base_change}_u8;\n"),
                &formatter_patch_map,
            ));
        }
        self.add_indentation(builder, *ident_count);
        builder.add_modified(RewriteNode::interpolate_patched(
            &format!("match core::fmt::{}::fmt($arg$, ref $f$) {{\n", fmt_type.trait_name()),
            &[arg_patch, formatter_patch].into(),
        ));
        *ident_count += 1;
        self.add_indentation(builder, *ident_count);
        builder.add_str("core::result::Result::Ok(_) => {\n");
        *ident_count += 1;
        if fmt_type.base_change().is_some() {
            self.add_indentation(builder, *ident_count);
            builder.add_modified(RewriteNode::interpolate_patched(
                "$f$.base = __write_macro_prev_base__;\n",
                &formatter_patch_map,
            ));
        }
```

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4563)* status: all files reviewed, 5 unresolved discussions (waiting on @orizi)

**Pull request closed without merging**
