### PR TITLE
keccak for any size in bytes

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3508)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/keccak.cairo` line 92 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3508#-NYqtUlC0UvEmAfUo0lf:-NYqtUlC0UvEmAfUo0lg:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5e56ecaa09ad5b523e225b23184421660c40f1c5/corelib/src/keccak.cairo#L92)):*
> ```Cairo
> //   560229490 == int.from_bytes(b'rld!', 'little')
> //
> // Returns the hash as a u256.
> ```





_Suggestion:_
```Cairo
// Returns the hash as a little endian u256.
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3508)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/keccak.cairo` line 6 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3508#-NYquDjS7NF8BUB2K6F_:-NYquDjS7NF8BUB2K6Fa:b4fgmpz) ([raw file](https://github.com/starkware-libs/cairo/blob/bc3b5e825e5c131e45115c4f7f62fbe1f19a33ec/corelib/src/keccak.cairo#L6)):*
> ```Cairo
> use starknet::SyscallResultTrait;
> 
> const KECCAK_FULL_RATE_IN_U64S: usize = 17;
> ```

why did you rename it?

word is ambigious.



_Code quote:_
```Cairo
KECCAK_FULL_RATE_IN_U64S
```

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/keccak.cairo` line 135 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3508#-NYqubkq4lwV4wXhtmwi:-NYqubkq4lwV4wXhtmwj:bacg5lm) ([raw file](https://github.com/starkware-libs/cairo/blob/5e56ecaa09ad5b523e225b23184421660c40f1c5/corelib/src/keccak.cairo#L135)):*
> ```Cairo
>         1
>     } else if last_input_num_bytes == 1 {
>         0x100 + (last_input_word & 0x77)
> ```

why 0x77?



_Suggestion:_
```Cairo
last_input_word & 0xff
```

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/keccak.cairo` line 126 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3508#-NYquoCr-Y02FUfn-rrZ:-NYquoCr-Y02FUfn-rr_:bckafl7) ([raw file](https://github.com/starkware-libs/cairo/blob/5e56ecaa09ad5b523e225b23184421660c40f1c5/corelib/src/keccak.cairo#L126)):*
> ```Cairo
>         } else {
>             panic_with_felt252('Keccak last input word >7b')
>         };
> ```

why not
0x8000000000000000 + the result of the if chain below?



_Code quote:_
```Cairo
        let word_to_append = if last_input_num_bytes == 0 {
            0x8000000000000001
        } else if last_input_num_bytes == 1 {
            0x8000000000000100 + (last_input_word & 0x77)
        } else if last_input_num_bytes == 2 {
            0x8000000000010000 + (last_input_word & 0x7777)
        } else if last_input_num_bytes == 3 {
            0x8000000001000000 + (last_input_word & 0x777777)
        } else if last_input_num_bytes == 4 {
            0x8000000100000000 + (last_input_word & 0x77777777)
        } else if last_input_num_bytes == 5 {
            0x8000010000000000 + (last_input_word & 0x7777777777)
        } else if last_input_num_bytes == 6 {
            0x8001000000000000 + (last_input_word & 0x777777777777)
        } else if last_input_num_bytes == 7 {
            0x8100000000000000 + (last_input_word & 0x77777777777777)
        } else {
            panic_with_felt252('Keccak last input word >7b')
        };
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3508)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/keccak.cairo` line 6 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3508#-NYquDjS7NF8BUB2K6F_:-NYqxAk7DIUt2Cr0Hy2J:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bc3b5e825e5c131e45115c4f7f62fbe1f19a33ec/corelib/src/keccak.cairo#L6)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why did you rename it?

word is ambigious.
</blockquote></details>

Done.
___
*[`corelib/src/keccak.cairo` line 92 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3508#-NYqtUlC0UvEmAfUo0lf:-NYqxZZn8dY-KWdBh2ZR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5e56ecaa09ad5b523e225b23184421660c40f1c5/corelib/src/keccak.cairo#L92)):*
> ```Cairo
> //   560229490 == int.from_bytes(b'rld!', 'little')
> //
> // Returns the hash as a u256.
> ```

Done.
___
*[`corelib/src/keccak.cairo` line 126 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3508#-NYquoCr-Y02FUfn-rrZ:-NYqxtq3BsnqSId-kwvk:b-x2d1jp) ([raw file](https://github.com/starkware-libs/cairo/blob/5e56ecaa09ad5b523e225b23184421660c40f1c5/corelib/src/keccak.cairo#L126)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why not
0x8000000000000000 + the result of the if chain below?
</blockquote></details>

To avoid the runtime addition of constants in the common case. Do you think it's not worth it?
___
*[`corelib/src/keccak.cairo` line 135 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3508#-NYqubkq4lwV4wXhtmwi:-NYqyL-h-ONe8ORZub1L:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5e56ecaa09ad5b523e225b23184421660c40f1c5/corelib/src/keccak.cairo#L135)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why 0x77?
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/keccak.cairo` line 126 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3508#-NYquoCr-Y02FUfn-rrZ:-NYr5-Z9CMKJ6_BS5szI:b4whgmo) ([raw file](https://github.com/starkware-libs/cairo/blob/5e56ecaa09ad5b523e225b23184421660c40f1c5/corelib/src/keccak.cairo#L126)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

To avoid the runtime addition of constants in the common case. Do you think it's not worth it?
</blockquote></details>

yes, there is also a cost for code size.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3508)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`corelib/src/keccak.cairo` line 92 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3508#-NYqtUlC0UvEmAfUo0lf:-NYr5BS4DI5Q252v2Wcw:b-gp4kzn) ([raw file](https://github.com/starkware-libs/cairo/blob/5e56ecaa09ad5b523e225b23184421660c40f1c5/corelib/src/keccak.cairo#L92)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Done.
</blockquote></details>

btw, why not implement pow?

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3508)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/keccak.cairo` line 92 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3508#-NYqtUlC0UvEmAfUo0lf:-NYrOyBC7lnDoVW-mJUU:b-uthluh) ([raw file](https://github.com/starkware-libs/cairo/blob/5e56ecaa09ad5b523e225b23184421660c40f1c5/corelib/src/keccak.cairo#L92)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

btw, why not implement pow?
</blockquote></details>

again, efficiency.
We can consider it later and add it here if we think it's beneficial.
___
*[`corelib/src/keccak.cairo` line 126 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3508#-NYquoCr-Y02FUfn-rrZ:-NYrOrssBuVLoPJy_H2l:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5e56ecaa09ad5b523e225b23184421660c40f1c5/corelib/src/keccak.cairo#L126)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

yes, there is also a cost for code size.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3508)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`corelib/src/keccak.cairo` line 125 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3508#-NYrUG-o6WaQP27b0hBL:-NYrUG-o6WaQP27b0hBM:bqppxt9) ([raw file](https://github.com/starkware-libs/cairo/blob/d5499e2146c3fa1d40342fed75552a4e5f98aa0c/corelib/src/keccak.cairo#L125)):*
> ```Cairo
>     } else {
>         panic_with_felt252('Keccak last input word >7b')
>     };
> ```

maybe

let next_bit = ...

if last_input_word >= next_bit {
    panic_with_felt252('Invalid input')
}

let first_word_to_append = next_bit + last_input_word;



_Suggestion:_
```Cairo
    let first_word_to_append = if last_input_num_bytes == 0 {
        1
    } else if last_input_num_bytes == 1 {
        0x100 + (last_input_word & 0xff)
    } else if last_input_num_bytes == 2 {
        0x10000 + (last_input_word & 0xffff)
    } else if last_input_num_bytes == 3 {
        0x1000000 + (last_input_word & 0xffffff)
    } else if last_input_num_bytes == 4 {
        0x100000000 + (last_input_word & 0xffffffff)
    } else if last_input_num_bytes == 5 {
        0x10000000000 + (last_input_word & 0xffffffffff)
    } else if last_input_num_bytes == 6 {
        0x1000000000000 + (last_input_word & 0xffffffffffff)
    } else if last_input_num_bytes == 7 {
        0x100000000000000 + (last_input_word & 0xffffffffffffff)
    } else {
        panic_with_felt252('Keccak last input word >7b')
    };
    
    
```

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/keccak.cairo` line 125 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3508#-NYrUG-o6WaQP27b0hBL:-NYrYWEs2am_npRUfMRK:bs61zwh) ([raw file](https://github.com/starkware-libs/cairo/blob/d5499e2146c3fa1d40342fed75552a4e5f98aa0c/corelib/src/keccak.cairo#L125)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

maybe

let next_bit = ...

if last_input_word >= next_bit {
    panic_with_felt252('Invalid input')
}

let first_word_to_append = next_bit + last_input_word;


</blockquote></details>

actually, I think you can just divide by next_bit.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3508)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/keccak.cairo` line 125 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3508#-NYrUG-o6WaQP27b0hBL:-NYrdHnUDotrYuoL3Y9N:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d5499e2146c3fa1d40342fed75552a4e5f98aa0c/corelib/src/keccak.cairo#L125)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

actually, I think you can just divide by next_bit.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3508)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`corelib/src/keccak.cairo` line 112 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3508#-NYrf0sD5UdrVMEYECwf:-NYrf0sD5UdrVMEYECwg:b-26ms6c) ([raw file](https://github.com/starkware-libs/cairo/blob/6b2836dfeb4b1dcb1eda8df00dfe47c5a5d2301b/corelib/src/keccak.cairo#L112)):*
> ```Cairo
>     //     0x1000000 + (last_input_word & 0xffffff)
>     let first_word_to_append = if last_input_num_bytes == 0 {
>         // This is the common case. It is handled separately to avoid the unnecessary division by 1.
> ```

How do you know that this is the common case?

I suggest removing this from the comment.



_Code quote:_
```Cairo
This is the common case.
```

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3508#-:-NYrh-mu78DomAxWoSth:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @yuvalsw)

**Comment by feltroidprime** [comment]
thanks <3

**Pull request merged**
