### PR TITLE
LS: Fix multiline strings highlighting

### PR DESCRIPTION
**Pull request by Draggu**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6088)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6088)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Draggu and @mkaput)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6088#-O2y-DUK35OP5AyEmdpo:-O2y-DUK35OP5AyEmdpp:b8mxdmb) (no related file):*
please add a previously failing test.

___

**Review by Draggu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6088)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @mkaput and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6088#-O2y-DUK35OP5AyEmdpo:-O2yEgdpCfMJ7Vu_cluD:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

please add a previously failing test.
</blockquote></details>

Done.

___

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6088)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @Draggu and @mkaput)

___
*[`crates/cairo-lang-language-server/src/ide/semantic_highlighting/mod.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6088#-O2yIpcA6_lOu0M7HQKE:-O2yIpcA6_lOu0M7HQKF:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/877f40663084504d584463517ad9909d0dc99c38/crates/cairo-lang-language-server/src/ide/semantic_highlighting/mod.rs#L92)):*
> ```XML
>                                 let mut lines = text.split("\n").peekable();
> 
>                                 // split string into multiple single line tokens
> ```





_Suggestion:_
```XML
                                };

                                // Not using `.lines()` since constant length new line separator is required.
                                let mut lines = text.split("\n").peekable();

                                // Split string into multiple single line tokens.
```
___
*[`crates/cairo-lang-language-server/tests/e2e/semantic_tokens.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6088#-O2yISZO6kRGUOARfAjN:-O2yISZO6kRGUOARfAjO:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/877f40663084504d584463517ad9909d0dc99c38/crates/cairo-lang-language-server/tests/e2e/semantic_tokens.rs#L62)):*
> ```XML
> 
>     // there is multiline (2) string
>     // check if 2 consecutive tokens are of type string
> ```





_Suggestion:_
```XML
    // There is a multiline (2) string, check if 2 consecutive tokens are of type string.
```

**Review by Draggu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6088)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-language-server/src/ide/semantic_highlighting/mod.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6088#-O2yIpcA6_lOu0M7HQKE:-O2yVDtX9BBqM0RiWqKh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/877f40663084504d584463517ad9909d0dc99c38/crates/cairo-lang-language-server/src/ide/semantic_highlighting/mod.rs#L92)):*
> ```XML
>                                 let mut lines = text.split("\n").peekable();
> 
>                                 // split string into multiple single line tokens
> ```

Done.
___
*[`crates/cairo-lang-language-server/tests/e2e/semantic_tokens.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6088#-O2yISZO6kRGUOARfAjN:-O2yVEjM1gXQGjR0XGi5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/877f40663084504d584463517ad9909d0dc99c38/crates/cairo-lang-language-server/tests/e2e/semantic_tokens.rs#L62)):*
> ```XML
> 
>     // there is multiline (2) string
>     // check if 2 consecutive tokens are of type string
> ```

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6088)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @mkaput)

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6088)* status: all files reviewed, 2 unresolved discussions (waiting on @Draggu)

___
*[`crates/cairo-lang-language-server/src/ide/semantic_highlighting/mod.rs` line 8 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6088#-O3ClLMJ9NK2zWSlWeLT:-O3ClLMJ9NK2zWSlWeLU:b42jqtw) ([raw file](https://github.com/starkware-libs/cairo/blob/81bccff9735f2f1f75b10ba24e01f829d90bdcca/crates/cairo-lang-language-server/src/ide/semantic_highlighting/mod.rs#L8)):*
> ```XML
> use cairo_lang_utils::unordered_hash_map::UnorderedHashMap;
> use cairo_lang_utils::Upcast;
> use token_kind::MultilineSemanticTokenKind;
> ```

+ sort imports after this change



_Suggestion:_
```XML
use self::token_kind::MultilineSemanticTokenKind;
```
___
*[`crates/cairo-lang-language-server/tests/e2e/semantic_tokens.rs` line 38 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6088#-O3ClVvVBosOO3ngXMrm:-O3ClVvVBosOO3ngXMrn:bl8qd3f) ([raw file](https://github.com/starkware-libs/cairo/blob/81bccff9735f2f1f75b10ba24e01f829d90bdcca/crates/cairo-lang-language-server/tests/e2e/semantic_tokens.rs#L38)):*
> ```XML
>             "src/lib.cairo" => r#"
> fn main() {
>     let _ = "
> ```

please make this a separate test that explicitly checks multiline tokens

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6088)* status: all files reviewed, 3 unresolved discussions (waiting on @Draggu)

___
*[`crates/cairo-lang-language-server/src/ide/semantic_highlighting/mod.rs` line 76 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6088#-O3DQSpzEimivyPevXA0:-O3DQSpzEimivyPevXA1:bv0nkmx) ([raw file](https://github.com/starkware-libs/cairo/blob/81bccff9735f2f1f75b10ba24e01f829d90bdcca/crates/cairo-lang-language-server/src/ide/semantic_highlighting/mod.rs#L76)):*
> ```XML
>                     if let Some(multiline_token) = semantic_kind.as_multiline_token() {
>                         match multiline_token {
>                             MultilineSemanticTokenKind::String => {
> ```

I doubt this logic would differ depending on token kind. For example, multiline block comments would work identically (if they have existed).

Can't you just detect if a token spans multiple lines and chop it here, regardless of what kind it is? You should be able to just look at TextSpan of the token first, without having to search for `\n` (which definitely is more expensive).

**Review by Draggu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6088)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-language-server/src/ide/semantic_highlighting/mod.rs` line 8 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6088#-O3ClLMJ9NK2zWSlWeLT:-O3IN-uo76TPP1fF4Ooi:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/81bccff9735f2f1f75b10ba24e01f829d90bdcca/crates/cairo-lang-language-server/src/ide/semantic_highlighting/mod.rs#L8)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

+ sort imports after this change
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/ide/semantic_highlighting/mod.rs` line 76 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6088#-O3DQSpzEimivyPevXA0:-O3IMtmeBvK09_D6qkZf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/81bccff9735f2f1f75b10ba24e01f829d90bdcca/crates/cairo-lang-language-server/src/ide/semantic_highlighting/mod.rs#L76)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I doubt this logic would differ depending on token kind. For example, multiline block comments would work identically (if they have existed).

Can't you just detect if a token spans multiple lines and chop it here, regardless of what kind it is? You should be able to just look at TextSpan of the token first, without having to search for `\n` (which definitely is more expensive).
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/tests/e2e/semantic_tokens.rs` line 38 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6088#-O3ClVvVBosOO3ngXMrm:-O3IMqii03YwNFhbjPJU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/81bccff9735f2f1f75b10ba24e01f829d90bdcca/crates/cairo-lang-language-server/tests/e2e/semantic_tokens.rs#L38)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

please make this a separate test that explicitly checks multiline tokens
</blockquote></details>

Done.

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6088)* status: all files reviewed, 3 unresolved discussions (waiting on @Draggu)

___
*[`crates/cairo-lang-language-server/src/ide/semantic_highlighting/mod.rs` line 74 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6088#-O3IUlK4AT9R3dYwB21R:-O3IUlK53msBsO1NcPGq:bf7zsuq) ([raw file](https://github.com/starkware-libs/cairo/blob/4d8a2e7dc559cd06caabf4994051aa67ad7c8352/crates/cairo-lang-language-server/src/ide/semantic_highlighting/mod.rs#L74)):*
> ```XML
> 
>                 if let Some(semantic_kind) = maybe_semantic_kind {
>                     let text = node.get_text(db);
> ```

We are in the `GreenNodeDetails::Token` branch, so the `.text()` method is guaranteed to always return `Some(SmolStr)`, and `.text` is way much faster (just an Arc clone at worst) than `get_text` (whole tree traversal which allocate and join strings).

Mind that we are on a hot path here after all.



_Suggestion:_
```XML
let Some(text) = node.text(db) else { unreachable!() };
```
___
*[`crates/cairo-lang-language-server/src/ide/semantic_highlighting/mod.rs` line 76 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6088#-O3IVSJe28sCIxA8VSK3:-O3IVSJf0g0i7Mxl8yZi:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/4d8a2e7dc559cd06caabf4994051aa67ad7c8352/crates/cairo-lang-language-server/src/ide/semantic_highlighting/mod.rs#L76)):*
> ```XML
>                     let text = node.get_text(db);
> 
>                     if text.lines().take(2).count() > 1 {
> ```





_Suggestion:_
```XML
if text.contains('\n') {
```
___
*[`crates/cairo-lang-language-server/src/ide/semantic_highlighting/mod.rs` line 93 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6088#-O3IXPTj66uMnvWTBbY9:-O3IXPTj66uMnvWTBbYA:b-7hbpla) ([raw file](https://github.com/starkware-libs/cairo/blob/4d8a2e7dc559cd06caabf4994051aa67ad7c8352/crates/cairo-lang-language-server/src/ide/semantic_highlighting/mod.rs#L93)):*
> ```XML
>                                 self.encoder.next_line();
>                             }
>                         }
> ```

wdyt?



_Suggestion:_
```XML
                        // Split multiline token into multiple single line tokens.
                        for line in text.split_inclusive('\n') {
                            self.push_semantic_token(line.len() as u32, &semantic_kind, data);
                            
                            if line.ends_with('\n') {
                                self.encoder.next_line();
                            }
                        }
```

**Review by Draggu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6088)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @mkaput)

___
*[`crates/cairo-lang-language-server/src/ide/semantic_highlighting/mod.rs` line 74 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6088#-O3IUlK4AT9R3dYwB21R:-O3XS55n3RQ-jG87DDY-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4d8a2e7dc559cd06caabf4994051aa67ad7c8352/crates/cairo-lang-language-server/src/ide/semantic_highlighting/mod.rs#L74)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

We are in the `GreenNodeDetails::Token` branch, so the `.text()` method is guaranteed to always return `Some(SmolStr)`, and `.text` is way much faster (just an Arc clone at worst) than `get_text` (whole tree traversal which allocate and join strings).

Mind that we are on a hot path here after all.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/ide/semantic_highlighting/mod.rs` line 76 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6088#-O3IVSJe28sCIxA8VSK3:-O3XS4yq-Kum_xs--YOx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4d8a2e7dc559cd06caabf4994051aa67ad7c8352/crates/cairo-lang-language-server/src/ide/semantic_highlighting/mod.rs#L76)):*
> ```XML
>                     let text = node.get_text(db);
> 
>                     if text.lines().take(2).count() > 1 {
> ```

Done.
___
*[`crates/cairo-lang-language-server/src/ide/semantic_highlighting/mod.rs` line 93 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6088#-O3IXPTj66uMnvWTBbY9:-O3XS4UC-fTskbHalkZy:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4d8a2e7dc559cd06caabf4994051aa67ad7c8352/crates/cairo-lang-language-server/src/ide/semantic_highlighting/mod.rs#L93)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

wdyt?
</blockquote></details>

Done.

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6088#-:-O3XZsCKBXWdbmpr9y6P:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Draggu)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6088#-:-O3lIRn30v7x9KSNoN1J:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Draggu)

**Pull request merged**
