### PR TITLE
Fix #2116

### LINKED ISSUE #2116: bug: event emit gives `error: Variable was previously moved.`
# Bug Report

**Cairo version:**

`b51c511ab39dae631362d4157853db46c2c49d64`

**Current behavior:**

emitting the following event:

```
    #[event]
    fn ComponentValueSet(component_id: felt, entity_id: felt, data: Array::<felt>) {}

    ...

    #[external]
    fn on_component_set(entity_id: felt, data: Array::<felt>) {
        ComponentValueSet(caller_address_felt, entity_id, data);
    }
```

results in the error

```
error: Variable was previously moved.
 --> contract:143:9
        serde::Serde::<felt>::serialize(ref data, entity_id);
        ^**************************************************^
```

compiled contract looks like:

```
    #[event]
    fn ComponentValueSet(component_id: felt, entity_id: felt, data: Array::<felt>) {
        let mut keys = array_new();
        array_append(ref keys, 0x20427dbf22fa80ffee4e42a5864b7fd37b9f906cc4db230d084faa3a0ce558f);
        let mut data = array_new();
        serde::Serde::<felt>::serialize(ref data, component_id);
        serde::Serde::<felt>::serialize(ref data, entity_id);
        serde::Serde::<Array::<felt>>::serialize(ref data, data);
        
        starknet::emit_event_syscall(keys, data).unwrap_syscall()
    }
```

image

full repo at: https://github.com/dojoengine/dojo/pull/51

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2119)

### CODE REVIEW

**Review by yuvalsw — COMMENTED** [review]
LGTM, but what is 2116? Seems like it was deleted?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2119#-:-NOEEvrI-7yFwFHOg9om:bra8a7v)* status: 0 of 2 files reviewed, all discussions resolved

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2119#-:-NOEF47Z-kxioN3i1TqL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
The link works for me, why are you saying it was deleted?

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2119#-:-NOElC7yD79PChr_Ttw2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2119)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
