### PR TITLE
Constant cost entrypoints

### PR DESCRIPTION
**Pull request by spapinistarkware**
commit-id:5b544a03

---

**Stack**:
- #1880
- #1874 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1874)* status: 4 of 11 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1874#-NMXudHiDWrISQ4aKTHo:-NMXudHiDWrISQ4aKTHp:bdhqgv4) ([raw file](https://github.com/starkware-libs/cairo/blob/79444c21aae2fd11509745c2623085eacc56d79a/crates/cairo-lang-sierra-gas/src/lib.rs#L51)):*
> ```XML
> pub fn calc_gas_info(
>     program: &Program,
>     function_gas_fixation: HashMap<usize, i32>,
> ```

use sierra::.. FunctionId here - as the indices are not used in this context.
and use `registry.get_function` later.



_Code quote:_
```XML
<usize
```
___
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1874#-NMXuvhq9RbF6ujn7kuM:-NMXuvhq9RbF6ujn7kuN:bl96p6k) ([raw file](https://github.com/starkware-libs/cairo/blob/79444c21aae2fd11509745c2623085eacc56d79a/crates/cairo-lang-sierra-gas/src/lib.rs#L51)):*
> ```XML
> pub fn calc_gas_info(
>     program: &Program,
>     function_gas_fixation: HashMap<usize, i32>,
> ```

function_set_costs
?



_Code quote:_
```XML
function_gas_fixation
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1874)* status: 4 of 11 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1874#-NMXudHiDWrISQ4aKTHo:-NMXz6rq5LG4FZwGoGB0:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/79444c21aae2fd11509745c2623085eacc56d79a/crates/cairo-lang-sierra-gas/src/lib.rs#L51)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

use sierra::.. FunctionId here - as the indices are not used in this context.
and use `registry.get_function` later.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1874#-NMXuvhq9RbF6ujn7kuM:-NMXz7Ou1Ws9K7fAlIiM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/79444c21aae2fd11509745c2623085eacc56d79a/crates/cairo-lang-sierra-gas/src/lib.rs#L51)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

function_set_costs
?
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 11 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1874)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/metadata.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1874#-NMY3VQ06W4Yje4uzNN3:-NMY3VQ06W4Yje4uzNN4:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/b0c24b115e56d5336187ea7a743b6df1be1c1646/crates/cairo-lang-sierra-to-casm/src/metadata.rs#L29)):*
> ```XML
> }
> 
> #[derive(Default)]
> ```

doc



_Code quote:_
```XML
#[derive(Default)]
pub struct MetadataComputationConfig {
    pub function_set_costs: HashMap<FunctionId, HashMap<CostTokenType, i32>>,
```
___
*[`crates/cairo-lang-sierra-to-casm/src/metadata.rs` line 31 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1874#-NMY3OdQAK7xhzNCjEkG:-NMY3OdQAK7xhzNCjEkH:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b0c24b115e56d5336187ea7a743b6df1be1c1646/crates/cairo-lang-sierra-to-casm/src/metadata.rs#L31)):*
> ```XML
> #[derive(Default)]
> pub struct MetadataComputationConfig {
>     pub function_set_costs: HashMap<FunctionId, HashMap<CostTokenType, i32>>,
> ```





_Suggestion:_
```XML
    pub function_set_costs: UnorderedHashMap<FunctionId, UnorderedHashMap<CostTokenType, i32>>,
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1874)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/metadata.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1874#-NMY3VQ06W4Yje4uzNN3:-NMY_JcJ63pBpv2ywkj0:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b0c24b115e56d5336187ea7a743b6df1be1c1646/crates/cairo-lang-sierra-to-casm/src/metadata.rs#L29)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/metadata.rs` line 31 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1874#-NMY3OdQAK7xhzNCjEkG:-NMY_Jul3Cvis6q1TKXe:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b0c24b115e56d5336187ea7a743b6df1be1c1646/crates/cairo-lang-sierra-to-casm/src/metadata.rs#L31)):*
> ```XML
> #[derive(Default)]
> pub struct MetadataComputationConfig {
>     pub function_set_costs: HashMap<FunctionId, HashMap<CostTokenType, i32>>,
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 11 of 29 files at r7, 8 of 11 files at r9, 57 of 57 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1874#-:-NMYh0YgCBl0ZcoXdmsw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
