### PR TITLE
Remove global `implicits_precedence` from RootDatabase and replace it with tagging of `#[external]` functions within `StarknetPlugin`

### LINKED ISSUE #2651: dev:  Remove global `implicits_precedence` from RootDatabase and replace it with tagging of `#[external]` functions within `StarknetPlugin`
As title says. This has been discussed with Cairo team privately and we agreed upon trying this approach.

### PR DESCRIPTION
**Pull request by mkaput**
fix #2651

---

**Stack**:
- #2894
- #2893
- #2882 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2882)

### CODE REVIEW

**Review by mkaput — COMMENTED** [review]
@orizi could you please verify that I didn't mess anything in Sierra? To my eyes it looks great but I may have overlooked something.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2882#-:-NTU5c4uEGBjnu3qrFoa:bpik1cd)* status: 0 of 21 files reviewed, all discussions resolved (waiting on @orizi, @spapinistarkware, and @yuvalsw)

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 8 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2882)* status: 8 of 21 files reviewed, 8 unresolved discussions (waiting on @mkaput, @orizi, and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2882#-NTh2ajn5RWZcRRa2k4F:-NTh2ajn5RWZcRRa2k4G:bdge03d) (no related file):*
Can you please explain the rational behind this change?

___
___
*[`crates/cairo-lang-lowering/src/implicits/mod.rs` line 244 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2882#-NTgwj6f7HtKVcaFy16V:-NTgwj6f7HtKVcaFy16W:bac586z) ([raw file](https://github.com/starkware-libs/cairo/blob/bf02f85984907ccab5efe941e99da58238e370b7/crates/cairo-lang-lowering/src/implicits/mod.rs#L244)):*
> ```XML
>         }
>     }
>     Ok(all_implicits.into_iter().collect())
> ```

this is not sorted now on purpose?
___
*[`crates/cairo-lang-semantic/src/db.rs` line 435 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2882#-NTgwwGA9kTz_CIWWwiz:-NTgwwGA9kTz_CIWWwj-:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/bf02f85984907ccab5efe941e99da58238e370b7/crates/cairo-lang-semantic/src/db.rs#L435)):*
> ```XML
>         impl_function_id: ImplFunctionId,
>     ) -> Maybe<Vec<TypeId>>;
>     /// Returns the explicit implicits precedence of an impl function.
> ```





_Suggestion:_
```XML
 Returns the implicits precedence
```
___
*[`crates/cairo-lang-semantic/src/db.rs` line 520 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2882#-NTgx69SAvz6-hd1WKbV:-NTgx69SAvz6-hd1WKbW:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/bf02f85984907ccab5efe941e99da58238e370b7/crates/cairo-lang-semantic/src/db.rs#L520)):*
> ```XML
>         free_function_id: FreeFunctionId,
>     ) -> Maybe<Vec<TypeId>>;
>     /// Returns the explicit implicits precedence of a free function.
> ```





_Suggestion:_
```XML
urns th implicits precedence of a
```
___
*[`crates/cairo-lang-semantic/src/items/function_with_body.rs` line 273 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2882#-NTh-jpaA6O4xc29ExJD:-NTh-jpaA6O4xc29ExJE:b-f9kukk) ([raw file](https://github.com/starkware-libs/cairo/blob/bf02f85984907ccab5efe941e99da58238e370b7/crates/cairo-lang-semantic/src/items/function_with_body.rs#L273)):*
> ```XML
> }
> 
> /// Get [ImplicitPrecedence] of the given function by looking at its attributes.
> ```

You're given the attributes, not the function.
Also add doc of the second return type.

Also - I am not sure we want to do attribute processing in the semantic phase.
___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 726 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2882#-NTh0yNXBRZNTtAZan93:-NTh0yNXBRZNTtAZan94:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/bf02f85984907ccab5efe941e99da58238e370b7/crates/cairo-lang-semantic/src/items/functions.rs#L726)):*
> ```XML
> 
> #[derive(Clone, Debug, Default, Eq, PartialEq)]
> pub struct ImplicitPrecedence(Vec<TypeId>);
> ```

doc
___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 731 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2882#-NTh0bgK6MDTJ1Cih2N8:-NTh0bgK6MDTJ1Cih2N9:b5unbue) ([raw file](https://github.com/starkware-libs/cairo/blob/bf02f85984907ccab5efe941e99da58238e370b7/crates/cairo-lang-semantic/src/items/functions.rs#L731)):*
> ```XML
>     /// A precedence that does not actually prefer any implicit.
>     ///
>     /// When applied to a sequence of implicits, their order will not change.
> ```

they will change according to their names, won't they?



_Code quote:_
```XML
their order will not change.
```
___
*[`crates/cairo-lang-starknet/src/plugin/consts.rs` line 31 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2882#-NTh1Uba7WNUVoMoC-X9:-NTh1Uba7WNUVoMoC-XA:b-3qnc53) ([raw file](https://github.com/starkware-libs/cairo/blob/bf02f85984907ccab5efe941e99da58238e370b7/crates/cairo-lang-starknet/src/plugin/consts.rs#L31)):*
> ```XML
> pub(super) const L1_HANDLER_FIRST_PARAM_NAME: &str = "from_address";
> 
> /// Starknet OS expected implicit precedence.
> ```

suggestion



_Suggestion:_
```XML
/// Starknet OS required implicit precedence.
```

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2882)* status: 8 of 21 files reviewed, 8 unresolved discussions (waiting on @orizi, @spapinistarkware, and @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2882#-NTh2ajn5RWZcRRa2k4F:-NTwRzW13U7RZrA2IOox:b-cyb64m) (no related file):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Can you please explain the rational behind this change?
</blockquote></details>

Pinged you on private channels to the whole discussion. To sum it up publicly: 
- my primary motivation is to remove `with_implicits_precedence` on `RootDatabaseBuilder`, and make `StarknetPlugin` the only thing you have to enable in order to build contracts
- with this, compiler users will only have to think about plugins regarding what they are compiling when setting up `RootDatabaseBuilder`
- and effectively move differentiating point between pure Cairo and Starknet contract compilation to be after diagnostics checking (currently it's at the very beginning of compilation process -- because you have to think about it when setting up RootDatabase)

___
___
*[`crates/cairo-lang-lowering/src/implicits/mod.rs` line 244 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2882#-NTgwj6f7HtKVcaFy16V:-NTwSfaf19sGpjCYGFfb:b-k0endp) ([raw file](https://github.com/starkware-libs/cairo/blob/bf02f85984907ccab5efe941e99da58238e370b7/crates/cairo-lang-lowering/src/implicits/mod.rs#L244)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

this is not sorted now on purpose?
</blockquote></details>

I moved to sorting down, so that each particular function sorts implicits on its own

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2882)* status: 8 of 21 files reviewed, 5 unresolved discussions (waiting on @orizi, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 435 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2882#-NTgwwGA9kTz_CIWWwiz:-NTweXa80Pm0iczvJ_Wi:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/bf02f85984907ccab5efe941e99da58238e370b7/crates/cairo-lang-semantic/src/db.rs#L435)):*
> ```XML
>         impl_function_id: ImplFunctionId,
>     ) -> Maybe<Vec<TypeId>>;
>     /// Returns the explicit implicits precedence of an impl function.
> ```

Done
___
*[`crates/cairo-lang-semantic/src/db.rs` line 520 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2882#-NTgx69SAvz6-hd1WKbV:-NTweX1J7T6us05t9BIC:b-j418un) ([raw file](https://github.com/starkware-libs/cairo/blob/bf02f85984907ccab5efe941e99da58238e370b7/crates/cairo-lang-semantic/src/db.rs#L520)):*
> explicit
Done
___
*[`crates/cairo-lang-semantic/src/items/function_with_body.rs` line 273 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2882#-NTh-jpaA6O4xc29ExJD:-NTwekUw-RkXQlp14VW6:bxtru0f) ([raw file](https://github.com/starkware-libs/cairo/blob/bf02f85984907ccab5efe941e99da58238e370b7/crates/cairo-lang-semantic/src/items/function_with_body.rs#L273)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

You're given the attributes, not the function.
Also add doc of the second return type.

Also - I am not sure we want to do attribute processing in the semantic phase.
</blockquote></details>

This function is following implementation of inline config, and I just monkeyed all of this. I am hesitant to make a differing implementation because it's out of scope of this PR... The doc also already explicitly states that it looks at the attributes that it gets, and it assumes they come from the function declaration.

I clarified the returned type because I agree it's missing.
___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 726 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2882#-NTh0yNXBRZNTtAZan93:-NTwgWnjD6UxSL5NLwyC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bf02f85984907ccab5efe941e99da58238e370b7/crates/cairo-lang-semantic/src/items/functions.rs#L726)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 731 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2882#-NTh0bgK6MDTJ1Cih2N8:-NTwgEGY-taHbQa_xduA:b-j0asw4) ([raw file](https://github.com/starkware-libs/cairo/blob/bf02f85984907ccab5efe941e99da58238e370b7/crates/cairo-lang-semantic/src/items/functions.rs#L731)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

they will change according to their names, won't they?
</blockquote></details>

Done, you're right.
___
*[`crates/cairo-lang-starknet/src/plugin/consts.rs` line 31 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2882#-NTh1Uba7WNUVoMoC-X9:-NTwe0lv0OJmz6sBNkuu:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/bf02f85984907ccab5efe941e99da58238e370b7/crates/cairo-lang-starknet/src/plugin/consts.rs#L31)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

suggestion
</blockquote></details>

Done

**Comment by mkaput** [comment]
Superseded by #2958

**Pull request closed without merging**
