### PR TITLE
Addes dependent types to the ABI.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3720)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3720)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/test_data/test_contract.sierra.json` line 2045 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3720#-N_n-0u05gRZk42yNrSG:-N_n-0u05gRZk42yNrSH:b-ebvdo) ([raw file](https://github.com/starkware-libs/cairo/blob/77ecda5e87ad956379550c798f085445af518df5/crates/cairo-lang-starknet/test_data/test_contract.sierra.json#L2045)):*
> ```JSON
>     {
>       "type": "enum",
>       "name": "core::bool",
> ```

I thought we've decided not to add type from the core lib?



_Code quote:_
```JSON
core::bool"
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/abi.rs` line 569 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3720#-N_n05wG8OD7-PHFbdhI:-N_n05wG8OD7-PHFbdhJ:brttpt6) ([raw file](https://github.com/starkware-libs/cairo/blob/94c613b9d559655c34d505a3b82fa54a9f0e41d5/crates/cairo-lang-starknet/src/abi.rs#L569)):*
> ```XML
>             ConcreteTypeId::Struct(id) => self.abi.items.push(Item::Struct(Struct {
>                 name: concrete.format(db),
>                 members: get_struct_members(db, id).map_err(|_| ABIError::UnexpectedType)?,
> ```

the problem was the this didn't add inner types, right?



_Code quote:_
```XML
get_struct_members(db, id)
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3720)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/test_data/test_contract.sierra.json` line 2045 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3720#-N_n-0u05gRZk42yNrSG:-N_n-87tBwEuTU7kmnjF:b9keqct) ([raw file](https://github.com/starkware-libs/cairo/blob/77ecda5e87ad956379550c798f085445af518df5/crates/cairo-lang-starknet/test_data/test_contract.sierra.json#L2045)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I thought we've decided not to add type from the core lib?
</blockquote></details>

we've rolled back on that decision a while ago.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3720)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/abi.rs` line 569 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3720#-N_n05wG8OD7-PHFbdhI:-N_n0H8-17magCouxBWG:b-3cslek) ([raw file](https://github.com/starkware-libs/cairo/blob/94c613b9d559655c34d505a3b82fa54a9f0e41d5/crates/cairo-lang-starknet/src/abi.rs#L569)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

the problem was the this didn't add inner types, right?
</blockquote></details>

indeed.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3720)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3720#-:-N_n0hSZ-80eCpzJs7xI:bnfp4nl)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3720)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
