### PR TITLE
Change contract_address range to match backend.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1605)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
I don't know if we should fix that or fix the backend.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1605#-:-NL1A9Tk9vt50PX0EhSW:bbsi6qg)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1605)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/interoperability.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1605#-NM88snR6UpETWaYMUry:-NM88snR6UpETWaYMUrz:bj1oqwt) ([raw file](https://github.com/starkware-libs/cairo/blob/af777f03fac33cbcba49a69bb4947719ae91e705/crates/cairo-lang-sierra/src/extensions/modules/starknet/interoperability.rs#L17)):*
> ```XML
> use crate::program::GenericArg;
> 
> /// Type for StarkNet storage address, a value in the range [1, 2 ** 250 - 256).
> ```

The comment says storage, but the type name is `ContractAddress`.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/starknet/interoperability.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1605#-NM89CI47kQd0KLBMWMR:-NM89CI47kQd0KLBMWMS:b-ebyghy) ([raw file](https://github.com/starkware-libs/cairo/blob/af777f03fac33cbcba49a69bb4947719ae91e705/crates/cairo-lang-sierra-to-casm/src/invocations/starknet/interoperability.rs#L74)):*
> ```XML
> ) -> Result<CompiledInvocation, InvocationError> {
>     let addr_bound: BigInt = (BigInt::one() << 251) - 256;
>     let addr = &libfunc.c;
> ```

Can this be negative?

**Review by liorgold2 — COMMENTED** [review]
WDYM?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1605#-:-NM89PV70cW2Js-33Yy-:b-7zi8tj)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
the backend put more restriction than the cairo code in lots of places:
e.g.
https://github.com/starkware-industries/starkware/blob/a290ebf2ab90b523d9f36179a1323c08244cbfd9/src/starkware/starknet/definitions/constants.py#L17

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/interoperability.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1605#-NM88snR6UpETWaYMUry:-NM8BFKy6qgKUdedR7NY:b-qwc6bw) ([raw file](https://github.com/starkware-libs/cairo/blob/af777f03fac33cbcba49a69bb4947719ae91e705/crates/cairo-lang-sierra/src/extensions/modules/starknet/interoperability.rs#L17)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

The comment says storage, but the type name is `ContractAddress`.
</blockquote></details>

Ori already fixed that.

**Review by liorgold2 — COMMENTED** [review]
That's a valid restriction since 0 is used for the OS.
We need to decide what `get_caller_address`returns when the caller is the OS. One option is `Option<ContractAddress>`.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1605#-:-NM8UCgP0TqTFc75H_L6:b-kcasfg)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-to-casm/src/invocations/starknet/interoperability.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1605#-NM89CI47kQd0KLBMWMR:-NMXcytUCFgXYlnD0fpB:bjfkxi7) ([raw file](https://github.com/starkware-libs/cairo/blob/af777f03fac33cbcba49a69bb4947719ae91e705/crates/cairo-lang-sierra-to-casm/src/invocations/starknet/interoperability.rs#L74)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Can this be negative?
</blockquote></details>

Yes.
I fixed it in a different PR.

**Comment by ilyalesokhin-starkware** [comment]
Decided to keep the range [0, 2**251)

**Pull request closed without merging**
