### PR TITLE
Better error message on return type mismatch.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1276)

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1276)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1276)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1276)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/sierra_generator/src/local_variables.rs` line 258 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1276#-NJ-JGdO7n-aKtm0ft0r:-NJ-JGdO7n-aKtm0ft0s:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/434cba563ad4c6e66d0153e83fa294ec84fd114d/crates/sierra_generator/src/local_variables.rs#L258)):*
> ```XML
>         outputs.len(),
>         vars.len(),
>         "Wrong number of outputs for '{}'. Likely misalignment of the libfunc's corresponding \
> ```





_Suggestion:_
```XML
        "Wrong number of outputs for '{}'. The 'extern' declaration of the libfunc does not match the Sierra definition.",
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1276)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @orizi)

___
*[`crates/sierra_generator/src/local_variables.rs` line 258 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1276#-NJ-JGdO7n-aKtm0ft0r:-NJ-K6HQ5GC6CI05eLGV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/434cba563ad4c6e66d0153e83fa294ec84fd114d/crates/sierra_generator/src/local_variables.rs#L258)):*
> ```XML
>         outputs.len(),
>         vars.len(),
>         "Wrong number of outputs for '{}'. Likely misalignment of the libfunc's corresponding \
> ```

Done.

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1276#-:-NJ-KJbB-y78B94ZNOkH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
