### PR TITLE
Added basic temporary serde, and used it for contracts.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:ce45b825

---

**Stack**:
- #1508
- #1504 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r1, 8 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1504)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @orizi and @yuvalsw)

___
*[`crates/starknet/src/plugin.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1504#-NKH_AKQ3WcNt8zPnkTQ:-NKH_AKQ3WcNt8zPnkTR:b7x5z6o) ([raw file](https://github.com/starkware-libs/cairo/blob/dc9b8cf62471717bb25ebe1c1108355c84bf8d57/crates/starknet/src/plugin.rs#L164)):*
> ```XML
>             quote! {let $mut_modifier$(arg_name.clone()) = match $deser_func(data) {
>                 Option::Some(x) => x,
>                 Option::None(()) => panic(array_new::<felt>()),
> ```

add error message or TODO.



_Code quote:_
```XML
panic(array_new::<felt>())
```

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1504#-:-NKHeRFW7GoCvSlvbNsI:bnfp4nl)* status: 9 of 11 files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 2 of 11 files at r1, 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1504#-:-NKHweaa7fQF6644vocu:bnfp4nl)* status: 2 of 11 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`corelib/serde.cairo` line 32 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1504#-NKHrpKF62R7_tY7ALQQ:-NKHrpKG0H--eW80s0DT:bnlarjv) ([raw file](https://github.com/starkware-libs/cairo/blob/bca6273fc248254b469bae5eb8baa0dc1cf6652e/corelib/serde.cairo#L32)):*
> ```Cairo
> fn serialize_u256(ref serialized: Array::<felt>, input: u256) {
>     serialize_u128(serialized, input.low);
>     serialize_u128(serialized, input.high);
> ```

Is there a reason we serialize it as "little endian"?



_Code quote:_
```Cairo
    serialize_u128(serialized, input.low);
    serialize_u128(serialized, input.high);
```
___
*[`crates/starknet/src/plugin.rs` line 164 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1504#-NKHuEAu37XxQ3DTolp3:-NKHuEAu37XxQ3DTolp4:b3y7bbl) ([raw file](https://github.com/starkware-libs/cairo/blob/bca6273fc248254b469bae5eb8baa0dc1cf6652e/crates/starknet/src/plugin.rs#L164)):*
> ```XML
>             quote! {let $mut_modifier$(arg_name.clone()) = match $deser_func(data) {
>                 Option::Some(x) => x,
>                 Option::None(()) => panic(array_new::<felt>()),
> ```

TOK
Add error message



_Code quote:_
```XML
array_new::<felt>()
```
___
*[`crates/starknet/src/plugin.rs` line 177 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1504#-NKHttjM5YGK9ExSFNBv:-NKHttjM5YGK9ExSFNBw:b-75ywm7) ([raw file](https://github.com/starkware-libs/cairo/blob/bca6273fc248254b469bae5eb8baa0dc1cf6652e/crates/starknet/src/plugin.rs#L177)):*
> ```XML
>     let wrapped_name = format!("super::{function_name}");
>     let (let_res, append_res) = match sig.ret_ty(db) {
>         OptionReturnTypeClause::Empty(_) => ("", "".to_owned()),
> ```

why is this needed?



_Code quote:_
```XML
.to_owned()
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1504)* status: 2 of 11 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`corelib/serde.cairo` line 32 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1504#-NKHrpKF62R7_tY7ALQQ:-NKI0c8RBPWQr-ao3CuQ:b-bl40xr) ([raw file](https://github.com/starkware-libs/cairo/blob/bca6273fc248254b469bae5eb8baa0dc1cf6652e/corelib/serde.cairo#L32)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Is there a reason we serialize it as "little endian"?
</blockquote></details>

no particular reason - just needed to decide on ordering.
___
*[`crates/starknet/src/plugin.rs` line 177 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1504#-NKHttjM5YGK9ExSFNBv:-NKI0rDb0eRqhd5xjb9T:bm73to9) ([raw file](https://github.com/starkware-libs/cairo/blob/bca6273fc248254b469bae5eb8baa0dc1cf6652e/crates/starknet/src/plugin.rs#L177)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

why is this needed?
</blockquote></details>

since the other arm returns a string (because of the format!(..))

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 1 of 11 files at r1, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1504)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1504)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`corelib/serde.cairo` line 32 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1504#-NKHrpKF62R7_tY7ALQQ:-NKIMAKUEtAeszO7Q8zX:b-czlbyc) ([raw file](https://github.com/starkware-libs/cairo/blob/bca6273fc248254b469bae5eb8baa0dc1cf6652e/corelib/serde.cairo#L32)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no particular reason - just needed to decide on ordering.
</blockquote></details>

If you don't mind, I prefer big endian on serialization as it's more "readable" (although no one is really going to read this).
But not big an endian. ehhh deal. :)
___
*[`crates/starknet/src/plugin.rs` line 177 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1504#-NKHttjM5YGK9ExSFNBv:-NKILiQQ-dW4bPtweFRW:b-pjjvvy) ([raw file](https://github.com/starkware-libs/cairo/blob/bca6273fc248254b469bae5eb8baa0dc1cf6652e/crates/starknet/src/plugin.rs#L177)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

since the other arm returns a string (because of the format!(..))
</blockquote></details>

OK
I think we usually use to_string rather than to_owned, so consider this.
Another option is to add .as_str() to the format.
___
*[`crates/starknet/src/plugin.rs` line 164 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1504#-NKILHmX-sVKrJvazRF3:-NKILHmX-sVKrJvazRF4:b-hoe10h) ([raw file](https://github.com/starkware-libs/cairo/blob/873b288eee76e2e77a120d9b829cd302251e1d97/crates/starknet/src/plugin.rs#L164)):*
> ```XML
>     let mut arg_definitions = quote! {};
>     let mut ref_appends = quote! {};
>     let input_data_short_err = "'Input too short for arguments'";
> ```

I'd even add "argument #i" (use enumerate and move this defintion into the for)



_Suggestion:_
```XML
Input too short for deserialization of argument
```

**Pull request merged**
