### PR TITLE
Made simple stores based on store packing.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4280)

### CODE REVIEW

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4280#-:-NhWqWof0SEI1qbk8wb1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4280)* status: 22 of 31 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4280#-NhbYn5m7FhQtMDlvWwM:-NhcQZhN-gTODDpJI5NF:bhd9vyd) (no related file):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

1. Can you please doc StorePacking and Store traits?
2. There was no impl of StorePacking so far besides in one test?
</blockquote></details>

1. Done.
2. Was used for easier implementation for users.

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4280#-NhbZbui3l5QsDLADALX):*
Done.
___
*[`corelib/src/starknet/storage_access.cairo` line 130 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4280#-Nhb_w9kDehXrxiNNpkQ:-NhcOeEqD_ieJpYQe7Gt:b-nj65zf) ([raw file](https://github.com/starkware-libs/cairo/blob/858dbd2f918b2dd9eabc1d35f6c6002b2d7bf4bf/corelib/src/starknet/storage_access.cairo#L130)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

wouldn't this work instead of all?

```
impl TStorePacking<T, +Into<T, felt252>, +TryInto<felt252, T>> of StorePacking<T, felt252> {
    // #[inline] here too?
    fn pack(value: T) -> felt252 {
        value.into()
    }
    #[inline]
    fn unpack(value: felt252) -> T {
        value.try_into().expect('Unexpected value')
    }
}
```

And if you don't want it to be added automatically for new types which are convertible to felt252, you can use the hidden generic impl + impl aliases method. But I don't see a reason not to add automatically for types convertible to felt252.
</blockquote></details>

i don't want to break the divergence in the panic value.
___
*[`corelib/src/starknet/storage_access.cairo` line 145 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4280#-Nhba6Kb1d743EsdDJbe:-NhcQmA3ATS0imYauuQ3:bgqb003) ([raw file](https://github.com/starkware-libs/cairo/blob/858dbd2f918b2dd9eabc1d35f6c6002b2d7bf4bf/corelib/src/starknet/storage_access.cairo#L145)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

why is unpack inlined but pack isn't? Is it on purpose?
</blockquote></details>

the pack does not require it - the heuristic inlines it already (it is always a single libfunc).
___
*[`corelib/src/starknet/storage_access.cairo` line 147 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4280#-Nhb_X293FfODeBsp3Wf:-NhcOpyXCvFmLHT6hdFn:b8ii6t7) ([raw file](https://github.com/starkware-libs/cairo/blob/858dbd2f918b2dd9eabc1d35f6c6002b2d7bf4bf/corelib/src/starknet/storage_access.cairo#L147)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Here and in the other impls.
</blockquote></details>

this keeps the same original error.
StorePacking exists only for Store.

**Review by yuvalsw — APPROVED** [review]
> Reviewed 9 of 9 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4280)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/starknet/storage_access.cairo` line 130 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4280#-Nhb_w9kDehXrxiNNpkQ:-Nhfuz4V2yvRZXFTia_G:bnytzr2) ([raw file](https://github.com/starkware-libs/cairo/blob/858dbd2f918b2dd9eabc1d35f6c6002b2d7bf4bf/corelib/src/starknet/storage_access.cairo#L130)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i don't want to break the divergence in the panic value.
</blockquote></details>

unblocking, but - is it that important?
___
*[`corelib/src/starknet/storage_access.cairo` line 147 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4280#-Nhb_X293FfODeBsp3Wf:-Nhfv6211zjpKmnU5UjG:b79nd7n) ([raw file](https://github.com/starkware-libs/cairo/blob/858dbd2f918b2dd9eabc1d35f6c6002b2d7bf4bf/corelib/src/starknet/storage_access.cairo#L147)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this keeps the same original error.
StorePacking exists only for Store.
</blockquote></details>

I don't see the issue with changing the original error, as long as it has the same important info.
But also here - unblocking

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4280#-:-Nhfve6nASPd2ZFZdkmk:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4280)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/starknet/storage_access.cairo` line 130 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4280#-Nhb_w9kDehXrxiNNpkQ:-Nhfy__x7mmUyxgb0hHt:bbnx9tz) ([raw file](https://github.com/starkware-libs/cairo/blob/858dbd2f918b2dd9eabc1d35f6c6002b2d7bf4bf/corelib/src/starknet/storage_access.cairo#L130)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

unblocking, but - is it that important?
</blockquote></details>

I don't know if it is - so rather not break it - and at the very least - still easier to find possible errors in this case.
___
*[`corelib/src/starknet/storage_access.cairo` line 147 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4280#-Nhb_X293FfODeBsp3Wf:-NhfyoNtD40sPhmHKJJN:bo7kfft) ([raw file](https://github.com/starkware-libs/cairo/blob/858dbd2f918b2dd9eabc1d35f6c6002b2d7bf4bf/corelib/src/starknet/storage_access.cairo#L147)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I don't see the issue with changing the original error, as long as it has the same important info.
But also here - unblocking
</blockquote></details>

i tried not to do any logic changes - but about this specifically - the error is for the StoreU8 - not for the StorePack - StorePack is a fancy way of doing a Store.

**Pull request merged**
