### PR TITLE
Enable drop check

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2441)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2441** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2441" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2441?utm_source=stack-comment).

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2441)* status: 0 of 29 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2441#-NQAzJ_iAPi7JFm3i7xo:-NQAzJ_iAPi7JFm3i7xp:bksns1n) (no related file):*
Enabled the drop check and diagnostics everywhere.
Addas the Drop impl generic params where needed.
Fixed inference:
Before, when adding a new impl var, inference eagerly searched for all impls and set it as candidates.
This lead to infinite recursion sometimes.
Now, inference only searches for candidates when the first generic arg is not a variable (e.g. Option<?0> is not a var).
This is a heuristic.

Cycle detection should be incorporated later.

___

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 29 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2441)* status: all files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`corelib/src/ec.cairo` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2441#-NQB0RYM2vGufgKjfqYQ:-NQB0RYN7bANOeSHnXnk:b-c0x0k4) ([raw file](https://github.com/starkware-libs/cairo/blob/eab9e7d7e11e262ae9901c520e44330b2b52e06c/corelib/src/ec.cairo#L19)):*
> ```Cairo
> type NonZeroEcPoint = NonZero<EcPoint>;
> 
> impl NonZeroEcPointCopy of Copy::<NonZeroEcPoint>;
> ```

Delete as well
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 504 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2441#-NQBHSyQ0XWUU5nauL87:-NQBHSyR4_4_7-s8-Vo-:bz5ftuf) ([raw file](https://github.com/starkware-libs/cairo/blob/eab9e7d7e11e262ae9901c520e44330b2b52e06c/crates/cairo-lang-semantic/src/expr/inference.rs#L504)):*
> ```XML
>     /// Determines if an assignment to `generic_params` can be chosen s.t. `generic_args` will be
>     /// substituted to `expected_generic_args`.
>     // TODO(spapini): Fail gracefuly on infinite loops.
> ```

gracefully
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/diagnostics` line 177 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2441#-NQBHuRY0hCFKR1OFiko:-NQBHuRY0hCFKR1OFikp:b-85bp) ([raw file](https://github.com/starkware-libs/cairo/blob/071b1373d9da0b5f7e00f1826c00fa75a8c015ed/crates/cairo-lang-starknet/src/plugin/plugin_test_data/diagnostics#L177)):*
> ```
> 
> //! > expected_diagnostics
> error: Type annotations needed. Failed to infer ?5
> ```

Why did this change?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2441)* status: 27 of 29 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/ec.cairo` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2441#-NQB0RYM2vGufgKjfqYQ:-NQEFS_-9YApposxG3Vg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/eab9e7d7e11e262ae9901c520e44330b2b52e06c/corelib/src/ec.cairo#L19)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Delete as well
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 504 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2441#-NQBHSyQ0XWUU5nauL87:-NQEFVrl0j1Lr7HOhoPf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/eab9e7d7e11e262ae9901c520e44330b2b52e06c/crates/cairo-lang-semantic/src/expr/inference.rs#L504)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

gracefully
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/diagnostics` line 177 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2441#-NQBHuRY0hCFKR1OFiko:-NQEFuOH-msJXMe_teXx:bnjj2iy) ([raw file](https://github.com/starkware-libs/cairo/blob/071b1373d9da0b5f7e00f1826c00fa75a8c015ed/crates/cairo-lang-starknet/src/plugin/plugin_test_data/diagnostics#L177)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Why did this change?
</blockquote></details>

The order of things changed. Before, we kept the deserialize as a trait function, and tried to resolve it at the end. Now, we try to resolve it early.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2441#-:-NQEH6wH2Nvu9sbeONvx:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
