### PR TITLE
fix usages in if let construct

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5016)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5016)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5016#-Npyz3SL07D9hStTdtCb:-Npyz3SL07D9hStTdtCc:bs6gqyj) (no related file):*
added failing test.

___

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5016)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5016#-Npyz3SL07D9hStTdtCb:-Npz1Rx13tISXUguNZHc:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

added failing test.
</blockquote></details>

Done.

___

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5016)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/test_data/if` line 263 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5016#-Npz2xkY46O5cBBslGW4:-Npz2xkY46O5cBBslGW5:b-l6hdjr) ([raw file](https://github.com/starkware-libs/cairo/blob/cc9e35b39d07d0eaffb94429f038e3c51410b0ae/crates/cairo-lang-lowering/src/test_data/if#L263)):*
> ```
> //! > function
> fn foo(a: myEnum) -> felt252 {
>     if let x = a {
> ```

revert

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5016)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/test_data/if` line 263 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5016#-Npz2xkY46O5cBBslGW4:-Npz42tv1_cVg2TBljKi:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cc9e35b39d07d0eaffb94429f038e3c51410b0ae/crates/cairo-lang-lowering/src/test_data/if#L263)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

revert
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5016#-:-Npz8p30AIsIbFS4CYE_:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5016)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
