### PR TITLE
Add hash_chain e2e test.

### PR DESCRIPTION
**Pull request by liorgold2**
**Stack**:
- #1137
- #1133
- #1132 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1132)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1132#-:-NHyt4QD2qR7iETMbX0u:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`tests/examples_test.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1132#-NHyt14w35_uh1eUReQY:-NHyt14w35_uh1eUReQZ:b-r60bo3) ([raw file](https://github.com/starkware-libs/cairo/blob/15250a081e80696d751b3a4449dee86382ea6e34/tests/examples_test.rs#L100)):*
> ```XML
> #[test_case("enum_flow", false)]
> #[test_case("corelib_usage", false)]
> #[test_case("hash_chain", false)]
> ```

add a disabled runner test.



_Code quote:_
```XML
#[test_case("hash_chain", false)]
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1132)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1132)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`tests/examples_test.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1132#-NHyt14w35_uh1eUReQY:-NI-7MlpAb2UaKAZ8OWz:bnfuknu) ([raw file](https://github.com/starkware-libs/cairo/blob/15250a081e80696d751b3a4449dee86382ea6e34/tests/examples_test.rs#L100)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add a disabled runner test.
</blockquote></details>

Done. I tried using `=> ignore`, but I couldn't make it work for some reason, so I went with a comment + TODO.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1132)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

___
*[`tests/examples_test.rs` line 167 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1132#-NI-CgDU8xjPk-KOvqoc:-NI-CgDU8xjPk-KOvqod:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ff5a3b0244884b345537655d66507780c15dd50b/tests/examples_test.rs#L167)):*
> ```XML
> //     &[BigInt::parse_bytes(
> //         b"2dca1ad81a6107a9ef68c69f791bcdbda1df257aab76bd43ded73d96ed6227d", 16)];
> //     "hash_chain")]
> ```





_Suggestion:_
```XML
#[test_case(
     "hash_chain",
     &[3].map(BigInt::from),
     &[BigInt::parse_bytes(
         b"2dca1ad81a6107a9ef68c69f791bcdbda1df257aab76bd43ded73d96ed6227d", 16)] => ignore["reason"];
     "hash_chain")]
```

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1132)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1132)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
