### PR TITLE
chore: fix Cairo Extension logo

### PR DESCRIPTION
**Pull request by TAdev0**
@mkaput here is the branch where building locally solved the issue with logo correctly displaying 

This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5768)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5768)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput and @TAdev0)

___
*[`vscode-cairo/icons/marketplace.png` line 0 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5768#-O-0udtN3t2dl86RB7PF:-O-0udtN3t2dl86RB7PG:bxngkll) ([raw file](https://github.com/starkware-libs/cairo/blob/2418c17cbaad8ff3e4dff73a6b353a0620c0358c/vscode-cairo/icons/marketplace.png#L0)):*
this seems to have become 0 sized - should've this just been deleted?

**Comment by mkaput** [comment]
I still do not see anything being changed except you converted from SVG to 128x128 PNG (which is making things worse on low-resolution displays) and did some binary-level changes to the marketplace icon.

1. Can you please explain why do you need to convert to PNG?
2. Can you please provide me an instruction how to reproduce your issues on the following commit: f4b7b14b0f46b9e8cd6f0167d3b3120ec21681eb

This all works for me:

image
image

**Comment by TAdev0** [comment]
@mkaput indeed the content of the PR is not what makes it work. Building locally `main` works as well.

What we need to do is `vsce publish` 

I just tried to do it but i need a "Personal Access Token for publisher 'StarkWare` ", how can i get it ?

**Comment by mkaput** [comment]
You cannot release the extension to general audience :)

**Comment by TAdev0** [comment]
@mkaput  can you do `vsce publish` so that the logo will correctly display here?

https://marketplace.visualstudio.com/items?itemName=starkware.cairo1

**Comment by mkaput** [comment]
we'll do this along Cairo 2.7 release

**Pull request closed without merging**
