### PR TITLE
Core Lib Documentation: `Dict` module 

### PR DESCRIPTION
**Pull request by TAdev0**

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6753)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @TAdev0)

___
*[`corelib/src/dict.cairo` line 11 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6753#-OChkna4CB430jiatMxQ:-OChkna4CB430jiatMxR:b-xketdx) ([raw file](https://github.com/starkware-libs/cairo/blob/52a3b381160fc77d09741cc1f0ea1b85efd8b1fd/corelib/src/dict.cairo#L11)):*
> ```Cairo
> //! - `key`: The dictionary key being accessed (`felt252`)
> //! - `prev_value`: The previous value associated with this key
> //! - `new_value`: The new value being associated with this key
> ```

as discussed - should probably not be here.



_Code quote:_
```Cairo
//! Due to Cairo's immutable memory model, dictionaries are implemented as an append-only list
//! of dictionary access entries. Each entry is a triple of:
//! - `key`: The dictionary key being accessed (`felt252`)
//! - `prev_value`: The previous value associated with this key
//! - `new_value`: The new value being associated with this key
```

**Review by enitrat — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6753)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/dict.cairo` line 11 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6753#-OChkna4CB430jiatMxQ:-OCi1Fuu1dte9LTCN0di:bd3hz2s) ([raw file](https://github.com/starkware-libs/cairo/blob/52a3b381160fc77d09741cc1f0ea1b85efd8b1fd/corelib/src/dict.cairo#L11)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

as discussed - should probably not be here.
</blockquote></details>

@orizi Moved to end of module doc instead of here; however I'm still of opinion that this context is required to properly understand why the 'entry' mechanism is built the way it is (it returns a `prev_value` and takes a `new_value` when finalizing)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6753)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @enitrat)

___
*[`corelib/src/dict.cairo` line 11 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6753#-OChkna4CB430jiatMxQ:-OCi5ILU-V5sn-p4Ui1U:b-qw1rmh) ([raw file](https://github.com/starkware-libs/cairo/blob/52a3b381160fc77d09741cc1f0ea1b85efd8b1fd/corelib/src/dict.cairo#L11)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

@orizi Moved to end of module doc instead of here; however I'm still of opinion that this context is required to properly understand why the 'entry' mechanism is built the way it is (it returns a `prev_value` and takes a `new_value` when finalizing)
</blockquote></details>

i only partially agree.
the need for squashing is one thing - the actual layout is completely irelevant - and at the most i would have put a link for further reading.

**Comment by TAdev0** [comment]
@orizi  just removed the impl details

**Pull request merged**
