### PR TITLE
LS: Add completions of struct members

### PR DESCRIPTION
**Pull request by integraledelebesgue**
**Stack**:
- #6566
- #6565
- #6567 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by piotmag769 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6567#-:-OA__ToT5AyzTa4Umbop:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/tests/test_data/completions/structs.txt` line 25 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6567#-OA_c1bQ0GsP_KDlivFW:-OA_c1bQ0GsP_KDlivFX:b-r6ada1) ([raw file](https://github.com/starkware-libs/cairo/blob/dd6a947c496bb5d1efc2aecf3cb5e6b9dc48ff57/crates/cairo-lang-language-server/tests/test_data/completions/structs.txt#L25)):*
> ```help
>             x: 0x0,
>             y: 0x0,
>             z: 0x0
> ```

I guess missing <caret> here?
___
*[`crates/cairo-lang-language-server/tests/test_data/completions/structs.txt` line 40 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6567#-OA_c5NN1I4cJTyMPUMb:-OA_c5NN1I4cJTyMPUMc:b-lfvuh) ([raw file](https://github.com/starkware-libs/cairo/blob/dd6a947c496bb5d1efc2aecf3cb5e6b9dc48ff57/crates/cairo-lang-language-server/tests/test_data/completions/structs.txt#L40)):*
> ```help
>             x: 0x0,
>             <caret>
>             ..s
> ```

To make sure it doesn't work in the second case



_Suggestion:_
```help
            <caret>
            <caret>..s
```

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6567)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, and @orizi)

___
*[`crates/cairo-lang-language-server/tests/test_data/completions/structs.txt` line 47 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6567#-OAqYl23BDNJ41vTveI6:-OAqYl23BDNJ41vTveI7:bcm0ebr) ([raw file](https://github.com/starkware-libs/cairo/blob/dd6a947c496bb5d1efc2aecf3cb5e6b9dc48ff57/crates/cairo-lang-language-server/tests/test_data/completions/structs.txt#L47)):*
> ```help
> mod happy_cases {
>     use super::some_module::Struct;
>     
> ```

please trim whitespace in empty lines
___
*[`crates/cairo-lang-language-server/tests/test_data/completions/structs.txt` line 62 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6567#-OAqY_Kw3Ho2u43BUQup:-OAqY_Kw3Ho2u43BUQuq:bo4jw0n) ([raw file](https://github.com/starkware-libs/cairo/blob/dd6a947c496bb5d1efc2aecf3cb5e6b9dc48ff57/crates/cairo-lang-language-server/tests/test_data/completions/structs.txt#L62)):*
> ```help
>             x: 0x0,
>             <caret>
>         }
> ```

consider putting all of these in single line so that source line contexts will make sense



_Suggestion:_
```help
        let a = Struct { <caret> };

        let b = Struct { y: 0x0, <caret> };

        let c = Struct { y: 0x0, x: 0x0, <caret> }
```

**Review by integraledelebesgue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6567)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/tests/test_data/completions/structs.txt` line 25 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6567#-OA_c1bQ0GsP_KDlivFW:-OAqVaZfC-F8Cbzgbnzd:b-4aqp9b) ([raw file](https://github.com/starkware-libs/cairo/blob/dd6a947c496bb5d1efc2aecf3cb5e6b9dc48ff57/crates/cairo-lang-language-server/tests/test_data/completions/structs.txt#L25)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

I guess missing <caret> here?
</blockquote></details>

This struct is instantiated only to be used below in a "tail": `..s`

**Review by piotmag769 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6567)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, and @orizi)

**Review by integraledelebesgue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6567)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/tests/test_data/completions/structs.txt` line 62 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6567#-OAqY_Kw3Ho2u43BUQup:-OArDzdCBB4SWinOmw1W:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/dd6a947c496bb5d1efc2aecf3cb5e6b9dc48ff57/crates/cairo-lang-language-server/tests/test_data/completions/structs.txt#L62)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

consider putting all of these in single line so that source line contexts will make sense
</blockquote></details>

Done.

**Review by integraledelebesgue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6567)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/tests/test_data/completions/structs.txt` line 47 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6567#-OAqYl23BDNJ41vTveI6:-OArLtX452L54fuCAGrX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/dd6a947c496bb5d1efc2aecf3cb5e6b9dc48ff57/crates/cairo-lang-language-server/tests/test_data/completions/structs.txt#L47)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

please trim whitespace in empty lines
</blockquote></details>

Done.

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6567#-:-OAvQpco5cA7iLvT5gjn:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @orizi)

**Review by piotmag769 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6567)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @orizi)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6567#-:-OAx99KA6YF5h0vd63o2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6567)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)

**Review by Draggu — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 1 of 1 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6567#-:-OB5GmeXDYHEku2bWD_b:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae)

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6567)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae)

**Review by mkaput — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6567)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae)

**Review by piotmag769 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6567)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae and @integraledelebesgue)

___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 363 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6567#-OBebywH-Usy6d9xpgs7:-OBebywH-Usy6d9xpgs8:btvljlc) ([raw file](https://github.com/starkware-libs/cairo/blob/ef74001e81d34242a5ab265755d31b4e3567e79b/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L363)):*
> ```XML
> 
>     let struct_members =
>         concrete_struct_members(db, constructor_semantic_expr.concrete_struct_id).ok()?;
> ```

This is a query, use it as one



_Suggestion:_
```XML
db.concrete_struct_members(constructor_semantic_expr.concrete_struct_id)
```

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6567)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae and @integraledelebesgue)

**Review by integraledelebesgue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6567)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 363 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6567#-OBebywH-Usy6d9xpgs7:-OBf2A2-17pdWjYN_Uze:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/920e8b09fe33d095c0ea3502a3db235cd7f13a09/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L363)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

This is a query, use it as one
</blockquote></details>

Done

**Review by mkaput — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6567)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae)

**Comment by integraledelebesgue** [comment]
✓ Commit merged in pull request [#6566](https://github.com/starkware-libs/cairo/pull/6566)

**Pull request merged**
