### PR TITLE
Sierra generation: Add types that only appear in user functions.

### PR DESCRIPTION
**Pull request by liorgold2**
**Stack**:
- #4573
- #4572
- #4571 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4571)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4571)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-generator/src/program_generator.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4571#-NlqfxzM7ZoYmAEKdKo7:-NlqfxzM7ZoYmAEKdKo8:bqwnfci) ([raw file](https://github.com/starkware-libs/cairo/blob/fbcdccef1c123886c4d6bfe573f202c810e4ec68/crates/cairo-lang-sierra-generator/src/program_generator.rs#L159)):*
> ```XML
>     let types_in_user_functions = functions.iter().flat_map(|func| {
>         chain!(func.parameters.iter().map(|param| param.ty.clone()), func.ret_types.iter().cloned())
>     });
> ```

won't the function call libfunc already catch this?



_Code quote:_
```XML
    // Collect types that appear in user functions.
    let types_in_user_functions = functions.iter().flat_map(|func| {
        chain!(func.parameters.iter().map(|param| param.ty.clone()), func.ret_types.iter().cloned())
    });
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4571)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/program_generator.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4571#-NlqfxzM7ZoYmAEKdKo7:-Nlqm21J64FzrWS7Xnlg:br77a79) ([raw file](https://github.com/starkware-libs/cairo/blob/fbcdccef1c123886c4d6bfe573f202c810e4ec68/crates/cairo-lang-sierra-generator/src/program_generator.rs#L159)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

won't the function call libfunc already catch this?
</blockquote></details>

There are rare cases in which there is no function call:

```
struct MyStruct {
}

foo(x: MyStruct) -> MyStruct {
   x
}
```

If `MyStruct` was not of size 0, then there would be `store_temp(x)` which will add `MyStruct`. But sine it's of size 0, then `foo` is empty and the Sierra code we get is invalid.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4571)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-generator/src/program_generator.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4571#-NlqfxzM7ZoYmAEKdKo7:-NlqplD375YWdgsicPy2:b-b3om81) ([raw file](https://github.com/starkware-libs/cairo/blob/fc475b9fe36b9227fc38a4c6a2a4ef47663e1a59/crates/cairo-lang-sierra-generator/src/program_generator.rs#L159)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

There are rare cases in which there is no function call:

```
struct MyStruct {
}

foo(x: MyStruct) -> MyStruct {
   x
}
```

If `MyStruct` was not of size 0, then there would be `store_temp(x)` which will add `MyStruct`. But sine it's of size 0, then `foo` is empty and the Sierra code we get is invalid.
</blockquote></details>

but in this case - if `foo` isn't called we won't need `MyStruct` - and if it is - the function call libfunc would have caught `MyStruct` usage.

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4571)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/program_generator.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4571#-NlqfxzM7ZoYmAEKdKo7:-NlqsTAn8UF8_fDfts7g:b-queizk) ([raw file](https://github.com/starkware-libs/cairo/blob/fc475b9fe36b9227fc38a4c6a2a4ef47663e1a59/crates/cairo-lang-sierra-generator/src/program_generator.rs#L159)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

but in this case - if `foo` isn't called we won't need `MyStruct` - and if it is - the function call libfunc would have caught `MyStruct` usage.
</blockquote></details>

Unless `foo` is marked as a required function that starts the DFS.
In particular, such code fails in the e2e test.
I can skip this PR, and avoid this problem in my e2e test if you think it's better.
WDYT?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4571)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-generator/src/program_generator.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4571#-NlqfxzM7ZoYmAEKdKo7:-Nlqtkiw3YO3wdoA0s4f:b-c9srx5) ([raw file](https://github.com/starkware-libs/cairo/blob/fc475b9fe36b9227fc38a4c6a2a4ef47663e1a59/crates/cairo-lang-sierra-generator/src/program_generator.rs#L159)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Unless `foo` is marked as a required function that starts the DFS.
In particular, such code fails in the e2e test.
I can skip this PR, and avoid this problem in my e2e test if you think it's better.
WDYT?
</blockquote></details>

it is ok - but doc it is only for code entrypoints (as this was what confused me)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4571)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4571)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/program_generator.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4571#-NlqfxzM7ZoYmAEKdKo7:-NlqyaZ-BW6PrpoK1GCS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fc475b9fe36b9227fc38a4c6a2a4ef47663e1a59/crates/cairo-lang-sierra-generator/src/program_generator.rs#L159)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it is ok - but doc it is only for code entrypoints (as this was what confused me)
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4571#-:-Nlr-fvPCxBCgxDpHh6T:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
