### PR TITLE
Add use star in parser.

### PR DESCRIPTION
**Pull request by Tomer-StarkWare**

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6558)* status: 2 of 9 files reviewed, 1 unresolved discussion (waiting on @orizi and @Tomer-StarkWare)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 602 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6558#-OAXSV0x3GYtvW8NUEE-:-OAXSV0x3GYtvW8NUEE0:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/386e23a811d412b4dee516a9e039035387212a85/crates/cairo-lang-parser/src/parser.rs#L602)):*
> ```XML
>             let star = self.parse_token::<TerminalMul>();
>             UsePathStar::new_green(self.db, star).into()
>         } else if let Ok(ident) = self.try_parse_identifier() {
> ```





_Suggestion:_
```XML
        match self.peek().kind {
        SyntaxKind::TerminalLBrace => {
            let lbrace = self.parse_token::<TerminalLBrace>();
            let items = UsePathList::new_green(self.db,
                    self.parse_separated_list::<
                        UsePath, TerminalComma, UsePathListElementOrSeparatorGreen
                    >(
                        Self::try_parse_use_path,
                        is_of_kind!(rbrace, module_item_kw),
                        "path segment",
                    ));
            let rbrace = self.parse_token::<TerminalRBrace>();
            UsePathMulti::new_green(self.db, lbrace, items, rbrace).into()
        } 
        SyntaxKind::TerminalMul => {
            let star = self.parse_token::<TerminalMul>();
            UsePathStar::new_green(self.db, star).into()
        } 
        _ => {
             if let Ok(ident) = self.try_parse_identifier() {
                 ...
                 }
        }
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6558)* status: 2 of 9 files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-defs/src/db.rs` line 776 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6558#-OAXQphx0tHFJeEMuwJ4:-OAXQphx0tHFJeEMuwJ5:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/386e23a811d412b4dee516a9e039035387212a85/crates/cairo-lang-defs/src/db.rs#L776)):*
> ```XML
>                 stack.extend(use_path.use_paths(db).elements(db).into_iter().rev())
>             }
>             ast::UsePath::Star(_) => todo!(),
> ```





_Suggestion:_
```XML
            ast::UsePath::Star(_) => todo!("Change function to collect and `star` use as well."),
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1027 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6558#-OAXRmbF1uCb1GwbHE3o:-OAXRmbF1uCb1GwbHE3p:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/386e23a811d412b4dee516a9e039035387212a85/crates/cairo-lang-formatter/src/formatter_impl.rs#L1027)):*
> ```XML
>         (UsePath::Leaf(_) | UsePath::Single(_) | UsePath::Star(_), UsePath::Multi(_)) => {
>             Ordering::Less
>         }
> ```





_Suggestion:_
```XML
        // Handling star to always be first.
        (UsePath::Star(_), UsePath::Star(_)) => Ordering::Equals,
        (UsePath::Star(_), _) => Ordering::Greater,
        (_, UsePath::Star(_)) => Ordering::Less,
        // Case for multi vs non-multi: multi paths are always ordered before non-multi paths.
        (UsePath::Multi(_), UsePath::Leaf(_) | UsePath::Single(_) | UsePath::Star(_)) => {
            Ordering::Greater
        }
        (UsePath::Leaf(_) | UsePath::Single(_) | UsePath::Star(_), UsePath::Multi(_)) => {
            Ordering::Less
        }
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1120 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6558#-OAXSiovC7-eyYdmHNSZ:-OAXSiovC7-eyYdmHNS_:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/386e23a811d412b4dee516a9e039035387212a85/crates/cairo-lang-formatter/src/formatter_impl.rs#L1120)):*
> ```XML
>         }
>     }
> }
> ```





_Suggestion:_
```XML
        }
    }
}
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1134 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6558#-OAXR6pyCSOL6b7g1L6Q:-OAXR6pz1RxfJnfTD3AP:b-q8j9vk) ([raw file](https://github.com/starkware-libs/cairo/blob/386e23a811d412b4dee516a9e039035387212a85/crates/cairo-lang-formatter/src/formatter_impl.rs#L1134)):*
> ```XML
>             Some(ast::UsePath::Multi(ast::UsePathMulti::from_syntax_node(db, node.clone())))
>         }
>         SyntaxKind::UsePathStar => todo!(),
> ```

this can be handled in this PR - as it is syntax level



_Suggestion:_
```XML
        SyntaxKind::UsePathStar => Some(ast::UsePath::Star(ast::UsePathStar::from_syntax_node(db, node.clone()))),
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1163 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6558#-OAXRWn72nkgiJS5ytvz:-OAXRWn72nkgiJS5ytw-:bs3ummb) ([raw file](https://github.com/starkware-libs/cairo/blob/386e23a811d412b4dee516a9e039035387212a85/crates/cairo-lang-formatter/src/formatter_impl.rs#L1163)):*
> ```XML
>         UsePath::Multi(_) => None,
>         UsePath::Star(_) => todo!(),
>     }
> ```

function is deleted on rebase.



_Code quote:_
```XML
                .cloned(),
            UsePath::Star(_) => todo!(),
        },
        UsePath::Multi(_) => None,
        UsePath::Star(_) => todo!(),
    }
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6558)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/items/us.rs` line 70 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6558#-OAXUG1bCQVPMzURyF_M:-OAXUG1bCQVPMzURyF_N:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/386e23a811d412b4dee516a9e039035387212a85/crates/cairo-lang-semantic/src/items/us.rs#L70)):*
> ```XML
>             panic!("Only `UsePathLeaf` and `UsePathSingle` are supported.")
>         }
>         ast::UsePath::Star(_) => todo!(),
> ```





_Suggestion:_
```XML
        ast::UsePath::Multi(_) | ast::UsePath::Star(_) => {
            panic!("Only `UsePathLeaf` and `UsePathSingle` are supported.")
        }
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6558)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-defs/src/db.rs` line 776 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6558#-OAXQphx0tHFJeEMuwJ4:-OAXY7jv3oVFRIw5PJRR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/386e23a811d412b4dee516a9e039035387212a85/crates/cairo-lang-defs/src/db.rs#L776)):*
> ```XML
>                 stack.extend(use_path.use_paths(db).elements(db).into_iter().rev())
>             }
>             ast::UsePath::Star(_) => todo!(),
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/items/us.rs` line 70 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6558#-OAXUG1bCQVPMzURyF_M:-OAX_z9X5n_hASoyfi2V:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/386e23a811d412b4dee516a9e039035387212a85/crates/cairo-lang-semantic/src/items/us.rs#L70)):*
> ```XML
>             panic!("Only `UsePathLeaf` and `UsePathSingle` are supported.")
>         }
>         ast::UsePath::Star(_) => todo!(),
> ```

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6558)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Tomer-StarkWare)

**Pull request merged**
