### PR TITLE
Removed various TODOs.

### PR DESCRIPTION
**Pull request by orizi**
Added some additional boolean libfuncs tests.

commit-id:dd9081ed

---

**Stack**:
- #1617
- #1616
- #1615
- #1612 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1612#-:-NKn-sYh32I_8QdeJI7G:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`corelib/lib.cairo` line 11 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1612#-NKn-VRH6xLZz2Wh679T:-NKn-VRH6xLZz2Wh679U:b9045gs) ([raw file](https://github.com/starkware-libs/cairo/blob/b41970ccd6dc55f55ee90f2b2eec08081701102e/corelib/lib.cairo#L11)):*
> ```Cairo
> 
> extern fn bool_and_impl(a: bool, b: bool) -> (bool,) implicits() nopanic;
> fn bool_and(a: bool, b: bool) -> bool implicits() nopanic {
> ```





_Code quote:_
```Cairo
extern fn bool_and_impl(a: bool, b: bool) -> (bool,) implicits() nopanic;
fn bool_and(a: bool, b: bool) -> bool implicits() nopanic {
    let (r,) = bool_and_impl(a, b);
```
___
*[`examples/fib_u128.cairo` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1612#-NKn-dZh7gowR4orxvm-:-NKn-dZiEbp2JEFanxRs:bu83ncb) ([raw file](https://github.com/starkware-libs/cairo/blob/b41970ccd6dc55f55ee90f2b2eec08081701102e/examples/fib_u128.cairo#L2)):*
> ```Cairo
> // Calculates fib...
> fn fib(a: u128, b: u128, n: u128) -> u128 implicits(RangeCheck) {
> ```

i trust that these todos are no longer relevant, don't understand why though

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1612)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @gilbens-starkware)

___
*[`corelib/lib.cairo` line 11 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1612#-NKn-VRH6xLZz2Wh679T:-NKn1ZTm-kikK4Rz2lb7:belpbtz) ([raw file](https://github.com/starkware-libs/cairo/blob/b2a1e7ff92986b668b01bf3273552408e942777a/corelib/lib.cairo#L11)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>


</blockquote></details>

we decided that since we'll have inlining - there's no reason to mark these specifically, and simply returning a tuple of bool also removes the auto-branching of the libfunc.
i'll add an attribute to auto generate such code for the future.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1612)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @gilbens-starkware)

___
*[`examples/fib_u128.cairo` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1612#-NKn-dZh7gowR4orxvm-:-NKn1ttR1jlWeQ_WNsLP:b-461w4h) ([raw file](https://github.com/starkware-libs/cairo/blob/b2a1e7ff92986b668b01bf3273552408e942777a/examples/fib_u128.cairo#L2)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

i trust that these todos are no longer relevant, don't understand why though
</blockquote></details>

because they were already done :)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1612)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`examples/fib_u128.cairo` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1612#-NKn-dZh7gowR4orxvm-:-NKn25Mr9VRZp9QCTe_C:bdbqon7) ([raw file](https://github.com/starkware-libs/cairo/blob/b2a1e7ff92986b668b01bf3273552408e942777a/examples/fib_u128.cairo#L2)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

because they were already done :)
</blockquote></details>

so the todod wasn't referring to the `match` statements that are still here?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1612)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

___
*[`examples/fib_u128.cairo` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1612#-NKn-dZh7gowR4orxvm-:-NKn2H4n8RMfCllm-XKv:b-3cslek) ([raw file](https://github.com/starkware-libs/cairo/blob/b2a1e7ff92986b668b01bf3273552408e942777a/examples/fib_u128.cairo#L2)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

so the todod wasn't referring to the `match` statements that are still here?
</blockquote></details>

indeed.

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1612)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
