### PR TITLE
Audit responses.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #5679
- #5651 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5651)

### CODE REVIEW

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5651)* status: 4 of 6 files reviewed, 6 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 247 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5651#-Nz2lAeOCd1wAHBHDw0L:-Nz2lAeOCd1wAHBHDw0M:b-h9jiit) ([raw file](https://github.com/starkware-libs/cairo/blob/6eae0019dd3812b7a74afcbfe5758572ebf40297/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L247)):*
> ```XML
>         require(q_max < u128_limit)?;
>         // `r` is range checked in all algorithm variants, so `rhs.upper` must be at most `2**128 +
>         // 1`.
> ```

(move line split if possible)



_Suggestion:_
```XML
        // `r` is range checked in all algorithm variants, so `rhs.upper` must be at most
        // `2**128 + 1`.
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 259 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5651#-Nz2lWRxDo3qZ5D3Aw08:-Nz2lWRxDo3qZ5D3Aw09:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6eae0019dd3812b7a74afcbfe5758572ebf40297/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L259)):*
> ```XML
>         if lhs_upper_sqrt.pow(2) != lhs.upper {
>             lhs_upper_sqrt += 1;
>         }
> ```





_Suggestion:_
```XML
        // Round lhs_upper_sqrt up.
        if lhs_upper_sqrt.pow(2) != lhs.upper {
            lhs_upper_sqrt += 1;
        }
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 262 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5651#-Nz2llJ01IxS9gq_SHna:-Nz2llJ01IxS9gq_SHnb:b8j6lgx) ([raw file](https://github.com/starkware-libs/cairo/blob/6eae0019dd3812b7a74afcbfe5758572ebf40297/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L262)):*
> ```XML
>         if &lhs_upper_sqrt * &u128_limit < prime {
>             // Since the value bounded by root is range checked.
>             require(lhs_upper_sqrt < u128_limit)?;
> ```

(alternatively, you can add it to the `if` condition)



_Suggestion:_
```XML
            // Make sure `lhs_upper_sqrt < 2**128`, since the value bounded by root is range checked.
            require(lhs_upper_sqrt < u128_limit)?;
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 288 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5651#-Nz2m483E-7Ah8eXXznG:-Nz2m483E-7Ah8eXXznH:bt7c8nr) ([raw file](https://github.com/starkware-libs/cairo/blob/7a39cafc6408a126c5caface92cd411c510da02a/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L288)):*
> ```XML
>             under_range.size() >= BigInt::one()
>                 && over_range.size() >= BigInt::one()
>                 && under_range.is_small_range()
> ```

You still need to check `is_small_range()`, right?
___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 355 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5651#-Nz2nOLX3xcyW8Uf62M3:-Nz2nOLX3xcyW8Uf62M4:bjzm8zc) ([raw file](https://github.com/starkware-libs/cairo/blob/6eae0019dd3812b7a74afcbfe5758572ebf40297/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L355)):*
> ```XML
>     );
>     Ok(LibfuncSignature::new_non_branch_ex(
>         vec![ParamSignature::new(lhs), ParamSignature::new(rhs).with_allow_const()],
> ```

Did you check that it works?
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 131 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5651#-Nz2q3pm7n4kjlrcPQhE:-Nz2q3pm7n4kjlrcPQhF:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6eae0019dd3812b7a74afcbfe5758572ebf40297/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L131)):*
> ```XML
>             casm_build_extend! {casm_builder,
>                 // q * b + r < min{q, b} * max{q, b} + 2**128 <=
>                 // root * 2**128 + 2**128 <= (root + 1) * 2**128 < prime.
> ```





_Suggestion:_
```XML
                // Note that for a honest prover, `min{q, b} < root`, as otherwise
                // `lhs_upper > a >= q * b >= root ** 2` (and on the other hand,
                // by the definition of `root`: `root ** 2 >= lhs_upper`).
                // Therefore we require `min{q, b} < root`, which guarantees that:
                //   q * b + r < min{q, b} * max{q, b} + 2**128 <=
                //   (root - 1) * 2**128 + 2**128 <= root * 2**128 < prime.
```

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5651)* status: 5 of 6 files reviewed, 7 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/test/integer_test.cairo` line 2079 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5651#-Nz2s4ww-4M5yVeVVkr8:-Nz2s4ww-4M5yVeVVkr9:b-2dfqax) ([raw file](https://github.com/starkware-libs/cairo/blob/5cd101e0f2fb5ea6db4fcaa08acc8ead3440e14f/corelib/src/test/integer_test.cairo#L2079)):*
> ```Cairo
>         helpers::DivRemResImpl<POW_2_251, U128_MAX, POW_2_123, { U128_MAX - 1 }>;
> 
>     type MaxRootLhs =
> ```

```
// Test an extreme case where BoundedIntDivRemAlgorithm::KnownSmallLhs is used,
// and `min{b, q} = lhs_upper_sqrt - 1`.
```

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5651)* status: 5 of 6 files reviewed, 8 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs` line 216 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5651#-Nz2tgro1lK5D2l5bl7n:-Nz2tgro1lK5D2l5bl7o:b-28h8ad) ([raw file](https://github.com/starkware-libs/cairo/blob/5cd101e0f2fb5ea6db4fcaa08acc8ead3440e14f/crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs#L216)):*
> ```XML
>             vec![OutputVarInfo {
>                 ty: context.get_concrete_type(Sha256StateHandleType::id(), &[])?,
>                 ref_info: OutputVarReferenceInfo::SimpleDerefs,
> ```

`with_allow_all` doesn't work with `SimpleDerefs`.

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5651)* status: all files reviewed, 8 unresolved discussions (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5651)* status: all files reviewed, 8 unresolved discussions (waiting on @liorgold2)

___
*[`corelib/src/test/integer_test.cairo` line 2079 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5651#-Nz2s4ww-4M5yVeVVkr8:-Nz2uMYX-C3gojTnlIWJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5cd101e0f2fb5ea6db4fcaa08acc8ead3440e14f/corelib/src/test/integer_test.cairo#L2079)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

```
// Test an extreme case where BoundedIntDivRemAlgorithm::KnownSmallLhs is used,
// and `min{b, q} = lhs_upper_sqrt - 1`.
```
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 247 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5651#-Nz2lAeOCd1wAHBHDw0L:-Nz2uW_A6_i9h85KS_Si:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5cd101e0f2fb5ea6db4fcaa08acc8ead3440e14f/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L247)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

(move line split if possible)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 259 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5651#-Nz2lWRxDo3qZ5D3Aw08:-Nz2uf-W6EVVsmm9p7Kr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5cd101e0f2fb5ea6db4fcaa08acc8ead3440e14f/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L259)):*
> ```XML
>         if lhs_upper_sqrt.pow(2) != lhs.upper {
>             lhs_upper_sqrt += 1;
>         }
> ```

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 262 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5651#-Nz2llJ01IxS9gq_SHna:-Nz2ukfj1H_o3LVyg5vU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5cd101e0f2fb5ea6db4fcaa08acc8ead3440e14f/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L262)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

(alternatively, you can add it to the `if` condition)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 288 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5651#-Nz2m483E-7Ah8eXXznG:-Nz2v7YT7nya9Cl1mFK1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6835d674221b31eb70563b92cee945fde174f51b/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L288)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

You still need to check `is_small_range()`, right?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 355 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5651#-Nz2nOLX3xcyW8Uf62M3:-Nz2vywuCi31uUWInW7J:b2876op) ([raw file](https://github.com/starkware-libs/cairo/blob/5cd101e0f2fb5ea6db4fcaa08acc8ead3440e14f/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L355)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Did you check that it works?
</blockquote></details>

yes - added to the test.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs` line 216 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5651#-Nz2tgro1lK5D2l5bl7n:-Nz2w7YO-xk4JoY0_4Bx:bd6f4nu) ([raw file](https://github.com/starkware-libs/cairo/blob/5cd101e0f2fb5ea6db4fcaa08acc8ead3440e14f/crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs#L216)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

`with_allow_all` doesn't work with `SimpleDerefs`.
</blockquote></details>

moved to `Deferred(Generic)` instead.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 131 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5651#-Nz2q3pm7n4kjlrcPQhE:-Nz2xERX3L6jW9ce9ar6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5cd101e0f2fb5ea6db4fcaa08acc8ead3440e14f/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L131)):*
> ```XML
>             casm_build_extend! {casm_builder,
>                 // q * b + r < min{q, b} * max{q, b} + 2**128 <=
>                 // root * 2**128 + 2**128 <= (root + 1) * 2**128 < prime.
> ```

Done.

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 4 of 7 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5651)* status: 8 of 9 files reviewed, all discussions resolved

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5651#-:-NzRzR1rDTTvKVXLAxqx:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
