### PR TITLE
Derive events with member attributes

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2876)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2873** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2873" target="_blank">Graphite</a> 
    * **PR #2874** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2874" target="_blank">Graphite</a> 
      * **PR #2876** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2876" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2876?utm_source=stack-comment).

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2876)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 197 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2876#-NTNsm4f2rKz9xObf4fT:-NTNsm4f2rKz9xObf4fU:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ffa850f2361c2c0e355cc0f53599e16795186653/crates/cairo-lang-starknet/src/plugin/events.rs#L197)):*
> ```XML
>             "
>                 serde::Serde::serialize(
>                     ref values, $value$
> ```





_Suggestion:_
```XML
                serde::Serde::serialize(ref values, $value$);",
```
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/events` line 31 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2876#-NTNt-z59UoMVSwdb4Wx:-NTNt-z59UoMVSwdb4Wy:b-26iew) ([raw file](https://github.com/starkware-libs/cairo/blob/ffa850f2361c2c0e355cc0f53599e16795186653/crates/cairo-lang-starknet/src/plugin/plugin_test_data/events#L31)):*
> ```
>         self: MyEventStruct, ref keys: Array<felt252>, ref values: Array<felt252>
>     ) {
>                 serde::Serde::serialize(
> ```

can you make this well indented?



_Suggestion:_
```
    fn append_keys_and_values(
        self: MyEventStruct, ref keys: Array<felt252>, ref values: Array<felt252>
    ) {
        serde::Serde::serialize(ref values, self.x);
        serde::Serde::serialize(ref values, self.data);
    }
}
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2876)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/events` line 62 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2876#-NTNtFXf8DM1Juptj_py:-NTNtFXf8DM1Juptj_pz:btbr7fr) ([raw file](https://github.com/starkware-libs/cairo/blob/ffa850f2361c2c0e355cc0f53599e16795186653/crates/cairo-lang-starknet/src/plugin/plugin_test_data/events#L62)):*
> ```
>                 );
>             },
>             
> ```

make sure this is deleted



_Code quote:_
```
············
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2876)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2876)* status: all files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2876)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 197 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2876#-NTNsm4f2rKz9xObf4fT:-NTODIqF6yeG0mfQ2ede:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6c9cd1e4bda5102b26f805117d09d94c8c05c352/crates/cairo-lang-starknet/src/plugin/events.rs#L197)):*
> ```XML
>             "
>                 serde::Serde::serialize(
>                     ref values, $value$
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/events` line 31 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2876#-NTNt-z59UoMVSwdb4Wx:-NTO1Ui45PxiE11nD_ch:b2nhky0) ([raw file](https://github.com/starkware-libs/cairo/blob/6c9cd1e4bda5102b26f805117d09d94c8c05c352/crates/cairo-lang-starknet/src/plugin/plugin_test_data/events#L31)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can you make this well indented?
</blockquote></details>

No.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/events` line 62 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2876#-NTNtFXf8DM1Juptj_py:-NTODF4h2Sg6sDhpkK6p:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6c9cd1e4bda5102b26f805117d09d94c8c05c352/crates/cairo-lang-starknet/src/plugin/plugin_test_data/events#L62)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

make sure this is deleted
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2876)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2876#-:-NTOJqYR4AAFLFN5Oalp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
