### PR TITLE
Support types with interchangeable value in return_optimization.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4792)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 30 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4792)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/return_optimization.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4792#-No6AlzmDQJ_r_35w9xZ:-No6AlzmDQJ_r_35w9x_:b-9j5psq) ([raw file](https://github.com/starkware-libs/cairo/blob/c5cf6dcf0269539674e65f00ed315ace1508a6a6/crates/cairo-lang-lowering/src/optimizations/return_optimization.rs#L27)):*
> ```XML
>     if !lowered.blocks.is_empty() {
>         let unit_ty = semantic::corelib::unit_ty(db.upcast());
>         let tuple_with_unit = db.intern_type(semantic::TypeLongId::Tuple(vec![unit_ty]));
> ```

consider actually running something discovering all the unit equivalent types recursively.
Including user defined struct and addional recursion.
TODO OK.



_Code quote:_
```XML
        let unit_ty = semantic::corelib::unit_ty(db.upcast());
        let tuple_with_unit = db.intern_type(semantic::TypeLongId::Tuple(vec![unit_ty]));
```
___
*[`crates/cairo-lang-lowering/src/optimizations/return_optimization.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4792#-No6AfsG-GhHMRZBT5kZ:-No6AfsH3QNLVUcdf0e_:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c5cf6dcf0269539674e65f00ed315ace1508a6a6/crates/cairo-lang-lowering/src/optimizations/return_optimization.rs#L53)):*
> ```XML
> pub struct ReturnOptimizerContext<'a> {
>     lowered: &'a FlatLowered,
>     unitlike_types: HashSet<semantic::TypeId>,
> ```





_Suggestion:_
```XML
    unitlike_types: UnorderedHashSet<semantic::TypeId>,
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/return_optimization.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4792#-No6AlzmDQJ_r_35w9xZ:-No6EVV6BGOfd18kDl3u:b-yunywh) ([raw file](https://github.com/starkware-libs/cairo/blob/c5cf6dcf0269539674e65f00ed315ace1508a6a6/crates/cairo-lang-lowering/src/optimizations/return_optimization.rs#L27)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

consider actually running something discovering all the unit equivalent types recursively.
Including user defined struct and addional recursion.
TODO OK.
</blockquote></details>

I refactor the code to make it easier to support user types.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4792)* status: 29 of 30 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/return_optimization.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4792#-No6AfsG-GhHMRZBT5kZ:-No6EUeZ7_zH9L7VLyWg:brpmqc3) ([raw file](https://github.com/starkware-libs/cairo/blob/c5cf6dcf0269539674e65f00ed315ace1508a6a6/crates/cairo-lang-lowering/src/optimizations/return_optimization.rs#L53)):*
> ```XML
> pub struct ReturnOptimizerContext<'a> {
>     lowered: &'a FlatLowered,
>     unitlike_types: HashSet<semantic::TypeId>,
> ```

removed.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4792#-:-No6F27uBHXbM2L6Z_B5:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4792)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4792)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
