### PR TITLE
Fix cairo test CI script.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2392)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2392)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`scripts/cairo_test.sh` line 4 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2392#-NPv9Puf0APT5DDvPats:-NPv9Puf0APT5DDvPatt:b-diip7u) ([raw file](https://github.com/starkware-libs/cairo/blob/a98a95a7b51cbe47d91747ab0b8f6fa7e481a2ea/scripts/cairo_test.sh#L4)):*
> ```Shell
> 
> exit_code=0
> cargo +nightly-2022-11-03 run --bin cairo-test -- --path corelib/
> ```

why not



_Suggestion:_
```Shell
cargo +nightly-2022-11-03 run --bin cairo-test -- --path corelib/ && \
cargo +nightly-2022-11-03 run --bin cairo-test -- --path tests/bug_samples/ --starknet
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2392)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`scripts/cairo_test.sh` line 4 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2392#-NPv9Puf0APT5DDvPats:-NPvAR675Pro9dHX-eml:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a98a95a7b51cbe47d91747ab0b8f6fa7e481a2ea/scripts/cairo_test.sh#L4)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why not
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2392#-:-NPvAbzt-fJ-PghUUQ2_:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @gilbens-starkware)

**Comment by mkaput** [comment]
why not `set -euxo pipefail` ?

**Pull request merged**
