### PR TITLE
Made diagnostics be properly mapped on cfg rewrites.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3973)

### CODE REVIEW

**Review by yuvalsw — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3973)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3973#-NdVh9gQCL9LDe-4NZBp:-NdVh9gQCL9LDe-4NZBq:b-wkktci) ([raw file](https://github.com/starkware-libs/cairo/blob/6a8d5bbcb7084bccd51249299c62cc6363fc1362/crates/cairo-lang-plugins/src/plugins/config.rs#L46)):*
> ```XML
> }
> 
> /// Handle an item that is not dropped from the AST directly.
> ```

handle->handles. And "handles" in what way?
I don't understand the meaning of "directly" here.



_Code quote:_
```XML
from the AST directly.
```
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3973#-NdVh0UM6x_infcPEQim:-NdVh0UM6x_infcPEQin:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6a8d5bbcb7084bccd51249299c62cc6363fc1362/crates/cairo-lang-plugins/src/plugins/config.rs#L48)):*
> ```XML
> /// Handle an item that is not dropped from the AST directly.
> /// In case it includes a dropped elements and needs to be rewritten it returns the appropriate
> /// PatchBuilder. Otherwise returns `None`, and it won't be rewritten or dropped.
> ```





_Suggestion:_
```XML
/// In case it includes dropped elements and needs to be rewritten, it returns the appropriate
/// PatchBuilder. Otherwise returns `None`, and it won't be rewritten or dropped.
```
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3973#-NdViQR13sqbmfMjIJE7:-NdViQR13sqbmfMjIJE8:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6a8d5bbcb7084bccd51249299c62cc6363fc1362/crates/cairo-lang-plugins/src/plugins/config.rs#L94)):*
> ```XML
> }
> 
> /// Get the list of items that should be kept in the AST.
> ```





_Suggestion:_
```XML
// Gets the list o
```
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3973#-NdViZxD0Pr-Q5dUvMzs:-NdViZxD0Pr-Q5dUvMzt:b-6u0ffk) ([raw file](https://github.com/starkware-libs/cairo/blob/6a8d5bbcb7084bccd51249299c62cc6363fc1362/crates/cairo-lang-plugins/src/plugins/config.rs#L99)):*
> ```XML
>     db: &dyn SyntaxGroup,
>     cfg_set: &CfgSet,
>     all_items: Vec<Item>,
> ```

can this be change to:?



_Suggestion:_
```XML
all_items: &[Item],
```

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3973#-:-NdVjObX4nVHeSnt3HY6:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3973)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3973#-NdVh9gQCL9LDe-4NZBp:-NdZBB1j23ghhwLbnnxr:bthnnx2) ([raw file](https://github.com/starkware-libs/cairo/blob/2eb8e02e20f0115f2a9e702e657c364d8ce348cb/crates/cairo-lang-plugins/src/plugins/config.rs#L46)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

handle->handles. And "handles" in what way?
I don't understand the meaning of "directly" here.
</blockquote></details>

I mean fully dropped since does not match config.
updating.
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3973#-NdViZxD0Pr-Q5dUvMzs:-NdZBilwDZR30eJS0tBR:b-bgoxng) ([raw file](https://github.com/starkware-libs/cairo/blob/2eb8e02e20f0115f2a9e702e657c364d8ce348cb/crates/cairo-lang-plugins/src/plugins/config.rs#L99)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

can this be change to:?
</blockquote></details>

hmm - i guess we can, as we also transform the vector anyway.

**Review by yuvalsw — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3973)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
