### PR TITLE
Add loop syntax

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2599)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2599** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2599" target="_blank">Graphite</a>  👈
    * **PR #2600** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2600" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2599?utm_source=stack-comment).

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2599#-:-NRSv1Ki1L_88bcOWV7T:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-syntax-codegen/src/cairo_spec.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2599#-NRSuu4CBooVc4AujI1d:-NRSuu4CBooVc4AujI1e:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/12c72788c3e97beadf4456d461c6c0899d7d7f7b/crates/cairo-lang-syntax-codegen/src/cairo_spec.rs#L167)):*
> ```XML
>     )
>     .add_struct(StructBuilder::new("ExprLoop")
>         .node("loop_kw", "TerminalLoop")
> ```





_Suggestion:_
```XML
        .node_with_explicit_kind("If", "ExprIf")
    )
    .add_struct(StructBuilder::new("ExprLoop")
        .node("loop_kw", "TerminalLoop")
        .node("body", "ExprBlock")
    )
    .add_struct(StructBuilder::new("ElseClause")
```

**Comment by spapinistarkware** [comment]
@spapinistarkware queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2599).

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2599)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-syntax-codegen/src/cairo_spec.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2599#-NRSuu4CBooVc4AujI1d:-NRT67uh7JFWn31aIiGB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/12c72788c3e97beadf4456d461c6c0899d7d7f7b/crates/cairo-lang-syntax-codegen/src/cairo_spec.rs#L167)):*
> ```XML
>     )
>     .add_struct(StructBuilder::new("ExprLoop")
>         .node("loop_kw", "TerminalLoop")
> ```

Done.

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2599)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2599)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Comment by spapinistarkware** [comment]
[Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2599) failed to merge this pull request for an unknown reason. Try your merge again, or report a bug if you see this consistently.

**Comment by spapinistarkware** [comment]
@spapinistarkware queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2599).

**Comment by spapinistarkware** [comment]
[Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2599) failed to merge this pull request for an unknown reason. Try your merge again, or report a bug if you see this consistently.

**Comment by spapinistarkware** [comment]
@spapinistarkware queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2599).

**Comment by spapinistarkware** [comment]
[Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2599) failed to merge this pull request for an unknown reason. Try your merge again, or report a bug if you see this consistently.

**Comment by spapinistarkware** [comment]
@spapinistarkware queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2599).

**Comment by spapinistarkware** [comment]
[Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2599) failed to merge this pull request for an unknown reason. Try your merge again, or report a bug if you see this consistently.

**Pull request merged**
