### PR TITLE
Add ap tracking management to sierra gen.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2757)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2757)* status: 0 of 29 files reviewed, 1 unresolved discussion

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 393 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2757#-NSfF0d14XHjnIUQQFpb:-NSfF0d29ondSV114fQC:bc5im3b) ([raw file](https://github.com/starkware-libs/cairo/blob/f596ee1316582376fbe2a52de29d7a4bb3fae3c0/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L393)):*
> ```XML
> 
>         // TODO(ilya): Fix the following:
>         // let expected_ap_change = match metadata.ap_change_info.function_ap_change.get(&func.id) {
> ```

It seems that the metadata is wrong.



_Code quote:_
```XML
let expected_ap_change = match metadata.ap_change_info.function_ap_change.get(&func.id)
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2757)* status: 0 of 29 files reviewed, 1 unresolved discussion (waiting on @liorgold2, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 393 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2757#-NSfF0d14XHjnIUQQFpb:-NSgPEUo0dTI_69ALlkh:b-ifjga6) ([raw file](https://github.com/starkware-libs/cairo/blob/f596ee1316582376fbe2a52de29d7a4bb3fae3c0/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L393)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

It seems that the metadata is wrong.
</blockquote></details>

Resolved by adding disable_ap_tracking before return statements.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/test_data/account.sierra` line 509 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2757#-NSh1B1n0rNh7LdJqq66:-NSt7hgr9bnGRObRcYiN:b3tih2l) ([raw file](https://github.com/starkware-libs/cairo/blob/74b40da0b4031442e818de4c6646b9b419565067/crates/cairo-lang-starknet/test_data/account.sierra#L509)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why are there changes not related to locals?
</blockquote></details>

What changes are unrelated?

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2757)* status: 9 of 29 files reviewed, 9 unresolved discussions (waiting on @ilyalesokhin-starkware, @liorgold2, and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/test_data/account.sierra` line 509 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2757#-NSh1B1n0rNh7LdJqq66:-NStBpxlAo3QYk-VA7NL:bjbwrj3) ([raw file](https://github.com/starkware-libs/cairo/blob/74b40da0b4031442e818de4c6646b9b419565067/crates/cairo-lang-starknet/test_data/account.sierra#L509)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

What changes are unrelated?
</blockquote></details>

probably some moved code on reviewable - recommented where i see it.
___
*[`crates/cairo-lang-starknet/test_data/account.sierra` line 550 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2757#-NStBl1-A0pLcOpuKY7L:-NStBl1-A0pLcOpuKY7M:b-2jwd8n) ([raw file](https://github.com/starkware-libs/cairo/blob/e06879f50a9959016eccd28289bd5b61c81a465a/crates/cairo-lang-starknet/test_data/account.sierra#L550)):*
> ```
> store_temp<EcOp>([33]) -> ([55]);
> store_temp<GasBuiltin>([34]) -> ([56]);
> store_temp<System>([35]) -> ([57]);
> ```

in relation to the previous comment - why all these lines were deleted?



_Code quote:_
```
enum_match<core::PanicResult::<(core::felt252,)>>([36]) { fallthrough([41]) 225([42]) };
branch_align() -> ();
struct_deconstruct<Tuple<felt252>>([41]) -> ([43]);
array_new<felt252>() -> ([44]);
store_temp<Array<felt252>>([44]) -> ([47]);
store_temp<felt252>([43]) -> ([48]);
function_call<user@core::serde::Felt252Serde::serialize>([47], [48]) -> ([45], [46]);
drop<Unit>([46]) -> ();
snapshot_take<Array<felt252>>([45]) -> ([49], [50]);
drop<Array<felt252>>([49]) -> ();
struct_construct<core::array::Span::<core::felt252>>([50]) -> ([51]);
struct_construct<Tuple<core::array::Span::<core::felt252>>>([51]) -> ([52]);
enum_init<core::PanicResult::<(core::array::Span::<core::felt252>,)>, 0>([52]) -> ([53]);
store_temp<RangeCheck>([32]) -> ([54]);
store_temp<EcOp>([33]) -> ([55]);
store_temp<GasBuiltin>([34]) -> ([56]);
store_temp<System>([35]) -> ([57]);
store_temp<core::PanicResult::<(core::array::Span::<core::felt252>,)>>([53]) -> ([58]);
return([54], [55], [56], [57], [58]);
branch_align() -> ();
enum_init<core::PanicResult::<(core::array::Span::<core::felt252>,)>, 1>([42]) -> ([59]);
store_temp<RangeCheck>([32]) -> ([60]);
store_temp<EcOp>([33]) -> ([61]);
store_temp<GasBuiltin>([34]) -> ([62]);
store_temp<System>([35]) -> ([63]);
store_temp<core::PanicResult::<(core::array::Span::<core::felt252>,)>>([59]) -> ([64]);
return([60], [61], [62], [63], [64]);
branch_align() -> ();
array_new<felt252>() -> ([65]);
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/test_data/account.sierra` line 550 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2757#-NStBl1-A0pLcOpuKY7L:-NStDss0BhiBmZvQewvl:b-l87pdk) ([raw file](https://github.com/starkware-libs/cairo/blob/e06879f50a9959016eccd28289bd5b61c81a465a/crates/cairo-lang-starknet/test_data/account.sierra#L550)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

in relation to the previous comment - why all these lines were deleted?
</blockquote></details>

They weren't deleted.

I don't know why the diff alignment is so bad.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/test_data/account.sierra` line 550 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2757#-NStBl1-A0pLcOpuKY7L:-NStEeCjDjkTPzPKH7YE:b-to6kc3) ([raw file](https://github.com/starkware-libs/cairo/blob/e06879f50a9959016eccd28289bd5b61c81a465a/crates/cairo-lang-starknet/test_data/account.sierra#L550)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

They weren't deleted.

I don't know why the diff alignment is so bad.
</blockquote></details>

If you replace

\[\d*\] -> \[*]
in vscode you get a much better diff.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2757)* status: 9 of 29 files reviewed, 9 unresolved discussions (waiting on @liorgold2, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-generator/src/ap_tracking.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2757#-NSh0UnF0I-d2kBK3yt-:-NStIhEK4k8RMHpeGWSX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f596ee1316582376fbe2a52de29d7a4bb3fae3c0/crates/cairo-lang-sierra-generator/src/ap_tracking.rs#L9)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc - especially context vs data
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/ap_tracking.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2757#-NSh0FF11-geDwo0X9cT:-NStM--c2tXu3KUXFBo2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f596ee1316582376fbe2a52de29d7a4bb3fae3c0/crates/cairo-lang-sierra-generator/src/ap_tracking.rs#L9)):*
> ```XML
> 
> #[derive(Default)]
> pub struct ApTrackingData {
> ```

Done.
___
*[`crates/cairo-lang-sierra-generator/src/ap_tracking.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2757#-NSh0KA14jVX2Kyq1buc:-NStIgyjDRyxLpSoKSk1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f596ee1316582376fbe2a52de29d7a4bb3fae3c0/crates/cairo-lang-sierra-generator/src/ap_tracking.rs#L17)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/ap_tracking.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2757#-NSh0OjW4b9GLQ3n2WRx:-NStLI_E4E-NKbq3fHlX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f596ee1316582376fbe2a52de29d7a4bb3fae3c0/crates/cairo-lang-sierra-generator/src/ap_tracking.rs#L45)):*
> ```XML
> }
> 
> pub struct ApTrackingContext {
> ```

Done.
___
*[`crates/cairo-lang-sierra-generator/src/ap_tracking.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2757#-NSh0ZSA6pHbFpl3-q1w:-NStLIoz0acNxamRm3EE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f596ee1316582376fbe2a52de29d7a4bb3fae3c0/crates/cairo-lang-sierra-generator/src/ap_tracking.rs#L45)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/ap_tracking.rs` line 54 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2757#-NSh0cUF-yOFO0xoXVtJ:-NStM1VPAOj-dwpXMUGP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f596ee1316582376fbe2a52de29d7a4bb3fae3c0/crates/cairo-lang-sierra-generator/src/ap_tracking.rs#L54)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc (vs info)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/test_data/account.sierra` line 509 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2757#-NSh1B1n0rNh7LdJqq66:-NStE6FUDyr6DaoNpIQ_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/74b40da0b4031442e818de4c6646b9b419565067/crates/cairo-lang-starknet/test_data/account.sierra#L509)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

probably some moved code on reviewable - recommented where i see it.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 28 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2757)* status: 11 of 29 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware, @liorgold2, and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-generator/src/ap_tracking.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2757#-NSh0UnF0I-d2kBK3yt-:-NStltXB0DmwpRvSMmOJ:b4ue4xd) ([raw file](https://github.com/starkware-libs/cairo/blob/f596ee1316582376fbe2a52de29d7a4bb3fae3c0/crates/cairo-lang-sierra-generator/src/ap_tracking.rs#L9)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

the doc helps - but not enough - you have 3 structs with basically the same name - you need to decide on the exact meaning of each struct and rename them.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/ap_tracking.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2757#-NSh0UnF0I-d2kBK3yt-:-NStrrzP459tqC8svVxa:b-629j0w) ([raw file](https://github.com/starkware-libs/cairo/blob/f596ee1316582376fbe2a52de29d7a4bb3fae3c0/crates/cairo-lang-sierra-generator/src/ap_tracking.rs#L9)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the doc helps - but not enough - you have 3 structs with basically the same name - you need to decide on the exact meaning of each struct and rename them.
</blockquote></details>

ApTrackingData is the only public once.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2757)* status: 11 of 29 files reviewed, 3 unresolved discussions (waiting on @liorgold2, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-generator/src/ap_tracking.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2757#-NSh0UnF0I-d2kBK3yt-:-NStsKNj9oleaik0NFNw:b-t3d1z7) ([raw file](https://github.com/starkware-libs/cairo/blob/f596ee1316582376fbe2a52de29d7a4bb3fae3c0/crates/cairo-lang-sierra-generator/src/ap_tracking.rs#L9)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

so add a less nice and longer name to the external ones
</blockquote></details>

I could call it
ApTrackingAnalysisResult,
but it is a bit strange to have

ApTrackingAnalysisResult in ExprGeneratorContext, no?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2757)* status: 11 of 29 files reviewed, 3 unresolved discussions (waiting on @liorgold2, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-generator/src/ap_tracking.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2757#-NSh0UnF0I-d2kBK3yt-:-NStsYkyCsqmrVv747Pb:b-on1hvz) ([raw file](https://github.com/starkware-libs/cairo/blob/f596ee1316582376fbe2a52de29d7a4bb3fae3c0/crates/cairo-lang-sierra-generator/src/ap_tracking.rs#L9)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I could call it
ApTrackingAnalysisResult,
but it is a bit strange to have

ApTrackingAnalysisResult in ExprGeneratorContext, no?
</blockquote></details>

I could call the other two

ApTrackingAnalysisContext
and
ApTrackingAnalysisInfo
if you think those are better.

**Review by orizi — COMMENTED** [review]
> Reviewed 6 of 28 files at r1, 12 of 14 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2757)* status: all files reviewed, 3 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2757)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware, @liorgold2, and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-generator/src/ap_tracking.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2757#-NSh0UnF0I-d2kBK3yt-:-NStt4fO2-qolvbT3ydm:b-g3jowh) ([raw file](https://github.com/starkware-libs/cairo/blob/f596ee1316582376fbe2a52de29d7a4bb3fae3c0/crates/cairo-lang-sierra-generator/src/ap_tracking.rs#L9)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I could call the other two

ApTrackingAnalysisContext
and
ApTrackingAnalysisInfo
if you think those are better.


</blockquote></details>

Adding Analysis is already much better

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2757)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-generator/src/ap_tracking.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2757#-NSh0UnF0I-d2kBK3yt-:-NStvDKx6d_ZoW8JPCTZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f596ee1316582376fbe2a52de29d7a4bb3fae3c0/crates/cairo-lang-sierra-generator/src/ap_tracking.rs#L9)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Adding Analysis is already much better
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/ap_tracking.rs` line 189 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2757#-NStvF2d4LD9bh4YCDei:-NStvF2d4LD9bh4YCDej:b4k0pde) ([raw file](https://github.com/starkware-libs/cairo/blob/782254c4ae9dda3284d7b140fbb912dce38e5215/crates/cairo-lang-sierra-generator/src/ap_tracking.rs#L189)):*
> ```XML
>         // Since the function has an unknown ap change we need to disable ap tracking
>         // before any return.
>         self.data.disable_ap_tracking.insert(block_id);
> ```

Where should I put the TODO?
is the suggestion below better?



_Suggestion:_
```XML
   
        // Since the function has an unknown ap change, we need to disable ap tracking
        // before any return.
        self.data.disable_ap_tracking.insert(block_id);
       // TODO(ilya): Consider removing the logic above as it adds Sierra statements.
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2757#-:-NSuvSmmDsP22piC158x:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @spapinistarkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 10 of 28 files at r1, 7 of 14 files at r3, 5 of 5 files at r5, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2757)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2 and @spapinistarkware)

**Pull request merged**
