### PR TITLE
Add `set_crate_config` to setup_test_crate.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4510)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/test_utils.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4510#-NkpMLlV4p6IR28GyaqC:-NkpMLlW4nYO19Gt1fk6:b-x1ku1p) ([raw file](https://github.com/starkware-libs/cairo/blob/9892f7e6826c5d204c8d1818a5bced669846da49/crates/cairo-lang-semantic/src/test_utils.rs#L136)):*
> ```XML
> 
>     // db.crate_configs(crate_id, Cr
>     db.set_crate_config(
> ```

this changes requires a mut db everywhere



_Code quote:_
```XML
 db.set_crate_config(
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/test_utils.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4510#-NkpMLlV4p6IR28GyaqC:-NktI2ZW8kIYtDutAzHs:bu37r9f) ([raw file](https://github.com/starkware-libs/cairo/blob/9892f7e6826c5d204c8d1818a5bced669846da49/crates/cairo-lang-semantic/src/test_utils.rs#L136)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

this changes requires a mut db everywhere
</blockquote></details>

It seems that I can't do it with parallel tests.

I get:



_Code snippet:_
```XML
thread 'test::lowering::error_propagate' panicked at 'increment_revision invoked during a query computation', /home/ilya/.cargo/registry/src/index.crates.io-6f17d22bba15001f/salsa-0.16.1/src/runtime.rs:273:13
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4510)* status: 1 of 21 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/test_utils.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4510#-NkpMLlV4p6IR28GyaqC:-NktMtTP31-ShJOF2vt3:bv8z3nl) ([raw file](https://github.com/starkware-libs/cairo/blob/9892f7e6826c5d204c8d1818a5bced669846da49/crates/cairo-lang-semantic/src/test_utils.rs#L136)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

It seems that I can't do it with parallel tests.

I get:
</blockquote></details>

since we use a shared db to make the tests run faster - it cannot have different inputs.
for this case we need to have a different precofigured crates per configuration (and just decide which crate to put new files in, when we compile an additional file).
or have a different db for each setup.
the first is probably better.

**Comment by ilyalesokhin-starkware** [comment]
Done in a better way in: #4513

**Pull request closed without merging**
