### PR TITLE
Added semantic model of impl types

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4719)

### CODE REVIEW

**Comment by yuvalsw** [comment]
change target branch

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4719)* status: all files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/lookup_item.rs` line 196 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4719#-NnDUZfOBqC5unC49Vpk:-NnDUZfOBqC5unC49Vpl:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7a28257521a503a744ceb4527cd3b8667d982e1b/crates/cairo-lang-semantic/src/lookup_item.rs#L196)):*
> ```XML
> impl HasResolverData for ImplFunctionId {
>     fn resolver_data(&self, db: &dyn SemanticGroup) -> Maybe<Arc<ResolverData>> {
>         db.impl_function_resolver_data(*self)
> ```





_Suggestion:_
```XML
impl HasResolverData for ImplTypeId {
    fn resolver_data(&self, db: &dyn SemanticGroup) -> Maybe<Arc<ResolverData>> {
        db.impl_type_resolver_data(*self)
    }
}

impl HasResolverData for ImplFunctionId {
    fn resolver_data(&self, db: &dyn SemanticGroup) -> Maybe<Arc<ResolverData>> {
        db.impl_function_resolver_data(*self)
```
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 520 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4719#-NnDTZVvAuPS47ltFRQ_:-NnDTZVw0a-u85uCQD-x:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7a28257521a503a744ceb4527cd3b8667d982e1b/crates/cairo-lang-semantic/src/items/imp.rs#L520)):*
> ```XML
> pub fn impl_type_by_trait_type(
>     db: &dyn SemanticGroup,
>     impl_def_id: ImplDefId,
> ```





_Suggestion:_
```XML
/// Query implementation of [crate::db::SemanticGroup::impl_types].
pub fn impl_types(
    db: &dyn SemanticGroup,
    impl_def_id: ImplDefId,
) -> Maybe<Arc<OrderedHashMap<ImplTypeId, ast::ItemTypeAlias>>> {
    Ok(db.priv_impl_definition_data(impl_def_id)?.item_type_asts)
}

/// Query implementation of [crate::db::SemanticGroup::impl_type_ids].
pub fn impl_type_ids(
    db: &dyn SemanticGroup,
    impl_def_id: ImplDefId,
) -> Maybe<Arc<Vec<ImplTypeId>>> {
    Ok(Arc::new(db.impl_types(impl_def_id)?.keys().copied().collect()))
}

/// Query implementation of [crate::db::SemanticGroup::impl_type_by_id].
pub fn impl_type_by_id(
    db: &dyn SemanticGroup,
    impl_type_id: ImplTypeId,
) -> Maybe<Option<ast::ItemTypeAlias>> {
    let impl_types = db.impl_types(impl_type_id.impl_def_id(db.upcast()))?;
    Ok(impl_types.get(&impl_type_id).cloned())
}

/// Query implementation of [crate::db::SemanticGroup::impl_type_by_trait_type].
pub fn impl_type_by_trait_type(
    db: &dyn SemanticGroup,
    impl_def_id: ImplDefId,
```
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1316 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4719#-NnDTnDl36tMEJwR0S-V:-NnDTnDl36tMEJwR0S-W:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/7a28257521a503a744ceb4527cd3b8667d982e1b/crates/cairo-lang-semantic/src/items/imp.rs#L1316)):*
> ```XML
> // // === Impl Item Type Assignment ===
> 
> // #[derive(Clone, Debug, PartialEq, Eq, DebugWithDb)]
> ```

?

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4719)* status: 11 of 13 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/lookup_item.rs` line 196 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4719#-NnDUZfOBqC5unC49Vpk:-NnDtMNfCxuMVmohDfqg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7a28257521a503a744ceb4527cd3b8667d982e1b/crates/cairo-lang-semantic/src/lookup_item.rs#L196)):*
> ```XML
> impl HasResolverData for ImplFunctionId {
>     fn resolver_data(&self, db: &dyn SemanticGroup) -> Maybe<Arc<ResolverData>> {
>         db.impl_function_resolver_data(*self)
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 520 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4719#-NnDTZVvAuPS47ltFRQ_:-NnDsvcd12kKuYsbRoho:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7a28257521a503a744ceb4527cd3b8667d982e1b/crates/cairo-lang-semantic/src/items/imp.rs#L520)):*
> ```XML
> pub fn impl_type_by_trait_type(
>     db: &dyn SemanticGroup,
>     impl_def_id: ImplDefId,
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1316 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4719#-NnDTnDl36tMEJwR0S-V:-NnDsgUU1MJv7Gn2MCfE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7a28257521a503a744ceb4527cd3b8667d982e1b/crates/cairo-lang-semantic/src/items/imp.rs#L1316)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4719#-:-NnDw6TkAB-39iNjleje:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4719)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
