### PR TITLE
Remove unnecessary drops from storage impls.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5952)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5952)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`corelib/src/starknet/storage.cairo` line 266 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5952#-O0t4O96909Sujm27s1c:-O0t4O96909Sujm27s1d:b-mtun4o) ([raw file](https://github.com/starkware-libs/cairo/blob/3ba88388aa620782553e591bda6323664eeba416/corelib/src/starknet/storage.cairo#L266)):*
> ```Cairo
>     +core::hash::Hash<EntryInfo::<T>::Key, StoragePathHashState>,
>     +starknet::Store<EntryInfo::<T>::Value>,
>     +Drop<EntryInfo::<T>::Key>,
> ```

this doesn't seem required as well.



_Code quote:_
```Cairo
    +Drop<EntryInfo::<T>::Key>,
```
___
*[`corelib/src/starknet/storage.cairo` line 298 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5952#-O0t4YHP6FiD4DixJJ2Q:-O0t4YHP6FiD4DixJJ2R:b-7ropln) ([raw file](https://github.com/starkware-libs/cairo/blob/3ba88388aa620782553e591bda6323664eeba416/corelib/src/starknet/storage.cairo#L298)):*
> ```Cairo
>     +core::hash::Hash<EntryInfo::<MutableTrait::<T>::InnerType>::Key, StoragePathHashState>,
>     +starknet::Store<EntryInfo::<MutableTrait::<T>::InnerType>::Value>,
>     +Drop<EntryInfo::<MutableTrait::<T>::InnerType>::Key>,
> ```

ditto



_Code quote:_
```Cairo
    +Drop<EntryInfo::<MutableTrait::<T>::InnerType>::Key>,
```
___
*[`corelib/src/starknet/storage.cairo` line 512 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5952#-O0t4aox-AI9MD8381H4:-O0t4aox-AI9MD8381H5:b-7ropln) ([raw file](https://github.com/starkware-libs/cairo/blob/3ba88388aa620782553e591bda6323664eeba416/corelib/src/starknet/storage.cairo#L512)):*
> ```Cairo
>     impl PointerImpl: StorageAsPointer<T>,
>     impl AccessImpl: StoragePointerReadAccess<StoragePointer0Offset<PointerImpl::Value>>,
>     +Drop<T>,
> ```

ditto



_Code quote:_
```Cairo
    +Drop<T>,
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5952)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/starknet/storage.cairo` line 266 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5952#-O0t4O96909Sujm27s1c:-O0t76ik1J1XUFbtSDQ5:b-1beo6) ([raw file](https://github.com/starkware-libs/cairo/blob/3ba88388aa620782553e591bda6323664eeba416/corelib/src/starknet/storage.cairo#L266)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this doesn't seem required as well.
</blockquote></details>

It is, the arg `key` is dropped in case of a panic.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5952)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`corelib/src/starknet/storage.cairo` line 266 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5952#-O0t4O96909Sujm27s1c:-O0t7TSJ6DVspzR2XzGY:b-tyosxi) ([raw file](https://github.com/starkware-libs/cairo/blob/3ba88388aa620782553e591bda6323664eeba416/corelib/src/starknet/storage.cairo#L266)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

It is, the arg `key` is dropped in case of a panic.
</blockquote></details>

the key is used in the first `.entry(key)` call.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5952)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/starknet/storage.cairo` line 266 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5952#-O0t4O96909Sujm27s1c:-O0tBMAm-Nkfc4rnWe5m:b-bejxps) ([raw file](https://github.com/starkware-libs/cairo/blob/3ba88388aa620782553e591bda6323664eeba416/corelib/src/starknet/storage.cairo#L266)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the key is used in the first `.entry(key)` call.
</blockquote></details>

You are of course correct. Done
___
*[`corelib/src/starknet/storage.cairo` line 298 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5952#-O0t4YHP6FiD4DixJJ2Q:-O0tBP999BUpmxStt9YX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3ba88388aa620782553e591bda6323664eeba416/corelib/src/starknet/storage.cairo#L298)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`corelib/src/starknet/storage.cairo` line 512 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5952#-O0t4aox-AI9MD8381H4:-O0tBPNdAjCZP8wGiOjV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3ba88388aa620782553e591bda6323664eeba416/corelib/src/starknet/storage.cairo#L512)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5952)* status: 2 of 11 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`corelib/src/starknet/storage.cairo` line 512 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5952#-O0t4aox-AI9MD8381H4:-O0tCL47Dv7cY30f92Xn:byw65y9) ([raw file](https://github.com/starkware-libs/cairo/blob/3ba88388aa620782553e591bda6323664eeba416/corelib/src/starknet/storage.cairo#L512)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

still here.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5952)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/starknet/storage.cairo` line 512 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5952#-O0t4aox-AI9MD8381H4:-O0wM8C96N1PbTWwEJ62:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3ba88388aa620782553e591bda6323664eeba416/corelib/src/starknet/storage.cairo#L512)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

still here.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5952#-:-O0wPj9x8XoRlDTREvbR:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
