### PR TITLE
Remove assert only hints.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2998)

### CODE REVIEW

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2998)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2998#-:-NUQ6el87-4z3W8YOR3U:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2998)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1137 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2998#-NUQGpph9LdrxivP3cM0:-NUQGpph9LdrxivP3cM1:brhumzt) ([raw file](https://github.com/starkware-libs/cairo/blob/32ac32d30082fbf58cf830e8a9e57ada6f819c89/crates/cairo-lang-runner/src/casm_run/mod.rs#L1137)):*
> ```XML
>             insert_value_to_cellref!(vm, next_key, dict_squash_exec_scope.current_key().unwrap())?;
>         }
>         CoreHint::AssertLtAssertValidInput { .. } => {}
> ```

Same here.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1188 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2998#-NUQGrl6-_FOqvFCkirz:-NUQGrl6-_FOqvFCkis-:brhumzt) ([raw file](https://github.com/starkware-libs/cairo/blob/32ac32d30082fbf58cf830e8a9e57ada6f819c89/crates/cairo-lang-runner/src/casm_run/mod.rs#L1188)):*
> ```XML
>             )?;
>         }
>         CoreHint::AssertLeAssertThirdArcExcluded => {}
> ```

Same here.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2998)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2998#-NUQGvRc-IX7EIF-WDaX:-NUQGvRc-IX7EIF-WDaY:b-zad8xp) (no related file):*
the e2e test file should change.

___

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2998)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2998)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @liorgold2)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2998#-NUQGvRc-IX7EIF-WDaX:-NUQIgyW0Q3y0QXqotSn:b-896fix) (no related file):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

the e2e test file should change.
</blockquote></details>

Done.



_Code quote (from crates/cairo-lang-runner/src/casm_run/mod.rs):_
```XML
 CoreHint::AssertLtAsse
```

___
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1137 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2998#-NUQGpph9LdrxivP3cM0:-NUQIhQx7oJeGPTVWvtB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/32ac32d30082fbf58cf830e8a9e57ada6f819c89/crates/cairo-lang-runner/src/casm_run/mod.rs#L1137)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1188 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2998#-NUQGrl6-_FOqvFCkirz:-NUQIhu81wEd7_hC-HPr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/32ac32d30082fbf58cf830e8a9e57ada6f819c89/crates/cairo-lang-runner/src/casm_run/mod.rs#L1188)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2998#-:-NUQMAY30zT-kZvBvZhR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
