### PR TITLE
Adding type info to felt252 serialization.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #3655
- #3654 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3654)

### CODE REVIEW

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3654#-:-N_3uV1S-8LkKfoc8Qex:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/felt252_serde.rs` line 437 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3654#-N_8c4erAxNZb-F7TZ50:-N_8c4erAxNZb-F7TZ51:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f290a220ac2b3214205f8ce3cc5913d1db7620a1/crates/cairo-lang-starknet/src/felt252_serde.rs#L437)):*
> ```XML
>         let decl_ti_value: u64 = match &self.declared_type_info {
>             Some(info) => {
>                 // Makes sure the type info value is not 0.
> ```





_Suggestion:_
```XML
   // The marker guarantees that the type info value is not 0.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/felt252_serde.rs` line 446 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3654#-N_8cNls3QK4-Ei_Yn4X:-N_8cNls3QK4-Ei_Yn4Y:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f290a220ac2b3214205f8ce3cc5913d1db7620a1/crates/cairo-lang-starknet/src/felt252_serde.rs#L446)):*
> ```XML
>             None => 0,
>         };
>         (BigInt::from(len) + BigInt::from(2u32).pow(128) * decl_ti_value).serialize(output)?;
> ```





_Suggestion:_
```XML
BigInt::from(decl_ti_value).shl(128)
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3654)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3654)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware, @ilyalesokhin-starkware, and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/felt252_serde.rs` line 437 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3654#-N_8c4erAxNZb-F7TZ50:-N_8elORA3-GLNlpYHkn:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f290a220ac2b3214205f8ce3cc5913d1db7620a1/crates/cairo-lang-starknet/src/felt252_serde.rs#L437)):*
> ```XML
>         let decl_ti_value: u64 = match &self.declared_type_info {
>             Some(info) => {
>                 // Makes sure the type info value is not 0.
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/felt252_serde.rs` line 446 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3654#-N_8cNls3QK4-Ei_Yn4X:-N_8ew9f7nGF6-qNljOQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f290a220ac2b3214205f8ce3cc5913d1db7620a1/crates/cairo-lang-starknet/src/felt252_serde.rs#L446)):*
> ```XML
>             None => 0,
>         };
>         (BigInt::from(len) + BigInt::from(2u32).pow(128) * decl_ti_value).serialize(output)?;
> ```

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3654#-:-N_8imGA56JU5c8fdLR9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
