### PR TITLE
Added bytes31 type

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3602)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 18 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3602)* status: 18 of 20 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/lib.cairo` line 319 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3602#-NZaX4VGBswKm0dwVj4B:-NZaX4VGBswKm0dwVj4C:binlkt4) ([raw file](https://github.com/starkware-libs/cairo/blob/68190ac2e2ef5b27dd113bc1478ace19e9c3a4ad/corelib/src/lib.cairo#L319)):*
> ```Cairo
> // bytes31.
> mod bytes_31;
> use bytes_31::{bytes31, bytes31_try_from_felt252, bytes31_to_felt252};
> ```

add the relevant TryInto and Into traits and only export them.



_Code quote:_
```Cairo
bytes31_try_from_felt252, bytes31_to_felt252
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned128.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3602#-NZai-bsE0o54eeuQfLW:-NZai-bsE0o54eeuQfLX:b-l6hdjr) ([raw file](https://github.com/starkware-libs/cairo/blob/68190ac2e2ef5b27dd113bc1478ace19e9c3a4ad/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned128.rs#L58)):*
> ```XML
>             jump NoOverflow if no_overflow != 0;
>             // Overflow:
>             // Here we know that 2**128 <= a + b < 2 * 2**128 - 1.
> ```

revert



_Code quote:_
```XML
 // Here we know that 2**128 <= a + b < 2 * 2**128 - 1.
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3602)* status: 18 of 20 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned128.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3602#-NZai-bsE0o54eeuQfLW:-NZb9tsW0QEYGJipSjw2:b-9v8oe3) ([raw file](https://github.com/starkware-libs/cairo/blob/68190ac2e2ef5b27dd113bc1478ace19e9c3a4ad/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned128.rs#L58)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

revert
</blockquote></details>

Why? This is a fix of the comment.

**Review by orizi — COMMENTED** [review]
> Reviewed 6 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3602)* status: 19 of 20 files reviewed, all discussions resolved

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned128.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3602#-NZai-bsE0o54eeuQfLW:-NZbvOtFCq3NqB-nyieF:bdeua48) ([raw file](https://github.com/starkware-libs/cairo/blob/68190ac2e2ef5b27dd113bc1478ace19e9c3a4ad/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned128.rs#L58)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Why? This is a fix of the comment.
</blockquote></details>

Oh - right, that is the very old fix we were discussing.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3602)* status: 18 of 20 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`corelib/src/test/bytes31_test.cairo` line 7 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3602#-NZeWDJ9DLs-QkpJVxJO:-NZeWDJ9DLs-QkpJVxJP:b-rkyezo) ([raw file](https://github.com/starkware-libs/cairo/blob/c0d911f909a0575f81ae60adfc7b1e5345058e62/corelib/src/test/bytes31_test.cairo#L7)):*
> ```Cairo
> #[test]
> fn test_bytes31_casts() {
>     let one_as_bytes31: Option<bytes31> = 1.try_into();
> ```

add tests for -1 and 0 as the other side of the spectrum.



_Code quote:_
```Cairo
    let one_as_bytes31: Option<bytes31> = 1.try_into();
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3602)* status: 19 of 20 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3602)* status: 19 of 20 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/test/bytes31_test.cairo` line 7 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3602#-NZeWDJ9DLs-QkpJVxJO:-NZeY9Bj-2anIA8FDdnv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c0d911f909a0575f81ae60adfc7b1e5345058e62/corelib/src/test/bytes31_test.cairo#L7)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add tests for -1 and 0 as the other side of the spectrum.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3602#-:-NZeYxtZ4F44N8EUmyFk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
