### PR TITLE
Added assert_{le, lt, ge, gt}

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3135)

### CODE REVIEW

**Comment by yuvalsw** [comment]
change target branch

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3135)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`corelib/src/lib.cairo` line 268 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3135#-NVekrWJ6XbNC9AT5M1J:-NVekrWJ6XbNC9AT5M1K:b78km5l) ([raw file](https://github.com/starkware-libs/cairo/blob/460ad28cf8742d356efd833841987604db06ef15/corelib/src/lib.cairo#L268)):*
> ```Cairo
>     if a > b {
>         panic_with_felt252(err_code)
>     }
> ```

why not?



_Suggestion:_
```Cairo
    assert(a > b, err_code)
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3135)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`corelib/src/lib.cairo` line 268 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3135#-NVekrWJ6XbNC9AT5M1J:-NVjW62p5jsOUMPj2eGA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/460ad28cf8742d356efd833841987604db06ef15/corelib/src/lib.cairo#L268)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why not?
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r6, 34 of 34 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3135#-:-NVjehgrA6i8caYyoUde:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
