### PR TITLE
Change array to queue.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2167)

### CODE REVIEW

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 84 of 84 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2167#-:-NOPQwbL1tc-xWQ1SGn8:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @spapinistarkware)

___
*[`tests/test_data/fib_queue.casm` line 238 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2167#-NOPQmYS3nwZe9F9ihTZ:-NOPQmYS3nwZe9F9ihT_:b2s2ria) ([raw file](https://github.com/starkware-libs/cairo/blob/0439c2d77f0cfad6a012b8879f72e0af89ddee22/tests/test_data/fib_queue.casm#L238)):*
> ```
> %{ memory[ap + 0] = segments.add() %}
> ap += 1;
> [ap + 0] = 1816587023098810795437523349031413646961304691, ap++;
> ```

What is this?

**Comment by mkaput** [comment]
May I ask why is this change happening?

**Review by gilbens-starkware — COMMENTED** [review]
Array implies a data structure capable of mutating any element in the array, not just appending to the end.
We want a name that better reflects the capabilities, and queue is the closest DS, although we allow accessing all the elements so it's not perfect.
We are open to suggestions for other names :)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2167#-:-NOPciCQ4KR6PDQ3RUXJ:b-vhg3is)* status: 68 of 84 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware and @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
> Reviewed 16 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2167)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Comment by mkaput** [comment]
Queue appends at the end and *pops at the front*. I think Array much better matches this behaviour and I believe that's a term used in Cairo0 ?

What about Vector or Table?

**Review by spapinistarkware — COMMENTED** [review]
We will also add the popfront thing in this type, it's possible. So, it *is* a Queue.
My worries are that users won't understand this is the preferred Builder for sequences.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2167#-:-NOQ8BohCULwxOLcGejF:b-9lj5ef)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Comment by mkaput** [comment]
_Sequence_ hmmmmmm

**Comment by spapinistarkware** [comment]
> _Sequence_ hmmmmmm

Maybe we can add to discussions?

**Pull request closed without merging**
