### PR TITLE
Support using interpolate_patched multiple times on the same builder.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1438)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1438)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1438#-NJtIfUI5KBLN_dA5LAI:-NJtIfUI5KBLN_dA5LAJ:b-x2wknm) (no related file):*
Please add a test for multiple interpolate_patched on the same builder.

___

**Comment by ilyalesokhin-starkware** [comment]
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Please add a test for multiple interpolate_patched on the same builder.
</blockquote></details>

I think it would just complicate the test without a good reason.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1438#-:-NJtXdn431yHKswcx1o2:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1438#-NJtIfUI5KBLN_dA5LAI:-NJtXPwH1TnPcVcXJ2Ay:b-sj36np) (no related file):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I think it would just complicate the test without a good reason.
</blockquote></details>

The description of the PR is that you allow this. It makes sense to test. But I see your point. Your call.

___

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1438#-:-NJtuExiDIrjo6D74f8r:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1438)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Pull request merged**
