### PR TITLE
Add storage ptr for simple storage members.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5378)

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5378)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`corelib/src/starknet/storage_access.cairo` line 820 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5378#-Nv199ub52GnCofldpt7:-Nv199uc7my50lwKgMZr:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b80ce8515b3120864a6e1bd7e072c217b666668b/corelib/src/starknet/storage_access.cairo#L820)):*
> ```Cairo
> }
> 
> /// A pointer to an address in storage, can be used to read and write values, if the generic type supports it (e.g. basic types like `felt252`). Or to generate a new address by hashing the current address and some value (e.g. a pointer to a LegacyMap, can be further hashed with the key to get the final address).
> ```





_Suggestion:_
```Cairo
/// A pointer to an address in storage, can be used to read and write values, if the generic type supports it (e.g. basic types like `felt252`).
```
___
*[`corelib/src/starknet/storage_access.cairo` line 831 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5378#-Nv19YbmCMTxJFyy3b5i:-Nv19YbmCMTxJFyy3b5j:bfz7e8e) ([raw file](https://github.com/starkware-libs/cairo/blob/b80ce8515b3120864a6e1bd7e072c217b666668b/corelib/src/starknet/storage_access.cairo#L831)):*
> ```Cairo
> pub struct StoragePath<T> {
>     pub hash_state: core::poseidon::HashState,
> }
> ```

Consider making this generic on a hash state instead.
Calling it generic and have a specific one based poseidon, and another specific called `Legacy` and based on pedersen.



_Code quote:_
```Cairo
/// An intermediate struct to store an hash state, in order to be able to hash multiple values and get the final address.
/// Storage path should have two interfaces, if T is storable then it should implement `StorageMember` in order to be able to get the address of the storage path, and if T is not storable then it should implement `StoragePathUpdate` in order to be able to update the hash state with another value.
#[derive(Copy, Drop)]
pub struct StoragePath<T> {
    pub hash_state: core::poseidon::HashState,
}
```
___
*[`corelib/src/starknet/storage_access.cairo` line 855 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5378#-Nv1A9IE0uxzmNi3_Xe5:-Nv1A9IE0uxzmNi3_Xe6:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b80ce8515b3120864a6e1bd7e072c217b666668b/corelib/src/starknet/storage_access.cairo#L855)):*
> ```Cairo
> trait StorageMember<TMemberState, T> {
>     // TODO(Gil): This is not used right now, consider removing.
>     fn base_address(self: @TMemberState) -> StorageBaseAddress;
> ```





_Suggestion:_
```Cairo
    // TODO(Gil): This is not used right now, consider removing.
    fn as_ptr(self: @TMemberState) -> StoragePointer;
```

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5378)* status: 0 of 20 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware)

___
*[`corelib/src/starknet/storage_access.cairo` line 832 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5378#-NvVJM1kDPXeWwIgD8dL:-NvVJM1kDPXeWwIgD8dM:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/febb01ca272083a23dd258d373d85fce50fa1d04/corelib/src/starknet/storage_access.cairo#L832)):*
> ```Cairo
> /// `StorageMember` in order to be able to get the address of the storage path, and if T is not
> /// storable then it should implement `StoragePathUpdate` in order to be able to update the hash
> /// state with another value.
> ```





_Suggestion:_
```Cairo
/// An intermediate struct to store a hash state, in order to be able to hash multiple values and
/// get the final address.
/// Storage path should have two interfaces, if T is storable then it should implement
/// `StorageMember` in order to be able to get the address of the storage path, and if T is not
/// storable then it should implement `StoragePathUpdate` in order to be able to update the hash
/// state with another value.
```
___
*[`corelib/src/starknet/storage_access.cairo` line 891 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5378#-NvVJyUU1DS0bJYT2ql-:-NvVJyUU1DS0bJYT2ql0:b-1rb53l) ([raw file](https://github.com/starkware-libs/cairo/blob/febb01ca272083a23dd258d373d85fce50fa1d04/corelib/src/starknet/storage_access.cairo#L891)):*
> ```Cairo
> /// A phantom type for storage maps, should only be used as a generic arg of StoragePath.
> // TODO(Gil): Introduce this type in the contract plugin to support ad-hoc shortcut functions.
> pub struct StorageMap<K, V> {}
> ```

this should be the type doc that is shown to the user - describe what a storage map means instead in the doc.



_Suggestion:_
```Cairo
///
#[phantom]
pub struct StorageMap<K, V> {}
```
___
*[`corelib/src/starknet/storage_access.cairo` line 902 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5378#-NvVKNTM-XfKV_MPm0Go:-NvVKNTM-XfKV_MPm0Gp:b-llpgqp) ([raw file](https://github.com/starkware-libs/cairo/blob/febb01ca272083a23dd258d373d85fce50fa1d04/corelib/src/starknet/storage_access.cairo#L902)):*
> ```Cairo
>         > { hash_state: Hash::<K, core::poseidon::HashState>::update_state(self.hash_state, key) }
>     }
> }
> ```

can  be generic on hash state as well - can't it?



_Code quote:_
```Cairo
impl StoragePathUpdateMap<
    K, V, +Hash<K, core::poseidon::HashState>
> of StoragePathUpdate<StorageMap<K, V>, K, V> {
    #[inline(always)]
    fn entry(self: StoragePath<StorageMap<K, V>>, key: K) -> StoragePath<V> {
        StoragePath::<
            V
        > { hash_state: Hash::<K, core::poseidon::HashState>::update_state(self.hash_state, key) }
    }
}
```
___
*[`crates/cairo-lang-starknet/src/plugin/storage_v2.rs` line 436 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5378#-Nv20R-U0iK4vsdJVDKV:-Nv20R-U0iK4vsdJVDKW:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/b80ce8515b3120864a6e1bd7e072c217b666668b/crates/cairo-lang-starknet/src/plugin/storage_v2.rs#L436)):*
> ```XML
>                 starknet::storage_access::storage_base_address_const::<{address}>()
>             }}
>             
> ```

.



_Suggestion:_
```XML
·
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5378)* status: 0 of 20 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/starknet/storage_access.cairo` line 855 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5378#-Nv1A9IE0uxzmNi3_Xe5:-Nv7LADg4Xhte65E2EAw:bcwvcmt) ([raw file](https://github.com/starkware-libs/cairo/blob/b80ce8515b3120864a6e1bd7e072c217b666668b/corelib/src/starknet/storage_access.cairo#L855)):*
> ```Cairo
> trait StorageMember<TMemberState, T> {
>     // TODO(Gil): This is not used right now, consider removing.
>     fn base_address(self: @TMemberState) -> StorageBaseAddress;
> ```

`as_ptr` is a "shortcut" as it is just for non map types.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5378)* status: 0 of 31 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/starknet/storage_access.cairo` line 832 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5378#-NvVJM1kDPXeWwIgD8dL:-NvWqYsS4aWCtzgOW599:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/febb01ca272083a23dd258d373d85fce50fa1d04/corelib/src/starknet/storage_access.cairo#L832)):*
> ```Cairo
> /// `StorageMember` in order to be able to get the address of the storage path, and if T is not
> /// storable then it should implement `StoragePathUpdate` in order to be able to update the hash
> /// state with another value.
> ```

Done.
___
*[`corelib/src/starknet/storage_access.cairo` line 891 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5378#-NvVJyUU1DS0bJYT2ql-:-NvWrFwICu5EiV4DyQbI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/febb01ca272083a23dd258d373d85fce50fa1d04/corelib/src/starknet/storage_access.cairo#L891)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this should be the type doc that is shown to the user - describe what a storage map means instead in the doc.
</blockquote></details>

Done.
___
*[`corelib/src/starknet/storage_access.cairo` line 902 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5378#-NvVKNTM-XfKV_MPm0Go:-NvWrzx79oNNsZG4lGLT:bqduqef) ([raw file](https://github.com/starkware-libs/cairo/blob/febb01ca272083a23dd258d373d85fce50fa1d04/corelib/src/starknet/storage_access.cairo#L902)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can  be generic on hash state as well - can't it?
</blockquote></details>

And the concrete hash will be specified by the plugin?
___
*[`crates/cairo-lang-starknet/src/plugin/storage_v2.rs` line 436 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5378#-Nv20R-U0iK4vsdJVDKV:-NvWs9KG603C6BGtyLDv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b80ce8515b3120864a6e1bd7e072c217b666668b/crates/cairo-lang-starknet/src/plugin/storage_v2.rs#L436)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 29 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5378)* status: 1 of 31 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware)

___
*[`corelib/src/starknet/storage.cairo` line 144 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5378#-Nv_xcM68Mi96043tjL1:-Nv_xcM68Mi96043tjL2:b-xk5ypw) ([raw file](https://github.com/starkware-libs/cairo/blob/8881cbdf4b5081ebf7a3fb88dcc4a38cc1ff386f/corelib/src/starknet/storage.cairo#L144)):*
> ```Cairo
> }
> 
> /// Trait for updating the hash state with a value. The implementation should be done for `Map`
> ```

should not be a part of the base PR.

Probably true for all path based parts.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5378)* status: 1 of 31 files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/starknet/storage.cairo` line 144 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5378#-Nv_xcM68Mi96043tjL1:-NvfdTTBEbvgTWkowORo:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8881cbdf4b5081ebf7a3fb88dcc4a38cc1ff386f/corelib/src/starknet/storage.cairo#L144)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

should not be a part of the base PR.

Probably true for all path based parts.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 16 files at r3, 4 of 29 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5378)* status: 7 of 31 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware)

___
*[`corelib/src/starknet/storage.cairo` line 89 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5378#-Nvfwa7l6AtLA6ef9fMM:-Nvfwa7m6Dlc6iuYqvOB:bery8ve) ([raw file](https://github.com/starkware-libs/cairo/blob/8dde90d64c2475a4efaa2ebaea89ad4179063cb7/corelib/src/starknet/storage.cairo#L89)):*
> ```Cairo
> pub trait StorageAsPointer<TMemberState, T> {
>     fn as_ptr(self: @TMemberState) -> StoragePointer<T>;
> }
> ```

add TODO



_Suggestion:_
```Cairo
pub trait StorageAsPointer<TMemberState, +MemberStateInfo<TMemberState>> {
    fn as_ptr(self: @TMemberState) -> StoragePointer<MemberStateInfo<TMemberState>::Value>;
}
```
___
*[`crates/cairo-lang-starknet/src/plugin/consts.rs` line 25 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5378#-Nvfyl0k7DME4FnQbPib:-Nvfyl0k7DME4FnQbPic:b-ynm0o8) ([raw file](https://github.com/starkware-libs/cairo/blob/8dde90d64c2475a4efaa2ebaea89ad4179063cb7/crates/cairo-lang-starknet/src/plugin/consts.rs#L25)):*
> ```XML
> pub const STORE_TRAIT: &str = "starknet::Store";
> pub const STORAGE_MEMBER_TRAIT: &str = "starknet::storage::StorageAsPath";
> pub const SIMPLE_STORAGE_MEMBER_TRAIT: &str = "starknet::storage::StorageAsPointer";
> ```

fix names
___
*[`crates/cairo-lang-starknet/src/plugin/storage.rs` line 378 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5378#-NvfytNE-zP_yBraDNsK:-NvfytNE-zP_yBraDNsL:b-68y2nc) ([raw file](https://github.com/starkware-libs/cairo/blob/8dde90d64c2475a4efaa2ebaea89ad4179063cb7/crates/cairo-lang-starknet/src/plugin/storage.rs#L378)):*
> ```XML
>         impl InternalPointerAccess{member_state_name}Impl of \
>                  {SIMPLE_STORAGE_MEMBER_TRAIT}<{member_state_name}, $type_path$> {{
>             fn as_ptr(self: @{member_state_name}) -> \
> ```

use it in the other generated code and check degradation. 
___
*[`crates/cairo-lang-starknet/src/plugin/test.rs` line 77 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5378#-NvfyzI12L9mv_9xTxB4:-NvfyzI12L9mv_9xTxB5:bk2hdtp) ([raw file](https://github.com/starkware-libs/cairo/blob/8dde90d64c2475a4efaa2ebaea89ad4179063cb7/crates/cairo-lang-starknet/src/plugin/test.rs#L77)):*
> ```XML
>         raw_output: "raw_output",
>         storage: "storage",
>         hello_starknet_storage_v2: "hello_starknet_storage_v2",
> ```

it is not v2 in any way.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 211 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5378#-NvfzR1W7Kb5fYIbjf4V:-NvfzR1W7Kb5fYIbjf4W:b-hfpv23) ([raw file](https://github.com/starkware-libs/cairo/blob/8dde90d64c2475a4efaa2ebaea89ad4179063cb7/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L211)):*
> ```XML
>                     StorageMapMemberAccessTrait, StorageMemberAccessTrait, 
>                     StorageAsPointer, StoragePointerAccess
>                 }};
> ```

remove.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5378)* status: 7 of 31 files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/starknet/storage.cairo` line 89 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5378#-Nvfwa7l6AtLA6ef9fMM:-NvkDxDy0jo1tZEttDuK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8dde90d64c2475a4efaa2ebaea89ad4179063cb7/corelib/src/starknet/storage.cairo#L89)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add TODO
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/consts.rs` line 25 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5378#-Nvfyl0k7DME4FnQbPib:-NvkEOIh-U8OKBHeLR22:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8dde90d64c2475a4efaa2ebaea89ad4179063cb7/crates/cairo-lang-starknet/src/plugin/consts.rs#L25)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix names
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 211 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5378#-NvfzR1W7Kb5fYIbjf4V:-NvkEv2LCbBkEmHPXIoq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8dde90d64c2475a4efaa2ebaea89ad4179063cb7/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L211)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove.
</blockquote></details>

Done.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5378)* status: 7 of 31 files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/storage.rs` line 378 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5378#-NvfytNE-zP_yBraDNsK:-NvlMPPo-metX8x-Rxdi:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8dde90d64c2475a4efaa2ebaea89ad4179063cb7/crates/cairo-lang-starknet/src/plugin/storage.rs#L378)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

use it in the other generated code and check degradation.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/test.rs` line 77 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5378#-NvfyzI12L9mv_9xTxB4:-NvlMPstExZSiWh-Zfa0:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8dde90d64c2475a4efaa2ebaea89ad4179063cb7/crates/cairo-lang-starknet/src/plugin/test.rs#L77)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it is not v2 in any way.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 24 of 24 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5378)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`-- commits` line 3 at r9](https://reviewable.io/reviews/starkware-libs/cairo/5378#-NvlTbNF3MtdY2D1PXne):*
squash.
___
*[`crates/cairo-lang-starknet/src/plugin/storage.rs` line 384 at r9](https://reviewable.io/reviews/starkware-libs/cairo/5378#-NvlVBJ02H-QPJw1lsIJ:-NvlVBJ02H-QPJw1lsIK:b-upq8dn) ([raw file](https://github.com/starkware-libs/cairo/blob/02cc2573fac06915472e6a3ab9b5e3b2fc512056/crates/cairo-lang-starknet/src/plugin/storage.rs#L384)):*
> ```XML
>                 }}
>             }}
>         }}
> ```

remove all the `\` and just add proper line breaks.



_Code quote:_
```XML
        impl InternalPointerAccess{member_state_name}Impl of \
                 {STORAGE_AS_POINTER_TRAIT}<{member_state_name}, $type_path$> {{
            fn as_ptr(self: @{member_state_name}) -> \
                 starknet::storage::StoragePointer<$type_path$> {{
                starknet::storage::StoragePointer{{address: \
                 Internal{member_state_name}Impl::address(self)
                }}
            }}
        }}
```
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 209 at r9](https://reviewable.io/reviews/starkware-libs/cairo/5378#-NvlUX750cpqwORdJ7QN:-NvlUX750cpqwORdJ7QO:b3kst) ([raw file](https://github.com/starkware-libs/cairo/blob/02cc2573fac06915472e6a3ab9b5e3b2fc512056/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L209)):*
> ```XML
>                 use starknet::storage::{{
>                     StorageMapMemberAddressTrait, StorageMemberAddressTrait,
>                     StorageMapMemberAccessTrait, StorageMemberAccessTrait, 
> ```

r

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5378)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`-- commits` line 3 at r9](https://reviewable.io/reviews/starkware-libs/cairo/5378#-NvlTbNF3MtdY2D1PXne):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

squash.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/storage.rs` line 384 at r9](https://reviewable.io/reviews/starkware-libs/cairo/5378#-NvlVBJ02H-QPJw1lsIJ:-NvlZjOw7R-MkptpBP84:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/02cc2573fac06915472e6a3ab9b5e3b2fc512056/crates/cairo-lang-starknet/src/plugin/storage.rs#L384)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove all the `\` and just add proper line breaks.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 209 at r9](https://reviewable.io/reviews/starkware-libs/cairo/5378#-NvlUX750cpqwORdJ7QN:-Nvl_7Da4oSmhsvZjNr_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/02cc2573fac06915472e6a3ab9b5e3b2fc512056/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L209)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

r
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 21 of 21 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5378#-:-Nvle8vR3ZiFVlACFb9h:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
