### PR TITLE
Changed order of casm contract check to catch more fine grained errors.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2381)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/casm_contract_class.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2381#-NPr1bFo7wS1ihhZXCXq:-NPr1bFo7wS1ihhZXCXr:b-gv6u9a) ([raw file](https://github.com/starkware-libs/cairo/blob/30f5b2226b144cf56eaaf50291e2149f14f6a99a/crates/cairo-lang-starknet/src/casm_contract_class.rs#L50)):*
> ```XML
>     #[error("{0} is not a supported builtin type.")]
>     InvalidBuiltinType(ConcreteTypeId),
>     #[error("Invalid entry point signature - builtins are not in the expected order.")]
> ```

What error are you going to return when there is an unknown implicit?



_Code quote:_
```XML
  #[error("Invalid entry point signature - builtins are not in the expected order.")]
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2381)* status: 0 of 1 files reviewed, all discussions resolved

___
*[`crates/cairo-lang-starknet/src/casm_contract_class.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2381#-NPr1bFo7wS1ihhZXCXq:-NPr1mmY8wWfy3A3pz2O:b2ni8w0) ([raw file](https://github.com/starkware-libs/cairo/blob/30f5b2226b144cf56eaaf50291e2149f14f6a99a/crates/cairo-lang-starknet/src/casm_contract_class.rs#L50)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

What error are you going to return when there is an unknown implicit?
</blockquote></details>

nvm

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2381#-:-NPr2Q-0-P6wfhPCEpLY:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2381)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
