### PR TITLE
Add lowering locations

### PR DESCRIPTION
**Pull request by spapinistarkware**
commit-id:ea9765d9

---

**Stack**:
- #1781
- #1778 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1778)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1778)* status: 13 of 15 files reviewed, 2 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1778#-NLuv3z97CoPqfvxxGmt:-NLz5ZBp3W5qPyZOd1N8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fb21a5d79114581bc798a16dd2e642c7a01c3b08/crates/cairo-lang-lowering/src/lower/context.rs#L121)):*
> ```XML
>         StableLocation::new(self.function_id.module_file_id(self.db.upcast()), stable_ptr)
>     }
> }
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1778#-NLuv2p-CNJnYSyjyV5e:-NLz5ZTIE5PZ3sImg8Kd:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fb21a5d79114581bc798a16dd2e642c7a01c3b08/crates/cairo-lang-lowering/src/lower/context.rs#L122)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1778)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1778)* status: 6 of 15 files reviewed, 10 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1778#-NLyxssC3fXqpBTeDUy5:-NLz964e56AOXQMTVYiB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fb21a5d79114581bc798a16dd2e642c7a01c3b08/crates/cairo-lang-lowering/src/lower/context.rs#L118)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/lower_if.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1778#-NLz0OAF6hX_0_1FVtFX:-NLzA8ln-bEpbMEgZ0Jw:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fb21a5d79114581bc798a16dd2e642c7a01c3b08/crates/cairo-lang-lowering/src/lower/lower_if.rs#L83)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

already defined, just clone it.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 297 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1778#-NLz5VGYAe27qSE1B0jz:-NLzAMlI6SYKkKMW3DFQ:bwygxsx) ([raw file](https://github.com/starkware-libs/cairo/blob/fb21a5d79114581bc798a16dd2e642c7a01c3b08/crates/cairo-lang-lowering/src/lower/mod.rs#L297)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

inline
</blockquote></details>

Noted.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 369 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1778#-NLz5eIK2hmSQ1TklG2C:-NLzARBI4bszIHsieu5Z:bwygxsx) ([raw file](https://github.com/starkware-libs/cairo/blob/fb21a5d79114581bc798a16dd2e642c7a01c3b08/crates/cairo-lang-lowering/src/lower/mod.rs#L369)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

define later, not relevant until line 394
</blockquote></details>

Noted.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 474 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1778#-NLz5zTc2LFa0HeRa0FQ:-NLzAZAL0YQYdcC0qvn7:bwygxsx) ([raw file](https://github.com/starkware-libs/cairo/blob/fb21a5d79114581bc798a16dd2e642c7a01c3b08/crates/cairo-lang-lowering/src/lower/mod.rs#L474)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

inline. This is only used in the end of the function
</blockquote></details>

Noted.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 624 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1778#-NLz6pGZ32_dPkBbMU-n:-NLzA_t9-3wxAvWcrCOz:bwygxsx) ([raw file](https://github.com/starkware-libs/cairo/blob/fb21a5d79114581bc798a16dd2e642c7a01c3b08/crates/cairo-lang-lowering/src/lower/mod.rs#L624)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

define later. not used until  653
</blockquote></details>

Noted.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 740 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1778#-NLz6xBE1bdKksN2ZZk8:-NLzAapz4fiR12IIr2k0:bwygxsx) ([raw file](https://github.com/starkware-libs/cairo/blob/fb21a5d79114581bc798a16dd2e642c7a01c3b08/crates/cairo-lang-lowering/src/lower/mod.rs#L740)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

inline
</blockquote></details>

Noted.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 758 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1778#-NLz6zLgDCowPdJNu9ST:-NLzAbXK-aMe7jLHDdYY:bwygxsx) ([raw file](https://github.com/starkware-libs/cairo/blob/fb21a5d79114581bc798a16dd2e642c7a01c3b08/crates/cairo-lang-lowering/src/lower/mod.rs#L758)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

inline
</blockquote></details>

Noted.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 793 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1778#-NLz75ZW1KjWXURX7mga:-NLzAcU-34vPopF9XMu8:bwygxsx) ([raw file](https://github.com/starkware-libs/cairo/blob/fb21a5d79114581bc798a16dd2e642c7a01c3b08/crates/cairo-lang-lowering/src/lower/mod.rs#L793)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

inline
</blockquote></details>

Noted.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 949 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1778#-NLz7PkrB4trSTbzKt6V:-NLzAdVh7IDPcKkmcunR:bwygxsx) ([raw file](https://github.com/starkware-libs/cairo/blob/fb21a5d79114581bc798a16dd2e642c7a01c3b08/crates/cairo-lang-lowering/src/lower/mod.rs#L949)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

inline
</blockquote></details>

Noted.

**Review by orizi — APPROVED** [review]
> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1778)* status: all files reviewed, 10 unresolved discussions (waiting on @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1778#-:-NLzJWyj33UxrxMbdXRe:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/generators.rs` line 116 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1778#-NLzIu399ZSE_gX-X4Jb:-NLzIu399ZSE_gX-X4Jc:b2ni8l0) ([raw file](https://github.com/starkware-libs/cairo/blob/8ea4a4987f5c2c00b9c1594e2dd04b161a7c1392/crates/cairo-lang-lowering/src/lower/generators.rs#L116)):*
> ```XML
>     /// Variable that holds the struct value.
>     pub input: VariableId,
>     /// Variable requests for the newly generated field values.
> ```

nit



_Suggestion:_
```XML
y generated member values
```

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 5 of 14 files at r1, 1 of 3 files at r2, 8 of 9 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1778)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
