### PR TITLE
Error when trying to cut Cairo release which would unsync from Scarb

### PR DESCRIPTION
**Pull request by mkaput**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4216)

### CODE REVIEW

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4216)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @orizi)

___
*[`scripts/bump_version.sh` line 44 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4216#-Nfzk1EDELP7T2M1z8MA:-Nfzk1EDELP7T2M1z8MB:bd435lw) ([raw file](https://github.com/starkware-libs/cairo/blob/11322fe386fda9d0bc23d8c0dd135be8eed0b9f6/scripts/bump_version.sh#L44)):*
> ```Shell
> 		echo "error: cairo $NEW_VERSION < scarb $latest_scarb_version"
> 		exit 1
> 	fi
> ```

FYI I reformatted this file with `shfmt` which prefers tabulators

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4216)* status: 0 of 1 files reviewed, all discussions resolved

___
*[`scripts/bump_version.sh` line 44 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4216#-Nfzk1EDELP7T2M1z8MA:-Ng2ZvGR8RY3bUGSmge8:b-f2vy38) ([raw file](https://github.com/starkware-libs/cairo/blob/11322fe386fda9d0bc23d8c0dd135be8eed0b9f6/scripts/bump_version.sh#L44)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

FYI I reformatted this file with `shfmt` which prefers tabulators
</blockquote></details>

can you `s/\t/    /g` on it so we'd remain consistent with the repo?

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4216)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @orizi)

___
*[`scripts/bump_version.sh` line 44 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4216#-Nfzk1EDELP7T2M1z8MA:-Ng30WTu65arSdkV111T:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/11322fe386fda9d0bc23d8c0dd135be8eed0b9f6/scripts/bump_version.sh#L44)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can you `s/\t/    /g` on it so we'd remain consistent with the repo?
</blockquote></details>

Done

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4216)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4216#-:-Ng3eHOR7ie0c78RloTe:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Pull request merged**
