### PR TITLE
Allow custom HintProcessor injection to cairo-lang-runner

### PR DESCRIPTION
**Pull request by MaksymilianDemitraszek**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3283)

### CODE REVIEW

**Comment by MaksymilianDemitraszek** [comment]
This PR will let protostar (and hopefully other tools) to use cairo-lang-runner as an extensible library.

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3283)* status: all files reviewed, 8 unresolved discussions (waiting on @MaksymilianDemitraszek)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 64 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3283#-NWqdk5B1TNBQ3V3_xE3:-NWqdk5C-uKUxtmCvJKY:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/52b79dc336f3789303eb16a46323811bdf80cd0e/crates/cairo-lang-runner/src/lib.rs#L64)):*
> ```XML
> }
> 
> /// The full result of a run with starknet state.
> ```





_Suggestion:_
```XML
Starknet
```
___
*[`crates/cairo-lang-runner/src/lib.rs` line 156 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3283#-NWqe3Gs8rcEVYmfilMV:-NWqe3Gs8rcEVYmfilMW:bia1bvd) ([raw file](https://github.com/starkware-libs/cairo/blob/52b79dc336f3789303eb16a46323811bdf80cd0e/crates/cairo-lang-runner/src/lib.rs#L156)):*
> ```XML
>             string_to_hint: HashMap::new(),
>         };
>         match self.run_function(func, args, available_gas, &mut hint_processor) {
> ```

https://doc.rust-lang.org/stable/std/result/enum.Result.html#method.map would be a bit more idiomatic here
___
*[`crates/cairo-lang-runner/src/lib.rs` line 175 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3283#-NWqeFU81F0h9rOi6laA:-NWqeFU81F0h9rOi6laB:b-cd227m) ([raw file](https://github.com/starkware-libs/cairo/blob/52b79dc336f3789303eb16a46323811bdf80cd0e/crates/cairo-lang-runner/src/lib.rs#L175)):*
> ```XML
>         args: &[Arg],
>         available_gas: Option<usize>,
>         hint_processor: &mut Processor,
> ```

This is quite a big function. I wonder if it wouldn't be more performant to accept `&mut dyn HintDictBuild + HintProcessor` here instead of being generic

**Review by mkaput — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3283)* status: all files reviewed, 7 unresolved discussions (waiting on @MaksymilianDemitraszek)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 175 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3283#-NWqeFU81F0h9rOi6laA:-NXErP-ABmaeicmvX1S8:b3afrz6) ([raw file](https://github.com/starkware-libs/cairo/blob/52b79dc336f3789303eb16a46323811bdf80cd0e/crates/cairo-lang-runner/src/lib.rs#L175)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

This is quite a big function. I wonder if it wouldn't be more performant to accept `&mut dyn HintDictBuild + HintProcessor` here instead of being generic
</blockquote></details>

OK, I see that you are basically forced to use generics here, because traits have generic methods. But I don't think they have to be employed here because it's just an iterator which I guess could just be a slice over instructions.... Topic for refactoring in future work IMHO

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3283#-:-NXF6S-y9Ki8K7ZooRJG:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @MaksymilianDemitraszek and @orizi)

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3283)* status: all files reviewed, 3 unresolved discussions (waiting on @MaksymilianDemitraszek)

**Review by MaksymilianDemitraszek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3283)* status: 4 of 7 files reviewed, 3 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 76 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3283#-NWqJVlC-Ni4AtgQaEhr:-NXss6eHC0IhI84b161-:b-l9ifv3) ([raw file](https://github.com/starkware-libs/cairo/blob/52b79dc336f3789303eb16a46323811bdf80cd0e/crates/cairo-lang-runner/src/casm_run/mod.rs#L76)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i don't understand the doc.
</blockquote></details>

As this trait was confusing and hard to explain I removed it entirely. Hope it simplifies things a bit

**Review by MaksymilianDemitraszek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3283)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1823 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3283#-NXGFYlcELRSSQFEVD_5:-NXssfCrDpufEJnCL6Yj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7b9ef2d0e096d1dc111a158f59c31d5c366cc15b/crates/cairo-lang-runner/src/casm_run/mod.rs#L1823)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by MaksymilianDemitraszek — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3283#-:-NXuCXjA-IW9tkTltnIW:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MaksymilianDemitraszek)

**Comment by MaksymilianDemitraszek** [comment]
@orizi I don't have write permissions to the repository, can you merge it?

**Pull request merged**
