### PR TITLE
LS: Proc macro handle responses

### PR DESCRIPTION
**Pull request by Draggu**
**Stack**:
- #6706
- #6705
- #6704 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by piotmag769 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6704#-:-OC917xC14rvCNFq5EOK:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/controller.rs` line 138 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6704#-OC919VtCCXnCJZjMK_a:-OC919VuEWmbEYpsn4MR:bwwvu10) ([raw file](https://github.com/starkware-libs/cairo/blob/7c79b401417a6c8fd3eda9e28dade1eea68ff099/crates/cairo-lang-language-server/src/lang/proc_macros/controller.rs#L138)):*
> ```XML
>             }
>             ClientStatus::Ready(client) => {
>                 // TODO we should check here if there are live snapshots, but no idea if it is
> ```

Maybe an issue for that?
___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/client/mod.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6704#-OC91V1n5-tD776Yzu-5:-OC91V1n5-tD776Yzu-6:b3hi3wg) ([raw file](https://github.com/starkware-libs/cairo/blob/7c79b401417a6c8fd3eda9e28dade1eea68ff099/crates/cairo-lang-language-server/src/lang/proc_macros/client/mod.rs#L78)):*
> ```XML
>         mut job: impl FnMut(RpcResponse, &mut FxHashMap<RequestId, RequestParams>),
>     ) {
>         let mut responses = self.connection.responses.lock().unwrap();
> ```

Now we don't need the drop I guess, but doesn't it hurt the performance?

**Review by Draggu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6704)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @integraledelebesgue, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/client/mod.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6704#-OC91V1n5-tD776Yzu-5:-OCDX1V-36tRGOLEBbAw:b-c6gtwz) ([raw file](https://github.com/starkware-libs/cairo/blob/7c79b401417a6c8fd3eda9e28dade1eea68ff099/crates/cairo-lang-language-server/src/lang/proc_macros/client/mod.rs#L78)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Now we don't need the drop I guess, but doesn't it hurt the performance?
</blockquote></details>

It is same order of locks that previously, only different abstraction.

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6704)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/controller.rs` line 138 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6704#-OC919VtCCXnCJZjMK_a:-OCI2AvmAPxVUk6COu97:b-7hbprb) ([raw file](https://github.com/starkware-libs/cairo/blob/7c79b401417a6c8fd3eda9e28dade1eea68ff099/crates/cairo-lang-language-server/src/lang/proc_macros/controller.rs#L138)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Maybe an issue for that?
</blockquote></details>

wdym?
___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/controller.rs` line 117 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6704#-OCI0v451ap3SbQ0_8Oc:-OCI0v451ap3SbQ0_8Od:bk2yxf2) ([raw file](https://github.com/starkware-libs/cairo/blob/09874f7bcb970db563a080650d190fa73b28c510/crates/cairo-lang-language-server/src/lang/proc_macros/controller.rs#L117)):*
> ```XML
>             }
>             ClientStatus::Ready(client) => {
>                 // TODO we should check here if there are live snapshots, but no idea if it is
> ```

use our standard TODO comment form
___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/controller.rs` line 120 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6704#-OCI376j23UgLI4TAAqN:-OCI376j23UgLI4TAAqO:b-g1zdbw) ([raw file](https://github.com/starkware-libs/cairo/blob/09874f7bcb970db563a080650d190fa73b28c510/crates/cairo-lang-language-server/src/lang/proc_macros/controller.rs#L120)):*
> ```XML
>                 // possible with salsa public api. if there are snapshots running we
>                 // can skip this job, this will lead to more updates at once later
>                 // and less cancellation.
> ```

I believe this could be doable by observing [salsa events](https://docs.rs/rust-analyzer-salsa/latest/salsa/trait.Database.html#method.salsa_event) and maintaining an atomic flag 
___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/controller.rs` line 200 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6704#-OCI3nx-7ebrQZBH1opM:-OCI3nx-7ebrQZBH1opN:b-hdn2wc) ([raw file](https://github.com/starkware-libs/cairo/blob/09874f7bcb970db563a080650d190fa73b28c510/crates/cairo-lang-language-server/src/lang/proc_macros/controller.rs#L200)):*
> ```XML
>                     error!("{error:#?}");
> 
>                     self.handle_error(db)
> ```

have you tested this case? won't you deadlock here?
___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/client/mod.rs` line 73 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6704#-OCI-mAY0NfJpgdIh_1J:-OCI-mAY0NfJpgdIh_1K:btazb9c) ([raw file](https://github.com/starkware-libs/cairo/blob/09874f7bcb970db563a080650d190fa73b28c510/crates/cairo-lang-language-server/src/lang/proc_macros/client/mod.rs#L73)):*
> ```XML
>     }
> 
>     /// Calls `job` for all available responses without waiting for new ones.
> ```

the fact that this function holds locks is pretty important I think, consider docing it

the question is: can't you just collect all things and collect them into a vector and return?

**Review by Arcticae — APPROVED** [review]
:lgtm: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6704#-:-OCIu5t-2M4zmUchmWgK:bg7igkv)* status: all files reviewed, 4 unresolved discussions (waiting on @Draggu, @integraledelebesgue, @orizi, and @piotmag769)

**Review by Draggu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6704)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @integraledelebesgue, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/controller.rs` line 117 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6704#-OCI0v451ap3SbQ0_8Oc:-OCJ4hNw-7a4_lqoopj3:b-ikos2o) ([raw file](https://github.com/starkware-libs/cairo/blob/09874f7bcb970db563a080650d190fa73b28c510/crates/cairo-lang-language-server/src/lang/proc_macros/controller.rs#L117)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

use our standard TODO comment form
</blockquote></details>

No more relevant.
___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/controller.rs` line 120 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6704#-OCI376j23UgLI4TAAqN:-OCJ43Ax-K2eFmbdiFCB:b6htsfh) ([raw file](https://github.com/starkware-libs/cairo/blob/09874f7bcb970db563a080650d190fa73b28c510/crates/cairo-lang-language-server/src/lang/proc_macros/controller.rs#L120)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I believe this could be doable by observing [salsa events](https://docs.rs/rust-analyzer-salsa/latest/salsa/trait.Database.html#method.salsa_event) and maintaining an atomic flag
</blockquote></details>

Events don't allow tracking if there is a snapshot alive, the only thing that could be used here is salsa internal arc counter, but it is not exposed. I think we can just ignore this now.
___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/controller.rs` line 200 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6704#-OCI3nx-7ebrQZBH1opM:-OCJ3dGM2eNUeQK8kBBE:bj7k46i) ([raw file](https://github.com/starkware-libs/cairo/blob/09874f7bcb970db563a080650d190fa73b28c510/crates/cairo-lang-language-server/src/lang/proc_macros/controller.rs#L200)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

have you tested this case? won't you deadlock here?
</blockquote></details>

Reworked, now will not deadlock.
___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/client/mod.rs` line 73 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6704#-OCI-mAY0NfJpgdIh_1J:-OCJ3kMq11RXosiMTZXz:b-ps2ffr) ([raw file](https://github.com/starkware-libs/cairo/blob/09874f7bcb970db563a080650d190fa73b28c510/crates/cairo-lang-language-server/src/lang/proc_macros/client/mod.rs#L73)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

the fact that this function holds locks is pretty important I think, consider docing it

the question is: can't you just collect all things and collect them into a vector and return?
</blockquote></details>

Can but don't see a need for this extra buffering. Done.

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6704#-:-OCXuCKwErJvY8Kmkfe9:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @integraledelebesgue, @orizi, and @piotmag769)

**Review by mkaput — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6704)* status: all files reviewed, 1 unresolved discussion (waiting on @integraledelebesgue, @orizi, and @piotmag769)

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6704)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
