### PR TITLE
Add Serde on EthAddress

### PR DESCRIPTION
**Pull request by gaetbout**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5158)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5158)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @gaetbout)

___
*[`corelib/src/starknet/eth_address.cairo` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5158#-Nrjut_dCe71qHa5iD1P:-Nrjut_e8AsaS6K2rm5A:b-3h7wke) ([raw file](https://github.com/starkware-libs/cairo/blob/abcf13c9aa2096a8c6ccf1011197700c81837da2/corelib/src/starknet/eth_address.cairo#L9)):*
> ```Cairo
> // An Ethereum address (160 bits).
> #[derive(Copy, Drop, Hash, PartialEq, Serde, starknet::Store)]
> pub struct EthAddress {
> ```

The default implementation is bad, as it won't make sure the inner value is valid.
Add a try-into based implementation instead.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5158)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @gaetbout)

___
*[`corelib/src/starknet/eth_address.cairo` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5158#-Nrjut_dCe71qHa5iD1P:-NrkFVie8lfkZ1S0DLsU:bvpzijm) ([raw file](https://github.com/starkware-libs/cairo/blob/abcf13c9aa2096a8c6ccf1011197700c81837da2/corelib/src/starknet/eth_address.cairo#L9)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

The default implementation is bad, as it won't make sure the inner value is valid.
Add a try-into based implementation instead.
</blockquote></details>

nm - it is already implemented.
please close this PR.

**Comment by gaetbout** [comment]
Thing is that I have an `EthAddress` that I'm trying to convert to `NonZero<EthAddress>`.
Both using `into()` or `try_into()` it doesn't work.
Although it works with u256, or felt252...
How should I proceed?

**Comment by orizi** [comment]
There is no such thing as a `NonZero<EthAddress>` - it is supported only for a select number of types.

**Comment by gaetbout** [comment]
What if I want to handle this type as a fn parameter?
I then have to manually make those checks (which is fine, just unexpected)

**Comment by orizi** [comment]
You'd need to test it, as there no NonZero support for it.

**Pull request closed without merging**
