### PR TITLE
chore: Add logo to Cairo 1 VSC Extension

### PR DESCRIPTION
**Pull request by TAdev0**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5766)

### CODE REVIEW

**Comment by mkaput** [comment]
This PR changes nothing, closing

**Comment by TAdev0** [comment]
Hi @mkaput , i'm working at Nethermind and I was asked to add a logo to the VSC extension. I saw there was a logo already in the package.json but no logo displays in the VSC marketplace

**Comment by TAdev0** [comment]
I tried changing with another one, i supposed there was maybe a display error related to the size of the file, maybe i'm missing something to make it work

**Comment by mkaput** [comment]
How are you testing your changes?

The only method I know that works is to build the extension manually and install it by sideloading (code —install-extension)

**Comment by TAdev0** [comment]
@mkaput  it is the first time i deal with logos and VSC extensions. I was indeed really unsure my PR would solve the issue. I'll try what you suggested. thanks a lot!

**Comment by TAdev0** [comment]
ok i just tested locally and it works ! The PR resolves the issue

Screenshot 2024-06-10 at 12 34 07

**Comment by TAdev0** [comment]
Screenshot 2024-06-10 at 12 37 03

works well for files as well

**Pull request closed without merging**
