### PR TITLE
Fix ABI format.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2238)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
old abi:

[
    {
        "members": [
            {
                "name": "index",
                "offset": 0,
                "type": "felt"
            },
            {
                "name": "values",
                "offset": 1,
                "type": "(x: felt, y: felt)"
            }
        ],
        "name": "IndexAndValues",
        "size": 3,
        "type": "struct"
    },
    {
        "members": [
            {
                "name": "key",
                "offset": 0,
                "type": "felt"
            },
            {
                "name": "value",
                "offset": 1,
                "type": "felt"
            }
        ],
        "name": "StorageCell",
        "size": 2,
        "type": "struct"
    },
    {
        "inputs": [
            {
                "name": "index",
                "type": "felt"
            },
            {
                "name": "diffs_len",
                "type": "felt"
            },
            {
                "name": "diffs",
                "type": "felt*"
            }
        ],
        "name": "advance_counter",
        "outputs": [],
        "type": "function"
    },
    {
        "inputs": [
            {
                "name": "address",
                "type": "felt"
            },
            {
                "name": "value",
                "type": "felt"
            }
        ],
        "name": "constructor",
        "outputs": [],
        "type": "constructor"
    },
    {
        "inputs": [
            {
                "name": "index_and_x",
                "type": "IndexAndValues"
            }
        ],
        "name": "xor_counters",
        "outputs": [],
        "type": "function"
    },
    {
        "inputs": [],
        "name": "foo",
        "outputs": [
            {
                "name": "res",
                "type": "felt"
            }
        ],
        "type": "function"
    },
    {
        "inputs": [],
        "name": "test_ec_op",
        "outputs": [],
        "type": "function"
    },
    {
        "inputs": [
            {
                "name": "address",
                "type": "felt"
            },
            {
                "name": "index_and_x",
                "type": "IndexAndValues"
            }
        ],
        "name": "call_xor_counters",
        "outputs": [],
        "type": "function"
    },
    {
        "inputs": [
            {
                "name": "index",
                "type": "felt"
            }
        ],
        "name": "add_signature_to_counters",
        "outputs": [],
        "type": "function"
    },
    {
        "inputs": [
            {
                "name": "address",
                "type": "felt"
            },
            {
                "name": "value",
                "type": "felt"
            }
        ],
        "name": "set_value",
        "outputs": [],
        "type": "function"
    },
    {
        "inputs": [
            {
                "name": "address",
                "type": "felt"
            }
        ],
        "name": "get_value",
        "outputs": [
            {
                "name": "res",
                "type": "felt"
            }
        ],
        "type": "function"
    },
    {
        "inputs": [],
        "name": "entry_point",
        "outputs": [],
        "type": "function"
    },
    {
        "inputs": [],
        "name": "test_builtins",
        "outputs": [
            {
                "name": "result",
                "type": "felt"
            }
        ],
        "type": "function"
    },
    {
        "inputs": [
            {
                "name": "to_address",
                "type": "felt"
            }
        ],
        "name": "send_message",
        "outputs": [],
        "type": "function"
    },
    {
        "inputs": [
            {
                "name": "keys_len",
                "type": "felt"
            },
            {
                "name": "keys",
                "type": "felt*"
            },
            {
                "name": "data_len",
                "type": "felt"
            },
            {
                "name": "data",
                "type": "felt*"
            }
        ],
        "name": "test_emit_event",
        "outputs": [],
        "type": "function"
    },
    {
        "data": [
            {
                "name": "storage_cells_len",
                "type": "felt"
            },
            {
                "name": "storage_cells",
                "type": "StorageCell*"
            }
        ],
        "keys": [],
        "name": "log_storage_cells",
        "type": "event"
    },
    {
        "inputs": [
            {
                "name": "storage_cells_len",
                "type": "felt"
            },
            {
                "name": "storage_cells",
                "type": "StorageCell*"
            }
        ],
        "name": "test_high_level_event",
        "outputs": [],
        "type": "function"
    },
    {
        "inputs": [
            {
                "name": "contract_address",
                "type": "felt"
            },
            {
                "name": "function_selector",
                "type": "felt"
            },
            {
                "name": "calldata_len",
                "type": "felt"
            },
            {
                "name": "calldata",
                "type": "felt*"
            }
        ],
        "name": "test_call_contract",
        "outputs": [],
        "type": "function"
    },
    {
        "inputs": [
            {
                "name": "class_hash",
                "type": "felt"
            },
            {
                "name": "contract_address_salt",
                "type": "felt"
            },
            {
                "name": "constructor_calldata_len",
                "type": "felt"
            },
            {
                "name": "constructor_calldata",
                "type": "felt*"
            }
        ],
        "name": "test_deploy",
        "outputs": [
            {
                "name": "contract_address",
                "type": "felt"
            }
        ],
        "type": "function"
    },
    {
        "inputs": [
            {
                "name": "class_hash",
                "type": "felt"
            },
            {
                "name": "contract_address_salt",
                "type": "felt"
            },
            {
                "name": "deploy_from_zero",
                "type": "felt"
            },
            {
                "name": "constructor_calldata_len",
                "type": "felt"
            },
            {
                "name": "constructor_calldata",
                "type": "felt*"
            },
            {
                "name": "key",
                "type": "felt"
            },
            {
                "name": "value",
                "type": "felt"
            }
        ],
        "name": "test_deploy_and_call",
        "outputs": [
            {
                "name": "contract_address",
                "type": "felt"
            }
        ],
        "type": "function"
    },
    {
        "inputs": [
            {
                "name": "from_address",
                "type": "felt"
            },
            {
                "name": "amount",
                "type": "felt"
            }
        ],
        "name": "deposit",
        "outputs": [],
        "type": "l1_handler"
    },
    {
        "inputs": [
            {
                "name": "expected_address",
                "type": "felt"
            }
        ],
        "name": "test_get_caller_address",
        "outputs": [],
        "type": "function"
    },
    {
        "inputs": [
            {
                "name": "expected_address",
                "type": "felt"
            }
        ],
        "name": "test_get_sequencer_address",
        "outputs": [],
        "type": "function"
    },
    {
        "inputs": [
            {
                "name": "expected_timestamp",
                "type": "felt"
            }
        ],
        "name": "test_get_block_timestamp",
        "outputs": [],
        "type": "function"
    },
    {
        "inputs": [
            {
                "name": "expected_address",
                "type": "felt"
            }
        ],
        "name": "test_get_contract_address",
        "outputs": [],
        "type": "function"
    },
    {
        "inputs": [
            {
                "name": "expected_block_number",
                "type": "felt"
            }
        ],
        "name": "test_get_block_number",
        "outputs": [],
        "type": "function"
    },
    {
        "inputs": [
            {
                "name": "other_contract_address",
                "type": "felt"
            },
            {
                "name": "address",
                "type": "felt"
            }
        ],
        "name": "test_call_storage_consistency",
        "outputs": [],
        "type": "function"
    },
    {
        "inputs": [
            {
                "name": "other_contract_address",
                "type": "felt"
            },
            {
                "name": "depth",
                "type": "felt"
            }
        ],
        "name": "test_re_entrance",
        "outputs": [],
        "type": "function"
    },
    {
        "inputs": [
            {
                "name": "value",
                "type": "felt"
            }
        ],
        "name": "add_value",
        "outputs": [],
        "type": "function"
    },
    {
        "inputs": [
            {
                "name": "self_address",
                "type": "felt"
            },
            {
                "name": "value",
                "type": "felt"
            }
        ],
        "name": "recursive_add_value",
        "outputs": [],
        "type": "function"
    },
    {
        "inputs": [
            {
                "name": "address",
                "type": "felt"
            }
        ],
        "name": "increase_value",
        "outputs": [],
        "type": "function"
    },
    {
        "inputs": [
            {
                "name": "self_address",
                "type": "felt"
            },
            {
                "name": "arr_len",
                "type": "felt"
            },
            {
                "name": "arr",
                "type": "felt*"
            }
        ],
        "name": "test_call_with_array",
        "outputs": [],
        "type": "function"
    },
    {
        "inputs": [
            {
                "name": "self_address",
                "type": "felt"
            },
            {
                "name": "arr_len",
                "type": "felt"
            },
            {
                "name": "arr",
                "type": "StorageCell*"
            }
        ],
        "name": "test_call_with_struct_array",
        "outputs": [],
        "type": "function"
    },
    {
        "inputs": [
            {
                "name": "class_hash",
                "type": "felt"
            }
        ],
        "name": "test_library_call_syntactic_sugar",
        "outputs": [],
        "type": "function"
    },
    {
        "inputs": [
            {
                "name": "expected_account_contract_address",
                "type": "felt"
            }
        ],
        "name": "test_get_tx_info",
        "outputs": [],
        "type": "function"
    },
    {
        "inputs": [
            {
                "name": "expected_version",
                "type": "felt"
            }
        ],
        "name": "test_tx_version",
        "outputs": [],
        "type": "function"
    },
    {
        "inputs": [
            {
                "name": "code_address",
                "type": "felt"
            },
            {
                "name": "selector",
                "type": "felt"
            },
            {
                "name": "calldata_len",
                "type": "felt"
            },
            {
                "name": "calldata",
                "type": "felt*"
            }
        ],
        "name": "test_delegate_call",
        "outputs": [
            {
                "name": "retdata_size",
                "type": "felt"
            },
            {
                "name": "retdata",
                "type": "felt*"
            }
        ],
        "type": "function"
    },
    {
        "inputs": [
            {
                "name": "class_hash",
                "type": "felt"
            },
            {
                "name": "selector",
                "type": "felt"
            },
            {
                "name": "calldata_len",
                "type": "felt"
            },
            {
                "name": "calldata",
                "type": "felt*"
            }
        ],
        "name": "test_library_call",
        "outputs": [
            {
                "name": "retdata_size",
                "type": "felt"
            },
            {
                "name": "retdata",
                "type": "felt*"
            }
        ],
        "type": "function"
    },
    {
        "inputs": [
            {
                "name": "class_hash",
                "type": "felt"
            },
            {
                "name": "selector",
                "type": "felt"
            },
            {
                "name": "calldata_len",
                "type": "felt"
            },
            {
                "name": "calldata",
                "type": "felt*"
            }
        ],
        "name": "test_library_call_l1_handler",
        "outputs": [],
        "type": "function"
    },
    {
        "inputs": [],
        "name": "test_count_actual_storage_changes",
        "outputs": [],
        "type": "function"
    },
    {
        "inputs": [
            {
                "name": "class_hash",
                "type": "felt"
            }
        ],
        "name": "test_replace_class",
        "outputs": [],
        "type": "function"
    }
]

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2238#-:-NOsJ_Ih-rCrIvlWp--g:bh9bykw)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @liorgold2, @orizi, @spapinistarkware, and @yuvalsw)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
soldity abi:
https://github.com/starkware-industries/starkware/blob/00231a766a6dde655afab59580f372a9ba75c5f0/src/starkware/solidity/public_abi/StarkExchange.abi#L3

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2238#-:-NOsJob76nfs0QPc4-bM:bu8tl8u)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @liorgold2, @orizi, @spapinistarkware, and @yuvalsw)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2238#-:-NOsLD9qCTZPg6AB_rgY:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware, @liorgold2, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2238#-NOsKh_u7TZ2Ux8egIMQ:-NOsKh_u7TZ2Ux8egIMR:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5c3493d60105de107355d56b19ac2f4009b6ec11/crates/cairo-lang-semantic/src/types.rs#L102)):*
> ```XML
>             if types.is_empty() {
>                 return true;
>             }
> ```





_Suggestion:_
```XML
        mathces!(db.lookup_intern_type(*self), TypeLongId::Tuple(types) if types.is_empty())
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2238)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2, @spapinistarkware, and @yuvalsw)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2238)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2, @spapinistarkware, and @yuvalsw)

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2238)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware, @liorgold2, and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 98 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2238#-NOznpHa8hzQ4Gevyhjl:-NOznpHa8hzQ4Gevyhjm:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d2cde0e1a704cb4402a2804124f3a630f2070d5a/crates/cairo-lang-semantic/src/types.rs#L98)):*
> ```XML
> 
>     /// Returns `true` if the type is `()`.
>     pub fn is_unit_type(&self, db: &dyn SemanticGroup) -> bool {
> ```





_Suggestion:_
```XML
is_unit(&s
```
___
*[`crates/cairo-lang-starknet/src/abi.rs` line 69 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2238#-NOzo2V84s4nQqzs99Uz:-NOzo2V84s4nQqzs99V-:b-ttmk9z) ([raw file](https://github.com/starkware-libs/cairo/blob/d2cde0e1a704cb4402a2804124f3a630f2070d5a/crates/cairo-lang-starknet/src/abi.rs#L69)):*
> ```XML
>                 vec![]
>             } else {
>                 vec![Output { name: "".into(), ty: signature.return_type.format(db) }]
> ```

what is this for?



_Code quote:_
```XML
name: "".into()
```
___
*[`crates/cairo-lang-starknet/src/plugin/consts.rs` line 11 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2238#-NOzoWV1EDhJmdEfpcW-:-NOzoWV1EDhJmdEfpcW0:b-at3h95) ([raw file](https://github.com/starkware-libs/cairo/blob/d2cde0e1a704cb4402a2804124f3a630f2070d5a/crates/cairo-lang-starknet/src/plugin/consts.rs#L11)):*
> ```XML
> pub(super) const ACCOUNT_CONTRACT_ATTR: &str = "account_contract";
> pub(super) const CONTRACT_ATTR: &str = "contract";
> pub const EXTERNAL_ATTR: &str = "external";
> ```

why did you remove "(super)"? Where else is it used?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2238)* status: all files reviewed, 3 unresolved discussions (waiting on @liorgold2, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 98 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2238#-NOznpHa8hzQ4Gevyhjl:-NPBK8A_7_d-KQOtyUox:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/d2cde0e1a704cb4402a2804124f3a630f2070d5a/crates/cairo-lang-semantic/src/types.rs#L98)):*
> ```XML
> 
>     /// Returns `true` if the type is `()`.
>     pub fn is_unit_type(&self, db: &dyn SemanticGroup) -> bool {
> ```

done
___
*[`crates/cairo-lang-starknet/src/abi.rs` line 69 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2238#-NOzo2V84s4nQqzs99Uz:-NPBJlo88kw3iH00FFgY:b-1w8ixd) ([raw file](https://github.com/starkware-libs/cairo/blob/d2cde0e1a704cb4402a2804124f3a630f2070d5a/crates/cairo-lang-starknet/src/abi.rs#L69)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

what is this for?
</blockquote></details>

Solidity and cairo 0 have named return types.
___
*[`crates/cairo-lang-starknet/src/abi_test.rs` line 17 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2238#-NPBKMxK7GLeH-a140xA:-NPBKMxK7GLeH-a140xB:b5qusnk) ([raw file](https://github.com/starkware-libs/cairo/blob/d2cde0e1a704cb4402a2804124f3a630f2070d5a/crates/cairo-lang-starknet/src/abi_test.rs#L17)):*
> ```XML
>         indoc! {"
>             trait MyAbi {
>                 fn foo(a: felt, b: u128) -> Option::<()>;
> ```

Do we want this function to appear in the ABI?
it has no attributes.



_Code quote:_
```XML
fn foo(a: felt, b: u128) -> Option::<()>;
```
___
*[`crates/cairo-lang-starknet/src/plugin/consts.rs` line 11 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2238#-NOzoWV1EDhJmdEfpcW-:-NPBKDVe5Wv6fHf1i0hP:b-81taoq) ([raw file](https://github.com/starkware-libs/cairo/blob/d2cde0e1a704cb4402a2804124f3a630f2070d5a/crates/cairo-lang-starknet/src/plugin/consts.rs#L11)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

why did you remove "(super)"? Where else is it used?
</blockquote></details>

reverted.

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2238)* status: 6 of 9 files reviewed, 3 unresolved discussions (waiting on @liorgold2, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 70 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2238#-NPBOMJOCi3vneUZ1H_p:-NPBOMJOCi3vneUZ1H_q:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ecf1c7d510834d2b783cb7af68ccf3ff4b6c940a/crates/cairo-lang-semantic/src/types.rs#L70)):*
> ```XML
>     fn option_from(other: TypeLongId) -> Option<Self> {
>         if let TypeLongId::Concrete(res) = other {
>             Some(res)
> ```





_Suggestion:_
```XML
        try_extract_matches!(other, TypeLongId::Concrete)
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2238)* status: 6 of 9 files reviewed, 3 unresolved discussions (waiting on @liorgold2, @orizi, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 70 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2238#-NPBOMJOCi3vneUZ1H_p:-NPDSEa8-Sa1qfFZiXlB:b-t5amts) ([raw file](https://github.com/starkware-libs/cairo/blob/ecf1c7d510834d2b783cb7af68ccf3ff4b6c940a/crates/cairo-lang-semantic/src/types.rs#L70)):*
> ```XML
>     fn option_from(other: TypeLongId) -> Option<Self> {
>         if let TypeLongId::Concrete(res) = other {
>             Some(res)
> ```

not related to the PR, but ok.



_Code quote:_
```XML
fn option_from(other: TypeLongId) -> Option<Self>
```

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 5 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2238)* status: all files reviewed, 3 unresolved discussions (waiting on @liorgold2, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 70 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2238#-NPBOMJOCi3vneUZ1H_p:-NPDZ7LZCFqGLWye0P1w:bbv826q) ([raw file](https://github.com/starkware-libs/cairo/blob/ecf1c7d510834d2b783cb7af68ccf3ff4b6c940a/crates/cairo-lang-semantic/src/types.rs#L70)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

not related to the PR, but ok.
</blockquote></details>

for some reason the pr changed this formatting - so it became related :\

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2238)* status: all files reviewed, 4 unresolved discussions (waiting on @liorgold2, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/abi_test.rs` line 62 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2238#-NPDg15p87WN0X6Yef1Q:-NPDg15q-qDP9PoQRvDF:bdiuln0) ([raw file](https://github.com/starkware-libs/cairo/blob/02af347c98905004263579e632188af7143e73ca/crates/cairo-lang-starknet/src/abi_test.rs#L62)):*
> ```XML
>               "outputs": [
>                 {
>                   "name": "",
> ```

@liorgold2 
Do we want name here?



_Code quote:_
```XML
"name": ""
```

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r4, 1 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2238)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware, @liorgold2, and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/abi.rs` line 69 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2238#-NOzo2V84s4nQqzs99Uz:-NPHhVQ03bBfRA_X_gmP:bvclfik) ([raw file](https://github.com/starkware-libs/cairo/blob/d2cde0e1a704cb4402a2804124f3a630f2070d5a/crates/cairo-lang-starknet/src/abi.rs#L69)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Solidity and cairo 0 have named return types.
</blockquote></details>

So we're going to keep it, always empty just for this?
___
*[`crates/cairo-lang-starknet/src/abi_test.rs` line 17 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2238#-NPBKMxK7GLeH-a140xA:-NPHrvo5Dt-qvdsGj18z:b-5515ln) ([raw file](https://github.com/starkware-libs/cairo/blob/d2cde0e1a704cb4402a2804124f3a630f2070d5a/crates/cairo-lang-starknet/src/abi_test.rs#L17)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Do we want this function to appear in the ABI?
it has no attributes.
</blockquote></details>

In a generated ABI there can't be such functions (without attributes) as they will not be generated unless marked as external/view/event.
I think that if someone writes such a function themselves in an ABI, it's OK to decide the default is external. It's also OK (maybe better) to generate a diagnostic and to make them explicitly specify the state_mutability.
___
*[`crates/cairo-lang-starknet/src/abi_test.rs` line 62 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2238#-NPDg15p87WN0X6Yef1Q:-NPHho3J8srhOJrewmvG:btq1c08) ([raw file](https://github.com/starkware-libs/cairo/blob/02af347c98905004263579e632188af7143e73ca/crates/cairo-lang-starknet/src/abi_test.rs#L62)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

@liorgold2 
Do we want name here?
</blockquote></details>

IMO no. The question is what are the implications re compatability with cairo0 and solidity.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2238)* status: all files reviewed, 4 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/abi.rs` line 69 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2238#-NPMt1JbA-dr9uoE6j_p:-NPMt1JbA-dr9uoE6j_q:b-9wybje) ([raw file](https://github.com/starkware-libs/cairo/blob/02af347c98905004263579e632188af7143e73ca/crates/cairo-lang-starknet/src/abi.rs#L69)):*
> ```XML
>                 vec![]
>             } else {
>                 vec![Output { name: "".into(), ty: signature.return_type.format(db) }]
> ```

Should we flatten tuples here?

e.g.
if signature.return_type is (felt, felt)
?



_Code quote:_
```XML
 vec![Output { name: "".into(), ty: signature.return_type.format(db) }]
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2238)* status: all files reviewed, 3 unresolved discussions (waiting on @liorgold2, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/abi.rs` line 69 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2238#-NOzo2V84s4nQqzs99Uz:-NPMtDETDtX5qlVmb5iG:bfuwu2o) ([raw file](https://github.com/starkware-libs/cairo/blob/d2cde0e1a704cb4402a2804124f3a630f2070d5a/crates/cairo-lang-starknet/src/abi.rs#L69)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

So we're going to keep it, always empty just for this?
</blockquote></details>

maybe we are going to support named tuple in the future?

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2238)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/abi_test.rs` line 62 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2238#-NPDg15p87WN0X6Yef1Q:-NPMhB2x8Xy4Quexj0RH:btg2up5) ([raw file](https://github.com/starkware-libs/cairo/blob/02af347c98905004263579e632188af7143e73ca/crates/cairo-lang-starknet/src/abi_test.rs#L62)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

IMO no. The question is what are the implications re compatability with cairo0 and solidity.
</blockquote></details>

We may have name in the future, once we support named tuples. I suggest removing the `name` property now, and possibly add this only in the case of named tuples (in the future).
In any case, if we decide to keep it, it should be `"name": null` instead of `"name": ""`,

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2238)* status: 1 of 9 files reviewed, 1 unresolved discussion (waiting on @orizi, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/abi_test.rs` line 62 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2238#-NPDg15p87WN0X6Yef1Q:-NPN5y-V2b91zjiyUV01:b-pdq19l) ([raw file](https://github.com/starkware-libs/cairo/blob/02af347c98905004263579e632188af7143e73ca/crates/cairo-lang-starknet/src/abi_test.rs#L62)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

We may have name in the future, once we support named tuples. I suggest removing the `name` property now, and possibly add this only in the case of named tuples (in the future).
In any case, if we decide to keep it, it should be `"name": null` instead of `"name": ""`,
</blockquote></details>

done.

Just to make sure, we don't care about backward compatibility in the ABI?

**Review by orizi — APPROVED** [review]
> Reviewed 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2238)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/abi.rs` line 69 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2238#-NOzo2V84s4nQqzs99Uz:-NPN6it3DdOAiazyq3P5:b-segup2) ([raw file](https://github.com/starkware-libs/cairo/blob/d2cde0e1a704cb4402a2804124f3a630f2070d5a/crates/cairo-lang-starknet/src/abi.rs#L69)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

maybe we are going to support named tuple in the future?
</blockquote></details>

i assume we are - but then names would be included in the type anyway.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2238)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/abi.rs` line 69 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2238#-NOzo2V84s4nQqzs99Uz:-NPN8ouWExw12PZXi4st:ba43mt) ([raw file](https://github.com/starkware-libs/cairo/blob/d2cde0e1a704cb4402a2804124f3a630f2070d5a/crates/cairo-lang-starknet/src/abi.rs#L69)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i assume we are - but then names would be included in the type anyway.
</blockquote></details>

The question then is way to we have a vector here?

ref argument?
Backward compatibility?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2238)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/abi.rs` line 69 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2238#-NOzo2V84s4nQqzs99Uz:-NPN9Rm-8zse3lygoUsN:b-itsv9r) ([raw file](https://github.com/starkware-libs/cairo/blob/d2cde0e1a704cb4402a2804124f3a630f2070d5a/crates/cairo-lang-starknet/src/abi.rs#L69)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

The question then is way to we have a vector here?

ref argument?
Backward compatibility?
</blockquote></details>

*why have a vector.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2238)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/abi.rs` line 69 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2238#-NOzo2V84s4nQqzs99Uz:-NPNHWjxBnHqQ0LM3LLD:b1meprd) ([raw file](https://github.com/starkware-libs/cairo/blob/d2cde0e1a704cb4402a2804124f3a630f2070d5a/crates/cairo-lang-starknet/src/abi.rs#L69)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

*why have a vector.
</blockquote></details>

I agree - it should be the type directly. No vector.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2238)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @orizi, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/abi.rs` line 69 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2238#-NOzo2V84s4nQqzs99Uz:-NPNJAGYDR_ExM7cTnAK:b-55149n) ([raw file](https://github.com/starkware-libs/cairo/blob/d2cde0e1a704cb4402a2804124f3a630f2070d5a/crates/cairo-lang-starknet/src/abi.rs#L69)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I agree - it should be the type directly. No vector.
</blockquote></details>

added a TODO for now.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2238#-:-NPNRO8A0TgM5DUh6GSY:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/abi.rs` line 153 at r7](https://reviewable.io/reviews/starkware-libs/cairo/2238#-NPNRRIh54lF7uHQq57U:-NPNRRIh54lF7uHQq57V:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8a3e2fbb295f9703e8d67c6680bbe0727dab56e9/crates/cairo-lang-starknet/src/abi.rs#L153)):*
> ```XML
>     pub inputs: Vec<Input>,
> 
>     // TODO(ilya): Should the the output be a vector or a single type?
> ```





_Suggestion:_
```XML
the
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2238)* status: 8 of 9 files reviewed, all discussions resolved (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/abi.rs` line 153 at r7](https://reviewable.io/reviews/starkware-libs/cairo/2238#-NPNRRIh54lF7uHQq57U:-NPNVNIsDBFMCCWGb-YT:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/8a3e2fbb295f9703e8d67c6680bbe0727dab56e9/crates/cairo-lang-starknet/src/abi.rs#L153)):*
> ```XML
>     pub inputs: Vec<Input>,
> 
>     // TODO(ilya): Should the the output be a vector or a single type?
> ```

done.

**Pull request merged**
