### PR TITLE
Display for snapshots

### PR DESCRIPTION
**Pull request by piotmag769**
Came up with it after the previous PR was closed :/

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4745)

### CODE REVIEW

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4745)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4745#-NnOkqswCdBEry4F8vGw:-NnOkqswCdBEry4F8vGx:bj0i0z) (no related file):*
I added this because without it snapshot implementations of Display required specific import of the concrete impl - example below

package structure:
```
src/
  lib.cairo
  abc.cairo
```

lib.cairo:
```cairo
mod abc;
use core::fmt::{Display, Formatter, Error};

#[derive(Drop)]
struct Y {}

impl DisplayY of Display<Y> {
  fn fmt(self: @Y, ref f: Formatter) -> Result<(), Error> {
      Result::Ok(())
  }
}

impl DisplayYSnap of Display<@Y> {
  fn fmt(self: @@Y, ref f: Formatter) -> Result<(), Error> {
    Result::Ok(())
  }
}
```

abc.cairo
```cairo
use super::Y;

fn func() {
  println!("{}", @Y{});
}
```

For this package `scarb build` fails. The fix is to add `use super::DisplayYSnap;` to abc.cairo. Is it a desired behaviour?

___

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4745)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4745#-NnOkqswCdBEry4F8vGw:-NnOnt4D5saI_Lp23jp2:bfuhz8n) (no related file):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

I added this because without it snapshot implementations of Display required specific import of the concrete impl - example below

package structure:
```
src/
  lib.cairo
  abc.cairo
```

lib.cairo:
```cairo
mod abc;
use core::fmt::{Display, Formatter, Error};

#[derive(Drop)]
struct Y {}

impl DisplayY of Display<Y> {
  fn fmt(self: @Y, ref f: Formatter) -> Result<(), Error> {
      Result::Ok(())
  }
}

impl DisplayYSnap of Display<@Y> {
  fn fmt(self: @@Y, ref f: Formatter) -> Result<(), Error> {
    Result::Ok(())
  }
}
```

abc.cairo
```cairo
use super::Y;

fn func() {
  println!("{}", @Y{});
}
```

For this package `scarb build` fails. The fix is to add `use super::DisplayYSnap;` to abc.cairo. Is it a desired behaviour?
</blockquote></details>

Clarification:
the error message is 
```console
error: Trait has no implementation in context: core::fmt::Display::<@uwu::Y>
 --> /Users/piotrmagiera/SWM/uwu/src/abc.cairo[println_macro][writeln_macro]:3:31
    match core::fmt::Display::fmt(__write_macro_arg0__, ref __formatter_for_print_macros__) {
```
and the part of the code
```cairo
impl DisplayY of Display<Y> {
  fn fmt(self: @Y, ref f: Formatter) -> Result<(), Error> { 
    Result::Ok(()) 
  }
}
```
is not needed to reproduce

___

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4745)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4745#-NnOkqswCdBEry4F8vGw:-NnPpEUd1m9HPdtTFO_N:b-rtxw95) (no related file):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Clarification:
the error message is 
```console
error: Trait has no implementation in context: core::fmt::Display::<@uwu::Y>
 --> /Users/piotrmagiera/SWM/uwu/src/abc.cairo[println_macro][writeln_macro]:3:31
    match core::fmt::Display::fmt(__write_macro_arg0__, ref __formatter_for_print_macros__) {
```
and the part of the code
```cairo
impl DisplayY of Display<Y> {
  fn fmt(self: @Y, ref f: Formatter) -> Result<(), Error> { 
    Result::Ok(()) 
  }
}
```
is not needed to reproduce
</blockquote></details>

Update: same thing happens when implementing `Display` for `Array<Y>`

```console
error: Trait has no implementation in context: core::fmt::Display::<core::array::Array::<uwu::Y>>
 --> /Users/piotrmagiera/SWM/uwu/src/abc.cairo[println_macro][writeln_macro]:3:31
    match core::fmt::Display::fmt(__write_macro_arg0__, ref __formatter_for_print_macros__) {
                              ^*^
```

I've used Scarb depending on Cairo from the main branch (bumped the Cairo deps for Scarb locally and built it), so it uses the latest possible compiler version - both issues still occur.

___

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4745)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4745#-NnYxtcI3Cf8Pu2V1dcg:-NnYxtcI3Cf8Pu2V1dch:bxnl4pn) (no related file):*
I'm not sure we actually want this - do note that any user of this can actually just call this with adding a `*`.
The diagnostic itself indeed should be better mapped to the original user code.

___

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4745)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4745#-NnYxtcI3Cf8Pu2V1dcg:-Nn_J7Zs47m5loxI7CQi:bgnjld) (no related file):*
>do note that any user of this can actually just call this with adding a `*`

Isn't `Copy` trait required to use desnap operator though? It would be helpful for printing e.g. snapshot of a struct that has a field of a type `Array<felt252>`. Note that there is a similar generic implementation for Debug for snapshots in corelib already.
https://github.com/starkware-libs/cairo/blob/8290898d602f87fb5bc3a18f28a42430cf6d3fdc/corelib/src/fmt.cairo#L71

___

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4745#-:-NniGeDFDmivHje8_AZ4:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4745)* status: all files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4745#-NniH3RN0swnHdIMPa_I:-NniH3RN0swnHdIMPa_J:b-uxd2jp) (no related file):*
Adding @ilyalesokhin-starkware for 2nd eye.

___

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4745)* status: all files reviewed, 2 unresolved discussions (waiting on @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4745#-NnmxIvIDIpfVYJdoEkW:-NnmxIvIDIpfVYJdoEkX:bk3gsrs) (no related file):*
@ilyalesokhin-starkware for 2nd eye

___

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4745#-:-NpERoBg1TjUUZ2FOCOY:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi and @piotmag769)

**Pull request merged**
