### PR TITLE
added closures to parser

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5976)

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5976)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @gilbens-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5976#-O1HUL9D8Udx3HAxrGhq:-O1HUL9D8Udx3HAxrGhr:bmmere) (no related file):*
@ilyalesokhin-starkware 

___

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5976#-:-O1Kz2KH0xJRiI_G8Z7y:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware and @orizi)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5976#-:-O1LanUU3ITXT24XxFQJ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5976)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/closure` line 8 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5976#-O1Le_v031k2FyCe5N3f:-O1Le_v031k2FyCe5N3g:b-se3l2h) ([raw file](https://github.com/starkware-libs/cairo/blob/cc01687c50bdd33b016d8fe3e04e3b0509206598/crates/cairo-lang-parser/src/parser_test_data/partial_trees/closure#L8)):*
> ```
> //! > cairo_code
> fn test() {
>     let expensive_closure =  | num: u32, b, c: felt252 | -> u32 {
> ```

You can add a todo on me to fix the formatting.



_Code quote:_
```
 let expensive_closure =  | num: u32, b, c: felt252 | -> u32 {
```

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5976#-:-O1Leuu5BrQsoBDhSw8U:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5976)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

**Review by mkaput — APPROVED** [review]
> Reviewed 4 of 10 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5976)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

**Pull request merged**
