### PR TITLE
Read scarb path from config, show warning if missing in both config and path var

### LINKED ISSUE #2615: bug: LS crash if scarb binary is missing
# Bug Report

**Cairo version:**

Alpha 6

**Current behavior:**

```
WARN   crates/cairo-lang-language-server/src/lib.rs:783 15:27:45 Failed to obtain scarb metadata from manifest file.

Caused by:
    0: failed to read `scarb metadata` output
    1: No such file or directory (os error 2)
```

**Expected behavior:**

Nice warning box and LS should abandon setting up crate roots

**Steps to reproduce:**

Open `corelib` without Scarb in `PATH`

**Other information:**

Reported to me by @ilyalesokhin-starkware

### PR DESCRIPTION
**Pull request by maciektr**
fix #2615

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2710)

### CODE REVIEW

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2710)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware, @maciektr, and @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 233 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2710#-NSAfluBAYZvociJ6XEw:-NSAfluBAYZvociJ6XEx:b2nhkus) ([raw file](https://github.com/starkware-libs/cairo/blob/d38572a879d9fb2d3e75a5e38db986fb4cd705d7/crates/cairo-lang-language-server/src/lib.rs#L233)):*
> ```XML
> 
> #[derive(Debug)]
> pub enum ScarbPath {}
> ```

Nit



_Suggestion:_
```XML
pub struct ScarbPath;
```
___
*[`vscode-cairo/src/extension.ts` line 105 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2710#-NSAfaFuALyvjvXD6wrq:-NSAfaFuALyvjvXD6wrr:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d38572a879d9fb2d3e75a5e38db986fb4cd705d7/vscode-cairo/src/extension.ts#L105)):*
> ```XML
>         vscode.workspace.registerTextDocumentContentProvider("vfs", myProvider);
> 
>         client.onNotification('scarb/path', (param) => {
> ```





_Suggestion:_
```XML
'scarb/could-not-find-scarb-executable'
```

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2710)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware, @maciektr, and @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2710#-NSAhj_N7ookGHvSYVaY:-NSAhj_N7ookGHvSYVaZ:b-3dyk0b) ([raw file](https://github.com/starkware-libs/cairo/blob/d38572a879d9fb2d3e75a5e38db986fb4cd705d7/crates/cairo-lang-language-server/src/lib.rs#L213)):*
> ```XML
>                     if is_executable(path.clone()) {
>                         return Ok(Some(path));
>                     }
> ```

BTW I think I would print a warning if the item is not executable



_Code quote:_
```XML
                    if is_executable(path.clone()) {
                        return Ok(Some(path));
                    }
```

**Review by mkaput — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2710)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware, @maciektr, and @orizi)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
Just to make sure, if scrab is not installed and the path is not configured, I won't get any errors, right?

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2710#-:-NSAp2Ci5JieqlJ4JoiG:b-g79omi)* status: all files reviewed, 3 unresolved discussions (waiting on @maciektr and @orizi)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2710)* status: all files reviewed, 4 unresolved discussions (waiting on @maciektr and @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 866 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2710#-NSB485I2oF_IkmWFtvJ:-NSB485I2oF_IkmWFtvK:b-84fc03) ([raw file](https://github.com/starkware-libs/cairo/blob/d38572a879d9fb2d3e75a5e38db986fb4cd705d7/crates/cairo-lang-language-server/src/lib.rs#L866)):*
> ```XML
> 
> #[cfg(windows)]
> pub fn is_executable<P: AsRef<Path>>(path: P) -> bool {
> ```

since you don’t validate that it is an executable on windows, maybe you should call it
validate_executable_path or something like that?



_Code quote:_
```XML
pub fn is_executable<P: AsRef<Path>>(path: P) -> bool {
    path.as_ref().is_file()
}
```

**Review by mkaput — COMMENTED** [review]
No, LS will ask you to install Scarb; that's the expected behaviour -- if you have Scarb project, you should have Scarb installed.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2710#-:-NSB79Ya5X_cyRoPq895:bdbz6gr)* status: all files reviewed, 4 unresolved discussions (waiting on @maciektr and @orizi)

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2710)* status: all files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware, @maciektr, and @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 866 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2710#-NSB485I2oF_IkmWFtvJ:-NSB7IJO2DBeew_3PlE6:b-cgest8) ([raw file](https://github.com/starkware-libs/cairo/blob/d38572a879d9fb2d3e75a5e38db986fb4cd705d7/crates/cairo-lang-language-server/src/lib.rs#L866)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

since you don’t validate that it is an executable on windows, maybe you should call it
validate_executable_path or something like that?
</blockquote></details>

This is copy-pasted from Cargo, basically there is no such thing as "executable file" on Windows. You either try to execute it and succeed or fail. The only thing we can check is if path points to a file or to a directory

**Review by mkaput — COMMENTED** [review]
If will not crash though, but ignore the project entirely

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2710#-:-NSB7dC588xYHeOYCJlV:b-5okg02)* status: all files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware, @maciektr, and @orizi)

**Comment by maciektr** [comment]
If it is a Scarb project (containing Scarb.toml manifest file), and Scarb is not installed, we will show following warning.

**Review by maciektr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2710)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware, @mkaput, and @orizi)

___
*[`vscode-cairo/src/extension.ts` line 105 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2710#-NSAfaFuALyvjvXD6wrq:-NSBUG2M4Dey7O611Mig:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d38572a879d9fb2d3e75a5e38db986fb4cd705d7/vscode-cairo/src/extension.ts#L105)):*
> ```XML
>         vscode.workspace.registerTextDocumentContentProvider("vfs", myProvider);
> 
>         client.onNotification('scarb/path', (param) => {
> ```

Done.

**Comment by maciektr** [comment]
*[`crates/cairo-lang-language-server/src/lib.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2710#-NSAhj_N7ookGHvSYVaY:-NSBddi1DQN761pfN9ET:bnkkqvf) ([raw file](https://github.com/starkware-libs/cairo/blob/d38572a879d9fb2d3e75a5e38db986fb4cd705d7/crates/cairo-lang-language-server/src/lib.rs#L213)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

BTW I think I would print a warning if the item is not executable
</blockquote></details>

Moved to cairo extension side.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
But there is a Scarb.toml file in the repo.
https://github.com/starkware-libs/cairo/blob/439da05a031c2eda263c4ce12d0b71d20f38205f/corelib/Scarb.toml

does this mean that Scarb is a dependency of this repo?
do we have dependencies in both directions?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2710#-:-NSBdwYc8Ui2B1GQMEix:b-anw08m)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @mkaput and @orizi)

**Review by mkaput — APPROVED** [review]
Yes, Scarb is a development dependency of this repo currently. I mean, it is not needed strictly to build the project, but is necessary for some other development tasks.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2710#-:-NSBgHmVEy64xFYwY-Ni:b-v454fb)* status: all files reviewed, 1 unresolved discussion (waiting on @maciektr and @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 819 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2710#-NSBfUbpAE1XLlZeEDBD:-NSBfUbpAE1XLlZeEDBE:b-lxis0z) ([raw file](https://github.com/starkware-libs/cairo/blob/26f5a56a215449dbbc4f6c33735de1f8d1c6bd61/crates/cairo-lang-language-server/src/lib.rs#L819)):*
> ```XML
> ) -> anyhow::Result<scarb_metadata::Metadata> {
>     scarb_metadata::MetadataCommand::new()
>         .scarb_path(scarb_path)
> ```

I think we should rather let MetadataCommand to find Scarb in $SCARB and $PATH as it does, and only call this method if you really know Scarb location. Perhaps we could expose a ScarbNotFound error variant upstream in `scarb-metadata` and consume it here?

Non-blocking, we can do this in followup PR IMHO

**Comment by maciektr** [comment]
*[`crates/cairo-lang-language-server/src/lib.rs` line 819 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2710#-NSBfUbpAE1XLlZeEDBD:-NSBi61rDnFcw1NPnU_p:b-epctgf) ([raw file](https://github.com/starkware-libs/cairo/blob/26f5a56a215449dbbc4f6c33735de1f8d1c6bd61/crates/cairo-lang-language-server/src/lib.rs#L819)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I think we should rather let MetadataCommand to find Scarb in $SCARB and $PATH as it does, and only call this method if you really know Scarb location. Perhaps we could expose a ScarbNotFound error variant upstream in `scarb-metadata` and consume it here?

Non-blocking, we can do this in followup PR IMHO
</blockquote></details>

I thought about this, but I have decided to pass the value anyway, as we use it to decide if we should run scarb metada at all in `detect_crate_for`, so any discrepancy here would be confusing. :thinking:

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2710)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Comment by ilyalesokhin-starkware** [comment]
Is it possible to remove Scarb.toml from this repo?
and have it as part of the scrab?

**Comment by maciektr** [comment]
@ilyalesokhin-starkware Should we move this discussion to a separate issue?

**Review by mkaput — APPROVED** [review]
I would favour doing so, the problem we are facing is that developing `core` using LS currently requires Scarb, which wasn't explicitly announced by the plugin -- this is fixed by this PR. Simply installing Scarb locally is good enough even in long term (which is proved by other language teams, see node.js depends on npm, rust depends on cargo etc.)

Removing Scarb.toml, or cairo_project.toml (which I actually would prefer to do!) is a different thing.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2710#-:-NSjE44k04M0DjLyrtd_:b-s7vduk)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware and @orizi)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2710#-:-NSo-ply86jB8BaWxIyu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2710)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
