### PR TITLE
a more efficient WideMul implementation

### PR DESCRIPTION
**Pull request by zuphitf**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1494)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1494)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @zuphitf)

___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 240 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1494#-NKDf0eq9Ew1p59gOOoP:-NKDf0eq9Ew1p59gOOoQ:b5fmkov) ([raw file](https://github.com/starkware-libs/cairo/blob/2473d0879afe90ba12aaff94c7ec1ba021b522c9/crates/sierra_to_casm/src/invocations/uint128.rs#L240)):*
> ```XML
>                 // Note that reconstruction of the felt `lower_uint128_with_carry` is performed
>                 // with no wrap-around: `carry` was capped at 66 bits and then shifted 128 bits.
>                 // `lower_uint128` is range-checked for 128 bits. Overall, within 194 bits range.
> ```

explain why the original `lower_uint128_with_carry` is capped by 194  (and therefore we can allow carry to be bound by 66)



_Code quote:_
```XML
                // `lower_uint128` is range-checked for 128 bits. Overall, within 194 bits range.
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1494)* status: all files reviewed, 2 unresolved discussions (waiting on @zuphitf)

___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 232 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1494#-NKDoTPk80EADnNnhxTv:-NKDoTPk80EADnNnhxTw:bk172po) ([raw file](https://github.com/starkware-libs/cairo/blob/2473d0879afe90ba12aaff94c7ec1ba021b522c9/crates/sierra_to_casm/src/invocations/uint128.rs#L232)):*
> ```XML
>                 assert carry = *(range_check++);
>                 // Verify that carry < 2**66 by constraining carry + (2**128-1) - (2**66-1) < 2**128.
>                 const carry_range_fixer = u128::MAX - (2u128.pow(66) - 1);
> ```

Let `n = (2^64-1)^2 = 2^128 - 2^65 + 1`. Then:
```
(a0*b1 + a1*b0 + (a0 * b0) // 2^64) // 2^64 <= (2n + n // 2^64) // 2^64
                                            = (2^129 - 2^66 + 2 + 2^64 - 2) // 2^64
                                            = 2^65 - 4 + 1
                                            = 2^65 - 3
```
Consider changing the carry fixer to give the tightest bound possible.



_Code quote:_
```XML
const carry_range_fixer = u128::MAX - (2u128.pow(66) - 1);
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1494)* status: all files reviewed, 2 unresolved discussions (waiting on @zuphitf)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1494)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @zuphitf)

___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 232 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1494#-NKDoTPk80EADnNnhxTv:-NKDqwX_5Tg0xrunWokB:b-bufbcy) ([raw file](https://github.com/starkware-libs/cairo/blob/2473d0879afe90ba12aaff94c7ec1ba021b522c9/crates/sierra_to_casm/src/invocations/uint128.rs#L232)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Let `n = (2^64-1)^2 = 2^128 - 2^65 + 1`. Then:
```
(a0*b1 + a1*b0 + (a0 * b0) // 2^64) // 2^64 <= (2n + n // 2^64) // 2^64
                                            = (2^129 - 2^66 + 2 + 2^64 - 2) // 2^64
                                            = 2^65 - 4 + 1
                                            = 2^65 - 3
```
Consider changing the carry fixer to give the tightest bound possible.
</blockquote></details>

i'd rather not - just describe why the bound is obviously just enough.
being to exact is needlessly dangerous.

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1494)* status: all files reviewed, 1 unresolved discussion (waiting on @zuphitf)

**Review by zuphitf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1494)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 240 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1494#-NKDf0eq9Ew1p59gOOoP:-NKE1zRF4dLVHwBLHuq0:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2473d0879afe90ba12aaff94c7ec1ba021b522c9/crates/sierra_to_casm/src/invocations/uint128.rs#L240)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

explain why the original `lower_uint128_with_carry` is capped by 194  (and therefore we can allow carry to be bound by 66)
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1494#-:-NKE2VRe-q0rgQtv8eI-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1494)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zuphitf)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1494#-:-NKE2XNV2MCrtJpLy_DU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zuphitf)

**Pull request merged**
