### PR TITLE
Added hello_starknet contract

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1468)

### CODE REVIEW

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 8 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1468#-:-NK8Gw8qA82Avsi1rwED:bnfp4nl)* status: 8 of 12 files reviewed, all discussions resolved (waiting on @liorgold2 and @orizi)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1468#-:-NK8NHx2D9FR5j2C_Uel:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1468)* status: all files reviewed, 3 unresolved discussions (waiting on @liorgold2 and @yuvalsw)

___
*[`crates/starknet/src/casm_contract_class_test.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1468#-NKAi_QcAkqTmydKuo-C:-NKAi_QcAkqTmydKuo-D:bsm073k) ([raw file](https://github.com/starkware-libs/cairo/blob/b0f7619d58630a34355eed2c17452cd23f7e266b/crates/starknet/src/casm_contract_class_test.rs#L8)):*
> ```XML
> 
> #[test_case("test_contract"; "test_contract")]
> #[test_case("hello_starknet"; "hello_starknet")]
> ```

no need for the rename clause - as the parameters are exactly the rename.



_Suggestion:_
```XML
#[test_case("test_contract")]
#[test_case("hello_starknet")]
```
___
*[`crates/starknet/src/contract_class_test.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1468#-NKAimkq5LsNhCwkjgZ8:-NKAimkq5LsNhCwkjgZ9:bsm073k) ([raw file](https://github.com/starkware-libs/cairo/blob/b0f7619d58630a34355eed2c17452cd23f7e266b/crates/starknet/src/contract_class_test.rs#L55)):*
> ```XML
> }
> 
> #[test_case("test_contract"; "test_contract")]
> ```

no need for the rename clause - as the parameters are exactly the rename.



_Suggestion:_
```XML
#[test_case("test_contract")]
#[test_case("hello_starknet")]
```
___
*[`crates/starknet/src/contract_class_test.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1468#-NKAiq2FDbzhZBIrC5oL:-NKAiq2FDbzhZBIrC5oM:bsm073k) ([raw file](https://github.com/starkware-libs/cairo/blob/b0f7619d58630a34355eed2c17452cd23f7e266b/crates/starknet/src/contract_class_test.rs#L64)):*
> ```XML
> }
> 
> #[test_case("test_contract"; "test_contract")]
> ```

no need for the rename clause - as the parameters are exactly the rename.



_Suggestion:_
```XML
#[test_case("test_contract")]
#[test_case("hello_starknet")]
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1468)* status: 7 of 12 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware, @liorgold2, and @orizi)

___
*[`crates/starknet/src/casm_contract_class_test.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1468#-NKAi_QcAkqTmydKuo-C:-NKCdkSpCBqQpwso6Ctn:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b0f7619d58630a34355eed2c17452cd23f7e266b/crates/starknet/src/casm_contract_class_test.rs#L8)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no need for the rename clause - as the parameters are exactly the rename.
</blockquote></details>

Done.
___
*[`crates/starknet/src/contract_class_test.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1468#-NKAimkq5LsNhCwkjgZ8:-NKCdqzJ9nBLaobaj8jc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b0f7619d58630a34355eed2c17452cd23f7e266b/crates/starknet/src/contract_class_test.rs#L55)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no need for the rename clause - as the parameters are exactly the rename.
</blockquote></details>

Done.
___
*[`crates/starknet/src/contract_class_test.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1468#-NKAiq2FDbzhZBIrC5oL:-NKCdrkAEpH_rlM_jOme:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b0f7619d58630a34355eed2c17452cd23f7e266b/crates/starknet/src/contract_class_test.rs#L64)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no need for the rename clause - as the parameters are exactly the rename.
</blockquote></details>

Done.

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 7 of 12 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1468)* status: all files reviewed, 3 unresolved discussions (waiting on @liorgold2 and @orizi)

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1468)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1468)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 2 of 6 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1468)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1468)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
