### PR TITLE
Supported empty fixed sized array.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #5418
- #5417 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5417)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5417)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 991 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5417#-NvS6oLECqV8r-hqmEXF:-NvS6oLECqV8r-hqmEXG:b3eemys) ([raw file](https://github.com/starkware-libs/cairo/blob/72c7ac73ed995fe0f7e531ebb02ead565752e6f3/crates/cairo-lang-lowering/src/lower/mod.rs#L991)):*
> ```XML
>     let exprs = match &expr.items {
>         semantic::FixedSizeArrayItems::Items(items) if items.is_empty() => {
>             return Ok(LoweredExpr::Tuple { exprs: vec![], location });
> ```

Will using a `LoweredExpr::FixedSizeArray` require many changes down the line?



_Code quote:_
```XML
 return Ok(LoweredExpr::Tuple { exprs: vec![], location });
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5417)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @gilbens-starkware and @mkaput)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 991 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5417#-NvS6oLECqV8r-hqmEXF:-NvSg4qgEeloiGaSTco_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/72c7ac73ed995fe0f7e531ebb02ead565752e6f3/crates/cairo-lang-lowering/src/lower/mod.rs#L991)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Will using a `LoweredExpr::FixedSizeArray` require many changes down the line?
</blockquote></details>

Done.

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5417)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @mkaput)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5417#-:-NvVdvEY-6MJyZu7kEbK:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Pull request merged**
