### PR TITLE
Removed false positive warning for udeps.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #4311
- #4306
- #4305
- #4304
- #4301
- #4299
- #4303 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4303)

### CODE REVIEW

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4303)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-proc-macros/Cargo.toml` line 15 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4303#-Nhvs_LB6bs1aOY7EGad:-Nhvs_LB6bs1aOY7EGae:b-4hgoiq) ([raw file](https://github.com/starkware-libs/cairo/blob/4b112c2edca27135c4024daa89dd5b5a3a466a51/crates/cairo-lang-proc-macros/Cargo.toml#L15)):*
> ```TOML
> ignored = ["cairo-lang-debug"]
> 
> [package.metadata.cargo-udeps.ignore]
> ```

But we are no longer using udeps, why do we need it?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4303)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/cairo-lang-proc-macros/Cargo.toml` line 15 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4303#-Nhvs_LB6bs1aOY7EGad:-NhvuKCP6uCGEO4MXqEG:batc4ls) ([raw file](https://github.com/starkware-libs/cairo/blob/4b112c2edca27135c4024daa89dd5b5a3a466a51/crates/cairo-lang-proc-macros/Cargo.toml#L15)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

But we are no longer using udeps, why do we need it?
</blockquote></details>

Just for local runs - no reason for these to fail as well.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4303)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-proc-macros/Cargo.toml` line 15 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4303#-Nhvs_LB6bs1aOY7EGad:-Nhw_W2KC5wmeoWdDKWo:b-dhj1aj) ([raw file](https://github.com/starkware-libs/cairo/blob/7cf5a95c5bc9d0c57a4acc6b289cade982d1ad79/crates/cairo-lang-proc-macros/Cargo.toml#L15)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Just for local runs - no reason for these to fail as well.
</blockquote></details>

Isn't there a flag for docs? Can't we do something similar to what we do for testing? (an optional dependency that exists only if we have a specific flag)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4303)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/cairo-lang-proc-macros/Cargo.toml` line 15 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4303#-Nhvs_LB6bs1aOY7EGad:-NhxxSNH2owhMmmMfhiV:b-exf90g) ([raw file](https://github.com/starkware-libs/cairo/blob/7cf5a95c5bc9d0c57a4acc6b289cade982d1ad79/crates/cairo-lang-proc-macros/Cargo.toml#L15)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Isn't there a flag for docs? Can't we do something similar to what we do for testing? (an optional dependency that exists only if we have a specific flag)
</blockquote></details>

even if that is the case i highly doubt this wouldn't make udeps complain.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4303#-:-Nhz_BvP1jv4Slw0AVAX:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-proc-macros/Cargo.toml` line 15 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4303#-Nhvs_LB6bs1aOY7EGad:-NhzYRw06LQ_MaQ1CSzH:b-g3so26) ([raw file](https://github.com/starkware-libs/cairo/blob/7cf5a95c5bc9d0c57a4acc6b289cade982d1ad79/crates/cairo-lang-proc-macros/Cargo.toml#L15)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

even if that is the case i highly doubt this wouldn't make udeps complain.
</blockquote></details>

According to the udpes docs, that's the way to make udeps ignore doc-dependencies.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4303#-:-NhzqMY0CZrVDzxA7t-h:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
