### PR TITLE
Changed bytes31 casts to use libfunc upcast.

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3611)

### CODE REVIEW

**Comment by yuvalsw** [comment]
change target branch to minor version change branch, once base commits from main are merged to it.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3611)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @orizi, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3611#-N_YAlf-BFAgk6pObOxc:-N_YAlf-BFAgk6pObOxd:b-avtkby) ([raw file](https://github.com/starkware-libs/cairo/blob/e71bfd87814fef8280af4c17d659de78cb5b3963/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L37)):*
> ```XML
>         (Uint64Type::ID, 64),
>         (Uint128Type::ID, 128),
>         (Bytes31Type::ID, 248),
> ```

This affects downcast as well, which is not intended, right?

**Comment by yuvalsw** [comment]
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3611#-N_YAlf-BFAgk6pObOxc:-N_YKOHF8Mjgq0ezmFuG:bu08q3m) ([raw file](https://github.com/starkware-libs/cairo/blob/e71bfd87814fef8280af4c17d659de78cb5b3963/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L37)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

This affects downcast as well, which is not intended, right?
</blockquote></details>

It does, it is not used, but not sure it's harmful. Do you think we should forbid those downcasts?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3611)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3611#-N_YAlf-BFAgk6pObOxc:-N_YgWbOCe_83C5MC5dW:b-oocsbq) ([raw file](https://github.com/starkware-libs/cairo/blob/e71bfd87814fef8280af4c17d659de78cb5b3963/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L37)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

It does, it is not used, but not sure it's harmful. Do you think we should forbid those downcasts?
</blockquote></details>

not sure if it needs to be forbidden - but the implementation itself needs to change.
(as we use the fact the source already fits within 128 bits.)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3611)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @liorgold2, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3611#-N_YAlf-BFAgk6pObOxc:-N_dQfGD96hlxMEz54rY:b-9gvtbh) ([raw file](https://github.com/starkware-libs/cairo/blob/e71bfd87814fef8280af4c17d659de78cb5b3963/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L37)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

So may be easier to forbid - I don't currently see a usecase for it
</blockquote></details>

added suggestion for how to forbid.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3611#-N_dQWc93YoJ6Sf8bs8V:-N_dQWc93YoJ6Sf8bs8W:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e71bfd87814fef8280af4c17d659de78cb5b3963/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L119)):*
> ```XML
>         if !is_valid {
>             return Err(SpecializationError::UnsupportedGenericArg);
>         }
> ```





_Suggestion:_
```XML
        let is_valid = from_nbits >= to_nbits && from_nbits <= 128;
        if !is_valid {
            return Err(SpecializationError::UnsupportedGenericArg);
        }
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3611)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @liorgold2, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3611#-N_YAlf-BFAgk6pObOxc:-NbTG9F312Ro2IoGM_Su:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e71bfd87814fef8280af4c17d659de78cb5b3963/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L37)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

added suggestion for how to forbid.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3611#-N_dQWc93YoJ6Sf8bs8V:-NbTGAnaE1PqvMqZnGZ1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e71bfd87814fef8280af4c17d659de78cb5b3963/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L119)):*
> ```XML
>         if !is_valid {
>             return Err(SpecializationError::UnsupportedGenericArg);
>         }
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3611#-:-NbTO3gf6-LstIXYAx67:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

**Pull request closed without merging**
