### PR TITLE
Added TryInto::<u384, {u256,u128}>.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6326)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/circuit.cairo` line 510 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6326#-O5lsmML80VKCymwDweZ:-O5lsmML80VKCymwDwe_:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9977c1e0cbc5c42445f2b7edc25e690f5d972712/corelib/src/circuit.cairo#L510)):*
> ```Cairo
>     }
> 
>     pub fn to_u128(value: u384) -> Option<u128> {
> ```





_Suggestion:_
```Cairo
try_inoto_u128
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6326)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6326)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/circuit.cairo` line 510 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6326#-O5lsmML80VKCymwDweZ:-O5ltbEJ9EA-PwJQOQAN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9977c1e0cbc5c42445f2b7edc25e690f5d972712/corelib/src/circuit.cairo#L510)):*
> ```Cairo
>     }
> 
>     pub fn to_u128(value: u384) -> Option<u128> {
> ```

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/circuit.cairo` line 482 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6326#-O5lxMVz9Yl6g1JcFS0T:-O5lxMVz9Yl6g1JcFS0U:b-s4hc3e) ([raw file](https://github.com/starkware-libs/cairo/blob/4412b1bc3c7ed3e6058a2df83e83708f078c02df/corelib/src/circuit.cairo#L482)):*
> ```Cairo
>     }
> 
>     impl AddHelperTo96By32Impl of AddHelper<
> ```

why is there a 'TO'?



_Suggestion:_
```Cairo
AddHelper96With32Impl
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6326)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/circuit.cairo` line 482 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6326#-O5lxMVz9Yl6g1JcFS0T:-O5mBrnB2X0kAl-uQUZB:b-dbr5hb) ([raw file](https://github.com/starkware-libs/cairo/blob/4412b1bc3c7ed3e6058a2df83e83708f078c02df/corelib/src/circuit.cairo#L482)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why is there a 'TO'?
</blockquote></details>

the result is u96 in it becomes it by adding a u32.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6326#-:-O5mfOTGDghKs-NqSqGH:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
