### PR TITLE
Use `stable` rust version for CI builds

### PR DESCRIPTION
**Pull request by maciektr**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2526)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
lgtm. @orizi ?

**Review by orizi — COMMENTED** [review]
i think we use it in ci for certain things - but not for others - so we probably shouldn't - but will make sure tomorrow.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2526#-:-NQuJATD4PnxUNjUBNFc:blzdd5g)* status: 0 of 1 files reviewed, all discussions resolved

**Review by mkaput — COMMENTED** [review]
I think it would be better to simply remove any unstable usages and stick with stable compiler version?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2526#-:-NQxm9NB6VmDYrKSgLdi:b-tq8i9c)* status: 0 of 1 files reviewed, all discussions resolved

**Review by mkaput — COMMENTED** [review]
@orizi ping

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2526#-:-NRX3Ws-793wjlgKpiZr:btm9feg)* status: 0 of 1 files reviewed, all discussions resolved

**Review by orizi — COMMENTED** [review]
i think we only do it for the fmt - the generic build is not based on the nightly (if it is - it is just for the consistency of the generated ast code)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2526#-:-NRX44Cl4p_YV7P5j8zm:b-td8oja)* status: 0 of 1 files reviewed, all discussions resolved

**Review by mkaput — COMMENTED** [review]
So perhaps this PR should go the other way around and remove any `nightly` references except the formatter?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2526#-:-NRX6FqPC2qAylJpIREa:b-cjv3av)* status: 0 of 1 files reviewed, all discussions resolved

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2526#-:-NRlxTj-BLnSnKPrHZEs:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciektr)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2526)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciektr)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2526)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciektr)

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2526)* status: all files reviewed, 2 unresolved discussions (waiting on @maciektr)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2526#-NRmLx3l8ai8Iq7gdxiF:-NRmLx3l8ai8Iq7gdxiG:b-ynkhxs) (no related file):*
Also somewhere there should be a note that you need that particular nightly installed to be able to run tests

___

**Comment by maciektr** [comment]
*[`scripts/cairo_test.sh` line 3 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2526#-NRmLd8lAbs0gJRkt9qy:-NRmSkqV2_NqmjYaRVTv:bjefpfd) ([raw file](https://github.com/starkware-libs/cairo/blob/d2a2a6d3ce993caa81de40b0c65a38664e85a8d0/scripts/cairo_test.sh#L3)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Do these scripts now run locally?
</blockquote></details>

From my tests, yes.

**Review by maciektr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2526)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @mkaput and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2526#-NRmLUNI1tzgz4kSDCrl:-NRmMaiH-2AEQWISXThj:b-896fix) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

@maciektr please adjust PR description :)
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2526#-NRmLx3l8ai8Iq7gdxiF:-NRmecBD5MoYj9oJlaQf:b-896fix) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Also somewhere there should be a note that you need that particular nightly installed to be able to run tests
</blockquote></details>

Done.

___

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r2, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2526#-:-NRwLvG3Csq2uASbfTJf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciektr)

**Pull request merged**
