### PR TITLE
Add dict manager to Sierra and remove start pointer of dict.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1413)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1413)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/sierra_to_casm/src/invocations/dict_felt_to.rs` line 543 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1413#-NJkKUgyBCKVxRuytziB:-NJkKUgz0XjLEoHodd_j:b29wneo) ([raw file](https://github.com/starkware-libs/cairo/blob/01b0ab93371dbfcfac0c848f44e443116f29c4c9/crates/sierra_to_casm/src/invocations/dict_felt_to.rs#L543)):*
> ```XML
> }
> 
> impl ApplyApChange for DictFeltToView {
> ```

entirely remove the view - as this is now a simple `as_buffer` call.



_Code quote:_
```XML
DictFeltToView
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1413)* status: 1 of 10 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/sierra_to_casm/src/invocations/dict_felt_to.rs` line 543 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1413#-NJkKUgyBCKVxRuytziB:-NJoMRje8K8r1yLmV3JA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/01b0ab93371dbfcfac0c848f44e443116f29c4c9/crates/sierra_to_casm/src/invocations/dict_felt_to.rs#L543)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

entirely remove the view - as this is now a simple `as_buffer` call.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1413)* status: 7 of 10 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/sierra_to_casm/src/invocations/dict_felt_to.rs` line 67 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1413#-NJoQnnIDM6H41E8pv0c:-NJoQnnIDM6H41E8pv0d:bmrd1oz) ([raw file](https://github.com/starkware-libs/cairo/blob/63251f177f0b6a7e7c2923a9f78893a47c04cd11/crates/sierra_to_casm/src/invocations/dict_felt_to.rs#L67)):*
> ```XML
>         tempvar temp_n_destructed;
>         assert temp_dict_infos_start = dict_infos_start;
>         assert temp_n_dicts = n_dicts;
> ```

after this is submitted - for the let. https://reviewable.io/reviews/starkware-libs/cairo/1423



_Suggestion:_
```XML
    let dict_manager_ptr_ref = match builder.refs {
        [ReferenceValue { expression: expr_dict_manager, .. }] => {
            expr_dict_manager.try_unpack_single()?.to_buffer(2)?
        }
        refs => {
            return Err(InvocationError::WrongNumberOfArguments {
                expected: 1,
                actual: refs.len(),
            });
        }
    };
    let mut casm_builder = CasmBuilder::default();
    let dict_manager_ptr = casm_builder.add_var(dict_manager_ptr_ref);
    let imm_1 = casm_builder.add_var(ResOperand::Immediate(1.into()));
    let imm_3 = casm_builder.add_var(ResOperand::Immediate(3.into()));
    casm_build_extend! {casm_builder,
        tempvar new_dict_end;
        hint AllocDictFeltTo {dict_manager_ptr: dict_manager_ptr} into {new_dict_end_dst: new_dict_end};
        // Previous dict info
        tempvar dict_infos_start;
        assert *(dict_manager_ptr++) = dict_infos_start;
        tempvar n_dicts;
        assert *(dict_manager_ptr++) = n_dicts;
        tempvar n_destructed;
        assert *(dict_manager_ptr++) = n_destructed;
        let new_dict_manager_ptr = dict_manager_ptr;
        // New dict info
        assert *(dict_manager_ptr++) = dict_infos_start;
        tempvar new_n_dicts;
        assert new_n_dicts = n_dicts + imm_1;
        assert *(dict_manager_ptr++) = new_n_dicts;
        assert *(dict_manager_ptr++) = n_destructed;
    };
    let CasmBuildResult { instructions, fallthrough_state, .. } = casm_builder.build();
    assert_eq!(
        core_libfunc_ap_change::core_libfunc_ap_change(builder.libfunc),
        [sierra_ap_change::ApChange::Known(fallthrough_state.ap_change)]
    );
    Ok(builder.build(
        instructions,
        vec![],
        [[
            ReferenceExpression::from_cell(CellExpression::from_res_operand(
                fallthrough_state.get_adjusted(new_dict_manager_ptr),
            )),
            ReferenceExpression::from_cell(CellExpression::Deref(
                fallthrough_state.get_adjusted_as_cell_ref(new_dict_end),
            )),
        ]
        .into_iter()]
        .into_iter(),
    ))
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1413)* status: 2 of 10 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/sierra_to_casm/src/invocations/dict_felt_to.rs` line 67 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1413#-NJoQnnIDM6H41E8pv0c:-NJqgbQS2nN-sgTDuW7P:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/63251f177f0b6a7e7c2923a9f78893a47c04cd11/crates/sierra_to_casm/src/invocations/dict_felt_to.rs#L67)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

after this is submitted - for the let. https://reviewable.io/reviews/starkware-libs/cairo/1423
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, 6 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1413)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/sierra_to_casm/src/invocations/dict_felt_to.rs` line 50 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1413#-NJqjjNs0dUiLYaJWlyD:-NJqjjNt8AGLZUfP9VHk:brk18l5) ([raw file](https://github.com/starkware-libs/cairo/blob/3939965e2171af2a7219e5437b5fda5bcef67601/crates/sierra_to_casm/src/invocations/dict_felt_to.rs#L50)):*
> ```XML
>     let imm_1 = casm_builder.add_var(ResOperand::Immediate(1.into()));
>     casm_build_extend! {casm_builder,
>         tempvar new_dict_end;
> ```

is this value not checked in anyway?
you get it only from the hint - but there's no writing of anything related to it into the buffer.



_Code quote:_
```XML
new_dict_end
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1413)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/sierra_to_casm/src/invocations/dict_felt_to.rs` line 55 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1413#-NJslFjYEaSykkK0KDwr:-NJslFjYEaSykkK0KDws:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/3939965e2171af2a7219e5437b5fda5bcef67601/crates/sierra_to_casm/src/invocations/dict_felt_to.rs#L55)):*
> ```XML
>         tempvar dict_infos_start;
>         assert *(dict_manager_ptr++) = dict_infos_start;
>         tempvar n_dicts;
> ```

.



_Suggestion:_
```XML
        hint AllocDictFeltTo {dict_manager_ptr: dict_manager_ptr};
        // Previous dict info
        tempvar dict_infos_start;
        assert *(dict_manager_ptr++) = dict_infos_start;
        tempvar n_dicts;
        assert *(dict_manager_ptr++) = n_dicts;
        tempvar n_destructed;
        assert *(dict_manager_ptr++) = n_destructed;
        let new_dict_manager_ptr = dict_manager_ptr;
        // New dict info
        assert *(dict_manager_ptr++) = dict_infos_start;
        tempvar new_n_dicts;
        assert new_n_dicts = n_dicts + imm_1;
        assert *(dict_manager_ptr++) = new_n_dicts;
        assert *(dict_manager_ptr++) = n_destructed;
        tempvar offset;
        assert offset = n_dicts * imm_3;
        tempvar new_dict_end_ptr;
        assert new_dict_end_ptr = dict_infos_start + offset;
        let new_dict_end = new_dict_end_ptr[0];
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1413)* status: 6 of 11 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/sierra_to_casm/src/invocations/dict_felt_to.rs` line 50 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1413#-NJqjjNs0dUiLYaJWlyD:-NJtA_Tl47UPNEDhdNiA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3939965e2171af2a7219e5437b5fda5bcef67601/crates/sierra_to_casm/src/invocations/dict_felt_to.rs#L50)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is this value not checked in anyway?
you get it only from the hint - but there's no writing of anything related to it into the buffer.
</blockquote></details>

Done.
___
*[`crates/sierra_to_casm/src/invocations/dict_felt_to.rs` line 55 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1413#-NJslFjYEaSykkK0KDwr:-NJtAYoY6NHHimcwPy5T:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3939965e2171af2a7219e5437b5fda5bcef67601/crates/sierra_to_casm/src/invocations/dict_felt_to.rs#L55)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1413#-:-NJtEaOFEXBBqO3x-2BA:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/casm/src/builder.rs` line 496 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1413#-NJtDHt50c4sd3VnFHRV:-NJtDHt50c4sd3VnFHRW:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7917cf686efec8bd55e74db042529fab8b1dec92/crates/casm/src/builder.rs#L496)):*
> ```XML
>     };
>     ($builder:ident, let $dst:ident = $buffer:ident [ $offset:ident ] ; $($tok:tt)*) => {
>         let $dst = $builder.double_deref($buffer, $offset);
> ```





_Suggestion:_
```XML
    ($builder:ident, let $dst:ident = $buffer:ident [ $offset:expr ] ; $($tok:tt)*) => {
        let $dst = $builder.double_deref($buffer, $offset);
        $crate::casm_build_extend!($builder, $($tok)*)
    };
    ($builder:ident, let $dst:ident = *$buffer:ident; $($tok:tt)*) => {
        let $dst = $builder.double_deref($buffer, 0);
        $crate::casm_build_extend!($builder, $($tok)*)
    };
```
___
*[`crates/sierra_to_casm/src/invocations/dict_felt_to.rs` line 70 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1413#-NJtEDudCLRn4-gQaO-G:-NJtEDudCLRn4-gQaO-H:b-1k3v9s) ([raw file](https://github.com/starkware-libs/cairo/blob/7917cf686efec8bd55e74db042529fab8b1dec92/crates/sierra_to_casm/src/invocations/dict_felt_to.rs#L70)):*
> ```XML
>         tempvar new_dict_end_ptr;
>         assert new_dict_end_ptr = dict_infos_start + offset;
>         let new_dict_end_ref = new_dict_end_ptr[0];
> ```

no need



_Suggestion:_
```XML
        let new_dict_end = new_dict_end_ptr[0];
```
___
*[`crates/sierra_to_casm/src/invocations/dict_felt_to.rs` line 87 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1413#-NJtEL6dAWTYZ5S9D3V-:-NJtEL6dAWTYZ5S9D3V0:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7917cf686efec8bd55e74db042529fab8b1dec92/crates/sierra_to_casm/src/invocations/dict_felt_to.rs#L87)):*
> ```XML
>                 fallthrough_state.get_adjusted(new_dict_manager_ptr),
>             )),
>             ReferenceExpression::from_cell(CellExpression::Deref(
> ```





_Suggestion:_
```XML
            ReferenceExpression::from_cell(CellExpression::from_res_operand(
                fallthrough_state.get_adjusted(new_dict_end),
            )),
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1413)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/casm/src/builder.rs` line 496 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1413#-NJtDHt50c4sd3VnFHRV:-NJtlyz16vG3j96-yakc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7917cf686efec8bd55e74db042529fab8b1dec92/crates/casm/src/builder.rs#L496)):*
> ```XML
>     };
>     ($builder:ident, let $dst:ident = $buffer:ident [ $offset:ident ] ; $($tok:tt)*) => {
>         let $dst = $builder.double_deref($buffer, $offset);
> ```

Done.
___
*[`crates/sierra_to_casm/src/invocations/dict_felt_to.rs` line 70 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1413#-NJtEDudCLRn4-gQaO-G:-NJtvFHECp6XkZi3JSJH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7917cf686efec8bd55e74db042529fab8b1dec92/crates/sierra_to_casm/src/invocations/dict_felt_to.rs#L70)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no need
</blockquote></details>

Done.
___
*[`crates/sierra_to_casm/src/invocations/dict_felt_to.rs` line 87 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1413#-NJtEL6dAWTYZ5S9D3V-:-NJtvIKwBUg84tIjAf2-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7917cf686efec8bd55e74db042529fab8b1dec92/crates/sierra_to_casm/src/invocations/dict_felt_to.rs#L87)):*
> ```XML
>                 fallthrough_state.get_adjusted(new_dict_manager_ptr),
>             )),
>             ReferenceExpression::from_cell(CellExpression::Deref(
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1413#-:-NJtyBGz9QoRdEd7S6hJ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/sierra_to_casm/src/invocations/dict_felt_to.rs` line 70 at r6](https://reviewable.io/reviews/starkware-libs/cairo/1413#-NJty8i29lX6L9jP7Kz0:-NJty8i29lX6L9jP7Kz1:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/12a8f8eb5fd4df8a48e648fd6d37faf4c1c03117/crates/sierra_to_casm/src/invocations/dict_felt_to.rs#L70)):*
> ```XML
>         tempvar new_dict_end_ptr;
>         assert new_dict_end_ptr = dict_infos_start + offset;
>         let new_dict_end = new_dict_end_ptr[0];
> ```





_Suggestion:_
```XML
*new_dict_end_ptr;
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1413)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/sierra_to_casm/src/invocations/dict_felt_to.rs` line 70 at r6](https://reviewable.io/reviews/starkware-libs/cairo/1413#-NJty8i29lX6L9jP7Kz0:-NJtycqq2YFgQ5-QGSFR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/12a8f8eb5fd4df8a48e648fd6d37faf4c1c03117/crates/sierra_to_casm/src/invocations/dict_felt_to.rs#L70)):*
> ```XML
>         tempvar new_dict_end_ptr;
>         assert new_dict_end_ptr = dict_infos_start + offset;
>         let new_dict_end = new_dict_end_ptr[0];
> ```

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1413)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1413)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
