### PR TITLE
Improved error for too-long generic ID

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2481)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2481)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/felt_serde.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2481#-NQWAI7c9pnbjUMFflr4:-NQWAI7c9pnbjUMFflr5:bzhi3tw) ([raw file](https://github.com/starkware-libs/cairo/blob/b4a53423602c95c7db7ee6aa204dae4591f84a34/crates/cairo-lang-starknet/src/felt_serde.rs#L35)):*
> ```XML
>     #[error(
>         "Id `{0}` is too long for serialization. It is longer than {} characters. Consider \
>          whitelisting it in LONG_IDS_WHITELIST.",
> ```

this is not a list of allowed names - this is the actual list of the names.
if you want to add some other descriptor word - feel free - whitelist isn't it.



_Code quote:_
```XML
WHITELIST
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2481)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/felt_serde.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2481#-NQWAI7c9pnbjUMFflr4:-NQWJoNc4diNYqnF60X-:b-iww6wf) ([raw file](https://github.com/starkware-libs/cairo/blob/b4a53423602c95c7db7ee6aa204dae4591f84a34/crates/cairo-lang-starknet/src/felt_serde.rs#L35)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

It is the list of Ids that are too long that we allow to serialize. Otherwise - why is it there at all?
I wanted to add a word so that it's easy to find. LONG_IDS is a bit too generic.
I am open to suggestions if you don't like 'whitelist'
</blockquote></details>

SERDE_SUPPORTED_LONG_IDS would be fine i guess.



_Code quote:_
```XML
    static ref 
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2481)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/felt_serde.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2481#-NQWAI7c9pnbjUMFflr4:-NQWPnr01gizo7hpkl5e:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b4a53423602c95c7db7ee6aa204dae4591f84a34/crates/cairo-lang-starknet/src/felt_serde.rs#L35)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

SERDE_SUPPORTED_LONG_IDS would be fine i guess.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2481#-:-NQWQOw3C6fsAUm-kM2b:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2481)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
