### PR TITLE
Removed the need to move instructions in order to run them.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:0366abef

---

**Stack**:
- #1531
- #1528 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1528#-:-NKMfX7-Dvq7t9twrGPX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1528)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/casm/src/run.rs` line 179 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1528#-NKMirU2CT8fmBlUuWkO:-NKMirU2CT8fmBlUuWkP:bvfupfv) ([raw file](https://github.com/starkware-libs/cairo/blob/b1a1da31907a1629f27b929f2493e7f4cdfb777d/crates/casm/src/run.rs#L179)):*
> ```XML
> ) -> Result<(Vec<Option<BigInt>>, usize), Box<VirtualMachineError>> {
>     let data: Vec<MaybeRelocatable> = instructions
>         .clone()
> ```

why clone?



_Code quote:_
```XML
clone()
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1528)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @ilyalesokhin-starkware)

___
*[`crates/casm/src/run.rs` line 179 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1528#-NKMirU2CT8fmBlUuWkO:-NKMjXOUEr2OXfsxQzEa:b-f3qem1) ([raw file](https://github.com/starkware-libs/cairo/blob/b1a1da31907a1629f27b929f2493e7f4cdfb777d/crates/casm/src/run.rs#L179)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why clone?
</blockquote></details>

it clones the iterator - not the data.
it is a must - otherwise it would have been consumed, and it is used again.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1528#-:-NKMw2CM8ORHVhbHuf0I:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
