### PR TITLE
fix(corelib): Add missing impl for type conversions between U256

### PR DESCRIPTION
**Pull request by lambda-0x**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3293)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3293)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @lambda-0x)

___
*[`corelib/src/integer.cairo` line 1572 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3293#-NWs4had44IQUxnMHsT0:-NWs4had44IQUxnMHsT1:bm5r896) ([raw file](https://github.com/starkware-libs/cairo/blob/074481f6d8b8494af86b1e89d8a0afb2e3064f81/corelib/src/integer.cairo#L1572)):*
> ```Cairo
>     }
> }
> ```

Wdyt about adding all the others
___
*[`corelib/src/integer.cairo` line 1454 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3293#-NWwEVO50hbVvVHLDO9O:-NWwEVO50hbVvVHLDO9P:b-sntstk) ([raw file](https://github.com/starkware-libs/cairo/blob/5bd5e782d34c277d6cda4d8d25bbde3621167685/corelib/src/integer.cairo#L1454)):*
> ```Cairo
> }
> 
> // impls for (where X > 8):
> ```

I think it's better without these comments.
The impl signature is clear enough.

**Comment by lambda-0x** [comment]
> Wdyt about adding all the others

which other are missing?

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3293#-:-NX9BN6t6iywhsyCU3si:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lambda-0x)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3293#-:-NX9Uo06BacCxEcRojkR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lambda-0x)

**Comment by lambda-0x** [comment]
CI is failing due to this file having: https://github.com/starkware-libs/cairo/blob/d4486931e06cd58daf954afb2446704281eb7f83/tests/bug_samples/issue3211.cairo#L6-L15

Which causes there to be duplicate implementation error, what should i do with the duplicate impl in that test?

**Review by spapinistarkware — APPROVED** [review]
Be explicit when using this impl.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3293#-:-NXFR_gz4rxNlWVMT7oi:b-74gwx2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lambda-0x)

**Review by spapinistarkware — APPROVED** [review]
i.e. refer to the specific impl by name

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3293#-:-NXFRffyBIwcI3cxbXL3:bb6wlln)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lambda-0x)

**Comment by lambda-0x** [comment]
the problem is both have the same name, should rename the one used in test something else @spapinistarkware?

**Review by spapinistarkware — APPROVED** [review]
You don't have to rename, it shadows the core one. u can rename if u want.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3293#-:-NXFefs90VVzqgEq2EHO:b-v0ss7w)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lambda-0x)

**Pull request merged**
