### PR TITLE
Prevent adding trait uses to traits in scope from completions menu and add tests.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6140)

### CODE REVIEW

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6140)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 298 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6140#-O3WyCxg2dmh6Huc1wG2:-O3WyCxg2dmh6Huc1wG3:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8ed6c6bb1fb1e60a78b4cddf69cb3704da8f2ed7/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L298)):*
> ```XML
> /// Checks if a module has a trait in scope.
> #[tracing::instrument(level = "trace", skip_all)]
> pub fn module_has_trait(
> ```





_Suggestion:_
```XML
fn module_has_trait(
```
___
*[`crates/cairo-lang-language-server/tests/e2e/completions.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6140#-O3WykjU3gP5Ug4b3rCz:-O3WykjU3gP5Ug4b3rD-:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8ed6c6bb1fb1e60a78b4cddf69cb3704da8f2ed7/crates/cairo-lang-language-server/tests/e2e/completions.rs#L40)):*
> ```XML
>     ls.open("src/lib.cairo");
> 
>     let mut complitions = OrderedHashMap::default();
> ```





_Suggestion:_
```XML
completions
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6140)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 298 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6140#-O3WyCxg2dmh6Huc1wG2:-O3X-p3oBBFtxuncP1Ue:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8ed6c6bb1fb1e60a78b4cddf69cb3704da8f2ed7/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L298)):*
> ```XML
> /// Checks if a module has a trait in scope.
> #[tracing::instrument(level = "trace", skip_all)]
> pub fn module_has_trait(
> ```

Done.
___
*[`crates/cairo-lang-language-server/tests/e2e/completions.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6140#-O3WykjU3gP5Ug4b3rCz:-O3X-oNJ7K4OW8X2MNK1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8ed6c6bb1fb1e60a78b4cddf69cb3704da8f2ed7/crates/cairo-lang-language-server/tests/e2e/completions.rs#L40)):*
> ```XML
>     ls.open("src/lib.cairo");
> 
>     let mut complitions = OrderedHashMap::default();
> ```

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6140)* status: all files reviewed, 2 unresolved discussions (waiting on @mkaput and @piotmag769)

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6140)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 298 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6140#-O3WyCxg2dmh6Huc1wG2:-O3XNx-_6CyUo-ZOT0ZK:bzefgvm) ([raw file](https://github.com/starkware-libs/cairo/blob/8ed6c6bb1fb1e60a78b4cddf69cb3704da8f2ed7/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L298)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Have you pushed this? It's still `pub` here.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6140)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 298 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6140#-O3WyCxg2dmh6Huc1wG2:-O3XQoplBuacm0aHqwAx:bs4hqcc) ([raw file](https://github.com/starkware-libs/cairo/blob/8ed6c6bb1fb1e60a78b4cddf69cb3704da8f2ed7/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L298)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Have you pushed this? It's still `pub` here.
</blockquote></details>

Apparently not. Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6140)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput and @piotmag769)

**Review by mkaput — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6140)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @piotmag769)

**Review by mkaput — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6140#-:-O3XZTA992GyjFp3YWA2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @piotmag769)

**Pull request closed without merging**
