### PR TITLE
changed constrain_range function to downcast

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4884)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4884)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

___
*[`corelib/src/internal.cairo` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4884#-NoqCw477sz5Hbq1l2NT:-NoqCw477sz5Hbq1l2NU:b-j5vgwv) ([raw file](https://github.com/starkware-libs/cairo/blob/29d276509347b21a16f57d049213b1d05ec50be4/corelib/src/internal.cairo#L12)):*
> ```Cairo
> extern type BoundedInt<const MIN: felt252, const MAX: felt252>;
> 
> extern fn downcast<T, S>(value: T) -> Option<S> implicits(RangeCheck) nopanic;
> ```

delete it - use the existing `core::integer::downcast` instead.
___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 493 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4884#-NoqCpSy1Y5MBNA7dR-C:-NoqCpSy1Y5MBNA7dR-D:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/29d276509347b21a16f57d049213b1d05ec50be4/crates/cairo-lang-semantic/src/corelib.rs#L493)):*
> ```XML
>         db,
>         internal,
>         "downcast".into(),
> ```





_Suggestion:_
```XML
/// The function `downcast` from the `internal` submodule.
pub fn core_downcast(db: &dyn SemanticGroup, input: TypeId, output: TypeId) -> FunctionId {
    let internal = core_submodule(db, "internal");

    get_function_id(
        db,
        internal,
        "downcast".into(),
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4884)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4884)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/internal.cairo` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4884#-NoqCw477sz5Hbq1l2NT:-NoqEymW1FRK26GvsPpP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/29d276509347b21a16f57d049213b1d05ec50be4/corelib/src/internal.cairo#L12)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

delete it - use the existing `core::integer::downcast` instead.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 493 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4884#-NoqCpSy1Y5MBNA7dR-C:-NoqDf4z1JqbGSdQT6wt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/29d276509347b21a16f57d049213b1d05ec50be4/crates/cairo-lang-semantic/src/corelib.rs#L493)):*
> ```XML
>         db,
>         internal,
>         "downcast".into(),
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4884)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 2281 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4884#-NoqFLmOBrIx-MkbLWEX:-NoqFLmOBrIx-MkbLWEY:b-ftf3wy) ([raw file](https://github.com/starkware-libs/cairo/blob/dd586a8cf697f972bec123a55c2c9870af64c1ce/crates/cairo-lang-lowering/src/lower/mod.rs#L2281)):*
> ```XML
> fn numeric_match_optimization_threshold(ctx: &mut LoweringContext<'_, '_>) -> usize {
>     // Use [usize::max] as the default value, so that the optimization is not used by default.
>     // TODO(TomerStarkware): Make the default to 8 on `sierra-minor-update` branch.
> ```

as discussed - update todo.



_Code quote:_
```XML
    // TODO(TomerStarkware): Make the default to 8 on `sierra-minor-update` branch.
```
___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 485 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4884#-NoqFIip5511LLrnppiS:-NoqFIip5511LLrnppiT:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/dd586a8cf697f972bec123a55c2c9870af64c1ce/crates/cairo-lang-semantic/src/corelib.rs#L485)):*
> ```XML
>     get_generic_function_id(db, core_submodule(db, "internal"), "require_implicit".into())
> }
> /// The function `downcast` from the `internal` submodule.
> ```





_Suggestion:_
```XML
}
/// The function `downcast` from the `integer` submodule.
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4884)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4884)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 2281 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4884#-NoqFLmOBrIx-MkbLWEX:-NoqFp_i-tRkFNB8EpG8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/dd586a8cf697f972bec123a55c2c9870af64c1ce/crates/cairo-lang-lowering/src/lower/mod.rs#L2281)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

as discussed - update todo.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 485 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4884#-NoqFIip5511LLrnppiS:-NoqFpQM80wqRpC4B_Gh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/dd586a8cf697f972bec123a55c2c9870af64c1ce/crates/cairo-lang-semantic/src/corelib.rs#L485)):*
> ```XML
>     get_generic_function_id(db, core_submodule(db, "internal"), "require_implicit".into())
> }
> /// The function `downcast` from the `internal` submodule.
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4884)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 2281 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4884#-NoqILgE3GiuIwtGwuYO:-NoqILgE3GiuIwtGwuYP:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/91a1b053c94cd47aa547dcabf077d63e1f94d2e1/crates/cairo-lang-lowering/src/lower/mod.rs#L2281)):*
> ```XML
> fn numeric_match_optimization_threshold(ctx: &mut LoweringContext<'_, '_>) -> usize {
>     // Use [usize::max] as the default value, so that the optimization is not used by default.
>     // TODO(TomerStarkware): Make the default to optimal number on `sierra-minor-update` branch.
> ```





_Suggestion:_
```XML
    // TODO(TomerStarkware): Set the default to be optimal on `sierra-minor-update` branch.
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4884)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 2281 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4884#-NoqILgE3GiuIwtGwuYO:-NoqJa8FAsbDABP6-5IP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/91a1b053c94cd47aa547dcabf077d63e1f94d2e1/crates/cairo-lang-lowering/src/lower/mod.rs#L2281)):*
> ```XML
> fn numeric_match_optimization_threshold(ctx: &mut LoweringContext<'_, '_>) -> usize {
>     // Use [usize::max] as the default value, so that the optimization is not used by default.
>     // TODO(TomerStarkware): Make the default to optimal number on `sierra-minor-update` branch.
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4884#-:-NoqLDh6BoZwcWBQQWec:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
