### PR TITLE
Doc StorageNode.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6055)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`tests/e2e_test_data/libfuncs/consts` line 7 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6055#-O2UbqUy0iQUREfl9MHm:-O2UbqUzBV4BjS0R9Usb:b-l6hdjr) ([raw file](https://github.com/starkware-libs/cairo/blob/e63517bed1e5e608639ab8c30eca561f13b111bd/tests/e2e_test_data/libfuncs/consts#L7)):*
> ```
> 
> //! > cairo
> const V: felt252 = 100;
> ```

revert



_Code quote:_
```
const V: felt252 = 100;
```

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/starknet/storage.cairo` line 392 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6055#-O2Ue1gB7qo_J0wx-c8W:-O2Ue1gB7qo_J0wx-c8X:b3skoar) ([raw file](https://github.com/starkware-libs/cairo/blob/0fab857b7933042cf155abaef52008d3625b5433/corelib/src/starknet/storage.cairo#L392)):*
> ```Cairo
> /// }
> /// ```
> /// For a type `T` that implement `StorageNode` (e.g. `MyStruct` in the example above),
> ```

in what sense MyStruct implements StorageNode?

did you mean annotated with?



_Code quote:_
```Cairo
/// For a type `T` that implement `StorageNode` (e.g. `MyStruct` in the example above),
```

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/starknet/storage.cairo` line 400 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6055#-O2UhsHo31yNYNEPupBX:-O2UhsHo31yNYNEPupBY:b-vuiuyc) ([raw file](https://github.com/starkware-libs/cairo/blob/0fab857b7933042cf155abaef52008d3625b5433/corelib/src/starknet/storage.cairo#L400)):*
> ```Cairo
> ///    let a_value = self.my_struct.a.read();
> ///    let b_value = self.my_struct.b.entry(42).read();
> /// }
> ```

can you write a function that gets
self.my_struct



_Code quote:_
```Cairo
/// fn use_storage(self: @ContractState) {
///    let a_value = self.my_struct.a.read();
///    let b_value = self.my_struct.b.entry(42).read();
/// }
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6055)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @ArielElp, @ilyalesokhin-starkware, and @orizi)

___
*[`corelib/src/starknet/storage.cairo` line 353 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6055#-O2Uc-bWCMcowXm3FQ3e:-O36h1tk4qkDE-C-uSKM:bvudy74) ([raw file](https://github.com/starkware-libs/cairo/blob/0fab857b7933042cf155abaef52008d3625b5433/corelib/src/starknet/storage.cairo#L353)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what does bind mean?
</blockquote></details>

Edited.
___
*[`corelib/src/starknet/storage.cairo` line 365 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6055#-O2UdmvP58JE1weVZh2X:-O36hBLI-yaA1zia1dix:b-t2ceaw) ([raw file](https://github.com/starkware-libs/cairo/blob/0fab857b7933042cf155abaef52008d3625b5433/corelib/src/starknet/storage.cairo#L365)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Don't understand.

why are Structs which do not contain phantom types, storeable?
</blockquote></details>

Usually, if it is part of a storage struct. Edited.
___
*[`corelib/src/starknet/storage.cairo` line 392 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6055#-O2Ue1gB7qo_J0wx-c8W:-O36jSs415VT7DhmyR3m:b-2n76lg) ([raw file](https://github.com/starkware-libs/cairo/blob/0fab857b7933042cf155abaef52008d3625b5433/corelib/src/starknet/storage.cairo#L392)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

in what sense MyStruct implements StorageNode?

did you mean annotated with?
</blockquote></details>

There is implementation of `StorageNode<MyStruct>`. In the context of deref, the deref impl have a generic impl `+StorageNode<T>`, so I want to say that it works for types that have have this impl, any suggestion other than implements `StorageNode`?
___
*[`corelib/src/starknet/storage.cairo` line 400 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6055#-O2UhsHo31yNYNEPupBX:-O36k6XL8siPUwzslsVW:b-ulvtm5) ([raw file](https://github.com/starkware-libs/cairo/blob/0fab857b7933042cf155abaef52008d3625b5433/corelib/src/starknet/storage.cairo#L400)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

can you write a function that gets
self.my_struct
</blockquote></details>

The arg will be `StoragePath<MyStruct>`, I need to write such example but either in the `StoragePath` doc or in an external place.
___
*[`tests/e2e_test_data/libfuncs/consts` line 7 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6055#-O2UbqUy0iQUREfl9MHm:-O36kUN85C0MvMwV5YTH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e63517bed1e5e608639ab8c30eca561f13b111bd/tests/e2e_test_data/libfuncs/consts#L7)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

revert
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6055)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, and @orizi)

___
*[`corelib/src/starknet/storage/storage_node.cairo` line 65 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6055#-O36mXLo2VW6MqW0EfQl:-O36mXLo2VW6MqW0EfQm:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/61127572781393a9899be675846c20d2824ebfe4/corelib/src/starknet/storage/storage_node.cairo#L65)):*
> ```Cairo
> /// ```
> ///
> /// If we will annotate the member with `#[flat]`, the storage node will be flattened, and the
> ```





_Suggestion:_
```Cairo
/// If a member is annotated with `#[flat]`, the storage node will be flattened, and the
```
___
*[`corelib/src/starknet/storage/storage_node.cairo` line 76 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6055#-O36mhVy6RQ2gj84e6G5:-O36mhVz8CAEAaKtsSa-:b8stmxr) ([raw file](https://github.com/starkware-libs/cairo/blob/61127572781393a9899be675846c20d2824ebfe4/corelib/src/starknet/storage/storage_node.cairo#L76)):*
> ```Cairo
> /// }
> ///
> /// In this case, the storage node will be flattened, and both `self.a` and `self.my_struct.a` will
> ```

Does this generate an error?



_Code quote:_
```Cairo
`self.a` and `self.my_struct.a`
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6055)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @ArielElp, @ilyalesokhin-starkware, and @orizi)

___
*[`corelib/src/starknet/storage/storage_node.cairo` line 65 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6055#-O36mXLo2VW6MqW0EfQl:-O36oR9w8VfDpBb2giBm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/61127572781393a9899be675846c20d2824ebfe4/corelib/src/starknet/storage/storage_node.cairo#L65)):*
> ```Cairo
> /// ```
> ///
> /// If we will annotate the member with `#[flat]`, the storage node will be flattened, and the
> ```

Done.
___
*[`corelib/src/starknet/storage/storage_node.cairo` line 76 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6055#-O36mhVy6RQ2gj84e6G5:-O36neJ3D0wkjZtNcUNa:b7zxmhg) ([raw file](https://github.com/starkware-libs/cairo/blob/61127572781393a9899be675846c20d2824ebfe4/corelib/src/starknet/storage/storage_node.cairo#L76)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Does this generate an error?
</blockquote></details>

Not yet, Tomer is working on it (it'll be a warning for backwards compatibility).

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6055#-:-O36oq8CDtibBPMGkAJw:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArielElp and @orizi)

**Pull request merged**
