### PR TITLE
Allow plugins to defined additional diagnostic notes for errors from plugin generated file

### PR DESCRIPTION
**Pull request by maciektr**

### CODE REVIEW

**Comment by maciektr** [comment]
I'd like to enable plugins to define additional diagnostic notes that should be attached to each diagnostic located in a plugin generated file. 
This may be used for instance to mimic Rust's notes in diagnostics raised in code produced by procedural macros. 
```
error: struct literal body without path
 --> src/lib.rs:3:1
  |
3 | #[attribute_macro]
  | ^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the attribute macro `attribute_macro` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Review by orizi — CHANGES_REQUESTED** [review]
i like the concept.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6729#-:-OCXXMytCg9dZbC6L0ap:b-yxaz6m)* status: 0 of 28 files reviewed, 2 unresolved discussions (waiting on @maciektr, @mkaput, and @wawel37)

___
*[`crates/cairo-lang-defs/src/db.rs` line 434 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6729#-OCXXDmk5Nh6ABN4z9Dq:-OCXXDmk5Nh6ABN4z9Dr:b-kqxp0g) ([raw file](https://github.com/starkware-libs/cairo/blob/2f30f61b03b6311fdf366f538ae7067f0a8422b0/crates/cairo-lang-defs/src/db.rs#L434)):*
> ```XML
>     plugin_diagnostics: Vec<PluginDiagnostic>,
>     /// Diagnostic notes defined by a plugin for the given file.
>     diagnostics_notes: HashMap<FileId, Vec<DiagnosticNote>>,
> ```

additionally - consider adding here what this note actually means - also - i don't fully understand why is it a vector (as currently it is simply a string).



_Suggestion:_
```XML
    /// Diagnostic notes defined by a plugin for the given file.
    diagnostics_notes: OrderedHashMap<FileId, Vec<DiagnosticNote>>,
```
___
*[`crates/cairo-lang-defs/src/test.rs` line 225 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6729#-OCXXq8j5TtNuiDrAjhs:-OCXXq8k6fOC8OmBRmxh:b-u26q2f) ([raw file](https://github.com/starkware-libs/cairo/blob/2f30f61b03b6311fdf366f538ae7067f0a8422b0/crates/cairo-lang-defs/src/test.rs#L225)):*
> ```XML
>                         code_mappings: Default::default(),
>                         aux_data: None,
>                         diagnostics_notes: Vec::new(),
> ```

all around - just for us to easily changing the underlying implementation without going over all specific instances.



_Suggestion:_
```XML
                        diagnostics_notes: Default::default(),
```

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 25 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6729)* status: 25 of 28 files reviewed, 3 unresolved discussions (waiting on @maciektr and @wawel37)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6729#-OCXZ9y_EHnYoxjOCpDw:-OCXZ9y_EHnYoxjOCpDx:bf5fvbd) (no related file):*
why not add notes to `PluginDiagnostics` and then convert that into `DiagnosticEntry.notes` ?

**Comment by maciektr** [comment]
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

why not add notes to `PluginDiagnostics` and then convert that into `DiagnosticEntry.notes` ?
</blockquote></details>

@mkaput PluginDiagnostics only is not enough. PluginDiagnostics are ones returned from the plugin in the `diagnostics` field of the PluginResult. I want to be able to define additional info for all diagnostics raised for the fails I produce - i.e. syntax, semantic, etc.

**Review by maciektr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6729)* status: 1 of 28 files reviewed, 3 unresolved discussions (waiting on @mkaput, @orizi, and @wawel37)

___
*[`crates/cairo-lang-defs/src/db.rs` line 434 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6729#-OCXXDmk5Nh6ABN4z9Dq:-OCXfzUm5AWSV-HIt1UX:b-cqqvw9) ([raw file](https://github.com/starkware-libs/cairo/blob/2f30f61b03b6311fdf366f538ae7067f0a8422b0/crates/cairo-lang-defs/src/db.rs#L434)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

additionally - consider adding here what this note actually means - also - i don't fully understand why is it a vector (as currently it is simply a string).
</blockquote></details>

I just thought we might as well accept more than one note - change to single String 
___
*[`crates/cairo-lang-defs/src/test.rs` line 225 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6729#-OCXXq8j5TtNuiDrAjhs:-OCXcNRU3J7pbYCc6bOO:brg3c43) ([raw file](https://github.com/starkware-libs/cairo/blob/2f30f61b03b6311fdf366f538ae7067f0a8422b0/crates/cairo-lang-defs/src/test.rs#L225)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

all around - just for us to easily changing the underlying implementation without going over all specific instances.
</blockquote></details>

Done.  :pray:

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 25 of 27 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6729)* status: 28 of 29 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @maciektr, @mkaput, @piotmag769, and @wawel37)

___
*[`crates/cairo-lang-defs/src/db.rs` line 434 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6729#-OCXXDmk5Nh6ABN4z9Dq:-OCXmYoo2EryjR0DONCH:b-952llu) ([raw file](https://github.com/starkware-libs/cairo/blob/2f30f61b03b6311fdf366f538ae7067f0a8422b0/crates/cairo-lang-defs/src/db.rs#L434)):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

I just thought we might as well accept more than one note - change to single String
</blockquote></details>

it sounds like something that may happen - i just don't really see a reason if it is already only added in a single spot.
___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 174 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6729#-OCXnKqp9pettwHM5Izv:-OCXnKqp9pettwHM5Izw:bymusaq) ([raw file](https://github.com/starkware-libs/cairo/blob/4653e53e172cb0679f53d855fa4abadc6b07b98f/crates/cairo-lang-compiler/src/diagnostics.rs#L174)):*
> ```XML
>             for module_id in modules.iter() {
>                 let diagnostic_notes =
>                     db.module_plugin_diagnostics_notes(*module_id).unwrap_or_default();
> ```

should this somehow be added while mapping the diagnostics?
___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 222 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6729#-OCXnGHsE43D05jns-Tm:-OCXnGHsE43D05jns-Tn:b78km5l) ([raw file](https://github.com/starkware-libs/cairo/blob/4653e53e172cb0679f53d855fa4abadc6b07b98f/crates/cairo-lang-compiler/src/diagnostics.rs#L222)):*
> ```XML
>         group: Diagnostics<TEntry>,
>         skip_warnings: bool,
>         file_notes: Arc<OrderedHashMap<FileId, DiagnosticNote>>,
> ```

why not?



_Suggestion:_
```XML
        file_notes: &OrderedHashMap<FileId, DiagnosticNote>,
```

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 24 of 27 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6729)* status: 28 of 29 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @maciektr, @piotmag769, and @wawel37)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6729#-OCXZ9y_EHnYoxjOCpDw:-OCXrhUG6WT3TbvP06B6:b-9398qb) (no related file):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

@mkaput PluginDiagnostics only is not enough. PluginDiagnostics are ones returned from the plugin in the `diagnostics` field of the PluginResult. I want to be able to define additional info for all diagnostics raised for the fails I produce - i.e. syntax, semantic, etc.
</blockquote></details>

ok, so my thinking in more general form now: shouldn't this note be produced while converting PluginDiagnostics into DiagnosticsEntry? I think that's what Ori asks for here also: https://reviewable.io/reviews/starkware-libs/cairo/6729#-OCXnKqp9pettwHM5Izv

**Comment by maciektr** [comment]
> PluginDiagnostics into DiagnosticsEntry

But I want to also show this notes, for types of Diagnostics that I believe are never `PluginDiagnostic` - like SemanticDiagnostics raised in the virtual files.

**Comment by maciektr** [comment]
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

> PluginDiagnostics into DiagnosticsEntry

But I want to also show this notes, for types of Diagnostics that I believe are never `PluginDiagnostic` - like SemanticDiagnostics raised in the virtual files.
</blockquote></details>

Please correct me if I am wrong :thinking:

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6729)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @maciektr, @mkaput, @piotmag769, and @wawel37)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6729#-OCXZ9y_EHnYoxjOCpDw:-OCXu4e54MvxxIJPxAd0:bdtlau2) (no related file):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

Please correct me if I am wrong :thinking:
</blockquote></details>

discussing this offline

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6729)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @maciektr, @piotmag769, and @wawel37)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6729#-OCXZ9y_EHnYoxjOCpDw:-OCXzx977lb-9oi2xEk3:b96d701) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

discussing this offline
</blockquote></details>

ok looks like i misunderstood this PR

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6729)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @maciektr, @piotmag769, and @wawel37)

**Review by maciektr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6729)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @mkaput, @orizi, @piotmag769, and @wawel37)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 174 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6729#-OCXnKqp9pettwHM5Izv:-OCY1G2x6oF6kdRU8K8M:ba4bi7r) ([raw file](https://github.com/starkware-libs/cairo/blob/4653e53e172cb0679f53d855fa4abadc6b07b98f/crates/cairo-lang-compiler/src/diagnostics.rs#L174)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

should this somehow be added while mapping the diagnostics?
</blockquote></details>

Sorry, I don't think I understand what you mean? :thinking: 
___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 222 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6729#-OCXnGHsE43D05jns-Tm:-OCY1KU1-TvJ7eE9Ad5z:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4653e53e172cb0679f53d855fa4abadc6b07b98f/crates/cairo-lang-compiler/src/diagnostics.rs#L222)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why not?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-defs/src/db.rs` line 434 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6729#-OCXXDmk5Nh6ABN4z9Dq:-OCY1Lml0WVBMh5EVGut:b-5n0a5v) ([raw file](https://github.com/starkware-libs/cairo/blob/2f30f61b03b6311fdf366f538ae7067f0a8422b0/crates/cairo-lang-defs/src/db.rs#L434)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it sounds like something that may happen - i just don't really see a reason if it is already only added in a single spot.
</blockquote></details>

Agree :+1:

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6729)* status: 28 of 29 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @integraledelebesgue, @mkaput, @piotmag769, and @wawel37)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 174 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6729#-OCXnKqp9pettwHM5Izv:-OCY5WvJ7VftUUBf-GDX:bukw4a7) ([raw file](https://github.com/starkware-libs/cairo/blob/4653e53e172cb0679f53d855fa4abadc6b07b98f/crates/cairo-lang-compiler/src/diagnostics.rs#L174)):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

Sorry, I don't think I understand what you mean? :thinking:
</blockquote></details>

a diagnostics that you got from a file - may have been created by code generated from file `A` - by plugin `B` - when mapped back - maybe the note should be added there.

(and if there were several layers - maybe more so)

**Comment by maciektr** [comment]
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 174 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6729#-OCXnKqp9pettwHM5Izv:-OCY7lqWBJ9xYCsCEN1q:b-9ecbrn) ([raw file](https://github.com/starkware-libs/cairo/blob/4653e53e172cb0679f53d855fa4abadc6b07b98f/crates/cairo-lang-compiler/src/diagnostics.rs#L174)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

a diagnostics that you got from a file - may have been created by code generated from file `A` - by plugin `B` - when mapped back - maybe the note should be added there.

(and if there were several layers - maybe more so)
</blockquote></details>

Oh, but my understanding was that the `DiagnosticLocation` always points to the original location, and only `user_location` (https://github.com/starkware-libs/cairo/blob/484222eebaf9411562dcd9079a3e93d3c9789ff4/crates/cairo-lang-diagnostics/src/diagnostics.rs#L69) is translated :thinking: (and used for formatting https://github.com/starkware-libs/cairo/blob/484222eebaf9411562dcd9079a3e93d3c9789ff4/crates/cairo-lang-diagnostics/src/diagnostics.rs#L93) 
Is this not true?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6729)* status: 28 of 29 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @integraledelebesgue, @mkaput, @piotmag769, and @wawel37)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 174 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6729#-OCXnKqp9pettwHM5Izv:-OCY982XAA8G9Xocjjj3:bwe52pn) ([raw file](https://github.com/starkware-libs/cairo/blob/4653e53e172cb0679f53d855fa4abadc6b07b98f/crates/cairo-lang-compiler/src/diagnostics.rs#L174)):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

Oh, but my understanding was that the `DiagnosticLocation` always points to the original location, and only `user_location` (https://github.com/starkware-libs/cairo/blob/484222eebaf9411562dcd9079a3e93d3c9789ff4/crates/cairo-lang-diagnostics/src/diagnostics.rs#L69) is translated :thinking: (and used for formatting https://github.com/starkware-libs/cairo/blob/484222eebaf9411562dcd9079a3e93d3c9789ff4/crates/cairo-lang-diagnostics/src/diagnostics.rs#L93) 
Is this not true?
</blockquote></details>

it is true - therefore the place to add the notes is probably during this mapping - that is my point.

**Review by piotmag769 — CHANGES_REQUESTED** [review]
> Reviewed 24 of 27 files at r2, 2 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6729)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @maciektr, @mkaput, and @wawel37)

___
*[`crates/cairo-lang-defs/src/plugin.rs` line 53 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6729#-OCYG6oM9qVB3H-On_tZ:-OCYG6oM9qVB3H-On_t_:b-qyjkc5) ([raw file](https://github.com/starkware-libs/cairo/blob/e583661dcb7cc40674f738e7dc4c579e7ad1ba85/crates/cairo-lang-defs/src/plugin.rs#L53)):*
> ```XML
>     /// Arbitrary data that the plugin generates along with the file.
>     pub aux_data: Option<DynGeneratedFileAuxData>,
>     /// Diagnostic notes for the file.
> ```

Comment is inconsistent (plural form) + doesn't explain the purpose
___
*[`crates/cairo-lang-defs/src/db.rs` line 256 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6729#-OCYDdqY7N5JakcCJsuk:-OCYDdqY7N5JakcCJsul:b-vbw624) ([raw file](https://github.com/starkware-libs/cairo/blob/e583661dcb7cc40674f738e7dc4c579e7ad1ba85/crates/cairo-lang-defs/src/db.rs#L256)):*
> ```XML
>         module_id: ModuleId,
>     ) -> Maybe<Arc<[(ModuleFileId, PluginDiagnostic)]>>;
>     /// Diagnostic notes defined by a plugin for the given file.
> ```

The comment is inaccurate (you don't specify any file in the input). Also doesn't explain the purpose, without the PR description (as a code reader) I would never know why you map `FileId` to `DiagnosticNote` as one to one relation.

Explain the purpose in other comments too :pray:

**Review by wawel37 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6729)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @maciektr, and @mkaput)

___
*[`crates/cairo-lang-defs/src/db.rs` line 435 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6729#-OCYJzA16KdU9eMkzbuR:-OCYJzA16KdU9eMkzbuS:b2v74eb) ([raw file](https://github.com/starkware-libs/cairo/blob/e583661dcb7cc40674f738e7dc4c579e7ad1ba85/crates/cairo-lang-defs/src/db.rs#L435)):*
> ```XML
>     /// Diagnostic note defined by a plugin for the given file.
>     /// Diagnostic notes are added with `note: ` prefix at the end of diagnostic display.
>     diagnostics_notes: OrderedHashMap<FileId, DiagnosticNote>,
> ```

Nit: Maybe it would be nice to define some type alias for `diagnostics_notes`, as this specific type is used throughout the whole diagnostics process, down to `format_with_severity`

**Review by mkaput — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6729)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @maciektr, and @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6729)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @maciektr, and @mkaput)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 174 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6729#-OCXnKqp9pettwHM5Izv:-OCbsO9w28NWhB1HINEc:bhl1n9m) ([raw file](https://github.com/starkware-libs/cairo/blob/4653e53e172cb0679f53d855fa4abadc6b07b98f/crates/cairo-lang-compiler/src/diagnostics.rs#L174)):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

Sorry, this may be a dumb question but I still don't see what you mean, since the mapping of diagnostic location happens in DebugWithDb when formatting the diagnostic.

https://github.com/starkware-libs/cairo/blob/484222eebaf9411562dcd9079a3e93d3c9789ff4/crates/cairo-lang-diagnostics/src/diagnostics.rs#L217

https://github.com/starkware-libs/cairo/blob/484222eebaf9411562dcd9079a3e93d3c9789ff4/crates/cairo-lang-diagnostics/src/diagnostics.rs#L91-L93
</blockquote></details>

so you would add only the note only from the last file in the chain - my question is - what about the previous notes?
original code `A` - generated code `B` - caused an additional generated code `C`.

if you have diagnostics on `C` - you would only get notes of `C` and not of `B` as well.

**Comment by maciektr** [comment]
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 174 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6729#-OCXnKqp9pettwHM5Izv:-OCczmTX2FP5Fud1Lcqo:btkg9g1) ([raw file](https://github.com/starkware-libs/cairo/blob/4653e53e172cb0679f53d855fa4abadc6b07b98f/crates/cairo-lang-compiler/src/diagnostics.rs#L174)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

so you would add only the note only from the last file in the chain - my question is - what about the previous notes?
original code `A` - generated code `B` - caused an additional generated code `C`.

if you have diagnostics on `C` - you would only get notes of `C` and not of `B` as well.
</blockquote></details>

Oh, I understand now, completely agree, thank you!

**Review by maciektr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6729)* status: 24 of 34 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-defs/src/db.rs` line 256 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6729#-OCYDdqY7N5JakcCJsuk:-OCczq82DgIOsYI4NfV6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e583661dcb7cc40674f738e7dc4c579e7ad1ba85/crates/cairo-lang-defs/src/db.rs#L256)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

The comment is inaccurate (you don't specify any file in the input). Also doesn't explain the purpose, without the PR description (as a code reader) I would never know why you map `FileId` to `DiagnosticNote` as one to one relation.

Explain the purpose in other comments too :pray:
</blockquote></details>

Done.
___
*[`crates/cairo-lang-defs/src/plugin.rs` line 53 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6729#-OCYG6oM9qVB3H-On_tZ:-OCczrCa0jP2aI--9QSw:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e583661dcb7cc40674f738e7dc4c579e7ad1ba85/crates/cairo-lang-defs/src/plugin.rs#L53)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Comment is inconsistent (plural form) + doesn't explain the purpose
</blockquote></details>

Done.

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 7 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6729)* status: 31 of 34 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @integraledelebesgue, @mkaput, @orizi, and @wawel37)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 10 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6729)* status: 31 of 34 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @maciektr, @mkaput, @piotmag769, and @wawel37)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 174 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6729#-OCXnKqp9pettwHM5Izv:-OCd2Fh3EsMPJgg603P7:b-gy3kav) ([raw file](https://github.com/starkware-libs/cairo/blob/4653e53e172cb0679f53d855fa4abadc6b07b98f/crates/cairo-lang-compiler/src/diagnostics.rs#L174)):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

Oh, I understand now, completely agree, thank you!
</blockquote></details>

is this still required now?
i'm assuming you are already getting the diagnostics past remappings.
___
*[`crates/cairo-lang-diagnostics/src/diagnostics.rs` line 79 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6729#-OCd1_2w3P-e03XIgfo5:-OCd1_2w3P-e03XIgfo6:bb7f2bf) ([raw file](https://github.com/starkware-libs/cairo/blob/5f9b57d86a8c53582ca4408ac70682393586ca2c/crates/cairo-lang-diagnostics/src/diagnostics.rs#L79)):*
> ```XML
>     }
> 
>     pub fn user_location_with_notes(
> ```

doc.

**Comment by maciektr** [comment]
*[`crates/cairo-lang-diagnostics/src/diagnostics.rs` line 79 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6729#-OCd1_2w3P-e03XIgfo5:-OCd41kR6jJpNxHMj3CZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5f9b57d86a8c53582ca4408ac70682393586ca2c/crates/cairo-lang-diagnostics/src/diagnostics.rs#L79)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc.
</blockquote></details>

Done.

**Comment by maciektr** [comment]
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 174 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6729#-OCXnKqp9pettwHM5Izv:-OCd4Amp-Rt35lyHR04H:b-p4z8bc) ([raw file](https://github.com/starkware-libs/cairo/blob/4653e53e172cb0679f53d855fa4abadc6b07b98f/crates/cairo-lang-compiler/src/diagnostics.rs#L174)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is this still required now?
i'm assuming you are already getting the diagnostics past remappings.
</blockquote></details>

I am getting them in `format_with_severity`, where I translate the location. If you have a better place for this, please let me know :pray:

**Review by piotmag769 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 10 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6729#-:-OCd4U1mAOcuNAIzln0Y:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @maciektr, @mkaput, @orizi, and @wawel37)

___
*[`crates/cairo-lang-diagnostics/src/diagnostics.rs` line 79 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6729#-OCd2uVI2W3iNoKl6G_r:-OCd2uVI2W3iNoKl6G_s:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5f9b57d86a8c53582ca4408ac70682393586ca2c/crates/cairo-lang-diagnostics/src/diagnostics.rs#L79)):*
> ```XML
>     }
> 
>     pub fn user_location_with_notes(
> ```





_Suggestion:_
```XML
user_location_with_plugin_notes
```

**Comment by maciektr** [comment]
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 174 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6729#-OCXnKqp9pettwHM5Izv:-OCd4Vkp3AsRtgbbi2dZ:blm65fv) ([raw file](https://github.com/starkware-libs/cairo/blob/4653e53e172cb0679f53d855fa4abadc6b07b98f/crates/cairo-lang-compiler/src/diagnostics.rs#L174)):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

I am getting them in `format_with_severity`, where I translate the location. If you have a better place for this, please let me know :pray:
</blockquote></details>

(TEntry::DbType may not have this query, as it's only FilesGroup)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6729)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @maciektr, @mkaput, and @wawel37)

___
*[`crates/cairo-lang-plugins/src/test.rs` line 206 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6729#-OCd8PyV1JwueCoViVxK:-OCd8PyV1JwueCoViVxL:bv6ttq7) ([raw file](https://github.com/starkware-libs/cairo/blob/aacf270c46070f0a5d48b9f4e7785cc7602147a7/crates/cairo-lang-plugins/src/test.rs#L206)):*
> ```XML
> #[derive(Debug, Default)]
> struct FirstNotePlugin;
> impl MacroPlugin for FirstNotePlugin {
> ```

maybe just add these to the "general" test and add as test cases there directly?

**Review by Arcticae — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r3, 2 of 10 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6729#-:-OCd8c7p6IAjpfKl-Bv-:bg7igkv)* status: all files reviewed, 3 unresolved discussions (waiting on @Draggu, @integraledelebesgue, @maciektr, @mkaput, @orizi, and @wawel37)

**Review by maciektr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6729)* status: 33 of 41 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @mkaput, @orizi, @piotmag769, and @wawel37)

___
*[`crates/cairo-lang-plugins/src/test.rs` line 206 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6729#-OCd8PyV1JwueCoViVxK:-OCdO9jm-T5zNjQhpWsz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/aacf270c46070f0a5d48b9f4e7785cc7602147a7/crates/cairo-lang-plugins/src/test.rs#L206)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe just add these to the "general" test and add as test cases there directly?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-diagnostics/src/diagnostics.rs` line 79 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6729#-OCd2uVI2W3iNoKl6G_r:-OCdO8rT4r-RuAHhUK7v:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5f9b57d86a8c53582ca4408ac70682393586ca2c/crates/cairo-lang-diagnostics/src/diagnostics.rs#L79)):*
> ```XML
>     }
> 
>     pub fn user_location_with_notes(
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 7 of 8 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6729#-:-OCdUVB9CUsK2I2cgNF7:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Draggu, @integraledelebesgue, @mkaput, @piotmag769, and @wawel37)

**Review by piotmag769 — APPROVED** [review]
> Reviewed 7 of 8 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6729)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Draggu, @integraledelebesgue, @mkaput, and @wawel37)

**Pull request merged**
