### PR TITLE
Cleaner correcter SCC phases

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2613)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2613** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2613" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2613?utm_source=stack-comment).

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2613#-:-NRXvk2oCIx4UDLPeotn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2613)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 111 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2613#-NRYEdKs7PKVJ5maaVPN:-NRYEdKs7PKVJ5maaVPO:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/168ff878a62316f93a0f3a4518479bd113d65583/crates/cairo-lang-lowering/src/db.rs#L111)):*
> ```XML
> 
>     #[salsa::invoke(crate::implicits::scc_implicits)]
>     fn scc_implicits(&self, function: ConcreteSCCRepresentative) -> Maybe<Vec<TypeId>>;
> ```

doc

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2613)* status: all files reviewed, 5 unresolved discussions (waiting on @yuvalsw)

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2613)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/implicits/mod.rs` line 199 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2613#-NRYGITc0x6UdOsR3QdQ:-NRYdyTN5VP_Ca_KXMir:bf32diu) ([raw file](https://github.com/starkware-libs/cairo/blob/168ff878a62316f93a0f3a4518479bd113d65583/crates/cairo-lang-lowering/src/implicits/mod.rs#L199)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Do you have another suggestion on how to add a non query method in the DB?
</blockquote></details>

Why shouldn't it be a query?
Also - if T below is only LoweringGroup, why not implement only for it?
___
*[`crates/cairo-lang-lowering/src/panic/mod.rs` line 313 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2613#-NRYI_eaDshPPlqm6AiS:-NRYYqfq1F69wKXIqVQf:bo32g6q) ([raw file](https://github.com/starkware-libs/cairo/blob/168ff878a62316f93a0f3a4518479bd113d65583/crates/cairo-lang-lowering/src/panic/mod.rs#L313)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Noted.
</blockquote></details>

Why only noted? Please explain your opinion if you don't agree with something...
IMO the if-return method is good on one of 2 cases:
1. it prevents indentation.
2. the if condition is somewhat considered an error case / trivial success case.
If the 2 options are equally normal, I think if-else is better.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2613)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/implicits/mod.rs` line 199 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2613#-NRYGITc0x6UdOsR3QdQ:-NRYneev3vkUqtwxdHWr:b-b2n0z1) ([raw file](https://github.com/starkware-libs/cairo/blob/168ff878a62316f93a0f3a4518479bd113d65583/crates/cairo-lang-lowering/src/implicits/mod.rs#L199)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Why shouldn't it be a query?
Also - if T below is only LoweringGroup, why not implement only for it?
</blockquote></details>

All this does is calling 2 queries. I think caching it is a waste, and also bloats the db code with too many queries.
LoweringGroup is not a type. I can only impl things for types.
___
*[`crates/cairo-lang-lowering/src/panic/mod.rs` line 313 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2613#-NRYI_eaDshPPlqm6AiS:-NRYnz1rDpuqzuTK11MF:b-acryot) ([raw file](https://github.com/starkware-libs/cairo/blob/168ff878a62316f93a0f3a4518479bd113d65583/crates/cairo-lang-lowering/src/panic/mod.rs#L313)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Why only noted? Please explain your opinion if you don't agree with something...
IMO the if-return method is good on one of 2 cases:
1. it prevents indentation.
2. the if condition is somewhat considered an error case / trivial success case.
If the 2 options are equally normal, I think if-else is better.
</blockquote></details>

I think it's easier to reason about code with early returns, even when there are only 2 cases. It's also more consistent.
For example, if I had 3 Cases, I'd prefer 2 early returns than an early return and an if.

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2613)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2613#-:-NRb6sWQ8gCIGqaUfCsF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
