### PR TITLE
Bug fix: Move push_values before label.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2217)

### CODE REVIEW

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2217)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/inline` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2217#-NOn2EAf19hfjv2Z5lk2:-NOn2EAgAnm-t3dsGlWW:b4nb105) ([raw file](https://github.com/starkware-libs/cairo/blob/a67afa98f10b5788781527e36796706090cd906a/crates/cairo-lang-sierra-generator/src/function_generator_test_data/inline#L84)):*
> ```
> #[inline(always)]
> fn inlined_expect(option: Option::<@felt>) -> @felt {
> match option {
> ```

Fix indentation.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2217)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/inline` line 72 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2217#-NOn2G-eAuGPkZPQnovw:-NOn2G-fEKtYWKtMHhMP:b-bqdia9) ([raw file](https://github.com/starkware-libs/cairo/blob/a67afa98f10b5788781527e36796706090cd906a/crates/cairo-lang-sierra-generator/src/function_generator_test_data/inline#L72)):*
> ```
> //! > function
> fn foo(a : Array::<felt>) -> @felt {
>   let t: Option::<@felt> = a.get(0_u32);
> ```

Identation should be 4 spaces.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2217)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/inline` line 71 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2217#-NOn2JPZDJFTi6USr-Lw:-NOn2JPZDJFTi6USr-Lx:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/a67afa98f10b5788781527e36796706090cd906a/crates/cairo-lang-sierra-generator/src/function_generator_test_data/inline#L71)):*
> ```
> 
> //! > function
> fn foo(a : Array::<felt>) -> @felt {
> ```

.



_Suggestion:_
```
fn foo(a: Array::<felt>) -> @felt {
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2217#-:-NOn3-r-6HYoM9rKwgxQ:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2217)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/inline` line 71 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2217#-NOn2JPZDJFTi6USr-Lw:-NOn2YoH2nxaVBGGRihw:b-53fzo0) ([raw file](https://github.com/starkware-libs/cairo/blob/a67afa98f10b5788781527e36796706090cd906a/crates/cairo-lang-sierra-generator/src/function_generator_test_data/inline#L71)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

.
</blockquote></details>

Pass `a` by snapshot to slightly reduce Sierra size.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2217)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/inline` line 71 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2217#-NOn2JPZDJFTi6USr-Lw:-NOn2o9Z-UuC4tboLUGz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a67afa98f10b5788781527e36796706090cd906a/crates/cairo-lang-sierra-generator/src/function_generator_test_data/inline#L71)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/inline` line 72 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2217#-NOn2G-eAuGPkZPQnovw:-NOn2qvEArRfa9FOb0gx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a67afa98f10b5788781527e36796706090cd906a/crates/cairo-lang-sierra-generator/src/function_generator_test_data/inline#L72)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Identation should be 4 spaces.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/inline` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2217#-NOn2EAf19hfjv2Z5lk2:-NOn2xHACTkA34-b-xeT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a67afa98f10b5788781527e36796706090cd906a/crates/cairo-lang-sierra-generator/src/function_generator_test_data/inline#L84)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Fix indentation.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2217)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/inline` line 71 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2217#-NOn2JPZDJFTi6USr-Lw:-NOn41_54FAVR8YPRrYt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a67afa98f10b5788781527e36796706090cd906a/crates/cairo-lang-sierra-generator/src/function_generator_test_data/inline#L71)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2217)* status: all files reviewed, 3 unresolved discussions (waiting on @liorgold2)

**Review by liorgold2 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2217)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2217#-:-NOn6c1L7bmfSF2pv-5v:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
