### PR TITLE
Make sure there are no goto to arm targets.

### LINKED ISSUE #3211: bug: Multiple jumps to arm blocks are not allowed.
# Bug Report

**Cairo version:** bcebb2e3

**Current behavior:**

The compiler panics when trying to compile and run this test:

```rust

impl U256TryIntoU64 of TryInto<u256, u64> {
    #[inline(always)]
    fn try_into(self: u256) -> Option<u64> {
        if (self.high == 0) {
            self.low.try_into()
        } else {
            Option::None(())
        }
    }
}

#[test]
fn test_u256_tryinto_u64() {
    let a = u256 { low: 64, high: 0 };
    let b: u64 = a.try_into().unwrap();
    assert(b == 64, 'b conv');
}

```

The resulting error is:

```sh
thread 'main' panicked at 'Multiple jumps to arm blocks are not allowed.', crates/cairo-lang-lowering/src/implicits/mod.rs:148:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

When I remove the `#[inline(always)]` arg, the test passes.

**Expected behavior:**

I expect the compiler to compile the code regardless if the code is marked as inline or not.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
Fixes #3211.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3264)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3264)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3264#-NWfscSu7YRiobqdcsvL:-NWfscSu7YRiobqdcsvM:b-aze7lt) (no related file):*
also add the issue to the bug_samples dir?

___
___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3264#-NWfsFX5EV8BJcsiJL-r:-NWfsFX5EV8BJcsiJL-s:bb6x13q) ([raw file](https://github.com/starkware-libs/cairo/blob/53bcea495081bbf60b0342171637888f2a2d27ba/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L68)):*
> ```XML
>         for block in new_blocks.into_iter() {
>             lowered.blocks.push(block);
>         }
> ```

IIRC



_Suggestion:_
```XML
        lowered.blocks.extend(new_blocks.into_iter());
```

**Comment by ilyalesokhin-starkware** [comment]
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

also add the issue to the bug_samples dir?
</blockquote></details>

Should the issue replace the test that I've added?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3264)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3264#-NWfscSu7YRiobqdcsvL:-NWft5Ba-wInw7gDYA4r:b-3jmhnk) (no related file):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Should the issue replace the test that I've added?
</blockquote></details>

no - having both is totally fine.

___

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3264)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/test.cairo` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3264#-NWg3__w0EmPmeYmHQzC:-NWg3__x51XnpqsT4FSq:b-giwxba) ([raw file](https://github.com/starkware-libs/cairo/blob/a68c03a5f6c4eca197d2a8e79d16c255d4bd6da8/corelib/src/test.cairo#L1)):*
> ```Cairo
> mod secp256k1_test;
> ```

revert probably
___
*[`corelib/src/test/keccak_test.cairo` line 5 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3264#-NWg3dcZ88DJMGHJtlB1:-NWg3dcZ88DJMGHJtlB2:b-byuvx0) ([raw file](https://github.com/starkware-libs/cairo/blob/a68c03a5f6c4eca197d2a8e79d16c255d4bd6da8/corelib/src/test/keccak_test.cairo#L5)):*
> ```Cairo
> use core::traits::Into;
> use core::traits::Default;
> use starknet::SyscallResultTrait;
> ```

seems unrelated as well.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3264)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/test.cairo` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3264#-NWg3__w0EmPmeYmHQzC:-NWg9H8n5wbBe7AK1pLg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a68c03a5f6c4eca197d2a8e79d16c255d4bd6da8/corelib/src/test.cairo#L1)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

revert probably
</blockquote></details>

Done.
___
*[`corelib/src/test/keccak_test.cairo` line 5 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3264#-NWg3dcZ88DJMGHJtlB1:-NWg9HPg4bRs1RoqIhA-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a68c03a5f6c4eca197d2a8e79d16c255d4bd6da8/corelib/src/test/keccak_test.cairo#L5)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

seems unrelated as well.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3264#-:-NWgHPsiCQWl3giyCNcf:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3264)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
