### PR TITLE
fixed range check gas cost for sha256 syscall

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5370)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 353 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5370#-NuwS_Cr89y8vyCrFd85:-NuwS_Cr89y8vyCrFd86:bnudosc) ([raw file](https://github.com/starkware-libs/cairo/blob/c219f8bd25d315ba77581e07198821dd67929109/crates/cairo-lang-runner/src/casm_run/mod.rs#L353)):*
> ```XML
>     pub const KECCAK: usize = 0;
>     pub const KECCAK_ROUND_COST: usize = 180000;
>     pub const SHA256_PROCESS_BLOCK: usize = 2000 * STEP + 6 * RANGE_CHECK;
> ```

Does this include the range check in the syscall?



_Code quote:_
```XML
6 * RANGE_CHECK;
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5370)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi and @TomerStarkware)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 353 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5370#-NuwS_Cr89y8vyCrFd85:-NuwSx5C26nNiLOQy1Rn:b-oeojs5) ([raw file](https://github.com/starkware-libs/cairo/blob/c219f8bd25d315ba77581e07198821dd67929109/crates/cairo-lang-runner/src/casm_run/mod.rs#L353)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Does this include the range check in the syscall?
</blockquote></details>

let fix this value after it works in the os

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5370)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 353 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5370#-NuwS_Cr89y8vyCrFd85:-NuwTysDCmn9Fu6WKxep:bx2rb2q) ([raw file](https://github.com/starkware-libs/cairo/blob/c219f8bd25d315ba77581e07198821dd67929109/crates/cairo-lang-runner/src/casm_run/mod.rs#L353)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

let fix this value after it works in the os
</blockquote></details>

in the syscall itself there is no range_check, in finalize there are 6*7 range checks per 7 blocks

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 353 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5370#-NuwS_Cr89y8vyCrFd85:-NuwnX_pC4J73MZpVjEj:b631msz) ([raw file](https://github.com/starkware-libs/cairo/blob/c219f8bd25d315ba77581e07198821dd67929109/crates/cairo-lang-runner/src/casm_run/mod.rs#L353)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

in the syscall itself there is no range_check, in finalize there are 6*7 range checks per 7 blocks
</blockquote></details>

There should be a range_check  or 2 for the gas check in the syscall.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5370)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5370)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 353 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5370#-NuwS_Cr89y8vyCrFd85:-Nz_GegBEtVpLFmHaBSu:b-589i6t) ([raw file](https://github.com/starkware-libs/cairo/blob/c219f8bd25d315ba77581e07198821dd67929109/crates/cairo-lang-runner/src/casm_run/mod.rs#L353)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

There should be a range_check  or 2 for the gas check in the syscall.
</blockquote></details>

don't i need the 65 range checks like in the blockifier

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5370)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5370#-:-O-eHUsf8Pi2SloLBLKV:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
