### PR TITLE
Lowering snapshot support for structs and enums

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2136)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 11 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2136#-:-NOIwCupA5EfoUAZvLdv:bnfp4nl)* status: 10 of 13 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 485 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2136#-NOIvAZQ5CBgIKi5-RVa:-NOIvAZQ5CBgIKi5-RVb:b2nhdkj) ([raw file](https://github.com/starkware-libs/cairo/blob/3c35f55c2dbfab7103c90cef0eab51f757e2815a/crates/cairo-lang-semantic/src/types.rs#L485)):*
> ```XML
> }
> 
> pub fn peel_snapshots(db: &dyn SemanticGroup, ty: TypeId) -> (usize, TypeLongId) {
> ```

Doc
___
*[`crates/cairo-lang-semantic/src/types.rs` line 495 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2136#-NOIvBX8AAPz_bUQyLfZ:-NOIvBX8AAPz_bUQyLf_:b2nhdkj) ([raw file](https://github.com/starkware-libs/cairo/blob/3c35f55c2dbfab7103c90cef0eab51f757e2815a/crates/cairo-lang-semantic/src/types.rs#L495)):*
> ```XML
> }
> 
> pub fn wrap_in_snapshots(db: &dyn SemanticGroup, ty: TypeId, n_snapshots: usize) -> TypeId {
> ```

Doc
___
*[`crates/cairo-lang-sierra-generator/src/types.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2136#-NOIvlONEmYqB5TieiF8:-NOIvlONEmYqB5TieiF9:b-uxakjj) ([raw file](https://github.com/starkware-libs/cairo/blob/3c35f55c2dbfab7103c90cef0eab51f757e2815a/crates/cairo-lang-sierra-generator/src/types.rs#L94)):*
> ```XML
>             }))
>         }
>         // TODO(spapini): Maybe don't always wrap in Snapshot, since Sierra doesn't like it.
> ```

You can use the type dupability info to decide to remove snapshots recursively

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2136)* status: 11 of 13 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 710 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2136#-NOIwNGL-VmkWkyE_29q:-NOIwNGL-VmkWkyE_29r:b2nhdkj) ([raw file](https://github.com/starkware-libs/cairo/blob/3c35f55c2dbfab7103c90cef0eab51f757e2815a/crates/cairo-lang-lowering/src/lower/mod.rs#L710)):*
> ```XML
> }
> 
> struct EnumDetails {
> ```

Doc

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2136)* status: 9 of 13 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 710 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2136#-NOIwNGL-VmkWkyE_29q:-NOJ5XRSC2Ft5rEuTpL9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3c35f55c2dbfab7103c90cef0eab51f757e2815a/crates/cairo-lang-lowering/src/lower/mod.rs#L710)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/types.rs` line 485 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2136#-NOIvAZQ5CBgIKi5-RVa:-NOJ5Zon1nsfRwam9gN1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3c35f55c2dbfab7103c90cef0eab51f757e2815a/crates/cairo-lang-semantic/src/types.rs#L485)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/types.rs` line 495 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2136#-NOIvBX8AAPz_bUQyLfZ:-NOJ5_6tE58JjR6My7-y:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3c35f55c2dbfab7103c90cef0eab51f757e2815a/crates/cairo-lang-semantic/src/types.rs#L495)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/types.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2136#-NOIvlONEmYqB5TieiF8:-NOJ5Ir_-PmTWccqwswy:bxwd9zc) ([raw file](https://github.com/starkware-libs/cairo/blob/3c35f55c2dbfab7103c90cef0eab51f757e2815a/crates/cairo-lang-sierra-generator/src/types.rs#L94)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

You can use the type dupability info to decide to remove snapshots recursively 
</blockquote></details>

The comment is old, I used your `snapshot_ty` to do it for me:)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 13 files at r1, 1 of 1 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2136)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
