### PR TITLE
Allow renaming a variable twice as it might happen in some cases.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4967)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4967)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/cancel_ops.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4967#-NpVG9O9D3S-9OQvAUes:-NpVG9O9D3S-9OQvAUet:b-1ao6) ([raw file](https://github.com/starkware-libs/cairo/blob/6f20e519e378f2a1c406c90a29bfab11f5d111d6/crates/cairo-lang-lowering/src/optimizations/cancel_ops.rs#L41)):*
> ```XML
>     // Remove no-longer needed statements.
>     stmts_to_remove.sort_by_key(|(block_id, stmt_id)| (block_id.0, *stmt_id));
>     for (block_id, stmt_id) in stmts_to_remove.into_iter().rev().dedup() {
> ```

how do you know the problematic ones would be consecutive?
doc how you know it, and why these might exist.



_Code quote:_
```XML
    for (block_id, stmt_id) in stmts_to_remove.into_iter().rev().dedup() {
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/cancel_ops.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4967#-NpVG9O9D3S-9OQvAUes:-NpVGNcxB9ONiO38BdSW:b-xpadct) ([raw file](https://github.com/starkware-libs/cairo/blob/6f20e519e378f2a1c406c90a29bfab11f5d111d6/crates/cairo-lang-lowering/src/optimizations/cancel_ops.rs#L41)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

how do you know the problematic ones would be consecutive?
doc how you know it, and why these might exist.
</blockquote></details>

because of the sorting.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4967)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/cancel_ops.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4967#-NpVG9O9D3S-9OQvAUes:-NpVGlHp9XgUAMcjfwl7:b6o8hpz) ([raw file](https://github.com/starkware-libs/cairo/blob/6f20e519e378f2a1c406c90a29bfab11f5d111d6/crates/cairo-lang-lowering/src/optimizations/cancel_ops.rs#L41)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

because of the sorting.
</blockquote></details>

oh - right - but still doc the need for dedup.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4967)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/cancel_ops.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4967#-NpVG9O9D3S-9OQvAUes:-NpVHXEEDLdIH33lkMID:bohqa17) ([raw file](https://github.com/starkware-libs/cairo/blob/6f20e519e378f2a1c406c90a29bfab11f5d111d6/crates/cairo-lang-lowering/src/optimizations/cancel_ops.rs#L41)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

oh - right - but still doc the need for dedup.
</blockquote></details>

Done.
I couldn't put the .dedup() before the .rev().

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4967#-:-NpVHrR67jiPRY72w3gm:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
