### PR TITLE
High level support and testsing for span-to-fixed-sized array.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #5590
- #5589
- #5588
- #5584
- #5583 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5583)

### CODE REVIEW

**Review by TomerStarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5583#-:-NyEod8kEhIyaQ7GX2ok:bnfp4nl)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/array.cairo` line 274 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5583#-NyEuPV_16PB7uo-mSma:-NyEuPV_16PB7uo-mSmb:b-75ywm7) ([raw file](https://github.com/starkware-libs/cairo/blob/cc736d175f7180ce7936f034c4aded5be7ed9acd/corelib/src/array.cairo#L274)):*
> ```Cairo
> }
> 
> impl SpanTryIntoEmptyFixedSizedArray<T, +Drop<T>> of TryInto<Span<T>, Box<@[T; 0]>> {
> ```

why is this needed?



_Code quote:_
```Cairo
SpanTryIntoEmptyFixedSizedArray<T, +Drop<T>> of TryInto<Span<T>, Box<@[T; 0]>>
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5583)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/array.cairo` line 274 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5583#-NyEuPV_16PB7uo-mSma:-NyEuWxyA6rgWLIQjWfL:b-omur46) ([raw file](https://github.com/starkware-libs/cairo/blob/cc736d175f7180ce7936f034c4aded5be7ed9acd/corelib/src/array.cairo#L274)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why is this needed?
</blockquote></details>

this just makes try-into for empty sized arrays work.

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/array.cairo` line 262 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5583#-NyEypom1bwxe2r8v14v:-NyEypom1bwxe2r8v14w:boor3ow) ([raw file](https://github.com/starkware-libs/cairo/blob/cc736d175f7180ce7936f034c4aded5be7ed9acd/corelib/src/array.cairo#L262)):*
> ```Cairo
> /// The additional `+Copy<@T>` arg is to prevent later stages from propagating the `S` type Sierra
> /// level, where it is deduced by the `T` type.
> extern fn tuple_from_span<T, +Copy<@T>, S>(span: @Array<S>) -> Option<Box<@T>> nopanic;
> ```

why can't we use the following signature?



_Suggestion:_
```Cairo
extern fn tuple_from_span<T, SIZE: u32>(span: @Array<T>) -> Option<Box<[T, SIZE]>> nopanic;
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5583)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/array.cairo` line 262 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5583#-NyEypom1bwxe2r8v14v:-NyF6yas5R7g8F5iHs8O:b-9bdglv) ([raw file](https://github.com/starkware-libs/cairo/blob/cc736d175f7180ce7936f034c4aded5be7ed9acd/corelib/src/array.cairo#L262)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why can't we use the following signature?
</blockquote></details>

no - look at the above comment.
will change it to be inner type based soon.

but currently like `span_from_tuple`

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/array.cairo` line 262 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5583#-NyEypom1bwxe2r8v14v:-NyFVRZb92R1qaJHW_L6:bz3xqhq) ([raw file](https://github.com/starkware-libs/cairo/blob/cc736d175f7180ce7936f034c4aded5be7ed9acd/corelib/src/array.cairo#L262)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no - look at the above comment.
will change it to be inner type based soon.

but currently like `span_from_tuple`
</blockquote></details>

I read the comment and didn't understand it.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5583)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/array.cairo` line 262 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5583#-NyEypom1bwxe2r8v14v:-NyFWIVmCAGGbbUfKMu6:b-5dujkg) ([raw file](https://github.com/starkware-libs/cairo/blob/cc736d175f7180ce7936f034c4aded5be7ed9acd/corelib/src/array.cairo#L262)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I read the comment and didn't understand it.
</blockquote></details>

the only type in the generics of the libfunc is `T` - the following args *must not be* passed to the libfunc.
since i want it to be exactly the same as `span_from_tuple` i don't want to limit it to only returning the `fixed_size_array` in the libfunc - so we are only dependent on the tuple like struct `T`, and the size is not part of the signature.

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/array.cairo` line 262 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5583#-NyEypom1bwxe2r8v14v:-NyF_APx1stbfhbc8kPN:b-bqix5e) ([raw file](https://github.com/starkware-libs/cairo/blob/cc736d175f7180ce7936f034c4aded5be7ed9acd/corelib/src/array.cairo#L262)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the only type in the generics of the libfunc is `T` - the following args *must not be* passed to the libfunc.
since i want it to be exactly the same as `span_from_tuple` i don't want to limit it to only returning the `fixed_size_array` in the libfunc - so we are only dependent on the tuple like struct `T`, and the size is not part of the signature.
</blockquote></details>

"the following args _must not be_ passed to the libfunc."
what does that mean?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5583)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/array.cairo` line 262 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5583#-NyEypom1bwxe2r8v14v:-NyF_aw2448N2DY6MDf4:b-eah6q9) ([raw file](https://github.com/starkware-libs/cairo/blob/cc736d175f7180ce7936f034c4aded5be7ed9acd/corelib/src/array.cairo#L262)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

"the following args _must not be_ passed to the libfunc."
what does that mean?
</blockquote></details>

it isn't part of the expected generic args by sierra.

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/array.cairo` line 262 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5583#-NyEypom1bwxe2r8v14v:-NyF_mdx6KrExy2HSoCP:bd70kt5) ([raw file](https://github.com/starkware-libs/cairo/blob/cc736d175f7180ce7936f034c4aded5be7ed9acd/corelib/src/array.cairo#L262)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it isn't part of the expected generic args by sierra.
</blockquote></details>

how does +Copy<@T> prevent propagating the `S` type to sierra

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5583)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @t)

___
*[`corelib/src/array.cairo` line 262 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5583#-NyEypom1bwxe2r8v14v:-NyFanLIEQL-gGF6gDmT:b-4gq2v1) ([raw file](https://github.com/starkware-libs/cairo/blob/cc736d175f7180ce7936f034c4aded5be7ed9acd/corelib/src/array.cairo#L262)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

how does +Copy<@T> prevent propagating the `S` type to sierra
</blockquote></details>

impl args and everything following are not passed to sierra.

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/array.cairo` line 262 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5583#-NyEypom1bwxe2r8v14v:-NyFq4uPDR2_tHEWwc3-:bxl6ng1) ([raw file](https://github.com/starkware-libs/cairo/blob/cc736d175f7180ce7936f034c4aded5be7ed9acd/corelib/src/array.cairo#L262)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

impl args and everything following are not passed to sierra.
</blockquote></details>

Why did you decide on using +Copy
instead of +IgnoreFollowingArgs?

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/array.cairo` line 262 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5583#-NyEypom1bwxe2r8v14v:-NyFqNdY2Nw3JqYLfkzb:b-mcufd7) ([raw file](https://github.com/starkware-libs/cairo/blob/cc736d175f7180ce7936f034c4aded5be7ed9acd/corelib/src/array.cairo#L262)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why did you decide on using +Copy
instead of +IgnoreFollowingArgs?
</blockquote></details>

maybe use 
S_
?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5583)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @t)

___
*[`corelib/src/array.cairo` line 262 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5583#-NyEypom1bwxe2r8v14v:-NyFtjnq-DoOwSP4CM4f:bo4ufy4) ([raw file](https://github.com/starkware-libs/cairo/blob/cc736d175f7180ce7936f034c4aded5be7ed9acd/corelib/src/array.cairo#L262)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

maybe use 
S_
?
</blockquote></details>

it is already used - and will soon be removed - rather not add boilerplate for this PR.

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/test/array_test.cairo` line 149 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5583#-NyK3bOmBDef4HdQAmbQ:-NyK3bOmBDef4HdQAmbR:b-ixpbuy) ([raw file](https://github.com/starkware-libs/cairo/blob/550ddf4b7933b622baf0af3896cf463317cbd61a/corelib/src/test/array_test.cairo#L149)):*
> ```Cairo
> }
> 
> fn debox<T, const SIZE: usize>(value: Option<@Box<[T; SIZE]>>) -> Option<@[T; SIZE]> {
> ```

what is debox?
can you document it?



_Code quote:_
```Cairo
debox
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5583)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @t)

___
*[`corelib/src/test/array_test.cairo` line 149 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5583#-NyK3bOmBDef4HdQAmbQ:-NyKG3xP6_KaHZZfFtGN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/550ddf4b7933b622baf0af3896cf463317cbd61a/corelib/src/test/array_test.cairo#L149)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what is debox?
can you document it?
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/test/array_test.cairo` line 149 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5583#-NyK3bOmBDef4HdQAmbQ:-NyOcoaw8pe3Z3M4Bffy:b-euab64) ([raw file](https://github.com/starkware-libs/cairo/blob/550ddf4b7933b622baf0af3896cf463317cbd61a/corelib/src/test/array_test.cairo#L149)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Why do you need to wrap it in a snapshot?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5583)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @t)

___
*[`corelib/src/test/array_test.cairo` line 149 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5583#-NyK3bOmBDef4HdQAmbQ:-NyOknWD0OPbo30e_ir6:b-7ah5vp) ([raw file](https://github.com/starkware-libs/cairo/blob/550ddf4b7933b622baf0af3896cf463317cbd61a/corelib/src/test/array_test.cairo#L149)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why do you need to wrap it in a snapshot?
</blockquote></details>

The input already had a snapshot, leaving the snapshot here remove the need to require the data to have Copy

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5583#-:-NyOmJL203pXSQEzBOmj:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
