### PR TITLE
Updated nightly to newer version.

### PR DESCRIPTION
**Pull request by orizi**
Refactored runner to remove lib usage causing new errors.

---

**Stack**:
- #5463 ⬅
- #5466

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5463)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1806 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5463#-NwEfLRF59087Ae5D0eL:-NwEfLRF59087Ae5D0eM:btczxtq) ([raw file](https://github.com/starkware-libs/cairo/blob/d959a6e8ee1cb1c93e2c2770d9f859ab5bf626ca/crates/cairo-lang-runner/src/casm_run/mod.rs#L1806)):*
> ```XML
>             // Keep sampling a random field element `X` until `X^3 + X + beta` is a quadratic
>             // residue.
>             let mut rng = rand::thread_rng();
> ```

Is it ok to change hints?



_Code quote:_
```XML
 let mut rng = rand::thread_rng()
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1806 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5463#-NwEfLRF59087Ae5D0eL:-NwEhDQv8oN3meQDcQOF:b-jp4rft) ([raw file](https://github.com/starkware-libs/cairo/blob/d959a6e8ee1cb1c93e2c2770d9f859ab5bf626ca/crates/cairo-lang-runner/src/casm_run/mod.rs#L1806)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why not if it makes no changes to the flow of the run?
</blockquote></details>

it gives a different points

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5463)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1806 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5463#-NwEfLRF59087Ae5D0eL:-NwEhIbiBU7vRgk0StkG:b6hjz7q) ([raw file](https://github.com/starkware-libs/cairo/blob/d959a6e8ee1cb1c93e2c2770d9f859ab5bf626ca/crates/cairo-lang-runner/src/casm_run/mod.rs#L1806)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it gives a different points
</blockquote></details>

it gives a different ec-state - which is unextractable - this is just the random around the point.
the actual run would have the exact same flow.
(otherwise it would also have meant that we had to have the exact same random seed in every computer running this)

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5463#-:-NwEj9S14sKcmUGEKG0B:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5463)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
