### PR TITLE
dev: make widemul a method of LHS type

### PR DESCRIPTION
**Pull request by enitrat**
Makes `widemul` a method callable on the type of self.

enables:
`let ab = a.wide_mul(b);`
previously only `let ab = WideMul::wide_mul(a,b);` was possible

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6165)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6165#-:-O4-jQIv1-Lr4cGMI0K9:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @enitrat)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6165)* status: all files reviewed, 1 unresolved discussion (waiting on @enitrat)

___
*[`corelib/src/num/traits/ops/widemul.cairo` line 6 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6165#-O4-jhRP8JTLP6lWdQ34:-O4-jhRP8JTLP6lWdQ35:b-ig5x8x) ([raw file](https://github.com/starkware-libs/cairo/blob/c131592a69faabbd6ec364ccbcd2704e0d197d82/corelib/src/num/traits/ops/widemul.cairo#L6)):*
> ```Cairo
>     type Target;
>     /// Multiply two values together, producing a wider type.
>     fn wide_mul(self: Lhs, v: Rhs) -> Self::Target;
> ```

(i know `{Overflowing,Checked}*` are not that way, but `Saturating*` is, and it makes more sense)



_Suggestion:_
```Cairo
    fn wide_mul(self: Lhs, other: Rhs) -> Self::Target;
```

**Review by enitrat — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6165)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/num/traits/ops/widemul.cairo` line 6 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6165#-O4-jhRP8JTLP6lWdQ34:-O4-xov44UY8ISYOvHEe:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c131592a69faabbd6ec364ccbcd2704e0d197d82/corelib/src/num/traits/ops/widemul.cairo#L6)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

(i know `{Overflowing,Checked}*` are not that way, but `Saturating*` is, and it makes more sense)
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6165#-:-O4-ydaCDgpYtolgbakT:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @enitrat)

**Pull request merged**
