### PR TITLE
Use full path for `call_contract_syscall`.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4534)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 9 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4534)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @ilyalesokhin-starkware)

___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/contracts.adoc` line 208 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4534#-NlNK8SD4qXLp0XZQQXc:-NlNK8SE7l6FptS-q74D:b-yokh81) ([raw file](https://github.com/starkware-libs/cairo/blob/02182254436c1c5390e5b4aafcbf44b0b711c59c/docs/reference/src/components/cairo/modules/language_constructs/pages/contracts.adoc#L208)):*
> ```AsciiDoc
> === Using system calls
> 
> Another way to call another contract is to use the `starknet::syscalls::call_contract_syscall` system call.
> ```

fix lines

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4534)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/contracts.adoc` line 208 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4534#-NlNK8SD4qXLp0XZQQXc:-NlNQ1JH6bf4xLNRCN72:bb7hmr8) ([raw file](https://github.com/starkware-libs/cairo/blob/02182254436c1c5390e5b4aafcbf44b0b711c59c/docs/reference/src/components/cairo/modules/language_constructs/pages/contracts.adoc#L208)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix lines
</blockquote></details>

how?

**Comment by ilyalesokhin-starkware** [comment]
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/contracts.adoc` line 208 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4534#-NlNK8SD4qXLp0XZQQXc:-NlNQYCl4e8ezc-mkxlv:bou5dgy) ([raw file](https://github.com/starkware-libs/cairo/blob/02182254436c1c5390e5b4aafcbf44b0b711c59c/docs/reference/src/components/cairo/modules/language_constructs/pages/contracts.adoc#L208)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

how?
</blockquote></details>

is this ok?

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4534#-:-NlNYvwqEO0XlaqeIa6j:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
