### PR TITLE
LS: refresh project on `cairo_project.toml` change, register text document sync on server side

### PR DESCRIPTION
**Pull request by piotmag769**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6316)

### CODE REVIEW

**Review by mkaput — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6316)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @orizi)

**Review by Draggu — CHANGES_REQUESTED** [review]
Please move this logic into `client_capabilities.rs`.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6316#-:-O5XZmi_4vcOZPHslgsT:b-o08isn)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @Arcticae and @orizi)

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6316)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 850 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6316#-O5Xc-Wj5FMLx37H0Xy3:-O5Xc-Wj5FMLx37H0Xy4:b-gz8agi) ([raw file](https://github.com/starkware-libs/cairo/blob/652762df36a7c2d83445eff2abbc1fb5d6926f67/crates/cairo-lang-language-server/src/lib.rs#L850)):*
> ```XML
>                 serde_json::to_value(TextDocumentChangeRegistrationOptions {
>                     document_selector,
>                     sync_kind: 2, // TextDocumentSyncKind::FULL
> ```

but FULL is 1, while INCREMENTAL is 2 according to `lsp_types`. isn't something off here?
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 863 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6316#-O5XbMcj1ck5bJo5cM_R:-O5XbMcj1ck5bJo5cM_S:b-57roll) ([raw file](https://github.com/starkware-libs/cairo/blob/652762df36a7c2d83445eff2abbc1fb5d6926f67/crates/cairo-lang-language-server/src/lib.rs#L863)):*
> ```XML
>             for (method, options) in zip(methods, register_options) {
>                 register_dynamically(method, Some(options), &self.client).await;
>             }
> ```

I sense overengineering here. Why not just something like this:



_Suggestion:_
```XML
            self.register_dynamic_capability(
                "textDocument/didOpen"
                &text_document_registration_options,
            ).await;
            self.register_dynamic_capability(
                "textDocument/didChange",
                TextDocumentChangeRegistrationOptions {
                    document_selector,
                    sync_kind: 2, // TextDocumentSyncKind::FULL
                },
            ).await;
            self.register_dynamic_capability(
                "textDocument/didSave",
                TextDocumentSaveRegistrationOptions {
                    include_text: Some(false),
                    text_document_registration_options: text_document_registration_options.clone(),
                },
            ).await;
            self.register_dynamic_capability(
                "textDocument/didClose",
                &text_document_registration_options,
            ).await;
```
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 1027 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6316#-O5Xc_ZcC8eeQmKkaiAu:-O5Xc_ZcC8eeQmKkaiAv:bb7qzhp) ([raw file](https://github.com/starkware-libs/cairo/blob/652762df36a7c2d83445eff2abbc1fb5d6926f67/crates/cairo-lang-language-server/src/lib.rs#L1027)):*
> ```XML
>     let result = client.register_capability(vec![registration]).await;
>     if let Err(err) = result {
>         warn!("Failed to register {method} event: {err:#?}");
> ```

wdyt



_Suggestion:_
```XML
error!("failed to register dynamic capabilities for {method}: {err:#?}");
```
___
*[`crates/cairo-lang-language-server/src/lsp/client_capabilities.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6316#-O5Xcyk_4ZhvU6kytIlC:-O5Xcyk_4ZhvU6kytIlD:bljob9k) ([raw file](https://github.com/starkware-libs/cairo/blob/652762df36a7c2d83445eff2abbc1fb5d6926f67/crates/cairo-lang-language-server/src/lsp/client_capabilities.rs#L18)):*
> ```XML
>     fn workspace_configuration_support(&self) -> bool;
> 
>     /// The client supports dynamic registration for the `workspace/didChangeWatchedFiles`
> ```

fix doc

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6316)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 850 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6316#-O5Xc-Wj5FMLx37H0Xy3:-O5XwbtE1xBclQDWCDP9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/652762df36a7c2d83445eff2abbc1fb5d6926f67/crates/cairo-lang-language-server/src/lib.rs#L850)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

but FULL is 1, while INCREMENTAL is 2 according to `lsp_types`. isn't something off here?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 863 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6316#-O5XbMcj1ck5bJo5cM_R:-O5Xwt1EESmW8mzv6A_l:b-lyk353) ([raw file](https://github.com/starkware-libs/cairo/blob/652762df36a7c2d83445eff2abbc1fb5d6926f67/crates/cairo-lang-language-server/src/lib.rs#L863)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I sense overengineering here. Why not just something like this:
</blockquote></details>

Done, did this before, maybe it is indeed better
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 1027 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6316#-O5Xc_ZcC8eeQmKkaiAu:-O5XxTLsBnKASYt8rPoy:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/652762df36a7c2d83445eff2abbc1fb5d6926f67/crates/cairo-lang-language-server/src/lib.rs#L1027)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

wdyt
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lsp/client_capabilities.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6316#-O5Xcyk_4ZhvU6kytIlC:-O5XxIVB7MmyN8IDemlj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/652762df36a7c2d83445eff2abbc1fb5d6926f67/crates/cairo-lang-language-server/src/lsp/client_capabilities.rs#L18)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

fix doc
</blockquote></details>

Done.

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6316)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @mkaput, and @orizi)

**Review by piotmag769 — COMMENTED** [review]
Will do in a separate PR after we merge relevant stuff

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6316#-:-O5YA0y-C9StTSgJMWOC:b-c5wlfs)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @mkaput, and @orizi)

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6316)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 371 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6316#-O5YIb7XBqKgarVY2Tdw:-O5YIb7YCDEyYmLQ3hJF:b-9x5v7i) ([raw file](https://github.com/starkware-libs/cairo/blob/381d6aef27bb64d9384a66a939f574c0803dc2a5/crates/cairo-lang-language-server/src/lib.rs#L371)):*
> ```XML
>             register_options: Some(serde_json::to_value(register_options).unwrap()),
>         };
>         let result = self.client.register_capability(vec![registration]).await;
> ```

oh I see now that this support batch registration. could we make use of that?

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6316)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 371 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6316#-O5YIb7XBqKgarVY2Tdw:-O5YXVVAAdhcs5fV1r7E:b6akp7k) ([raw file](https://github.com/starkware-libs/cairo/blob/381d6aef27bb64d9384a66a939f574c0803dc2a5/crates/cairo-lang-language-server/src/lib.rs#L371)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

oh I see now that this support batch registration. could we make use of that?
</blockquote></details>

Sure, completely missed that

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6316)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

**Review by mkaput — CHANGES_REQUESTED** [review]
BTW I think we should do a separate `server_capabilities.rs`

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6316#-:-O5lhEO50m3-hq9JGRKo:b-p6ff3o)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 419 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6316#-O5lhoW22M638TZzafke:-O5lhoW22M638TZzafkf:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/1863487a504bac2a70926d3c0258b76ffc318970/crates/cairo-lang-language-server/src/lib.rs#L419)):*
> ```XML
>                     serde_json::to_value(TextDocumentChangeRegistrationOptions {
>                         document_selector,
>                         sync_kind: 1, // TextDocumentSyncKind::FULL
> ```





_Suggestion:_
```XML
sync_kind: TextDocumentSyncKind::FULL as i32,
```

**Review by piotmag769 — COMMENTED** [review]
Done in slightly different way

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6316#-:-O5mbgvX3rfGC3rE-zJL:b-c1yc9y)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 419 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6316#-O5lhoW22M638TZzafke:-O5mb_4Q0kf9Wc7VdDYG:b-eiekfb) ([raw file](https://github.com/starkware-libs/cairo/blob/1863487a504bac2a70926d3c0258b76ffc318970/crates/cairo-lang-language-server/src/lib.rs#L419)):*
> ```XML
>                     serde_json::to_value(TextDocumentChangeRegistrationOptions {
>                         document_selector,
>                         sync_kind: 1, // TextDocumentSyncKind::FULL
> ```

Cannot be done, it is an impl const, not an enum

**Review by Draggu — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r4, 4 of 6 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6316#-:-O5mhX2iBtcH-8egxrnb:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @mkaput, and @orizi)

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 4 of 6 files at r6, 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6316#-:-O5n2TaF1fHV_ZuzRpUw:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @orizi)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 3 of 6 files at r6, 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6316)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae)

**Pull request merged**
