### PR TITLE
Added panicable to all uint128 functions.

### PR DESCRIPTION
**Pull request by orizi**
Currently makes code much less efficient - as it adds function calls and
locals.

commit-id:153e6739

---

**Stack**:
- #1170
- #1165
- #1164
- #1161
- #1140
- #1120 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1120)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`corelib/integer.cairo` line 5 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1120#-NI2D-9iEGzb1rcBHOgM:-NI2D-9iEGzb1rcBHOgN:b-wiep5o) ([raw file](https://github.com/starkware-libs/cairo/blob/99c0fc8b9ec3fb8b93cc1c95fe377b6efc13bab5/corelib/integer.cairo#L5)):*
> ```Cairo
> impl Uint128Drop of Drop::<uint128>;
> 
> // TODO(orizi): Change all error codes into
> ```

I'm on edge! Can't handle the suspense..
Do tell, change into what?
___
*[`crates/plugins/src/panicable.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1120#-NI2DBB90DjUbpageC7Z:-NI2DBB90DjUbpageC7_:br9z0xn) ([raw file](https://github.com/starkware-libs/cairo/blob/99c0fc8b9ec3fb8b93cc1c95fe377b6efc13bab5/crates/plugins/src/panicable.rs#L98)):*
> ```XML
>                                 array_append::<felt>(data, {err_value});
>                                 panic(data);
>                                 {function_name}_panicable({args})
> ```

Add a comment on why we are doing this, and maybe a TODO to remove.
___
*[`tests/test_data/fib_uint128.casm` line 6 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1120#-NI2DXfBE4XOk_dMVma0:-NI2DXfBE4XOk_dMVma1:b-3wrzv0) ([raw file](https://github.com/starkware-libs/cairo/blob/99c0fc8b9ec3fb8b93cc1c95fe377b6efc13bab5/tests/test_data/fib_uint128.casm#L6)):*
> ```
> [ap + 0] = [fp + -5], ap++;
> jmp rel 78;
> [ap + 0] = [fp + -6], ap++;
> ```

This is really sad... Can we save this?

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1120)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`tests/test_data/fib_uint128.casm` line 6 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1120#-NI2DXfBE4XOk_dMVma0:-NI2DbqaCgmCcxKQoUq-:b-lyb2n8) ([raw file](https://github.com/starkware-libs/cairo/blob/99c0fc8b9ec3fb8b93cc1c95fe377b6efc13bab5/tests/test_data/fib_uint128.casm#L6)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This is really sad... Can we save this?
</blockquote></details>

Requires inliniong, yeah, I know.. Myabe let @liorgold2 TAL?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1120)* status: 4 of 11 files reviewed, 3 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

___
*[`corelib/integer.cairo` line 5 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1120#-NI2D-9iEGzb1rcBHOgM:-NI3RR4H3ns3SlP719FE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/99c0fc8b9ec3fb8b93cc1c95fe377b6efc13bab5/corelib/integer.cairo#L5)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I'm on edge! Can't handle the suspense..
Do tell, change into what?
</blockquote></details>

Done.
___
*[`crates/plugins/src/panicable.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1120#-NI2DBB90DjUbpageC7Z:-NI3RrrsB8BpezukylWs:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/99c0fc8b9ec3fb8b93cc1c95fe377b6efc13bab5/crates/plugins/src/panicable.rs#L98)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Add a comment on why we are doing this, and maybe a TODO to remove.
</blockquote></details>

Done.
___
*[`tests/test_data/fib_uint128.casm` line 6 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1120#-NI2DXfBE4XOk_dMVma0:-NI3T0K18QEiXnwnSlPT:b-8kidoi) ([raw file](https://github.com/starkware-libs/cairo/blob/99c0fc8b9ec3fb8b93cc1c95fe377b6efc13bab5/tests/test_data/fib_uint128.casm#L6)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Requires inliniong, yeah, I know.. Myabe let @liorgold2 TAL?
</blockquote></details>

adding another checked impl.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 9 files at r1, 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1120#-:-NI6ZOSgCkcn_2HOXlyj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
