### PR TITLE
Use semantic var location instead of SealedBlockBuilder location.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3697)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3697)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 598 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3697#-N_ba6Wo5ZgZoCWvPneI:-N_ba6Wo5ZgZoCWvPneJ:besgkca) ([raw file](https://github.com/starkware-libs/cairo/blob/e43714c2c8953529e15f140ef7fb848b792aa7aa/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L598)):*
> ```
> error: Variable was previously moved. Trait has no implementation in context: core::traits::Copy::<core::array::Array::<core::felt252>>
>  --> lib.cairo:8:8
> fn foo(ref self: MyStruct) {
> ```

what was the previous value?



_Code quote:_
```
fn foo(ref self: MyStruct) {
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 598 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3697#-N_ba6Wo5ZgZoCWvPneI:-N_bbd0s6V1fxpuNardw:bqh1jm1) ([raw file](https://github.com/starkware-libs/cairo/blob/e43714c2c8953529e15f140ef7fb848b792aa7aa/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L598)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

what was the previous value?
</blockquote></details>

error: Variable was previously moved. Trait has no implementation in context: core::traits::Copy::<core::array::Array::<core::felt252\>>



_Code snippet:_
```
error: Variable was previously moved. Trait has no implementation in context: core::traits::Copy::<core::array::Array::<core::felt252>>
 --> lib.cairo:9:5
    if self.b == 0 {
    ^**************^
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 598 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3697#-N_ba6Wo5ZgZoCWvPneI:-N_bbkym23YNxdduhjxP:b-sgfuca) ([raw file](https://github.com/starkware-libs/cairo/blob/e43714c2c8953529e15f140ef7fb848b792aa7aa/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L598)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

error: Variable was previously moved. Trait has no implementation in context: core::traits::Copy::<core::array::Array::<core::felt252\>>
</blockquote></details>

or more generally, the location of the block the caused the reconstructure.

btw, the usage location is also bad (it is not trimmed to 1 line :(



_Code snippet:_
```
Statements:
  (v15: test::MyStruct) <- struct_construct(v1{`if self.b == 0 {
       self.a = Default::default();
    }`}, v3{`if self.b == 0 {
       self.a = Default::default();
    }`})
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3697#-:-N_bdSbGBWR_BJChIfuV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
wrong approch.

**Pull request merged**
