### PR TITLE
Fix gas cost of get_gas_all

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1898)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1898)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/builtin_cost.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1898#-NMcVspZEyAldQcHrrQy:-NMcVspZEyAldQcHrrQz:b-3bmhjr) ([raw file](https://github.com/starkware-libs/cairo/blob/3e56069dbed18d1a62a011a29f3c7311dae31509/crates/cairo-lang-sierra/src/extensions/modules/builtin_cost.rs#L30)):*
> ```XML
> impl CostTokenType {
>     pub fn iter() -> std::slice::Iter<'static, Self> {
>         [CostTokenType::Step, CostTokenType::Pedersen, CostTokenType::Bitwise, CostTokenType::EcOp]
> ```

is there a way to make this be the chain of the 2 others?



_Code quote:_
```XML
        [CostTokenType::Step, CostTokenType::Pedersen, CostTokenType::Bitwise, CostTokenType::EcOp]
            .iter()
```
___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 242 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1898#-NMcXj2e0o4bwo7i5eDk:-NMcXj2e0o4bwo7i5eDl:b-wimn3h) ([raw file](https://github.com/starkware-libs/cairo/blob/3e56069dbed18d1a62a011a29f3c7311dae31509/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L242)):*
> ```XML
>                 vec![
>                     ops.sub(ops.const_cost(cost_branch0 + 3), cost.unwrap()),
>                     ops.const_cost(cost_branch1 + 5),
> ```

are the +3/+5 not related to the basic ap change?



_Code quote:_
```XML
                    ops.sub(ops.const_cost(cost_branch0 + 3), cost.unwrap()),
                    ops.const_cost(cost_branch1 + 5),
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1898)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/builtin_cost.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1898#-NMcVspZEyAldQcHrrQy:-NMczBod2GKkLgTZKQom:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3e56069dbed18d1a62a011a29f3c7311dae31509/crates/cairo-lang-sierra/src/extensions/modules/builtin_cost.rs#L30)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is there a way to make this be the chain of the 2 others?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 242 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1898#-NMcXj2e0o4bwo7i5eDk:-NMczE4N-c1OPehnVaUF:b5x1lnm) ([raw file](https://github.com/starkware-libs/cairo/blob/3e56069dbed18d1a62a011a29f3c7311dae31509/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L242)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

are the +3/+5 not related to the basic ap change?
</blockquote></details>

You tell me, I dunno. What should I write here?

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1898)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 242 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1898#-NMcXj2e0o4bwo7i5eDk:-NMczvPsAuPsxqFIc0Fx:b-waa32o) ([raw file](https://github.com/starkware-libs/cairo/blob/3e56069dbed18d1a62a011a29f3c7311dae31509/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L242)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

You tell me, I dunno. What should I write here?
</blockquote></details>

i guess i'm gonna validate it anyway, so fine for now.

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1898)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 242 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1898#-NMcXj2e0o4bwo7i5eDk:-NMd-57O0KvAMiCrGE1M:bstuzrl) ([raw file](https://github.com/starkware-libs/cairo/blob/3e56069dbed18d1a62a011a29f3c7311dae31509/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L242)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i guess i'm gonna validate it anyway, so fine for now.
</blockquote></details>

but probably +1 and  +2.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1898)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
