### PR TITLE
Create a parser API for TokenStream.

### PR DESCRIPTION
**Pull request by wawel37**

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6594)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @maciektr, @mkaput, and @wawel37)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6594#-OAwkMy3-VwlOdX8lvvb:-OAwkMy3-VwlOdX8lvvc:b-hf76io) (no related file):*
@gilbens-starkware 

___

**Review by gilbens-starkware — COMMENTED** [review]
What's the motivation for this change?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6594#-:-OAwkQ6dA5WvLz8z_8tn:b-2ily24)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @maciektr, @mkaput, and @wawel37)

**Review by wawel37 — COMMENTED** [review]
It's directly connected to changing the way Scarb communicates with procedural macro in order to create more accurate code mappings.

Related issues:
https://github.com/software-mansion/scarb/issues/1710
https://github.com/software-mansion/scarb/issues/1132

Scarb host and macro communicate using TokenStream. It stores all of the code as a stream of tokens. Each of them got code as a string and also a span (start and end TextOffset). We need those to map tokens from macro's result to the origin code. This way, any diagnostics that occured during execution of the macro will point either to the origin code or the code that was generated by the macro. As for now, we always point to the macro attribute or call if it's a function-like macro.

This change just creates an additional API inside the parser, which lets us parse a TokenStream (string version of it), and keep all of the offsets that the tokens included. Previously all the offsets of SyntaxNodes were based upon a TextOffset::default, used in a root_node creation [here](https://github.com/starkware-libs/cairo/blob/d401aeb9dbfc7364fd172ce251bc0dd62b303340/crates/cairo-lang-syntax/src/node/mod.rs#L50). 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6594#-:-OAwqSEU3KzvD70KR1cm:bwf5vix)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @maciektr and @mkaput)

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 7 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6594)* status: all files reviewed, 5 unresolved discussions (waiting on @maciektr and @wawel37)

___
*[`crates/cairo-lang-parser/Cargo.toml` line 22 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6594#-OB-QvYT72Cd_g-q41Ds:-OB-QvYT72Cd_g-q41Dt:b-b6ppda) ([raw file](https://github.com/starkware-libs/cairo/blob/deb833cfb4eec26a88545eaac5fa76fc32819220/crates/cairo-lang-parser/Cargo.toml#L22)):*
> ```TOML
> smol_str.workspace = true
> unescaper.workspace = true
> indoc.workspace = true
> ```

this is only used in deps, so it should go to dev dependencies
___
*[`crates/cairo-lang-parser/src/test_utils.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6594#-OB-RS1893XsWAdkN8M9:-OB-RS1893XsWAdkN8MA:bfgb78q) ([raw file](https://github.com/starkware-libs/cairo/blob/deb833cfb4eec26a88545eaac5fa76fc32819220/crates/cairo-lang-parser/src/test_utils.rs#L49)):*
> ```XML
> 
> #[derive(Debug, Clone)]
> pub struct TokenStream {
> ```

wdyt? I'd probably apply this convention to all the other types



_Suggestion:_
```XML
pub struct MockTokenStream {
```
___
*[`crates/cairo-lang-parser/src/test_utils.rs` line 54 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6594#-OB-Rebd7CsTolUaeufq:-OB-Rebd7CsTolUaeufr:byp6237) ([raw file](https://github.com/starkware-libs/cairo/blob/deb833cfb4eec26a88545eaac5fa76fc32819220/crates/cairo-lang-parser/src/test_utils.rs#L54)):*
> ```XML
> 
> #[derive(Debug, Default, Clone)]
> pub struct TextSpan {
> ```

can't we reuse `cairo_lang_filesystem::span::TextSpan` here?
___
*[`crates/cairo-lang-parser/src/types.rs` line 5 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6594#-OB-RoxAB5rsIIbNuef-:-OB-RoxAB5rsIIbNuef0:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/deb833cfb4eec26a88545eaac5fa76fc32819220/crates/cairo-lang-parser/src/types.rs#L5)):*
> ```XML
> use cairo_lang_filesystem::span::TextOffset;
> 
> pub trait TokenStream: Display {
> ```

doc

**Review by wawel37 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6594)* status: 5 of 9 files reviewed, 5 unresolved discussions (waiting on @maciektr and @mkaput)

___
*[`crates/cairo-lang-parser/Cargo.toml` line 22 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6594#-OB-QvYT72Cd_g-q41Ds:-OB04tkq0hMvNulRRLrM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/deb833cfb4eec26a88545eaac5fa76fc32819220/crates/cairo-lang-parser/Cargo.toml#L22)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

this is only used in deps, so it should go to dev dependencies
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/test_utils.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6594#-OB-RS1893XsWAdkN8M9:-OB08AhX3_pC7brh2zdS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/deb833cfb4eec26a88545eaac5fa76fc32819220/crates/cairo-lang-parser/src/test_utils.rs#L49)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

wdyt? I'd probably apply this convention to all the other types
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/test_utils.rs` line 54 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6594#-OB-Rebd7CsTolUaeufq:-OB08AxtCCtDE4lcZhiM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/deb833cfb4eec26a88545eaac5fa76fc32819220/crates/cairo-lang-parser/src/test_utils.rs#L54)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

can't we reuse `cairo_lang_filesystem::span::TextSpan` here?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/types.rs` line 5 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6594#-OB-RoxAB5rsIIbNuef-:-OB08EbK8E2revz3MRXD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/deb833cfb4eec26a88545eaac5fa76fc32819220/crates/cairo-lang-parser/src/types.rs#L5)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6594)* status: all files reviewed, 4 unresolved discussions (waiting on @maciektr and @wawel37)

___
*[`crates/cairo-lang-parser/src/test_utils.rs` line 12 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6594#-OB0HWaiD0foqnt2MyNd:-OB0HWaiD0foqnt2MyNe:bivcmq) ([raw file](https://github.com/starkware-libs/cairo/blob/9342806d5681ec65e4cbb986a87c63e723f354da/crates/cairo-lang-parser/src/test_utils.rs#L12)):*
> ```XML
> use smol_str::SmolStr;
> 
> use crate::types::TokenStream as TokenStreamable;
> ```

now this renaming is unnecessary



_Suggestion:_
```XML
use crate::types::TokenStream;
```
___
*[`crates/cairo-lang-parser/src/types.rs` line 8 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6594#-OB0J5_w077g4R4RoTUZ:-OB0J5_w077g4R4RoTU_:b1nnfli) ([raw file](https://github.com/starkware-libs/cairo/blob/9342806d5681ec65e4cbb986a87c63e723f354da/crates/cairo-lang-parser/src/types.rs#L8)):*
> ```XML
> /// parser. Using it, we can control what the initial [TextOffset] should be used during creation of
> /// a Root [cairo_lang_syntax::node::SyntaxNode].
> pub trait TokenStream: Display {
> ```

This trait does not transmit actual tokens in any way. Don't you want to pass the source `FileId` here?
___
*[`crates/cairo-lang-parser/src/types.rs` line 10 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6594#-OB0HxmR3SYUtZyJg4Oo:-OB0HxmR3SYUtZyJg4Op:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9342806d5681ec65e4cbb986a87c63e723f354da/crates/cairo-lang-parser/src/types.rs#L10)):*
> ```XML
> pub trait TokenStream: Display {
>     fn get_start_offset(&self) -> Option<TextOffset>;
> }
> ```





_Suggestion:_
```XML
/// Used to run Cairo language parser over a custom source of tokens not produced by the lexer.
pub trait TokenStream: Display {
    /// Returns the starting [`TextOffset`] of the token stream, if any.
    ///
    /// This property is used as offset of a root [cairo_lang_syntax::node::SyntaxNode] produced
    /// when parsing this stream.
    fn get_start_offset(&self) -> Option<TextOffset>;
}
```

**Review by wawel37 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6594)* status: all files reviewed, 4 unresolved discussions (waiting on @maciektr and @mkaput)

___
*[`crates/cairo-lang-parser/src/test_utils.rs` line 12 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6594#-OB0HWaiD0foqnt2MyNd:-OB506pO3CQdj-e2cmbH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9342806d5681ec65e4cbb986a87c63e723f354da/crates/cairo-lang-parser/src/test_utils.rs#L12)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

now this renaming is unnecessary
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/types.rs` line 8 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6594#-OB0J5_w077g4R4RoTUZ:-OB50w_G9-ciwNHNE7Nn:b-urmp97) ([raw file](https://github.com/starkware-libs/cairo/blob/9342806d5681ec65e4cbb986a87c63e723f354da/crates/cairo-lang-parser/src/types.rs#L8)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

This trait does not transmit actual tokens in any way. Don't you want to pass the source `FileId` here?
</blockquote></details>

The `Display` Trait is responsible for providing the `to_string` function. From the compiler point of view, it's the only thing we want from the `TokenStream`
___
*[`crates/cairo-lang-parser/src/types.rs` line 10 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6594#-OB0HxmR3SYUtZyJg4Oo:-OB50r5B5qUjAUg624kR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9342806d5681ec65e4cbb986a87c63e723f354da/crates/cairo-lang-parser/src/types.rs#L10)):*
> ```XML
> pub trait TokenStream: Display {
>     fn get_start_offset(&self) -> Option<TextOffset>;
> }
> ```

Done.

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6594)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware, @maciektr, @orizi, and @wawel37)

___
*[`crates/cairo-lang-parser/src/types.rs` line 8 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6594#-OB0J5_w077g4R4RoTUZ:-OBA9A5m-cV1YTiKhN_R:bjgyor2) ([raw file](https://github.com/starkware-libs/cairo/blob/9342806d5681ec65e4cbb986a87c63e723f354da/crates/cairo-lang-parser/src/types.rs#L8)):*
<details><summary><i>Previously, wawel37 (Mateusz Kowalski) wrote…</i></summary><blockquote>

The `Display` Trait is responsible for providing the `to_string` function. From the compiler point of view, it's the only thing we want from the `TokenStream`
</blockquote></details>

OK. That's a bit counterintuitive because `Display` is meant to show something on the screen, and it enforces overhead of formatting. It also forces allocation, which can be avoided.

BTW, `to_string` actually comes from https://doc.rust-lang.org/stable/std/string/trait.ToString.html which is implemented for all Display-ables.

Nonetheless, because of allocations, I'd suggest adding an explicit method that returns `&str`

**Review by wawel37 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6594)* status: 4 of 9 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware, @maciektr, @mkaput, and @orizi)

___
*[`crates/cairo-lang-parser/src/types.rs` line 8 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6594#-OB0J5_w077g4R4RoTUZ:-OBAUbh07LZ1BOEC0rGn:b-861g5f) ([raw file](https://github.com/starkware-libs/cairo/blob/9342806d5681ec65e4cbb986a87c63e723f354da/crates/cairo-lang-parser/src/types.rs#L8)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

OK. That's a bit counterintuitive because `Display` is meant to show something on the screen, and it enforces overhead of formatting. It also forces allocation, which can be avoided.

BTW, `to_string` actually comes from https://doc.rust-lang.org/stable/std/string/trait.ToString.html which is implemented for all Display-ables.

Nonetheless, because of allocations, I'd suggest adding an explicit method that returns `&str`
</blockquote></details>

Done. Made it store the String inside the MockTokenStream and return a slice from a trait function.

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6594#-:-OBAt6HB8T0V2g-Ctlaw:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @maciektr, @orizi, and @wawel37)

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6594)* status: all files reviewed, 2 unresolved discussions (waiting on @maciektr, @orizi, and @wawel37)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 182 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6594#-OBUJolI-fvxqb_I3rdj:-OBUJolI-fvxqb_I3rdk:b-5c5ben) ([raw file](https://github.com/starkware-libs/cairo/blob/ba9fcc183d5e4bb0b1b12edaef1e48e51e7e014b/crates/cairo-lang-parser/src/parser.rs#L182)):*
> ```XML
>             diagnostics,
>             pending_skipped_token_diagnostics: Default::default(),
>         };
> ```

Use `Parser::new` (rebase if needed, it is a recent change).



_Code quote:_
```XML
        let parser = Parser {
            db,
            file_id,
            lexer,
            next_terminal,
            pending_trivia: Vec::new(),
            offset: Default::default(),
            current_width: Default::default(),
            last_trivia_length: Default::default(),
            diagnostics,
            pending_skipped_token_diagnostics: Default::default(),
        };
```

**Review by wawel37 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6594)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware, @maciektr, and @orizi)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 182 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6594#-OBUJolI-fvxqb_I3rdj:-OBUgGZy4j-jbuMbtY4_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ba9fcc183d5e4bb0b1b12edaef1e48e51e7e014b/crates/cairo-lang-parser/src/parser.rs#L182)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Use `Parser::new` (rebase if needed, it is a recent change).
</blockquote></details>

Done.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 9 files at r1, 1 of 2 files at r2, 1 of 4 files at r3, 4 of 5 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6594#-:-OBUkQS76AMKyT8C9MXF:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @maciektr, @orizi, and @wawel37)

**Review by mkaput — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6594)* status: all files reviewed, 1 unresolved discussion (waiting on @maciektr, @orizi, and @wawel37)

**Comment by wawel37** [comment]
Just to be sure @orizi, are you going to review this one or it's ready to merge?

**Review by wawel37 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6594)* status: all files reviewed, 1 unresolved discussion (waiting on @maciektr and @orizi)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6594#-OAwkMy3-VwlOdX8lvvb:-OBVbcql0IKvA8g2G8KJ:b4jtfm1) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

@gilbens-starkware
</blockquote></details>

Just to be sure @orizi, are you going to review that or is it ready to merge?

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1, 1 of 2 files at r2, 1 of 4 files at r3, 1 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6594)* status: all files reviewed, 5 unresolved discussions (waiting on @maciektr and @wawel37)

___
*[`crates/cairo-lang-parser/src/types.rs` line 13 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6594#-OBVcr1wBleugV45sMps:-OBVcr1x0eIe3lmA1LNc:b78jgvb) ([raw file](https://github.com/starkware-libs/cairo/blob/206c90795002bce03f56234c8bb1c4ceb8752a30/crates/cairo-lang-parser/src/types.rs#L13)):*
> ```XML
> 
>     /// Returns all tokens string content as a slice.
>     fn to_str(&self) -> &str;
> ```

seems more sensible to me - as it does not create anything new.



_Suggestion:_
```XML
    fn as_str(&self) -> &str;
```
___
*[`crates/cairo-lang-parser/src/test_utils.rs` line 47 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6594#-OBVcjg75IFdXCv7K69Z:-OBVcjg75IFdXCv7K69_:b-lw24iu) ([raw file](https://github.com/starkware-libs/cairo/blob/206c90795002bce03f56234c8bb1c4ceb8752a30/crates/cairo-lang-parser/src/test_utils.rs#L47)):*
> ```XML
> }
> 
> #[derive(Debug, Clone)]
> ```

doc all.
___
*[`crates/cairo-lang-parser/src/test_utils.rs` line 96 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6594#-OBVeFrpCYrmDOVgRiM-:-OBVeFrpCYrmDOVgRiM0:b-dgfa5n) ([raw file](https://github.com/starkware-libs/cairo/blob/206c90795002bce03f56234c8bb1c4ceb8752a30/crates/cairo-lang-parser/src/test_utils.rs#L96)):*
> ```XML
>     fn get_start_offset(&self) -> Option<TextOffset> {
>         self.tokens.first().map(|token| token.span.start)
>     }
> ```

is this used for testing if empty?

if not - maybe:

and change the `new_root_with_offset` to not get an optional value.



_Suggestion:_
```XML
    fn get_start_offset(&self) -> TextOffset {
        self.tokens.first().map(|token| token.span.start).unwrap_or_default()
    }
```
___
*[`crates/cairo-lang-parser/src/db_test.rs` line 63 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6594#-OBVcS9q2r-w44cgdY74:-OBVcS9q2r-w44cgdY75:b-s7lrpp) ([raw file](https://github.com/starkware-libs/cairo/blob/206c90795002bce03f56234c8bb1c4ceb8752a30/crates/cairo-lang-parser/src/db_test.rs#L63)):*
> ```XML
> #[test]
> fn test_token_stream_parser() {
>     let code = include_str!("parser_test_data/cairo_test_files/short.cairo");
> ```

can you read directly?
this would make changing the test file cause recompilation.



_Code quote:_
```XML
    let code = include_str!("parser_test_data/cairo_test_files/short.cairo");
```

**Review by wawel37 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6594)* status: all files reviewed, 4 unresolved discussions (waiting on @maciektr and @orizi)

___
*[`crates/cairo-lang-parser/src/db_test.rs` line 63 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6594#-OBVcS9q2r-w44cgdY74:-OBVsh4502xASvay--gm:b-160oqo) ([raw file](https://github.com/starkware-libs/cairo/blob/206c90795002bce03f56234c8bb1c4ceb8752a30/crates/cairo-lang-parser/src/db_test.rs#L63)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can you read directly?
this would make changing the test file cause recompilation.
</blockquote></details>

What do you exactly mean by "directly"? Something like this? https://github.com/starkware-libs/cairo/blob/31592e3f8efc03bfa847ca85507a3aafc3138e8d/crates/cairo-lang-formatter/src/test.rs#L101
___
*[`crates/cairo-lang-parser/src/test_utils.rs` line 47 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6594#-OBVcjg75IFdXCv7K69Z:-OBVqAJVBbVsYrHWG6_I:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/206c90795002bce03f56234c8bb1c4ceb8752a30/crates/cairo-lang-parser/src/test_utils.rs#L47)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc all.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/test_utils.rs` line 96 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6594#-OBVeFrpCYrmDOVgRiM-:-OBVqwRODzwRct9qQ-tP:btp4fkb) ([raw file](https://github.com/starkware-libs/cairo/blob/206c90795002bce03f56234c8bb1c4ceb8752a30/crates/cairo-lang-parser/src/test_utils.rs#L96)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is this used for testing if empty?

if not - maybe:

and change the `new_root_with_offset` to not get an optional value.
</blockquote></details>

The `TokenStream` interface was created to later be used not only in the testing. The only thing that was created directly for the sake of testing are `Mock*` structs. And as we don't want to change the interface of this function, i think it's better to leave it as it is. Sometimes TokenStream can be empty, and then the textoffset should be None (as there is no content inside)
___
*[`crates/cairo-lang-parser/src/types.rs` line 13 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6594#-OBVcr1wBleugV45sMps:-OBVnOa6-aBIK25bJVEX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/206c90795002bce03f56234c8bb1c4ceb8752a30/crates/cairo-lang-parser/src/types.rs#L13)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

seems more sensible to me - as it does not create anything new.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1, 2 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6594)* status: 7 of 9 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware, @maciektr, @mkaput, and @wawel37)

___
*[`crates/cairo-lang-parser/src/db_test.rs` line 63 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6594#-OBVcS9q2r-w44cgdY74:-OBVuSBV8E7FaAt845BP:bb7sa0c) ([raw file](https://github.com/starkware-libs/cairo/blob/206c90795002bce03f56234c8bb1c4ceb8752a30/crates/cairo-lang-parser/src/db_test.rs#L63)):*
<details><summary><i>Previously, wawel37 (Mateusz Kowalski) wrote…</i></summary><blockquote>

What do you exactly mean by "directly"? Something like this? https://github.com/starkware-libs/cairo/blob/31592e3f8efc03bfa847ca85507a3aafc3138e8d/crates/cairo-lang-formatter/src/test.rs#L101
</blockquote></details>

yes.
___
*[`crates/cairo-lang-parser/src/utils.rs` line 76 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6594#-OBVv9KT9gfMVLDbApqM:-OBVv9KT9gfMVLDbApqN:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/206c90795002bce03f56234c8bb1c4ceb8752a30/crates/cairo-lang-parser/src/utils.rs#L76)):*
> ```XML
>     }
> 
>     pub fn parse_token_stream(
> ```

doc
___
*[`crates/cairo-lang-parser/src/utils.rs` line 97 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6594#-OBVvA4a9TqTu1VkSyFe:-OBVvA4a9TqTu1VkSyFf:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/206c90795002bce03f56234c8bb1c4ceb8752a30/crates/cairo-lang-parser/src/utils.rs#L97)):*
> ```XML
>     }
> 
>     pub fn parse_token_stream_expr(
> ```

doc

**Review by wawel37 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6594)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware, @maciektr, @mkaput, and @orizi)

___
*[`crates/cairo-lang-parser/src/db_test.rs` line 63 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6594#-OBVcS9q2r-w44cgdY74:-OBWIWjl5Klkz0i5T3iS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/206c90795002bce03f56234c8bb1c4ceb8752a30/crates/cairo-lang-parser/src/db_test.rs#L63)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

yes.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/utils.rs` line 76 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6594#-OBVv9KT9gfMVLDbApqM:-OBW7SFJDojqu1FBfdOb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/206c90795002bce03f56234c8bb1c4ceb8752a30/crates/cairo-lang-parser/src/utils.rs#L76)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/utils.rs` line 97 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6594#-OBVvA4a9TqTu1VkSyFe:-OBW7SaB8ZtKjP0osktK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/206c90795002bce03f56234c8bb1c4ceb8752a30/crates/cairo-lang-parser/src/utils.rs#L97)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6594)* status: all files reviewed, 1 unresolved discussion (waiting on @maciektr and @wawel37)

___
*[`crates/cairo-lang-parser/src/db_test.rs` line 65 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6594#-OBWU2dg6VkMjOQIcWxQ:-OBWU2dh9wUnt96GeL-W:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5576ae149aef29b18f057e840a55c753c3129b0d/crates/cairo-lang-parser/src/db_test.rs#L65)):*
> ```XML
> #[test]
> fn test_token_stream_parser() {
>     let filepath: PathBuf = "src/parser_test_data/cairo_test_files/short.cairo".into();
> ```





_Suggestion:_
```XML
    let filepath: PathBuf = [env!("CARGO_MANIFEST_DIR"), "src/parser_test_data/cairo_test_files/short.cairo"].into_iter().collect()
```

**Review by wawel37 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6594)* status: all files reviewed, 1 unresolved discussion (waiting on @maciektr and @orizi)

___
*[`crates/cairo-lang-parser/src/db_test.rs` line 65 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6594#-OBWU2dg6VkMjOQIcWxQ:-OBZtpvX9fPQK9x96A-k:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5576ae149aef29b18f057e840a55c753c3129b0d/crates/cairo-lang-parser/src/db_test.rs#L65)):*
> ```XML
> #[test]
> fn test_token_stream_parser() {
>     let filepath: PathBuf = "src/parser_test_data/cairo_test_files/short.cairo".into();
> ```

Done.

**Pull request merged**
