### PR TITLE
ByteArray

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3609)

### CODE REVIEW

**Comment by yuvalsw** [comment]
Change target branch

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3609)* status: 2 of 6 files reviewed, 5 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/byte_array.cairo` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3609#-NZeFO_B6JzQ19r9lt_g:-NZeFO_B6JzQ19r9lt_h:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0e34bf1b8d7cd7c3ecee486bf2e4540c018aea8b/corelib/src/byte_array.cairo#L13)):*
> ```Cairo
> 
> // TODO(yuval): don't allow creation of invalid ByteArray?
> #[derive(Drop)]
> ```





_Suggestion:_
```Cairo
#[derive(Clone, Drop)]
```
___
*[`corelib/src/byte_array.cairo` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3609#-NZeFd0f9_USWaQNZHKC:-NZeFd0f9_USWaQNZHKD:b6owocw) ([raw file](https://github.com/starkware-libs/cairo/blob/0e34bf1b8d7cd7c3ecee486bf2e4540c018aea8b/corelib/src/byte_array.cairo#L18)):*
> ```Cairo
>     data: Array<bytes31>,
>     // Less than 31 bytes. The number of bytes in here is specified in `pending_word_len`.
>     pending_word: bytes31,
> ```

will reduce the to and from done in the byte append.



_Suggestion:_
```Cairo
    // Less than 31 bytes. The number of bytes in here is specified in `pending_word_len`.
    raw_pending_word: felt252,
```
___
*[`corelib/src/byte_array.cairo` line 92 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3609#-NZeE_BL43dvoOqMNefE:-NZeE_BM4aEaFiOlYk8L:bmm67en) ([raw file](https://github.com/starkware-libs/cairo/blob/0e34bf1b8d7cd7c3ecee486bf2e4540c018aea8b/corelib/src/byte_array.cairo#L92)):*
> ```Cairo
> 
>     // Appends a byte array to the end of `self`.
>     fn append(ref self: ByteArray, mut other: @ByteArray) {
> ```

`append` in rust is the consuming variant.



_Suggestion:_
```Cairo
extend
```
___
*[`corelib/src/byte_array.cairo` line 113 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3609#-NZeF2KlE1e5AS8geHFL:-NZeF2KlE1e5AS8geHFM:bp01q17) ([raw file](https://github.com/starkware-libs/cairo/blob/0e34bf1b8d7cd7c3ecee486bf2e4540c018aea8b/corelib/src/byte_array.cairo#L113)):*
> ```Cairo
>         result.append(right);
>         result
>     }
> ```

add a clone implementation and:



_Suggestion:_
```Cairo
    fn concat(left: @ByteArray, right: @ByteArray) -> ByteArray {
        let mut result = left.clone();
        result.append(right);
        result
    }
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3609)* status: 1 of 6 files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/byte_array.cairo` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3609#-NZeFO_B6JzQ19r9lt_g:-N_A806K5kloIp56X8eO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0e34bf1b8d7cd7c3ecee486bf2e4540c018aea8b/corelib/src/byte_array.cairo#L13)):*
> ```Cairo
> 
> // TODO(yuval): don't allow creation of invalid ByteArray?
> #[derive(Drop)]
> ```

Done.
___
*[`corelib/src/byte_array.cairo` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3609#-NZeFd0f9_USWaQNZHKC:-N_E-ZjW9gcXLzkEJ5ak:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0e34bf1b8d7cd7c3ecee486bf2e4540c018aea8b/corelib/src/byte_array.cairo#L18)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

will reduce the to and from done in the byte append.
</blockquote></details>

Done.
___
*[`corelib/src/byte_array.cairo` line 92 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3609#-NZeE_BL43dvoOqMNefE:-N_E0NTB-yqQzKUi4D3u:b-rqih77) ([raw file](https://github.com/starkware-libs/cairo/blob/0e34bf1b8d7cd7c3ecee486bf2e4540c018aea8b/corelib/src/byte_array.cairo#L92)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

`append` in rust is the consuming variant.
</blockquote></details>

I checked both c++ and Rust:
Append is +=, Concat is +. (Rust uses push/push_str, but the documentation says append)
https://doc.rust-lang.org/std/string/struct.String.html
https://en.cppreference.com/w/cpp/string/basic_string
___
*[`corelib/src/byte_array.cairo` line 113 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3609#-NZeF2KlE1e5AS8geHFL:-N_A8-9QAxxdpIhKYdaj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0e34bf1b8d7cd7c3ecee486bf2e4540c018aea8b/corelib/src/byte_array.cairo#L113)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add a clone implementation and:
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3609)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/byte_array.cairo` line 82 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3609#-N_TGhp41JezKJDFtNdu:-N_TGhp41JezKJDFtNdv:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b2d34907689fbe3a9e93bd3d9d5af978d54cd81b/corelib/src/byte_array.cairo#L82)):*
> ```Cairo
>                 return;
>             }
>         }
> ```





_Suggestion:_
```Cairo
        if self.pending_word_len == 0 {
            if len == BYTES_IN_BYTES31 {
                self.data.append(word.try_into().unwrap());
            } else {
                self.pending_word = word;
                self.pending_word_len = len;
            }
            return;
        }
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3609)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/byte_array.cairo` line 230 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3609#-N_U-_eo8E7dCs6XqshV:-N_U-_eo8E7dCs6XqshW:b-p1anyh) ([raw file](https://github.com/starkware-libs/cairo/blob/b2d34907689fbe3a9e93bd3d9d5af978d54cd81b/corelib/src/byte_array.cairo#L230)):*
> ```Cairo
>     // Note: this function doesn't update the new pending length of self. It's the caller's
>     // responsibility.
>     fn append_split_index_short(ref self: ByteArray, word: felt252, split_index: u8) {
> ```

rename to include the 16 - as we are not actually generic.
index_lt_16
index_16
index_gt_16



_Code quote:_
```Cairo
append_split_index_short
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3609)* status: 2 of 6 files reviewed, 5 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/byte_array.cairo` line 64 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3609#-N_UFiTACH-kTBMrCKxa:-N_UFiTACH-kTBMrCKxb:b-wbbql) ([raw file](https://github.com/starkware-libs/cairo/blob/b2d34907689fbe3a9e93bd3d9d5af978d54cd81b/corelib/src/byte_array.cairo#L64)):*
> ```Cairo
>         }
> 
>         self.append_word_fits_into_pending(word, len);
> ```

rather have shortest branch first.



_Suggestion:_
```Cairo
        if self.pending_word_len + len < BYTES_IN_BYTES31 {
            self.append_word_fits_into_pending(word, len);
            return;
        }
        let split_index = BYTES_IN_BYTES31 - self.pending_word_len;
        let (first, second) = split_bytes31(:word, :len, index: split_index);
        let to_append = first * one_shift_left_bytes_felt252(self.pending_word_len)
            + self.pending_word;
        self.data.append(to_append.try_into().unwrap());
        self.pending_word = second;
        self.pending_word_len = len - split_index;
```
___
*[`corelib/src/byte_array.cairo` line 112 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3609#-N_UGBSI6YkvD3fJmMfX:-N_UGBSI6YkvD3fJmMfY:bat9vr5) ([raw file](https://github.com/starkware-libs/cairo/blob/b2d34907689fbe3a9e93bd3d9d5af978d54cd81b/corelib/src/byte_array.cairo#L112)):*
> ```Cairo
>                     }
>                 };
>             };
> ```

after rebase.



_Suggestion:_
```Cairo
            loop {
                match other_data.pop_front() {
                    Option::Some(current_word) => {
                        self_data.append(*current_word);
                    },
                    Option::None => {
                        break;
                    }
                };
            };
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3609)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/byte_array.cairo` line 64 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3609#-N_UFiTACH-kTBMrCKxa:-N_Y-FJW91sPPR04tjis:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b2d34907689fbe3a9e93bd3d9d5af978d54cd81b/corelib/src/byte_array.cairo#L64)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rather have shortest branch first.
</blockquote></details>

Done.
___
*[`corelib/src/byte_array.cairo` line 82 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3609#-N_TGhp41JezKJDFtNdu:-N_Y-Wh_9CnoggOXSmqB:bfdl8qp) ([raw file](https://github.com/starkware-libs/cairo/blob/b2d34907689fbe3a9e93bd3d9d5af978d54cd81b/corelib/src/byte_array.cairo#L82)):*
> ```Cairo
>                 return;
>             }
>         }
> ```

Unfortunately this is also not possible, probably due to the same bug in borrowing. I get `Variable was previously moved. Trait has no implementation in context: core::traits::Copy::<core::array::Array::<core::bytes\_31::bytes31>>` for the self in the if block.
___
*[`corelib/src/byte_array.cairo` line 112 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3609#-N_UGBSI6YkvD3fJmMfX:-N_YJHIp34uX7pcFSWtp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b2d34907689fbe3a9e93bd3d9d5af978d54cd81b/corelib/src/byte_array.cairo#L112)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

after rebase.
</blockquote></details>

Done.
___
*[`corelib/src/byte_array.cairo` line 230 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3609#-N_U-_eo8E7dCs6XqshV:-N_Y2tgH-iJt2PNRmwHK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b2d34907689fbe3a9e93bd3d9d5af978d54cd81b/corelib/src/byte_array.cairo#L230)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rename to include the 16 - as we are not actually generic.
index_lt_16
index_16
index_gt_16
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3609)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/byte_array.cairo` line 214 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3609#-N_Z3OPl9U9kZTIhXM1I:-N_Z3OPl9U9kZTIhXM1J:buxfdcz) ([raw file](https://github.com/starkware-libs/cairo/blob/30c13218b754b32831860d34c538070e735a8a0f/corelib/src/byte_array.cairo#L214)):*
> ```Cairo
> 
>         let new_pending = self.pending_word.into()
>             + byte.into() * one_shift_left_bytes_felt252(self.pending_word_len);
> ```

is it better to pack in this endianity?

if you'd pack the otherway won't you just need to do:
let new_pending = self.pending_word * 256 + byte.into();



_Code quote:_
```Cairo
        let new_pending = self.pending_word.into()
            + byte.into() * one_shift_left_bytes_felt252(self.pending_word_len);
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3609)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/byte_array.cairo` line 214 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3609#-N_Z3OPl9U9kZTIhXM1I:-N_eTFR61pgKtHMqV_L-:bva7jya) ([raw file](https://github.com/starkware-libs/cairo/blob/30c13218b754b32831860d34c538070e735a8a0f/corelib/src/byte_array.cairo#L214)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

do note that it despite not affecting the interface - it would affect all serialization of the struct.
so we have to decide on a form before we allow this to exist.
</blockquote></details>

I did not yet implement serde

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3609)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/byte_array.cairo` line 233 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3609#-N_jwl2A2j3dzZ1wVq1X:-N_jwl2A2j3dzZ1wVq1Y:b-uuwa75) ([raw file](https://github.com/starkware-libs/cairo/blob/46b0d8b5d7cc29a979deb10785531b2f84646b96/corelib/src/byte_array.cairo#L233)):*
> ```Cairo
>     // responsibility.
>     fn append_split_index_lt_16(ref self: ByteArray, word: felt252, split_index: u8) {
>         let u256{low, high } = u256_from_felt252(word);
> ```

(now works without `: u256`



_Suggestion:_
```Cairo
let u256{low, high } = word.into();
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3609)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/byte_array.cairo` line 233 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3609#-N_jwl2A2j3dzZ1wVq1X:-NaBax-94FvIHKIFyeO4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/46b0d8b5d7cc29a979deb10785531b2f84646b96/corelib/src/byte_array.cairo#L233)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

(now works without `: u256`
</blockquote></details>

Done.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3609)* status: 3 of 7 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/byte_array.cairo` line 99 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3609#-NaC6G-M4ExH7PYYHAgv:-NaN4yz-Antd3gIv7Rvp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f3f16d3bef76afd99705b1dafd7bc344d9c712b8/corelib/src/byte_array.cairo#L99)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

check if resolved.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3609)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/bytes_31.cairo` line 60 at r8](https://reviewable.io/reviews/starkware-libs/cairo/3609#-Na_eINP55j74uVtEB3c:-Na_eINP55j74uVtEB3d:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/16199374791ba12da53bda1fdb9c86326a23f225/corelib/src/bytes_31.cairo#L60)):*
> ```Cairo
> }
> 
> // Splits a bytes31 into two bytes31s at the given index (LSB's index is 0)..
> ```





_Suggestion:_
```Cairo
// Splits a bytes31 into two bytes31s at the given index (LSB's index is 0).
```
___
*[`corelib/src/test/byte_array_test.cairo` line 22 at r8](https://reviewable.io/reviews/starkware-libs/cairo/3609#-Na_f2n0Ee7Llp_Rr-PA:-Na_f2n0Ee7Llp_Rr-PB:b-ws2yd) ([raw file](https://github.com/starkware-libs/cairo/blob/16199374791ba12da53bda1fdb9c86326a23f225/corelib/src/test/byte_array_test.cairo#L22)):*
> ```Cairo
>     let mut expected_data: Array<felt252> = Default::default();
>     expected_data.append(0x0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f);
>     compare_byte_array(@ba, expected_data.span(), 2, 0x2021);
> ```

generally use it to make the test cases themselves more readable (mostly at `test_append_*` tests).



_Suggestion:_
```Cairo
    let expected_data = array![0x0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f].span();
    compare_byte_array(@ba, expected_data, 2, 0x2021);
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3609)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/bytes_31.cairo` line 60 at r8](https://reviewable.io/reviews/starkware-libs/cairo/3609#-Na_eINP55j74uVtEB3c:-Na_umv7276kddJP1euT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/16199374791ba12da53bda1fdb9c86326a23f225/corelib/src/bytes_31.cairo#L60)):*
> ```Cairo
> }
> 
> // Splits a bytes31 into two bytes31s at the given index (LSB's index is 0)..
> ```

Done.
___
*[`corelib/src/test/byte_array_test.cairo` line 22 at r8](https://reviewable.io/reviews/starkware-libs/cairo/3609#-Na_f2n0Ee7Llp_Rr-PA:-Na_ulncEmNyQJTZMXCa:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/16199374791ba12da53bda1fdb9c86326a23f225/corelib/src/test/byte_array_test.cairo#L22)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

generally use it to make the test cases themselves more readable (mostly at `test_append_*` tests).
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3609#-:-Na_w39mE0ZZodMRXDjU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
