### PR TITLE
Tomer/fix implize type with generic impls

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5521)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5521)* status: 2 of 11 files reviewed, 7 unresolved discussions (waiting on @TomerStarkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5521#-NxNG-OkAS41LE3sXUdx):*
rebase.
___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 160 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5521#-NxNGMg_8-Asf1GRAkQK:-NxNGMg_8-Asf1GRAkQL:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ae59167d8ec166bb467b1c00a5c724fb4c01878f/crates/cairo-lang-semantic/src/items/functions.rs#L160)):*
> ```XML
>                     substitution: &GenericSubstitution::from_impl(id.impl_id),
>                 }
>                 .rewrite(signature)
> ```





_Suggestion:_
```XML
                )?;
                let substitution = &GenericSubstitution::from_impl(id.impl_id);
                SubstitutionRewriter { db, substitution }.rewrite(signature)
```
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1452 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5521#-NxNGbxW90gHMJtI20s1:-NxNGbxW90gHMJtI20s2:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ae59167d8ec166bb467b1c00a5c724fb4c01878f/crates/cairo-lang-semantic/src/items/imp.rs#L1452)):*
> ```XML
>     let substitution = &concrete_impl.substitution(db)?;
>     let ty = SubstitutionRewriter { db, substitution }.rewrite(ty)?;
>     Ok(Some(ty))
> ```





_Suggestion:_
```XML
    Ok(Some(SubstitutionRewriter { db, substitution }.rewrite(ty)?))
```
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 2131 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5521#-NxNH4NIBd0y_jZkQEZX:-NxNH4NIBd0y_jZkQEZY:byo7onq) ([raw file](https://github.com/starkware-libs/cairo/blob/ae59167d8ec166bb467b1c00a5c724fb4c01878f/crates/cairo-lang-semantic/src/items/tests/trait_type#L2131)):*
> ```
> //! > ==========================================================================
> 
> //! > using a trait's associated type in a concrete impl with generic args.
> ```

fix test name to validate the failure - as impls shouldn't be discovered by trait types.
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 2173 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5521#-NxNGsM-2oZ0zSmtwepF:-NxNGsM-2oZ0zSmtwepG:b-1ex4r) ([raw file](https://github.com/starkware-libs/cairo/blob/ae59167d8ec166bb467b1c00a5c724fb4c01878f/crates/cairo-lang-semantic/src/items/tests/trait_type#L2173)):*
> ```
> //! > ==========================================================================
> 
> //! > using an impl's function with an associated type in it's signature of a concrete impl with generic args.
> ```

100 chars.
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 2202 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5521#-NxNGrC-CxIrcLcyRGbX:-NxNGrC-CxIrcLcyRGbY:b-1ex4r) ([raw file](https://github.com/starkware-libs/cairo/blob/ae59167d8ec166bb467b1c00a5c724fb4c01878f/crates/cairo-lang-semantic/src/items/tests/trait_type#L2202)):*
> ```
> //! > ==========================================================================
> 
> //! > using a trait's function with an associated type in it's signature of a concrete impl with generic args.
> ```

100 chars.
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 2231 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5521#-NxNGnAmBts0o0btxsUz:-NxNGnAmBts0o0btxsV-:b-1ex4r) ([raw file](https://github.com/starkware-libs/cairo/blob/ae59167d8ec166bb467b1c00a5c724fb4c01878f/crates/cairo-lang-semantic/src/items/tests/trait_type#L2231)):*
> ```
> //! > ==========================================================================
> 
> //! > using a trait's function with an associated type in it's signature of a generic concrete impl with generic args.
> ```

100 chars.

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 4 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5521)* status: all files reviewed, 6 unresolved discussions (waiting on @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5521)* status: 8 of 11 files reviewed, 6 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 160 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5521#-NxNGMg_8-Asf1GRAkQK:-NxNUKkr1oYl41tMQ6St:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ae59167d8ec166bb467b1c00a5c724fb4c01878f/crates/cairo-lang-semantic/src/items/functions.rs#L160)):*
> ```XML
>                     substitution: &GenericSubstitution::from_impl(id.impl_id),
>                 }
>                 .rewrite(signature)
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1452 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5521#-NxNGbxW90gHMJtI20s1:-NxNUaqH6jmO0i-GPa_O:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ae59167d8ec166bb467b1c00a5c724fb4c01878f/crates/cairo-lang-semantic/src/items/imp.rs#L1452)):*
> ```XML
>     let substitution = &concrete_impl.substitution(db)?;
>     let ty = SubstitutionRewriter { db, substitution }.rewrite(ty)?;
>     Ok(Some(ty))
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 2131 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5521#-NxNH4NIBd0y_jZkQEZX:-NxNUrE45I1pwfcwhISC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ae59167d8ec166bb467b1c00a5c724fb4c01878f/crates/cairo-lang-semantic/src/items/tests/trait_type#L2131)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix test name to validate the failure - as impls shouldn't be discovered by trait types.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 2173 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5521#-NxNGsM-2oZ0zSmtwepF:-NxNZdQ70z16EQxU5xG9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ae59167d8ec166bb467b1c00a5c724fb4c01878f/crates/cairo-lang-semantic/src/items/tests/trait_type#L2173)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

100 chars.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 2202 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5521#-NxNGrC-CxIrcLcyRGbX:-NxNZdpV8fSyJb3jzQbu:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ae59167d8ec166bb467b1c00a5c724fb4c01878f/crates/cairo-lang-semantic/src/items/tests/trait_type#L2202)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

100 chars.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 2231 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5521#-NxNGnAmBts0o0btxsUz:-NxNZuif7RlBCPZR6oqu:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ae59167d8ec166bb467b1c00a5c724fb4c01878f/crates/cairo-lang-semantic/src/items/tests/trait_type#L2231)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

100 chars.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5521#-:-NxNa2YX2n3tr-2ySTH9:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5521)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
