### PR TITLE
Added basic erc20 test contract.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:d4b76750

---

**Stack**:
- #1866
- #1864
- #1863
- #1862
- #1860
- #1857
- #1855
- #1854
- #1853 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1853)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @bbrandtom, @liorgold2, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/casm_contract_class.rs` line 163 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1853#-NMTtREjD0TQrs-__AQn:-NMTtREk47J7-lZQVwUv:b-hay66i) ([raw file](https://github.com/starkware-libs/cairo/blob/5037e032bc3b2d74eeeba44173c79d1c796e71cb/crates/cairo-lang-starknet/src/casm_contract_class.rs#L163)):*
> ```XML
>             {
>                 eprintln!("Unexpected entry point cost.");
>             }
> ```

revert?



_Code quote:_
```XML
            // TODO(orizi): Convert back into an assert when there's a valid const cost.
            if metadata.gas_info.function_costs[function.id.clone()]
                != OrderedHashMap::from_iter([(CostTokenType::Step, ENTRY_POINT_COST)])
            {
                eprintln!("Unexpected entry point cost.");
            }
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/plugin_test_data/hello_starknet` line 91 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1853#-NMTt_hR6ABycvOWsY8s:-NMTt_hR6ABycvOWsY8t:b-jpuj5k) ([raw file](https://github.com/starkware-libs/cairo/blob/cfeb13fd9f05be80b47919e0668c651201ba27ee/crates/cairo-lang-starknet/src/plugin_test_data/hello_starknet#L91)):*
> ```
>                     let mut err_data = array_new();
>                     array_append(ref err_data, 'Out of gas');
>                     panic(err_data);
> ```

both options compile?



_Code quote:_
```
 panic(err_data);
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/test_data/erc20.cairo` line 7 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1853#-NMTtjBjAds9W7EH6Lz-:-NMTtjBjAds9W7EH6Lz0:b-ldq9mc) ([raw file](https://github.com/starkware-libs/cairo/blob/5037e032bc3b2d74eeeba44173c79d1c796e71cb/crates/cairo-lang-starknet/test_data/erc20.cairo#L7)):*
> ```Cairo
>     total_supply: u256,
>     balances: Map::<felt, u256>,
>     allowances: Map::<(felt, felt), u256>,
> ```

is it hard to fix the formatting?



_Code quote:_
```Cairo
    struct Storage { name: felt, symbol: felt, // TODO(orizi): Move to u8.
    decimals: felt,
    total_supply: u256,
    balances: Map::<felt, u256>,
    allowances: Map::<(felt, felt), u256>,
    }
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1853)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @bbrandtom, @ilyalesokhin-starkware, @liorgold2, and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/casm_contract_class.rs` line 163 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1853#-NMTtREjD0TQrs-__AQn:-NMTtbkeDuhL293hjbGd:b-vx7gv5) ([raw file](https://github.com/starkware-libs/cairo/blob/5037e032bc3b2d74eeeba44173c79d1c796e71cb/crates/cairo-lang-starknet/src/casm_contract_class.rs#L163)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

revert?
</blockquote></details>

no - the code won't compile with it - and i want the assert to return after this todo is fixed.
(since we have enrtypoints that require pedersen, and some that don't)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1853)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @bbrandtom, @ilyalesokhin-starkware, @liorgold2, and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/plugin_test_data/hello_starknet` line 91 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1853#-NMTt_hR6ABycvOWsY8s:-NMTtqh90Ey-yaM1-SAs:b2nign6) ([raw file](https://github.com/starkware-libs/cairo/blob/cfeb13fd9f05be80b47919e0668c651201ba27ee/crates/cairo-lang-starknet/src/plugin_test_data/hello_starknet#L91)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

both options compile?
</blockquote></details>

yes
___
*[`crates/cairo-lang-starknet/test_data/erc20.cairo` line 7 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1853#-NMTtjBjAds9W7EH6Lz-:-NMTtsJw21Eit4l8Vcer:b-djqp2z) ([raw file](https://github.com/starkware-libs/cairo/blob/5037e032bc3b2d74eeeba44173c79d1c796e71cb/crates/cairo-lang-starknet/test_data/erc20.cairo#L7)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

is it hard to fix the formatting?
</blockquote></details>

maybe - not relevant for the pr itself.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/test_data/erc20.cairo` line 106 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1853#-NMTv4os6E6fWa43Pazo:-NMTv4os6E6fWa43Pazp:b-gbcd5b) ([raw file](https://github.com/starkware-libs/cairo/blob/5037e032bc3b2d74eeeba44173c79d1c796e71cb/crates/cairo-lang-starknet/test_data/erc20.cairo#L106)):*
> ```Cairo
>         let current_allowance = allowances::read((owner, spender));
>         let ONES_MASK = 0xffffffffffffffffffffffffffffffff_u128;
>         if current_allowance.low != ONES_MASK | current_allowance.high != ONES_MASK {
> ```

can you move this to

is_unlimited_allowence()?



_Code quote:_
```Cairo
 if current_allowance.low != ONES_MASK | current_allowance.high != ONES_MASK
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1853)* status: 1 of 12 files reviewed, 6 unresolved discussions (waiting on @bbrandtom, @ilyalesokhin-starkware, @liorgold2, and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/test_data/erc20.cairo` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1853#-NMTtocm7YJ0P3tbb7U_:-NMTvxTS7BxTHgH6McO8:b-21b9jg) ([raw file](https://github.com/starkware-libs/cairo/blob/5037e032bc3b2d74eeeba44173c79d1c796e71cb/crates/cairo-lang-starknet/test_data/erc20.cairo#L18)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

didn't you do that already?
</blockquote></details>

no - that is a following pr.
___
*[`crates/cairo-lang-starknet/test_data/erc20.cairo` line 106 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1853#-NMTvBPmBaHUseq-4itj:-NMTw2w61rtiOdkztllT:b-luvx6o) ([raw file](https://github.com/starkware-libs/cairo/blob/5037e032bc3b2d74eeeba44173c79d1c796e71cb/crates/cairo-lang-starknet/test_data/erc20.cairo#L106)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't see it in the cairo0 code? did you decide to ad it?
</blockquote></details>

https://github.com/OpenZeppelin/cairo-contracts/blob/ad399728e6fcd5956a4ed347fb5e8ee731d37ec4/src/openzeppelin/token/erc20/library.cairo#L347
___
*[`crates/cairo-lang-starknet/test_data/erc20.cairo` line 106 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1853#-NMTv4os6E6fWa43Pazo:-NMTwCohApy0yd0rTjNX:b-gzcs3d) ([raw file](https://github.com/starkware-libs/cairo/blob/5037e032bc3b2d74eeeba44173c79d1c796e71cb/crates/cairo-lang-starknet/test_data/erc20.cairo#L106)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

can you move this to

is_unlimited_allowence()?

</blockquote></details>

keeping it similar to the original code - but will extract to var.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1853)* status: 1 of 12 files reviewed, 7 unresolved discussions (waiting on @bbrandtom, @liorgold2, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/test_data/erc20.cairo` line 21 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1853#-NMTwG4K1UdxCJu_spRP:-NMTwG4K1UdxCJu_spRQ:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/5037e032bc3b2d74eeeba44173c79d1c796e71cb/crates/cairo-lang-starknet/test_data/erc20.cairo#L21)):*
> ```Cairo
>     #[external]
>     fn constructor(
>         name_: felt, symbol_: felt, decimals_: felt, initial_supply: u256, recipient: felt
> ```





_Suggestion:_
```Cairo
minter_address
```
___
*[`crates/cairo-lang-starknet/test_data/erc20.cairo` line 26 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1853#-NMTwHRP8OK5of2YaEZe:-NMTwHRP8OK5of2YaEZf:b2ni2nk) ([raw file](https://github.com/starkware-libs/cairo/blob/5037e032bc3b2d74eeeba44173c79d1c796e71cb/crates/cairo-lang-starknet/test_data/erc20.cairo#L26)):*
> ```Cairo
>         symbol::write(symbol_);
>         decimals::write(decimals_);
>         assert(recipient != 0, 'ERC20: mint to the 0 address');
> ```

fix



_Code quote:_
```Cairo
ERC20: mint to the 0 address
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1853)* status: 1 of 12 files reviewed, 7 unresolved discussions (waiting on @bbrandtom, @ilyalesokhin-starkware, @liorgold2, and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/test_data/erc20.cairo` line 21 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1853#-NMTwG4K1UdxCJu_spRP:-NMTww-2Bo7-cly1_q-W:bcvn06j) ([raw file](https://github.com/starkware-libs/cairo/blob/5037e032bc3b2d74eeeba44173c79d1c796e71cb/crates/cairo-lang-starknet/test_data/erc20.cairo#L21)):*
> ```Cairo
>     #[external]
>     fn constructor(
>         name_: felt, symbol_: felt, decimals_: felt, initial_supply: u256, recipient: felt
> ```

these are the names in the other contract - for now rather conform to it.
___
*[`crates/cairo-lang-starknet/test_data/erc20.cairo` line 26 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1853#-NMTwHRP8OK5of2YaEZe:-NMTx1eYDdZ6HXVjbgpS:b-7ropln) ([raw file](https://github.com/starkware-libs/cairo/blob/5037e032bc3b2d74eeeba44173c79d1c796e71cb/crates/cairo-lang-starknet/test_data/erc20.cairo#L26)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

fix
</blockquote></details>

ditto

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 6 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1853)* status: 7 of 12 files reviewed, 3 unresolved discussions (waiting on @bbrandtom, @liorgold2, and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/test_data/erc20.cairo` line 21 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1853#-NMTwG4K1UdxCJu_spRP:-NMTyDs-6h6b3zELVAci:bve7uo5) ([raw file](https://github.com/starkware-libs/cairo/blob/5037e032bc3b2d74eeeba44173c79d1c796e71cb/crates/cairo-lang-starknet/test_data/erc20.cairo#L21)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

these are the names in the other contract - for now rather conform to it.
</blockquote></details>

I don't see it:
https://github.com/OpenZeppelin/cairo-contracts/blob/ad399728e6fcd5956a4ed347fb5e8ee731d37ec4/src/openzeppelin/token/erc20/library.cairo#L66

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1853)* status: 7 of 12 files reviewed, 2 unresolved discussions (waiting on @bbrandtom, @liorgold2, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/test_data/erc20.cairo` line 107 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1853#-NMTyMZ_54NdI4Bq1lDY:-NMTyMZ_54NdI4Bq1lDZ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7c52cc7b53a27b13ab3f57489c483345ee9a96f3/crates/cairo-lang-starknet/test_data/erc20.cairo#L107)):*
> ```Cairo
>         let ONES_MASK = 0xffffffffffffffffffffffffffffffff_u128;
>         let is_inifinity = current_allowance.low != ONES_MASK | current_allowance.high != ONES_MASK;
>         if is_inifinity {
> ```





_Suggestion:_
```Cairo
 if !is_inifinity {
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1853)* status: 7 of 12 files reviewed, 2 unresolved discussions (waiting on @bbrandtom, @liorgold2, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/test_data/erc20.cairo` line 106 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1853#-NMTv4os6E6fWa43Pazo:-NMTyQFr28wMKyqslC2l:bmlsml1) ([raw file](https://github.com/starkware-libs/cairo/blob/5037e032bc3b2d74eeeba44173c79d1c796e71cb/crates/cairo-lang-starknet/test_data/erc20.cairo#L106)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

keeping it similar to the original code - but will extract to var.
</blockquote></details>

I prefer is_unlimited_allowence..

why do we have to keep their stupid name?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1853)* status: 7 of 12 files reviewed, 3 unresolved discussions (waiting on @bbrandtom, @ilyalesokhin-starkware, @liorgold2, and @orizi)

___
*[`crates/cairo-lang-starknet/test_data/erc20.cairo` line 10 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1853#-NMU9Nwf3clm3lI8U7Y8:-NMU9XDq9YKusOdgNcAu:b-y7u4gj) ([raw file](https://github.com/starkware-libs/cairo/blob/7c52cc7b53a27b13ab3f57489c483345ee9a96f3/crates/cairo-lang-starknet/test_data/erc20.cairo#L10)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Yuck, did we really go with this for events??
</blockquote></details>

Another suggestion, for example, a single Enum

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1853)* status: 7 of 12 files reviewed, 5 unresolved discussions (waiting on @bbrandtom, @ilyalesokhin-starkware, @liorgold2, and @orizi)

___
*[`crates/cairo-lang-starknet/test_data/erc20.cairo` line 20 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1853#-NMU9q7H5JUGRZExsqmZ:-NMU9q7H5JUGRZExsqm_:bkfoko5) ([raw file](https://github.com/starkware-libs/cairo/blob/7c52cc7b53a27b13ab3f57489c483345ee9a96f3/crates/cairo-lang-starknet/test_data/erc20.cairo#L20)):*
> ```Cairo
>     // TODO(orizi): Make into a constructor attribute.
>     #[external]
>     fn constructor(
> ```

Does the constructor have a different behaviour than other functions, or is it just a name? Eaither way, it's kinda weird right now,
___
*[`crates/cairo-lang-starknet/test_data/erc20.cairo` line 33 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1853#-NMUAAxV3gNQuJHqApB-:-NMUAAxV3gNQuJHqApB0:b3cjo3e) ([raw file](https://github.com/starkware-libs/cairo/blob/7c52cc7b53a27b13ab3f57489c483345ee9a96f3/crates/cairo-lang-starknet/test_data/erc20.cairo#L33)):*
> ```Cairo
>     }
> 
>     #[view]
> ```

TODO: Auto add these in the plugin (given an annotation perhaps)



_Code quote:_
```Cairo
[view]
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1853)* status: 7 of 12 files reviewed, 5 unresolved discussions (waiting on @bbrandtom, @ilyalesokhin-starkware, @liorgold2, and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/test_data/erc20.cairo` line 21 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1853#-NMTwG4K1UdxCJu_spRP:-NMUS21AAmw31L_DF4Ac:b-luvxz2) ([raw file](https://github.com/starkware-libs/cairo/blob/5037e032bc3b2d74eeeba44173c79d1c796e71cb/crates/cairo-lang-starknet/test_data/erc20.cairo#L21)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't see it:
https://github.com/OpenZeppelin/cairo-contracts/blob/ad399728e6fcd5956a4ed347fb5e8ee731d37ec4/src/openzeppelin/token/erc20/library.cairo#L66
</blockquote></details>

https://github.com/OpenZeppelin/cairo-contracts/blob/ad399728e6fcd5956a4ed347fb5e8ee731d37ec4/src/openzeppelin/token/erc20/library.cairo#L228
___
*[`crates/cairo-lang-starknet/test_data/erc20.cairo` line 10 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1853#-NMU9Nwf3clm3lI8U7Y8:-NMURYXS1-h-Q10fNrQI:bd6zfo4) ([raw file](https://github.com/starkware-libs/cairo/blob/7c52cc7b53a27b13ab3f57489c483345ee9a96f3/crates/cairo-lang-starknet/test_data/erc20.cairo#L10)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Another suggestion, for example, a single Enum
</blockquote></details>

pretty good idea - not for this pr anyway - as events were added in an older pr.
___
*[`crates/cairo-lang-starknet/test_data/erc20.cairo` line 20 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1853#-NMU9q7H5JUGRZExsqmZ:-NMURiL7DfBo_5AVTiPp:b-g1oy3o) ([raw file](https://github.com/starkware-libs/cairo/blob/7c52cc7b53a27b13ab3f57489c483345ee9a96f3/crates/cairo-lang-starknet/test_data/erc20.cairo#L20)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Does the constructor have a different behaviour than other functions, or is it just a name? Eaither way, it's kinda weird right now,
</blockquote></details>

it would have - it would create a constructor entry point - happens in a following pr.
___
*[`crates/cairo-lang-starknet/test_data/erc20.cairo` line 33 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1853#-NMUAAxV3gNQuJHqApB-:-NMUS6Uf6iCzOrkJVmkt:bcpypoq) ([raw file](https://github.com/starkware-libs/cairo/blob/7c52cc7b53a27b13ab3f57489c483345ee9a96f3/crates/cairo-lang-starknet/test_data/erc20.cairo#L33)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

TODO: Auto add these in the plugin (given an annotation perhaps)
</blockquote></details>

this feels like an external consideration - not sure this fits for a todo.
___
*[`crates/cairo-lang-starknet/test_data/erc20.cairo` line 107 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1853#-NMTyMZ_54NdI4Bq1lDY:-NMUSzJfCJ6XzpmRm1G1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7c52cc7b53a27b13ab3f57489c483345ee9a96f3/crates/cairo-lang-starknet/test_data/erc20.cairo#L107)):*
> ```Cairo
>         let ONES_MASK = 0xffffffffffffffffffffffffffffffff_u128;
>         let is_inifinity = current_allowance.low != ONES_MASK | current_allowance.high != ONES_MASK;
>         if is_inifinity {
> ```

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/test_data/erc20.cairo` line 21 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1853#-NMTwG4K1UdxCJu_spRP:-NMUUFxMBpT1plrxCDmJ:bbnql2d) ([raw file](https://github.com/starkware-libs/cairo/blob/5037e032bc3b2d74eeeba44173c79d1c796e71cb/crates/cairo-lang-starknet/test_data/erc20.cairo#L21)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

https://github.com/OpenZeppelin/cairo-contracts/blob/ad399728e6fcd5956a4ed347fb5e8ee731d37ec4/src/openzeppelin/token/erc20/library.cairo#L228
</blockquote></details>

but the constructor does not call mint.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/test_data/erc20.cairo` line 107 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1853#-NMTyMZ_54NdI4Bq1lDY:-NMUVN4p5zHA2IOLGaEW:b-ut7np8) ([raw file](https://github.com/starkware-libs/cairo/blob/7c52cc7b53a27b13ab3f57489c483345ee9a96f3/crates/cairo-lang-starknet/test_data/erc20.cairo#L107)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see it

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1853)* status: 7 of 12 files reviewed, 4 unresolved discussions (waiting on @bbrandtom, @ilyalesokhin-starkware, @liorgold2, and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/test_data/erc20.cairo` line 107 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1853#-NMTyMZ_54NdI4Bq1lDY:-NMUarwP8-0kgFFupvCD:bsiogv8) ([raw file](https://github.com/starkware-libs/cairo/blob/7c52cc7b53a27b13ab3f57489c483345ee9a96f3/crates/cairo-lang-starknet/test_data/erc20.cairo#L107)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't see it
</blockquote></details>

look again

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1853)* status: 7 of 12 files reviewed, 4 unresolved discussions (waiting on @bbrandtom, @ilyalesokhin-starkware, @liorgold2, and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/test_data/erc20.cairo` line 21 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1853#-NMTwG4K1UdxCJu_spRP:-NMUb2Gp93gU7Q1yeKtU:b-61vieh) ([raw file](https://github.com/starkware-libs/cairo/blob/5037e032bc3b2d74eeeba44173c79d1c796e71cb/crates/cairo-lang-starknet/test_data/erc20.cairo#L21)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

but the constructor does not call mint.
</blockquote></details>

https://github.com/OpenZeppelin/cairo-contracts/blob/ad399728e6fcd5956a4ed347fb5e8ee731d37ec4/src/openzeppelin/token/erc20/presets/ERC20.cairo#L25

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/test_data/erc20.cairo` line 107 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1853#-NMTyMZ_54NdI4Bq1lDY:-NMUhPy40yQS1eYjmb1i:b-hj626x) ([raw file](https://github.com/starkware-libs/cairo/blob/7c52cc7b53a27b13ab3f57489c483345ee9a96f3/crates/cairo-lang-starknet/test_data/erc20.cairo#L107)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

look again
</blockquote></details>

don't you want to change the allowance only if it is not unlimited ?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1853)* status: 8 of 12 files reviewed, 3 unresolved discussions (waiting on @bbrandtom, @liorgold2, and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/test_data/erc20.cairo` line 108 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1853#-NMUi1wf-U5yUUL835XO:-NMUi1wf-U5yUUL835XP:bmkj2n2) ([raw file](https://github.com/starkware-libs/cairo/blob/802d19245cee977c5d21acf767e4f97d56a29288/crates/cairo-lang-starknet/test_data/erc20.cairo#L108)):*
> ```Cairo
>         let is_unlimited_allowence = current_allowance.low == ONES_MASK & current_allowance.high == ONES_MASK;
>         if is_unlimited_allowence {
>             approve_helper(owner, spender, current_allowance - amount);
> ```

I find it a bit strange that you emit an event here, but I guess you've copied it from the original code.



_Code quote:_
```Cairo
 approve_helper(owner, spender, current_allowance - amount);
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1853)* status: 8 of 12 files reviewed, 3 unresolved discussions (waiting on @bbrandtom, @liorgold2, and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/test_data/erc20.cairo` line 107 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1853#-NMTyMZ_54NdI4Bq1lDY:-NMUvHEI3Esh1pkmzc_C:b-w5azhz) ([raw file](https://github.com/starkware-libs/cairo/blob/7c52cc7b53a27b13ab3f57489c483345ee9a96f3/crates/cairo-lang-starknet/test_data/erc20.cairo#L107)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

don't you want to change the allowance only if it is not unlimited ?
</blockquote></details>

right - fixing
___
*[`crates/cairo-lang-starknet/test_data/erc20.cairo` line 108 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1853#-NMUi1wf-U5yUUL835XO:-NMUvKP3127hyXy0FX1t:b-pb9bue) ([raw file](https://github.com/starkware-libs/cairo/blob/da8d62b8c54159583b7f117f90644387d37937a3/crates/cairo-lang-starknet/test_data/erc20.cairo#L108)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I find it a bit strange that you emit an event here, but I guess you've copied it from the original code.
</blockquote></details>

indeed

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/test_data/erc20.cairo` line 107 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1853#-NMTyMZ_54NdI4Bq1lDY:-NMV4GR_B-cdEle_DAlB:b-281mec) ([raw file](https://github.com/starkware-libs/cairo/blob/7c52cc7b53a27b13ab3f57489c483345ee9a96f3/crates/cairo-lang-starknet/test_data/erc20.cairo#L107)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

right - fixing
</blockquote></details>

I misspelled allowance 



_Suggestion:_
```Cairo
allowance
```

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1853#-:-NMV4RaN-FHF75e8KEbE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bbrandtom and @liorgold2)

**Review by ilyalesokhin-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1853)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bbrandtom and @liorgold2)

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1853)* status: 11 of 12 files reviewed, all discussions resolved (waiting on @bbrandtom, @ilyalesokhin-starkware, and @liorgold2)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1853)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bbrandtom and @liorgold2)

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1853)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bbrandtom and @liorgold2)

**Pull request merged**
