### PR TITLE
Adding step counter in casm builder.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:cbd50e21

---

**Stack**:
- #1982
- #1980
- #1979
- #1977
- #1976
- #1973
- #1972
- #1971
- #1966 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1966)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-casm/src/builder.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1966#-NN0cEYGCXc7Uh5meTYx:-NN0cEYGCXc7Uh5meTYy:b-1g6bcr) ([raw file](https://github.com/starkware-libs/cairo/blob/3b23cac0c5e65e4f5c7f3e3af89f72623ee7bd09/crates/cairo-lang-casm/src/builder.rs#L34)):*
> ```XML
>     /// The AP change since the beginging of the run.
>     pub ap_change: usize,
>     /// The number of casm steps since the beginging of the run.
> ```

Begining, also in ap_change above.

**Review by gilbens-starkware — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1966)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by spapinistarkware — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1966#-:-NN1mwMd3H_W67curz4w:bg7igk9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1966#-:-NN1tXEt8u1D4kN1Dzih:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
