### PR TITLE
Updated contribution guidelines.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #3388
- #3387
- #3386
- #3385
- #3373 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3373)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3373)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @orizi)

___
*[`docs/CONTRIBUTING.md` line 65 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3373#-NXnYOdI8gPwzE91cR8p:-NXnYOdI8gPwzE91cR8q:b-80nzd9) ([raw file](https://github.com/starkware-libs/cairo/blob/625120da46ffdff9dc338b61fdedec22779a8e58/docs/CONTRIBUTING.md#L65)):*
> ```Markdown
> 8. [Open a Pull Request](https://github.com/starkware-libs/cairo/compare) to one of the following branches:
>     * [cairo-major-update](https://github.com/starkware-libs/cairo/tree/cairo-major-update) If the change breaks existing high level code.
>     * [sierra-minor-update](https://github.com/starkware-libs/cairo/tree/sierra-minor-update) If the will enable generation of Sierra not compilable by the older version of the Sierra to CASM compiler.
> ```

the what?
Also, lines under 100chars



_Code quote:_
```Markdown
the will 
```

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3373#-:-NXnYSkG4ryIccNkFb5m:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @orizi)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3373)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`docs/CONTRIBUTING.md` line 64 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3373#-NXnguiK20te8FBvpnmo:-NXnguiK20te8FBvpnmp:b24qu9s) ([raw file](https://github.com/starkware-libs/cairo/blob/1369c34dc62fd11b2ed3c08650023d6ba5dcab60/docs/CONTRIBUTING.md#L64)):*
> ```Markdown
> 7. Push to the branch (`git push origin feat/amazing_feature`)
> 8. [Open a Pull Request](https://github.com/starkware-libs/cairo/compare) to one of the following branches:
>     * [cairo-major-update](https://github.com/starkware-libs/cairo/tree/cairo-major-update) If the change breaks existing high level code.
> ```

Lines too long.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3373)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`docs/CONTRIBUTING.md` line 41 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3373#-NXnh87O4lSbnkFvqAiu:-NXnh87O4lSbnkFvqAiv:b-r1dun5) ([raw file](https://github.com/starkware-libs/cairo/blob/1369c34dc62fd11b2ed3c08650023d6ba5dcab60/docs/CONTRIBUTING.md#L41)):*
> ```Markdown
> ## Issues and feature requests
> 
> You've found a bug in the source code, a mistake in the documentation or maybe you'd like a new feature?Take a look at [GitHub Discussions](https://github.com/starkware-libs-cairo/discussions) to see if it's already being discussed.  You can help us by [submitting an issue on GitHub](https://github.com/starkware-libs-cairo/issues). Before you create an issue, make sure to search the issue archive -- your issue may have already been addressed!
> ```

Line too long.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3373)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`docs/CONTRIBUTING.md` line 65 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3373#-NXnYOdI8gPwzE91cR8p:-NXnhRmb4b9S23yzTBYU:b205kga) ([raw file](https://github.com/starkware-libs/cairo/blob/1369c34dc62fd11b2ed3c08650023d6ba5dcab60/docs/CONTRIBUTING.md#L65)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

the what?
Also, lines under 100chars
</blockquote></details>

This sentence is not clear

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3373)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`docs/CONTRIBUTING.md` line 63 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3373#-NXnhhE55konshv6Gf46:-NXnhhE55konshv6Gf47:bjij5eb) ([raw file](https://github.com/starkware-libs/cairo/blob/1369c34dc62fd11b2ed3c08650023d6ba5dcab60/docs/CONTRIBUTING.md#L63)):*
> ```Markdown
> 6. Commit your changes (`git commit -m 'feat: Add amazing_feature'`)
> 7. Push to the branch (`git push origin feat/amazing_feature`)
> 8. [Open a Pull Request](https://github.com/starkware-libs/cairo/compare) to one of the following branches:
> ```

Order by:
* main
*

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3373)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

___
*[`docs/CONTRIBUTING.md` line 41 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3373#-NXnh87O4lSbnkFvqAiu:-NXnkRLDB3jD883HhTv2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1369c34dc62fd11b2ed3c08650023d6ba5dcab60/docs/CONTRIBUTING.md#L41)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Line too long.
</blockquote></details>

Done.
___
*[`docs/CONTRIBUTING.md` line 63 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3373#-NXnhhE55konshv6Gf46:-NXnkSNK7NQ_CfXMZkGs:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1369c34dc62fd11b2ed3c08650023d6ba5dcab60/docs/CONTRIBUTING.md#L63)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Order by:
* main
* 
</blockquote></details>

Done.
___
*[`docs/CONTRIBUTING.md` line 64 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3373#-NXnguiK20te8FBvpnmo:-NXnkS_h8OnGa86f_e_F:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1369c34dc62fd11b2ed3c08650023d6ba5dcab60/docs/CONTRIBUTING.md#L64)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Lines too long.
</blockquote></details>

Done.
___
*[`docs/CONTRIBUTING.md` line 65 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3373#-NXnYOdI8gPwzE91cR8p:-NXnkSza68JnU3BaM_zJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1369c34dc62fd11b2ed3c08650023d6ba5dcab60/docs/CONTRIBUTING.md#L65)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

This sentence is not clear
</blockquote></details>

Done.

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3373#-:-NXnylRW4kinb005AZMW:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
