### PR TITLE
Improved diagnostics for format strings

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4594)

### CODE REVIEW

**Comment by yuvalsw** [comment]
change target branch

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4594)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/inline_macros/write.rs` line 371 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4594#-Nlwhmia3raXaCPb7H78:-Nlwhmia3raXaCPb7H79:b-q0cfw9) ([raw file](https://github.com/starkware-libs/cairo/blob/9c547f56ca9c2885043424b573e4919bcf23c9dc/crates/cairo-lang-semantic/src/inline_macros/write.rs#L371)):*
> ```XML
>     source: ArgumentSource,
>     /// The format type to use.
>     fmt_type: FormattingTrait,
> ```

rename and update doc



_Code quote:_
```XML
    /// The format type to use.
    fmt_type: FormattingTrait,
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4594)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/inline_macros/write.rs` line 371 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4594#-Nlwhmia3raXaCPb7H78:-Nlwrrlg8ZXk2POxYzzo:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9c547f56ca9c2885043424b573e4919bcf23c9dc/crates/cairo-lang-semantic/src/inline_macros/write.rs#L371)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rename and update doc
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4594#-:-NlwzGer5XMnl2cu-68Q:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
