### PR TITLE
Disable support for impl body.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1585)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1585)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`crates/cairo-semantic/src/diagnostic.rs` line 513 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1585#-NKhJrJp8nl2HBt5t2cp:-NKhJrJq8vL8dLkJrxJp:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/87803ce9dcee2337f8e53925b4beaf3407ea17db/crates/cairo-semantic/src/diagnostic.rs#L513)):*
> ```XML
>         actual_ty: semantic::TypeId,
>     },
>     ImplIsBodyNotSupported,
> ```





_Suggestion:_
```XML
 ImplBodyIsNotSupported
```

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1585)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @yuvalsw)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1585)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-semantic/src/diagnostic.rs` line 513 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1585#-NKhJrJp8nl2HBt5t2cp:-NKhNZlYB82zRuvbazo0:b-pas6ot) ([raw file](https://github.com/starkware-libs/cairo/blob/87803ce9dcee2337f8e53925b4beaf3407ea17db/crates/cairo-semantic/src/diagnostic.rs#L513)):*
> ```XML
>         actual_ty: semantic::TypeId,
>     },
>     ImplIsBodyNotSupported,
> ```

Done.
Thanks :)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1585#-:-NKhNwqZ8RRR-PVAxIKL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
