### PR TITLE
Formatter: change flow to aggregate all, then break. 

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1776)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 26 of 28 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1776)* status: all files reviewed, 9 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/formatter.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1776#-NLuf3j92E3kuS9PheOB:-NLuf3j92E3kuS9PheOC:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c014a6b0a35df008bb91521481307a80bd46ab1f/crates/cairo-lang-formatter/src/formatter.rs#L57)):*
> ```XML
>     /// Indicates to put a space instead of the break line point if it were not broken.
>     pub space_if_not_broken: bool,
>     /// Indicates that the break line point is for an empty line in the code.
> ```





_Suggestion:_
```XML
Indicates that the break line point was added instead of an empty line in the code, which means it must be preserved in the output.
```
___
*[`crates/cairo-lang-formatter/src/formatter.rs` line 58 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1776#-NLueN1b0xlZIyRa_gxD:-NLueN1b0xlZIyRa_gxE:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c014a6b0a35df008bb91521481307a80bd46ab1f/crates/cairo-lang-formatter/src/formatter.rs#L58)):*
> ```XML
>     pub space_if_not_broken: bool,
>     /// Indicates that the break line point is for an empty line in the code.
>     pub new_line_bp: bool,
> ```





_Suggestion:_
```XML
empty_line_breakpoint
```
___
*[`crates/cairo-lang-formatter/src/formatter.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1776#-NLufRI01YsS699iprVu:-NLufRI01YsS699iprVv:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c014a6b0a35df008bb91521481307a80bd46ab1f/crates/cairo-lang-formatter/src/formatter.rs#L69)):*
> ```XML
>         Self { precedence, break_indentation, is_optional, space_if_not_broken, new_line_bp: false }
>     }
>     pub fn new_newline_properties() -> Self {
> ```





_Suggestion:_
```XML
new_emptyline
```
___
*[`crates/cairo-lang-formatter/src/formatter.rs` line 209 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1776#-NLuiDKv1QtGAffOG2QN:-NLuiDKv1QtGAffOG2QO:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c014a6b0a35df008bb91521481307a80bd46ab1f/crates/cairo-lang-formatter/src/formatter.rs#L209)):*
> ```XML
>     }
>     /// Appends an allowed user newline to the line.
>     pub fn push_newline_break_line_point(&mut self) {
> ```





_Suggestion:_
```XML
    /// Appends a user-inserted empty line to the line.
    pub fn push_empty_line_break_line_point(&mut self) {
```
___
*[`crates/cairo-lang-formatter/src/formatter.rs` line 513 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1776#-NLuivF_-WMCsX3bYCnu:-NLuivF_-WMCsX3bYCnv:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c014a6b0a35df008bb91521481307a80bd46ab1f/crates/cairo-lang-formatter/src/formatter.rs#L513)):*
> ```XML
>     empty_lines_allowance: usize,
>     /// Indicates if there were non-whitespace tokens since the last newline.
>     is_current_line_empty: bool,
> ```





_Suggestion:_
```XML
    /// Indicates whether the current line only consists of whitespae tokens (since the last newline).
    is_current_line_whitespaces: bool,
```
___
*[`crates/cairo-lang-formatter/src/formatter.rs` line 610 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1776#-NLulOmACTsZC8qvzKpM:-NLulOmB4jvVCZSdNJ1o:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c014a6b0a35df008bb91521481307a80bd46ab1f/crates/cairo-lang-formatter/src/formatter.rs#L610)):*
> ```XML
>         }
>     }
>     /// Formats a token node and it to the result.
> ```





_Suggestion:_
```XML
    /// Formats a token node and appends it to the result.
    /// Assumes the given SyntaxNode is a token.
```
___
*[`crates/cairo-lang-formatter/src/formatter.rs` line 617 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1776#-NLukyZa-qtXFA1s83ym:-NLukyZa-qtXFA1s83yn:bliwj3o) ([raw file](https://github.com/starkware-libs/cairo/blob/c014a6b0a35df008bb91521481307a80bd46ab1f/crates/cairo-lang-formatter/src/formatter.rs#L617)):*
> ```XML
>     }
>     /// Appends a token node to the result.
>     fn append_token(&mut self, text: SmolStr, syntax_node: &SyntaxNode, no_space_after: bool) {
> ```

Please inline this into format_token.
1. It is only used there.
2. This function appends text, not a token.
3. With the token in format_token, you could check the token kind to know if it is only whitespaces or not (this is a separate token kind).
___
*[`crates/cairo-lang-formatter/src/formatter.rs` line 635 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1776#-NLul_oH0-NZliLRpRVm:-NLul_oH0-NZliLRpRVn:b776zu1) ([raw file](https://github.com/starkware-libs/cairo/blob/c014a6b0a35df008bb91521481307a80bd46ab1f/crates/cairo-lang-formatter/src/formatter.rs#L635)):*
> ```XML
> }
> 
> fn is_only_whitespaces(s: &str) -> bool {
> ```

see previous comment, I think this isn't needed.



_Code quote:_
```XML
fn is_only_whitespaces(s: &str) -> bool {
    s.trim().is_empty()
```
___
*[`crates/cairo-lang-formatter/src/node_properties.rs` line 162 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1776#-NLumIyC-pJmCLla1_hk:-NLumIyC-pJmCLla1_hl:b-vsp2x) ([raw file](https://github.com/starkware-libs/cairo/blob/c014a6b0a35df008bb91521481307a80bd46ab1f/crates/cairo-lang-formatter/src/node_properties.rs#L162)):*
> ```XML
>         }
>     }
>     fn get_wrapping_break_line_point_properties(
> ```

Let's discuss the large numbers in the precedences.

**Review by yuvalsw — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1776)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/formatter.rs` line 215 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1776#-NLvFJIy4F2gvCcqbFze:-NLvFJIz6Fmc9aEBaY1S:b-4sqojk) ([raw file](https://github.com/starkware-libs/cairo/blob/7420ceae96100b212eb81e2e819efe9fb48c0873/crates/cairo-lang-formatter/src/formatter.rs#L215)):*
> ```XML
>     }
>     /// Appends a user-inserted empty line to the line.
>     pub fn push_empty_line_break_line_point(&mut self) {
> ```

try to be consistent - either emptyline is a single word (in all occurrences) or 2 words (empty_line).



_Code quote:_
```XML
empty_line
```
___
*[`crates/cairo-lang-formatter/src/formatter.rs` line 516 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1776#-NLvFX_kA1c3jYOxxfVr:-NLvFX_kA1c3jYOxxfVs:bb7phvt) ([raw file](https://github.com/starkware-libs/cairo/blob/7420ceae96100b212eb81e2e819efe9fb48c0873/crates/cairo-lang-formatter/src/formatter.rs#L516)):*
> ```XML
>     /// The number of empty lines allowed after the current node.
>     empty_lines_allowance: usize,
>     /// Indicates whether the current line only consists of whitespae tokens (since the last newline).
> ```

typo



_Code quote:_
```XML
whitespae
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1776)* status: all files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1776#-NM33I8w5xVi_NEd5DaV:-NM33I8xEB4uUN2VtrCQ:b-ouoqi) (no related file):*
Change target branch

___
___
*[`crates/cairo-lang-formatter/src/formatter.rs` line 617 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1776#-NLukyZa-qtXFA1s83ym:-NLuqT1E7D3S892K9-Sz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c014a6b0a35df008bb91521481307a80bd46ab1f/crates/cairo-lang-formatter/src/formatter.rs#L617)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Please inline this into format_token.
1. It is only used there.
2. This function appends text, not a token.
3. With the token in format_token, you could check the token kind to know if it is only whitespaces or not (this is a separate token kind).
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/formatter.rs` line 635 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1776#-NLul_oH0-NZliLRpRVm:-NLuqSpbA0hkh8212KVr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c014a6b0a35df008bb91521481307a80bd46ab1f/crates/cairo-lang-formatter/src/formatter.rs#L635)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

see previous comment, I think this isn't needed.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/formatter.rs` line 215 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1776#-NLvFJIy4F2gvCcqbFze:-NM34O-O3J1u1dvF8dqZ:bfq7988) ([raw file](https://github.com/starkware-libs/cairo/blob/7420ceae96100b212eb81e2e819efe9fb48c0873/crates/cairo-lang-formatter/src/formatter.rs#L215)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

try to be consistent - either emptyline is a single word (in all occurrences) or 2 words (empty_line).
</blockquote></details>

All is empty_line afaik.
___
*[`crates/cairo-lang-formatter/src/formatter.rs` line 622 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1776#-NLvIbyk5ZYhCBpKBvxw:-NM34oFfB3-mMQGB_pk0:b-dik2xu) ([raw file](https://github.com/starkware-libs/cairo/blob/6b7b6d0812048106d34b7941e27a7ed64063b306/crates/cairo-lang-formatter/src/formatter.rs#L622)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

use ::Max - 1.
</blockquote></details>

why -1?
___
*[`crates/cairo-lang-formatter/src/node_properties.rs` line 162 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1776#-NLumIyC-pJmCLla1_hk:-NM34s7VBi-JsBblxFzz:bljyaqb) ([raw file](https://github.com/starkware-libs/cairo/blob/c014a6b0a35df008bb91521481307a80bd46ab1f/crates/cairo-lang-formatter/src/node_properties.rs#L162)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Let's discuss the large numbers in the precedences.
</blockquote></details>

I'll change it together with the wrapping.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1776#-:-NM8zrQG-WryPyZBGFmN:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/formatter.rs` line 50 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1776#-NLvHc6V9x951Pn1hAX8:-NM8zLxn7nC0wtFn_jjO:bh4108t) ([raw file](https://github.com/starkware-libs/cairo/blob/6b7b6d0812048106d34b7941e27a7ed64063b306/crates/cairo-lang-formatter/src/formatter.rs#L50)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

actually it doesn't have to be preserved (there is the new lines allowance). Please adjust to "should" and explain when it's not preserved.
</blockquote></details>

and explain when it's not preserved.
___
*[`crates/cairo-lang-formatter/src/formatter.rs` line 65 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1776#-NM8zVCpBjPOFGGBh0HV:-NM8zVCpBjPOFGGBh0HW:bq0bcqp) ([raw file](https://github.com/starkware-libs/cairo/blob/93121eec3b561150d36135063986c7f9b9044a22/crates/cairo-lang-formatter/src/formatter.rs#L65)):*
> ```XML
>     fn cmp(&self, other: &Self) -> Ordering {
>         match (self.is_empty_line_breakpoint, other.is_empty_line_breakpoint) {
>             (true, true) | (false, false) => self.precedence.cmp(&other.precedence),
> ```

nit: I think you could do (x, x) instead.



_Code quote:_
```XML
(true, true) | (false, false) 
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1776)* status: 27 of 28 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-formatter/src/formatter.rs` line 65 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1776#-NM8zVCpBjPOFGGBh0HV:-NM906gH41veUrW6FR4Q:b-924dq0) ([raw file](https://github.com/starkware-libs/cairo/blob/93121eec3b561150d36135063986c7f9b9044a22/crates/cairo-lang-formatter/src/formatter.rs#L65)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

nit: I think you could do (x, x) instead.
</blockquote></details>

(x, x) does not work (unless there is a trick I don't know), I can do (_, _) if it is last but I prefer the explicit version.

**Review by orizi — APPROVED** [review]
> Reviewed 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1776)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
> Reviewed 29 of 29 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1776)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 2 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1776)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
