### PR TITLE
Minor refactoring of starknet cairo level tests.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #4019
- #4013
- #3993 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3993)

### CODE REVIEW

**Review by yuvalsw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3993)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3993)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo` line 111 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3993#-Nd__VWe04y0gSICibGb:-Nd_cECU0TWr1uloMCCK:b2ni1bp) ([raw file](https://github.com/starkware-libs/cairo/blob/0bc2762901639d0386d7b9db2edfeb187d694aa5/crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo#L111)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

where is the 1 gone?
</blockquote></details>

f2f

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3993)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo` line 88 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3993#-Nd_xgAv0a4Da6J7eDwQ:-Nd_xgAwC9z7WrbXXXYu:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e94fd47690f45aff84a06f41a4595123dc9073d0/crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo#L88)):*
> ```Cairo
> #[test]
> #[should_panic]
> fn test_wrapper_too_many_enough_args() {
> ```





_Suggestion:_
```Cairo
test_wrapper_too_many_args() {
```
___
*[`crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo` line 89 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3993#-Nd_xlGm3IO1crafVnJI:-Nd_xlGm3IO1crafVnJJ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e94fd47690f45aff84a06f41a4595123dc9073d0/crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo#L89)):*
> ```Cairo
> #[should_panic]
> fn test_wrapper_too_many_enough_args() {
>     test_contract::__external::get_plus_2(serialized((1, 2)));
> ```





_Suggestion:_
```Cairo
xternal::get_plus_2(serialized(array![2]));
```
___
*[`crates/cairo-lang-starknet/cairo_level_tests/contract_with_ownable.cairo` line 0 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3993#-Ndeyvib-yAau1gqCUiq:-Ndeyvib-yAau1gqCUir:be9542g) ([raw file](https://github.com/starkware-libs/cairo/blob/6096054276aa2ce6e490308ac353061581a263a8/crates/cairo-lang-starknet/cairo_level_tests/contract_with_ownable.cairo#L0)):*
Is this file related to this pr?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3993)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/contract_with_ownable.cairo` line  at r3](https://reviewable.io/reviews/starkware-libs/cairo/3993#-Ndeyvib-yAau1gqCUiq:-Ndf30Dk2UtzvBbah81U:b-8a1wef) ([raw file](https://github.com/starkware-libs/cairo/blob/d2d85fb9faf04e2a96a8fc6ee9824d1be50c49a5/crates/cairo-lang-starknet/cairo_level_tests/contract_with_ownable.cairo#L)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Is this file related to this pr?
</blockquote></details>

buhhh - added by accident again.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3993#-:-NdfJMS12T1H6qMPF7CO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo` line 89 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3993#-Nd_xlGm3IO1crafVnJI:-NdfJG36DBb25sxGqgPa:bocb2l1) ([raw file](https://github.com/starkware-libs/cairo/blob/e94fd47690f45aff84a06f41a4595123dc9073d0/crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo#L89)):*
> ```Cairo
> #[should_panic]
> fn test_wrapper_too_many_enough_args() {
>     test_contract::__external::get_plus_2(serialized((1, 2)));
> ```

I don't see this change.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3993)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo` line 89 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3993#-Nd_xlGm3IO1crafVnJI:-NdiPH4m3oOLSgzx02iG:bfeefdd) ([raw file](https://github.com/starkware-libs/cairo/blob/e94fd47690f45aff84a06f41a4595123dc9073d0/crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo#L89)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I don't see this change.
</blockquote></details>

i just input too many args - no reason for this to be an array.

**Pull request merged**
