### PR TITLE
added tail struct for struct constructions

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4923)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4923)* status: 3 of 8 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 2362 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4923#-Np-dTc6-aSxbb_yXRgX:-Np-dTc6-aSxbb_yXRgY:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/a242043678fb79bcbe9c7d3394fe3fe065678d9b/crates/cairo-lang-lowering/src/lower/mod.rs#L2362)):*
> ```XML
> 
>     if let Some(member_path) = &expr.member_path {
>         // assert!(expr.n_snapshots == 0, "Member access should not have snapshots.");
> ```

?
___
*[`crates/cairo-lang-lowering/src/test_data/struct` line 16 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4923#-Np-dHw_7s__FM81qejS:-Np-dHw_7s__FM81qejT:b-l6hdjr) ([raw file](https://github.com/starkware-libs/cairo/blob/a242043678fb79bcbe9c7d3394fe3fe065678d9b/crates/cairo-lang-lowering/src/test_data/struct#L16)):*
> ```
> //! > module_code
> struct MyStruct {
>     a: (),
> ```

revert
___
*[`crates/cairo-lang-lowering/src/test_data/struct` line 129 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4923#-Np-dzq08UGMGd8i8aJ4:-Np-dzq08UGMGd8i8aJ5:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a242043678fb79bcbe9c7d3394fe3fe065678d9b/crates/cairo-lang-lowering/src/test_data/struct#L129)):*
> ```
>     b: felt252,
>     c: (felt252, felt252),
> }
> ```





_Suggestion:_
```
//! > function
fn foo(s: MyStruct) -> MyStruct {
  MyStruct { a: (), .. MyStruct { c: (1, 2), .. MyStruct { b: 9, .. s } } }
}

//! > function_name
foo

//! > module_code
#[derive(Copy)]
struct MyStruct {
  a: (),
  b: felt252,
  c: (felt252, felt252),
}
```
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1662 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4923#-Np-jO2SAbfi_RK6__QW:-Np-jO2SAbfi_RK6__QX:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a242043678fb79bcbe9c7d3394fe3fe065678d9b/crates/cairo-lang-semantic/src/expr/compute.rs#L1662)):*
> ```XML
>             }
>             ast::StructArg::StructArgTail(tail_expr_syntax) => {
>                 // Todo(TomerStarkware): remove tail expression from argument list.
> ```





_Suggestion:_
```XML
                // TODO(TomerStarkware): remove tail expression from argument list.
```
___
*[`crates/cairo-lang-semantic/src/expr/objects.rs` line 447 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4923#-Np-j_kkBETl1JCvdZLn:-Np-j_kkBETl1JCvdZLo:b-cikxla) ([raw file](https://github.com/starkware-libs/cairo/blob/a242043678fb79bcbe9c7d3394fe3fe065678d9b/crates/cairo-lang-semantic/src/expr/objects.rs#L447)):*
> ```XML
>     pub concrete_struct_id: ConcreteStructId,
>     pub members: Vec<(MemberId, ExprId)>,
>     pub tail_struct: Option<ExprId>,
> ```

is that the name of the concept in rust?

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4923)* status: 1 of 9 files reviewed, 11 unresolved discussions (waiting on @orizi and @TomerStarkware)

___
*[`crates/cairo-lang-formatter/src/node_properties.rs` line 100 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4923#-Np0DPEi7QFNlM0kF9kl:-Np0DPEi7QFNlM0kF9km:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/d3c13e6f7b841fc570475c58e15cf8d47f67d9ae/crates/cairo-lang-formatter/src/node_properties.rs#L100)):*
> ```XML
>                 true
>             }
> ```

remove
___
*[`crates/cairo-lang-formatter/src/node_properties.rs` line 146 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4923#-Np0DX4ECnOMSx4AZvCD:-Np0DX4ECnOMSx4AZvCE:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d3c13e6f7b841fc570475c58e15cf8d47f67d9ae/crates/cairo-lang-formatter/src/node_properties.rs#L146)):*
> ```XML
>             }
> 
>             _ => false,
> ```





_Suggestion:_
```XML
            SyntaxKind::TokenDotDot
                if grandparent_kind(db, self) == Some(SyntaxKind::StructArgTail) =>
            {
                true
            }
            _ => false,
```
___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 676 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4923#-Np0P43VAUxqnC8fROeE:-Np0P43VAUxqnC8fROeF:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/af3b53c7087b2ce56d197a737ada39a774120dcc/crates/cairo-lang-semantic/src/diagnostic.rs#L676)):*
> ```XML
>                                                                      all the fields in the struct \
>                                                                      have already been specified."
>                 .into(),
> ```





_Suggestion:_
```XML
            SemanticDiagnosticKind::StructTailExpressionNoEffect => {
                "Struct update has no effect, all the fields in the struct have already been specified."
                .into(),
        }
```
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1708 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4923#-Np0Ojgf7Uts3LVRqbY7:-Np0Ojgf7Uts3LVRqbY8:bc5itba) ([raw file](https://github.com/starkware-libs/cairo/blob/af3b53c7087b2ce56d197a737ada39a774120dcc/crates/cairo-lang-semantic/src/expr/compute.rs#L1708)):*
> ```XML
>     if members.len() == member_exprs.len() {
>         if let Some((_, base_struct_syntax)) = base_struct {
>             return Err(ctx.diagnostics.report(&base_struct_syntax, StructTailExpressionNoEffect));
> ```

Consider changing to warning.



_Code quote:_
```XML
return Err(ctx.diagnostics.report(&base_struct_syntax, StructTailExpressionNoEffect));
```
___
*[`crates/cairo-lang-semantic/src/expr/test_data/structure` line 7 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4923#-Np0G5yk-aGbkUHxkZ7_:-Np0G5yk-aGbkUHxkZ7a:b-qiwxfh) ([raw file](https://github.com/starkware-libs/cairo/blob/d3c13e6f7b841fc570475c58e15cf8d47f67d9ae/crates/cairo-lang-semantic/src/expr/test_data/structure#L7)):*
> ```
> 
> //! > function
> #[cairofmt::skip]
> ```

Why skip?



_Code quote:_
```
#[cairofmt::skip]
```
___
*[`crates/cairo-lang-semantic/src/expr/test_data/structure` line 129 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4923#-Np0GT6M5rNgKj_FTq3h:-Np0GT6M5rNgKj_FTq3i:bqmxvqk) ([raw file](https://github.com/starkware-libs/cairo/blob/d3c13e6f7b841fc570475c58e15cf8d47f67d9ae/crates/cairo-lang-semantic/src/expr/test_data/structure#L129)):*
> ```
>  --> lib.cairo:5:15
>     A { a: 4, ..a }
>               ^*^
> ```

Change ` Struct update` to reflect the name you'll chose in the code.



_Code quote:_
```
//! > expected_diagnostics
error: Struct update has no effect, all the fields in the struct have already been specified.
 --> lib.cairo:5:15
    A { a: 4, ..a }
              ^*^
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4923)* status: 3 of 9 files reviewed, 9 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 2396 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4923#-Np0LnoC8A92-Z_96sMe:-Np0LnoC8A92-Z_96sMf:b1fwpfm) ([raw file](https://github.com/starkware-libs/cairo/blob/c3c54e9648b6b84f995f30843ddba662bd024410/crates/cairo-lang-lowering/src/lower/mod.rs#L2396)):*
> ```XML
>             (*member_id, lower_expr_to_var_usage(ctx, builder, *expr_id))
>         }));
>     if members.len() != members_vars_usages.len() {
> ```

add comment about the handling.
___
*[`crates/cairo-lang-semantic/src/expr/objects.rs` line 447 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4923#-Np0POV47s58__cjl7yZ:-Np0POV47s58__cjl7y_:b-ackre0) ([raw file](https://github.com/starkware-libs/cairo/blob/c3c54e9648b6b84f995f30843ddba662bd024410/crates/cairo-lang-semantic/src/expr/objects.rs#L447)):*
> ```XML
>     pub concrete_struct_id: ConcreteStructId,
>     pub members: Vec<(MemberId, ExprId)>,
>     pub tail_struct: Option<ExprId>,
> ```

specifically - it being a struct is wholly uninteresting.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r4, 1 of 2 files at r5, 2 of 3 files at r6, 1 of 1 files at r7, 1 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4923)* status: 7 of 9 files reviewed, 8 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1708 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4923#-Np0Ojgf7Uts3LVRqbY7:-Np0kunN2Q1dZl0Y2AhI:b-qxrn28) ([raw file](https://github.com/starkware-libs/cairo/blob/af3b53c7087b2ce56d197a737ada39a774120dcc/crates/cairo-lang-semantic/src/expr/compute.rs#L1708)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Consider changing to warning.
</blockquote></details>

hmm - yeah - sounds sensible to me as well.
___
*[`crates/cairo-lang-semantic/src/expr/objects.rs` line 447 at r8](https://reviewable.io/reviews/starkware-libs/cairo/4923#-Np0l8YbBdekSGYEJ7_P:-Np0l8Yc0XExyVxcQeSO:b58yxsp) ([raw file](https://github.com/starkware-libs/cairo/blob/9462c55f24ac4b627d969303946bb9ff63a97c43/crates/cairo-lang-semantic/src/expr/objects.rs#L447)):*
> ```XML
>     pub concrete_struct_id: ConcreteStructId,
>     pub members: Vec<(MemberId, ExprId)>,
>     pub base_struct: Option<ExprId>,
> ```

doc what it is here as well - guesses arent clear.
___
*[`tests/test_data/fib_struct.sierra` line 30 at r8](https://reviewable.io/reviews/starkware-libs/cairo/4923#-Np0lKWC5FRp8UJ9X7x2:-Np0lKWC5FRp8UJ9X7x3:b-vfpjkj) ([raw file](https://github.com/starkware-libs/cairo/blob/9462c55f24ac4b627d969303946bb9ff63a97c43/tests/test_data/fib_struct.sierra#L30)):*
> ```
> drop<felt252>([1]) -> (); // 4
> drop<felt252>([2]) -> (); // 5
> struct_construct<Unit>() -> ([5]); // 6
> ```

why are there changes here?

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4923)* status: 7 of 9 files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-formatter/src/node_properties.rs` line 100 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4923#-Np0DPEi7QFNlM0kF9kl:-Np0SQx25Poh1FcN8jJb:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/d3c13e6f7b841fc570475c58e15cf8d47f67d9ae/crates/cairo-lang-formatter/src/node_properties.rs#L100)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 2362 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4923#-Np-dTc6-aSxbb_yXRgX:-Np02J0IC2q7rxFTb-5P:b-hfpv0l) ([raw file](https://github.com/starkware-libs/cairo/blob/a242043678fb79bcbe9c7d3394fe3fe065678d9b/crates/cairo-lang-lowering/src/lower/mod.rs#L2362)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

removed
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 2396 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4923#-Np0LnoC8A92-Z_96sMe:-NpBJWU230JwgGizAwEK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c3c54e9648b6b84f995f30843ddba662bd024410/crates/cairo-lang-lowering/src/lower/mod.rs#L2396)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add comment about the handling.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/test_data/struct` line 16 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4923#-Np-dHw_7s__FM81qejS:-Np0Bu1S2lV8AUUUQUe9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a242043678fb79bcbe9c7d3394fe3fe065678d9b/crates/cairo-lang-lowering/src/test_data/struct#L16)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

revert
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/test_data/struct` line 129 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4923#-Np-dzq08UGMGd8i8aJ4:-Np0C-Hq5ZaddNgH46RO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a242043678fb79bcbe9c7d3394fe3fe065678d9b/crates/cairo-lang-lowering/src/test_data/struct#L129)):*
> ```
>     b: felt252,
>     c: (felt252, felt252),
> }
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1662 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4923#-Np-jO2SAbfi_RK6__QW:-Np0C9mW4053VS_awkyF:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a242043678fb79bcbe9c7d3394fe3fe065678d9b/crates/cairo-lang-semantic/src/expr/compute.rs#L1662)):*
> ```XML
>             }
>             ast::StructArg::StructArgTail(tail_expr_syntax) => {
>                 // Todo(TomerStarkware): remove tail expression from argument list.
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1708 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4923#-Np0Ojgf7Uts3LVRqbY7:-NpBK84O0VfkAa4efmUG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/af3b53c7087b2ce56d197a737ada39a774120dcc/crates/cairo-lang-semantic/src/expr/compute.rs#L1708)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

hmm - yeah - sounds sensible to me as well.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/objects.rs` line 447 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4923#-Np-j_kkBETl1JCvdZLn:-Np0CJpREObukvhYaD65:bt5df6n) ([raw file](https://github.com/starkware-libs/cairo/blob/a242043678fb79bcbe9c7d3394fe3fe065678d9b/crates/cairo-lang-semantic/src/expr/objects.rs#L447)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is that the name of the concept in rust?
</blockquote></details>

It was called tail struct in our parser, 
___
*[`crates/cairo-lang-semantic/src/expr/objects.rs` line 447 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4923#-Np0POV47s58__cjl7yZ:-Np0QsxZBNOB5YhkfW7Y:bowvx1r) ([raw file](https://github.com/starkware-libs/cairo/blob/c3c54e9648b6b84f995f30843ddba662bd024410/crates/cairo-lang-semantic/src/expr/objects.rs#L447)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

specifically - it being a struct is wholly uninteresting.
</blockquote></details>

changed to base_struct
___
*[`crates/cairo-lang-semantic/src/expr/test_data/structure` line 7 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4923#-Np0G5yk-aGbkUHxkZ7_:-Np0RPka18sElnRJW-Or:b-veqh2q) ([raw file](https://github.com/starkware-libs/cairo/blob/d3c13e6f7b841fc570475c58e15cf8d47f67d9ae/crates/cairo-lang-semantic/src/expr/test_data/structure#L7)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Why skip?
</blockquote></details>

so the struct won't fold to one line
___
*[`crates/cairo-lang-semantic/src/expr/test_data/structure` line 129 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4923#-Np0GT6M5rNgKj_FTq3h:-NpBKPBF5ybPR2IOJZgL:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d3c13e6f7b841fc570475c58e15cf8d47f67d9ae/crates/cairo-lang-semantic/src/expr/test_data/structure#L129)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Change ` Struct update` to reflect the name you'll chose in the code.
</blockquote></details>

Done.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4923)* status: 2 of 9 files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/objects.rs` line 447 at r8](https://reviewable.io/reviews/starkware-libs/cairo/4923#-Np0l8YbBdekSGYEJ7_P:-NpBMOQJCsdu8L7Ivv9-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9462c55f24ac4b627d969303946bb9ff63a97c43/crates/cairo-lang-semantic/src/expr/objects.rs#L447)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc what it is here as well - guesses arent clear.
</blockquote></details>

Done.
___
*[`tests/test_data/fib_struct.sierra` line 30 at r8](https://reviewable.io/reviews/starkware-libs/cairo/4923#-Np0lKWC5FRp8UJ9X7x2:-NpBWvBrALYGLk4EbBCk:by43kuw) ([raw file](https://github.com/starkware-libs/cairo/blob/9462c55f24ac4b627d969303946bb9ff63a97c43/tests/test_data/fib_struct.sierra#L30)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why are there changes here?
</blockquote></details>

changed back

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4923)* status: all files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 671 at r9](https://reviewable.io/reviews/starkware-libs/cairo/4923#-NpBYhhVC2UDQ5LihfIg:-NpBYhhVC2UDQ5LihfIh:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2bb82d0caf22b5852035c40bfc7d45874ee66d87/crates/cairo-lang-semantic/src/diagnostic.rs#L671)):*
> ```XML
>             }
>             SemanticDiagnosticKind::StructBaseStructExpressionNotLast => {
>                 "The base struct must always be the last field.".into()
> ```





_Suggestion:_
```XML
                "The base struct must always be the last argument.".into()
```
___
*[`crates/cairo-lang-semantic/src/expr/objects.rs` line 448 at r9](https://reviewable.io/reviews/starkware-libs/cairo/4923#-NpBZ-Ni2F0ruA35_p2r:-NpBZ-Ni2F0ruA35_p2s:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2bb82d0caf22b5852035c40bfc7d45874ee66d87/crates/cairo-lang-semantic/src/expr/objects.rs#L448)):*
> ```XML
>     pub members: Vec<(MemberId, ExprId)>,
>     // An optional base struct to copy missing members from in the struct construction.
>     // For example `let x = MyStruct { a: 1, ..base }`.
> ```





_Suggestion:_
```XML
    /// The base struct to copy missing members from if provided.
    /// For example `let x = MyStruct { a: 1, ..base }`.
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4923)* status: all files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 671 at r9](https://reviewable.io/reviews/starkware-libs/cairo/4923#-NpBYhhVC2UDQ5LihfIg:-NpBhPjO1zIqwVZM2QZr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2bb82d0caf22b5852035c40bfc7d45874ee66d87/crates/cairo-lang-semantic/src/diagnostic.rs#L671)):*
> ```XML
>             }
>             SemanticDiagnosticKind::StructBaseStructExpressionNotLast => {
>                 "The base struct must always be the last field.".into()
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/objects.rs` line 448 at r9](https://reviewable.io/reviews/starkware-libs/cairo/4923#-NpBZ-Ni2F0ruA35_p2r:-NpBha-m4yOAw-WrG470:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2bb82d0caf22b5852035c40bfc7d45874ee66d87/crates/cairo-lang-semantic/src/expr/objects.rs#L448)):*
> ```XML
>     pub members: Vec<(MemberId, ExprId)>,
>     // An optional base struct to copy missing members from in the struct construction.
>     // For example `let x = MyStruct { a: 1, ..base }`.
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4923#-:-NpDKCjZ5XdCf-cg1D6o:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 1 of 1 files at r7, 1 of 2 files at r8, 4 of 7 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4923#-:-NpE1FwV1AqjEgdjfUgg:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

**Pull request merged**
