### PR TITLE
feat(corelib): add boolean operators to Result type

### PR DESCRIPTION
**Pull request by cairolover**
Adds `and`, `and_then`, `or`, `or_else`, `unwrap_or_else` to ResultTrait along with tests.

note: the module documentation is taken from Rust's. the item-level doc was adapted to Cairo.

### CODE REVIEW

**Review by cairolover — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6921)* status: 0 of 2 files reviewed, 1 unresolved discussion

___
*[`corelib/src/result.cairo` line 371 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6921#-OEtfbpJ45_0sybntkpi:-OEtfbpJ45_0sybntkpj:b8gkun8) ([raw file](https://github.com/starkware-libs/cairo/blob/16a2805299926b435a90aefa47f205a1dc6c1395/corelib/src/result.cairo#L371)):*
> ```Cairo
>     /// assert!(x.or(y) == Result::Ok(2));
>     /// ```
>     //TODO: why can't I restrict E and U to implement Destruct rather than Drop?
> ```

Same comment for `and`: I'm not sure why this can't be `+Destruct<T>, +Destruct<F>, +Destruct<E>` rather than `+Drop<T>, +Drop<F>, +Destruct<E>`

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6921)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @cairolover)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6921#-OEwBC3U2T5GDuxsNIMd:-OEwBC3U2T5GDuxsNIMe:b-i3xkiz) (no related file):*
2nd eye @TomerStarkware 
___
*[`corelib/src/result.cairo` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6921#-OEwAOuiCrXsda_JpGnX:-OEwAOuiCrXsda_JpGnY:b-di8l4l) ([raw file](https://github.com/starkware-libs/cairo/blob/16a2805299926b435a90aefa47f205a1dc6c1395/corelib/src/result.cairo#L84)):*
> ```Cairo
> //! [`Ok`]: Result::Ok
> //! [`Err`]: Result::Err
> //!
> ```

don't move the comment block.
___
*[`corelib/src/result.cairo` line 317 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6921#-OEwAaPz-QphE370HgEv:-OEwAaPz-QphE370HgEw:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/16a2805299926b435a90aefa47f205a1dc6c1395/corelib/src/result.cairo#L317)):*
> ```Cairo
>             Result::Err(e) => Result::Err(e),
>         }
>     }
> ```





_Suggestion:_
```Cairo
    #[inline]
    fn and<U, +Destruct<T>, +Drop<E>, +Drop<U>>(
        self: Result<T, E>, other: Result<U, E>,
    ) -> Result<U, E> {
        match self {
            Result::Ok(_) => other,
            Result::Err(e) => Result::Err(e),
        }
    }
```
___
*[`corelib/src/result.cairo` line 380 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6921#-OEwAEyj-KwmxKr0ILJj:-OEwAEyj-KwmxKr0ILJk:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/16a2805299926b435a90aefa47f205a1dc6c1395/corelib/src/result.cairo#L380)):*
> ```Cairo
>             Result::Err(_) => res,
>         }
>     }
> ```





_Suggestion:_
```Cairo
    #[inline]
    fn or<F, +Drop<T>, +Drop<F>, +Destruct<E>>(
        self: Result<T, E>, other: Result<T, F>,
    ) -> Result<T, F> {
        match self {
            Result::Ok(v) => Result::Ok(v),
            Result::Err(_) => other,
        }
    }
```

**Review by TomerStarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6921#-:-OExsPuH69gqYRsscQNI:bnfp4nl)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @cairolover and @orizi)

**Review by cairolover — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6921)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/result.cairo` line 371 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6921#-OEtfbpJ45_0sybntkpi:-OEyYR6v89dFfEcEQicN:b-4b66d3) ([raw file](https://github.com/starkware-libs/cairo/blob/16a2805299926b435a90aefa47f205a1dc6c1395/corelib/src/result.cairo#L371)):*
<details><summary><i>Previously, cairolover (cairolover) wrote…</i></summary><blockquote>

Same comment for `and`: I'm not sure why this can't be `+Destruct<T>, +Destruct<F>, +Destruct<E>` rather than `+Drop<T>, +Drop<F>, +Destruct<E>`
</blockquote></details>

still unsure about that; but if it's fine for you, then I removed the comment.
___
*[`corelib/src/result.cairo` line 317 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6921#-OEwAaPz-QphE370HgEv:-OEyYB26Bqfe_xFKhoCs:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/16a2805299926b435a90aefa47f205a1dc6c1395/corelib/src/result.cairo#L317)):*
> ```Cairo
>             Result::Err(e) => Result::Err(e),
>         }
>     }
> ```

Done.
___
*[`corelib/src/result.cairo` line 380 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6921#-OEwAEyj-KwmxKr0ILJj:-OEyYQ1r0jH1IN20m6Zj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/16a2805299926b435a90aefa47f205a1dc6c1395/corelib/src/result.cairo#L380)):*
> ```Cairo
>             Result::Err(_) => res,
>         }
>     }
> ```

Done.

**Review by cairolover — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6921)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/result.cairo` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6921#-OEwAOuiCrXsda_JpGnX:-OEyYnyO0sI8pDXNDbhS:b-nqoun5) ([raw file](https://github.com/starkware-libs/cairo/blob/16a2805299926b435a90aefa47f205a1dc6c1395/corelib/src/result.cairo#L84)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

don't move the comment block.
</blockquote></details>

Method overview should come after imo. otherwise the `?` operator description is burried under the methods description

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6921)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @cairolover)

___
*[`corelib/src/result.cairo` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6921#-OEwAOuiCrXsda_JpGnX:-OEyzhS2612TmGAnfMMj:b-pogjwj) ([raw file](https://github.com/starkware-libs/cairo/blob/16a2805299926b435a90aefa47f205a1dc6c1395/corelib/src/result.cairo#L84)):*
<details><summary><i>Previously, cairolover (cairolover) wrote…</i></summary><blockquote>

Method overview should come after imo. otherwise the `?` operator description is burried under the methods description
</blockquote></details>

maybe - but this is completely unrelated to the PR.

**Review by cairolover — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6921)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/result.cairo` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6921#-OEwAOuiCrXsda_JpGnX:-OEz03qy86vm6poemLvQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/16a2805299926b435a90aefa47f205a1dc6c1395/corelib/src/result.cairo#L84)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe - but this is completely unrelated to the PR.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6921)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @cairolover)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6921#-OEz4bbxDd350LCeXTV2:-OEz4bbxDd350LCeXTV3:b-clj6ma) (no related file):*
@enitrat for doc 2nd eye.

**Review by enitrat — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6921#-:-OEzn_1X1hvHSbkd7Gi_:bnfp4nl)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @cairolover and @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6921)* status: all files reviewed, 5 unresolved discussions (waiting on @cairolover)

___
*[`corelib/src/result.cairo` line 277 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6921#-OF0rDFD2vfBPczAW4-d:-OF0rDFD2vfBPczAW4-e:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/33870fb290bf8328593a1cd0735d1845dd01492c/corelib/src/result.cairo#L277)):*
> ```Cairo
>         +Destruct<E>,
>         +Drop<F>,
>         impl func: core::ops::FnOnce<F, (E,)>[Output: T],
> ```





_Suggestion:_
```Cairo
        +core::ops::FnOnce<F, (E,)>[Output: T],
```
___
*[`corelib/src/result.cairo` line 340 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6921#-OF0rAPtBU1vB0bH5zu8:-OF0rAPuBVpCQGHn1vkN:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/33870fb290bf8328593a1cd0735d1845dd01492c/corelib/src/result.cairo#L340)):*
> ```Cairo
>     /// ```
>     #[inline]
>     fn and_then<U, F, +Drop<F>, impl func: core::ops::FnOnce<F, (T,)>[Output: Result<U, E>]>(
> ```





_Suggestion:_
```Cairo
    fn and_then<U, F, +Drop<F>, +core::ops::FnOnce<F, (T,)>[Output: Result<U, E>]>(
```
___
*[`corelib/src/result.cairo` line 400 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6921#-OF0r4Gf5UQyNdizVvLt:-OF0r4Gg1MK3YqJlRz06:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/33870fb290bf8328593a1cd0735d1845dd01492c/corelib/src/result.cairo#L400)):*
> ```Cairo
>     /// ```
>     #[inline]
>     fn or_else<F, O, +Drop<O>, impl func: core::ops::FnOnce<O, (E,)>[Output: Result<T, F>]>(
> ```





_Suggestion:_
```Cairo
    fn or_else<F, O, +Drop<O>, +func: core::ops::FnOnce<O, (E,)>[Output: Result<T, F>]>(
```

**Review by cairolover — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6921)* status: all files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/result.cairo` line 277 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6921#-OF0rDFD2vfBPczAW4-d:-OF0yekh9lyw0vsyBSCs:bqbkh6y) ([raw file](https://github.com/starkware-libs/cairo/blob/33870fb290bf8328593a1cd0735d1845dd01492c/corelib/src/result.cairo#L277)):*
> ```Cairo
>         +Destruct<E>,
>         +Drop<F>,
>         impl func: core::ops::FnOnce<F, (E,)>[Output: T],
> ```

Done. (removed restriction on func::Output as well)
___
*[`corelib/src/result.cairo` line 340 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6921#-OF0rAPtBU1vB0bH5zu8:-OF0ygla1gZLsPyqZ9qm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/33870fb290bf8328593a1cd0735d1845dd01492c/corelib/src/result.cairo#L340)):*
> ```Cairo
>     /// ```
>     #[inline]
>     fn and_then<U, F, +Drop<F>, impl func: core::ops::FnOnce<F, (T,)>[Output: Result<U, E>]>(
> ```

Done.
___
*[`corelib/src/result.cairo` line 400 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6921#-OF0r4Gf5UQyNdizVvLt:-OF0yhMN8H5orIUkuntW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/33870fb290bf8328593a1cd0735d1845dd01492c/corelib/src/result.cairo#L400)):*
> ```Cairo
>     /// ```
>     #[inline]
>     fn or_else<F, O, +Drop<O>, impl func: core::ops::FnOnce<O, (E,)>[Output: Result<T, F>]>(
> ```

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6921)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
