### PR TITLE
Made `withdraw_gas` return all variables.

### PR DESCRIPTION
**Pull request by orizi**
Making the results from linear calculation usable.

---

**Stack**:
- #4447
- #4439
- #4438 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4438)

### CODE REVIEW

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4438#-:-NjqSSPS6lEEad-9UhmD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4438)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4438)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-gas/src/compute_costs.rs` line 732 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4438#-Nkj3dWjBB0q15eN2hCg:-Nkj3dWjBB0q15eN2hCh:b-36oasj) ([raw file](https://github.com/starkware-libs/cairo/blob/508879d670af35eb869ed8a9a29ef7dfd0aa813b/crates/cairo-lang-sierra-gas/src/compute_costs.rs#L732)):*
> ```XML
>         future_wallet_value: i32,
>     ) -> Result<i32, CostError> {
>         let BranchCost::WithdrawGas(info) = branch_cost else {
> ```

This changes behavior + I'm not sure it can get to the else part.

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4438)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4438)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @liorgold2)

___
*[`crates/cairo-lang-sierra-gas/src/compute_costs.rs` line 686 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4438#-Nkj3U8m2mfcasRCPm6_:-NkjOM6a9pilPUp2gDHj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7a8c89b4244b5ef1fa0186be3f17945ca385f4c4/crates/cairo-lang-sierra-gas/src/compute_costs.rs#L686)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Revert removing the word `account`?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-gas/src/compute_costs.rs` line 732 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4438#-Nkj3dWjBB0q15eN2hCg:-NkjONUF7dIzF2xsnY8j:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/508879d670af35eb869ed8a9a29ef7dfd0aa813b/crates/cairo-lang-sierra-gas/src/compute_costs.rs#L732)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

This changes behavior + I'm not sure it can get to the else part.
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4438)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-gas/src/objects.rs` line 108 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4438#-Nkjgbqi-0zDcsYNWBLY:-NkjqdLBBGoPP4pBKvNL:b8hcafo) ([raw file](https://github.com/starkware-libs/cairo/blob/f2cc63a09cd5484149d36775a0f58f0a60fe2f6c/crates/cairo-lang-sierra-gas/src/objects.rs#L108)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

To verify that I understand: for old programs, this is guaranteed to be 0?
</blockquote></details>

yes - the solver would make sure of it as well (as these variables don't go into the calculation)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4438)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_expr.rs` line 60 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4438#-Nl3mUq-715eoSpVY78A:-Nl3mUq-715eoSpVY78B:bu2yxsp) ([raw file](https://github.com/starkware-libs/cairo/blob/f2cc63a09cd5484149d36775a0f58f0a60fe2f6c/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_expr.rs#L60)):*
> ```XML
>     libfunc: &CoreConcreteLibfunc,
> ) -> Vec<CostExprMap> {
>     // Keeping the old calculation as is - `withdraw_gas` should only supply gas for consts.
> ```

Consider moving this code into `core_libfunc_precost` with a bool argument.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4438)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_expr.rs` line 60 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4438#-Nl3mUq-715eoSpVY78A:-Nl3nwBr1xhg5HkUfTK7:b-uzx98d) ([raw file](https://github.com/starkware-libs/cairo/blob/f2cc63a09cd5484149d36775a0f58f0a60fe2f6c/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_expr.rs#L60)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Consider moving this code into `core_libfunc_precost` with a bool argument.
</blockquote></details>

Never mind. As you said - this is only to fix the bug.
Can we stop running this function at all starting Sierra 1.5.0?

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4438)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-gas/src/objects.rs` line 116 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4438#-Nl3tsr88IINM05c8OwX:-Nl3tsr88IINM05c8OwY:bkg44dg) ([raw file](https://github.com/starkware-libs/cairo/blob/f2cc63a09cd5484149d36775a0f58f0a60fe2f6c/crates/cairo-lang-sierra-gas/src/objects.rs#L116)):*
> ```XML
>         // Failure branch have some additional costs.
>         if !self.success {
>             if self.with_builtin_costs || cost_computation > 0 {
> ```

What happens if `with_builtin_costs = true` and `cost_computation == 0`? Do we still need the "additional minus 1" in this case?

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1, 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4438)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4438#-Nl3uSEyAdGFsURTE14X:-Nl3uSEz1NZl-J8pgLvb:b8alip7) (no related file):*
Should we have a unit test that shows that `withdraw_gas` doesn't take care of builtins (in 1.4.0)? We can discuss f2f.

```
fn foo() {
   match withdraw_gas() {
      ...success.. => {
         poseidon();
     }
     ...failure... => {}
   }
}
```

___

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4438)* status: all files reviewed, 7 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 118 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4438#-Nl3zp5W7UlPvD2NTB8M:-Nl3zp5XC2vVD_6vmVPA:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/e38513e1684d6631d764fc5c30783a94e00e5651/crates/cairo-lang-sierra-gas/src/lib.rs#L118)):*
> ```XML
>             ) {
>                 for token in CostTokenType::iter_precost() {
>                     assert_eq!(info.variable_values.insert((StatementIdx(i), *token), 0), None);
> ```

.



_Suggestion:_
```XML
                    // Check that the variable was not assigned a value, and set it to zero.
                    assert_eq!(info.variable_values.insert((StatementIdx(i), *token), 0), None);
```

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4438)* status: 8 of 9 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra-gas/src/objects.rs` line 116 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4438#-Nl3tsr88IINM05c8OwX:-NmV3uDUBSu6X-r4vRF-:b32wtd) ([raw file](https://github.com/starkware-libs/cairo/blob/e38513e1684d6631d764fc5c30783a94e00e5651/crates/cairo-lang-sierra-gas/src/objects.rs#L116)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

yes - doing this (very possible) change is a major sierra break.
</blockquote></details>

ok

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4438)* status: 8 of 9 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs` line 175 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4438#-NmVA-bp91oUN2SrZ6GL:-NmVA-bp91oUN2SrZ6GM:bjf9poy) ([raw file](https://github.com/starkware-libs/cairo/blob/1f26e21bdf8970a96ff92334e59139eb8827651f/crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs#L175)):*
> ```XML
>     pre_instructions: InstructionsWithRelocations,
> ) -> Result<CompiledInvocation, InvocationError> {
>     let failure_handle_statement_id = get_non_fallthrough_statement_id(&builder);
> ```

Move below, above the its usage.

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4438)* status: 8 of 9 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4438#-:-NmVCjYT3LCIdDTPMccJ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by liorgold2 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4438)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4438)* status: 8 of 9 files reviewed, all discussions resolved (waiting on @gilbens-starkware and @liorgold2)

**Pull request merged**
