### PR TITLE
Add DiagnosticNote.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3719)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3719)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-diagnostics/src/diagnostics.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3719#-N_mYVoTCs3d6Bp3TInu:-N_mYVoTCs3d6Bp3TInv:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/204f154981fbb083de5f47c4c8e6ecc4508b38c8/crates/cairo-lang-diagnostics/src/diagnostics.rs#L29)):*
> ```XML
> }
> #[derive(Clone, Debug, Eq, Hash, PartialEq)]
> pub struct DiagnosticLocation {
> ```

doc
___
*[`crates/cairo-lang-diagnostics/src/diagnostics.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3719#-N_mYZ061NU9AqrBiu4b:-N_mYZ061NU9AqrBiu4c:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/204f154981fbb083de5f47c4c8e6ecc4508b38c8/crates/cairo-lang-diagnostics/src/diagnostics.rs#L29)):*
> ```XML
> }
> #[derive(Clone, Debug, Eq, Hash, PartialEq)]
> pub struct DiagnosticLocation {
> ```





_Suggestion:_
```XML
    // TODO(spapini): Add a way to inspect the diagnostic programmatically, e.g, downcast.
}

#[derive(Clone, Debug, Eq, Hash, PartialEq)]
pub struct DiagnosticLocation {
```
___
*[`crates/cairo-lang-diagnostics/src/diagnostics.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3719#-N_mYQHM9YU9opUMiS7H:-N_mYQHM9YU9opUMiS7I:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/204f154981fbb083de5f47c4c8e6ecc4508b38c8/crates/cairo-lang-diagnostics/src/diagnostics.rs#L53)):*
> ```XML
> 
> #[derive(Clone, Debug, Eq, Hash, PartialEq)]
> pub struct DiagnosticNote {
> ```

doc

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3719)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/objects.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3719#-N_mYf6N5pzHicY4VgfN:-N_mYf6N5pzHicY4VgfO:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/204f154981fbb083de5f47c4c8e6ecc4508b38c8/crates/cairo-lang-lowering/src/objects.rs#L47)):*
> ```XML
>     }
> 
>     // Creates a new Location with the a note from the given text and location
> ```





_Suggestion:_
```XML
    /// Creates a new Location with the a note from the given text and location.
```

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3719)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3719)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-diagnostics/src/diagnostics.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3719#-N_mYZ061NU9AqrBiu4b:-N_n4KfrBiF6gxbJMqEa:bs7wumb) ([raw file](https://github.com/starkware-libs/cairo/blob/204f154981fbb083de5f47c4c8e6ecc4508b38c8/crates/cairo-lang-diagnostics/src/diagnostics.rs#L29)):*
> ```XML
> }
> #[derive(Clone, Debug, Eq, Hash, PartialEq)]
> pub struct DiagnosticLocation {
> ```

Done.
___
*[`crates/cairo-lang-diagnostics/src/diagnostics.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3719#-N_mYVoTCs3d6Bp3TInu:-N_n4o7U0gIt-lFUmawJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/204f154981fbb083de5f47c4c8e6ecc4508b38c8/crates/cairo-lang-diagnostics/src/diagnostics.rs#L29)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-diagnostics/src/diagnostics.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3719#-N_mYQHM9YU9opUMiS7H:-N_n4GTb3OIsxjN4xSZb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/204f154981fbb083de5f47c4c8e6ecc4508b38c8/crates/cairo-lang-diagnostics/src/diagnostics.rs#L53)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/objects.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3719#-N_mYf6N5pzHicY4VgfN:-N_n3x7m4j2TdxcIIAsE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/204f154981fbb083de5f47c4c8e6ecc4508b38c8/crates/cairo-lang-lowering/src/objects.rs#L47)):*
> ```XML
>     }
> 
>     // Creates a new Location with the a note from the given text and location
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3719)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/objects.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3719#-N_nEUIt8N71hvQmxCLD:-N_nEUIt8N71hvQmxCLE:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/678936aaa837b9c4439ce8b41c217c8ad23a927f/crates/cairo-lang-lowering/src/objects.rs#L47)):*
> ```XML
>     }
> 
>     /// Creates a new Location with the a note from the given text and location
> ```





_Suggestion:_
```XML
    /// Creates a new Location with the a note from the given text and location.
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3719)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/objects.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3719#-N_nEUIt8N71hvQmxCLD:-Na0KKmO1KdG46E6CSiI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/678936aaa837b9c4439ce8b41c217c8ad23a927f/crates/cairo-lang-lowering/src/objects.rs#L47)):*
> ```XML
>     }
> 
>     /// Creates a new Location with the a note from the given text and location
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3719#-:-Na0M4Mq5xhKnnzyaFmB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
