### PR TITLE
Verify that branching_libfuncs go to branch_align.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1868)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1868#-:-NMUW1iXD_0y7KkxnhcY:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1868#-NMUVhJ50u5UL5mNCCfW:-NMUVhJ6C-ACmLnfPBH0:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/99c492979fb28f84bfa0dc65d480d6a3fbabab7c/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L84)):*
> ```XML
>     /// The function id that the statement belongs to.
>     pub function_id: FunctionId,
>     // Indicates whether convergence in allowed in the given statement.
> ```





_Suggestion:_
```XML
    pub function_id: FunctionId,
    /// Indicates whether convergence in allowed in the given statement.
    pub convergence_allowed: bool,
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1868)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1868#-NMUVhJ50u5UL5mNCCfW:-NMXPXlEC4ZHjiyC-ug_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/99c492979fb28f84bfa0dc65d480d6a3fbabab7c/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L84)):*
> ```XML
>     /// The function id that the statement belongs to.
>     pub function_id: FunctionId,
>     // Indicates whether convergence in allowed in the given statement.
> ```

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1868)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1868)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
