### PR TITLE
Extract code out of get_branch_requirements().

### PR DESCRIPTION
**Pull request by liorgold2**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3056)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3056)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-gas/src/compute_costs.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3056#-NUprmwV20NXnGnuypEb:-NUprmwV20NXnGnuypEc:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/94b10076c42b2c5b2daea9725f291ae698159c96/crates/cairo-lang-sierra-gas/src/compute_costs.rs#L77)):*
> ```XML
> }
> 
> fn get_branch_requirements<
> ```

doc

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3056)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3056#-:-NUpsgrmEZjcpW36IdLA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3056)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-gas/src/compute_costs.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3056#-NUprmwV20NXnGnuypEb:-NUpsh_65JtAg3ZxEe9V:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/94b10076c42b2c5b2daea9725f291ae698159c96/crates/cairo-lang-sierra-gas/src/compute_costs.rs#L77)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Pull request merged**
