### PR TITLE
Add type inference for snapshot(TypeVar) and support for desnap of TypeVar.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2367)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2367)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2367#-NPmGHsfDL-g0IzNyPf2:-NPmGHsfDL-g0IzNyPf3:b-lefas8) (no related file):*
Change target branch.

___

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2367)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 242 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2367#-NPpo_V5EMBDPbXg1eKi:-NPpo_V5EMBDPbXg1eKj:b-83sjoh) ([raw file](https://github.com/starkware-libs/cairo/blob/0f37d49c06e219cd779e8c72bb6df6df251d77b2/crates/cairo-lang-semantic/src/expr/compute.rs#L242)):*
> ```XML
>         let desnapped_ty = match ctx.db.lookup_intern_type(expr_ty) {
>             TypeLongId::Var(_) => {
>                 let desnapped_var = ctx.resolver.inference.new_var(syntax.stable_ptr().0);
> ```

Nice!
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 233 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2367#-NPppBpg3nCACfgdkYtH:-NPppBpg3nCACfgdkYtI:b-219qsm) ([raw file](https://github.com/starkware-libs/cairo/blob/0f37d49c06e219cd779e8c72bb6df6df251d77b2/crates/cairo-lang-semantic/src/expr/inference.rs#L233)):*
> ```XML
>                     _ => {
>                         let var =
>                             extract_matches!(self.db.lookup_intern_type(inner_ty), TypeLongId::Var);
> ```

You are using matches! and extracting here. I'd rather if you used a single `if let` instead, to extract the value.



_Code quote:_
```XML
                        let var =
                            extract_matches!(self.db.lookup_intern_type(inner_ty), TypeLongId::Var);
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2367)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 224 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2367#-NPppNNA1_QebNhK-RM4:-NPppNNA1_QebNhK-RM5:b3x0c4n) ([raw file](https://github.com/starkware-libs/cairo/blob/0f37d49c06e219cd779e8c72bb6df6df251d77b2/crates/cairo-lang-semantic/src/expr/inference.rs#L224)):*
> ```XML
>             TypeLongId::Snapshot(inner_ty) if ty0_is_self && inner_ty == ty0 => {
>                 return Ok((ty1, 1));
>             }
> ```

I think this function should be revised. There must be something that covers all the bases correctly... Maybe we can set a time to discuss it?

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2367)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2367)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 233 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2367#-NPppBpg3nCACfgdkYtH:-NQ-MWiG06aqO2aWCIGS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0f37d49c06e219cd779e8c72bb6df6df251d77b2/crates/cairo-lang-semantic/src/expr/inference.rs#L233)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

You are using matches! and extracting here. I'd rather if you used a single `if let` instead, to extract the value.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2367#-:-NQ-Mr8m4_Wo0oceE6qA:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2367)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 227 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2367#-NQ-gl0B52tKOlR5u8k5:-NQ-gl0B52tKOlR5u8k6:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/1e375dfe4d4e1709c417f796a6683f33fcae5b38/crates/cairo-lang-semantic/src/expr/inference.rs#L227)):*
> ```XML
>                     }
>                     match self.db.lookup_intern_type(ty0) {
>                         TypeLongId::Snapshot(_) => {}
> ```





_Suggestion:_
```XML
                    if !matches!(self.db.lookup_intern_type(ty0), TypeLongId::Snapshot) {
```

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2367)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
why is this not merged yet?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2367#-:-NRasfXc1GbexAx_d8lP:b-3ld1vv)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

**Review by spapinistarkware — APPROVED** [review]
We can merge this, but the logic there (before this PR as well) is sketchy and not well defined, and we should clean it sometime.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2367#-:-NRavViF4lgi7QKl-6jZ:b-7govum)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Pull request merged**
