### PR TITLE
Adding the last line of a multi-line diagnostics.

### PR DESCRIPTION
**Pull request by Tomer-StarkWare**

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6850)* status: 0 of 41 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-diagnostics/src/diagnostics_test.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6850#-ODfGgmr-AO09mNG1IKD:-ODfGgmr-AO09mNG1IKE:b-u5n53r) ([raw file](https://github.com/starkware-libs/cairo/blob/588504849672544fbb45a2fa5c843462dcf75fe7/crates/cairo-lang-diagnostics/src/diagnostics_test.rs#L66)):*
> ```XML
>                  dummy_file.sierra:2:2
>             efg.
>             ***^
> ```

or something like that?
cause this one seems unclear.



_Suggestion:_
```XML
             --> dummy_file.sierra:1:1-2:2
            V***
            abcd
            efg.
            ***^
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6850)* status: 0 of 130 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-diagnostics/src/diagnostics_test.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6850#-ODfGgmr-AO09mNG1IKD:-ODgtWUZE94DfZqLZKAU:begw0lt) ([raw file](https://github.com/starkware-libs/cairo/blob/588504849672544fbb45a2fa5c843462dcf75fe7/crates/cairo-lang-diagnostics/src/diagnostics_test.rs#L66)):*
<details><summary><i>Previously, Tomer-StarkWare (TomerC-StarkWare) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

How about now?

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 142 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6850)* status: 5 of 142 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-diagnostics/src/location_marks.rs` line 9 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6850#-OEJms_r0veNlB8AZ0UQ:-OEJms_r0veNlB8AZ0UR:bkjz0pc) ([raw file](https://github.com/starkware-libs/cairo/blob/b59bf21b645f887cf8840b5d59690ebc8eed2065/crates/cairo-lang-diagnostics/src/location_marks.rs#L9)):*
> ```XML
> mod test;
> 
> pub fn get_location_marks(
> ```

this one is now only for single file?
if so - rename and doc.



_Code quote:_
```XML
pub fn get_location_marks(
```
___
*[`crates/cairo-lang-diagnostics/src/location_marks.rs` line 44 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6850#-OEJn3rU3lBO0NPrgnjA:-OEJn3rU3lBO0NPrgnjB:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b59bf21b645f887cf8840b5d59690ebc8eed2065/crates/cairo-lang-diagnostics/src/location_marks.rs#L44)):*
> ```XML
>             res.push('^');
>         }
>     }
> ```





_Suggestion:_
```XML
    

    let subspan_in_first_line =
        TextSpan { start: span.start, end: std::cmp::min(first_line_end, span.end) };
    let marker_length = subspan_in_first_line.n_chars(&content);
    res.extend(repeat_n('^', marker_length));
```
___
*[`crates/cairo-lang-diagnostics/src/location_marks.rs` line 49 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6850#-OEJmZak1DFxUft_2cPO:-OEJmZak1DFxUft_2cPP:b-y7juuw) ([raw file](https://github.com/starkware-libs/cairo/blob/b59bf21b645f887cf8840b5d59690ebc8eed2065/crates/cairo-lang-diagnostics/src/location_marks.rs#L49)):*
> ```XML
> }
> 
> pub fn get_multiple_lines_location_marks(
> ```

doc.

add boolean to skip printing middle lines.
(have `| ...` or something instead.

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6850)* status: 2 of 146 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-diagnostics/src/location_marks.rs` line 9 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6850#-OEJms_r0veNlB8AZ0UQ:-OEKD8hcCfE7jZwqSSKV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b59bf21b645f887cf8840b5d59690ebc8eed2065/crates/cairo-lang-diagnostics/src/location_marks.rs#L9)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this one is now only for single file?
if so - rename and doc.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-diagnostics/src/location_marks.rs` line 49 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6850#-OEJmZak1DFxUft_2cPO:-OEKFuIt26gQuJqSiTL-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b59bf21b645f887cf8840b5d59690ebc8eed2065/crates/cairo-lang-diagnostics/src/location_marks.rs#L49)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc.

add boolean to skip printing middle lines.
(have `| ...` or something instead.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-diagnostics/src/location_marks.rs` line 44 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6850#-OEJn3rU3lBO0NPrgnjA:-OEKE5_qCgvvOK4KDlSt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b59bf21b645f887cf8840b5d59690ebc8eed2065/crates/cairo-lang-diagnostics/src/location_marks.rs#L44)):*
> ```XML
>             res.push('^');
>         }
>     }
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 23 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6850)* status: 3 of 146 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-diagnostics/src/diagnostics.rs` line 134 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6850#-OEOTMCK5GxByNkQ0dhx:-OEOTMCK5GxByNkQ0dhy:b-rvnh1n) ([raw file](https://github.com/starkware-libs/cairo/blob/8b8f9c444fd6ed123845d41d1ed8e60d21d8936d/crates/cairo-lang-diagnostics/src/diagnostics.rs#L134)):*
> ```XML
>                             db,
>                             &user_location,
>                             starting_text_pos.line + 3 < ending_text_pos.line,
> ```

comment as to why.
(just creating 3 as a const with a good name above the `marks = ` can be enough)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 23 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6850)* status: 4 of 146 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-diagnostics/src/location_marks.rs` line 41 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6850#-OEOTntr3_Xhm024zlbu:-OEOTnts3G1xLyRNeLYQ:b-hfpv23) ([raw file](https://github.com/starkware-libs/cairo/blob/8b8f9c444fd6ed123845d41d1ed8e60d21d8936d/crates/cairo-lang-diagnostics/src/location_marks.rs#L41)):*
> ```XML
>         TextSpan { start: span.start, end: std::cmp::min(first_line_end, span.end) };
>     let marker_length = subspan_in_first_line.n_chars(&content);
>     println!("marker_length: {}", marker_length);
> ```

remove.



_Code quote:_
```XML
    println!("marker_length: {}", marker_length);
```
___
*[`crates/cairo-lang-diagnostics/src/location_marks.rs` line 43 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6850#-OEOTtLO9MEeOaILb-Tk:-OEOTtLO9MEeOaILb-Tl:bk3vso6) ([raw file](https://github.com/starkware-libs/cairo/blob/8b8f9c444fd6ed123845d41d1ed8e60d21d8936d/crates/cairo-lang-diagnostics/src/location_marks.rs#L43)):*
> ```XML
>     println!("marker_length: {}", marker_length);
>     // marker_length can be 0 if the span is empty.
>     res.extend(repeat_n('^', max(marker_length, 1)));
> ```

since just single use - consider:



_Suggestion:_
```XML
    res.extend(repeat_n('^', std::cmp::max(marker_length, 1)));
```
___
*[`crates/cairo-lang-diagnostics/src/location_marks.rs` line 77 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6850#-OEOU4Db3v8AdW1gq00m:-OEOU4Db3v8AdW1gq00n:bw2ukpo) ([raw file](https://github.com/starkware-libs/cairo/blob/8b8f9c444fd6ed123845d41d1ed8e60d21d8936d/crates/cairo-lang-diagnostics/src/location_marks.rs#L77)):*
> ```XML
>     } else {
>         res += "| ...\n";
>     }
> ```

put the `3` constant here.
from the outside you should just decide if you want this concept.



_Code quote:_
```XML
    if !skip_middle_lines {
        for row_index in first_line_idx + 1..=last_line_idx - 1 {
            res += &get_line_content(summary.clone(), row_index, content.clone(), false);
        }
    } else {
        res += "| ...\n";
    }
```
___
*[`crates/cairo-lang-diagnostics/src/location_marks.rs` line 113 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6850#-OEOUKX3CYynqFxZiaM8:-OEOUKX3CYynqFxZiaM9:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/8b8f9c444fd6ed123845d41d1ed8e60d21d8936d/crates/cairo-lang-diagnostics/src/location_marks.rs#L113)):*
> ```XML
>     };
>     res += line_span.take(&content);
>     res.push('\n');
> ```





_Suggestion:_
```XML
    format!("{}{content}\n", if first_line { " " } else { "| " })
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6850)* status: 4 of 146 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-diagnostics/src/diagnostics.rs` line 134 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6850#-OEOTMCK5GxByNkQ0dhx:-OEOZkR65Deso3UFIyn-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8b8f9c444fd6ed123845d41d1ed8e60d21d8936d/crates/cairo-lang-diagnostics/src/diagnostics.rs#L134)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

comment as to why.
(just creating 3 as a const with a good name above the `marks = ` can be enough)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-diagnostics/src/location_marks.rs` line 41 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6850#-OEOTntr3_Xhm024zlbu:-OEOZoU8BSRDt-khzsIA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8b8f9c444fd6ed123845d41d1ed8e60d21d8936d/crates/cairo-lang-diagnostics/src/location_marks.rs#L41)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-diagnostics/src/location_marks.rs` line 43 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6850#-OEOTtLO9MEeOaILb-Tk:-OEOZs4h6xqR6GqyqYj1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8b8f9c444fd6ed123845d41d1ed8e60d21d8936d/crates/cairo-lang-diagnostics/src/location_marks.rs#L43)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

since just single use - consider:
</blockquote></details>

Done.
___
*[`crates/cairo-lang-diagnostics/src/location_marks.rs` line 77 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6850#-OEOU4Db3v8AdW1gq00m:-OEO_Ywy2XRUxHXTB_Uj:b-rt24qn) ([raw file](https://github.com/starkware-libs/cairo/blob/8b8f9c444fd6ed123845d41d1ed8e60d21d8936d/crates/cairo-lang-diagnostics/src/location_marks.rs#L77)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

put the `3` constant here.
from the outside you should just decide if you want this concept.
</blockquote></details>

Not sure I understand. There is now a boolean that the function gets (not related to the number of lines), and a check in the function regarding the number of lines
___
*[`crates/cairo-lang-diagnostics/src/location_marks.rs` line 113 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6850#-OEOUKX3CYynqFxZiaM8:-OEOb0Za35_QFVBt_kDU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8b8f9c444fd6ed123845d41d1ed8e60d21d8936d/crates/cairo-lang-diagnostics/src/location_marks.rs#L113)):*
> ```XML
>     };
>     res += line_span.take(&content);
>     res.push('\n');
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6850)* status: 4 of 146 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-diagnostics/src/location_marks.rs` line 77 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6850#-OEOU4Db3v8AdW1gq00m:-OEOe-H6E3E9xXU8OCJJ:b-so2jgy) ([raw file](https://github.com/starkware-libs/cairo/blob/8b8f9c444fd6ed123845d41d1ed8e60d21d8936d/crates/cairo-lang-diagnostics/src/location_marks.rs#L77)):*
<details><summary><i>Previously, Tomer-StarkWare (TomerC-StarkWare) wrote…</i></summary><blockquote>

Not sure I understand. There is now a boolean that the function gets (not related to the number of lines), and a check in the function regarding the number of lines
</blockquote></details>

something like what you did.
___
*[`crates/cairo-lang-diagnostics/src/location_marks.rs` line 69 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6850#-OEOdfdpDe60AR4SjV-m:-OEOdfdpDe60AR4SjV-n:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a447ac82302b5bb996dc5315a73b756b500e9b63/crates/cairo-lang-diagnostics/src/location_marks.rs#L69)):*
> ```XML
>         span.end.position_in_file(db, location.file_id).expect("Failed to find location in file.");
> 
>     let minimum_lines_to_show = 3;
> ```





_Suggestion:_
```XML
    CONST LINES_TO_REPLACE_MIDDLE: usize = 4;
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6850)* status: 4 of 146 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-diagnostics/src/location_marks.rs` line 69 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6850#-OEOdfdpDe60AR4SjV-m:-OEOnRKG4a9mZ2UKlhTR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a447ac82302b5bb996dc5315a73b756b500e9b63/crates/cairo-lang-diagnostics/src/location_marks.rs#L69)):*
> ```XML
>         span.end.position_in_file(db, location.file_id).expect("Failed to find location in file.");
> 
>     let minimum_lines_to_show = 3;
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6850)* status: 4 of 146 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-diagnostics/src/location_marks.rs` line 70 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6850#-OEOpcwC06ENrruV-F9h:-OEOpcwC06ENrruV-F9i:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/24ec8f4f2a2060b4ff7ac1b80fcc475659ebb0f7/crates/cairo-lang-diagnostics/src/location_marks.rs#L70)):*
> ```XML
> 
>     const LINES_TO_REPLACE_MIDDLE: usize = 4;
>     if !skip_middle_lines || first_line_idx + LINES_TO_REPLACE_MIDDLE >= last_line_idx {
> ```





_Suggestion:_
```XML
if !skip_middle_lines || first_line_idx + LINES_TO_REPLACE_MIDDLE > last_line_idx {
```

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 142 files at r4, 1 of 23 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6850)* status: 7 of 146 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @Tomer-StarkWare)

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6850)* status: 7 of 146 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-diagnostics/src/location_marks.rs` line 70 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6850#-OEOpcwC06ENrruV-F9h:-OEOxMvFCLvsIwqj6h_E:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/24ec8f4f2a2060b4ff7ac1b80fcc475659ebb0f7/crates/cairo-lang-diagnostics/src/location_marks.rs#L70)):*
> ```XML
> 
>     const LINES_TO_REPLACE_MIDDLE: usize = 4;
>     if !skip_middle_lines || first_line_idx + LINES_TO_REPLACE_MIDDLE >= last_line_idx {
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 142 files at r4, 1 of 23 files at r5, 2 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6850)* status: 11 of 146 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-diagnostics/src/location_marks.rs` line 1 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6850#-OEP4urX553tZGPVWEmu:-OEP4urX553tZGPVWEmv:b-7i6sqo) ([raw file](https://github.com/starkware-libs/cairo/blob/f819340d47776c7ade228b30df85712db056160b/crates/cairo-lang-diagnostics/src/location_marks.rs#L1)):*
> ```XML
> use std::sync::Arc;
> ```

lets make `get_single` and `get_multiple` non-`pub`.
and have an external caller using the more relevant one.

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6850)* status: 6 of 146 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-diagnostics/src/location_marks.rs` line 1 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6850#-OEP4urX553tZGPVWEmu:-OEP8g7f3vN7y5ytLIgq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f819340d47776c7ade228b30df85712db056160b/crates/cairo-lang-diagnostics/src/location_marks.rs#L1)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

lets make `get_single` and `get_multiple` non-`pub`.
and have an external caller using the more relevant one.
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 15 of 142 files at r4, 1 of 6 files at r9, 5 of 7 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6850)* status: 27 of 146 files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 103 of 142 files at r4, 11 of 23 files at r5, 3 of 6 files at r9, 2 of 7 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6850)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6850#-:-OEPPOT65l4xOEL8g3Ct:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 15 of 50 files at r11.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6850)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @Tomer-StarkWare)

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6850)* status: 135 of 146 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/statement_location_test_data/simple` line 1149 at r11](https://reviewable.io/reviews/starkware-libs/cairo/6850#-OETEGAPA1RSMJo4OIk0:-OETSeJn4edPLWWEXxJZ:bhqhwc6) ([raw file](https://github.com/starkware-libs/cairo/blob/4f431d32d07b774c783973f7b42e452439438843/crates/cairo-lang-sierra-generator/src/statement_location_test_data/simple#L1149)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

should it be?
</blockquote></details>

Yes it should, fixed

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6850#-:-OETWoQw0PmwpwTrpAmS:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6850)* status: 145 of 146 files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
