### PR TITLE
Changed diagnostics to have full file paths

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4024)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4024)* status: 6 of 11 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-filesystem/src/ids.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4024#-NdiOqo5EkDqIYkee9Oo:-NdiOqo5EkDqIYkee9Op:b-use5l5) ([raw file](https://github.com/starkware-libs/cairo/blob/6c50780b2759858c4805b36c73d106f148b9539a/crates/cairo-lang-filesystem/src/ids.rs#L115)):*
> ```XML
>     fn full_path(&self, db: &dyn FilesGroup) -> String {
>         if let Some(parent) = self.parent {
>             format!("{}[{}]", parent.full_path(db), self.name)
> ```

can you explain this path?



_Code quote:_
```XML
"{}[{}]
```
___
*[`crates/cairo-lang-plugins/src/test.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4024#-NdiOZyA7jmLmwnNaAua:-NdiOZyA7jmLmwnNaAub:b2wqon9) ([raw file](https://github.com/starkware-libs/cairo/blob/6c50780b2759858c4805b36c73d106f148b9539a/crates/cairo-lang-plugins/src/test.rs#L153)):*
> ```XML
> }
> 
> fn test_general_plugin(
> ```

is this related?

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4024)* status: 6 of 12 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-filesystem/src/ids.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4024#-NdiOqo5EkDqIYkee9Oo:-NdieYMx85zQxVwJ5Xjd:bjl8avj) ([raw file](https://github.com/starkware-libs/cairo/blob/6c50780b2759858c4805b36c73d106f148b9539a/crates/cairo-lang-filesystem/src/ids.rs#L115)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can you explain this path?
</blockquote></details>

I didn't want to have a.cairo/virtual_file/virtual_file2.
I hoped you'd suggest something else for the syntax of a virtual file path.
___
*[`crates/cairo-lang-plugins/src/test.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4024#-NdiOZyA7jmLmwnNaAua:-NdierzX8Qz91vbxu1IB:b-ze5p5g) ([raw file](https://github.com/starkware-libs/cairo/blob/6c50780b2759858c4805b36c73d106f148b9539a/crates/cairo-lang-plugins/src/test.rs#L153)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is this related?
</blockquote></details>

Yes, I wanted to have a diagnostic with a path to a double-indirected file. See
"error: Double indirection diagnostic
 --> test_src/lib.cairo[virt1][virt2]:1:1
"
in file "general".

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 11 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4024)* status: 9 of 12 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-filesystem/src/ids.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4024#-NdiOqo5EkDqIYkee9Oo:-NdildOq54M6j6TpS3H2:bkuobr4) ([raw file](https://github.com/starkware-libs/cairo/blob/6c50780b2759858c4805b36c73d106f148b9539a/crates/cairo-lang-filesystem/src/ids.rs#L115)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I didn't want to have a.cairo/virtual_file/virtual_file2.
I hoped you'd suggest something else for the syntax of a virtual file path.
</blockquote></details>

add a todo to choose a more readable path.
and add to discussions.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4024)* status: 10 of 12 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4024)* status: 10 of 12 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-filesystem/src/ids.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4024#-NdiOqo5EkDqIYkee9Oo:-Ndk2Lcb1v4lF9b3Dpem:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6c50780b2759858c4805b36c73d106f148b9539a/crates/cairo-lang-filesystem/src/ids.rs#L115)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add a todo to choose a more readable path.
and add to discussions.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4024#-:-Ndk3717-gEaIRZ7yOXW:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4024)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4024)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
