### PR TITLE
Plugin diagnostic mapper

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1388)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/defs/src/plugin.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1388#-NJePhfn5N022BeUHJPx:-NJePhfn5N022BeUHJPy:bb7r2f0) ([raw file](https://github.com/starkware-libs/cairo/blob/2795abee2acaee5e3f098fd4353ce222dd1450fc/crates/defs/src/plugin.rs#L19)):*
> ```XML
> pub struct DynDiagnosticMapper(pub Arc<dyn DiagnosticMapper>);
> impl DynDiagnosticMapper {
>     pub fn new<T: DiagnosticMapper + 'static>(mapper: T) -> Self {
> ```

why?



_Code quote:_
```XML
 'static
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 14 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1388)* status: 14 of 15 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/defs/src/plugin.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1388#-NJeSx855GpTQr9kSUNk:-NJeSx855GpTQr9kSUNl:b-wvsxvb) ([raw file](https://github.com/starkware-libs/cairo/blob/2795abee2acaee5e3f098fd4353ce222dd1450fc/crates/defs/src/plugin.rs#L46)):*
> ```XML
> 
>     fn map_diag(&self, _diag: &dyn std::any::Any) -> Vec<PluginDiagnostic> {
>         vec![]
> ```

Aren't you deleting the diagnostics here?



_Code quote:_
```XML
vec![]
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1388)* status: 14 of 15 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/defs/src/plugin.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1388#-NJePhfn5N022BeUHJPx:-NJiiYb40uli1TySgpH8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2795abee2acaee5e3f098fd4353ce222dd1450fc/crates/defs/src/plugin.rs#L19)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why?
</blockquote></details>

Done.
___
*[`crates/defs/src/plugin.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1388#-NJeSx855GpTQr9kSUNk:-NJiiZLt9a7x2AGcUrFY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2795abee2acaee5e3f098fd4353ce222dd1450fc/crates/defs/src/plugin.rs#L46)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Aren't you deleting the diagnostics here?
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1388)* status: 11 of 15 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/defs/src/db.rs` line 186 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1388#-NJixWld7AJcyLB8Y3CG:-NJixWld7AJcyLB8Y3CH:by8lm26) ([raw file](https://github.com/starkware-libs/cairo/blob/7fc0903538e3cbee79ac161d88d39ac3355a656b/crates/defs/src/db.rs#L186)):*
> ```XML
> pub struct FileInfo {
>     pub diagnostic_mapper: DynDiagnosticMapper,
>     pub origin: FileIndex,
> ```

Document.



_Code quote:_
```XML
pub origin: FileIndex,
```
___
*[`crates/semantic/src/db.rs` line 602 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1388#-NJiydIH7GedxjBWp1RR:-NJiydIH7GedxjBWp1RS:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7fc0903538e3cbee79ac161d88d39ac3355a656b/crates/semantic/src/db.rs#L602)):*
> ```XML
>                     },
>                 });
>                 continue;
> ```





_Suggestion:_
```XML
has_changed = true;
continue;
```
___
*[`crates/semantic/src/diagnostic.rs` line 385 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1388#-NJizVarDviD9cjjCrYH:-NJizVarDviD9cjjCrYI:b-hfpv23) ([raw file](https://github.com/starkware-libs/cairo/blob/7fc0903538e3cbee79ac161d88d39ac3355a656b/crates/semantic/src/diagnostic.rs#L385)):*
> ```XML
>                     "Plugin diagnostic: {}\n Original diagnostic: {}",
>                     diagnostic.message,
>                     original_diag.format(db)
> ```

remove.



_Code quote:_
```XML
 original_diag.format(db)
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1388)* status: 13 of 15 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1388)* status: 13 of 15 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/semantic/src/diagnostic_test.rs` line 118 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1388#-NJizzHJEtMREqrIeT1G:-NJizzHJEtMREqrIeT1H:b-iawrn6) ([raw file](https://github.com/starkware-libs/cairo/blob/7fc0903538e3cbee79ac161d88d39ac3355a656b/crates/semantic/src/diagnostic_test.rs#L118)):*
> ```XML
>         indoc! {r#"
>             error: Unexpected return type. Expected: "core::integer::u128", found: "core::felt".
>              --> virt2:3:16
> ```

In the next PR place fix this to point to the source code.

you can change the plugin

AddInlineModuleDummyPlugin -> WrapFuncWithInlineModulePlugin



_Code quote:_
```XML
virt2:3:16
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1388)* status: 11 of 15 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/defs/src/db.rs` line 186 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1388#-NJixWld7AJcyLB8Y3CG:-NJj7Px-0itV1h_3cSQ3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7fc0903538e3cbee79ac161d88d39ac3355a656b/crates/defs/src/db.rs#L186)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Document.
</blockquote></details>

Done.
___
*[`crates/semantic/src/db.rs` line 602 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1388#-NJiydIH7GedxjBWp1RR:-NJj7QW3A2tlFg8psFYH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7fc0903538e3cbee79ac161d88d39ac3355a656b/crates/semantic/src/db.rs#L602)):*
> ```XML
>                     },
>                 });
>                 continue;
> ```

Done.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1388)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/defs/src/db.rs` line 186 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1388#-NJjKo7N7wUT6V35r1Es:-NJjKo7N7wUT6V35r1Et:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a31a11ab5dd37623dc400933ddcaedca4deac73e/crates/defs/src/db.rs#L186)):*
> ```XML
> pub struct FileInfo {
>     pub diagnostic_mapper: DynDiagnosticMapper,
>     /// The file index in this module from which the current file was generated.
> ```





_Suggestion:_
```XML
the
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 15 files at r1, 2 of 7 files at r2, 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1388)* status: all files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/defs/src/plugin.rs` line 55 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1388#-NJjLSUU93Fj23SyvD_H:-NJjLSUU93Fj23SyvD_I:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/a31a11ab5dd37623dc400933ddcaedca4deac73e/crates/defs/src/plugin.rs#L55)):*
> ```XML
> 
> pub struct PluginGeneratedFile {
>     pub name: SmolStr,
> ```

doc



_Code quote:_
```XML
pub struct PluginGeneratedFile {
    pub name: SmolStr,
    pub content: String,
    pub diagnostic_mapper: DynDiagnosticMapper,
}
```
___
*[`crates/semantic/src/db.rs` line 572 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1388#-NJjLcl94smbA-3L_Txd:-NJjLcl94smbA-3L_Txe:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/a31a11ab5dd37623dc400933ddcaedca4deac73e/crates/semantic/src/db.rs#L572)):*
> ```XML
> }
> 
> fn map_diagnostics(
> ```

doc



_Code quote:_
```XML
map_diagnostics(
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 15 files at r1, 1 of 7 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1388)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/defs/src/plugin.rs` line 10 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1388#-NJjNAbXAt2zo_Wx92C7:-NJjNAbY173K8U-1ATrs:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/a929423a1764f1b560c78a0592181cd94c281cb9/crates/defs/src/plugin.rs#L10)):*
> ```XML
> use syntax::node::ids::SyntaxStablePtrId;
> 
> pub trait DiagnosticMapper: std::fmt::Debug + Sync + Send {
> ```

doc



_Code quote:_
```XML
DiagnosticMapper
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1388)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/defs/src/db.rs` line 186 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1388#-NJjKo7N7wUT6V35r1Es:-NJjMnrfCE8LHbTQt02_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a31a11ab5dd37623dc400933ddcaedca4deac73e/crates/defs/src/db.rs#L186)):*
> ```XML
> pub struct FileInfo {
>     pub diagnostic_mapper: DynDiagnosticMapper,
>     /// The file index in this module from which the current file was generated.
> ```

Done.
___
*[`crates/defs/src/plugin.rs` line 55 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1388#-NJjLSUU93Fj23SyvD_H:-NJjMWKd6YI_5TnZtLr9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a31a11ab5dd37623dc400933ddcaedca4deac73e/crates/defs/src/plugin.rs#L55)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/semantic/src/db.rs` line 572 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1388#-NJjLcl94smbA-3L_Txd:-NJjMnEB9hGMWwCE_2Yp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a31a11ab5dd37623dc400933ddcaedca4deac73e/crates/semantic/src/db.rs#L572)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1388)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/defs/src/plugin.rs` line 10 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1388#-NJjNAbXAt2zo_Wx92C7:-NJjO9ej1iO8So4iNyJ1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a929423a1764f1b560c78a0592181cd94c281cb9/crates/defs/src/plugin.rs#L10)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1388#-:-NJjVYVs9_9Y4NjaT3wL:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1388#-:-NJjej032Ibiw9HP6LGG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 8 of 15 files at r1, 3 of 7 files at r2, 2 of 3 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1388)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
