### PR TITLE
Refactor block arena

### PR DESCRIPTION
**Pull request by spapinistarkware**
**Stack**:
- #1614
- #1613
- #1609
- #1607 ⬅
- #1606

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1607)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 10 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1607)* status: 10 of 12 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lowering/src/lower/context.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1607#-NKmZRn8803Cpib9O5_4:-NKmZRn8803Cpib9O5_5:b2ni2nk) ([raw file](https://github.com/starkware-libs/cairo/blob/52e84d3a76da5d22ecb7fc23d0811e5452d667b0/crates/cairo-lowering/src/lower/context.rs#L89)):*
> ```XML
>     /// Arena of allocated lowered variables.
>     pub variables: Arena<Variable>,
>     /// Arena of allocated lowered blocks.
> ```

fix



_Code quote:_
```XML
/// Arena of allocated lowered blocks.
```
___
*[`crates/cairo-lowering/src/objects/blocks.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1607#-NKmZNP9CuVypv5z0ThD:-NKmZNP9CuVypv5z0ThE:b-9hwykd) ([raw file](https://github.com/starkware-libs/cairo/blob/52e84d3a76da5d22ecb7fc23d0811e5452d667b0/crates/cairo-lowering/src/objects/blocks.rs#L9)):*
> ```XML
> 
> #[derive(Debug, Default, PartialEq, Eq)]
> pub struct Blocks(pub Vec<Block>);
> ```

doc as to why this and not arena.



_Code quote:_
```XML
Blocks
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1607)* status: 8 of 12 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lowering/src/lower/context.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1607#-NKmZRn8803Cpib9O5_4:-NKmcBjd0zfjNbArLXv2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/52e84d3a76da5d22ecb7fc23d0811e5452d667b0/crates/cairo-lowering/src/lower/context.rs#L89)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix
</blockquote></details>

Done.
___
*[`crates/cairo-lowering/src/objects/blocks.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1607#-NKmZNP9CuVypv5z0ThD:-NKmbpB13s1c_SeJhO1X:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/52e84d3a76da5d22ecb7fc23d0811e5452d667b0/crates/cairo-lowering/src/objects/blocks.rs#L9)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc as to why this and not arena.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 12 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1607#-:-NKmhr0mDSf4iZeckMfA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Comment by spapinistarkware** [comment]
✓ Commit merged in pull request [#1609](https://github.com/starkware-libs/cairo2/pull/1609)

**Pull request closed without merging**
