### PR TITLE
rewrite constant data after finalization

### PR DESCRIPTION
**Pull request by TomerStarkware**

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6825)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 1333 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6825#-ODLZIv18KN_YWcJir2q:-ODLZIv18KN_YWcJir2r:b-19ei7a) ([raw file](https://github.com/starkware-libs/cairo/blob/7850cee48676961476bc610dd049e9d8802fe4ec/crates/cairo-lang-semantic/src/expr/inference.rs#L1333)):*
> ```XML
>             ImplLongId::ImplVar(var) => {
>                 let long_id = var.lookup_intern(self.db);
>                 assert_eq!(self.inference_id, long_id.inference_id);
> ```

explain the assertion.
or if this change is required at all.



_Code quote:_
```XML
                assert_eq!(self.inference_id, long_id.inference_id);
```
___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 321 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6825#-ODLZjDUDn3Gm-Fxxahe:-ODLZjDUDn3Gm-Fxxahf:b-u1qfoi) ([raw file](https://github.com/starkware-libs/cairo/blob/7850cee48676961476bc610dd049e9d8802fe4ec/crates/cairo-lang-semantic/src/items/constant.rs#L321)):*
> ```XML
>     // Check fully resolved.
>     ctx.resolver.inference().finalize(ctx.diagnostics, constant_ast.stable_ptr().untyped());
>     ctx.apply_inference_rewriter_to_exprs();
> ```

why wasn't this enough?



_Code quote:_
```XML
   ctx.apply_inference_rewriter_to_exprs();
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6825)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 1333 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6825#-ODLZIv18KN_YWcJir2q:-ODL_FG_2quoF9Uyb29a:b-nccq3o) ([raw file](https://github.com/starkware-libs/cairo/blob/7850cee48676961476bc610dd049e9d8802fe4ec/crates/cairo-lang-semantic/src/expr/inference.rs#L1333)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

explain the assertion.
or if this change is required at all.
</blockquote></details>

not required,
but it never make senense to write an impl from another infrence
___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 321 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6825#-ODLZjDUDn3Gm-Fxxahe:-ODL_Zl2-8wGCuRDbJwy:bs6k4sn) ([raw file](https://github.com/starkware-libs/cairo/blob/7850cee48676961476bc610dd049e9d8802fe4ec/crates/cairo-lang-semantic/src/items/constant.rs#L321)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why wasn't this enough?
</blockquote></details>

we are returning `const_value` which contains vars to the module inference

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6825)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 1333 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6825#-ODLZIv18KN_YWcJir2q:-ODLa8iiCOuvdRxujKKR:b-7l1a84) ([raw file](https://github.com/starkware-libs/cairo/blob/7850cee48676961476bc610dd049e9d8802fe4ec/crates/cairo-lang-semantic/src/expr/inference.rs#L1333)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

not required,
but it never make senense to write an impl from another infrence
</blockquote></details>

but isn't it always true?
sounds like something for another PR in any case if required.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6825)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 1333 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6825#-ODLZIv18KN_YWcJir2q:-ODLcTIYAZ0XTVg13D60:bs0lhzy) ([raw file](https://github.com/starkware-libs/cairo/blob/7850cee48676961476bc610dd049e9d8802fe4ec/crates/cairo-lang-semantic/src/expr/inference.rs#L1333)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

but isn't it always true?
sounds like something for another PR in any case if required.
</blockquote></details>

it was not in this case, because of the bug 
but this apparently does happen in other test cases so I will revert in this pr anyway

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6825#-:-ODLdbCZ6z7aex38Pe-1:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6825)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 1333 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6825#-ODLZIv18KN_YWcJir2q:-ODLdQzK7DVABotnADds:b-az93wv) ([raw file](https://github.com/starkware-libs/cairo/blob/7850cee48676961476bc610dd049e9d8802fe4ec/crates/cairo-lang-semantic/src/expr/inference.rs#L1333)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

it was not in this case, because of the bug 
but this apparently does happen in other test cases so I will revert in this pr anyway
</blockquote></details>

ok this can happen because of clone_with_inference_id, which allows the impl and the inference to have different ids

**Pull request merged**
