### PR TITLE
Raise error on multiple occurrences of `#[panic_with]`

### PR DESCRIPTION
**Pull request by mkaput**
**Stack**:
- #2790
- #2789
- #2780
- #2731
- #2767 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2767)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2767#-:-NSmLeU_B_5QNvkgabYE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2767)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2767#-:-NStoNNf29i9f4NYYoc5:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @mkaput)

___
*[`crates/cairo-lang-plugins/src/plugins/panicable.rs` line 46 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2767#-NStndUGBpE7NsxGoBkD:-NStndUGBpE7NsxGoBkE:badkcgq) ([raw file](https://github.com/starkware-libs/cairo/blob/a0fb3034aaeb9c7432c57d2379192fb4ca009caa/crates/cairo-lang-plugins/src/plugins/panicable.rs#L46)):*
> ```XML
> impl SemanticPlugin for PanicablePlugin {}
> 
> /// Adds an implementation for all requested derives for the type.
> ```

Can you please fix the comment?



_Code quote:_
```XML
Adds an implementation for all requested derives for the type.
```
___
*[`crates/cairo-lang-plugins/src/plugins/panicable.rs` line 62 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2767#-NSto0ZhDm7CmR9gVZpc:-NSto0Zi4pcDSkTO3cjt:b-3qnc53) ([raw file](https://github.com/starkware-libs/cairo/blob/a0fb3034aaeb9c7432c57d2379192fb4ca009caa/crates/cairo-lang-plugins/src/plugins/panicable.rs#L62)):*
> ```XML
>             diagnostics: vec![PluginDiagnostic {
>                 stable_ptr: extra_attr.stable_ptr().untyped(),
>                 message: "Attribute cannot be applied multiple times to the same item.".into(),
> ```

suggestion



_Suggestion:_
```XML
`panic_with` attribute cannot be appli
```

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2767)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`crates/cairo-lang-plugins/src/plugins/panicable.rs` line 46 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2767#-NStndUGBpE7NsxGoBkD:-NStr6-z3aScM0KljgYy:b-e51ncg) ([raw file](https://github.com/starkware-libs/cairo/blob/a0fb3034aaeb9c7432c57d2379192fb4ca009caa/crates/cairo-lang-plugins/src/plugins/panicable.rs#L46)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Can you please fix the comment?
</blockquote></details>

I will address this on subsequent PR
___
*[`crates/cairo-lang-plugins/src/plugins/panicable.rs` line 62 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2767#-NSto0ZhDm7CmR9gVZpc:-NStr2a95gxQIMj6UPRV:b-e51ncg) ([raw file](https://github.com/starkware-libs/cairo/blob/a0fb3034aaeb9c7432c57d2379192fb4ca009caa/crates/cairo-lang-plugins/src/plugins/panicable.rs#L62)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

suggestion
</blockquote></details>

I will address this on subsequent PR

**Pull request merged**
