### PR TITLE
Remove arguments from state.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4208)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4208)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4208#-Nfz-Jiq2tOmsbD1fSRy:-Nfz-Jiq2tOmsbD1fSRz:b-4vhy95) ([raw file](https://github.com/starkware-libs/cairo/blob/34d71c7deaefb497607c9998126e7c6bd4c86cf7/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L226)):*
> ```XML
>     ) -> VarState {
>         let var_state = self.state().variables.swap_remove(arg).unwrap_or_else(|| {
>             panic!("Unkonwn state for {arg}.");
> ```

unreachable! And rephrase to explain why.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4208)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4208#-Nfz-Jiq2tOmsbD1fSRy:-Nfz18u18tGLyCSzATYw:by83h44) ([raw file](https://github.com/starkware-libs/cairo/blob/34d71c7deaefb497607c9998126e7c6bd4c86cf7/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L226)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

unreachable! And rephrase to explain why.
</blockquote></details>

What should be explained?

I assume that the state for all the variables is known.

I could use an unwrap without an explanation here, but in case we have a bug the error would be worse.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4208)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4208#-Nfz64x57sY1WLOJkEDf:-Nfz64x57sY1WLOJkEDg:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/34d71c7deaefb497607c9998126e7c6bd4c86cf7/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L226)):*
> ```XML
>     ) -> VarState {
>         let var_state = self.state().variables.swap_remove(arg).unwrap_or_else(|| {
>             panic!("Unkonwn state for {arg}.");
> ```





_Suggestion:_
```XML
 panic!("Unknown state for variable `{arg}`.");
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4208)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4208#-Nfz64x57sY1WLOJkEDf:-NfzBkwP13WN2B1ff-_Y:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/34d71c7deaefb497607c9998126e7c6bd4c86cf7/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L226)):*
> ```XML
>     ) -> VarState {
>         let var_state = self.state().variables.swap_remove(arg).unwrap_or_else(|| {
>             panic!("Unkonwn state for {arg}.");
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4208#-:-NfzEd_r2kO6N5YybxbC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
