### PR TITLE
fixed resolver data when resolving genric consts

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5678)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5678)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 271 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5678#-Nz30ANDCHV_DFYz8cKo:-Nz30ANE9tcEGVl8w5jF:bpoeaa2) ([raw file](https://github.com/starkware-libs/cairo/blob/2a1132bb454e09d3687da46e2f91ec23749903f8/crates/cairo-lang-semantic/src/items/constant.rs#L271)):*
> ```XML
>         for id in 0..inference.type_vars.len() {
>             inference.type_assignment.entry(LocalTypeVarId(id)).or_insert(ty_missing);
>         }
> ```

probably not required.



_Code quote:_
```XML
        let ty_missing = TypeId::missing(ctx.db, diag);
        for id in 0..inference.type_vars.len() {
            inference.type_assignment.entry(LocalTypeVarId(id)).or_insert(ty_missing);
        }
```
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 1113 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5678#-Nz30DKQE9Ghh_8Qttt7:-Nz30DKQE9Ghh_8Qttt8:bb7f2bf) ([raw file](https://github.com/starkware-libs/cairo/blob/2a1132bb454e09d3687da46e2f91ec23749903f8/crates/cairo-lang-semantic/src/resolve/mod.rs#L1113)):*
> ```XML
>                     Resolver::new(self.db, self.module_file_id, InferenceId::Canonical);
> 
>                 std::mem::swap(&mut resolver.data, &mut self.data);
> ```

doc.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5678)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 1114 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5678#-Nz34tOX6vbXhTvEtTvt:-Nz34tOX6vbXhTvEtTvu:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d2461e5bcee7465150843c915cafce0689c60b83/crates/cairo-lang-semantic/src/resolve/mod.rs#L1114)):*
> ```XML
> 
>                 // using the resolver's data in the constant computation context, so impvars are
>                 // added to the correct inference.
> ```





_Suggestion:_
```XML
                // using the resolver's data in the constant computation context, so impl vars are
                // added to the correct inference.
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5678)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 1111 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5678#-Nz35D2_8vEOHmymm6BP:-Nz35D2_8vEOHmymm6BQ:bp3vdsb) ([raw file](https://github.com/starkware-libs/cairo/blob/d2461e5bcee7465150843c915cafce0689c60b83/crates/cairo-lang-semantic/src/resolve/mod.rs#L1111)):*
> ```XML
>                 let environment = Environment::empty();
>                 let mut resolver =
>                     Resolver::new(self.db, self.module_file_id, InferenceId::Canonical);
> ```

take the data directly instead before - and then create the resolver with `Resolver::with_data`.
also - call it const_eval_resolver or something.
and doc the resetting of the data into self as well.



_Code quote:_
```XML
                let mut resolver =
                    Resolver::new(self.db, self.module_file_id, InferenceId::Canonical);
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5678#-:-Nz39vAeEmwuYXr8--5P:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5678)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 1111 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5678#-Nz35D2_8vEOHmymm6BP:-Nz392EG8JSQ8azEZ_0D:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d2461e5bcee7465150843c915cafce0689c60b83/crates/cairo-lang-semantic/src/resolve/mod.rs#L1111)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

take the data directly instead before - and then create the resolver with `Resolver::with_data`.
also - call it const_eval_resolver or something.
and doc the resetting of the data into self as well.
</blockquote></details>

Done.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5678)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 1136 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5678#-Nz3Jdk92MnHW5YTDAMT:-Nz3LCItB3shHA9LH331:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/02fb84a39bb8ea5e3566ccec4bff8d5e40df5318/crates/cairo-lang-semantic/src/resolve/mod.rs#L1136)):*
> ```XML
> 
>                 // Update `self` data with const_eval_resolver's data.
>                 std::mem::swap(&mut ctx.resolver.data, &mut self.data);
> ```

Done.

**Pull request merged**
