### PR TITLE
Made intro point be edge (src and dst stmts) based and node based.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3197)

### CODE REVIEW

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3197)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/references.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3197#-NVyCZ-pD_KuKljZbPmR:-NVyCZ-pD_KuKljZbPmS:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ae4626a22dc0501af34ca328279c8dad4002ef99/crates/cairo-lang-sierra-to-casm/src/references.rs#L151)):*
> ```XML
>                     stack_idx: None,
>                     introduction_point: IntroductionPoint {
>                         source_statement_idx: func.entry_point,
> ```





_Suggestion:_
```XML
source_statement_idx: None,
```

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3197)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

**Review by liorgold2 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3197)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3197)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
