### PR TITLE
Remove support of immediate as first argument of eq() libfuncs.

### PR DESCRIPTION
**Pull request by liorgold2**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2973)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2973)* status: 5 of 9 files reviewed, 1 unresolved discussion (waiting on @liorgold2, @orizi, and @spapinistarkware)

___
*[`tests/e2e_test_data/libfuncs/u16` line 388 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2973#-NUGKkkuCFLR0vy8O9tV:-NUGKkkuCFLR0vy8O9tW:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/06ca479d7f3ed8899576185514b0b6215d45a79a/tests/e2e_test_data/libfuncs/u16#L388)):*
> ```
> test::foo@0() -> (core::bool);
> 
> //! > ==========================================================================
> ```

remove



_Code quote:_
```
//! > ==========================================================================

//! > u16_eq libfunc (a immediate, b deref)

//! > test_comments
//! see the comment for: u16_eq libfunc (a deref, b deref).

//! > test_runner_name
SmallE2ETestRunner

//! > cairo
fn foo(b: u16) -> bool {
    integer::u16_eq(11_u16, b)
}
```

**Comment by ilyalesokhin-starkware** [comment]
*[`tests/e2e_test_data/libfuncs/u16` line 393 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2973#-NUGKnum8RA1cMaTez-j:-NUGKnum8RA1cMaTez-k:b-hfpv23) ([raw file](https://github.com/starkware-libs/cairo/blob/06ca479d7f3ed8899576185514b0b6215d45a79a/tests/e2e_test_data/libfuncs/u16#L393)):*
> ```
> 
> //! > test_comments
> //! see the comment for: u16_eq libfunc (a deref, b deref).
> ```

remove.



_Code quote:_
```
//! > test_comments
//! see the comment for: u16_eq libfunc (a deref, b deref).

//! > test_runner_name
SmallE2ETestRunner

//! > cairo
fn foo(b: u16) -> bool {
    integer::u16_eq(11_u16, b)
}
```

**Comment by ilyalesokhin-starkware** [comment]
*[`tests/e2e_test_data/libfuncs/u16` line 393 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2973#-NUGKnum8RA1cMaTez-j:-NUGKrhXEs1-mfoYxb72:bv473qz) ([raw file](https://github.com/starkware-libs/cairo/blob/06ca479d7f3ed8899576185514b0b6215d45a79a/tests/e2e_test_data/libfuncs/u16#L393)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

remove.
</blockquote></details>

Sorry, keep this one.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2973)* status: 5 of 9 files reviewed, 2 unresolved discussions (waiting on @liorgold2, @orizi, and @spapinistarkware)

___
*[`tests/e2e_test_data/libfuncs/u64` line 390 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2973#-NUGLYhP8uFcuL4UaSgj:-NUGLYhP8uFcuL4UaSgk:b-hfpv1m) ([raw file](https://github.com/starkware-libs/cairo/blob/6e97b48b01237fa6292125dc73fd019d98fd0835/tests/e2e_test_data/libfuncs/u64#L390)):*
> ```
> //! > ==========================================================================
> 
> //! > u64_eq libfunc (a immediate, b deref)
> ```

remove?



_Code quote:_
```
//! > u64_eq libfunc (a immediate, b deref)
```

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2973#-:-NUGMoj7CqoOW8Oq6wfe:bnfp4nl)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @liorgold2, @orizi, and @spapinistarkware)

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 4 of 7 files at r1, 2 of 2 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2973)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @orizi)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2973)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`tests/e2e_test_data/libfuncs/u64` line 390 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2973#-NUGLYhP8uFcuL4UaSgj:-NUGQLRf1JfKk_r7WCdk:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6e97b48b01237fa6292125dc73fd019d98fd0835/tests/e2e_test_data/libfuncs/u64#L390)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

remove?
</blockquote></details>

Done.

**Pull request merged**
