### PR TITLE
Replace setup_project with RootDatabaseBuilder

### PR DESCRIPTION
**Pull request by maciektr**
Suggested changes: 
- Replace `setup_project` functions with `RootDatabaseBuilder` functionality for more coherent API 
- Follow up on @ilyalesokhin-starkware work from #1889

This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1932)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1932)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @maciektr)

___
*[`crates/cairo-lang-compiler/src/db.rs` line 137 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1932#-NMwcSLfDSmebqXsm1EM:-NMwcSLfDSmebqXsm1EN:b3ihank) ([raw file](https://github.com/starkware-libs/cairo/blob/b233fbad09043c0d88cd23f5fd4b8dc8a1147f0a/crates/cairo-lang-compiler/src/db.rs#L137)):*
> ```XML
>         self.db
>             .as_files_group_mut()
>             .override_file_content(file_id, Some(Arc::new(format!("mod {file_stem};"))));
> ```

I belive this is broken if file_stem is lib.cairo.



_Code quote:_
```XML
   .override_file_content(file_id, Some(Arc::new(format!("mod {file_stem};"))));
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
What is the motivation for mixing setup_project with with the creation of the db?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1932#-:-NMwfUhAC6UXUeGcdIRO:bx7wu2z)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @maciektr and @spapinistarkware)

___
*[`crates/cairo-lang-compiler/src/db.rs` line 169 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1932#-NMwfOln8TewGGJlzZ6D:-NMwfOln8TewGGJlzZ6E:bbsvbh1) ([raw file](https://github.com/starkware-libs/cairo/blob/b233fbad09043c0d88cd23f5fd4b8dc8a1147f0a/crates/cairo-lang-compiler/src/db.rs#L169)):*
> ```XML
>         let bad_path_err = || ProjectError::BadPath { path: path.to_string_lossy().to_string() };
>         let file_stem = path.file_stem().and_then(OsStr::to_str).ok_or_else(bad_path_err)?;
>         if file_stem == "lib" { Ok(path.parent().ok_or_else(bad_path_err)?) } else { Ok(path) }
> ```

I'm afraid this behavior is going to be a bit surprising.

maybe we should support this option?



_Code quote:_
```XML
 if file_stem == "lib" { Ok(path.parent().ok_or_else(bad_path_err)?) } else { Ok(path) }
```

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1932)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @maciektr)

___
*[`crates/cairo-lang-compiler/src/db.rs` line 122 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1932#-NMxMzU9745lwi0_aiAd:-NMxMzU9745lwi0_aiAe:b-f7wgv6) ([raw file](https://github.com/starkware-libs/cairo/blob/b233fbad09043c0d88cd23f5fd4b8dc8a1147f0a/crates/cairo-lang-compiler/src/db.rs#L122)):*
> ```XML
>     /// Setup to 'db' to compile the file at the given path.
>     /// Returns the id of the generated crate.
>     fn setup_project_from_single_file(
> ```

Shouldn't these function actually be ctors on ProjectConfig?

**Comment by maciektr** [comment]
@ilyalesokhin-starkware @spapinistarkware 
This change has been motivated by an intent to provide both a more concise api for the project setup, as well as a convenient way to expose the main crates discovered during the setup phase for the use of scarb package manager. After a longer discussion with 
@mkaput held internally we have come to a conclusion that we can obtain the main crate ids through different means in the scarb internally. Thus we have decided that we can close this PR without introducing changes in regard to your concerns.

**Pull request closed without merging**
