### PR TITLE
LS: expose view analyzed crates command

### LINKED ISSUE #6089: Provide `cairo/viewAnalyzedCrates` as a command in VSCode
We have a custom LSP method that returns a Markdown string describing the entire current input to the AnalyzerDatabase:

https://github.com/starkware-libs/cairo/blob/b5c542917b3f953a25e6559028b31cadcfe8f62f/crates/cairo-lang-language-server/src/lsp/ext.rs#L5-L13

There is no way to use it in VSCode, though.

**Goal**: Implement a VSCode-side command, accessible from <kbd>F1</kbd> menu, that will open a side panel with a Markdown render of the output of `cairo/viewAnalyzedCrates`.

The preview should be refreshed whenever a different file is opened. Eventually, we'd love this to only refresh whenever CairoLS reports state change, but we don't have the necessary infrastructure yet.

> [!TIP]
> For reference, take a look how this is done in Rust Analyzer:
>
> https://github.com/rust-lang/rust-analyzer/blob/38817263e484337e842e4ba4259a7ab4617931ab/editors/code/src/commands.ts#L752-L818

> [!NOTE]
> Skip rendering Markdown if this would require manual parsing etc. It's only feasible for use to use it only if it's a one-liner from VSCode APIs. It'd be much more maintainable to return HTML from CairoLS and show it in webview - you can consider that.

### PR DESCRIPTION
**Pull request by piotmag769**
Closes #6089 

This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6266)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6266#-:-O57XGENAfs5e9epbHzY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @mkaput)

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6266)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, and @piotmag769)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6266#-O5DSpMX8VMB6G3ozfCz):*




_Suggestion:_
```
- 2f137f7: LS: expose view analyzed crates command
  
  fix #6089
```
___
*[`vscode-cairo/package.json` line 79 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6266#-O5DT3uj-pNL5rKyUikS:-O5DT3un0D5QOUx2UPYH:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2f137f79350d3d99d68425e1e218539dd28c3e55/vscode-cairo/package.json#L79)):*
> ```JSON
>       {
>         "command": "cairo.viewAnalyzedCrates",
>         "title": "View crates currently analyzed by LS",
> ```





_Suggestion:_
```JSON
View currently analyzed crates
```
___
*[`vscode-cairo/package.json` line 138 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6266#-O5DT7GW6pmmuzSvSv6P:-O5DT7GX31VymFn7-qqy:brpxjw3) ([raw file](https://github.com/starkware-libs/cairo/blob/2f137f79350d3d99d68425e1e218539dd28c3e55/vscode-cairo/package.json#L138)):*
> ```JSON
>     ],
>     "configurationDefaults": {
>       "explorer.fileNesting.enabled": true,
> ```

change out of scope of this PR

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6266)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, and @mkaput)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6266#-O5DSpMX8VMB6G3ozfCz):*
? i don't get it xD
___
*[`vscode-cairo/package.json` line 79 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6266#-O5DT3uj-pNL5rKyUikS:-O5DgbWpAiIqNt25YrkD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2f137f79350d3d99d68425e1e218539dd28c3e55/vscode-cairo/package.json#L79)):*
> ```JSON
>       {
>         "command": "cairo.viewAnalyzedCrates",
>         "title": "View crates currently analyzed by LS",
> ```

Done.
___
*[`vscode-cairo/package.json` line 138 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6266#-O5DT7GW6pmmuzSvSv6P:-O5Dgvpr7BwvHQTGKcjW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2f137f79350d3d99d68425e1e218539dd28c3e55/vscode-cairo/package.json#L138)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

change out of scope of this PR
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6266)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, and @mkaput)

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6266#-:-O5DrNwA4k3VNWHILbWM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6266#-O5DSpMX8VMB6G3ozfCz):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

? i don't get it xD
</blockquote></details>

link PR in commit/PR description

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6266)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)

**Review by mkaput — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6266)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)

**Review by mkaput — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6266)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)

**Pull request merged**
