### PR TITLE
Remove %{%} from hint serialization.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1527)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
This is compatible with cairo 0

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1527#-:-NKMZ_h61sAM5jCCDoxA:bpd2mz5)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @orizi)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1527)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/casm/src/instructions.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1527#-NKMZfwc9wl990MZHMB-:-NKMZfwc9wl990MZHMB0:bgi8vz9) ([raw file](https://github.com/starkware-libs/cairo/blob/1ec32c661be59f77ae26bce3b61f4a53a23942ba/crates/casm/src/instructions.rs#L72)):*
> ```XML
>                 write!(f, " ")?;
>             }
>             writeln!(f, "%}}")?;
> ```

This is a big ugly.

The alternative is to generate hint with `%{` and remove them when we serialize the program.
here:
https://github.com/starkware-libs/cairo/blob/8d3c62a0e8bf477a2dcc8015b8864d38a7331e5b/crates/starknet/src/casm_contract_class.rs#L83



_Code quote:_
```XML
            let hint_str = hint.to_string();
            write!(f, "%{{")?;
            if !hint_str.starts_with('\n') {
                write!(f, " ")?;
            }
            write!(f, "{}", hint)?;
            if !hint_str.ends_with('\n') {
                write!(f, " ")?;
            }
            writeln!(f, "%}}")?;
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1527)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/casm/src/instructions.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1527#-NKMcEPs4qtq9dfhDodk:-NKMcEPs4qtq9dfhDodl:bpzwmoc) ([raw file](https://github.com/starkware-libs/cairo/blob/1ec32c661be59f77ae26bce3b61f4a53a23942ba/crates/casm/src/instructions.rs#L64)):*
> ```XML
>         for hint in &self.hints {
>             let hint_str = hint.to_string();
>             write!(f, "%{{")?;
> ```

i think we can assume that if we have any line breaks - it would be consistent.



_Suggestion:_
```XML
            let hint_str = hint.to_string();
            if hint_str.contains('\n') {
                writeln!(f, "%{{{hint_str}%}}")
            } else {
                writeln!(f, "%{{ {hint_str} %}}")
            }
```
___
*[`crates/casm/src/instructions.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1527#-NKMZfwc9wl990MZHMB-:-NKMc-j36L1BKh0kQitY:bktzyn1) ([raw file](https://github.com/starkware-libs/cairo/blob/1ec32c661be59f77ae26bce3b61f4a53a23942ba/crates/casm/src/instructions.rs#L72)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

This is a big ugly.

The alternative is to generate hint with `%{` and remove them when we serialize the program.
here:
https://github.com/starkware-libs/cairo/blob/8d3c62a0e8bf477a2dcc8015b8864d38a7331e5b/crates/starknet/src/casm_contract_class.rs#L83
</blockquote></details>

it is pretty ugly - but we can probably simplify it in the way i suggest above - and it would be enough for now.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1527#-:-NKMdKJJ4vZvDZVO5pFx:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1527)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/casm/src/instructions.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1527#-NKMcEPs4qtq9dfhDodk:-NKMfINjCprwec2u3ADV:b-j7tc7) ([raw file](https://github.com/starkware-libs/cairo/blob/1ec32c661be59f77ae26bce3b61f4a53a23942ba/crates/casm/src/instructions.rs#L64)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i think we can assume that if we have any line breaks - it would be consistent.
</blockquote></details>

nice, though I prefer starts_with over contains.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1527)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
