### PR TITLE
Add derive for Default

### PR DESCRIPTION
**Pull request by ArielElp**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3733)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3733)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @ArielElp)

___
*[`corelib/src/lib.cairo` line 208 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3733#-Na1Ubqu0eQ4KsfRgSMA:-Na1Ubqu0eQ4KsfRgSMB:b18mlgu) ([raw file](https://github.com/starkware-libs/cairo/blob/736d4a644b31fc9066c88382e82d591088ceebe1/corelib/src/lib.cairo#L208)):*
> ```Cairo
>         bool::False
>     }
> }
> ```

add derive for bool directly.



_Code quote:_
```Cairo
impl BoolDefault of Default<bool> {
    #[inline(always)]
    fn default() -> bool nopanic {
        bool::False
    }
}
```
___
*[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3733#-Na1VVfV8544Igm5hZxH:-Na1VVfW9_jHAJJyeLmR:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/736d4a644b31fc9066c88382e82d591088ceebe1/crates/cairo-lang-plugins/src/plugins/derive.rs#L66)):*
> ```XML
> }
> 
> struct VariantExtraInfo {
> ```

doc
___
*[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3733#-Na1VM7j5mR6EvDCx7cc:-Na1VM7j5mR6EvDCx7cd:b-tea93c) ([raw file](https://github.com/starkware-libs/cairo/blob/736d4a644b31fc9066c88382e82d591088ceebe1/crates/cairo-lang-plugins/src/plugins/derive.rs#L68)):*
> ```XML
> struct VariantExtraInfo {
>     name: SmolStr,
>     attribute_names: Vec<String>,
> ```

keep a clone of the SyntaxPtr here - and use the `query_attr` function on it instead of this.



_Code quote:_
```XML
attribute_names
```
___
*[`crates/cairo-lang-syntax/src/node/helpers.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3733#-Na1UtYd7zrhE6mtZgW4:-Na1UtYd7zrhE6mtZgW5:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/736d4a644b31fc9066c88382e82d591088ceebe1/crates/cairo-lang-syntax/src/node/helpers.rs#L174)):*
> ```XML
>     }
> 
>     /// Find first attribute named exactly `attr` attached do this node.
> ```

remove



_Code quote:_
```XML
    fn attribute_names(&self, db: &dyn SyntaxGroup) -> Vec<String> {
        self.attributes_elements(db)
            .into_iter()
            .map(|a| a.attr(db).as_syntax_node().get_text_without_trivia(db))
            .collect()
    }

    /// Find first attribute named exactly `attr` attached do this node.
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3733)* status: 3 of 5 files reviewed, 6 unresolved discussions (waiting on @ArielElp)

___
*[`corelib/src/lib.cairo` line 22 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3733#-Na2Dq2Y7oefRPJ9P6li:-Na2Dq2Y7oefRPJ9P6lj:bqrrulg) ([raw file](https://github.com/starkware-libs/cairo/blob/7c5b0c15793d297c6698d9dda4714ed4de8d3800/corelib/src/lib.cairo#L22)):*
> ```Cairo
>     fn default() -> () {
>         ()
>     }
> ```

remove after https://reviewable.io/reviews/starkware-libs/cairo/3742 is merged.



_Code quote:_
```Cairo
impl DefaultTupleSize0 of Default<()> {
    fn default() -> () {
        ()
    }
```
___
*[`corelib/src/test/plugins_test.cairo` line 84 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3733#-Na2EBMRA-Kn-boEg2xQ:-Na2EBMRA-Kn-boEg2xR:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7c5b0c15793d297c6698d9dda4714ed4de8d3800/corelib/src/test/plugins_test.cairo#L84)):*
> ```Cairo
>     );
>     assert_eq(@actual, @expected, 'unexpected default value');
> }
> ```





_Suggestion:_
```Cairo
fn test_derive_default_struct() {
    let actual: StructForDefault = Default::default();
    let expected = StructForDefault { a: 0, b: 0, c: false };
    assert_eq(@actual, @expected, 'unexpected default value');
}

#[test]
fn test_derive_default_enum() {
    let actual: EnumForDefault = Default::default();
    let expected = EnumForDefault::C(
        StructForDefault { a: 0, b: 0, c: false }
    );
    assert_eq(@actual, @expected, 'unexpected default value');
}
```
___
*[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 402 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3733#-Na2EeBZ4t40tXkFv-gh:-Na2EeBZ4t40tXkFv-gi:b-h1vdp7) ([raw file](https://github.com/starkware-libs/cairo/blob/7c5b0c15793d297c6698d9dda4714ed4de8d3800/crates/cairo-lang-plugins/src/plugins/derive.rs#L402)):*
> ```XML
>                 variants.iter().enumerate().map(|(idx, variant)| {
>                     format!(
>                         "{name}::{variant_name}(x) => {{ serde::Serde::serialize(@{idx}, ref output); \
> ```

100 columns wide lines.



_Code quote:_
```XML
                  "{name}::{variant_name}(x) => {{ serde::Serde::serialize(@{idx}, ref output); \
```

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3733)* status: 3 of 5 files reviewed, 6 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/lib.cairo` line 208 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3733#-Na1Ubqu0eQ4KsfRgSMA:-Na1_bWo12497KKza8-G:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/736d4a644b31fc9066c88382e82d591088ceebe1/corelib/src/lib.cairo#L208)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add derive for bool directly.
</blockquote></details>

Done.
___
*[`corelib/src/test/plugins_test.cairo` line 84 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3733#-Na2EBMRA-Kn-boEg2xQ:-Na2q8tF7xKuI8KQXoim:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7c5b0c15793d297c6698d9dda4714ed4de8d3800/corelib/src/test/plugins_test.cairo#L84)):*
> ```Cairo
>     );
>     assert_eq(@actual, @expected, 'unexpected default value');
> }
> ```

Done.
___
*[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3733#-Na1VVfV8544Igm5hZxH:-Na2p09y7WNaSADGD33l:bplgac9) ([raw file](https://github.com/starkware-libs/cairo/blob/736d4a644b31fc9066c88382e82d591088ceebe1/crates/cairo-lang-plugins/src/plugins/derive.rs#L66)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

it's gone now
___
*[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3733#-Na1VM7j5mR6EvDCx7cc:-Na2p-jT46QGotJvKwa9:b-ipk2l1) ([raw file](https://github.com/starkware-libs/cairo/blob/736d4a644b31fc9066c88382e82d591088ceebe1/crates/cairo-lang-plugins/src/plugins/derive.rs#L68)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

keep a clone of the SyntaxPtr here - and use the `query_attr` function on it instead of this.
</blockquote></details>

passed db instead
___
*[`crates/cairo-lang-syntax/src/node/helpers.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3733#-Na1UtYd7zrhE6mtZgW4:-Na2pG6GAvGi45DJ_ep1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/736d4a644b31fc9066c88382e82d591088ceebe1/crates/cairo-lang-syntax/src/node/helpers.rs#L174)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3733)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/lib.cairo` line 22 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3733#-Na2Dq2Y7oefRPJ9P6li:-Na2s-9481quNZ6GI94j:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7c5b0c15793d297c6698d9dda4714ed4de8d3800/corelib/src/lib.cairo#L22)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove after https://reviewable.io/reviews/starkware-libs/cairo/3742 is merged.
</blockquote></details>

Done.

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3733)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 402 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3733#-Na2EeBZ4t40tXkFv-gh:-Na5FnIPBHVSX2BggzI5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7c5b0c15793d297c6698d9dda4714ed4de8d3800/crates/cairo-lang-plugins/src/plugins/derive.rs#L402)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

100 columns wide lines.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3733)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @ArielElp)

___
*[`corelib/src/test/plugins_test.cairo` line 81 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3733#-Na5PFFl1bYKkZB9kKPZ:-Na5PFFmDaVgOlp4n26h:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2adb21f240e0216e97e651e4d27d100394ec1d86/corelib/src/test/plugins_test.cairo#L81)):*
> ```Cairo
>     let actual: EnumForDefault = Default::default();
>     let expected = EnumForDefault::C(StructForDefault { a: 0, b: 0, c: bool::False });
>     assert_eq(@actual, @expected, 'unexpected default value');
> ```





_Suggestion:_
```Cairo
#[test]
fn test_derive_default_struct() {
    let actual: StructForDefault = Default::default();
    let expected = StructForDefault { a: 0, b: 0, c: false };
    assert_eq(@actual, @expected, 'unexpected default value');
}

#[test]
fn test_derive_default_enum() {
    let actual: EnumForDefault = Default::default();
    let expected = EnumForDefault::C(StructForDefault { a: 0, b: 0, c: false });
    assert_eq(@actual, @expected, 'unexpected default value');
```
___
*[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 64 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3733#-Na5QCrt9iYwEVt_62MS:-Na5QCruDVv2i4buGWWP:b-8qfa9x) ([raw file](https://github.com/starkware-libs/cairo/blob/2adb21f240e0216e97e651e4d27d100394ec1d86/crates/cairo-lang-plugins/src/plugins/derive.rs#L64)):*
> ```XML
>     Struct { members: Vec<SmolStr>, type_generics: Vec<SmolStr>, other_generics: Vec<String> },
>     Extern,
> }
> ```

do another PR properly refactoring the ExtraInfo so it would be nicer to add the Default option.
This PR does too much, and the addition of default itself does not look like all the other options.



_Code quote:_
```XML
enum ExtraInfo {
    Enum(Vec<Variant>),
    Struct { members: Vec<SmolStr>, type_generics: Vec<SmolStr>, other_generics: Vec<String> },
    Extern,
}
```
___
*[`crates/cairo-lang-syntax/src/node/helpers.rs` line 172 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3733#-Na5Pmxx-tw22MvLBKbx:-Na5Pmxx-tw22MvLBKby:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/2adb21f240e0216e97e651e4d27d100394ec1d86/crates/cairo-lang-syntax/src/node/helpers.rs#L172)):*
> ```XML
>             .map(|a| a.attr(db).as_syntax_node().get_text_without_trivia(db))
>             .collect()
>     }
> ```

remove



_Code quote:_
```XML
    }

    fn attribute_names(&self, db: &dyn SyntaxGroup) -> Vec<String> {
        self.attributes_elements(db)
            .into_iter()
            .map(|a| a.attr(db).as_syntax_node().get_text_without_trivia(db))
            .collect()
    }
```

**Pull request closed without merging**
