### PR TITLE
Add LoweringDiagnosticKind::UnexpectedError.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3666)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3666#-:-N_8xmp8Ar1Rm-grAQ51:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3666)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1172 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3666#-N_92026Dq5QBOGE4sLS:-N_92027DyWIUOKMnS0q:b-dri356) ([raw file](https://github.com/starkware-libs/cairo/blob/e31884a73d209a91e7f5c8bc12e6cc2ddcdb2f9f/crates/cairo-lang-lowering/src/lower/mod.rs#L1172)):*
> ```XML
>         members.iter().position(|(_, member)| member.id == expr.member).ok_or_else(|| {
>             LoweringFlowError::Failed(
>                 ctx.diagnostics.report(expr.stable_ptr.untyped(), UnexpectedError),
> ```

1. Why is this unexpected? What happens if one accesses a non-existing member?
2. Why is unexpected error different than panic? Is there a rule of thumb to when to do what when something unexpected happens?

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3666)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1172 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3666#-N_92026Dq5QBOGE4sLS:-N_92uAT9OkLNaTobvub:b-a2nfdv) ([raw file](https://github.com/starkware-libs/cairo/blob/e31884a73d209a91e7f5c8bc12e6cc2ddcdb2f9f/crates/cairo-lang-lowering/src/lower/mod.rs#L1172)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

1. Why is this unexpected? What happens if one accesses a non-existing member?
2. Why is unexpected error different than panic? Is there a rule of thumb to when to do what when something unexpected happens?
</blockquote></details>

1. This should have already been detected in the semantic level. (the current diagnostic was wrong)
2. This was just easy to keep, without the danger of actually causing panics for users.

**Comment by yuvalsw** [comment]
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1172 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3666#-N_92026Dq5QBOGE4sLS:-N_9C3Yk-eAcw7jkckj_:bv8p1gj) ([raw file](https://github.com/starkware-libs/cairo/blob/e31884a73d209a91e7f5c8bc12e6cc2ddcdb2f9f/crates/cairo-lang-lowering/src/lower/mod.rs#L1172)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

1. This should have already been detected in the semantic level. (the current diagnostic was wrong)
2. This was just easy to keep, without the danger of actually causing panics for users.
</blockquote></details>

2. I think it should be discussed in the team, but I am unblocking as it's an improvement.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3666#-:-N_9Ct5n3Qudp0XdBpTC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3666)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
