### PR TITLE
Add sub_pointers storage node.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5872)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5872)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware)

___
*[`corelib/src/starknet/storage.cairo` line 349 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5872#-O0CWJub5gQQnFS6JCqw:-O0CWJucBvbNpVmA3Qnm:b785nqh) ([raw file](https://github.com/starkware-libs/cairo/blob/d807cdf03c7f39c95cac15ebf2f39b5590f8cb26/corelib/src/starknet/storage.cairo#L349)):*
> ```Cairo
> }
> 
> pub trait SubPointersNode<T> {
> ```

Doc, including members 
___
*[`corelib/src/starknet/storage.cairo` line 515 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5872#-O0CWbYK9GIPThRtLvOq:-O0CWbYK9GIPThRtLvOr:b36p87o) ([raw file](https://github.com/starkware-libs/cairo/blob/d807cdf03c7f39c95cac15ebf2f39b5590f8cb26/corelib/src/starknet/storage.cairo#L515)):*
> ```Cairo
> 
> /// Implementation of SubPointersNode for core types.
> ```

Empty line 
___
*[`corelib/src/starknet/storage.cairo` line 518 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5872#-O0CX4OCENs6XaNRNkfL:-O0CX4OCENs6XaNRNkfM:bpgwn5j) ([raw file](https://github.com/starkware-libs/cairo/blob/d807cdf03c7f39c95cac15ebf2f39b5590f8cb26/corelib/src/starknet/storage.cairo#L518)):*
> ```Cairo
> #[derive(Drop, Copy)]
> struct u256SubPointersNode {
>     high: starknet::storage::StoragePointer<u128>,
> ```

Swap order to match original.
___
*[`corelib/src/starknet/storage.cairo` line 527 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5872#-O0CXDTR0kTsfVUHo2cH:-O0CXDTR0kTsfVUHo2cI:b-9ydo4z) ([raw file](https://github.com/starkware-libs/cairo/blob/d807cdf03c7f39c95cac15ebf2f39b5590f8cb26/corelib/src/starknet/storage.cairo#L527)):*
> ```Cairo
>         let base_address = self.address;
>         let mut current_offset = self.offset;
>         current_offset = current_offset + starknet::Store::<u128>::size();
> ```

There should be only one add.
The low should be with base offset 
___
*[`crates/cairo-lang-filesystem/src/ids.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5872#-O0CWpNI2iELWYk_VpfN:-O0CWpNI2iELWYk_VpfO:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/d807cdf03c7f39c95cac15ebf2f39b5590f8cb26/crates/cairo-lang-filesystem/src/ids.rs#L81)):*
> ```XML
> impl CodeMapping {
>     pub fn translate(&self, span: TextSpan) -> Option<TextSpan> {
>         return None;
> ```

?

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5872)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/starknet/storage.cairo` line 349 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5872#-O0CWJub5gQQnFS6JCqw:-O0D2vpz4Uc9jUfPvfX9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d807cdf03c7f39c95cac15ebf2f39b5590f8cb26/corelib/src/starknet/storage.cairo#L349)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Doc, including members
</blockquote></details>

Done.
___
*[`corelib/src/starknet/storage.cairo` line 515 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5872#-O0CWbYK9GIPThRtLvOq:-O0D6QKyCCcbI-rhEo10:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d807cdf03c7f39c95cac15ebf2f39b5590f8cb26/corelib/src/starknet/storage.cairo#L515)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Empty line
</blockquote></details>

Done.
___
*[`corelib/src/starknet/storage.cairo` line 518 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5872#-O0CX4OCENs6XaNRNkfL:-O0D6QpA2_6CIBypw3MU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d807cdf03c7f39c95cac15ebf2f39b5590f8cb26/corelib/src/starknet/storage.cairo#L518)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Swap order to match original.
</blockquote></details>

Done.
___
*[`corelib/src/starknet/storage.cairo` line 527 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5872#-O0CXDTR0kTsfVUHo2cH:-O0DAvCr5BdZ5UgC6wLP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d807cdf03c7f39c95cac15ebf2f39b5590f8cb26/corelib/src/starknet/storage.cairo#L527)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

There should be only one add.
The low should be with base offset
</blockquote></details>

Done.
___
*[`crates/cairo-lang-filesystem/src/ids.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5872#-O0CWpNI2iELWYk_VpfN:-O0DAxQbDiamMT1OAyfi:brsj8th) ([raw file](https://github.com/starkware-libs/cairo/blob/d807cdf03c7f39c95cac15ebf2f39b5590f8cb26/crates/cairo-lang-filesystem/src/ids.rs#L81)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

Was debugging, reverted.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5872)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware)

___
*[`corelib/src/starknet/storage.cairo` line 352 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5872#-O0DK0O8-GkYASC8haMD:-O0DK0O8-GkYASC8haME:bj56vg5) ([raw file](https://github.com/starkware-libs/cairo/blob/ceebad91a5f13135a29e20ed28a79c42864ba183/corelib/src/starknet/storage.cairo#L352)):*
> ```Cairo
> /// contrast to storage node, the fields of the struct are just offseted from the base address of
> /// the struct.
> pub trait SubPointersNode<T> {
> ```

the word `node` should probably be dropped all around.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5872)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin/storage_node.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5872#-O0DRbsn0OWXRk_yV7Sm:-O0DRbsn0OWXRk_yV7Sn:b-6tzyem) ([raw file](https://github.com/starkware-libs/cairo/blob/75365b81e0b13f99ea9a4d842362116ef7d2a9d7/crates/cairo-lang-starknet/src/plugin/storage_node.rs#L80)):*
> ```XML
> /// Code generation for the different types of storage nodes.
> impl StorageNodeType {
>     fn from_struct_ast(db: &dyn SyntaxGroup, struct_ast: &ast::ItemStruct) -> Option<Self> {
> ```

this requires validation not both exists.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2, 1 of 1 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5872)* status: all files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware)

___
*[`corelib/src/starknet/storage.cairo` line 353 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5872#-O0De8EbB3IsR8EvyX2q:-O0De8EbB3IsR8EvyX2r:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/21b00501ed4abbe49561f77605c4cd3e7ea5f0c6/corelib/src/starknet/storage.cairo#L353)):*
> ```Cairo
> /// the struct.
> pub trait SubPointers<T> {
>     /// The type of the storage node, generated for the struct T.
> ```





_Suggestion:_
```Cairo
    /// The type of the storage pointers, generated for the struct T.
```
___
*[`corelib/src/starknet/storage.cairo` line 355 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5872#-O0DeCCX85p0_5bP0v4t:-O0DeCCX85p0_5bP0v4u:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/21b00501ed4abbe49561f77605c4cd3e7ea5f0c6/corelib/src/starknet/storage.cairo#L355)):*
> ```Cairo
>     /// The type of the storage node, generated for the struct T.
>     type SubPointersType;
>     /// Creates a sub pointers node for the given storage pointer to a struct T.
> ```





_Suggestion:_
```Cairo
   /// Creates a sub pointers struct for the given storage pointer to a struct T.
```
___
*[`crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo` line 186 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5872#-O0DRHaa68zcNg1J882D:-O0DeI2IDqAG36GYWZM0:b6ivd5c) ([raw file](https://github.com/starkware-libs/cairo/blob/75365b81e0b13f99ea9a4d842362116ef7d2a9d7/crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo#L186)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

move to `storage_access.cairo` tests.
</blockquote></details>

and remove here.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/storage_access.cairo` line 141 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5872#-O0DeMvS5-WHdbRF3gGq:-O0DeMvS5-WHdbRF3gGr:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/21b00501ed4abbe49561f77605c4cd3e7ea5f0c6/crates/cairo-lang-starknet/cairo_level_tests/storage_access.cairo#L141)):*
> ```Cairo
>         d: 4_u64,
>         e: 5_u128,
>         f: BoundedInt::max() - 1,
> ```

?

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5872)* status: 4 of 7 files reviewed, 6 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/starknet/storage.cairo` line 352 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5872#-O0DK0O8-GkYASC8haMD:-O0DdIr8D9rimuJLoaVW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ceebad91a5f13135a29e20ed28a79c42864ba183/corelib/src/starknet/storage.cairo#L352)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the word `node` should probably be dropped all around.
</blockquote></details>

Done.
___
*[`corelib/src/starknet/storage.cairo` line 353 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5872#-O0De8EbB3IsR8EvyX2q:-O0DlSbj8Nsu-TrEIF5T:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/21b00501ed4abbe49561f77605c4cd3e7ea5f0c6/corelib/src/starknet/storage.cairo#L353)):*
> ```Cairo
> /// the struct.
> pub trait SubPointers<T> {
>     /// The type of the storage node, generated for the struct T.
> ```

Done.
___
*[`corelib/src/starknet/storage.cairo` line 355 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5872#-O0DeCCX85p0_5bP0v4t:-O0DlSzt3ScxAwfJ8ciq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/21b00501ed4abbe49561f77605c4cd3e7ea5f0c6/corelib/src/starknet/storage.cairo#L355)):*
> ```Cairo
>     /// The type of the storage node, generated for the struct T.
>     type SubPointersType;
>     /// Creates a sub pointers node for the given storage pointer to a struct T.
> ```

Done.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/storage_access.cairo` line 141 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5872#-O0DeMvS5-WHdbRF3gGq:-O0Dgp7B3jLwNg80YRUb:bw8annt) ([raw file](https://github.com/starkware-libs/cairo/blob/21b00501ed4abbe49561f77605c4cd3e7ea5f0c6/crates/cairo-lang-starknet/cairo_level_tests/storage_access.cairo#L141)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

Just to make the two parts different so it'll test the order is not mixed.
___
*[`crates/cairo-lang-starknet/src/plugin/storage_node.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5872#-O0DRbsn0OWXRk_yV7Sm:-O0DkwdxAKt5t43TROur:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/75365b81e0b13f99ea9a4d842362116ef7d2a9d7/crates/cairo-lang-starknet/src/plugin/storage_node.rs#L80)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this requires validation not both exists.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo` line 186 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5872#-O0DRHaa68zcNg1J882D:-O0DdJjK1Yd53gCm9aF8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/75365b81e0b13f99ea9a4d842362116ef7d2a9d7/crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo#L186)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

move to `storage_access.cairo` tests.
</blockquote></details>

Done.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5872)* status: 3 of 7 files reviewed, 6 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo` line 186 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5872#-O0DRHaa68zcNg1J882D:-O0Dlm7x9H7C2Xh0aEys:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/75365b81e0b13f99ea9a4d842362116ef7d2a9d7/crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo#L186)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5872#-:-O0DmxsFB_VTxnSB3WR0:bnfp4nl)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
