### PR TITLE
implizing generic impl's function's signatures

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5511)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5511)* status: 4 of 10 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 1092 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5511#-NxE3yAH8e2kIIUFABtI:-NxE3yAH8e2kIIUFABtJ:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/319892152dc7bb4c1c1591ef9682aa0962d7c487/crates/cairo-lang-semantic/src/db.rs#L1092)):*
> ```XML
>     #[salsa::invoke(items::functions::concrete_function_signature)]
>     fn concrete_function_signature(&self, function_id: FunctionId) -> Maybe<semantic::Signature>;
>     /// Returns the given function's signature, after implization as needed (that is, if this is an
> ```

?
___
*[`crates/cairo-lang-semantic/src/types.rs` line 199 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5511#-NxE3n0xDzM7Kt9065Ho:-NxE3n0xDzM7Kt9065Hp:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/319892152dc7bb4c1c1591ef9682aa0962d7c487/crates/cairo-lang-semantic/src/types.rs#L199)):*
> ```XML
> 
> #[derive(Clone, Debug, Copy)]
> pub enum ImplizationImplContext {
> ```

doc

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5511)* status: 4 of 10 files reviewed, 7 unresolved discussions (waiting on @orizi and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 958 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5511#-NxH8kl55YhWi12f5RFH:-NxH8kl6ACB1zdaCxKC3:bl1m8lj) ([raw file](https://github.com/starkware-libs/cairo/blob/319892152dc7bb4c1c1591ef9682aa0962d7c487/crates/cairo-lang-semantic/src/types.rs#L958)):*
> ```XML
>             type_id.is_var_free(db) && size.is_var_free(db)
>         }
>         TypeLongId::TraitType(_) => true,
> ```

Consider moving this to the `true` list if we are at it.



_Code quote:_
```XML
TypeLongId::TraitType(_) => true,
```
___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 749 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5511#-NxHA45XCi7fHL9onUcE:-NxHA45XCi7fHL9onUcF:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/319892152dc7bb4c1c1591ef9682aa0962d7c487/crates/cairo-lang-semantic/src/items/functions.rs#L749)):*
> ```XML
> }
> 
> /// Returns the Implizes signature of the given function  given its context.
> ```





_Suggestion:_
```XML
Returns the implized signature of the given function given its context.
```
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 2104 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5511#-NxHB79N2Uziffo9e54k:-NxHB79N2Uziffo9e54l:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/319892152dc7bb4c1c1591ef9682aa0962d7c487/crates/cairo-lang-semantic/src/items/tests/trait_type#L2104)):*
> ```
> //! > ==========================================================================
> 
> //! > using an impl's associated type in a concrete impl with generic args.
> ```





_Suggestion:_
```
Impl's associated type in a concrete impl with generic args.
```
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 2131 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5511#-NxHBJVw-Yqe_CEm0kej:-NxHBJVx79sVB4hXErS4:brejra4) ([raw file](https://github.com/starkware-libs/cairo/blob/319892152dc7bb4c1c1591ef9682aa0962d7c487/crates/cairo-lang-semantic/src/items/tests/trait_type#L2131)):*
> ```
> //! > ==========================================================================
> 
> //! > using a trait's associated type in a concrete impl with generic args.
> ```

Same below



_Suggestion:_
```
Trait's associated type in a concrete impl with generic args.
```
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 2154 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5511#-NxHAb6z1PPRGfKMvlTs:-NxHAb6z1PPRGfKMvlTt:b6ts96l) ([raw file](https://github.com/starkware-libs/cairo/blob/319892152dc7bb4c1c1591ef9682aa0962d7c487/crates/cairo-lang-semantic/src/items/tests/trait_type#L2154)):*
> ```
> }
> 
> ///TODO(TomerStarkware): infer impl types from trait types.   
> ```

Remove whitespaces at the end of the line, and if it is clear where the fix should be done move it there.



_Code quote:_
```
///TODO(TomerStarkware): infer impl types from trait types.
```

**Review by orizi — COMMENTED** [review]
> Reviewed 4 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5511)* status: 8 of 10 files reviewed, 7 unresolved discussions (waiting on @TomerStarkware)

**Comment by TomerStarkware** [comment]
irrelavant

**Pull request closed without merging**
