### PR TITLE
Made ParamSignature clonable

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3409)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3409)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3409#-NXpSw9G4mMFIm5-HUJM:-NXpSw9G4mMFIm5-HUJN:brwtf7v) (no related file):*
i think i am against this - as this loses the describaibility of weather we add `.with_allow_add_const(),` or similar per input.

___

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3409)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3409#-NXpSw9G4mMFIm5-HUJM:-NXpU53EEkCioV1O5igR:b9ddup6) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i think i am against this - as this loses the describaibility of weather we add `.with_allow_add_const(),` or similar per input.
</blockquote></details>

I didn't use it where we have with_allow_add_const()

___

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3409)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3409#-NXpSw9G4mMFIm5-HUJM:-NXpYD907vFIwc4iujuO:b-ciou2u) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i know - that is the point - when i want to change something won't i get some confusion?
</blockquote></details>

It's a utility. One can choose not to use it when it's not clear. I only used it where it was exactly the same.

___

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3409)* status: all files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3409#-NXpSw9G4mMFIm5-HUJM:-NXsMNHuCbXT0O8UixIJ:br1coop) (no related file):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

It's a utility. One can choose not to use it when it's not clear. I only used it where it was exactly the same.
</blockquote></details>

i know its a utility - i not sure it currently adds anything that don't just allows the code to be more confusing.

___

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3409)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3409#-NXpSw9G4mMFIm5-HUJM:-NXt8agtByH5qzv_-r-h:b-da7h2w) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i know its a utility - i not sure it currently adds anything that don't just allows the code to be more confusing.
</blockquote></details>

In some cases it reduces code. In some it's not, where one can choose not to use it. It makes a lot of sense to enable cloning it as sometimes there are parameters which are the same and there is no reason to create then again and again.

___
___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 287 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3409#-NXpUGJjDelF_2voXwA9:-NXtIzes-CxUpUpsimB9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f5ed8d09745f243899935b1bfa4a947038d89b1c/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L287)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

was index type on purpose.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/int/unsigned128.rs` line 121 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3409#-NXpU7ACEO6D23W1MI8v:-NXtJUH1BK8PwVPv9iVM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f5ed8d09745f243899935b1bfa4a947038d89b1c/crates/cairo-lang-sierra/src/extensions/modules/int/unsigned128.rs#L121)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

same issue as the previous pr.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3409#-:-NXtKbOU8xrRTxvGCIbj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3409#-NXpSw9G4mMFIm5-HUJM:-NXtKQjg73xP5MIK3QjW:bxy6ii4) (no related file):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

In some cases it reduces code. In some it's not, where one can choose not to use it. It makes a lot of sense to enable cloning it as sometimes there are parameters which are the same and there is no reason to create then again and again.
</blockquote></details>

do note this was always a very short construction - but resolving anyway.

___

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3409)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
