### PR TITLE
add type to ConstValue

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5564)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 20 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5564)* status: 20 of 23 files reviewed, 6 unresolved discussions (waiting on @mkaput and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/const_folding.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5564#-NxwDSWb4gSIZcSr6moJ:-NxwDSWb4gSIZcSr6moK:bsqt3cj) ([raw file](https://github.com/starkware-libs/cairo/blob/c452d3e029dddf7d998aa27f4fb89a0552157cf9/crates/cairo-lang-lowering/src/optimizations/const_folding.rs#L195)):*
> ```XML
>                                         };
>                                         v.is_zero()
>                                     }),
> ```

extract into a function and use everywhere.



_Suggestion:_
```XML
                                    ConstValue::Struct(s, _) => s.iter().all(|v| {
                                        v.into_int().unwrap().is_zero()
                                    }),
```
___
*[`crates/cairo-lang-semantic/src/types.rs` line 538 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5564#-NxwEPCL4JnmWn0Yo40l:-NxwEPCL4JnmWn0Yo40m:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c452d3e029dddf7d998aa27f4fb89a0552157cf9/crates/cairo-lang-semantic/src/types.rs#L538)):*
> ```XML
>                 _ => Err(diagnostics.report(syntax, FixedSizeArrayNonNumericSize)),
>             }
>         }
> ```





_Suggestion:_
```XML
            );
        if matches!(const_value, ConstValue::Int(_, _) | ConstValue::Generic(_)) {
            Ok(Some(const_value.intern(db)))
        } else {
            Err(diagnostics.report(syntax, FixedSizeArrayNonNumericSize))
        }
```
___
*[`crates/cairo-lang-semantic/src/expr/inference/canonic.rs` line 217 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5564#-NxwEukL1kzdvjrK_wHU:-NxwEukL1kzdvjrK_wHV:b-24fdpe) ([raw file](https://github.com/starkware-libs/cairo/blob/c452d3e029dddf7d998aa27f4fb89a0552157cf9/crates/cairo-lang-semantic/src/expr/inference/canonic.rs#L217)):*
> ```XML
>             id: *self.to_canonic.const_var_mapping.entry(var.id).or_insert(next_id),
>             inference_id: InferenceId::Canonical,
>             ..*var
> ```

rather stay explicit.



_Suggestion:_
```XML
            ty: var.ty
```
___
*[`crates/cairo-lang-semantic/src/expr/inference/canonic.rs` line 379 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5564#-NxwF17X7pEpDgZe-xhg:-NxwF17X7pEpDgZe-xhh:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/c452d3e029dddf7d998aa27f4fb89a0552157cf9/crates/cairo-lang-semantic/src/expr/inference/canonic.rs#L379)):*
> ```XML
>             id,
>             inference_id: self.mapping.target_inference_id,
>             ..*var
> ```

.



_Suggestion:_
```XML
            ty: var.ty
```
___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5564#-NxwF6Fk9_JRAKgvVbsX:-NxwF6Fk9_JRAKgvVbsY:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/c452d3e029dddf7d998aa27f4fb89a0552157cf9/crates/cairo-lang-semantic/src/items/constant.rs#L90)):*
> ```XML
>         self.lookup_intern(db).is_var_free()
>     }
> ```

doc
___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5564#-NxwFWFT1Xr8x44DL7Ef:-NxwFWFT1Xr8x44DL7Eg:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/c452d3e029dddf7d998aa27f4fb89a0552157cf9/crates/cairo-lang-semantic/src/items/constant.rs#L135)):*
> ```XML
>         }
>     }
>     pub fn ty(&self, db: &dyn SemanticGroup) -> Maybe<TypeId> {
> ```

doc

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5564)* status: 13 of 23 files reviewed, 8 unresolved discussions (waiting on @mkaput and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 764 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5564#-NxwSU3O65hzGHpuyatp:-NxwSU3O65hzGHpuyatq:bnj5dw3) ([raw file](https://github.com/starkware-libs/cairo/blob/8c50ddc47ee9a14756611387c345c2b42ebf5a47/crates/cairo-lang-lowering/src/db.rs#L764)):*
> ```XML
>                 * size
>                     .lookup_intern(db)
>                     .extract_value()
> ```

bad name - it does not state any particular type.



_Suggestion:_
```XML
                    .to_int()
```
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 669 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5564#-NxwSe0y05B8YzJ95uTU:-NxwSe0y05B8YzJ95uTV:bgrt1iv) ([raw file](https://github.com/starkware-libs/cairo/blob/8c50ddc47ee9a14756611387c345c2b42ebf5a47/crates/cairo-lang-lowering/src/lower/mod.rs#L669)):*
> ```XML
>                         .lookup_intern(ctx.db)
>                         .extract_value()
>                         .expect("Expected ConstValue::Int for size")
> ```

unwrapping sounds mostly ok to me all around here.



_Code quote:_
```XML
                        .expect("Expected ConstValue::Int for size")
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 23 files at r1, 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5564)* status: all files reviewed, 2 unresolved discussions (waiting on @mkaput and @TomerStarkware)

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 14 of 23 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5564#-:-NxwheMW3ah-oIPadXXx:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5564)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 162 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5564#-Nxx0n7-COTI2SFROuAZ:-Nxx0n70DxbFiDd14Iwp:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/1e57ff341eb4bc14d1f98c648d82471a69654fb8/crates/cairo-lang-semantic/src/items/constant.rs#L162)):*
> ```XML
>             _ => None,
>         }
>     }
> ```





_Suggestion:_
```XML
    /// Returns the value of an int const as a BigInt.
    pub fn to_int(self) -> Option<BigInt> {
        match self {
            ConstValue::Int(value, _) => Some(value),
            _ => None,
        }
    }
```

**Review by mkaput — APPROVED** [review]
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5564)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5564)* status: 12 of 24 files reviewed, 1 unresolved discussion (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 764 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5564#-NxwSU3O65hzGHpuyatp:-NxwZIIr0IxF0i8GVdI-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8c50ddc47ee9a14756611387c345c2b42ebf5a47/crates/cairo-lang-lowering/src/db.rs#L764)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

bad name - it does not state any particular type.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/types.rs` line 538 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5564#-NxwEPCL4JnmWn0Yo40l:-NxwJbLA8S-I9IDWzmVf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c452d3e029dddf7d998aa27f4fb89a0552157cf9/crates/cairo-lang-semantic/src/types.rs#L538)):*
> ```XML
>                 _ => Err(diagnostics.report(syntax, FixedSizeArrayNonNumericSize)),
>             }
>         }
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/inference/canonic.rs` line 217 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5564#-NxwEukL1kzdvjrK_wHU:-NxwJoyEB6bj7axRoFCw:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c452d3e029dddf7d998aa27f4fb89a0552157cf9/crates/cairo-lang-semantic/src/expr/inference/canonic.rs#L217)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rather stay explicit.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/inference/canonic.rs` line 379 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5564#-NxwF17X7pEpDgZe-xhg:-NxwJq1nC1YFkvkdcJB6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c452d3e029dddf7d998aa27f4fb89a0552157cf9/crates/cairo-lang-semantic/src/expr/inference/canonic.rs#L379)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5564#-NxwF6Fk9_JRAKgvVbsX:-NxwK9Zj0XDfMQ3fXGnV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c452d3e029dddf7d998aa27f4fb89a0552157cf9/crates/cairo-lang-semantic/src/items/constant.rs#L90)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5564#-NxwFWFT1Xr8x44DL7Ef:-NxwKAH_B7lM59mCGSx0:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c452d3e029dddf7d998aa27f4fb89a0552157cf9/crates/cairo-lang-semantic/src/items/constant.rs#L135)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 162 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5564#-Nxx0n7-COTI2SFROuAZ:-Ny-GEAx3yySe8yVWPuu:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1e57ff341eb4bc14d1f98c648d82471a69654fb8/crates/cairo-lang-semantic/src/items/constant.rs#L162)):*
> ```XML
>             _ => None,
>         }
>     }
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 162 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5564#-Ny-M_u2BmXI-VmU3plK:-Nyp1gIKCMLj-eutzpjP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/99d9c850395a71e411948c1f2a11968c7ffc09eb/crates/cairo-lang-semantic/src/items/constant.rs#L162)):*
> ```XML
>             _ => None,
>         }
>     }
> ```

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 10 of 12 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5564)* status: 22 of 24 files reviewed, 1 unresolved discussion (waiting on @mkaput)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5564#-:-Nyp3AT9-gHMvz6uOCXt:bnfp4nl)* status: 22 of 24 files reviewed, 1 unresolved discussion (waiting on @mkaput)

**Review by mkaput — APPROVED** [review]
> Reviewed 12 of 12 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5564)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Pull request closed without merging**
