### PR TITLE
Lowering signature

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2647)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2647)* status: all files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/ids.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2647#-NRlSH7mBe3ZSqjznJHn:-NRlSH7mBe3ZSqjznJHo:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/52c772249975189a4a9aa6ef371ce30e3a901a04/crates/cairo-lang-lowering/src/ids.rs#L226)):*
> ```XML
> #[derive(Clone, Debug, PartialEq, Eq, DebugWithDb, SemanticObject)]
> #[debug_db(dyn LoweringGroup + 'a)]
> pub struct Signature {
> ```

doc



_Code quote:_
```XML
pub struct Signature {
```
___
*[`crates/cairo-lang-lowering/src/ids.rs` line 249 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2647#-NRlSMf975m1QZN1kuf6:-NRlSMf975m1QZN1kuf7:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/52c772249975189a4a9aa6ef371ce30e3a901a04/crates/cairo-lang-lowering/src/ids.rs#L249)):*
> ```XML
> semantic::add_rewrite!(<'a>, SubstitutionRewriter<'a>, DiagnosticAdded, Signature);
> 
> fn parameter_as_member_path(param: semantic::Parameter) -> semantic::VarMemberPath {
> ```

doc



_Code quote:_
```XML
parameter_as_member_path
```
___
*[`crates/cairo-lang-sierra-generator/src/db.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2647#-NRlTfvl3rpC3a3WMzBb:-NRlTfvm0v-ADvANaP2S:b-l6mkjh) ([raw file](https://github.com/starkware-libs/cairo/blob/52c772249975189a4a9aa6ef371ce30e3a901a04/crates/cairo-lang-sierra-generator/src/db.rs#L106)):*
> ```XML
>     // it in the end of program_generator::get_sierra_program instead of calling this function from
>     // there.
>     let semantic_function_id = db.lookup_intern_sierra_function(function_id);
> ```

rename



_Code quote:_
```XML
semantic_function_id
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2647)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/ids.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2647#-NRlSH7mBe3ZSqjznJHn:-NRlV89i4arWAmMoQumn:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/52c772249975189a4a9aa6ef371ce30e3a901a04/crates/cairo-lang-lowering/src/ids.rs#L226)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/ids.rs` line 249 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2647#-NRlSMf975m1QZN1kuf6:-NRlV8UW59PMYkDgEbbS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/52c772249975189a4a9aa6ef371ce30e3a901a04/crates/cairo-lang-lowering/src/ids.rs#L249)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2647)* status: 8 of 10 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/db.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2647#-NRlTfvl3rpC3a3WMzBb:-NRlVIrn8qSbEMZmqW5u:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/52c772249975189a4a9aa6ef371ce30e3a901a04/crates/cairo-lang-sierra-generator/src/db.rs#L106)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rename
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2647#-:-NRlXgoZ69Lng7R7JEx3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
