### PR TITLE
Add span get and at.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2218)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2218)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`tests/e2e_test.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2218#-NOnUOYbBlhcZ0zrTpdu:-NOnUOYbBlhcZ0zrTpdv:b-f07qnw) ([raw file](https://github.com/starkware-libs/cairo/blob/9b36258059bc755895705a7975957df2449868b1/tests/e2e_test.rs#L48)):*
> ```XML
>     SmallE2ETestRunner
> );
> ```

move to test.cairo as discussed.



_Code quote:_
```XML
    },
    SmallE2ETestRunner
);

cairo_lang_test_utils::test_file_test_with_runner!(
    corelib_e2e,
    "e2e_test_data/corelib",
    {
        span: "span",
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2218)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`tests/e2e_test.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2218#-NOnUOYbBlhcZ0zrTpdu:-NOndUk-Cbhpy3BE8d10:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9b36258059bc755895705a7975957df2449868b1/tests/e2e_test.rs#L48)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

move to test.cairo as discussed.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2218)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/test.cairo` line 881 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2218#-NOne2JQ25_0cxQt2Z4Q:-NOnenSE0Tfg1ngIuhLJ:b1nmt77) ([raw file](https://github.com/starkware-libs/cairo/blob/882f5684cc7c976039ca29ea52e51239182cdfe6/corelib/src/test.cairo#L881)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove - meaning
</blockquote></details>

less comment for the test.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2218#-:-NOniVC0-NCKkFRs4km0:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Pull request merged**
