### PR TITLE
Borrow checker as analyzer

### PR DESCRIPTION
**Pull request by spapinistarkware**
This removes the optimization that was in borrow check before. That will be replaces by the new remapping optimization. So, they should probably be on the same stack before merging.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2240)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2240)* status: 3 of 22 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/test_data/arm_pattern_destructure` line 858 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2240#-NOseosJ3Edo_Jd12eAY:-NOseosJ3Edo_Jd12eAZ:b-g2nowh) ([raw file](https://github.com/starkware-libs/cairo/blob/fe65019a81c94fc5a5ab8a98c2a8e1e6aad1b411/crates/cairo-lang-lowering/src/test_data/arm_pattern_destructure#L858)):*
> ```
>   (v6: core::felt, v7: core::felt) <- struct_destructure(v5)
> End:
>   Callsite({v2 -> v37, v3 -> v36})
> ```

why would these be newly introduced?



_Code quote:_
```
, v3 -> v36
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2240)* status: 4 of 22 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/test_data/snapshot` line 242 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2240#-NOsexrdAbXkILnMgE22:-NOsexrdAbXkILnMgE23:bwomwzz) ([raw file](https://github.com/starkware-libs/cairo/blob/105f6ccfd4579a22a2e6d1104b0de7fa0474a156/crates/cairo-lang-lowering/src/test_data/snapshot#L242)):*
> ```
> //! > lowering_diagnostics
> error: Cannot desnap a non copyable type.
>  --> lib.cairo:2:3
> ```

this shouldn't have disappeared.



_Code quote:_
```
error: Cannot desnap a non copyable type.
 --> lib.cairo:2:3
  *value
  ^****^
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2240)* status: 4 of 22 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/test_data/snapshot` line 242 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2240#-NOsexrdAbXkILnMgE22:-NOsi3c-2IYNG9BzC2TD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/105f6ccfd4579a22a2e6d1104b0de7fa0474a156/crates/cairo-lang-lowering/src/test_data/snapshot#L242)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this shouldn't have disappeared.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 17 of 22 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2240#-:-NOsjHk67X1kLBW8qrmM:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2240#-NOsjLMb96C6DPrFC8DI:-NOsjLMb96C6DPrFC8DJ:b7rnqbn) (no related file):*
approve only after optimizing out extra remappings in a following pr.

___

**Pull request closed without merging**
