### PR TITLE
Add more getters.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2137)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2137)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/starknet.cairo` line 78 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2137#-NOJFe4e5BpPL2HoFz7C:-NOJFe4f97EoJp8x6XYL:b9mzokr) ([raw file](https://github.com/starkware-libs/cairo/blob/46d6a886b25e0c426a6346d166ac89eb9a805e8e/corelib/starknet.cairo#L78)):*
> ```Cairo
> extern fn get_block_number_syscall() -> SyscallResult::<felt> implicits(GasBuiltin, System) nopanic;
> 
> fn get_block_number() -> felt {
> ```

Why felt and not u128?



_Code quote:_
```Cairo
 felt
```
___
*[`corelib/starknet.cairo` line 86 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2137#-NOJFjQc77lnIaeN4Tz5:-NOJFjQc77lnIaeN4Tz6:b-a5pusk) ([raw file](https://github.com/starkware-libs/cairo/blob/46d6a886b25e0c426a6346d166ac89eb9a805e8e/corelib/starknet.cairo#L86)):*
> ```Cairo
> ) nopanic;
> 
> fn get_block_timestamp() -> felt {
> ```

Similarly here, what type should be here? What is the representation of this timestamp? Perhaps its own type?



_Code quote:_
```Cairo
felt 
```

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/starknet.cairo` line 86 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2137#-NOJFjQc77lnIaeN4Tz5:-NOJQ49JAzmHD5oVJQ_T:b-k2uuxk) ([raw file](https://github.com/starkware-libs/cairo/blob/46d6a886b25e0c426a6346d166ac89eb9a805e8e/corelib/starknet.cairo#L86)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Similarly here, what type should be here? What is the representation of this timestamp? Perhaps its own type?
</blockquote></details>

in soldidity it is uint (alias for uint256), are you ok with using uint128 here?

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2137#-:-NOJU6Zm0UrlwBdSxa_5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`corelib/starknet.cairo` line 86 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2137#-NOJFjQc77lnIaeN4Tz5:-NOJTvTiEzq7VQCY6laU:b-lsnep3) ([raw file](https://github.com/starkware-libs/cairo/blob/46d6a886b25e0c426a6346d166ac89eb9a805e8e/corelib/starknet.cairo#L86)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

in soldidity it is uint (alias for uint256), are you ok with using uint128 here?
</blockquote></details>

It's probably ok.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2137)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`corelib/starknet.cairo` line 78 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2137#-NOJFe4e5BpPL2HoFz7C:-NOJRcEMAmngJv8f0gp0:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/46d6a886b25e0c426a6346d166ac89eb9a805e8e/corelib/starknet.cairo#L78)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Why felt and not u128?
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 4 of 7 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2137)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by spapinistarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2137)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`corelib/starknet.cairo` line 78 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2137#-NOJFe4e5BpPL2HoFz7C:-NOJkE1M6GoM2QzB1hEE:b-v4jcxc) ([raw file](https://github.com/starkware-libs/cairo/blob/46d6a886b25e0c426a6346d166ac89eb9a805e8e/corelib/starknet.cairo#L78)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Lior asked for u64, right?

**Pull request merged**
