### PR TITLE
Use a unified mapping for variable states.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4171)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/local_variables_test_data/e2e` line 147 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4171#-Nfe2Mi63aEuA0HZH_n9:-Nfe2Mi71ZXtgPQImXNS:b-s5yz99) ([raw file](https://github.com/starkware-libs/cairo/blob/d41e1c2290e93dc31d4e0a68c099fcd5a14e87e4/crates/cairo-lang-sierra-generator/src/local_variables_test_data/e2e#L147)):*
> ```
> dup<felt252>([1]) -> ([1], [5])
> store_temp<felt252>([5]) -> ([5])
> store_local<felt252>([2], [1]) -> ([1])
> ```

I need to debug why this happens.



_Code quote:_
```
store_local<felt252>([2], [1]) -> ([1])
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4171)* status: 0 of 3 files reviewed, 2 unresolved discussions

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 381 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4171#-Nfe2tLG9FDuDbw0kVNF:-Nfe2tLG9FDuDbw0kVNG:b-nbmqg3) ([raw file](https://github.com/starkware-libs/cairo/blob/d41e1c2290e93dc31d4e0a68c099fcd5a14e87e4/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L381)):*
> ```XML
>     /// Copies all the temporary variables that are marked as locals into local variables,
>     /// and removes them from [State::temporary_variables].
>     fn store_temporary_variables_as_locals(&mut self) {
> ```

I'll try to merge this function with store_all_possibly_lost_variables.



_Code quote:_
```XML
fn store_temporary_variables_as_locals(&mut self) {
```

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4171)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/state.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4171#-NfeC6y9CcLEVeSs3LLk:-NfeC6y9CcLEVeSs3LLl:b3zasb1) ([raw file](https://github.com/starkware-libs/cairo/blob/d41e1c2290e93dc31d4e0a68c099fcd5a14e87e4/crates/cairo-lang-sierra-generator/src/store_variables/state.rs#L33)):*
> ```XML
> 
> #[derive(Clone, Debug, Eq, PartialEq)]
> pub enum VarState {
> ```

doc.

also - why no LocalVar?
___
*[`crates/cairo-lang-sierra-generator/src/store_variables/state.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4171#-NfeCV9j4gpGAH_18gd_:-NfeCV9j4gpGAH_18gda:b-6c9oph) ([raw file](https://github.com/starkware-libs/cairo/blob/0dcf4892da8d4d3c60f9787c6a305594ebbec9c8/crates/cairo-lang-sierra-generator/src/store_variables/state.rs#L121)):*
> ```XML
>         self.deferred_variables.swap_remove(&res);
>         self.temporary_variables.swap_remove(&res);
>         self.known_stack.remove_variable(&res);
> ```

where has the known stack gone to?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/store_variables/state.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4171#-NfeC6y9CcLEVeSs3LLk:-NfeO20f5i8SM8uRAlRc:b-b0zeda) ([raw file](https://github.com/starkware-libs/cairo/blob/d41e1c2290e93dc31d4e0a68c099fcd5a14e87e4/crates/cairo-lang-sierra-generator/src/store_variables/state.rs#L33)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc.

also - why no LocalVar?
</blockquote></details>

I thought I'd add it in a future PR, do you think it should be done in the same PR?

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4171)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 398 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4171#-NfeRKre6PBQPfS_uFTX:-NfeRKre6PBQPfS_uFTY:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d41e1c2290e93dc31d4e0a68c099fcd5a14e87e4/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L398)):*
> ```XML
>                 VarState::TempVar { ty } => ty,
>                 VarState::Deferred { .. } => panic!("expected tempvar"),
>             };
> ```





_Suggestion:_
```XML
            let VarState::TempVar { ty } = self.state().variables.swap_remove(var).unwrap() else {
                panic!("expected tempvar");
            };
```
___
*[`crates/cairo-lang-sierra-generator/src/store_variables/state.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4171#-NfeC6y9CcLEVeSs3LLk:-NfeQbsICsnAlpQnm8Hj:b-rlvdvd) ([raw file](https://github.com/starkware-libs/cairo/blob/d41e1c2290e93dc31d4e0a68c099fcd5a14e87e4/crates/cairo-lang-sierra-generator/src/store_variables/state.rs#L33)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I thought I'd add it in a future PR, do you think it should be done in the same PR?
</blockquote></details>

sure - still doc.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4171)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/state.rs` line 37 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4171#-NferkksBdXkpgGGjBnm:-Nferkkt7uQnrbjuFIOc:ba5fdph) ([raw file](https://github.com/starkware-libs/cairo/blob/0dcf4892da8d4d3c60f9787c6a305594ebbec9c8/crates/cairo-lang-sierra-generator/src/store_variables/state.rs#L37)):*
> ```XML
> pub struct State {
>     /// A map from [sierra::ids::VarId] of a deferred reference
>     /// (for example, `[ap - 1] + [ap - 2]`) to [DeferredVariableInfo].
> ```

Move the deleted doc to the new enum doc

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4171)* status: all files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/store_variables/state.rs` line 37 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4171#-NferkksBdXkpgGGjBnm:-NffA8NUEJ-B7jpt4Urb:b9ny4mt) ([raw file](https://github.com/starkware-libs/cairo/blob/0dcf4892da8d4d3c60f9787c6a305594ebbec9c8/crates/cairo-lang-sierra-generator/src/store_variables/state.rs#L37)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Move the deleted doc to the new enum doc
</blockquote></details>

I don't understand the comment.

What does '(for example, `[ap - 1] + [ap - 2]`) to [DeferredVariableInfo].' mean?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4171)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 398 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4171#-NfeRKre6PBQPfS_uFTX:-NffARNA8__UIGgc-rvq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d41e1c2290e93dc31d4e0a68c099fcd5a14e87e4/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L398)):*
> ```XML
>                 VarState::TempVar { ty } => ty,
>                 VarState::Deferred { .. } => panic!("expected tempvar"),
>             };
> ```

Done.
___
*[`crates/cairo-lang-sierra-generator/src/local_variables_test_data/e2e` line 147 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4171#-Nfe2Mi63aEuA0HZH_n9:-Nfek_CB6GJ53wVAY__P:b-qssebl) ([raw file](https://github.com/starkware-libs/cairo/blob/d41e1c2290e93dc31d4e0a68c099fcd5a14e87e4/crates/cairo-lang-sierra-generator/src/local_variables_test_data/e2e#L147)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I need to debug why this happens.
</blockquote></details>

fixed.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4171)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 398 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4171#-NfeRKre6PBQPfS_uFTX:-NffOWVMDOsYalVr8rZT:b-uaaqls) ([raw file](https://github.com/starkware-libs/cairo/blob/d41e1c2290e93dc31d4e0a68c099fcd5a14e87e4/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L398)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'll push the fix soon.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4171)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/state.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4171#-NfeC6y9CcLEVeSs3LLk:-NffYSKB03wC8YJv5WFc:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/d41e1c2290e93dc31d4e0a68c099fcd5a14e87e4/crates/cairo-lang-sierra-generator/src/store_variables/state.rs#L33)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

sure - still doc.
</blockquote></details>

done

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 381 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4171#-Nfe2tLG9FDuDbw0kVNF:-NffYWNV5iYcmofnTCQy:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/d41e1c2290e93dc31d4e0a68c099fcd5a14e87e4/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L381)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I'll try to merge this function with store_all_possibly_lost_variables.
</blockquote></details>

done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4171)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/state.rs` line 33 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4171#-NffXIQP2Alb07_ZFwKG:-NffZ99t2GQ6xZ5O_1Xu:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b2bbdb826dea0f67bcc26e226f19240cf457bd02/crates/cairo-lang-sierra-generator/src/store_variables/state.rs#L33)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc.
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4171)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/state.rs` line 40 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4171#-NffZE6GBzSlabPvPYyr:-NffZE6GBzSlabPvPYys:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/1f0ae9b3c7922daf3ee56789043aa90264dc67e0/crates/cairo-lang-sierra-generator/src/store_variables/state.rs#L40)):*
> ```XML
>     Deferred { info: DeferredVariableInfo },
>     // TODO(ilya): add LocalVar
> }
> ```





_Suggestion:_
```XML
    /// The variable is a temporary variable with the given type.
    TempVar { ty: sierra::ids::ConcreteTypeId },
    /// The variable is deferred with the given DeferredVariableInfo.
    Deferred { info: DeferredVariableInfo },
    // TODO(ilya): add LocalVar
}
```

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4171)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4171)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/state.rs` line 37 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4171#-NferkksBdXkpgGGjBnm:-NffbEwO2jizgoxOyvu3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0dcf4892da8d4d3c60f9787c6a305594ebbec9c8/crates/cairo-lang-sierra-generator/src/store_variables/state.rs#L37)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

to VarState - this will explain the meaning of TempVar vs deferred.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/store_variables/state.rs` line 40 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4171#-NffZE6GBzSlabPvPYyr:-NffbEf440i8DihQs6Bo:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1f0ae9b3c7922daf3ee56789043aa90264dc67e0/crates/cairo-lang-sierra-generator/src/store_variables/state.rs#L40)):*
> ```XML
>     Deferred { info: DeferredVariableInfo },
>     // TODO(ilya): add LocalVar
> }
> ```

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4171)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4171#-:-NffbTe2-sApBvzeCLJp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
