### PR TITLE
Added `require` util.

### PR DESCRIPTION
**Pull request by orizi**
Used all around.

---

**Stack**:
- #5418
- #5417
- #5416
- #5393 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5393)

### CODE REVIEW

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 27 of 28 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5393#-:-Nv7-RPh-SxNI7oXx7eO:bnfp4nl)* status: 27 of 28 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware and @mkaput)

**Review by mkaput — CHANGES_REQUESTED** [review]
TBH, to my eyes this does not bring significant improvements, but I want to enforce my opinion here. I would love just not to use it in the LS

> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5393#-:-Nv769Pe1SY8Lk6KWS7f:b-12nrdu)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 1218 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5393#-Nv75g0rDDx97bs0XS8O:-Nv75g0rDDx97bs0XS8P:b5u3fm) ([raw file](https://github.com/starkware-libs/cairo/blob/7a0b5d3920fc39c82f6070f85b1d2b66059b26e2/crates/cairo-lang-language-server/src/lib.rs#L1218)):*
> ```XML
>     let syntax_db = db.upcast();
>     let (node, lookup_items) = get_node_and_lookup_items(db, file, position)?;
>     require(node.kind(syntax_db) == SyntaxKind::TokenIdentifier)?;
> ```

Could you please revert this change in the LS code? I would like to eventually minimize source dependencies on compiler utils and other crates in my areas of interest :/

**Review by mkaput — COMMENTED** [review]
*I do not want to enforce

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5393#-:-Nv76SJ_3RsyY3r2JfUg:b-xl0t5l)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5393)* status: 27 of 28 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @ilyalesokhin-starkware, and @mkaput)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 1218 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5393#-Nv75g0rDDx97bs0XS8O:-Nv77Ih033jkjPrMEGZ6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7a0b5d3920fc39c82f6070f85b1d2b66059b26e2/crates/cairo-lang-language-server/src/lib.rs#L1218)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Could you please revert this change in the LS code? I would like to eventually minimize source dependencies on compiler utils and other crates in my areas of interest :/
</blockquote></details>

Done.

**Review by mkaput — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5393)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 27 of 28 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5393)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 1 of 28 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5393)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by mkaput — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5393)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 1 of 28 files at r1, 2 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5393)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
