### PR TITLE
Move compiler_errors test to use testing infra.

### PR DESCRIPTION
**Pull request by liorgold2**
**Stack**:
- #4787
- #4786 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4786)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4786)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/test_data/errors` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4786#-Nntb_VDDcDQbVuzu_m7:-Nntb_VE3h8YjYq0wwwK:bxfwdzt) ([raw file](https://github.com/starkware-libs/cairo/blob/ecd48b05bbf10ee2b8227d4020793d2507a02a59/crates/cairo-lang-sierra-to-casm/src/test_data/errors#L1)):*
> ```
> //! > Missing reference
> ```

it seems a lot is missing - can you please compare the files?

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4786)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/test_data/errors` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4786#-Nntb_VDDcDQbVuzu_m7:-No2-m3B7TNOCvvZCCIX:b-9nf6to) ([raw file](https://github.com/starkware-libs/cairo/blob/ecd48b05bbf10ee2b8227d4020793d2507a02a59/crates/cairo-lang-sierra-to-casm/src/test_data/errors#L1)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it seems a lot is missing - can you please compare the files?
</blockquote></details>

I didn't move the entire file to the infra, just the `compiler_errors` test.
I haven't reviewed all of them but the number of test cases is the same (37) and the first and last ones are also the same (and I used automation to make the translation)
Are you sure tests a missing?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4786)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/test_data/errors` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4786#-Nntb_VDDcDQbVuzu_m7:-No2QnaICbyBkFMfYbyU:b-uv4de1) ([raw file](https://github.com/starkware-libs/cairo/blob/ecd48b05bbf10ee2b8227d4020793d2507a02a59/crates/cairo-lang-sierra-to-casm/src/test_data/errors#L1)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

I didn't move the entire file to the infra, just the `compiler_errors` test.
I haven't reviewed all of them but the number of test cases is the same (37) and the first and last ones are also the same (and I used automation to make the translation)
Are you sure tests a missing?
</blockquote></details>

at least the type section of the last test.

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4786)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/test_data/errors` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4786#-Nntb_VDDcDQbVuzu_m7:-No66CLN62KAGCKA7n9f:b-v07gvo) ([raw file](https://github.com/starkware-libs/cairo/blob/ecd48b05bbf10ee2b8227d4020793d2507a02a59/crates/cairo-lang-sierra-to-casm/src/test_data/errors#L1)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

at least the type section of the last test.
</blockquote></details>

Ok, issue was that names didn't match the tests (due to alphabetic sorting). This should be fixed now.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4786#-:-No689-p8MMVmQ3ZVYJ0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
