### PR TITLE
Pass entire `FormattedDiagnosticEntry` to `DiagnosticCallback`

### PR DESCRIPTION
**Pull request by mkaput**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5179)

### CODE REVIEW

**Comment by mkaput** [comment]
pushed outside of the #5180 stack due to some spr abnormalities. needs #5180

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5179#-:-Ns-oYH_CxYYW2JS4MFW:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @maciektr)

**Review by maciektr — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5179#-:-Ns7b-Mm2w6QIvgKD21W:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5179)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @mkaput)

___
*[`-- commits` line 3 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5179#-NsAX3I84yzNNu6aSs7n):*
this rebase to main is probably missing

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5179)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`-- commits` line 3 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5179#-NsAX3I84yzNNu6aSs7n):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this rebase to main is probably missing
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5179)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Pull request merged**
