### PR TITLE
Share lowering context creation

### PR DESCRIPTION
**Pull request by spapinistarkware**
**Stack**:
- #1614
- #1613
- #1609
- #1607
- #1606 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1606)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1606)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lowering/src/lower.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1606#-NKmUmxg3R6onxavi2GM:-NKmUmxg3R6onxavi2GN:b-d6ylq8) ([raw file](https://github.com/starkware-libs/cairo/blob/5a7182c70aa2e4d7f31b5114a495bea83800680d/crates/cairo-lowering/src/lower.rs#L65)):*
> ```XML
>     // Params.
>     let input_semantic_vars: Vec<cairo_semantic::Variable> =
>         signature.params.iter().cloned().map(cairo_semantic::Variable::Param).collect();
> ```

these seem to already happen in the info, or at a later line.



_Code quote:_
```XML
    let function_def = db.free_function_definition(free_function_id)?;

    let signature = db.free_function_declaration_signature(free_function_id)?;

    let implicits = db.free_function_all_implicits_vec(free_function_id)?;
    // Params.






    let input_semantic_vars: Vec<cairo_semantic::Variable> =
        signature.params.iter().cloned().map(cairo_semantic::Variable::Param).collect();
```
___
*[`crates/cairo-lowering/src/lower/context.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1606#-NKmU4cbEoZ1no3PQl5O:-NKmU4cbEoZ1no3PQl5P:bdchfxe) ([raw file](https://github.com/starkware-libs/cairo/blob/5a7182c70aa2e4d7f31b5114a495bea83800680d/crates/cairo-lowering/src/lower/context.rs#L23)):*
> ```XML
> use crate::objects::{Block, Variable};
> 
> pub struct LoweringInfo<'db> {
> ```

what is the diff between the context and the info?
doc



_Code quote:_
```XML
pub struct LoweringInfo<'db> {
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1606)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lowering/src/lower.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1606#-NKmUmxg3R6onxavi2GM:-NKmc5mrE8pXh9zWOOu8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6d1002c4f87bef7cbae5b94ac8986e83902144f6/crates/cairo-lowering/src/lower.rs#L65)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

these seem to already happen in the info, or at a later line.
</blockquote></details>

Done.
___
*[`crates/cairo-lowering/src/lower/context.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1606#-NKmU4cbEoZ1no3PQl5O:-NKmc56o0qXPrGKBrpjT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6d1002c4f87bef7cbae5b94ac8986e83902144f6/crates/cairo-lowering/src/lower/context.rs#L23)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

what is the diff between the context and the info?
doc
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1606#-:-NKmhgIc0Z3Ff3bNHqsG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Comment by spapinistarkware** [comment]
✓ Commit merged in pull request [#1609](https://github.com/starkware-libs/cairo2/pull/1609)

**Pull request closed without merging**
