### PR TITLE
Dori/create point at infinity

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1548)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1548)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/cairo-sierra/src/extensions/modules/ec.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1548#-NKORl7WCQyJUSaLYM5Q:-NKORl7WCQyJUSaLYM5R:b-nnoox4) ([raw file](https://github.com/starkware-libs/cairo/blob/d645f4a0e81b3a0bcd6dbd03654fe4b11866320f/crates/cairo-sierra/src/extensions/modules/ec.rs#L102)):*
> ```XML
>             vec![OutputVarInfo {
>                 ty: context.get_concrete_type(EcPointType::id(), &[])?,
>                 ref_info: OutputVarReferenceInfo::Deferred(DeferredOutputKind::Generic),
> ```

I think it is const
___
*[`crates/cairo-sierra-ap-change/src/core_libfunc_ap_change.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1548#-NKORsAT8mRqkZEeDhKa:-NKORsAT8mRqkZEeDhKb:bc94hgm) ([raw file](https://github.com/starkware-libs/cairo/blob/d645f4a0e81b3a0bcd6dbd03654fe4b11866320f/crates/cairo-sierra-ap-change/src/core_libfunc_ap_change.rs#L44)):*
> ```XML
>             EcConcreteLibFunc::CreatePoint(_) => vec![ApChange::Known(6), ApChange::Known(6)],
>             EcConcreteLibFunc::CreatePointAtInfinity(_) => vec![ApChange::Known(2)],
>             EcConcreteLibFunc::InitState(_) => vec![ApChange::Unknown],
> ```

Cost should be zero
___
*[`crates/cairo-sierra-gas/src/core_libfunc_cost_base.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1548#-NKORxVG9T8MCLvLpwlP:-NKORxVG9T8MCLvLpwlQ:byhbyvw) ([raw file](https://github.com/starkware-libs/cairo/blob/d645f4a0e81b3a0bcd6dbd03654fe4b11866320f/crates/cairo-sierra-gas/src/core_libfunc_cost_base.rs#L64)):*
> ```XML
>         Bool(BoolConcreteLibFunc::Not(_)) => vec![ops.const_cost(1)],
>         Ec(EcConcreteLibFunc::CreatePoint(_)) => vec![ops.const_cost(3), ops.const_cost(3)],
>         Ec(EcConcreteLibFunc::CreatePointAtInfinity(_)) => vec![ops.const_cost(1)],
> ```

Ap change should be zero
___
*[`crates/cairo-sierra-to-casm/src/invocations/ec.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1548#-NKOS26vAKTzDLbOtFEI:-NKOS26vAKTzDLbOtFEJ:bl29ahw) ([raw file](https://github.com/starkware-libs/cairo/blob/d645f4a0e81b3a0bcd6dbd03654fe4b11866320f/crates/cairo-sierra-to-casm/src/invocations/ec.rs#L168)):*
> ```XML
>     casm_build_extend! {casm_builder,
>         const zero = BigInt::from(0);
>         tempvar x = zero;
> ```

Just return the zero itself, no need for the tempvars

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1548)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1548)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1548)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @orizi)

___
*[`crates/cairo-sierra/src/extensions/modules/ec.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1548#-NKORl7WCQyJUSaLYM5Q:-NKTCqH3-qolJxo5XIiR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d645f4a0e81b3a0bcd6dbd03654fe4b11866320f/crates/cairo-sierra/src/extensions/modules/ec.rs#L102)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I think it is const
</blockquote></details>

Done.
___
*[`crates/cairo-sierra-ap-change/src/core_libfunc_ap_change.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1548#-NKORsAT8mRqkZEeDhKa:-NKTCZHH2ylr73cd4FNf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d645f4a0e81b3a0bcd6dbd03654fe4b11866320f/crates/cairo-sierra-ap-change/src/core_libfunc_ap_change.rs#L44)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Cost should be zero
</blockquote></details>

Done.
___
*[`crates/cairo-sierra-gas/src/core_libfunc_cost_base.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1548#-NKORxVG9T8MCLvLpwlP:-NKTC_NO3o_edr-kTPLX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d645f4a0e81b3a0bcd6dbd03654fe4b11866320f/crates/cairo-sierra-gas/src/core_libfunc_cost_base.rs#L64)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Ap change should be zero
</blockquote></details>

Done.
___
*[`crates/cairo-sierra-to-casm/src/invocations/ec.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1548#-NKOS26vAKTzDLbOtFEI:-NKTCaRT3eNpRSWFxkEC:b-4a7x6f) ([raw file](https://github.com/starkware-libs/cairo/blob/d645f4a0e81b3a0bcd6dbd03654fe4b11866320f/crates/cairo-sierra-to-casm/src/invocations/ec.rs#L168)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Just return the zero itself, no need for the tempvars
</blockquote></details>

Done (now use `build_only_reference_changes` like in `felt_const` or `uint128_const`)

**Pull request closed without merging**
