### PR TITLE
Remove redundant checks and fix y_parity polarity.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3554)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
Please elaborate what changes (and if nontrivial - what is the rational).

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3554#-:-NZ6h1gn3v0oC5vDPnuU:bp58hjm)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 710 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3554#-NZ6gDp5EDBPgxVhk5-b:-NZ6gDp5EDBPgxVhk5-c:b-gyjvke) ([raw file](https://github.com/starkware-libs/cairo/blob/e6afeae594cdd1e6a626700a7b2b794fdb15ca81/crates/cairo-lang-runner/src/casm_run/mod.rs#L710)):*
> ```XML
>                     gas_counter,
>                     system_buffer.next_u256()?,
>                     system_buffer.next_felt252()?.is_odd(),
> ```

The param is called y_parity and is of type bool. This is a boolean, similar to `is_v_even`. So if it's zero (false in bool) - it indicates odd, and if it's not (true for bool), it indicates even.
As it's of type bool, it's anyway only makes sense to check if it's false or true, not odd/even.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1242 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3554#-NZ6gqZK6OXRIlDKMdh5:-NZ6gqZK6OXRIlDKMdh6:b-3bcmay) ([raw file](https://github.com/starkware-libs/cairo/blob/dcbafcd5ca1e6c7f0f855c582a0d6fe536636d6d/crates/cairo-lang-runner/src/casm_run/mod.rs#L1242)):*
> ```XML
> ) -> Result<SyscallResult, HintError> {
>     deduct_gas!(gas_counter, 500);
>     if m >= <secp256r1::Fr as PrimeField>::MODULUS.into() {
> ```

Rational for removing this?
Also - why only for r1 and not for k1?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1242 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3554#-NZ6gqZK6OXRIlDKMdh5:-NZ6iyKM4pCDS05Bgrey:b-qpgqec) ([raw file](https://github.com/starkware-libs/cairo/blob/dcbafcd5ca1e6c7f0f855c582a0d6fe536636d6d/crates/cairo-lang-runner/src/casm_run/mod.rs#L1242)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Rational for removing this?
Also - why only for r1 and not for k1?
</blockquote></details>

I meant to fix k1.

I don't see the point in adding this extra check.

**Comment by ilyalesokhin-starkware** [comment]
The rational is to make it consistent with the implementation in the OS.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
Please elaborate that in the pr title

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3554#-:-NZ6uGQ50PwNeAD72Pir:bq0rnit)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 710 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3554#-NZ6gDp5EDBPgxVhk5-b:-NZ6tnra8kWBHMBzOZyf:bbuj7z) ([raw file](https://github.com/starkware-libs/cairo/blob/e6afeae594cdd1e6a626700a7b2b794fdb15ca81/crates/cairo-lang-runner/src/casm_run/mod.rs#L710)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why does it make sense for 0 to indicate odd?
</blockquote></details>

0 indicates false. And false for `is_even` is odd.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 710 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3554#-NZ6gDp5EDBPgxVhk5-b:-NZ71rV-Dw28d_Ktnlg0:b-4gw8wk) ([raw file](https://github.com/starkware-libs/cairo/blob/e6afeae594cdd1e6a626700a7b2b794fdb15ca81/crates/cairo-lang-runner/src/casm_run/mod.rs#L710)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

0 indicates false. And false for `is_even` is odd.
</blockquote></details>

the field is call `y_parity`, not `is_even`.

do you want to rename it?

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3554)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 710 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3554#-NZ6gDp5EDBPgxVhk5-b:-NZ759qeEXkPr8X169S6:bdvu037) ([raw file](https://github.com/starkware-libs/cairo/blob/e6afeae594cdd1e6a626700a7b2b794fdb15ca81/crates/cairo-lang-runner/src/casm_run/mod.rs#L710)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

the field is call `y_parity`, not `is_even`.

do you want to rename it?
</blockquote></details>

I my head it's the same: is y even.
But you are probably right. is_y_even is clearer. You can rename it if you want.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1242 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3554#-NZ6gqZK6OXRIlDKMdh5:-NZ73wax0oRPsXtDqnar:b-yp04z1) ([raw file](https://github.com/starkware-libs/cairo/blob/dcbafcd5ca1e6c7f0f855c582a0d6fe536636d6d/crates/cairo-lang-runner/src/casm_run/mod.rs#L1242)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I meant to fix k1.

I don't see the point in adding this extra check.
</blockquote></details>

In the original pr I asked Ori why it's needed. He wanted it, please make sure he's also ok with removing it.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 710 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3554#-NZ6gDp5EDBPgxVhk5-b:-NZKI7sk0ZQR3km7866P:b6z3nee) ([raw file](https://github.com/starkware-libs/cairo/blob/e6afeae594cdd1e6a626700a7b2b794fdb15ca81/crates/cairo-lang-runner/src/casm_run/mod.rs#L710)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I my head it's the same: is y even.
But you are probably right. is_y_even is clearer. You can rename it if you want.
</blockquote></details>

How is '`y_parity` the same as is_even?

also, note that this is not what is implemented in the code.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 710 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3554#-NZ6gDp5EDBPgxVhk5-b:-NZKIhQ06pi-3_JSE69-:b6861w) ([raw file](https://github.com/starkware-libs/cairo/blob/e6afeae594cdd1e6a626700a7b2b794fdb15ca81/crates/cairo-lang-runner/src/casm_run/mod.rs#L710)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

How is '`y_parity` the same as is_even?

also, note that this is not what is implemented in the code.
</blockquote></details>

I thought about renaming but I find it strange the the syscall uses the
y_parity terminology but the implementation uses is_even (with reversed polarity).

I think we should be consistent.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
done.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3554#-:-NZKJReWA1pz4E51pJ_y:b-7rl0jd)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3554)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 596 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3554#-NZMCRTbEl7hvqYpQuQ-:-NZMCRTbEl7hvqYpQuQ0:bku47yl) ([raw file](https://github.com/starkware-libs/cairo/blob/3eeb8663cd2862ffaf4777f588d501d83d779f20/crates/cairo-lang-runner/src/casm_run/mod.rs#L596)):*
> ```XML
>                     gas_counter,
>                     system_buffer.next_u256()?,
>                     system_buffer.next_felt252()?.is_odd(),
> ```

Please add next_bool - this will be the least confusing IMO.



_Code quote:_
```XML
next_felt252()
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3554)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 596 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3554#-NZMCRTbEl7hvqYpQuQ-:-NZPEm2H-mkvyO04rNJ3:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/3eeb8663cd2862ffaf4777f588d501d83d779f20/crates/cairo-lang-runner/src/casm_run/mod.rs#L596)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Please add next_bool - this will be the least confusing IMO.
</blockquote></details>

done.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3554)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1150 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3554#-NZPvWRZ5f1g-aqCsrWH:-NZPvWRZ5f1g-aqCsrWI:bjzz601) ([raw file](https://github.com/starkware-libs/cairo/blob/f936433dcd679711c25dbcbaf526e5244d129961/crates/cairo-lang-runner/src/casm_run/mod.rs#L1150)):*
> ```XML
>     gas_counter: &mut usize,
>     x: BigUint,
>     y_parity: bool,
> ```

y_parity is true if v is even. (see in recover_public_key_u32).
so if smaller is odd and y_parity is true (that is v is even), we should take greater.
Or simpler - change is_odd below to is_even.
I am still ok with renaming y_parity to is_y_even, or similar.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3554#-:-NZWROJo4cwh0V-DjGZ-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/starknet/secp256_trait.cairo` line 30 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3554#-NZWQ6M_5BuypUTSReCM:-NZWQ6M_5BuypUTSReCN:b-4bwunl) ([raw file](https://github.com/starkware-libs/cairo/blob/6bf11d455d895edd71022566f7b021b43975826c/corelib/src/starknet/secp256_trait.cairo#L30)):*
> ```Cairo
> /// Note:
> ///   Some places use non boolean values for v.
> ///   In that case, `recover_public_key_u32` may be a better match.
> ```

y_parity is the parity of r.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3554)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @yuvalsw)

___
*[`corelib/src/starknet/secp256_trait.cairo` line 30 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3554#-NZWQ6M_5BuypUTSReCM:-NZWTMUZ5oHHkLgM9eh2:bmyywjn) ([raw file](https://github.com/starkware-libs/cairo/blob/6bf11d455d895edd71022566f7b021b43975826c/corelib/src/starknet/secp256_trait.cairo#L30)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

y_parity is the parity of r.
</blockquote></details>

done, but I feel that there are too many details here.

**Pull request merged**
