### PR TITLE
Optimize derive(StorageAccess)

### PR DESCRIPTION
**Pull request by maciejka**
Optimises StorageAccess derivation. Generated code is very close and supposedly as efficient as hand writen implementation.
E.g.: StorageAccess impl for `EthAddress`:
```
impl StorageAccessEthAddress of starknet::StorageAccess::<EthAddress> {
    fn read(address_domain: u32, base: starknet::StorageBaseAddress) -> starknet::SyscallResult<EthAddress> {
        let address = starknet::StorageAccess::<felt252>::read(address_domain, base)?;
        starknet::SyscallResult::Ok(
            EthAddress {
                address,
            }
        )
    }
    fn write(address_domain: u32, base: starknet::StorageBaseAddress, value: EthAddress) -> starknet::SyscallResult<()> {
        starknet::StorageAccess::<felt252>::write(address_domain, base, value.address)?;
        starknet::SyscallResult::Ok(())
    }
    fn read_at_offset_internal(address_domain: u32, base: starknet::StorageBaseAddress, offset: u8) -> starknet::SyscallResult<EthAddress> {
        let address = starknet::StorageAccess::<felt252>::read_at_offset_internal(address_domain, base, offset)?;
        starknet::SyscallResult::Ok(
            EthAddress {
                address,
            }
        )
    }
    #[inline(always)]
    fn write_at_offset_internal(address_domain: u32, base: starknet::StorageBaseAddress, offset: u8, value: EthAddress) -> starknet::SyscallResult<()> {
        starknet::StorageAccess::<felt252>::write_at_offset_internal(address_domain, base, offset, value.address)?;
        starknet::SyscallResult::Ok(())
    }
    #[inline(always)]
    fn size_internal(value: EthAddress) -> u8 {
        starknet::StorageAccess::<felt252>::size_internal(value.address)
    }
}
```
and for `u256`:
```
impl StorageAccessu256 of starknet::StorageAccess::<u256> {
    fn read(address_domain: u32, base: starknet::StorageBaseAddress) -> starknet::SyscallResult<u256> {
        let low = starknet::StorageAccess::<u128>::read(address_domain, base)?;
        let mut current_offset = starknet::StorageAccess::<u128>::size_internal(low);
        let high = starknet::StorageAccess::<u128>::read_at_offset_internal(address_domain, base, current_offset)?;
        starknet::SyscallResult::Ok(
            u256 {
                low,
                high,
            }
        )
    }
    fn write(address_domain: u32, base: starknet::StorageBaseAddress, value: u256) -> starknet::SyscallResult<()> {
        starknet::StorageAccess::<u128>::write(address_domain, base, value.low)?;
        let mut current_offset = starknet::StorageAccess::<u128>::size_internal(value.low);
        starknet::StorageAccess::<u128>::write_at_offset_internal(address_domain, base, current_offset, value.high)?;
        starknet::SyscallResult::Ok(())
    }
    fn read_at_offset_internal(address_domain: u32, base: starknet::StorageBaseAddress, offset: u8) -> starknet::SyscallResult<u256> {
        let low = starknet::StorageAccess::<u128>::read_at_offset_internal(address_domain, base, offset)?;
        let mut current_offset = offset + starknet::StorageAccess::<u128>::size_internal(low);
        let high = starknet::StorageAccess::<u128>::read_at_offset_internal(address_domain, base, current_offset)?;
        starknet::SyscallResult::Ok(
            u256 {
                low,
                high,
            }
        )
    }
    #[inline(always)]
    fn write_at_offset_internal(address_domain: u32, base: starknet::StorageBaseAddress, offset: u8, value: u256) -> starknet::SyscallResult<()> {
        starknet::StorageAccess::<u128>::write_at_offset_internal(address_domain, base, offset, value.low)?;
        let mut current_offset = offset + starknet::StorageAccess::<u128>::size_internal(value.low);
        starknet::StorageAccess::<u128>::write_at_offset_internal(address_domain, base, current_offset, value.high)?;
        starknet::SyscallResult::Ok(())
    }
    #[inline(always)]
    fn size_internal(value: u256) -> u8 {
        starknet::StorageAccess::<u128>::size_internal(value.low) +
        starknet::StorageAccess::<u128>::size_internal(value.high)
    }
}
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3259)

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
add the `derive` for u256 here to prove this is just as good.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3259#-:-NWcPNY5AIA5amijPpYi:bqm7pyr)* status: 0 of 1 files reviewed, all discussions resolved

**Comment by maciejka** [comment]
> add the `derive` for u256 here to prove this is just as good.
> 
> > Reviewed all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3259#-:-NWcPNY5AIA5amijPpYi:bqm7pyr)_ status: 0 of 1 files reviewed, all discussions resolved

Done. There are some changes in sierra file for erc20.cairo. It is not clear to me whether it is just due to the different location of the implementation or something else. Would you please have a look?

**Review by orizi — COMMENTED** [review]
looks good

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3259#-:-NWfGp7pBbHxRgfdn9qc:b-47fafm)* status: 1 of 6 files reviewed, all discussions resolved

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3259#-:-NWfH-PB0OAjlmCoFGZs:bnfp4nl)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @maciejka)

___
*[`corelib/src/starknet/storage_access.cairo` line 356 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3259#-NWfGwMd4vaBH1r2E6DP:-NWfGwMd4vaBH1r2E6DQ:b32vhw) ([raw file](https://github.com/starkware-libs/cairo/blob/8a89587bcee9539e52712d1d92994d62ef9e3576/corelib/src/starknet/storage_access.cairo#L356)):*
> ```Cairo
> //             + StorageAccess::<u128>::size_internal(value.high)
> //     }
> // }
> ```

:)

**Review by orizi — APPROVED** [review]
> Reviewed 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3259)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciejka)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3259#-:-NWjwi7hCM6QO5z5WeHy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciejka)

**Review by orizi — APPROVED** [review]
just fix conflicts (most probably just running `CAIRO_FIX_TESTS=1 cargo t -p cairo-lang-plugins erc20` and we'll merge :)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3259#-:-NWk8POQ8egbuidKogIO:b-k86dtk)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciejka)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3259#-:-NWlQwac5pxZgTi3Q8IV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciejka)

**Pull request merged**
