### PR TITLE
Add fixed size array pattern lowering.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5169)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5169)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 673 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5169#-Nro7F6J2MIF4eZ4U94t:-Nro7F6J2MIF4eZ4U94u:b-5qd341) ([raw file](https://github.com/starkware-libs/cairo/blob/af65d380b91d17ccd68507a5890ea70a103a74c2/crates/cairo-lang-lowering/src/lower/mod.rs#L673)):*
> ```XML
>             }
>         }
>         semantic::Pattern::FixedSizeArray(semantic::PatternFixedSizeArray {
> ```

see if you can extract some logic from tuple - as this is very similar.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5169)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 673 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5169#-Nro7F6J2MIF4eZ4U94t:-Ns2gXAeB5ivNi4yGTQQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/af65d380b91d17ccd68507a5890ea70a103a74c2/crates/cairo-lang-lowering/src/lower/mod.rs#L673)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

see if you can extract some logic from tuple - as this is very similar.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5169)* status: 3 of 9 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 643 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5169#-Ns2iGJL4WuWMWfzahs-:-Ns2iGJL4WuWMWfzahs0:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/91ba6141f16812bb634cda0dfd4c52e8af55f981/crates/cairo-lang-lowering/src/lower/mod.rs#L643)):*
> ```XML
>         }) => {
>             lower_tuple_like_pattern_helper(ctx, builder, lowered_expr, &elements_patterns, ty)?;
>         }
> ```





_Suggestion:_
```XML
        semantic::Pattern::Tuple(semantic::PatternTuple { field_patterns: pattern, ty, .. }) |
        semantic::Pattern::FixedSizeArray(semantic::PatternFixedSizeArray {
            elements_patterns: pattern,
            ty,
            ..
        }) => {
            lower_tuple_like_pattern_helper(ctx, builder, lowered_expr, &patterns, ty)?;
        }
```

**Review by orizi — COMMENTED** [review]
> Reviewed 5 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5169)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5169)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5169)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 643 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5169#-Ns2iGJL4WuWMWfzahs-:-Ns2j-9K-tXPr6Ho9Dvx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/91ba6141f16812bb634cda0dfd4c52e8af55f981/crates/cairo-lang-lowering/src/lower/mod.rs#L643)):*
> ```XML
>         }) => {
>             lower_tuple_like_pattern_helper(ctx, builder, lowered_expr, &elements_patterns, ty)?;
>         }
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5169#-:-Ns2kDVU2dpvDwQw8bcT:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5169)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
