### PR TITLE
Added assert_eq and assert_ne

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3129)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3129#-:-NVdvwcV007qAqLC99Q7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3129)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3129)* status: 6 of 30 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`corelib/src/test/test_utils.cairo` line 5 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3129#-NVi8KtT4z7zdnlm77GB:-NVi8KtT4z7zdnlm77GC:b78km5l) ([raw file](https://github.com/starkware-libs/cairo/blob/925765b22c5ad2006fbd4e49875cce4835029f0e/corelib/src/test/test_utils.cairo#L5)):*
> ```Cairo
>     if a != b {
>         panic_with_felt252(err_code)
>     }
> ```

why not?



_Suggestion:_
```Cairo
    assert(a != b, err_code)
```

**Review by orizi — COMMENTED** [review]
> Reviewed 15 of 24 files at r3, 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3129)* status: 28 of 30 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @yuvalsw)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 24 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3129)* status: 29 of 30 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3129)* status: 28 of 30 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`corelib/src/test/test_utils.cairo` line 5 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3129#-NVi8KtT4z7zdnlm77GB:-NVi9QKO4CaNzTF3XWEZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/925765b22c5ad2006fbd4e49875cce4835029f0e/corelib/src/test/test_utils.cairo#L5)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why not?
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3129)* status: 29 of 30 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 2 files at r6, 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3129)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
