### PR TITLE
Add types to ABI.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2314)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2314)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/abi.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2314#-NPOOT271rFtO4faIStq:-NPOOT271rFtO4faIStr:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/75a9ae0b9d855a8ad6f6165e88a96d0d0affbea1/crates/cairo-lang-starknet/src/abi.rs#L143)):*
> ```XML
>     }
> 
>     fn add_concrete_type(
> ```

doc



_Code quote:_
```XML
    fn add_concrete_type(
```
___
*[`crates/cairo-lang-starknet/src/abi.rs` line 173 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2314#-NPONW4e0CJaETwIPX0i:-NPONW4e0CJaETwIPX0j:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/75a9ae0b9d855a8ad6f6165e88a96d0d0affbea1/crates/cairo-lang-starknet/src/abi.rs#L173)):*
> ```XML
>     let mut res = vec![];
>     for (name, member) in
>         db.concrete_struct_members(id).map_err(|_| ABIError::UnexpectedType)?.iter()
> ```





_Suggestion:_
```XML
    Ok(
        db.concrete_struct_members(id).map_err(|_| ABIError::UnexpectedType)?.iter()
        .map(|(name, member)|StructMember { name: name.to_string(), ty: member.ty.format(db) })
        .collect()
    )
```
___
*[`crates/cairo-lang-starknet/src/abi.rs` line 192 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2314#-NPONrQ44JqWcKRLHqZk:-NPONrQ44JqWcKRLHqZl:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/75a9ae0b9d855a8ad6f6165e88a96d0d0affbea1/crates/cairo-lang-starknet/src/abi.rs#L192)):*
> ```XML
>             name: name.to_string(),
>             ty: db
>                 .concrete_enum_variant(
> ```





_Suggestion:_
```XML
    db.enum_variants(generic_id).map_err(|_| ABIError::UnexpectedType)?.iter()
       .map(|(name, variant_id)|Ok(EnumVariant {
            name: name.to_string(),
            ty: db
                .concrete_enum_variant(
                    id,
                    &db.variant_semantic(generic_id, *variant_id)
                        .map_err(|_| ABIError::UnexpectedType)?,
                )
                .map_err(|_| ABIError::UnexpectedType)?
                .ty
                .format(db),
        }))
    }.collect::<Result<Vec<_>,_>>()
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2314)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2314)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/abi.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2314#-NPOOT271rFtO4faIStq:-NPQw7Wm7-o304KOdQOA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/75a9ae0b9d855a8ad6f6165e88a96d0d0affbea1/crates/cairo-lang-starknet/src/abi.rs#L143)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/abi.rs` line 173 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2314#-NPONW4e0CJaETwIPX0i:-NPQw44IDL1-rx7nNXme:bz4bz6i) ([raw file](https://github.com/starkware-libs/cairo/blob/75a9ae0b9d855a8ad6f6165e88a96d0d0affbea1/crates/cairo-lang-starknet/src/abi.rs#L173)):*
> ```XML
>     let mut res = vec![];
>     for (name, member) in
>         db.concrete_struct_members(id).map_err(|_| ABIError::UnexpectedType)?.iter()
> ```

I prefer to keep it the way it is.
___
*[`crates/cairo-lang-starknet/src/abi.rs` line 192 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2314#-NPONrQ44JqWcKRLHqZk:-NPQvtV-DvSEiS7A8inD:bz4bz6i) ([raw file](https://github.com/starkware-libs/cairo/blob/75a9ae0b9d855a8ad6f6165e88a96d0d0affbea1/crates/cairo-lang-starknet/src/abi.rs#L192)):*
> ```XML
>             name: name.to_string(),
>             ty: db
>                 .concrete_enum_variant(
> ```

I prefer to keep it the way it is.



_Code quote:_
```XML
res.push(EnumVariant {
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2314)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/abi.rs` line 173 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2314#-NPONW4e0CJaETwIPX0i:-NPQzjN0DMGFxus_1HFQ:b-6qyeis) ([raw file](https://github.com/starkware-libs/cairo/blob/75a9ae0b9d855a8ad6f6165e88a96d0d0affbea1/crates/cairo-lang-starknet/src/abi.rs#L173)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I prefer to keep it the way it is.
</blockquote></details>

this is the rust idiom for creating collections - please give an explaination.
___
*[`crates/cairo-lang-starknet/src/abi.rs` line 192 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2314#-NPONrQ44JqWcKRLHqZk:-NPQztvB5ctcvUxqmbYI:b-7ropln) ([raw file](https://github.com/starkware-libs/cairo/blob/75a9ae0b9d855a8ad6f6165e88a96d0d0affbea1/crates/cairo-lang-starknet/src/abi.rs#L192)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I prefer to keep it the way it is.
</blockquote></details>

ditto

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2314)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2314)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/abi.rs` line 173 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2314#-NPONW4e0CJaETwIPX0i:-NPR2DfmBq_lMQFouj5L:berizs7) ([raw file](https://github.com/starkware-libs/cairo/blob/75a9ae0b9d855a8ad6f6165e88a96d0d0affbea1/crates/cairo-lang-starknet/src/abi.rs#L173)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is the rust idiom for creating collections - please give an explaination.
</blockquote></details>

It would making adding and offset to StructMember
or just adding an eprint there more difficult.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2314)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/abi.rs` line 173 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2314#-NPONW4e0CJaETwIPX0i:-NPRLbOS6H-t0dlsEa4e:bi60905) ([raw file](https://github.com/starkware-libs/cairo/blob/75a9ae0b9d855a8ad6f6165e88a96d0d0affbea1/crates/cairo-lang-starknet/src/abi.rs#L173)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

It would making adding and offset to StructMember
or just adding an eprint there more difficult.
</blockquote></details>

This is already supported well enough while still using the iterators (enumerate and so on)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2314)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/abi.rs` line 173 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2314#-NPONW4e0CJaETwIPX0i:-NPSD-fB9heV2-dI86Ke:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/75a9ae0b9d855a8ad6f6165e88a96d0d0affbea1/crates/cairo-lang-starknet/src/abi.rs#L173)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

This is already supported well enough while still using the iterators (enumerate and so on)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/abi.rs` line 192 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2314#-NPONrQ44JqWcKRLHqZk:-NPSD0OcETZ8pbkgOlVS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/75a9ae0b9d855a8ad6f6165e88a96d0d0affbea1/crates/cairo-lang-starknet/src/abi.rs#L192)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/abi.rs` line 189 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2314#-NPSD33rCmWuPdmZPTP9:-NPSD33rCmWuPdmZPTPA:b-2chg0i) ([raw file](https://github.com/starkware-libs/cairo/blob/e662d952bd4c6cc925077d3b9808de33435317f9/crates/cairo-lang-starknet/src/abi.rs#L189)):*
> ```XML
> 
>     db.enum_variants(generic_id)
>         .map_err(|_| ABIError::UnexpectedType)?
> ```

can I avoid this somehow?



_Code quote:_
```XML
.map_err(|_| ABIError::UnexpectedType)?
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2314#-:-NPSDvzK9aaN8a5KoVI6:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2314)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/abi.rs` line 189 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2314#-NPSD33rCmWuPdmZPTP9:-NPSjtPa01FiPm3S2U9D:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/e662d952bd4c6cc925077d3b9808de33435317f9/crates/cairo-lang-starknet/src/abi.rs#L189)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

can I avoid this somehow?
</blockquote></details>

done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2314#-:-NPSkPPN6xdr_WjvhJzz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
