### PR TITLE
Add starknet_libfunc_cost_base.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1299)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1299#-:-NJ4FlqnAo5PYCsUMeUT:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/sierra_gas/src/starknet_libfunc_cost_base.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1299#-NJ4FcjHBr8OkEl2UzxL:-NJ4FcjHBr8OkEl2UzxM:b-ly5nxn) ([raw file](https://github.com/starkware-libs/cairo/blob/9b36590811a1dc5aa701450faa1654e39a3ef765/crates/sierra_gas/src/starknet_libfunc_cost_base.rs#L12)):*
> ```XML
> ) -> Vec<Ops::CostType> {
>     match libfunc {
>         StarkNetConcreteLibFunc::StorageRead(_) => vec![ops.const_cost(50)],
> ```

I assume you may want to use a variable here (instead of a constant 50) at some point?
if so - add a todo



_Code quote:_
```XML
vec![ops.const_cost(50)]
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1299)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/sierra_gas/src/starknet_libfunc_cost_base.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1299#-NJ4FcjHBr8OkEl2UzxL:-NJ4I4Zc0uk0Qj74VngX:bq57e4q) ([raw file](https://github.com/starkware-libs/cairo/blob/9b36590811a1dc5aa701450faa1654e39a3ef765/crates/sierra_gas/src/starknet_libfunc_cost_base.rs#L12)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I assume you may want to use a variable here (instead of a constant 50) at some point?
if so - add a todo
</blockquote></details>

I have no idea what we want here.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1299)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1299)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/sierra_gas/src/starknet_libfunc_cost_base.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1299#-NJ4JyhiCVLV5eQNihU6:-NJ4JyhiCVLV5eQNihU7:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/33ed08f52e05d11688e58dfad8ddced8e81e4945/crates/sierra_gas/src/starknet_libfunc_cost_base.rs#L12)):*
> ```XML
> ) -> Vec<Ops::CostType> {
>     match libfunc {
>         // TODO: Do we want to use a fixed gas cost for storage?
> ```

.



_Suggestion:_
```XML
// TODO(Ilya): Consider adding a `CostTokenType::StorageRead` or make storage read a branch.
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1299)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/sierra_gas/src/starknet_libfunc_cost_base.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1299#-NJ4JyhiCVLV5eQNihU6:-NJ4KUSX7q_sOZdT1SXv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/33ed08f52e05d11688e58dfad8ddced8e81e4945/crates/sierra_gas/src/starknet_libfunc_cost_base.rs#L12)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1299#-:-NJ4KuvkEz9RJgFLzWdK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1299)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
