### PR TITLE
Add stroage_address_try_from_felt.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2341)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2341)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`tests/e2e_test_data/libfuncs/starknet/storage` line 197 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2341#-NPWMEzQ0Ie-x8kt7VpC:-NPWMEzRAlbVLmjt84oB:b1h7j59) ([raw file](https://github.com/starkware-libs/cairo/blob/813b6dad255dea9a3dab780e0b7b34d3ad29360f/tests/e2e_test_data/libfuncs/starknet/storage#L197)):*
> ```
> //! > cairo
> fn foo(address: felt) -> Option::<starknet::StorageAddress> {
>     starknet::storage_address_try_from_felt(address)
> ```

is this test needed?

It is pretty much the same as contract_address_try_from_felt.

I could add a cairo level test the panics



_Code quote:_
```
  starknet::storage_address_try_from_felt(address)
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2341)* status: 2 of 9 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/starknet/storage_access.cairo` line 34 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2341#-NPWOjRN7UgC9TqUD9YU:-NPWOjRN7UgC9TqUD9YV:b-mfupac) ([raw file](https://github.com/starkware-libs/cairo/blob/813b6dad255dea9a3dab780e0b7b34d3ad29360f/corelib/src/starknet/storage_access.cairo#L34)):*
> ```Cairo
> extern fn storage_address_try_from_felt(
>     address: felt
> ) -> Option<StorageAddress> implicits(RangeCheck) nopanic;
> ```

is there a use case that requires this?
otherwise i would rather not just add it



_Code quote:_
```Cairo
extern fn storage_address_try_from_felt(
    address: felt
) -> Option<StorageAddress> implicits(RangeCheck) nopanic;
```
___
*[`tests/e2e_test_data/libfuncs/starknet/storage` line 197 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2341#-NPWOJA-DEL8IvogJOnL:-NPWOJA-DEL8IvogJOnM:b-bsq288) ([raw file](https://github.com/starkware-libs/cairo/blob/813b6dad255dea9a3dab780e0b7b34d3ad29360f/tests/e2e_test_data/libfuncs/starknet/storage#L197)):*
> ```
> //! > cairo
> fn foo(address: felt) -> Option::<starknet::StorageAddress> {
>     starknet::storage_address_try_from_felt(address)
> ```

add a test - don't remove an existing one.



_Code quote:_
```
    starknet::storage_address_try_from_felt(address)
```
___
*[`tests/e2e_test_data/libfuncs/starknet/storage` line 197 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2341#-NPWMEzQ0Ie-x8kt7VpC:-NPWOQLh7SwyFuaW1o81:byr24yj) ([raw file](https://github.com/starkware-libs/cairo/blob/813b6dad255dea9a3dab780e0b7b34d3ad29360f/tests/e2e_test_data/libfuncs/starknet/storage#L197)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

is this test needed?

It is pretty much the same as contract_address_try_from_felt.

I could add a cairo level test the panics

</blockquote></details>

we can't say for certain these are the same - so having different tests is needed.

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/starknet/storage_access.cairo` line 34 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2341#-NPWOjRN7UgC9TqUD9YU:-NPWOxvYAH0W9pnbjm4z:bb9d5uk) ([raw file](https://github.com/starkware-libs/cairo/blob/813b6dad255dea9a3dab780e0b7b34d3ad29360f/corelib/src/starknet/storage_access.cairo#L34)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is there a use case that requires this?
otherwise i would rather not just add it
</blockquote></details>

I want to be able to pass a StorageAddress to an entry point.
I'll need a deserialize function for that.

**Review by orizi — COMMENTED** [review]
> Reviewed 7 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2341)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2341)* status: 7 of 10 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`tests/e2e_test_data/libfuncs/starknet/storage` line 197 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2341#-NPWOJA-DEL8IvogJOnL:-NPWYddi5fpO3h2gAeLI:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/813b6dad255dea9a3dab780e0b7b34d3ad29360f/tests/e2e_test_data/libfuncs/starknet/storage#L197)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add a test - don't remove an existing one.
</blockquote></details>

done

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2341#-:-NPW_2QQ2H5R89sgBJSU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
