### PR TITLE
Fix optimize_remappings to ignore unreachable blocks.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4808)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4808)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/remappings.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4808#-NoCLqjo5yqXVE00qfyV:-NoCLqjo5yqXVE00qfyW:b8zxehh) ([raw file](https://github.com/starkware-libs/cairo/blob/31f96d91dc046407084a59a86af1ebf6f8862cf3/crates/cairo-lang-lowering/src/optimizations/remappings.rs#L18)):*
> ```XML
> 
> #[derive(Default)]
> struct Context {
> ```

doc (I realize it wasn't before)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4808)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/remappings.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4808#-NoCLqjo5yqXVE00qfyV:-NoCM1QzEOkgf7BtXJMa:b-5vj6uj) ([raw file](https://github.com/starkware-libs/cairo/blob/31f96d91dc046407084a59a86af1ebf6f8862cf3/crates/cairo-lang-lowering/src/optimizations/remappings.rs#L18)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc (I realize it wasn't before)
</blockquote></details>

(functions as well)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4808)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/remappings.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4808#-NoCgGw-6ieMg3XvdQPu:-NoCgGw-6ieMg3XvdQPv:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5388075be73a899af8d32e86eac16f96b4a8859c/crates/cairo-lang-lowering/src/optimizations/remappings.rs#L18)):*
> ```XML
> 
> /// Visits all the reachable remappings in the function, calls f on each one and returns a vector
> /// indicating which blocks are reachable.
> ```





_Suggestion:_
```XML
/// Visits all the reachable remappings in the function, calls `f` on each one and returns a vector
/// indicating which blocks are reachable.
```
___
*[`crates/cairo-lang-lowering/src/optimizations/remappings.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4808#-NoCgOoQDJ5rJRv_3hVl:-NoCgOoQDJ5rJRv_3hVm:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5388075be73a899af8d32e86eac16f96b4a8859c/crates/cairo-lang-lowering/src/optimizations/remappings.rs#L49)):*
> ```XML
>     dest_to_srcs: HashMap<VariableId, Vec<VariableId>>,
>     /// Cache of a mapping from variable id in the old lowering to variable id in the new lowering.
>     /// This mapping is built on demand
> ```





_Suggestion:_
```XML
    /// Cache of a mapping from variable id in the old lowering to variable id in the new lowering.
    /// This mapping is built on demand.
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4808#-:-NoCkcVk8KJPOothOP6u:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4808)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/remappings.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4808#-NoCgGw-6ieMg3XvdQPu:-NoCiB6p2YX15mpFGXP3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5388075be73a899af8d32e86eac16f96b4a8859c/crates/cairo-lang-lowering/src/optimizations/remappings.rs#L18)):*
> ```XML
> 
> /// Visits all the reachable remappings in the function, calls f on each one and returns a vector
> /// indicating which blocks are reachable.
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/optimizations/remappings.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4808#-NoCgOoQDJ5rJRv_3hVl:-NoCiDcx9BZPjPL1iYOc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5388075be73a899af8d32e86eac16f96b4a8859c/crates/cairo-lang-lowering/src/optimizations/remappings.rs#L49)):*
> ```XML
>     dest_to_srcs: HashMap<VariableId, Vec<VariableId>>,
>     /// Cache of a mapping from variable id in the old lowering to variable id in the new lowering.
>     /// This mapping is built on demand
> ```

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4808)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
