### PR TITLE
Support constants in semantic.

### PR DESCRIPTION
**Pull request by liorgold2**
commit-id:67708f86

---

**Stack**:
- #1837
- #1836
- #1827
- #1822
- #1821
- #1820 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 11 files at r1, 3 of 5 files at r2, 1 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1820#-:-NMK2-fA4vyrR0k7NV2y:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 435 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1820#-NMJyza33d7DrR7hd600:-NMJyza33d7DrR7hd601:b-rj2z6b) ([raw file](https://github.com/starkware-libs/cairo/blob/52ac28dca44969f4fb8f5e9b2bf44fb76ec46632/crates/cairo-lang-language-server/src/lib.rs#L435)):*
> ```XML
>             let (module_id, file_index, stable_ptr) = match item {
>                 ResolvedGenericItem::Constant(_) => {
>                     unimplemented!("Constant definitions are not supported yet.");
> ```

Why not just implement it?
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1198 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1820#-NMK1RMa29NfrTrn1pvk:-NMK1RMa29NfrTrn1pvl:bijxzr7) ([raw file](https://github.com/starkware-libs/cairo/blob/52ac28dca44969f4fb8f5e9b2bf44fb76ec46632/crates/cairo-lang-semantic/src/expr/compute.rs#L1198)):*
> ```XML
> 
> /// Resolves a variable or a constant given a context and a path expression.
> fn resolve_variable_or_constant(
> ```

The function name is weird, and seems to indicate the implementation, not the purpose.
Maybe something like resolve_expr_path?
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1216 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1820#-NMK0v9y066iRL1lEAE-:-NMK0v9z0So44yrWxY65:b-e2ufgo) ([raw file](https://github.com/starkware-libs/cairo/blob/52ac28dca44969f4fb8f5e9b2bf44fb76ec46632/crates/cairo-lang-semantic/src/expr/compute.rs#L1216)):*
> ```XML
>                 return Ok(res);
>             }
>             // Check if this is a constant.
> ```

Do this outside the match. I think the logic should look like:
try_resolve_local().or_else(try_resolve_item_path), or something similar.

Technically, we could also support generic constants here.

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1820)* status: 10 of 12 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 435 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1820#-NMJyza33d7DrR7hd600:-NMK6tT2B1yjjjOPA7Kl:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/52ac28dca44969f4fb8f5e9b2bf44fb76ec46632/crates/cairo-lang-language-server/src/lib.rs#L435)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Why not just implement it?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1198 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1820#-NMK1RMa29NfrTrn1pvk:-NMK74S-6pz5B0arImRV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/52ac28dca44969f4fb8f5e9b2bf44fb76ec46632/crates/cairo-lang-semantic/src/expr/compute.rs#L1198)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

The function name is weird, and seems to indicate the implementation, not the purpose.
Maybe something like resolve_expr_path?
</blockquote></details>

Done.

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1820)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1820)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1820)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1216 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1820#-NMK0v9y066iRL1lEAE-:-NML4nWU3U2jfBO72Dum:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/52ac28dca44969f4fb8f5e9b2bf44fb76ec46632/crates/cairo-lang-semantic/src/expr/compute.rs#L1216)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Do this outside the match. I think the logic should look like:
try_resolve_local().or_else(try_resolve_item_path), or something similar.

Technically, we could also support generic constants here.
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1820#-:-NMMmlYI1NEwW_zijdK7:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

**Review by spapinistarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1820)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
