### PR TITLE
Array methods

### PR DESCRIPTION
**Pull request by spapinistarkware**
commit-id:6c88a709

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 24 of 24 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1911#-:-NMe1IsF1wL_DnU7FUCx:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`corelib/array.cairo` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1911#-NMe18yD5xvV2HCR-QqX:-NMe18yEEzNB6btBT5jP:b-38bhzz) ([raw file](https://github.com/starkware-libs/cairo/blob/4339d25517ce44353d0b13833b63dfe54bac6608/corelib/array.cairo#L36)):*
> ```Cairo
>         array_get(ref self, index)
>     }
>     fn at(ref self: Array::<T>, index: u128) -> T {
> ```

inline?



_Code quote:_
```Cairo
    fn at(ref self: Array::<T>, index: u128) -> T {
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1911)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/array.cairo` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1911#-NMe18yD5xvV2HCR-QqX:-NMe2eFq4R6ULe5kkTAU:b-d9s90f) ([raw file](https://github.com/starkware-libs/cairo/blob/4339d25517ce44353d0b13833b63dfe54bac6608/corelib/array.cairo#L36)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

inline?
</blockquote></details>

It's panicable.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1911)* status: 16 of 24 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`corelib/array.cairo` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1911#-NMe18yD5xvV2HCR-QqX:-NMe3wWs9ReIlVxWejpR:b3pozqw) ([raw file](https://github.com/starkware-libs/cairo/blob/4339d25517ce44353d0b13833b63dfe54bac6608/corelib/array.cairo#L36)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

It's panicable.
</blockquote></details>

that shouldn't be an issue - you just need the function itself to not have an early return - this directly returns the wrapped data - doesn't it?

**Review by orizi — COMMENTED** [review]
> Reviewed 4 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1911)* status: 20 of 24 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1911)* status: 20 of 24 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/array.cairo` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1911#-NMe18yD5xvV2HCR-QqX:-NMe6_9_1vTX_3hdv_iH:bx51ulz) ([raw file](https://github.com/starkware-libs/cairo/blob/4339d25517ce44353d0b13833b63dfe54bac6608/corelib/array.cairo#L36)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

that shouldn't be an issue - you just need the function itself to not have an early return - this directly returns the wrapped data - doesn't it?
</blockquote></details>

The panic phase transform calls to may_panic functions into a match. ther eis not return value optimization there.

**Review by orizi — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1911)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
