### PR TITLE
Add compute_target_values().

### PR DESCRIPTION
**Pull request by liorgold2**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4152)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4152)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-gas/src/compute_costs.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4152#-NfLMsTt5eArz0LSoe77:-NfLMsTt5eArz0LSoe78:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/0e4b813f371923b55b1ae76467f94067bc1c626c/crates/cairo-lang-sierra-gas/src/compute_costs.rs#L27)):*
> ```XML
>     std::fmt::Debug + Default + Clone + Eq + Add<Output = Self> + Sub<Output = Self>
> {
>     fn min2(value1: &Self, value2: &Self) -> Self;
> ```

doc

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4152)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-gas/src/compute_costs.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4152#-NfLMsTt5eArz0LSoe77:-NfPZKDB9A52lOJfCitV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0e4b813f371923b55b1ae76467f94067bc1c626c/crates/cairo-lang-sierra-gas/src/compute_costs.rs#L27)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4152)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-gas/src/compute_costs.rs` line 473 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4152#-NfP_N5JBhgTUp8fw-kl:-NfP_N5JBhgTUp8fw-km:b-8eb0ov) ([raw file](https://github.com/starkware-libs/cairo/blob/df725d0fc866e011e4949da33b92e45cf603c424/crates/cairo-lang-sierra-gas/src/compute_costs.rs#L473)):*
> ```XML
>         // Pass the excess to the branches.
>         for (branch_info, _branch_cost, _branch_requirement) in
>             zip_eq3(&invocation.branches, &libfunc_cost, branch_requirements)
> ```

add a todo here to make it clear why not:



_Suggestion:_
```XML
        // Pass the excess to the branches.
        for branch_info in &invocation.branches
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4152#-:-NfPa0LX7PVZoymwwR0I:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
