### PR TITLE
Add build_storage_read

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1256)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1256)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/sierra_to_casm/src/invocations/storage.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1256#-NIkkJca-Ljgxsa0IMV7:-NIkkJca-Ljgxsa0IMV8:b-k91gvm) ([raw file](https://github.com/starkware-libs/cairo/blob/4ca504a730a6303aab03f9b91d0ea1a0a8d94479/crates/sierra_to_casm/src/invocations/storage.rs#L13)):*
> ```XML
> };
> 
> /// Builds instructions for Sierra struct operations.
> ```

wrong doc.



_Code quote:_
```XML
/// Builds instructions for Sierra struct operations.
```
___
*[`crates/sierra_to_casm/src/invocations/storage.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1256#-NIkkO_I6qDu1edGmjoU:-NIkkO_I6qDu1edGmjoV:b-zg8z6f) ([raw file](https://github.com/starkware-libs/cairo/blob/4ca504a730a6303aab03f9b91d0ea1a0a8d94479/crates/sierra_to_casm/src/invocations/storage.rs#L14)):*
> ```XML
> 
> /// Builds instructions for Sierra struct operations.
> pub fn build_storage_read(
> ```

any reason not to be in the starknet file?



_Code quote:_
```XML
build_storage_read
```

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1256#-:-NIkkkVOBpj5h_04Nl5o:bnfp4nl)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1256)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1256)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/sierra_to_casm/src/invocations/storage.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1256#-NIkkO_I6qDu1edGmjoU:-NIkmPJG3q3z0MalNp-C:bo43uxd) ([raw file](https://github.com/starkware-libs/cairo/blob/4ca504a730a6303aab03f9b91d0ea1a0a8d94479/crates/sierra_to_casm/src/invocations/storage.rs#L14)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

any reason not to be in the starknet file?
</blockquote></details>

I prefer to split it as I think there is going to be quite a bit of logic the starknet file.

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1256)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1256)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`crates/sierra_to_casm/src/invocations/storage.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1256#-NIkkJca-Ljgxsa0IMV7:-NIksCxq-E0aRvlouXH5:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/4ca504a730a6303aab03f9b91d0ea1a0a8d94479/crates/sierra_to_casm/src/invocations/storage.rs#L13)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

wrong doc.
</blockquote></details>

done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1256)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
