### PR TITLE
added Fn trait

### PR DESCRIPTION
**Pull request by TomerStarkware**

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 15 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6659)* status: 14 of 16 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1949 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6659#-OBdlqZN9ko7-qMhUdvv:-OBdlqZN9ko7-qMhUdvw:bxahu2p) ([raw file](https://github.com/starkware-libs/cairo/blob/50a74a108bb755c811fd86da6ab6274905d6d078/crates/cairo-lang-lowering/src/lower/mod.rs#L1949)):*
> ```XML
>         )
>         .map_err(LoweringFlowError::Failed)?;
>     }
> ```

we need both?



_Suggestion:_
```XML
    add_closure_call_function(
        ctx,
        expr,
        builder.semantics.closures.get(&capture_var_usage.var_id).unwrap(),
        if ctx.variables[capture_var_usage.var_id].copyable.is_ok() {
            semantic::corelib::fn_trait(ctx.db.upcast())
        } else {
            semantic::corelib::fn_once_trait(ctx.db.upcast())
        },
    )
```
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1806 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6659#-OBdmsYl0cJqCt0TIQYg:-OBdmsYl0cJqCt0TIQYh:bsvs8k7) ([raw file](https://github.com/starkware-libs/cairo/blob/50a74a108bb755c811fd86da6ab6274905d6d078/crates/cairo-lang-semantic/src/items/imp.rs#L1806)):*
> ```XML
>             let ret_ty = db.trait_type_by_name(trait_id, "Output".into()).unwrap().unwrap();
> 
>             (
> ```

this is very unclear - use the functions properly, even if it means splitting `handle_mem_trait` into another closure.
___
*[`corelib/src/ops/function.cairo` line 33 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6659#-OBdl4B1Ec67xm5SdbFK:-OBdl4B25m5i7c6w4nM7:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/50a74a108bb755c811fd86da6ab6274905d6d078/corelib/src/ops/function.cairo#L33)):*
> ```Cairo
> 
> pub trait Fn<T, Args> {
>     /// The returned type after the call operator is used.
> ```





_Suggestion:_
```Cairo
/// Instances of `Fn` can be called multiple times.
///
/// `Fn` is implemented automatically by closures that capture only copyable variables.
pub trait Fn<T, Args> {
    /// The returned type after the call operator is used.
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6659)* status: 14 of 16 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1949 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6659#-OBdlqZN9ko7-qMhUdvv:-OBeJD0u6h87rDZ-GMiy:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/50a74a108bb755c811fd86da6ab6274905d6d078/crates/cairo-lang-lowering/src/lower/mod.rs#L1949)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

we need both?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1806 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6659#-OBdmsYl0cJqCt0TIQYg:-OBeM7gn9TjJn12lvk6y:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/50a74a108bb755c811fd86da6ab6274905d6d078/crates/cairo-lang-semantic/src/items/imp.rs#L1806)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is very unclear - use the functions properly, even if it means splitting `handle_mem_trait` into another closure.
</blockquote></details>

Done.
___
*[`corelib/src/ops/function.cairo` line 33 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6659#-OBdl4B1Ec67xm5SdbFK:-OBeIwFw2ZhvJCunaOW4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/50a74a108bb755c811fd86da6ab6274905d6d078/corelib/src/ops/function.cairo#L33)):*
> ```Cairo
> 
> pub trait Fn<T, Args> {
>     /// The returned type after the call operator is used.
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6659#-:-OBeWR5k0mDbNB8IAooH:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 7 of 16 files at r1, 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6659)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6659)* status: all files reviewed, 3 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 991 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6659#-OCCv9VFBduLSNqqPVA8:-OCCv9VFBduLSNqqPVA9:boq1qc1) ([raw file](https://github.com/starkware-libs/cairo/blob/72d0fba9c1beb98ba0bc6a48788d40e3e39187d5/crates/cairo-lang-semantic/src/expr/inference.rs#L991)):*
> ```XML
>                     // We return `SolutionSet::Ambiguous` here to indicate that more
>                     // information is needed.
>                     if !matches!(ty.lookup_intern(inference.db), TypeLongId::Closure(_))
> ```

can you document the change?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1775 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6659#-OCCxRFd6RliN7jmqqz3:-OCCxRFd6RliN7jmqqz4:b-doeirn) ([raw file](https://github.com/starkware-libs/cairo/blob/72d0fba9c1beb98ba0bc6a48788d40e3e39187d5/crates/cairo-lang-semantic/src/items/imp.rs#L1775)):*
> ```XML
> 
>             let id = db.trait_generic_params(trait_id).unwrap().first().unwrap().id();
>             let param: GenericParam = GenericParam::NegImpl(GenericParamImpl {
> ```

document.
fn_once_trait is generated only if there is no fn_trait



_Suggestion:_
```XML
neg_impl_param
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1807 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6659#-OCCzIz4BbDHxr2NcyvF:-OCCzIz4BbDHxr2NcyvG:b-kl43c0) ([raw file](https://github.com/starkware-libs/cairo/blob/72d0fba9c1beb98ba0bc6a48788d40e3e39187d5/crates/cairo-lang-semantic/src/items/imp.rs#L1807)):*
> ```XML
>             (
>                 concrete_trait,
>                 mem_trait_generic_params(copy_trait(db), None),
> ```

document



_Code quote:_
```XML
   mem_trait_generic_params(copy_trait(db), None),
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6659)* status: 14 of 16 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1804 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6659#-OCCrPk15dmNiAXOx5Ft:-OCDtRFB5xP3BNP3RBYe:b-7mqz91) ([raw file](https://github.com/starkware-libs/cairo/blob/72d0fba9c1beb98ba0bc6a48788d40e3e39187d5/crates/cairo-lang-lowering/src/lower/mod.rs#L1804)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

When does this happen?
</blockquote></details>

It will happen if we pass fn_once_trait and the closure is fn_trait (it would have a regular impl and a generated one),
but currently, we check if the closure is copiable in the call to `add\_closure\_call\_function`, so this cannot actually happen.
___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 863 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6659#-OCCt1iP3YKJNV74kGCN:-OCDuEJg6fF0d3qpXZQA:bqk5y4p) ([raw file](https://github.com/starkware-libs/cairo/blob/72d0fba9c1beb98ba0bc6a48788d40e3e39187d5/crates/cairo-lang-semantic/src/diagnostic.rs#L863)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Is there a test for this error?
</blockquote></details>

yes `Calling a non closure type.` in `cairo/crates/cairo-lang-semantic/src/expr/test_data/closure`
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 991 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6659#-OCCv9VFBduLSNqqPVA8:-OCDvAa_-eIRarEpVjuC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/72d0fba9c1beb98ba0bc6a48788d40e3e39187d5/crates/cairo-lang-semantic/src/expr/inference.rs#L991)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

can you document the change?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1775 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6659#-OCCxRFd6RliN7jmqqz3:-OCDvZFQ30wcGAAgBuo9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/72d0fba9c1beb98ba0bc6a48788d40e3e39187d5/crates/cairo-lang-semantic/src/items/imp.rs#L1775)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

document.
fn_once_trait is generated only if there is no fn_trait
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6659)* status: all files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6659)* status: 15 of 16 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1807 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6659#-OCCzIz4BbDHxr2NcyvF:-OCSPQc_29HXrX7EeQY2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/72d0fba9c1beb98ba0bc6a48788d40e3e39187d5/crates/cairo-lang-semantic/src/items/imp.rs#L1807)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

document
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6659)* status: all files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 16 files at r1, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6659#-:-OCbMmpcB0tZJRAi5HCh:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
