### PR TITLE
language server: pass correct non-POSIX paths to detect_crate_for

### PR DESCRIPTION
**Pull request by dedushky**
Uri to path conversion is not performed correctly on Windows because file paths are not POSIX style. That's why detect_crate_for works incorrectly:

> Error loading file /d%3A/projects/cairo...

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4388)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4388)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dedushky)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 373 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4388#-NjDPeEAA9nb5azrlR2t:-NjDPeEAA9nb5azrlR2u:b-4tl2gt) ([raw file](https://github.com/starkware-libs/cairo/blob/c2ee5a2337986f0b5b6d6a13eac15716d0f8e1d0/crates/cairo-lang-language-server/src/lib.rs#L373)):*
> ```XML
>             if let FileLongId::OnDisk(file_path) = file {
> 				self.detect_crate_for(&mut db, file_path).await;
>             }
> ```

run `./scripts/cairo_fmt.sh`
use spaces.



_Code quote:_
```XML
            if let FileLongId::OnDisk(file_path) = file {
				self.detect_crate_for(&mut db, file_path).await;
            }
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4388#-:-NjDnkxC9_JDXpWmFxkO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dedushky)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4388)* status: all files reviewed, 1 unresolved discussion (waiting on @dedushky and @gilbens-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4388#-NjE64px5dBjBL9NLoB-:-NjE64px5dBjBL9NLoB0:b-9xfho7) (no related file):*
fix clippy warning.

___

**Comment by dedushky** [comment]
clippy warning fixed

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4388)* status: all files reviewed, 1 unresolved discussion (waiting on @dedushky and @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4388)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4388#-:-NjH012f0ZAU8VrlCDCy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dedushky)

**Pull request merged**
