### PR TITLE
Unary minus separated from literals.

### PR DESCRIPTION
**Pull request by orizi**
A revert of https://reviewable.io/reviews/starkware-libs/cairo/3619 . Fixes that allow current code to still compile and give correct diags.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3815)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 33 of 40 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3815)* status: all files reviewed, 10 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 636 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3815#-NbW8gXA72hZ5FJZOHNj:-NbW8gXA72hZ5FJZOHNk:b-r06ntt) ([raw file](https://github.com/starkware-libs/cairo/blob/e843137e98cf5c37a81f231a473963f233e22f9e/crates/cairo-lang-lowering/src/lower/mod.rs#L636)):*
> ```XML
> 
> /// Lowers an expression of type [semantic::ExprFunctionCall].
> fn lower_expr_function_call(
> ```

Small note: IIUC this means that Neg::neg(3) and -3 behave exactly the same although they are different semantically. It might be surprising that Neg::neg() doesn't behave like a function call. But I can't of where it can be confusing/misleading, so I think I am OK with it. Just noting in case you can think of something wrong about this. If there is, we may need to tell them semantically.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 648 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3815#-NbV_Gmv7UYU-jRo3i71:-NbV_Gmv7UYU-jRo3i72:buox6ui) ([raw file](https://github.com/starkware-libs/cairo/blob/e843137e98cf5c37a81f231a473963f233e22f9e/crates/cairo-lang-lowering/src/lower/mod.rs#L648)):*
> ```XML
>             if let GenericFunctionId::Impl(imp) = expr.function.get_concrete(db).generic_function {
>                 if imp.impl_id.concrete_trait(db).unwrap().trait_id(db)
>                     == get_core_trait(db, "Neg".into())
> ```

Consider also checking the function name, for the unlikely case that we add another function in this trait in the future, which would be horrible to debug.
On the other hand of course it is a little less efficient.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 648 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3815#-NbVa5fyEh4IFkU6Pejz:-NbVa5fyEh4IFkU6Pek-:b5em9ba) ([raw file](https://github.com/starkware-libs/cairo/blob/e843137e98cf5c37a81f231a473963f233e22f9e/crates/cairo-lang-lowering/src/lower/mod.rs#L648)):*
> ```XML
>             if let GenericFunctionId::Impl(imp) = expr.function.get_concrete(db).generic_function {
>                 if imp.impl_id.concrete_trait(db).unwrap().trait_id(db)
>                     == get_core_trait(db, "Neg".into())
> ```

isn't it better to fail faster if the function is not neg? There are more functions that are not this one than functions that get != params.



_Code quote:_
```XML
                if imp.impl_id.concrete_trait(db).unwrap().trait_id(db)
                    == get_core_trait(db, "Neg".into())
```
___
*[`crates/cairo-lang-lowering/src/test_data/literal` line 12 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3815#-NbVF_Zt59nFQxaw1DI4:-NbVF_Zt59nFQxaw1DI5:b-qemm9r) ([raw file](https://github.com/starkware-libs/cairo/blob/e843137e98cf5c37a81f231a473963f233e22f9e/crates/cairo-lang-lowering/src/test_data/literal#L12)):*
> ```
>     let a = 4294967296_u32;
>     let b = 18446744073709551616_u64;
>     let c = 340282366920938463463374607431768211456_u128;
> ```

nit: hex



_Code quote:_
```
    let a = 256_u8;
    let a = 65536_u16;
    let a = 4294967296_u32;
    let b = 18446744073709551616_u64;
    let c = 340282366920938463463374607431768211456_u128;
```
___
*[`crates/cairo-lang-lowering/src/test_data/literal` line 22 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3815#-NbVFhM83A1dJO5mRqjR:-NbVFhM83A1dJO5mRqjS:bk9svvz) ([raw file](https://github.com/starkware-libs/cairo/blob/e843137e98cf5c37a81f231a473963f233e22f9e/crates/cairo-lang-lowering/src/test_data/literal#L22)):*
> ```
> 
> //! > lowering_diagnostics
> error: The value does not fit within the range of type core::integer::u8.
> ```

why only one error? same below
___
*[`crates/cairo-lang-parser/src/parser.rs` line 1825 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3815#-NbVI4Iq7TmP-WU3GEy3:-NbVI4Iq7TmP-WU3GEy4:b-3mpff) ([raw file](https://github.com/starkware-libs/cairo/blob/e843137e98cf5c37a81f231a473963f233e22f9e/crates/cairo-lang-parser/src/parser.rs#L1825)):*
> ```XML
>             SyntaxKind::TerminalMinus => {
>                 let minus = self.take::<TerminalMinus>().into();
>                 let literal = self.parse_token::<TerminalLiteralNumber>().into();
> ```

These are the names of the params.



_Suggestion:_
```XML
                let op = self.take::<TerminalMinus>().into();
                let expr = self.parse_token::<TerminalLiteralNumber>().into();
```
___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 619 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3815#-NbVQWbH-m6SIGUAZ-a9:-NbVQWbH-m6SIGUAZ-aA:b-g9y2qz) ([raw file](https://github.com/starkware-libs/cairo/blob/e843137e98cf5c37a81f231a473963f233e22f9e/crates/cairo-lang-semantic/src/corelib.rs#L619)):*
> ```XML
> #[derive(Clone, Debug, Eq, Hash, PartialEq)]
> pub enum LiteralError {
>     InvalidType,
> ```

Is it an invalid type or a type from which one can't create literals?
___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 623 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3815#-NbVQvSJ2W-lmmEff6Rt:-NbVQvSJ2W-lmmEff6Ru:b89kb54) ([raw file](https://github.com/starkware-libs/cairo/blob/e843137e98cf5c37a81f231a473963f233e22f9e/crates/cairo-lang-semantic/src/corelib.rs#L623)):*
> ```XML
> }
> impl LiteralError {
>     pub fn format(&self, db: &dyn SemanticGroup) -> String {
> ```

debugWithDb may fit here
___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 629 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3815#-NbVQLUJ1MWIJ8It9Eyo:-NbVQLUJ1MWIJ8It9Eyp:b-j5n5t5) ([raw file](https://github.com/starkware-libs/cairo/blob/e843137e98cf5c37a81f231a473963f233e22f9e/crates/cairo-lang-semantic/src/corelib.rs#L629)):*
> ```XML
>                 ty.format(db.upcast())
>             ),
>             Self::InvalidType => "A literal with this type cannot be created.".into(),
> ```

add type name here too
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 703 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3815#-NbVZUZGEXYEsKPRg7Ld:-NbVZUZGEXYEsKPRg7Le:blacyrk) ([raw file](https://github.com/starkware-libs/cairo/blob/d5c3b3fae86e92b9f1dbf68ee767d60fcf2b4377/crates/cairo-lang-semantic/src/expr/compute.rs#L703)):*
> ```XML
>                 .map_err(|err| ctx.diagnostics.report_by_ptr(pattern.stable_ptr.untyped(), err))
>                 .ok();
>         }
> ```

Did you move these to lowering (lower_expr_constant_helper)? I guess there is something I miss.
If so - why? And is it enough to only check in contstants?



_Code quote:_
```XML
        if let Expr::Literal(expr) = expr {
            validate_literal(ctx.db, expr.ty, expr.value.clone())
                .map_err(|err| ctx.diagnostics.report_by_ptr(expr.stable_ptr.untyped(), err))
                .ok();
        }
    }
    for (_id, pattern) in ctx.patterns.iter_mut() {
        *pattern = ctx.resolver.inference().rewrite(pattern.clone()).no_err();
        if let Pattern::Literal(pattern) = pattern {
            validate_literal(ctx.db, pattern.literal.ty, pattern.literal.value.clone())
                .map_err(|err| ctx.diagnostics.report_by_ptr(pattern.stable_ptr.untyped(), err))
                .ok();
        }
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3815)* status: all files reviewed, 7 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 636 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3815#-NbW8gXA72hZ5FJZOHNj:-NbhC1VGAebnPMaFolVD:bxgp472) ([raw file](https://github.com/starkware-libs/cairo/blob/e843137e98cf5c37a81f231a473963f233e22f9e/crates/cairo-lang-lowering/src/lower/mod.rs#L636)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Small note: IIUC this means that Neg::neg(3) and -3 behave exactly the same although they are different semantically. It might be surprising that Neg::neg() doesn't behave like a function call. But I can't of where it can be confusing/misleading, so I think I am OK with it. Just noting in case you can think of something wrong about this. If there is, we may need to tell them semantically.
</blockquote></details>

it is known - but this sounds like a good enough decision for the time being.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 648 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3815#-NbVa5fyEh4IFkU6Pejz:-NbhEoyG0rZ0cNVQfAX8:b-jnc9v2) ([raw file](https://github.com/starkware-libs/cairo/blob/e843137e98cf5c37a81f231a473963f233e22f9e/crates/cairo-lang-lowering/src/lower/mod.rs#L648)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

isn't it better to fail faster if the function is not neg? There are more functions that are not this one than functions that get != params.
</blockquote></details>

i tried to avoid db calls and use data already available.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 648 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3815#-NbV_Gmv7UYU-jRo3i71:-NbhGBd6Ei3ZDsWdAEE6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e843137e98cf5c37a81f231a473963f233e22f9e/crates/cairo-lang-lowering/src/lower/mod.rs#L648)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Consider also checking the function name, for the unlikely case that we add another function in this trait in the future, which would be horrible to debug.
On the other hand of course it is a little less efficient.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/test_data/literal` line 22 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3815#-NbVFhM83A1dJO5mRqjR:-NbhJuBsDkIQUeUpn720:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e843137e98cf5c37a81f231a473963f233e22f9e/crates/cairo-lang-lowering/src/test_data/literal#L22)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

why only one error? same below
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 619 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3815#-NbVQWbH-m6SIGUAZ-a9:-NbhGdeJAK19PXkyRH6t:bql1guc) ([raw file](https://github.com/starkware-libs/cairo/blob/e843137e98cf5c37a81f231a473963f233e22f9e/crates/cairo-lang-semantic/src/corelib.rs#L619)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Is it an invalid type or a type from which one can't create literals?
</blockquote></details>

Invalid type for a literal generally - i guess we can move this to be only semantic.
___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 623 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3815#-NbVQvSJ2W-lmmEff6Rt:-NbhGXji3fjaRy9CR1gx:b4s7j6o) ([raw file](https://github.com/starkware-libs/cairo/blob/e843137e98cf5c37a81f231a473963f233e22f9e/crates/cairo-lang-semantic/src/corelib.rs#L623)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

debugWithDb may fit here
</blockquote></details>

this is the merged print for diagnostics - not sure i should add a debug 
___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 629 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3815#-NbVQLUJ1MWIJ8It9Eyo:-NbhGnGeBkfrXdAo2uWQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e843137e98cf5c37a81f231a473963f233e22f9e/crates/cairo-lang-semantic/src/corelib.rs#L629)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

add type name here too
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 703 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3815#-NbVZUZGEXYEsKPRg7Ld:-NbhKQGDBPXTnpAbTxP4:b-ey9zaq) ([raw file](https://github.com/starkware-libs/cairo/blob/d5c3b3fae86e92b9f1dbf68ee767d60fcf2b4377/crates/cairo-lang-semantic/src/expr/compute.rs#L703)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Did you move these to lowering (lower_expr_constant_helper)? I guess there is something I miss.
If so - why? And is it enough to only check in contstants?

</blockquote></details>

these validations are exactly what was moved to lowering stage.
Since i don't know the type when meeting the minus literal, and this would require querying around the current expression for each such validation.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3815#-:-NbjB9-B0_82EYLh9Otf:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 528 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3815#-NbjAZOQDj9YSMqsm4u1:-NbjAZOQDj9YSMqsm4u2:b3ep3hr) ([raw file](https://github.com/starkware-libs/cairo/blob/4007c58527a706d21cd0999dd6720eb93d27ef0f/crates/cairo-lang-lowering/src/lower/mod.rs#L528)):*
> ```XML
> }
> 
> /// Lowers a semantic expression that is a constant.
> ```

Can you please clarify that this doesn't refer to a constant item?



_Code quote:_
```XML
 Lowers a semantic expression that is a constant.
```
___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 619 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3815#-NbVQWbH-m6SIGUAZ-a9:-NbjAmqT5g742nYcLTDL:bbp90f0) ([raw file](https://github.com/starkware-libs/cairo/blob/e843137e98cf5c37a81f231a473963f233e22f9e/crates/cairo-lang-semantic/src/corelib.rs#L619)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Invalid type for a literal generally - i guess we can move this to be only semantic.
</blockquote></details>

Can you please rename to InvalidLiteralType for it to be clearer that it doesn't mean the type itself is invalid?

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3815)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3815)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by yuvalsw — APPROVED** [review]
> Reviewed 2 of 2 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3815)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
