### PR TITLE
Making sure functions do not have an unstorable ty.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #3170
- #3167 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3167)

### CODE REVIEW

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3167)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/program_registry.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3167#-NV_6yoaCu0JFF510w-2:-NV_6yoaCu0JFF510w-3:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/f6f4ec6be9eb3dff128c880cc7df8544c55b4b34/crates/cairo-lang-sierra/src/program_registry.rs#L48)):*
> ```XML
>     #[error("Type info declaration mismatch")]
>     TypeInfoDeclarationMismatch(ConcreteTypeId),
>     #[error("Function param with unstorable type")]
> ```

.



_Suggestion:_
```XML
#[error("Function parameter type must be storable")]
```

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3167)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3167)* status: all files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/program_registry.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3167#-NV_8BKPDj0DzQ9D-dyw:-NV_8BKPDj0DzQ9D-dyx:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/f6f4ec6be9eb3dff128c880cc7df8544c55b4b34/crates/cairo-lang-sierra/src/program_registry.rs#L123)):*
> ```XML
>     }
> 
>     fn validate(&self) -> Result<(), Box<ProgramRegistryError>> {
> ```

.



_Suggestion:_
```XML
    /// Checks the validity of the [ProgramRegistry].
    ///
    /// Checks that all the parameter and return types are storable.
    fn validate(&self) -> Result<(), Box<ProgramRegistryError>> {
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3167)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3167#-NV_6mTA0SpOSnoIyCD-:-NV_IV6v-aW817I2Tu61:b-896fix) (no related file):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Target branch should be `dev-v1.1.0`
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3167#-NV_7JUu87YPsso5Ts8y:-NV_IVNH9wlF_VheIJT-:b-896fix) (no related file):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Add a `compiler_test` test.
</blockquote></details>

Done.

___
___
*[`crates/cairo-lang-sierra/src/program_registry.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3167#-NV_6yoaCu0JFF510w-2:-NV_JazV9W1PoHjSxTZz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/dadf5822ce0e36070e1af06c6eda655e201317f6/crates/cairo-lang-sierra/src/program_registry.rs#L48)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Include function id in the error message?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/program_registry.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3167#-NV_7V1gDCwKFEsaGQOd:-NV_Jg6cBD_e_QKrf9pb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/dadf5822ce0e36070e1af06c6eda655e201317f6/crates/cairo-lang-sierra/src/program_registry.rs#L70)):*
> ```XML
> impl<TType: GenericType, TLibfunc: GenericLibfunc> ProgramRegistry<TType, TLibfunc> {
>     /// Create a registry for the program.
>     pub fn with_ap_change(
> ```

Done.
___
*[`crates/cairo-lang-sierra/src/program_registry.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3167#-NV_8BKPDj0DzQ9D-dyw:-NV_JpztCpTC6jBLj6KW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/dadf5822ce0e36070e1af06c6eda655e201317f6/crates/cairo-lang-sierra/src/program_registry.rs#L123)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3167#-:-NV_NLtK6pl4HlOBz7d_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/program_registry.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3167#-NV_6yoaCu0JFF510w-2:-NV_Mzrt3sv0BQbFrnB5:b7e7uqz) ([raw file](https://github.com/starkware-libs/cairo/blob/dadf5822ce0e36070e1af06c6eda655e201317f6/crates/cairo-lang-sierra/src/program_registry.rs#L48)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You missed the second question, but it's not important.

**Pull request merged**
