### PR TITLE
Add `get_starknet_inline_macro_plugins` and `RootDatabaseBuilder::with_inline_macro_plugins`

### PR DESCRIPTION
**Pull request by mkaput**
Add centralized source of information about Starknet-relevant plugins, instead of smearing this list everywhere.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4313)

### CODE REVIEW

**Comment by mkaput** [comment]
This will help mitigating issues like: https://github.com/software-mansion/scarb/issues/832

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4313)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @mkaput and @yuvalsw)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4313#-Nho5Xyb14_xOPtzL58O:-Nho5Xyc0_Tb7oeIVZTh:begpihx) ([raw file](https://github.com/starkware-libs/cairo/blob/8758d4904a253afd6ec5d3bd4634ae7de29960d5/crates/cairo-lang-language-server/src/lib.rs#L88)):*
> ```XML
>         .with_macro_plugin(Arc::new(StarkNetPlugin::default()))
>         .with_macro_plugin(Arc::new(TestPlugin::default()))
>         .with_inline_macro_plugins(get_starknet_inline_macro_plugins())
> ```

maybe instead add a concept of "PluginSuite" - containing both the inlines and the Starknet plugin.

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4313)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @maciektr and @yuvalsw)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4313#-Nho5Xyb14_xOPtzL58O:-NhzqyKm97a3rDLRtDUi:bxk283c) ([raw file](https://github.com/starkware-libs/cairo/blob/8758d4904a253afd6ec5d3bd4634ae7de29960d5/crates/cairo-lang-language-server/src/lib.rs#L88)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe instead add a concept of "PluginSuite" - containing both the inlines and the Starknet plugin.
</blockquote></details>

I'm :100: for this, but this seems to be a much bigger change, which I don't want to dig into as I don't know how much time I have left :stuck_out_tongue_winking_eye: 

So, as for this PR I see two options:
1. Close it and live on the edge as we did to this date.
2. Merge it and proceed with plugin suites later on.

We want to soonish get back to the topic of compiler plugins, @maciektr will be working on that while I'll be on my leave. So I think it would be natural if @maciektr do this refactoring. Wdyt all?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4313)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @maciektr and @yuvalsw)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4313#-Nho5Xyb14_xOPtzL58O:-NiP5qEo1hDqwO6xxkJ7:b3t2nuc) ([raw file](https://github.com/starkware-libs/cairo/blob/8758d4904a253afd6ec5d3bd4634ae7de29960d5/crates/cairo-lang-language-server/src/lib.rs#L88)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I'm :100: for this, but this seems to be a much bigger change, which I don't want to dig into as I don't know how much time I have left :stuck_out_tongue_winking_eye: 

So, as for this PR I see two options:
1. Close it and live on the edge as we did to this date.
2. Merge it and proceed with plugin suites later on.

We want to soonish get back to the topic of compiler plugins, @maciektr will be working on that while I'll be on my leave. So I think it would be natural if @maciektr do this refactoring. Wdyt all?
</blockquote></details>

I now have an open PR for the plugin suite.

**Comment by mkaput** [comment]
superseded by #4349

**Pull request closed without merging**
