### PR TITLE
Made `panic` return never-type in the semantic level.

### PR DESCRIPTION
**Pull request by orizi**
Includes better error propagation in lowering stage.

commit-id:d41e4dda

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1170)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1170#-NI61l-c6d8HlTTKYBgq:-NI61l-d6rfArRuRBc7B:b-3kk8j9) (no related file):*
Wdyt about just declaring panic's siganture as -> Never ?
I think it will be less magical to the code readers, and less edge cases in the compiler.
(And yes, make Never a real type. Enum with no branches, for example)

___

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1170)* status: 2 of 12 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1170#-NI61l-c6d8HlTTKYBgq:-NI6q3Wh-6cAiBHPJCwX:b-896fix) (no related file):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Wdyt about just declaring panic's siganture as -> Never ?
I think it will be less magical to the code readers, and less edge cases in the compiler.
(And yes, make Never a real type. Enum with no branches, for example)
</blockquote></details>

Done.

___

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1170#-:-NI6qmm04TFp1_oAhVni:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1170)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
