### PR TITLE
Refactor syscall hint handling.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #3146
- #3142 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3142)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3142)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 411 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3142#-NVZ09cbAPFtj2nkbhfP:-NVZ09cbAPFtj2nkbhfQ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6eeb570d99f8bc1069d296bee9c1edc6ca379b2a/crates/cairo-lang-runner/src/casm_run/mod.rs#L411)):*
> ```XML
> }
> impl<'a> MemBuffer<'a> {
>     /// Create a new buffer.
> ```





_Suggestion:_
```XML
Creates
```
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 416 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3142#-NVZ0Bf_6k3xOriTREBQ:-NVZ0Bf_6k3xOriTREBR:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6eeb570d99f8bc1069d296bee9c1edc6ca379b2a/crates/cairo-lang-runner/src/casm_run/mod.rs#L416)):*
> ```XML
>     }
> 
>     /// Create a new segements and returns a buffer wrapping it.
> ```





_Suggestion:_
```XML
Creates
```
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 416 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3142#-NVZ0E385vE2L1dF2rqK:-NVZ0E385vE2L1dF2rqL:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6eeb570d99f8bc1069d296bee9c1edc6ca379b2a/crates/cairo-lang-runner/src/casm_run/mod.rs#L416)):*
> ```XML
>     }
> 
>     /// Create a new segements and returns a buffer wrapping it.
> ```





_Suggestion:_
```XML
segment
```
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 524 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3142#-NVZ0_Uf9NFL6CKO415u:-NVZ0_Uf9NFL6CKO415v:b-lf8n) ([raw file](https://github.com/starkware-libs/cairo/blob/6eeb570d99f8bc1069d296bee9c1edc6ca379b2a/crates/cairo-lang-runner/src/casm_run/mod.rs#L524)):*
> ```XML
>                 self.storage_write(
>                     gas_counter,
>                     system_buffer.next_val()?,
> ```

The names are not clear. Consider using `let name = system_buffer...`, and then passing the variables by name to `self.storage_write`

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3142)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 631 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3142#-NVZ0u604kB8qj3osbfT:-NVZ0u604kB8qj3osbfU:blslwqv) ([raw file](https://github.com/starkware-libs/cairo/blob/6eeb570d99f8bc1069d296bee9c1edc6ca379b2a/crates/cairo-lang-runner/src/casm_run/mod.rs#L631)):*
> ```XML
>         let signature_end = res_segment.ptr;
>         let tx_info_ptr = res_segment.ptr;
>         res_segment.write(tx_info.version.clone())?;
> ```

Consider adding a trait to write entire structs

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3142)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 411 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3142#-NVZ09cbAPFtj2nkbhfP:-NVZ1wOrEmrOmbSOTFa7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6eeb570d99f8bc1069d296bee9c1edc6ca379b2a/crates/cairo-lang-runner/src/casm_run/mod.rs#L411)):*
> ```XML
> }
> impl<'a> MemBuffer<'a> {
>     /// Create a new buffer.
> ```

Done.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 416 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3142#-NVZ0Bf_6k3xOriTREBQ:-NVZ1wj0Ed7ip2_31BaD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6eeb570d99f8bc1069d296bee9c1edc6ca379b2a/crates/cairo-lang-runner/src/casm_run/mod.rs#L416)):*
> ```XML
>     }
> 
>     /// Create a new segements and returns a buffer wrapping it.
> ```

Done.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 416 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3142#-NVZ0E385vE2L1dF2rqK:-NVZ2-6H3ar2WAiPn5oc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6eeb570d99f8bc1069d296bee9c1edc6ca379b2a/crates/cairo-lang-runner/src/casm_run/mod.rs#L416)):*
> ```XML
>     }
> 
>     /// Create a new segements and returns a buffer wrapping it.
> ```

Done.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 524 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3142#-NVZ0_Uf9NFL6CKO415u:-NVZ1Pnt8CZuwb_a1pSI:b3108j1) ([raw file](https://github.com/starkware-libs/cairo/blob/6eeb570d99f8bc1069d296bee9c1edc6ca379b2a/crates/cairo-lang-runner/src/casm_run/mod.rs#L524)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

The names are not clear. Consider using `let name = system_buffer...`, and then passing the variables by name to `self.storage_write`
</blockquote></details>

this would add the possibility for reading and passing the args in the wrong order - this way the function defines the correct params
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 631 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3142#-NVZ0u604kB8qj3osbfT:-NVZ1j6M9WKp_4OvsDvw:b1zk28u) ([raw file](https://github.com/starkware-libs/cairo/blob/6eeb570d99f8bc1069d296bee9c1edc6ca379b2a/crates/cairo-lang-runner/src/casm_run/mod.rs#L631)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Consider adding a trait to write entire structs
</blockquote></details>

maybe when we have a lot of different structs types - which we currently do not have.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3142#-:-NVZ2e-a9L45W2kT5jjK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
