### PR TITLE
Added validation that all trait items are implemented in the impl

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1795)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1795)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 308 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1795#-NM2SP-a0szOXUbupkRV:-NM2SP-a0szOXUbupkRW:b-va3cqz) ([raw file](https://github.com/starkware-libs/cairo/blob/c96100cfc45fc1c7a412582f27bfc4553e20a852/crates/cairo-lang-semantic/src/items/imp.rs#L308)):*
> ```XML
>         .trait_functions(db.lookup_intern_concrete_trait(concrete_trait).trait_id)?
>         .into_iter()
>         .map(|(name, _)| name)
> ```

Can you use
.keys()?



_Code quote:_
```XML
        .into_iter()
        .map(|(name, _)| name)
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1795)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 308 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1795#-NM2SP-a0szOXUbupkRV:-NM3BKZ86GDLQIuENGX5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c96100cfc45fc1c7a412582f27bfc4553e20a852/crates/cairo-lang-semantic/src/items/imp.rs#L308)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Can you use
.keys()?
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1795#-:-NM3EGDtEU8tCMl59chu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1795)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1795#-:-NM7iFGT00ndAuf70m2t:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1795)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
