### PR TITLE
Store defered variables that are assigned a local variable.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2751)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2751#-:-NS_frEbDJsymAHzD3OX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2751)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 226 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2751#-NS_jWyL4_05eqiCv_ld:-NS_jWyL4_05eqiCv_le:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/3d6b68ae6245a6f9274958454e6abd85306a71e6/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L226)):*
> ```XML
>             if self.local_variables.get(arg).is_some() {
>                 // If a deferred argument was assinged a local then we should store
>                 // it in case the function has a `SameAsParam` output.
> ```

.



_Suggestion:_
```XML
                // If a deferred argument was marked as a local variable, then store
                // it. This is important in case an alias of the variable is used later
                // (for example, due to `SameAsParam` output).
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2751)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 226 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2751#-NS_jWyL4_05eqiCv_ld:-NS_l3bZ97ovdjBsv51b:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3d6b68ae6245a6f9274958454e6abd85306a71e6/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L226)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2751)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @orizi)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 4 of 6 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2751)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
