### PR TITLE
Added generation of impl of HasComponent

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3975)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3975)* status: 2 of 11 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/storage.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3975#-NcwMDRz9R8_92wocLnS:-NcwMDS--rcYi9Vs6t0e:b5jcdki) ([raw file](https://github.com/starkware-libs/cairo/blob/1f796a8c3b74a88dfb569f82d8fced51c2fddf8c/crates/cairo-lang-starknet/src/plugin/storage.rs#L42)):*
> ```XML
>             });
>             continue;
>         }
> ```

don't  they have to be supported?
Shouldn't you just skip them without creating a diagnostic?



_Code quote:_
```XML
        // TODO(yuval): support nested structs.
        // Nested members are not supported yet, skip them.
        if member.attributes(db).has_attr(db, NESTED_ATTR) {
            diagnostics.push(PluginDiagnostic {
                message: "Nested storage members are not not yet supported.".to_string(),
                stable_ptr: member.stable_ptr().untyped(),
            });
            continue;
        }
```
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 410 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3975#-NcwMYA_8PQEfhkSpCcT:-NcwMYA_8PQEfhkSpCcU:b-wp5zp7) ([raw file](https://github.com/starkware-libs/cairo/blob/1f796a8c3b74a88dfb569f82d8fced51c2fddf8c/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L410)):*
> ```XML
> ) -> PluginResult {
>     if let Some((_module_ast, module_kind)) =
>         grand_grand_parent_starknet_module(component_macro_ast.as_syntax_node(), db)
> ```

are you using this in storage implementation as well?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3975)* status: 2 of 11 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/mod.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3975#-NcwMp1801a1AsIF-yUV:-NcwMp1801a1AsIF-yUW:b-aa45gw) ([raw file](https://github.com/starkware-libs/cairo/blob/1f796a8c3b74a88dfb569f82d8fced51c2fddf8c/crates/cairo-lang-starknet/src/plugin/mod.rs#L61)):*
> ```XML
>                 // The macro is expanded in handle_module_by_storage, but we also need to remove the
>                 // original code.
>                 starknet_module::contract::remove_component_inline_macro(db, &inline_macro_ast)
> ```

are there particular extractions that are make it easier implementing this as part of the contract module handling itself?
since, AFAIU, all the parts generated by this are independent.



_Code quote:_
```XML
                // The macro is expanded in handle_module_by_storage, but we also need to remove the
                // original code.
                starknet_module::contract::remove_component_inline_macro(db, &inline_macro_ast)
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3975)* status: 2 of 11 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/mod.rs` line 265 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3975#-NcwN_Dz1P_40jxdSOPR:-NcwN_Dz1P_40jxdSOPS:b-ajmze6) ([raw file](https://github.com/starkware-libs/cairo/blob/1f796a8c3b74a88dfb569f82d8fced51c2fddf8c/crates/cairo-lang-starknet/src/plugin/starknet_module/mod.rs#L265)):*
> ```XML
>     db: &dyn SyntaxGroup,
> ) -> Option<(ast::ItemModule, StarknetModuleKind)> {
>     let module_node = item_node.parent()?.parent()?.parent()?;
> ```

doc why `.parent()?.parent()?.parent()?;`

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3975)* status: 2 of 11 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/mod.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3975#-NcwMp1801a1AsIF-yUV:-NcwabuWCOOV3soQBs_2:b-pojhj0) ([raw file](https://github.com/starkware-libs/cairo/blob/1f796a8c3b74a88dfb569f82d8fced51c2fddf8c/crates/cairo-lang-starknet/src/plugin/mod.rs#L61)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

are there particular extractions that are make it easier implementing this as part of the contract module handling itself?
since, AFAIU, all the parts generated by this are independent.
</blockquote></details>

I don't follow. This only removes the original item. The logic of the code generation based on it is all in the contract module handling.
___
*[`crates/cairo-lang-starknet/src/plugin/storage.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3975#-NcwMDRz9R8_92wocLnS:-Ncwaz4z8xO5xC9d1kcU:b-ywjcp1) ([raw file](https://github.com/starkware-libs/cairo/blob/1f796a8c3b74a88dfb569f82d8fced51c2fddf8c/crates/cairo-lang-starknet/src/plugin/storage.rs#L42)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

don't  they have to be supported?
Shouldn't you just skip them without creating a diagnostic?
</blockquote></details>

This would be confusing for the contract writer. They don't have to be supported for now. Later we'll add this support. For now it wouldn't be possible to add them in the contract's storage.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 410 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3975#-NcwMYA_8PQEfhkSpCcT:-NcwbeXQ3ept3xZBfdXb:b9okzp0) ([raw file](https://github.com/starkware-libs/cairo/blob/1f796a8c3b74a88dfb569f82d8fced51c2fddf8c/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L410)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

are you using this in storage implementation as well?
</blockquote></details>

Yes. It's in this PR, you should be able to see it.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/mod.rs` line 265 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3975#-NcwN_Dz1P_40jxdSOPR:-NcwcNNs7LKosKVUdKVE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1f796a8c3b74a88dfb569f82d8fced51c2fddf8c/crates/cairo-lang-starknet/src/plugin/starknet_module/mod.rs#L265)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc why `.parent()?.parent()?.parent()?;`
</blockquote></details>

Done.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3975)* status: 6 of 11 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/mod.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3975#-NcwMp1801a1AsIF-yUV:-NcwsQclE9ZkhANVJZ00:bqqs4c9) ([raw file](https://github.com/starkware-libs/cairo/blob/1f796a8c3b74a88dfb569f82d8fced51c2fddf8c/crates/cairo-lang-starknet/src/plugin/mod.rs#L61)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I'm just asking for the rationale for this being different than the storage struct, where all the generation occurs on the struct definition.
</blockquote></details>

The processing of all the items in the contract module is done when we see the storage struct. This is no different, and thus it's also done in the same place. In addition, we need to remove the original inline macro, and because this is the only place it's possible to do it, we do it here.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/contract` line 110 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3975#-Ncweynw62cFkjC-Z4ue:-NcwvfFR-IafcXB1NgRj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fc1adeaf6cb1c159e1cabbb359f4a9a6bbdc885e/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/contract#L110)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Why did this disappear?
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 11 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3975)* status: 16 of 18 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/mod.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3975#-NcwMp1801a1AsIF-yUV:-NcxHRz47KNKZyxh2obL:bqnc7cs) ([raw file](https://github.com/starkware-libs/cairo/blob/1f796a8c3b74a88dfb569f82d8fced51c2fddf8c/crates/cairo-lang-starknet/src/plugin/mod.rs#L61)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

The processing of all the items in the contract module is done when we see the storage struct. This is no different, and thus it's also done in the same place. In addition, we need to remove the original inline macro, and because this is the only place it's possible to do it, we do it here.
</blockquote></details>

got it - everything is created on the storage for some reason.
don't really understand why - but this indeed does not diverge from this design.
___
*[`crates/cairo-lang-starknet/src/plugin/storage.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3975#-NcwMDRz9R8_92wocLnS:-NcxGGSE2dg_zUQ2i_pL:b-u0rmxq) ([raw file](https://github.com/starkware-libs/cairo/blob/1f796a8c3b74a88dfb569f82d8fced51c2fddf8c/crates/cairo-lang-starknet/src/plugin/storage.rs#L42)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

This would be confusing for the contract writer. They don't have to be supported for now. Later we'll add this support. For now it wouldn't be possible to add them in the contract's storage.
</blockquote></details>

but for future compatibility - it makes more sense if it has to appear there,
otherwise - what does the `component!(..., storage={})` point to?
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 410 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3975#-NcwMYA_8PQEfhkSpCcT:-NcxHDJxCDVZwT5-C2Ev:b9sl5j9) ([raw file](https://github.com/starkware-libs/cairo/blob/1f796a8c3b74a88dfb569f82d8fced51c2fddf8c/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L410)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Yes. It's in this PR, you should be able to see it.
</blockquote></details>

that was why this was retracted :)

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3975)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3975)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/storage.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3975#-NcwMDRz9R8_92wocLnS:-Nd0gBBk5CwJy9pgXrJU:btbmzk8) ([raw file](https://github.com/starkware-libs/cairo/blob/1f796a8c3b74a88dfb569f82d8fced51c2fddf8c/crates/cairo-lang-starknet/src/plugin/storage.rs#L42)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

but for future compatibility - it makes more sense if it has to appear there,
otherwise - what does the `component!(..., storage={})` point to?
</blockquote></details>

As discussed - will be added in the next PR.
Currently the "storage:" in component! is ignored.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3975#-:-Nd0iD6EAPKwPgq7eFSZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
