### PR TITLE
Added components

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3876)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3876)* status: 2 of 30 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3876#-NbQ1c_oEmzu97QJslSh:-NbQ1c_pDQkkrk_cIadg:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/320ca9607a618f859a9faa37fc5bc708f5cb1e21/crates/cairo-lang-starknet/src/plugin/contract.rs#L56)):*
> ```XML
> }
> 
> fn validate_module(
> ```

doc
___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 107 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3876#-NbQ1gSw1jtiYdDwQbj9:-NbQ1gSw1jtiYdDwQbjA:b-5ae9kc) ([raw file](https://github.com/starkware-libs/cairo/blob/320ca9607a618f859a9faa37fc5bc708f5cb1e21/crates/cairo-lang-starknet/src/plugin/contract.rs#L107)):*
> ```XML
> 
> #[derive(PartialEq, Eq, Copy, Clone)]
> pub enum StarknetModuleKind {
> ```

doc all
___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 357 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3876#-NbQ2-NJ8kA_Q6LGTsP1:-NbQ2-NJ8kA_Q6LGTsP2:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/320ca9607a618f859a9faa37fc5bc708f5cb1e21/crates/cairo-lang-starknet/src/plugin/contract.rs#L357)):*
> ```XML
> }
> 
> // Handles an impl inside a contract module.
> ```





_Suggestion:_
```XML
/// Handles an impl inside a contract module.
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3876)* status: 2 of 30 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3876#-NbQ1c_oEmzu97QJslSh:-NbUn0KiCO5fzXZQF_6O:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/320ca9607a618f859a9faa37fc5bc708f5cb1e21/crates/cairo-lang-starknet/src/plugin/contract.rs#L56)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 107 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3876#-NbQ1gSw1jtiYdDwQbj9:-NbUn-qm2w6Be4KrIikm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/320ca9607a618f859a9faa37fc5bc708f5cb1e21/crates/cairo-lang-starknet/src/plugin/contract.rs#L107)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc all
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 357 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3876#-NbQ2-NJ8kA_Q6LGTsP1:-NbUlAPU7jkvFiE0iVv-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/320ca9607a618f859a9faa37fc5bc708f5cb1e21/crates/cairo-lang-starknet/src/plugin/contract.rs#L357)):*
> ```XML
> }
> 
> // Handles an impl inside a contract module.
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 30 files at r1, 23 of 24 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3876)* status: 28 of 30 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 149 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3876#-NbT6P2L4CS8x2GP1cx9:-NbT6P2L4CS8x2GP1cxA:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/320ca9607a618f859a9faa37fc5bc708f5cb1e21/crates/cairo-lang-starknet/src/plugin/contract.rs#L149)):*
> ```XML
>     let Some(module_kind) = StarknetModuleKind::from_module(db, &module_ast) else {
>         return None;
>     };
> ```





_Suggestion:_
```XML
    let module_kind = StarknetModuleKind::from_module(db, &module_ast)?;
```
___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3876#-Nbh99-VCce5F5E1GCCT:-Nbh99-VCce5F5E1GCCU:bwe59pv) ([raw file](https://github.com/starkware-libs/cairo/blob/e46567c7a753b21b77deb450a11ab0105a347601/crates/cairo-lang-starknet/src/plugin/contract.rs#L53)):*
> ```XML
>     }
> 
>     PluginResult::default()
> ```

consider using `match StarknetModuleKind::from_module(db, module_ast)` and `to_str_capital`



_Code quote:_
```XML
    if module_ast.has_attr(db, CONTRACT_ATTR) {
        return validate_module(db, module_ast, "Contract");
    }
    if module_ast.has_attr(db, COMPONENT_ATTR) {
        return validate_module(db, module_ast, "Component");
    }

    PluginResult::default()
```
___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 235 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3876#-NbhB_IhA51Ry2Ae8c-W:-NbhB_IhA51Ry2Ae8c-X:b-948buc) ([raw file](https://github.com/starkware-libs/cairo/blob/e46567c7a753b21b77deb450a11ab0105a347601/crates/cairo-lang-starknet/src/plugin/contract.rs#L235)):*
> ```XML
>             "
>             #[cfg(test)]
>             const TEST_CLASS_HASH: felt252 = {test_class_hash};
> ```

this is only relevant for contracts.



_Code quote:_
```XML
            #[cfg(test)]
            const TEST_CLASS_HASH: felt252 = {test_class_hash};
```
___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 237 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3876#-NbhBdzq7fPw6JSL4Fnz:-NbhBdzq7fPw6JSL4Fo-:br7avxj) ([raw file](https://github.com/starkware-libs/cairo/blob/e46567c7a753b21b77deb450a11ab0105a347601/crates/cairo-lang-starknet/src/plugin/contract.rs#L237)):*
> ```XML
>             const TEST_CLASS_HASH: felt252 = {test_class_hash};
>             $state_struct_code$
>             $generated_wrapper_functions$
> ```

also only relevant for contracts.



_Code quote:_
```XML
            $generated_wrapper_functions$
```
___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 545 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3876#-NbhAE3u1WKq9XqRVu0f:-NbhAE3u1WKq9XqRVu0g:b44w7n7) ([raw file](https://github.com/starkware-libs/cairo/blob/e46567c7a753b21b77deb450a11ab0105a347601/crates/cairo-lang-starknet/src/plugin/contract.rs#L545)):*
> ```XML
>         declaration.generic_params(db)
>     {
>         // TODO(yuval): For components, validate this in the component generation.
> ```

isn't this just relevant for the impl-alias part?
this code does not directly generate any wrappers for contracts, so this TODO is more likely to just be forgotten here.



_Code quote:_
```XML
        // TODO(yuval): For components, validate this in the component generation.
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3876)* status: 28 of 30 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 149 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3876#-NbT6P2L4CS8x2GP1cx9:-NbilfEy7QyUdxcHTw6r:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/320ca9607a618f859a9faa37fc5bc708f5cb1e21/crates/cairo-lang-starknet/src/plugin/contract.rs#L149)):*
> ```XML
>     let Some(module_kind) = StarknetModuleKind::from_module(db, &module_ast) else {
>         return None;
>     };
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3876#-Nbh99-VCce5F5E1GCCT:-NbilROq352tHfjTe4uY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e46567c7a753b21b77deb450a11ab0105a347601/crates/cairo-lang-starknet/src/plugin/contract.rs#L53)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

consider using `match StarknetModuleKind::from_module(db, module_ast)` and `to_str_capital`
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 235 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3876#-NbhB_IhA51Ry2Ae8c-W:-NbixbAn0P5jnfeY5EzD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e46567c7a753b21b77deb450a11ab0105a347601/crates/cairo-lang-starknet/src/plugin/contract.rs#L235)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is only relevant for contracts.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 237 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3876#-NbhBdzq7fPw6JSL4Fnz:-NbiwJPu6-KD6jRT-Hxx:bczklb8) ([raw file](https://github.com/starkware-libs/cairo/blob/e46567c7a753b21b77deb450a11ab0105a347601/crates/cairo-lang-starknet/src/plugin/contract.rs#L237)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

also only relevant for contracts.
</blockquote></details>

This would indeed be empty for components.
___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 545 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3876#-NbhAE3u1WKq9XqRVu0f:-NbixmowA6YAWuE2EqiK:binbgdj) ([raw file](https://github.com/starkware-libs/cairo/blob/e46567c7a753b21b77deb450a11ab0105a347601/crates/cairo-lang-starknet/src/plugin/contract.rs#L545)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

isn't this just relevant for the impl-alias part?
this code does not directly generate any wrappers for contracts, so this TODO is more likely to just be forgotten here.
</blockquote></details>

Correct, removed.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 30 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3876#-:-Nbj43ZmAwWpyXSUmDTh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware and @spapinistarkware)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 30 files at r1, 20 of 24 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3876#-:-NbjCLg1EXar3oqmujWI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3876)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
