### PR TITLE
Added ABI trait for Starknet contracts

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1499)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1499)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/starknet/src/plugin_test_data/contract` line 29 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1499#-NKEJSysBdBeTu2hHwZc:-NKEJSysBdBeTu2hHwZd:bfy0q9o) ([raw file](https://github.com/starkware-libs/cairo/blob/09b7f401e12370abd98d350ac50a71a690badd57/crates/starknet/src/plugin_test_data/contract#L29)):*
> ```
> 
>     #[view]
>     fn get_something(ref system: System, ref arg: felt, num: felt) -> felt {
> ```

didn't you remove that?



_Code quote:_
```
ref system: System
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1499)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/starknet/src/plugin.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1499#-NKEJWIK9_1rZBZF7v_P:-NKEJWIK9_1rZBZF7v_Q:b-oa8022) ([raw file](https://github.com/starkware-libs/cairo/blob/09b7f401e12370abd98d350ac50a71a690badd57/crates/starknet/src/plugin.rs#L106)):*
> ```XML
>             $original_items
> 
>             // TODO(yuval): add impl of __abi and use it from the wrappers, instead of the original
> ```

what is the benefit?



_Code quote:_
```XML
add impl of __abi and use it from the wrappers
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1499)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/starknet/src/plugin.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1499#-NKEJWIK9_1rZBZF7v_P:-NKELkQvDQTxz_WvnVDw:b-t5pi76) ([raw file](https://github.com/starkware-libs/cairo/blob/09b7f401e12370abd98d350ac50a71a690badd57/crates/starknet/src/plugin.rs#L106)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what is the benefit?
</blockquote></details>

It's strange that other contract that will impl this ABI will actually impl it, and this one wouldn't. I feel it might also lead to future bugs I don't yet think of if we don't do the same as other contracts that impl this ABI.
Anyway - added "consider"
___
*[`crates/starknet/src/plugin_test_data/contract` line 29 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1499#-NKEJSysBdBeTu2hHwZc:-NKEMDNxEhCWygmplssL:b-w47771) ([raw file](https://github.com/starkware-libs/cairo/blob/09b7f401e12370abd98d350ac50a71a690badd57/crates/starknet/src/plugin_test_data/contract#L29)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

didn't you remove that?
</blockquote></details>

rebased...

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 8 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1499#-:-NKEQ0iEAiZ9yi7Mt2Ze:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 1 of 8 files at r1, 6 of 7 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1499)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1499)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
