### PR TITLE
Add flag to enable gas to cairo-test

### PR DESCRIPTION
**Pull request by maciektr**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5288)

### CODE REVIEW

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5288#-:-NtQN-x35bqfQ-dfBThT:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5288)* status: all files reviewed, 1 unresolved discussion (waiting on @maciektr)

___
*[`crates/bin/cairo-test/src/main.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5288#-NtQZnDoDKPAjcDpPkVa:-NtQZnDoDKPAjcDpPkVb:b-p15pmz) ([raw file](https://github.com/starkware-libs/cairo/blob/fe38492fd9064b1a572fa3fd1eb8d5aa4ae4729a/crates/bin/cairo-test/src/main.rs#L59)):*
> ```XML
>     #[clap(short, long, default_value_t, value_enum)]
>     run_profiler: RunProfilerConfigArg,
>     /// Should enable gas calculation.
> ```

should this affect all gas operations?
no auto-gas addition and so on?



_Code quote:_
```XML
    /// Should enable gas calculation.
```

**Comment by maciektr** [comment]
*[`crates/bin/cairo-test/src/main.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5288#-NtQZnDoDKPAjcDpPkVa:-NtREgh30-rPea9m_g_P:b-kzifct) ([raw file](https://github.com/starkware-libs/cairo/blob/fe38492fd9064b1a572fa3fd1eb8d5aa4ae4729a/crates/bin/cairo-test/src/main.rs#L59)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

should this affect all gas operations?
no auto-gas addition and so on?
</blockquote></details>

Yes, this actually should affect both. I will update this to include compilation as well. Sorry, I thought about running only, because that's what we use in Scarb.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5288)* status: all files reviewed, 1 unresolved discussion (waiting on @maciektr)

___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 304 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5288#-NtRFNUE9XKoBaTpmyWF:-NtRFNUFA3rUASFZ6bVL:b4b384a) ([raw file](https://github.com/starkware-libs/cairo/blob/95cebb9c604e003cfeff124a255306e249a643cb/crates/cairo-lang-test-runner/src/lib.rs#L304)):*
> ```XML
> }
> 
> pub struct RunTestsFlags {
> ```

doc (including fields)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5288#-:-NtRL5V463ViHtqKTHrl:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @maciektr)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5288)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @maciektr)

**Pull request merged**
