### PR TITLE
Updated get gas to support range-check added with const.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:8ea3bcc2

---

**Stack**:
- #1369
- #1368
- #1367
- #1366
- #1365
- #1364 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1364)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1364)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1364#-:-NJdQ5N_Bj-7G_BU2mlj:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/sierra_to_casm/src/compiler_test.rs` line 290 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1364#-NJdPRPQ-keYIyvYLHA4:-NJdPRPQ-keYIyvYLHA5:bmxhwyj) ([raw file](https://github.com/starkware-libs/cairo/blob/af969b98b33195f10905ccefc671f3c7770ec7b6/crates/sierra_to_casm/src/compiler_test.rs#L290)):*
> ```XML
>                 %{ memory[ap + 0] = 799 < memory[ap + -2] %}
>                 jmp rel 9 if [ap + 0] != 0, ap++;
>                 [ap + -3] = [ap + 0] + 799, ap++;
> ```

It is usually clearer when the [ap + 0] is on the lhs, guess that it's from inside the builder?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1364)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/sierra_to_casm/src/compiler_test.rs` line 290 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1364#-NJdPRPQ-keYIyvYLHA4:-NJdQrvt5mCX6GjMTOjc:b-a3sgxz) ([raw file](https://github.com/starkware-libs/cairo/blob/af969b98b33195f10905ccefc671f3c7770ec7b6/crates/sierra_to_casm/src/compiler_test.rs#L290)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

It is usually clearer when the [ap + 0] is on the lhs, guess that it's from inside the builder?
</blockquote></details>

yeah - but the main idea here was reducing the number of immediates - since it is currently a bit annoying to add these all the time.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1364)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
