### PR TITLE
Handling impl alias generics lookup.

### PR DESCRIPTION
**Pull request by orizi**
Prevents impl alias resolve.

---

**Stack**:
- #3993
- #3992
- #3989
- #3990 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3990)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3990)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/test_db.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3990#-Nd6Q2tU9PCVrA-vm_OV:-Nd6Q2tU9PCVrA-vm_OW:b-5t9uma) ([raw file](https://github.com/starkware-libs/cairo/blob/65ab3724d0bae3bd5004ae9f9e77d72c041955c3/crates/cairo-lang-semantic/src/test_db.rs#L12)):*
> ```XML
> 
> #[salsa::database(SemanticDatabase, DefsDatabase, ParserDatabase, SyntaxDatabase, FilesDatabase)]
> pub struct SemanticDatabaseForTesting {
> ```

this already exists in semantic/..//test_utils.rs
___
*[`crates/cairo-lang-semantic/src/items/impl_alias.rs` line 179 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3990#-Nd6R_6fDDKXArNuKKFb:-Nd6R_6fDDKXArNuKKFc:bs7kvap) ([raw file](https://github.com/starkware-libs/cairo/blob/65ab3724d0bae3bd5004ae9f9e77d72c041955c3/crates/cairo-lang-semantic/src/items/impl_alias.rs#L179)):*
> ```XML
> 
> /// Query implementation of [crate::db::SemanticGroup::impl_alias_impl_def].
> pub fn impl_alias_impl_def(db: &dyn SemanticGroup, impl_alias_id: ImplAliasId) -> Maybe<ImplDefId> {
> ```

the computation should be done in `priv_impl_alias_semantic_data`. This should be a selector.
___
*[`crates/cairo-lang-semantic/src/items/impl_alias.rs` line 183 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3990#-Nd6SCIwAZhwiGyVBK3v:-Nd6SCIwAZhwiGyVBK3w:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/65ab3724d0bae3bd5004ae9f9e77d72c041955c3/crates/cairo-lang-semantic/src/items/impl_alias.rs#L183)):*
> ```XML
>     let mut diagnostics = SemanticDiagnostics::new(module_file_id.file_id(db.upcast())?);
> 
>     let module_impls = db.module_impl_aliases(module_file_id.0)?;
> ```





_Suggestion:_
```XML
 module_impl_aliases
```
___
*[`crates/cairo-lang-semantic/src/items/impl_alias.rs` line 186 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3990#-Nd6SbR6ApJlcwtperbP:-Nd6SbR6ApJlcwtperbQ:b5aa6xv) ([raw file](https://github.com/starkware-libs/cairo/blob/65ab3724d0bae3bd5004ae9f9e77d72c041955c3/crates/cairo-lang-semantic/src/items/impl_alias.rs#L186)):*
> ```XML
>     let syntax_db = db.upcast();
>     let impl_alias_ast = module_impls.get(&impl_alias_id).to_maybe()?;
>     let inference_id = InferenceId::ImplAliasTrait(impl_alias_id);
> ```

what does "Trait" mean here? I think it should be ImplAliasImplDef



_Code quote:_
```XML
ImplAliasTrait
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3990)* status: all files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/test_db.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3990#-Nd6Q2tU9PCVrA-vm_OV:-Nd7CEzDCtIewHayFs2Z:b50b9y8) ([raw file](https://github.com/starkware-libs/cairo/blob/65ab3724d0bae3bd5004ae9f9e77d72c041955c3/crates/cairo-lang-semantic/src/test_db.rs#L12)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

this already exists in semantic/..//test_utils.rs
</blockquote></details>

i have no idea how this appeared. removed.
___
*[`crates/cairo-lang-semantic/src/items/impl_alias.rs` line 179 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3990#-Nd6R_6fDDKXArNuKKFb:-Nd7CeG-BzyJdPSZNfV_:b4b3pub) ([raw file](https://github.com/starkware-libs/cairo/blob/65ab3724d0bae3bd5004ae9f9e77d72c041955c3/crates/cairo-lang-semantic/src/items/impl_alias.rs#L179)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

the computation should be done in `priv_impl_alias_semantic_data`. This should be a selector.
</blockquote></details>

no it shouldn't - that was exactly the cause of the cycle this prevents.
Here it just resolves where is the generic impl this points to - it does not resolve it.
___
*[`crates/cairo-lang-semantic/src/items/impl_alias.rs` line 186 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3990#-Nd6SbR6ApJlcwtperbP:-Nd7CyYHBp1s6VTF_W1E:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/65ab3724d0bae3bd5004ae9f9e77d72c041955c3/crates/cairo-lang-semantic/src/items/impl_alias.rs#L186)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

what does "Trait" mean here? I think it should be ImplAliasImplDef
</blockquote></details>

Done.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3990#-:-Nd9uSQe8-ztLSLFe6QP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/items/impl_alias.rs` line 183 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3990#-Nd6SCIwAZhwiGyVBK3v:-Nd9uCf2-DExoCP-fW5b:b-ju3kiw) ([raw file](https://github.com/starkware-libs/cairo/blob/65ab3724d0bae3bd5004ae9f9e77d72c041955c3/crates/cairo-lang-semantic/src/items/impl_alias.rs#L183)):*
> ```XML
>     let mut diagnostics = SemanticDiagnostics::new(module_file_id.file_id(db.upcast())?);
> 
>     let module_impls = db.module_impl_aliases(module_file_id.0)?;
> ```

I don't see the change

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3990)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/items/impl_alias.rs` line 183 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3990#-Nd6SCIwAZhwiGyVBK3v:-Nd9upLd7w1uTPmvo715:b-v3xndw) ([raw file](https://github.com/starkware-libs/cairo/blob/65ab3724d0bae3bd5004ae9f9e77d72c041955c3/crates/cairo-lang-semantic/src/items/impl_alias.rs#L183)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I don't see the change
</blockquote></details>

Somehow wasn't pushed. Done.

**Pull request merged**
