### PR TITLE
Make cycle lookup dependency type based.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4809)

### CODE REVIEW

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4809)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/graph_algorithms/cycles.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4809#-NoHnH6gASr0pAAN5N8F:-NoHnH6gASr0pAAN5N8G:bo5cpot) ([raw file](https://github.com/starkware-libs/cairo/blob/09e8b08cd74492307691e3b884564a366d3e2c2e/crates/cairo-lang-lowering/src/graph_algorithms/cycles.rs#L16)):*
> ```XML
> ) -> Maybe<OrderedHashSet<FunctionId>> {
>     let lowered = db.function_with_body_lowering(function_id)?;
>     Ok(get_direct_callees(&lowered, dependency_type).into_iter().collect())
> ```

Nice :)
___
*[`tests/e2e_test_data/libfuncs/coupon` line 217 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4809#-NoHo6-r5Ek5hp8T_AMB:-NoHo6-r5Ek5hp8T_AMC:bsj6u8c) ([raw file](https://github.com/starkware-libs/cairo/blob/09e8b08cd74492307691e3b884564a366d3e2c2e/tests/e2e_test_data/libfuncs/coupon#L217)):*
> ```
> }
> 
> fn destruct(arr: Array<(NonDroppable, destruct::Coupon)>) nopanic {
> ```

Can you revert the changes in this test to what it was before the workaround?
```
git checkout -p origin/coupons tests/e2e_test_data/libfuncs/coupon
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4809)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`tests/e2e_test_data/libfuncs/coupon` line 217 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4809#-NoHo6-r5Ek5hp8T_AMB:-NoHzrhAAIuB2ptcFQ4O:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/09e8b08cd74492307691e3b884564a366d3e2c2e/tests/e2e_test_data/libfuncs/coupon#L217)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Can you revert the changes in this test to what it was before the workaround?
```
git checkout -p origin/coupons tests/e2e_test_data/libfuncs/coupon
```
</blockquote></details>

Done.

**Review by liorgold2 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4809)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4809#-:-NoRVmQlCcpUV1YasZ2p:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
