### PR TITLE
Added tuple implementation for Clone and Destruct.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #5871
- #5870
- #5869
- #5867
- #5858
- #5852
- #5865 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5865)

### CODE REVIEW

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5865)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/clone.cairo` line 30 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5865#-O09EcYz4-tSCCLXR9T3:-O09EcYz4-tSCCLXR9T4:b9ss8mv) ([raw file](https://github.com/starkware-libs/cairo/blob/e7d8c278d25f754117dad5fa8e60eccfe67f205d/corelib/src/clone.cairo#L30)):*
> ```Cairo
> }
> 
> /// An implementation of `CloneHelper` for a snapshot of any type with `PartialEq`
> ```

PartialEq?



_Code quote:_
```Cairo
/// An implementation of `CloneHelper` for a snapshot of any type with `PartialEq`
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5865)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`corelib/src/clone.cairo` line 30 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5865#-O09EcYz4-tSCCLXR9T3:-O09HUWD68A3YE3vsEPs:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e7d8c278d25f754117dad5fa8e60eccfe67f205d/corelib/src/clone.cairo#L30)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

PartialEq?
</blockquote></details>

Done.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5865#-:-O09trIO3ScUxQmAusWC:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by gilbens-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5865)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5865)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @orizi)

**Pull request merged**
