### PR TITLE
Remove FlatBlock::inputs.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
Add FlatLowered::parameters for function parameters.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2436)

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
> Reviewed 10 of 57 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2436)* status: 10 of 57 files reviewed, all discussions resolved (waiting on @spapinistarkware and @yuvalsw)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 51 of 57 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2436#-:-NQJh8V_Dw2fjNaWNOhU:bnfp4nl)* status: 55 of 57 files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2436)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 48 of 57 files at r1, 7 of 8 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2436)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2436)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
