### PR TITLE
Avoid call to panic_with_byte_array in simple usage of panic!

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5958)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5958)* status: 2 of 7 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/inline_macros/panic.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5958#-O0yXeoD5A7D-c0XyLFF:-O0yXeoD5A7D-c0XyLFG:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/54adc0bb9ab5c1c3f1d49ba814ed6fa7721f9d82/crates/cairo-lang-semantic/src/inline_macros/panic.rs#L56)):*
> ```XML
>     ));
> 
>     true
> ```





_Suggestion:_
```XML
    
    if format_str.find(|c| c == '{' || c == '}').is_some() {
        return false;
    }
    builder.add_str(&format!(
        "core::panic(array![core::byte_array::BYTE_ARRAY_MAGIC, {}, ",
        format_str.len() / FELT252_BYTES,
    ));
    for chunk in format_str.as_bytes().chunks(FELT252_BYTES) {
        builder.add_str(&format!("{:#x}, ", BigInt::from_bytes_be(Sign::Plus, chunk)));
    }
    let remainder_size = format_str.len() % FELT252_BYTES;
    if remainder_size == 0 {
        // Adding the empty remainder word.
        builder.add_str("0, ");
    }
    builder.add_str(&format!("{remainder_size}))"));
    true
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5958)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/inline_macros/panic.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5958#-O0yXeoD5A7D-c0XyLFF:-O1B37el8DmrtplXCCc4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/54adc0bb9ab5c1c3f1d49ba814ed6fa7721f9d82/crates/cairo-lang-semantic/src/inline_macros/panic.rs#L56)):*
> ```XML
>     ));
> 
>     true
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5958)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/expansion_test_data/inline_macros` line 119 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5958#-O1B9SIoCpgKojaHizgG:-O1B9SIoCpgKojaHizgH:bq7zocd) ([raw file](https://github.com/starkware-libs/cairo/blob/da882814c82e8b9997c6f9b9c99b36cd002307b7/crates/cairo-lang-semantic/src/expr/expansion_test_data/inline_macros#L119)):*
> ```
> //! > ==========================================================================
> 
> //! > Test expansion of panic macro with a simple long string
> ```

can you add a test with length that divides by 31?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5958)* status: 2 of 7 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/expansion_test_data/inline_macros` line 119 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5958#-O1B9SIoCpgKojaHizgG:-O1BFep7AT8vtB_7cQhu:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/da882814c82e8b9997c6f9b9c99b36cd002307b7/crates/cairo-lang-semantic/src/expr/expansion_test_data/inline_macros#L119)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can you add a test with length that divides by 31?
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5958#-:-O1BHwhk7VPh38ZrGGPX:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5958)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/inline_macros/panic.rs` line 24 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5958#-O1BMOsW9YXeyAACs5xe:-O1BMOsW9YXeyAACs5xf:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/142d5dca2cfe0387e76085f58b8433a75e4c2f48/crates/cairo-lang-semantic/src/inline_macros/panic.rs#L24)):*
> ```XML
>         [] => {
>             // Trivial panic!() with no arguments case.
>             builder.add_str("core::panic(array![core::byte_array::BYTE_ARRAY_MAGIC, 0, 0, 0);");
> ```

.



_Suggestion:_
```XML
            builder.add_str("core::panics::panic(array![core::byte_array::BYTE_ARRAY_MAGIC, 0, 0, 0);");
```
___
*[`crates/cairo-lang-semantic/src/inline_macros/panic.rs` line 63 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5958#-O1BMSYL9LbRzRaSeYEG:-O1BMSYL9LbRzRaSeYEH:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/142d5dca2cfe0387e76085f58b8433a75e4c2f48/crates/cairo-lang-semantic/src/inline_macros/panic.rs#L63)):*
> ```XML
> 
>     builder.add_str(&format!(
>         "core::panic(array![core::byte_array::BYTE_ARRAY_MAGIC, 0, '{}', {}",
> ```

.



_Suggestion:_
```XML
    builder.add_str(&format!(
        "core::panics::panic(array![core::byte_array::BYTE_ARRAY_MAGIC, 0, '{}', {}",
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5958#-:-O1BSlo89QHqtGGaTb2o:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5958)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/byte_array.cairo` line 17 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5958#-O1B_h2WBlexslRAda7c:-O1B_h2XA8i1OfOsmuvo:b-qlyasi) ([raw file](https://github.com/starkware-libs/cairo/blob/791d702408ec3cdbfb649c62d14eadd54efc055f/corelib/src/byte_array.cairo#L17)):*
> ```Cairo
> /// magic as one of the felt252s indicates that right after it you should expect a serialized
> /// ByteArray. This is currently used mainly for prints and panics.
> pub(crate) const BYTE_ARRAY_MAGIC: felt252 =
> ```

Note that I had to make this public and I'm not sure this is the right place for this const



_Code quote:_
```Cairo
pub(crate) const BYTE_ARRAY_MAGIC
```

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5958)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/byte_array.cairo` line 17 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5958#-O1B_h2WBlexslRAda7c:-O1BmRPp2Y4JNf9K2kbj:bi7uve0) ([raw file](https://github.com/starkware-libs/cairo/blob/791d702408ec3cdbfb649c62d14eadd54efc055f/corelib/src/byte_array.cairo#L17)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Note that I had to make this public and I'm not sure this is the right place for this const
</blockquote></details>

I don't really have a better in place in mind for the time being - and it isn't *too* bad.

**Pull request merged**
