### PR TITLE
Made request embeddable add drop only if required, and component add drop.

### PR DESCRIPTION
**Pull request by orizi**
Added a full expansion test of componenet usage.

---

**Stack**:
- #3993
- #3992
- #3989 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3989)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, 1 of 4 files at r2, 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3989)* status: 12 of 13 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/embedded_impl` line 9 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3989#-Nd6BdYh3BoC6zP3rCrH:-Nd6BdYh3BoC6zP3rCrI:beolhhx) ([raw file](https://github.com/starkware-libs/cairo/blob/86c4dfd98f0781e0343b6af18f8a2617c7226dc8/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/embedded_impl#L9)):*
> ```
> #[starknet::embeddable(v0)]
> #[generate_trait]
> impl OutsideImpl<TContractState, impl DropTContractState: Drop<TContractState>> of OutsideTrait<TContractState, DropTContractState> {
> ```

As discussed, I don't like the additional requirement for impls with #[embeddable]. Let's try to remove it (either by making sure we don't need this PR or by adding the drop impl in the generated data, conditionally).
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_ownable` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3989#-Nd60iV07s2GxKngjqE1:-Nd60iV07s2GxKngjqE2:borvic9) ([raw file](https://github.com/starkware-libs/cairo/blob/873b18285da9714503f1fbb50057058119138ce5/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_ownable#L18)):*
> ```
>     #[derive(Copy, Drop, starknet::Event)]
>     struct Event {
>     }
> ```

can remove



_Code quote:_
```
    #[event]
    #[derive(Copy, Drop, starknet::Event)]
    struct Event {
    }
```
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_ownable` line 64 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3989#-Nd6AVORBY6c2t57vlNB:-Nd6AVORBY6c2t57vlNC:b-y7cizo) ([raw file](https://github.com/starkware-libs/cairo/blob/873b18285da9714503f1fbb50057058119138ce5/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_ownable#L64)):*
> ```
>     #[embed(v0)]
>     impl OwnershipTransfer = super::ownable::Transfer<ContractState>;
>     use super::ownable::TransferTrait;
> ```

this should not be needed.
(although maybe we didn't add traits for impl aliases to the context. I can do it if this is the issue here)



_Code quote:_
```
use super::ownable::TransferTrait;
```
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_ownable` line 66 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3989#-Nd6Amow1mKNbE7k7CPo:-Nd6Amow1mKNbE7k7CPp:beuntv6) ([raw file](https://github.com/starkware-libs/cairo/blob/873b18285da9714503f1fbb50057058119138ce5/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_ownable#L66)):*
> ```
>     use super::ownable::TransferTrait;
> 
>     #[embed(v0)]
> ```

shouldn't embed only work with impl alias? what does it mean here?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3989)* status: 12 of 13 files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_ownable` line 64 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3989#-Nd6AVORBY6c2t57vlNB:-Nd7EUvaBVynBhZPtpIV:bi311c9) ([raw file](https://github.com/starkware-libs/cairo/blob/873b18285da9714503f1fbb50057058119138ce5/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_ownable#L64)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

this should not be needed.
(although maybe we didn't add traits for impl aliases to the context. I can do it if this is the issue here)
</blockquote></details>

how would this not be needed?
this is the trait of the component (not for the contract) how would it be available here?
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_ownable` line 66 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3989#-Nd6Amow1mKNbE7k7CPo:-Nd7EkEu9niUU_Iwntl1:b-oc3tt2) ([raw file](https://github.com/starkware-libs/cairo/blob/873b18285da9714503f1fbb50057058119138ce5/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_ownable#L66)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

shouldn't embed only work with impl alias? what does it mean here?
</blockquote></details>

embed on impl means to embed the impl in the contract - 
this makes it possible to call functions by `self.member()` while still actually being a part of the abi, without implementing an external trait.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3989)* status: 7 of 15 files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/embedded_impl` line 9 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3989#-Nd6BdYh3BoC6zP3rCrH:-Nd9VqCv4SYgRyVEq0o2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c4689a04f8fccb321059cc644783df4fda0ce313/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/embedded_impl#L9)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

As discussed, I don't like the additional requirement for impls with #[embeddable]. Let's try to remove it (either by making sure we don't need this PR or by adding the drop impl in the generated data, conditionally).
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_ownable` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3989#-Nd60iV07s2GxKngjqE1:-Nd9Vox-41JTfJQGwpvH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/873b18285da9714503f1fbb50057058119138ce5/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_ownable#L18)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

can remove
</blockquote></details>

Done.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3989)* status: all files reviewed, 6 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/embeddable.rs` line 40 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3989#-Nd9wg897hii_yrrhgUo:-Nd9wg897hii_yrrhgUp:bdtiiz0) ([raw file](https://github.com/starkware-libs/cairo/blob/e523ecb5cd93644b98ba0ea048c0eeb5e415bcdb/crates/cairo-lang-starknet/src/plugin/embeddable.rs#L40)):*
> ```XML
>             let has_drop_impl = elements.iter().any(|param| {
>                 if let ast::GenericParam::Impl(i) = param {
>                     is_name_with_arg(db, &i.trait_path(db), "Drop", GENERIC_CONTRACT_STATE_NAME)
> ```

Can this be a method of ExprPath?



_Code quote:_
```XML
is_name_with_arg
```
___
*[`crates/cairo-lang-starknet/src/plugin/embeddable.rs` line 40 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3989#-Nd9zsF17DC_-bpZNOCj:-Nd9zsF17DC_-bpZNOCk:bhca72o) ([raw file](https://github.com/starkware-libs/cairo/blob/e523ecb5cd93644b98ba0ea048c0eeb5e415bcdb/crates/cairo-lang-starknet/src/plugin/embeddable.rs#L40)):*
> ```XML
>             let has_drop_impl = elements.iter().any(|param| {
>                 if let ast::GenericParam::Impl(i) = param {
>                     is_name_with_arg(db, &i.trait_path(db), "Drop", GENERIC_CONTRACT_STATE_NAME)
> ```

I think you also need to check Destruct and PanicDestruct and fail the generation in those cases with a proper diagnostic.
If you generate with an additional Drop impl, then there would be 2 impls of PanicDestruct.



_Code quote:_
```XML
Drop", 
```
___
*[`crates/cairo-lang-starknet/src/plugin/utils.rs` line 31 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3989#-NdA-uy0ESWHJwq7NMj7:-NdA-uy0ESWHJwq7NMj8:bv4vl47) ([raw file](https://github.com/starkware-libs/cairo/blob/e523ecb5cd93644b98ba0ea048c0eeb5e415bcdb/crates/cairo-lang-starknet/src/plugin/utils.rs#L31)):*
> ```XML
> /// Returns true if type_ast is `name`.
> /// Does not resolve paths or type aliases.
> pub fn is_name(db: &dyn SyntaxGroup, type_ast: &ast::Expr, name: &str) -> bool {
> ```

this name is too generic.
And maybe use `identifier` instead of name?
Suggestion: `is_expr_identifier`.



_Code quote:_
```XML
is_name
```
___
*[`crates/cairo-lang-starknet/src/plugin/utils.rs` line 55 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3989#-NdA1XWs1s1ENCG_3TtK:-NdA1XWs1s1ENCG_3TtL:b-jbtnqv) ([raw file](https://github.com/starkware-libs/cairo/blob/e523ecb5cd93644b98ba0ea048c0eeb5e415bcdb/crates/cairo-lang-starknet/src/plugin/utils.rs#L55)):*
> ```XML
> /// Returns true if `type_path` matches `$name$<$arg$>`.
> /// Does not resolve paths, type aliases or named generics.
> pub fn is_name_with_arg(
> ```

If possible, add this as a method of ExprPath, and add a similar one for Expr (which can be used in is_felt252_span). This can be done in helpers.rs.
If not possible for some reason, I suggest to call it is_path_name_with_arg (and also add is_expr_name_with_arg).



_Code quote:_
```XML
fn is_name_with_arg(
```
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_ownable` line 64 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3989#-Nd6AVORBY6c2t57vlNB:-NdA30ZUB8uoOtfxHhW9:bb4b877) ([raw file](https://github.com/starkware-libs/cairo/blob/873b18285da9714503f1fbb50057058119138ce5/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_ownable#L64)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

how would this not be needed?
this is the trait of the component (not for the contract) how would it be available here?
</blockquote></details>

As the impl you embed implements it.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_ownable` line 66 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3989#-Nd6Amow1mKNbE7k7CPo:-NdA3EY6-YKjuijA38qg:bpom71v) ([raw file](https://github.com/starkware-libs/cairo/blob/873b18285da9714503f1fbb50057058119138ce5/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_ownable#L66)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

embed on impl means to embed the impl in the contract - 
this makes it possible to call functions by `self.member()` while still actually being a part of the abi, without implementing an external trait.
</blockquote></details>

I guess it's unrelated to this PR, but isn't it a little strange? To `embed` something that already written directly in the contract?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3989)* status: all files reviewed, 5 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/embeddable.rs` line 40 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3989#-Nd9wg897hii_yrrhgUo:-NdA8k6v5344x3VqJQXO:b-vpj7df) ([raw file](https://github.com/starkware-libs/cairo/blob/e523ecb5cd93644b98ba0ea048c0eeb5e415bcdb/crates/cairo-lang-starknet/src/plugin/embeddable.rs#L40)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Can this be a method of ExprPath?
</blockquote></details>

it can be - but i don't really think it should, as this is for the plugin area.
I'm adding this here as an external helper instead.
___
*[`crates/cairo-lang-starknet/src/plugin/utils.rs` line 31 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3989#-NdA-uy0ESWHJwq7NMj7:-NdA9UOMCxwHgdZf3QuY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e523ecb5cd93644b98ba0ea048c0eeb5e415bcdb/crates/cairo-lang-starknet/src/plugin/utils.rs#L31)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

this name is too generic.
And maybe use `identifier` instead of name?
Suggestion: `is_expr_identifier`.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_ownable` line 64 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3989#-Nd6AVORBY6c2t57vlNB:-NdADx7n5-YLhR4JXWHh:b-w398zc) ([raw file](https://github.com/starkware-libs/cairo/blob/873b18285da9714503f1fbb50057058119138ce5/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_ownable#L64)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

As the impl you embed implements it.
</blockquote></details>

i call it on the member - not the contract.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_ownable` line 66 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3989#-Nd6Amow1mKNbE7k7CPo:-NdAE3fD2DT8DeW4pAL-:bc88w85) ([raw file](https://github.com/starkware-libs/cairo/blob/873b18285da9714503f1fbb50057058119138ce5/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_ownable#L66)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I guess it's unrelated to this PR, but isn't it a little strange? To `embed` something that already written directly in the contract?
</blockquote></details>

that was the other "include" - we can discuss further with the team.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3989)* status: 13 of 16 files reviewed, 5 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/embeddable.rs` line 40 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3989#-Nd9zsF17DC_-bpZNOCj:-NdAGaWG7r-yJ7UdrpZk:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e523ecb5cd93644b98ba0ea048c0eeb5e415bcdb/crates/cairo-lang-starknet/src/plugin/embeddable.rs#L40)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I think you also need to check Destruct and PanicDestruct and fail the generation in those cases with a proper diagnostic.
If you generate with an additional Drop impl, then there would be 2 impls of PanicDestruct.
</blockquote></details>

Done.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3989)* status: all files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/embeddable.rs` line 51 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3989#-NdAIRb49iA4w3ZicNi6:-NdAIRb52nybgnV551iR:b-ahqpsw) ([raw file](https://github.com/starkware-libs/cairo/blob/b66dec57c1895e619f2962a68b2e3363908f8f9e/crates/cairo-lang-starknet/src/plugin/embeddable.rs#L51)):*
> ```XML
>             });
>             for param in &elements {
>                 if matches!(param, ast::GenericParam::Impl(imp) if imp.trait_path(db).is_path_name_with_arg(db, "Destruct", GENERIC_CONTRACT_STATE_NAME) || imp.trait_path(db).is_path_name_with_arg(db, "PanicDestruct", GENERIC_CONTRACT_STATE_NAME))
> ```

can you please add a test for these cases?
___
*[`crates/cairo-lang-starknet/src/plugin/embeddable.rs` line 53 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3989#-NdAI7tHChAYEqKHW9Mr:-NdAI7tHChAYEqKHW9Ms:bksv2sf) ([raw file](https://github.com/starkware-libs/cairo/blob/b66dec57c1895e619f2962a68b2e3363908f8f9e/crates/cairo-lang-starknet/src/plugin/embeddable.rs#L53)):*
> ```XML
>                 if matches!(param, ast::GenericParam::Impl(imp) if imp.trait_path(db).is_path_name_with_arg(db, "Destruct", GENERIC_CONTRACT_STATE_NAME) || imp.trait_path(db).is_path_name_with_arg(db, "PanicDestruct", GENERIC_CONTRACT_STATE_NAME))
>                 {
>                     diagnostics.push(PluginDiagnostic {
> ```

should we generate the code if there is a diagnostic?
___
*[`crates/cairo-lang-starknet/src/plugin/embeddable.rs` line 56 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3989#-NdAHf6sDEwCSnsj2kzk:-NdAHf6sDEwCSnsj2kzl:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b66dec57c1895e619f2962a68b2e3363908f8f9e/crates/cairo-lang-starknet/src/plugin/embeddable.rs#L56)):*
> ```XML
>                         stable_ptr: param.stable_ptr().untyped(),
>                         message: "Embeddable impl params cannot be for `Destruct` or \
>                                   `PanicDestruct`."
> ```





_Suggestion:_
```XML
                        message: "Embeddable impl can't have impl generic params of `Destruct<TContractState>` or \
                                  `PanicDestruct<TContractState>`."
```
___
*[`crates/cairo-lang-starknet/src/plugin/utils.rs` line 35 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3989#-NdAJ5uL-xWcU7gH8IQi:-NdAJ5uM7KGAjDioP4V7:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b66dec57c1895e619f2962a68b2e3363908f8f9e/crates/cairo-lang-starknet/src/plugin/utils.rs#L35)):*
> ```XML
>         path_name: &str,
>         generic_arg: &str,
>     ) -> bool;
> ```





_Suggestion:_
```XML
    fn is_name_with_arg(
        &self,
        db: &dyn SyntaxGroup,
        name: &str,
        generic_arg: &str,
    ) -> bool;
```
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_ownable` line 64 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3989#-Nd6AVORBY6c2t57vlNB:-NdAKjKj0nriWU3dKpMU:b-7832v3) ([raw file](https://github.com/starkware-libs/cairo/blob/873b18285da9714503f1fbb50057058119138ce5/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_ownable#L64)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i call it on the member - not the contract.
</blockquote></details>

NM, this should not block this PR

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3989)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/embeddable.rs` line 53 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3989#-NdAI7tHChAYEqKHW9Mr:-NdB1her27t9Ff8xEfAP:bedkj8p) ([raw file](https://github.com/starkware-libs/cairo/blob/b66dec57c1895e619f2962a68b2e3363908f8f9e/crates/cairo-lang-starknet/src/plugin/embeddable.rs#L53)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

in this case - i think so - as the error that will be created by this is way downstream.
</blockquote></details>

I thought we need not to generate the code as this would lead to more (confusing) diagnostics. But as per the other comment - there are no other diagnostics, and it seems right (nothing that may need to be panic-destructed of type TContractState), so I am not sure again that this PR is needed.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/embedded_impl` line 364 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3989#-NdB0rUp8VurIHtzBiZ9:-NdB0rUp8VurIHtzBiZA:b-lbw41h) ([raw file](https://github.com/starkware-libs/cairo/blob/171870007779843a8bda444fbd583634a14830bb/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/embedded_impl#L364)):*
> ```
>     serde::Serde::<felt252>::serialize(@res, ref arr);
>     array::ArrayTrait::span(@arr)
> }
> ```

The fact that there are no further diagnostics besides the ones by the plugin, and that here we have both impls and all works (as we don't have anything of type TContractState), so no panic causes an ambiguous call - maybe means that this is not needed?



_Code quote:_
```
#[implicit_precedence(Pedersen, RangeCheck, Bitwise, EcOp, Poseidon, SegmentArena, GasBuiltin, System)]
fn __wrapper_ret_3<TContractState,
    impl DisallowedDestruct: Destruct<TContractState>,impl UnsafeNewContractState: UnsafeNewContractStateTraitForOutsideImplWithDestruct<TContractState>, impl TContractStateDrop: Drop<TContractState>>(mut data: Span::<felt252>) -> Span::<felt252> {
    internal::require_implicit::<System>();
    internal::revoke_ap_tracking();
    option::OptionTraitImpl::expect(gas::withdraw_gas(), 'Out of gas');

    assert(array::SpanTrait::is_empty(data), 'Input too long for arguments');
    option::OptionTraitImpl::expect(
        gas::withdraw_gas_all(get_builtin_costs()), 'Out of gas',
    );
    let mut contract_state = UnsafeNewContractState::unsafe_new_contract_state();
    let res = OutsideImplWithDestruct::<TContractState, DisallowedDestruct>::ret_3(@contract_state, );
    let mut arr = array::array_new();
    // References.
    // Result.
    serde::Serde::<felt252>::serialize(@res, ref arr);
    array::ArrayTrait::span(@arr)
}
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3989)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/embeddable.rs` line 53 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3989#-NdAI7tHChAYEqKHW9Mr:-NdBlU6F3chOF8neeI75:b-p59xf5) ([raw file](https://github.com/starkware-libs/cairo/blob/b66dec57c1895e619f2962a68b2e3363908f8f9e/crates/cairo-lang-starknet/src/plugin/embeddable.rs#L53)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I thought we need not to generate the code as this would lead to more (confusing) diagnostics. But as per the other comment - there are no other diagnostics, and it seems right (nothing that may need to be panic-destructed of type TContractState), so I am not sure again that this PR is needed.
</blockquote></details>

It makes the compiler panic at sierra gen stage, it is something much deeper in handling of different destruct types.
Since this is currently caused by something unnecessary, we can investigate, but I don't want this investigatation to block us.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3989#-:-NdPQ8CC2BMrY8NDpXA2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/embeddable.rs` line 53 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3989#-NdAI7tHChAYEqKHW9Mr:-NdPPb7a4JIpMhsoycAo:b-thxfdi) ([raw file](https://github.com/starkware-libs/cairo/blob/b66dec57c1895e619f2962a68b2e3363908f8f9e/crates/cairo-lang-starknet/src/plugin/embeddable.rs#L53)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

It makes the compiler panic at sierra gen stage, it is something much deeper in handling of different destruct types.
Since this is currently caused by something unnecessary, we can investigate, but I don't want this investigatation to block us.
</blockquote></details>

OK, but we need to make sure to investigate - might be another bug
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/embedded_impl` line 364 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3989#-NdB0rUp8VurIHtzBiZ9:-NdPQ9L37f6j0QyLUVSp:b-pqa9gn) ([raw file](https://github.com/starkware-libs/cairo/blob/171870007779843a8bda444fbd583634a14830bb/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/embedded_impl#L364)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

The fact that there are no further diagnostics besides the ones by the plugin, and that here we have both impls and all works (as we don't have anything of type TContractState), so no panic causes an ambiguous call - maybe means that this is not needed?
</blockquote></details>

Resolving per the other discussion - seems unnecessary in the cairo level, but there might be something else causing sierra gen to fail, so this is a temporary(?) workaround.

**Pull request merged**
