### PR TITLE
Fix TODO.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4910)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4910)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/ecdsa.cairo` line 29 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4910#-NoxFDmb1SIsp2R2Z_fC:-NoxFDmc3us6i53v9MsP:b-wdet1u) ([raw file](https://github.com/starkware-libs/cairo/blob/0bbd0c58f8d6ea7bb27346c511aab104e7252857/corelib/src/ecdsa.cairo#L29)):*
> ```Cairo
> ) -> bool {
>     // Check that s != 0 (mod stark_curve::ORDER).
>     if signature_s == 0 || signature_s == ec::stark_curve::ORDER {
> ```

This still seems to cause a regression.

**Review by orizi — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4910)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4910)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-runner/src/profiling_test_data/major_test_cases` line 954 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4910#-NpteUcG3MjQZvn3CulB:-NpteUcG3MjQZvn3CulC:b48kosm) ([raw file](https://github.com/starkware-libs/cairo/blob/31c21a4cb88d9a5e0cbbf1bef645c3e2be45fcad/crates/cairo-lang-runner/src/profiling_test_data/major_test_cases#L954)):*
> ```
> Weight by Sierra stack trace:
>   test::ecdsa_call: 186
>   test::ecdsa_call -> core::ecdsa::check_ecdsa_signature: 172
> ```

this actually adds 2 steps on the run.



_Code quote:_
```
  test::ecdsa_call -> core::ecdsa::check_ecdsa_signature: 172
```

**Comment by ilyalesokhin-starkware** [comment]
requires improvement to the return optimization

**Pull request closed without merging**
