### PR TITLE
Add `TryInto<u512, u256>`

### PR DESCRIPTION
**Pull request by delaaxe**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5031)

### CODE REVIEW

**Comment by delaaxe** [comment]
There's clippy errors even though I didn't change any rust code

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5031)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @delaaxe)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5031#-NqXKxY04EC3GB-lO40k:-NqXKxY04EC3GB-lO40l:b8ikomv) (no related file):*
any particular usecase for this?
in general we only use u512 for modular operation back into u256.

___

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5031)* status: all files reviewed, 3 unresolved discussions (waiting on @delaaxe)

___
*[`corelib/src/integer.cairo` line 1384 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5031#-NqYnFkV95jPo1hXrbTD:-NqYnFkV95jPo1hXrbTE:b68enyj) ([raw file](https://github.com/starkware-libs/cairo/blob/9dcdc491d6e3840680fa7b93f2cd231a2cc63a29/corelib/src/integer.cairo#L1384)):*
> ```Cairo
>         }
>     }
> }
> ```

no need (it was required in some specific other instances)



_Suggestion:_
```Cairo
impl U512TryIntoU256 of TryInto<u512, u256> {
    fn try_into(self: u512) -> Option<u256> {
        if self.limb2 != 0 || self.limb3 != 0 {
            Option::None
        } else {
            Option::Some(u256 { low: self.limb0, high: self.limb1 })
        }
    }
}
```
___
*[`corelib/src/test/integer_test.cairo` line 811 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5031#-NqYnNA4-xa9lniDMeUv:-NqYnNA4-xa9lniDMeUw:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9dcdc491d6e3840680fa7b93f2cd231a2cc63a29/corelib/src/test/integer_test.cairo#L811)):*
> ```Cairo
>     };
>     let option: Option<u256> = num.try_into();
>     assert(option.is_none(), 'u512 -/-> u256');
> ```





_Suggestion:_
```Cairo
    assert!(u512 { limb0: 1, limb1: 2, limb2: 0, limb3: 0 }.try_into() == Option::Some(0x200000000000000000000000000000001_u256));
    assert!(u512 { limb0: 1, limb1: 2, limb2: 3, limb3: 0 }.try_into() == Option::<u256>::None);
    assert!(u512 { limb0: 1, limb1: 2, limb2: 0, limb3: 4 }.try_into() == Option::<u256>::None);
    assert!(u512 { limb0: 1, limb1: 2, limb2: 3, limb3: 4 }.try_into() == Option::<u256>::None);
```

**Review by delaaxe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5031)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/integer.cairo` line 1384 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5031#-NqYnFkV95jPo1hXrbTD:-NqYyjyP3pgCuDJQnNKA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9dcdc491d6e3840680fa7b93f2cd231a2cc63a29/corelib/src/integer.cairo#L1384)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no need (it was required in some specific other instances)
</blockquote></details>

Done.
___
*[`corelib/src/test/integer_test.cairo` line 811 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5031#-NqYnNA4-xa9lniDMeUv:-NqYzBAq0hoNhmJ6r9Ff:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9dcdc491d6e3840680fa7b93f2cd231a2cc63a29/corelib/src/test/integer_test.cairo#L811)):*
> ```Cairo
>     };
>     let option: Option<u256> = num.try_into();
>     assert(option.is_none(), 'u512 -/-> u256');
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r4, 8 of 8 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5031#-:-NqZ5A26CFrm2O5lV99g:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @delaaxe)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5031#-NqZ5AfO31M0Blt05qKC:-NqZ5AfP24CciYhrHgoz:b-uuj1x0) (no related file):*
@gilbens-starkware for 2nd eye.

___

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5031)* status: all files reviewed, 1 unresolved discussion (waiting on @delaaxe)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5031#-:-NqavuDj3zzKoK-j0pt_:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @delaaxe)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5031)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @delaaxe)

**Pull request merged**
