### PR TITLE
Double buffering db in language server.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4496)

### CODE REVIEW

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4496)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4496#-NkQYKd76V3_PCIirf4v:-NkQYKd76V3_PCIirf4w:b-ebnpwn) ([raw file](https://github.com/starkware-libs/cairo/blob/d602cfd107ce7825c682521733c9e7cb8f4dd317/crates/cairo-lang-language-server/src/lib.rs#L171)):*
> ```XML
>         let mut db_mut = self.db_mutex.lock().await;
>         if let Ok(mut last_replace) = self.last_replace.try_lock() {
>             const REPLACE_INTERVAL: Duration = Duration::from_secs(1800);
> ```

Why is the const in here?



_Code quote:_
```XML
const REPLACE_INTERVAL: Duration = Duration::from_secs(1800);
```
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 176 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4496#-NkQYIF2ADFAGmAm8Ksn:-NkQYIF3CFKIOLYL7rgn:b2nhdkj) ([raw file](https://github.com/starkware-libs/cairo/blob/d602cfd107ce7825c682521733c9e7cb8f4dd317/crates/cairo-lang-language-server/src/lib.rs#L176)):*
> ```XML
>                 *last_replace = SystemTime::now();
>             }
>         }
> ```

Doc



_Code quote:_
```XML
        if let Ok(mut last_replace) = self.last_replace.try_lock() {
            const REPLACE_INTERVAL: Duration = Duration::from_secs(1800);
            if last_replace.elapsed().unwrap() > REPLACE_INTERVAL {
                *db_mut = basic_db();
                *last_replace = SystemTime::now();
            }
        }
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4496)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4496#-NkQYKd76V3_PCIirf4v:-NkVR9FpBgm_-gqgn1BF:b-gzo0n7) ([raw file](https://github.com/starkware-libs/cairo/blob/d602cfd107ce7825c682521733c9e7cb8f4dd317/crates/cairo-lang-language-server/src/lib.rs#L171)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Why is the const in here?
</blockquote></details>

because i use it only in one place - on reason for it to be golbal.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4496)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 176 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4496#-NkQYIF2ADFAGmAm8Ksn:-NkVmF01CQ1wykGEppFH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d602cfd107ce7825c682521733c9e7cb8f4dd317/crates/cairo-lang-language-server/src/lib.rs#L176)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Doc
</blockquote></details>

Done.

**Comment by MahmoudMohajer** [comment]
Good job, is it going to solve the issue or is it just a painkiller for the memory leak in the Cairo language server?

**Review by orizi — COMMENTED** [review]
There no memory leak - as all the memory is traced - the issue is that salsa is bad about releasing data, so this makes us explicity recreate the salsa db in the language server once in a while.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4496#-:-NkW4qDBCUIOzGXQTXNV:buwrgjq)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
