### PR TITLE
Crate top level documentation

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1625)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-compiler/src/lib.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1625#-NKrLRGT8aUuWU5Ii8IK:-NKrLRGT8aUuWU5Ii8IL:b-ghi8cy) ([raw file](https://github.com/starkware-libs/cairo/blob/bab32b7b4f24a377a10c303b305a7fb9a46556b9/crates/cairo-compiler/src/lib.rs#L42)):*
> ```XML
> 
> /// Compiles a Cairo project at the given path.
> /// The project must be a valid Cairo project.
> ```

Can you elaborate?



_Code quote:_
```XML
valid Cairo project
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1625)* status: 1 of 14 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-eq-solver/src/lib.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1625#-NKrLrVw200g9qv3VDZh:-NKrLrVw200g9qv3VDZi:beymlrm) ([raw file](https://github.com/starkware-libs/cairo/blob/bab32b7b4f24a377a10c303b305a7fb9a46556b9/crates/cairo-eq-solver/src/lib.rs#L17)):*
> ```XML
> /// # Returns
> /// * `Some(HashMap<Var, i64>)` - The solutions to the equations.
> /// * `None` - The equations are unsolvable or the input equations are empty.
> ```

how did you check this?



_Code quote:_
```XML
the input equations are empty
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-formatter/src/lib.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1625#-NKrM6ZF5DZDgiy_O-gm:-NKrM6ZF5DZDgiy_O-gn:b1p7fsc) ([raw file](https://github.com/starkware-libs/cairo/blob/bab32b7b4f24a377a10c303b305a7fb9a46556b9/crates/cairo-formatter/src/lib.rs#L20)):*
> ```XML
> mod test;
> 
> /// Return the formatted file as a string.
> ```

what file?



_Code quote:_
```XML
formatted file
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-sierra-ap-change/src/lib.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1625#-NKrMS4V9PAiV20U1q-M:-NKrMS4V9PAiV20U1q-N:btjtezo) ([raw file](https://github.com/starkware-libs/cairo/blob/bab32b7b4f24a377a10c303b305a7fb9a46556b9/crates/cairo-sierra-ap-change/src/lib.rs#L1)):*
> ```XML
> //! Sierra AP change computation.
> ```

not sure this is the right word.



_Code quote:_
```XML
computation
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 3 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1625)* status: 4 of 14 files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1625)* status: 3 of 23 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-compiler/src/lib.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1625#-NKrLRGT8aUuWU5Ii8IK:-NKrMhul9-dRDW-Zl3we:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bab32b7b4f24a377a10c303b305a7fb9a46556b9/crates/cairo-compiler/src/lib.rs#L42)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Can you elaborate?
</blockquote></details>

Done.
___
*[`crates/cairo-eq-solver/src/lib.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1625#-NKrLrVw200g9qv3VDZh:-NKrMivQ9dzLbIlSPkig:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bab32b7b4f24a377a10c303b305a7fb9a46556b9/crates/cairo-eq-solver/src/lib.rs#L17)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

how did you check this?
</blockquote></details>

Done.
___
*[`crates/cairo-formatter/src/lib.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1625#-NKrM6ZF5DZDgiy_O-gm:-NKrMjKn8kj-IrgThwCE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bab32b7b4f24a377a10c303b305a7fb9a46556b9/crates/cairo-formatter/src/lib.rs#L20)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what file?
</blockquote></details>

Done.
___
*[`crates/cairo-sierra-ap-change/src/lib.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1625#-NKrMS4V9PAiV20U1q-M:-NKrMjhs9P-15DtkCSeP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bab32b7b4f24a377a10c303b305a7fb9a46556b9/crates/cairo-sierra-ap-change/src/lib.rs#L1)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

not sure this is the right word.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1625)* status: 3 of 23 files reviewed, 5 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-compiler/src/lib.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1625#-NKrNE0T8M-HyYKV1PeV:-NKrNE0T8M-HyYKV1PeW:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9c701486fad65986b6e02854038cb193ba64447b/crates/cairo-compiler/src/lib.rs#L43)):*
> ```XML
> /// Compiles a Cairo project at the given path.
> /// The project must be a valid Cairo project:
> /// Either a standalone `.cairo` file (a single crate), or a directory with a `lib.cairo` file and
> ```





_Suggestion:_
```XML
cairo_project.toml
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1625)* status: 3 of 23 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-compiler/src/lib.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1625#-NKrNE0T8M-HyYKV1PeV:-NKrN_i-ECKYJwtajRCk:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9c701486fad65986b6e02854038cb193ba64447b/crates/cairo-compiler/src/lib.rs#L43)):*
> ```XML
> /// Compiles a Cairo project at the given path.
> /// The project must be a valid Cairo project:
> /// Either a standalone `.cairo` file (a single crate), or a directory with a `lib.cairo` file and
> ```

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 9 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1625)* status: 12 of 23 files reviewed, all discussions resolved

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1625#-:-NKrNcla6SxwsrIEkRQ8:bnfp4nl)* status: 12 of 23 files reviewed, all discussions resolved

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 10 of 14 files at r1, 12 of 13 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1625)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
