### PR TITLE
adding iterator to span

### PR DESCRIPTION
**Pull request by Tomer-StarkWare**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5661)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5661)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`corelib/src/array.cairo` line 341 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5661#-Nyy9v6ABJ4KhXelenGO:-Nyy9v6B3Mq-70f-kfdg:b8a5flp) ([raw file](https://github.com/starkware-libs/cairo/blob/0c9587dd4974d6206bf845c3e54cf9e859d4960b/corelib/src/array.cairo#L341)):*
> ```Cairo
> }
> 
> pub struct SpanIter<T> {
> ```

additionally doc.
___
*[`corelib/src/array.cairo` line 367 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5661#-Nyy9lxw-uc73TgFsbmE:-Nyy9lxw-uc73TgFsbmF:bjhzvdw) ([raw file](https://github.com/starkware-libs/cairo/blob/0c9587dd4974d6206bf845c3e54cf9e859d4960b/corelib/src/array.cairo#L367)):*
> ```Cairo
> struct ArrayIter<T> {
>     array: Array<T>,
> }
> ```

and doc.



_Suggestion:_
```Cairo
#[derive(Drop, Clone)]
pub struct ArrayIter<T> {
    array: Array<T>,
}
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5661)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`corelib/src/array.cairo` line 341 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5661#-Nyy9v6ABJ4KhXelenGO:-NyyCDhn9wwc6vmx7QHA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0c9587dd4974d6206bf845c3e54cf9e859d4960b/corelib/src/array.cairo#L341)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

additionally doc.
</blockquote></details>

Done.
___
*[`corelib/src/array.cairo` line 367 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5661#-Nyy9lxw-uc73TgFsbmE:-NyyEMQ78X41yfGoNrgu:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0c9587dd4974d6206bf845c3e54cf9e859d4960b/corelib/src/array.cairo#L367)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

and doc.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5661#-:-NyyKJCX1XduR2jZpeAS:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5661)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
