### PR TITLE
Added test case for new contract syntax

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3427)

### CODE REVIEW

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3427#-:-NYCHrzZAsciuXYBsjPM:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/casm_contract_class_test.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3427#-NYCHu3g7Skv_I1RYAih:-NYCHu3g7Skv_I1RYAii:bl272b7) ([raw file](https://github.com/starkware-libs/cairo/blob/68cf9cf2d9db8523c8e6d6b0bc2955db292f9945/crates/cairo-lang-starknet/src/casm_contract_class_test.rs#L32)):*
> ```XML
> }
> 
> #[test_case("test_contract")]
> ```

test_contract is old syntax?



_Code quote:_
```XML
#[test_case("test_contract")]
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3427)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/casm_contract_class_test.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3427#-NYCHu3g7Skv_I1RYAih:-NYCQliH74zYHgMpV-II:by9d3jj) ([raw file](https://github.com/starkware-libs/cairo/blob/68cf9cf2d9db8523c8e6d6b0bc2955db292f9945/crates/cairo-lang-starknet/src/casm_contract_class_test.rs#L32)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

test_contract is old syntax?
</blockquote></details>

Somewhat. It uses directly external functions rather than impls. It's supported in the new syntax too of course, but we'll arrange everything in the tests later. This is now a transition phase.

**Review by ilyalesokhin-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3427)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3427)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/casm_contract_class_test.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3427#-NYCHu3g7Skv_I1RYAih:-NYCShDD-q91c4Jo5xSI:b32wtd) ([raw file](https://github.com/starkware-libs/cairo/blob/68cf9cf2d9db8523c8e6d6b0bc2955db292f9945/crates/cairo-lang-starknet/src/casm_contract_class_test.rs#L32)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Somewhat. It uses directly external functions rather than impls. It's supported in the new syntax too of course, but we'll arrange everything in the tests later. This is now a transition phase.
</blockquote></details>

ok

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3427)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/casm_contract_class_test.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3427#-NYCHu3g7Skv_I1RYAih:-NYCSkin49WW72KLfZQc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/68cf9cf2d9db8523c8e6d6b0bc2955db292f9945/crates/cairo-lang-starknet/src/casm_contract_class_test.rs#L32)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

ok
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3427)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
