### PR TITLE
Added destructors in cycle detectors.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5335)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/borrow_check/mod.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5335#-Nu2xAWWAyvAsgM4oZsk:-Nu2xAWWAyvAsgM4oZsl:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/bc30dc1edd4722b12e64478a2453dec0b5963b4a/crates/cairo-lang-lowering/src/borrow_check/mod.rs#L33)):*
> ```XML
>     success: Maybe<()>,
>     block_extra_calls: OrderedHashMap<BlockId, Vec<FunctionId>>,
>     destruct_fn: TraitFunctionId,
> ```





_Suggestion:_
```XML
destruct_trait
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5335)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @orizi)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/borrow_check/mod.rs` line 158 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5335#-Nu2yPZBENJhO3nNneaS:-Nu2yPZBENJhO3nNneaT:b-l2l033) ([raw file](https://github.com/starkware-libs/cairo/blob/cd6318478905d177b8d140852aa47a3501045fe5/crates/cairo-lang-lowering/src/borrow_check/mod.rs#L158)):*
> ```XML
>                             &[
>                                 (panic_demand, Some(DropPosition::Panic(stmt.location))),
>                                 (info.clone(), Some(DropPosition::Panic(stmt.location))),
> ```

what happend to this?



_Code quote:_
```XML
info.clone(), Some(DropPosition::Panic(stmt.location)
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5335)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/mod.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5335#-Nu2xAWWAyvAsgM4oZsk:-Nu2xq_u3zAeaOchoBGt:b44tvm9) ([raw file](https://github.com/starkware-libs/cairo/blob/bc30dc1edd4722b12e64478a2453dec0b5963b4a/crates/cairo-lang-lowering/src/borrow_check/mod.rs#L33)):*
> ```XML
>     success: Maybe<()>,
>     block_extra_calls: OrderedHashMap<BlockId, Vec<FunctionId>>,
>     destruct_fn: TraitFunctionId,
> ```

it is the fn id - not the trait.
___
*[`crates/cairo-lang-lowering/src/borrow_check/mod.rs` line 158 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5335#-Nu2yPZBENJhO3nNneaS:-Nu2zVjcAk2Wc9pFG87N:bfvp6mt) ([raw file](https://github.com/starkware-libs/cairo/blob/cd6318478905d177b8d140852aa47a3501045fe5/crates/cairo-lang-lowering/src/borrow_check/mod.rs#L158)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what happend to this?
</blockquote></details>

the location became larger - so i extract it to a variable.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 8 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5335#-:-Nu3B5vM5JxeVMXY0YyC:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
