### PR TITLE
Use snapshot for array_len.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2128)

### CODE REVIEW

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2128)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-formatter/src/node_properties.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2128#-NOIrgVBDH1Hc2qcSg1P:-NOIrgVBDH1Hc2qcSg1Q:b-io0utd) ([raw file](https://github.com/starkware-libs/cairo/blob/22283106b94b39c2e9081215976c8147c6c9ffe9/crates/cairo-lang-formatter/src/node_properties.rs#L59)):*
> ```XML
>             SyntaxKind::TokenDot
>             | SyntaxKind::TokenNot
>             | SyntaxKind::TokenAt
> ```

Can you reformat?
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 464 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2128#-NOIrtDj-VMECJM34SpA:-NOIrtDj-VMECJM34SpB:bsrfkwe) ([raw file](https://github.com/starkware-libs/cairo/blob/22283106b94b39c2e9081215976c8147c6c9ffe9/crates/cairo-lang-semantic/src/expr/inference.rs#L464)):*
> ```XML
> 
>         // If the function takes a snapshot of self_ty, fix the param type.
>         let fixed_param_ty = match self.db.lookup_intern_type(first_param.ty) {
> ```

Looks good

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2128#-:-NOIsepwCE9DxK0lDUTO:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2128)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 464 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2128#-NOIrtDj-VMECJM34SpA:-NOIubFQBYsGsVTzOrI6:b1m4y8p) ([raw file](https://github.com/starkware-libs/cairo/blob/22283106b94b39c2e9081215976c8147c6c9ffe9/crates/cairo-lang-semantic/src/expr/inference.rs#L464)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Looks good
</blockquote></details>

it does not work :(

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2128)* status: 7 of 27 files reviewed, all discussions resolved (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-formatter/src/node_properties.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2128#-NOIrgVBDH1Hc2qcSg1P:-NOJnOjoEYSEHFXwphj8:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/22283106b94b39c2e9081215976c8147c6c9ffe9/crates/cairo-lang-formatter/src/node_properties.rs#L59)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Can you reformat?
</blockquote></details>

done.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2128)* status: 7 of 27 files reviewed, all discussions resolved

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 464 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2128#-NOIrtDj-VMECJM34SpA:-NOK26QPAgAZn_RiNOM6:bpzi09u) ([raw file](https://github.com/starkware-libs/cairo/blob/22283106b94b39c2e9081215976c8147c6c9ffe9/crates/cairo-lang-semantic/src/expr/inference.rs#L464)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it does not work :(
</blockquote></details>

It will



_Code quote:_
```XML
infer_concrete_trait_by_self
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2128)* status: 12 of 27 files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
ptal

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2128#-:-NOKTyza4JVmqt1FqFVO:bb7mtv8)* status: 12 of 27 files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 15 of 20 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2128#-:-NOKVyY74w8YgaHeEKNg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 5 of 19 files at r1, 9 of 20 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2128)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
