### PR TITLE
Rename BlockUsages -> Usages.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
Remove tracking of usages for blocks as they are unused.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6108)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/test_data/usage` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6108#-O3Bd0CFErCs8iiJ66A-:-O3Bd0CFErCs8iiJ66A0:blgwzg8) ([raw file](https://github.com/starkware-libs/cairo/blob/7a907518d783dab2a0550abf3f0b1090a7ac346e/crates/cairo-lang-lowering/src/lower/test_data/usage#L84)):*
> ```
>   Changes: ParamId(test::a)::b::c, ParamId(test::b),
>   Snapshot_Usage:
>   Introductions: LocalVarId(test::h),
> ```

Note that this was changed, as it is introduced in the body of the loop and not in the loop it self.



_Code quote:_
```
 Introductions: LocalVarId(test::h),
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6108#-:-O3Bg4oF-O9Dt_eeQHu3:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/usage.rs` line 156 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6108#-O3BfUzq9-GIRGPtChII:-O3BfUzq9-GIRGPtChIJ:bb7phvt) ([raw file](https://github.com/starkware-libs/cairo/blob/13f21165b33e8449039b7e3fc74f3750fd0b62b6/crates/cairo-lang-lowering/src/lower/usage.rs#L156)):*
> ```XML
> #[debug_db(ExprFormatter<'a>)]
> pub struct Usages {
>     /// Mapping from an [ExprId] for expressions of interest to thier [Usage].
> ```

typo

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/usage.rs` line 156 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6108#-O3BfUzq9-GIRGPtChII:-O3BgAXV8l_QHxLUrUHL:b-3kig9r) ([raw file](https://github.com/starkware-libs/cairo/blob/13f21165b33e8449039b7e3fc74f3750fd0b62b6/crates/cairo-lang-lowering/src/lower/usage.rs#L156)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

typo
</blockquote></details>

Updated the comments.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6108)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6108#-O3BgG0K6Ex67WIWSPMD:-O3BgG0K6Ex67WIWSPME:b3qajo2) (no related file):*
doesn't this change remove the need of printing introductions?

___

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6108)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

**Comment by ilyalesokhin-starkware** [comment]
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doesn't this change remove the need of printing introductions?
</blockquote></details>

Done,
It was not always empty for closures, but we didn't use that information.

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6108)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
