### PR TITLE
Added tests for diagnostics in entry point wrapper creation.

### PR DESCRIPTION
**Pull request by yuvalsw**
Also added tests for diagnostics in entry point wrapper creation.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1709)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1709)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 292 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1709#-NLLYJ1bAOg5jqUvwgPV:-NLLYJ1bAOg5jqUvwgPW:b-3uu6zt) ([raw file](https://github.com/starkware-libs/cairo/blob/0e6831f09377ab503f811e13770ef3899be81565/crates/cairo-lang-starknet/src/plugin.rs#L292)):*
> ```XML
> 
>                         // TODO(yuval): keep track of whether the function is external/view.
>                         abi_functions.push(RewriteNode::Modified(ModifiedNode {
> ```

Not sure I understand the motivation for this change.

is it to reduce the number of errors the users gets?



_Code quote:_
```XML
 abi_functions.push(RewriteNode::Modified(ModifiedNode {
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1709)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 292 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1709#-NLLYJ1bAOg5jqUvwgPV:-NLLi5CSCYlykZP1i2iC:b-wt1tyh) ([raw file](https://github.com/starkware-libs/cairo/blob/0e6831f09377ab503f811e13770ef3899be81565/crates/cairo-lang-starknet/src/plugin.rs#L292)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Not sure I understand the motivation for this change.

is it to reduce the number of errors the users gets?
</blockquote></details>

No.
It doesn't make sense to add the function to the ABI if we didn't succeed to create the wrapper, does it?

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1709)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 292 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1709#-NLLYJ1bAOg5jqUvwgPV:-NLLoxwm5Ut6ED1LftJC:beltdni) ([raw file](https://github.com/starkware-libs/cairo/blob/0e6831f09377ab503f811e13770ef3899be81565/crates/cairo-lang-starknet/src/plugin.rs#L292)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

No.
It doesn't make sense to add the function to the ABI if we didn't succeed to create the wrapper, does it?
</blockquote></details>

I don't see why.

Functions shouldn't disappear from the semantic module just because they have an semantic problem.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1709)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 292 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1709#-NLLYJ1bAOg5jqUvwgPV:-NLQpNOl8BDSitcKpqqA:b2v9xec) ([raw file](https://github.com/starkware-libs/cairo/blob/0e6831f09377ab503f811e13770ef3899be81565/crates/cairo-lang-starknet/src/plugin.rs#L292)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't see why.

Functions shouldn't disappear from the semantic module just because they have an semantic problem.
</blockquote></details>

Removed, as discussed f2f.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
Can you edit the commit msg and the name of the PR?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1709#-:-NLQvDLODslc4YGNmkrp:bpr7i15)* status: 0 of 7 files reviewed, 1 unresolved discussion

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1709#-:-NLQx-SHC4hBTyR4EIza:bnfp4nl)* status: 0 of 7 files reviewed, all discussions resolved

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1709)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1709#-NLQxQjPEEjFo5nXQGmX:-NLQxQjPEEjFo5nXQGmY:b-ouoqi) (no related file):*
Change target branch

___

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1709)* status: all files reviewed, 1 unresolved discussion

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1709)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
