### PR TITLE
Fix is_fully_concrete().

### PR DESCRIPTION
**Pull request by liorgold2**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4669)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4669)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @liorgold2)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4669#-Nmfbpnm0OKBJWRb1hr8:-Nmfbpnm0OKBJWRb1hr9:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/433da449895ef054493ca2b4f4fa380cd1e1fd0c/crates/cairo-lang-semantic/src/items/imp.rs#L113)):*
> ```XML
>         ))
>     }
>     /// Returns true if all the inner type are concrete.
> ```





_Suggestion:_
```XML
    /// Returns true if the type does not depend on any generics.
```
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4669#-NmfbagYEgNPXTxQJ0lU:-NmfbagYEgNPXTxQJ0lV:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/433da449895ef054493ca2b4f4fa380cd1e1fd0c/crates/cairo-lang-semantic/src/items/imp.rs#L159)):*
> ```XML
>         db.impl_concrete_trait(*self)
>     }
>     /// Returns true if all the inner type are concrete.
> ```





_Suggestion:_
```XML
    /// Returns true if the impl does not depend on any generics.
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4669)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4669#-Nmfbpnm0OKBJWRb1hr8:-Nmg2y1gC9d2Psuc5_Gv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/433da449895ef054493ca2b4f4fa380cd1e1fd0c/crates/cairo-lang-semantic/src/items/imp.rs#L113)):*
> ```XML
>         ))
>     }
>     /// Returns true if all the inner type are concrete.
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4669#-NmfbagYEgNPXTxQJ0lU:-Nmg36SXEWuScMRbc7ry:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/433da449895ef054493ca2b4f4fa380cd1e1fd0c/crates/cairo-lang-semantic/src/items/imp.rs#L159)):*
> ```XML
>         db.impl_concrete_trait(*self)
>     }
>     /// Returns true if all the inner type are concrete.
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4669)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @liorgold2)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 224 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4669#-Nmh3lDY65zHQNcK72KU:-Nmh3lDZ-s7RRQPGj9mf:b6nnmlt) ([raw file](https://github.com/starkware-libs/cairo/blob/80795de054c995436f49d39ffbce8772cdc4e3a2/crates/cairo-lang-semantic/src/types.rs#L224)):*
> ```XML
>             }
>         };
>         generic_args.iter().all(|generic_argument_id| generic_argument_id.is_fully_concrete(db))
> ```

self.generic_args().iter().all(..

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4669)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4669)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 224 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4669#-Nmh3lDY65zHQNcK72KU:-NmjX5o06o1Gd09Sar8S:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/80795de054c995436f49d39ffbce8772cdc4e3a2/crates/cairo-lang-semantic/src/types.rs#L224)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

self.generic_args().iter().all(..
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4669#-:-Nmk-aviB4gTp7XA4WZZ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
