### PR TITLE
Enforced event attribute for contract events.

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3340)

### CODE REVIEW

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 16 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3340)* status: 16 of 20 files reviewed, 1 unresolved discussion (waiting on @orizi, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/storage.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3340#-NXQe7pm-Wg5I4HhIzgV:-NXQe7pm-Wg5I4HhIzgW:b-e8czia) ([raw file](https://github.com/starkware-libs/cairo/blob/2b3efcdc8357b0de3b548cd5a0a54a9055e9a5e7/crates/cairo-lang-starknet/src/plugin/storage.rs#L89)):*
> ```XML
>     }
>     let empty_event_code =
>         if has_event { "" } else { "#[event] #[derive(Drop, starknet::Event)] enum Event {}\n" };
> ```

Add a new line after the first attribute.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3340)* status: 16 of 20 files reviewed, 2 unresolved discussions (waiting on @orizi, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-starknet/test_data/erc20.sierra` line 3784 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3340#-NXQfWWK5blB2dc_AEQY:-NXQfWWL7H5FwFIaZVZh:b-bqlrxt) ([raw file](https://github.com/starkware-libs/cairo/blob/2b3efcdc8357b0de3b548cd5a0a54a9055e9a5e7/crates/cairo-lang-starknet/test_data/erc20.sierra#L3784)):*
> ```
> u128_eq([36], [37]) { fallthrough() 3308() };
> branch_align() -> ();
> drop<u128>([35]) -> ();
> ```

I don't understand why the sierra code changed, do you?

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3340)* status: 16 of 20 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/plugin/storage.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3340#-NXQe7pm-Wg5I4HhIzgV:-NXQgJob90wja2GX9e7L:b2e3cf7) ([raw file](https://github.com/starkware-libs/cairo/blob/2b3efcdc8357b0de3b548cd5a0a54a9055e9a5e7/crates/cairo-lang-starknet/src/plugin/storage.rs#L89)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Add a new line after the first attribute.
</blockquote></details>

It's the generated code and the rest doesn't have line breaks.

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 4 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3340)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi and @spapinistarkware)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3340#-:-NXQqzQ3-BgWIoUYfz77:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi and @spapinistarkware)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3340)* status: 15 of 20 files reviewed, all discussions resolved (waiting on @gilbens-starkware, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/test_data/erc20.sierra` line 3784 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3340#-NXQfWWK5blB2dc_AEQY:-NXQqKdMAegOLW1RnlOh:bncvegj) ([raw file](https://github.com/starkware-libs/cairo/blob/2b3efcdc8357b0de3b548cd5a0a54a9055e9a5e7/crates/cairo-lang-starknet/test_data/erc20.sierra#L3784)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

I don't understand why the sierra code changed, do you?
</blockquote></details>

Rebased.

**Pull request merged**
