### PR TITLE
Avoid adding labels when we have a fallthrough with no gotos.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2106)

### CODE REVIEW

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2106)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/expr_generator_context.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2106#-NO51eYC-i1RTnDmiL4E:-NO51eYC-i1RTnDmiL4F:b9gj3cf) ([raw file](https://github.com/starkware-libs/cairo/blob/0e458706a89b95f6dfd26369fe9ae92629dfe943/crates/cairo-lang-sierra-generator/src/expr_generator_context.rs#L106)):*
> ```XML
>     }
> 
>     pub fn block_has_label(&mut self, block_id: &BlockId) -> bool {
> ```

Document.
Remove `mut` from `&mut self`?

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2106#-:-NO522nT5O6g0Gzb4ueB:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2106)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-generator/src/expr_generator_context.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2106#-NO51eYC-i1RTnDmiL4E:-NO53Qq-7XSJN5akdP_8:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/0e458706a89b95f6dfd26369fe9ae92629dfe943/crates/cairo-lang-sierra-generator/src/expr_generator_context.rs#L106)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Document.
Remove `mut` from `&mut self`?
</blockquote></details>

done.

**Review by liorgold2 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2106)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2106#-:-NO53pGg4gio0I7jepzi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2106)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
