### PR TITLE
Changed .unwrap_or_else(|| panic...) to .expect(...)

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1121)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1121)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1121#-NI2LNNL5vagXgYxB8ss:-NI2LNNM0iHZZj9v6HyC:bjxa3p8) (no related file):*
i'm against this - feel free to add more reviewers for discussion.

___

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1121)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1121#-NI2LNNL5vagXgYxB8ss:-NI6v5FE6nOu4u81XFMD:b-rjp4r) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i'm against this - feel free to add more reviewers for discussion.
</blockquote></details>

@orizi, why?

___

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1121)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1121#-NI2LNNL5vagXgYxB8ss:-NI78FXZ6gJUy-84OIvb:b-86vdgv) (no related file):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

@orizi, why?
</blockquote></details>

unwrapping and error checking are nice as a suffix of an expression - wrapping the entire expression is much less nice IMO.

___

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1121#-:-NI8QvS32Wl7I6JZDkEN:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1121#-NI2LNNL5vagXgYxB8ss:-NI8Q-or5NJjpY6Km40H:b-jjlge8) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

unwrapping and error checking are nice as a suffix of an expression - wrapping the entire expression is much less nice IMO.
</blockquote></details>

For me both orders are fine.

___

**Review by liorgold2 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1121)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1121)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1121#-NI2LNNL5vagXgYxB8ss:-NI8a_wM4CdoD2PR-lAl:b-ut02zl) (no related file):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

For me both orders are fine.
</blockquote></details>

@spapinistarkware, Ori asked for your opinion too.

___

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1121)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1121#-NI2LNNL5vagXgYxB8ss:-NIC6rGxEW0xG9L0SGP-:bjrrki4) (no related file):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

@spapinistarkware, Ori asked for your opinion too.
</blockquote></details>

I'm inclined to not add too many internal utils. It makes it harder for outsiders to read and contribute. I prefer to stay rust idiomatic, and it seems unwrap_or_else(|| panic!()) is the idiomatic way.

___

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1121)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware and @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1121#-NI2LNNL5vagXgYxB8ss:-NIDbRA26ehmik_og0dq:bwwo0w1) (no related file):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I'm inclined to not add too many internal utils. It makes it harder for outsiders to read and contribute. I prefer to stay rust idiomatic, and it seems unwrap_or_else(|| panic!()) is the idiomatic way.
</blockquote></details>

this seems also like it would blow up the moment you want to stream a couple of these together in the same expression.

___

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1121)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1121#-NI2LNNL5vagXgYxB8ss:-NIRAOoz2J4exoB480ZZ:b9idw55) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this seems also like it would blow up the moment you want to stream a couple of these together in the same expression.
</blockquote></details>

I am still good with it, but will archive this PR per the partial objection.

___

**Pull request closed without merging**
