### PR TITLE
Stable Stream Token interface

### PR DESCRIPTION
**Pull request by wawel37**
This PR implements a `StableStreamToken` representation of StreamToken.

We need this to be as stable as possible, as we would use this to convert `SyntaxNodes` to concrete TokenStream types. As the macro API for user depends on a certain version of the parser and SyntaxNodes, we need to have a middleware type to be later converted to concrete types needed by macro API.

### CODE REVIEW

**Review by Draggu — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6707)* status: all files reviewed, 3 unresolved discussions (waiting on @wawel37)

___
*[`crates/cairo-lang-stable-token/src/lib.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6707#-OC89eQaBbACFxpCT3TA:-OC89eQaBbACFxpCT3TB:b-ap3mzl) ([raw file](https://github.com/starkware-libs/cairo/blob/9bae546130eb833bc376fb17b1c56f83ed28923a/crates/cairo-lang-stable-token/src/lib.rs#L9)):*
> ```XML
> }
> 
> pub struct StableToken(pub String, pub Option<StableSpan>);
> ```

Please name these props.
___
*[`crates/cairo-lang-stable-token/src/lib.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6707#-OC89lmQ4HD7a3ufzFwH:-OC89lmQ4HD7a3ufzFwI:bibv47o) ([raw file](https://github.com/starkware-libs/cairo/blob/9bae546130eb833bc376fb17b1c56f83ed28923a/crates/cairo-lang-stable-token/src/lib.rs#L19)):*
> ```XML
> pub trait ToStableTokenStream {
>     fn to_stable_token_stream(&self) -> impl Iterator<Item = StableToken>;
> }
> ```

Move it to associated type.



_Suggestion:_
```XML
pub trait ToStableTokenStream {
    type Iter: Iterator<Item = StableToken>;

    fn to_stable_token_stream(&self) -> Self::Iter;
}
```
___
*[`crates/cairo-lang-syntax/src/node/with_db.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6707#-OC8AGqK2muu1-Xc7AjO:-OC8AGqK2muu1-Xc7AjP:b-5g6hr8) ([raw file](https://github.com/starkware-libs/cairo/blob/9bae546130eb833bc376fb17b1c56f83ed28923a/crates/cairo-lang-syntax/src/node/with_db.rs#L19)):*
> ```XML
> impl<'a, Db: SyntaxGroup> ToStableTokenStream for SyntaxNodeWithDb<'a, Db> {
>     fn to_stable_token_stream(&self) -> impl Iterator<Item = StableToken> {
>         self.node.tokens(self.db).map(|token| {
> ```

Create own iterator type. This will make it more stable.

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6707)* status: all files reviewed, 6 unresolved discussions (waiting on @Draggu, @orizi, and @wawel37)

___
*[`crates/cairo-lang-stable-token/src/lib.rs` line 4 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6707#-OCIqJN8AIxjxnLi0sPf:-OCIqJN8AIxjxnLi0sPg:b-fj7jnn) ([raw file](https://github.com/starkware-libs/cairo/blob/ac100319708b138cecc78af54b678f4335646d75/crates/cairo-lang-stable-token/src/lib.rs#L4)):*
> ```XML
> //! We want this to be as stable as possible and limit the changes here to bare minimum.
> 
> pub struct StableSpan {
> ```

consider documenting everything here. I would even slap `#![deny(missing_docs)]` at the top of this file
___
*[`crates/cairo-lang-stable-token/src/lib.rs` line 10 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6707#-OCIqROvEwvcHA4Yvd_E:-OCIqROvEwvcHA4Yvd_F:b8xlpay) ([raw file](https://github.com/starkware-libs/cairo/blob/ac100319708b138cecc78af54b678f4335646d75/crates/cairo-lang-stable-token/src/lib.rs#L10)):*
> ```XML
> 
> pub struct StableToken {
>     pub content: String,
> ```

have you considered using `&str`?
___
*[`crates/cairo-lang-stable-token/Cargo.toml` line 4 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6707#-OCIp_tP3OGehcTmpWsF:-OCIp_tP3OGehcTmpWsG:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ac100319708b138cecc78af54b678f4335646d75/crates/cairo-lang-stable-token/Cargo.toml#L4)):*
> ```TOML
> name = "cairo-lang-stable-token"
> version = "1.0.0"
> edition = "2021"
> ```





_Suggestion:_
```TOML
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "<fill this>"
```

**Review by wawel37 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6707)* status: all files reviewed, 6 unresolved discussions (waiting on @Draggu, @mkaput, and @orizi)

___
*[`crates/cairo-lang-stable-token/src/lib.rs` line 4 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6707#-OCIqJN8AIxjxnLi0sPf:-OCItLLh035p-eTVYmmS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ac100319708b138cecc78af54b678f4335646d75/crates/cairo-lang-stable-token/src/lib.rs#L4)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

consider documenting everything here. I would even slap `#![deny(missing_docs)]` at the top of this file
</blockquote></details>

Done.
___
*[`crates/cairo-lang-stable-token/src/lib.rs` line 10 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6707#-OCIqROvEwvcHA4Yvd_E:-OCIuwZ06Dav15-iS3Iz:bo9kfer) ([raw file](https://github.com/starkware-libs/cairo/blob/ac100319708b138cecc78af54b678f4335646d75/crates/cairo-lang-stable-token/src/lib.rs#L10)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

have you considered using `&str`?
</blockquote></details>

Yes, but we are using the SyntaxNode's `get_text` method, which returns `String` directly, so the stable token can store the owned String, and it wont be copied either way.
___
*[`crates/cairo-lang-stable-token/Cargo.toml` line 4 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6707#-OCIp_tP3OGehcTmpWsF:-OCIsReR2S1U44qXw5kq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ac100319708b138cecc78af54b678f4335646d75/crates/cairo-lang-stable-token/Cargo.toml#L4)):*
> ```TOML
> name = "cairo-lang-stable-token"
> version = "1.0.0"
> edition = "2021"
> ```

Done.

**Review by Draggu — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6707#-:-OCIvWYe8L6Fe2W62_Jo:bnfp4nl)* status: 6 of 8 files reviewed, 4 unresolved discussions (waiting on @mkaput, @orizi, and @wawel37)

___
*[`crates/cairo-lang-syntax/src/node/mod.rs` line 311 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6707#-OCIvL-f4n1uvWZ8rZmp:-OCIvL-f4n1uvWZ8rZmq:bqtj9d4) ([raw file](https://github.com/starkware-libs/cairo/blob/59af33cdddb5725d0aaff2c6fc0a6ca226db1f5b/crates/cairo-lang-syntax/src/node/mod.rs#L311)):*
> ```XML
>     /// Gets all the leaves of the SyntaxTree, where the self node is the root of a tree.
>     pub fn tokens<'a>(&'a self, db: &'a dyn SyntaxGroup) -> impl Iterator<Item = Self> + 'a {
>         self.preorder(db).filter_map(move |event| match event {
> ```

Why do we need this `move` now?

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6707#-:-OCJ08_00PwlOJMv2w0U:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6707)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @wawel37)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6707#-OCJ0FrY-t-tj6Ghqp8o:-OCJ0FrY-t-tj6Ghqp8p:bf5sa3p) (no related file):*
add this crate here: https://github.com/starkware-libs/cairo/blob/0721127e91d0f172a25cb891fe83dd6d802cd075/scripts/release_crates.sh#L8-L52

**Review by wawel37 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6707)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput and @orizi)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6707#-OCJ0FrY-t-tj6Ghqp8o:-OCJ5oNpE_Vh1wI7CWLc:b-896fix) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

add this crate here: https://github.com/starkware-libs/cairo/blob/0721127e91d0f172a25cb891fe83dd6d802cd075/scripts/release_crates.sh#L8-L52
</blockquote></details>

Done.

**Review by mkaput — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6707)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6707)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wawel37)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6707#-OCJ0FrY-t-tj6Ghqp8o:-OCT7yYHASV62B7H63sQ:bbc7ha3) (no related file):*
<details><summary><i>Previously, wawel37 (Mateusz Kowalski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I need further convincing for any such thing added not in the language server crate.

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6707)* status: all files reviewed, 1 unresolved discussion (waiting on @wawel37)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6707#-OCJ0FrY-t-tj6Ghqp8o:-OCXWkrp2LUr3LRPrKET:bdoqnqs) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I need further convincing for any such thing added not in the language server crate.
</blockquote></details>

LS has nothing to do here, this is procmacros <> cairo lang parser interop thing

**Comment by maciektr** [comment]
*[`crates/cairo-lang-syntax/Cargo.toml` line 13 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6707#-OCT882L-XWD1TOYFrjI:-OCXWc--D8ymatTxwl_6:b91cbfx) ([raw file](https://github.com/starkware-libs/cairo/blob/d15a4df3737b78e707fd9c4d15ccec6be1e63f65/crates/cairo-lang-syntax/Cargo.toml#L13)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this being through a completely different version scheme is highly suspicious.
</blockquote></details>

That's the point we are making. 
Ideally, we don't want to ever release any other version of this crate. 
It's meant to define a structure that never changes and can be used by both the cairo-lang-* crates and Scarb procedural macro API without neither of them being tied by version requirements - that is, any version of Scarb procedural macro API can use any version of cairo-lang-* crates, if they only interchange data through these structs, as they never change.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6707)* status: all files reviewed, 2 unresolved discussions (waiting on @wawel37)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6707#-OCdVuK7C6hkcZc8RavI:-OCdVuK7C6hkcZc8RavJ:bq6srcf) (no related file):*
the meaning of the word "stable" all around is different from everywhere else for the project.

we should have some other name.
___
*[`scripts/release_crates.sh` line 27 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6707#-OCdVYVV3T4g-aN0iPz-:-OCdVYVV3T4g-aN0iPz0:biigyjy) ([raw file](https://github.com/starkware-libs/cairo/blob/d15a4df3737b78e707fd9c4d15ccec6be1e63f65/scripts/release_crates.sh#L27)):*
> ```Shell
>     cairo-lang-sierra
>     cairo-lang-sierra-type-size
>     cairo-lang-stable-token
> ```

with the new versioning - i believe this might actually just break our release.



_Code quote:_
```Shell
    cairo-lang-stable-token
```

**Review by wawel37 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6707)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6707#-OCdVuK7C6hkcZc8RavI:-OCgxxrk0_g-a3aUCDMt:bdf9uyx) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the meaning of the word "stable" all around is different from everywhere else for the project.

we should have some other name.
</blockquote></details>

I was thinking about primitive, fixed and maybe DTO (but it might be wrong as this isn't directly a DTO). What do you think?
___
*[`scripts/release_crates.sh` line 27 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6707#-OCdVYVV3T4g-aN0iPz-:-OCgxe81-4u9AeIK4wJ5:bw2izhg) ([raw file](https://github.com/starkware-libs/cairo/blob/d15a4df3737b78e707fd9c4d15ccec6be1e63f65/scripts/release_crates.sh#L27)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

with the new versioning - i believe this might actually just break our release.
</blockquote></details>

I'm sorry but I don't understand but how is it going to affect the release?

**Review by wawel37 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6707)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`scripts/release_crates.sh` line 27 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6707#-OCdVYVV3T4g-aN0iPz-:-OChUxkSCd4ZrRHA8ehW:bzny3) ([raw file](https://github.com/starkware-libs/cairo/blob/d15a4df3737b78e707fd9c4d15ccec6be1e63f65/scripts/release_crates.sh#L27)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this attempt to release all the crates - the moment it is already released this would not not allow to release again.
(so it would break our 2nd release after this)
</blockquote></details>

Oh, so we should release this single crate manually, right? We need to also change the `release_crates.sh`'s assertion, so it ignores this crate. What do you think?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6707)* status: all files reviewed, 2 unresolved discussions (waiting on @wawel37)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6707#-OCdVuK7C6hkcZc8RavI:-OChk2g6AJhOiHvdVL3J:b1fgtxs) (no related file):*
<details><summary><i>Previously, wawel37 (Mateusz Kowalski) wrote…</i></summary><blockquote>

I was thinking about primitive, fixed and maybe DTO (but it might be wrong as this isn't directly a DTO). What do you think?
</blockquote></details>

didn't see any rename.
___
*[`scripts/release_crates.sh` line 27 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6707#-OCdVYVV3T4g-aN0iPz-:-OChk6J0CYQZ3KXIX98K:b-x5m23e) ([raw file](https://github.com/starkware-libs/cairo/blob/d15a4df3737b78e707fd9c4d15ccec6be1e63f65/scripts/release_crates.sh#L27)):*
<details><summary><i>Previously, wawel37 (Mateusz Kowalski) wrote…</i></summary><blockquote>

Oh, so we should release this single crate manually, right? We need to also change the `release_crates.sh`'s assertion, so it ignores this crate. What do you think?
</blockquote></details>

probably.

**Review by wawel37 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6707)* status: 1 of 9 files reviewed, 2 unresolved discussions (waiting on @Draggu, @mkaput, and @orizi)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6707#-OCdVuK7C6hkcZc8RavI:-OCiPeSg-9HC0n-tgZ_N:b-je58ih) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

didn't see any rename.
</blockquote></details>

Done. Change the name to "primitive"
___
*[`scripts/release_crates.sh` line 27 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6707#-OCdVYVV3T4g-aN0iPz-:-OCiPUQz3I3mVjaUWVu5:b1k25q7) ([raw file](https://github.com/starkware-libs/cairo/blob/d15a4df3737b78e707fd9c4d15ccec6be1e63f65/scripts/release_crates.sh#L27)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

probably.
</blockquote></details>

Done. Will remove it from the release list then.

**Review by mkaput — APPROVED** [review]
> Reviewed 8 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6707)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

**Review by mkaput — APPROVED** [review]
> Reviewed 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6707)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6707#-:-OCmxMGW67CRNYNHJa4T:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @wawel37)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6707)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wawel37)

**Review by mkaput — APPROVED** [review]
> Reviewed 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6707)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wawel37)

**Pull request merged**
