### PR TITLE
Make the formatter sort imports by default.

### PR DESCRIPTION
**Pull request by gilbens-starkware**

### CODE REVIEW

**Review by orizi — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6855)* status: all files reviewed, 1 unresolved discussion (waiting on @dean-starkware and @mkaput)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6855#-ODjrl4A3WAXgm5xpvz_:-ODjvOK314BxN6nAd3wS:bf0clok) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

This is kind of a breaking change, isn't it? Upgrading Cairo will make CIs fail suddenly. In Rust this would mandate edition change.
</blockquote></details>

i think this is ok in this case - as the update itself is still version by version, and part of the "update PR" will be the fixed formatting.

otherwise any formatting update is considered a breaking change.

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6855)* status: all files reviewed, 1 unresolved discussion (waiting on @dean-starkware and @orizi)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6855#-ODjrl4A3WAXgm5xpvz_:-ODk-EM2BfM3C9xPefpJ:bleqxk9) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i think this is ok in this case - as the update itself is still version by version, and part of the "update PR" will be the fixed formatting.

otherwise any formatting update is considered a breaking change.
</blockquote></details>

on the other hand: if you make this on-by-default then why give users an option to disable it after all?

**Review by mkaput — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6855)* status: all files reviewed, 1 unresolved discussion (waiting on @dean-starkware and @orizi)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6855)* status: all files reviewed, 1 unresolved discussion (waiting on @dean-starkware and @mkaput)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6855#-ODjrl4A3WAXgm5xpvz_:-ODk0qDN2xEGNnY2Xgpz:bqflwwj) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

on the other hand: if you make this on-by-default then why give users an option to disable it after all?
</blockquote></details>

for backwards compatibility in more specific cases.

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6855)* status: all files reviewed, 1 unresolved discussion (waiting on @dean-starkware and @orizi)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6855#-ODjrl4A3WAXgm5xpvz_:-ODk6je8DQTvHiI3G0Et:bvvlh35) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

for backwards compatibility in more specific cases.
</blockquote></details>

unblocking, I don't have a strong opinion on this

**Review by dean-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6855#-:-ODkFRkS1TITQBZpABS8:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6855)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6855#-ODlNZeW4SczPbMGMQbf:-ODlNZeW4SczPbMGMQbg:b-pgk41m) (no related file):*
make the fmt binary affect this in a previous PR first.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6855)* status: 11 of 121 files reviewed, 1 unresolved discussion (waiting on @mkaput and @orizi)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6855#-ODlNZeW4SczPbMGMQbf:-OE9sKXg4WcUNF5qTr0i:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

make the fmt binary affect this in a previous PR first.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6855)* status: 11 of 128 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @mkaput)

___
*[`corelib/src/array.cairo` line 66 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6855#-OEIXneu2lNJwXkkeTzD:-OEIXneu2lNJwXkkeTzE:b-teois4) ([raw file](https://github.com/starkware-libs/cairo/blob/e6524893ae234dae3be8faac0bed06fa7bc4e3cd/corelib/src/array.cairo#L66)):*
> ```Cairo
> #[feature("deprecated-index-traits")]
> use crate::traits::IndexView;
> use crate::{RangeCheck, box::BoxTrait, iter::Iterator, metaprogramming::TypeEqual, serde::Serde};
> ```

should probably additionally improve this before.



_Code quote:_
```Cairo
use crate::{RangeCheck, box::BoxTrait, iter::Iterator, metaprogramming::TypeEqual, serde::Serde};
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6855)* status: 11 of 128 files reviewed, 2 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`corelib/src/array.cairo` line 66 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6855#-OEIXneu2lNJwXkkeTzD:-OEOAApJCqa44CbJ4WFN:b-ge5opg) ([raw file](https://github.com/starkware-libs/cairo/blob/e6524893ae234dae3be8faac0bed06fa7bc4e3cd/corelib/src/array.cairo#L66)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

should probably additionally improve this before.
</blockquote></details>

You mean special handling of `crate`?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6855)* status: 11 of 128 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @mkaput)

___
*[`corelib/src/array.cairo` line 66 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6855#-OEIXneu2lNJwXkkeTzD:-OEOLZ5pADXSiHqNQnRD:bepepwe) ([raw file](https://github.com/starkware-libs/cairo/blob/e6524893ae234dae3be8faac0bed06fa7bc4e3cd/corelib/src/array.cairo#L66)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

You mean special handling of `crate`?
</blockquote></details>

yes.

probably `super` as well.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r5, 8 of 55 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6855)* status: 12 of 129 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @mkaput)

___
*[`corelib/src/bytes_31.cairo` line 37 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6855#-OEiKgKKAkNJZg32vMZT:-OEiKgKL5l9kv7W-KRHd:b-l6hdjr) ([raw file](https://github.com/starkware-libs/cairo/blob/ad21034c455f871c26342c9c55479b5600ae4f3e/corelib/src/bytes_31.cairo#L37)):*
> ```Cairo
> extern fn bytes31_to_felt252(value: bytes31) -> felt252 nopanic;
> 
> /// A trait for accessing a specific byte of ampl CollectionsBreakingBeha `bytes31` type.
> ```

revert

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 17 of 110 files at r3, 15 of 55 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6855)* status: 44 of 129 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @mkaput)

___
*[`corelib/src/starknet.cairo` line 74 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6855#-OEiLEC0EzQ_Xhk8GETw:-OEiLEC0EzQ_Xhk8GETx:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ad21034c455f871c26342c9c55479b5600ae4f3e/corelib/src/starknet.cairo#L74)):*
> ```Cairo
> pub use info::v2::{
>     ExecutionInfo as ExecutionInfo, ResourceBounds as ResourcesBounds, TxInfo as TxInfo,
> };
> ```





_Suggestion:_
```Cairo
pub use info::v2::{
    ExecutionInfo, ResourceBounds, TxInfo,
};
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6855)* status: 43 of 129 files reviewed, 2 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`corelib/src/bytes_31.cairo` line 37 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6855#-OEiKgKKAkNJZg32vMZT:-OEmcZnT4o_hOuuUq7dw:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ad21034c455f871c26342c9c55479b5600ae4f3e/corelib/src/bytes_31.cairo#L37)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

revert
</blockquote></details>

Done.
___
*[`corelib/src/starknet.cairo` line 74 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6855#-OEiLEC0EzQ_Xhk8GETw:-OEmeSsv1IWEAiF9YXXe:bsqiyln) ([raw file](https://github.com/starkware-libs/cairo/blob/ad21034c455f871c26342c9c55479b5600ae4f3e/corelib/src/starknet.cairo#L74)):*
> ```Cairo
> pub use info::v2::{
>     ExecutionInfo as ExecutionInfo, ResourceBounds as ResourcesBounds, TxInfo as TxInfo,
> };
> ```

Done.
Notice that for `ResourceBounds` it's singular and plural, so I kept it as is.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6855)* status: 41 of 132 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @mkaput)

___
*[`corelib/src/array.cairo` line 148 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6855#-OEmfrvp30o7qRtugF-j:-OEmfrvp30o7qRtugF-k:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/9c90a0d2726ef9b195ec460179ab1c21a2e5053a/corelib/src/array.cairo#L148)):*
> ```Cairo
>     /// ```
>     fn append_span<+Clone<T>, +Drop<T>>(ref self: Array<T>, mut span: Span<T>) {
>         // let x = Some(5);
> ```

.



_Code quote:_
```Cairo
use crate::traits::IndexView;
use Option::{None, Some};
/// A collection of elements of the same type continuous in memory.
#[derive(Drop)]
pub extern type Array<T>;
    /// assert!(arr == array![1, 2, 3]);
    /// ```
    fn append_span<+Clone<T>, +Drop<T>>(ref self: Array<T>, mut span: Span<T>) {
        // let x = Some(5);
```

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 110 files at r3, 1 of 55 files at r6, 1 of 1 files at r7, 1 of 5 files at r8, 1 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6855)* status: 47 of 132 files reviewed, all discussions resolved (waiting on @mkaput)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6855)* status: 47 of 132 files reviewed, all discussions resolved (waiting on @mkaput and @orizi)

___
*[`corelib/src/array.cairo` line 148 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6855#-OEmfrvp30o7qRtugF-j:-OEmhAjA0UoyRcAq95Rv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9c90a0d2726ef9b195ec460179ab1c21a2e5053a/corelib/src/array.cairo#L148)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 28 of 110 files at r3, 1 of 1 files at r4, 9 of 55 files at r6, 1 of 4 files at r9, 80 of 80 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6855#-:-OEp9ntG3yw9pMejnIiz:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
