### PR TITLE
Fix generics

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3879)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3879** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3879" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/3879?utm_source=stack-comment).

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3879)* status: 4 of 22 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3879#-NbUEoIKDN8r8J0YUzks:-NbUEoIKDN8r8J0YUzkt:bnnvjrt) ([raw file](https://github.com/starkware-libs/cairo/blob/49ef0b74b76c37cb795e27f5c613ffcdc1eebdfd/crates/cairo-lang-semantic/src/expr/inference.rs#L62)):*
> ```XML
> #[derive(Copy, Clone, Debug, PartialEq, Eq, Hash, DebugWithDb, SemanticObject)]
> #[debug_db(dyn SemanticGroup + 'static)]
> pub enum InferenceId {
> ```

please doc what do you mean by the id here.
(i am yet to understand at this point)



_Code quote:_
```XML
InferenceId
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 16 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3879)* status: 20 of 22 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 518 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3879#-NbUF8Xq4j75EUZXa63d:-NbUF8Xq4j75EUZXa63e:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/49ef0b74b76c37cb795e27f5c613ffcdc1eebdfd/crates/cairo-lang-semantic/src/expr/inference.rs#L518)):*
> ```XML
>     }
> 
>     fn assign_impl(&mut self, var_id: ImplVarId, impl_id: ImplId) -> InferenceResult<ImplId> {
> ```

doc
___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 308 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3879#-NbUFcfV5_7l9r_0pMmz:-NbUFcfV5_7l9r_0pMn-:b-t0lo7g) ([raw file](https://github.com/starkware-libs/cairo/blob/49ef0b74b76c37cb795e27f5c613ffcdc1eebdfd/crates/cairo-lang-semantic/src/items/generics.rs#L308)):*
> ```XML
>     let mut diagnostics = SemanticDiagnostics::new(module_file_id.file_id(db.upcast())?);
>     let inference_id = InferenceId::GenericImplParamTrait(generic_param_id);
>     // TODO: We should not create a new resolver -  we are missing the other generic params
> ```

assign

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3879)* status: all files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3879)* status: 20 of 22 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3879#-NbUEoIKDN8r8J0YUzks:-NbUkXok7T5DOM20vysh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/49ef0b74b76c37cb795e27f5c613ffcdc1eebdfd/crates/cairo-lang-semantic/src/expr/inference.rs#L62)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

please doc what do you mean by the id here.
(i am yet to understand at this point)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 518 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3879#-NbUF8Xq4j75EUZXa63d:-NbUkymv2dyc3LzBBKnh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/49ef0b74b76c37cb795e27f5c613ffcdc1eebdfd/crates/cairo-lang-semantic/src/expr/inference.rs#L518)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 308 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3879#-NbUFcfV5_7l9r_0pMmz:-NbUlEgE9bqURczXeX9N:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/49ef0b74b76c37cb795e27f5c613ffcdc1eebdfd/crates/cairo-lang-semantic/src/items/generics.rs#L308)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

assign
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3879#-:-NbUmNA22Yk0u_QEz3YE:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3879#-NbUmIII7WbGz85XbV9q:-NbUmIII7WbGz85XbV9r:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e0ba55d51eb4a90c1632fe868f49b4958bc016cb/crates/cairo-lang-semantic/src/expr/inference.rs#L60)):*
> ```XML
> }
> 
> /// An id for an inference context. Each inference variablwe is associated with an inference id.
> ```





_Suggestion:_
```XML
/// An id for an inference context. Each inference variable is associated with an inference id.
```

**Pull request merged**
