### PR TITLE
Changed flag add_withdraw_gas default from false to true.

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2807)

### CODE REVIEW

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 5 of 32 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2807)* status: 5 of 32 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-filesystem/src/flag.rs` line 4 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2807#-NSvOqdf-XRr6Ry9ZAWX:-NSvOqdf-XRr6Ry9ZAWY:b-pqc8a) ([raw file](https://github.com/starkware-libs/cairo/blob/a647d9863bb9c98a68760a8bc6553da88adf5de8/crates/cairo-lang-filesystem/src/flag.rs#L4)):*
> ```XML
> #[derive(PartialEq, Eq, Debug)]
> pub enum Flag {
>     AddWithdrawGas(bool),
> ```

Why is this changed? It doesn't affect the default. Seems more natural to me to keep the positive sense

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 32 files at r1, 4 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2807)* status: 11 of 32 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2807#-NTCA0IH73yxx_5ZjIH0:-NTCA0IH73yxx_5ZjIH1:b-ebzm1k) (no related file):*
All the sierra generator examples which use revoke_ap() are now needlessly complicated. Can you compile them without the flag / find a non-recursive solution for revoke_ap?

___

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 32 files at r1, 5 of 13 files at r2, 23 of 23 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2807#-:-NTJF0mw8ATpXkNqNDQD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 6 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2807)* status: 36 of 38 files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 2 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2807)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
