### PR TITLE
cairo-ls: Set crate roots from Scarb metadata

### PR DESCRIPTION
**Pull request by maciektr**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2303)

### CODE REVIEW

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2303)* status: all files reviewed, 9 unresolved discussions (waiting on @maciektr and @spapinistarkware)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 737 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2303#-NPLzsHQDcobriSEMB2t:-NPLzsHQDcobriSEMB2u:b-kqtjnm) ([raw file](https://github.com/starkware-libs/cairo/blob/dea2ad5e77bb19d86bb847c99cfe418637052d34/crates/cairo-lang-language-server/src/lib.rs#L737)):*
> ```XML
> 
> #[derive(Serialize, Deserialize, Debug)]
> pub struct ProjectMetadata {
> ```

let's be specific, use word `scarb` in all relevant items



_Suggestion:_
```XML
ScarbProjectMetadata
```
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 744 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2303#-NPM-1hV7_2b6cb5cG1Z:-NPM-1hV7_2b6cb5cG1_:b-22wkef) ([raw file](https://github.com/starkware-libs/cairo/blob/dea2ad5e77bb19d86bb847c99cfe418637052d34/crates/cairo-lang-language-server/src/lib.rs#L744)):*
> ```XML
> #[derive(Serialize, Deserialize, Debug)]
> pub struct PackageMetadata {
>     pub id: SmolStr,
> ```

I think we could skip `SmolStr` optimization here? Scarb uses it mostly here because it copies values from other data structures when building them, but here we are only deserializing, so there's no benefit
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 757 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2303#-NPLz3c-8Tl9TgCA3n2L:-NPLz3c-8Tl9TgCA3n2M:b-o7q2l2) ([raw file](https://github.com/starkware-libs/cairo/blob/dea2ad5e77bb19d86bb847c99cfe418637052d34/crates/cairo-lang-language-server/src/lib.rs#L757)):*
> ```XML
> 
> /// Reads Scarb project metadata from manifest file.
> fn read_scarb_metadata(manifest_path: PathBuf) -> anyhow::Result<ProjectMetadata> {
> ```

Add `use anyhow::Result`
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 763 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2303#-NPLxOaHAX91LoKig5Z6:-NPLxOaHAX91LoKig5Z7:b-1no72a) ([raw file](https://github.com/starkware-libs/cairo/blob/dea2ad5e77bb19d86bb847c99cfe418637052d34/crates/cairo-lang-language-server/src/lib.rs#L763)):*
> ```XML
>     cmd.current_dir(manifest_path.parent().unwrap());
>     let child = cmd.spawn().with_context(|| "failed to spawn")?;
>     let output = child.wait_with_output()?;
> ```

https://doc.rust-lang.org/stable/std/process/struct.Command.html#method.output



_Code quote:_
```XML
    let child = cmd.spawn().with_context(|| "failed to spawn")?;
    let output = child.wait_with_output()?;
```
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 767 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2303#-NPLxtxE05nnBEAOu-EE:-NPLxtxE05nnBEAOu-EF:bzi692d) ([raw file](https://github.com/starkware-libs/cairo/blob/dea2ad5e77bb19d86bb847c99cfe418637052d34/crates/cairo-lang-language-server/src/lib.rs#L767)):*
> ```XML
>     let messages_vec = messages_body.split('\n').collect::<Vec<&str>>();
>     let body = messages_vec[messages_vec.len() - 2];
>     let metadata: ProjectMetadata = serde_json::from_str(body)?;
> ```

This flow has some assumptions about output:

1. It assumes it will be valid UTF-8, which will not be a case in case of program malfunction
2. It assumes `ProjectMetadata` will always to second last (actually, why is it so? I thought this should go always last?)

that I think could be avoided with the following scheme:

1. `output.stdout: Vec<u8>`, so `output.stdout.as_slice: &[u8]` and there is `impl BufRead for &[u8]`. BufRead has `lines()` method, so use it for splitting output into lines
2. Revert the iterator with https://doc.rust-lang.org/stable/std/iter/trait.Iterator.html#method.rev
3. Use https://doc.rust-lang.org/stable/std/iter/trait.Iterator.html#method.flat_map to try to deserialize `ProjectMetadata` and skip lines that fail to do so. Hint: `Option` is iterable
4. Raise an error if metadata haven't been found.



_Code quote:_
```XML
    let messages_body = String::from_utf8(output.stdout).unwrap();
    let messages_vec = messages_body.split('\n').collect::<Vec<&str>>();
    let body = messages_vec[messages_vec.len() - 2];
    let metadata: ProjectMetadata = serde_json::from_str(body)?;
```
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 768 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2303#-NPLzjAR0ySFSIiPyLtU:-NPLzjAR0ySFSIiPyLtV:bcw4obh) ([raw file](https://github.com/starkware-libs/cairo/blob/dea2ad5e77bb19d86bb847c99cfe418637052d34/crates/cairo-lang-language-server/src/lib.rs#L768)):*
> ```XML
>     let body = messages_vec[messages_vec.len() - 2];
>     let metadata: ProjectMetadata = serde_json::from_str(body)?;
>     Ok(metadata)
> ```

I think it would be very desired to include `stderr` in error message in case process fails.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 790 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2303#-NPM-tDm4bVIdhqbn1kf:-NPM-tDm4bVIdhqbn1kg:b-chifzh) ([raw file](https://github.com/starkware-libs/cairo/blob/dea2ad5e77bb19d86bb847c99cfe418637052d34/crates/cairo-lang-language-server/src/lib.rs#L790)):*
> ```XML
>             };
>         }
>     }
> ```

Are you sure you need these clones here? You seem to be moving stuff out of `project_metadata`
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 805 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2303#-NPM-VmT6ImX3pxVSHis:-NPM-VmT6ImX3pxVSHit:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/dea2ad5e77bb19d86bb847c99cfe418637052d34/crates/cairo-lang-language-server/src/lib.rs#L805)):*
> ```XML
>                 update_crate_roots_from_metadata(db, metadata);
>             } else {
>                 eprintln!("Failed to obtain scarb metadata from manifest file.");
> ```





_Suggestion:_
```XML
warn!("Failed to obtain metadata from Scarb.toml.");
```
___
*[`crates/cairo-lang-project/src/lib.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2303#-NPLwz88CanDrq2uOqgv:-NPLwz88CanDrq2uOqgw:b4b96p1) ([raw file](https://github.com/starkware-libs/cairo/blob/dea2ad5e77bb19d86bb847c99cfe418637052d34/crates/cairo-lang-project/src/lib.rs#L22)):*
> ```XML
> }
> const PROJECT_FILE_NAME: &str = "cairo_project.toml";
> pub const SCARB_PROJECT_FILE_NAME: &str = "Scarb.toml";
> ```

I don't think this is a good place for this constant. Cairo compiler should not bother at all about Scarb, it's just LS concern, so I think this const should be only placed in LS crate

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2303)* status: all files reviewed, 9 unresolved discussions (waiting on @maciektr and @mkaput)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 805 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2303#-NPM-VmT6ImX3pxVSHis:-NPM7Wv696ikRhiuObo9:bkd7o7r) ([raw file](https://github.com/starkware-libs/cairo/blob/dea2ad5e77bb19d86bb847c99cfe418637052d34/crates/cairo-lang-language-server/src/lib.rs#L805)):*
> ```XML
>                 update_crate_roots_from_metadata(db, metadata);
>             } else {
>                 eprintln!("Failed to obtain scarb metadata from manifest file.");
> ```

Does wanr use stderr? Because stdout is reserved for lsp communication.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2303)* status: all files reviewed, 9 unresolved discussions (waiting on @maciektr and @mkaput)

___
*[`crates/cairo-lang-project/src/lib.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2303#-NPLwz88CanDrq2uOqgv:-NPM7gKXBDUybRor-L9z:b32v57) ([raw file](https://github.com/starkware-libs/cairo/blob/dea2ad5e77bb19d86bb847c99cfe418637052d34/crates/cairo-lang-project/src/lib.rs#L22)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I don't think this is a good place for this constant. Cairo compiler should not bother at all about Scarb, it's just LS concern, so I think this const should be only placed in LS crate
</blockquote></details>

+1

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2303)* status: all files reviewed, 9 unresolved discussions (waiting on @maciektr and @mkaput)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 737 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2303#-NPLzsHQDcobriSEMB2t:-NPM7mWD4yVZn-SwNFWB:b-aex7wh) ([raw file](https://github.com/starkware-libs/cairo/blob/dea2ad5e77bb19d86bb847c99cfe418637052d34/crates/cairo-lang-language-server/src/lib.rs#L737)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

let's be specific, use word `scarb` in all relevant items
</blockquote></details>

Should this maybe be in a Scarb crate, which we should include in the dependencies of the lsp crate?

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2303)* status: all files reviewed, 9 unresolved discussions (waiting on @maciektr and @spapinistarkware)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 737 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2303#-NPLzsHQDcobriSEMB2t:-NPMCIVL0h8W0NKDR5WA:bqqcvgg) ([raw file](https://github.com/starkware-libs/cairo/blob/dea2ad5e77bb19d86bb847c99cfe418637052d34/crates/cairo-lang-language-server/src/lib.rs#L737)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Should this maybe be in a Scarb crate, which we should include in the dependencies of the lsp crate?
</blockquote></details>

It's already in Scarb crate, but I am hesitant to make a dependency on Scarb here because:
1. It forms a cycle between two repositories
2. This would weld Scarb version with LSP version, while I believe LSP should support all Cairo/Scarb versions up to LSP version
3. Scarb is a huge dependency
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 805 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2303#-NPM-VmT6ImX3pxVSHis:-NPMC94q73cZKRlOBfko:bir8vwo) ([raw file](https://github.com/starkware-libs/cairo/blob/dea2ad5e77bb19d86bb847c99cfe418637052d34/crates/cairo-lang-language-server/src/lib.rs#L805)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Does wanr use stderr? Because stdout is reserved for lsp communication.
</blockquote></details>

By default, `tracing` outputs to stderr, not sure about log, but I think it's similar. It's all configurable

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2303)* status: all files reviewed, 9 unresolved discussions (waiting on @maciektr and @spapinistarkware)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 737 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2303#-NPLzsHQDcobriSEMB2t:-NPMCqK23E1t6OZAbXRv:br2swuw) ([raw file](https://github.com/starkware-libs/cairo/blob/dea2ad5e77bb19d86bb847c99cfe418637052d34/crates/cairo-lang-language-server/src/lib.rs#L737)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

It's already in Scarb crate, but I am hesitant to make a dependency on Scarb here because:
1. It forms a cycle between two repositories
2. This would weld Scarb version with LSP version, while I believe LSP should support all Cairo/Scarb versions up to LSP version
3. Scarb is a huge dependency
</blockquote></details>

Also, note that this is actually a strict subset of Scarb's output represented here

**Comment by maciektr** [comment]
*[`crates/cairo-lang-language-server/src/lib.rs` line 757 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2303#-NPLz3c-8Tl9TgCA3n2L:-NPNmNaADlJc7s_Gri4T:bpg3kls) ([raw file](https://github.com/starkware-libs/cairo/blob/dea2ad5e77bb19d86bb847c99cfe418637052d34/crates/cairo-lang-language-server/src/lib.rs#L757)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Add `use anyhow::Result`
</blockquote></details>

It conflicts with line 52.



_Code quote:_
```XML
use tower_lsp::jsonrpc::Result;
```

**Comment by maciektr** [comment]
*[`crates/cairo-lang-language-server/src/lib.rs` line 790 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2303#-NPM-tDm4bVIdhqbn1kf:-NPNt4t8AQgeYmMaH937:b6yjnvx) ([raw file](https://github.com/starkware-libs/cairo/blob/dea2ad5e77bb19d86bb847c99cfe418637052d34/crates/cairo-lang-language-server/src/lib.rs#L790)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Are you sure you need these clones here? You seem to be moving stuff out of `project_metadata`
</blockquote></details>

Indeed, I do not actually need all of them, though I need to copy from `package_metadata` as it is not removed from the packages map at this point.

**Review by maciektr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2303)* status: all files reviewed, 8 unresolved discussions (waiting on @mkaput and @spapinistarkware)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 737 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2303#-NPLzsHQDcobriSEMB2t:-NPNmcNx61SLFZ1-PdG4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/dea2ad5e77bb19d86bb847c99cfe418637052d34/crates/cairo-lang-language-server/src/lib.rs#L737)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Also, note that this is actually a strict subset of Scarb's output represented here
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 763 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2303#-NPLxOaHAX91LoKig5Z6:-NPNr8cADB-QdLPf_j58:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/dea2ad5e77bb19d86bb847c99cfe418637052d34/crates/cairo-lang-language-server/src/lib.rs#L763)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

https://doc.rust-lang.org/stable/std/process/struct.Command.html#method.output
</blockquote></details>

Done.
___
*[`crates/cairo-lang-project/src/lib.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2303#-NPLwz88CanDrq2uOqgv:-NPNn9bqE0RIj5D4_2vo:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/dea2ad5e77bb19d86bb847c99cfe418637052d34/crates/cairo-lang-project/src/lib.rs#L22)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

**Review by mkaput — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2303)* status: all files reviewed, 3 unresolved discussions (waiting on @maciektr and @spapinistarkware)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 790 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2303#-NPM-tDm4bVIdhqbn1kf:-NPR15xB16niBK1L2A4d:b-6b1gmv) ([raw file](https://github.com/starkware-libs/cairo/blob/dea2ad5e77bb19d86bb847c99cfe418637052d34/crates/cairo-lang-language-server/src/lib.rs#L790)):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

Indeed, I do not actually need all of them, though I need to copy from `package_metadata` as it is not removed from the packages map at this point. 
</blockquote></details>

FYI the `drain` method could be helpful here

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2303)* status: all files reviewed, 2 unresolved discussions (waiting on @maciektr and @spapinistarkware)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 774 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2303#-NPSRBWP9utbfHIGF03Z:-NPSRBWP9utbfHIGF03_:bl38if1) ([raw file](https://github.com/starkware-libs/cairo/blob/f8e08a70d75ce7c7b36ef504eb40c8bc8a78e342/crates/cairo-lang-language-server/src/lib.rs#L774)):*
> ```XML
>         .ok_or_else(|| {
>             anyhow!(
>                 "Manifest not found. Scarb stderr: `{}`",
> ```

stderr will almost always be multiline, it'd be better to have a format more like:

```
Scarb.toml not found. Calling `scarb metadata` failed.

stderr:
{}
```

**Review by maciektr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2303)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @mkaput and @spapinistarkware)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 805 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2303#-NPM-VmT6ImX3pxVSHis:-NPSbPQaDnY_Ihf0lQWt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/dea2ad5e77bb19d86bb847c99cfe418637052d34/crates/cairo-lang-language-server/src/lib.rs#L805)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

By default, `tracing` outputs to stderr, not sure about log, but I think it's similar. It's all configurable
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 774 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2303#-NPSRBWP9utbfHIGF03Z:-NPSbOhN5oF48yn4PNit:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f8e08a70d75ce7c7b36ef504eb40c8bc8a78e342/crates/cairo-lang-language-server/src/lib.rs#L774)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

stderr will almost always be multiline, it'd be better to have a format more like:

```
Scarb.toml not found. Calling `scarb metadata` failed.

stderr:
{}
```
</blockquote></details>

Done.

**Review by mkaput — APPROVED** [review]
:lgtm_strong:

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2303#-:-NPSbjp755FFZm-Onx35:b-jbsf8z)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciektr)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2303#-:-NPat2m33CqzkHsssiri:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @maciektr and @spapinistarkware)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 790 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2303#-NPasico0d43ZB4fb3sY:-NPasico0d43ZB4fb3sZ:bx3cki4) ([raw file](https://github.com/starkware-libs/cairo/blob/13df4dd6fd97ef8b747c308b3050f621496e545e/crates/cairo-lang-language-server/src/lib.rs#L790)):*
> ```XML
>     project_metadata: ScarbProjectMetadata,
> ) {
>     let packages: BTreeMap<String, ScarbPackageMetadata> = project_metadata
> ```

Why not a hash map?

**Comment by maciektr** [comment]
*[`crates/cairo-lang-language-server/src/lib.rs` line 790 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2303#-NPasico0d43ZB4fb3sY:-NPaytc42hWNIiO2EHkP:bt4v4x6) ([raw file](https://github.com/starkware-libs/cairo/blob/13df4dd6fd97ef8b747c308b3050f621496e545e/crates/cairo-lang-language-server/src/lib.rs#L790)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Why not a hash map?
</blockquote></details>

Indeed, it does not make a difference here. I've changed it to HashMap. Thanks!

**Review by mkaput — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2303)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

**Review by mkaput — APPROVED** [review]
Seems like I can merge this :tada: 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2303#-:-NPb0rnjCYpuMlpqtfwZ:bdvpn90)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

**Review by mkaput — APPROVED** [review]
Oh, actually it's blocked by Ori still, reviewable UX got me :sweat_smile: 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2303#-:-NPb1Dj17wEMGAwiK5Ms:bh36fvv)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2303)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
