### PR TITLE
LS: Refactor main loop to support `select!`

### PR DESCRIPTION
**Pull request by Draggu**
**Stack**:
- #6706
- #6705
- #6704
- #6638
- #6703
- #6702
- #6637
- #6701 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by mkaput — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6701)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @integraledelebesgue, @orizi, and @piotmag769)

**Review by Draggu — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6701)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @integraledelebesgue, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 361 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6701#-OC8Qy6w7YeYwA-dsXQI:-OC8X-nY85szMxzBG3D6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c2cbf46d18a80620cdaf334480d370a375d96b70/crates/cairo-lang-language-server/src/lib.rs#L361)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I see that you're using this macro many times in future PRs, though the `let () = unwrap_or_break!(...)` pattern looks quite hard to grasp.
</blockquote></details>

Done.

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6701#-:-OC8XSETC65ywAXNwxii:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @integraledelebesgue, @orizi, and @piotmag769)

**Review by piotmag769 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6701#-:-OC8XgrK6MNo74QZ0Bsv:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @integraledelebesgue, and @orizi)

**Pull request merged**
