### PR TITLE
LS: Make `crate::server::schedule::thread` accessible in codebase

### PR DESCRIPTION
**Pull request by mkaput**
**Stack**:
- #6508
- #6507 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by piotmag769 — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6507)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @orizi)

**Review by piotmag769 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6507#-:-O9oDE2Z33PelBG5S9p3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @orizi)

**Review by Draggu — APPROVED** [review]
I don't think this should be separate PR

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6507#-:-O9t57T_CmUQA367pz_r:b-4xzw2h)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @orizi)

**Review by mkaput — COMMENTED** [review]
This is small but paradoxically, the changes in imports etc. obfuscated diffs of #6508 hence I separated the PR. Notice that I'm changing module structure (removing re-imports etc.) in parts that #6508 has no interest in.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6507#-:-O9u3EKM72Ji-kpaNrrU:b-27i8w)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @orizi)

**Pull request merged**
