### PR TITLE
Added validation of limit  for `validate_in_range`.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1923)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1923)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1923#-NMhjP9c-GxJvgCrPZHi:-NMhjP9c-GxJvgCrPZHj:b-h4vaig) ([raw file](https://github.com/starkware-libs/cairo/blob/b15daf05620616a57c5a611df17d202852cd1966/crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs#L174)):*
> ```XML
> pub fn validate_in_range<const K: u8>(
>     casm_builder: &mut CasmBuilder,
>     limit: &BigInt,
> ```

have you considered using Felt?



_Code quote:_
```XML
BigInt
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs` line 182 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1923#-NMhltdZ5C11ATmWiZK8:-NMhltdZ5C11ATmWiZK9:bkg1xux) ([raw file](https://github.com/starkware-libs/cairo/blob/b15daf05620616a57c5a611df17d202852cd1966/crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs#L182)):*
> ```XML
> ) {
>     assert!(a_imm <= b_imm, "{a_imm} <= {a_imm}");
>     assert_eq!(limit / (u128::MAX - (K - 1) as u128), a_imm.into());
> ```


would
assert_eq (limit, a_imm * b_imm +  b_imm - 1)
 work?



_Code quote:_
```XML
    assert_eq!(limit / (u128::MAX - (K - 1) as u128), a_imm.into());
    assert_eq!(limit % (u128::MAX - (K - 1) as u128), b_imm.into());
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1923#-NMhmQtm18_zmfm8A9T1:-NMhmQtm18_zmfm8A9T2:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b15daf05620616a57c5a611df17d202852cd1966/crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs#L181)):*
> ```XML
>     auxiliary_vars: &[Var],
> ) {
>     assert!(a_imm <= b_imm, "{a_imm} <= {a_imm}");
> ```





_Suggestion:_
```XML
{a_imm} > {a_imm}
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1923)* status: 2 of 7 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1923#-NMhmQtm18_zmfm8A9T1:-NMhmXOMEtRcoos5_BKb:b4z87de) ([raw file](https://github.com/starkware-libs/cairo/blob/b15daf05620616a57c5a611df17d202852cd1966/crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs#L181)):*
> ```XML
>     auxiliary_vars: &[Var],
> ) {
>     assert!(a_imm <= b_imm, "{a_imm} <= {a_imm}");
> ```

{a_imm} > {b_imm}

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1923)* status: 2 of 7 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/uint.rs` line 201 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1923#-NMhmgcR-wLl3u66nCOl:-NMhmgcR-wLl3u66nCOm:b8vv032) ([raw file](https://github.com/starkware-libs/cairo/blob/b15daf05620616a57c5a611df17d202852cd1966/crates/cairo-lang-sierra-to-casm/src/invocations/uint.rs#L201)):*
> ```XML
>             validate_in_range::<K>(
>                 &mut casm_builder,
>                 &(BigInt::parse_bytes(PRIME_STR[2..].as_bytes(), 16).unwrap() - LIMIT),
> ```

PRIME!
macro maybe?



_Code quote:_
```XML
(BigInt::parse_bytes(PRIME_STR[2..].as_bytes(), 16).unwrap()
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1923)* status: 2 of 7 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1923#-NMhjP9c-GxJvgCrPZHi:-NMi-SHDCnMNaAMnyAtl:bvre3mw) ([raw file](https://github.com/starkware-libs/cairo/blob/b15daf05620616a57c5a611df17d202852cd1966/crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs#L174)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

have you considered using Felt?
</blockquote></details>

no since the check here is not really related to it - but fixed it in the call side.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1923#-NMhmQtm18_zmfm8A9T1:-NMi-YKKCmnWIp6BZ-B6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b15daf05620616a57c5a611df17d202852cd1966/crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs#L181)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

{a_imm} > {b_imm}
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs` line 182 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1923#-NMhltdZ5C11ATmWiZK8:-NMi-Yrk0k_VNS9DzSpE:b9bynme) ([raw file](https://github.com/starkware-libs/cairo/blob/b15daf05620616a57c5a611df17d202852cd1966/crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs#L182)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>


would
assert_eq (limit, a_imm * b_imm +  b_imm - 1)
 work?
</blockquote></details>

it would - but it would require making the u128 into bigint, and not getting which one actually failed.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/uint.rs` line 201 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1923#-NMhmgcR-wLl3u66nCOl:-NMi-nU44AvQ7xZ_HXI9:b-dfycvq) ([raw file](https://github.com/starkware-libs/cairo/blob/b15daf05620616a57c5a611df17d202852cd1966/crates/cairo-lang-sierra-to-casm/src/invocations/uint.rs#L201)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

PRIME!
macro maybe?
</blockquote></details>

used Felt conversions instead.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1923#-NMhjP9c-GxJvgCrPZHi:-NMi1ZVt2mzOD7G0VMXM:b-qmbpfp) ([raw file](https://github.com/starkware-libs/cairo/blob/b15daf05620616a57c5a611df17d202852cd1966/crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs#L174)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no since the check here is not really related to it - but fixed it in the call side.
</blockquote></details>

Maybe BigUint than?



_Code quote:_
```XML
&
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1923)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs` line 182 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1923#-NMhltdZ5C11ATmWiZK8:-NMi1KzHAhxEWtGshmLC:b-prdbzf) ([raw file](https://github.com/starkware-libs/cairo/blob/b15daf05620616a57c5a611df17d202852cd1966/crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs#L182)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it would - but it would require making the u128 into bigint, and not getting which one actually failed.
</blockquote></details>

I'm not worried about it, The goal here is to help the reviewer not the code writer.
but your call.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/uint.rs` line 201 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1923#-NMhmgcR-wLl3u66nCOl:-NMi1WMf-qLj0KNtBYEs:b-7m74ok) ([raw file](https://github.com/starkware-libs/cairo/blob/b15daf05620616a57c5a611df17d202852cd1966/crates/cairo-lang-sierra-to-casm/src/invocations/uint.rs#L201)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

used Felt conversions instead.
</blockquote></details>

nice.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1923)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1923#-NMhjP9c-GxJvgCrPZHi:-NMi1v9c6BDBxKw4PAVa:b-vqp9f3) ([raw file](https://github.com/starkware-libs/cairo/blob/b15daf05620616a57c5a611df17d202852cd1966/crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs#L174)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Maybe BigUint than?
</blockquote></details>

this makes sure i need to convert everything to ubigint on the callers side - rather not.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs` line 182 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1923#-NMhltdZ5C11ATmWiZK8:-NMi26li1elEIobFDiwR:b-x3t9v) ([raw file](https://github.com/starkware-libs/cairo/blob/b15daf05620616a57c5a611df17d202852cd1966/crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs#L182)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I'm not worried about it, The goal here is to help the reviewer not the code writer.
but your call.

</blockquote></details>

it actually is supposed to help the code writer - by not allowing bad configuration - the reviewer won't see these in the next usage.
anyway - i may just change it all to be auto calculated.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/uint.rs` line 201 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1923#-NMhmgcR-wLl3u66nCOl:-NMi2gut4ZE6T3kgEsUo:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b15daf05620616a57c5a611df17d202852cd1966/crates/cairo-lang-sierra-to-casm/src/invocations/uint.rs#L201)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

nice.
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1923#-NMhjP9c-GxJvgCrPZHi:-NMiEm6k8ko0O9kg7xT0:b-x2wy7c) ([raw file](https://github.com/starkware-libs/cairo/blob/b15daf05620616a57c5a611df17d202852cd1966/crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs#L174)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this makes sure i need to convert everything to ubigint on the callers side - rather not.
</blockquote></details>

you currently do:
  &(-Felt::from(LIMIT)).to_biguint().to_bigint().unwrap(),

can't you just remove the to_bigint?

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1923)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/starknet/storage.rs` line 71 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1923#-NMiExIdER9Em7565KD6:-NMiExIdER9Em7565KD7:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e4044c748d8352e550e25c36e98ad57c0e2a170b/crates/cairo-lang-sierra-to-casm/src/invocations/starknet/storage.rs#L71)):*
> ```XML
>     validate_in_range::<1>(
>         &mut casm_builder,
>         &(BigInt::parse_bytes(PRIME_STR[2..].as_bytes(), 16).unwrap() - addr_bound.clone()),
> ```





_Suggestion:_
```XML
 &(-Felt::from(addr_bounr)).to_biguint().to_bigint().unwrap(),
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1923)* status: 2 of 7 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/starknet/storage.rs` line 71 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1923#-NMiExIdER9Em7565KD6:-NMiIW6a-x9GsvpRSe33:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e4044c748d8352e550e25c36e98ad57c0e2a170b/crates/cairo-lang-sierra-to-casm/src/invocations/starknet/storage.rs#L71)):*
> ```XML
>     validate_in_range::<1>(
>         &mut casm_builder,
>         &(BigInt::parse_bytes(PRIME_STR[2..].as_bytes(), 16).unwrap() - addr_bound.clone()),
> ```

Done.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1923)* status: 2 of 7 files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1923)* status: 2 of 7 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1923#-NMhjP9c-GxJvgCrPZHi:-NMiR1gn9D9zfDecRnUL:b-97bur6) ([raw file](https://github.com/starkware-libs/cairo/blob/b15daf05620616a57c5a611df17d202852cd1966/crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs#L174)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

you currently do:
  &(-Felt::from(LIMIT)).to_biguint().to_bigint().unwrap(),

can't you just remove the to_bigint?
</blockquote></details>

these aren't the only usages.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r1, 1 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1923#-:-NMia5v26ZBi3_HNXOVX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
