### PR TITLE
Fixed pattern destructure in match arms

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1125)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1125#-:-NHyqOwHDwuexJJ6jKis:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/semantic/src/items/functions.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1125#-NHyqAiS1OSIfQTkQ-NP:-NHyqAiS1OSIfQTkQ-NQ:b-xaijma) ([raw file](https://github.com/starkware-libs/cairo/blob/65b46410f43952bff1f4b4d91e2cc5841e4c651c/crates/semantic/src/items/functions.rs#L38)):*
> ```XML
> impl FunctionId {
>     /// Returns the ExternFunctionId if this is an extern function. Otherwise returns none.
>     pub fn extern_function_id_or_none(
> ```

consider:
(get that returns option - is try get generally in rust)



_Suggestion:_
```XML
get_extern_function_id
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1125)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/semantic/src/items/functions.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1125#-NHyqAiS1OSIfQTkQ-NP:-NI1TqHG8u2iBHXwu5Px:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/65b46410f43952bff1f4b4d91e2cc5841e4c651c/crates/semantic/src/items/functions.rs#L38)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

consider:
(get that returns option - is try get generally in rust)
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1125)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1125)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 1 of 3 files at r2, 4 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1125)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
