### PR TITLE
Added test for all lowering phases

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2466)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2466)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware and @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2466#-NQUrzeL4_rH2aadaG_I:-NQUrzeL4_rH2aadaG_J:b-ne40if) (no related file):*
what is the use case to see all?
is this mostly for debugging?

___

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2466)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2466#-NQUrzeL4_rH2aadaG_I:-NQWQ0cL5T3fbqcOuGI3:bjwyzz3) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

what is the use case to see all?
is this mostly for debugging?
</blockquote></details>

Yes. I wrote it in a comment.
It is common that you are looking for the lowering representation after a specific phase, and it happened many times that I had to tweak the existing tests, then remove it after finding and fixing.
This is the reason I added only one simple test in there as an "example".
It is super useful.

___

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2466#-:-NQWR6Cz7vAPCYFncIYI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2466)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
