### PR TITLE
Delegated `PluginSuite` initialization outside `RootDatabaseBuilder`

### PR DESCRIPTION
**Pull request by integraledelebesgue**
**Stack**:
- #6843
- #6842
- #6841
- #6840
- #6839
- #6838 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6838)* status: 1 of 20 files reviewed, 1 unresolved discussion (waiting on @integraledelebesgue and @orizi)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6838#-ODRm0pZ6_XmKYDbfhO8:-ODRm0pZ6_XmKYDbfhO9:bf20zby) (no related file):*
The number of changes here is tremendous to a level of alerting lights for me. Have you considered having a system of "use this plugin suite by default for crates if there are no per-crate ones"? This should make you avoid any added logic to tests

**Review by integraledelebesgue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6838)* status: 1 of 20 files reviewed, 1 unresolved discussion (waiting on @mkaput and @orizi)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6838#-ODRm0pZ6_XmKYDbfhO8:-ODRpgcBAuVIrcy00qG9:b-q9l752) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

The number of changes here is tremendous to a level of alerting lights for me. Have you considered having a system of "use this plugin suite by default for crates if there are no per-crate ones"? This should make you avoid any added logic to tests
</blockquote></details>

Yeah, that would be useful in tests. This would require representing the default suite in the database and using it in the queries not being induced by Salsa's `inputs, all across the compiler. This sounds quite hacky to me. Also, it's relevant only in the context of testing so I haven't stuck with that idea.

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6838)* status: 1 of 20 files reviewed, 1 unresolved discussion (waiting on @integraledelebesgue and @orizi)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6838#-ODRm0pZ6_XmKYDbfhO8:-ODRtTSMAv41BrtiK7ys:b-6wkbsg) (no related file):*
<details><summary><i>Previously, integraledelebesgue (Jan Smółka) wrote…</i></summary><blockquote>

Yeah, that would be useful in tests. This would require representing the default suite in the database and using it in the queries not being induced by Salsa's `inputs, all across the compiler. This sounds quite hacky to me. Also, it's relevant only in the context of testing so I haven't stuck with that idea.
</blockquote></details>

it is acceptable to have such things dedicated for tests if it benefits them A LOT, and this one will do. For example, this will allow you to keep shared db

**Comment by integraledelebesgue** [comment]
Closing pull request: commit has gone away

**Pull request closed without merging**
