### PR TITLE
added support for const generic paramters in types and inference

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5234)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5234)* status: all files reviewed, 10 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/substitution.rs` line 326 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5234#-Nsd8w6DCaiWHurSKqUt:-Nsd8w6DCaiWHurSKqUu:b2ni2qw) ([raw file](https://github.com/starkware-libs/cairo/blob/14224e0b4e97bd2ce7229dc9c3e5b74469416f82/crates/cairo-lang-semantic/src/substitution.rs#L326)):*
> ```XML
>     }
> }
> add_basic_rewrites!(<'a>, SubstitutionRewriter<'a>, DiagnosticAdded, @exclude TypeLongId ImplId ConstValue);
> ```

fmt
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 247 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5234#-Nsd93Qn9v6-2PVMve6y:-Nsd93Qo1JlvmYkgwdFp:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/14224e0b4e97bd2ce7229dc9c3e5b74469416f82/crates/cairo-lang-semantic/src/expr/inference.rs#L247)):*
> ```XML
>     /// Current inferred assignment for type variables.
>     pub type_assignment: HashMap<LocalTypeVarId, TypeId>,
>     pub const_assignment: HashMap<LocalConstVarId, ConstValueId>,
> ```

doc
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 252 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5234#-Nsd94Id5kDn1rvVjhoB:-Nsd94Id5kDn1rvVjhoC:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/14224e0b4e97bd2ce7229dc9c3e5b74469416f82/crates/cairo-lang-semantic/src/expr/inference.rs#L252)):*
> ```XML
>     /// Type variables.
>     pub type_vars: Vec<TypeVar>,
>     pub const_vars: Vec<ConstVar>,
> ```

doc
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 386 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5234#-Nsd98be62GDskBZX-f2:-Nsd98be62GDskBZX-f3:bljob9k) ([raw file](https://github.com/starkware-libs/cairo/blob/14224e0b4e97bd2ce7229dc9c3e5b74469416f82/crates/cairo-lang-semantic/src/expr/inference.rs#L386)):*
> ```XML
>     }
> 
>     /// Allocates a new [TypeVar] for an unknown type that needs to be inferred.
> ```

fix doc
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 393 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5234#-Nsd9AEF0dt139VCBE23:-Nsd9AEF0dt139VCBE24:bljob9k) ([raw file](https://github.com/starkware-libs/cairo/blob/14224e0b4e97bd2ce7229dc9c3e5b74469416f82/crates/cairo-lang-semantic/src/expr/inference.rs#L393)):*
> ```XML
>     }
> 
>     /// Allocates a new [TypeVar] for an unknown type that needs to be inferred.
> ```

fix doc
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 617 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5234#-Nsd9CDA84xWoe-4CZ7D:-Nsd9CDA84xWoe-4CZ7E:bljob9k) ([raw file](https://github.com/starkware-libs/cairo/blob/14224e0b4e97bd2ce7229dc9c3e5b74469416f82/crates/cairo-lang-semantic/src/expr/inference.rs#L617)):*
> ```XML
>     }
> 
>     /// Assigns a value to a [TypeVar]. Return the assigned type, or an error.
> ```

fix doc
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 678 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5234#-Nsd9FNK-fI0xF1jPNWY:-Nsd9FNK-fI0xF1jPNWZ:bljob9k) ([raw file](https://github.com/starkware-libs/cairo/blob/14224e0b4e97bd2ce7229dc9c3e5b74469416f82/crates/cairo-lang-semantic/src/expr/inference.rs#L678)):*
> ```XML
>             Some(GenericArgumentId::Constant(const_value)) => {
>                 if let ConstValue::Var(_) = self.db.lookup_intern_const_value(*const_value) {
>                     // Don't try to infer such impls.
> ```

fix doc
___
*[`crates/cairo-lang-semantic/src/expr/inference/conform.rs` line 193 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5234#-Nsd9_asDg7us7GSaPEd:-Nsd9_asDg7us7GSaPEe:bsnx7hi) ([raw file](https://github.com/starkware-libs/cairo/blob/14224e0b4e97bd2ce7229dc9c3e5b74469416f82/crates/cairo-lang-semantic/src/expr/inference/conform.rs#L193)):*
> ```XML
>     }
> 
>     /// Same as conform_ty but supports adding snapshots to ty0 if `ty0_is_self` is true.
> ```

fix doc.
___
*[`crates/cairo-lang-semantic/src/expr/inference/conform.rs` line 221 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5234#-Nsd9em52oWDMSUor9Dw:-Nsd9em52oWDMSUor9Dx:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/14224e0b4e97bd2ce7229dc9c3e5b74469416f82/crates/cairo-lang-semantic/src/expr/inference/conform.rs#L221)):*
> ```XML
>             _ => Err(InferenceError::ConstKindMismatch { const0: id0, const1: id1 }),
>         }
>     }
> ```





_Suggestion:_
```XML
        match const_value0 {
            ConstValue::Var(var) => Ok(self.assign_const(var, id1)?),
            _ => Err(InferenceError::ConstKindMismatch { const0: id0, const1: id1 }),
        }
    }
```
___
*[`crates/cairo-lang-semantic/src/expr/test_data/generics` line 691 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5234#-NsdA8p-EKsR2s92_AdP:-NsdA8p-EKsR2s92_AdQ:b-wdlpnc) ([raw file](https://github.com/starkware-libs/cairo/blob/14224e0b4e97bd2ce7229dc9c3e5b74469416f82/crates/cairo-lang-semantic/src/expr/test_data/generics#L691)):*
> ```
> 
> //! > expected_diagnostics
> error: Unexpected return type. Expected: "test::S::<1>", found: "test::S::<?0>".
> ```

shouldn't this work?
also- please rename struct and functions to make readble.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5234)* status: 6 of 10 files reviewed, 10 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 247 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5234#-Nsd93Qn9v6-2PVMve6y:-NsdlfAsAA5ida-2Uaif:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/14224e0b4e97bd2ce7229dc9c3e5b74469416f82/crates/cairo-lang-semantic/src/expr/inference.rs#L247)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 252 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5234#-Nsd94Id5kDn1rvVjhoB:-NsdlfrRBeJ4Mhy_C6e1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/14224e0b4e97bd2ce7229dc9c3e5b74469416f82/crates/cairo-lang-semantic/src/expr/inference.rs#L252)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 386 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5234#-Nsd98be62GDskBZX-f2:-Nsdlgvb3FPRKH6QbxXE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/14224e0b4e97bd2ce7229dc9c3e5b74469416f82/crates/cairo-lang-semantic/src/expr/inference.rs#L386)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 393 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5234#-Nsd9AEF0dt139VCBE23:-Nsdlu-N1TryVvMnBstD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/14224e0b4e97bd2ce7229dc9c3e5b74469416f82/crates/cairo-lang-semantic/src/expr/inference.rs#L393)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 617 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5234#-Nsd9CDA84xWoe-4CZ7D:-NsdlvR0ACOKB3rf-ieL:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/14224e0b4e97bd2ce7229dc9c3e5b74469416f82/crates/cairo-lang-semantic/src/expr/inference.rs#L617)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 678 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5234#-Nsd9FNK-fI0xF1jPNWY:-Nsdm2kn3dneK3tuHLkj:b-cukgra) ([raw file](https://github.com/starkware-libs/cairo/blob/14224e0b4e97bd2ce7229dc9c3e5b74469416f82/crates/cairo-lang-semantic/src/expr/inference.rs#L678)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix doc
</blockquote></details>

The comment refers to the impl we are trying to return 
___
*[`crates/cairo-lang-semantic/src/expr/inference/conform.rs` line 193 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5234#-Nsd9_asDg7us7GSaPEd:-NsdmFByEAYebJFMmtuX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/14224e0b4e97bd2ce7229dc9c3e5b74469416f82/crates/cairo-lang-semantic/src/expr/inference/conform.rs#L193)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix doc.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/generics` line 691 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5234#-NsdA8p-EKsR2s92_AdP:-NsdoDDuB_xlH7dZI97G:b-ey01c6) ([raw file](https://github.com/starkware-libs/cairo/blob/14224e0b4e97bd2ce7229dc9c3e5b74469416f82/crates/cairo-lang-semantic/src/expr/test_data/generics#L691)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

shouldn't this work?
also- please rename struct and functions to make readble.
</blockquote></details>

I forgot to fix tests
done

**Review by orizi — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5234)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5234#-:-NshF6iX5X7CePRWM0wc:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
