### PR TITLE
Moved generated external module of contracts into the module itself

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1443)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1443)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/starknet/src/contract_test.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1443#-NJtU-tX2NQM1VRW4hzD:-NJtU-tX2NQM1VRW4hzE:b4fn530) ([raw file](https://github.com/starkware-libs/cairo/blob/2fbca7cba1df9f2d24a6d85052a700a9c91ad435/crates/starknet/src/contract_test.rs#L29)):*
> ```XML
>             }
>             mod __generated__ERC20 {
>                 func internal_func(ref system: System) -> felt {
> ```

why is this copied but func ep1 is not copied?



_Code quote:_
```XML
internal_func
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1443)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/starknet/src/plugin.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1443#-NJtUDzjEJPo_oKL7_Wg:-NJtUDzjEJPo_oKL7_Wh:bb7r2f0) ([raw file](https://github.com/starkware-libs/cairo/blob/2fbca7cba1df9f2d24a6d85052a700a9c91ad435/crates/starknet/src/plugin.rs#L64)):*
> ```XML
>     let mut original_items = rust::Tokens::new();
>     for item in body.items(db).elements(db) {
>         match &item {
> ```

why?



_Code quote:_
```XML
&
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1443)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/starknet/src/plugin_test_data/storage` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1443#-NJtUeSD9-1gSTjZC89Z:-NJtUeSD9-1gSTjZC89_:b-46l591) ([raw file](https://github.com/starkware-libs/cairo/blob/2fbca7cba1df9f2d24a6d85052a700a9c91ad435/crates/starknet/src/plugin_test_data/storage#L32)):*
> ```
> }
> mod __generated__TestContract {
>     struct Storage { storage_var: felt, }
> ```

maybe we want to delete the storage struct?



_Code quote:_
```
struct Storage { storage_var: felt, }
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1443)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/starknet/src/contract_test.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1443#-NJtU-tX2NQM1VRW4hzD:-NJtYI9o0RbmxQRMHh7j:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2fbca7cba1df9f2d24a6d85052a700a9c91ad435/crates/starknet/src/contract_test.rs#L29)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why is this copied but func ep1 is not copied?
</blockquote></details>

Done.
___
*[`crates/starknet/src/plugin.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1443#-NJtUDzjEJPo_oKL7_Wg:-NJtYPkf7ZNEApqbMEAI:bdn1945) ([raw file](https://github.com/starkware-libs/cairo/blob/2fbca7cba1df9f2d24a6d85052a700a9c91ad435/crates/starknet/src/plugin.rs#L64)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why?
</blockquote></details>

Because I use it after the match, so I want to avoid copying when possible.
___
*[`crates/starknet/src/plugin_test_data/storage` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1443#-NJtUeSD9-1gSTjZC89Z:-NJta-AE1nujXr9Brdx-:b-iuxafv) ([raw file](https://github.com/starkware-libs/cairo/blob/2fbca7cba1df9f2d24a6d85052a700a9c91ad435/crates/starknet/src/plugin_test_data/storage#L32)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

maybe we want to delete the storage struct?
</blockquote></details>

Maybe once I move the storage_var mod into the generated contract module?

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1443#-:-NJtpo67EjUwgY8xY755:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by ilyalesokhin-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1443)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
