### PR TITLE
Orizi/merge v2.1.0 rc0 into main

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3718)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/ec.cairo` line 32 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3718#-N_mM8C50I45gLCiPuFf:-N_mM8C50I45gLCiPuFg:b-405rn9) ([raw file](https://github.com/starkware-libs/cairo/blob/f2bad189cf93bc2a27996f7a0b4273e6a9212b29/corelib/src/ec.cairo#L32)):*
> ```Cairo
> extern fn ec_point_try_new_nz(x: felt252, y: felt252) -> Option<NonZeroEcPoint> nopanic;
> /// Constructs a non-zero point from its x coordinate.
> /// Returns `None` if no point of form (x, _) is on the curve.
> ```

should be rephrased.



_Code quote:_
```Cairo
no point of form (x, _)
```

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/ec.cairo` line 41 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3718#-N_mMZqk1kWdhZ4pxev8:-N_mMZqk1kWdhZ4pxev9:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f2bad189cf93bc2a27996f7a0b4273e6a9212b29/corelib/src/ec.cairo#L41)):*
> ```Cairo
> extern fn ec_point_is_zero(p: EcPoint) -> IsZeroResult<EcPoint> nopanic;
> 
> /// Converts `EcPoint` to `NonZeroEcPoint`.
> ```





_Suggestion:_
```Cairo
/// Converts `EcPoint` to `Optional<NonZeroEcPoint>`
```

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 55 files at r1, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3718#-:-N_mN-7d67WIFtvsHpbL:bnfp4nl)* status: 7 of 60 files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3718)* status: 7 of 60 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/ec.cairo` line 32 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3718#-N_mM8C50I45gLCiPuFf:-N_mNtu1BlBL1fpxL24Z:b-gwzc0p) ([raw file](https://github.com/starkware-libs/cairo/blob/f2bad189cf93bc2a27996f7a0b4273e6a9212b29/corelib/src/ec.cairo#L32)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

should be rephrased.
</blockquote></details>

reverted - unrelated.
___
*[`corelib/src/ec.cairo` line 41 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3718#-N_mMZqk1kWdhZ4pxev8:-N_mNx5u8v2ZDcv3i8cx:b-gwzc0p) ([raw file](https://github.com/starkware-libs/cairo/blob/f2bad189cf93bc2a27996f7a0b4273e6a9212b29/corelib/src/ec.cairo#L41)):*
> ```Cairo
> extern fn ec_point_is_zero(p: EcPoint) -> IsZeroResult<EcPoint> nopanic;
> 
> /// Converts `EcPoint` to `NonZeroEcPoint`.
> ```

reverted - unrelated.

**Review by orizi — COMMENTED** [review]
> Reviewed 54 of 55 files at r1, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3718)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
