### PR TITLE
Added function with body to lowering and Sierra generator

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1748)

### CODE REVIEW

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1748)* status: 0 of 37 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1748#-NLX0pXI6T2W650wy010:-NLX0pXI6T2W650wy011:b-3yf84a) (no related file):*
change target branch

___

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 37 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1748)* status: 4 of 37 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 383 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1748#-NL_P4zw8iC7C1YaSvx0:-NL_P4zw8iC7C1YaSvx1:bygcv5o) ([raw file](https://github.com/starkware-libs/cairo/blob/a30ad8590652f3ea5856eb08732d1d7327eee780/crates/cairo-lang-language-server/src/lib.rs#L383)):*
> ```XML
>         let file = self.file(&db, file_uri);
>         let position = params.text_document_position_params.position;
>         let Some((node, lookup_items)) = get_node_and_lookup_items(&*db, file, position) else {return Ok(None)};
> ```

Taxing: Line too long.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1748)* status: 3 of 46 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 383 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1748#-NL_P4zw8iC7C1YaSvx0:-NL_zw4FAO2DibywaSqZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a30ad8590652f3ea5856eb08732d1d7327eee780/crates/cairo-lang-language-server/src/lib.rs#L383)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Taxing: Line too long.
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 14 of 37 files at r1, 1 of 1 files at r2, 1 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1748#-:-NLa5M6834omMa3osIHZ:bnfp4nl)* status: 19 of 46 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/expr/test.rs` line 84 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1748#-NLa4ZF11pXxQwvCX-0J:-NLa4ZF249PZtxpDwwt7:b-jb0xqc) ([raw file](https://github.com/starkware-libs/cairo/blob/5be7e199dcc243aed9dc1a969c5e3fdf875b4c17/crates/cairo-lang-semantic/src/expr/test.rs#L84)):*
> ```XML
>     let test_expr = setup_test_expr(&mut db_val, "a = a * 3", "", "let mut a = 5;").unwrap();
>     let db = &db_val;
>     let expr = db.expr_semantic(test_expr.function_id.clone(), test_expr.expr_id);
> ```

Make the Id copyable please.



_Code quote:_
```XML
.clone()
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1748)* status: 19 of 46 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/expr/test.rs` line 84 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1748#-NLa4ZF11pXxQwvCX-0J:-NLa9PPr6F9pvd2UcnYI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5be7e199dcc243aed9dc1a969c5e3fdf875b4c17/crates/cairo-lang-semantic/src/expr/test.rs#L84)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Make the Id copyable please.
</blockquote></details>

Done.

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 17 of 37 files at r1, 1 of 10 files at r4, 19 of 19 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1748)* status: 37 of 46 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 9 of 10 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1748)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by yuvalsw — COMMENTED** [review]
> Dismissed @spapinistarkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1748)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
