### PR TITLE
Refactored upcast and downcast to support small BoundedInts.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #4848
- #4839
- #4813
- #4812
- #4785 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4785)

### CODE REVIEW

**Review by TomerStarkware — APPROVED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4785)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware and @liorgold2)

**Review by TomerStarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4785#-:-No6BidZ3v6ZiN44c2l6:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware and @liorgold2)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4785)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/utils.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4785#-NoBelAgE9-QWVDX82yf:-NoBelAh4tXZfWA-9h5u:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e65af467a7385bdaa89d3dde0da155ff8b2f47de/crates/cairo-lang-sierra/src/extensions/modules/utils.rs#L39)):*
> ```XML
> }
> 
> /// An half-close half-open range.
> ```





_Suggestion:_
```XML
/// A range of integers (`[lower, upper)`).
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/utils.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4785#-NoBezEeEdFDOwG9KCJg:-NoBezEeEdFDOwG9KCJh:b-ib0guk) ([raw file](https://github.com/starkware-libs/cairo/blob/e65af467a7385bdaa89d3dde0da155ff8b2f47de/crates/cairo-lang-sierra/src/extensions/modules/utils.rs#L50)):*
> ```XML
>     /// Creates a closed range i.e. `[lower, upper]`.
>     pub fn closed(lower: impl Into<BigInt>, upper: impl Into<BigInt>) -> Self {
>         Self::half_open(lower, upper.into() + 1)
> ```

How does it know which type to cast into?
I think I prefer to have an explicit cast to `BigInt` in this case.



_Code quote:_
```XML
.into()
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4785)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/utils.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4785#-NoBfBL08puOQ6H4t7-V:-NoBfBL08puOQ6H4t7-W:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/e65af467a7385bdaa89d3dde0da155ff8b2f47de/crates/cairo-lang-sierra/src/extensions/modules/utils.rs#L56)):*
> ```XML
>         Self { lower: lower.into(), upper: upper.into() }
>     }
>     /// Returns the Range bounds from the given type info.
> ```

.



_Suggestion:_
```XML
    /// Returns the [Range] bounds from the given type info.
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4785)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/utils.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4785#-NoBfBL08puOQ6H4t7-V:-NoBfaC-73dp0D2OEpaP:b-2uc5ym) ([raw file](https://github.com/starkware-libs/cairo/blob/e65af467a7385bdaa89d3dde0da155ff8b2f47de/crates/cairo-lang-sierra/src/extensions/modules/utils.rs#L56)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

.
</blockquote></details>

Same below.

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4785)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4785)* status: all files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-sierra-ap-change/src/core_libfunc_ap_change.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4785#-NoBuDtM6efAGuO1TBVV:-NoBuDtM6efAGuO1TBVW:b-c93o0r) ([raw file](https://github.com/starkware-libs/cairo/blob/e65af467a7385bdaa89d3dde0da155ff8b2f47de/crates/cairo-lang-sierra-ap-change/src/core_libfunc_ap_change.rs#L104)):*
> ```XML
>             CastConcreteLibfunc::Downcast(libfunc) => {
>                 // Overflow tests are more expensive when asserting a value is above non-zero value.
>                 let extra_below = usize::from(!libfunc.to_range.lower.is_zero());
> ```

(Consider using `if libfunc.to_range.lower.is_zero() { 1 } else { 0 }` in such cases instead of `usize::from`)



_Code quote:_
```XML
usize::from(!libfunc.to_range.lower.is_zero())
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4785)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @liorgold2)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/utils.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4785#-NoBelAgE9-QWVDX82yf:-NoCLCTwBPPe61kF2VsU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e65af467a7385bdaa89d3dde0da155ff8b2f47de/crates/cairo-lang-sierra/src/extensions/modules/utils.rs#L39)):*
> ```XML
> }
> 
> /// An half-close half-open range.
> ```

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/utils.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4785#-NoBezEeEdFDOwG9KCJg:-NoCLCxu8VqeA-KbKLI9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e65af467a7385bdaa89d3dde0da155ff8b2f47de/crates/cairo-lang-sierra/src/extensions/modules/utils.rs#L50)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

How does it know which type to cast into?
I think I prefer to have an explicit cast to `BigInt` in this case.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-ap-change/src/core_libfunc_ap_change.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4785#-NoBuDtM6efAGuO1TBVV:-NoCLHKVAfxY_uDpjHcx:bcgpmqh) ([raw file](https://github.com/starkware-libs/cairo/blob/e65af467a7385bdaa89d3dde0da155ff8b2f47de/crates/cairo-lang-sierra-ap-change/src/core_libfunc_ap_change.rs#L104)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

(Consider using `if libfunc.to_range.lower.is_zero() { 1 } else { 0 }` in such cases instead of `usize::from`)
</blockquote></details>

clippy prefers this when there's no `!` but Done anyway.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4785)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware, @orizi, and @TomerStarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4785#-NoCm5Ur7j-ezj-hBGcr:-NoCm5Ur7j-ezj-hBGcs:b-ejkesh) ([raw file](https://github.com/starkware-libs/cairo/blob/4c0a4e02b7331ded48ede1377c2b2532a994e624/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L43)):*
> ```XML
>     assert!(
>         libfunc.from_range.is_rc() && libfunc.to_range.is_rc(),
>         "Downcasting from types of size > 128 bit is not supported."
> ```

(since it's not just "from types" but also "to types")



_Suggestion:_
```XML
"Downcasting is not supported for types of size > 128 bit."
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4785#-NoCmeGA0QWgNwvP_7Nb:-NoCmeGA0QWgNwvP_7Nc:b-odqna0) ([raw file](https://github.com/starkware-libs/cairo/blob/c1f9ed85f3e94452819f2436358ee3a97d896949/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L53)):*
> ```XML
>         }
>         CastType { overflow_above: true, overflow_below: false } => {
>             // Signed to signed would go the `both` or `no_overflow` cases.
> ```

Remind me, why did we have the assert in the first place?

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4785)* status: 7 of 8 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware, @orizi, and @TomerStarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 180 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4785#-NoCnTlm22mtDxbIxt7v:-NoCnTlm22mtDxbIxt7w:b-919uhk) ([raw file](https://github.com/starkware-libs/cairo/blob/4c0a4e02b7331ded48ede1377c2b2532a994e624/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L180)):*
> ```XML
> 
>     casm_build_extend!(casm_builder, OverflowAbove:);
>     validate_ge_no_opt(casm_builder, range_check, value, &to_range.upper);
> ```

Why the `no_opt`?
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 199 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4785#-NoCnHyU2zyBcnlXCJis:-NoCnHyVEOSP1ChIwRjR:bg6f1n9) ([raw file](https://github.com/starkware-libs/cairo/blob/4c0a4e02b7331ded48ede1377c2b2532a994e624/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L199)):*
> ```XML
> 
> /// Validates that `value` is greater or equal to `bound`.
> /// If `bound` is zero, this is a no-op, does no calculation.
> ```

WDYM by this? It does a range-check.



_Code quote:_
```XML
/// If `bound` is zero, this is a no-op, does no calculation.
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 208 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4785#-NoCneTy0ZVfyJDECe-N:-NoCneTy0ZVfyJDECe-O:b2wchue) ([raw file](https://github.com/starkware-libs/cairo/blob/4c0a4e02b7331ded48ede1377c2b2532a994e624/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L208)):*
> ```XML
> }
> 
> /// Validates that `value` is greater or equal to `bound`.
> ```

Add something like `/// A non-optimized version of validate_ge(). Required since ...`



_Code quote:_
```XML
/// Validates that `value` is greater or equal to `bound`.
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4785)* status: 7 of 8 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware, @orizi, and @TomerStarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4785#-NoCo-LN2C1VWPTTprXs:-NoCo-LN2C1VWPTTprXt:bzavlar) ([raw file](https://github.com/starkware-libs/cairo/blob/c1f9ed85f3e94452819f2436358ee3a97d896949/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L42)):*
> ```XML
> impl IntTypeInfo {
>     /// Returns the cast type.
>     pub fn cast_type(&self, to: &IntTypeInfo) -> CastType {
> ```

Can't say I'll miss this function...

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4785)* status: 7 of 8 files reviewed, 8 unresolved discussions (waiting on @gilbens-starkware, @orizi, and @TomerStarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4785#-NoCoLWH67PiB_Sn5AW6:-NoCoLWI-hRlIKL3izti:bnqrpee) ([raw file](https://github.com/starkware-libs/cairo/blob/4c0a4e02b7331ded48ede1377c2b2532a994e624/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L48)):*
> ```XML
>         let from_range = Range::from_type(context, from_ty.clone())?;
>         let to_range: Range = Range::from_type(context, to_ty.clone())?;
>         if to_range.lower > from_range.lower || to_range.upper < from_range.upper {
> ```

I'd go with
```
let is_upcast = to_range.lower <= from_range.lower && from_range.upper <= to_range.upper;
if !is_upcast { ... }
```

(which is the picture I have when I imagine the inclusion of the ranges `[ .. [ ... ] ... ]`)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4785)* status: 7 of 8 files reviewed, 8 unresolved discussions (waiting on @gilbens-starkware, @orizi, and @TomerStarkware)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4785)* status: 7 of 8 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware, @liorgold2, and @TomerStarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4785#-NoCm5Ur7j-ezj-hBGcr:-NoCppOCBeA53I3l5U7q:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4c0a4e02b7331ded48ede1377c2b2532a994e624/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L43)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

(since it's not just "from types" but also "to types")
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4785#-NoCmeGA0QWgNwvP_7Nb:-NoCp-Hp3aSPjV-fgKHl:b9wn2ed) ([raw file](https://github.com/starkware-libs/cairo/blob/c1f9ed85f3e94452819f2436358ee3a97d896949/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L53)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Remind me, why did we have the assert in the first place?
</blockquote></details>

because the cost calculation was wrong in some edge cases that couldn't happen.
the overflow above below stuff in the calculation solve this case.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 180 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4785#-NoCnTlm22mtDxbIxt7v:-NoCpEMzBJ2VQBF4_T-H:btig1je) ([raw file](https://github.com/starkware-libs/cairo/blob/4c0a4e02b7331ded48ede1377c2b2532a994e624/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L180)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Why the `no_opt`?
</blockquote></details>

to make the merged arms take the same amount of work always. (otherwise ap-mismatch)
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 199 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4785#-NoCnHyU2zyBcnlXCJis:-NoCq9YYCeFJHSTEZbae:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4c0a4e02b7331ded48ede1377c2b2532a994e624/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L199)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

WDYM by this? It does a range-check.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 208 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4785#-NoCneTy0ZVfyJDECe-N:-NoCqNRAB-0M0kYcDjV-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4c0a4e02b7331ded48ede1377c2b2532a994e624/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L208)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Add something like `/// A non-optimized version of validate_ge(). Required since ...`
</blockquote></details>

Done.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r1, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4785)* status: 6 of 8 files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware, @orizi, and @TomerStarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/utils.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4785#-NoBezEeEdFDOwG9KCJg:-NoGDSlW8YLOUXmzDRIz:b-hjrtvg) ([raw file](https://github.com/starkware-libs/cairo/blob/e65af467a7385bdaa89d3dde0da155ff8b2f47de/crates/cairo-lang-sierra/src/extensions/modules/utils.rs#L50)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not sure you understood me. I think moving to `impl Into<>` was good.
I was just worried about `upper.into() + 1` - what the `into` does in this case? And in any case, change this particular `into` (`upper.into()`) to have an explicit cast to `BigInt`.

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4785)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @orizi, and @TomerStarkware)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4785)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware, @orizi, and @TomerStarkware)

___
*[`tests/e2e_test_data/libfuncs/casts` line 682 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4785#-NoGFn364ViCwWDqmWmA:-NoGFn364ViCwWDqmWmB:byvtfiv) ([raw file](https://github.com/starkware-libs/cairo/blob/0ad1cef82f72cd90d25e62286f3c32518332f267/tests/e2e_test_data/libfuncs/casts#L682)):*
> ```
> //! > ==========================================================================
> 
> //! > i8 to BoundedInt<-5, 5> downcast
> ```

(to avoid the symmetry and be able to see where each "5" in the casm output came from)



_Suggestion:_
```
//! > i8 to BoundedInt<-5, 3> downcast
```

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4785)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware, @orizi, and @TomerStarkware)

___
*[`tests/e2e_test_data/libfuncs/casts` line 915 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4785#-NoGpLw37S9Swg9C5Qlf:-NoGpLw37S9Swg9C5Qlg:brgwrm7) ([raw file](https://github.com/starkware-libs/cairo/blob/0ad1cef82f72cd90d25e62286f3c32518332f267/tests/e2e_test_data/libfuncs/casts#L915)):*
> ```
> [ap + -1] = [[fp + -4] + 0];
> jmp rel 19;
> [fp + -3] = [ap + 0] + 0, ap++;
> ```

This instruction seems to be redundant.

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4785)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware, @orizi, and @TomerStarkware)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4785)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware, @liorgold2, and @TomerStarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/utils.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4785#-NoBezEeEdFDOwG9KCJg:-NoGxlNeDDfa6NwIjhWP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e65af467a7385bdaa89d3dde0da155ff8b2f47de/crates/cairo-lang-sierra/src/extensions/modules/utils.rs#L50)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Not sure you understood me. I think moving to `impl Into<>` was good.
I was just worried about `upper.into() + 1` - what the `into` does in this case? And in any case, change this particular `into` (`upper.into()`) to have an explicit cast to `BigInt`.
</blockquote></details>

Done.
___
*[`tests/e2e_test_data/libfuncs/casts` line 682 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4785#-NoGFn364ViCwWDqmWmA:-NoGxuZE54lZD7v1rwZ8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0ad1cef82f72cd90d25e62286f3c32518332f267/tests/e2e_test_data/libfuncs/casts#L682)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

(to avoid the symmetry and be able to see where each "5" in the casm output came from)
</blockquote></details>

Done.
___
*[`tests/e2e_test_data/libfuncs/casts` line 915 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4785#-NoGpLw37S9Swg9C5Qlf:-NoGxzQ3BDomGUK_w_Zm:buu2aua) ([raw file](https://github.com/starkware-libs/cairo/blob/0ad1cef82f72cd90d25e62286f3c32518332f267/tests/e2e_test_data/libfuncs/casts#L915)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

This instruction seems to be redundant.
</blockquote></details>

it is caused by the "no-opt" call.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4785)* status: 7 of 8 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware, @orizi, and @TomerStarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/utils.rs` line 87 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4785#-NoH7QwkCo8CD4C-NJK1:-NoH7QwkCo8CD4C-NJK2:b-6w74lq) ([raw file](https://github.com/starkware-libs/cairo/blob/293ed7d93d76e23fd3894c39b43c841b791fde71/crates/cairo-lang-sierra/src/extensions/modules/utils.rs#L87)):*
> ```XML
>     }
>     /// Returns true if this range is smaller than the RangeCheck range.
>     pub fn is_rc(&self) -> bool {
> ```

Rename (e.g., `small_range_size`, `range_size_in_u128` (which is not accurate given the `<=`).

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4785)* status: 4 of 8 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware, @liorgold2, and @TomerStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4785#-NoGHWl-6tyFAM7AURbD:-NoHH8p898Wr1xzvpI4A:b-896fix) (no related file):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Add some Cairo tests. Specifically things that couldn't happen before (e.g., `[100, 200) to [120, 180)` or values bigger than 2**128 (as long as the range size < 2**128)
</blockquote></details>

Done.

___
___
*[`crates/cairo-lang-sierra/src/extensions/modules/utils.rs` line 87 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4785#-NoH7QwkCo8CD4C-NJK1:-NoHDnKc3t5tC721YioN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/293ed7d93d76e23fd3894c39b43c841b791fde71/crates/cairo-lang-sierra/src/extensions/modules/utils.rs#L87)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Rename (e.g., `small_range_size`, `range_size_in_u128` (which is not accurate given the `<=`).
</blockquote></details>

Done.

**Review by TomerStarkware — APPROVED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4785)* status: all files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @liorgold2)

**Review by TomerStarkware — APPROVED** [review]
> Reviewed 1 of 4 files at r5, 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4785)* status: all files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @liorgold2)

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r5, 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4785#-:-NocKg2V4YkAj64zva8Y:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
