### PR TITLE
Move inference errors to notes.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3716)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3716#-:-N_lrENi63dMNIu5uIY7:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/diagnostic.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3716#-N_lr4go42OAeWMD7aUf:-N_lr4go42OAeWMD7aUg:b-lb860o) ([raw file](https://github.com/starkware-libs/cairo/blob/dd32a58d7ba1f03a384ecb4545d322e49b064b81/crates/cairo-lang-lowering/src/diagnostic.rs#L67)):*
> ```XML
>             LoweringDiagnosticKind::DesnappingANonCopyableType { .. } => {
>                 "Cannot desnap a non copyable type.".into()
>             }
> ```

maybe remove the members as these are no longer used?



_Code quote:_
```XML
            }
            LoweringDiagnosticKind::VariableMoved { .. } => {
                "Variable was previously moved.".into()
            }
            LoweringDiagnosticKind::VariableNotDropped { .. } => {
                "Variable not dropped.".into()
            }
            LoweringDiagnosticKind::DesnappingANonCopyableType { .. } => {
                "Cannot desnap a non copyable type.".into()
            }
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/diagnostic.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3716#-N_lr4go42OAeWMD7aUf:-N_lrrO04IgUSNi4fuDW:bfrs5gk) ([raw file](https://github.com/starkware-libs/cairo/blob/dd32a58d7ba1f03a384ecb4545d322e49b064b81/crates/cairo-lang-lowering/src/diagnostic.rs#L67)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe remove the members as these are no longer used?
</blockquote></details>

I've considered it, but I think shahar wants the diagnostics to be programmatically inspectable.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/diagnostic.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3716#-N_lr4go42OAeWMD7aUf:-N_lt0wKCwy_S1gHS7hS:bi8jfyg) ([raw file](https://github.com/starkware-libs/cairo/blob/dd32a58d7ba1f03a384ecb4545d322e49b064b81/crates/cairo-lang-lowering/src/diagnostic.rs#L67)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I've considered it, but I think shahar wants the diagnostics to be programmatically inspectable.
</blockquote></details>

I guess the long-term solution is to extend the notes respectability, but I don't know how to do that right now.

Do you think I should remove the inference errors for now?

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3716)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/diagnostic.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3716#-N_lr4go42OAeWMD7aUf:-N_lur8a38PlC3VDehUU:b-dmqfy2) ([raw file](https://github.com/starkware-libs/cairo/blob/dd32a58d7ba1f03a384ecb4545d322e49b064b81/crates/cairo-lang-lowering/src/diagnostic.rs#L67)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I guess the long-term solution is to extend the notes respectability, but I don't know how to do that right now.

Do you think I should remove the inference errors for now?
</blockquote></details>

no - the current way sg.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3716)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
