### PR TITLE
Include test config in language server

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2593)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2593#-:-NRRsyWSEEXdaXT91AB0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2593)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2593#-NRS-gYZ1xKZrXE4MhAC:-NRS-gYZ1xKZrXE4MhAD:b-vcm5gj) (no related file):*
This conflicts quite a lot with #2589. Seems to be much easier to resolve conflicts when that one is merged

___

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2593)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @mkaput and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2593#-NRS-gYZ1xKZrXE4MhAC:-NRS0PyyBLKT-skza1J7:b-lp4z56) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

This conflicts quite a lot with #2589. Seems to be much easier to resolve conflicts when that one is merged
</blockquote></details>

Can you update 2589 to also make LSP see test config?

___

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2593)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2593#-NRS-gYZ1xKZrXE4MhAC:-NRSNCDg7TAHx5JqeLyo:bj5siq9) (no related file):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Can you update 2589 to also make LSP see test config?
</blockquote></details>

Will do tomorrow

___

**Pull request closed without merging**
