### PR TITLE
Added variants to arms of MatchExtern

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1113)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1113)* status: 1 of 11 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/lowering/src/lower.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1113#-NHxDlgK5H5_y8qTHMin:-NHxDlgK5H5_y8qTHMio:bp6d4e6) ([raw file](https://github.com/starkware-libs/cairo/blob/b1a385576fafb24632f0c14636c96d19db0ecb02/crates/lowering/src/lower.rs#L8)):*
> ```XML
> use scope::{BlockScope, BlockScopeEnd};
> use semantic::corelib::{
>     self, core_felt_ty, core_jump_nz_func, core_nonzero_ty, get_core_function_id,
> ```

I tihnk we should ne consistent. Either use everything through corelib::, or nothing.



_Code quote:_
```XML
self,
```

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1113)* status: 1 of 11 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/lowering/src/test.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1113#-NHxE15j6kJGbwICwn4m:-NHxE15j6kJGbwICwn4n:b-wq98ir) ([raw file](https://github.com/starkware-libs/cairo/blob/b1a385576fafb24632f0c14636c96d19db0ecb02/crates/lowering/src/test.rs#L12)):*
> ```XML
>     lowering_test,
>     [
>         // "src/test_data/assignment",
> ```

Nice try

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1113)* status: 1 of 11 files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/lowering/src/test_data/match` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1113#-NHxE5jE8wXZURefmUAJ:-NHxE5jE8wXZURefmUAK:b-li4yil) ([raw file](https://github.com/starkware-libs/cairo/blob/6175f09d97f0d8ed8ad5a70c56340d10799c5891/crates/lowering/src/test_data/match#L55)):*
> ```
> //! > ==========================================================================
> 
> //! > Test match zero with non-zero value.
> ```

Why deleted?

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 10 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1113)* status: all files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1113)* status: 8 of 11 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/lowering/src/lower.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1113#-NHxDlgK5H5_y8qTHMin:-NHxM1uY-jNOGlpqADlc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b1a385576fafb24632f0c14636c96d19db0ecb02/crates/lowering/src/lower.rs#L8)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I tihnk we should ne consistent. Either use everything through corelib::, or nothing.
</blockquote></details>

Done.
___
*[`crates/lowering/src/test.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1113#-NHxE15j6kJGbwICwn4m:-NHxLkla-hgbTEyGnAKS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b1a385576fafb24632f0c14636c96d19db0ecb02/crates/lowering/src/test.rs#L12)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Nice try
</blockquote></details>

Done.
___
*[`crates/lowering/src/test_data/match` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1113#-NHxE5jE8wXZURefmUAJ:-NHxLqhvCrse_7fnStEa:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6175f09d97f0d8ed8ad5a70c56340d10799c5891/crates/lowering/src/test_data/match#L55)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Why deleted?
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1113#-:-NHxRIc58R0EiW14Yaia:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 7 of 11 files at r1, 2 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1113)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
