### PR TITLE
Added ability for minimal support of reads and writes in hints.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1535)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1535)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-casm/src/run.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1535#-NKNc-ei6mHGuflip1qp:-NKNc-ei6mHGuflip1qq:bcqrywb) ([raw file](https://github.com/starkware-libs/cairo/blob/512d968b4f64ce7f163494d3b34286c067167123/crates/cairo-casm/src/run.rs#L86)):*
> ```XML
> 
> /// Execution scope for starknet related data.
> struct StarknetExecScope {
> ```

I think we should keep track of the syscall_ptr here.



_Code quote:_
```XML
StarknetExecScope
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1535)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-casm/src/run.rs` line 208 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1535#-NKNckoC4qRgwmrhoWJz:-NKNckoC4qRgwmrhoWK-:b-67m4qz) ([raw file](https://github.com/starkware-libs/cairo/blob/512d968b4f64ce7f163494d3b34286c067167123/crates/cairo-casm/src/run.rs#L208)):*
> ```XML
>                         vm.insert_value(&revert_reason_ptr, BigInt::from(0))?;
>                     } else {
>                         vm.insert_value(&gas_counter_updated_ptr, gas_counter)?;
> ```

Maybe we shouldn't have and updated gas counter int the failure case?



_Code quote:_
```XML
      vm.insert_value(&gas_counter_updated_ptr, gas_counter)?;
```

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1535#-:-NKNe1Xc4p4zSY_xf65r:bnfp4nl)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1535)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-casm/src/run.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1535#-NKNc-ei6mHGuflip1qp:-NKNgfTx7_Y-ovkNlKCk:b-wem3s7) ([raw file](https://github.com/starkware-libs/cairo/blob/512d968b4f64ce7f163494d3b34286c067167123/crates/cairo-casm/src/run.rs#L86)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I think we should keep track of the syscall_ptr here.
</blockquote></details>

maybe we should - but this is complicated - as we don't know where is the initial value of the syscall ptr, and initialising if from the first usages sounds wierd.
___
*[`crates/cairo-casm/src/run.rs` line 208 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1535#-NKNckoC4qRgwmrhoWJz:-NKNfoEv6ZD24NqwPblj:bbmcmv) ([raw file](https://github.com/starkware-libs/cairo/blob/512d968b4f64ce7f163494d3b34286c067167123/crates/cairo-casm/src/run.rs#L208)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Maybe we shouldn't have and updated gas counter int the failure case?
</blockquote></details>

in the cases of running out of gas - we may decide to return 0 - but actually returning a minus would be an issue.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1535)* status: 0 of 3 files reviewed, 1 unresolved discussion

___
*[`crates/cairo-casm/src/run.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1535#-NKNc-ei6mHGuflip1qp:-NKNhSU27B6D-JTG8th-:b32wtd) ([raw file](https://github.com/starkware-libs/cairo/blob/512d968b4f64ce7f163494d3b34286c067167123/crates/cairo-casm/src/run.rs#L86)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe we should - but this is complicated - as we don't know where is the initial value of the syscall ptr, and initialising if from the first usages sounds wierd.
</blockquote></details>

ok

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1535)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
