### PR TITLE
Format starknet plugin code.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1560)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1560)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`crates/cairo-starknet/src/plugin.rs` line 133 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1560#-NKS40z9E0WNA_2f7slm:-NKS40z9E0WNA_2f7sln:b-74xjef) ([raw file](https://github.com/starkware-libs/cairo/blob/d37f22b315619fdb27a4d2e54e803f5fe5a3e6fe/crates/cairo-starknet/src/plugin.rs#L133)):*
> ```XML
>             name: "contract".into(),
>             // TODO(ilya): Remove formatting once the plugin output is readable.
>             content: cairo_formatter::format_string(db, contract_code),
> ```

This will mess with patcher, right?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1560)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-starknet/src/plugin.rs` line 133 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1560#-NKS40z9E0WNA_2f7slm:-NKS5t3e0CiUlREo0lO6:bpjzmr6) ([raw file](https://github.com/starkware-libs/cairo/blob/d37f22b315619fdb27a4d2e54e803f5fe5a3e6fe/crates/cairo-starknet/src/plugin.rs#L133)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This will mess with patcher, right?
</blockquote></details>

The code here does not use the patcher.

We will remove it when we fix the code to use the patcher.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1560#-:-NKS8FvK9yXm1TeTbV7Z:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1560)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
