### PR TITLE
Bidirectional type inference

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1823)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 12 of 13 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1823#-:-NMEeiwG-hGh_lQjp37_:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1823#-NMEdtBR1NDaYJNsFDBw:-NMEdtBS8pjDSKkyrm9U:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/5d062a14e68db311fa68ec77fd5ceb46e5f9dc87/crates/cairo-lang-semantic/src/expr/inference.rs#L14)):*
> ```XML
> 
> #[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
> pub struct TypeVar {
> ```

doc



_Code quote:_
```XML
pub struct TypeVar {
```
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1823#-NMEdy6u1gcGNbQXQ9Eq:-NMEdy6u1gcGNbQXQ9Er:b-5ae9kc) ([raw file](https://github.com/starkware-libs/cairo/blob/5d062a14e68db311fa68ec77fd5ceb46e5f9dc87/crates/cairo-lang-semantic/src/expr/inference.rs#L26)):*
> ```XML
> }
> 
> pub struct Inference<'db> {
> ```

doc all



_Code quote:_
```XML
pub struct Inference<'db> {
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1823)* status: 9 of 13 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1823#-NMEdtBR1NDaYJNsFDBw:-NMF9QKf12Nr7M6v7fd_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5d062a14e68db311fa68ec77fd5ceb46e5f9dc87/crates/cairo-lang-semantic/src/expr/inference.rs#L14)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1823#-NMEdy6u1gcGNbQXQ9Eq:-NMF9Pr69l87mRcuqu5G:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5d062a14e68db311fa68ec77fd5ceb46e5f9dc87/crates/cairo-lang-semantic/src/expr/inference.rs#L26)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc all
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1823)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 136 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1823#-NMFBi-7CA7Oq58RDYbE:-NMFBi-7CA7Oq58RDYbF:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/0459aa3b8bba05f9d056e4f72210c18e999a058f/crates/cairo-lang-semantic/src/expr/inference.rs#L136)):*
> ```XML
>     /// Gets current canonical representation for a [Pattern] after all known
>     /// substitutions.
>     pub fn reduce_pattern(&mut self, pattern: &mut Pattern) {
> ```

?



_Suggestion:_
```XML
    /// Updates current canonical representation for a [Pattern] after all known
    /// substitutions.
    pub fn reduce_pattern(&mut self, pattern: &mut Pattern) {
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1823)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 136 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1823#-NMFBi-7CA7Oq58RDYbE:-NMFUblo9qBQXj4urSO6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0459aa3b8bba05f9d056e4f72210c18e999a058f/crates/cairo-lang-semantic/src/expr/inference.rs#L136)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1823)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
