### PR TITLE
Renamed uint128 -> u128, uint256 -> u256.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:27956b65

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 35 of 36 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1369)* status: 35 of 36 files reviewed, 1 unresolved discussion (waiting on @liorgold2, @orizi, @spapinistarkware, and @yuvalsw)

___
*[`corelib/integer.cairo` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1369#-NJYmaAg7gThuH6Yq8pN:-NJYmaAg7gThuH6Yq8pO:bangls1) ([raw file](https://github.com/starkware-libs/cairo/blob/24cf46e16dc9e2596b1ac8c36910102682b4f128/corelib/integer.cairo#L1)):*
> ```Cairo
> extern type u128;
> ```

I'm not sure we should change the sierra type name.

consider using
extern type uint128;
type u128 = uint128;



_Code quote:_
```Cairo
extern type u128;
```

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1369#-:-NJYmmda3cqeqKb_CJfm:bnfp4nl)* status: 35 of 36 files reviewed, 1 unresolved discussion (waiting on @liorgold2, @orizi, @spapinistarkware, and @yuvalsw)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1369)* status: 35 of 36 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware, @liorgold2, @spapinistarkware, and @yuvalsw)

___
*[`corelib/integer.cairo` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1369#-NJYmaAg7gThuH6Yq8pN:-NJZ0z-o6g-azxLaxwBS:bezpn2) ([raw file](https://github.com/starkware-libs/cairo/blob/24cf46e16dc9e2596b1ac8c36910102682b4f128/corelib/integer.cairo#L1)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I'm not sure we should change the sierra type name.

consider using
extern type uint128;
type u128 = uint128;
</blockquote></details>

adding to discussions.

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 1 of 36 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1369)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2, @spapinistarkware, and @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
> Reviewed 26 of 36 files at r1, 3 of 3 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1369)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2, @orizi, and @spapinistarkware)

___
*[`crates/semantic/src/diagnostic_test_data/tests` line 173 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1369#-NJbC_ZDC_78PGYaQIGb:-NJbC_ZDC_78PGYaQIGc:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7c1c1038abd9b1d72034358cce9195c753e5c124/crates/semantic/src/diagnostic_test_data/tests#L173)):*
> ```
>     let a = 123_u128;
>     let b = 123_NonZero;
>     let b = 123_uint129;
> ```





_Suggestion:_
```
u129
```

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1369#-:-NJdduKW9TOSP_X-OnfT:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2, @orizi, and @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1369)* status: 35 of 36 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware, @liorgold2, @spapinistarkware, and @yuvalsw)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1369)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2 and @spapinistarkware)

**Pull request merged**
