### PR TITLE
Add more drop statements.

### PR DESCRIPTION
**Pull request by liorgold2**
commit-id:e5c4f412

---

**Stack**:
- #1563
- #1562
- #1561 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1561#-:-NKTSgwz1jg2K4kb3NeS:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-sierra-generator/src/block_generator.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1561#-NKTSHu93js5k7y26UnT:-NKTSHu93js5k7y26UnU:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/e62104c74c9b6f5e655b5bf263870e7f25d11eae/crates/cairo-sierra-generator/src/block_generator.rs#L55)):*
> ```XML
> }
> 
> fn add_drop_statements(
> ```

doc



_Code quote:_
```XML
add_drop_statements(
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1561)* status: 22 of 23 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-sierra-generator/src/block_generator.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1561#-NKTSHu93js5k7y26UnT:-NKcuzcR5oEpRl2fbQcw:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e62104c74c9b6f5e655b5bf263870e7f25d11eae/crates/cairo-sierra-generator/src/block_generator.rs#L55)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1561)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @orizi)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1561)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1561)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
