### PR TITLE
Added `panic_with_byte_array`

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4261)

### CODE REVIEW

**Comment by yuvalsw** [comment]
change target

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4261)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/byte_array.cairo` line 266 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4261#-NgoFHOG9L5d71WuKUpd:-NgoFHOG9L5d71WuKUpe:bhxh10h) ([raw file](https://github.com/starkware-libs/cairo/blob/31c812c0ec4be1c74392e2225ba5004c03e1ac06/corelib/src/byte_array.cairo#L266)):*
> ```Cairo
>     fn panic(self: ByteArray) -> never {
>         panic_with_byte_array(self)
>     }
> ```

remove this.
we'd add an inline macro wrapper for this.



_Code quote:_
```Cairo
    /// Panics with `self`. That is, panics with an `Array<felt252>` with `BYTE_ARRAY_MAGIC`, and
    /// then the serialization of `self`.
    #[inline(always)]
    fn panic(self: ByteArray) -> never {
        panic_with_byte_array(self)
    }
```
___
*[`corelib/src/test/byte_array_test.cairo` line 448 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4261#-NgoFd9t8f1yMe38IO0j:-NgoFd9t8f1yMe38IO0k:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/31c812c0ec4be1c74392e2225ba5004c03e1ac06/corelib/src/test/byte_array_test.cairo#L448)):*
> ```Cairo
> 
> #[test]
> // TODO(yuval): use BYTE_ARRAY_MAGIC in these tests once constants are supported.
> ```





_Suggestion:_
```Cairo
// TODO(yuval): have "" in the test from the framework.
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4261)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/byte_array.cairo` line 266 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4261#-NgoFHOG9L5d71WuKUpd:-Ngs2HSa7-S4vEFTWRzX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/31c812c0ec4be1c74392e2225ba5004c03e1ac06/corelib/src/byte_array.cairo#L266)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove this.
we'd add an inline macro wrapper for this.
</blockquote></details>

Done.
___
*[`corelib/src/test/byte_array_test.cairo` line 448 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4261#-NgoFd9t8f1yMe38IO0j:-Ngs2RghBw9PPpYZHulm:bhiocx4) ([raw file](https://github.com/starkware-libs/cairo/blob/31c812c0ec4be1c74392e2225ba5004c03e1ac06/corelib/src/test/byte_array_test.cairo#L448)):*
> ```Cairo
> 
> #[test]
> // TODO(yuval): use BYTE_ARRAY_MAGIC in these tests once constants are supported.
> ```

I don't understand what you meant

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4261)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/byte_array.cairo` line 361 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4261#-NgsnB965qlwdERZreiK:-NgsnB97BMoWmWO6b9jp:b-4w0acj) ([raw file](https://github.com/starkware-libs/cairo/blob/5774807f4d122c56e366d2cf53cf631ec19b6a39/corelib/src/byte_array.cairo#L361)):*
> ```Cairo
>         result.append((*self.pending_word_len).into());
>         result
>     }
> ```

maybe just add a `Serde` derive for the type - and than just the other suggestion.



_Code quote:_
```Cairo
    /// Serializes the ByteArray into a felt array, for panicking/printing.
    fn serialize(self: @ByteArray) -> Array<felt252> {
        let mut result = array![];
        result.append(BYTE_ARRAY_MAGIC);
        let mut serialized_data = array![];
        self.data.serialize(ref serialized_data);
        result.append_span(serialized_data.span());
        result.append(*self.pending_word);
        result.append((*self.pending_word_len).into());
        result
    }
```
___
*[`corelib/src/byte_array.cairo` line 389 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4261#-NgsnWFi0BvvvSjwYC_B:-NgsnWFi0BvvvSjwYC_C:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5774807f4d122c56e366d2cf53cf631ec19b6a39/corelib/src/byte_array.cairo#L389)):*
> ```Cairo
>     let serialized = err.serialize();
>     panic(serialized)
> }
> ```





_Suggestion:_
```Cairo
/// Panics with the given ByteArray. That is, panics with an `Array<felt252>` with
/// `BYTE_ARRAY_MAGIC`, and then the serialized given ByteArray.
#[inline(always)]
fn panic_with_byte_array(err: @ByteArray) -> never {
    let mut serialized = array![BYTE_ARRAY_MAGIC];
    err.serialize(ref serialized);
    panic(serialized)
}
```
___
*[`corelib/src/test/byte_array_test.cairo` line 448 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4261#-NgoFd9t8f1yMe38IO0j:-Ngso2do2IIeiZWL5g7h:bk9cijw) ([raw file](https://github.com/starkware-libs/cairo/blob/31c812c0ec4be1c74392e2225ba5004c03e1ac06/corelib/src/test/byte_array_test.cairo#L448)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I don't understand what you meant
</blockquote></details>

instead of using the `MAGIC` const - having the tests expects a panic with a `"Some panic"` result.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4261)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/byte_array.cairo` line 361 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4261#-NgsnB965qlwdERZreiK:-NgswK-F2Y4bWv8d7Bid:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0de82136c90247be167340d29d3ef4c26033d811/corelib/src/byte_array.cairo#L361)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe just add a `Serde` derive for the type - and than just the other suggestion.
</blockquote></details>

Done.
___
*[`corelib/src/byte_array.cairo` line 389 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4261#-NgsnWFi0BvvvSjwYC_B:-Ngsw38V-RDz6HoQDFjZ:bcunr5g) ([raw file](https://github.com/starkware-libs/cairo/blob/0de82136c90247be167340d29d3ef4c26033d811/corelib/src/byte_array.cairo#L389)):*
> ```Cairo
>     let serialized = err.serialize();
>     panic(serialized)
> }
> ```

Done, besides the snapshot. This is panicking, I don't see the benefit of not consuming the byte array.
___
*[`corelib/src/test/byte_array_test.cairo` line 448 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4261#-NgoFd9t8f1yMe38IO0j:-NgswRbM-BkK4XdvGD4v:b-6gq8dp) ([raw file](https://github.com/starkware-libs/cairo/blob/31c812c0ec4be1c74392e2225ba5004c03e1ac06/corelib/src/test/byte_array_test.cairo#L448)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

instead of using the `MAGIC` const - having the tests expects a panic with a `"Some panic"` result.
</blockquote></details>

OK, one is shorter term, second is longer term.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4261)* status: all files reviewed, 2 unresolved discussions (waiting on @bytearray)

___
*[`corelib/src/byte_array.cairo` line 389 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4261#-NgsnWFi0BvvvSjwYC_B:-NgtIhFqD12amcgBC2VF:bdwaeab) ([raw file](https://github.com/starkware-libs/cairo/blob/0de82136c90247be167340d29d3ef4c26033d811/corelib/src/byte_array.cairo#L389)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

So what's the benefit of having it as a snapshot?
Not sure about moving it - don't think it's important - it is also ok to call it, would just be less convenient than with panic!() once we have it.
</blockquote></details>

If and when the type @ByteArray would be created from "some string", with no runtime cost, it would be callable.

**Comment by yuvalsw** [comment]
*[`corelib/src/byte_array.cairo` line 389 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4261#-NgsnWFi0BvvvSjwYC_B:-NgtyC5mAURLGr2F8hzD:b-4o0x4l) ([raw file](https://github.com/starkware-libs/cairo/blob/0de82136c90247be167340d29d3ef4c26033d811/corelib/src/byte_array.cairo#L389)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

If and when the type @ByteArray would be created from "some string", with no runtime cost, it would be callable.
</blockquote></details>

I get that it can be as good as the consuming version, but what is the advantage?
(BTW, writing "@bytearray" add such a user to the review :) Turns out there is such a user...)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4261)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @bytearray)

___
*[`corelib/src/byte_array.cairo` line 389 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4261#-NgsnWFi0BvvvSjwYC_B:-Ngx_orXD7u5uENMRzdy:b-60q5xx) ([raw file](https://github.com/starkware-libs/cairo/blob/0de82136c90247be167340d29d3ef4c26033d811/corelib/src/byte_array.cairo#L389)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I get that it can be as good as the consuming version, but what is the advantage?
(BTW, writing "@bytearray" add such a user to the review :) Turns out there is such a user...)
</blockquote></details>

as it would be possible to call it from an "only const is available" context.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4261)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`corelib/src/byte_array.cairo` line 369 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4261#-NgxrWA53XwouAg3emsV:-NgxrWA53XwouAg3emsW:bbysgdo) ([raw file](https://github.com/starkware-libs/cairo/blob/ca71682ef609177c24408fb04930f449a378c707/corelib/src/byte_array.cairo#L369)):*
> ```Cairo
>     let mut serialized = array![BYTE_ARRAY_MAGIC];
>     err.serialize(ref serialized);
>     panic(serialized)
> ```

move this to `src/panics.cairo`



_Code quote:_
```Cairo
#[inline(always)]
fn panic_with_byte_array(err: @ByteArray) -> never {
    let mut serialized = array![BYTE_ARRAY_MAGIC];
    err.serialize(ref serialized);
    panic(serialized)
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4261)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/byte_array.cairo` line 369 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4261#-NgxrWA53XwouAg3emsV:-Ngxy7bMDs1KlibUJ6eP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ca71682ef609177c24408fb04930f449a378c707/corelib/src/byte_array.cairo#L369)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

move this to `src/panics.cairo`
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4261#-:-NgxyZuqD1qOGkYg88OX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
