### PR TITLE
feat(corelib): OptionTrait::unwrap_or_else

### PR DESCRIPTION
**Pull request by enitrat**
adds `unwrap_or_else` to OptionTrait

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6913#-:-OEo9C0S11u53M7-_UnM:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @enitrat)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6913#-OEo9DBHAxTBQHy78tx4:-OEo9DBHAxTBQHy78tx5:btwpq03) (no related file):*
@TomerStarkware 2nd eye.

**Review by TomerStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6913)* status: all files reviewed, 3 unresolved discussions (waiting on @enitrat)

___
*[`corelib/src/option.cairo` line 249 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6913#-OEoYK8VEirQ25LxsUJl:-OEoYK8VEirQ25LxsUJm:b-gtvdk9) ([raw file](https://github.com/starkware-libs/cairo/blob/eed2a1a31509f5199e90e6c75a8872f801cd0be6/corelib/src/option.cairo#L249)):*
> ```Cairo
>     /// assert!(Option::None.unwrap_or_else(|| 2 * k) == 20);
>     /// ```
>     fn unwrap_or_else<F, +Drop<F>, impl func: core::ops::Fn<F, ()>[Output: T], +Drop<func::Output>>(
> ```

core::ops::FnOnce



_Code quote:_
```Cairo
core::ops::Fn
```
___
*[`corelib/src/option.cairo` line 309 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6913#-OEoYR7_0TZ6DC8KrGqI:-OEoYR7_0TZ6DC8KrGqJ:b-gtvdk9) ([raw file](https://github.com/starkware-libs/cairo/blob/eed2a1a31509f5199e90e6c75a8872f801cd0be6/corelib/src/option.cairo#L309)):*
> ```Cairo
> 
>     #[inline]
>     fn unwrap_or_else<F, +Drop<F>, impl func: core::ops::Fn<F, ()>[Output: T], +Drop<func::Output>>(
> ```

core::ops::FnOnce



_Suggestion:_
```Cairo
core::ops::Fn
```

**Review by enitrat — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6913)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @orizi and @TomerStarkware)

___
*[`corelib/src/option.cairo` line 249 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6913#-OEoYK8VEirQ25LxsUJl:-OEo_heGCPre9rrvtrZf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/eed2a1a31509f5199e90e6c75a8872f801cd0be6/corelib/src/option.cairo#L249)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

core::ops::FnOnce
</blockquote></details>

Done.
___
*[`corelib/src/option.cairo` line 309 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6913#-OEoYR7_0TZ6DC8KrGqI:-OEo_iDk9O2Kh4WX9BR5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/eed2a1a31509f5199e90e6c75a8872f801cd0be6/corelib/src/option.cairo#L309)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

core::ops::FnOnce
</blockquote></details>

Done.

**Review by TomerStarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6913#-:-OEogappAnZiKT4iNPmO:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @enitrat)

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6913)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @enitrat)

**Pull request merged**
