### PR TITLE
LS unwind panics

### PR DESCRIPTION
**Pull request by spapinistarkware**
Panics now dont crash the language server.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3302)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3302)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3302#-NX5UguP2BLlqleCHYzV:-NX5UguP2BLlqleCHYzW:b-u8g94x) (no related file):*
are we sure it is totally fine to use the `-pre` version of salsa?

___

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3302)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3302#-NX5UguP2BLlqleCHYzV:-NX5UxAq2bF4SplmQY7d:buwct8v) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

are we sure it is totally fine to use the `-pre` version of salsa?
</blockquote></details>

I copied this from rust-analyzer.
Also, it actually tells u what is the cycle, and not just numbers!

___

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3302#-:-NX5Yub7A01qctskTOat:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 147 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3302#-NX5YnYI-Mryu8S88Byt:-NX5YnYJ33KsnKleQ5zp:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/62738f4ae7f2c517415d7ff6642dc31424e04a2d/crates/cairo-lang-language-server/src/lib.rs#L147)):*
> ```XML
>     }
> 
>     async fn with_db<F, T>(&self, f: F) -> LSPResult<T>
> ```

doc
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 1056 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3302#-NX5YdPyCDDfqVvLxPTb:-NX5YdPyCDDfqVvLxPTc:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/62738f4ae7f2c517415d7ff6642dc31424e04a2d/crates/cairo-lang-language-server/src/lib.rs#L1056)):*
> ```XML
> }
> 
> fn get_uri(db: &RootDatabase, file_id: FileId) -> Url {
> ```

doc

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3302)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 147 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3302#-NX5YnYI-Mryu8S88Byt:-NX8x16m3_21FDsOOQ_P:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/62738f4ae7f2c517415d7ff6642dc31424e04a2d/crates/cairo-lang-language-server/src/lib.rs#L147)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 1056 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3302#-NX5YdPyCDDfqVvLxPTb:-NX8x4c-6jBCwh0TY7Ty:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/62738f4ae7f2c517415d7ff6642dc31424e04a2d/crates/cairo-lang-language-server/src/lib.rs#L1056)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Pull request merged**
