### PR TITLE
Add lookup locations for impls

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2484)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2484** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2484" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2484?utm_source=stack-comment).

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2484)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 873 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2484#-NQZK5H7-A3x5V3SG_kZ:-NQZK5H7-A3x5V3SG_k_:bnk1npv) ([raw file](https://github.com/starkware-libs/cairo/blob/fc23996445743dcdf8268bd71ae9d45121321166/crates/cairo-lang-semantic/src/expr/inference.rs#L873)):*
> ```XML
>         self.impl_var_data[var.id].candidates = Some(candidates.clone());
>         log::info!(
>             "Impl inference candidates for {:?} at {:?}: {:?}",
> ```

this feels like something that would happen too much for `info` level.



_Code quote:_
```XML
        log::info!(
            "Impl inference candidates for {:?} at {:?}: {:?}",
            concrete_trait_id.debug(self.db.elongate()),
            lookup_context.debug(self.db.elongate()),
            candidates.iter().collect_vec().debug(self.db.elongate()),
        );
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2484)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 873 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2484#-NQZK5H7-A3x5V3SG_kZ:-NQZOwVi--n0bJ9-xzaj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fc23996445743dcdf8268bd71ae9d45121321166/crates/cairo-lang-semantic/src/expr/inference.rs#L873)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this feels like something that would happen too much for `info` level.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2484#-:-NQZP3Ni2SeQKaIHtYNj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
