### PR TITLE
Rename extension to Cairo1 to avoid conflicts with the old extension.

### PR DESCRIPTION
**Pull request by liorgold2**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1102)

### CODE REVIEW

**Review by spapinistarkware — COMMENTED** [review]
Can you update the readne to disable the ild extension?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1102#-:-NHtG-8959rzdw4MCYOg:bk3jsh4)* status: 0 of 2 files reviewed, all discussions resolved

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1102)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`vscode-cairo/package.json` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1102#-NHwrbpJ2xBo-5qD0aOL:-NHwrbpJ2xBo-5qD0aOM:byzbsu5) ([raw file](https://github.com/starkware-libs/cairo/blob/35109fd25174db91841f25c5ac489bd86d1139ea/vscode-cairo/package.json#L37)):*
> ```JSON
>                 "title": "Cairo",
>                 "properties": {
>                     "cairo1.enableLanguageServer": {
> ```

Pleae fix

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1102)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @liorgold2)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1102#-NHxEFhr9bZQtnUxwNFw:-NHxEFhsCDql0I2-Kcnx:b-qirl5r) (no related file):*
I already merged the LSP changes.

___

**Review by liorgold2 — COMMENTED** [review]
Not sure what you mean.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1102#-:-NHzbsbo5XPF41aMQQRk:bppj29x)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1102#-NHxEFhr9bZQtnUxwNFw:-NHzbor16Q3t7S0MuG78:b-896fix) (no related file):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I already merged the LSP changes.
</blockquote></details>

Done.

___
___
*[`vscode-cairo/package.json` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1102#-NHwrbpJ2xBo-5qD0aOL:-NHzafIk3mDNFdlUAioZ:b-re7pjg) ([raw file](https://github.com/starkware-libs/cairo/blob/35109fd25174db91841f25c5ac489bd86d1139ea/vscode-cairo/package.json#L37)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Pleae fix
</blockquote></details>

Re-added since this is controlled by `extension.ts`. See below.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1102#-:-NI26rjA73rO0CqUp9mx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
