### PR TITLE
LS: Add hovers for path segments

### LINKED ISSUE #6540: LS: Incorrect hovers for path segments
Path segments in import statements don't have hovers by themselves
Image

However, when they appear in e.g. function call context, they inherit hover of the called function:
Image

### PR DESCRIPTION
**Pull request by integraledelebesgue**
Closes #6540

## Changes:
* Modules appearing in paths have proper hovers containing information about their location
* Hovers look exactly the same as in Rust Analyzer

### CODE REVIEW

**Review by piotmag769 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6649)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @integraledelebesgue, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/src/lang/inspect/defs.rs` line 330 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6649#-OBewoh10RjeAaOa55sT:-OBewoh10RjeAaOa55sU:b-uuw50x) ([raw file](https://github.com/starkware-libs/cairo/blob/10198aa3bff1c42a42e5830d663199bc450c413d/crates/cairo-lang-language-server/src/lang/inspect/defs.rs#L330)):*
> ```XML
>     /// Gets the module's documentation if it's available.
>     pub fn documentation(&self) -> Option<String> {
>         // Modules cannot have docstrings at the moment.
> ```

This is not true, `get_item_documentation` should deal with it

**Review by integraledelebesgue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6649)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lang/inspect/defs.rs` line 313 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6649#-OBfRFJBB8PkMhZ99Q-N:-OBjgkos0nZT0P5IrARk:b-j31j14) ([raw file](https://github.com/starkware-libs/cairo/blob/10198aa3bff1c42a42e5830d663199bc450c413d/crates/cairo-lang-language-server/src/lang/inspect/defs.rs#L313)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

this is parent module full path. term _full path_ as used here is very misleading
</blockquote></details>

I rebuilt the path logic a bit and also changed those confusing names
___
*[`crates/cairo-lang-language-server/src/lang/inspect/defs.rs` line 330 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6649#-OBewoh10RjeAaOa55sT:-OBjgu057ZnOfRBbknNm:b-dhlf4m) ([raw file](https://github.com/starkware-libs/cairo/blob/10198aa3bff1c42a42e5830d663199bc450c413d/crates/cairo-lang-language-server/src/lang/inspect/defs.rs#L330)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

This is not true, `get_item_documentation` should deal with it
</blockquote></details>

You're right. I added a proper decumentation retrieval logic

**Review by mkaput — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6649)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

**Review by mkaput — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6649#-:-OBxdncq4lxA5m9NN9Sr:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

**Review by piotmag769 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6649#-:-OBy2qgH6TLD4EKhTwOF:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @integraledelebesgue, and @orizi)

___
*[`crates/cairo-lang-language-server/src/lang/inspect/defs.rs` line 101 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6649#-OBy4Cy61BUn79vE_I47:-OBy4Cy61BUn79vE_I48:b-4igyds) ([raw file](https://github.com/starkware-libs/cairo/blob/d38de43e6e05dc15cc1086527e8b4cd671622433/crates/cairo-lang-language-server/src/lang/inspect/defs.rs#L101)):*
> ```XML
>             }
> 
>             ResolvedItem::Generic(ResolvedGenericItem::Module(id)) => {
> ```

Out of curiosity: when do we enter each branch? What is a generic module? ;p

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6649)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

**Pull request merged**
