### PR TITLE
added associated type bounds with TypeEqual trait

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6024)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6024)* status: 1 of 6 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`corelib/src/lib.cairo` line 372 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6024#-O1uFvWz7E-1E3XSiN5z:-O1uFvWz7E-1E3XSiN6-:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/b04bf9e7e891fc288835130b7e567b891602ccba/corelib/src/lib.cairo#L372)):*
> ```Cairo
> /// Metaprogramming.
> pub mod metaprogramming;
> use metaprogramming::TypeEqual;
> ```

remove



_Code quote:_
```Cairo
use metaprogramming::TypeEqual;
```
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 314 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6024#-O1uMEk66tBtDQ5YpnZh:-O1uMEk66tBtDQ5YpnZi:biadn1g) ([raw file](https://github.com/starkware-libs/cairo/blob/b04bf9e7e891fc288835130b7e567b891602ccba/crates/cairo-lang-semantic/src/expr/inference.rs#L314)):*
> ```XML
>     ambiguous: Vec<(LocalImplVarId, Ambiguity)>,
>     /// Mapping from impl types to type variables.
>     impl_type_bounds: HashMap<ImplTypeId, TypeVar>,
> ```

possibly.



_Suggestion:_
```XML
    impl_type_bounds: HashMap<ImplTypeId, TypeId>,
```
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 500 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6024#-O1uIAHm6pVU-PCnroGZ:-O1uIAHm6pVU-PCnroG_:ba7aj7k) ([raw file](https://github.com/starkware-libs/cairo/blob/b04bf9e7e891fc288835130b7e567b891602ccba/crates/cairo-lang-semantic/src/expr/inference.rs#L500)):*
> ```XML
>             inference_id: self.inference_id,
>             id: LocalTypeVarId(self.type_vars.len()),
>             is_solve_required: true,
> ```

and heavily doc.



_Suggestion:_
```XML
            is_placeholder: true,
```
___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 407 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6024#-O1uDo9y1daPOgzgx5tY:-O1uDo9y1daPOgzgx5tZ:b-jzh8dq) ([raw file](https://github.com/starkware-libs/cairo/blob/b04bf9e7e891fc288835130b7e567b891602ccba/crates/cairo-lang-semantic/src/items/generics.rs#L407)):*
> ```XML
>         };
>         let ConcreteTraitLongId { trait_id, generic_args } = concrete_trait_id.lookup_intern(db);
>         if trait_id == get_core_trait(db, CoreTraitContext::TopLevel, "TypeEqual".into()) {
> ```

Add an additional CoreTraitContext instead of the `use metaprogramming::TypeEqual;` in the corelib.



_Code quote:_
```XML
        if trait_id == get_core_trait(db, CoreTraitContext::TopLevel, "TypeEqual".into()) {
```
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 2283 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6024#-O1uMV9n2PApXzkme065:-O1uMV9n2PApXzkme066:b-moxkaw) ([raw file](https://github.com/starkware-libs/cairo/blob/b04bf9e7e891fc288835130b7e567b891602ccba/crates/cairo-lang-semantic/src/items/tests/trait_type#L2283)):*
> ```
> fn foo() {
>          ^
> ```

Add tests for:

inference for impl depending on an impl-type with type equality.
return type depending on an impl-type with type equality.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 708 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6024#-O1ucd9BCE2OgLpmpgUa:-O1ucd9C5xhy1y3bbfFw:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b04bf9e7e891fc288835130b7e567b891602ccba/crates/cairo-lang-semantic/src/expr/inference.rs#L708)):*
> ```XML
> 
>             let ty_missing = TypeId::missing(self.db, diag);
>             for i in 0..self.type_vars.len() {
> ```





_Suggestion:_
```XML
for var in &self.type_vars {
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6024)* status: 5 of 10 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 737 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6024#-O29uJK1CBFgw2o-3I08:-O29uJK1CBFgw2o-3I09:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d874a26bf697b5f0b5318670c15965d407ad0ba9/crates/cairo-lang-semantic/src/corelib.rs#L737)):*
> ```XML
>         )),
>         ResolvedGenericItem::Trait
>     )
> ```





_Suggestion:_
```XML
    let base_module = match context {
        CoreTraitContext::TopLevel => db.core_module(),
        CoreTraitContext::Ops => core_submodule(db, "ops"),
        CoreTraitContext::Iterator => core_submodule(db, "iter"),
        CoreTraitContext::MetaProgramming => core_submodule(db, "metaprogramming"),
    };
    // This should not fail if the corelib is present.
    let item_id = db.module_item_by_name(base_module, name.clone())
        .unwrap_or_else(|_| panic!(
            "Core module `{module}` failed to compile.",
            module = base_module.full_path(db.upcast())
        ))
        .unwrap_or_else(|| panic!(
            "Core module `{module}` is missing an use item for trait `{name}`.",
            module = base_module.full_path(db.upcast()),
        ));
    match item_id {
        ModuleItemId::Trait(id) => id,
        ModuleItemId::Use(use_id) => {
            extract_matches!(
                db.use_resolved_item(use_id).unwrap_or_else(|_| panic!(
                    "Could not resolve core trait `{module}::{name}`.",
                    module = base_module.full_path(db.upcast()),
                )),
                ResolvedGenericItem::Trait   
            )
        },
        _ => panic!("Expecting only traits, or uses pointing to traits."),
    }
```
___
*[`crates/cairo-lang-semantic/src/types.rs` line 820 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6024#-O29vO4S0Tq0o9ExR6eB:-O29vO4S0Tq0o9ExR6eC:bb7r2f0) ([raw file](https://github.com/starkware-libs/cairo/blob/d874a26bf697b5f0b5318670c15965d407ad0ba9/crates/cairo-lang-semantic/src/types.rs#L820)):*
> ```XML
>             type_id.is_var_free(db) && size.is_var_free(db)
>         }
>         TypeLongId::ImplType(_) => false,
> ```

why?



_Code quote:_
```XML
        TypeLongId::ImplType(_) => false,
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6024)* status: 4 of 10 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 737 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6024#-O29uJK1CBFgw2o-3I08:-O2EQti52S7_VY-54JNL:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d874a26bf697b5f0b5318670c15965d407ad0ba9/crates/cairo-lang-semantic/src/corelib.rs#L737)):*
> ```XML
>         )),
>         ResolvedGenericItem::Trait
>     )
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/types.rs` line 820 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6024#-O29vO4S0Tq0o9ExR6eB:-O2EQF1S66GQT83kWuF0:bwba770) ([raw file](https://github.com/starkware-libs/cairo/blob/d874a26bf697b5f0b5318670c15965d407ad0ba9/crates/cairo-lang-semantic/src/types.rs#L820)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why?
</blockquote></details>

I want to rewrite ImplTypes if they have bounds

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6024)* status: 7 of 10 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 820 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6024#-O29vO4S0Tq0o9ExR6eB:-O2EiUzI2ffbaVJQC-rK:b7fpnjw) ([raw file](https://github.com/starkware-libs/cairo/blob/d874a26bf697b5f0b5318670c15965d407ad0ba9/crates/cairo-lang-semantic/src/types.rs#L820)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

I want to rewrite ImplTypes if they have bounds
</blockquote></details>

so doc it.
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 2311 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6024#-O2EizBNBS3MHWGje20o:-O2EizBNBS3MHWGje20p:b-a5w8ql) ([raw file](https://github.com/starkware-libs/cairo/blob/91ef098559af989240c687c93bae3998d104b5da/crates/cairo-lang-semantic/src/items/tests/trait_type#L2311)):*
> ```
> //! > ==========================================================================
> 
> //! > Associated type bounds2.
> ```

find better test name.
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 2428 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6024#-O2EjUzgDKHSuS5AEsUC:-O2EjUzgDKHSuS5AEsUD:bjjwh37) ([raw file](https://github.com/starkware-libs/cairo/blob/91ef098559af989240c687c93bae3998d104b5da/crates/cairo-lang-semantic/src/items/tests/trait_type#L2428)):*
> ```
> //! > ==========================================================================
> 
> //! > Associated type bounds return type not fully bounded. 
> ```

i don't fully understand what is tested.
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 2488 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6024#-O2Ej_F-A8NtZ5CVS2na:-O2Ej_F-A8NtZ5CVS2nb:b-b10cxu) ([raw file](https://github.com/starkware-libs/cairo/blob/91ef098559af989240c687c93bae3998d104b5da/crates/cairo-lang-semantic/src/items/tests/trait_type#L2488)):*
> ```
> 
> //! > module_code
> impl I of core::metaprogramming::TypeEqual<u32, felt252>;
> ```

this is the only part required for the diagnostic - remove everything else.



_Code quote:_
```
impl I of core::metaprogramming::TypeEqual<u32, felt252>;
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6024)* status: 8 of 10 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6024)* status: 6 of 10 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 820 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6024#-O29vO4S0Tq0o9ExR6eB:-O2OJyeR9um6pEIX-WSc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d874a26bf697b5f0b5318670c15965d407ad0ba9/crates/cairo-lang-semantic/src/types.rs#L820)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

so doc it.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 2311 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6024#-O2EizBNBS3MHWGje20o:-O2OW_j10e4kJugMSrTR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/91ef098559af989240c687c93bae3998d104b5da/crates/cairo-lang-semantic/src/items/tests/trait_type#L2311)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

find better test name.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 2428 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6024#-O2EjUzgDKHSuS5AEsUC:-O2OKhP9BbzaJlxFPm0T:bm8tryh) ([raw file](https://github.com/starkware-libs/cairo/blob/91ef098559af989240c687c93bae3998d104b5da/crates/cairo-lang-semantic/src/items/tests/trait_type#L2428)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i don't fully understand what is tested.
</blockquote></details>

The return type is an associated type with bounds which do not bound it to a concrete type
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 2488 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6024#-O2Ej_F-A8NtZ5CVS2na:-O2OWaR70QmxaYozClcm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/91ef098559af989240c687c93bae3998d104b5da/crates/cairo-lang-semantic/src/items/tests/trait_type#L2488)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is the only part required for the diagnostic - remove everything else.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 10 files at r2, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6024)* status: 9 of 10 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 820 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6024#-O29vO4S0Tq0o9ExR6eB:-O2OX03o5uBRBxMZCq44:bc5wc00) ([raw file](https://github.com/starkware-libs/cairo/blob/d874a26bf697b5f0b5318670c15965d407ad0ba9/crates/cairo-lang-semantic/src/types.rs#L820)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

also consider adding a TODO - as this can definitely can cause performance issues. 
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 2428 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6024#-O2EjUzgDKHSuS5AEsUC:-O2OXwZQ18FVzwqfl3GU:b3xi1xk) ([raw file](https://github.com/starkware-libs/cairo/blob/91ef098559af989240c687c93bae3998d104b5da/crates/cairo-lang-semantic/src/items/tests/trait_type#L2428)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

The return type is an associated type with bounds which do not bound it to a concrete type
</blockquote></details>

this is still not clear at all.
additionally actually change the name of the test to help me understand.
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 2311 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6024#-O2OXbuuE77j35JMhsKs:-O2OXbuuE77j35JMhsKt:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a6ab4941ab9132ebc5c2cbfc07227ce13b7cae04/crates/cairo-lang-semantic/src/items/tests/trait_type#L2311)):*
> ```
> //! > ==========================================================================
> 
> //! > Associated type bounds transative.
> ```





_Suggestion:_
```
//! > Associated type bounds transitive.
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6024)* status: 9 of 10 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 820 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6024#-O29vO4S0Tq0o9ExR6eB:-O2O_9lJ7ztitIJ_RUEc:bg501g) ([raw file](https://github.com/starkware-libs/cairo/blob/d874a26bf697b5f0b5318670c15965d407ad0ba9/crates/cairo-lang-semantic/src/types.rs#L820)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

also consider adding a TODO - as this can definitely can cause performance issues.
</blockquote></details>

can we use default rewrite for typeid, and then check var_free on typelongid, and add special check for impltype?
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 2428 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6024#-O2EjUzgDKHSuS5AEsUC:-O2OajA-1wuewX0vwOWY:b-5hsjcu) ([raw file](https://github.com/starkware-libs/cairo/blob/91ef098559af989240c687c93bae3998d104b5da/crates/cairo-lang-semantic/src/items/tests/trait_type#L2428)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is still not clear at all.
additionally actually change the name of the test to help me understand.
</blockquote></details>

its for when associated types are only bounded to other associated types and not to other types
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 2311 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6024#-O2OXbuuE77j35JMhsKs:-O2Oau0VCSWJIpqsg12T:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a6ab4941ab9132ebc5c2cbfc07227ce13b7cae04/crates/cairo-lang-semantic/src/items/tests/trait_type#L2311)):*
> ```
> //! > ==========================================================================
> 
> //! > Associated type bounds transative.
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6024#-:-O2ObhHj0HP6dvssI99j:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by mkaput — APPROVED** [review]
> Reviewed 7 of 10 files at r2, 1 of 1 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6024)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 2435 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6024#-O2ZfohS6dq5dZkk_0md:-O2ZfohS6dq5dZkk_0me:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f3b56c122903aef821ac5aca4d3d153f73341d12/crates/cairo-lang-semantic/src/items/tests/trait_type#L2435)):*
> ```
>     impl I1: MyTrait, impl I2: MyTrait, +core::metaprogramming::TypeEqual<I1::ty, I2::ty>
> >() -> I1::ty {
>     I1::foo()
> ```





_Suggestion:_
```
I2::foo()
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 5 of 6 files at r1, 7 of 10 files at r2, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6024)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/types.rs` line 821 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6024#-O2ZigIP0EtiBS5oyRwN:-O2ZigIP0EtiBS5oyRwO:b-kqoser) ([raw file](https://github.com/starkware-libs/cairo/blob/f3b56c122903aef821ac5aca4d3d153f73341d12/crates/cairo-lang-semantic/src/types.rs#L821)):*
> ```XML
>         }
>         // ImplType need to be rewritten if they have bounds constraints.
>         TypeLongId::ImplType(_) => false,
> ```

How do you know it has bounds constraints?



_Code quote:_
```XML
        // ImplType need to be rewritten if they have bounds constraints.
        TypeLongId::ImplType(_) => false,
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/types.rs` line 820 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6024#-O2ZmRkQ9xq4aB_TLBr2:-O2ZmRkR6KssOtBqgvta:bivhpxs) ([raw file](https://github.com/starkware-libs/cairo/blob/f3b56c122903aef821ac5aca4d3d153f73341d12/crates/cairo-lang-semantic/src/types.rs#L820)):*
> ```XML
>             type_id.is_var_free(db) && size.is_var_free(db)
>         }
>         // ImplType need to be rewritten if they have bounds constraints.
> ```

Maybe we need to rename the function to "priv_type_might_need_rewrite", or at least added a todo to consider it?



_Suggestion:_
```XML
  // a var free ImplType needs to be rewritten if has impl bounds constraints.
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6024)* status: 8 of 11 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware, @mkaput, and @orizi)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 820 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6024#-O2ZmRkQ9xq4aB_TLBr2:-O2e8gBdD_lQyZMhbBnI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f3b56c122903aef821ac5aca4d3d153f73341d12/crates/cairo-lang-semantic/src/types.rs#L820)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Maybe we need to rename the function to "priv_type_might_need_rewrite", or at least added a todo to consider it?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 2435 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6024#-O2ZfohS6dq5dZkk_0md:-O2ZtIvN0CBm2cbY3RSY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f3b56c122903aef821ac5aca4d3d153f73341d12/crates/cairo-lang-semantic/src/items/tests/trait_type#L2435)):*
> ```
>     impl I1: MyTrait, impl I2: MyTrait, +core::metaprogramming::TypeEqual<I1::ty, I2::ty>
> >() -> I1::ty {
>     I1::foo()
> ```

Done.

**Review by mkaput — APPROVED** [review]
> Reviewed 2 of 3 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6024)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 890 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6024#-O2wvnejBVuPo6pNX9wX:-O2wvnejBVuPo6pNX9wY:bhzkhcg) ([raw file](https://github.com/starkware-libs/cairo/blob/63905684114ee2cb9d6e6ec88863eb062c2e7cff/crates/cairo-lang-semantic/src/expr/compute.rs#L890)):*
> ```XML
>             (generic_args[0], generic_args[1])
>         else {
>             unreachable!("TypeEqual should have 2 arguments");
> ```

Can you add a test for this?



_Code quote:_
```XML
unreachable!("TypeEqual should have 2 arguments");
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 3 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6024)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6024)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 890 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6024#-O2wvnejBVuPo6pNX9wX:-O2xSLjs7lsUKvCy8R_z:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/63905684114ee2cb9d6e6ec88863eb062c2e7cff/crates/cairo-lang-semantic/src/expr/compute.rs#L890)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Can you add a test for this?
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6024#-:-O2xXvpE1vxNZ74VFjXj:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by mkaput — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6024)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6024)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 820 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6024#-O29vO4S0Tq0o9ExR6eB:-O366pyfB_gZAndm2TEs:b92qdh2) ([raw file](https://github.com/starkware-libs/cairo/blob/d874a26bf697b5f0b5318670c15965d407ad0ba9/crates/cairo-lang-semantic/src/types.rs#L820)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

can we use default rewrite for typeid, and then check var_free on typelongid, and add special check for impltype?
</blockquote></details>

maybe - but let us check what actually happens first, but in any case, this suggestion won't solve this - as the impl-type might be an inner type - so the outermost type might still depend on it and won't be 'var-free'.

**Pull request merged**
