### PR TITLE
Add OptimizationStrategy.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5124)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5124)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/strategy.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5124#-NrFGnpT2J7Y_Qi6lUfC:-NrFGnpT2J7Y_Qi6lUfD:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/9c85f42cd8990efc82ed8927555bfcf6ecc148de/crates/cairo-lang-lowering/src/optimizations/strategy.rs#L20)):*
> ```XML
> 
> #[derive(Clone, Debug, Eq, Hash, PartialEq)]
> pub enum OptimizationPhase {
> ```

doc
___
*[`crates/cairo-lang-lowering/src/optimizations/strategy.rs` line 44 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5124#-NrFGoYS1Frq_3K6xWqE:-NrFGoYS1Frq_3K6xWqF:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/9c85f42cd8990efc82ed8927555bfcf6ecc148de/crates/cairo-lang-lowering/src/optimizations/strategy.rs#L44)):*
> ```XML
> 
> #[derive(Clone, Debug, Eq, Hash, PartialEq)]
> pub struct OptimizationStrategy(pub Vec<OptimizationPhase>);
> ```

doc
___
*[`crates/cairo-lang-lowering/src/optimizations/strategy.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5124#-NrFGqr34n1urkvONGr-:-NrFGqr34n1urkvONGr0:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/9c85f42cd8990efc82ed8927555bfcf6ecc148de/crates/cairo-lang-lowering/src/optimizations/strategy.rs#L47)):*
> ```XML
> 
> impl OptimizationStrategyId {
>     pub fn default_strategy(db: &dyn LoweringGroup) -> Self {
> ```

doc
___
*[`crates/cairo-lang-lowering/src/optimizations/strategy.rs` line 71 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5124#-NrFGr__EeSKZnMW_4hB:-NrFGr__EeSKZnMW_4hC:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/9c85f42cd8990efc82ed8927555bfcf6ecc148de/crates/cairo-lang-lowering/src/optimizations/strategy.rs#L71)):*
> ```XML
>     }
> 
>     pub fn apply_strategy(
> ```

doc

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5124)* status: 1 of 3 files reviewed, 6 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 379 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5124#-NrFCKj1B_UGdwsleMEx:-NrFLUhzBQJyK4PUjB8x:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/769fcd054b437d1bf615bef723c59b8ab22f0fd9/crates/cairo-lang-lowering/src/db.rs#L379)):*
> ```XML
> 
> // Applies optimizations to the post_panic lowering.
> fn concrete_function_with_body_lowered(
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/optimizations/strategy.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5124#-NrFCl5s9PQa6BFqZHL1:-NrFKj80D4hJU9Pu1KL-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/769fcd054b437d1bf615bef723c59b8ab22f0fd9/crates/cairo-lang-lowering/src/optimizations/strategy.rs#L38)):*
> ```XML
> define_short_id!(
>     OptimizationStrategy,
>     Vec<OptimizationPhase>,
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/optimizations/strategy.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5124#-NrFGnpT2J7Y_Qi6lUfC:-NrFJpeW7i4vQ_IOvC4B:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9c85f42cd8990efc82ed8927555bfcf6ecc148de/crates/cairo-lang-lowering/src/optimizations/strategy.rs#L20)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/optimizations/strategy.rs` line 44 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5124#-NrFGoYS1Frq_3K6xWqE:-NrFKjOE8sKDp4ztiz9b:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9c85f42cd8990efc82ed8927555bfcf6ecc148de/crates/cairo-lang-lowering/src/optimizations/strategy.rs#L44)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/optimizations/strategy.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5124#-NrFGqr34n1urkvONGr-:-NrFKjbt9ov0Hcy8Sqns:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9c85f42cd8990efc82ed8927555bfcf6ecc148de/crates/cairo-lang-lowering/src/optimizations/strategy.rs#L47)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/optimizations/strategy.rs` line 71 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5124#-NrFGr__EeSKZnMW_4hB:-NrFKk7P29j1V0nNtjEn:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9c85f42cd8990efc82ed8927555bfcf6ecc148de/crates/cairo-lang-lowering/src/optimizations/strategy.rs#L71)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5124)* status: 5 of 10 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/strategy.rs` line 76 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5124#-NrFeiiB9KMmyVUWzdhI:-NrFeiiB9KMmyVUWzdhJ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7112fbd5e49e4739b4e1d4a6ef5b2d43933733f7/crates/cairo-lang-lowering/src/optimizations/strategy.rs#L76)):*
> ```XML
> 
> impl OptimizationStrategyId {
>     // The default strategy used in the lowering.
> ```





_Suggestion:_
```XML
    /// The default strategy used in the lowering.
```

**Review by orizi — COMMENTED** [review]
> Reviewed 5 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5124)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5124)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/strategy.rs` line 76 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5124#-NrFeiiB9KMmyVUWzdhI:-NrG1YTHDaQa1VCg1pgO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7112fbd5e49e4739b4e1d4a6ef5b2d43933733f7/crates/cairo-lang-lowering/src/optimizations/strategy.rs#L76)):*
> ```XML
> 
> impl OptimizationStrategyId {
>     // The default strategy used in the lowering.
> ```

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5124)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5124#-:-NrG1tbl-8C6CqdYKY_M:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
