### PR TITLE
Made plugin only dependent on the syntactic level.

### PR DESCRIPTION
**Pull request by orizi**
Pathces are always saved and diagnostics mappings are performed in
diagnostics.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3790)

### CODE REVIEW

**Review by mkaput — APPROVED** [review]
> Reviewed 42 of 42 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3790)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3790#-NagWSPr-PFhEiOGbBAi:-NagWSPr-PFhEiOGbBAj:b-o6jf2o) (no related file):*
FYI This is a breaking change for Scarb and transitively for Dojo, where we use SemanticPlugin in our types; but it's okay for us to patch I believe

___
___
*[`crates/cairo-lang-compiler/src/db.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3790#-NagVT8f1espye2Sesje:-NagVT8f1espye2Sesjf:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8f149d3a59df80fc13bf42eb919cd3ec896f86ad/crates/cairo-lang-compiler/src/db.rs#L88)):*
> ```XML
>     }
> 
>     pub fn with_semantic_plugin(&mut self, plugin: Arc<dyn MacroPlugin>) -> &mut Self {
> ```





_Suggestion:_
```XML
with_macro_plugin
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3790)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3790#-NagWSPr-PFhEiOGbBAi:-NahDpai9MBNGY3qwGE-:b-c5l6tv) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

FYI This is a breaking change for Scarb and transitively for Dojo, where we use SemanticPlugin in our types; but it's okay for us to patch I believe
</blockquote></details>

you use it but don't need it - it will just remove some dead code.

___

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3790)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3790#-NagWSPr-PFhEiOGbBAi:-NakvMSl4Xdxu7OUj7wA:b5uupu2) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you use it but don't need it - it will just remove some dead code.
</blockquote></details>

Yes I know this, that's why I'm not protesting :-)

___

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 41 of 42 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3790)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3790#-NauOXbm7DTEWjbXhfjy:-NauOXbm7DTEWjbXhfjz:b-ktfe8) (no related file):*
Please make all aux_data Option

___
___
*[`crates/cairo-lang-filesystem/src/lib.rs` line 8 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3790#-NauGiT41qNPduZ06IjH:-NauGiT41qNPduZ06IjI:b-n4nmip) ([raw file](https://github.com/starkware-libs/cairo/blob/3ef7e6d538935c972b09f8ba8c8bf7e470be87fc/crates/cairo-lang-filesystem/src/lib.rs#L8)):*
> ```XML
> pub mod flag;
> pub mod ids;
> pub mod patches;
> ```

Can u move this to defs?

**Review by mkaput — APPROVED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3790)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3790)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3790#-NauOXbm7DTEWjbXhfjy:-NavoIaa4El9GmxOQNaQ:b-896fix) (no related file):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Please make all aux_data Option
</blockquote></details>

Done.

___
___
*[`crates/cairo-lang-filesystem/src/lib.rs` line 8 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3790#-NauGiT41qNPduZ06IjH:-NavoJJu1S8pDG-bsE6r:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3ef7e6d538935c972b09f8ba8c8bf7e470be87fc/crates/cairo-lang-filesystem/src/lib.rs#L8)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Can u move this to defs?
</blockquote></details>

Done.

**Review by mkaput — APPROVED** [review]
> Reviewed 17 of 17 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3790)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 17 of 17 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3790#-:-NbJvf7O2cFsaK-G8kJ1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3790)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 30 of 30 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3790)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
