### PR TITLE
Anonymous generic impl param

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2880)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2880** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2880" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2880?utm_source=stack-comment).

**Review by mkaput — COMMENTED** [review]
Kinda not sure what to think of this given this trick with `<>`

- on the one hand, I would rather expect syntax like `impl Clone<T>` (without `:` part)
- on the other hand, I understand the purpose is to slim down the amount of keystrokes as much as possible

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2880#-:-NTOhwf63JXNnv7SWW2G:b-h64un0)* status: 0 of 40 files reviewed, all discussions resolved (waiting on @orizi)

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2880)* status: 0 of 40 files reviewed, all discussions resolved (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2880#-NTOi27lCdYqXHO-MgZ-:-NTOi27m7LrJ8TfDq-7R:b-1iqlwv) (no related file):*
Discussed privately with @spapinistarkware:

Me: 
> this means that the path must always be generic isn’t it?
> isn’t this locking us down from supporting impls that are not generic in this context?

Shahar:
> You can always use `MyTrait<>`

Me:
> 🤯

___

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 19 of 40 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2880)* status: 19 of 40 files reviewed, 2 unresolved discussions (waiting on @mkaput and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/test_data/generics` line 102 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2880#-NTP-LgH4QGogzwXPDZ8:-NTP-LgH4QGogzwXPDZ9:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/cb7f2cac5a78b94fc2c0e1e890e436835c2c0961/crates/cairo-lang-lowering/src/test_data/generics#L102)):*
> ```
> 
> //! > module_code
> fn bar<MyTrait>(){Imp::foo()}
> ```





_Suggestion:_
```
//! > module_code
fn bar<MyTrait<>>(){Imp::foo()}
```
___
*[`crates/cairo-lang-parser/src/parser_test_data/reserved_identifier` line 294 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2880#-NTP-gH-5Dd1qMXFGnn1:-NTP-gH-5Dd1qMXFGnn2:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/cb7f2cac5a78b94fc2c0e1e890e436835c2c0961/crates/cairo-lang-parser/src/parser_test_data/reserved_identifier#L294)):*
> ```
> //! > expected_diagnostics
> error: Missing token TerminalGT.
>  --> dummy_file.cairo:1:10
> ```

?



_Code quote:_
```
error: Missing token TerminalGT.
 --> dummy_file.cairo:1:10
struct A<mod> {}
         ^
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2880)* status: 0 of 51 files reviewed, 2 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-lowering/src/test_data/generics` line 102 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2880#-NTP-LgH4QGogzwXPDZ8:-NbjD_ArEozX_rEy2nKK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cb7f2cac5a78b94fc2c0e1e890e436835c2c0961/crates/cairo-lang-lowering/src/test_data/generics#L102)):*
> ```
> 
> //! > module_code
> fn bar<MyTrait>(){Imp::foo()}
> ```

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/reserved_identifier` line 294 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2880#-NTP-gH-5Dd1qMXFGnn1:-NbjDaHk6g4SKFHYPh_7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cb7f2cac5a78b94fc2c0e1e890e436835c2c0961/crates/cairo-lang-parser/src/parser_test_data/reserved_identifier#L294)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2880)* status: 0 of 52 files reviewed, 4 unresolved discussions (waiting on @mkaput, @orizi, and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2880#-NbjJqDE8l3FAu0p0R4G:-NbjJqDE8l3FAu0p0R4H:bpgr9v) (no related file):*
Please add a test case with an impl generic param of a trait without generic args.
I only found one such example in the code (in bug_samples/issue2995.cairo), but please add a dedicated test for it (1 test for named, one test for unnamed).

___
___
*[`crates/cairo-lang-lowering/src/test_data/generics` line 106 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2880#-NbjIdVGB6AxaFCIGK3e:-NbjIdVGB6AxaFCIGK3f:ba7hxdn) ([raw file](https://github.com/starkware-libs/cairo/blob/d7ec79aabe8152ef11ec309f8a7fbc58b5de273a/crates/cairo-lang-lowering/src/test_data/generics#L106)):*
> ```
> 
> //! > module_code
> fn bar<impl Imp: MyTrait>(){Imp::foo()}
> ```

Remove "Imp" here and please add another test for a named impl.



_Suggestion:_
```
ar<impl MyTrait>(){Imp
```

**Review by orizi — COMMENTED** [review]
> Reviewed 48 of 51 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2880)* status: all files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2880#-:-NbjLnFlAfhDn6HBvKi4:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2880)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi and @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2880#-NbjJqDE8l3FAu0p0R4G:-NbjNSgp8Y3JBmN5Jx_H:bg1glct) (no related file):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Please add a test case with an impl generic param of a trait without generic args.
I only found one such example in the code (in bug_samples/issue2995.cairo), but please add a dedicated test for it (1 test for named, one test for unnamed).
</blockquote></details>

I added near the generic file you commented on above, is that ok?

___
___
*[`crates/cairo-lang-lowering/src/test_data/generics` line 106 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2880#-NbjIdVGB6AxaFCIGK3e:-NbjNJHR9583KTpYcUH7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d7ec79aabe8152ef11ec309f8a7fbc58b5de273a/crates/cairo-lang-lowering/src/test_data/generics#L106)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Remove "Imp" here and please add another test for a named impl.
</blockquote></details>

Done.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2880)* status: 50 of 52 files reviewed, 5 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/test_data/generics` line 106 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2880#-NbjOQMu2kpF7WGCyi4q:-NbjOQMvBi-jAVP526Y6:bx58wul) ([raw file](https://github.com/starkware-libs/cairo/blob/3b1f39303e781a3cef2979f9713405d091cd85e3/crates/cairo-lang-lowering/src/test_data/generics#L106)):*
> ```
> 
> //! > module_code
> fn bar<impl MyTrait>(){MyTrait::foo()}
> ```

This makes me reconsider it. "impl MyTrait" looks weird.
I want to raise again the option to call it "impls".
Though as Gil pointed out (we discussed it f2f now), this means we'll still have "impl" in the named variant. We can change the named variant to also be "X impls Y", or "X: impls Y", but then the named variant again doesn't look like the definition (although it might be OK if it's completely different (as opposed to very-similar-but-different previously)).
One more thing to check when considering this: how would each option look like with nested generics in the impl generic params themselves.

WDYT?



_Code quote:_
```
impl MyTrait
```
___
*[`crates/cairo-lang-lowering/src/test_data/generics` line 111 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2880#-NbjPwrIDQ6BigG4YEOX:-NbjPwrIDQ6BigG4YEOY:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/3b1f39303e781a3cef2979f9713405d091cd85e3/crates/cairo-lang-lowering/src/test_data/generics#L111)):*
> ```
> }
> impl MyImpl of MyTrait {
>   fn foo(){}
> ```





_Suggestion:_
```
fn foo() {}
```
___
*[`crates/cairo-lang-lowering/src/test_data/generics` line 148 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2880#-NbjQ7uM4zJMGH0nXBlk:-NbjQ7uM4zJMGH0nXBll:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/3b1f39303e781a3cef2979f9713405d091cd85e3/crates/cairo-lang-lowering/src/test_data/generics#L148)):*
> ```
> impl MyImpl of MyTrait {
>   fn foo(){}
> }
> ```





_Suggestion:_
```
fn bar<impl Imp: MyTrait>() { Imp::foo() }
trait MyTrait {
  fn foo();
}
impl MyImpl of MyTrait {
  fn foo() {}
}
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2880)* status: 51 of 52 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2880)* status: 51 of 52 files reviewed, 3 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/test_data/generics` line 106 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2880#-NbjOQMu2kpF7WGCyi4q:-Nbn1Bu60QsS5dCAB22j:bcyh2vi) ([raw file](https://github.com/starkware-libs/cairo/blob/3b1f39303e781a3cef2979f9713405d091cd85e3/crates/cairo-lang-lowering/src/test_data/generics#L106)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

This makes me reconsider it. "impl MyTrait" looks weird.
I want to raise again the option to call it "impls".
Though as Gil pointed out (we discussed it f2f now), this means we'll still have "impl" in the named variant. We can change the named variant to also be "X impls Y", or "X: impls Y", but then the named variant again doesn't look like the definition (although it might be OK if it's completely different (as opposed to very-similar-but-different previously)).
One more thing to check when considering this: how would each option look like with nested generics in the impl generic params themselves.

WDYT?
</blockquote></details>

You wil NEVER get your "of" -> ":" PR merged, do you realize this???

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2880)* status: 51 of 52 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2880#-Nbx-rgGDsv9f0YZu579:-Nbx-rgHASOnNDqDO6BO:bjzvm5b) (no related file):*
Change to the newly discussed short `+` syntax.

___

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2880)* status: 51 of 52 files reviewed, 2 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2880#-Nbx-rgGDsv9f0YZu579:-NbxwoxC5OC8XqC_75m5:b-ny6rl5) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Change to the newly discussed short `+` syntax.
</blockquote></details>

(moving out of my attention set until this is changed)

___

**Review by mkaput — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2880)* status: 51 of 52 files reviewed, 2 unresolved discussions (waiting on @orizi and @yuvalsw)

**Pull request closed without merging**
