### PR TITLE
Added PartialEq impl for Array<T>

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3812)

### CODE REVIEW

**Comment by yuvalsw** [comment]
change target branch

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3812)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/array.cairo` line 210 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3812#-NalYH38033fFXUfHsUj:-NalYH38033fFXUfHsUk:bt5bz4i) ([raw file](https://github.com/starkware-libs/cairo/blob/7d489d9ec88240aaa99367a3d65b1765ea9e4461/corelib/src/array.cairo#L210)):*
> ```Cairo
> 
> // TODO(yg): add tests.
> impl ArrayPartialEq<T, impl PartialEqImpl: PartialEq<T>> of PartialEq<Array<T>> {
> ```

implement for span instead - and call it from here.



_Code quote:_
```Cairo
impl ArrayPartialEq<T, impl PartialEqImpl: PartialEq<T>> of PartialEq<Array<T>> {
```
___
*[`corelib/src/array.cairo` line 236 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3812#-NalY3by9g3s9x2_qxJb:-NalY3by9g3s9x2_qxJc:bbakjl2) ([raw file](https://github.com/starkware-libs/cairo/blob/7d489d9ec88240aaa99367a3d65b1765ea9e4461/corelib/src/array.cairo#L236)):*
> ```Cairo
>                     break rhs_v.is_none();
>                 },
>             };
> ```

since you already checked len.



_Suggestion:_
```Cairo
            match lhs_span.pop_front() {
                Option::Some(lhs_v) => {
                    if lhs_v != rhs_span.pop_front().unwrap() {
                        break false;
                    }
                },
                Option::None => { break true; },
            };
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3812)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/array.cairo` line 210 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3812#-NalYH38033fFXUfHsUj:-NalqQvC-kHttc2KRW5B:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/21add5c8e653c82f55b6a1b452f4c4bc388fce5b/corelib/src/array.cairo#L210)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

implement for span instead - and call it from here.
</blockquote></details>

Done.
___
*[`corelib/src/array.cairo` line 236 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3812#-NalY3by9g3s9x2_qxJb:-NalpI9z0_AN8XwYLA4h:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/21add5c8e653c82f55b6a1b452f4c4bc388fce5b/corelib/src/array.cairo#L236)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

since you already checked len.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3812#-:-Nalr81Q-CAA2llNfSHA:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
