### PR TITLE
feat: replace the cairo-vm felt type by the starknet-types-core one

### PR DESCRIPTION
**Pull request by tdelabro**
In the effort to homogenize the `Felt` type used across the Starknet rust ecosystem, this PR replaces the uses of the `cairo_felt::Felt252` type with the `starknet-types-cores::felt::Felt` type.

It is already used in the cairo-vm, and after this PR is merged, it will be in starknet-api and blockifier.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5150)

### CODE REVIEW

**Comment by tdelabro** [comment]
@orizi Do you think you can review this?

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5150)* status: 0 of 37 files reviewed, 1 unresolved discussion (waiting on @tdelabro)

___
*[`Cargo.toml` line 88 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5150#-NraFb2U1iXAejkC_J3P:-NraFb2U1iXAejkC_J3Q:b-e0nj4j) ([raw file](https://github.com/starkware-libs/cairo/blob/9e234193ccee1f93efa1aef3fa9a2ebcc181a1af/Cargo.toml#L88)):*
> ```TOML
> assert_matches = "1.5"
> bimap = "0.6.3"
> cairo-vm = "1.0.0-rc1"
> ```

@dorimedini-starkware is this going to be an issue?



_Code quote:_
```TOML
cairo-vm = "1.0.0-rc1"
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5150)* status: 0 of 37 files reviewed, 3 unresolved discussions (waiting on @tdelabro)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5150#-NraFm4j-GCR-00Q58ST:-NraFm4j-GCR-00Q58SU:bwt9g99) ([raw file](https://github.com/starkware-libs/cairo/blob/9e234193ccee1f93efa1aef3fa9a2ebcc181a1af/crates/cairo-lang-runner/src/lib.rs#L45)):*
> ```XML
> use num_traits::ToPrimitive;
> use profiling::{user_function_idx_by_sierra_statement_idx, ProfilingInfo};
> use starknet_types_core::felt::Felt;
> ```

and revert the other related changes.



_Suggestion:_
```XML
use starknet_types_core::felt::Felt as Felt252;
```
___
*[`crates/cairo-lang-runner/src/casm_run/contract_address.rs` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5150#-NraG5D0DWO3P50pAiuT:-NraG5D0DWO3P50pAiuU:bqbmy0v) ([raw file](https://github.com/starkware-libs/cairo/blob/9e234193ccee1f93efa1aef3fa9a2ebcc181a1af/crates/cairo-lang-runner/src/casm_run/contract_address.rs#L2)):*
> ```XML
> use starknet_crypto::{pedersen_hash, FieldElement};
> use starknet_types_core::felt::Felt;
> ```

and everywhere else



_Suggestion:_
```XML
use starknet_types_core::felt::Felt as Felt252;
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 13 of 37 files at r1, 24 of 24 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5150)* status: all files reviewed, 5 unresolved discussions (waiting on @tdelabro)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 341 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5150#-NraOiWZ7brbaroiwP-w:-NraOiW_3yUwaU1s6Px8:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8e5355cb1fbcb744db6dc86496b8d2f0fa36111e/crates/cairo-lang-runner/src/lib.rs#L341)):*
> ```XML
>             // Safe to unwrap because:
>             // - both Relocatable values exist in the same segment
>             // - `real_pc_0` is by construction always greater than any step pc
> ```





_Suggestion:_
```XML
            // Safe to unwrap because:
            // - both Relocatable values exist in the same segment.
            // - `real_pc_0` is by construction always greater than any step pc.
```
___
*[`crates/cairo-lang-runner/src/short_string.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5150#-NraP-jc-EOxEhKFUwyX:-NraP-jc-EOxEhKFUwyY:b-hhbm3c) ([raw file](https://github.com/starkware-libs/cairo/blob/8e5355cb1fbcb744db6dc86496b8d2f0fa36111e/crates/cairo-lang-runner/src/short_string.rs#L36)):*
> ```XML
> 
>     let mut as_string = "".to_string();
>     for (i, byte) in bytes.into_iter().skip_while(|b| *b == 0).enumerate() {
> ```

doesn't this significantly changes the meaning of the code?
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 632 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5150#-NraPnZT39zz_95kxGX7:-NraPnZUAETkD-dM_Br0:bn6hrfj) ([raw file](https://github.com/starkware-libs/cairo/blob/8e5355cb1fbcb744db6dc86496b8d2f0fa36111e/crates/cairo-lang-runner/src/casm_run/mod.rs#L632)):*
> ```XML
> 
>         let selector = system_buffer.next_felt252()?.to_bytes_be();
>         let first_selector_non_zero_byte =
> ```

did the side of the padding switch for some reason?
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1253 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5150#-NraRIn6-Dc8EFu1vmCl:-NraRIn6-Dc8EFu1vmCm:b-7e6a9y) ([raw file](https://github.com/starkware-libs/cairo/blob/8e5355cb1fbcb744db6dc86496b8d2f0fa36111e/crates/cairo-lang-runner/src/casm_run/mod.rs#L1253)):*
> ```XML
>     }
>     // 2 ** 64 in mont representation
>     const TWO_64_RAW: [u64; 4] = [0x483ff, 0xffffffffffffffff, 0xffffffffffffffe0, 0x4400];
> ```

can this we generated some other way? from 2^64 directly possibly?



_Code quote:_
```XML
const TWO_64_RAW: [u64; 4] = [0x483ff, 0xffffffffffffffff, 0xffffffffffffffe0, 0x4400];
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5150)* status: 36 of 37 files reviewed, 3 unresolved discussions (waiting on @tdelabro)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 632 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5150#-NraPnZT39zz_95kxGX7:-Nriep7G84UcDOBo7N-J:b-72p82z) ([raw file](https://github.com/starkware-libs/cairo/blob/8e5355cb1fbcb744db6dc86496b8d2f0fa36111e/crates/cairo-lang-runner/src/casm_run/mod.rs#L632)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

did the side of the padding switch for some reason?
</blockquote></details>

this one was much nicer the new by hand padding.
please just doc the padding.
and explain what changed to me.

**Review by tdelabro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5150)* status: 36 of 37 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`Cargo.toml` line 88 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5150#-NraFb2U1iXAejkC_J3P:-Nrkuc1f8u8xvbE_5TI0:bmkb7es) ([raw file](https://github.com/starkware-libs/cairo/blob/9e234193ccee1f93efa1aef3fa9a2ebcc181a1af/Cargo.toml#L88)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

@tdelabro - note this means this PR cannot be merged until at the very least we merged 2.6.0 into main - which is gonna be a bit of a while (as we are waiting for starknet release).
</blockquote></details>

How much of a while are we talking about?
Is it up to LC? As soon as they release "1.0.0" you will follow?
___
*[`crates/cairo-lang-runner/src/lib.rs` line 341 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5150#-NraOiWZ7brbaroiwP-w:-Nra_sq61ltCQp8i9-GQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8e5355cb1fbcb744db6dc86496b8d2f0fa36111e/crates/cairo-lang-runner/src/lib.rs#L341)):*
> ```XML
>             // Safe to unwrap because:
>             // - both Relocatable values exist in the same segment
>             // - `real_pc_0` is by construction always greater than any step pc
> ```

Done.
___
*[`crates/cairo-lang-runner/src/short_string.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5150#-NraP-jc-EOxEhKFUwyX:-Nra_vqQCjFDGwOOYteB:b-j0k5zd) ([raw file](https://github.com/starkware-libs/cairo/blob/8e5355cb1fbcb744db6dc86496b8d2f0fa36111e/crates/cairo-lang-runner/src/short_string.rs#L36)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doesn't this significantly changes the meaning of the code?
</blockquote></details>

No.
The previous Felt type `to_bytes_be` method was only returning the exact amount of used bytes. 
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 632 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5150#-NraPnZT39zz_95kxGX7:-NrktGYd0aC31rnROY97:bu7tfvk) ([raw file](https://github.com/starkware-libs/cairo/blob/8e5355cb1fbcb744db6dc86496b8d2f0fa36111e/crates/cairo-lang-runner/src/casm_run/mod.rs#L632)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this one was much nicer the new by hand padding.
please just doc the padding.
and explain what changed to me.
</blockquote></details>

Yes sorry. So the previously used felt type (cairo-vm's one) `to_bytes_be` was returning a `&[u8]` with only the bytes used.
So you would get an array of 1 to 32 bytes, depending on how big is your number.
This implementation always returns a `[u8; 32]` so if you have a small number the n first bytes will be zeros.
Here we are talking short strings, meaning that when you decode them, you end up with your expected text, prefixed by a bunch of `\0` because they are valid, but invisible, utf8 characters.

So knowing that we just have to prepend our hardcoded string with the right amount of `\0` characters. The good thing is that there is no room for error because the compiler expects `[u8; 32]` so it will refuse to compile if you don't put enough padding.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1253 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5150#-NraRIn6-Dc8EFu1vmCl:-NrkuOrF83bRJXpfTS3N:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/8e5355cb1fbcb744db6dc86496b8d2f0fa36111e/crates/cairo-lang-runner/src/casm_run/mod.rs#L1253)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can this we generated some other way? from 2^64 directly possibly?
</blockquote></details>

done

**Review by tdelabro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5150)* status: 36 of 37 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 632 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5150#-NraPnZT39zz_95kxGX7:-Nrkv18LDsUlEW5ZjSqX:b-c9nfc8) ([raw file](https://github.com/starkware-libs/cairo/blob/8e5355cb1fbcb744db6dc86496b8d2f0fa36111e/crates/cairo-lang-runner/src/casm_run/mod.rs#L632)):*
<details><summary><i>Previously, tdelabro (Timothée Delabrouille) wrote…</i></summary><blockquote>

Yes sorry. So the previously used felt type (cairo-vm's one) `to_bytes_be` was returning a `&[u8]` with only the bytes used.
So you would get an array of 1 to 32 bytes, depending on how big is your number.
This implementation always returns a `[u8; 32]` so if you have a small number the n first bytes will be zeros.
Here we are talking short strings, meaning that when you decode them, you end up with your expected text, prefixed by a bunch of `\0` because they are valid, but invisible, utf8 characters.

So knowing that we just have to prepend our hardcoded string with the right amount of `\0` characters. The good thing is that there is no room for error because the compiler expects `[u8; 32]` so it will refuse to compile if you don't put enough padding.
</blockquote></details>

The `first_selector_non_zero_byte` involves more computation, including some iteration, while checking `[u8; 32]` identity will be performed super efficiently.
So even if it involves a lil bit of boilerplate padding, I think it is the better way

**Review by tdelabro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5150)* status: 36 of 37 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`Cargo.toml` line 88 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5150#-NraFb2U1iXAejkC_J3P:-Nrl3CVsAib8WELWoHK6:b560de2) ([raw file](https://github.com/starkware-libs/cairo/blob/9e234193ccee1f93efa1aef3fa9a2ebcc181a1af/Cargo.toml#L88)):*
> I think so. If you depend on a breaking change now you should be breaking yourself, no?  


I don't this this is true. If you don't expose the type externally there are no breaking changes as long as your codebase keeps doing the same thing.
Not every lib releases a new breaking change version every time one of its dependencies has a breaking change. It wouldn't make sense

**Review by tdelabro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5150)* status: 36 of 37 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`Cargo.toml` line 88 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5150#-NraFb2U1iXAejkC_J3P:-Nrl3__l9Dytx__uFXWY:be8pl6h) ([raw file](https://github.com/starkware-libs/cairo/blob/9e234193ccee1f93efa1aef3fa9a2ebcc181a1af/Cargo.toml#L88)):*
<details><summary><i>Previously, tdelabro (Timothée Delabrouille) wrote…</i></summary><blockquote>

> I think so. If you depend on a breaking change now you should be breaking yourself, no?  


I don't this this is true. If you don't expose the type externally there are no breaking changes as long as your codebase keeps doing the same thing.
Not every lib releases a new breaking change version every time one of its dependencies has a breaking change. It wouldn't make sense
</blockquote></details>

So here we will only have a breaking change if you re-report the new Felt type in some lib's interface. Do you?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5150)* status: 36 of 37 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @tdelabro)

___
*[`Cargo.toml` line 88 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5150#-NraFb2U1iXAejkC_J3P:-Nrnal2W5lcHJ6Fqh0Ml:bq6hvc2) ([raw file](https://github.com/starkware-libs/cairo/blob/9e234193ccee1f93efa1aef3fa9a2ebcc181a1af/Cargo.toml#L88)):*
<details><summary><i>Previously, tdelabro (Timothée Delabrouille) wrote…</i></summary><blockquote>

So here we will only have a breaking change if you re-report the new Felt type in some lib's interface. Do you?
</blockquote></details>

cairo-vm types are exposed AFAIK - as we give some hint implementation for blockifier.
so this will need to be postponed by about a week and a half.
___
*[`crates/cairo-lang-runner/src/short_string.rs` line 54 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5150#-NrnbRbNAn7GlVos203P:-NrnbRbO3ugk_GKabVch:brr2h2r) ([raw file](https://github.com/starkware-libs/cairo/blob/2d9d050e407f3650ebbcba07bc0548396c52fac8/crates/cairo-lang-runner/src/short_string.rs#L54)):*
> ```XML
>     if missing_nulls > 0 {
>         as_string.insert_str(0, &r"\0".repeat(missing_nulls));
>     }
> ```

can this actually fail now?



_Code quote:_
```XML
    let missing_nulls = length.saturating_sub(as_string.len());
    if missing_nulls > 0 {
        as_string.insert_str(0, &r"\0".repeat(missing_nulls));
    }
```

**Review by tdelabro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5150)* status: 36 of 37 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @orizi)

___
*[`crates/cairo-lang-runner/src/short_string.rs` line 54 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5150#-NrnbRbNAn7GlVos203P:-Nrqu-ANDtrTxPyIOF0y:bjrvu4z) ([raw file](https://github.com/starkware-libs/cairo/blob/2d9d050e407f3650ebbcba07bc0548396c52fac8/crates/cairo-lang-runner/src/short_string.rs#L54)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can this actually fail now?
</blockquote></details>

What do you mean by "fail"? No unwrap nor error is being returned in the code you highlighted, so there is no opportunity to fail.

**Review by tdelabro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5150)* status: 36 of 37 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @orizi)

___
*[`crates/cairo-lang-runner/src/short_string.rs` line 54 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5150#-NrnbRbNAn7GlVos203P:-NrqvEKKEpce0u1J9XmG:b-25kew9) ([raw file](https://github.com/starkware-libs/cairo/blob/2d9d050e407f3650ebbcba07bc0548396c52fac8/crates/cairo-lang-runner/src/short_string.rs#L54)):*
<details><summary><i>Previously, tdelabro (Timothée Delabrouille) wrote…</i></summary><blockquote>

What do you mean by "fail"? No unwrap nor error is being returned in the code you highlighted, so there is no opportunity to fail.
</blockquote></details>

Oh you probably mean the subtraction, yes it was failing for some tests: test_as_cairo_short_string_ex and test_format_for_debug

**Review by tdelabro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5150)* status: 35 of 37 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @orizi)

___
*[`crates/cairo-lang-runner/src/short_string.rs` line 54 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5150#-NrnbRbNAn7GlVos203P:-NrqwTZK72OUOTk3GYdn:bk9egcn) ([raw file](https://github.com/starkware-libs/cairo/blob/2d9d050e407f3650ebbcba07bc0548396c52fac8/crates/cairo-lang-runner/src/short_string.rs#L54)):*
<details><summary><i>Previously, tdelabro (Timothée Delabrouille) wrote…</i></summary><blockquote>

Oh you probably mean the subtraction, yes it was failing for some tests: test_as_cairo_short_string_ex and test_format_for_debug
</blockquote></details>

There was an error in my reasoning, using `as_string.len()` is not the same thing as using `bytes_len`. It's fixed in my latest push, bringing back the original behavior.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5150)* status: 36 of 37 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @tdelabro)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 632 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5150#-NraPnZT39zz_95kxGX7:-Ns-tk8a6k0lOHdMh6Jd:b-c99paw) ([raw file](https://github.com/starkware-libs/cairo/blob/8e5355cb1fbcb744db6dc86496b8d2f0fa36111e/crates/cairo-lang-runner/src/casm_run/mod.rs#L632)):*
<details><summary><i>Previously, tdelabro (Timothée Delabrouille) wrote…</i></summary><blockquote>

The `first_selector_non_zero_byte` involves more computation, including some iteration, while checking `[u8; 32]` identity will be performed super efficiently.
So even if it involves a lil bit of boilerplate padding, I think it is the better way
</blockquote></details>

i'm actually not entirely sure what is the underlying implementation for the match - it is quite possible it will compare the bytes for it by some `memcmp` style operation - so the \0 would be repeatedly processed in any case - while making the code less nice.

**Review by tdelabro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5150)* status: 36 of 37 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @orizi)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 632 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5150#-NraPnZT39zz_95kxGX7:-Ns0AsvH-rZfDWbPp3Zm:bsxxhg7) ([raw file](https://github.com/starkware-libs/cairo/blob/8e5355cb1fbcb744db6dc86496b8d2f0fa36111e/crates/cairo-lang-runner/src/casm_run/mod.rs#L632)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i'm actually not entirely sure what is the underlying implementation for the match - it is quite possible it will compare the bytes for it by some `memcmp` style operation - so the \0 would be repeatedly processed in any case - while making the code less nice.
</blockquote></details>

https://www.reddit.com/r/rust/comments/sm2aof/how_does_rust_implement_matching_against_strings/

It's hard to find resources on this subject, but my general rule of thumb is to assume the Rust compiler and LLVM are smarter than me and will optimize my code in a best way I can. For this specific example, I would put my money on it without hesitation.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5150)* status: 36 of 37 files reviewed, 2 unresolved discussions (waiting on @tdelabro)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 632 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5150#-NraPnZT39zz_95kxGX7:-Ns2cCCwD-K3Hirw4rRg:bplcbb2) ([raw file](https://github.com/starkware-libs/cairo/blob/8e5355cb1fbcb744db6dc86496b8d2f0fa36111e/crates/cairo-lang-runner/src/casm_run/mod.rs#L632)):*
<details><summary><i>Previously, tdelabro (Timothée Delabrouille) wrote…</i></summary><blockquote>

https://www.reddit.com/r/rust/comments/sm2aof/how_does_rust_implement_matching_against_strings/

It's hard to find resources on this subject, but my general rule of thumb is to assume the Rust compiler and LLVM are smarter than me and will optimize my code in a best way I can. For this specific example, I would put my money on it without hesitation.
</blockquote></details>

the rule of thumbs would work in the other direction as well (as rust may do the other op as efficient as possible) - so i rather have the readable code unless we actually have performance issues because of this.

**Review by tdelabro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5150)* status: 36 of 37 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 632 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5150#-NraPnZT39zz_95kxGX7:-Ns4sq6jEUmEPFw236l9:b5ujrni) ([raw file](https://github.com/starkware-libs/cairo/blob/8e5355cb1fbcb744db6dc86496b8d2f0fa36111e/crates/cairo-lang-runner/src/casm_run/mod.rs#L632)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the rule of thumbs would work in the other direction as well (as rust may do the other op as efficient as possible) - so i rather have the readable code unless we actually have performance issues because of this.
</blockquote></details>

Let's benchmark then

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5150)* status: all files reviewed, 2 unresolved discussions (waiting on @tdelabro)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 632 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5150#-NraPnZT39zz_95kxGX7:-NsAZ6LB13B_N6jbmlpV:bidhpgn) ([raw file](https://github.com/starkware-libs/cairo/blob/8e5355cb1fbcb744db6dc86496b8d2f0fa36111e/crates/cairo-lang-runner/src/casm_run/mod.rs#L632)):*
<details><summary><i>Previously, tdelabro (Timothée Delabrouille) wrote…</i></summary><blockquote>

Let's benchmark then
</blockquote></details>

the selector choice is highly unlikely to be any significant part of the running time in any case.

**Pull request closed without merging**
