### PR TITLE
Borrow checking remapping optimization

### PR DESCRIPTION
**Pull request by spapinistarkware**
commit-id:4b6a3244

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1781#-:-NLuwGf2-O1UFE-oFf6D:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware, @liorgold2, and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/mod.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1781#-NLuwL6g6FvFDum7425C:-NLuwL6g6FvFDum7425D:b-62ntfd) ([raw file](https://github.com/starkware-libs/cairo/blob/85a3e83d149d2ba02a002d17c73adfa2fee6ea3d/crates/cairo-lang-lowering/src/borrow_check/mod.rs#L32)):*
> ```XML
>     diagnostics: &'a mut LoweringDiagnostics,
>     lowered: &'a FlatLowered,
>     new_ends: HashMap<BlockId, FlatBlockEnd>,
> ```

doc member



_Code quote:_
```XML
    new_ends: HashMap<BlockId, FlatBlockEnd>,
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1781)* status: 16 of 18 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware, @liorgold2, and @orizi)

___
*[`crates/cairo-lang-lowering/src/borrow_check/mod.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1781#-NLuwL6g6FvFDum7425C:-NLuznP0CYIZS1u9owOj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/85a3e83d149d2ba02a002d17c73adfa2fee6ea3d/crates/cairo-lang-lowering/src/borrow_check/mod.rs#L32)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc member
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1781)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware and @liorgold2)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1781)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware and @liorgold2)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1781)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware and @liorgold2)

**Pull request merged**
