### PR TITLE
LS: New state architecture

### LINKED ISSUE #6129: New LS State Architecture
Rewrite LS state into a mutable state and snapshot structures and use coarse locking (either get entire state as mutable, or lock for a short time to produce a snapshot and defer work into a blocking background thread) depending on the request coming from the editor

This task is spin off #5355

### PR DESCRIPTION
**Pull request by Draggu**
fix #6129

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6309)

### CODE REVIEW

**Review by Arcticae — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6309#-:-O5T0h44133rpbkevg0F:bnfp4nl)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/state.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6309#-O5Sz9fm7XERcSKJuz5B:-O5Sz9fm7XERcSKJuz5C:bxo10v9) ([raw file](https://github.com/starkware-libs/cairo/blob/6704721dc960f98e20ee3680f5f6bba7abd5bae1/crates/cairo-lang-language-server/src/state.rs#L32)):*
> ```XML
> 
> impl State {
>     pub fn snapshot(&self) -> StateSnapshot {
> ```

The naming of structs seems weird here, `Snapshot` and `Owned` may be easily confused with salsa/rusts' std

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6309)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/state.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6309#-O5Sz9fm7XERcSKJuz5B:-O5TC2Gp0vPqiL8aMhFi:bmvf6hx) ([raw file](https://github.com/starkware-libs/cairo/blob/6704721dc960f98e20ee3680f5f6bba7abd5bae1/crates/cairo-lang-language-server/src/state.rs#L32)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

The naming of structs seems weird here, `Snapshot` and `Owned` may be easily confused with salsa/rusts' std
</blockquote></details>

any suggestions? these are the words we brainstormed on huddle
___
*[`crates/cairo-lang-language-server/src/state.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6309#-O5T9YADDaOAKVXYcwVS:-O5T9YADDaOAKVXYcwVT:bu5i1za) ([raw file](https://github.com/starkware-libs/cairo/blob/6704721dc960f98e20ee3680f5f6bba7abd5bae1/crates/cairo-lang-language-server/src/state.rs#L65)):*
> ```XML
> 
> #[derive(Debug, Default)]
> pub struct Owned<T: ?Sized>(Arc<T>);
> ```

doc all of these
___
*[`crates/cairo-lang-language-server/src/state.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6309#-O5T9i9HA7wekwIne6MW:-O5T9i9HA7wekwIne6MX:bkrxdin) ([raw file](https://github.com/starkware-libs/cairo/blob/6704721dc960f98e20ee3680f5f6bba7abd5bae1/crates/cairo-lang-language-server/src/state.rs#L77)):*
> ```XML
>     pub fn new(inner: Arc<T>) -> Self {
>         Self(inner)
>     }
> ```

reorder, put constructors at first



_Suggestion:_
```XML
    pub fn new(inner: Arc<T>) -> Self {
        Self(inner)
    }
    
    pub fn snapshot(&self) -> Snapshot<T> {
        Snapshot(self.0.clone())
    }
```

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6309)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 960 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6309#-O5TCoHD3fXHHxz9Q3l8:-O5TCoHD3fXHHxz9Q3l9:b6yo049) ([raw file](https://github.com/starkware-libs/cairo/blob/6704721dc960f98e20ee3680f5f6bba7abd5bae1/crates/cairo-lang-language-server/src/lib.rs#L960)):*
> ```XML
>     async fn completion(&self, params: CompletionParams) -> LSPResult<Option<CompletionResponse>> {
>         let state = self.state_snapshot().await;
>         self.catch_panics(move || ide::completion::complete(params, &state.db)).await
> ```

I think it might be worth it to make a method that just makes a snapshot of db. no need to make snapshots of all state fields if they're not gonna be used



_Suggestion:_
```XML
        let db = self.db_snapshot().await;
        self.catch_panics(move || ide::completion::complete(params, db)).await
```
___
*[`crates/cairo-lang-language-server/src/state.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6309#-O5TCICL5uYV9gqJdQfr:-O5TCICL5uYV9gqJdQfs:b-uzzglr) ([raw file](https://github.com/starkware-libs/cairo/blob/6704721dc960f98e20ee3680f5f6bba7abd5bae1/crates/cairo-lang-language-server/src/state.rs#L57)):*
> ```XML
>     pub open_files: Snapshot<HashSet<Url>>,
>     #[allow(dead_code)]
>     pub file_diagnostics: Snapshot<HashMap<Url, FileDiagnostics>>,
> ```

just remove this if it's unused

**Review by piotmag769 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6309)* status: 2 of 3 files reviewed, 8 unresolved discussions (waiting on @Arcticae, @Draggu, and @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 275 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6309#-O5SfuMt-ZCTMNg0_rta:-O5SfuMt-ZCTMNg0_rtb:b-tipyy2) ([raw file](https://github.com/starkware-libs/cairo/blob/6704721dc960f98e20ee3680f5f6bba7abd5bae1/crates/cairo-lang-language-server/src/lib.rs#L275)):*
> ```XML
> }
> 
> /// FIXME: Remove when we move to sync world.
> ```

More like TODO?
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 277 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6309#-O5TDacCDJoDgwCMHdZ_:-O5TDacCDJoDgwCMHdZa:b2nhhcg) ([raw file](https://github.com/starkware-libs/cairo/blob/6704721dc960f98e20ee3680f5f6bba7abd5bae1/crates/cairo-lang-language-server/src/lib.rs#L277)):*
> ```XML
> /// FIXME: Remove when we move to sync world.
> /// This is macro because of lifetimes problems with `self`.
> macro_rules! state_mut_async {
> ```

It 
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 314 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6309#-O5TBo1FAdL8kwDhi_FT:-O5TBo1FAdL8kwDhi_FU:bxp59q0) ([raw file](https://github.com/starkware-libs/cairo/blob/6704721dc960f98e20ee3680f5f6bba7abd5bae1/crates/cairo-lang-language-server/src/lib.rs#L314)):*
> ```XML
> 
>     /// Catches panics and returns Err.
>     async fn catch_panics<F, T>(&self, f: F) -> LSPResult<T>
> ```

This is great imo, much clearer what it does
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 339 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6309#-O5TCFHP-O5d9sVRcQ_a:-O5TCFHP-O5d9sVRcQ_b:bfbpylb) ([raw file](https://github.com/starkware-libs/cairo/blob/6704721dc960f98e20ee3680f5f6bba7abd5bae1/crates/cairo-lang-language-server/src/lib.rs#L339)):*
> ```XML
>     /// Locks and gets a server state.
>     #[tracing::instrument(level = "trace", skip_all)]
>     async fn state_mut<F, T>(&self, f: F) -> T
> ```

`mutate_state`/`call_on_mutable_state`? It doesn't return the state

**Review by piotmag769 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6309)* status: 2 of 3 files reviewed, 9 unresolved discussions (waiting on @Arcticae, @Draggu, and @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 278 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6309#-O5TFdHnDQDDjtP1KhJC:-O5TFdHnDQDDjtP1KhJD:bj8jjgw) ([raw file](https://github.com/starkware-libs/cairo/blob/6704721dc960f98e20ee3680f5f6bba7abd5bae1/crates/cairo-lang-language-server/src/lib.rs#L278)):*
> ```XML
> /// This is macro because of lifetimes problems with `self`.
> macro_rules! state_mut_async {
>     ($state:ident,$this:ident,$($f:tt)+) => {
> ```

Can we add whitespaces there, please xD

**Review by Draggu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6309)* status: 1 of 3 files reviewed, 7 unresolved discussions (waiting on @Arcticae, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 278 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6309#-O5TFdHnDQDDjtP1KhJC:-O5TJfR_3O2vWt2antlH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6704721dc960f98e20ee3680f5f6bba7abd5bae1/crates/cairo-lang-language-server/src/lib.rs#L278)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Can we add whitespaces there, please xD
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 339 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6309#-O5TCFHP-O5d9sVRcQ_a:-O5TJgmg-LKqDF5aS7Cj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6704721dc960f98e20ee3680f5f6bba7abd5bae1/crates/cairo-lang-language-server/src/lib.rs#L339)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

`mutate_state`/`call_on_mutable_state`? It doesn't return the state
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 960 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6309#-O5TCoHD3fXHHxz9Q3l8:-O5TJiU4-UUAI3An2SnC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6704721dc960f98e20ee3680f5f6bba7abd5bae1/crates/cairo-lang-language-server/src/lib.rs#L960)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I think it might be worth it to make a method that just makes a snapshot of db. no need to make snapshots of all state fields if they're not gonna be used
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/state.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6309#-O5TCICL5uYV9gqJdQfr:-O5TJlaV5aonHz2Dsr4d:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6704721dc960f98e20ee3680f5f6bba7abd5bae1/crates/cairo-lang-language-server/src/state.rs#L57)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

just remove this if it's unused
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/state.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6309#-O5T9YADDaOAKVXYcwVS:-O5TJm3p4GnbqoZ-c94w:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6704721dc960f98e20ee3680f5f6bba7abd5bae1/crates/cairo-lang-language-server/src/state.rs#L65)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

doc all of these
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/state.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6309#-O5T9i9HA7wekwIne6MW:-O5TJmgN-GZi9CNbrAHt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6704721dc960f98e20ee3680f5f6bba7abd5bae1/crates/cairo-lang-language-server/src/state.rs#L77)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

reorder, put constructors at first
</blockquote></details>

Done.

**Review by piotmag769 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6309#-:-O5TLgXi5xYSePAB7q4P:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @Arcticae, @mkaput, and @orizi)

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6309)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, and @orizi)

___
*[`crates/cairo-lang-language-server/src/state.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6309#-O5T9i9HA7wekwIne6MW:-O5TMC_vB2W3T2ecVspi:b-9qg1u4) ([raw file](https://github.com/starkware-libs/cairo/blob/6704721dc960f98e20ee3680f5f6bba7abd5bae1/crates/cairo-lang-language-server/src/state.rs#L77)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not done

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6309)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae and @Draggu)

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6309)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae and @Draggu)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 286 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6309#-O5TdiCd9aRpeBoyla-4:-O5TdiCe3zJj-bNiPKA_:b-odmhuq) ([raw file](https://github.com/starkware-libs/cairo/blob/71fc9d453d41e92b249cf60b0c4c971a7a50a5c2/crates/cairo-lang-language-server/src/lib.rs#L286)):*
> ```XML
>         }
>     };
> }
> ```

This macro looks unnecessary. It is used only 3 times. Why not just keep the original code?

**Review by mkaput — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6309)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae and @Draggu)

**Review by Draggu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6309)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 286 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6309#-O5TdiCd9aRpeBoyla-4:-O5ThaE8EgTsnDmsylpL:bjjup16) ([raw file](https://github.com/starkware-libs/cairo/blob/71fc9d453d41e92b249cf60b0c4c971a7a50a5c2/crates/cairo-lang-language-server/src/lib.rs#L286)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

This macro looks unnecessary. It is used only 3 times. Why not just keep the original code?
</blockquote></details>

Will be easy to forgot about this. Keeping this in 1 place seems better to me. After we erase async this should be regular `with_state_mut`.
___
*[`crates/cairo-lang-language-server/src/state.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6309#-O5Sz9fm7XERcSKJuz5B:-O5Ti214EpFB01Tcgd95:b-rbnr5x) ([raw file](https://github.com/starkware-libs/cairo/blob/6704721dc960f98e20ee3680f5f6bba7abd5bae1/crates/cairo-lang-language-server/src/state.rs#L32)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

maybe `Owned` -> `Origin`?

I think `Snapshot` could stay still
</blockquote></details>

Conclusion?
___
*[`crates/cairo-lang-language-server/src/state.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6309#-O5T9i9HA7wekwIne6MW:-O5ThvvhAofCPLWwpQBj:bc6lvis) ([raw file](https://github.com/starkware-libs/cairo/blob/6704721dc960f98e20ee3680f5f6bba7abd5bae1/crates/cairo-lang-language-server/src/state.rs#L77)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

not done
</blockquote></details>

Changed order in `State` not here XD. Done.

**Review by mkaput — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6309)* status: all files reviewed, 1 unresolved discussion (waiting on @Draggu)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 286 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6309#-O5TdiCd9aRpeBoyla-4:-O5TqELf5EvJLeSVV0tM:b-qxuwgy) ([raw file](https://github.com/starkware-libs/cairo/blob/71fc9d453d41e92b249cf60b0c4c971a7a50a5c2/crates/cairo-lang-language-server/src/lib.rs#L286)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

Will be easy to forgot about this. Keeping this in 1 place seems better to me. After we erase async this should be regular `with_state_mut`.
</blockquote></details>

couldn't we reduce scope of this macro to just take a lock? so that making an `async { ... }` block could happen outside?
___
*[`crates/cairo-lang-language-server/src/state.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6309#-O5Sz9fm7XERcSKJuz5B:-O5TqSr0-dtlMMBHQhce:bmczce0) ([raw file](https://github.com/starkware-libs/cairo/blob/6704721dc960f98e20ee3680f5f6bba7abd5bae1/crates/cairo-lang-language-server/src/state.rs#L32)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

It's not that big of a deal for me. Makes sense when you think about it
</blockquote></details>

I'm not enforcing changing this either

**Review by Draggu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6309)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 286 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6309#-O5TdiCd9aRpeBoyla-4:-O5U0Tuz8foqEoKeVfL6:bmpec4r) ([raw file](https://github.com/starkware-libs/cairo/blob/71fc9d453d41e92b249cf60b0c4c971a7a50a5c2/crates/cairo-lang-language-server/src/lib.rs#L286)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

couldn't we reduce scope of this macro to just take a lock? so that making an `async { ... }` block could happen outside?
</blockquote></details>

Easy to forget to drop lock asap.

**Pull request merged**
