### PR TITLE
PanicDestruct

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3233)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3232** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3232" target="_blank">Graphite</a> 
    * **PR #3233** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3233" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/3233?utm_source=stack-comment).

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3233)* status: 1 of 40 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/lib.cairo` line 242 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3233#-NWCMJdd-22CtbIfAnfl:-NXcztQ0ETVBY2ZqN3yb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/189913c5c9bcce3cc7827f27c067dc50e624957f/corelib/src/lib.cairo#L242)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I think leaving it here makes a bit more sense
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/destructs.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3233#-NWCMv7g8uDVGXo9-wYw:-NXcyrpf4GV8MsBdGr7J:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/93dd51073e85649eefc2b3bf48af5c8be4a04c15/crates/cairo-lang-lowering/src/destructs.rs#L42)):*
> ```XML
>     // A panic destructor call.
>     Panic(PanicDeconstructionEntry),
> }
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/destructs.rs` line 98 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3233#-NWCNFES15LfELOvDofH:-NXczcyQ0rzSdrk8qG5C:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/93dd51073e85649eefc2b3bf48af5c8be4a04c15/crates/cairo-lang-lowering/src/destructs.rs#L98)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 26 files at r2, 12 of 31 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3233)* status: 14 of 40 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`corelib/src/lib.cairo` line 242 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3233#-NWCMJdd-22CtbIfAnfl:-NXd6SH014sttOG_nBuK:be815p4) ([raw file](https://github.com/starkware-libs/cairo/blob/189913c5c9bcce3cc7827f27c067dc50e624957f/corelib/src/lib.cairo#L242)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

the panic type itself should have stayed here or moved to a panic submodule.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3233)* status: 12 of 70 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/lib.cairo` line 242 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3233#-NWCMJdd-22CtbIfAnfl:-NXiKYJkD9z2CBuaeoxq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/189913c5c9bcce3cc7827f27c067dc50e624957f/corelib/src/lib.cairo#L242)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the panic type itself should have stayed here or moved to a panic submodule.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r1, 1 of 26 files at r2, 1 of 31 files at r3, 1 of 2 files at r5, 36 of 67 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3233)* status: 44 of 75 files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/destructs.rs` line 77 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3233#-NXiSc9A1cSXHKEzqZK1:-NXiSc9A1cSXHKEzqZK2:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a848c089c404ad1cc6b3794fba42d5ded663854a/crates/cairo-lang-lowering/src/destructs.rs#L77)):*
> ```XML
>             return;
>         }
>         // If a non destructible variable gets our of scope, add a panic_destruct call for it.
> ```





_Suggestion:_
```XML
        }
        // If a non destructible variable gets out of scope, add a panic_destruct call for it.
```
___
*[`crates/cairo-lang-lowering/src/destructs.rs` line 126 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3233#-NXiTg1o2ARQH-f7hluN:-NXiTg1p7vk--v-t3JqI:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/a848c089c404ad1cc6b3794fba42d5ded663854a/crates/cairo-lang-lowering/src/destructs.rs#L126)):*
> ```XML
> }
> #[derive(Clone)]
> pub enum PanicLocation {
> ```

doc
___
*[`crates/cairo-lang-lowering/src/destructs.rs` line 128 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3233#-NXiUji44xmHpifXRhWo:-NXiUji5El1Uv-qQ5xB3:b-7rj2pg) ([raw file](https://github.com/starkware-libs/cairo/blob/a848c089c404ad1cc6b3794fba42d5ded663854a/crates/cairo-lang-lowering/src/destructs.rs#L128)):*
> ```XML
> pub enum PanicLocation {
>     PanicVar { panic_var: VariableId, statement_location: StatementLocation },
>     PanicTuple { tuple_var: VariableId, statement_location: StatementLocation },
> ```

don't we want a generic impl for tuple panic destruct?
___
*[`crates/cairo-lang-lowering/src/borrow_check/mod.rs` line 27 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3233#-NXiUvqMBZSLtfM5n9YC:-NXiUvqMBZSLtfM5n9YD:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/a848c089c404ad1cc6b3794fba42d5ded663854a/crates/cairo-lang-lowering/src/borrow_check/mod.rs#L27)):*
> ```XML
> 
> #[derive(Copy, Clone, Default)]
> pub enum PanicState {
> ```

doc

**Review by orizi — COMMENTED** [review]
> Reviewed 31 of 67 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3233)* status: all files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3233)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/destructs.rs` line 77 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3233#-NXiSc9A1cSXHKEzqZK1:-NXiWDse6DwLr6GaKyVY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a848c089c404ad1cc6b3794fba42d5ded663854a/crates/cairo-lang-lowering/src/destructs.rs#L77)):*
> ```XML
>             return;
>         }
>         // If a non destructible variable gets our of scope, add a panic_destruct call for it.
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/destructs.rs` line 126 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3233#-NXiTg1o2ARQH-f7hluN:-NXiWbn33xsPrnIzJyNx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a848c089c404ad1cc6b3794fba42d5ded663854a/crates/cairo-lang-lowering/src/destructs.rs#L126)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/destructs.rs` line 128 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3233#-NXiUji44xmHpifXRhWo:-NXiWii-4R8yS5BSNyUw:b-7zi8tj) ([raw file](https://github.com/starkware-libs/cairo/blob/a848c089c404ad1cc6b3794fba42d5ded663854a/crates/cairo-lang-lowering/src/destructs.rs#L128)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

don't we want a generic impl for tuple panic destruct?
</blockquote></details>

WDYM?
___
*[`crates/cairo-lang-lowering/src/borrow_check/mod.rs` line 27 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3233#-NXiUvqMBZSLtfM5n9YC:-NXiX4TT9pacpGdz_9a0:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a848c089c404ad1cc6b3794fba42d5ded663854a/crates/cairo-lang-lowering/src/borrow_check/mod.rs#L27)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3233#-:-NXiXXCnB_Fd0lDtElzw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/destructs.rs` line 128 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3233#-NXiUji44xmHpifXRhWo:-NXiXO7yEIrCcfEPDD7T:bl5z3ua) ([raw file](https://github.com/starkware-libs/cairo/blob/a848c089c404ad1cc6b3794fba42d5ded663854a/crates/cairo-lang-lowering/src/destructs.rs#L128)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

WDYM?
</blockquote></details>

i misunderstood the code - nm.

**Review by orizi — APPROVED** [review]
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3233)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
