### PR TITLE
Add nullable_ty() and box_ty().

### PR DESCRIPTION
**Pull request by liorgold2**
**Stack**:
- #4717
- #4716 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4716)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4716)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/boxing.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4716#-Nn9kRuI1Y9r_N36JBfX:-Nn9kRuI1Y9r_N36JBfY:byljnja) ([raw file](https://github.com/starkware-libs/cairo/blob/ae78a76764693e26b89b0f6c66aca6cb682f8536/crates/cairo-lang-sierra/src/extensions/modules/boxing.rs#L37)):*
> ```XML
> pub type BoxType = GenericTypeArgGenericTypeWrapper<BoxTypeWrapped>;
> 
> fn box_fn(context: &dyn SignatureSpecializationContext, ty: ConcreteTypeId) -> Result<ConcreteTypeId, SpecializationError> {
> ```

use already existing `boxed_ty` (and probably move it)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4716)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/getter.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4716#-Nn9m0Ru3bDaaqUYDAT3:-Nn9m0RvDzktmnKqhePO:be8ngh1) ([raw file](https://github.com/starkware-libs/cairo/blob/74147be435e6d7b1f4bfd925e8af0caf4723b592/crates/cairo-lang-sierra/src/extensions/modules/starknet/getter.rs#L81)):*
> ```XML
> ) -> Result<ConcreteTypeId, SpecializationError> {
>     context.get_wrapped_concrete_type(NullableType::id(), ty)
> }
> ```

these shouldn't be in starknet dir.



_Code quote:_
```XML
/// Helper for getting a boxed type for a given type `T`.
pub fn boxed_ty(
    context: &dyn SignatureSpecializationContext,
    ty: ConcreteTypeId,
) -> Result<ConcreteTypeId, SpecializationError> {
    context.get_wrapped_concrete_type(BoxType::id(), ty)
}

/// Helper for getting the type `Nullable<T>`.
pub fn nullable_ty(
    context: &dyn SignatureSpecializationContext,
    ty: ConcreteTypeId,
) -> Result<ConcreteTypeId, SpecializationError> {
    context.get_wrapped_concrete_type(NullableType::id(), ty)
}
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4716)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/boxing.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4716#-Nn9kRuI1Y9r_N36JBfX:-Nn9nkQz55ZKOL8NmoEc:bazs3gv) ([raw file](https://github.com/starkware-libs/cairo/blob/ae78a76764693e26b89b0f6c66aca6cb682f8536/crates/cairo-lang-sierra/src/extensions/modules/boxing.rs#L37)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

use already existing `boxed_ty` (and probably move it)
</blockquote></details>

Moved here + renamed to `box_ty`.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/getter.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4716#-Nn9m0Ru3bDaaqUYDAT3:-Nn9ni7F5L5BIlbweUuJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/74147be435e6d7b1f4bfd925e8af0caf4723b592/crates/cairo-lang-sierra/src/extensions/modules/starknet/getter.rs#L81)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

these shouldn't be in starknet dir.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4716#-:-NnAThUy5W4IgtKYKpbt:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
