### PR TITLE
Safer Blocks, and better generic param DebugWithDB

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2442)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2442** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2442" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2442?utm_source=stack-comment).

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 13 of 18 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2442#-:-NQEk4pS0i7TT_kNWAFg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 13 of 18 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2442)* status: all files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-diagnostics/src/diagnostics.rs` line 139 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2442#-NQJvZtsBwLrTCwPdFFy:-NQJvZtt-HpVbwDE8GCz:b-hbyk4i) ([raw file](https://github.com/starkware-libs/cairo/blob/0da105bfb197c07d9a1e8167dbe5b82972113dc4/crates/cairo-lang-diagnostics/src/diagnostics.rs#L139)):*
> ```XML
> 
>     pub fn is_diagnostic_free(&self) -> Maybe<()> {
>         if self.0.count == 0 { Ok(()) } else { Err(DiagnosticAdded) }
> ```

this is "is_empty".
I don't think the name makes it clear that this is the opposite of "is_empty" but with another way of outputing the result.



_Code quote:_
```XML
self.0.count == 0
```
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 117 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2442#-NQJw0ob-KNkjC06LQg8:-NQJw0ob-KNkjC06LQg9:b-rl43d5) ([raw file](https://github.com/starkware-libs/cairo/blob/0da105bfb197c07d9a1e8167dbe5b82972113dc4/crates/cairo-lang-lowering/src/inline/mod.rs#L117)):*
> ```XML
>     /// stack for statements that require rewriting.
>     statement_rewrite_stack: StatementStack,
>     /// Indicates that there was an error during inlining.
> ```

update the doc
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 100 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2442#-NQJwpps90V-SGppuSiu:-NQJwpps90V-SGppuSiv:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0da105bfb197c07d9a1e8167dbe5b82972113dc4/crates/cairo-lang-lowering/src/lower/mod.rs#L100)):*
> ```XML
>     });
>     let blocks = root_ok
>         .map(|_| ctx.blocks.build().expect("Root block must exists."))
> ```





_Suggestion:_
```XML
exist
```
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 755 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2442#-NQJyC7J29p6Ko_xptWb:-NQJyC7J29p6Ko_xptWc:b-1c12md) ([raw file](https://github.com/starkware-libs/cairo/blob/0da105bfb197c07d9a1e8167dbe5b82972113dc4/crates/cairo-lang-lowering/src/lower/mod.rs#L755)):*
> ```XML
>         try_extract_matches!(concrete_ty, ConcreteTypeId::Enum).ok_or_else(|| {
>             LoweringFlowError::Failed(
>                 ctx.diagnostics.report(expr.stable_ptr.untyped(), UnsupportedMatch),
> ```

Maybe add different types of unsupported match? So that the error would be clear.



_Code quote:_
```XML
        LoweringFlowError::Failed(
            ctx.diagnostics.report(expr.stable_ptr.untyped(), UnsupportedMatch),
        )
    })?;
    let concrete_enum_id =
        try_extract_matches!(concrete_ty, ConcreteTypeId::Enum).ok_or_else(|| {
            LoweringFlowError::Failed(
                ctx.diagnostics.report(expr.stable_ptr.untyped(), UnsupportedMatch),
            )
```
___
*[`crates/cairo-lang-lowering/src/objects/blocks.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2442#-NQJzJuc4SSaKYI4g5od:-NQJzJuc4SSaKYI4g5oe:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0da105bfb197c07d9a1e8167dbe5b82972113dc4/crates/cairo-lang-lowering/src/objects/blocks.rs#L26)):*
> ```XML
> /// This is used instead of id_arena, since the latter is harder to clone and modify.
> #[derive(Clone, Debug, Default, PartialEq, Eq)]
> pub struct BlocksBuilder<T>(pub Vec<T>);
> ```





_Suggestion:_
```XML
(Vec<T>)
```
___
*[`crates/cairo-lang-lowering/src/objects/blocks.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2442#-NQJzQU9017mVdfqc9qg:-NQJzQU9017mVdfqc9qh:b-qhe46s) ([raw file](https://github.com/starkware-libs/cairo/blob/0da105bfb197c07d9a1e8167dbe5b82972113dc4/crates/cairo-lang-lowering/src/objects/blocks.rs#L87)):*
> ```XML
> 
>     pub fn has_root(&self) -> Maybe<()> {
>         if self.is_empty() { Err(DiagnosticAdded) } else { Ok(()) }
> ```

please doc why it's OK to add DiagnosticAdded in these functions.



_Code quote:_
```XML
    pub fn root_block(&self) -> Maybe<&T> {
        if self.is_empty() { Err(DiagnosticAdded) } else { Ok(&self.0[0]) }
    }

    pub fn has_root(&self) -> Maybe<()> {
        if self.is_empty() { Err(DiagnosticAdded) } else { Ok(()) }
    }
```
___
*[`crates/cairo-lang-sierra-generator/src/utils.rs` line 252 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2442#-NQK26_o18caYjUyZcTl:-NQK26_o18caYjUyZcTm:blrba9z) ([raw file](https://github.com/starkware-libs/cairo/blob/0da105bfb197c07d9a1e8167dbe5b82972113dc4/crates/cairo-lang-sierra-generator/src/utils.rs#L252)):*
> ```XML
>         {
>             let function = db.lookup_intern_sierra_function(function);
>             panic!("Missing function {:?}", function.debug(db.elongate()));
> ```

why isn't this logic in the debug of the kind of the SpecializationError?



_Code quote:_
```XML
            let function = db.lookup_intern_sierra_function(function);
            panic!("Missing function {:?}", function.debug(db.elongate()));
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2442#-:-NQKHk4iCbAf0ryVczZc:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2442#-:-NQKM-q13LKHKj5RMySt:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
