### PR TITLE
Force the inclusion of `System` in the list of implicits.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1529)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1529#-:-NKMwKikAj7UFnpt3bht:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1529#-:-NKMyB6qDdr9qgcLdS5U:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/starknet/src/plugin.rs` line 230 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1529#-NKMxQLm7bHxrRyY25RI:-NKMxQLm7bHxrRyY25RJ:b-6zj4c8) ([raw file](https://github.com/starkware-libs/cairo/blob/da46ee317272698c24626c4cc98f52b897f54adf/crates/starknet/src/plugin.rs#L230)):*
> ```XML
>             if array_len::<felt>(data) != 0_u128 {
>                 // Force the inclusion of `System` in the list of implicits.
>                 starknet::use_system_implicit();
> ```

Please move to first/last line , not inside a random if. This is much more readable, and after inlining this is anyway going to be translated to nothing.



_Code quote:_
```XML
                // Force the inclusion of `System` in the list of implicits.
                starknet::use_system_implicit();
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 21 of 21 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1529)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-runner/src/lib.rs` line 107 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1529#-NKNaovx4fwCwtpv5PpC:-NKNaovy7qKLUL49Xkg3:b-n70y6m) ([raw file](https://github.com/starkware-libs/cairo/blob/4a27b2a1a7b2729ab1ef65b82834fa1b1e398a3c/crates/cairo-runner/src/lib.rs#L107)):*
> ```XML
>                 false
>             } else {
>                 // TODO(orizi): Actually return the builtin pointers.
> ```

remove the todo - no longer relevant.



_Code quote:_
```XML
                // TODO(orizi): Actually return the builtin pointers.
```

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1529)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
