### PR TITLE
Handle box constants.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #5149
- #5134 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5134)

### CODE REVIEW

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5134)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5134#-Nr_bs0AC0Va5niutF82:-Nr_bs0AC0Va5niutF83:b-abq4vr) (no related file):*
Add tests for it.

___

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5134)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5134#-Nr_bs0AC0Va5niutF82:-Nr_wAxx4LJm9V0YGC-b:b-896fix) (no related file):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Add tests for it.
</blockquote></details>

Done.

___

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5134)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5134#-Nr_bs0AC0Va5niutF82:-NrjTFZI-dJ64pbkCUHz:bx65pua) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still blocking

___

**Review by gilbens-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5134)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
