### PR TITLE
Added split_bytes31

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3608)

### CODE REVIEW

**Comment by yuvalsw** [comment]
Change target branch

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3608)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/lib.cairo` line 210 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3608#-N_Z-74c9kl6mqKtlqTf:-N_ZJkwp4qDso1BOqUsK:b8cgi4t) ([raw file](https://github.com/starkware-libs/cairo/blob/d58ce1f5211f698cd79ddc36f998685134d00af1/corelib/src/lib.cairo#L210)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

might be useful for other stuff - but i think if we export it it should be in a more orderly fashion.
</blockquote></details>

I think all felt252 stuff should be in a separate file, but this is for a separate PR. I can do it later

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3608)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/bytes_31.cairo` line 75 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3608#-N_YzU2yCfa-KWlg2ZIy:-N_ZKCqUEfjwgD8o3h_g:bj1yl0u) ([raw file](https://github.com/starkware-libs/cairo/blob/d58ce1f5211f698cd79ddc36f998685134d00af1/corelib/src/bytes_31.cairo#L75)):*
> ```Cairo
>     }
> 
>     let u256{low, high } = u256_from_felt252(word);
> ```

Changed, but unfortunately inference currently doesn't recognise the type of the pattern, so had to add ": u256".
___
*[`corelib/src/bytes_31.cairo` line 112 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3608#-N_YzrCg34DlARCxfIz2:-N_ZOEs0En0cUjuS_ZQR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d58ce1f5211f698cd79ddc36f998685134d00af1/corelib/src/bytes_31.cairo#L112)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

note that assert due incur a price - make sure this is actually needed.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3608)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`corelib/src/lib.cairo` line 210 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3608#-N_Z-74c9kl6mqKtlqTf:-N_ZR3128VkC8nfGGZoy:bq4nljc) ([raw file](https://github.com/starkware-libs/cairo/blob/d58ce1f5211f698cd79ddc36f998685134d00af1/corelib/src/lib.cairo#L210)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I think all felt252 stuff should be in a separate file, but this is for a separate PR. I can do it later
</blockquote></details>

mostly since 2 to the power of 128 is not necessarily a concept for felt252 as it is - just declare it for your usage needs, and not for everyone.

**Comment by yuvalsw** [comment]
*[`corelib/src/lib.cairo` line 210 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3608#-N_Z-74c9kl6mqKtlqTf:-N_ZTYWPEfj_tvPgDJut:b-mt2vq6) ([raw file](https://github.com/starkware-libs/cairo/blob/d58ce1f5211f698cd79ddc36f998685134d00af1/corelib/src/lib.cairo#L210)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

mostly since 2 to the power of 128 is not necessarily a concept for felt252 as it is - just declare it for your usage needs, and not for everyone.
</blockquote></details>

I thought you said you agree it may be useful for other stuff. It's not specific for bytes31 so I didn't want to put it in bytes_31.cairo and then import it from there when using in byte_array.cairo. And it made sense to put with other felt stuff as it may be useful. It is a felt thing IMO as this is the 2^128 constant of type felt252.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3608)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`corelib/src/lib.cairo` line 210 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3608#-N_Z-74c9kl6mqKtlqTf:-N_bm70V2KWf8IBiAZAi:bw6ro1q) ([raw file](https://github.com/starkware-libs/cairo/blob/d58ce1f5211f698cd79ddc36f998685134d00af1/corelib/src/lib.cairo#L210)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I thought you said you agree it may be useful for other stuff. It's not specific for bytes31 so I didn't want to put it in bytes_31.cairo and then import it from there when using in byte_array.cairo. And it made sense to put with other felt stuff as it may be useful. It is a felt thing IMO as this is the 2^128 constant of type felt252.
</blockquote></details>

it may be useful - but i don't want to export it for now.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3608)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/lib.cairo` line 210 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3608#-N_Z-74c9kl6mqKtlqTf:-N_cFM0cEFwVcommUUkg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d58ce1f5211f698cd79ddc36f998685134d00af1/corelib/src/lib.cairo#L210)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it may be useful - but i don't want to export it for now.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3608#-:-N_cFyLw9utucbg4iUJS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
