### PR TITLE
Implicits phase

### PR DESCRIPTION
**Pull request by spapinistarkware**
Based on Yuval's PR
https://reviewable.io/reviews/starkware-libs/cairo/2317#-

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2327)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 30 of 47 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2327)* status: 30 of 47 files reviewed, 5 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/implicits/mod.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2327#-NPRm-8C1ewXd3N3ocZo:-NPRm-8C1ewXd3N3ocZp:bb7r2f0) ([raw file](https://github.com/starkware-libs/cairo/blob/13038425238d97058b7e6bc1c5c93af454329ea0/crates/cairo-lang-lowering/src/implicits/mod.rs#L55)):*
> ```XML
>     lowering_ctx.variables = lowered.variables.clone();
> 
>     // TODO: Skip this phase for non panicable functions.
> ```

why?



_Suggestion:_
```XML
    // TODO(spapini): Skip this phase for non panicable functions.
    let implicits_tys = db.function_all_implicits(function_id.function_id(db.upcast()))?;
```
___
*[`crates/cairo-lang-lowering/src/implicits/mod.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2327#-NPRm9-l3ZD1mAbpESse:-NPRm9-l3ZD1mAbpESsf:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/13038425238d97058b7e6bc1c5c93af454329ea0/crates/cairo-lang-lowering/src/implicits/mod.rs#L59)):*
> ```XML
> 
>     let mut implicit_index = HashMap::new();
>     for (i, ty) in implicits_tys.iter().enumerate() {
> ```





_Suggestion:_
```XML
    let implicit_index = HashMap::from_iter(
        implicits_tys.iter().enumerate().map(|(i, ty)|(*ty, i)
    );
```
___
*[`crates/cairo-lang-lowering/src/implicits/mod.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2327#-NPRmxMS15VYeUKmicGG:-NPRmxMS15VYeUKmicGH:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/13038425238d97058b7e6bc1c5c93af454329ea0/crates/cairo-lang-lowering/src/implicits/mod.rs#L85)):*
> ```XML
> }
> 
> fn alloc_implicits(
> ```

doc



_Code quote:_
```XML
alloc_implicits
```
___
*[`crates/cairo-lang-lowering/src/implicits/mod.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2327#-NPRn6OJ8851l0YSs1cR:-NPRn6OJ8851l0YSs1cS:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/13038425238d97058b7e6bc1c5c93af454329ea0/crates/cairo-lang-lowering/src/implicits/mod.rs#L93)):*
> ```XML
> }
> 
> fn lower_block(ctx: &mut Context<'_>, block_id: BlockId) -> Maybe<()> {
> ```

doc



_Code quote:_
```XML
lower_block
```
___
*[`crates/cairo-lang-lowering/src/implicits/mod.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2327#-NPRnN1xB8HZo_LWr-Rf:-NPRnN1xB8HZo_LWr-Rg:buro890) ([raw file](https://github.com/starkware-libs/cairo/blob/13038425238d97058b7e6bc1c5c93af454329ea0/crates/cairo-lang-lowering/src/implicits/mod.rs#L102)):*
> ```XML
>         .or_insert_with(|| alloc_implicits(ctx.ctx, &ctx.implicits_tys, ctx.location))
>         .clone();
>     for i in 0..ctx.lowered.blocks[block_id].statements.len() {
> ```

if works



_Suggestion:_
```XML
    for (i, statement) in &mut statements {
        match statement {
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2327)* status: 30 of 47 files reviewed, 6 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-starknet/test_data/account.sierra` line 287 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2327#-NPRbCjL6I2lQCaH9RTB:-NPRbCjL6I2lQCaH9RTC:b-xya493) ([raw file](https://github.com/starkware-libs/cairo/blob/13038425238d97058b7e6bc1c5c93af454329ea0/crates/cairo-lang-starknet/test_data/account.sierra#L287)):*
> ```
> store_temp<EcOp>([1]) -> ([20]);
> store_temp<GasBuiltin>([12]) -> ([21]);
> store_temp<System>([3]) -> ([22]);
> ```

why are these no longer locals?



_Code quote:_
```
store_temp<RangeCheck>([11]) -> ([19]);
store_temp<EcOp>([1]) -> ([20]);
store_temp<GasBuiltin>([12]) -> ([21]);
store_temp<System>([3]) -> ([22]);
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 13 of 47 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2327)* status: 43 of 47 files reviewed, 7 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`tests/test_data/fib_u128.casm` line 4 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2327#-NPRoZyB92mxj8yXwNye:-NPRoZyB92mxj8yXwNyf:bnsvg22) ([raw file](https://github.com/starkware-libs/cairo/blob/13038425238d97058b7e6bc1c5c93af454329ea0/tests/test_data/fib_u128.casm#L4)):*
> ```
> jmp rel 4 if [ap + -1] != 0;
> jmp rel 7;
> [ap + 0] = [fp + -6], ap++;
> ```

same here - why are these aligned?



_Code quote:_
```
jmp rel 7;
[ap + 0] = [fp + -6], ap++;
```

**Review by yuvalsw — DISMISSED** [review]
> Reviewed 4 of 47 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2327)* status: 43 of 47 files reviewed, 14 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/implicits/mod.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2327#-NPT4ano0350LNP9mbUL:-NPT4ano0350LNP9mbUM:bd48dtt) ([raw file](https://github.com/starkware-libs/cairo/blob/13038425238d97058b7e6bc1c5c93af454329ea0/crates/cairo-lang-lowering/src/implicits/mod.rs#L67)):*
> ```XML
>         lowered,
>         implicit_index,
>         implicits_tys,
> ```

Do you really need both tys and index?
___
*[`crates/cairo-lang-lowering/src/implicits/mod.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2327#-NPT4ozg43aC_xNS_R6Q:-NPT4ozg43aC_xNS_R6R:b6b69sj) ([raw file](https://github.com/starkware-libs/cairo/blob/13038425238d97058b7e6bc1c5c93af454329ea0/crates/cairo-lang-lowering/src/implicits/mod.rs#L73)):*
> ```XML
>     };
> 
>     // Iterate block queue (old and new blocks).
> ```

I don't understand this comment
___
*[`crates/cairo-lang-lowering/src/implicits/mod.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2327#-NPT5Rl7CqK5V7RGdLuV:-NPT5Rl7CqK5V7RGdLuW:bay9o3u) ([raw file](https://github.com/starkware-libs/cairo/blob/13038425238d97058b7e6bc1c5c93af454329ea0/crates/cairo-lang-lowering/src/implicits/mod.rs#L102)):*
> ```XML
>         .or_insert_with(|| alloc_implicits(ctx.ctx, &ctx.implicits_tys, ctx.location))
>         .clone();
>     for i in 0..ctx.lowered.blocks[block_id].statements.len() {
> ```

export to a var



_Code quote:_
```XML
ctx.lowered.blocks[block_id].statements
```
___
*[`crates/cairo-lang-lowering/src/implicits/mod.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2327#-NPT5vi49DAT90Dpvpu-:-NPT5vi49DAT90Dpvpu0:b-857um7) ([raw file](https://github.com/starkware-libs/cairo/blob/13038425238d97058b7e6bc1c5c93af454329ea0/crates/cairo-lang-lowering/src/implicits/mod.rs#L103)):*
> ```XML
>         .clone();
>     for i in 0..ctx.lowered.blocks[block_id].statements.len() {
>         match &mut ctx.lowered.blocks[block_id].statements[i] {
> ```

Do we plan additional types of "call" statements?
If not, I think this should be an "if let"
___
*[`crates/cairo-lang-lowering/src/implicits/mod.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2327#-NPT8Tfl0TwMovd9hvaI:-NPT8Tfl0TwMovd9hvaJ:b14lx2x) ([raw file](https://github.com/starkware-libs/cairo/blob/13038425238d97058b7e6bc1c5c93af454329ea0/crates/cairo-lang-lowering/src/implicits/mod.rs#L148)):*
> ```XML
>         }
>         FlatBlockEnd::Match { info } => match info {
>             MatchInfo::Enum(stmt) => {
> ```

please rename. Also below



_Code quote:_
```XML
stmt
```
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 421 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2327#-NPTA5r_6UT9OZQLKpKS:-NPTA5r_6UT9OZQLKpKT:b-l6g6pu) ([raw file](https://github.com/starkware-libs/cairo/blob/13038425238d97058b7e6bc1c5c93af454329ea0/crates/cairo-lang-lowering/src/lower/mod.rs#L421)):*
> ```XML
>         .map(|semantic_var_id| ctx.semantic_defs[*semantic_var_id].ty())
>         .collect();
>     let inputs = arg_inputs.into_iter().collect();
> ```

remove, or just use arg_inputs below.



_Code quote:_
```XML
.into_iter().collect()
```
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2327#-NPTAdD9CxS07YocvQMu:-NPTAdD9CxS07YocvQMv:bhukg27) ([raw file](https://github.com/starkware-libs/cairo/blob/13038425238d97058b7e6bc1c5c93af454329ea0/crates/cairo-lang-lowering/src/lower/scope.rs#L57)):*
> ```XML
> 
>     /// Creates a [BlockBuilder] for a subscope with unchanged refs.
>     pub fn subscope_with_bound_refs(&self, block_id: BlockId) -> BlockBuilder {
> ```

remove function



_Code quote (from crates/cairo-lang-lowering/src/lower/mod.rs):_
```XML
subscope.bind_refs();
```

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 47 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2327)* status: 46 of 47 files reviewed, 14 unresolved discussions (waiting on @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 47 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2327)* status: all files reviewed, 14 unresolved discussions (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2327)* status: 0 of 93 files reviewed, 14 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/implicits/mod.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2327#-NPRm-8C1ewXd3N3ocZo:-NPStkEP7anY9Yd05mUv:bb71nyg) ([raw file](https://github.com/starkware-libs/cairo/blob/13038425238d97058b7e6bc1c5c93af454329ea0/crates/cairo-lang-lowering/src/implicits/mod.rs#L55)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why?
</blockquote></details>

Oops
___
*[`crates/cairo-lang-lowering/src/implicits/mod.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2327#-NPRm9-l3ZD1mAbpESse:-NPStptPCGjJCmvqLqFm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/13038425238d97058b7e6bc1c5c93af454329ea0/crates/cairo-lang-lowering/src/implicits/mod.rs#L59)):*
> ```XML
> 
>     let mut implicit_index = HashMap::new();
>     for (i, ty) in implicits_tys.iter().enumerate() {
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/implicits/mod.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2327#-NPRmxMS15VYeUKmicGG:-NPStzkl8iARL_kI0Xgm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/13038425238d97058b7e6bc1c5c93af454329ea0/crates/cairo-lang-lowering/src/implicits/mod.rs#L85)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/implicits/mod.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2327#-NPRn6OJ8851l0YSs1cR:-NPSu96P68KWf_G92nTa:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/13038425238d97058b7e6bc1c5c93af454329ea0/crates/cairo-lang-lowering/src/implicits/mod.rs#L93)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/implicits/mod.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2327#-NPRnN1xB8HZo_LWr-Rf:-NPSugq5BczUsY-I1raj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/13038425238d97058b7e6bc1c5c93af454329ea0/crates/cairo-lang-lowering/src/implicits/mod.rs#L102)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

if works
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/test_data/account.sierra` line 287 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2327#-NPRbCjL6I2lQCaH9RTB:-NPSyBkz9KndWd3sWH9R:b-6cx9e8) ([raw file](https://github.com/starkware-libs/cairo/blob/13038425238d97058b7e6bc1c5c93af454329ea0/crates/cairo-lang-starknet/test_data/account.sierra#L287)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why are these no longer locals?
</blockquote></details>

Bug in remapping optimization:( Fixed.
___
*[`tests/test_data/fib_u128.casm` line 4 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2327#-NPRoZyB92mxj8yXwNye:-NPSyFoK2VY80w5B6e4Y:bb73xfv) ([raw file](https://github.com/starkware-libs/cairo/blob/13038425238d97058b7e6bc1c5c93af454329ea0/tests/test_data/fib_u128.casm#L4)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

same here - why are these aligned?
</blockquote></details>

Same

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2327)* status: 0 of 93 files reviewed, 11 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/implicits/mod.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2327#-NPT4ano0350LNP9mbUL:-NPWFpvv4phUveQbPX8U:b59dyqp) ([raw file](https://github.com/starkware-libs/cairo/blob/13038425238d97058b7e6bc1c5c93af454329ea0/crates/cairo-lang-lowering/src/implicits/mod.rs#L67)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Do you really need both tys and index?
</blockquote></details>

Yes. When calling an inner function, it gets a subset of the tys, so I fetch their index in the parent implicits.
___
*[`crates/cairo-lang-lowering/src/implicits/mod.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2327#-NPT4ozg43aC_xNS_R6Q:-NPWG4I9ALPsOA_S720p:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/13038425238d97058b7e6bc1c5c93af454329ea0/crates/cairo-lang-lowering/src/implicits/mod.rs#L73)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I don't understand this comment
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/implicits/mod.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2327#-NPT8Tfl0TwMovd9hvaI:-NPWGKunCUeagWyJcwkR:b-9da684) ([raw file](https://github.com/starkware-libs/cairo/blob/13038425238d97058b7e6bc1c5c93af454329ea0/crates/cairo-lang-lowering/src/implicits/mod.rs#L148)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

please rename. Also below
</blockquote></details>

Why? What's wrong with stmt?
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2327#-NPTAdD9CxS07YocvQMu:-NPWGdQ17zChPLl4MC2y:bycziuh) ([raw file](https://github.com/starkware-libs/cairo/blob/13038425238d97058b7e6bc1c5c93af454329ea0/crates/cairo-lang-lowering/src/lower/scope.rs#L57)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

remove function
</blockquote></details>

I intend on cleaning up in a later PR

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 48 files at r5, 1 of 26 files at r7, 36 of 37 files at r8, 55 of 55 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2327#-:-NPWM2Zr2DWhvSX-VK8K:bnfp4nl)* status: all files reviewed, 7 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/implicits/mod.rs` line 36 at r9](https://reviewable.io/reviews/starkware-libs/cairo/2327#-NPWI1Ke6MidFpV3Pumu:-NPWI1Ke6MidFpV3Pumv:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/c53d2033080d580a2a007848199730e310bb5f49/crates/cairo-lang-lowering/src/implicits/mod.rs#L36)):*
> ```XML
> }
> 
> pub fn inner_lower_implicits(
> ```

doc



_Code quote:_
```XML
pub fn inner_lower_implicits(
```
___
*[`crates/cairo-lang-lowering/src/implicits/mod.rs` line 100 at r9](https://reviewable.io/reviews/starkware-libs/cairo/2327#-NPWI94tAc9Wg7nZ8qDh:-NPWI94tAc9Wg7nZ8qDi:b-furm2o) ([raw file](https://github.com/starkware-libs/cairo/blob/c53d2033080d580a2a007848199730e310bb5f49/crates/cairo-lang-lowering/src/implicits/mod.rs#L100)):*
> ```XML
>         .or_insert_with(|| alloc_implicits(ctx.ctx, &ctx.implicits_tys, ctx.location))
>         .clone();
>     let statements = &mut ctx.lowered.blocks[block_id].statements;
> ```

i think you are now using it only once - so just inline the variable into the for.



_Code quote:_
```XML
    let statements = &mut ctx.lowered.blocks[block_id].statements;
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2327)* status: 54 of 93 files reviewed, 7 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/implicits/mod.rs` line 36 at r9](https://reviewable.io/reviews/starkware-libs/cairo/2327#-NPWI1Ke6MidFpV3Pumu:-NPWMX1G9Aei8Rnyurkb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c53d2033080d580a2a007848199730e310bb5f49/crates/cairo-lang-lowering/src/implicits/mod.rs#L36)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/implicits/mod.rs` line 100 at r9](https://reviewable.io/reviews/starkware-libs/cairo/2327#-NPWI94tAc9Wg7nZ8qDh:-NPWMcDw24IOCMxO2Aeh:bonqnz4) ([raw file](https://github.com/starkware-libs/cairo/blob/c53d2033080d580a2a007848199730e310bb5f49/crates/cairo-lang-lowering/src/implicits/mod.rs#L100)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i think you are now using it only once - so just inline the variable into the for.
</blockquote></details>

But Yuval literaly just asked me to extrcat to a var!!!!!!

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 3 of 48 files at r5, 15 of 37 files at r8, 36 of 55 files at r9, 38 of 39 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2327)* status: all files reviewed, 7 unresolved discussions (waiting on @orizi and @yuvalsw)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2327)* status: all files reviewed, 6 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/implicits/mod.rs` line 100 at r9](https://reviewable.io/reviews/starkware-libs/cairo/2327#-NPWI94tAc9Wg7nZ8qDh:-NPWQXlc04KsKn-ZOwhC:b-bcntxv) ([raw file](https://github.com/starkware-libs/cairo/blob/c53d2033080d580a2a007848199730e310bb5f49/crates/cairo-lang-lowering/src/implicits/mod.rs#L100)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

But Yuval literaly just asked me to extrcat to a var!!!!!!
</blockquote></details>

but it was before the refactoring i asked for :)

**Pull request merged**
