### PR TITLE
Added diagnostics comparison to test_partial_parser_tree

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1521)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1521)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/parser/src/parser_test.rs` line 263 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1521#-NKJ_aw899iSBCZJds8t:-NKJ_aw9DJ85t5DA9ktC:bmghjj3) ([raw file](https://github.com/starkware-libs/cairo/blob/9a59561603b21d1bf039e51227037e2a3408b267/crates/parser/src/parser_test.rs#L263)):*
> ```XML
>     let (syntax_root, diagnostics) =
>         get_syntax_root_and_diagnostics(db, file_id, &inputs["cairo_code"]);
>     assert_eq!(diagnostics.format(db), inputs["expected_diagnostics"]);
> ```

auto fix won't work this way, right?



_Code quote:_
```XML
assert_eq!(diagnostics.format(db), inputs["expected_diagnostics"]);
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1521)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/parser/src/parser_test.rs` line 269 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1521#-NKJ_rNE0ZPwNGrGlFI3:-NKJ_rNE0ZPwNGrGlFI4:b6u86qx) ([raw file](https://github.com/starkware-libs/cairo/blob/9a59561603b21d1bf039e51227037e2a3408b267/crates/parser/src/parser_test.rs#L269)):*
> ```XML
>         "expected_tree".into(),
>         print_partial_tree(db, &syntax_root, &inputs["top_level_kind"], ignored_kinds),
>     )])
> ```

Can't you do the following?



_Suggestion:_
```XML
    OrderedHashMap::from([(
        "expected_tree".into(),
        print_partial_tree(db, &syntax_root, &inputs["top_level_kind"], ignored_kinds),
        "expected_diagnostics".into(),
        diagnostics.format(db),
    )])
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 3 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1521)* status: 3 of 10 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1521)* status: 3 of 10 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/parser/src/parser_test.rs` line 263 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1521#-NKJ_aw899iSBCZJds8t:-NKMvgii7ci2ZfU0Swxu:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9a59561603b21d1bf039e51227037e2a3408b267/crates/parser/src/parser_test.rs#L263)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

auto fix won't work this way, right?
</blockquote></details>

Done.
___
*[`crates/parser/src/parser_test.rs` line 269 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1521#-NKJ_rNE0ZPwNGrGlFI3:-NKMvgwk4p3vbnXKxNoz:b9seiz0) ([raw file](https://github.com/starkware-libs/cairo/blob/9a59561603b21d1bf039e51227037e2a3408b267/crates/parser/src/parser_test.rs#L269)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Can't you do the following?
</blockquote></details>

I already did. But turns out only in the next PR :)
Moved it here now.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1521#-:-NKMyts5AXnvKdFWL5pV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 20 of 20 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1521)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
