### PR TITLE
Orizi/exec info v2

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4242)

### CODE REVIEW

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4242)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp and @liorgold2)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4242)* status: all files reviewed, 2 unresolved discussions (waiting on @ArielElp and @orizi)

___
*[`corelib/src/starknet/info.cairo` line 112 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4242#-NgYuYdO5KW7qb0F_t55:-NgYuYdO5KW7qb0F_t56:bf60gvj) ([raw file](https://github.com/starkware-libs/cairo/blob/32524b99945a062f43ec807e527071dc12301369/corelib/src/starknet/info.cairo#L112)):*
> ```Cairo
>         tip: u128,
>         // If specified, the paymaster should pay for the execution of the tx.
>         // The data includes the address of the paymaster sponsoring the transaction, followed by extra
> ```

Line too long
___
*[`corelib/src/starknet/info.cairo` line 131 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4242#-NgYuircAqECghT2tAXm:-NgYuircAqECghT2tAXn:b-jxzfnz) ([raw file](https://github.com/starkware-libs/cairo/blob/32524b99945a062f43ec807e527071dc12301369/corelib/src/starknet/info.cairo#L131)):*
> ```Cairo
>         max_amount: u128,
>         // The maximum price the user is willing to pay for the resource unit.
>         max_price_per_unit: u128,
> ```

I think that one of these two is actually `u64`. Does it matter?



_Code quote:_
```Cairo
        // The maximum amount of the resource allowed for usage during the execution.
        max_amount: u128,
        // The maximum price the user is willing to pay for the resource unit.
        max_price_per_unit: u128,
```

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4242)* status: all files reviewed, 4 unresolved discussions (waiting on @ArielElp and @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/getter.rs` line 180 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4242#-NgYwBUtDfeDFBAYT8c6:-NgYwBUtDfeDFBAYT8c7:bo5hkzz) ([raw file](https://github.com/starkware-libs/cairo/blob/32524b99945a062f43ec807e527071dc12301369/crates/cairo-lang-sierra/src/extensions/modules/starknet/getter.rs#L180)):*
> ```XML
> ) -> Result<ConcreteTypeId, SpecializationError> {
>     let resource_bounds_array_ty =
>         context.get_wrapped_concrete_type(ArrayType::id(), get_resource_bounds_type(context)?)?;
> ```

Don't we have `array_ty` function? If not we should.
`span_ty` will be nice as well (can get the full name string as a parameter)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 6 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4242)* status: all files reviewed, 4 unresolved discussions (waiting on @ArielElp and @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4242)* status: all files reviewed, 4 unresolved discussions (waiting on @ArielElp and @liorgold2)

___
*[`corelib/src/starknet/info.cairo` line 112 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4242#-NgYuYdO5KW7qb0F_t55:-NgZizT80vm7GkXD59SX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/32524b99945a062f43ec807e527071dc12301369/corelib/src/starknet/info.cairo#L112)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Line too long
</blockquote></details>

Done.
___
*[`corelib/src/starknet/info.cairo` line 131 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4242#-NgYuircAqECghT2tAXm:-NgZj-VW2hh0FnNbqoho:b-e1z04d) ([raw file](https://github.com/starkware-libs/cairo/blob/32524b99945a062f43ec807e527071dc12301369/corelib/src/starknet/info.cairo#L131)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

I think that one of these two is actually `u64`. Does it matter?
</blockquote></details>

This should be decided specifically somewhere else.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/getter.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4242#-NgYvBMSBvDnNu5fJrfU:-NgZjJr03EKTlHrHmS3u:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/32524b99945a062f43ec807e527071dc12301369/crates/cairo-lang-sierra/src/extensions/modules/starknet/getter.rs#L76)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

(alternatively `def` -> `definition`)
Same below
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/getter.rs` line 180 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4242#-NgYwBUtDfeDFBAYT8c6:-NgZjLAe4BVzE9u0aQnO:bw3owuj) ([raw file](https://github.com/starkware-libs/cairo/blob/32524b99945a062f43ec807e527071dc12301369/crates/cairo-lang-sierra/src/extensions/modules/starknet/getter.rs#L180)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Don't we have `array_ty` function? If not we should.
`span_ty` will be nice as well (can get the full name string as a parameter)
</blockquote></details>

about the array - not for this PR.
span_ty Done.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4242)* status: 8 of 10 files reviewed, 3 unresolved discussions (waiting on @ArielElp, @ilyalesokhin-starkware, and @orizi)

___
*[`corelib/src/starknet/info.cairo` line 131 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4242#-NgYuircAqECghT2tAXm:-NgltomP94kGZaj6uJh2:b9y1s5h) ([raw file](https://github.com/starkware-libs/cairo/blob/32524b99945a062f43ec807e527071dc12301369/corelib/src/starknet/info.cairo#L131)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

This should be decided specifically somewhere else.
</blockquote></details>

`max_amount` is `u64`

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4242)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp and @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4242)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @ArielElp and @liorgold2)

___
*[`corelib/src/starknet/info.cairo` line 131 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4242#-NgYuircAqECghT2tAXm:-NgoGNL67yKBsxYmfxh1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/32524b99945a062f43ec807e527071dc12301369/corelib/src/starknet/info.cairo#L131)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

`max_amount` is `u64`
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4242#-:-NgrWHZGEchgElcuwJWO:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp and @liorgold2)

**Review by ilyalesokhin-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4242)* status: all files reviewed, 2 unresolved discussions (waiting on @ArielElp, @liorgold2, and @orizi)

___
*[`corelib/src/starknet/info.cairo` line 47 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4242#-Ngrby-6B1UZT5o-XaJm:-Ngrby-6B1UZT5o-XaJn:bf0qj1k) ([raw file](https://github.com/starkware-libs/cairo/blob/7faf81a250290a0001c859832b2f17a755e6272a/corelib/src/starknet/info.cairo#L47)):*
> ```Cairo
> fn get_execution_info() -> Box<ExecutionInfo> {
>     get_execution_info_syscall().unwrap_syscall()
> }
> ```

You are going to update it in the followup PR?



_Code quote:_
```Cairo
fn get_execution_info() -> Box<ExecutionInfo> {
    get_execution_info_syscall().unwrap_syscall()
}
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4242)* status: all files reviewed, 2 unresolved discussions (waiting on @ArielElp, @ilyalesokhin-starkware, and @liorgold2)

___
*[`corelib/src/starknet/info.cairo` line 47 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4242#-Ngrby-6B1UZT5o-XaJm:-Ngspu0r7e2_Ghlysd8j:b-3objwv) ([raw file](https://github.com/starkware-libs/cairo/blob/7faf81a250290a0001c859832b2f17a755e6272a/corelib/src/starknet/info.cairo#L47)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

You are going to update it in the followup PR?
</blockquote></details>

not currently - this just adds basic support for  the libfunc - does not move the users to use the new version (as it is even not supported on starknet)

**Review by liorgold2 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4242)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp)

**Pull request merged**
