### PR TITLE
Prevent closures from compiling.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6203)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1687 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6203#-O49f81j4Cw5VRdiyqzE:-O49f81j4Cw5VRdiyqzF:b-e9ezuk) ([raw file](https://github.com/starkware-libs/cairo/blob/46fa56055289b34182bcd64da4cfec48f1cd9eb4/crates/cairo-lang-lowering/src/lower/mod.rs#L1687)):*
> ```XML
>     let usage = ctx.usages.usages[&expr_id].clone();
> 
>     ctx.diagnostics.report(expr.stable_ptr, LoweringDiagnosticKind::Unsupported);
> ```

I think the code is currently safe even without it, but once I add destructors, we will get panics in sierra-gen.



_Code quote:_
```XML
ctx.diagnostics.report(expr.stable_ptr, LoweringDiagnosticKind::Unsupported);
```

**Review by TomerStarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6203#-:-O49fZUsB40V5aYwZgKP:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6203#-:-O49gYh9AfoU4FFb6RpN:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by TomerStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6203)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1687 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6203#-O49f81j4Cw5VRdiyqzE:-O49gitN9H8dHGKNxH_R:b-gejrvv) ([raw file](https://github.com/starkware-libs/cairo/blob/46fa56055289b34182bcd64da4cfec48f1cd9eb4/crates/cairo-lang-lowering/src/lower/mod.rs#L1687)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I think the code is currently safe even without it, but once I add destructors, we will get panics in sierra-gen.
</blockquote></details>

It does panic right now when I try to test closures

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1687 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6203#-O49f81j4Cw5VRdiyqzE:-O49gxrx4eN3HWbu5B3r:b-n80u2k) ([raw file](https://github.com/starkware-libs/cairo/blob/46fa56055289b34182bcd64da4cfec48f1cd9eb4/crates/cairo-lang-lowering/src/lower/mod.rs#L1687)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

It does panic right now when I try to test closures
</blockquote></details>

can you give list the test case that panics?

**Review by TomerStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6203)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1687 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6203#-O49f81j4Cw5VRdiyqzE:-O49hUI27jIkVm_ix2mv:bd1bt71) ([raw file](https://github.com/starkware-libs/cairo/blob/46fa56055289b34182bcd64da4cfec48f1cd9eb4/crates/cairo-lang-lowering/src/lower/mod.rs#L1687)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

can you give list the test case that panics?
</blockquote></details>

When I add this to my pr it panics



_Code snippet:_
```XML
let c = |x: felt252| x + 1;

assert\_eq!(c(1), 2);
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1687 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6203#-O49f81j4Cw5VRdiyqzE:-O49iveb7-NF2AVQh8AG:bobpyql) ([raw file](https://github.com/starkware-libs/cairo/blob/46fa56055289b34182bcd64da4cfec48f1cd9eb4/crates/cairo-lang-lowering/src/lower/mod.rs#L1687)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

When I add this to my pr it panics
</blockquote></details>

Ok, the issue is that you have another way of destroying the capture.

**Pull request merged**
