### PR TITLE
Updated u256_div_mod according to audit.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3509)

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3509)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned256.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3509#-NYqwqnvAfXkZVcC4QwP:-NYqwqnvAfXkZVcC4QwQ:b-6dhpxl) ([raw file](https://github.com/starkware-libs/cairo/blob/a640d675f377c77d6ba9816389d2767ca2052ad9/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned256.rs#L93)):*
> ```XML
>         assert quotient1 = *(range_check++);
>         assert remainder0 = *(range_check++);
>         assert remainder1 = *(range_check++);
> ```

Audit:
`one of the range check is not necessary since the value is checked to be 0.`

Can you please expand?
@liorgold2 

Also - is it not true in `u512_divmod`?



_Code quote:_
```XML
        assert remainder1 = *(range_check++);
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3509)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned256.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3509#-NYrLQUaDJevjDc24P5r:-NYrLQUaDJevjDc24P5s:b-b8huoc) ([raw file](https://github.com/starkware-libs/cairo/blob/a640d675f377c77d6ba9816389d2767ca2052ad9/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned256.rs#L74)):*
> ```XML
>         // Remainder 128-bit limbs.
>         tempvar remainder0;
>         tempvar remainder1;
> ```

moving these to the end of the allocation seems very annoying, while also we still need the guarantee validation call right after - still seems like too much work for a minor gai 



_Code quote:_
```XML
        // Quotient 128-bit limbs.
        tempvar quotient0;
        tempvar quotient1;
        // Remainder 128-bit limbs.
        tempvar remainder0;
        tempvar remainder1;
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned256.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3509#-NYqwqnvAfXkZVcC4QwP:-NYrKv7--x3G8SS4h5Rr:be29lkm) ([raw file](https://github.com/starkware-libs/cairo/blob/a640d675f377c77d6ba9816389d2767ca2052ad9/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned256.rs#L93)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Audit:
`one of the range check is not necessary since the value is checked to be 0.`

Can you please expand?
@liorgold2 

Also - is it not true in `u512_divmod`?
</blockquote></details>

Oh - it is because of the case where q1 == 0.
I don't see a way that keeps the code efficient and balanced.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3509)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned256.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3509#-NYqwqnvAfXkZVcC4QwP:-NYvYGxa2pwnYZkWxtS_:b-tvjeqy) ([raw file](https://github.com/starkware-libs/cairo/blob/a640d675f377c77d6ba9816389d2767ca2052ad9/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned256.rs#L93)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Oh - it is because of the case where q1 == 0.
I don't see a way that keeps the code efficient and balanced.
</blockquote></details>

IIRC That's what we meant and we also thought we can;t balance the range check ptr.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3509#-:-NYvY_qY7Z9LEsr1toiW:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3509)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3509)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned256.rs` line 103 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3509#-NZVp7Z09pvCrvKpQuax:-NZVppoL9Gzyjs8DgfTJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/73e30b5daf80c2b3c69af547a31ec65e9f14a033/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned256.rs#L103)):*
> ```XML
>         jump After;
>     HighDiff:
>         // Aligning the branches.
> ```

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned256.rs` line 106 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3509#-NZVpIfw3AM1x0WBqRyp:-NZVpqBV-GJFyV8GNQ-G:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/73e30b5daf80c2b3c69af547a31ec65e9f14a033/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned256.rs#L106)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Consider putting `tempvar diff0;` and `tempvar diff0_min_1` above the `jump` as in the other libfunc.
</blockquote></details>

Done.

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3509#-:-NZWZazUBkQyCd0lFrY5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
