### PR TITLE
Removed unused boolean in sierra-gen

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2318)

### CODE REVIEW

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2318)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2318#-NPO1hH3Eux-QaIFwuOe:-NPO1hH3Eux-QaIFwuOf:b-3yf84a) (no related file):*
change target branch

___

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2318#-:-NPODD2i7-27lrO1CECY:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2318)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-sierra-generator/src/block_generator.rs` line 143 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2318#-NPWNy7P1wOEzsySVubX:-NPWNy7P1wOEzsySVubY:b-emdvki) ([raw file](https://github.com/starkware-libs/cairo/blob/f59329d9aab6accb900db0de16eef91f6da6433f/crates/cairo-lang-sierra-generator/src/block_generator.rs#L143)):*
> ```XML
>                 }
>             });
>             Ok(statements)
> ```

Can you move this outside of the match?



_Code quote:_
```XML
Ok(statements)
```

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2318)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2318)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
