### PR TITLE
Fixed bug of bad diagnostics when a use points to something that does…

### PR DESCRIPTION
**Pull request by yuvalsw**
…n't exist

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4175)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4175)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4175#-NfgFflMEAb_02VNBywo:-NfgFflMEAb_02VNBywp:bjk4a8g) (no related file):*
how do we know all these new `unwrap`s are fine?

___

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4175)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Comment by yuvalsw** [comment]
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

how do we know all these new `unwrap`s are fine?
</blockquote></details>

like we know others are. This is where we don't expect errors, and if we do, crashing should be OK.
Of course - we need to go over them carefully like we do for any other unwrap. This is why I added you both, hoping you review each one carefully

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4175)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4175#-NfgFflMEAb_02VNBywo:-Nfk74xy6vzLCyMQbnza:b-hnntc1) (no related file):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

like we know others are. This is where we don't expect errors, and if we do, crashing should be OK.
Of course - we need to go over them carefully like we do for any other unwrap. This is why I added you both, hoping you review each one carefully
</blockquote></details>

I understand all the switching of the `?` with continues.
but the `unwrap`s are very unclear - as this are not from a previous layer on the same data that necessarily passed without diagnostics - which is when we know it won't fail.
this just calls the `defs` base crate, which do not provide basic diagnostics for all, or other parts of the semantic that we don't know has passed.
each unwrap here unfortunately needs to be explicitly explain or reverted to a `?`.

___

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4175)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4175)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4175#-NfgFflMEAb_02VNBywo:-Nfohk1aAYyR0QGEpksW:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I understand all the switching of the `?` with continues.
but the `unwrap`s are very unclear - as this are not from a previous layer on the same data that necessarily passed without diagnostics - which is when we know it won't fail.
this just calls the `defs` base crate, which do not provide basic diagnostics for all, or other parts of the semantic that we don't know has passed.
each unwrap here unfortunately needs to be explicitly explain or reverted to a `?`.
</blockquote></details>

Done.

___

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4175)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 267 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4175#-Nfou7bIBhNxFB8X_Fgn:-Nfou7bJ5xUx9ebjKyCU:b-ncolu2) ([raw file](https://github.com/starkware-libs/cairo/blob/040b849f7584f6f691b3b0616faa55d2a3866e4d/crates/cairo-lang-semantic/src/items/imp.rs#L267)):*
> ```XML
> pub fn impl_def_trait(db: &dyn SemanticGroup, impl_def_id: ImplDefId) -> Maybe<TraitId> {
>     let module_file_id = impl_def_id.module_file_id(db.upcast());
>     let mut diagnostics = SemanticDiagnostics::new(module_file_id.file_id(db.upcast()).unwrap());
> ```

Should be reverted.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4175)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4175)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 267 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4175#-Nfou7bIBhNxFB8X_Fgn:-NfpbNq41QvbZs738Nsr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/040b849f7584f6f691b3b0616faa55d2a3866e4d/crates/cairo-lang-semantic/src/items/imp.rs#L267)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Should be reverted.
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4175)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4175)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4175#-:-Nfpd31D4_jTImed3-97:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
