### PR TITLE
Fix missing outer docs in case of being between attributes

### PR DESCRIPTION
**Pull request by wawel37**
Fixes: [#6535](https://github.com/starkware-libs/cairo/issues/6535) and [Scarb #1707](https://github.com/software-mansion/scarb/issues/1707)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6603)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, @piotmag769, and @wawel37)

___
*[`crates/cairo-lang-doc/src/db.rs` line 319 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6603#-OB5Lf4RBeKWetOOHu20:-OB5Lf4RBeKWetOOHu21:b-9v1m6) ([raw file](https://github.com/starkware-libs/cairo/blob/1009ee874c725a3806052231f909b73cf9bdefa1/crates/cairo-lang-doc/src/db.rs#L319)):*
> ```XML
>         .lines()
>         .filter(|line| !line.trim().is_empty())
>         // Takes all the lines before the definition. Anything other than doc comments will be filtered out later.
> ```

`./scripts/rust_fmt.sh`

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6603#-:-OB5NM4zCs1tKeYCK_o6:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @piotmag769, and @wawel37)

**Review by Draggu — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6603)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @piotmag769, and @wawel37)

___
*[`crates/cairo-lang-doc/src/db.rs` line 320 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6603#-OB6Db9p7aW91XgB-d1B:-OB6Db9p7aW91XgB-d1C:brd0128) ([raw file](https://github.com/starkware-libs/cairo/blob/1009ee874c725a3806052231f909b73cf9bdefa1/crates/cairo-lang-doc/src/db.rs#L320)):*
> ```XML
>         .filter(|line| !line.trim().is_empty())
>         // Takes all the lines before the definition. Anything other than doc comments will be filtered out later.
>         .take_while_ref(|line| is_comment_line(line) || line.starts_with("#"))
> ```

If there is white space before `#` it will fail.

**Review by wawel37 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6603)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-doc/src/db.rs` line 319 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6603#-OB5Lf4RBeKWetOOHu20:-OB6FuS-0pn5N9ApArkB:b-lzqjp8) ([raw file](https://github.com/starkware-libs/cairo/blob/1009ee874c725a3806052231f909b73cf9bdefa1/crates/cairo-lang-doc/src/db.rs#L319)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

`./scripts/rust_fmt.sh`
</blockquote></details>

I ran it and nothing changed. What's wrong with this format? Should the comment be on the left side, right behind the code line?
___
*[`crates/cairo-lang-doc/src/db.rs` line 320 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6603#-OB6Db9p7aW91XgB-d1B:-OB6FuJ78_15aR-geg19:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1009ee874c725a3806052231f909b73cf9bdefa1/crates/cairo-lang-doc/src/db.rs#L320)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

If there is white space before `#` it will fail.
</blockquote></details>

Done.

**Review by Draggu — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6603#-:-OB6MSwC0YE7JDzPThtC:bnfp4nl)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @mkaput, @orizi, and @piotmag769)

**Review by piotmag769 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6603#-:-OB6ZcZ22M4z_rzIFTSZ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae and @orizi)

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6603)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae and @orizi)

___
*[`crates/cairo-lang-doc/src/db.rs` line 319 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6603#-OB5Lf4RBeKWetOOHu20:-OBA8mUX9mSZtf1p_qbt:b-1782na) ([raw file](https://github.com/starkware-libs/cairo/blob/1009ee874c725a3806052231f909b73cf9bdefa1/crates/cairo-lang-doc/src/db.rs#L319)):*
<details><summary><i>Previously, wawel37 (Mateusz Kowalski) wrote…</i></summary><blockquote>

I ran it and nothing changed. What's wrong with this format? Should the comment be on the left side, right behind the code line?
</blockquote></details>

I guess line is to long. Just put each sentence in separate lines and you should be good to go (btw, latest intellij has this breaking built-in, it's called Apply Structural Wrapping)

**Review by wawel37 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6603)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-doc/src/db.rs` line 319 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6603#-OB5Lf4RBeKWetOOHu20:-OBAPWPl-7_VuzOF__G8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1009ee874c725a3806052231f909b73cf9bdefa1/crates/cairo-lang-doc/src/db.rs#L319)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I guess line is to long. Just put each sentence in separate lines and you should be good to go (btw, latest intellij has this breaking built-in, it's called Apply Structural Wrapping)
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6603#-:-OBAqN1C66k7Osh-0L4N:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae)

**Review by mkaput — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6603)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae)

**Pull request merged**
