### PR TITLE
Modularize SierraCasmRunner and casm_run

### PR DESCRIPTION
**Pull request by cptartur**
We want to use some functionalities of SierraCasmRunner in Starknet Foundry but need access to some lower-level functionalities. This PR exposes some parts of SierraCasmRunner as static methods so they can be used directly while preserving top-level APIs. It also introduces similar changes to casm_run.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4644)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4644)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @cptartur)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 383 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4644#-NmPXncE4iYF_j5JYmld:-NmPXncE4iYF_j5JYmle:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/18bf29e5c37e337949ccd112666aac36e11951b5/crates/cairo-lang-runner/src/lib.rs#L383)):*
> ```XML
>     }
> 
>     fn generic_id_and_size_from_concrete(
> ```

doc
___
*[`crates/cairo-lang-runner/src/lib.rs` line 449 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4644#-NmPYEBfDP10hIGUeh9r:-NmPYEBfDP10hIGUeh9s:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/18bf29e5c37e337949ccd112666aac36e11951b5/crates/cairo-lang-runner/src/lib.rs#L449)):*
> ```XML
>                 }
>             }
>             ap_offset += i16::try_from(1 + values.len()).unwrap();
> ```





_Suggestion:_
```XML
                let arr_at: i16 = (i + 1).into_or_panic();
                casm_extend! {ctx,
                    [ap + 0] = (v.to_bigint());
                    [ap + 0] = [[ap - arr_at] + i.into_or_panic()], ap++;
                }
            }
            ap_offset += (1 + values.len()).into_or_panic();
```
___
*[`crates/cairo-lang-runner/src/lib.rs` line 591 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4644#-NmPZSbO-dgaWGHZKXPm:-NmPZSbO-dgaWGHZKXPn:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/18bf29e5c37e337949ccd112666aac36e11951b5/crates/cairo-lang-runner/src/lib.rs#L591)):*
> ```XML
> }
> 
> pub fn initialize_vm(context: RunFunctionContext<'_>) -> Result<(), Box<CairoRunError>> {
> ```

doc

**Review by cptartur — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4644)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 383 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4644#-NmPXncE4iYF_j5JYmld:-NnEJAsvEp4Xn2M4B248:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/18bf29e5c37e337949ccd112666aac36e11951b5/crates/cairo-lang-runner/src/lib.rs#L383)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runner/src/lib.rs` line 449 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4644#-NmPYEBfDP10hIGUeh9r:-NnEJAAL9zRPy0Sv7xDt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/18bf29e5c37e337949ccd112666aac36e11951b5/crates/cairo-lang-runner/src/lib.rs#L449)):*
> ```XML
>                 }
>             }
>             ap_offset += i16::try_from(1 + values.len()).unwrap();
> ```

Done.
___
*[`crates/cairo-lang-runner/src/lib.rs` line 591 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4644#-NmPZSbO-dgaWGHZKXPm:-NnEJ3YN4S75KlVEqux9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/18bf29e5c37e337949ccd112666aac36e11951b5/crates/cairo-lang-runner/src/lib.rs#L591)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4644)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @cptartur)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 2132 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4644#-NnEM-nh9i77Yt1CYUSU:-NnEM-nh9i77Yt1CYUSV:bcjeoay) ([raw file](https://github.com/starkware-libs/cairo/blob/ee1cef4abbb176c39e28dc4f477ed03726ece336/crates/cairo-lang-runner/src/casm_run/mod.rs#L2132)):*
> ```XML
> }
> 
> pub fn build_program_data<'a, Instructions>(instructions: Instructions) -> Vec<MaybeRelocatable>
> ```

rebase - there's now AssembledCairoProgram

**Comment by cptartur** [comment]
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 2132 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4644#-NnEM-nh9i77Yt1CYUSU:-NnEPP23Dqsz_I6yKACL:bpchavd) ([raw file](https://github.com/starkware-libs/cairo/blob/ee1cef4abbb176c39e28dc4f477ed03726ece336/crates/cairo-lang-runner/src/casm_run/mod.rs#L2132)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rebase - there's now AssembledCairoProgram
</blockquote></details>

Is it applicable here? We use data from `build_program_data` to construct `cairo-vm`'s `Program` and then `CairoRunner`.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4644)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @cptartur)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 2132 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4644#-NnEM-nh9i77Yt1CYUSU:-NnERd0pCtgHP1Xv4YZ_:bnkfzyb) ([raw file](https://github.com/starkware-libs/cairo/blob/ee1cef4abbb176c39e28dc4f477ed03726ece336/crates/cairo-lang-runner/src/casm_run/mod.rs#L2132)):*
<details><summary><i>Previously, cptartur (Artur Michałek) wrote…</i></summary><blockquote>

Is it applicable here? We use data from `build_program_data` to construct `cairo-vm`'s `Program` and then `CairoRunner`.
</blockquote></details>

it is a must for it.
it will include constant memory when relevant and possible other things at some point.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 2094 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4644#-NnER_BQ48PisoanTxlv:-NnER_BR6HOqP3HmcngQ:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/e317a561d690f2ab70e5eb956e5726d083d0af12/crates/cairo-lang-runner/src/casm_run/mod.rs#L2094)):*
> ```XML
> type RunFunctionRes = (Vec<Option<Felt252>>, usize);
> 
> pub fn run_function_with_runner(
> ```

doc

**Comment by cptartur** [comment]
*[`crates/cairo-lang-runner/src/lib.rs` line 614 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4644#-NnFA2GI8bV8taXLKlKh:-NnIzK870QHAVULBuTsp:b2ux83d) ([raw file](https://github.com/starkware-libs/cairo/blob/1e2b0ea5cfcf0a0f221cfa7e4c4a22a129daac96/crates/cairo-lang-runner/src/lib.rs#L614)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you HAVE TO use the version from the AssemebledCairoProgram - otherwise you are missing instructions.
</blockquote></details>

It should be using `AssemebledCairoProgram` now

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4644)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @cptartur)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 146 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4644#-NnM0bm59CTo9vst0UTF:-NnM0bm59CTo9vst0UTG:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/61998e80259545e6cef4f540b0dce7ad93aa836d/crates/cairo-lang-runner/src/lib.rs#L146)):*
> ```XML
> }
> 
> pub fn hints_from_assembled_program(
> ```

doc
___
*[`crates/cairo-lang-runner/src/lib.rs` line 635 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4644#-NnM0lWE7hnRur3AtvEz:-NnM0lWE7hnRur3AtvF-:b-ddigk9) ([raw file](https://github.com/starkware-libs/cairo/blob/61998e80259545e6cef4f540b0dce7ad93aa836d/crates/cairo-lang-runner/src/lib.rs#L635)):*
> ```XML
> }
> 
> pub fn assemble_program(
> ```

doc.
and probably just add an `assemble_ex` to the original program that accepts a header and a footer instead.
___
*[`crates/cairo-lang-runner/src/casm_run/test.rs` line 20 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4644#-NnM0uhy3JL_NdNVYy18:-NnM0uhy3JL_NdNVYy19:bz7z9as) ([raw file](https://github.com/starkware-libs/cairo/blob/61998e80259545e6cef4f540b0dce7ad93aa836d/crates/cairo-lang-runner/src/casm_run/test.rs#L20)):*
> ```XML
> use crate::{build_hints_dict, CairoHintProcessor, StarknetState};
> 
> pub fn assemble_instructions<'b>(
> ```

this should not exist.

**Review by drknzz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4644)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @cptartur and @orizi)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 146 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4644#-NnM0bm59CTo9vst0UTF:-NoBYR8k1fPT1MIkJsmt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/61998e80259545e6cef4f540b0dce7ad93aa836d/crates/cairo-lang-runner/src/lib.rs#L146)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runner/src/lib.rs` line 635 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4644#-NnM0lWE7hnRur3AtvEz:-NoBY_8BB-ab2OkOautB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/61998e80259545e6cef4f540b0dce7ad93aa836d/crates/cairo-lang-runner/src/lib.rs#L635)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc.
and probably just add an `assemble_ex` to the original program that accepts a header and a footer instead.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 2094 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4644#-NnER_BQ48PisoanTxlv:-NoBYaGS4U_Ukr2iRGG2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e317a561d690f2ab70e5eb956e5726d083d0af12/crates/cairo-lang-runner/src/casm_run/mod.rs#L2094)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runner/src/casm_run/test.rs` line 20 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4644#-NnM0uhy3JL_NdNVYy18:-NoBYci93-D3scrWKaHQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/61998e80259545e6cef4f540b0dce7ad93aa836d/crates/cairo-lang-runner/src/casm_run/test.rs#L20)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this should not exist.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r6, 1 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4644)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @cptartur and @drknzz)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 303 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4644#-NoCRoRVA3DYZiUjufSp:-NoCRoRVA3DYZiUjufSq:b-cnv71s) ([raw file](https://github.com/starkware-libs/cairo/blob/d66659a8a9fb47e5ba1636e12a75ad64f9bf8e1b/crates/cairo-lang-runner/src/lib.rs#L303)):*
> ```XML
>                 } else {
>                     None
>                 }
> ```

if you are already changing this.



_Suggestion:_
```XML
                (info.long_id.generic_id == *ty).then_some(info)
```
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 2138 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4644#-NoCTWW2BG_CJ2tj8DLh:-NoCTWW2BG_CJ2tj8DLi:b9secd2) ([raw file](https://github.com/starkware-libs/cairo/blob/d66659a8a9fb47e5ba1636e12a75ad64f9bf8e1b/crates/cairo-lang-runner/src/casm_run/mod.rs#L2138)):*
> ```XML
> pub fn run_function<'a, 'b: 'a, Instructions>(
>     vm: &mut VirtualMachine,
>     instructions: Instructions,
> ```

this is no longer a good name.
probably bytecode.



_Suggestion:_
```XML
    bytecode: impl Iterator<Item = &'a BigInt> + Clone,
```
___
*[`crates/cairo-lang-runner/src/casm_run/test.rs` line 123 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4644#-NoCTt-m9iFWOrwljSTy:-NoCTt-m9iFWOrwljSTz:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d66659a8a9fb47e5ba1636e12a75ad64f9bf8e1b/crates/cairo-lang-runner/src/casm_run/test.rs#L123)):*
> ```XML
>         function.instructions.iter().flat_map(|is| is.assemble().encode()).collect();
> 
>     let (cells, ap) = run_function(
> ```





_Suggestion:_
```XML
    };
    let bytecode =
        casm.instructions.iter().flat_map(|instruction| is.assemble().encode());

    let (cells, ap) = run_function(
```
___
*[`crates/cairo-lang-runner/src/casm_run/test.rs` line 160 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4644#-NoCTjIq7mH9fg23oo7h:-NoCTjIq7mH9fg23oo7i:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d66659a8a9fb47e5ba1636e12a75ad64f9bf8e1b/crates/cairo-lang-runner/src/casm_run/test.rs#L160)):*
> ```XML
>     let (memory, ap) = run_function(
>         &mut VirtualMachine::new(true),
>         instructions.iter(),
> ```





_Suggestion:_
```XML
    };
    let bytecode =
        casm.instructions.iter().flat_map(|instruction| is.assemble().encode());

    let (memory, ap) = run_function(
        &mut VirtualMachine::new(true),
        bytecode,
```

**Review by drknzz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4644)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 303 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4644#-NoCRoRVA3DYZiUjufSp:-NoGoW7c2n4brC5HBZkp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d66659a8a9fb47e5ba1636e12a75ad64f9bf8e1b/crates/cairo-lang-runner/src/lib.rs#L303)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

if you are already changing this.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 2138 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4644#-NoCTWW2BG_CJ2tj8DLh:-NoGqgTJ5RZoFhhGf6y1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d66659a8a9fb47e5ba1636e12a75ad64f9bf8e1b/crates/cairo-lang-runner/src/casm_run/mod.rs#L2138)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is no longer a good name.
probably bytecode.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runner/src/casm_run/test.rs` line 123 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4644#-NoCTt-m9iFWOrwljSTy:-NoH0mx-94lzv7khKoRm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d66659a8a9fb47e5ba1636e12a75ad64f9bf8e1b/crates/cairo-lang-runner/src/casm_run/test.rs#L123)):*
> ```XML
>         function.instructions.iter().flat_map(|is| is.assemble().encode()).collect();
> 
>     let (cells, ap) = run_function(
> ```

Done.
___
*[`crates/cairo-lang-runner/src/casm_run/test.rs` line 160 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4644#-NoCTjIq7mH9fg23oo7h:-NoH0_qgA5O7rmm9plRR:bfi1kks) ([raw file](https://github.com/starkware-libs/cairo/blob/d66659a8a9fb47e5ba1636e12a75ad64f9bf8e1b/crates/cairo-lang-runner/src/casm_run/test.rs#L160)):*
> ```XML
>     let (memory, ap) = run_function(
>         &mut VirtualMachine::new(true),
>         instructions.iter(),
> ```

run_function expects references, so I left the collect

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4644#-:-NoH7z5FClDc0yua7JaG:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cptartur)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4644)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cptartur)

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4644)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cptartur)

**Pull request merged**
