### PR TITLE
Added `derive` macro doc.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #3088
- #3080 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3080)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3080)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @JameStark and @orizi)

___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/derive-macro.adoc` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3080#-NUzgZrM1b2IRRWH7nLL:-NUzgZrM1b2IRRWH7nLM:b-mwoqbb) ([raw file](https://github.com/starkware-libs/cairo/blob/d892c282fbd2524fb2345508358edc4f712fd117/docs/reference/src/components/cairo/modules/language_constructs/pages/derive-macro.adoc#L3)):*
> ```AsciiDoc
> = Derive macro
> 
> The _derive macro_ is added to a type definition to provide it with some basic implementations. The derive macro is used to implement traits for structs and enums automatically. The compiler will generate the code for the methods of the traits that have been implemented via derive.
> ```

Try to keep lines length < 100chars

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3080)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @JameStark and @orizi)

___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/derive-macro.adoc` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3080#-NUzguQBAgb-do-Kdgjj:-NUzguQBAgb-do-Kdgjk:byck3af) ([raw file](https://github.com/starkware-libs/cairo/blob/d892c282fbd2524fb2345508358edc4f712fd117/docs/reference/src/components/cairo/modules/language_constructs/pages/derive-macro.adoc#L14)):*
> ```AsciiDoc
> }
> ----
> ```

Add a TODO to mention derives on generic types

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3080)* status: all files reviewed, 3 unresolved discussions (waiting on @JameStark and @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3080)* status: all files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/derive-macro.adoc` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3080#-NUzgZrM1b2IRRWH7nLL:-NUzit3A-vrb4qdn2_8A:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d892c282fbd2524fb2345508358edc4f712fd117/docs/reference/src/components/cairo/modules/language_constructs/pages/derive-macro.adoc#L3)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Try to keep lines length < 100chars
</blockquote></details>

Done.
___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/derive-macro.adoc` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3080#-NUzglRk8X-RkQHorrIc:-NUzj5XB6m_WBH4ewDSI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d892c282fbd2524fb2345508358edc4f712fd117/docs/reference/src/components/cairo/modules/language_constructs/pages/derive-macro.adoc#L3)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Bad copilot! Bad!
</blockquote></details>

Done.
___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/derive-macro.adoc` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3080#-NUzguQBAgb-do-Kdgjj:-NUzlM_09b-XY-HlSEwv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d892c282fbd2524fb2345508358edc4f712fd117/docs/reference/src/components/cairo/modules/language_constructs/pages/derive-macro.adoc#L14)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Add a TODO to mention derives on generic types
</blockquote></details>

Done.

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3080)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3080#-:-NUztwAK06X2yrsVs-iD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
