### PR TITLE
Using anonymous impl param when possible.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4054)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4054)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/hash.cairo` line 23 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4054#-Ne7evYxAap2ATD7XivO:-Ne7evYyAQn9IV3_RST6:b-bd517b) ([raw file](https://github.com/starkware-libs/cairo/blob/ce18f4e0492db3ffb3e555cfc5b3e69b84789e47/corelib/src/hash.cairo#L23)):*
> ```Cairo
> 
> /// Implementation of `LegacyHash` for types that have `Hash` for backwards compatibility.
> impl LegacyHashForHash<T, +Hash<T, pedersen::HashState, _>> of LegacyHash<T> {
> ```

can't these '_'s  be omitted?



_Code quote:_
```Cairo
, _
```
___
*[`corelib/src/serde.cairo` line 106 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4054#-Ne7fhyb-TnMxHfRu2IG:-Ne7fhyb-TnMxHfRu2IH:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ce18f4e0492db3ffb3e555cfc5b3e69b84789e47/corelib/src/serde.cairo#L106)):*
> ```Cairo
>         fn deserialize(ref serialized: Span<felt252>) -> Option<T> {
>             Option::Some((TryInto::try_into(*serialized.pop_front()?))?)
>         }
> ```





_Suggestion:_
```Cairo
        fn serialize(self: @T, ref output: Array<felt252>) {
            output.append((*self).into());
        }
        #[inline(always)]
        fn deserialize(ref serialized: Span<felt252>) -> Option<T> {
            Option::Some((*serialized.pop_front()?).into()?)
        }
```
___
*[`corelib/src/starknet/secp256_trait.cairo` line 63 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4054#-Ne7gSJQC2MKH16-TcHT:-Ne7gSJQC2MKH16-TcHU:b-r5gmxt) ([raw file](https://github.com/starkware-libs/cairo/blob/ce18f4e0492db3ffb3e555cfc5b3e69b84789e47/corelib/src/starknet/secp256_trait.cairo#L63)):*
> ```Cairo
>     // where the divisions by `r` are modulo `N` (the size of the curve).
> 
>     let n_nz = Secp256Trait::<Secp256Point>::get_curve_size().try_into().unwrap();
> ```

isn't it better in this case to just leave the name?
same in lines 81 and 127



_Code quote:_
```Cairo
Secp256Trait::<Secp256Point>::
```
___
*[`corelib/src/starknet/storage_access.cairo` line 514 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4054#-Ne7griYD9eLsVBeycp2:-Ne7griYD9eLsVBeycp3:b-9ap8lx) ([raw file](https://github.com/starkware-libs/cairo/blob/ce18f4e0492db3ffb3e555cfc5b3e69b84789e47/corelib/src/starknet/storage_access.cairo#L514)):*
> ```Cairo
>         Store::<E0>::size() + Store::<E1>::size()
>     }
> }
> ```

same here and below. isn't it better to leave the names?



_Code quote:_
```Cairo
impl TupleSize2Store<E0, E1, +Store<E0>, +Drop<E0>, +Store<E1>, +Drop<E1>> of Store<(E0, E1)> {
    #[inline(always)]
    fn read(address_domain: u32, base: StorageBaseAddress) -> SyscallResult<(E0, E1)> {
        let e0 = Store::read(address_domain, base)?;
        let e1 = Store::read_at_offset(address_domain, base, Store::<E0>::size())?;
        Result::Ok((e0, e1))
    }
    #[inline(always)]
    fn write(address_domain: u32, base: StorageBaseAddress, value: (E0, E1)) -> SyscallResult<()> {
        let (e0, e1) = value;
        Store::write(address_domain, base, e0)?;
        Store::write_at_offset(address_domain, base, Store::<E0>::size(), e1)
    }
    #[inline(always)]
    fn read_at_offset(
        address_domain: u32, base: StorageBaseAddress, mut offset: u8
    ) -> SyscallResult<(E0, E1)> {
        let e0 = Store::read_at_offset(address_domain, base, offset)?;
        offset += Store::<E0>::size();
        let e1 = Store::read_at_offset(address_domain, base, offset)?;
        Result::Ok((e0, e1))
    }
    #[inline(always)]
    fn write_at_offset(
        address_domain: u32, base: StorageBaseAddress, mut offset: u8, value: (E0, E1)
    ) -> SyscallResult<()> {
        let (e0, e1) = value;
        Store::write_at_offset(address_domain, base, offset, e0)?;
        offset += Store::<E0>::size();
        Store::write_at_offset(address_domain, base, offset, e1)
    }
    #[inline(always)]
    fn size() -> u8 {
        Store::<E0>::size() + Store::<E1>::size()
    }
}
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4054)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/hash.cairo` line 23 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4054#-Ne7evYxAap2ATD7XivO:-Ne7smpCCp7fRws8qDtJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/851ebb3f69220d2465c045424e70a3fe4d30c517/corelib/src/hash.cairo#L23)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

can't these '_'s  be omitted?
</blockquote></details>

Done.
___
*[`corelib/src/starknet/secp256_trait.cairo` line 63 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4054#-Ne7gSJQC2MKH16-TcHT:-Ne7rhvIDneu3EVT9sk1:b-a7fu9j) ([raw file](https://github.com/starkware-libs/cairo/blob/851ebb3f69220d2465c045424e70a3fe4d30c517/corelib/src/starknet/secp256_trait.cairo#L63)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

isn't it better in this case to just leave the name?
same in lines 81 and 127
</blockquote></details>

sure - reverting.
___
*[`corelib/src/starknet/storage_access.cairo` line 514 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4054#-Ne7griYD9eLsVBeycp2:-Ne7tejG0JidB3XBAHBj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/851ebb3f69220d2465c045424e70a3fe4d30c517/corelib/src/starknet/storage_access.cairo#L514)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

same here and below. isn't it better to leave the names?
</blockquote></details>

Done.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4054#-:-Ne90ZaH6xtPWIcUYsAu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4054)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
