### PR TITLE
Introduce a `consteval_int` macro to compute integers at compile-time

### LINKED ISSUE #3130: feat: compile-time arithmetic for constants
# Feature Request

**Describe the Feature Request**

The Cairo compiler should be able to calculate the compile-time value of constants, to make it easier to write such constants, e.g.:
```
const some_value = (256 * 1080) & 0xfaff + 1234; // should become 14336
const some_power_of_2: felt252 = 2**128 - 1; // should become 340282366920938463463374607431768211455
```

The only operator not currently in Cairo is `**`, but I feel an 'integer power' operator is super convenient when doing blockchain development, so it seems like it should be implemented as well.

**Describe Preferred Solution**

The compiler should just compile that arithmetic expression into its proper value.

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by wraitii**
Fixes #3130

This introduces a Cairo plugin that converts constant expressions in constant into their actual value, so that we can write code such as the below without requiring further compiler changes. I think it's sufficient to do this in constants.
```
const some_value = consteval_int!((256 * 1080) & 0xfaff + 1234); // should become 14336
const some_other_value: felt252 = consteval_int!(256 - 1); // should become 255
```
I have a separate diff on a 'pow operator' (`2**128`)  that I can push next if that is wanted.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3132)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3132)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @wraitii)

___
*[`tests/bug_samples/issue2964.cairo` line 23 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3132#-NWDWxTZCo4Xtqq-gevH:-NWDWxTZCo4Xtqq-gevI:bpbulxo) ([raw file](https://github.com/starkware-libs/cairo/blob/1551c727916bc5378a488ef013d5760f1aff6c9b/tests/bug_samples/issue2964.cairo#L23)):*
> ```Cairo
>     // This assumes that Drop implies Destruct and Copy implies Clone
>     let mut a = GenericStruct { x: SimpleStruct { x: 1, y: 2 }, y: SimpleStruct { x: 1, y: 2 } };
>     a.x.x = 24;
> ```

What is this change?

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
This alters the behaviour of the code. for example 255_u8+1-1 will work with your plugin, but fail without.
I'd rather this be explicit with an inline macro, or at the very least an annotation above the const item, that explains this does operations in the integers realm.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3132#-:-NWDXZ8q1Wxn5zAdKzvR:b-pcgtgv)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @wraitii)

___
*[`crates/cairo-lang-plugins/src/plugins/arithmetic.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3132#-NWDXA-o4sMjZReBC0ob:-NWDXA-o4sMjZReBC0oc:btlrpf1) ([raw file](https://github.com/starkware-libs/cairo/blob/1551c727916bc5378a488ef013d5760f1aff6c9b/crates/cairo-lang-plugins/src/plugins/arithmetic.rs#L73)):*
> ```XML
>                 Some(rec_compute(db, &bin_expr.lhs(db))? - rec_compute(db, &bin_expr.rhs(db))?)
>             }
>             ast::BinaryOperator::Div(_) => {
> ```

This might be wrong. For example, felt division is incorrect here. Are u sure u wanna support div?
___
*[`crates/cairo-lang-plugins/src/plugins/arithmetic.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3132#-NWDXL1dEavRWwlgmR4s:-NWDXL1dEavRWwlgmR4t:bowyuff) ([raw file](https://github.com/starkware-libs/cairo/blob/1551c727916bc5378a488ef013d5760f1aff6c9b/crates/cairo-lang-plugins/src/plugins/arithmetic.rs#L76)):*
> ```XML
>                 Some(rec_compute(db, &bin_expr.lhs(db))? / rec_compute(db, &bin_expr.rhs(db))?)
>             }
>             ast::BinaryOperator::Mod(_) => {
> ```

Same as for Div. Felts won't like this.

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3132)* status: all files reviewed, 2 unresolved discussions (waiting on @wraitii)

**Review by spapinistarkware — COMMENTED** [review]
Looks good to me. Let's wait for Orizi to also take a look.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3132#-:-NXeZxkk9L4EMmASTvQ9:b-k1pbby)* status: all files reviewed, 2 unresolved discussions (waiting on @wraitii)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3132)* status: all files reviewed, 5 unresolved discussions (waiting on @wraitii)

___
*[`crates/cairo-lang-plugins/src/plugins/consteval_int.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3132#-NXiDkOj1OXV0E756p9o:-NXiDkOj1OXV0E756p9p:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/cd89bc04f8102e9aa558618a8ee1ce0f9e73c595/crates/cairo-lang-plugins/src/plugins/consteval_int.rs#L34)):*
> ```XML
> }
> 
> fn handle_constant(db: &dyn SyntaxGroup, constant_ast: &ast::ItemConstant) -> PluginResult {
> ```

doc
___
*[`crates/cairo-lang-plugins/src/plugins/consteval_int.rs` line 68 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3132#-NXiDl9z1dfZtp4mL-D1:-NXiDl9z1dfZtp4mL-D2:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/cd89bc04f8102e9aa558618a8ee1ce0f9e73c595/crates/cairo-lang-plugins/src/plugins/consteval_int.rs#L68)):*
> ```XML
> }
> 
> fn extract_consteval_macro_expression(
> ```

doc
___
*[`crates/cairo-lang-plugins/src/plugins/consteval_int.rs` line 93 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3132#-NXiDlzO1oKYrrJZKqpJ:-NXiDlzO1oKYrrJZKqpK:b-wz6dct) ([raw file](https://github.com/starkware-libs/cairo/blob/cd89bc04f8102e9aa558618a8ee1ce0f9e73c595/crates/cairo-lang-plugins/src/plugins/consteval_int.rs#L93)):*
> ```XML
> }
> 
> fn rec_compute(
> ```

doc
and rename to 'compute_constant_expr'

**Comment by wraitii** [comment]
Done all inlines.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3132)* status: all files reviewed, 6 unresolved discussions (waiting on @spapinistarkware and @wraitii)

___
*[`crates/cairo-lang-plugins/src/plugins/consteval_int.rs` line 36 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3132#-NXjnpGH0htBOc6sTtC7:-NXjnpGH0htBOc6sTtC8:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6748e25347ea4f117df31da7ce6ed42d9cb523ae/crates/cairo-lang-plugins/src/plugins/consteval_int.rs#L36)):*
> ```XML
> // Rewrite a constant declaration that contains a consteval_int macro
> // into a constant declaration with the computed value,
> // e.g. `const a: felt252 = consteval_int!(2 * 2 * 2);` into `const a: felt252 = 8;`.
> ```





_Suggestion:_
```XML
/// Rewrite a constant declaration that contains a consteval_int macro
/// into a constant declaration with the computed value,
/// e.g. `const a: felt252 = consteval_int!(2 * 2 * 2);` into `const a: felt252 = 8;`.
```
___
*[`crates/cairo-lang-plugins/src/plugins/consteval_int.rs` line 71 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3132#-NXjnnlpAdCeSrqR0A6V:-NXjnnlqDObqnpSeAa5i:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6748e25347ea4f117df31da7ce6ed42d9cb523ae/crates/cairo-lang-plugins/src/plugins/consteval_int.rs#L71)):*
> ```XML
> }
> 
> // Extract the actual expression from the consteval_int macro, or fail with diagnostics.
> ```





_Suggestion:_
```XML
/// Extract the actual expression from the consteval_int macro, or fail with diagnostics.
```
___
*[`crates/cairo-lang-plugins/src/plugins/consteval_int.rs` line 98 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3132#-NXjnmHq4FYbXF-0V_F6:-NXjnmHq4FYbXF-0V_F7:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6748e25347ea4f117df31da7ce6ed42d9cb523ae/crates/cairo-lang-plugins/src/plugins/consteval_int.rs#L98)):*
> ```XML
> 
> // Compute the actual value of an integer expression, or fail with diagnostics.
> // This computation handles arbitrary integers, unlike regular Cairo math.
> ```





_Suggestion:_
```XML
/// Compute the actual value of an integer expression, or fail with diagnostics.
/// This computation handles arbitrary integers, unlike regular Cairo math.
```
___
*[`tests/bug_samples/issue3130.cairo` line 7 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3132#-NXjo-qX2byUk3_vwHl1:-NXjo-qX2byUk3_vwHl2:b-rz026n) ([raw file](https://github.com/starkware-libs/cairo/blob/6748e25347ea4f117df31da7ce6ed42d9cb523ae/tests/bug_samples/issue3130.cairo#L7)):*
> ```Cairo
> 
> #[test]
> fn main() {}
> ```

add to `bug_samples/lib.cairo`



_Code quote:_
```Cairo
const a: felt252 = (4 + 2 * 3) * 256;
const b: felt252 = 0xff & (24 + 5 * 2);
const c: felt252 = -0xff & (24 + 5 * 2);
const d: felt252 = 0xff | (24 + 5 * 2);

#[test]
fn main() {}
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3132#-:-NXjtj0X3HASEW2yZ5yX:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware and @wraitii)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3132#-:-NXjx9qzCwbNhXEKtbY1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wraitii)

**Comment by wraitii** [comment]
@orizi @spapinistarkware Cairo_fmt wants to add a space before the 'consteval_int', but that suggestion actually crashes the Cairo compiler.

I'm not entirely sure how to fix this, it's not obvious to me where this space gets added in the formatter.

**Review by orizi — COMMENTED** [review]
We probably need to fix something in the formatter. (As this is the first macro usage)
Will fix tomorrow and ping here.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3132#-:-NXlHNO_3jqFfCtXVX_W:b-gnvo4e)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @wraitii)

**Review by orizi — COMMENTED** [review]
can you check again?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3132#-:-NXonzb-C5Y5sVNxUR7v:boi9r8t)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @wraitii)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 9 files at r2, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3132)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wraitii)

**Pull request merged**
