### PR TITLE
LS: Rename `project::scarb::db` to `project::scarb`

### PR DESCRIPTION
**Pull request by mkaput**
This refactor will yield better diffs in the next commit.

---

**Stack**:
- #6009
- #6008 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6008)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6008#-:-O1VUA2w2MBW40biRO63:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Draggu)

**Review by Draggu — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6008#-:-O1VsA31AaL3-qgY4Ksz:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Comment by mkaput** [comment]
@orizi why did you drop this branch?

**Comment by orizi** [comment]
Just deleted merged branches - i assume github just closed it because it was targeting a deleted branch :thinking:

**Comment by mkaput** [comment]
ok weird. restored the branch and I'll re-push here

**Pull request merged**
