### PR TITLE
Formatter: add protected zone precedence.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1318)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1318)* status: all files reviewed, 8 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/formatter/src/formatter.rs` line 71 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1318#-NJLB3-ZBKG9JALoykPa:-NJZqDi0B3jcxWcesM6o:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b8a7297795e11d8afb5c864d30eb1a34d43f940f/crates/formatter/src/formatter.rs#L71)):*
> ```XML
>     /// More generally, any break point inside a child LineBuilder will be ignored unless there
>     /// are no breakpoint which are direct children of the parent LineBuilder.
>     /// The precedence dictates the order in which the internal builders will be open.
> ```

Done.
___
*[`crates/formatter/src/formatter.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1318#-NJLAtFR1yEl_FOc1-rl:-NJZI8HZ1mkvGueJFgL1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b8a7297795e11d8afb5c864d30eb1a34d43f940f/crates/formatter/src/formatter.rs#L74)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

This is the same as protected zone, right?
Please choose one of the names and be consistent with it.
</blockquote></details>

Done.
___
*[`crates/formatter/src/formatter.rs` line 151 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1318#-NJLBxAq5nBCf1vHNayZ:-NJZILOR3DBky0tqTLk8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b8a7297795e11d8afb5c864d30eb1a34d43f940f/crates/formatter/src/formatter.rs#L151)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

+ add documentation.
</blockquote></details>

Done.
___
*[`crates/formatter/src/formatter.rs` line 354 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1318#-NJLCmbo4ASDWk9sassU:-NJZUGU46ZAUYBKH9bUu:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b8a7297795e11d8afb5c864d30eb1a34d43f940f/crates/formatter/src/formatter.rs#L354)):*
> ```XML
>     }
>     /// Returns the minimum protected zone precedence from within all the protected zones
>     /// which are a direct child of this builder, or None if there are no protected zones.
> ```

Done.
___
*[`crates/formatter/src/formatter.rs` line 355 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1318#-NJLD7FnErW-C8dnDh9c:-NJZUGqF4w_gwI4dm9NR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b8a7297795e11d8afb5c864d30eb1a34d43f940f/crates/formatter/src/formatter.rs#L355)):*
> ```XML
>     /// Returns the minimum protected zone precedence from within all the protected zones
>     /// which are a direct child of this builder, or None if there are no protected zones.
>     fn get_min_flatten_precedence(&self) -> Option<usize> {
> ```

Done.
___
*[`crates/formatter/src/formatter.rs` line 372 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1318#-NJLK9FW8nfoUE5A3cVG:-NJZsYRa0EAYeyI6nH3D:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b8a7297795e11d8afb5c864d30eb1a34d43f940f/crates/formatter/src/formatter.rs#L372)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

change to .expect("...")
</blockquote></details>

Done.
___
*[`crates/formatter/src/formatter.rs` line 372 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1318#-NJLDm3k4cgWdUVOOWBL:-NJZsYl02vtee21Ub5ZS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b8a7297795e11d8afb5c864d30eb1a34d43f940f/crates/formatter/src/formatter.rs#L372)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

move into get_min_flatten_precedence
</blockquote></details>

Done.
___
*[`crates/formatter/src/formatter.rs` line 376 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1318#-NJLEucIBeAc8kupioK6:-NJ_3Erm2NW-YBnb2cCt:b2mgnpn) ([raw file](https://github.com/starkware-libs/cairo/blob/b8a7297795e11d8afb5c864d30eb1a34d43f940f/crates/formatter/src/formatter.rs#L376)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Please add a TODO to improve the complexity. This is currently O(n^2) (actually n*m where n is the number of children and m is the number of protected zones in the biggest group of protected zones of the same precedence...)
</blockquote></details>

Added in the calling function as it is a more general problem.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1318)* status: all files reviewed, 8 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/formatter/src/formatter.rs` line 376 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1318#-NJLEucIBeAc8kupioK6:-NJbWmw0Emedr1EwlntW:b87ikz6) ([raw file](https://github.com/starkware-libs/cairo/blob/b8a7297795e11d8afb5c864d30eb1a34d43f940f/crates/formatter/src/formatter.rs#L376)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Added in the calling function as it is a more general problem.
</blockquote></details>

It's still a good practice to add the information in the TODO. Don't leave is as an exercise for the future improver to find where to improve. You already know what can be improved. Document what and where (indeed, we don't need too many details, but clues can help save some work later).
___
*[`crates/formatter/src/formatter.rs` line 68 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1318#-NJbUGxM91SLr31yvHPe:-NJbUGxM91SLr31yvHPf:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9d6fa714d3cecc1003683194b4876e78f0d24aec/crates/formatter/src/formatter.rs#L68)):*
> ```XML
>     /// For example, in the expression let x = 1 * (2 + 3); everything inside the parenthesis
>     /// will be collected into a protected zone and will be broken only if the line is too
>     /// long after the first break line point, the one before the '*' operator, is broken.
> ```





_Suggestion:_
```XML
    /// Any break line point inside a protected zone is ignored unless
    /// it has no sibling break line points.
    /// For example, in the expression let "x = 1 * (2 + 3);" everything inside the parentheses
    /// is collected into a protected zone and is broken only if the line is too
    /// long after the first break line point (the one before the '*' operator) is broken.
    /// More generally, any break point inside a protected zone is ignored unless there
    /// are no breakpoints which are direct children of the parent LineBuilder.
    /// The precedence dictates the order of breaking the protected zones, among sibling protected
    /// zones. For example, the body of a function should be broken into separate lines before
    /// the function signature.
```
___
*[`crates/formatter/src/formatter.rs` line 251 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1318#-NJbUsIQE_wp-Ehx5KOq:-NJbUsIQE_wp-Ehx5KOr:b-87r37s) ([raw file](https://github.com/starkware-libs/cairo/blob/9d6fa714d3cecc1003683194b4876e78f0d24aec/crates/formatter/src/formatter.rs#L251)):*
> ```XML
>     /// Returns a vec of strings, each one represents a line.
>     fn break_line_tree(&self, max_line_width: usize, tab_size: usize) -> Vec<String> {
>         // TODO(gil): improve the complexity of this function.
> ```

add what's wrong with it now. It's not necessarily you that will do it in the future, and it's not necessarily going to happen soon, so better document what you know to ease it for the one to actually do it in the future.



_Code quote:_
```XML
improve the complexity of this function.
```
___
*[`crates/formatter/src/formatter.rs` line 256 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1318#-NJbVG31EaWXv3LY-0Oa:-NJbVG31EaWXv3LY-0Ob:bfh4qbf) ([raw file](https://github.com/starkware-libs/cairo/blob/9d6fa714d3cecc1003683194b4876e78f0d24aec/crates/formatter/src/formatter.rs#L256)):*
> ```XML
>         }
>         let mut sub_builders = self.break_line_tree_single_level(tab_size);
>         // While the line is not broken into several lines, try to unprotect a protected zone then
> ```

Not clear



_Code quote:_
```XML
        // While the line is not broken into several lines, try to unprotect a protected zone then
        // break it.
```
___
*[`crates/formatter/src/formatter.rs` line 259 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1318#-NJbXMw_8ZHO8xbCDy5t:-NJbXMw_8ZHO8xbCDy5u:bpydbxz) ([raw file](https://github.com/starkware-libs/cairo/blob/9d6fa714d3cecc1003683194b4876e78f0d24aec/crates/formatter/src/formatter.rs#L259)):*
> ```XML
>         // break it.
>         while sub_builders.len() == 1 {
>             if !sub_builders[0].contains_protected_zone() {
> ```

you changed !is_flat() to !contains_protected_zone(). Don't they have the opposite meaning? I think you should remove the not.



_Code quote:_
```XML
!sub_builders[0].contains_protected_zone() {
```
___
*[`crates/formatter/src/formatter.rs` line 261 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1318#-NJbVTfA2e6LwD6c0M-O:-NJbVTfA2e6LwD6c0M-P:b1zqv0) ([raw file](https://github.com/starkware-libs/cairo/blob/9d6fa714d3cecc1003683194b4876e78f0d24aec/crates/formatter/src/formatter.rs#L261)):*
> ```XML
>             if !sub_builders[0].contains_protected_zone() {
>                 sub_builders =
>                     sub_builders[0].unprotect_zone().break_line_tree_single_level(tab_size);
> ```

Consider (unprotect is not confusing)



_Suggestion:_
```XML
break_protected_zone
```
___
*[`crates/formatter/src/formatter.rs` line 373 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1318#-NJbW1TzBDAzXSKICo1o:-NJbW1TzBDAzXSKICo1p:b3cc7kl) ([raw file](https://github.com/starkware-libs/cairo/blob/9d6fa714d3cecc1003683194b4876e78f0d24aec/crates/formatter/src/formatter.rs#L373)):*
> ```XML
>     }
>     /// Creates a new LineBuilder where the first subchild which is a protected zone, is now
>     /// unprotected.
> ```

Oh, I think I get it now... you don't yet break the protected zone, but you create a copy of the same line, but with the protected zone as an integral part of the line, without the protection.
If this is right, break_protected_zone is probably wrong, but try to think of a better verb than "unprotect". Some suggestions:
open, unwind, remove_protection



_Code quote:_
```XML
unprotected
```
___
*[`crates/formatter/src/formatter.rs` line 397 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1318#-NJbXbbM9zHo1hIr86ne:-NJbXbbM9zHo1hIr86nf:bmxn5e4) ([raw file](https://github.com/starkware-libs/cairo/blob/9d6fa714d3cecc1003683194b4876e78f0d24aec/crates/formatter/src/formatter.rs#L397)):*
> ```XML
>     /// Returns whether or not the line contains a protected zone.
>     fn contains_protected_zone(&self) -> bool {
>         !self.children.iter().any(|child| matches!(child, LineComponent::ProtectedZone { .. }))
> ```

Save as above - you should remove the not here.



_Suggestion:_
```XML
self
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1318)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/formatter/src/formatter.rs` line 256 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1318#-NJbVG31EaWXv3LY-0Oa:-NJspTiu9Xkd842Hqho6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9d6fa714d3cecc1003683194b4876e78f0d24aec/crates/formatter/src/formatter.rs#L256)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Not clear
</blockquote></details>

Done.
___
*[`crates/formatter/src/formatter.rs` line 259 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1318#-NJbXMw_8ZHO8xbCDy5t:-NJspW7qDETkEoxqbHuK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9d6fa714d3cecc1003683194b4876e78f0d24aec/crates/formatter/src/formatter.rs#L259)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

you changed !is_flat() to !contains_protected_zone(). Don't they have the opposite meaning? I think you should remove the not.
</blockquote></details>

Done.
___
*[`crates/formatter/src/formatter.rs` line 397 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1318#-NJbXbbM9zHo1hIr86ne:-NJsprU8Coi5gPEYts4b:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9d6fa714d3cecc1003683194b4876e78f0d24aec/crates/formatter/src/formatter.rs#L397)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Save as above - you should remove the not here.
</blockquote></details>

Done.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1318#-:-NJsuFnDBSpy_qOBbPNU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1318#-:-NMUWIPz2e1DX_KHGLnz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by yuvalsw — APPROVED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1318)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1318)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @gilbens-starkware)

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1318)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
