### PR TITLE
Avoid silent failure in get_concrete_type_id.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1872)

### CODE REVIEW

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1872#-:-NMYTsWk9hO7mdYWYfuy:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by spapinistarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1872)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1872)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-sierra-generator/src/types.rs` line 93 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1872#-NMc11Tw7Ty-dXTMLXOW:-NMc11Tw7Ty-dXTMLXOX:bc5c1rk) ([raw file](https://github.com/starkware-libs/cairo/blob/3e9527a2e333e8091f0517c5100177612a88cb6d/crates/cairo-lang-sierra-generator/src/types.rs#L93)):*
> ```XML
>         | semantic::TypeLongId::Missing(_) => {
>             panic!(
>                 "Types should be fully resolved at this point. Got: `{}`.",
> ```

Does the following look ok?

thread 'main' panicked at 'Types should be fully resolved at this point. Got `T`', crates/cairo-lang-sierra-generator/src/types.rs:91:13



_Code quote:_
```XML
"Types should be fully resolved at this point. Got: `{}`.",
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1872#-:-NMc8Nre6rwPaGgiEwHP:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/types.rs` line 93 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1872#-NMc11Tw7Ty-dXTMLXOW:-NMc8Hke2t-eay3tdh94:bhygi6r) ([raw file](https://github.com/starkware-libs/cairo/blob/3e9527a2e333e8091f0517c5100177612a88cb6d/crates/cairo-lang-sierra-generator/src/types.rs#L93)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Does the following look ok?

thread 'main' panicked at 'Types should be fully resolved at this point. Got `T`', crates/cairo-lang-sierra-generator/src/types.rs:91:13
</blockquote></details>

this should never happen - so that will be much easier to debug when it does.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1872)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/types.rs` line 93 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1872#-NMc11Tw7Ty-dXTMLXOW:-NMc9MZG5smFNrr2FcOz:b-5d5wna) ([raw file](https://github.com/starkware-libs/cairo/blob/3e9527a2e333e8091f0517c5100177612a88cb6d/crates/cairo-lang-sierra-generator/src/types.rs#L93)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this should never happen - so that will be much easier to debug when it does.
</blockquote></details>

I'm not sure that `T` or `MyType` is clear enough. but at least it is not a silent failure.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1872)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Pull request merged**
