### PR TITLE
LS: Get rid of needless `scarb metadata` calls

### PR DESCRIPTION
**Pull request by piotmag769**
This PR improves UX regarding project loading for Scarb projects (so assume the rest of the description concerns only these). Logic regarding `cairo_project.toml`-based projects remains unchanged as there is no such an UX issue associated with them.

Before this PR `scarb metadata` was called on every `didOpen` notification. Moreover it was called once per each currently open file when:
- `cairo/reloadWorkspace` command was executed
- `didChangeWatchedFiles` informing about `Scarb.toml` change was received

This PR changes it so we keep *paths* to `Scarb.toml`s that correspond to members of Scarb's workspaces we already analysed/loaded. 

When a `didOpen` notification is received, we check if the path to `Scarb.toml` for the opened file is in *paths*. If it is, we skip the `scarb metadata` execution, else we do as before, but we add paths of all workspace members' manifests to *paths*.

Keep in mind it also improves UX for the two remaining cases: we clear *paths* and load projects for all currently open files, but loading a project for one file from workspace A will prevent redundant `scarb metadata` calls for all the other open files from workspace A (via mechanism described above).

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6689)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/project/scarb.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6689#-OC2XfEi420Pyjt98Qbm:-OC2XfEi420Pyjt98Qbn:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/242dd13483c0953a9341dfd494311a315aa7e3ca/crates/cairo-lang-language-server/src/project/scarb.rs#L21)):*
> ```XML
> use crate::project::crate_data::Crate;
> 
> pub fn get_workspace_members_manifests(metadata: &Metadata) -> Vec<PathBuf> {
> ```

doc

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6689)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/state.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6689#-OC2jVLl5hDHYOMfe4jd:-OC2jVLmDLcvqEZ9oXfT:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/242dd13483c0953a9341dfd494311a315aa7e3ca/crates/cairo-lang-language-server/src/state.rs#L21)):*
> ```XML
>     pub db: AnalysisDatabase,
>     pub open_files: Owned<HashSet<Url>>,
>     pub loaded_scarb_manifests: HashSet<PathBuf>,
> ```





_Suggestion:_
```XML
    pub loaded_scarb_manifests: Owned<HashSet<PathBuf>>,
```
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 395 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6689#-OC2nF2f91RBXJByc3A0:-OC2nF2f91RBXJByc3A1:b-aurb9t) ([raw file](https://github.com/starkware-libs/cairo/blob/242dd13483c0953a9341dfd494311a315aa7e3ca/crates/cairo-lang-language-server/src/lib.rs#L395)):*
> ```XML
>             Some(ProjectManifestPath::Scarb(manifest_path)) => {
>                 if loaded_scarb_manifests.contains(&manifest_path) {
>                     return;
> ```

consider adding a trace log telling the reason of skipping
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 413 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6689#-OC2nOtOD6kwOoA05B44:-OC2nOtOD6kwOoA05B45:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/242dd13483c0953a9341dfd494311a315aa7e3ca/crates/cairo-lang-language-server/src/lib.rs#L413)):*
> ```XML
>                     for manifest in manifests {
>                         loaded_scarb_manifests.insert(manifest);
>                     }
> ```





_Suggestion:_
```XML
                    loaded_scarb_manifests.extend(get_workspace_members_manifests(&metadata))
```

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6689)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 395 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6689#-OC2nF2f91RBXJByc3A0:-OC2uEw261dxOWoWy4xO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/242dd13483c0953a9341dfd494311a315aa7e3ca/crates/cairo-lang-language-server/src/lib.rs#L395)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

consider adding a trace log telling the reason of skipping
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/project/scarb.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6689#-OC2XfEi420Pyjt98Qbm:-OC2vPvh7Qz6I3aIWwW4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/242dd13483c0953a9341dfd494311a315aa7e3ca/crates/cairo-lang-language-server/src/project/scarb.rs#L21)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/state.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6689#-OC2jVLl5hDHYOMfe4jd:-OC2usOi6dnyfG18oEyN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/242dd13483c0953a9341dfd494311a315aa7e3ca/crates/cairo-lang-language-server/src/state.rs#L21)):*
> ```XML
>     pub db: AnalysisDatabase,
>     pub open_files: Owned<HashSet<Url>>,
>     pub loaded_scarb_manifests: HashSet<PathBuf>,
> ```

Done.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 413 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6689#-OC2nOtOD6kwOoA05B44:-OC2ulwb3d9sigiFFOuD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/242dd13483c0953a9341dfd494311a315aa7e3ca/crates/cairo-lang-language-server/src/lib.rs#L413)):*
> ```XML
>                     for manifest in manifests {
>                         loaded_scarb_manifests.insert(manifest);
>                     }
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6689#-:-OC34-oR52M1UprD23W1:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, and @mkaput)

**Review by Draggu — APPROVED** [review]
:lgtm:

> Reviewed 2 of 5 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6689#-:-OC3EI7H5zLA2Wr5bVgI:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae and @mkaput)

**Review by Arcticae — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6689#-:-OC3WuxfEM0jtG51sYAe:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @mkaput)

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6689#-:-OC8APrO20YnDvcGQwqK:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 395 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6689#-OC8ABos8IZ-MHzYf5Kx:-OC8ABos8IZ-MHzYf5Ky:b2ni8l0) ([raw file](https://github.com/starkware-libs/cairo/blob/308c8725cbd02a37e898e6636cf72c78eb52f5b8/crates/cairo-lang-language-server/src/lib.rs#L395)):*
> ```XML
>             Some(ProjectManifestPath::Scarb(manifest_path)) => {
>                 if loaded_scarb_manifests.contains(&manifest_path) {
>                     trace!("Project with manifest `{}` is already loaded", manifest_path.display());
> ```

nit



_Suggestion:_
```XML
trace!("scarb project is already loaded: {}", manifest_path.display());
```

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6689)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 395 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6689#-OC8ABos8IZ-MHzYf5Kx:-OC8YBVhDoqfE7jJMfVO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/308c8725cbd02a37e898e6636cf72c78eb52f5b8/crates/cairo-lang-language-server/src/lib.rs#L395)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

nit
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 395 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6689#-OC30yA10msrcq-QUqSR:-OC32om4Di34UBsZ_KxK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6e8c20a9b42c1816cd9ebdfafb631f1bf7ce4ee4/crates/cairo-lang-language-server/src/lib.rs#L395)):*
> ```XML
>             Some(ProjectManifestPath::Scarb(manifest_path)) => {
>                 if loaded_scarb_manifests.contains(&manifest_path) {
>                     trace!("Project with manifest {} is already loaded", manifest_path.display());
> ```

Done.

**Pull request merged**
