### PR TITLE
Added `FixedSizedArray::span`.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #5405
- #5401
- #5393
- #5389
- #5403 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5403)

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5403)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`corelib/src/array.cairo` line 225 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5403#-NvB4tCSEPOZhZK2MVCP:-NvBA4M6EThWgqNpYngH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3522642f905aae78bbd949e1f66f276f54d2895e/corelib/src/array.cairo#L225)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

why does T need to be copiable?
</blockquote></details>

Done.

**Review by TomerStarkware — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5403)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by TomerStarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5403#-:-NvBAcITDw-VHL1jjmWA:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by TomerStarkware — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5403)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
