### PR TITLE
Coupons: Add dependency_type.

### PR DESCRIPTION
**Pull request by liorgold2**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4664)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4664)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 395 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4664#-NmksOGv6cAZ_NAAuzn0:-NmksOGv6cAZ_NAAuzn1:b-z0snvk) ([raw file](https://github.com/starkware-libs/cairo/blob/92dd915054281675b54c64d8970b3d401c00918d/crates/cairo-lang-lowering/src/db.rs#L395)):*
> ```XML
> 
> /// Given the lowering of a function, returns the set of direct callees of that function.
> fn get_direct_callees(
> ```

maybe this function should be renamed now to something related with building calls dependency graph?
___
*[`crates/cairo-lang-lowering/src/db.rs` line 403 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4664#-NmkvPU184QUzSieFewa:-NmkvPU28H7iBVOBhXSD:bvus9vv) ([raw file](https://github.com/starkware-libs/cairo/blob/92dd915054281675b54c64d8970b3d401c00918d/crates/cairo-lang-lowering/src/db.rs#L403)):*
> ```XML
>         for statement in &block.statements {
>             if let Statement::Call(statement_call) = statement {
>                 if dependency_type == DependencyType::Call || statement_call.coupon_input.is_none()
> ```

Please doc.
Also why it's OK to not add another dep (of the buy_coupon function) in the ::Cost type case.

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4664)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 395 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4664#-NmksOGv6cAZ_NAAuzn0:-Nml1f2GEoVeHs1G_fss:b-bwpf6n) ([raw file](https://github.com/starkware-libs/cairo/blob/92dd915054281675b54c64d8970b3d401c00918d/crates/cairo-lang-lowering/src/db.rs#L395)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

maybe this function should be renamed now to something related with building calls dependency graph?
</blockquote></details>

Noted. This rename will probably mean we should also rename functions like `concrete_function_with_body_postinline_direct_callees` and since I have no idea what their name means in the first place I can't do it myself. I have no objection to renaming though.
___
*[`crates/cairo-lang-lowering/src/db.rs` line 403 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4664#-NmkvPU184QUzSieFewa:-Nml2bJh9nyH3K4WSNtK:b-br7qzs) ([raw file](https://github.com/starkware-libs/cairo/blob/92dd915054281675b54c64d8970b3d401c00918d/crates/cairo-lang-lowering/src/db.rs#L403)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Please doc.
Also why it's OK to not add another dep (of the buy_coupon function) in the ::Cost type case.
</blockquote></details>

Done.
For now, added a TODO. I'll later try to implement it and either change the TODO to an implementation or a comment explaining why it's not implemented.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4664)* status: all files reviewed, 3 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 395 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4664#-NmksOGv6cAZ_NAAuzn0:-Nml4gJtBtIkA8_MT2-A:b-vq6xgh) ([raw file](https://github.com/starkware-libs/cairo/blob/92dd915054281675b54c64d8970b3d401c00918d/crates/cairo-lang-lowering/src/db.rs#L395)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Noted. This rename will probably mean we should also rename functions like `concrete_function_with_body_postinline_direct_callees` and since I have no idea what their name means in the first place I can't do it myself. I have no objection to renaming though.
</blockquote></details>

OK, then please adjust the doc here of what this really does.
___
*[`crates/cairo-lang-lowering/src/db.rs` line 430 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4664#-Nml5L3s5apaZweUUlUe:-Nml5L3s5apaZweUUlUf:b-l5tma9) ([raw file](https://github.com/starkware-libs/cairo/blob/859aec6c4f8b923397174775c7bbda7d26d49134/crates/cairo-lang-lowering/src/db.rs#L430)):*
> ```XML
>         for statement in &block.statements {
>             if let Statement::Call(statement_call) = statement {
>                 // If the dependency_type is DependencyType::Cost and this call has a coupon, then
> ```

This is also a good opportunity to ask you to doc the .coupon_input field in StatementCall, and what it means if it's None.



_Suggestion:_
```XML
s call has a coupon input, the
```
___
*[`crates/cairo-lang-lowering/src/db.rs` line 431 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4664#-Nml5Ax1ADAOwSl2NsRE:-Nml5Ax1ADAOwSl2NsRF:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/859aec6c4f8b923397174775c7bbda7d26d49134/crates/cairo-lang-lowering/src/db.rs#L431)):*
> ```XML
>             if let Statement::Call(statement_call) = statement {
>                 // If the dependency_type is DependencyType::Cost and this call has a coupon, then
>                 // the call statement has a constant const and therefore there is no cost dependency
> ```





_Suggestion:_
```XML
onstant cost and therefore 
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4664)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 395 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4664#-NmksOGv6cAZ_NAAuzn0:-Nml7Zkx4sxmiuREyZFu:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/92dd915054281675b54c64d8970b3d401c00918d/crates/cairo-lang-lowering/src/db.rs#L395)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

OK, then please adjust the doc here of what this really does.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/db.rs` line 430 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4664#-Nml5L3s5apaZweUUlUe:-Nml6_Ny04_m_8p3-rKY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/859aec6c4f8b923397174775c7bbda7d26d49134/crates/cairo-lang-lowering/src/db.rs#L430)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

This is also a good opportunity to ask you to doc the .coupon_input field in StatementCall, and what it means if it's None.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/db.rs` line 431 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4664#-Nml5Ax1ADAOwSl2NsRE:-Nml6-lS5AXxtpWGMCxn:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/859aec6c4f8b923397174775c7bbda7d26d49134/crates/cairo-lang-lowering/src/db.rs#L431)):*
> ```XML
>             if let Statement::Call(statement_call) = statement {
>                 // If the dependency_type is DependencyType::Cost and this call has a coupon, then
>                 // the call statement has a constant const and therefore there is no cost dependency
> ```

Done.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4664#-:-Nml9nNjAzzCf564mRjd:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4664)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
