### PR TITLE
Fixed enum libfunc costs

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2158)

### CODE REVIEW

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2158)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2158#-NOLIAVT5zMsC0NPCIg_:-NOLIAVT5zMsC0NPCIga:b-3yf84a) (no related file):*
change target branch

___

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2158)* status: 0 of 21 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 276 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2158#-NOOSfbl1aJ87hxWGEie:-NOOSfbl1aJ87hxWGEif:b8nre3d) ([raw file](https://github.com/starkware-libs/cairo/blob/174e978de8b6c2f26140bb07db813ecd5bece357/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L276)):*
> ```XML
>                 0 => unreachable!(),
>                 1 => vec![ops.steps(0)],
>                 2 => vec![ops.steps(2), ops.steps(1)],
> ```

Change to the match cost only (as discussed).

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2158)* status: 0 of 21 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 276 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2158#-NOOSfbl1aJ87hxWGEie:-NOPGk1Y0hedl70rKW1r:bmnllh8) ([raw file](https://github.com/starkware-libs/cairo/blob/435a7a4f296aa3a165fa0eaf17e5b3f8d7c06af0/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L276)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Change to the match cost only (as discussed).
</blockquote></details>

Nice catch! thanks!

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2158)* status: 0 of 21 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 268 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2158#-NOPOgM887p4P-3TaR5R:-NOPOgM887p4P-3TaR5S:b-5cfcaj) ([raw file](https://github.com/starkware-libs/cairo/blob/19e33c6e5a33b63511e7f2a87d95880258dce734/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L268)):*
> ```XML
>             vec![ops.steps(1)]
>         }
>         Enum(EnumConcreteLibfunc::Init(_)) => vec![ops.steps(2)],
> ```

Should be 0, store_temp will pay for it.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2158)* status: 0 of 21 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 268 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2158#-NOPOgM887p4P-3TaR5R:-NOPSmAu15JX-gJvlvVQ:bodutsv) ([raw file](https://github.com/starkware-libs/cairo/blob/19e33c6e5a33b63511e7f2a87d95880258dce734/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L268)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Should be 0, store_temp will pay for it.
</blockquote></details>

Thanks again! Done.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 21 of 21 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2158#-:-NOPYuC_DpsfKR8TETbf:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 11 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2158)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 10 of 21 files at r5, 3 of 11 files at r6, 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2158)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2158)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 16 of 16 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2158)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2158)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2158#-:-NOiOdG6DsU-wIyAmdoX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
