### PR TITLE
LS: Add code action completing missing trait members in `impl`

### PR DESCRIPTION
**Pull request by integraledelebesgue**
Closes [#5944](https://github.com/starkware-libs/cairo/issues/5944)

## Changes
* If `impl` block is missing some members of an implemented trait, a quick fix filling those members appears
* Known generic arguments are inserted in impls, unknown substituted with placeholders
* Inserted code is not formatted

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6690)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, and @piotmag769)

___
*[`crates/cairo-lang-language-server/tests/e2e/code_actions.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6690#-OC2Y7bFA4AoRZSsG_6L:-OC2Y7bFA4AoRZSsG_6M:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a6bf85bb71c8f9efd6e1821c9bf40d9ca57aa05c/crates/cairo-lang-language-server/tests/e2e/code_actions.rs#L18)):*
> ```XML
>         macro_expand: "macro_expand.txt",
>         fill_struct_fields: "fill_trait_members.txt",
>         fill_trait_members: "fill_trait_members.txt",
> ```





_Suggestion:_
```XML
        fill_struct_fields: "fill_struct_fields.txt",
        fill_trait_members: "fill_trait_members.txt",
```
___
*[`crates/cairo-lang-language-server/src/ide/code_actions/fill_trait_members.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6690#-OC2YIZq7JGH8JwNSs5p:-OC2YIZq7JGH8JwNSs5q:bpez8xh) ([raw file](https://github.com/starkware-libs/cairo/blob/a6bf85bb71c8f9efd6e1821c9bf40d9ca57aa05c/crates/cairo-lang-language-server/src/ide/code_actions/fill_trait_members.rs#L141)):*
> ```XML
>     let attributes = constant_data.attributes;
> 
>     // Will this ever happen? I believe trait consts cannot have default values.
> ```

currently - const items indeed never have default values.



_Code quote:_
```XML
    // Will this ever happen? I believe trait consts cannot have default values.
```

**Review by integraledelebesgue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6690)* status: 5 of 9 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/code_actions/fill_trait_members.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6690#-OC2YIZq7JGH8JwNSs5p:-OC31-Xo3Z0JiQKmz7Ww:bhiafyc) ([raw file](https://github.com/starkware-libs/cairo/blob/a6bf85bb71c8f9efd6e1821c9bf40d9ca57aa05c/crates/cairo-lang-language-server/src/ide/code_actions/fill_trait_members.rs#L141)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

currently - const items indeed never have default values.
</blockquote></details>

Thank you for answer @orizi. I'll remove the retrieval logic then.
___
*[`crates/cairo-lang-language-server/tests/e2e/code_actions.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6690#-OC2Y7bFA4AoRZSsG_6L:-OC382hL148fdRdgg3Ki:bmfxgaw) ([raw file](https://github.com/starkware-libs/cairo/blob/a6bf85bb71c8f9efd6e1821c9bf40d9ca57aa05c/crates/cairo-lang-language-server/tests/e2e/code_actions.rs#L18)):*
> ```XML
>         macro_expand: "macro_expand.txt",
>         fill_struct_fields: "fill_trait_members.txt",
>         fill_trait_members: "fill_trait_members.txt",
> ```

Done :)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6690)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @integraledelebesgue, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/code_actions/fill_trait_members.rs` line 131 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6690#-OC3K-ZUEBXDL9DLMG02:-OC3K-ZV6yTGXoDnJHjL:bm0s4y) ([raw file](https://github.com/starkware-libs/cairo/blob/284675a3e089c559aa3e3e0e987b67c0466b55cb/crates/cairo-lang-language-server/src/ide/code_actions/fill_trait_members.rs#L131)):*
> ```XML
> }
> 
> fn constant_code(
> ```

probably doc as well.

**Review by integraledelebesgue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6690)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/code_actions/fill_trait_members.rs` line 131 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6690#-OC3K-ZUEBXDL9DLMG02:-OC8D_pd8Jy7_DmYjV3S:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/284675a3e089c559aa3e3e0e987b67c0466b55cb/crates/cairo-lang-language-server/src/ide/code_actions/fill_trait_members.rs#L131)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

probably doc as well.
</blockquote></details>

Done

**Review by mkaput — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6690)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6690#-:-OC9Bq_dEk-EaV47iLlt:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @piotmag769)

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6690)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @piotmag769)

**Review by piotmag769 — CHANGES_REQUESTED** [review]
:lgtm:, great job :muscle: 

> Reviewed 5 of 9 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6690#-:-OCDCz0A-rigfhEG9Nev:b8o8nli)* status: all files reviewed, 7 unresolved discussions (waiting on @Arcticae, @Draggu, and @integraledelebesgue)

___
*[`crates/cairo-lang-language-server/src/ide/code_actions/fill_trait_members.rs` line 31 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6690#-OCDaKBm0UyHx_-EtyXg:-OCDaKBm0UyHx_-EtyXh:b9rb4ol) ([raw file](https://github.com/starkware-libs/cairo/blob/8aca37e6cfcead7dc55337ce91725e1e700efff1/crates/cairo-lang-language-server/src/ide/code_actions/fill_trait_members.rs#L31)):*
> ```XML
>     let file = db.find_module_file_containing_node(&node)?.file_id(db).ok()?;
> 
>     let item_impl_node = db.first_ancestor_of_kind(node, SyntaxKind::ItemImpl)?;
> ```

Does it also work when caret is in impl body? If so is it intended (imo it's fine, just asking) + can we add a test for that?
___
*[`crates/cairo-lang-language-server/src/ide/code_actions/fill_trait_members.rs` line 75 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6690#-OCDUp3WD5ETaX1x5UK6:-OCDUp3X6WL9UeRWi3HI:buh7t8f) ([raw file](https://github.com/starkware-libs/cairo/blob/8aca37e6cfcead7dc55337ce91725e1e700efff1/crates/cairo-lang-language-server/src/ide/code_actions/fill_trait_members.rs#L75)):*
> ```XML
>             .collect_vec()
>             .into_iter(),
>         trait_types.values().map(|id| format!("type {};", id.name(db))),
> ```

That's also what happen in IntelliJ



_Suggestion:_
```XML
"type {} = ();"
```
___
*[`crates/cairo-lang-language-server/src/ide/code_actions/fill_trait_members.rs` line 140 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6690#-OCDT8eI8xLAr_cdOZNs:-OCDT8eJ-NcsoMwvlRhU:b-l7fc0l) ([raw file](https://github.com/starkware-libs/cairo/blob/8aca37e6cfcead7dc55337ce91725e1e700efff1/crates/cairo-lang-language-server/src/ide/code_actions/fill_trait_members.rs#L140)):*
> ```XML
> ) -> Option<String> {
>     let name = id.name(db);
>     let constant_data = db.priv_trait_constant_data(id).ok()?;
> ```

`db.trait_constant_type(id)`
___
*[`crates/cairo-lang-language-server/src/ide/code_actions/fill_trait_members.rs` line 148 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6690#-OCDWdku8O3a_8VhH8LM:-OCDWdku8O3a_8VhH8LN:b-g8ea0s) ([raw file](https://github.com/starkware-libs/cairo/blob/8aca37e6cfcead7dc55337ce91725e1e700efff1/crates/cairo-lang-language-server/src/ide/code_actions/fill_trait_members.rs#L148)):*
> ```XML
> /// Generates [`Parameter`] declaration containing its name,
> /// type and optionally a `ref` indicator.
> /// Generics are substituted with concrete types according to a given [`SubstitutionRewriter`]
> ```

What about a case like this?
```cairo
trait MyTrait {
    fn func<B>(b: B) -> B {
        return b;
    }
}
```
You cannot substitute the `B` since the function is generic itself (depend on trait's generic params). WIll the substitution fail or just return the generic type name?

Can we add a func like this to the trait in tests?
___
*[`crates/cairo-lang-language-server/src/ide/code_actions/fill_trait_members.rs` line 149 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6690#-OCDTwlj4ZSXqHyCN0mq:-OCDTwlj4ZSXqHyCN0mr:b-ffo8rt) ([raw file](https://github.com/starkware-libs/cairo/blob/8aca37e6cfcead7dc55337ce91725e1e700efff1/crates/cairo-lang-language-server/src/ide/code_actions/fill_trait_members.rs#L149)):*
> ```XML
> /// type and optionally a `ref` indicator.
> /// Generics are substituted with concrete types according to a given [`SubstitutionRewriter`]
> fn function_parameter(
> ```

[nit] should be below `function_code` as it is used there
___
*[`crates/cairo-lang-language-server/src/ide/code_actions/fill_trait_members.rs` line 157 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6690#-OCDWD_MDfnfnQ7xMt5-:-OCDWD_MDfnfnQ7xMt50:b-lb1zfz) ([raw file](https://github.com/starkware-libs/cairo/blob/8aca37e6cfcead7dc55337ce91725e1e700efff1/crates/cairo-lang-language-server/src/ide/code_actions/fill_trait_members.rs#L157)):*
> ```XML
>         cairo_lang_semantic::Mutability::Reference => "ref ",
>         cairo_lang_semantic::Mutability::Immutable => "",
>         // `mut` modifier is not used with function arguments.
> ```

That's not true, `mut` it allowed there. `ref` is `&mut`
___
*[`crates/cairo-lang-language-server/tests/test_data/code_actions/fill_trait_members.txt` line 117 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6690#-OCDbTb7AD7rBu_8FNqv:-OCDbTb7AD7rBu_8FNqw:baz0my1) ([raw file](https://github.com/starkware-libs/cairo/blob/8aca37e6cfcead7dc55337ce91725e1e700efff1/crates/cairo-lang-language-server/tests/test_data/code_actions/fill_trait_members.txt#L117)):*
> ```help
>     impl ImplWithEverything<caret> of MyTrait<u32, felt252, 12> {
> Title: Implement missing members
> Add new text: ""
> ```

This shouldn't be a thing, we should check for empty string

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6690)* status: all files reviewed, 7 unresolved discussions (waiting on @Arcticae, @Draggu, and @integraledelebesgue)

**Review by integraledelebesgue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6690)* status: 7 of 9 files reviewed, 6 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/code_actions/fill_trait_members.rs` line 31 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6690#-OCDaKBm0UyHx_-EtyXg:-OCKhROh-YNSsRdMa1dV:b-2fy062) ([raw file](https://github.com/starkware-libs/cairo/blob/efe8fd2c89b5098496ec0ec31e21987f444bd706/crates/cairo-lang-language-server/src/ide/code_actions/fill_trait_members.rs#L31)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Does it also work when caret is in impl body? If so is it intended (imo it's fine, just asking) + can we add a test for that?
</blockquote></details>

It doesn't - only `impl`'s name is affected by the diagnostics and underlined in red. Tbh i can't figure out how to allow performing the action from the body.
___
*[`crates/cairo-lang-language-server/src/ide/code_actions/fill_trait_members.rs` line 75 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6690#-OCDUp3WD5ETaX1x5UK6:-OCKhkvV7MLVUYopBboc:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/efe8fd2c89b5098496ec0ec31e21987f444bd706/crates/cairo-lang-language-server/src/ide/code_actions/fill_trait_members.rs#L75)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

That's also what happen in IntelliJ
</blockquote></details>

Done
___
*[`crates/cairo-lang-language-server/src/ide/code_actions/fill_trait_members.rs` line 140 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6690#-OCDT8eI8xLAr_cdOZNs:-OCKhlyd55F32EMK3QHq:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/efe8fd2c89b5098496ec0ec31e21987f444bd706/crates/cairo-lang-language-server/src/ide/code_actions/fill_trait_members.rs#L140)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

`db.trait_constant_type(id)`
</blockquote></details>

Done
___
*[`crates/cairo-lang-language-server/src/ide/code_actions/fill_trait_members.rs` line 148 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6690#-OCDWdku8O3a_8VhH8LM:-OCKhzltESzskPsJ6_28:bwlslyd) ([raw file](https://github.com/starkware-libs/cairo/blob/efe8fd2c89b5098496ec0ec31e21987f444bd706/crates/cairo-lang-language-server/src/ide/code_actions/fill_trait_members.rs#L148)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

What about a case like this?
```cairo
trait MyTrait {
    fn func<B>(b: B) -> B {
        return b;
    }
}
```
You cannot substitute the `B` since the function is generic itself (depend on trait's generic params). WIll the substitution fail or just return the generic type name?

Can we add a func like this to the trait in tests?
</blockquote></details>

I fixed the implementation to handle such functions and added a quite complex test case to verify it
___
*[`crates/cairo-lang-language-server/src/ide/code_actions/fill_trait_members.rs` line 157 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6690#-OCDWD_MDfnfnQ7xMt5-:-OCKi4gM20LM0NmPpSmw:b-asc88z) ([raw file](https://github.com/starkware-libs/cairo/blob/efe8fd2c89b5098496ec0ec31e21987f444bd706/crates/cairo-lang-language-server/src/ide/code_actions/fill_trait_members.rs#L157)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

That's not true, `mut` it allowed there. `ref` is `&mut`
</blockquote></details>

Sure, I added the appropriate prefix

**Review by integraledelebesgue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6690)* status: 7 of 9 files reviewed, 6 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-language-server/tests/test_data/code_actions/fill_trait_members.txt` line 117 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6690#-OCDbTb7AD7rBu_8FNqv:-OCKiI86ChyJpgUVb4XQ:b-7pu0i) ([raw file](https://github.com/starkware-libs/cairo/blob/efe8fd2c89b5098496ec0ec31e21987f444bd706/crates/cairo-lang-language-server/tests/test_data/code_actions/fill_trait_members.txt#L117)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

This shouldn't be a thing, we should check for empty string
</blockquote></details>

I don't know why does it even appear here because that `impl` shouldn't emit any diagnostics.

**Review by mkaput — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6690)* status: all files reviewed, 6 unresolved discussions (waiting on @Arcticae, @Draggu, and @piotmag769)

**Review by piotmag769 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6690)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, and @integraledelebesgue)

___
*[`crates/cairo-lang-language-server/src/ide/code_actions/fill_trait_members.rs` line 31 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6690#-OCDaKBm0UyHx_-EtyXg:-OCYICnq8uI_s8FEFeLv:bt1sacq) ([raw file](https://github.com/starkware-libs/cairo/blob/efe8fd2c89b5098496ec0ec31e21987f444bd706/crates/cairo-lang-language-server/src/ide/code_actions/fill_trait_members.rs#L31)):*
<details><summary><i>Previously, integraledelebesgue (Jan Smółka) wrote…</i></summary><blockquote>

It doesn't - only `impl`'s name is affected by the diagnostics and underlined in red. Tbh i can't figure out how to allow performing the action from the body.
</blockquote></details>

It is even better that we cannot, was just making sure. It is quite weird though, since the body is a child of `ItemImpl` :thinking: 
___
*[`crates/cairo-lang-language-server/tests/test_data/code_actions/fill_trait_members.txt` line 117 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6690#-OCDbTb7AD7rBu_8FNqv:-OCYJOqo0q6s9Rb9H-wi:bk3fwaz) ([raw file](https://github.com/starkware-libs/cairo/blob/efe8fd2c89b5098496ec0ec31e21987f444bd706/crates/cairo-lang-language-server/tests/test_data/code_actions/fill_trait_members.txt#L117)):*
<details><summary><i>Previously, integraledelebesgue (Jan Smółka) wrote…</i></summary><blockquote>

I don't know why does it even appear here because that `impl` shouldn't emit any diagnostics.
</blockquote></details>

It is indeed weird :thinking: Maybe it happens bcs there are other traits in this file that emit this diagnostic? If so just check for the empty string I guess

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6690)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, and @integraledelebesgue)

**Review by Arcticae — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6690#-:-OCdJliLDy1HJZTVnTFz:bg7igkv)* status: all files reviewed, 2 unresolved discussions (waiting on @Draggu, @integraledelebesgue, and @piotmag769)

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6690)* status: all files reviewed, 2 unresolved discussions (waiting on @Draggu, @integraledelebesgue, and @piotmag769)

**Comment by piotmag769** [comment]
Moved to LS repo: https://github.com/software-mansion/cairols/pull/4

**Pull request closed without merging**
