### PR TITLE
Add SemanticDiagnosticKind::NameDefinedMultipleTimes.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1618)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1618)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-semantic/src/db.rs` line 595 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1618#-NKqhFA6CuPgVQPKU8E7:-NKqhFA6CuPgVQPKU8E8:b-4tbpqi) ([raw file](https://github.com/starkware-libs/cairo/blob/0ea4321e5e82460b5c57cf9caaee46f113bf80de/crates/cairo-semantic/src/db.rs#L595)):*
> ```XML
> 
>     let mut defined_items = HashSet::new();
>     for (name, item) in db.module_items(module_id)?.items.iter() {
> ```

this alredy removed duplicates :(



_Code quote:_
```XML
 db.module_items
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 38 of 39 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1618)* status: 38 of 39 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 100 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1618#-NKsY9XZDP_9SCpD_78Y:-NKsY9XZDP_9SCpD_78Z:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2ecb2216e132a2378a7da2a7989b7750f5d35c2c/crates/cairo-lang-semantic/src/db.rs#L100)):*
> ```XML
>     /// Private query to compute data about the module.
>     #[salsa::invoke(items::module::priv_module_items_data)]
>     fn priv_module_items_data(&self, module_id: ModuleId) -> Maybe<Arc<ModuleItemsData>>;
> ```





_Suggestion:_
```XML
ModuleSemanticData
```
___
*[`crates/cairo-lang-semantic/src/items/module.rs` line 43 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1618#-NKsXTqJ9Fn43g1GB9fr:-NKsXTqJ9Fn43g1GB9fs:b-j27na9) ([raw file](https://github.com/starkware-libs/cairo/blob/2ecb2216e132a2378a7da2a7989b7750f5d35c2c/crates/cairo-lang-semantic/src/items/module.rs#L43)):*
> ```XML
> 
>         if items.insert(name.clone(), *item).is_some() {
>             // TODO(ilya): Remove name from items.
> ```

probably leaving the first is ok.



_Code quote:_
```XML
            // TODO(ilya): Remove name from items.
```
___
*[`crates/cairo-lang-semantic/src/items/tests/module` line 5 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1618#-NKsXjmn4u7kVLq5w-ia:-NKsXjmn4u7kVLq5w-ib:b-ym7j9o) ([raw file](https://github.com/starkware-libs/cairo/blob/2ecb2216e132a2378a7da2a7989b7750f5d35c2c/crates/cairo-lang-semantic/src/items/tests/module#L5)):*
> ```
> //! > test_function_name
> test_function_diagnostics
> ```

add more tests.



_Code quote:_
```
//! > Test redefintion of the same name.

//! > test_function_name
test_function_diagnostics

//! > function
fn foo() {
   let a = 5;
}

//! > function_name
foo

//! > module_code
fn foo() {}

// TODO(ilya): Add other items (requires test_module_diagnostics).

//! > expected_diagnostics
error: The name `foo` is defined multiple times.
 --> lib.cairo:4:1
fn foo() {
^********^
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1618)* status: 35 of 39 files reviewed, 3 unresolved discussions (waiting on @orizi, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 100 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1618#-NKsY9XZDP_9SCpD_78Y:-NKvs_-h1OVZHknvwkrA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2ecb2216e132a2378a7da2a7989b7750f5d35c2c/crates/cairo-lang-semantic/src/db.rs#L100)):*
> ```XML
>     /// Private query to compute data about the module.
>     #[salsa::invoke(items::module::priv_module_items_data)]
>     fn priv_module_items_data(&self, module_id: ModuleId) -> Maybe<Arc<ModuleItemsData>>;
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/items/module.rs` line 43 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1618#-NKsXTqJ9Fn43g1GB9fr:-NKvrBKB9tk3NVBnJ1BJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2ecb2216e132a2378a7da2a7989b7750f5d35c2c/crates/cairo-lang-semantic/src/items/module.rs#L43)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

probably leaving the first is ok.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/tests/module` line 5 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1618#-NKsXjmn4u7kVLq5w-ia:-NKvsZ484zn81IQEf-UX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2ecb2216e132a2378a7da2a7989b7750f5d35c2c/crates/cairo-lang-semantic/src/items/tests/module#L5)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add more tests.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1618#-:-NKvx7BkEZcdf2DiLLas:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware and @yuvalsw)

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1618)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware and @yuvalsw)

**Pull request merged**
