### PR TITLE
Updated boxing to support non-1 sized types.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:c194c8ec

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1736)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/nullable.rs` line 34 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1736#-NLa7H-l3wZCBo99f40L:-NLaUfRSBtJZLsC0ZM6K:b3n82d7) ([raw file](https://github.com/starkware-libs/cairo/blob/e97b5eaee2e659dde4b5cbe9bd8960cf319ace8c/crates/cairo-lang-sierra/src/extensions/modules/nullable.rs#L34)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Add a TODO to support it in the future, maybe with a trivial non optimized implementation (e.g. bool)
</blockquote></details>

Instead already added support for objects of size 0
___
*[`tests/e2e_test_data/libfuncs/box` line 135 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1736#-NLa7YjmBLQBRhP1jRix:-NLaUSbC8qprUSDCYoAj:bw5ip0z) ([raw file](https://github.com/starkware-libs/cairo/blob/e97b5eaee2e659dde4b5cbe9bd8960cf319ace8c/tests/e2e_test_data/libfuncs/box#L135)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Why no test no `Box<()>`?
</blockquote></details>

That was a good touch, this causes a libfunc that return () - this has interesting and problematic results. (Unit type result seems to sierra like 'return nothing ' which causes a mismatch)
Would probably test with an empty struct and add todo.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1736)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`tests/e2e_test_data/libfuncs/box` line 146 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1736#-NLkH9SZ1dT1KrYOp-Ai:-NLkH9SZ1dT1KrYOp-Aj:b-ns2gqa) ([raw file](https://github.com/starkware-libs/cairo/blob/30f5e54fe73006645f685048847f89863aa3396d/tests/e2e_test_data/libfuncs/box#L146)):*
> ```
> //! > cairo
> fn foo(x: ()) -> Box::<()> {
>     into_box::<()>(x)
> ```

Will this work? If so, remove the argument.



_Suggestion:_
```
into_box::<()>(())
```
___
*[`tests/e2e_test_data/libfuncs/box` line 215 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1736#-NLkHTvs9tMj-XsV8Ff3:-NLkHTvs9tMj-XsV8Ff4:b-cvo2xi) ([raw file](https://github.com/starkware-libs/cairo/blob/30f5e54fe73006645f685048847f89863aa3396d/tests/e2e_test_data/libfuncs/box#L215)):*
> ```
> struct Empty {}
> fn foo(x: Empty) -> Box::<Empty> {
>     into_box::<Empty>(x)
> ```

Same here: `into_box::<Empty>(Empty{})`

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1736)* status: all files reviewed, 5 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 112 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1736#-NLkJK6KCWngZQ0tVdyg:-NLkJK6KCWngZQ0tVdyh:bkerxuk) ([raw file](https://github.com/starkware-libs/cairo/blob/30f5e54fe73006645f685048847f89863aa3396d/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L112)):*
> ```XML
>         Box(libfunc) => match libfunc {
>             BoxConcreteLibfunc::Into(libfunc) => {
>                 vec![ops.const_cost(info_provider.type_size(&libfunc.ty) as i32)]
> ```

We shouldn't use `as`, we should use something that panics.
If the best thing provided by the std lib is `try_into().unwrap()`, I think we should write a utility function for this.



_Code quote:_
```XML
 as i32
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/boxing.rs` line 29 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1736#-NLkI8GX8W7vbp45I-8Y:-NLkI8GX8W7vbp45I-8Z:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/30f5e54fe73006645f685048847f89863aa3396d/crates/cairo-lang-sierra-to-casm/src/invocations/boxing.rs#L29)):*
> ```XML
>     let mut casm_builder = CasmBuilder::default();
>     let addr = if operand.cells.is_empty() {
>         // In cases of a zero sized var, we just simulate a non-zero addr.
> ```





_Suggestion:_
```XML
// In cases of a zero-sized variable, we just simulate a non-zero address.
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1736)* status: all files reviewed, 5 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 112 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1736#-NLkJK6KCWngZQ0tVdyg:-NLkzpsK54Wcqna31Ss-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/30f5e54fe73006645f685048847f89863aa3396d/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L112)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

We shouldn't use `as`, we should use something that panics.
If the best thing provided by the std lib is `try_into().unwrap()`, I think we should write a utility function for this.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/boxing.rs` line 29 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1736#-NLkI8GX8W7vbp45I-8Y:-NLkzw_nCzmjXYzi63hp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/30f5e54fe73006645f685048847f89863aa3396d/crates/cairo-lang-sierra-to-casm/src/invocations/boxing.rs#L29)):*
> ```XML
>     let mut casm_builder = CasmBuilder::default();
>     let addr = if operand.cells.is_empty() {
>         // In cases of a zero sized var, we just simulate a non-zero addr.
> ```

Done.
___
*[`tests/e2e_test_data/libfuncs/box` line 146 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1736#-NLkH9SZ1dT1KrYOp-Ai:-NLl-Euv4uSaLLJ1TGf5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/30f5e54fe73006645f685048847f89863aa3396d/tests/e2e_test_data/libfuncs/box#L146)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Will this work? If so, remove the argument.
</blockquote></details>

Done.
___
*[`tests/e2e_test_data/libfuncs/box` line 215 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1736#-NLkHTvs9tMj-XsV8Ff3:-NLl-FfEDrkFgMkqLaDu:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/30f5e54fe73006645f685048847f89863aa3396d/tests/e2e_test_data/libfuncs/box#L215)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Same here: `into_box::<Empty>(Empty{})`
</blockquote></details>

Done.

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r4, 2 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1736)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @liorgold2)

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1736#-:-NLq8WpU1gppHoPNYtpo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
