### PR TITLE
Contract now does not generate logic within generated wrapper modules.

### PR DESCRIPTION
**Pull request by orizi**
For externalization - only `use`s wrappers.
For storage, no inner module.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3868)

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3868)* status: all files reviewed, 7 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 167 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3868#-NbQ3f7d90SJf4wIadDJ:-NbQJnJV8v0S6gGNundD:b-8u3mng) ([raw file](https://github.com/starkware-libs/cairo/blob/eff96f1b26dff1d5cf1f918ce3f3db9217273d0a/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L167)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

why do you need indoc here?
</blockquote></details>

so i won't get the extra tabs.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/contract` line 268 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3868#-NbQ--KMEyEZpkTsAxtm:-NbQJZfG4CqeEcBoC6D4:btu537n) ([raw file](https://github.com/starkware-libs/cairo/blob/eff96f1b26dff1d5cf1f918ce3f3db9217273d0a/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/contract#L268)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

then you can use them without adding the "__wrapper"
</blockquote></details>

that won't help - as i'd still use the function_id itself, which has the name including wrapper.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3868)* status: all files reviewed, 7 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/contract` line 268 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3868#-NbQ--KMEyEZpkTsAxtm:-NbQV2S-6K-lwfweox0Y:b-vxp6qp) ([raw file](https://github.com/starkware-libs/cairo/blob/eff96f1b26dff1d5cf1f918ce3f3db9217273d0a/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/contract#L268)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

that won't help - as i'd still use the function_id itself, which has the name including wrapper.
</blockquote></details>

In Sierra it indeede wouldn't. But in test you'll call __external::name and not __external::__wrapped_name

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3868)* status: all files reviewed, 4 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/contract.rs` line 136 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3868#-NbQ5ejp38ntb2e6SYTk:-NbR8QQo0JIRzoenkuHG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/eff96f1b26dff1d5cf1f918ce3f3db9217273d0a/crates/cairo-lang-starknet/src/contract.rs#L136)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Then you can do it with a db .module_uses_ids(module_id). ... .map(|use_id| ...) instead of a for + pushing to a mut vec of functions.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/contract_test.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3868#-NbQ0VTW4uuMZ7BZCNYN:-NbR8TozBgjFdTYz672K:b-11nmhx) ([raw file](https://github.com/starkware-libs/cairo/blob/eff96f1b26dff1d5cf1f918ce3f3db9217273d0a/crates/cairo-lang-starknet/src/contract_test.rs#L51)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

change should be reverted with the "as" I suggested
</blockquote></details>

it won't :(
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/contract` line 268 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3868#-NbQ--KMEyEZpkTsAxtm:-NbR8zkc6eZI-17zwHAe:bm4gdph) ([raw file](https://github.com/starkware-libs/cairo/blob/eff96f1b26dff1d5cf1f918ce3f3db9217273d0a/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/contract#L268)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

In Sierra it indeede wouldn't. But in test you'll call __external::name and not __external::__wrapped_name
</blockquote></details>

i don't really feel a need to make the ugly operation of directly calling a wrapper pretty, but let us do this just for backwards compatibility.

**Comment by yuvalsw** [comment]
*[`crates/cairo-lang-starknet/src/contract_test.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3868#-NbQ0VTW4uuMZ7BZCNYN:-NbTO4sX9RVbG84bBnC3:bm05v47) ([raw file](https://github.com/starkware-libs/cairo/blob/eff96f1b26dff1d5cf1f918ce3f3db9217273d0a/crates/cairo-lang-starknet/src/contract_test.rs#L51)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it won't :(
</blockquote></details>

Ah, I see why, should consider fixing it (not here), but unrelated.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3868#-:-NbTOKcI8vnCkjGj-Oqa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
