### PR TITLE
Handling illegal abi arguments.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4129)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4129)* status: all files reviewed, 7 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 3703 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4129#-NfF_sJKEDRj7yNA4Noz:-NfF_sJKEDRj7yNA4Np-:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9b48c0c77f15a37ac1195ef48c9a1a68785dc93f/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L3703)):*
> ```
> 
>     #[abi(v0)]
>     impl Alias = SomeImpl<ContractState>;
> ```





_Suggestion:_
```
s = super::SomeImpl<Contr
```
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 3706 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4129#-NfF_ylg9yi4aODgOqqt:-NfF_ylg9yi4aODgOqqu:bcw68n3) ([raw file](https://github.com/starkware-libs/cairo/blob/9b48c0c77f15a37ac1195ef48c9a1a68785dc93f/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L3706)):*
> ```
> 
>     #[abi(embed)]
>     impl InlineImpl of SomeTrait<ContractState> {
> ```

define SomeTrait as an interface and user super:: here.



_Code quote:_
```
SomeTrait
```
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 265 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4129#-NfFaLbo1Luf1-f3LWVp:-NfFaLbo1Luf1-f3LWVq:b8vstza) ([raw file](https://github.com/starkware-libs/cairo/blob/9b48c0c77f15a37ac1195ef48c9a1a68785dc93f/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L265)):*
> ```XML
>             }
>         }
>         ast::Item::ImplAlias(alias_ast) if alias_ast.has_attr(db, ABI_ATTR) => {
> ```

this is redundant work. use the result from the query_attr inside the arm.



_Code quote:_
```XML
alias_ast.has_attr(
```
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 274 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4129#-NfFadjW1Rt89UJTClkE:-NfFadjW1Rt89UJTClkF:b-3qnc53) ([raw file](https://github.com/starkware-libs/cairo/blob/9b48c0c77f15a37ac1195ef48c9a1a68785dc93f/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L274)):*
> ```XML
>                     message: format!(
>                         "The '{ABI_ATTR}' attribute must have the '{ABI_ATTR_EMBED_V0_ARG}' \
>                          argument.",
> ```

suggestion



_Suggestion:_
```XML
                        "The '{ABI_ATTR}' attribute for impl aliases only support the '{ABI_ATTR_EMBED_V0_ARG}' \
                         argument.",
```
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 451 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4129#-NfFbLnJ6AOz9ovtoVwA:-NfFbLnJ6AOz9ovtoVwB:b-khmh16) ([raw file](https://github.com/starkware-libs/cairo/blob/9b48c0c77f15a37ac1195ef48c9a1a68785dc93f/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L451)):*
> ```XML
>     None,
>     PerItem,
>     Embed,
> ```

This is actually a good place to document what each of them does.



_Code quote:_
```XML
    PerItem,
    Embed,
```
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 470 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4129#-NfFbxlzCvIQPZ_wELoG:-NfFbxlzCvIQPZ_wELoH:b-3qnc53) ([raw file](https://github.com/starkware-libs/cairo/blob/9b48c0c77f15a37ac1195ef48c9a1a68785dc93f/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L470)):*
> ```XML
>                 message: format!(
>                     "The '{ABI_ATTR}' attribute must have the '{ABI_ATTR_PER_ITEM_ARG}' or \
>                      '{ABI_ATTR_EMBED_V0_ARG}' argument.",
> ```

suggestion



_Suggestion:_
```XML
                    "The '{ABI_ATTR}' attribute for impl aliases only supports the '{ABI_ATTR_PER_ITEM_ARG}' or the \
                     '{ABI_ATTR_EMBED_V0_ARG}' argument.",
```
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 477 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4129#-NfFcNlzBzvs0ywzamOS:-NfFcNlzBzvs0ywzamOT:bt8svd) ([raw file](https://github.com/starkware-libs/cairo/blob/9b48c0c77f15a37ac1195ef48c9a1a68785dc93f/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L477)):*
> ```XML
>         }
>     } else if has_v0_attribute(db, diagnostics, imp, EXTERNAL_ATTR) {
>         ImplAbiConfig::Embed
> ```

this is actually a third thing now. "External", I guess.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4129)* status: all files reviewed, 7 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 3703 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4129#-NfF_sJKEDRj7yNA4Noz:-NfFdeEc7s3dg5UuQ__S:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9b48c0c77f15a37ac1195ef48c9a1a68785dc93f/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L3703)):*
> ```
> 
>     #[abi(v0)]
>     impl Alias = SomeImpl<ContractState>;
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 3706 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4129#-NfF_ylg9yi4aODgOqqt:-NfFdhTS-zumLImsGjSD:b-74mwfv) ([raw file](https://github.com/starkware-libs/cairo/blob/9b48c0c77f15a37ac1195ef48c9a1a68785dc93f/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L3706)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

define SomeTrait as an interface and user super:: here.
</blockquote></details>

this would just generate extra uninteresting code.
Done. the `super::`.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 265 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4129#-NfFaLbo1Luf1-f3LWVp:-NfFexuv53mX2iLcYRAh:bjyxp6r) ([raw file](https://github.com/starkware-libs/cairo/blob/9b48c0c77f15a37ac1195ef48c9a1a68785dc93f/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L265)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

this is redundant work. use the result from the query_attr inside the arm.
</blockquote></details>

this validates cases for multiple ABI attributes.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 274 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4129#-NfFadjW1Rt89UJTClkE:-NfFev2OABkI9KMeq_1s:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9b48c0c77f15a37ac1195ef48c9a1a68785dc93f/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L274)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

suggestion
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 451 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4129#-NfFbLnJ6AOz9ovtoVwA:-NfFejHD8dwZrYCPD8Wc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9b48c0c77f15a37ac1195ef48c9a1a68785dc93f/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L451)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

This is actually a good place to document what each of them does.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 470 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4129#-NfFbxlzCvIQPZ_wELoG:-NfFf7GABSelTmns_oOd:bhse4yf) ([raw file](https://github.com/starkware-libs/cairo/blob/9b48c0c77f15a37ac1195ef48c9a1a68785dc93f/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L470)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

suggestion
</blockquote></details>

this isn't an impl alias.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 477 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4129#-NfFcNlzBzvs0ywzamOS:-NfFf9T98Mw5iMV4Ksef:br7kdr2) ([raw file](https://github.com/starkware-libs/cairo/blob/9b48c0c77f15a37ac1195ef48c9a1a68785dc93f/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L477)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

this is actually a third thing now. "External", I guess.
</blockquote></details>

not really - at least in this context (not abi.rs) these act exactly the same way.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4129)* status: all files reviewed, 6 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 3706 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4129#-NfF_ylg9yi4aODgOqqt:-NfFzWJdBCAT0Lw1VanU:b7s23mh) ([raw file](https://github.com/starkware-libs/cairo/blob/9b48c0c77f15a37ac1195ef48c9a1a68785dc93f/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L3706)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this would just generate extra uninteresting code.
Done. the `super::`.
</blockquote></details>

But otherwise you have an uninteresting diagnostic, which is worse IMO because when you read this test, you read the diags, not the generated code.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 265 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4129#-NfFaLbo1Luf1-f3LWVp:-NfFzyIaBa4hDHSG2vZS:b7l9955) ([raw file](https://github.com/starkware-libs/cairo/blob/9b48c0c77f15a37ac1195ef48c9a1a68785dc93f/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L265)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this validates cases for multiple ABI attributes.
</blockquote></details>

You can still do it with only a single pass over the attrs.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 470 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4129#-NfFbxlzCvIQPZ_wELoG:-NfG0geeDgrCsLmGxUfd:bxr29) ([raw file](https://github.com/starkware-libs/cairo/blob/9b48c0c77f15a37ac1195ef48c9a1a68785dc93f/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L470)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this isn't an impl alias.
</blockquote></details>

I copy-pasted. Meant "for impls" here. To be consistent with the diag for impl aliases.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 477 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4129#-NfFcNlzBzvs0ywzamOS:-NfG17vrA98v1fZNn16C:bty1g0g) ([raw file](https://github.com/starkware-libs/cairo/blob/9b48c0c77f15a37ac1195ef48c9a1a68785dc93f/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L477)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

not really - at least in this context (not abi.rs) these act exactly the same way.
</blockquote></details>

You did add eventually, right?
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 409 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4129#-NfG-ljb8kgQlpMtWGHb:-NfG-ljb8kgQlpMtWGHc:b-t902ss) ([raw file](https://github.com/starkware-libs/cairo/blob/137e43162fe8faac4f8bde93c38ab261ae38ebdf/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L409)):*
> ```XML
>             entry_point_kind
>         } else {
>             // is_embed || is_external
> ```

adjust



_Code quote:_
```XML
// is_embed || is_external
```
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 442 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4129#-NfG0-cG7BaehVmsv2uv:-NfG0-cG7BaehVmsv2uw:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/137e43162fe8faac4f8bde93c38ab261ae38ebdf/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L442)):*
> ```XML
>     PerItem,
>     /// The impl is marked with `#[abi(embed_v0)]`. The entire impl is embedded into the ABI as
>     /// external functions.
> ```





_Suggestion:_
```XML
    /// The impl is marked with `#[abi(embed_v0)]`. The entire impl and the interface are embedded into the ABI.
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4129)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 265 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4129#-NfFaLbo1Luf1-f3LWVp:-NfG2pbdAPgvJaqe4Ooc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9b48c0c77f15a37ac1195ef48c9a1a68785dc93f/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L265)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

You can still do it with only a single pass over the attrs.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 470 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4129#-NfFbxlzCvIQPZ_wELoG:-NfG3DF74LH_JismG5M8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9b48c0c77f15a37ac1195ef48c9a1a68785dc93f/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L470)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I copy-pasted. Meant "for impls" here. To be consistent with the diag for impl aliases.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 477 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4129#-NfFcNlzBzvs0ywzamOS:-NfG3GioCVafssbpHO-R:b-nd9m2f) ([raw file](https://github.com/starkware-libs/cairo/blob/9b48c0c77f15a37ac1195ef48c9a1a68785dc93f/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L477)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

You did add eventually, right?
</blockquote></details>

yes, part of the rebase.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 409 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4129#-NfG-ljb8kgQlpMtWGHb:-NfG3-ch89k9fUL91EUB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/137e43162fe8faac4f8bde93c38ab261ae38ebdf/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L409)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

adjust
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 442 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4129#-NfG0-cG7BaehVmsv2uv:-NfG35Dt6uDg9WJwGwQD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/137e43162fe8faac4f8bde93c38ab261ae38ebdf/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L442)):*
> ```XML
>     PerItem,
>     /// The impl is marked with `#[abi(embed_v0)]`. The entire impl is embedded into the ABI as
>     /// external functions.
> ```

Done.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4129)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 3706 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4129#-NfF_ylg9yi4aODgOqqt:-NfG4sLf4S10Xt--dDHw:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9b48c0c77f15a37ac1195ef48c9a1a68785dc93f/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L3706)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

But otherwise you have an uninteresting diagnostic, which is worse IMO because when you read this test, you read the diags, not the generated code.
</blockquote></details>

Done.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4129#-:-NfG6Gzd-mA5uUCYyiTg:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 272 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4129#-NfG5sag8Z4DImpJiYih:-NfG5sag8Z4DImpJiYii:b-3vpfz4) ([raw file](https://github.com/starkware-libs/cairo/blob/d155d0ca1fe502f4688e5c9c45174b485e7a2d2b/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L272)):*
> ```XML
>                 .query_attr(db, ABI_ATTR)
>                 .iter()
>                 .all(|attr| !is_single_arg_attr(db, attr, ABI_ATTR_EMBED_V0_ARG))
> ```

nit: change to any, without the '!', and handle the good case first.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 414 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4129#-NfG642l2F_CzjwsiAJv:-NfG642l2F_CzjwsiAJw:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d155d0ca1fe502f4688e5c9c45174b485e7a2d2b/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L414)):*
> ```XML
>             entry_point_kind
>         } else {
>             // matches!(abi_config, ImplAbiConfig::Embed || ImplAbiConfig::External)
> ```





_Suggestion:_
```XML
s!(abi_config, ImplAbiConfig::Embed | ImplAbiConfig::Ext
```

**Review by yuvalsw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4129)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4129)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 272 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4129#-NfG5sag8Z4DImpJiYih:-NfG70mPCoGB10KW-HUD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d155d0ca1fe502f4688e5c9c45174b485e7a2d2b/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L272)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

nit: change to any, without the '!', and handle the good case first.
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4129)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4129)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
