### PR TITLE
Expose PanicDestruct instead of Drop.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6021)

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6021)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/circuit.cairo` line 160 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6021#-O1qgRS9E9GHrib2J8uE:-O1qsSBPEgFiv92HGh5z:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/e1ca99b91d950d534accd7dab97105490b55a4aa/corelib/src/circuit.cairo#L160)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

consider making `PanicDestructForDestruct` pub(crate) and:
</blockquote></details>





_Code snippet:_
```Cairo
 --> corelib/src/circuit.cairo:136:47
    pub impl PanicDestructAddInputResult<C> = PanicDestructForDestruct<super::AddInputResult<C>>;
                                              ^**********************^
```

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/circuit.cairo` line 160 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6021#-O1qgRS9E9GHrib2J8uE:-O1uA-NF9lx9EPjUBWSi:byt9jcr) ([raw file](https://github.com/starkware-libs/cairo/blob/e1ca99b91d950d534accd7dab97105490b55a4aa/corelib/src/circuit.cairo#L160)):*
> ```Cairo
> impl PanicDestructAddInputResult<C> = internal::PanicDestructAddInputResult<C>;
> impl PanicDestructCircuitData<C> = internal::PanicDestructCircuitData<C>;
> impl PanicDestructCircuitInputAccumulator<C> = internal::PanicDestructCircuitInputAccumulator<C>;
> ```

should I make PanicDestructForDestruct public?

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/circuit.cairo` line 160 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6021#-O1qgRS9E9GHrib2J8uE:-O1uAg6Y5jXvkCrE0rl0:b-6uqait) ([raw file](https://github.com/starkware-libs/cairo/blob/e1ca99b91d950d534accd7dab97105490b55a4aa/corelib/src/circuit.cairo#L160)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

should I make PanicDestructForDestruct public?
</blockquote></details>

I guess pub(crate) also works.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6021#-:-O1uDdE4892z7eM-eXbo:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
