### PR TITLE
Use module_item_by_name.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1624)

### CODE REVIEW

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1624#-:-NKrs-MW5n3yZwz_hm7j:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1624#-:-NKs4kRIBRcviDognSH-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-starknet/src/contract.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1624#-NKs4SIP43fFbOaLPW4P:-NKs4SIP43fFbOaLPW4Q:b-1jtysl) ([raw file](https://github.com/starkware-libs/cairo/blob/3d81c96bf3d7b55986f83836394fd6d4be038574/crates/cairo-starknet/src/contract.rs#L72)):*
> ```XML
>         .module_item_by_name(generated_module_id, EXTERNAL_MODULE.into())
>         .to_option()
>         .with_context(|| "Failed to get generated module items.")?
> ```

Fix the error message. Same in the other places in this PR

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-starknet/src/contract.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1624#-NKs4SIP43fFbOaLPW4P:-NKsC8A09EFdNgNIrDI9:bxh2dde) ([raw file](https://github.com/starkware-libs/cairo/blob/3d81c96bf3d7b55986f83836394fd6d4be038574/crates/cairo-starknet/src/contract.rs#L72)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Fix the error message. Same in the other places in this PR
</blockquote></details>

what should be the fixed error message?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1624)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-starknet/src/contract.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1624#-NKs4SIP43fFbOaLPW4P:-NKsIaQXERKthYulP8np:b2ai93r) ([raw file](https://github.com/starkware-libs/cairo/blob/3d81c96bf3d7b55986f83836394fd6d4be038574/crates/cairo-starknet/src/contract.rs#L72)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what should be the fixed error message?
</blockquote></details>

+ this error is mainly for us and module_item_by_name can only fail if you can't get the module items.

should I use unwarp here?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1624)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-starknet/src/contract.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1624#-NKs4SIP43fFbOaLPW4P:-NKsKopI5Vwu6tn7xRH3:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/3d81c96bf3d7b55986f83836394fd6d4be038574/crates/cairo-starknet/src/contract.rs#L72)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

+ this error is mainly for us and module_item_by_name can only fail if you can't get the module items.

should I use unwarp here?
</blockquote></details>

done.



_Code quote:_
```XML
.module_item
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1624#-:-NKsL26_B8t7B7eLHRn1:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1624)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1624)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1624#-:-NKtlpkpELExS1E5kSYo:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/contract.rs` line 72 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1624#-NKtlZ7wDhtaEyZE1ZRL:-NKtlZ7wDhtaEyZE1ZRM:b-yfccib) ([raw file](https://github.com/starkware-libs/cairo/blob/8de6335fa7fb45cf00633ae2afddad2f38d67cce/crates/cairo-lang-starknet/src/contract.rs#L72)):*
> ```XML
>         .module_item_by_name(generated_module_id, EXTERNAL_MODULE.into())
>         .to_option()
>         .with_context(|| "Failed to lookup an item in the generated module.")?
> ```

Nit: You can specify which module.
Here and below

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/contract.rs` line 72 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1624#-NKtlZ7wDhtaEyZE1ZRL:-NKvMvml9KrBjvBrTA3L:bknhelb) ([raw file](https://github.com/starkware-libs/cairo/blob/8de6335fa7fb45cf00633ae2afddad2f38d67cce/crates/cairo-lang-starknet/src/contract.rs#L72)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Nit: You can specify which module.
Here and below
</blockquote></details>

That is exacly why I wanted to leave the old comment.

The failure here is before the lookup.  if the lookup happens and the item is not found it is handled below.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1624)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
