### PR TITLE
Make find_impls_at_module() work with Uninferred impls

### PR DESCRIPTION
**Pull request by spapinistarkware**
In preperation for resolving ImplAlias

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2821)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* 04-14-Better_methdo_and_impl_resolution
  * **PR #2821** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2821" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2821?utm_source=stack-comment).

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2821)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 954 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2821#-NT1XkAI8S728xjw9GyC:-NT1XkAJBajCviOHAfrk:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/434fca1314b4c6344d9e2360e09d059cd4d9c231/crates/cairo-lang-semantic/src/expr/inference.rs#L954)):*
> ```XML
>     }
> 
>     pub fn can_infer_impl(
> ```

doc



_Code quote:_
```XML
can_infer_impl
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2821)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 954 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2821#-NT1XkAI8S728xjw9GyC:-NT3FCEJCGSNMgoJZFMV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/434fca1314b4c6344d9e2360e09d059cd4d9c231/crates/cairo-lang-semantic/src/expr/inference.rs#L954)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2821#-:-NT3WOEF4hBudbEd9mN0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
