### PR TITLE
Use OutputVarInfo::new_builtin.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5927)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5927)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/circuit.rs` line 862 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5927#-O0hyVo25d3LwVGOx3Tw:-O0hyVo25d3LwVGOx3Tx:b-ykxuvo) ([raw file](https://github.com/starkware-libs/cairo/blob/13806283d25f39a6ecdcfe067b5ede8d68f9c170/crates/cairo-lang-sierra/src/extensions/modules/circuit.rs#L862)):*
> ```XML
> 
>         Ok(LibfuncSignature::new_non_branch(
>             vec![range_check96_type.clone(), mul_mod_builtin_ty.clone(), guarantee_ty, zero, one],
> ```

and allow_with_const as well - right?



_Code quote:_
```XML
range_check96_type.clone(), mul_mod_builtin_ty.clone()
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra/src/extensions/modules/circuit.rs` line 862 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5927#-O0hyVo25d3LwVGOx3Tw:-O0iCICk4i2oF54Usget:bhtb9uv) ([raw file](https://github.com/starkware-libs/cairo/blob/13806283d25f39a6ecdcfe067b5ede8d68f9c170/crates/cairo-lang-sierra/src/extensions/modules/circuit.rs#L862)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

and allow_with_const as well - right?
</blockquote></details>

do you mean `with_allow_add_const`?

for the range_check96 I can't for the mul_mod it depends on the size of the circuit

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra/src/extensions/modules/circuit.rs` line 862 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5927#-O0hyVo25d3LwVGOx3Tw:-O0iCfNUBuKFEYHJ3yx2:b-1sos62) ([raw file](https://github.com/starkware-libs/cairo/blob/13806283d25f39a6ecdcfe067b5ede8d68f9c170/crates/cairo-lang-sierra/src/extensions/modules/circuit.rs#L862)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

do you mean `with_allow_add_const`?

for the range_check96 I can't for the mul_mod it depends on the size of the circuit
</blockquote></details>

Lior suggested adding 
maybe_tempvar which allocates a tempvar if the offset exceeds 15bits

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5927)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/circuit.rs` line 862 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5927#-O0hyVo25d3LwVGOx3Tw:-O0iHrFN5jnMSXHKsA-M:b64ggo9) ([raw file](https://github.com/starkware-libs/cairo/blob/13806283d25f39a6ecdcfe067b5ede8d68f9c170/crates/cairo-lang-sierra/src/extensions/modules/circuit.rs#L862)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Lior suggested adding 
maybe_tempvar which allocates a tempvar if the offset exceeds 15bits
</blockquote></details>

Isn't this the failure guarantee? It shouldn't be dependent on the circuit size, no?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra/src/extensions/modules/circuit.rs` line 862 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5927#-O0hyVo25d3LwVGOx3Tw:-O0iMeXWD-ESij-PWjml:b-55mazx) ([raw file](https://github.com/starkware-libs/cairo/blob/13806283d25f39a6ecdcfe067b5ede8d68f9c170/crates/cairo-lang-sierra/src/extensions/modules/circuit.rs#L862)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Isn't this the failure guarantee? It shouldn't be dependent on the circuit size, no?
</blockquote></details>

I meant that the const in add_const (n_actual_mul_mods * MOD_BUILTIN_INSTANCE_SIZE) could exceed 15 bits.

I guess this is not the case since `n_actual_mul_mods` is a tempvar and not a const in our implementation.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5927#-:-O0iOovZ7HXgSlbk9eb3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5927#-:-O0iOwUfDdc6_saMOonj:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
