### PR TITLE
Added `*Assign` ops and Depracated `*Eq` ops.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #5716
- #5715
- #5714
- #5713
- #5712
- #5679 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5679)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 9 of 12 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5679)* status: 10 of 12 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/byte_array.cairo` line 352 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5679#-NzWtXkDA2xcUlLymdlU:-NzWtXkDA2xcUlLymdlV:b-cy1sr2) ([raw file](https://github.com/starkware-libs/cairo/blob/3cf96da8b18d939eec632a928f70d0e45050824a/corelib/src/byte_array.cairo#L352)):*
> ```Cairo
> }
> #[feature("deprecated-op-assign-traits")]
> impl ByteArrayAddEq of core::traits::AddEq<ByteArray> {
> ```

For consistency.



_Suggestion:_
```Cairo
mpl ByteArrayAddEq of AddEq<ByteArray> {
```
___
*[`corelib/src/ops.cairo` line 4 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5679#-NzWsZk36PUA4nN7oNPL:-NzWsZk36PUA4nN7oNPM:b-uhkziv) ([raw file](https://github.com/starkware-libs/cairo/blob/3cf96da8b18d939eec632a928f70d0e45050824a/corelib/src/ops.cairo#L4)):*
> ```Cairo
> pub use index::{Index, IndexView};
> 
> mod arith;
> ```

It's not the Rust equivalent name right? Consider opening it to discussion.



_Code quote:_
```Cairo
mod arith;
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5679)* status: 10 of 12 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`corelib/src/ops.cairo` line 4 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5679#-NzWsZk36PUA4nN7oNPL:-NzX5unnBFzCv8-t02wL:b-cx4psz) ([raw file](https://github.com/starkware-libs/cairo/blob/3cf96da8b18d939eec632a928f70d0e45050824a/corelib/src/ops.cairo#L4)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

It's not the Rust equivalent name right? Consider opening it to discussion.
</blockquote></details>

Exact same as rust, and more importantly, not pub

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 11 of 12 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5679#-:-NzXqPASCS9DcvtaawMI:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5679#-:-NzXs1sB8FGjX9zHUb2c:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

___
*[`corelib/src/byte_array.cairo` line 352 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5679#-NzWtXkDA2xcUlLymdlU:-NzXrx3N58O4n86tgRmv:b-zbjba) ([raw file](https://github.com/starkware-libs/cairo/blob/293c82e8a42d5fea0b3f67858cf726a4d85d54b6/corelib/src/byte_array.cairo#L352)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

don't think it is required - as it should be removed from the prelude as well.
(this will just be added to be removed)
</blockquote></details>

You didn't add the path in all other places, but not really important.

**Pull request merged**
