### PR TITLE
Fix cycles in impl definitions.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3201)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3201)* status: 1 of 8 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 301 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3201#-NVyY7BbARtZcBlk-hSO:-NVyY7BbARtZcBlk-hSP:b-mdrhss) ([raw file](https://github.com/starkware-libs/cairo/blob/f9b50bbd1abc5370046c7c50c040c25915d6906c/crates/cairo-lang-semantic/src/resolve/mod.rs#L301)):*
> ```XML
>         &mut self,
>         diagnostics: &mut SemanticDiagnostics,
>         segments: &mut Peekable<std::slice::Iter<'_, ast::PathSegment>>,
> ```

Add doc for the arg

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3201)* status: 1 of 8 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 311 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3201#-NW0uZMjBO4S8BrXBD7m:-NW0uZMjBO4S8BrXBD7n:b-c0eyym) ([raw file](https://github.com/starkware-libs/cairo/blob/f9b50bbd1abc5370046c7c50c040c25915d6906c/crates/cairo-lang-semantic/src/resolve/mod.rs#L311)):*
> ```XML
>         Ok(match segments.peek().unwrap() {
>             syntax::node::ast::PathSegment::WithGenericArgs(generic_segment) => {
>                 if !allow_generic_args {
> ```

Make this an early return (i.e. no 'else')

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3201)* status: 2 of 8 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 259 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3201#-NW0ugmP-Qv0kBRrSnwO:-NW0ugmP-Qv0kBRrSnwP:b-5myvlt) ([raw file](https://github.com/starkware-libs/cairo/blob/f9b50bbd1abc5370046c7c50c040c25915d6906c/crates/cairo-lang-semantic/src/resolve/mod.rs#L259)):*
> ```XML
>         path: impl AsSegments,
>         item_type: NotFoundItemType,
>         allow_generic_args: bool,
> ```

Add 2 public functions, one `resolve_generic_path` that behaves like the old one, and another `resolve_generic_path_with_args`. Rename this function and make it private.
This will make the interface to the `Resolver` a little cleaner.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3201)* status: 2 of 8 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 189 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3201#-NW0vMeR0oF1z1GRQtMn:-NW0vMeR0oF1z1GRQtMo:boibrat) ([raw file](https://github.com/starkware-libs/cairo/blob/f9b50bbd1abc5370046c7c50c040c25915d6906c/crates/cairo-lang-semantic/src/items/imp.rs#L189)):*
> ```XML
> 
> /// Query implementation of [crate::db::SemanticGroup::impl_def_generic_params_data].
> pub fn impl_def_generic_params_data(
> ```

This isn't really the end goal we discussed.
I think each generic param should have its own semantic model in its own query.
Then, this function would go away.
right?

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3201)* status: 2 of 8 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/substitution.rs` line 307 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3201#-NW0vi5uERO-4AzK6J7O:-NW0vi5uERO-4AzK6J7P:b5yhw9x) ([raw file](https://github.com/starkware-libs/cairo/blob/f9b50bbd1abc5370046c7c50c040c25915d6906c/crates/cairo-lang-semantic/src/substitution.rs#L307)):*
> ```XML
>             if let Some(generic_arg) = self.substitution.get(&generic_param) {
>                 let impl_id = *extract_matches!(generic_arg, GenericArgumentId::Impl);
>                 return Ok(impl_id);
> ```

Document here and bove why we don't need to rewrite:
```
Substitution is guaranteed to not contain its own variables.
```
Also, add a TODO to actually do this reduction, perhaps in the ctor, and check for cycles there.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3201)* status: 3 of 8 files reviewed, 8 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`tests/bug_samples/issue2995.cairo` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3201#-NW0wXGW5WcNMq02LPsk:-NW0wXGW5WcNMq02LPsl:bf6zj3l) ([raw file](https://github.com/starkware-libs/cairo/blob/f9b50bbd1abc5370046c7c50c040c25915d6906c/tests/bug_samples/issue2995.cairo#L1)):*
> ```Cairo
> trait Trait0<T> {}
> ```

Is this relevant?
___
*[`tests/bug_samples/issue2995.cairo` line 4 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3201#-NW0w71XCDj9MMgGonZ9:-NW0w71XCDj9MMgGonZA:byd9d2v) ([raw file](https://github.com/starkware-libs/cairo/blob/f9b50bbd1abc5370046c7c50c040c25915d6906c/tests/bug_samples/issue2995.cairo#L4)):*
> ```Cairo
> trait ATrait {}
> 
> struct B<T, G, impl GTriat: ATrait> {
> ```

I know the typo is in the source material, but we can fix names here.GTrait



_Suggestion:_
```Cairo
GImpl
```
___
*[`tests/bug_samples/issue2995.cairo` line 4 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3201#-NW0wc1Y0FLdSoBvFvs8:-NW0wc1Y0FLdSoBvFvs9:b-s202lm) ([raw file](https://github.com/starkware-libs/cairo/blob/f9b50bbd1abc5370046c7c50c040c25915d6906c/tests/bug_samples/issue2995.cairo#L4)):*
> ```Cairo
> trait ATrait {}
> 
> struct B<T, G, impl GTriat: ATrait> {
> ```

If we have `impl X:Copy<G>` here, we would still panic with a cycle?
We should still solve this somehow. We should add a Task.
First, let's just not panic:) Find out why cycle handling doesn't work here.
And in the future, actually handle it unless there is a "real" cycle.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3201)* status: 1 of 8 files reviewed, 7 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/substitution.rs` line 307 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3201#-NW0vi5uERO-4AzK6J7O:-NWBZTdf6GRBb7SyyutH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f9b50bbd1abc5370046c7c50c040c25915d6906c/crates/cairo-lang-semantic/src/substitution.rs#L307)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Document here and bove why we don't need to rewrite:
```
Substitution is guaranteed to not contain its own variables.
```
Also, add a TODO to actually do this reduction, perhaps in the ctor, and check for cycles there.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 189 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3201#-NW0vMeR0oF1z1GRQtMn:-NWBccVj3sQKqsAFxIsx:b-wc4p2w) ([raw file](https://github.com/starkware-libs/cairo/blob/f9b50bbd1abc5370046c7c50c040c25915d6906c/crates/cairo-lang-semantic/src/items/imp.rs#L189)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This isn't really the end goal we discussed.
I think each generic param should have its own semantic model in its own query.
Then, this function would go away.
right?
</blockquote></details>

I am working on it in a separate PR, but it is more complicated than we thought as other parts relies on the resolver holding concrete items. I think it requires a discussion about the whole resolving strategy. My idea is to add a `generic_items_in_context` queries  for each item, WDYT?
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 259 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3201#-NW0ugmP-Qv0kBRrSnwO:-NWB_W8R1f1y8pA-rUB3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f9b50bbd1abc5370046c7c50c040c25915d6906c/crates/cairo-lang-semantic/src/resolve/mod.rs#L259)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Add 2 public functions, one `resolve_generic_path` that behaves like the old one, and another `resolve_generic_path_with_args`. Rename this function and make it private.
This will make the interface to the `Resolver` a little cleaner.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 301 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3201#-NVyY7BbARtZcBlk-hSO:-NWB_lNL3TZKYkRtkj6L:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f9b50bbd1abc5370046c7c50c040c25915d6906c/crates/cairo-lang-semantic/src/resolve/mod.rs#L301)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Add doc for the arg
</blockquote></details>

Done.
___
*[`tests/bug_samples/issue2995.cairo` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3201#-NW0wXGW5WcNMq02LPsk:-NWBcY-yCp-Ibnmk2-9i:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f9b50bbd1abc5370046c7c50c040c25915d6906c/tests/bug_samples/issue2995.cairo#L1)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Is this relevant?
</blockquote></details>

Done.
___
*[`tests/bug_samples/issue2995.cairo` line 4 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3201#-NW0wc1Y0FLdSoBvFvs8:-NWBcLO-EvmSpIcMIX7K:b6fjqu2) ([raw file](https://github.com/starkware-libs/cairo/blob/f9b50bbd1abc5370046c7c50c040c25915d6906c/tests/bug_samples/issue2995.cairo#L4)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

If we have `impl X:Copy<G>` here, we would still panic with a cycle?
We should still solve this somehow. We should add a Task.
First, let's just not panic:) Find out why cycle handling doesn't work here.
And in the future, actually handle it unless there is a "real" cycle.
</blockquote></details>

No, we raise a diagnostic that multiple impls of Copy<G> were detected. 
___
*[`tests/bug_samples/issue2995.cairo` line 4 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3201#-NW0w71XCDj9MMgGonZ9:-NWBcYFJCfrtJLz7TwXX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f9b50bbd1abc5370046c7c50c040c25915d6906c/tests/bug_samples/issue2995.cairo#L4)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I know the typo is in the source material, but we can fix names here.GTrait
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3201)* status: 1 of 8 files reviewed, 8 unresolved discussions (waiting on @gilbens-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 260 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3201#-NWBvGQ2ABMdNmLrw-PF:-NWBvGQ2ABMdNmLrw-PG:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/816c2e1ef999983e8d48ab69a7e909d930ce062f/crates/cairo-lang-semantic/src/resolve/mod.rs#L260)):*
> ```XML
>         self.resolve_generic_path_inner(diagnostics, path, item_type, false)
>     }
>     pub fn resolve_generic_path_with_args(
> ```

doc



_Code quote:_
```XML
    pub fn resolve_generic_path(
        &mut self,
        diagnostics: &mut SemanticDiagnostics,
        path: impl AsSegments,
        item_type: NotFoundItemType,
    ) -> Maybe<ResolvedGenericItem> {
        self.resolve_generic_path_inner(diagnostics, path, item_type, false)
    }
    pub fn resolve_generic_path_with_args(
```
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 320 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3201#-NWBvKg_66pFo8C0nBHp:-NWBvKg_66pFo8C0nBHq:bhcs52x) ([raw file](https://github.com/starkware-libs/cairo/blob/816c2e1ef999983e8d48ab69a7e909d930ce062f/crates/cairo-lang-semantic/src/resolve/mod.rs#L320)):*
> ```XML
>         diagnostics: &mut SemanticDiagnostics,
>         segments: &mut Peekable<std::slice::Iter<'_, ast::PathSegment>>,
>         // Allow and ignore generic arguments in the path.
> ```

move the doc to the doc of the function.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3201)* status: all files reviewed, 10 unresolved discussions (waiting on @gilbens-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 217 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3201#-NWCDDnnDMifgQCEcSrS:-NWCDDnnDMifgQCEcSrT:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/cfa1259a5fd360a2d9cff56ac310577c2007b17e/crates/cairo-lang-semantic/src/items/imp.rs#L217)):*
> ```XML
> }
> 
> pub fn impl_def_generic_params(
> ```

doc



_Code quote:_
```XML
impl_def_generic_param
```
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 264 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3201#-NWCDKLZ6DKcgdnlX5fo:-NWCDKLZ6DKcgdnlX5fp:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/cfa1259a5fd360a2d9cff56ac310577c2007b17e/crates/cairo-lang-semantic/src/items/imp.rs#L264)):*
> ```XML
> }
> /// Query implementation of [crate::db::SemanticGroup::impl_def_concrete_trait].
> pub fn impl_concrete_trait(db: &dyn SemanticGroup, impl_id: ImplId) -> Maybe<ConcreteTraitId> {
> ```





_Suggestion:_
```XML
        .and_then(|generic_item| try_extract_matches!(generic_item, ResolvedGenericItem::Trait))
        .ok_or_else(|| diagnostics.report(&trait_path_syntax, NotATrait))
}

/// Query implementation of [crate::db::SemanticGroup::impl_def_concrete_trait].
pub fn impl_concrete_trait(db: &dyn SemanticGroup, impl_id: ImplId) -> Maybe<ConcreteTraitId> {
```
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 787 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3201#-NWCDSkF754OapE-OcnD:-NWCDSkF754OapE-OcnE:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/cfa1259a5fd360a2d9cff56ac310577c2007b17e/crates/cairo-lang-semantic/src/items/imp.rs#L787)):*
> ```XML
>         }
>     }
>     fn trait_id(&self, db: &dyn SemanticGroup) -> Maybe<TraitId> {
> ```





_Suggestion:_
```XML
        }
    }

    fn trait_id(&self, db: &dyn SemanticGroup) -> Maybe<TraitId> {
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3201)* status: 6 of 8 files reviewed, 10 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 217 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3201#-NWCDDnnDMifgQCEcSrS:-NWpaPq26iBx1N3jyCmg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cfa1259a5fd360a2d9cff56ac310577c2007b17e/crates/cairo-lang-semantic/src/items/imp.rs#L217)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 264 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3201#-NWCDKLZ6DKcgdnlX5fo:-NWpahsz22T1DOijhZh-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cfa1259a5fd360a2d9cff56ac310577c2007b17e/crates/cairo-lang-semantic/src/items/imp.rs#L264)):*
> ```XML
> }
> /// Query implementation of [crate::db::SemanticGroup::impl_def_concrete_trait].
> pub fn impl_concrete_trait(db: &dyn SemanticGroup, impl_id: ImplId) -> Maybe<ConcreteTraitId> {
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 787 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3201#-NWCDSkF754OapE-OcnD:-NWpahYl7NUNdwUbu2CW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cfa1259a5fd360a2d9cff56ac310577c2007b17e/crates/cairo-lang-semantic/src/items/imp.rs#L787)):*
> ```XML
>         }
>     }
>     fn trait_id(&self, db: &dyn SemanticGroup) -> Maybe<TraitId> {
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 260 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3201#-NWBvGQ2ABMdNmLrw-PF:-NWpbRUmAe66kq3sIZl-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/816c2e1ef999983e8d48ab69a7e909d930ce062f/crates/cairo-lang-semantic/src/resolve/mod.rs#L260)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 4 of 7 files at r2, 2 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3201)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @orizi)

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3201)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 790 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3201#-NWqddMY2i9xDjiFBj8E:-NWqddMY2i9xDjiFBj8F:b-qpeckz) ([raw file](https://github.com/starkware-libs/cairo/blob/0e4642ab2acb91d3bc40ab8612d3f7cb18ac7d04/crates/cairo-lang-semantic/src/items/imp.rs#L790)):*
> ```XML
>         }
>     }
>     
> ```

Fix whitespace

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3201)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3201#-:-NWqdk_r9A8DRSNMFWpO:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3201#-:-NXJyMz15t273brmAlqb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
