### PR TITLE
Adding vm simulation for keccak.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2888)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2888)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/test/keccak_test.cairo` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2888#-NTSl3AU4hyXBkjAd1uC:-NTSl3AU4hyXBkjAd1uD:b4r3261) ([raw file](https://github.com/starkware-libs/cairo/blob/7db8d38515b495cd1f65c8a27dc262bcc125d583/corelib/src/test/keccak_test.cairo#L28)):*
> ```Cairo
>     assert(
>         starknet::syscalls::keccak_syscall(input.span()).unwrap_syscall() == u256 {
>             high: 0x528d145dfe6571afd2eb808dfba4703c, low: 0x388da73622e8fdd5ec687be9c50d2218
> ```

I got
low:  0xec687be9c50d2218388da73622e8fdd5
high: 0xd2eb808dfba4703c528d145dfe6571af



_Code quote:_
```Cairo
  high: 0x528d145dfe6571afd2eb808dfba4703c, low: 0x388da73622e8fdd5ec687be9c50d2218
```
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 466 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2888#-NTSgHet0vu8nSjM5xjb:-NTSgHet0vu8nSjM5xjc:b-41sh46) ([raw file](https://github.com/starkware-libs/cairo/blob/7db8d38515b495cd1f65c8a27dc262bcc125d583/crates/cairo-lang-runner/src/casm_run/mod.rs#L466)):*
> ```XML
>                     })?;
>                 } else if selector == "Keccak".as_bytes() {
>                     check_handle_oog(4, 5000, &mut |vm| {
> ```

This should depend on the input size, right?



_Code quote:_
```XML
check_handle_oog
```
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 473 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2888#-NTSgT_gCG3p2W9pkqAm:-NTSgT_gCG3p2W9pkqAn:b-blkph3) ([raw file](https://github.com/starkware-libs/cairo/blob/7db8d38515b495cd1f65c8a27dc262bcc125d583/crates/cairo-lang-runner/src/casm_run/mod.rs#L473)):*
> ```XML
>                         if data_end_ptr <= data_start_ptr {
>                             return Ok(Some(Felt252::from_bytes_be(b"Invalid data range")));
>                         }
> ```

Do we need to check this?

it is enforced by sierra, right?



_Code quote:_
```XML
                        if data_end_ptr <= data_start_ptr {
                            return Ok(Some(Felt252::from_bytes_be(b"Invalid data range")));
                        }
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 495 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2888#-NTSlcVE0yC5iiHqVMe5:-NTSlcVE0yC5iiHqVMe6:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7db8d38515b495cd1f65c8a27dc262bcc125d583/crates/cairo-lang-runner/src/casm_run/mod.rs#L495)):*
> ```XML
>                             res_low_ptr,
>                             (Felt252::from(state[2]) << 64u32) + Felt252::from(state[3]),
>                         )?;
> ```





_Suggestion:_
```XML
                        let res_low_ptr = get_ptr(vm, cell, &(base_offset.clone() + 7u32))?;
                        let res_high_ptr = get_ptr(vm, cell, &(base_offset.clone() + 6u32))?;
                        
                        vm.insert_value(
                            res_low_ptr,
                            (Felt252::from(state[3]) << 64u32) + Felt252::from(state[2]),
                        )?;
                       
                        vm.insert_value(
                            res_high_ptr,
                            (Felt252::from(state[1]) << 64u32) + Felt252::from(state[0]),
                        )?;
                        
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 486 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2888#-NTSmM8C4eGcbskIowAI:-NTSmM8C4eGcbskIowAJ:btj1ttb) ([raw file](https://github.com/starkware-libs/cairo/blob/7db8d38515b495cd1f65c8a27dc262bcc125d583/crates/cairo-lang-runner/src/casm_run/mod.rs#L486)):*
> ```XML
>                             keccak::f1600(&mut state)
>                         }
>                         let res_high_ptr = get_ptr(vm, cell, &(base_offset.clone() + 6u32))?;
> ```

we define u256 as
struct u256 {
    low: u128,
    high: u128,
}



_Code quote:_
```XML
                        let res_high_ptr = get_ptr(vm, cell, &(base_offset.clone() + 6u32))?;
                        let res_low_ptr = get_ptr(vm, cell, &(base_offset.clone() + 7u32))?;
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2888)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 495 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2888#-NTSlcVE0yC5iiHqVMe5:-NTSmWsd6_zcqNM_Pmjj:b1rfppm) ([raw file](https://github.com/starkware-libs/cairo/blob/7db8d38515b495cd1f65c8a27dc262bcc125d583/crates/cairo-lang-runner/src/casm_run/mod.rs#L495)):*
> ```XML
>                             res_low_ptr,
>                             (Felt252::from(state[2]) << 64u32) + Felt252::from(state[3]),
>                         )?;
> ```

or maybe:
                     



_Suggestion:_
```XML
                       let res_low_ptr = get_ptr(vm, cell, &(base_offset.clone() + 6u32))?;                        
                       let res_high_ptr = get_ptr(vm, cell, &(base_offset.clone() + 7u32))?;

                        vm.insert_value(
                            res_low_ptr,
                            (Felt252::from(state[1]) << 64u32) + Felt252::from(state[0]),
                        )?;
          
                        vm.insert_value(
                            res_high_ptr,
                            (Felt252::from(state[3]) << 64u32) + Felt252::from(state[2]),
                        )?;
                     
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2888)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 486 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2888#-NTSmM8C4eGcbskIowAI:-NTUsft_1hO6bYzBvyi1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7db8d38515b495cd1f65c8a27dc262bcc125d583/crates/cairo-lang-runner/src/casm_run/mod.rs#L486)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

we define u256 as
struct u256 {
    low: u128,
    high: u128,
}
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2888#-:-NTgO2Te6gJ2WCGYkb5w:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by ilyalesokhin-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2888)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 473 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2888#-NTSgT_gCG3p2W9pkqAm:-NTgQ-CbACbajzdsVkhg:b-5h0omb) ([raw file](https://github.com/starkware-libs/cairo/blob/7db8d38515b495cd1f65c8a27dc262bcc125d583/crates/cairo-lang-runner/src/casm_run/mod.rs#L473)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

This also makes sure the span isn't empty, so partially 
</blockquote></details>

not 100% sure we should fail in this case, but I'm fine with failing here.

**Pull request merged**
