### PR TITLE
Destructors

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2537)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2537** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2537" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2537?utm_source=stack-comment).

**Comment by spapinistarkware** [comment]
Right now it's not very useful, it doesn add on panics. Ill add another commit to the stack before merging that adds the detructor calls after panic phase.

**Comment by spapinistarkware** [comment]
Right now it's not very useful, it doesn add on panics. Ill add another commit to the stack before merging that adds the detructor calls after panic phase.

**Review by spapinistarkware — COMMENTED** [review]
I changed it, it adds destructor calls after the panic phase. And gives correct borrow checking error pre monomorphization.
The issue left it that implicit finding should occure *after* the panic phase, and this new destructor phase, so we need to add *another* scc query. This will be done in another PR.
Until then, it wont be able to get rid of dicts =>  as a new implicit would need to be added, the segment manager,

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2537#-:-NQqIQhp5_DaZotLrNNv:b-ayw99x)* status: 0 of 27 files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 10 of 17 files at r1, 11 of 17 files at r2, 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2537)* status: 29 of 30 files reviewed, 5 unresolved discussions (waiting on @spapinistarkware)

___
*[`corelib/src/traits.cairo` line 93 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2537#-NQy1QMV0F3r0dst5s-1:-NQy1QMV0F3r0dst5s-2:bya8bmd) ([raw file](https://github.com/starkware-libs/cairo/blob/9d577b3c6127a019f730888e4da2bdddce6e7e79/corelib/src/traits.cairo#L93)):*
> ```Cairo
> }
> 
> // TODO(spapini): Remove this, it can lead to multiple impls and unwanted Destruct implementation.
> ```

you mean you just want to call the underlying drop or destruct according to what exists?



_Code quote:_
```Cairo
// TODO(spapini): Remove this, it can lead to multiple impls and unwanted Destruct implementation.
```
___
*[`crates/cairo-lang-lowering/src/destructs.rs` line 14 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2537#-NQy5Ir0DftgYjjRSfs4:-NQy5Ir0DftgYjjRSfs5:b-9sa1fo) ([raw file](https://github.com/starkware-libs/cairo/blob/9d577b3c6127a019f730888e4da2bdddce6e7e79/crates/cairo-lang-lowering/src/destructs.rs#L14)):*
> ```XML
> 
> pub type LoweredDemand = Demand<VariableId>;
> pub struct DestructAdder<'a> {
> ```

doc - including the algorithm itself.



_Code quote:_
```XML
pub struct DestructAdder<'a> {
```
___
*[`crates/cairo-lang-lowering/src/objects.rs` line 104 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2537#-NQy2KRV1cjBiAZccIe9:-NQy2KRV1cjBiAZccIeA:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/9d577b3c6127a019f730888e4da2bdddce6e7e79/crates/cairo-lang-lowering/src/objects.rs#L104)):*
> ```XML
>     /// Can the type be (trivially) duplicated.
>     pub duplicatable: InferenceResult<()>,
>     pub destruct_impl: InferenceResult<ImplId>,
> ```

doc



_Code quote:_
```XML
    pub duplicatable: InferenceResult<()>,
    pub destruct_impl: InferenceResult<ImplId>,
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 17 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2537)* status: all files reviewed, 5 unresolved discussions (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2537)* status: all files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/dict.cairo` line 22 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2537#-NQy0waB6zurOG2DPy_Q:-NQyCWzs14DnqfGzSNmY:b-hsi8tg) ([raw file](https://github.com/starkware-libs/cairo/blob/9d577b3c6127a019f730888e4da2bdddce6e7e79/corelib/src/dict.cairo#L22)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

are these related?
</blockquote></details>

Yes. Since it is nopanic, if I dont declare it as one, I get unecessary checks for dtors/drops wher eI dont need.
___
*[`corelib/src/hash.cairo` line 105 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2537#-NQy0zuB3_oCJD9hC-9g:-NQyCgns1Nmz0ZRz1lAv:b-ogn0u5) ([raw file](https://github.com/starkware-libs/cairo/blob/9d577b3c6127a019f730888e4da2bdddce6e7e79/corelib/src/hash.cairo#L105)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why is this required now?
</blockquote></details>

hash() is not defined as `nopanic` (which make sense), so we might panic before actually consuming e1
___
*[`corelib/src/traits.cairo` line 93 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2537#-NQy1QMV0F3r0dst5s-1:-NQyCwTO0mpD5PtQdcOD:bfsgmx7) ([raw file](https://github.com/starkware-libs/cairo/blob/9d577b3c6127a019f730888e4da2bdddce6e7e79/corelib/src/traits.cairo#L93)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you mean you just want to call the underlying drop or destruct according to what exists?
</blockquote></details>

No, I want Destruct to always exists, but I wonder what happens if users want to specify their own dtors for droppable types. Actually, maybe it shouldnt be supported anyway, so myabe it's ok.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2537)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/destructs.rs` line 14 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2537#-NQy5Ir0DftgYjjRSfs4:-NR-QvSHDYhYbL_RJkHX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9d577b3c6127a019f730888e4da2bdddce6e7e79/crates/cairo-lang-lowering/src/destructs.rs#L14)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc - including the algorithm itself.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/objects.rs` line 104 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2537#-NQy2KRV1cjBiAZccIe9:-NR-Pz8gBoLRysnBhY74:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9d577b3c6127a019f730888e4da2bdddce6e7e79/crates/cairo-lang-lowering/src/objects.rs#L104)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Pull request merged**
