### PR TITLE
checking last n blocks, adding check to nightly

### PR DESCRIPTION
**Pull request by Tomer-StarkWare**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5627)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5627)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 169 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5627#-Nya4DUh8baumXAhhPBF:-Nya4DUiEpwa7XIePuyl:b-2yy45k) ([raw file](https://github.com/starkware-libs/cairo/blob/baf4a132adf38432fca73a63fe384041d8bea1ba/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L169)):*
> ```XML
>         let fullnode_args = args.fullnode_args.unwrap();
>         let (start_block, end_block) = if let Some(last_n_blocks) = fullnode_args.last_n_blocks {
>             let end_block = get_last_block_number(&fullnode_url).await?;
> ```

+1, as you don't scan the end block.
___
*[`scripts/starknet_sierra_validate.sh` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5627#-Nya2bso460KZlZOHhdc:-Nya2bspEwSAVXqc0SY1:by2stb7) ([raw file](https://github.com/starkware-libs/cairo/blob/baf4a132adf38432fca73a63fe384041d8bea1ba/scripts/starknet_sierra_validate.sh#L9)):*
> ```Shell
> fi
> 
> cargo run --bin starknet-sierra-upgrade-validate -- --fullnode-url 'https://papyrus-mainnet-dan.sw-dev.io/rpc/v0_7_0' --last-n-blocks $N_BLOCKS
> ```

Add empty line.
___
*[`scripts/starknet_sierra_validate.sh` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5627#-Nya2tUW8yLp-YDcRfrJ:-Nya2tUW8yLp-YDcRfrK:bw6ikf0) ([raw file](https://github.com/starkware-libs/cairo/blob/baf4a132adf38432fca73a63fe384041d8bea1ba/scripts/starknet_sierra_validate.sh#L9)):*
> ```Shell
> fi
> 
> cargo run --bin starknet-sierra-upgrade-validate -- --fullnode-url 'https://papyrus-mainnet-dan.sw-dev.io/rpc/v0_7_0' --last-n-blocks $N_BLOCKS
> ```

Use default env var value (look at other scripts here as to how)

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5627)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 169 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5627#-Nya4DUh8baumXAhhPBF:-NynSTXc52NWCDt5hr_4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/baf4a132adf38432fca73a63fe384041d8bea1ba/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L169)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

+1, as you don't scan the end block.
</blockquote></details>

Done.
___
*[`scripts/starknet_sierra_validate.sh` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5627#-Nya2bso460KZlZOHhdc:-NynSeXj-QhyUPQV5ElS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/baf4a132adf38432fca73a63fe384041d8bea1ba/scripts/starknet_sierra_validate.sh#L9)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Add empty line.
</blockquote></details>

Done.
___
*[`scripts/starknet_sierra_validate.sh` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5627#-Nya2tUW8yLp-YDcRfrJ:-NynSfBQBS8DCn356MZu:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/baf4a132adf38432fca73a63fe384041d8bea1ba/scripts/starknet_sierra_validate.sh#L9)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Use default env var value (look at other scripts here as to how)
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5627#-:-NynVuQV0ckhvVQPazne:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5627)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
