### PR TITLE
Core Lib Documentation: `box` module

### PR DESCRIPTION
**Pull request by TAdev0**

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6651)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @TAdev0)

___
*[`corelib/src/box.cairo` line 5 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6651#-OBalI5u1WLt66vGPMtn:-OBalI5u1WLt66vGPMto:b-605b52) ([raw file](https://github.com/starkware-libs/cairo/blob/b85ea7ccaac5b858c4033d964d7d0fb2ae62ab2c/corelib/src/box.cairo#L5)):*
> ```Cairo
> //! `Box<T>` provides a way to store a value of type `T` in Cairo VM's _boxed_ segment,
> //! leaving only a pointer in the execution segment. This allows for:
> //!
> ```

This is information about the platform - not the language - shouldn't be the main point of the doc IMO.
(can exist, as a note, not as the main thing)



_Code quote:_
```Cairo
//! A smart pointer type that stores its value in a dedicated memory segment.
//!
//! `Box<T>` provides a way to store a value of type `T` in Cairo VM's _boxed_ segment,
//! leaving only a pointer in the execution segment. This allows for:
//!
```

**Review by enitrat — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6651)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/box.cairo` line 5 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6651#-OBalI5u1WLt66vGPMtn:-OBdlMTy8q5FCpLzfxLN:b-5ur33h) ([raw file](https://github.com/starkware-libs/cairo/blob/b85ea7ccaac5b858c4033d964d7d0fb2ae62ab2c/corelib/src/box.cairo#L5)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

This is information about the platform - not the language - shouldn't be the main point of the doc IMO.
(can exist, as a note, not as the main thing)
</blockquote></details>

How would you want to see this exactly? I think it's important and thus should not be left out of the documentation (like notes on the memory layouts for Dicts, Arrays, etc).

It's true that now with Cairo Native this is not necessarily true 🤔. Any format you would prefer for these notes?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6651)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @enitrat)

___
*[`corelib/src/box.cairo` line 5 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6651#-OBalI5u1WLt66vGPMtn:-OBdn9YH26BCGpwK_MIr:b8668xd) ([raw file](https://github.com/starkware-libs/cairo/blob/b85ea7ccaac5b858c4033d964d7d0fb2ae62ab2c/corelib/src/box.cairo#L5)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

How would you want to see this exactly? I think it's important and thus should not be left out of the documentation (like notes on the memory layouts for Dicts, Arrays, etc).

It's true that now with Cairo Native this is not necessarily true 🤔. Any format you would prefer for these notes?
</blockquote></details>

As i said - should be as a note in the documentation - but not the top of the definition.

so should probably be at the end, and include the word "note".

I'm really not convinced this is important note for developers, as they should know how to use it (interface) and why to use it (makes moving a value around much cheaper) - knowing how this is actually cheaper under the hood shouldn't be as interesting.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6651)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @enitrat)

___
*[`corelib/src/box.cairo` line 5 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6651#-OBalI5u1WLt66vGPMtn:-OBdnwhY012iaHiC7uWV:b-7ezncx) ([raw file](https://github.com/starkware-libs/cairo/blob/b85ea7ccaac5b858c4033d964d7d0fb2ae62ab2c/corelib/src/box.cairo#L5)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

As i said - should be as a note in the documentation - but not the top of the definition.

so should probably be at the end, and include the word "note".

I'm really not convinced this is important note for developers, as they should know how to use it (interface) and why to use it (makes moving a value around much cheaper) - knowing how this is actually cheaper under the hood shouldn't be as interesting.
</blockquote></details>

same thing should be true for array and for dict.

**Review by enitrat — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6651)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/box.cairo` line 5 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6651#-OBalI5u1WLt66vGPMtn:-OBePgmr2mvYx2QI8jV7:b-s622lo) ([raw file](https://github.com/starkware-libs/cairo/blob/b85ea7ccaac5b858c4033d964d7d0fb2ae62ab2c/corelib/src/box.cairo#L5)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

same thing should be true for array and for dict.
</blockquote></details>

I see, thanks

**Comment by TAdev0** [comment]
@orizi  @enitrat  I added as a `//` comment the cairo VM memory details. Dont know if its better to keep it or remove it given that Cairo-VM is not the only platform to run Cairo code and I suppose the Cairo library should be platform agnostic

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6651)* status: all files reviewed, 1 unresolved discussion (waiting on @TAdev0)

___
*[`corelib/src/box.cairo` line 130 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6651#-OBjoNuICBUVhuPYIX3d:-OBjoNuICBUVhuPYIX3e:b4i7ysl) ([raw file](https://github.com/starkware-libs/cairo/blob/70fcd1ffc6e7b723b7623c78047526051e00bb96/corelib/src/box.cairo#L130)):*
> ```Cairo
>     }
> }
> // NOTE: A `Box<T>` is a smart pointer type that provides a way to store a value of type `T` in
> ```

this can be at the bottom of the top doc IMO.

**Comment by TAdev0** [comment]
@orizi  updated

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6651#-:-OBkCUqr8MHZeUyaw1hM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TAdev0)

**Pull request merged**
