### PR TITLE
Add has_early_return information to PrivInlineData.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1956)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1956)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1956#-NMx1ksa5scBnasxQXsQ:-NMx1ksa5scBnasxQXsR:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/2416af2e1344727a5e60f8cfcd55a76322212206/crates/cairo-lang-lowering/src/inline/mod.rs#L42)):*
> ```XML
> 
> #[derive(Debug, PartialEq, Eq)]
> pub struct InlineInfo {
> ```

doc



_Code quote:_
```XML
#[derive(Debug, PartialEq, Eq)]
pub struct InlineInfo {
```
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1956#-NMx1xImE1eoR34AQqeT:-NMx1xImE1eoR34AQqeU:b-l6mkjh) ([raw file](https://github.com/starkware-libs/cairo/blob/2416af2e1344727a5e60f8cfcd55a76322212206/crates/cairo-lang-lowering/src/inline/mod.rs#L64)):*
> ```XML
> /// Checks if the given function can be inlined.
> /// If report_diagnostics is true, adds a diagnostics with the reason that prevents inlining.
> fn check_inlinable(
> ```

rename



_Code quote:_
```XML
check_inlinable
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1956)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1956#-NMx1ksa5scBnasxQXsQ:-NMxcq8t0lA6t9eJdl8d:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2416af2e1344727a5e60f8cfcd55a76322212206/crates/cairo-lang-lowering/src/inline/mod.rs#L42)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1956#-NMx1xImE1eoR34AQqeT:-NMxcptb-G1pgW4ImgY8:b-64vtsp) ([raw file](https://github.com/starkware-libs/cairo/blob/2416af2e1344727a5e60f8cfcd55a76322212206/crates/cairo-lang-lowering/src/inline/mod.rs#L64)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rename
</blockquote></details>

Done.

hopefully it won't be reverted.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1956#-:-NMxg07X1PDa3s8LtbdC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1956)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
