### PR TITLE
Simplify 'le' and 'lt' hints in overflowing_sub and comparisons.

### PR DESCRIPTION
**Pull request by liorgold2**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2903)

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
> Reviewed 8 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2903)* status: all files reviewed, 2 unresolved discussions (waiting on @Alon-Ti and @liorgold2)

**Review by Alon-Ti — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2903)* status: all files reviewed, 3 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/uint.rs` line 178 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2903#-NTiG1Mh-v5HqwEKGVKt:-NTiG1Mh-v5HqwEKGVKu:bbbusf1) ([raw file](https://github.com/starkware-libs/cairo/blob/0ccfc38a98bec6c7aadfb8a208ddfcc48645aa86/crates/cairo-lang-sierra-to-casm/src/invocations/uint.rs#L178)):*
> ```XML
>             hint TestLessThanOrEqual {lhs: b, rhs: a} into {dst: a_ge_b};
>             jump NoOverflow if a_ge_b != 0;
>             // Underflow:
> ```

Underflow -> Overflow
(https://www.quora.com/What-is-the-difference-between-overflow-and-underflow)

**Review by orizi — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2903)* status: all files reviewed, 3 unresolved discussions (waiting on @liorgold2)

**Review by orizi — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2903)* status: all files reviewed, 3 unresolved discussions (waiting on @liorgold2)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2903#-NTZ6mEB3b2n35iQwJrs:-NTnNvTUEAetCDgIHIFS:b-25vpko) (no related file):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

If I'm not mistaken this is not a problem since we're just changing hints, which are not part of the hash, so we should be fine. Am I missing something?

If we still want it in a late branch, let's open this branch now and merge this into that branch.
</blockquote></details>

i'm not sure - but still lets do that.

___

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2903)* status: 4 of 11 files reviewed, 2 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2903#-NTZ6mEB3b2n35iQwJrs:-NUG8YnnD1h8UbUrdP1_:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i'm not sure - but still lets do that.
</blockquote></details>

Done.

___

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2903)* status: 4 of 11 files reviewed, 2 unresolved discussions (waiting on @Alon-Ti and @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/uint.rs` line 178 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2903#-NTiG1Mh-v5HqwEKGVKt:-NUG9ueHEDGbKfxjzhuX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0ccfc38a98bec6c7aadfb8a208ddfcc48645aa86/crates/cairo-lang-sierra-to-casm/src/invocations/uint.rs#L178)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

Underflow -> Overflow
(https://www.quora.com/What-is-the-difference-between-overflow-and-underflow)
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 9 files at r1, 2 of 4 files at r2, 2 of 7 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2903#-:-NUGfosQ2JQ-mOd7DGoy:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Alon-Ti and @orizi)

**Review by liorgold2 — COMMENTED** [review]
> Dismissed @Alon-Ti and @orizi from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2903)* status: 10 of 15 files reviewed, all discussions resolved (waiting on @Alon-Ti, @orizi, and @spapinistarkware)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 6 files at r4, 3 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2903)* status: 13 of 15 files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 3 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2903)* status: 13 of 15 files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 2 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2903)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2903)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
