### PR TITLE
Added Sierra storage_write system call

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1379)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1379#-:-NJ_XHVV2Iws5p-kpBbk:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`crates/casm/src/builder.rs` line 228 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1379#-NJ_WpVbAu08aJQ0k8u6:-NJ_WpVbAu08aJQ0k8u7:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/720388da01b7142191ced2064970c6324f936d79/crates/casm/src/builder.rs#L228)):*
> ```XML
>     }
> 
>     pub fn add_system_call(&mut self, var: Var) {
> ```

doc



_Code quote:_
```XML
add_system_call
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1379)* status: 12 of 14 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/casm/src/builder.rs` line 228 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1379#-NJ_WpVbAu08aJQ0k8u6:-NJb0zsrD3NPSVQkEemD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/720388da01b7142191ced2064970c6324f936d79/crates/casm/src/builder.rs#L228)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1379)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1379)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
