### PR TITLE
feat: deterministic contract address calculation

### LINKED ISSUE #4375: bug: CASM runner assigns arbitrary contract addresses instead of using correct address computation
# Bug Report

**Cairo version:**
2.3.1

**Current behavior:**
Currently, the casm runner assigns arbitrary addresses to contracts deployed using `deploy_syscall`, incrementing them from 0.
https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-runner/src/casm_run/mod.rs#L947-L948

**Expected behavior:**
The contract addresses should be calculated according to the specifications.
```js
contract_address := pedersen(
    “STARKNET_CONTRACT_ADDRESS”,
    deployer_address,
    salt,
    class_hash,
    constructor_calldata_hash)
```

**Other information:**
### Why this matters

> this sole thing is blocking the UDC migration to cairo 1+

> It prevents us from testing anything relying on computation of starknet addresses

I am willing to try to submit a PR if this is accepted.

### PR DESCRIPTION
**Pull request by enitrat**
Closes #4375.

The CASM runner now computes addresses for deployed contracts according to the specification available [here](https://docs.starknet.io/documentation/architecture_and_concepts/Smart_Contracts/contract-address/). 

I tested the code with pre-computed values and verified that they match.
I also tested it in "prod" by running our codebase with this updated version of the runner. It correctly matches the expected contract address that we compute in our Cairo programs.

I am not very familiar with how the architecture is done, so I just added the computation functions inside `crates/cairo-lang-starknet/src/contract.rs` as it seemed like the most appropriate place.
Also, I'm not entirely sure how I should handle error management or if we should just panic when converting the compiler's `Felt252` type to the `FieldElement` type used in `pedersen`

Looking forward to your review!

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4391)

### CODE REVIEW

**Comment by enitrat** [comment]
CI fails because of a clippy error, but it doesn't seem directly related to my changes

**Review by enitrat — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4391)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 982 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4391#-NjDFILy5xAX4vFgsc1i:-NjDbRoo7kKGMZkr7r8_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/80cfc120368ac84ce9d8d234f138e7fc31915c92/crates/cairo-lang-runner/src/casm_run/mod.rs#L982)):*
> ```XML
>                 .starknet_state
>                 .open_caller_context((deployed_contract_address.clone(), new_caller_address));
>             let res = self.call_entry_point(gas_counter, runner, constructor, calldata, vm);
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/contract.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4391#-NjDFdqu4d33dy_eWITA:-NjDbW_C0YSm_Pzl47IA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/80cfc120368ac84ce9d8d234f138e7fc31915c92/crates/cairo-lang-starknet/src/contract.rs#L70)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

none of this is required for this crate.
move all these changes to the runner (in a new submodule)
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4391)* status: 5 of 9 files reviewed, 9 unresolved discussions (waiting on @enitrat)

___
*[`crates/cairo-lang-runner/Cargo.toml` line 31 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4391#-NjDhqmV00N9-lsEo63u:-NjDhqmV00N9-lsEo63v:b-i8c6b4) ([raw file](https://github.com/starkware-libs/cairo/blob/98321021191ebc58e38f2de67c563c7936c8ae03/crates/cairo-lang-runner/Cargo.toml#L31)):*
> ```TOML
> thiserror.workspace = true
> starknet-crypto = "0.6.1"
> hex = "0.4.3"
> ```

add both in the main .toml



_Suggestion:_
```TOML
starknet-crypto.workspace = true
hex.workspace = true
```
___
*[`crates/cairo-lang-runner/src/contract_address.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4391#-NjDmu-7640ZC5gtMm2A:-NjDmu-7640ZC5gtMm2B:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/98321021191ebc58e38f2de67c563c7936c8ae03/crates/cairo-lang-runner/src/contract_address.rs#L15)):*
> ```XML
> }
> 
> // 2 ** 251 - 256
> ```





_Suggestion:_
```XML
/// 2 ** 251 - 256
```
___
*[`crates/cairo-lang-runner/src/contract_address.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4391#-NjDmxImCE_r4w0-bNa4:-NjDmxImCE_r4w0-bNa5:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/98321021191ebc58e38f2de67c563c7936c8ae03/crates/cairo-lang-runner/src/contract_address.rs#L23)):*
> ```XML
> ]);
> 
> // Cairo string of "STARKNET_CONTRACT_ADDRESS"
> ```





_Suggestion:_
```XML
/// Cairo string of "STARKNET_CONTRACT_ADDRESS"
```
___
*[`crates/cairo-lang-runner/src/contract_address.rs` line 31 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4391#-NjDmz4p0rbhy1xvLKlX:-NjDmz4p0rbhy1xvLKlY:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/98321021191ebc58e38f2de67c563c7936c8ae03/crates/cairo-lang-runner/src/contract_address.rs#L31)):*
> ```XML
> ]);
> 
> fn felt252_to_field_element(input: &Felt252) -> anyhow::Result<FieldElement> {
> ```

doc
___
*[`crates/cairo-lang-runner/src/contract_address.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4391#-NjDkUUV7_OJOtioLG29:-NjDkUUV7_OJOtioLG2A:bq9y6kb) ([raw file](https://github.com/starkware-libs/cairo/blob/98321021191ebc58e38f2de67c563c7936c8ae03/crates/cairo-lang-runner/src/contract_address.rs#L33)):*
> ```XML
> fn felt252_to_field_element(input: &Felt252) -> anyhow::Result<FieldElement> {
>     FieldElement::from_bytes_be(&input.to_be_bytes())
>         .map_err(|_| anyhow::anyhow!("Failed to convert felt252 to field element."))
> ```

This should never fail - `unwrap` here would be easier to debug if and when it does happen.



_Code quote:_
```XML
map_err(|_| anyhow::anyhow!("Failed to convert felt252 to field element."))
```
___
*[`crates/cairo-lang-runner/src/contract_address.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4391#-NjDn1JzDEYnisS2MA8y:-NjDn1JzDEYnisS2MA8z:b5jj9ql) ([raw file](https://github.com/starkware-libs/cairo/blob/98321021191ebc58e38f2de67c563c7936c8ae03/crates/cairo-lang-runner/src/contract_address.rs#L43)):*
> ```XML
>     constructor_calldata: &[Felt252],
>     deployer_address: &Felt252,
> ) -> anyhow::Result<Felt252> {
> ```

as above - can't actually fail.



_Code quote:_
```XML
anyhow::Result
```
___
*[`crates/cairo-lang-runner/src/lib.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4391#-NjDi3Qi2fA4Mko9yNnv:-NjDi3Qi2fA4Mko9yNnw:bpwpkn8) ([raw file](https://github.com/starkware-libs/cairo/blob/98321021191ebc58e38f2de67c563c7936c8ae03/crates/cairo-lang-runner/src/lib.rs#L43)):*
> ```XML
> 
> pub mod casm_run;
> pub mod contract_address;
> ```

make a non-pub submodule of casm_run.
___
*[`crates/cairo-lang-runner/src/casm_run/test.rs` line 446 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4391#-NjDiKNsDYDRs1teO6XA:-NjDiKNt82poBS3KNY45:bjz65lq) ([raw file](https://github.com/starkware-libs/cairo/blob/98321021191ebc58e38f2de67c563c7936c8ae03/crates/cairo-lang-runner/src/casm_run/test.rs#L446)):*
> ```XML
> #[test]
> fn test_calculate_contract_address() {
>     let salt = Felt252::from_bytes_be(&hex::decode("65766d5f61646472657373").unwrap());
> ```

also elsewhere
(and remove hex dependency)



_Suggestion:_
```XML
felt252_str!("0x65766d5f61646472657373");
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4391#-:-NjH5yW89UUL-y-xx43I:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @enitrat)

___
*[`crates/cairo-lang-runner/Cargo.toml` line 10 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4391#-NjH5ZwqETffKiB-QTQW:-NjH5ZwqETffKiB-QTQX:b-hfpv23) ([raw file](https://github.com/starkware-libs/cairo/blob/89505a49ab831d773473ea35491ba4c0a5608114/crates/cairo-lang-runner/Cargo.toml#L10)):*
> ```TOML
> 
> [dependencies]
> anyhow.workspace = true
> ```

remove.

**Review by enitrat — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4391)* status: all files reviewed, 1 unresolved discussion (waiting on @enitrat)

___
*[`crates/cairo-lang-runner/Cargo.toml` line 31 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4391#-NjDhqmV00N9-lsEo63u:-NjH54pj-069GdkiqOjr:b-a0eplv) ([raw file](https://github.com/starkware-libs/cairo/blob/98321021191ebc58e38f2de67c563c7936c8ae03/crates/cairo-lang-runner/Cargo.toml#L31)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add both in the main .toml
</blockquote></details>

Done. (removed hex)
___
*[`crates/cairo-lang-runner/src/casm_run/test.rs` line 446 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4391#-NjDiKNsDYDRs1teO6XA:-NjH5GiM5ytwyRDc81W7:boxapq3) ([raw file](https://github.com/starkware-libs/cairo/blob/98321021191ebc58e38f2de67c563c7936c8ae03/crates/cairo-lang-runner/src/casm_run/test.rs#L446)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

also elsewhere
(and remove hex dependency)
</blockquote></details>

Done. (used decimal value)
___
*[`crates/cairo-lang-runner/src/lib.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4391#-NjDi3Qi2fA4Mko9yNnv:-NjH5J-N7qZmU1s9RKsy:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/98321021191ebc58e38f2de67c563c7936c8ae03/crates/cairo-lang-runner/src/lib.rs#L43)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

make a non-pub submodule of casm_run.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runner/src/contract_address.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4391#-NjDmu-7640ZC5gtMm2A:-NjH57YT6-x2K_ISjkUA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/98321021191ebc58e38f2de67c563c7936c8ae03/crates/cairo-lang-runner/src/contract_address.rs#L15)):*
> ```XML
> }
> 
> // 2 ** 251 - 256
> ```

Done.
___
*[`crates/cairo-lang-runner/src/contract_address.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4391#-NjDmxImCE_r4w0-bNa4:-NjH57sz8DNEbhShse-P:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/98321021191ebc58e38f2de67c563c7936c8ae03/crates/cairo-lang-runner/src/contract_address.rs#L23)):*
> ```XML
> ]);
> 
> // Cairo string of "STARKNET_CONTRACT_ADDRESS"
> ```

Done.
___
*[`crates/cairo-lang-runner/src/contract_address.rs` line 31 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4391#-NjDmz4p0rbhy1xvLKlX:-NjH58ZyEixBmQXPGFTi:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/98321021191ebc58e38f2de67c563c7936c8ae03/crates/cairo-lang-runner/src/contract_address.rs#L31)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runner/src/contract_address.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4391#-NjDkUUV7_OJOtioLG29:-NjH59Ev-OPawwptHAO0:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/98321021191ebc58e38f2de67c563c7936c8ae03/crates/cairo-lang-runner/src/contract_address.rs#L33)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

This should never fail - `unwrap` here would be easier to debug if and when it does happen.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runner/src/contract_address.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4391#-NjDn1JzDEYnisS2MA8y:-NjH5AwoCxqG_OkeF_7Y:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/98321021191ebc58e38f2de67c563c7936c8ae03/crates/cairo-lang-runner/src/contract_address.rs#L43)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

as above - can't actually fail.
</blockquote></details>

Done.

**Review by enitrat — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4391)* status: 7 of 10 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-runner/Cargo.toml` line 10 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4391#-NjH5ZwqETffKiB-QTQW:-NjH6JsO-qSNyndRIz4U:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/89505a49ab831d773473ea35491ba4c0a5608114/crates/cairo-lang-runner/Cargo.toml#L10)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4391)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enitrat)

**Review by enitrat — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4391#-:-NjS8xRL2f_kvVySFr2C:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enitrat)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4391)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enitrat)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4391)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enitrat)

**Comment by enitrat** [comment]
> (waiting on @enitrat)

I'm not super familiar with Reviewable do I need to do something?

**Review by orizi — APPROVED** [review]
No, will merge on Sunday 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4391#-:-NjSD3nV1n1uNHZrIq8c:b-99nrat)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enitrat)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4391)* status: all files reviewed, 1 unresolved discussion (waiting on @enitrat)

___
*[`crates/cairo-lang-runner/src/casm_run/test.rs` line 445 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4391#-NjazIyw-7J8ZUkBdzwv:-NjaxuRUBjsWNJ13wh5s:bx14216) ([raw file](https://github.com/starkware-libs/cairo/blob/4fd18c1fa0f53d800323eff6a95547d2ce890ada/crates/cairo-lang-runner/src/casm_run/test.rs#L445)):*
> ```XML
> 
> #[test]
> fn test_calculate_contract_address() {
> ```

where did you bring these values from?
just to know the validation.

**Comment by enitrat** [comment]
I just used some values I used in my tests in Kakarot. I tested these values against the `starknet_api` crate and made sure the results were correct.

```rust
#[cfg(test)]
mod test {
    use starknet_api::{
        calldata,
        core::{calculate_contract_address, ClassHash, ContractAddress, PatriciaKey},
        hash::{StarkFelt, StarkHash},
        transaction::{Calldata, ContractAddressSalt},
    };
    use starknet_crypto::FieldElement;

    #[test]
    fn test_calc_ca() {
        let salt_felt = StarkFelt::try_from("0x65766d5f61646472657373").unwrap();
        let salt: ContractAddressSalt = ContractAddressSalt(salt_felt);
        let deployer_address_felt = StarkFelt::try_from("1").unwrap();
        let deployer_address: ContractAddress = ContractAddress(PatriciaKey::from(1_u128));
        let class_hash = StarkHash::try_from(
            "0x03ef34708a5a14ee92cfa571a1afdf331aa231d10d3f2f99ff1f8f7516a8c6d2",
        )
        .unwrap();
        let class_hash = ClassHash(class_hash);
        let calldata: Calldata = calldata!(deployer_address_felt, salt_felt);
        let deployed_contract_address =
            calculate_contract_address(salt, class_hash, &calldata, deployer_address).unwrap();

        let expected = ContractAddress(
            PatriciaKey::try_from(
                StarkHash::try_from(
                    "0x050f2821ed90360ac0508d52f8db1f87e541811773bce3dbcaf863c572cd696f",
                )
                .unwrap(),
            )
            .unwrap(),
        );

        assert_eq!(expected, deployed_contract_address);
    }
}

```

**Review by enitrat — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4391)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/casm_run/test.rs` line 445 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4391#-NjazIyw-7J8ZUkBdzwv:-Njb-3ic8J8XS8mQbMI_:b66z47s) ([raw file](https://github.com/starkware-libs/cairo/blob/4fd18c1fa0f53d800323eff6a95547d2ce890ada/crates/cairo-lang-runner/src/casm_run/test.rs#L445)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

where did you bring these values from?
just to know the validation.
</blockquote></details>

I just used some values I used in my tests in [Kakarot](https://github.com/kkrt-labs/kakarot-ssj/blob/b856ea00b06e7c2d0390ede54e561af70d6c54b7/crates/contracts/src/tests/test_kakarot_core.cairo#L139-L156). I tested these values against the `starknet_api` crate and made sure the results were correct.

```rust
#[cfg(test)]
mod test {
    use starknet_api::{
        calldata,
        core::{calculate_contract_address, ClassHash, ContractAddress, PatriciaKey},
        hash::{StarkFelt, StarkHash},
        transaction::{Calldata, ContractAddressSalt},
    };
    use starknet_crypto::FieldElement;

    #[test]
    fn test_calc_ca() {
        let salt_felt = StarkFelt::try_from("0x65766d5f61646472657373").unwrap();
        let salt: ContractAddressSalt = ContractAddressSalt(salt_felt);
        let deployer_address_felt = StarkFelt::try_from("1").unwrap();
        let deployer_address: ContractAddress = ContractAddress(PatriciaKey::from(1_u128));
        let class_hash = StarkHash::try_from(
            "0x03ef34708a5a14ee92cfa571a1afdf331aa231d10d3f2f99ff1f8f7516a8c6d2",
        )
        .unwrap();
        let class_hash = ClassHash(class_hash);
        let calldata: Calldata = calldata!(deployer_address_felt, salt_felt);
        let deployed_contract_address =
            calculate_contract_address(salt, class_hash, &calldata, deployer_address).unwrap();

        let expected = ContractAddress(
            PatriciaKey::try_from(
                StarkHash::try_from(
                    "0x050f2821ed90360ac0508d52f8db1f87e541811773bce3dbcaf863c572cd696f",
                )
                .unwrap(),
            )
            .unwrap(),
        );

        assert_eq!(expected, deployed_contract_address);
    }
}

```

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4391)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enitrat)

**Pull request merged**
