### PR TITLE
Add Circuit type.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5552)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5552)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/circuit.cairo` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5552#-NxhBW5JAcAnudjvTYe2:-NxhBW5JAcAnudjvTYe3:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/99981aecc04a67f58c55af4ff37e772054c286bd/corelib/src/circuit.cairo#L28)):*
> ```Cairo
> 
> 
> /// Defines an input for a circuit.
> ```





_Suggestion:_
```Cairo
pub extern type MulMod;

/// A wrapper to crate circuit.
pub extern type Circuit<Outputs>;

/// Defines an input for a circuit.
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/circuit.rs` line 364 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5552#-NxhBa67Etb1u4F6wXY0:-NxhBa67Etb1u4F6wXY1:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/99981aecc04a67f58c55af4ff37e772054c286bd/crates/cairo-lang-sierra/src/extensions/modules/circuit.rs#L364)):*
> ```XML
> 
> // A type that creates a circuit from a tuple of outputs.
> #[derive(Default)]
> ```





_Suggestion:_
```XML
/// A type that creates a circuit from a tuple of outputs.
#[derive(Default)]
```
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 455 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5552#-NxhC34cBmiIlm14DgXr:-NxhC34cBmiIlm14DgXs:b-bg8emf) ([raw file](https://github.com/starkware-libs/cairo/blob/99981aecc04a67f58c55af4ff37e772054c286bd/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L455)):*
> ```XML
> 
>     let circuits_info =
>         CircuitsInfo::new(&registry, program.type_declarations.iter().map(|td| &td.id))?;
> ```

shouldn't we still only iterate on the libfuncs - but just use the circuit type info?



_Code quote:_
```XML
        CircuitsInfo::new(&registry, program.type_declarations.iter().map(|td| &td.id))?;
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 455 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5552#-NxhC34cBmiIlm14DgXr:-NxuiTSH6eXCgZb7tj7t:b-9y44sg) ([raw file](https://github.com/starkware-libs/cairo/blob/99981aecc04a67f58c55af4ff37e772054c286bd/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L455)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

shouldn't we still only iterate on the libfuncs - but just use the circuit type info?
</blockquote></details>

Iterating over libfuncs would force me to keep track of all the libfuncs that need this info.

What is the benefit of iterating over libfuncs?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5552)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/circuit.cairo` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5552#-NxhBW5JAcAnudjvTYe2:-NxuiIcq01JMDzXfTc77:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/99981aecc04a67f58c55af4ff37e772054c286bd/corelib/src/circuit.cairo#L28)):*
> ```Cairo
> 
> 
> /// Defines an input for a circuit.
> ```

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/circuit.rs` line 364 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5552#-NxhBa67Etb1u4F6wXY0:-NxuiQro3zl6vw9GwTjn:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/99981aecc04a67f58c55af4ff37e772054c286bd/crates/cairo-lang-sierra/src/extensions/modules/circuit.rs#L364)):*
> ```XML
> 
> // A type that creates a circuit from a tuple of outputs.
> #[derive(Default)]
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5552)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 455 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5552#-NxhC34cBmiIlm14DgXr:-Nxuu-3g2LzbD2qx22KF:bhvw5ih) ([raw file](https://github.com/starkware-libs/cairo/blob/99981aecc04a67f58c55af4ff37e772054c286bd/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L455)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Iterating over libfuncs would force me to keep track of all the libfuncs that need this info.

What is the benefit of iterating over libfuncs?
</blockquote></details>

unused types would not cause calculations, and we would still just need to cache over the inner type.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5552)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 455 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5552#-NxhC34cBmiIlm14DgXr:-NxvGV9kEz8bcGexBsnm:bk3w087) ([raw file](https://github.com/starkware-libs/cairo/blob/99981aecc04a67f58c55af4ff37e772054c286bd/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L455)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

unused types would not cause calculations, and we would still just need to cache over the inner type.
</blockquote></details>

Why would they appear if they are unused?

What do you think about filtering only int the const segment generation?

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5552)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 455 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5552#-NxhC34cBmiIlm14DgXr:-NxvH7e-83ka8ERFuMoY:b6q0id) ([raw file](https://github.com/starkware-libs/cairo/blob/99981aecc04a67f58c55af4ff37e772054c286bd/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L455)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why would they appear if they are unused?

What do you think about filtering only int the const segment generation?
</blockquote></details>

they won't - unless someone is trying to do something malicious.

filtering the types?
what you currently did uses them only in the case it was used in a descriptor - which i like.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 455 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5552#-NxhC34cBmiIlm14DgXr:-NxvJvvqC2Wae7lm0R0y:bqgtkmu) ([raw file](https://github.com/starkware-libs/cairo/blob/99981aecc04a67f58c55af4ff37e772054c286bd/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L455)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

they won't - unless someone is trying to do something malicious.

filtering the types?
what you currently did uses them only in the case it was used in a descriptor - which i like.
</blockquote></details>

I add it to consts segment only if get_descriptor is called, but I compute the circuit info when Circuit<Ouputs> is declared.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet-classes/src/contract_segmentation_test_data/find_segment` line 363 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5552#-NxvK_4H5CEc6TE4jX6v:-NxvK_4H5CEc6TE4jX6w:b-e9p68z) ([raw file](https://github.com/starkware-libs/cairo/blob/dc6e28bf2104928df18efdf7285bb13d31c9daa7/crates/cairo-lang-starknet-classes/src/contract_segmentation_test_data/find_segment#L363)):*
> ```
> type core::circuit::CircuitInput::<1> = CircuitInput<1> [storable: false, drop: false, dup: false, zero_sized: false];
> 
> libfunc get_circuit_descriptor<Circuit<(core::circuit::AddModGate::<core::circuit::CircuitInput::<0>, core::circuit::CircuitInput::<1>>, core::circuit::CircuitInput::<2>)>> = get_circuit_descriptor<Circuit<(core::circuit::AddModGate::<core::circuit::CircuitInput::<0>, core::circuit::CircuitInput::<1>>, core::circuit::CircuitInput::<2>)>>;
> ```

This wasn't called before.



_Code quote:_
```
get_circuit_descriptor
```

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5552)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet-classes/src/contract_segmentation_test_data/find_segment` line 363 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5552#-NxvK_4H5CEc6TE4jX6v:-NxvLsAP6R7AFkOBPggO:b-pqov82) ([raw file](https://github.com/starkware-libs/cairo/blob/dc6e28bf2104928df18efdf7285bb13d31c9daa7/crates/cairo-lang-starknet-classes/src/contract_segmentation_test_data/find_segment#L363)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

This wasn't called before.
</blockquote></details>

makes sense

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5552)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 455 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5552#-NxhC34cBmiIlm14DgXr:-NxvLv7E67yt7K8xLXEO:b7rs44d) ([raw file](https://github.com/starkware-libs/cairo/blob/99981aecc04a67f58c55af4ff37e772054c286bd/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L455)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I add it to consts segment only if get_descriptor is called, but I compute the circuit info when Circuit<Ouputs> is declared.
</blockquote></details>

that's fine i think

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5552)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
