### PR TITLE
adding iterator to span

### PR DESCRIPTION
**Pull request by Tomer-StarkWare**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5638)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5638)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`corelib/src/array.cairo` line 230 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5638#-NyoSn1BE9A_KBOaZOz-:-NyoSn1BE9A_KBOaZOz0:b4cnvi) ([raw file](https://github.com/starkware-libs/cairo/blob/716f8f17a594cdf210c3819eeca54dd0d913aa29/corelib/src/array.cairo#L230)):*
> ```Cairo
>         }
>     }
>     fn into_iter(self: Span<T>) -> SpanIter<T> {
> ```

add to another trait `IntoIter` and implement it.

additionally add a `unstable feautre` attr on it.
___
*[`corelib/src/array.cairo` line 343 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5638#-NyoSx0-50CXGO3r6WWF:-NyoSx0-50CXGO3r6WWG:b8fogej) ([raw file](https://github.com/starkware-libs/cairo/blob/716f8f17a594cdf210c3819eeca54dd0d913aa29/corelib/src/array.cairo#L343)):*
> ```Cairo
> }
> 
> pub use core::num::traits::Iterator;
> ```

remove usage.
or at the very least move to top.
___
*[`corelib/src/num/traits/ops.cairo` line 5 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5638#-NyoT0h05b4ff0alVuG9:-NyoT0h05b4ff0alVuGA:bpkhqjh) ([raw file](https://github.com/starkware-libs/cairo/blob/716f8f17a594cdf210c3819eeca54dd0d913aa29/corelib/src/num/traits/ops.cairo#L5)):*
> ```Cairo
> pub mod checked;
> pub mod saturating;
> pub mod iterator;
> ```

core::ops - not core::num::ops
___
*[`corelib/src/num/traits/ops/iterator.cairo` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5638#-NyoT4849Qxv74e2jT46:-NyoT4849Qxv74e2jT47:b-hh6g6) ([raw file](https://github.com/starkware-libs/cairo/blob/716f8f17a594cdf210c3819eeca54dd0d913aa29/corelib/src/num/traits/ops/iterator.cairo#L2)):*
> ```Cairo
> /// An iterator over a collection of values.
> pub trait Iterator<T> {
> ```

move as stated above.
___
*[`corelib/src/test/array_test.cairo` line 180 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5638#-NyoT6cH1paUixK5GKSF:-NyoT6cH1paUixK5GKSG:bl1ed3r) ([raw file](https://github.com/starkware-libs/cairo/blob/716f8f17a594cdf210c3819eeca54dd0d913aa29/corelib/src/test/array_test.cairo#L180)):*
> ```Cairo
> }
> 
> use core::array::{Iterator};
> ```

usage not needed.
if needed - remove `{}`
if needed - move to top.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5638)* status: all files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`corelib/src/iter/traits/iterator.cairo` line 3 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5638#-NypTyV25f5KW6HyL1im:-NypTyV25f5KW6HyL1in:b-5zm81r) ([raw file](https://github.com/starkware-libs/cairo/blob/10786185d2fd7cca00c471d00f7eb125ed6410fb/corelib/src/iter/traits/iterator.cairo#L3)):*
> ```Cairo
> /// An iterator over a collection of values.
> pub trait Iterator<T> {
>     type Item;
> ```

doc all members.
___
*[`corelib/src/iter/traits/iterator.cairo` line 8 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5638#-NypTmUQB2VlLPUP5GFE:-NypTmUQB2VlLPUP5GFF:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/10786185d2fd7cca00c471d00f7eb125ed6410fb/corelib/src/iter/traits/iterator.cairo#L8)):*
> ```Cairo
> 
> /// Turn a collection of values into an iterator.
> #[unstable(feature: "collections")]
> ```





_Suggestion:_
```Cairo
#[unstable(feature: "collections-into-iter", note: "type bounds in traits not yet supported.")]
```
___
*[`corelib/src/iter/traits/iterator.cairo` line 10 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5638#-NypU-r1CYDF4S1z0CrV:-NypU-r1CYDF4S1z0CrW:b-5zm81r) ([raw file](https://github.com/starkware-libs/cairo/blob/10786185d2fd7cca00c471d00f7eb125ed6410fb/corelib/src/iter/traits/iterator.cairo#L10)):*
> ```Cairo
> #[unstable(feature: "collections")]
> pub trait IntoIterator<T> {
>     type IntoIter;
> ```

doc all members.
___
*[`corelib/src/prelude/v2023_10.cairo` line 28 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5638#-NypU1zf5fMyWM6hv3-P:-NypU1zf5fMyWM6hv3-Q:b642v85) ([raw file](https://github.com/starkware-libs/cairo/blob/10786185d2fd7cca00c471d00f7eb125ed6410fb/corelib/src/prelude/v2023_10.cairo#L28)):*
> ```Cairo
> };
> pub use core::zeroable::NonZero;
> pub use core::iter::traits::iterator::Iterator;
> ```

remove from prelude completely as discussed.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 21 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5638)* status: 10 of 28 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`-- commits` line 3 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5638#-Nyu9A0CCb_2HCFVhkAv):*
fix commits.
properly rebase.
___
*[`corelib/src/array.cairo` line 355 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5638#-Nyu8jGS2MRqrsVbdyFa:-Nyu8jGS2MRqrsVbdyFb:b-pibnso) ([raw file](https://github.com/starkware-libs/cairo/blob/ff3b865eac3c2f4dec00be7ca9627bdc34603520/corelib/src/array.cairo#L355)):*
> ```Cairo
> 
> #[feature("collections-into-iter")]
> pub impl SpanIntoIterator<T> of core::iter::traits::iterator::IntoIterator<Span<T>> {
> ```

remove pub.
___
*[`corelib/src/test/array_test.cairo` line 183 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5638#-Nyu95FBAbZBCD01DFdu:-Nyu95FBAbZBCD01DFdv:bmgvqpm) ([raw file](https://github.com/starkware-libs/cairo/blob/ff3b865eac3c2f4dec00be7ca9627bdc34603520/corelib/src/test/array_test.cairo#L183)):*
> ```Cairo
> fn test_span_iterator() {
>     let mut span = array![10, 11, 12, 13_felt252].span();
>     let mut iter = core::array::SpanIntoIterator::into_iter(ref span);
> ```

use feature instead of direct impl.

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5638)* status: 10 of 28 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`-- commits` line 3 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5638#-Nyu9A0CCb_2HCFVhkAv):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix commits.
properly rebase.
</blockquote></details>

Done.
___
*[`corelib/src/array.cairo` line 343 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5638#-NyoSx0-50CXGO3r6WWF:-NyoWmR46Xt2zfb6fKis:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/716f8f17a594cdf210c3819eeca54dd0d913aa29/corelib/src/array.cairo#L343)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove usage.
or at the very least move to top.
</blockquote></details>

Done.
___
*[`corelib/src/array.cairo` line 355 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5638#-Nyu8jGS2MRqrsVbdyFa:-NyuIEjoE23Ut8RSRn6S:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ff3b865eac3c2f4dec00be7ca9627bdc34603520/corelib/src/array.cairo#L355)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove pub.
</blockquote></details>

Done.
___
*[`corelib/src/iter/traits/iterator.cairo` line 3 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5638#-NypTyV25f5KW6HyL1im:-NysszTT4gfJ2KIGDBuh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/10786185d2fd7cca00c471d00f7eb125ed6410fb/corelib/src/iter/traits/iterator.cairo#L3)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc all members.
</blockquote></details>

Done.
___
*[`corelib/src/iter/traits/iterator.cairo` line 8 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5638#-NypTmUQB2VlLPUP5GFE:-NysszqU06snhxvVpr7i:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/10786185d2fd7cca00c471d00f7eb125ed6410fb/corelib/src/iter/traits/iterator.cairo#L8)):*
> ```Cairo
> 
> /// Turn a collection of values into an iterator.
> #[unstable(feature: "collections")]
> ```

Done.
___
*[`corelib/src/iter/traits/iterator.cairo` line 10 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5638#-NypU-r1CYDF4S1z0CrV:-Nyst-8xC33RD5GiQC7c:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/10786185d2fd7cca00c471d00f7eb125ed6410fb/corelib/src/iter/traits/iterator.cairo#L10)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc all members.
</blockquote></details>

Done.
___
*[`corelib/src/test/array_test.cairo` line 183 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5638#-Nyu95FBAbZBCD01DFdu:-NyuI2cb3qAmYakiV9da:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ff3b865eac3c2f4dec00be7ca9627bdc34603520/corelib/src/test/array_test.cairo#L183)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

use feature instead of direct impl.
</blockquote></details>

Done.
___
*[`corelib/src/prelude/v2023_10.cairo` line 28 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5638#-NypU1zf5fMyWM6hv3-P:-NyuH_Z07ulyJksZa4tp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/10786185d2fd7cca00c471d00f7eb125ed6410fb/corelib/src/prelude/v2023_10.cairo#L28)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove from prelude completely as discussed.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 22 of 22 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5638#-:-NyuTGxcDW23PquKwFr4:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Pull request merged**
