### PR TITLE
Loop semantic model

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2601)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2599** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2599" target="_blank">Graphite</a> 
    * **PR #2600** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2600" target="_blank">Graphite</a> 
      * **PR #2601** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2601" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2601?utm_source=stack-comment).

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2601#-:-NRSwSOS2S6jQuYKcEs-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 750 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2601#-NRSw69UClDcJNUiLmy5:-NRSw69UClDcJNUiLmy6:bj9w34r) ([raw file](https://github.com/starkware-libs/cairo/blob/48f4ece8e6103d52047d3bec35a0113b968258e8/crates/cairo-lang-semantic/src/expr/compute.rs#L750)):*
> ```XML
>         let mut statements = syntax.body(syntax_db).statements(syntax_db).elements(syntax_db);
>         // Remove the tail expression, if exists.
>         // TODO(spapini): Diagnostics for tail in loops.
> ```

isn't this the next line?



_Code quote:_
```XML
        // TODO(spapini): Diagnostics for tail in loops.
```

**Comment by spapinistarkware** [comment]
@spapinistarkware queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2601).

**Comment by spapinistarkware** [comment]
[Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2601) failed to merge this pull request for an unknown reason. Try your merge again, or report a bug if you see this consistently.

**Comment by spapinistarkware** [comment]
@spapinistarkware queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2601).

**Comment by spapinistarkware** [comment]
[Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2601) failed to merge this pull request for an unknown reason. Try your merge again, or report a bug if you see this consistently.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2601)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 750 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2601#-NRSw69UClDcJNUiLmy5:-NRT9dY3Bgj1uTs8EJYI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2fa10d051c22c331c5b7fa9a4aab42c0a149e3e1/crates/cairo-lang-semantic/src/expr/compute.rs#L750)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

isn't this the next line?
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2601)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Comment by spapinistarkware** [comment]
@spapinistarkware queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2601).

**Comment by spapinistarkware** [comment]
[Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2601) failed to merge this pull request for an unknown reason. Try your merge again, or report a bug if you see this consistently.

**Comment by spapinistarkware** [comment]
@spapinistarkware queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2601).

**Comment by spapinistarkware** [comment]
[Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2601) failed to merge this pull request for an unknown reason. Try your merge again, or report a bug if you see this consistently.

**Pull request merged**
