### PR TITLE
Change function identifier in profiling to fully qualified path

### PR DESCRIPTION
**Pull request by piotmag769**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5306)

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5306)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @piotmag769)

___
*[`crates/cairo-lang-runner/src/profiling_test_data/major_test_cases` line 75 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5306#-NtWpz9s8Zm1gp7oL8CS:-NtWpz9s8Zm1gp7oL8CT:bmgm51a) ([raw file](https://github.com/starkware-libs/cairo/blob/951abccfe45d4751685f3f958ef0174eb8c831d6/crates/cairo-lang-runner/src/profiling_test_data/major_test_cases#L75)):*
> ```
>   function test::pow2_14000: 12
> Weight by Cairo function:
>   function unknown: 126021
> ```

seems there's some mishandling there.



_Code quote:_
```
  function unknown: 126021
```

**Review by orizi — COMMENTED** [review]
> Reviewed 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5306)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @piotmag769)

___
*[`crates/cairo-lang-semantic/src/test_utils.rs` line 124 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5306#-Nt_nmUk6an6eljrxKN3:-Nt_nmUk6an6eljrxKN4:b1rn3re) ([raw file](https://github.com/starkware-libs/cairo/blob/3426c827d934273fe5a0990205439c74cc1c0ae7/crates/cairo-lang-semantic/src/test_utils.rs#L124)):*
> ```XML
>     let x = PathBuf::from("lib.cairo");
>     std::fs::write(&x, content.as_bytes()).unwrap();
>     let file_id = db.intern_file(FileLongId::OnDisk(x));
> ```

revert this.
just discover in the print case due to the missing Parent in the virtual file.
this may cause weird test collisions.



_Code quote:_
```XML
    let x = PathBuf::from("lib.cairo");
    std::fs::write(&x, content.as_bytes()).unwrap();
    let file_id = db.intern_file(FileLongId::OnDisk(x));
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5306#-:-Nt_rOxpBEE6wI2vyFAo:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @piotmag769)

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 2 of 5 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5306)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/statements_locations.rs` line 28 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5306#-Nt_vC5R7R02H9k_bhQY:-Nt_vC5R7R02H9k_bhQZ:bezcwfw) ([raw file](https://github.com/starkware-libs/cairo/blob/3b00ec42b82f7a94515fd24d57ac5e504d4a0364/crates/cairo-lang-sierra-generator/src/statements_locations.rs#L28)):*
> ```XML
>             let file_name = file_id.file_name(db.upcast());
> 
>             while let FileLongId::Virtual(VirtualFile { parent: Some(parent), .. }) =
> ```

Will split this function to make sure the cases where:

- parent for VirtualFile is missing
- the ModuleId for real file is missing 

are discoverable from the outside on the type level. These cases shouldn't happen but better to be safe than sorry.
___
*[`crates/cairo-lang-semantic/src/test_utils.rs` line 124 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5306#-Nt_nmUk6an6eljrxKN3:-Nt_uilT3DhjobaA-Jf_:b-icisfs) ([raw file](https://github.com/starkware-libs/cairo/blob/3426c827d934273fe5a0990205439c74cc1c0ae7/crates/cairo-lang-semantic/src/test_utils.rs#L124)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

revert this.
just discover in the print case due to the missing Parent in the virtual file.
this may cause weird test collisions.
</blockquote></details>

Accidentally committed

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5306)* status: all files reviewed, 1 unresolved discussion

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5306)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @piotmag769)

___
*[`crates/cairo-lang-sierra-generator/src/statements_locations.rs` line 28 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5306#-Nt_vC5R7R02H9k_bhQY:-NtaC7k8-EGaa2SjyJCJ:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/3b00ec42b82f7a94515fd24d57ac5e504d4a0364/crates/cairo-lang-sierra-generator/src/statements_locations.rs#L28)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Will split this function to make sure the cases where:

- parent for VirtualFile is missing
- the ModuleId for real file is missing 

are discoverable from the outside on the type level. These cases shouldn't happen but better to be safe than sorry.
</blockquote></details>

Done

**Pull request merged**
