### PR TITLE
Changed plugin tests to be based on expand code.

### PR DESCRIPTION
**Pull request by orizi**
Recursively expands all existing items.

---

**Stack**:
- #3973
- #3972
- #3971 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3971)

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3971)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-plugins/src/test.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3971#-NdVR1I38cKcdvBKA9cn:-NdZ0LMB48D7qQ2Yg9Jm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/39138949daac4a331ca6bb39864c56113fe994ef/crates/cairo-lang-plugins/src/test.rs#L115)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Suggestion. Something like:
</blockquote></details>

Done.
___
*[`crates/cairo-lang-plugins/src/test.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3971#-NdVV4OV7knqUwxuXRi4:-NdZAl8A2X8nUoQ4V2P9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/39138949daac4a331ca6bb39864c56113fe994ef/crates/cairo-lang-plugins/src/test.rs#L155)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

let's call it test_lib.cairo or similar. Would be one small step easier to find where the diagnostics come from.
</blockquote></details>

Done.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3971)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-plugins/src/test.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3971#-NdVV4OV7knqUwxuXRi4:-NdZX0EH60Y3fRwOGxH1:b3hfjo4) ([raw file](https://github.com/starkware-libs/cairo/blob/39138949daac4a331ca6bb39864c56113fe994ef/crates/cairo-lang-plugins/src/test.rs#L155)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant instead of the lib.cairo (so that in the diagnostics we don't see  lib.cairo, which is confusing with other lib.cairo)
___
*[`crates/cairo-lang-plugins/src/test.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3971#-NdZW0Jn9rKV5u3k71tA:-NdZW0Jo4FNCiCsAYtFn:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/554b64e8732078cd3d8f9dfbb301cb044e1f60a2/crates/cairo-lang-plugins/src/test.rs#L75)):*
> ```XML
>     let mut output = String::new();
>     let syntax_db = db.upcast();
>     // Collec the module diagnostics.
> ```





_Suggestion:_
```XML
/ Collect the module diagn
```
___
*[`crates/cairo-lang-plugins/src/test_data/generate_trait` line 145 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3971#-NdVVZ8V0oeA3tHu3c4p:-NdZWuY_8yjEaJI2qBMO:b-db1s11) ([raw file](https://github.com/starkware-libs/cairo/blob/39138949daac4a331ca6bb39864c56113fe994ef/crates/cairo-lang-plugins/src/test_data/generate_trait#L145)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

While you're at it... Thanks :)
</blockquote></details>

Also in the impl please :)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3971)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-plugins/src/test.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3971#-NdVV4OV7knqUwxuXRi4:-NdZYK0PA8QD7rzdyAQv:bpdewj8) ([raw file](https://github.com/starkware-libs/cairo/blob/39138949daac4a331ca6bb39864c56113fe994ef/crates/cairo-lang-plugins/src/test.rs#L155)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I meant instead of the lib.cairo (so that in the diagnostics we don't see  lib.cairo, which is confusing with other lib.cairo)
</blockquote></details>

Discussed f2f

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3971#-:-NdZeE3e3W8l6N3EaJpS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
