### PR TITLE
Added a printer binary for sierra code within a contract.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3910)

### CODE REVIEW

**Review by yuvalsw — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3910)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3910#-NcRY8jJ7yOTVQBXhXO5:-NcRY8jJ7yOTVQBXhXO6:b-57hmcw) (no related file):*
LGTM, but wait for spapini's review, as I'm less familiar with these parts.

___

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3910)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

**Review by yuvalsw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3910)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3910)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
