### PR TITLE
Remove lt libfuncs

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2991)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2991** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2991" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2991?utm_source=stack-comment).

**Comment by spapinistarkware** [comment]
This is waiting on inlining change

**Comment by ilyalesokhin-starkware** [comment]
*[`tests/e2e_test_data/libfuncs/u128` line 339 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2991#-NUL3vX82deJYV47EoGK:-NUL3vX82deJYV47EoGL:b-brf2i0) ([raw file](https://github.com/starkware-libs/cairo/blob/cffa4252bf924966069934521134335478586d8f/tests/e2e_test_data/libfuncs/u128#L339)):*
> ```
> //! > cairo
> fn foo(a: u128, b: u128) -> bool {
>     a < b
> ```

According to @orizi  where are supposed to only have libfuncs here.



_Code quote:_
```
 a < b
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2991)* status: 5 of 14 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

___
*[`tests/e2e_test_data/libfuncs/u128` line 369 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2991#-NUL42QZ8pU562mj6P8L:-NUL42Q_BkF18bun4wrO:b-9eqpvf) ([raw file](https://github.com/starkware-libs/cairo/blob/cffa4252bf924966069934521134335478586d8f/tests/e2e_test_data/libfuncs/u128#L369)):*
> ```
> 
> //! > function_costs
> test::foo: OrderedHashMap({Const: 1580})
> ```

it is a lot less efficent, why do we want to do this change?



_Code quote:_
```
test::foo: OrderedHashMap({Const: 1580})
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2991)* status: 5 of 14 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`tests/e2e_test_data/libfuncs/u128` line 339 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2991#-NUL3vX82deJYV47EoGK:-NULJSsK44jft_z9c8RB:bsflix7) ([raw file](https://github.com/starkware-libs/cairo/blob/cffa4252bf924966069934521134335478586d8f/tests/e2e_test_data/libfuncs/u128#L339)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

According to @orizi  where are supposed to only have libfuncs here.
</blockquote></details>

Yes, it's mostly for you to see the changes in casm, then ill delete these tests

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2991)* status: 5 of 14 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware, @liorgold2, and @orizi)

___
*[`tests/e2e_test_data/libfuncs/u128` line 369 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2991#-NUL42QZ8pU562mj6P8L:-NULJXZL78skU0H8T6NB:b-7c8kpp) ([raw file](https://github.com/starkware-libs/cairo/blob/cffa4252bf924966069934521134335478586d8f/tests/e2e_test_data/libfuncs/u128#L369)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it is a lot less efficent, why do we want to do this change?
</blockquote></details>

See above. Im still waiting on inlining change

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2991)* status: 2 of 15 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware, @liorgold2, and @orizi)

___
*[`tests/e2e_test_data/libfuncs/u32` line 154 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2991#-NULM3oY7QsvzXAPW_YZ:-NULM3oY7QsvzXAPW_Y_:bb2fpyg) ([raw file](https://github.com/starkware-libs/cairo/blob/2af8f8291c8c24b8c5c7a60b4cdcc09f49b879fe/tests/e2e_test_data/libfuncs/u32#L154)):*
> ```
> [ap + 0] = [fp + -5] + 1, ap++;
> [ap + 0] = 1, ap++;
> [ap + 0] = [ap + -4] + 4294967296, ap++;
> ```

@ilyalesokhin-starkware the match optimization didn't work here, but when I did a match manually (isntead of callnig is_err), it did. Have any idea?

**Review by liorgold2 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2991)* status: 2 of 15 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`tests/e2e_test_data/libfuncs/u128` line 339 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2991#-NUL3vX82deJYV47EoGK:-NULXAiYEFcavDg6b0Gf:b2yx0qv) ([raw file](https://github.com/starkware-libs/cairo/blob/cffa4252bf924966069934521134335478586d8f/tests/e2e_test_data/libfuncs/u128#L339)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Yes, it's mostly for you to see the changes in casm, then ill delete these tests
</blockquote></details>

Please don't remove it, it's a good test.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2991)* status: 2 of 15 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware, @liorgold2, and @orizi)

___
*[`tests/e2e_test_data/libfuncs/u128` line 339 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2991#-NUL3vX82deJYV47EoGK:-NULZZeI2ZhkFn2mafJP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cffa4252bf924966069934521134335478586d8f/tests/e2e_test_data/libfuncs/u128#L339)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Please don't remove it, it's a good test.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 3 of 14 files at r1, 2 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2991)* status: 7 of 19 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`tests/e2e_test_data/libfuncs/u128` line 339 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2991#-NUL3vX82deJYV47EoGK:-NULntX04gC30TkXqMBs:bsccm84) ([raw file](https://github.com/starkware-libs/cairo/blob/cffa4252bf924966069934521134335478586d8f/tests/e2e_test_data/libfuncs/u128#L339)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

we need to put it in a different directory,

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2991#-:-NULo-kx4xS7gZ1-UH_k:bnfp4nl)* status: 9 of 19 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

**Review by ilyalesokhin-starkware — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2991)* status: 9 of 19 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

___
*[`corelib/src/integer.cairo` line 1394 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2991#-NULqfFu35PJdRxrluiH:-NULqfFvDyVXZgzr4Mpc:bol25mp) ([raw file](https://github.com/starkware-libs/cairo/blob/d8116c2fd66fe0c147b9ffe51e259724322dfd05/corelib/src/integer.cairo#L1394)):*
> ```Cairo
> 
> #[inline]
> fn internal_is_err<T, E, impl TDrop: Drop<T>, impl EDrop: Drop<E>>(value: Result<T, E>) -> bool {
> ```

I suggest into_is_err
+
document.



_Code quote:_
```Cairo
internal_is_err
```

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 3 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2991)* status: 12 of 19 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/integer.cairo` line 1394 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2991#-NULqfFu35PJdRxrluiH:-NULs4FR4VR4G--4VFbK:brxp9sq) ([raw file](https://github.com/starkware-libs/cairo/blob/d8116c2fd66fe0c147b9ffe51e259724322dfd05/corelib/src/integer.cairo#L1394)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I suggest into_is_err
+
document.
</blockquote></details>

Sounds good.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2991)* status: 8 of 21 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @liorgold2)

___
*[`corelib/src/integer.cairo` line 1394 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2991#-NULqfFu35PJdRxrluiH:-NULvVRD61-ygCUHK1BU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d8116c2fd66fe0c147b9ffe51e259724322dfd05/corelib/src/integer.cairo#L1394)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Sounds good.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 10 files at r3, 6 of 6 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2991)* status: 17 of 21 files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 6 of 14 files at r1, 2 of 9 files at r2, 4 of 10 files at r3, 6 of 6 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2991)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 1 of 14 files at r1, 2 of 9 files at r2, 2 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2991)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
