### PR TITLE
Profiler: added profiling per (Sierra) stack trace.

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4894)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4894)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 351 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4894#-NoqsEBiC2dCFeGvx3Lx:-NoqsEBiC2dCFeGvx3Ly:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/1eeecde4a878fa8193047152a604b6fac6db9f3a/crates/cairo-lang-runner/src/lib.rs#L351)):*
> ```XML
>                     let concrete_name: SmolStr = format!("{}", invocation.libfunc_id).into();
>                     let generic_name = concrete_name_to_generic_name(concrete_name);
>                     if generic_name == "function_call" {
> ```





_Suggestion:_
```XML
                if generic_name == FunctionCallLibfunc::STR_ID {
```
___
*[`crates/cairo-lang-runner/src/lib.rs` line 361 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4894#-Noqru_VBjEu0MqBRX9Y:-Noqru_VBjEu0MqBRX9Z:b-o05xen) ([raw file](https://github.com/starkware-libs/cairo/blob/1eeecde4a878fa8193047152a604b6fac6db9f3a/crates/cairo-lang-runner/src/lib.rs#L361)):*
> ```XML
>                     let cur_stack: Vec<_> =
>                         chain!(function_stack.iter().map(|f| f.0), [user_function_idx]).collect();
>                     *stack_trace_weights.entry(cur_stack).or_insert(0) += cur_weight;
> ```

shouldn't the stack be added for statements within the function itself if we already track the stack?
or is it too heavy?



_Code quote:_
```XML
*stack_trace_weights.entry(cur_stack).or_insert(0) += cur_weight;
```

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4894)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4894)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 351 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4894#-Noqskdw2LPV2DgagePu:-NosaSeG5lDbkxmPSFxQ:b-ucfknh) ([raw file](https://github.com/starkware-libs/cairo/blob/1eeecde4a878fa8193047152a604b6fac6db9f3a/crates/cairo-lang-runner/src/lib.rs#L351)):*
> ```XML
>                     let concrete_name: SmolStr = format!("{}", invocation.libfunc_id).into();
>                     let generic_name = concrete_name_to_generic_name(concrete_name);
>                     if generic_name == "function_call" {
> ```

Thanks!
___
*[`crates/cairo-lang-runner/src/lib.rs` line 361 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4894#-Noqru_VBjEu0MqBRX9Y:-NosZQ1kC7KtuAYZ0yFO:b-kir8gs) ([raw file](https://github.com/starkware-libs/cairo/blob/1eeecde4a878fa8193047152a604b6fac6db9f3a/crates/cairo-lang-runner/src/lib.rs#L361)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

shouldn't the stack be added for statements within the function itself if we already track the stack?
or is it too heavy?
</blockquote></details>

Do you suggest to include the specific statement of the function in the stack so that we know exactly what statement is heavy?
Not sure it's too heavy, we can try that too. But first ack this is what you mean, and then I can do it in a following PR.
BTW this is not too helpful currently with sierra as a statement is either a libfunc (for which we know the price), a call to a user function (which we do track), or return. It may help in cases where you call bar()  twice from foo(), and you don't know which is the heavier. But I don't think this is a usecase for profilers generally - more relevant for debuggers.
In Cairo it may be more helpful, but still I am not sure this is in the responsibilities of the profiler.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4894)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 780 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4894#-Np-XEpW-C9R5934FQYy:-Np-XEpW-C9R5934FQYz:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/77b1cadb3a353755dfedffd91973d4b91fa885c1/crates/cairo-lang-runner/src/lib.rs#L780)):*
> ```XML
>         MAX_STACK_TRACE_DEPTH_DEFAULT
>     };
>     max_stack_trace_depth
> ```





_Suggestion:_
```XML
    std::env::var("MAX_STACK_TRACE_DEPTH").ok()
                    .and_then(|value| value.parse::<usize>().ok())
                    .on_none(||eprintln!("bad... something something"))
                    .unwrap_or(MAX_STACK_TRACE_DEPTH_DEFAULT)
```

**Review by orizi — COMMENTED** [review]
> Reviewed 4 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4894)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @yuvalsw)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4894#-:-Np-jzVd-BO88w-qUsSG:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
