### PR TITLE
Supported calling methods from traits from impl generic parameters

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3832)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3832)* status: 2 of 7 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1599 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3832#-NbJzXvL1QOqCvAoVLmt:-NbJzXvL1QOqCvAoVLmu:b-15g2wa) ([raw file](https://github.com/starkware-libs/cairo/blob/5e2a25784863f8383556e59434346241b45776d0/crates/cairo-lang-semantic/src/expr/compute.rs#L1599)):*
> ```XML
>     let mut candidate_traits = all_module_trait_ids(ctx)?;
> 
>     // Add traits from generic args in the context.
> ```

Look also in the impl items in the current module. (including uses)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 4 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3832)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3832)* status: 1 of 13 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1599 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3832#-NbJzXvL1QOqCvAoVLmt:-NbUNqfp4lYatnuDA7ec:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5e2a25784863f8383556e59434346241b45776d0/crates/cairo-lang-semantic/src/expr/compute.rs#L1599)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Look also in the impl items in the current module. (including uses)
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 7 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3832#-:-Nbj9gED4ZzUJgxt9IhE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
