### PR TITLE
supporting attribute flatting

### PR DESCRIPTION
**Pull request by Tomer-StarkWare**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6072)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6072)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/src/plugin/storage_interfaces.rs` line 225 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6072#-O2sRSYgC-O-B7AHr41E:-O2sRSYgC-O-B7AHr41F:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a3ab3ce6be0b9f86fe4dfe8bb80aaf96feb34905/crates/cairo-lang-starknet/src/plugin/storage_interfaces.rs#L225)):*
> ```XML
>                     return "starknet::storage::StoragePath".to_string();
>                 }
>                 "starknet::storage::PendingStoragePath".to_string()
> ```





_Suggestion:_
```XML
                if member.has_attr(self.db, FLAT_ATTR) {
                    "starknet::storage::StoragePath".to_string()
                } else {
                    "starknet::storage::PendingStoragePath".to_string()
                }
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6072)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/storage_interfaces.rs` line 225 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6072#-O2sRSYgC-O-B7AHr41E:-O2sWEWa4pdwZks6Tsy_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a3ab3ce6be0b9f86fe4dfe8bb80aaf96feb34905/crates/cairo-lang-starknet/src/plugin/storage_interfaces.rs#L225)):*
> ```XML
>                     return "starknet::storage::StoragePath".to_string();
>                 }
>                 "starknet::storage::PendingStoragePath".to_string()
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6072)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/flat_storage_test.cairo` line 3 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6072#-O2sjQF6B6kJk8fO4pKt:-O2sjQF6B6kJk8fO4pKu:b57mb4p) ([raw file](https://github.com/starkware-libs/cairo/blob/e49ab7225241314578e5b2f2211b76250b301572/crates/cairo-lang-starknet/cairo_level_tests/flat_storage_test.cairo#L3)):*
> ```Cairo
> use core::starknet::storage::{StoragePointerWriteAccess, StoragePointerReadAccess};
> 
> #[starknet::storage_node]
> ```

please simplifiy the test with better names for the structs and members.
(e.g. "ignored member", "transparent", and so on)

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6072)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/flat_storage_test.cairo` line 3 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6072#-O2sjQF6B6kJk8fO4pKt:-O2ssfHU5VIhD43-rXpc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e49ab7225241314578e5b2f2211b76250b301572/crates/cairo-lang-starknet/cairo_level_tests/flat_storage_test.cairo#L3)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

please simplifiy the test with better names for the structs and members.
(e.g. "ignored member", "transparent", and so on)
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6072#-:-O2tGXjw8rIhl_At34B-:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6072)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @gilbens-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6072#-O2tGZcuC8gNIZmFIzIC:-O2tGZcuC8gNIZmFIzID:b-fmb6mi) (no related file):*
Wait on @gilbens-starkware as well please.

___

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6072)* status: all files reviewed, 1 unresolved discussion (waiting on @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/flat_storage_test.cairo` line 37 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6072#-O2toG1f6ijSODlwgzrE:-O2toG1f6ijSODlwgzrF:b-euo29u) ([raw file](https://github.com/starkware-libs/cairo/blob/4742a5d59ade29b5c86a5a816fbbb0466229d34a/crates/cairo-lang-starknet/cairo_level_tests/flat_storage_test.cairo#L37)):*
> ```Cairo
>         pub member: IgnoredMemberStruct,
>     }
> }
> ```

It's not really `v0` and `new` more like with and without `ignored`.



_Code quote:_
```Cairo
#[starknet::contract]
mod contract_v0 {
    use core::starknet::storage::{StoragePointerReadAccess, StoragePointerWriteAccess};
    use super::Struct0;
    #[storage]
    pub struct Storage {
        pub member: Struct0,
    }
}

#[starknet::storage_node]
struct IgnoredMemberStruct {
    #[flat]
    pub ignored_member: Struct0,
}

#[starknet::contract]
mod contract_new {
    use core::starknet::storage::{StoragePointerReadAccess, StoragePointerWriteAccess};
    use super::IgnoredMemberStruct;
    #[storage]
    pub struct Storage {
        pub member: IgnoredMemberStruct,
    }
}
```

**Pull request merged**
