### PR TITLE
feat: Support generic types in Derive statements

### LINKED ISSUE #2956: feat: Derives with generics
Today, you can derive some trait impls on types, e.g.:
```
#[derive(Copy)]
struct A {
  a: u8
}
```
But, it doesn't work for items with generics, like this:
```
#[derive(Copy)]
struct A<T> {
  a: T
}
```

The relevant file is derive.rs
You should probably look up the generic parameters from the AST, and add the proper generic arguments in the derived impl. For example:

```
impl ACopy<T, impl TCopy: Copy<T>> of Copy<A<T>>;
```

### PR DESCRIPTION
**Pull request by wraitii**
Fix #2956 

This implements derive support for all existing derive for structs with generic types.
I haven't done it for enums but can be added (not sure if those can take generic types?).

Also wondering if this should be actually tested in cairo somewhere ?

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2964)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2964)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @wraitii)

___
*[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2964#-NUATMM17tyNlCR9Ti-Z:-NUATMM17tyNlCR9Ti-_:b-cd35gq) ([raw file](https://github.com/starkware-libs/cairo/blob/b2dcb0bea92c77d4ead26b670bb5bfaaf5cbfc55/crates/cairo-lang-plugins/src/plugins/derive.rs#L64)):*
> ```XML
> enum ExtraInfo {
>     Enum(Vec<SmolStr>),
>     Struct(Vec<SmolStr>, Vec<SmolStr>),
> ```

Please extract variables to a new struct with named members.
___
*[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2964#-NUATZ2x6ugdh_r6m4Vu:-NUATZ2x6ugdh_r6m4Vv:b77wgv7) ([raw file](https://github.com/starkware-libs/cairo/blob/b2dcb0bea92c77d4ead26b670bb5bfaaf5cbfc55/crates/cairo-lang-plugins/src/plugins/derive.rs#L72)):*
> ```XML
> }
> 
> fn extract_generics(db: &dyn SyntaxGroup, struct_ast: &ItemStruct) -> Vec<SmolStr> {
> ```

I suspect you'll need a more involved logic when you support generic impl params.
___
*[`crates/cairo-lang-plugins/src/test_data/derive` line 20 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2964#-NUATCmb1d0RzulZjQZa:-NUATCmc5aHWgTgGT_D2:btf6k9p) ([raw file](https://github.com/starkware-libs/cairo/blob/b2dcb0bea92c77d4ead26b670bb5bfaaf5cbfc55/crates/cairo-lang-plugins/src/test_data/derive#L20)):*
> ```
> 
> #[derive(Drop, Clone, PartialEq, Serde)]
> struct TwoMemberGenericStruct<T, U> {
> ```

Please test also with impl generic params.

**Comment by spapinistarkware** [comment]
You can also add a pure Cairo test under bug_samples with the issue name.

**Review by wraitii — COMMENTED** [review]
Done. Note that there are currently errors in some other cairo tests (seems they're also not run by default and one needs to cargo run --bin cairo-test)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2964#-:-NUBNjTF-_fOzBLRjuyI:b-wek28s)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2964#-NUATMM17tyNlCR9Ti-Z:-NUBNcKa9tZzTnK8Ix0e:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/b2dcb0bea92c77d4ead26b670bb5bfaaf5cbfc55/crates/cairo-lang-plugins/src/plugins/derive.rs#L64)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Please extract variables to a new struct with named members.
</blockquote></details>

Done
___
*[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2964#-NUATZ2x6ugdh_r6m4Vu:-NUBNe1nEqKfNnX1_-iv:buketii) ([raw file](https://github.com/starkware-libs/cairo/blob/b2dcb0bea92c77d4ead26b670bb5bfaaf5cbfc55/crates/cairo-lang-plugins/src/plugins/derive.rs#L72)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I suspect you'll need a more involved logic when you support generic impl params.
</blockquote></details>

Indeed
___
*[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2964#-NUBNxdp9IKR1jdoZp6Q:-NUBNxdp9IKR1jdoZp6R:b-ik6um5) ([raw file](https://github.com/starkware-libs/cairo/blob/f831fe57feb5063fde1d3fe04b81f244aa82fb1f/crates/cairo-lang-plugins/src/plugins/derive.rs#L86)):*
> ```XML
>                 }
>                 ast::GenericParam::Const(c) => {
>                     other_generics.push(c.as_syntax_node().get_text_without_trivia(db))
> ```

I believe these don't actually work well yet, but I think this should cover it anyways?
___
*[`crates/cairo-lang-plugins/src/test_data/derive` line 20 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2964#-NUATCmb1d0RzulZjQZa:-NUBNgS57pYoKThSTQYM:b-gli2e0) ([raw file](https://github.com/starkware-libs/cairo/blob/b2dcb0bea92c77d4ead26b670bb5bfaaf5cbfc55/crates/cairo-lang-plugins/src/test_data/derive#L20)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Please test also with impl generic params.
</blockquote></details>

Done, added a simpler test as well

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
It's running on the CI, so I'm ok with it.

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2964#-:-NUBwIQt8uejmLKmuHJk:byh1kd9)* status: all files reviewed, 4 unresolved discussions (waiting on @wraitii)

___
*[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2964#-NUBNxdp9IKR1jdoZp6Q:-NUCTVk53kBthvHgVuZT:byr4flj) ([raw file](https://github.com/starkware-libs/cairo/blob/f831fe57feb5063fde1d3fe04b81f244aa82fb1f/crates/cairo-lang-plugins/src/plugins/derive.rs#L86)):*
<details><summary><i>Previously, wraitii (Lancelot de Ferrière) wrote…</i></summary><blockquote>

I believe these don't actually work well yet, but I think this should cover it anyways?
</blockquote></details>

Right.
___
*[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 100 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2964#-NUCTlRgBGVuu8co6bMI:-NUCTlRgBGVuu8co6bMJ:b-wbfdpe) ([raw file](https://github.com/starkware-libs/cairo/blob/f831fe57feb5063fde1d3fe04b81f244aa82fb1f/crates/cairo-lang-plugins/src/plugins/derive.rs#L100)):*
> ```XML
>     f: impl Fn(&SmolStr) -> String,
> ) -> String {
>     match (type_generics.is_empty(), other_generics.is_empty()) {
> ```

This  logic can be simpler. There is no need to check for is_entpy() (abd even in general, I think checking for length 0 is usually smelly).
Note that you can end with a trailing comma 
So, simply iterating over the generics and appending something and a comma, should cut it.
___
*[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 115 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2964#-NUCUKqwD-vfKcSdYEZe:-NUCUKqwD-vfKcSdYEZf:b-816h6l) ([raw file](https://github.com/starkware-libs/cairo/blob/f831fe57feb5063fde1d3fe04b81f244aa82fb1f/crates/cairo-lang-plugins/src/plugins/derive.rs#L115)):*
> ```XML
> }
> 
> fn format_generics(type_generics: &Vec<SmolStr>, other_generics: &Vec<String>) -> String {
> ```

Same.
___
*[`tests/bug_samples/issue2964.cairo` line 12 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2964#-NUCUx8OCVjqRzDk3wMl:-NUCUx8OCVjqRzDk3wMm:buxkxur) ([raw file](https://github.com/starkware-libs/cairo/blob/f831fe57feb5063fde1d3fe04b81f244aa82fb1f/tests/bug_samples/issue2964.cairo#L12)):*
> ```Cairo
> }
> 
> // This doesn't actually work, fails with 'unknown literal' on U
> ```

Right, like u said, constant generics don't work yet. You can remove this from the test for now, with a TODO to check it as well. Put the todo on me (spapini)

**Review by wraitii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2964)* status: 0 of 4 files reviewed, 9 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 100 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2964#-NUCTlRgBGVuu8co6bMI:-NUGldllCvd298VUubNT:b8k49e9) ([raw file](https://github.com/starkware-libs/cairo/blob/f831fe57feb5063fde1d3fe04b81f244aa82fb1f/crates/cairo-lang-plugins/src/plugins/derive.rs#L100)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This  logic can be simpler. There is no need to check for is_entpy() (abd even in general, I think checking for length 0 is usually smelly).
Note that you can end with a trailing comma 
So, simply iterating over the generics and appending something and a comma, should cut it.
</blockquote></details>

Simplified the logic, it leads to empty`<>` when deriving non-generic structs, but that seems OK to the cairo compiler
___
*[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 115 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2964#-NUCUKqwD-vfKcSdYEZe:-NUGljhZ2OUcDWJfjmMt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f831fe57feb5063fde1d3fe04b81f244aa82fb1f/crates/cairo-lang-plugins/src/plugins/derive.rs#L115)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Same.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 228 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2964#-NUGluTi-IBZZpimQMR8:-NUGluTi-IBZZpimQMR9:blsiy4l) ([raw file](https://github.com/starkware-libs/cairo/blob/4eda50ae2e8772a5c1fa5ef9ef47072d102e20c2/crates/cairo-lang-plugins/src/plugins/derive.rs#L228)):*
> ```XML
>                 }).join("\n            "),
>                 generics = format_generics(type_generics, other_generics),
>                 generics_impl = format_generics_with_trait(type_generics, other_generics, |t| format!("impl {t}Clone: Clone<{t}>, impl {t}Destruct: Destruct<{t}>"))
> ```

It's unclear to me why Clone requires Destruct exactly (or rather, it's unclear to me what is getting destructed?). See comment in `derive` test below.
___
*[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 314 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2964#-NUGm1-J4mWFFRIqicSf:-NUGm1-J4mWFFRIqicSg:b-ic7qmh) ([raw file](https://github.com/starkware-libs/cairo/blob/4eda50ae2e8772a5c1fa5ef9ef47072d102e20c2/crates/cairo-lang-plugins/src/plugins/derive.rs#L314)):*
> ```XML
>                         }).join("\n        "),
>                         generics = format_generics(type_generics, other_generics),
>                         generics_impl = format_generics_with_trait(type_generics, other_generics, |t| format!("impl {t}PartialEq: PartialEq<{t}>, impl {t}Destruct: Destruct<{t}>"))
> ```

Also added Destruct here, takes ownership so for now this sorta makes sense to me
___
*[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 368 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2964#-NUGm5xe4IqHIYcPJcWi:-NUGm5xe4IqHIYcPJcWj:bln04k6) ([raw file](https://github.com/starkware-libs/cairo/blob/4eda50ae2e8772a5c1fa5ef9ef47072d102e20c2/crates/cairo-lang-plugins/src/plugins/derive.rs#L368)):*
> ```XML
>                         member_names.iter().map(|member| format!("{member}: serde::Serde::deserialize(ref serialized)?,")).join("\n            "),
>                         generics = format_generics(type_generics, other_generics),
>                         generics_impl = format_generics_with_trait(type_generics, other_generics, |t| format!("impl {t}Serde: serde::Serde<{t}>, impl {t}Destruct: Destruct<{t}>"))
> ```

Likewise added Destruct
___
*[`crates/cairo-lang-plugins/src/test_data/derive` line 130 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2964#-NUGmAB32cwMunb1_QpE:-NUGmAB40qjOsA03_wcd:bkztumz) ([raw file](https://github.com/starkware-libs/cairo/blob/4eda50ae2e8772a5c1fa5ef9ef47072d102e20c2/crates/cairo-lang-plugins/src/test_data/derive#L130)):*
> ```
>     fn clone(self: @TwoMemberGenericStruct<T, U, impl USomeTrait: SomeTrait<U, T>, >) -> TwoMemberGenericStruct<T, U, impl USomeTrait: SomeTrait<U, T>, > {
>         TwoMemberGenericStruct {
>             a: self.a.clone(),
> ```

This is where the compiler complains that self.a is dropped if I don't add the TDestruct impl, which is odd to me, but there's definitely a chance I'm just not fully understanding this linear type thing.
___
*[`tests/bug_samples/issue2964.cairo` line 12 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2964#-NUCUx8OCVjqRzDk3wMl:-NUGllCtAXeypGeLwYS8:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/f831fe57feb5063fde1d3fe04b81f244aa82fb1f/tests/bug_samples/issue2964.cairo#L12)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Right, like u said, constant generics don't work yet. You can remove this from the test for now, with a TODO to check it as well. Put the todo on me (spapini)
</blockquote></details>

Done
___
*[`tests/bug_samples/issue2964.cairo` line 26 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2964#-NUGmPjtEPMWf7QTG0WX:-NUGmPjtEPMWf7QTG0WY:b-vg7pm2) ([raw file](https://github.com/starkware-libs/cairo/blob/4eda50ae2e8772a5c1fa5ef9ef47072d102e20c2/tests/bug_samples/issue2964.cairo#L26)):*
> ```Cairo
> #[test]
> fn main() {
>     // This assumes that Drop implies Destruct and Copy implies Clone
> ```

I believe this is correct, but I've seen comments in the core lib that implies it might not stay that way?

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2964)* status: all files reviewed, 7 unresolved discussions (waiting on @wraitii)

___
*[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 228 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2964#-NUGluTi-IBZZpimQMR8:-NUH9F5B2fayvOyx8S7o:b-349zs1) ([raw file](https://github.com/starkware-libs/cairo/blob/4eda50ae2e8772a5c1fa5ef9ef47072d102e20c2/crates/cairo-lang-plugins/src/plugins/derive.rs#L228)):*
<details><summary><i>Previously, wraitii (Lancelot de Ferrière) wrote…</i></summary><blockquote>

It's unclear to me why Clone requires Destruct exactly (or rather, it's unclear to me what is getting destructed?). See comment in `derive` test below.
</blockquote></details>

See below
___
*[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 314 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2964#-NUGm1-J4mWFFRIqicSf:-NUH9GRW1DZ2b6qcK0Ek:b-pnhr5h) ([raw file](https://github.com/starkware-libs/cairo/blob/4eda50ae2e8772a5c1fa5ef9ef47072d102e20c2/crates/cairo-lang-plugins/src/plugins/derive.rs#L314)):*
<details><summary><i>Previously, wraitii (Lancelot de Ferrière) wrote…</i></summary><blockquote>

Also added Destruct here, takes ownership so for now this sorta makes sense to me
</blockquote></details>

See below
___
*[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 368 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2964#-NUGm5xe4IqHIYcPJcWi:-NUH9MfI8yLUXBmMbbEm:b-349zs1) ([raw file](https://github.com/starkware-libs/cairo/blob/4eda50ae2e8772a5c1fa5ef9ef47072d102e20c2/crates/cairo-lang-plugins/src/plugins/derive.rs#L368)):*
<details><summary><i>Previously, wraitii (Lancelot de Ferrière) wrote…</i></summary><blockquote>

Likewise added Destruct
</blockquote></details>

See below
___
*[`crates/cairo-lang-plugins/src/test_data/derive` line 130 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2964#-NUGmAB32cwMunb1_QpE:-NUH7v13AP0BPuyURfb6:b-ueklrd) ([raw file](https://github.com/starkware-libs/cairo/blob/4eda50ae2e8772a5c1fa5ef9ef47072d102e20c2/crates/cairo-lang-plugins/src/test_data/derive#L130)):*
<details><summary><i>Previously, wraitii (Lancelot de Ferrière) wrote…</i></summary><blockquote>

This is where the compiler complains that self.a is dropped if I don't add the TDestruct impl, which is odd to me, but there's definitely a chance I'm just not fully understanding this linear type thing.
</blockquote></details>

The member borrowing logic does not recognize snapshots right now. This leads to multiple issues.
Here, self.a.clone() can panic, when when it does, self.a and self.b are borrowed byt value, and need to be dropped.

The correct fix here is to fix the borrowing logic to include snapshot. This will also fix https://github.com/starkware-libs/cairo/issues/2816.

For now, add a TODO on the derive, to remove the Destruct requirements.
___
*[`tests/bug_samples/issue2964.cairo` line 21 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2964#-NUH8xKABhhZYOx_R99H:-NUH8xKABhhZYOx_R99I:b-mdyu61) ([raw file](https://github.com/starkware-libs/cairo/blob/4eda50ae2e8772a5c1fa5ef9ef47072d102e20c2/tests/bug_samples/issue2964.cairo#L21)):*
> ```Cairo
> //#[derive(Drop)]
> struct GenericStructConst<T, const U: felt252> {
>     x: T, 
> ```

Remove extra whitespace at the end of the line.



_Code quote:_
```Cairo
·
```
___
*[`tests/bug_samples/issue2964.cairo` line 26 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2964#-NUGmPjtEPMWf7QTG0WX:-NUH934uEwnlTx8WCKP-:b-cv85y3) ([raw file](https://github.com/starkware-libs/cairo/blob/4eda50ae2e8772a5c1fa5ef9ef47072d102e20c2/tests/bug_samples/issue2964.cairo#L26)):*
<details><summary><i>Previously, wraitii (Lancelot de Ferrière) wrote…</i></summary><blockquote>

I believe this is correct, but I've seen comments in the core lib that implies it might not stay that way?
</blockquote></details>

That's a nother topic:) You can assume this, it's ok.

**Review by wraitii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2964)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-plugins/src/test_data/derive` line 130 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2964#-NUGmAB32cwMunb1_QpE:-NUHnNsf0GQ_56Mksyy7:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/4eda50ae2e8772a5c1fa5ef9ef47072d102e20c2/crates/cairo-lang-plugins/src/test_data/derive#L130)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

The member borrowing logic does not recognize snapshots right now. This leads to multiple issues.
Here, self.a.clone() can panic, when when it does, self.a and self.b are borrowed byt value, and need to be dropped.

The correct fix here is to fix the borrowing logic to include snapshot. This will also fix https://github.com/starkware-libs/cairo/issues/2816.

For now, add a TODO on the derive, to remove the Destruct requirements.
</blockquote></details>

Done
___
*[`tests/bug_samples/issue2964.cairo` line 21 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2964#-NUH8xKABhhZYOx_R99H:-NUHnP4P8Q6Ab6CElmHZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4eda50ae2e8772a5c1fa5ef9ef47072d102e20c2/tests/bug_samples/issue2964.cairo#L21)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Remove extra whitespace at the end of the line.
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2964)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wraitii)

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2964)* status: all files reviewed, 2 unresolved discussions (waiting on @wraitii)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2964#-NUK_egDCiuv32Hunqca:-NUK_egDCiuv32Hunqcb:b-hg4rhs) (no related file):*
Note that clippy fails.

___
___
*[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 314 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2964#-NUK_cKd3gW1igFw3-y6:-NUK_cKd3gW1igFw3-y7:budq0an) ([raw file](https://github.com/starkware-libs/cairo/blob/8b83a2358103b3763690165d70dbbe4dc4bc4514/crates/cairo-lang-plugins/src/plugins/derive.rs#L314)):*
> ```XML
>                 }).join("\n        "),
>                 generics = format_generics(type_generics, other_generics),
>                 // TODO(spapini): Remove the Destruct requirement by changing member borrowing logic to recognize snapshots.
> ```

Keep lines under 100 chars.

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2964)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @wraitii)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2964#-:-NUR4_Nx8VfrfcVxXDrz:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @wraitii)

**Pull request merged**
