### PR TITLE
Add poseidon_hash_span.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2614)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2614)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @liorgold2)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2614#-NRYYsUG774ytTumVeAd:-NRYYsUG774ytTumVeAe:b-ncsa83) (no related file):*
let us wait on the rust-vm having poseidon so we'd have a user code test for this as well. (should happen today)

___
___
*[`corelib/src/poseidon.cairo` line 24 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2614#-NRYWKDO1SGIgCCVBBcI:-NRYWKDO1SGIgCCVBBcJ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6a6bf610fc4869142a2a9e46bdaf94b437090d02/corelib/src/poseidon.cairo#L24)):*
> ```Cairo
> // To distinguish between different input sizes always pad with 1 and possibly with another 0 to
> // complete to an even sized input.
> fn poseidon_hash_span(ref span: Span<felt252>) -> felt252 {
> ```





_Suggestion:_
```Cairo
fn poseidon_hash_span(mut span: Span<felt252>) -> felt252 {
```

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2614)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`corelib/src/poseidon.cairo` line 21 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2614#-NRlowCOC9RJL4ARG20z:-NRlowCOC9RJL4ARG21-:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6a6bf610fc4869142a2a9e46bdaf94b437090d02/corelib/src/poseidon.cairo#L21)):*
> ```Cairo
> 
> // Apply the sponge construction to digest many elements.
> // To distinguish between the use cases the capacity element is initialized to 0.
> ```





_Suggestion:_
```Cairo
/// Computes the Poseidon hash on the given input.
///
/// Applies the sponge construction to digest many elements.
/// To distinguish between use cases, the capacity element is initialized to 0.
/// To distinguish between different input sizes always pads with 1, and possibly with another 0 to
/// complete to an even-sized input.
```

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2614)* status: all files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/poseidon.cairo` line 31 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2614#-NRlpzlX5EF0EyggqCLA:-NRlpzlX5EF0EyggqCLB:b-dd3chd) ([raw file](https://github.com/starkware-libs/cairo/blob/6a6bf610fc4869142a2a9e46bdaf94b437090d02/corelib/src/poseidon.cairo#L31)):*
> ```Cairo
> fn _poseidon_hash_span_inner(
>     state: PoseidonBuiltinState, ref span: Span<felt252>
> ) -> PoseidonBuiltinState {
> ```

Just return the final felt (`s0`). There's no reason to return all of them.



_Code quote:_
```Cairo
-> PoseidonBuiltinState
```
___
*[`corelib/src/poseidon.cairo` line 45 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2614#-NRlppNw7qyQR6UfOrUB:-NRlppNw7qyQR6UfOrUC:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6a6bf610fc4869142a2a9e46bdaf94b437090d02/corelib/src/poseidon.cairo#L45)):*
> ```Cairo
>             // Pad input with [1, 0].
>             let (s0, s1, s2) = hades_permutation(state.s0 + *x, state.s1 + 1, state.s2);
>             return PoseidonBuiltinState { s0, s1, s2 };
> ```





_Suggestion:_
```Cairo
            // Add x and pad with [0].
            let (s0, s1, s2) = hades_permutation(state.s0 + *x, state.s1 + 1, state.s2);
            return PoseidonBuiltinState { s0, s1, s2 };
```

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2614)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`corelib/src/poseidon.cairo` line 45 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2614#-NRlppNw7qyQR6UfOrUB:-NRxpOWZ48TztzDnHguf:b-pga6si) ([raw file](https://github.com/starkware-libs/cairo/blob/6a6bf610fc4869142a2a9e46bdaf94b437090d02/corelib/src/poseidon.cairo#L45)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Fix comment (or not pushed yet?)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2614)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2614#-NRYYsUG774ytTumVeAd:-NRxpWq-8ybuHkCWDqT1:b840qub) (no related file):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I think we should merge this and not wait for the vm.
</blockquote></details>

IIUC the VM was already released, wasn't it?

___

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2614)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @liorgold2)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2614#-NRYYsUG774ytTumVeAd:-NS-TwWE6T9c2w4UDtLI:b-r1xft) (no related file):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

IIUC the VM was already released, wasn't it?
</blockquote></details>

apparently not - it should be in the next release which should be this week IIUC.

___

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2614)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`corelib/src/poseidon.cairo` line 45 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2614#-NRlppNw7qyQR6UfOrUB:-NS-ncLG7xRROwb7Wp5a:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6a6bf610fc4869142a2a9e46bdaf94b437090d02/corelib/src/poseidon.cairo#L45)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Fix comment (or not pushed yet?)
</blockquote></details>

Done.

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2614#-:-NSCtvk98D186ZZnONS6:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2614#-:-NS_CBb--uorFMDuqoR4:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Pull request merged**
