### PR TITLE
Added parser for type aliases.

### PR DESCRIPTION
**Pull request by orizi**
No resolve of aliases yet.

commit-id:669bdaa9

---

**Stack**:
- #1508
- #1504
- #1503
- #1498
- #1485 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1485)* status: 5 of 11 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/parser/src/parser.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1485#-NKCfbc_214ai2JII9px:-NKCfbc_214ai2JII9py:b1he046) ([raw file](https://github.com/starkware-libs/cairo/blob/ffc7556ec2a8b48f06562e824210c9a29fc1e743/crates/parser/src/parser.rs#L213)):*
> ```XML
>     /// Expected pattern: `type <Identifier>{<ParamList>} = <TypeExpression>`
>     fn expect_type_alias(&mut self, attributes: AttributeListGreen) -> ItemTypeAliasGreen {
>         let type_kw = self.parse_token::<TerminalType>();
> ```

Use `take` like in `expect_free_function`

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 6 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1485)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by spapinistarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1485)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1485#-:-NKD_RaD3NiypqqmIaA6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1485)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
