### PR TITLE
Changed implicits phase to use concrete functions

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2379)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2379)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/implicits/mod.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2379#-NPrAMgP6hfBEaHXv2a8:-NPrAMgP6hfBEaHXv2a9:b-uwbg4i) ([raw file](https://github.com/starkware-libs/cairo/blob/deff27883663b555d231c7ec55f29cac3e7b961c/crates/cairo-lang-lowering/src/implicits/mod.rs#L55)):*
> ```XML
>     lowering_ctx.variables = lowered.variables.clone();
> 
>     let implicits_tys = db.function_with_body_all_implicits_vec(function_id)?;
> ```

can you rename to concrete_?



_Code quote:_
```XML
function_with_body_all_implicits_vec
```
___
*[`crates/cairo-lang-lowering/src/implicits/mod.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2379#-NPrAicV8lc99-yJVeTa:-NPrAicV8lc99-yJVeTb:b-mluuf6) ([raw file](https://github.com/starkware-libs/cairo/blob/deff27883663b555d231c7ec55f29cac3e7b961c/crates/cairo-lang-lowering/src/implicits/mod.rs#L104)):*
> ```XML
>         if let Statement::Call(stmt) = statement {
>             let callee_implicits =
>                 ctx.db.function_all_implicits(stmt.function.get_concrete(ctx.db.upcast()))?;
> ```

I'd rather this function gets FunctionId. This is the more correct intefrace IMO, since this place doesn't care if it's a concrete, or some other function (e.g. function pointer).



_Code quote:_
```XML
.get_concrete(ctx.db.upcast()
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2379)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/scc/mod.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2379#-NPrAyy41oScPZoNEnM-:-NPrAyy41oScPZoNEnM0:b-dkv3f1) ([raw file](https://github.com/starkware-libs/cairo/blob/deff27883663b555d231c7ec55f29cac3e7b961c/crates/cairo-lang-lowering/src/scc/mod.rs#L69)):*
> ```XML
> pub fn function_all_implicits(
>     db: &dyn LoweringGroup,
>     function: ConcreteFunction,
> ```

FunctionId is better IMO, see above



_Code quote:_
```XML
ConcreteFunction,
```

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2379)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 230 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2379#-NPrBINV50ftBCCijXCx:-NPrBINV50ftBCCijXCy:bgwtgeb) ([raw file](https://github.com/starkware-libs/cairo/blob/deff27883663b555d231c7ec55f29cac3e7b961c/crates/cairo-lang-semantic/src/items/functions.rs#L230)):*
> ```XML
>     pub fn try_get_extern_function_id(
>         &self,
>         // TODO(yg): remove static?
> ```

Yes, remove the static

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2379)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/implicits/mod.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2379#-NPrAicV8lc99-yJVeTa:-NPrEHVe-2KtQdRN53cV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/deff27883663b555d231c7ec55f29cac3e7b961c/crates/cairo-lang-lowering/src/implicits/mod.rs#L104)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I'd rather this function gets FunctionId. This is the more correct intefrace IMO, since this place doesn't care if it's a concrete, or some other function (e.g. function pointer).
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 230 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2379#-NPrBINV50ftBCCijXCx:-NPrEFXu29OUY_t3ut_T:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/deff27883663b555d231c7ec55f29cac3e7b961c/crates/cairo-lang-semantic/src/items/functions.rs#L230)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Yes, remove the static
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2379#-:-NPrEqod8uzew1T5LIyn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
