### PR TITLE
LS: Unrecognized LS requests to be cancelled on salsa failures

### LINKED ISSUE #6315: LS: Unrecognized LS requests to be cancelled on salsa failures
There are errors that aren't recognized properly as cancelled and result in LS crashes
Those can be reproduced with quickly writing and saving the file

Example stack trace:

```
 349.045077958s ERROR cairo_lang_language_server: caught panic when computing diagnostics for vfs://677/impls.cairo
thread 'tokio-runtime-worker' panicked at /Users/timelock/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rust-analyzer-salsa-0.17.0-pre.6/src/derived/slot.rs:301:21:
assertion failed: old_memo.revisions.changed_at <= revisions.changed_at
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: salsa::derived::slot::Slot<Q,MP>::execute
   4: salsa::derived::slot::Slot<Q,MP>::maybe_changed_after
   5: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_after
   6: salsa::derived::slot::Memo<V>::verify_revisions
   7: salsa::derived::slot::Slot<Q,MP>::maybe_changed_after
   8: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_after
   9: salsa::derived::slot::Memo<V>::verify_revisions
  10: salsa::derived::slot::Slot<Q,MP>::maybe_changed_after
  11: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_after
  12: salsa::derived::slot::Memo<V>::verify_revisions
  13: salsa::derived::slot::Slot<Q,MP>::read
  14: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
  15: <DB as cairo_lang_parser::db::ParserGroup>::file_syntax::__shim
  16: cairo_lang_language_server::ide::code_actions::code_actions
  17: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  18: tokio::runtime::task::core::Core<T,S>::poll
  19: tokio::runtime::task::harness::Harness<T,S>::poll
  20: tokio::runtime::blocking::pool::Inner::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
 350.446812500s ERROR cairo_lang_language_server: caught panic in LSP worker thread
[Error - 17:00:41] Request textDocument/codeAction failed.
  Message: Internal error
  Code: -32603 
```

### PR DESCRIPTION
**Pull request by Draggu**
fix #6315

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6319)

### CODE REVIEW

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6319#-:-O5XdQau2gyjGUvGZE-S:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @orizi, and @piotmag769)

**Review by piotmag769 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6319)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @orizi)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6319#-:-O5gBPJtDCkqiMN2D8J0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae)

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6319)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae)

**Comment by baitcode** [comment]
Well done. Is there any issue on Salsa side to allow for more granular errors? Let me know if there is not, I'll create one. And may be try to fix it.

**Comment by mkaput** [comment]
> Well done. Is there any issue on Salsa side to allow for more granular errors? Let me know if there is not, I'll create one. And may be try to fix it.

Hey! In general, we're working around a Salsa bug here, and it just would be nice to just fix the condition in Salsa that triggers the assertion that we are catching here.

**Pull request merged**
