### PR TITLE
Documentation/rename fixes

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2059)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2059#-:-NNkbkbGA3-_Pm0Je2oJ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-utils/src/strongly_connected_components.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2059#-NNkbfuJ0IVYu2ftw_ph:-NNkbfuJ0IVYu2ftw_pi:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/36f3648cf8f46c3298d6db47c2dd01843db2ebcd/crates/cairo-lang-utils/src/strongly_connected_components.rs#L18)):*
> ```XML
>     /// Returns a list of the node's neighbors.
>     /// Must be stable for the scc result to be stable. i.e. if the output for a node here doesn't
>     /// change between different runs, the computed SCC of the node is guaranteed to also not
> ```





_Suggestion:_
```XML
    /// Returns a list of the node's neighbors.
    /// Must be stable for the SCC result to be stable. i.e. if the output for a node here doesn't
    /// change between different runs, the computed SCC of the node is guaranteed to also not
    /// change.
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2059)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-utils/src/strongly_connected_components.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2059#-NNkbfuJ0IVYu2ftw_ph:-NNlpAWc4DH5KDnz_Oer:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/36f3648cf8f46c3298d6db47c2dd01843db2ebcd/crates/cairo-lang-utils/src/strongly_connected_components.rs#L18)):*
> ```XML
>     /// Returns a list of the node's neighbors.
>     /// Must be stable for the scc result to be stable. i.e. if the output for a node here doesn't
>     /// change between different runs, the computed SCC of the node is guaranteed to also not
> ```

Done.

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2059)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by yuvalsw — COMMENTED** [review]
> Dismissed @orizi from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2059)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
