### PR TITLE
Added EntryPointKind

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2631)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2631)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 290 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2631#-NRcYuwQ8OewWPMHfYP4:-NRcYuwQ8OewWPMHfYP5:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/b42808bfeaec54d05d2307a201eab48f5d3afc19/crates/cairo-lang-starknet/src/plugin/contract.rs#L290)):*
> ```XML
> 
> // TODO(yg): move?
> // TODO(yg): doc enum anf function.
> ```

?



_Code quote:_
```XML
// TODO(yg): doc enum anf function.
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2631)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2631#-NRcZH6V7qxw_6ptL_pi:-NRcZH6V7qxw_6ptL_pj:b-an18xj) ([raw file](https://github.com/starkware-libs/cairo/blob/b42808bfeaec54d05d2307a201eab48f5d3afc19/crates/cairo-lang-starknet/src/plugin/contract.rs#L125)):*
> ```XML
>             }
>             ast::Item::FreeFunction(item_function) => {
>                 if let Some(entry_point_kind) = get_entry_point_kind(db, item_function) {
> ```

what happens if it is none?



_Code quote:_
```XML
 if let Some(entry_point_kind) = get_entry_point_kind(db, item_function) {
```

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2631#-:-NRgGDogBR3IJFguW1ns:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
Multiple attributes?
The logic didn't change, I just represented it more nicely.
Currently there is an order and if there are multiple attributes, the first of the order in the code will be taken into account. We might need to revisit this anyway.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2631#-:-NRgHjjs9kTJgmcQZ-VN:b-oie3f2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
