### PR TITLE
Remove FlatBlockEnd::Fallthrough.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
After the topological sort, we can check if
FlatBlockEnd::Goto(target_block_id, _) should be a fallthrough using the condition: *target_block_id == block_id.next().

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2340)

### CODE REVIEW

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 13 of 13 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2340#-:-NPWBgzN2p-C6vNfvo8G:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi and @yuvalsw)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 10 of 13 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2340)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/objects/blocks.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2340#-NPWCKFZ-nvMrrr5EfKx:-NPWCKFZ-nvMrrr5EfKy:b7f3myb) ([raw file](https://github.com/starkware-libs/cairo/blob/92f5bbd92200a77e9bc05583fcb7f2061297ea11/crates/cairo-lang-lowering/src/objects/blocks.rs#L19)):*
> ```XML
>     }
> 
>     pub fn next(&self) -> BlockId {
> ```

maybe `next_block` just to not make this seem like an iterator?



_Code quote:_
```XML
next
```

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2340#-:-NPWCUQ91PPcG0IYO2dl:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @yuvalsw)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2340)* status: 10 of 13 files reviewed, 1 unresolved discussion (waiting on @orizi, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/objects/blocks.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2340#-NPWCKFZ-nvMrrr5EfKx:-NPWEEERBIxtLZ_TIcGP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/92f5bbd92200a77e9bc05583fcb7f2061297ea11/crates/cairo-lang-lowering/src/objects/blocks.rs#L19)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe `next_block` just to not make this seem like an iterator?
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 9 of 13 files at r1, 1 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2340)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @yuvalsw)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2340)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 31 of 31 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2340)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
