### PR TITLE
Interned all strings.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6011)

### CODE REVIEW

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6011)* status: 0 of 124 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @ilyalesokhin-starkware, and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6011#-O1WdVSFAkgh2zRgjX8E:-O1WdVSFAkgh2zRgjX8F:br3noe9) (no related file):*
This change sounds like it will create a massive memory leak-style behaviour, especially in the LS. Salsa has no means for garbage collection for interned items (LRU doesn't work there), so it will hard for me to combat in LS.

___

**Comment by ilyalesokhin-starkware** [comment]
Why did you remove all the Smolstr usage?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-syntax/src/node/ids.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6011#-O1jlOuZ6g42vl9qRpkR:-O1jlOuZ6g42vl9qRpkS:b-97wqu8) ([raw file](https://github.com/starkware-libs/cairo/blob/24dd4cd763cd77fde29bcd4b1c2b49d1cfd67d6f/crates/cairo-lang-syntax/src/node/ids.rs#L12)):*
> ```XML
> use crate::node::stable_ptr::SyntaxStablePtr;
> 
> define_short_id!(TextId, Arc::<str>, SyntaxGroup, lookup_intern_text, intern_text);
> ```

Maybe StringId?
(non-blocking)



_Suggestion:_
```XML
StringId
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/items/modifiers.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6011#-O1jqU-P6ZViA9KmLTlJ:-O1jqU-P6ZViA9KmLTlK:b-x9d1hb) ([raw file](https://github.com/starkware-libs/cairo/blob/24dd4cd763cd77fde29bcd4b1c2b49d1cfd67d6f/crates/cairo-lang-semantic/src/items/modifiers.rs#L16)):*
> ```XML
>     modifier_list: &[Modifier],
> ) -> Mutability {
>     let mut last: Option<&Modifier> = None;
> ```

why is this change is the same PR?



_Code quote:_
```XML
let mut last: Option<&Modifier> = None;
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 502 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6011#-O1jqw5OECnNAlqHiEd7:-O1jqw5OECnNAlqHiEd8:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/24dd4cd763cd77fde29bcd4b1c2b49d1cfd67d6f/crates/cairo-lang-semantic/src/resolve/mod.rs#L502)):*
> ```XML
>             ast::PathSegment::WithGenericArgs(_) => false,
>             ast::PathSegment::Simple(simple) => {
>                 simple.ident(syntax_db).text(syntax_db) == TextId::interned("super", self.db)
> ```





_Suggestion:_
```XML
simple.ident(syntax_db).text(syntax_db).lookup_intern(self.db).as_ref() == "super"
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 92 of 124 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6011)* status: 92 of 124 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 502 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6011#-O1jqw5OECnNAlqHiEd7:-O1jr46g6EOSd4alepEG:b-ustjhr) ([raw file](https://github.com/starkware-libs/cairo/blob/24dd4cd763cd77fde29bcd4b1c2b49d1cfd67d6f/crates/cairo-lang-semantic/src/resolve/mod.rs#L502)):*
> ```XML
>             ast::PathSegment::WithGenericArgs(_) => false,
>             ast::PathSegment::Simple(simple) => {
>                 simple.ident(syntax_db).text(syntax_db) == TextId::interned("super", self.db)
> ```

other places as well.

**Review by orizi — COMMENTED** [review]
Most of it should just have become the inner arc<str> - there may be some spill over.
in any case - it seems the over abundance of arc is enough of an issue to make this not really worth it.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6011#-:-O1jwH4r1Hu_MtdB7pvc:bvqzoyh)* status: 92 of 124 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware, @ilyalesokhin-starkware, and @mkaput)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6011#-O1WdVSFAkgh2zRgjX8E:-O1jwCCd2aQqv4oehAfz:b-ax4g8u) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

This change sounds like it will create a massive memory leak-style behaviour, especially in the LS. Salsa has no means for garbage collection for interned items (LRU doesn't work there), so it will hard for me to combat in LS.
</blockquote></details>

this is no worse than the entire existing db - only removing the duplication of data.

___
___
*[`crates/cairo-lang-semantic/src/items/modifiers.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6011#-O1jqU-P6ZViA9KmLTlJ:-O1jwdIA1u3ThVAZvJTv:b-yh78i5) ([raw file](https://github.com/starkware-libs/cairo/blob/24dd4cd763cd77fde29bcd4b1c2b49d1cfd67d6f/crates/cairo-lang-semantic/src/items/modifiers.rs#L16)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why is this change is the same PR?
</blockquote></details>

it was removal of being text dependent.

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6011)* status: 92 of 124 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware, @ilyalesokhin-starkware, and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6011#-O1WdVSFAkgh2zRgjX8E:-O1qg0y6-wjsKLGEwqbA:bltlsey) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is no worse than the entire existing db - only removing the duplication of data.
</blockquote></details>

Yes, it is no worse, but it's also not better, and I think it'd be better to only take steps towards better memory management?

Have you measured how much memory is actually deduplicated here? Note that `Arc<str>` and `SmolStr` do also deduplicate clones, yet they properly deallocate when the last instance is dropped.

___

**Review by mkaput — COMMENTED** [review]
> Reviewed 124 of 124 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6011)* status: all files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware, @ilyalesokhin-starkware, and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6011#-O2xhU_557cUfq4jRn9e:-O2xhU_6Cjc8d4LvVb53:b-cdnplk) (no related file):*
FYI https://doc.rust-lang.org/stable/alloc/sync/struct.Arc.html#impl-Default-for-Arc%3Cstr%3E stabilized in Rust 1.80

___

**Pull request closed without merging**
