### PR TITLE
Added syntax and parsing for associated constant

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4641)

### CODE REVIEW

**Comment by yuvalsw** [comment]
change target branch

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4641)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-syntax-codegen/src/cairo_spec.rs` line 565 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4641#-NmCvimyBMKXCSo_yVrC:-NmCvimyBMKXCSo_yVrD:b-b00pzf) ([raw file](https://github.com/starkware-libs/cairo/blob/92d36e602be450313a8192d20cdbc46934ba57e3/crates/cairo-lang-syntax-codegen/src/cairo_spec.rs#L565)):*
> ```XML
>         .node_with_explicit_kind("Function", "FunctionWithBody")
>         .node("AssociatedType")
>         .node_with_explicit_kind("AssociatedConstant", "ItemConstant")
> ```

why `Associated` we are already in the impl context.
`Function` is not `Associated` as well.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4641)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4641#-NmR6s8zD0FPjZlMVVJS:-NmR6s8zD0FPjZlMVVJT:bho2s9) (no related file):*
awaiting rebase and item rename.

___

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4641)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4641#-NmR6s8zD0FPjZlMVVJS:-NmRGyqa2LSvOsyIcGS5:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

awaiting rebase and item rename.
</blockquote></details>

Done.

___
___
*[`crates/cairo-lang-syntax-codegen/src/cairo_spec.rs` line 565 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4641#-NmCvimyBMKXCSo_yVrC:-NmR95Dw0yFrnD98DuQc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/92d36e602be450313a8192d20cdbc46934ba57e3/crates/cairo-lang-syntax-codegen/src/cairo_spec.rs#L565)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why `Associated` we are already in the impl context.
`Function` is not `Associated` as well.
</blockquote></details>

Done.

**Pull request closed without merging**
