### PR TITLE
added calling expressions on closures

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6192)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6192)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 146 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6192#-O44nwdu3vBgX5JsB3vc:-O44nwdvE3B78ifdQ7a5:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e957ee9293e4101207fa96562cea66e9cdeef1d5/crates/cairo-lang-semantic/src/expr/compute.rs#L146)):*
> ```XML
>     cfg_set: Arc<CfgSet>,
>     /// whether to look for closures when calling variables.
>     /// TODO(TomerStarkware): Remove this once we disallow calling overshadowed functions.
> ```





_Suggestion:_
```XML
    /// whether to look for closures when calling variables.
    /// TODO(TomerStarkware): Remove this once we disallow calling shadowed functions.
```
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 880 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6192#-O44oafs7F-glcAO0yCH:-O44oaft8qDV4tX2TjlH:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e957ee9293e4101207fa96562cea66e9cdeef1d5/crates/cairo-lang-semantic/src/expr/compute.rs#L880)):*
> ```XML
>         }
>         ResolvedConcreteItem::Function(function) => {
>             if is_over_shadow_by_variable {
> ```





_Suggestion:_
```XML
            if is_shadowed_by_variable {
```
___
*[`crates/cairo-lang-semantic/src/expr/test_data/closure` line 297 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6192#-O44qJLx6NN6GYKJsQsd:-O44qJLx6NN6GYKJsQse:bcrcwxp) ([raw file](https://github.com/starkware-libs/cairo/blob/e957ee9293e4101207fa96562cea66e9cdeef1d5/crates/cairo-lang-semantic/src/expr/test_data/closure#L297)):*
> ```
> error: Trait has no implementation in context: core::traits::Into::<core::integer::u256, core::integer::u32>.
>  --> lib.cairo:3:22
>         a.into() + b.into() + c.into()
> ```

have a tests without diagnostics.

also explain why there's only one.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/closure` line 302 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6192#-O44qdeNAsaysDjVyp5L:-O44qdeNAsaysDjVyp5M:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e957ee9293e4101207fa96562cea66e9cdeef1d5/crates/cairo-lang-semantic/src/expr/test_data/closure#L302)):*
> ```
> //! > ==========================================================================
> 
> //! > Test overshadowing a function with a variable.
> ```





_Suggestion:_
```
Test shadowing of a function with a variable.
```
___
*[`crates/cairo-lang-semantic/src/expr/test_data/closure` line 305 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6192#-O44qxuGCC08R5tSYiRT:-O44qxuGCC08R5tSYiRU:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e957ee9293e4101207fa96562cea66e9cdeef1d5/crates/cairo-lang-semantic/src/expr/test_data/closure#L305)):*
> ```
> 
> //! > test_runner_name
> test_function_diagnostics(expect_diagnostics: true)
> ```





_Suggestion:_
```
test_function_diagnostics(expect_diagnostics: warnings_only)
```
___
*[`crates/cairo-lang-semantic/src/expr/test_data/closure` line 329 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6192#-O44rbvwCt2xHoS-0Ke_:-O44rbvwCt2xHoS-0Kea:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e957ee9293e4101207fa96562cea66e9cdeef1d5/crates/cairo-lang-semantic/src/expr/test_data/closure#L329)):*
> ```
> //! > ==========================================================================
> 
> //! > Test overshadowing a function with a variable when closure are in context.
> ```





_Suggestion:_
```
//! > Test shadowing a function with a variable when closure are in context.
```
___
*[`crates/cairo-lang-semantic/src/expr/test_data/closure` line 368 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6192#-O44rZdc4uoWY-_FcPa0:-O44rZdc4uoWY-_FcPa1:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e957ee9293e4101207fa96562cea66e9cdeef1d5/crates/cairo-lang-semantic/src/expr/test_data/closure#L368)):*
> ```
> //! > ==========================================================================
> 
> //! > Test overshadowing a function with a closure.
> ```





_Suggestion:_
```
//! > Test shadowing a function with a closure.
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6192)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 146 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6192#-O44nwdu3vBgX5JsB3vc:-O44tCIT3xNAXLgkm4FM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e957ee9293e4101207fa96562cea66e9cdeef1d5/crates/cairo-lang-semantic/src/expr/compute.rs#L146)):*
> ```XML
>     cfg_set: Arc<CfgSet>,
>     /// whether to look for closures when calling variables.
>     /// TODO(TomerStarkware): Remove this once we disallow calling overshadowed functions.
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 880 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6192#-O44oafs7F-glcAO0yCH:-O44t8VnBS8noLB43Mh0:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e957ee9293e4101207fa96562cea66e9cdeef1d5/crates/cairo-lang-semantic/src/expr/compute.rs#L880)):*
> ```XML
>         }
>         ResolvedConcreteItem::Function(function) => {
>             if is_over_shadow_by_variable {
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/closure` line 297 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6192#-O44qJLx6NN6GYKJsQsd:-O44tE0S8XQIV4oX-6WL:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e957ee9293e4101207fa96562cea66e9cdeef1d5/crates/cairo-lang-semantic/src/expr/test_data/closure#L297)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

have a tests without diagnostics.

also explain why there's only one.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/closure` line 302 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6192#-O44qdeNAsaysDjVyp5L:-O44scRU-t9-ahyipfSe:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e957ee9293e4101207fa96562cea66e9cdeef1d5/crates/cairo-lang-semantic/src/expr/test_data/closure#L302)):*
> ```
> //! > ==========================================================================
> 
> //! > Test overshadowing a function with a variable.
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/closure` line 305 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6192#-O44qxuGCC08R5tSYiRT:-O44sOXe-BOy1M9RqP1H:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e957ee9293e4101207fa96562cea66e9cdeef1d5/crates/cairo-lang-semantic/src/expr/test_data/closure#L305)):*
> ```
> 
> //! > test_runner_name
> test_function_diagnostics(expect_diagnostics: true)
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/closure` line 329 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6192#-O44rbvwCt2xHoS-0Ke_:-O44sO9O3ODmxR0ZYsDh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e957ee9293e4101207fa96562cea66e9cdeef1d5/crates/cairo-lang-semantic/src/expr/test_data/closure#L329)):*
> ```
> //! > ==========================================================================
> 
> //! > Test overshadowing a function with a variable when closure are in context.
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/closure` line 368 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6192#-O44rZdc4uoWY-_FcPa0:-O44sEBH7Y5yHZOROJ2U:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e957ee9293e4101207fa96562cea66e9cdeef1d5/crates/cairo-lang-semantic/src/expr/test_data/closure#L368)):*
> ```
> //! > ==========================================================================
> 
> //! > Test overshadowing a function with a closure.
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6192#-:-O459PRAAm9es45jrNRO:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 769 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6192#-O45q0-s-EBFSt2holbA:-O45q0-s-EBFSt2holbB:beekl8q) ([raw file](https://github.com/starkware-libs/cairo/blob/5cc0ca9c359fceb405efdfb30b098347a5a9c781/crates/cairo-lang-semantic/src/expr/compute.rs#L769)):*
> ```XML
>         if let Some(var) = get_variable_by_name(ctx, &variable_name, path.stable_ptr().into()) {
>             is_shadowed_by_variable = true;
>             if ctx.are_closures_in_context {
> ```

why is this needed? Is this an optimization?



_Code quote:_
```XML
if ctx.are_closures_in_context {
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 812 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6192#-O45qU_6AKV5dnEYBsVX:-O45qU_6AKV5dnEYBsVY:b-n348k1) ([raw file](https://github.com/starkware-libs/cairo/blob/5cc0ca9c359fceb405efdfb30b098347a5a9c781/crates/cairo-lang-semantic/src/expr/compute.rs#L812)):*
> ```XML
>                 let args_expr = Expr::Tuple(ExprTuple {
>                     items: args,
>                     ty: TypeLongId::Tuple(arg_types.clone()).intern(db),
> ```

why is this cloned?



_Code quote:_
```XML
arg_types.clone()
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6192)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 769 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6192#-O45q0-s-EBFSt2holbA:-O46RlIpEnKTd3pkJRCK:bsducl2) ([raw file](https://github.com/starkware-libs/cairo/blob/5cc0ca9c359fceb405efdfb30b098347a5a9c781/crates/cairo-lang-semantic/src/expr/compute.rs#L769)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why is this needed? Is this an optimization?
</blockquote></details>

For now we dont want to break old code which called a function that has the same name has local variable
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 812 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6192#-O45qU_6AKV5dnEYBsVX:-O46RkUn4I33QwiGWxD9:b-hfpv0l) ([raw file](https://github.com/starkware-libs/cairo/blob/5cc0ca9c359fceb405efdfb30b098347a5a9c781/crates/cairo-lang-semantic/src/expr/compute.rs#L812)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why is this cloned?
</blockquote></details>

removed

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6192)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 769 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6192#-O45q0-s-EBFSt2holbA:-O49HQpBDOMHODmcatDT:b-ssgb8z) ([raw file](https://github.com/starkware-libs/cairo/blob/5cc0ca9c359fceb405efdfb30b098347a5a9c781/crates/cairo-lang-semantic/src/expr/compute.rs#L769)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

For now we dont want to break old code which called a function that has the same name has local variable
</blockquote></details>

can't you check the type of the variable instead of checking `are_closures_in_context`?

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6192)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 769 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6192#-O45q0-s-EBFSt2holbA:-O49aG2I07Wx_gntfJdd:bvx03zh) ([raw file](https://github.com/starkware-libs/cairo/blob/5cc0ca9c359fceb405efdfb30b098347a5a9c781/crates/cairo-lang-semantic/src/expr/compute.rs#L769)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

can't you check the type of the variable instead of checking `are_closures_in_context`?
</blockquote></details>

The type may also be var or generic.

Also, we eventually want to always look for the impl, and give an error if it is not found, this is just a workaround to not break existing code.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6192)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`ai8.txt` line 1 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6192#-O49tIHO1ZA0Trqz6tZU:-O49tIHO1ZA0Trqz6tZV:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/127417b2364ce8b7a4bd7cdc0663e9216099ee63/ai8.txt#L1)):*
> ```help
> 0. before_all: Parameters:
> ```

?

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6192)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`ai8.txt` line 1 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6192#-O49tIHO1ZA0Trqz6tZU:-O49yFzI5NYv4ZIlP-HH:bvth56w) ([raw file](https://github.com/starkware-libs/cairo/blob/127417b2364ce8b7a4bd7cdc0663e9216099ee63/ai8.txt#L1)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

reverted

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6192)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6192)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6192)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
