### PR TITLE
Added diagnostics for recursive types.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:064384af

---

**Stack**:
- #5482
- #5480
- #5478 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5478)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/db.rs` line 1142 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5478#-NwKFOhJ8hkJLp-7p80e:-NwKFOhK9d3csU3arWLf:b13hmha) ([raw file](https://github.com/starkware-libs/cairo/blob/72cb4d5c21a4536d6bc10c6ba60803e538f9a327/crates/cairo-lang-semantic/src/db.rs#L1142)):*
> ```XML
>     #[salsa::invoke(types::direct_recursive_type)]
>     #[salsa::cycle(types::direct_recursive_type_cycle)]
>     fn direct_recursive_type(&self, ty: types::TypeId) -> Maybe<bool>;
> ```

document.



_Code quote:_
```XML
 fn direct_recursive_type(&self, ty: types::TypeId) -> Maybe<bool>;
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5478)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 1142 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5478#-NwKFOhJ8hkJLp-7p80e:-NwKO8qA6Ind7a9U-r0G:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/72cb4d5c21a4536d6bc10c6ba60803e538f9a327/crates/cairo-lang-semantic/src/db.rs#L1142)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

document.
</blockquote></details>

Done.

**Comment by orizi** [comment]
Closing pull request: commit has gone away

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/items/tests/struct` line 59 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5478#-NwhfeO91Xd7f2p3XaQl:-NwhfeOA5Bvn4rv1uzlJ:b6rn6pr) ([raw file](https://github.com/starkware-libs/cairo/blob/3300fdd9f035ffd7ad9de543af9c9553e9e64b13/crates/cairo-lang-semantic/src/items/tests/struct#L59)):*
> ```
>     ^*******^
> 
> error: Direct recursive type "test::A".
> ```

rust give:
recursive type `types::A` has infinite size



_Code quote:_
```
error: Direct recursive type "test::A".
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/items/tests/struct` line 59 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5478#-NwhfeO91Xd7f2p3XaQl:-Nwhfro74l79Wbm5bj9w:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/3300fdd9f035ffd7ad9de543af9c9553e9e64b13/crates/cairo-lang-semantic/src/items/tests/struct#L59)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

rust give:
recursive type `types::A` has infinite size
</blockquote></details>





_Code snippet:_
```
error[E0072]: recursive type `types::A` has infinite size
   --> crates/cairo-lang-semantic/src/types.rs:794:1
    |
794 | struct A {
    | ^^^^^^^^
795 |     a: i32,
796 |     b: A,
    |        - recursive without indirection
    |
help: insert some indirection (e.g., a `Box`, `Rc`, or `&`) to break the cycle
    |
796 |     b: Box<A>,
    |        ++++ +
```

**Pull request closed without merging**
