### PR TITLE
Add sierra const enums.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4706)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4706)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 103 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4706#-Nn4MjV9AFxtxQl5s5gR:-Nn4MjV9AFxtxQl5s5gS:b-kef3ea) ([raw file](https://github.com/starkware-libs/cairo/blob/28e4813839e9729d223071c7fd7b1822300d3530/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L103)):*
> ```XML
> 
> /// Given a const type representing a struct, validates that the inner data types are compatible
> /// with the struct types, and recursively validates the inner data.
> ```

no need for recursion - it is tested by the system (as the inner cost-type was already validated)



_Code quote:_
```XML
/// with the struct types, and recursively validates the inner data.
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 147 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4706#-Nn4MrKc4Fj_h8vLzpjU:-Nn4MrKc4Fj_h8vLzpjV:b2lt5uv) ([raw file](https://github.com/starkware-libs/cairo/blob/28e4813839e9729d223071c7fd7b1822300d3530/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L147)):*
> ```XML
> 
> /// Given a const type representing an enum, validates that the inner data is a selector followed by
> /// a const type of the corresponding variant, and recursively validates the const type.
> ```

no recursion again.
already internally tested by the const type construction.



_Code quote:_
```XML
/// a const type of the corresponding variant, and recursively validates the const type.
```
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler_test.rs` line 671 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4706#-Nn4N0e-6Gqoy_4sZTpa:-Nn4N0e-6Gqoy_4sZTpb:b-dcrvil) ([raw file](https://github.com/starkware-libs/cairo/blob/28e4813839e9729d223071c7fd7b1822300d3530/crates/cairo-lang-sierra-to-casm/src/compiler_test.rs#L671)):*
> ```XML
>         type Box<MyEnum> = Box<MyEnum>;
> 
>         libfunc const_as_box<const<MyEnum, 0, const<felt252, 5>>> = const_as_box<const<MyEnum, 0, const<felt252, 5>>>;
> ```

long line

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4706)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 103 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4706#-Nn4MjV9AFxtxQl5s5gR:-Nn4NzHmAEWkH6fF66gv:bflynr6) ([raw file](https://github.com/starkware-libs/cairo/blob/28e4813839e9729d223071c7fd7b1822300d3530/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L103)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no need for recursion - it is tested by the system (as the inner cost-type was already validated)
</blockquote></details>

Done. (In the parent pr).
___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 147 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4706#-Nn4MrKc4Fj_h8vLzpjU:-Nn4O0Xm6K2JJl1MFPPc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/28e4813839e9729d223071c7fd7b1822300d3530/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L147)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no recursion again.
already internally tested by the const type construction.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler_test.rs` line 671 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4706#-Nn4N0e-6Gqoy_4sZTpa:-Nn4O5VZ9RAYwGijh0Lh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/28e4813839e9729d223071c7fd7b1822300d3530/crates/cairo-lang-sierra-to-casm/src/compiler_test.rs#L671)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

long line
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4706#-:-Nn4TY0dDafhWFEK6rq0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4706)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4706)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
