### PR TITLE
Add Poseidon hashing functions for one and two values 

### PR DESCRIPTION
**Pull request by Leonard-Pat**
This PR proposes two new wrapper functions for Poseidon hashing. 

1. `hash_one_element`
2. `hash_two_elements`

With the current implementation of Poseidon hashing one/two values is different to Pedersen due to the nature of the algorithm, however both implement the HashState which can cause confusion.  Where'as in pedersen hashing two elements is simply done as follows:
```
PedersenTrait::new(0).update(1).finalize()
```
Hashing two values in Poseidon with the similar pattern is wrong:
```
PoseidonTrait::new().update(0).update(1).finalize();
```
This can cause errors (for example here in Alexandria's merkle tree impl https://github.com/keep-starknet-strange/alexandria/blob/main/src/merkle_tree/src/merkle_tree.cairo#L69). Hashing one or two values using Poseidon uses the formula described [here](https://docs.starknet.io/documentation/architecture_and_concepts/Cryptography/hash-functions/)).
This is because under the hood 'finalize' actually incurs another round of hashing (whereas this is not the case for Pedersen) which may be misleading.

This is why I propose two new methods that can help with this issue (with the relevant tests) .

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5096)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5096)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Leonard-Pat)

___
*[`corelib/src/poseidon.cairo` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5096#-Nr1Gznq8pCb8SuIS0m-:-Nr1Gznq8pCb8SuIS0m0:b2mljyn) ([raw file](https://github.com/starkware-libs/cairo/blob/5e6e9fc19ec381903ba473c46e2c8c99a6542d7a/corelib/src/poseidon.cairo#L59)):*
> ```Cairo
> }
> 
> pub fn poseidon_hash_one_element(value: felt252) -> felt252 {
> ```

is this a part of the usual usage of poseidon?
it generally seems to me that this shouldn't actually be part of the corelib.

**Comment by Leonard-Pat** [comment]
> > _[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5096)_ status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Leonard-Pat)
> 
> _[`corelib/src/poseidon.cairo` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5096#-Nr1Gznq8pCb8SuIS0m-:-Nr1Gznq8pCb8SuIS0m0:b2mljyn) ([raw file](https://github.com/starkware-libs/cairo/blob/5e6e9fc19ec381903ba473c46e2c8c99a6542d7a/corelib/src/poseidon.cairo#L59)):_
> 
> > ```cairo
> > }
> > 
> > pub fn poseidon_hash_one_element(value: felt252) -> felt252 {
> > ```
> 
> is this a part of the usual usage of poseidon? it generally seems to me that this shouldn't actually be part of the corelib.

I think so - its more to mimic the starkcurve TS lib (https://github.com/paulmillr/scure-starknet/blob/b9e81d7345ecdd088d0f263ceaed7d9e0b9290cb/index.ts#L362) used by sn.js

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5096)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Leonard-Pat)

___
*[`corelib/src/poseidon.cairo` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5096#-Nr1Gznq8pCb8SuIS0m-:-Nr1Tb3-9zDZVaQ6H7Lg:b-2luz7x) ([raw file](https://github.com/starkware-libs/cairo/blob/5e6e9fc19ec381903ba473c46e2c8c99a6542d7a/corelib/src/poseidon.cairo#L59)):*
<details><summary><i>Previously, Leonard-Pat wrote…</i></summary><blockquote>

I think so - its more to mimic the starkcurve TS lib (https://github.com/paulmillr/scure-starknet/blob/b9e81d7345ecdd088d0f263ceaed7d9e0b9290cb/index.ts#L362) used by sn.js  
</blockquote></details>

in any case - the solution should probably be creating a state correctly (using another function - not `new`) - instead of using the function directly.

**Comment by Leonard-Pat** [comment]
> > _[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5096)_ status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Leonard-Pat)
> 
> _[`corelib/src/poseidon.cairo` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5096#-Nr1Gznq8pCb8SuIS0m-:-Nr1Tb3-9zDZVaQ6H7Lg:b-2luz7x) ([raw file](https://github.com/starkware-libs/cairo/blob/5e6e9fc19ec381903ba473c46e2c8c99a6542d7a/corelib/src/poseidon.cairo#L59)):_
> Previously, Leonard-Pat wrote…
> 
> in any case - the solution should probably be creating a state correctly (using another function - not `new`) - instead of using the function directly.

I've updated to be a trait - however do you think its better if theres a another hash struct

**Comment by enitrat** [comment]
Was taking a glance and it reminded me of this issue that I had when writing the Hash Chapter in the Cairo book, in which we introduce how to use the corelib hash functions using the Hash trait (see https://github.com/cairo-book/cairo-book/pull/496).


> The confusion comes from the fact that Pedersen is instantiated with a base state while poseidon is not.
So if you want to simply hash the struct members together you would need to instantiated the state with the first member of the struct, and then update it with the remaining members, and then finalize. Whereas for poseidon you can simply update the default empty state with the struct to hash.

> I'll verify later if there isn't a more elegant way of just hashing a structs fields together - and if there isnt one we should ask for it

One problem is that Pedersen is always introduced with a base state, unlike Poseidon, and the hashes calculated with, for example starknet-js, often don't match the ones in Cairo because of these properties. 

I'm sure there's a better design to design this hashing API to avoid these problems

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5096)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Leonard-Pat)

___
*[`corelib/src/poseidon.cairo` line 70 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5096#-Nwhb9k-4tlaKTdZDVuj:-Nwhb9k-4tlaKTdZDVuk:bv8i9tv) ([raw file](https://github.com/starkware-libs/cairo/blob/3561ffdd3109edf516b5349bc635becf52d6ebb8/corelib/src/poseidon.cairo#L70)):*
> ```Cairo
>         r
>     }
> }
> ```

and doc all.



_Suggestion:_
```Cairo
trait HashValueHelper<V> {
    fn hash_value(v: V) -> felt252;
}
impl SingleHashValueHelper<V, +Into<V, felt252>> of HashValueHelper<V> {
    fn hash_value(v: V) -> felt252 {
        let (r, _, _) = hades_permutation(v.into(), 0, 1);
        r
    }
}
impl PairHashValueHelper<V0, V1, +Into<V0, felt252>, +Into<V1, felt252>> of HashValueHelper<(V0, V1)> {
    fn hash_value((v0, v1): (V0, V1)) -> felt252 {
        let (r, _, _) = hades_permutation(v0.into(), v1.into(), 2);
        r
    }
}

pub fn hash_value<V, +HashValueHelper<V>>(v: V) -> felt252 {
    HashValueHelper::hash_value(v)
}
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5096)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @Leonard-Pat)

___
*[`corelib/src/poseidon.cairo` line 59 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5096#-NwiasTIBjLs64mmkeLm:-NwiasTIBjLs64mmkeLn:b-of4zvo) ([raw file](https://github.com/starkware-libs/cairo/blob/b236ca59f0308d141ce368349ff022a6f6677868/corelib/src/poseidon.cairo#L59)):*
> ```Cairo
> }
> 
> trait HashValueHelper<V> {
> ```

doc these as well.
___
*[`corelib/src/sha256.cairo` line 36 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5096#-Nwi_Z_wD44QddjZ0cjT:-Nwi_Z_wD44QddjZ0cjU:b-hay66z) ([raw file](https://github.com/starkware-libs/cairo/blob/b236ca59f0308d141ce368349ff022a6f6677868/corelib/src/sha256.cairo#L36)):*
> ```Cairo
> 
>     while ind != arr
>         .len() {
> ```

revert.
___
*[`corelib/src/test/sha256_test.cairo` line 17 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5096#-Nwi_aKB4q6L3PZQYV7d:-Nwi_aKB4q6L3PZQYV7e:b-l6hdjr) ([raw file](https://github.com/starkware-libs/cairo/blob/b236ca59f0308d141ce368349ff022a6f6677868/corelib/src/test/sha256_test.cairo#L17)):*
> ```Cairo
>     assert_eq!(a, 0x61be55a8);
>     let [
>         a, _, _, _, _, _, _, _,
> ```

revert

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/poseidon.cairo` line 86 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5096#-Nwj4naWBFCaN8DvbL2A:-Nwj4naX7e-jshtIl7Rq:bre0sa3) ([raw file](https://github.com/starkware-libs/cairo/blob/702b20a8011b5d2ce4add339b81e2e13506e6de1/corelib/src/poseidon.cairo#L86)):*
> ```Cairo
> 
> /// Computes the Poseidon hash of either a single value or a pair of values.
> pub fn hash_value<V, +HashValueHelper<V>>(v: V) -> felt252 {
> ```

What's the advantage of making this generic? instead of declaring two functions?



_Code quote:_
```Cairo
hash_value<V, +HashValueHelper<V>>(v: V)
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5096)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @Leonard-Pat)

___
*[`corelib/src/poseidon.cairo` line 86 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5096#-Nwj4naWBFCaN8DvbL2A:-NwjA8w70wOpZGoe-5wF:b-1oxgq2) ([raw file](https://github.com/starkware-libs/cairo/blob/702b20a8011b5d2ce4add339b81e2e13506e6de1/corelib/src/poseidon.cairo#L86)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

What's the advantage of making this generic? instead of declaring two functions?
</blockquote></details>

the two functions are less clear IMO - the aim of this as a function fits more when saying "this is the hash definition of a full value" - moving the hash over span to here as well make more sense to me.

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/poseidon.cairo` line 86 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5096#-Nwj4naWBFCaN8DvbL2A:-NwjB7eU8-zH-XRFKwky:b-dliy56) ([raw file](https://github.com/starkware-libs/cairo/blob/702b20a8011b5d2ce4add339b81e2e13506e6de1/corelib/src/poseidon.cairo#L86)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the two functions are less clear IMO - the aim of this as a function fits more when saying "this is the hash definition of a full value" - moving the hash over span to here as well make more sense to me.
</blockquote></details>

But those are different functions.

you have

posiedon_hash_single
posideion_hash
and 
poseidon_hash_many

and I'm not sure we want to mix them.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5096)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @Leonard-Pat)

___
*[`corelib/src/poseidon.cairo` line 86 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5096#-Nwj4naWBFCaN8DvbL2A:-NwjDKRg1vUr2Bt5pCXf:b-26gnfn) ([raw file](https://github.com/starkware-libs/cairo/blob/702b20a8011b5d2ce4add339b81e2e13506e6de1/corelib/src/poseidon.cairo#L86)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

But those are different functions.

you have

posiedon_hash_single
posideion_hash
and 
poseidon_hash_many

and I'm not sure we want to mix them.
</blockquote></details>

all of these are different functions - but are only used for the cases where you wish to get a single final value, and not advancing a hash state.

**Review by orizi — COMMENTED** [review]
is the merkle tree the only relevant use case?
if so - it seems merkle tree libraries should take care of it themselves - instead of including this in the languages core.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5096#-:-NwtEK9q6kTLD_XoRQXZ:b2pbgev)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @Leonard-Pat)

**Comment by Leonard-Pat** [comment]
I think they're are lot of use cases for hashing a single / two values together - we've used both throughout our account (at Argent)

**Comment by Leonard-Pat** [comment]
> is the merkle tree the only relevant use case? if so - it seems merkle tree libraries should take care of it themselves - instead of including this in the languages core.
> 
> > _[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5096#-:-NwtEK9q6kTLD_XoRQXZ:b2pbgev)_ status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @Leonard-Pat)

I think they're are lot of use cases for hashing a single / two values together - we've used both throughout our account (at Argent)

**Pull request closed without merging**
