### PR TITLE
Move validation to parser.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4295)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-parser/src/parser.rs` line 1906 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4295#-NhRoPCBAGxVJ8amOKSf:-NhRoPCBAGxVJ8amOKSg:b2ux6hn) ([raw file](https://github.com/starkware-libs/cairo/blob/70f1272415fade6b15603aa19537d3617788235a/crates/cairo-lang-parser/src/parser.rs#L1906)):*
> ```XML
>         let span = TextSpan { start: self.offset, end: self.offset.add_width(self.current_width) };
> 
>         validate_literal_number(self.diagnostics, text, span, self.file_id);
> ```

Does this make sense?

Is there a simple way to get the text or syntax_node from TerminalLiteralNumberGreen?



_Code quote:_
```XML
        let text = self.peek().text.clone();
        let span = TextSpan { start: self.offset, end: self.offset.add_width(self.current_width) };

        validate_literal_number(self.diagnostics, text, span, self.file_id);
```

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4295)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-parser/src/lib.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4295#-NhS8dFJ6vz3gX-DPcbi:-NhS8dFJ6vz3gX-DPcbj:buttl1r) ([raw file](https://github.com/starkware-libs/cairo/blob/70f1272415fade6b15603aa19537d3617788235a/crates/cairo-lang-parser/src/lib.rs#L15)):*
> ```XML
> pub mod recovery;
> pub mod utils;
> #[allow(dead_code)]
> ```

is this required?
___
*[`crates/cairo-lang-parser/src/parser.rs` line 1902 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4295#-NhS8NU5BcwT61lhUGRt:-NhS8NU5BcwT61lhUGRu:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/70f1272415fade6b15603aa19537d3617788235a/crates/cairo-lang-parser/src/parser.rs#L1902)):*
> ```XML
>     }
> 
>     fn try_terminal_literal_number(&mut self) -> TerminalLiteralNumberGreen {
> ```

doc
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/literal` line 140 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4295#-NhS8rlt6cqLJTsftChJ:-NhS8rlt6cqLJTsftChK:bso6t16) ([raw file](https://github.com/starkware-libs/cairo/blob/70f1272415fade6b15603aa19537d3617788235a/crates/cairo-lang-parser/src/parser_test_data/partial_trees/literal#L140)):*
> ```
>  --> dummy_file.cairo:3:21
>     let illegal_bin = 0b2;
>                     ^^
> ```

fix span

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4295)* status: all files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-parser/src/validation.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4295#-NhW2oEV7rsVcAb_MIlo:-NhW2oEV7rsVcAb_MIlp:bk63wv4) ([raw file](https://github.com/starkware-libs/cairo/blob/975bad1b305121db06cbe74a5642124b49272ae7/crates/cairo-lang-parser/src/validation.rs#L25)):*
> ```XML
> /// 1. Is parsable according to its radix.
> /// 2. Has properly formatted suffix.
> pub fn validate_literal_number(
> ```

Are the other `pub`s required?

**Review by mkaput — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4295)* status: all files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-parser/src/db.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4295#-Nh_d8iK0_dhud5B8DDy:-Nh_d8iLEtBFE0ULtpdD:b2nhkus) ([raw file](https://github.com/starkware-libs/cairo/blob/975bad1b305121db06cbe74a5642124b49272ae7/crates/cairo-lang-parser/src/db.rs#L49)):*
> ```XML
>             }
>         };
>         node
> ```

Nit



_Suggestion:_
```XML
        match file_id.kind(db.upcast()) {
            FileKind::Module => {
                Parser::parse_file(db.upcast(), &mut diagnostics, file_id, &s).as_syntax_node()
            }
            FileKind::Expr => {
                Parser::parse_file_expr(db.upcast(), &mut diagnostics, file_id, &s).as_syntax_node()
            }
        }
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4295)* status: 2 of 7 files reviewed, 5 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-parser/src/db.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4295#-Nh_d8iK0_dhud5B8DDy:-Nh_qryoC3glZ-59YOYX:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/975bad1b305121db06cbe74a5642124b49272ae7/crates/cairo-lang-parser/src/db.rs#L49)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Nit
</blockquote></details>

done
___
*[`crates/cairo-lang-parser/src/validation.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4295#-NhW2oEV7rsVcAb_MIlo:-Nh_qyoI8uAB5qQ85kY1:brjfz43) ([raw file](https://github.com/starkware-libs/cairo/blob/975bad1b305121db06cbe74a5642124b49272ae7/crates/cairo-lang-parser/src/validation.rs#L25)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Are the other `pub`s required?
</blockquote></details>

Removed the unnecessary ones.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/literal` line 140 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4295#-NhS8rlt6cqLJTsftChJ:-Nh_r3eg-yjodtWJPi8R:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/70f1272415fade6b15603aa19537d3617788235a/crates/cairo-lang-parser/src/parser_test_data/partial_trees/literal#L140)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix span
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/lib.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4295#-NhS8dFJ6vz3gX-DPcbi:-Nh_r4C55h2QBb_4CJnr:bvth56w) ([raw file](https://github.com/starkware-libs/cairo/blob/70f1272415fade6b15603aa19537d3617788235a/crates/cairo-lang-parser/src/lib.rs#L15)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is this required?
</blockquote></details>

reverted

**Review by orizi — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4295)* status: all files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @mkaput)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1911 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4295#-Nh_sfAG5OA4HEsRg7vP:-Nh_sfAG5OA4HEsRg7vQ:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/8ca270e55fc4c3b695d2e439491c7d2312d37a46/crates/cairo-lang-parser/src/parser.rs#L1911)):*
> ```XML
>     }
> 
>     fn take_terminal_short_string(&mut self) -> TerminalShortStringGreen {
> ```

doc
___
*[`crates/cairo-lang-parser/src/parser.rs` line 1920 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4295#-Nh_sfrwEYRYMz9Ix5qs:-Nh_sfrwEYRYMz9Ix5qt:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/8ca270e55fc4c3b695d2e439491c7d2312d37a46/crates/cairo-lang-parser/src/parser.rs#L1920)):*
> ```XML
>     }
> 
>     fn take_terminal_string(&mut self) -> TerminalStringGreen {
> ```

doc

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4295#-:-NhaM6je4lrlNx1kNuwC:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)

**Pull request merged**
