### PR TITLE
dev: implement Zero for u384

### PR DESCRIPTION
**Pull request by enitrat**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6329)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6329)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @enitrat)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6329#-O5n9tYdBKwYRdlcVHZW:-O5n9tYdBKwYRdlcVHZX:b629rvh) (no related file):*
add a test as well.

___

**Review by enitrat — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6329)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6329#-O5n9tYdBKwYRdlcVHZW:-O5w4nUr5b0zZeQcPGwA:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add a test as well.
</blockquote></details>

Done.

___

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6329#-:-O5w5xPQ1r88jnOFZMTO:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @enitrat)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6329)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @enitrat)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6329#-O5w646G6HHo2LSZ3-qK:-O5w646HBoUgLRteppJ2:b-gajptm) (no related file):*
@ilyalesokhin-starkware for 2nd eye.

___

**Pull request merged**
