### PR TITLE
Added libfunc for u256_inv_mod_n.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3603)

### CODE REVIEW

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3603)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3603#-N_2q1kV50_dCTzzLMDm:-N_2q1kW49Df-kHrsmLh:bqnno6q) (no related file):*
Change PR title: `div` -> `inv`.

___

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3603)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3603#-N_2q1kV50_dCTzzLMDm:-N_2t1_P3LVSt_uwBOvl:b-896fix) (no related file):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Change PR title: `div` -> `inv`.
</blockquote></details>

Done.

___

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3603)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3603#-Naf9SI5AaAT9PYZTHby:-Naf9SI5AaAT9PYZTHbz:b-tg9txf) (no related file):*
Shouldn't the target branch be `sierra-minor-update`?

___

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3603)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`corelib/src/test/math_test.cairo` line 98 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3603#-NcHa-sEBP5Lsf1Z29oP:-NcHa-sEBP5Lsf1Z29oQ:b-fpc4dh) ([raw file](https://github.com/starkware-libs/cairo/blob/6a42e6fa2cb76369be53b0798d319b1c85fda549/corelib/src/test/math_test.cairo#L98)):*
> ```Cairo
>         .unwrap();
>     assert(q == 0, '0 / 3 != 0 (13)');
>     assert(
> ```

Missing tests (e.g., random 256-bit numbers)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 2 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3603)* status: 2 of 10 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3603)* status: 4 of 10 files reviewed, 3 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`corelib/src/test/math_test.cairo` line 98 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3603#-NcHa-sEBP5Lsf1Z29oP:-NfeR08Y7yodSyXK11aE:bo7bvj9) ([raw file](https://github.com/starkware-libs/cairo/blob/6a42e6fa2cb76369be53b0798d319b1c85fda549/corelib/src/test/math_test.cairo#L98)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still missing.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3603)* status: 4 of 10 files reviewed, 3 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

___
*[`corelib/src/test/math_test.cairo` line 98 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3603#-NcHa-sEBP5Lsf1Z29oP:-NfeTs5R1i2hI7riWdVH:bxf3sc3) ([raw file](https://github.com/starkware-libs/cairo/blob/6a42e6fa2cb76369be53b0798d319b1c85fda549/corelib/src/test/math_test.cairo#L98)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Still missing.
</blockquote></details>

somehow got lost - readded.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3603)* status: 3 of 10 files reviewed, 5 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`corelib/src/math.cairo` line 81 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3603#-NfkjgO9Bx3NbtAQdI9c:-NfkjgO9Bx3NbtAQdI9d:b-r1dun5) ([raw file](https://github.com/starkware-libs/cairo/blob/f281153794b17d58036d0ed2f54da12d4c5ac84a/corelib/src/math.cairo#L81)):*
> ```Cairo
> 
> /// Returns `1 / b (mod n)`, or None if `b` is not invertible modulo `n`.
> /// Additionally returns several `U128MulGuarantee`s that are required for validating the calculation.
> ```

Line too long.
___
*[`corelib/src/math.cairo` line 100 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3603#-Nfkk1pv1E-tSv8AqTXl:-Nfkk1pv1E-tSv8AqTXm:bamk7h2) ([raw file](https://github.com/starkware-libs/cairo/blob/f281153794b17d58036d0ed2f54da12d4c5ac84a/corelib/src/math.cairo#L100)):*
> ```Cairo
> 
> /// Returns `a / b (mod n)`, or None if `b` is not invertible modulo `n`.
> fn u256_div_mod_n(a: u256, b: NonZero<u256>, n: NonZero<u256>) -> Option<u256> {
> ```

Can you split `u256_inv_mod_n` out of this function?

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3603)* status: 3 of 10 files reviewed, 6 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`corelib/src/test/math_test.cairo` line 2 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3603#-Nfkl0Qu7XYAdmpSi1GZ:-Nfkl0Qu7XYAdmpSi1G_:b-fo9tum) ([raw file](https://github.com/starkware-libs/cairo/blob/f281153794b17d58036d0ed2f54da12d4c5ac84a/corelib/src/test/math_test.cairo#L2)):*
> ```Cairo
> /// Helper for making a non-zero value.
> fn nz<N, impl TryIntoNonZeroN: TryInto<N, NonZero<N>>>(n: N) -> NonZero<N> {
> ```

Use `+` syntax.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3603)* status: 6 of 10 files reviewed, 6 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

___
*[`corelib/src/math.cairo` line 81 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3603#-NfkjgO9Bx3NbtAQdI9c:-Nfl2nkaBR8CDeHXvxmh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f281153794b17d58036d0ed2f54da12d4c5ac84a/corelib/src/math.cairo#L81)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Line too long.
</blockquote></details>

Done.
___
*[`corelib/src/math.cairo` line 100 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3603#-Nfkk1pv1E-tSv8AqTXl:-Nfl5gJnAnyE-pY9NAbE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f281153794b17d58036d0ed2f54da12d4c5ac84a/corelib/src/math.cairo#L100)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Can you split `u256_inv_mod_n` out of this function?
</blockquote></details>

Done.
___
*[`corelib/src/test/math_test.cairo` line 2 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3603#-Nfkl0Qu7XYAdmpSi1GZ:-Nfl35KuBUbw-R06rv79:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f281153794b17d58036d0ed2f54da12d4c5ac84a/corelib/src/test/math_test.cairo#L2)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Use `+` syntax.
</blockquote></details>

Done.

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3603)* status: 9 of 10 files reviewed, 10 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1952 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3603#-NfoLMqo6u1vK4Bp2QA7:-NfoLMqo6u1vK4Bp2QA8:bu3g178) ([raw file](https://github.com/starkware-libs/cairo/blob/fe29e21552a73a8d411e0ed84b955c86852581ea/crates/cairo-lang-runner/src/casm_run/mod.rs#L1952)):*
> ```XML
>             } else {
>                 r %= &n;
>                 if r.is_negative() {
> ```

I guess this one (unlike python) is necessary?

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3603)* status: all files reviewed, 10 unresolved discussions (waiting on @orizi and @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3603)* status: 6 of 10 files reviewed, 8 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

___
*[`corelib/src/math.cairo` line 100 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3603#-NfoGjAZ55ewdO1h4Son:-NfocmOk8naqjQ58xo_r:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fe29e21552a73a8d411e0ed84b955c86852581ea/corelib/src/math.cairo#L100)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`corelib/src/test/math_test.cairo` line 65 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3603#-NfoHLQuD3_WacvmECIc:-NfoXdNXB8qAuGqrAJ14:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fe29e21552a73a8d411e0ed84b955c86852581ea/corelib/src/test/math_test.cairo#L65)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Add:
```
assert(math::u256_div_mod_n(5, 4, nz(6)).is_none(), '4 / 3 == None (6)');
```
</blockquote></details>

Done.
___
*[`corelib/src/test/math_test.cairo` line 101 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3603#-NfoHqsy32N4a-8BCpUE:-NfoauRUA-mAoc0ojhbK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fe29e21552a73a8d411e0ed84b955c86852581ea/corelib/src/test/math_test.cairo#L101)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Add one with a large **odd** gcd (`>2**128`)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 240 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3603#-NfoIHwD9HDkM1lmVOn6:-NfobdTqEOdX-gvBthlw:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fe29e21552a73a8d411e0ed84b955c86852581ea/crates/cairo-lang-casm/src/hints/mod.rs#L240)):*
> ```XML
>     /// `g * t = n`
>     ///
>     /// In all cases - `name`0 is the least significant limb.
> ```

Done.
___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 728 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3603#-NfoJ_Js6UdSBTxA5o_1:-Nfobs4S0ZO0bj32PHGr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fe29e21552a73a8d411e0ed84b955c86852581ea/crates/cairo-lang-casm/src/hints/mod.rs#L728)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Remove spaces.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 730 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3603#-NfoKHMwCBU5udZDJwmn:-NfobrBL2TOfx3wFhnlP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fe29e21552a73a8d411e0ed84b955c86852581ea/crates/cairo-lang-casm/src/hints/mod.rs#L730)):*
> ```XML
>     
>                         b = {b0} + {b1} * 2**128
>                         n = {n0} + {n1} * 2**128
> ```

Done.
___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 746 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3603#-NfoK-Mz8NwVDxFQI281:-NfocO657GQOMgptCGAH:bu6ynqi) ([raw file](https://github.com/starkware-libs/cairo/blob/fe29e21552a73a8d411e0ed84b955c86852581ea/crates/cairo-lang-casm/src/hints/mod.rs#L746)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

This can't happen after the `%`, right?
</blockquote></details>

correct - fixed as this is python.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1952 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3603#-NfoLMqo6u1vK4Bp2QA7:-Nfoc7GLA7OXBjud_x5c:bnktyzy) ([raw file](https://github.com/starkware-libs/cairo/blob/fe29e21552a73a8d411e0ed84b955c86852581ea/crates/cairo-lang-runner/src/casm_run/mod.rs#L1952)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

I guess this one (unlike python) is necessary?
</blockquote></details>

we have no promise from extended gcd to get a negative `r` - so this is required here (as rust is like c++ AFAIK)

**Review by liorgold2 — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3603)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`corelib/src/test/math_test.cairo` line 101 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3603#-NfoHqsy32N4a-8BCpUE:-NfpeV4H6gKy92A9BF21:b-hvyd05) ([raw file](https://github.com/starkware-libs/cairo/blob/fe29e21552a73a8d411e0ed84b955c86852581ea/corelib/src/test/math_test.cairo#L101)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Add another test with b==n==256-bit odd number. This will test the branch where g1 is large.

**Review by liorgold2 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3603)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3603)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @spapinistarkware)

___
*[`corelib/src/test/math_test.cairo` line 101 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3603#-NfoHqsy32N4a-8BCpUE:-Nfpz8tm2Owpl8ojXtvc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fe29e21552a73a8d411e0ed84b955c86852581ea/corelib/src/test/math_test.cairo#L101)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Add another test with b==n==256-bit odd number. This will test the branch where g1 is large.
</blockquote></details>

Done.

**Review by liorgold2 — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3603)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3603#-:-NfuJucT9ZB-yzaKa4pb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
