### PR TITLE
Add scrub units optimization.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5142)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5142)* status: 0 of 58 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/profiling_test_data/profiling` line 299 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5142#-NrZlqau-QdnRPivp6C4:-NrZlqau-QdnRPivp6C5:b-di1dlh) ([raw file](https://github.com/starkware-libs/cairo/blob/70727210a9f1e0859d4ef96865f08cb8f53e9023/crates/cairo-lang-runner/src/profiling_test_data/profiling#L299)):*
> ```
>   function test::main: 1
> Weight by Cairo function:
>   function unknown: 1
> ```

according to @gilbens-starkware we need to add locations to `return` in the lowering to fix this.



_Code quote:_
```
function unknown: 1
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 27 of 58 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5142)* status: 27 of 58 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5142#-NrZvkz--XJzPZ_XEajd:-NrZvkz0BSQHwVgUSk3o:b-e8phvx) (no related file):*
ideas why sierra code expanded in some instances?

___
___
*[`crates/cairo-lang-lowering/src/db.rs` line 355 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5142#-NrZtpQ0-lJKhDVgTKGo:-NrZtpQ0-lJKhDVgTKGp:b-l6hdjr) ([raw file](https://github.com/starkware-libs/cairo/blob/70727210a9f1e0859d4ef96865f08cb8f53e9023/crates/cairo-lang-lowering/src/db.rs#L355)):*
> ```XML
>         (*db.function_with_body_lowering(function.function_with_body_id(db))?).clone();
>     concretize_lowered(db, &mut lowered, &function.substitution(semantic_db)?)?;
> ```

revert
___
*[`crates/cairo-lang-lowering/src/inline/test_data/inline` line 431 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5142#-NrZu8Cr3DPNTrfdkE8y:-NrZu8Cr3DPNTrfdkE8z:b-n5v5kw) ([raw file](https://github.com/starkware-libs/cairo/blob/70727210a9f1e0859d4ef96865f08cb8f53e9023/crates/cairo-lang-lowering/src/inline/test_data/inline#L431)):*
> ```
>   (v3: core::array::Array::<core::felt252>) <- core::array::ArrayImpl::<core::felt252>::append(v0, v1)
>   (v2: ()) <- struct_construct()
>   () <- struct_destructure(v2)
> ```

why does this appear all around?



_Code quote:_
```
  (v2: ()) <- struct_construct()
  () <- struct_destructure(v2)
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/inline/test_data/inline` line 431 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5142#-NrZu8Cr3DPNTrfdkE8y:-Nr_4KZwAWcD5dhHosvX:b-8hfmqk) ([raw file](https://github.com/starkware-libs/cairo/blob/70727210a9f1e0859d4ef96865f08cb8f53e9023/crates/cairo-lang-lowering/src/inline/test_data/inline#L431)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why does this appear all around?
</blockquote></details>

Thats how scrub units works, it is cleaned up in cancel_ops or split struct if v2 is unused.

**Comment by ilyalesokhin-starkware** [comment]
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

ideas why sierra code expanded in some instances?
</blockquote></details>

Fewer things are inlined because of `SimpleInlineWeight`

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5142)* status: 27 of 58 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5142#-NrZvkz--XJzPZ_XEajd:-Nr_9ZwZ6r_Eh_FYaFEV:b-g88v56) (no related file):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Fewer things are inlined because of `SimpleInlineWeight`
</blockquote></details>

can you add a leading PR that enhances the heuristic?

___

**Review by orizi — COMMENTED** [review]
> Reviewed 4 of 67 files at r2, 27 of 27 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5142)* status: 44 of 94 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 14 of 58 files at r1, 36 of 67 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5142)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5142#-:-Nrplf2O5axwlfiG3w9P:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5142)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Pull request merged**
