### PR TITLE
Allow applying StarkNet to `RootDatabaseBuilder`

### PR DESCRIPTION
**Pull request by mkaput**
commit-id:6af6ca78

---

**Stack**:
- #1993
- #1992
- #1991
- #1989
- #1988 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by orizi — DISMISSED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1988#-:-NN5ia3M9e-CxsGb3tgk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1988)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)

___
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1988#-NN5j8jyBZqgxrdvdHuy:-NN5j8jyBZqgxrdvdHuz:by4s89r) ([raw file](https://github.com/starkware-libs/cairo/blob/7a315186164105b5a253eb97d7aabfbe31e3b948/crates/cairo-lang-starknet/src/contract_class.rs#L68)):*
> ```XML
> /// If `replace_ids` is true, replaces sierra ids with human-readable ones.
> pub fn compile_path(path: &Path, replace_ids: bool) -> anyhow::Result<ContractClass> {
>     let mut db_val = get_starknet_database();
> ```

why not keep that function?



_Code quote:_
```XML
get_starknet_database();
```

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1988)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1988#-NN5j8jyBZqgxrdvdHuy:-NN5l2WE9tOpM7Cq6_Dj:b3wb9ql) ([raw file](https://github.com/starkware-libs/cairo/blob/7a315186164105b5a253eb97d7aabfbe31e3b948/crates/cairo-lang-starknet/src/contract_class.rs#L68)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why not keep that function?
</blockquote></details>

It's just a shortcut for the builder, which hides enforcement of dev_corelib. I didn't see any benefit for public users for this function, and it wasn't used such a lot internally to justify it presence IMHO.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1988#-NN6BBpcDkmeBxFjlqZY:-NN6BBpcDkmeBxFjlqZZ:b-rz71bb) ([raw file](https://github.com/starkware-libs/cairo/blob/fd6bc4ca2c6e948f7c9420adbccd0d5e9120e8e1/crates/cairo-lang-starknet/src/contract_class.rs#L69)):*
> ```XML
> pub fn compile_path(path: &Path, replace_ids: bool) -> Result<ContractClass> {
>     let mut db_val = {
>         let mut b = RootDatabase::builder();
> ```

this code is duplicated



_Code quote:_
```XML
        let mut b = RootDatabase::builder();
        b.with_dev_corelib().unwrap();
        b.with_starknet();
        b.build()
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1988)* status: all files reviewed, 2 unresolved discussions (waiting on @mkaput)

___
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1988#-NN5j8jyBZqgxrdvdHuy:-NN6BJoo9aO0L3W6Owpf:b-q4zsif) ([raw file](https://github.com/starkware-libs/cairo/blob/74b0662e3e6dfb7a7e06b7bb18d2553e6d124fd4/crates/cairo-lang-starknet/src/contract_class.rs#L68)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

It's just a shortcut for the builder, which hides enforcement of dev_corelib. I didn't see any benefit for public users for this function, and it wasn't used such a lot internally to justify it presence IMHO.
</blockquote></details>

you replaced it with duplicated code.

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1988)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1988#-NN5j8jyBZqgxrdvdHuy:-NN6BWp9EJbY3KyMJiru:b-eetr5z) ([raw file](https://github.com/starkware-libs/cairo/blob/74b0662e3e6dfb7a7e06b7bb18d2553e6d124fd4/crates/cairo-lang-starknet/src/contract_class.rs#L68)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

you replaced it with duplicated code.
</blockquote></details>

I will defend this duplication: it makes it explicit that `core` is pulled via dev mode.

I think it would be more pleasant if one could write a one-liner `RootDatabase::builder().with_dev_corelib().unwrap().with_starknet().build()`, but that's a topic for separate PR because this needs redoing the builder internals (I have an idea now how to achieve this). Would such one-liner work?

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1988)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1988#-NN6BBpcDkmeBxFjlqZY:-NN6RhS6BjE55mvB1Mhz:b-q6ymn1) ([raw file](https://github.com/starkware-libs/cairo/blob/2698dae57c5093b35ff984cddc4c71584767ea9e/crates/cairo-lang-starknet/src/contract_class.rs#L69)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

this code is duplicated
</blockquote></details>

See my previous reply

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1988#-:-NN6Tm1k8LwgBLJf2G16:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)

___
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1988#-NN5j8jyBZqgxrdvdHuy:-NN6TLJ65GxOcbN4HjIA:b57dg3i) ([raw file](https://github.com/starkware-libs/cairo/blob/b311fe5de77daf965fffe2c377eebecc24c6fef9/crates/cairo-lang-starknet/src/contract_class.rs#L68)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I will defend this duplication: it makes it explicit that `core` is pulled via dev mode.

I think it would be more pleasant if one could write a one-liner `RootDatabase::builder().with_dev_corelib().unwrap().with_starknet().build()`, but that's a topic for separate PR because this needs redoing the builder internals (I have an idea now how to achieve this). Would such one-liner work? 
</blockquote></details>

I don't understand the issue with the corelib.

I think it is convenient to have  get_starknet_database() for testing, but I see that it currently has one user in testing.
So I'm ok with this PR.

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1988)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1988#-NN5j8jyBZqgxrdvdHuy:-NN6c9g23q3L6uU8bAC4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b311fe5de77daf965fffe2c377eebecc24c6fef9/crates/cairo-lang-starknet/src/contract_class.rs#L68)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't understand the issue with the corelib.

I think it is convenient to have  get_starknet_database() for testing, but I see that it currently has one user in testing.
So I'm ok with this PR.

</blockquote></details>

Done.

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1988)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1988#-NN5j8jyBZqgxrdvdHuy:-NN6dxfY8kVnYpeqlg3N:b-9eibbu) ([raw file](https://github.com/starkware-libs/cairo/blob/8eea44dad3230681f3fc7c3464da66651fec3ac0/crates/cairo-lang-starknet/src/contract_class.rs#L68)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I find `with_dev_corelib` not to be usable by crate users outside this repository, and I think it's important to be explicit when it is used. It's magic imposes particular project structure and makes binaries unportable.

The usage of builder is basically the same thing as using optional kwargs in Python. I don't see any benefit of having a special function which just provides some parameters.

**Review by mkaput — COMMENTED** [review]
> Dismissed @ilyalesokhin-starkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1988)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Pull request merged**
