### PR TITLE
added if-let expression in the parser

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4944)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4944)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1599 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4944#-NpFQlSi4mu1NNTj9JlP:-NpFQlSi4mu1NNTj9JlQ:b-4b1s1v) ([raw file](https://github.com/starkware-libs/cairo/blob/2346e46202de7acacd232d1b941f9935f37c829c/crates/cairo-lang-parser/src/parser.rs#L1599)):*
> ```XML
> 
>     /// Assumes the current token is `If`.
>     fn expect_if(&mut self) -> TryParseResult<BlockOrIfGreen> {
> ```

`TryParseResult` are generally for `try_` style functions.
why diverge?



_Code quote:_
```XML
    fn expect_if(&mut self) -> TryParseResult<BlockOrIfGreen> {
```
___
*[`crates/cairo-lang-parser/src/parser.rs` line 1606 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4944#-NpFQIgb18GKJwf1y8Tl:-NpFQIgb18GKJwf1y8Tm:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2346e46202de7acacd232d1b941f9935f37c829c/crates/cairo-lang-parser/src/parser.rs#L1606)):*
> ```XML
>             Ok(BlockOrIfGreen::from(self.expect_if_expr(if_kw)?))
>         }
>     }
> ```





_Suggestion:_
```XML
    fn expect_if(&mut self) -> TryParseResult<BlockOrIfGreen> {
        let if_kw = self.take::<TerminalIf>();
        if self.peek().kind == SyntaxKind::TerminalLet {
            Ok(self.expect_if_let_expr(if_kw)?.into())
        } else {
            Ok(self.expect_if_expr(if_kw)?.into())
        }
    }
```
___
*[`crates/cairo-lang-parser/src/parser.rs` line 1646 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4944#-NpFQ6GOEmrtzMvOrA39:-NpFQ6GP4tIDAHc3R3Op:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/2346e46202de7acacd232d1b941f9935f37c829c/crates/cairo-lang-parser/src/parser.rs#L1646)):*
> ```XML
>     }
> 
>     fn parse_optional_else_clause(&mut self) -> TryParseResult<OptionElseClauseGreen> {
> ```

doc

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4944)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1599 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4944#-NpFQlSi4mu1NNTj9JlP:-NpFSLM9036Pf8uXURBu:b-v96xi7) ([raw file](https://github.com/starkware-libs/cairo/blob/2346e46202de7acacd232d1b941f9935f37c829c/crates/cairo-lang-parser/src/parser.rs#L1599)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

`TryParseResult` are generally for `try_` style functions.
why diverge?
</blockquote></details>

so I change to try_parse all three functions?
___
*[`crates/cairo-lang-parser/src/parser.rs` line 1606 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4944#-NpFQIgb18GKJwf1y8Tl:-NpFSehMAvsUhfHv5mkG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2346e46202de7acacd232d1b941f9935f37c829c/crates/cairo-lang-parser/src/parser.rs#L1606)):*
> ```XML
>             Ok(BlockOrIfGreen::from(self.expect_if_expr(if_kw)?))
>         }
>     }
> ```

Done.
___
*[`crates/cairo-lang-parser/src/parser.rs` line 1646 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4944#-NpFQ6GOEmrtzMvOrA39:-NpFTt3NB-Qr_lGYGEWD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2346e46202de7acacd232d1b941f9935f37c829c/crates/cairo-lang-parser/src/parser.rs#L1646)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4944)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1599 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4944#-NpFQlSi4mu1NNTj9JlP:-NpFUKb1AkKsJCvSZcIA:b-h9uhuc) ([raw file](https://github.com/starkware-libs/cairo/blob/2346e46202de7acacd232d1b941f9935f37c829c/crates/cairo-lang-parser/src/parser.rs#L1599)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

so I change to try_parse all three functions?
</blockquote></details>

the question is - is this a case for a `try_` or a similar case to `expect_loop` and the others near it.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4944)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1599 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4944#-NpFQlSi4mu1NNTj9JlP:-NpK3rWSEW9Z7mBDKb-M:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/2346e46202de7acacd232d1b941f9935f37c829c/crates/cairo-lang-parser/src/parser.rs#L1599)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the question is - is this a case for a `try_` or a similar case to `expect_loop` and the others near it.
</blockquote></details>

Done

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4944)* status: all files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1191 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4944#-NpK7bHhEZA93Na531Gd:-NpK7bHi2jgORTisj7So:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ec5371a3417dd004032bd856d4c5f3835f112431/crates/cairo-lang-parser/src/parser.rs#L1191)):*
> ```XML
>             SyntaxKind::TerminalIf if lbrace_allowed == LbraceAllowed::Allow => {
>                 Ok(ExprGreen(self.expect_parse_if().0))
>             }
> ```





_Suggestion:_
```XML
            SyntaxKind::TerminalIf if lbrace_allowed == LbraceAllowed::Allow => {
                Ok(self.expect_parse_if().into())
            }
```
___
*[`crates/cairo-lang-parser/src/parser.rs` line 1607 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4944#-NpK7sys-AtZqgJQJWIa:-NpK7sys-AtZqgJQJWIb:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ec5371a3417dd004032bd856d4c5f3835f112431/crates/cairo-lang-parser/src/parser.rs#L1607)):*
> ```XML
>         }
>     }
>     /// Expected pattern: `if <expr> <block> [else <block>]`.
> ```





_Suggestion:_
```XML
        }
    }
    
    /// Expected pattern: `if <expr> <block> [else <block>]`.
```
___
*[`crates/cairo-lang-parser/src/parser.rs` line 1667 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4944#-NpK7ujp7X1ScjJxhujq:-NpK7ujq8Ou9uFEtam2d:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ec5371a3417dd004032bd856d4c5f3835f112431/crates/cairo-lang-parser/src/parser.rs#L1667)):*
> ```XML
>         }
>     }
>     /// Assumes the current token is `Loop`.
> ```





_Suggestion:_
```XML
    }
    
    /// Assumes the current token is `Loop`.
```
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/if_else` line 176 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4944#-NpK8C4w8vRkkXRYelxa:-NpK8C4w8vRkkXRYelxb:bp1tqfu) ([raw file](https://github.com/starkware-libs/cairo/blob/ec5371a3417dd004032bd856d4c5f3835f112431/crates/cairo-lang-parser/src/parser_test_data/partial_trees/if_else#L176)):*
> ```
> 
> //! > cairo_code
> /// TODO(Tomerstarkware): parse boolean expressions in if-let as separate expressions from the let expression.
> ```

shorten line.

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4944)* status: all files reviewed, 10 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1599 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4944#-NpK5q1zC-UIEKTlzRNg:-NpK5q1zC-UIEKTlzRNh:bvgdtv8) ([raw file](https://github.com/starkware-libs/cairo/blob/ec5371a3417dd004032bd856d4c5f3835f112431/crates/cairo-lang-parser/src/parser.rs#L1599)):*
> ```XML
> 
>     /// Assumes the current token is `If`.
>     fn expect_parse_if(&mut self) -> BlockOrIfGreen {
> ```

And in all the other `expect_parse...`



_Suggestion:_
```XML
fn expect_if
```
___
*[`crates/cairo-lang-parser/src/parser.rs` line 1607 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4944#-NpK6oXe154gcAxrV90l:-NpK6oXe154gcAxrV90m:b-ra05a7) ([raw file](https://github.com/starkware-libs/cairo/blob/ec5371a3417dd004032bd856d4c5f3835f112431/crates/cairo-lang-parser/src/parser.rs#L1607)):*
> ```XML
>         }
>     }
>     /// Expected pattern: `if <expr> <block> [else <block>]`.
> ```

The `if` is already taken at this point.



_Suggestion:_
```XML
<expr> <block> [else <block>]`
```
___
*[`crates/cairo-lang-parser/src/parser.rs` line 1608 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4944#-NpK82Pn0tYyTYjphC-e:-NpK82Pn0tYyTYjphC-f:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ec5371a3417dd004032bd856d4c5f3835f112431/crates/cairo-lang-parser/src/parser.rs#L1608)):*
> ```XML
>     }
>     /// Expected pattern: `if <expr> <block> [else <block>]`.
>     fn expect_parse_if_expr(&mut self, if_kw: TerminalIfGreen) -> ExprIfGreen {
> ```





_Suggestion:_
```XML
parse_if_expr(
```
___
*[`crates/cairo-lang-parser/src/parser.rs` line 1617 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4944#-NpK9dD63rb-ioun3Mz3:-NpK9dD63rb-ioun3Mz4:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ec5371a3417dd004032bd856d4c5f3835f112431/crates/cairo-lang-parser/src/parser.rs#L1617)):*
> ```XML
>     }
>     /// Expected pattern: `if let <pattern> = <expr> <block> [else <block>]`.
>     fn expect_parse_if_let_expr(&mut self, if_kw: TerminalIfGreen) -> ExprIfLetGreen {
> ```





_Suggestion:_
```XML
expect_if_let_expr
```
___
*[`crates/cairo-lang-parser/src/parser.rs` line 1634 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4944#-NpKBTh3AfaQtWoCRapd:-NpKBTh46Tr5PO6isAAL:b-pb44rm) ([raw file](https://github.com/starkware-libs/cairo/blob/ec5371a3417dd004032bd856d4c5f3835f112431/crates/cairo-lang-parser/src/parser.rs#L1634)):*
> ```XML
>             })
>         } else {
>             pattern_list_green
> ```

inline



_Code quote:_
```XML
pattern_list_green
```
___
*[`crates/cairo-lang-parser/src/parser.rs` line 1636 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4944#-NpKCV3Y8N1yeYEzR6fP:-NpKCV3Y8N1yeYEzR6fQ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ec5371a3417dd004032bd856d4c5f3835f112431/crates/cairo-lang-parser/src/parser.rs#L1636)):*
> ```XML
>             pattern_list_green
>         };
>         let eq = self.take::<TerminalEq>();
> ```





_Suggestion:_
```XML
self.parse_token
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4944)* status: 8 of 9 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1191 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4944#-NpK7bHhEZA93Na531Gd:-NpKNj029ozmguXFzTJN:b-uhecoz) ([raw file](https://github.com/starkware-libs/cairo/blob/ec5371a3417dd004032bd856d4c5f3835f112431/crates/cairo-lang-parser/src/parser.rs#L1191)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

there is no into from `BlockOrIf` to `Expr`
</blockquote></details>

why is this one different from all the others around it then?
___
*[`crates/cairo-lang-parser/src/parser.rs` line 1667 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4944#-NpK7ujp7X1ScjJxhujq:-NpKNsNzDUJ58DkqFh3s:b-284aay) ([raw file](https://github.com/starkware-libs/cairo/blob/ec5371a3417dd004032bd856d4c5f3835f112431/crates/cairo-lang-parser/src/parser.rs#L1667)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

no it isn't
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/if_else` line 176 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4944#-NpK8C4w8vRkkXRYelxa:-NpKO-46AiT-JDr3cMEK:b-3wzbn7) ([raw file](https://github.com/starkware-libs/cairo/blob/ec5371a3417dd004032bd856d4c5f3835f112431/crates/cairo-lang-parser/src/parser_test_data/partial_trees/if_else#L176)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

shorten line.
</blockquote></details>

still use the most inside a single line.

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, 3 of 3 files at r4, 2 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4944)* status: all files reviewed, 5 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-parser/src/parser_test_data/diagnostics/if` line 50 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4944#-NpKYAwGC6MduFnRxPL7:-NpKYAwGC6MduFnRxPL8:bfruwtc) ([raw file](https://github.com/starkware-libs/cairo/blob/04b71a3d228bee132a7b2d2179f893ce91d2fa28/crates/cairo-lang-parser/src/parser_test_data/diagnostics/if#L50)):*
> ```
> //! > ==========================================================================
> 
> //! > Test if-let missing pattern
> ```

Add common mixed up cases, e.g.:
`if let x {}`,
`if let x == y {}`,
`if x = y {}`
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/if_else` line 98 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4944#-NpKYhcI6uYzH57qdUwc:-NpKYhcI6uYzH57qdUwd:b-m2yqiy) ([raw file](https://github.com/starkware-libs/cairo/blob/04b71a3d228bee132a7b2d2179f893ce91d2fa28/crates/cairo-lang-parser/src/parser_test_data/partial_trees/if_else#L98)):*
> ```
> 
> //! > ignored_kinds
> ExprBinary
> ```

Not sure if `ExprBinary` is needed, but `ExprBlock` should be ignored.



_Code quote:_
```
ExprBinary
```
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/if_else` line 188 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4944#-NpKYzmGBGxMgWKUfHUc:-NpKYzmGBGxMgWKUfHUd:b2nreh6) ([raw file](https://github.com/starkware-libs/cairo/blob/04b71a3d228bee132a7b2d2179f893ce91d2fa28/crates/cairo-lang-parser/src/parser_test_data/partial_trees/if_else#L188)):*
> ```
> 
> //! > ignored_kinds
> ```

Same as above.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4944)* status: 6 of 9 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1191 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4944#-NpK7bHhEZA93Na531Gd:-NpKn_n1A-nuoH1DyMT-:b9ilxkx) ([raw file](https://github.com/starkware-libs/cairo/blob/ec5371a3417dd004032bd856d4c5f3835f112431/crates/cairo-lang-parser/src/parser.rs#L1191)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

BlockOrIf is not defined as an expression in the parser
I can either add it or define a new terminal for both if-types and return that type from `expect_if`
both would require an enum inside an enum which Gil claims is problematic
</blockquote></details>

it is weird that all (which is only one) calls to `expect_if` use only `.0` of it.
i would expect a different return value.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4944)* status: 6 of 9 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1191 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4944#-NpK7bHhEZA93Na531Gd:-NpOP19FBosDb6iTj2cL:brad4gj) ([raw file](https://github.com/starkware-libs/cairo/blob/ec5371a3417dd004032bd856d4c5f3835f112431/crates/cairo-lang-parser/src/parser.rs#L1191)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it is weird that all (which is only one) calls to `expect_if` use only `.0` of it.
i would expect a different return value.
</blockquote></details>

parse_optional_else_clause function also calls to expect_if

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4944)* status: 6 of 9 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1191 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4944#-NpK7bHhEZA93Na531Gd:-NpOgHUeElu2ZMOwyp0b:b-z7rpso) ([raw file](https://github.com/starkware-libs/cairo/blob/ec5371a3417dd004032bd856d4c5f3835f112431/crates/cairo-lang-parser/src/parser.rs#L1191)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

parse_optional_else_clause function also calls to expect_if
</blockquote></details>

so wrap it in a block there instead of removing it here.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4944)* status: 5 of 9 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1191 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4944#-NpK7bHhEZA93Na531Gd:-NpP15gfBzU9bEIDcKc2:b9bed1d) ([raw file](https://github.com/starkware-libs/cairo/blob/ec5371a3417dd004032bd856d4c5f3835f112431/crates/cairo-lang-parser/src/parser.rs#L1191)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

so wrap it in a block there instead of removing it here.
</blockquote></details>

Now expect_if returns ExprGreen and parse_optional_else_clause casts to BlockOrIfGreen.
This seems worse as converting BlockOrIfGreen to ExprGreen should always be possible, but otherwise is not always true (but will work in this case)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4944)* status: 5 of 9 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1599 at r9](https://reviewable.io/reviews/starkware-libs/cairo/4944#-NpP3Ded65DC0-v9r2MU:-NpP3Ded65DC0-v9r2MV:b-i4t16j) ([raw file](https://github.com/starkware-libs/cairo/blob/59ca0545d87d96073e0fb92a9041b93c61025336/crates/cairo-lang-parser/src/parser.rs#L1599)):*
> ```XML
> 
>     /// Assumes the current token is `If`.
>     fn expect_if(&mut self) -> ExprGreen {
> ```

can you just return the inner type and wrap it on the different callsites?



_Code quote:_
```XML
f) -> ExprGreen 
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4944)* status: 5 of 9 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1599 at r9](https://reviewable.io/reviews/starkware-libs/cairo/4944#-NpP3Ded65DC0-v9r2MU:-NpP3nxM6tdSMU5XfbOn:bn03u4s) ([raw file](https://github.com/starkware-libs/cairo/blob/59ca0545d87d96073e0fb92a9041b93c61025336/crates/cairo-lang-parser/src/parser.rs#L1599)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can you just return the inner type and wrap it on the different callsites?
</blockquote></details>

The inner type can either be ExprIfGreen or ExprIfLetGreen which both can be cast ExprGreen or ExprBlockIfGreen,
I can also create a non-generated type to cast both into and cast that type into ExprGreen and ExprBlockIfGreen, but that seems redundant

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4944)* status: 5 of 9 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-syntax-codegen/src/cairo_spec.rs` line 166 at r9](https://reviewable.io/reviews/starkware-libs/cairo/4944#-NpPBqhf3SgvMYWBsuoZ:-NpPBqhf3SgvMYWBsuo_:b-xkmwc8) ([raw file](https://github.com/starkware-libs/cairo/blob/59ca0545d87d96073e0fb92a9041b93c61025336/crates/cairo-lang-syntax-codegen/src/cairo_spec.rs#L166)):*
> ```XML
>     .add_struct(StructBuilder::new("ExprIf")
>         .node("if_kw", "TerminalIf")
>         .node("condition", "Expr")
> ```

it seems the spec is wrong - and `if let Some(x) = v` `Some(x) = v` should be considered a condition.



_Code quote:_
```XML
        .node("condition", "Expr")
```

**Review by orizi — COMMENTED** [review]
> Reviewed 7 of 7 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4944)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r7, 1 of 1 files at r11, 6 of 6 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4944)* status: all files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-formatter/test_data/cairo_files/test1.cairo` line 52 at r12](https://reviewable.io/reviews/starkware-libs/cairo/4944#-NpTyesgA9Me9DJuqAE_:-NpTyesgA9Me9DJuqAEa:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d323f82d70f8a14131c2f54618f8936671e4e9da/crates/cairo-lang-formatter/test_data/cairo_files/test1.cairo#L52)):*
> ```Cairo
> fn if_let_test() {
>     if let (x, y) = (x + x + x + x + x + x + x + x + x + x + x + x + x + x + x + x + x + x,y + y + y + y + y + y) {
>         println!("x is five!");
> ```





_Suggestion:_
```Cairo
        if_let_block_content();
```
___
*[`crates/cairo-lang-formatter/test_data/cairo_files/test1.cairo` line 54 at r12](https://reviewable.io/reviews/starkware-libs/cairo/4944#-NpTytSF0pC0LUOWfh6H:-NpTytSF0pC0LUOWfh6I:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d323f82d70f8a14131c2f54618f8936671e4e9da/crates/cairo-lang-formatter/test_data/cairo_files/test1.cairo#L54)):*
> ```Cairo
>         println!("x is five!");
>     }
> }
> ```





_Suggestion:_
```Cairo
    }
}
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4944#-:-NpU9eWDDTyo7R7rzdfq:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, 5 of 7 files at r10, 1 of 1 files at r11, 4 of 6 files at r12, 1 of 2 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4944#-:-NpUKjYWBhyWXTWfZwxA:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1631 at r13](https://reviewable.io/reviews/starkware-libs/cairo/4944#-NpUK1PEDrQPz1tLfXNL:-NpUK1PEDrQPz1tLfXNM:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f3dfa4aa2982e2745bb1f4a300403930a184f072/crates/cairo-lang-parser/src/parser.rs#L1631)):*
> ```XML
>             Self::try_parse_pattern,
>             is_of_kind!(eq),
>             "pattern",Some(ParserDiagnosticKind::DisallowedTrailingSeparatorOr),
> ```





_Suggestion:_
```XML
  "pattern",
  Some(ParserDiagnosticKind::DisallowedTrailingSeparatorOr),
```

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4944)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4944)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

**Pull request merged**
