### PR TITLE
LS: Proc macro request handling

### PR DESCRIPTION
**Pull request by Draggu**
This should be in next PR but it is bloated with code copied from scarb.

---

**Stack**:
- #6706
- #6705
- #6704
- #6638
- #6703 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by piotmag769 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6703)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @integraledelebesgue, @mkaput, and @orizi)

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6703#-:-OCHdOoL1CokJd20ZbL8:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @integraledelebesgue, and @orizi)

**Review by Arcticae — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6703#-:-OCIouyD75rWPcedwWmw:bg7igkv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @integraledelebesgue and @orizi)

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6703)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @integraledelebesgue and @orizi)

**Review by mkaput — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6703)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @integraledelebesgue and @orizi)

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6703)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
