### PR TITLE
Supported Hover hints for impl functions in the language server

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1766)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1766)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 507 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1766#-NLpvJBi8YVcLTIQoIBF:-NLpvJBi8YVcLTIQoIBG:bkunk2m) ([raw file](https://github.com/starkware-libs/cairo/blob/a7bfc0d77948b1cfefe57c7ac67af0e82b4d254f/crates/cairo-lang-language-server/src/lib.rs#L507)):*
> ```XML
>     match node.kind(syntax_db) {
>         SyntaxKind::ItemFreeFunction => {
>             if node.parent()?.parent()?.kind(syntax_db) == SyntaxKind::ImplBody {
> ```

The `?` are wrong here I think. You want to fallback to FreeFunction.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1766)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 507 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1766#-NLpvJBi8YVcLTIQoIBF:-NLqXSvQ2fX2SwNod2zC:b-7hygmy) ([raw file](https://github.com/starkware-libs/cairo/blob/a7bfc0d77948b1cfefe57c7ac67af0e82b4d254f/crates/cairo-lang-language-server/src/lib.rs#L507)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

The `?` are wrong here I think. You want to fallback to FreeFunction.
</blockquote></details>

Good catch, thanks. Fixed.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1766)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1766#-NLq_uJPDIW2i24jBTfp:-NLq_uJPDIW2i24jBTfq:be4x7vm) (no related file):*
don't delete branch

___

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1766#-:-NLtVJt30BS-7OGT4Yd6:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1766)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1766#-:-NLyxRnoCFmm0UZL-1tr:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
