### PR TITLE
Added expect_diagnostics parameter to test_expr_diagnostics

### PR DESCRIPTION
**Pull request by yuvalsw**
Also fixed a "#[must_use] test

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5279)

### CODE REVIEW

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5279)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/tests` line 467 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5279#-NtGKpbiBOXYVcgzlmng:-NtGKpbj7SFAw5povWLl:b-exgbvf) ([raw file](https://github.com/starkware-libs/cairo/blob/cff46bb8ae2c42d70575527e1b2c915f8b80c54f/crates/cairo-lang-semantic/src/diagnostic_test_data/tests#L467)):*
> ```
> //! > expr_code
> {
>   must_use_function();
> ```

That's intentional, to test that a tail expression is considered as usage.



_Suggestion:_
```
  must_use_function()
```

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5279)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/tests` line 467 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5279#-NtGKpbiBOXYVcgzlmng:-NtGL8Vw216FRkb3AKGA:b-y9egg6) ([raw file](https://github.com/starkware-libs/cairo/blob/cff46bb8ae2c42d70575527e1b2c915f8b80c54f/crates/cairo-lang-semantic/src/diagnostic_test_data/tests#L467)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

That's intentional, to test that a tail expression is considered as usage.
</blockquote></details>

We can add another test with the `;` but not sure if it's really needed.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5279#-:-NtIjkW30aIXFeOQvYy_:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/tests` line 467 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5279#-NtGKpbiBOXYVcgzlmng:-NtIjHSBCk7uxtFty-NW:bm2y8qb) ([raw file](https://github.com/starkware-libs/cairo/blob/cff46bb8ae2c42d70575527e1b2c915f8b80c54f/crates/cairo-lang-semantic/src/diagnostic_test_data/tests#L467)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Ah, ok, the test name should reflect the meaning, especially that this is under diagnostic_test_data. A reader can't guess the intention :)
</blockquote></details>

It does say tail expression :)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5279#-:-NtRLP-AEtadk39ZhBy1:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Pull request merged**
