### PR TITLE
Fixed drop issue

### LINKED ISSUE #2152: bug: Wrong Drops
The following code tried to Drop Pedersen.
```
fn reproduce_bug() {
    match get_gas_all(get_builtin_costs()) {
        Option::Some(_) => {},
        Option::None(_) => {
            let mut data = ArrayTrait::new();
            data.append('OOG');
            panic(data);
        }
    }
    let a = 1;
    let b = 2;
    let mut c = 0;
    if a < b {
        c = LegacyHash::hash(a, b);
    } else {
        c = LegacyHash::hash(b, a);
    }
}
```

### PR DESCRIPTION
**Pull request by spapinistarkware**
Fixes #2152

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2154)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2154#-:-NOKoPrv8IankHdumV6r:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-generator/src/utils.rs` line 342 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2154#-NOKo2Vz6NkECg8CXAIP:-NOKo2Vz6NkECg8CXAIQ:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/8258c3da45b4b4528130804739c4daec71d23098/crates/cairo-lang-sierra-generator/src/utils.rs#L342)):*
> ```XML
> }
> 
> fn block_outputs(
> ```

doc



_Code quote:_
```XML
block_outputs(
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2154)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/utils.rs` line 342 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2154#-NOKo2Vz6NkECg8CXAIP:-NOKp2kT6I8wPLQpvKuU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8258c3da45b4b4528130804739c4daec71d23098/crates/cairo-lang-sierra-generator/src/utils.rs#L342)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2154)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2154)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-sierra-generator/src/utils.rs` line 336 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2154#-NOKrBNJ0yxpBSYwgNA4:-NOKrBNK6SfCXlox_fv1:bixrbbx) ([raw file](https://github.com/starkware-libs/cairo/blob/5977813377262a7623c952987ce4d28b8bf93479/crates/cairo-lang-sierra-generator/src/utils.rs#L336)):*
> ```XML
>     for block in blocks {
>         if let lowering::FlatBlockEnd::Callsite(remapping) = &lowered_function.blocks[*block].end {
>             // It is guaranteed by lowering phase that all of the variables mapped to are the same.
> ```

Don't you want to keep the comment? Otherwise, it's unclear why you stop at the first one.
___
*[`crates/cairo-lang-sierra-generator/src/utils.rs` line 342 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2154#-NOKrHepAdFUEV7HzM6A:-NOKrHepAdFUEV7HzM6B:bohcw3q) ([raw file](https://github.com/starkware-libs/cairo/blob/520a8151894009b4a42fda9a358dcd7d3e6cd20d/crates/cairo-lang-sierra-generator/src/utils.rs#L342)):*
> ```XML
> }
> 
> /// Collects output variables from a block.
> ```

Mention when None is returned.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2154)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2154)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by liorgold2 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2154)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by liorgold2 — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2154)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
