### PR TITLE
Support right/left trimmed nodes in patcher

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2293)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2293)* status: 3 of 7 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/patcher.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2293#-NPHijNE9d5pzvsHa-UL:-NPHijNE9d5pzvsHa-UM:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/e0beb783e20c2fc7acf458955d63e62696e25b9e/crates/cairo-lang-semantic/src/patcher.rs#L9)):*
> ```XML
> use cairo_lang_utils::extract_matches;
> 
> // TODO(yg): split to 4 PRs: 1. support right/left trimmed nodes. 2.
> ```

remove



_Code quote:_
```XML
// TODO(yg): split to 4 PRs: 1. support right/left trimmed nodes. 2.
// support modifying trimmed nodes. 3. fix contract code to not copy mut modifier. 4. use mut param
// in Cairo contract.
```
___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 221 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2293#-NPHmrx62oxld-cTNLAS:-NPHmrx62oxld-cTNLAT:b-s1kdas) ([raw file](https://github.com/starkware-libs/cairo/blob/e0beb783e20c2fc7acf458955d63e62696e25b9e/crates/cairo-lang-starknet/src/plugin/contract.rs#L221)):*
> ```XML
>             (
>                 "original_items".to_string(),
>                 RewriteNode::Modified(ModifiedNode { children: Some(kept_original_items) }),
> ```

add new_modified



_Code quote:_
```XML
Modified(ModifiedNode { children: Some(kept_original_items) })
```

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2293#-:-NPHmyb9CVtWDtGBRRZ6:bnfp4nl)* status: 3 of 7 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2293)* status: 3 of 7 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/patcher.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2293#-NPHijNE9d5pzvsHa-UL:-NPHoJHqCCGmsQ9uoZvP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e0beb783e20c2fc7acf458955d63e62696e25b9e/crates/cairo-lang-semantic/src/patcher.rs#L9)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 221 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2293#-NPHmrx62oxld-cTNLAS:-NPHqIsE2RTTlFSWXhOs:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e0beb783e20c2fc7acf458955d63e62696e25b9e/crates/cairo-lang-starknet/src/plugin/contract.rs#L221)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add new_modified
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2293#-:-NPHslPl8vPAkQM8fLm1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
