### PR TITLE
Make bytecode unsigned.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1217)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1217#-:-NIaQ6pN60AePSxU8Ogz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware and @yuvalsw)

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1217)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/starknet/src/casm_contract_class.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1217#-NIaWGIfCUywfCto0IzQ:-NIaWGIfCUywfCto0IzR:b-6rmhvg) ([raw file](https://github.com/starkware-libs/cairo/blob/356f4f2397b93ebef7c4ab97e28aee78af31ef2c/crates/starknet/src/casm_contract_class.rs#L64)):*
> ```XML
>             }
>             bytecode.extend(instruction.assemble().encode().iter().map(|big_int| {
>                 let res = big_int % &prime;
> ```

bigint modulo can be negative :(
```
if res.is_negative() {
res += prime
}
```

Then remove assertion

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1217)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi, @spapinistarkware, and @yuvalsw)

___
*[`crates/starknet/src/casm_contract_class.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1217#-NIaWGIfCUywfCto0IzQ:-NIarazA3tAzd0P7OZ1C:b-rgqe3i) ([raw file](https://github.com/starkware-libs/cairo/blob/356f4f2397b93ebef7c4ab97e28aee78af31ef2c/crates/starknet/src/casm_contract_class.rs#L64)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

bigint modulo can be negative :(
```
if res.is_negative() {
res += prime
}
```

Then remove assertion
</blockquote></details>

I did something slightly different.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1217#-:-NIazFLa1992fSJnLxqc:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware and @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1217)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1217)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1217)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
