### PR TITLE
Added support for should_panic with a string literal

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4265)

### CODE REVIEW

**Comment by yuvalsw** [comment]
change target

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4265)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-test-plugin/src/test_config.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4265#-NgwPIqS87n9dC7czChi:-NgwPIqS87n9dC7czChj:bo2ypu9) ([raw file](https://github.com/starkware-libs/cairo/blob/f7ccbdcef84e3416ec8c5c49613bcd9bb7e4fe2e/crates/cairo-lang-test-plugin/src/test_config.rs#L15)):*
> ```XML
> 
> const BYTE_ARRAY_MAGIC_HIGH: u128 = 0x46a6158a16a947e5916b2a2ca68501a;
> const BYTE_ARRAY_MAGIC_LOW: u128 = 0x45e93d7110e81aa2d6438b1c57c879a3;
> ```

have this as:
and later use `felt_str!`



_Suggestion:_
```XML
const BYTE_ARRAY_MAGIC_HIGH: &str = "0x46a6158a16a947e5916b2a2ca68501a45e93d7110e81aa2d6438b1c57c879a3";
```
___
*[`crates/cairo-lang-test-plugin/src/test_config.rs` line 213 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4265#-NgwQ8ht8AOMAQKHThtQ:-NgwQ8ht8AOMAQKHThtR:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f7ccbdcef84e3416ec8c5c49613bcd9bb7e4fe2e/crates/cairo-lang-test-plugin/src/test_config.rs#L213)):*
> ```XML
>                 )
>                 .collect(),
>             )
> ```





_Suggestion:_
```XML
            let panic_string = panic_string.string_value(db).unwrap();
            let full_words = panic_string.as_bytes().chunks_exact(31);
            let pending_word = full_words.remainder();
            Some(
                chain!(
                    [felt_str!(byte_array_magic), full_words.len().into()],
                    full_words.map(|word|BigInt::from_bytes_be(Sign::Plus, word).into()),
                    [BigInt::from_bytes_be(Sign::Plus, pending_word).into(), pending_word.len().into()]
                )
                .collect(),
            )
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4265)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/test/byte_array_test.cairo` line 485 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4265#-NgwRGJJ78bT2euBbTJC:-NgwRGJJ78bT2euBbTJD:bx0ve6i) ([raw file](https://github.com/starkware-libs/cairo/blob/f7ccbdcef84e3416ec8c5c49613bcd9bb7e4fe2e/corelib/src/test/byte_array_test.cairo#L485)):*
> ```Cairo
> 
> #[test]
> #[should_panic(expected: "error")]
> ```

what about stacking of errors?
("error", 'wrapping1' , 'wrapping2')

it is probably required to have the single output option as a shorthand.



_Code quote:_
```Cairo
#[should_panic(expected: "error")]
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4265)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/test/byte_array_test.cairo` line 485 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4265#-NgwRGJJ78bT2euBbTJC:-NgwcRIbEAmT-naRLWc3:b-nphwqk) ([raw file](https://github.com/starkware-libs/cairo/blob/f7ccbdcef84e3416ec8c5c49613bcd9bb7e4fe2e/corelib/src/test/byte_array_test.cairo#L485)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

what about stacking of errors?
("error", 'wrapping1' , 'wrapping2')

it is probably required to have the single output option as a shorthand.
</blockquote></details>

another PR
___
*[`crates/cairo-lang-test-plugin/src/test_config.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4265#-NgwPIqS87n9dC7czChi:-Ngwc6YhCWaOMrk-_cqG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f7ccbdcef84e3416ec8c5c49613bcd9bb7e4fe2e/crates/cairo-lang-test-plugin/src/test_config.rs#L15)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

have this as:
and later use `felt_str!`
</blockquote></details>

Done.
___
*[`crates/cairo-lang-test-plugin/src/test_config.rs` line 213 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4265#-NgwQ8ht8AOMAQKHThtQ:-Ngwbyu93t1Up2k9oOq4:ba7c925) ([raw file](https://github.com/starkware-libs/cairo/blob/f7ccbdcef84e3416ec8c5c49613bcd9bb7e4fe2e/crates/cairo-lang-test-plugin/src/test_config.rs#L213)):*
> ```XML
>                 )
>                 .collect(),
>             )
> ```

Done most. Prefer not to inline everything as it's easier to read.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4265#-:-NgxTCrm84k7IG55cnOX:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4265)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
