### PR TITLE
Add ec_add and ec_sub.

### PR DESCRIPTION
**Pull request by liorgold2**
commit-id:22160822

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1887#-:-NMZPLHZ0qDD6EdY-10H:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1887)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1887)* status: all files reviewed, 4 unresolved discussions (waiting on @liorgold2)

___
*[`corelib/ec.cairo` line 5 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1887#-NMbzN7ICqvNIuNu6i04:-NMbzN7ICqvNIuNu6i05:bbzgr63) ([raw file](https://github.com/starkware-libs/cairo/blob/43524bc5adbd72827495434b1cb09d119d67f6e6/corelib/ec.cairo#L5)):*
> ```Cairo
> extern type EcPoint;
> 
> impl OptionEcPointCopy of Copy::<Option::<EcPoint>>;
> ```

what is `impl .. of` in rust? docs only mention `impl .. for` from what I can search



_Code quote:_
```Cairo
impl OptionEcPointCopy of Copy::<Option::<EcPoint>>;
```
___
*[`corelib/ec.cairo` line 56 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1887#-NMbwWFW7fzWmTZ4SXlR:-NMbwWFW7fzWmTZ4SXlS:b-q3e0qh) ([raw file](https://github.com/starkware-libs/cairo/blob/43524bc5adbd72827495434b1cb09d119d67f6e6/corelib/ec.cairo#L56)):*
> ```Cairo
> }
> 
> fn ec_sub(p: Option::<EcPoint>, q: Option::<EcPoint>) -> Option::<EcPoint> {
> ```

weird that `ec_add` has a docstring and `ec_sub` doesn't
___
*[`corelib/test.cairo` line 37 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1887#-NMbzR-8EmuFTs8dI_K-:-NMbzR-8EmuFTs8dI_K0:b-735ktu) ([raw file](https://github.com/starkware-libs/cairo/blob/43524bc5adbd72827495434b1cb09d119d67f6e6/corelib/test.cairo#L37)):*
> ```Cairo
> }
> 
> impl OptionEcPointCopy of Copy::<Option::<EcPoint>>;
> ```

why does this line appear twice?



_Code quote:_
```Cairo
impl OptionEcPointCopy of Copy::<Option::<EcPoint>>;
```
___
*[`corelib/test.cairo` line 83 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1887#-NMc-1S345vWjSNtExXd:-NMc-1S345vWjSNtExXe:b-sar63b) ([raw file](https://github.com/starkware-libs/cairo/blob/43524bc5adbd72827495434b1cb09d119d67f6e6/corelib/test.cairo#L83)):*
> ```Cairo
>     // Compute `(-p) - p`.
>     let (sub2_x,
>     sub2_y) = ec_point_unwrap(ec_sub(Option::Some(ec_neg(p)), Option::Some(p)).unwrap());
> ```

is gil aware of this weird linebreak?



_Code quote:_
```Cairo
    let (sub2_x,
    sub2_y) = ec_point_unwrap(ec_sub(Option::Some(ec_neg(p)), Option::Some(p)).unwrap());
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1887)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1887)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`corelib/ec.cairo` line 56 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1887#-NMc6l9uD8MrPjAQjTI8:-NMc6l9uD8MrPjAQjTI9:bimlq98) ([raw file](https://github.com/starkware-libs/cairo/blob/ded78e364123317e91c7a7bd95131024dd705745/corelib/ec.cairo#L56)):*
> ```Cairo
> }
> 
> fn ec_sub(p: Option::<EcPoint>, q: Option::<EcPoint>) -> Option::<EcPoint> {
> ```

impl EcPointSub of Sub::<Option::<EcPoint>> {

is now supported.



_Code quote:_
```Cairo
fn ec_sub(p: Option::<EcPoint>, q: Option::<EcPoint>) -> Option::<EcPoint> {
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1887)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1887)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @orizi)

___
*[`corelib/ec.cairo` line 56 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1887#-NMbwWFW7fzWmTZ4SXlR:-NMchQ_YD4jCvnNABnsQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/43524bc5adbd72827495434b1cb09d119d67f6e6/corelib/ec.cairo#L56)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

weird that `ec_add` has a docstring and `ec_sub` doesn't
</blockquote></details>

Done.
___
*[`corelib/ec.cairo` line 56 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1887#-NMc6l9uD8MrPjAQjTI8:-NMchRFm6nHZxZ9ou8gU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ded78e364123317e91c7a7bd95131024dd705745/corelib/ec.cairo#L56)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

impl EcPointSub of Sub::<Option::<EcPoint>> {

is now supported.
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1887)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1887)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1887#-:-NMcitVY5bvhdx2_RFEW:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
