### PR TITLE
Split blocks after match statements

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2224)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2224)* status: 0 of 37 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 556 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2224#-NOoH-JsAWMV0TwO_ofr:-NOoH-JuDAocEaI4tQdm:b-48bvhk) ([raw file](https://github.com/starkware-libs/cairo/blob/a09de02dbe59f0fdeed90cd8945cc332b4cb7dba/crates/cairo-lang-lowering/src/inline/mod.rs#L556)):*
> ```XML
>         self.statement_rewrite_stack.push_statments(
>             root_block.statements.iter().map(|statement| mapper.rebuild_statement(statement)),
>         );
> ```

This will make the root block exit the function, which is wrong.



_Code quote:_
```XML
        self.block_end = FlatBlockEnd::Fallthrough(
            return_block_id,
            VarRemapping {
                remapping: OrderedHashMap::from_iter(izip!(
                    outputs.iter().cloned(),
                    actual_outputs.iter().map(|var_id| mapper.rename_var(var_id)),


                )),
            },
        );

        for (block_id, _) in lowered.blocks.iter() {
            if block_id == root_block_id {
                continue;
            }
            mapper.rename_block(&block_id);
        }

        self.statement_rewrite_stack.push_statments(
            root_block.statements.iter().map(|statement| mapper.rebuild_statement(statement)),
        );
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2224)* status: 1 of 37 files reviewed, 6 unresolved discussions (waiting on @orizi, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 104 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2224#-NOrnwZF81c1gbuJO3hk:-NOrnwZG9Lu_D47ZtVo2:b-ad75pi) ([raw file](https://github.com/starkware-libs/cairo/blob/786c83677aeabdcf7f8aa2c0e0eb8d58fff0a91d/crates/cairo-lang-lowering/src/inline/mod.rs#L104)):*
> ```XML
>         match &block.end {
>             FlatBlockEnd::Return(_) => {}
>             FlatBlockEnd::Unreachable | FlatBlockEnd::Goto(..) | FlatBlockEnd::Fallthrough(..) => {
> ```

merge withhe FlatBlockEnd::Callsite case.



_Code quote:_
```XML
| FlatBlockEnd::Goto(..) | FlatBlockEnd::Fallthrough(..)
```
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 373 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2224#-NOroCYbB50QvLcrpALZ:-NOroCYbB50QvLcrpAL_:bjs5809) ([raw file](https://github.com/starkware-libs/cairo/blob/786c83677aeabdcf7f8aa2c0e0eb8d58fff0a91d/crates/cairo-lang-lowering/src/inline/mod.rs#L373)):*
> ```XML
>     }
> 
>     fn fix_block_end(
> ```

Document

Fixes a block by remmaping var_ids and block_ids.
Returns are replace with Goto/Fallthrough to  return_block_id.



_Code quote:_
```XML
fix_block_end
```
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 378 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2224#-NOroOv_0YQ-EE_d5zng:-NOroOv_0YQ-EE_d5znh:b-fsfdja) ([raw file](https://github.com/starkware-libs/cairo/blob/786c83677aeabdcf7f8aa2c0e0eb8d58fff0a91d/crates/cairo-lang-lowering/src/inline/mod.rs#L378)):*
> ```XML
>         return_block_id: BlockId,
>         outputs: &[id_arena::Id<crate::Variable>],
>         is_last_block: bool,
> ```

or use_fallthrough



_Suggestion:_
```XML
should_fallthrough
```
___
*[`crates/cairo-lang-lowering/src/inline/test_data/inline` line 375 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2224#-NOrp6zZDMBRkS-qh-8B:-NOrp6zZDMBRkS-qh-8C:beedkr4) ([raw file](https://github.com/starkware-libs/cairo/blob/786c83677aeabdcf7f8aa2c0e0eb8d58fff0a91d/crates/cairo-lang-lowering/src/inline/test_data/inline#L375)):*
> ```
>     return 1;
>   }
> End:
> ```

revet changes



_Code quote:_
```
End:
  Fallthrough(blk6, {})

blk1:
```

**Review by ilyalesokhin-starkware — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2224)* status: 1 of 37 files reviewed, 5 unresolved discussions (waiting on @orizi, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 110 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2224#-NOs61J86RNQKFCtyXer:-NOs61J86RNQKFCtyXes:b-xdaocx) ([raw file](https://github.com/starkware-libs/cairo/blob/786c83677aeabdcf7f8aa2c0e0eb8d58fff0a91d/crates/cairo-lang-lowering/src/inline/mod.rs#L110)):*
> ```XML
>                         diagnostics.report(
>                             function_id.untyped_stable_ptr(defs_db),
>                             LoweringDiagnosticKind::InliningFunctionWithUnreachableEndNotSupported,
> ```

consider fixing the error message
root block => root scope.



_Code quote:_
```XML
InliningFunctionWithUnreachableEndNotSupported
```
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 373 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2224#-NOroCYbB50QvLcrpALZ:-NOs6FNY4nnLhsCWbkge:b-jjg71z) ([raw file](https://github.com/starkware-libs/cairo/blob/786c83677aeabdcf7f8aa2c0e0eb8d58fff0a91d/crates/cairo-lang-lowering/src/inline/mod.rs#L373)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Document

Fixes a block by remmaping var_ids and block_ids.
Returns are replace with Goto/Fallthrough to  return_block_id.
</blockquote></details>

actually I added this function to my PR
https://reviewable.io/reviews/starkware-libs/cairo/2237

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2224)* status: 1 of 37 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/borrow_check/mod.rs` line 148 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2224#-NOsTKRuEJ2NOUj_Ua6i:-NOsTKRuEJ2NOUj_Ua6j:b11hssb) ([raw file](https://github.com/starkware-libs/cairo/blob/786c83677aeabdcf7f8aa2c0e0eb8d58fff0a91d/crates/cairo-lang-lowering/src/borrow_check/mod.rs#L148)):*
> ```XML
>     ) -> LoweredDemand {
>         let demand = match block_end {
>             FlatBlockEnd::Fallthrough(target_block_id, remapping) => {
> ```

Can you unite the 2 match arms?

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2224)* status: 1 of 37 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/fmt.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2224#-NOoIuje1xCc5nLZ901L:-NOozJDR6yK5LmxZ65gS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a09de02dbe59f0fdeed90cd8945cc332b4cb7dba/crates/cairo-lang-lowering/src/fmt.rs#L43)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

but also - would we never want to debug print a block in the middle of the population stage?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2224#-NOoGZgs7ohS0yq4uQ2x:-NOoyYNP5Y-uOILnbh3-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a09de02dbe59f0fdeed90cd8945cc332b4cb7dba/crates/cairo-lang-lowering/src/inline/mod.rs#L112)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

don't you need to fix that?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 556 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2224#-NOoH-JsAWMV0TwO_ofr:-NOoyrr3AbEnvYcGvP3J:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a09de02dbe59f0fdeed90cd8945cc332b4cb7dba/crates/cairo-lang-lowering/src/inline/mod.rs#L556)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

This will make the root block exit the function, which is wrong.
</blockquote></details>

Done.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2224)* status: 1 of 38 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/mod.rs` line 148 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2224#-NOsTKRuEJ2NOUj_Ua6i:-NOsc6iBASPU9MB5fQTe:bvszvy4) ([raw file](https://github.com/starkware-libs/cairo/blob/973280b7cddf4febd14a39c8c51ab0e6c5af2204/crates/cairo-lang-lowering/src/borrow_check/mod.rs#L148)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Can you unite the 2 match arms?
</blockquote></details>

The logic uses fallthrough/goto according to the original variant.
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 104 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2224#-NOrnwZF81c1gbuJO3hk:-NOsYjLwAz76LH0Uk1QO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/973280b7cddf4febd14a39c8c51ab0e6c5af2204/crates/cairo-lang-lowering/src/inline/mod.rs#L104)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

merge withhe FlatBlockEnd::Callsite case.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 373 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2224#-NOroCYbB50QvLcrpALZ:-NOsZ3n--RDoAfn3GUp4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/973280b7cddf4febd14a39c8c51ab0e6c5af2204/crates/cairo-lang-lowering/src/inline/mod.rs#L373)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

actually I added this function to my PR
https://reviewable.io/reviews/starkware-libs/cairo/2237
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 378 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2224#-NOroOv_0YQ-EE_d5zng:-NOsanpwAQrsbn-1vMFG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/973280b7cddf4febd14a39c8c51ab0e6c5af2204/crates/cairo-lang-lowering/src/inline/mod.rs#L378)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

or use_fallthrough
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/inline/test_data/inline` line 375 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2224#-NOrp6zZDMBRkS-qh-8B:-NOsas_MBZXUBmzmnGRN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/973280b7cddf4febd14a39c8c51ab0e6c5af2204/crates/cairo-lang-lowering/src/inline/test_data/inline#L375)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

revet changes
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 16 of 37 files at r1, 1 of 5 files at r3, 1 of 5 files at r4, 2 of 5 files at r5, 20 of 20 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2224#-:-NOshb5p5M_cfbKOKGZ_:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/fmt.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2224#-NOoIuje1xCc5nLZ901L:-NOsfSui7tNxxHGJ5OtZ:b8v30mr) ([raw file](https://github.com/starkware-libs/cairo/blob/a09de02dbe59f0fdeed90cd8945cc332b4cb7dba/crates/cairo-lang-lowering/src/fmt.rs#L43)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Done.
</blockquote></details>

this still does not answer the question about partial population debug printing.
___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 327 at r6](https://reviewable.io/reviews/starkware-libs/cairo/2224#-NOsg50s4k7XPR0WjH_r:-NOsg50s4k7XPR0WjH_s:bhyyzvc) ([raw file](https://github.com/starkware-libs/cairo/blob/472a8b7e1ce2c0421789c810310473dd73c26172/crates/cairo-lang-lowering/src/lower/context.rs#L327)):*
> ```XML
>     let block_id = scope.block_id;
>     match err {
>         LoweringFlowError::Failed(diag_added) => return Err(diag_added),
> ```

or doc why not possible.



_Suggestion:_
```XML
    match err {
        LoweringFlowError::Failed(diag_added) => return Err(diag_added),
        LoweringFlowError::Unreachable => {
            scope.unreachable(ctx);

        }
        LoweringFlowError::Return(return_var) => {
            scope.ret(ctx, return_var)?;
        }
        LoweringFlowError::Panic(data_var) => {
            scope.panic(ctx, data_var)?;
        }
    }
    Ok(SealedBlockBuilder::Ends(scope.block_id))
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2224)* status: all files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/fmt.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2224#-NOoIuje1xCc5nLZ901L:-NOsnsYA52pa44Il3r8V:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a09de02dbe59f0fdeed90cd8945cc332b4cb7dba/crates/cairo-lang-lowering/src/fmt.rs#L43)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this still does not answer the question about partial population debug printing.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 327 at r6](https://reviewable.io/reviews/starkware-libs/cairo/2224#-NOsg50s4k7XPR0WjH_r:-NOsn8b_CqAi0N9fz9cp:b-zb6s2k) ([raw file](https://github.com/starkware-libs/cairo/blob/472a8b7e1ce2c0421789c810310473dd73c26172/crates/cairo-lang-lowering/src/lower/context.rs#L327)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

or doc why not possible.
</blockquote></details>

ret/unreachable/panic consume the scope.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 104 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2224#-NOrnwZF81c1gbuJO3hk:-NOsqlSqDWwVgK2q7pxr:b-1xt36t) ([raw file](https://github.com/starkware-libs/cairo/blob/973280b7cddf4febd14a39c8c51ab0e6c5af2204/crates/cairo-lang-lowering/src/inline/mod.rs#L104)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Done.
</blockquote></details>

yeah, I was wrong.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 20 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2224)* status: 37 of 40 files reviewed, 3 unresolved discussions (waiting on @orizi, @spapinistarkware, and @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2224)* status: 37 of 40 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 104 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2224#-NOrnwZF81c1gbuJO3hk:-NOss52wC9Jg8KJ3TaFZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/973280b7cddf4febd14a39c8c51ab0e6c5af2204/crates/cairo-lang-lowering/src/inline/mod.rs#L104)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

yeah, I was wrong.
</blockquote></details>

Done.

**Review by orizi — DISMISSED** [review]
> Reviewed 2 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2224)* status: 39 of 40 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/fmt.rs` line 42 at r7](https://reviewable.io/reviews/starkware-libs/cairo/2224#-NOssA3B-IvN1pDO8Lc9:-NOssA3B-IvN1pDO8LcA:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/50088373f99f88d0c697faf68cbbecc931cf0bb5/crates/cairo-lang-lowering/src/fmt.rs#L42)):*
> ```XML
> impl DebugWithDb<LoweredFormatter<'_>> for StructuredBlock {
>     fn fmt(&self, f: &mut std::fmt::Formatter<'_>, ctx: &LoweredFormatter<'_>) -> std::fmt::Result {
>         if matches!(self.end, StructuredBlockEnd::NotSet) {
> ```





_Suggestion:_
```XML
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>, ctx: &LoweredFormatter<'_>) -> std::fmt::Result {
        if self.is_set() {
```
___
*[`crates/cairo-lang-lowering/src/test.rs` line 51 at r7](https://reviewable.io/reviews/starkware-libs/cairo/2224#-NOssIq-4VCnekyYoy2u:-NOssIq-4VCnekyYoy2v:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/50088373f99f88d0c697faf68cbbecc931cf0bb5/crates/cairo-lang-lowering/src/test.rs#L51)):*
> ```XML
>         db.priv_function_with_body_lowered_structured(test_function.function_id).unwrap();
>     if structured_lowered.blocks.iter().any(|(_, b)| !b.is_set()) {
>         panic!("There should not be any unset structured blocks");
> ```





_Suggestion:_
```XML
    assert!(structured_lowered.blocks.iter().all(|(_, b)| b.is_set()),
        "There should not be any unset structured blocks");
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2224)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @yuvalsw)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2224)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @yuvalsw)

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2224)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2224)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/fmt.rs` line 42 at r7](https://reviewable.io/reviews/starkware-libs/cairo/2224#-NOssA3B-IvN1pDO8Lc9:-NOt-4gd7MSyLuMcZp2a:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/50088373f99f88d0c697faf68cbbecc931cf0bb5/crates/cairo-lang-lowering/src/fmt.rs#L42)):*
> ```XML
> impl DebugWithDb<LoweredFormatter<'_>> for StructuredBlock {
>     fn fmt(&self, f: &mut std::fmt::Formatter<'_>, ctx: &LoweredFormatter<'_>) -> std::fmt::Result {
>         if matches!(self.end, StructuredBlockEnd::NotSet) {
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/test.rs` line 51 at r7](https://reviewable.io/reviews/starkware-libs/cairo/2224#-NOssIq-4VCnekyYoy2u:-NOszr2R6HJed_NxeYXt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/50088373f99f88d0c697faf68cbbecc931cf0bb5/crates/cairo-lang-lowering/src/test.rs#L51)):*
> ```XML
>         db.priv_function_with_body_lowered_structured(test_function.function_id).unwrap();
>     if structured_lowered.blocks.iter().any(|(_, b)| !b.is_set()) {
>         panic!("There should not be any unset structured blocks");
> ```

Done.

**Review by yuvalsw — COMMENTED** [review]
> Dismissed @ilyalesokhin-starkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2224)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2224)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 5 files at r5, 3 of 20 files at r6, 1 of 3 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2224)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 1 of 5 files at r5, 1 of 3 files at r7, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2224)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 16 of 37 files at r1, 1 of 5 files at r4, 13 of 20 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2224)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
