### PR TITLE
feat: make turbofish syntax for typed path optional

### LINKED ISSUE #1672: dev: generics type syntax contains turbofish
```
fn main() -> Option::<felt> {
    fib(1, 1, 13)
}

/// Calculates fib...
fn fib(a: felt, b: felt, n: felt) -> Option::<felt> {
    get_gas()?;
    match n {
        0 => Option::<felt>::Some(a),
        _ => fib(b, a + b, n - 1),
    }
}
```

I hate to bikeshed but the syntax looks weird with turbofish in type signatures. (Turbofish are expected in expressions though so that part’s fine.) Could it be changed to this for consistency with Rust:

```
fn main() -> Option<felt> {
    fib(1, 1, 13)
}

/// Calculates fib...
fn fib(a: felt, b: felt, n: felt) -> Option<felt> {
    get_gas()?;
    match n {
        0 => Option::<felt>::Some(a),
        _ => fib(b, a + b, n - 1),
    }
}
```

thank you

### PR DESCRIPTION
**Pull request by cwkang1998**
As per title, remove the need for turbofish syntax for typed path (generics).

Fixes  #1672

```rust
// This is valid
fn fib(a: felt, b: felt, n: felt) -> Option::<felt> {
    match n {
        0 => Option::<felt>::Some(a),
        _ => fib(b, a + b, n - 1),
    }
}

// This is now also valid
fn fib(a: felt, b: felt, n: felt) -> Option<felt> {
    match n {
        0 => Option::<felt>::Some(a),
        _ => fib(b, a + b, n - 1),
    }
}
```

Initially planning on removing turbofish syntax for typed path completely (Essentially making `Option::<felt>` and invalid syntax), however that will be breaking change that affects all current cairo code, so opted for an approach that allows the omission of `::` without causing a breaking change. Would love to hear some thoughts about this.

Also stumbled upon an interesting [old discussion](https://github.com/rust-lang/rfcs/pull/2544#issuecomment-453653184) of the turbofish syntax in the rust repo.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2289)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2289)* status: all files reviewed, 5 unresolved discussions (waiting on @cwkang1998)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1283 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2289#-NPHK4-REXdt3wVZp8tc:-NPHK4-REXdt3wVZp8td:bl13k5z) ([raw file](https://github.com/starkware-libs/cairo/blob/4c2cdf859f413c17f50796a2569bbd10708fdc93/crates/cairo-lang-parser/src/parser.rs#L1283)):*
> ```XML
>     fn parse_type_path(&mut self) -> ExprPathGreen {
>         let mut children: Vec<ExprPathElementOrSeparatorGreen> = vec![];
> ```

Remove blank line
___
*[`crates/cairo-lang-parser/src/parser.rs` line 1286 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2289#-NPHK6ac7YzpJ7qKLaC_:-NPHK6ac7YzpJ7qKLaCa:bl13k5z) ([raw file](https://github.com/starkware-libs/cairo/blob/4c2cdf859f413c17f50796a2569bbd10708fdc93/crates/cairo-lang-parser/src/parser.rs#L1286)):*
> ```XML
>         loop {
>             let (segment, optional_separator) = self.parse_type_path_segment();
> ```

Remove blank line
___
*[`crates/cairo-lang-parser/src/parser.rs` line 1670 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2289#-NPHKmZV6uawdTup5x1S:-NPHKmZV6uawdTup5x1T:btlmdha) ([raw file](https://github.com/starkware-libs/cairo/blob/4c2cdf859f413c17f50796a2569bbd10708fdc93/crates/cairo-lang-parser/src/parser.rs#L1670)):*
> ```XML
>             Some(self.take::<Terminal>())
>         } else {
>             None
> ```

Make sure you use formatting with the settings in this repo.
___
*[`crates/cairo-lang-parser/src/ppp1.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2289#-NPHKygX6cZ02cbAIhiI:-NPHKygX6cZ02cbAIhiJ:by97t53) ([raw file](https://github.com/starkware-libs/cairo/blob/4c2cdf859f413c17f50796a2569bbd10708fdc93/crates/cairo-lang-parser/src/ppp1.rs#L1)):*
> ```XML
> // #[cfg(test)]
> ```

Remove this file
___
*[`crates/cairo-lang-parser/test_data/cairo_files/test3.cairo` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2289#-NPHL2jiDjNWVL4zozz5:-NPHL2jiDjNWVL4zozz6:bot6wby) ([raw file](https://github.com/starkware-libs/cairo/blob/4c2cdf859f413c17f50796a2569bbd10708fdc93/crates/cairo-lang-parser/test_data/cairo_files/test3.cairo#L12)):*
> ```Cairo
>         _ => fib(b, a + b, n - 1),
>     }
> }
> ```

Add a newline at the end

**Review by spapinistarkware — COMMENTED** [review]
This is similar to rust, that also allows turbofish. I would opt to remove them in formatter, though.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2289#-:-NPI-O_z6dGGq8yQV48f:b-2mocx9)* status: all files reviewed, 5 unresolved discussions (waiting on @cwkang1998)

**Comment by cwkang1998** [comment]
Found an interesting behavior, when doing `./scripts/cairo_fmt.sh`, or `cargo run --bin cairo-format -- -r`, it correctly detects file in the `corelib/src` directory, but not the `crates/cairo-lang-parser/test_data/cairo_files/test3.cairo` directory.
Doing `cargo run --bin cairo-format ./crates/cairo-lang-parser/test_data/cairo_files/test3.cairo` does work as expected.

Is this intended behavior?

**Review by orizi — COMMENTED** [review]
yes - we have a `.cairofmtignore` in that directory in since we test files that have parsing errors (so these cannot be formatted)

> Reviewed 2 of 15 files at r1, 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2289#-:-NPINxJ28ovKGvESsavS:b-92lzm6)* status: 15 of 16 files reviewed, 5 unresolved discussions (waiting on @cwkang1998 and @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2289)* status: 15 of 16 files reviewed, 4 unresolved discussions (waiting on @cwkang1998)

**Review by cwkang1998 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2289)* status: 14 of 16 files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1283 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2289#-NPHK4-REXdt3wVZp8tc:-NPMk8-d3tCwLTpNjqgl:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/11401445e0ad9b0bad9ae9d9456102796efb5658/crates/cairo-lang-parser/src/parser.rs#L1283)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Remove blank line
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser.rs` line 1286 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2289#-NPHK6ac7YzpJ7qKLaC_:-NPMiSd80txRfGD4uysU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/11401445e0ad9b0bad9ae9d9456102796efb5658/crates/cairo-lang-parser/src/parser.rs#L1286)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Remove blank line
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/test_data/cairo_files/test3.cairo` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2289#-NPHL2jiDjNWVL4zozz5:-NPMk8wp8rqn6n_5ccva:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/11401445e0ad9b0bad9ae9d9456102796efb5658/crates/cairo-lang-parser/test_data/cairo_files/test3.cairo#L12)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Add a newline at the end
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/ppp1.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2289#-NPHKygX6cZ02cbAIhiI:-NPMk9zWAUDpRKuasCXp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/11401445e0ad9b0bad9ae9d9456102796efb5658/crates/cairo-lang-parser/src/ppp1.rs#L1)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Remove this file
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
note that if you are rebased we changed the relevant `.cairofmtignore` to include only the problematic files - so your file would now would be automatically fixed as well.

> Reviewed 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2289#-:-NPMsnSUAJBgtC0BNv4_:bufompa)* status: 15 of 16 files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 15 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2289#-:-NPMt-6QEMFZo5XuVcrn:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2289)* status: all files reviewed, 3 unresolved discussions (waiting on @cwkang1998)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1283 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2289#-NPHK4-REXdt3wVZp8tc:-NPNGkB88wT6noc9di5v:b-g3ft9j) ([raw file](https://github.com/starkware-libs/cairo/blob/11401445e0ad9b0bad9ae9d9456102796efb5658/crates/cairo-lang-parser/src/parser.rs#L1283)):*
<details><summary><i>Previously, cwkang1998 (Chen Wen Kang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The empty line is still here
___
*[`crates/cairo-lang-parser/src/parser.rs` line 1286 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2289#-NPHK6ac7YzpJ7qKLaC_:-NPNGmuLBVPuVW4tQNer:b-g3ft9j) ([raw file](https://github.com/starkware-libs/cairo/blob/11401445e0ad9b0bad9ae9d9456102796efb5658/crates/cairo-lang-parser/src/parser.rs#L1286)):*
<details><summary><i>Previously, cwkang1998 (Chen Wen Kang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The empty line is still here
___
*[`crates/cairo-lang-parser/test_data/cairo_files/test3.cairo` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2289#-NPHL2jiDjNWVL4zozz5:-NPNGq8-AgMSWZ_AkpiZ:bmj24ss) ([raw file](https://github.com/starkware-libs/cairo/blob/11401445e0ad9b0bad9ae9d9456102796efb5658/crates/cairo-lang-parser/test_data/cairo_files/test3.cairo#L12)):*
<details><summary><i>Previously, cwkang1998 (Chen Wen Kang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It's still here

**Review by cwkang1998 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2289)* status: 14 of 16 files reviewed, 3 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-parser/test_data/cairo_files/test3.cairo` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2289#-NPHL2jiDjNWVL4zozz5:-NPNRiXV6eup_wVyXCPS:b-niqae7) ([raw file](https://github.com/starkware-libs/cairo/blob/11401445e0ad9b0bad9ae9d9456102796efb5658/crates/cairo-lang-parser/test_data/cairo_files/test3.cairo#L12)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

It's still here
</blockquote></details>

Weird, locally there's a line, but for some reason its not being registered with git.

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2289)* status: 15 of 16 files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/cairo-lang-parser/test_data/cairo_files/test3.cairo` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2289#-NPHL2jiDjNWVL4zozz5:-NPNXEDk1kadDCVfWMUD:bs3caye) ([raw file](https://github.com/starkware-libs/cairo/blob/11401445e0ad9b0bad9ae9d9456102796efb5658/crates/cairo-lang-parser/test_data/cairo_files/test3.cairo#L12)):*
<details><summary><i>Previously, cwkang1998 (Chen Wen Kang) wrote…</i></summary><blockquote>

Weird, locally there's a line, but for some reason its not being registered with git. 
</blockquote></details>

Now it's ok

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2289#-:-NPNXJzo5bzHJv0j8KNR:bnfp4nl)* status: 15 of 16 files reviewed, all discussions resolved (waiting on @orizi)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r2, 1 of 1 files at r3, 1 of 2 files at r4, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2289)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @cwkang1998)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2289)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cwkang1998)

**Pull request merged**
