### PR TITLE
Add box trait, and hide box extern functions.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2513)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 13 of 13 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2513#-:-NQawXcU-gMHv_sW8bQx:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`corelib/src/box.cairo` line 5 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2513#-NQavCY09-IQpjCF6149:-NQavCY09-IQpjCF614A:brplk08) ([raw file](https://github.com/starkware-libs/cairo/blob/9e8a14faf7914d53ee619f6f820aad589021e55d/corelib/src/box.cairo#L5)):*
> ```Cairo
> impl BoxTDrop<T, impl TDrop: Drop::<T>> of Drop::<Box::<T>>;
> 
> extern fn into_box<T>(value: T) -> Box<T> nopanic;
> ```

add a doc + TODO above these.



_Code quote:_
```Cairo
extern fn into_box<T>(value: T) -> Box<T> nopanic;
extern fn unbox<T>(box: Box<T>) -> T nopanic;
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2513)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/box.cairo` line 5 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2513#-NQavCY09-IQpjCF6149:-NQdSnWAEHHRc-uEPKzx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9e8a14faf7914d53ee619f6f820aad589021e55d/corelib/src/box.cairo#L5)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add a doc + TODO above these.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2513#-:-NQdYCg46nuY6VYwWd8l:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`corelib/src/box.cairo` line 7 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2513#-NQdY9GS6glluv_Xo5HQ:-NQdY9GS6glluv_Xo5HR:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6857075878db8debcb64c84a453623c6a383c485/corelib/src/box.cairo#L7)):*
> ```Cairo
> // These functions are only exposed in the corelib through the trait below since calling them
> // directly with tuples panics due to auto unpacking of the tuple.
> // TODO(Gil): Expose in the core lib when the described behaviour is fixed.  
> ```





_Suggestion:_
```Cairo
.
```

**Review by orizi — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2513)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2513)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/box.cairo` line 7 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2513#-NQdY9GS6glluv_Xo5HQ:-NQdhvcCEtsoK4le92gK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6857075878db8debcb64c84a453623c6a383c485/corelib/src/box.cairo#L7)):*
> ```Cairo
> // These functions are only exposed in the corelib through the trait below since calling them
> // directly with tuples panics due to auto unpacking of the tuple.
> // TODO(Gil): Expose in the core lib when the described behaviour is fixed.  
> ```

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2513)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
