### PR TITLE
Add `compile_prepared_db_program_artifact` (will be used by Scarb)

### PR DESCRIPTION
**Pull request by piotmag769**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5333)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5333)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5333#-Ntzj_gt8QUfkobzXcwk:-Ntzj_guCZg2w_5-5q2-:b-cc6yta) (no related file):*
@mkaput aware of additional users?

___

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5333)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mkaput and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5333#-Ntzj_gt8QUfkobzXcwk:-NtzoSW5BFEb-Q4T4IYT:b61p8sb) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

@mkaput aware of additional users?
</blockquote></details>

@mkaput is mostly OOF today (and until the end of the week), so he may not review it soon

___

**Review by mkaput — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5333)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi and @piotmag769)

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5333)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-compiler/src/lib.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5333#-Nu-1_mx8YqsBIyNiTj2:-Nu-4lND1bLesdTssCE-:b96wgqy) ([raw file](https://github.com/starkware-libs/cairo/blob/dcf8a9a4024ca1a722d7a015a14c4fe22d060e5a/crates/cairo-lang-compiler/src/lib.rs#L130)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

blocking here instead.
</blockquote></details>

Yup I am, but it was ignored in Scarb anyways. I will add a wrapper function then, didn't know that someone else was using this function.

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5333)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-compiler/src/lib.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5333#-Nu-1_mx8YqsBIyNiTj2:-Nu-cdgH3M5ssNw7F-fo:bj8xwn6) ([raw file](https://github.com/starkware-libs/cairo/blob/dcf8a9a4024ca1a722d7a015a14c4fe22d060e5a/crates/cairo-lang-compiler/src/lib.rs#L130)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Yup I am, but it was ignored in Scarb anyways. I will add a wrapper function then, didn't know that someone else was using this function.
</blockquote></details>

Now that it is in a separate function losing the debug info won't be a problem

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5333#-:-Nu-e9SrCu4MvPVnowrY:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)

**Pull request merged**
