### PR TITLE
Pass ids of crates to find test in to the TestRunner

### PR DESCRIPTION
**Pull request by maciektr**
Instead of searching for tests in all dependencies, we should be able to pass crate ids to use.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3924)

### CODE REVIEW

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3924#-:-Nc1HIt-6en24AR77zAR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3924)* status: all files reviewed, 1 unresolved discussion (waiting on @maciektr)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3924#-Nc1JiYz8sb7n9zkgTvN:-Nc1JiYz8sb7n9zkgTvO:b-k7njd8) (no related file):*
Did previously projects dependent on other ran both test suites?

___

**Comment by maciektr** [comment]
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Did previously projects dependent on other ran both test suites?
</blockquote></details>

Hi @orizi!

If you setup your project via `cairo_project.toml` file and use the test runner cli then yes, it runs tests in all crates. You can filter them out by name prefix. **This PR does not change this behaviour.**

In Scarb we currently only pass the id of the crate that we want to test as `main_crate_ids`. As a effect, we do not run tests from dependencies. However, this approach is flawed - the test runner only compiles contracts from the crates identified by `main_crate_ids` (see https://github.com/software-mansion/scarb/discussions/568 as an example of why it is a problem). 

By introducing this change, we want to allow users who build upon the Test runner to decide which crates should be only compiled, and which searched for tests.

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3924#-:-Nc1lLH-4wvdZK5cjcwA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciektr)

**Pull request merged**
