### PR TITLE
Hide array libfuncs calls and use ArrayTrait where possible.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2517)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2517)* status: 0 of 30 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2517#-NQdyWVe2NHNP8im5Bgl:-NQdyWVe2NHNP8im5Bgm:b-l6u88n) (no related file):*
rebase

___

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 12 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2517)* status: 12 of 30 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/inference` line 52 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2517#-NQdzEzM6wwakQhLGx3z:-NQdzEzM6wwakQhLGx4-:bg0ic9z) ([raw file](https://github.com/starkware-libs/cairo/blob/4d7aa2cab31fb40178a71c74ded35ef88daf6e1c/crates/cairo-lang-semantic/src/expr/test_data/inference#L52)):*
> ```
> fn foo() {
>    let mut arr = ArrayTrait::new();
>    arr.append(arr);
> ```

use array::array_append

to keep the meaning of the test.



_Code quote:_
```
   let mut arr = ArrayTrait::new();
   arr.append(arr);
```
___
*[`crates/cairo-lang-semantic/src/expr/test_data/inference` line 81 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2517#-NQdzaeE5qRmkFVHr5pC:-NQdzaeE5qRmkFVHr5pD:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/4d7aa2cab31fb40178a71c74ded35ef88daf6e1c/crates/cairo-lang-semantic/src/expr/test_data/inference#L81)):*
> ```
> //! > function
> fn foo() {
>     let mut arr = array_new();
> ```





_Suggestion:_
```
fn foo() {
    let mut arr = ArrayTrait::new();
```
___
*[`crates/cairo-lang-semantic/src/expr/test_data/inference` line 127 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2517#-NQdzhuU8_Jy8lBGoUXX:-NQdzhuU8_Jy8lBGoUXY:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/4d7aa2cab31fb40178a71c74ded35ef88daf6e1c/crates/cairo-lang-semantic/src/expr/test_data/inference#L127)):*
> ```
> //! > function
> fn foo() -> felt252 {
>     panic(array_new())
> ```





_Suggestion:_
```
fn foo() -> felt252 {
    panic(array::array_new())
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2517)* status: 16 of 30 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contract` line 52 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2517#-NQe-5QP8whB5TRUOjc1:-NQe-5QP8whB5TRUOjc2:bvw1gnn) ([raw file](https://github.com/starkware-libs/cairo/blob/4d7aa2cab31fb40178a71c74ded35ef88daf6e1c/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contract#L52)):*
> ```
>     #[l1_handler]
>     fn l1_handler_func(arg: felt252, num: felt252) {}
> ```

rerun with FIX as there are some new spaces.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2517)* status: 17 of 30 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2517)* status: 6 of 37 files reviewed, 5 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2517#-NQdyWVe2NHNP8im5Bgl:-NQeE5ZU9uV6Y1BY6Af5:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rebase
</blockquote></details>

Done.

___
___
*[`crates/cairo-lang-semantic/src/expr/test_data/inference` line 52 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2517#-NQdzEzM6wwakQhLGx3z:-NQe2Z2cBM55-LYG3vO1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4d7aa2cab31fb40178a71c74ded35ef88daf6e1c/crates/cairo-lang-semantic/src/expr/test_data/inference#L52)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

use array::array_append

to keep the meaning of the test.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/inference` line 81 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2517#-NQdzaeE5qRmkFVHr5pC:-NQe2yOv7HnG81ZIiT2h:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4d7aa2cab31fb40178a71c74ded35ef88daf6e1c/crates/cairo-lang-semantic/src/expr/test_data/inference#L81)):*
> ```
> //! > function
> fn foo() {
>     let mut arr = array_new();
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/inference` line 127 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2517#-NQdzhuU8_Jy8lBGoUXX:-NQe2yov-yQAwBOlxS2m:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4d7aa2cab31fb40178a71c74ded35ef88daf6e1c/crates/cairo-lang-semantic/src/expr/test_data/inference#L127)):*
> ```
> //! > function
> fn foo() -> felt252 {
>     panic(array_new())
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contract` line 52 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2517#-NQe-5QP8whB5TRUOjc1:-NQeCy9T4L4z4IOrGIZO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4d7aa2cab31fb40178a71c74ded35ef88daf6e1c/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contract#L52)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rerun with FIX as there are some new spaces.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 30 files at r1, 29 of 30 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2517#-:-NQeEwiY6QLthi4xPm8k:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
