### PR TITLE
Add Short string literals doc.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2683)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2683)* status: all files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @liorgold2)

___
*[`docs/reference/src/literal-expressions.adoc` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2683#-NS19vQ7CEXLSE5rayhj:-NS19vQ7CEXLSE5rayhk:b-ps32kg) ([raw file](https://github.com/starkware-libs/cairo/blob/2988432286b907d82b7cc7f023c50ad4f6d7366a/docs/reference/src/literal-expressions.adoc#L14)):*
> ```AsciiDoc
> by name or some other evaluation rule.
> 
> == Boolean literals
> ```

can you please align the order? (what's first - bool or numeric?)
___
*[`docs/reference/src/literal-expressions.adoc` line 82 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2683#-NS18WYeB-LhHpK7lPnW:-NS18WYfDn0r2V3R6Q02:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2988432286b907d82b7cc7f023c50ad4f6d7366a/docs/reference/src/literal-expressions.adoc#L82)):*
> ```AsciiDoc
> 
> A short string is a ascii-string whose length is limited by the type that holds it.
> The default type is a felt which limit the length of the string to 31 characters.
> ```





_Suggestion:_
```AsciiDoc
 `felt252` which limits the length of the string to 31 characters.
```
___
*[`docs/reference/src/literal-expressions.adoc` line 87 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2683#-NS18xmwD8Hs3zH0g4Xm:-NS18xmx4QfR8JQhIbkN:b2efh27) ([raw file](https://github.com/starkware-libs/cairo/blob/2988432286b907d82b7cc7f023c50ad4f6d7366a/docs/reference/src/literal-expressions.adoc#L87)):*
> ```AsciiDoc
> 
> Examples of numeric literals of various forms:
> [source]
> ```

Suggestion, to be consistent with the invalid examples above



_Suggestion:_
```AsciiDoc
Examples of short string literals:
- `'short_string'`
- `'short_string'_u128`
- `'a'_u8`
```
___
*[`docs/reference/src/literal-expressions.adoc` line 97 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2683#-NS19eb82LhCDHkdLGqi:-NS19eb82LhCDHkdLGqj:b-gmcgvm) ([raw file](https://github.com/starkware-libs/cairo/blob/2988432286b907d82b7cc7f023c50ad4f6d7366a/docs/reference/src/literal-expressions.adoc#L97)):*
> ```AsciiDoc
> It is important to note that a short-string is simply a way to represent a field element,
> it's not a real string.
> Cairo doesn't support strings at the moment, and when it does, strings will be represented using
> ```

I think we decided not to mention stuff that should exist in the future. It is OK though to mention that string are currently not supported.



_Code quote:_
```AsciiDoc
Cairo doesn't support strings at the moment, and when it does, strings will be represented using
``"`` rather than ``'``.
```
___
*[`docs/reference/src/literal-expressions.adoc` line 100 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2683#-NS19UlUCxKIiSLV56Oz:-NS19UlUCxKIiSLV56P-:b-ajt5tc) ([raw file](https://github.com/starkware-libs/cairo/blob/2988432286b907d82b7cc7f023c50ad4f6d7366a/docs/reference/src/literal-expressions.adoc#L100)):*
> ```AsciiDoc
> ``"`` rather than ``'``.
> 
> The string's first character is the most significant byte of the integer (big endian
> ```

IIRC Lior mentioned there is an explanation about it. Can you please link it from here?



_Suggestion:_
```AsciiDoc
The short string's first character is the most significant byte of the integer (big endian
representation).
```

**Comment by ilyalesokhin-starkware** [comment]
*[`docs/reference/src/literal-expressions.adoc` line 87 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2683#-NS18xmwD8Hs3zH0g4Xm:-NS1EwaN6_EGItUW5_bc:b5gvjss) ([raw file](https://github.com/starkware-libs/cairo/blob/2988432286b907d82b7cc7f023c50ad4f6d7366a/docs/reference/src/literal-expressions.adoc#L87)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Suggestion, to be consistent with the invalid examples above
</blockquote></details>

What is the benefit of adding \`?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2683)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @liorgold2 and @yuvalsw)

___
*[`docs/reference/src/literal-expressions.adoc` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2683#-NS19vQ7CEXLSE5rayhj:-NS1EdXD-J8d8uJ_OqDI:b-71j7al) ([raw file](https://github.com/starkware-libs/cairo/blob/2988432286b907d82b7cc7f023c50ad4f6d7366a/docs/reference/src/literal-expressions.adoc#L14)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

can you please align the order? (what's first - bool or numeric?)
</blockquote></details>

I decided to remove the ebnf.
___
*[`docs/reference/src/literal-expressions.adoc` line 97 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2683#-NS19eb82LhCDHkdLGqi:-NS1FiIj2JUckL47llXZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2988432286b907d82b7cc7f023c50ad4f6d7366a/docs/reference/src/literal-expressions.adoc#L97)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I think we decided not to mention stuff that should exist in the future. It is OK though to mention that string are currently not supported.
</blockquote></details>

Done.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2683)* status: all files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @liorgold2)

___
*[`docs/reference/src/literal-expressions.adoc` line 82 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2683#-NS18WYeB-LhHpK7lPnW:-NS1IJ2e4IFUG4cKRDFK:bzd7fr) ([raw file](https://github.com/starkware-libs/cairo/blob/2988432286b907d82b7cc7f023c50ad4f6d7366a/docs/reference/src/literal-expressions.adoc#L82)):*
> ```AsciiDoc
> 
> A short string is a ascii-string whose length is limited by the type that holds it.
> The default type is a felt which limit the length of the string to 31 characters.
> ```

please add `` to wrap felt252
___
*[`docs/reference/src/literal-expressions.adoc` line 87 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2683#-NS18xmwD8Hs3zH0g4Xm:-NS1IRfM4CFgIoWtyivV:b-223bk6) ([raw file](https://github.com/starkware-libs/cairo/blob/2988432286b907d82b7cc7f023c50ad4f6d7366a/docs/reference/src/literal-expressions.adoc#L87)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

What is the benefit of adding \`?
</blockquote></details>

I meant to remove the "[source]" and "----"s. This way it shows them as bullets.

the added `` marks this as code, which looks nicer and clearer. Also - generally - prevents adoc special characters rendering (at least sometimes).
___
*[`docs/reference/src/literal-expressions.adoc` line 100 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2683#-NS19UlUCxKIiSLV56Oz:-NS1KCez4EXzO9D1AfOh:b9mnlt3) ([raw file](https://github.com/starkware-libs/cairo/blob/2988432286b907d82b7cc7f023c50ad4f6d7366a/docs/reference/src/literal-expressions.adoc#L100)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

IIRC Lior mentioned there is an explanation about it. Can you please link it from here?
</blockquote></details>

Can you please add a link?
___
*[`docs/reference/src/literal-expressions.adoc` line 6 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2683#-NS1Hli223q2Ds9Iw22z:-NS1Hli223q2Ds9Iw23-:b-1p5pv6) ([raw file](https://github.com/starkware-libs/cairo/blob/a8359589c63fb6c07b67a510566d9fdf17a059cb/docs/reference/src/literal-expressions.adoc#L6)):*
> ```AsciiDoc
> tokens, that immediately and directly denotes the value it evaluates to, rather than referring to it
> by name or some other evaluation rule.
> There are there kinds of literal expressions.
> ```

three.
Or 3.
Or simple 'some'/"these are the kind of ...". This ensures it remains true if we add a kind.

Also - please add a linebreak before this line.



_Code quote:_
```AsciiDoc
there
```
___
*[`docs/reference/src/literal-expressions.adoc` line 10 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2683#-NS1I6bPB4ZZKdXIUlwh:-NS1I6bPB4ZZKdXIUlwi:b-kgb0bj) ([raw file](https://github.com/starkware-libs/cairo/blob/a8359589c63fb6c07b67a510566d9fdf17a059cb/docs/reference/src/literal-expressions.adoc#L10)):*
> ```AsciiDoc
> == Boolean literals
> 
> The two values of the boolean type are written `true` and `false`.
> ```

this is also mentioned in Gil's boolean page. Can you please talk to see if it should be only in one or in both?
___
*[`docs/reference/src/literal-expressions.adoc` line 20 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2683#-NS1J8jU-IUQiXhN9q15:-NS1J8jV7EDFQcx0Ve1w:b3i0nrd) ([raw file](https://github.com/starkware-libs/cairo/blob/a8359589c63fb6c07b67a510566d9fdf17a059cb/docs/reference/src/literal-expressions.adoc#L20)):*
> ```AsciiDoc
> == Numeric literals
> 
> A numeric literal can be written using three bases:
> ```

This is not true anymore. Exactly gives an example of my point above :)
I'd write: "A numeric literal can be written in one of the following bases:"



_Code quote:_
```AsciiDoc
three
```
___
*[`docs/reference/src/literal-expressions.adoc` line 56 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2683#-NS1Jeo15zhBwmCng7oa:-NS1Jeo15zhBwmCng7ob:bamln1u) ([raw file](https://github.com/starkware-libs/cairo/blob/a8359589c63fb6c07b67a510566d9fdf17a059cb/docs/reference/src/literal-expressions.adoc#L56)):*
> ```AsciiDoc
> > single numeric literal.
> 
> == Short string literals
> ```

Capital letters in headings.



_Code quote:_
```AsciiDoc
Short string literals
```
___
*[`docs/reference/src/literal-expressions.adoc` line 73 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2683#-NS1In8XCTjFVj3hZfPw:-NS1In8XCTjFVj3hZfPx:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a8359589c63fb6c07b67a510566d9fdf17a059cb/docs/reference/src/literal-expressions.adoc#L73)):*
> ```AsciiDoc
> 
> It is important to note that a short-string is not really
> a string type. it is a way to encode a string as a numerical value.
> ```





_Suggestion:_
```AsciiDoc
It is 
```

**Comment by ilyalesokhin-starkware** [comment]
*[`docs/reference/src/literal-expressions.adoc` line 100 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2683#-NS19UlUCxKIiSLV56Oz:-NS1KnzKABZ6DPn35K6Z:b-wv4a6m) ([raw file](https://github.com/starkware-libs/cairo/blob/2988432286b907d82b7cc7f023c50ad4f6d7366a/docs/reference/src/literal-expressions.adoc#L100)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Can you please add a link?
</blockquote></details>

https://github.com/starkware-industries/starkware/blob/bb97613588253d78c57fffd5be8bcda12c2d48f9/src/starkware/cairo/docs/how_cairo_works/consts.rst#L47

I didn't see an explantaion.

**Comment by ilyalesokhin-starkware** [comment]
*[`docs/reference/src/literal-expressions.adoc` line 87 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2683#-NS18xmwD8Hs3zH0g4Xm:-NS1LmLT-8WQQLU7RoCO:b-824zqt) ([raw file](https://github.com/starkware-libs/cairo/blob/2988432286b907d82b7cc7f023c50ad4f6d7366a/docs/reference/src/literal-expressions.adoc#L87)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I meant to remove the "[source]" and "----"s. This way it shows them as bullets.

the added `` marks this as code, which looks nicer and clearer. Also - generally - prevents adoc special characters rendering (at least sometimes).
</blockquote></details>

it puts all of them in one line
Examples of short string literals: - 'short_string' - 'short_string'_u128 - 'a'_u8

**Comment by ilyalesokhin-starkware** [comment]
*[`docs/reference/src/literal-expressions.adoc` line 56 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2683#-NS1Jeo15zhBwmCng7oa:-NS1PmrdE8TFZUqIUbBk:b7dmmec) ([raw file](https://github.com/starkware-libs/cairo/blob/a8359589c63fb6c07b67a510566d9fdf17a059cb/docs/reference/src/literal-expressions.adoc#L56)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Capital letters in headings.
</blockquote></details>

== Numeric literals
is also not capiatlized.

**Comment by ilyalesokhin-starkware** [comment]
*[`docs/reference/src/literal-expressions.adoc` line 73 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2683#-NS1In8XCTjFVj3hZfPw:-NS1Qded5KoU200jPExQ:b-nlf0hx) ([raw file](https://github.com/starkware-libs/cairo/blob/a8359589c63fb6c07b67a510566d9fdf17a059cb/docs/reference/src/literal-expressions.adoc#L73)):*
> ```AsciiDoc
> 
> It is important to note that a short-string is not really
> a string type. it is a way to encode a string as a numerical value.
> ```

rephrased.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2683)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @liorgold2 and @yuvalsw)

___
*[`docs/reference/src/literal-expressions.adoc` line 82 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2683#-NS18WYeB-LhHpK7lPnW:-NS1Q74y5kvo6G37yQHM:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/2988432286b907d82b7cc7f023c50ad4f6d7366a/docs/reference/src/literal-expressions.adoc#L82)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

please add `` to wrap felt252
</blockquote></details>

done
___
*[`docs/reference/src/literal-expressions.adoc` line 6 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2683#-NS1Hli223q2Ds9Iw22z:-NS1P1a7C70Wpnm_Yuv2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a8359589c63fb6c07b67a510566d9fdf17a059cb/docs/reference/src/literal-expressions.adoc#L6)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

three.
Or 3.
Or simple 'some'/"these are the kind of ...". This ensures it remains true if we add a kind.

Also - please add a linebreak before this line.
</blockquote></details>

Done.
___
*[`docs/reference/src/literal-expressions.adoc` line 10 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2683#-NS1I6bPB4ZZKdXIUlwh:-NS1Qa4q0A8opHAcybdL:ba9scay) ([raw file](https://github.com/starkware-libs/cairo/blob/a8359589c63fb6c07b67a510566d9fdf17a059cb/docs/reference/src/literal-expressions.adoc#L10)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

this is also mentioned in Gil's boolean page. Can you please talk to see if it should be only in one or in both?
</blockquote></details>

gils docs is not merged yet.
___
*[`docs/reference/src/literal-expressions.adoc` line 20 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2683#-NS1J8jU-IUQiXhN9q15:-NS1PhOb9l_jHqIfikLl:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/a8359589c63fb6c07b67a510566d9fdf17a059cb/docs/reference/src/literal-expressions.adoc#L20)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

This is not true anymore. Exactly gives an example of my point above :)
I'd write: "A numeric literal can be written in one of the following bases:"
</blockquote></details>

done

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2683)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @liorgold2)

___
*[`docs/reference/src/literal-expressions.adoc` line 87 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2683#-NS18xmwD8Hs3zH0g4Xm:-NS1fyok2yMA-A2ww2Q3:bmi8y8g) ([raw file](https://github.com/starkware-libs/cairo/blob/2988432286b907d82b7cc7f023c50ad4f6d7366a/docs/reference/src/literal-expressions.adoc#L87)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it puts all of them in one line
Examples of short string literals: - 'short_string' - 'short_string'_u128 - 'a'_u8
</blockquote></details>

Add one empty line before the list. See example above in "Examples of invalid numeric literals".
___
*[`docs/reference/src/literal-expressions.adoc` line 100 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2683#-NS19UlUCxKIiSLV56Oz:-NS1gkZR8CJxyyqvC_QD:b32w0x) ([raw file](https://github.com/starkware-libs/cairo/blob/2988432286b907d82b7cc7f023c50ad4f6d7366a/docs/reference/src/literal-expressions.adoc#L100)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

https://github.com/starkware-industries/starkware/blob/bb97613588253d78c57fffd5be8bcda12c2d48f9/src/starkware/cairo/docs/how_cairo_works/consts.rst#L47

I didn't see an explantaion.
</blockquote></details>

OK
___
*[`docs/reference/src/literal-expressions.adoc` line 10 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2683#-NS1I6bPB4ZZKdXIUlwh:-NS1fJ2F5_lENPLJ78Re:b-a3ohq1) ([raw file](https://github.com/starkware-libs/cairo/blob/a8359589c63fb6c07b67a510566d9fdf17a059cb/docs/reference/src/literal-expressions.adoc#L10)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

gils docs is not merged yet.
</blockquote></details>

This is why I think you should discuss and decide.
___
*[`docs/reference/src/literal-expressions.adoc` line 23 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2683#-NS1fgNFBv9EyZ073HAo:-NS1fgNFBv9EyZ073HAp:b-nkw6sc) ([raw file](https://github.com/starkware-libs/cairo/blob/77dc33a4aa444709b7ee523f367b6709cc9f665a/docs/reference/src/literal-expressions.adoc#L23)):*
> ```AsciiDoc
> == Numeric Literals
> 
> Cairo supports the following numeric literal:
> ```

literals/literal types/literal bases



_Code quote:_
```AsciiDoc
the following numeric literal:
```
___
*[`docs/reference/src/literal-expressions.adoc` line 25 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2683#-NS1f_vo7E9L8XnPUIHL:-NS1f_vo7E9L8XnPUIHM:b-1lpfpx) ([raw file](https://github.com/starkware-libs/cairo/blob/77dc33a4aa444709b7ee523f367b6709cc9f665a/docs/reference/src/literal-expressions.adoc#L25)):*
> ```AsciiDoc
> Cairo supports the following numeric literal:
> 1. A decimal literal that consists of only decimal digits.
> 2. A hexadecimal literal starts with the character sequence `0x` and continues with hex digits.
> ```

either both with "that": "that starts", or both without it.



_Code quote:_
```AsciiDoc
1. A decimal literal that consists of only decimal digits.
2. A hexadecimal literal starts with the character sequence `0x` and continues with hex digits.
```

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2683)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @liorgold2)

**Comment by ilyalesokhin-starkware** [comment]
*[`docs/reference/src/literal-expressions.adoc` line 10 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2683#-NS1I6bPB4ZZKdXIUlwh:-NS5k1rn92j7mh4gDCQI:b-ern3a6) ([raw file](https://github.com/starkware-libs/cairo/blob/a8359589c63fb6c07b67a510566d9fdf17a059cb/docs/reference/src/literal-expressions.adoc#L10)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

This is why I think you should discuss and decide.
</blockquote></details>

I'm not sure what is the suggestion, do you want to remove this section?

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2683)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @liorgold2)

___
*[`docs/reference/src/literal-expressions.adoc` line 10 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2683#-NS1I6bPB4ZZKdXIUlwh:-NS5mbMXESOxkDGizr_q:bc6biip) ([raw file](https://github.com/starkware-libs/cairo/blob/a8359589c63fb6c07b67a510566d9fdf17a059cb/docs/reference/src/literal-expressions.adoc#L10)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I'm not sure what is the suggestion, do you want to remove this section?
</blockquote></details>

I just wanted you to decide if it's better to repeat in both, put only here or only there...

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2683)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @yuvalsw)

___
*[`docs/reference/src/literal-expressions.adoc` line 10 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2683#-NS1I6bPB4ZZKdXIUlwh:-NSZlSpvENNdecqPNrXH:b-blzsbn) ([raw file](https://github.com/starkware-libs/cairo/blob/a8359589c63fb6c07b67a510566d9fdf17a059cb/docs/reference/src/literal-expressions.adoc#L10)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I just wanted you to decide if it's better to repeat in both, put only here or only there...
</blockquote></details>

talked to gil, he said its ok.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2683#-:-NS_a4z6AmHotPk6OQd_:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @liorgold2)

___
*[`docs/reference/src/cairo/modules/ROOT/pages/literal-expressions.adoc` line 24 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2683#-NS__d6X8et_-9UoJdsy:-NS__d6X8et_-9UoJdsz:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/945f040b35c4bfef2446e8747c3c4b168f536482/docs/reference/src/cairo/modules/ROOT/pages/literal-expressions.adoc#L24)):*
> ```AsciiDoc
> 1. A decimal literal that consists of only decimal digits.
> 2. A hexadecimal literal that start with the character sequence `0x` and continues with hex digits.
> 3. Binary literal that start with the character sequence `0b` and continues with binary digits.
> ```





_Suggestion:_
```AsciiDoc
3. A binary literal that start with the character sequence `0b` and continues with binar
```
___
*[`docs/reference/src/cairo/modules/ROOT/pages/literal-expressions.adoc` line 40 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2683#-NS__sPQ0TAWyadvxSng:-NS__sPQ0TAWyadvxSnh:bvhk50t) ([raw file](https://github.com/starkware-libs/cairo/blob/945f040b35c4bfef2446e8747c3c4b168f536482/docs/reference/src/cairo/modules/ROOT/pages/literal-expressions.adoc#L40)):*
> ```AsciiDoc
> | `1234`                  | 1234  | `felt252`
> | `1234_felt252           | 1234  | `felt252`
> | `1234_i32               | 1234  | `i32`
> ```

we don't have i32
___
*[`docs/reference/src/cairo/modules/ROOT/pages/literal-expressions.adoc` line 43 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2683#-NS__htx14wjzOmBO0ZT:-NS__htx14wjzOmBO0ZU:b-60gkdo) ([raw file](https://github.com/starkware-libs/cairo/blob/945f040b35c4bfef2446e8747c3c4b168f536482/docs/reference/src/cairo/modules/ROOT/pages/literal-expressions.adoc#L43)):*
> ```AsciiDoc
> | `1234_u128              | 1234  | `u128`
> | `0x4D2`                 | 1234  | `felt252`
> | `0b0000010011010010` | 1234  | `felt252`
> ```

please align

**Pull request merged**
