### PR TITLE
Add self to ABI

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3051)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3042** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3042" target="_blank">Graphite</a> 
    * **PR #3044** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3044" target="_blank">Graphite</a> 
      * **PR #3045** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3045" target="_blank">Graphite</a> 
        * **PR #3050** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3050" target="_blank">Graphite</a> 
          * **PR #3051** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3051" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/3051?utm_source=stack-comment).

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 15 files at r1, 9 of 32 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3051)* status: 11 of 35 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/abi.rs` line 88 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3051#-NWgrTGg2nDv_nxNelM8:-NWgrTGg2nDv_nxNelM9:b-5qua6r) ([raw file](https://github.com/starkware-libs/cairo/blob/a458aa38e9134f045f5d266e45e3113fc2c45399/crates/cairo-lang-starknet/src/abi.rs#L88)):*
> ```XML
>             return Err(ABIError::EntrypointMustHaveSelf);
>         }
>         // TODO(spapini): Check the first param type.
> ```

is this too complex to do this time?



_Code quote:_
```XML
// TODO(spapini): Check the first param type.
```
___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 42 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3051#-NWgsob0DTPMvF0weeWb:-NWgsob0DTPMvF0weeWc:b-1w1au1) ([raw file](https://github.com/starkware-libs/cairo/blob/a458aa38e9134f045f5d266e45e3113fc2c45399/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L42)):*
> ```XML
>     let mut library_caller_method_impls = vec![];
>     let base_name = trait_ast.name(db).text(db);
>     let dispatcher_name = format!("{base_name}DispatcherTrait");
> ```

can you delete this and use the abi trait now?



_Code quote:_
```XML
    let dispatcher_name = format!("{base_name}DispatcherTrait");
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3051)* status: 11 of 35 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contract` line 141 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3051#-NWgtZN66UX8s1nh2SmT:-NWgtZN66UX8s1nh2SmU:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/a458aa38e9134f045f5d266e45e3113fc2c45399/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contract#L141)):*
> ```
> 
> 
> trait __abi<Storage> {
> ```

.



_Suggestion:_
```
trait __abi<State> {
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3051)* status: 11 of 35 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contract` line 141 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3051#-NWgtZN66UX8s1nh2SmT:-NWgzFm56ZxINhIJFmxV:b-60x8q6) ([raw file](https://github.com/starkware-libs/cairo/blob/a458aa38e9134f045f5d266e45e3113fc2c45399/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contract#L141)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

This is a big change. This is the same struct as Storage today.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 15 files at r1, 21 of 32 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3051)* status: 33 of 35 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 32 files at r3, 7 of 17 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3051)* status: 30 of 40 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/abi.rs` line 109 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3051#-NWhBgMZ1zOULoqc3-56:-NWhBgMZ1zOULoqc3-57:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/eb97fd9988e9b9bd0d057aef9ac8b4911bdc3297/crates/cairo-lang-starknet/src/abi.rs#L109)):*
> ```XML
>         // TODO(spapini): Remove the attributes altogether.
>         if trait_function_has_attr(db, trait_function_id, VIEW_ATTR)? == is_ref {
>             eprintln!("{name}: {}", is_ref);
> ```

remove



_Code quote:_
```XML
         eprintln!("{name}: {}", is_ref);
```
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/dispatcher` line 15 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3051#-NWhCfUv7R5xr9_8vHEA:-NWhCfUv7R5xr9_8vHEB:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/eb97fd9988e9b9bd0d057aef9ac8b4911bdc3297/crates/cairo-lang-starknet/src/plugin/plugin_test_data/dispatcher#L15)):*
> ```
>     fn bad_sig(ref self: T, ref arg1: felt252, ref arg2: felt252) -> felt252;
> 
>     fn bad_sig2(__calldata__: felt252);
> ```





_Suggestion:_
```
    fn bad_sig2(self: @T, __calldata__: felt252);
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3051)* status: 18 of 47 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/abi.rs` line 88 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3051#-NWgrTGg2nDv_nxNelM8:-NWh3Ely5xqpB86mMytG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a458aa38e9134f045f5d266e45e3113fc2c45399/crates/cairo-lang-starknet/src/abi.rs#L88)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is this too complex to do this time?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 42 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3051#-NWgsob0DTPMvF0weeWb:-NWh0j89A5d9ICwj0_2-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a458aa38e9134f045f5d266e45e3113fc2c45399/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L42)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can you delete this and use the abi trait now?
</blockquote></details>

Done.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3051)* status: 18 of 47 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/abi.rs` line 109 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3051#-NWhBgMZ1zOULoqc3-56:-NWlcGjI2t9QMI7dtVlV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/eb97fd9988e9b9bd0d057aef9ac8b4911bdc3297/crates/cairo-lang-starknet/src/abi.rs#L109)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/dispatcher` line 15 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3051#-NWhCfUv7R5xr9_8vHEA:-NWlcXRW8-bYiyJ2GaTY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/eb97fd9988e9b9bd0d057aef9ac8b4911bdc3297/crates/cairo-lang-starknet/src/plugin/plugin_test_data/dispatcher#L15)):*
> ```
>     fn bad_sig(ref self: T, ref arg1: felt252, ref arg2: felt252) -> felt252;
> 
>     fn bad_sig2(__calldata__: felt252);
> ```

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 14 of 23 files at r5, 4 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3051)* status: 35 of 47 files reviewed, all discussions resolved

___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 42 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3051#-NWgsob0DTPMvF0weeWb:-NWnfUdm85WO9VDey66g:b-h292q0) ([raw file](https://github.com/starkware-libs/cairo/blob/a458aa38e9134f045f5d266e45e3113fc2c45399/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L42)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

per discussion today are we re-adding these?

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 23 files at r5, 1 of 5 files at r6, 12 of 12 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3051#-:-NWqjJ74B5ho1bl5GA-L:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3051)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
