### PR TITLE
Add error for allowed libfuncs file not found.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2552)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2552)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/src/allowed_libfuncs.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2552#-NQuSQlD0mUpEmpXGxyI:-NQuSQlD0mUpEmpXGxyJ:b-y0vfj8) ([raw file](https://github.com/starkware-libs/cairo/blob/d0f61fe47f3fb76a397b43c529ec07b71f2de8bd/crates/cairo-lang-starknet/src/allowed_libfuncs.rs#L123)):*
> ```XML
>     allowed_libfuncs.map_err(|_| AllowedLibfuncsError::UnexpectedAllowedLibfuncsList {
>         allowed_libfuncs_list_name: list_name,
>     })
> ```

fix this error as well.



_Code quote:_
```XML
    allowed_libfuncs.map_err(|_| AllowedLibfuncsError::UnexpectedAllowedLibfuncsList {
        allowed_libfuncs_list_name: list_name,
    })
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/allowed_libfuncs.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2552#-NQuSQlD0mUpEmpXGxyI:-NQuU5PQBWbTAGKpNlFI:b-o9q2cz) ([raw file](https://github.com/starkware-libs/cairo/blob/d0f61fe47f3fb76a397b43c529ec07b71f2de8bd/crates/cairo-lang-starknet/src/allowed_libfuncs.rs#L123)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

fix this error as well.
</blockquote></details>

I meant add a deserialization failed error.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2552)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/allowed_libfuncs.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2552#-NQuSQlD0mUpEmpXGxyI:-NQuTujL5wURSJ9jRICc:bp4bzdh) ([raw file](https://github.com/starkware-libs/cairo/blob/d0f61fe47f3fb76a397b43c529ec07b71f2de8bd/crates/cairo-lang-starknet/src/allowed_libfuncs.rs#L123)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I meant add a deserialization failed error.
</blockquote></details>

I added another error variant, I'll change its name.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2552)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/allowed_libfuncs.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2552#-NQuSQlD0mUpEmpXGxyI:-NQuVF-n2LKhESQo7sy7:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/d0f61fe47f3fb76a397b43c529ec07b71f2de8bd/crates/cairo-lang-starknet/src/allowed_libfuncs.rs#L123)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

I added another error variant, I'll change its name.
</blockquote></details>

Done

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/allowed_libfuncs.rs` line 123 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2552#-NQuek2b3TKkmJ-tO_uM:-NQuek2b3TKkmJ-tO_uN:bkrx40j) ([raw file](https://github.com/starkware-libs/cairo/blob/4de400b55ac4335a5b31b2bb06346b9fe9aeca80/crates/cairo-lang-starknet/src/allowed_libfuncs.rs#L123)):*
> ```XML
>         serde_json::from_str(&allowed_libfuncs_str);
>     allowed_libfuncs.map_err(|_| AllowedLibfuncsError::DeserializationError {
>         allowed_libfuncs_list_file: allowed_libfuncs_str,
> ```

is it a file or a string?



_Code quote:_
```XML
 allowed_libfuncs_list_file: allowed_libfuncs_str,
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2552)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2552)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/allowed_libfuncs.rs` line 123 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2552#-NQuek2b3TKkmJ-tO_uM:-NRS3ayeDOtGpmayjmUe:b-2nibcu) ([raw file](https://github.com/starkware-libs/cairo/blob/4de400b55ac4335a5b31b2bb06346b9fe9aeca80/crates/cairo-lang-starknet/src/allowed_libfuncs.rs#L123)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

is it a file or a string?
</blockquote></details>

You are correct. Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2552#-:-NRS5l6bD4NMZQHqArs_:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved

**Pull request merged**
