### PR TITLE
Add shorthand for virtual file creation to parser utils

### PR DESCRIPTION
**Pull request by maciektr**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5538)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5538)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @maciektr and @mkaput)

___
*[`crates/cairo-lang-parser/src/utils.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5538#-NxwTs2lESQ8_kbThDwe:-NxwTs2lESQ8_kbThDwf:b-79f4o7) ([raw file](https://github.com/starkware-libs/cairo/blob/3d86bb2c9c5ed4aeb2962b6ce55cde5f2ca190a8/crates/cairo-lang-parser/src/utils.rs#L76)):*
> ```XML
> pub struct ParsingDiagnosticsAddedError {
>     pub diagnostics: Diagnostics<ParserDiagnostic>,
> }
> ```

i need a better excuse to add this dependency.
why is this required at all?



_Code quote:_
```XML
#[derive(Debug, Error)]
#[error("Diagnostics added")]
pub struct ParsingDiagnosticsAddedError {
    pub diagnostics: Diagnostics<ParserDiagnostic>,
}
```

**Comment by maciektr** [comment]
*[`crates/cairo-lang-parser/src/utils.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5538#-NxwTs2lESQ8_kbThDwe:-NxwVHPz-piaAbww1Nro:bjl61v) ([raw file](https://github.com/starkware-libs/cairo/blob/3d86bb2c9c5ed4aeb2962b6ce55cde5f2ca190a8/crates/cairo-lang-parser/src/utils.rs#L76)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i need a better excuse to add this dependency.
why is this required at all?
</blockquote></details>

Well, it's just about ergonomics. This way if you only care about parsing the node (which proc macro authors will need), you can do: 
```
let db = SimpleParserDatabase::default;
let node = db.parse_virtual(contents)?;
```
So that it's simple to reason about.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5538)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @maciektr and @mkaput)

___
*[`crates/cairo-lang-parser/src/utils.rs` line 44 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5538#-NxwXdpQDoITC-f_w_Tc:-NxwXdpQDoITC-f_w_Td:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/3d86bb2c9c5ed4aeb2962b6ce55cde5f2ca190a8/crates/cairo-lang-parser/src/utils.rs#L44)):*
> ```XML
> 
> impl SimpleParserDatabase {
>     pub fn parse_virtual(
> ```

doc
___
*[`crates/cairo-lang-parser/src/utils.rs` line 56 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5538#-NxwXevw9WIr2w1uALz-:-NxwXevw9WIr2w1uALz0:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/3d86bb2c9c5ed4aeb2962b6ce55cde5f2ca190a8/crates/cairo-lang-parser/src/utils.rs#L56)):*
> ```XML
>     }
> 
>     pub fn parse_virtual_with_diagnostics(
> ```

doc
___
*[`crates/cairo-lang-parser/src/utils.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5538#-NxwTs2lESQ8_kbThDwe:-NxwXlJY8C2P5FETLE8f:b-c1qng3) ([raw file](https://github.com/starkware-libs/cairo/blob/3d86bb2c9c5ed4aeb2962b6ce55cde5f2ca190a8/crates/cairo-lang-parser/src/utils.rs#L76)):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

Well, it's just about ergonomics. This way if you only care about parsing the node (which proc macro authors will need), you can do: 
```
let db = SimpleParserDatabase::default;
let node = db.parse_virtual(contents)?;
```
So that it's simple to reason about.
</blockquote></details>

i still don't see why is it here.
just wrap it with an error somewhere else - no reason for it to be wrapped in this area.

For now just return the diagnostics in the err - handling it as a proper error is weird.

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5538)* status: all files reviewed, 4 unresolved discussions (waiting on @maciektr and @orizi)

___
*[`crates/cairo-lang-parser/src/utils.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5538#-Nxwgo8Z-mOFS-fVAt65:-Nxwgo8Z-mOFS-fVAt66:b-r5did2) ([raw file](https://github.com/starkware-libs/cairo/blob/3d86bb2c9c5ed4aeb2962b6ce55cde5f2ca190a8/crates/cairo-lang-parser/src/utils.rs#L74)):*
> ```XML
> #[derive(Debug, Error)]
> #[error("Diagnostics added")]
> pub struct ParsingDiagnosticsAddedError {
> ```

do we really need `thiserror` here? seems like a trivial manual impl of the `Error` trait would be fine here
___
*[`crates/cairo-lang-parser/src/utils.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5538#-NxwTs2lESQ8_kbThDwe:-Nxwh3632m-Y4vZgCuMf:bx3pqqd) ([raw file](https://github.com/starkware-libs/cairo/blob/3d86bb2c9c5ed4aeb2962b6ce55cde5f2ca190a8/crates/cairo-lang-parser/src/utils.rs#L76)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i still don't see why is it here.
just wrap it with an error somewhere else - no reason for it to be wrapped in this area.

For now just return the diagnostics in the err - handling it as a proper error is weird.
</blockquote></details>

I wonder if this could use the `Maybe` type from `cairo-lang-diagnostics`

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5538)* status: all files reviewed, 4 unresolved discussions (waiting on @maciektr and @mkaput)

___
*[`crates/cairo-lang-parser/src/utils.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5538#-NxwTs2lESQ8_kbThDwe:-Nxwjsif8kGUPOaGT8Gw:bl3tlc2) ([raw file](https://github.com/starkware-libs/cairo/blob/3d86bb2c9c5ed4aeb2962b6ce55cde5f2ca190a8/crates/cairo-lang-parser/src/utils.rs#L76)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I wonder if this could use the `Maybe` type from `cairo-lang-diagnostics`
</blockquote></details>

it isn't really the maybe - as the diagnostics themselves are added and not a marker that they were added.

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5538)* status: all files reviewed, 4 unresolved discussions (waiting on @maciektr and @orizi)

___
*[`crates/cairo-lang-parser/src/utils.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5538#-NxwTs2lESQ8_kbThDwe:-NxwkXak86o-FEZLeHYX:b-7jzv7t) ([raw file](https://github.com/starkware-libs/cairo/blob/3d86bb2c9c5ed4aeb2962b6ce55cde5f2ca190a8/crates/cairo-lang-parser/src/utils.rs#L76)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it isn't really the maybe - as the diagnostics themselves are added and not a marker that they were added.
</blockquote></details>

right

**Review by maciektr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5538)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-parser/src/utils.rs` line 44 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5538#-NxwXdpQDoITC-f_w_Tc:-NxxUdo_BIZTNvE23ZCM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3d86bb2c9c5ed4aeb2962b6ce55cde5f2ca190a8/crates/cairo-lang-parser/src/utils.rs#L44)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/utils.rs` line 56 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5538#-NxwXevw9WIr2w1uALz-:-NxxUe0k8Kt-Cf5IMgY-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3d86bb2c9c5ed4aeb2962b6ce55cde5f2ca190a8/crates/cairo-lang-parser/src/utils.rs#L56)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/utils.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5538#-Nxwgo8Z-mOFS-fVAt65:-NxxWY7V1Yr9Zhko0TyY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3d86bb2c9c5ed4aeb2962b6ce55cde5f2ca190a8/crates/cairo-lang-parser/src/utils.rs#L74)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

do we really need `thiserror` here? seems like a trivial manual impl of the `Error` trait would be fine here
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/utils.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5538#-NxwTs2lESQ8_kbThDwe:-NxxWVDz-ug7n09V8Byl:b-yrawu0) ([raw file](https://github.com/starkware-libs/cairo/blob/3d86bb2c9c5ed4aeb2962b6ce55cde5f2ca190a8/crates/cairo-lang-parser/src/utils.rs#L76)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

right
</blockquote></details>

Sure, thanks! 
Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5538)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @maciektr and @mkaput)

___
*[`crates/cairo-lang-parser/src/utils.rs` line 84 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5538#-NxxoVaCBKjT7LeJBA3f:-NxxoVaD1Ra97tqqiA8_:b-8ed8sx) ([raw file](https://github.com/starkware-libs/cairo/blob/0ec7aa5c581f4a3d3a3ab2d34e022db9e65fc295/crates/cairo-lang-parser/src/utils.rs#L84)):*
> ```XML
> #[derive(Debug)]
> pub struct ParserErrorDiagnosticAdded {
>     diagnostics: String,
> ```

Is it a string to remove the dependency for an external user?
If so doc specifically, if not return the original diagnostics structure in the result.

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5538)* status: all files reviewed, 2 unresolved discussions (waiting on @maciektr and @mkaput)

**Comment by maciektr** [comment]
*[`crates/cairo-lang-parser/src/utils.rs` line 84 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5538#-NxxoVaCBKjT7LeJBA3f:-NxxpEl4E2VaGziToeUc:b-enm36p) ([raw file](https://github.com/starkware-libs/cairo/blob/0ec7aa5c581f4a3d3a3ab2d34e022db9e65fc295/crates/cairo-lang-parser/src/utils.rs#L84)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Is it a string to remove the dependency for an external user?
If so doc specifically, if not return the original diagnostics structure in the result.
</blockquote></details>

Oh, no, just thought we want to display it formatted (as we won't have db to format with in display impl). If that's not needed, I am changing it to a struct, sorry!

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5538)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @maciektr and @mkaput)

___
*[`crates/cairo-lang-parser/src/utils.rs` line 84 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5538#-NxxoVaCBKjT7LeJBA3f:-Nxy5A8M4gwb0F9Gao3L:b-8qp2kh) ([raw file](https://github.com/starkware-libs/cairo/blob/0ec7aa5c581f4a3d3a3ab2d34e022db9e65fc295/crates/cairo-lang-parser/src/utils.rs#L84)):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

Oh, no, just thought we want to display it formatted (as we won't have db to format with in display impl). If that's not needed, I am changing it to a struct, sorry!
</blockquote></details>

you can just return `Diagnostics<ParserDiagnostic>` and drop the type completely.

**Comment by maciektr** [comment]
*[`crates/cairo-lang-parser/src/utils.rs` line 84 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5538#-NxxoVaCBKjT7LeJBA3f:-NxyDlzw5rho3Znro_Op:b-1plx9n) ([raw file](https://github.com/starkware-libs/cairo/blob/0ec7aa5c581f4a3d3a3ab2d34e022db9e65fc295/crates/cairo-lang-parser/src/utils.rs#L84)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you can just return `Diagnostics<ParserDiagnostic>` and drop the type completely.
</blockquote></details>

Ehh, right, sorry :bow:

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5538#-:-NxyGRMu1AkIvXUi-y5R:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5538)* status: all files reviewed, 3 unresolved discussions (waiting on @maciektr)

___
*[`crates/cairo-lang-parser/src/utils.rs` line 43 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5538#-Ny-9pNoB3sHFIjzvgsh:-Ny-9pNoB3sHFIjzvgsi:b-6dtrbs) ([raw file](https://github.com/starkware-libs/cairo/blob/ac5eef15797c365cd6b855fd42e09d8bf3e45f60/crates/cairo-lang-parser/src/utils.rs#L43)):*
> ```XML
> 
> impl SimpleParserDatabase {
>     /// Parse new file and return its syntax root.
> ```

the rustdoc convention is expressing "thing does something", not expressing "the goal of thing thing"



_Suggestion:_
```XML
/// Parses new file and returns its syntax root.
```
___
*[`crates/cairo-lang-parser/src/utils.rs` line 45 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5538#-Ny-9F6xEXyqjZLR_P2Q:-Ny-9F6xEXyqjZLR_P2R:b-anxjin) ([raw file](https://github.com/starkware-libs/cairo/blob/ac5eef15797c365cd6b855fd42e09d8bf3e45f60/crates/cairo-lang-parser/src/utils.rs#L45)):*
Screams with _masło maślane_

This function actually does return diagnostics but in error position.

Maybe this sentence should state, wdyt?:

> This is similar to [`parse_virtual_with_diagnostics`], but is more ergonomic in cases when exact diagnostics do not matter at the usage place.

(notice I used `[]` to make links actual links in docs)
___
*[`crates/cairo-lang-parser/src/utils.rs` line 56 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5538#-Ny-A8FRBouanM9GENb-:-Ny-A8FS9A-JUhGjX-ig:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ac5eef15797c365cd6b855fd42e09d8bf3e45f60/crates/cairo-lang-parser/src/utils.rs#L56)):*
> ```XML
>     }
> 
>     /// Parse new file and return its syntax root with diagnostics.
> ```





_Suggestion:_
```XML
    /// Parses new file and return its syntax root with diagnostics.
```

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5538)* status: all files reviewed, 4 unresolved discussions (waiting on @maciektr)

___
*[`crates/cairo-lang-parser/src/utils.rs` line 66 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5538#-Ny-BDPEBjL9RUNlrKEZ:-Ny-BDPFEQRV0XylvovY:bb2tluo) ([raw file](https://github.com/starkware-libs/cairo/blob/ac5eef15797c365cd6b855fd42e09d8bf3e45f60/crates/cairo-lang-parser/src/utils.rs#L66)):*
> ```XML
>         let file = FileLongId::Virtual(VirtualFile {
>             parent: None,
>             name: "parser_input".to_smolstr(),
> ```

nit, you can use `Into::into` and save an import 🤪

**Review by maciektr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5538)* status: all files reviewed, 3 unresolved discussions (waiting on @mkaput)

___
*[`crates/cairo-lang-parser/src/utils.rs` line 43 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5538#-Ny-9pNoB3sHFIjzvgsh:-Ny-YAUG2jqZtNeWtOsJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ac5eef15797c365cd6b855fd42e09d8bf3e45f60/crates/cairo-lang-parser/src/utils.rs#L43)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

the rustdoc convention is expressing "thing does something", not expressing "the goal of thing thing"
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/utils.rs` line 45 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5538#-Ny-9F6xEXyqjZLR_P2Q:-Ny-YJh_BHgDMCP9mgOi:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ac5eef15797c365cd6b855fd42e09d8bf3e45f60/crates/cairo-lang-parser/src/utils.rs#L45)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Screams with _masło maślane_

This function actually does return diagnostics but in error position.

Maybe this sentence should state, wdyt?:

> This is similar to [`parse_virtual_with_diagnostics`], but is more ergonomic in cases when exact diagnostics do not matter at the usage place.

(notice I used `[]` to make links actual links in docs)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/utils.rs` line 56 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5538#-Ny-A8FRBouanM9GENb-:-Ny-YDYDE4MsmSxTCNLT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ac5eef15797c365cd6b855fd42e09d8bf3e45f60/crates/cairo-lang-parser/src/utils.rs#L56)):*
> ```XML
>     }
> 
>     /// Parse new file and return its syntax root with diagnostics.
> ```

Done.

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5538#-:-Ny-pGzU4Z0uiJwgqFbB:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @maciektr)

**Pull request merged**
