### PR TITLE
Improve Span deserialization.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4595)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4595)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/array.cairo` line 147 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4595#-NlwkI_qAe2sB-T7s6YT:-NlwkI_qAe2sB-T7s6YU:btn3iax) ([raw file](https://github.com/starkware-libs/cairo/blob/732d9ba21d1853041ede9cc4fdbc87b83408bbad/corelib/src/array.cairo#L147)):*
> ```Cairo
>         serialized = serialized.slice(length, serialized.len() - length);
>         Option::Some(Span { snapshot: res })
>     }
> ```

you probably need to make this impl have a negative param - and have a specific impl for Span<felt252>



_Code quote:_
```Cairo
        let length = *serialized.pop_front()?;;
        let res = serialized.slice(0, length);
        serialized = serialized.slice(length, serialized.len() - length);
        Option::Some(Span { snapshot: res })
    }
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4595)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/array.cairo` line 147 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4595#-NlwkI_qAe2sB-T7s6YT:-Nm67Ilj6FkdqnA-gpYe:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/732d9ba21d1853041ede9cc4fdbc87b83408bbad/corelib/src/array.cairo#L147)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you probably need to make this impl have a negative param - and have a specific impl for Span<felt252>
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4595)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/array.cairo` line 7 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4595#-Nm68RoR6_yZkBlYUILd:-Nm68RoR6_yZkBlYUILe:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/aa2c22d0b6254c9ffbea479430889776d412b3e7/corelib/src/array.cairo#L7)):*
> ```Cairo
> use core::option::OptionTrait;
> use core::serde::Serde;
> use core::metaprogramming::{TypeEqual, TypeEqualImpl};
> ```





_Suggestion:_
```Cairo
use core::metaprogramming::TypeEqual;
```
___
*[`corelib/src/lib.cairo` line 355 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4595#-Nm68I6f6K27kNZj1jGm:-Nm68I6f6K27kNZj1jGn:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/aa2c22d0b6254c9ffbea479430889776d412b3e7/corelib/src/lib.cairo#L355)):*
> ```Cairo
> 
> // Metaprogramming.
> pub mod metaprogramming;
> ```





_Suggestion:_
```Cairo
// Metaprogramming.
mod metaprogramming;
```
___
*[`corelib/src/metaprogramming.cairo` line 5 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4595#-Nm68DLOENFAzG3MBP-P:-Nm68DLOENFAzG3MBP-Q:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/aa2c22d0b6254c9ffbea479430889776d412b3e7/corelib/src/metaprogramming.cairo#L5)):*
> ```Cairo
> pub trait TypeEqual<S, T> {}
> 
> pub impl TypeEqualImpl<T> of TypeEqual<T, T>;
> ```





_Suggestion:_
```Cairo
/// A trait that can be used to disable implementations based on the types of the generic args.
/// Assumes that `TypeEqualImpl` is the only implementation of this trait.
pub trait TypeEqual<S, T> {}

impl TypeEqualImpl<T> of TypeEqual<T, T>;
```

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/lib.cairo` line 355 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4595#-Nm68I6f6K27kNZj1jGm:-Nm68fu10TgRqUiBu6bX:b-g3t40x) ([raw file](https://github.com/starkware-libs/cairo/blob/aa2c22d0b6254c9ffbea479430889776d412b3e7/corelib/src/lib.cairo#L355)):*
> ```Cairo
> 
> // Metaprogramming.
> pub mod metaprogramming;
> ```

why? 
A user might want to use `TypeEqual`

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/metaprogramming.cairo` line 5 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4595#-Nm68DLOENFAzG3MBP-P:-Nm68tg3867fsNPq8QF3:b-sgsvmk) ([raw file](https://github.com/starkware-libs/cairo/blob/aa2c22d0b6254c9ffbea479430889776d412b3e7/corelib/src/metaprogramming.cairo#L5)):*
> ```Cairo
> pub trait TypeEqual<S, T> {}
> 
> pub impl TypeEqualImpl<T> of TypeEqual<T, T>;
> ```

what about the idea that only pub impls can be infered?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4595)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/array.cairo` line 7 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4595#-Nm68RoR6_yZkBlYUILd:-Nm68e6u6PCP70HPLop0:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/aa2c22d0b6254c9ffbea479430889776d412b3e7/corelib/src/array.cairo#L7)):*
> ```Cairo
> use core::option::OptionTrait;
> use core::serde::Serde;
> use core::metaprogramming::{TypeEqual, TypeEqualImpl};
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4595)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/metaprogramming.cairo` line 5 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4595#-Nm68DLOENFAzG3MBP-P:-Nm69hoj4fKSXV-eMnr_:b8wwyol) ([raw file](https://github.com/starkware-libs/cairo/blob/aa2c22d0b6254c9ffbea479430889776d412b3e7/corelib/src/metaprogramming.cairo#L5)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what about the idea that only pub impls can be infered?
</blockquote></details>

we have decided against it.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4595)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/metaprogramming.cairo` line 5 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4595#-Nm68DLOENFAzG3MBP-P:-Nm6GMf95GI3LFyfcEG4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/aa2c22d0b6254c9ffbea479430889776d412b3e7/corelib/src/metaprogramming.cairo#L5)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

we have decided against it.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4595#-:-Nm6GqNy3K8Qm9pK2AD2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
