### PR TITLE
Use deref in storage access, and refactor storage.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
**Stack**:
- #5830 ⬅
- #5855

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5830)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 76 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5830)* status: 1 of 76 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`corelib/src/starknet/storage.cairo` line 16 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5830#-O-oKfGBEy44JdQdd901:-O-oKfGBEy44JdQdd902:bi84rcx) ([raw file](https://github.com/starkware-libs/cairo/blob/b04aee24e33267fd26d68740e19da35dc608ed8f/corelib/src/starknet/storage.cairo#L16)):*
> ```Cairo
> 
> /// Trait for accessing any contract/component storage member.
> #[deprecated(feature: "StorageMemberAccessTrait", note: "Use `StorageAccessTrait` instead.")]
> ```

why is this required?
is there direct usage of it anywhere?
___
*[`corelib/src/starknet/storage.cairo` line 245 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5830#-O-oKsXyEWObRZ62UMi1:-O-oKsXyEWObRZ62UMi2:b-hfpv23) ([raw file](https://github.com/starkware-libs/cairo/blob/b04aee24e33267fd26d68740e19da35dc608ed8f/corelib/src/starknet/storage.cairo#L245)):*
> ```Cairo
> 
> /// Trait for updating the hash state with a value, using an `entry` method.
> // TODO(Gil): Once associated types are stabilized, make `K` and `V` associated types of this trait.
> ```

remove.
___
*[`corelib/src/starknet/storage.cairo` line 256 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5830#-O-oKvHM3U7u4G0hcSZw:-O-oKvHM3U7u4G0hcSZx:bn8ukgv) ([raw file](https://github.com/starkware-libs/cairo/blob/b04aee24e33267fd26d68740e19da35dc608ed8f/corelib/src/starknet/storage.cairo#L256)):*
> ```Cairo
> pub struct Map<K, V> {}
> 
> type LegacyMap<K, V> = Map<K, V>;
> ```

just add a `use` with deprecated in the plugin instead of here (as we currently have to support it without `starknet::` anyway.

**Review by orizi — COMMENTED** [review]
> Reviewed 4 of 76 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5830)* status: 5 of 76 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5830)* status: 4 of 76 files reviewed, 3 unresolved discussions (waiting on @ArielElp and @orizi)

___
*[`corelib/src/starknet/storage.cairo` line 16 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5830#-O-oKfGBEy44JdQdd901:-O-oiEjT67culvMS9wJq:b7dddqr) ([raw file](https://github.com/starkware-libs/cairo/blob/6cada6116c400014552ed3e47afbbddf7b6db3c2/corelib/src/starknet/storage.cairo#L16)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why is this required?
is there direct usage of it anywhere?
</blockquote></details>

Not by us, but maybe someone used it, I can just remove the `ref`.
___
*[`corelib/src/starknet/storage.cairo` line 245 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5830#-O-oKsXyEWObRZ62UMi1:-O060ngV8RY2ReOk9SsK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6cada6116c400014552ed3e47afbbddf7b6db3c2/corelib/src/starknet/storage.cairo#L245)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove.
</blockquote></details>

Done.
___
*[`corelib/src/starknet/storage.cairo` line 256 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5830#-O-oKvHM3U7u4G0hcSZw:-O060oEu5_Jzy4XqJIcE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6cada6116c400014552ed3e47afbbddf7b6db3c2/corelib/src/starknet/storage.cairo#L256)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

just add a `use` with deprecated in the plugin instead of here (as we currently have to support it without `starknet::` anyway.
</blockquote></details>

Done.

**Comment by gilbens-starkware** [comment]
Reopened in #5857 .

**Pull request closed without merging**
