### PR TITLE
Simplify add_fallthroughs.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2323)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2323)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/test.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2323#-NPQrZ0Q7kvmlqrI9AhL:-NPQrZ0Q7kvmlqrI9AhM:bwdo4pw) ([raw file](https://github.com/starkware-libs/cairo/blob/cfe5ad851a830878e223bfbd15512e2091b9bf18/crates/cairo-lang-lowering/src/inline/test.rs#L46)):*
> ```XML
> 
>     let mut after = before.deref().clone();
>     apply_inlining(db, test_function.function_id, &mut after).unwrap();
> ```

I feel that adding topo sort here will make the output harder to review.
and add_fallthroughs requires topo_sort now.



_Code quote:_
```XML
    apply_inlining(db, test_function.function_id, &mut after).unwrap();
    optimize_remappings(&mut after);
    add_fallthroughs(&mut after);
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2323)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/flow/test.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2323#-NPQsJjg9RcOCp-38FOJ:-NPQsJjg9RcOCp-38FOK:br8yvhc) ([raw file](https://github.com/starkware-libs/cairo/blob/9e67d3bd03b60f603138d8258481feedbd4f29a8/crates/cairo-lang-lowering/src/flow/test.rs#L1)):*
> ```XML
> use cairo_lang_debug::DebugWithDb;
> ```

this file is just a duplication of the other.



_Code quote:_
```XML
use cairo_lang_debug::DebugWithDb;
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2323)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/flow/test.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2323#-NPQsJjg9RcOCp-38FOJ:-NPQtadd-w-l9fpOVvTa:brpmqc3) ([raw file](https://github.com/starkware-libs/cairo/blob/9e67d3bd03b60f603138d8258481feedbd4f29a8/crates/cairo-lang-lowering/src/flow/test.rs#L1)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this file is just a duplication of the other.
</blockquote></details>

removed.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2323#-:-NPQvaNv5ojydXq-TOQ9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
