### PR TITLE
Patcher diagnostic mapper

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1410)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1410)* status: 1 of 10 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/defs/src/db.rs` line 229 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1410#-NJk7hWs7s1aCA76B4MW:-NJk7hWs7s1aCA76B4MX:by8lm26) ([raw file](https://github.com/starkware-libs/cairo/blob/b70c614e873b235d6a768d14cf9c206fe08df6e1/crates/defs/src/db.rs#L229)):*
> ```XML
>                     main_file_info = parent_module_data.generated_file_info
>                         [submodule_id.file_index(db).0]
>                         .clone();
> ```

Document.



_Code quote:_
```XML
                    main_file_info = parent_module_data.generated_file_info
                        [submodule_id.file_index(db).0]
                        .clone();
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1410)* status: 1 of 10 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/defs/src/db.rs` line 203 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1410#-NJk86Fm6Iiw7haaa3Et:-NJk86Fm6Iiw7haaa3Eu:b-jbfgnq) ([raw file](https://github.com/starkware-libs/cairo/blob/b70c614e873b235d6a768d14cf9c206fe08df6e1/crates/defs/src/db.rs#L203)):*
> ```XML
>     pub extern_functions: OrderedHashMap<ExternFunctionId, ast::ItemExternFunction>,
>     pub files: Vec<FileId>,
>     pub generated_file_info: Vec<Option<FileInfo>>,
> ```

Add comment.

None means that the file wasn't generated.



_Code quote:_
```XML
 pub generated_file_info: Vec<Option<FileInfo>>,
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1410)* status: 1 of 10 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/semantic/src/db.rs` line 600 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1410#-NJk97eg9X_f2M4HrnyA:-NJk97eg9X_f2M4HrnyB:b-hfpv23) ([raw file](https://github.com/starkware-libs/cairo/blob/b70c614e873b235d6a768d14cf9c206fe08df6e1/crates/semantic/src/db.rs#L600)):*
> ```XML
>         assert_eq!(diag.stable_location.module_file_id.0, module_id, "Unexpected module id.");
>         let file_index = diag.stable_location.module_file_id.1;
>         println!("stable_location: {:?}", diag.stable_location.module_file_id);
> ```

remove.



_Code quote:_
```XML
 println!("stable_location: {:?}", diag.stable_location.module_file_id);
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/defs/src/db.rs` line 203 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1410#-NJk86Fm6Iiw7haaa3Et:-NJnGijv5FyK7Q6LmnB2:bmv7tez) ([raw file](https://github.com/starkware-libs/cairo/blob/b70c614e873b235d6a768d14cf9c206fe08df6e1/crates/defs/src/db.rs#L203)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Add comment.

None means that the file wasn't generated.
</blockquote></details>

or no remapping?

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1410)* status: 2 of 10 files reviewed, 9 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/semantic/src/db.rs` line 606 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1410#-NJnHBRg7DKQOHlLCSg7:-NJnHBRg7DKQOHlLCSg8:b9nuolu) ([raw file](https://github.com/starkware-libs/cairo/blob/b70c614e873b235d6a768d14cf9c206fe08df6e1/crates/semantic/src/db.rs#L606)):*
> ```XML
>                     stable_location: StableLocation::new(
>                         file_info.origin,
>                         db.intern_stable_ptr(SyntaxStablePtr::Root),
> ```

Why is this the location?



_Code quote:_
```XML
                        file_info.origin,
                        db.intern_stable_ptr(SyntaxStablePtr::Root),
```
___
*[`crates/semantic/src/diagnostic_test.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1410#-NJnHYCt2Eu-18njdS5X:-NJnHYCuEu3UCeHErVIS:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/b70c614e873b235d6a768d14cf9c206fe08df6e1/crates/semantic/src/diagnostic_test.rs#L150)):*
> ```XML
>     let submodule_submodules = db.module_submodules(*submodule_id).unwrap();
>     let subsubmodule_id = submodule_submodules.first().unwrap();
>     println!("subsubmodule_id: {:?}", subsubmodule_id);
> ```

remove



_Code quote:_
```XML
 println!("subsubmodule_id: {:?}", subsubmodule_id);
```
___
*[`crates/semantic/src/patcher.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1410#-NJnHtYHBdyn9PsVU6Y2:-NJnHtYHBdyn9PsVU6Y3:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/b70c614e873b235d6a768d14cf9c206fe08df6e1/crates/semantic/src/patcher.rs#L26)):*
> ```XML
>                     "Translation. span: {span:?}, patch_span: {patch_span:?}, \
>                      origin_span:{origin_span:?}"
>                 );
> ```

remove



_Code quote:_
```XML
                println!(
                    "Translation. span: {span:?}, patch_span: {patch_span:?}, \
                     origin_span:{origin_span:?}"
                );
```
___
*[`crates/semantic/src/patcher.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1410#-NJnIpbp2Unb9a8u5twF:-NJnIpbp2Unb9a8u5twG:bys72qy) ([raw file](https://github.com/starkware-libs/cairo/blob/b70c614e873b235d6a768d14cf9c206fe08df6e1/crates/semantic/src/patcher.rs#L56)):*
> ```XML
> pub fn interpolate_patched(
>     db: &dyn SyntaxGroup,
>     code: String,
> ```

you are copying it anyway, right?



_Suggestion:_
```XML
 code: &str
```
___
*[`crates/semantic/src/patcher.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1410#-NJnINSM49p6gMwnQRA7:-NJnINSM49p6gMwnQRA8:b-mjscyv) ([raw file](https://github.com/starkware-libs/cairo/blob/b70c614e873b235d6a768d14cf9c206fe08df6e1/crates/semantic/src/patcher.rs#L68)):*
> ```XML
> 
>         let mut name = String::new();
>         for d in chars.by_ref() {
> ```

Is this the same?



_Suggestion:_
```XML
&chars
```
___
*[`crates/semantic/src/patcher.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1410#-NJnIY0i-r2qaDB_05FE:-NJnIY0i-r2qaDB_05FF:by8lm26) ([raw file](https://github.com/starkware-libs/cairo/blob/b70c614e873b235d6a768d14cf9c206fe08df6e1/crates/semantic/src/patcher.rs#L75)):*
> ```XML
>         }
>         if name.is_empty() {
>             builder.add_char('$');
> ```

Document.



_Code quote:_
```XML
        if name.is_empty() {
            builder.add_char('$');
            continue;
        }
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1410)* status: 2 of 10 files reviewed, 9 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/defs/src/db.rs` line 203 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1410#-NJk86Fm6Iiw7haaa3Et:-NJnvWai19bR_p_3O1dE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b70c614e873b235d6a768d14cf9c206fe08df6e1/crates/defs/src/db.rs#L203)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

or no remapping?
</blockquote></details>

Done.
___
*[`crates/defs/src/db.rs` line 229 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1410#-NJk7hWs7s1aCA76B4MW:-NJnvl10D1caMiS_4hv6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b70c614e873b235d6a768d14cf9c206fe08df6e1/crates/defs/src/db.rs#L229)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Document.
</blockquote></details>

Done.
___
*[`crates/semantic/src/db.rs` line 600 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1410#-NJk97eg9X_f2M4HrnyA:-NJnwEhOBMq452R-uQ_l:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b70c614e873b235d6a768d14cf9c206fe08df6e1/crates/semantic/src/db.rs#L600)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

remove.
</blockquote></details>

Done.
___
*[`crates/semantic/src/db.rs` line 606 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1410#-NJnHBRg7DKQOHlLCSg7:-NJnwF1F4A53XXqAnguO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b70c614e873b235d6a768d14cf9c206fe08df6e1/crates/semantic/src/db.rs#L606)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why is this the location?
</blockquote></details>

Done.
___
*[`crates/semantic/src/diagnostic_test.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1410#-NJnHYCt2Eu-18njdS5X:-NJnwIAx1xsKU6SntTgn:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b70c614e873b235d6a768d14cf9c206fe08df6e1/crates/semantic/src/diagnostic_test.rs#L150)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`crates/semantic/src/patcher.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1410#-NJnHtYHBdyn9PsVU6Y2:-NJnwVWU6vxyFafvdsQ7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b70c614e873b235d6a768d14cf9c206fe08df6e1/crates/semantic/src/patcher.rs#L26)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`crates/semantic/src/patcher.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1410#-NJnIpbp2Unb9a8u5twF:-NJnwVnr1e4m52cJrm_G:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b70c614e873b235d6a768d14cf9c206fe08df6e1/crates/semantic/src/patcher.rs#L56)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

you are copying it anyway, right?
</blockquote></details>

Done.
___
*[`crates/semantic/src/patcher.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1410#-NJnINSM49p6gMwnQRA7:-NJnwcOk9mQrKGZ0ACp2:br6rrrn) ([raw file](https://github.com/starkware-libs/cairo/blob/b70c614e873b235d6a768d14cf9c206fe08df6e1/crates/semantic/src/patcher.rs#L68)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Is this the same?
</blockquote></details>

Nope :(
___
*[`crates/semantic/src/patcher.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1410#-NJnIY0i-r2qaDB_05FE:-NJnxF21C_u9p4O7B2Hd:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b70c614e873b235d6a768d14cf9c206fe08df6e1/crates/semantic/src/patcher.rs#L75)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Document.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1410#-:-NJnzc2w0Dt2BVLed0po:bnfp4nl)* status: 6 of 10 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/semantic/src/db.rs` line 609 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1410#-NJnzOuf-QNRvdVK2ly9:-NJnzOuf-QNRvdVK2lyA:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d3769ddf11a361c12c47ea60988a4b33b3e7d7cf/crates/semantic/src/db.rs#L609)):*
> ```XML
>             if let Some(plugin_diag) = file_info.diagnostic_mapper.map_diag(db, diag) {
>                 // We don't have a real location, so we give a dummy location in the correct file.
>                 // SemanticDiagnostic struct knowns to give te proper span for
> ```





_Suggestion:_
```XML
the
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1410)* status: 6 of 10 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/semantic/src/db.rs` line 609 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1410#-NJnzOuf-QNRvdVK2ly9:-NJo-7Hq7A2Reo4Q4jSw:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d3769ddf11a361c12c47ea60988a4b33b3e7d7cf/crates/semantic/src/db.rs#L609)):*
> ```XML
>             if let Some(plugin_diag) = file_info.diagnostic_mapper.map_diag(db, diag) {
>                 // We don't have a real location, so we give a dummy location in the correct file.
>                 // SemanticDiagnostic struct knowns to give te proper span for
> ```

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 4 of 10 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1410)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
