### PR TITLE
*_get_gas() for builtins: Implement Sierra->casm.

### PR DESCRIPTION
**Pull request by liorgold2**
commit-id:add13acf

---

**Stack**:
- #1212
- #1211 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1211)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`crates/sierra_to_casm/src/invocations/builtin_cost.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1211#-NISKzanCSjThPLagZI-:-NISKzaoD2cZsr7y50Mv:b2xvzoc) ([raw file](https://github.com/starkware-libs/cairo/blob/f87e0895fb4cd7a842338ca5d7888473a059cbc2/crates/sierra_to_casm/src/invocations/builtin_cost.rs#L33)):*
> ```XML
> ) -> Result<CompiledInvocation, InvocationError> {
>     // TODO(lior): Share code with get_gas().
>     // TODO(orizi): Add Range-Check usage.
> ```

probably a leftover.



_Code quote:_
```XML
    // TODO(orizi): Add Range-Check usage.
```
___
*[`crates/sierra_to_casm/src/invocations/builtin_cost.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1211#-NISLaA92F-CJzhx9PX_:-NISLaA92F-CJzhx9PXa:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f87e0895fb4cd7a842338ca5d7888473a059cbc2/crates/sierra_to_casm/src/invocations/builtin_cost.rs#L116)):*
> ```XML
>                     op: FeltOperator::Sub,
>                     a: gas_counter_value.unchecked_apply_known_ap_change(2),
>                     b: DerefOrImmediate::Immediate(requested_count.to_bigint().unwrap()),
> ```





_Suggestion:_
```XML
(BigInt::from(requested_count)
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1211)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/sierra_to_casm/src/invocations/builtin_cost.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1211#-NISKzanCSjThPLagZI-:-NISPgtjAx_cX8zmDvLY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f87e0895fb4cd7a842338ca5d7888473a059cbc2/crates/sierra_to_casm/src/invocations/builtin_cost.rs#L33)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

probably a leftover.
</blockquote></details>

Done.
___
*[`crates/sierra_to_casm/src/invocations/builtin_cost.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1211#-NISLaA92F-CJzhx9PX_:-NISPhDp9Y1mVvy_DqEA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f87e0895fb4cd7a842338ca5d7888473a059cbc2/crates/sierra_to_casm/src/invocations/builtin_cost.rs#L116)):*
> ```XML
>                     op: FeltOperator::Sub,
>                     a: gas_counter_value.unchecked_apply_known_ap_change(2),
>                     b: DerefOrImmediate::Immediate(requested_count.to_bigint().unwrap()),
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1211#-:-NISRN_D8HVcdJ3iB7km:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1211)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
