### PR TITLE
Added syscall hint to casm macro and used it in storgae_read

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1345)

### CODE REVIEW

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1345#-:-NJKEnjZ3Duq-P3qVaiv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1345)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/sierra_to_casm/src/invocations/starknet/storage.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1345#-NJKHRHFD2bWQ7ccmEtw:-NJKHRHFD2bWQ7ccmEtx:bqwf7cz) ([raw file](https://github.com/starkware-libs/cairo/blob/4526e7f3ccb2d344a9f27fba066831e5e36f931c/crates/sierra_to_casm/src/invocations/starknet/storage.rs#L41)):*
> ```XML
>         [ap] = [[system_base] + system_offset];
>         storage_address = [[system_base] + (system_offset + 1)];
>         %{ syscall_handler.syscall(segments=segments, syscall_ptr=[ap + -1]) %}
> ```

why did you change it?



_Code quote:_
```XML
[ap + -1]
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1345)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/sierra_to_casm/src/invocations/starknet/storage.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1345#-NJKHRHFD2bWQ7ccmEtw:-NJKHZJ6E95GaIQlLugB:buj23wx) ([raw file](https://github.com/starkware-libs/cairo/blob/4526e7f3ccb2d344a9f27fba066831e5e36f931c/crates/sierra_to_casm/src/invocations/starknet/storage.rs#L41)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why did you change it?
</blockquote></details>

It was
[[system_base] + (system_offset )]



_Code quote:_
```XML
[[system_base] + (system_offset + 1)]
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1345)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/casm/src/inline.rs` line 261 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1345#-NJKx5rk0dDfTqe-2C2r:-NJKx5rk0dDfTqe-2C2s:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/9f52954d056fa9ce7e202fc387370b0d163eaa25/crates/casm/src/inline.rs#L261)):*
> ```XML
>     };
>     ([$var:ident + $offset:expr]) => {
>         $crate::operand::CellRef { register: $var.register, offset: $var.offset + $offset }
> ```

remove



_Code quote:_
```XML
    ([$var:ident + $offset:expr]) => {
        $crate::operand::CellRef { register: $var.register, offset: $var.offset + $offset }
    };
    ([ap - $offset:expr]) => {
        $crate::operand::CellRef { register: $crate::reg!(ap), offset: -$offset }
    };
    ([fp - $offset:expr]) => {
        $crate::operand::CellRef { register: $crate::reg!(fp), offset: -$offset }
    };
    ([$var:ident - $offset:expr]) => {
        $crate::operand::CellRef { register: $var.register, offset: $var.offset - $offset }
    };
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1345)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/casm/src/inline.rs` line 261 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1345#-NJKx5rk0dDfTqe-2C2r:-NJKxFP8EtRHxHyP372Z:bnlgfdv) ([raw file](https://github.com/starkware-libs/cairo/blob/9f52954d056fa9ce7e202fc387370b0d163eaa25/crates/casm/src/inline.rs#L261)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

remove
</blockquote></details>

or add `&`

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1345#-:-NJLAV2LCulFchAKaw5l:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1345)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

___
*[`crates/sierra_to_casm/src/invocations/starknet/storage.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1345#-NJKHRHFD2bWQ7ccmEtw:-NJKqaPMEPNNvTScQmvx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4526e7f3ccb2d344a9f27fba066831e5e36f931c/crates/sierra_to_casm/src/invocations/starknet/storage.rs#L41)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

It was
[[system_base] + (system_offset )]
</blockquote></details>

Done.

**Pull request merged**
