### PR TITLE
feat: OverflowingSub trait

### PR DESCRIPTION
**Pull request by enitrat**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5164)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5164)* status: all files reviewed, 2 unresolved discussions (waiting on @enitrat)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5164#-NrkdA-10pfnjsOc259r:-NrkdA-10pfnjsOc259s:b-uuj1x0) (no related file):*
@gilbens-starkware for 2nd eye.

___
___
*[`corelib/src/num/traits/ops/overflowing.cairo` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5164#-Nrkd1Nd4NUoAskp97LQ:-Nrkd1Nd4NUoAskp97LR:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2ed0d93ab31078e5afb0b6b187ad7a8b8b742f28/corelib/src/num/traits/ops/overflowing.cairo#L12)):*
> ```Cairo
> pub trait OverflowingSub<T> {
>     /// Returns a tuple of the difference along with a boolean indicating whether an arithmetic overflow
>     /// would occur.
> ```





_Suggestion:_
```Cairo
    /// Returns a tuple of the difference along with a boolean indicating whether an arithmetic
    /// overflow would occur.
```

**Review by enitrat — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5164)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/num/traits/ops/overflowing.cairo` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5164#-Nrkd1Nd4NUoAskp97LQ:-NrkefyGCnQKPnHFzFqQ:b4ne6er) ([raw file](https://github.com/starkware-libs/cairo/blob/2ed0d93ab31078e5afb0b6b187ad7a8b8b742f28/corelib/src/num/traits/ops/overflowing.cairo#L12)):*
> ```Cairo
> pub trait OverflowingSub<T> {
>     /// Returns a tuple of the difference along with a boolean indicating whether an arithmetic overflow
>     /// would occur.
> ```

Done. What's the correct line length to use?

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5164)* status: all files reviewed, 2 unresolved discussions (waiting on @enitrat)

___
*[`corelib/src/num/traits/ops/overflowing.cairo` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5164#-Nrkd1Nd4NUoAskp97LQ:-NrkezvP5U3QqtVveT1c:b-1ex4r) ([raw file](https://github.com/starkware-libs/cairo/blob/2ed0d93ab31078e5afb0b6b187ad7a8b8b742f28/corelib/src/num/traits/ops/overflowing.cairo#L12)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

Done. What's the correct line length to use?
</blockquote></details>

100 chars.

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5164#-:-Nrkf6vN-UodQaH_Jv7s:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @enitrat)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5164#-:-NrnyI5y1YExcwWIjmRj:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @enitrat)

**Pull request merged**
