### PR TITLE
Fix consistency between get-lowering and the actual lowering.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5119)

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
> Reviewed 13 of 16 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5119)* status: 15 of 18 files reviewed, 1 unresolved discussion

**Review by orizi — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5119#-:-NrEeGR28VBneUsTfPrl:bnfp4nl)* status: 15 of 18 files reviewed, 1 unresolved discussion

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 15 of 16 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5119)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 16 files at r1, 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5119)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
