### PR TITLE
Document trait AccountContract.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6043)

### CODE REVIEW

**Review by ArielElp — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6043)* status: all files reviewed, 3 unresolved discussions (waiting on @Draggu, @ilyalesokhin-starkware, @mkaput, @orizi, and @piotmag769)

___
*[`corelib/src/starknet/account.cairo` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6043#-O2TU4us8aK-NX0RV-nt:-O2TU4us8aK-NX0RV-nu:b-o88uj9) ([raw file](https://github.com/starkware-libs/cairo/blob/e1afb12b8623a9404a109f5b50568ff84bc08c0b/corelib/src/starknet/account.cairo#L14)):*
> ```Cairo
> }
> 
> /// A trait for account contracts that support validate and declaration transactions with
> ```

cahnge to "...that support class declarations (only __validate__ and __execute__ are mandatory for an account)"

no need to add "support validate", all accounts must have validate, also drop version > 0, we shouldn't focus on old deprecated accounts
___
*[`corelib/src/starknet/account.cairo` line 16 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6043#-O2TUqIgDmm0gwEk1gXe:-O2TUqIgDmm0gwEk1gXf:b-mr7mfg) ([raw file](https://github.com/starkware-libs/cairo/blob/e1afb12b8623a9404a109f5b50568ff84bc08c0b/corelib/src/starknet/account.cairo#L16)):*
> ```Cairo
> /// A trait for account contracts that support validate and declaration transactions with
> /// version > 0.
> /// The trait assumes that the calldata for invoke transactions is `Array<Call>`. This is not enforced
> ```

The trait --> This trait
___
*[`corelib/src/starknet/account.cairo` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6043#-O2TUv9lBHCE0J7O3zSH:-O2TUv9lBHCE0J7O3zSI:br3qlg4) ([raw file](https://github.com/starkware-libs/cairo/blob/e1afb12b8623a9404a109f5b50568ff84bc08c0b/corelib/src/starknet/account.cairo#L17)):*
> ```Cairo
> /// version > 0.
> /// The trait assumes that the calldata for invoke transactions is `Array<Call>`. This is not enforced
> /// by StarkNet, but block explorers might not be able to parse other formats.
> ```

but block explorers might not be able to parse other formats --> but is the network standard according to SNIP6, deviating from the standard interface may lead to incompatibility with standard tooling

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6043#-:-O2TdNdA-b5b9VV4yu8p:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Draggu, @ilyalesokhin-starkware, @orizi, and @piotmag769)

___
*[`corelib/src/starknet/account.cairo` line 18 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6043#-O2Td-la2eD5u-Ucg3yt:-O2Td-la2eD5u-Ucg3yu:bwvi71l) ([raw file](https://github.com/starkware-libs/cairo/blob/525502fd38cdb6e0821c03b094810c92cd68b5bd/corelib/src/starknet/account.cairo#L18)):*
> ```Cairo
> /// This trait assumes that the calldata for invoke transactions is `Array<Call>`. This is the
> /// network standard following SNIP6. It is not enforced by StarkNet, but deviating from the standard
> /// interface may lead to incompatibility with standard tooling.
> ```

nit: put an empty line between the summary sentence and the rest of the doc

also I recommend putting each sentence on a separate line because changes are usually scoped to sentences and this gives better diffs 

no need to apply this though, I just wanted to share my insights



_Suggestion:_
```Cairo
/// A trait for account contracts that support class declarations (only validate and execute are
/// mandatory for an account).

/// This trait assumes that the calldata for invoke transactions is `Array<Call>`.
/// This is the network standard following SNIP6.
/// It is not enforced by StarkNet, but deviating from the standard
/// interface may lead to incompatibility with standard tooling.
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6043)* status: all files reviewed, 2 unresolved discussions (waiting on @Draggu, @ilyalesokhin-starkware, and @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6043#-O2TgxcsEkCPhZqRcDFh:-O2TgxcsEkCPhZqRcDFi:bepgx1r) (no related file):*
run `./scripts/cairo_fmt.sh` to fix the long lines.

___

**Review by piotmag769 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6043)* status: all files reviewed, 2 unresolved discussions (waiting on @Draggu and @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6043)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Draggu, @mkaput, @orizi, and @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6043#-O2TgxcsEkCPhZqRcDFh:-O2ThPUd0NX9lJjcMWRR:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

run `./scripts/cairo_fmt.sh` to fix the long lines.
</blockquote></details>

Done.

___
___
*[`corelib/src/starknet/account.cairo` line 18 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6043#-O2Td-la2eD5u-Ucg3yt:-O2Tptk25SKgjyCPE1z0:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/525502fd38cdb6e0821c03b094810c92cd68b5bd/corelib/src/starknet/account.cairo#L18)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

nit: put an empty line between the summary sentence and the rest of the doc

also I recommend putting each sentence on a separate line because changes are usually scoped to sentences and this gives better diffs 

no need to apply this though, I just wanted to share my insights
</blockquote></details>

done

**Review by mkaput — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6043)* status: all files reviewed, 1 unresolved discussion (waiting on @Draggu and @orizi)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6043#-:-O2TreRjAMptLe0lAsxT:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Draggu)

**Pull request merged**
