### PR TITLE
Made cairo-level test errors more explicit.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:bfb115d6

---

**Stack**:
- #1200
- #1199
- #1194
- #1190 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1190#-:-NIBr97C6RcVduDyYcpI:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @orizi)

___
*[`tests/cairo_level_tests.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1190#-NIBqdtXAZfu9JMIO464:-NIBqdtXAZfu9JMIO465:b2f52qx) ([raw file](https://github.com/starkware-libs/cairo/blob/92e946d4ee0d6978c9385ca3f11528a1f571151a/tests/cairo_level_tests.rs#L18)):*
> ```XML
> 
> /// Converts a bigint to u64.
> fn bigint_to_uint64(num: &BigInt) -> u64 {
> ```

Don't we have a try_into() for this?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1190)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`tests/cairo_level_tests.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1190#-NIBzBf14n8DtO2UtL81:-NIBzBf14n8DtO2UtL82:b-jv3kd9) ([raw file](https://github.com/starkware-libs/cairo/blob/92e946d4ee0d6978c9385ca3f11528a1f571151a/tests/cairo_level_tests.rs#L35)):*
> ```XML
>         replace_sierra_ids_in_program(&db, &db.get_sierra_program(main_crate_ids).unwrap());
>     let instructions = get_runnable_casm(&sierra_program, &[], false);
>     let (cells, ap) = run_function(instructions).unwrap();
> ```

would this work? the `cells[ap - X]` is harder to read
```
let (err_code, err_data_start_or_test_count, err_data_end) = 
    run_function_return_values(instructions, 3).unwrap();
```



_Code quote:_
```XML
let (cells, ap) = run_function(instructions).unwrap();
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1190)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @spapinistarkware)

___
*[`tests/cairo_level_tests.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1190#-NIBqdtXAZfu9JMIO464:-NICI2GvBWzL5PVVhJso:bxk8a8a) ([raw file](https://github.com/starkware-libs/cairo/blob/92e946d4ee0d6978c9385ca3f11528a1f571151a/tests/cairo_level_tests.rs#L18)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Don't we have a try_into() for this?
</blockquote></details>

I haven't seen one
___
*[`tests/cairo_level_tests.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1190#-NIBzBf14n8DtO2UtL81:-NICHqfV19eX-x9sDBAv:b-agya2r) ([raw file](https://github.com/starkware-libs/cairo/blob/92e946d4ee0d6978c9385ca3f11528a1f571151a/tests/cairo_level_tests.rs#L35)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

would this work? the `cells[ap - X]` is harder to read
```
let (err_code, err_data_start_or_test_count, err_data_end) = 
    run_function_return_values(instructions, 3).unwrap();
```
</blockquote></details>

Not really

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1190)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`tests/cairo_level_tests.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1190#-NIBzBf14n8DtO2UtL81:-NICMBSx2LZxbOCgVrJ0:b8zcqi) ([raw file](https://github.com/starkware-libs/cairo/blob/92e946d4ee0d6978c9385ca3f11528a1f571151a/tests/cairo_level_tests.rs#L35)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Not really
</blockquote></details>

ah... no auto unpacking for unknown length of RHS? `match` would work though, no?
because if this code ends up being the core of flow test framework I think it's worth making it more readable

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1190)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @spapinistarkware)

___
*[`tests/cairo_level_tests.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1190#-NIBzBf14n8DtO2UtL81:-NICYLmF1rvdtTbToSC0:b-iwzpnu) ([raw file](https://github.com/starkware-libs/cairo/blob/92e946d4ee0d6978c9385ca3f11528a1f571151a/tests/cairo_level_tests.rs#L35)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ah... no auto unpacking for unknown length of RHS? `match` would work though, no?
because if this code ends up being the core of flow test framework I think it's worth making it more readable
</blockquote></details>

note this is access at ap index - there's no relevant unpacking here.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1190)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1190)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1190)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1190)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1190)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1190)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`tests/cairo_level_tests.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1190#-NIBqdtXAZfu9JMIO464:-NIDa2wr-PcMYq6GK6Im:b-28sd7u) ([raw file](https://github.com/starkware-libs/cairo/blob/92e946d4ee0d6978c9385ca3f11528a1f571151a/tests/cairo_level_tests.rs#L18)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I haven't seen one
</blockquote></details>

oh - cool `u64::try_from(num).unwrap()` works.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1190)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1190)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1190#-:-NIDn7dsD2i8aPVM9dDZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1190)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
