### PR TITLE
Merge sierra minor update into coupons

### PR DESCRIPTION
**Pull request by liorgold2**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4667)

### CODE REVIEW

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 122 of 122 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4667)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4667)* status: 122 of 123 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`tests/e2e_test_data/metadata_computation` line 1577 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4667#-NmfK4Rh59ijw4nbKKVs:-NmfMXhU7L9z-KypRatZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/450fc2fb53e3f0d5c2aba335d1e81b12b8e227b1/tests/e2e_test_data/metadata_computation#L1577)):*
> ```
> test::foo: 4
> 
> //! > ap_solution_no_solver
> ```

Done.

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4667)* status: 122 of 123 files reviewed, 2 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4667#-NmfMdEM3BMcQZuZWPFL:-NmfMdEN0wBdliUrTe9X:bxjj1y5) (no related file):*
Merge instead of squash

___

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4667#-:-NmfOkt23QZeTdrrBh3d:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Review by liorgold2 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4667)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
