### PR TITLE
adding libfuncs coverage

### PR DESCRIPTION
**Pull request by Tomer-StarkWare**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6184)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6184)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/contracts/libfuncs_coverage.cairo` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6184#-O4-fb9Z7Q6jG9Nzv4I5:-O4-fb9Z7Q6jG9Nzv4I6:befxalp) ([raw file](https://github.com/starkware-libs/cairo/blob/03db3da234682965f8710d644e13e0fdf452d35b/crates/cairo-lang-starknet/cairo_level_tests/contracts/libfuncs_coverage.cairo#L32)):*
> ```Cairo
>     I32: SignedIntLibfuncs<i32>,
>     I64: SignedIntLibfuncs<i64>,
>     I128: SignedIntLibfuncs<i128>,
> ```

revert all the signed parts.



_Code quote:_
```Cairo
    I8: SignedIntLibfuncs<i8>,
    I16: SignedIntLibfuncs<i16>,
    I32: SignedIntLibfuncs<i32>,
    I64: SignedIntLibfuncs<i64>,
    I128: SignedIntLibfuncs<i128>,
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6184)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/contracts/libfuncs_coverage.cairo` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6184#-O4-fb9Z7Q6jG9Nzv4I5:-O4-hb2I2-Fv-Rd5zFyH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/03db3da234682965f8710d644e13e0fdf452d35b/crates/cairo-lang-starknet/cairo_level_tests/contracts/libfuncs_coverage.cairo#L32)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

revert all the signed parts.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6184)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/contracts/libfuncs_coverage.cairo` line 6 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6184#-O4-lIjv5-97MAC7EfD0:-O4-lIjv5-97MAC7EfD1:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/1e6843fbbb453552918b5ce11f591870261e1d6e/crates/cairo-lang-starknet/cairo_level_tests/contracts/libfuncs_coverage.cairo#L6)):*
> ```Cairo
> use core::result::ResultTrait;
> #[starknet::contract]
> mod libfuncs_coverage {
> ```





_Suggestion:_
```Cairo
use starknet::storage::StoragePathEntry;
use starknet::storage::StoragePointerWriteAccess;
use starknet::storage::StoragePointerReadAccess;

#[starknet::contract]
mod libfuncs_coverage {
```
___
*[`crates/cairo-lang-starknet/cairo_level_tests/contracts/libfuncs_coverage.cairo` line 270 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6184#-O4-lDZh1adLDes2jVwt:-O4-lDZh1adLDes2jVwu:buzc583) ([raw file](https://github.com/starkware-libs/cairo/blob/1e6843fbbb453552918b5ce11f591870261e1d6e/crates/cairo-lang-starknet/cairo_level_tests/contracts/libfuncs_coverage.cairo#L270)):*
> ```Cairo
>         }
>     }
> }
> ```

unused.



_Code quote:_
```Cairo
/// Represents the result of checking whether a value is zero.
#[derive(Drop)]
pub(crate) enum IsZeroResult<T> {
    /// Indicates that the value is zero.
    Zero,
    /// Indicates that the value is non-zero, wrapping it in a NonZero<T>.
    NonZero: NonZero<T>,
}

extern fn i8_is_zero(a: i8) -> IsZeroResult<i8> implicits() nopanic;
extern fn i16_is_zero(a: i16) -> IsZeroResult<i16> implicits() nopanic;
extern fn i32_is_zero(a: i32) -> IsZeroResult<i32> implicits() nopanic;
extern fn i64_is_zero(a: i64) -> IsZeroResult<i64> implicits() nopanic;
extern fn i128_is_zero(a: i128) -> IsZeroResult<i128> implicits() nopanic;


trait IsZero<T> {
    /// Checks if the value is zero.
    fn is_zero(self: T) -> bool;
}

impl I8IsZero of IsZero<i8> {
    #[inline(always)]
    fn is_zero(self: i8) -> bool {
        if let IsZeroResult::Zero = i8_is_zero(self) {
            true
        } else {
            false
        }
    }
}

impl I16IsZero of IsZero<i16> {
    #[inline(always)]
    fn is_zero(self: i16) -> bool {
        if let IsZeroResult::Zero = i16_is_zero(self) {
            true
        } else {
            false
        }
    }
}

impl I32IsZero of IsZero<i32> {
    #[inline(always)]
    fn is_zero(self: i32) -> bool {
        if let IsZeroResult::Zero = i32_is_zero(self) {
            true
        } else {
            false
        }
    }
}

impl I64IsZero of IsZero<i64> {
    #[inline(always)]
    fn is_zero(self: i64) -> bool {
        if let IsZeroResult::Zero = i64_is_zero(self) {
            true
        } else {
            false
        }
    }
}

impl I128IsZero of IsZero<i128> {
    #[inline(always)]
    fn is_zero(self: i128) -> bool {
        if let IsZeroResult::Zero = i128_is_zero(self) {
            true
        } else {
            false
        }
    }
}
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6184)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/contracts/libfuncs_coverage.cairo` line 6 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6184#-O4-lIjv5-97MAC7EfD0:-O4-xEvo3HFpb87csSpC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1e6843fbbb453552918b5ce11f591870261e1d6e/crates/cairo-lang-starknet/cairo_level_tests/contracts/libfuncs_coverage.cairo#L6)):*
> ```Cairo
> use core::result::ResultTrait;
> #[starknet::contract]
> mod libfuncs_coverage {
> ```

Done.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/contracts/libfuncs_coverage.cairo` line 270 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6184#-O4-lDZh1adLDes2jVwt:-O4-xLet7INNhPYwNb33:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1e6843fbbb453552918b5ce11f591870261e1d6e/crates/cairo-lang-starknet/cairo_level_tests/contracts/libfuncs_coverage.cairo#L270)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

unused.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6184#-:-O4-yua9AEpEZXGdTsnC:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6184)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Tomer-StarkWare)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6184#-:-O4-zTu76QP6wEv5iFs1:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Tomer-StarkWare)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6184)* status: all files reviewed, 2 unresolved discussions (waiting on @Tomer-StarkWare)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6184#-O40JKy48U7s2CV9AqMN:-O40JKy48U7s2CV9AqMO:b-o28q5b) (no related file):*
please rebase  -the current version includes data from a merged commit.

___
___
*[`crates/cairo-lang-starknet/cairo_level_tests/contracts/libfuncs_coverage.cairo` line 4 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6184#-O40JRiT0tBILDlyn_gL:-O40JRiT0tBILDlyn_gM:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f0700f932c877a0a5a12b57c8de9ad80c2ded58a/crates/cairo-lang-starknet/cairo_level_tests/contracts/libfuncs_coverage.cairo#L4)):*
> ```Cairo
> use starknet::storage::StoragePointerWriteAccess;
> use starknet::storage::StoragePointerReadAccess;
> #[starknet::contract]
> ```





_Suggestion:_
```Cairo
use starknet::storage::StoragePointerReadAccess;

#[starknet::contract]
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6184)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/contracts/libfuncs_coverage.cairo` line 48 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6184#-O40OzThANYrp9dYBfne:-O40OzTi-6S5FW69eNKP:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2dc349a3f13fd862ad9bac8483f7f178ec9ce7b8/crates/cairo-lang-starknet/cairo_level_tests/contracts/libfuncs_coverage.cairo#L48)):*
> ```Cairo
> 
> 
> enum NumericLibfuncs<T> {
> ```





_Suggestion:_
```Cairo
use starknet::storage::StoragePointerWriteAccess;
use starknet::storage::StoragePointerReadAccess;

#[starknet::contract]
mod libfuncs_coverage {
    #[storage]
    struct Storage {}
    Starknet: StarknetLibfuncs,
}

enum NumericLibfuncs<T> {
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6184)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6184#-O40JKy48U7s2CV9AqMN:-O40QeTj1Udoawh1JPG9:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

please rebase  -the current version includes data from a merged commit.
</blockquote></details>

Done.

___
___
*[`crates/cairo-lang-starknet/cairo_level_tests/contracts/libfuncs_coverage.cairo` line 4 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6184#-O40JRiT0tBILDlyn_gL:-O40R0_l63QAgoLvK-kJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f0700f932c877a0a5a12b57c8de9ad80c2ded58a/crates/cairo-lang-starknet/cairo_level_tests/contracts/libfuncs_coverage.cairo#L4)):*
> ```Cairo
> use starknet::storage::StoragePointerWriteAccess;
> use starknet::storage::StoragePointerReadAccess;
> #[starknet::contract]
> ```

Done.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/contracts/libfuncs_coverage.cairo` line 48 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6184#-O40OzThANYrp9dYBfne:-O40RXUGBMG1EDNeAD7N:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2dc349a3f13fd862ad9bac8483f7f178ec9ce7b8/crates/cairo-lang-starknet/cairo_level_tests/contracts/libfuncs_coverage.cairo#L48)):*
> ```Cairo
> 
> 
> enum NumericLibfuncs<T> {
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6184)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/contracts/libfuncs_coverage.cairo` line 4 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6184#-O40JRiT0tBILDlyn_gL:-O40SWrc6SBXLUr1IbqB:b21f6l4) ([raw file](https://github.com/starkware-libs/cairo/blob/f0700f932c877a0a5a12b57c8de9ad80c2ded58a/crates/cairo-lang-starknet/cairo_level_tests/contracts/libfuncs_coverage.cairo#L4)):*
<details><summary><i>Previously, Tomer-StarkWare (TomerC-StarkWare) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

no it isn't.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/contracts/libfuncs_coverage.cairo` line 48 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6184#-O40OzThANYrp9dYBfne:-O40SZ-w1DNk24uucpgb:b21f6l4) ([raw file](https://github.com/starkware-libs/cairo/blob/2dc349a3f13fd862ad9bac8483f7f178ec9ce7b8/crates/cairo-lang-starknet/cairo_level_tests/contracts/libfuncs_coverage.cairo#L48)):*
<details><summary><i>Previously, Tomer-StarkWare (TomerC-StarkWare) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

no it isn't.

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6184)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/contracts/libfuncs_coverage.cairo` line 4 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6184#-O40JRiT0tBILDlyn_gL:-O40Vurz4jUG5ICnMlXy:b-j7cpkk) ([raw file](https://github.com/starkware-libs/cairo/blob/f0700f932c877a0a5a12b57c8de9ad80c2ded58a/crates/cairo-lang-starknet/cairo_level_tests/contracts/libfuncs_coverage.cairo#L4)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no it isn't.
</blockquote></details>

Sorry, is now, my bad, didn't notice I didn't push
___
*[`crates/cairo-lang-starknet/cairo_level_tests/contracts/libfuncs_coverage.cairo` line 48 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6184#-O40OzThANYrp9dYBfne:-O40Voa7AOpnT_aYwZ1X:b-j7cpkk) ([raw file](https://github.com/starkware-libs/cairo/blob/2dc349a3f13fd862ad9bac8483f7f178ec9ce7b8/crates/cairo-lang-starknet/cairo_level_tests/contracts/libfuncs_coverage.cairo#L48)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no it isn't.
</blockquote></details>

Sorry, is now, my bad, didn't notice I didn't push

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6184#-:-O40WBANBazRYMYrfFoy:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @Tomer-StarkWare)

**Pull request merged**
