### PR TITLE
Handling use star in Semantics.

### PR DESCRIPTION
**Pull request by Tomer-StarkWare**

### CODE REVIEW

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6592)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @orizi and @Tomer-StarkWare)

___
*[`crates/cairo-lang-defs/src/db.rs` line 801 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6592#-OAwXlt_2s5mteV00peo:-OAwXlt_2s5mteV00pep:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/fe472175ccd60484ba290df4a029807a1b254bf3/crates/cairo-lang-defs/src/db.rs#L801)):*
> ```XML
> 
> /// Returns all the path star under a given use item.
> /// Notice that UsePath::Star is not returned here.
> ```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6592)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 1062 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6592#-OAwgVjnAw7EKFWET-am:-OAwgVjnAw7EKFWET-an:b-hdg54o) ([raw file](https://github.com/starkware-libs/cairo/blob/fe472175ccd60484ba290df4a029807a1b254bf3/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L1062)):*
> ```
> )
> 
> //! > expected_diagnostics
> ```

add a proper test.

this doesn;t actually use `a::b::*;`

add a test that  gets diagnostics if the use path is bad.



_Code quote:_
```
//! > ==========================================================================

//! > Testing use star

//! > test_runner_name
test_expr_semantics(expect_diagnostics: false)

//! > module_code
pub mod generic_type {
    pub struct S {
        pub x: u8,
    }
    pub enum E {
        A: u8,
        B: u16,
    }
}

use generic_type::*;

//! > function_body

//! > expr_code
{

}

//! > expected_semantics
Block(
    ExprBlock {
        statements: [],
        tail: None,
        ty: (),
    },
)

//! > expected_diagnostics
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6592)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 1062 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6592#-OAwgVjnAw7EKFWET-am:-OBKAq2I5ddwL83ibno3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fe472175ccd60484ba290df4a029807a1b254bf3/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L1062)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add a proper test.

this doesn;t actually use `a::b::*;`

add a test that  gets diagnostics if the use path is bad.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-defs/src/db.rs` line 801 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6592#-OAwXlt_2s5mteV00peo:-OBKAp0FBXuiDPv_3iRC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fe472175ccd60484ba290df4a029807a1b254bf3/crates/cairo-lang-defs/src/db.rs#L801)):*
> ```XML
> 
> /// Returns all the path star under a given use item.
> /// Notice that UsePath::Star is not returned here.
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6592)* status: all files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-defs/src/db.rs` line 801 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6592#-OBKIxu-5xXFDdHuaOB_:-OBKIxu-5xXFDdHuaOBa:bfxqua1) ([raw file](https://github.com/starkware-libs/cairo/blob/e4048a1c76abca4199aa6b58314ab8f0f534b871/crates/cairo-lang-defs/src/db.rs#L801)):*
> ```XML
> 
> /// Returns all the path star under a given use item.
> /// Notice that UsePath::Leaf is not returned here.
> ```

how are the `Notice` thing relevant?
remove/



_Suggestion:_
```XML
/// Returns all the path leaves under a given use item.
pub fn get_all_path_leaves(db: &dyn SyntaxGroup, use_item: &ast::ItemUse) -> Vec<ast::UsePathLeaf> {
    let mut res = vec![];
    let mut stack = vec![use_item.use_path(db)];
    while let Some(use_path) = stack.pop() {
        match use_path {
            ast::UsePath::Leaf(use_path) => res.push(use_path),
            ast::UsePath::Single(use_path) => stack.push(use_path.use_path(db)),
            ast::UsePath::Multi(use_path) => {
                stack.extend(use_path.use_paths(db).elements(db).into_iter().rev())
            }
            ast::UsePath::Star(_) => {}
        }
    }
    res
}

/// Returns all the path stars under a given use item.
```
___
*[`crates/cairo-lang-defs/src/db.rs` line 892 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6592#-OBKJwUp-C0sYcdwe8-0:-OBKJwUp-C0sYcdwe8-1:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e4048a1c76abca4199aa6b58314ab8f0f534b871/crates/cairo-lang-defs/src/db.rs#L892)):*
> ```XML
> }
> pub fn module_global_use_by_id(
>     db: &dyn DefsGroup,
> ```





_Suggestion:_
```XML
    let module_uses = db.module_uses(use_id.module_file_id(db.upcast()).0)?;
    Ok(module_uses.get(&use_id).cloned())
}

pub fn module_global_use_by_id(
    db: &dyn DefsGroup,
```
___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 1028 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6592#-OBKJCix1YfL7xj-Wkkq:-OBKJCix1YfL7xj-Wkkr:b-d1sgm7) ([raw file](https://github.com/starkware-libs/cairo/blob/e4048a1c76abca4199aa6b58314ab8f0f534b871/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L1028)):*
> ```
> //! > ==========================================================================
> 
> //! > Testing use star without implementation in Semantic
> ```

Add a TODO stating this gives a bad result for now.
___
*[`crates/cairo-lang-semantic/src/items/module.rs` line 115 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6592#-OBKKRLh01hNOuSgAyll:-OBKKRLh01hNOuSgAylm:b-dyld7g) ([raw file](https://github.com/starkware-libs/cairo/blob/e4048a1c76abca4199aa6b58314ab8f0f534b871/crates/cairo-lang-semantic/src/items/module.rs#L115)):*
> ```XML
>         }
>     }
>     let global_uses = db.module_global_uses(module_id)?.keys().copied().collect::<Vec<_>>();
> ```

the visiblity of global uses is also required to be part of the semantic data.

you probably need a `pub global_uses: OrderedHashMap<GlobalUseId, Visibility>`,



_Code quote:_
```XML
    let global_uses = db.module_global_uses(module_id)?.keys().copied().collect::<Vec<_>>();
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6592)* status: 5 of 8 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-defs/src/db.rs` line 801 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6592#-OBKIxu-5xXFDdHuaOB_:-OBKxXjHA_kIa-qWhMZy:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e4048a1c76abca4199aa6b58314ab8f0f534b871/crates/cairo-lang-defs/src/db.rs#L801)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

how are the `Notice` thing relevant?
remove/
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 1028 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6592#-OBKJCix1YfL7xj-Wkkq:-OBLPMM1572HqfdNpxs2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e4048a1c76abca4199aa6b58314ab8f0f534b871/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L1028)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Add a TODO stating this gives a bad result for now.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/module.rs` line 115 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6592#-OBKKRLh01hNOuSgAyll:-OBLPQ2a5jx5afLPwr_H:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e4048a1c76abca4199aa6b58314ab8f0f534b871/crates/cairo-lang-semantic/src/items/module.rs#L115)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the visiblity of global uses is also required to be part of the semantic data.

you probably need a `pub global_uses: OrderedHashMap<GlobalUseId, Visibility>`,
</blockquote></details>

Done.
___
*[`crates/cairo-lang-defs/src/db.rs` line 892 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6592#-OBKJwUp-C0sYcdwe8-0:-OBKyXVWBIsrylrxtCud:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e4048a1c76abca4199aa6b58314ab8f0f534b871/crates/cairo-lang-defs/src/db.rs#L892)):*
> ```XML
> }
> pub fn module_global_use_by_id(
>     db: &dyn DefsGroup,
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6592)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/items/module.rs` line 38 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6592#-OBLfD0B0McgE8KvWAMv:-OBLfD0B0McgE8KvWAMw:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/3867f9676a71dd0427ec4cb1228815fd9eb5844f/crates/cairo-lang-semantic/src/items/module.rs#L38)):*
> ```XML
>     pub global_uses: OrderedHashMap<GlobalUseId, cairo_lang_syntax::node::ast::Visibility>,
>     pub diagnostics: Diagnostics<SemanticDiagnostic>,
> }
> ```





_Suggestion:_
```XML
    pub items: OrderedHashMap<SmolStr, ModuleItemInfo>,
    pub global_uses: OrderedHashMap<GlobalUseId, Visibility>,
    pub diagnostics: Diagnostics<SemanticDiagnostic>,
}
```
___
*[`crates/cairo-lang-semantic/src/items/module.rs` line 123 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6592#-OBLfOdj0f5-R1jM25eX:-OBLfOdj0f5-R1jM25eY:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/3867f9676a71dd0427ec4cb1228815fd9eb5844f/crates/cairo-lang-semantic/src/items/module.rs#L123)):*
> ```XML
>             (*global_use_id, item.visibility(syntax_db))
>         })
>         .collect();
> ```





_Suggestion:_
```XML
    let global_uses = db
        .module_global_uses(module_id)?
        .iter()
        .map(|(global_use_id, use_path_star)| {
            let item = ast::UsePath::Star(use_path_star.clone()).get_item(syntax_db);
            (*global_use_id, Visibility::from_ast(db.upcast(), &mut diagnostics, &item.visibility(syntax_db)))
        })
        .collect();
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6592#-:-OBLi3bf4Gs4LHhgu82L:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6592)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/items/module.rs` line 122 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6592#-OBQMth1AcMm2PRenpsZ:-OBQMth1AcMm2PRenps_:b-pesw4u) ([raw file](https://github.com/starkware-libs/cairo/blob/a632be5232f14b131ef174ea55d5f9a5bf68f663/crates/cairo-lang-semantic/src/items/module.rs#L122)):*
> ```XML
>             let item = ast::UsePath::Star(use_path_star.clone()).get_item(syntax_db);
>             let visibility = item.visibility(syntax_db);
>             if !matches!(visibility, ast::Visibility::Default(_)) {
> ```

add TODO to consider adding these.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:
:lgtm:

> Reviewed 3 of 8 files at r1, 3 of 4 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6592#-:-OBUyVHO5EGMRQeHBkZL:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Tomer-StarkWare)

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6592)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/items/module.rs` line 122 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6592#-OBQMth1AcMm2PRenpsZ:-OBa5dJsBAQS8tGp4r6H:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a632be5232f14b131ef174ea55d5f9a5bf68f663/crates/cairo-lang-semantic/src/items/module.rs#L122)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add TODO to consider adding these.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6592)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Tomer-StarkWare)

**Pull request merged**
