### PR TITLE
Validate that each statement belongs to 1 function.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1786)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1786)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1786#-NLyRjyv-Am1e-i2UXpT:-NLyRjyv-Am1e-i2UXpU:b4s51zj) ([raw file](https://github.com/starkware-libs/cairo/blob/0cc29e6c0c792504fdf6017a48c55fca7a4fd0a9/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L78)):*
> ```XML
>     pub refs: StatementRefs,
>     // The index of the function in the ProgramAnnotations.functions.
>     pub function_idx: usize,
> ```

I don't know if I should use the function id or function idx here :(



_Code quote:_
```XML
  pub function_idx: usize,
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1786)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1786#-NLybcOe9H1OjkgCmY0i:-NLybcOe9H1OjkgCmY0j:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0cc29e6c0c792504fdf6017a48c55fca7a4fd0a9/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L77)):*
> ```XML
> pub struct StatementAnnotations {
>     pub refs: StatementRefs,
>     // The index of the function in the ProgramAnnotations.functions.
> ```





_Suggestion:_
```XML
    /// The index of the function in the ProgramAnnotations.functions.
```
___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1786#-NLyRjyv-Am1e-i2UXpT:-NLybRlaBlkIerunnubn:bfeg8kc) ([raw file](https://github.com/starkware-libs/cairo/blob/0cc29e6c0c792504fdf6017a48c55fca7a4fd0a9/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L78)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't know if I should use the function id or function idx here :(
</blockquote></details>

since it is in context that does not enforce id == idx - id is probably better.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1786)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1786#-NLybcOe9H1OjkgCmY0i:-NLyv1F5EH9-XwEklAm8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0cc29e6c0c792504fdf6017a48c55fca7a4fd0a9/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L77)):*
> ```XML
> pub struct StatementAnnotations {
>     pub refs: StatementRefs,
>     // The index of the function in the ProgramAnnotations.functions.
> ```

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1786#-NLyRjyv-Am1e-i2UXpT:-NLyuhVa-9uMsYhd-xR-:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/0cc29e6c0c792504fdf6017a48c55fca7a4fd0a9/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L78)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

since it is in context that does not enforce id == idx - id is probably better.
</blockquote></details>

done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1786#-:-NLz0U9C5syf6ekTmLak:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1786)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
