### PR TITLE
Added more basic validation when building program registry.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #4622
- #4616 ⬅
- #4596

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4616)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra/src/program_registry.rs` line 152 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4616#-NmPll3q4gALBSOpSsfW:-NmPll3r4hsY46Vtkfr4:bjq5nf4) ([raw file](https://github.com/starkware-libs/cairo/blob/24ee5b2eba3c3d47f80aed66249b39c10e70055a/crates/cairo-lang-sierra/src/program_registry.rs#L152)):*
> ```XML
>             };
>             let libfunc = self.get_libfunc(&invocation.libfunc_id)?;
>             if invocation.args.len() != libfunc.param_signatures().len() {
> ```

isn't it checked here:
https://github.com/starkware-libs/cairo/blob/ae9704426bbbe661ca7d13d721cd32955a129c9b/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L88



_Code quote:_
```XML
  if invocation.args.len() != libfunc.param_signatures().len() {
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4616)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/program_registry.rs` line 152 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4616#-NmPll3q4gALBSOpSsfW:-NmPmFSV0YlKtYTubF01:b-hee0y3) ([raw file](https://github.com/starkware-libs/cairo/blob/24ee5b2eba3c3d47f80aed66249b39c10e70055a/crates/cairo-lang-sierra/src/program_registry.rs#L152)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

isn't it checked here:
https://github.com/starkware-libs/cairo/blob/ae9704426bbbe661ca7d13d721cd32955a129c9b/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L88
</blockquote></details>

it is - but it is much later in the compilation process.
checks that happen here are before thing that are sierra-target dependent stuff happening.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra/src/program_registry.rs` line 152 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4616#-NmPll3q4gALBSOpSsfW:-NmPuKqwEqeHN1_3e35-:blvqhbg) ([raw file](https://github.com/starkware-libs/cairo/blob/24ee5b2eba3c3d47f80aed66249b39c10e70055a/crates/cairo-lang-sierra/src/program_registry.rs#L152)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it is - but it is much later in the compilation process.
checks that happen here are before thing that are sierra-target dependent stuff happening.
</blockquote></details>

what is the `sierra-target dependent stuff`?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4616)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/program_registry.rs` line 152 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4616#-NmPll3q4gALBSOpSsfW:-NmPwi9DBpwTjTUbiYQy:b-1y676h) ([raw file](https://github.com/starkware-libs/cairo/blob/24ee5b2eba3c3d47f80aed66249b39c10e70055a/crates/cairo-lang-sierra/src/program_registry.rs#L152)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what is the `sierra-target dependent stuff`?
</blockquote></details>

sizes of variable, actual costs of libfuncs and so on.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra/src/program_registry.rs` line 152 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4616#-NmPll3q4gALBSOpSsfW:-NmQ6k7VCu-OBH3qLjFF:b-6sih4s) ([raw file](https://github.com/starkware-libs/cairo/blob/24ee5b2eba3c3d47f80aed66249b39c10e70055a/crates/cairo-lang-sierra/src/program_registry.rs#L152)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

sizes of variable, actual costs of libfuncs and so on.
</blockquote></details>

CAn you move it to a function and document that all those checks are redundant?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-to-casm/src/compiler_test.rs` line 558 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4616#-NmQ6sD15O9O7ONcj2wo:-NmQ6sD15O9O7ONcj2wp:b3jgt1j) ([raw file](https://github.com/starkware-libs/cairo/blob/78b26206a2ed57f450a190de2b570fe34113d04c/crates/cairo-lang-sierra-to-casm/src/compiler_test.rs#L558)):*
> ```XML
>                 return();
>                 test_program@0([1]: felt252, [2]: felt252, [3]: felt252) -> ();
>             "}, "#0: Invocation mismatched to libfunc";
> ```

you broke this test



_Code quote:_
```XML
   "}, "#0: Invocation mismatched to libfunc";
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4616)* status: 0 of 13 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler_test.rs` line 558 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4616#-NmQ6sD15O9O7ONcj2wo:-NmQ8X0LC7um0y50k0K0:b-bmiva) ([raw file](https://github.com/starkware-libs/cairo/blob/78b26206a2ed57f450a190de2b570fe34113d04c/crates/cairo-lang-sierra-to-casm/src/compiler_test.rs#L558)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

you broke this test
</blockquote></details>

no i haven't - that is the same error - just earlier.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4616)* status: 0 of 13 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/program_registry.rs` line 152 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4616#-NmPll3q4gALBSOpSsfW:-NmQ8vHeDCMnCp0lHQwq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/24ee5b2eba3c3d47f80aed66249b39c10e70055a/crates/cairo-lang-sierra/src/program_registry.rs#L152)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

CAn you move it to a function and document that all those checks are redundant?
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-to-casm/src/compiler_test.rs` line 558 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4616#-NmQ6sD15O9O7ONcj2wo:-NmQsAyMEv-bmxlw_8zR:b-hud1zl) ([raw file](https://github.com/starkware-libs/cairo/blob/78b26206a2ed57f450a190de2b570fe34113d04c/crates/cairo-lang-sierra-to-casm/src/compiler_test.rs#L558)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no i haven't - that is the same error - just earlier.
</blockquote></details>

I meant that there is no test for the second check.

Is that intended? are we going to remove the second check?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4616)* status: 0 of 13 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler_test.rs` line 558 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4616#-NmQ6sD15O9O7ONcj2wo:-NmQtjqp8Mv-0G3LvTVu:b-ecoc49) ([raw file](https://github.com/starkware-libs/cairo/blob/78b26206a2ed57f450a190de2b570fe34113d04c/crates/cairo-lang-sierra-to-casm/src/compiler_test.rs#L558)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I meant that there is no test for the second check.

Is that intended? are we going to remove the second check?
</blockquote></details>

it can be removed now - if we decide to do it is another question, i'm fine with it.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 13 files at r1, 10 of 11 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4616)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/program_registry.rs` line 135 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4616#-NmQuS1HA2svfQlPgKYu:-NmQuS1HA2svfQlPgKYv:b-519unx) ([raw file](https://github.com/starkware-libs/cairo/blob/f82420e1e46510ff821dfe34b41ecaf25a8135d8/crates/cairo-lang-sierra/src/program_registry.rs#L135)):*
> ```XML
>     /// Checks the validity of the [ProgramRegistry].
>     ///
>     /// Checks that all the parameter and return types are storable.
> ```

Update the comment to mention that it checks that program.



_Code quote:_
```XML
    /// Checks the validity of the [ProgramRegistry].
    ///
    /// Checks that all the parameter and return types are storable.
```
___
*[`crates/cairo-lang-sierra/src/program_registry.rs` line 156 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4616#-NmQr2IkDGcklEgdbOSD:-NmQr2IkDGcklEgdbOSE:b-omxgsu) ([raw file](https://github.com/starkware-libs/cairo/blob/f82420e1e46510ff821dfe34b41ecaf25a8135d8/crates/cairo-lang-sierra/src/program_registry.rs#L156)):*
> ```XML
>     ///
>     /// Some of the checks may be checked again later, but this is a good place to fail early, as
>     /// well as document most ways  describing a valid sierra program.
> ```

I find "document most ways  describing a valid sierra program." confusing



_Suggestion:_
```XML
    /// Some of the checks may be checked again later, but this is a good place to fail early.
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4616)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/program_registry.rs` line 156 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4616#-NmQr2IkDGcklEgdbOSD:-NmQyFxG8mrj55dfYGKP:b-ibt7pr) ([raw file](https://github.com/starkware-libs/cairo/blob/f82420e1e46510ff821dfe34b41ecaf25a8135d8/crates/cairo-lang-sierra/src/program_registry.rs#L156)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I find "document most ways  describing a valid sierra program." confusing
</blockquote></details>

rephrased and moved.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4616)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/program_registry.rs` line 135 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4616#-NmQuS1HA2svfQlPgKYu:-NmQyL3FAHUvC9wGVREP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f82420e1e46510ff821dfe34b41ecaf25a8135d8/crates/cairo-lang-sierra/src/program_registry.rs#L135)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Update the comment to mention that it checks that program.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4616)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/program_registry.rs` line 135 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4616#-NmR3ryp9d9CgFasQUfv:-NmR3ryp9d9CgFasQUfw:b-37o0wj) ([raw file](https://github.com/starkware-libs/cairo/blob/9fc5bf1fccd6716df1371a9b3b1855568b568a15/crates/cairo-lang-sierra/src/program_registry.rs#L135)):*
> ```XML
>     /// Checks the validity of the [ProgramRegistry].
>     ///
>     /// This validation attempt to validate that this is a valid Sierra program.
> ```

you changed this to check the program as wll.



_Suggestion:_
```XML
    /// Checks the validity of the ProgramRegistry and runs basic validations on the program.
   
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4616)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/program_registry.rs` line 135 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4616#-NmR3ryp9d9CgFasQUfv:-NmR5h8i9zFh7HoY_kDl:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9fc5bf1fccd6716df1371a9b3b1855568b568a15/crates/cairo-lang-sierra/src/program_registry.rs#L135)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

you changed this to check the program as wll.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4616#-:-NmR8QAi3876b-djRf3H:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
