### PR TITLE
Core Lib Documentation: `fmt` module

### PR DESCRIPTION
**Pull request by TAdev0**

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6652)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @TAdev0)

___
*[`corelib/src/fmt.cairo` line 230 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6652#-OBamWl59NiKLl0Qc6wN:-OBamWl59NiKLl0Qc6wO:bci3kn3) ([raw file](https://github.com/starkware-libs/cairo/blob/4a674b58e65f67a5c521f81ac4c34710dee53202/corelib/src/fmt.cairo#L230)):*
> ```Cairo
> 
> /// `Debug` impl for fixed sized arrays of size 2 and above.
> /// Not starting from size 1 since we have a special case for 0.
> ```

This is useful to understand the code here.

you possibly only want to remove the `///` and make it `//`.



_Code quote:_
```Cairo
/// `Debug` impl for fixed sized arrays of size 2 and above.
/// Not starting from size 1 since we have a special case for 0.
```

**Comment by TAdev0** [comment]
@orizi  just address your comments. I restore the comment under `//` for `TupleDebugHelperTupleNext` and `TupleDebugHelperFixedSizedArrayNext`. But i think they were originally wrong, I modified them, tell me if its fine.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6652#-:-OBjom5X99jShCyIy4BR:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TAdev0)

**Comment by TAdev0** [comment]
@orizi  can also be added to the merge queue I suppose?

**Pull request merged**
