### PR TITLE
Move test contracts to the contracts crate and adjust the tests accor…

### PR DESCRIPTION
**Pull request by gilbens-starkware**
…dingly.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4218)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 10 of 60 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4218)* status: 10 of 60 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/upgradable_counter` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4218#-NgELQiS8ShyAtQqdAQa:-NgELQiS8ShyAtQqdAQb:b1ijekb) ([raw file](https://github.com/starkware-libs/cairo/blob/b337a69bc2f87a126379de02e9c851700f090d0f/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/upgradable_counter#L17)):*
> ```
> }
> 
> #[starknet::component]
> ```

Why is the component code included?

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4218)* status: 10 of 60 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/upgradable_counter` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4218#-NgELQiS8ShyAtQqdAQa:-NgIInq915tzrIc2oVw4:b3iejyz) ([raw file](https://github.com/starkware-libs/cairo/blob/b337a69bc2f87a126379de02e9c851700f090d0f/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/upgradable_counter#L17)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Why is the component code included?
</blockquote></details>

In this PR I mostly moved the files, the components are removed in #4219 .

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 39 of 60 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4218#-:-NgIJ_Gy80-o8QS-7IRI:bnfp4nl)* status: 49 of 60 files reviewed, all discussions resolved

**Review by orizi — APPROVED** [review]
> Reviewed 13 of 60 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4218)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
