### PR TITLE
refactoring statement const semantics

### PR DESCRIPTION
**Pull request by Tomer-StarkWare**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6353)

### CODE REVIEW

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6353#-:-O60fsE82sW7zvTUnkkK:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @piotmag769, and @Tomer-StarkWare)

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6353)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae and @orizi)

___
*[`crates/cairo-lang-defs/src/ids.rs` line 656 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6353#-O60MnLL-Gl5sft6wYip:-O60WYiK72n0SZhVzti1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/311de3c802a3d7e592df8531915c4c52fd43e9c0/crates/cairo-lang-defs/src/ids.rs#L656)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the name here is ok.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/semantic.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6353#-O60NFH64ljGuFIR76SK:-O60WcyQAUmW5TOE7QW1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/311de3c802a3d7e592df8531915c4c52fd43e9c0/crates/cairo-lang-semantic/src/semantic.rs#L53)):*
> ```XML
> }
> 
> // Semantic model if local item kind.
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/const` line 125 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6353#-O60NLgg6SBr7D7GaMAM:-O61Blz72w1mNmIL2i0d:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/311de3c802a3d7e592df8531915c4c52fd43e9c0/crates/cairo-lang-semantic/src/expr/semantic_test_data/const#L125)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix regeression.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6353)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @mkaput, and @Tomer-StarkWare)

___
*[`crates/cairo-lang-defs/src/ids.rs` line 956 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6353#-O61IBHs2afk-zyp5QPz:-O61IBHt5ywcWOoSsDoH:bsqzgtv) ([raw file](https://github.com/starkware-libs/cairo/blob/192e3bb94174477e77c86a4e8d9b65ca3588c5e6/crates/cairo-lang-defs/src/ids.rs#L956)):*
> ```XML
> define_top_level_language_element_id!(
>     LocalConstId,
>     LocalConstLongId,
> ```

this rename makes sense for this PR.



_Suggestion:_
```XML
    StatementConstId,
    StatementConstLongId,
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6353)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @mkaput, and @orizi)

___
*[`crates/cairo-lang-defs/src/ids.rs` line 956 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6353#-O61IBHs2afk-zyp5QPz:-O61Q30e7Esil3Y8fMjm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/192e3bb94174477e77c86a4e8d9b65ca3588c5e6/crates/cairo-lang-defs/src/ids.rs#L956)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this rename makes sense for this PR.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6353)* status: 3 of 8 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @mkaput, and @Tomer-StarkWare)

___
*[`crates/cairo-lang-defs/src/ids.rs` line 956 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6353#-O61IBHs2afk-zyp5QPz:-O61bbaTEpeN00rqbFtR:bnoqn6) ([raw file](https://github.com/starkware-libs/cairo/blob/192e3bb94174477e77c86a4e8d9b65ca3588c5e6/crates/cairo-lang-defs/src/ids.rs#L956)):*
<details><summary><i>Previously, Tomer-StarkWare (TomerC-StarkWare) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Rename the db queries as well.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6353)* status: 3 of 8 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @mkaput, and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/semantic.rs` line 56 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6353#-O61bjiI9PWwOU7Tizoy:-O61bjiI9PWwOU7Tizoz:b5v23xy) ([raw file](https://github.com/starkware-libs/cairo/blob/663c88602b072e36b7989ab2797e85aa5a06b56c/crates/cairo-lang-semantic/src/semantic.rs#L56)):*
> ```XML
> #[derive(Clone, Debug, Hash, PartialEq, Eq, DebugWithDb, SemanticObject)]
> #[debug_db(dyn SemanticGroup + 'static)]
> pub enum LocalItemKind {
> ```

Statement

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6353)* status: 3 of 8 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @mkaput, and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/semantic.rs` line 58 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6353#-O61xCOd9B7VHwHF2Nja:-O61xCOd9B7VHwHF2Njb:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f9cd1b98715623c2324b31b9aaeb9f02d189c26c/crates/cairo-lang-semantic/src/semantic.rs#L58)):*
> ```XML
> pub enum LocalItemKind {
>     Constant(ConstValueId, TypeId),
> }
> ```





_Suggestion:_
```XML
}

/// Semantic model of statement item kind.
#[derive(Clone, Debug, Hash, PartialEq, Eq, DebugWithDb, SemanticObject)]
#[debug_db(dyn SemanticGroup + 'static)]
pub enum StatementItemKind {
    Constant(ConstValueId, TypeId),
}
```

**Review by mkaput — APPROVED** [review]
> Reviewed 2 of 5 files at r2, 2 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6353)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae and @Tomer-StarkWare)

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6353)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae and @Tomer-StarkWare)

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6353)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae and @Tomer-StarkWare)

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6353)* status: 4 of 8 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @mkaput, and @orizi)

___
*[`crates/cairo-lang-defs/src/ids.rs` line 956 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6353#-O61IBHs2afk-zyp5QPz:-O6FT-ny45jJw6Cd9aPV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/192e3bb94174477e77c86a4e8d9b65ca3588c5e6/crates/cairo-lang-defs/src/ids.rs#L956)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Rename the db queries as well.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/semantic.rs` line 56 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6353#-O61bjiI9PWwOU7Tizoy:-O61dcsc6KYUE4bU8NcZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/663c88602b072e36b7989ab2797e85aa5a06b56c/crates/cairo-lang-semantic/src/semantic.rs#L56)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Statement
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/semantic.rs` line 58 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6353#-O61xCOd9B7VHwHF2Nja:-O6FSKooAlXJs8e1BKZy:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f9cd1b98715623c2324b31b9aaeb9f02d189c26c/crates/cairo-lang-semantic/src/semantic.rs#L58)):*
> ```XML
> pub enum LocalItemKind {
>     Constant(ConstValueId, TypeId),
> }
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6353#-:-O6FVhiDCUC3VuYD2Ei7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae)

**Pull request merged**
