### PR TITLE
Report next_usage_position for moved vars.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
Issue: #3480.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3546)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3546)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/test_data/borrow_check` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3546#-NZ1FhIeEfvuRT22FcAT:-NZ1FhIfEosqHzk_cyEv:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a874895a5716a6a4e60cafa9c6c73dfe4a7cdbd1/crates/cairo-lang-lowering/src/test_data/borrow_check#L14)):*
> ```
>     use_a_drop(y);
>   }
>   use_a_copy2(x);
> ```





_Suggestion:_
```
  if true {
    use_a_copy(x);
    use_a_drop(y);
  } else {
    use_a_drop(y);
  }
  use_a_copy(x);
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3546)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/test_data/borrow_check` line 282 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3546#-NZ1FxItE9gYMr-SbaFM:-NZ1FxItE9gYMr-SbaFN:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/a874895a5716a6a4e60cafa9c6c73dfe4a7cdbd1/crates/cairo-lang-lowering/src/test_data/borrow_check#L282)):*
> ```
> 
> extern fn use_a_drop1(x: ADrop) nopanic;
> extern fn use_a_drop2(x: ADrop) nopanic;
> ```

.



_Suggestion:_
```
fn foo(x: ADrop, mut y: ADrop) {
  if true {
    use_a_drop(y);
  } else {
    y = x;
  }
  use_a_drop(y);
}

//! > function_name
foo

//! > module_code
extern type ADrop;
impl ADropDrop of Drop::<ADrop>;

extern fn use_a_drop(x: ADrop) nopanic;
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3546)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/test_data/borrow_check` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3546#-NZ1FhIeEfvuRT22FcAT:-NZ1XTqk1UHAkW28Pi13:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a874895a5716a6a4e60cafa9c6c73dfe4a7cdbd1/crates/cairo-lang-lowering/src/test_data/borrow_check#L14)):*
> ```
>     use_a_drop(y);
>   }
>   use_a_copy2(x);
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/test_data/borrow_check` line 282 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3546#-NZ1FxItE9gYMr-SbaFM:-NZ1Xa265gZb2HMWr__Y:b-xhowcg) ([raw file](https://github.com/starkware-libs/cairo/blob/a874895a5716a6a4e60cafa9c6c73dfe4a7cdbd1/crates/cairo-lang-lowering/src/test_data/borrow_check#L282)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

I wanted to prepare it for the fix, but I guess we can fix it later.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3546)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/test_data/borrow_check` line 72 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3546#-NZ1Y2TI4e3oIVssFr1r:-NZ1Y2TI4e3oIVssFr1s:b-px221t) ([raw file](https://github.com/starkware-libs/cairo/blob/fcfc441897e17e1de85a22d31ef2338ad0c39de0/crates/cairo-lang-lowering/src/test_data/borrow_check#L72)):*
> ```
> extern fn use_a_copy(x: ACopy) nopanic;
> extern fn use_a_drop1(x: ADrop) nopanic;
> extern fn use_a_drop2(x: ADrop) nopanic;
> ```

why is there a need for 2 functions?



_Suggestion:_
```
  if true {
    use_a_copy(x);
    use_a_drop(y);
  } else {
  }
  use_a_drop(y);
}

//! > function_name
foo

//! > module_code
extern type ACopy;
impl ACopyCopy of Copy::<ACopy>;
extern type ADrop;
impl ADropDrop of Drop::<ADrop>;

extern fn use_a_copy(x: ACopy) nopanic;
extern fn use_a_drop(x: ADrop) nopanic;
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3546)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/test_data/borrow_check` line 72 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3546#-NZ1Y2TI4e3oIVssFr1r:-NZ27TSc5vB0j-iTnJr-:b-kak3q5) ([raw file](https://github.com/starkware-libs/cairo/blob/fcfc441897e17e1de85a22d31ef2338ad0c39de0/crates/cairo-lang-lowering/src/test_data/borrow_check#L72)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why is there a need for 2 functions?
</blockquote></details>

It makes it easier to understand the error location.

I don't want to count the lines to figure it out.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3546#-:-NZ4sQLA2z1Kf_LLX-iM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
