### PR TITLE
Fix array len new_vars_only.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2474)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2474)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2474#-NQVUmzG8xWAR8P6mL8V:-NQVUmzG8xWAR8P6mL8W:b-4mmrxn) ([raw file](https://github.com/starkware-libs/cairo/blob/5b89b282b8db2e57a2eb42f9a4ad192550a6e724/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L93)):*
> ```XML
>                 ref_info: OutputVarReferenceInfo::Deferred(DeferredOutputKind::Generic),
>             }],
>             SierraApChange::Known { new_vars_only: ty_size == 1 },
> ```

just make it false instead - let us be less permissive with these. 



_Code quote:_
```XML
            }],
            SierraApChange::Known { new_vars_only: ty_size == 1 },
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2474)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2474#-NQVUmzG8xWAR8P6mL8V:-NQVWq-U9CmWIBL9VqLZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5b89b282b8db2e57a2eb42f9a4ad192550a6e724/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L93)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

just make it false instead - let us be less permissive with these. 
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2474)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @gilbens-starkware)

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2474)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2474#-:-NQW74yk9U45gPMiGJhH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
