### PR TITLE
Implement neg operator.

### PR DESCRIPTION
**Pull request by Alon-Ti**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1160)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1160)* status: 2 of 9 files reviewed, 2 unresolved discussions (waiting on @Alon-Ti)

___
*[`crates/sierra/src/extensions/modules/felt.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1160#-NI3YgS60SfvfZoq8ea0:-NI3YgS60SfvfZoq8ea1:b-v536dg) ([raw file](https://github.com/starkware-libs/cairo/blob/f5da7b19c1d8bcbfce81d5b280024361fb5aaad7/crates/sierra/src/extensions/modules/felt.rs#L63)):*
> ```XML
>     Mul,
>     Div,
>     Neg,
> ```

i don't see why to add it here.



_Code quote:_
```XML
    Neg,
```
___
*[`examples/fib_local.cairo` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1160#-NI3Yyh_2LRHekVQIBXp:-NI3Yyh_2LRHekVQIBXq:b-jvaib4) ([raw file](https://github.com/starkware-libs/cairo/blob/f5da7b19c1d8bcbfce81d5b280024361fb5aaad7/examples/fib_local.cairo#L3)):*
> ```Cairo
> func fib(n: felt) -> felt {
>     if n == 0 {
>         -1
> ```

this does not sound right.



_Code quote:_
```Cairo
        -1
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1160)* status: 1 of 13 files reviewed, 2 unresolved discussions (waiting on @Alon-Ti)

___
*[`crates/sierra/src/extensions/modules/felt.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1160#-NI3YgS60SfvfZoq8ea0:-NI7Dsnf1gHfI5dKw472:bjlmwn) ([raw file](https://github.com/starkware-libs/cairo/blob/f5da7b19c1d8bcbfce81d5b280024361fb5aaad7/crates/sierra/src/extensions/modules/felt.rs#L63)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

Where do you suggest I add it? Wouldn't anywhere else force me to split `FeltOperationLibFunc`?
</blockquote></details>

you probably should - this is not a binary op.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1160)* status: 1 of 13 files reviewed, 3 unresolved discussions (waiting on @Alon-Ti)

___
*[`crates/semantic/src/diagnostic_test_data/tests` line 121 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1160#-NI7EIaK4CATB2Mzs6tM:-NI7EIaK4CATB2Mzs6tN:b9cneyl) ([raw file](https://github.com/starkware-libs/cairo/blob/b54cd52a1cadeac2219c71022249b3066681c060/crates/semantic/src/diagnostic_test_data/tests#L121)):*
> ```
>       ^
> 
> //! > ==========================================================================
> ```

this belongs in another pr.



_Code quote:_
```
//! > ==========================================================================

//! > Test unsupported operators

//! > test_function_name
test_expr_diagnostics

//! > expr_code
1

//! > module_code

//! > function_body
1 == 1;
11 + (1 == 1);
112 & 192;
-(1 == 2);
!17;

//! > expected_diagnostics
error: Binary operator '+' is not supported for types 'core::felt' and 'core::bool'.
 --> lib.cairo:2:4
11 + (1 == 1);
   ^

error: Binary operator '&' is not supported for types 'core::felt' and 'core::felt'.
 --> lib.cairo:3:5
112 & 192;
    ^

error: Unary operator '-' is not supported for type 'core::bool'.
 --> lib.cairo:4:1
-(1 == 2);
^

error: Unary operator '!' is not supported for type 'core::felt'.
 --> lib.cairo:5:1
!17; {
^
```

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1160)* status: 1 of 13 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/semantic/src/diagnostic_test_data/tests` line 121 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1160#-NI7EIaK4CATB2Mzs6tM:-NIamK6v2F-ZkWsuy0z1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b54cd52a1cadeac2219c71022249b3066681c060/crates/semantic/src/diagnostic_test_data/tests#L121)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this belongs in another pr.
</blockquote></details>

Done.
___
*[`crates/sierra/src/extensions/modules/felt.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1160#-NI3YgS60SfvfZoq8ea0:-NIlgU121ZBbEATXWWWk:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f5da7b19c1d8bcbfce81d5b280024361fb5aaad7/crates/sierra/src/extensions/modules/felt.rs#L63)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you probably should - this is not a binary op.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 8 files at r2, 16 of 16 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1160)* status: all files reviewed, 2 unresolved discussions (waiting on @Alon-Ti)

___
*[`crates/sierra_to_casm/src/invocations/felt.rs` line 60 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1160#-NIlmmUt3VTUFaLS77qU:-NIlmmUu0Ydxm1Abm3GG:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/de12dfbfe90d73f8f5d8bacad33bae07662f43a6/crates/sierra_to_casm/src/invocations/felt.rs#L60)):*
> ```XML
>         .map_err(|_| InvocationError::InvalidReferenceExpressionForArgument)?;
>     let expression = match cell {
>         CellExpression::Deref(a) => UnaryOpExpression { op, a: DerefOrImmediate::Deref(a) },
> ```





_Suggestion:_
```XML
    let expression = UnaryOpExpression { op, a: match cell {
        CellExpression::Deref(a) => DerefOrImmediate::Deref(a),
        CellExpression::Immediate(a) => DerefOrImmediate::Immediate(a),
        _ => return Err(InvocationError::InvalidReferenceExpressionForArgument),
    }};
```
___
*[`examples/fib_unary.cairo` line 5 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1160#-NIlnPvTAP8O4-s152S5:-NIlnPvTAP8O4-s152S6:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/de12dfbfe90d73f8f5d8bacad33bae07662f43a6/examples/fib_unary.cairo#L5)):*
> ```Cairo
> }
> 
> func _fib(a: felt, b: felt, n: felt) -> felt {
> ```





_Suggestion:_
```Cairo
func fib(n: felt) -> felt {
    -fib_inner(-1, -1, n)
}

func fib_inner(a: felt, b: felt, n: felt) -> felt {
    if n != 0 {
        a
    } else {
        fib_inner(b, a + b, n - 1)
    }
}
```

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1160#-:-NIlnoNO97KDyjnk_e8_:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Alon-Ti)

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1160)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/sierra_to_casm/src/invocations/felt.rs` line 60 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1160#-NIlmmUt3VTUFaLS77qU:-NIlrmgD8VpuoYtMaXpj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/de12dfbfe90d73f8f5d8bacad33bae07662f43a6/crates/sierra_to_casm/src/invocations/felt.rs#L60)):*
> ```XML
>         .map_err(|_| InvocationError::InvalidReferenceExpressionForArgument)?;
>     let expression = match cell {
>         CellExpression::Deref(a) => UnaryOpExpression { op, a: DerefOrImmediate::Deref(a) },
> ```

Done.
___
*[`examples/fib_unary.cairo` line 5 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1160#-NIlnPvTAP8O4-s152S5:-NIlqz3N45UXad-blYkV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/de12dfbfe90d73f8f5d8bacad33bae07662f43a6/examples/fib_unary.cairo#L5)):*
> ```Cairo
> }
> 
> func _fib(a: felt, b: felt, n: felt) -> felt {
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1160)* status: all files reviewed, 1 unresolved discussion (waiting on @Alon-Ti)

___
*[`examples/fib_unary.cairo` line 5 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1160#-NIlsHn-65gOGwlccONT:-NIlsHn-65gOGwlccONU:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/bdee03871c3eff528b125317f0da1f860bfef548/examples/fib_unary.cairo#L5)):*
> ```Cairo
> }
> func fib_inner(a: felt, b: felt, n: felt) -> felt {
>     // TODO(alont): change the condition to !(n == 0) once it's supported.
> ```

remove



_Code quote:_
```Cairo
  // TODO(alont): change the condition to !(n == 0) once it's supported.
```

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1160)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`examples/fib_unary.cairo` line 5 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1160#-NIlsHn-65gOGwlccONT:-NIlsTRVAQatvJYi2MwF:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bdee03871c3eff528b125317f0da1f860bfef548/examples/fib_unary.cairo#L5)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1160)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @Alon-Ti)

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1160)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Alon-Ti)

**Pull request merged**
