### PR TITLE
added cairo location to match

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4881)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4881)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-sierra-generator/src/statement_location_test_data/simple` line 86 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4881#-Nopme4F3Iku_hTkppiz:-Nopme4F3Iku_hTkppj-:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7a546c3e1d8e0e2b48ce0585128cc398cc3fded3/crates/cairo-lang-sierra-generator/src/statement_location_test_data/simple#L86)):*
> ```
>         }
>     }
> }
> ```





_Suggestion:_
```
    match myEnum {
        MyEnum::A(a) => a,
        MyEnum::B(b) => b,
        MyEnum::C((c1, c2)) => {
            if c1 == 0 { c1 + c2 } else { c1 * c2 }
        }
    }
}
```
___
*[`crates/cairo-lang-sierra-generator/src/statement_location_test_data/simple` line 96 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4881#-NopmsU93TSbZbGmPHLw:-NopmsU93TSbZbGmPHLx:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7a546c3e1d8e0e2b48ce0585128cc398cc3fded3/crates/cairo-lang-sierra-generator/src/statement_location_test_data/simple#L96)):*
> ```
>     B:felt252,
>     C:(felt252,felt252),
> }
> ```





_Suggestion:_
```
enum MyEnum {
    A: felt252,
    B: felt252,
    C: (felt252, felt252),
}
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4881)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/statement_location_test_data/simple` line 86 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4881#-Nopme4F3Iku_hTkppiz:-NopoEf2ATo3QJBMJAzT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7a546c3e1d8e0e2b48ce0585128cc398cc3fded3/crates/cairo-lang-sierra-generator/src/statement_location_test_data/simple#L86)):*
> ```
>         }
>     }
> }
> ```

Done.
___
*[`crates/cairo-lang-sierra-generator/src/statement_location_test_data/simple` line 96 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4881#-NopmsU93TSbZbGmPHLw:-NopoIRK87p0FzeVAsuv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7a546c3e1d8e0e2b48ce0585128cc398cc3fded3/crates/cairo-lang-sierra-generator/src/statement_location_test_data/simple#L96)):*
> ```
>     B:felt252,
>     C:(felt252,felt252),
> }
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4881#-:-NoptAAM2xFx_ZErYQY9:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4881)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4881#-:-Noq0pd-E_F5ISbca-_P:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
