### PR TITLE
Refactor calculate_reverse_topological_ordering so that it can be used in compute_costs.rs.

### PR DESCRIPTION
**Pull request by liorgold2**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4107)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4107)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-gas/src/generate_equations.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4107#-NenDk4f06gslA59QqBF:-NenDk4g4fMavL4YReKN:b4orpdk) ([raw file](https://github.com/starkware-libs/cairo/blob/c6b1a839f87871e1d94ccffdc5fbe0bf915be5a1/crates/cairo-lang-sierra-gas/src/generate_equations.rs#L151)):*
> ```XML
>     while let Some(idx) = stack.pop() {
>         println!("Visiting {idx}");
>         match status.get(idx.0) {
> ```

Remove print.

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4107)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-gas/src/generate_equations.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4107#-NenDk4f06gslA59QqBF:-Neo81-z5M7wyvYriFkz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c6b1a839f87871e1d94ccffdc5fbe0bf915be5a1/crates/cairo-lang-sierra-gas/src/generate_equations.rs#L151)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Remove print.
</blockquote></details>

Done.

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4107)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-gas/src/generate_equations.rs` line 160 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4107#-NeoBF-8DNPF9r61Y3EP:-NeoBF-8DNPF9r61Y3EQ:b-pmyzoq) ([raw file](https://github.com/starkware-libs/cairo/blob/bfd68fe09cdb5b891d64fa5371afe8785d230550/crates/cairo-lang-sierra-gas/src/generate_equations.rs#L160)):*
> ```XML
>                 stack.push(idx);
>                 for child in children_callback(&idx) {
>                     match status.get(child.0) {
> ```

This part is required to handle cycles (when a child is `InProgress`). In a future PR I'll add to it an option to raise an error when this happens.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4107#-:-NeqHc-82QCY7cPrrUW1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
