### PR TITLE
Add FlatStorage to embed storage objects in contract storage.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
**Stack**:
- #6032
- #6031 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6031)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6031)* status: 0 of 30 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`corelib/src/starknet/storage.cairo` line 482 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6031#-O2-HrmgAsh5h5EaiMhT:-O2-HrmgAsh5h5EaiMhU:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b99f21cb89f785f57d5a9770195e7799458f6253/corelib/src/starknet/storage.cairo#L482)):*
> ```Cairo
> /// A type that represents a flat storage, i.e. a storage object which does not have any effect on
> /// the path taken into consideration when computing the address of the storage object.
> pub struct FlatStorage<T> {}
> ```





_Suggestion:_
```Cairo
/// A type that represents a flattened storage, i.e. a storage object which does not have any effect on
/// the path taken into consideration when computing the address of the storage object.
pub struct FlattenedStorage<T> {}
```
___
*[`corelib/src/starknet/storage.cairo` line 508 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6031#-O2-Hh7T0BNx0FyB_TXA:-O2-Hh7T0BNx0FyB_TXB:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b99f21cb89f785f57d5a9770195e7799458f6253/corelib/src/starknet/storage.cairo#L508)):*
> ```Cairo
> /// A struct for holding an address to initialize a storage path with. The members (not direct
> /// members, but accessible using deref) of a contract state are either `StorageBase` or
> /// `FlatStorage`` instances, with the generic type representing the type of the stored member.
> ```





_Suggestion:_
```Cairo
/// A struct for holding an address to initialize a storage path with. The members (not direct
/// members, but accessible using deref) of a contract state are either `StorageBase` or
/// `FlatStorage` instances, with the generic type representing the type of the stored member.
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 30 files at r1, 1 of 27 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6031)* status: 1 of 30 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`corelib/src/starknet/storage.cairo` line 481 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6031#-O2-NNUsBckxHM5pV9aQ:-O2-NNUsBckxHM5pV9aR:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/eda188ec4df53d32cf3ba8350a36846e49b82d04/corelib/src/starknet/storage.cairo#L481)):*
> ```Cairo
> 
> /// A type that represents a flattned storage, i.e. a storage object which does not have any effect
> /// on the path taken into consideration when computing the address of the storage object.
> ```





_Suggestion:_
```Cairo
/// A type that represents a flattened storage, i.e. a storage object which does not have any effect
/// on the path taken into consideration when computing the address of the storage object.
```
___
*[`corelib/src/starknet/storage.cairo` line 524 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6031#-O2-NY9F6jT7e7YDBLs_:-O2-NY9F6jT7e7YDBLsa:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/eda188ec4df53d32cf3ba8350a36846e49b82d04/corelib/src/starknet/storage.cairo#L524)):*
> ```Cairo
> }
> 
> pub trait MutableStorageTrait<T> {
> ```

doc

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6031)* status: 1 of 30 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/components/diagnostics` line 88 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6031#-O2-O3JVAdioAdUEGXHo:-O2-O3JWEbx9DHZn6t2D:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/b99f21cb89f785f57d5a9770195e7799458f6253/crates/cairo-lang-starknet/src/plugin/plugin_test_data/components/diagnostics#L88)):*
> ```
> //             self.storage_mut()
> //     }
> // }
> ```

?



_Code quote:_
```
//  impl FlatStorageDeref of core::ops::Deref<starknet::storage::FlatStorage<Storage>> {
//     type Target = ComponentStorageBase;
//     fn deref(self: starknet::storage::FlatStorage<Storage>) -> //  ComponentStorageBase {
//             self.storage()
//     }
// }
// impl MutableFlatStorageDeref of //  core::ops::Deref<starknet::storage::FlatStorage<starknet::storage::Mutable<Storage>>> //  {
//     type Target = ComponentStorageBaseMut;
//     fn deref(self: //  starknet::storage::FlatStorage<starknet::storage::Mutable<Storage>>) -> //  ComponentStorageBaseMut {
//             self.storage_mut()
//     }
// }
```
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/components/diagnostics` line 261 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6031#-O2-O7vl-V0t_h3Spz9l:-O2-O7vl-V0t_h3Spz9m:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/b99f21cb89f785f57d5a9770195e7799458f6253/crates/cairo-lang-starknet/src/plugin/plugin_test_data/components/diagnostics#L261)):*
> ```
> // impl MutableFlatStorageDeref of //  core::ops::Deref<starknet::storage::FlatStorage<starknet::storage::Mutable<Storage>>> //  {
> //     type Target = ComponentStorageBaseMut;
> //     fn deref(self: //  starknet::storage::FlatStorage<starknet::storage::Mutable<Storage>>) -> //  ComponentStorageBaseMut {
> ```

?
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/components/diagnostics` line 442 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6031#-O2-OASm6UDGLm159nDo:-O2-OASm6UDGLm159nDp:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/b99f21cb89f785f57d5a9770195e7799458f6253/crates/cairo-lang-starknet/src/plugin/plugin_test_data/components/diagnostics#L442)):*
> ```
> // }
> 
> pub struct ComponentState<TContractState> {
> ```

?



_Code quote:_
```
//  impl FlatStorageDeref of core::ops::Deref<starknet::storage::FlatStorage<Storage>> {
//     type Target = ComponentStorageBase;
//     fn deref(self: starknet::storage::FlatStorage<Storage>) -> //  ComponentStorageBase {
//             self.storage()
//     }
// }
// impl MutableFlatStorageDeref of //  core::ops::Deref<starknet::storage::FlatStorage<starknet::storage::Mutable<Storage>>> //  {
//     type Target = ComponentStorageBaseMut;
//     fn deref(self: //  starknet::storage::FlatStorage<starknet::storage::Mutable<Storage>>) -> //  ComponentStorageBaseMut {
//             self.storage_mut()
//     }
// }

pub struct ComponentState<TContractState> {
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6031)* status: 1 of 30 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 27 files at r2, 28 of 28 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6031)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6031)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/starknet/storage.cairo` line 508 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6031#-O2-Hh7T0BNx0FyB_TXA:-O2-MMCFA5qYojnTNRuV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b99f21cb89f785f57d5a9770195e7799458f6253/corelib/src/starknet/storage.cairo#L508)):*
> ```Cairo
> /// A struct for holding an address to initialize a storage path with. The members (not direct
> /// members, but accessible using deref) of a contract state are either `StorageBase` or
> /// `FlatStorage`` instances, with the generic type representing the type of the stored member.
> ```

Done.
___
*[`corelib/src/starknet/storage.cairo` line 481 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6031#-O2-NNUsBckxHM5pV9aQ:-O2-ONE54JmvK9dVrMGW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/eda188ec4df53d32cf3ba8350a36846e49b82d04/corelib/src/starknet/storage.cairo#L481)):*
> ```Cairo
> 
> /// A type that represents a flattned storage, i.e. a storage object which does not have any effect
> /// on the path taken into consideration when computing the address of the storage object.
> ```

Done.
___
*[`corelib/src/starknet/storage.cairo` line 524 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6031#-O2-NY9F6jT7e7YDBLs_:-O2-_GqOC8VCwx7-lYoI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/eda188ec4df53d32cf3ba8350a36846e49b82d04/corelib/src/starknet/storage.cairo#L524)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6031)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`corelib/src/starknet/storage.cairo` line 481 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6031#-O2-NNUsBckxHM5pV9aQ:-O2-aBSf9DuMxG8S5jmC:bm42cvi) ([raw file](https://github.com/starkware-libs/cairo/blob/eda188ec4df53d32cf3ba8350a36846e49b82d04/corelib/src/starknet/storage.cairo#L481)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not it isn't

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6031)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`corelib/src/starknet/storage.cairo` line 524 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6031#-O2-NY9F6jT7e7YDBLs_:-O2-h4RZ6RGGZ4mVSKd4:b-7m314d) ([raw file](https://github.com/starkware-libs/cairo/blob/eda188ec4df53d32cf3ba8350a36846e49b82d04/corelib/src/starknet/storage.cairo#L524)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nope.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6031)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/starknet/storage.cairo` line 524 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6031#-O2-NY9F6jT7e7YDBLs_:-O2-me7kC8ET0Z0cYfZh:b-9sqnfx) ([raw file](https://github.com/starkware-libs/cairo/blob/eda188ec4df53d32cf3ba8350a36846e49b82d04/corelib/src/starknet/storage.cairo#L524)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

nope.
</blockquote></details>

Thought you meant the type. Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6031#-:-O2-vUFu2d7KHMsVwEgE:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6031)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

___
*[`corelib/src/starknet/storage.cairo` line 527 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6031#-O2-vWwYDJquUG7EDD3G:-O2-vWwYDJquUG7EDD3H:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/5c5adcb59869752a09a0aaedb29728c6f0bed3ef/corelib/src/starknet/storage.cairo#L527)):*
> ```Cairo
> 
> 
> /// A trait for creating the struct containing the mutable StorageBase or FlattenedStorage of all
> ```

.



_Suggestion:_
```Cairo
}

/// A trait for creating the struct containing the mutable StorageBase or FlattenedStorage of all
```

**Pull request merged**
