### PR TITLE
feat: add `continue` for loops

### LINKED ISSUE #2939: feat: `continue` for loops
# Feature Request

Currently, there is only `break` for loops. However, there are instances where we want to skip the current iteration but continue with the loop to continue

**Describe Preferred Solution**

Add `continue` for loops

### PR DESCRIPTION
**Pull request by tserg**
Fix #2939.

[Copy-pasted from issue] This requires:

- Adding the syntax for continue:
  - Change cairo_spec.rs, run the generate-syntax binary, fix parser.
  - Add the statement in the semantic crate (look for the break syntax and do similarly)
  - In lowering crate, at crates/cairo-lang-lowering/src/lower/mod.rs, handle the continue similarly to break, but use call_loop_func() to add a recursive call
  
I am stuck on `lower_statement()` in `crates/cairo-lang-lowering/src/lower/mod.rs` and will appreciate some guidance. How do I access the `ExprLoop` from a `continue` statement to pass to `call_loop_func`? Or maybe I am going about it the wrong way?

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2947)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Can you store it on the context when you encounter it? Something like current_loop_expr

**Comment by tserg** [comment]
I have made the changes. The control flow still looks incorrect though.

Using the tests in `crates/cairo-lang-lowering/src/lower/test_data/loop` as an example, I modified an example to this:
```
fn foo() -> bool {
    let mut x = 5;
    loop {
        let y = x + 1;
        x = y;
        if y == 7 {
            continue;
        }
        if y == 10 {
            break true;
        };
    }
}
```
This is the lowering output. I think `blk1` should be jumping to a different block from `blk2`.
```
Main:
Parameters:
blk0 (root):
Statements:
  (v0: core::felt252) <- 5u
  (v2: core::felt252, v1: core::bool) <- foo[expr19](v0)
End:
  Return(v1)


Generated:
Parameters: v0: core::felt252
blk0 (root):
Statements:
  (v1: core::felt252) <- 1u
  (v2: core::felt252) <- core::Felt252Add::add(v0, v1)
  (v3: core::felt252) <- 7u
  (v4: core::felt252) <- core::Felt252Sub::sub(v2, v3)
End:
  Match(match core::felt252_is_zero(v4) {
    IsZeroResult::Zero => blk1,
    IsZeroResult::NonZero(v7) => blk2,
  })

blk1:
Statements:
  (v6: core::felt252, v5: core::bool) <- foo[expr19](v2)
End:
  Goto(blk3, {v6 -> v8}) <--------------------- should be jumping to a different block from blk2

blk2:
Statements:
End:
  Goto(blk3, {v2 -> v8})
  
blk3:
Statements:
  (v9: core::felt252) <- 10u
  (v10: core::felt252) <- core::Felt252Sub::sub(v2, v9)
End:
  Match(match core::felt252_is_zero(v10) {
    IsZeroResult::Zero => blk4,
    IsZeroResult::NonZero(v13) => blk5,
  })
...
```

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
Please ass a test. You can look for test files named loop, and also add one in corelib/tests

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2947#-:-NU6Cv404SMRYrkkM-gH:b-v1o1cs)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @tserg)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 321 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2947#-NU7CiS8-zbLWPheRSpI:-NU7CiS8-zbLWPheRSpJ:bt2oikt) ([raw file](https://github.com/starkware-libs/cairo/blob/531eba457db91e389433dd0eaae12d2a4480336d/crates/cairo-lang-lowering/src/lower/mod.rs#L321)):*
> ```XML
>             log::trace!("Lowering a continue statement.");
>             let loop_expr = ctx.current_loop_expr.clone().unwrap();
>             call_loop_func(ctx, ctx.signature.clone(), builder, &loop_expr)?;
> ```

Note that you do not end the evaluation of the block. Take a look at return and break - they return immediately.
You should do the same - call recursively, and then return that value.

**Review by spapinistarkware — COMMENTED** [review]
I added a comment in the code that should fix this.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2947#-:-NU7D0Lh6vkr2i5QDibb:bc8zrrg)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @tserg)

**Review by spapinistarkware — COMMENTED** [review]
Looks good. Can you add a cairo test under bug_samples with the issue number? So that we see it works end to end. Remember to add a #[test] above it.

> Reviewed 1 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2947#-:-NUAQCPKEqTGUGyUipC4:b-j1t6zg)* status: 1 of 15 files reviewed, 1 unresolved discussion (waiting on @tserg)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 3 of 12 files at r1, 3 of 8 files at r2, 8 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2947)* status: all files reviewed, 1 unresolved discussion (waiting on @tserg)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2947#-:-NUAfndu6G210Z9MgGgI:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @tserg)

**Comment by tserg** [comment]
Thanks for the help @spapinistarkware !

**Pull request merged**
