### PR TITLE
added arm selector enum to match arm

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4653)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 18 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4653)* status: 18 of 19 files reviewed, 4 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/objects.rs` line 304 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4653#-NmWQybwCUQs5AlFfyUU:-NmWQybwCUQs5AlFfyUV:bljob9k) ([raw file](https://github.com/starkware-libs/cairo/blob/57ddecd083e1db9409c6e2a2740d62502af2c731/crates/cairo-lang-lowering/src/objects.rs#L304)):*
> ```XML
> #[derive(Clone, Debug, PartialEq, Eq)]
> pub struct MatchArm {
>     /// The id of the arm variant.
> ```

fix doc
___
*[`crates/cairo-lang-lowering/src/concretize/mod.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4653#-NmWRBqB8CgRzfEthjk3:-NmWRBqB8CgRzfEthjk4:bso3b97) ([raw file](https://github.com/starkware-libs/cairo/blob/57ddecd083e1db9409c6e2a2740d62502af2c731/crates/cairo-lang-lowering/src/concretize/mod.rs#L61)):*
> ```XML
>         }
>         if let FlatBlockEnd::Match { info } = &mut block.end {
>             for MatchArm { arm_selector: variant_id, .. } in match info {
> ```

fix name
___
*[`crates/cairo-lang-semantic/src/items/enm.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4653#-NmWRpmdAB_BFrb4SeBp:-NmWRZOw5YusFkV2ojxq:b1vivuz) ([raw file](https://github.com/starkware-libs/cairo/blob/57ddecd083e1db9409c6e2a2740d62502af2c731/crates/cairo-lang-semantic/src/items/enm.rs#L174)):*
> ```XML
> #[derive(Clone, Debug, Hash, PartialEq, Eq, DebugWithDb, SemanticObject)]
> #[debug_db(dyn SemanticGroup + 'static)]
> pub struct ValueSelectorArm {
> ```

is this type directly required?
___
*[`crates/cairo-lang-semantic/src/items/enm.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4653#-NmWR_5MCUjk9ROiZkB8:-NmWR_5N3W1kG3CdC4cE:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/57ddecd083e1db9409c6e2a2740d62502af2c731/crates/cairo-lang-semantic/src/items/enm.rs#L181)):*
> ```XML
> #[derive(Clone, Debug, Hash, PartialEq, Eq, DebugWithDb, SemanticObject)]
> #[debug_db(dyn SemanticGroup + 'static)]
> pub enum MatchArmSelector {
> ```

doc

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4653)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4653)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4653)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4653)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4653)* status: 18 of 20 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/objects.rs` line 304 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4653#-NmWQybwCUQs5AlFfyUU:-NmW_aepAGJhjW6qC-Zc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/57ddecd083e1db9409c6e2a2740d62502af2c731/crates/cairo-lang-lowering/src/objects.rs#L304)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/concretize/mod.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4653#-NmWRBqB8CgRzfEthjk3:-NmW_a4x9mKZeVqlYOxy:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/57ddecd083e1db9409c6e2a2740d62502af2c731/crates/cairo-lang-lowering/src/concretize/mod.rs#L61)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix name
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/enm.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4653#-NmWRpmdAB_BFrb4SeBp:-NmW_eFG6UWlrPiDH52P:b-6ysgyk) ([raw file](https://github.com/starkware-libs/cairo/blob/57ddecd083e1db9409c6e2a2740d62502af2c731/crates/cairo-lang-semantic/src/items/enm.rs#L174)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is this type directly required?
</blockquote></details>

for the next pr
___
*[`crates/cairo-lang-semantic/src/items/enm.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4653#-NmWR_5MCUjk9ROiZkB8:-NmWdUZdDZzJ4dPPvtBv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/57ddecd083e1db9409c6e2a2740d62502af2c731/crates/cairo-lang-semantic/src/items/enm.rs#L181)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4653)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/items/enm.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4653#-NmWRpmdAB_BFrb4SeBp:-No6m7Xx0mB2lo4Q89yi:b-2bzt9l) ([raw file](https://github.com/starkware-libs/cairo/blob/57ddecd083e1db9409c6e2a2740d62502af2c731/crates/cairo-lang-semantic/src/items/enm.rs#L174)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

for the next pr
</blockquote></details>

is the type actually required? can't you use `usize` directly?

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4653)* status: 19 of 20 files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/items/enm.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4653#-NmWR_5MCUjk9ROiZkB8:-No6q4tW-9SaNOMozSQq:b-s1oi1j) ([raw file](https://github.com/starkware-libs/cairo/blob/57ddecd083e1db9409c6e2a2740d62502af2c731/crates/cairo-lang-semantic/src/items/enm.rs#L181)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

identifier is probably the wrong word.
___
*[`crates/cairo-lang-semantic/src/items/enm.rs` line 170 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4653#-No6q2JS9zocwf2sovCU:-No6q2JS9zocwf2sovCV:b-s1oi1j) ([raw file](https://github.com/starkware-libs/cairo/blob/476346f4114f5f455d546bbb6ccad90f04e860c4/crates/cairo-lang-semantic/src/items/enm.rs#L170)):*
> ```XML
> }
> 
> /// Identifier of a match arm of a match on numeric values.
> ```

identifier is probably the wrong word.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4653)* status: 19 of 20 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/items/enm.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4653#-NmWRpmdAB_BFrb4SeBp:-No6z0IYCMN9YWeiMtTd:bavounp) ([raw file](https://github.com/starkware-libs/cairo/blob/57ddecd083e1db9409c6e2a2740d62502af2c731/crates/cairo-lang-semantic/src/items/enm.rs#L174)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is the type actually required? can't you use `usize` directly?
</blockquote></details>

require for dont_rewrite
___
*[`crates/cairo-lang-semantic/src/items/enm.rs` line 170 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4653#-No6q2JS9zocwf2sovCU:-No6z-VS62n5LiNlLfsu:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/476346f4114f5f455d546bbb6ccad90f04e860c4/crates/cairo-lang-semantic/src/items/enm.rs#L170)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

identifier is probably the wrong word.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4653#-:-No71FnS3XOiP6ewbhms:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4653)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4653)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
