### PR TITLE
Add u128_byte_reverse.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2839)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`tests/e2e_test_data/libfuncs/u128` line 730 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2839#-NT9gwQ29FigtE9fmqOb:-NT9gwQ29FigtE9fmqOc:b-11zjal) ([raw file](https://github.com/starkware-libs/cairo/blob/0d05e3b82e4c63714d5580e22aa01103a4087e20/tests/e2e_test_data/libfuncs/u128#L730)):*
> ```
> [ap + 0] = [ap + -5] + [ap + -1], ap++;
> [ap + 0] = 72057594037927936, ap++;
> [ap + 0] = [ap + 0] * [ap + -1], ap++;
> ```

@orizi 
This seems to be a bug.
it is supposed to be:
[ap + k] = [ap + (k-1)] * ...

for some k (maybe 0).


https://github.com/starkware-libs/cairo/blob/0d05e3b82e4c63714d5580e22aa01103a4087e20/crates/cairo-lang-sierra-to-casm/src/invocations/uint128.rs#L408



_Code quote:_
```
[ap + 0] = [ap + 0] * [ap + -1], ap++;
```

**Comment by ilyalesokhin-starkware** [comment]
*[`tests/e2e_test_data/libfuncs/u128` line 730 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2839#-NT9gwQ29FigtE9fmqOb:-NT9jrjq7lwyBHq5QsKE:b6gdebf) ([raw file](https://github.com/starkware-libs/cairo/blob/0d05e3b82e4c63714d5580e22aa01103a4087e20/tests/e2e_test_data/libfuncs/u128#L730)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

@orizi 
This seems to be a bug.
it is supposed to be:
[ap + k] = [ap + (k-1)] * ...

for some k (maybe 0).


https://github.com/starkware-libs/cairo/blob/0d05e3b82e4c63714d5580e22aa01103a4087e20/crates/cairo-lang-sierra-to-casm/src/invocations/uint128.rs#L408
</blockquote></details>

nvm, the issue is with:
https://github.com/starkware-libs/cairo/blob/0d05e3b82e4c63714d5580e22aa01103a4087e20/crates/cairo-lang-sierra-to-casm/src/invocations/uint128.rs#L421

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2839)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2839#-NTAzCPPCkr1bZymcWu1:-NTAzCPPCkr1bZymcWu2:bl0d8ao) (no related file):*
Won't having split functions for u128 into u16 more efficient, and just widemul back into u64?

___

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2839)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/uint128.rs` line 390 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2839#-NTBTfaj568dxMzGWwB1:-NTBTfal2NHre6McdRZ4:b-d8npni) ([raw file](https://github.com/starkware-libs/cairo/blob/c2860a17d85dc1b34233b8f618246c9dfabcef49/crates/cairo-lang-sierra-to-casm/src/invocations/uint128.rs#L390)):*
> ```XML
>     ];
> 
>     let mut temp = input;
> ```

won't this be just as efficient in user code?



_Code quote:_
```XML
    let masks = [
        0x00ff00ff00ff00ff00ff00ff00ff00ff_u128,
        0x00ffff0000ffff0000ffff0000ffff00_u128,
        0x00ffffffff00000000ffffffff000000_u128,
    ];

    let mut temp = input;
    let mut shift = BigInt::from(1 << 16);
    for mask_imm in masks.into_iter().map(BigInt::from) {
        let shift_imm = BigInt::from(&shift - 1);
        casm_build_extend! {casm_builder,
            assert temp = *(bitwise++);
            const mask_imm = mask_imm;
            const shift_imm = shift_imm;
            tempvar shift_temp = shift_imm;
            tempvar mask = mask_imm;
            assert mask = *(bitwise++);
            tempvar and = *(bitwise++);
            let _xor = *(bitwise++);
            let _or = *(bitwise++);

            tempvar shifted_var = and * shift_temp;
            tempvar x = temp + shifted_var;
        };

        shift = &shift * &shift;
        temp = x;
    }
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-to-casm/src/invocations/uint128.rs` line 390 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2839#-NTBTfaj568dxMzGWwB1:-NTCagdG3tWv_7qiec2F:b-4jaq9c) ([raw file](https://github.com/starkware-libs/cairo/blob/c2860a17d85dc1b34233b8f618246c9dfabcef49/crates/cairo-lang-sierra-to-casm/src/invocations/uint128.rs#L390)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

won't this be just as efficient in user code?
</blockquote></details>

What type would you use for `temp`?

A felt can't be assigned to bitwise safely, and u251 would add range checks.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2839)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2839#-NTAzCPPCkr1bZymcWu1:-NTCaezJ2ZiTSR8T5nMg:ba2ijlj) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Won't having split functions for u128 into u16 more efficient, and just widemul back into u64?
</blockquote></details>

I don't see how.

___

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2839)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2839#-NTAzCPPCkr1bZymcWu1:-NTCcf2E5ZsWpJZgJ_NR:b-ghi8cy) (no related file):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't see how.
</blockquote></details>

Can you elaborate?

___

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2839)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2839#-NTAzCPPCkr1bZymcWu1:-NTCbVTf0k-c4rMvf39X:b-yrm916) (no related file):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't see how.
</blockquote></details>

First off - I don't remember how heavy is the bitwise builtin usage, so that would remove its need.
anyway - I think you should first implement whatever you wanted in user code, and then add libfuncs to improve the performance, not the other way around, easier to prove necessity, to design and to test.

___
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/uint128.rs` line 390 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2839#-NTBTfaj568dxMzGWwB1:-NTCcm13A8x_ovAc7LWW:bipc115) ([raw file](https://github.com/starkware-libs/cairo/blob/c2860a17d85dc1b34233b8f618246c9dfabcef49/crates/cairo-lang-sierra-to-casm/src/invocations/uint128.rs#L390)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

What type would you use for `temp`?

A felt can't be assigned to bitwise safely, and u251 would add range checks.
</blockquote></details>

Temp is a legal u128, but it is indeed not checked at the time.
 We still can logically split this to something which is simpler but useful.
This libfunc still seems to me to be doing something extremely specific

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2839)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2839#-NTAzCPPCkr1bZymcWu1:-NTCdadEBkYRc6p0hDBv:bff4thq) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

First off - I don't remember how heavy is the bitwise builtin usage, so that would remove its need.
anyway - I think you should first implement whatever you wanted in user code, and then add libfuncs to improve the performance, not the other way around, easier to prove necessity, to design and to test.

</blockquote></details>

The main idea is just:
u128 into 16 u8, and recombination of the bytes.
but extra libfuncs would be required all around 

___

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2839)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2839#-NTAzCPPCkr1bZymcWu1:-NTCewJ-3s0BDN_4O3Kr:bmc28pg) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

The main idea is just:
u128 into 16 u8, and recombination of the bytes.
but extra libfuncs would be required all around 
</blockquote></details>

Implementing it in high level code is a lot more work.
Lior agreed that this should be a libfunc.

___
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/uint128.rs` line 390 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2839#-NTBTfaj568dxMzGWwB1:-NTCf4wI5ZS4dusHmyv3:b5bxnem) ([raw file](https://github.com/starkware-libs/cairo/blob/c2860a17d85dc1b34233b8f618246c9dfabcef49/crates/cairo-lang-sierra-to-casm/src/invocations/uint128.rs#L390)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Temp is a legal u128, but it is indeed not checked at the time.
 We still can logically split this to something which is simpler but useful.
This libfunc still seems to me to be doing something extremely specific
</blockquote></details>

Temp is not a legal u128.
it is a valid 
u{128+ (8 + 16 + 32)}

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2839)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2839#-NTAzCPPCkr1bZymcWu1:-NTCfUDI2ZcpOFuxfoCV:b-fw2vv4) (no related file):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Implementing it in high level code is a lot more work.
Lior agreed that this should be a libfunc.
</blockquote></details>

this is really little work:
fn foo(mut a: u128) -> (u64, u64) {
   let mut v1: u64 = 0;
   let b: u64 = a % 256; a /= 256; v1 *= b;
   let b: u64 = a % 256; a /= 256; v1 *= 256; v1 += b;
   let b: u64 = a % 256; a /= 256; v1 *= 256; v1 += b;
   let b: u64 = a % 256; a /= 256; v1 *= 256; v1 += b;
   let b: u64 = a % 256; a /= 256; v1 *= 256; v1 += b;
   let b: u64 = a % 256; a /= 256; v1 *= 256; v1 += b;
   let b: u64 = a % 256; a /= 256; v1 *= 256; v1 += b;
   let b: u64 = a % 256; a /= 256; v1 *= 256; v1 += b;
   let mut v2: u64 = 0;
   let b: u64 = a % 256; a /= 256; v2 *= b;
   let b: u64 = a % 256; a /= 256; v2 *= 256; v2 += b;
   let b: u64 = a % 256; a /= 256; v2 *= 256; v2 += b;
   let b: u64 = a % 256; a /= 256; v2 *= 256; v2 += b;
   let b: u64 = a % 256; a /= 256; v2 *= 256; v2 += b;
   let b: u64 = a % 256; a /= 256; v2 *= 256; v2 += b;
   let b: u64 = a % 256; a /= 256; v2 *= 256; v2 += b;
   let b: u64 = a % 256; a /= 256; v2 *= 256; v2 += b;
   (v1, v2)
}

of course it is a lot less efficient - but let get to the target before we start implementing stuff that we need to make actual decisions on.

___
___
*[`crates/cairo-lang-sierra/src/extensions/modules/uint128.rs` line 294 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2839#-NTCgt4e5bFaQ5j24EO-:-NTCgt4f2znuv-OQoRBK:b-5ut0l9) ([raw file](https://github.com/starkware-libs/cairo/blob/5f29a8f4a4b29f5d70f3cded900f103342c75286/crates/cairo-lang-sierra/src/extensions/modules/uint128.rs#L294)):*
> ```XML
>             vec![
>                 OutputVarInfo {
>                     ty: bitwise_ty,
> ```

this already exists - not sure why it appeared here.



_Code quote:_
```XML
/// Libfunc for computing the Bitwise (and,or,xor) of two u128s.
/// Returns 3 u128s (and the updated builtin pointer).
#[derive(Default)]
pub struct BitwiseLibfunc {}
impl NoGenericArgsGenericLibfunc for BitwiseLibfunc {
    const STR_ID: &'static str = "bitwise";

    fn specialize_signature(
        &self,
        context: &dyn SignatureSpecializationContext,
    ) -> Result<LibfuncSignature, SpecializationError> {
        let bitwise_ty = context.get_concrete_type(BitwiseType::id(), &[])?;
        let u128_ty = context.get_concrete_type(Uint128Type::id(), &[])?;
        Ok(LibfuncSignature::new_non_branch_ex(
            vec![
                ParamSignature {
                    ty: bitwise_ty.clone(),
                    allow_deferred: false,
                    allow_add_const: true,
                    allow_const: false,
                },
                ParamSignature::new(u128_ty.clone()),
                ParamSignature::new(u128_ty.clone()),
            ],
            vec![
                OutputVarInfo {
                    ty: bitwise_ty,
                    ref_info: OutputVarReferenceInfo::Deferred(DeferredOutputKind::AddConst {
                        param_idx: 0,
                    }),
                },
                OutputVarInfo {
                    ty: u128_ty.clone(),
                    ref_info: OutputVarReferenceInfo::Deferred(DeferredOutputKind::Generic),
                },
                OutputVarInfo {
                    ty: u128_ty.clone(),
                    ref_info: OutputVarReferenceInfo::Deferred(DeferredOutputKind::Generic),
                },
                OutputVarInfo {
                    ty: u128_ty,
                    ref_info: OutputVarReferenceInfo::Deferred(DeferredOutputKind::Generic),
                },
            ],
            SierraApChange::Known { new_vars_only: true },
        ))
    }
}
```

**Comment by ilyalesokhin-starkware** [comment]
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is really little work:
fn foo(mut a: u128) -> (u64, u64) {
   let mut v1: u64 = 0;
   let b: u64 = a % 256; a /= 256; v1 *= b;
   let b: u64 = a % 256; a /= 256; v1 *= 256; v1 += b;
   let b: u64 = a % 256; a /= 256; v1 *= 256; v1 += b;
   let b: u64 = a % 256; a /= 256; v1 *= 256; v1 += b;
   let b: u64 = a % 256; a /= 256; v1 *= 256; v1 += b;
   let b: u64 = a % 256; a /= 256; v1 *= 256; v1 += b;
   let b: u64 = a % 256; a /= 256; v1 *= 256; v1 += b;
   let b: u64 = a % 256; a /= 256; v1 *= 256; v1 += b;
   let mut v2: u64 = 0;
   let b: u64 = a % 256; a /= 256; v2 *= b;
   let b: u64 = a % 256; a /= 256; v2 *= 256; v2 += b;
   let b: u64 = a % 256; a /= 256; v2 *= 256; v2 += b;
   let b: u64 = a % 256; a /= 256; v2 *= 256; v2 += b;
   let b: u64 = a % 256; a /= 256; v2 *= 256; v2 += b;
   let b: u64 = a % 256; a /= 256; v2 *= 256; v2 += b;
   let b: u64 = a % 256; a /= 256; v2 *= 256; v2 += b;
   let b: u64 = a % 256; a /= 256; v2 *= 256; v2 += b;
   (v1, v2)
}

of course it is a lot less efficient - but let get to the target before we start implementing stuff that we need to make actual decisions on.
</blockquote></details>

it gives me
error: Unexpected argument type. Expected: "core::integer::u64", found: "core::integer::u128".
 --> keccak.cairo:108:18
    let b: u64 = a % 256;
                 ^*****^
I might be able to make it work, but I think it is a waste of time.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2839)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/uint128.rs` line 294 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2839#-NTCgt4e5bFaQ5j24EO-:-NTn2Qg5E0Y7zJiFlMxI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5f29a8f4a4b29f5d70f3cded900f103342c75286/crates/cairo-lang-sierra/src/extensions/modules/uint128.rs#L294)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this already exists - not sure why it appeared here.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2839)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2839#-NTAzCPPCkr1bZymcWu1:-NTnDZaW-rvkWiVXE5Jk:bigy4oc) (no related file):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it gives me
error: Unexpected argument type. Expected: "core::integer::u64", found: "core::integer::u128".
 --> keccak.cairo:108:18
    let b: u64 = a % 256;
                 ^*****^
I might be able to make it work, but I think it is a waste of time.


</blockquote></details>

you'd just need to add `.into()`

___

**Comment by ilyalesokhin-starkware** [comment]
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you'd just need to add `.into()`
</blockquote></details>

it didn't compile and I don't want to fight with it.

lior said we should add the libfunc.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2839)* status: 0 of 14 files reviewed, 3 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2839#-NTAzCPPCkr1bZymcWu1:-NUpNjzH3WoDULGwEyLT:bbfileo) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is not a good claim for why this paricular libfunc should exist instead of any of the other options.
</blockquote></details>

change to u128_byte_reverse.

___

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 11 files at r5, 10 of 12 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2839)* status: 12 of 14 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/test/integer_test.cairo` line 889 at r6](https://reviewable.io/reviews/starkware-libs/cairo/2839#-NUpPnuVEoAQmpTVSjUJ:-NUpPnuVEoAQmpTVSjUK:bwc1g88) ([raw file](https://github.com/starkware-libs/cairo/blob/786969f106409ae30c4a5e85bb03c119ea89545e/corelib/src/test/integer_test.cairo#L889)):*
> ```Cairo
> #[test]
> fn test_u128_byte_reverse() {
>     let x = 0x000102030405060708090a0b0c0d0e0f_u128;
> ```

inline `x` and remove _u128
___
*[`crates/cairo-lang-sierra/src/extensions/modules/int/unsigned128.rs` line 309 at r6](https://reviewable.io/reviews/starkware-libs/cairo/2839#-NUpQ62Q7ozQohoGbLa3:-NUpQ62Q7ozQohoGbLa4:bqf61l6) ([raw file](https://github.com/starkware-libs/cairo/blob/786969f106409ae30c4a5e85bb03c119ea89545e/crates/cairo-lang-sierra/src/extensions/modules/int/unsigned128.rs#L309)):*
> ```XML
>         Ok(LibfuncSignature::new_non_branch_ex(
>             vec>                 ParamSignature {
> ```

use the ParamSignature::new(..).with_.. pattern.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned128.rs` line 451 at r6 ([raw file](https://github.com/starkware-libs/cairo/blob/786969f106409ae30c4a5e85bb03c119ea89545e/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned128.rs#L451)):*
> ```XML
>             const mask_imm = mask_imm;
>             const shift_imm = shift_imm;
>             tempvar shift_temp = shift_imm;
> ```

no need for the extra tempvar - as this is a valid immediate for the shifting mul.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2839#-:-NUpmVoM0BLWxPpfwi07:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2839)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/test/integer_test.cairo` line 889 at r6](https://reviewable.io/reviews/starkware-libs/cairo/2839#-NUpPnuVEoAQmpTVSjUJ:-NUpjXJ_EZX7dv-zFDtL:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/786969f106409ae30c4a5e85bb03c119ea89545e/corelib/src/test/integer_test.cairo#L889)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

inline `x` and remove _u128
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/int/unsigned128.rs` line 309 at r6](https://reviewable.io/reviews/starkware-libs/cairo/2839#-NUpQ62Q7ozQohoGbLa3:-NUpjfBMCg5L73u5tWog:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/786969f106409ae30c4a5e85bb03c119ea89545e/crates/cairo-lang-sierra/src/extensions/modules/int/unsigned128.rs#L309)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

use the ParamSignature::new(..).with_.. pattern.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2839)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
