### PR TITLE
Added Cairo extended GCD function

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3138)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3138)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/integer.cairo` line 1540 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3138#-NVUUdVgCvoJ5u1J5Z6d:-NVUUdVgCvoJ5u1J5Z6e:bkm92eb) ([raw file](https://github.com/starkware-libs/cairo/blob/841f4fa873dca5b9b6f25d708c95b3d6aec4009d/corelib/src/integer.cairo#L1540)):*
> ```Cairo
> // TODO(yuval): use signed integers once supported.
> /// Extended GCD: finds numbers (g, s, t, sign_s, sign_t) such that
> /// g = gcd(x, y) = sign_s*s*a + sign_t*t*b
> ```

extract to another module.
(maybe even a submodule of an algorithm module)
___
*[`corelib/src/test/integer_test.cairo` line 7 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3138#-NVTF2XU51cM6jdMImmF:-NVTF2XU51cM6jdMImmG:b-lvxncn) ([raw file](https://github.com/starkware-libs/cairo/blob/38a048ed83c687df2ca3926ba836a792ddd092a6/corelib/src/test/integer_test.cairo#L7)):*
> ```Cairo
> use integer::
> { u16_sqrt , u32_sqrt , u64_sqrt , u8_sqrt , BoundedInt , u128_wrapping_sub } ; #[test]
> fn test_u8_operators() {
> ```

you probably need to update formatter.



_Code quote:_
```Cairo
use option::OptionTrait;
use integer::
{ u16_sqrt , u32_sqrt , u64_sqrt , u8_sqrt , BoundedInt , u128_wrapping_sub } ; #[test]

fn test_u8_operators() {
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3138)* status: 2 of 8 files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/math.cairo` line 26 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3138#-NV_2yknBFKhuhGtEc9a:-NV_2yknBFKhuhGtEc9b:bf5fhhn) ([raw file](https://github.com/starkware-libs/cairo/blob/0aa03fc0bdcdbcde86baa1a1c815b1174b34650c/corelib/src/math.cairo#L26)):*
> ```Cairo
> >(
>     a: NonZero<T>, b: NonZero<T>
> ) -> (T, T, bool, T, bool) {
> ```

is there a a real need for both bools?
___
*[`corelib/src/math.cairo` line 49 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3138#-NV_2Yre-XnmXRoT6Rj_:-NV_2Yre-XnmXRoT6Rja:bcva0i9) ([raw file](https://github.com/starkware-libs/cairo/blob/0aa03fc0bdcdbcde86baa1a1c815b1174b34650c/corelib/src/math.cairo#L49)):*
> ```Cairo
>     fn is_one(self: T) -> bool;
>     /// Returns whether self is not equal to 1, the multiplicative identity element.
>     fn is_non_one(self: T) -> bool;
> ```

i think we don't need these:
- not used here.
- as efficient if you -1 and use `is_zero`.



_Code quote:_
```Cairo
    /// Returns whether self is equal to 1, the multiplicative identity element.
    fn is_one(self: T) -> bool;
    /// Returns whether self is not equal to 1, the multiplicative identity element.
    fn is_non_one(self: T) -> bool;
```

**Comment by yuvalsw** [comment]
*[`corelib/src/math.cairo` line 49 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3138#-NV_2Yre-XnmXRoT6Rj_:-NV_BwifAvieOHmIm9fY:br2v2cv) ([raw file](https://github.com/starkware-libs/cairo/blob/0aa03fc0bdcdbcde86baa1a1c815b1174b34650c/corelib/src/math.cairo#L49)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i think we don't need these:
- not used here.
- as efficient if you -1 and use `is_zero`.
</blockquote></details>

This is orthogonal to this PR (I moved it from integer.cairo).
Anyway, I agree, but I added these to look like zeroable. We can make a future PR to change both.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3138)* status: 2 of 8 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/integer.cairo` line 1540 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3138#-NVUUdVgCvoJ5u1J5Z6d:-NVZvdhZ1vZyvmduYxGN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/841f4fa873dca5b9b6f25d708c95b3d6aec4009d/corelib/src/integer.cairo#L1540)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

extract to another module.
(maybe even a submodule of an algorithm module)
</blockquote></details>

Done.
___
*[`corelib/src/math.cairo` line 26 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3138#-NV_2yknBFKhuhGtEc9a:-NV_IP-mEc4M0CL1-zH6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0aa03fc0bdcdbcde86baa1a1c815b1174b34650c/corelib/src/math.cairo#L26)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is there a a real need for both bools?
</blockquote></details>

Done.
___
*[`corelib/src/test/integer_test.cairo` line 7 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3138#-NVTF2XU51cM6jdMImmF:-NVZtR31DHSsyBkcY10m:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/38a048ed83c687df2ca3926ba836a792ddd092a6/corelib/src/test/integer_test.cairo#L7)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you probably need to update formatter.
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 6 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3138)* status: 6 of 8 files reviewed, all discussions resolved

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r4, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3138#-:-NV_M8wiCO2C3HQ-ZQ8o:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3138)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3138)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
