### PR TITLE
Add get_circuit_output.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5717)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs` line 465 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5717#-NzY86Jj0RBTqOHj9gHv:-NzY86Jj0RBTqOHj9gHw:ba92i3h) ([raw file](https://github.com/starkware-libs/cairo/blob/a8b3a880adb4f7014c3f6af8f03e95174609d5d2/crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs#L465)):*
> ```XML
>         tempvar output_ptr = values_ptr + output_offset;
> 
>         tempvar output0 = output_ptr[0];
> ```

I can do the following, but there is a high risk of exceeding the max allowed offset.



_Suggestion:_
```XML
        tempvar output0 = values_ptr[output_offset];
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5717)* status: 3 of 7 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/circuit.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5717#-NzYEKsa8MBZ1B0DS6fX:-NzYEKsa8MBZ1B0DS6fY:bu1y2ya) ([raw file](https://github.com/starkware-libs/cairo/blob/a8b3a880adb4f7014c3f6af8f03e95174609d5d2/crates/cairo-lang-sierra/src/extensions/modules/circuit.rs#L59)):*
> ```XML
>          GetDescriptor(GetCircuitDescriptorLibFunc),
>          InitCircuitData(InitCircuitDataLibFunc),
>          GetOuput(GetOuputLibFunc),
> ```

GetOutput

**Review by orizi — COMMENTED** [review]
> Reviewed 4 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5717)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs` line 465 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5717#-NzY86Jj0RBTqOHj9gHv:-NzYExnt6iZV662x1TRS:bs7og3c) ([raw file](https://github.com/starkware-libs/cairo/blob/a8b3a880adb4f7014c3f6af8f03e95174609d5d2/crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs#L465)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I can do the following, but there is a high risk of exceeding the max allowed offset.
</blockquote></details>

Doc it

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5717)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/circuit.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5717#-NzYEKsa8MBZ1B0DS6fX:-NzYFes89VTDxzK1NYae:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a8b3a880adb4f7014c3f6af8f03e95174609d5d2/crates/cairo-lang-sierra/src/extensions/modules/circuit.rs#L59)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

GetOutput
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5717#-:-NzYJ7CPALpd__CMi6Xl:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 7 files at r1, 5 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5717)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
