### PR TITLE
Added .intern() methods to all IDs

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5429)

### CODE REVIEW

**Comment by yuvalsw** [comment]
change target branch

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 54 of 72 files at r1, 18 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5429)* status: all files reviewed, 2 unresolved discussions (waiting on @mkaput and @yuvalsw)

___
*[`crates/cairo-lang-formatter/src/lib.rs` line 56 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5429#-NvbalUICIAyhKsuPJuV:-NvbalUICIAyhKsuPJuW:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/90526e4b643027d392cbc8b36ed77973c6589684/crates/cairo-lang-formatter/src/lib.rs#L56)):*
> ```XML
>         kind: FileKind::Module,
>     })
>     // TODO(yg): remove upcast?
> ```

?

**Review by mkaput — APPROVED** [review]
> Reviewed 54 of 72 files at r1, 18 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5429)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi and @yuvalsw)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5429#-:-NvjsPcf8dKehfCTDNfO:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5429#-:-NvkOYN63QpusE6e2FJz:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5429)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
