### PR TITLE
Enabled redeposit for all cost types.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4665)

### CODE REVIEW

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4665)* status: 7 of 11 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/gas.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4665#-NmuOL849HnlwCI-53kN:-NmuOL849HnlwCI-53kO:bnhv57d) ([raw file](https://github.com/starkware-libs/cairo/blob/7b0bece97fb44c4d6b4cdb7405214800a4cd64d8/crates/cairo-lang-sierra/src/extensions/modules/gas.rs#L213)):*
> ```XML
>     /// Returns the number of steps required for the computation of the requested cost, given the
>     /// number of requested token usages. The number of steps is also the change in `ap` (every
>     /// step includes `ap++`).
> ```

Remove/modify since the explanation is not accurate anymore - the `call` and `ret` in fetching the table adds two to ap, but not because they include `ap++`.



_Suggestion:_
```XML
    /// number of requested token usages. The number of steps is also the change in `ap`.
```
___
*[`tests/e2e_test.rs` line 202 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4665#-Nmz35B50fGgL0afR4ek:-Nmz35B50fGgL0afR4el:ba854ie) ([raw file](https://github.com/starkware-libs/cairo/blob/7b0bece97fb44c4d6b4cdb7405214800a4cd64d8/tests/e2e_test.rs#L202)):*
> ```XML
>         MetadataComputationConfig { function_set_costs: enforced_costs, ..Default::default() };
>     let metadata_with_linear = calc_metadata(&sierra_program, metadata_config.clone()).unwrap();
>     println!("Metadata: {}", metadata_with_linear.gas_info);
> ```

Revert?
___
*[`tests/e2e_test_data/metadata_computation` line 870 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4665#-NmzktW_Dd2eFbbM7STn:-NmzkRLh4cW63HdjhfCt:b-yatr66) ([raw file](https://github.com/starkware-libs/cairo/blob/7b0bece97fb44c4d6b4cdb7405214800a4cd64d8/tests/e2e_test_data/metadata_computation#L870)):*
> ```
> #1: OrderedHashMap({Pedersen: 0, Poseidon: 0, Bitwise: 0, EcOp: 0, Const: 0})
> #13: OrderedHashMap({Pedersen: 0, Poseidon: 0, Bitwise: 0, EcOp: 0, Const: 0})
> #15: OrderedHashMap({Pedersen: 0, Poseidon: 0, Bitwise: 3, EcOp: 0, Const: 1310})
> ```

Let's discuss f2f.
___
*[`tests/e2e_test_data/libfuncs/gas` line 93 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4665#-NmuNqvo-e-cPW3mKoxd:-NmuNqvo-e-cPW3mKoxe:bj0q60z) ([raw file](https://github.com/starkware-libs/cairo/blob/7b0bece97fb44c4d6b4cdb7405214800a4cd64d8/tests/e2e_test_data/libfuncs/gas#L93)):*
> ```
> fn foo(x: felt252) {
>     if x == 0 {
> 	1 & 2_u128;
> ```

Replace tab with spaces.

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4665)* status: 8 of 11 files reviewed, 5 unresolved discussions (waiting on @orizi)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4665)* status: 9 of 11 files reviewed, 5 unresolved discussions (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4665)* status: 9 of 11 files reviewed, 5 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/gas.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4665#-NmuOL849HnlwCI-53kN:-Nn-B8i987Ox5cba3Zcz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7b0bece97fb44c4d6b4cdb7405214800a4cd64d8/crates/cairo-lang-sierra/src/extensions/modules/gas.rs#L213)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Remove/modify since the explanation is not accurate anymore - the `call` and `ret` in fetching the table adds two to ap, but not because they include `ap++`.
</blockquote></details>

Done.
___
*[`tests/e2e_test.rs` line 202 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4665#-Nmz35B50fGgL0afR4ek:-Nn-Aray2zu9vE-MvGDR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7b0bece97fb44c4d6b4cdb7405214800a4cd64d8/tests/e2e_test.rs#L202)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Revert?
</blockquote></details>

Done.
___
*[`tests/e2e_test_data/libfuncs/gas` line 93 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4665#-NmuNqvo-e-cPW3mKoxd:-Nn-Aa-2Ehw4Q9396Krg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7b0bece97fb44c4d6b4cdb7405214800a4cd64d8/tests/e2e_test_data/libfuncs/gas#L93)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Replace tab with spaces.
</blockquote></details>

Done.
___
*[`tests/e2e_test_data/libfuncs/gas` line 104 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4665#-NmzvykB27Ma0_I7kBTo:-Nn-AagsEiwWnEbUR7T9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7b0bece97fb44c4d6b4cdb7405214800a4cd64d8/tests/e2e_test_data/libfuncs/gas#L104)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Not used?
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4665)* status: 5 of 11 files reviewed, 5 unresolved discussions (waiting on @liorgold2)

___
*[`tests/e2e_test_data/metadata_computation` line 870 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4665#-NmzktW_Dd2eFbbM7STn:-Nn3ndaj5NFlh0O8F5g4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7b0bece97fb44c4d6b4cdb7405214800a4cd64d8/tests/e2e_test_data/metadata_computation#L870)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Let's discuss f2f.
</blockquote></details>

Done.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4665)* status: 7 of 11 files reviewed, 6 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs` line 124 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4665#-Nn9sbm_4gNiSv7763TP:-Nn9sbma2FrtNAW0zl-u:b-182afu) ([raw file](https://github.com/starkware-libs/cairo/blob/80d40a41b8a2d040479ad4f97ec21cbf8d565423/crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs#L124)):*
> ```XML
>         ));
>     }
>     if !CostTokenType::iter().all(|token| variable_values.contains_key(&(builder.idx, *token))) {
> ```

This is sanity check, right?
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs` line 144 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4665#-Nn9sspP8Y2--S_R0F--:-Nn9sspP8Y2--S_R0F-0:b-eurkta) ([raw file](https://github.com/starkware-libs/cairo/blob/80d40a41b8a2d040479ad4f97ec21cbf8d565423/crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs#L144)):*
> ```XML
>         casm_builder,
>         [("Fallthrough", &[&[updated_gas]], None)],
>         CostValidationInfo { range_check_info: None, extra_costs: Some([requested_count as i32]) },
> ```

What does this do?



_Code quote:_
```XML
extra_costs: Some([requested_count as i32])
```

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4665)* status: 9 of 11 files reviewed, 5 unresolved discussions (waiting on @orizi)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4665)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @orizi)

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4665#-:-NnAFUk33DzTY5gEVEkp:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4665)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs` line 124 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4665#-Nn9sbm_4gNiSv7763TP:-NnAQbBP3ljpTdoP5FEO:bfmajdi) ([raw file](https://github.com/starkware-libs/cairo/blob/80d40a41b8a2d040479ad4f97ec21cbf8d565423/crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs#L124)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

This is sanity check, right?
</blockquote></details>

yes - pretty much the flip side of the old validate 0.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs` line 144 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4665#-Nn9sspP8Y2--S_R0F--:-NnAQiff2GiNl2J4aD_S:b-evsp87) ([raw file](https://github.com/starkware-libs/cairo/blob/80d40a41b8a2d040479ad4f97ec21cbf8d565423/crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs#L144)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

What does this do?
</blockquote></details>

the extra removed cost that isn't counted in the builder.
(in the withdraw variant we have a `-requested_count` instead for example)

**Review by liorgold2 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4665)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
