### PR TITLE
Refactor analyze_ap_changes.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2754)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2754)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2754#-NSdx7yz8zBlHI_6QEgn:-NSdx7yz8zBlHI_6QEgo:b-klhu02) ([raw file](https://github.com/starkware-libs/cairo/blob/3fc4eea2819fb5077640512da00c867f6e5cb88c/crates/cairo-lang-sierra-generator/src/local_variables.rs#L73)):*
> ```XML
>     let peeled_used_after_revoke: OrderedHashSet<_> =
>         ctx.used_after_revoke.iter().map(|var| ctx.peel_aliases(var)).copied().collect();
>     let locals = ctx.filter_locals(&peeled_used_after_revoke, &peeled_used_after_revoke);
> ```

are you planing to have an additional usage for this?
as you are providing the same var twice.



_Code quote:_
```XML
let locals = ctx.filter_locals(&peeled_used_after_revoke, &peeled_used_after_revoke);
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2754#-NSdx7yz8zBlHI_6QEgn:-NSdxY0AEJIpJz1v3Col:badix7s) ([raw file](https://github.com/starkware-libs/cairo/blob/3fc4eea2819fb5077640512da00c867f6e5cb88c/crates/cairo-lang-sierra-generator/src/local_variables.rs#L73)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

are you planing to have an additional usage for this?
as you are providing the same var twice.
</blockquote></details>

yes, I'm going to add:
let need_ap_align = ctx.filter_locals(&peeled_used_after_revoke, &need_ap_align);

**Comment by ilyalesokhin-starkware** [comment]
Actually, I need to think about it a bit more.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2754)* status: all files reviewed, 3 unresolved discussions

___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2754#-NSdx7yz8zBlHI_6QEgn:-NSe-7LeA-AaZvpHX1uN:b-9pgwn7) ([raw file](https://github.com/starkware-libs/cairo/blob/3fc4eea2819fb5077640512da00c867f6e5cb88c/crates/cairo-lang-sierra-generator/src/local_variables.rs#L73)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

yes, I'm going to add:
let need_ap_align = ctx.filter_locals(&peeled_used_after_revoke, &need_ap_align);
</blockquote></details>

i'm not sure how this would work exactly - but would see at the time.
___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2754#-NSdzlfoCRlHjKFKtnOo:-NSdzlfoCRlHjKFKtnOp:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/3fc4eea2819fb5077640512da00c867f6e5cb88c/crates/cairo-lang-sierra-generator/src/local_variables.rs#L181)):*
> ```XML
> 
> impl<'a> FindLocalsContext<'a> {
>     // Given a variable that might be an alias follow aliases until we get the original variable.
> ```





_Suggestion:_
```XML
impl<'a> FindLocalsContext<'a> {
    /// Given a variable that might be an alias follow aliases until we get the original variable.
```
___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 193 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2754#-NSdzyA756pNESGdhlmm:-NSdzyA756pNESGdhlmn:b4rfydg) ([raw file](https://github.com/starkware-libs/cairo/blob/3fc4eea2819fb5077640512da00c867f6e5cb88c/crates/cairo-lang-sierra-generator/src/local_variables.rs#L193)):*
> ```XML
>         &self,
>         revoked_vars: &OrderedHashSet<VariableId>,
>         vars: &OrderedHashSet<VariableId>,
> ```

rename these to make more sense.



_Code quote:_
```XML
        revoked_vars: &OrderedHashSet<VariableId>,
        vars: &OrderedHashSet<VariableId>,
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2754)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2754#-NSdx7yz8zBlHI_6QEgn:-NSe2B9952uTF-ezn0cQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3fc4eea2819fb5077640512da00c867f6e5cb88c/crates/cairo-lang-sierra-generator/src/local_variables.rs#L73)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i'm not sure how this would work exactly - but would see at the time.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2754#-NSdzlfoCRlHjKFKtnOo:-NSe2AaU4ZmvWfeAC1f4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3fc4eea2819fb5077640512da00c867f6e5cb88c/crates/cairo-lang-sierra-generator/src/local_variables.rs#L181)):*
> ```XML
> 
> impl<'a> FindLocalsContext<'a> {
>     // Given a variable that might be an alias follow aliases until we get the original variable.
> ```

Done.
___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 193 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2754#-NSdzyA756pNESGdhlmm:-NSe2AoCEYLLshYP58aQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3fc4eea2819fb5077640512da00c867f6e5cb88c/crates/cairo-lang-sierra-generator/src/local_variables.rs#L193)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rename these to make more sense.
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2754#-NSe2EsV4ZizL7wR6gvu:-NSe2EsV4ZizL7wR6gvv:b-u85u8e) ([raw file](https://github.com/starkware-libs/cairo/blob/a09a8fdbc9d1ba13b8c211a4011a3d58a37f3249/crates/cairo-lang-sierra-generator/src/local_variables.rs#L48)):*
> ```XML
>         used_after_revoke: Default::default(),
>         block_callers: Default::default(),
>         unrevocable: UnorderedHashSet::from_iter(lowered_function.parameters.iter().cloned()),
> ```

is this name ok?

do we prefer
not_ap_based?



_Code quote:_
```XML
unrevocable
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2754)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 199 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2754#-NSe2IqgAYPmF_sr2kec:-NSe2IqgAYPmF_sr2ked:b-m5lba9) ([raw file](https://github.com/starkware-libs/cairo/blob/a09a8fdbc9d1ba13b8c211a4011a3d58a37f3249/crates/cairo-lang-sierra-generator/src/local_variables.rs#L199)):*
> ```XML
>     ///
>     /// Note that `revoked_vars` are variable that are going to be unrevocable.
>     pub fn is_revokable(
> ```

do we prefer
is_ap_based?



_Code quote:_
```XML
is_revokable
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2754)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2754#-NSe2EsV4ZizL7wR6gvu:-NSe6jN27P7neHpjSUFw:b-yqf9eu) ([raw file](https://github.com/starkware-libs/cairo/blob/a09a8fdbc9d1ba13b8c211a4011a3d58a37f3249/crates/cairo-lang-sierra-generator/src/local_variables.rs#L48)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

is this name ok?

do we prefer
not_ap_based?
</blockquote></details>

it all depends on how we fill this struct - currently all i know about it is that it declares "whatever is here is not in locals"
___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 199 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2754#-NSe2IqgAYPmF_sr2kec:-NSe73Mi9BmDSosfMwDZ:b-oghxrf) ([raw file](https://github.com/starkware-libs/cairo/blob/a09a8fdbc9d1ba13b8c211a4011a3d58a37f3249/crates/cairo-lang-sierra-generator/src/local_variables.rs#L199)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

do we prefer
is_ap_based?
</blockquote></details>

i'm not sure it is any of these - this just answers - do we need to store it as a local, or not - we might not need to for various reasons.
___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 201 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2754#-NSe7Eef-EFdy88cYIG6:-NSe7Eef-EFdy88cYIG7:b-v82e1l) ([raw file](https://github.com/starkware-libs/cairo/blob/a09a8fdbc9d1ba13b8c211a4011a3d58a37f3249/crates/cairo-lang-sierra-generator/src/local_variables.rs#L201)):*
> ```XML
>     pub fn is_revokable(
>         &self,
>         revoked_vars: &OrderedHashSet<VariableId>,
> ```

these aren't actually revoked vars - these are vars that we make sure won't be revoked (as this is the algorithm that happens here)



_Code quote:_
```XML
revoked_vars
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 201 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2754#-NSe7Eef-EFdy88cYIG6:-NSe_9LjEtW_ch-71tiW:b-mvecv1) ([raw file](https://github.com/starkware-libs/cairo/blob/a09a8fdbc9d1ba13b8c211a4011a3d58a37f3249/crates/cairo-lang-sierra-generator/src/local_variables.rs#L201)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

these aren't actually revoked vars - these are vars that we make sure won't be revoked (as this is the algorithm that happens here)
</blockquote></details>

they would have been revoked if they were ap based.

do you have a better name?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2754)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2754#-NSe2EsV4ZizL7wR6gvu:-NSea-1G2hW0MhsumBCk:bmsraks) ([raw file](https://github.com/starkware-libs/cairo/blob/a09a8fdbc9d1ba13b8c211a4011a3d58a37f3249/crates/cairo-lang-sierra-generator/src/local_variables.rs#L48)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it all depends on how we fill this struct - currently all i know about it is that it declares "whatever is here is not in locals"
</blockquote></details>

As far as I can tell, it holds literals and fp-based vars.
___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 199 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2754#-NSe2IqgAYPmF_sr2kec:-NSe_tnvBSv0PHcOdVCq:b-4lascv) ([raw file](https://github.com/starkware-libs/cairo/blob/a09a8fdbc9d1ba13b8c211a4011a3d58a37f3249/crates/cairo-lang-sierra-generator/src/local_variables.rs#L199)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i'm not sure it is any of these - this just answers - do we need to store it as a local, or not - we might not need to for various reasons.
</blockquote></details>

I don't follow.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2754)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 199 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2754#-NSe2IqgAYPmF_sr2kec:-NSev4iLA1DNegxZCUzV:b-chqres) ([raw file](https://github.com/starkware-libs/cairo/blob/a09a8fdbc9d1ba13b8c211a4011a3d58a37f3249/crates/cairo-lang-sierra-generator/src/local_variables.rs#L199)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

This function does not tell you if this is ap-based, or revoked, it tells you if you need to store this variable specifically as local.
You made decide not to because:
It was the function's param
It is const
It is contained within another local variable

So this var will be local anyway - the question is - do we need a specific store for, so the name here is wrong.
</blockquote></details>

The function answers the question can 'peeled_var' be revoked if we don't make it a local.



_Code quote:_
```XML
might_be_revoked
```
___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 201 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2754#-NSe7Eef-EFdy88cYIG6:-NSev-em5hqRAdI5ZuhY:b-opou46) ([raw file](https://github.com/starkware-libs/cairo/blob/a09a8fdbc9d1ba13b8c211a4011a3d58a37f3249/crates/cairo-lang-sierra-generator/src/local_variables.rs#L201)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

they would have been revoked if they were ap based.

do you have a better name?


</blockquote></details>

I used the original name.

**Pull request merged**
