### PR TITLE
Update felt252-type.adoc

### PR DESCRIPTION
**Pull request by victorMagdesian**
reference:https://cairo-by-example.com/examples/felt252/

### CODE REVIEW

**Review by victorMagdesian — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6790)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @victorMagdesian)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6790)* status: all files reviewed, 1 unresolved discussion (waiting on @victorMagdesian)

___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/felt252-type.adoc` line 4 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6790#-OD5qTmV3tsUdkNk9pn8:-OD5qTmV3tsUdkNk9pn9:bjktf4a) ([raw file](https://github.com/starkware-libs/cairo/blob/edc4b37ebb230d67401805d2c84ccd13012c2a3d/docs/reference/src/components/cairo/modules/language_constructs/pages/felt252-type.adoc#L4)):*
> ```AsciiDoc
> 
> 
> Field elements have the property of intentionally "wrapping around" when their value exceeds the specified range, using modular arithmetic.
> ```

limit your lines to 100 chars (3 times in this file)

**Review by victorMagdesian — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6790)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/felt252-type.adoc` line 4 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6790#-OD5qTmV3tsUdkNk9pn8:-OD6JDMC-OCIhDHJEqxe:bvm7z8d) ([raw file](https://github.com/starkware-libs/cairo/blob/edc4b37ebb230d67401805d2c84ccd13012c2a3d/docs/reference/src/components/cairo/modules/language_constructs/pages/felt252-type.adoc#L4)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

limit your lines to 100 chars (3 times in this file)
</blockquote></details>

Resolved

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6790#-:-OD6Y_-01W0Z6LKV8LUA:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @victorMagdesian)

**Pull request merged**
