### PR TITLE
Added u32.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:4c45a9f8

---

**Stack**:
- #2066
- #2065 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2065)* status: 5 of 15 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/uint.rs` line 553 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2065#-NNoagqGDTxYEUCzPgI5:-NNoagqGDTxYEUCzPgI6:bnwm10v) ([raw file](https://github.com/starkware-libs/cairo/blob/adb2e0b5a26915e3894943c0ea926ad888ec287b/crates/cairo-lang-sierra/src/extensions/modules/uint.rs#L553)):*
> ```XML
>     const CONST: &'static str = "u32_const";
>     const EQUAL: &'static str = "u32_eq";
>     const SQUARE_ROOT: &'static str = "u64_sqrt";
> ```

it this intentional? don't you have a typing issue?



_Code quote:_
```XML
u64
```

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/integer.cairo` line 334 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2065#-NNofKi1DY-efhUhyPBy:-NNofKi1DY-efhUhyPBz:b-6atk61) ([raw file](https://github.com/starkware-libs/cairo/blob/adb2e0b5a26915e3894943c0ea926ad888ec287b/corelib/integer.cairo#L334)):*
> ```Cairo
> }
> 
> extern fn u32_overflowing_add(a: u32, b: u32) -> Result::<u32, u32> implicits(RangeCheck) nopanic;
> ```

where is this implemented?



_Code quote:_
```Cairo
extern fn u32_overflowing_add(a: u32, b: u32) -> Result::<u32, u32> implicits(RangeCheck) nopanic;
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 7 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2065)* status: 12 of 15 files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2065)* status: 12 of 15 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`corelib/integer.cairo` line 334 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2065#-NNofKi1DY-efhUhyPBy:-NNovb5t79S-wYsdLgBp:bc5qdsk) ([raw file](https://github.com/starkware-libs/cairo/blob/adb2e0b5a26915e3894943c0ea926ad888ec287b/corelib/integer.cairo#L334)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

where is this implemented?
</blockquote></details>

discussed f2f
___
*[`crates/cairo-lang-sierra/src/extensions/modules/uint.rs` line 553 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2065#-NNoagqGDTxYEUCzPgI5:-NNovccOCCJGnUbaLZGr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/adb2e0b5a26915e3894943c0ea926ad888ec287b/crates/cairo-lang-sierra/src/extensions/modules/uint.rs#L553)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it this intentional? don't you have a typing issue?
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 15 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2065#-:-NNoyDaj5dHaFmI3KCzR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
