### PR TITLE
Adding support to Const in Statements in Parser

### PR DESCRIPTION
**Pull request by Tomer-StarkWare**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6245)

### CODE REVIEW

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6245)* status: 1 of 8 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/constant` line 197 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6245#-O4k2APKEZ74qjfNUCsQ:-O4kCVaGD1dahy9GT-R5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a76484b91c53abcdbf161facc18fa86565c26804/crates/cairo-lang-parser/src/parser_test_data/partial_trees/constant#L197)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add an additional test that adds an `#[attribute]` over such a const.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6245)* status: 1 of 8 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1987 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6245#-O4kDzOEDaWwyPoPxWAn:-O4kDzOEDaWwyPoPxWAo:b-ae5o0v) ([raw file](https://github.com/starkware-libs/cairo/blob/68a27c89eb58228b210303721f245986e12b017b/crates/cairo-lang-parser/src/parser.rs#L1987)):*
> ```XML
>             }
>             SyntaxKind::TerminalConst => {
>                 let mod_item_green = Self::try_parse_module_item(self)?;
> ```

rename function.
also - extract from`try_parse_module_item` the code for calling given the attributes (that are already parsed out of the current match)



_Code quote:_
```XML
                let mod_item_green = Self::try_parse_module_item(self)?;
```

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6245)* status: 1 of 8 files reviewed, 3 unresolved discussions (waiting on @orizi and @Tomer-StarkWare)

___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/constant` line 225 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6245#-O4ncatXDgmpxTtqzxLi:-O4ncatY6CKru5hFtB-5:b-vjbrgr) ([raw file](https://github.com/starkware-libs/cairo/blob/68a27c89eb58228b210303721f245986e12b017b/crates/cairo-lang-parser/src/parser_test_data/partial_trees/constant#L225)):*
> ```
> //! > ==========================================================================
> 
> //! > Const Statements attribute with Missing Type
> ```

No need for the missing type with the attribute test. And the attribute is not parsed correctly, see Ori's comment in parser.rs.



_Code quote:_
```
Const Statements attribute with Missing Type
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6245)* status: 1 of 8 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1987 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6245#-O4kDzOEDaWwyPoPxWAn:-O4oALZd6OpyOvC3ckDZ:b-gc4ceq) ([raw file](https://github.com/starkware-libs/cairo/blob/68a27c89eb58228b210303721f245986e12b017b/crates/cairo-lang-parser/src/parser.rs#L1987)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rename function.
also - extract from`try_parse_module_item` the code for calling given the attributes (that are already parsed out of the current match)
</blockquote></details>

I'm using a different function, should I still rename the function?
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/constant` line 225 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6245#-O4ncatXDgmpxTtqzxLi:-O4oAL7XAJGdNV27VPUU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/68a27c89eb58228b210303721f245986e12b017b/crates/cairo-lang-parser/src/parser_test_data/partial_trees/constant#L225)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

No need for the missing type with the attribute test. And the attribute is not parsed correctly, see Ori's comment in parser.rs.
</blockquote></details>

Done.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6245)* status: 1 of 8 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/constant` line 225 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6245#-O4ncatXDgmpxTtqzxLi:-O4oB1w_AKi9b68o9yHh:b-vfyjh2) ([raw file](https://github.com/starkware-libs/cairo/blob/68a27c89eb58228b210303721f245986e12b017b/crates/cairo-lang-parser/src/parser_test_data/partial_trees/constant#L225)):*
<details><summary><i>Previously, Tomer-StarkWare (TomerC-StarkWare) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Change the test title.

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 8 files at r1, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6245)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi and @Tomer-StarkWare)

___
*[`crates/cairo-lang-syntax/src/node/helpers.rs` line 487 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6245#-O4oJYHIDRJ9r8cZRq7P:-O4oJYHIDRJ9r8cZRq7Q:b-1xv6k2) ([raw file](https://github.com/starkware-libs/cairo/blob/9bec18ecf57cefbc60f76871201d456ad6917f81/crates/cairo-lang-syntax/src/node/helpers.rs#L487)):*
> ```XML
>             Statement::Let(statement) => statement.attributes_elements(db),
>             Statement::Expr(statement) => statement.attributes_elements(db),
>             Statement::Item(_) => todo!(),
> ```

Add it in this pr as it is a syntactic query.



_Code quote:_
```XML
Statement::Item(_) => todo!(),
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6245)* status: all files reviewed, 1 unresolved discussion (waiting on @Tomer-StarkWare)

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6245)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-syntax/src/node/helpers.rs` line 487 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6245#-O4oJYHIDRJ9r8cZRq7P:-O4oY6cy67M6aYHeLNsx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9bec18ecf57cefbc60f76871201d456ad6917f81/crates/cairo-lang-syntax/src/node/helpers.rs#L487)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Add it in this pr as it is a syntactic query.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6245#-:-O4oYzym3P4ybBiFKZQq:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6245#-:-O4oo2AiBjpQyULdHbrg:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Tomer-StarkWare)

**Pull request merged**
