### PR TITLE
Refactor ExprClosure and its format function.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6037)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6037)* status: 1 of 8 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-diagnostics/src/diagnostics.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6037#-O24IQDV7MeQfW7dWC3D:-O24IQDV7MeQfW7dWC3E:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/3c8fded35591637a9587a5b28c6ea83e70d1fd6b/crates/cairo-lang-diagnostics/src/diagnostics.rs#L70)):*
> ```XML
>         Self { file_id, span }
>     }
> ```

doc
___
*[`crates/cairo-lang-semantic/src/types.rs` line 800 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6037#-O24Hmqo2UXEY8Q6p3RZ:-O24J3Y1AM4SypI-Ue6K:b-ezumkq) ([raw file](https://github.com/starkware-libs/cairo/blob/3c8fded35591637a9587a5b28c6ea83e70d1fd6b/crates/cairo-lang-semantic/src/types.rs#L800)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I'm not sure what the correct answer is here.
but before this PR, we defined closure as different.
"if closure0.body_id != closure1.body_id"
So generic argument of the containing_function didn't really effect the type of the closure.
</blockquote></details>

yeah - IMO it is logically dependent on the outer function - but it depends on our usage of this function.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/types.rs` line 800 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6037#-O24Hmqo2UXEY8Q6p3RZ:-O24LcmADAvcRPqvJQff:b-sefw4m) ([raw file](https://github.com/starkware-libs/cairo/blob/3c8fded35591637a9587a5b28c6ea83e70d1fd6b/crates/cairo-lang-semantic/src/types.rs#L800)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

yeah - IMO it is logically dependent on the outer function - but it depends on our usage of this function.
</blockquote></details>

The original usage was here:
https://github.com/starkware-libs/cairo/blob/774405d12fa31dc1d0c9a65521f67d35a857556d/crates/cairo-lang-semantic/src/expr/inference.rs#L923

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/types.rs` line 404 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6037#-O24MGRh6Vx_DCmjv581:-O24MGRh6Vx_DCmjv582:bs14yyj) ([raw file](https://github.com/starkware-libs/cairo/blob/00da82c3839e42f6640b0776ba34a4badbe605fd/crates/cairo-lang-semantic/src/types.rs#L404)):*
> ```XML
>     /// Every closure has a unique type that is based on the stable location of its wrapper.
>     #[dont_rewrite]
>     pub wrapper_location: StableLocation,
> ```

it seems that rust is using the location of the wrapper to define the closure:



_Code quote (i):_
```XML
 pub wrapper_location: StableLocation,
```



_Code snippet (ii):_
```XML
    let a = |b, c| {
        b;
    };

    if a != 5 {}
    
    gives:
    error[E0369]: binary operation `!=` cannot be applied to type `{closure@crates/cairo-lang-lowering/src/concretize/mod.rs:17:13: 17:19}`
  --> crates/cairo-lang-lowering/src/concretize/mod.rs:21:10
   |
21 |     if a != 5 {}
   |        - ^^ - {integer}
   |        |
   |        {closure@crates/cairo-lang-lowering/src/concretize/mod.rs:17:13: 17:19}
```

**Review by TomerStarkware — APPROVED** [review]
> Reviewed 3 of 8 files at r1, 3 of 5 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6037)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 800 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6037#-O24Hmqo2UXEY8Q6p3RZ:-O24OVyT73WhcAqCRX_L:b-xybga5) ([raw file](https://github.com/starkware-libs/cairo/blob/3c8fded35591637a9587a5b28c6ea83e70d1fd6b/crates/cairo-lang-semantic/src/types.rs#L800)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

The original usage was here:
https://github.com/starkware-libs/cairo/blob/774405d12fa31dc1d0c9a65521f67d35a857556d/crates/cairo-lang-semantic/src/expr/inference.rs#L923
</blockquote></details>

I think ignoring the containing function before was a mistake
___
*[`crates/cairo-lang-semantic/src/types.rs` line 404 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6037#-O24MGRh6Vx_DCmjv581:-O24O2ue15lnfj6bOV8Q:bc06jf9) ([raw file](https://github.com/starkware-libs/cairo/blob/00da82c3839e42f6640b0776ba34a4badbe605fd/crates/cairo-lang-semantic/src/types.rs#L404)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it seems that rust is using the location of the wrapper to define the closure:
</blockquote></details>

Don't we still want the concrete-containing function for the type?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-diagnostics/src/diagnostics.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6037#-O24IQDV7MeQfW7dWC3D:-O24Y3iUELHJk3Id3eHU:b-a1d8gu) ([raw file](https://github.com/starkware-libs/cairo/blob/3c8fded35591637a9587a5b28c6ea83e70d1fd6b/crates/cairo-lang-diagnostics/src/diagnostics.rs#L70)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

I'm not sure there is something useful I can write here.
The last line in the function is the most useful documentation, do you want me to copy it to the comment?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/types.rs` line 404 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6037#-O24MGRh6Vx_DCmjv581:-O24YMMcCRu22s0xR7Op:bf2c6r4) ([raw file](https://github.com/starkware-libs/cairo/blob/00da82c3839e42f6640b0776ba34a4badbe605fd/crates/cairo-lang-semantic/src/types.rs#L404)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

Don't we still want the concrete-containing function for the type?
</blockquote></details>

Assuming the closure type can't escape from the function, I think it is not nessiary.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6037)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @orizi and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 800 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6037#-O24Hmqo2UXEY8Q6p3RZ:-O24YX_J1c9zDPJ1TBsO:bw5qaxv) ([raw file](https://github.com/starkware-libs/cairo/blob/3c8fded35591637a9587a5b28c6ea83e70d1fd6b/crates/cairo-lang-semantic/src/types.rs#L800)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

I think ignoring the containing function before was a mistake
</blockquote></details>

I think we should proceed under the assumption that a closure type cannot escape from the function.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6037#-:-O24jJWP9Xre4tjv-E5M:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

**Review by TomerStarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6037)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/lower/test_data/usage` line 197 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6037#-O24lhXjCoOwITjn-1CA:-O24lhXjCoOwITjn-1CB:bzaukbi) ([raw file](https://github.com/starkware-libs/cairo/blob/5b5eec88c1d56f7f6d947ddfefbfb9afccfcffd7/crates/cairo-lang-lowering/src/lower/test_data/usage#L197)):*
> ```
> //! > ==========================================================================
> 
> //! > Test closure usage
> ```

why revert?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/test_data/usage` line 197 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6037#-O24lhXjCoOwITjn-1CA:-O24rMur0RYeE7hnsNCa:bmiith) ([raw file](https://github.com/starkware-libs/cairo/blob/5b5eec88c1d56f7f6d947ddfefbfb9afccfcffd7/crates/cairo-lang-lowering/src/lower/test_data/usage#L197)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

why revert?
</blockquote></details>

I want to do it in another PR.

**Review by TomerStarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6037#-:-O24ufsQDabM-9nxWqJ1:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by TomerStarkware — APPROVED** [review]
:lgtm:
:lgtm:

> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6037#-:-O24y0LQ8DMb820R21Tw:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
