### PR TITLE
Forbade #[inline(always)] for function with impl generic parameters

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2429)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2429#-NQ5jh-X86ZspSyqvLrv:-NQ5jh-X86ZspSyqvLrw:bloon5x) ([raw file](https://github.com/starkware-libs/cairo/blob/1032ea74549f303f6b44afc23f5905965e2bbcdb/crates/cairo-lang-lowering/src/inline/mod.rs#L33)):*
> ```XML
> #[derive(Debug, PartialEq, Eq)]
> pub struct InlineInfo {
>     /// Indicates that the function can be inlined with `#[inline(always)]`.
> ```

it can also be inlined without #[inline(always)].

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2429)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2429)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2429#-NQ5jh-X86ZspSyqvLrv:-NQ5mbO81yQtT5GHVOKf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1032ea74549f303f6b44afc23f5905965e2bbcdb/crates/cairo-lang-lowering/src/inline/mod.rs#L33)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it can also be inlined without #[inline(always)].
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2429#-:-NQ5mfHfB2BPnW2BEwbh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
