### PR TITLE
Added traits from impl aliases in the module, to the context

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4003)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 7 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4003)* status: 7 of 9 files reviewed, 4 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`Cargo.toml` line 5 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4003#-NdijPMIAX7rc3QQ_Bvp:-NdijPMIAX7rc3QQ_Bvq:b2wqon9) ([raw file](https://github.com/starkware-libs/cairo/blob/ab3a36d3e1c1ac3caa10fb1296af28b40cd412f9/Cargo.toml#L5)):*
> ```TOML
> 
> [workspace]
> resolver = "1"
> ```

is this related?
___
*[`crates/cairo-lang-semantic/src/expr/inference/solver.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4003#-NdijcYGEs5rYD92hOht:-NdijcYGEs5rYD92hOhu:b-2pfjt5) ([raw file](https://github.com/starkware-libs/cairo/blob/ab3a36d3e1c1ac3caa10fb1296af28b40cd412f9/crates/cairo-lang-semantic/src/expr/inference/solver.rs#L143)):*
> ```XML
>             };
>             if let Some(unique_solution) = unique_solution {
>                 if unique_solution.0 != candidate_solution.0 {
> ```

why is this required?
___
*[`crates/cairo-lang-semantic/src/expr/test_data/method` line 206 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4003#-Ndiklr15hNNrpNn6c8L:-Ndiklr15hNNrpNn6c8M:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/ab3a36d3e1c1ac3caa10fb1296af28b40cd412f9/crates/cairo-lang-semantic/src/expr/test_data/method#L206)):*
> ```
> //! > function
> fn foo() {
>     // TODO(yg): change back to u8.
> ```

?
___
*[`crates/cairo-lang-semantic/src/expr/test_data/method` line 231 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4003#-NdikoxCCYlzPdsjGDBr:-NdikoxCCYlzPdsjGDBs:b-myfd29) ([raw file](https://github.com/starkware-libs/cairo/blob/ab3a36d3e1c1ac3caa10fb1296af28b40cd412f9/crates/cairo-lang-semantic/src/expr/test_data/method#L231)):*
> ```
> //! > ==========================================================================
> 
> //! > Test calling a method of a trait from an impl alias in the module that is not the relevant impl.
> ```

rephrase to shorter than 100

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4003)* status: 7 of 9 files reviewed, 4 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`Cargo.toml` line 5 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4003#-NdijPMIAX7rc3QQ_Bvp:-Ndiwwg-3ogfRqlmZEAj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ab3a36d3e1c1ac3caa10fb1296af28b40cd412f9/Cargo.toml#L5)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is this related?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/inference/solver.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4003#-NdijcYGEs5rYD92hOht:-NdivgHdBauMcVBOQQaj:b-3m3npg) ([raw file](https://github.com/starkware-libs/cairo/blob/ab3a36d3e1c1ac3caa10fb1296af28b40cd412f9/crates/cairo-lang-semantic/src/expr/inference/solver.rs#L143)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why is this required?
</blockquote></details>

This was a bug, this PR triggered it.
It announced an ambiguity between an impl and itself.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/method` line 206 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4003#-Ndiklr15hNNrpNn6c8L:-Ndiw_jP3nR54zPX4Z55:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ab3a36d3e1c1ac3caa10fb1296af28b40cd412f9/crates/cairo-lang-semantic/src/expr/test_data/method#L206)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/method` line 231 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4003#-NdikoxCCYlzPdsjGDBr:-NdiwiIs0DS-Yw_Cqd2l:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ab3a36d3e1c1ac3caa10fb1296af28b40cd412f9/crates/cairo-lang-semantic/src/expr/test_data/method#L231)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rephrase to shorter than 100
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4003)* status: 6 of 9 files reviewed, 4 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/expr/inference/solver.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4003#-NdijcYGEs5rYD92hOht:-NdjYW8mBGeVDIZTGI24:bp05my1) ([raw file](https://github.com/starkware-libs/cairo/blob/ab3a36d3e1c1ac3caa10fb1296af28b40cd412f9/crates/cairo-lang-semantic/src/expr/inference/solver.rs#L143)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

This was a bug, this PR triggered it.
It announced an ambiguity between an impl and itself.
</blockquote></details>

can you add a comment about how this is triggered and why it is required?

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4003)* status: 4 of 9 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference/solver.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4003#-NdijcYGEs5rYD92hOht:-NdkEJzk1b6KHmQnbRUt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ab3a36d3e1c1ac3caa10fb1296af28b40cd412f9/crates/cairo-lang-semantic/src/expr/inference/solver.rs#L143)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can you add a comment about how this is triggered and why it is required?
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4003#-:-NdkXI3c4XFVnYrXlnlb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 18 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4003)* status: 12 of 26 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-defs/Cargo.toml` line 15 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4003#-NdoFZq_5JpYn8tO9Aof:-NdoFZq_5JpYn8tO9Aog:bwa9rc0) ([raw file](https://github.com/starkware-libs/cairo/blob/5e1810c020088e48694044cebf0b720c2708a8a4/crates/cairo-lang-defs/Cargo.toml#L15)):*
> ```TOML
> cairo-lang-parser = { path = "../cairo-lang-parser", version = "2.2.0" }
> cairo-lang-syntax = { path = "../cairo-lang-syntax", version = "2.2.0" }
> cairo-lang-test-utils = { path = "../cairo-lang-test-utils", features = ["testing"] }
> ```

this still requires version in non-dev dep.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4003)* status: 7 of 26 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-defs/Cargo.toml` line 15 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4003#-NdoFZq_5JpYn8tO9Aof:-NdzQ6qY80__klrIAJsd:bp3aow6) ([raw file](https://github.com/starkware-libs/cairo/blob/5e1810c020088e48694044cebf0b720c2708a8a4/crates/cairo-lang-defs/Cargo.toml#L15)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this still requires version in non-dev dep.
</blockquote></details>

Reverted.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 11 of 12 files at r5, 3 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4003)* status: 21 of 26 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-semantic/Cargo.toml` line 22 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4003#-NdzRKmAAKNLwZkOIUv5:-NdzRKmAAKNLwZkOIUv6:b-3qswcy) ([raw file](https://github.com/starkware-libs/cairo/blob/5e21e0512a66b25648e28375e1535c68db16d0f7/crates/cairo-lang-semantic/Cargo.toml#L22)):*
> ```TOML
> cairo-lang-syntax = { path = "../cairo-lang-syntax", version = "2.2.0" }
> cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.2.0" }
> cairo-lang-test-utils = { path = "../cairo-lang-test-utils", optional = true, features = ["testing"] }
> ```

does this prevent dependencies with no features?
otherwise we must use a version, as this would break the release process.

**Pull request merged**
