### PR TITLE
Small changes

### PR DESCRIPTION
**Pull request by liorgold2**
**Stack**:
- #4821
- #4820 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4820)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4820)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 430 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4820#-NoHkNk05ZHp6B0mvhkQ:-NoHkNk05ZHp6B0mvhkR:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8e1610131f61f62a4f191694c4accda4fd1be6b6/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L430)):*
> ```XML
>         Const(libfunc) => match libfunc {
>             // TODO(orizi): Fix.
>             ConstConcreteLibfunc::AsBox(_) => vec![ConstCost::default().into()],
> ```





_Suggestion:_
```XML
        Const(libfunc) => match libfunc {
            ConstConcreteLibfunc::AsBox(_) => vec![ConstCost::steps(3).into()],
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4820)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 430 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4820#-NoHkNk05ZHp6B0mvhkQ:-NoRCdTO2nl-8X6OumRa:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8e1610131f61f62a4f191694c4accda4fd1be6b6/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L430)):*
> ```XML
>         Const(libfunc) => match libfunc {
>             // TODO(orizi): Fix.
>             ConstConcreteLibfunc::AsBox(_) => vec![ConstCost::default().into()],
> ```

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4820)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4820#-:-NoREr4r1t9LFNhhMH4j:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
