### PR TITLE
Reduced runtime of examples tests by using fixtures.

### PR DESCRIPTION
**Pull request by orizi**
Runtime now is ~10 seconds.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2349)

### CODE REVIEW

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 19 of 21 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2349)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`tests/examples_test.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2349#-NPkr-B36pa88EhT0-U9:-NPkr-B36pa88EhT0-UA:b-xhf0v5) ([raw file](https://github.com/starkware-libs/cairo/blob/eb00c6ca0b3f133ed9b312d9811753f5c18dbbdd/tests/examples_test.rs#L51)):*
> ```XML
> }
> 
> /// Compiles the Cairo code for `name` to a Sierra program.
> ```

Maybe mention that it's the code of `examples::main` and nothing else.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2349#-:-NPksdLP9R0-DCnZPFgx:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2349)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

___
*[`tests/examples_test.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2349#-NPkr-B36pa88EhT0-U9:-NPkuK6g5JWNCjp7gCIa:b-nlf0hx) ([raw file](https://github.com/starkware-libs/cairo/blob/eb00c6ca0b3f133ed9b312d9811753f5c18dbbdd/tests/examples_test.rs#L51)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Maybe mention that it's the code of `examples::main` and nothing else.
</blockquote></details>

rephrased.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 19 of 21 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2349#-:-NPkvbww59s-2QRMpHGy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
