### PR TITLE
nullable: Add e2e test for multiple libfuncs.

### PR DESCRIPTION
**Pull request by liorgold2**
commit-id:50189608

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1459#-:-NK4l63HAQJHcow6c1Nk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1459)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1459)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1459)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1459)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
