### PR TITLE
LS: fix diagnostics' panics

### PR DESCRIPTION
**Pull request by piotmag769**

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6529)* status: 1 of 8 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-defs/src/db.rs` line 599 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6529#-OAJOjNy496eOV7qVoXF:-OAJOjNy496eOV7qVoXG:b2wbjyo) ([raw file](https://github.com/starkware-libs/cairo/blob/3002dab967481684a58241b1105d42cc60ac309f/crates/cairo-lang-defs/src/db.rs#L599)):*
> ```XML
>         .unwrap();
>     data.files.get(&file_id).cloned()
> }
> ```

implement the above function using this function.

have a default implementation for the non-maybe version.



_Code quote:_
```XML
/// Returns the `VirtualFile` matching the given external id.
pub fn maybe_ext_as_virtual_impl(
    db: &dyn DefsGroup,
    external_id: salsa::InternId,
) -> Option<VirtualFile> {
    let long_id = PluginGeneratedFileId::from_intern_id(external_id).lookup_intern(db);
    let file_id = FileLongId::External(external_id).intern(db);
    let data = db
        .priv_module_sub_files(long_id.module_id, long_id.stable_ptr.file_id(db.upcast()))
        .unwrap();
    data.files.get(&file_id).cloned()
}
```
___
*[`crates/cairo-lang-filesystem/src/db.rs` line 171 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6529#-OAJOsOKDbyTaLUxTZl4:-OAJOsOKDbyTaLUxTZl5:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/3002dab967481684a58241b1105d42cc60ac309f/crates/cairo-lang-filesystem/src/db.rs#L171)):*
> ```XML
>     fn maybe_ext_as_virtual(&self, _external_id: salsa::InternId) -> Option<VirtualFile> {
>         panic!("Should not be called, unless specifically implemented!");
>     }
> ```





_Suggestion:_
```XML
    fn ext_as_virtual(&self, external_id: salsa::InternId) -> VirtualFile {
        self.maybe_ext_as_virtual(external_id).unwrap()
    }

    /// Returns the virtual file matching the external id if found.
    fn maybe_ext_as_virtual(&self, _external_id: salsa::InternId) -> Option<VirtualFile> {
        panic!("Should not be called, unless specifically implemented!");
    }
```

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6529)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

___
*[`crates/cairo-lang-defs/src/db.rs` line 599 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6529#-OAJOjNy496eOV7qVoXF:-OAJZIc3-W3-UQN-OuYP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3002dab967481684a58241b1105d42cc60ac309f/crates/cairo-lang-defs/src/db.rs#L599)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

implement the above function using this function.

have a default implementation for the non-maybe version.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-filesystem/src/db.rs` line 171 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6529#-OAJOsOKDbyTaLUxTZl4:-OAJYxsPBj0LvufpnJB3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3002dab967481684a58241b1105d42cc60ac309f/crates/cairo-lang-filesystem/src/db.rs#L171)):*
> ```XML
>     fn maybe_ext_as_virtual(&self, _external_id: salsa::InternId) -> Option<VirtualFile> {
>         panic!("Should not be called, unless specifically implemented!");
>     }
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6529)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-defs/src/db.rs` line 579 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6529#-OAJa9Ur2qcn-OA4aT_o:-OAJa9Ur2qcn-OA4aT_p:b-2ef7u0) ([raw file](https://github.com/starkware-libs/cairo/blob/6dea1e72b105c273052c75a816469036e260ebef/crates/cairo-lang-defs/src/db.rs#L579)):*
> ```XML
> 
> /// Returns the `VirtualFile` matching the given external id.
> pub fn ext_as_virtual_impl(db: &dyn DefsGroup, external_id: salsa::InternId) -> VirtualFile {
> ```

You can probably just drop this function.
___
*[`crates/cairo-lang-language-server/src/lang/db/mod.rs` line 92 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6529#-OAJaLL15e_tFQ6dRu59:-OAJaLL15e_tFQ6dRu5A:byb7qgt) ([raw file](https://github.com/starkware-libs/cairo/blob/6dea1e72b105c273052c75a816469036e260ebef/crates/cairo-lang-language-server/src/lang/db/mod.rs#L92)):*
> ```XML
> impl salsa::Database for AnalysisDatabase {}
> impl ExternalFiles for AnalysisDatabase {
>     fn ext_as_virtual(&self, external_id: salsa::InternId) -> VirtualFile {
> ```

This already has a default implementation now.

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6529)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-defs/src/db.rs` line 579 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6529#-OAJa9Ur2qcn-OA4aT_o:-OAMMJ8W3Ei51snaAcm4:b-4cklh8) ([raw file](https://github.com/starkware-libs/cairo/blob/6dea1e72b105c273052c75a816469036e260ebef/crates/cairo-lang-defs/src/db.rs#L579)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

You can probably just drop this function.
</blockquote></details>

agree, I see some cases when this unwrap could be entirely avoided, and the less unwraps and the more deferred they are we have the easier they'll be to manage and reason about
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/lsp.rs` line 38 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6529#-OAMMsIaE-hrJDzmBIHY:-OAMMsIb7ZHRSrUtaJcM:bz7a5ou) ([raw file](https://github.com/starkware-libs/cairo/blob/6dea1e72b105c273052c75a816469036e260ebef/crates/cairo-lang-language-server/src/lang/diagnostics/lsp.rs#L38)):*
> ```XML
>                 };
>                 let Some(uri) = db.url_for_file(file_id) else {
>                     trace!("url for file {:?} not found", file_id.lookup_intern(db));
> ```

will be easier to grep



_Suggestion:_
```XML
trace!("url for file not found: {:?}", file_id.lookup_intern(db));
```
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/refresh.rs` line 127 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6529#-OAMMyxxCBGbEs2NU554:-OAMMyxxCBGbEs2NU555:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6dea1e72b105c273052c75a816469036e260ebef/crates/cairo-lang-language-server/src/lang/diagnostics/refresh.rs#L127)):*
> ```XML
> ) {
>     let Some(file_uri) = db.url_for_file(*file) else {
>         trace!("url for file {:?} not found", file.lookup_intern(db));
> ```





_Suggestion:_
```XML
trace!("url for file not found: {:?}", file.lookup_intern(db));
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6529)* status: all files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, and @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6529#-OANXWVY4NFug8801SFe:-OANXWVZDN3Ht_B8-5mZ:bl9bj1u) (no related file):*
consider using `try_` instead of `maybe_` as this seems to be what we mostly do in the repo.

___

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6529)* status: all files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6529#-OANXWVY4NFug8801SFe:-OANYlW7AiD3FNxE4Wey:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

consider using `try_` instead of `maybe_` as this seems to be what we mostly do in the repo.
</blockquote></details>

Done.

___
___
*[`crates/cairo-lang-defs/src/db.rs` line 579 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6529#-OAJa9Ur2qcn-OA4aT_o:-OANYu2S3M3qUMyAx_rv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6dea1e72b105c273052c75a816469036e260ebef/crates/cairo-lang-defs/src/db.rs#L579)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

agree, I see some cases when this unwrap could be entirely avoided, and the less unwraps and the more deferred they are we have the easier they'll be to manage and reason about
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lang/db/mod.rs` line 92 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6529#-OAJaLL15e_tFQ6dRu59:-OANYuqa8LtOEvU6Uj5f:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6dea1e72b105c273052c75a816469036e260ebef/crates/cairo-lang-language-server/src/lang/db/mod.rs#L92)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

This already has a default implementation now.
</blockquote></details>

Done.

**Review by mkaput — COMMENTED** [review]
> Reviewed 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6529)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 8 files at r1, 4 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6529#-:-OAN_rNW3R6oHMXxev__:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, and @piotmag769)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6529)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, and @piotmag769)

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6529#-:-OANaQgo7wPQEa86q3L5:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)

**Pull request merged**
