### PR TITLE
feat(corelib): range is_empty

### PR DESCRIPTION
**Pull request by julio4**
Add `core::ops::RangeTrait` with:

`fn is_empty(self: @Range<T>) -> bool`

Returns `true` if the range contains no items.

#### Examples

```cairo
assert!(!(3_u8..5_u8).is_empty());
assert!( (3_u8..3_u8).is_empty());
assert!( (3_u8..2_u8).is_empty());
```

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6925#-:-OEz2lIG1oUNxZYysddr:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @julio4)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6925#-OEz2mKsCs_RnlpE6tjh:-OEz2mKsCs_RnlpE6tji:b-uuj1x0) (no related file):*
@gilbens-starkware for 2nd eye.

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6925)* status: all files reviewed, 1 unresolved discussion (waiting on @julio4)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6925#-:-OF10I1hERgD0IaKmpBw:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @julio4)

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6925)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @julio4)

**Pull request merged**
