### PR TITLE
Add diagnostics to plugin test.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1329)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1329)* status: all files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/diagnostics/src/diagnostics.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1329#-NJFupK71tKvgoAux-Y9:-NJFupK71tKvgoAux-YA:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/ba5e00ded9548683884384339d06fc496c565afb/crates/diagnostics/src/diagnostics.rs#L60)):*
> ```XML
>     location: DiagnosticLocation,
> ) -> String {
>     let location = location;
> ```

?



_Code quote:_
```XML
 let location = location;
```
___
*[`crates/diagnostics/src/diagnostics.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1329#-NJFvg3lB7q1i4TPNQ11:-NJFvg3lB7q1i4TPNQ12:b-jatftt) ([raw file](https://github.com/starkware-libs/cairo/blob/ba5e00ded9548683884384339d06fc496c565afb/crates/diagnostics/src/diagnostics.rs#L61)):*
> ```XML
> ) -> String {
>     let location = location;
>     let filename = location.file_id.file_name(db.upcast());
> ```

Are you sure you need those upcasts if the param is of type FilesGroup?



_Code quote:_
```XML
db.upcast()
```
___
*[`crates/diagnostics/src/diagnostics.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1329#-NJFvvdmCvBC54K6Kk-x:-NJFvvdmCvBC54K6Kk-y:behqh7v) ([raw file](https://github.com/starkware-libs/cairo/blob/ba5e00ded9548683884384339d06fc496c565afb/crates/diagnostics/src/diagnostics.rs#L84)):*
> ```XML
>             let message = entry.format(db);
>             res += &format_diagnostics(db.upcast(), &message, entry.location(db));
>             res += "\n";
> ```

Isn't this redundant with the \n in the end of format_diagnostics?
If the double \n is needed, why not write is twice in format_diagnostics?



_Code quote:_
```XML
res += "\n";
```
___
*[`crates/starknet/src/plugin.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1329#-NJFxFjC7mT_eIVbd_zB:-NJFxFjC7mT_eIVbd_zC:b-neipn3) ([raw file](https://github.com/starkware-libs/cairo/blob/ba5e00ded9548683884384339d06fc496c565afb/crates/starknet/src/plugin.rs#L36)):*
> ```XML
> }
> 
> /// If the struct is annotated with CONTRACT_ATTR, generate getter functions for
> ```

module



_Code quote:_
```XML
struct
```
___
*[`crates/starknet/src/plugin_test.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1329#-NJFzr8F73gnbm6g_hXO:-NJFzr8F73gnbm6g_hXP:bgcohbr) ([raw file](https://github.com/starkware-libs/cairo/blob/ba5e00ded9548683884384339d06fc496c565afb/crates/starknet/src/plugin_test.rs#L30)):*
> ```XML
>             let syntax_node = db
>                 .file_syntax(file_id)
>                 .expect("File for diagnostic not found")
> ```

Can you please do this once, right after creating the file?



_Code quote:_
```XML
            let syntax_node = db
                .file_syntax(file_id)
                .expect("File for diagnostic not found")
                .as_syntax_node()
```
___
*[`crates/starknet/src/plugin_test.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1329#-NJG-8AV0YY1WrxHbTRu:-NJG-8AV0YY1WrxHbTRv:b-h2se3t) ([raw file](https://github.com/starkware-libs/cairo/blob/ba5e00ded9548683884384339d06fc496c565afb/crates/starknet/src/plugin_test.rs#L52)):*
> ```XML
> }
> 
> parser_test!(test1, ["src/plugin_test_data/starknet",], test_expand_contract);
> ```

Consider renaming to test_valid_expansion and test_diagnostics or similar.



_Code quote:_
```XML
parser_test!(test1, ["src/plugin_test_data/starknet",], test_expand_contract);
parser_test!(test2, ["src/plugin_test_data/diagnostics",], test_expand_contract);
```
___
*[`crates/starknet/src/plugin_test_data/diagnostics` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1329#-NJG-YFh8FEyAvBnJDbe:-NJG-YFh8FEyAvBnJDbf:b-s8vk0b) ([raw file](https://github.com/starkware-libs/cairo/blob/ba5e00ded9548683884384339d06fc496c565afb/crates/starknet/src/plugin_test_data/diagnostics#L1)):*
> ```
> //! > Test expansion of a simple starknet contract.
> ```

change



_Code quote:_
```
Test expansion of a simple starknet contract.
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1329)* status: all files reviewed, 6 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/diagnostics/src/diagnostics.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1329#-NJFupK71tKvgoAux-Y9:-NJG2Vuq29Bayp6P_KbW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ba5e00ded9548683884384339d06fc496c565afb/crates/diagnostics/src/diagnostics.rs#L60)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`crates/diagnostics/src/diagnostics.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1329#-NJFvvdmCvBC54K6Kk-x:-NJG2ZVw0tesqHjdI0zQ:b-js4jyj) ([raw file](https://github.com/starkware-libs/cairo/blob/ba5e00ded9548683884384339d06fc496c565afb/crates/diagnostics/src/diagnostics.rs#L84)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Isn't this redundant with the \n in the end of format_diagnostics?
If the double \n is needed, why not write is twice in format_diagnostics?
</blockquote></details>

I've added to be consistent with the current format.

do you think format_diagnostics should be followed by an empty line?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1329)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/starknet/src/plugin.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1329#-NJFxFjC7mT_eIVbd_zB:-NJG374v3Vh13vGeJs5a:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/ba5e00ded9548683884384339d06fc496c565afb/crates/starknet/src/plugin.rs#L36)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

module
</blockquote></details>

done
___
*[`crates/starknet/src/plugin_test.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1329#-NJFzr8F73gnbm6g_hXO:-NJG3swgClD1ygRfY0Pl:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/ba5e00ded9548683884384339d06fc496c565afb/crates/starknet/src/plugin_test.rs#L30)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Can you please do this once, right after creating the file?
</blockquote></details>

done
___
*[`crates/starknet/src/plugin_test.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1329#-NJG-8AV0YY1WrxHbTRu:-NJG3fJfD9iL2a11PIfw:bwfqeli) ([raw file](https://github.com/starkware-libs/cairo/blob/ba5e00ded9548683884384339d06fc496c565afb/crates/starknet/src/plugin_test.rs#L52)):*
> test_diagnostics
done
___
*[`crates/starknet/src/plugin_test_data/diagnostics` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1329#-NJG-YFh8FEyAvBnJDbe:-NJG3rfB1vDKMM7qK4hR:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/ba5e00ded9548683884384339d06fc496c565afb/crates/starknet/src/plugin_test_data/diagnostics#L1)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

change
</blockquote></details>

done.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1329)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/diagnostics/src/diagnostics.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1329#-NJFvg3lB7q1i4TPNQ11:-NJGSklh89_0qsuqXLkE:bo6f7ku) ([raw file](https://github.com/starkware-libs/cairo/blob/ba5e00ded9548683884384339d06fc496c565afb/crates/diagnostics/src/diagnostics.rs#L61)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Are you sure you need those upcasts if the param is of type FilesGroup?
</blockquote></details>

there are 2 more.



_Code quote:_
```XML
file_name
```
___
*[`crates/diagnostics/src/diagnostics.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1329#-NJFvvdmCvBC54K6Kk-x:-NJGSv6o7dXxjEo1A8ep:b-ph7fcw) ([raw file](https://github.com/starkware-libs/cairo/blob/ba5e00ded9548683884384339d06fc496c565afb/crates/diagnostics/src/diagnostics.rs#L84)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I've added to be consistent with the current format.

do you think format_diagnostics should be followed by an empty line?
</blockquote></details>

If after any diagnostic you add a \n anyway, why not do it in the format of the diagnostic itself?
___
*[`crates/starknet/src/plugin_test.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1329#-NJFzr8F73gnbm6g_hXO:-NJGTQb3DWR3maPeiwKx:bosmy42) ([raw file](https://github.com/starkware-libs/cairo/blob/ba5e00ded9548683884384339d06fc496c565afb/crates/starknet/src/plugin_test.rs#L30)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

done
</blockquote></details>

I meant to call the lookup only once, outside of the for loop.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1329)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/starknet/src/plugin_test.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1329#-NJFzr8F73gnbm6g_hXO:-NJGsRNnAmtvQqI_cC_1:b3gheqq) ([raw file](https://github.com/starkware-libs/cairo/blob/ba5e00ded9548683884384339d06fc496c565afb/crates/starknet/src/plugin_test.rs#L30)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I meant to call the lookup only once, outside of the for loop.
</blockquote></details>

what lookup do you want to move? is different for each item.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1329)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/diagnostics/src/diagnostics.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1329#-NJFvvdmCvBC54K6Kk-x:-NJGsnqT5YmKBT3PW8hg:beubcxk) ([raw file](https://github.com/starkware-libs/cairo/blob/ba5e00ded9548683884384339d06fc496c565afb/crates/diagnostics/src/diagnostics.rs#L84)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

If after any diagnostic you add a \n anyway, why not do it in the format of the diagnostic itself?
</blockquote></details>

because than it would be format_diagnostics_and_append_new_line

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1329)* status: 4 of 8 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/diagnostics/src/diagnostics.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1329#-NJFvg3lB7q1i4TPNQ11:-NJJWwMS5DMdosQ_NPW0:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/ba5e00ded9548683884384339d06fc496c565afb/crates/diagnostics/src/diagnostics.rs#L61)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

there are 2 more.
</blockquote></details>

done.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1329#-:-NJJtsLF7H2ILOVWYy2h:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/starknet/src/plugin_test.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1329#-NJFzr8F73gnbm6g_hXO:-NJJtXzL9rAxNyh4dt4s:b-fochdc) ([raw file](https://github.com/starkware-libs/cairo/blob/ba5e00ded9548683884384339d06fc496c565afb/crates/starknet/src/plugin_test.rs#L30)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what lookup do you want to move? is different for each item.
</blockquote></details>

You are right. But the as_syntax_node() clones the node, so you can do this only once.



_Code quote:_
```XML
as_syntax_node
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1329)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`crates/diagnostics/src/diagnostics.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1329#-NJFvvdmCvBC54K6Kk-x:-NJJzV7zD4chV__UXVeK:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/ba5e00ded9548683884384339d06fc496c565afb/crates/diagnostics/src/diagnostics.rs#L84)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

because than it would be format_diagnostics_and_append_new_line
</blockquote></details>

done
___
*[`crates/starknet/src/plugin_test.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1329#-NJFzr8F73gnbm6g_hXO:-NJJzZBiD5UD_VcQH4gb:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/ba5e00ded9548683884384339d06fc496c565afb/crates/starknet/src/plugin_test.rs#L30)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

You are right. But the as_syntax_node() clones the node, so you can do this only once.
</blockquote></details>

done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 3 of 6 files at r2, 3 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1329)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
