### PR TITLE
Enum sub pointers.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6042)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6042)* status: 1 of 8 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`corelib/src/starknet/storage/sub_pointers.cairo` line 40 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6042#-O2RMOo3522a_iQsZoZs:-O2RMOo3522a_iQsZoZt:b-lw24iu) ([raw file](https://github.com/starkware-libs/cairo/blob/606f0ca623b9dd7ff79ff4572caeb29fd4615107/corelib/src/starknet/storage/sub_pointers.cairo#L40)):*
> ```Cairo
> 
> 
> pub trait SubPointersForward<T> {
> ```

doc all.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6042)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/starknet/storage/sub_pointers.cairo` line 40 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6042#-O2RMOo3522a_iQsZoZs:-O32o8PK3XNdSwM5FVjG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/606f0ca623b9dd7ff79ff4572caeb29fd4615107/corelib/src/starknet/storage/sub_pointers.cairo#L40)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc all.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6042)* status: 1 of 8 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin/storage_interfaces.rs` line 508 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6042#-O32qBhM33iVn_nMW8xc:-O32qBhM33iVn_nMW8xd:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/0383a9997321a280aab9b8acb4405a661ee80e38/crates/cairo-lang-starknet/src/plugin/storage_interfaces.rs#L508)):*
> ```XML
> }
> 
> pub fn handle_storage_interface_enum(
> ```

doc

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6042)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin/storage_interfaces_temp.rs` line 572 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6042#-O32qHFMDVzIbksla14F:-O32qHFMDVzIbksla14G:bq6jfw4) ([raw file](https://github.com/starkware-libs/cairo/blob/0383a9997321a280aab9b8acb4405a661ee80e38/crates/cairo-lang-starknet/src/plugin/storage_interfaces_temp.rs#L572)):*
> ```XML
> ///            }
> ///       }
> ///   }
> ```

should this doc be here?



_Code quote:_
```XML
/// How it should look like:
///
/// user defined enum:
/// #[derive(starknet::Store)]
/// enum MyEnum {
///     A: u32,
///     B: u64,
/// }
///
/// generated code:
/// enum MyEnumSubPointers {
///    A: StoragePointer<u32>,
///    B: StoragePointer<u64>,
/// }
///
/// impl MyEnumSubPointers of SubPointers<MyEnum> {
///    type SubPointersType = MyEnumSubPointers;
///    fn sub_pointers(self: StoragePointer<MyEnum>) -> MyEnumSubPointers {
///        let selector_storage_pointer: StoragePointer<felt252> = self.into();
///        let selector = selector_storage_pointer.read();
///         match selector {
///            "0" => MyEnumSubPointers::A(starknet::storage::StoragePointer {
///               address: self.address,
///               offset: self.offset + 1,
///             }
///           "1" => MyEnumSubPointers::B(starknet::storage::StoragePointer {
///              address: self.address,
///              offset: self.offset + 1,
///            }
///       }
///   }
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6042)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/storage_interfaces.rs` line 508 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6042#-O32qBhM33iVn_nMW8xc:-O32uCCw9xM_L_nEE8vj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0383a9997321a280aab9b8acb4405a661ee80e38/crates/cairo-lang-starknet/src/plugin/storage_interfaces.rs#L508)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/storage_interfaces_temp.rs` line 572 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6042#-O32qHFMDVzIbksla14F:-O32v0ubCzwJqRtXvHkL:bvvdh2j) ([raw file](https://github.com/starkware-libs/cairo/blob/0383a9997321a280aab9b8acb4405a661ee80e38/crates/cairo-lang-starknet/src/plugin/storage_interfaces_temp.rs#L572)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

should this doc be here?
</blockquote></details>

No this whole file sneak in in a rebase, deleted.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 6 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6042#-:-O334FCuE4phfXb3SYsf:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
