### PR TITLE
Refactor return optimization.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5148)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5148)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/return_optimization.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5148#-Nr_RJz0D0MiqDrM5N5_:-Nr_RJz0D0MiqDrM5N5a:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/8713489505cfaa1b752252664d1f956831404e81/crates/cairo-lang-lowering/src/optimizations/return_optimization.rs#L67)):*
> ```XML
>     }
> 
>     fn try_merge_match(
> ```

doc

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5148)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/return_optimization.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5148#-Nr_RJz0D0MiqDrM5N5_:-Nr_TJiN9g2b-y6TVAQ0:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8713489505cfaa1b752252664d1f956831404e81/crates/cairo-lang-lowering/src/optimizations/return_optimization.rs#L67)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5148)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/return_optimization.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5148#-Nr_UQ-2-uBAmntx4fFn:-Nr_VAn5BvXA9CObsYp8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/19d8e01c2a96898cc09160a61e81eb6dd24151d3/crates/cairo-lang-lowering/src/optimizations/return_optimization.rs#L69)):*
> ```XML
> 
>     /// Helper function for `merge_match`.
>     /// Retruns `Option<ReturnInfo>` rather then `AnalyzerInfo` to simplify early return.
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5148#-:-Nr_Vq9FD02rPwBx6xJY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5148)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5148)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
