### PR TITLE
Added const-folding `*_eq` with 0 into `*_iz_zero`.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6454)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 1 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6454)* status: 1 of 20 files reviewed, all discussions resolved

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6454)* status: 1 of 20 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/const_folding.rs` line 734 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6454#-O8WD8rfBeNSgEih7Sku:-O8WD8rfBeNSgEih7Skv:b-lycg0o) ([raw file](https://github.com/starkware-libs/cairo/blob/c9983248cbf59c0c05fa0fb14395379b3b4d8b02/crates/cairo-lang-lowering/src/optimizations/const_folding.rs#L734)):*
> ```XML
> }
> 
> /// The range of a type for normalizations.
> ```

Fix doc



_Code quote:_
```XML
/// The range of a type for normalizations.
```

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6454#-:-O8WDkff-K8E9BhvcHgi:bnfp4nl)* status: 1 of 20 files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6454)* status: 1 of 21 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/const_folding.rs` line 734 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6454#-O8WD8rfBeNSgEih7Sku:-O8WncXS0ayNQIGmuBPw:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f21a2469f655a3f7a3d124c6ff0cd6ecf102a782/crates/cairo-lang-lowering/src/optimizations/const_folding.rs#L734)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Fix doc
</blockquote></details>

Done.

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 9 of 20 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6454)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
