### PR TITLE
Added basic doc for testing module.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #6054
- #6053
- #6052
- #6048
- #6047 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6047)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/testing.cairo` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6047#-O2UABdbCD7ELR2r0JL_:-O2UABdbCD7ELR2r0JLa:b-204s7h) ([raw file](https://github.com/starkware-libs/cairo/blob/24777af5f6ecb1888b81f7440653486bae3b95ef/corelib/src/testing.cairo#L3)):*
> ```Cairo
> use core::gas::GasBuiltin;
> 
> /// Returns the amount of gas available for the current execution.
> ```

Doesn't the
"gas available for the current execution" include the gas wallet?



_Code quote:_
```Cairo
/// Returns the amount of gas available for the current execution.
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6047)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/testing.cairo` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6047#-O2UABdbCD7ELR2r0JL_:-O2UBY3pAg8iicR8r36V:b-8raul9) ([raw file](https://github.com/starkware-libs/cairo/blob/24777af5f6ecb1888b81f7440653486bae3b95ef/corelib/src/testing.cairo#L3)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Doesn't the
"gas available for the current execution" include the gas wallet?
</blockquote></details>

no - only the global wallet - not the compiler wallet.

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/testing.cairo` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6047#-O2UABdbCD7ELR2r0JL_:-O2UBkiNBuPtZ1DThNsV:bqhoq28) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2708aae23d972af9c4c21702565cd2671559d0/corelib/src/testing.cairo#L3)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no - only the global wallet - not the compiler wallet.
</blockquote></details>

Why is the compiler wallet not available for execution?

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/testing.cairo` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6047#-O2UC3Ry0EsWlagvJnqN:-O2UC3Rz3d1Tqn1tduA0:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2708aae23d972af9c4c21702565cd2671559d0/corelib/src/testing.cairo#L3)):*
> ```Cairo
> use core::gas::GasBuiltin;
> 
> /// Returns the amount of gas available for the current execution.
> ```





_Suggestion:_
```Cairo
// Returns the amount of gas available in the GasBuiltin.
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6047)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/testing.cairo` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6047#-O2UABdbCD7ELR2r0JL_:-O2UFBZ3C7qka8qpYAdy:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2708aae23d972af9c4c21702565cd2671559d0/corelib/src/testing.cairo#L3)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why is the compiler wallet not available for execution?
</blockquote></details>

Done.
___
*[`corelib/src/testing.cairo` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6047#-O2UC3Ry0EsWlagvJnqN:-O2UFBsh9--JOTnksjCl:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2708aae23d972af9c4c21702565cd2671559d0/corelib/src/testing.cairo#L3)):*
> ```Cairo
> use core::gas::GasBuiltin;
> 
> /// Returns the amount of gas available for the current execution.
> ```

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/testing.cairo` line 14 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6047#-O2USkf-7ErA4BLXEhVY:-O2USkf-7ErA4BLXEhVZ:b-hg3vua) ([raw file](https://github.com/starkware-libs/cairo/blob/4dfd6000c1bf64dcad29f720c39c77adf1e60342/corelib/src/testing.cairo#L14)):*
> ```Cairo
> /// // Calling the function that consumes gas.
> /// // GasBuiltin will be reduced by the `gas_heavy_function` dynamic price (i.e. internal Calls
> /// // to `withdraw_gas`).
> ```

Why does it matter if gas_heavy_function uses withdraw_gas internally? 



_Code quote:_
```Cairo
/// // GasBuiltin will be reduced by the `gas_heavy_function` dynamic price (i.e. internal Calls
/// // to `withdraw_gas`).
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6047)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/testing.cairo` line 14 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6047#-O2USkf-7ErA4BLXEhVY:-O2UTG4207SWVQkPAMSF:b4hi2mc) ([raw file](https://github.com/starkware-libs/cairo/blob/4dfd6000c1bf64dcad29f720c39c77adf1e60342/corelib/src/testing.cairo#L14)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why does it matter if gas_heavy_function uses withdraw_gas internally?
</blockquote></details>

This is the only dynamic pricing that may exist.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6047#-:-O2Ujv0k1z5hWGYIN81G:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
