### PR TITLE
Add dict read/write to the hint processor.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1686)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1686)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1686#-NLG8XSzAc_WgBIFDqsf:-NLG8XSzAc_WgBIFDqsg:bt1obvg) (no related file):*
TODO: change target branch.

___

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1686#-:-NLGGV7E3oBE2XfMPZ15:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`corelib/test.cairo` line 366 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1686#-NLGG4v5-_B3LTcY1sfw:-NLGG4v61oFMTFWoZ7cF:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2239897c1928e01bfadc7a70c3ef0364f2ffef2f/corelib/test.cairo#L366)):*
> ```Cairo
> fn test_dict_default_val() {
>     let mut dict = dict_felt_to_new::<felt>();
>     let default_val = dict_felt_to_read::<felt>(dict, 0);
> ```





_Suggestion:_
```Cairo
#[test]
fn test_dict_default_val() {
    let mut dict = dict_felt_to_new::<felt>();
    assert(dict_felt_to_read::<felt>(dict, 0) == 0, 'default_val == 0');
}
```
___
*[`corelib/test.cairo` line 377 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1686#-NLGG9hkEqTKnhT9hjtr:-NLGG9hkEqTKnhT9hjts:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2239897c1928e01bfadc7a70c3ef0364f2ffef2f/corelib/test.cairo#L377)):*
> ```Cairo
>     let val10 = dict_felt_to_read::<felt>(dict, 10);
>     let val11 = dict_felt_to_read::<felt>(dict, 11);
>     let val12 = dict_felt_to_read::<felt>(dict, 12);
> ```





_Suggestion:_
```Cairo
    let mut dict = dict_felt_to_new::<felt>();
    dict_felt_to_write::<felt>(dict, 10, 110);
    dict_felt_to_write::<felt>(dict, 11, 111);
    assert(dict_felt_to_read::<felt>(dict, 10) == 110, 'dict[10] == 110');
    assert(dict_felt_to_read::<felt>(dict, 11) == 111, 'dict[11] == 111');
    assert(dict_felt_to_read::<felt>(dict, 12) == 0, 'default_val == 0');
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1686)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`corelib/test.cairo` line 366 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1686#-NLGG4v5-_B3LTcY1sfw:-NLGP_NBBtIFpxo4b8Oo:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2239897c1928e01bfadc7a70c3ef0364f2ffef2f/corelib/test.cairo#L366)):*
> ```Cairo
> fn test_dict_default_val() {
>     let mut dict = dict_felt_to_new::<felt>();
>     let default_val = dict_felt_to_read::<felt>(dict, 0);
> ```

Done.
___
*[`corelib/test.cairo` line 377 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1686#-NLGG9hkEqTKnhT9hjtr:-NLGP_jV9qCdJ4F83tC0:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2239897c1928e01bfadc7a70c3ef0364f2ffef2f/corelib/test.cairo#L377)):*
> ```Cairo
>     let val10 = dict_felt_to_read::<felt>(dict, 10);
>     let val11 = dict_felt_to_read::<felt>(dict, 11);
>     let val12 = dict_felt_to_read::<felt>(dict, 12);
> ```

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1686)* status: all files reviewed, 1 unresolved discussion

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1686)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
