### PR TITLE
Add RootDatabase builder

### PR DESCRIPTION
**Pull request by maciektr**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1824)

### CODE REVIEW

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 39 of 39 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1824)* status: all files reviewed, 5 unresolved discussions (waiting on @maciektr)

___
*[`crates/cairo-lang-compiler/src/db.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1824#-NMDcLVTAh_zAlipmdjq:-NMDcLVTAh_zAlipmdjr:bu74ix4) ([raw file](https://github.com/starkware-libs/cairo/blob/2e61f75ab4ea2ac0dfc170cee7461c0aa02f872d/crates/cairo-lang-compiler/src/db.rs#L36)):*
> ```XML
> }
> impl salsa::Database for RootDatabase {}
> impl RootDatabase {
> ```

I think we might want to introduce a builder pattern here.

Docs: https://rust-unofficial.github.io/patterns/patterns/creational/builder.html

Though I would rather use non-consuming builders i.e. pass `&mut self` in the builder rather than `mut self` as in linked example. https://web.archive.org/web/20210104103100/https://doc.rust-lang.org/1.12.0/style/ownership/builders.html#non-consuming-builders-preferred
___
*[`crates/cairo-lang-compiler/src/db.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1824#-NMDd6LS6BGWeYNPD_yF:-NMDd6LS6BGWeYNPD_yG:b-2c3tyz) ([raw file](https://github.com/starkware-libs/cairo/blob/2e61f75ab4ea2ac0dfc170cee7461c0aa02f872d/crates/cairo-lang-compiler/src/db.rs#L47)):*
> ```XML
>     pub fn with_dev_corelib(plugins: Vec<Arc<dyn SemanticPlugin>>) -> Option<Self> {
>         let mut db = Self::new(plugins);
>         detect_corelib().map(|path| {
> ```

nitpick: I would rather use `if let Some(path) = detect_corelib()` syntax here. Mutating captured stuff from within functional combinators is not so clean and obvious
___
*[`crates/cairo-lang-compiler/src/db.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1824#-NMDct4cDKNpp3RdpFcR:-NMDct4cDKNpp3RdpFcS:b-8sals4) ([raw file](https://github.com/starkware-libs/cairo/blob/2e61f75ab4ea2ac0dfc170cee7461c0aa02f872d/crates/cairo-lang-compiler/src/db.rs#L55)):*
> ```XML
>     }
> 
>     pub fn with_project_config(
> ```

This is not interning all crate_roots from the project.

I think it might be epic to remove the `setup_project` function in favour of this!
___
*[`crates/cairo-lang-compiler/src/project.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1824#-NMDdRGS8EzAxeeLMltJ:-NMDdRGS8EzAxeeLMltK:b3jfxjz) ([raw file](https://github.com/starkware-libs/cairo/blob/2e61f75ab4ea2ac0dfc170cee7461c0aa02f872d/crates/cairo-lang-compiler/src/project.rs#L61)):*
> ```XML
> 
> /// Updates the crate roots from a ProjectConfig object.
> pub fn update_crate_roots_from_project_config(db: &mut dyn SemanticGroup, config: ProjectConfig) {
> ```

I think this definitely should go to RootDatabase construction phase?
___
*[`crates/cairo-lang-semantic/src/expr/test.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1824#-NMDe-Vd2QLWe9YJf4CD:-NMDe-Vd2QLWe9YJf4CE:bqarc17) ([raw file](https://github.com/starkware-libs/cairo/blob/e1939582a5bb7be063ff6e7667c94f7f99640bcb/crates/cairo-lang-semantic/src/expr/test.rs#L51)):*
> ```XML
> #[test_case(r"'\x12\x34'_u128", 0x1234, "u128")]
> fn test_expr_literal(expr: &str, value: i128, ty_name: &str) {
>     let mut db_val = SemanticDatabaseForTesting::default();
> ```

I think `Testing` databases could have the sensible `default` which calls `with_dev_corelib().unwrap()`. No need to change these files IMHO

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 33 of 33 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1824)* status: all files reviewed, 6 unresolved discussions (waiting on @maciektr)

___
*[`crates/cairo-lang-compiler/src/db.rs` line 67 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1824#-NMSdrNpBUHmVyhT6B-_:-NMSdrNpBUHmVyhT6B-a:b-rolu5x) ([raw file](https://github.com/starkware-libs/cairo/blob/fa57d733f25ce8b95b90998c843505edd924fab5/crates/cairo-lang-compiler/src/db.rs#L67)):*
> ```XML
> impl RootDatabaseBuilder {
>     pub fn new() -> Self {
>         Self { db: RootDatabase::new(Vec::new()) }
> ```

perhaps?



_Suggestion:_
```XML
RootDatabase::empty()
```
___
*[`crates/cairo-lang-compiler/src/db.rs` line 100 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1824#-NMSeXQV4Sht3wWcSno2:-NMSeXQV4Sht3wWcSno3:bj7ourv) ([raw file](https://github.com/starkware-libs/cairo/blob/fa57d733f25ce8b95b90998c843505edd924fab5/crates/cairo-lang-compiler/src/db.rs#L100)):*
> ```XML
>                 .iter()
>                 .map(|name| get_core_ty_by_name(&self.db, name.into(), vec![]))
>                 .collect_vec(),
> ```

With this snippet, you wouldn't have to use itertools in this crate :)



_Suggestion:_
```XML
.collect::<Vec<_>>()
```
___
*[`crates/cairo-lang-compiler/src/db.rs` line 107 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1824#-NMSdMwTBTMoneMu-VWp:-NMSdMwTBTMoneMu-VWq:b-frtury) ([raw file](https://github.com/starkware-libs/cairo/blob/fa57d733f25ce8b95b90998c843505edd924fab5/crates/cairo-lang-compiler/src/db.rs#L107)):*
> ```XML
>     pub fn build(&mut self) -> &mut RootDatabase {
>         &mut self.db
>     }
> ```

The builder should consume itself and return the database.

1. This will eliminate the need for `mem::take` which is sketchy.
2. I think you should be also able to avoid having to type `let mut builder` everywhere.



_Suggestion:_
```XML
    pub fn build(self) -> RootDatabase {
        self.db
    }
```

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 10 of 11 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1824)* status: all files reviewed, 3 unresolved discussions (waiting on @maciektr)

___
*[`crates/cairo-lang-starknet/src/db.rs` line 20 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1824#-NMU1TkBEftakABjoMm5:-NMU1TkBEftakABjoMm6:b-msq5wt) ([raw file](https://github.com/starkware-libs/cairo/blob/be00b61c08f909631ac70f8c3d6bf5e4e78fd1f9/crates/cairo-lang-starknet/src/db.rs#L20)):*
> ```XML
>         .with_dev_corelib()
>         .unwrap()
>         .with_implicit_precedence(Vec::from(precedence))
> ```

`vec![]` macro will be handy here

**Review by mkaput — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1824)* status: all files reviewed, 2 unresolved discussions (waiting on @maciektr)

**Review by mkaput — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1824#-:-NMYA_sfENJ2M5r1UEFB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciektr)

___
*[`crates/cairo-lang-compiler/src/db.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1824#-NMDct4cDKNpp3RdpFcR:-NMYAYyX7R6nhzHvDu78:b-dwxrcv) ([raw file](https://github.com/starkware-libs/cairo/blob/2e61f75ab4ea2ac0dfc170cee7461c0aa02f872d/crates/cairo-lang-compiler/src/db.rs#L55)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

This is not interning all crate_roots from the project.

I think it might be epic to remove the `setup_project` function in favour of this!
</blockquote></details>

Topic for separate PR I think.
___
*[`crates/cairo-lang-compiler/src/project.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1824#-NMDdRGS8EzAxeeLMltJ:-NMYAWMB6k0yO9NvdHfb:b-dwxrcv) ([raw file](https://github.com/starkware-libs/cairo/blob/2e61f75ab4ea2ac0dfc170cee7461c0aa02f872d/crates/cairo-lang-compiler/src/project.rs#L61)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I think this definitely should go to RootDatabase construction phase?
</blockquote></details>

Topic for separate PR I think.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 39 files at r1, 4 of 33 files at r2, 6 of 11 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1824)* status: all files reviewed, 1 unresolved discussion (waiting on @maciektr and @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 731 at r6](https://reviewable.io/reviews/starkware-libs/cairo/1824#-NMYXpbh4nGnCI-OAvNN:-NMYXpbh4nGnCI-OAvNO:bncdpqz) ([raw file](https://github.com/starkware-libs/cairo/blob/fcbca284ad539aa21c0f69288cd62359eba8c873/crates/cairo-lang-language-server/src/lib.rs#L731)):*
> ```XML
>         path.pop();
>         if let Ok(config) = ProjectConfig::from_directory(path.as_path()) {
>             update_crate_roots_from_project_config(db, config);
> ```

The language server should try to init from dev_corelib as well. At least, this is how we work today on the repo. WDYT?

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 19 of 33 files at r2, 2 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1824)* status: all files reviewed, 1 unresolved discussion (waiting on @maciektr and @orizi)

**Comment by maciektr** [comment]
*[`crates/cairo-lang-language-server/src/lib.rs` line 731 at r6](https://reviewable.io/reviews/starkware-libs/cairo/1824#-NMYXpbh4nGnCI-OAvNN:-NMcLW4t-M4LSX_9No3u:b-qhhkoq) ([raw file](https://github.com/starkware-libs/cairo/blob/fcbca284ad539aa21c0f69288cd62359eba8c873/crates/cairo-lang-language-server/src/lib.rs#L731)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

The language server should try to init from dev_corelib as well. At least, this is how we work today on the repo. WDYT?
</blockquote></details>

I agree it should, although I believe this behaviour is supported in the current state of changes. 
The language server db is created with `get_starknet_database` helper (https://github.com/starkware-libs/cairo/blob/f90934e027153a2abe5d6fb4ede83bb03e024e22/crates/cairo-lang-language-server/src/bin/language_server.rs#L14) which is suggested to include dev corelib detection step as well (https://github.com/starkware-libs/cairo/blob/fcbca284ad539aa21c0f69288cd62359eba8c873/crates/cairo-lang-starknet/src/db.rs#L17).

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1824#-:-NMcPW01E_qmYrXAejG3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Comment by mkaput** [comment]
😍

**Comment by mkaput** [comment]
Good job @maciektr !

**Pull request merged**
