### PR TITLE
Added gas redeposit optimization stage.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6280)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/gas.cairo` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6280#-O5DzgRJ-LDfixW9-bRF:-O5DzgRK-qiDqsJdBuip:byrn9rt) ([raw file](https://github.com/starkware-libs/cairo/blob/bbe185686e7c3518da0de2abac6474158bb1ee31/corelib/src/gas.cairo#L42)):*
> ```Cairo
> ///
> /// Useful for cases where different branches take different amounts of gas, but gas withdrawal is
> /// the same for both.
> ```

What do you mean by "gas withdrawal is the same for both"?



_Code quote:_
```Cairo
/// Useful for cases where different branches take different amounts of gas, but gas withdrawal is
/// the same for both.
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6280)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @ilyalesokhin-starkware)

___
*[`corelib/src/gas.cairo` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6280#-O5DzgRJ-LDfixW9-bRF:-O5E-QDH4MxGbZALLvRZ:bopvxml) ([raw file](https://github.com/starkware-libs/cairo/blob/bbe185686e7c3518da0de2abac6474158bb1ee31/corelib/src/gas.cairo#L42)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

What do you mean by "gas withdrawal is the same for both"?
</blockquote></details>

i mean the gas withdrawal happened before the branching - so it was shared by both.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/gas_redeposit.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6280#-O5E-m9g8gz88yPD-Ro4:-O5E-m9g8gz88yPD-Ro5:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/bbe185686e7c3518da0de2abac6474158bb1ee31/crates/cairo-lang-lowering/src/optimizations/gas_redeposit.rs#L69)):*
> ```XML
>             }
>             FlatBlockEnd::Match { info } => {
>                 let location = info.location().with_auto_generation_note(db, "withdraw_gas");
> ```





_Suggestion:_
```XML
redeposit_gas
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/strategy.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6280#-O5E0J1u17IgPaOfXSr1:-O5E0J1u17IgPaOfXSr2:blp1d3r) ([raw file](https://github.com/starkware-libs/cairo/blob/bbe185686e7c3518da0de2abac6474158bb1ee31/crates/cairo-lang-lowering/src/optimizations/strategy.rs#L127)):*
> ```XML
>     OptimizationStrategy(vec![
>         OptimizationPhase::GasRedeposit,
>         OptimizationPhase::LowerImplicits,
> ```

What functions have the gas builtins before lower implicits?
is it used only in functions where the builtin was requested explicitly?



_Code quote:_
```XML
        OptimizationPhase::GasRedeposit,
        OptimizationPhase::LowerImplicits,
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/test_data/gas_redeposit` line 159 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6280#-O5E0snX5RN-tn79TcwE:-O5E0snX5RN-tn79TcwF:bnqv7oh) ([raw file](https://github.com/starkware-libs/cairo/blob/bbe185686e7c3518da0de2abac6474158bb1ee31/crates/cairo-lang-lowering/src/optimizations/test_data/gas_redeposit#L159)):*
> ```
> 
> //! > after
> Parameters: v0: core::felt252
> ```

there is no GasBuiltin in this function, how come the optimization is applied?



_Code quote:_
```
Parameters: v0: core::felt252
```

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/gas.cairo` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6280#-O5DzgRJ-LDfixW9-bRF:-O5E3D546bby9VQHY5Or:bbnri82) ([raw file](https://github.com/starkware-libs/cairo/blob/bbe185686e7c3518da0de2abac6474158bb1ee31/corelib/src/gas.cairo#L42)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i mean the gas withdrawal happened before the branching - so it was shared by both.
</blockquote></details>

Can you remove it?
does it add information on top of
"Useful for cases where different branches take different amounts of gas"?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6280)* status: 0 of 11 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @ilyalesokhin-starkware)

___
*[`corelib/src/gas.cairo` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6280#-O5DzgRJ-LDfixW9-bRF:-O5EMS6Z2DXvsAB8Jg2G:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bbe185686e7c3518da0de2abac6474158bb1ee31/corelib/src/gas.cairo#L42)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Can you remove it?
does it add information on top of
"Useful for cases where different branches take different amounts of gas"?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/optimizations/gas_redeposit.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6280#-O5E-m9g8gz88yPD-Ro4:-O5EMzFK8gKTFuGsHI2h:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bbe185686e7c3518da0de2abac6474158bb1ee31/crates/cairo-lang-lowering/src/optimizations/gas_redeposit.rs#L69)):*
> ```XML
>             }
>             FlatBlockEnd::Match { info } => {
>                 let location = info.location().with_auto_generation_note(db, "withdraw_gas");
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/optimizations/strategy.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6280#-O5E0J1u17IgPaOfXSr1:-O5EN-yN7_MkBCySCo0s:b-adj40g) ([raw file](https://github.com/starkware-libs/cairo/blob/bbe185686e7c3518da0de2abac6474158bb1ee31/crates/cairo-lang-lowering/src/optimizations/strategy.rs#L127)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

What functions have the gas builtins before lower implicits?
is it used only in functions where the builtin was requested explicitly?
</blockquote></details>

because of loops and dependencies of loops and explicitly using functions (such as syscalls, entrypoints and dict-squash)
___
*[`crates/cairo-lang-lowering/src/optimizations/test_data/gas_redeposit` line 159 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6280#-O5E0snX5RN-tn79TcwE:-O5ENJIVCvmMoa1z8Sbb:bjpz9be) ([raw file](https://github.com/starkware-libs/cairo/blob/bbe185686e7c3518da0de2abac6474158bb1ee31/crates/cairo-lang-lowering/src/optimizations/test_data/gas_redeposit#L159)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

there is no GasBuiltin in this function, how come the optimization is applied?
</blockquote></details>

it depends on a function that does have it.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/gas_redeposit.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6280#-O5HRBEr9pRKIDovR1VE:-O5HRBEr9pRKIDovR1VF:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9024330dc12c66cfc037fef64184c294e33054b0/crates/cairo-lang-lowering/src/optimizations/gas_redeposit.rs#L20)):*
> ```XML
> /// Check if the function has the `GasBuiltin` implicit.
> /// If it does, add a `redeposit_gas` call at the beginning of every branch in the code.
> /// If it doesn't, do nothing.
> ```





_Suggestion:_
```XML
/// Check if the function will have the `GasBuiltin` implicit after the lower_implicits stage.
/// If so, add a `redeposit_gas` call at the beginning of every branch in the code.
/// Otherwise, do nothing.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/gas_redeposit.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6280#-O5HRBEr9pRKIDovR1VE:-O5HRTCKERKTIqK6hZEr:bbt31d8) ([raw file](https://github.com/starkware-libs/cairo/blob/9024330dc12c66cfc037fef64184c294e33054b0/crates/cairo-lang-lowering/src/optimizations/gas_redeposit.rs#L20)):*
> ```XML
> /// Check if the function has the `GasBuiltin` implicit.
> /// If it does, add a `redeposit_gas` call at the beginning of every branch in the code.
> /// If it doesn't, do nothing.
> ```

add a comment that needs to be done before the lower_implicits stage

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 10 of 11 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6280)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6280)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/gas_redeposit.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6280#-O5HRBEr9pRKIDovR1VE:-O5MQOhiAqWblyIKXNXl:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9024330dc12c66cfc037fef64184c294e33054b0/crates/cairo-lang-lowering/src/optimizations/gas_redeposit.rs#L20)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

add a comment that needs to be done before the lower_implicits stage
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/gas_redeposit.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6280#-O5HRBEr9pRKIDovR1VE:-O5MflLFBaEIK4Nq0J3u:bwjqbkw) ([raw file](https://github.com/starkware-libs/cairo/blob/9024330dc12c66cfc037fef64184c294e33054b0/crates/cairo-lang-lowering/src/optimizations/gas_redeposit.rs#L20)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You didn't mention that it has to be done before the lower_implicits stage.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6280)* status: 8 of 11 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/gas_redeposit.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6280#-O5HRBEr9pRKIDovR1VE:-O5Mh74H-aU_0TVk5mgR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9024330dc12c66cfc037fef64184c294e33054b0/crates/cairo-lang-lowering/src/optimizations/gas_redeposit.rs#L20)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

You didn't mention that it has to be done before the lower_implicits stage.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6280#-:-O5N-6F02eSIVxEZE9Dw:bnfp4nl)* status: 10 of 11 files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
