### PR TITLE
added support for passing const generic params as const generic argum…

### PR DESCRIPTION
**Pull request by TomerStarkware**
…ents

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5203)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5203)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5203#-NsEN4tVC869JDWN9hXz:-NsEN4tVC869JDWN9hY-:b7hw0r4) (no related file):*
blocking since reviewable didn't.

___

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5203)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/generics` line 663 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5203#-NsEMcWQ4kCO2y8Bh84Q:-NsHlRq-BWNRRvg0edJt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7bfd84b32bf77c68f9388b09f266c1f7287769fd/crates/cairo-lang-semantic/src/expr/test_data/generics#L663)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Improve print.
</blockquote></details>

Done.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5203)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5203#-NsEN4tVC869JDWN9hXz:-NsI5jcK8XgSmzWEp4Ly:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

blocking since reviewable didn't.
</blockquote></details>

Done.

___

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5203)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
