### PR TITLE
Coupons: Add more tests.

### PR DESCRIPTION
**Pull request by liorgold2**
commit-id:372a4349

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4735)

### CODE REVIEW

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4735)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 896 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4735#-NnJsNJf4Md-Q0t9yRe1:-NnJsNJf4Md-Q0t9yRe2:b39ixta) ([raw file](https://github.com/starkware-libs/cairo/blob/8a22ffd43ca20a1e6f3c1992fbda001c852697da/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L896)):*
> ```
> note: Trait has no implementation in context: core::traits::PanicDestruct::<test::NonCopy>
> 
> error: Variable not dropped.
> ```

Not sure if when I remove it if hurts the coverage that was supposed to be achieved by this test. PTAL.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4735)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`corelib/src/test/coupon_test.cairo` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4735#-NnKt-T89GVX4VXAseqp:-NnKt-T89GVX4VXAseqq:b5qnjk5) ([raw file](https://github.com/starkware-libs/cairo/blob/6c71eaf54240c123095cc88714c37026c83181a9/corelib/src/test/coupon_test.cairo#L13)):*
> ```Cairo
> impl NonDroppableDestruct of Destruct<NonDroppable> {
>     fn destruct(self: NonDroppable) nopanic {
>         print(array![self.x]);
> ```

i don't like print based tests.

can you make this function not a destructor, and just add to a counter?
There is no need to call destruct specifically i guess - just to make sure it is actually not taking gas for the run.

so just calling it + checking available gas before and after are the same (so only coupons were wasted)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4735)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 896 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4735#-NnJsNJf4Md-Q0t9yRe1:-NnKtpB9Aiw9x1tcAnBo:b-w7vjk6) ([raw file](https://github.com/starkware-libs/cairo/blob/8a22ffd43ca20a1e6f3c1992fbda001c852697da/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L896)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Not sure if when I remove it if hurts the coverage that was supposed to be achieved by this test. PTAL.
</blockquote></details>

it is fine - not the interesting part of the test.

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4735)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/test/coupon_test.cairo` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4735#-NnKt-T89GVX4VXAseqp:-NnLDSol0HZeEjz5Od39:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6c71eaf54240c123095cc88714c37026c83181a9/corelib/src/test/coupon_test.cairo#L13)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i don't like print based tests.

can you make this function not a destructor, and just add to a counter?
There is no need to call destruct specifically i guess - just to make sure it is actually not taking gas for the run.

so just calling it + checking available gas before and after are the same (so only coupons were wasted)
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4735)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`corelib/src/test/coupon_test.cairo` line 15 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4735#-NnLye2l59GTLr5ULImP:-NnLye2l59GTLr5ULImQ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c9e225098d1285824c51052bc172e33d30501798/corelib/src/test/coupon_test.cairo#L15)):*
> ```Cairo
> 
> #[test]
> fn test_arr_sqrt() {
> ```





_Suggestion:_
```Cairo
fn test_arr_sum() {
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4735)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/test/coupon_test.cairo` line 15 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4735#-NnLye2l59GTLr5ULImP:-NnO4k7_-eol7X_UGmpw:b-a4wcvi) ([raw file](https://github.com/starkware-libs/cairo/blob/c9e225098d1285824c51052bc172e33d30501798/corelib/src/test/coupon_test.cairo#L15)):*
> ```Cairo
> 
> #[test]
> fn test_arr_sqrt() {
> ```

Oops. Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4735#-:-NnOe9bSAAXDPij6BKdp:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
