### PR TITLE
LS: Introduce E2E test suite

### PR DESCRIPTION
**Pull request by mkaput**
**Stack**:
- #5474
- #5510 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5510)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5510)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @mkaput)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5510#-NxDMo7899FgzoYGYc3w:-NxDMo7899FgzoYGYc3x:b18xb3z) ([raw file](https://github.com/starkware-libs/cairo/blob/ccae1b51dc23f9172f52b38ac25a43558aec0a1b/crates/cairo-lang-language-server/src/lib.rs#L161)):*
> ```XML
> pub fn build_service_for_e2e_tests() -> (LspService<impl LanguageServer>, ClientSocket) {
>     Backend::build_service(Tricks::default())
> }
> ```

maybe under test-feature?



_Code quote:_
```XML
#[cfg(debug_assertions)]
#[doc(hidden)]
pub fn build_service_for_e2e_tests() -> (LspService<impl LanguageServer>, ClientSocket) {
    Backend::build_service(Tricks::default())
}
```

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5510)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5510#-NxDMo7899FgzoYGYc3w:-NxHijJ20Wiwscmp3Iez:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ccae1b51dc23f9172f52b38ac25a43558aec0a1b/crates/cairo-lang-language-server/src/lib.rs#L161)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe under test-feature?
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5510)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @mkaput)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 157 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5510#-NxI2kZN5Rv3dbJWnPaC:-NxI2kZOCKQ3i-yPtySd:bafywsa) ([raw file](https://github.com/starkware-libs/cairo/blob/dcebea24e516eafe80ce5f5a51138264b0e5f191/crates/cairo-lang-language-server/src/lib.rs#L157)):*
> ```XML
> 
> /// Special function to run the language server in end-to-end tests. Do not use in production code!
> #[cfg(feature = "testing")]
> ```

no longer required under test feature.



_Suggestion:_
```XML
/// Special function to run the language server in end-to-end tests.
#[cfg(feature = "testing")]
```
___
*[`crates/cairo-lang-language-server/tests/e2e/support/mod.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5510#-NxI30B--OqE1wh5GrJg:-NxI30B--OqE1wh5GrJh:bcxynxf) ([raw file](https://github.com/starkware-libs/cairo/blob/dcebea24e516eafe80ce5f5a51138264b0e5f191/crates/cairo-lang-language-server/tests/e2e/support/mod.rs#L1)):*
> ```XML
> use std::ffi::OsStr;
> ```

was this code copied from somewhere?
if so - doc with a code pointer.
if not - doc all around.

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5510)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 157 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5510#-NxI2kZN5Rv3dbJWnPaC:-NxITX6k2G1L0_oF-mv3:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/dcebea24e516eafe80ce5f5a51138264b0e5f191/crates/cairo-lang-language-server/src/lib.rs#L157)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no longer required under test feature.
</blockquote></details>

Done
___
*[`crates/cairo-lang-language-server/tests/e2e/support/mod.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5510#-NxI30B--OqE1wh5GrJg:-NxIe7iH5jqH4YC-p0Wx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/dcebea24e516eafe80ce5f5a51138264b0e5f191/crates/cairo-lang-language-server/tests/e2e/support/mod.rs#L1)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

was this code copied from somewhere?
if so - doc with a code pointer.
if not - doc all around.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5510)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)

___
*[`crates/cairo-lang-language-server/tests/e2e/support/fixture.rs` line 8 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5510#-NxIeYnW2ZSgjMlqGFVe:-NxIeYnW2ZSgjMlqGFVf:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/54759c81195e05dbfec742c255d0b36a14e1a2bb/crates/cairo-lang-language-server/tests/e2e/support/fixture.rs#L8)):*
> ```XML
> use tower_lsp::lsp_types::Url;
> 
> /// A temporary directory that is a context for testing the language server
> ```





_Suggestion:_
```XML
/// A temporary directory that is a context for testing the language server.
```

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5510)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-language-server/tests/e2e/support/fixture.rs` line 8 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5510#-NxIeYnW2ZSgjMlqGFVe:-NxIkUrY7et4zp1FvPjD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/54759c81195e05dbfec742c255d0b36a14e1a2bb/crates/cairo-lang-language-server/tests/e2e/support/fixture.rs#L8)):*
> ```XML
> use tower_lsp::lsp_types::Url;
> 
> /// A temporary directory that is a context for testing the language server
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5510#-:-NxInAhTEPEvlqAVUA0J:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5510)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Pull request merged**
