### PR TITLE
Prevent embeddable_as adding Drop if already exist.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4142)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4142)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/components/diagnostics` line 1002 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4142#-NfGwtVc3z_KkbkKYHa-:-NfGwtVc3z_KkbkKYHa0:boek55o) ([raw file](https://github.com/starkware-libs/cairo/blob/4cc4215634ee24471f035023fe69095779110bc9/crates/cairo-lang-starknet/src/plugin/plugin_test_data/components/diagnostics#L1002)):*
> ```
> 
> //! > test_runner_name
> ExpandContractTestRunner(expect_diagnostics: false)
> ```

1. move to another file
2. Add here tests with Destruct, PanicDestruct.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs` line 282 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4142#-NfGwkgG33BAshRIDZu_:-NfGwkgG33BAshRIDZua:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/4cc4215634ee24471f035023fe69095779110bc9/crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs#L282)):*
> ```XML
>             ("impl_functions".to_string(), RewriteNode::new_modified(impl_functions)),
>         ]
>         .into(),
> ```





_Suggestion:_
```XML
    let has_drop_impl = params.generic_params_node.elements(db).iter().any(|param| {
        param.is_impl_of(db, "Drop", GENERIC_CONTRACT_STATE_NAME)
    });
    let maybe_drop_impl = if has_drop_impl {
        ""
    } else {
        format!("{maybe_comma}impl {GENERIC_CONTRACT_STATE_NAME}Drop: \
        Drop<{GENERIC_CONTRACT_STATE_NAME}>")
    };

    let generated_impl_node = RewriteNode::interpolate_patched(
        &formatdoc!(
            "
        #[starknet::embeddable]
        impl $generated_impl_name$<
            $generic_params${maybe_drop_impl}
        > of $trait_path$<{GENERIC_CONTRACT_STATE_NAME}> {{$impl_functions$
        }}"
        ),
        &[
            ("trait_path".to_string(), trait_path_without_generics),
            (
                "generated_impl_name".to_string(),
                RewriteNode::Copied(params.attr_arg_value.as_syntax_node()),
            ),
            (
                "generic_params".to_string(),
                RewriteNode::Copied(params.generic_params_node.as_syntax_node()),
            ),
            ("impl_functions".to_string(), RewriteNode::new_modified(impl_functions)),
        ]
        .into(),
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4142)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/components/diagnostics` line 1002 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4142#-NfGwtVc3z_KkbkKYHa-:-NfGyWPS-ZSypHb639qm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4cc4215634ee24471f035023fe69095779110bc9/crates/cairo-lang-starknet/src/plugin/plugin_test_data/components/diagnostics#L1002)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

1. move to another file
2. Add here tests with Destruct, PanicDestruct.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs` line 282 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4142#-NfGvB-w7qwPW0uRkEAx:-NfGyP0UAj2nPD3cH1uN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4cc4215634ee24471f035023fe69095779110bc9/crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs#L282)):*
> ```XML
>             ("impl_functions".to_string(), RewriteNode::new_modified(impl_functions)),
>         ]
>         .into(),
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs` line 282 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4142#-NfGwkgG33BAshRIDZu_:-NfGyTjA2cjIKYHXI6eW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4cc4215634ee24471f035023fe69095779110bc9/crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs#L282)):*
> ```XML
>             ("impl_functions".to_string(), RewriteNode::new_modified(impl_functions)),
>         ]
>         .into(),
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4142#-:-NfGyxti18Q-yqoDmtLT:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4142)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/components/diagnostics` line 1147 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4142#-NfH8OdwELnQ8kOMqrl4:-NfH8OdwELnQ8kOMqrl5:blx5f4) ([raw file](https://github.com/starkware-libs/cairo/blob/4347041bdfaa2a5e8d1c505b0f8ece745ba8d0cb/crates/cairo-lang-starknet/src/plugin/plugin_test_data/components/diagnostics#L1147)):*
> ```
> }
> 
> //! > expected_diagnostics
> ```

in both tests: please move diagnostics section before generated code section.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/components/diagnostics` line 1161 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4142#-NfH8t3s4Ln41rrc6UDn:-NfH8t3s4Ln41rrc6UDo:bsrwy4r) ([raw file](https://github.com/starkware-libs/cairo/blob/4347041bdfaa2a5e8d1c505b0f8ece745ba8d0cb/crates/cairo-lang-starknet/src/plugin/plugin_test_data/components/diagnostics#L1161)):*
> ```
>  --> lib.cairo:8:21
>     #[embeddable_as(MyImpl)]
>                     ^****^
> ```

would these errors happen if we add the same check in embeddable_as, and don't generate the code in this case?
If not - I think it's worth adding such check.



_Code quote:_
```
error: Plugin diagnostic: Trait `core::traits::Destruct::<TContractState>` has multiple implementations, in: GenericParamImpl(test::component::MyImpl::_), core::traits::DestructFromDrop::<TContractState, GenericParamImpl(test::component::MyImpl::TContractStateDrop)>
 --> lib.cairo:9:10
    impl MyInnerImpl<TContractState, impl X: HasComponent<TContractState>, +Destruct<TContractState>> of MyTrait<ComponentState<TContractState>> {
         ^*********^

error: Plugin diagnostic: Trait `core::traits::Destruct::<TContractState>` has multiple implementations, in: GenericParamImpl(test::component::__wrapper__MyImpl__do_nothing::_), core::traits::DestructFromDrop::<TContractState, GenericParamImpl(test::component::__wrapper__MyImpl__do_nothing::TContractStateDrop)>
 --> lib.cairo:8:21
    #[embeddable_as(MyImpl)]
                    ^****^
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4142)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/components/diagnostics` line 1161 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4142#-NfH8t3s4Ln41rrc6UDn:-NfIRtpW1dA5VdQ9c84N:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4347041bdfaa2a5e8d1c505b0f8ece745ba8d0cb/crates/cairo-lang-starknet/src/plugin/plugin_test_data/components/diagnostics#L1161)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

would these errors happen if we add the same check in embeddable_as, and don't generate the code in this case?
If not - I think it's worth adding such check.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4142)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4142)* status: all files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/components/diagnostics` line 1106 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4142#-NfIa2fd5H3htSUIYudc:-NfIa2fd5H3htSUIYudd:b-f7onlc) ([raw file](https://github.com/starkware-libs/cairo/blob/b86761d3495a5bd6f7aa40c8a335bf158d1cf210/crates/cairo-lang-starknet/src/plugin/plugin_test_data/components/diagnostics#L1106)):*
> ```
> }
> 
> //! > ==========================================================================
> ```

please add tests for embeddable (directly, without embeddable_as), with all 3 options.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs` line 227 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4142#-NfIZj9k6PgqmBJFkvsf:-NfIZj9l3pTA0R_IPBsv:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b86761d3495a5bd6f7aa40c8a335bf158d1cf210/crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs#L227)):*
> ```XML
>         return;
>     };
>     let mut has_illegal_impl = false;
> ```





_Suggestion:_
```XML
has_invalid_impl
```
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs` line 233 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4142#-NfI_4pK8gOkFk5tdhWl:-NfI_4pK8gOkFk5tdhWm:b6yv9k7) ([raw file](https://github.com/starkware-libs/cairo/blob/b86761d3495a5bd6f7aa40c8a335bf158d1cf210/crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs#L233)):*
> ```XML
>         {
>             has_illegal_impl = true;
>             diagnostics.push(PluginDiagnostic {
> ```

I am not sure we want multiple diagnostics (not that it's a common case). Maybe simply return here?
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs` line 238 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4142#-NfIZu1N1nHZW0TRQn4w:-NfIZu1N1nHZW0TRQn4x:b-nvoweu) ([raw file](https://github.com/starkware-libs/cairo/blob/b86761d3495a5bd6f7aa40c8a335bf158d1cf210/crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs#L238)):*
> ```XML
>                     "Embeddable_as impl can't have impl generic params of \
>                      `Destruct<{GENERIC_CONTRACT_STATE_NAME}>` or \
>                      `PanicDestruct<{GENERIC_CONTRACT_STATE_NAME}>`."
> ```

please also change the embeddable twin diag to be phrased similarly



_Suggestion:_
```XML
                    "`embeddable_as` impls can't have impl generic parameters of \
                     `Destruct<{GENERIC_CONTRACT_STATE_NAME}>` or \
                     `PanicDestruct<{GENERIC_CONTRACT_STATE_NAME}>`."
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4142)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/components/diagnostics` line 1106 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4142#-NfIa2fd5H3htSUIYudc:-NfJtlU77VeiwZfJozGW:buunnx9) ([raw file](https://github.com/starkware-libs/cairo/blob/b86761d3495a5bd6f7aa40c8a335bf158d1cf210/crates/cairo-lang-starknet/src/plugin/plugin_test_data/components/diagnostics#L1106)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

please add tests for embeddable (directly, without embeddable_as), with all 3 options.
</blockquote></details>

There are tests for `Destruct` and `PanicDestruct`, added for drop.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs` line 233 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4142#-NfI_4pK8gOkFk5tdhWl:-NfJraDuDtW4Uw-tYQ_x:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b86761d3495a5bd6f7aa40c8a335bf158d1cf210/crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs#L233)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I am not sure we want multiple diagnostics (not that it's a common case). Maybe simply return here?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs` line 238 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4142#-NfIZu1N1nHZW0TRQn4w:-NfJrrC_5Z5LuzkGu8xe:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b86761d3495a5bd6f7aa40c8a335bf158d1cf210/crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs#L238)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

please also change the embeddable twin diag to be phrased similarly
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4142)* status: all files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4142#-:-NfKXg_rCZloHOL-aFRM:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/embedded_impl` line 534 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4142#-NfKXYNY6w6s2Wrkmcwp:-NfKXYNY6w6s2Wrkmcwq:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/27a025f430764dc3ab05e09aa9b517e75f4be3f0/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/embedded_impl#L534)):*
> ```
> //! > ==========================================================================
> 
> //! > Test embeddable impl with exisiting drop impl..
> ```





_Suggestion:_
```
mpl.
```

**Pull request merged**
