### PR TITLE
Sierra->casm: Implement into_nullable() libfunc.

### PR DESCRIPTION
**Pull request by liorgold2**
commit-id:8f2c5dab

---

**Stack**:
- #1451
- #1436 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1436)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/sierra_to_casm/src/invocations/nullable.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1436#-NJqmBuR1QyXAQDwEoXo:-NJqmBuR1QyXAQDwEoXp:blkb7rw) ([raw file](https://github.com/starkware-libs/cairo/blob/268e0c2b6623149d9eff22ccbae1432cfa579b69/crates/sierra_to_casm/src/invocations/nullable.rs#L13)):*
> ```XML
>     match libfunc {
>         NullableConcreteLibFunc::Null(_) => build_nullable_null(builder),
>         NullableConcreteLibFunc::IntoNullable(_) => build_nullable_into_nullable(builder),
> ```

the system already validates all the typing - and there's no reason to not allow all options.



_Suggestion:_
```XML
 build_identity(builder)
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1436)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1436)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1436)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`crates/sierra_to_casm/src/invocations/nullable.rs` line 53 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1436#-NJxkfe8EbSNvHIGvnIR:-NJxkfe8EbSNvHIGvnIS:b-2bcd4c) ([raw file](https://github.com/starkware-libs/cairo/blob/dd26cc0552e3a2f2530968af454eae17979f7dc9/crates/sierra_to_casm/src/invocations/nullable.rs#L53)):*
> ```XML
>     assert!(
>         *builder.program_info.type_sizes.get(&libfunc.ty).expect("Unknown size for type") > 0,
>         "Nullable<> cannot be used for types of size 0."
> ```

no need - as we initiate the registry with all available concrete types.



_Suggestion:_
```XML
    assert!(
        *builder.program_info.type_sizes[&libfunc.ty] > 0,
        "Nullable<> cannot be used for types of size 0."
    );
```

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1436)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1436#-:-NJyRaJm467r-8Asv_JN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1436)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

___
*[`crates/sierra_to_casm/src/invocations/nullable.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1436#-NJqmBuR1QyXAQDwEoXo:-NJyP-UF2qYKsziOOkNl:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/268e0c2b6623149d9eff22ccbae1432cfa579b69/crates/sierra_to_casm/src/invocations/nullable.rs#L13)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the system already validates all the typing - and there's no reason to not allow all options.
</blockquote></details>

Done.

**Pull request merged**
