### PR TITLE
Make parse attribute stop on non-hash sign.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3928)

### CODE REVIEW

**Comment by yuvalsw** [comment]
*[`crates/cairo-lang-parser/src/parser_test_data/attribute_errors` line 8 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3928#-Nc2WfKZ3Y-l7keiux1O:-Nc2WfK_5FvpQPrqq_3A:bjchmou) ([raw file](https://github.com/starkware-libs/cairo/blob/9062c5b7cab2d346d4f947d501d0327ab8b47364/crates/cairo-lang-parser/src/parser_test_data/attribute_errors#L8)):*
> ```
> //! > cairo_code
> #[aaa]
> 3
> ```

Please add another test for:
#[aaa]
[bbb]
#[ccc]

This would be worse now, but probably acceptable



_Code quote:_
```
#[aaa]
3
```

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3928)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-parser/src/parser_test_data/attribute_errors` line 11 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3928#-Nc2XHHh4_IHeKqfQlv8:-Nc2XHHh4_IHeKqfQlv9:b-ydphw6) ([raw file](https://github.com/starkware-libs/cairo/blob/9062c5b7cab2d346d4f947d501d0327ab8b47364/crates/cairo-lang-parser/src/parser_test_data/attribute_errors#L11)):*
> ```
> 
> //! > top_level_kind
> Item
> ```

why don't we see the trees in the tests?
I think we can't have an enum here(?). Try removing this to view the whole tree and then decide on the relevant top_level_kind.



_Code quote:_
```
Item
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3928)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser_test_data/attribute_errors` line 8 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3928#-Nc2WfKZ3Y-l7keiux1O:-Nc2dxTU8bRVdQfLcr7C:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9062c5b7cab2d346d4f947d501d0327ab8b47364/crates/cairo-lang-parser/src/parser_test_data/attribute_errors#L8)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Please add another test for:
#[aaa]
[bbb]
#[ccc]

This would be worse now, but probably acceptable
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/attribute_errors` line 11 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3928#-Nc2XHHh4_IHeKqfQlv8:-Nc2dxrN8cPcHqkkmIAO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9062c5b7cab2d346d4f947d501d0327ab8b47364/crates/cairo-lang-parser/src/parser_test_data/attribute_errors#L11)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

why don't we see the trees in the tests?
I think we can't have an enum here(?). Try removing this to view the whole tree and then decide on the relevant top_level_kind.
</blockquote></details>

Done.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3928)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-parser/src/parser_test_data/attribute_errors` line 28 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3928#-NcNmvMi4r8ESme--llH:-NcNmvMi4r8ESme--llI:b-qogodv) ([raw file](https://github.com/starkware-libs/cairo/blob/4000c0c6c0198d24d484c6dadf50ef1cb91391db/crates/cairo-lang-parser/src/parser_test_data/attribute_errors#L28)):*
> ```
> //! > expected_tree
> └── Top level kind: ItemList
>     └── child #0: Missing []
> ```

shouldn't the missing item contain the attributes?
Hmm maybe it's because of the way it's printed. If so - I guess it's ok for now.



_Code quote:_
```
 child #0: Missing []
```
___
*[`crates/cairo-lang-parser/src/parser_test_data/attribute_errors` line 139 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3928#-NcNnhz37e2nx74mFzdS:-NcNnhz37e2nx74mFzdT:bn2ddj2) ([raw file](https://github.com/starkware-libs/cairo/blob/4000c0c6c0198d24d484c6dadf50ef1cb91391db/crates/cairo-lang-parser/src/parser_test_data/attribute_errors#L139)):*
> ```
> 1
> #[bbb]
> 2
> ```

I am not sure how useful this test is, it's simply the same thing from the test above, twice.

I wanted a test for:
#[aaa]  
[bbb]  
#[ccc]

(which is a possible mistake, if someone skips typing the '#')



_Code quote:_
```
#[aaa]
1
#[bbb]
2
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3928)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser_test_data/attribute_errors` line 28 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3928#-NcNmvMi4r8ESme--llH:-NcOYfjmDcyrd6Erp6Pm:b-rogg5e) ([raw file](https://github.com/starkware-libs/cairo/blob/4000c0c6c0198d24d484c6dadf50ef1cb91391db/crates/cairo-lang-parser/src/parser_test_data/attribute_errors#L28)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

shouldn't the missing item contain the attributes?
Hmm maybe it's because of the way it's printed. If so - I guess it's ok for now.
</blockquote></details>

It's printed like that all over, i'll TAL at it later.
___
*[`crates/cairo-lang-parser/src/parser_test_data/attribute_errors` line 139 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3928#-NcNnhz37e2nx74mFzdS:-NcOYm7X5dFrGv3qP0Wc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4000c0c6c0198d24d484c6dadf50ef1cb91391db/crates/cairo-lang-parser/src/parser_test_data/attribute_errors#L139)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I am not sure how useful this test is, it's simply the same thing from the test above, twice.

I wanted a test for:
#[aaa]  
[bbb]  
#[ccc]

(which is a possible mistake, if someone skips typing the '#')
</blockquote></details>

Done.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3928)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser_test_data/attribute_errors` line 138 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3928#-NcSDNMj1U3vvQgAcuRg:-NcXCJSb1Yo77UzuwSJb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d58ad93b4e9157c1d30427d52e9ff71b0a92f294/crates/cairo-lang-parser/src/parser_test_data/attribute_errors#L138)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

add a valid item after it.
</blockquote></details>

Done.

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3928)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
