### PR TITLE
Added trait QueryAttrs

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1566)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1566)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-syntax/src/node/helpers.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1566#-NKSRhYMAi7FdVMVGajO:-NKSRhYN4syEgwrLYy5w:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/99b3bc83106ff7c7d16a22463c47c116ff5a6750/crates/cairo-syntax/src/node/helpers.rs#L130)):*
> ```XML
> /// Trait for querying attributes of AST items.
> pub trait QueryAttrs {
>     fn any_attr(&self, db: &dyn SyntaxGroup, attr: &str) -> bool;
> ```





_Suggestion:_
```XML
has_attr
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1566)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-syntax/src/node/helpers.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1566#-NKSRhYMAi7FdVMVGajO:-NKSqvU-8GL1ipTldB3V:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/99b3bc83106ff7c7d16a22463c47c116ff5a6750/crates/cairo-syntax/src/node/helpers.rs#L130)):*
> ```XML
> /// Trait for querying attributes of AST items.
> pub trait QueryAttrs {
>     fn any_attr(&self, db: &dyn SyntaxGroup, attr: &str) -> bool;
> ```

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1566#-:-NKTJ_p36FZSVJlUr9B3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1566)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
