### PR TITLE
Added generics doc to the reference

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2714)

### CODE REVIEW

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2714)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`docs/reference/src/generics.adoc` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2714#-NSBfRIuD22WTL-Sjh4I:-NSZvO6_3DldTii0LmwZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/dbaef3dd19a8c2108f94f506ce751a8effe78c68/docs/reference/src/generics.adoc#L3)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Suggestion for rephrasing.
</blockquote></details>

Done.
___
*[`docs/reference/src/generics.adoc` line 4 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2714#-NSBdm628b0bsobu-pk5:-NSZvWln3m5XWqRSdhhY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/dbaef3dd19a8c2108f94f506ce751a8effe78c68/docs/reference/src/generics.adoc#L4)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

link to items
</blockquote></details>

Done.
___
*[`docs/reference/src/generics.adoc` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2714#-NSBe33J-6YHdCAVzRyV:-NSZvbutDfU8zv4P0jor:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/dbaef3dd19a8c2108f94f506ce751a8effe78c68/docs/reference/src/generics.adoc#L9)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`docs/reference/src/generics.adoc` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2714#-NSBeCrC4F5Garnvs7Un:-NSZxNUO-wKYvzorqu7a:b-reagzv) ([raw file](https://github.com/starkware-libs/cairo/blob/dbaef3dd19a8c2108f94f506ce751a8effe78c68/docs/reference/src/generics.adoc#L28)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Assignment can be confused with the assignment statement.
Also, I'd like to rephrase this a bit:

To use a generic item on specific

```

```
Maybe something with substitution?
```
An generic item can be made concrete by substitutionb
```
</blockquote></details>

I rephrased, LMK what you think.
I avoided saying "A generic item can be made" as it might sound like it creates only one concrete item. I also made this clear anyway.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2714)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`docs/reference/src/generics.adoc` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2714#-NSBeCrC4F5Garnvs7Un:-NS__h853kDvuGX-XEs3:b-yo0iza) ([raw file](https://github.com/starkware-libs/cairo/blob/dbaef3dd19a8c2108f94f506ce751a8effe78c68/docs/reference/src/generics.adoc#L28)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I rephrased, LMK what you think.
I avoided saying "A generic item can be made" as it might sound like it creates only one concrete item. I also made this clear anyway.
</blockquote></details>

Did you push your changes?

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2714)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`docs/reference/src/generics.adoc` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2714#-NSBeCrC4F5Garnvs7Un:-NS_aGk78KyQ6szmRdOx:b2ni8q9) ([raw file](https://github.com/starkware-libs/cairo/blob/dbaef3dd19a8c2108f94f506ce751a8effe78c68/docs/reference/src/generics.adoc#L28)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Did you push your changes?
</blockquote></details>

now

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2714)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2714)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2714)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2714#-:-NStLta9DYvedx9ucRFd:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
