### PR TITLE
Modules

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2691)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2691** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2691" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2691?utm_source=stack-comment).

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2691)* status: all files reviewed, 16 unresolved discussions (waiting on @spapinistarkware)

___
*[`docs/reference/src/module.adoc` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2691#-NS1ab-x2IjmJHErHqCC:-NS1ab-x2IjmJHErHqCD:b-ewz29i) ([raw file](https://github.com/starkware-libs/cairo/blob/5c1ed504c574c6445f7e7a2161804275636860b2/docs/reference/src/module.adoc#L3)):*
> ```AsciiDoc
> = Modules and crates
> 
> In Cairo, modules are used to organize code into separate files, allowing for easier management of
> ```

scopes? namespaces?
Files are something else (which we should clarify the difference from modules).



_Code quote:_
```AsciiDoc
files
```
___
*[`docs/reference/src/module.adoc` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2691#-NS1b22bCO41YusYQEqi:-NS1b22bCO41YusYQEqj:b-3qnc53) ([raw file](https://github.com/starkware-libs/cairo/blob/5c1ed504c574c6445f7e7a2161804275636860b2/docs/reference/src/module.adoc#L3)):*
> ```AsciiDoc
> = Modules and crates
> 
> In Cairo, modules are used to organize code into separate files, allowing for easier management of
> ```

suggestion



_Suggestion:_
```AsciiDoc
Modules are used to orga
```
___
*[`docs/reference/src/module.adoc` line 4 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2691#-NS1atcXD7n0TiRyS2rq:-NS1atcXD7n0TiRyS2rr:b5bz2c0) ([raw file](https://github.com/starkware-libs/cairo/blob/5c1ed504c574c6445f7e7a2161804275636860b2/docs/reference/src/module.adoc#L4)):*
> ```AsciiDoc
> 
> In Cairo, modules are used to organize code into separate files, allowing for easier management of
> code and better code reusability. A module is a named container for language items (See items.adoc)
> ```

should be link?



_Suggestion:_
```AsciiDoc
(see items.adoc)
```
___
*[`docs/reference/src/module.adoc` line 7 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2691#-NS1bOQG3yE7-l8gKOZJ:-NS1bOQG3yE7-l8gKOZK:b20i4w5) ([raw file](https://github.com/starkware-libs/cairo/blob/5c1ed504c574c6445f7e7a2161804275636860b2/docs/reference/src/module.adoc#L7)):*
> ```AsciiDoc
> such as structs, enums, functions, constants, and traits.
> 
> A crate is a compilation unit, and has a root module defined at the file `lib.cairo` under the
> ```

1. Previous sentence said modules (plural), this one says "a crate" (singular). Please choose one form.
2. I think it is a bit confusing that it's both a directory and a compilation unit. I suggest something like: "A crate is a compilation unit that is organised in a designated root directory. It has a root module defined at the file `lib.cairo` under this directory.
___
*[`docs/reference/src/module.adoc` line 8 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2691#-NS1bM2xA1ikdgm3g8PY:-NS1bM2xA1ikdgm3g8PZ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5c1ed504c574c6445f7e7a2161804275636860b2/docs/reference/src/module.adoc#L8)):*
> ```AsciiDoc
> 
> A crate is a compilation unit, and has a root module defined at the file `lib.cairo` under the
> crate root directory.
> ```





_Suggestion:_
```AsciiDoc
crate's root directory.
```
___
*[`docs/reference/src/module.adoc` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2691#-NS1cP0t31ZfB8FPG3Vo:-NS1cP0t31ZfB8FPG3Vp:b1hvuyx) ([raw file](https://github.com/starkware-libs/cairo/blob/5c1ed504c574c6445f7e7a2161804275636860b2/docs/reference/src/module.adoc#L13)):*
> ```AsciiDoc
> A module can be defined in two ways: inlined in the current file or in a separate file.
> When a module is defined in a separate file, the file is located under
> `<current_module_dir>/<module_name>.cairo`.
> ```

If it's the root module, this is the crate dir



_Code quote:_
```AsciiDoc
<current_module_dir>
```
___
*[`docs/reference/src/module.adoc` line 23 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2691#-NS1cf861dhZ9ieg08W0:-NS1cf861dhZ9ieg08W1:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5c1ed504c574c6445f7e7a2161804275636860b2/docs/reference/src/module.adoc#L23)):*
> ```AsciiDoc
> }
> 
> // This is a module defined in at `/bar.cairo`.
> ```





_Suggestion:_
```AsciiDoc
is is a module defined in `a/bar.cairo`
```
___
*[`docs/reference/src/module.adoc` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2691#-NS1cy6q91Y6zXvV3djX:-NS1cy6q91Y6zXvV3djY:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5c1ed504c574c6445f7e7a2161804275636860b2/docs/reference/src/module.adoc#L28)):*
> ```AsciiDoc
> 
> == Module Hierarchy
> The module hierarchy that is defined by the module definitions in the source code.
> ```





_Suggestion:_
```AsciiDoc
he module hierarcht is defined by the mo
```
___
*[`docs/reference/src/module.adoc` line 29 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2691#-NS1d4fP8QhUwiDc-v15:-NS1d4fP8QhUwiDc-v16:b-9oyr00) ([raw file](https://github.com/starkware-libs/cairo/blob/5c1ed504c574c6445f7e7a2161804275636860b2/docs/reference/src/module.adoc#L29)):*
> ```AsciiDoc
> == Module Hierarchy
> The module hierarchy that is defined by the module definitions in the source code.
> When a module is defined inside another module, it is called a *nested module*. The parent
> ```

maybe submodule?



_Code quote:_
```AsciiDoc
*nested module*
```
___
*[`docs/reference/src/module.adoc` line 31 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2691#-NS1dObN1P4y2bujwNnX:-NS1dObN1P4y2bujwNnY:b-1eh9yx) ([raw file](https://github.com/starkware-libs/cairo/blob/5c1ed504c574c6445f7e7a2161804275636860b2/docs/reference/src/module.adoc#L31)):*
> ```AsciiDoc
> When a module is defined inside another module, it is called a *nested module*. The parent
> module can be referred to using the `super` keyword. The root module of a crate has no parent.
> Submodules are modules defined inside the current module, and can be referred to using
> ```

this repeats the previous sentence (also defines it as submodule (vs. nested modules)).



_Code quote:_
```AsciiDoc
Submodules are modules defined inside the current module
```
___
*[`docs/reference/src/module.adoc` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2691#-NS1dJEuDfR3CS8mhUaT:-NS1dJEuDfR3CS8mhUaU:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5c1ed504c574c6445f7e7a2161804275636860b2/docs/reference/src/module.adoc#L32)):*
> ```AsciiDoc
> module can be referred to using the `super` keyword. The root module of a crate has no parent.
> Submodules are modules defined inside the current module, and can be referred to using
> their name.
> ```





_Suggestion:_
```AsciiDoc
their names.
```
___
*[`docs/reference/src/module.adoc` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2691#-NS1eQnS2__6VkvAkK6J:-NS1eQnS2__6VkvAkK6K:b20rh97) ([raw file](https://github.com/starkware-libs/cairo/blob/5c1ed504c574c6445f7e7a2161804275636860b2/docs/reference/src/module.adoc#L36)):*
> ```AsciiDoc
> 
> == Module Scope
> Items defined inside a module are available only within the module. In particular, items defined
> ```

This is confusing as there are ways to access them. Just not directly.



_Code quote:_
```AsciiDoc
Items defined inside a module are available only within the module
```
___
*[`docs/reference/src/module.adoc` line 39 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2691#-NS1dqsR1H-Fm8B1p5JP:-NS1dqsR1H-Fm8B1p5JQ:b-7nahk0) ([raw file](https://github.com/starkware-libs/cairo/blob/5c1ed504c574c6445f7e7a2161804275636860b2/docs/reference/src/module.adoc#L39)):*
> ```AsciiDoc
> at outer modules are not available in inner modules, even when inlined.
> To make an item from an outer module available in an inner module, the item must be
> imported using the `use` keyword. (See `use.adoc`)
> ```

link?



_Code quote:_
```AsciiDoc
(See `use.adoc`)
```
___
*[`docs/reference/src/module.adoc` line 39 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2691#-NS1dtVQ-CtAe1l3wwMd:-NS1dtVQ-CtAe1l3wwMe:bmrvvyy) ([raw file](https://github.com/starkware-libs/cairo/blob/5c1ed504c574c6445f7e7a2161804275636860b2/docs/reference/src/module.adoc#L39)):*
> ```AsciiDoc
> at outer modules are not available in inner modules, even when inlined.
> To make an item from an outer module available in an inner module, the item must be
> imported using the `use` keyword. (See `use.adoc`)
> ```

"or by referring to them using their relative/full path."
This is actually what you demonstrate below.

Please also add an example of `use` below (maybe with an additional struct B).



_Code quote:_
```AsciiDoc
To make an item from an outer module available in an inner module, the item must be
imported using the `use` keyword. (See `use.adoc`)
```
___
*[`docs/reference/src/SUMMARY.adoc` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2691#-NS1a1h80-8HS8jSGzar:-NS1a1h80-8HS8jSGzas:b-9gvrva) ([raw file](https://github.com/starkware-libs/cairo/blob/5c1ed504c574c6445f7e7a2161804275636860b2/docs/reference/src/SUMMARY.adoc#L19)):*
> ```AsciiDoc
> 
> * link:items.adoc[Items]
> ** link:module.adoc[Module]
> ```

plural, to be consistent with the rest.



_Code quote:_
```AsciiDoc
* link:module.adoc[Module]
```
___
*[`docs/reference/src/traits.adoc` line 4 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2691#-NS1aC4D7qPB5DSoHy_K:-NS1aC4D7qPB5DSoHy_L:beclsvb) ([raw file](https://github.com/starkware-libs/cairo/blob/5c1ed504c574c6445f7e7a2161804275636860b2/docs/reference/src/traits.adoc#L4)):*
> ```AsciiDoc
> 
> Traits and impls are a feature of the Cairo language, providing a way to define
> abstract behavior and implement it in a concrete manner.
> ```

suggestion
IMO "feature of the Cairo language" is redundant.



_Suggestion:_
```AsciiDoc
Traits and impls provide a way to define
abstract behavior and implement it in a concrete manner.
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2691)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`docs/reference/src/module.adoc` line 7 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2691#-NS1bOQG3yE7-l8gKOZJ:-NS4flsk9TglxvEv7Qw7:b-915tn) ([raw file](https://github.com/starkware-libs/cairo/blob/5c1ed504c574c6445f7e7a2161804275636860b2/docs/reference/src/module.adoc#L7)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

1. Previous sentence said modules (plural), this one says "a crate" (singular). Please choose one form.
2. I think it is a bit confusing that it's both a directory and a compilation unit. I suggest something like: "A crate is a compilation unit that is organised in a designated root directory. It has a root module defined at the file `lib.cairo` under this directory.

</blockquote></details>

1. Previous statements started with "modules are ...", and then easoned about a single module.
2. It's not a directory, it has a root directory though (I used "crate root directory")
___
*[`docs/reference/src/module.adoc` line 31 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2691#-NS1dObN1P4y2bujwNnX:-NS4wHCzByc_hzsBnpn8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5c1ed504c574c6445f7e7a2161804275636860b2/docs/reference/src/module.adoc#L31)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

this repeats the previous sentence (also defines it as submodule (vs. nested modules)).
</blockquote></details>

Done.
___
*[`docs/reference/src/module.adoc` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2691#-NS1eQnS2__6VkvAkK6J:-NS4wWoB1nhYgCaMBH4U:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5c1ed504c574c6445f7e7a2161804275636860b2/docs/reference/src/module.adoc#L36)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

This is confusing as there are ways to access them. Just not directly.
</blockquote></details>

Done.
___
*[`docs/reference/src/module.adoc` line 39 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2691#-NS1dqsR1H-Fm8B1p5JP:-NS4wg-G163fvA5HhbLS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5c1ed504c574c6445f7e7a2161804275636860b2/docs/reference/src/module.adoc#L39)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

link?
</blockquote></details>

Done.
___
*[`docs/reference/src/module.adoc` line 39 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2691#-NS1dtVQ-CtAe1l3wwMd:-NS4xfu68k-BM_MFOqmZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5c1ed504c574c6445f7e7a2161804275636860b2/docs/reference/src/module.adoc#L39)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

"or by referring to them using their relative/full path."
This is actually what you demonstrate below.

Please also add an example of `use` below (maybe with an additional struct B).
</blockquote></details>

Done.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2691)* status: all files reviewed, 5 unresolved discussions (waiting on @spapinistarkware)

___
*[`docs/reference/src/module.adoc` line 4 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2691#-NS68cDm2jDTF3pMrIxe:-NS68cDn0_a4qxS_pB8J:bfhrw1e) ([raw file](https://github.com/starkware-libs/cairo/blob/1a4da056f6ee32061251e5868828734b15610c21/docs/reference/src/module.adoc#L4)):*
> ```AsciiDoc
> 
> Crates and modules are used to organize code into separate namespaces, allowing for easier
> management of code and better code reusability. A module is a named container for
> ```

new paragraph for a main definition?



_Code quote:_
```AsciiDoc
A module
```
___
*[`docs/reference/src/module.adoc` line 12 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2691#-NS694PVE8u2kuPu3jNH:-NS694PVE8u2kuPu3jNI:b-g6gebk) ([raw file](https://github.com/starkware-libs/cairo/blob/1a4da056f6ee32061251e5868828734b15610c21/docs/reference/src/module.adoc#L12)):*
> ```AsciiDoc
> == Defining a Module
> A module can be defined in two ways: inlined in the current file or in a separate file.
> When a module is defined in a separate file, the file is located in a file located according
> ```

repetition.

suggestion for this sentence:
"the file location is determined by the module hierarchy"



_Code quote:_
```AsciiDoc
e file is located in a file located
```
___
*[`docs/reference/src/module.adoc` line 24 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2691#-NS69dM849cF6aas9tf7:-NS69dM849cF6aas9tf8:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/1a4da056f6ee32061251e5868828734b15610c21/docs/reference/src/module.adoc#L24)):*
> ```AsciiDoc
> }
> 
> // This is a module defined in `/bar.cairo`.
> ```





_Suggestion:_
```AsciiDoc
in `a/bar.cairo`
```
___
*[`docs/reference/src/module.adoc` line 37 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2691#-NS6A7i40wWmfen4Nk4B:-NS6A7i40wWmfen4Nk4C:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/1a4da056f6ee32061251e5868828734b15610c21/docs/reference/src/module.adoc#L37)):*
> ```AsciiDoc
> == Module Scope
> Items defined inside a module are directly available within the module.
> In particular, items defined at outer modules are not available in inner modules, even when inlined.
> ```

?



_Suggestion:_
```AsciiDoc
not directly available
```
___
*[`docs/reference/src/module.adoc` line 50 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2691#-NS6ALTk9sYn_onO_CUY:-NS6ALTk9sYn_onO_CUZ:b-mmsz9w) ([raw file](https://github.com/starkware-libs/cairo/blob/1a4da056f6ee32061251e5868828734b15610c21/docs/reference/src/module.adoc#L50)):*
> ```AsciiDoc
>         // A {}; // This is not allowed, because `A` is not in scope.
>         super::A {}; // This is allowed, because `super` refers to the parent module.
>         B {}; // This is allowed, because `B` is imported.
> ```

please align the comments for readability



_Code quote:_
```AsciiDoc
        // A {}; // This is not allowed, because `A` is not in scope.
        super::A {}; // This is allowed, because `super` refers to the parent module.
        B {}; // This is allowed, because `B` is imported.
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2691)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`docs/reference/src/module.adoc` line 12 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2691#-NS694PVE8u2kuPu3jNH:-NS6B50Y02bNdF049vAr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1a4da056f6ee32061251e5868828734b15610c21/docs/reference/src/module.adoc#L12)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

repetition.

suggestion for this sentence:
"the file location is determined by the module hierarchy"
</blockquote></details>

Done.

**Review by yuvalsw — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2691)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
