### PR TITLE
Conform result types earlier to resolve inconsistencies

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5406)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 33 of 34 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5406)* status: 32 of 34 files reviewed, 2 unresolved discussions (waiting on @mkaput and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/test_data/generics` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5406#-NvBtMou9jH34iFiME_o:-NvBtMou9jH34iFiME_p:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/25fe6080a3343c58d37c2899862f5ba20a219282/crates/cairo-lang-lowering/src/test_data/generics#L9)):*
> ```
> fn foo() {
>     immovable(5.foo(true));
> //immovable(MyTrait::foo(6, false));
> ```

?
___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 414 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5406#-NvBtzlZ1d3HRLCVrmp9:-NvBtzlZ1d3HRLCVrmpA:bc6o6vv) ([raw file](https://github.com/starkware-libs/cairo/blob/25fe6080a3343c58d37c2899862f5ba20a219282/crates/cairo-lang-semantic/src/diagnostic.rs#L414)):*
> ```XML
>             SemanticDiagnosticKind::ReturnTypeNotErrorPropagateType { return_ty } => {
>                 format!(
>                     r#"`?` can't be used in a function with return type "{}". Only `Option` and `Result` types support error propagation."#,
> ```

long line.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 34 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5406)* status: all files reviewed, 2 unresolved discussions (waiting on @mkaput and @yuvalsw)

**Review by mkaput — APPROVED** [review]
:+1: for LS changes

> Reviewed 33 of 34 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5406#-:-NvGYRv999rYxghS0OCs:brpuoaq)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5406)* status: 30 of 34 files reviewed, 2 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 414 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5406#-NvBtzlZ1d3HRLCVrmp9:-NvC9i3k6JIA0aROmD0T:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/25fe6080a3343c58d37c2899862f5ba20a219282/crates/cairo-lang-semantic/src/diagnostic.rs#L414)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

long line.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/test_data/generics` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5406#-NvBtMou9jH34iFiME_o:-NvC9tId3HNG9Dlz1zrt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/25fe6080a3343c58d37c2899862f5ba20a219282/crates/cairo-lang-lowering/src/test_data/generics#L9)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5406#-:-NvReNaDD5B7o0CXgXgR:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5406)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5406)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
