### PR TITLE
Add Poseidon.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2565)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2565)* status: 12 of 15 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @liorgold2)

___
*[`corelib/src/lib.cairo` line 397 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2565#-NR2VEqK0hIakXPLUDpt:-NR2VEqK0hIakXPLUDpu:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f90a093809991be5ff0dcb05c8ecb122f9006f51/corelib/src/lib.cairo#L397)):*
> ```Cairo
> // poseidon
> mod poseidon;
> use poseidon::Poseidon;
> ```





_Suggestion:_
```Cairo
// poseidon
mod poseidon;
use poseidon::Poseidon;

// Debug.
mod debug;
```
___
*[`corelib/src/poseidon.cairo` line 13 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2565#-NR2ZCbK8VI1WHIPuGwA:-NR2ZCbK8VI1WHIPuGwB:b-vzgaw6) ([raw file](https://github.com/starkware-libs/cairo/blob/6ed57ce7c85ca5ba6e7610f906ceeda84b6e2529/corelib/src/poseidon.cairo#L13)):*
> ```Cairo
> 
> // Hashes two elements and retrieves a single field element output.
> fn poseidon_hash(x: felt252, y: felt252) -> felt252 {
> ```

for now - i think this should be removed - and added once we know  how to write the full trait.



_Code quote:_
```Cairo
// Hashes two elements and retrieves a single field element output.
fn poseidon_hash(x: felt252, y: felt252) -> felt252 {
    // To distinguish between the use cases the capacity element is initialized to 2.
    let (r0, r1, r2) = poseidon(x, y, 2);
    r0
}
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/posiedon.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2565#-NR2YcNR4goRTUrYn7jy:-NR2YcNR4goRTUrYn7jz:b-nlutic) ([raw file](https://github.com/starkware-libs/cairo/blob/f90a093809991be5ff0dcb05c8ecb122f9006f51/crates/cairo-lang-sierra/src/extensions/modules/posiedon.rs#L35)):*
> ```XML
> pub struct HadesPermutationLibfunc {}
> impl NoGenericArgsGenericLibfunc for HadesPermutationLibfunc {
>     const STR_ID: &'static str = "poseidon";
> ```

maybe?



_Suggestion:_
```XML
hades_permutation
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/poseidon.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2565#-NR2YtwG2eqyE0qGRyr0:-NR2YtwG2eqyE0qGRyr1:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f90a093809991be5ff0dcb05c8ecb122f9006f51/crates/cairo-lang-sierra-to-casm/src/invocations/poseidon.rs#L29)):*
> ```XML
>         deref s1;
>         deref s2;
>         buffer(3) poseidon;
> ```





_Suggestion:_
```XML
buffer(5) poseidon;
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-to-casm/src/invocations/poseidon.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2565#-NR2YtwG2eqyE0qGRyr0:-NR2aNcT6e5fCgfIMpl4:bzc1oow) ([raw file](https://github.com/starkware-libs/cairo/blob/f90a093809991be5ff0dcb05c8ecb122f9006f51/crates/cairo-lang-sierra-to-casm/src/invocations/poseidon.rs#L29)):*
> ```XML
>         deref s1;
>         deref s2;
>         buffer(3) poseidon;
> ```

Why is it 2 for Pedersen?
https://github.com/starkware-libs/cairo/blob/9e42faf9cef6168a7e9a11fc4c9a1a25333277b9/crates/cairo-lang-sierra-to-casm/src/invocations/pedersen.rs#L32

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-to-casm/src/invocations/poseidon.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2565#-NR2YtwG2eqyE0qGRyr0:-NR2as4Z-IRvmb4h8ppL:brzhz03) ([raw file](https://github.com/starkware-libs/cairo/blob/f90a093809991be5ff0dcb05c8ecb122f9006f51/crates/cairo-lang-sierra-to-casm/src/invocations/poseidon.rs#L29)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why is it 2 for Pedersen?
https://github.com/starkware-libs/cairo/blob/9e42faf9cef6168a7e9a11fc4c9a1a25333277b9/crates/cairo-lang-sierra-to-casm/src/invocations/pedersen.rs#L32
</blockquote></details>

nvm, you are right.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2565)* status: 8 of 15 files reviewed, 4 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`corelib/src/lib.cairo` line 397 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2565#-NR2VEqK0hIakXPLUDpt:-NR2c1TTCY4uT0avTXKJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f90a093809991be5ff0dcb05c8ecb122f9006f51/corelib/src/lib.cairo#L397)):*
> ```Cairo
> // poseidon
> mod poseidon;
> use poseidon::Poseidon;
> ```

Done.
___
*[`corelib/src/poseidon.cairo` line 13 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2565#-NR2ZCbK8VI1WHIPuGwA:-NR2c1s98YdEN2VgR4Gx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6ed57ce7c85ca5ba6e7610f906ceeda84b6e2529/corelib/src/poseidon.cairo#L13)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

for now - i think this should be removed - and added once we know  how to write the full trait.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/posiedon.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2565#-NR2YcNR4goRTUrYn7jy:-NR2c-tz-ZG-JwyXibxI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f90a093809991be5ff0dcb05c8ecb122f9006f51/crates/cairo-lang-sierra/src/extensions/modules/posiedon.rs#L35)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe?
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 8 of 13 files at r1, 2 of 2 files at r3, 5 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2565)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
