### PR TITLE
Core Lib Documentation: `byte_array` module

### PR DESCRIPTION
**Pull request by TAdev0**

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6653)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @TAdev0)

___
*[`corelib/src/byte_array.cairo` line 2 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6653#-OBalZrz0w-TC3ae3CDZ:-OBalZrz0w-TC3ae3CD_:be56hm) ([raw file](https://github.com/starkware-libs/cairo/blob/2d469869694a5ead3e5afca967de18efe41f81e9/corelib/src/byte_array.cairo#L2)):*
> ```Cairo
> //! A dynamic, growable array of bytes where bytes are stored in multiples of 31 bytes,
> //! with a `felt252` pending word used for bytes that don't complete a full `bytes31` word.
> ```

This sounds like an implementation detail.

can be included - but shouldn't be the start.

Note that the `pub` part of the ByteArray does not include this info.



_Code quote:_
```Cairo
//! A dynamic, growable array of bytes where bytes are stored in multiples of 31 bytes,
//! with a `felt252` pending word used for bytes that don't complete a full `bytes31` word.
```

**Comment by TAdev0** [comment]
@orizi  just updated, moving this sentence right before the  `ByteArray` struct definition

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6653)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @TAdev0)

___
*[`corelib/src/byte_array.cairo` line 68 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6653#-OBjp9Ab7N6551LxNbDj:-OBjp9Ab7N6551LxNbDk:b8wv74l) ([raw file](https://github.com/starkware-libs/cairo/blob/b7d10d44c3109a068cf581029c0f1877ca44c915/corelib/src/byte_array.cairo#L68)):*
> ```Cairo
> 
> // TODO(yuval): don't allow creation of invalid ByteArray?
> /// A dynamic, growable array of bytes where bytes are stored in multiples of 31 bytes,
> ```

same implementation detail - should probably not be emphasized.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6653)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @TAdev0)

___
*[`corelib/src/byte_array.cairo` line 73 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6653#-OBkCj3q118SColtaip7:-OBkCj3q118SColtaip8:b36c33f) ([raw file](https://github.com/starkware-libs/cairo/blob/676189cd26aa806dba8e82944e636cf300ba5859/corelib/src/byte_array.cairo#L73)):*
> ```Cairo
> 
> // TODO(yuval): don't allow creation of invalid ByteArray?
> /// Cairo's `String` type.
> ```

it isn't - it is a bytearray - the string  literal but can be used with it - but it deliberately isn't a string.

**Pull request merged**
