### PR TITLE
add closing parenthesis to methods completion

### PR DESCRIPTION
**Pull request by dean-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6380)

### CODE REVIEW

**Review by dean-starkware — COMMENTED** [review]
fixes #5935   

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6380#-:-O6uU3q24L-vVTZ_QZG1:b-idh7tz)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, @orizi, and @piotmag769)

**Review by Draggu — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6380#-:-O6zT-JiErOQyfcIiwAN:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @gilbens-starkware, @mkaput, @orizi, and @piotmag769)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6380#-:-O6zailb5cpvbjZWlOKr:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @mkaput, @orizi, and @piotmag769)

**Review by piotmag769 — APPROVED** [review]

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6380)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @dean-starkware, and @mkaput)

___
*[`crates/cairo-lang-language-server/tests/e2e/completions.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6380#-O6zq3gJ0f2vqeHy_NXC:-O6zq3gJ0f2vqeHy_NXD:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2d67ffe5af00b28b0fc6891af27bc9659d3d6266/crates/cairo-lang-language-server/tests/e2e/completions.rs#L68)):*
> ```XML
>                     if let Some(text) = completion.insert_text {
>                         report.push_str(format!("Insert text: {}\n", text).as_str());
>                     }
> ```





_Suggestion:_
```XML
                    report.push_str(format!("Completion: {}\n", completion.label).as_str());
                    if let Some(text) = completion.insert_text {
                        report.push_str(format!("Insert text: {text}\n").as_str());
                    }
```

**Review by dean-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6380)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/tests/e2e/completions.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6380#-O6zq3gJ0f2vqeHy_NXC:-O796xp59802RAilpj54:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2d67ffe5af00b28b0fc6891af27bc9659d3d6266/crates/cairo-lang-language-server/tests/e2e/completions.rs#L68)):*
> ```XML
>                     if let Some(text) = completion.insert_text {
>                         report.push_str(format!("Insert text: {}\n", text).as_str());
>                     }
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6380#-:-O798bctETtQF3lKh9ds:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @mkaput)

**Pull request merged**
