### PR TITLE
Remove bool_eq.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2490)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2490#-:-NQZs5Ph0k_DwwLjk0Al:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2490)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`tests/e2e_test_data/libfuncs/bool` line 140 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2490#-NQZw8rc3Qw8a-EkR-q6:-NQZw8rc3Qw8a-EkR-q7:b-ggrnw4) ([raw file](https://github.com/starkware-libs/cairo/blob/6991bed56e55d90546eec6fdb4512bc33f42714d/tests/e2e_test_data/libfuncs/bool#L140)):*
> ```
> test::foo@0([0]: core::bool) -> (core::bool);
> 
> //! > ==========================================================================
> ```

extra deletion :)



_Code quote:_
```
//! > ==========================================================================
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2490)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2490)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
