### PR TITLE
LS: Initialize tracing in E2E tests

### PR DESCRIPTION
**Pull request by mkaput**
**Stack**:
- #5474
- #5525 ⬅
- #5531

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5525)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5525)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mkaput)

___
*[`crates/cairo-lang-language-server/tests/e2e/support/mod.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5525#-NxRpgupD2ozV2FW5VVb:-NxRpguq2rKyk5T4sq9i:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/477ab13b23ea79d250871abab58917906dd69117/crates/cairo-lang-language-server/tests/e2e/support/mod.rs#L41)):*
> ```XML
> pub(crate) use sandbox;
> 
> pub fn init_tracing() {
> ```

doc

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5525)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-language-server/tests/e2e/support/mod.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5525#-NxRpgupD2ozV2FW5VVb:-NxRxDtX62W_bQbYLNDR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/477ab13b23ea79d250871abab58917906dd69117/crates/cairo-lang-language-server/tests/e2e/support/mod.rs#L41)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5525#-:-NxS1D7HDiblbCAjSWI6:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Comment by mkaput** [comment]
Closing pull request: commit has gone away

**Pull request closed without merging**
