### PR TITLE
optimize_matches should skip matches where when input variable is used.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2451)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2451)* status: 0 of 13 files reviewed, 1 unresolved discussion

___
*[`crates/cairo-lang-lowering/src/optimizations/test_data/option` line 595 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2451#-NQPr8br4Tly0a_046CS:-NQPr8bs2Vo8eil2hkJd:bzn5bd) ([raw file](https://github.com/starkware-libs/cairo/blob/b56088300204a757b7fd476e9b1296339c6adf37/crates/cairo-lang-lowering/src/optimizations/test_data/option#L595)):*
> ```
> Statements:
> End:
>   Goto(blk2, {v1 -> v8})
> ```

Note that this is no longer ssa :(



_Code quote:_
```
v8
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
Since the optimization does not work for any of the OptionTrait function is it rather pointless :(

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2451#-:-NQVrggj6fKFvrZRZcRA:b90gojy)* status: 0 of 18 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 13 files at r1, 2 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2451)* status: 4 of 17 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2451#-NQZLU2f0TPf-dQa8GjG:-NQZLU2g66BE4sMWtvcR:bgnyn24) ([raw file](https://github.com/starkware-libs/cairo/blob/0bc793a0fcdd08092e9dd888937baea6710f288d/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L55)):*
> ```XML
>         statement_location: (BlockId, usize),
>     ) -> bool {
>         if let Statement::EnumConstruct(StatementEnumConstruct { variant, input, output }) = stmt {
> ```

Use let else
___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 56 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2451#-NQZLX5n-h6sxDmVqG83:-NQZLX5n-h6sxDmVqG84:bgnyn24) ([raw file](https://github.com/starkware-libs/cairo/blob/0bc793a0fcdd08092e9dd888937baea6710f288d/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L56)):*
> ```XML
>     ) -> bool {
>         if let Statement::EnumConstruct(StatementEnumConstruct { variant, input, output }) = stmt {
>             if let Some(ref mut candidate) = &mut info.candidate {
> ```

Use let else
___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2451#-NQZLZD_-i5SxYsJ2NMM:-NQZLZD_-i5SxYsJ2NMN:bje4qdp) ([raw file](https://github.com/starkware-libs/cairo/blob/0bc793a0fcdd08092e9dd888937baea6710f288d/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L57)):*
> ```XML
>         if let Statement::EnumConstruct(StatementEnumConstruct { variant, input, output }) = stmt {
>             if let Some(ref mut candidate) = &mut info.candidate {
>                 if *output == candidate.match_variable {
> ```

Realt return instead.
___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 161 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2451#-NQZMq0F5MT5MVYOJdir:-NQZMq0F5MT5MVYOJdis:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0bc793a0fcdd08092e9dd888937baea6710f288d/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L161)):*
> ```XML
> 
>                 if remapping.len() != expected_remappings {
>                     // Remapping is currently not suppored as it breaks SSA when we use the same
> ```





_Suggestion:_
```XML
supported
```
___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer_test.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2451#-NQZMviUC2TVBwl3uKbN:-NQZMviUC2TVBwl3uKbO:byp18fd) ([raw file](https://github.com/starkware-libs/cairo/blob/0bc793a0fcdd08092e9dd888937baea6710f288d/crates/cairo-lang-lowering/src/optimizations/match_optimizer_test.rs#L53)):*
> ```XML
>     let mut after = before.clone();
>     optimize_matches(&mut after);
>     // topological_sort(&mut after);
> ```

Remove

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2451)* status: 4 of 17 files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer_test.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2451#-NQZNaVrBwDzWtcRa71a:-NQZNaVrBwDzWtcRa71b:b-u34tkj) ([raw file](https://github.com/starkware-libs/cairo/blob/0bc793a0fcdd08092e9dd888937baea6710f288d/crates/cairo-lang-lowering/src/optimizations/match_optimizer_test.rs#L48)):*
> ```XML
>     apply_inlining(db, test_function.function_id, &mut before).unwrap();
>     before = lower_panics(db, test_function.concrete_function_id, &before).unwrap();
>     topological_sort(&mut before);
> ```

Now I can't see the removed blocks though. Why did you change this?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer_test.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2451#-NQZNaVrBwDzWtcRa71a:-NQZXx9xAMunRSlz4Vd-:b-nr109c) ([raw file](https://github.com/starkware-libs/cairo/blob/0bc793a0fcdd08092e9dd888937baea6710f288d/crates/cairo-lang-lowering/src/optimizations/match_optimizer_test.rs#L48)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Now I can't see the removed blocks though. Why did you change this?
</blockquote></details>

the  removed blocks should be in the topological_sort test that you didn't add. not here.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer_test.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2451#-NQZNaVrBwDzWtcRa71a:-NQZY1o2-riKd_pIKo1o:b-6a0svw) ([raw file](https://github.com/starkware-libs/cairo/blob/0bc793a0fcdd08092e9dd888937baea6710f288d/crates/cairo-lang-lowering/src/optimizations/match_optimizer_test.rs#L48)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

the  removed blocks should be in the topological_sort test that you didn't add. not here.
</blockquote></details>

it is hard to review the output if I apply  topological_sort as it changes the block numbers

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 2 of 14 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2451)* status: 3 of 17 files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 161 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2451#-NQZMq0F5MT5MVYOJdir:-NQaHT901pZcj9fX173W:bkbhgvd) ([raw file](https://github.com/starkware-libs/cairo/blob/0bc793a0fcdd08092e9dd888937baea6710f288d/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L161)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Fix again please:)

**Review by spapinistarkware — COMMENTED** [review]
Why doesn't it work for them?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2451#-:-NQaHjUdBu1Xqvy5nzYR:bykj107)* status: 3 of 17 files reviewed, all discussions resolved (waiting on @orizi)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2451)* status: 2 of 17 files reviewed, all discussions resolved (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 161 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2451#-NQZMq0F5MT5MVYOJdir:-NQeNa8f2XoHx8AfbvJZ:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/0bc793a0fcdd08092e9dd888937baea6710f288d/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L161)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Fix again please:)
</blockquote></details>

done

**Comment by ilyalesokhin-starkware** [comment]
The const for the panic is loaded between the enum_init and the match_enum.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 13 files at r1, 8 of 14 files at r3, 5 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2451#-:-NQegrTl4S9K423oxBuE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 13 files at r1, 1 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2451)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 20 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2451#-NQehK2YEnqKVPYDrBM3:-NQehK2YEnqKVPYDrBM4:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/3fac73602678ee01945a4ac49caf0f1c770a6846/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L20)):*
> ```XML
>     if !lowered.blocks.is_empty() {
>         // Apply the optimization until the lowered represantation is unchanged.
>         // loop {
> ```

?



_Code quote:_
```XML
        // loop {
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2451)* status: 16 of 17 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 20 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2451#-NQehK2YEnqKVPYDrBM3:-NQeri2t5c7bu3IylanH:b2llp2a) ([raw file](https://github.com/starkware-libs/cairo/blob/3fac73602678ee01945a4ac49caf0f1c770a6846/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L20)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
thanks.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2451)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
