### PR TITLE
Inline bottom up.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5174)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 11 of 65 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5174)* status: 11 of 65 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 295 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5174#-NrpMSXS7osWbzuxWrCj:-NrpMSXT0b_Z0gLTSKpu:b4sp1e1) ([raw file](https://github.com/starkware-libs/cairo/blob/154e455952f5efc9e6c2a35df8602da4c49e10c7/crates/cairo-lang-lowering/src/inline/mod.rs#L295)):*
> ```XML
>                     return self.inline_function(called_func, &stmt.inputs, &stmt.outputs);
>                 }
>             }
> ```

won't the feedback set already prevent this?



_Suggestion:_
```XML
            if let Some(called_func) = stmt.function.body(self.variables.db)? {
                if self.variables.db.priv_should_inline(called_func)? {
                    return self.inline_function(called_func, &stmt.inputs, &stmt.outputs);
                }
            }
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5174)* status: 11 of 65 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 295 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5174#-NrpMSXS7osWbzuxWrCj:-NrpOIrQCugaXgz04OES:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/154e455952f5efc9e6c2a35df8602da4c49e10c7/crates/cairo-lang-lowering/src/inline/mod.rs#L295)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

won't the feedback set already prevent this?
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 30 of 65 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5174)* status: 40 of 65 files reviewed, 1 unresolved discussion

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 24 of 65 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5174#-:-NrpSQS07LkzviPDylmi:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
