### PR TITLE
Fix builtin order.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1408)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1408)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/lowering/src/lower/implicits.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1408#-NJjKxCT7Wx6j_2ZIvAL:-NJjKxCT7Wx6j_2ZIvAM:b-kvzcs2) ([raw file](https://github.com/starkware-libs/cairo/blob/7c8e2ae722eaf87b035a26e5cc345f153eb13a18/crates/lowering/src/lower/implicits.rs#L97)):*
> ```XML
> 
>     // The following type need to precedence other types for compatibility with the StarkNet OS.
>     let precedence = ["RangeCheck", "Pedersen", "GasBuiltin"]
> ```

add some TODO at the very least make this not be recalculated for every sort.



_Code quote:_
```XML
    let semantic_db = db.upcast();

    // The following type need to precedence other types for compatibility with the StarkNet OS.
    let precedence = ["RangeCheck", "Pedersen", "GasBuiltin"]
        .iter()
        .map(|name| get_core_ty_by_name(semantic_db, name.into(), vec![]))
        .collect_vec();

    implicits_vec.sort_by_cached_key(|type_id| {
        if let Some(idx) = precedence.iter().position(|item| item == type_id) {
            return (idx, "".to_string());
        }

        (precedence.len(), type_id.format(semantic_db))
    });

    Ok(implicits_vec)
}
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1408#-:-NJjVxKn0sKRqGtEAzTn:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/lowering/src/db.rs` line 83 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1408#-NJjVf5mEwKNEPTJyIl3:-NJjVf5mEwKNEPTJyIl4:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/66ba8a9587e47d5dee0f037ad2ede07bf7cc5059/crates/lowering/src/db.rs#L83)):*
> ```XML
> }
> 
> pub fn init_lowering_group(db: &mut (dyn LoweringGroup + 'static)) {
> ```

doc



_Code quote:_
```XML
init_lowering_group
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1408)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/lowering/src/db.rs` line 83 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1408#-NJjVf5mEwKNEPTJyIl3:-NJjgbHw9cs_6AT9OlP3:b-seaikf) ([raw file](https://github.com/starkware-libs/cairo/blob/66ba8a9587e47d5dee0f037ad2ede07bf7cc5059/crates/lowering/src/db.rs#L83)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

all the init_*_group functions are not documented.

I'm not sure what documentation I could add (over the name of the function).
___
*[`crates/lowering/src/lower/implicits.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1408#-NJjKxCT7Wx6j_2ZIvAL:-NJjgZz5Bux7mfFFTPKh:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/7c8e2ae722eaf87b035a26e5cc345f153eb13a18/crates/lowering/src/lower/implicits.rs#L97)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add some TODO at the very least make this not be recalculated for every sort.
</blockquote></details>

done.



_Code quote (from crates/lowering/src/db.rs):_
```XML
init_lowering_group
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1408)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/lowering/src/db.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1408#-NJjltfh-kR9cZso822a:-NJjltfh-kR9cZso822b:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/66ba8a9587e47d5dee0f037ad2ede07bf7cc5059/crates/lowering/src/db.rs#L77)):*
> ```XML
>     #[salsa::invoke(crate::lower::implicits::function_scc)]
>     fn function_scc(&self, function_id: FreeFunctionId) -> Vec<FreeFunctionId>;
> ```





_Suggestion:_
```XML
    /// An array that sets the precedence of implicit types.
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1408#-:-NJjmllM1Cr-WTfZFcaP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 5 of 7 files at r1, 9 of 10 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1408)* status: 14 of 15 files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
