### PR TITLE
Add component dependency example test (mintable, depends on ownable a…

### PR DESCRIPTION
**Pull request by gilbens-starkware**
…nd erc20).

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4144)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4144)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @orizi and @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4144#-NfH44GQ5CftOCv0QcuX:-NfH44GQ5CftOCv0QcuY:bjf44aw) (no related file):*
change target branch.

___

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4144)* status: 4 of 9 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/mintable` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4144#-NfHBG_Q85_RRjmtECQR:-NfHBG_Q85_RRjmtECQS:b-d0z9qg) ([raw file](https://github.com/starkware-libs/cairo/blob/f976aeeb6d088f22103a4b410660a160f01186ae/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/mintable#L17)):*
> ```
> // The duplication is done since the expand test which also use this file is not aware to the rest of the crate.
> // The contract using these components is at the end of the file.
> // TODO(Gil): Add the capability to read multiple files in the test framework and remove this duplication.
> ```

Make shorter than 100.



_Code quote:_
```
// The ERC20 and Ownable components are duplicates of the ones in `with_erc20` and `with_ownable` files.
// The duplication is done since the expand test which also use this file is not aware to the rest of the crate.
// The contract using these components is at the end of the file.
// TODO(Gil): Add the capability to read multiple files in the test framework and remove this duplication.
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4144)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/cairo-lang-starknet/test_data/mintable.cairo` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4144#-NfHCBry-81H0CujnDgN:-NfHCBry-81H0CujnDgO:b-7ropln) ([raw file](https://github.com/starkware-libs/cairo/blob/f976aeeb6d088f22103a4b410660a160f01186ae/crates/cairo-lang-starknet/test_data/mintable.cairo#L3)):*
> ```Cairo
> use starknet::ContractAddress;
> 
> // The ERC20 and Ownable components are duplicates of the ones in `with_erc20` and `with_ownable` files.
> ```

ditto

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4144)* status: all files reviewed, 12 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/mintable` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4144#-NfH9xz0BUKM5493L-mG:-NfH9xz17vHM512O_U9w:b-l6mkjh) ([raw file](https://github.com/starkware-libs/cairo/blob/f976aeeb6d088f22103a4b410660a160f01186ae/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/mintable#L1)):*
> ```
> //! > Test expansion of a simple starknet contract with ownable component.
> ```

rename



_Code quote:_
```
 a simple starknet contract with ownable componen
```
___
*[`crates/cairo-lang-starknet/test_data/mintable.cairo` line 262 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4144#-NfHE0Jf4Q06rfxDvY8Z:-NfHE0Jf4Q06rfxDvY8_:bqx6ynr) ([raw file](https://github.com/starkware-libs/cairo/blob/f976aeeb6d088f22103a4b410660a160f01186ae/crates/cairo-lang-starknet/test_data/mintable.cairo#L262)):*
> ```Cairo
>     #[storage]
>     struct Storage {}
> ```

remove blank line
___
*[`crates/cairo-lang-starknet/test_data/mintable.cairo` line 263 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4144#-NfHFLID6et1cYwaEt8P:-NfHFLID6et1cYwaEt8Q:bgdygrw) ([raw file](https://github.com/starkware-libs/cairo/blob/f976aeeb6d088f22103a4b410660a160f01186ae/crates/cairo-lang-starknet/test_data/mintable.cairo#L263)):*
> ```Cairo
>     struct Storage {}
> ```

consider adding an event here
___
*[`crates/cairo-lang-starknet/test_data/mintable.cairo` line 270 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4144#-NfHEgCI3Gv8sZ-uWut_:-NfHEgCI3Gv8sZ-uWuta:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f976aeeb6d088f22103a4b410660a160f01186ae/crates/cairo-lang-starknet/test_data/mintable.cairo#L270)):*
> ```Cairo
>         impl Ownable: super::ownable::HasComponent<TContractState>,
>         impl ERC20: super::erc20::HasComponent<TContractState>,
>         impl TContractStateDrop: Drop<TContractState>
> ```





_Suggestion:_
```Cairo
+Drop<TC
```
___
*[`crates/cairo-lang-starknet/test_data/mintable.cairo` line 276 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4144#-NfHEtbF9nvQbc_oy1fX:-NfHEtbF9nvQbc_oy1fY:bhkt3sg) ([raw file](https://github.com/starkware-libs/cairo/blob/f976aeeb6d088f22103a4b410660a160f01186ae/crates/cairo-lang-starknet/test_data/mintable.cairo#L276)):*
> ```Cairo
>             let ownable_component = Ownable::get_component(self.get_contract());
>             ownable_component.validate_ownership();
>             let mut contract = self.get_contract_mut();
> ```

get once as mut, pass as snapshot to Ownable::get_component.
___
*[`crates/cairo-lang-starknet/test_data/mintable.cairo` line 302 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4144#-NfHF_9t8Z9YhhWmNxQN:-NfHF_9t8Z9YhhWmNxQO:b-x3d4hf) ([raw file](https://github.com/starkware-libs/cairo/blob/f976aeeb6d088f22103a4b410660a160f01186ae/crates/cairo-lang-starknet/test_data/mintable.cairo#L302)):*
> ```Cairo
>         erc20_storage: super::erc20::Storage,
>         #[substorage(v0)]
>         ownable_storage: super::ownable::Storage,
> ```

in a separate pr - can we have a test of a contract that doesn't suffice the dependency?
___
*[`crates/cairo-lang-starknet/test_data/mintable.cairo` line 322 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4144#-NfHFrbzAw_w157G0Gcq:-NfHFrbzAw_w157G0Gcr:b-cov0ap) ([raw file](https://github.com/starkware-libs/cairo/blob/f976aeeb6d088f22103a4b410660a160f01186ae/crates/cairo-lang-starknet/test_data/mintable.cairo#L322)):*
> ```Cairo
>     impl ERC20Impl = super::erc20::IERC20<ContractState>;
> 
>     impl ERC20Helper = super::erc20::ERC20HelperImpl<ContractState>;
> ```

why do you need this helper
___
*[`crates/cairo-lang-starknet/test_data/mintable.cairo` line 331 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4144#-NfHGSv1BTo-72qQeg-4:-NfHGSv1BTo-72qQeg-5:b-689ha1) ([raw file](https://github.com/starkware-libs/cairo/blob/f976aeeb6d088f22103a4b410660a160f01186ae/crates/cairo-lang-starknet/test_data/mintable.cairo#L331)):*
> ```Cairo
>     #[abi(embed_v0)]
>     impl MintImpl = super::mintable::Mint<ContractState>;
> ```

for completeness - can you add an abi(embed_v0) impl here with some external function?
___
*[`crates/cairo-lang-starknet/test_data/mintable.cairo` line 334 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4144#-NfHGOIk3IKq-w3MKB24:-NfHGOIl0P3ZvBBp0Iyn:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f976aeeb6d088f22103a4b410660a160f01186ae/crates/cairo-lang-starknet/test_data/mintable.cairo#L334)):*
> ```Cairo
>     #[abi(per_item)]
>     #[generate_trait]
>     impl Impl of Trait {
> ```





_Suggestion:_
```Cairo
impl CtorImpl of CtorTrait {
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4144)* status: 13 of 15 files reviewed, 13 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/cairo-lang-starknet/test_data/ownable_erc20.cairo` line 2 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4144#-NfIYHLj0QkGDZFpoPSS:-NfIYHLj0QkGDZFpoPST:byix0t7) ([raw file](https://github.com/starkware-libs/cairo/blob/35c97d2f65c48e5492fe09fb3d10c49002a5f28b/crates/cairo-lang-starknet/test_data/ownable_erc20.cairo#L2)):*
> ```Cairo
> // The ERC20 and Ownable components are duplicates of the ones in `with_erc20` and `with_ownable` files.
> // The duplication is done since the expand test which also use this file is not aware to the rest of the crate.
> ```

Make shorter than 100 chars.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4144)* status: 4 of 15 files reviewed, 10 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/mintable` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4144#-NfHBG_Q85_RRjmtECQR:-NfIToRC4AqO151ZymC6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f976aeeb6d088f22103a4b410660a160f01186ae/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/mintable#L17)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Make shorter than 100.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/test_data/mintable.cairo` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4144#-NfHCBry-81H0CujnDgN:-NfITq0o21Ak7BvHBMCH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f976aeeb6d088f22103a4b410660a160f01186ae/crates/cairo-lang-starknet/test_data/mintable.cairo#L3)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/test_data/mintable.cairo` line 263 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4144#-NfHFLID6et1cYwaEt8P:-NfITzy38odxJCyVVks1:b3e0ay9) ([raw file](https://github.com/starkware-libs/cairo/blob/f976aeeb6d088f22103a4b410660a160f01186ae/crates/cairo-lang-starknet/test_data/mintable.cairo#L263)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

consider adding an event here
</blockquote></details>

What's the difference from the ownable example?
___
*[`crates/cairo-lang-starknet/test_data/mintable.cairo` line 276 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4144#-NfHEtbF9nvQbc_oy1fX:-NfIUO4fBoZ_DpE8AdZN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f976aeeb6d088f22103a4b410660a160f01186ae/crates/cairo-lang-starknet/test_data/mintable.cairo#L276)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

get once as mut, pass as snapshot to Ownable::get_component.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/test_data/mintable.cairo` line 302 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4144#-NfHF_9t8Z9YhhWmNxQN:-NfIURbH3_o97ZfrDR6V:blmjnuy) ([raw file](https://github.com/starkware-libs/cairo/blob/f976aeeb6d088f22103a4b410660a160f01186ae/crates/cairo-lang-starknet/test_data/mintable.cairo#L302)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

in a separate pr - can we have a test of a contract that doesn't suffice the dependency?
</blockquote></details>

Checked and it is looking good. I'll add it later.
___
*[`crates/cairo-lang-starknet/test_data/mintable.cairo` line 322 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4144#-NfHFrbzAw_w157G0Gcq:-NfIUjJCC2YPY3RN-Lg2:b-gptfjd) ([raw file](https://github.com/starkware-libs/cairo/blob/f976aeeb6d088f22103a4b410660a160f01186ae/crates/cairo-lang-starknet/test_data/mintable.cairo#L322)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

why do you need this helper
</blockquote></details>

We don't. done.
___
*[`crates/cairo-lang-starknet/test_data/mintable.cairo` line 331 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4144#-NfHGSv1BTo-72qQeg-4:-NfIWp23-5RAm1umIJmk:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f976aeeb6d088f22103a4b410660a160f01186ae/crates/cairo-lang-starknet/test_data/mintable.cairo#L331)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

for completeness - can you add an abi(embed_v0) impl here with some external function?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/test_data/mintable.cairo` line 334 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4144#-NfHGOIk3IKq-w3MKB24:-NfIVD7b7zx0VRbcL9EJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f976aeeb6d088f22103a4b410660a160f01186ae/crates/cairo-lang-starknet/test_data/mintable.cairo#L334)):*
> ```Cairo
>     #[abi(per_item)]
>     #[generate_trait]
>     impl Impl of Trait {
> ```

Done.
___
*[`crates/cairo-lang-starknet/test_data/ownable_erc20.cairo` line 2 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4144#-NfIYHLj0QkGDZFpoPSS:-NfIZITv4XG2iF8Gr1DO:bfgxtmy) ([raw file](https://github.com/starkware-libs/cairo/blob/35c97d2f65c48e5492fe09fb3d10c49002a5f28b/crates/cairo-lang-starknet/test_data/ownable_erc20.cairo#L2)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Make shorter than 100 chars.
</blockquote></details>

Done in the previous pr. Rebase bug.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4144#-:-NfIcVanATbzoQqQIRXy:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4144#-:-NfJeEnV5sDVeLWmVXyq:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by orizi — COMMENTED** [review]
> Reviewed 10 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4144)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4144)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Pull request merged**
