### PR TITLE
Add a debug print libfunc

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1654)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1654)* status: 4 of 9 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1654#-NL06MtB2COR1Co2SIFm:-NL06MtB2COR1Co2SIFn:b-s8buq3) (no related file):*
i would assume the next step would be to print in the lambda class run.rs file hint processor.

won't it would be easier to only allow printing shortstrings (or felts) for now, and considering these longer options to be added later?
(since actually printing an array from the hint processor is gonna be harder, and the shortstrings would be good enough for a first stage).

___
___
*[`crates/cairo-lang-sierra/src/extensions/modules/debug.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1654#-NL05mnH3SJS6C5I-L5A:-NL05mnH3SJS6C5I-L5B:b2ni2nk) ([raw file](https://github.com/starkware-libs/cairo/blob/f0f3f26d3dbf60655cb475ffd30e72eb3ef9c927/crates/cairo-lang-sierra/src/extensions/modules/debug.rs#L16)):*
> ```XML
> }
> 
> /// Libfunc for comparing u128s` equality.
> ```

fix



_Code quote:_
```XML
/// Libfunc for comparing u128s` equality.
```

**Review by orizi — COMMENTED** [review]
> Reviewed 5 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1654)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1654)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1654#-NL06MtB2COR1Co2SIFm:-NL071az8k7pVIHpCwCd:b-uonvj2) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i would assume the next step would be to print in the lambda class run.rs file hint processor.

won't it would be easier to only allow printing shortstrings (or felts) for now, and considering these longer options to be added later?
(since actually printing an array from the hint processor is gonna be harder, and the shortstrings would be good enough for a first stage).
</blockquote></details>

1. Yes.
2. Why would it be more difficult?

___

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1654)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/debug.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1654#-NL05mnH3SJS6C5I-L5A:-NL07LveDU3TzdJphcUh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f0f3f26d3dbf60655cb475ffd30e72eb3ef9c927/crates/cairo-lang-sierra/src/extensions/modules/debug.rs#L16)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1654)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1654#-NL06MtB2COR1Co2SIFm:-NL07YwV3TN-JNvW_SsI:b-h4st1x) (no related file):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

1. Yes.
2. Why would it be more difficult?
</blockquote></details>

because i'm not sure yet what you are going to have as an input to the hint - but it would be in casm level, not sierra level.

___

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1654)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1654#-NL06MtB2COR1Co2SIFm:-NL0DF528QnUIKux5CDQ:b-vnw8jm) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

because i'm not sure yet what you are going to have as an input to the hint - but it would be in casm level, not sierra level.
</blockquote></details>

The pointer to the memory

___

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1654)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1654#-NL06MtB2COR1Co2SIFm:-NL0EnnX5vGleO09USlg:b7rj99d) (no related file):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

The pointer to the memory
</blockquote></details>

this would still probably be more annoying than strictly needed, but ok.

___

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1654)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1654#-:-NL0F3KaAWOOLlEF62wE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
