### PR TITLE
Add executable functions as entry points of tests compilation

### PR DESCRIPTION
**Pull request by maciektr**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5699)

### CODE REVIEW

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5699#-:-NzRsgG91QG0vYxE1fVy:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5699)* status: all files reviewed, 1 unresolved discussion (waiting on @maciektr)

___
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5699#-NzS5QMm24dIdoYg9pqj:-NzS5QMn0fFSJ4nuc71M:bfvpstq) ([raw file](https://github.com/starkware-libs/cairo/blob/6bdcdb9874f469cc85199280d5c0dda191fd66f1/crates/cairo-lang-test-plugin/src/lib.rs#L94)):*
> ```XML
>         db.get_sierra_program_for_functions(
>             chain!(
>                 executable_functions.clone().into_keys(),
> ```

Isn't it duplicating the test functions as well?

**Comment by maciektr** [comment]
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5699#-NzS5QMm24dIdoYg9pqj:-NzSAB3x1lhHssIW97zK:b-f1b5w4) ([raw file](https://github.com/starkware-libs/cairo/blob/6bdcdb9874f469cc85199280d5c0dda191fd66f1/crates/cairo-lang-test-plugin/src/lib.rs#L94)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Isn't it duplicating the test functions as well?
</blockquote></details>

Not really, as test plugin we use does not define executables yet https://github.com/starkware-libs/cairo/blob/43c61c21ee161d555e52ba6cc898f476ad78b3a5/crates/cairo-lang-test-plugin/src/plugin.rs#L14

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5699)* status: all files reviewed, 1 unresolved discussion (waiting on @maciektr)

___
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5699#-NzS5QMm24dIdoYg9pqj:-NzSAaF90Y_DUnb2XknJ:b-lg4dnu) ([raw file](https://github.com/starkware-libs/cairo/blob/6bdcdb9874f469cc85199280d5c0dda191fd66f1/crates/cairo-lang-test-plugin/src/lib.rs#L94)):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

Not really, as test plugin we use does not define executables yet https://github.com/starkware-libs/cairo/blob/43c61c21ee161d555e52ba6cc898f476ad78b3a5/crates/cairo-lang-test-plugin/src/plugin.rs#L14
</blockquote></details>

so add a TODO over `all_tests` to remove it when it is used.

**Review by maciektr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5699)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5699#-NzS5QMm24dIdoYg9pqj:-NzSC2Cy3ysz-nHuE21u:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6bdcdb9874f469cc85199280d5c0dda191fd66f1/crates/cairo-lang-test-plugin/src/lib.rs#L94)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

so add a TODO over `all_tests` to remove it when it is used.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5699)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @maciektr)

___
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 93 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5699#-NzSDJLW1LhvsGutOort:-NzSDJLW1LhvsGutOoru:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7a094a3ece516976b9f4a66a5541e7029c6cec2f/crates/cairo-lang-test-plugin/src/lib.rs#L93)):*
> ```XML
>     let SierraProgramWithDebug { program: sierra_program, debug_info } = Arc::unwrap_or_clone(
>         db.get_sierra_program_for_functions(
>             // TODO(all_tests): Remove test entrypoints after migration to executable attr.
> ```





_Suggestion:_
```XML
            // TODO(maciektr): Remove test entrypoints after migration to executable attr.
```

**Comment by maciektr** [comment]
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 93 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5699#-NzSDJLW1LhvsGutOort:-NzSEWq5Es3rSx2093G6:bgunkd4) ([raw file](https://github.com/starkware-libs/cairo/blob/7a094a3ece516976b9f4a66a5541e7029c6cec2f/crates/cairo-lang-test-plugin/src/lib.rs#L93)):*
> ```XML
>     let SierraProgramWithDebug { program: sierra_program, debug_info } = Arc::unwrap_or_clone(
>         db.get_sierra_program_for_functions(
>             // TODO(all_tests): Remove test entrypoints after migration to executable attr.
> ```

:man_facepalming: Sorry, I see what you meant by the "all_tests" now :laughing:

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5699#-:-NzSFKUFEYH82yZ-TtCe:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @maciektr)

**Pull request merged**
