### PR TITLE
Add a borrow checker test that gives a bad location.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3641)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3641)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 603 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3641#-N_-2bC49HgHeotJYkSf:-N_-2bC49HgHeotJYkSg:b-jv1vg7) ([raw file](https://github.com/starkware-libs/cairo/blob/2c8d64555bc4df038dfde5a0094819e26c2673e5/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L603)):*
> ```
>         self.a = Default::default();
>     }
> }
> ```

I think this should compile in the future.
But I'm not quite sure what test case to use instead.



_Code quote:_
```
fn foo(ref self: MyStruct) {
    if self.b == 0 {
        self.a = Default::default();
    }
}
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3641)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 603 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3641#-N_-2bC49HgHeotJYkSf:-N_-3H58D5nb4dH2rSND:b-1yj4je) ([raw file](https://github.com/starkware-libs/cairo/blob/2c8d64555bc4df038dfde5a0094819e26c2673e5/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L603)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I think this should compile in the future.
But I'm not quite sure what test case to use instead.
</blockquote></details>

this indeed should compile - the `usage check` algorithm should auto-restructure `self`.
what do you actually want to test?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3641)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 603 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3641#-N_-2bC49HgHeotJYkSf:-N_-3fVc9fEAcFfvFrA9:b-q12gak) ([raw file](https://github.com/starkware-libs/cairo/blob/2c8d64555bc4df038dfde5a0094819e26c2673e5/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L603)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this indeed should compile - the `usage check` algorithm should auto-restructure `self`.
what do you actually want to test?
</blockquote></details>

I want to check a usage location inside the StructRecomposer see the other comment.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 603 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3641#-N_-2bC49HgHeotJYkSf:-N_-3wHk0RIy2AcdcPFg:b-x8rsh7) ([raw file](https://github.com/starkware-libs/cairo/blob/2c8d64555bc4df038dfde5a0094819e26c2673e5/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L603)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I want to check a usage location inside the StructRecomposer see the other comment.
</blockquote></details>

btw, the problem is that `self` is auto-restructured twice.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3641)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 603 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3641#-N_-2bC49HgHeotJYkSf:-N_-5-pJAl8avOhNcaPE:bxe6zh7) ([raw file](https://github.com/starkware-libs/cairo/blob/2c8d64555bc4df038dfde5a0094819e26c2673e5/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L603)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

btw, the problem is that `self` is auto-restructured twice.
</blockquote></details>

how about just: `self.a.destroy()` - what would happen?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 603 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3641#-N_-2bC49HgHeotJYkSf:-N_-6TPx6unao7xVjhTZ:b-8xdojg) ([raw file](https://github.com/starkware-libs/cairo/blob/2c8d64555bc4df038dfde5a0094819e26c2673e5/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L603)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

how about just: `self.a.destroy()` - what would happen?
</blockquote></details>

What is destroy?

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3641)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/test.rs` line 41 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3641#-N_-AHWODLn_rrw3ljQ9:-N_-AHWODLn_rrw3ljQA:b-9werkh) ([raw file](https://github.com/starkware-libs/cairo/blob/c66c87165794153e9c05190dabd23973f6d83f83/crates/cairo-lang-lowering/src/borrow_check/test.rs#L41)):*
> ```XML
>     } else {
>         "".into()
>     };
> ```

this is to support the diagnostics case?



_Code quote:_
```XML
    let lowering = if let Ok(lowered) =
        db.priv_function_with_body_lowering(function_id.function_with_body_id(db))
    {
        format!("{:?}", lowered.debug(&LoweredFormatter { db, variables: &lowered.variables }))
    } else {
        "".into()
    };
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/borrow_check/test.rs` line 41 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3641#-N_-AHWODLn_rrw3ljQ9:-N_-AVNwAJGlR5EsIVxN:bb7sa0c) ([raw file](https://github.com/starkware-libs/cairo/blob/c66c87165794153e9c05190dabd23973f6d83f83/crates/cairo-lang-lowering/src/borrow_check/test.rs#L41)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is to support the diagnostics case?
</blockquote></details>

yes.

**Pull request merged**
