### PR TITLE
Fix snapshot semantics

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2196)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2196)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/snapshot` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2196#-NOe9gb05Jf5oQ3l5o62:-NOe9gb05Jf5oQ3l5o63:b-jmepyd) ([raw file](https://github.com/starkware-libs/cairo/blob/f3c5bb62083f050a696fd515d29303ecce6e0c31/crates/cairo-lang-semantic/src/expr/test_data/snapshot#L42)):*
> ```
> //! > module_code
> struct A {
>     a: Array::<felt>,
> ```

unused



_Code quote:_
```
//! > module_code
struct A {
    a: Array::<felt>,
    b: felt,
}
fn bar(a: @Array::<felt>, b: @felt) {
}
```

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2196#-:-NOe9pCrDwY56TH0gSy4:bnfp4nl)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2196)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/snapshot` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2196#-NOe9gb05Jf5oQ3l5o62:-NOeAPmx23tClOp250p8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f3c5bb62083f050a696fd515d29303ecce6e0c31/crates/cairo-lang-semantic/src/expr/test_data/snapshot#L42)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

unused
</blockquote></details>

Done.

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2196)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2196)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2196)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
