### PR TITLE
Added redeposit as an extra store_temp piggy-back.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #4778
- #4727
- #4726 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4726)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 634 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4726#-NnmGy_hA_0ohMA4-dZ2:-NnmGy_hA_0ohMA4-dZ3:biyozug) ([raw file](https://github.com/starkware-libs/cairo/blob/503b2864d97dd410d9dec5add93524a0a22eba45/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L634)):*
> ```XML
> 
>     /// Adds lightweight calls to libfuncs when performing a store_temp on a variable already stored
>     /// on temp. This is currently used only for adding the `redeposit_gas` libfunc.
> ```

what is "stored on temp"?



_Code quote:_
```XML
    /// Adds lightweight calls to libfuncs when performing a store_temp on a variable already stored
    /// on temp. This is currently used only for adding the `redeposit_gas` libfunc.
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 7 of 48 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4726)* status: 7 of 48 files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4726)* status: 7 of 48 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 634 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4726#-NnmGy_hA_0ohMA4-dZ2:-Nnme8NRDy75agLUB9ed:bc69agg) ([raw file](https://github.com/starkware-libs/cairo/blob/503b2864d97dd410d9dec5add93524a0a22eba45/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L634)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what is "stored on temp"?
</blockquote></details>

variable can be deffered or stored. stored can be either local or temp.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 16 of 49 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4726)* status: 16 of 49 files reviewed, 1 unresolved discussion (waiting on @orizi)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 648 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4726#-NnmjvNd6WPl0W3W8zQ-:-NnmjvNd6WPl0W3W8zQ0:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d0b8757737f61a48f4bbc22364db385d493b66ef/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L648)):*
> ```XML
>     }
> 
>     /// Adds re-deposit gas libfunc for the given variable if relevant.
> ```





_Suggestion:_
```XML
   /// Adds a call to the re-deposit gas libfunc for the given variable if relevant.
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4726)* status: 16 of 49 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 634 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4726#-NnmGy_hA_0ohMA4-dZ2:-NnmpHZ18yb06vgnBrGB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/503b2864d97dd410d9dec5add93524a0a22eba45/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L634)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

stored as temp?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 648 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4726#-NnmjvNd6WPl0W3W8zQ-:-NnmpOoH6k3twL1yI4Mt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d0b8757737f61a48f4bbc22364db385d493b66ef/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L648)):*
> ```XML
>     }
> 
>     /// Adds re-deposit gas libfunc for the given variable if relevant.
> ```

Done.

**Pull request merged**
