### PR TITLE
Handle arrays in run_function()

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2910)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2907** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2907" target="_blank">Graphite</a> 
    * **PR #2908** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2908" target="_blank">Graphite</a> 
      * **PR #2909** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2909" target="_blank">Graphite</a> 
        * **PR #2910** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2910" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2910?utm_source=stack-comment).

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2910#-:-NTeHdNp1EnPWRf86KhP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Comment by spapinistarkware** [comment]
@spapinistarkware queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2910).

**Comment by spapinistarkware** [comment]
[Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2910) failed to merge this pull request for an unknown reason. Try your merge again, or report a bug if you see this consistently.

**Pull request merged**
