### PR TITLE
Optimizing out extra created blocks.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:c589fdad

---

**Stack**:
- #1909
- #1908
- #1895 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 306 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1895#-NMcWU2JB4tBBi9DfvpG:-NMcWU2JB4tBBi9DfvpH:b-cgud5o) ([raw file](https://github.com/starkware-libs/cairo/blob/b15e95932ab09ad7370fbeafe0ec8120fe398779/crates/cairo-lang-lowering/src/inline/mod.rs#L306)):*
> ```XML
>     /// Inlines the given function, with the given input and outputs variables.
>     ///
>     /// Returns the block_id that should be called instead of the function.
> ```

fix documentation.



_Code quote:_
```XML
   /// Returns the block_id that should be called instead of the function.
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 52 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1895)* status: 1 of 52 files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 332 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1895#-NMcXNq615VS1IW_TeXh:-NMcXNq7Dj8DbtHsKryB:bvlnayl) ([raw file](https://github.com/starkware-libs/cairo/blob/b15e95932ab09ad7370fbeafe0ec8120fe398779/crates/cairo-lang-lowering/src/inline/mod.rs#L332)):*
> ```XML
>                     outputs.iter().cloned()
>                 )
>             )),
> ```

I don't understand what's going on here.

lowered.blocks[root_block_id].inputs and inputs are from different functions and can overlap.

+ fix comment.



_Code quote:_
```XML
            renamed_vars: HashMap::<VariableId, VariableId>::from_iter(chain!(
                izip!(lowered.blocks[root_block_id].inputs.iter().cloned(), inputs.iter().cloned()),
                izip!(
                    extract_matches!(&root_block.end, FlatBlockEnd::Return).iter().cloned(),
                    outputs.iter().cloned()
                )
            )),
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1895)* status: 1 of 52 files reviewed, 3 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 377 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1895#-NMcXdCeEgN65nDpvFNf:-NMcXdCeEgN65nDpvFNg:b1sggmn) ([raw file](https://github.com/starkware-libs/cairo/blob/b15e95932ab09ad7370fbeafe0ec8120fe398779/crates/cairo-lang-lowering/src/inline/mod.rs#L377)):*
> ```XML
> ) -> Maybe<()> {
>     let lowering_builder = LoweringContextBuilder::new(db, function_id)?;
>     let mut inlining_bound = 10;
> ```

please do this in a seperate PR.



_Code quote:_
```XML
  let mut inlining_bound = 10;
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1895)* status: 1 of 52 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 306 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1895#-NMcWU2JB4tBBi9DfvpG:-NMcY_RM88A7fvkMpsqo:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b15e95932ab09ad7370fbeafe0ec8120fe398779/crates/cairo-lang-lowering/src/inline/mod.rs#L306)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

fix documentation.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 332 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1895#-NMcXNq615VS1IW_TeXh:-NMcYyvHDOkFUivZGl_e:b-3jyaw0) ([raw file](https://github.com/starkware-libs/cairo/blob/b15e95932ab09ad7370fbeafe0ec8120fe398779/crates/cairo-lang-lowering/src/inline/mod.rs#L332)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't understand what's going on here.

lowered.blocks[root_block_id].inputs and inputs are from different functions and can overlap.

+ fix comment.
</blockquote></details>

since we replace the names of all params to new params,
if we translate the input names, and the output names, there won't be overlaps here.
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 377 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1895#-NMcXdCeEgN65nDpvFNf:-NMcY0BQ8bqYTKYPCcnu:b-giyzrp) ([raw file](https://github.com/starkware-libs/cairo/blob/b15e95932ab09ad7370fbeafe0ec8120fe398779/crates/cairo-lang-lowering/src/inline/mod.rs#L377)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

please do this in a seperate PR.
</blockquote></details>

can't - the change caused this to do just a single inlining iteration - this breaks a lot without it.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 332 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1895#-NMcXNq615VS1IW_TeXh:-NMccRoaEMnUgIP9o5Fv:b-cur6p2) ([raw file](https://github.com/starkware-libs/cairo/blob/b15e95932ab09ad7370fbeafe0ec8120fe398779/crates/cairo-lang-lowering/src/inline/mod.rs#L332)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

since we replace the names of all params to new params,
if we translate the input names, and the output names, there won't be overlaps here.
</blockquote></details>

What happens if you remap to variables from extract_matches!(&root_block.end, FlatBlockEnd::Return) to the same variable in
outputs?



_Code quote:_
```XML
 outputs
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1895)* status: 1 of 52 files reviewed, 3 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 365 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1895#-NMccpT1CsljxuvE8XUZ:-NMccpT1CsljxuvE8XU_:b-5tk5oh) ([raw file](https://github.com/starkware-libs/cairo/blob/4fae05ec476bcad162e0da1489172cd7d012eba6/crates/cairo-lang-lowering/src/inline/mod.rs#L365)):*
> ```XML
>         }
>         for stmt in &root_block.statements {
>             statements.push(mapper.rebuild_statement(stmt));
> ```

can you call rewrite?



_Suggestion:_
```XML
 rewrite(mapper.rebuild_statement(stmt, statements)?
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 332 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1895#-NMcXNq615VS1IW_TeXh:-NMcdn228KYYjDN8QBxa:b-kq7e3) ([raw file](https://github.com/starkware-libs/cairo/blob/b15e95932ab09ad7370fbeafe0ec8120fe398779/crates/cairo-lang-lowering/src/inline/mod.rs#L332)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

What happens if you remap to variables from extract_matches!(&root_block.end, FlatBlockEnd::Return) to the same variable in
outputs?
</blockquote></details>

add a test

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 24 of 52 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1895)* status: 26 of 52 files reviewed, 3 unresolved discussions (waiting on @orizi and @spapinistarkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 5 of 52 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1895)* status: 31 of 52 files reviewed, 3 unresolved discussions (waiting on @orizi and @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1895)* status: 31 of 52 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 332 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1895#-NMcXNq615VS1IW_TeXh:-NMcj4LEAiRrHYGUKU5o:bhssx3o) ([raw file](https://github.com/starkware-libs/cairo/blob/b15e95932ab09ad7370fbeafe0ec8120fe398779/crates/cairo-lang-lowering/src/inline/mod.rs#L332)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

add a test
</blockquote></details>

yeah - thought about it myself - probably closing this pr now and just handling in sierra gen.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1895)* status: 31 of 52 files reviewed, 3 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 332 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1895#-NMcXNq615VS1IW_TeXh:-NMcm-4K1jHYZJJsuBxN:bovns7f) ([raw file](https://github.com/starkware-libs/cairo/blob/b15e95932ab09ad7370fbeafe0ec8120fe398779/crates/cairo-lang-lowering/src/inline/mod.rs#L332)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

yeah - thought about it myself - probably closing this pr now and just handling in sierra gen.
</blockquote></details>

Maybe it is not possible?

I don't think it is  a bad PR.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 52 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1895)* status: 31 of 52 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 329 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1895#-NMczYTp-84nMKtbOEvD:-NMczYTp-84nMKtbOEvE:b-vx8i6c) ([raw file](https://github.com/starkware-libs/cairo/blob/4fae05ec476bcad162e0da1489172cd7d012eba6/crates/cairo-lang-lowering/src/inline/mod.rs#L329)):*
> ```XML
>                 izip!(lowered.blocks[root_block_id].inputs.iter().cloned(), inputs.iter().cloned()),
>                 izip!(
>                     extract_matches!(&root_block.end, FlatBlockEnd::Return).iter().cloned(),
> ```

I think the root block may end with Unreachable.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1895)* status: 31 of 52 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 329 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1895#-NMczYTp-84nMKtbOEvD:-NMczgX6CCyDNqKbLb6y:bvt24f7) ([raw file](https://github.com/starkware-libs/cairo/blob/4fae05ec476bcad162e0da1489172cd7d012eba6/crates/cairo-lang-lowering/src/inline/mod.rs#L329)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I think the root block may end with Unreachable.
</blockquote></details>

Or is it checked somewhere before?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1895)* status: 31 of 52 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 377 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1895#-NMcXdCeEgN65nDpvFNf:-NMd0DU71vb_9ggRGmYV:bwopoz7) ([raw file](https://github.com/starkware-libs/cairo/blob/b15e95932ab09ad7370fbeafe0ec8120fe398779/crates/cairo-lang-lowering/src/inline/mod.rs#L377)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can't - the change caused this to do just a single inlining iteration - this breaks a lot without it.
</blockquote></details>

I thought this algorithm is recursive. Why do we need to iterate here? This makes it quadratic.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1895)* status: 31 of 52 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 332 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1895#-NMcXNq615VS1IW_TeXh:-NMd0i1R9Vyg563n4cjD:b-y4hfhq) ([raw file](https://github.com/starkware-libs/cairo/blob/b15e95932ab09ad7370fbeafe0ec8120fe398779/crates/cairo-lang-lowering/src/inline/mod.rs#L332)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

It's not a bad PR, and I'd rather have it here than in sierragen. The best thing would probably be to rename variables in the caller as well, but for now I think it's ok to inline only function that return unique vars. Just check it in loewring diagnostics.
</blockquote></details>

this is more complex than that - inlining the identity function is already an issue here.
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 377 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1895#-NMcXdCeEgN65nDpvFNf:-NMd0uHg2-kLlx5ksOd3:b-pgv38u) ([raw file](https://github.com/starkware-libs/cairo/blob/b15e95932ab09ad7370fbeafe0ec8120fe398779/crates/cairo-lang-lowering/src/inline/mod.rs#L377)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I thought this algorithm is recursive. Why do we need to iterate here? This makes it quadratic.
</blockquote></details>

it is no longer recursive here.
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 329 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1895#-NMczYTp-84nMKtbOEvD:-NMd0bA59osxbftGDG6g:bvpddhz) ([raw file](https://github.com/starkware-libs/cairo/blob/4fae05ec476bcad162e0da1489172cd7d012eba6/crates/cairo-lang-lowering/src/inline/mod.rs#L329)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Or is it checked somewhere before?
</blockquote></details>

how can it be unreachable with no early returns?
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 365 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1895#-NMccpT1CsljxuvE8XUZ:-NMd0qh77Rr3midw5HDO:b40th3c) ([raw file](https://github.com/starkware-libs/cairo/blob/4fae05ec476bcad162e0da1489172cd7d012eba6/crates/cairo-lang-lowering/src/inline/mod.rs#L365)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

can you call rewrite?
</blockquote></details>

no - as i don't want to do recursion here.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1895#-:-NMdMw3e5GqrtqtuQJwd:bnfp4nl)* status: 29 of 54 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 2 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1895)* status: 31 of 54 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 44 of 52 files at r1, 5 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1895)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1895)* status: 50 of 55 files reviewed, 3 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 365 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1895#-NMccpT1CsljxuvE8XUZ:-NMdnTMr5jsx0LrR7YcQ:b-hr90nh) ([raw file](https://github.com/starkware-libs/cairo/blob/4fae05ec476bcad162e0da1489172cd7d012eba6/crates/cairo-lang-lowering/src/inline/mod.rs#L365)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no - as i don't want to do recursion here.
</blockquote></details>

this is working for me:
https://github.com/starkware-libs/cairo/commit/f5d6538d014dfe543f155ea4515cb683de001d9a

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1895)* status: 48 of 55 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 377 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1895#-NMcXdCeEgN65nDpvFNf:-NMdq0vF2O4GMWpqjeDA:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/b15e95932ab09ad7370fbeafe0ec8120fe398779/crates/cairo-lang-lowering/src/inline/mod.rs#L377)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it is no longer recursive here.
</blockquote></details>

Done
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 365 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1895#-NMccpT1CsljxuvE8XUZ:-NMdpy8a5EBhIhOS8VbB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4fae05ec476bcad162e0da1489172cd7d012eba6/crates/cairo-lang-lowering/src/inline/mod.rs#L365)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

this is working for me:
https://github.com/starkware-libs/cairo/commit/f5d6538d014dfe543f155ea4515cb683de001d9a
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 5 of 5 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1895)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r3, 1 of 5 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1895#-:-NMdtDJy9ro8kk2ybrk2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
