### PR TITLE
Add Zero trait.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2113)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2113)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @yuvalsw)

___
*[`corelib/zero.cairo` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2113#-NOA5QgU2NFxy3jNdJFC:-NOA5QgU2NFxy3jNdJFD:b-ilj5yz) ([raw file](https://github.com/starkware-libs/cairo/blob/020e9387496d8f66253dadce40c3c8628526076d/corelib/zero.cairo#L1)):*
> ```Cairo
> trait Zero<T> {
> ```

I'm not sure where to put it.

rust has:
num_traits::identities::Zero

should I open a num_traits directory?



_Code quote:_
```Cairo
trait Zero<T>
```

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2113#-:-NOACypM4LEz-stX5T_U:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/starknet.cairo` line 153 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2113#-NOAC_Yq-xJFwF1OBB0I:-NOAC_YrAEnzAYKiSLxX:botn7s) ([raw file](https://github.com/starkware-libs/cairo/blob/020e9387496d8f66253dadce40c3c8628526076d/corelib/starknet.cairo#L153)):*
> ```Cairo
> }
> 
> impl ContractAddressZero of Zero::<ContractAddress> {
> ```

I prefer it to be read the same as the "rhs" of the `of`, so Zero(able)ContractAddress



_Code quote:_
```Cairo
ContractAddressZero
```
___
*[`corelib/zero.cairo` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2113#-NOA5QgU2NFxy3jNdJFC:-NOABLQm9GSiQ2ofcWep:b-afvgwa) ([raw file](https://github.com/starkware-libs/cairo/blob/020e9387496d8f66253dadce40c3c8628526076d/corelib/zero.cairo#L1)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I'm not sure where to put it.

rust has:
num_traits::identities::Zero

should I open a num_traits directory?

</blockquote></details>

This is OK for now IMO. If we add more, we can rename.
___
*[`corelib/zero.cairo` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2113#-NOABQKz49U1Dm59IRAW:-NOABQKz49U1Dm59IRAX:b193613) ([raw file](https://github.com/starkware-libs/cairo/blob/020e9387496d8f66253dadce40c3c8628526076d/corelib/zero.cairo#L1)):*
> ```Cairo
> trait Zero<T> {
> ```

I don't like the name.
How about Zeroable?
___
*[`corelib/zero.cairo` line 4 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2113#-NOABmqnBt6nzKsXrMpS:-NOABmqnBt6nzKsXrMpT:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/020e9387496d8f66253dadce40c3c8628526076d/corelib/zero.cairo#L4)):*
> ```Cairo
>     /// Returns the additive identity element of Self, 0.
>     fn zero() -> T;
>     /// Returns true if self is equal to the additive identity.
> ```





_Suggestion:_
```Cairo
/// Returns whether self is equal to 0, the additive identity element.
```
___
*[`corelib/zero.cairo` line 15 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2113#-NOAC0hI-6m1izXLEuX5:-NOAC0hI-6m1izXLEuX6:bhxyslo) ([raw file](https://github.com/starkware-libs/cairo/blob/020e9387496d8f66253dadce40c3c8628526076d/corelib/zero.cairo#L15)):*
> ```Cairo
> 
>     /// Returns true if self is equal to the additive identity.
>     #[inline(always)]
> ```

redundant documentation.



_Suggestion:_
```Cairo
    fn zero() -> felt {
        0
    }

    #[inline(always)]
    fn is_zero(self: felt) -> bool {
        self == 0
    }
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2113)* status: all files reviewed, 5 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/lib.cairo` line 395 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2113#-NODqxMl6yqnQpOS9vPj:-NODqxMl6yqnQpOS9vPk:b-xwwozf) ([raw file](https://github.com/starkware-libs/cairo/blob/020e9387496d8f66253dadce40c3c8628526076d/corelib/lib.cairo#L395)):*
> ```Cairo
> 
> mod zero;
> use zero::Zero;
> ```

should this be
use zeroable::Zeroable
?

how do we want to call the implementation file?



_Code quote:_
```Cairo
use zero::Zero;
```
___
*[`corelib/zero.cairo` line 4 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2113#-NOABmqnBt6nzKsXrMpS:-NOAMGcH5BFWWRdRTfiE:b15gcuw) ([raw file](https://github.com/starkware-libs/cairo/blob/020e9387496d8f66253dadce40c3c8628526076d/corelib/zero.cairo#L4)):*
> ```Cairo
>     /// Returns the additive identity element of Self, 0.
>     fn zero() -> T;
>     /// Returns true if self is equal to the additive identity.
> ```

I copied it from the rust docs, but ok.



_Code quote (from corelib/starknet.cairo):_
```Cairo
 zero
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2113)* status: all files reviewed, 5 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/starknet.cairo` line 153 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2113#-NOAC_Yq-xJFwF1OBB0I:-NODrXfT8Pf65txI0o33:b-234trx) ([raw file](https://github.com/starkware-libs/cairo/blob/020e9387496d8f66253dadce40c3c8628526076d/corelib/starknet.cairo#L153)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I prefer it to be read the same as the "rhs" of the `of`, so Zero(able)ContractAddress
</blockquote></details>

ZeroableContractAddress sounds like a type.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2113)* status: all files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/lib.cairo` line 395 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2113#-NODqxMl6yqnQpOS9vPj:-NODspM25NZl7oGkxssZ:b871uml) ([raw file](https://github.com/starkware-libs/cairo/blob/020e9387496d8f66253dadce40c3c8628526076d/corelib/lib.cairo#L395)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

should this be
use zeroable::Zeroable
?

how do we want to call the implementation file?

</blockquote></details>

IMO yes
___
*[`corelib/starknet.cairo` line 153 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2113#-NOAC_Yq-xJFwF1OBB0I:-NODt-fz9Gu67Pr5COlX:b-v09k39) ([raw file](https://github.com/starkware-libs/cairo/blob/020e9387496d8f66253dadce40c3c8628526076d/corelib/starknet.cairo#L153)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

ZeroableContractAddress sounds like a type.
</blockquote></details>

Right, but I don't see the issue with it. but OK, ContractAddressZeroable is also fine

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2113)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`corelib/zero.cairo` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2113#-NOABQKz49U1Dm59IRAW:-NODxjAXBjFoMBf-FXoP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/020e9387496d8f66253dadce40c3c8628526076d/corelib/zero.cairo#L1)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I don't like the name.
How about Zeroable?
</blockquote></details>

Done.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2113#-:-NOEEAVMDY8CECSz2PrH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
