### PR TITLE
Iterate over all builtins in *_get_gas().

### PR DESCRIPTION
**Pull request by liorgold2**
commit-id:a459ad90

---

**Stack**:
- #1289
- #1288
- #1287
- #1286
- #1285 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1285#-:-NJ--qi-1vbVamAGm__a:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/sierra_to_casm/src/invocations/builtin_cost.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1285#-NJ--8Z06QAHSYYreIQs:-NJ--8Z06QAHSYYreIQt:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f69804b2d5c2df6b1ae24b7518f49bfa2b7986a7/crates/sierra_to_casm/src/invocations/builtin_cost.rs#L68)):*
> ```XML
>         .ok_or(InvocationError::UnknownVariableData)?;
>     let mut compute_requested_amount: Vec<Instruction> = casm! {
>         [ap] = requested_steps, ap++;
> ```





_Suggestion:_
```XML
    let mut compute_requested_amount = casm! { [ap] = requested_steps, ap++; };
    let mut compute_requested_amount_ap_change: usize = 1;
    for token_type in CostTokenType::iter() {
        if *token_type == CostTokenType::Step {
            continue;
        }
        let requested_count = variable_values
            .get(&(builder.idx, *token_type))
            .ok_or(InvocationError::UnknownVariableData)?;
        let translated_builtin_cost =
            builtin_cost.unchecked_apply_known_ap_change(compute_requested_amount_ap_change);
        casm_extend!(
            compute_requested_amount,
            // TODO(lior): Fetch the cost of each builtin separately.
            [ap] = translated_builtin_cost * (*requested_count), ap++;
            [ap] = [ap - 2] + [ap - 1], ap++;
        );
        compute_requested_amount_ap_change += 2;
    }
```

**Review by liorgold2 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1285)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1285)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/sierra_to_casm/src/invocations/builtin_cost.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1285#-NJ--8Z06QAHSYYreIQs:-NJ-K5mj0wgSZcEQqMOr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f69804b2d5c2df6b1ae24b7518f49bfa2b7986a7/crates/sierra_to_casm/src/invocations/builtin_cost.rs#L68)):*
> ```XML
>         .ok_or(InvocationError::UnknownVariableData)?;
>     let mut compute_requested_amount: Vec<Instruction> = casm! {
>         [ap] = requested_steps, ap++;
> ```

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1285)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
