### PR TITLE
Added `trim` action for `bounded_int`.

### PR DESCRIPTION
**Pull request by orizi**

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 421 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6788#-OD05OsWDhDbcz-U2nPb:-OD05OsWDhDbcz-U2nPc:b-frqy87) ([raw file](https://github.com/starkware-libs/cairo/blob/7265c8763e760816688de8ce337fd346d69a4116/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L421)):*
> ```XML
>                 BranchSignature {
>                     vars: vec![],
>                     ap_change: SierraApChange::Known { new_vars_only: false },
> ```

it can be true for the case where trimmed_value == 0, right?



_Code quote:_
```XML
new_vars_only: false 
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6788)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @dean-starkware, @gilbens-starkware, and @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6788)* status: 6 of 8 files reviewed, 4 unresolved discussions (waiting on @dean-starkware, @gilbens-starkware, and @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 414 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6788#-OD1EX7H1X5O9Wx5y9wP:-OD5N_6w81ZdGcR9n1AS:b-3ouasn) ([raw file](https://github.com/starkware-libs/cairo/blob/7265c8763e760816688de8ce337fd346d69a4116/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L414)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

The error message doesn’t indicate why the argument is unsupported, making debugging harder.
</blockquote></details>

good point - but - currently our support for basic error in sierra-to-casm is limited - we should probably expand it all around - but not by adding string - just having more fine grained errors.

in any case - not for this PR.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 415 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6788#-OD1CwOw5YPh0m3JshB5:-OD5NoDW575Rr4ojHoXb:br3uns3) ([raw file](https://github.com/starkware-libs/cairo/blob/7265c8763e760816688de8ce337fd346d69a4116/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L415)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

After adjusting the range, there is no re-validation to ensure it is still meaningful.
For example, if `trimmed_value` is the only valid value in the range (e.g., `[3, 4)`), trimming it would result in an invalid range `[4, 4)`.
</blockquote></details>

it is already done when trying to generate the resulting BoundedInt type - as it won't ever be created.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 421 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6788#-OD05OsWDhDbcz-U2nPb:-OD5O-4v9JoptX3hDuYU:b-esdiyc) ([raw file](https://github.com/starkware-libs/cairo/blob/7265c8763e760816688de8ce337fd346d69a4116/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L421)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it can be true for the case where trimmed_value == 0, right?
</blockquote></details>

correct - i need to have the same solve here.
Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 429 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6788#-OD1Gt_a0IGZo-ry7Jg3:-OD5O6ND5t80zc5wp47m:b-rgmbng) ([raw file](https://github.com/starkware-libs/cairo/blob/7265c8763e760816688de8ce337fd346d69a4116/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L429)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

There's ambiguity here:
The current logic ensures that if `trimmed_value` doesn’t match the `Min` or `Max - 1`, the function immediately returns an error.
Thus, there is no scenario where the range remains unchanged. The existence of a "No Change" is ambiguous- when would the libfunc produce this outcome? what condition would cause the range to remain unmodified?
</blockquote></details>

we cannot compile the function in the case the TRIM value is not MAX or MIN.
ap-change is about the changes to the ap pointer - the returned value isn't changed (value-wise) in any case.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6788)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6788#-:-ODC-8zN6IGbLFGEca8t:bnfp4nl)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
