### PR TITLE
Enrich members caching.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6343)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6343#-O5w77sK0lbTo3lj0Ymk:-O5w77sK0lbTo3lj0Yml:b-8ylye9) ([raw file](https://github.com/starkware-libs/cairo/blob/3a93f059137a94cdde391c4c508d209f0a63d3d4/crates/cairo-lang-semantic/src/resolve/mod.rs#L125)):*
> ```XML
> }
> impl EnrichedMembers {
>     /// Returns the enriched member structure for a single member if exists.
> ```

The return type is `EnrichedMembers`



_Code quote:_
```XML
enriched member structure
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6343)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6343#-O5w77sK0lbTo3lj0Ymk:-O5w9E2c9x0iJxrxtCzx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3a93f059137a94cdde391c4c508d209f0a63d3d4/crates/cairo-lang-semantic/src/resolve/mod.rs#L125)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

The return type is `EnrichedMembers`
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2865 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6343#-O5wZxIc5R7m3zkNmoSJ:-O5wZxIc5R7m3zkNmoSK:b-bxswq3) ([raw file](https://github.com/starkware-libs/cairo/blob/3a93f059137a94cdde391c4c508d209f0a63d3d4/crates/cairo-lang-semantic/src/expr/compute.rs#L2865)):*
> ```XML
>                 return Ok(e.clone());
>             }
>             entry.swap_remove()
> ```

why is the entry removed?



_Code quote:_
```XML
 entry.swap_remove()
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2865 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6343#-O5x7ZR703dgZ7DP127N:-O5x7ZR703dgZ7DP127O:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/3a93f059137a94cdde391c4c508d209f0a63d3d4/crates/cairo-lang-semantic/src/expr/compute.rs#L2865)):*
> ```XML
>                 return Ok(e.clone());
>             }
>             entry.swap_remove()
> ```

doc

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6343)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2865 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6343#-O5x7ZR703dgZ7DP127N:-O5x7smZ1AXD57WMFaGx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3a93f059137a94cdde391c4c508d209f0a63d3d4/crates/cairo-lang-semantic/src/expr/compute.rs#L2865)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 130 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6343#-O60OBDV8qpTd5CyWYhK:-O60OBDV8qpTd5CyWYhL:b-x8pgw) ([raw file](https://github.com/starkware-libs/cairo/blob/18ce47dbea00185cf5a973f0981818e7dfaaa427/crates/cairo-lang-semantic/src/resolve/mod.rs#L130)):*
> ```XML
>     /// `EnrichedTypeMemberAccessFailure::NotFound` otherwise returns
>     /// `EnrichedTypeMemberAccessFailure::NotFinal`.
>     pub fn accessed(
> ```

why is is called accessed?
maybe get_member?



_Code quote:_
```XML
accessed
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 162 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6343#-O60Oc3O9stVWDxPQB6m:-O60Oc3O9stVWDxPQB6n:b-ln98nv) ([raw file](https://github.com/starkware-libs/cairo/blob/18ce47dbea00185cf5a973f0981818e7dfaaa427/crates/cairo-lang-semantic/src/resolve/mod.rs#L162)):*
> ```XML
>     /// The member was not found.
>     NotFound,
>     /// The member was not found, but the enriched type info is not final.
> ```

can you elaborate on what final means?



_Code quote:_
```XML
  /// The member was not found, but the enriched type info is not final.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2936 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6343#-O60dqcG6TT7KvHa8nGn:-O60dqcG6TT7KvHa8nGo:b5bygrl) ([raw file](https://github.com/starkware-libs/cairo/blob/ddf77644556a324011133b0937736d8b3fc855b8/crates/cairo-lang-semantic/src/expr/compute.rs#L2936)):*
> ```XML
>         };
> 
>     // If the variable is mutable, and implements DerefMut, we use DerefMut in the first iteration.
> ```

Why is the first iteration special?



_Code quote:_
```XML
in the first iteration
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 119 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6343#-O60fLzD-v3uGfrmXpwN:-O60fLzD-v3uGfrmXpwO:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ddf77644556a324011133b0937736d8b3fc855b8/crates/cairo-lang-semantic/src/resolve/mod.rs#L119)):*
> ```XML
>     /// The sequence of deref functions needed to access the members.
>     pub deref_functions: Vec<(FunctionId, Mutability)>,
>     /// The tail remaining for required computation - the current expression `Deref`/`DerefMut`
> ```





_Suggestion:_
```XML
The tail of the current computation computation. The search for additional members will continue from this point.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2973 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6343#-O60iBW03fOT4OzTbwAV:-O60iBW03fOT4OzTbwAW:b8pzmgx) ([raw file](https://github.com/starkware-libs/cairo/blob/ddf77644556a324011133b0937736d8b3fc855b8/crates/cairo-lang-semantic/src/expr/compute.rs#L2973)):*
> ```XML
>             // If member is contained we can stop the calculation post the lookup.
>             if members.contains_key(accessed_member_name) {
>                 *calc_tail = Some(expr.id);
> ```

why is the calc_tail assigment related to finding the member? what happens if the member is not found?



_Code quote:_
```XML
    *calc_tail = Some(expr.id);
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6343)* status: 0 of 2 files reviewed, 8 unresolved discussions (waiting on @gilbens-starkware and @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2936 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6343#-O60dqcG6TT7KvHa8nGn:-O60ujaR-87Sl3Y37ukw:b-cdvc0w) ([raw file](https://github.com/starkware-libs/cairo/blob/ddf77644556a324011133b0937736d8b3fc855b8/crates/cairo-lang-semantic/src/expr/compute.rs#L2936)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why is the first iteration special?
</blockquote></details>

since out `DerefMut` is simulated - after it returned a value next calls would be `Deref` (as there's no longer a mut var available)
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2973 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6343#-O60iBW03fOT4OzTbwAV:-O60vr72CALw7wwJhvIR:b9sjkpc) ([raw file](https://github.com/starkware-libs/cairo/blob/ddf77644556a324011133b0937736d8b3fc855b8/crates/cairo-lang-semantic/src/expr/compute.rs#L2973)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why is the calc_tail assigment related to finding the member? what happens if the member is not found?
</blockquote></details>

if it wasn't found - it was fully enriched.
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 119 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6343#-O60fLzD-v3uGfrmXpwN:-O60w9d55foQi3djNcag:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ddf77644556a324011133b0937736d8b3fc855b8/crates/cairo-lang-semantic/src/resolve/mod.rs#L119)):*
> ```XML
>     /// The sequence of deref functions needed to access the members.
>     pub deref_functions: Vec<(FunctionId, Mutability)>,
>     /// The tail remaining for required computation - the current expression `Deref`/`DerefMut`
> ```

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 120 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6343#-O60xvjxA25ViLtH9FoO:-O60xvjxA25ViLtH9FoP:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/95274b92b6cba99a03ccc6742ad71ddd45d07949/crates/cairo-lang-semantic/src/resolve/mod.rs#L120)):*
> ```XML
>     pub deref_functions: Vec<(FunctionId, Mutability)>,
>     /// The tail of the current computation computation. The search for additional members will
>     /// continue from this point.
> ```





_Suggestion:_
```XML
    /// The tail of deref chain explored so far. The search for additional members will
    /// continue from this point.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2969 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6343#-O60yaIT8zUhTLB0eAal:-O60yaIT8zUhTLB0eAam:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ddf77644556a324011133b0937736d8b3fc855b8/crates/cairo-lang-semantic/src/expr/compute.rs#L2969)):*
> ```XML
>                 if !enriched.contains_key(member_name) {
>                     enriched.insert(member_name.clone(), (member.clone(), n_deref));
>                 }
> ```





_Suggestion:_
```XML
                if enriched.entry(member_name).or_insert_with(...
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2981 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6343#-O60z-SK-hOANdCqopzI:-O60z-SK-hOANdCqopzJ:b-yncmfh) ([raw file](https://github.com/starkware-libs/cairo/blob/ddf77644556a324011133b0937736d8b3fc855b8/crates/cairo-lang-semantic/src/expr/compute.rs#L2981)):*
> ```XML
>             // member access.
>             break;
>         }
> ```

Why is it ok to leave the tail as None in this case?



_Code quote:_
```XML
        if !visited_types.insert(long_ty.intern(ctx.db)) {
            // Break if we have a cycle. A diagnostic will be reported from the impl and not from
            // member access.
            break;
        }
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6343)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware and @orizi)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2915 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6343#-O610Fua0KAjJ7TgpBTU:-O610Fua0KAjJ7TgpBTV:b-fcem3) ([raw file](https://github.com/starkware-libs/cairo/blob/ddf77644556a324011133b0937736d8b3fc855b8/crates/cairo-lang-semantic/src/expr/compute.rs#L2915)):*
> ```XML
> 
>     let expr_id = calc_tail.expect("`enrich_members` should be called with a `calc_tail` value.");
>     *calc_tail = None;
> ```

make sure the comment above the exploration tail is consistent with the new name.



_Suggestion:_
```XML
 // This function either finds a member and sets the exploration_tail or finishes the exploration and
 // leaves that exploration tail as None
 *exploration_tail = None;
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6343)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware and @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2915 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6343#-O610Fua0KAjJ7TgpBTU:-O6116F_1kUR_xHNKAML:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ddf77644556a324011133b0937736d8b3fc855b8/crates/cairo-lang-semantic/src/expr/compute.rs#L2915)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

make sure the comment above the exploration tail is consistent with the new name.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2969 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6343#-O60yaIT8zUhTLB0eAal:-O61-Qap0KwoJZOt3DCx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ddf77644556a324011133b0937736d8b3fc855b8/crates/cairo-lang-semantic/src/expr/compute.rs#L2969)):*
> ```XML
>                 if !enriched.contains_key(member_name) {
>                     enriched.insert(member_name.clone(), (member.clone(), n_deref));
>                 }
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2981 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6343#-O60z-SK-hOANdCqopzI:-O61-ehl5VHjwJmZ1sd5:by92f7o) ([raw file](https://github.com/starkware-libs/cairo/blob/ddf77644556a324011133b0937736d8b3fc855b8/crates/cairo-lang-semantic/src/expr/compute.rs#L2981)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why is it ok to leave the tail as None in this case?
</blockquote></details>

because members won't be properly found anyway.
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 120 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6343#-O60xvjxA25ViLtH9FoO:-O61-tNo7daIkBoXaxAQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/95274b92b6cba99a03ccc6742ad71ddd45d07949/crates/cairo-lang-semantic/src/resolve/mod.rs#L120)):*
> ```XML
>     pub deref_functions: Vec<(FunctionId, Mutability)>,
>     /// The tail of the current computation computation. The search for additional members will
>     /// continue from this point.
> ```

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6343#-:-O613gI05T0fVa4PAHDR:bnfp4nl)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Pull request merged**
