### PR TITLE
refactored generic_signature function

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5791)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5791)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 158 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5791#-O-GOcU62kMz6aoy87_6:-O-GOcU62kMz6aoy87_7:bnxcqbc) ([raw file](https://github.com/starkware-libs/cairo/blob/ffe60eedc920d5177758bdd2a9d9619ee3e9d9f1/crates/cairo-lang-semantic/src/items/functions.rs#L158)):*
> ```XML
>             GenericFunctionId::Impl(id) => {
>                 let concrete_trait_id = match id.impl_id {
>                     ImplId::Concrete(concrete_impl_id) => {
> ```

can you explain why this is ok?

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5791)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 158 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5791#-O-GOcU62kMz6aoy87_6:-O-GT6sj0iDbgwlVrF89:b-aa9q6h) ([raw file](https://github.com/starkware-libs/cairo/blob/ffe60eedc920d5177758bdd2a9d9619ee3e9d9f1/crates/cairo-lang-semantic/src/items/functions.rs#L158)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can you explain why this is ok?
</blockquote></details>

its the same logic anyway

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5791#-:-O-GVCTo6GemrRex5MDD:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5791)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
