### PR TITLE
Initial definitions for bitwise builtin

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
Signed-off-by: Dori Medini <dori@starkware.co>

commit-id:74d9313e

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1394)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1394)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/sierra/src/extensions/modules/bitwise.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1394#-NJegiVzBLDNiCMELm_l:-NJegiVzBLDNiCMELm_m:b-58au8a) ([raw file](https://github.com/starkware-libs/cairo/blob/6a6cab0f846381cbbc8594c1b1470cc3d5163ace/crates/sierra/src/extensions/modules/bitwise.rs#L36)):*
> ```XML
> define_libfunc_hierarchy! {
>     pub enum BitwiseLibFunc {
>         Do(BitwiseDoLibFunc),
> ```

`Do` is kinda sucky but what should I call this?
Pedersen uses `Hash`



_Code quote:_
```XML
Do(BitwiseDoLibFunc)
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, 2 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1394)* status: all files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/sierra/src/extensions/modules/bitwise.rs` line 14 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1394#-NJk4heXBo3HBGO8-GIT:-NJk4heXBo3HBGO8-GIU:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/108b5ee8b88faf15c2744506ca241449c3f3c945/crates/sierra/src/extensions/modules/bitwise.rs#L14)):*
> ```XML
> use crate::ids::{GenericLibFuncId, GenericTypeId};
> 
> /// Type representing the Pedersen hash builtin.
> ```





_Suggestion:_
```XML
/// Type representing the Bitwise builtin.
```
___
*[`crates/sierra/src/extensions/modules/bitwise.rs` line 36 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1394#-NJk4OCT-Yp-i3j-8iEy:-NJk4OCU2HkI7GHIBc2d:b-tjrph0) ([raw file](https://github.com/starkware-libs/cairo/blob/108b5ee8b88faf15c2744506ca241449c3f3c945/crates/sierra/src/extensions/modules/bitwise.rs#L36)):*
> ```XML
> define_libfunc_hierarchy! {
>     pub enum BitwiseLibFunc {
>         Do(BitwiseDoLibFunc),
> ```

remove this class - rename `BitwiseDoLibFunc` to BitwiseLibFunc



_Code quote:_
```XML
define_libfunc_hierarchy! {
    pub enum BitwiseLibFunc {
        Do(BitwiseDoLibFunc),
    }, BitwiseConcreteLibFunc
}
```
___
*[`crates/sierra/src/extensions/modules/bitwise.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1394#-NJk4XSn-i2HCQkXUzEp:-NJk4XSn-i2HCQkXUzEq:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/108b5ee8b88faf15c2744506ca241449c3f3c945/crates/sierra/src/extensions/modules/bitwise.rs#L41)):*
> ```XML
> 
> /// LibFunc for computing the Bitwise (and,or,xor) of two felts.
> /// Returns 3 felts (and the updated builtin pointer).
> ```





_Suggestion:_
```XML
/// LibFunc for computing the Bitwise (and, or, xor) of two u128s.
/// Returns 3 u128s (and the updated builtin pointer).
```
___
*[`crates/sierra/src/simulation/core.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1394#-NJepmOS7EhB1HEDmuKk:-NJepmOS7EhB1HEDmuKl:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6a6cab0f846381cbbc8594c1b1470cc3d5163ace/crates/sierra/src/simulation/core.rs#L55)):*
> ```XML
>                 vec![CoreValue::Felt(a & b), CoreValue::Felt(a | b), CoreValue::Felt(a ^ b)],
>                 0,
>             )),
> ```





_Suggestion:_
```XML
        Bitwise(_) => match &inputs[..] {
            [CoreValue::Uin128(a), CoreValue::Uin128(b)] => Ok((
                vec![CoreValue::Uin128(a & b), CoreValue::Uin128(a | b), CoreValue::Uin128(a ^ b)],
                0,
            )),
            [_, _] => Err(LibFuncSimulationError::MemoryLayoutMismatch),
            _ => Err(LibFuncSimulationError::WrongNumberOfArgs),
        },
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1394)* status: 6 of 8 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/sierra/src/extensions/modules/bitwise.rs` line 14 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1394#-NJk4heXBo3HBGO8-GIT:-NJk6k_32eXMPN8Wmd9P:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/108b5ee8b88faf15c2744506ca241449c3f3c945/crates/sierra/src/extensions/modules/bitwise.rs#L14)):*
> ```XML
> use crate::ids::{GenericLibFuncId, GenericTypeId};
> 
> /// Type representing the Pedersen hash builtin.
> ```

Done.
___
*[`crates/sierra/src/extensions/modules/bitwise.rs` line 36 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1394#-NJk4OCT-Yp-i3j-8iEy:-NJk6l9y-nJfi16ROnIQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/108b5ee8b88faf15c2744506ca241449c3f3c945/crates/sierra/src/extensions/modules/bitwise.rs#L36)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove this class - rename `BitwiseDoLibFunc` to BitwiseLibFunc
</blockquote></details>

Done.
___
*[`crates/sierra/src/extensions/modules/bitwise.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1394#-NJk4XSn-i2HCQkXUzEp:-NJk6lVu0vpSEm7R8GUy:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/108b5ee8b88faf15c2744506ca241449c3f3c945/crates/sierra/src/extensions/modules/bitwise.rs#L41)):*
> ```XML
> 
> /// LibFunc for computing the Bitwise (and,or,xor) of two felts.
> /// Returns 3 felts (and the updated builtin pointer).
> ```

Done.
___
*[`crates/sierra/src/simulation/core.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1394#-NJepmOS7EhB1HEDmuKk:-NJk6eeBEpAPXMD182gY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6a6cab0f846381cbbc8594c1b1470cc3d5163ace/crates/sierra/src/simulation/core.rs#L55)):*
> ```XML
>                 vec![CoreValue::Felt(a & b), CoreValue::Felt(a | b), CoreValue::Felt(a ^ b)],
>                 0,
>             )),
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1394#-:-NJkBImR7O6rGzDgnY7K:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1394)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
