### PR TITLE
fix: deploy syscall address registry

### LINKED ISSUE #4488: bug: CASM runner `deploy_syscall` doesn't support external call to deployer in constructor
# Bug Report

**Cairo version:**
2.4.0-rc4

**Current behavior:**
The `deploy` function in the CASM runner in charge of deploying a contract first starts by executing the constructor of the contract, and only then registers the address of the contract in the starknet state. 
This causes a problem when a Factory contract deploys a Child contract, and this Child needs to access a method from the Factory contract as an external call, as this will fail with a `CONTRACT_NOT_DEPLOYED` error.

**Expected behavior:**
The contract should be registered in starknet state _before_ the execution of the constructor, so that Child contracts can call methods from their Factory.

**Steps to reproduce:**

**Related code:**

This is the part in the runner that is responsible for executing the constructor and setting the contract address
```rust
 // Call constructor if it exists.
        let (res_data_start, res_data_end) = if let Some(constructor) = &contract_info.constructor {
            let old_addrs = self
                .starknet_state
                .open_caller_context((deployed_contract_address.clone(), deployer_address));
            let res = self.call_entry_point(gas_counter, runner, constructor, calldata, vm);
            self.starknet_state.close_caller_context(old_addrs);
            match res {
                Ok(value) => value,
                Err(mut revert_reason) => {
                    fail_syscall!(revert_reason, b"CONSTRUCTOR_FAILED");
                }
            }
            
             // Set the class hash of the deployed contract before executing the constructor,
        // as the constructor could make an external call to this address.
        self.starknet_state
            .deployed_contracts
            .insert(deployed_contract_address.clone(), class_hash);
```

Reproducible example:
```rust
use core::result::ResultTrait;
use starknet::deploy_syscall;
use debug::PrintTrait;

#[starknet::interface]
trait IFactory<TContractState> {
    fn test(self: @TContractState) -> felt252;
}

#[starknet::interface]
trait IEmptyContract<TContractState> {
    fn initialize(ref self: TContractState) -> felt252;
}

#[starknet::contract]
mod Factory {
    use core::traits::TryInto;
    use starknet::{ClassHash, deploy_syscall};
    use array::ArrayTrait;
    use super::{IEmptyContractDispatcher, IEmptyContractDispatcherTrait};
    use debug::PrintTrait;
    #[storage]
    struct Storage {}

    #[constructor]
    fn constructor(ref self: ContractState, child_hash: ClassHash) {
        let calldata = array![];
        let (address, _) = deploy_syscall(child_hash.try_into().unwrap(), 0, calldata.span(), false)
            .expect('child deploy failed');
        // The child contract is deployed, but the following line fails without propagating an error.
        let res = IEmptyContractDispatcher { contract_address: address }.initialize();
        res.print();
    }

    #[abi(embed_v0)]
    impl FactoryImpl of super::IFactory<ContractState> {
        fn test(self: @ContractState) -> felt252 {
            'test'
        }
    }
}

#[starknet::contract]
mod EmptyContract {
    use starknet::account::{Call, AccountContract};
    use starknet::get_caller_address;
    use super::{IFactoryDispatcher, IFactoryDispatcherTrait};
    use debug::PrintTrait;

    #[storage]
    struct Storage {}

    #[abi(embed_v0)]
    impl EmptyContractImpl of super::IEmptyContract<ContractState> {
        fn initialize(ref self: ContractState) -> felt252 {
            let deployer_address = get_caller_address();
            // This fails, but secretly: nothing happens and no error is returned.
            // but the following line is not executed.
            let res = IFactoryDispatcher { contract_address: deployer_address }.test();
            'This line is not printed'.print();
            res
        }
    }
}

#[cfg(test)]
#[test]
fn test_deploy_in_construct() {
    let calldata = array![EmptyContract::TEST_CLASS_HASH.try_into().unwrap()];
    deploy_syscall(Factory::TEST_CLASS_HASH.try_into().unwrap(), 0, calldata.span(), false);
}

```

### PR DESCRIPTION
**Pull request by enitrat**
Fixes #4488

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4489)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4489)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @enitrat)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4489#-NkJaxjNEUoN7NtWF_jf:-NkJaxjNEUoN7NtWF_jg:b9s3f1l) (no related file):*
Add a tests in `cairo-lang-starknet/cairo-level-tests`.

___
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 984 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4489#-NkJbca45BzKlTOzPaG0:-NkJbca56Tkcnqyntz8v:b-il4fq4) ([raw file](https://github.com/starkware-libs/cairo/blob/59c5d4acd0ee7550bdaa65d2f50db8b1e7902f43/crates/cairo-lang-runner/src/casm_run/mod.rs#L984)):*
> ```XML
>                 Ok(value) => value,
>                 Err(mut revert_reason) => {
>                     fail_syscall!(revert_reason, b"CONSTRUCTOR_FAILED");
> ```

I would assume this failure should revert the deployment as well.

**Review by enitrat — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4489)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4489#-NkJaxjNEUoN7NtWF_jf:-NkK7_uUB4o5nv47lPrE:b-fgc95g) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Add a tests in `cairo-lang-starknet/cairo-level-tests`.
</blockquote></details>

Done. Also tested that before the changes, the test failed with 
```
failures:
   cairo_level_tests::deployment::test_deploy_in_construct - Panicked with 0x666163746f7279206465706c6f796d656e74206661696c6564 ('factory deployment failed').

Error: test result: FAILED. 47 passed; 1 failed; 0 ignored
```

Now, it passes.

___
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 984 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4489#-NkJbca45BzKlTOzPaG0:-NkK7aYp5bko0uQQCVVo:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/59c5d4acd0ee7550bdaa65d2f50db8b1e7902f43/crates/cairo-lang-runner/src/casm_run/mod.rs#L984)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I would assume this failure should revert the deployment as well.
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/cairo_level_tests/deployment.cairo` line 30 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4489#-NkK_MLs4xdue9Mv2fsW:-NkK_MLs4xdue9Mv2fsX:bot49mv) ([raw file](https://github.com/starkware-libs/cairo/blob/44830b5ea2924124aa3912098c18d90ec8057dbc/crates/cairo-lang-starknet/cairo_level_tests/deployment.cairo#L30)):*
> ```Cairo
>         let (address, _) = deploy_syscall(child_hash.try_into().unwrap(), 0, calldata.span(), false)
>             .expect('child deployment failed');
>         // The child contract is deployed, but the following line fails without propagating an error.
> ```

Is this fixed following this PR?



_Code quote:_
```Cairo
 // The child contract is deployed, but the following line fails without propagating an error.
```

**Review by enitrat — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4489)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/deployment.cairo` line 30 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4489#-NkK_MLs4xdue9Mv2fsW:-NkKa9fG-NbdZIuBSDgY:b6mcbpa) ([raw file](https://github.com/starkware-libs/cairo/blob/44830b5ea2924124aa3912098c18d90ec8057dbc/crates/cairo-lang-starknet/cairo_level_tests/deployment.cairo#L30)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Is this fixed following this PR?
</blockquote></details>

oops - sorry, I missed this comment. Yes, it's fixed following this PR and the test passes correctly.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4489#-:-NkKlXqk8IfgfXNCz1Ds:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4489)* status: all files reviewed, 1 unresolved discussion (waiting on @enitrat)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/deployment.cairo` line 74 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4489#-NkLAWe21-VGAwR65XSL:-NkLAWe21-VGAwR65XSM:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a51a40d7a77df4bb52e0e4c95b0c4f32c4308ad8/crates/cairo-lang-starknet/cairo_level_tests/deployment.cairo#L74)):*
> ```Cairo
>     let res = IFactoryDispatcher { contract_address: starknet_address }.get_value();
>     assert(res == 1, 'factory value is not 1')
> }
> ```





_Suggestion:_
```Cairo
use core::result::ResultTrait;
use starknet::deploy_syscall;

#[starknet::interface]
trait IValue<TContractState> {
    fn get_value(self: @TContractState) -> felt252;
    fn set_value(ref self: TContractState, value: felt252);
}

#[starknet::contract]
mod self_caller {
    use core::traits::TryInto;
    use starknet::{ClassHash, deploy_syscall};
    use super::{IValueDispatcher, IValueDispatcherTrait};
    #[storage]
    struct Storage {
        value: felt252,
    }

    #[constructor]
    fn constructor(ref self: ContractState) {
        IValueDispatcher { contract_address: starknet::get_contract_address() }.set_value(1);
    }

    #[abi(embed_v0)]
    impl ValueImpl of super::IValue<ContractState> {
        fn get_value(self: @ContractState) -> felt252 {
            self.value.read()
        }

        fn set_value(ref self: ContractState, value: felt252) {
            self.value.write(value);
        }
    }
}

#[test]
fn test_deploy_in_construct() {
    let (contract_address, _) = deploy_syscall(
        self_caller::TEST_CLASS_HASH.try_into().unwrap(), 0, array![].span(), false
    )
        .expect('deployment failed');
    assert!(IValueDispatcher { contract_address }.get_value() == 1);
}
```

**Review by enitrat — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4489)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/deployment.cairo` line 74 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4489#-NkLAWe21-VGAwR65XSL:-NkLIUT94mOSgpv-NR2-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a51a40d7a77df4bb52e0e4c95b0c4f32c4308ad8/crates/cairo-lang-starknet/cairo_level_tests/deployment.cairo#L74)):*
> ```Cairo
>     let res = IFactoryDispatcher { contract_address: starknet_address }.get_value();
>     assert(res == 1, 'factory value is not 1')
> }
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4489#-:-NkLN062-dFg9XzNPXjM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enitrat)

**Pull request merged**
