### PR TITLE
impl GenericParam

### PR DESCRIPTION
**Pull request by spapinistarkware**
commit-id:3c4ef0db

---

**Stack**:
- #2102
- #2078 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 16 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2078)* status: 16 of 21 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2078#-NNpvCdS-XH4Hu8iG9Nx:-NNpvCdS-XH4Hu8iG9Ny:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/512865d31ff8aa2c4e9db92085d3546ae236f058/crates/cairo-lang-semantic/src/items/functions.rs#L31)):*
> ```XML
> pub struct ConcreteImplGenericFunctionId {
>     pub concrete_impl_id: ConcreteImplId,
>     pub function: ImplFunctionId,
> ```

doc



_Code quote:_
```XML
#[derive(Copy, Clone, Debug, Hash, PartialEq, Eq)]
pub struct ConcreteImplGenericFunctionId {
    pub concrete_impl_id: ConcreteImplId,
    pub function: ImplFunctionId,
}

#[derive(Copy, Clone, Debug, Hash, PartialEq, Eq)]
pub struct ImplGenericParamFunctionId {
    pub param: GenericParamId,
    pub trait_function_id: TraitFunctionId,
}
```
___
*[`crates/cairo-lang-starknet/src/plugin_test_data/diagnostics` line 358 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2078#-NNpven92choNBwcYwaa:-NNpven92choNBwcYwab:b-fuawka) ([raw file](https://github.com/starkware-libs/cairo/blob/512865d31ff8aa2c4e9db92085d3546ae236f058/crates/cairo-lang-starknet/src/plugin_test_data/diagnostics#L358)):*
> ```
>                                      ^
> 
> error: Trait `core::serde::Serde` has multiple implementations, in: ImplDefId(core::serde::FeltSerde), ImplDefId(core::serde::BoolSerde), ImplDefId(core::serde::U8Serde), ImplDefId(core::serde::U32Serde), ImplDefId(core::serde::U64Serde), ImplDefId(core::serde::U128Serde), ImplDefId(core::serde::U256Serde), ImplDefId(core::serde::ArrayFeltSerde)
> ```

fix print.
also - fix the diagnostic itself at some point - the issue is missing impl - not multiple impls.



_Code quote:_
```
ImplDefId(core::serde::FeltSerde), ImplDefId(core::serde::BoolSerde), ImplDefId(core::serde::U8Serde), ImplDefId(core::serde::U32Serde), ImplDefId(core::serde::U64Serde), ImplDefId(core::serde::U128Serde), ImplDefId(core::serde::U256Serde), ImplDefId(core::serde::ArrayFeltSerde)
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2078)* status: 12 of 21 files reviewed, 2 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2078#-NNpvCdS-XH4Hu8iG9Nx:-NNq6kY3DuZLf2U-Mmh7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/512865d31ff8aa2c4e9db92085d3546ae236f058/crates/cairo-lang-semantic/src/items/functions.rs#L31)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin_test_data/diagnostics` line 358 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2078#-NNpven92choNBwcYwaa:-NNq6l3d6NUtlvhTKH7B:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/512865d31ff8aa2c4e9db92085d3546ae236f058/crates/cairo-lang-starknet/src/plugin_test_data/diagnostics#L358)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix print.
also - fix the diagnostic itself at some point - the issue is missing impl - not multiple impls.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 21 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2078)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 375 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2078#-NNqWlpPDtVH7le783_W:-NNqWlpPDtVH7le783_X:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/734cd7aecd7e361a1d019f6abaffe3465141cf8d/crates/cairo-lang-semantic/src/expr/inference.rs#L375)):*
> ```XML
>         if !self.can_infer_generics(
>             &imp_generic_param,
>             &long_imp_concrete_trait.generic_args,
> ```

?



_Suggestion:_
```XML
        self.can_infer_generics(
            &imp_generic_param,
            &long_imp_concrete_trait.generic_args,
            &long_concrete_trait.generic_args,
            stable_ptr,
        )
```
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 385 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2078#-NNqWqM10D_alXJY_VF3:-NNqWqM10D_alXJY_VF4:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/734cd7aecd7e361a1d019f6abaffe3465141cf8d/crates/cairo-lang-semantic/src/expr/inference.rs#L385)):*
> ```XML
> 
>     /// Infers all the variables required to make na impl (possibly with free generic params) can
>     /// provide a concrete trait.
> ```





_Suggestion:_
```XML
    /// Infers all the variables required to make an impl (possibly with free generic params) can
    /// provide a concrete trait.
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2078)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 375 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2078#-NNqWlpPDtVH7le783_W:-NNqXqmo1uAEcGduO6Ln:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/734cd7aecd7e361a1d019f6abaffe3465141cf8d/crates/cairo-lang-semantic/src/expr/inference.rs#L375)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 385 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2078#-NNqWqM10D_alXJY_VF3:-NNqXst07lGSETgIIlZh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/734cd7aecd7e361a1d019f6abaffe3465141cf8d/crates/cairo-lang-semantic/src/expr/inference.rs#L385)):*
> ```XML
> 
>     /// Infers all the variables required to make na impl (possibly with free generic params) can
>     /// provide a concrete trait.
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2078#-:-NNqY9zF6ylmHHDGkK66:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2078)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 6 of 21 files at r1, 5 of 7 files at r2, 2 of 5 files at r4, 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2078)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
