### PR TITLE
Literal generic argument.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1275)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 15 files at r1, 8 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1275)* status: 12 of 15 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/semantic/src/types.rs` line 289 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1275#-NIr2FJ595prg6kIkwqq:-NIr2FJ595prg6kIkwqr:blmjkf1) ([raw file](https://github.com/starkware-libs/cairo/blob/d26564dcfb78153544fbce6236526bfd6adc6c0e/crates/semantic/src/types.rs#L289)):*
> ```XML
>             .map(|generic_arg| match generic_arg {
>                 GenericArgumentId::Type(ty) => *ty,
>                 GenericArgumentId::Literal(_) => todo!(),
> ```

What is the Todo here?
Is it actually reachable? 
Add more info here.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1275)* status: 9 of 15 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/semantic/src/types.rs` line 289 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1275#-NIr2FJ595prg6kIkwqq:-NJ-6pCK4OGS3-NBOONB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d26564dcfb78153544fbce6236526bfd6adc6c0e/crates/semantic/src/types.rs#L289)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

What is the Todo here?
Is it actually reachable? 
Add more info here.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 10 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1275#-:-NJ-_7eQ5QJxqI4BHM8A:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1275)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1275)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
