### PR TITLE
Added doc for panic.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3088)

### CODE REVIEW

**Review by JameStark — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3088)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/panic.adoc` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3088#-NUzx4US8-QSk2Fy-Evj:-NUzx4US8-QSk2Fy-Evk:bb7r32j) ([raw file](https://github.com/starkware-libs/cairo/blob/6fe32c005989b0cd0f29d7f797573ca76f3aa9ac/docs/reference/src/components/cairo/modules/language_constructs/pages/panic.adoc#L3)):*
> ```AsciiDoc
> = Panic
> 
> Code in _Cairo1.0_ may _panic_ - which means it may fail we an unrecoverable error. When the program panics, using the xref:linear-types.adoc[linear type system] all living variables on the stack would be `Dropped` or otherwise destructed, which makes sure the run remains provable and valid.
> ```

with



_Code quote:_
```AsciiDoc
we
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3088)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @JameStark and @spapinistarkware)

___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/panic.adoc` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3088#-NUzx4US8-QSk2Fy-Evj:-NUzxfmLAkBA4Q_W5YKc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a6dbb6034dd1e45f0fedb1421c4b289d316be997/docs/reference/src/components/cairo/modules/language_constructs/pages/panic.adoc#L3)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

with
</blockquote></details>

Done.
___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/panic.adoc` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3088#-NUzxFIB5MuLBVoUwsw1:-NUzxygm4_NJWKS9jStF:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a6dbb6034dd1e45f0fedb1421c4b289d316be997/docs/reference/src/components/cairo/modules/language_constructs/pages/panic.adoc#L17)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

This
</blockquote></details>

Done.
___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/panic.adoc` line 22 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3088#-NUzxPBW-Zg0aP1ih3v5:-NUzyIiL6MhlVUV0oBav:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a6dbb6034dd1e45f0fedb1421c4b289d316be997/docs/reference/src/components/cairo/modules/language_constructs/pages/panic.adoc#L22)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

Not needed
</blockquote></details>

Done.

**Review by JameStark — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3088)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3088)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @JameStark and @orizi)

___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/panic.adoc` line 19 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3088#-NV-9EM03DyOdywkITsD:-NV-9EM03DyOdywkITsE:bb7rwdc) ([raw file](https://github.com/starkware-libs/cairo/blob/f42b46ab7bff9a52900e8bc24cd6d88170742951/docs/reference/src/components/cairo/modules/language_constructs/pages/panic.adoc#L19)):*
> ```AsciiDoc
> The `panic` function takes a single argument, which is a `felt252` array.
> This array is the data that is passed as the reason the run panicked.
> The `panic` function never returns, and is marked as such with the xref:never-type.adoc[never type].
> ```

xref



_Code quote:_
```AsciiDoc
 never 
```

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3088)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @JameStark and @orizi)

___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/panic.adoc` line 27 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3088#-NV-9MzX7o0a2sS3ShRE:-NV-9MzY6dvwGZgdZwF_:bkqwwsk) ([raw file](https://github.com/starkware-libs/cairo/blob/f42b46ab7bff9a52900e8bc24cd6d88170742951/docs/reference/src/components/cairo/modules/language_constructs/pages/panic.adoc#L27)):*
> ```AsciiDoc
> This can be useful for writing code that may never fail.
> Only _nopanic_ functions may be called from a _nopanic_ function.
> ```

Give an example that destructors are no panic

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3088)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3088)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @JameStark and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3088#-NV-9u2S57m6I7lfby1k:-NV-EacdDQl2Sf38W6MC:b-896fix) (no related file):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

1. I would like to explain that it is not possible to "catch" panics, and if you want to do a nopanic code, use only non panicking version of stuff.
2. Talk about how panic plays with traits. For example, the Add::add function is panicable, even though it's impl for felt is not.
</blockquote></details>

Done.

___
___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/panic.adoc` line 19 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3088#-NV-9EM03DyOdywkITsD:-NV-BcSM3pxLr6SUqTj5:b-6z93cx) ([raw file](https://github.com/starkware-libs/cairo/blob/f42b46ab7bff9a52900e8bc24cd6d88170742951/docs/reference/src/components/cairo/modules/language_constructs/pages/panic.adoc#L19)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

xref
</blockquote></details>

it is xref-ed 4 words after - you want this to appear twice?
___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/panic.adoc` line 27 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3088#-NV-9MzX7o0a2sS3ShRE:-NV-C5Vp-Y9HWws8KPnP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f42b46ab7bff9a52900e8bc24cd6d88170742951/docs/reference/src/components/cairo/modules/language_constructs/pages/panic.adoc#L27)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Give an example that destructors are no panic
</blockquote></details>

Done.

**Comment by orizi** [comment]
Closing pull request: commit has gone away

**Pull request closed without merging**
