### PR TITLE
Added impl_item_by_name/trait_item_by_name

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5248)

### CODE REVIEW

**Comment by yuvalsw** [comment]
change target

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5248)* status: all files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 594 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5248#-NsmPM0E9PryS4O1QyI-:-NsmPM0E9PryS4O1QyI0:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/2606ec93f2c8fee38bd39d77bafec1796ae6db94/crates/cairo-lang-semantic/src/items/imp.rs#L594)):*
> ```XML
>     let mut function_asts = OrderedHashMap::default();
>     let mut item_type_asts = OrderedHashMap::default();
>     // TODO(yg): can it be unordered?
> ```

.
___
*[`crates/cairo-lang-semantic/src/items/trt.rs` line 401 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5248#-NsmPPv-7gDwkAqjEbh7:-NsmPPv-7gDwkAqjEbh8:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/2606ec93f2c8fee38bd39d77bafec1796ae6db94/crates/cairo-lang-semantic/src/items/trt.rs#L401)):*
> ```XML
>     let mut function_asts = OrderedHashMap::default();
>     let mut item_type_asts = OrderedHashMap::default();
>     // TODO(yg): can it be unordered?
> ```

.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5248)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 594 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5248#-NsmPM0E9PryS4O1QyI-:-NsmdPVK6midehqjl577:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2606ec93f2c8fee38bd39d77bafec1796ae6db94/crates/cairo-lang-semantic/src/items/imp.rs#L594)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/trt.rs` line 401 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5248#-NsmPPv-7gDwkAqjEbh7:-NsmdOhP-TLdSMuMpvLh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2606ec93f2c8fee38bd39d77bafec1796ae6db94/crates/cairo-lang-semantic/src/items/trt.rs#L401)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5248#-:-Nsmg62S-qIEDOCM7njK:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion

**Pull request merged**
