### PR TITLE
Added short string support.

### PR DESCRIPTION
**Pull request by Alon-Ti**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1376)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1376)* status: all files reviewed, 5 unresolved discussions (waiting on @Alon-Ti)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1376#-NJ_JlF4EZYiDn0H0UhX:-NJ_JlF4EZYiDn0H0UhY:bssc36k) (no related file):*
add a usage in the examples so it would affect the tests.

___
___
*[`crates/parser/src/lexer.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1376#-NJ_IfFe3MpnHvGwAHMi:-NJ_IfFe3MpnHvGwAHMj:b4o89eu) ([raw file](https://github.com/starkware-libs/cairo/blob/871567703690e5c3991f98d35b561c9a5d5516b8/crates/parser/src/lexer.rs#L134)):*
> ```XML
>     /// Takes a short string.
>     fn take_token_short_string(&mut self) -> TokenKind {
>         if self.peek() == Some('"') {
> ```

we should probably also disallow non-ascii charachters.
so .is_acsii as well.



_Suggestion:_
```XML
    /// Takes a short string.
    fn take_token_short_string(&mut self) -> TokenKind {
        if self.peek() == Some('\'') {
            self.take();
            // TODO(alon) support '\'' escaping.
            self.take_while(|c| c != '\'');
            self.take();
        }

        // Parse _type suffix.
        if self.peek() == Some('_') {
            self.take_while(|c| c.is_ascii_alphanumeric() || c == '_');
        }
        TokenKind::ShortString
    }
```
___
*[`crates/parser/src/lexer.rs` line 208 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1376#-NJ_Ikdu5Hsyejwt5qZt:-NJ_Ikdu5Hsyejwt5qZu:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/871567703690e5c3991f98d35b561c9a5d5516b8/crates/parser/src/lexer.rs#L208)):*
> ```XML
>             match current {
>                 '0'..='9' => self.take_token_literal_number(),
>                 '"' => self.take_token_short_string(),
> ```





_Suggestion:_
```XML
                '\'' => self.take_token_short_string(),
```
___
*[`crates/semantic/src/expr/compute.rs` line 883 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1376#-NJ_IwTI8I5D0u1S2LF9:-NJ_IwTI8I5D0u1S2LFA:bwpct57) ([raw file](https://github.com/starkware-libs/cairo/blob/871567703690e5c3991f98d35b561c9a5d5516b8/crates/semantic/src/expr/compute.rs#L883)):*
> ```XML
>     let text = short_string_syntax.text(syntax_db);
> 
>     if let Some((literal, suffix)) = text[1..].rsplit_once('"') {
> ```

for future proofing of support of escaping - just slice [1:len-1]



_Code quote:_
```XML
 if let Some((literal, suffix)) = text[1..].rsplit_once('"') {
```
___
*[`crates/semantic/src/expr/compute.rs` line 892 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1376#-NJ_J62KCYEU8mJ-lg8Z:-NJ_J62KCYEU8mJ-lg8_:b-ncyyia) ([raw file](https://github.com/starkware-libs/cairo/blob/871567703690e5c3991f98d35b561c9a5d5516b8/crates/semantic/src/expr/compute.rs#L892)):*
> ```XML
>         let mut value = BigInt::from(0);
>         for c in literal.chars() {
>             value <<= 8;
> ```

BigInt::from_bytes_le



_Code quote:_
```XML
        let mut value = BigInt::from(0);
        for c in literal.chars() {
            value <<= 8;
            value |= BigInt::from(c as u16);
        }
```

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1376)* status: 3 of 12 files reviewed, 5 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1376#-NJ_JlF4EZYiDn0H0UhX:-NJeYiQn7WBaY0wbpqU_:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add a usage in the examples so it would affect the tests.
</blockquote></details>

Done.

___
___
*[`crates/parser/src/lexer.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1376#-NJ_IfFe3MpnHvGwAHMi:-NJeV0IG1p10gmmyVvAq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/871567703690e5c3991f98d35b561c9a5d5516b8/crates/parser/src/lexer.rs#L134)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

we should probably also disallow non-ascii charachters.
so .is_acsii as well.
</blockquote></details>

Done.
___
*[`crates/parser/src/lexer.rs` line 208 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1376#-NJ_Ikdu5Hsyejwt5qZt:-NJeV4Zl3zd0ic-CyMIs:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/871567703690e5c3991f98d35b561c9a5d5516b8/crates/parser/src/lexer.rs#L208)):*
> ```XML
>             match current {
>                 '0'..='9' => self.take_token_literal_number(),
>                 '"' => self.take_token_short_string(),
> ```

Done.
___
*[`crates/semantic/src/expr/compute.rs` line 883 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1376#-NJ_IwTI8I5D0u1S2LF9:-NJeV8rC1HtXEpyF8yRo:b2mm0hz) ([raw file](https://github.com/starkware-libs/cairo/blob/871567703690e5c3991f98d35b561c9a5d5516b8/crates/semantic/src/expr/compute.rs#L883)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

for future proofing of support of escaping - just slice [1:len-1]
</blockquote></details>

This won't work because of the type suffix, and there should be no problem with escaping because this splits from the right.
___
*[`crates/semantic/src/expr/compute.rs` line 892 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1376#-NJ_J62KCYEU8mJ-lg8Z:-NJeWmD4ACnY2SRkfUu1:bizi77d) ([raw file](https://github.com/starkware-libs/cairo/blob/871567703690e5c3991f98d35b561c9a5d5516b8/crates/semantic/src/expr/compute.rs#L892)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

BigInt::from_bytes_le
</blockquote></details>

Done, but with `be` for compatibility with cairo0 (and C, apparently).

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1376)* status: 8 of 12 files reviewed, 1 unresolved discussion (waiting on @Alon-Ti)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1376#-NJ_JlF4EZYiDn0H0UhX:-NJebGmn1iCS8wYdseOj:by93d9g) (no related file):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

Done.
</blockquote></details>

in the parser tests - no need for a full example tests (just changing some panic there to be shortstring based would suffice)

___

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1376)* status: 8 of 13 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1376#-NJ_JlF4EZYiDn0H0UhX:-NJedH88DVHd5cHnP9Sv:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

in the parser tests - no need for a full example tests (just changing some panic there to be shortstring based would suffice)
</blockquote></details>

Done.

___

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1376#-:-NJedqGpE9iKOc1bHVZL:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Alon-Ti)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1376)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Alon-Ti)

**Pull request merged**
