### PR TITLE
Add reload command for cairo language server extension, reload on changed Scarb.toml

### PR DESCRIPTION
**Pull request by maciektr**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2951)

### CODE REVIEW

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2951#-:-NU5YZ-5Brkxz52rAjR5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Comment by mkaput** [comment]
@spapinistarkware can we merge this?

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2951#-:-NUu3qEa318gVhs3WDTh:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @mkaput)

**Review by spapinistarkware — COMMENTED** [review]
Yes.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2951#-:-NUu3ss8DQjoyrojrtL9:bb77ufg)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @mkaput)

**Review by mkaput — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2951)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciektr)

**Review by mkaput — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2951)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciektr)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2951#-:-NUu5c7iBvCpni7ihOeW:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciektr)

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2951)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciektr)

**Review by mkaput — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2951)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciektr)

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2951)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciektr)

**Pull request merged**
