### PR TITLE
Add Map storage type.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5432)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 22 files at r1, 1 of 21 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5432)* status: 2 of 22 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware)

___
*[`corelib/src/starknet/storage.cairo` line 121 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5432#-Nvg7masDUPUJDst5rtc:-Nvg7masDUPUJDst5rtd:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/9d954c8c8b67cd628dc82435d44d08aa0db29209/corelib/src/starknet/storage.cairo#L121)):*
> ```Cairo
> }
> 
> type StoragePath<T> = GenericStoragePath<T, core::poseidon::HashState>;
> ```

doc
___
*[`corelib/src/starknet/storage.cairo` line 131 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5432#-Nvg8AOS2oTeZRQOeazA:-Nvg8AOS2oTeZRQOeazB:b-ufnp1p) ([raw file](https://github.com/starkware-libs/cairo/blob/9d954c8c8b67cd628dc82435d44d08aa0db29209/corelib/src/starknet/storage.cairo#L131)):*
> ```Cairo
> pub trait StoragePathFinalize<T> {
>     fn finalize(self: StoragePath<T>) -> StoragePointer<T>;
> }
> ```

maybe just implement the `as_ptr` trait as well?



_Code quote:_
```Cairo
/// Trait for finalizing the hash state and getting the final address.
pub trait StoragePathFinalize<T> {
    fn finalize(self: StoragePath<T>) -> StoragePointer<T>;
}
```
___
*[`corelib/src/starknet/storage.cairo` line 146 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5432#-Nvg8HUeDLCO6G9a-iAG:-Nvg8HUeDLCO6G9a-iAH:b-80z1a5) ([raw file](https://github.com/starkware-libs/cairo/blob/9d954c8c8b67cd628dc82435d44d08aa0db29209/corelib/src/starknet/storage.cairo#L146)):*
> ```Cairo
> pub trait StoragePathEntry<C, K, V> {
>     fn entry(self: StoragePath<C>, key: K) -> StoragePath<V>;
> }
> ```

TODO.



_Suggestion:_
```Cairo
/// Trait for updating the hash state with a value, using an `entry` method.
pub trait StoragePathEntry<C> {
    type K;
    type V;
    fn entry(self: StoragePath<C>, key: K) -> StoragePath<V>;
}
```
___
*[`crates/cairo-lang-starknet/src/plugin/storage.rs` line 534 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5432#-Nvg8cWH1MJROv0HUnLL:-Nvg8cWH1MJROv0HUnLM:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/9d954c8c8b67cd628dc82435d44d08aa0db29209/crates/cairo-lang-starknet/src/plugin/storage.rs#L534)):*
> ```XML
> }
> 
> fn handle_nonlegacy_mapping_storage_member(
> ```

doc

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5432)* status: 2 of 22 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 210 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5432#-Nvg8hmCBkGDxmHZnZaz:-Nvg8hmCBkGDxmHZnZb-:b-hfpv23) ([raw file](https://github.com/starkware-libs/cairo/blob/9d954c8c8b67cd628dc82435d44d08aa0db29209/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L210)):*
> ```XML
>                     StorageMapMemberAddressTrait, StorageMemberAddressTrait,
>                     StorageMapMemberAccessTrait, StorageMemberAccessTrait, 
>                     StorageAsPointer, StoragePointerAccess, StorageAsPath, StoragePathFinalize
> ```

remove.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5432)* status: 0 of 24 files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/starknet/storage.cairo` line 121 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5432#-Nvg7masDUPUJDst5rtc:-NvlX2co8l5cbP_ho5zj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9d954c8c8b67cd628dc82435d44d08aa0db29209/corelib/src/starknet/storage.cairo#L121)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`corelib/src/starknet/storage.cairo` line 131 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5432#-Nvg8AOS2oTeZRQOeazA:-NvlQNu-7uHD-ANk1L0u:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9d954c8c8b67cd628dc82435d44d08aa0db29209/corelib/src/starknet/storage.cairo#L131)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe just implement the `as_ptr` trait as well?
</blockquote></details>

Done.
___
*[`corelib/src/starknet/storage.cairo` line 146 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5432#-Nvg8HUeDLCO6G9a-iAG:-NvlXHJcCe_vGmr2mZcv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9d954c8c8b67cd628dc82435d44d08aa0db29209/corelib/src/starknet/storage.cairo#L146)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

TODO.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/storage.rs` line 534 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5432#-Nvg8cWH1MJROv0HUnLL:-NvlXS4z0EPt5faUhAIw:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9d954c8c8b67cd628dc82435d44d08aa0db29209/crates/cairo-lang-starknet/src/plugin/storage.rs#L534)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 210 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5432#-Nvg8hmCBkGDxmHZnZaz:-NvlQSOl2MRD6xFVk75R:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9d954c8c8b67cd628dc82435d44d08aa0db29209/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L210)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 24 of 24 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5432)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 395 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5432#-NvleWqX4fX6jF_1D5Hh:-NvleWqY14EU4MQ5cYBY:bx533q7) ([raw file](https://github.com/starkware-libs/cairo/blob/dac5bf5b845be66a1ea10c4edfd4d9a5626babe8/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L395)):*
> ```
>                  ^*^
> 
> error: Type annotations needed. Failed to infer ?0.
> ```

can we improve errors here?

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 21 of 22 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5432)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`corelib/src/starknet/storage.cairo` line 142 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5432#-Nvli9LP3AHtcGkb71kD:-Nvli9LP3AHtcGkb71kE:b-jfiy98) ([raw file](https://github.com/starkware-libs/cairo/blob/0a276ea461d294cfcbce788e8b583b905aa3fb53/corelib/src/starknet/storage.cairo#L142)):*
> ```Cairo
>         }
>     }
> }
> ```

as pointer



_Code quote:_
```Cairo
/// An implementation of `StoragePathFinalize` for any type that implements `Store`.
impl StorableStoragePathFinalize<T, +starknet::Store<T>> of StorageAsPointer<StoragePath<T>, T> {
    fn as_ptr(self: @StoragePath<T>) -> StoragePointer<T> {
        StoragePointer::<
            T
        > {
            address: starknet::storage_access::storage_base_address_from_felt252(
                core::hash::HashStateTrait::<core::poseidon::HashState>::finalize(*self.hash_state)
            )
        }
    }
}
```
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 395 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5432#-NvleWqX4fX6jF_1D5Hh:-NvliITw0MR9p_CME4pq:b-f2w00a) ([raw file](https://github.com/starkware-libs/cairo/blob/dac5bf5b845be66a1ea10c4edfd4d9a5626babe8/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L395)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Improved, but do we want to keep this test now that `Map` is enabled?
</blockquote></details>

why didit complain about a drop before and now doesn't?

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5432)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/starknet/storage.cairo` line 142 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5432#-Nvli9LP3AHtcGkb71kD:-NvlkQSV5IsOtgSvjRaS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0a276ea461d294cfcbce788e8b583b905aa3fb53/corelib/src/starknet/storage.cairo#L142)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

as pointer
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 395 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5432#-NvleWqX4fX6jF_1D5Hh:-Nvlj0sr7aMcb1tBYJTy:bxt01w1) ([raw file](https://github.com/starkware-libs/cairo/blob/dac5bf5b845be66a1ea10c4edfd4d9a5626babe8/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L395)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why didit complain about a drop before and now doesn't?
</blockquote></details>

The contract plugin ignored the `mapping` member, but the drop plugin didn't. It caused a discrepancy between the two.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5432)* status: 23 of 24 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 395 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5432#-NvleWqX4fX6jF_1D5Hh:-NvlktPgByVzfjelxJAE:b-ra2rnw) ([raw file](https://github.com/starkware-libs/cairo/blob/dac5bf5b845be66a1ea10c4edfd4d9a5626babe8/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L395)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

The contract plugin ignored the `mapping` member, but the drop plugin didn't. It caused a discrepancy between the two.
</blockquote></details>

in any case - let us keep the test for the time being.

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5432)* status: 23 of 24 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`corelib/src/starknet/storage.cairo` line 142 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5432#-Nvli9LP3AHtcGkb71kD:-Nvll-tK7Hd6R-J3AiTp:b-9tsmd2) ([raw file](https://github.com/starkware-libs/cairo/blob/0a276ea461d294cfcbce788e8b583b905aa3fb53/corelib/src/starknet/storage.cairo#L142)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

fix doc as well.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5432)* status: 23 of 24 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/starknet/storage.cairo` line 142 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5432#-Nvli9LP3AHtcGkb71kD:-Nvll9waEi5weDBH8Hyl:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0a276ea461d294cfcbce788e8b583b905aa3fb53/corelib/src/starknet/storage.cairo#L142)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix doc as well.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5432#-:-NvllkhX5QbrhwMcXxAT:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
