### PR TITLE
Made felt252 range the full possible range of logical values.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #4863
- #4848
- #4839
- #4813
- #4812 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4812)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 4 of 6 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4812)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/range_reduction.rs` line 64 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4812#-NoSAf_19gNwZow2eTX-:-NoSAf_19gNwZow2eTX0:b-kt8j11) ([raw file](https://github.com/starkware-libs/cairo/blob/3a67ff2ea4747fd85ce367a530379791f49f15ec/crates/cairo-lang-sierra/src/extensions/modules/range_reduction.rs#L64)):*
> ```XML
>         let out_range = Range::from_type_info(&out_ty_info)?;
> 
>         if in_range.size() < Felt252::prime().into() || !out_range.lower.is_zero() {
> ```

Doc this



_Code quote:_
```XML
 in_range.size() < Felt252::prime().into()
```

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r3, 1 of 5 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4812)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/test.rs` line 303 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4812#-NocKmvZ8BrQqC5BBYW_:-NocKmvZ8BrQqC5BBYWa:bpw4m32) ([raw file](https://github.com/starkware-libs/cairo/blob/70fa6c623c368dd63a8049515f9bda01d8f8cc2d/crates/cairo-lang-sierra/src/extensions/test.rs#L303)):*
> ```XML
> #[test_case("enum_snapshot_match", vec![type_arg("NonDupEnum")] => Ok(());
>             "enum_snapshot_match<NonDupEnum>")]
> #[test_case("constrain_range", vec![type_arg("felt252"), type_arg("BoundedInt0_3")]
> ```

These are going to be removed in the next PR?
___
*[`crates/cairo-lang-sierra/src/extensions/modules/range_reduction.rs` line 64 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4812#-NoSAf_19gNwZow2eTX-:-NocKzMU9A2wRu3Xzj-s:b7agr3x) ([raw file](https://github.com/starkware-libs/cairo/blob/3a67ff2ea4747fd85ce367a530379791f49f15ec/crates/cairo-lang-sierra/src/extensions/modules/range_reduction.rs#L64)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Doc this
</blockquote></details>

This code is being removed in the next PR, right?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4812)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra/src/extensions/test.rs` line 303 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4812#-NocKmvZ8BrQqC5BBYW_:-NocO3ld5FVewsMFqzGl:bb7sa0c) ([raw file](https://github.com/starkware-libs/cairo/blob/70fa6c623c368dd63a8049515f9bda01d8f8cc2d/crates/cairo-lang-sierra/src/extensions/test.rs#L303)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

These are going to be removed in the next PR?
</blockquote></details>

yes.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/range_reduction.rs` line 64 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4812#-NoSAf_19gNwZow2eTX-:-NoSCgCh8G7v2UiVri5W:bawy08l) ([raw file](https://github.com/starkware-libs/cairo/blob/3a67ff2ea4747fd85ce367a530379791f49f15ec/crates/cairo-lang-sierra/src/extensions/modules/range_reduction.rs#L64)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Doc this
</blockquote></details>

file deleted in next PR in any case.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4812)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/range_reduction.rs` line 64 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4812#-NoSAf_19gNwZow2eTX-:-NoejGP25yyAPwcdonAZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3a67ff2ea4747fd85ce367a530379791f49f15ec/crates/cairo-lang-sierra/src/extensions/modules/range_reduction.rs#L64)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

file deleted in next PR in any case.
</blockquote></details>

Done.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r1, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4812#-:-NofORW411wvDNbT7EVF:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2)

**Pull request merged**
