### PR TITLE
Add semantic to range operator.

### PR DESCRIPTION
**Pull request by liorgold2**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6274)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6274)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`corelib/src/traits.cairo` line 356 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6274#-O58RG-G9h2LwsvYybYr:-O58RG-G9h2LwsvYybYs:bxsh1o0) ([raw file](https://github.com/starkware-libs/cairo/blob/e27a0bba82ae7bbadf99838326d0ae708ab72373/corelib/src/traits.cairo#L356)):*
> ```Cairo
>     /// Handles the `..` operator. Returns the value of the expression `lower_bound..upper_bound`.
>     fn range(lower_bound: T, upper_bound: T) -> Self::RangeType;
> }
> ```

we no longer put new traits here.
move to ops/range/range.cairo.

add pub uses in `ops.cairo`.



_Code quote:_
```Cairo
pub trait RangeOp<T> {
    type RangeType;

    /// Handles the `..` operator. Returns the value of the expression `lower_bound..upper_bound`.
    fn range(lower_bound: T, upper_bound: T) -> Self::RangeType;
}
```
___
*[`corelib/src/iter/traits/iterator.cairo` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6274#-O58RkWb1GCEtEYUtQTD:-O58RkWb1GCEtEYUtQTE:be6m4vz) ([raw file](https://github.com/starkware-libs/cairo/blob/e27a0bba82ae7bbadf99838326d0ae708ab72373/corelib/src/iter/traits/iterator.cairo#L32)):*
> ```Cairo
> /// Represents the range [lower_bound, upper_bound).
> #[derive(Clone, Drop)]
> pub struct Range<T> {
> ```

move to `ops` as well.

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6274)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/traits.cairo` line 356 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6274#-O58RG-G9h2LwsvYybYr:-O58UWKD088phLmtBXjW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e27a0bba82ae7bbadf99838326d0ae708ab72373/corelib/src/traits.cairo#L356)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

we no longer put new traits here.
move to ops/range/range.cairo.

add pub uses in `ops.cairo`.
</blockquote></details>

Done.
___
*[`corelib/src/iter/traits/iterator.cairo` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6274#-O58RkWb1GCEtEYUtQTD:-O58V189EFaOhLZ-BRwI:b-fe2q0k) ([raw file](https://github.com/starkware-libs/cairo/blob/e27a0bba82ae7bbadf99838326d0ae708ab72373/corelib/src/iter/traits/iterator.cairo#L32)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

move to `ops` as well.
</blockquote></details>

Done.

Should I add all of them:
```
pub use range::{Range, RangeOp, RangeOpImpl, RangeIterator};
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6274)* status: 2 of 7 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/iter/traits/iterator.cairo` line 53 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6274#-O58Vw4i4XSakJbN5GMy:-O58Vw4i4XSakJbN5GMz:b79hxkj) ([raw file](https://github.com/starkware-libs/cairo/blob/e27a0bba82ae7bbadf99838326d0ae708ab72373/corelib/src/iter/traits/iterator.cairo#L53)):*
> ```Cairo
> 
> pub impl RangeIterator<
>     T, impl OneT: One<T>, +AddAssign<T, T>, +Copy<T>, +Drop<T>, +PartialEq<T>,
> ```

Which is better: `AddAssign` or `Add` (and change to `self.lower_bound = value + OneT::one()`?



_Code quote:_
```Cairo
+AddAssign<T, T>
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6274)* status: 2 of 7 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/traits.cairo` line 355 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6274#-O58WGFU6us8s5FkEU23:-O58WGFV2iSGIOEMFLgi:b87wuko) ([raw file](https://github.com/starkware-libs/cairo/blob/e27a0bba82ae7bbadf99838326d0ae708ab72373/corelib/src/traits.cairo#L355)):*
> ```Cairo
> 
>     /// Handles the `..` operator. Returns the value of the expression `lower_bound..upper_bound`.
>     fn range(lower_bound: T, upper_bound: T) -> Self::RangeType;
> ```

Should I support two different types? (only in the trait, I'll implement for `T,T`)



_Suggestion:_
```Cairo
fn range(lower_bound: S, upper_bound: T) -> Self::RangeType;
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6274)* status: 2 of 7 files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/iter/traits/iterator.cairo` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6274#-O58ZYW3CUYtDl2q01v9:-O58ZYW3CUYtDl2q01vA:b2nge6p) ([raw file](https://github.com/starkware-libs/cairo/blob/e27a0bba82ae7bbadf99838326d0ae708ab72373/corelib/src/iter/traits/iterator.cairo#L37)):*
> ```Cairo
> }
> 
> pub impl RangeOpImpl<
> ```

Is this a good name? Maybe `RangeOpRangeImpl` or `RangeImpl`?



_Code quote:_
```Cairo
RangeOpImpl
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, 2 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6274)* status: 3 of 9 files reviewed, 11 unresolved discussions (waiting on @liorgold2)

___
*[`corelib/src/lib.cairo` line 11 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6274#-O58Zu0X11slpEYa-4p5:-O58Zu0X11slpEYa-4p6:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/d53cf796099eeab316ca2618766e3dcd4da0abd8/corelib/src/lib.cairo#L11)):*
> ```Cairo
> };
> #[allow(unused_imports)]
> use ops::RangeOp;
> ```

remove



_Code quote:_
```Cairo
#[allow(unused_imports)]
use ops::RangeOp;
```
___
*[`corelib/src/ops.cairo` line 11 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6274#-O58__p_9z75BWgHvLnB:-O58__p_9z75BWgHvLnC:bfk5xu8) ([raw file](https://github.com/starkware-libs/cairo/blob/d53cf796099eeab316ca2618766e3dcd4da0abd8/corelib/src/ops.cairo#L11)):*
> ```Cairo
> pub use deref::DerefMut;
> mod range;
> pub use range::{Range, RangeOp, RangeOpImpl, RangeIterator};
> ```

unless impossible.



_Suggestion:_
```Cairo
mod range;
pub use range::{Range, RangeOp};
```
___
*[`corelib/src/ops/range.cairo` line 5 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6274#-O58ZxeSDUWW9A14l3Px:-O58ZxeSDUWW9A14l3Py:byajdyv) ([raw file](https://github.com/starkware-libs/cairo/blob/d53cf796099eeab316ca2618766e3dcd4da0abd8/corelib/src/ops/range.cairo#L5)):*
> ```Cairo
> use core::num::traits::One;
> 
> pub trait RangeOp<T> {
> ```

can you add some doc for the trait and trait type as well?
___
*[`corelib/src/ops/range.cairo` line 17 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6274#-O58_EGC7NTX6cGVmpKV:-O58_EGC7NTX6cGVmpKW:bvq9c8o) ([raw file](https://github.com/starkware-libs/cairo/blob/d53cf796099eeab316ca2618766e3dcd4da0abd8/corelib/src/ops/range.cairo#L17)):*
> ```Cairo
>     lower_bound: T,
>     upper_bound: T,
> }
> ```

how about shorter names here?



_Suggestion:_
```Cairo
#[derive(Clone, Drop)]
pub struct Range<Idx> {
    /// The lower bound of the range (inclusive).
    pub start: Idx,
    /// The upper bound of the range (exclusive).
    pub end: Idx,
}
```
___
*[`corelib/src/test/language_features/for_test.cairo` line 2 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6274#-O58_V4s8-YTSuCvCtFI:-O58_V4s8-YTSuCvCtFJ:b-rs7ze6) ([raw file](https://github.com/starkware-libs/cairo/blob/d53cf796099eeab316ca2618766e3dcd4da0abd8/corelib/src/test/language_features/for_test.cairo#L2)):*
> ```Cairo
> use core::iter::IntoIterator;
> use core::ops::RangeOpImpl;
> ```

works only with this?



_Code quote:_
```Cairo
use core::ops::RangeOpImpl;
```
___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 476 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6274#-O58_hxGE6Fbba6Z0Mgz:-O58_hxGE6Fbba6Z0Mh-:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d53cf796099eeab316ca2618766e3dcd4da0abd8/crates/cairo-lang-semantic/src/corelib.rs#L476)):*
> ```XML
>         BinaryOperator::Or(_) => ("BitOr", "bitor", false, CoreTraitContext::TopLevel),
>         BinaryOperator::Xor(_) => ("BitXor", "bitxor", false, CoreTraitContext::TopLevel),
>         BinaryOperator::DotDot(_) => ("RangeOp", "range", false, CoreTraitContext::TopLevel),
> ```





_Suggestion:_
```XML
        BinaryOperator::DotDot(_) => ("RangeOp", "range", false, CoreTraitContext::Ops),
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6274)* status: 3 of 9 files reviewed, 9 unresolved discussions (waiting on @liorgold2)

___
*[`corelib/src/traits.cairo` line 355 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6274#-O58WGFU6us8s5FkEU23:-O58_qYJ5OCaKmRWhBiY:b-n5g6ph) ([raw file](https://github.com/starkware-libs/cairo/blob/e27a0bba82ae7bbadf99838326d0ae708ab72373/corelib/src/traits.cairo#L355)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Should I support two different types? (only in the trait, I'll implement for `T,T`)
</blockquote></details>

one type seems reasonable for me.
___
*[`corelib/src/iter/traits/iterator.cairo` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6274#-O58ZYW3CUYtDl2q01v9:-O58aF_AEYZKVuyF-uUK:b-8i5fsp) ([raw file](https://github.com/starkware-libs/cairo/blob/e27a0bba82ae7bbadf99838326d0ae708ab72373/corelib/src/iter/traits/iterator.cairo#L37)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Is this a good name? Maybe `RangeOpRangeImpl` or `RangeImpl`?
</blockquote></details>

sounds like a good name as long as it isn't `pub` (if it has to be, lets understand why and solve this)
___
*[`corelib/src/iter/traits/iterator.cairo` line 53 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6274#-O58Vw4i4XSakJbN5GMy:-O58_we45tpguW0qtONc:b-64occ1) ([raw file](https://github.com/starkware-libs/cairo/blob/e27a0bba82ae7bbadf99838326d0ae708ab72373/corelib/src/iter/traits/iterator.cairo#L53)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Which is better: `AddAssign` or `Add` (and change to `self.lower_bound = value + OneT::one()`?
</blockquote></details>

i think i'd prefer `Add`.

but now that i think of it - maybe `AddAssign<T, BoundedInt<1, 1>>` instead of all.

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6274)* status: 0 of 9 files reviewed, 7 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/ops.cairo` line 11 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6274#-O58__p_9z75BWgHvLnB:-O58l7Kk4PQxfYpgX-3c:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d53cf796099eeab316ca2618766e3dcd4da0abd8/corelib/src/ops.cairo#L11)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

unless impossible.
</blockquote></details>

Done.
___
*[`corelib/src/ops/range.cairo` line 5 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6274#-O58ZxeSDUWW9A14l3Px:-O58kB1rBvaCe1AraSMx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d53cf796099eeab316ca2618766e3dcd4da0abd8/corelib/src/ops/range.cairo#L5)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can you add some doc for the trait and trait type as well?
</blockquote></details>

Done.
___
*[`corelib/src/ops/range.cairo` line 17 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6274#-O58_EGC7NTX6cGVmpKV:-O58kPG5AlVXIhAIGVYn:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d53cf796099eeab316ca2618766e3dcd4da0abd8/corelib/src/ops/range.cairo#L17)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

how about shorter names here?
</blockquote></details>

Done.
___
*[`corelib/src/test/language_features/for_test.cairo` line 2 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6274#-O58_V4s8-YTSuCvCtFI:-O58kYjq8t869XRo6h8A:b-tu1fsl) ([raw file](https://github.com/starkware-libs/cairo/blob/d53cf796099eeab316ca2618766e3dcd4da0abd8/corelib/src/test/language_features/for_test.cairo#L2)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

works only with this?
</blockquote></details>

Works fine now. Maybe it has to do with the fact that the impl wasn't in the same module of the trait before the changes you requested.
___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 476 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6274#-O58_hxGE6Fbba6Z0Mgz:-O58lOtu9KIr_imXSi86:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d53cf796099eeab316ca2618766e3dcd4da0abd8/crates/cairo-lang-semantic/src/corelib.rs#L476)):*
> ```XML
>         BinaryOperator::Or(_) => ("BitOr", "bitor", false, CoreTraitContext::TopLevel),
>         BinaryOperator::Xor(_) => ("BitXor", "bitxor", false, CoreTraitContext::TopLevel),
>         BinaryOperator::DotDot(_) => ("RangeOp", "range", false, CoreTraitContext::TopLevel),
> ```

Done.
___
*[`corelib/src/lib.cairo` line 11 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6274#-O58Zu0X11slpEYa-4p5:-O58lNYc9mlOHsFbqU4_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d53cf796099eeab316ca2618766e3dcd4da0abd8/corelib/src/lib.cairo#L11)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`corelib/src/iter/traits/iterator.cairo` line 53 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6274#-O58Vw4i4XSakJbN5GMy:-O58lp347i9MaMet0qCa:b-70zflu) ([raw file](https://github.com/starkware-libs/cairo/blob/e27a0bba82ae7bbadf99838326d0ae708ab72373/corelib/src/iter/traits/iterator.cairo#L53)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i think i'd prefer `Add`.

but now that i think of it - maybe `AddAssign<T, BoundedInt<1, 1>>` instead of all.
</blockquote></details>

Keeping it `AddAssign` for this PR.

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6274)* status: 0 of 9 files reviewed, 7 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/iter/traits/iterator.cairo` line 53 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6274#-O58Vw4i4XSakJbN5GMy:-O58qG82A7N1TaAAco6C:bb3i9vv) ([raw file](https://github.com/starkware-libs/cairo/blob/e27a0bba82ae7bbadf99838326d0ae708ab72373/corelib/src/iter/traits/iterator.cairo#L53)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Keeping it `AddAssign` for this PR.
</blockquote></details>

Changed to `Add`

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r2, 5 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6274)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`corelib/src/ops/range.cairo` line 21 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6274#-O58tNEkDnwXAo9uvp8I:-O58tNEkDnwXAo9uvp8J:b-6dz1a9) ([raw file](https://github.com/starkware-libs/cairo/blob/4d7827d249dc14e1e9ec6ca234e7664b3ca20b3b/corelib/src/ops/range.cairo#L21)):*
> ```Cairo
>     /// The upper bound of the range (exclusive).
>     end: T,
> }
> ```

Consider directly constructing the `Range` type.

and adding another `RangeIterator` type with the depenencies described above for the `RangeOp` trait.



_Suggestion:_
```Cairo
/// Represents the range [start, end).
#[derive(Clone, Drop)]
pub struct Range<T> {
    /// The lower bound of the range (inclusive).
    pub start: T,
    /// The upper bound of the range (exclusive).
    pub end: T,
}
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6274)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`corelib/src/ops/range.cairo` line 12 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6274#-O5DE3Vu5WWuiIjaUHxP:-O5DE3Vu5WWuiIjaUHxQ:burjo2) ([raw file](https://github.com/starkware-libs/cairo/blob/beb61ebb4bacd4b8bf6c86634f488d873f5c48db/corelib/src/ops/range.cairo#L12)):*
> ```Cairo
>     /// Handles the `..` operator. Returns the value of the expression `start..end`.
>     fn range(start: T, end: T) -> Self::RangeType;
> }
> ```

maybe even with `generate_trait`.
(we can simplify as it is only an internal implementation detail for the time being.



_Suggestion:_
```Cairo
/// Handles the range operator (`..`).
trait RangeOp<T> {
    /// Handles the `..` operator. Returns the value of the expression `start..end`.
    fn range_op(start: T, end: T) -> Range<T>;
}
```
___
*[`corelib/src/ops/range.cairo` line 20 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6274#-O5DDg1QDDaNdr4nEZtJ:-O5DDg1RCEgYizerMF00:b-a1nrv7) ([raw file](https://github.com/starkware-libs/cairo/blob/beb61ebb4bacd4b8bf6c86634f488d873f5c48db/corelib/src/ops/range.cairo#L20)):*
> ```Cairo
>     start: T,
>     /// The upper bound of the range (exclusive).
>     end: T,
> ```

`pub`s here still make sense to me - but i guess not a must for the time being.



_Suggestion:_
```Cairo
    /// The lower bound of the range (inclusive).
    pub start: T,
    /// The upper bound of the range (exclusive).
    pub end: T,
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6274)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/ops/range.cairo` line 12 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6274#-O5DE3Vu5WWuiIjaUHxP:-O5DF4Cb0UjXqFkSz66k:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/beb61ebb4bacd4b8bf6c86634f488d873f5c48db/corelib/src/ops/range.cairo#L12)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe even with `generate_trait`.
(we can simplify as it is only an internal implementation detail for the time being.
</blockquote></details>

Done.

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6274)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/ops/range.cairo` line 21 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6274#-O58tNEkDnwXAo9uvp8I:-O5DFNAt6cfUGkZlGfuN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4d7827d249dc14e1e9ec6ca234e7664b3ca20b3b/corelib/src/ops/range.cairo#L21)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Consider directly constructing the `Range` type.

and adding another `RangeIterator` type with the depenencies described above for the `RangeOp` trait.
</blockquote></details>

Done.
___
*[`corelib/src/ops/range.cairo` line 12 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6274#-O5DE3Vu5WWuiIjaUHxP:-O5DFRgj6bof5Of8sZb7:bd4hb0i) ([raw file](https://github.com/starkware-libs/cairo/blob/beb61ebb4bacd4b8bf6c86634f488d873f5c48db/corelib/src/ops/range.cairo#L12)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry, not done. Will look later.
___
*[`corelib/src/ops/range.cairo` line 20 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6274#-O5DDg1QDDaNdr4nEZtJ:-O5DFJHqB1MUB0BNHuVV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/beb61ebb4bacd4b8bf6c86634f488d873f5c48db/corelib/src/ops/range.cairo#L20)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

`pub`s here still make sense to me - but i guess not a must for the time being.
</blockquote></details>

Done.

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6274)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/ops/range.cairo` line 12 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6274#-O5DE3Vu5WWuiIjaUHxP:-O5DTLHE2msJF7PEqVXR:bee1d6l) ([raw file](https://github.com/starkware-libs/cairo/blob/beb61ebb4bacd4b8bf6c86634f488d873f5c48db/corelib/src/ops/range.cairo#L12)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Sorry, not done. Will look later.
</blockquote></details>

Actually, I prefer to keep it explicit as it is used by the core.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6274)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`corelib/src/ops/range.cairo` line 62 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6274#-O5DVLgTD_-3LoDYlfhp:-O5DVLgTD_-3LoDYlfhq:bfcm7qf) ([raw file](https://github.com/starkware-libs/cairo/blob/4cfd27b4fee5ba0c1b735bdbfc42224c7fb6a103/corelib/src/ops/range.cairo#L62)):*
> ```Cairo
> > of IntoIterator<Range<T>> {
>     type IntoIter = RangeIterator<T>;
>     impl Iterator = RangeIteratorImpl<T>;
> ```

not needed.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6274#-:-O5Dd4cP6ZZejVkMTDHE:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6274)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
