### PR TITLE
Internal audit changes.

### PR DESCRIPTION
**Pull request by liorgold2**
**Stack**:
- #5880
- #5876 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5876)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5876#-:-O0DoZHl73K5hKVFwq7A:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5876)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-starknet-classes/src/allowed_libfuncs_lists/all.json` line 82 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5876#-O0DuN3-4OfN5rzaKZaX:-O0DuN3-4OfN5rzaKZaY:bb7onj7) ([raw file](https://github.com/starkware-libs/cairo/blob/09f02bab223d0652ce131087dda4490d2fe2754f/crates/cairo-lang-starknet-classes/src/allowed_libfuncs_lists/all.json#L82)):*
> ```JSON
>         "felt252_sub",
>         "felt252_sub_const",
>         "add_circuit_input",
> ```

sort



_Code quote:_
```JSON
        "add_circuit_input",
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5876)* status: 6 of 13 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-starknet-classes/src/allowed_libfuncs_lists/all.json` line 82 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5876#-O0DuN3-4OfN5rzaKZaX:-O0EjZ5QAvXxLANqQfjN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/09f02bab223d0652ce131087dda4490d2fe2754f/crates/cairo-lang-starknet-classes/src/allowed_libfuncs_lists/all.json#L82)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

sort
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5876)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs` line 436 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5876#-O0Eq0QK1GuGUa0qw0Un:-O0Eq0QK1GuGUa0qw0Uo:bm8mu4k) ([raw file](https://github.com/starkware-libs/cairo/blob/6b050a6d6423330c789aa6d98bd8165ee39d8fd1/crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs#L436)):*
> ```XML
> 
>         // If the nullifier is zero, add an unsatisfiable constraint.
>         fail;
> ```

isn't this a little bit less efficient code-size-wise?
(we can see in the resulting casm)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5876)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs` line 436 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5876#-O0Eq0QK1GuGUa0qw0Un:-O0FqJvYCD4vZcvuPyzp:b-9pvaib) ([raw file](https://github.com/starkware-libs/cairo/blob/6b050a6d6423330c789aa6d98bd8165ee39d8fd1/crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs#L436)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

isn't this a little bit less efficient code-size-wise?
(we can see in the resulting casm)
</blockquote></details>

It is. But it's the right thing to do (e.g., it affects gas counting of the function).

**Review by orizi — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5876)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
