### PR TITLE
SemanticPlugin

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1513)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/semantic/src/diagnostic_test.rs` line 166 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1513#-NKIqtCYEDt64yVfwHZZ:-NKIqtCYEDt64yVfwHZ_:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/201b7f2675f1d2994b2303a97121c414a1d77f66/crates/semantic/src/diagnostic_test.rs#L166)):*
> ```XML
>             .patches
>             .translate(db.upcast(), diag.stable_location.diagnostic_location(db.upcast()).span)?;
>         Some(PluginMappedDiagnostic { span, message: "Mapped error.".into() })
> ```





_Suggestion:_
```XML
"Mapped error. {diag.format(db)}"
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1513)* status: 0 of 23 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/semantic/src/diagnostic_test.rs` line 166 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1513#-NKIqtCYEDt64yVfwHZZ:-NKIsM6LEIZljgq7OYMs:b-x4vsob) ([raw file](https://github.com/starkware-libs/cairo/blob/201b7f2675f1d2994b2303a97121c414a1d77f66/crates/semantic/src/diagnostic_test.rs#L166)):*
> ```XML
>             .patches
>             .translate(db.upcast(), diag.stable_location.diagnostic_location(db.upcast()).span)?;
>         Some(PluginMappedDiagnostic { span, message: "Mapped error.".into() })
> ```

In another PR

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 23 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1513#-:-NKItUfxDagvtCR33mNw:bnfp4nl)* status: 22 of 23 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1513)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/defs/src/plugin.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1513#-NKIuPFd4wPWEhkrlQrY:-NKIuPFd4wPWEhkrlQrZ:b-3kbmxd) ([raw file](https://github.com/starkware-libs/cairo/blob/201b7f2675f1d2994b2303a97121c414a1d77f66/crates/defs/src/plugin.rs#L10)):*
> ```XML
> use syntax::node::ids::SyntaxStablePtrId;
> 
> /// A trait for mapping plugin generated diagnostics to more readable diagnostics.
> ```

fix comment



_Code quote:_
```XML
A trait for mapping plugin generated diagnostics to more readable diagnostics
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1513)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/defs/src/plugin.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1513#-NKIuUmZ6Rk1Ru5k_cbJ:-NKIuUmZ6Rk1Ru5k_cbK:btdhpfl) ([raw file](https://github.com/starkware-libs/cairo/blob/201b7f2675f1d2994b2303a97121c414a1d77f66/crates/defs/src/plugin.rs#L45)):*
> ```XML
>     /// A diagnostics mapper, to allow more readable diagnostics that originate in plugin generated
>     /// virtual files.
>     pub token: DynMacroToken,
> ```

why is it called macro token?



_Code quote:_
```XML
MacroToken
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1513)* status: 14 of 23 files reviewed, 3 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/defs/src/test.rs` line 170 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1513#-NKJ-xOi3jdtq49QrmZK:-NKJ-xOi3jdtq49QrmZL:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b9840ebbfe4f1d36f90e42915e0688498390776e/crates/defs/src/test.rs#L170)):*
> ```XML
> 
> #[derive(Debug)]
> struct DummyToken;
> ```





_Suggestion:_
```XML
DummyAuxData
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1513)* status: 14 of 23 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/defs/src/plugin.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1513#-NKIuPFd4wPWEhkrlQrY:-NKIyobv9_8iQfdkEtqa:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/201b7f2675f1d2994b2303a97121c414a1d77f66/crates/defs/src/plugin.rs#L10)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

fix comment
</blockquote></details>

Done.
___
*[`crates/defs/src/plugin.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1513#-NKIuUmZ6Rk1Ru5k_cbJ:-NKIzgSWDMf-D1gL91Hs:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/201b7f2675f1d2994b2303a97121c414a1d77f66/crates/defs/src/plugin.rs#L45)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why is it called macro token?
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 13 of 23 files at r1, 9 of 9 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1513#-:-NKJ2xQV5q6Lu_kLcHuf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1513)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

___
*[`crates/defs/src/test.rs` line 170 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1513#-NKJ-xOi3jdtq49QrmZK:-NKJ0N312Ns58bdw3XH8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b9840ebbfe4f1d36f90e42915e0688498390776e/crates/defs/src/test.rs#L170)):*
> ```XML
> 
> #[derive(Debug)]
> struct DummyToken;
> ```

Done.

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 12 of 23 files at r1, 7 of 9 files at r3, 1 of 2 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1513)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1513)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
