### PR TITLE
Add readme for docs(1172)

### PR DESCRIPTION
**Pull request by ChengYueJia**
Add the readme int docs to show the ways how to view the docs locally.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1172)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1172)* status: 1 of 2 files reviewed, 10 unresolved discussions (waiting on @ChengYueJia)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1172#-NJ9P5Ww4G9wlcNA1EUj:-NJ9P5Ww4G9wlcNA1EUk:bjnmj5z) (no related file):*
for some reason this is not viewable on github as legal markdown, please fix.

___
___
*[`docs/reference/readme.md` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1172#-NJ9NVGp0SoAe33nl4IJ:-NJ9NVGp0SoAe33nl4IK:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f81a65de620978203beed0e4e1aeea4855515d4e/docs/reference/readme.md#L1)):*
> ```Markdown
> The docs is wrotten in [AsciiDoc](https://asciidoc.org/)(`.adoc`). You can view the docs locally in many ways.
> ```





_Suggestion:_
```Markdown
The docs are written in [AsciiDoc](https://asciidoc.org/)(`.adoc`). You can view the docs locally in many ways.
```
___
*[`docs/reference/readme.md` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1172#-NJ9NdpT2I6Sd6zHzDyy:-NJ9NdpT2I6Sd6zHzDyz:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f81a65de620978203beed0e4e1aeea4855515d4e/docs/reference/readme.md#L3)):*
> ```Markdown
> The docs is wrotten in [AsciiDoc](https://asciidoc.org/)(`.adoc`). You can view the docs locally in many ways.
> 
> - View  on IDE
> ```





_Suggestion:_
```Markdown
- View on IDE
```
___
*[`docs/reference/readme.md` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1172#-NJ9Nfv_59egQZeMxDOh:-NJ9Nfv_59egQZeMxDOi:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f81a65de620978203beed0e4e1aeea4855515d4e/docs/reference/readme.md#L9)):*
> ```Markdown
> ## View on IDE
> 
> - install `AsciiDoc`plugins in `VsCode` or `Intellij IDEA`
> ```





_Suggestion:_
```Markdown
- Install `AsciiDoc`plugins in `VsCode` or `Intellij IDEA`
```
___
*[`docs/reference/readme.md` line 24 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1172#-NJ9Njm76YsxUn04QCSr:-NJ9Njm76YsxUn04QCSs:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f81a65de620978203beed0e4e1aeea4855515d4e/docs/reference/readme.md#L24)):*
> ```Markdown
> > Tips:`pwd` is `cairo/docs/reference`
> 
> - convert specify file
> ```





_Suggestion:_
```Markdown
- Convert a single file
```
___
*[`docs/reference/readme.md` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1172#-NJ9NqKxDWoMvmEZp03e:-NJ9NqKxDWoMvmEZp03f:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f81a65de620978203beed0e4e1aeea4855515d4e/docs/reference/readme.md#L28)):*
> ```Markdown
> `asciidoctor src/Summary.adoc`
> 
> - convert all files
> ```





_Suggestion:_
```Markdown
Convert all files
```
___
*[`docs/reference/readme.md` line 33 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1172#-NJ9Nu1u7L_l8XOfnBIG:-NJ9Nu1u7L_l8XOfnBIH:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f81a65de620978203beed0e4e1aeea4855515d4e/docs/reference/readme.md#L33)):*
> ```Markdown
> ## View in Pdf
> ### Install `asciidoctor`
> > Tips: when you install `asciidoctor`, the `asciidoctor-pdf`also be installed.
> ```





_Suggestion:_
```Markdown
> Note: when you install `asciidoctor`, `asciidoctor-pdf` also be installed.
```
___
*[`docs/reference/readme.md` line 43 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1172#-NJ9O1lq5ZC77JdF02xc:-NJ9O1lq5ZC77JdF02xd:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f81a65de620978203beed0e4e1aeea4855515d4e/docs/reference/readme.md#L43)):*
> ```Markdown
> `apt-get install asciidoctor`
> ### Convert to Html
> > Tips:`pwd` is `cairo/docs/reference`
> ```





_Suggestion:_
```Markdown
> Tips: `pwd` is `cairo/docs/reference`
```
___
*[`docs/reference/readme.md` line 45 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1172#-NJ9O5NM4fTa1ux71GxE:-NJ9O5NM4fTa1ux71GxF:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f81a65de620978203beed0e4e1aeea4855515d4e/docs/reference/readme.md#L45)):*
> ```Markdown
> > Tips:`pwd` is `cairo/docs/reference`
> 
> - convert specify file
> ```





_Suggestion:_
```Markdown
- Convert a single file
```
___
*[`docs/reference/readme.md` line 50 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1172#-NJ9OCVx1CeFDukAgKt8:-NJ9OCVx1CeFDukAgKt9:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f81a65de620978203beed0e4e1aeea4855515d4e/docs/reference/readme.md#L50)):*
> ```Markdown
> 
> - convert all files
> ```





_Suggestion:_
```Markdown
- Convert all files
```

**Comment by ChengYueJia** [comment]
@orizi Thanks for pointing them out. It's done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1172#-:-NJEcfQZ0Im2tE3mwe0s:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ChengYueJia)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1172)* status: all files reviewed, 1 unresolved discussion (waiting on @ChengYueJia)

___
*[`docs/reference/readme.md` line 66 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1172#-NJEd-DSCLpzqHu1zlya:-NJEd-DSCLpzqHu1zlyb:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/bb74975034069e01446d2fa1ababf667e71a5579/docs/reference/readme.md#L66)):*
> ```Markdown
> ```
> 
> Now, there will generate `PDF` files.
> ```

.



_Suggestion:_
```Markdown
Now `PDF` versions of the documentation will be generated.
```

**Comment by ChengYueJia** [comment]
Yeah, Make sense. It's benn done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1172)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ChengYueJia)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1172)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ChengYueJia)

**Pull request merged**
