### PR TITLE
Named arguments: Strip '_' from parameter name.

### PR DESCRIPTION
**Pull request by liorgold2**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1669)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1669)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1090 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1669#-NLLJaCf7nBmN-9Ws6sL:-NLLJaCf7nBmN-9Ws6sM:b-xhhi7f) ([raw file](https://github.com/starkware-libs/cairo/blob/b2376acda088c2c35c5bd751402809ab3d6d6f75/crates/cairo-lang-semantic/src/expr/compute.rs#L1090)):*
> ```XML
>             // Compare `param.name` and `name`, after trimming underscores.
>             // This is done so that a (for example, unused) parameter named `_x` can be referred to
>             // both as `x` or `_x` in the call-site.
> ```

This seems sketchy to me... Could lead to potential issues I believe, if you leave this kind of degree of freedom in the signature (e.g. signautre hash, 3rd party tools that are not aware, etc..)

I think a better solution is to somehow explicitly allow the unuse of a parameter at the implementation.

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1669)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1669)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

**Comment by liorgold2** [comment]
Decided not to do this (at least not right now).

**Pull request closed without merging**
