### PR TITLE
Add OutputVarReferenceInfo::PartialParam.

### PR DESCRIPTION
**Pull request by liorgold2**
commit-id:087c9889

---

**Stack**:
- #1678
- #1676
- #1675
- #1677 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1677#-:-NLFWXS6BPmq19Odg3_K:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra/src/extensions/lib_func.rs` line 328 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1677#-NLFWR453TJN8BmfWFCm:-NLFWR453TJN8BmfWFCn:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c85a775ac27eb57908d2559d928ef9984d5e32f0/crates/cairo-lang-sierra/src/extensions/lib_func.rs#L328)):*
> ```XML
>     /// For example, it may be the first element of a struct.
>     ///
>     /// Information, such as whether the parameter was a temporary or local variable will be copied
> ```





_Suggestion:_
```XML
    /// Information such as whether the parameter was a temporary or local variable will be copied
    /// to the output variable.
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1677)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/lib_func.rs` line 328 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1677#-NLFWR453TJN8BmfWFCm:-NLFjCZF45nA0do3p1ij:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/189f266e731c7b4f3d5d988c4a77822628e379a1/crates/cairo-lang-sierra/src/extensions/lib_func.rs#L328)):*
> ```XML
>     /// For example, it may be the first element of a struct.
>     ///
>     /// Information, such as whether the parameter was a temporary or local variable will be copied
> ```

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1677)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1677)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
