### PR TITLE
Traits and impls doc

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2685)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2685** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2685" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2685?utm_source=stack-comment).

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2685)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`docs/reference/src/traits.adoc` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2685#-NS0m8JI9f8fRfhzD0xg:-NS0m8JJDCBd55vfIhIv:b-jdcak5) ([raw file](https://github.com/starkware-libs/cairo/blob/d8488db7795a497f9cd9d0b0a856df2f8007a77b/docs/reference/src/traits.adoc#L2)):*
> ```AsciiDoc
> = Cairo Traits and Impls
> Cairo traits and impls are a powerful feature of the Cairo language, providing a way to define abstract behavior and implement it in a concrete manner. Traits define a set of related functions, while impls provide the actual implementation of those functions. This feature promotes code reusability and modular design.
> ```

Consider breaking into shorter lines.
___
*[`docs/reference/src/traits.adoc` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2685#-NS0nsbb4rmB7rC5IuWu:-NS0nsbb4rmB7rC5IuWv:b-2542gs) ([raw file](https://github.com/starkware-libs/cairo/blob/d8488db7795a497f9cd9d0b0a856df2f8007a77b/docs/reference/src/traits.adoc#L2)):*
> ```AsciiDoc
> = Cairo Traits and Impls
> Cairo traits and impls are a powerful feature of the Cairo language, providing a way to define abstract behavior and implement it in a concrete manner. Traits define a set of related functions, while impls provide the actual implementation of those functions. This feature promotes code reusability and modular design.
> ```

Maybe mention impl names?
___
*[`docs/reference/src/traits.adoc` line 51 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2685#-NS0n6CY9rSqIpMJ-gYQ:-NS0n6CY9rSqIpMJ-gYR:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d8488db7795a497f9cd9d0b0a856df2f8007a77b/docs/reference/src/traits.adoc#L51)):*
> ```AsciiDoc
> 
> == `self` and Methods
> The self parameter in Cairo trait and impl functions represents a value of a specified type, allowing for a more convenient method-like syntax for that type. It must be the first parameter wof the function. A function defined in such a way can be called as a method on the value:
> ```





_Suggestion:_
```AsciiDoc
 parameter of the 
```
___
*[`docs/reference/src/traits.adoc` line 64 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2685#-NS0nNrL3pEi53Q5zmBk:-NS0nNrL3pEi53Q5zmBl:bbhfcik) ([raw file](https://github.com/starkware-libs/cairo/blob/d8488db7795a497f9cd9d0b0a856df2f8007a77b/docs/reference/src/traits.adoc#L64)):*
> ```AsciiDoc
> 
> == Search locations for methods.
> When a method is called, the compiler will search for a trait with a matching function name in the current scope.
> ```

Consider:



_Suggestion:_
```AsciiDoc
When a method is called, the compiler will search for a trait containing a function with a matching name
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2685)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @ilyalesokhin-starkware)

___
*[`docs/reference/src/traits.adoc` line 51 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2685#-NS0n6CY9rSqIpMJ-gYQ:-NS0p85_0ArbKHdhYGZh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d8488db7795a497f9cd9d0b0a856df2f8007a77b/docs/reference/src/traits.adoc#L51)):*
> ```AsciiDoc
> 
> == `self` and Methods
> The self parameter in Cairo trait and impl functions represents a value of a specified type, allowing for a more convenient method-like syntax for that type. It must be the first parameter wof the function. A function defined in such a way can be called as a method on the value:
> ```

Done.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2685#-:-NS0psUiBcAL3NhCnpG0:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`docs/reference/src/traits.adoc` line 2 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2685#-NS0rSqlCEkydRibrBzC:-NS0rSqlCEkydRibrBzD:b-hfpv23) ([raw file](https://github.com/starkware-libs/cairo/blob/f2f1914928a7cf6b220c7b679e87d8063ca430d3/docs/reference/src/traits.adoc#L2)):*
> ```AsciiDoc
> = Cairo Traits and Impls
> Cairo traits and impls are a powerful feature of the Cairo language, providing a way to define
> ```

remove.



_Code quote:_
```AsciiDoc
powerful feature
```

**Comment by ilyalesokhin-starkware** [comment]
*[`docs/reference/src/traits.adoc` line 25 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2685#-NS0sECj-4ZcUxni8d2Y:-NS0sECj-4ZcUxni8d2Z:b-awvlmq) ([raw file](https://github.com/starkware-libs/cairo/blob/f2f1914928a7cf6b220c7b679e87d8063ca430d3/docs/reference/src/traits.adoc#L25)):*
> ```AsciiDoc
>     let a = Display::display(5_usize);
>     // Can be called by the trait name.
>     let b = DisplayUsize::display(5_usize);
> ```

there is a missmatch between the comments and code.



_Code quote:_
```AsciiDoc
    // Can be called by the impl name.
    let a = Display::display(5_usize);
    // Can be called by the trait name.
    let b = DisplayUsize::display(5_usize);
```

**Comment by ilyalesokhin-starkware** [comment]
*[`docs/reference/src/traits.adoc` line 39 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2685#-NS0t4Ri-JjEqJ6fs0gC:-NS0t4Rj42MOwCizI3F1:bgombmb) ([raw file](https://github.com/starkware-libs/cairo/blob/f2f1914928a7cf6b220c7b679e87d8063ca430d3/docs/reference/src/traits.adoc#L39)):*
> ```AsciiDoc
> [source,rust]
> ----
> fn foo<T: impl TDisplay: Display<T>>(value: T) {
> ```

is 'Display' a trait or an impl?



_Suggestion:_
```AsciiDoc
T, impl TDisplay: Display<T>
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2685)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @spapinistarkware)

___
*[`docs/reference/src/traits.adoc` line 36 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2685#-NS0tXIr0S_DjBbRO6g0:-NS0tXIr0S_DjBbRO6g1:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f2f1914928a7cf6b220c7b679e87d8063ca430d3/docs/reference/src/traits.adoc#L36)):*
> ```AsciiDoc
> In Cairo, impls can be used as generic parameters, allowing for a more flexible and modular design.
> For example, the following code defines a function that takes a generic parameter `T` that
> implements the `Display` trait:
> ```





_Suggestion:_
```AsciiDoc
For example, the following code defines a function that takes a generic parameter `T` and 
and an implementation of the Display<T> trait.
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2685)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @spapinistarkware)

___
*[`docs/reference/src/traits.adoc` line 65 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2685#-NS0uMGv2Ab1gRzVctD_:-NS0uMGv2Ab1gRzVctDa:b-ulnlg3) ([raw file](https://github.com/starkware-libs/cairo/blob/f2f1914928a7cf6b220c7b679e87d8063ca430d3/docs/reference/src/traits.adoc#L65)):*
> ```AsciiDoc
> [source,rust]
> ----
> fn bar<T: impl TDisplay: Display<T>>(value: T) {
> ```

There is not 'self' parameter here.

is the first parameter always considered a 'self' parameter?



_Code quote:_
```AsciiDoc
T: impl TDisplay: Display<T>
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2685)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @ilyalesokhin-starkware)

___
*[`docs/reference/src/traits.adoc` line 2 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2685#-NS0rSqlCEkydRibrBzC:-NS0vHvPEt-vRuODETYG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f2f1914928a7cf6b220c7b679e87d8063ca430d3/docs/reference/src/traits.adoc#L2)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

remove.
</blockquote></details>

Done.
___
*[`docs/reference/src/traits.adoc` line 25 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2685#-NS0sECj-4ZcUxni8d2Y:-NS0vLos6qpliY5tMKI9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f2f1914928a7cf6b220c7b679e87d8063ca430d3/docs/reference/src/traits.adoc#L25)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

there is a missmatch between the comments and code.
</blockquote></details>

Done.
___
*[`docs/reference/src/traits.adoc` line 36 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2685#-NS0tXIr0S_DjBbRO6g0:-NS0vVeG4UA-L70au9nO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f2f1914928a7cf6b220c7b679e87d8063ca430d3/docs/reference/src/traits.adoc#L36)):*
> ```AsciiDoc
> In Cairo, impls can be used as generic parameters, allowing for a more flexible and modular design.
> For example, the following code defines a function that takes a generic parameter `T` that
> implements the `Display` trait:
> ```

Done.
___
*[`docs/reference/src/traits.adoc` line 39 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2685#-NS0t4Ri-JjEqJ6fs0gC:-NS0vW7K4WktqYU8qJ72:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f2f1914928a7cf6b220c7b679e87d8063ca430d3/docs/reference/src/traits.adoc#L39)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

is 'Display' a trait or an impl?
</blockquote></details>

Done.
___
*[`docs/reference/src/traits.adoc` line 65 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2685#-NS0uMGv2Ab1gRzVctD_:-NS0ve_w5PNPNARNwvQa:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f2f1914928a7cf6b220c7b679e87d8063ca430d3/docs/reference/src/traits.adoc#L65)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

There is not 'self' parameter here.

is the first parameter always considered a 'self' parameter?

</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`docs/reference/src/traits.adoc` line 37 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2685#-NS1-VEvDNM7ttI-8qN7:-NS1-VEvDNM7ttI-8qN8:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6ca733ffa697407e15e14b886141da60ade1baba/docs/reference/src/traits.adoc#L37)):*
> ```AsciiDoc
> In Cairo, impls can be used as generic parameters, allowing for a more flexible and modular design.
> For example, the following code defines a function that takes a generic parameter `T` and
> and implementation of the `Display<T>` trait:
> ```





_Suggestion:_
```AsciiDoc
an
```

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2685#-:-NS10Mn_Cd_sTHnUS5ef:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
