### PR TITLE
Added NonZeroTrait and moved non_zero to a separate module

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2624)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2624)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/non_zero.cairo` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2624#-NRc8knc52Jq1cnssb9D:-NRc8knc52Jq1cnssb9E:bbuq5gy) ([raw file](https://github.com/starkware-libs/cairo/blob/84c5bd672c9d6036dee8000c00dd139140bb1057/corelib/src/non_zero.cairo#L2)):*
> ```Cairo
> extern type NonZero<T>;
> impl NonZeroTCopy<T, impl TCopy: Copy::<T>> of Copy::<NonZero::<T>>;
> ```

maybe move all to the `zeroable` lib? it feels like all of these sort of stuff should be together.



_Code quote:_
```Cairo
extern type NonZero<T>;
impl NonZeroTCopy<T, impl TCopy: Copy::<T>> of Copy::<NonZero::<T>>;
impl NonZeroTDrop<T, impl TDrop: Drop::<T>> of Drop::<NonZero::<T>>;
enum IsZeroResult<T> {
    Zero: (),
    NonZero: NonZero<T>,
}
```
___
*[`corelib/src/non_zero.cairo` line 11 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2624#-NRc8uYp2ylcJKoO91tl:-NRc8uYp2ylcJKoO91tm:b-z8fnl0) ([raw file](https://github.com/starkware-libs/cairo/blob/84c5bd672c9d6036dee8000c00dd139140bb1057/corelib/src/non_zero.cairo#L11)):*
> ```Cairo
> 
> trait NonZeroTrait<T> {
>     fn unwrap_nz(self: NonZero<T>) -> T nopanic;
> ```

not sure i like the name - should probably either be `unwrap` or the full name `unwrap_non_zero`.
(i understand why you didn't want the simple `unwrap`)



_Code quote:_
```Cairo
unwrap_nz
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2624)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/non_zero.cairo` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2624#-NRc8knc52Jq1cnssb9D:-NRc_nFC5V4dq91GJnQ5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/84c5bd672c9d6036dee8000c00dd139140bb1057/corelib/src/non_zero.cairo#L2)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe move all to the `zeroable` lib? it feels like all of these sort of stuff should be together.
</blockquote></details>

Done.
___
*[`corelib/src/non_zero.cairo` line 11 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2624#-NRc8uYp2ylcJKoO91tl:-NRcPZim7Q5Jsnf-njaA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/84c5bd672c9d6036dee8000c00dd139140bb1057/corelib/src/non_zero.cairo#L11)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

not sure i like the name - should probably either be `unwrap` or the full name `unwrap_non_zero`.
(i understand why you didn't want the simple `unwrap`)
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2624#-:-NRcluttBt7uXtMqW4iH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2624)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2624)* status: 7 of 14 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`corelib/src/lib.cairo` line 396 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2624#-NRiEzWA2H2OjGcd5sBg:-NRiEzWA2H2OjGcd5sBh:b-2pfjt5) ([raw file](https://github.com/starkware-libs/cairo/blob/c806721d48172f9b14f07af7bdf4e9ef50d330f8/corelib/src/lib.cairo#L396)):*
> ```Cairo
> use zeroable::Zeroable;
> use zeroable::NonZero;
> use zeroable::unwrap_non_zero;
> ```

why is this required?



_Code quote:_
```Cairo
use zeroable::unwrap_non_zero;
```

**Review by orizi — COMMENTED** [review]
> Reviewed 6 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2624)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2624)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/lib.cairo` line 396 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2624#-NRiEzWA2H2OjGcd5sBg:-NRlgF1W7088nN9xBYhL:bb9wwbr) ([raw file](https://github.com/starkware-libs/cairo/blob/c806721d48172f9b14f07af7bdf4e9ef50d330f8/corelib/src/lib.cairo#L396)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why is this required?
</blockquote></details>

Because it is used in places...
It used to be directly in the corelib, so I left it there. I thought it makes sense to re-export it rather than hide it and add `use` explicitly everywhere.



_Code quote:_
```Cairo
unwrap_non_zero
```

**Pull request merged**
