### PR TITLE
Split diagnostics from gathering of inline data.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5102)

### CODE REVIEW

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5102#-:-Nr5d5U3BHuTTeqMOyoi:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5102)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5102#-Nr5dbj9CPqG33s5H1Kx:-Nr5dbj9CPqG33s5H1Ky:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/ea272c0957a68f9f59792a5a51cca4c5c4b44bd4/crates/cairo-lang-lowering/src/inline/mod.rs#L23)):*
> ```XML
> };
> 
> pub fn get_inline_diagnostics(
> ```

doc

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5102)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5102)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5102#-Nr5dbj9CPqG33s5H1Kx:-Nr5g3jdAJ-eWOL39o5M:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ea272c0957a68f9f59792a5a51cca4c5c4b44bd4/crates/cairo-lang-lowering/src/inline/mod.rs#L23)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5102#-:-Nr5nDbf6_bURV8OXx7z:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
