### PR TITLE
Handle functions that return never type.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2698)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2698)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/test_data/panic` line 162 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2698#-NS5WHau7SUYReb4n8i8:-NS5WHau7SUYReb4n8i9:bccb8gf) ([raw file](https://github.com/starkware-libs/cairo/blob/ce9f351899583c3c639685600677fd872285b50a/crates/cairo-lang-lowering/src/test_data/panic#L162)):*
> ```
> blk4:
> Statements:
>   (v6: (core::felt252,)) <- struct_construct(v4)
> ```

note that  core::never is assinged to core::felt252 here.



_Code quote:_
```
  (v6: (core::felt252,)) <- struct_construct(v4)
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2698)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/test_data/panic` line 162 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2698#-NS5WHau7SUYReb4n8i8:-NSaXVZ59CbSeXK-Qace:b3qd2ix) ([raw file](https://github.com/starkware-libs/cairo/blob/ce9f351899583c3c639685600677fd872285b50a/crates/cairo-lang-lowering/src/test_data/panic#L162)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

note that  core::never is assinged to core::felt252 here.
</blockquote></details>

fixed now.



_Code quote:_
```
core::never,)>) 
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2698)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 607 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2698#-NSaalYN7OR2jfReENOU:-NSaalYOExiD1qOL-vCy:b2nhdkj) ([raw file](https://github.com/starkware-libs/cairo/blob/d4e9b2cb750fc8505051072fdf8667eac3451c3b/crates/cairo-lang-lowering/src/lower/mod.rs#L607)):*
> ```XML
>         .add(ctx, &mut builder.statements);
> 
>         if ret_ty == never_ty(ctx.db.upcast()) {
> ```

Doc

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2698)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 607 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2698#-NSaalYN7OR2jfReENOU:-NSdhRRR2egbJ8TqP7ml:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d4e9b2cb750fc8505051072fdf8667eac3451c3b/crates/cairo-lang-lowering/src/lower/mod.rs#L607)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/block_generator_test_data/panic` line 63 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2698#-NSdhUc88BeYuQLFV0OM:-NSdhUc88BeYuQLFV0ON:b-rpkzm2) ([raw file](https://github.com/starkware-libs/cairo/blob/5adc2666d372ddeb1296e9564c8f35211fb6f93c/crates/cairo-lang-sierra-generator/src/block_generator_test_data/panic#L63)):*
> ```
>     PanicResult::Ok(v9) => blk3,
>     PanicResult::Err(v11) => blk4,
>   })
> ```

Note that this is still not optimal.

ideally, I would have

extern fn propogate_error(err: PanicResult::<(core::never,)>) -> PanicResult::<T>



_Code quote:_
```
Statements:
  (v8: core::PanicResult::<(core::never,)>) <- test::no_inline_panic()
End:
  Match(match_enum(v8) {
    PanicResult::Ok(v9) => blk3,
    PanicResult::Err(v11) => blk4,
  })
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2698#-:-NSdnf2g7M5vhcuPeDI3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware and @yuvalsw)

**Pull request merged**
