### PR TITLE
Add int_range_try_new libfunc.

### PR DESCRIPTION
**Pull request by liorgold2**
**Stack**:
- #6298
- #6289
- #6288 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6288)

### CODE REVIEW

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6288)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/range.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6288#-O5IfmPF6DiuYaQ4cXbm:-O5IfmPF6DiuYaQ4cXbn:bjqxx39) ([raw file](https://github.com/starkware-libs/cairo/blob/e3e3115c4eaa2deb690475ba8641943842f75648/crates/cairo-lang-sierra/src/extensions/modules/range.rs#L120)):*
> ```XML
>                 },
>                 // Failure.
>                 BranchSignature {
> ```

I wonder if I should return the range `[y, y]` in the failure branch. Currently, the high level code looks like:
```
        match internal::range_try_new(self.start, self.end) {
            Option::Some(range) => range,
            Option::None => internal::range_try_new(self.end, self.end).unwrap(),
        }
```
Note the `unwrap()` which makes it panicable (unnecessarily). 

The two ways to solve it (if we want to) are:
1. Return the range `[y, y]` on failure.
2. Add another libfunc for constructing an empty range `[a, a]` (which never fails)

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6288)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/range.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6288#-O5IfmPF6DiuYaQ4cXbm:-O5Iut3RDK7rhYkilhrY:b-vdl4cr) ([raw file](https://github.com/starkware-libs/cairo/blob/e3e3115c4eaa2deb690475ba8641943842f75648/crates/cairo-lang-sierra/src/extensions/modules/range.rs#L120)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

I wonder if I should return the range `[y, y]` in the failure branch. Currently, the high level code looks like:
```
        match internal::range_try_new(self.start, self.end) {
            Option::Some(range) => range,
            Option::None => internal::range_try_new(self.end, self.end).unwrap(),
        }
```
Note the `unwrap()` which makes it panicable (unnecessarily). 

The two ways to solve it (if we want to) are:
1. Return the range `[y, y]` on failure.
2. Add another libfunc for constructing an empty range `[a, a]` (which never fails)
</blockquote></details>

making `Range` `constable` makes sense as  well.

but returning it in the `Result::Err` makes sense to me (as it actually costs nothing).

but if we add it as `constable` we can than just `(One::one(), One::one())` or something like it.

**Review by orizi — COMMENTED** [review]
> Reviewed 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6288)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6288)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/range.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6288#-O5IfmPF6DiuYaQ4cXbm:-O5K9E751awQfuUHs8MQ:b-umso6g) ([raw file](https://github.com/starkware-libs/cairo/blob/e3e3115c4eaa2deb690475ba8641943842f75648/crates/cairo-lang-sierra/src/extensions/modules/range.rs#L120)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

making `Range` `constable` makes sense as  well.

but returning it in the `Result::Err` makes sense to me (as it actually costs nothing).

but if we add it as `constable` we can than just `(One::one(), One::one())` or something like it.
</blockquote></details>

I went with returning `[y, y)` or failure as this is the simplest solution.
Done in another PR.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6288#-:-O5KJcjc9VbJmOHh8ZRn:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
