### PR TITLE
Add *BuiltinCost types.

### PR DESCRIPTION
**Pull request by liorgold2**
commit-id:2dc7bd6f

---

**Stack**:
- #1242
- #1236
- #1221
- #1220 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1220)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/sierra/src/extensions/modules/builtin_cost.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1220#-NIafjIL29JI8WJSYcC6:-NIafjIL29JI8WJSYcC7:b2duxns) ([raw file](https://github.com/starkware-libs/cairo/blob/8fa0c0fa1d2abc7240d89cc76295aa8027473b20/crates/sierra/src/extensions/modules/builtin_cost.rs#L59)):*
> ```XML
>     fn by_id(id: &GenericTypeId) -> Option<Self> {
>         for token_type in CostTokenType::iter() {
>             // TODO(lior): Change name to camel case.
> ```

isn't it already?



_Code quote:_
```XML
            // TODO(lior): Change name to camel case.
```

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1220)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1220)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/sierra/src/extensions/modules/builtin_cost.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1220#-NIafjIL29JI8WJSYcC6:-NIbbY653dv9Tbh6L67r:bvze2lz) ([raw file](https://github.com/starkware-libs/cairo/blob/8fa0c0fa1d2abc7240d89cc76295aa8027473b20/crates/sierra/src/extensions/modules/builtin_cost.rs#L59)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

isn't it already?
</blockquote></details>

Yep. Removed. Thanks!

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1220#-:-NIbhr4rE44Y4rWGk_Ya:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1220)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
