### PR TITLE
Add get_builtin_costs libfunc.

### PR DESCRIPTION
**Pull request by liorgold2**
commit-id:7bb569e8

---

**Stack**:
- #1634
- #1632 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1632#-:-NKryBwg9pSOjIQaBauS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1632)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1632#-NKrzOQ0DV9NaH9GKIdR:-NKrzOQ0DV9NaH9GKIdS:b-txq9of) ([raw file](https://github.com/starkware-libs/cairo/blob/303bf120bb33612d62e86bb90e36b17a30f696bb/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L102)):*
> ```XML
>     let mut relocations: Vec<RelocationEntry> = Vec::new();
> 
>     // Maps statement_idx to program_offset.
> ```

update comment.



_Code quote:_
```XML
 // Maps statement_idx to program_offset.
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1632)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/relocations.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1632#-NKrzV4S4L2Mp-q-IadQ:-NKrzV4S4L2Mp-q-IadR:b27kxjp) ([raw file](https://github.com/starkware-libs/cairo/blob/303bf120bb33612d62e86bb90e36b17a30f696bb/crates/cairo-lang-sierra-to-casm/src/relocations.rs#L15)):*
> ```XML
>     RelativeStatementId(StatementIdx),
>     /// Points to the first felt after the program code.
>     EndOfProgram,
> ```

this is still relative.

Ie end - curr_pc



_Code quote:_
```XML
/// Points to the first felt after the program code.
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1632)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1632)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1632#-NKrzOQ0DV9NaH9GKIdR:-NKs5Y-aCZ2nClFAKbjv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/303bf120bb33612d62e86bb90e36b17a30f696bb/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L102)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

update comment.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/relocations.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1632#-NKrzV4S4L2Mp-q-IadQ:-NKs59iYEXQfZxssTVm3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/303bf120bb33612d62e86bb90e36b17a30f696bb/crates/cairo-lang-sierra-to-casm/src/relocations.rs#L15)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

this is still relative.

Ie end - curr_pc
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1632#-:-NKs5lUOCsU-7cFLyGrv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1632)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware and @orizi)

**Pull request merged**
