### PR TITLE
Updated storage-read and write to work with u8 offset.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1752)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1752)* status: 0 of 17 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/starknet.cairo` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1752#-NLa70f-E52InDj_VbTR:-NLa70f-E52InDj_VbTS:b8qb4z1) ([raw file](https://github.com/starkware-libs/cairo/blob/be43d9c5923ed4596b211cb7127b761a327a50de/corelib/starknet.cairo#L19)):*
> ```Cairo
> // data availability guarantees.
> extern fn storage_read_syscall(
>     address_domain: felt, address: StorageAddress, offset: u8,
> ```

I don't understand why these are in the api of the function. Why not just storage_read(felt)->felt?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1752)* status: 0 of 17 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`corelib/starknet.cairo` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1752#-NLa70f-E52InDj_VbTR:-NLeIsxN7E4G3Rzd8oPQ:bm5hl90) ([raw file](https://github.com/starkware-libs/cairo/blob/be43d9c5923ed4596b211cb7127b761a327a50de/corelib/starknet.cairo#L19)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I don't understand why these are in the api of the function. Why not just storage_read(felt)->felt?
</blockquote></details>

we need the domain for handling L1 accesses AFAIK, and we need the offset to support reading of structs (as base addresses are in range [0,2**251 - 256)

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1752)* status: 0 of 17 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/starknet.cairo` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1752#-NLa70f-E52InDj_VbTR:-NLoMs3c5vdp4XRsneZ7:b53lxna) ([raw file](https://github.com/starkware-libs/cairo/blob/be43d9c5923ed4596b211cb7127b761a327a50de/corelib/starknet.cairo#L19)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

we need the domain for handling L1 accesses AFAIK, and we need the offset to support reading of structs (as base addresses are in range [0,2**251 - 256)
</blockquote></details>

I'm still not convinced. It doesn't sound like it genuienly models the storage interface.
why not just allow readinf from any u251?

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1752)* status: 0 of 17 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware, @liorgold2, and @orizi)

___
*[`corelib/starknet.cairo` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1752#-NLa70f-E52InDj_VbTR:-NLohe354r1OhXFwVpgt:b-csphci) ([raw file](https://github.com/starkware-libs/cairo/blob/be43d9c5923ed4596b211cb7127b761a327a50de/corelib/starknet.cairo#L19)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I'm still not convinced. It doesn't sound like it genuienly models the storage interface.
why not just allow readinf from any u251?
</blockquote></details>

I discussed this with @liorgold2 and @ilyalesokhin-starkware. We are fine with the suggestion of hacing 2 types: u251, and something like AddrBase (bounded by `2**251-256`), and the address here will u251. WDYT about that?
___
*[`corelib/starknet.cairo` line 22 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1752#-NLoi8DB9InpsBB0W-2F:-NLoi8DB9InpsBB0W-2G:bvyqw46) ([raw file](https://github.com/starkware-libs/cairo/blob/27ccc235e5c0b19a3a2139666468f6594e738601/corelib/starknet.cairo#L22)):*
> ```Cairo
> ) -> Result::<felt, felt> implicits(GasBuiltin, System) nopanic;
> extern fn storage_write_syscall(
>     address_domain: felt, address: StorageAddress, offset: u8, value: felt,
> ```

WDYT about adding a type for the AddressDomain? It was confusing to me until I asked ilya what it is. I think it can help the readability and API.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1752)* status: 0 of 17 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

___
*[`corelib/starknet.cairo` line 22 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1752#-NLoi8DB9InpsBB0W-2F:-NLpUq7FCenQy_0R803c:b-8yps8q) ([raw file](https://github.com/starkware-libs/cairo/blob/27ccc235e5c0b19a3a2139666468f6594e738601/corelib/starknet.cairo#L22)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

WDYT about adding a type for the AddressDomain? It was confusing to me until I asked ilya what it is. I think it can help the readability and API.
</blockquote></details>

How would the type AddressDomain have help you?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 6 of 17 files at r1, 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1752)* status: 8 of 17 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1752)* status: 8 of 17 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @liorgold2)

___
*[`corelib/starknet.cairo` line 22 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1752#-NLoi8DB9InpsBB0W-2F:-NLt_SCA66__6t7ENogf:b-ynhxml) ([raw file](https://github.com/starkware-libs/cairo/blob/27ccc235e5c0b19a3a2139666468f6594e738601/corelib/starknet.cairo#L22)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

How would the type AddressDomain have help you?
</blockquote></details>

I thought it was some address (big number). We can add doc on the type AddressDomain to explain what it is, instead.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1752)* status: 8 of 17 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware, @liorgold2, and @spapinistarkware)

___
*[`corelib/starknet.cairo` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1752#-NLa70f-E52InDj_VbTR:-NLtcizk8ZOPBAMC8J66:b-9g5098) ([raw file](https://github.com/starkware-libs/cairo/blob/be43d9c5923ed4596b211cb7127b761a327a50de/corelib/starknet.cairo#L19)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I discussed this with @liorgold2 and @ilyalesokhin-starkware. We are fine with the suggestion of hacing 2 types: u251, and something like AddrBase (bounded by `2**251-256`), and the address here will u251. WDYT about that?
</blockquote></details>

This seems very cumbersome, especially when this is the only proper usage of this type.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1752)* status: 8 of 17 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @liorgold2)

___
*[`corelib/starknet.cairo` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1752#-NLa70f-E52InDj_VbTR:-NLuLN-fDS1UPqkk2KdE:b-gjolm5) ([raw file](https://github.com/starkware-libs/cairo/blob/be43d9c5923ed4596b211cb7127b761a327a50de/corelib/starknet.cairo#L19)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

This seems very cumbersome, especially when this is the only proper usage of this type.
</blockquote></details>

According to you. The users might want to do something else. This suggestion descirbes the API better.

**Comment by orizi** [comment]
Closing pull request: commit has gone away

**Pull request closed without merging**
