### PR TITLE
Remove file path from sierra location tests.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4882)

### CODE REVIEW

**Review by TomerStarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4882#-:-NopkONI51CrTuySFaGj:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4882)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-sierra-generator/src/sierra_location_test.rs` line 44 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4882#-NopmFst1_p1qZc879O_:-NopmFst1_p1qZc879Oa:b-ivw8qq) ([raw file](https://github.com/starkware-libs/cairo/blob/0688f5387cbffaf8444e2936eac9b9ff8320e32c/crates/cairo-lang-sierra-generator/src/sierra_location_test.rs#L44)):*
> ```XML
>             let diagnostic_str = format!("{:?}", location.diagnostic_location(db).debug(db));
>             // Remove the file name (first line) from the diagnostic string.
>             format!("Originating location:\n{}", diagnostic_str.lines().skip(1).join("\n"))
> ```

call the inner function instead.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4882)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi and @TomerStarkware)

___
*[`crates/cairo-lang-sierra-generator/src/sierra_location_test.rs` line 44 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4882#-NopmFst1_p1qZc879O_:-Nopnzk7BDMFlXCQTtzA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0688f5387cbffaf8444e2936eac9b9ff8320e32c/crates/cairo-lang-sierra-generator/src/sierra_location_test.rs#L44)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

call the inner function instead.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4882#-:-NopoAwo5ebY2VbsbowQ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
