### PR TITLE
felt -> felt252

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2479)

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
> Reviewed 127 of 292 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2479)* status: 127 of 293 files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 6 of 292 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2479)* status: 133 of 293 files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 161 of 292 files at r1, 2 of 3 files at r2, 4 of 4 files at r4, 1 of 1 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2479#-:-NQW3BF_3gKFEwcFSQ7v:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler_test.rs` line 32 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2479#-NQW0stiDSJ3qIjUG8_J:-NQW0stiDSJ3qIjUG8_K:b-xxu2qe) ([raw file](https://github.com/starkware-libs/cairo/blob/dd93d03f8cee0467c163ead688471298529ab351/crates/cairo-lang-sierra-to-casm/src/compiler_test.rs#L32)):*
> ```XML
>                 libfunc call_box_and_back = function_call<user@box_and_back>;
> 
>                 rename_felt252([1]) -> ([1]);                      // #0
> ```

The statement numbering lost the alignment.
___
*[`docs/reference/src/notation.adoc` line 20 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2479#-NQVz35PDRMAE1-qy0Ts:-NQVz35PDRMAE1-qy0Tt:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/dd93d03f8cee0467c163ead688471298529ab351/docs/reference/src/notation.adoc#L20)):*
> ```AsciiDoc
> | `x{a}`                  | `[0-9a-fA-F]{2}`              | Exactly `a` repetitions of `x`
> | `x{a,b}`                | `[0-9a-fA-F]{1,6}`            | `a` to `b` repetitions of `x`
> | `&#124;`                | `felt252 &#124; int`             | Either one or another
> ```





_Suggestion:_
```AsciiDoc
| `&#124;`                | `felt252 &#124; int`          | Either one or anothe
```

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 292 files at r1, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2479)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2479)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
