### PR TITLE
Iterate generic params once.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4461)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4461)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/generics` line 486 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4461#-NjwKyq24rKuFr_ipFN0:-NjwKyq3CyK4ZTr-qDsP:bv1stug) ([raw file](https://github.com/starkware-libs/cairo/blob/fe343a9eb32ee4eddc9c3e4569e95f0236a84f8b/crates/cairo-lang-semantic/src/expr/test_data/generics#L486)):*
> ```
> 
> //! > module_code
> trait MyTrait<+Drop<T>, T> {
> ```

pub trait DemandReport<R: DemandReporter<Var>, Var> {}
is a valid syntax in rust.



_Code quote:_
```
trait MyTrait<+Drop<T>, T> {
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4461)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/generics` line 486 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4461#-NjwKyq24rKuFr_ipFN0:-Njx5wsJ8NE-9d6QWph9:b4celco) ([raw file](https://github.com/starkware-libs/cairo/blob/fe343a9eb32ee4eddc9c3e4569e95f0236a84f8b/crates/cairo-lang-semantic/src/expr/test_data/generics#L486)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

pub trait DemandReport<R: DemandReporter<Var>, Var> {}
is a valid syntax in rust.
</blockquote></details>

yes, this should be fine.
___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 218 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4461#-Njx6ibcBnqlNC6Kkmj3:-Njx6ibcBnqlNC6Kkmj4:b-zbxfpe) ([raw file](https://github.com/starkware-libs/cairo/blob/fe343a9eb32ee4eddc9c3e4569e95f0236a84f8b/crates/cairo-lang-semantic/src/items/generics.rs#L218)):*
> ```XML
>         }
>     }
>     let generic_param_syntax = opt_generic_param_syntax.unwrap();
> ```

what happens in the case of:
```
trait MyTrait<Drop<T>, Copy<T>> { .. }
```
(i understand this would have happened before as well)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4461)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 218 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4461#-Njx6ibcBnqlNC6Kkmj3:-Nk9kClY1viFlSZfYNdr:b-32768w) ([raw file](https://github.com/starkware-libs/cairo/blob/fe343a9eb32ee4eddc9c3e4569e95f0236a84f8b/crates/cairo-lang-semantic/src/items/generics.rs#L218)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

what happens in the case of:
```
trait MyTrait<Drop<T>, Copy<T>> { .. }
```
(i understand this would have happened before as well)
</blockquote></details>

why is this a special case?

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4461)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4461)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
