### PR TITLE
Add serialized array macro

### PR DESCRIPTION
**Pull request by iamvukasin**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5386)

### CODE REVIEW

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5386)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @iamvukasin and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5386#-Nv316oAEyjon-wiMqL3:-Nv316oAEyjon-wiMqL4:b-mssmm2) (no related file):*
The snippets look fine. Changing reviewer to @orizi.

TBH, This doesn't look like something worthy adding to the standard library, and I'd rather see this as a macro package, when we'll release them in Scarb.

___

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5386)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @iamvukasin and @mkaput)

___
*[`crates/cairo-lang-semantic/src/inline_macros/serialized_array.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5386#-Nv31xMr9red-egEmkK6:-Nv31xMr9red-egEmkK7:bblcrrk) ([raw file](https://github.com/starkware-libs/cairo/blob/78cb07ba37c5b44e93c7a3f873729b00fa1ac90b/crates/cairo-lang-semantic/src/inline_macros/serialized_array.rs#L9)):*
> ```XML
> use cairo_lang_syntax::node::{ast, TypedSyntaxNode};
> 
> #[derive(Debug, Default)]
> ```

can be replaced with:
```
fn serialized<T, +Serde<T>>(t: T) {
    let mut arr = Default::default();
    Serde::<T>::serde(t, ref arr);
    arr
}
```
and used as:
```
serialized((1, 2, 3_u256))
```

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5386)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @iamvukasin and @orizi)

___
*[`crates/cairo-lang-semantic/src/inline_macros/serialized_array.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5386#-Nv31xMr9red-egEmkK6:-Nv5nnSE-8GHn9um1Y_w:b-u16qlm) ([raw file](https://github.com/starkware-libs/cairo/blob/78cb07ba37c5b44e93c7a3f873729b00fa1ac90b/crates/cairo-lang-semantic/src/inline_macros/serialized_array.rs#L9)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can be replaced with:
```
fn serialized<T, +Serde<T>>(t: T) {
    let mut arr = Default::default();
    Serde::<T>::serde(t, ref arr);
    arr
}
```
and used as:
```
serialized((1, 2, 3_u256))
```
</blockquote></details>

This one is smart! And again, to my taste, this looks like a util that I'd rather see copy-pasted into your codebase or upstreamed to Alexandria if they'd be willing to accept it

**Comment by iamvukasin** [comment]
I didn't know about `serialized` and that you can use a tuple for this. In any case, I think it is a useful util (we use it a lot for both production contracts and tests). It would be good to have it available somewhere (in stdlib, Alexandria or somewhere else) since it is way more readable and less error-prone.

If you think it is not for this repo, I can open a PR for Alexandria and add `serialized`.

> I'd rather see this as a macro package, when we'll release them in Scarb.

Looking forward to it!

**Review by orizi — COMMENTED** [review]
in any case - shouldn't be a macro - definitely not in the cairo-lang repo itself - so this PR should be closed.

the fn itself can be in alexandria IMO - as currently we don't have a proper place for such utils in corelib, unless we have specific suggestions for location in the corelib.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5386#-:-Nv69fAM7CIVE2GJtqri:b-jeqjyz)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @iamvukasin and @mkaput)

**Comment by mkaput** [comment]
Seems like we're at the dead end here. Closing.

**Pull request closed without merging**
