### PR TITLE
infer trait implementations based on trait types

### PR DESCRIPTION
**Pull request by TomerStarkware**

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6600)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @piotmag769, and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference/canonic.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6600#-OB4xvtk7H8L7u39glNU:-OB4xvtk7H8L7u39glNV:bardjv3) ([raw file](https://github.com/starkware-libs/cairo/blob/b8eea9eab863c72d6669ab5f643cccad0a90049e/crates/cairo-lang-semantic/src/expr/inference/canonic.rs#L42)):*
> ```XML
> /// A canonical representation of a concrete trait that needs to be solved.
> #[derive(Clone, PartialEq, Hash, Eq, Debug, SemanticObject)]
> pub struct CanonicalTrait(pub ConcreteTraitId, pub ImplVarTraitItemMappings);
> ```

and fix doc.



_Suggestion:_
```XML
pub struct CanonicalTrait {
    pub id: ConcreteTraitId,
    pub mappings: ImplVarTraitItemMappings,
}
```
___
*[`crates/cairo-lang-semantic/src/expr/inference/conform.rs` line 176 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6600#-OB4xVU442Nh2jZdbedr:-OB4xVU442Nh2jZdbeds:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b8eea9eab863c72d6669ab5f643cccad0a90049e/crates/cairo-lang-semantic/src/expr/inference/conform.rs#L176)):*
> ```XML
>                     parent_function: closure0.parent_function,
>                 };
>                 Ok((TypeLongId::Closure(closure0).intern(self.db), n_snapshots))
> ```





_Suggestion:_
```XML
                Ok((TypeLongId::Closure(ClosureTypeLongId {
                    param_tys,
                    ret_ty,
                    captured_types,
                    wrapper_location: closure0.wrapper_location,
                    parent_function: closure0.parent_function,
                }).intern(self.db), n_snapshots))
```
___
*[`crates/cairo-lang-semantic/src/expr/inference/solver.rs` line 230 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6600#-OB4yDBu3MzS0616jTp1:-OB4yDBv7Ila-cAij3K6:b9vicx7) ([raw file](https://github.com/starkware-libs/cairo/blob/b8eea9eab863c72d6669ab5f643cccad0a90049e/crates/cairo-lang-semantic/src/expr/inference/solver.rs#L230)):*
> ```XML
>                 inference.reduce_impl_impl(ImplImplId::new(candidate_impl, *trait_impl, db))?;
>             inference.conform_impl(impl2, *impl_id)?;
>         }
> ```

and make sure (and doc) the conform direction is correct.



_Suggestion:_
```XML
        for (trait_type, ty) in canonical_trait.1.types.iter() {
            let mapped_ty = inference.reduce_impl_ty(ImplTypeId::new(candidate_impl, *trait_type, db))?;
            inference.conform_ty(mapped_ty, *ty)?;
        }
        for (trait_const, const_id) in canonical_trait.1.constants.iter() {
            let mapped_const_id = inference.reduce_impl_constant(ImplConstantId::new(
                candidate_impl,
                *trait_const,
                db,
            ))?;
            inference.conform_const(mapped_const_id, *const_id)?;
        }

        for (trait_impl, impl_id) in canonical_trait.1.impls.iter() {
            let mapped_impl_id =
                inference.reduce_impl_impl(ImplImplId::new(candidate_impl, *trait_impl, db))?;
            inference.conform_impl(mapped_impl_id, *impl_id)?;
        }
```

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 1 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6600#-:-OB5LrSJ6BEqu2OPCmK2:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @piotmag769, and @TomerStarkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6600)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference/solver.rs` line 88 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6600#-OBQr7dIAA5pmbrsEOSK:-OBQr7dIAA5pmbrsEOSL:b-yjgqjj) ([raw file](https://github.com/starkware-libs/cairo/blob/02488d322c62f3502ff52e9af3624323f182868a/crates/cairo-lang-semantic/src/expr/inference/solver.rs#L88)):*
> ```XML
>     let mut concrete_trait_id = canonical_trait.0;
>     if !concrete_trait_id.is_fully_concrete(db) {
>         let mut solver = Solver::new(db, canonical_trait, lookup_context.clone());
> ```

comment what is being done here.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6600)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/inference/canonic.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6600#-OB4xvtk7H8L7u39glNU:-OBUX_vq1e7IISvVBLk3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b8eea9eab863c72d6669ab5f643cccad0a90049e/crates/cairo-lang-semantic/src/expr/inference/canonic.rs#L42)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

and fix doc.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/inference/solver.rs` line 230 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6600#-OB4yDBu3MzS0616jTp1:-OBUWF5b-0j84ClPn__M:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b8eea9eab863c72d6669ab5f643cccad0a90049e/crates/cairo-lang-semantic/src/expr/inference/solver.rs#L230)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

and make sure (and doc) the conform direction is correct.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/inference/solver.rs` line 88 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6600#-OBQr7dIAA5pmbrsEOSK:-OBUVjnU4t4RoGvZw9V8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/02488d322c62f3502ff52e9af3624323f182868a/crates/cairo-lang-semantic/src/expr/inference/solver.rs#L88)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

comment what is being done here.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/inference/conform.rs` line 176 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6600#-OB4xVU442Nh2jZdbedr:-OBUVC0-70mVVTYY32iD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b8eea9eab863c72d6669ab5f643cccad0a90049e/crates/cairo-lang-semantic/src/expr/inference/conform.rs#L176)):*
> ```XML
>                     parent_function: closure0.parent_function,
>                 };
>                 Ok((TypeLongId::Closure(closure0).intern(self.db), n_snapshots))
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6600)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference/solver.rs` line 88 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6600#-OBUjix7Cr4_trc0iP_r:-OBUjix7Cr4_trc0iP_s:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8f7350926518b8cb33c1398313573eb006b8d3af/crates/cairo-lang-semantic/src/expr/inference/solver.rs#L88)):*
> ```XML
>     let mut concrete_trait_id = canonical_trait.id;
>     // If the trait is not fully concrete, we might be able to use the  trait's items to find a
>     // more concrete trait.
> ```





_Suggestion:_
```XML
    // If the trait is not fully concrete, we might be able to use the trait's items to find a
    // more concrete trait.
```
___
*[`crates/cairo-lang-semantic/src/expr/inference/solver.rs` line 102 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6600#-OBUjmtu0chCrXvfCghU:-OBUjmtu0chCrXvfCghV:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8f7350926518b8cb33c1398313573eb006b8d3af/crates/cairo-lang-semantic/src/expr/inference/solver.rs#L102)):*
> ```XML
>         }
>     }
>     // Solve the trait without the trait items.
> ```





_Suggestion:_
```XML
    // Solve the trait without the trait items, so we'd be able to find conflicting impls.
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6600)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/inference/solver.rs` line 88 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6600#-OBUjix7Cr4_trc0iP_r:-OBVAYBt8Z8GdIf1wEiJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8f7350926518b8cb33c1398313573eb006b8d3af/crates/cairo-lang-semantic/src/expr/inference/solver.rs#L88)):*
> ```XML
>     let mut concrete_trait_id = canonical_trait.id;
>     // If the trait is not fully concrete, we might be able to use the  trait's items to find a
>     // more concrete trait.
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/inference/solver.rs` line 102 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6600#-OBUjmtu0chCrXvfCghU:-OBVAYQZDppY3GOKYI4w:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8f7350926518b8cb33c1398313573eb006b8d3af/crates/cairo-lang-semantic/src/expr/inference/solver.rs#L102)):*
> ```XML
>         }
>     }
>     // Solve the trait without the trait items.
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6600#-:-OBVAej43Fmcy6fh-RM-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)

**Review by mkaput — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6600)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)

**Pull request merged**
