### PR TITLE
Avoid pushing zero sized function arguments.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4267)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4267)* status: 1 of 35 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/function_call.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4267#-Ngwapir0s4CLG073jx9:-Ngwq-wS1V2WFVz0GWHS:b-5f9fhq) ([raw file](https://github.com/starkware-libs/cairo/blob/b3a73f5263040cc64524908af9033ec90ed088fd/crates/cairo-lang-sierra/src/extensions/modules/function_call.rs#L28)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

validate as discussed f2f.

and doc.
</blockquote></details>

Done.

sierra_to_casm does not use `ParamSignature`
___
*[`crates/cairo-lang-sierra/src/extensions/modules/function_call.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4267#-NgwbuYh9BhXbgIYqSQm:-Ngwq0Fx3x7_8osqQ4gl:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b3a73f5263040cc64524908af9033ec90ed088fd/crates/cairo-lang-sierra/src/extensions/modules/function_call.rs#L31)):*
> ```XML
>                             let mut param_sig = ParamSignature::new(ty.clone());
>                             if context.get_type_info(ty.clone())?.zero_sized {
>                                 param_sig = param_sig.with_allow_deferred()
> ```

Done.
___
*[`crates/cairo-lang-sierra-generator/src/pre_sierra.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4267#-NgwbGuG-IRnA__tzr6q:-Ngwn1wUClJ2WwQIlYis:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b3a73f5263040cc64524908af9033ec90ed088fd/crates/cairo-lang-sierra-generator/src/pre_sierra.rs#L71)):*
> ```XML
> 
>     
> }
> ```

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
I think I can do this in push_values without adding unnecessary renames.
based on:
https://reviewable.io/reviews/starkware-libs/cairo/4269

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4267#-:-NgwtXsD7K22183MCERV:b-r6vvw0)* status: 1 of 35 files reviewed, 3 unresolved discussions (waiting on @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 28 of 33 files at r1, 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4267)* status: 34 of 35 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/zero_size` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4267#-NgwdUsCAndin-6PbKeM:-NgwdUsCAndin-6PbKeN:b2ni2nk) ([raw file](https://github.com/starkware-libs/cairo/blob/b3a73f5263040cc64524908af9033ec90ed088fd/crates/cairo-lang-sierra-generator/src/function_generator_test_data/zero_size#L1)):*
> ```
> //! > Test that accessing a member of a struct does not cause all the struct to be stored.
> ```

fix

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4267)* status: 34 of 35 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/zero_size` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4267#-NgwdUsCAndin-6PbKeM:-NgxjW9A7z3bhFZ2C67J:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b3a73f5263040cc64524908af9033ec90ed088fd/crates/cairo-lang-sierra-generator/src/function_generator_test_data/zero_size#L1)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
decided to avoid pushing zero_sized vars in push_values.

**Pull request closed without merging**
