### PR TITLE
ConstDict: Add new and insert signatures

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2632)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2632** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2632" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2632?utm_source=stack-comment).

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2632)* status: 1 of 8 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_dict.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2632#-NRcnAHRDnhGOzeI2iJ6:-NRcnAHRDnhGOzeI2iJ7:b-my16kv) ([raw file](https://github.com/starkware-libs/cairo/blob/b6c3ab121b33402d00486917e3fc763b1efbc02e/crates/cairo-lang-sierra/src/extensions/modules/const_dict.rs#L118)):*
> ```XML
> pub struct ConstDictInsertLibfunc {}
> impl NamedLibfunc for ConstDictInsertLibfunc {
>     const STR_ID: &'static str = "const_dict_insert";
> ```

maybe do call it something of the manner of sorted_array?
it includes an insert - so calling it a const is weird - and the same with lower bound and span.



_Code quote:_
```XML
const_dict_insert
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2632)* status: 1 of 8 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_dict.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2632#-NRcns-mBAXFXCcJyNUE:-NRcns-mBAXFXCcJyNUF:b-31pihm) ([raw file](https://github.com/starkware-libs/cairo/blob/b6c3ab121b33402d00486917e3fc763b1efbc02e/crates/cairo-lang-sierra/src/extensions/modules/const_dict.rs#L155)):*
> ```XML
>                     OutputVarInfo {
>                         ty: boxed_ty(context, snapshot_ty(context, v_ty)?)?,
>                         ref_info: OutputVarReferenceInfo::Deferred(DeferredOutputKind::Generic),
> ```

why return a box - or anything for that matter - doesn't it just add?



_Code quote:_
```XML
                    OutputVarInfo {
                        ty: boxed_ty(context, snapshot_ty(context, v_ty)?)?,
                        ref_info: OutputVarReferenceInfo::Deferred(DeferredOutputKind::Generic),
                    },
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2632)* status: 1 of 8 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_dict.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2632#-NRcns-mBAXFXCcJyNUE:-NRcvgccEp5DFJEvbs5p:b-w1tl7w) ([raw file](https://github.com/starkware-libs/cairo/blob/b6c3ab121b33402d00486917e3fc763b1efbc02e/crates/cairo-lang-sierra/src/extensions/modules/const_dict.rs#L155)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why return a box - or anything for that matter - doesn't it just add?
</blockquote></details>

My resoning was that you get extra information after a successful addition, which is that you have this value stored somewhere. Returning a Box to it represents this, and the user can do something with it.

That was just an idea. I can return bool instead. WDYT?

**Pull request closed without merging**
