### PR TITLE
Add ec_point_from_x libfunc.

### PR DESCRIPTION
**Pull request by liorgold2**
commit-id:cb1bda6b

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1770#-:-NLqMMJ0979-75yBhEZH:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @Alon-Ti, @dorimedini-starkware, and @liorgold2)

___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 144 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1770#-NLqLUzR4NfLdXovrjbe:-NLqLUzR4NfLdXovrjbf:b-bu634y) ([raw file](https://github.com/starkware-libs/cairo/blob/b76f548c4bb74c3c6d85c858929e1bdd507dbf3f/crates/cairo-lang-casm/src/hints/mod.rs#L144)):*
> ```XML
>     /// Since 3 is not a quadratic residue, exactly one of `val` and `3 * val` is a quadratic
>     /// residue (unless `val` is 0). This allows proving that `val` is not a quadratic residue.
>     FieldSqrt {
> ```

is there a better name?
as this doesn't actully do a basic sqrt.



_Code quote:_
```XML
FieldSqrt
```
___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 295 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1770#-NLqJnfJBGr2AFIEedZO:-NLqJnfJBGr2AFIEedZP:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b76f548c4bb74c3c6d85c858929e1bdd507dbf3f/crates/cairo-lang-casm/src/hints/mod.rs#L295)):*
> ```XML
>                 writedoc!(
>                     f,
>                     "
> ```





_Suggestion:_
```XML
            Hint::FieldSqrt { val, sqrt } => {
                writedoc!(
                    f,
                    "

                        from starkware.crypto.signature.signature import FIELD_PRIME
                        from starkware.python.math_utils import is_quad_residue, sqrt

                        val = {}
                        if is_quad_residue(val, FIELD_PRIME):
                            memory{sqrt} = sqrt(val, FIELD_PRIME)
                        else:
                            memory{sqrt} = sqrt(val * 3, FIELD_PRIME)
                        ",
                        ResOperandFormatter(val)
                )
            }
```
___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1770#-NLqKrxJ6Ko1yz_QHHF9:-NLqKrxJ6Ko1yz_QHHFA:bp8blyr) ([raw file](https://github.com/starkware-libs/cairo/blob/b76f548c4bb74c3c6d85c858929e1bdd507dbf3f/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L85)):*
> ```XML
>             }
>             EcConcreteLibfunc::PointFromX(_) => vec![
>                 ops.const_cost(0), // TODO: fix.
> ```

add assignee



_Code quote:_
```XML
                ops.const_cost(0), // TODO: fix.
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1770)* status: all files reviewed, 4 unresolved discussions (waiting on @Alon-Ti, @dorimedini-starkware, and @liorgold2)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 220 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1770#-NLqQ9nv2-5oxlntNfy-:-NLqQ9nv2-5oxlntNfy0:b-7ov9vv) ([raw file](https://github.com/starkware-libs/cairo/blob/b76f548c4bb74c3c6d85c858929e1bdd507dbf3f/crates/cairo-lang-runner/src/casm_run/mod.rs#L220)):*
> ```XML
>             }
>             Hint::FieldSqrt { .. } => {
>                 unimplemented!();
> ```

impl:



_Suggestion:_
```XML
            Hint::FieldSqrt { val, sqrt } => {
                let val = Fq::from(get_val(val)?.to_biguint());
                insert_value_to_cellref!(vm, y, Felt::from(
                    if val.legendre().is_qr() {
                        val
                    } else {
                        val * 3
                    }.sqrt().unwrap().into_bigint().into::<BigUint>()
                ))?;
            }
```

**Review by Alon-Ti — CHANGES_REQUESTED** [review]
> Reviewed 9 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1770)* status: all files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware and @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs` line 156 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1770#-NLtSRH4A_oLu9iXKbXW:-NLtSRH4A_oLu9iXKbXX:b-oqr6qy) ([raw file](https://github.com/starkware-libs/cairo/blob/b76f548c4bb74c3c6d85c858929e1bdd507dbf3f/crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs#L156)):*
> ```XML
>         // Check that `y^2 = 3 * rhs`.
>         // Since 3 is not a quadratic residue in the field, it will follow that `rhs` is not a
>         // quadratic residue, which implies that there is no `y` such that `(x, y)` is on the curve.
> ```

Add comment about `rhs=0`.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1770#-NLtL-ARCaQrpNUg-oa_:-NLtL-ARCaQrpNUg-oaa:b-nnq22u) ([raw file](https://github.com/starkware-libs/cairo/blob/b76f548c4bb74c3c6d85c858929e1bdd507dbf3f/crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs#L161)):*
> ```XML
>         jump NotOnCurve;
>         OnCurve:
>         // Fallthrough - failure.
> ```

failure?

**Review by Alon-Ti — COMMENTED** [review]
> Reviewed 2 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1770)* status: all files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware and @liorgold2)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1770)* status: all files reviewed, 6 unresolved discussions (waiting on @liorgold2)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1770)* status: all files reviewed, 6 unresolved discussions (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1770)* status: all files reviewed, 6 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 144 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1770#-NLqLUzR4NfLdXovrjbe:-NLuQXNr4phLRAYwzGRv:baps9l) ([raw file](https://github.com/starkware-libs/cairo/blob/b76f548c4bb74c3c6d85c858929e1bdd507dbf3f/crates/cairo-lang-casm/src/hints/mod.rs#L144)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is there a better name?
as this doesn't actully do a basic sqrt.
</blockquote></details>

It does, as far as I see it. The only weird behavior is when there's no root. Is this what you meant?
___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 295 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1770#-NLqJnfJBGr2AFIEedZO:-NLuQhae-RGCbWwEfWCJ:b-l91108) ([raw file](https://github.com/starkware-libs/cairo/blob/b76f548c4bb74c3c6d85c858929e1bdd507dbf3f/crates/cairo-lang-casm/src/hints/mod.rs#L295)):*
> ```XML
>                 writedoc!(
>                     f,
>                     "
> ```

What's the difference?

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1770)* status: 7 of 11 files reviewed, 6 unresolved discussions (waiting on @Alon-Ti, @dorimedini-starkware, and @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1770#-NLtL-ARCaQrpNUg-oa_:-NLuSHUA5RQoezuZacqr:bdmt8ls) ([raw file](https://github.com/starkware-libs/cairo/blob/b76f548c4bb74c3c6d85c858929e1bdd507dbf3f/crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs#L161)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

failure?
</blockquote></details>

Nope. success. Thanks!

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1770)* status: all files reviewed, 6 unresolved discussions (waiting on @Alon-Ti, @liorgold2, and @orizi)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1770)* status: 8 of 11 files reviewed, 6 unresolved discussions (waiting on @Alon-Ti, @dorimedini-starkware, and @orizi)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 220 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1770#-NLqQ9nv2-5oxlntNfy-:-NLujmwE2qE0l2rp45rv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b76f548c4bb74c3c6d85c858929e1bdd507dbf3f/crates/cairo-lang-runner/src/casm_run/mod.rs#L220)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Try `Fq::from(BigUint::from(3))`?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1770#-NLqKrxJ6Ko1yz_QHHF9:-NLukhIUBb8QbWfsWby8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b76f548c4bb74c3c6d85c858929e1bdd507dbf3f/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L85)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

I didn't mean to leave it undone. I'll fix it.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs` line 156 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1770#-NLtSRH4A_oLu9iXKbXW:-NLunRA4379H6nn2tmYE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b76f548c4bb74c3c6d85c858929e1bdd507dbf3f/crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs#L156)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

Add comment about `rhs=0`.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1770)* status: all files reviewed, 3 unresolved discussions (waiting on @Alon-Ti and @liorgold2)

___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 144 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1770#-NLqLUzR4NfLdXovrjbe:-NLuo4Vt8qJ8v6WKuBIz:b-7wrody) ([raw file](https://github.com/starkware-libs/cairo/blob/b76f548c4bb74c3c6d85c858929e1bdd507dbf3f/crates/cairo-lang-casm/src/hints/mod.rs#L144)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

It does, as far as I see it. The only weird behavior is when there's no root. Is this what you meant?
</blockquote></details>

Yeah, but I accept
___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 295 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1770#-NLqJnfJBGr2AFIEedZO:-NLuo90r8sZg01ORAa8w:bq8s4ot) ([raw file](https://github.com/starkware-libs/cairo/blob/b76f548c4bb74c3c6d85c858929e1bdd507dbf3f/crates/cairo-lang-casm/src/hints/mod.rs#L295)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

What's the difference?
</blockquote></details>

Supported values would be constants and double derefs if required.
It prints correctly for all options.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1770)* status: all files reviewed, 3 unresolved discussions (waiting on @Alon-Ti and @liorgold2)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1770)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1770)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 295 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1770#-NLqJnfJBGr2AFIEedZO:-NLuxIq6CzOKvFwQgeD4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b76f548c4bb74c3c6d85c858929e1bdd507dbf3f/crates/cairo-lang-casm/src/hints/mod.rs#L295)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Supported values would be constants and double derefs if required.
It prints correctly for all options.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1770)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 295 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1770#-NLqJnfJBGr2AFIEedZO:-NLuxdBFCjcdB_MDoaD-:b-c5emck) ([raw file](https://github.com/starkware-libs/cairo/blob/b76f548c4bb74c3c6d85c858929e1bdd507dbf3f/crates/cairo-lang-casm/src/hints/mod.rs#L295)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

assuming you just haven't pushed yet - unblocking.

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1770)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1770)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
