### PR TITLE
Added ability to add attributes to the generated trait.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #3265
- #3275 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3275)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3275)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-plugins/src/test_data/generate_trait` line 30 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3275#-NWi-dKl0Ivg2arS97lN:-NWi-dKl0Ivg2arS97lO:baj23ry) ([raw file](https://github.com/starkware-libs/cairo/blob/ecc0c3cfb61d232f3c0e251b90de7ba9d8a0eac8/crates/cairo-lang-plugins/src/test_data/generate_trait#L30)):*
> ```
> }
> 
> #[generate_trait(trait_attribute: some(attr), trait_attribute: other(attr2))]
> ```

The named parameter is necessary here? I think it's confusing

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3275)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-plugins/src/test_data/generate_trait` line 30 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3275#-NWi-dKl0Ivg2arS97lN:-NWibjUr-mVWT13EHUbD:b4hair2) ([raw file](https://github.com/starkware-libs/cairo/blob/ecc0c3cfb61d232f3c0e251b90de7ba9d8a0eac8/crates/cairo-lang-plugins/src/test_data/generate_trait#L30)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

The named parameter is necessary here? I think it's confusing 
</blockquote></details>

1. in case we want to add an additional configuration for the generate trait itself.
2. Otherwise the inner attribute would not exactly correspond to the structure (Or do you mean having it AttributeArgVariant::Unnamed, so it would just be `#[generate_trait(some(attr), other(attr2))]`?)

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3275)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-plugins/src/test_data/generate_trait` line 30 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3275#-NWi-dKl0Ivg2arS97lN:-NWjvhrXCKfGBn0uzcA7:b-io4jx6) ([raw file](https://github.com/starkware-libs/cairo/blob/ecc0c3cfb61d232f3c0e251b90de7ba9d8a0eac8/crates/cairo-lang-plugins/src/test_data/generate_trait#L30)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

1. in case we want to add an additional configuration for the generate trait itself.
2. Otherwise the inner attribute would not exactly correspond to the structure (Or do you mean having it AttributeArgVariant::Unnamed, so it would just be `#[generate_trait(some(attr), other(attr2))]`?)
</blockquote></details>

Yes, I mean unnamed.
We can still add in the future using named args. How about this:
#[generate_trait(attrs(some(attr), other(attr)))]

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3275)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-plugins/src/test_data/generate_trait` line 30 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3275#-NWi-dKl0Ivg2arS97lN:-NWk3ksX471memrNzsR9:bsm2vt5) ([raw file](https://github.com/starkware-libs/cairo/blob/ecc0c3cfb61d232f3c0e251b90de7ba9d8a0eac8/crates/cairo-lang-plugins/src/test_data/generate_trait#L30)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Yes, I mean unnamed.
We can still add in the future using named args. How about this:
#[generate_trait(attrs(some(attr), other(attr)))]
</blockquote></details>

i'm not sure i prefer this - but done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3275#-:-NWk99o-Dkw6OUh5CJIM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
