### PR TITLE
moved const generic evaluation to semantic

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5173)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 11 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5173)* status: 11 of 15 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 673 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5173#-NroYmnxBftUdCt-Htk9:-NroYmnxBftUdCt-HtkA:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6865fa70dab5080da0965d863a27e76da766f72d/crates/cairo-lang-lowering/src/db.rs#L673)):*
> ```XML
>             }
>             ModuleItemId::Submodule(_) => {}
>             ModuleItemId::Use(_) => {}
> ```





_Suggestion:_
```XML
            ModuleItemId::Constant(_) => {}
            ModuleItemId::Submodule(_) => {}
            ModuleItemId::Use(_) => {}
```
___
*[`crates/cairo-lang-lowering/src/objects.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5173#-NroZ7Wr-Eo7O79GrbDS:-NroZ7Wr-Eo7O79GrbDT:bhwitcw) ([raw file](https://github.com/starkware-libs/cairo/blob/6865fa70dab5080da0965d863a27e76da766f72d/crates/cairo-lang-lowering/src/objects.rs#L128)):*
> ```XML
> }
> 
> /// A lowered constant.
> ```

is there any extra info here that isn't on semantic?
if not - remove.
___
*[`crates/cairo-lang-lowering/src/test_data/constant` line 167 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5173#-NroZL7JD573af0z1GMb:-NroZL7JD573af0z1GMc:blzl87u) ([raw file](https://github.com/starkware-libs/cairo/blob/6865fa70dab5080da0965d863a27e76da766f72d/crates/cairo-lang-lowering/src/test_data/constant#L167)):*
> ```
>        ^
> 
> //! > lowering_diagnostics
> ```

move semantic diags to semantic test (in corresponding `constant` file)
___
*[`crates/cairo-lang-semantic/src/expr/test_data/generics` line 553 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5173#-NroZa_C3BGDpNI-5RZx:-NroZa_C3BGDpNI-5RZy:b-onan2u) ([raw file](https://github.com/starkware-libs/cairo/blob/6865fa70dab5080da0965d863a27e76da766f72d/crates/cairo-lang-semantic/src/expr/test_data/generics#L553)):*
> ```
>                              ^
> 
> //! > ==========================================================================
> ```

another PR.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5173)* status: 1 of 15 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 673 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5173#-NroYmnxBftUdCt-Htk9:-Nrob6_d6Tx0kuD8kXRV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6865fa70dab5080da0965d863a27e76da766f72d/crates/cairo-lang-lowering/src/db.rs#L673)):*
> ```XML
>             }
>             ModuleItemId::Submodule(_) => {}
>             ModuleItemId::Use(_) => {}
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/objects.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5173#-NroZ7Wr-Eo7O79GrbDS:-Nrp8jfg2LUw-qnJbG3N:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6865fa70dab5080da0965d863a27e76da766f72d/crates/cairo-lang-lowering/src/objects.rs#L128)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is there any extra info here that isn't on semantic?
if not - remove.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/test_data/constant` line 167 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5173#-NroZL7JD573af0z1GMb:-Nrob_x1AVv453CzLNeE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6865fa70dab5080da0965d863a27e76da766f72d/crates/cairo-lang-lowering/src/test_data/constant#L167)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

move semantic diags to semantic test (in corresponding `constant` file)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/generics` line 553 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5173#-NroZa_C3BGDpNI-5RZx:-NrpAhK71kxjCO7etYTg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6865fa70dab5080da0965d863a27e76da766f72d/crates/cairo-lang-semantic/src/expr/test_data/generics#L553)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

another PR.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 15 files at r1, 7 of 12 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5173)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/constant` line 302 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5173#-NrpT8H_DUmtooYQ6E3Q:-NrpT8H_DUmtooYQ6E3R:bqlpcv4) ([raw file](https://github.com/starkware-libs/cairo/blob/ce375de97e9222ac862740a008f20e0f870a5b4b/crates/cairo-lang-semantic/src/expr/test_data/constant#L302)):*
> ```
> error: This expression is not supported as constant.
>  --> lib.cairo:10:39
> const CALCULATION_WITH_DIVISION: u8 = 120 / 0;
> ```

where have the division by 0 error disapeared?
___
*[`crates/cairo-lang-semantic/src/expr/test_data/match` line 197 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5173#-NrpTDjt0CsKNQpyLeK_:-NrpTDjt0CsKNQpyLeKa:b-onan2u) ([raw file](https://github.com/starkware-libs/cairo/blob/ce375de97e9222ac862740a008f20e0f870a5b4b/crates/cairo-lang-semantic/src/expr/test_data/match#L197)):*
> ```
>                                              ^***^
> 
> //! > ==========================================================================
> ```

another PR.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5173)* status: 12 of 17 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/constant` line 302 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5173#-NrpT8H_DUmtooYQ6E3Q:-NrpcZNa4L2pfJkMLZSD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ce375de97e9222ac862740a008f20e0f870a5b4b/crates/cairo-lang-semantic/src/expr/test_data/constant#L302)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

where have the division by 0 error disapeared?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/match` line 197 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5173#-NrpTDjt0CsKNQpyLeK_:-NrpczL90hWymfF8mjia:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ce375de97e9222ac862740a008f20e0f870a5b4b/crates/cairo-lang-semantic/src/expr/test_data/match#L197)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

another PR.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5173)* status: 12 of 17 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 991 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5173#-NrpeWN1Dro7a285SQ43:-NrpeWN1Dro7a285SQ44:b-6oeq5t) ([raw file](https://github.com/starkware-libs/cairo/blob/5cf2f98a96bd23bc749c5ec7a9d096f6f7573437/crates/cairo-lang-semantic/src/diagnostic.rs#L991)):*
> ```XML
>     UnsupportedConstant,
>     DivisionByZero,
> ```

Remove space

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5173#-:-Nrpek-z87U3Tyc6ecAd:bnfp4nl)* status: 14 of 17 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5173)* status: 14 of 17 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 991 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5173#-NrpeWN1Dro7a285SQ43:-Nrpg6nn5VFnXV4GHbUt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5cf2f98a96bd23bc749c5ec7a9d096f6f7573437/crates/cairo-lang-semantic/src/diagnostic.rs#L991)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Remove space
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 5 files at r4, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5173)* status: 16 of 17 files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5173)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5173)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
