### PR TITLE
Make contract tests visibility compatible.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
**Stack**:
- #5929
- #5925
- #5932 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5932)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 8 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5932)* status: 7 of 13 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/abi_dispatchers_tests.cairo` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5932#-O0m_csFDZdTX8FOshLH:-O0m_csFDZdTX8FOshLI:b-35qz5s) ([raw file](https://github.com/starkware-libs/cairo/blob/ef9607cefbaedbfb1ae861125f112a37601260d0/crates/cairo-lang-starknet/cairo_level_tests/abi_dispatchers_tests.cairo#L55)):*
> ```Cairo
>     let a = starknet::contract_address_const::<11>();
>     test_contract::__external::set_another_address(serialized(a));
>     assert_eq!(@test_contract::__external::get_another_address(serialized(())), @serialized(a),);
> ```

if moving to `assert_eq!` remove the `@`
___
*[`crates/cairo-lang-starknet/cairo_level_tests/storage_access.cairo` line 10 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5932#-O0mgEofCFmbCpPHaA7g:-O0mgEofCFmbCpPHaA7h:bm5w0ly) ([raw file](https://github.com/starkware-libs/cairo/blob/ef9607cefbaedbfb1ae861125f112a37601260d0/crates/cairo-lang-starknet/cairo_level_tests/storage_access.cairo#L10)):*
> ```Cairo
> impl StorageAddressPartialEq of PartialEq<StorageAddress> {
>     fn eq(lhs: @StorageAddress, rhs: @StorageAddress) -> bool {
>         let lhs: felt252 = (*lhs).try_into().unwrap();
> ```

this isn't fallible - `.into()` or revert.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5932)* status: 6 of 13 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/abi_dispatchers_tests.cairo` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5932#-O0m_csFDZdTX8FOshLH:-O0mj51uArq4i_5-hJzF:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ef9607cefbaedbfb1ae861125f112a37601260d0/crates/cairo-lang-starknet/cairo_level_tests/abi_dispatchers_tests.cairo#L55)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

if moving to `assert_eq!` remove the `@`
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/storage_access.cairo` line 10 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5932#-O0mgEofCFmbCpPHaA7g:-O0mjxjL0Je_PZ2q3IKf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ef9607cefbaedbfb1ae861125f112a37601260d0/crates/cairo-lang-starknet/cairo_level_tests/storage_access.cairo#L10)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this isn't fallible - `.into()` or revert.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 13 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5932)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo` line 117 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5932#-O0mkNyzBqfrzbMe44g4:-O0mkNyzBqfrzbMe44g5:b-6vk83x) ([raw file](https://github.com/starkware-libs/cairo/blob/862d6c1001cbde2d5d731ecca96d306c3c11f01e/crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo#L117)):*
> ```Cairo
> #[test]
> fn read_first_value() {
>     assert_eq!(test_contract::__external::get_value(serialized(())), serialized(0), "Wrong result");
> ```

remove the extra arg as well.
as well as everywhere else.



_Code quote:_
```Cairo
, "Wrong result
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5932#-:-O0mqwdo6XoYN4ACJNVQ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5932)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo` line 117 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5932#-O0mkNyzBqfrzbMe44g4:-O0nB8aEBDk27B8y9tdE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/862d6c1001cbde2d5d731ecca96d306c3c11f01e/crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo#L117)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove the extra arg as well.
as well as everywhere else.
</blockquote></details>

Done.

**Pull request merged**
