### PR TITLE
Add inline diagnostics.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1762)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1762)* status: 3 of 7 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1762#-NLoO_BiDZoQxkAfpMq0:-NLoO_BiDZoQxkAfpMq1:b-6xdukb) ([raw file](https://github.com/starkware-libs/cairo/blob/8499fd134be1775e70b1f2572e378b92349d1893/crates/cairo-lang-lowering/src/db.rs#L27)):*
> ```XML
>     ) -> Maybe<Arc<StructuredLowered>>;
> 
>     // Reports inlining diagnostics.
> ```

We should expose another query for is_inlinable(), to be used by the lowering phase. It's better API than checking for inline_diagnostics IMO (Though, the implementation could be just that).
___
*[`crates/cairo-lang-lowering/src/diagnostic.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1762#-NLoNIxNDOgYt3rZOhZg:-NLoNIxODu9FbjzI7Mgm:bghurwq) ([raw file](https://github.com/starkware-libs/cairo/blob/8499fd134be1775e70b1f2572e378b92349d1893/crates/cairo-lang-lowering/src/diagnostic.rs#L84)):*
> ```XML
>     UnsupportedMatch,
>     UnsupportedMatchArm,
>     InliningFailed { reason: String },
> ```

reason: String is not structured enough, and will make the API of the compiler harder to use.
Better use specific kinds here (e.g. InliningRefNotSupported, etc...)
___
*[`crates/cairo-lang-lowering/src/test.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1762#-NLoP6HM3z3bPZj48SPW:-NLoP6HM3z3bPZj48SPX:b-oban1g) ([raw file](https://github.com/starkware-libs/cairo/blob/8499fd134be1775e70b1f2572e378b92349d1893/crates/cairo-lang-lowering/src/test.rs#L52)):*
> ```XML
>     let mut diagnostics = DiagnosticsBuilder::default();
>     diagnostics.extend(structured_lowered.diagnostics.clone());
>     diagnostics.extend((*db.inline_diagnostics(test_function.function_id).unwrap()).clone());
> ```

I don't want to update this every time something happens. WDYT about either of these:
1. Just call module_lowering_diagnostics here.
2. Refactor module_lower_diagnostics to use a query free_function_lowering_diagnostics (or function with_body_lowering_diagnostics after yuval's refactor), and use it here?
___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1762#-NLoPgS63_BtoHnywEtR:-NLoPgS63_BtoHnywEtS:b-j4reqp) ([raw file](https://github.com/starkware-libs/cairo/blob/8499fd134be1775e70b1f2572e378b92349d1893/crates/cairo-lang-lowering/src/lower/inline.rs#L23)):*
> ```XML
>         }
> 
>         // TODO: move this logic to semantic/plugin
> ```

This is an unassigned TODO, add a name?
Also, why do we want this TODO? I think this code being here is ok.



_Code quote:_
```XML
// TODO: move this logic to semantic/plugin
```
___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1762#-NLoPwXQADqjxv7UbMHz:-NLoPwXQADqjxv7UbMI-:bp09ta8) ([raw file](https://github.com/starkware-libs/cairo/blob/8499fd134be1775e70b1f2572e378b92349d1893/crates/cairo-lang-lowering/src/lower/inline.rs#L29)):*
> ```XML
>                     diagnostics.report(
>                         path.node.stable_ptr(),
>                         LoweringDiagnosticKind::InliningFailed {
> ```

Use a specifi LoweringDiagnosticKind variant. Below as well.
___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1762#-NLoQDyr3fTSQxyOXtgP:-NLoQDyr3fTSQxyOXtgQ:b-s4mq24) ([raw file](https://github.com/starkware-libs/cairo/blob/8499fd134be1775e70b1f2572e378b92349d1893/crates/cairo-lang-lowering/src/lower/inline.rs#L52)):*
> ```XML
>             .function_with_body_direct_function_with_body_callees(function_id)?
>             .contains(&function_id)
>             // TODO(ilya): Relax requirement, if one of the functions is does not have
> ```

You also need to make this check more strict. We can have a cycle of calls, and we need to make sure this doesn't happen or we will panic.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/diagnostic.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1762#-NLoNIxNDOgYt3rZOhZg:-NLoRSFH5EkkLnVPwk1T:b-njllmn) ([raw file](https://github.com/starkware-libs/cairo/blob/8499fd134be1775e70b1f2572e378b92349d1893/crates/cairo-lang-lowering/src/diagnostic.rs#L84)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

reason: String is not structured enough, and will make the API of the compiler harder to use.
Better use specific kinds here (e.g. InliningRefNotSupported, etc...)
</blockquote></details>

but InliningRefNotSupported is going to be removed in the future.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1762#-NLoQDyr3fTSQxyOXtgP:-NLoS9QN7JL2-3UtoJyo:boekt69) ([raw file](https://github.com/starkware-libs/cairo/blob/8499fd134be1775e70b1f2572e378b92349d1893/crates/cairo-lang-lowering/src/lower/inline.rs#L52)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

You also need to make this check more strict. We can have a cycle of calls, and we need to make sure this doesn't happen or we will panic.
</blockquote></details>

I don't understand. the current check is strict enough, it guarantees no cycles.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1762#-NLoPgS63_BtoHnywEtR:-NLoRaio2KQVsss5vhnw:bai41u3) ([raw file](https://github.com/starkware-libs/cairo/blob/8499fd134be1775e70b1f2572e378b92349d1893/crates/cairo-lang-lowering/src/lower/inline.rs#L23)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This is an unassigned TODO, add a name?
Also, why do we want this TODO? I think this code being here is ok.
</blockquote></details>

You need to look at the syntax to get a good location.
e.g. here:
https://github.com/starkware-libs/cairo/blob/8499fd134be1775e70b1f2572e378b92349d1893/crates/cairo-lang-lowering/src/lower/inline.rs#L38

It would be better to put the location of the attribute list.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/db.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1762#-NLoO_BiDZoQxkAfpMq0:-NLoT49w3VVh-CtqyhMa:beujxzo) ([raw file](https://github.com/starkware-libs/cairo/blob/8499fd134be1775e70b1f2572e378b92349d1893/crates/cairo-lang-lowering/src/db.rs#L27)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

We should expose another query for is_inlinable(), to be used by the lowering phase. It's better API than checking for inline_diagnostics IMO (Though, the implementation could be just that).
</blockquote></details>

No one is going to use the is_inlinable() in the near future.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1762)* status: 0 of 10 files reviewed, 6 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1762#-NLoO_BiDZoQxkAfpMq0:-NLq1anv3HafKfrYGKQy:b-j6b07r) ([raw file](https://github.com/starkware-libs/cairo/blob/8499fd134be1775e70b1f2572e378b92349d1893/crates/cairo-lang-lowering/src/db.rs#L27)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

No one is going to use the is_inlinable() in the near future.
</blockquote></details>

will add in the next PR if needed.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1762)* status: 0 of 10 files reviewed, 6 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/test.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1762#-NLoP6HM3z3bPZj48SPW:-NLq1g2bC5sSVlY0VgWV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8499fd134be1775e70b1f2572e378b92349d1893/crates/cairo-lang-lowering/src/test.rs#L52)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I don't want to update this every time something happens. WDYT about either of these:
1. Just call module_lowering_diagnostics here.
2. Refactor module_lower_diagnostics to use a query free_function_lowering_diagnostics (or function with_body_lowering_diagnostics after yuval's refactor), and use it here?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1762#-NLoPwXQADqjxv7UbMHz:-NLq1hxF1Gt1M3Q7DPu9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8499fd134be1775e70b1f2572e378b92349d1893/crates/cairo-lang-lowering/src/lower/inline.rs#L29)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Use a specifi LoweringDiagnosticKind variant. Below as well.
</blockquote></details>

Done.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 9 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1762)* status: 8 of 10 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 53 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1762#-NLtWHUR6P6lpEi4TMzd:-NLtWHUR6P6lpEi4TMze:b-cof35b) ([raw file](https://github.com/starkware-libs/cairo/blob/9f67599e0b54f2361d0db88baa4afe450e689929/crates/cairo-lang-lowering/src/inline/mod.rs#L53)):*
> ```XML
>             _ => {
>                 diagnostics.report(
>                     attr.args_stable_ptr.untyped(),
> ```

Extract to a function.
Also, maybe this could be make simpler with some general utility functions?



_Code quote:_
```XML
    for attr in db.function_with_body_attributes(function_id)?.iter() {
        if attr.id != "inline" {
            continue;
        }

        match &attr.args[..] {
            [ast::Expr::Path(path)] if &path.node.get_text(db.upcast()) == "always" => {
                config = InlineConfiguration::Always;
            }
            [] => {
                diagnostics.report(
                    attr.id_stable_ptr.untyped(),
                    LoweringDiagnosticKind::InlineWithoutArgumentNotSupported,
                );
            }
            _ => {
                diagnostics.report(
                    attr.args_stable_ptr.untyped(),
                    LoweringDiagnosticKind::UnsupportedInlineArguments,
                );
            }
        }

        if seen_inline_attr {
            diagnostics.report(
                attr.id_stable_ptr.untyped(),
                LoweringDiagnosticKind::RedundantInlineAttribute,
            );
            // If we have multiple inline attributes revert to InlineConfiguration::None.
            config = InlineConfiguration::None;
        }

        seen_inline_attr = true;
    }
```
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 71 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1762#-NLtWnBpCxYOoa7xsqyg:-NLtWnBpCxYOoa7xsqyh:b-tbglsw) ([raw file](https://github.com/starkware-libs/cairo/blob/9f67599e0b54f2361d0db88baa4afe450e689929/crates/cairo-lang-lowering/src/inline/mod.rs#L71)):*
> ```XML
>     }
> 
>     let mut is_inlineable = true;
> ```

Extract to a function `check_inlinable()`, and use early returns in it.



_Code quote:_
```XML
    let mut is_inlineable = true;
    if db
            .function_with_body_direct_function_with_body_callees(function_id)?
            .contains(&function_id)
            // TODO(ilya): Relax requirement, if one of the functions is does not have
            //  #[inline(always)] than we can inline it.
            || db.function_with_body_scc(function_id).len() > 1
    {
        is_inlineable = false;
        if config == InlineConfiguration::Always {
            diagnostics.report(
                function_id.untyped_stable_ptr(defs_db),
                LoweringDiagnosticKind::CannotInlineFunctionThatMightCallItself,
            );
        }
    }

    if is_inlineable {
        // Note that if the function is not inlineable, callling function_with_body_lowered_flat
        // is unsafe since it could trigger a cycle.
        let lowered = db.function_with_body_lowered_flat(function_id)?;
        let root_block_id = lowered.root?;

        for (block_id, block) in lowered.blocks.iter() {
            match block.end {
                FlatBlockEnd::Return { .. } if block_id != root_block_id => {
                    is_inlineable = false;
                    if config == InlineConfiguration::Always {
                        diagnostics.report(
                            function_id.untyped_stable_ptr(defs_db),
                            LoweringDiagnosticKind::InliningFunctionWithEarlyReturnNotSupported,
                        );
                    }
                }
                _ => {}
            };
        }
    }
```
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 89 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1762#-NLtWqX77xMg0zdD8hHA:-NLtWqX77xMg0zdD8hHB:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9f67599e0b54f2361d0db88baa4afe450e689929/crates/cairo-lang-lowering/src/inline/mod.rs#L89)):*
> ```XML
> 
>     if is_inlineable {
>         // Note that if the function is not inlineable, callling function_with_body_lowered_flat
> ```





_Suggestion:_
```XML
calling 
```
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 90 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1762#-NLtX-HIAuiON1EEr4cq:-NLtX-HIAuiON1EEr4cr:b6oezyu) ([raw file](https://github.com/starkware-libs/cairo/blob/9f67599e0b54f2361d0db88baa4afe450e689929/crates/cairo-lang-lowering/src/inline/mod.rs#L90)):*
> ```XML
>     if is_inlineable {
>         // Note that if the function is not inlineable, callling function_with_body_lowered_flat
>         // is unsafe since it could trigger a cycle.
> ```

We should have a query for the flat before inlining, and call it here.
No cycles should occur.
You can add a TODO for that for now.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1762)* status: 8 of 10 files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 53 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1762#-NLtWHUR6P6lpEi4TMzd:-NLtdCSz89K3xVizsXJu:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9f67599e0b54f2361d0db88baa4afe450e689929/crates/cairo-lang-lowering/src/inline/mod.rs#L53)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Extract to a function.
Also, maybe this could be make simpler with some general utility functions?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 71 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1762#-NLtWnBpCxYOoa7xsqyg:-NLtePw0Al7FfCI2t3LW:b-nh2ob7) ([raw file](https://github.com/starkware-libs/cairo/blob/9f67599e0b54f2361d0db88baa4afe450e689929/crates/cairo-lang-lowering/src/inline/mod.rs#L71)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Extract to a function `check_inlinable()`, and use early returns in it.
</blockquote></details>

doesn't early return go against reporting all the errors?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1762)* status: 7 of 10 files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 71 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1762#-NLtWnBpCxYOoa7xsqyg:-NLtgsUS5jFWHjkc36fY:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/9f67599e0b54f2361d0db88baa4afe450e689929/crates/cairo-lang-lowering/src/inline/mod.rs#L71)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

doesn't early return go against reporting all the errors?
</blockquote></details>

done.
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 89 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1762#-NLtWqX77xMg0zdD8hHA:-NLtgrnP9dgPDIqtWGxp:brpmqc3) ([raw file](https://github.com/starkware-libs/cairo/blob/9f67599e0b54f2361d0db88baa4afe450e689929/crates/cairo-lang-lowering/src/inline/mod.rs#L89)):*
> ```XML
> 
>     if is_inlineable {
>         // Note that if the function is not inlineable, callling function_with_body_lowered_flat
> ```

removed.
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 90 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1762#-NLtX-HIAuiON1EEr4cq:-NLtgoMi9Blki1FMhBs3:b2xjjws) ([raw file](https://github.com/starkware-libs/cairo/blob/9f67599e0b54f2361d0db88baa4afe450e689929/crates/cairo-lang-lowering/src/inline/mod.rs#L90)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

We should have a query for the flat before inlining, and call it here.
No cycles should occur.
You can add a TODO for that for now.
</blockquote></details>

Done.
I'll use a separate query.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r1, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1762#-:-NLu8apb4qYq1exoODeL:bnfp4nl)* status: 9 of 10 files reviewed, all discussions resolved

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1762)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
