### PR TITLE
Extracted ap changes code from sierra main crate.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:72d7b554

---

**Stack**:
- #1281
- #1280
- #1279
- #1278 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 14 of 39 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1278)* status: 14 of 39 files reviewed, all discussions resolved (waiting on @liorgold2)

___
*[`crates/sierra/src/extensions/lib_func.rs` line 330 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1278#-NIziSMw-jhOn3sEKeJO:-NIziSMw-jhOn3sEKeJP:b-1j0rhk) ([raw file](https://github.com/starkware-libs/cairo/blob/e8594cbe5265af0de431eedc6ef2ea46ba344148/crates/sierra/src/extensions/lib_func.rs#L330)):*
> ```XML
>     /// The libfunc changes `ap` by pushing new tempvars, as described by
>     /// [OutputVarReferenceInfo::NewTempVar] in [`BranchSignature::vars`].
>     /// `new_vars_only` means that only the new variables were added on stack.
> ```

I feel that we are exposing internal implementation details here.

But I might be wrong, maybe it is true in any size-agnostic implementation.



_Code quote:_
```XML
`new_vars_only` means that only the new variables were added on stack.
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 11 of 39 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1278)* status: 25 of 39 files reviewed, 3 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`crates/sierra_ap_change/src/core_libfunc_ap_change.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1278#-NIzjA-61uYhHUE9I1BR:-NIzjA-61uYhHUE9I1BS:b-2v70hu) ([raw file](https://github.com/starkware-libs/cairo/blob/e8594cbe5265af0de431eedc6ef2ea46ba344148/crates/sierra_ap_change/src/core_libfunc_ap_change.rs#L67)):*
> ```XML
>             }
>             MemConcreteLibFunc::AlignTemps(libfunc) => {
>                 vec![ApChange::KnownByTypeSize(libfunc.ty.clone())]
> ```

I don't think this is the right name if it is used by AlignTemps.



_Code quote:_
```XML
KnownByTypeSize
```
___
*[`crates/sierra_generator/src/ap_change.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1278#-NIzjnON8YA2NJpmnUf5:-NIzjnON8YA2NJpmnUf6:b-8iy4v4) ([raw file](https://github.com/starkware-libs/cairo/blob/e8594cbe5265af0de431eedc6ef2ea46ba344148/crates/sierra_generator/src/ap_change.rs#L67)):*
> ```XML
>                 if matches!(
>                     branch_signature.ap_change,
>                     SierraApChange::Unknown | SierraApChange::NotImplemented
> ```

Is it still used? can we remove it?



_Code quote:_
```XML
SierraApChange::NotImplemented
```
___
*[`crates/sierra_to_casm/src/invocations/mod.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1278#-NIzkq1T3h4zfsPxuskO:-NIzkq1T3h4zfsPxuskP:b-npwl68) ([raw file](https://github.com/starkware-libs/cairo/blob/e8594cbe5265af0de431eedc6ef2ea46ba344148/crates/sierra_to_casm/src/invocations/mod.rs#L190)):*
> ```XML
>                     }
>                     sierra_ap_change::ApChange::KnownByTypeSize(ty) => {
>                         ApChange::Known(self.program_info.type_sizes[&ty])
> ```

how does this work for AlignTemps?
are you declaring a type with the right size for AlighTemps?



_Code quote:_
```XML
                    sierra_ap_change::ApChange::KnownByTypeSize(ty) => {
                        ApChange::Known(self.program_info.type_sizes[&ty])
                    }
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1278)* status: 25 of 39 files reviewed, 4 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`crates/sierra_ap_change/src/core_libfunc_ap_change.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1278#-NIzz6b-6koGQ6vOiQYq:-NIzz6b03Yy7ubTN8G8e:bmeg7yx) ([raw file](https://github.com/starkware-libs/cairo/blob/e8594cbe5265af0de431eedc6ef2ea46ba344148/crates/sierra_ap_change/src/core_libfunc_ap_change.rs#L37)):*
> ```XML
>             FeltConcrete::JumpNotZero(_) => vec![ApChange::Known(0), ApChange::Known(0)],
>         },
>         // TODO(orizi): Make this variable dependent.
> ```

I don't understand.
Can you phrase it better.



_Code quote:_
```XML
Make this variable dependent.
```
___
*[`crates/sierra_ap_change/src/lib.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1278#-NIzzVMG4a2CEd8BSKz-:-NIzzVMG4a2CEd8BSKz0:b-g18aye) ([raw file](https://github.com/starkware-libs/cairo/blob/e8594cbe5265af0de431eedc6ef2ea46ba344148/crates/sierra_ap_change/src/lib.rs#L13)):*
> ```XML
>     Known(usize),
>     /// The libfunc changes `ap` by a known size.
>     KnownByTypeSize(ConcreteTypeId),
> ```

fix comments.



_Code quote:_
```XML
    /// The libfunc changes `ap` by a known size.
    KnownByTypeSize(ConcreteTypeId),
    /// The libfunc changes `ap` by a known size.
    FunctionCall(FunctionId),
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1278)* status: 23 of 39 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @liorgold2)

___
*[`crates/sierra/src/extensions/lib_func.rs` line 330 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1278#-NIziSMw-jhOn3sEKeJO:-NJ-_Jny8V9-xhGweVHH:bik3zzz) ([raw file](https://github.com/starkware-libs/cairo/blob/e8594cbe5265af0de431eedc6ef2ea46ba344148/crates/sierra/src/extensions/lib_func.rs#L330)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I feel that we are exposing internal implementation details here.

But I might be wrong, maybe it is true in any size-agnostic implementation.
</blockquote></details>

we are - but it is necessary information.
___
*[`crates/sierra_ap_change/src/core_libfunc_ap_change.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1278#-NIzz6b-6koGQ6vOiQYq:-NJ-_R6WAxA9QWzQdmzx:b-xsqxzt) ([raw file](https://github.com/starkware-libs/cairo/blob/e8594cbe5265af0de431eedc6ef2ea46ba344148/crates/sierra_ap_change/src/core_libfunc_ap_change.rs#L37)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't understand.
Can you phrase it better.
</blockquote></details>

removed - this is inaccurate to begin with.
___
*[`crates/sierra_ap_change/src/core_libfunc_ap_change.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1278#-NIzjA-61uYhHUE9I1BR:-NJ-_xu2Bwrcrq8PZrA7:b-k3f6bc) ([raw file](https://github.com/starkware-libs/cairo/blob/e8594cbe5265af0de431eedc6ef2ea46ba344148/crates/sierra_ap_change/src/core_libfunc_ap_change.rs#L67)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't think this is the right name if it is used by AlignTemps.
</blockquote></details>

because? - this is still exactly the same change.
___
*[`crates/sierra_ap_change/src/lib.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1278#-NIzzVMG4a2CEd8BSKz-:-NJ-aFryBLszOX5U63dJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e8594cbe5265af0de431eedc6ef2ea46ba344148/crates/sierra_ap_change/src/lib.rs#L13)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

fix comments.
</blockquote></details>

Done.
___
*[`crates/sierra_generator/src/ap_change.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1278#-NIzjnON8YA2NJpmnUf5:-NJ-aH2RAJJnYL0y5J0H:b7bn9ga) ([raw file](https://github.com/starkware-libs/cairo/blob/e8594cbe5265af0de431eedc6ef2ea46ba344148/crates/sierra_generator/src/ap_change.rs#L67)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Is it still used? can we remove it?
</blockquote></details>

not sure - not for this pr.
___
*[`crates/sierra_to_casm/src/invocations/mod.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1278#-NIzkq1T3h4zfsPxuskO:-NJ-as6fDVxmFFzzrZHZ:bdgoig5) ([raw file](https://github.com/starkware-libs/cairo/blob/e8594cbe5265af0de431eedc6ef2ea46ba344148/crates/sierra_to_casm/src/invocations/mod.rs#L190)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

how does this work for AlignTemps?
are you declaring a type with the right size for AlighTemps?
</blockquote></details>

align temps is not branch align.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 11 of 39 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1278#-:-NJ0PeSf6gclJBvQMz8U:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1278)* status: all files reviewed, 1 unresolved discussion

___
*[`crates/sierra/src/extensions/modules/function_call.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1278#-NJ0c-fWEkWch_jKC-wZ:-NJ0c-fWEkWch_jKC-w_:bykq0e7) ([raw file](https://github.com/starkware-libs/cairo/blob/1249eef2bbfc5f2671b80ea55edf7f91ef5ddea3/crates/sierra/src/extensions/modules/function_call.rs#L36)):*
> ```XML
>                         })
>                         .collect(),
>                     ap_change,
> ```

I think this is wrong.

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1278)* status: all files reviewed, 2 unresolved discussions

___
*[`crates/sierra_generator/src/store_variables/state.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1278#-NJ0c_aKDU0k9Y8ABCrK:-NJ0c_aKDU0k9Y8ABCrL:b-pou1kg) ([raw file](https://github.com/starkware-libs/cairo/blob/1249eef2bbfc5f2671b80ea55edf7f91ef5ddea3/crates/sierra_generator/src/store_variables/state.rs#L55)):*
> ```XML
>                 self.clear_known_stack();
>             }
>             SierraApChange::Known { new_vars_only } if !new_vars_only => {
> ```

Does this work? If so, change below as well.



_Suggestion:_
```XML
SierraApChange::Known { False }
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1278)* status: all files reviewed, 1 unresolved discussion

___
*[`crates/sierra/src/extensions/modules/function_call.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1278#-NJ0c-fWEkWch_jKC-wZ:-NJ0cxWc4EkEZOTRKdvg:bwdz6iv) ([raw file](https://github.com/starkware-libs/cairo/blob/1249eef2bbfc5f2671b80ea55edf7f91ef5ddea3/crates/sierra/src/extensions/modules/function_call.rs#L36)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

I think this is wrong.
</blockquote></details>

Actually, I think this is fine.

**Pull request merged**
