### PR TITLE
Added copy-and-drop for non-zero.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:628ec47c

---

**Stack**:
- #1232
- #1231
- #1230
- #1229
- #1228
- #1227
- #1205
- #1204 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1204)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/integer.cairo` line 58 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1204#-NIRsgQ-2Rj0U783A2i3:-NIRsgQ-2Rj0U783A2i4:b-eqnsky) ([raw file](https://github.com/starkware-libs/cairo/blob/8e3158fd130e38a7e6a2577aeac0f4a89d3f9bf2/corelib/integer.cairo#L58)):*
> ```Cairo
> }
> 
> impl NonZeroUint128Copy of Copy::<NonZero::<uint128>>;
> ```

Why not derive?

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1204#-:-NIRsoeF3SyX_QuqbBcA:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1204)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @spapinistarkware)

___
*[`corelib/integer.cairo` line 58 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1204#-NIRsgQ-2Rj0U783A2i3:-NIbVGP55kjrQKoXaOSO:b-dbs19i) ([raw file](https://github.com/starkware-libs/cairo/blob/8e3158fd130e38a7e6a2577aeac0f4a89d3f9bf2/corelib/integer.cairo#L58)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Why not derive?
</blockquote></details>

This works currently for type declarations - not for specifications.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1204)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
