### PR TITLE
keep track of next use.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3538)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3538)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/lifetime.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3538#-NZ0v9wo4OzgoanPXHz4:-NZ0v9wo4OzgoanPXHz5:b-tsq1qx) ([raw file](https://github.com/starkware-libs/cairo/blob/5e4a628eef6652f60730c89b914baee0bf95c6ca/crates/cairo-lang-sierra-generator/src/lifetime.rs#L116)):*
> ```XML
>         &mut root_demands,
>         &lowered_function.parameters,
>         // TODO(ilya): What is the statement location here?
> ```

no real need for location here - as this is post monomorphization.
might be helpful for future internal debug - but don't worry about it too much.

also - which statement are you referring to exactly?



_Code quote:_
```XML
 // TODO(ilya): What is the statement location here?
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3538)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/lifetime.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3538#-NZ0v9wo4OzgoanPXHz4:-NZ0xEPe6PMJLmYCUXCJ:b-f8r9rx) ([raw file](https://github.com/starkware-libs/cairo/blob/5e4a628eef6652f60730c89b914baee0bf95c6ca/crates/cairo-lang-sierra-generator/src/lifetime.rs#L116)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no real need for location here - as this is post monomorphization.
might be helpful for future internal debug - but don't worry about it too much.

also - which statement are you referring to exactly?
</blockquote></details>

This is a location for lifetimes, not for diagnostics.


We introduce the function parameters here so it is before the first statement.
I can avoid calling analyzer.introduce here
and call `root_demands.variables_introduced(..) directly:
https://github.com/starkware-libs/cairo/blob/5e4a628eef6652f60730c89b914baee0bf95c6ca/crates/cairo-lang-sierra-generator/src/lifetime.rs#L266

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/lifetime.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3538#-NZ0v9wo4OzgoanPXHz4:-NZ0y9Hw0WU592iYDtiS:b-7hbpla) ([raw file](https://github.com/starkware-libs/cairo/blob/5e4a628eef6652f60730c89b914baee0bf95c6ca/crates/cairo-lang-sierra-generator/src/lifetime.rs#L116)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

This is a location for lifetimes, not for diagnostics.


We introduce the function parameters here so it is before the first statement.
I can avoid calling analyzer.introduce here
and call `root_demands.variables_introduced(..) directly:
https://github.com/starkware-libs/cairo/blob/5e4a628eef6652f60730c89b914baee0bf95c6ca/crates/cairo-lang-sierra-generator/src/lifetime.rs#L266

</blockquote></details>

wdyt?

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3538)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/lifetime.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3538#-NZ0v9wo4OzgoanPXHz4:-NZ10ynlE2MgpZj9jpek:b-13b3nz) ([raw file](https://github.com/starkware-libs/cairo/blob/5e4a628eef6652f60730c89b914baee0bf95c6ca/crates/cairo-lang-sierra-generator/src/lifetime.rs#L116)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

wdyt?
</blockquote></details>

that i don't understand what exactly you are trying to solve.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3538)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/lifetime.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3538#-NZ0v9wo4OzgoanPXHz4:-NZ11BkzAoWyJyfy2wxU:b-kfy1lm) ([raw file](https://github.com/starkware-libs/cairo/blob/5e4a628eef6652f60730c89b914baee0bf95c6ca/crates/cairo-lang-sierra-generator/src/lifetime.rs#L116)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

that i don't understand what exactly you are trying to solve.
</blockquote></details>

analysis.analyzer.introduce(...) requires needs statement_location for the case that is uses(== assigns) an uninitalized locals.

There is no valid statement_location when the function parameters are introduced.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3538)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/lifetime.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3538#-NZ0v9wo4OzgoanPXHz4:-NZ127Ri4HAf2mttd9Nr:b-yhp2yv) ([raw file](https://github.com/starkware-libs/cairo/blob/5e4a628eef6652f60730c89b914baee0bf95c6ca/crates/cairo-lang-sierra-generator/src/lifetime.rs#L116)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

analysis.analyzer.introduce(...) requires needs statement_location for the case that is uses(== assigns) an uninitalized locals.

There is no valid statement_location when the function parameters are introduced.
</blockquote></details>

so do that and doc why you did that.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3538)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/lifetime.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3538#-NZ0v9wo4OzgoanPXHz4:-NZ161lV76__dpyhUwNM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5e4a628eef6652f60730c89b914baee0bf95c6ca/crates/cairo-lang-sierra-generator/src/lifetime.rs#L116)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

so do that and doc why you did that.
</blockquote></details>

Done.

**Pull request merged**
