### PR TITLE
If `available_gas` is missing on tests it now has a default large value.

### PR DESCRIPTION
**Pull request by orizi**
Also enabled `static` value to the param for cases we wish to specifically allow no dynamic gas intake.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4172)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 31 of 32 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4172)* status: 31 of 32 files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-test-plugin/src/test_config.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4172#-NfenzuO1tEQ38Cxgi58:-NfenzuO1tEQ38Cxgi59:b-ud4mh3) ([raw file](https://github.com/starkware-libs/cairo/blob/2499161faf3bf77da5fd722743c0879d140919b8/crates/cairo-lang-test-plugin/src/test_config.rs#L11)):*
> ```XML
> 
> use super::{AVAILABLE_GAS_ATTR, IGNORE_ATTR, SHOULD_PANIC_ATTR, TEST_ATTR};
> use crate::STATIC_GAS_ARG;
> ```

merge the 2 lines.



_Code quote:_
```XML
use super::{AVAILABLE_GAS_ATTR, IGNORE_ATTR, SHOULD_PANIC_ATTR, TEST_ATTR};
use crate::STATIC_GAS_ARG;
```
___
*[`crates/cairo-lang-test-plugin/src/test_config.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4172#-NferDftA1d7i4EwhMbu:-NferDftA1d7i4EwhMbv:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2499161faf3bf77da5fd722743c0879d140919b8/crates/cairo-lang-test-plugin/src/test_config.rs#L121)):*
> ```XML
> }
> 
> /// Extract the available gas from the attribute.
> ```





_Suggestion:_
```XML
 Extracts the available 
```
___
*[`crates/cairo-lang-test-plugin/src/test_config.rs` line 138 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4172#-NfesdKCDsZsY-piQ6MM:-NfesdKCDsZsY-piQ6MN:b-yzsise) ([raw file](https://github.com/starkware-libs/cairo/blob/2499161faf3bf77da5fd722743c0879d140919b8/crates/cairo-lang-test-plugin/src/test_config.rs#L138)):*
> ```XML
>                 ..
>             },
>         ] => literal.numeric_value(db).unwrap_or_default().to_usize(),
> ```

why unwrap_or_default and not '?'?



_Code quote:_
```XML
unwrap_or_default()
```
___
*[`crates/cairo-lang-test-plugin/src/test_config.rs` line 149 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4172#-Nfesuf22rbRDHx71vUE:-Nfesuf22rbRDHx71vUF:b-oasulu) ([raw file](https://github.com/starkware-libs/cairo/blob/2499161faf3bf77da5fd722743c0879d140919b8/crates/cairo-lang-test-plugin/src/test_config.rs#L149)):*
> ```XML
>                 stable_ptr: attr.id_stable_ptr.untyped(),
>                 message: format!(
>                     "Attribute should have a single value argument or `{STATIC_GAS_ARG}`."
> ```

We don't support short strings here.



_Suggestion:_
```XML
single numeric literal argumen
```
___
*[`crates/cairo-lang-test-runner/src/test_config.rs` line 0 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4172#-NfetETK-RddqU6jwAKd:-NfetETK-RddqU6jwAKe:b-v0n1y7) ([raw file](https://github.com/starkware-libs/cairo/blob/2499161faf3bf77da5fd722743c0879d140919b8/crates/cairo-lang-test-runner/src/test_config.rs#L0)):*
why is this file deleted?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4172)* status: 31 of 32 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-test-plugin/src/test_config.rs` line 138 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4172#-NfesdKCDsZsY-piQ6MM:-NfexxVv8NWfejod-twm:bl2rgl2) ([raw file](https://github.com/starkware-libs/cairo/blob/2499161faf3bf77da5fd722743c0879d140919b8/crates/cairo-lang-test-plugin/src/test_config.rs#L138)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

why unwrap_or_default and not '?'?
</blockquote></details>

adding all this to the same diagnostic instead.
___
*[`crates/cairo-lang-test-runner/src/test_config.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/cairo/4172#-NfetETK-RddqU6jwAKd:-Nff42xmCeQeDf3U0HFS:b-mnhzyg) ([raw file](https://github.com/starkware-libs/cairo/blob/2499161faf3bf77da5fd722743c0879d140919b8/crates/cairo-lang-test-runner/src/test_config.rs#L)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

why is this file deleted?
</blockquote></details>

because it was duplicated - it is an old duplication of the other test_config.rs

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 32 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4172)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-test-plugin/src/test_config.rs` line 122 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4172#-NffGHdc6Ns58m_GmbjR:-NffGHdc6Ns58m_GmbjS:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0d310e3c3eae3a37b30e328404d822ac120ffdb4/crates/cairo-lang-test-plugin/src/test_config.rs#L122)):*
> ```XML
> /// Extract the available gas from the attribute.
> /// Adds a diagnostic if the attribute is malformed.
> /// Returns `None` if the attribute is `static`, or the attribute is malformed.
> ```





_Suggestion:_
```XML
e is "static", or
```
___
*[`crates/cairo-lang-test-plugin/src/test_config.rs` line 137 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4172#-NffGVrB2kYtKx5PvEV1:-NffGVrB2kYtKx5PvEV2:b-nutwqx) ([raw file](https://github.com/starkware-libs/cairo/blob/0d310e3c3eae3a37b30e328404d822ac120ffdb4/crates/cairo-lang-test-plugin/src/test_config.rs#L137)):*
> ```XML
>             stable_ptr: attr.args_stable_ptr.untyped(),
>             message: format!(
>                 "Attribute should have a single value argument or `{STATIC_GAS_ARG}`."
> ```

numeric literal



_Code quote:_
```XML
 a single value argument 
```
___
*[`crates/cairo-lang-test-plugin/src/test_config.rs` line 141 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4172#-NffGlHs4XIvcDT8eUKQ:-NffGlHs4XIvcDT8eUKR:b-tiiwyu) ([raw file](https://github.com/starkware-libs/cairo/blob/0d310e3c3eae3a37b30e328404d822ac120ffdb4/crates/cairo-lang-test-plugin/src/test_config.rs#L141)):*
> ```XML
>         })
>     };
>     match &attr.args[..] {
> ```

consider returning a bool from this match and then if true, add the diagnostic. Otherwise, in most cases the lambda is created but not used.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4172)* status: 31 of 32 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-test-plugin/src/test_config.rs` line 137 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4172#-NffGVrB2kYtKx5PvEV1:-NffPNra1iTBJkZ7oQhj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0d310e3c3eae3a37b30e328404d822ac120ffdb4/crates/cairo-lang-test-plugin/src/test_config.rs#L137)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

numeric literal
</blockquote></details>

Done.
___
*[`crates/cairo-lang-test-plugin/src/test_config.rs` line 141 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4172#-NffGlHs4XIvcDT8eUKQ:-NffP7oH0Q27ub1UVGnj:bf3jnv2) ([raw file](https://github.com/starkware-libs/cairo/blob/0d310e3c3eae3a37b30e328404d822ac120ffdb4/crates/cairo-lang-test-plugin/src/test_config.rs#L141)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

consider returning a bool from this match and then if true, add the diagnostic. Otherwise, in most cases the lambda is created but not used.
</blockquote></details>

doesn't look nicer unfortunately - rather have this.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4172)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-test-plugin/src/test_config.rs` line 141 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4172#-NffGlHs4XIvcDT8eUKQ:-Nfg3HpaBHM-ZCg3uHqz:bgv6m0) ([raw file](https://github.com/starkware-libs/cairo/blob/0d310e3c3eae3a37b30e328404d822ac120ffdb4/crates/cairo-lang-test-plugin/src/test_config.rs#L141)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doesn't look nicer unfortunately - rather have this.
</blockquote></details>

doesn't look nicer - maybe, but more efficient in the good (common) case.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4172)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-test-plugin/src/test_config.rs` line 141 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4172#-NffGlHs4XIvcDT8eUKQ:-Nfg3hNC3skcEKagPplX:bqfwikb) ([raw file](https://github.com/starkware-libs/cairo/blob/0d310e3c3eae3a37b30e328404d822ac120ffdb4/crates/cairo-lang-test-plugin/src/test_config.rs#L141)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

doesn't look nicer - maybe, but more efficient in the good (common) case.
</blockquote></details>

the closure created and not being used is very unlikely to have an actual cost.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4172#-:-Nfjlm3lBN64DN7wohoq:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-test-plugin/src/test_config.rs` line 141 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4172#-NffGlHs4XIvcDT8eUKQ:-Nfjl_3I7ChL8JNb2E_b:bsfisqn) ([raw file](https://github.com/starkware-libs/cairo/blob/0d310e3c3eae3a37b30e328404d822ac120ffdb4/crates/cairo-lang-test-plugin/src/test_config.rs#L141)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the closure created and not being used is very unlikely to have an actual cost.
</blockquote></details>

I still think it's better and don't see the big advantage of this approach, but not insisting - unblocking.

**Pull request merged**
