### PR TITLE
no_std cairo-lang-starknet

### PR DESCRIPTION
**Pull request by tdelabro**
supersed #4790

Exposes what can be exposed in `no_std`
Keep everything else untouched for `std`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4811)

### CODE REVIEW

**Comment by tdelabro** [comment]
@orizi following our messages exchange you can review this one

**Comment by tdelabro** [comment]
@orizi ready for review

**Review by tdelabro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4811)* status: 8 of 51 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/bin/starknet-sierra-extract-code/src/main.rs` line 26 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4811#-NoSiIhZ8WkO9JsxveOZ:-NoW3ZEWAldX1MBLjCi9:b-ot845b) ([raw file](https://github.com/starkware-libs/cairo/blob/9d8c4a82927776e3b4b3687c8fa6dcfa64efb319/crates/bin/starknet-sierra-extract-code/src/main.rs#L26)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

move the functions that do not use the db into the `-types` crate.
leave them as members.
make them just not nostd.
</blockquote></details>

The problem with this one is that it uses `Felt252SerdeError`and `felt252_serde::sierra_from_felt252s`, which are only defined in cairo-lang-starknet, and only make sense there.
I can't have `-type` depends on `cl-starknet`. So I would have to move those types back into `-types` and we would rapidly end up in the situation we were last time you reviewed.

`extract_sierra_program_from_contract_class` requires those two mods:
```rust
mod felt252_serde;
mod felt252_vec_compression;
```

`casm_contract_class_from_contract_class` requires:
```rust
use crate::allowed_libfuncs::AllowedLibfuncsError;
use crate::contract::starknet_keccak;
use crate::felt252_serde::{sierra_from_felt252s, Felt252SerdeError};
```

`starknet_keccak` used by the previous two is self-contained and can be moved anywhere.

` validate_compatible_sierra_version` requires `mod allowed_libfuncs`.

So, mods`allowed_libfuncs`, `felt252_serde`, and `felt252_vec_compression would be moved to `-types` along with the `starknet_keccak` function. 
We will end up with `-types` in the situation you did not like for `cl-starknet` in the previous state (a lot of code and deps behind the `feature = std` flag), and there are now two crates. To me personally, it sounds like all the disadvantages of the previous state, with the additional one of having two crates, and not that many new advantages. 

The main advantage of the current state is that you don't have to deal with std/no-std when working in `cl-starknet` where most of the logic is. But as we move more of this logic back into `-types`, it becomes less and less interesting.

In the end, it's your call. Tell me what you want me to do :)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4811)* status: 8 of 51 files reviewed, 3 unresolved discussions (waiting on @tdelabro)

___
*[`crates/bin/starknet-sierra-extract-code/src/main.rs` line 26 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4811#-NoSiIhZ8WkO9JsxveOZ:-NoWAtP2E3-JSZl4hhMs:bbh5w5h) ([raw file](https://github.com/starkware-libs/cairo/blob/9d8c4a82927776e3b4b3687c8fa6dcfa64efb319/crates/bin/starknet-sierra-extract-code/src/main.rs#L26)):*
<details><summary><i>Previously, tdelabro (Timothée Delabrouille) wrote…</i></summary><blockquote>

The problem with this one is that it uses `Felt252SerdeError`and `felt252_serde::sierra_from_felt252s`, which are only defined in cairo-lang-starknet, and only make sense there.
I can't have `-type` depends on `cl-starknet`. So I would have to move those types back into `-types` and we would rapidly end up in the situation we were last time you reviewed.

`extract_sierra_program_from_contract_class` requires those two mods:
```rust
mod felt252_serde;
mod felt252_vec_compression;
```

`casm_contract_class_from_contract_class` requires:
```rust
use crate::allowed_libfuncs::AllowedLibfuncsError;
use crate::contract::starknet_keccak;
use crate::felt252_serde::{sierra_from_felt252s, Felt252SerdeError};
```

`starknet_keccak` used by the previous two is self-contained and can be moved anywhere.

` validate_compatible_sierra_version` requires `mod allowed_libfuncs`.

So, mods`allowed_libfuncs`, `felt252_serde`, and `felt252_vec_compression would be moved to `-types` along with the `starknet_keccak` function. 
We will end up with `-types` in the situation you did not like for `cl-starknet` in the previous state (a lot of code and deps behind the `feature = std` flag), and there are now two crates. To me personally, it sounds like all the disadvantages of the previous state, with the additional one of having two crates, and not that many new advantages. 

The main advantage of the current state is that you don't have to deal with std/no-std when working in `cl-starknet` where most of the logic is. But as we move more of this logic back into `-types`, it becomes less and less interesting.

In the end, it's your call. Tell me what you want me to do :)
</blockquote></details>

the only logical thing for me we can do is separate this crate into 2 by the following process:
1. salsa db dependent (which means the plugin + SierraContractClass generation)
2. non - salsa db dependent - CasmContractClass and generation

within the second structure - some parts may logically also be no-std.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 41 files at r3, 15 of 41 files at r7, 2 of 3 files at r8, 2 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4811)* status: 20 of 63 files reviewed, 5 unresolved discussions (waiting on @tdelabro)

___
*[`Cargo.toml` line 52 at r9](https://reviewable.io/reviews/starkware-libs/cairo/4811#-NpQNfViB9E87rnx0m1A:-NpQNfViB9E87rnx0m1B:bi8hv2o) ([raw file](https://github.com/starkware-libs/cairo/blob/6996d18ecd2b925195badbd2c3ca2a6e4e288969/Cargo.toml#L52)):*
> ```TOML
>     "crates/cairo-lang-starknet",
>     "crates/cairo-lang-starknet-types",
>     "crates/cairo-lang-syntax",
> ```

rename - `types` to `classes` - add the definitions
of CasmContractClass and ContractClass in  `classes`.
The ABI and the ABI builder would probably be split between the 2.



_Suggestion:_
```TOML
    "crates/cairo-lang-starknet",
    "crates/cairo-lang-starknet-class",
    "crates/cairo-lang-syntax",
```
___
*[`crates/bin/starknet-sierra-extract-code/src/main.rs` line 26 at r9](https://reviewable.io/reviews/starkware-libs/cairo/4811#-NpQNUjn1HmaN7F3o1qv:-NpQNUjn1HmaN7F3o1qw:b-ac1zaf) ([raw file](https://github.com/starkware-libs/cairo/blob/6996d18ecd2b925195badbd2c3ca2a6e4e288969/crates/bin/starknet-sierra-extract-code/src/main.rs#L26)):*
> ```XML
>     )
>     .with_context(|| "deserialization Failed.")?;
>     let sierra_program = extract_sierra_program_from_contract_class(&contract_class)
> ```

as discussed - make a method again.



_Code quote:_
```XML
extract_sierra_program_from_contract_class
```

**Comment by tdelabro** [comment]
@orizi ready for review

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 29 files at r1, 3 of 3 files at r6, 3 of 41 files at r7, 25 of 46 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4811)* status: 31 of 63 files reviewed, 6 unresolved discussions (waiting on @tdelabro)

___
*[`crates/cairo-lang-starknet-classes/src/abi.rs` line 15 at r11](https://reviewable.io/reviews/starkware-libs/cairo/4811#-NpZGFkpALRcsjGgcKRk:-NpZGFkpALRcsjGgcKRl:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0fca64d4457316e14cdd05160760fad5a3d0daf1/crates/cairo-lang-starknet-classes/src/abi.rs#L15)):*
> ```XML
> type TraitFnCount = UnorderedHashMap<String, usize>;
> #[cfg(not(feature = "std"))]
> type TraitFnCount = UnorderedHashMap<String, usize, hashbrown::hash_map::DefaultHashBuilder>;
> ```





_Suggestion:_
```XML
#[cfg(feature = "std")]
type ContractItems = OrderedHashSet<Item>;
#[cfg(not(feature = "std"))]
type ContractItems = OrderedHashSet<Item, hashbrown::hash_map::DefaultHashBuilder>;
```
___
*[`crates/cairo-lang-starknet-classes/src/abi.rs` line 39 at r11](https://reviewable.io/reviews/starkware-libs/cairo/4811#-NpZGfmE1HsKo5SxW3AC:-NpZGfmE1HsKo5SxW3AD:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0fca64d4457316e14cdd05160760fad5a3d0daf1/crates/cairo-lang-starknet-classes/src/abi.rs#L39)):*
> ```XML
>         let trait_fn_count: TraitFnCount = self
>             .items
>             .iter()
> ```





_Suggestion:_
```XML
    ) {
        let trait_fn_count: UnorderedHashMap<_, _> = self
            .items
            .iter()
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 46 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4811)* status: 34 of 63 files reviewed, 9 unresolved discussions (waiting on @tdelabro)

___
*[`crates/cairo-lang-starknet-classes/src/felt252_serde.rs` line 37 at r11](https://reviewable.io/reviews/starkware-libs/cairo/4811#-NpZH8bKEN_PJQl0ReSN:-NpZH8bKEN_PJQl0ReSO:bk3eu43) ([raw file](https://github.com/starkware-libs/cairo/blob/2789b60a15223b465841d88888d23c9c3e27946d/crates/cairo-lang-starknet-classes/src/felt252_serde.rs#L37)):*
> ```XML
> #[cfg(test)]
> #[path = "felt252_serde_test.rs"]
> mod test;
> ```

tests should remain here.



_Code quote:_
```XML
use crate::felt252_vec_compression::{compress, decompress};

#[cfg(test)]
#[path = "felt252_serde_test.rs"]
mod test;
```
___
*[`crates/cairo-lang-starknet-classes/src/felt252_serde.rs` line 91 at r11](https://reviewable.io/reviews/starkware-libs/cairo/4811#-NpZHDIS8Fy_n6XVNJlZ:-NpZHDIS8Fy_n6XVNJl_:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0fca64d4457316e14cdd05160760fad5a3d0daf1/crates/cairo-lang-starknet-classes/src/felt252_serde.rs#L91)):*
> ```XML
> 
> /// Trait for serializing and deserializing into a felt252 vector.
> pub trait Felt252Serde: Sized {
> ```





_Suggestion:_
```XML
/// Trait for serializing and deserializing into a felt252 vector.
trait Felt252Serde: Sized {
```
___
*[`crates/cairo-lang-starknet-classes/src/felt252_serde.rs` line 179 at r11](https://reviewable.io/reviews/starkware-libs/cairo/4811#-NpZHBNjEBVUUzpyXqWm:-NpZHBNjEBVUUzpyXqWn:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0fca64d4457316e14cdd05160760fad5a3d0daf1/crates/cairo-lang-starknet-classes/src/felt252_serde.rs#L179)):*
> ```XML
> /// A set of all the supported long generic ids.
> pub static SERDE_SUPPORTED_LONG_IDS: Lazy<OrderedHashSet<&'static str>> = Lazy::new(|| {
>     OrderedHashSet::from_iter([
> ```





_Suggestion:_
```XML
const SHORT_STRING_BOUND: usize = 31;
/// A set of all the supported long generic ids.
static SERDE_SUPPORTED_LONG_IDS: Lazy<OrderedHashSet<&'static str>> = Lazy::new(|| {
    OrderedHashSet::from_iter([
```

**Review by tdelabro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4811)* status: 34 of 63 files reviewed, 9 unresolved discussions (waiting on @orizi)

___
*[`crates/bin/starknet-sierra-compile/src/main.rs` line 67 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4811#-NoSn3KY4AlrkvFmE3Tv:-NpZIDe2CYoLM_IVeqMv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3b6986b39d284e7e6c1e3b38803228c503c7ae39/crates/bin/starknet-sierra-compile/src/main.rs#L67)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

move back to type.
</blockquote></details>

Done.
___
*[`crates/bin/starknet-sierra-extract-code/src/main.rs` line 26 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4811#-NoSiIhZ8WkO9JsxveOZ:-NpZIEpgEa1n1O4cRjFd:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9d8c4a82927776e3b4b3687c8fa6dcfa64efb319/crates/bin/starknet-sierra-extract-code/src/main.rs#L26)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the only logical thing for me we can do is separate this crate into 2 by the following process:
1. salsa db dependent (which means the plugin + SierraContractClass generation)
2. non - salsa db dependent - CasmContractClass and generation

within the second structure - some parts may logically also be no-std.
</blockquote></details>

Done.
___
*[`crates/bin/starknet-sierra-extract-code/src/main.rs` line 26 at r9](https://reviewable.io/reviews/starkware-libs/cairo/4811#-NpQNUjn1HmaN7F3o1qv:-NpZIFSUCKcJvwKKJLUu:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6996d18ecd2b925195badbd2c3ca2a6e4e288969/crates/bin/starknet-sierra-extract-code/src/main.rs#L26)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

as discussed - make a method again.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet-classes/src/felt252_serde.rs` line 37 at r11](https://reviewable.io/reviews/starkware-libs/cairo/4811#-NpZH8bKEN_PJQl0ReSN:-NpZHdUHCRlls5walZmj:b-12irq9) ([raw file](https://github.com/starkware-libs/cairo/blob/2789b60a15223b465841d88888d23c9c3e27946d/crates/cairo-lang-starknet-classes/src/felt252_serde.rs#L37)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

tests should remain here.
</blockquote></details>

As explained in a comment here: https://github.com/starkware-libs/cairo/pull/4811/files#diff-d8c90976b28677bf6e7ddc0fbaa8e9acfaafa05d08f4d6bb32e5625191e6a93e
Test cannot stay there
___
*[`crates/cairo-lang-starknet-classes/src/felt252_serde.rs` line 91 at r11](https://reviewable.io/reviews/starkware-libs/cairo/4811#-NpZHDIS8Fy_n6XVNJlZ:-NpZHlJq3C4hBEnimKlS:bdvo249) ([raw file](https://github.com/starkware-libs/cairo/blob/0fca64d4457316e14cdd05160760fad5a3d0daf1/crates/cairo-lang-starknet-classes/src/felt252_serde.rs#L91)):*
> ```XML
> 
> /// Trait for serializing and deserializing into a felt252 vector.
> pub trait Felt252Serde: Sized {
> ```

This trait is now used outside of the crate. It's used in cairo-lang-starknet. Therefore it has to be public in cairo-lang-starknet-classes
___
*[`crates/cairo-lang-starknet-classes/src/felt252_serde.rs` line 179 at r11](https://reviewable.io/reviews/starkware-libs/cairo/4811#-NpZHBNjEBVUUzpyXqWm:-NpZI-N25-4d_h-uX3nS:b-iwwsin) ([raw file](https://github.com/starkware-libs/cairo/blob/0fca64d4457316e14cdd05160760fad5a3d0daf1/crates/cairo-lang-starknet-classes/src/felt252_serde.rs#L179)):*
> ```XML
> /// A set of all the supported long generic ids.
> pub static SERDE_SUPPORTED_LONG_IDS: Lazy<OrderedHashSet<&'static str>> = Lazy::new(|| {
>     OrderedHashSet::from_iter([
> ```

Because the tests have to be cairo-lang-starknet, and need access to this static variable, it has to be public

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4811)* status: 35 of 63 files reviewed, 9 unresolved discussions (waiting on @tdelabro)

___
*[`crates/cairo-lang-starknet-classes/src/felt252_serde.rs` line 91 at r11](https://reviewable.io/reviews/starkware-libs/cairo/4811#-NpZHDIS8Fy_n6XVNJlZ:-NpZWKCX2f-ZxEXpHP_z:b-lh7ivq) ([raw file](https://github.com/starkware-libs/cairo/blob/0fca64d4457316e14cdd05160760fad5a3d0daf1/crates/cairo-lang-starknet-classes/src/felt252_serde.rs#L91)):*
<details><summary><i>Previously, tdelabro (Timothée Delabrouille) wrote…</i></summary><blockquote>

This trait is now used outside of the crate. It's used in cairo-lang-starknet. Therefore it has to be public in cairo-lang-starknet-classes
</blockquote></details>

well - it shouldn't - remove.
___
*[`crates/cairo-lang-starknet-classes/src/felt252_serde.rs` line 179 at r11](https://reviewable.io/reviews/starkware-libs/cairo/4811#-NpZHBNjEBVUUzpyXqWm:-NpZWcUK6T8n4fytAWWc:b-m9c3j9) ([raw file](https://github.com/starkware-libs/cairo/blob/0fca64d4457316e14cdd05160760fad5a3d0daf1/crates/cairo-lang-starknet-classes/src/felt252_serde.rs#L179)):*
<details><summary><i>Previously, tdelabro (Timothée Delabrouille) wrote…</i></summary><blockquote>

Because the tests have to be cairo-lang-starknet, and need access to this static variable, it has to be public
</blockquote></details>

move the tests back in any case.
as you only need the path.
same for all other tests files.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4811)* status: 35 of 63 files reviewed, 8 unresolved discussions (waiting on @tdelabro)

___
*[`crates/cairo-lang-starknet-classes/src/felt252_serde.rs` line 37 at r11](https://reviewable.io/reviews/starkware-libs/cairo/4811#-NpZH8bKEN_PJQl0ReSN:-NpZX-jC3R7se_3W7lmq:b-cul4vi) ([raw file](https://github.com/starkware-libs/cairo/blob/2789b60a15223b465841d88888d23c9c3e27946d/crates/cairo-lang-starknet-classes/src/felt252_serde.rs#L37)):*
<details><summary><i>Previously, tdelabro (Timothée Delabrouille) wrote…</i></summary><blockquote>

As explained in a comment here: https://github.com/starkware-libs/cairo/pull/4811/files#diff-d8c90976b28677bf6e7ddc0fbaa8e9acfaafa05d08f4d6bb32e5625191e6a93e
Test cannot stay there
</blockquote></details>

they must.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4811)* status: 35 of 63 files reviewed, 7 unresolved discussions (waiting on @tdelabro)

___
*[`crates/cairo-lang-starknet-classes/src/abi.rs` line 68 at r11](https://reviewable.io/reviews/starkware-libs/cairo/4811#-NpZY0LGAzxp8fRyYHsc:-NpZY0LGAzxp8fRyYHsd:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/0fca64d4457316e14cdd05160760fad5a3d0daf1/crates/cairo-lang-starknet-classes/src/abi.rs#L68)):*
> ```XML
>     }
> 
>     pub fn insert_item(&mut self, item: Item) -> bool {
> ```

doc

**Pull request closed without merging**
