### PR TITLE
Fully resolve items

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2595)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2595** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2595" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2595?utm_source=stack-comment).

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 11 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2595)* status: 11 of 16 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 247 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2595#-NRSG6NdC5ieAcbEOx0D:-NRSG6NdC5ieAcbEOx0E:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/8f7354da8584535c3bc82f2c215916ce0bef6463/crates/cairo-lang-semantic/src/items/imp.rs#L247)):*
> ```XML
> ) -> Maybe<ImplDeclarationData> {
>     let name = impl_def_id.name(db.upcast());
>     eprintln!("S {name}");
> ```

remove



_Code quote:_
```XML
    eprintln!("S {name}");
```

**Review by orizi — COMMENTED** [review]
> Reviewed 4 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2595)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2595)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 247 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2595#-NRSG6NdC5ieAcbEOx0D:-NRSUBNQ2nNdiTegESvN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8f7354da8584535c3bc82f2c215916ce0bef6463/crates/cairo-lang-semantic/src/items/imp.rs#L247)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2595)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2595#-:-NRSWQMZ6q4M2MTY_LjE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
