### PR TITLE
Panic type

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3232)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3232** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3232" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/3232?utm_source=stack-comment).

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 27 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3232)* status: 27 of 28 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/casm_contract_class.rs` line 144 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3232#-NWCFyUqAnBSK9VLqXaw:-NWCFyUqAnBSK9VLqXax:b-g1yu5k) ([raw file](https://github.com/starkware-libs/cairo/blob/189913c5c9bcce3cc7827f27c067dc50e624957f/crates/cairo-lang-starknet/src/casm_contract_class.rs#L144)):*
> ```XML
>     }
> 
>     fn is_valid_entry_point_return_type(&self, ty: &ConcreteTypeId) -> bool {
> ```

this means all old code won't be submittable.
we probably need to support both.



_Code quote:_
```XML
is_valid_entry_point_return_type
```
___
*[`crates/cairo-lang-starknet/src/casm_contract_class.rs` line 157 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3232#-NWCFlO51OWJ5WC-FsU_:-NWCFlO51OWJ5WC-FsUa:b-5ae9kc) ([raw file](https://github.com/starkware-libs/cairo/blob/189913c5c9bcce3cc7827f27c067dc50e624957f/crates/cairo-lang-starknet/src/casm_contract_class.rs#L157)):*
> ```XML
>     }
> 
>     fn extract_result_ty(&self, ty: &ConcreteTypeId) -> Option<(&ConcreteTypeId, &ConcreteTypeId)> {
> ```

doc all



_Code quote:_
```XML
extract_result_ty
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3232)* status: 8 of 63 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/casm_contract_class.rs` line 144 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3232#-NWCFyUqAnBSK9VLqXaw:-NXcuuNHBziZAQDyBJus:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/189913c5c9bcce3cc7827f27c067dc50e624957f/crates/cairo-lang-starknet/src/casm_contract_class.rs#L144)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this means all old code won't be submittable.
we probably need to support both.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/casm_contract_class.rs` line 157 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3232#-NWCFlO51OWJ5WC-FsU_:-NXcuuw91fRBUI_EePKW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/189913c5c9bcce3cc7827f27c067dc50e624957f/crates/cairo-lang-starknet/src/casm_contract_class.rs#L157)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc all
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 17 of 53 files at r2, 38 of 38 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3232#-:-NXd2GyIBgruIlZQZ8Bl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
