### PR TITLE
Avoid storing zero sized objects on the stack.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4290)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4290#-:-NhR6MJz4thYX2JvDu_a:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/state.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4290#-NhR66jP9Js07Wd2__J7:-NhR66jP9Js07Wd2__J8:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/18ede0ac9521cf5936d5202a2a44a993273a4f03/crates/cairo-lang-sierra-generator/src/store_variables/state.rs#L50)):*
> ```XML
>     ZeroSizedVar,
>     /// The variable was consumed and can no longer be used.
>     /// This state is used because there is no efficent way of removing variables
> ```





_Suggestion:_
```XML
pub enum VarState {
    /// The variable is a temporary variable with the given type.
    TempVar { ty: sierra::ids::ConcreteTypeId },
    /// The variable is deferred with the given DeferredVariableInfo.
    Deferred { info: DeferredVariableInfo },
    /// The variable is a local variable.
    LocalVar,
    /// The variable is of size zero.
    ZeroSizedVar,
    /// The variable was consumed and can no longer be used.
    /// This state is used because there is no efficent way of removing variables
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4290)* status: 0 of 62 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/state.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4290#-NhR66jP9Js07Wd2__J7:-NhRSnz-6fUXt3C5Nb6U:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/18ede0ac9521cf5936d5202a2a44a993273a4f03/crates/cairo-lang-sierra-generator/src/store_variables/state.rs#L50)):*
> ```XML
>     ZeroSizedVar,
>     /// The variable was consumed and can no longer be used.
>     /// This state is used because there is no efficent way of removing variables
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 33 of 62 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4290)* status: 33 of 62 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/lib_func.rs` line 387 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4290#-NhS9PbnABUlyinhvGGU:-NhS9PbnABUlyinhvGGV:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/3aeaf736773470f6559dea87088e3e299a4e8a10/crates/cairo-lang-sierra/src/extensions/lib_func.rs#L387)):*
> ```XML
>     SimpleDerefs,
>     // The output is a of size 0.
>     ZeroSized,
> ```





_Suggestion:_
```XML
    SameAsParam { param_idx: usize },
    /// The output value is a part of one of the parameters.
    /// For example, it may be the first element of a struct.
    ///
    /// Information, such as whether the parameter was a temporary or local variable, will be
    /// copied to the output variable.
    PartialParam { param_idx: usize },
    /// The output was allocated as a temporary variable and it is at the top of the stack
    /// (contiguously).
    NewTempVar {
    Deferred(DeferredOutputKind),
    /// All the output cells are of the form `[ap/fp + const]`. For example, `([ap + 1], [fp])`.
    SimpleDerefs,
    /// The output is a of size 0.
    ZeroSized,
```

**Review by orizi — COMMENTED** [review]
> Reviewed 27 of 62 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4290)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4290)* status: 60 of 62 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/lib_func.rs` line 387 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4290#-NhS9PbnABUlyinhvGGU:-NhVgzPM42vOStsnBi7G:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3aeaf736773470f6559dea87088e3e299a4e8a10/crates/cairo-lang-sierra/src/extensions/lib_func.rs#L387)):*
> ```XML
>     SimpleDerefs,
>     // The output is a of size 0.
>     ZeroSized,
> ```

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4290)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
