### PR TITLE
Added a `to_buffer` helper method.

### PR DESCRIPTION
**Pull request by orizi**
Fixing inline.rs to support deref ResOperand.

commit-id:e007c84c

---

**Stack**:
- #1407
- #1406
- #1405 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1405)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/sierra_to_casm/src/invocations/pedersen.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1405#-NJiqkhH8gpYPx_O0G1U:-NJiqkhH8gpYPx_O0G1V:bua06g8) ([raw file](https://github.com/starkware-libs/cairo/blob/6a721aa6f8a39177d6b6daf2db1676cc6f91a3c3/crates/sierra_to_casm/src/invocations/pedersen.rs#L34)):*
> ```XML
>             ReferenceValue { expression: expr_y, .. },
>         ] => (
>             expr_pedersen.try_unpack_single()?.to_buffer(2)?,
> ```

don't you need 3 here? `x,y,hash(x,y)`?



_Code quote:_
```XML
2
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1405)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/sierra_to_casm/src/invocations/pedersen.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1405#-NJiqkhH8gpYPx_O0G1U:-NJjFM0n6UyWoIfITcvX:b402az9) ([raw file](https://github.com/starkware-libs/cairo/blob/6a721aa6f8a39177d6b6daf2db1676cc6f91a3c3/crates/sierra_to_casm/src/invocations/pedersen.rs#L34)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

don't you need 3 here? `x,y,hash(x,y)`?
</blockquote></details>

no -  but because of a confusing reason -
the max_access is +2 not +3 - the fact that the new location would be +2**15 exactly is ok.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1405#-:-NJjFgTuD_14-XSSQDHd:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1405)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
