### PR TITLE
Add preorder syntax node traversal API

### PR DESCRIPTION
**Pull request by mkaput**
**Stack**:
- #2780
- #2803
- #2814 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2814)

### CODE REVIEW

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2814)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @mkaput)

___
*[`crates/cairo-lang-syntax/src/node/mod.rs` line 215 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2814#-NTCAmqhCiZmzIzPV5cA:-NTCAmqhCiZmzIzPV5cB:bmb94py) ([raw file](https://github.com/starkware-libs/cairo/blob/2192f05c2cfe090bb99db631848cb90f50cb2e01/crates/cairo-lang-syntax/src/node/mod.rs#L215)):*
> ```XML
>     }
> 
>     /// Traverse the subtree rooted at the current node (including the current node) in preorder.
> ```

Can you move all this traversal loic to a new module?

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2814#-:-NTCBS51898CeYhP5Gq7:bnfp4nl)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @mkaput)

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2814)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2814)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mkaput)

___
*[`crates/cairo-lang-syntax/src/node/mod.rs` line 215 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2814#-NTCAmqhCiZmzIzPV5cA:-NTCynfMAZBs7zSBRRYM:bu622av) ([raw file](https://github.com/starkware-libs/cairo/blob/2192f05c2cfe090bb99db631848cb90f50cb2e01/crates/cairo-lang-syntax/src/node/mod.rs#L215)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Can you move all this traversal loic to a new module?
</blockquote></details>

Done, moved to `iter` module

**Pull request merged**
