### PR TITLE
Move locations to an interned ObjectOrigin sturct.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3417)

### CODE REVIEW

**Review by orizi — DISMISSED** [review]
:lgtm:

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3417#-:-NXty5C46SuUux8-aJva:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3417#-NXty6fX3Nrh-J4T23aw:-NXty6fX3Nrh-J4T23ax:b-8i7os2) (no related file):*
wanna see what @spapinistarkware thinks as well.

___

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3417)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/diagnostic.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3417#-NXxuw2o02KQTM2rzTp9:-NXxuw2o02KQTM2rzTpA:bhe6pv7) ([raw file](https://github.com/starkware-libs/cairo/blob/a1e83fe593e36c9b2320e42fc54dd697b01158af/crates/cairo-lang-lowering/src/diagnostic.rs#L10)):*
> ```XML
> use cairo_lang_syntax::node::ids::SyntaxStablePtrId;
> 
> use crate::SourceLocation;
> ```

wdyt about Origin?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/diagnostic.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3417#-NXxuw2o02KQTM2rzTp9:-NXy7kPJ6lGhv-kK-AYf:b-dfrp2t) ([raw file](https://github.com/starkware-libs/cairo/blob/a1e83fe593e36c9b2320e42fc54dd697b01158af/crates/cairo-lang-lowering/src/diagnostic.rs#L10)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

wdyt about Origin?
</blockquote></details>

I think it is a bit ambigous.
wdyt about 'ObjectOrigin'?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3417)* status: 1 of 14 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3417#-NXty6fX3Nrh-J4T23aw:-NXy7hhnE3AVkGIJmJbK:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

wanna see what @spapinistarkware thinks as well.
</blockquote></details>

Done.

___

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3417)* status: 1 of 14 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 1 of 14 files at r1, 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3417)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3417#-:-NXynO7k6SHx4c-EcHjL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
