### PR TITLE
Handling u256 inverse for n == 1.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4478)

### CODE REVIEW

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4478)* status: 1 of 7 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned256.rs` line 492 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4478#-NkB-HhB6qJwmY8-qPHu:-NkB-HhB6qJwmY8-qPHv:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/5dd835feb64f82fa1b7269e65f90f27117122986/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned256.rs#L492)):*
> ```XML
>         assert t0 = *(range_check++);
>         assert t1 = *(range_check++);
>         // Validating `g > 1`.
> ```

.



_Suggestion:_
```XML
        // Validate that `g > 1` or `g = n = 1`.
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned256.rs` line 497 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4478#-NkB-Lhs7tKjLtLil1p3:-NkB-Lhs7tKjLtLil1p4:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5dd835feb64f82fa1b7269e65f90f27117122986/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned256.rs#L497)):*
> ```XML
>         assert g0_minus_1 = g0 - one;
>         jump GIsValid if g0_minus_1 != 0;
>         // Handling the case where `g = 1``, which is only valid if `n = 1``.
> ```





_Suggestion:_
```XML
        // Handle the case where `g = 1`, which is only valid if `n = 1`.
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned256.rs` line 502 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4478#-NkB0EcG0L21P1B519AO:-NkB0EcHCu_j063kt0TY:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5dd835feb64f82fa1b7269e65f90f27117122986/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned256.rs#L502)):*
> ```XML
>         GIsValid:
> 
>         // Validating `g * s = b` and `g * t = n`.
> ```





_Suggestion:_
```XML
        // Validate `g * s = b` and `g * t = n`.
```

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4478)* status: 1 of 7 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned256.rs` line 492 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4478#-NkB1Iel9rmDdHKCjggI:-NkB1Iel9rmDdHKCjggJ:bnz6rk4) ([raw file](https://github.com/starkware-libs/cairo/blob/5dd835feb64f82fa1b7269e65f90f27117122986/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned256.rs#L492)):*
> ```XML
>         assert t0 = *(range_check++);
>         assert t1 = *(range_check++);
>         // Validating `g > 1`.
> ```

Document the behavior above the libfunc's signature (`unsigned256.rs` + the cairo file)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4478)* status: 3 of 7 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 244 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4478#-NkB27tTCmYiI1tzwk0b:-NkB27tUAFkbCp0yiS9d:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5dd835feb64f82fa1b7269e65f90f27117122986/crates/cairo-lang-casm/src/hints/mod.rs#L244)):*
> ```XML
>     /// A special case is when `n == 1`, we consider it as no inverse.
>     /// In this case: Returns `g == 1`, `s == b` and `t == 1`.
>     /// All no-inverse requirements are satisfied, not including g > 1.
> ```





_Suggestion:_
```XML
    /// The case `n == 1` is considered "no-inverse" (special case).
    /// In this case: Returns `g == 1`, `s == b` and `t == 1`.
    /// All no-inverse requirements are satisfied, except for `g > 1`.
```

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4478)* status: 4 of 7 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`corelib/src/test/math_test.cairo` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4478#-NkB3PBE43ocpLQfZO8n:-NkB3PBE43ocpLQfZO8o:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5dd835feb64f82fa1b7269e65f90f27117122986/corelib/src/test/math_test.cairo#L94)):*
> ```Cairo
>     assert(math::u256_inv_mod(8, nz(24)).is_none(), 'inv_mov(8, 24) != None');
>     assert(math::u256_inv_mod(1, nz(1)).is_none(), 'inv_mov(1, 1) != 0');
>     assert(math::u256_inv_mod(7, nz(1)).is_none(), 'inv_mov(7, 1) != 0');
> ```





_Suggestion:_
```Cairo
    assert(math::u256_inv_mod(1, nz(1)).is_none(), 'inv_mov(1, 1) != None');
    assert(math::u256_inv_mod(7, nz(1)).is_none(), 'inv_mov(7, 1) != None');
```

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4478)* status: 4 of 8 files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/int/unsigned256.rs` line 120 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4478#-NkB4kgc3V23VUgCsfF9:-NkB4kgc3V23VUgCsfFA:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/cc70cb94de4c22b8a19fea72049ebbd9579c103f/crates/cairo-lang-sierra/src/extensions/modules/int/unsigned256.rs#L120)):*
> ```XML
> /// Inverse Modulo N.
> /// Libfunc for calculating the inverse of a number modulo N, if `N == 1` does not consider the
> /// value as invertible.
> ```





_Suggestion:_
```XML
/// Inverse Modulo N.
///
/// Libfunc for calculating the inverse of a number modulo N.
/// If `N == 1`, the value is not considered invertible.
```

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4478)* status: 5 of 8 files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4478)* status: 4 of 8 files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware and @liorgold2)

___
*[`corelib/src/test/math_test.cairo` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4478#-NkB3PBE43ocpLQfZO8n:-NkB5TC79IYN63xffzm4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5dd835feb64f82fa1b7269e65f90f27117122986/corelib/src/test/math_test.cairo#L94)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Add `inv_mod(0, 1)` and `inv_mod(0, 7)`
</blockquote></details>

Done.

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4478)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

**Review by liorgold2 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4478)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4478)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware and @liorgold2)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/int/unsigned256.rs` line 120 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4478#-NkB4kgc3V23VUgCsfF9:-NkB600x0HtscrRbDmU1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cc70cb94de4c22b8a19fea72049ebbd9579c103f/crates/cairo-lang-sierra/src/extensions/modules/int/unsigned256.rs#L120)):*
> ```XML
> /// Inverse Modulo N.
> /// Libfunc for calculating the inverse of a number modulo N, if `N == 1` does not consider the
> /// value as invertible.
> ```

Done.

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4478#-:-NkB65j-AV6LWYAExSSM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
