### PR TITLE
Add find_contract_structs.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1136)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1136)* status: 4 of 8 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/starknet/src/contract.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1136#-NI-DD0HE_3X39I-Gf1w:-NI-DD0HE_3X39I-Gf1x:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ca078b6499ded321217b67b77267d5563981d5ba/crates/starknet/src/contract.rs#L12)):*
> ```XML
> mod test;
> 
> // Represents a contract defintion
> ```





_Suggestion:_
```XML
/// Represents a contract defintion.
```
___
*[`crates/starknet/src/contract.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1136#-NI-DBs65tFbwq3yX_yz:-NI-DBs7EtFDC7HH8Z8c:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/ca078b6499ded321217b67b77267d5563981d5ba/crates/starknet/src/contract.rs#L20)):*
> ```XML
> }
> 
> pub fn find_contract_structs(db: &dyn SemanticGroup) -> Vec<ContractDefinition> {
> ```

doc



_Code quote:_
```XML
find_contract_structs
```
___
*[`crates/starknet/src/contract.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1136#-NI-DjEP90hyXdqlBX1R:-NI-DjEP90hyXdqlBX1S:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ca078b6499ded321217b67b77267d5563981d5ba/crates/starknet/src/contract.rs#L39)):*
> ```XML
>                                         impls: resolve_impls(db, struct_id, &attr.args),
>                                     });
>                                 }
> ```





_Suggestion:_
```XML
            for (_name, item) in module_items.items.iter() {
                if let ModuleItemId::Struct(struct_id) = item {
                    if let Some(attrs) = db.struct_attributes(*struct_id) {
                        if let [attr] = attrs.as_slice() {
                            if attr.id == "contract" {
                                contracts.push(ContractDefinition {
                                    id: *struct_id,
                                    impls: resolve_impls(db, struct_id, &attr.args),
                                });
                            }
                        };
                    }
                }
            }
```
___
*[`crates/starknet/src/contract.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1136#-NI-DFj881RFyd54ctH5:-NI-DFj881RFyd54ctH6:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ca078b6499ded321217b67b77267d5563981d5ba/crates/starknet/src/contract.rs#L50)):*
> ```XML
> }
> 
> // Resolve impl_exprs into ConcreteImplId's.
> ```





_Suggestion:_
```XML
/// Resolve impl_exprs into ConcreteImplId's.
```
___
*[`crates/starknet/src/contract.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1136#-NI-ECNE5UPHNqcT1BSX:-NI-ECNE5UPHNqcT1BSY:bv3w6f9) ([raw file](https://github.com/starkware-libs/cairo/blob/ca078b6499ded321217b67b77267d5563981d5ba/crates/starknet/src/contract.rs#L71)):*
> ```XML
>                 Some(item) => panic!("Expected an `impl`, Got {:?}.", item),
>                 None => {
>                     panic!("Failed to resolve {}.", path.as_syntax_node().text(syntax_db).unwrap())
> ```

why not result based?



_Code quote:_
```XML
                    panic!("Failed to resolve {}.", path.as_syntax_node().text(syntax_db).unwrap())
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1136)* status: 4 of 8 files reviewed, 5 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/starknet/src/contract.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1136#-NI-DD0HE_3X39I-Gf1w:-NI1LQTxDmlvh9C3lPMq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ca078b6499ded321217b67b77267d5563981d5ba/crates/starknet/src/contract.rs#L12)):*
> ```XML
> mod test;
> 
> // Represents a contract defintion
> ```

Done.
___
*[`crates/starknet/src/contract.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1136#-NI-DBs65tFbwq3yX_yz:-NI1LzGV6fgg6_FnVrmj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ca078b6499ded321217b67b77267d5563981d5ba/crates/starknet/src/contract.rs#L20)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.



_Code quote:_
```XML
find_contract_structs
```
___
*[`crates/starknet/src/contract.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1136#-NI-DjEP90hyXdqlBX1R:-NI1M6_I4Bb6f54kFHXH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ca078b6499ded321217b67b77267d5563981d5ba/crates/starknet/src/contract.rs#L39)):*
> ```XML
>                                         impls: resolve_impls(db, struct_id, &attr.args),
>                                     });
>                                 }
> ```

Done.
___
*[`crates/starknet/src/contract.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1136#-NI-DFj881RFyd54ctH5:-NI1M6NLDQaIlkATLqpI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ca078b6499ded321217b67b77267d5563981d5ba/crates/starknet/src/contract.rs#L50)):*
> ```XML
> }
> 
> // Resolve impl_exprs into ConcreteImplId's.
> ```

Done.
___
*[`crates/starknet/src/contract.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1136#-NI-ECNE5UPHNqcT1BSX:-NI1RHSm8LAD-boFtqD0:b-hnbw1x) ([raw file](https://github.com/starkware-libs/cairo/blob/ca078b6499ded321217b67b77267d5563981d5ba/crates/starknet/src/contract.rs#L71)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why not result based?
</blockquote></details>

removed from this PR.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1136)* status: 4 of 8 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/starknet/src/contract.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1136#-NI1TeZc-3yomG8xmfdO:-NI1TeZc-3yomG8xmfdP:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c8295c1da9565030f863f3a1a7fe632788ae66a7/crates/starknet/src/contract.rs#L10)):*
> ```XML
> 
> /// Represents a struct and an attribute that marks it as a contract.
> pub struct UnresolvedContractDefinition {
> ```





_Suggestion:_
```XML
pub struct UnresolvedContractDefinition {
    /// The struct that defines the contracts storage.
    pub id: StructId,
    /// The contract attribute
    pub attr: Attribute,
}
```
___
*[`crates/starknet/src/contract.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1136#-NI1Trnm67ieQpsXgd15:-NI1Trnm67ieQpsXgd16:b-r49vxo) ([raw file](https://github.com/starkware-libs/cairo/blob/c8295c1da9565030f863f3a1a7fe632788ae66a7/crates/starknet/src/contract.rs#L28)):*
> ```XML
>             };
> 
>             for (_name, item) in module_items.items.iter() {
> ```

if exists.



_Suggestion:_
```XML
 for item in module_items.items.values() {
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 8 files at r1, 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1136)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1136)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/starknet/src/contract.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1136#-NI1TeZc-3yomG8xmfdO:-NI1VkQE-jzuU7CvSijZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/22bd34339890fd5a3ef90bbec993eb2d29eb118e/crates/starknet/src/contract.rs#L10)):*
> ```XML
> 
> /// Represents a struct and an attribute that marks it as a contract.
> pub struct UnresolvedContractDefinition {
> ```

Done.
___
*[`crates/starknet/src/contract.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1136#-NI1Trnm67ieQpsXgd15:-NI1Vy890Hq3h-UG0Zm6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/22bd34339890fd5a3ef90bbec993eb2d29eb118e/crates/starknet/src/contract.rs#L28)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

if exists.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1136#-:-NI1WJdC8Nmw6WkoMBnj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
