### PR TITLE
Fixed new clippy errors

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4687)

### CODE REVIEW

**Review by orizi — DISMISSED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4687)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-utils/src/bigint.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4687#-NmlmgNY6mb45xhyv4kK:-NmlmgNY6mb45xhyv4kL:b5vnopd) ([raw file](https://github.com/starkware-libs/cairo/blob/8d05f06929d418ad836d4a208a4e0865e0ae07e2/crates/cairo-lang-utils/src/bigint.rs#L65)):*
> ```XML
>     pub enum Sign {
>         Minus,
>         None,
> ```

this might break existing jsons.



_Code quote:_
```XML
        None,
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4687)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-utils/src/bigint.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4687#-NmlmgNY6mb45xhyv4kK:-NmyrZ1D0ZKbKie5vI-S:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8d05f06929d418ad836d4a208a4e0865e0ae07e2/crates/cairo-lang-utils/src/bigint.rs#L65)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this might break existing jsons.
</blockquote></details>

Done.

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 7 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4687#-:-NmyzRFSDzfyLUibTGMs:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by liorgold2 — APPROVED** [review]
> Dismissed @orizi from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4687)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
