### PR TITLE
allow for implicit impls for impl impl items

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5915)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5915)* status: 2 of 7 files reviewed, 6 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 707 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5915#-O0c9eC79fEOmoXLn_tD:-O0c9eC79fEOmoXLn_tE:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/e1bbe1b44597d7e116aab196e426ebbe26bb6522/crates/cairo-lang-semantic/src/db.rs#L707)):*
> ```XML
>     fn impl_item_by_name(&self, impl_def_id: ImplDefId, name: SmolStr)
>     -> Maybe<Option<ImplItemId>>;
>     /// Returns something
> ```

?
___
*[`crates/cairo-lang-semantic/src/db.rs` line 760 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5915#-O0c9f1P93DNwKmIpQ_O:-O0c9f1P93DNwKmIpQ_P:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/e1bbe1b44597d7e116aab196e426ebbe26bb6522/crates/cairo-lang-semantic/src/db.rs#L760)):*
> ```XML
>         trait_impl_id: TraitImplId,
>     ) -> Maybe<ImplImplDefId>;
>     /// Returns something
> ```

?
___
*[`crates/cairo-lang-semantic/src/db.rs` line 969 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5915#-O0cA64uB09_KZEZrDx8:-O0cA64uB09_KZEZrDx9:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/e1bbe1b44597d7e116aab196e426ebbe26bb6522/crates/cairo-lang-semantic/src/db.rs#L969)):*
> ```XML
>     #[salsa::invoke(items::imp::implicit_impl_impl_impl)]
>     #[salsa::cycle(items::imp::implicit_impl_impl_impl_cycle)]
>     fn implicit_impl_impl_impl(
> ```

doc
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 906 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5915#-O0cB7tU9tdOZ66gHJQ8:-O0cB7tU9tdOZ66gHJQ9:bcb6nwo) ([raw file](https://github.com/starkware-libs/cairo/blob/e1bbe1b44597d7e116aab196e426ebbe26bb6522/crates/cairo-lang-semantic/src/items/imp.rs#L906)):*
> ```XML
>     impl_def_id: ImplDefId,
>     trait_impl_id: TraitImplId,
> ) -> Maybe<Option<TraitImplId>> {
> ```

is the input and the output the same value?



_Code quote:_
```XML
    trait_impl_id: TraitImplId,
) -> Maybe<Option<TraitImplId>> {
```
___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 461 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5915#-O0cBmWa7xLJOK50RpJo:-O0cBmWa7xLJOK50RpJp:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e1bbe1b44597d7e116aab196e426ebbe26bb6522/crates/cairo-lang-semantic/src/items/tests/trait#L461)):*
> ```
> }
> impl MyImpl of MyTrait;
> ///TODO(TomerStarkware): improve diagnostics for missing impls.
> ```





_Suggestion:_
```
// TODO(TomerStarkware): improve diagnostics for missing impls.
```
___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 516 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5915#-O0cCG_I0grenp_80z6K:-O0cCG_I0grenp_80z6L:b-2jxdp7) ([raw file](https://github.com/starkware-libs/cairo/blob/e1bbe1b44597d7e116aab196e426ebbe26bb6522/crates/cairo-lang-semantic/src/items/tests/trait#L516)):*
> ```
>      ^****^
> 
> error: Trait has no implementation in context: test::OtherTrait.
> ```

this should point to the problematic member as well IMO.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5915)* status: 2 of 7 files reviewed, 6 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 707 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5915#-O0c9eC79fEOmoXLn_tD:-O0cQLr_CshD2sKDSl8K:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e1bbe1b44597d7e116aab196e426ebbe26bb6522/crates/cairo-lang-semantic/src/db.rs#L707)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/db.rs` line 760 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5915#-O0c9f1P93DNwKmIpQ_O:-O0cQMvn4RtUckdNnSg6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e1bbe1b44597d7e116aab196e426ebbe26bb6522/crates/cairo-lang-semantic/src/db.rs#L760)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/db.rs` line 969 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5915#-O0cA64uB09_KZEZrDx8:-O0cQOBI31rwr7ufI0wd:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e1bbe1b44597d7e116aab196e426ebbe26bb6522/crates/cairo-lang-semantic/src/db.rs#L969)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 906 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5915#-O0cB7tU9tdOZ66gHJQ8:-O0cMkfM-D-9gjn_bgD4:bid07fm) ([raw file](https://github.com/starkware-libs/cairo/blob/e1bbe1b44597d7e116aab196e426ebbe26bb6522/crates/cairo-lang-semantic/src/items/imp.rs#L906)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is the input and the output the same value?
</blockquote></details>

if the outer impl does not explicitly contain the trait impl 
can be refactored to `is implicit impl impl`
___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 461 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5915#-O0cBmWa7xLJOK50RpJo:-O0cNOIR0ca8J_aRX1pO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e1bbe1b44597d7e116aab196e426ebbe26bb6522/crates/cairo-lang-semantic/src/items/tests/trait#L461)):*
> ```
> }
> impl MyImpl of MyTrait;
> ///TODO(TomerStarkware): improve diagnostics for missing impls.
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 516 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5915#-O0cCG_I0grenp_80z6K:-O0cNSjc-T1lAHAN4pKE:bz1wmnp) ([raw file](https://github.com/starkware-libs/cairo/blob/e1bbe1b44597d7e116aab196e426ebbe26bb6522/crates/cairo-lang-semantic/src/items/tests/trait#L516)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this should point to the problematic member as well IMO.
</blockquote></details>

I agree, but infrence.finalize does not return the errors
I can check explicitly if the var created is in refuted, or ambiguous

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5915)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 760 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5915#-O0cR5VnBJykWHj9iHNC:-O0cR5VnBJykWHj9iHND:b-9degxm) ([raw file](https://github.com/starkware-libs/cairo/blob/90eddc301892420cc7218968389cae8ba4b79f39/crates/cairo-lang-semantic/src/db.rs#L760)):*
> ```XML
>         trait_impl_id: TraitImplId,
>     ) -> Maybe<ImplImplDefId>;
>     /// Returns whether `trait_impl_id` is an implicit impl in `impl_def_id`.
> ```

function does not return a bool.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 906 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5915#-O0cB7tU9tdOZ66gHJQ8:-O0cRBS36C45iW-3SseN:b-6d25im) ([raw file](https://github.com/starkware-libs/cairo/blob/e1bbe1b44597d7e116aab196e426ebbe26bb6522/crates/cairo-lang-semantic/src/items/imp.rs#L906)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

if the outer impl does not explicitly contain the trait impl 
can be refactored to `is implicit impl impl`
</blockquote></details>

please do.
___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 516 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5915#-O0cCG_I0grenp_80z6K:-O0cRHCy-vGkbI0UwhXd:bh8sc5v) ([raw file](https://github.com/starkware-libs/cairo/blob/e1bbe1b44597d7e116aab196e426ebbe26bb6522/crates/cairo-lang-semantic/src/items/tests/trait#L516)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

I agree, but infrence.finalize does not return the errors
I can check explicitly if the var created is in refuted, or ambiguous
</blockquote></details>

but you do know the point you try to solve - have a diagnostic wrapping the inference error for impl item.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5915)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 760 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5915#-O0cR5VnBJykWHj9iHNC:-O0ccaGA3qyf7EKQxa2n:b-n9tkhd) ([raw file](https://github.com/starkware-libs/cairo/blob/90eddc301892420cc7218968389cae8ba4b79f39/crates/cairo-lang-semantic/src/db.rs#L760)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

function does not return a bool.
</blockquote></details>

changed
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 906 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5915#-O0cB7tU9tdOZ66gHJQ8:-O0cc_Gt8keHnw1IexUR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e1bbe1b44597d7e116aab196e426ebbe26bb6522/crates/cairo-lang-semantic/src/items/imp.rs#L906)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

please do.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 516 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5915#-O0cCG_I0grenp_80z6K:-O0cgTm45okmvCMYoK-m:bz6jvqt) ([raw file](https://github.com/starkware-libs/cairo/blob/e1bbe1b44597d7e116aab196e426ebbe26bb6522/crates/cairo-lang-semantic/src/items/tests/trait#L516)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

but you do know the point you try to solve - have a diagnostic wrapping the inference error for impl item.
</blockquote></details>

if I use inference.solve is there a way to tell which impl was unsolved?

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5915)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 516 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5915#-O0cCG_I0grenp_80z6K:-O0cxCr7ATi04QHj_-Gz:bc0wjg) ([raw file](https://github.com/starkware-libs/cairo/blob/e1bbe1b44597d7e116aab196e426ebbe26bb6522/crates/cairo-lang-semantic/src/items/tests/trait#L516)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

if I use inference.solve is there a way to tell which impl was unsolved?
</blockquote></details>

Don't you solve per item now?

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5915)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 516 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5915#-O0cCG_I0grenp_80z6K:-O0cxo270fxKAwraG_Vh:b-hwbmyw) ([raw file](https://github.com/starkware-libs/cairo/blob/e1bbe1b44597d7e116aab196e426ebbe26bb6522/crates/cairo-lang-semantic/src/items/tests/trait#L516)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Don't you solve per item now?
</blockquote></details>

wdym? I use inference.finalize in priv\_implicit\_impl\_impl\_semantic\_data

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5915)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 516 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5915#-O0cCG_I0grenp_80z6K:-O0cyGO4BGgIT7Rc_Ve2:b-zauvy5) ([raw file](https://github.com/starkware-libs/cairo/blob/e1bbe1b44597d7e116aab196e426ebbe26bb6522/crates/cairo-lang-semantic/src/items/tests/trait#L516)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

wdym? I use inference.finalize in priv\_implicit\_impl\_impl\_semantic\_data
</blockquote></details>

But you can do it per item.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5915)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 516 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5915#-O0cCG_I0grenp_80z6K:-O0czjGl10hBqvDY0ZKk:b-h3fwf6) ([raw file](https://github.com/starkware-libs/cairo/blob/e1bbe1b44597d7e116aab196e426ebbe26bb6522/crates/cairo-lang-semantic/src/items/tests/trait#L516)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

But you can do it per item.
</blockquote></details>

I meant if when I use inference.solve there more error which could be unrelated to the current implicit impl I am trying to solve

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5915)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 516 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5915#-O0cCG_I0grenp_80z6K:-O0d1WCS4npfEvtg7Nb4:b-mltlyd) ([raw file](https://github.com/starkware-libs/cairo/blob/e1bbe1b44597d7e116aab196e426ebbe26bb6522/crates/cairo-lang-semantic/src/items/tests/trait#L516)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

I meant if when I use inference.solve there more error which could be unrelated to the current implicit impl I am trying to solve
</blockquote></details>

But you can still just solve it on the spot, item by item, so you'd know which what failed for which.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5915#-:-O0hNm_u4DVrzOSmGWwV:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
