### PR TITLE
Provide `compile_prepared_db` for StarkNet

### PR DESCRIPTION
**Pull request by mkaput**
commit-id:78c5d43f

---

**Stack**:
- #2018
- #2012
- #1999
- #1993 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1993)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @mkaput)

___
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1993#-NNBdHaeC2G4oQktj8bz:-NNBdHaeC2G4oQktj8c-:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/3cac8e7334b89c34ab0c7e976290fd12f2ce161e/crates/cairo-lang-starknet/src/contract_class.rs#L84)):*
> ```XML
> }
> 
> fn compile_only_contract_in_prepared_db(
> ```

doc



_Code quote:_
```XML
fn compile_only_contract_in_prepared_db(
```
___
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1993#-NNBdK5g-jjpFLhyYLsC:-NNBdK5g-jjpFLhyYLsD:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/3cac8e7334b89c34ab0c7e976290fd12f2ce161e/crates/cairo-lang-starknet/src/contract_class.rs#L127)):*
> ```XML
> }
> 
> fn compile_contract_with_prepared_and_checked_db(
> ```

doc



_Code quote:_
```XML
fn compile_contract_with_prepared_and_checked_db(
```

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1993)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1993#-NNBdHaeC2G4oQktj8bz:-NNC-JDL4mlmmXJmGjGs:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/69a4878b54cfe59a8c06bafc08ec64e044d859da/crates/cairo-lang-starknet/src/contract_class.rs#L84)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1993#-NNBdK5g-jjpFLhyYLsC:-NNC-Iw33UrQJKjbbiLd:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/69a4878b54cfe59a8c06bafc08ec64e044d859da/crates/cairo-lang-starknet/src/contract_class.rs#L127)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1993)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1993#-:-NNC2ocd-Z1Or6TJJ4JA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1993)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
