### PR TITLE
Add starknet Serde impls to extra_uses

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2516)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2516)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2516#-NQdv-onBS4uEoyt4xa2:-NQdv-onBS4uEoyt4xa3:b-mzkv7x) (no related file):*
we shouldn't do that imo - and if we do - the extra uses has got to be a set.

___

**Comment by ilyalesokhin-starkware** [comment]
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

ok - i'm convinced we should do it - but this still has to become a set (otherwise we get random compilation errors if users provide these by themselves)
</blockquote></details>

the other uses are use super::{...}

the using a set wouldn't help you.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2516)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2516#-NQdv-onBS4uEoyt4xa2:-NQe0uxl9SFs3QfCrP0E:bo8nd9f) (no related file):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

the other uses are use super::{...}

the using a set wouldn't help you.
</blockquote></details>

adding these by default would break users with very bad diags - but you can make a dictionary mapped by name - and then just use the `values()` of it.

___

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2516)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2516#-NQdv-onBS4uEoyt4xa2:-NQeEBOs271E_Bq7FIha:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

adding these by default would break users with very bad diags - but you can make a dictionary mapped by name - and then just use the `values()` of it.
</blockquote></details>

Done.

___

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2516#-:-NQeGftw22yFu1b0OBjJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
