### PR TITLE
Add the consts segment into the casm contract bytecode.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
**Stack**:
- #4714
- #4712 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4712)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4712)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-casm/src/assembler.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4712#-Nn8tRx22Sh6JsN-Xvwp:-Nn8tRx38sWuQeVXK153:b-agqzyp) ([raw file](https://github.com/starkware-libs/cairo/blob/08d7af0b7a2215b2be95c120d2b342ce4a939cf8/crates/cairo-lang-casm/src/assembler.rs#L79)):*
> ```XML
> pub struct AssembledCairoProgram {
>     /// The bytecode of the program.
>     pub bytecode: Vec<BigUintAsHex>,
> ```

Do not rely on BigUintAs hex here, it is just for json encode.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4712)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-casm/src/assembler.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4712#-Nn8tRx22Sh6JsN-Xvwp:-Nn9B3S5Bo3930MDheuR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/08d7af0b7a2215b2be95c120d2b342ce4a939cf8/crates/cairo-lang-casm/src/assembler.rs#L79)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Do not rely on BigUintAs hex here, it is just for json encode.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4712#-:-Nn9IcvJ3x1nRWoNyd7B:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Comment by gilbens-starkware** [comment]
✓ Commit merged in pull request [#4714](https://github.com/starkware-libs/cairo/pull/4714)

**Pull request closed without merging**
