### PR TITLE
Enabling gas calculation not based on lp.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #4447
- #4655 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4655)

### CODE REVIEW

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4655)* status: 7 of 10 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4655#-Nm_XM-jBRRDBSZZf90p:-Nm_XM-jBRRDBSZZf90q:ba854hx) ([raw file](https://github.com/starkware-libs/cairo/blob/ac231ee38cec354f68be780931fddf872b510296/crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs#L127)):*
> ```XML
>         .ok_or(InvocationError::UnknownVariableData)?;
> 
>     check_zero_precost_values(variable_values, builder.idx)?;
> ```

Revert.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4655)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`tests/e2e_test_data/metadata_computation` line 736 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4655#-Nm_ZxIp-gLw22QB-EBh:-Nm_ZxIp-gLw22QB-EBi:b-wauyrp) ([raw file](https://github.com/starkware-libs/cairo/blob/52690d7dd3dee1ddd16722620317a4e885e6bf5b/tests/e2e_test_data/metadata_computation#L736)):*
> ```
> //! > cairo
> fn foo() -> u128 {
>     core::gas::withdraw_gas().unwrap();
> ```

Replace `unwrap` with `match`.

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 2 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4655)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4655)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4655#-Nm_XM-jBRRDBSZZf90p:-Nm_aSAV2lksny7fkeDF:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ac231ee38cec354f68be780931fddf872b510296/crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs#L127)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Revert.
</blockquote></details>

Done.
___
*[`tests/e2e_test_data/metadata_computation` line 736 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4655#-Nm_ZxIp-gLw22QB-EBh:-Nm_bBHE8QoeSGOSdeu8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/52690d7dd3dee1ddd16722620317a4e885e6bf5b/tests/e2e_test_data/metadata_computation#L736)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Replace `unwrap` with `match`.
</blockquote></details>

Done.

**Review by liorgold2 — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4655)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4655#-:-Nm_m0mGBsjoqgv1TEKe:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
