### PR TITLE
Core Lib Documentation: `Zeroable` module

### PR DESCRIPTION
**Pull request by TAdev0**

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6722)* status: all files reviewed, 1 unresolved discussion (waiting on @TAdev0)

___
*[`corelib/src/zeroable.cairo` line 40 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6722#-OCcSMIR08gdOLs4w9oP:-OCcSMIR08gdOLs4w9oQ:b-fywwxk) ([raw file](https://github.com/starkware-libs/cairo/blob/da3615360a8a8f0e6e2621452e278b986dac81a1/corelib/src/zeroable.cairo#L40)):*
> ```Cairo
>     /// assert!(5.is_non_zero());
>     /// assert!(!0.is_non_zero());
>     /// ```
> ```

should still not remove documentation from traits.



_Code quote:_
```Cairo
/// A trait for types that have a concept of zero and can be compared to zero.
///
/// This trait is useful for numeric types or any type that has an additive identity element.
pub(crate) trait Zeroable<T> {
    /// Returns the additive identity element of Self, 0.
    ///
    /// This method should return a value that, when added to any other value of type T,
    /// does not change that value.
    ///
    /// # Examples
    ///
    /// ```
    /// assert_eq!(Zeroable::<i32>::zero(), 0);
    /// ```
    #[must_use]
    fn zero() -> T;

    /// Returns whether self is equal to 0, the additive identity element.
    ///
    /// # Examples
    ///
    /// ```
    /// assert!(0.is_zero());
    /// assert!(!5.is_zero());
    /// ```
    #[must_use]
    fn is_zero(self: T) -> bool;

    /// Returns whether self is not equal to 0, the additive identity element.
    ///
    /// This method is the logical inverse of `is_zero()`.
    ///
    /// # Examples
    ///
    /// ```
    /// assert!(5.is_non_zero());
    /// assert!(!0.is_non_zero());
    /// ```
```

**Comment by TAdev0** [comment]
@orizi  this documentation has been moved to the `Zero` module for the `pub trait Zero<T>` trait. Leaving this one would induce a duplicate in comment, while `Zeroable` trait is actually an internal trait.

This was discussed with @enitrat

**Review by enitrat — COMMENTED** [review]
Let's agree on keeping already existing documentation of private  / crate-restricted items with `///`, if that's fine for you @orizi - besides `impl` that should inherit the base trait doc

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6722#-:-OCq9Fkk3xROoiOgSd7A:b-zal024)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi and @TAdev0)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6722#-:-OCqy2AFBN7kItOTY0rW:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TAdev0)

**Comment by TAdev0** [comment]
@orizi  there was some formatting error, should be ok now.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6722#-:-OCsFGGG6va27ZQ5dpVS:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TAdev0)

**Pull request merged**
