### PR TITLE
run fmt on vscode ext

### PR DESCRIPTION
**Pull request by gaetbout**
Ran the formatter on vscode extension.
It should fix the CI

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3061)

### CODE REVIEW

**Comment by gaetbout** [comment]
@spapinistarkware 🙏

**Review by spapinistarkware — COMMENTED** [review]
The CI is broken? I only see a newline added. Which formatter?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3061#-:-NUuCw2CBaa2n5GHw57p:b-62lkrp)* status: 0 of 1 files reviewed, all discussions resolved

**Comment by gaetbout** [comment]
"Some checks were not successful
1 failing and 14 successful checks"
The one failing was 
"VSCode Cairo Extension CI / format and lint (pull_request)"

Just ran 
`npm run fmt`
on the vscode extension to fix it.

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3061)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gaetbout)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3061#-:-NUuF-IqDNqTlgSVnLXz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gaetbout)

**Pull request merged**
