### PR TITLE
Update support links

### PR DESCRIPTION
**Pull request by Arcticae**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6119)

### CODE REVIEW

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6119#-:-O3HcjiWCm8y-wvFMXNy:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, and @orizi)

**Review by Draggu — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6119#-:-O3INb_64D56praLNK5f:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae and @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6119#-:-O3R2FCI2tFHHcmqF8QY:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae)

___
*[`vscode-cairo/SUPPORT.md` line 13 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6119#-O3R2KA0BfmBulOlcXAJ:-O3R2KA0BfmBulOlcXAK:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/fe2e7c7cbb7807851c9446c965b6a2acd0373c9e/vscode-cairo/SUPPORT.md#L13)):*
> ```Markdown
> 
> If you have searched the GitHub issues for your problem, and still would like to contact the team,
> we are providing support on [Telegram](https://t.me/cairo_ls_support) or [Discord](https://discord.gg/QypNMzkHbc).
> ```





_Suggestion:_
```Markdown
## How to file issues

This project uses GitHub Issues to track bugs and feature requests.
Please search the [existing issues](https://github.com/starkware-libs/cairo/issues) before filing
new issues to avoid duplicates.
For new issues, file your bug or feature request as a new Issue.
Make sure to mention that your issue concerns language server specifically to get your request
processed quicker.

## Contact

If you have searched the GitHub issues for your problem, and still would like to contact the team,
we are providing support on [Telegram](https://t.me/cairo_ls_support) or
[Discord](https://discord.gg/QypNMzkHbc).
```

**Review by Arcticae — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6119)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`vscode-cairo/README.md` line 96 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6119#-O3HakR3CVJdsCGIaywN:-O3WVATr9_WMQlfe5SQa:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4b5ae1dba50a59334c72a72168d3fb6cf72586b5/vscode-cairo/README.md#L96)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

please keep these links sorted
</blockquote></details>

Done.
___
*[`vscode-cairo/SUPPORT.md` line 13 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6119#-O3R2KA0BfmBulOlcXAJ:-O3WXE1h5BFxJWE-IeBM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fe2e7c7cbb7807851c9446c965b6a2acd0373c9e/vscode-cairo/SUPPORT.md#L13)):*
> ```Markdown
> 
> If you have searched the GitHub issues for your problem, and still would like to contact the team,
> we are providing support on [Telegram](https://t.me/cairo_ls_support) or [Discord](https://discord.gg/QypNMzkHbc).
> ```

Done.

**Review by mkaput — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6119)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @piotmag769)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6119#-:-O3W_g-0ErsKGNpvLoW3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @piotmag769)

**Pull request merged**
