### PR TITLE
Add a simple inlining heuristic.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2062)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2062#-:-NNlEaFy4byIT-OV8C8K:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2062)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2062#-NNlF5ca26YyTPq_Uq8c:-NNlF5ca26YyTPq_Uq8d:b-hkiz6c) (no related file):*
add some test that the heuristic does inline something.

___

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2062)* status: 6 of 16 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2062#-NNlF5ca26YyTPq_Uq8c:-NNooj8YCvl1pQVAG4oe:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add some test that the heuristic does inline something.
</blockquote></details>

Done.

___

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2062)* status: 6 of 16 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 147 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2062#-NNos6Ig8B9GCjiwTwga:-NNos6Ig8B9GCjiwTwgb:bk8ilun) ([raw file](https://github.com/starkware-libs/cairo/blob/e088ab96d9f54ff2537e7f1809ec32b5569f1569/crates/cairo-lang-lowering/src/inline/mod.rs#L147)):*
> ```XML
>             // A function that just returns a literal should be inlined.
>             Statement::Literal(_) => {
>                 info.should_inline = true;
> ```

I thought about it while writing the test :)
not sure if it is a good idea or not.



_Code quote:_
```XML
            // A function that just returns a literal should be inlined.
            Statement::Literal(_) => {
                info.should_inline = true;
            }
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2062)* status: 8 of 16 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 144 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2062#-NNoy4nUACgEuzy3GB8y:-NNoy4nUACgEuzy3GB8z:b-z83ivf) ([raw file](https://github.com/starkware-libs/cairo/blob/7965cdfa75ae642a94656a67dc0cc4abcda78510/crates/cairo-lang-lowering/src/inline/mod.rs#L144)):*
> ```XML
>                     info.should_inline = true;
>                 }
>             }
> ```

extract to function.



_Code quote:_
```XML
    if let [statement] = root_block.statements.as_slice() {
        // TODO(ilya): Support other block endings.
        assert_matches!(root_block.end, FlatBlockEnd::Return(..));

        match statement {
            // If all the candidate function does is make a call to another function then it
            // should be inlined.
            Statement::Call(stmt) => {
                let concrete_function = db.lookup_intern_function(stmt.function).function;
                let semantic_db = db.upcast();
                if concrete_function.get_body(semantic_db).is_some() {
                    info.should_inline = true;
                }
            }
            // A function that just returns a literal should be inlined.
            Statement::Literal(_) => {
                info.should_inline = true;
            }
            _ => {}
        }
    }
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r3, 3 of 6 files at r4, 13 of 13 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2062)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2062#-NNp5bIkCp9fJwYAI64x:-NNp5bIkCp9fJwYAI64y:bfpw07g) (no related file):*
debugging why the cairotest failed it required - as this is really unexpected.

___

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2062)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 144 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2062#-NNoy4nUACgEuzy3GB8y:-NNp6VxB4eRHYSRbWzFJ:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/7965cdfa75ae642a94656a67dc0cc4abcda78510/crates/cairo-lang-lowering/src/inline/mod.rs#L144)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

extract to function.
</blockquote></details>

done

**Review by orizi — COMMENTED** [review]
> Reviewed 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2062)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2062)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2062#-NNp5bIkCp9fJwYAI64x:-NNpQtLC0FjAB4HV4vHx:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

debugging why the cairotest failed it required - as this is really unexpected.
</blockquote></details>

Done.



_Code quote (from crates/cairo-lang-lowering/src/inline/mod.rs):_
```XML
                let concrete_function = db.lookup_intern_function(stmt.function).function;
                let semantic_db = db.upcast();
                if concrete_function.get_body(semantic_db).is_some() {
                    info.should_inline = true;
                }
```

___

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2062)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r3, 3 of 6 files at r4, 3 of 13 files at r5, 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2062)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
