### PR TITLE
Account contract fixes.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2291)

### CODE REVIEW

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2291)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 27 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2291#-NPHNbX1CQD2b4K8QjBy:-NPHNbX1CQD2b4K8QjBz:bbjpn86) ([raw file](https://github.com/starkware-libs/cairo/blob/89271bde143aa3eada4abef4138889b0ecbad6a9/crates/cairo-lang-starknet/test_data/account.cairo#L27)):*
> ```Cairo
>                 signature_s: *signature.at(1_u32),
>             ),
>             'invalid signature',
> ```

Change to `INVALID_SIGNATURE`
___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 30 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2291#-NPHNdyWEh_pNS1CokHm:-NPHNdyWEh_pNS1CokHn:b-sbda0c) ([raw file](https://github.com/starkware-libs/cairo/blob/89271bde143aa3eada4abef4138889b0ecbad6a9/crates/cairo-lang-starknet/test_data/account.cairo#L30)):*
> ```Cairo
>         );
> 
>         'VALIDATED'
> ```

Move to a constant in the standard starknet library.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2291)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2291#-NPHNw6L7fQVgafDWWYV:-NPHNw6L7fQVgafDWWYW:b7d4wsl) ([raw file](https://github.com/starkware-libs/cairo/blob/89271bde143aa3eada4abef4138889b0ecbad6a9/crates/cairo-lang-starknet/test_data/account.cairo#L42)):*
> ```Cairo
>     ) -> felt {
>         // Note that the storage var is not set at this point, so we need to take the public
>         // key from the arguments.
> ```

Please check with @Yoni-Starkware.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2291)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 60 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2291#-NPHOx4b750T29y9v3MC:-NPHOx4b750T29y9v3MD:b-mxeqq7) ([raw file](https://github.com/starkware-libs/cairo/blob/89271bde143aa3eada4abef4138889b0ecbad6a9/crates/cairo-lang-starknet/test_data/account.cairo#L60)):*
> ```Cairo
>     #[external]
>     #[raw_output]
>     fn __execute__(
> ```

Missing some checks from `src/starkware/starknet/third_party/open_zeppelin/Account.cairo`. E.g., origin must be the OS, and tx version must not be zero.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2291)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @orizi and @Yoni-Starkware)

___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2291#-NPHNw6L7fQVgafDWWYV:-NPHSNZt3IaYotElgPBi:b-l0d6v6) ([raw file](https://github.com/starkware-libs/cairo/blob/89271bde143aa3eada4abef4138889b0ecbad6a9/crates/cairo-lang-starknet/test_data/account.cairo#L42)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Please check with @Yoni-Starkware.
</blockquote></details>

Apperently the constructor runs before __validate_deploy__, so we can use the regular flow.

I feel that we might as well inline __validate_deploy__ in the constructor in that case.
but I gues separating them allows use do use a different flow when you are deploying the account contract from a syscall.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2291)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @Yoni-Starkware)

___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2291#-NPHNw6L7fQVgafDWWYV:-NPHUnj--D-Ldhr1MTZu:b-wexon7) ([raw file](https://github.com/starkware-libs/cairo/blob/89271bde143aa3eada4abef4138889b0ecbad6a9/crates/cairo-lang-starknet/test_data/account.cairo#L42)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Apperently the constructor runs before __validate_deploy__, so we can use the regular flow.

I feel that we might as well inline __validate_deploy__ in the constructor in that case.
but I gues separating them allows use do use a different flow when you are deploying the account contract from a syscall.


</blockquote></details>

Right. We do want to support both flows using the same contract class.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2291#-NPHODrX9DWYnN8PRhJH:-NPHUV3wCNlDWNsLKcMq:b-4guuwl) ([raw file](https://github.com/starkware-libs/cairo/blob/89271bde143aa3eada4abef4138889b0ecbad6a9/crates/cairo-lang-starknet/test_data/account.cairo#L61)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

In a different PR, can we support the old ABI:
`call_array_len: felt, call_array: CallArray*, calldata_len: felt, calldata: felt*`?
There is no need to support multicall (we can assert the length is 1).
But supporting the old ABI will mean it will show correctly on the block explorer.
Making sure this is possible in Cairo1 will also increase the Cairo0-compatibility which is our current goal.
</blockquote></details>

I don't understnad is the open zeppling the only account standard that is supported?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2291)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @liorgold2, @orizi, and @Yoni-Starkware)

___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2291#-NPHNw6L7fQVgafDWWYV:-NPH_5RV3Ok7eznGwGsk:b-c2srv6) ([raw file](https://github.com/starkware-libs/cairo/blob/89271bde143aa3eada4abef4138889b0ecbad6a9/crates/cairo-lang-starknet/test_data/account.cairo#L42)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Right. We do want to support both flows using the same contract class.
</blockquote></details>

you could pass a flag to the constructor, but ok.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2291)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @liorgold2, @orizi, and @Yoni-Starkware)

___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 60 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2291#-NPHOx4b750T29y9v3MC:-NPHj648AOPBjaJfXH2-:b4hdsry) ([raw file](https://github.com/starkware-libs/cairo/blob/89271bde143aa3eada4abef4138889b0ecbad6a9/crates/cairo-lang-starknet/test_data/account.cairo#L60)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it is not intuative that __execute__ has to theck that the caller is origin.
</blockquote></details>

what happens if the version is 0?

why are future versions supported?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 60 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2291#-NPHOx4b750T29y9v3MC:-NPHrbxQ72z-Bn-_K5ob:bmm835o) ([raw file](https://github.com/starkware-libs/cairo/blob/89271bde143aa3eada4abef4138889b0ecbad6a9/crates/cairo-lang-starknet/test_data/account.cairo#L60)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what happens if the version is 0?

why are future versions supported?
</blockquote></details>

why is the tx version validated during execute and not during validate?

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2291)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @Yoni-Starkware)

___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 60 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2291#-NPHOx4b750T29y9v3MC:-NPHxuta1xPmc_XD0v-0:bvc50e5) ([raw file](https://github.com/starkware-libs/cairo/blob/89271bde143aa3eada4abef4138889b0ecbad6a9/crates/cairo-lang-starknet/test_data/account.cairo#L60)):*
> it is not intuative that execute has to theck that the caller is origin.

Right, but this is how it's done ATM. You're welcome to suggest another design.
(the problem is that otherwise any contract can invoke execute and steal you money :( )

> what happens if the version is 0?

Then it doesn't go through validate, since in v0 validate was within execute.
v0 will hopefully be removed from the OS in the following versions, but until then, it's a soundness issue.

> why are future versions supported?

Don't understand the question.

> why is the tx version validated during execute and not during validate?

Same answer as above - because in v0 it doesn't call validate at all.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2291)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @Yoni-Starkware)

___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2291#-NPHODrX9DWYnN8PRhJH:-NPHygxo5wNeF4OLfn_z:b-ekvlwk) ([raw file](https://github.com/starkware-libs/cairo/blob/89271bde143aa3eada4abef4138889b0ecbad6a9/crates/cairo-lang-starknet/test_data/account.cairo#L61)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't understnad is the open zeppling the only account standard that is supported?
</blockquote></details>

No. Argent and Braavos have accounts. I think they use the same API, but even if not - blockchain explorer has to support each of them individually.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2291)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @liorgold2, @orizi, and @Yoni-Starkware)

___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2291#-NPHODrX9DWYnN8PRhJH:-NPHzi3FDFZF6Cxvz7Jp:bi3ic8b) ([raw file](https://github.com/starkware-libs/cairo/blob/89271bde143aa3eada4abef4138889b0ecbad6a9/crates/cairo-lang-starknet/test_data/account.cairo#L61)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

we parse the calldata twice, in `__validate__` and `__execute__` this seems like a bad design.

Maybe validate should be #[raw_input]?

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2291)* status: all files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware, @liorgold2, and @Yoni-Starkware)

___
*[`crates/cairo-lang-semantic/src/items/us.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2291#-NPI50cm5aXWbjCrQ0es:-NPI50cm5aXWbjCrQ0et:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/929099a9040ac3f90d1c2b80af8bbf5274e83e4f/crates/cairo-lang-semantic/src/items/us.rs#L53)):*
> ```XML
>     let use_ast = module_uses.get(use_id).to_maybe()?;
>     let syntax_db = db.upcast();
>     eprint!("{:?}", _cycle);
> ```

remove



_Code quote:_
```XML
    eprint!("{:?}", _cycle);
```

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2291)* status: all files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware and @Yoni-Starkware)

___
*[`corelib/src/starknet.cairo` line 137 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2291#-NPIIuGfD9wCRX0XMUm-:-NPIIuGfD9wCRX0XMUm0:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/929099a9040ac3f90d1c2b80af8bbf5274e83e4f/corelib/src/starknet.cairo#L137)):*
> ```Cairo
> 
> /// The expected return value of the validated functions in an accounted contract.
> const VALIDATED: felt = 'validated';
> ```





_Suggestion:_
```Cairo
/// The expected return value of the `__validate*__` functions of an accounted contract.
const VALIDATED: felt = 'VALID';
```

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2291)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2291#-NPHODrX9DWYnN8PRhJH:-NPIKTx30XHDE9e4jv05:b8normx) ([raw file](https://github.com/starkware-libs/cairo/blob/89271bde143aa3eada4abef4138889b0ecbad6a9/crates/cairo-lang-starknet/test_data/account.cairo#L61)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

we parse the calldata twice, in `__validate__` and `__execute__` this seems like a bad design.

Maybe validate should be #[raw_input]?
</blockquote></details>

Makes sense, yes.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2291)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`corelib/src/starknet.cairo` line 137 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2291#-NPIIuGfD9wCRX0XMUm-:-NPIe7PK43jgcJDcIion:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/929099a9040ac3f90d1c2b80af8bbf5274e83e4f/corelib/src/starknet.cairo#L137)):*
> ```Cairo
> 
> /// The expected return value of the validated functions in an accounted contract.
> const VALIDATED: felt = 'validated';
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/items/us.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2291#-NPI50cm5aXWbjCrQ0es:-NPIe6RI24kksa5w6Sgu:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/929099a9040ac3f90d1c2b80af8bbf5274e83e4f/crates/cairo-lang-semantic/src/items/us.rs#L53)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2291)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 6 files at r4, 1 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2291#-:-NPT3iKeD2Px-SGF6s66:bnfp4nl)* status: 3 of 6 files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 6 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2291)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
