### PR TITLE
Fix bug in local variables aliasing.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
**Stack**:
- #5052
- #5028 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5028)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5028)* status: all files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5028#-Nq3P4Nv1Ik6URIWanim):*




_Suggestion:_
```
Fix bug in local variables aliasing.
```
___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 286 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5028#-Nq3PPts2O-lCgyca6Fy:-Nq3PPts2O-lCgyca6Fz:b-eagsez) ([raw file](https://github.com/starkware-libs/cairo/blob/a5a11dad75b58be770d08915cc3e19a6c5d00f18/crates/cairo-lang-sierra-generator/src/local_variables.rs#L286)):*
> ```XML
>         output_vars: &[VariableId],
>         params_signatures: &[ParamSignature],
>     ) -> BranchInfo {
> ```

more sensible - as the order is:
info for the inputs.
info for the outputs.
var info for inputs.
var info for outputs.



_Suggestion:_
```XML
    fn analyze_branch(
        &mut self,
        params_signatures: &[ParamSignature],
        branch_signature: &BranchSignature,
        input_vars: &[VarUsage],
        output_vars: &[VariableId],
    ) -> BranchInfo {
```
___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 291 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5028#-Nq3Q4Xq4VIHHFz8zk_z:-Nq3Q4Xq4VIHHFz8zka-:bjhazu8) ([raw file](https://github.com/starkware-libs/cairo/blob/a5a11dad75b58be770d08915cc3e19a6c5d00f18/crates/cairo-lang-sierra-generator/src/local_variables.rs#L291)):*
> ```XML
>             match output_info.ref_info {
>                 OutputVarReferenceInfo::SameAsParam { param_idx } => {
>                     // TODO(Gil): Maintain the input variable state (const, add const, deferred or
> ```

add doc as to why - not just a TODO.
___
*[`crates/cairo-lang-sierra-generator/src/local_variables_test_data/match_extern` line 16 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5028#-Nq3QHFf2_gkuHc4AtfM:-Nq3QHFf2_gkuHc4AtfN:bw1qktg) ([raw file](https://github.com/starkware-libs/cairo/blob/a5a11dad75b58be770d08915cc3e19a6c5d00f18/crates/cairo-lang-sierra-generator/src/local_variables_test_data/match_extern#L16)):*
> ```
>             revoke_ap();
>             // y is revoked, but it shouldn't, since it's the same as x, which is local.
>             // TODO(Gil): This is because the call to felt252_is_zero revokes, see 
> ```

change the test to still test the original result.
add this test to keep the todo.
___
*[`tests/bug_samples/lib.cairo` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5028#-Nq3QQXV0guQUm7SgyRQ:-Nq3QQXV0guQUm7SgyRR:bb7onj7) ([raw file](https://github.com/starkware-libs/cairo/blob/a5a11dad75b58be770d08915cc3e19a6c5d00f18/tests/bug_samples/lib.cairo#L3)):*
> ```Cairo
> mod ecdsa_completeness;
> mod indirect_impl_alias;
> mod revoked_locals;
> ```

sort
___
*[`tests/bug_samples/revoked_locals.cairo` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5028#-Nq3QTWN1ammLut62t1I:-Nq3QTWN1ammLut62t1J:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/a5a11dad75b58be770d08915cc3e19a6c5d00f18/tests/bug_samples/revoked_locals.cairo#L17)):*
> ```Cairo
> }
> 
> // #[inline(never)]
> ```

remove

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5028)* status: 2 of 6 files reviewed, 6 unresolved discussions (waiting on @orizi)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5028#-Nq3P4Nv1Ik6URIWanim):*
Done.
___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 286 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5028#-Nq3PPts2O-lCgyca6Fy:-Nq6uGCA2iM2OfdA7kDE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a5a11dad75b58be770d08915cc3e19a6c5d00f18/crates/cairo-lang-sierra-generator/src/local_variables.rs#L286)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

more sensible - as the order is:
info for the inputs.
info for the outputs.
var info for inputs.
var info for outputs.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 291 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5028#-Nq3Q4Xq4VIHHFz8zk_z:-Nq7-93E4dE2VK9Irplg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a5a11dad75b58be770d08915cc3e19a6c5d00f18/crates/cairo-lang-sierra-generator/src/local_variables.rs#L291)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add doc as to why - not just a TODO.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/local_variables_test_data/match_extern` line 16 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5028#-Nq3QHFf2_gkuHc4AtfM:-Nq72AM9A1Dnwef6Osqj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a5a11dad75b58be770d08915cc3e19a6c5d00f18/crates/cairo-lang-sierra-generator/src/local_variables_test_data/match_extern#L16)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

change the test to still test the original result.
add this test to keep the todo.
</blockquote></details>

Done.
___
*[`tests/bug_samples/lib.cairo` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5028#-Nq3QQXV0guQUm7SgyRQ:-Nq6xwTQ6EwZdu-9p9Zq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a5a11dad75b58be770d08915cc3e19a6c5d00f18/tests/bug_samples/lib.cairo#L3)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

sort
</blockquote></details>

Done.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5028)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 299 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5028#-Nq7AiiT-SQ_pGODPVA4:-NqP8lpuAVI1Y3sWYkvk:b874hhh) ([raw file](https://github.com/starkware-libs/cairo/blob/7e20ae3e554736b63721aca570aa71aed4ec57f2/crates/cairo-lang-sierra-generator/src/local_variables.rs#L299)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the same test is required for `PartialParam` as well.
This may make you have to do the proper solution instead.
</blockquote></details>

Changed to follow only consts.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5028)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 237 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5028#-NqPA-ga02b6CGxZ2I0n:-NqPA-ga02b6CGxZ2I0o:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/0bd77a43f92b23294cd39b94d3e9ce2433b3ca12/crates/cairo-lang-sierra-generator/src/local_variables.rs#L237)):*
> ```XML
>         var
>     }
>     pub fn peel_const_aliases(&'a self, mut var: &'a VariableId) -> &VariableId {
> ```

doc

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5028)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 237 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5028#-NqPA-ga02b6CGxZ2I0n:-NqRPldV9tr8WM-XMK-i:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0bd77a43f92b23294cd39b94d3e9ce2433b3ca12/crates/cairo-lang-sierra-generator/src/local_variables.rs#L237)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5028#-:-NqRVnDk3rWPVhXABKIg:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
