### PR TITLE
Compute the semantic representation of a constant definition.

### PR DESCRIPTION
**Pull request by liorgold2**
commit-id:1cf1a7dc

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1797#-:-NM16hHOBpN1w025FHId:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1797)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1797#-NM33bSH8fKsOmX8ASUt:-NM33bSH8fKsOmX8ASUu:b-g6ckkw) ([raw file](https://github.com/starkware-libs/cairo/blob/f2650ef6948921378921ba36b2cf551bbb4d6ee9/crates/cairo-lang-semantic/src/items/constant.rs#L22)):*
> ```XML
> #[debug_db(dyn SemanticGroup + 'static)]
> pub struct Constant {
>     value: Expr,
> ```

How is this going to be lowered? What is the right representation here? I'm thinking about general structs, or Span even..

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1797)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1797#-NM33bSH8fKsOmX8ASUt:-NM3X5o6CvihXsf4xJ8G:b-be0s05) ([raw file](https://github.com/starkware-libs/cairo/blob/f2650ef6948921378921ba36b2cf551bbb4d6ee9/crates/cairo-lang-semantic/src/items/constant.rs#L22)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

How is this going to be lowered? What is the right representation here? I'm thinking about general structs, or Span even..
</blockquote></details>

Currently, the plan is to restrict the expr to be a literal and to only support things like `felt`, `u128` and `bool`.
For the future: it seems the constant resolution (e.g., computation of the constant in `const X = 5 + 3`) should be in the lowering phase and not in the semantic phase. Assuming this, `Constant::value` should probably stay `Expr` also when we have more complicated things.
WDYT?

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1797#-:-NM3mxIkBQQ6KvK7bQ5B:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1797)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
