### PR TITLE
libfunc coverage test

### PR DESCRIPTION
**Pull request by Tomer-StarkWare**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6135)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6135)* status: 4 of 9 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/src/plugin/test.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6135#-O3WXdPq9hUFdbObjXpc:-O3WXdPwAmQ55rh8oA_o:b-48j562) ([raw file](https://github.com/starkware-libs/cairo/blob/2bc7ec219e1ecde6f53a1a7d71ed426908c60e85/crates/cairo-lang-starknet/src/plugin/test.rs#L150)):*
> ```XML
>     {
>         hello_starknet: "hello_starknet",
>         libfuncs_coverage: "libfuncs_coverage",
> ```

remove from the expand test - the only interesting test for this is the class compilation tests.



_Code quote:_
```XML
        libfuncs_coverage: "libfuncs_coverage",
```
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/libfuncs_coverage` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6135#-O3WXy1D9poDghjmLkOC:-O3WXy1D9poDghjmLkOD:b-9li8yt) ([raw file](https://github.com/starkware-libs/cairo/blob/2bc7ec219e1ecde6f53a1a7d71ed426908c60e85/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/libfuncs_coverage#L1)):*
> ```
> //! > Test libfuncs usage.
> ```

remove file.
___
*[`crates/cairo-lang-starknet-classes/src/casm_contract_class_test.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6135#-O3WZDjm2Ov--lH8H6y4:-O3WZDjm2Ov--lH8H6y5:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2bc7ec219e1ecde6f53a1a7d71ed426908c60e85/crates/cairo-lang-starknet-classes/src/casm_contract_class_test.rs#L62)):*
> ```XML
> #[test_case("libfuncs_coverage__libfuncs_coverage")]
> fn test_contract_libfuncs_coverage(name: &str) {
>     let libfunc_to_cover = [
> ```





_Suggestion:_
```XML
 OrderedHashMap::from_iter([
```
___
*[`crates/cairo-lang-starknet-classes/src/casm_contract_class_test.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6135#-O3WYmp44Dq_JVXqQGsq:-O3WYmp44Dq_JVXqQGsr:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2bc7ec219e1ecde6f53a1a7d71ed426908c60e85/crates/cairo-lang-starknet-classes/src/casm_contract_class_test.rs#L116)):*
> ```XML
>     for libfunc_declaration in libfunc_declarations.iter() {
>         libfunc_generics.push(libfunc_declaration.long_id.generic_id.to_string());
>     }
> ```





_Suggestion:_
```XML
    let used_libfuncs = OrderedHashMap::from_iter(
        program.libfunc_declarations.iter().map(|decl|decl.long_id.generic_id.to_string())
    );
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6135)* status: 4 of 9 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/test.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6135#-O3WXdPq9hUFdbObjXpc:-O3WaNnK5jfw22bwM9cC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2bc7ec219e1ecde6f53a1a7d71ed426908c60e85/crates/cairo-lang-starknet/src/plugin/test.rs#L150)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove from the expand test - the only interesting test for this is the class compilation tests.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/libfuncs_coverage` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6135#-O3WXy1D9poDghjmLkOC:-O3WaJZp3UdbBsycsz1k:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2bc7ec219e1ecde6f53a1a7d71ed426908c60e85/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/libfuncs_coverage#L1)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove file.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet-classes/src/casm_contract_class_test.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6135#-O3WZDjm2Ov--lH8H6y4:-O3Wfn7rC7EPpnqNlRKp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2bc7ec219e1ecde6f53a1a7d71ed426908c60e85/crates/cairo-lang-starknet-classes/src/casm_contract_class_test.rs#L62)):*
> ```XML
> #[test_case("libfuncs_coverage__libfuncs_coverage")]
> fn test_contract_libfuncs_coverage(name: &str) {
>     let libfunc_to_cover = [
> ```

Done.
___
*[`crates/cairo-lang-starknet-classes/src/casm_contract_class_test.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6135#-O3WYmp44Dq_JVXqQGsq:-O3Wg9LDEXyWiJPLjbzQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2bc7ec219e1ecde6f53a1a7d71ed426908c60e85/crates/cairo-lang-starknet-classes/src/casm_contract_class_test.rs#L116)):*
> ```XML
>     for libfunc_declaration in libfunc_declarations.iter() {
>         libfunc_generics.push(libfunc_declaration.long_id.generic_id.to_string());
>     }
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6135)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet-classes/src/casm_contract_class_test.rs` line 118 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6135#-O3Wh3DM0ktY43sLWYKN:-O3Wh3DM0ktY43sLWYKO:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/485d4623271662b721d73d5806d0efe5e5ec2fe3/crates/cairo-lang-starknet-classes/src/casm_contract_class_test.rs#L118)):*
> ```XML
>     let used_libfuncs: OrderedHashSet<String> = OrderedHashSet::from_iter(
>         program.libfunc_declarations.iter().map(|decl| decl.long_id.generic_id.to_string()),
>     );
> ```





_Suggestion:_
```XML
    let used_libfuncs = OrderedHashSet::from_iter(
        program.libfunc_declarations.iter().map(|decl| decl.long_id.generic_id.to_string()),
    );
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6135)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet-classes/src/casm_contract_class_test.rs` line 129 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6135#-O3Wh9Rs4Zqf1lY5kD03:-O3Wh9Rs4Zqf1lY5kD04:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/485d4623271662b721d73d5806d0efe5e5ec2fe3/crates/cairo-lang-starknet-classes/src/casm_contract_class_test.rs#L129)):*
> ```XML
>         assert!(
>             libfunc_to_cover.contains(libfunc_name),
>             "libfunc {libfunc_name} is covered by the contract but not in the list."
> ```

.



_Suggestion:_
```XML
            "libfunc `{libfunc_name}` is not in covered by the contract."
        );
    }
    for libfunc_name in used_libfuncs.iter() {
        assert!(
            libfunc_to_cover.contains(libfunc_name),
            "libfunc `{libfunc_name}` is covered by the contract but not in the list."
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 9 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6135#-:-O3WscuwBb3wzRCjM1y1:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6135)* status: all files reviewed, 2 unresolved discussions (waiting on @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/contracts/libfuncs_coverage.cairo` line 63 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6135#-O3X--MN3R5-hz3b6X8C:-O3X--MO5eUZgvBUtHpk:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2bc7ec219e1ecde6f53a1a7d71ed426908c60e85/crates/cairo-lang-starknet/cairo_level_tests/contracts/libfuncs_coverage.cairo#L63)):*
> ```Cairo
> fn use_and_panic<T, +PanicDestruct<T>>(t: T) {
>     panic!();
> }
> ```





_Suggestion:_
```Cairo
#[inline(never)}
fn int_libfuncs<T, +Add<T>, +Sub<T>, +PanicDestruct<T>>(libfuncs: IntLibfuncs<T>) {
    match libfuncs {
        IntLibfuncs::Add((a, b)) => use_and_panic(a + b),
        IntLibfuncs::Sub((a, b)) => use_and_panic(a - b),
    }
}

#[inline(never)]
fn use_and_panic<T, +PanicDestruct<T>>(t: T) {
    panic!();
}
```
___
*[`crates/cairo-lang-starknet/cairo_level_tests/contracts/libfuncs_coverage.cairo` line 17 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6135#-O3WyMdNCd08f5aEx3y2:-O3WyMdNCd08f5aEx3y3:b-vdgi41) ([raw file](https://github.com/starkware-libs/cairo/blob/2c1870a73242792605ed8b1870d5dca91c9f541c/crates/cairo-lang-starknet/cairo_level_tests/contracts/libfuncs_coverage.cairo#L17)):*
> ```Cairo
> 
> enum Libfuncs {
>     None,
> ```

Why `None` is needed?



_Code quote:_
```Cairo
None,
```

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6135)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/contracts/libfuncs_coverage.cairo` line 63 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6135#-O3X--MN3R5-hz3b6X8C:-O3X1XtzDjOCb2jLeuv3:bhsaz2i) ([raw file](https://github.com/starkware-libs/cairo/blob/2bc7ec219e1ecde6f53a1a7d71ed426908c60e85/crates/cairo-lang-starknet/cairo_level_tests/contracts/libfuncs_coverage.cairo#L63)):*
> ```Cairo
> fn use_and_panic<T, +PanicDestruct<T>>(t: T) {
>     panic!();
> }
> ```

no need whatsoever.

the other one is required for ensuring this contracts works as intended.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/contracts/libfuncs_coverage.cairo` line 17 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6135#-O3WyMdNCd08f5aEx3y2:-O3X1RPB1QdVp3GMkPdF:btpz5on) ([raw file](https://github.com/starkware-libs/cairo/blob/2c1870a73242792605ed8b1870d5dca91c9f541c/crates/cairo-lang-starknet/cairo_level_tests/contracts/libfuncs_coverage.cairo#L17)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Why `None` is needed?
</blockquote></details>

to call it without thinking about specific setup.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6135#-:-O3X96mO6tnRoWL1LfCo:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Tomer-StarkWare)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6135)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Tomer-StarkWare)

**Pull request merged**
