### PR TITLE
Add semantic support for inline modules.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1309)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1309#-:-NJAdpYM2YORKQbN_hXH:bnfp4nl)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @orizi and @yuvalsw)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1309)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`crates/defs/src/db.rs` line 217 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1309#-NJArHHK4TYvCVsBw8ng:-NJArHHK4TYvCVsBw8nh:b6tfulc) ([raw file](https://github.com/starkware-libs/cairo/blob/0ab0cac9ff3e93984869ba21c75b479b844efb7d/crates/defs/src/db.rs#L217)):*
> ```XML
> 
>     let mut item_list = match module_id {
>         ModuleId::Submodule(SubmoduleId::Inline(id)) => {
> ```

add TODO to consider if we can move back to virtual modules.



_Code quote:_
```XML
    let mut item_list = match module_id {
        ModuleId::Submodule(SubmoduleId::Inline(id)) => {
            let parent = id.parent(db);
```
___
*[`crates/defs/src/db.rs` line 229 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1309#-NJAriGm-wmp5nLtKnDG:-NJAriGnCWTshNItzGe-:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0ab0cac9ff3e93984869ba21c75b479b844efb7d/crates/defs/src/db.rs#L229)):*
> ```XML
> 
>             match db.module_data(parent)?.submodules[SubmoduleId::Inline(id)].body(syntax_db) {
>                 MaybeModuleBody::Some(body) => body.items(syntax_db),
> ```





_Suggestion:_
```XML
            extract_matches!(db.module_data(parent)?.submodules[SubmoduleId::Inline(id)].body(syntax_db), MaybeModuleBody::Some, "Expected an inline module").items(syntax_db)}
```
___
*[`crates/defs/src/db.rs` line 320 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1309#-NJArzPV1v6vtv-wz3xj:-NJArzPW9WPCcB1-3eUW:bnnahz0) ([raw file](https://github.com/starkware-libs/cairo/blob/0ab0cac9ff3e93984869ba21c75b479b844efb7d/crates/defs/src/db.rs#L320)):*
> ```XML
> 
>         match file_queue.pop_front() {
>             Some(next_file) => file = next_file,
> ```

consider while and using a pair with an optional file.



_Code quote:_
```XML
        match file_queue.pop_front() {
            Some(next_file) => file = next_file,
            None => break,
        };
        let syntax_file = db.file_syntax(file)?;
        item_list = syntax_file.items(syntax_db);
```

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1309)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @yuvalsw)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1309)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/defs/src/db.rs` line 217 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1309#-NJArHHK4TYvCVsBw8ng:-NJAvxQu0oZQIKBVzZMR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0ab0cac9ff3e93984869ba21c75b479b844efb7d/crates/defs/src/db.rs#L217)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add TODO to consider if we can move back to virtual modules.
</blockquote></details>

Done.
___
*[`crates/defs/src/db.rs` line 229 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1309#-NJAriGm-wmp5nLtKnDG:-NJAwZFbCeHrxv-ypr5E:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0ab0cac9ff3e93984869ba21c75b479b844efb7d/crates/defs/src/db.rs#L229)):*
> ```XML
> 
>             match db.module_data(parent)?.submodules[SubmoduleId::Inline(id)].body(syntax_db) {
>                 MaybeModuleBody::Some(body) => body.items(syntax_db),
> ```

Done.
___
*[`crates/defs/src/db.rs` line 320 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1309#-NJArzPV1v6vtv-wz3xj:-NJAw_Eg63xqdx37IyuJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0ab0cac9ff3e93984869ba21c75b479b844efb7d/crates/defs/src/db.rs#L320)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

consider while and using a pair with an optional file.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1309)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`crates/defs/src/db.rs` line 233 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1309#-NJBBjoo-fhbi42TNX2A:-NJBBjoq5oUeodrKk62B:br5if0j) ([raw file](https://github.com/starkware-libs/cairo/blob/4a6701c9928f2e5fbe8bea653916b6368e10797f/crates/defs/src/db.rs#L233)):*
> ```XML
>             // Create an empty dummy file for domains separation between virtual submodules
>             // of the parent module and virtual submodules of the inline module.
>             let module_file = db.intern_file(FileLongId::Virtual(VirtualFile {
> ```

move this to the other pr as discussed



_Code quote:_
```XML
            // Create an empty dummy file for domains separation between virtual submodules
            // of the parent module and virtual submodules of the inline module.
            let module_file = db.intern_file(FileLongId::Virtual(VirtualFile {
                parent: Some(parent_file),
                name: format!("__{}", id.name(db.upcast())).into(),
                content: Arc::new(String::new()),
            }));
```

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 2 of 5 files at r1, 1 of 2 files at r2, 1 of 2 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1309#-:-NJBQLAx9jY-b7rhmI4z:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/defs/src/db.rs` line 225 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1309#-NJBOp_bCkfDqu_7D9dO:-NJBOp_c8ISy8_1VRjzm:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d323b36418b5ba8671051e24e4f5e14595ce6ef6/crates/defs/src/db.rs#L225)):*
> ```XML
>     let module_file = db.module_main_file(module_id)?;
> 
>     let item_list = match module_id {
> ```





_Suggestion:_
```XML
item_asts
```
___
*[`crates/defs/src/db.rs` line 231 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1309#-NJBNDIq0JXI4eVTLWbH:-NJBNDIq0JXI4eVTLWbI:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d323b36418b5ba8671051e24e4f5e14595ce6ef6/crates/defs/src/db.rs#L231)):*
> ```XML
>         ModuleId::Submodule(SubmoduleId::Inline(inline_submodule_id)) => {
>             // TODO(ilya): Can we avoid lookuing up the parent module_data here?
>             let item_module = &db.module_data(inline_submodule_id.parent(db))?.submodules
> ```





_Suggestion:_
```XML
item_module_ast
```
___
*[`crates/defs/src/db.rs` line 250 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1309#-NJBOtLx8WPNNHfcDPd4:-NJBOtLyDRa51RTPGZNV:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d323b36418b5ba8671051e24e4f5e14595ce6ef6/crates/defs/src/db.rs#L250)):*
> ```XML
>         res.files.push(module_file);
> 
>         for item in item_list.elements(syntax_db) {
> ```





_Suggestion:_
```XML
 item_ast
```
___
*[`crates/defs/src/db.rs` line 263 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1309#-NJBO2E8BiCbxpzC2DlT:-NJBO2E8BiCbxpzC2DlU:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d323b36418b5ba8671051e24e4f5e14595ce6ef6/crates/defs/src/db.rs#L263)):*
> ```XML
>                     content: Arc::new(content),
>                 }));
>                 // TODO(ilya): consider implementing virtual modules as inline modules.
> ```





_Suggestion:_
```XML
 TODO(ilya): Consider implementing plugin-generated modules as inline modules.
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1309)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi and @yuvalsw)

___
*[`crates/defs/src/db.rs` line 233 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1309#-NJBBjoo-fhbi42TNX2A:-NJBRQKR2qFJ5R2qC-FD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4a6701c9928f2e5fbe8bea653916b6368e10797f/crates/defs/src/db.rs#L233)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

move this to the other pr as discussed
</blockquote></details>

Done.
___
*[`crates/defs/src/db.rs` line 225 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1309#-NJBOp_bCkfDqu_7D9dO:-NJBQdi40ymVeVXeTD-w:b-ha46iy) ([raw file](https://github.com/starkware-libs/cairo/blob/d323b36418b5ba8671051e24e4f5e14595ce6ef6/crates/defs/src/db.rs#L225)):*
> item_asts
done
___
*[`crates/defs/src/db.rs` line 231 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1309#-NJBNDIq0JXI4eVTLWbH:-NJBRO_m0T_-Xvsoa0Us:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/d323b36418b5ba8671051e24e4f5e14595ce6ef6/crates/defs/src/db.rs#L231)):*
> ```XML
>         ModuleId::Submodule(SubmoduleId::Inline(inline_submodule_id)) => {
>             // TODO(ilya): Can we avoid lookuing up the parent module_data here?
>             let item_module = &db.module_data(inline_submodule_id.parent(db))?.submodules
> ```

done
___
*[`crates/defs/src/db.rs` line 250 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1309#-NJBOtLx8WPNNHfcDPd4:-NJBRRyX-RTVqB9823RR:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/d323b36418b5ba8671051e24e4f5e14595ce6ef6/crates/defs/src/db.rs#L250)):*
> ```XML
>         res.files.push(module_file);
> 
>         for item in item_list.elements(syntax_db) {
> ```

done
___
*[`crates/defs/src/db.rs` line 263 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1309#-NJBO2E8BiCbxpzC2DlT:-NJBRn9T2aewBrxt_9Ss:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/d323b36418b5ba8671051e24e4f5e14595ce6ef6/crates/defs/src/db.rs#L263)):*
> ```XML
>                     content: Arc::new(content),
>                 }));
>                 // TODO(ilya): consider implementing virtual modules as inline modules.
> ```

done

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 4 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1309)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
