### PR TITLE
Add default dict value trait and make it a requirement for the dict t…

### PR DESCRIPTION
**Pull request by gilbens-starkware**
…rait.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2826)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2826)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @liorgold2)

___
*[`corelib/src/traits.cairo` line 118 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2826#-NT5um8Q2hZiwj2iuvxw:-NT5um8R7LUkaYBapUaH:b-67jxzo) ([raw file](https://github.com/starkware-libs/cairo/blob/a9dae178a42812e51a56310c7af322c6e45d12a8/corelib/src/traits.cairo#L118)):*
> ```Cairo
> 
> /// Trait for default values of value in a dict. Should be logically equivalent to 0.
> trait Felt252DictDefault<T> {
> ```

didn't we call it `Felt252DictValue`?



_Code quote:_
```Cairo
/// Trait for default values of value in a dict. Should be logically equivalent to 0.
trait Felt252DictDefault<T> {
    fn felt252dict_default() -> T nopanic;
}
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2826)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @liorgold2)

___
*[`corelib/src/integer.cairo` line 1227 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2826#-NT5utFG0POhETKYm3X9:-NT5utFG0POhETKYm3XA:b-erf8gk) ([raw file](https://github.com/starkware-libs/cairo/blob/a9dae178a42812e51a56310c7af322c6e45d12a8/corelib/src/integer.cairo#L1227)):*
> ```Cairo
> }
> 
> impl U256Felt252DictDefault of Felt252DictDefault<u256> {
> ```

this is not a valid dict value - so we should not impl it.



_Code quote:_
```Cairo
impl U256Felt252DictDefault of Felt252DictDefault<u256> {
    #[inline(always)]
    fn felt252dict_default() -> u256 nopanic {
        u256 { low: 0, high: 0 }
    }
}
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2826)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`corelib/src/integer.cairo` line 1227 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2826#-NT5utFG0POhETKYm3X9:-NT5yXxX7Ed3EnvHX90T:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a9dae178a42812e51a56310c7af322c6e45d12a8/corelib/src/integer.cairo#L1227)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is not a valid dict value - so we should not impl it.
</blockquote></details>

Done.
___
*[`corelib/src/traits.cairo` line 118 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2826#-NT5um8Q2hZiwj2iuvxw:-NT5yZER8b3u_Rd4mWJ6:bms1h1c) ([raw file](https://github.com/starkware-libs/cairo/blob/a9dae178a42812e51a56310c7af322c6e45d12a8/corelib/src/traits.cairo#L118)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

didn't we call it `Felt252DictValue`?
</blockquote></details>

Not sure, but I think `Felt252DictValue` doesn't convey the meaning of the trait.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2826)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @liorgold2)

___
*[`corelib/src/lib.cairo` line 375 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2826#-NT6T6gd2dzutuSzqss6:-NT6T6gd2dzutuSzqss7:b-varqpm) ([raw file](https://github.com/starkware-libs/cairo/blob/79c8e8d73232e7bc6628d1acf74056529399da88/corelib/src/lib.cairo#L375)):*
> ```Cairo
> use integer::U128Default;
> use integer::U256Default;
> use integer::U8Felt252DictDefault;
> ```

i think these are no longer required.



_Code quote:_
```Cairo
use integer::U8Felt252DictDefault;
use integer::U16Felt252DictDefault;
use integer::U32Felt252DictDefault;
use integer::U64Felt252DictDefault;
use integer::U128Felt252DictDefault;
```
___
*[`corelib/src/traits.cairo` line 118 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2826#-NT5um8Q2hZiwj2iuvxw:-NT6TQW1B1cGPPtgMv6q:b-c8azzi) ([raw file](https://github.com/starkware-libs/cairo/blob/a9dae178a42812e51a56310c7af322c6e45d12a8/corelib/src/traits.cairo#L118)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Not sure, but I think `Felt252DictValue` doesn't convey the meaning of the trait. 
</blockquote></details>

it does - the meaning of the trait is the fact that this is an allowed value.
this requires the default function - but that is not the actual name of the trait.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2826)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`corelib/src/lib.cairo` line 375 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2826#-NT6T6gd2dzutuSzqss6:-NT91f-v5dCvQHf4Asau:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/79c8e8d73232e7bc6628d1acf74056529399da88/corelib/src/lib.cairo#L375)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i think these are no longer required.
</blockquote></details>

Done.
___
*[`corelib/src/traits.cairo` line 118 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2826#-NT5um8Q2hZiwj2iuvxw:-NT91cDP9YTIX1kCZWZA:bl5u7xw) ([raw file](https://github.com/starkware-libs/cairo/blob/a9dae178a42812e51a56310c7af322c6e45d12a8/corelib/src/traits.cairo#L118)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it does - the meaning of the trait is the fact that this is an allowed value.
this requires the default function - but that is not the actual name of the trait.
</blockquote></details>

Got it, Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2826)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @liorgold2)

___
*[`corelib/src/lib.cairo` line 375 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2826#-NT6T6gd2dzutuSzqss6:-NT9DAfo3GJ0x3jL2q74:blvt4sm) ([raw file](https://github.com/starkware-libs/cairo/blob/79c8e8d73232e7bc6628d1acf74056529399da88/corelib/src/lib.cairo#L375)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Why did you leave the u128?
___
*[`corelib/src/traits.cairo` line 119 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2826#-NT9Devk2zy3-NOCXQrz:-NT9Devk2zy3-NOCXQs-:bekf4kz) ([raw file](https://github.com/starkware-libs/cairo/blob/e3393cf8f5c443c0ed41753ae35e22a2ee9b1c99/corelib/src/traits.cairo#L119)):*
> ```Cairo
> /// Trait for default values of value in a dict. Should be logically equivalent to 0.
> trait Felt252DictValue<T> {
>     fn felt252dict_default() -> T nopanic;
> ```

Maybe `zero_default`

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2826)* status: 4 of 9 files reviewed, 3 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`corelib/src/lib.cairo` line 375 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2826#-NT6T6gd2dzutuSzqss6:-NT9FHeQ8aLKHikPoWl-:bs4eapo) ([raw file](https://github.com/starkware-libs/cairo/blob/79c8e8d73232e7bc6628d1acf74056529399da88/corelib/src/lib.cairo#L375)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Why did you leave the u128?
</blockquote></details>

Did I?
___
*[`corelib/src/traits.cairo` line 119 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2826#-NT9Devk2zy3-NOCXQrz:-NT9HmI0-LyzOXsSTEsS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e3393cf8f5c443c0ed41753ae35e22a2ee9b1c99/corelib/src/traits.cairo#L119)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Maybe `zero_default`
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2826#-:-NT9afBd-hjxLUwCxPtL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
