### PR TITLE
Add diagnostic for literal out of range.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2075)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2075)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2075#-NNp2ov1EXM-0MntURZZ:-NNp2ov22C71L-6wNpP0:b-lefas8) (no related file):*
Change target branch.

___

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2075)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 513 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2075#-NNp3hwv3gtTdq48kxe-:-NNp3hwv3gtTdq48kxe0:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2bb4cea370e1c37cc8e28bdfc70d5e18f9d9e13e/crates/cairo-lang-semantic/src/corelib.rs#L513)):*
> ```XML
>         .unwrap())
>     } else if ty == u8_ty {
>         Ok((BigInt::from(1) << 8) - 1)
> ```





_Suggestion:_
```XML
    } else if ty == u8_ty {
        Ok((BigInt::from(u8::MAX))
    } else if ty == u32_ty {
        Ok((BigInt::from(u32::MAX))
    } else if ty == u64_ty {
        Ok((BigInt::from(u64::MAX))
    } else if ty == u128_ty {
        Ok((BigInt::from(u128::MAX))
    } else {
        Err(SemanticDiagnosticKind::NoLiteralFunctionFound)
    }
}
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2075)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1155 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2075#-NNp4Mgv0L-4Kh52b7ug:-NNp4Mgv0L-4Kh52b7uh:bb0ivg1) ([raw file](https://github.com/starkware-libs/cairo/blob/2bb4cea370e1c37cc8e28bdfc70d5e18f9d9e13e/crates/cairo-lang-semantic/src/expr/compute.rs#L1155)):*
> ```XML
>     if value < BigInt::from(0)
>         || value
>             > try_get_type_max_value(db, ty)
> ```

merge these two functions, maybe even pass the bound variable inside.



_Code quote:_
```XML
    if value < BigInt::from(0)
        || value
            > try_get_type_max_value(db, ty)
                .map_err(|err| ctx.diagnostics.report(literal_syntax, err))?
    {
        return Err(ctx.diagnostics.report(literal_syntax, LiteralOutOfRange { ty }));
    }
    try_get_const_libfunc_name_by_type(db, ty)
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2075)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 513 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2075#-NNp3hwv3gtTdq48kxe-:-NNpS9b46CSAIsfOstFz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2bb4cea370e1c37cc8e28bdfc70d5e18f9d9e13e/crates/cairo-lang-semantic/src/corelib.rs#L513)):*
> ```XML
>         .unwrap())
>     } else if ty == u8_ty {
>         Ok((BigInt::from(1) << 8) - 1)
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1155 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2075#-NNp4Mgv0L-4Kh52b7ug:-NNpSCd8C1asPHMCT9oe:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2bb4cea370e1c37cc8e28bdfc70d5e18f9d9e13e/crates/cairo-lang-semantic/src/expr/compute.rs#L1155)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

merge these two functions, maybe even pass the bound variable inside.
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2075)* status: 3 of 5 files reviewed, 3 unresolved discussions

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2075#-:-NNqW5Or3-nLMKc6d7T0:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 488 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2075#-NNqVv-P0xxP0Vq_ge4-:-NNqVv-P0xxP0Vq_ge40:bqiolbi) ([raw file](https://github.com/starkware-libs/cairo/blob/72df1eb667002507c54052a90301c8aa227e6ead/crates/cairo-lang-semantic/src/corelib.rs#L488)):*
> ```XML
> 
> /// Checks if a value fits in range for a specific type, and returns an error if not.
> pub fn is_value_in_type_range(
> ```

as it validates the type as well.
update doc accordingly.



_Suggestion:_
```XML
validate_literal
```
___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 497 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2075#-NNqVXXb65pzMrvUMMm_:-NNqVXXc6SP9Mu7y2dyE:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/72df1eb667002507c54052a90301c8aa227e6ead/crates/cairo-lang-semantic/src/corelib.rs#L497)):*
> ```XML
>     if ty == core_felt_ty(db) {
>         max_value = BigInt::from_str_radix(
>             "800000000000011000000000000000000000000000000000000000000000000",
> ```





_Suggestion:_
```XML
pub fn is_value_in_type_range(
    db: &dyn SemanticGroup,
    ty: TypeId,
    value: BigInt,
) -> Result<(), SemanticDiagnosticKind> {
    // As for now all types are non-negative, add min_value when signed integers are added.
    let max_value =
    if ty == core_felt_ty(db) {
        max_value = BigInt::from_str_radix(
            "800000000000011000000000000000000000000000000000000000000000000",
            16,
        )
        .unwrap();
    } else if ty == get_core_ty_by_name(db, "u8".into(), vec![]) {
        BigInt::from(u8::MAX)
    } else if ty == get_core_ty_by_name(db, "u16".into(), vec![]) {
        BigInt::from(u16::MAX)
    } else if ty == get_core_ty_by_name(db, "u32".into(), vec![]) {
        BigInt::from(u32::MAX)
    } else if ty == get_core_ty_by_name(db, "u64".into(), vec![]) {
        BigInt::from(u64::MAX)
    } else if ty == get_core_ty_by_name(db, "u128".into(), vec![]) {
        BigInt::from(u128::MAX)
    } else {
        return Err(SemanticDiagnosticKind::NoLiteralFunctionFound);
    };
    if !(value >= BigInt::from(0) && value <= max_value) {
        Err(SemanticDiagnosticKind::LiteralOutOfRange { ty })
    } else {
        Ok(())
    }
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2075)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 501 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2075#-NNq_DLm0RVuZ9V4cvgY:-NNq_DLm0RVuZ9V4cvgZ:b-7w5x54) ([raw file](https://github.com/starkware-libs/cairo/blob/f4bb438144cead0e5c7cc809001011402425bb2f/crates/cairo-lang-semantic/src/corelib.rs#L501)):*
> ```XML
>         )
>         .unwrap()
>     } else if ty == get_core_ty_by_name(db, "u8".into(), vec![]) {
> ```

value.is_negative() || value.bits() > 8;



_Code quote:_
```XML
    } else if ty == get_core_ty_by_name(db, "u8".into(), vec![]) {
```

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2075)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
