### PR TITLE
Move storage var logic inside a module.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1316)

### CODE REVIEW

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1316#-:-NJFYNaB0oI15Vq1j-IO:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/starknet/src/plugin.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1316#-NJFXvG6D-Dcec3eOr4s:-NJFXvG6D-Dcec3eOr4t:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/bcb245ca1a659b8df416dc04ef551b1ace435f9a/crates/starknet/src/plugin.rs#L50)):*
> ```XML
>         let getter = quote! {
>             mod $name {
>                 func read(ref syscall_ptr: SyscallPtr) -> felt {
> ```





_Suggestion:_
```XML
system
```

**Review by yuvalsw — APPROVED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1316)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/defs/src/ids.rs` line 307 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1316#-NJFuG5RBvBb09IZvHc2:-NJFuG5RBvBb09IZvHc3:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f6840924431ac502994e47d0fb9808cfb5b9a437/crates/defs/src/ids.rs#L307)):*
> ```XML
> 
>     pub fn parent(&self, db: &dyn DefsGroup) -> ModuleId {
>         db.lookup_intern_inline_submodule(*self).0.0
> ```





_Suggestion:_
```XML
        self.module_file_id(db).0
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1316)* status: 5 of 7 files reviewed, all discussions resolved (waiting on @yuvalsw)

___
*[`crates/defs/src/ids.rs` line 307 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1316#-NJFuG5RBvBb09IZvHc2:-NJFxKcr4st95M3CmvOo:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/f6840924431ac502994e47d0fb9808cfb5b9a437/crates/defs/src/ids.rs#L307)):*
> ```XML
> 
>     pub fn parent(&self, db: &dyn DefsGroup) -> ModuleId {
>         db.lookup_intern_inline_submodule(*self).0.0
> ```

done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 5 of 7 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1316)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
