### PR TITLE
Add missing test files and sort.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3598)

### CODE REVIEW

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3598#-:-NZ_Cif38Ju7HkkFAdUO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3598)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`corelib/src/test/secp256r1_test.cairo` line 37 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3598#-NZ_HIEf9y_lFpI9ifri:-NZ_HIEf9y_lFpI9ifrj:b-3c8efg) ([raw file](https://github.com/starkware-libs/cairo/blob/573098ee08f341259c45b6e62075827f84980336/corelib/src/test/secp256r1_test.cairo#L37)):*
> ```Cairo
>     // msg = ""
>     // public key: (0x04aaec73635726f213fb8a9e64da3b8632e41495a944d0045b522eba7240fad5,
>     //              0x0087d9315798aaa3a5ba01775787ced05eaaf7b4e09fc81d6d1aa546e8365d525d)
> ```

Why removed?
This is to help in debugging. It's not easy to build inputs for this test



_Code quote:_
```Cairo
    // msg = ""
    // public key: (0x04aaec73635726f213fb8a9e64da3b8632e41495a944d0045b522eba7240fad5,
    //              0x0087d9315798aaa3a5ba01775787ced05eaaf7b4e09fc81d6d1aa546e8365d525d)
```

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3598)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`corelib/src/test/secp256r1_test.cairo` line 37 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3598#-NZ_HIEf9y_lFpI9ifri:-NZ_HaHP1vFZc9G-N_Lc:b-cii2lw) ([raw file](https://github.com/starkware-libs/cairo/blob/573098ee08f341259c45b6e62075827f84980336/corelib/src/test/secp256r1_test.cairo#L37)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Why removed?
This is to help in debugging. It's not easy to build inputs for this test
</blockquote></details>

It's a comment, not code leftovers.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3598)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`corelib/src/test/secp256r1_test.cairo` line 37 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3598#-NZ_HIEf9y_lFpI9ifri:-NZ_HltM4ZOiSCchGAAO:b-hbu9mt) ([raw file](https://github.com/starkware-libs/cairo/blob/573098ee08f341259c45b6e62075827f84980336/corelib/src/test/secp256r1_test.cairo#L37)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

It's a comment, not code leftovers.
</blockquote></details>

this is code leftovers - as it does not exist in k1 - and matches the values in k1

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3598)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`corelib/src/test/secp256r1_test.cairo` line 37 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3598#-NZ_HIEf9y_lFpI9ifri:-NZ_Hx6A7MnIFU1pNJoG:brrtlbm) ([raw file](https://github.com/starkware-libs/cairo/blob/573098ee08f341259c45b6e62075827f84980336/corelib/src/test/secp256r1_test.cairo#L37)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is code leftovers - as it does not exist in k1 - and matches the values in k1
</blockquote></details>

nm - reverted

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3598#-:-NZ_NVR54uluiVrAv1QG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
