### PR TITLE
Added option to print used resources for tests.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #5292
- #5291
- #5266 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5266)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 9 of 23 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5266)* status: 9 of 28 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 251 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5266#-NtAUFUWDfhndSd2Rr5A:-NtAUFUWDfhndSd2Rr5B:b-7dvr1b) ([raw file](https://github.com/starkware-libs/cairo/blob/f903e0f03b07079edfa78ed48f353eb8f6c20f54/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L251)):*
> ```XML
>         Infos: Iterator<Item = &'b Self::Info> + Clone,
>     {
>         let arm_demands = zip_eq(match_info.arms(), infos.clone())
> ```

can't you use .iter() here and below to avoid this clone?



_Code quote:_
```XML
clone()
```
___
*[`crates/cairo-lang-utils/src/unordered_hash_map.rs` line 296 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5266#-NtAWsrOD13xw-lb9j1h:-NtAWsrOD13xw-lb9j1i:b-235yel) ([raw file](https://github.com/starkware-libs/cairo/blob/f903e0f03b07079edfa78ed48f353eb8f6c20f54/crates/cairo-lang-utils/src/unordered_hash_map.rs#L296)):*
> ```XML
>             match self.0.entry(key.clone()) {
>                 Entry::Occupied(mut e) => {
>                     merge(e.get_mut(), value);
> ```

wouldn't it make more sense to let the function only output the value to use and not also insert it?
Also - I think it makes sense for the merge function to get the key as input for the decision.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5266)* status: 0 of 28 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 251 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5266#-NtAUFUWDfhndSd2Rr5A:-NtAaOhC5hoVYCDug-n9:bsp17wm) ([raw file](https://github.com/starkware-libs/cairo/blob/f903e0f03b07079edfa78ed48f353eb8f6c20f54/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L251)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

can't you use .iter() here and below to avoid this clone?
</blockquote></details>

it is a clone of the iterator - not of the iterators content.
___
*[`crates/cairo-lang-utils/src/unordered_hash_map.rs` line 296 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5266#-NtAWsrOD13xw-lb9j1h:-NtAamts4qZBussdWqPU:by5vp2f) ([raw file](https://github.com/starkware-libs/cairo/blob/f903e0f03b07079edfa78ed48f353eb8f6c20f54/crates/cairo-lang-utils/src/unordered_hash_map.rs#L296)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

wouldn't it make more sense to let the function only output the value to use and not also insert it?
Also - I think it makes sense for the merge function to get the key as input for the decision.
</blockquote></details>

1. it is an edit for the merge state - if we extract it, and add again it will be less efficient for no good reason.
2. Probably makes sense - but for now not really needed, fn is really easily adapted to support.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, 10 of 10 files at r3, 13 of 13 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5266)* status: all files reviewed, 14 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 106 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5266#-NtAdBje3uBsnI3_xTjA:-NtAdBje3uBsnI3_xTjB:b-mhmxbv) ([raw file](https://github.com/starkware-libs/cairo/blob/237ebb7dc26467f8b1c85d8739044b6707ba7cf4/crates/cairo-lang-runner/src/lib.rs#L106)):*
> ```XML
> /// The used resources in a run.
> #[derive(Debug, Eq, PartialEq, Clone, Default)]
> pub struct UsedResources {
> ```

IIUC the diff between UsedResources and ExecutionResource is the syscalls, that is, starknet. So I would call one this one StarknetExecutionResources, and specify starknet in the doc too.
___
*[`crates/cairo-lang-runner/src/lib.rs` line 114 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5266#-NtAdsau2v4kJFJveXfM:-NtAdsau2v4kJFJveXfN:bl7vrfr) ([raw file](https://github.com/starkware-libs/cairo/blob/237ebb7dc26467f8b1c85d8739044b6707ba7cf4/crates/cairo-lang-runner/src/lib.rs#L114)):*
> ```XML
> impl UsedResources {
>     /// Adds the resources of `other` to `self`.
>     pub fn add(&mut self, other: Self) {
> ```

Can you impl Add/AddAssign?
___
*[`crates/cairo-lang-runner/src/lib.rs` line 251 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5266#-NtAf_qn6o3LvKJRVZSb:-NtAf_qn6o3LvKJRVZSc:b-656h52) ([raw file](https://github.com/starkware-libs/cairo/blob/237ebb7dc26467f8b1c85d8739044b6707ba7cf4/crates/cairo-lang-runner/src/lib.rs#L251)):*
> ```XML
>             syscalls_used_resources: Default::default(),
>         };
>         let RunResult { gas_counter, memory, value, used_resources, profiling_info } = self
> ```

it's confusing that it's called used_resources when its type isn't UsedResources but ExecutionResources. (unless you rename to UsedResources and StarknetUsedResources/SyscallsUsedResources)



_Code quote:_
```XML
used_resources
```
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 102 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5266#-NtAjMr84Kay66J5seF_:-NtAjMr84Kay66J5seFa:bcun1j4) ([raw file](https://github.com/starkware-libs/cairo/blob/237ebb7dc26467f8b1c85d8739044b6707ba7cf4/crates/cairo-lang-runner/src/casm_run/mod.rs#L102)):*
> ```XML
>     /// The starknet state.
>     pub starknet_state: StarknetState,
>     /// Maintains the resources of the run.
> ```

the VM resources?
Worth making the difference clearer.



_Code quote:_
```XML
ins the resources of the run.
```
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 2092 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5266#-NtAh32S115LBEtp06pZ:-NtAh32T0Ggvu4bM7QlZ:b9w8mcp) ([raw file](https://github.com/starkware-libs/cairo/blob/237ebb7dc26467f8b1c85d8739044b6707ba7cf4/crates/cairo-lang-runner/src/casm_run/mod.rs#L2092)):*
> ```XML
> }
> 
> type RunFunctionRes = (Vec<Option<Felt252>>, usize, ExecutionResources);
> ```

This may be a good time to make it named.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 2155 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5266#-NtAih8P9uvMyTdgBnb5:-NtAih8Q7i10lQXkK6uq:b7i0mhi) ([raw file](https://github.com/starkware-libs/cairo/blob/237ebb7dc26467f8b1c85d8739044b6707ba7cf4/crates/cairo-lang-runner/src/casm_run/mod.rs#L2155)):*
> ```XML
>     let used_resources = runner
>         .get_execution_resources(vm)
>         .expect("Failed to get execution resources, but the run was successful.");
> ```

so we don't want to panic, right?
___
*[`crates/cairo-lang-runner/src/casm_run/test.rs` line 114 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5266#-NtAjlnHD_9dDThL6P7P:-NtAjlnHD_9dDThL6P7Q:btfd2fu) ([raw file](https://github.com/starkware-libs/cairo/blob/237ebb7dc26467f8b1c85d8739044b6707ba7cf4/crates/cairo-lang-runner/src/casm_run/test.rs#L114)):*
> ```XML
> fn test_runner(function: CasmContext, n_returns: usize, expected: &[i128]) {
>     let (hints_dict, string_to_hint) = build_hints_dict(function.instructions.iter());
>     let mut hint_processor = CairoHintProcessor {
> ```

Maybe add a `new` function from a string_to_hint?
___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 443 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5266#-NtB7xI1COdhy0KgtMij:-NtB7xI1COdhy0KgtMik:byn2p8v) ([raw file](https://github.com/starkware-libs/cairo/blob/237ebb7dc26467f8b1c85d8739044b6707ba7cf4/crates/cairo-lang-test-runner/src/lib.rs#L443)):*
> ```XML
>     };
>     let summary = wrapped_summary.as_mut().unwrap();
>     let (res_type, status_str, gas_usage, used_resources, profiling_info) = if let Some(x) = status
> ```

please rename



_Code quote:_
```XML
x
```
___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 468 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5266#-NtB9KewCJltPru5s35z:-NtB9KewCJltPru5s36-:by3d7ir) ([raw file](https://github.com/starkware-libs/cairo/blob/237ebb7dc26467f8b1c85d8739044b6707ba7cf4/crates/cairo-lang-test-runner/src/lib.rs#L468)):*
> ```XML
>     }
>     if let Some(used_resources) = used_resources {
>         let filtered = used_resources.execution_resources.filter_unused_builtins();
> ```

I can't find this method.



_Code quote:_
```XML
filter_unused_builtins
```
___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 469 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5266#-NtB8r1862_s7NC4Y2f4:-NtB8r1862_s7NC4Y2f5:b-hyp4ee) ([raw file](https://github.com/starkware-libs/cairo/blob/237ebb7dc26467f8b1c85d8739044b6707ba7cf4/crates/cairo-lang-test-runner/src/lib.rs#L469)):*
> ```XML
>     if let Some(used_resources) = used_resources {
>         let filtered = used_resources.execution_resources.filter_unused_builtins();
>         println!("    steps: {}", filtered.n_steps);
> ```

can you add an example of the output?
___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 470 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5266#-NtB9igmE2DO0uM7Lbqg:-NtB9igmE2DO0uM7Lbqh:brgnyvs) ([raw file](https://github.com/starkware-libs/cairo/blob/237ebb7dc26467f8b1c85d8739044b6707ba7cf4/crates/cairo-lang-test-runner/src/lib.rs#L470)):*
> ```XML
>         let filtered = used_resources.execution_resources.filter_unused_builtins();
>         println!("    steps: {}", filtered.n_steps);
>         println!("    memory holes: {}", filtered.n_memory_holes);
> ```

I can't find these members of the result struct. too.



_Code quote:_
```XML
n_memory_holes
```
___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 475 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5266#-NtB9xJF-hnWXcpmTdL8:-NtB9xJF-hnWXcpmTdL9:b-8zgg8a) ([raw file](https://github.com/starkware-libs/cairo/blob/237ebb7dc26467f8b1c85d8739044b6707ba7cf4/crates/cairo-lang-test-runner/src/lib.rs#L475)):*
> ```XML
>                 println!(
>                     "    {name}: ({})",
>                     m.into_iter().sorted().map(|(k, v)| format!("{k:?}: {v}")).join(", ")
> ```

Is this `:?` needed?



_Code quote:_
```XML
:?
```

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5266)* status: all files reviewed, 15 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-utils/src/unordered_hash_map.rs` line 296 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5266#-NtAWsrOD13xw-lb9j1h:-NtBAJhe2LwwL05koYCE:b-hvry1n) ([raw file](https://github.com/starkware-libs/cairo/blob/f903e0f03b07079edfa78ed48f353eb8f6c20f54/crates/cairo-lang-utils/src/unordered_hash_map.rs#L296)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

1. it is an edit for the merge state - if we extract it, and add again it will be less efficient for no good reason.
2. Probably makes sense - but for now not really needed, fn is really easily adapted to support.
</blockquote></details>

1. I meant that the `merge` function here chooses the value, and the editing is done here in the case of Occupied.
___
*[`crates/cairo-lang-utils/src/unordered_hash_map.rs` line 286 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5266#-NtBA_E5B9ERHDPHmFve:-NtBA_E5B9ERHDPHmFvf:bciq2f6) ([raw file](https://github.com/starkware-libs/cairo/blob/237ebb7dc26467f8b1c85d8739044b6707ba7cf4/crates/cairo-lang-utils/src/unordered_hash_map.rs#L286)):*
> ```XML
>     /// Merges the map with another map. If a key is present in both maps, the given merge function
>     /// is used to combine the values.
>     pub fn merge<M>(&mut self, other: &Self, merge: M)
> ```

Suggest to rename BTW, it has the same name as the function itself.



_Code quote:_
```XML
merge: M
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5266)* status: 22 of 28 files reviewed, 13 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 106 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5266#-NtAdBje3uBsnI3_xTjA:-NtR4edt5PM2HKBRXTw_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/237ebb7dc26467f8b1c85d8739044b6707ba7cf4/crates/cairo-lang-runner/src/lib.rs#L106)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

IIUC the diff between UsedResources and ExecutionResource is the syscalls, that is, starknet. So I would call one this one StarknetExecutionResources, and specify starknet in the doc too.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runner/src/lib.rs` line 114 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5266#-NtAdsau2v4kJFJveXfM:-NtR4j-2CAMRArF7dEk-:b-9bs0rn) ([raw file](https://github.com/starkware-libs/cairo/blob/237ebb7dc26467f8b1c85d8739044b6707ba7cf4/crates/cairo-lang-runner/src/lib.rs#L114)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Can you impl Add/AddAssign?
</blockquote></details>

Done - but just add_assign as only it was needed.
___
*[`crates/cairo-lang-runner/src/lib.rs` line 251 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5266#-NtAf_qn6o3LvKJRVZSb:-NtR4tC-7gRPDRxp9UA2:b-evj6jk) ([raw file](https://github.com/starkware-libs/cairo/blob/237ebb7dc26467f8b1c85d8739044b6707ba7cf4/crates/cairo-lang-runner/src/lib.rs#L251)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

it's confusing that it's called used_resources when its type isn't UsedResources but ExecutionResources. (unless you rename to UsedResources and StarknetUsedResources/SyscallsUsedResources)
</blockquote></details>

the type can hold general execution resources - but the meaning of it in this case is the actual used resources.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 102 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5266#-NtAjMr84Kay66J5seF_:-NtR5kHf9817CN8mcPv8:b-cvr2a0) ([raw file](https://github.com/starkware-libs/cairo/blob/237ebb7dc26467f8b1c85d8739044b6707ba7cf4/crates/cairo-lang-runner/src/casm_run/mod.rs#L102)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

the VM resources?
Worth making the difference clearer.
</blockquote></details>

I don't know what the first one means - it is unrelated to this PR.
it seems to count steps across multiple runners. 
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 2155 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5266#-NtAih8P9uvMyTdgBnb5:-NtQ__ly0QviCzXsGIfH:b48rcr7) ([raw file](https://github.com/starkware-libs/cairo/blob/237ebb7dc26467f8b1c85d8739044b6707ba7cf4/crates/cairo-lang-runner/src/casm_run/mod.rs#L2155)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

so we don't want to panic, right?
</blockquote></details>

this cannot actually happen - as all sierra runs should complete.
___
*[`crates/cairo-lang-runner/src/casm_run/test.rs` line 114 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5266#-NtAjlnHD_9dDThL6P7P:-NtR8EiF1G1viVVuUcSV:b-oztmy3) ([raw file](https://github.com/starkware-libs/cairo/blob/237ebb7dc26467f8b1c85d8739044b6707ba7cf4/crates/cairo-lang-runner/src/casm_run/test.rs#L114)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Maybe add a `new` function from a string_to_hint?
</blockquote></details>

maybe - but unrelated to the PR.
___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 443 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5266#-NtB7xI1COdhy0KgtMij:-NtR9ECs93A0T4pQPuB1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/237ebb7dc26467f8b1c85d8739044b6707ba7cf4/crates/cairo-lang-test-runner/src/lib.rs#L443)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

please rename
</blockquote></details>

Done.
___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 468 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5266#-NtB9KewCJltPru5s35z:-NtQ_kZC4z6gn2kQU1-H:bqtj53d) ([raw file](https://github.com/starkware-libs/cairo/blob/237ebb7dc26467f8b1c85d8739044b6707ba7cf4/crates/cairo-lang-test-runner/src/lib.rs#L468)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I can't find this method.
</blockquote></details>

this is in the cairo-vm repo.
___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 469 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5266#-NtB8r1862_s7NC4Y2f4:-NtR9b7_-EBTYUGf9RIz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/237ebb7dc26467f8b1c85d8739044b6707ba7cf4/crates/cairo-lang-test-runner/src/lib.rs#L469)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

can you add an example of the output?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 470 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5266#-NtB9igmE2DO0uM7Lbqg:-NtQ_pnw1tzTjRHZrhmx:bqtj53d) ([raw file](https://github.com/starkware-libs/cairo/blob/237ebb7dc26467f8b1c85d8739044b6707ba7cf4/crates/cairo-lang-test-runner/src/lib.rs#L470)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I can't find these members of the result struct. too.
</blockquote></details>

this is in the cairo-vm repo.
___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 475 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5266#-NtB9xJF-hnWXcpmTdL8:-NtQ_vNZ4juGdaEbv5Mw:blcs5rd) ([raw file](https://github.com/starkware-libs/cairo/blob/237ebb7dc26467f8b1c85d8739044b6707ba7cf4/crates/cairo-lang-test-runner/src/lib.rs#L475)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Is this `:?` needed?
</blockquote></details>

used longer form instead.
(basically we print the same way as foundry does)
___
*[`crates/cairo-lang-utils/src/unordered_hash_map.rs` line 296 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5266#-NtAWsrOD13xw-lb9j1h:-NtRBWIm8Z32Yi1kL3tq:bgf8bxn) ([raw file](https://github.com/starkware-libs/cairo/blob/f903e0f03b07079edfa78ed48f353eb8f6c20f54/crates/cairo-lang-utils/src/unordered_hash_map.rs#L296)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

1. I meant that the `merge` function here chooses the value, and the editing is done here in the case of Occupied.
</blockquote></details>

1. it is already inserted - so i need to edit it - or to do awful lifetime stuff.
https://reviewable.io/reviews/starkware-libs/cairo/5291
___
*[`crates/cairo-lang-utils/src/unordered_hash_map.rs` line 286 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5266#-NtBA_E5B9ERHDPHmFve:-NtRDtfp4qDuqcI7mPyO:b-6dxy27) ([raw file](https://github.com/starkware-libs/cairo/blob/237ebb7dc26467f8b1c85d8739044b6707ba7cf4/crates/cairo-lang-utils/src/unordered_hash_map.rs#L286)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Suggest to rename BTW, it has the same name as the function itself.
</blockquote></details>

https://reviewable.io/reviews/starkware-libs/cairo/5291

**Review by yuvalsw — APPROVED** [review]
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5266)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 474 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5266#-NtUwEup49_AlTCKPM4i:-NtUwEuq5XRclOX6P8EM:bhqe0dt) ([raw file](https://github.com/starkware-libs/cairo/blob/e0a2a0b30a1e0f52d6923c4c75066c1880582243/crates/cairo-lang-test-runner/src/lib.rs#L474)):*
> ```XML
>         //     steps: 42
>         //     memory holes: 20
>         //     builtins: ("range_check_builtin": 3)
> ```

IIUC with another builtin it would be:
builtins: ("range_check_builtin": 3, "another_builtin": 1)

Are the parentheses and the quotes needed then?



_Suggestion:_
```XML
 builtins: range_check_builtin: 3
```
___
*[`crates/cairo-lang-utils/src/unordered_hash_map.rs` line 296 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5266#-NtAWsrOD13xw-lb9j1h:-NtV00De-MFHxX_mELOf:b4cdl12) ([raw file](https://github.com/starkware-libs/cairo/blob/f903e0f03b07079edfa78ed48f353eb8f6c20f54/crates/cairo-lang-utils/src/unordered_hash_map.rs#L296)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

1. it is already inserted - so i need to edit it - or to do awful lifetime stuff.
https://reviewable.io/reviews/starkware-libs/cairo/5291
</blockquote></details>

Replied there.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5266#-:-NtV0KL04anIfXSwFuIm:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5266)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 474 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5266#-NtUwEup49_AlTCKPM4i:-NtV0rCN2BfD_wOhQ0RT:bnvh4ll) ([raw file](https://github.com/starkware-libs/cairo/blob/e0a2a0b30a1e0f52d6923c4c75066c1880582243/crates/cairo-lang-test-runner/src/lib.rs#L474)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

IIUC with another builtin it would be:
builtins: ("range_check_builtin": 3, "another_builtin": 1)

Are the parentheses and the quotes needed then?
</blockquote></details>

took the option people are happy with in foundry.
these encapsulate the cases where more than one is used quite comfortably.

**Review by yuvalsw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5266)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by yuvalsw — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5266)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
