### PR TITLE
Added felt-serde for sierra.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:9ebfff5b

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1429)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/starknet/src/felt_serde.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1429#-NJskjJoBdatJwRoYFGw:-NJskjJoBdatJwRoYFGx:b-rv7wzd) ([raw file](https://github.com/starkware-libs/cairo/blob/23c493930fb973b84ba814e71c090413c32a9d31/crates/starknet/src/felt_serde.rs#L102)):*
> ```XML
>     fn serialize(&self, output: &mut Vec<BigIntAsHex>) -> Result<(), FeltSerdeError> {
>         output.push(BigIntAsHex {
>             value: self.to_biguint().ok_or(FeltSerdeError::BigIntOutOfBounds)?,
> ```

This only happens for negative numbers, right?

Do we want to enforce value < prime somewhere?



_Code quote:_
```XML
BigIntOutOfBounds
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1429)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/starknet/src/felt_serde.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1429#-NJslG04EX-f1CfOBQ2c:-NJslG04EX-f1CfOBQ2d:boyw9kh) ([raw file](https://github.com/starkware-libs/cairo/blob/23c493930fb973b84ba814e71c090413c32a9d31/crates/starknet/src/felt_serde.rs#L137)):*
> ```XML
>             ) -> Result<(Self, &[BigIntAsHex]), FeltSerdeError> {
>                 let (id, input) = u64::deserialize(input)?;
>                 Ok((Self::new(id), input))
> ```

why are you returning the input here?

shouldn't you do something like

input[1:]
?



_Code quote:_
```XML
Ok((Self::new(id), input))
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1429)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/starknet/src/felt_serde.rs` line 227 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1429#-NJsnbAq91DCTI5Cf6Of:-NJsnbAq91DCTI5Cf6Og:b-nhyr1u) ([raw file](https://github.com/starkware-libs/cairo/blob/23c493930fb973b84ba814e71c090413c32a9d31/crates/starknet/src/felt_serde.rs#L227)):*
> ```XML
> struct_serde! {
>     Function {
>         id: FunctionId,
> ```

I don't think we should have this in the serialization, I think this should be the index in the array.



_Code quote:_
```XML
id: FunctionId,
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1429)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/starknet/src/felt_serde.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1429#-NJskjJoBdatJwRoYFGw:-NJsurj63PvPXKk9c5MP:b-x3melj) ([raw file](https://github.com/starkware-libs/cairo/blob/23c493930fb973b84ba814e71c090413c32a9d31/crates/starknet/src/felt_serde.rs#L102)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

This only happens for negative numbers, right?

Do we want to enforce value < prime somewhere?

</blockquote></details>

this would mean that we need to receive the prime everywhere - it is probably ok that we validate it in the writer part.
___
*[`crates/starknet/src/felt_serde.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1429#-NJslG04EX-f1CfOBQ2c:-NJsv2-ZArCgApO-gGk_:b-iqe2be) ([raw file](https://github.com/starkware-libs/cairo/blob/23c493930fb973b84ba814e71c090413c32a9d31/crates/starknet/src/felt_serde.rs#L137)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why are you returning the input here?

shouldn't you do something like

input[1:]
?
</blockquote></details>

note the previous line - if you have a good suggestion for a convension like calling it `rest` or `tail` that won't be confusing in the cases where we work recursively - will do.
___
*[`crates/starknet/src/felt_serde.rs` line 227 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1429#-NJsnbAq91DCTI5Cf6Of:-NJsvKR6830Z3Lp2vb63:b-wv95ud) ([raw file](https://github.com/starkware-libs/cairo/blob/23c493930fb973b84ba814e71c090413c32a9d31/crates/starknet/src/felt_serde.rs#L227)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't think we should have this in the serialization, I think this should be the index in the array.
</blockquote></details>

currently - i want it to work - later - we may optimise further.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1429#-:-NJsy49fBnp4vygTwuLs:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

___
*[`crates/starknet/src/felt_serde.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1429#-NJslG04EX-f1CfOBQ2c:-NJsxyYVBNf1hxFTtxzC:b-aek90w) ([raw file](https://github.com/starkware-libs/cairo/blob/23c493930fb973b84ba814e71c090413c32a9d31/crates/starknet/src/felt_serde.rs#L137)):*
>  have a good suggestion for a convension like 
ok.

**Pull request merged**
