### PR TITLE
Added support for removing original items when plugins act on them

### PR DESCRIPTION
**Pull request by yuvalsw**
Used it in Starknet plugin to remove the original contract item

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1520)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1520)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/defs/src/db.rs` line 267 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1520#-NKJNIslC5bTQVPwAb7N:-NKJNIslC5bTQVPwAb7O:b-mg84g7) ([raw file](https://github.com/starkware-libs/cairo/blob/9bf518805aa43fb148c1d8b6ccf51a1f36a6f9b9/crates/defs/src/db.rs#L267)):*
> ```XML
>                     res.plugin_diagnostics.push((module_file_id, plugin_diag));
>                 }
>                 if result.remove_original_item {
> ```

isn't it weired to ask to file to be removed, not generate any code and then continue to the next plugin?



_Code quote:_
```XML
                if result.remove_original_item {
                    remove_original_item = true;
                }
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1520)* status: 1 of 14 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/starknet/src/contract_test.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1520#-NKJOATz-yOY5LE6Kf87:-NKJOATz-yOY5LE6Kf88:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/9bf518805aa43fb148c1d8b6ccf51a1f36a6f9b9/crates/starknet/src/contract_test.rs#L19)):*
> ```XML
> 
>             #[generated_contract]
>             mod __generated__ERC20 {
> ```





_Suggestion:_
```XML
ERC20
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1520)* status: 5 of 14 files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/defs/src/db.rs` line 289 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1520#-NKJQGwm75YYEysNYXO6:-NKJQGwm75YYEysNYXO7:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9bf518805aa43fb148c1d8b6ccf51a1f36a6f9b9/crates/defs/src/db.rs#L289)):*
> ```XML
>                 // operate on it, they should operate on the result (the rest of the attributes
>                 // should be copied to the new generated code).
>                 break;
> ```





_Suggestion:_
```XML
                if let Some(generated) = result.code {      
                    let new_file = db.intern_file(FileLongId::Virtual(VirtualFile {
                        parent: Some(module_file),
                        name: generated.name,
                        origin: module_file_id,
                    }));
                    module_queue.push_back((new_file, db.file_syntax(new_file)?.items(syntax_db)));
                    // New code was generated for this item. If there are more plugins that should
                    // operate on it, they should operate on the result (the rest of the attributes
                    // should be copied to the new generated code).
                    break;
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1520)* status: 5 of 14 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/defs/src/db.rs` line 267 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1520#-NKJNIslC5bTQVPwAb7N:-NKN0iNDCT-Gb4Y18E2a:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9bf518805aa43fb148c1d8b6ccf51a1f36a6f9b9/crates/defs/src/db.rs#L267)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

isn't it weired to ask to file to be removed, not generate any code and then continue to the next plugin?
</blockquote></details>

Done.
___
*[`crates/defs/src/db.rs` line 289 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1520#-NKJQGwm75YYEysNYXO6:-NKMyry35j8O8TTTvZFT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9bf518805aa43fb148c1d8b6ccf51a1f36a6f9b9/crates/defs/src/db.rs#L289)):*
> ```XML
>                 // operate on it, they should operate on the result (the rest of the attributes
>                 // should be copied to the new generated code).
>                 break;
> ```

Done.
___
*[`crates/starknet/src/contract_test.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1520#-NKJOATz-yOY5LE6Kf87:-NKMz4fr3rZ2afBUVdng:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9bf518805aa43fb148c1d8b6ccf51a1f36a6f9b9/crates/starknet/src/contract_test.rs#L19)):*
> ```XML
> 
>             #[generated_contract]
>             mod __generated__ERC20 {
> ```

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 32 of 32 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1520#-:-NKNXG-uB6mMIkMFbpzu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 1 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1520)* status: 25 of 33 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 8 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1520)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
