### PR TITLE
Better diagnostics for enum arm matches failure.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #2332
- #2324 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2324)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2324)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2324#-NPRKEfo7R2DzrwEp-Sd:-NPRKEfpAjV0uTFxJGVI:b-kcubp1) (no related file):*
Can you add a test that shows the new diagnostics?

___

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2324)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2324#-NPRKEfo7R2DzrwEp-Sd:-NPRpaeB2SvGLYZ0usUh:b-896fix) (no related file):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Can you add a test that shows the new diagnostics?
</blockquote></details>

Done.

___

**Review by orizi — COMMENTED** [review]
> Reviewed 5 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2324)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2324#-:-NPStX2zANIahe1RRr1d:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Pull request merged**
