### PR TITLE
Don't replace module contract

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3045)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3042** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3042" target="_blank">Graphite</a> 
    * **PR #3044** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3044" target="_blank">Graphite</a> 
      * **PR #3045** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3045" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/3045?utm_source=stack-comment).

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 12 of 20 files at r1, 10 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3045)* status: 19 of 31 files reviewed, 4 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 30 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3045#-NUoqxzd7yuiCHMgkP6m:-NUoqxzd7yuiCHMgkP6n:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/e91777ae41ffdec1c458780dba77ec43b1788b44/crates/cairo-lang-starknet/src/plugin/contract.rs#L30)):*
> ```XML
> use crate::plugin::aux_data::StarkNetContractAuxData;
> 
> pub fn handle_module(db: &dyn SyntaxGroup, module_ast: ast::ItemModule) -> PluginResult {
> ```

doc
___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 46 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3045#-NUord9X4hLoXWiA-d-X:-NUord9X4hLoXWiA-d-Y:b-34f5z5) ([raw file](https://github.com/starkware-libs/cairo/blob/e91777ae41ffdec1c458780dba77ec43b1788b44/crates/cairo-lang-starknet/src/plugin/contract.rs#L46)):*
> ```XML
>     let Some(storage_struct_ast) = body.items(db).elements(db).into_iter().find(|item| {
>         let ast::Item::Struct(struct_ast) = item else { return false; };
>         struct_ast.name(db).text(db) == "Storage"
> ```

?
`matches!(item,  ast::Item::Struct(struct_ast) if struct_ast.name(db).text(db) == "Storage")`
___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3045#-NUotFS53XSrHLcZFfr5:-NUotFS53XSrHLcZFfr6:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/e91777ae41ffdec1c458780dba77ec43b1788b44/crates/cairo-lang-starknet/src/plugin/events.rs#L21)):*
> ```XML
> use crate::contract::starknet_keccak;
> 
> pub fn handle_function(db: &dyn SyntaxGroup, function_ast: ast::FunctionWithBody) -> PluginResult {
> ```

doc
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/diagnostics` line 342 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3045#-NUosYQJCavGKuBgncUh:-NUosYQJCavGKuBgncUi:blvpt0x) ([raw file](https://github.com/starkware-libs/cairo/blob/e91777ae41ffdec1c458780dba77ec43b1788b44/crates/cairo-lang-starknet/src/plugin/plugin_test_data/diagnostics#L342)):*
> ```
> }
> 
> //! > generated_cairo_code
> ```

where has the generated code gone?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3045)* status: 17 of 55 files reviewed, 4 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 46 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3045#-NUord9X4hLoXWiA-d-X:-NUq_wKZ7WOXJbL06reP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e91777ae41ffdec1c458780dba77ec43b1788b44/crates/cairo-lang-starknet/src/plugin/contract.rs#L46)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
`matches!(item,  ast::Item::Struct(struct_ast) if struct_ast.name(db).text(db) == "Storage")`
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3045#-NUotFS53XSrHLcZFfr5:-NUqa8YEEeqo5AymjHYv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e91777ae41ffdec1c458780dba77ec43b1788b44/crates/cairo-lang-starknet/src/plugin/events.rs#L21)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 20 files at r1, 2 of 18 files at r2, 32 of 33 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3045)* status: 54 of 55 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3045#-NUv0BKx-wd0usDGbyQE:-NUv0BKx-wd0usDGbyQF:bpj18rz) (no related file):*
why are there casm changes here?

___
___
*[`crates/cairo-lang-starknet/test_data/hello_starknet.cairo` line 11 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3045#-NUv-exo1a5OcJ6uhRBg:-NUv-exo1a5OcJ6uhRBh:b-fiw4x9) ([raw file](https://github.com/starkware-libs/cairo/blob/250363694d37422041318d7063d981978891b396/crates/cairo-lang-starknet/test_data/hello_starknet.cairo#L11)):*
> ```Cairo
>     #[external]
>     fn increase_balance(ref self: Storage, amount: felt252) {
>         // TODO(spapini):  Remove explicit snapshot when snapshot member borrowing is fixed.
> ```

which snapshot?



_Code quote:_
```Cairo
 // TODO(spapini):  Remove explicit snapshot when snapshot member borrowing is fixed.
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3045)* status: 15 of 55 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-starknet/test_data/hello_starknet.cairo` line 11 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3045#-NUv-exo1a5OcJ6uhRBg:-NVxSxio6v_6BHfN4jU4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/250363694d37422041318d7063d981978891b396/crates/cairo-lang-starknet/test_data/hello_starknet.cairo#L11)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

which snapshot?
</blockquote></details>

Done.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3045)* status: 15 of 55 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3045#-NUv0BKx-wd0usDGbyQE:-NVxUyjRDNHs8XWo7vRo:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why are there casm changes here?
</blockquote></details>

Done.

___

**Review by orizi — COMMENTED** [review]
> Reviewed 40 of 40 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3045)* status: 54 of 55 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3045#-:-NVxYRJV4PULKRdxKefz:bnfp4nl)* status: 54 of 55 files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3045)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
