### PR TITLE
Refactor lowering objects

### PR DESCRIPTION
**Pull request by spapinistarkware**
commit-id:37371f78

---

**Stack**:
- #1614
- #1613 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1613)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1613)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lowering/src/objects.rs` line 55 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1613#-NKn-9As2hTNt7bZVF8P:-NKn-9As2hTNt7bZVF8Q:bpaag3l) ([raw file](https://github.com/starkware-libs/cairo/blob/1ff50257764c7fca984f2a6b87910c67f04cd22b/crates/cairo-lowering/src/objects.rs#L55)):*
> ```XML
> /// A block of statements. Each block gets inputs and outputs, and is composed of
> /// a linear sequence of statements.
> ///
> ```

update docs to reflect the difference



_Code quote:_
```XML
/// A block of statements. Each block gets inputs and outputs, and is composed of
/// a linear sequence of statements.
///
/// A block may end with a `return`, which exits the current function.
///
/// A block contains the list of variables to be dropped at its end. Other than these variables and
/// the output variables, it is guaranteed that no other variable is alive.
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1613)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1613)* status: 11 of 13 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lowering/src/objects.rs` line 55 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1613#-NKn-9As2hTNt7bZVF8P:-NKrIRbt2cnVDt4m1lpE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1ff50257764c7fca984f2a6b87910c67f04cd22b/crates/cairo-lowering/src/objects.rs#L55)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

update docs to reflect the difference
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1613)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
