### PR TITLE
added if-let expression in semantic

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4945)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4945)* status: 6 of 11 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-syntax-codegen/src/cairo_spec.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4945#-NpHJP7J8kw8oYfGUn-v:-NpHJP7J8kw8oYfGUn-w:b-wcdggu) ([raw file](https://github.com/starkware-libs/cairo/blob/fad0f4442e1e9477f08384b42251534f3fd06710/crates/cairo-lang-syntax-codegen/src/cairo_spec.rs#L33)):*
> ```XML
>         .node("Match")
>         .node("If")
>         .node("IfLet")
> ```

isnt this part of the syntax pr?

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4945)* status: 7 of 12 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/objects.rs` line 356 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4945#-NpKG8rd6Mx4Q_NI45XJ:-NpKMHMoC-RrGSjjiIKj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fad0f4442e1e9477f08384b42251534f3fd06710/crates/cairo-lang-semantic/src/expr/objects.rs#L356)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Shouldn't it hold the rhs expr?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-syntax-codegen/src/cairo_spec.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4945#-NpHJP7J8kw8oYfGUn-v:-NpKKtrT88Nso1YKYvUK:b-n9tkhd) ([raw file](https://github.com/starkware-libs/cairo/blob/fad0f4442e1e9477f08384b42251534f3fd06710/crates/cairo-lang-syntax-codegen/src/cairo_spec.rs#L33)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

isnt this part of the syntax pr?
</blockquote></details>

changed

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4945)* status: 7 of 12 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 951 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4945#-NpKO7dd9TAurrZjX8ru:-NpKO7dd9TAurrZjX8rv:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/78a6b552fcce9e731aed57cf80636aa5597ec8b8/crates/cairo-lang-semantic/src/expr/compute.rs#L951)):*
> ```XML
>         (patterns, arm_expr)
>     })
> }
> ```

doc
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 956 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4945#-NpKOA5n0WGd7FC6lcg0:-NpKOA5n0WGd7FC6lcg1:b-gvafoc) ([raw file](https://github.com/starkware-libs/cairo/blob/78a6b552fcce9e731aed57cf80636aa5597ec8b8/crates/cairo-lang-semantic/src/expr/compute.rs#L956)):*
> ```XML
>     syntax: &ast::ExprMatch,
> ) -> Maybe<Expr> {
>     // TODO(yuval): verify exhaustiveness.
> ```

don't we already?
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1043 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4945#-NpKOCLr6EIsisZqmSIe:-NpKOCLr6EIsisZqmSIf:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/78a6b552fcce9e731aed57cf80636aa5597ec8b8/crates/cairo-lang-semantic/src/expr/compute.rs#L1043)):*
> ```XML
>     }))
> }
> fn compute_expr_if_let_semantic(
> ```

doc

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4945)* status: 7 of 12 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1096 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4945#-NpK_LdU-PHeOQekj_4t:-NpK_LdV176mp5Vla-HU:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/776d0dffc612a3dab330a09f2f3c542dec0ebe76/crates/cairo-lang-semantic/src/expr/compute.rs#L1096)):*
> ```XML
>     }))
> }
> /// Computes the semantic model of an expression of type [ast::ExprLoop].
> ```





_Suggestion:_
```XML
}

/// Computes the semantic model of an expression of type [ast::ExprLoop].
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r1, 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4945)* status: 9 of 12 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/if` line 80 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4945#-NpKcPKJ7R8G6q6beQwf:-NpKcPKK3qRJnSONWess:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8432d27cb3973d16130742831feca475706bf456/crates/cairo-lang-semantic/src/expr/test_data/if#L80)):*
> ```
>         return false;
>     }
> }
> ```





_Suggestion:_
```
    let x = Option::Some(7_u64);
    if let MyEnum::A(y) = x {
        return y == 9;
    } else {
        return false;
    }
}
```
___
*[`crates/cairo-lang-semantic/src/expr/test_data/if` line 117 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4945#-NpKcS0SDFpfl9H00BCQ:-NpKcS0SDFpfl9H00BCR:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8432d27cb3973d16130742831feca475706bf456/crates/cairo-lang-semantic/src/expr/test_data/if#L117)):*
> ```
>     }
>     
> }
> ```





_Suggestion:_
```
fn foo() -> bool {
    let x = Option::Some(7_u64);
    if let Some(y) = x || true {
        return y == 9;
    } else {
        return false;
    }
}
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4945)* status: 9 of 12 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 951 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4945#-NpKO7dd9TAurrZjX8ru:-NpKoRhx-spZL9EXBDMs:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/78a6b552fcce9e731aed57cf80636aa5597ec8b8/crates/cairo-lang-semantic/src/expr/compute.rs#L951)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 956 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4945#-NpKOA5n0WGd7FC6lcg0:-NpKnglhEPhlrWT71r4s:b-99kpqh) ([raw file](https://github.com/starkware-libs/cairo/blob/78a6b552fcce9e731aed57cf80636aa5597ec8b8/crates/cairo-lang-semantic/src/expr/compute.rs#L956)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

don't we already?
</blockquote></details>

in lowering
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1043 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4945#-NpKOCLr6EIsisZqmSIe:-NpKoSW-CLcQP9x_TNSG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/78a6b552fcce9e731aed57cf80636aa5597ec8b8/crates/cairo-lang-semantic/src/expr/compute.rs#L1043)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1096 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4945#-NpK_LdU-PHeOQekj_4t:-NpKoStk3jc07oL6cQKz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/776d0dffc612a3dab330a09f2f3c542dec0ebe76/crates/cairo-lang-semantic/src/expr/compute.rs#L1096)):*
> ```XML
>     }))
> }
> /// Computes the semantic model of an expression of type [ast::ExprLoop].
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/if` line 80 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4945#-NpKcPKJ7R8G6q6beQwf:-NpKouYcBzIgm1nLOQEx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8432d27cb3973d16130742831feca475706bf456/crates/cairo-lang-semantic/src/expr/test_data/if#L80)):*
> ```
>         return false;
>     }
> }
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/if` line 117 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4945#-NpKcS0SDFpfl9H00BCQ:-NpKovBD05SlahVIAPIK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8432d27cb3973d16130742831feca475706bf456/crates/cairo-lang-semantic/src/expr/test_data/if#L117)):*
> ```
>     }
>     
> }
> ```

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4945)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4945)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4945)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 5 of 11 files at r1, 3 of 5 files at r2, 1 of 2 files at r6, 2 of 4 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4945)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 882 at r9](https://reviewable.io/reviews/starkware-libs/cairo/4945#-NpUQ1AdAN-Xn218SwN0:-NpUQ1AdAN-Xn218SwN1:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/cb6ab1557d4bb73ffd440272f35977aa333c1e63/crates/cairo-lang-semantic/src/expr/compute.rs#L882)):*
> ```XML
> }
> 
> /// computes the semnatic of a match arm pattern and the block expression.
> ```





_Suggestion:_
```XML
/// Computes the semnatic model of a match arm pattern and 
```
___
*[`crates/cairo-lang-semantic/src/expr/test.rs` line 69 at r9](https://reviewable.io/reviews/starkware-libs/cairo/4945#-NpURwis00SRM7OKjzL3:-NpURwit4DjrZfy7REYj:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/cb6ab1557d4bb73ffd440272f35977aa333c1e63/crates/cairo-lang-semantic/src/expr/test.rs#L69)):*
> ```XML
>         literals: "literals",
>         match_: "match",
>         if_:"if",
> ```





_Suggestion:_
```XML
if_: "if",
```

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4945)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 8 of 17 files at r10, 13 of 13 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4945#-:-NpV3wprCcxd-yRqVohY:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4945)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 882 at r9](https://reviewable.io/reviews/starkware-libs/cairo/4945#-NpUQ1AdAN-Xn218SwN0:-NpV1zzD06mAuIFm-gLZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cb6ab1557d4bb73ffd440272f35977aa333c1e63/crates/cairo-lang-semantic/src/expr/compute.rs#L882)):*
> ```XML
> }
> 
> /// computes the semnatic of a match arm pattern and the block expression.
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/test.rs` line 69 at r9](https://reviewable.io/reviews/starkware-libs/cairo/4945#-NpURwis00SRM7OKjzL3:-NpV5j45Ab3Wbs1H78Sx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cb6ab1557d4bb73ffd440272f35977aa333c1e63/crates/cairo-lang-semantic/src/expr/test.rs#L69)):*
> ```XML
>         literals: "literals",
>         match_: "match",
>         if_:"if",
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4945)* status: 20 of 23 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/objects.rs` line 359 at r13](https://reviewable.io/reviews/starkware-libs/cairo/4945#-NpYjFctB_R27iwnS_Rd:-NpYjFctB_R27iwnS_Re:bls5lqy) ([raw file](https://github.com/starkware-libs/cairo/blob/bf5f78948243bcb7a4cabb94809c97c38cfc170d/crates/cairo-lang-semantic/src/expr/objects.rs#L359)):*
> ```XML
>     pub arms: Vec<MatchArm>,
>     pub ty: semantic::TypeId,
>     #[hide_field_debug_with_db]
> ```

discussed f2f.



_Code quote:_
```XML
    pub expr: ExprId,
    pub arms: Vec<MatchArm>,
    pub ty: semantic::TypeId,
    #[hide_field_debug_with_db]
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4945)* status: 19 of 23 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/objects.rs` line 359 at r13](https://reviewable.io/reviews/starkware-libs/cairo/4945#-NpYjFctB_R27iwnS_Rd:-NpYpOqA1DZoKNuixg5N:bvth56w) ([raw file](https://github.com/starkware-libs/cairo/blob/bf5f78948243bcb7a4cabb94809c97c38cfc170d/crates/cairo-lang-semantic/src/expr/objects.rs#L359)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

discussed f2f.
</blockquote></details>

reverted

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4945)* status: 19 of 23 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/objects.rs` line 129 at r14](https://reviewable.io/reviews/starkware-libs/cairo/4945#-NpYtSqxAwqoEab60aaR:-NpYtSqxAwqoEab60aaS:bb1m0vj) ([raw file](https://github.com/starkware-libs/cairo/blob/ca5f1142b61c2fea45dd536175e9dbf571e9b916/crates/cairo-lang-semantic/src/expr/objects.rs#L129)):*
> ```XML
>     Match(ExprMatch),
>     If(ExprIf),
>     IfLet(ExprIfLet),
> ```

as discussed f2f - move IfLet to be a part of the condition if possible.



_Code quote:_
```XML
    IfLet(ExprIfLet),
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4945#-:-NpZ8D2s85Tbi7FdfSHo:bnfp4nl)* status: 21 of 23 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 4 files at r15.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4945)* status: 22 of 23 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 8 of 13 files at r11, 1 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4945)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 17 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4945)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4945)* status: 21 of 24 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/lower_if.rs` line 75 at r16](https://reviewable.io/reviews/starkware-libs/cairo/4945#-NpZD1_xBc3GNKvB13oV:-NpZD1_y72dUJ4oMAy0r:byoip1r) ([raw file](https://github.com/starkware-libs/cairo/blob/f2e9fcf240d5bab585da6eb61b498c75b8be5ad0/crates/cairo-lang-lowering/src/lower/lower_if.rs#L75)):*
> ```XML
>             ));
>         }
>     };
> ```

and everywhere else.



_Suggestion:_
```XML
    if let semantic::Condition::BoolExpr(expr_condition) = expr.condition else {
        return Err(LoweringFlowError::Failed(
            ctx.diagnostics.report(expr.stable_ptr.untyped(), Unsupported),
        ));
    };
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4945)* status: 21 of 24 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/lower_if.rs` line 75 at r16](https://reviewable.io/reviews/starkware-libs/cairo/4945#-NpZD1_xBc3GNKvB13oV:-NpnoyrM9FEBlORe7Mxa:b-otsdpp) ([raw file](https://github.com/starkware-libs/cairo/blob/f2e9fcf240d5bab585da6eb61b498c75b8be5ad0/crates/cairo-lang-lowering/src/lower/lower_if.rs#L75)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

and everywhere else.
</blockquote></details>

added expr function for Condition struct

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r17.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4945)* status: 21 of 24 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/lower_if.rs` line 68 at r17](https://reviewable.io/reviews/starkware-libs/cairo/4945#-NpntydfBDkbtbFCq77p:-NpntydfBDkbtbFCq77q:b30gbti) ([raw file](https://github.com/starkware-libs/cairo/blob/6b192c200cea1a18be3e8402eab60ea268b697d5/crates/cairo-lang-lowering/src/lower/lower_if.rs#L68)):*
> ```XML
>     expr: &semantic::ExprIf,
> ) -> LoweringResult<LoweredExpr> {
>     let semantic::Condition::BoolExpr(expr_condition) = expr.condition else {
> ```

use function
___
*[`crates/cairo-lang-lowering/src/lower/usage.rs` line 214 at r17](https://reviewable.io/reviews/starkware-libs/cairo/4945#-Npntf2L2rbZ0eG7btub:-Npntf2L2rbZ0eG7btuc:b30gbti) ([raw file](https://github.com/starkware-libs/cairo/blob/6b192c200cea1a18be3e8402eab60ea268b697d5/crates/cairo-lang-lowering/src/lower/usage.rs#L214)):*
> ```XML
>             }
>             Expr::If(expr) => {
>                 match expr.condition {
> ```

use function
___
*[`crates/cairo-lang-semantic/src/expr/objects.rs` line 358 at r17](https://reviewable.io/reviews/starkware-libs/cairo/4945#-NpntTbW6YFLjThhayu0:-NpntTbW6YFLjThhayu1:biwbqq4) ([raw file](https://github.com/starkware-libs/cairo/blob/6b192c200cea1a18be3e8402eab60ea268b697d5/crates/cairo-lang-semantic/src/expr/objects.rs#L358)):*
> ```XML
> }
> impl Condition {
>     pub fn expr(&self) -> ExprId {
> ```

doc.
rename to `bool_condition`

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4945)* status: 20 of 24 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/lower_if.rs` line 68 at r17](https://reviewable.io/reviews/starkware-libs/cairo/4945#-NpntydfBDkbtbFCq77p:-Npo67pNEzwzgG3b6zts:b-kcoax7) ([raw file](https://github.com/starkware-libs/cairo/blob/6b192c200cea1a18be3e8402eab60ea268b697d5/crates/cairo-lang-lowering/src/lower/lower_if.rs#L68)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

use function
</blockquote></details>

but here i want the compiler to issue warning if the user did try to use if-let

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4945)* status: 20 of 24 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/usage.rs` line 214 at r17](https://reviewable.io/reviews/starkware-libs/cairo/4945#-Npntf2L2rbZ0eG7btub:-NpoOZCK1TIRHn_E-R4C:b-ut4vhf) ([raw file](https://github.com/starkware-libs/cairo/blob/6b192c200cea1a18be3e8402eab60ea268b697d5/crates/cairo-lang-lowering/src/lower/usage.rs#L214)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

use function
</blockquote></details>

removed function
___
*[`crates/cairo-lang-semantic/src/expr/objects.rs` line 358 at r17](https://reviewable.io/reviews/starkware-libs/cairo/4945#-NpntTbW6YFLjThhayu0:-NpoOk6J0H8N9jMvCWT7:b-hfpv0l) ([raw file](https://github.com/starkware-libs/cairo/blob/6b192c200cea1a18be3e8402eab60ea268b697d5/crates/cairo-lang-semantic/src/expr/objects.rs#L358)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc.
rename to `bool_condition`
</blockquote></details>

removed

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r16, 2 of 2 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4945#-:-NpoQ5Di8AIFBvRsydcg:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Pull request merged**
