### PR TITLE
Use Star Edition filter

### PR DESCRIPTION
**Pull request by Tomer-StarkWare**

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6742)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 541 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6742#-OCcF9e90BlpED7ZYpxa:-OCcF9e90BlpED7ZYpxb:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/578b4d8719fd1c40d2390465d73c7e038b16b2b0/crates/cairo-lang-semantic/src/diagnostic.rs#L541)):*
> ```XML
>                 format!(
>                     "Global `use` item is not supported in {} edition.",
>                     edition.prelude_submodule_name()
> ```





_Suggestion:_
```XML
                format!("Global `use` item is not supported in `{:edition?}` edition.")
```
___
*[`crates/cairo-lang-semantic/src/items/module.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6742#-OCcFW556SRH9rmsLQRZ:-OCcFW556SRH9rmsLQR_:b-k6rks2) ([raw file](https://github.com/starkware-libs/cairo/blob/578b4d8719fd1c40d2390465d73c7e038b16b2b0/crates/cairo-lang-semantic/src/items/module.rs#L132)):*
> ```XML
>                     SemanticDiagnosticKind::GlobalUsesNotSupportedInEdition(edition),
>                 );
>             }
> ```

move the diagnostic to `glob-use` item.



_Code quote:_
```XML
    let edition = db
        .crate_config(module_id.owning_crate(db.upcast()))
        .map(|cfg| cfg.settings.edition)
        .unwrap_or_default();
    let allow_global_uses = !edition.ignore_visibility();
    let global_uses = db
        .module_global_uses(module_id)?
        .iter()
        .map(|(global_use_id, use_path_star)| {
            let item = ast::UsePath::Star(use_path_star.clone()).get_item(syntax_db);
            let visibility = item.visibility(syntax_db);
            if !allow_global_uses {
                diagnostics.report(
                    use_path_star,
                    SemanticDiagnosticKind::GlobalUsesNotSupportedInEdition(edition),
                );
            }
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6742)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/items/module.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6742#-OCcFW556SRH9rmsLQRZ:-OCchw_L4wonk6mBOV0Q:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/578b4d8719fd1c40d2390465d73c7e038b16b2b0/crates/cairo-lang-semantic/src/items/module.rs#L132)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

move the diagnostic to `glob-use` item.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 541 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6742#-OCcF9e90BlpED7ZYpxa:-OCcJuFu0GeOnEFRcAEi:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/578b4d8719fd1c40d2390465d73c7e038b16b2b0/crates/cairo-lang-semantic/src/diagnostic.rs#L541)):*
> ```XML
>                 format!(
>                     "Global `use` item is not supported in {} edition.",
>                     edition.prelude_submodule_name()
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6742)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/items/us.rs` line 191 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6742#-OCciGoF3XvByjO4hUdL:-OCciGoF3XvByjO4hUdM:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/82fd936ac6ce5bef7476be0adc28e3878c46a3af/crates/cairo-lang-semantic/src/items/us.rs#L191)):*
> ```XML
>         ));
>         return Ok(UseGlobalData { diagnostics: diagnostics.build(), imported_module });
>     }
> ```





_Suggestion:_
```XML
    let star_ast = db.module_global_use_by_id(global_use_id)?.to_maybe()?;
    let mut resolver = Resolver::new(db, module_file_id, inference_id);
    let edition = resolver.settings.edition;
    if edition.ignore_visibility() {
        let imported_module = Err(diagnostics.report(
            &star_ast,
            SemanticDiagnosticKind::GlobalUsesNotSupportedInEdition(edition),
        ));
        return Ok(UseGlobalData { diagnostics: diagnostics.build(), imported_module });
    }
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6742)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/items/us.rs` line 191 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6742#-OCciGoF3XvByjO4hUdL:-OCcjAx64YTRaiQDvOWe:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/82fd936ac6ce5bef7476be0adc28e3878c46a3af/crates/cairo-lang-semantic/src/items/us.rs#L191)):*
> ```XML
>         ));
>         return Ok(UseGlobalData { diagnostics: diagnostics.build(), imported_module });
>     }
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6742)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/items/us.rs` line 188 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6742#-OCcjZCpCX2NdLsS2rtr:-OCcjZCq29tPQYF-ibbo:bk7dcsi) ([raw file](https://github.com/starkware-libs/cairo/blob/6a9d90efd792eb4dc541425098168f09770a9953/crates/cairo-lang-semantic/src/items/us.rs#L188)):*
> ```XML
>             Err(diagnostics.report(&star_ast, GlobalUsesNotSupportedInEdition(edition)));
>         return Ok(UseGlobalData { diagnostics: diagnostics.build(), imported_module });
>     }
> ```

don't break everything in that case - just add to diagnostics.



_Suggestion:_
```XML
    if edition.ignore_visibility() {
        // We block support for global use where visibility is ignored.
        diagnostics.report(&star_ast, GlobalUsesNotSupportedInEdition(edition));
    }
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6742)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/items/us.rs` line 188 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6742#-OCcjZCpCX2NdLsS2rtr:-OCckO8S4N3hpkWA4Atb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6a9d90efd792eb4dc541425098168f09770a9953/crates/cairo-lang-semantic/src/items/us.rs#L188)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

don't break everything in that case - just add to diagnostics.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6742#-:-OCclg273IVFQ9RLEwQp:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
