### PR TITLE
Fix entry point to point to wrapper.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1245)

### CODE REVIEW

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1245#-:-NIfT0CD0JVDKnzjyAt9:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/starknet/src/plugin.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1245#-NIfSnhy6vrl8PAc09LK:-NIfSnhy6vrl8PAc09LL:b8b3jvj) ([raw file](https://github.com/starkware-libs/cairo/blob/7951225ec4bee762f6920b0d3fd3c169f9327ba7/crates/starknet/src/plugin.rs#L9)):*
> ```XML
> use syntax::node::{ast, Terminal, TypedSyntaxNode};
> 
> pub static CONTRACT_IMPL_ATTR: &str = "ContractImpl";
> ```

Why pub?
___
*[`crates/starknet/src/plugin.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1245#-NIfSddP6G4BX2SaGMk6:-NIfSddP6G4BX2SaGMk7:b-cmn2kq) ([raw file](https://github.com/starkware-libs/cairo/blob/7951225ec4bee762f6920b0d3fd3c169f9327ba7/crates/starknet/src/plugin.rs#L10)):*
> ```XML
> 
> pub static CONTRACT_IMPL_ATTR: &str = "ContractImpl";
> pub static WRAPPER_PREFIX: &str = "__wrapper";
> ```

Include the last underscore here.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1245)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/starknet/src/plugin.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1245#-NIfSnhy6vrl8PAc09LK:-NIgnY6k77ajLIBgiiJs:b-u1sb35) ([raw file](https://github.com/starkware-libs/cairo/blob/7951225ec4bee762f6920b0d3fd3c169f9327ba7/crates/starknet/src/plugin.rs#L9)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Why pub?
</blockquote></details>

otherwise I get:
error[E0603]: static `WRAPPER_PREFIX` is private
___
*[`crates/starknet/src/plugin.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1245#-NIfSddP6G4BX2SaGMk6:-NIgnjreEQRWHVmUDDiQ:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/7951225ec4bee762f6920b0d3fd3c169f9327ba7/crates/starknet/src/plugin.rs#L10)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Include the last underscore here.
</blockquote></details>

done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1245)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1245)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
