### PR TITLE
Removed internal attrs from #[embeddable] impls

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4122)

### CODE REVIEW

**Comment by yuvalsw** [comment]
change target

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 13 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4122#-:-NethdoN99opHdec34UD:bnfp4nl)* status: 13 of 14 files reviewed, 1 unresolved discussion

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 14 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4122)* status: all files reviewed, 1 unresolved discussion

**Review by orizi — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4122)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
