### PR TITLE
Find correct impls for abi Event

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3587)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3587)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3587#-NZV9Nyw3WJncsdZ1PpR:-NZV9Nyw3WJncsdZ1PpS:b-670qnv) (no related file):*
Please add issue test.

___

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3587)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3587#-NZV9Nyw3WJncsdZ1PpR:-NZVfauY5v8sQXcuLChA:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Please add issue test.
</blockquote></details>

Done.

___

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3587)* status: all files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/abi_test.rs` line 198 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3587#-NZVoWxL8mZUVmTseWju:-NZVoWxL8mZUVmTseWjv:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb25c8058d6120b0a6e370eaf322df28d58660d/crates/cairo-lang-starknet/src/abi_test.rs#L198)):*
> ```XML
>           struct A {
>           }
>           
> ```


___
*[`crates/cairo-lang-starknet/src/abi_test.rs` line 202 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3587#-NZVoYvwExSC6W1LCHW6:-NZVoYvwExSC6W1LCHW7:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb25c8058d6120b0a6e370eaf322df28d58660d/crates/cairo-lang-starknet/src/abi_test.rs#L202)):*
> ```XML
>           mod test_contract {
>               use super::A;
>           
> ```


___
*[`crates/cairo-lang-starknet/src/abi_test.rs` line 206 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3587#-NZVo_5J54Bu8_d3Dqr9:-NZVo_5J54Bu8_d3DqrA:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb25c8058d6120b0a6e370eaf322df28d58660d/crates/cairo-lang-starknet/src/abi_test.rs#L206)):*
> ```XML
>               struct Storage {
>               }
>           
> ```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3587)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/abi_test.rs` line 198 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3587#-NZVoWxL8mZUVmTseWju:-NZVp2p6AZit0tMRezbx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb25c8058d6120b0a6e370eaf322df28d58660d/crates/cairo-lang-starknet/src/abi_test.rs#L198)):*
> ```XML
>           struct A {
>           }
>           
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/abi_test.rs` line 202 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3587#-NZVoYvwExSC6W1LCHW6:-NZVp3AA9wTIxF6yjTwW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb25c8058d6120b0a6e370eaf322df28d58660d/crates/cairo-lang-starknet/src/abi_test.rs#L202)):*
> ```XML
>           mod test_contract {
>               use super::A;
>           
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/abi_test.rs` line 206 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3587#-NZVo_5J54Bu8_d3Dqr9:-NZVp3YB9z9wn26HjcDv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb25c8058d6120b0a6e370eaf322df28d58660d/crates/cairo-lang-starknet/src/abi_test.rs#L206)):*
> ```XML
>               struct Storage {
>               }
>           
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3587#-:-NZVpBVNEzID5H2JDWM4:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Pull request merged**
