### PR TITLE
Multiply step cost by 100.

### PR DESCRIPTION
**Pull request by liorgold2**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1305)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1305)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1305#-NJ9W_gl0VVURdsBwj_6:-NJ9W_gl0VVURdsBwj_7:b-xl31e6) (no related file):*
it seems like there's some missing file - as there's no impl change.

___

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1305)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`crates/sierra_to_casm/src/invocations/builtin_cost.rs` line 111 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1305#-NJ9_k5dEfeDLjZcJtiJ:-NJ9_k5e1kGyAcwBK0uN:bsn21eq) ([raw file](https://github.com/starkware-libs/cairo/blob/bb6a2a635e4d1b3e4d7273a90bacf3f29ca0323d/crates/sierra_to_casm/src/invocations/builtin_cost.rs#L111)):*
> ```XML
>     );
>     let compute_requested_amount_steps =
>         casm! { [ap] = ((requested_steps - refund_steps) * 100), ap++; };
> ```

can you put it as some actual constant somewhere?



_Code quote:_
```XML
 * 100
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1305)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/sierra_to_casm/src/invocations/builtin_cost.rs` line 111 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1305#-NJ9_k5dEfeDLjZcJtiJ:-NJ9iuS9CblwXzl1lRUf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bb6a2a635e4d1b3e4d7273a90bacf3f29ca0323d/crates/sierra_to_casm/src/invocations/builtin_cost.rs#L111)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can you put it as some actual constant somewhere?
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1305#-:-NJ9tCkW5zlzg4G2aFTj:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> Dismissed @orizi from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1305)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
