### PR TITLE
removed redundant LanguageElementId function

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1789)

### CODE REVIEW

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1789#-:-NM2R45oBRhPnlgE0ih9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

___
*[`crates/cairo-lang-defs/src/ids.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1789#-NM2R5Ew9kKkJaV04T5q:-NM2R5Ew9kKkJaV04T5r:b-cu0jap) ([raw file](https://github.com/starkware-libs/cairo/blob/9ae075b0ceee3d7286c9f0d249804333272bbbab/crates/cairo-lang-defs/src/ids.rs#L41)):*
> ```XML
>     fn file_index(&self, db: &dyn DefsGroup) -> FileIndex;
>     fn module_file_id(&self, db: &dyn DefsGroup) -> ModuleFileId {
>         ModuleFileId(self.parent_module(db), self.file_index(db))
> ```

Note that for the short_id, you are doing the lookup twice with this implementation.

I don't know if the compiler can optimize it to 1 look or not.



_Code quote:_
```XML
  ModuleFileId(self.parent_module(db), self.file_index(db))
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1789)* status: 14 of 15 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-defs/src/ids.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1789#-NM2R5Ew9kKkJaV04T5q:-NM4b1DM9xaSqa6zWPjB:b-5hnnbs) ([raw file](https://github.com/starkware-libs/cairo/blob/9ae075b0ceee3d7286c9f0d249804333272bbbab/crates/cairo-lang-defs/src/ids.rs#L41)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Note that for the short_id, you are doing the lookup twice with this implementation.

I don't know if the compiler can optimize it to 1 look or not.
</blockquote></details>

This was actually worse. There was a circle, I don't know how it worked, if it did... Anyway - fixed it.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1789#-:-NM7c7kjApWeBZjypUo1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1789)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
