### PR TITLE
chore: remove all instances of inline(always) from corelib

### PR DESCRIPTION
**Pull request by javra**
As suggested by @orizi in the discussion to PR #5911.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6114)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 25 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6114)* status: all files reviewed, 1 unresolved discussion (waiting on @javra)

___
*[`corelib/src/option.cairo` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6114#-O3Cg3QVDNYsxwKHTtnx:-O3Cg3QVDNYsxwKHTtny:bitxyid) ([raw file](https://github.com/starkware-libs/cairo/blob/69ba4aaa9132fd64b872362dbb7b96b5073cfebc/corelib/src/option.cairo#L56)):*
> ```Cairo
>     fn unwrap(self: Option<T>) -> T {
>         self.expect('Option::unwrap failed.')
>     }
> ```

these are a must - without your builds would crash.



_Suggestion:_
```Cairo
    #[inline(never)]
    fn expect(self: Option<T>, err: felt252) -> T {
        match self {
            Option::Some(x) => x,
            Option::None => core::panic_with_felt252(err),
        }
    }

    #[inline(never)]
    fn unwrap(self: Option<T>) -> T {
        self.expect('Option::unwrap failed.')
    }
```

**Review by javra — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6114)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/option.cairo` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6114#-O3Cg3QVDNYsxwKHTtnx:-O3Cusm57tuYJH0K6NGN:b-4ggge9) ([raw file](https://github.com/starkware-libs/cairo/blob/69ba4aaa9132fd64b872362dbb7b96b5073cfebc/corelib/src/option.cairo#L56)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

these are a must - without your builds would crash.
</blockquote></details>

Did you mean to add `never`? They were `inline(always)` before.

What's special about `unwrap` and `expect` in terms of inlining? You already mentioned it on the other PR and I tested it on a small example which didn't crash.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6114)* status: all files reviewed, 2 unresolved discussions (waiting on @javra)

___
*[`corelib/src/option.cairo` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6114#-O3Cg3QVDNYsxwKHTtnx:-O3Cvqy95SgCnDXVcI0z:b-472rd6) ([raw file](https://github.com/starkware-libs/cairo/blob/69ba4aaa9132fd64b872362dbb7b96b5073cfebc/corelib/src/option.cairo#L56)):*
<details><summary><i>Previously, javra (Jakob von Raumer) wrote…</i></summary><blockquote>

Did you mean to add `never`? They were `inline(always)` before.

What's special about `unwrap` and `expect` in terms of inlining? You already mentioned it on the other PR and I tested it on a small example which didn't crash.
</blockquote></details>

i meant `always` - sorry.

it is required due to code doing `withdraw_gas().unwrap()` (or expect).
if it isn't inlined - gas variables won't be able to properly be solved.

**Review by javra — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6114)* status: 24 of 25 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/option.cairo` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6114#-O3Cg3QVDNYsxwKHTtnx:-O3D3u7RBqbcDJ86slGQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/69ba4aaa9132fd64b872362dbb7b96b5073cfebc/corelib/src/option.cairo#L56)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i meant `always` - sorry.

it is required due to code doing `withdraw_gas().unwrap()` (or expect).
if it isn't inlined - gas variables won't be able to properly be solved.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6114#-:-O3D4_e33NNgHFdJR-nA:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @javra)

**Comment by javra** [comment]
@ilyalesokhin-starkware

**Comment by javra** [comment]
Can we move this forward before it rots more than it already has? :sweat_smile:

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6114)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @javra)

**Review by orizi — APPROVED** [review]
yes - sorry - unblocking - rebase and i'll merge.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6114#-:-O5RiNJfDk088VNUn8bM:biyvh9t)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @javra)

**Review by javra — COMMENTED** [review]
done :thumbsup: 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6114#-:-O5S30nN7cFA738Zky7W:b2mf85b)* status: 1 of 25 files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 24 of 24 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6114#-:-O5SEVa9BctOi9G6YgRI:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @javra)

**Pull request merged**
