### PR TITLE
added as expressions in semantic

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5254)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5254)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @orizi and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/type_cast` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5254#-NsrYrdU64kUtAzFgV3S:-NsrYrdU64kUtAzFgV3T:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/1bdff952f86f7cce07efe829a152bedef7f0dbd3/crates/cairo-lang-semantic/src/expr/test_data/type_cast#L1)):*
> ```
> //! > Test type cast nnnnnnn wrong type
> ```


___
*[`crates/cairo-lang-semantic/src/expr/test_data/type_cast` line 25 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5254#-NsrZHrbBLolExdHO0N1:-NsrZHrbBLolExdHO0N2:brmslcl) ([raw file](https://github.com/starkware-libs/cairo/blob/1bdff952f86f7cce07efe829a152bedef7f0dbd3/crates/cairo-lang-semantic/src/expr/test_data/type_cast#L25)):*
> ```
> //! > ==========================================================================
> 
> //! > Test type case wrong type
> ```

Change



_Code quote:_
```
Test type case wrong type
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5254)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/type_cast` line 9 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5254#-NsrpZc35bmEt1GAu_b8:-NsrpZc35bmEt1GAu_b9:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8ba320c09ee90dbf677146a16ce7923270af3988/crates/cairo-lang-semantic/src/expr/test_data/type_cast#L9)):*
> ```
> fn foo() {
>   let _x = 5 as u32;
>   let _y: i16 = _x;
> ```





_Suggestion:_
```
  let _x: i16 = 5 as u32;
```
___
*[`crates/cairo-lang-semantic/src/expr/test_data/type_cast` line 25 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5254#-Nsrpj6fBkgw_IsWrz9W:-Nsrpj6fBkgw_IsWrz9X:bptu5ic) ([raw file](https://github.com/starkware-libs/cairo/blob/8ba320c09ee90dbf677146a16ce7923270af3988/crates/cairo-lang-semantic/src/expr/test_data/type_cast#L25)):*
> ```
> //! > ==========================================================================
> 
> //! > Test type cast annotation needed
> ```

i don't understand.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5254)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/type_cast` line 0 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5254#-NsrqJFg57Mo4XShPepZ:-NsrqJFh5pLyxbGZ8_D8:b-h5q460) ([raw file](https://github.com/starkware-libs/cairo/blob/8ba320c09ee90dbf677146a16ce7923270af3988/crates/cairo-lang-semantic/src/expr/test_data/type_cast#L0)):*
Add `as Array<_>` test.

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5254)* status: all files reviewed, 3 unresolved discussions (waiting on @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5254)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/type_cast` line 9 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5254#-NsrpZc35bmEt1GAu_b8:-Nsvwh5iEF9n7WMTQUIY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8ba320c09ee90dbf677146a16ce7923270af3988/crates/cairo-lang-semantic/src/expr/test_data/type_cast#L9)):*
> ```
> fn foo() {
>   let _x = 5 as u32;
>   let _y: i16 = _x;
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/type_cast` line 25 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5254#-Nsrpj6fBkgw_IsWrz9W:-NsvwnsZBJ8ltBlU9BWd:bacfbm0) ([raw file](https://github.com/starkware-libs/cairo/blob/8ba320c09ee90dbf677146a16ce7923270af3988/crates/cairo-lang-semantic/src/expr/test_data/type_cast#L25)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i don't understand.
</blockquote></details>

changed test name
___
*[`crates/cairo-lang-semantic/src/expr/test_data/type_cast` line  at r2](https://reviewable.io/reviews/starkware-libs/cairo/5254#-NsrqJFg57Mo4XShPepZ:-NsvwgoBEbtbXYiEmuHY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8ba320c09ee90dbf677146a16ce7923270af3988/crates/cairo-lang-semantic/src/expr/test_data/type_cast#L)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Add `as Array<_>` test.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5254#-:-Nsvy2tcDSnsbPeo5V0N:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5254)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request closed without merging**
