### PR TITLE
Add LoweredExpr::as_var_usage.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3505)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3505#-:-NYqe2qb1z50DQMx0D8D:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3505)* status: 4 of 7 files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/generators.rs` line 173 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3505#-NYqsuCW7ZK9CkoG5e5b:-NYqsuCW7ZK9CkoG5e5c:b-ake1h8) ([raw file](https://github.com/starkware-libs/cairo/blob/da2a9e99427ae9c0503c0355e6b41268963c0db9/crates/cairo-lang-lowering/src/lower/generators.rs#L173)):*
> ```XML
> ///
> /// Note that we return Vec<VariableId> rather then Vec<VarUsage> as the location
> /// in the var request is not accurate.
> ```

Note sure what to do here.

I think currently, the user can provide more accurate location.



_Code quote:_
```XML
/// Note that we return Vec<VariableId> rather then Vec<VarUsage> as the location
/// in the var request is not accurate.
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3505)* status: 5 of 7 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/lower/generators.rs` line 173 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3505#-NYqsuCW7ZK9CkoG5e5b:-NYqveeb7WznW3dOFaBO:b-q8zvy2) ([raw file](https://github.com/starkware-libs/cairo/blob/da2a9e99427ae9c0503c0355e6b41268963c0db9/crates/cairo-lang-lowering/src/lower/generators.rs#L173)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Note sure what to do here.

I think currently, the user can provide more accurate location.
</blockquote></details>

destructure is always the target of an assignment or of a match.

this returns to my first issue with this - every expression has a VarUsage at its definition.
not every variable has a VarUsage in the definition.

Struct destructure is not any VarUsage.
```
let Pattern { x } = y;
```
`y` is a usage - `x` has nothing to do with usages.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3505)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/generators.rs` line 173 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3505#-NYqsuCW7ZK9CkoG5e5b:-NYr5QqK5hpisULv--Bk:ba0qwbv) ([raw file](https://github.com/starkware-libs/cairo/blob/da2a9e99427ae9c0503c0355e6b41268963c0db9/crates/cairo-lang-lowering/src/lower/generators.rs#L173)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

destructure is always the target of an assignment or of a match.

this returns to my first issue with this - every expression has a VarUsage at its definition.
not every variable has a VarUsage in the definition.

Struct destructure is not any VarUsage.
```
let Pattern { x } = y;
```
`y` is a usage - `x` has nothing to do with usages.
</blockquote></details>

Member access uses destructure, and it does have a usage location.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3505)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/lower/generators.rs` line 173 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3505#-NYqsuCW7ZK9CkoG5e5b:-NYr8txR7zFLN0aPfZK0:bqazf2x) ([raw file](https://github.com/starkware-libs/cairo/blob/da2a9e99427ae9c0503c0355e6b41268963c0db9/crates/cairo-lang-lowering/src/lower/generators.rs#L173)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Member access uses destructure, and it does have a usage location.
</blockquote></details>

true - but it is the `StructMemberAccess` generator - not this one.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3505)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/generators.rs` line 173 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3505#-NYqsuCW7ZK9CkoG5e5b:-NYrHc5v5D5zLBCMt33-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/da2a9e99427ae9c0503c0355e6b41268963c0db9/crates/cairo-lang-lowering/src/lower/generators.rs#L173)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

true - but it is the `StructMemberAccess` generator - not this one.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3505)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/lower/generators.rs` line 173 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3505#-NYrIXYa57b_iNpe8PiS:-NYrIXYb5T4CcuMMTQ6V:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2afa9096d8c698b8c6c2c41fb34028a8a62a8b44/crates/cairo-lang-lowering/src/lower/generators.rs#L173)):*
> ```XML
> ///
> /// Note that we return `Vec<VariableId>` rather then `Vec<VarUsage>` as the location
> /// in the var request is not accurate.
> ```





_Suggestion:_
```XML
/// Note that we return `Vec<VariableId>` rather then `Vec<VarUsage>` as this is not an expression, but a set of variables returned due to destructuring..
```
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 434 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3505#-NYrJ1o8-MXsmaTdUldY:-NYrJ1o8-MXsmaTdUldZ:b-ixfdg6) ([raw file](https://github.com/starkware-libs/cairo/blob/2afa9096d8c698b8c6c2c41fb34028a8a62a8b44/crates/cairo-lang-lowering/src/lower/mod.rs#L434)):*
> ```XML
>                 .into_iter()
> 
>                 // TODO(ilya): Improve location.
> ```

in what way? - explain the issue.



_Code quote:_
```XML
// TODO(ilya): Improve location.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/generators.rs` line 173 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3505#-NYrIXYa57b_iNpe8PiS:-NYrUvZZ8RnChGpSnrAC:b-gl6pc2) ([raw file](https://github.com/starkware-libs/cairo/blob/2afa9096d8c698b8c6c2c41fb34028a8a62a8b44/crates/cairo-lang-lowering/src/lower/generators.rs#L173)):*
> ```XML
> ///
> /// Note that we return `Vec<VariableId>` rather then `Vec<VarUsage>` as the location
> /// in the var request is not accurate.
> ```

I don't think it is clear how this generator is different from the rest and way it is not an expression.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 434 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3505#-NYrJ1o8-MXsmaTdUldY:-NYrVkmp9GY5Egom1lAW:bbuvko4) ([raw file](https://github.com/starkware-libs/cairo/blob/2afa9096d8c698b8c6c2c41fb34028a8a62a8b44/crates/cairo-lang-lowering/src/lower/mod.rs#L434)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

in what way? - explain the issue.
</blockquote></details>

the same location is used for all the tuple members.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3505)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 434 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3505#-NYrJ1o8-MXsmaTdUldY:-NYrWTftAG7iChRQ6Qkc:b-tvcxcs) ([raw file](https://github.com/starkware-libs/cairo/blob/2afa9096d8c698b8c6c2c41fb34028a8a62a8b44/crates/cairo-lang-lowering/src/lower/mod.rs#L434)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

the same location is used for all the tuple members.
</blockquote></details>

in the TODO comment.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3505)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/generators.rs` line 173 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3505#-NYrIXYa57b_iNpe8PiS:-NYrWfB916Riu_JDHa-U:b-nlf0hx) ([raw file](https://github.com/starkware-libs/cairo/blob/2afa9096d8c698b8c6c2c41fb34028a8a62a8b44/crates/cairo-lang-lowering/src/lower/generators.rs#L173)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't think it is clear how this generator is different from the rest and way it is not an expression.
</blockquote></details>

rephrased.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 434 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3505#-NYrJ1o8-MXsmaTdUldY:-NYrWer3Awle3SeDab88:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2afa9096d8c698b8c6c2c41fb34028a8a62a8b44/crates/cairo-lang-lowering/src/lower/mod.rs#L434)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

in the TODO comment.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3505)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/lower/generators.rs` line 173 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3505#-NYrIXYa57b_iNpe8PiS:-NYrujkZDS_Ksn2-MEXP:bqwbrvv) ([raw file](https://github.com/starkware-libs/cairo/blob/c4105df99ce34227b5a2f1e199f9e3f80f14851b/crates/cairo-lang-lowering/src/lower/generators.rs#L173)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

rephrased.
</blockquote></details>

not pushed

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3505)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 434 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3505#-NYrJ1o8-MXsmaTdUldY:-NYs0XgLAJIwXxF_9o6T:b-d7rzl7) ([raw file](https://github.com/starkware-libs/cairo/blob/c4105df99ce34227b5a2f1e199f9e3f80f14851b/crates/cairo-lang-lowering/src/lower/mod.rs#L434)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not that i see

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3505)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 434 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3505#-NYrJ1o8-MXsmaTdUldY:-NYs272C3TJSjQcM6MHz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c4105df99ce34227b5a2f1e199f9e3f80f14851b/crates/cairo-lang-lowering/src/lower/mod.rs#L434)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

not that i see
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3505)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
