### PR TITLE
Renamed inlineable->inlinable

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2233)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
Not sure you are right
https://en.wiktionary.org/wiki/inlineable

**Review by yuvalsw — COMMENTED** [review]
It says this is the alternative.
Also: https://www.spellzone.com/unit27/page8.cfm
And https://howtospell.co.uk/spelling-words-with-ible-or-able.

But seems like it's also ok-ish, so if you want it this way, we can leave it.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2233#-:-NOpAbcK-yRHDQMZ23Hz:b8trxvf)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
I find inlineable more intuative, but I don't mind renaming it.
@orizi ?

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2233#-:-NOsCWvYEl_cPmfpMz-Y:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
