### PR TITLE
Rename and slightly change EC functions.

### PR DESCRIPTION
**Pull request by liorgold2**
commit-id:59303d4f

---

**Stack**:
- #1837
- #1846
- #1836 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1836)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1836#-NML8Vh47KzNNoZm_OhK:-NML8Vh47KzNNoZm_OhL:b6jhb7g) (no related file):*
This PR introduces the following changes:
1. Rename functions with the convention `ec_state_*`, and using `new` instead of `create` (like rust).
2. Returning the zero point is not an error so it usually shouldn't panic.
3. Removed ec_try_op and replace it with ec_mul which is more useful as a standalone function.
4. Work with `ref` for `EcState`.
5. Removed the Copy trait from EcState. While EcState is still duplicatable in the sierra level, it's confusing that ec_state_finalize() doesn't destroy the object.
6. Add some documentation.

___

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1836#-:-NMNMkk74N0yFiutdZdU:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @liorgold2)

___
*[`corelib/ec.cairo` line 12 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1836#-NMNLOv71kKar-fnQen9:-NMNLOv8CPTQhc50-JQ3:b-kcqmal) ([raw file](https://github.com/starkware-libs/cairo/blob/1aeb045460bed662cfc01a285aa0bd8e6fc777da/corelib/ec.cairo#L12)):*
> ```Cairo
> // EC state.
> 
> #[derive(Drop)]
> ```

won't not having a dup not allow more efficient algorithms that skip doing this init multiple times?

I don't really get what is so bad at having the dup function.



_Code quote:_
```Cairo
#[derive(Drop)]
extern type EcState;
```
___
*[`corelib/ec.cairo` line 19 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1836#-NMNMClB9fKOdthszdsw:-NMNMClB9fKOdthszdsx:b-jcfmjb) ([raw file](https://github.com/starkware-libs/cairo/blob/1aeb045460bed662cfc01a285aa0bd8e6fc777da/corelib/ec.cairo#L19)):*
> ```Cairo
> // TODO(lior): Remove the panic version `ec_state_finalize_nonzero` once option_unwrap() is
> //   supported.
> #[panic_with('Zero point', ec_state_finalize_nonzero)]
> ```

?
(just to have context)



_Suggestion:_
```Cairo
#[panic_with('EC zero point', ec_state_finalize_nonzero)]
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1836)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1836)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @orizi)

___
*[`corelib/ec.cairo` line 12 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1836#-NMNLOv71kKar-fnQen9:-NMNglQo79yT97B0c1q6:b-vvn4k7) ([raw file](https://github.com/starkware-libs/cairo/blob/1aeb045460bed662cfc01a285aa0bd8e6fc777da/corelib/ec.cairo#L12)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

won't not having a dup not allow more efficient algorithms that skip doing this init multiple times?

I don't really get what is so bad at having the dup function.
</blockquote></details>

Noted. We have to decide how to allow explicit clones for duplicatable types.
For now, we won't allow this additional efficiency.
___
*[`corelib/ec.cairo` line 19 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1836#-NMNMClB9fKOdthszdsw:-NMNhGBV-t1iwhz3whn_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1aeb045460bed662cfc01a285aa0bd8e6fc777da/corelib/ec.cairo#L19)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
(just to have context)
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1836)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @liorgold2)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1836)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @liorgold2)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1836)* status: all files reviewed, 3 unresolved discussions (waiting on @liorgold2)

___
*[`corelib/ec.cairo` line 12 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1836#-NMNLOv71kKar-fnQen9:-NMNnsD_9_hzYvG58TMX:b-hfx6zy) ([raw file](https://github.com/starkware-libs/cairo/blob/1aeb045460bed662cfc01a285aa0bd8e6fc777da/corelib/ec.cairo#L12)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Noted. We have to decide how to allow explicit clones for duplicatable types.
For now, we won't allow this additional efficiency.
</blockquote></details>

I don't follow; `ec_state_add` and `ec_state_add_mul` don't re-initialize, which algorithms are you talking about?
___
*[`corelib/test.cairo` line 39 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1836#-NMNpv4JDc84IPfEEDBb:-NMNpv4JDc84IPfEEDBc:bjynxqa) ([raw file](https://github.com/starkware-libs/cairo/blob/75a7ca06427c7f3e5c547b8aa088d80c9f1fe7fa/corelib/test.cairo#L39)):*
> ```Cairo
>     // Beta + 2 is a square, and for x = 1 and alpha = 1, x^3 + alpha * x + beta = beta + 2.
>     let beta_p2_root = 2487829544412206244690656897973144572467842667075005257202960243805141046681;
>     let p = ec_point_new(1, beta_p2_root);
> ```

I think here would be a good place to test your `from_x` function, no?



_Suggestion:_
```Cairo
    let beta_p2_root = 2487829544412206244690656897973144572467842667075005257202960243805141046681;
    let p = option_unwrap(ec_point_from_x(1));
    let (x, y) = ec_point_unwrap(p);
    assert(x == 1, 'x == 1');
    assert(y == beta_p2_root || y == -beta_p2_root, 'y is correct');
```
___
*[`corelib/test.cairo` line 51 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1836#-NMNqmSP9zrTptiv38Pm:-NMNqmSP9zrTptiv38Pn:bhx9mmc) ([raw file](https://github.com/starkware-libs/cairo/blob/75a7ca06427c7f3e5c547b8aa088d80c9f1fe7fa/corelib/test.cairo#L51)):*
> ```Cairo
>     // Try doing the same thing with the EC op builtin.
>     let mut state = ec_state_init();
>     ec_state_add_mul(ref state, 1, p); // TODO
> ```

what is there to do here?



_Code quote:_
```Cairo
// TODO
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1836)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`corelib/ec.cairo` line 12 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1836#-NMNLOv71kKar-fnQen9:-NMNvj-kDvhC3FKR34uZ:bd4mft9) ([raw file](https://github.com/starkware-libs/cairo/blob/1aeb045460bed662cfc01a285aa0bd8e6fc777da/corelib/ec.cairo#L12)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I don't follow; `ec_state_add` and `ec_state_add_mul` don't re-initialize, which algorithms are you talking about?
</blockquote></details>

E.g., if you want both `P+Q+R` and `P+Q+S`, you could duplicate the state after computing `P+Q`.

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1836)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @orizi)

___
*[`corelib/test.cairo` line 39 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1836#-NMNpv4JDc84IPfEEDBb:-NMNz-GZ8hNdF9a5tigI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/75a7ca06427c7f3e5c547b8aa088d80c9f1fe7fa/corelib/test.cairo#L39)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think here would be a good place to test your `from_x` function, no?
</blockquote></details>

Done.
___
*[`corelib/test.cairo` line 51 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1836#-NMNqmSP9zrTptiv38Pm:-NMNz00r2YTVoKXcf-jt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/75a7ca06427c7f3e5c547b8aa088d80c9f1fe7fa/corelib/test.cairo#L51)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what is there to do here?
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1836#-:-NMO-kuj0Sn0dIjXsOKY:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`corelib/ec.cairo` line 12 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1836#-NMNLOv71kKar-fnQen9:-NMO-XkNE6ExgvQbcv-S:b32wh8) ([raw file](https://github.com/starkware-libs/cairo/blob/1aeb045460bed662cfc01a285aa0bd8e6fc777da/corelib/ec.cairo#L12)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

E.g., if you want both `P+Q+R` and `P+Q+S`, you could duplicate the state after computing `P+Q`.
</blockquote></details>

ah

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1836)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`corelib/test.cairo` line 83 at r6](https://reviewable.io/reviews/starkware-libs/cairo/1836#-NMOE4NeA1eLiRcTSTd_:-NMOE4NeA1eLiRcTSTda:bjrtk2o) ([raw file](https://github.com/starkware-libs/cairo/blob/c6cf10898abf68c9889cc673e2bd827167960376/corelib/test.cairo#L83)):*
> ```Cairo
> fn test_bad_ec_point_finalization() {
>     let state = ec_state_init();
>     let point_at_infinity = ec_state_finalize(state);
> ```

bring this back, just call `ec_state_finalize_nonzero` instead. Should be a good thing to test, no?



_Code quote:_
```Cairo
ec_state_finalize(state)
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1836)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`corelib/test.cairo` line 83 at r6](https://reviewable.io/reviews/starkware-libs/cairo/1836#-NMOE4NeA1eLiRcTSTd_:-NMOFXJ7CBo-B_DsIxE0:b-36vq8x) ([raw file](https://github.com/starkware-libs/cairo/blob/c6cf10898abf68c9889cc673e2bd827167960376/corelib/test.cairo#L83)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

bring this back, just call `ec_state_finalize_nonzero` instead. Should be a good thing to test, no?
</blockquote></details>

Moved to next PR. See https://reviewable.io/reviews/starkware-libs/cairo/1846.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1836)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
