### PR TITLE
Adding flattened contract storage

### PR DESCRIPTION
**Pull request by Tomer-StarkWare**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6065)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6065)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6065#-O2ZI_I6A_sukV5EnTyM:-O2ZI_I6A_sukV5EnTyN:b-unnhbk) (no related file):*
rename v1 to v0 all around.
rename v2 to new all around.

___
___
*[`crates/cairo-lang-starknet/cairo_level_tests/component_v1_v2_test.cairo` line 8 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6065#-O2ZI5kZBijwlVjJkrHI:-O2ZI5kZBijwlVjJkrHJ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d18f58a7557bcbd36176f87d645319abd7cef832/crates/cairo-lang-starknet/cairo_level_tests/component_v1_v2_test.cairo#L8)):*
> ```Cairo
>         pub member: felt252,
>     }
> }
> ```





_Suggestion:_
```Cairo
use core::starknet::storage::{StoragePointerWriteAccess, StoragePointerReadAccess};
#[starknet::component]
mod comp_v0 {
    #[storage]
    pub struct Storage {
        pub member: felt252,
    }
}
```
___
*[`crates/cairo-lang-starknet/cairo_level_tests/component_v1_v2_test.cairo` line 24 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6065#-O2ZI8sK7Ui-3cymW9QB:-O2ZI8sK7Ui-3cymW9QC:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d18f58a7557bcbd36176f87d645319abd7cef832/crates/cairo-lang-starknet/cairo_level_tests/component_v1_v2_test.cairo#L24)):*
> ```Cairo
>         comp: comp_v1::Event,
>     }
> }
> ```





_Suggestion:_
```Cairo
#[starknet::contract]
mod contract_v0 {
    use super::comp_v0;
    component!(path: comp_v0, storage: comp, event: comp);
    #[storage]
    pub struct Storage {
        #[substorage(v0)]
        pub comp: comp_v0::Storage,
    }
    #[event]
    #[derive(Drop, starknet::Event)]
    enum Event {
        comp: comp_v0::Event,
    }
}
```
___
*[`crates/cairo-lang-starknet/cairo_level_tests/component_v1_v2_test.cairo` line 91 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6065#-O2ZIpc8DfWaD14EbE5n:-O2ZIpc8DfWaD14EbE5o:b-eduk1c) ([raw file](https://github.com/starkware-libs/cairo/blob/d18f58a7557bcbd36176f87d645319abd7cef832/crates/cairo-lang-starknet/cairo_level_tests/component_v1_v2_test.cairo#L91)):*
> ```Cairo
>     let mut contract_state_v2 = contract_v2::contract_state_for_testing();
>     contract_state_v1.comp.member.write(1);
>     assert_eq!(contract_state_v2.get_member(), 1);
> ```

either do both contracts through contract calls, or all through storage access.
no mixing.



_Code quote:_
```Cairo
    contract_state_v1.comp.member.write(1);
    assert_eq!(contract_state_v2.get_member(), 1);
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6065)* status: 0 of 12 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6065#-O2ZI_I6A_sukV5EnTyM:-O2ZLLHi8FUulY2NuJC4:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rename v1 to v0 all around.
rename v2 to new all around.
</blockquote></details>

Done.

___
___
*[`crates/cairo-lang-starknet/cairo_level_tests/component_v1_v2_test.cairo` line 8 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6065#-O2ZI5kZBijwlVjJkrHI:-O2ZLM-c7iBEGKjo9iFY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d18f58a7557bcbd36176f87d645319abd7cef832/crates/cairo-lang-starknet/cairo_level_tests/component_v1_v2_test.cairo#L8)):*
> ```Cairo
>         pub member: felt252,
>     }
> }
> ```

Done.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/component_v1_v2_test.cairo` line 24 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6065#-O2ZI8sK7Ui-3cymW9QB:-O2ZLM_P8vzPURvUyxJm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d18f58a7557bcbd36176f87d645319abd7cef832/crates/cairo-lang-starknet/cairo_level_tests/component_v1_v2_test.cairo#L24)):*
> ```Cairo
>         comp: comp_v1::Event,
>     }
> }
> ```

Done.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/component_v1_v2_test.cairo` line 91 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6065#-O2ZIpc8DfWaD14EbE5n:-O2ZatAVB2YHvMEpmHuf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d18f58a7557bcbd36176f87d645319abd7cef832/crates/cairo-lang-starknet/cairo_level_tests/component_v1_v2_test.cairo#L91)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

either do both contracts through contract calls, or all through storage access.
no mixing.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r1, 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6065)* status: 6 of 12 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/component_usage_test.cairo` line 7 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6065#-O2ZgEtEEhra07WZ-FS5:-O2ZgEtEEhra07WZ-FS6:b-3oszkw) ([raw file](https://github.com/starkware-libs/cairo/blob/4fa0c2849cf6d051607f19feaf29e867b46cd6ce/crates/cairo-lang-starknet/cairo_level_tests/component_usage_test.cairo#L7)):*
> ```Cairo
>     fn get_member(self: @TCS) -> felt252;
>     fn set_member(ref self: TCS, value: felt252);
> }
> ```

use the actual same trait - no reason to mix.



_Suggestion:_
```Cairo
#[starknet::interface]
pub trait ComponentTrait<TCS> {
    fn get_member(self: @TCS) -> felt252;
    fn set_member(ref self: TCS, value: felt252);
}
```

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r1, 3 of 3 files at r2, 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6065)* status: 11 of 12 files reviewed, 5 unresolved discussions (waiting on @orizi and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/contracts/with_erc20_mini.cairo` line 8 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6065#-O2ZHCVk0Ql3rBO5LvOK:-O2ZHCVk0Ql3rBO5LvOL:bn0l6bo) ([raw file](https://github.com/starkware-libs/cairo/blob/d18f58a7557bcbd36176f87d645319abd7cef832/crates/cairo-lang-starknet/cairo_level_tests/contracts/with_erc20_mini.cairo#L8)):*
> ```Cairo
>     use starknet::ContractAddress;
>     use starknet::storage::{
>         StorageAsPath, StorageNode, StorageNodeMut, StorageTraitMut, StorageTrait
> ```

Are these still needed?



_Code quote:_
```Cairo
StorageNode, StorageNodeMut
```
___
*[`crates/cairo-lang-starknet/src/plugin/storage_interfaces.rs` line 304 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6065#-O2ZgnDSBoPYzg6KSKJg:-O2ZgnDSBoPYzg6KSKJh:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/4fa0c2849cf6d051607f19feaf29e867b46cd6ce/crates/cairo-lang-starknet/src/plugin/storage_interfaces.rs#L304)):*
> ```XML
> /// impls to the given builder. Used for both storage nodes, sub pointers and traits which are
> /// triggered by `#[derive(Store)]`.
> fn storage_interface_for_interface_type(
> ```





_Suggestion:_
```XML
/// Generate the code for a single interface type.
fn handle_storage_interface_for_interface_type(
```
___
*[`crates/cairo-lang-starknet/src/plugin/storage_interfaces.rs` line 324 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6065#-O2ZhAjq4D0n9fk7CGjb:-O2ZhAjq4D0n9fk7CGjc:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/4fa0c2849cf6d051607f19feaf29e867b46cd6ce/crates/cairo-lang-starknet/src/plugin/storage_interfaces.rs#L324)):*
> ```XML
> 
> /// Handles the generation of the storage interface for the given struct.
> /// For StorageNode, it generates both for StorageNode and StorageTrait.
> ```





_Suggestion:_
```XML
/// Adds the storage node structs (two variants, mutable and immutable) and their constructor
/// impls to the given builder. This function is called from several places:
///  - From this plugin for adding storage nodes, and storage base trait.
///  - From the derive plugin of the `Store` trait which also generates a sub-pointers interface.
///  - From the contract storage plugin, which generates storage base trait.
```
___
*[`crates/cairo-lang-starknet/src/plugin/storage_interfaces.rs` line 348 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6065#-O2ZgN3A4F_Cqd-iblaM:-O2ZgN3A4F_Cqd-iblaN:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/4fa0c2849cf6d051607f19feaf29e867b46cd6ce/crates/cairo-lang-starknet/src/plugin/storage_interfaces.rs#L348)):*
> ```XML
>         panic!("Invalid storage interface type.");
>     };
>     storage_interface_for_interface_type(db, struct_ast, metadata, storage_node_type, &mut builder);
> ```





_Suggestion:_
```XML
    let storage_interface_types = if struct_ast.has_attr(db, STORAGE_NODE_ATTR) {
        vec![StorageInterfaceType::StorageTrait, StorageInterfaceType::StorageNode]
    } else if struct_ast.has_attr(db, STORAGE_ATTR) {
        vec![StorageInterfaceType::StorageTrait]
    } else if has_derive(struct_ast, db, STORE_TRAIT).is_some() {
        vec![StorageInterfaceType::SubPointers]
    } else {
        panic!("Invalid storage interface type.");
    };
    for interface_type in storage_interface_types {
        storage_interface_for_interface_type(db, struct_ast, metadata, interface_type, &mut builder);
    }
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6065)* status: 6 of 12 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/component_usage_test.cairo` line 7 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6065#-O2ZgEtEEhra07WZ-FS5:-O2_3e4f8LHxUTQw68D5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4fa0c2849cf6d051607f19feaf29e867b46cd6ce/crates/cairo-lang-starknet/cairo_level_tests/component_usage_test.cairo#L7)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

use the actual same trait - no reason to mix.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/contracts/with_erc20_mini.cairo` line 8 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6065#-O2ZHCVk0Ql3rBO5LvOK:-O2_4td84UwSg58a6MH2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d18f58a7557bcbd36176f87d645319abd7cef832/crates/cairo-lang-starknet/cairo_level_tests/contracts/with_erc20_mini.cairo#L8)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Are these still needed?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/storage_interfaces.rs` line 304 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6065#-O2ZgnDSBoPYzg6KSKJg:-O2_47LL-cfFlGHDomoO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4fa0c2849cf6d051607f19feaf29e867b46cd6ce/crates/cairo-lang-starknet/src/plugin/storage_interfaces.rs#L304)):*
> ```XML
> /// impls to the given builder. Used for both storage nodes, sub pointers and traits which are
> /// triggered by `#[derive(Store)]`.
> fn storage_interface_for_interface_type(
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/storage_interfaces.rs` line 324 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6065#-O2ZhAjq4D0n9fk7CGjb:-O2_4sYk-71wakTiF9fe:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4fa0c2849cf6d051607f19feaf29e867b46cd6ce/crates/cairo-lang-starknet/src/plugin/storage_interfaces.rs#L324)):*
> ```XML
> 
> /// Handles the generation of the storage interface for the given struct.
> /// For StorageNode, it generates both for StorageNode and StorageTrait.
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/storage_interfaces.rs` line 348 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6065#-O2ZgN3A4F_Cqd-iblaM:-O2_4rm52uhwyy1foid7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4fa0c2849cf6d051607f19feaf29e867b46cd6ce/crates/cairo-lang-starknet/src/plugin/storage_interfaces.rs#L348)):*
> ```XML
>         panic!("Invalid storage interface type.");
>     };
>     storage_interface_for_interface_type(db, struct_ast, metadata, storage_node_type, &mut builder);
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6065)* status: 6 of 12 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/component_usage_test.cairo` line 73 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6065#-O2_6m25DsVYAiafCaCG:-O2_6m25DsVYAiafCaCH:b-hfpv23) ([raw file](https://github.com/starkware-libs/cairo/blob/12cd2d9e1086458a22cdd091c91249297197beec/crates/cairo-lang-starknet/cairo_level_tests/component_usage_test.cairo#L73)):*
> ```Cairo
>     fn get_member(self: @TCS) -> felt252;
>     fn set_member(ref self: TCS, value: felt252);
> }
> ```

remove.



_Code quote:_
```Cairo
#[starknet::interface]
pub trait ComponentNewTrait<TCS> {
    fn get_member(self: @TCS) -> felt252;
    fn set_member(ref self: TCS, value: felt252);
}
```
___
*[`crates/cairo-lang-starknet/cairo_level_tests/component_usage_test.cairo` line 85 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6065#-O2_6oiu1U3PAiVtc-N8:-O2_6oiu1U3PAiVtc-N9:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/12cd2d9e1086458a22cdd091c91249297197beec/crates/cairo-lang-starknet/cairo_level_tests/component_usage_test.cairo#L85)):*
> ```Cairo
>         self.storage_mut().member.write(value);
>     }
> }
> ```





_Suggestion:_
```Cairo
#[starknet::embeddable]
pub impl ComponentNewImpl<
    TContractState, +HasStorage<TContractState, ComponentNewStorage>, +Drop<TContractState>
> of ComponentTrait<TContractState> {
    fn get_member(self: @TContractState) -> felt252 {
        self.storage().member.read()
    }
    fn set_member(ref self: TContractState, value: felt252) {
        self.storage_mut().member.write(value);
    }
}
```
___
*[`crates/cairo-lang-starknet/cairo_level_tests/component_usage_test.cairo` line 113 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6065#-O2_6yEv7OVxz4u4PstE:-O2_6yEv7OVxz4u4PstF:b-41y3bx) ([raw file](https://github.com/starkware-libs/cairo/blob/12cd2d9e1086458a22cdd091c91249297197beec/crates/cairo-lang-starknet/cairo_level_tests/component_usage_test.cairo#L113)):*
> ```Cairo
> 
> #[test]
> fn contract_v0_write_new_read_test() {
> ```

is there any good reason not to directly read the values here?

what is the value of using a starknet::interface for this case?

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6065)* status: 6 of 12 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/component_usage_test.cairo` line 73 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6065#-O2_6m25DsVYAiafCaCG:-O2_8LeaC8ehxjPR2hdL:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/12cd2d9e1086458a22cdd091c91249297197beec/crates/cairo-lang-starknet/cairo_level_tests/component_usage_test.cairo#L73)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/component_usage_test.cairo` line 85 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6065#-O2_6oiu1U3PAiVtc-N8:-O2_8LRH0UfrL60eZ5eJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/12cd2d9e1086458a22cdd091c91249297197beec/crates/cairo-lang-starknet/cairo_level_tests/component_usage_test.cairo#L85)):*
> ```Cairo
>         self.storage_mut().member.write(value);
>     }
> }
> ```

Done.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/component_usage_test.cairo` line 113 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6065#-O2_6yEv7OVxz4u4PstE:-O2_BxM15dOKNN98fTv2:b-bs88b9) ([raw file](https://github.com/starkware-libs/cairo/blob/12cd2d9e1086458a22cdd091c91249297197beec/crates/cairo-lang-starknet/cairo_level_tests/component_usage_test.cairo#L113)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is there any good reason not to directly read the values here?

what is the value of using a starknet::interface for this case?
</blockquote></details>

We wanted to check the deref() access to the values.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6065)* status: 6 of 12 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/component_usage_test.cairo` line 113 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6065#-O2_6yEv7OVxz4u4PstE:-O2dIYkQEmTaFfIsbT__:b-5ab65k) ([raw file](https://github.com/starkware-libs/cairo/blob/12cd2d9e1086458a22cdd091c91249297197beec/crates/cairo-lang-starknet/cairo_level_tests/component_usage_test.cairo#L113)):*
<details><summary><i>Previously, Tomer-StarkWare (TomerC-StarkWare) wrote…</i></summary><blockquote>

We wanted to check the deref() access to the values.
</blockquote></details>

but should that be tested somewhere else (also - already tested somewhere else)

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6065)* status: 6 of 12 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/component_usage_test.cairo` line 113 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6065#-O2_6yEv7OVxz4u4PstE:-O2e-yEV1C0o5Mbqpk0G:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/12cd2d9e1086458a22cdd091c91249297197beec/crates/cairo-lang-starknet/cairo_level_tests/component_usage_test.cairo#L113)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

but should that be tested somewhere else (also - already tested somewhere else)
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 6 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6065#-:-O2sQnVTEZ5RadgAr6U2:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6065#-:-O2sSRGTDpxmsIVVVfKM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Tomer-StarkWare)

**Pull request merged**
