### PR TITLE
Small refactor.

### PR DESCRIPTION
**Pull request by liorgold2**
**Stack**:
- #6328
- #6327
- #6323 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6323)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6323)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 264 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6323#-O5hFmSVAYrc_5vvT-n-:-O5hFmSVAYrc_5vvT-n0:bdvemw5) ([raw file](https://github.com/starkware-libs/cairo/blob/7e38ce1d57001faf938959db995bd51e1cd44d09/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L264)):*
> ```XML
>         candidate.match_variable = var_usage.var_id;
> 
>         if remapping.len() != 1 {
> ```

just to make it a bit more direct.



_Suggestion:_
```XML
        if remapping.len() > 1 {
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 264 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6323#-O5hFmSVAYrc_5vvT-n-:-O5lYR3P6W0bzvliBmpb:bu2w8ns) ([raw file](https://github.com/starkware-libs/cairo/blob/7e38ce1d57001faf938959db995bd51e1cd44d09/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L264)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

just to make it a bit more direct.
</blockquote></details>

How do you handle a remapping of a variable that is not the match variable?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 228 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6323#-O5lbed47p6RNwyTFlgg:-O5lbed47p6RNwyTFlgh:byz687m) ([raw file](https://github.com/starkware-libs/cairo/blob/84effd5107d57506cfea13ba2dbfe04c5a560110/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L228)):*
> ```XML
> 
>         let Some(var_usage) = remapping.get(&candidate.match_variable) else {
>             return;
> ```

In the original code, the candidate was invalidated in this case.



_Code quote:_
```XML
 return;
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6323)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @liorgold2)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 264 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6323#-O5hFmSVAYrc_5vvT-n-:-O5lgCuE2Kkhnd-m_6OB:b-j2z0gl) ([raw file](https://github.com/starkware-libs/cairo/blob/7e38ce1d57001faf938959db995bd51e1cd44d09/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L264)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

How do you handle a remapping of a variable that is not the match variable?
</blockquote></details>

he already  had a return on empty remapping - i don't understand the placement of the question.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 264 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6323#-O5hFmSVAYrc_5vvT-n-:-O5lknk11scrAmcLVqY7:b-bj4jjy) ([raw file](https://github.com/starkware-libs/cairo/blob/7e38ce1d57001faf938959db995bd51e1cd44d09/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L264)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

he already  had a return on empty remapping - i don't understand the placement of the question.
</blockquote></details>

I'm talking about a non-empty case; I added a comment above.

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6323)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 264 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6323#-O5hFmSVAYrc_5vvT-n-:-O5m_fdlB82LPeJ2m71g:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/7e38ce1d57001faf938959db995bd51e1cd44d09/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L264)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I'm talking about a non-empty case; I added a comment above.
</blockquote></details>

Done
___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 228 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6323#-O5lbed47p6RNwyTFlgg:-O5m_HPT8Xkcfoyu6Lye:bj3eoea) ([raw file](https://github.com/starkware-libs/cairo/blob/84effd5107d57506cfea13ba2dbfe04c5a560110/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L228)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

In the original code, the candidate was invalidated in this case.
</blockquote></details>

Fixed, thanks.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6323#-:-O5mgD9y8MCiUUeNPDPl:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6323#-:-O5mgxI67Je3O_Yk1iLn:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6323)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
