### PR TITLE
Add optional `annotations` field to `SierraProgram` and `ContractClass`

### PR DESCRIPTION
**Pull request by mkaput**
This field adds an ability to store non-crucial information about the program, for use by external libraries and tool.

See `Annotations` type docs for more information.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4076)

### CODE REVIEW

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4076)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/felt252_serde.rs` line 413 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4076#-NeMoseh6h8tE3lgjShN:-NeMoseh6h8tE3lgjShO:b-3ttogu) ([raw file](https://github.com/starkware-libs/cairo/blob/1b39360fac7253835cc18339517ce57a10f17d30/crates/cairo-lang-starknet/src/felt252_serde.rs#L413)):*
> ```XML
>         }
>         // TODO(mkaput): Consider deserializing annotations here.
>         let annotations = Default::default();
> ```

Here goes a question: where is Felt252Serde of this structure used? I have no idea if we should bother with (de)serializing annotations here, it all depends on use cases.

Nonetheless, if I'd had to implement one, I suggest dumping annotations to JSON, and storing them as a long string (so a sequence of bytes, 1 per felt). Wdyt?

**Review by orizi — COMMENTED** [review]
Do not hold this in the program structure.
You may hold it in the wrapper type or add it to the DebugInfo (and maybe add that info to the json serialization)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4076#-:-NeagjOKBNBnMw6Ep9HG:bewinje)* status: 0 of 8 files reviewed, 1 unresolved discussion

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4076)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @mkaput)

___
*[`crates/cairo-lang-sierra/src/program.rs` line 60 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4076#-NerOUUH9MUDODoWGzY9:-NerOUUH9MUDODoWGzYA:b-nwexdk) ([raw file](https://github.com/starkware-libs/cairo/blob/a029c0a01dc2ab82e95cfaedab179138e7db5c3c/crates/cairo-lang-sierra/src/program.rs#L60)):*
> ```XML
>     /// Descriptions of the functions - signatures and entry points.
>     pub funcs: Vec<Function>,
>     /// Debug information for a Sierra program.
> ```

Do not keep as part of the program.
Keep at the external serialized structure.

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4076)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/program.rs` line 60 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4076#-NerOUUH9MUDODoWGzY9:-NfzbJLb2arz1_hkwwgf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a029c0a01dc2ab82e95cfaedab179138e7db5c3c/crates/cairo-lang-sierra/src/program.rs#L60)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Do not keep as part of the program.
Keep at the external serialized structure.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 9 files at r3, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4076#-:-NgPJja76UC6yzhdAUhj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Pull request merged**
