### PR TITLE
corelib stuff

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3759)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3744** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3744" target="_blank">Graphite</a> 
    * **PR #3745** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3745" target="_blank">Graphite</a> 
      * **PR #3746** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3746" target="_blank">Graphite</a> 
        * **PR #3747** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3747" target="_blank">Graphite</a> 
          * **PR #3748** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3748" target="_blank">Graphite</a> 
            * **PR #3749** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3749" target="_blank">Graphite</a> 
              * **PR #3750** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3750" target="_blank">Graphite</a> 
                * **PR #3751** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3751" target="_blank">Graphite</a> 
                  * **PR #3752** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3752" target="_blank">Graphite</a> 
                    * **PR #3753** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3753" target="_blank">Graphite</a> 
                      * **PR #3754** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3754" target="_blank">Graphite</a> 
                        * **PR #3755** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3755" target="_blank">Graphite</a> 
                          * **PR #3756** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3756" target="_blank">Graphite</a> 
                            * **PR #3757** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3757" target="_blank">Graphite</a> 
                              * **PR #3759** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3759" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/3759?utm_source=stack-comment).

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3744** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3744" target="_blank">Graphite</a> 
    * **PR #3745** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3745" target="_blank">Graphite</a> 
      * **PR #3746** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3746" target="_blank">Graphite</a> 
        * **PR #3747** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3747" target="_blank">Graphite</a> 
          * **PR #3748** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3748" target="_blank">Graphite</a> 
            * **PR #3749** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3749" target="_blank">Graphite</a> 
              * **PR #3750** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3750" target="_blank">Graphite</a> 
                * **PR #3751** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3751" target="_blank">Graphite</a> 
                  * **PR #3752** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3752" target="_blank">Graphite</a> 
                    * **PR #3753** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3753" target="_blank">Graphite</a> 
                      * **PR #3754** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3754" target="_blank">Graphite</a> 
                        * **PR #3755** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3755" target="_blank">Graphite</a> 
                          * **PR #3756** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3756" target="_blank">Graphite</a> 
                            * **PR #3757** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3757" target="_blank">Graphite</a> 
                              * **PR #3759** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3759" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/3759?utm_source=stack-comment).

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3759)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3759#-NaHR9je63tEb8VveK-V:-NaHR9je63tEb8VveK-W:b-d36xeo) (no related file):*
as mentioned f2f - not sure we should support this for now.

___

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3759)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3759#-NaHR9je63tEb8VveK-V:-NaLLhVMANha0nRt4InB:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

as mentioned f2f - not sure we should support this for now.
</blockquote></details>

Done.

___

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3759)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`corelib/src/starknet/storage_access.cairo` line 671 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3759#-NaLLvfxCOu_ZUOkZCo8:-NaLLvfxCOu_ZUOkZCo9:b-c5h4ov) ([raw file](https://github.com/starkware-libs/cairo/blob/00d49e45a808767c3b4a8de6bd8753895d39af9d/corelib/src/starknet/storage_access.cairo#L671)):*
> ```Cairo
>             message.append('Incorrect index:');
>             message.append(idx);
>             starknet::SyscallResult::Err(message)
> ```

in all 4 places.



_Suggestion:_
```Cairo
            starknet::SyscallResult::Err(array!['Incorrect index:', idx])
```

**Pull request merged**
