### PR TITLE
Added `const_as_immediate` libfunc.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #5061
- #5007 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5007)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
:lgtm:

> Reviewed 8 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5007#-:-NpxrGt5-vWxX3dMYHqV:bnfp4nl)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @orizi)

___
*[`tests/e2e_test_data/libfuncs/consts` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5007#-NpxqI_-0g86Rn0lhfdw:-NpxqI_-0g86Rn0lhfdx:b8b9ins) ([raw file](https://github.com/starkware-libs/cairo/blob/8f80e7da79e63ca082b79d398e55935589a554fd/tests/e2e_test_data/libfuncs/consts#L9)):*
> ```
> extern type Const<T, const VALUE: T>;
> extern fn const_as_immediate<T>() -> felt252 nopanic;
> extern fn const_as_box<T, const SEGMENT_INDEX: felt252>() -> Box<felt252> nopanic;
> ```

Just for consistency with the other tests.



_Suggestion:_
```
extern fn const_as_box<T, const SEGMENT_INDEX: felt252>() -> Box<felt252> nopanic;
extern fn const_as_immediate<T>() -> felt252 nopanic;
```

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5007)* status: 8 of 9 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 339 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5007#-NpyH16r9F83L45NOAVI:-NpyH16r9F83L45NOAVJ:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/8f80e7da79e63ca082b79d398e55935589a554fd/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L339)):*
> ```XML
>             return Err(SpecializationError::UnsupportedGenericArg);
>         }
>         let generic_args = context.get_type_info(ty.clone())?.long_id.generic_args;
> ```





_Suggestion:_
```XML
type_info
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 339 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5007#-NpyIc1hEn9ZOWXz8Lve:-NpyIc1i1PIUHNbMs6aC:b-1b6k7r) ([raw file](https://github.com/starkware-libs/cairo/blob/8f80e7da79e63ca082b79d398e55935589a554fd/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L339)):*
> ```XML
>             return Err(SpecializationError::UnsupportedGenericArg);
>         }
>         let generic_args = context.get_type_info(ty.clone())?.long_id.generic_args;
> ```

Maybe use `get_const_args`? Especially if we're splitting the first argument there.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 352 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5007#-NpyHyi1BVKMf8TDihHZ:-NpyHyi1BVKMf8TDihH_:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8f80e7da79e63ca082b79d398e55935589a554fd/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L352)):*
> ```XML
>                     ref_info: OutputVarReferenceInfo::Deferred(DeferredOutputKind::Const),
>                 }],
>                 SierraApChange::Known { new_vars_only: false },
> ```





_Suggestion:_
```XML
                SierraApChange::Known { new_vars_only: true },
```

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5007)* status: 8 of 9 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/const_type.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5007#-NpyJZwZ4aOkGvEdq4XH:-NpyJZwZ4aOkGvEdq4XI:bwytxrx) ([raw file](https://github.com/starkware-libs/cairo/blob/8f80e7da79e63ca082b79d398e55935589a554fd/crates/cairo-lang-sierra-to-casm/src/invocations/const_type.rs#L64)):*
> ```XML
>     builder: CompiledInvocationBuilder<'_>,
> ) -> Result<CompiledInvocation, InvocationError> {
>     let cells = (builder.program_info.const_data_values)(&libfunc.const_type)
> ```

Are the `()` around `const_data_values` needed?

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 2 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5007)* status: 8 of 9 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5007)* status: 8 of 9 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @liorgold2)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 339 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5007#-NpyH16r9F83L45NOAVI:-Nq2vwoo5nCU62mjdLI6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8f80e7da79e63ca082b79d398e55935589a554fd/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L339)):*
> ```XML
>             return Err(SpecializationError::UnsupportedGenericArg);
>         }
>         let generic_args = context.get_type_info(ty.clone())?.long_id.generic_args;
> ```

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 339 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5007#-NpyIc1hEn9ZOWXz8Lve:-Nq2vy_f5n8bVWI3IuHN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8f80e7da79e63ca082b79d398e55935589a554fd/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L339)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Maybe use `get_const_args`? Especially if we're splitting the first argument there.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 352 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5007#-NpyHyi1BVKMf8TDihHZ:-Nq2w0ELDnI0dm_bCkVn:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8f80e7da79e63ca082b79d398e55935589a554fd/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L352)):*
> ```XML
>                     ref_info: OutputVarReferenceInfo::Deferred(DeferredOutputKind::Const),
>                 }],
>                 SierraApChange::Known { new_vars_only: false },
> ```

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/const_type.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5007#-NpyJZwZ4aOkGvEdq4XH:-NpyM3yY7RT3vQt1wwX-:b-olv5o7) ([raw file](https://github.com/starkware-libs/cairo/blob/8f80e7da79e63ca082b79d398e55935589a554fd/crates/cairo-lang-sierra-to-casm/src/invocations/const_type.rs#L64)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Are the `()` around `const_data_values` needed?
</blockquote></details>

yes - since it is a member and not a method.

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 9 files at r1, 2 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5007#-:-NqXT1Zg5lG0Tvhd0pe6:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
