### PR TITLE
Added bookkeep and validation of known stack.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #2292
- #2288 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2288)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2288#-NPMAWC41HN2e3us-hJM:-NPMAWC41HN2e3us-hJN:b-1d5781) ([raw file](https://github.com/starkware-libs/cairo/blob/44c99c0db47df13e9325e7c58d108346e6f9f155/crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs#L168)):*
> ```XML
>                         }
>                         OutputVarReferenceInfo::PartialParam { .. }
>                         | OutputVarReferenceInfo::Deferred(_) => None,
> ```

Can you refactor this into a function?

It is a bit hard to read as a lambda



_Code quote:_
```XML
                    let stack_idx = match var_info.ref_info {
                        OutputVarReferenceInfo::NewTempVar { idx } => {
                            expression.cells.iter().for_each(|cell| {
                                assert_matches!(
                                    cell,
                                    CellExpression::Deref(CellRef { register: Register::AP, .. })
                                )
                            });
                            if let Some(idx) = idx {
                                new_stack_size += 1;
                                Some(stack_base + idx)
                            } else {
                                None
                            }
                        }
                        OutputVarReferenceInfo::NewLocalVar => {
                            expression.cells.iter().for_each(|cell| {
                                assert_matches!(
                                    cell,
                                    CellExpression::Deref(CellRef { register: Register::FP, .. })
                                )
                            });
                            None
                        }
                        OutputVarReferenceInfo::SameAsParam { param_idx } => {
                            if clear_old_stack {
                                None
                            } else {
                                param_stack_idx(param_idx)
                            }
                        }
                        OutputVarReferenceInfo::PartialParam { .. }
                        | OutputVarReferenceInfo::Deferred(_) => None,
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 8 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2288)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2288)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2288#-NPMAWC41HN2e3us-hJM:-NPMl3wVCddnPaUUuQBR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f75e27e5af17dd4344ef6c5ecf828250179efa4c/crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs#L168)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Can you refactor this into a function?

It is a bit hard to read as a lambda


</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2288)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs` line 107 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2288#-NPN0UGJEIUomrYfXN6T:-NPN0UGJEIUomrYfXN6U:bkmhohm) ([raw file](https://github.com/starkware-libs/cairo/blob/b5c174cef7bf7a6dc1140a3c19ff3f198c92edaf/crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs#L107)):*
> ```XML
>     /// The change to the remaing gas value in the wallet.
>     pub gas_change: OrderedHashMap<CostTokenType, i64>,
>     /// Should the stack be cleared due to unknown written changes.
> ```

What is an `unknown written change`?



_Code quote:_
```XML
 unknown written changes
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs` line 120 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2288#-NPN-kij40UuDMoRuFiw:-NPN-kij40UuDMoRuFix:by8lm26) ([raw file](https://github.com/starkware-libs/cairo/blob/b5c174cef7bf7a6dc1140a3c19ff3f198c92edaf/crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs#L120)):*
> ```XML
>         branch_signature: &BranchSignature,
>         curr_stack_size: usize,
>         param_stack_idx: ParamStackIdx,
> ```

Document.



_Code quote:_
```XML
  param_stack_idx: ParamStackIdx,
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs` line 287 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2288#-NPN-nyf6u7Eava_afih:-NPN-nyf6u7Eava_afii:b-j32819) ([raw file](https://github.com/starkware-libs/cairo/blob/b5c174cef7bf7a6dc1140a3c19ff3f198c92edaf/crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs#L287)):*
> ```XML
>     pub libfunc: &'a CoreConcreteLibfunc,
>     pub idx: StatementIdx,
>     pub refs: &'a [ReferenceValue],
> ```

Can you change this to inovke_refs and document?



_Code quote:_
```XML
   pub refs: &'a [ReferenceValue],
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2288)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs` line 107 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2288#-NPN0UGJEIUomrYfXN6T:-NPN26sl0xL-Qig-iDRk:b-r89hwv) ([raw file](https://github.com/starkware-libs/cairo/blob/b5c174cef7bf7a6dc1140a3c19ff3f198c92edaf/crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs#L107)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

What is an `unknown written change`?
</blockquote></details>

something was written to ap - but it is not fully tracked (meaning - no variable is pointing to it)
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs` line 120 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2288#-NPN-kij40UuDMoRuFiw:-NPN1qG9CLmeciHo_IJU:b-xlxw3a) ([raw file](https://github.com/starkware-libs/cairo/blob/b5c174cef7bf7a6dc1140a3c19ff3f198c92edaf/crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs#L120)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Document.
</blockquote></details>

added doc in the following pr - also note that you cannot doc params directly in rust
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs` line 287 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2288#-NPN-nyf6u7Eava_afih:-NPN1znc4wIvJ9lM7cMa:b-xuf0qu) ([raw file](https://github.com/starkware-libs/cairo/blob/b5c174cef7bf7a6dc1140a3c19ff3f198c92edaf/crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs#L287)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Can you change this to inovke_refs and document?
</blockquote></details>

definitely not happening in this pr.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 9 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2288#-:-NPN8B5u4WoZhS9u0JxA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs` line 107 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2288#-NPN8Fz-78W0sz1mL7TV:-NPN8Fz-78W0sz1mL7TW:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b5c174cef7bf7a6dc1140a3c19ff3f198c92edaf/crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs#L107)):*
> ```XML
>     /// The change to the remaing gas value in the wallet.
>     pub gas_change: OrderedHashMap<CostTokenType, i64>,
>     /// Should the stack be cleared due to unknown written changes.
> ```





_Suggestion:_
```XML
  /// Should the stack be cleared due to a gap between stack items.
```

**Review by ilyalesokhin-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2288)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2288)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
