### PR TITLE
Orizi/update audited

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4364)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
Two commits on purpose?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4364#-:-NiZP08-00MxyA8pHQ-a:bjd2usl)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware and @liorgold2)

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4364)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware, @liorgold2, and @orizi)

___
*[`crates/cairo-lang-starknet/src/allowed_libfuncs_lists/audited.json` line 62 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4364#-Ni_25hvAXZQWPPn2aJK:-Ni_25hvAXZQWPPn2aJL:bde9hfq) ([raw file](https://github.com/starkware-libs/cairo/blob/dbb1c1b12dc59f6483295dbaba271f9132232b0b/crates/cairo-lang-starknet/src/allowed_libfuncs_lists/audited.json#L62)):*
> ```JSON
>         "finalize_locals",
>         "function_call",
>         "get_block_hash_syscall",
> ```

Not from this PR, but not in the audited doc.



_Code quote:_
```JSON
"get_block_hash_syscall",
```
___
*[`crates/cairo-lang-starknet/src/allowed_libfuncs_lists/audited.json` line 65 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4364#-Ni_2CtF1SD8A3h0eWV8:-Ni_2CtF1SD8A3h0eWV9:bdfl6c) ([raw file](https://github.com/starkware-libs/cairo/blob/dbb1c1b12dc59f6483295dbaba271f9132232b0b/crates/cairo-lang-starknet/src/allowed_libfuncs_lists/audited.json#L65)):*
> ```JSON
>         "get_builtin_costs",
>         "get_execution_info_syscall",
>         "get_execution_info_v2_syscall",
> ```

Not in the audited doc.



_Code quote:_
```JSON
"get_execution_info_v2_syscall",
```
___
*[`crates/cairo-lang-starknet/src/allowed_libfuncs_lists/audited.json` line 170 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4364#-Ni_2QXW1OypgCX8Kw4A:-Ni_2QXW1OypgCX8Kw4B:b-1flh3v) ([raw file](https://github.com/starkware-libs/cairo/blob/dbb1c1b12dc59f6483295dbaba271f9132232b0b/crates/cairo-lang-starknet/src/allowed_libfuncs_lists/audited.json#L170)):*
> ```JSON
>         "u16_try_from_felt252",
>         "u16_wide_mul",
>         "u256_guarantee_inv_mod_n",
> ```

Not in audited doc.



_Code quote:_
```JSON
"u256_guarantee_inv_mod_n",
```

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4364)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware, @liorgold2, and @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4364)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware, @ilyalesokhin-starkware, and @liorgold2)

___
*[`crates/cairo-lang-starknet/src/allowed_libfuncs_lists/audited.json` line 62 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4364#-Ni_25hvAXZQWPPn2aJK:-Ni_4oJy97QOjwmFdiOV:b-qo9pxu) ([raw file](https://github.com/starkware-libs/cairo/blob/dbb1c1b12dc59f6483295dbaba271f9132232b0b/crates/cairo-lang-starknet/src/allowed_libfuncs_lists/audited.json#L62)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Not from this PR, but not in the audited doc.
</blockquote></details>

it is fine.
___
*[`crates/cairo-lang-starknet/src/allowed_libfuncs_lists/audited.json` line 65 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4364#-Ni_2CtF1SD8A3h0eWV8:-Ni_4pbX77tVED2g4icq:b-qo9pxu) ([raw file](https://github.com/starkware-libs/cairo/blob/dbb1c1b12dc59f6483295dbaba271f9132232b0b/crates/cairo-lang-starknet/src/allowed_libfuncs_lists/audited.json#L65)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Not in the audited doc.
</blockquote></details>

it is fine.
___
*[`crates/cairo-lang-starknet/src/allowed_libfuncs_lists/audited.json` line 170 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4364#-Ni_2QXW1OypgCX8Kw4A:-Ni_4s4ZBP_t2R49g_n-:b-qo9pxu) ([raw file](https://github.com/starkware-libs/cairo/blob/dbb1c1b12dc59f6483295dbaba271f9132232b0b/crates/cairo-lang-starknet/src/allowed_libfuncs_lists/audited.json#L170)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Not in audited doc.
</blockquote></details>

it is fine.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4364#-:-Ni_5HVg7Hv2wii3nfJ4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware and @liorgold2)

**Pull request merged**
