### PR TITLE
LS: Look for unmanaged `core` in Scarb

### LINKED ISSUE #6235: Look for unmanaged `core` in Scarb
Implement this TODO:

https://github.com/starkware-libs/cairo/blob/cdaceb909ccf0644b7e385669d2c48417ceb90d4/crates/cairo-lang-language-server/src/project/unmanaged_core_crate.rs#L26-L29

I think it'd be best to cache the result in a `LazyLock`.

### PR DESCRIPTION
**Pull request by mkaput**
fixes #6235

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6248)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6248#-:-O4sdWwG5UNjQFACr8pg:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @piotmag769)

**Review by Arcticae — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6248#-:-O4tc6yU6hYpHFP9ugdK:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Draggu and @piotmag769)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6248)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Draggu and @piotmag769)

**Review by Draggu — APPROVED** [review]
:lgtm:

> Reviewed 2 of 5 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6248#-:-O5E2XiuDdjLFrI0p0De:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @piotmag769)

**Review by piotmag769 — APPROVED** [review]
:lgtm: feel free to resolve everything and answer later

> Reviewed 2 of 5 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6248#-:-O5E9SCI2xxLn-v-jvjK:b-bxg6xc)* status: all files reviewed, 3 unresolved discussions (waiting on @mkaput)

___
*[`crates/cairo-lang-language-server/src/project/unmanaged_core_crate.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6248#-O5E7pZ05dXhMfuGFRNV:-O5E7pZ05dXhMfuGFRNW:b-z34g3z) ([raw file](https://github.com/starkware-libs/cairo/blob/583c5e94b99b95b27f283c90d1ca58fd25155692/crates/cairo-lang-language-server/src/project/unmanaged_core_crate.rs#L37)):*
> ```XML
>         .or_else(|| find_scarb_managed_core(scarb))
>         .or_else(|| {
>             if cfg!(feature = "testing") {
> ```

Is this feature set by compiler team?
___
*[`crates/cairo-lang-language-server/src/project/unmanaged_core_crate.rs` line 133 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6248#-O5E939VEVSAIQIgTsbW:-O5E939VEVSAIQIgTsbX:bf0nwx2) ([raw file](https://github.com/starkware-libs/cairo/blob/583c5e94b99b95b27f283c90d1ca58fd25155692/crates/cairo-lang-language-server/src/project/unmanaged_core_crate.rs#L133)):*
> ```XML
>     };
> 
>     static CACHE: OnceLock<Option<PathBuf>> = OnceLock::new();
> ```

Smart! :bulb: 
___
*[`crates/cairo-lang-language-server/src/toolchain/scarb.rs` line 56 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6248#-O5E9Og7DoiqaWA-Btvx:-O5E9Og7DoiqaWA-Btvy:bb76mu4) ([raw file](https://github.com/starkware-libs/cairo/blob/583c5e94b99b95b27f283c90d1ca58fd25155692/crates/cairo-lang-language-server/src/toolchain/scarb.rs#L56)):*
> ```XML
>                 if path.is_none() {
>                     if self.is_silent {
>                         // If we are in silent mode, then missing Scarb is probably dealt with
> ```

Why?
___
*[`crates/cairo-lang-language-server/src/toolchain/scarb.rs` line 83 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6248#-O5E9wfv545IJWYknyRa:-O5E9wfv545IJWYknyRb:bxozee) ([raw file](https://github.com/starkware-libs/cairo/blob/583c5e94b99b95b27f283c90d1ca58fd25155692/crates/cairo-lang-language-server/src/toolchain/scarb.rs#L83)):*
> ```XML
>                 // initialized yet.
>                 //
>                 // This maintains a good UX for the following scenario (timeline):
> ```

Could you elaborate on that? I don't think I quite get it

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6248)* status: all files reviewed, 3 unresolved discussions (waiting on @piotmag769)

___
*[`crates/cairo-lang-language-server/src/project/unmanaged_core_crate.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6248#-O5E7pZ05dXhMfuGFRNV:-O5EBb8J1AqjBPcu54_q:b-1zzi6d) ([raw file](https://github.com/starkware-libs/cairo/blob/583c5e94b99b95b27f283c90d1ca58fd25155692/crates/cairo-lang-language-server/src/project/unmanaged_core_crate.rs#L37)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Is this feature set by compiler team?
</blockquote></details>

This is only set in our tests, here: https://github.com/starkware-libs/cairo/blob/536bcff76e78e159405d781c037536ecb446e9ec/crates/cairo-lang-language-server/Cargo.toml#L43
___
*[`crates/cairo-lang-language-server/src/toolchain/scarb.rs` line 56 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6248#-O5E9Og7DoiqaWA-Btvx:-O5EBxSE3izwaiCZ86sg:bxm1abb) ([raw file](https://github.com/starkware-libs/cairo/blob/583c5e94b99b95b27f283c90d1ca58fd25155692/crates/cairo-lang-language-server/src/toolchain/scarb.rs#L56)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

The whole idea of silent mode is that we're using Scarb but in a not obligatory way, i.e. nothing's wrong if Scarb is missing etc. This naturally means that we cannot shout at the user like we'd do in normal mode because this might end up being misleading.

A prime example are the E2E tests, where we don't have Scarb, so we expect the scarb-managed-core branch to fail, but right after we're using `detect_corelib`. We do not want to produce the missing-scarb notification in such scenario.
___
*[`crates/cairo-lang-language-server/src/toolchain/scarb.rs` line 83 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6248#-O5E9wfv545IJWYknyRa:-O5EDnkw18IdIg1WD-Dc:b4zk9qg) ([raw file](https://github.com/starkware-libs/cairo/blob/583c5e94b99b95b27f283c90d1ca58fd25155692/crates/cairo-lang-language-server/src/toolchain/scarb.rs#L83)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Could you elaborate on that? I don't think I quite get it
</blockquote></details>

A silently failing scarb-managed-core flow that would happen before scarb metadata call, could block the missing-scarb notificaiton from popping up when that scarb metadata is run

**Review by piotmag769 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6248)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Pull request merged**
