### PR TITLE
Audit comments.

### PR DESCRIPTION
**Pull request by liorgold2**
**Stack**:
- #4821 ⬅
- #4820

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4821)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4821)* status: 2 of 5 files reviewed, 7 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 214 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4821#-NoeeKY44JrtcDh4h2W-:-NoeeKY44JrtcDh4h2W0:b-7hbprb) ([raw file](https://github.com/starkware-libs/cairo/blob/0ad66c3c80d30d7479fde19cb56e3ee8d99b1da1/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L214)):*
> ```XML
>                 vecOutputVarInfo {
>                     ty: boxed_inner_ty,
>                     // TODO: check
> ```

wdym?
___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 217 at r2 ([raw file](https://github.com/starkware-libs/cairo/blob/0ad66c3c80d30d7479fde19cb56e3ee8d99b1da1/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L217)):*
> ```XML
>                     ref_info: OutputVarReferenceInfo::NewTempVar { idx: 0 },
>                 }],
>                 // TODO: Can we test `new_vars_only` automatically?
> ```

Done
___
*[`crates/cairo-lang-sierra/src/extensions/modules/enm.rs` line 248 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4821#-NoefvxKDYjtKK_Wtw6W:-NoefvxKDYjtKK_Wtw6X:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/0ad66c3c80d30d7479fde19cb56e3ee8d99b1da1/crates/cairo-lang-sierra/src/extensions/modules/enm.rs#L248)):*
> ```XML
>             }
>         }
>         // TODO: refactor this into a function `bounded_int_ty` that takes two Into<BigInt>
> ```

Done
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 145 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4821#-Nof-ghh1P1-OUweqi9I:-Nof-ghh1P1-OUweqi9J:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/0ad66c3c80d30d7479fde19cb56e3ee8d99b1da1/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L145)):*
> ```XML
>         let mut const_allocations = OrderedHashMap::default();
>         let mut const_segment_size = 0;
>         // TODO: order by appearance in the type segment of the program. The current order may be
> ```

done
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 206 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4821#-Nof-hps4DCo7OPeBS33:-Nof-hps4DCo7OPeBS34:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/0ad66c3c80d30d7479fde19cb56e3ee8d99b1da1/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L206)):*
> ```XML
>                 match &const_type.inner_data[..] {
>                     [GenericArg::Value(selector), GenericArg::Type(ty)] => {
>                         // TODO: Convert selector to the correct form.
> ```

done
___
*[`crates/cairo-lang-sierra-to-casm/src/relocations.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4821#-NogCcHP7BlQvxclBRMM:-NogCcHP7BlQvxclBRMN:bth9zvs) ([raw file](https://github.com/starkware-libs/cairo/blob/0ad66c3c80d30d7479fde19cb56e3ee8d99b1da1/crates/cairo-lang-sierra-to-casm/src/relocations.rs#L45)):*
> ```XML
>             }
>             Relocation::EndOfProgram => {
>                 // TODO: Check const usage + withdraw_gas_all in one test (if not exists).
> ```

Adding cairo level tests for it, these ensures both work at the same time.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/const_type.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4821#-NogCfir0MUogR86mdpG:-NogCfir0MUogR86mdpH:b-mbce9) ([raw file](https://github.com/starkware-libs/cairo/blob/0ad66c3c80d30d7479fde19cb56e3ee8d99b1da1/crates/cairo-lang-sierra-to-casm/src/invocations/const_type.rs#L36)):*
> ```XML
>     };
>     let relocations = vec![
>         // TODO: check Relocation::Const.
> ```

Adding cairo level tests for it.

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4821)* status: 4 of 5 files reviewed, 7 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 214 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4821#-NoeeKY44JrtcDh4h2W-:-Noqs4Sz8cRa5f3XXe78:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0ad66c3c80d30d7479fde19cb56e3ee8d99b1da1/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L214)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

wdym?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 217 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4821#-NoRUzzk-OivBLDVXd04:-Noqs3wcCcIdVKSePQVU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0ad66c3c80d30d7479fde19cb56e3ee8d99b1da1/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L217)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Done
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/enm.rs` line 248 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4821#-NoefvxKDYjtKK_Wtw6W:-NoqsWK_84icIJZdvvKS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0ad66c3c80d30d7479fde19cb56e3ee8d99b1da1/crates/cairo-lang-sierra/src/extensions/modules/enm.rs#L248)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Done
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 145 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4821#-Nof-ghh1P1-OUweqi9I:-NoqsbOiBWWED3UNk9Jv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0ad66c3c80d30d7479fde19cb56e3ee8d99b1da1/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L145)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

done
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 206 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4821#-Nof-hps4DCo7OPeBS33:-Noqsc_r3UWCO4eGDSEx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0ad66c3c80d30d7479fde19cb56e3ee8d99b1da1/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L206)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

done
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/const_type.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4821#-NogCfir0MUogR86mdpG:-NoqsuYm3xZnEElzgWxO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0ad66c3c80d30d7479fde19cb56e3ee8d99b1da1/crates/cairo-lang-sierra-to-casm/src/invocations/const_type.rs#L36)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Adding cairo level tests for it.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4821)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/relocations.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4821#-NogCcHP7BlQvxclBRMM:-Np-NRdJ2d_Ti2C-m6Bf:b-6dyg1k) ([raw file](https://github.com/starkware-libs/cairo/blob/0ad66c3c80d30d7479fde19cb56e3ee8d99b1da1/crates/cairo-lang-sierra-to-casm/src/relocations.rs#L45)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Adding cairo level tests for it, these ensures both work at the same time.
</blockquote></details>

https://reviewable.io/reviews/starkware-libs/cairo/4918

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4821)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/relocations.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4821#-NogCcHP7BlQvxclBRMM:-Np0EYpOEgOqKYlLmIH7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0ad66c3c80d30d7479fde19cb56e3ee8d99b1da1/crates/cairo-lang-sierra-to-casm/src/relocations.rs#L45)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

https://reviewable.io/reviews/starkware-libs/cairo/4918
</blockquote></details>

Done.

**Pull request closed without merging**
