### PR TITLE
Remove LoweredExpr::var

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3586)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3586)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 368 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3586#-NZUrvmmCnV-onxR7LoX:-NZUrvmmCnV-onxR7LoY:b-p5wzv9) ([raw file](https://github.com/starkware-libs/cairo/blob/f6a85dfec11053c65cc68e77db3c82e1639b8e41/crates/cairo-lang-lowering/src/lower/mod.rs#L368)):*
> ```XML
>             let sem_var = semantic::Variable::Local(sem_var.clone());
>             // Deposit the owned variable in the semantic variables store.
>             let var = lowered_expr.var(ctx, builder)?;
> ```

I could have kept this function,
but I found it easier to clean up the manual `VarUsage` wrapping in the code by removing it.



_Code quote:_
```XML
lowered_expr.var(ctx, builder)?;
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3586)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/lower/lower_if.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3586#-NZUvWid-tLboUXyu4zk:-NZUvWid-tLboUXyu4zl:b6f8wf0) ([raw file](https://github.com/starkware-libs/cairo/blob/afcdeeeb357fb240876339fc237e531019689fe3/crates/cairo-lang-lowering/src/lower/lower_if.rs#L81)):*
> ```XML
>     log::trace!("Lowering a boolean if expression: {:?}", expr.debug(&ctx.expr_formatter));
>     // The condition cannot be unit.
>     let match_input = lower_expr_to_var_usage(ctx, builder, expr.condition)?;
> ```

i think the original name was a bit clearer.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/lower_if.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3586#-NZUvWid-tLboUXyu4zk:-NZUxCyo2EkdG2d2FaNo:b-mbmxvf) ([raw file](https://github.com/starkware-libs/cairo/blob/afcdeeeb357fb240876339fc237e531019689fe3/crates/cairo-lang-lowering/src/lower/lower_if.rs#L81)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i think the original name was a bit clearer.
</blockquote></details>

But it is a var_usage, not a var.

condition_input?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3586)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/lower/lower_if.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3586#-NZUvWid-tLboUXyu4zk:-NZV24_D7vfLaFZFgRex:bizjijz) ([raw file](https://github.com/starkware-libs/cairo/blob/afcdeeeb357fb240876339fc237e531019689fe3/crates/cairo-lang-lowering/src/lower/lower_if.rs#L81)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

But it is a var_usage, not a var.

condition_input?
</blockquote></details>

condition_var_usage?
condition?

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3586#-:-NZV9Ut2EEsYO3x-jgfN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
