### PR TITLE
Made sierra contracts be felt-vec based.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:e5e65d0b

---

**Stack**:
- #1485
- #1484
- #1482 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1482#-:-NKCJrJQB5eZz1ZKYYdV:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/starknet/src/contract_class_test.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1482#-NKCJH4s-TJeZLbju0TW:-NKCJH4s-TJeZLbju0TX:bv9bku5) ([raw file](https://github.com/starkware-libs/cairo/blob/ea69bb2fe7abebe7a7c68578377d5a6152ca9d18/crates/starknet/src/contract_class_test.rs#L19)):*
> ```XML
>     let contract = ContractClass {
>         sierra_program: vec![],
>         sierra_program_debug_info: sierra::debug_info::DebugInfo {
> ```

I think this should be inside the sierra program.



_Code quote:_
```XML
sierra_program_debug_info
```
___
*[`crates/starknet/src/contract_class_test.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1482#-NKCJjQb3zCikAdZpUyt:-NKCJjQb3zCikAdZpUyu:bvplqnv) ([raw file](https://github.com/starkware-libs/cairo/blob/ea69bb2fe7abebe7a7c68578377d5a6152ca9d18/crates/starknet/src/contract_class_test.rs#L80)):*
> ```XML
>     let mut sierra_program = sierra_from_felts(&contract.sierra_program).unwrap();
>     contract.sierra_program_debug_info.populate(&mut sierra_program);
> ```

Consider removing it
and fixing 
Program::fmt to use the debug info.



_Code quote:_
```XML
    let mut sierra_program = sierra_from_felts(&contract.sierra_program).unwrap();
    contract.sierra_program_debug_info.populate(&mut sierra_program);
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1482)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/starknet/src/contract_class_test.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1482#-NKCJH4s-TJeZLbju0TW:-NKCL_jI65Ckz-9O7mQ5:bmwte00) ([raw file](https://github.com/starkware-libs/cairo/blob/ea69bb2fe7abebe7a7c68578377d5a6152ca9d18/crates/starknet/src/contract_class_test.rs#L19)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I think this should be inside the sierra program.
</blockquote></details>

in here specifically - this would not make sense - as this is *only* the debug info, which will be used for debug only, so it cannot be here within the serialized program.
___
*[`crates/starknet/src/contract_class_test.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1482#-NKCJjQb3zCikAdZpUyt:-NKCLrXI54_P3GJYem4P:bhqy39r) ([raw file](https://github.com/starkware-libs/cairo/blob/ea69bb2fe7abebe7a7c68578377d5a6152ca9d18/crates/starknet/src/contract_class_test.rs#L80)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Consider removing it
and fixing 
Program::fmt to use the debug info.
</blockquote></details>

as long as we support lalrpop - i don't think we should do that.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/starknet/src/contract_class_test.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1482#-NKCJH4s-TJeZLbju0TW:-NKCWzD14q7VOevfM5Yy:bjfbrbk) ([raw file](https://github.com/starkware-libs/cairo/blob/ad1c0dc822dbdd71068bc70417602460257e1717/crates/starknet/src/contract_class_test.rs#L19)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

in here specifically - this would not make sense - as this is *only* the debug info, which will be used for debug only, so it cannot be here within the serialized program.
</blockquote></details>

I see, but I find it strange that a sierra can be serialized to felts only inside a StarkNet Contract.

**Review by ilyalesokhin-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1482)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by ilyalesokhin-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1482)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/starknet/src/contract_class_test.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1482#-NKCJjQb3zCikAdZpUyt:-NKCXD5iBMrxmq8BgM6o:bdao303) ([raw file](https://github.com/starkware-libs/cairo/blob/ad1c0dc822dbdd71068bc70417602460257e1717/crates/starknet/src/contract_class_test.rs#L80)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

as long as we support lalrpop - i don't think we should do that.
</blockquote></details>

I disagree.

But this PR is a change in the right direction.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1482)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/starknet/src/contract_class_test.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1482#-NKCJH4s-TJeZLbju0TW:-NKCe9476IlX2iMzWZyQ:b-rmgthd) ([raw file](https://github.com/starkware-libs/cairo/blob/ad1c0dc822dbdd71068bc70417602460257e1717/crates/starknet/src/contract_class_test.rs#L19)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I see, but I find it strange that a sierra can be serialized to felts only inside a StarkNet Contract.
</blockquote></details>

when we need felts serialization anywhere else - we'll extract it - but this is unrelated.

**Pull request merged**
