### PR TITLE
Move diagnostics reporting to inference.finalize().

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5350)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 15 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5350)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`crates/cairo-lang-starknet/test_data/test_syscalls.json` line 0 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5350#-NuTZhMYAHxljSsBDN4k:-NuTZhMYAHxljSsBDN4l:b-6byopr) ([raw file](https://github.com/starkware-libs/cairo/blob/1f5882935ef47b4def3e2468328131865370670b/crates/cairo-lang-starknet/test_data/test_syscalls.json#L0)):*
Probably added by mistake.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5350)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-starknet/test_data/test_syscalls.json` line  at r1](https://reviewable.io/reviews/starkware-libs/cairo/5350#-NuTZhMYAHxljSsBDN4k:-NuTaH15C-2IkNAzTrue:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1f5882935ef47b4def3e2468328131865370670b/crates/cairo-lang-starknet/test_data/test_syscalls.json#L)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Probably added by mistake.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5350)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 624 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5350#-NuTey6g4ECi9RRaXfkv:-NuTey6g4ECi9RRaXfkw:b-ef0nrf) ([raw file](https://github.com/starkware-libs/cairo/blob/59f7a230413809aad61c4a4f4d3245243118c384/crates/cairo-lang-semantic/src/expr/inference.rs#L624)):*
> ```XML
>             );
>         }
>     }
> ```

will this work?



_Suggestion:_
```XML
        language_element: impl LanguageElementId,
    ) {
        if let Err((err_set, err_stable_ptr)) = self.finalize_without_reporting() {
            self.report_on_pending_error(
                err_set,
                diagnostics,
                err_stable_ptr.unwrap_or_else(||language_element.untyped_stable_ptr()),
            );
        }
    }
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 624 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5350#-NuTey6g4ECi9RRaXfkv:-NuThCS82nCjg4wm_DH2:bh98uqp) ([raw file](https://github.com/starkware-libs/cairo/blob/59f7a230413809aad61c4a4f4d3245243118c384/crates/cairo-lang-semantic/src/expr/inference.rs#L624)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

will this work?
</blockquote></details>

Maybe, but why do you want to make this a generic function?
is getting the stable pointer an expensive operation?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 624 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5350#-NuTey6g4ECi9RRaXfkv:-NuTjkSVC6A2MjG9gk91:bmg694n) ([raw file](https://github.com/starkware-libs/cairo/blob/59f7a230413809aad61c4a4f4d3245243118c384/crates/cairo-lang-semantic/src/expr/inference.rs#L624)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Maybe, but why do you want to make this a generic function?
is getting the stable pointer an expensive operation?
</blockquote></details>

`LanguageElementId` does not work.

I tried `LanguageElementId` but I get:



_Code snippet:_
```XML
error[E0277]: the trait bound `&cairo_lang_syntax::node::ast::ItemTypeAlias: cairo_lang_syntax::node::TypedSyntaxNode` is not satisfied
   --> crates/cairo-lang-semantic/src/items/type_aliases.rs:55:42
    |
55  |     inference.finalize(&mut diagnostics, type_alias_ast);
    |               --------                   ^^^^^^^^^^^^^^ the trait `cairo_lang_syntax::node::TypedSyntaxNode` is not implemented for `&cairo_lang_syntax::node::ast::ItemTypeAlias`
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 624 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5350#-NuTey6g4ECi9RRaXfkv:-NuTjxt37I-lfecZfqM2:bpk0txt) ([raw file](https://github.com/starkware-libs/cairo/blob/59f7a230413809aad61c4a4f4d3245243118c384/crates/cairo-lang-semantic/src/expr/inference.rs#L624)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

`LanguageElementId` does not work.

I tried `LanguageElementId` but I get:
</blockquote></details>

sorry, I tried `TypedSyntaxNode`, I guess I could pass a call back.

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5350)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 624 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5350#-NuTey6g4ECi9RRaXfkv:-NuTktpd3P4ZcJPDdGzx:bns9obi) ([raw file](https://github.com/starkware-libs/cairo/blob/59f7a230413809aad61c4a4f4d3245243118c384/crates/cairo-lang-semantic/src/expr/inference.rs#L624)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

sorry, I tried `TypedSyntaxNode`, I guess I could pass a call back.
</blockquote></details>

No need.

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5350#-:-NuTkyiF71AWmW9DUkqi:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
