### PR TITLE
Moved parser tests to use the testing infrastructure.

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4010)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 14 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4010)* status: 14 of 15 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser_test.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4010#-Nd_bKCa0W7By2J0OFcP:-Nd_bKCa0W7By2J0OFcQ:bl9168a) ([raw file](https://github.com/starkware-libs/cairo/blob/f9c6ceed8ee22e9edc3155430dd1324cf57505f4/crates/cairo-lang-parser/src/parser_test.rs#L90)):*
> ```XML
> }
> 
> /// Returns the syntax_root and diagnostics of a file in the db, according to the parser test
> ```

and doc



_Suggestion:_
```XML
        ("expected_diagnostics".into(), diagnostics),
    ]))
}

pub fn test_full_parser_tree(
    inputs: &OrderedHashMap<String, String>,
    args: &OrderedHashMap<String, String>,
) -> Result<OrderedHashMap<String, String>, String> {
    let db = &SimpleParserDatabase::default();
    let (syntax_root, diagnostics) = get_syntax_root_and_diagnostics_from_inputs(db, inputs);
    has_disallowed_diagnostics(args, &diagnostics)?;

    Ok(OrderedHashMap::from([
        (
            "expected_tree".into(),
            print_tree(
                db,
                &syntax_root,
                bool_input(&inputs["print_colors"]),
                bool_input(&inputs["print_trivia"]),
            ),
        ),
        ("expected_diagnostics".into(), diagnostics),
    ]))
}

fn test_colored_parsed_code(
    inputs: &OrderedHashMap<String, String>,
    _args: &OrderedHashMap<String, String>,
) -> Result<OrderedHashMap<String, String>, String> {
    let db = &SimpleParserDatabase::default();
    let (syntax_root, _) = get_syntax_root_and_diagnostics_from_inputs(db, inputs);
    Ok(OrderedHashMap::from([(
        "expected_colored".into(),
        print_colored(db, &syntax_root, bool_input(&inputs["is_verbose"])),
    )]))
}

/// Returns the syntax_root and diagnostics of a file in the db, according to the parser test
```
___
*[`crates/cairo-lang-test-utils/src/lib.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4010#-Nd_bxGUEU2fMmsIJULo:-Nd_bxGVEkrtVqlMH5-7:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f9c6ceed8ee22e9edc3155430dd1324cf57505f4/crates/cairo-lang-test-utils/src/lib.rs#L67)):*
> ```XML
>         panic!("Expected 'true' or 'false', actual: {input}");
>     }
> }
> ```





_Suggestion:_
```XML
) -> Result<(), String> {
    if let Some(allow_diagnostics) = args.get("allow_diagnostics") {
        if !bool::from_str(allow_diagnostics) && !diagnostics.is_empty() {
            return Err(format!(
                "allow_diagnostics is false, but diagnostics were generated:\n{}",
                diagnostics
            ));
        }
    }

    Ok(())
}
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4010)* status: 13 of 15 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-parser/src/parser_test.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4010#-Nd_bKCa0W7By2J0OFcP:-Nd_dIudEwiNhTETRgfC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f9c6ceed8ee22e9edc3155430dd1324cf57505f4/crates/cairo-lang-parser/src/parser_test.rs#L90)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

and doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-test-utils/src/lib.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4010#-Nd_bxGUEU2fMmsIJULo:-Nd_edDP38upP6maNnt_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f9c6ceed8ee22e9edc3155430dd1324cf57505f4/crates/cairo-lang-test-utils/src/lib.rs#L67)):*
> ```XML
>         panic!("Expected 'true' or 'false', actual: {input}");
>     }
> }
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4010#-:-Nd_iQAKAwudo3EalgI3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4010)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4010)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4010)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
