### PR TITLE
Using code words to compress sierra program

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2645)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/felt252_serde.rs` line 66 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2645#-NRlNMFh7Qx7Q_mo0KDK:-NRlNMFh7Qx7Q_mo0KDL:bh7hvrf) ([raw file](https://github.com/starkware-libs/cairo/blob/892031c032d0054420f0a4d4e172718c05a5d6d3/crates/cairo-lang-starknet/src/felt252_serde.rs#L66)):*
> ```XML
> }
> 
> /// Given the size of the code book, returns the number of bits required to encode a code word, and
> ```

what does the code size have to do with the number of bits required to encode a code word?



_Code quote:_
```XML
Given the size of the code book, returns the number of bits required to encode a code word, and
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/felt252_serde.rs` line 124 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2645#-NRlPHLy8gJqhDIpaoGE:-NRlPHLy8gJqhDIpaoGF:b-oxnye7) ([raw file](https://github.com/starkware-libs/cairo/blob/892031c032d0054420f0a4d4e172718c05a5d6d3/crates/cairo-lang-starknet/src/felt252_serde.rs#L124)):*
> ```XML
>             v >>= bits_per_word;
>         }
>         for i in 0..curr_words {
> ```

why split into two loops?



_Code quote:_
```XML
        for i in 0..curr_words {
            unpacked_words_buffer[curr_words - 1 - i] =
                (v.clone() & BigUint::from(word_mask)).to_usize().unwrap();
            v >>= bits_per_word;
        }
        for i in 0..curr_words {
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
this breaks backward compltability, right?

> Reviewed 3 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2645#-:-NRlPStw9-btx4ypAoq4:b-m70cf8)* status: 3 of 7 files reviewed, 2 unresolved discussions (waiting on @orizi)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
bump the contract_class_version

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2645#-:-NRlUopi4tz3rCPqrY0A:bfy84vs)* status: 3 of 7 files reviewed, 2 unresolved discussions (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
we are bumping this as part of the release - not with every touch.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2645#-:-NRlXm1JDnV_RG7tiMKU:b-umakkv)* status: 3 of 7 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/felt252_serde.rs` line 66 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2645#-NRlNMFh7Qx7Q_mo0KDK:-NRlXuPx50Wdsm5ynpY0:b-98re3t) ([raw file](https://github.com/starkware-libs/cairo/blob/892031c032d0054420f0a4d4e172718c05a5d6d3/crates/cairo-lang-starknet/src/felt252_serde.rs#L66)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what does the code size have to do with the number of bits required to encode a code word?
</blockquote></details>

this is the size of the `code` not the size of the sierra program.
___
*[`crates/cairo-lang-starknet/src/felt252_serde.rs` line 124 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2645#-NRlPHLy8gJqhDIpaoGE:-NRlY-zc-9OQ7fx1ogh7:b7p76u2) ([raw file](https://github.com/starkware-libs/cairo/blob/892031c032d0054420f0a4d4e172718c05a5d6d3/crates/cairo-lang-starknet/src/felt252_serde.rs#L124)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why split into two loops?
</blockquote></details>

the insertion order is inverted.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2645)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/felt252_serde.rs` line 66 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2645#-NRlNMFh7Qx7Q_mo0KDK:-NRl_DX39mfBvpoK2vWN:bebv65u) ([raw file](https://github.com/starkware-libs/cairo/blob/892031c032d0054420f0a4d4e172718c05a5d6d3/crates/cairo-lang-starknet/src/felt252_serde.rs#L66)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

you should pass the number of unique words here, not the program size.
</blockquote></details>

correct - and that is the code size. not the program size.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2645)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/felt252_serde.rs` line 124 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2645#-NRlPHLy8gJqhDIpaoGE:-NRl_LX6DZgyLdNfYkuf:b-kf7c1h) ([raw file](https://github.com/starkware-libs/cairo/blob/892031c032d0054420f0a4d4e172718c05a5d6d3/crates/cairo-lang-starknet/src/felt252_serde.rs#L124)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

then maybe you should encode it it the other order?

i.e. make the encoding more expensive and the decode cheaper.
</blockquote></details>

it would just move the issue to the encoding - in the exact same annoying manner.

**Review by mkaput — COMMENTED** [review]
> we are bumping this as part of the release - not with every touch.

Ouch I think this asks for disaster. Back when I worked in IntelliJ Rust we did what @ilyalesokhin-starkware's suggested, because it's less problematic to bump version counter by accident by multiple ticks, than to forget to bump it at all

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2645#-:-NRlcCkuElGaAdyRsrdb:bosgrmv)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by mkaput — COMMENTED** [review]
yeah, but another example I have is if somebody supposedly will use a checkout of this repository after this PR but before next release to build sierra, and feed it into existing Starknet, they will get cryptic error about malformed sierra instead an error that different version was published

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2645#-:-NRljezA6XneaH8479qA:b-apsme5)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by orizi — COMMENTED** [review]
that is why i'm not planning on merging it before we decide on a couple of things here.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2645#-:-NRlkIHBAkJjLQb8JrsA:b45gaih)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2645)* status: 5 of 9 files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2645)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 7 of 8 files at r7, 7 of 7 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2645)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
