### PR TITLE
Made config travese the entire tree only when needed.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3786)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3786)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3786#-Naa0e3kE8QMKgcQzFmQ:-Naa0e3kE8QMKgcQzFmR:befg661) ([raw file](https://github.com/starkware-libs/cairo/blob/b604a1a74782879140d4aada7c4abeb99b463be0/crates/cairo-lang-plugins/src/plugins/config.rs#L40)):*
> ```XML
>             };
>         }
>         match item_ast {
> ```

I think there are some more that are needed, like ModuleBody, ImplBody, etc... Check in the cairo_spec.rs, or in parser test syntax files for example

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3786)* status: 0 of 1 files reviewed, all discussions resolved

___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3786#-Naa0e3kE8QMKgcQzFmQ:-Naa0xKL0K1lEGrBdqOS:b-6n41uy) ([raw file](https://github.com/starkware-libs/cairo/blob/b604a1a74782879140d4aada7c4abeb99b463be0/crates/cairo-lang-plugins/src/plugins/config.rs#L40)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I think there are some more that are needed, like ModuleBody, ImplBody, etc... Check in the cairo_spec.rs, or in parser test syntax files for example
</blockquote></details>

Oh, I misunderstood, nvm.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3786)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3786#-Naa11Al2O7nxaFj_v7D:-Naa11Al2O7nxaFj_v7E:b8djdve) ([raw file](https://github.com/starkware-libs/cairo/blob/b604a1a74782879140d4aada7c4abeb99b463be0/crates/cairo-lang-plugins/src/plugins/config.rs#L87)):*
> ```XML
> impl ConfigMacroHelper {
>     /// Traverse the syntax tree, accumulates the code without the dropped parts.
>     fn traverse(&mut self, db: &dyn SyntaxGroup, syntax_node: SyntaxNode) {
> ```

I think a simple solution is to add a whitelist of syntaxnodekind

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3786)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3786#-Naa11Al2O7nxaFj_v7D:-Naa1M3w8vDwt2SYSQmm:b-n3c0kt) ([raw file](https://github.com/starkware-libs/cairo/blob/b604a1a74782879140d4aada7c4abeb99b463be0/crates/cairo-lang-plugins/src/plugins/config.rs#L87)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I think a simple solution is to add a whitelist of syntaxnodekind
</blockquote></details>

where?
in the cases where we remove stuff - currently we have to traverse all the included data.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3786#-:-NaaEoLG8bDiW2SY1w5K:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
