### PR TITLE
Using disable_ap_tracking instead of revoke_ap_change.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #2292
- #2288
- #2273 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2273)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/program_generator.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2273#-NPM4daC6DS194VkkKC6:-NPM4daC6DS194VkkKC7:b-hl2sge) ([raw file](https://github.com/starkware-libs/cairo/blob/763b73b7ea1465ed66e52a2d077ddced9a8e5867/crates/cairo-lang-sierra-generator/src/program_generator.rs#L146)):*
> ```XML
>             // not occur.
>             if function.body.get(function.prolog_size)
>                 != Some(&simple_statement(revoke_ap_tracking_libfunc_id(db), &[], &[]))
> ```

why would a function start that way?
the user put it there manually?



_Code quote:_
```XML
            if function.body.get(function.prolog_size)
                != Some(&simple_statement(revoke_ap_tracking_libfunc_id(db), &[], &[]))
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/program_generator.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2273#-NPM4daC6DS194VkkKC6:-NPM4khC1u9Hc1Q-l12N:bwd38ub) ([raw file](https://github.com/starkware-libs/cairo/blob/763b73b7ea1465ed66e52a2d077ddced9a8e5867/crates/cairo-lang-sierra-generator/src/program_generator.rs#L146)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why would a function start that way?
the user put it there manually?


</blockquote></details>

This feels like a strange optimization for the case for the first instruction in the function is revoke_ap_tracking.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2273)* status: 0 of 20 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-generator/src/program_generator.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2273#-NPM4daC6DS194VkkKC6:-NPM4onj2OsAq8z1ViLe:bv4gvq1) ([raw file](https://github.com/starkware-libs/cairo/blob/763b73b7ea1465ed66e52a2d077ddced9a8e5867/crates/cairo-lang-sierra-generator/src/program_generator.rs#L146)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

This feels like a strange optimization for the case for the first instruction in the function is revoke_ap_tracking.
</blockquote></details>

yes - we are that user - at entry point - since i don't want any ap-alignment there.
this is the only place people actually do it (it is in the internal.cairo module)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/program_generator.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2273#-NPM4daC6DS194VkkKC6:-NPM5LHV6n6AmSgkNwKN:bf7gujy) ([raw file](https://github.com/starkware-libs/cairo/blob/763b73b7ea1465ed66e52a2d077ddced9a8e5867/crates/cairo-lang-sierra-generator/src/program_generator.rs#L146)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

yes - we are that user - at entry point - since i don't want any ap-alignment there.
this is the only place people actually do it (it is in the internal.cairo module)
</blockquote></details>

whats wrong with always adding disable_ap_tracking?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2273)* status: 0 of 20 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-generator/src/program_generator.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2273#-NPM4daC6DS194VkkKC6:-NPM5uoOBDT2wwAX0u7q:bvzlkls) ([raw file](https://github.com/starkware-libs/cairo/blob/763b73b7ea1465ed66e52a2d077ddced9a8e5867/crates/cairo-lang-sierra-generator/src/program_generator.rs#L146)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

whats wrong with always adding disable_ap_tracking?
</blockquote></details>

we need it revoked - not just disabled (previously the same libfunc was called twice in a row) - we can decide to just add it in this case.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 20 of 20 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2273)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/test_data/account.json` line 16523 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2273#-NPM6PpoBJqT55gtUvg8:-NPM6PpoBJqT55gtUvg9:b-kmixgw) ([raw file](https://github.com/starkware-libs/cairo/blob/cbfd85c16c3933b5941e5c1cb3b022b47b421079/crates/cairo-lang-starknet/test_data/account.json#L16523)):*
> ```JSON
>       [
>         0,
>         "felt"
> ```

Unrelated to this PR, but cas those be sequential now?



_Suggestion:_
```JSON
      [
        "felt",
        "Unit"
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/program_generator.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2273#-NPM4daC6DS194VkkKC6:-NPM6dxIAtA2ArJvYtUw:bwpkhpa) ([raw file](https://github.com/starkware-libs/cairo/blob/763b73b7ea1465ed66e52a2d077ddced9a8e5867/crates/cairo-lang-sierra-generator/src/program_generator.rs#L146)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

we need it revoked - not just disabled (previously the same libfunc was called twice in a row) - we can decide to just add it in this case.
</blockquote></details>

Here you are adding disable_ap_tracking only if the first statement is not revoke.
I'm asking if this condition is needed.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2273)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-generator/src/program_generator.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2273#-NPM4daC6DS194VkkKC6:-NPM6sAaCDF1MtTfJg5I:b-euy2am) ([raw file](https://github.com/starkware-libs/cairo/blob/763b73b7ea1465ed66e52a2d077ddced9a8e5867/crates/cairo-lang-sierra-generator/src/program_generator.rs#L146)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Here you are adding disable_ap_tracking only if the first statement is not revoke.
I'm asking if this condition is needed.
</blockquote></details>

not needed - just removes an extra line - that is not really needed (and before was the actual same line)

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2273#-:-NPM6ZkU7qW2FTU1589y:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-generator/src/program_generator.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2273#-NPM4daC6DS194VkkKC6:-NPM7AMG4UIrTn38GNyx:b6moguf) ([raw file](https://github.com/starkware-libs/cairo/blob/763b73b7ea1465ed66e52a2d077ddced9a8e5867/crates/cairo-lang-sierra-generator/src/program_generator.rs#L146)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

not needed - just removes an extra line - that is not really needed (and before was the actual same line)
</blockquote></details>

if the fist instruction is disable_ap_tracking you also don't need to add it.

Why didn't you do that optimization?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2273)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-sierra-generator/src/program_generator.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2273#-NPM4daC6DS194VkkKC6:-NPM7MyVCBBv1Om1DLyD:b-imwaae) ([raw file](https://github.com/starkware-libs/cairo/blob/763b73b7ea1465ed66e52a2d077ddced9a8e5867/crates/cairo-lang-sierra-generator/src/program_generator.rs#L146)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

if the fist instruction is disable_ap_tracking you also don't need to add it.

Why didn't you do that optimization?
</blockquote></details>

because no user code would ever create this - usercode can only create revoke.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2273)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/test_data/account.json` line 16523 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2273#-NPM6PpoBJqT55gtUvg8:-NPMaCCM9k7GrWKwHeF_:b-z6ti6p) ([raw file](https://github.com/starkware-libs/cairo/blob/cbfd85c16c3933b5941e5c1cb3b022b47b421079/crates/cairo-lang-starknet/test_data/account.json#L16523)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Unrelated to this PR, but cas those be sequential now?
</blockquote></details>

they seem sequential to me

**Review by ilyalesokhin-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2273)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by ilyalesokhin-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2273)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-sierra-generator/src/program_generator.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2273#-NPM4daC6DS194VkkKC6:-NPMboAb4ByrMQHbOXdD:b6lk69h) ([raw file](https://github.com/starkware-libs/cairo/blob/763b73b7ea1465ed66e52a2d077ddced9a8e5867/crates/cairo-lang-sierra-generator/src/program_generator.rs#L146)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

because no user code would ever create this - usercode can only create revoke.
</blockquote></details>

I put it as non-blocking, but I find it strange.

What if the second user instruction is revoke_ap_tracking?
is the code any diffrent.

**Review by ilyalesokhin-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2273)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/test_data/account.json` line 16523 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2273#-NPM6PpoBJqT55gtUvg8:-NPMc-ZS79hoBLYtSZrm:bjoc5ic) ([raw file](https://github.com/starkware-libs/cairo/blob/d5c56f12537b3f481cc8fc1cea9a11d863c7d232/crates/cairo-lang-starknet/test_data/account.json#L16523)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

they seem sequential to me
</blockquote></details>

I meant using the fact that they are sequential to remove the numbers.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2273)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-generator/src/program_generator.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2273#-NPM4daC6DS194VkkKC6:-NPMdTyP3oMQDZWQ2Xlc:b-sm70m1) ([raw file](https://github.com/starkware-libs/cairo/blob/763b73b7ea1465ed66e52a2d077ddced9a8e5867/crates/cairo-lang-sierra-generator/src/program_generator.rs#L146)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I put it as non-blocking, but I find it strange.

What if the second user instruction is revoke_ap_tracking?
is the code any diffrent.
</blockquote></details>

May add a pr moving the revoke to before the prologue - then would become irrelevant 
___
*[`crates/cairo-lang-starknet/test_data/account.json` line 16523 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2273#-NPM6PpoBJqT55gtUvg8:-NPMdH2i4NAPnFXji0Xx:bne34o0) ([raw file](https://github.com/starkware-libs/cairo/blob/d5c56f12537b3f481cc8fc1cea9a11d863c7d232/crates/cairo-lang-starknet/test_data/account.json#L16523)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I meant using the fact that they are sequential to remove the numbers.
</blockquote></details>

I guess we need to look at the generation of this to know.
But indeed, not related to the pr.

**Pull request merged**
