### PR TITLE
dean/improve array formatting #6448

### PR DESCRIPTION
**Pull request by dean-starkware**
feat: improve array formatting #6448

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 16 of 77 files at r1, 29 of 32 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6514)* status: 45 of 77 files reviewed, 1 unresolved discussion (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 73 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6514#-OACUM-H4ZKclHD8qQjU:-OACUM-H4ZKclHD8qQjV:b-w9t7dj) ([raw file](https://github.com/starkware-libs/cairo/blob/23483adba1bcd2b0f9cc782c4e3724234d8c1582/crates/cairo-lang-formatter/src/formatter_impl.rs#L73)):*
> ```XML
>     pub is_comma_broken: bool,
>     /// Indicates whether a comma should be added when the line breaks.
>     pub is_comma_broken: bool,
> ```

this seems to not compile.



_Code quote:_
```XML
    /// Indicates whether a comma should be added when the line breaks.
    pub is_comma_broken: bool,
    /// Indicates whether a comma should be added when the line breaks.
    pub is_comma_broken: bool,
```

**Review by dean-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6514)* status: 45 of 77 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 73 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6514#-OACUM-H4ZKclHD8qQjU:-OACsoae9HXEc7Z0kDlv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/23483adba1bcd2b0f9cc782c4e3724234d8c1582/crates/cairo-lang-formatter/src/formatter_impl.rs#L73)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this seems to not compile.
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6514)* status: 45 of 77 files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6514)* status: 45 of 77 files reviewed, 1 unresolved discussion (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/test_data/expected_results/linebreaking.cairo` line 266 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6514#-OADHSYvAiIpjES6NIJJ:-OADHSYw-N-SxeusTEGd:b-ujm2c2) ([raw file](https://github.com/starkware-libs/cairo/blob/32154205a93d71c6b373b74e414941e32bd43ea9/crates/cairo-lang-formatter/test_data/expected_results/linebreaking.cairo#L266)):*
> ```Cairo
>     let arr1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
>     let arr2 = [
>         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
> ```

this probably should have move to the next line with the previous `1`.



_Code quote:_
```Cairo
,
```

**Review by dean-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6514)* status: 45 of 77 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-formatter/test_data/expected_results/linebreaking.cairo` line 266 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6514#-OADHSYvAiIpjES6NIJJ:-OADO1b21OSmelWljHA_:b-uni64w) ([raw file](https://github.com/starkware-libs/cairo/blob/32154205a93d71c6b373b74e414941e32bd43ea9/crates/cairo-lang-formatter/test_data/expected_results/linebreaking.cairo#L266)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this probably should have move to the next line with the previous `1`.
</blockquote></details>

I don't understand what you are referring to.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6514)* status: 45 of 77 files reviewed, 1 unresolved discussion (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/test_data/expected_results/linebreaking.cairo` line 266 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6514#-OADHSYvAiIpjES6NIJJ:-OADPETC1cfiV9qu_LgP:bjmit4r) ([raw file](https://github.com/starkware-libs/cairo/blob/32154205a93d71c6b373b74e414941e32bd43ea9/crates/cairo-lang-formatter/test_data/expected_results/linebreaking.cairo#L266)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

I don't understand what you are referring to.
</blockquote></details>

The comma is char 101, so it should move to the next line.

**Pull request closed without merging**
