### PR TITLE
fix build with minimal-versions, add CI to prevent regression

### PR DESCRIPTION
**Pull request by 0xalpharush**
closes https://github.com/starkware-libs/cairo/issues/2583

I've bumped the `string_cache` dependency as this seems sufficient to avoid the issue. Additionally, I've add a step in the CI which builds cairo with `-Zminimal-versions` to ensure that the dependencies specified in the Cargo.toml are strict enough to facilitate building with the minimal versions

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2584)

### CODE REVIEW

**Comment by 0xalpharush** [comment]
Hm, pinning the version doesn't seem to work...

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2584)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @0xalpharush)

___
*[`Cargo.toml` line 92 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2584#-NRSFFQuEWwivR9lhayc:-NRSFFQv58QKgKyS6f05:bws613l) ([raw file](https://github.com/starkware-libs/cairo/blob/3663f0ddfeec35a29a556ff0a7ceddc83ef1df8f/Cargo.toml#L92)):*
> ```TOML
> unescaper = "0.1.1"
> xshell = "0.2.2"
> string_cache = "0.8.4"
> ```

Add a newline

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2584)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @0xalpharush)

___
*[`.github/workflows/ci.yml` line 101 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2584#-NRSFHOV0YBgPwRpGz3R:-NRSFHOV0YBgPwRpGz3S:brdkquc) ([raw file](https://github.com/starkware-libs/cairo/blob/3663f0ddfeec35a29a556ff0a7ceddc83ef1df8f/.github/workflows/ci.yml#L101)):*
> ```YAML
>       - run: >
>           scripts/docs.sh
>           
> ```

Remove extra whitespace

**Comment by spapinistarkware** [comment]
Closing, since this doesnt seem to work

**Pull request closed without merging**
