### PR TITLE
Add Event derive

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2873)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2873** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2873" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2873?utm_source=stack-comment).

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 10 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2873)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`corelib/src/starknet/event.cairo` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2873#-NTNP8TjAKvLe70Jd547:-NTNP8TjAKvLe70Jd548:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/b13e2b2b369525fcfc176cec29efbe61fad5bd17/corelib/src/starknet/event.cairo#L3)):*
> ```Cairo
> use serde::Serde;
> 
> trait Event<T> {
> ```

?



_Suggestion:_
```Cairo
trait Event<T> {
    fn append_keys_and_values(self: T, ref keys: Array<felt252>, ref values: Array<felt252>);
    // TODO(spapini): Add a "deserialize" function meant for viewing the event.
}
```
___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2873#-NTNSCXC8bjtMPuQXUn2:-NTNSCXC8bjtMPuQXUn3:bx8mo7x) ([raw file](https://github.com/starkware-libs/cairo/blob/b13e2b2b369525fcfc176cec29efbe61fad5bd17/crates/cairo-lang-starknet/src/plugin/events.rs#L109)):*
> ```XML
>         let attr = attr.structurize(db);
>         let [arg] = &attr.args[..] else { return false; };
>         let AttributeArg{
> ```

extract to func and fix.



_Code quote:_
```XML
    if !enum_ast.query_attr(db, "derive").into_iter().any(|attr| {
        let attr = attr.structurize(db);
        let [arg] = &attr.args[..] else { return false; };
        let AttributeArg{
            variant: AttributeArgVariant::Unnamed {
                value: ast::Expr::Path(path),
                ..
            },
            ..
        } = arg else {
            return false;
        };
        path.as_syntax_node().get_text(db) == "starknet::Event"
    }) {
        return PluginResult::default();
    }
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2873)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/starknet/event.cairo` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2873#-NTNP8TjAKvLe70Jd547:-NTNUmbf4MXW_ITS_Kzz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b13e2b2b369525fcfc176cec29efbe61fad5bd17/corelib/src/starknet/event.cairo#L3)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2873#-NTNSCXC8bjtMPuQXUn2:-NTNUW3P6eZeUuKV89Si:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b13e2b2b369525fcfc176cec29efbe61fad5bd17/crates/cairo-lang-starknet/src/plugin/events.rs#L109)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

extract to func and fix.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2873)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2873#-NTN_9TKAdA-3FhvsxSF:-NTN_9TKAdA-3FhvsxSG:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7160d9ae5afcff9f5dc021a139df3924cb1cf872/crates/cairo-lang-starknet/src/plugin/events.rs#L163)):*
> ```XML
> 
> /// Returns true if the type should be derived as an event.
> fn derive_event_needed<T: QueryAttrs>(with_attrs: &T, db: &dyn SyntaxGroup) -> bool {
> ```





_Suggestion:_
```XML
/// Returns true if the type should be derived as an event.
fn derive_event_needed<T: QueryAttrs>(with_attrs: &T, db: &dyn SyntaxGroup) -> bool {
    with_attrs.query_attr(db, "derive").into_iter().any(|attr| {
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2873)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 131 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2873#-NTN_qax7a4kmrqz5iRA:-NTN_qax7a4kmrqz5iRB:b-nue06j) ([raw file](https://github.com/starkware-libs/cairo/blob/7160d9ae5afcff9f5dc021a139df3924cb1cf872/crates/cairo-lang-starknet/src/plugin/events.rs#L131)):*
> ```XML
>     let event_impl = RewriteNode::interpolate_patched(
>         "
> impl $enum_name$IsEvent of starknet::Event<$enum_name$> {
> ```

use `indoc` to remove the extra generated whitespace



_Suggestion:_
```XML
    // Add an implementation for `Event<StructName>`.
    let event_impl = RewriteNode::interpolate_patched(
"
impl $enum_name$IsEvent of starknet::Event<$enum_name$> {
    fn append_keys_and_values(
        self: $enum_name$, ref keys: Array<felt252>, ref values: Array<felt252>
    ) {
        match self {
            $append_variants$
        }
    }
}
",
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2873)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 131 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2873#-NTN_qax7a4kmrqz5iRA:-NTNcRkRBBTXCoTqJGGV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7160d9ae5afcff9f5dc021a139df3924cb1cf872/crates/cairo-lang-starknet/src/plugin/events.rs#L131)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

use `indoc` to remove the extra generated whitespace
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2873#-NTN_9TKAdA-3FhvsxSF:-NTNcRI0-0rlgAWQ1Ph2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7160d9ae5afcff9f5dc021a139df3924cb1cf872/crates/cairo-lang-starknet/src/plugin/events.rs#L163)):*
> ```XML
> 
> /// Returns true if the type should be derived as an event.
> fn derive_event_needed<T: QueryAttrs>(with_attrs: &T, db: &dyn SyntaxGroup) -> bool {
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2873)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 58 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2873#-NTNgTUZDaHigCoPxmSd:-NTNgTUZDaHigCoPxmSe:b-2pzw2e) ([raw file](https://github.com/starkware-libs/cairo/blob/2231185fbb4430b128f4d21a660243fc56dd5c2e/crates/cairo-lang-starknet/src/plugin/events.rs#L58)):*
> ```XML
>     let struct_name = RewriteNode::new_trimmed(struct_ast.name(db).as_syntax_node());
>     let event_impl = RewriteNode::interpolate_patched(
>         "
> ```

indoc as well
___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 118 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2873#-NTNgjKg4V70VImZbQs2:-NTNgjKg4V70VImZbQs3:b-a66ymm) ([raw file](https://github.com/starkware-libs/cairo/blob/2231185fbb4430b128f4d21a660243fc56dd5c2e/crates/cairo-lang-starknet/src/plugin/events.rs#L118)):*
> ```XML
>                 starknet::Event::append_keys_and_values(val, ref keys, ref values);
>             },
>             ",
> ```

I think this line should be deleted to prevent the whitespace

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2873)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 58 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2873#-NTNgTUZDaHigCoPxmSd:-NTNjOB99_h7KFODXSBm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2231185fbb4430b128f4d21a660243fc56dd5c2e/crates/cairo-lang-starknet/src/plugin/events.rs#L58)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

indoc as well
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 118 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2873#-NTNgjKg4V70VImZbQs2:-NTNmtJhD8hm5MMXu026:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2231185fbb4430b128f4d21a660243fc56dd5c2e/crates/cairo-lang-starknet/src/plugin/events.rs#L118)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I think this line should be deleted to prevent the whitespace 
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2873#-:-NTNnGPr4EFEI1Vw3YwM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
