### PR TITLE
Matching branch merge by introduction point.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #2423
- #2421 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2421)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2421)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/references.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2421#-NQ4Z3gFDlZYWL7EltTX:-NQ4Z3gFDlZYWL7EltTY:b-75ywm7) ([raw file](https://github.com/starkware-libs/cairo/blob/bb3fa7f2da3e5d30b87eef1f724dd256d521cd57/crates/cairo-lang-sierra-to-casm/src/references.rs#L35)):*
> ```XML
>     pub stack_idx: Option<usize>,
>     /// The statememt and output index where the value was introduced.
>     /// Statement may be None if it is to be populated later.
> ```

why is this needed?



_Code quote:_
```XML
 /// Statement may be None if it is to be populated later.
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2421)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/references.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2421#-NQ4_fzT2K7ocY1DEW3v:-NQ4_fzT2K7ocY1DEW3w:b6ezefb) ([raw file](https://github.com/starkware-libs/cairo/blob/bb3fa7f2da3e5d30b87eef1f724dd256d521cd57/crates/cairo-lang-sierra-to-casm/src/references.rs#L36)):*
> ```XML
>     /// The statememt and output index where the value was introduced.
>     /// Statement may be None if it is to be populated later.
>     pub introduction_point: (Option<StatementIdx>, usize),
> ```

why os the param_idx needed?



_Code quote:_
```XML
 usize
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-to-casm/src/references.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2421#-NQ4Z3gFDlZYWL7EltTX:-NQ4_y0q3e0UUEh72rTD:b-5j681q) ([raw file](https://github.com/starkware-libs/cairo/blob/bb3fa7f2da3e5d30b87eef1f724dd256d521cd57/crates/cairo-lang-sierra-to-casm/src/references.rs#L35)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why is this needed?
</blockquote></details>

Ok, I guess you need to return  introduction_point in branch_changes to handle OutputVarReferenceInfo::SameAsParamOk 



_Code quote (from crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs):_
```XML
 OutputVarReferenceInfo::SameAsParam
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2421)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/references.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2421#-NQ4Z3gFDlZYWL7EltTX:-NQ4dhrb46HnoqaOoX1D:bo6ap9y) ([raw file](https://github.com/starkware-libs/cairo/blob/bb3fa7f2da3e5d30b87eef1f724dd256d521cd57/crates/cairo-lang-sierra-to-casm/src/references.rs#L35)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Ok, I guess you need to return  introduction_point in branch_changes to handle OutputVarReferenceInfo::SameAsParamOk 
</blockquote></details>

Indeed 
___
*[`crates/cairo-lang-sierra-to-casm/src/references.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2421#-NQ4_fzT2K7ocY1DEW3v:-NQ4d78HCGu2wXCkwDYl:b-8ebmia) ([raw file](https://github.com/starkware-libs/cairo/blob/bb3fa7f2da3e5d30b87eef1f724dd256d521cd57/crates/cairo-lang-sierra-to-casm/src/references.rs#L36)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why os the param_idx needed?
</blockquote></details>

Otherwise if I have a struct of two unit types, and I deconstruct it, I may rename one in one branch, and the second in the other, and they would be mergable (and if they become of non-zero size later it would break, since they won't point to the same expression - including the index solves this)

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2421)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2421#-NQ546Ep6-CHY_tDmevq:-NQ546Ep6-CHY_tDmevr:b-k8k7ob) ([raw file](https://github.com/starkware-libs/cairo/blob/bb3fa7f2da3e5d30b87eef1f724dd256d521cd57/crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs#L155)):*
> ```XML
>                             (None, output_idx)
>                         };
>                     ReferenceValue { expression, ty: ty.clone(), stack_idx, introduction_point }
> ```

Can you use a different type here?

and make the introduction_point in  ReferenceValue non-optional?



_Code quote:_
```XML
 ReferenceValue { expression, ty: ty.clone(), stack_idx, introduction_point }
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2421)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2421#-NQ546Ep6-CHY_tDmevq:-NQ60JXGCsOkcX_y_pc6:b68hpt) ([raw file](https://github.com/starkware-libs/cairo/blob/bb3fa7f2da3e5d30b87eef1f724dd256d521cd57/crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs#L155)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Can you use a different type here?

and make the introduction_point in  ReferenceValue non-optional?
</blockquote></details>

Everything here recursively use the same type, so this won't be simple.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2421)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2421#-NQ546Ep6-CHY_tDmevq:-NQ6A6gECWZizyxZbzIw:btzmcrf) ([raw file](https://github.com/starkware-libs/cairo/blob/bb3fa7f2da3e5d30b87eef1f724dd256d521cd57/crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs#L155)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Everything here recursively use the same type, so this won't be simple.
</blockquote></details>

it is not that hard:
https://github.com/starkware-libs/cairo/commit/bb3fa7f2da3e5d30b87eef1f724dd256d521cd57

just need to come up with a better name.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2421)* status: 1 of 7 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2421#-NQ546Ep6-CHY_tDmevq:-NQ6ARzc7N3KBRQn5JBn:bm6f37w) ([raw file](https://github.com/starkware-libs/cairo/blob/bb3fa7f2da3e5d30b87eef1f724dd256d521cd57/crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs#L155)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it is not that hard:
https://github.com/starkware-libs/cairo/commit/bb3fa7f2da3e5d30b87eef1f724dd256d521cd57

just need to come up with a better name.
</blockquote></details>

sorry:
https://github.com/starkware-libs/cairo/commit/6840bac34d2e46868a5d9cad2c467f5e93c6df9f

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2421)* status: 1 of 8 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/references.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2421#-NQ4_fzT2K7ocY1DEW3v:-NQ6reg3C0D1o3RhtcLM:bj67hiv) ([raw file](https://github.com/starkware-libs/cairo/blob/bb3fa7f2da3e5d30b87eef1f724dd256d521cd57/crates/cairo-lang-sierra-to-casm/src/references.rs#L36)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Otherwise if I have a struct of two unit types, and I deconstruct it, I may rename one in one branch, and the second in the other, and they would be mergable (and if they become of non-zero size later it would break, since they won't point to the same expression - including the index solves this)
</blockquote></details>

added test
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2421#-NQ546Ep6-CHY_tDmevq:-NQ6rd6g3WigvOXsvgtl:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bb3fa7f2da3e5d30b87eef1f724dd256d521cd57/crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs#L155)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

sorry:
https://github.com/starkware-libs/cairo/commit/6840bac34d2e46868a5d9cad2c467f5e93c6df9f
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-to-casm/src/references.rs` line 60 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2421#-NQJXWs_5PPhcBlcF70G:-NQJXWs_5PPhcBlcF70H:b-3kbmxd) ([raw file](https://github.com/starkware-libs/cairo/blob/ab4349324e2251f02415b5a2a58a4d406c9211e9/crates/cairo-lang-sierra-to-casm/src/references.rs#L60)):*
> ```XML
> }
> 
> /// The
> ```

fix comment



_Code quote:_
```XML
/// The
```

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r1, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2421#-:-NQJXlJ89TRkCdh9att-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2421)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/references.rs` line 60 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2421#-NQJXWs_5PPhcBlcF70G:-NQKIF62-bxBEQ8gDzcn:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ab4349324e2251f02415b5a2a58a4d406c9211e9/crates/cairo-lang-sierra-to-casm/src/references.rs#L60)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

fix comment
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-to-casm/src/references.rs` line 60 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2421#-NQJXWs_5PPhcBlcF70G:-NQL-C3t4SEGI0FNu4y-:b-p04q62) ([raw file](https://github.com/starkware-libs/cairo/blob/ab4349324e2251f02415b5a2a58a4d406c9211e9/crates/cairo-lang-sierra-to-casm/src/references.rs#L60)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't understand your comment.

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2421)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/references.rs` line 60 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2421#-NQJXWs_5PPhcBlcF70G:-NQL-QeBBcTTmJy2GWXM:bvqm3ih) ([raw file](https://github.com/starkware-libs/cairo/blob/ab4349324e2251f02415b5a2a58a4d406c9211e9/crates/cairo-lang-sierra-to-casm/src/references.rs#L60)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't understand your comment.
</blockquote></details>

Add `Similar to IntroductionPoint, but the statement idx might not be assigned yet.`

**Pull request merged**
