### PR TITLE
Improved match tests for or patterns

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4609)

### CODE REVIEW

**Comment by yuvalsw** [comment]
change target branch

**Review by TomerStarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4609)* status: all files reviewed, 1 unresolved discussion

**Review by TomerStarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4609#-:-Nm3MCpP-CsB4k2u1Vz9:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4609#-:-Nm4tL2e9AJMCmwXeyXj:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

**Pull request merged**
