### PR TITLE
Fixed issue 4038. Properly finding required ap tracking config.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4070)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/ap_tracking.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4070#-NeIdFP-8jBF6SG8sCzK:-NeIdFP-8jBF6SG8sCzL:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8785f0ae47c72cf39cd1d4a8d7389e9e7dec4995/crates/cairo-lang-sierra-generator/src/ap_tracking.rs#L151)):*
> ```XML
> 
>         // If we have a variable the lives after a converges then we need to enable ap tracking
>         // Otherwise we can disable ap tracking.
> ```





_Suggestion:_
```XML
        // If we have a variable the lives in more then one arm we need to enable ap tracking
        // If there are no variables of interest in any of the arms, we can disable ap tracking.
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4070)* status: 1 of 12 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/ap_tracking.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4070#-NeIcYlW1-fOzUe3AC2K:-NeIcYlW1-fOzUe3AC2L:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/8785f0ae47c72cf39cd1d4a8d7389e9e7dec4995/crates/cairo-lang-sierra-generator/src/ap_tracking.rs#L64)):*
> ```XML
> struct ApTrackingAnalysisInfo {
>     /// A mapping from variables to the blocks where they are used.
>     /// The block are sorted in reverse order.
> ```

remove



_Code quote:_
```XML
  /// The block are sorted in reverse order.
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4070)* status: 1 of 12 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/ap_tracking.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4070#-NeIcYlW1-fOzUe3AC2K:-NeIh2s24jfULHdxsvIS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8785f0ae47c72cf39cd1d4a8d7389e9e7dec4995/crates/cairo-lang-sierra-generator/src/ap_tracking.rs#L64)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4070)* status: 1 of 12 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/ap_tracking.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4070#-NeIdFP-8jBF6SG8sCzK:-NeIqR1m5ExxX9Moz3TM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8785f0ae47c72cf39cd1d4a8d7389e9e7dec4995/crates/cairo-lang-sierra-generator/src/ap_tracking.rs#L151)):*
> ```XML
> 
>         // If we have a variable the lives after a converges then we need to enable ap tracking
>         // Otherwise we can disable ap tracking.
> ```

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4070)* status: 2 of 12 files reviewed, all discussions resolved

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 10 of 12 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4070#-:-NeSgAi39MU7ZEFzjsVm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
