### PR TITLE
LS: Expand Macro command server side

### PR DESCRIPTION
**Pull request by Draggu**
**Stack**:
- #6076
- #6075 ⬅
- #6074

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6075)

### CODE REVIEW

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6075)* status: 2 of 7 files reviewed, 4 unresolved discussions (waiting on @Draggu and @orizi)

___
*[`crates/cairo-lang-language-server/src/lang/db/syntax.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O2iNOX87robRqZs5Lhi:-O2iNOX87robRqZs5Lhj:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a39d33ac00f9b152eb90ae068b6522b4f49943ab/crates/cairo-lang-language-server/src/lang/db/syntax.rs#L57)):*
> ```XML
>     /// Traverse tree in root direction
>     /// Finds first node with specified kind
>     /// Returns it's respective child
> ```





_Suggestion:_
```XML
    /// Traverse tree in root direction.
    ///
    /// Finds first node with specified kind.
    /// Returns it's respective child that is the parent of `node`.
```
___
*[`crates/cairo-lang-language-server/src/lsp/ext.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O2iNKzC8yqqXp6sf3JN:-O2iNKzC8yqqXp6sf3JO:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/a39d33ac00f9b152eb90ae068b6522b4f49943ab/crates/cairo-lang-language-server/src/lsp/ext.rs#L16)):*
> ```XML
> }
> 
> pub struct ExpandMacro;
> ```

doc
___
*[`crates/cairo-lang-language-server/src/lsp/ext.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O2iMym65zFOlDzMgJCh:-O2iMym65zFOlDzMgJCi:bxipf99) ([raw file](https://github.com/starkware-libs/cairo/blob/a39d33ac00f9b152eb90ae068b6522b4f49943ab/crates/cairo-lang-language-server/src/lsp/ext.rs#L19)):*
> ```XML
> 
> #[derive(Serialize, Deserialize)]
> ```

unnecessary empty lines
___
*[`crates/cairo-lang-language-server/src/lsp/ext.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O2iN3hN7h1hJq2cSS0s:-O2iN3hN7h1hJq2cSS0t:b-5m8kz9) ([raw file](https://github.com/starkware-libs/cairo/blob/a39d33ac00f9b152eb90ae068b6522b4f49943ab/crates/cairo-lang-language-server/src/lsp/ext.rs#L21)):*
> ```XML
> 
> pub struct TextDocument {
>     pub uri: Url,
> ```

please reuse `lsp_types` for this and `Position`

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6075)* status: 2 of 7 files reviewed, 5 unresolved discussions (waiting on @Draggu and @orizi)

___
*[`crates/cairo-lang-language-server/src/lang/inspect/macros.rs` line 144 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O2i_YtR1WF6nqccmA82:-O2i_YtSCZJYz0Dwpbzj:brblc6o) ([raw file](https://github.com/starkware-libs/cairo/blob/a39d33ac00f9b152eb90ae068b6522b4f49943ab/crates/cairo-lang-language-server/src/lang/inspect/macros.rs#L144)):*
> ```XML
> }
> 
> pub fn expand_macro(db: &AnalysisDatabase, params: &ExpandMacroParams) -> Option<String> {
> ```

please try to put public stuff at the top of the file

**Review by mkaput — COMMENTED** [review]
Looks amazing

> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6075#-:-O2id6e_0u6gpEKqteVh:b-elzjmc)* status: 2 of 7 files reviewed, 5 unresolved discussions (waiting on @Draggu and @orizi)

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6075)* status: all files reviewed, 6 unresolved discussions (waiting on @Draggu and @orizi)

___
*[`crates/cairo-lang-language-server/src/lang/inspect/macros.rs` line 131 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O2idaMTDDHLOt0KG5K2:-O2idaMTDDHLOt0KG5K3:bmf6udh) ([raw file](https://github.com/starkware-libs/cairo/blob/1805eea2291b47f4b9563ea7a298fbfd9dc1a53b/crates/cairo-lang-language-server/src/lang/inspect/macros.rs#L131)):*
> ```XML
> 
>         output.push_str(&file_content);
>         output.push_str("\n\n// ------------\n\n");
> ```

can you please avoid this for the last item in the output?

the easiest would be to collect all chunks into a vec and then call `join` on this

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6075)* status: all files reviewed, 10 unresolved discussions (waiting on @Draggu)

___
*[`crates/cairo-lang-language-server/src/lang/inspect/macros.rs` line 22 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O2j9u8JCnd4YaOzRAfs:-O2j9u8JCnd4YaOzRAft:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/1805eea2291b47f4b9563ea7a298fbfd9dc1a53b/crates/cairo-lang-language-server/src/lang/inspect/macros.rs#L22)):*
> ```XML
> use crate::lsp::ext::ExpandMacroParams;
> 
> fn expanded_macro_files(
> ```

doc
___
*[`crates/cairo-lang-language-server/src/lang/inspect/macros.rs` line 67 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O2j9vc23GDhqdQYk-xU:-O2j9vc23GDhqdQYk-xV:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/1805eea2291b47f4b9563ea7a298fbfd9dc1a53b/crates/cairo-lang-language-server/src/lang/inspect/macros.rs#L67)):*
> ```XML
> }
> 
> fn expand_inline_macros(db: &AnalysisDatabase, node: SyntaxNode) -> Option<String> {
> ```

doc
___
*[`crates/cairo-lang-language-server/src/lang/inspect/macros.rs` line 111 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O2jA1rWBPXbpoU_EPAh:-O2jA1rWBPXbpoU_EPAi:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/1805eea2291b47f4b9563ea7a298fbfd9dc1a53b/crates/cairo-lang-language-server/src/lang/inspect/macros.rs#L111)):*
> ```XML
>         let mut file_content = db.file_content(file)?.to_string();
> 
>         // iterate in reversed order so positions are not affected by inlining
> ```





_Suggestion:_
```XML
        // Iterate in reversed order so positions are not affected by inlining.
```
___
*[`crates/cairo-lang-language-server/src/lang/inspect/macros.rs` line 142 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O2jA8sI-7FOluRKv8Zz:-O2jA8sI-7FOluRKv8_-:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/1805eea2291b47f4b9563ea7a298fbfd9dc1a53b/crates/cairo-lang-language-server/src/lang/inspect/macros.rs#L142)):*
> ```XML
> }
> 
> pub fn expand_macro(db: &AnalysisDatabase, params: &ExpandMacroParams) -> Option<String> {
> ```

doc

**Review by mkaput — COMMENTED** [review]
> Reviewed 7 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6075)* status: 9 of 10 files reviewed, 4 unresolved discussions (waiting on @Draggu and @orizi)

**Review by Draggu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6075)* status: all files reviewed, 5 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-language-server/src/ide/macros/expand.rs` line 45 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O3Dmndu2yWiUFnBj56p:-O3HSoHa19sa-8vszOoV:b-hh04sv) ([raw file](https://github.com/starkware-libs/cairo/blob/47709ef03befd470218f7ba3d3e4957453277e05/crates/cairo-lang-language-server/src/ide/macros/expand.rs#L45)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Please extract this part into separate function to make `expand_macro` smaller. My name suggestion:

```rust
fn build_synthetic_macro_plugin_metadata(...) -> MacroPluginMetadata
```
</blockquote></details>

Because of `MacroPluginMetadata` signature

```rs
pub struct MacroPluginMetadata<'a> {
```

We can extract at most `cfg_set` and `edition` to separate function while `metadata` have to be created here.
I'm not sure if it is worth doing this.
___
*[`crates/cairo-lang-language-server/src/lang/inspect/macros.rs` line 22 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O2j9u8JCnd4YaOzRAfs:-O3HTTtL7cM7XKRcxbjo:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1805eea2291b47f4b9563ea7a298fbfd9dc1a53b/crates/cairo-lang-language-server/src/lang/inspect/macros.rs#L22)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lang/inspect/macros.rs` line 67 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O2j9vc23GDhqdQYk-xU:-O3HTU6A0xWpDyDSKkD2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1805eea2291b47f4b9563ea7a298fbfd9dc1a53b/crates/cairo-lang-language-server/src/lang/inspect/macros.rs#L67)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lang/inspect/macros.rs` line 111 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O2jA1rWBPXbpoU_EPAh:-O3HTUVL8LJf4snqDDPD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1805eea2291b47f4b9563ea7a298fbfd9dc1a53b/crates/cairo-lang-language-server/src/lang/inspect/macros.rs#L111)):*
> ```XML
>         let mut file_content = db.file_content(file)?.to_string();
> 
>         // iterate in reversed order so positions are not affected by inlining
> ```

Done.
___
*[`crates/cairo-lang-language-server/src/lang/inspect/macros.rs` line 142 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O2jA8sI-7FOluRKv8Zz:-O3HTUqg5MouRZqcJoJI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1805eea2291b47f4b9563ea7a298fbfd9dc1a53b/crates/cairo-lang-language-server/src/lang/inspect/macros.rs#L142)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by mkaput — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6075#-:-O3HW7fvA2YmjH544YEh:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-language-server/src/ide/macros/expand.rs` line 45 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O3Dmndu2yWiUFnBj56p:-O3HW18cDT7Yx6Ha7nPk:bjihj2t) ([raw file](https://github.com/starkware-libs/cairo/blob/47709ef03befd470218f7ba3d3e4957453277e05/crates/cairo-lang-language-server/src/ide/macros/expand.rs#L45)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

Because of `MacroPluginMetadata` signature

```rs
pub struct MacroPluginMetadata<'a> {
```

We can extract at most `cfg_set` and `edition` to separate function while `metadata` have to be created here.
I'm not sure if it is worth doing this.
</blockquote></details>

oh that's unfortunate :( leave this as-is then

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6075)* status: all files reviewed, 5 unresolved discussions (waiting on @Draggu and @orizi)

___
*[`crates/cairo-lang-language-server/src/ide/macros/expand.rs` line 325 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O3IZ7D-3270ePpqt4S-:-O3IZ7D-3270ePpqt4S0:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/22468c935d6ca8a8d7dae0e6e186dee46536e13d/crates/cairo-lang-language-server/src/ide/macros/expand.rs#L325)):*
> ```XML
>             output.push_str("\n\n");
>         }
>     }
> ```





_Suggestion:_
```XML
    output.push_str(file_content.trim_end_matches('\n'));
    output.push_str("\n\n");
```

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6075#-:-O3Ii2E-B0QIZtjtpyVX:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r3, 7 of 8 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6075)* status: all files reviewed, 2 unresolved discussions (waiting on @Draggu)

___
*[`crates/cairo-lang-language-server/src/ide/macros/expand.rs` line 123 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O3R3diq4d-uV-2VmDkd:-O3R3diq4d-uV-2VmDke:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/bf78faa583c0032b95342d32846987688683bb28/crates/cairo-lang-language-server/src/ide/macros/expand.rs#L123)):*
> ```XML
>                 }
>             }
>         }
> ```





_Suggestion:_
```XML
        for item_ast in item_asts {
            for plugin in db.macro_plugins() {
                let result = plugin.generate_code(db.upcast(), item_ast.clone(), metadata);

                if let Some(generated) = result.code {
                    let new_file = FileLongId::Virtual(VirtualFile {
                        parent: Some(module_file),
                        name: generated.name,
                        content: generated.content.into(),
                        code_mappings: Default::default(),
                        kind: FileKind::Module,
                    })
                    .intern(db);

                    module_queue.push_back((
                        new_file,
                        db.file_module_syntax(new_file)
                            .ok()?
                            .items(syntax_db)
                            .elements(db.upcast()),
                    ));
                }
                if result.remove_original_item {
                    break;
                }
            }
        }
```
___
*[`crates/cairo-lang-language-server/src/ide/macros/expand.rs` line 132 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O3R3mJQ33HlAMiEBuFD:-O3R3mJQ33HlAMiEBuFE:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/bf78faa583c0032b95342d32846987688683bb28/crates/cairo-lang-language-server/src/ide/macros/expand.rs#L132)):*
> ```XML
> fn count_depth(node: SyntaxNode) -> usize {
>     std::iter::successors(Some(node), SyntaxNode::parent).count()
> }
> ```





_Suggestion:_
```XML
/// Finds the depth of the node in tree.
fn node_depth(node: SyntaxNode) -> usize {
    std::iter::successors(Some(node), SyntaxNode::parent).count()
}
```

**Review by Draggu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6075)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/macros/expand.rs` line 123 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O3R3diq4d-uV-2VmDkd:-O3WuZ_j85T4XmKCWB30:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bf78faa583c0032b95342d32846987688683bb28/crates/cairo-lang-language-server/src/ide/macros/expand.rs#L123)):*
> ```XML
>                 }
>             }
>         }
> ```

Done.
___
*[`crates/cairo-lang-language-server/src/ide/macros/expand.rs` line 132 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O3R3mJQ33HlAMiEBuFD:-O3WuZyjBUG4LqUxC5Fo:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bf78faa583c0032b95342d32846987688683bb28/crates/cairo-lang-language-server/src/ide/macros/expand.rs#L132)):*
> ```XML
> fn count_depth(node: SyntaxNode) -> usize {
>     std::iter::successors(Some(node), SyntaxNode::parent).count()
> }
> ```

Done.

**Review by mkaput — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6075)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @orizi, and @piotmag769)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6075#-:-O3X1EOuEpnFICz-0P7P:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @piotmag769)

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6075)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @piotmag769)

**Review by Arcticae — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r3, 7 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6075)* status: all files reviewed, 7 unresolved discussions (waiting on @Draggu and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/macros/expand.rs` line 25 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O3bhU3e0-wH2144cxkx:-O3bhU3e0-wH2144cxky:b-uoqyag) ([raw file](https://github.com/starkware-libs/cairo/blob/7d0ed10199a9f62e039eeddba8d274a224879f40/crates/cairo-lang-language-server/src/ide/macros/expand.rs#L25)):*
> ```XML
> 
> /// Tries to expand macro, returns it as string.
> pub fn expand_macro(db: &AnalysisDatabase, params: &TextDocumentPositionParams) -> Option<String> {
> ```

I am generally lacking clear flow here, a few sentences of documentation would make this file much easier to understand what algorithm you're implementing here 
___
*[`crates/cairo-lang-language-server/src/ide/macros/expand.rs` line 181 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O3bh89p9QtKjN-pVNJo:-O3bh89p9QtKjN-pVNJp:b-sx9qs4) ([raw file](https://github.com/starkware-libs/cairo/blob/7d0ed10199a9f62e039eeddba8d274a224879f40/crates/cairo-lang-language-server/src/ide/macros/expand.rs#L181)):*
> ```XML
> 
> /// Formats output string.
> fn format_output(output: &str, is_inline_macro: bool) -> String {
> ```

Perhaps we could refactor this so we don't have the boolean flag here
___
*[`crates/cairo-lang-language-server/src/ide/macros/expand.rs` line 214 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O3bgmYNDvL_mxIkaD9E:-O3bgmYNDvL_mxIkaD9F:b-s1sp05) ([raw file](https://github.com/starkware-libs/cairo/blob/7d0ed10199a9f62e039eeddba8d274a224879f40/crates/cairo-lang-language-server/src/ide/macros/expand.rs#L214)):*
> ```XML
> 
> impl FileProcessorConfig {
>     /// Config for main file.
> ```

I lack some explanation here for this class and different use cases
___
*[`crates/cairo-lang-language-server/src/ide/macros/expand.rs` line 236 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O3bgiDYCC3TogRYfL7G:-O3bgiDYCC3TogRYfL7H:b-kp1x60) ([raw file](https://github.com/starkware-libs/cairo/blob/7d0ed10199a9f62e039eeddba8d274a224879f40/crates/cairo-lang-language-server/src/ide/macros/expand.rs#L236)):*
> ```XML
>     }
> 
>     /// Config for generated files.
> ```

Not really useful comment
___
*[`crates/cairo-lang-language-server/src/ide/macros/expand.rs` line 253 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O3bg23nAZzchiyA0TlU:-O3bg23nAZzchiyA0TlV:b-35cu1f) ([raw file](https://github.com/starkware-libs/cairo/blob/7d0ed10199a9f62e039eeddba8d274a224879f40/crates/cairo-lang-language-server/src/ide/macros/expand.rs#L253)):*
> ```XML
> /// Inlines macros in single file, pushes new inlined file if any macro was inlined, otherwise
> /// pushes output string.
> fn process_file(
> ```

This function does too many things for my taste, also the lack of proper naming indicates that 
___
*[`crates/cairo-lang-language-server/src/ide/macros/expand.rs` line 300 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O3bgGoO42webE8i_p2f:-O3bgGoO42webE8i_p2g:b-aa4342) ([raw file](https://github.com/starkware-libs/cairo/blob/7d0ed10199a9f62e039eeddba8d274a224879f40/crates/cairo-lang-language-server/src/ide/macros/expand.rs#L300)):*
> ```XML
> 
> /// Extends output with single file.
> fn push_file_content(db: &AnalysisDatabase, file: FileId, file_content: &str, output: &mut String) {
> ```

Naming does not indicate what really happens here
___
*[`crates/cairo-lang-language-server/src/lang/db/syntax.rs` line 59 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O3bfg2J-XvVPkTq_qU4:-O3bfg2J-XvVPkTq_qU5:b-gof08) ([raw file](https://github.com/starkware-libs/cairo/blob/7d0ed10199a9f62e039eeddba8d274a224879f40/crates/cairo-lang-language-server/src/lang/db/syntax.rs#L59)):*
> ```XML
>     /// Finds first node with specified kind.
>     /// Returns it's respective child that is the ancestor of `node`.
>     fn first_ancestor_of_kind_respective_child(
> ```

This name is confusing to me 
I think it'd be better if we just got the ancestor and then called `.parent()` on it

**Review by Draggu — COMMENTED** [review]
> Dismissed @Arcticae from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6075)* status: all files reviewed, 6 unresolved discussions (waiting on @Arcticae and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/macros/expand.rs` line 25 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O3bhU3e0-wH2144cxkx:-O3hUfu13xydg0ZRCOPf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7d0ed10199a9f62e039eeddba8d274a224879f40/crates/cairo-lang-language-server/src/ide/macros/expand.rs#L25)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

I am generally lacking clear flow here, a few sentences of documentation would make this file much easier to understand what algorithm you're implementing here
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/ide/macros/expand.rs` line 181 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O3bh89p9QtKjN-pVNJo:-O3hUfQJBUro3MV52kTH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7d0ed10199a9f62e039eeddba8d274a224879f40/crates/cairo-lang-language-server/src/ide/macros/expand.rs#L181)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

Perhaps we could refactor this so we don't have the boolean flag here
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/ide/macros/expand.rs` line 214 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O3bgmYNDvL_mxIkaD9E:-O3hUejr0mgcfNBxVHJA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7d0ed10199a9f62e039eeddba8d274a224879f40/crates/cairo-lang-language-server/src/ide/macros/expand.rs#L214)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

I lack some explanation here for this class and different use cases
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/ide/macros/expand.rs` line 236 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O3bgiDYCC3TogRYfL7G:-O3hUe4fDHvnVwFgZeaT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7d0ed10199a9f62e039eeddba8d274a224879f40/crates/cairo-lang-language-server/src/ide/macros/expand.rs#L236)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

Not really useful comment
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/ide/macros/expand.rs` line 253 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O3bg23nAZzchiyA0TlU:-O3hUdDn3vkjdo_cB9Ra:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7d0ed10199a9f62e039eeddba8d274a224879f40/crates/cairo-lang-language-server/src/ide/macros/expand.rs#L253)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

This function does too many things for my taste, also the lack of proper naming indicates that
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/ide/macros/expand.rs` line 300 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O3bgGoO42webE8i_p2f:-O3hUcZ4-XPNaQQ3yU8y:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7d0ed10199a9f62e039eeddba8d274a224879f40/crates/cairo-lang-language-server/src/ide/macros/expand.rs#L300)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

Naming does not indicate what really happens here
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lang/db/syntax.rs` line 59 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O3bfg2J-XvVPkTq_qU4:-O3hUQFZ7XSKMfcQdzsx:b-iypmbn) ([raw file](https://github.com/starkware-libs/cairo/blob/7d0ed10199a9f62e039eeddba8d274a224879f40/crates/cairo-lang-language-server/src/lang/db/syntax.rs#L59)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

This name is confusing to me 
I think it'd be better if we just got the ancestor and then called `.parent()` on it
</blockquote></details>

Discussed offline

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6075)* status: all files reviewed, 6 unresolved discussions (waiting on @Arcticae and @piotmag769)

**Review by Arcticae — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6075#-:-O3lJIlPEUhdDjV0TXyk:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @piotmag769)

**Comment by Draggu** [comment]
✓ Commit merged in pull request [#6076](https://github.com/starkware-libs/cairo/pull/6076)

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 2 of 4 files at r3, 7 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6075)* status: all files reviewed, 3 unresolved discussions

___
*[`crates/cairo-lang-language-server/src/ide/code_actions/expand_macro.rs` line 16 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O3Y8CWm8gaE33LbqeV9:-O3Y8CWm8gaE33LbqeVA:b-khlawl) ([raw file](https://github.com/starkware-libs/cairo/blob/7d0ed10199a9f62e039eeddba8d274a224879f40/crates/cairo-lang-language-server/src/ide/code_actions/expand_macro.rs#L16)):*
> ```XML
>         .is_some()
>     {
>         let title = "Expand macro recursively at caret".to_owned();
> ```

```
"Show recursive macro expansion"
```



_Code quote:_
```XML
"Expand macro recursively at caret"
```
___
*[`crates/cairo-lang-language-server/src/ide/code_actions/expand_macro.rs` line 24 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O3Y8SOz3j96lrMVmmBa:-O3Y8SOz3j96lrMVmmBb:bglglrq) ([raw file](https://github.com/starkware-libs/cairo/blob/7d0ed10199a9f62e039eeddba8d274a224879f40/crates/cairo-lang-language-server/src/ide/code_actions/expand_macro.rs#L24)):*
> ```XML
>         });
>     } else if db.first_ancestor_of_kind_respective_child(node, SyntaxKind::Attribute).is_some() {
>         let title = "Recursively expand macros for item at caret".to_owned();
> ```

Vide supra
___
*[`crates/cairo-lang-language-server/src/ide/macros/expand.rs` line 43 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O3YBl806GRfkzfon_nQ:-O3YBl806GRfkzfon_nR:bscn6or) ([raw file](https://github.com/starkware-libs/cairo/blob/7d0ed10199a9f62e039eeddba8d274a224879f40/crates/cairo-lang-language-server/src/ide/macros/expand.rs#L43)):*
> ```XML
>         cfg_set: &cfg_set,
>         declared_derives: &db.declared_derives(),
>         allowed_features: &Default::default(),
> ```

Isn't this extractable from the db too?
___
*[`crates/cairo-lang-language-server/src/lang/db/syntax.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6075#-O2iNOX87robRqZs5Lhi:-O3Y6zDY63CY0OSRHq0c:b-ukvlko) ([raw file](https://github.com/starkware-libs/cairo/blob/a39d33ac00f9b152eb90ae068b6522b4f49943ab/crates/cairo-lang-language-server/src/lang/db/syntax.rs#L57)):*
> ```XML
>     /// Traverse tree in root direction
>     /// Finds first node with specified kind
>     /// Returns it's respective child
> ```

+ it's -> its

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 4 of 5 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6075)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request closed without merging**
