### PR TITLE
Fix ExprVarMemberPath::Member stable_ptr.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3700)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3700)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 499 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3700#-N_cWA4a422jXM3lQ42H:-N_cWA4a422jXM3lQ42I:bwslhve) ([raw file](https://github.com/starkware-libs/cairo/blob/1859ae3548243dcd84b3f866233c7f368ad8a0f1/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L499)):*
> ```
>  --> lib.cairo:10:3
>   x.a += 1;
>   ^*^
> ```

Not sure if I should point to `x.a` or just `a`.



_Code quote:_
```
  x.a += 1;
  ^*^
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3700#-:-N_cWszb9JCIGrV8mFIu:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 499 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3700#-N_cWA4a422jXM3lQ42H:-N_cWiiXAbJpookHYCWS:bgyl65r) ([raw file](https://github.com/starkware-libs/cairo/blob/1859ae3548243dcd84b3f866233c7f368ad8a0f1/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L499)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Not sure if I should point to `x.a` or just `a`.
</blockquote></details>

the access to `x` itself is the issue - so `x.a` sound more sensible.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 499 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3700#-N_cWA4a422jXM3lQ42H:-N_cX-i76raDFi_XflBW:b-ybxa8w) ([raw file](https://github.com/starkware-libs/cairo/blob/1859ae3548243dcd84b3f866233c7f368ad8a0f1/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L499)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the access to `x` itself is the issue - so `x.a` sound more sensible.
</blockquote></details>

it is also possible that only x.a was moved.

also note that  the expression is`ExprVarMemberPath`  not `ExprMemberAccess`

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3700)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 499 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3700#-N_cWA4a422jXM3lQ42H:-N_cZjhbCeLIPCrlbbzf:b-5as3h9) ([raw file](https://github.com/starkware-libs/cairo/blob/1859ae3548243dcd84b3f866233c7f368ad8a0f1/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L499)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it is also possible that only x.a was moved.

also note that  the expression is`ExprVarMemberPath`  not `ExprMemberAccess`


</blockquote></details>

at least here - it is definitely about x - so we need to see another example.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3700)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 499 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3700#-N_cWA4a422jXM3lQ42H:-N_d5dX60afi6wWwt3n8:b-18mbol) ([raw file](https://github.com/starkware-libs/cairo/blob/1859ae3548243dcd84b3f866233c7f368ad8a0f1/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L499)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

at least here - it is definitely about x - so we need to see another example.
</blockquote></details>

I think giving the location of the member is more accurate.

The fact that the drop location is wrong here should not be a consideration.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 499 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3700#-N_cWA4a422jXM3lQ42H:-N_d9iZ0BYUDLTff0WxP:beduhvj) ([raw file](https://github.com/starkware-libs/cairo/blob/1859ae3548243dcd84b3f866233c7f368ad8a0f1/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L499)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I think giving the location of the member is more accurate.

The fact that the drop location is wrong here should not be a consideration.
</blockquote></details>

It seems that rust gives the full location



_Code snippet:_
```
257 |             lowered.variables,
    |             ^^^^^^^^^^^^^^^^^ move out of `lowered.variables` occurs here
```

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3700)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 499 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3700#-N_cWA4a422jXM3lQ42H:-N_dErjiETS5WliVkfOP:b-1eq25o) ([raw file](https://github.com/starkware-libs/cairo/blob/1859ae3548243dcd84b3f866233c7f368ad8a0f1/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L499)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

It seems that rust gives the full location
</blockquote></details>

also - it isn't wrong here - `x` was moved by `x.a` - `x.a` was not moved.
(as the issue is `b` and not `a`)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3700)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
