### PR TITLE
Dori/extract logic to function

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1544)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1544)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/cairo-sierra-to-casm/src/invocations/ec.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1544#-NKOPDiS6LaeUOxHCNqq:-NKOPDiS6LaeUOxHCNqr:b8tinpk) ([raw file](https://github.com/starkware-libs/cairo/blob/70448bcc4ecc5d952e2dfa9d9a1ce8bcc41c57b4/crates/cairo-sierra-to-casm/src/invocations/ec.rs#L32)):*
> ```XML
> /// Either asserts the point is on the curve, or adds a jump statement to a label called NotOnCurve,
> /// depending on the boolean flag passed.
> fn verify_ec_point(casm_builder: &mut CasmBuilder, x: Var, y: Var, jump_if_not_on_curve: bool) {
> ```

Cool idea - but I think it is better to just return the two vars that are the two side of the equation,
And do the label jump or assert from the outside

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1544)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @orizi)

___
*[`crates/cairo-sierra-to-casm/src/invocations/ec.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1544#-NKOPDiS6LaeUOxHCNqq:-NKO_E097_mpqe4EDeBc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/70448bcc4ecc5d952e2dfa9d9a1ce8bcc41c57b4/crates/cairo-sierra-to-casm/src/invocations/ec.rs#L32)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Cool idea - but I think it is better to just return the two vars that are the two side of the equation,
And do the label jump or assert from the outside 
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1544)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/cairo-sierra-to-casm/src/invocations/ec.rs` line 32 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1544#-NKPRm5n8V8z4KTTOW3Z:-NKPRm5n8V8z4KTTOW3_:b-bqw2cc) ([raw file](https://github.com/starkware-libs/cairo/blob/679386be4de8024e6d5fea8579991499a3fd09dd/crates/cairo-sierra-to-casm/src/invocations/ec.rs#L32)):*
> ```XML
> /// Populates the two "output vars" with the expected square of y, and the actual square of y. The
> /// caller may either assert they are equal, or compute the diff and handle it differently.
> fn verify_ec_point(casm_builder: &mut CasmBuilder, x: Var, y: Var, y2: Var, expected_y2: Var) {
> ```

Maybe call it y part and x part instead of expected_y2?

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1544#-:-NKPSgxh-FKie8X9i-Ey:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1544)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @orizi)

___
*[`crates/cairo-sierra-to-casm/src/invocations/ec.rs` line 32 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1544#-NKPRm5n8V8z4KTTOW3Z:-NKRvTTN0jltlWonQOWz:b-j5jr7l) ([raw file](https://github.com/starkware-libs/cairo/blob/679386be4de8024e6d5fea8579991499a3fd09dd/crates/cairo-sierra-to-casm/src/invocations/ec.rs#L32)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Maybe call it y part and x part instead of expected_y2?
</blockquote></details>

how about `computed_lhs` and `computed_rhs`? I think `x_part,y_part` can also be comfusing

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1544)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/cairo-sierra-to-casm/src/invocations/ec.rs` line 32 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1544#-NKPRm5n8V8z4KTTOW3Z:-NKSTNZc0hzq2M5SnfPH:bi7jbjs) ([raw file](https://github.com/starkware-libs/cairo/blob/679386be4de8024e6d5fea8579991499a3fd09dd/crates/cairo-sierra-to-casm/src/invocations/ec.rs#L32)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

how about `computed_lhs` and `computed_rhs`? I think `x_part,y_part` can also be comfusing
</blockquote></details>

sg, but update the doc, as it needs to describe an equation, not something about y's

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1544)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-sierra-to-casm/src/invocations/ec.rs` line 32 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1544#-NKPRm5n8V8z4KTTOW3Z:-NKSb4ny95EmN_9YvDpw:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/679386be4de8024e6d5fea8579991499a3fd09dd/crates/cairo-sierra-to-casm/src/invocations/ec.rs#L32)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

sg, but update the doc, as it needs to describe an equation, not something about y's
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1544#-:-NKSc7vQ6plSZpVYPBIi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
