### PR TITLE
added heuristic function for inlining functions

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5113)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 16 of 44 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5113)* status: 16 of 45 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware, @ilyalesokhin-starkware, and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5113#-NrB7vSd2XnpCguFWTjR:-NrB7vSd2XnpCguFWTjS:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/425e839376f55fc5e6ef6ca40110c4761c65eb3e/crates/cairo-lang-lowering/src/inline/mod.rs#L14)):*
> ```XML
> use itertools::{izip, zip_eq, Itertools};
> 
> use self::statements_weights::{ApproxCasmInlineWeight, InlineWeight};
> ```





_Suggestion:_
```XML
use statements_weights::{ApproxCasmInlineWeight, InlineWeight};
```
___
*[`crates/cairo-lang-lowering/src/inline/statements_weights.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5113#-NrB87f85_5n6OvdeUfc:-NrB87f85_5n6OvdeUfd:b-5ae5sy) ([raw file](https://github.com/starkware-libs/cairo/blob/425e839376f55fc5e6ef6ca40110c4761c65eb3e/crates/cairo-lang-lowering/src/inline/statements_weights.rs#L10)):*
> ```XML
>     fn statement_weight(&self, db: &dyn LoweringGroup, statement: &Statement) -> Maybe<i32>;
>     fn block_end_weight(&self, db: &dyn LoweringGroup, block_end: &FlatBlockEnd) -> Maybe<i32>;
>     fn lowered_weight(&self, db: &dyn LoweringGroup, lowered: &FlatLowered) -> Maybe<i32>;
> ```

doc fns



_Code quote:_
```XML
    fn statement_weight(&self, db: &dyn LoweringGroup, statement: &Statement) -> Maybe<i32>;
    fn block_end_weight(&self, db: &dyn LoweringGroup, block_end: &FlatBlockEnd) -> Maybe<i32>;
    fn lowered_weight(&self, db: &dyn LoweringGroup, lowered: &FlatLowered) -> Maybe<i32>;
```
___
*[`crates/cairo-lang-lowering/src/inline/statements_weights.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5113#-NrB8NO49l03mivQcBKl:-NrB8NO49l03mivQcBKm:b-gupu4b) ([raw file](https://github.com/starkware-libs/cairo/blob/425e839376f55fc5e6ef6ca40110c4761c65eb3e/crates/cairo-lang-lowering/src/inline/statements_weights.rs#L10)):*
> ```XML
>     fn statement_weight(&self, db: &dyn LoweringGroup, statement: &Statement) -> Maybe<i32>;
>     fn block_end_weight(&self, db: &dyn LoweringGroup, block_end: &FlatBlockEnd) -> Maybe<i32>;
>     fn lowered_weight(&self, db: &dyn LoweringGroup, lowered: &FlatLowered) -> Maybe<i32>;
> ```

why i32?
why Maybe?



_Code quote:_
```XML
    fn statement_weight(&self, db: &dyn LoweringGroup, statement: &Statement) -> Maybe<i32>;
    fn block_end_weight(&self, db: &dyn LoweringGroup, block_end: &FlatBlockEnd) -> Maybe<i32>;
    fn lowered_weight(&self, db: &dyn LoweringGroup, lowered: &FlatLowered) -> Maybe<i32>;
```
___
*[`crates/cairo-lang-lowering/src/inline/statements_weights.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5113#-NrB8WN-2dZs6LVOdzeF:-NrB8WN-2dZs6LVOdzeG:b-x6g7c6) ([raw file](https://github.com/starkware-libs/cairo/blob/425e839376f55fc5e6ef6ca40110c4761c65eb3e/crates/cairo-lang-lowering/src/inline/statements_weights.rs#L55)):*
> ```XML
>         match block_end {
>             // Return are removed when the function is inlined.
>             FlatBlockEnd::Return(outputs) => Ok(-(outputs.len() as i32)),
> ```

and everywhere



_Suggestion:_
```XML
            FlatBlockEnd::Return(outputs) => Ok(-(outputs.len().into_or_panic())),
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5113)* status: 16 of 45 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware, @ilyalesokhin-starkware, and @orizi)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5113#-NrB7vSd2XnpCguFWTjR:-NrBBgui-pME1LaZ1y4P:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/425e839376f55fc5e6ef6ca40110c4761c65eb3e/crates/cairo-lang-lowering/src/inline/mod.rs#L14)):*
> ```XML
> use itertools::{izip, zip_eq, Itertools};
> 
> use self::statements_weights::{ApproxCasmInlineWeight, InlineWeight};
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/inline/statements_weights.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5113#-NrB87f85_5n6OvdeUfc:-NrB9yRE3A_M-gif3gaw:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/425e839376f55fc5e6ef6ca40110c4761c65eb3e/crates/cairo-lang-lowering/src/inline/statements_weights.rs#L10)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc fns
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/inline/statements_weights.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5113#-NrB8NO49l03mivQcBKl:-NrB9C4r3E_cRQU-XyuT:b-u49q4h) ([raw file](https://github.com/starkware-libs/cairo/blob/425e839376f55fc5e6ef6ca40110c4761c65eb3e/crates/cairo-lang-lowering/src/inline/statements_weights.rs#L10)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why i32?
why Maybe?
</blockquote></details>

i32 because it can be negative (returns and parameters)
maybe because of function.body()
___
*[`crates/cairo-lang-lowering/src/inline/statements_weights.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5113#-NrB8WN-2dZs6LVOdzeF:-NrBB1uOBZKkk_fZWaWM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/425e839376f55fc5e6ef6ca40110c4761c65eb3e/crates/cairo-lang-lowering/src/inline/statements_weights.rs#L55)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

and everywhere
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5113)* status: 17 of 45 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware, @ilyalesokhin-starkware, and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/inline/statements_weights.rs` line 14 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5113#-NrBD1p2C7cKxhyAT7H-:-NrBD1p2C7cKxhyAT7H0:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/71f4ed9bb3f038ee3d3bbcc1f280786e3e4a0637/crates/cairo-lang-lowering/src/inline/statements_weights.rs#L14)):*
> ```XML
>     fn block_end_weight(&self, db: &dyn LoweringGroup, block_end: &FlatBlockEnd) -> Maybe<i32>;
>     // The weight of the entire lowered function.
>     fn lowered_weight(&self, db: &dyn LoweringGroup, lowered: &FlatLowered) -> Maybe<i32>;
> ```





_Suggestion:_
```XML
    /// The weight of a statement in the lowered function.
    fn statement_weight(&self, db: &dyn LoweringGroup, statement: &Statement) -> Maybe<i32>;
    /// The weight of the block end in the lowered function.
    fn block_end_weight(&self, db: &dyn LoweringGroup, block_end: &FlatBlockEnd) -> Maybe<i32>;
    /// The weight of the entire lowered function.
    fn lowered_weight(&self, db: &dyn LoweringGroup, lowered: &FlatLowered) -> Maybe<i32>;
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 41 files at r1, 25 of 44 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5113)* status: 44 of 45 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware, @ilyalesokhin-starkware, and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/inline/statements_weights.rs` line 50 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5113#-NrBERNr7dFbIEljCwpr:-NrBERNs8zjn6nD8NzWD:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/71f4ed9bb3f038ee3d3bbcc1f280786e3e4a0637/crates/cairo-lang-lowering/src/inline/statements_weights.rs#L50)):*
> ```XML
>     fn statement_weight(&self, db: &dyn LoweringGroup, statement: &Statement) -> Maybe<i32> {
>         match statement {
>             // Todo(Tomerstarkware): give a better approximation for the weight of libfuncs.
> ```





_Suggestion:_
```XML
            // TODO(TomerStarkware): give a better approximation for the weight of libfuncs.
```
___
*[`crates/cairo-lang-lowering/src/inline/statements_weights.rs` line 52 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5113#-NrBEeN78fVft6xmRyYZ:-NrBEeN78fVft6xmRyY_:b-ggdmoa) ([raw file](https://github.com/starkware-libs/cairo/blob/71f4ed9bb3f038ee3d3bbcc1f280786e3e4a0637/crates/cairo-lang-lowering/src/inline/statements_weights.rs#L52)):*
> ```XML
>             // Todo(Tomerstarkware): give a better approximation for the weight of libfuncs.
>             Statement::Call(statement_call) => Ok((statement_call.inputs.len()
>                 + if statement_call.function.body(db)?.is_some() { 1 } else { 3 })
> ```

comment the meaning of this calculation.
___
*[`crates/cairo-lang-lowering/src/inline/statements_weights.rs` line 84 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5113#-NrBF1Qk-RE_JcF4rWmD:-NrBF1QlEqlCf4e0EVve:b4dbe0x) ([raw file](https://github.com/starkware-libs/cairo/blob/71f4ed9bb3f038ee3d3bbcc1f280786e3e4a0637/crates/cairo-lang-lowering/src/inline/statements_weights.rs#L84)):*
> ```XML
>             })
>             .sum::<Maybe<i32>>()?
>             - lowered.parameters.len().into_or_panic::<i32>())
> ```

move implementation to trait.



_Code quote:_
```XML
        Ok(lowered
            .blocks
            .iter()
            .map(|(_, block)| {
                block
                    .statements
                    .iter()
                    .map(|statement| self.statement_weight(db, statement))
                    .sum::<Maybe<i32>>()
                    .and_then(|sum| Ok(sum + self.block_end_weight(db, &block.end)?))
            })
            .sum::<Maybe<i32>>()?
            - lowered.parameters.len().into_or_panic::<i32>())
```
___
*[`crates/cairo-lang-runner/src/profiling_test_data/major_test_cases` line 1328 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5113#-NrBDOSn2Jd8jqeBF_dO:-NrBDOSn2Jd8jqeBF_dP:b-1j116) ([raw file](https://github.com/starkware-libs/cairo/blob/71f4ed9bb3f038ee3d3bbcc1f280786e3e4a0637/crates/cairo-lang-runner/src/profiling_test_data/major_test_cases#L1328)):*
> ```
>   test::erc20_transfer -> core::starknet::testing::set_caller_address: 6
> Weight by Cairo stack trace:
>   test::erc20_transfer: 481
> ```

regression



_Code quote:_
```
  test::erc20_transfer: 481
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 44 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5113)* status: all files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware, @ilyalesokhin-starkware, and @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5113)* status: 0 of 56 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware, @ilyalesokhin-starkware, and @orizi)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 82 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5113#-NrBCnWSAbXYS1IjPqp1:-NrBF2JG-BZZ7jCSKIO7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/71f4ed9bb3f038ee3d3bbcc1f280786e3e4a0637/crates/cairo-lang-lowering/src/inline/mod.rs#L82)):*
> ```XML
>     let weight = ApproxCasmInlineWeight {};
>     let weight_of_blocks = weight.lowered_weight(db, lowered.as_ref())?;
>     if weight_of_blocks < inline_small_functions_threshold(db).try_into().unwrap() {
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/inline/statements_weights.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5113#-NrB8NO49l03mivQcBKl:-NrBEqUX9LQ9bnp8i2Li:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/425e839376f55fc5e6ef6ca40110c4761c65eb3e/crates/cairo-lang-lowering/src/inline/statements_weights.rs#L10)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

unwrap instead - you would never reach here if there are diags.
use isize to at least partially match the comparison with usize.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/inline/statements_weights.rs` line 14 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5113#-NrBD1p2C7cKxhyAT7H-:-NrBEr017CBEL22xxh39:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/71f4ed9bb3f038ee3d3bbcc1f280786e3e4a0637/crates/cairo-lang-lowering/src/inline/statements_weights.rs#L14)):*
> ```XML
>     fn block_end_weight(&self, db: &dyn LoweringGroup, block_end: &FlatBlockEnd) -> Maybe<i32>;
>     // The weight of the entire lowered function.
>     fn lowered_weight(&self, db: &dyn LoweringGroup, lowered: &FlatLowered) -> Maybe<i32>;
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/inline/statements_weights.rs` line 50 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5113#-NrBERNr7dFbIEljCwpr:-NrBIoHR5m0aNXiOKSNG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/71f4ed9bb3f038ee3d3bbcc1f280786e3e4a0637/crates/cairo-lang-lowering/src/inline/statements_weights.rs#L50)):*
> ```XML
>     fn statement_weight(&self, db: &dyn LoweringGroup, statement: &Statement) -> Maybe<i32> {
>         match statement {
>             // Todo(Tomerstarkware): give a better approximation for the weight of libfuncs.
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/inline/statements_weights.rs` line 52 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5113#-NrBEeN78fVft6xmRyYZ:-NrBHrE76wNsgoHFSdiz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/71f4ed9bb3f038ee3d3bbcc1f280786e3e4a0637/crates/cairo-lang-lowering/src/inline/statements_weights.rs#L52)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

comment the meaning of this calculation.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/inline/statements_weights.rs` line 84 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5113#-NrBF1Qk-RE_JcF4rWmD:-NrBHsV_84mVM5uUi3lG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/71f4ed9bb3f038ee3d3bbcc1f280786e3e4a0637/crates/cairo-lang-lowering/src/inline/statements_weights.rs#L84)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

move implementation to trait.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runner/src/profiling_test_data/major_test_cases` line 1328 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5113#-NrBDOSn2Jd8jqeBF_dO:-NrFpm9H3wEI2iV_ZfpB:b-dfdo6f) ([raw file](https://github.com/starkware-libs/cairo/blob/71f4ed9bb3f038ee3d3bbcc1f280786e3e4a0637/crates/cairo-lang-runner/src/profiling_test_data/major_test_cases#L1328)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

regression
</blockquote></details>

changed back to simple heuristic

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 55 of 56 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5113)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @ilyalesokhin-starkware, and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 91 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5113#-NrG-v2E-GRLTMI_6snS:-NrG-v2E-GRLTMI_6snT:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/4d16ab919b366410c20e9055ed51aa45456eca81/crates/cairo-lang-lowering/src/inline/mod.rs#L91)):*
> ```XML
>     // if num_of_statements < inline_small_functions_threshold(db) {
>     //     return Ok(true);
>     // }
> ```

?



_Code quote:_
```XML
    //     lowered.blocks.iter().map(|(_, block)| block.statements.len()).sum();
    // if num_of_statements < inline_small_functions_threshold(db) {
    //     return Ok(true);
    // }
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5113)* status: 47 of 56 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @ilyalesokhin-starkware, and @orizi)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 91 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5113#-NrG-v2E-GRLTMI_6snS:-NrGIIXm1cz6AJwkG3hh:bss4a2b) ([raw file](https://github.com/starkware-libs/cairo/blob/4d16ab919b366410c20e9055ed51aa45456eca81/crates/cairo-lang-lowering/src/inline/mod.rs#L91)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

Removed.

**Review by orizi — APPROVED** [review]
> Reviewed 9 of 9 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5113)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware and @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5113#-:-NrGTBhs2DOe6perkl5i:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware and @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5113)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware and @ilyalesokhin-starkware)

**Pull request merged**
