### PR TITLE
get_contracts_info()

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2909)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2907** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2907" target="_blank">Graphite</a> 
    * **PR #2908** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2908" target="_blank">Graphite</a> 
      * **PR #2909** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2909" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2909?utm_source=stack-comment).

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2909)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/contract.rs` line 154 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2909#-NTdpKjz6C4bPkL8tVL3:-NTdpKjz6C4bPkL8tVL4:b2nhdkj) ([raw file](https://github.com/starkware-libs/cairo/blob/7800dd81ed3aec811fe005c0220e21235523c71b/crates/cairo-lang-starknet/src/contract.rs#L154)):*
> ```XML
> }
> 
> pub struct ContractInfo {
> ```

Doc
___
*[`crates/cairo-lang-starknet/src/contract.rs` line 208 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2909#-NTdpXk6E4ncj6OFST8u:-NTdpXk6E4ncj6OFST8v:b6r0215) ([raw file](https://github.com/starkware-libs/cairo/blob/7800dd81ed3aec811fe005c0220e21235523c71b/crates/cairo-lang-starknet/src/contract.rs#L208)):*
> ```XML
> 
> /// Converts a function to a Sierra function.
> pub fn to_sierra_function<T: SierraIdReplacer>(
> ```

Doc the other return value as well

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2909)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/contract.rs` line 154 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2909#-NTdpKjz6C4bPkL8tVL3:-NTe6xpfEGzh54mta8TT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7800dd81ed3aec811fe005c0220e21235523c71b/crates/cairo-lang-starknet/src/contract.rs#L154)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/contract.rs` line 208 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2909#-NTdpXk6E4ncj6OFST8u:-NTe6z1X1IObzlt1KP0t:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7800dd81ed3aec811fe005c0220e21235523c71b/crates/cairo-lang-starknet/src/contract.rs#L208)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Doc the other return value as well
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2909#-:-NTeH17dC73zfpLswhGy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Comment by spapinistarkware** [comment]
@spapinistarkware queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2909).

**Comment by spapinistarkware** [comment]
[Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2909) failed to merge this pull request for an unknown reason. Try your merge again, or report a bug if you see this consistently.

**Pull request merged**
