### PR TITLE
Improve error message for anonymous impl params.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4636)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4636)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference/solver.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4636#-NmAhm4Q6sq9qcr6M72I:-NmAhm4R0_emw0RAk9GF:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9bde53daf0933bc622095c2fc9ba0bc127e0a594/crates/cairo-lang-semantic/src/expr/inference/solver.rs#L46)):*
> ```XML
>                 let impls_str =
>                     impls.iter().map(|imp| format!("{:?}", imp.full_path(db.upcast()))).join(", ");
>                 format!(
> ```





_Suggestion:_
```XML
                let impls_str =
                    impls.iter().map(|imp| format!("`{}`", imp.full_path(db.upcast()))).join(", ");
                format!(
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4636)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference/solver.rs` line 46 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4636#-NmBEve_3mOmmZ70GxYz:-NmBEve_3mOmmZ70GxZ-:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e93c88f867401ba208dbfc92369a3756ce179125/crates/cairo-lang-semantic/src/expr/inference/solver.rs#L46)):*
> ```XML
>                 let impls_str =
>                     impls.iter().map(|imp| format!("{}", imp.format(db.upcast()))).join(", ");
>                 format!(
> ```





_Suggestion:_
```XML
                    impls.iter().map(|imp| format!("`{}`", imp.format(db.upcast()))).join(", ");
    
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4636)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/inference/solver.rs` line 46 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4636#-NmBEve_3mOmmZ70GxYz:-NmBLj5a0HBM4FaN0Y6D:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e93c88f867401ba208dbfc92369a3756ce179125/crates/cairo-lang-semantic/src/expr/inference/solver.rs#L46)):*
> ```XML
>                 let impls_str =
>                     impls.iter().map(|imp| format!("{}", imp.format(db.upcast()))).join(", ");
>                 format!(
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 5 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4636#-:-NmBVOA08b9GVzmhhydm:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
