### PR TITLE
const in semantic: Add a resolved_lookback and resolve the type.

### PR DESCRIPTION
**Pull request by liorgold2**
commit-id:1c8b6804

### CODE REVIEW

**Review by yuvalsw — APPROVED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1758)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 150 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1758#-NLb6UlpDa3WkYrB-6T8:-NLb6Ulq5pEpvcxjxyWg:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/8bea667582dfdfb25992670967646e2d7a62b542/crates/cairo-lang-lowering/src/db.rs#L150)):*
> ```XML
>                         .unwrap_or_default(),
>                 );
>                 Constant
> ```

?

**Review by yuvalsw — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1758)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 8 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1758#-:-NLofSto9LdGMRz_sdPr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1758)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
