### PR TITLE
Added TraitOrImplContext to resolver data

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5217)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5217)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-defs/src/ids.rs` line 950 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5217#-NsTloTf-akCg_yjkaMS:-NsTloTf-akCg_yjkaMT:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/61460c5cdfd84f654087ab8d1a0580766f7579d4/crates/cairo-lang-defs/src/ids.rs#L950)):*
> ```XML
> }
> 
> // TODO(ygdm)
> ```

.
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5217#-NsTlspCAtNjgPghDZHk:-NsTlspCAtNjgPghDZHl:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/61460c5cdfd84f654087ab8d1a0580766f7579d4/crates/cairo-lang-semantic/src/resolve/mod.rs#L104)):*
> ```XML
>     /// Inference data for the resolver.
>     pub inference_data: InferenceData,
>     // TODO(ygd)
> ```

.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5217)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5217)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-defs/src/ids.rs` line 950 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5217#-NsTloTf-akCg_yjkaMS:-NsgCaSo3dIL-JYv1GoB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/61460c5cdfd84f654087ab8d1a0580766f7579d4/crates/cairo-lang-defs/src/ids.rs#L950)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5217#-NsTlspCAtNjgPghDZHk:-NsgCany-5jWJfC--pD9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/61460c5cdfd84f654087ab8d1a0580766f7579d4/crates/cairo-lang-semantic/src/resolve/mod.rs#L104)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5217#-:-NsgMnrp51Qnpy1wdrfW:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
