### PR TITLE
Add SyscallPtr.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1196)

### CODE REVIEW

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1196#-:-NICwh3MCe3HL4vOWB8s:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1196)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/starknet/examples/test_contract.cairo` line 4 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1196#-NICwjTlBnCfLP1x-P5B:-NICwjTlBnCfLP1x-P5C:bw7pdfl) ([raw file](https://github.com/starkware-libs/cairo/blob/57778b1919abc2d6e951f864a2daeee72cf2e6cd/crates/starknet/examples/test_contract.cairo#L4)):*
> ```Cairo
> 
> #[ContractImpl]
> impl TestContractImpl of ITestContract { func test(ref syscall_ptr : SyscallPtr) -> felt {
> ```

Please fix formatting

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1196#-:-NIRtjFQ7n4k42XxM1Fc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1196)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
