### PR TITLE
feat(corelib): OptionTrait::map_or, OptionTrait::map_or_else

### PR DESCRIPTION
**Pull request by julio4**
## `OptionTrait::map_or`

Returns the provided default result (if none), or applies a function to the contained value (if any).

#### Example

```
assert_eq!(Option::Some("foo").map_or(42, |v| v.len()), 3);

let x: Option<ByteArray> = Option::None;
assert_eq!(x.map_or(42, |v| v.len()), 42);
```

## `OptionTrait::map_or_else`

Computes a default function result (if none), or applies a different function to the contained value (if any).

#### Example

```
let k = 21;

let x = Option::Some("foo");
assert_eq!(x.map_or_else( || 2 * k, |v: ByteArray| v.len()), 3);

let x: Option<ByteArray> = Option::None;
assert_eq!(x.map_or_else( || 2 * k, |v: ByteArray| v.len()), 42);
```

### CODE REVIEW

**Review by enitrat — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6935)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @julio4)

___
*[`corelib/src/option.cairo` line 356 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6935#-OF3f40G3smuY7f7Awu0:-OF3f40G3smuY7f7Awu1:b6cv9qa) ([raw file](https://github.com/starkware-libs/cairo/blob/34dbc1e5f4c0c966ac64aa860e458ec8facc48f2/corelib/src/option.cairo#L356)):*
> ```Cairo
>     /// or applies a function to the contained value (if any).
>     ///
>     /// Arguments passed to `map_or` are eagerly evaluated; if you are passing
> ```

I don't believe this applies
___
*[`corelib/src/option.cairo` line 368 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6935#-OF3eeQREtgZFGhXKyeN:-OF3eeQREtgZFGhXKyeO:bauojr0) ([raw file](https://github.com/starkware-libs/cairo/blob/34dbc1e5f4c0c966ac64aa860e458ec8facc48f2/corelib/src/option.cairo#L368)):*
> ```Cairo
>     ///
>     /// let x: Option<ByteArray> = Option::None;
>     /// assert_eq!(x.map_or(42, |v| v.len()), 42);
> ```

This does not compile



_Code quote:_
```Cairo
    /// assert_eq!(Option::Some("foo").map_or(42, |v| v.len()), 3);
    ///
    /// let x: Option<ByteArray> = Option::None;
    /// assert_eq!(x.map_or(42, |v| v.len()), 42);
```

**Review by julio4 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6935)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @enitrat)

___
*[`corelib/src/option.cairo` line 356 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6935#-OF3f40G3smuY7f7Awu0:-OF3msG5A2f4HwD4FY0g:bs4e753) ([raw file](https://github.com/starkware-libs/cairo/blob/34dbc1e5f4c0c966ac64aa860e458ec8facc48f2/corelib/src/option.cairo#L356)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

I don't believe this applies
</blockquote></details>

Is it different than rust?
___
*[`corelib/src/option.cairo` line 368 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6935#-OF3eeQREtgZFGhXKyeN:-OF3mPjU36EudXziTFDQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/34dbc1e5f4c0c966ac64aa860e458ec8facc48f2/corelib/src/option.cairo#L368)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

This does not compile
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6935)* status: all files reviewed, 3 unresolved discussions (waiting on @enitrat and @julio4)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6935#-OFCXfjp1YpQxzYlWz-u:-OFCXfjp1YpQxzYlWz-v:bn4euig) (no related file):*
awaiting the other discussion.

**Review by enitrat — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6935)* status: all files reviewed, 3 unresolved discussions (waiting on @julio4)

___
*[`corelib/src/option.cairo` line 356 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6935#-OF3f40G3smuY7f7Awu0:-OFCdX1L7IhuNhJibPpl:b6gjxwg) ([raw file](https://github.com/starkware-libs/cairo/blob/34dbc1e5f4c0c966ac64aa860e458ec8facc48f2/corelib/src/option.cairo#L356)):*
<details><summary><i>Previously, julio4 (Julio) wrote…</i></summary><blockquote>

Is it different than rust?
</blockquote></details>

actually, no, you're right

**Review by enitrat — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6935#-:-OFCd_Il5GHAF5xupWsO:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @julio4 and @orizi)

___
*[`corelib/src/option.cairo` line 368 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6935#-OF3eeQREtgZFGhXKyeN:-OFCddsM4mA-aisO7Mt8:blsiy7c) ([raw file](https://github.com/starkware-libs/cairo/blob/34dbc1e5f4c0c966ac64aa860e458ec8facc48f2/corelib/src/option.cairo#L368)):*
<details><summary><i>Previously, julio4 (Julio) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@orizi shouldn't `v` be automatically inferred as a `ByteArray` here?

**Comment by julio4** [comment]
*[`corelib/src/option.cairo` line 368 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6935#-OF3eeQREtgZFGhXKyeN:-OFCegog9NfoXxM94-vP:b30cin7) ([raw file](https://github.com/starkware-libs/cairo/blob/34dbc1e5f4c0c966ac64aa860e458ec8facc48f2/corelib/src/option.cairo#L368)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

@orizi shouldn't `v` be automatically inferred as a `ByteArray` here?
</blockquote></details>

Would love to know as well how the trait bounds inference is currently done

**Review by julio4 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6935)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6935#-OFCXfjp1YpQxzYlWz-u:-OFCfA0U8AV98sumvGPh:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

awaiting the other discussion.
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6935)* status: all files reviewed, 1 unresolved discussion (waiting on @julio4)

___
*[`corelib/src/option.cairo` line 368 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6935#-OF3eeQREtgZFGhXKyeN:-OFCmFeGEuoKRcbIhYTp:bt36ie8) ([raw file](https://github.com/starkware-libs/cairo/blob/34dbc1e5f4c0c966ac64aa860e458ec8facc48f2/corelib/src/option.cairo#L368)):*
<details><summary><i>Previously, julio4 (Julio) wrote…</i></summary><blockquote>

Would love to know as well how the trait bounds inference is currently done
</blockquote></details>

it should - will make sure to check why it doesn't next week. @TomerStarkware 

in general - trait bounds are adding 2 things:
1. An additional assertion that the types match in the call context.
2. Makes the types be used as the exact same type in the function context.

**Review by TomerStarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6935#-:-OFIm3jH2IFQCYELyRNj:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6935#-:-OFQzrxT7pXW_uDpoGQb:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @julio4)

**Pull request merged**
