### PR TITLE
Made non-copy variable not be forwarded in const folding.

### LINKED ISSUE #6321: bug: failed to specialize `drop` for generic argument of type `u32`
# Bug Report

**Cairo version:**

scarb 2.8.0+nightly-2024-08-31 (19fe5e032 2024-08-31)
cairo: 2.8.0 (ac0e135fb)
sierra: 1.6.0

Note that the issue occurs on Scarb v2.6.4, v2.8.0 and v2.8.1. It does not occur on v2.7.*.

**Current behavior:**

Given a generic list-like structure using `Felt252Dict` like:

```cairo
#[derive(Destruct)]
struct List<T, +Drop<T>, +Felt252DictValue<T>> {
    items: Felt252Dict<T>,
    len: u32,
}
```

Then instantiating said structure with values of signed integer, unsigned integer or felt, results in this error:

```console
thread 'scarb compile drop_bug-t45lkkfl5igrc' panicked at /cargo/git/checkouts/cairo-f086c7e6d4098a68/ac0e135/crates/cairo-lang-sierra-generator/src/utils.rs:335:9:
Failed to specialize: `drop<drop_bug::List::<core::integer::u32, core::integer::u32Drop, core::integer::U32Felt252DictValue>>`. Error: Could not specialize libfunc `drop` with generic_args: [[6]]. Error: Provided generic argument is unsupported.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at scarb/src/ops/compile.rs:163:14:
Compiler thread has panicked.: Any { .. }
error: `scarb metadata` exited with error
``` 

**Expected behavior:**

The compiler should be able to handle numeric types for generic arguments in the above struct.

**Steps to reproduce:**

- use any Scarb 2.8.* version
- create a new Cairo project locally
- copy/paste code from "Related code" section below into your _src/lib.cairo_ file
- run `scarb cairo-run` in your terminal
- error appears

**Related code:**

```cairo
use core::dict::Felt252Dict;

#[derive(Destruct)]
struct List<T, +Drop<T>, +Felt252DictValue<T>> {
    items: Felt252Dict<T>,
    len: u32,
}

#[generate_trait]
pub impl ListImpl<T, +Drop<T>, +Felt252DictValue<T>> of ListTrait<T> {
    fn new() -> List<T> {
        List { items: Default::default(), len: 0 }
    }

    fn length(self: @List<T>) -> u32 {
        *self.len
    }
}

fn main() {
    let list = ListTrait::<u32>::new();
    assert!(list.length() == 0, "Not empty");
    println!("All good");
}
```

**Other information:**

I noticed that other people had similar problems in the past (see https://github.com/starkware-libs/cairo/issues/2462 and https://github.com/starkware-libs/cairo/issues/2135), but since this was very long time ago, it doesn't seem the issues are related to this. As mentioned before, the problem reported in this issue occurs with Cairo 2.6.4 and 2.8.*.

---

Also, if instead of `u32`, the List is instantiated with `ByteArray` like:

```cairo
let list = ListTrait::<ByteArray>::new();
// ...
```

Then the following error occurs:

```console
error[E0002]: Method `length` could not be called on type `drop_bug::List::<core::byte_array::ByteArray, core::byte_array::ByteArrayDrop, ImplVarId(65)>`.
Candidate `ListTrait::length` inference failed with: Trait has no implementation in context: drop_bug::ListTrait::<core::byte_array::ByteArray, core::byte_array::ByteArrayDrop, ?1>.
 --> /home/nenad/repos/drop_bug/src/lib.cairo:22:18
    assert!(list.length() == 0, "Not empty");
                 ^****^

error: could not compile `drop_bug` due to previous error
error: `scarb metadata` exited with error
```

I'm not certain whether I simply forgot to include some impl trait as a constraint

---

Another related problem: let's say we remove the generic argument and hardcode the `u32` type. A similar problem _still_ occurs, but _only_ on Scarb v2.8.*:

```cairo
use core::dict::Felt252Dict;

#[derive(Destruct)]
struct List {
    items: Felt252Dict<u32>,
    len: u32,
}

#[generate_trait]
pub impl ListImpl of ListTrait {
    fn new() -> List {
        List { items: Default::default(), len: 0 }
    }

    fn length(self: @List) -> u32 {
        *self.len
    }
}

fn main() {
    let list = ListTrait::new();
    assert!(list.length() == 0, "Not empty");
    println!("All good");
}
```

Running this results in:

```console
thread 'scarb compile drop_bug-t45lkkfl5igrc' panicked at /cargo/git/checkouts/cairo-f086c7e6d4098a68/ac0e135/crates/cairo-lang-sierra-generator/src/utils.rs:335:9:
Failed to specialize: `drop<drop_bug::List>`. Error: Could not specialize libfunc `drop` with generic_args: [[6]]. Error: Provided generic argument is unsupported.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at scarb/src/ops/compile.rs:163:14:
Compiler thread has panicked.: Any { .. }
error: `scarb metadata` exited with error
```

### PR DESCRIPTION
**Pull request by orizi**
Fixes #6321.

---

**Stack**:
- #6324 ⬅
- #6314
- #6313

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6324)

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6324)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/test_data/const_folding` line 3019 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6324#-O5h3GP7Dvsecg0pxe7P:-O5h3GP7Dvsecg0pxe7Q:b-kt1b18) ([raw file](https://github.com/starkware-libs/cairo/blob/c96d9abec652b51a2ad901f4b7794a06c466d163/crates/cairo-lang-lowering/src/optimizations/test_data/const_folding#L3019)):*
> ```
>   (v3: (core::felt252, core::dict::Felt252Dict::<core::felt252>), v4: @(core::felt252, core::dict::Felt252Dict::<core::felt252>)) <- snapshot(v2)
>   (v5: core::felt252, v6: core::dict::Felt252Dict::<core::felt252>) <- struct_destructure(v3)
>   (v7: core::dict::SquashedFelt252Dict::<core::felt252>) <- core::dict::Felt252DictImpl::<core::felt252, core::Felt252Felt252DictValue>::squash(v6)
> ```

before the fix.



_Suggestion:_
```
  (v7: core::dict::SquashedFelt252Dict::<core::felt252>) <- core::dict::Felt252DictImpl::<core::felt252, core::Felt252Felt252DictValue>::squash(v1)
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/const_folding.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6324#-O5hP02L5C3W7no7hdtI:-O5hP02L5C3W7no7hdtJ:bg46650) ([raw file](https://github.com/starkware-libs/cairo/blob/c1f8b639417d48d4d7f1020f9d6699866f2a9496/crates/cairo-lang-lowering/src/optimizations/const_folding.rs#L29)):*
> ```XML
> 
> /// Keeps track of equivalent values that a variables might be replaced with.
> /// Note: We don't keep track of types as we assume the usage is always correct.
> ```

is this comment still relevent?



_Code quote:_
```XML
/// Note: We don't keep track of types as we assume the usage is always correct.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/const_folding.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6324#-O5hP7RH7k7xY7IyvYBm:-O5hP7RH7k7xY7IyvYBn:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/c1f8b639417d48d4d7f1020f9d6699866f2a9496/crates/cairo-lang-lowering/src/optimizations/const_folding.rs#L40)):*
> ```XML
>     /// The variable is a struct of other variables.
>     Struct(Vec<VarInfo>),
>     /// A placeholder for building constructing a struct containing a const, for the unknown parts.
> ```

?



_Code quote:_
```XML
building constructing
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/const_folding.rs` line 41 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6324#-O5hPKie2DUaWN0vGokg:-O5hPKif1OdwB6UdxUCQ:bryxwm9) ([raw file](https://github.com/starkware-libs/cairo/blob/c1f8b639417d48d4d7f1020f9d6699866f2a9496/crates/cairo-lang-lowering/src/optimizations/const_folding.rs#L41)):*
> ```XML
>     Struct(Vec<VarInfo>),
>     /// A placeholder for building constructing a struct containing a const, for the unknown parts.
>     Placeholder,
> ```

Maybe None or undefined?



_Code quote:_
```XML
Placeholder
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6324)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/const_folding.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6324#-O5hP02L5C3W7no7hdtI:-O5hQCM7676s3sa-w5ms:bgocobz) ([raw file](https://github.com/starkware-libs/cairo/blob/c1f8b639417d48d4d7f1020f9d6699866f2a9496/crates/cairo-lang-lowering/src/optimizations/const_folding.rs#L29)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

is this comment still relevent?
</blockquote></details>

it didn't use to be - but it is now (since we added the snapshots)
___
*[`crates/cairo-lang-lowering/src/optimizations/const_folding.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6324#-O5hP7RH7k7xY7IyvYBm:-O5hQRzj72qL1N_V-am8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c1f8b639417d48d4d7f1020f9d6699866f2a9496/crates/cairo-lang-lowering/src/optimizations/const_folding.rs#L40)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/optimizations/const_folding.rs` line 41 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6324#-O5hPKie2DUaWN0vGokg:-O5hQSlG-EC50M1UptWF:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c1f8b639417d48d4d7f1020f9d6699866f2a9496/crates/cairo-lang-lowering/src/optimizations/const_folding.rs#L41)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Maybe None or undefined?
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6324)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/const_folding.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6324#-O5hP7RH7k7xY7IyvYBm:-O5hRJ5Z8TICkCZiZk6g:bd2yykj) ([raw file](https://github.com/starkware-libs/cairo/blob/c1f8b639417d48d4d7f1020f9d6699866f2a9496/crates/cairo-lang-lowering/src/optimizations/const_folding.rs#L40)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Done.
</blockquote></details>

fix comment as well.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6324)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/const_folding.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6324#-O5hP7RH7k7xY7IyvYBm:-O5hTAG_67yhrHwEQ0bU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c1f8b639417d48d4d7f1020f9d6699866f2a9496/crates/cairo-lang-lowering/src/optimizations/const_folding.rs#L40)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

fix comment as well.
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/const_folding.rs` line 39 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6324#-O5hVMjl97WppDIj6kVt:-O5hVMjl97WppDIj6kVu:bhitrqz) ([raw file](https://github.com/starkware-libs/cairo/blob/f02212a707f994d64a0f26f89edd6329de681bbf/crates/cairo-lang-lowering/src/optimizations/const_folding.rs#L39)):*
> ```XML
>     Snapshot(Box<VarInfo>),
>     /// The variable is a struct of other variables.
>     Struct(Vec<VarInfo>),
> ```

consider using option instead of untracked.



_Suggestion:_
```XML
 Struct(Vec<Option<VarInfo>>),
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/const_folding.rs` line 40 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6324#-O5hVBOT27E1CrhdXiVa:-O5hVBOT27E1CrhdXiVb:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f02212a707f994d64a0f26f89edd6329de681bbf/crates/cairo-lang-lowering/src/optimizations/const_folding.rs#L40)):*
> ```XML
>     /// The variable is a struct of other variables.
>     Struct(Vec<VarInfo>),
>     /// A marker for inner `VarInfo`s to be untracked - enables building recursive `VarInfo`s
> ```





_Suggestion:_
```XML
Enables building VarInfo::Structs where some of the members are untracked.
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6324)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/const_folding.rs` line 39 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6324#-O5hVMjl97WppDIj6kVt:-O5hZ-wGBVA7oJDbyooH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f02212a707f994d64a0f26f89edd6329de681bbf/crates/cairo-lang-lowering/src/optimizations/const_folding.rs#L39)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

consider using option instead of untracked.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/optimizations/const_folding.rs` line 40 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6324#-O5hVBOT27E1CrhdXiVa:-O5hZ0d-B2dfU3ITDkKP:b-cxchxo) ([raw file](https://github.com/starkware-libs/cairo/blob/f02212a707f994d64a0f26f89edd6329de681bbf/crates/cairo-lang-lowering/src/optimizations/const_folding.rs#L40)):*
> ```XML
>     /// The variable is a struct of other variables.
>     Struct(Vec<VarInfo>),
>     /// A marker for inner `VarInfo`s to be untracked - enables building recursive `VarInfo`s
> ```

No longer relevant.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6324#-:-O5has9rBw_e-ZdFuy0v:bnfp4nl)* status: 1 of 2 files reviewed, 1 unresolved discussion

**Pull request merged**
