### PR TITLE
Added assert_ne! test macro

### PR DESCRIPTION
**Pull request by clint419**
@orizi Hi, i added an `assert_ne! ` macro, you see if the pr is necessary, thank you

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4424)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4424)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @clint419)

___
*[`crates/cairo-lang-test-plugin/src/inline_macros/assert.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4424#-NjfQJ-Y-EmxrKk7EBuG:-NjfQJ-Y-EmxrKk7EBuH:b-gb62bv) ([raw file](https://github.com/starkware-libs/cairo/blob/b2a19034b872e388dd2bf3b94953bd4a277eac2b/crates/cairo-lang-test-plugin/src/inline_macros/assert.rs#L19)):*
> ```XML
>     fn generate_code(
>         &self,
>         db: &dyn SyntaxGroup,
> ```

and remove the later explicit call.



_Suggestion:_
```XML
trait CompareAssertionPlugin: NamedPlugin {
    const OPERATOR: &'static str;
}

impl NamedPlugin for CompareAssertionPlugin {
    fn generate_code(
        &self,
        db: &dyn SyntaxGroup,
```
___
*[`crates/cairo-lang-test-plugin/src/inline_macros/assert.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4424#-NjfR76IE8EbqKz0Zx7i:-NjfR76IE8EbqKz0Zx7j:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b2a19034b872e388dd2bf3b94953bd4a277eac2b/crates/cairo-lang-test-plugin/src/inline_macros/assert.rs#L101)):*
> ```XML
>                         );
>             "#,
>             },
> ```





_Suggestion:_
```XML
        let operator = Self::OPERATOR;
        builder.add_modified(RewriteNode::interpolate_patched(
            &formatdoc! {
                r#"
                {{
                    {maybe_assign_lhs}
                    {maybe_assign_rhs}
                    if !(@$lhs_value$ {operator} @$rhs_value$) {{
                        let mut {f}: core::fmt::Formatter = core::traits::Default::default();
                        core::result::ResultTrait::<(), core::fmt::Error>::unwrap(
                            write!({f}, "assertion `{lhs_escaped} {operator} {rhs_escaped}` failed")
                        );
            "#,
            },
```

**Review by clint419 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4424)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-test-plugin/src/inline_macros/assert.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4424#-NjfQJ-Y-EmxrKk7EBuG:-NjfiG1xC9Dx1FRYXNDj:bkqser0) ([raw file](https://github.com/starkware-libs/cairo/blob/b2a19034b872e388dd2bf3b94953bd4a277eac2b/crates/cairo-lang-test-plugin/src/inline_macros/assert.rs#L19)):*
> and remove the later explicit call.

The CompareAssertionPlugin is a trait that does not implement the NamedPlugin
___
*[`crates/cairo-lang-test-plugin/src/inline_macros/assert.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4424#-NjfR76IE8EbqKz0Zx7i:-Njg6WPw1pNVI-6ZqXov:bhug9gc) ([raw file](https://github.com/starkware-libs/cairo/blob/b2a19034b872e388dd2bf3b94953bd4a277eac2b/crates/cairo-lang-test-plugin/src/inline_macros/assert.rs#L101)):*
> ```XML
>                         );
>             "#,
>             },
> ```

-   This is a good suggestion

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4424)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @clint419)

___
*[`crates/cairo-lang-test-plugin/src/inline_macros/assert.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4424#-NjfQJ-Y-EmxrKk7EBuG:-Njg7Ycq5tm87icxTNSx:bz1koe2) ([raw file](https://github.com/starkware-libs/cairo/blob/b2a19034b872e388dd2bf3b94953bd4a277eac2b/crates/cairo-lang-test-plugin/src/inline_macros/assert.rs#L19)):*
<details><summary><i>Previously, clint419 (Clint) wrote…</i></summary><blockquote>

> and remove the later explicit call.

The CompareAssertionPlugin is a trait that does not implement the NamedPlugin
</blockquote></details>

instead:
```
trait CompareAssertionPlugin {
    const NAME: &'static str;
    const OPERATOR: &'static str;
}

impl<T: CompareAssertionPlugin> NamedPlugin for T {
...
```

**Review by clint419 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4424)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-test-plugin/src/inline_macros/assert.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4424#-NjfQJ-Y-EmxrKk7EBuG:-NjgCZeZ3iKT1wHloAs0:b-ikqfyp) ([raw file](https://github.com/starkware-libs/cairo/blob/b2a19034b872e388dd2bf3b94953bd4a277eac2b/crates/cairo-lang-test-plugin/src/inline_macros/assert.rs#L19)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

instead:
```
trait CompareAssertionPlugin {
    const NAME: &'static str;
    const OPERATOR: &'static str;
}

impl<T: CompareAssertionPlugin> NamedPlugin for T {
...
```
</blockquote></details>

The code violates orphan rules

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4424)* status: 1 of 6 files reviewed, 5 unresolved discussions (waiting on @clint419)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4424#-NjgIvXSAimL7N-Y54L1:-NjgIvXSAimL7N-Y54L2:b-7xjvbz) (no related file):*
add test to `corelib/src/test/testing_test.cairo`

___
___
*[`crates/cairo-lang-test-runner/test_data/lib.cairo` line 54 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4424#-NjgIqUY39eXc_fflq1I:-NjgIqUZDQP4h9yJsHMM:b-hay66z) ([raw file](https://github.com/starkware-libs/cairo/blob/05997e9116b2dac94efe7010195696252bddf174/crates/cairo-lang-test-runner/test_data/lib.cairo#L54)):*
> ```Cairo
>         let mut contract1 = IBalanceDispatcher { contract_address: address1 };
> 
>         assert_eq!(contract0.get(), 100);
> ```

revert.
___
*[`scripts/starknet_test.sh` line 6 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4424#-NjgInvLBXODRrHJivkM:-NjgInvLBXODRrHJivkN:b-hay66z) ([raw file](https://github.com/starkware-libs/cairo/blob/05997e9116b2dac94efe7010195696252bddf174/scripts/starknet_test.sh#L6)):*
> ```Shell
>     crates/cairo-lang-starknet/cairo_level_tests/ --starknet && \
> cargo run --bin cairo-test -- \
>     crates/cairo-lang-test-runner/test_data/ --starknet
> ```

revert.
___
*[`crates/cairo-lang-test-plugin/src/inline_macros/assert.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4424#-NjfQJ-Y-EmxrKk7EBuG:-NjgJ7is3twUbmT2G-Ah:bft2mfx) ([raw file](https://github.com/starkware-libs/cairo/blob/b2a19034b872e388dd2bf3b94953bd4a277eac2b/crates/cairo-lang-test-plugin/src/inline_macros/assert.rs#L19)):*
<details><summary><i>Previously, clint419 (Clint) wrote…</i></summary><blockquote>

The code violates orphan rules
</blockquote></details>

you can solve it in the standard way of solving it by using a wrapper.

If you don't want to do this -  just make the generate_code a function with generic arg - you get nothing from this trait.

**Review by clint419 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4424)* status: 1 of 6 files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-test-plugin/src/inline_macros/assert.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4424#-NjfQJ-Y-EmxrKk7EBuG:-NjgVJX27DV8H_CcXt_Z:b-kxz2k6) ([raw file](https://github.com/starkware-libs/cairo/blob/b2a19034b872e388dd2bf3b94953bd4a277eac2b/crates/cairo-lang-test-plugin/src/inline_macros/assert.rs#L19)):*
> you can solve it in the standard way of solving it by using a wrapper.

Yes. can i use macro complete?

**Review by clint419 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4424)* status: 1 of 6 files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-test-runner/test_data/lib.cairo` line 54 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4424#-NjgIqUY39eXc_fflq1I:-Njgc-TL9A4paJ2crxkd:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/05997e9116b2dac94efe7010195696252bddf174/crates/cairo-lang-test-runner/test_data/lib.cairo#L54)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

revert.
</blockquote></details>

Done.
___
*[`scripts/starknet_test.sh` line 6 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4424#-NjgInvLBXODRrHJivkM:-Njgc0Rq1MYX2sDpF8ek:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/05997e9116b2dac94efe7010195696252bddf174/scripts/starknet_test.sh#L6)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

revert.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4424)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @clint419)

___
*[`crates/cairo-lang-test-plugin/src/inline_macros/assert.rs` line 13 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4424#-NjgcH-d0unzGeWtLHZS:-NjgcH-e9jk_ONlaMFx4:b2nhdkj) ([raw file](https://github.com/starkware-libs/cairo/blob/ebeb425fec64e60fb69d7a6861255721979d5d6f/crates/cairo-lang-test-plugin/src/inline_macros/assert.rs#L13)):*
> ```XML
> use indoc::formatdoc;
> 
> trait CompareAssertionPlugin: NamedPlugin {
> ```

Doc

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4424)* status: all files reviewed, 2 unresolved discussions (waiting on @clint419)

**Review by clint419 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4424)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4424#-NjgIvXSAimL7N-Y54L1:-NjghfaJ7x6XSIaPwQhV:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add test to `corelib/src/test/testing_test.cairo`
</blockquote></details>

Done.

___
___
*[`crates/cairo-lang-test-plugin/src/inline_macros/assert.rs` line 13 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4424#-NjgcH-d0unzGeWtLHZS:-Njghe5D729FMNX1fQyP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ebeb425fec64e60fb69d7a6861255721979d5d6f/crates/cairo-lang-test-plugin/src/inline_macros/assert.rs#L13)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Doc
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4424#-:-Njgin31E4fk4JWlVvr8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @clint419)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4424)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @clint419)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4424#-NjgipZCATs9XPl8Ntbg:-NjgipZCATs9XPl8Ntbh:b-uuj1x0) (no related file):*
@gilbens-starkware for 2nd eye.

___

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, 1 of 3 files at r3, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4424)* status: all files reviewed, 1 unresolved discussion (waiting on @clint419)

___
*[`vscode-cairo/snippets/cairo.json` line 226 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4424#-Njgz-EEB29YmMsx2rpY:-Njgz-EEB29YmMsx2rpZ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d139f412492071abdec731efc9e62ea7cb1e110c/vscode-cairo/snippets/cairo.json#L226)):*
> ```JSON
>     "prefix": "assert_ne!",
>     "body": ["assert_ne!($1, $2);"],
>     "description": "Creates an simple test"
> ```





_Suggestion:_
```JSON
Creates an inline macro for asserting non-equality.
```

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4424)* status: all files reviewed, 1 unresolved discussion (waiting on @clint419)

___
*[`vscode-cairo/snippets/cairo.json` line 226 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4424#-Njgz-EEB29YmMsx2rpY:-NjgzsJm5j4tvnDjuUG-:bgpv2xj) ([raw file](https://github.com/starkware-libs/cairo/blob/d139f412492071abdec731efc9e62ea7cb1e110c/vscode-cairo/snippets/cairo.json#L226)):*
> ```JSON
>     "prefix": "assert_ne!",
>     "body": ["assert_ne!($1, $2);"],
>     "description": "Creates an simple test"
> ```

Maybe
`Creates an assert_ne! macro.`
As it should be short description.

**Review by clint419 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4424)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`vscode-cairo/snippets/cairo.json` line 226 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4424#-Njgz-EEB29YmMsx2rpY:-NjhD8i75815drsB3937:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d139f412492071abdec731efc9e62ea7cb1e110c/vscode-cairo/snippets/cairo.json#L226)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Maybe
`Creates an assert_ne! macro.`
As it should be short description.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4424)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4424#-:-NjhDd0x4n3bl6EP3J4g:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @clint419)

**Pull request merged**
