### PR TITLE
Fix module_main_file for inline submoudules.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1387)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1387)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`crates/semantic/src/diagnostic_test.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1387#-NJdU9Jl3R63vmVdmJ9c:-NJdU9Jl3R63vmVdmJ9d:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/d757425797ce2b18b637b5cd4a05b00060bba0c2/crates/semantic/src/diagnostic_test.rs#L45)):*
> ```XML
> 
> #[derive(Debug)]
> struct AddInlineModuleDummyPlugin {}
> ```

doc



_Code quote:_
```XML
AddInlineModuleDummyPlugin
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1387)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi and @yuvalsw)

___
*[`crates/semantic/src/diagnostic_test.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1387#-NJdU9Jl3R63vmVdmJ9c:-NJdVpwQDPolF_XlAC1w:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d757425797ce2b18b637b5cd4a05b00060bba0c2/crates/semantic/src/diagnostic_test.rs#L45)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1387#-:-NJdXeKw-CPFjlOGEZv5:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/semantic/src/diagnostic_test.rs` line 115 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1387#-NJdXRA1CEgYOxXV4aiF:-NJdXRA1CEgYOxXV4aiG:b-73ph0j) ([raw file](https://github.com/starkware-libs/cairo/blob/b822f62a7d7918a4118573f4e609447393ed5515/crates/semantic/src/diagnostic_test.rs#L115)):*
> ```XML
>         indoc! {r#"
>             error: Unexpected return type. Expected: "core::integer::uint128", found: "core::felt".
>              --> virt2:3:16
> ```

it returns the virtual file, so points to the generated code.
consider adding a TODO somewhere to fix this to point to the original code,



_Code quote:_
```XML
virt2:3:16
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1387)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/semantic/src/diagnostic_test.rs` line 115 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1387#-NJdXRA1CEgYOxXV4aiF:-NJdXidB5Dd7YdT80WO0:b-m18mb6) ([raw file](https://github.com/starkware-libs/cairo/blob/b822f62a7d7918a4118573f4e609447393ed5515/crates/semantic/src/diagnostic_test.rs#L115)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

it returns the virtual file, so points to the generated code.
consider adding a TODO somewhere to fix this to point to the original code,
</blockquote></details>

Why should it point to the original file?, the error is in the generated code.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
I think the description here is correct.

I fix module_main_file  and add a test.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1387#-:-NJdXuVn6JfK17qhuN7W:bi9am3h)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1387)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/semantic/src/diagnostic_test.rs` line 115 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1387#-NJdXRA1CEgYOxXV4aiF:-NJdbnXt7fDp-KaEMLdy:b-wv76d6) ([raw file](https://github.com/starkware-libs/cairo/blob/b822f62a7d7918a4118573f4e609447393ed5515/crates/semantic/src/diagnostic_test.rs#L115)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why should it point to the original file?, the error is in the generated code.
</blockquote></details>

Oh, OK, this is confusing as the same error (but with 5) exists in the original code.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1387)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1387#-:-NJdiYc1CMSjigQlfaIp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
