### PR TITLE
Add empty calldata when no constructor validation

### LINKED ISSUE #3680: feat: Validate empty calldata when deploying without constructor
# Feature Request

**Describe the Feature Request**

Currently, calldata passed to `deploy_syscall` is not validated when the contract doesn't have a constructor. I would expect this to panic as it does in the [blockifier implementation](https://github.com/starkware-libs/blockifier/blob/4af8928fdb82a8a5973595db9da5cee017afc7e7/crates/blockifier/src/execution/entry_point.rs#L367) used in the sequencer.

**Describe Preferred Solution**

Panic when non-empty calldata is passed to `deploy_syscall`, when the contract doesn't have a constructor.

**Related Code**

https://github.com/starkware-libs/cairo/blob/1edcc130fe701820016f9f4af754543b16bfbf67/crates/cairo-lang-runner/src/casm_run/mod.rs#L862-L883

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by ericnordelo**
Fixes #3680

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3681)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3681#-:-N_J1dsh2foUQmyICw14:bnfp4nl)* status: 2 of 5 files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3681#-N_J1f2z7g-kiiVEnNiG:-N_J1f2z7g-kiiVEnNiH:bgz1243) (no related file):*
@spapinistarkware for 2nd eye.

___

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3681)* status: 2 of 5 files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3681#-N_K6ZxIE0t_WxYyry4R:-N_K6ZxIE0t_WxYyry4S:b-hfvbw5) (no related file):*
please also rebase so the clippy changes won't be part of the PR (fixed in main alreay)

___

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3681#-:-N_SQOBj0lkcXda5duV_:bnfp4nl)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3681)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ericnordelo)

**Pull request merged**
