### PR TITLE
changing keyword: func --> fn.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:834d3343

---

**Stack**:
- #1471
- #1470
- #1467 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by gilbens-starkware — APPROVED** [review]
There are some macros which now have $fn:ident (e.g. in parser::test_utils), it seems to work, but maybe it is not advisable as fn is also a rust keyword (and it is highlighted in Reviewable but not in VSCode).

> Reviewed 141 of 141 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1467#-:-NK8EFtf9bznG8Aa6y6d:bd82u01)* status: all files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware, @liorgold2, @orizi, @spapinistarkware, and @yuvalsw)

___
*[`crates/runner/src/lib.rs` line 162 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1467#-NK8BX9IBL9y0dN25HHB:-NK8BX9J4nYWGY9JzoxH:bnu3v7r) ([raw file](https://github.com/starkware-libs/cairo/blob/5f388226a10f47a6a5bff122c0698646df2a2a76/crates/runner/src/lib.rs#L162)):*
> ```XML
>     }
> 
>     /// Returns the final values and type of all if `fn`s returning variables.
> ```

func is the name of the argument to this function.
___
*[`crates/sierra/src/extensions/lib_func.rs` line 229 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1467#-NK8CCZvD6AaEGGSP8tq:-NK8CCZvD6AaEGGSP8tr:b-wr0iqk) ([raw file](https://github.com/starkware-libs/cairo/blob/5f388226a10f47a6a5bff122c0698646df2a2a76/crates/sierra/src/extensions/lib_func.rs#L229)):*
> ```XML
> 
> /// Trait for implementing a specialization generator expecting a single generic param type, and
> /// creating a concrete lib fn containing that type as well.
> ```

libfunc
___
*[`crates/sierra_generator/src/canonical_id_replacer.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1467#-NK8CJ6v0yVdur45jPHF:-NK8CJ6v0yVdur45jPHG:b-wr0iqk) ([raw file](https://github.com/starkware-libs/cairo/blob/5f388226a10f47a6a5bff122c0698646df2a2a76/crates/sierra_generator/src/canonical_id_replacer.rs#L52)):*
> ```XML
>         id: &sierra::ids::ConcreteLibFuncId,
>     ) -> sierra::ids::ConcreteLibFuncId {
>         self.libfunc_ids.get(id).expect("Unexpected lib fn id.").clone()
> ```

libfunc
___
*[`crates/test_utils/src/parse_test_file.rs` line 144 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1467#-NK8DAif0N_KCxR0OnzE:-NK8DAif0N_KCxR0OnzF:b1h46hs) ([raw file](https://github.com/starkware-libs/cairo/blob/5f388226a10f47a6a5bff122c0698646df2a2a76/crates/test_utils/src/parse_test_file.rs#L144)):*
> ```XML
> /// The signature of `fn` should be of the form:
> /// ```ignore
> /// fn fn(
> ```

Maybe it should remain func in here.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1467#-:-NK8FK_XArJaErOLFm4-:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware, @liorgold2, @orizi, @spapinistarkware, and @yuvalsw)

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 34 of 141 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1467)* status: all files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware, @liorgold2, @orizi, and @yuvalsw)

___
*[`crates/parser/src/test_utils.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1467#-NK8FIYI8yAie_pdJLvh:-NK8FIYI8yAie_pdJLvi:byp6rt5) ([raw file](https://github.com/starkware-libs/cairo/blob/5f388226a10f47a6a5bff122c0698646df2a2a76/crates/parser/src/test_utils.rs#L43)):*
> ```XML
> #[macro_export]
> macro_rules! parser_test {
>     ($test_name:ident, $filenames:expr, $fn:ident) => {
> ```

Revert



_Code quote:_
```XML
fn
```

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1467)* status: all files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware, @liorgold2, @orizi, and @yuvalsw)

___
*[`crates/runner/src/lib.rs` line 162 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1467#-NK8FkNO6XQxg6ABYN7g:-NK8FkNP00CLp1tbq35u:bnthkr1) ([raw file](https://github.com/starkware-libs/cairo/blob/5ca9a9140a6f7233f043bcf5dcea500c422e4f5e/crates/runner/src/lib.rs#L162)):*
> ```XML
>     }
> 
>     /// Returns the final values and type of all if `func`s returning variables.
> ```

I actually don't understand the grammar here.



_Code quote:_
```XML
if `func`s return
```
___
*[`crates/semantic/src/test_utils.rs` line 249 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1467#-NK8Fq3h1CGt90kY_5Tj:-NK8Fq3h1CGt90kY_5Tk:b-l6hdjr) ([raw file](https://github.com/starkware-libs/cairo/blob/5ca9a9140a6f7233f043bcf5dcea500c422e4f5e/crates/semantic/src/test_utils.rs#L249)):*
> ```XML
> #[macro_export]
> macro_rules! semantic_test {
>     ($test_name:ident, $filenames:expr, $func:ident) => {
> ```

revert



_Code quote:_
```XML
fun
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1467)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware, @liorgold2, @spapinistarkware, and @yuvalsw)

___
*[`crates/parser/src/test_utils.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1467#-NK8FIYI8yAie_pdJLvh:-NK8KgrbBTn9JapgtIOl:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5f388226a10f47a6a5bff122c0698646df2a2a76/crates/parser/src/test_utils.rs#L43)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Revert
</blockquote></details>

Done.
___
*[`crates/semantic/src/test_utils.rs` line 249 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1467#-NK8Fq3h1CGt90kY_5Tj:-NK8Jmod74linT_LUxY4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5ca9a9140a6f7233f043bcf5dcea500c422e4f5e/crates/semantic/src/test_utils.rs#L249)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

revert
</blockquote></details>

Done.

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1467)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware, @liorgold2, @spapinistarkware, and @yuvalsw)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 2 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1467)* status: 140 of 141 files reviewed, all discussions resolved (waiting on @gilbens-starkware, @ilyalesokhin-starkware, @liorgold2, and @yuvalsw)

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1467)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware, @liorgold2, and @yuvalsw)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1467#-:-NK8anud9OdApNF13T2N:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware, @liorgold2, and @yuvalsw)

**Pull request merged**
