### PR TITLE
Tomerc/adding for loop to semantics

### PR DESCRIPTION
**Pull request by Tomer-StarkWare**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5727)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5727)* status: 0 of 17 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @Tomer-StarkWare, and @TomerStarkware)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5727#-NzbumKM-414h_3ClvpF):*
split commits into different PRs.

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5727)* status: 0 of 17 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @orizi, and @TomerStarkware)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5727#-NzbumKM-414h_3ClvpF):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

split commits into different PRs.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 17 files at r1, 10 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5727)* status: 16 of 17 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware, @Tomer-StarkWare, and @TomerStarkware)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5727#-Nzbxcj626IDfc1bzJJg):*
rename PR.
___
*[`crates/cairo-lang-lowering/src/lower/usage.rs` line 212 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5727#-Nzby8D38Wg-JpA3sahf:-Nzby8D38Wg-JpA3sahg:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/413003490362b05522b71b3b369091b53bf02818/crates/cairo-lang-lowering/src/lower/usage.rs#L212)):*
> ```XML
>             }
>             // TODO(Tomer-StarkWare): Add For loop to lowering
>             Expr::For(_expr) => {}
> ```





_Suggestion:_
```XML
            Expr::For(_expr) => todo!("Handle usages of `for` loop expression"),
```
___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 844 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5727#-NzbyYkZEC9npQI5qSJ2:-NzbyYkZEC9npQI5qSJ3:b-f9r85l) ([raw file](https://github.com/starkware-libs/cairo/blob/413003490362b05522b71b3b369091b53bf02818/crates/cairo-lang-semantic/src/diagnostic.rs#L844)):*
> ```XML
>     ModuleFileNotFound(String),
>     ExpectedIdentifierPattern,
>     ExpectedOptionErrorPropagationType,
> ```

why is this a new error?
don't we already have the same for `let` statements?



_Code quote:_
```XML
    ExpectedIdentifierPattern,
    ExpectedOptionErrorPropagationType,
```
___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 1097 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5727#-NzbySx7BFp_pIANsv2Q:-NzbySx7BFp_pIANsv2R:b-g452n9) ([raw file](https://github.com/starkware-libs/cairo/blob/413003490362b05522b71b3b369091b53bf02818/crates/cairo-lang-semantic/src/diagnostic.rs#L1097)):*
> ```XML
>     MultipleImplementationToTrait {
>         trait_name: SmolStr,
>     },
> ```

aren't these just existing inference errors?



_Code quote:_
```XML
    NoImplementationToTrait {
        trait_name: SmolStr,
    },
    MultipleImplementationToTrait {
        trait_name: SmolStr,
    },
```
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1259 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5727#-Nzbz2r14DVYXjxoYHc1:-Nzbz2r14DVYXjxoYHc2:bvike1a) ([raw file](https://github.com/starkware-libs/cairo/blob/413003490362b05522b71b3b369091b53bf02818/crates/cairo-lang-semantic/src/expr/compute.rs#L1259)):*
> ```XML
>     if syntax.identifier(syntax_db).text(syntax_db) != "in" {
>         ctx.diagnostics.report(syntax, ExpectedInIdentifier);
>     }
> ```

is this already checked in the parser?
if so - just make it an internal error of some kind.



_Code quote:_
```XML
    if syntax.identifier(syntax_db).text(syntax_db) != "in" {
        ctx.diagnostics.report(syntax, ExpectedInIdentifier);
    }
```
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1275 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5727#-Nzbzcxp-jDYDTFWexiJ:-Nzbzcxp-jDYDTFWexiK:boectp3) ([raw file](https://github.com/starkware-libs/cairo/blob/413003490362b05522b71b3b369091b53bf02818/crates/cairo-lang-semantic/src/expr/compute.rs#L1275)):*
> ```XML
>             None,
>             |_, _, _| NoImplementationToTrait { trait_name: "IntoIterator".into() },
>             |_, _, _| MultipleImplementationToTrait { trait_name: "IntoIterator".into() },
> ```

use the inference errors directly if possible (you get them in the closure inputs)



_Code quote:_
```XML
            |_, _, _| NoImplementationToTrait { trait_name: "IntoIterator".into() },
            |_, _, _| MultipleImplementationToTrait { trait_name: "IntoIterator".into() },
```
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1296 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5727#-NzbzRji6bLvBTXFBAu5:-NzbzRji6bLvBTXFBAu6:boectp3) ([raw file](https://github.com/starkware-libs/cairo/blob/413003490362b05522b71b3b369091b53bf02818/crates/cairo-lang-semantic/src/expr/compute.rs#L1296)):*
> ```XML
>         None,
>         |_, _, _| NoImplementationToTrait { trait_name: "Iterator".into() },
>         |_, _, _| MultipleImplementationToTrait { trait_name: "Iterator".into() },
> ```

use the inference errors directly if possible (you get them in the closure inputs)



_Code quote:_
```XML
        |_, _, _| NoImplementationToTrait { trait_name: "Iterator".into() },
        |_, _, _| MultipleImplementationToTrait { trait_name: "Iterator".into() },
```

**Review by TomerStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5727)* status: 16 of 17 files reviewed, 9 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 707 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5727#-NzcVkreEObw9eTZxHbX:-NzcVkreEObw9eTZxHbY:bwheoyw) ([raw file](https://github.com/starkware-libs/cairo/blob/413003490362b05522b71b3b369091b53bf02818/crates/cairo-lang-semantic/src/diagnostic.rs#L707)):*
> ```XML
>             }
>             SemanticDiagnosticKind::ExpectedInIdentifier => {
>                 "Identifier is not 'in' as it should be.".into()
> ```

"missing `in` in `for` loop"



_Code quote:_
```XML
"Identifier is not 'in' as it should be."
```
___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 844 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5727#-NzcWnsX7OgZuksuzGh4:-NzcWnsX7OgZuksuzGh5:b6auzwk) ([raw file](https://github.com/starkware-libs/cairo/blob/413003490362b05522b71b3b369091b53bf02818/crates/cairo-lang-semantic/src/diagnostic.rs#L844)):*
> ```XML
>     ModuleFileNotFound(String),
>     ExpectedIdentifierPattern,
>     ExpectedOptionErrorPropagationType,
> ```

I don't think they are being used,



_Code quote:_
```XML
    ExpectedIdentifierPattern,
    ExpectedOptionErrorPropagationType,
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5727)* status: 13 of 17 files reviewed, 9 unresolved discussions (waiting on @gilbens-starkware, @orizi, and @TomerStarkware)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5727#-Nzbxcj626IDfc1bzJJg):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rename PR.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/usage.rs` line 212 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5727#-Nzby8D38Wg-JpA3sahf:-NzcTyan2NgMoKokZXaJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/413003490362b05522b71b3b369091b53bf02818/crates/cairo-lang-lowering/src/lower/usage.rs#L212)):*
> ```XML
>             }
>             // TODO(Tomer-StarkWare): Add For loop to lowering
>             Expr::For(_expr) => {}
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 707 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5727#-NzcVkreEObw9eTZxHbX:-Nzce3ESBVGfAbJVzBM8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/413003490362b05522b71b3b369091b53bf02818/crates/cairo-lang-semantic/src/diagnostic.rs#L707)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

"missing `in` in `for` loop"
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 844 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5727#-NzbyYkZEC9npQI5qSJ2:-NzcYBrEBWqwycfoZKh9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/413003490362b05522b71b3b369091b53bf02818/crates/cairo-lang-semantic/src/diagnostic.rs#L844)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why is this a new error?
don't we already have the same for `let` statements?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 844 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5727#-NzcWnsX7OgZuksuzGh4:-NzcYC5TApJJMvRVQIon:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/413003490362b05522b71b3b369091b53bf02818/crates/cairo-lang-semantic/src/diagnostic.rs#L844)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

I don't think they are being used,
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 1097 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5727#-NzbySx7BFp_pIANsv2Q:-NzcqlTiBr76cECL3zlm:b8gg4oc) ([raw file](https://github.com/starkware-libs/cairo/blob/413003490362b05522b71b3b369091b53bf02818/crates/cairo-lang-semantic/src/diagnostic.rs#L1097)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

aren't these just existing inference errors?
</blockquote></details>

There are similar ones for Method calls
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1259 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5727#-Nzbz2r14DVYXjxoYHc1:-NzcbuUN7PgFcT8Czso1:bujm9bd) ([raw file](https://github.com/starkware-libs/cairo/blob/413003490362b05522b71b3b369091b53bf02818/crates/cairo-lang-semantic/src/expr/compute.rs#L1259)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is this already checked in the parser?
if so - just make it an internal error of some kind.
</blockquote></details>

Not checked in Parser, added TODO
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1275 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5727#-Nzbzcxp-jDYDTFWexiJ:-Nzd7W-DBgcypYY5yWok:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/413003490362b05522b71b3b369091b53bf02818/crates/cairo-lang-semantic/src/expr/compute.rs#L1275)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

use the inference errors directly if possible (you get them in the closure inputs)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1296 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5727#-NzbzRji6bLvBTXFBAu5:-Nzd7WMv5Harr5Ykbt4z:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/413003490362b05522b71b3b369091b53bf02818/crates/cairo-lang-semantic/src/expr/compute.rs#L1296)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

use the inference errors directly if possible (you get them in the closure inputs)
</blockquote></details>

Done.

**Comment by Tomer-StarkWare** [comment]
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1279 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5727#-NzeE_Ic2gCe7JqxCkiT:-Nzvdb9yDF6H8nEpEZug:b-yzvutl) ([raw file](https://github.com/starkware-libs/cairo/blob/fbf6058f1590a7d6a371612d4833abf5e8680b64/crates/cairo-lang-semantic/src/expr/compute.rs#L1279)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why is it unreachable?
can't there be multiple implementations somehow?
</blockquote></details>

There can be multiple implementations, this is covered in the function above (NoImplementationOfTrait), which checks if the NoImplementation is due to lack of implementation, or not a specific one (multiple implementations).
The next code checks whether there are multiple traits, which is impossible since we know the specific Traits.

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5727)* status: all files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware, @orizi, and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/usage.rs` line 212 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5727#-NzeDzejDt90g6yIRxHn:-NzvcMia7sNalaEXM70b:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fbf6058f1590a7d6a371612d4833abf5e8680b64/crates/cairo-lang-lowering/src/lower/usage.rs#L212)):*
> ```XML
>             }
>             // TODO(Tomer-StarkWare): Add For loop to lowering
>             Expr::For(_expr) => todo!("Handle usages of `for` loop expression"),
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1259 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5727#-Nzbz2r14DVYXjxoYHc1:-Nzvkwsz7bO2_s7i0Bs6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/413003490362b05522b71b3b369091b53bf02818/crates/cairo-lang-semantic/src/expr/compute.rs#L1259)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

So don't add a specific diagnostic to immediately remove it.
use a generic unsupported.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1304 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5727#-NzeEgs84CavsIa_ibl_:-Nzve7WY5elAXAGhzLTz:b-2q0j3o) ([raw file](https://github.com/starkware-libs/cairo/blob/fbf6058f1590a7d6a371612d4833abf5e8680b64/crates/cairo-lang-semantic/src/expr/compute.rs#L1304)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

Sorry about that.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5727)* status: all files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware, @Tomer-StarkWare, and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 812 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5727#-Nzvl9m_BGTUeMtzIca4:-Nzvl9m_BGTUeMtzIca5:b-f8j5p2) ([raw file](https://github.com/starkware-libs/cairo/blob/79a2869b88e026649d3d4d759515ae2d134532bb/crates/cairo-lang-semantic/src/diagnostic.rs#L812)):*
> ```XML
>                 } else {
>                     format!(
>                         "mplementation of trait `{}` could not be called on type `{}`.\n{}",
> ```

also - i don't understand the grammar.



_Suggestion:_
```XML
                    format!(
                        "Implementation of trait `{}` could not be called on type `{}`.\n{}",
```
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1279 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5727#-NzeE_Ic2gCe7JqxCkiT:-NzvlQnJEueiaBvAR4Ja:bdayxuu) ([raw file](https://github.com/starkware-libs/cairo/blob/fbf6058f1590a7d6a371612d4833abf5e8680b64/crates/cairo-lang-semantic/src/expr/compute.rs#L1279)):*
<details><summary><i>Previously, Tomer-StarkWare wrote…</i></summary><blockquote>

There can be multiple implementations, this is covered in the function above (NoImplementationOfTrait), which checks if the NoImplementation is due to lack of implementation, or not a specific one (multiple implementations).
The next code checks whether there are multiple traits, which is impossible since we know the specific Traits.
</blockquote></details>

so make the actual unreachable test reflect that.
(where it was checked already, for example)
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1304 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5727#-NzeEgs84CavsIa_ibl_:-NzvlZFN0KJgaJ4mmNKY:b-bk62x7) ([raw file](https://github.com/starkware-libs/cairo/blob/fbf6058f1590a7d6a371612d4833abf5e8680b64/crates/cairo-lang-semantic/src/expr/compute.rs#L1304)):*
<details><summary><i>Previously, Tomer-StarkWare wrote…</i></summary><blockquote>

Sorry about that.
</blockquote></details>

still - same as above.

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5727)* status: 15 of 17 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware, @orizi, and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 812 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5727#-Nzvl9m_BGTUeMtzIca4:-NzvmRYEBU9umnxTRO1R:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/79a2869b88e026649d3d4d759515ae2d134532bb/crates/cairo-lang-semantic/src/diagnostic.rs#L812)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

also - i don't understand the grammar.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1279 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5727#-NzeE_Ic2gCe7JqxCkiT:-NzvqXvp2Clojrtv5B94:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fbf6058f1590a7d6a371612d4833abf5e8680b64/crates/cairo-lang-semantic/src/expr/compute.rs#L1279)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

so make the actual unreachable test reflect that.
(where it was checked already, for example)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1304 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5727#-NzeEgs84CavsIa_ibl_:-NzvqYCF3a0ckpD-2rJ9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fbf6058f1590a7d6a371612d4833abf5e8680b64/crates/cairo-lang-semantic/src/expr/compute.rs#L1304)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

still - same as above.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5727)* status: 16 of 17 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware, @Tomer-StarkWare, and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 812 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5727#-Nzvl9m_BGTUeMtzIca4:-Nzw16caA6lIFW7poQG0:b6x8v90) ([raw file](https://github.com/starkware-libs/cairo/blob/79a2869b88e026649d3d4d759515ae2d134532bb/crates/cairo-lang-semantic/src/diagnostic.rs#L812)):*
<details><summary><i>Previously, Tomer-StarkWare wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I still don't understand the text.

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5727)* status: 15 of 17 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware, @orizi, and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 812 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5727#-Nzvl9m_BGTUeMtzIca4:-Nzw5dW--UB7prLJweAy:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/79a2869b88e026649d3d4d759515ae2d134532bb/crates/cairo-lang-semantic/src/diagnostic.rs#L812)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I still don't understand the text.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5727)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware, @Tomer-StarkWare, and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 812 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5727#-Nzvl9m_BGTUeMtzIca4:-NzwCfnU3cFUGP63CUtR:b2ni1bp) ([raw file](https://github.com/starkware-libs/cairo/blob/79a2869b88e026649d3d4d759515ae2d134532bb/crates/cairo-lang-semantic/src/diagnostic.rs#L812)):*
<details><summary><i>Previously, Tomer-StarkWare wrote…</i></summary><blockquote>

Done.
</blockquote></details>

f2f

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5727)* status: 16 of 17 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware, @orizi, and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 812 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5727#-Nzvl9m_BGTUeMtzIca4:-NzwEBRC7ngLpdNPV7pQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/79a2869b88e026649d3d4d759515ae2d134532bb/crates/cairo-lang-semantic/src/diagnostic.rs#L812)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

f2f
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5727#-:-NzwMepc8ME8tBCNowr4:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

**Review by TomerStarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5727)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
