### PR TITLE
Changing the prioritization in output Diagnostics.

### PR DESCRIPTION
**Pull request by Tomer-StarkWare**

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 7 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6884)* status: 7 of 11 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @Tomer-StarkWare, and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/closure` line 430 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6884#-OEOiJsxAh3x-ECEe_ni:-OEOiJsxAh3x-ECEe_nj:buahti7) ([raw file](https://github.com/starkware-libs/cairo/blob/5e8e0c5de34c57733feefffb9534e544689d2209/crates/cairo-lang-semantic/src/expr/test_data/closure#L430)):*
> ```
> 
> //! > expected_diagnostics
> error: Trait has no implementation in context: core::ops::function::Fn::<{closure@lib.cairo:5:15: 5:27}, (core::felt252,)>.
> ```

@TomerStarkware - suggestions for a better error?



_Code quote:_
```
error: Trait has no implementation in context: core::ops::function::Fn::<{closure@lib.cairo:5:15: 5:27}, (core::felt252,)>.
```
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2792 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6884#-OEOiCTl-RPpfyxtDHJc:-OEOiCTl-RPpfyxtDHJd:b-hay66z) ([raw file](https://github.com/starkware-libs/cairo/blob/5e8e0c5de34c57733feefffb9534e544689d2209/crates/cairo-lang-semantic/src/expr/compute.rs#L2792)):*
> ```XML
>             },
>         )?;
> ```

revert.

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6884)* status: 7 of 11 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @orizi, and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2792 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6884#-OEOiCTl-RPpfyxtDHJc:-OEOozkb8v7LFeFfIKh4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5e8e0c5de34c57733feefffb9534e544689d2209/crates/cairo-lang-semantic/src/expr/compute.rs#L2792)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

revert.
</blockquote></details>

Done.

**Review by TomerStarkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6884)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware, @orizi, and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/closure` line 430 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6884#-OEOiJsxAh3x-ECEe_ni:-OEOngBuDFrRxsMi9V5O:b87am0e) ([raw file](https://github.com/starkware-libs/cairo/blob/44a4e0b000415daedfee19918e47e9092122d5b2/crates/cairo-lang-semantic/src/expr/test_data/closure#L430)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

@TomerStarkware - suggestions for a better error?
</blockquote></details>

this is correct `bar` can only accept tuple of 3 not tuple of `1`, if we want different error we should probably report FnTrait errors differently
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 764 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6884#-OEOpxM18ZwH0EWRKTpC:-OEOpxM18ZwH0EWRKTpD:b-pp70rm) ([raw file](https://github.com/starkware-libs/cairo/blob/44a4e0b000415daedfee19918e47e9092122d5b2/crates/cairo-lang-semantic/src/expr/inference.rs#L764)):*
> ```XML
>             ));
>         }
>         if let Some((var, ambiguity)) = self.ambiguous.first() {
> ```

maybe ambigious last? or skip `WillNotInfer` at first and only report it after the types

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6884)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware, @Tomer-StarkWare, and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 764 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6884#-OEOpxM18ZwH0EWRKTpC:-OEOrQ8k2mkq-hh-MY9A:bsanhjy) ([raw file](https://github.com/starkware-libs/cairo/blob/44a4e0b000415daedfee19918e47e9092122d5b2/crates/cairo-lang-semantic/src/expr/inference.rs#L764)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

maybe ambigious last? or skip `WillNotInfer` at first and only report it after the types
</blockquote></details>

i agree.
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 774 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6884#-OEOrakO1UxZme1yFWJs:-OEOrakP0_z-fEEe3WQE:b-wrflwr) ([raw file](https://github.com/starkware-libs/cairo/blob/44a4e0b000415daedfee19918e47e9092122d5b2/crates/cairo-lang-semantic/src/expr/inference.rs#L774)):*
> ```XML
>                 return Some((InferenceVar::Type(var.id), InferenceError::TypeNotInferred(ty)));
>             }
>         }
> ```

save and find if it is "will not infer" - and skip if nothing else.



_Code quote:_
```XML
        if let Some((var, ambiguity)) = self.ambiguous.first() {
            let var = *var;
            // Note: do not rewrite `ambiguity`, since it is expressed in canonical variables.
            return Some((InferenceVar::Impl(var), InferenceError::Ambiguity(ambiguity.clone())));
        }
        for (id, var) in self.type_vars.iter().enumerate() {
            if self.type_assignment(LocalTypeVarId(id)).is_none() {
                let ty = TypeLongId::Var(*var).intern(self.db);
                return Some((InferenceVar::Type(var.id), InferenceError::TypeNotInferred(ty)));
            }
        }
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6884)* status: 4 of 11 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware, @Tomer-StarkWare, and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 775 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6884#-OEP60Aj4O96iH2gD9BJ:-OEP60Aj4O96iH2gD9BK:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2e673c298e0e39d7e90e34c2d91d4ab9568fdb0a/crates/cairo-lang-semantic/src/expr/inference.rs#L775)):*
> ```XML
>                 fallback_ret = 
>                     Some((InferenceVar::Impl(*var), InferenceError::Ambiguity(ambiguity.clone())));
>             }
> ```





_Suggestion:_
```XML
            // Note: do not rewrite `ambiguity`, since it is expressed in canonical variables.
            let ret = Some((InferenceVar::Impl(*var), InferenceError::Ambiguity(ambiguity.clone())));
            if !matches!(ambiguity, Ambiguity::WillNotInfer(_)) {
                return ret;
            } else {
                fallback_ret = ret;
            }
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6884)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware, @orizi, and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 775 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6884#-OEP60Aj4O96iH2gD9BJ:-OER2LstAMjYm4nELyVt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2e673c298e0e39d7e90e34c2d91d4ab9568fdb0a/crates/cairo-lang-semantic/src/expr/inference.rs#L775)):*
> ```XML
>                 fallback_ret = 
>                     Some((InferenceVar::Impl(*var), InferenceError::Ambiguity(ambiguity.clone())));
>             }
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6884#-:-OESb-qKCLaO_e2WZJt-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @TomerStarkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6884)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware, @Tomer-StarkWare, and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2763 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6884#-OEUGfXE1xY5fuWgKxV_:-OEUGfXE1xY5fuWgKxVa:b-hay66z) ([raw file](https://github.com/starkware-libs/cairo/blob/92467cb80e6b6a5abc586bf9ea927a027480ec3e/crates/cairo-lang-semantic/src/expr/compute.rs#L2763)):*
> ```XML
>             },
>         )?;
> ```

revert.

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6884)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware, @orizi, and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2763 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6884#-OEUGfXE1xY5fuWgKxV_:-OEUU_1g1l0m5XS9ky7y:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/92467cb80e6b6a5abc586bf9ea927a027480ec3e/crates/cairo-lang-semantic/src/expr/compute.rs#L2763)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

revert.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6884#-:-OEUWJfv6tafsXOuGI6Q:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @TomerStarkware)

**Review by TomerStarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6884)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
