### PR TITLE
Dori/bitwise impl

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1395)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1, 2 of 9 files at r2, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1395)* status: 3 of 12 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/casm/src/run.rs` line 146 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1395#-NJkLAZnD9qRtJYzCQub:-NJkLAZnD9qRtJYzCQuc:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/737839ea1174375379403db4e529ccd66acf2589/crates/casm/src/run.rs#L146)):*
> ```XML
>                 let bitwise_ptr = match ptr {
>                     ResOperand::Deref(val) => get_relocatable_from_cellref(*val)?,
>                     ResOperand::BinOp(op) => match op.op {
> ```





_Suggestion:_
```XML
                let bitwise_ptr = match ptr {
                    ResOperand::Deref(val) => get_relocatable_from_cellref(*val)?,
                    ResOperand::BinOp(BinOpOperand {op: Operation::Add, a, b}) =>
                        get_relocatable_from_cellref(op.a)?.add_int_mod(&get_val(op.b.clone())?, &prime)?,
                    _ => {
                        panic!("Unexpected param type for Bitwise hint {ptr}.")
                    }
                };
```

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 9 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1395)* status: 8 of 12 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1395)* status: 8 of 12 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @orizi)

___
*[`crates/casm/src/run.rs` line 146 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1395#-NJkLAZnD9qRtJYzCQub:-NJnr4HT8nh_0w-gI5E1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/737839ea1174375379403db4e529ccd66acf2589/crates/casm/src/run.rs#L146)):*
> ```XML
>                 let bitwise_ptr = match ptr {
>                     ResOperand::Deref(val) => get_relocatable_from_cellref(*val)?,
>                     ResOperand::BinOp(op) => match op.op {
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 9 files at r1, 1 of 9 files at r2, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1395#-:-NJo-ckkA5-LhCnWZdFo:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/casm/src/hints/mod.rs` line 149 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1395#-NJo-IxJ0AS5kQldy1LQ:-NJo-IxJ0AS5kQldy1LR:b-w05f1h) ([raw file](https://github.com/starkware-libs/cairo/blob/9198b2a5673b32159f6e50adbfc78c819bd91abe/crates/casm/src/hints/mod.rs#L149)):*
> ```XML
>                 write!(f, ") ")?;
>             }
>             Hint::Bitwise { ptr } => write!(f, " bitwise_handler(bitwise_ptr={}) ", ptr)?,
> ```

add at least a todo that makes this into a legal python string computing the value.
(as our prints needs to be a valid python call)



_Code quote:_
```XML
bitwise_handler(bitwise_ptr={}
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1395)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/casm/src/hints/mod.rs` line 149 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1395#-NJo-IxJ0AS5kQldy1LQ:-NJo0uav6KOyA9Za3F3z:bbfptbw) ([raw file](https://github.com/starkware-libs/cairo/blob/9198b2a5673b32159f6e50adbfc78c819bd91abe/crates/casm/src/hints/mod.rs#L149)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add at least a todo that makes this into a legal python string computing the value.
(as our prints needs to be a valid python call)
</blockquote></details>

Done.
Should I also add macro rules for this [here](https://github.com/starkware-libs/cairo2/blob/dori/bitwise-impl/crates/casm/src/inline.rs#L198)?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1395)* status: 11 of 12 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

___
*[`crates/casm/src/hints/mod.rs` line 149 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1395#-NJo-IxJ0AS5kQldy1LQ:-NJo4U1QBcxT80gcUZ7R:bwxmro8) ([raw file](https://github.com/starkware-libs/cairo/blob/9198b2a5673b32159f6e50adbfc78c819bd91abe/crates/casm/src/hints/mod.rs#L149)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Done.
Should I also add macro rules for this [here](https://github.com/starkware-libs/cairo2/blob/dori/bitwise-impl/crates/casm/src/inline.rs#L198)?
</blockquote></details>

no - as it is used only in a single place.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, 2 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1395)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`corelib/integer.cairo` line 157 at r7](https://reviewable.io/reviews/starkware-libs/cairo/1395#-NJoEE5ADzp75l8iGNJL:-NJoEE5ADzp75l8iGNJM:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2a68e85a9346cd5072c6f9d051766f2e81fd5909/corelib/integer.cairo#L157)):*
> ```Cairo
> extern func bitwise(a: u128, b: u128) -> (u128, u128, u128) implicits(Bitwise) nopanic;
> func u128_and(a: u128, b: u128) -> u128 implicits(Bitwise) nopanic {
>     let (v, _, _) = bitwise(a, b);
> ```





_Suggestion:_
```Cairo
func u128_and(a: u128, b: u128) -> u128 implicits(Bitwise) nopanic {
    let (v, _, _) = bitwise(a, b);
    v
}
func u128_or(a: u128, b: u128) -> u128 implicits(Bitwise) nopanic {
    let (_, v, _) = bitwise(a, b);
    v
}
func u128_xor(a: u128, b: u128) -> u128 implicits(Bitwise) nopanic {
    let (_, _, v) = bitwise(a, b);
    v
}
```
___
*[`crates/semantic/src/corelib.rs` line 316 at r7](https://reviewable.io/reviews/starkware-libs/cairo/1395#-NJoE0P088aEz_-5pAYB:-NJoE0P1DNDbOHsyQCMK:bi1hm58) ([raw file](https://github.com/starkware-libs/cairo/blob/2a68e85a9346cd5072c6f9d051766f2e81fd5909/crates/semantic/src/corelib.rs#L316)):*
> ```XML
>         BinaryOperator::Or(_) if [type1, type2] == [u128_ty, u128_ty] => "u128_or",
>         BinaryOperator::Or(_) => return unsupported_operator("|"),
>         BinaryOperator::Xor(_) if [type1, type2] == [bool_ty, bool_ty] => "bool_xor",
> ```

as well as tests



_Suggestion:_
```XML
        BinaryOperator::Xor(_) if [type1, type2] == [bool_ty, bool_ty] => "bool_xor",
        BinaryOperator::Xor(_) if [type1, type2] == [u128_ty, u128_ty] => "u128_xor",
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1395)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/integer.cairo` line 157 at r7](https://reviewable.io/reviews/starkware-libs/cairo/1395#-NJoEE5ADzp75l8iGNJL:-NJoFTWHBHQWhseGTSKb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2a68e85a9346cd5072c6f9d051766f2e81fd5909/corelib/integer.cairo#L157)):*
> ```Cairo
> extern func bitwise(a: u128, b: u128) -> (u128, u128, u128) implicits(Bitwise) nopanic;
> func u128_and(a: u128, b: u128) -> u128 implicits(Bitwise) nopanic {
>     let (v, _, _) = bitwise(a, b);
> ```

Done.
___
*[`crates/semantic/src/corelib.rs` line 316 at r7](https://reviewable.io/reviews/starkware-libs/cairo/1395#-NJoE0P088aEz_-5pAYB:-NJoFSga5ustF3K8B1JU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2a68e85a9346cd5072c6f9d051766f2e81fd5909/crates/semantic/src/corelib.rs#L316)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

as well as tests
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1395)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
