### PR TITLE
Report diagnostics for impl functions.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1990)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1990)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`corelib/integer.cairo` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1990#-NN5ikJiBx0KQYqRHG2M:-NN5ikJiBx0KQYqRHG2N:b-768f6) ([raw file](https://github.com/starkware-libs/cairo/blob/045d7633916392d029792707c98746fc4a29943c/corelib/integer.cairo#L59)):*
> ```Cairo
> 
> impl U128Add of Add::<u128> {
>     #[inline(always)]
> ```

all of these did not work?



_Code quote:_
```Cairo

    #[inline(always)]
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1990)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1990#-NN5j0N23os0ijd9Y-Ad:-NN5j0N23os0ijd9Y-Ae:bn46mxr) ([raw file](https://github.com/starkware-libs/cairo/blob/c036b37b7ab148308ede72836e5f967273a101a4/crates/cairo-lang-lowering/src/db.rs#L223)):*
> ```XML
>             ModuleItemId::Trait(_) => {}
>             ModuleItemId::Impl(impl_id) => {
>                 // TODO(ilya): Fix `Variable not dropped.` for generic variable.
> ```

please expand - i don't understand what it means or the relation to here



_Code quote:_
```XML
                // TODO(ilya): Fix `Variable not dropped.` for generic variable.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/db.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1990#-NN5j0N23os0ijd9Y-Ad:-NN5kn4KDzUFu7zbMEz8:b-qb1bsi) ([raw file](https://github.com/starkware-libs/cairo/blob/c036b37b7ab148308ede72836e5f967273a101a4/crates/cairo-lang-lowering/src/db.rs#L223)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

please expand - i don't understand what it means or the relation to here
</blockquote></details>

I'm getting:
error: Variable not dropped.
 --> option.cairo:33:26
            Option::Some(_) => true,
                         ^

error: Variable not dropped.
 --> option.cairo:39:26
            Option::Some(_) => false,

from the corelib.

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/integer.cairo` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1990#-NN5ikJiBx0KQYqRHG2M:-NN5ktdB34xNq49SmUWK:b-4g50k6) ([raw file](https://github.com/starkware-libs/cairo/blob/045d7633916392d029792707c98746fc4a29943c/corelib/integer.cairo#L59)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

all of these did not work?
</blockquote></details>

yes, they have an early return

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1990)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1990#-NN5j0N23os0ijd9Y-Ad:-NN5lP3IDqQ3bI_NFUc9:b-sh4k9m) ([raw file](https://github.com/starkware-libs/cairo/blob/c036b37b7ab148308ede72836e5f967273a101a4/crates/cairo-lang-lowering/src/db.rs#L223)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I'm getting:
error: Variable not dropped.
 --> option.cairo:33:26
            Option::Some(_) => true,
                         ^

error: Variable not dropped.
 --> option.cairo:39:26
            Option::Some(_) => false,

from the corelib.
</blockquote></details>

I'd rather you enable this and comment the corelib code. Is it possible?

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1990)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1990#-NN5j0N23os0ijd9Y-Ad:-NN5m5xI24caHy5GS5bb:b1bt9c4) ([raw file](https://github.com/starkware-libs/cairo/blob/c036b37b7ab148308ede72836e5f967273a101a4/crates/cairo-lang-lowering/src/db.rs#L223)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I'd rather you enable this and comment the corelib code. Is it possible?
</blockquote></details>

please expand the content of this todo.

**Review by yuvalsw — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1990)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`corelib/integer.cairo` line 467 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1990#-NN5qSKAAd6dUj83q_Oe:-NN5qSKAAd6dUj83q_Of:b-iquegi) ([raw file](https://github.com/starkware-libs/cairo/blob/045d7633916392d029792707c98746fc4a29943c/corelib/integer.cairo#L467)):*
> ```Cairo
> 
> impl U256Mul of Mul::<u256> {
>     #[inline(always)]
> ```

Why do you remove inlining for everything?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1990)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`corelib/integer.cairo` line 467 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1990#-NN5qSKAAd6dUj83q_Oe:-NN5xMLu5gpdneroUedF:bdblbq2) ([raw file](https://github.com/starkware-libs/cairo/blob/045d7633916392d029792707c98746fc4a29943c/corelib/integer.cairo#L467)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Why do you remove inlining for everything?
</blockquote></details>

Because those functions have early return and currently they can't be inlined.
___
*[`crates/cairo-lang-lowering/src/db.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1990#-NN5j0N23os0ijd9Y-Ad:-NN5xLTH4wA6TYmCyPAv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c036b37b7ab148308ede72836e5f967273a101a4/crates/cairo-lang-lowering/src/db.rs#L223)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

please expand the content of this todo.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1990)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1990#-:-NN5y_th9V2S9yvtbQRQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
