### PR TITLE
Don't report inference diagnostics if there are other diagnostics.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5930)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/items/tests/early_conform` line 1140 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5930#-O0m0u0H87pEK5Ejw2Bh:-O0m0u0H87pEK5Ejw2Bi:b-699lk1) ([raw file](https://github.com/starkware-libs/cairo/blob/cf17397c94ec9c0b6c6eae6e939c5f536d88bb36/crates/cairo-lang-semantic/src/items/tests/early_conform#L1140)):*
> ```
>                                           ^*****^
> 
> error: Type annotations needed. Failed to infer ?0.
> ```

I wanted to skip only those errors; I'll try a different approach.



_Code quote:_
```
error: Type annotations needed. Failed to infer ?0.
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 8 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5930)* status: 8 of 10 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/tests` line 180 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5930#-O0m1t7w4Ea63rDJF3S1:-O0m1t7w4Ea63rDJF3S2:b3x8xps) ([raw file](https://github.com/starkware-libs/cairo/blob/cf17397c94ec9c0b6c6eae6e939c5f536d88bb36/crates/cairo-lang-semantic/src/diagnostic_test_data/tests#L180)):*
> ```
>              ^******^
> 
> error: Mismatched types. The type `core::bool` cannot be created from a numeric literal.
> ```

This seemed like a good diag
___
*[`crates/cairo-lang-semantic/src/expr/test_data/function_call` line 181 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5930#-O0m2Nzd4U0mlu-XVrn-:-O0m2Nzd4U0mlu-XVrn0:b-tplvqj) ([raw file](https://github.com/starkware-libs/cairo/blob/cf17397c94ec9c0b6c6eae6e939c5f536d88bb36/crates/cairo-lang-semantic/src/expr/test_data/function_call#L181)):*
> ```
> 
> error: Trait has no implementation in context: core::traits::Add::<test::MyStruct>.
>  --> lib.cairo:13:5
> ```

Seems like a regression as well.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5930)* status: 4 of 11 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/tests` line 180 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5930#-O0m1t7w4Ea63rDJF3S1:-O0mElj19MNSXnPzVBUd:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cf17397c94ec9c0b6c6eae6e939c5f536d88bb36/crates/cairo-lang-semantic/src/diagnostic_test_data/tests#L180)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

This seemed like a good diag
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/function_call` line 181 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5930#-O0m2Nzd4U0mlu-XVrn-:-O0mEkZ92b6CASjzGsJX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cf17397c94ec9c0b6c6eae6e939c5f536d88bb36/crates/cairo-lang-semantic/src/expr/test_data/function_call#L181)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Seems like a regression as well.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5930#-:-O0mM9ojCJx4ZYgPcOuq:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
