### PR TITLE
add explicit boolean xor

### PR DESCRIPTION
**Pull request by zuphitf**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1580)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1580)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @zuphitf)

___
*[`crates/cairo-sierra/src/extensions/modules/boolean.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1580#-NKhVb7BAgihvL8ZHWBu:-NKhVb7BAgihvL8ZHWBv:b-308xeu) ([raw file](https://github.com/starkware-libs/cairo/blob/14ae1fe8e4f1a9521b6fda1876ec1e874481c1fa/crates/cairo-sierra/src/extensions/modules/boolean.rs#L73)):*
> ```XML
>         context: &dyn SignatureSpecializationContext,
>     ) -> Result<LibFuncSignature, SpecializationError> {
>         boolean_libfunc_signature(context, true, false)
> ```

False, false

As you do allocate vars which you do not return 
___
*[`crates/cairo-sierra-to-casm/src/invocations/boolean.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1580#-NKhWL-U8iR7e5mxpY6T:-NKhWL-U8iR7e5mxpY6U:b-p9sjef) ([raw file](https://github.com/starkware-libs/cairo/blob/14ae1fe8e4f1a9521b6fda1876ec1e874481c1fa/crates/cairo-sierra-to-casm/src/invocations/boolean.rs#L71)):*
> ```XML
> 
>     // Outputs `a * (1 - b) + (1 - a) * b = (a + b) - 2ab`.
>     Ok(builder.build(
> ```

Use the casm builder in all cases where we don't have only a reference expression as result.

**Review by zuphitf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1580)* status: 1 of 8 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-sierra/src/extensions/modules/boolean.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1580#-NKhVb7BAgihvL8ZHWBu:-NKhhyFl6g-99FmFkACa:bs7wuav) ([raw file](https://github.com/starkware-libs/cairo/blob/14ae1fe8e4f1a9521b6fda1876ec1e874481c1fa/crates/cairo-sierra/src/extensions/modules/boolean.rs#L73)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

False, false

As you do allocate vars which you do not return 
</blockquote></details>

Done  
___
*[`crates/cairo-sierra-to-casm/src/invocations/boolean.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1580#-NKhWL-U8iR7e5mxpY6T:-NKhhv4a7ZuvnjQP8UHP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/14ae1fe8e4f1a9521b6fda1876ec1e874481c1fa/crates/cairo-sierra-to-casm/src/invocations/boolean.rs#L71)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Use the casm builder in all cases where we don't have only a reference expression as result.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1580)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @zuphitf)

___
*[`crates/cairo-sierra-ap-change/src/core_libfunc_ap_change.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1580#-NKhjwG76SKaAH2slpzV:-NKhjwG76SKaAH2slpzW:b-10u4go) ([raw file](https://github.com/starkware-libs/cairo/blob/954cca0ee244fa04b88746c54723209eb4d76093/crates/cairo-sierra-ap-change/src/core_libfunc_ap_change.rs#L35)):*
> ```XML
>             BoolConcreteLibFunc::And(_) => vec![ApChange::Known(0)],
>             BoolConcreteLibFunc::Not(_) => vec![ApChange::Known(1)],
>             BoolConcreteLibFunc::Xor(_) => vec![ApChange::Known(4)],
> ```

This isn't correct, add the validation that the ap-change is valid in the libfunc.

**Comment by zuphitf** [comment]
*[`crates/cairo-sierra-ap-change/src/core_libfunc_ap_change.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1580#-NKhjwG76SKaAH2slpzV:-NKi5Uel9himrpXz6AYe:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/954cca0ee244fa04b88746c54723209eb4d76093/crates/cairo-sierra-ap-change/src/core_libfunc_ap_change.rs#L35)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

This isn't correct, add the validation that the ap-change is valid in the libfunc.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1580)* status: 1 of 8 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @zuphitf)

___
*[`crates/cairo-sierra-to-casm/src/invocations/boolean.rs` line 80 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1580#-NKlT90k5whK05s1Z1Cc:-NKlT90k5whK05s1Z1Cd:bopcmku) ([raw file](https://github.com/starkware-libs/cairo/blob/b78fdb4f8f7f06667e8acd31675683fd88b8f1ba/crates/cairo-sierra-to-casm/src/invocations/boolean.rs#L80)):*
> ```XML
>         tempvar ab = a*b;
>         tempvar two_ab = ab + ab;
>         tempvar a_plus_b = a + b;
> ```

won't this work?



_Suggestion:_
```XML
    casm_build_extend! {casm_builder,
        tempvar diff = a - b;
        let xor = diff * diff;
    }
```

**Comment by zuphitf** [comment]
*[`crates/cairo-sierra-to-casm/src/invocations/boolean.rs` line 80 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1580#-NKlT90k5whK05s1Z1Cc:-NKlo5Xv27IOlrcaZHMU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b78fdb4f8f7f06667e8acd31675683fd88b8f1ba/crates/cairo-sierra-to-casm/src/invocations/boolean.rs#L80)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

won't this work?
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r4, 2 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1580)* status: 5 of 8 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @zuphitf)

___
*[`crates/cairo-sierra-gas/src/core_libfunc_cost_base.rs` line 64 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1580#-NKloUJ64qLHXGps-wmo:-NKloUJ7AuyOrBUBc6rZ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5c85dc45949287baa7d920df86c42ae38e3db99d/crates/cairo-sierra-gas/src/core_libfunc_cost_base.rs#L64)):*
> ```XML
>         Bool(BoolConcreteLibfunc::And(_)) => vec![ops.const_cost(0)],
>         Bool(BoolConcreteLibfunc::Not(_)) => vec![ops.const_cost(1)],
>         Bool(BoolConcreteLibfunc::Xor(_)) => vec![ops.const_cost(3)],
> ```





_Suggestion:_
```XML
        Bool(BoolConcreteLibfunc::Xor(_)) => vec![ops.const_cost(1)],
```
___
*[`crates/cairo-sierra-to-casm/src/invocations/boolean.rs` line 77 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1580#-NKloxYz3UoNl61laNPp:-NKloxYz3UoNl61laNPq:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5c85dc45949287baa7d920df86c42ae38e3db99d/crates/cairo-sierra-to-casm/src/invocations/boolean.rs#L77)):*
> ```XML
> 
>     // Outputs `(a - b)^2`.
>     casm_build_extend! {casm_builder,
> ```





_Suggestion:_
```XML
    // Outputs `(a - b)^2`.
    casm_build_extend! {casm_builder,
        tempvar diff = a - b;
        let xor = diff * diff;
    }
    Ok(builder
        .build_from_casm_builder(casm_builder, [("Fallthrough", &[&[xor]], None)]))
}
```

**Comment by zuphitf** [comment]
*[`crates/cairo-sierra-gas/src/core_libfunc_cost_base.rs` line 64 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1580#-NKloUJ64qLHXGps-wmo:-NKlpBrIATTwqeTl3YoZ:b-aw4znq) ([raw file](https://github.com/starkware-libs/cairo/blob/5c85dc45949287baa7d920df86c42ae38e3db99d/crates/cairo-sierra-gas/src/core_libfunc_cost_base.rs#L64)):*
> ```XML
>         Bool(BoolConcreteLibfunc::And(_)) => vec![ops.const_cost(0)],
>         Bool(BoolConcreteLibfunc::Not(_)) => vec![ops.const_cost(1)],
>         Bool(BoolConcreteLibfunc::Xor(_)) => vec![ops.const_cost(3)],
> ```

Yep just noticed it too. Done



_Code quote:_
```XML
Bool(BoolConcreteLibfunc::Xor(_)) => vec![ops.const_cost(3)],
```

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 5 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1580)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @zuphitf)

**Review by zuphitf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1580)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-sierra-to-casm/src/invocations/boolean.rs` line 77 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1580#-NKloxYz3UoNl61laNPp:-NKlsktB7w19ejCMW7dV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5c85dc45949287baa7d920df86c42ae38e3db99d/crates/cairo-sierra-to-casm/src/invocations/boolean.rs#L77)):*
> ```XML
> 
>     // Outputs `(a - b)^2`.
>     casm_build_extend! {casm_builder,
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1580#-:-NKlu_s00FAnCbEmjPH1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
