### PR TITLE
Added #[cfg(test)] feature.

### PR DESCRIPTION
**Pull request by orizi**
Should reduce tests runtime.

---

**Stack**:
- #1559
- #1558 ⬅
- #1557

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1558)

### CODE REVIEW

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1558)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-plugins/src/config.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1558#-NKRn2DQ0I7oRoyYfQKg:-NKRn2DQ0I7oRoyYfQKh:bqp7xda) ([raw file](https://github.com/starkware-libs/cairo/blob/7be82dc9475e65ed6597b00edf3c9850b1136389/crates/cairo-plugins/src/config.rs#L19)):*
> ```XML
> impl MacroPlugin for ConfigPlugin {
>     fn generate_code(&self, db: &dyn SyntaxGroup, item_ast: ast::Item) -> PluginResult {
>         if let ast::Item::Module(module_ast) = item_ast {
> ```

TOK: Why only on modules?
___
*[`crates/cairo-plugins/src/config.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1558#-NKRnRDjATDTEkyjjcAi:-NKRnRDjATDTEkyjjcAj:b-fb2nh) ([raw file](https://github.com/starkware-libs/cairo/blob/7be82dc9475e65ed6597b00edf3c9850b1136389/crates/cairo-plugins/src/config.rs#L25)):*
> ```XML
>                         if !self
>                             .configs
>                             .contains(args.arg_list(db).as_syntax_node().get_text(db).trim())
> ```

This is not technically correct. We should maybe make a get_text() version with no trivia.



_Code quote:_
```XML
get_text(db).trim()
```
___
*[`crates/cairo-test-runner/src/cli.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1558#-NKRnrtg05U9b-6s6avh:-NKRnrtg05U9b-6s6avi:bibwuqb) ([raw file](https://github.com/starkware-libs/cairo/blob/7be82dc9475e65ed6597b00edf3c9850b1136389/crates/cairo-test-runner/src/cli.rs#L56)):*
> ```XML
>     let args = Args::parse();
> 
>     let mut plugins: Vec<Arc<dyn SemanticPlugin>> = vec![
> ```

Consider using get_default_plugins(), and looking up the Config plugin. Just to make sure it is kept consistent with defualt plugins.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1558)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-plugins/src/config.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1558#-NKRn2DQ0I7oRoyYfQKg:-NKSCGn20bFtRJ84zNd_:b-iv71ay) ([raw file](https://github.com/starkware-libs/cairo/blob/7be82dc9475e65ed6597b00edf3c9850b1136389/crates/cairo-plugins/src/config.rs#L19)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

TOK: Why only on modules?
</blockquote></details>

It sounds logical to me to not allow more fine grained ignore, but I don't have any strong opinions on that
___
*[`crates/cairo-plugins/src/config.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1558#-NKRnRDjATDTEkyjjcAi:-NKSCUfL6fuAcbgB2BW9:b-fnfut9) ([raw file](https://github.com/starkware-libs/cairo/blob/7be82dc9475e65ed6597b00edf3c9850b1136389/crates/cairo-plugins/src/config.rs#L25)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This is not technically correct. We should maybe make a get_text() version with no trivia.
</blockquote></details>

Sounds like a good idea - not the first place I'm running into this

**Review by spapinistarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1558)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-plugins/src/config.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1558#-NKRn2DQ0I7oRoyYfQKg:-NKSCr-_24IKYIFYK_Mm:b-7db4qt) ([raw file](https://github.com/starkware-libs/cairo/blob/7be82dc9475e65ed6597b00edf3c9850b1136389/crates/cairo-plugins/src/config.rs#L19)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

It sounds logical to me to not allow more fine grained ignore, but I don't have any strong opinions on that
</blockquote></details>

In rust you can put it on any item. TODO is  ok.

**Review by spapinistarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1558)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1558)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-test-runner/src/cli.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1558#-NKRnrtg05U9b-6s6avh:-NKSJC8Y6DQVhqq7mcPV:b13eof2) ([raw file](https://github.com/starkware-libs/cairo/blob/7be82dc9475e65ed6597b00edf3c9850b1136389/crates/cairo-test-runner/src/cli.rs#L56)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Consider using get_default_plugins(), and looking up the Config plugin. Just to make sure it is kept consistent with defualt plugins.
</blockquote></details>

Wouldn't the fact that the plugins are all arc prevent me from editing a plugin?

**Review by spapinistarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1558)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-test-runner/src/cli.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1558#-NKRnrtg05U9b-6s6avh:-NKSPTZN8J_o1y7ve37Y:b-nwcdfr) ([raw file](https://github.com/starkware-libs/cairo/blob/7be82dc9475e65ed6597b00edf3c9850b1136389/crates/cairo-test-runner/src/cli.rs#L56)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Wouldn't the fact that the plugins are all arc prevent me from editing a plugin?
</blockquote></details>

Right. You can try to recreate it instead. (pop and push).
Anyway, maybe just add a TODO for now,

**Comment by orizi** [comment]
Closing pull request: commit has gone away

**Pull request closed without merging**
