### PR TITLE
Fix ec_state_init signature.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2978)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2978)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs` line 310 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2978#-NUHAWrd1jIFzVtyrYXu:-NUHAWrd1jIFzVtyrYXv:bqni0xd) ([raw file](https://github.com/starkware-libs/cairo/blob/1aea12b5823be952a8d528657093cc45775e5f6e/crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs#L310)):*
> ```XML
>         tempvar expected_y2;
>     }
>     compute_ec_equation(&mut casm_builder, random_x, random_y, y2, expected_y2);
> ```

I removed this function because it had too many arguments after this change.



_Code quote:_
```XML
 compute_ec_equation(&mut casm_builder, random_x, random_y, y2, expected_y2);
```

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2978)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs` line 145 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2978#-NUHX1pA-WJrnD2MUQro:-NUHX1pA-WJrnD2MUQrp:b-8yobmc) ([raw file](https://github.com/starkware-libs/cairo/blob/4f45e8b5251be28d8dcd765cbcc15166d4cec10d/crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs#L145)):*
> ```XML
>     // Check if `(x, y)` is on the curve, by computing `y^2` and `x^3 + x + beta`.
>     casm_build_extend! {casm_builder,
>         tempvar aux0;
> ```

Can you put them after `y2` and `expected_y2` - it'll reduce the diff in the PR.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs` line 183 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2978#-NUHX9OREWftPWj8guZ-:-NUHX9OREWftPWj8guZ0:b-e0o0fx) ([raw file](https://github.com/starkware-libs/cairo/blob/4f45e8b5251be28d8dcd765cbcc15166d4cec10d/crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs#L183)):*
> ```XML
>         tempvar aux2;
>         tempvar rhs;
> ```

Remove this blank line.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2978)* status: 2 of 6 files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs` line 179 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2978#-NUHXDQa-corE-ylGvFU:-NUHXDQa-corE-ylGvFV:brhumzt) ([raw file](https://github.com/starkware-libs/cairo/blob/4f45e8b5251be28d8dcd765cbcc15166d4cec10d/crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs#L179)):*
> ```XML
>     casm_build_extend! {casm_builder,
>         let orig_range_check = range_check;
>         tempvar aux0;
> ```

Same here.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs` line 316 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2978#-NUHXH_hAsuPmfbZBENf:-NUHXH_hAsuPmfbZBENg:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/4f45e8b5251be28d8dcd765cbcc15166d4cec10d/crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs#L316)):*
> ```XML
>     // Sample a random point on the curve.
>     casm_build_extend! {casm_builder,
>         // auxilliary variables.
> ```





_Suggestion:_
```XML
// Auxilliary variables.
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs` line 323 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2978#-NUHXLJCELElFVAV2eN9:-NUHXLJCELElFVAV2eNA:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/4f45e8b5251be28d8dcd765cbcc15166d4cec10d/crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs#L323)):*
> ```XML
>         tempvar expected_y2;
> 
>         // ec state variables (need to be at the top of the stack)
> ```





_Suggestion:_
```XML
 // EC state variables (need to be at the top of the stack).
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs` line 329 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2978#-NUHXlk03ORjC9Td3hil:-NUHXlk03ORjC9Td3him:b-ledadz) ([raw file](https://github.com/starkware-libs/cairo/blob/4f45e8b5251be28d8dcd765cbcc15166d4cec10d/crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs#L329)):*
> ```XML
>         hint RandomEcPoint {} into { x: random_x, y: random_y };
>         // Initalize `random_ptr` and copy the random point into it.
>         const ec_state_size = 2;
> ```

Rename (unrelated to the PR).
(note `state` -> `point`)



_Suggestion:_
```XML
EC_POINT_SIZE
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs` line 335 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2978#-NUHX_Yj8kYdxq22K20x:-NUHX_Yj8kYdxq22K20y:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/4f45e8b5251be28d8dcd765cbcc15166d4cec10d/crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs#L335)):*
> ```XML
>     }
> 
>     // Assert the random point is on the curve.
> ```





_Suggestion:_
```XML
// Assert that the random point is on the curve.
```

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2978)* status: 5 of 6 files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs` line 329 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2978#-NUHXlk03ORjC9Td3hil:-NUHaQ1OBMUuF-pU2Z_7:bszhstn) ([raw file](https://github.com/starkware-libs/cairo/blob/4f45e8b5251be28d8dcd765cbcc15166d4cec10d/crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs#L329)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Rename (unrelated to the PR).
(note `state` -> `point`)
</blockquote></details>

casm_build_extend are still variables so no capital case.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2978)* status: 1 of 6 files reviewed, 7 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs` line 145 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2978#-NUHX1pA-WJrnD2MUQro:-NUHahIo8OsxpjpI7Xe6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4f45e8b5251be28d8dcd765cbcc15166d4cec10d/crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs#L145)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Can you put them after `y2` and `expected_y2` - it'll reduce the diff in the PR.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs` line 179 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2978#-NUHXDQa-corE-ylGvFU:-NUHhKi31Q8t9cBsM-KE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4f45e8b5251be28d8dcd765cbcc15166d4cec10d/crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs#L179)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs` line 183 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2978#-NUHX9OREWftPWj8guZ-:-NUHawLFCueXJ_phT5sd:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4f45e8b5251be28d8dcd765cbcc15166d4cec10d/crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs#L183)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Remove this blank line.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs` line 316 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2978#-NUHXH_hAsuPmfbZBENf:-NUHhMGb9iaZ219MZpbN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4f45e8b5251be28d8dcd765cbcc15166d4cec10d/crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs#L316)):*
> ```XML
>     // Sample a random point on the curve.
>     casm_build_extend! {casm_builder,
>         // auxilliary variables.
> ```

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs` line 323 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2978#-NUHXLJCELElFVAV2eN9:-NUHa9yhDHuz3zytShx3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4f45e8b5251be28d8dcd765cbcc15166d4cec10d/crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs#L323)):*
> ```XML
>         tempvar expected_y2;
> 
>         // ec state variables (need to be at the top of the stack)
> ```

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs` line 335 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2978#-NUHX_Yj8kYdxq22K20x:-NUHb-THCJxVe3kVPh_F:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4f45e8b5251be28d8dcd765cbcc15166d4cec10d/crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs#L335)):*
> ```XML
>     }
> 
>     // Assert the random point is on the curve.
> ```

Done.



_Code quote:_
```XML
// auxilliary variables.
```

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2978)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`tests/e2e_test_data/libfuncs/ec` line 355 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2978#-NUHjkDv4Z7Qm4tA2nry:-NUHjkDv4Z7Qm4tA2nrz:bwqu0sg) ([raw file](https://github.com/starkware-libs/cairo/blob/184e88b8e616bff431506f5c72a8dbf837818bb4/tests/e2e_test_data/libfuncs/ec#L355)):*
> ```
> [ap + 3] = [ap + -3] + 3141592653589793238462643383279502884197169399375105820974944592307816406665, ap++;
> [ap + -1] = [ap + 1] + [ap + 2], ap++;
> [ap + -3] = [ap + -2], ap++;
> ```

This is redundant; remove `expected_y2` and use `y2` instead.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2978)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`tests/e2e_test_data/libfuncs/ec` line 355 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2978#-NUHjkDv4Z7Qm4tA2nry:-NUI-8580-VRhazS24Hi:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/184e88b8e616bff431506f5c72a8dbf837818bb4/tests/e2e_test_data/libfuncs/ec#L355)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

This is redundant; remove `expected_y2` and use `y2` instead.
</blockquote></details>

Done.



_Code quote:_
```
[ap + -7] = [ap + -6], ap+
```

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2978#-:-NULQ_kzAYRI1QrGfYZo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 5 files at r3, 3 of 5 files at r4, 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2978)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
