### PR TITLE
Improved interpolate_patched to return RewriteNode

### PR DESCRIPTION
**Pull request by yuvalsw**
…to using formatdoc

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1579)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1579)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-semantic/src/patcher.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1579#-NKgSR3QDCI6-SN-iNgj:-NKgSR3QDCI6-SN-iNgk:b-sq43c) ([raw file](https://github.com/starkware-libs/cairo/blob/6184f604a83b5c756a96b0ba613eca16ae8b806d/crates/cairo-semantic/src/patcher.rs#L51)):*
> ```XML
>     /// Each substring of the form `$<name>$` is replaced with syntax nodes from `patches`.
>     /// A `$$` substring is replaced with `$`.
>     pub fn new_interpolate_patched(
> ```

looks good, You can remove the new



_Suggestion:_
```XML
 interpolate_patched
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-starknet/src/plugin.rs` line 141 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1579#-NKgnVsKAztMDV1igWQZ:-NKgnVsKAztMDV1igWQ_:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6184f604a83b5c756a96b0ba613eca16ae8b806d/crates/cairo-starknet/src/plugin.rs#L141)):*
> ```XML
>             _ => {}
>         };
>         // TODO(ygggg): item includes the leading and trailing trivia... Remove them. Add a function
> ```





_Suggestion:_
```XML
yg
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1579)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-semantic/src/patcher.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1579#-NKgSR3QDCI6-SN-iNgj:-NKgrDXc18IZBY1CE9Ua:br2bn34) ([raw file](https://github.com/starkware-libs/cairo/blob/6184f604a83b5c756a96b0ba613eca16ae8b806d/crates/cairo-semantic/src/patcher.rs#L51)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

looks good, You can remove the new
</blockquote></details>

This is kinda c'tor, so I wanted the 'new'.
___
*[`crates/cairo-starknet/src/plugin.rs` line 141 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1579#-NKgnVsKAztMDV1igWQZ:-NKgrBfo3n5T973QNLDl:bty4x76) ([raw file](https://github.com/starkware-libs/cairo/blob/6184f604a83b5c756a96b0ba613eca16ae8b806d/crates/cairo-starknet/src/plugin.rs#L141)):*
> ```XML
>             _ => {}
>         };
>         // TODO(ygggg): item includes the leading and trailing trivia... Remove them. Add a function
> ```

Moved to another PR

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1579)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-semantic/src/patcher.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1579#-NKgSR3QDCI6-SN-iNgj:-NKhBlvx9qA8S6fzEsN1:bpr5cjo) ([raw file](https://github.com/starkware-libs/cairo/blob/6184f604a83b5c756a96b0ba613eca16ae8b806d/crates/cairo-semantic/src/patcher.rs#L51)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

This is kinda c'tor, so I wanted the 'new'.
</blockquote></details>

from_ast is also a constructor.



_Code quote:_
```XML
from_ast
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1579)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-semantic/src/patcher.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1579#-NKgSR3QDCI6-SN-iNgj:-NKhFnRSEmjkbyfwvJAK:b-oqupkl) ([raw file](https://github.com/starkware-libs/cairo/blob/6184f604a83b5c756a96b0ba613eca16ae8b806d/crates/cairo-semantic/src/patcher.rs#L51)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

from_ast is also a constructor.
</blockquote></details>

do you have a strong objection to remove the new?

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1579)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-semantic/src/patcher.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1579#-NKgSR3QDCI6-SN-iNgj:-NKhf9Gr4KDhfMPeCgcx:b-n92w8o) ([raw file](https://github.com/starkware-libs/cairo/blob/6184f604a83b5c756a96b0ba613eca16ae8b806d/crates/cairo-semantic/src/patcher.rs#L51)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

do you have a strong objection to remove the new?
</blockquote></details>

no, removed.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1579#-:-NKhf7u85YEsY4M26P_R:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 3 of 6 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1579)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
