### PR TITLE
Better stack tracking for stack construct.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4588)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4588)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4588#-NlwILfJ-OfPuy7dpERA:-NlwILfJ-OfPuy7dpERB:b-6aj9u0) (no related file):*
wouldn't this cause generation of sierra not compilable by current sierra-to-casm?
if so - change target to sierra-minor-update.

___

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4588)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4588#-NlwILfJ-OfPuy7dpERA:-Nlw_bNc6C_a8MubXmJ2:b3rduw3) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

wouldn't this cause generation of sierra not compilable by current sierra-to-casm?
if so - change target to sierra-minor-update.
</blockquote></details>

I think we need to split the `OutputVarInfo` from sierra_to_casm, putting it there only creates backward compatibility issues :(

___

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4588)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4588#-NlwILfJ-OfPuy7dpERA:-NlwdBnN0yvM722aBQzb:bjf2bsr) (no related file):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I think we need to split the `OutputVarInfo` from sierra_to_casm, putting it there only creates backward compatibility issues :(
</blockquote></details>

I think the exact oposite is true - you changed this to generate better sierra code - but if it was somewhere else we wouldn't have been able to see you broke the code generation.

___

**Comment by ilyalesokhin-starkware** [comment]
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I think the exact oposite is true - you changed this to generate better sierra code - but if it was somewhere else we wouldn't have been able to see you broke the code generation.
</blockquote></details>

I 99.9% sure that the generated code is valid in the old sierra\_to\_casm.

Do you want me to add this as a patch in sierra-gen, i.e. change the signature of struct_construct only in sierra-gen?

**Comment by ilyalesokhin-starkware** [comment]
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I 99.9% sure that the generated code is valid in the old sierra\_to\_casm.

Do you want me to add this as a patch in sierra-gen, i.e. change the signature of struct_construct only in sierra-gen?
</blockquote></details>

nvm, I'm wrong :(
I always forget that we changed sierra-to-casm to rely on the `OutputVarReferenceInfo` instead of just tracking the references.
https://github.com/starkware-libs/cairo/blob/ee4ab2b33f4fdefcc9bb42bffcd1487f5d084f14/crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs#L222

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4588)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4588#-NlwILfJ-OfPuy7dpERA:-NlwkYHRB5cSBtulGkdi:b-558ny0) (no related file):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

nvm, I'm wrong :(
I always forget that we changed sierra-to-casm to rely on the `OutputVarReferenceInfo` instead of just tracking the references.
https://github.com/starkware-libs/cairo/blob/ee4ab2b33f4fdefcc9bb42bffcd1487f5d084f14/crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs#L222
</blockquote></details>

so i guess you need to change target.

___

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4588)* status: 0 of 40 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4588#-NlwILfJ-OfPuy7dpERA:-NmBfpN40f1qB7gwpPaH:bb7f2mf) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

so i guess you need to change target.
</blockquote></details>

done

___

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 28 of 38 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4588)* status: 30 of 40 files reviewed, 1 unresolved discussion

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 10 of 38 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4588#-:-NmBh-FE2h1VFgZ6IBl_:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
