### PR TITLE
Added support for oct and bin literals.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2621)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
TODO: Make formatter strip leading 0s

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2621#-:-NRaubls98gpzShXveLQ:b-lamq4k)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-parser/src/lexer.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2621#-NRauEOs6FpWz9oxlR2W:-NRauEOs6FpWz9oxlR2X:b-uh3fnk) ([raw file](https://github.com/starkware-libs/cairo/blob/a8e21b1b06873aff65d0071e30de93c582a086f0/crates/cairo-lang-parser/src/lexer.rs#L135)):*
> ```XML
>         };
>         // Not a special case - so just reading the rest of the digits.
>         if !special {
> ```

Can you put this in the else? instead of having `special`.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2621)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-parser/src/lexer.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2621#-NRauEOs6FpWz9oxlR2W:-NRav9eJEwb5uyKWgIkD:b-oedltq) ([raw file](https://github.com/starkware-libs/cairo/blob/a8e21b1b06873aff65d0071e30de93c582a086f0/crates/cairo-lang-parser/src/lexer.rs#L135)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Can you put this in the else? instead of having `special`.
</blockquote></details>

there are 2 elses - you'd prefer having this in both?

**Review by mkaput — COMMENTED** [review]
> TODO: Make formatter strip leading 0s

I'm not sure that's good? Rustfmt doesn't do this and I would find this surprising. Perhaps I write a series of `0b` flags; I would want to use zeros for padding:

```
let flag1 = 0b00001;
let flag2 = 0b00010;
let flag3 = 0b00100;
...
```

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2621#-:-NRavjScAGly2Tl5YbkP:b-3avy5n)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by orizi — COMMENTED** [review]
i think for the dec case it makes sense - but less so to the more "data" based ones.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2621#-:-NRawFrQCKhUUa4Wz9T6:bjdia7k)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2621#-:-NRb58nOEAtBMQaphtv6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2621)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
