### PR TITLE
Serde with versioning for Sierra Program representation

### PR DESCRIPTION
**Pull request by MrDenkoV**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3862)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3862)* status: 4 of 13 files reviewed, 2 unresolved discussions (waiting on @mkaput and @MrDenkoV)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3862#-NbJWGWT0shR7lIqwtKI:-NbJWGWT0shR7lIqwtKJ:bv466wk) (no related file):*
I think you should add a `VersionedProgram` or something similar, and simply read it.
Failure to read the version itself should happen by comparing the version by whoever is reading this.

___
___
*[`crates/cairo-lang-sierra/Cargo.toml` line 31 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3862#-NbJUM_pCiZHgY47ZfFN:-NbJUM_pCiZHgY47ZfFO:b-iio0s9) ([raw file](https://github.com/starkware-libs/cairo/blob/34c1ec664dda3237fa3c933c637aa04399a9847a/crates/cairo-lang-sierra/Cargo.toml#L31)):*
> ```TOML
> 
> [dev-dependencies]
> cairo-lang-test-utils = { path = "../cairo-lang-test-utils", version = "2.1.0-rc0" }
> ```

do not include versions in dev-deps



_Suggestion:_
```TOML
cairo-lang-test-utils = { path = "../cairo-lang-test-utils" }
```

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 8 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3862)* status: 9 of 13 files reviewed, 4 unresolved discussions (waiting on @MrDenkoV and @orizi)

___
*[`crates/cairo-lang-sierra/Cargo.toml` line 25 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3862#-NbJWPpq9Ou4CyjdO9iN:-NbJWPpq9Ou4CyjdO9iO:b-940em0) ([raw file](https://github.com/starkware-libs/cairo/blob/34c1ec664dda3237fa3c933c637aa04399a9847a/crates/cairo-lang-sierra/Cargo.toml#L25)):*
> ```TOML
> salsa.workspace = true
> serde.workspace = true
> serde_json.workspace = true
> ```

Do I see correctly that this is only used in tests? If so, please move this to `[dev-dependencies]`
___
*[`crates/cairo-lang-sierra/src/lib.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3862#-NbJVU6L31eWOu3fs0T0:-NbJVU6L31eWOu3fs0T1:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/34c1ec664dda3237fa3c933c637aa04399a9847a/crates/cairo-lang-sierra/src/lib.rs#L19)):*
> ```XML
> pub mod fmt;
> pub mod ids;
> mod lang_version_id;
> ```





_Suggestion:_
```XML
pub mod lang_version_id;
```

**Review by mkaput — COMMENTED** [review]
> Reviewed 1 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3862)* status: 9 of 13 files reviewed, 4 unresolved discussions (waiting on @MrDenkoV and @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 4 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3862)* status: all files reviewed, 4 unresolved discussions (waiting on @MrDenkoV)

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 22 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3862)* status: 3 of 24 files reviewed, 5 unresolved discussions (waiting on @MrDenkoV and @orizi)

___
*[`crates/cairo-lang-sierra/src/program.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3862#-Nby53tQ88l4MXlJ-cjM:-Nby53tQ88l4MXlJ-cjN:b-rukuth) ([raw file](https://github.com/starkware-libs/cairo/blob/9ad28528025d9da4bc0bf9c37777f1013183dfbd/crates/cairo-lang-sierra/src/program.rs#L24)):*
> ```XML
> }
> 
> impl TryFrom<VersionedProgram> for Program {
> ```

I doubt the sense of existence of this impl. It hides the notion of version expectation behind Rust's type inference: when you call `try_from` you are not explicit what Sierra version do you expect here and I'm not sure if this is a good thing.

I wonder if it wouldn't be better here to have an explicit `into_v1(VersionedProgram) -> Result<Program>` method, wdyt?

**Review by mkaput — COMMENTED** [review]
> Reviewed 2 of 22 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3862)* status: 5 of 24 files reviewed, 5 unresolved discussions (waiting on @MrDenkoV and @orizi)

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 22 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3862)* status: 6 of 24 files reviewed, 6 unresolved discussions (waiting on @MrDenkoV and @orizi)

___
*[`crates/cairo-lang-sierra/src/program_registry_test.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3862#-Nby5hdn0a2zcYzO8iTd:-Nby5hdn0a2zcYzO8iTe:bfgpb0c) ([raw file](https://github.com/starkware-libs/cairo/blob/9ad28528025d9da4bc0bf9c37777f1013183dfbd/crates/cairo-lang-sierra/src/program_registry_test.rs#L61)):*
> ```XML
>                 .unwrap()
>                 .try_into()
>                 .unwrap()
> ```

These changes seems to be not needed, as you map `Ok` variant to `()` anyway later on

**Review by MrDenkoV — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3862)* status: 3 of 24 files reviewed, 7 unresolved discussions (waiting on @mkaput and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3862#-NbJWGWT0shR7lIqwtKI:-NbydXwcCrAhBA5FHKeB:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I think you should add a `VersionedProgram` or something similar, and simply read it.
Failure to read the version itself should happen by comparing the version by whoever is reading this.
</blockquote></details>

Done.

___
___
*[`crates/bin/sierra-compile/src/main.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3862#-Nbyu3kw0QT5Rw5MFO8U:-Nbyu3kw0QT5Rw5MFO8V:b-wow71u) ([raw file](https://github.com/starkware-libs/cairo/blob/4b199e50952a0d867140cd120a775adf0cd7979e/crates/bin/sierra-compile/src/main.rs#L41)):*
> ```XML
>         gas_usage_check,
>     )
>     .with_context(|| "Compilation failed.")?;
> ```

Should we convert `VersionedProgram` to the `Program` as it is now, or perhaps change the `cairo_lang_sierra_to_casm::compiler::compile` to take `&VersionedProgram` as an argument? @orizi 



_Code quote:_
```XML
    let Ok(program) = ProgramParser::new().parse(&sierra_code).unwrap().into_v1() else {
        anyhow::bail!(indoc! {"
            Failed to parse sierra program.
            Note: StarkNet contracts should be compiled with `starknet-sierra-compile`."
        })
    };

    let gas_usage_check = true;
    let cairo_program = cairo_lang_sierra_to_casm::compiler::compile(
        &program,
        &calc_metadata(&program, Default::default())
            .with_context(|| "Failed calculating Sierra variables.")?,
        gas_usage_check,
    )
    .with_context(|| "Compilation failed.")?;
```
___
*[`crates/cairo-lang-sierra/Cargo.toml` line 25 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3862#-NbJWPpq9Ou4CyjdO9iN:-NbJaD4k6nA7uHtco4LF:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/34c1ec664dda3237fa3c933c637aa04399a9847a/crates/cairo-lang-sierra/Cargo.toml#L25)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Do I see correctly that this is only used in tests? If so, please move this to `[dev-dependencies]`
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/Cargo.toml` line 31 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3862#-NbJUM_pCiZHgY47ZfFN:-NbJaC2OE1lUmdUCaiwY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/34c1ec664dda3237fa3c933c637aa04399a9847a/crates/cairo-lang-sierra/Cargo.toml#L31)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

do not include versions in dev-deps
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/program.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3862#-Nby53tQ88l4MXlJ-cjM:-Nbytij3D8m3EAvJqRK-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9ad28528025d9da4bc0bf9c37777f1013183dfbd/crates/cairo-lang-sierra/src/program.rs#L24)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I doubt the sense of existence of this impl. It hides the notion of version expectation behind Rust's type inference: when you call `try_from` you are not explicit what Sierra version do you expect here and I'm not sure if this is a good thing.

I wonder if it wouldn't be better here to have an explicit `into_v1(VersionedProgram) -> Result<Program>` method, wdyt?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/program_registry_test.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3862#-Nby5hdn0a2zcYzO8iTd:-NbyPsrkDhCz7iNyzuDg:b-xn8b0n) ([raw file](https://github.com/starkware-libs/cairo/blob/9ad28528025d9da4bc0bf9c37777f1013183dfbd/crates/cairo-lang-sierra/src/program_registry_test.rs#L61)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

These changes seems to be not needed, as you map `Ok` variant to `()` anyway later on
</blockquote></details>

I believe it is needed, as it is passed as an argument to the `ProgramRegistry::new()`, expecting `&Program` and not `&VersionedProgram`, before the map.
However, if required, I can modify it to accept a `&VersionedProgram` argument.
___
*[`crates/cairo-lang-sierra/src/lib.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3862#-NbJVU6L31eWOu3fs0T0:-NbJa81a2lnFJuPaKo3i:bss4a2b) ([raw file](https://github.com/starkware-libs/cairo/blob/34c1ec664dda3237fa3c933c637aa04399a9847a/crates/cairo-lang-sierra/src/lib.rs#L19)):*
> ```XML
> pub mod fmt;
> pub mod ids;
> mod lang_version_id;
> ```

Removed.

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 8 of 22 files at r2, 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3862)* status: all files reviewed, 5 unresolved discussions (waiting on @mkaput, @MrDenkoV, and @orizi)

___
*[`crates/cairo-lang-sierra/src/program.rs` line 12 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3862#-Nc0mhQe6oBkzKb8MOxp:-Nc0mhQe6oBkzKb8MOxq:b-7hbpla) ([raw file](https://github.com/starkware-libs/cairo/blob/4b199e50952a0d867140cd120a775adf0cd7979e/crates/cairo-lang-sierra/src/program.rs#L12)):*
> ```XML
> };
> 
> /// Version of the Sierra Program.
> ```

wdyt?



_Suggestion:_
```XML
/// Version-tagged representation of Sierra program.
///
/// Always prefer using this struct in APIs instead of inner ones.
```
___
*[`crates/cairo-lang-sierra/tests/format_test.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3862#-Nc0o0gb5objQWhTfz_a:-Nc0o0gb5objQWhTfz_b:bm17la4) ([raw file](https://github.com/starkware-libs/cairo/blob/4b199e50952a0d867140cd120a775adf0cd7979e/crates/cairo-lang-sierra/tests/format_test.rs#L80)):*
> ```XML
>         parser
>             .parse(indoc! {"
>                 // Some comment.
> ```

Is there any difference between these two strings? Couldn't we just use it once in a variable?

**Review by MrDenkoV — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3862)* status: 18 of 24 files reviewed, 5 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-sierra/src/program.rs` line 12 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3862#-Nc0mhQe6oBkzKb8MOxp:-Nc1PUjo8PcQPprhhiNN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4b199e50952a0d867140cd120a775adf0cd7979e/crates/cairo-lang-sierra/src/program.rs#L12)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

wdyt?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/tests/format_test.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3862#-Nc0o0gb5objQWhTfz_a:-Nc1P5bUE4bve3D-kwex:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4b199e50952a0d867140cd120a775adf0cd7979e/crates/cairo-lang-sierra/tests/format_test.rs#L80)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Is there any difference between these two strings? Couldn't we just use it once in a variable?
</blockquote></details>

Done.

**Review by mkaput — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3862)* status: all files reviewed, 3 unresolved discussions (waiting on @mkaput and @orizi)

**Review by mkaput — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3862#-:-Nc1lWayAarSgAwsBNTn:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @mkaput and @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 22 files at r2, 1 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3862)* status: all files reviewed, 2 unresolved discussions (waiting on @mkaput and @MrDenkoV)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3862#-Nc2IvJ71L4nM4QClTrw:-Nc2IvJ71L4nM4QClTrx:bv0uxwq) (no related file):*
VersionedProgram needs to be a fully external wrapper.
Do not change anything in the sierra crate - just wrap the basic existing class, to allow version for your external serde.

___

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3862)* status: all files reviewed, 2 unresolved discussions (waiting on @mkaput, @MrDenkoV, and @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3862)* status: all files reviewed, 2 unresolved discussions (waiting on @MrDenkoV)

___
*[`crates/bin/sierra-compile/src/main.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3862#-Nbyu3kw0QT5Rw5MFO8U:-NcRLtlWAPUYSU2VZ7FT:b-oapeq3) ([raw file](https://github.com/starkware-libs/cairo/blob/4b199e50952a0d867140cd120a775adf0cd7979e/crates/bin/sierra-compile/src/main.rs#L41)):*
<details><summary><i>Previously, MrDenkoV wrote…</i></summary><blockquote>

Should we convert `VersionedProgram` to the `Program` as it is now, or perhaps change the `cairo_lang_sierra_to_casm::compiler::compile` to take `&VersionedProgram` as an argument? @orizi
</blockquote></details>

you should not affect any of the other crates - the external scarb wrapper for compilation can handle the versioning.
Just add the versioned artifact - i don't want any of our binaries to currently be sierra version dependent

**Comment by maciektr** [comment]
*[`crates/cairo-lang-compiler/src/lib.rs` line 113 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3862#-NcSOt3CCUPrbmY44aNt:-NcSOt3CCUPrbmY44aNu:b-5nvap) ([raw file](https://github.com/starkware-libs/cairo/blob/1168b9592e56c5d5cd6e81f5ad227eaa1ce9b5f4/crates/cairo-lang-compiler/src/lib.rs#L113)):*
> ```XML
>     }
> 
>     let versioned_program = Arc::into_inner(sierra_program).unwrap().into();
> ```

This `Arc` may come from the compiler db, so I am not sure if it is safe to drop it here :thinking: 
I believe it is safer to clone instead, e.g.:
```
let versioned_program = VersionedProgram::from((*sierra_program).clone());
```

**Review by maciektr — COMMENTED** [review]
> Reviewed 1 of 13 files at r1, 3 of 22 files at r2, 2 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3862)* status: all files reviewed, 3 unresolved discussions (waiting on @MrDenkoV)

**Review by MrDenkoV — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3862)* status: 7 of 24 files reviewed, 2 unresolved discussions (waiting on @maciektr, @mkaput, and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3862#-Nc2IvJ71L4nM4QClTrw:-NcWeypFCQNRlijtk8lz:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I'm fine with it being in this crate - i just don't want any code to be affected by the added version - as it is for only a single aim - for users who want to save sierra as an artifact. the repo itself isn't one of the users - so i don't want to affect it.
</blockquote></details>

Done.

___
___
*[`crates/cairo-lang-compiler/src/lib.rs` line 113 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3862#-NcSOt3CCUPrbmY44aNt:-NcWf7nYEt1hX_QY6Qp-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1168b9592e56c5d5cd6e81f5ad227eaa1ce9b5f4/crates/cairo-lang-compiler/src/lib.rs#L113)):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

This `Arc` may come from the compiler db, so I am not sure if it is safe to drop it here :thinking: 
I believe it is safer to clone instead, e.g.:
```
let versioned_program = VersionedProgram::from((*sierra_program).clone());
```
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 12 of 17 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3862)* status: 19 of 24 files reviewed, 5 unresolved discussions (waiting on @maciektr, @mkaput, and @MrDenkoV)

___
*[`crates/cairo-lang-compiler/src/lib.rs` line 113 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3862#-NcSOt3CCUPrbmY44aNt:-NcWn7Dw8uejJx2n8Ssi:br7chel) ([raw file](https://github.com/starkware-libs/cairo/blob/1168b9592e56c5d5cd6e81f5ad227eaa1ce9b5f4/crates/cairo-lang-compiler/src/lib.rs#L113)):*
<details><summary><i>Previously, MrDenkoV wrote…</i></summary><blockquote>

Done.
</blockquote></details>

why won't it be safe? - the idea is the reference counter - no unsafe code is involved here.
___
*[`crates/cairo-lang-sierra/src/debug_info_test.rs` line 6 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3862#-NcWnJD1CYu44N0mr5HA:-NcWnJD2BmQiIdIu6U4n:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/0a03637d739b3a706a05182d85a001211f28b3ae/crates/cairo-lang-sierra/src/debug_info_test.rs#L6)):*
> ```XML
> 
> use super::DebugInfo;
> use crate::program::VersionedProgram;
> ```

remove
___
*[`crates/cairo-lang-sierra/src/program.rs` line 18 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3862#-NcWnRsPB5FnJm5qlT4V:-NcWnRsQ0xxQ55Xic0Ib:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0a03637d739b3a706a05182d85a001211f28b3ae/crates/cairo-lang-sierra/src/program.rs#L18)):*
> ```XML
> /// Version-tagged representation of Sierra program.
> ///
> /// Always prefer using this struct in APIs instead of inner ones.
> ```





_Suggestion:_
```XML
/// Always prefer using this struct as saved artifacts instead of inner ones.
```
___
*[`crates/cairo-lang-sierra/src/program.rs` line 21 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3862#-NcWns4I4zbnQ9YdBld4:-NcWns4I4zbnQ9YdBld5:b-jlrz) ([raw file](https://github.com/starkware-libs/cairo/blob/0a03637d739b3a706a05182d85a001211f28b3ae/crates/cairo-lang-sierra/src/program.rs#L21)):*
> ```XML
> #[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
> pub enum VersionedProgram {
>     V1(Program),
> ```

@mkaput - would you prefer to use the external compiler version for this?



_Code quote:_
```XML
V1(Program),
```

**Comment by maciektr** [comment]
*[`crates/cairo-lang-compiler/src/lib.rs` line 113 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3862#-NcSOt3CCUPrbmY44aNt:-NcWqSrNDBZy61vPi1PF:b-7p3bv1) ([raw file](https://github.com/starkware-libs/cairo/blob/1168b9592e56c5d5cd6e81f5ad227eaa1ce9b5f4/crates/cairo-lang-compiler/src/lib.rs#L113)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why won't it be safe? - the idea is the reference counter - no unsafe code is involved here.
</blockquote></details>


I am just not sure if we can safely assume there is no other strong references. Please correct me if we can :)

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3862)* status: 19 of 24 files reviewed, 4 unresolved discussions (waiting on @maciektr and @MrDenkoV)

___
*[`crates/cairo-lang-sierra/src/program.rs` line 21 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3862#-NcWns4I4zbnQ9YdBld4:-NcXYeHKDd-YygAInXxR:bo697yn) ([raw file](https://github.com/starkware-libs/cairo/blob/0a03637d739b3a706a05182d85a001211f28b3ae/crates/cairo-lang-sierra/src/program.rs#L21)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

@mkaput - would you prefer to use the external compiler version for this?
</blockquote></details>

You mean version of `cairo-lang-sierra` package? If we take care of this being really stable, and only change these structs with major version bumps, then it could be OK. Otherwise, I'd rather stick with explicit enum-based versioning here. @MrDenkoV @maciektr opinions?

**Review by MrDenkoV — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3862)* status: 19 of 24 files reviewed, 4 unresolved discussions (waiting on @maciektr, @mkaput, and @orizi)

___
*[`crates/cairo-lang-compiler/src/lib.rs` line 113 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3862#-NcSOt3CCUPrbmY44aNt:-NcXAAMz8Ga-G9OrG4mj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1168b9592e56c5d5cd6e81f5ad227eaa1ce9b5f4/crates/cairo-lang-compiler/src/lib.rs#L113)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

oh - it was instead of the unwrap - got it.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/program.rs` line 18 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3862#-NcWnRsPB5FnJm5qlT4V:-NcWp3bA3HzqRrjJx9aZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0a03637d739b3a706a05182d85a001211f28b3ae/crates/cairo-lang-sierra/src/program.rs#L18)):*
> ```XML
> /// Version-tagged representation of Sierra program.
> ///
> /// Always prefer using this struct in APIs instead of inner ones.
> ```

Done.
___
*[`crates/cairo-lang-sierra/src/program.rs` line 21 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3862#-NcWns4I4zbnQ9YdBld4:-NcaHuHUDzv5hFpzbQUH:bk9tth7) ([raw file](https://github.com/starkware-libs/cairo/blob/0a03637d739b3a706a05182d85a001211f28b3ae/crates/cairo-lang-sierra/src/program.rs#L21)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

You mean version of `cairo-lang-sierra` package? If we take care of this being really stable, and only change these structs with major version bumps, then it could be OK. Otherwise, I'd rather stick with explicit enum-based versioning here. @MrDenkoV @maciektr opinions?
</blockquote></details>

I think using the enum-based versioning and decoupling from the compiler version gives more flexibility.
I'll prepare the other version as well to compare.
___
*[`crates/cairo-lang-sierra/src/debug_info_test.rs` line 6 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3862#-NcWnJD1CYu44N0mr5HA:-NcWotw222-05IEIb_i9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0a03637d739b3a706a05182d85a001211f28b3ae/crates/cairo-lang-sierra/src/debug_info_test.rs#L6)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 17 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3862#-:-NcaVcj89F2kOZ_GNQ7t:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @maciektr)

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 14 of 17 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3862)* status: all files reviewed, 3 unresolved discussions (waiting on @maciektr and @MrDenkoV)

___
*[`crates/cairo-lang-compiler/src/lib.rs` line 115 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3862#-NcacmH14awtr7SSlAkU:-NcacmH14awtr7SSlAkV:b6shf5i) ([raw file](https://github.com/starkware-libs/cairo/blob/d1e24029253d397755d6c27d97c2de360061ef24/crates/cairo-lang-compiler/src/lib.rs#L115)):*
> ```XML
>     let versioned_program = Arc::new((*sierra_program).clone().into());
> 
>     Ok(versioned_program)
> ```

You know, we've done the whole circle here... :wink: 



_Suggestion:_
```XML
    Ok(sierra_program)
```
___
*[`crates/cairo-lang-sierra/src/program.rs` line 43 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3862#-NcagUuQ9xrH8bd6NT5x:-NcagUuQ9xrH8bd6NT5y:b-k4dq93) ([raw file](https://github.com/starkware-libs/cairo/blob/d1e24029253d397755d6c27d97c2de360061ef24/crates/cairo-lang-sierra/src/program.rs#L43)):*
> ```XML
>             VersionedProgram::V1(program) => write!(f, "{program}")?,
>         }
>         Ok(())
> ```

micro-optimization, but let's stick with commonly advised pattern nonetheless



_Suggestion:_
```XML
        match self {
            VersionedProgram::V1(program) => fmt::Display::fmt(program, f),
        }
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3862)* status: all files reviewed, 3 unresolved discussions (waiting on @maciektr, @mkaput, and @MrDenkoV)

___
*[`crates/cairo-lang-compiler/src/lib.rs` line 115 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3862#-NcacmH14awtr7SSlAkU:-NcakTBl0Jn5B3seKjnr:b-s7wn35) ([raw file](https://github.com/starkware-libs/cairo/blob/d1e24029253d397755d6c27d97c2de360061ef24/crates/cairo-lang-compiler/src/lib.rs#L115)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

You know, we've done the whole circle here... :wink:
</blockquote></details>

indeed - revert file.

**Review by MrDenkoV — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3862)* status: 19 of 24 files reviewed, 3 unresolved discussions (waiting on @maciektr, @mkaput, and @orizi)

___
*[`crates/cairo-lang-sierra/src/program.rs` line 43 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3862#-NcagUuQ9xrH8bd6NT5x:-NcawqohC8znSGES2cp1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d1e24029253d397755d6c27d97c2de360061ef24/crates/cairo-lang-sierra/src/program.rs#L43)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

micro-optimization, but let's stick with commonly advised pattern nonetheless
</blockquote></details>

Done.
___
*[`crates/cairo-lang-compiler/src/lib.rs` line 115 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3862#-NcacmH14awtr7SSlAkU:-Ncawva91WjI9gmF_SZm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d1e24029253d397755d6c27d97c2de360061ef24/crates/cairo-lang-compiler/src/lib.rs#L115)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

indeed - revert file.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3862)* status: all files reviewed, 3 unresolved discussions (waiting on @maciektr and @mkaput)

**Review by mkaput — APPROVED** [review]
:lgtm_strong:

> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3862#-:-NcbMB6I3fHbqVSE826x:b-jbsf8z)* status: all files reviewed, 1 unresolved discussion (waiting on @maciektr)

**Review by maciektr — COMMENTED** [review]
> Reviewed 4 of 22 files at r2, 1 of 6 files at r4, 10 of 17 files at r5, 2 of 3 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3862)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MrDenkoV)

**Pull request merged**
