### PR TITLE
Cost computation: Set no_eq_solver=true starting sierra version 1.4.0.

### PR DESCRIPTION
**Pull request by liorgold2**
**Stack**:
- #4228
- #4227
- #4226
- #4225 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4225)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4225)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-starknet/src/casm_contract_class.rs` line 290 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4225#-NgEOISk17QDdgpPkU9r:-NgEOISk17QDdgpPkU9s:b-unpzk0) ([raw file](https://github.com/starkware-libs/cairo/blob/df721080b2fa5c8c2fb11300a5ccad4b48b163a7/crates/cairo-lang-starknet/src/casm_contract_class.rs#L290)):*
> ```XML
>         // TODO(lior): Remove this assert and condition once the equation solver is removed in major
>         //   version 2.
>         assert!(sierra_version.major == 1);
> ```

Assert_eq

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4225)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/casm_contract_class.rs` line 290 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4225#-NgEOISk17QDdgpPkU9r:-NgFmmE68nLr9DWEpLBw:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8877ad037de128ffc170ef078f362c856e885e01/crates/cairo-lang-starknet/src/casm_contract_class.rs#L290)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Assert_eq
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4225#-:-NgIFYF5DXQMvC4Jh53g:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4225)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
