### PR TITLE
Fix dict squash cost.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2857)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2857#-:-NTEQSN7CXrCzCHHitwP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2857)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2857)* status: all files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2857#-NTET7YF4iLgAMcGxfi4:-NTET7YF4iLgAMcGxfi5:b1ajkcn) ([raw file](https://github.com/starkware-libs/cairo/blob/b25d1e82a453aae8342e9585f68cc99be08f9b88/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L40)):*
> ```XML
> // The costs of the dict_squash libfunc, divided into different parts.
> /// The cost per each unique key in the dictionary. This cost is pre charged for each access
> /// (read/write/entry), and the overhead cost is refunded for each subsequent access.
> ```

Since you use "repeated" in the const name below. You can change to a better word if you find, but please update below as well.



_Suggestion:_
```XML
/// The cost per each unique key in the dictionary. This cost is pre-charged for each access
/// (read/write/entry), and the overhead cost is refunded for each repeated access.
/// Repeated access is access to a key that has already been accessed before.
```
___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 289 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2857#-NTETYofDr4q4P6kcXKw:-NTETYog3HrNx7zcw1Gb:bqcx1v9) ([raw file](https://github.com/starkware-libs/cairo/blob/b25d1e82a453aae8342e9585f68cc99be08f9b88/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L289)):*
> ```XML
>             Felt252DictConcreteLibfunc::Squash(_) => {
>                 // Dict squash have a fixed cost of 'DICT_SQUASH_CONST_COST' +
>                 // `DICT_SQUASH_UNIQUE_KEY_COST` for each dict access. Only the fixed
> ```

Is this part true?



_Code quote:_
```XML
`DICT_SQUASH_UNIQUE_KEY_COST` for each dict access
```
___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 291 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2857#-NTETjwaDGU3Jy8ygSZh:-NTETjwaDGU3Jy8ygSZi:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b25d1e82a453aae8342e9585f68cc99be08f9b88/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L291)):*
> ```XML
>                 // `DICT_SQUASH_UNIQUE_KEY_COST` for each dict access. Only the fixed
>                 // cost is charged here, so that we would always be able to call
>                 // squash even if running out of gas. The cost of the processing of
> ```





_Suggestion:_
```XML
                // squash even if running out of gas. The cost of the processing an entry for the first time the key appears
                // is `DICT_SQUASH_UNIQUE_KEY_COST`. Each additional access to
                // an existing key costs only 'DICT_SQUASH_REPEATED_ACCESS_COST'. In
```
___
*[`tests/e2e_test_data/libfuncs/felt252_dict` line 298 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2857#-NTEUJcSEQTgV--U3Id5:-NTEUJcSEQTgV--U3Id6:bk2mbzs) ([raw file](https://github.com/starkware-libs/cairo/blob/b25d1e82a453aae8342e9585f68cc99be08f9b88/tests/e2e_test_data/libfuncs/felt252_dict#L298)):*
> ```
> [fp + 1] = [ap + 0] + [ap + -1], ap++;
> [ap + -1] = [ap + 0] * 3, ap++;
> [ap + -1] = [ap + 0] + 1, ap++;
> ```

Why `+ 1`?

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2857)* status: all files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs` line 214 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2857#-NTEV1GD3S15Wk7-UAMu:-NTEV1GE0y6U5hwkayNG:b-14q0wh) ([raw file](https://github.com/starkware-libs/cairo/blob/b25d1e82a453aae8342e9585f68cc99be08f9b88/crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs#L214)):*
> ```XML
>             // Find the number of keys.
>             tempvar squashed_dict_len = squashed_dict_end - squashed_dict_start;
>             // The number of refunded accesses is number_of_accesses - number_of_keys - 1, which equals
> ```

Why the `- 1`? If I have 7 accesses before the squash and 3 after, it means 3 keys, so 3 of the accesses are first-access and were charged correctly. All the rest (7-3) should be refunded.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2857)* status: all files reviewed, 5 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2857#-NTET7YF4iLgAMcGxfi4:-NTEnFXR2WUvtv5KwW9s:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b25d1e82a453aae8342e9585f68cc99be08f9b88/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L40)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Since you use "repeated" in the const name below. You can change to a better word if you find, but please update below as well.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 289 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2857#-NTETYofDr4q4P6kcXKw:-NTEmo_W2UcJv4wVewXq:b7tl9zt) ([raw file](https://github.com/starkware-libs/cairo/blob/b25d1e82a453aae8342e9585f68cc99be08f9b88/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L289)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Is this part true?
</blockquote></details>

Yes, but I reworded it to avoid misunderstanding (the operator precedence wasn't well defined).
___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 291 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2857#-NTETjwaDGU3Jy8ygSZh:-NTEnEjk2f0SPDinqqVt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b25d1e82a453aae8342e9585f68cc99be08f9b88/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L291)):*
> ```XML
>                 // `DICT_SQUASH_UNIQUE_KEY_COST` for each dict access. Only the fixed
>                 // cost is charged here, so that we would always be able to call
>                 // squash even if running out of gas. The cost of the processing of
> ```

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs` line 214 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2857#-NTEV1GD3S15Wk7-UAMu:-NTEnJRa-ARweOLRYNN_:b-2nibcu) ([raw file](https://github.com/starkware-libs/cairo/blob/b25d1e82a453aae8342e9585f68cc99be08f9b88/crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs#L214)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Why the `- 1`? If I have 7 accesses before the squash and 3 after, it means 3 keys, so 3 of the accesses are first-access and were charged correctly. All the rest (7-3) should be refunded.
</blockquote></details>

You are correct. Done.
___
*[`tests/e2e_test_data/libfuncs/felt252_dict` line 298 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2857#-NTEUJcSEQTgV--U3Id5:-NTEV2CO0GZAieIhWoLA:b40o3cn) ([raw file](https://github.com/starkware-libs/cairo/blob/b25d1e82a453aae8342e9585f68cc99be08f9b88/tests/e2e_test_data/libfuncs/felt252_dict#L298)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Why `+ 1`?
</blockquote></details>

It's `-1` from the comment above.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2857)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 288 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2857#-NTF6BMu4WWMEqxBNaYB:-NTF6BMu4WWMEqxBNaYC:bfqtvaf) ([raw file](https://github.com/starkware-libs/cairo/blob/904903e73bfcfc354b87e80a464cde99bb4f0bcb/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L288)):*
> ```XML
>             }
>             Felt252DictConcreteLibfunc::Squash(_) => {
>                 // Dict squash have a fixed cost of 'DICT_SQUASH_CONST_COST' an additional cost of
> ```

Can you rewrite it in a more organized way?
The current paragraph is very confusing.
Use empty `//` lines to create paragraphs that the auto-formatter will not mess with.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs` line 214 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2857#-NTEV1GD3S15Wk7-UAMu:-NTF6Vv71WQfLHaV1VqC:b-roottj) ([raw file](https://github.com/starkware-libs/cairo/blob/b25d1e82a453aae8342e9585f68cc99be08f9b88/crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs#L214)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

You are correct. Done.
</blockquote></details>

Fix the comment as well (two places).
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs` line 154 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2857#-NTF6SvS3SJoIxqIexCb:-NTF6SvS3SJoIxqIexCc:b-r1dun5) ([raw file](https://github.com/starkware-libs/cairo/blob/904903e73bfcfc354b87e80a464cde99bb4f0bcb/crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs#L154)):*
> ```XML
>             const dict_info_size = 3;
>             const one = 1;
>             const gas_refund_per_access = DICT_SQUASH_UNIQUE_KEY_COST.cost() - DICT_SQUASH_REPEATED_ACCESS_COST.cost();
> ```

Line too long.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2857)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 288 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2857#-NTF6BMu4WWMEqxBNaYB:-NTFY7PH69duKcPmveee:b-f2ht0n) ([raw file](https://github.com/starkware-libs/cairo/blob/904903e73bfcfc354b87e80a464cde99bb4f0bcb/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L288)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Can you rewrite it in a more organized way?
The current paragraph is very confusing.
Use empty `//` lines to create paragraphs that the auto-formatter will not mess with.
</blockquote></details>

I've rewritten it.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs` line 154 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2857#-NTF6SvS3SJoIxqIexCb:-NTFYc0p0DqTNGKovq-C:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/904903e73bfcfc354b87e80a464cde99bb4f0bcb/crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs#L154)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Line too long.
</blockquote></details>

Done.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2857)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 290 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2857#-NTFkEYACjc14tViRUq8:-NTGHIhQAEdrrn1TrrDp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4e6ffc87a3dc682e44a5afd0278e90b7539a4b3f/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L290)):*
> ```XML
>                 // The `dict_squash` operation incurs a fixed cost of `DICT_SQUASH_CONST_COST`,
>                 // plus an additional cost of `DICT_SQUASH_UNIQUE_KEY_COST` for each read or write
>                 // access to a dictionary. However, the true cost of processing each unique key is
> ```

Done.

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2857#-:-NTI5mra0Iazrk6Jrdsf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
