### PR TITLE
Removing ap-calc direct depenency from gas-calc.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:c781a7a3

---

**Stack**:
- #1951
- #1957
- #1943
- #1942
- #1941 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 6 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1941)* status: 6 of 15 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1941#-NMwkAEp58hFoU9Oqrt-:-NMwkAEq3mP2sJxV9VWV:beoege) ([raw file](https://github.com/starkware-libs/cairo/blob/123f99aad67fb14b3e262eb1e5315aaf82320247/crates/cairo-lang-sierra-gas/src/lib.rs#L80)):*
> ```XML
>                 &InvocationCostInfoProviderForEqGen {
>                     registry: &registry,
>                     token_usages: |_| panic!("Token costs not available at precost calculation."),
> ```

It's a bit weird like this: readers of the usage of this interface might think it is available (for example, in precost computation).
Consider returning Option instead, and unwraping in post, to shift the responsilibity to the usage and not the provider (that otherwirse will have to assume things about its usage)



_Code quote:_
```XML
panic!
```

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 9 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1941#-:-NMwkhxaC6ttQzmHllRx:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1941)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1941#-NMwkAEp58hFoU9Oqrt-:-NMxSt3r881LOZOb87SZ:b-2uf020) ([raw file](https://github.com/starkware-libs/cairo/blob/b47e52cf2d59baeac8e845b6ec9b206a122c6004/crates/cairo-lang-sierra-gas/src/lib.rs#L80)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

It's a bit weird like this: readers of the usage of this interface might think it is available (for example, in precost computation).
Consider returning Option instead, and unwraping in post, to shift the responsilibity to the usage and not the provider (that otherwirse will have to assume things about its usage)

</blockquote></details>

removed in the following pr.

**Review by spapinistarkware — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1941)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by spapinistarkware — APPROVED** [review]

**Pull request merged**
