### PR TITLE
feat(formatter): accept input from stdin

### LINKED ISSUE #1086: feat: allow formatter to format stdin
# Feature Request

**Describe the Feature Request**

Currently the formatter only takes file paths as input. Would be nice if it can take stdin as input when the argument is `-`. This is useful in editors, which usually interface with formatters via stdin/stdout.

**Describe Preferred Solution**

Read from stdin when the supplied argument is `-`.

**Describe Alternatives**

N/A

**Related Code**

N/A

**Additional Context**

N/A

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by xJonathanLEI**
Resolves #1086. This PR makes it possible for the formatter to take input from stdin and emit formatted text into stdout (unless `--check` is specified, of course).

However, to make this work, I had to make some additional changes:

- The original code prints to stdout for progress when verbosity is set, but this can interfere with the formatted code output. I changed them to all use stderr. The official man page states that stderr can be used for diagnostics not just errors:

  ```console
  $ man stderr
  ---- SNIP ----
  Under  normal  circumstances  every  UNIX  program has three streams opened for it when it starts up, one for input, one for output, and one for printing diagnostic or error messages.
  ---- SNIP ----
  ```

  In fact, `curl` always sends the progress to stderr since it needs to output to stdout. We have the exact same issue here. So I changed it. Only the diff (when `--check` is used) and the formatted text can get on stdout now.

- I couldn't reuse the `format_file` code since it calls a function `get_syntax_root_and_diagnostics_from_file()` that's exclusive for reading from files. I had to make another almost-identical function for formatting `&str`, causing code duplication.

At this point I figured I might just do a bit more refactoring to clean it up. So I did these too:

- I abstracted away the input source (and thus output target) with an `Input` type, and refactored the `format_file()` code to use it;

- I created more readable/maintainable return types `FormatResult` and `FormatError` instead of just returning `bool`.

It looks like I made more changes than strictly necessary. So that's a brief explaination for that. I hope you forgive me for rewriting almost the whole file.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1139)

### CODE REVIEW

**Comment by xJonathanLEI** [comment]
OK it looks like you guys have additional clippy lints enabled. Lemme fix that up real quick.

**Comment by xJonathanLEI** [comment]
OK CI happy now :)

**Review by mkaput — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1139)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @xJonathanLEI)

___
*[`crates/formatter/src/bin/cli.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1139#-NI1o97l5znn5MzlNnpf:-NI1o97l5znn5MzlNnpg:bty4e7q) ([raw file](https://github.com/starkware-libs/cairo/blob/5e63c67f83a364e45982c6250533f7b95a011887/crates/formatter/src/bin/cli.rs#L27)):*
> ```XML
> 
> #[derive(Debug)]
> enum FormatError {
> ```

In CLI app I think you can easily skip writing error types and use `anyhow::bail!` all over the place

**Review by xJonathanLEI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1139)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @mkaput)

___
*[`crates/formatter/src/bin/cli.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1139#-NI1o97l5znn5MzlNnpf:-NI1p7BcEtgeWj7tRWHw:b47w4jm) ([raw file](https://github.com/starkware-libs/cairo/blob/5e63c67f83a364e45982c6250533f7b95a011887/crates/formatter/src/bin/cli.rs#L27)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

In CLI app I think you can easily skip writing error types and use `anyhow::bail!` all over the place
</blockquote></details>

Got it. Wasn't sure what is the preferred handling here. Will change to use `anyhow` now.

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1139)* status: all files reviewed, 1 unresolved discussion (waiting on @xJonathanLEI)

___
*[`crates/formatter/src/bin/cli.rs` line 28 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1139#-NI1ufvY2d017FFzBHpJ:-NI1ufvY2d017FFzBHpK:b-aq9c79) ([raw file](https://github.com/starkware-libs/cairo/blob/84d616fa67b70241caa71903d88f9d4d378a7956/crates/formatter/src/bin/cli.rs#L28)):*
> ```XML
> 
> #[derive(Debug)]
> struct UnparsableError;
> ```

dead code?

**Review by xJonathanLEI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1139)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)

___
*[`crates/formatter/src/bin/cli.rs` line 28 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1139#-NI1ufvY2d017FFzBHpJ:-NI1vysd4JXthzQPLN9m:b-kkker8) ([raw file](https://github.com/starkware-libs/cairo/blob/84d616fa67b70241caa71903d88f9d4d378a7956/crates/formatter/src/bin/cli.rs#L28)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

dead code?
</blockquote></details>

Wait.. I thought I deleted it, and not sure why Clippy isn't picking this up. That's weird. Sorry for that. Removing now.

**Review by xJonathanLEI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1139)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @mkaput)

___
*[`crates/formatter/src/bin/cli.rs` line 28 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1139#-NI1ufvY2d017FFzBHpJ:-NI1xGqB9YI1mwWga1ya:bc88g2p) ([raw file](https://github.com/starkware-libs/cairo/blob/84d616fa67b70241caa71903d88f9d4d378a7956/crates/formatter/src/bin/cli.rs#L28)):*
<details><summary><i>Previously, xJonathanLEI (Jonathan LEI) wrote…</i></summary><blockquote>

Wait.. I thought I deleted it, and not sure why Clippy isn't picking this up. That's weird. Sorry for that. Removing now.
</blockquote></details>

This time actually properly removed all error types :)

**Review by mkaput — APPROVED** [review]
Thanks for contribution ❤️❤️❤️

:lgtm:

I'm leaving clicking merge to @orizi or @spapinistarkware 

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1139#-:-NI1y1qOAG50otV5zyMT:bdqtp24)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @xJonathanLEI)

**Review by spapinistarkware — COMMENTED** [review]
I would rather we use the filesystem framework instead.
I suggest adding a VirtualFile for the stdin:
```
let new_file = db.intern_file(FileLongId::Virtual(VirtualFile {
                    parent: None,
                    name: "<stdin>,
                    content: Arc::new(content),
                }));
```
WDYT?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1139#-:-NI25Zi5DKCwwpJ8VwBF:b52rueb)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @xJonathanLEI)

**Review by xJonathanLEI — COMMENTED** [review]
PR updated. Using virtual file now.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1139#-:-NI2K46oDP3bDl16Ga3k:b10pdp3)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @mkaput)

**Review by xJonathanLEI — COMMENTED** [review]
Latest attempt :)

Using the file system properly now, basically option `2`.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1139#-:-NI2WVdUDscur8Xo50Xx:bv5eda4)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @mkaput)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:
Please squash before merging

> Reviewed 1 of 2 files at r1, 2 of 3 files at r3, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1139#-:-NI2aJS7DGkOq7-OzF9J:bipro9k)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @xJonathanLEI)

**Comment by xJonathanLEI** [comment]
I'm pretty sure you meant the "squash and merge" option on GitHub. But just in case, there's no action needed from my side right?

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1139)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @xJonathanLEI)

**Pull request merged**
