### PR TITLE
Enable split_structs optimization.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5039)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5039)* status: 0 of 32 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 404 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5039#-Nq819sYEcR2tvRDUO5m:-Nq819sZBGFLTDSQ_xe0:bsrb2cs) ([raw file](https://github.com/starkware-libs/cairo/blob/d958589fcb4d9cb86635197083103ddb6a395a52/crates/cairo-lang-lowering/src/db.rs#L404)):*
> ```XML
>     optimize_remappings(&mut lowered);
>     cancel_ops(&mut lowered);
>     split_structs(&mut lowered);
> ```

not sure where to put this.



_Code quote:_
```XML
split_structs(&mut lowered);
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 17 of 32 files at r1, 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5039#-:-Nq8CQYq7-amvnGmmeJb:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 404 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5039#-Nq819sYEcR2tvRDUO5m:-Nq87V0B1bGvQAh8m684:bvv4fe4) ([raw file](https://github.com/starkware-libs/cairo/blob/d958589fcb4d9cb86635197083103ddb6a395a52/crates/cairo-lang-lowering/src/db.rs#L404)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

not sure where to put this.
</blockquote></details>

Looks like a valid place

**Review by orizi — COMMENTED** [review]
> Reviewed 12 of 28 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5039)* status: 16 of 32 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 16 of 28 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5039)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 3 of 32 files at r1, 1 of 15 files at r2, 25 of 28 files at r3, 8 of 10 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5039)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
