### PR TITLE
Made macros arguments - arguments instead of expressions.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3951)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3951)* status: all files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1003 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3951#-NcSskOI2ey6R0hoWTyw:-NcSskOI2ey6R0hoWTyx:b-wckbog) ([raw file](https://github.com/starkware-libs/cairo/blob/df73812b717ece7aa32de458aee19ac09a3fd4fd/crates/cairo-lang-parser/src/parser.rs#L1003)):*
> ```XML
>     /// Gets `new_green` a green id node builder for the list of the requested type, applies it to
>     /// the parsed list and returns the result.
>     fn expect_wrapped_arg_list<
> ```

to be consistent with expect_parenthesized_argument_list



_Suggestion:_
```XML
expect_wrapped_argument_list
```
___
*[`crates/cairo-lang-parser/src/parser.rs` line 1031 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3951#-NcSsUpz3dxX-maWchvA:-NcSsUq-BYYzdxrGxmCq:b2ni2nk) ([raw file](https://github.com/starkware-libs/cairo/blob/df73812b717ece7aa32de458aee19ac09a3fd4fd/crates/cairo-lang-parser/src/parser.rs#L1031)):*
> ```XML
>     }
> 
>     /// Tries to parse parenthesized function call arguments.
> ```

fix



_Code quote:_
```XML
 function call arguments.
```
___
*[`crates/cairo-lang-semantic/src/inline_macros/consteval_int.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3951#-NcSuNVQB4RaMdTUFzuh:-NcSuNVQB4RaMdTUFzui:b-fcbnnr) ([raw file](https://github.com/starkware-libs/cairo/blob/df73812b717ece7aa32de458aee19ac09a3fd4fd/crates/cairo-lang-semantic/src/inline_macros/consteval_int.rs#L63)):*
> ```XML
>             return Some(arg_clause.value(db));
>         }
>     }
> ```

move extract_single_unnamed_arg to some utils and use it here.



_Code quote:_
```XML
    if let Ok([arg]) = <[_; 1]>::try_from(macro_arguments.elements(db)) {
        if let ast::ArgClause::Unnamed(arg_clause) = arg.arg_clause(db) {
            return Some(arg_clause.value(db));
        }
    }
```
___
*[`crates/cairo-lang-semantic/src/inline_macros/consteval_int.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3951#-NcSuZ6w7_zdBfM6NP9F:-NcSuZ6w7_zdBfM6NP9G:b-5rowv3) ([raw file](https://github.com/starkware-libs/cairo/blob/df73812b717ece7aa32de458aee19ac09a3fd4fd/crates/cairo-lang-semantic/src/inline_macros/consteval_int.rs#L66)):*
> ```XML
>     diagnostics.push(PluginDiagnostic {
>         stable_ptr: macro_arguments.stable_ptr().untyped(),
>         message: "consteval_int macro must have a single unnamed argument.".to_string(),
> ```

also change here to "exactly one"



_Code quote:_
```XML
 have a single unnamed arg
```
___
*[`crates/cairo-lang-starknet/src/inline_macros/selector.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3951#-NcSudoE-3zbJanWW5vH:-NcSudoE-3zbJanWW5vI:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/df73812b717ece7aa32de458aee19ac09a3fd4fd/crates/cairo-lang-starknet/src/inline_macros/selector.rs#L59)):*
> ```XML
> }
> 
> /// Extract single unnamed argument.
> ```





_Suggestion:_
```XML
 Extracts a single unnamed argum
```
___
*[`crates/cairo-lang-syntax-codegen/src/cairo_spec.rs` line 218 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3951#-NcSpQTcCjgjHMS__or-:-NcSpQTcCjgjHMS__or0:b2tpbgx) ([raw file](https://github.com/starkware-libs/cairo/blob/df73812b717ece7aa32de458aee19ac09a3fd4fd/crates/cairo-lang-syntax-codegen/src/cairo_spec.rs#L218)):*
> ```XML
>     .add_struct(StructBuilder::new("ArgListBracketed")
>         .node("lbrack", "TerminalLBrack")
>         .node("arguments", "ArgList")
> ```

arg allows for modifiers. I think we should have ArgClause here.
But we use it wrong in other places too (like generic args and attributes), so we can also change it in a separate PR. But probably better do it in the first place.
(we can rename, in a separate pr: Arg -> ArgWithModifiers, ArgClause -> Arg, or similar)



_Code quote:_
```XML
ArgList
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3951)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/cairo-lang-syntax-codegen/src/cairo_spec.rs` line 218 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3951#-NcSpQTcCjgjHMS__or-:-NcT5drR2z3t2Pfa1b-S:bi6n0b5) ([raw file](https://github.com/starkware-libs/cairo/blob/df73812b717ece7aa32de458aee19ac09a3fd4fd/crates/cairo-lang-syntax-codegen/src/cairo_spec.rs#L218)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

arg allows for modifiers. I think we should have ArgClause here.
But we use it wrong in other places too (like generic args and attributes), so we can also change it in a separate PR. But probably better do it in the first place.
(we can rename, in a separate pr: Arg -> ArgWithModifiers, ArgClause -> Arg, or similar)
</blockquote></details>

agreed.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3951#-:-NcU8ANw2YwEfsASmgZY:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/inline_macros/consteval_int.rs` line 30 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3951#-NcU7nTRBWIxlZImKsPs:-NcU7nTRBWIxlZImKsPt:bnxt8t6) ([raw file](https://github.com/starkware-libs/cairo/blob/193ef9cebc9beb52255825c629af98288d530dfc/crates/cairo-lang-semantic/src/inline_macros/consteval_int.rs#L30)):*
> ```XML
>                 diagnostics: vec![PluginDiagnostic {
>                     stable_ptr: args.stable_ptr().untyped(),
>                     message: "consteval_int macro must have a single unnamed argument.".to_string(),
> ```

exactly once



_Code quote:_
```XML
ave a single unname
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3951)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
