### PR TITLE
Add doc of the testing framework.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5304)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5304)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @yuvalsw)

___
*[`docs/CONTRIBUTING.md` line 31 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5304#-NtWgOmR9DnBh9u6gapr:-NtWgOmR9DnBh9u6gaps:b-jczwmd) ([raw file](https://github.com/starkware-libs/cairo/blob/388709803f4342eccdfa143f694b907bd9b35fae/docs/CONTRIBUTING.md#L31)):*
> ```Markdown
> 
> ## Running Tests
> There are various types of tests within the repository, including both Cairo-based and Rust-based tests.
> ```

make all lines shorter than 100 chars.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5304)* status: 0 of 19 files reviewed, 1 unresolved discussion (waiting on @orizi and @yuvalsw)

___
*[`docs/CONTRIBUTING.md` line 31 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5304#-NtWgOmR9DnBh9u6gapr:-NtWomP506X8Q5RNWTjU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/388709803f4342eccdfa143f694b907bd9b35fae/docs/CONTRIBUTING.md#L31)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

make all lines shorter than 100 chars.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5304)* status: 0 of 19 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5304#-NtWp2Fm1LbL7nUEyn8C:-NtWp2Fm1LbL7nUEyn8D:bv28028) (no related file):*
revert many relevant files.

___

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5304)* status: 0 of 19 files reviewed, 2 unresolved discussions (waiting on @orizi and @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5304#-NtWp2Fm1LbL7nUEyn8C:-NtWpFqZB6y72TAvA-IA:bb6un1j) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

revert many relevant files.
</blockquote></details>

Done

___

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 19 files at r2, 18 of 18 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5304#-:-NtWpiyv5g-WUbthpItK:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5304)* status: all files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`docs/CONTRIBUTING.md` line 48 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5304#-NtXLTnQ8KQuO4JEp0IB:-Ntoh56x6iYKgr5jOsQZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2f5e6142cdbf2fad689c5bcd7edec7d97b313abc/docs/CONTRIBUTING.md#L48)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Add about --single-file.
Add a blank line
</blockquote></details>

Done.
___
*[`docs/CONTRIBUTING.md` line 58 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5304#-NtXLkD7A7lvbLeNvAyY:-Ntoh43R6eWM9wps8ZsA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2f5e6142cdbf2fad689c5bcd7edec7d97b313abc/docs/CONTRIBUTING.md#L58)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

And it formats the code section, right?
</blockquote></details>

Done.
___
*[`docs/CONTRIBUTING.md` line 61 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5304#-NtXLzrM3wf55OGvDDss:-NtohnQrC7gl9MH6Usgi:b81kas7) ([raw file](https://github.com/starkware-libs/cairo/blob/2f5e6142cdbf2fad689c5bcd7edec7d97b313abc/docs/CONTRIBUTING.md#L61)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

only with CAIRO_FIX_TESTS, no?
</blockquote></details>

Without it will fail, added/

**Pull request merged**
