### PR TITLE
Add *_get_gas() libfuncs for builtins.

### PR DESCRIPTION
**Pull request by liorgold2**
commit-id:c00ea6d5

---

**Stack**:
- #1212
- #1211
- #1216
- #1210 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1210)* status: 1 of 8 files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1210)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/sierra/src/extensions/modules/builtin_cost.rs` line 30 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1210#-NISJWMd-zaGHSV5QYia:-NISJWMd-zaGHSV5QYib:b9lwjz6) ([raw file](https://github.com/starkware-libs/cairo/blob/db44deea6799016f8c707926b87c35752546f720/crates/sierra/src/extensions/modules/builtin_cost.rs#L30)):*
> ```XML
>     /// Returns the name of the token type, in snake_case.
>     pub fn name(&self) -> String {
>         match self {
> ```

maybe make this return a generic libfuc id itself?
this way you can remove the string creatin on runtime and use consts



_Code quote:_
```XML
    /// Returns the name of the token type, in snake_case.
    pub fn name(&self) -> String {
        match self {
            CostTokenType::Step => "step",
            CostTokenType::Pedersen => "pedersen",
        }
        .into()
    }
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1210)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/sierra/src/extensions/modules/builtin_cost.rs` line 30 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1210#-NISJWMd-zaGHSV5QYia:-NISNPyM5ymEcowVLnPZ:bt0uhwa) ([raw file](https://github.com/starkware-libs/cairo/blob/db44deea6799016f8c707926b87c35752546f720/crates/sierra/src/extensions/modules/builtin_cost.rs#L30)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe make this return a generic libfuc id itself?
this way you can remove the string creatin on runtime and use consts
</blockquote></details>

I may want to use the name for other things (types/other libfuncs). I don't think the enum should give you the *_get_gas libfunc id - the enum is more generic than this.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 7 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1210)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1210#-:-NISO33eBolDrHNQGflU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1210)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
