### PR TITLE
Remove get_statements_functions_map_for_tests.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6154)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6154)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @piotmag769)

___
*[`crates/cairo-lang-sierra-generator/src/statements_functions.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6154#-O3cH_yW9SviJll9Cc3y:-O3cH_yW9SviJll9Cc3z:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/c4621d7ad834374221c5ead615b4b7081d52bde1/crates/cairo-lang-sierra-generator/src/statements_functions.rs#L19)):*
> ```XML
> 
> impl StatementsFunctions {
>     pub fn from_annotations(annotations: &Annotations) -> Option<Self> {
> ```

doc

**Review by piotmag769 — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6154)* status: all files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-runner/src/profiling.rs` line 233 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6154#-O3cK7MJACiW3qunkGKQ:-O3cK7MJACiW3qunkGKR:b21bvik) ([raw file](https://github.com/starkware-libs/cairo/blob/c4621d7ad834374221c5ead615b4b7081d52bde1/crates/cairo-lang-runner/src/profiling.rs#L233)):*
> ```XML
>     /// that generated it. The function representation is composed of the function name and the
>     /// path (modules and impls) to the function in the file.
>     statements_functions: StatementsFunctions,
> ```

The doc is now outdated
___
*[`crates/cairo-lang-runner/src/profiling_test.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6154#-O3cLBmD8qL02swdjq_2:-O3cLBmD8qL02swdjq_3:b-t7r62i) ([raw file](https://github.com/starkware-libs/cairo/blob/c4621d7ad834374221c5ead615b4b7081d52bde1/crates/cairo-lang-runner/src/profiling_test.rs#L58)):*
> ```XML
>         ));
>     let sierra_program = replace_sierra_ids_in_program(&db, &sierra_program);
>     let statements_functions = debug_info.statements_locations.extract_statements_functions(&db);
> ```

Will it work? I made `maybe_containing_function_identifier_for_tests` just for this case actually. The logic wast that if it cannot find an absolute path to the module the `StableLocation` is in it falls back to filename. The fallback shouldn't happen in real projects, only in tests since it is the only place where `VirtualFile` can correspond to root of a crate

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-runner/src/profiling_test.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6154#-O3cLBmD8qL02swdjq_2:-O3fhArQ0K_94RQyRT58:b-yv5k4y) ([raw file](https://github.com/starkware-libs/cairo/blob/c4621d7ad834374221c5ead615b4b7081d52bde1/crates/cairo-lang-runner/src/profiling_test.rs#L58)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Will it work? I made `maybe_containing_function_identifier_for_tests` just for this case actually. The logic wast that if it cannot find an absolute path to the module the `StableLocation` is in it falls back to filename. The fallback shouldn't happen in real projects, only in tests since it is the only place where `VirtualFile` can correspond to root of a crate
</blockquote></details>

I guess not

**Comment by ilyalesokhin-starkware** [comment]
Removing `[statements_functions_map_for_tests` turned up to be more complicated than expected, so I did #6161 instead.

**Pull request closed without merging**
