### PR TITLE
Added test cases to bool_eq.

### PR DESCRIPTION
**Pull request by amosStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2153)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2153)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @amosStarkware)

___
*[`tests/e2e_test_data/libfuncs/bool` line 213 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2153#-NOKnfpZ480w7liIiSqG:-NOKnfpZ480w7liIiSqH:b-d5b4p1) ([raw file](https://github.com/starkware-libs/cairo/blob/5f41a57d00c3d78ac9616c83fe9dfdba9efb90dd/tests/e2e_test_data/libfuncs/bool#L213)):*
> ```
> //! > casm
> [ap + 0] = 1, ap++;
> [ap + 0] = 1, ap++;
> ```

since both are immediates, I would expect to simply see `[ap + 0] = 0, ap++` (where `0` is `1-1`).
Looks like both immediate values are pushed onto the AP stack.
Why?



_Code quote:_
```
[ap + 0] = 1, ap++;
[ap + 0] = 1, ap++;
[ap + -2] = [ap + 0] + [ap + -1], ap++;
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2153)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware)

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2153)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`tests/e2e_test_data/libfuncs/bool` line 213 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2153#-NOKnfpZ480w7liIiSqG:-NOKoO7Y2JLevLOLzn-O:biwxcxn) ([raw file](https://github.com/starkware-libs/cairo/blob/5f41a57d00c3d78ac9616c83fe9dfdba9efb90dd/tests/e2e_test_data/libfuncs/bool#L213)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

since both are immediates, I would expect to simply see `[ap + 0] = 0, ap++` (where `0` is `1-1`).
Looks like both immediate values are pushed onto the AP stack.
Why?
</blockquote></details>

good question, I don't know. since it uses the same function as `u128_eq` I would think it'd behave the same

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2153#-:-NOKpU5N90SYTicnKBh2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

___
*[`tests/e2e_test_data/libfuncs/bool` line 213 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2153#-NOKnfpZ480w7liIiSqG:-NOKpM334Hj9-VovpvyD:br0dhm5) ([raw file](https://github.com/starkware-libs/cairo/blob/5f41a57d00c3d78ac9616c83fe9dfdba9efb90dd/tests/e2e_test_data/libfuncs/bool#L213)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

good question, I don't know. since it uses the same function as `u128_eq` I would think it'd behave the same
</blockquote></details>

maybe the conversion of bool to u128 pushes it onto the AP stack... bummer, this can be shorter

**Pull request merged**
