### PR TITLE
Lifetime using demands

### PR DESCRIPTION
**Pull request by spapinistarkware**
**Stack**:
- #2284
- #2283
- #2282
- #2257
- #2254
- #2253
- #2252 ⬅
- #2245

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2252)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2252#-:-NOxmgQmA6fgRhiFe4vj:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/analysis.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2252#-NOxkcwm5HRApP8qBsk9:-NOxkcwm5HRApP8qBskA:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/4aa729cf1045b532a35c86f05fd64879b31d292a/crates/cairo-lang-lowering/src/borrow_check/analysis.rs#L13)):*
> ```XML
> };
> 
> pub type StatementLocation = (BlockId, usize);
> ```

doc



_Code quote:_
```XML
pub type StatementLocation = (BlockId, usize);
```
___
*[`crates/cairo-lang-sierra-generator/src/lifetime.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2252#-NOxkskSAot7nhSYokPF:-NOxkskSAot7nhSYokPG:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/4aa729cf1045b532a35c86f05fd64879b31d292a/crates/cairo-lang-sierra-generator/src/lifetime.rs#L101)):*
> ```XML
>     local_vars: &OrderedHashSet<VariableId>,
> ) -> Maybe<VariableLifetimeResult> {
>     eprintln!("------");
> ```

remove



_Code quote:_
```XML
    eprintln!("------");
```
___
*[`crates/cairo-lang-sierra-generator/src/lifetime.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2252#-NOxkyO7-feHbGg4imb1:-NOxkyO7-feHbGg4imb2:b-30x8x4) ([raw file](https://github.com/starkware-libs/cairo/blob/4aa729cf1045b532a35c86f05fd64879b31d292a/crates/cairo-lang-sierra-generator/src/lifetime.rs#L106)):*
> ```XML
>         BackAnalysis { lowered: lowered_function, cache: Default::default(), analyzer: context };
>     analysis.get_root_info();
>     // TODO(spapini): Handle unintroduced variables? Liek Uninitialized, perhaps?
> ```

reword a bit - and as discussed add relevant panic.



_Suggestion:_
```XML
    // TODO(spapini): Handle unintroduced variables? Like Uninitialized, perhaps?
```
___
*[`crates/cairo-lang-sierra-generator/src/lifetime.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2252#-NOxm7AWCFsnd1BRV7Fr:-NOxm7AWCFsnd1BRV7Fs:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/4aa729cf1045b532a35c86f05fd64879b31d292a/crates/cairo-lang-sierra-generator/src/lifetime.rs#L127)):*
> ```XML
> 
>     fn dup(&mut self, _position: StatementLocation, _var: SierraGenVar) {
>         eprintln!("dup {_var:?} {_position:?}");
> ```

remove



_Code quote:_
```XML
        eprintln!("dup {_var:?} {_position:?}");
```
___
*[`crates/cairo-lang-sierra-generator/src/lifetime.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2252#-NOxmB8e-2AGL6OzrDov:-NOxmB8e-2AGL6OzrDow:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/4aa729cf1045b532a35c86f05fd64879b31d292a/crates/cairo-lang-sierra-generator/src/lifetime.rs#L136)):*
> ```XML
>         _var: SierraGenVar,
>     ) {
>         eprintln!("LU {_var:?} {statement_location:?} {var_index}");
> ```

remove



_Code quote:_
```XML
        eprintln!("LU {_var:?} {statement_location:?} {var_index}");
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2252)* status: all files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2252)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/borrow_check/analysis.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2252#-NOxkcwm5HRApP8qBsk9:-NPCZFJN0eCDsdGSWaNP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4aa729cf1045b532a35c86f05fd64879b31d292a/crates/cairo-lang-lowering/src/borrow_check/analysis.rs#L13)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/lifetime.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2252#-NOxkskSAot7nhSYokPF:-NPCZSrz2_ij6QcZ3f8a:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4aa729cf1045b532a35c86f05fd64879b31d292a/crates/cairo-lang-sierra-generator/src/lifetime.rs#L101)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/lifetime.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2252#-NOxm7AWCFsnd1BRV7Fr:-NPCZV3E8HrRy9w1lZ-A:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4aa729cf1045b532a35c86f05fd64879b31d292a/crates/cairo-lang-sierra-generator/src/lifetime.rs#L127)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/lifetime.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2252#-NOxmB8e-2AGL6OzrDov:-NPCZW3d3NJawgCXMe8Q:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4aa729cf1045b532a35c86f05fd64879b31d292a/crates/cairo-lang-sierra-generator/src/lifetime.rs#L136)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2252)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request closed without merging**
