### PR TITLE
Using salsa from the rust-analyzer fork.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6173)

### CODE REVIEW

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 2 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6173)* status: 2 of 29 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @ilyalesokhin-starkware, @orizi, and @piotmag769)

___
*[`Cargo.toml` line 122 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6173#-O3mTRQB8yzW54nayXCF:-O3mTRQCCMFBphiJ1c9D:b-7hbpla) ([raw file](https://github.com/starkware-libs/cairo/blob/b9183d461eb84c4d1e25b4163e6256b2af5fb0e4/Cargo.toml#L122)):*
> ```TOML
> rayon = "1.10.0"
> rstest = "0.19.0"
> rust-analyzer-salsa = "0.17.0-pre.6"
> ```

wdyt?



_Suggestion:_
```TOML
salsa = { package = "rust-analyzer-salsa", version = "0.17.0-pre.6" }
```

**Review by mkaput — COMMENTED** [review]
> Reviewed 12 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6173)* status: 14 of 29 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @ilyalesokhin-starkware, @orizi, and @piotmag769)

**Review by piotmag769 — APPROVED** [review]
:lgtm:

> Reviewed 29 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6173#-:-O3mYeLv2GYKBOHEWFUg:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @ilyalesokhin-starkware, and @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6173)* status: 13 of 30 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @ilyalesokhin-starkware, @mkaput, and @piotmag769)

___
*[`Cargo.toml` line 122 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6173#-O3mTRQB8yzW54nayXCF:-O3w5zEN63eHJDRwE3mb:b19p5bj) ([raw file](https://github.com/starkware-libs/cairo/blob/b9183d461eb84c4d1e25b4163e6256b2af5fb0e4/Cargo.toml#L122)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

wdyt?
</blockquote></details>

Done.

Although - still in the process of handling the changes in cycle handling.

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6173)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @ilyalesokhin-starkware, and @orizi)

___
*[`crates/cairo-lang-starknet-classes/src/allowed_libfuncs_lists/audited.json` line 35 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6173#-O4eOP5Q2S0T5YgwHACY:-O4eOP5Q2S0T5YgwHACZ:b-jfimvs) ([raw file](https://github.com/starkware-libs/cairo/blob/d98bc26bb3dab8078663135992f09d5ac520f415/crates/cairo-lang-starknet-classes/src/allowed_libfuncs_lists/audited.json#L35)):*
> ```JSON
>         "bytes31_try_from_felt252",
>         "call_contract_syscall",
>         "circuit_failure_guarantee_verify",
> ```

change out of scope

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6173)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @ilyalesokhin-starkware, and @mkaput)

___
*[`crates/cairo-lang-starknet-classes/src/allowed_libfuncs_lists/audited.json` line 35 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6173#-O4eOP5Q2S0T5YgwHACY:-O4ekkgr5prVCOHOPgXJ:b9ojjl6) ([raw file](https://github.com/starkware-libs/cairo/blob/d98bc26bb3dab8078663135992f09d5ac520f415/crates/cairo-lang-starknet-classes/src/allowed_libfuncs_lists/audited.json#L35)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

change out of scope
</blockquote></details>

this PR is not ready for merge - so this isn't actually relevant.

**Review by mkaput — COMMENTED** [review]
> Reviewed 25 of 25 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6173)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, and @ilyalesokhin-starkware)

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6173)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @ilyalesokhin-starkware)

**Review by mkaput — APPROVED** [review]
:lgtm: but please @Draggu confirm that this works

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6173#-:-O4jPSUF52Ns10IUEoZS:b-cvkwa5)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @ilyalesokhin-starkware)

**Review by Draggu — APPROVED** [review]
> Reviewed 4 of 29 files at r1, 1 of 17 files at r2, 25 of 25 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6173)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @ilyalesokhin-starkware)

**Pull request merged**
