### PR TITLE
added lowering of FnOnce Call

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6355)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 11 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6355)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-sierra-generator/src/types.rs` line 206 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6355#-O60zjfe1gGCD9aj5I2g:-O60zjfe1gGCD9aj5I2h:bvp5kch) ([raw file](https://github.com/starkware-libs/cairo/blob/92187f8ef4f5f5a0979998d79af3d13365653943/crates/cairo-lang-sierra-generator/src/types.rs#L206)):*
> ```XML
>         semantic::TypeLongId::Closure(_) => {
>             vec![]
>         }
> ```

this needs to be the same as tuple.



_Code quote:_
```XML
            vec![]
        }
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6355)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/types.rs` line 206 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6355#-O60zjfe1gGCD9aj5I2g:-O611XP98HKmHPHCv6_z:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/92187f8ef4f5f5a0979998d79af3d13365653943/crates/cairo-lang-sierra-generator/src/types.rs#L206)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this needs to be the same as tuple.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6355)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-sierra-generator/src/types.rs` line 206 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6355#-O60zjfe1gGCD9aj5I2g:-O612RpmAsuFMyURvSJl:b10l6vt) ([raw file](https://github.com/starkware-libs/cairo/blob/92187f8ef4f5f5a0979998d79af3d13365653943/crates/cairo-lang-sierra-generator/src/types.rs#L206)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

this needs to be the captured types - not the param types.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6355)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/types.rs` line 206 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6355#-O60zjfe1gGCD9aj5I2g:-O61hTSO1tjP2hXwxqcz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/92187f8ef4f5f5a0979998d79af3d13365653943/crates/cairo-lang-sierra-generator/src/types.rs#L206)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this needs to be the captured types - not the param types.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6355)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-sierra-generator/src/types.rs` line 161 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6355#-O61wgFW1AMi_8uwVJfJ:-O61wgFW1AMi_8uwVJfK:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/41f24159fd2577f9069e6f29a8c337b2a65c75cb/crates/cairo-lang-sierra-generator/src/types.rs#L161)):*
> ```XML
>         semantic::TypeLongId::Closure(ty) => {
>             user_type_long_id("Struct", format!("{:?}", ty.debug(db.upcast())).into())?.into()
>         }
> ```





_Suggestion:_
```XML
        semantic::TypeLongId::Closure(_) => {
            user_type_long_id("Struct", ty.format(db.upcast())).into())?.into()
        }
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6355)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/types.rs` line 161 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6355#-O61wgFW1AMi_8uwVJfJ:-O6Fjo4f5_WjdtYBhQlj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/41f24159fd2577f9069e6f29a8c337b2a65c75cb/crates/cairo-lang-sierra-generator/src/types.rs#L161)):*
> ```XML
>         semantic::TypeLongId::Closure(ty) => {
>             user_type_long_id("Struct", format!("{:?}", ty.debug(db.upcast())).into())?.into()
>         }
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6355#-:-O6FoT1G0XsPIbPdN6h6:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 11 of 12 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6355#-:-O6Ftx0699t0HWf5TLdi:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
