### PR TITLE
Add declaration of into_nullable() libfunc.

### PR DESCRIPTION
**Pull request by liorgold2**
commit-id:59b9410b

---

**Stack**:
- #1451
- #1436
- #1435 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1435#-:-NJqlzlf5QRLBMhPgTWv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1435)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/sierra/src/extensions/modules/nullable.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1435#-NJqmSSRANUPuRIJSgNF:-NJqmSSRANUPuRIJSgNG:bqtnq9e) ([raw file](https://github.com/starkware-libs/cairo/blob/6f222bb186c32f2722244c2ed33d4510b0736f9f/crates/sierra/src/extensions/modules/nullable.rs#L96)):*
> ```XML
>             }],
>             SierraApChange::Known { new_vars_only: true },
>         ))
> ```

this function does nothing - so no reason for it not to handle any form the box is at.



_Suggestion:_
```XML
        Ok(LibFuncSignature::new_non_branch_ex(
            vec![ParamSignature { ty context.get_wrapped_concrete_type(BoxType::id(), ty.clone())?, allow: true... }],
            vec![OutputVarInfo {
                ty: context.get_wrapped_concrete_type(NullableType::id(), ty)?,
                ref_info: OutputVarReferenceInfo::SameAsParam { param_idx: 0 },
            }],
            SierraApChange::Known { new_vars_only: true },
        ))
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1435)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/sierra/src/extensions/modules/nullable.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1435#-NJqmSSRANUPuRIJSgNF:-NJvbYni6wRSOmXpWeqB:b-d99b93) ([raw file](https://github.com/starkware-libs/cairo/blob/1c70001703c45324701934eb86463a2ea6a74c8f/crates/sierra/src/extensions/modules/nullable.rs#L96)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this function does nothing - so no reason for it not to handle any form the box is at.
</blockquote></details>

Since I'm taking a non-trivial assumption - that the pointer of `Box<T>` is never 0 - I prefer to be on the safe side here.
See the comment in the next PR.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1435)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/sierra/src/extensions/modules/nullable.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1435#-NJqmSSRANUPuRIJSgNF:-NJve2pY8hmZQPe2yXtr:bkd7rs1) ([raw file](https://github.com/starkware-libs/cairo/blob/1c70001703c45324701934eb86463a2ea6a74c8f/crates/sierra/src/extensions/modules/nullable.rs#L96)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Since I'm taking a non-trivial assumption - that the pointer of `Box<T>` is never 0 - I prefer to be on the safe side here.
See the comment in the next PR.
</blockquote></details>

this is unrelated to the point - you still don't do any checks - so you can just return the same expression cell you received and it can be of any sub-type.

**Review by orizi — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1435)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1435)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1435)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

___
*[`crates/sierra/src/extensions/modules/nullable.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1435#-NJqmSSRANUPuRIJSgNF:-NJyRIdS5ke5crsHGBDN:b9e5p9j) ([raw file](https://github.com/starkware-libs/cairo/blob/1c70001703c45324701934eb86463a2ea6a74c8f/crates/sierra/src/extensions/modules/nullable.rs#L96)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is unrelated to the point - you still don't do any checks - so you can just return the same expression cell you received and it can be of any sub-type.
</blockquote></details>

Summarizing our discussion:

It only matters whether the pointer is zero or not in `from_nullable`, where we will check checked that it was already stored (and thus if the pointer is zero, it means that it's the `null` option).

**Pull request merged**
