### PR TITLE
updated left vs right line breaking

### PR DESCRIPTION
**Pull request by dean-starkware**

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6744)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/node_properties.rs` line 336 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6744#-OCcGgcsEO00eyYSYL4u:-OCcGgct6HuTP0GDZ6Aw:b-sxmbq9) ([raw file](https://github.com/starkware-libs/cairo/blob/c8c75eccd453ad5c5533886907542f485320985f/crates/cairo-lang-formatter/src/node_properties.rs#L336)):*
> ```XML
>                 {
>                     Some(9)
>                 } else {
> ```

using length is problematic - you probably need to check length in another way.
or just decide on one side before of the other

otherwise:
```
let struct { x // so much whitespace                                                                                              
} = foo(not, as, long, but, will, be, after, trimming, whitespace);
```

would be changed after second fmt call.



_Code quote:_
```XML
                let let_statement = ast::StatementLet::from_syntax_node(db, self.parent().unwrap());
                let pattern_len = let_statement.pattern(db).as_syntax_node().get_text(db).len();
                let rhs_len = let_statement.rhs(db).as_syntax_node().get_text(db).len();
                if pattern_len > rhs_len
                    && let_statement.pattern(db).as_syntax_node().kind(db)
                        == SyntaxKind::PatternStruct
                {
                    Some(9)
                } else {
```

**Review by dean-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6744)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-formatter/src/node_properties.rs` line 336 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6744#-OCcGgcsEO00eyYSYL4u:-OCc_cEI5svFxFV56JgJ:bapfznv) ([raw file](https://github.com/starkware-libs/cairo/blob/c8c75eccd453ad5c5533886907542f485320985f/crates/cairo-lang-formatter/src/node_properties.rs#L336)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

using length is problematic - you probably need to check length in another way.
or just decide on one side before of the other

otherwise:
```
let struct { x // so much whitespace                                                                                              
} = foo(not, as, long, but, will, be, after, trimming, whitespace);
```

would be changed after second fmt call.
</blockquote></details>

Good point. I decided to base it on the number of children of each node.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6744)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/node_properties.rs` line 332 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6744#-OCck1YX7INfAR8jhNFx:-OCck1YX7INfAR8jhNFy:b-x767rn) ([raw file](https://github.com/starkware-libs/cairo/blob/7e64562a24bca4f86c36815103e77eb6da163cde/crates/cairo-lang-formatter/src/node_properties.rs#L332)):*
> ```XML
>                 // Count significant children in pattern and RHS.
>                 let pattern_count = db.get_children(pattern.clone()).len();
>                 let rhs_count = db.get_children(let_statement.rhs(db).as_syntax_node()).len();
> ```

document the logic.

note that it is VERY unclear what does the length of the rhs actually means here.



_Code quote:_
```XML
let rhs_count = db.get_children(let_statement.rhs(db).as_syntax_node()).len();
```

**Review by dean-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6744)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-formatter/src/node_properties.rs` line 332 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6744#-OCck1YX7INfAR8jhNFx:-OCcvdkv5QI4amM3UgRD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7e64562a24bca4f86c36815103e77eb6da163cde/crates/cairo-lang-formatter/src/node_properties.rs#L332)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

document the logic.

note that it is VERY unclear what does the length of the rhs actually means here.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6744)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/node_properties.rs` line 332 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6744#-OCck1YX7INfAR8jhNFx:-OCd-hqO9h73BajUwCXE:b-lk1bud) ([raw file](https://github.com/starkware-libs/cairo/blob/7e64562a24bca4f86c36815103e77eb6da163cde/crates/cairo-lang-formatter/src/node_properties.rs#L332)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

the children isn't a really good variant for that - the basic number of children for even a block expression is 3.

how about `.desendents().len()` on both sides?
(specifically - only if matches `pattern)

**Review by dean-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6744)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-formatter/src/node_properties.rs` line 332 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6744#-OCck1YX7INfAR8jhNFx:-OCgTL2t150pUQESL7lR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7e64562a24bca4f86c36815103e77eb6da163cde/crates/cairo-lang-formatter/src/node_properties.rs#L332)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the children isn't a really good variant for that - the basic number of children for even a block expression is 3.

how about `.desendents().len()` on both sides?
(specifically - only if matches `pattern)
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6744)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/node_properties.rs` line 336 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6744#-OCgUzZ79W-PaucYG3Ak:-OCgUzZ79W-PaucYG3Al:b-ntukqg) ([raw file](https://github.com/starkware-libs/cairo/blob/87e939afd4e9b86f5b640c591792c29754ab09ba/crates/cairo-lang-formatter/src/node_properties.rs#L336)):*
> ```XML
>                 // intricate or multi-part expression.
>                 let pattern_count = pattern.descendants(db).count();
>                 let rhs_count = let_statement.rhs(db).as_syntax_node().descendants(db).count();
> ```

and doc why (this is just to make sure we don't do too long of an iteration.



_Suggestion:_
```XML
                let rhs_count = let_statement.rhs(db).as_syntax_node().descendants(db).take(pattern_count + 1).count();
```

**Review by dean-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6744)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-formatter/src/node_properties.rs` line 336 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6744#-OCgUzZ79W-PaucYG3Ak:-OCgax5Y1NwhBElSTnFp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/87e939afd4e9b86f5b640c591792c29754ab09ba/crates/cairo-lang-formatter/src/node_properties.rs#L336)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

and doc why (this is just to make sure we don't do too long of an iteration.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6744)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/node_properties.rs` line 348 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6744#-OCgdjfDAPrTkFOq66lT:-OCgdjfDAPrTkFOq66lU:bsreyp0) ([raw file](https://github.com/starkware-libs/cairo/blob/48f50e809181e8e0e485b529bc8448b2b45925d0/crates/cairo-lang-formatter/src/node_properties.rs#L348)):*
> ```XML
>                     .count();
> 
>                 if pattern_count > rhs_count && pattern.kind(db) == SyntaxKind::PatternStruct {
> ```

either don't have this part - or make it prevent the rest of the calculation if false.



_Code quote:_
```XML
 pattern.kind(db) == SyntaxKind::PatternStruct
```

**Review by dean-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6744)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-formatter/src/node_properties.rs` line 348 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6744#-OCgdjfDAPrTkFOq66lT:-OCghkGcErQHmfWK5c76:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/48f50e809181e8e0e485b529bc8448b2b45925d0/crates/cairo-lang-formatter/src/node_properties.rs#L348)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

either don't have this part - or make it prevent the rest of the calculation if false.
</blockquote></details>

Done.

**Pull request merged**
