### PR TITLE
support for otherwise pattern in match for enums

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4557)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4557)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/test_data/match` line 761 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4557#-NlYGzjg3E0rv87n96VE:-NlYGzjg3E0rv87n96VF:b2hrk56) ([raw file](https://github.com/starkware-libs/cairo/blob/6acecfedede939ba58b1fbfda20e432e8051cafc/crates/cairo-lang-lowering/src/test_data/match#L761)):*
> ```
> 
> //! > lowering_diagnostics
> error: Enum variant `VariantId(test::Three)` not covered.
> ```

improve message



_Code quote:_
```
`VariantId(test::Three)`
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4557)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/test_data/match` line 761 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4557#-NlYGzjg3E0rv87n96VE:-NlbzHBWDpjs-1eV8qI3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6acecfedede939ba58b1fbfda20e432e8051cafc/crates/cairo-lang-lowering/src/test_data/match#L761)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

improve message
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4557)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1121 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4557#-Nlc56tg44WlV-zCRzqB:-Nlc56tg44WlV-zCRzqC:b53aqkg) ([raw file](https://github.com/starkware-libs/cairo/blob/5c6cc93062b0f6d2543b420b398033b2d682b785/crates/cairo-lang-lowering/src/lower/mod.rs#L1121)):*
> ```XML
>             let block_id = subscope.block_id;
> 
>             let arm_index = variant_map
> ```

report all missing variants.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1255 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4557#-Nlc4hxA8fQVTHw8KGkq:-Nlc4hxA8fQVTHw8KGkr:btid411) ([raw file](https://github.com/starkware-libs/cairo/blob/5c6cc93062b0f6d2543b420b398033b2d682b785/crates/cairo-lang-lowering/src/lower/mod.rs#L1255)):*
> ```XML
>                 Pattern::EnumVariant(PatternEnumVariant { inner_pattern: None, .. })
>                 | Pattern::Otherwise(_) => Ok(()),
>                 _ => unreachable!(),
> ```

explain why in the macro string.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4557)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1121 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4557#-Nlc56tg44WlV-zCRzqB:-NlcjLEM9AHJStdpuGAd:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5c6cc93062b0f6d2543b420b398033b2d682b785/crates/cairo-lang-lowering/src/lower/mod.rs#L1121)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

report all missing variants.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1255 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4557#-Nlc4hxA8fQVTHw8KGkq:-NlcjLfr6wN9Prg-eshf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5c6cc93062b0f6d2543b420b398033b2d682b785/crates/cairo-lang-lowering/src/lower/mod.rs#L1255)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

explain why in the macro string.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4557)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1052 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4557#-NldFoHR-q9N_159cM1U:-NldFoHR-q9N_159cM1V:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ae27a560b056fb492df2cd4a2fa5bca20730baaf/crates/cairo-lang-lowering/src/lower/mod.rs#L1052)):*
> ```XML
> ) -> LoweringResult<UnorderedHashMap<semantic::ConcreteVariant, usize>> {
>     let mut map: UnorderedHashMap<_, _> = UnorderedHashMap::default();
>     for (arm_index, arm) in arms.enumerate() {
> ```





_Suggestion:_
```XML
/// Returns a map from variants to their corresponding arm index.
fn get_variant_to_arm_map<'a>(
    ctx: &mut LoweringContext<'_, '_>,
    arms: impl Iterator<Item = &'a semantic::MatchArm>,
    concrete_enum_id: semantic::ConcreteEnumId,
) -> LoweringResult<UnorderedHashMap<semantic::ConcreteVariant, usize>> {
    let mut map: UnorderedHashMap<_, _> = UnorderedHashMap::default();
    for (arm_index, arm) in arms.enumerate() {
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4557)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1051 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4557#-NlqGhTb68VTP78FMRAS:-NlqGhTb68VTP78FMRAT:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a001bf8955d9b0480f98b771cd269d5c2e49bd93/crates/cairo-lang-lowering/src/lower/mod.rs#L1051)):*
> ```XML
>     concrete_enum_id: semantic::ConcreteEnumId,
> ) -> LoweringResult<UnorderedHashMap<semantic::ConcreteVariant, usize>> {
>     let mut map: UnorderedHashMap<_, _> = UnorderedHashMap::default();
> ```





_Suggestion:_
```XML
    let mut map = UnorderedHashMap::default();
```
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1109 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4557#-NlqGrLg6jvEDe8rU8Eb:-NlqGrLg6jvEDe8rU8Ec:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a001bf8955d9b0480f98b771cd269d5c2e49bd93/crates/cairo-lang-lowering/src/lower/mod.rs#L1109)):*
> ```XML
>     let otherwise_variant = get_underscore_pattern_index(ctx, &expr.arms);
>     let variant_map: UnorderedHashMap<_, _> = get_variant_to_arm_map(
>         ctx,
> ```





_Suggestion:_
```XML
    let variant_map = get_variant_to_arm_map(
        ctx,
```
___
*[`crates/cairo-lang-lowering/src/test_data/match` line 781 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4557#-NlqHUx-BDs0BHKu1S-9:-NlqHUx-BDs0BHKu1S-A:b-ps53hi) ([raw file](https://github.com/starkware-libs/cairo/blob/a001bf8955d9b0480f98b771cd269d5c2e49bd93/crates/cairo-lang-lowering/src/test_data/match#L781)):*
> ```
> //! > ==========================================================================
> 
> //! > Test match on enum tuples.
> ```

is this related to this pr?
___
*[`crates/cairo-lang-lowering/src/test_data/match` line 788 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4557#-NlqHNMK1T0S3vaG9OWW:-NlqHNMK1T0S3vaG9OWX:b3gmkpd) ([raw file](https://github.com/starkware-libs/cairo/blob/a001bf8955d9b0480f98b771cd269d5c2e49bd93/crates/cairo-lang-lowering/src/test_data/match#L788)):*
> ```
> //! > function
> fn foo(a: A,b: A) -> felt252 {
>   match (a,b) {
> ```

format code

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4557#-:-NlqfJRr0AOI8AI23pC5:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4557)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1051 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4557#-NlqGhTb68VTP78FMRAS:-Nlqem3i3_i51uYGhH4c:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a001bf8955d9b0480f98b771cd269d5c2e49bd93/crates/cairo-lang-lowering/src/lower/mod.rs#L1051)):*
> ```XML
>     concrete_enum_id: semantic::ConcreteEnumId,
> ) -> LoweringResult<UnorderedHashMap<semantic::ConcreteVariant, usize>> {
>     let mut map: UnorderedHashMap<_, _> = UnorderedHashMap::default();
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1109 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4557#-NlqGrLg6jvEDe8rU8Eb:-NlqemlQ7i3LYaSoRIky:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a001bf8955d9b0480f98b771cd269d5c2e49bd93/crates/cairo-lang-lowering/src/lower/mod.rs#L1109)):*
> ```XML
>     let otherwise_variant = get_underscore_pattern_index(ctx, &expr.arms);
>     let variant_map: UnorderedHashMap<_, _> = get_variant_to_arm_map(
>         ctx,
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/test_data/match` line 781 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4557#-NlqHUx-BDs0BHKu1S-9:-Nlqeo7mDA-fPC6MLWCj:b29b4u2) ([raw file](https://github.com/starkware-libs/cairo/blob/a001bf8955d9b0480f98b771cd269d5c2e49bd93/crates/cairo-lang-lowering/src/test_data/match#L781)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is this related to this pr?
</blockquote></details>

no,removed
___
*[`crates/cairo-lang-lowering/src/test_data/match` line 788 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4557#-NlqHNMK1T0S3vaG9OWW:-Nlqer384hKJhm-4M-fJ:b-hfpv0l) ([raw file](https://github.com/starkware-libs/cairo/blob/a001bf8955d9b0480f98b771cd269d5c2e49bd93/crates/cairo-lang-lowering/src/test_data/match#L788)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

format code
</blockquote></details>

removed

**Pull request merged**
