### PR TITLE
Reverted `try_fetch_gas` names back into `get_gas`.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2372)

### CODE REVIEW

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 44 of 44 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2372)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-runner/README.md` line 24 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2372#-NPmj2HBEmLVC_tsovr0:-NPmj2HBEmLVC_tsovr1:bwevvun) ([raw file](https://github.com/starkware-libs/cairo/blob/091698ef277e8d74bdb2cbce86889b937d349f69/crates/cairo-lang-runner/README.md#L24)):*
> ```Markdown
> /// Calculates fib...
> fn fib(a: felt, b: felt, n: felt) -> Option::<felt> {
>     get_gas()?;
> ```

I guess:



_Suggestion:_
```Markdown
    gas::get_gas()?;
```
___
*[`crates/cairo-lang-runner/src/lib.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2372#-NPmj8ZEE0BJTBV0e-_q:-NPmj8ZEE0BJTBV0e-_r:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/091698ef277e8d74bdb2cbce86889b937d349f69/crates/cairo-lang-runner/src/lib.rs#L39)):*
> ```XML
>     #[error("GasBuiltin is required while `available_gas` value is provided.")]
>     GasBuiltinRequired,
>     #[error("Failed calculating gas usage, it is likely a call for `get_gas` is missing.")]
> ```





_Suggestion:_
```XML
    #[error("Failed calculating gas usage, it is likely a call for `gas::get_gas` is missing.")]
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2372)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-runner/README.md` line 24 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2372#-NPmj2HBEmLVC_tsovr0:-NPmkdJVEmjkgGFYzzVm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/091698ef277e8d74bdb2cbce86889b937d349f69/crates/cairo-lang-runner/README.md#L24)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

I guess:
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runner/src/lib.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2372#-NPmj8ZEE0BJTBV0e-_q:-NPmkhFa4C7vZxYGHjgl:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/091698ef277e8d74bdb2cbce86889b937d349f69/crates/cairo-lang-runner/src/lib.rs#L39)):*
> ```XML
>     #[error("GasBuiltin is required while `available_gas` value is provided.")]
>     GasBuiltinRequired,
>     #[error("Failed calculating gas usage, it is likely a call for `get_gas` is missing.")]
> ```

Done.

**Review by liorgold2 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2372)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2372#-:-NPnp14EC1_8wH655TNc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
