### PR TITLE
Introduced `DynEq + DynHash` bounds for `MacroPlugin`, `InlineMacroExprPlugin` and `AnalyzerPlugin` traits

### PR DESCRIPTION
**Pull request by integraledelebesgue**
**Stack**:
- #6843
- #6842
- #6841
- #6840
- #6839 ⬅
- #6838

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6839)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6839#-ODRhU3oBbUtNbRFoA-M:-ODRlilW5g5PCbqECv_g:b1i0y9f):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

please elaborate as to why you need this.
</blockquote></details>

I don't think we want to go this route. Have you considered just hashing and comparing pointers that are underlying to `Arc<MacroPlugin>` at all?

**Review by integraledelebesgue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6839)* status: all files reviewed, 1 unresolved discussion (waiting on @Draggu)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6839#-ODRhU3oBbUtNbRFoA-M:-ODRm-876M8_QpynyZVR:b-95fq46):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I don't think we want to go this route. Have you considered just hashing and comparing pointers that are underlying to `Arc<MacroPlugin>` at all?
</blockquote></details>

That was my first idea :) Such an approach is fine for plugins being unit structs, but is it safe to generalize it for non-unit plugins, especially the Scarb plugin? cc: @Draggu

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 31 of 31 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6839)* status: all files reviewed, 1 unresolved discussion (waiting on @Draggu)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6839#-ODRhU3oBbUtNbRFoA-M:-ODRq6LE-sOE6BhToiTi:byahppg):*
<details><summary><i>Previously, integraledelebesgue (Jan Smółka) wrote…</i></summary><blockquote>

That was my first idea :) Such an approach is fine for plugins being unit structs, but is it safe to generalize it for non-unit plugins, especially the Scarb plugin? cc: @Draggu
</blockquote></details>

wdym by Scarb plugin?

no plugin known to me has any state (and having one is pretty hardcore idea) so we can afford having duplicate instances of a plugin in worst case

**Review by integraledelebesgue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6839)* status: all files reviewed, 1 unresolved discussion (waiting on @Draggu)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6839#-ODRhU3oBbUtNbRFoA-M:-ODRuGzT2DJJDye1RwvR:begsp4k):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

wdym by Scarb plugin?

no plugin known to me has any state (and having one is pretty hardcore idea) so we can afford having duplicate instances of a plugin in worst case
</blockquote></details>

I'm talking about plugins like, for example, [`ProcMacroHostPlugin`](https://github.com/software-mansion/scarb/blob/b96c1bc8918256229a3bda9fe0be60a6d49a95f9/scarb/src/compiler/plugin/proc_macro/host.rs#L49) from Scarb. It's not a unit struct. At the same time, it becomes a part of a plugin suite loaded into a `RootDatabase` during Scarb compilation [here](https://github.com/software-mansion/scarb/blob/b96c1bc8918256229a3bda9fe0be60a6d49a95f9/scarb/src/compiler/db.rs#L67).

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6839)* status: all files reviewed, 1 unresolved discussion (waiting on @Draggu)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6839#-ODRhU3oBbUtNbRFoA-M:-ODexUbg5Cpscghwzw5I:b9iud9c):*
<details><summary><i>Previously, integraledelebesgue (Jan Smółka) wrote…</i></summary><blockquote>

I'm not saying we cannot compare pointers here, just wonder if that's a good approach for all possible forms of plugins.
</blockquote></details>

discussed offline -> let's go with pointer comparisons

**Comment by integraledelebesgue** [comment]
Closing pull request: commit has gone away

**Pull request closed without merging**
