### PR TITLE
Add keccak system call.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2862)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2862)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/starknet/syscalls.cairo` line 82 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2862#-NTIt4Oj9WB5KruXG0t1:-NTIt4Oj9WB5KruXG0t2:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/92d632dcf9d9c5b25251f2e2e079080b19f26a9f/corelib/src/starknet/syscalls.cairo#L82)):*
> ```Cairo
> 
> 
> // Computes the keccack of the input
> ```





_Suggestion:_
```Cairo
// Computes the keccak of the input.
```
___
*[`tests/e2e_test_data/libfuncs/starknet/syscalls` line 522 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2862#-NTItIr3Dj9c2AuCMQ68:-NTItIr3Dj9c2AuCMQ69:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/92d632dcf9d9c5b25251f2e2e079080b19f26a9f/tests/e2e_test_data/libfuncs/starknet/syscalls#L522)):*
> ```
> //! > ==========================================================================
> 
> //! > ==========================================================================
> ```





_Suggestion:_
```
//! > ==========================================================================

//! > keccak libfunc
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2862)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/starknet/syscalls.cairo` line 82 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2862#-NTIt4Oj9WB5KruXG0t1:-NTSE1pmDB2ncj6P5Tri:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/92d632dcf9d9c5b25251f2e2e079080b19f26a9f/corelib/src/starknet/syscalls.cairo#L82)):*
> ```Cairo
> 
> 
> // Computes the keccack of the input
> ```

Done.
___
*[`tests/e2e_test_data/libfuncs/starknet/syscalls` line 522 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2862#-NTItIr3Dj9c2AuCMQ68:-NTSE2IQEp5l0Dosql4r:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/92d632dcf9d9c5b25251f2e2e079080b19f26a9f/tests/e2e_test_data/libfuncs/starknet/syscalls#L522)):*
> ```
> //! > ==========================================================================
> 
> //! > ==========================================================================
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2862#-:-NTSEpOl8z-hhv3Ya0nv:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2862#-NTItfUZ5RiRPWIlBgQo:-NTItfUZ5RiRPWIlBgQp:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/92d632dcf9d9c5b25251f2e2e079080b19f26a9f/crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs#L153)):*
> ```XML
> }
> 
> /// Libfunc for the keccak system call.
> ```





_Suggestion:_
```XML
/// Libfunc for the keccak system call.
/// The libfunc takes an input with padding and returns the keccak hash.
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2862)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2862#-NTItfUZ5RiRPWIlBgQo:-NTSItcoEOtNK35WPsKG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/92d632dcf9d9c5b25251f2e2e079080b19f26a9f/crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs#L153)):*
> ```XML
> }
> 
> /// Libfunc for the keccak system call.
> ```

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2862)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 6 of 9 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2862)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
