### PR TITLE
Add DowncastableInt trait.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4603)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/types.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4603#-Nm6P_Jv08nSAF0JzKkC:-Nm6P_Jv08nSAF0JzKkD:bpprn0q) ([raw file](https://github.com/starkware-libs/cairo/blob/e7083b15ccfbaf459800826f5dd90f33bccbba08/crates/cairo-lang-semantic/src/types.rs#L78)):*
> ```XML
>     }
> 
>     pub fn is_inference_complete(&self, db: &dyn SemanticGroup) -> bool {
> ```

Not sure how to call this function.

I could call it is_concrete but it returns false for vars, I'm not sure if it is good or not.



_Code quote:_
```XML
is_inference_complete(
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4603)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/integer.cairo` line 1761 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4603#-Nm6YEbxB38cVYRtKOvb:-Nm6YEbxB38cVYRtKOvc:b-7p36ra) ([raw file](https://github.com/starkware-libs/cairo/blob/e7083b15ccfbaf459800826f5dd90f33bccbba08/corelib/src/integer.cairo#L1761)):*
> ```Cairo
> 
> impl DowncastableIntTryInto<
>     From, To, +DowncastableInt<From>, +DowncastableInt<To>, -TypeEqual<From, To>
> ```

would this work properly?
(and then just add an `IntoTryInto` implementation.



_Suggestion:_
```Cairo
impl DowncastableIntTryInto<
    From, To, +DowncastableInt<From>, +DowncastableInt<To>, -Into<From, To>
```

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/integer.cairo` line 1761 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4603#-Nm6YEbxB38cVYRtKOvb:-Nm6rTigDYDiUTIuV5Yi:b-yngx7a) ([raw file](https://github.com/starkware-libs/cairo/blob/e7083b15ccfbaf459800826f5dd90f33bccbba08/corelib/src/integer.cairo#L1761)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

would this work properly?
(and then just add an `IntoTryInto` implementation.
</blockquote></details>

when is the negative impl for TryIntoFromInto?

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/integer.cairo` line 1761 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4603#-Nm6YEbxB38cVYRtKOvb:-Nm6rpMpEN9vGqZBfdQ4:b-2vpiwy) ([raw file](https://github.com/starkware-libs/cairo/blob/e7083b15ccfbaf459800826f5dd90f33bccbba08/corelib/src/integer.cairo#L1761)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

when is the negative impl for TryIntoFromInto?
</blockquote></details>

what is?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4603)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/integer.cairo` line 1761 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4603#-Nm6YEbxB38cVYRtKOvb:-Nm8Lxr04nMrpXICXjE_:bk0zksh) ([raw file](https://github.com/starkware-libs/cairo/blob/e7083b15ccfbaf459800826f5dd90f33bccbba08/corelib/src/integer.cairo#L1761)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what is?
</blockquote></details>

probably always - unlikely to ever have a better impl.
___
*[`crates/cairo-lang-semantic/src/types.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4603#-Nm6P_Jv08nSAF0JzKkC:-Nm8LqqU3vq9ubWYNOql:b-pmjl88) ([raw file](https://github.com/starkware-libs/cairo/blob/e7083b15ccfbaf459800826f5dd90f33bccbba08/crates/cairo-lang-semantic/src/types.rs#L78)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Not sure how to call this function.

I could call it is_concrete but it returns false for vars, I'm not sure if it is good or not.
</blockquote></details>

suggested "fully_concrete"

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4603)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/integer.cairo` line 1761 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4603#-Nm6YEbxB38cVYRtKOvb:-NmBdVZpBYvBLFQtIgf-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e7083b15ccfbaf459800826f5dd90f33bccbba08/corelib/src/integer.cairo#L1761)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

probably always - unlikely to ever have a better impl.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4603)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference/solver.rs` line 187 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4603#-NmBhbfIC2v9vU25S9lk:-NmBhbfIC2v9vU25S9ll:b7njzh0) ([raw file](https://github.com/starkware-libs/cairo/blob/b5dcfc74589b95ecba89776e5fbe5feaf37bb8b7/crates/cairo-lang-semantic/src/expr/inference/solver.rs#L187)):*
> ```XML
>                         break;
>                     }
>                 }
> ```

extract to func and doc well.



_Code quote:_
```XML
                for garg in db.impl_def_generic_params(concrete_impl.impl_def_id(db.upcast()))? {
                    let GenericParam::NegImpl(neg_impl) = garg else {
                        continue;
                    };

                    let concrete_trait_id = rewriter.rewrite(neg_impl)?.concrete_trait?;
                    for garg in concrete_trait_id.generic_args(db) {
                        let GenericArgumentId::Type(ty) = garg else {
                            continue;
                        };

                        if let TypeLongId::Var(_) = db.lookup_intern_type(ty) {
                            if !ty.is_fully_concrete(db) {
                                return Ok(SolutionSet::Ambiguous(
                                    Ambiguity::NegativeImplWithUnresolvedGenericArgs {
                                        impl_id: candidate_solver.candidate_impl,
                                        ty,
                                    },
                                ));
                            }
                        }
                    }

                    if !matches!(
                        inference
                            .trait_solution_set(concrete_trait_id, self.lookup_context.clone())?,
                        SolutionSet::None
                    ) {
                        // If a negative impl has an impl, then we should skip it.
                        candidate_solution_set = SolutionSet::None;
                        break;
                    }
                }
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4603)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/inference/solver.rs` line 187 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4603#-NmBhbfIC2v9vU25S9lk:-NmBvWICEdJbMrL1bmg5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b5dcfc74589b95ecba89776e5fbe5feaf37bb8b7/crates/cairo-lang-semantic/src/expr/inference/solver.rs#L187)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

extract to func and doc well.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/inference/solver.rs` line 256 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4603#-NmBvZ3CABeNfeFhYBP3:-NmBvZ3D6JqeRYl5F8YE:b-lyktf3) ([raw file](https://github.com/starkware-libs/cairo/blob/1c554ce209a1efecd86da747849205c84d09f291/crates/cairo-lang-semantic/src/expr/inference/solver.rs#L256)):*
> ```XML
>                                             ty,
>                                         },
>                                     ));
> ```

Note that because of this case I have to return:
InferenceResult<SolutionSet<CanonicalImpl>>

So I can't move this logic to
inference.is_candidate_valid(...).



_Code quote:_
```XML
                                    return Ok(SolutionSet::Ambiguous(
                                        Ambiguity::NegativeImplWithUnresolvedGenericArgs {
                                            impl_id: self.candidate_impl,
                                            ty,
                                        },
                                    ));
```
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 655 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4603#-NmBvDFT4GQr5UvavKb_:-NmBvDFT4GQr5UvavKba:bhzokyi) ([raw file](https://github.com/starkware-libs/cairo/blob/79207b122190302c3df68183bc8732febab893d7/crates/cairo-lang-semantic/src/expr/inference.rs#L655)):*
> ```XML
>                                     ty,
>                                 },
>                             ));
> ```

Not that because of this case I have to 



_Code quote:_
```XML
                            return Ok(SolutionSet::Ambiguous(
                                Ambiguity::NegativeImplWithUnresolvedGenericArgs {
                                    impl_id: self.candidate_impl,
                                    ty,
                                },
                            ));
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4603)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference/solver.rs` line 255 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4603#-NmByMsNAe7b5kZ3teNX:-NmByMsNAe7b5kZ3teNY:b-d441a3) ([raw file](https://github.com/starkware-libs/cairo/blob/1c554ce209a1efecd86da747849205c84d09f291/crates/cairo-lang-semantic/src/expr/inference/solver.rs#L255)):*
> ```XML
>                                             impl_id: self.candidate_impl,
>                                             ty,
>                                         },
> ```

doc why this means this is ambiguous.



_Code quote:_
```XML
                            if let TypeLongId::Var(_) = db.lookup_intern_type(ty) {
                                if !ty.is_fully_concrete(db) {
                                    return Ok(SolutionSet::Ambiguous(
                                        Ambiguity::NegativeImplWithUnresolvedGenericArgs {
                                            impl_id: self.candidate_impl,
                                            ty,
                                        },
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4603)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/inference/solver.rs` line 255 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4603#-NmByMsNAe7b5kZ3teNX:-NmPtkrx22GHPv5v0mGO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1c554ce209a1efecd86da747849205c84d09f291/crates/cairo-lang-semantic/src/expr/inference/solver.rs#L255)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc why this means this is ambiguous.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4603#-:-NmQ5Rdh9H3aC5bM8Fig:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
