### PR TITLE
Add statements->functions map to `SierraDebugInfo`

### PR DESCRIPTION
**Pull request by piotmag769**
Follow up to https://github.com/starkware-libs/cairo/pull/5306

This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5325)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5325)* status: 1 of 22 files reviewed, 1 unresolved discussion (waiting on @piotmag769)

___
*[`crates/cairo-lang-sierra/src/debug_info.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5325#-NtqTXqpC5MEp64LdB86:-NtqTXqpC5MEp64LdB87:b-tego6d) ([raw file](https://github.com/starkware-libs/cairo/blob/5689c4fe5798864bdce98282d6abe4bbd469ba5e/crates/cairo-lang-sierra/src/debug_info.rs#L40)):*
> ```XML
>     pub annotations: Annotations,
> 
>     pub statements_functions: Option<StatementsFunctions>,
> ```

how difficult would it be to just insert into the annotations structure?
this would add no dependencies here.



_Code quote:_
```XML
    pub statements_functions: Option<StatementsFunctions>,
```

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5325)* status: 1 of 23 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/debug_info.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5325#-NtqTXqpC5MEp64LdB86:-NtqscBG3dVelCbTW1rD:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/5689c4fe5798864bdce98282d6abe4bbd469ba5e/crates/cairo-lang-sierra/src/debug_info.rs#L40)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

how difficult would it be to just insert into the annotations structure?
this would add no dependencies here.
</blockquote></details>

Done

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 7 of 22 files at r1, 16 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5325)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5325)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-compiler/src/lib.rs` line 38 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5325#-NtrDCSR4iociEIsceeT:-NtrDCSR4iociEIsceeU:bswvtpg) ([raw file](https://github.com/starkware-libs/cairo/blob/ff9ca18bdec8107a06893132d363682cff0938f9/crates/cairo-lang-compiler/src/lib.rs#L38)):*
> ```XML
>     /// Adds mappings used by [cairo-profiler](https://github.com/software-mansion/cairo-profiler)
>     /// to debug info annotations.
>     pub add_cairo_profiler_annotations: bool,
> ```

Decided to make it configurable so it doesn't slow down the compiler
___
*[`crates/cairo-lang-starknet/src/test_utils.rs` line 85 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5325#-NtrE17H9rPqd1gQ0RmD:-NtrE17H9rPqd1gQ0RmE:b-e2773t) ([raw file](https://github.com/starkware-libs/cairo/blob/ff9ca18bdec8107a06893132d363682cff0938f9/crates/cairo-lang-starknet/src/test_utils.rs#L85)):*
> ```XML
>             allowed_libfuncs_list_name: Some(BUILTIN_ALL_LIBFUNCS_LIST.to_string()),
>             diagnostics_reporter,
>             add_cairo_profiler_annotations: true,
> ```

Here for testing purposes

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5325)* status: all files reviewed, 4 unresolved discussions (waiting on @piotmag769)

___
*[`crates/cairo-lang-sierra/src/debug_info.rs` line 83 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5325#-NttUm003XEsaYnwZDA5:-NttUm003XEsaYnwZDA6:b-k1e9vy) ([raw file](https://github.com/starkware-libs/cairo/blob/ff9ca18bdec8107a06893132d363682cff0938f9/crates/cairo-lang-sierra/src/debug_info.rs#L83)):*
> ```XML
>         } else {
>             Default::default()
>         };
> ```

add all of this externally - not here.



_Code quote:_
```XML
/// The mapping from sierra statement index to fully qualified Cairo path of the Cairo function
/// (if obtainable) which caused the statement to be generated.
///  Should be created using [`StatementsLocation::extract_statements_functions`].
#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub struct StatementsFunctions {
    pub statements_to_functions_map: HashMap<StatementIdx, Option<String>>,
}

impl DebugInfo {
    /// Extracts the existing debug info from a program.
    pub fn extract(program: &Program, statements_functions: Option<StatementsFunctions>) -> Self {
        let annotations = if let Some(sf) = statements_functions {
            let mapping = serde_json::to_value(sf.statements_to_functions_map).unwrap();
            OrderedHashMap::from([(
                "github.com/software-mansion/cairo-profiler".to_string(),
                serde_json::Value::from_iter([("statements_functions", mapping)]),
            )])
        } else {
            Default::default()
        };
```
___
*[`crates/cairo-lang-sierra-generator/src/program_generator.rs` line 336 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5325#-NttV6J42SdudRS12sTP:-NttV6J42SdudRS12sTQ:b-t1gw2c) ([raw file](https://github.com/starkware-libs/cairo/blob/ff9ca18bdec8107a06893132d363682cff0938f9/crates/cairo-lang-sierra-generator/src/program_generator.rs#L336)):*
> ```XML
>     db: &dyn SierraGenGroup,
>     requested_crate_ids: Vec<CrateId>,
>     add_cairo_profiler_annotations: bool,
> ```

probably - since this is not directly profiler related



_Suggestion:_
```XML
    add_location_annotations: bool,
```
___
*[`crates/cairo-lang-sierra-generator/src/statements_locations.rs` line 152 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5325#-NttVGlZDJHDwhxnWReM:-NttVGlZDJHDwhxnWReN:bb7f2bf) ([raw file](https://github.com/starkware-libs/cairo/blob/ff9ca18bdec8107a06893132d363682cff0938f9/crates/cairo-lang-sierra-generator/src/statements_locations.rs#L152)):*
> ```XML
>     }
> 
>     pub fn extract_statements_functions(&self, db: &dyn DefsGroup) -> StatementsFunctions {
> ```

doc.
___
*[`crates/cairo-lang-starknet/src/test_utils.rs` line 85 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5325#-NtrE17H9rPqd1gQ0RmD:-NttVX4JBOE3XtPsps4P:b-6j9i8) ([raw file](https://github.com/starkware-libs/cairo/blob/ff9ca18bdec8107a06893132d363682cff0938f9/crates/cairo-lang-starknet/src/test_utils.rs#L85)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Here for testing purposes
</blockquote></details>

make it false - as i don't want this data for the starknet tests.
you should do a specific test for it somewhere else.

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5325)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/debug_info.rs` line 83 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5325#-NttUm003XEsaYnwZDA5:-Ntu9pE5AXTmfwodAd0S:beutya6) ([raw file](https://github.com/starkware-libs/cairo/blob/ff9ca18bdec8107a06893132d363682cff0938f9/crates/cairo-lang-sierra/src/debug_info.rs#L83)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add all of this externally - not here.
</blockquote></details>

You mean in the other function? Done.
___
*[`crates/cairo-lang-sierra-generator/src/program_generator.rs` line 336 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5325#-NttV6J42SdudRS12sTP:-Ntu8qUxBKM4YzoTh102:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ff9ca18bdec8107a06893132d363682cff0938f9/crates/cairo-lang-sierra-generator/src/program_generator.rs#L336)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

probably - since this is not directly profiler related
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/statements_locations.rs` line 152 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5325#-NttVGlZDJHDwhxnWReM:-Ntu9CVJ5Pc16RWdC2Da:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ff9ca18bdec8107a06893132d363682cff0938f9/crates/cairo-lang-sierra-generator/src/statements_locations.rs#L152)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/test_utils.rs` line 85 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5325#-NtrE17H9rPqd1gQ0RmD:-Ntu9MIH-tC7tiKEOSSD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ff9ca18bdec8107a06893132d363682cff0938f9/crates/cairo-lang-starknet/src/test_utils.rs#L85)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

make it false - as i don't want this data for the starknet tests.
you should do a specific test for it somewhere else.
</blockquote></details>

Done.

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 22 of 22 files at r4, 14 of 14 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5325)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5325)* status: all files reviewed, 4 unresolved discussions (waiting on @piotmag769)

___
*[`crates/cairo-lang-sierra/src/debug_info.rs` line 83 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5325#-NttUm003XEsaYnwZDA5:-NtuSoIO6NyBD_-VzOq-:b80terf) ([raw file](https://github.com/starkware-libs/cairo/blob/ff9ca18bdec8107a06893132d363682cff0938f9/crates/cairo-lang-sierra/src/debug_info.rs#L83)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

You mean in the other function? Done.
</blockquote></details>

this shouldn't be in this crate at all.
move this to the place where it is actually added.

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5325)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/debug_info.rs` line 83 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5325#-NttUm003XEsaYnwZDA5:-Ntuc4lS5--_wZ-sU4hM:bku1cuw) ([raw file](https://github.com/starkware-libs/cairo/blob/ff9ca18bdec8107a06893132d363682cff0938f9/crates/cairo-lang-sierra/src/debug_info.rs#L83)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

or a completely different crate.
i expect to see no changes in the sierra crate.
</blockquote></details>

Created a different crate, done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 22 files at r4, 13 of 14 files at r5, 1 of 10 files at r6, 3 of 11 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5325)* status: all files reviewed, 3 unresolved discussions (waiting on @piotmag769)

___
*[`crates/cairo-lang-sierra-generator/src/program_generator.rs` line 291 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5325#-Ntur-WZDt8fNZ2q-oyJ:-Ntur-WZDt8fNZ2q-oyK:bv4wwwg) ([raw file](https://github.com/starkware-libs/cairo/blob/be540f9e4197933828d1796695479cc35c843389/crates/cairo-lang-sierra-generator/src/program_generator.rs#L291)):*
> ```XML
>         program,
>         debug_info: SierraProgramDebugInfo { statements_locations, statements_functions },
>     }))
> ```

can't you call this externally?
you already have the db and the extra results.



_Code quote:_
```XML
    let statements_locations = StatementsLocations::from_locations_vec(&statements_locations);
    let statements_functions = if add_location_annotations {
        Some(statements_locations.extract_statements_functions(db.upcast()))
    } else {
        None
    };

    Ok(Arc::new(SierraProgramWithDebug {
        program,
        debug_info: SierraProgramDebugInfo { statements_locations, statements_functions },
    }))
```

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5325)* status: all files reviewed, 2 unresolved discussions (waiting on @piotmag769)

___
*[`crates/cairo-lang-sierra-generator/src/program_generator.rs` line 291 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5325#-Ntur-WZDt8fNZ2q-oyJ:-NtvGZ7n9kSzBlUAETr9:b-ip8naq) ([raw file](https://github.com/starkware-libs/cairo/blob/be540f9e4197933828d1796695479cc35c843389/crates/cairo-lang-sierra-generator/src/program_generator.rs#L291)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Done
</blockquote></details>

You can remove it (and the bool) from here completely.

just call `extract_statement_functions` directly on the output if required.

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5325)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/program_generator.rs` line 291 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5325#-Ntur-WZDt8fNZ2q-oyJ:-NtvJaxM2Pau66XdmPZx:b-919zr8) ([raw file](https://github.com/starkware-libs/cairo/blob/be540f9e4197933828d1796695479cc35c843389/crates/cairo-lang-sierra-generator/src/program_generator.rs#L291)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

You can remove it (and the bool) from here completely.

just call `extract_statement_functions` directly on the output if required.
</blockquote></details>

Misunderstood you, done.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5325)* status: all files reviewed, 2 unresolved discussions (waiting on @piotmag769)

___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/generics` line 14 at r9](https://reviewable.io/reviews/starkware-libs/cairo/5325#-NtvWaLE9WVe5-F2iJKR:-NtvWaLE9WVe5-F2iJKS:b-l6hdjr) ([raw file](https://github.com/starkware-libs/cairo/blob/2a2f69b1ebb87d4fa77d894543d5e403626c1fe6/crates/cairo-lang-sierra-generator/src/function_generator_test_data/generics#L14)):*
> ```
> foo
> 
> //! > module_code
> ```

revert

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5325)* status: 28 of 37 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/program_generator.rs` line 291 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5325#-Ntur-WZDt8fNZ2q-oyJ:-NtvYGaw1fTIdDeLefjm:bpoakd7) ([raw file](https://github.com/starkware-libs/cairo/blob/be540f9e4197933828d1796695479cc35c843389/crates/cairo-lang-sierra-generator/src/program_generator.rs#L291)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove it completely.
`    pub statements_functions: Option<StatementsFunctions>,`
is not needed as part of the structure at all IIUC.
you can just have the db available, and extract `statements_functions` from `statements_functions` and strait into annotations.
</blockquote></details>

Forgot it is not necessary here as it is not the debug info that is used in `VersionedProgram`
___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/generics` line 14 at r9](https://reviewable.io/reviews/starkware-libs/cairo/5325#-NtvWaLE9WVe5-F2iJKR:-NtvZFFYA9Oy93Hq7EFz:b-48tem2) ([raw file](https://github.com/starkware-libs/cairo/blob/2a2f69b1ebb87d4fa77d894543d5e403626c1fe6/crates/cairo-lang-sierra-generator/src/function_generator_test_data/generics#L14)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

revert
</blockquote></details>

This was actually generated by running `CAIRO_FIX_TESTS=1 cargo test`

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 9 of 9 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5325)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 5 of 9 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5325#-:-NtvyR1w2FLM1swVH4p8:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @piotmag769)

___
*[`crates/cairo-lang-sierra-generator/src/statements_functions.rs` line 23 at r10](https://reviewable.io/reviews/starkware-libs/cairo/5325#-Ntvyf2CEnOYDYUFaj6Z:-Ntvyf2CEnOYDYUFaj6_:bp6hzkj) ([raw file](https://github.com/starkware-libs/cairo/blob/24c4226440895e436ebb5f916c766909450c21b0/crates/cairo-lang-sierra-generator/src/statements_functions.rs#L23)):*
> ```XML
>             serde_json::Value::from_iter([("statements_functions", mapping)]),
>         )])
>     }
> ```

make the function add instead - in case there are other annotations.



_Code quote:_
```XML
impl From<StatementsFunctions> for Annotations {
    fn from(value: StatementsFunctions) -> Self {
        let mapping = serde_json::to_value(value.statements_to_functions_map).unwrap();
        OrderedHashMap::from([(
            "github.com/software-mansion/cairo-profiler".to_string(),
            serde_json::Value::from_iter([("statements_functions", mapping)]),
        )])
    }
```

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5325)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/statements_functions.rs` line 23 at r10](https://reviewable.io/reviews/starkware-libs/cairo/5325#-Ntvyf2CEnOYDYUFaj6Z:-NtvzU-N9ayDm9SYSiOP:b-7hzvpi) ([raw file](https://github.com/starkware-libs/cairo/blob/24c4226440895e436ebb5f916c766909450c21b0/crates/cairo-lang-sierra-generator/src/statements_functions.rs#L23)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

make the function add instead - in case there are other annotations.
</blockquote></details>

The adding is done in `ContractClass::new`, this one is a cast

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 11 files at r7, 1 of 6 files at r9, 1 of 9 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5325#-:-Ntw6lZBDBzvtpFav6Hb:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @piotmag769)

**Review by piotmag769 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5325#-:-NtzL3u4AwYJyVca1b3T:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @piotmag769)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5325)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @piotmag769)

**Pull request merged**
