### PR TITLE
Added option to setup the amount of gas for test.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:5ff87523

---

**Stack**:
- #1531
- #1528
- #1526 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/runner/src/lib.rs` line 221 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1526#-NKMh4rlDqVGnRW-__Id:-NKMh4rlDqVGnRW-__Ie:bx1qr90) ([raw file](https://github.com/starkware-libs/cairo/blob/b8f93fee13bf6cfd315b080af27d36db69639cac/crates/runner/src/lib.rs#L221)):*
> ```XML
>             } else if ty == &"GasBuiltin".into() {
>                 if let Some(available_gas) = available_gas {
>                     // TODO(lior): Handle the other token types.
> ```

What happened to this TODO?



_Code quote:_
```XML
 // TODO(lior): Handle the other token types
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/runner/src/lib.rs` line 221 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1526#-NKMh4rlDqVGnRW-__Id:-NKMhGEG7Im3CAXmn1NJ:b-xuczta) ([raw file](https://github.com/starkware-libs/cairo/blob/b8f93fee13bf6cfd315b080af27d36db69639cac/crates/runner/src/lib.rs#L221)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

What happened to this TODO?
</blockquote></details>

nvm, found it :)



_Code quote:_
```XML
        func: &Function,
        available_gas: Option<usize>,
    ) -> Result<usize, RunnerError> {
```

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1526#-:-NKMi0GO9nYl9frYrbfz:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/runner/src/lib.rs` line 254 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1526#-NKMhetU0OTrqWNgqyFM:-NKMhetU0OTrqWNgqyFN:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2dd3bbeb46aa34809f37ca19499e0931dde57713/crates/runner/src/lib.rs#L254)):*
> ```XML
>     }
> 
>     /// Returns the initial value for the gas counter.
> ```





_Suggestion:_
```XML
/// Returns the initial value for the gas counter.
/// If available_gas is None returns 0.
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1526)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @ilyalesokhin-starkware)

___
*[`crates/runner/src/lib.rs` line 221 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1526#-NKMh4rlDqVGnRW-__Id:-NKMj9E72QxjJs42kNvz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e5697ed5a574b95f770e19f401fd1047203945b2/crates/runner/src/lib.rs#L221)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

nvm, found it :)
</blockquote></details>

Done.
___
*[`crates/runner/src/lib.rs` line 254 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1526#-NKMhetU0OTrqWNgqyFM:-NKMjDuO2VmmLhNn--yB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2dd3bbeb46aa34809f37ca19499e0931dde57713/crates/runner/src/lib.rs#L254)):*
> ```XML
>     }
> 
>     /// Returns the initial value for the gas counter.
> ```

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1526#-:-NKMwTL3B0tzqBpgXoV3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
