### PR TITLE
Remove renaming optimization.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2133)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 7 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2133)* status: 7 of 18 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware, @liorgold2, and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2133#-NOItkwL4rzbxBUBsvwY:-NOItkwL4rzbxBUBsvwZ:b-fat1ao) (no related file):*
Why did this change sierra code?

___
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 454 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2133#-NOFgDAp5vb3BtvQNGX5:-NOIsSP45XJ41yKdcAWd:bici8ot) ([raw file](https://github.com/starkware-libs/cairo/blob/aa5bba7ff485d7601e63f077aa940bf32950a781/crates/cairo-lang-lowering/src/inline/mod.rs#L454)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Do we want to remove this optimization?

The optimization is a bit ugly and it loses source variable locations on the parameters of the inlined variable.
but we shouldn't get errors at this point and it results in nicer lowering code.

wdyt?
</blockquote></details>

If we want it as a different stage later it would be a bit more sensible to me, having a nicer lowered representation is nice, but should not make us have more confusing code in the earlier stage.
If we want to remove block interdependency, we should merge them completely, but that's definitely a different stage.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2133)* status: 0 of 31 files reviewed, 1 unresolved discussion (waiting on @liorgold2, @orizi, @spapinistarkware, and @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2133#-NOItkwL4rzbxBUBsvwY:-NOe9_PfC9GNxTg2RKBL:b-4rfzie) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Why did this change sierra code?
</blockquote></details>

looks like the code changes are fixed now :)

___

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 31 of 31 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2133#-:-NOeCFrd14Kjyz6ztpuE:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2, @spapinistarkware, and @yuvalsw)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 31 of 31 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2133)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2, @spapinistarkware, and @yuvalsw)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2133)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2, @spapinistarkware, and @yuvalsw)

**Pull request merged**
