### PR TITLE
Removed internal trait for each storage member

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4043)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4043)* status: 0 of 17 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`corelib/src/starknet.cairo` line 88 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4043#-Ne1DyCq3JQgbOJnLMyh:-Ne1DyCq3JQgbOJnLMyi:bqoynqe) ([raw file](https://github.com/starkware-libs/cairo/blob/aceb58cfc2558a23b7feceecd4a383c6d7249ae5/corelib/src/starknet.cairo#L88)):*
> ```Cairo
> 
> /// Trait for any contract storage member.
> trait InternalContractMemberStateTrait<TContractMemberState, TValue> {
> ```

any reason for 2 different traits?

also - put this trait in a much more internal location.
___
*[`crates/cairo-lang-starknet/src/plugin/storage.rs` line 363 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4043#-Ne1EJbH4UxLCe7hNWVi:-Ne1EJbH4UxLCe7hNWVj:bs4jl9t) ([raw file](https://github.com/starkware-libs/cairo/blob/aceb58cfc2558a23b7feceecd4a383c6d7249ae5/crates/cairo-lang-starknet/src/plugin/storage.rs#L363)):*
> ```XML
>     format!(
>         "
>     impl $storage_member_name$_{member_state_name}Impl = \
> ```

any reason for the impl alias instead of direct outside impl?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4043)* status: 0 of 17 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/storage.rs` line 363 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4043#-Ne1m1Jw9T62wBxJ94uG:-Ne1m1Jw9T62wBxJ94uH:b-xy3tzc) ([raw file](https://github.com/starkware-libs/cairo/blob/aceb58cfc2558a23b7feceecd4a383c6d7249ae5/crates/cairo-lang-starknet/src/plugin/storage.rs#L363)):*
> ```XML
>     format!(
>         "
>     impl $storage_member_name$_{member_state_name}Impl = \
> ```

also - the outside trait was not internal - so we need to add a rename there to not break existing contracts code.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4043)* status: 0 of 18 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`corelib/src/starknet.cairo` line 88 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4043#-Ne1DyCq3JQgbOJnLMyh:-Ne2BqvEErf97KEeX0yU:brqfwy3) ([raw file](https://github.com/starkware-libs/cairo/blob/aceb58cfc2558a23b7feceecd4a383c6d7249ae5/corelib/src/starknet.cairo#L88)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

any reason for 2 different traits?

also - put this trait in a much more internal location.
</blockquote></details>

Removed, added one for mappings.
Done.
___
*[`crates/cairo-lang-starknet/src/plugin/storage.rs` line 363 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4043#-Ne1EJbH4UxLCe7hNWVi:-Ne29bGDDVGBRGg6nJg2:b-z116yq) ([raw file](https://github.com/starkware-libs/cairo/blob/aceb58cfc2558a23b7feceecd4a383c6d7249ae5/crates/cairo-lang-starknet/src/plugin/storage.rs#L363)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

any reason for the impl alias instead of direct outside impl?
</blockquote></details>

I moved it out but then found out a problem (so reverted) - we look for impls near the definition of the struct. If I move it out of the module, the contract writer needs to add an explicit use when they have a component.
___
*[`crates/cairo-lang-starknet/src/plugin/storage.rs` line 363 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4043#-Ne1m1Jw9T62wBxJ94uG:-Ne3-Ef5BcHb6bgeBHbM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/aceb58cfc2558a23b7feceecd4a383c6d7249ae5/crates/cairo-lang-starknet/src/plugin/storage.rs#L363)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

also - the outside trait was not internal - so we need to add a rename there to not break existing contracts code.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 17 files at r1, 17 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4043)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @yuvalsw)

___
*[`corelib/src/starknet/storage.cairo` line 4 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4043#-Ne3iuE64duZt2cC9QzQ:-Ne3iuE64duZt2cC9QzR:b-rgwm7s) ([raw file](https://github.com/starkware-libs/cairo/blob/0a307fe3505cbf983fa74b7caea4818b566965af/corelib/src/starknet/storage.cairo#L4)):*
> ```Cairo
> trait StorageMemberStateTrait<TMemberState, TValue> {
>     fn address(self: @TMemberState) -> starknet::StorageBaseAddress;
>     fn read(self: @TMemberState) -> TValue;
> ```

maybe we can have a trait just for address - and make read and write at an extension trait+impl?
(as these always have the same impl)
___
*[`crates/cairo-lang-starknet/src/plugin/storage.rs` line 363 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4043#-Ne1EJbH4UxLCe7hNWVi:-Ne3iQnTABl7NG1PlJl0:b68rkmk) ([raw file](https://github.com/starkware-libs/cairo/blob/aceb58cfc2558a23b7feceecd4a383c6d7249ae5/crates/cairo-lang-starknet/src/plugin/storage.rs#L363)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I moved it out but then found out a problem (so reverted) - we look for impls near the definition of the struct. If I move it out of the module, the contract writer needs to add an explicit use when they have a component.
</blockquote></details>

so why is the impl alias required? wouldn't the impl near the class suffice?

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4043)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`corelib/src/starknet/storage.cairo` line 4 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4043#-Ne3iuE64duZt2cC9QzQ:-Ne42lpt1xircOUN_h1t:b-xueb60) ([raw file](https://github.com/starkware-libs/cairo/blob/0a307fe3505cbf983fa74b7caea4818b566965af/corelib/src/starknet/storage.cairo#L4)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe we can have a trait just for address - and make read and write at an extension trait+impl?
(as these always have the same impl)
</blockquote></details>

What is the benefit?
Do you intend to write the extension trait+impl for each var or once? if for each - I don't see the benefit. If once - where?
___
*[`crates/cairo-lang-starknet/src/plugin/storage.rs` line 363 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4043#-Ne1EJbH4UxLCe7hNWVi:-Ne45lTV53EWKFazKFUo:b9mn9lr) ([raw file](https://github.com/starkware-libs/cairo/blob/aceb58cfc2558a23b7feceecd4a383c6d7249ae5/crates/cairo-lang-starknet/src/plugin/storage.rs#L363)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

so why is the impl alias required? wouldn't the impl near the class suffice?
</blockquote></details>

Great question. Turns out it's not. It probably was when I started this PR a long ago.
It did help avoid the use from a component to the new traits in core/starknet as it found them automatically. But I now added the use instead.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 25 of 25 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4043)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`corelib/src/starknet/storage.cairo` line 4 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4043#-Ne3iuE64duZt2cC9QzQ:-Ne4NzeQ8IsJU8z9aQrt:b-wsn5a5) ([raw file](https://github.com/starkware-libs/cairo/blob/0a307fe3505cbf983fa74b7caea4818b566965af/corelib/src/starknet/storage.cairo#L4)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

What is the benefit?
Do you intend to write the extension trait+impl for each var or once? if for each - I don't see the benefit. If once - where?
</blockquote></details>

the benefit - removes the code duplication for the final reads and writes, as it is done with calling `address()` + `Store` implementation always in any case (less generated code - better diags generally)
___
*[`crates/cairo-lang-starknet/test_data/erc20.cairo` line 170 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4043#-Ne4OvKF8LdovNRBjSU_:-Ne4OvKF8LdovNRBjSUa:bofx8qw) ([raw file](https://github.com/starkware-libs/cairo/blob/d3d9a6d2f575606f9ceb12a0cf2c3bdc9c7e2649/crates/cairo-lang-starknet/test_data/erc20.cairo#L170)):*
> ```Cairo
>             ref self: ContractState, owner: ContractAddress, spender: ContractAddress, amount: u256
>         ) {
>             let current_allowance: u256 = self.allowances.read((owner, spender));
> ```

this is a must now?

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4043)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`corelib/src/starknet/storage.cairo` line 4 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4043#-Ne3iuE64duZt2cC9QzQ:-Ne4eW1f7BCuWLjJ2tmb:b1ni932) ([raw file](https://github.com/starkware-libs/cairo/blob/0a307fe3505cbf983fa74b7caea4818b566965af/corelib/src/starknet/storage.cairo#L4)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the benefit - removes the code duplication for the final reads and writes, as it is done with calling `address()` + `Store` implementation always in any case (less generated code - better diags generally)
</blockquote></details>

We probably need associated impls for that. Otherwise there is no way to enforce the extension trait to be implemented only with the correct value type.
___
*[`crates/cairo-lang-starknet/test_data/erc20.cairo` line 170 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4043#-Ne4OvKF8LdovNRBjSU_:-Ne4eix-05xQKcy8oknj:b-4d99cf) ([raw file](https://github.com/starkware-libs/cairo/blob/d3d9a6d2f575606f9ceb12a0cf2c3bdc9c7e2649/crates/cairo-lang-starknet/test_data/erc20.cairo#L170)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is a must now?
</blockquote></details>

unfortunately.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4043)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`corelib/src/starknet/storage.cairo` line 4 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4043#-Ne3iuE64duZt2cC9QzQ:-Ne4lkhw6m4v7PanlKLQ:b1bp80c) ([raw file](https://github.com/starkware-libs/cairo/blob/0a307fe3505cbf983fa74b7caea4818b566965af/corelib/src/starknet/storage.cairo#L4)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

We probably need associated impls for that. Otherwise there is no way to enforce the extension trait to be implemented only with the correct value type.
</blockquote></details>

Thinking about it again, maybe it's ok, and we just use it with the correct generic args from the generated code (with impl alias).

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4043)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/cairo-lang-starknet/test_data/erc20.cairo` line 170 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4043#-Ne4OvKF8LdovNRBjSU_:-Ne4yAbfCnV7_BgGgmgI:b-p2pm49) ([raw file](https://github.com/starkware-libs/cairo/blob/d3d9a6d2f575606f9ceb12a0cf2c3bdc9c7e2649/crates/cairo-lang-starknet/test_data/erc20.cairo#L170)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

unfortunately.
</blockquote></details>

So this is an additional breakage

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 33 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4043)* status: 3 of 35 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`corelib/src/starknet/storage.cairo` line 14 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4043#-NeCROlv8aUi_PZb3Smm:-NeCROlw6gq_E4DewT5P:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9d5e46a3b13fc9a057fbef75d1b43f431f21d863/corelib/src/starknet/storage.cairo#L14)):*
> ```Cairo
>     TMemberState,
>     TValue,
>     +StorageMemberAddressTrait<TMemberState, TValue>,
> ```





_Suggestion:_
```Cairo
/// Trait for getting the address of any contract/component storage member.
trait StorageMemberAddressTrait<TMemberState, TValue> {
    fn address(self: @TMemberState) -> starknet::StorageBaseAddress nopanic;
}

/// Trait for accessing any contract/component storage member.
trait StorageMemberAccessTrait<TMemberState, TValue> {
    fn read(self: @TMemberState) -> TValue;
    fn write(ref self: TMemberState, value: TValue);
}

/// Implementation of StorageMemberAccessTrait for types that implement StorageMemberAddressTrait.
impl StorageMemberAccessImpl<
    TMemberState,
    TValue,
    +StorageMemberAddressTrait<TMemberState, TValue>,
```
___
*[`corelib/src/starknet/storage.cairo` line 46 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4043#-NeCRbtkEVPFR9IBo0n9:-NeCRbtkEVPFR9IBo0nA:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9d5e46a3b13fc9a057fbef75d1b43f431f21d863/corelib/src/starknet/storage.cairo#L46)):*
> ```Cairo
> impl StorageMapMemberAccessImpl<
>     TMemberState,
>     TKey,
> ```





_Suggestion:_
```Cairo
}

/// Trait for getting the address of any contract/component mapping storage member.
trait StorageMapMemberAddressTrait<TMemberState, TKey, TValue> {
    fn address(self: @TMemberState, key: TKey) -> starknet::StorageBaseAddress;
}

/// Trait for accessing any contract/component storage member.
trait StorageMapMemberAccessTrait<TMemberState, TKey, TValue> {
    fn read(self: @TMemberState, key: TKey) -> TValue;
    fn write(ref self: TMemberState, key: TKey, value: TValue);
}

/// Implementation of StorageMapMemberAccessTrait for types that implement
/// StorageMapMemberAddressTrait.
impl StorageMapMemberAccessImpl<
    TMemberState,
    TKey,
```
___
*[`corelib/src/starknet/storage.cairo` line 73 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4043#-NeCT2XHDcMXyXz3lHi6:-NeCT2XHDcMXyXz3lHi7:be4b7ep) ([raw file](https://github.com/starkware-libs/cairo/blob/9d5e46a3b13fc9a057fbef75d1b43f431f21d863/corelib/src/starknet/storage.cairo#L73)):*
> ```Cairo
> // of the old trait.
> mod old {
>     trait StorageMemberStateTrait<TMemberState, TValue> {
> ```

wouldn't this cause a collision in the case of usage. 
___
*[`corelib/src/starknet/storage.cairo` line 73 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4043#-NeCU1kC1IMA925NoYbE:-NeCU1kC1IMA925NoYbF:bikl7ds) ([raw file](https://github.com/starkware-libs/cairo/blob/9d5e46a3b13fc9a057fbef75d1b43f431f21d863/corelib/src/starknet/storage.cairo#L73)):*
> ```Cairo
> // of the old trait.
> mod old {
>     trait StorageMemberStateTrait<TMemberState, TValue> {
> ```

also - maybe add `Legacy` to this trait name as it is only for legacy mapping.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4043)* status: 3 of 35 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`corelib/src/starknet/storage.cairo` line 14 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4043#-NeCROlv8aUi_PZb3Smm:-NeCfQOI8l5oM0r31Nmh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9d5e46a3b13fc9a057fbef75d1b43f431f21d863/corelib/src/starknet/storage.cairo#L14)):*
> ```Cairo
>     TMemberState,
>     TValue,
>     +StorageMemberAddressTrait<TMemberState, TValue>,
> ```

Done.
___
*[`corelib/src/starknet/storage.cairo` line 46 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4043#-NeCRbtkEVPFR9IBo0n9:-NeCfQ-PEVHzhSgIyNV5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9d5e46a3b13fc9a057fbef75d1b43f431f21d863/corelib/src/starknet/storage.cairo#L46)):*
> ```Cairo
> impl StorageMapMemberAccessImpl<
>     TMemberState,
>     TKey,
> ```

Done.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4043)* status: 2 of 35 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`corelib/src/starknet/storage.cairo` line 73 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4043#-NeCT2XHDcMXyXz3lHi6:-NeCfe475XITV1cDCgmd:bs00mof) ([raw file](https://github.com/starkware-libs/cairo/blob/9d5e46a3b13fc9a057fbef75d1b43f431f21d863/corelib/src/starknet/storage.cairo#L73)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

wouldn't this cause a collision in the case of usage.
</blockquote></details>

No, this is why it uses `state` and not `self` :)
___
*[`corelib/src/starknet/storage.cairo` line 73 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4043#-NeCU1kC1IMA925NoYbE:-NeCgXs7A5zjQ-FJNtNF:b-vt9te1) ([raw file](https://github.com/starkware-libs/cairo/blob/9d5e46a3b13fc9a057fbef75d1b43f431f21d863/corelib/src/starknet/storage.cairo#L73)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

also - maybe add `Legacy` to this trait name as it is only for legacy mapping.
</blockquote></details>

removed hash generic param

**Review by orizi — APPROVED** [review]
> Reviewed 27 of 27 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4043)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4043)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/test_data/erc20.cairo` line 170 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4043#-Ne4OvKF8LdovNRBjSU_:-NeIguyE9cyduv6ChCgI:bjf8yqb) ([raw file](https://github.com/starkware-libs/cairo/blob/d3d9a6d2f575606f9ceb12a0cf2c3bdc9c7e2649/crates/cairo-lang-starknet/test_data/erc20.cairo#L170)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

So this is an additional breakage
</blockquote></details>

Fixed - no breakage.

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4043)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
