### PR TITLE
Add get_tx_info_syscall.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2201)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2201#-:-NOhr24x-NAZU5T7xhdo:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/getter.rs` line 175 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2201#-NOhrI4q-IMdbF4ZuxCD:-NOhrI4q-IMdbF4ZuxCE:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8cefb2ec1613319e8b127317cb02b22afcd41f7b/crates/cairo-lang-sierra/src/extensions/modules/starknet/getter.rs#L175)):*
> ```XML
>         context: &dyn SignatureSpecializationContext,
>     ) -> Result<ConcreteTypeId, SpecializationError> {
>         context.get_concrete_type(BoxType::id(), &[GenericArg::Type(get_tx_info_type(context)?)])
> ```





_Suggestion:_
```XML
context.get_wrapped_concrete_type(BoxType::id(), get_tx_info_type(context)?)
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2201)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/getter.rs` line 175 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2201#-NOhrI4q-IMdbF4ZuxCD:-NOhumCGB9gkOsV7si_7:b2llp2a) ([raw file](https://github.com/starkware-libs/cairo/blob/8cefb2ec1613319e8b127317cb02b22afcd41f7b/crates/cairo-lang-sierra/src/extensions/modules/starknet/getter.rs#L175)):*
> ```XML
>         context: &dyn SignatureSpecializationContext,
>     ) -> Result<ConcreteTypeId, SpecializationError> {
>         context.get_concrete_type(BoxType::id(), &[GenericArg::Type(get_tx_info_type(context)?)])
> ```

Done.
thanks.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2201)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2201)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2201)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
