### PR TITLE
LS: Properly set crate dependencies and their settings

### LINKED ISSUE #6444: LS: Insert correct dependency versions when updating crate roots
Implement this TODO: 

https://github.com/starkware-libs/cairo/pull/6411/files#diff-d59b333ba7670534994598079b394c9f46961c54088015804ed156691615818dR95

### PR DESCRIPTION
**Pull request by mkaput**
fixes #6444

---

**Stack**:
- #6470
- #6466
- #6451 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6451)

### CODE REVIEW

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6451)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6451#-O8LooduBeNvTMiQaTsC:-O8Loodv6vdbRHAVeXzq:b-m89dzc) (no related file):*
TODO: test this manually

___
___
*[`crates/cairo-lang-language-server/src/project/scarb.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6451#-O8LouZI7mFivhsn_7hO:-O8LouZI7mFivhsn_7hP:b-xo9e4v) ([raw file](https://github.com/starkware-libs/cairo/blob/bf56068ab469ef7a6f5cb74f979b57cb990f355e/crates/cairo-lang-language-server/src/project/scarb.rs#L96)):*
> ```XML
>                     .filter(|component_as_dependency| {
>                         direct_dependencies.contains(&*component_as_dependency.name) || {
>                             // This is a hacky way of accommodating integration test components,
> ```

@piotmag769 I guess (but I'm not sure): we also have to do this hack that Scarb does, correct?

**Review by piotmag769 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6451)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/src/project/crate_data.rs` line 46 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6451#-O8MEFaECn9JVjC_z8RD:-O8MEFaECn9JVjC_z8RE:b-3oqkrh) ([raw file](https://github.com/starkware-libs/cairo/blob/27a46fb94d6bf5aed43d048d0385ee3b4e2079b3/crates/cairo-lang-language-server/src/project/crate_data.rs#L46)):*
> ```XML
>         // Ensure only the `core` crate has no discriminator.
>         // Otherwise, bad things would happen inside the compiler.
>         assert!((self.name == CORELIB_CRATE_NAME) ^ self.discriminator.is_some());
> ```

I would add an error message for easier debugging on user support (I know it should never happen, but it's LS so)
___
*[`crates/cairo-lang-language-server/src/project/scarb.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6451#-O8LouZI7mFivhsn_7hO:-O8MKS-L4YDmKrFOVK1v:bxfjezw) ([raw file](https://github.com/starkware-libs/cairo/blob/bf56068ab469ef7a6f5cb74f979b57cb990f355e/crates/cairo-lang-language-server/src/project/scarb.rs#L96)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

@piotmag769 I guess (but I'm not sure): we also have to do this hack that Scarb does, correct?
</blockquote></details>

The hack in `find_component_package` was used (so far) only for looking for `CrateSettings::edition`, `CrateSettings::experimental_features` and `CrateSettings::version` (the last one was useless for integration tests, is not used for anything but corelib anyways). 

I guess now it is also used for finding direct dependencies (this is correct), not sure what happens here though and this `group_name == component.name` doesn't seems correct at all

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6451)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

**Review by piotmag769 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6451)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, and @mkaput)

___
*[`crates/cairo-lang-language-server/src/project/scarb.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6451#-O8LouZI7mFivhsn_7hO:-O8MllZKApI2mYjEfyzB:bjyw1f7) ([raw file](https://github.com/starkware-libs/cairo/blob/bf56068ab469ef7a6f5cb74f979b57cb990f355e/crates/cairo-lang-language-server/src/project/scarb.rs#L96)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

The hack in `find_component_package` was used (so far) only for looking for `CrateSettings::edition`, `CrateSettings::experimental_features` and `CrateSettings::version` (the last one was useless for integration tests, is not used for anything but corelib anyways). 

I guess now it is also used for finding direct dependencies (this is correct), not sure what happens here though and this `group_name == component.name` doesn't seems correct at all
</blockquote></details>

Discussed offline, unblocking,

**Review by piotmag769 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6451)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, and @mkaput)

**Review by piotmag769 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6451)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, and @mkaput)

___
*[`crates/cairo-lang-language-server/src/project/scarb.rs` line 98 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6451#-O8N47pgCuETK5DUTVNk:-O8N47pgCuETK5DUTVNl:b-4gxf3k) ([raw file](https://github.com/starkware-libs/cairo/blob/27a46fb94d6bf5aed43d048d0385ee3b4e2079b3/crates/cairo-lang-language-server/src/project/scarb.rs#L98)):*
> ```XML
>                             // This is a hacky way of accommodating integration test components,
>                             // which need to depend on the tested package.
>                             if let Some(package) = find_component_package(
> ```

Actually the hack with finding package should not be here now that I think about it: it is only useful for the any integration test "package" (in which case we don't care about the logic below - the integration test "package" is not the one we want to add conditionally). It shouldn't affect the logic though: it will make the package pass the filter and add itself to the dependencies, so it should be fine

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6451)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/project/crate_data.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6451#-O8MUq7S3BWc7C7LAPW9:-O8ffDG03kZtyXM08c_4:b-hvcyak) ([raw file](https://github.com/starkware-libs/cairo/blob/27a46fb94d6bf5aed43d048d0385ee3b4e2079b3/crates/cairo-lang-language-server/src/project/crate_data.rs#L24)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can you add to the doc the difference between this and the versoin?
(do note - version is only included in `settings`)
</blockquote></details>

Done, but not here: https://github.com/starkware-libs/cairo/pull/6466
___
*[`crates/cairo-lang-language-server/src/project/crate_data.rs` line 46 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6451#-O8MEFaECn9JVjC_z8RD:-O8fRE2PAxcsdFWh7kC9:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/27a46fb94d6bf5aed43d048d0385ee3b4e2079b3/crates/cairo-lang-language-server/src/project/crate_data.rs#L46)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

I would add an error message for easier debugging on user support (I know it should never happen, but it's LS so)
</blockquote></details>

Done

**Review by piotmag769 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6451#-:-O8g1tz01lMksyA_OiIp:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, and @mkaput)

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6451)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6451#-O8LooduBeNvTMiQaTsC:-O8gFSLC3-IO0RCaBaAy:bkujytw) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

TODO: test this manually
</blockquote></details>

Tested and it works great!

___

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6451)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6451)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6451#-:-O8kaP8fEBHcte6k7Af1:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)

**Pull request merged**
