### PR TITLE
Don't print profiling section title when missing

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4990)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4990)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-runner/src/profiling.rs` line 262 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4990#-NpoCK9Y4eGj3Ldk9zVm:-NpoCK9Y4eGj3Ldk9zVn:b-lnon2c) ([raw file](https://github.com/starkware-libs/cairo/blob/663b8b13e03543483284bc8c7d8134abab246d13/crates/cairo-lang-runner/src/profiling.rs#L262)):*
> ```XML
>         } else {
>             None
>         };
> ```

consider:



_Suggestion:_
```XML
        let concrete_libfuncs_weights = params.process_by_concrete_libfunc.then(|| {
            let mut concrete_libfuncs_weights = OrderedHashMap::default();
            for (concrete_name, weight) in
                concrete_libfuncs.iter_sorted_by_key(|(concrete_name, weight)| {
                    (usize::MAX - **weight, (*concrete_name).clone())
                })
            {
                if *weight >= params.min_weight {
                    concrete_libfuncs_weights.insert(concrete_name.clone(), *weight);
                }
            }
            Some(concrete_libfuncs_weights)
        });
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4990)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/profiling.rs` line 262 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4990#-NpoCK9Y4eGj3Ldk9zVm:-NpoYb2FA3iH2RdhZ97Q:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/663b8b13e03543483284bc8c7d8134abab246d13/crates/cairo-lang-runner/src/profiling.rs#L262)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

consider:
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4990#-:-Npo_Sqd-xVgH9c-IVhC:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4990)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
