### PR TITLE
External impls

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3267)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3042** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3042" target="_blank">Graphite</a> 
    * **PR #3044** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3044" target="_blank">Graphite</a> 
      * **PR #3045** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3045" target="_blank">Graphite</a> 
        * **PR #3050** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3050" target="_blank">Graphite</a> 
          * **PR #3051** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3051" target="_blank">Graphite</a> 
            * **PR #3267** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3267" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/3267?utm_source=stack-comment).

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 11 of 33 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3267)* status: 11 of 33 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 72 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3267#-NWqp3Ed-BjATVTOjWdh:-NWqp3Ed-BjATVTOjWdi:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/ea156787109f7fdb2b0f1e24a7b77dd073f7c6a4/crates/cairo-lang-starknet/src/plugin/contract.rs#L72)):*
> ```XML
> 
> #[derive(Default)]
> struct ContractGenerationData {
> ```

doc
___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 333 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3267#-NWqp7s08S6UEqI0Ge22:-NWqp7s08S6UEqI0Ge23:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/ea156787109f7fdb2b0f1e24a7b77dd073f7c6a4/crates/cairo-lang-starknet/src/plugin/contract.rs#L333)):*
> ```XML
> }
> 
> fn handle_entry_point(
> ```

doc



_Code quote:_
```XML
fn handle_entry_point
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 16 of 33 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3267)* status: 27 of 33 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-starknet/test_data/account.sierra.json` line 2926 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3267#-NWqptFh9wQgBiSvjJl2:-NWqptFh9wQgBiSvjJl3:b7if2y2) ([raw file](https://github.com/starkware-libs/cairo/blob/d86c6e81e9cfbee79c1d9513a8f3a2a94622b7ce/crates/cairo-lang-starknet/test_data/account.sierra.json#L2926)):*
> ```JSON
>       "name": "account::account::Call",
>       "members": [
>         {
> ```

are we sure this is no longer required?

**Review by orizi — COMMENTED** [review]
> Reviewed 5 of 33 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3267)* status: 32 of 33 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3267)* status: 32 of 33 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 72 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3267#-NWqp3Ed-BjATVTOjWdh:-NWqqcpN6Tfa06BTZZ4P:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ea156787109f7fdb2b0f1e24a7b77dd073f7c6a4/crates/cairo-lang-starknet/src/plugin/contract.rs#L72)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 333 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3267#-NWqp7s08S6UEqI0Ge22:-NWqqjsxAMS-sjCRVM-e:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ea156787109f7fdb2b0f1e24a7b77dd073f7c6a4/crates/cairo-lang-starknet/src/plugin/contract.rs#L333)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/test_data/account.sierra.json` line 2926 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3267#-NWqptFh9wQgBiSvjJl2:-NWqqkme68fJi2jyyk95:b-tazs0c) ([raw file](https://github.com/starkware-libs/cairo/blob/d86c6e81e9cfbee79c1d9513a8f3a2a94622b7ce/crates/cairo-lang-starknet/test_data/account.sierra.json#L2926)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

are we sure this is no longer required?
</blockquote></details>

I assume stdlib types don't get generated? Not sure how this is decided. What do u suggest?

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 11 files at r4, 21 of 21 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3267#-:-NWr0i5z54iGoRiZMp_4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
