### PR TITLE
Orizi/replace class hash fail

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4157)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/ids.rs` line 144 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4157#-NfdbkKV-J_GFv7eKHKq:-NfdbkKW4MoXqeBPahg9:bxkon5h) ([raw file](https://github.com/starkware-libs/cairo/blob/7f4788dc70318c94ea1adcf42a34adc4b7518425/crates/cairo-lang-lowering/src/ids.rs#L144)):*
> ```XML
>         }
>     }
>     pub fn name(&self, db: &dyn LoweringGroup) -> SmolStr {
> ```

This should be cherry-picked in a separate PR, right?



_Code quote:_
```XML
 pub fn name(&self, db: &dyn LoweringGroup) -> SmolStr {
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1031 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4157#-Nfdc6x29ftk2dbeyswk:-Nfdc6x29ftk2dbeyswl:bya1blr) ([raw file](https://github.com/starkware-libs/cairo/blob/7f4788dc70318c94ea1adcf42a34adc4b7518425/crates/cairo-lang-runner/src/casm_run/mod.rs#L1031)):*
> ```XML
>     ) -> Result<SyscallResult, HintError> {
>         deduct_gas!(gas_counter, REPLACE_CLASS);
>         // Prepare runner for running the constructor.
> ```

Fix comment.



_Code quote:_
```XML
 // Prepare runner for running the constructor.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/inference/conform.rs` line 71 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4157#-NfdcJNt-eZcQpLRQymo:-NfdcJNt-eZcQpLRQymp:b-h4p570) ([raw file](https://github.com/starkware-libs/cairo/blob/7f4788dc70318c94ea1adcf42a34adc4b7518425/crates/cairo-lang-semantic/src/expr/inference/conform.rs#L71)):*
> ```XML
>         let ty0 = self.rewrite(ty0).no_err();
>         let ty1 = self.rewrite(ty1).no_err();
>         if ty0 == never_ty(self.db) || ty0.is_missing(self.db) {
> ```

separate PR.



_Code quote:_
```XML
ty0.is_missing(self.db)
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4157)* status: 0 of 17 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1031 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4157#-Nfdc6x29ftk2dbeyswk:-NfdpLpX2QPgeS9knJ7F:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7f4788dc70318c94ea1adcf42a34adc4b7518425/crates/cairo-lang-runner/src/casm_run/mod.rs#L1031)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Fix comment.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/ids.rs` line 144 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4157#-NfdbkKV-J_GFv7eKHKq:-Nfdo_3TDCQ2ks1Sali9:bhgboyz) ([raw file](https://github.com/starkware-libs/cairo/blob/7f4788dc70318c94ea1adcf42a34adc4b7518425/crates/cairo-lang-lowering/src/ids.rs#L144)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

This should be cherry-picked in a separate PR, right?
</blockquote></details>

just bad git target - removed all extra commits.
___
*[`crates/cairo-lang-semantic/src/expr/inference/conform.rs` line 71 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4157#-NfdcJNt-eZcQpLRQymo:-Nfdoi5y9LtUSKgE6w9B:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7f4788dc70318c94ea1adcf42a34adc4b7518425/crates/cairo-lang-semantic/src/expr/inference/conform.rs#L71)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

separate PR.
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/cairo_level_tests/replace_class_test.cairo` line 74 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4157#-Nfdq1vIEW0Bpk4UVtzZ:-Nfdq1vIEW0Bpk4UVtz_:bm9yceb) ([raw file](https://github.com/starkware-libs/cairo/blob/704be399f24735282109988c5fb67c6e7025f85e/crates/cairo-lang-starknet/cairo_level_tests/replace_class_test.cairo#L74)):*
> ```Cairo
> #[test]
> #[available_gas(30000000)]
> #[should_panic(expected: ('CLASS_HASH_NOT_FOUND', 'ENTRYPOINT_FAILED'))]
> ```

Why two errors?



_Code quote:_
```Cairo
#[should_panic(expected: ('CLASS_HASH_NOT_FOUND', 'ENTRYPOINT_FAILED'))]
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 14 of 16 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4157)* status: 14 of 17 files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4157)* status: 14 of 17 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/replace_class_test.cairo` line 74 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4157#-Nfdq1vIEW0Bpk4UVtzZ:-NfduLHB74YA5I6UzSHu:b-ysuohm) ([raw file](https://github.com/starkware-libs/cairo/blob/704be399f24735282109988c5fb67c6e7025f85e/crates/cairo-lang-starknet/cairo_level_tests/replace_class_test.cairo#L74)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why two errors?
</blockquote></details>

because it failed during an entry point - theses are not 2 failures - this is the error stack.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r4, 1 of 16 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4157#-:-NfdvlhFBnWRRsshgGZv:bnfp4nl)* status: 16 of 17 files reviewed, all discussions resolved

**Pull request merged**
