### PR TITLE
Coupons: Add Sierra type for function::Coupon.

### PR DESCRIPTION
**Pull request by liorgold2**
**Stack**:
- #4573
- #4572 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4572)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4572)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-generator/src/program_generator.rs` line 175 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4572#-NlqhMrZAUjsDJ5hInWb:-NlqhMrZAUjsDJ5hInWc:bl00yrj) ([raw file](https://github.com/starkware-libs/cairo/blob/07893b2884dae1971db6b4efa2ff81b47322535f/crates/cairo-lang-sierra-generator/src/program_generator.rs#L175)):*
> ```XML
>     // TODO(lior): Coupons that are declared but never used, should be replaced with an empty
>     //   coupon. Otherwise, the coupon's function may be omitted from the program, resulting in an
>     //   invalid Sierra program.
> ```

if you are planning on Coupons to not be droppable - coupons won't be able to be declared but not used - so that issue won't happen.

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4572)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/program_generator.rs` line 175 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4572#-NlqhMrZAUjsDJ5hInWb:-Nlqmbn-CMqjvcR60e2b:b5j2b2q) ([raw file](https://github.com/starkware-libs/cairo/blob/07893b2884dae1971db6b4efa2ff81b47322535f/crates/cairo-lang-sierra-generator/src/program_generator.rs#L175)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

if you are planning on Coupons to not be droppable - coupons won't be able to be declared but not used - so that issue won't happen.
</blockquote></details>

You can get a refund on a coupon without using it. This will happen if we go with the `Array` suggestion we had in case the inner type is droppable.
Consider:
```
let x = foo::coupon_buy()
foo::coupon_refund(x)
```
in this case `foo` may not be in the output of the Sierra at all, so you'll get an invalid code.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4572#-:-NlqqZAq3Tf26Rc5e8AJ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4572)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
