### PR TITLE
LS: pull crate dependencies from scarb

### PR DESCRIPTION
**Pull request by piotmag769**

### CODE REVIEW

**Comment by maciektr** [comment]
*[`crates/cairo-lang-language-server/Cargo.toml` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6527#-OAI4suYB2SqC7slQEbX:-OAI7hS74T4_eedPhZH3:b-m3h19k) ([raw file](https://github.com/starkware-libs/cairo/blob/4cb31d70b5f67ca6a08c42a4fbe390af1dd3fa60/crates/cairo-lang-language-server/Cargo.toml#L37)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Releasing a metadata version can't work?
</blockquote></details>

It will be released today CC @piotmag769

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6527)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, and @mkaput)

___
*[`crates/cairo-lang-language-server/Cargo.toml` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6527#-OAI4suYB2SqC7slQEbX:-OAIQM_9Bc1ss90FMAXi:b-bw7w3m) ([raw file](https://github.com/starkware-libs/cairo/blob/4cb31d70b5f67ca6a08c42a4fbe390af1dd3fa60/crates/cairo-lang-language-server/Cargo.toml#L37)):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

It will be released today CC @piotmag769
</blockquote></details>

Will wait for the release then
___
*[`crates/cairo-lang-language-server/src/project/scarb.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6527#-OAIDLIs5Qk2tdIBKO_5:-OAIQLnh1aLR0wgskXFO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4cb31d70b5f67ca6a08c42a4fbe390af1dd3fa60/crates/cairo-lang-language-server/src/project/scarb.rs#L101)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I would rather fall back to error + no dependencies than panic here. Out of paranoia.
</blockquote></details>

Done.

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6527)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/Cargo.toml` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6527#-OAI4suYB2SqC7slQEbX:-OAMBje_652vATXcDT9Q:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4cb31d70b5f67ca6a08c42a4fbe390af1dd3fa60/crates/cairo-lang-language-server/Cargo.toml#L37)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Will wait for the release then
</blockquote></details>

Done.

**Review by piotmag769 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6527)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6527#-:-OAMLiGm7v-OIntVUGlG:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6527)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6527)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)

___
*[`crates/cairo-lang-language-server/Cargo.toml` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6527#-OAI4suYB2SqC7slQEbX:-OAMMsAF-rEak4z-Irtz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4cb31d70b5f67ca6a08c42a4fbe390af1dd3fa60/crates/cairo-lang-language-server/Cargo.toml#L37)):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

Why not just `1.13`? I don't think you need to pin fixes.
</blockquote></details>

Done.

**Review by mkaput — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6527)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)

**Pull request merged**
