### PR TITLE
Panic when a dependency is misconfigured.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 1290 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6858#-ODl-R6c0U8BgSyy_coI:-ODl-R6c0U8BgSyy_coJ:b-7kxrhc) ([raw file](https://github.com/starkware-libs/cairo/blob/9aede37dae87636aae1c4ae73860fe2121a51cfd/crates/cairo-lang-semantic/src/resolve/mod.rs#L1290)):*
> ```XML
>                     get_long_id(dep_crate_id),
>                     configs.keys().cloned().map(get_long_id).collect_vec()
>                 );
> ```

Invalid crate dependency: Real { name: "bounded_int2", discriminator: Some("bounded_int") }
Configured crates: [
    Real {
        name: "core",
        discriminator: None,
    },
    Real {
        name: "stwo_cairo_verifier",
        discriminator: Some(
            "stwo_cairo_verifier",
        ),
    },
    Real {
        name: "bounded_int2",
        discriminator: Some(
            "bounded_int2",
        ),
    },
]



_Code quote:_
```XML
                panic!(
                    "Invalid crate dependency: {:?}\nconfigured crates: {:#?}",
                    get_long_id(dep_crate_id),
                    configs.keys().cloned().map(get_long_id).collect_vec()
                );
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 1290 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6858#-ODl-R6c0U8BgSyy_coI:-ODl-UOi1VlyO8os4y9e:bbrsbso) ([raw file](https://github.com/starkware-libs/cairo/blob/9aede37dae87636aae1c4ae73860fe2121a51cfd/crates/cairo-lang-semantic/src/resolve/mod.rs#L1290)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Invalid crate dependency: Real { name: "bounded_int2", discriminator: Some("bounded_int") }
Configured crates: [
    Real {
        name: "core",
        discriminator: None,
    },
    Real {
        name: "stwo_cairo_verifier",
        discriminator: Some(
            "stwo_cairo_verifier",
        ),
    },
    Real {
        name: "bounded_int2",
        discriminator: Some(
            "bounded_int2",
        ),
    },
]
</blockquote></details>

here is an example:



_Code snippet:_
```XML
Invalid crate dependency: Real { name: "bounded_int2", discriminator: Some("bounded_int") }
Configured crates: [
    Real {
        name: "core",
        discriminator: None,
    },
    Real {
        name: "stwo_cairo_verifier",
        discriminator: Some(
            "stwo_cairo_verifier",
        ),
    },
    Real {
        name: "bounded_int2",
        discriminator: Some(
            "bounded_int2",
        ),
    },
]
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6858#-:-ODlM1gz1-m2fi58Ucw4:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6858)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 1289 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6858#-ODlM8h47aOtCSNIdLQu:-ODlM8h47aOtCSNIdLQv:b-dz9uw9) ([raw file](https://github.com/starkware-libs/cairo/blob/9aede37dae87636aae1c4ae73860fe2121a51cfd/crates/cairo-lang-semantic/src/resolve/mod.rs#L1289)):*
> ```XML
>                     "Invalid crate dependency: {:?}\nconfigured crates: {:#?}",
>                     get_long_id(dep_crate_id),
>                     configs.keys().cloned().map(get_long_id).collect_vec()
> ```

oh - we should probably just filter to the relevant crate without discriminator.



_Code quote:_
```XML
                    "Invalid crate dependency: {:?}\nconfigured crates: {:#?}",
                    get_long_id(dep_crate_id),
                    configs.keys().cloned().map(get_long_id).collect_vec()
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6858)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 1291 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6858#-ODlMLLU4lEDzkYXxxmB:-ODlMLLU4lEDzkYXxxmC:b-dz9uw9) ([raw file](https://github.com/starkware-libs/cairo/blob/9aede37dae87636aae1c4ae73860fe2121a51cfd/crates/cairo-lang-semantic/src/resolve/mod.rs#L1291)):*
> ```XML
>                     configs.keys().cloned().map(get_long_id).collect_vec()
>                 );
>             }
> ```

oh - we should probably just filter to the relevant crate without discriminator.



_Suggestion:_
```XML
                panic!(
                    "Invalid crate dependency `{ident}: got discriminator {:?}\nconfigured discriminators: {:#?}",
                    dep.discriminator,
                    configs.keys().cloned().map(|crate_id|crate_id.lookup_intern(self.db).discriminator).collect_vec()
                );
            }
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 1291 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6858#-ODlMLLU4lEDzkYXxxmB:-OE87wjN6ZCktn-4ByCB:b-c6jx6j) ([raw file](https://github.com/starkware-libs/cairo/blob/9aede37dae87636aae1c4ae73860fe2121a51cfd/crates/cairo-lang-semantic/src/resolve/mod.rs#L1291)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i mean ```.filter_map(|crate_id| {
   let long_id = crate_id.lookup_intern(self.db);
   (long_id.name == ident).and_then(long_id.discriminator)
})```
</blockquote></details>

The name could also be wrong.

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6858#-:-OEAFtPOENa7nyGS4GKN:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
