### PR TITLE
Added an extern function for requiring implicits usage.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #3723 ⬅
- #3715
- #3714
- #3727

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3723)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/internal.cairo` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3723#-N_nA8iH49ZD3dbfLfhh:-N_nA8iI9pBC2quOnBRR:b-970nnl) ([raw file](https://github.com/starkware-libs/cairo/blob/59fe8aa44e04cde870e8e3d664adb9a1c72292e7/corelib/src/internal.cairo#L2)):*
> ```Cairo
> extern fn revoke_ap_tracking() implicits() nopanic;
> extern fn require_implicit<Implicit>() implicits(Implicit) nopanic;
> ```

Document that it is removed during lowering, and that is no such libfunc.



_Code quote:_
```Cairo
extern fn require_implicit<Implicit>() implicits(Implicit) nopanic;
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/diagnostics` line 2833 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3723#-N_nAnsVDBHtPNzdxvBv:-N_nAnsVDBHtPNzdxvBw:b-yosfpk) ([raw file](https://github.com/starkware-libs/cairo/blob/59fe8aa44e04cde870e8e3d664adb9a1c72292e7/crates/cairo-lang-starknet/src/plugin/plugin_test_data/diagnostics#L2833)):*
> ```
>             gas::withdraw_gas().expect('Out of gas');
>             
>             if !array::SpanTrait::is_empty(data) {
> ```

use `assert`



_Code quote:_
```
if !array::SpanTrait::is_empty(data) {
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 11 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3723)* status: 11 of 30 files reviewed, 2 unresolved discussions (waiting on @orizi)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3723)* status: 12 of 30 files reviewed, 2 unresolved discussions (waiting on @orizi)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 11 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3723)* status: 23 of 30 files reviewed, 2 unresolved discussions (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3723)* status: 17 of 30 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/internal.cairo` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3723#-N_nA8iH49ZD3dbfLfhh:-N_nFTzR9CuLNUBPObEC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/59fe8aa44e04cde870e8e3d664adb9a1c72292e7/corelib/src/internal.cairo#L2)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Document that it is removed during lowering, and that is no such libfunc.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/diagnostics` line 2833 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3723#-N_nAnsVDBHtPNzdxvBv:-N_nFlVu-k_Qvx3RVsy_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/59fe8aa44e04cde870e8e3d664adb9a1c72292e7/crates/cairo-lang-starknet/src/plugin/plugin_test_data/diagnostics#L2833)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

use `assert`
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 30 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3723#-:-Na0KtK12ntRwvS_z9FB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3723)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
