### PR TITLE
Topological sort on lowering

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2290)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 107 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2290)* status: 2 of 107 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2290#-NPHUrXT1sqD4vs6ctdo:-NPHUrXT1sqD4vs6ctdp:bfeb8qy) ([raw file](https://github.com/starkware-libs/cairo/blob/19a3161377782cf7edc588150c42a7dcd5a9fbe7/crates/cairo-lang-lowering/src/db.rs#L23)):*
> ```XML
> use crate::optimizations::remappings::optimize_remappings;
> use crate::panic::lower_panics;
> use crate::topsort::topsort;
> ```

I'd rather have `topological_sort`.
but at the very least `topo_sort`.



_Code quote:_
```XML
use crate::topsort::topsort;
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 107 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2290)* status: 4 of 107 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/topsort.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2290#-NPHV2pO9ZKG6e8vDRRM:-NPHV2pO9ZKG6e8vDRRN:b-h6a58k) ([raw file](https://github.com/starkware-libs/cairo/blob/19a3161377782cf7edc588150c42a7dcd5a9fbe7/crates/cairo-lang-lowering/src/topsort.rs#L9)):*
> ```XML
> 
> /// Makes sure each block has an incoming fallthrough, by replacing one of the Goto's
> /// with a fallthrough.
> ```

update doc to include the sorting.



_Code quote:_
```XML
/// Makes sure each block has an incoming fallthrough, by replacing one of the Goto's
/// with a fallthrough.
```
___
*[`crates/cairo-lang-lowering/src/borrow_check/analysis.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2290#-NPHVLxZ5ALYd2iqlnLo:-NPHVLxZ5ALYd2iqlnLp:b-co0tyx) ([raw file](https://github.com/starkware-libs/cairo/blob/19a3161377782cf7edc588150c42a7dcd5a9fbe7/crates/cairo-lang-lowering/src/borrow_check/analysis.rs#L17)):*
> ```XML
> 
> /// Analyzer trait to implement for each specific analysis.
> #[allow(unused_variables)]
> ```

something new caused this?



_Code quote:_
```XML
#[allow(unused_variables)]
```
___
*[`crates/cairo-lang-lowering/src/borrow_check/analysis.rs` line 126 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2290#-NPHVIr_5QRhYb4batpD:-NPHVIr_5QRhYb4batpE:b-5g7sw2) ([raw file](https://github.com/starkware-libs/cairo/blob/19a3161377782cf7edc588150c42a7dcd5a9fbe7/crates/cairo-lang-lowering/src/borrow_check/analysis.rs#L126)):*
> ```XML
>                     let arm_infos = arms
>                         .iter()
>                         .rev()
> ```

please doc this - this is confusing.



_Code quote:_
```XML
                    let arm_infos = arms
                        .iter()
                        .rev()
                        .map(|(_, arm_block)| (*arm_block, self.get_block_info(*arm_block)))
                        .rev()
                        .collect_vec();
```

**Review by orizi — COMMENTED** [review]
> Reviewed 21 of 107 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2290)* status: 25 of 107 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2290)* status: 25 of 107 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-generator/src/block_generator_test_data/inline` line 39 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2290#-NPHWRee0ECBjdah3-WA:-NPHWRee0ECBjdah3-WB:b57l01u) ([raw file](https://github.com/starkware-libs/cairo/blob/19a3161377782cf7edc588150c42a7dcd5a9fbe7/crates/cairo-lang-sierra-generator/src/block_generator_test_data/inline#L39)):*
> ```
> felt_is_zero([2]) { fallthrough() label0([4]) }
> branch_align() -> ()
> PushValues() -> ()
> ```

can you explain this?



_Code quote:_
```
branch_align() -> ()
PushValues() -> ()
label2:
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2290)* status: 25 of 107 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-generator/src/block_generator_test_data/inline` line 39 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2290#-NPHWRee0ECBjdah3-WA:-NPHfF3q3f7s4wQt9WyH:brwjmkv) ([raw file](https://github.com/starkware-libs/cairo/blob/19a3161377782cf7edc588150c42a7dcd5a9fbe7/crates/cairo-lang-sierra-generator/src/block_generator_test_data/inline#L39)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

its because of the code that was removed from crates/cairo-lang-sierra-generator/src/block_generator.rs
</blockquote></details>

and it would be removed when we remove `non-merging-fallthroughs`.
got it.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/db.rs` line 187 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2290#-NPHgOD13nj64LcVqRQg:-NPHgOD28__ywsBFtOsQ:b-lyxhwk) ([raw file](https://github.com/starkware-libs/cairo/blob/19a3161377782cf7edc588150c42a7dcd5a9fbe7/crates/cairo-lang-lowering/src/db.rs#L187)):*
> ```XML
>     optimize_remappings(&mut lowered);
>     topsort(&mut lowered);
>     add_fallthroughs(&mut lowered);
> ```

note that this function  also does toplogical sort.



_Code quote:_
```XML
add_fallthroughs(&mut lowered);
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2290)* status: 25 of 107 files reviewed, 6 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/analysis.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2290#-NPHhHUiBDzBN3bHmBEf:-NPHhHUiBDzBN3bHmBEg:bvn8da8) ([raw file](https://github.com/starkware-libs/cairo/blob/19a3161377782cf7edc588150c42a7dcd5a9fbe7/crates/cairo-lang-lowering/src/borrow_check/analysis.rs#L116)):*
> ```XML
>     /// Otherwise, returns None.
>     fn get_info_from_next_split(&mut self, block_id: BlockId) -> Option<(usize, TAnalyzer::Info)> {
>         for (i, stmt) in self.lowered.blocks[block_id].statements.iter().enumerate() {
> ```

don't you need to check only the last statement?



_Code quote:_
```XML
 for (i, stmt) in self.lowered.blocks[block_id].statements.iter().enumerate() {
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2290)* status: 25 of 107 files reviewed, 7 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/topsort.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2290#-NPHhxXZCZq_0LsZmrYn:-NPHhxXZCZq_0LsZmrYo:b1tlm5n) ([raw file](https://github.com/starkware-libs/cairo/blob/19a3161377782cf7edc588150c42a7dcd5a9fbe7/crates/cairo-lang-lowering/src/topsort.rs#L22)):*
> ```XML
>         let mut ctx = analysis.analyzer;
> 
>         // Rebuild the blocks without unnecessary remappings.
> ```

is this correct? what are you doing to the remappings?



_Code quote:_
```XML
   // Rebuild the blocks without unnecessary remappings.
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2290)* status: 25 of 107 files reviewed, 8 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 681 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2290#-NPHiIvT2H9lNTkb7ox1:-NPHiIvT2H9lNTkb7ox2:b-snf2rx) ([raw file](https://github.com/starkware-libs/cairo/blob/19a3161377782cf7edc588150c42a7dcd5a9fbe7/crates/cairo-lang-lowering/src/lower/mod.rs#L681)):*
> ```XML
>     }));
> 
>     scope.finalize_after_merge(ctx, merged)
> ```

why is this in the same PR as the TOPO sort?
Can't you have a separate PR to remove the fallthroughs?



_Code quote:_
```XML
 scope.finalize_after_merge(ctx, merged)
```

**Review by orizi — COMMENTED** [review]
> Reviewed 82 of 107 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2290)* status: all files reviewed, 8 unresolved discussions (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2290)* status: all files reviewed, 8 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 187 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2290#-NPHgOD13nj64LcVqRQg:-NPHxNCuAfceSXYJ-p5R:b-6rkari) ([raw file](https://github.com/starkware-libs/cairo/blob/19a3161377782cf7edc588150c42a7dcd5a9fbe7/crates/cairo-lang-lowering/src/db.rs#L187)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

note that this function  also does toplogical sort.
</blockquote></details>

It doesn't. I checked.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2290)* status: all files reviewed, 8 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/borrow_check/analysis.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2290#-NPHVLxZ5ALYd2iqlnLo:-NPHxUUb6VwLNTl03cha:b-5vnmxw) ([raw file](https://github.com/starkware-libs/cairo/blob/19a3161377782cf7edc588150c42a7dcd5a9fbe7/crates/cairo-lang-lowering/src/borrow_check/analysis.rs#L17)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

something new caused this?
</blockquote></details>

Default empty impls
___
*[`crates/cairo-lang-lowering/src/borrow_check/analysis.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2290#-NPHhHUiBDzBN3bHmBEf:-NPHxZ7v4K-UH_FSjcQq:begd6cz) ([raw file](https://github.com/starkware-libs/cairo/blob/19a3161377782cf7edc588150c42a7dcd5a9fbe7/crates/cairo-lang-lowering/src/borrow_check/analysis.rs#L116)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

don't you need to check only the last statement?
</blockquote></details>

No, I need to pass through all. Besides, this code is general.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 681 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2290#-NPHiIvT2H9lNTkb7ox1:-NPHy7RfAANvEDmNvk4w:bwdepx) ([raw file](https://github.com/starkware-libs/cairo/blob/19a3161377782cf7edc588150c42a7dcd5a9fbe7/crates/cairo-lang-lowering/src/lower/mod.rs#L681)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why is this in the same PR as the TOPO sort?
Can't you have a separate PR to remove the fallthroughs?
</blockquote></details>

It didn't work when I didn't do this I think. The added fallthroughs weren't always correct.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/db.rs` line 187 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2290#-NPHgOD13nj64LcVqRQg:-NPI-gq8D9A830xj7ihz:bz2xsdl) ([raw file](https://github.com/starkware-libs/cairo/blob/19a3161377782cf7edc588150c42a7dcd5a9fbe7/crates/cairo-lang-lowering/src/db.rs#L187)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

It doesn't. I checked.
</blockquote></details>


If you write the block_ids to a vector you get a topological sort of the block.
https://github.com/starkware-libs/cairo/blob/ef493fcb3f64e68e132641e6833ce80c1890b29c/crates/cairo-lang-lowering/src/flow/mod.rs#L60

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2290)* status: all files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 187 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2290#-NPHgOD13nj64LcVqRQg:-NPI0HBG3R0Ci7dtttQ0:b-ein5ee) ([raw file](https://github.com/starkware-libs/cairo/blob/19a3161377782cf7edc588150c42a7dcd5a9fbe7/crates/cairo-lang-lowering/src/db.rs#L187)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>


If you write the block_ids to a vector you get a topological sort of the block.
https://github.com/starkware-libs/cairo/blob/ef493fcb3f64e68e132641e6833ce80c1890b29c/crates/cairo-lang-lowering/src/flow/mod.rs#L60
</blockquote></details>

You don't

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 107 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2290)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2290)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 187 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2290#-NPHgOD13nj64LcVqRQg:-NPI0SyfCCFR7issdg91:b-pwekm3) ([raw file](https://github.com/starkware-libs/cairo/blob/19a3161377782cf7edc588150c42a7dcd5a9fbe7/crates/cairo-lang-lowering/src/db.rs#L187)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

You don't
</blockquote></details>

Maybe you can explain f2f why you do, I didnt understand I guess

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2290)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2290)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 187 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2290#-NPHgOD13nj64LcVqRQg:-NPI0bYa5injn2ZFuM9D:bl5l8tx) ([raw file](https://github.com/starkware-libs/cairo/blob/19a3161377782cf7edc588150c42a7dcd5a9fbe7/crates/cairo-lang-lowering/src/db.rs#L187)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Maybe you can explain f2f why you do, I didnt understand I guess
</blockquote></details>

Also, I need to rename the blocks anyway, right?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/db.rs` line 187 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2290#-NPHgOD13nj64LcVqRQg:-NPI0igP8qaeYHInekv4:bb7sa0c) ([raw file](https://github.com/starkware-libs/cairo/blob/19a3161377782cf7edc588150c42a7dcd5a9fbe7/crates/cairo-lang-lowering/src/db.rs#L187)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Also, I need to rename the blocks anyway, right?
</blockquote></details>

yes.



_Code quote:_
```XML
   add_fallthroughs(&mut lowered);
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2290)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 187 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2290#-NPHgOD13nj64LcVqRQg:-NPI0nNA4U9kdKYB63ah:b-ufo723) ([raw file](https://github.com/starkware-libs/cairo/blob/19a3161377782cf7edc588150c42a7dcd5a9fbe7/crates/cairo-lang-lowering/src/db.rs#L187)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

yes.
</blockquote></details>

Is it posiible to remove my code now?

why are we doing topological sort twice?



_Code quote:_
```XML
add_fallthroughs(&mut lowered);
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2290)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by ilyalesokhin-starkware — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2290)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/test.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2290#-NPI1x0sEaDJrsWf-fZL:-NPI1x0sEaDJrsWf-fZM:bxsyaka) ([raw file](https://github.com/starkware-libs/cairo/blob/96cfda0d8b933ff0e3b90ed6a08f4225489721c1/crates/cairo-lang-lowering/src/inline/test.rs#L51)):*
> ```XML
> 
>     // TODO(ilya): Move 'add_fallthroughs' to a dedicated test.
>     add_fallthroughs(&mut after);
> ```

this is called twice now.



_Code quote:_
```XML
    add_fallthroughs(&mut after);

    // TODO(ilya): Move 'add_fallthroughs' to a dedicated test.
    add_fallthroughs(&mut after);
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2290)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 187 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2290#-NPHgOD13nj64LcVqRQg:-NPI2bua-lTuZ1WlVXxY:bndx7ve) ([raw file](https://github.com/starkware-libs/cairo/blob/19a3161377782cf7edc588150c42a7dcd5a9fbe7/crates/cairo-lang-lowering/src/db.rs#L187)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Is it posiible to remove my code now?

why are we doing topological sort twice?
</blockquote></details>

Your code is adding fallthroughs. I t doesnt do any sort of top sort. Sierragen assumes fallthroughs for now. Your code is needed.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 107 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2290)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 187 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2290#-NPHgOD13nj64LcVqRQg:-NPI0cai2Yn_1CZCo1TF:b-libqid) ([raw file](https://github.com/starkware-libs/cairo/blob/19a3161377782cf7edc588150c42a7dcd5a9fbe7/crates/cairo-lang-lowering/src/db.rs#L187)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Your code is adding fallthroughs. I t doesnt do any sort of top sort. Sierragen assumes fallthroughs for now. Your code is needed.
</blockquote></details>

It does a tologogical sort to find where to put the fallthorughs, if the block_ids are already sorted then you don't need such a complicated logic.

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 83 of 107 files at r1, 3 of 4 files at r2, 21 of 21 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2290)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 13 of 21 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2290)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 107 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2290)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 107 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2290)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 79 of 107 files at r1, 21 of 21 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2290)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
