### PR TITLE
Added inlining for loop unrolling.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4727)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4727#-NnmBL1I5uYWXqeduQRY:-NnmBL1I5uYWXqeduQRZ:b-itf78u) ([raw file](https://github.com/starkware-libs/cairo/blob/d0cde57f3ef8f48dbac3fe47c49c91f4ec149456/crates/cairo-lang-lowering/src/inline/mod.rs#L90)):*
> ```XML
>         FunctionWithBodyLongId::Generated { .. }
>     ) {
>         return Ok(InlineInfo { is_inlinable: false, should_inline: true });
> ```

doesn't this mean that you can't inline the function?



_Code quote:_
```XML
is_inlinable: false
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 340 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4727#-NnmCMhP6cxIQWdRMpAe:-NnmCMhP6cxIQWdRMpAf:bb7r2f0) ([raw file](https://github.com/starkware-libs/cairo/blob/d0cde57f3ef8f48dbac3fe47c49c91f4ec149456/crates/cairo-lang-lowering/src/inline/mod.rs#L340)):*
> ```XML
>             return Ok(true);
>         }
>         // This means we are in loop unrolling.
> ```

why?



_Code quote:_
```XML
 // This means we are in loop unrolling.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 347 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4727#-NnmDG8WD0ZzOBQ5hZJS:-NnmDG8WD0ZzOBQ5hZJT:b-fqt56p) ([raw file](https://github.com/starkware-libs/cairo/blob/d0cde57f3ef8f48dbac3fe47c49c91f4ec149456/crates/cairo-lang-lowering/src/inline/mod.rs#L347)):*
> ```XML
>         let lowered = db.priv_concrete_function_with_body_lowered_flat(function_id)?;
>         let statement_count = lowered.blocks.iter().fold(
>             self.statement_rewrite_stack.total_size + lowered.blocks.len(),
> ```

why is the stack size relevent?



_Code quote:_
```XML
 self.statement_rewrite_stack.total_size
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 3 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4727)* status: 1 of 7 files reviewed, 3 unresolved discussions (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4727)* status: 1 of 7 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4727#-NnmBL1I5uYWXqeduQRY:-NnmhqWJ74aTgjKN4aKM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d0cde57f3ef8f48dbac3fe47c49c91f4ec149456/crates/cairo-lang-lowering/src/inline/mod.rs#L90)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

doesn't this mean that you can't inline the function?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 340 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4727#-NnmCMhP6cxIQWdRMpAe:-NnmiAhzByXmCvg7K11r:b-od01c6) ([raw file](https://github.com/starkware-libs/cairo/blob/d0cde57f3ef8f48dbac3fe47c49c91f4ec149456/crates/cairo-lang-lowering/src/inline/mod.rs#L340)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why?
</blockquote></details>

both the caller function and our function are in a cycle.
But it is probably better to check if both are in the same SCC.
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 347 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4727#-NnmDG8WD0ZzOBQ5hZJS:-NnmiSIJ-ddIl22mzqMa:b-ju612l) ([raw file](https://github.com/starkware-libs/cairo/blob/d0cde57f3ef8f48dbac3fe47c49c91f4ec149456/crates/cairo-lang-lowering/src/inline/mod.rs#L347)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why is the stack size relevent?
</blockquote></details>

it is the total number of generated statements in the context - this is to bound the amount of generated code.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/scc/mod.rs` line 19 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4727#-Nnmz0YN5VHM39148i8y:-Nnmz0YN5VHM39148i8z:bqw5z1d) ([raw file](https://github.com/starkware-libs/cairo/blob/065467a8e6d1084aa1521db2cad16338a9fc7ce8/crates/cairo-lang-lowering/src/scc/mod.rs#L19)):*
> ```XML
>     // Sort the SCCs by their lowest function ID, just for comparison purposes. This would not
>     // necessarily be stable between runs.
>     scc.sort_by_key(|id| id.as_intern_id());
> ```

why is the sort needed? what happens without it?



_Code quote:_
```XML
 scc.sort_by_key(|id| id.as_intern_id());
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4727)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4727)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/scc/mod.rs` line 19 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4727#-Nnmz0YN5VHM39148i8y:-Nnn-bc2BuKmYChght7i:b-52ggia) ([raw file](https://github.com/starkware-libs/cairo/blob/065467a8e6d1084aa1521db2cad16338a9fc7ce8/crates/cairo-lang-lowering/src/scc/mod.rs#L19)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why is the sort needed? what happens without it?
</blockquote></details>

the algorithm starts from the caller function - it would get the same results, but possibly in different order.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/scc/mod.rs` line 19 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4727#-Nnmz0YN5VHM39148i8y:-Nnn3q3b7Yv6FOlzDefZ:bpni799) ([raw file](https://github.com/starkware-libs/cairo/blob/065467a8e6d1084aa1521db2cad16338a9fc7ce8/crates/cairo-lang-lowering/src/scc/mod.rs#L19)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the algorithm starts from the caller function - it would get the same results, but possibly in different order.
</blockquote></details>

so it is not needed?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/scc/mod.rs` line 19 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4727#-Nnmz0YN5VHM39148i8y:-Nnn475D2gwCMnZ7hy1P:b2ni8w0) ([raw file](https://github.com/starkware-libs/cairo/blob/065467a8e6d1084aa1521db2cad16338a9fc7ce8/crates/cairo-lang-lowering/src/scc/mod.rs#L19)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

so it is not needed?
</blockquote></details>

nvm

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4727#-:-Nnn49Vi7fN0NBvQtWFK:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4727)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/scc/mod.rs` line 19 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4727#-Nnmz0YN5VHM39148i8y:-Nnn57334-Dg4rKwkBVO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/065467a8e6d1084aa1521db2cad16338a9fc7ce8/crates/cairo-lang-lowering/src/scc/mod.rs#L19)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

nvm
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4727)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4727)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4727)* status: 5 of 13 files reviewed, all discussions resolved

**Review by ilyalesokhin-starkware — COMMENTED** [review]
there are changes here after my lgtm

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4727#-:-No71USmDS-o-TvX3KqM:b1ea9tq)* status: 5 of 13 files reviewed, all discussions resolved

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 10 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4727)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 467 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4727#-NozLSq05iBqrL_BmbA3:-NozLSq05iBqrL_BmbA4:biqttxl) ([raw file](https://github.com/starkware-libs/cairo/blob/71d13b8d1fc7aa78987f21c386c136f6bf5eeae9/crates/cairo-lang-lowering/src/db.rs#L467)):*
> ```XML
>                 {
>                     direct_callees.push(statement_call.function);
>                 }
> ```

I think it is more consistent with the comment this way



_Suggestion:_
```XML
                if !(dependency_type == DependencyType::Cost && statement_call.coupon_input.is_some)
                {
                    direct_callees.push(statement_call.function);
                }
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4727)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 467 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4727#-NozLSq05iBqrL_BmbA3:-Np0I19X5y-tpQk20em2:b-zdki1k) ([raw file](https://github.com/starkware-libs/cairo/blob/71d13b8d1fc7aa78987f21c386c136f6bf5eeae9/crates/cairo-lang-lowering/src/db.rs#L467)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I think it is more consistent with the comment this way
</blockquote></details>

maybe it does - but it isn't a part of this PR.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4727#-:-NpE394OD1tyHpb0GCNE:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request closed without merging**
