### PR TITLE
Add clone

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2449)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2449** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2449" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2449?utm_source=stack-comment).

**Comment by spapinistarkware** [comment]
@gaetbout FYI

**Comment by gaetbout** [comment]
I'll close my PR and wait for this one! 
🥳 😃

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2449)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware and @yuvalsw)

___
*[`corelib/src/array.cairo` line 116 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2449#-NQKHK2_CRppVz6WBvdI:-NQKHK2_CRppVz6WBvdJ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e8ed97b17eec43ab9e5c84086b6c25bd56d35168/corelib/src/array.cairo#L116)):*
> ```Cairo
>         Option::None(_) => {
>             let mut data = array_new();
>             array_append(ref data, 'OOG');
> ```





_Suggestion:_
```Cairo
array_append(ref data, 'Out of gas');
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2449)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi and @yuvalsw)

___
*[`corelib/src/array.cairo` line 116 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2449#-NQKHK2_CRppVz6WBvdI:-NQKIjhaBkYG5hSCI77u:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e8ed97b17eec43ab9e5c84086b6c25bd56d35168/corelib/src/array.cairo#L116)):*
> ```Cairo
>         Option::None(_) => {
>             let mut data = array_new();
>             array_append(ref data, 'OOG');
> ```

Done.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2449)* status: all files reviewed, 6 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`corelib/src/array.cairo` line 111 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2449#-NQKTAFi9mgJZgczElvI:-NQKTAFi9mgJZgczElvJ:bo1x4g5) ([raw file](https://github.com/starkware-libs/cairo/blob/b3f6c59d724352dbb381be2d5423c4ace2492d69/corelib/src/array.cairo#L111)):*
> ```Cairo
> }
> 
> fn clone_loop<T, impl TClone: Clone::<T>>(mut at: Span<T>, ref response: Array<T>) {
> ```

why is the name 'at'?



_Code quote:_
```Cairo
at
```
___
*[`corelib/src/array.cairo` line 125 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2449#-NQKSudTEkpE9D8nXfzW:-NQKSudTEkpE9D8nXfzX:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b3f6c59d724352dbb381be2d5423c4ace2492d69/corelib/src/array.cairo#L125)):*
> ```Cairo
>             clone_loop::<T, TClone>(at, ref response);
>         },
>         Option::None(_) => (),
> ```





_Suggestion:_
```Cairo
{}
```
___
*[`corelib/src/clone.cairo` line 5 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2449#-NQKTdc99HwMJI9j7Gas:-NQKTdc99HwMJI9j7Gat:b-wtreqa) ([raw file](https://github.com/starkware-libs/cairo/blob/b3f6c59d724352dbb381be2d5423c4ace2492d69/corelib/src/clone.cairo#L5)):*
> ```Cairo
> }
> 
> impl TCopyClone<T, impl TCopy: Copy::<T>> of Clone::<T> {
> ```

need turbofish?



_Code quote:_
```Cairo
::<
```
___
*[`corelib/src/test.cairo` line 829 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2449#-NQKUER92DvmAB_8LxiL:-NQKUER92DvmAB_8LxiM:b5814dn) ([raw file](https://github.com/starkware-libs/cairo/blob/b3f6c59d724352dbb381be2d5423c4ace2492d69/corelib/src/test.cairo#L829)):*
> ```Cairo
> fn test_array_clone() {
>     let felt_snap_array: @Array<felt> = @test_array_helper();
>     let felt_snap_array_clone: Array<felt> = ArrayTCloneImpl::clone(felt_snap_array);
> ```

Can't you do?



_Suggestion:_
```Cairo
 felt_snap_array.clone()
```
___
*[`corelib/src/test.cairo` line 830 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2449#-NQKUOA-5RIXgzyQ2gdM:-NQKUOA-5RIXgzyQ2gdN:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/b3f6c59d724352dbb381be2d5423c4ace2492d69/corelib/src/test.cairo#L830)):*
> ```Cairo
>     let felt_snap_array: @Array<felt> = @test_array_helper();
>     let felt_snap_array_clone: Array<felt> = ArrayTCloneImpl::clone(felt_snap_array);
>     assert(felt_snap_array_clone.len() == 3_usize, 'felt_clone == 2');
> ```

?



_Code quote:_
```Cairo
felt_clone == 2
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2449)* status: all files reviewed, 6 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`corelib/src/test.cairo` line 829 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2449#-NQKUER92DvmAB_8LxiL:-NQKlMup3uNt2B0sbo-g:b-hoftsi) ([raw file](https://github.com/starkware-libs/cairo/blob/b3f6c59d724352dbb381be2d5423c4ace2492d69/corelib/src/test.cairo#L829)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Can't you do?
</blockquote></details>

Not right now.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2449)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`corelib/src/clone.cairo` line 5 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2449#-NQKTdc99HwMJI9j7Gas:-NQKm2RA0ml9YaMYSePe:bh67b1d) ([raw file](https://github.com/starkware-libs/cairo/blob/b3f6c59d724352dbb381be2d5423c4ace2492d69/corelib/src/clone.cairo#L5)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

need turbofish?
</blockquote></details>

Need right now.
___
*[`corelib/src/test.cairo` line 830 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2449#-NQKUOA-5RIXgzyQ2gdM:-NQKlmvq53-4RKrl6_AJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b3f6c59d724352dbb381be2d5423c4ace2492d69/corelib/src/test.cairo#L830)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2449)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`corelib/src/clone.cairo` line 5 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2449#-NQKTdc99HwMJI9j7Gas:-NQKoGLkDsCf02fRzZON:bb7110c) ([raw file](https://github.com/starkware-libs/cairo/blob/b3f6c59d724352dbb381be2d5423c4ace2492d69/corelib/src/clone.cairo#L5)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Need right now.
</blockquote></details>

Not*

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2449#-:-NQKtt2E-dVfciLt6k4w:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2449#-:-NQKuotM6cYgeLgQYQHR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
