### PR TITLE
Handled gas in standalone mode.

### PR DESCRIPTION
**Pull request by orizi**

### CODE REVIEW

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6835#-:-OD_5wCC36s-F0Jq78Xt:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
it fails :(

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6835#-:-OD_GjdN9QOIQL26W6-i:bcgzy2x)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
Fixed in https://reviewable.io/reviews/starkware-libs/cairo/6844 - as less related to here.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6835#-:-OD_juH8-kDIEybijOJL:b-qywd5r)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-runnable-utils/src/builder.rs` line 367 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6835#-ODa0okYALylf1TaBog6:-ODa0okYALylf1TaBog7:b5jaax4) ([raw file](https://github.com/starkware-libs/cairo/blob/dca9a0fd6dee3dd85fafc8abe59bb2b9c7ebbf9c/crates/cairo-lang-runnable-utils/src/builder.rs#L367)):*
> ```XML
>             // Setting gas to be far from u128 boundaries.
>             casm_build_extend! {ctx,
>                 const max_gas = i128::MAX;
> ```

The gas is signed?



_Code quote:_
```XML
const max_gas = i128::MAX;
```

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6835)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6835)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-runnable-utils/src/builder.rs` line 367 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6835#-ODa0okYALylf1TaBog6:-ODa1LA81r89jiZcxEGQ:bk1zjqx) ([raw file](https://github.com/starkware-libs/cairo/blob/dca9a0fd6dee3dd85fafc8abe59bb2b9c7ebbf9c/crates/cairo-lang-runnable-utils/src/builder.rs#L367)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

The gas is signed?
</blockquote></details>

no but its checks are u128 - so i want to prevent the chance of an overflow (may possibly be cause by squash), as well as of an underflow.

**Pull request merged**
