### PR TITLE
Refactor resolve_variable_by_name() in preparation for supporting con…

### PR DESCRIPTION
**Pull request by liorgold2**
…stants.

commit-id:a8c53701

---

**Stack**:
- #1827
- #1826
- #1822
- #1821
- #1820
- #1818 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1818#-:-NM9uq4I6G0s0qht34fN:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1092 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1818#-NM9u31h1bC5kM7wa8AW:-NM9u31h1bC5kM7wa8AX:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/af316afd7402ed46d12093362558e4d35400728e/crates/cairo-lang-semantic/src/expr/compute.rs#L1092)):*
> ```XML
>             let variable_name = identifier.text(ctx.db.upcast());
>             if let Some(res) = get_variable_by_name(ctx, &variable_name, path.stable_ptr().into()) {
>                 return Ok(res);
> ```





_Suggestion:_
```XML
            get_variable_by_name(ctx, &variable_name, path.stable_ptr().into()).ok_or_else(
                ||ctx.diagnostics.report(&identifier, VariableNotFound { name: variable_name }))
```
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1114 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1818#-NM9uSvsEnoWNGWz7ul5:-NM9uSvsEnoWNGWz7ul6:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/af316afd7402ed46d12093362558e4d35400728e/crates/cairo-lang-semantic/src/expr/compute.rs#L1114)):*
> ```XML
>     let variable_name = identifier.text(ctx.db.upcast());
>     if let Some(res) = get_variable_by_name(ctx, &variable_name, stable_ptr) {
>         Ok(res)
> ```





_Suggestion:_
```XML
    get_variable_by_name(ctx, &variable_name, stable_ptr).ok_or_else(||
        ctx.diagnostics.report(identifier, VariableNotFound { name: variable_name }))
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1818)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1092 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1818#-NM9u31h1bC5kM7wa8AW:-NMD8wYhDNoOrRqiRm67:bze5cxe) ([raw file](https://github.com/starkware-libs/cairo/blob/af316afd7402ed46d12093362558e4d35400728e/crates/cairo-lang-semantic/src/expr/compute.rs#L1092)):*
> ```XML
>             let variable_name = identifier.text(ctx.db.upcast());
>             if let Some(res) = get_variable_by_name(ctx, &variable_name, path.stable_ptr().into()) {
>                 return Ok(res);
> ```

Noted. I want to use early return since I'm adding code after it in the next PR.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1114 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1818#-NM9uSvsEnoWNGWz7ul5:-NMD8vPz4lYVosKzxOVl:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/af316afd7402ed46d12093362558e4d35400728e/crates/cairo-lang-semantic/src/expr/compute.rs#L1114)):*
> ```XML
>     let variable_name = identifier.text(ctx.db.upcast());
>     if let Some(res) = get_variable_by_name(ctx, &variable_name, stable_ptr) {
>         Ok(res)
> ```

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1818)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1818)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
