### PR TITLE
Handling extremely long user-type names by specific bounding.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #5871
- #5870
- #5869
- #5867
- #5852
- #5858 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5858)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/types.rs` line 252 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5858#-O08CDMs2FcowW4KZ3md:-O08CDMs2FcowW4KZ3me:bwfgtdc) ([raw file](https://github.com/starkware-libs/cairo/blob/0a29dd533d156f0a778f98e71fb257918305e76f/crates/cairo-lang-semantic/src/types.rs#L252)):*
> ```XML
>         let generic_type_format = self.generic_type(db).format(db.upcast());
>         let mut generic_args = self.generic_args(db).into_iter();
>         if let Some(first) = generic_args.next() {
> ```

This can cause collision in the types, right? 
Isn't this a problem?



_Code quote:_
```XML
 if let Some(first) = generic_args.next() {
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5858)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 252 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5858#-O08CDMs2FcowW4KZ3md:-O08HGOyBa9S1GJoYm19:b-w3qmqp) ([raw file](https://github.com/starkware-libs/cairo/blob/0a29dd533d156f0a778f98e71fb257918305e76f/crates/cairo-lang-semantic/src/types.rs#L252)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

This can cause collision in the types, right? 
Isn't this a problem?
</blockquote></details>

it can - do you think just adding the type-id itself is a good enough solution?
it isn't necessarily stable across compilations - but within one it will be consistent.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5858)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 252 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5858#-O08CDMs2FcowW4KZ3md:-O08Hgvh8TuerigwbwyU:b-u6tkgc) ([raw file](https://github.com/starkware-libs/cairo/blob/0a29dd533d156f0a778f98e71fb257918305e76f/crates/cairo-lang-semantic/src/types.rs#L252)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it can - do you think just adding the type-id itself is a good enough solution?
it isn't necessarily stable across compilations - but within one it will be consistent.
</blockquote></details>

we can add a specific sierra check to make sure we catch this if this propagates down to sierra.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5858#-:-O0IS6KW0zVYRCjtiDXM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
