### PR TITLE
Checked semantic diagnostics in contract test

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3440)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/contract_test.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3440#-NYH2Plo0tEPYXklJwM7:-NYH2Plo0tEPYXklJwM8:b-1qwc30) ([raw file](https://github.com/starkware-libs/cairo/blob/8dde89163790832f02dad7bd2c0c7e654b8b3e35/crates/cairo-lang-starknet/src/contract_test.rs#L66)):*
> ```XML
>     db.module_semantic_diagnostics(crate_module_id)
>         .unwrap()
>         .expect_with_db(db, "Unexpected semantic diagnostics");
> ```

why is checking the module diagnostics not enough.

like we do here:
https://github.com/starkware-libs/cairo/blob/e4210f602a794a53c4a0297d5fa593f7b9a13872/crates/cairo-lang-semantic/src/test_utils.rs#L115



_Suggestion:_
```XML
    db.module_semantic_diagnostics(crate_module_id)
        .unwrap()
        .expect_with_db(db, "Unexpected semantic diagnostics");
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3440)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3440)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/contract_test.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3440#-NYH2Plo0tEPYXklJwM7:-NYHZbTg27nW7FioQOZW:b-dtwkxc) ([raw file](https://github.com/starkware-libs/cairo/blob/8dde89163790832f02dad7bd2c0c7e654b8b3e35/crates/cairo-lang-starknet/src/contract_test.rs#L66)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why is checking the module diagnostics not enough.

like we do here:
https://github.com/starkware-libs/cairo/blob/e4210f602a794a53c4a0297d5fa593f7b9a13872/crates/cairo-lang-semantic/src/test_utils.rs#L115
</blockquote></details>

"// Note that the parent module does not report the diagnostics of its submodules."
And the diagnostics may be in submodules (e.g. the contract module or generated submodules).

Changed to use get_crate_semantic_diagnostics which is better (recursive all the way).

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3440#-:-NYHnR3k1w5vMurMzSHz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3440)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
