### PR TITLE
match on felt252 optimization using enum libfuncs

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4429)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r2, 3 of 7 files at r3, 12 of 33 files at r5, 25 of 32 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4429)* status: 38 of 55 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @TomerStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4429#-Nnsy4qT7mR-qh0mjRTJ:-Nnsy4qT7mR-qh0mjRTK:b-l6u88n) (no related file):*
rebase

___

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 29 files at r1, 1 of 5 files at r2, 2 of 32 files at r6, 1 of 24 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4429)* status: 25 of 55 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`corelib/src/internal.cairo` line 10 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4429#-No6yTj91drPga2TLIAD:-No6yTj91drPga2TLIAE:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d84967a03c531f7805c3ab452dbf0db2528a2210/corelib/src/internal.cairo#L10)):*
> ```Cairo
> extern type index_enum_type<const NUM_VARIANTS: felt252>;
> 
> extern type BoundedInt<const min: felt252, const max: felt252>;
> ```





_Suggestion:_
```Cairo
extern type BoundedInt<const MIN: felt252, const MAX: felt252>;
```
___
*[`crates/cairo-lang-lowering/src/objects.rs` line 342 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4429#-No6yjgN7c5NNcpcoQPv:-No6yjgN7c5NNcpcoQPw:brtlbfk) ([raw file](https://github.com/starkware-libs/cairo/blob/d84967a03c531f7805c3ab452dbf0db2528a2210/crates/cairo-lang-lowering/src/objects.rs#L342)):*
> ```XML
>     pub location: LocationId,
> }
> /// A statement that matches an enum, and "calls" a possibly different block for each branch.
> ```

this is an enum value - doc should be different from previous struct.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 2042 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4429#-No6z4uJ6AE7MxJwdKCa:-No6z4uJ6AE7MxJwdKCb:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/d84967a03c531f7805c3ab452dbf0db2528a2210/crates/cairo-lang-lowering/src/lower/mod.rs#L2042)):*
> ```XML
> }
> 
> fn lower_expr_match_index_enum(
> ```

doc
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 2167 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4429#-No6z7A07ZPqliIiMaVt:-No6z7A07ZPqliIiMaVu:b-vysxgr) ([raw file](https://github.com/starkware-libs/cairo/blob/d84967a03c531f7805c3ab452dbf0db2528a2210/crates/cairo-lang-lowering/src/lower/mod.rs#L2167)):*
> ```XML
>     });
> 
>     if max <= 3 {
> ```

make this a flag - so would be easily disabled and be an argument for testing.



_Code quote:_
```XML
    if max <= 3 {
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4429)* status: 25 of 55 files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 94 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4429#-No6zXYgBs5d8mwQMh1q:-No6zXYgBs5d8mwQMh1r:bv8i9tv) ([raw file](https://github.com/starkware-libs/cairo/blob/d84967a03c531f7805c3ab452dbf0db2528a2210/crates/cairo-lang-semantic/src/corelib.rs#L94)):*
> ```XML
>     )
>     .expect("could not find")
> }
> ```

and doc all.



_Suggestion:_
```XML
}

pub fn range_check_ty(db: &dyn SemanticGroup) -> TypeId {
    get_core_ty_by_name(db, "RangeCheck".into(), vec![])
}

pub fn index_enum_ty(db: &dyn SemanticGroup, num_of_variants: BigInt) -> TypeId {
    let internal = core_submodule(db, "internal");
    let literal_id = db.intern_literal(LiteralLongId { value: num_of_variants });
    try_get_ty_by_name(
        db,
        internal,
        "index_enum_type".into(),
        vec![GenericArgumentId::Literal(literal_id)],
    )
    .expect("could not find")
}
pub fn bounded_int_ty(db: &dyn SemanticGroup, min: BigInt, max: BigInt) -> TypeId {
    let internal = core_submodule(db, "internal");
    let lower_id = db.intern_literal(LiteralLongId { value: min });
    let upper_id = db.intern_literal(LiteralLongId { value: max });
    try_get_ty_by_name(
        db,
        internal,
        "BoundedInt".into(),
        vec![GenericArgumentId::Literal(lower_id), GenericArgumentId::Literal(upper_id)],
    )
    .expect("could not find")
}
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 32 files at r6, 19 of 24 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4429)* status: 46 of 55 files reviewed, 10 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 510 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4429#-No6znIm0mE5e2UHifmT:-No6znIm0mE5e2UHifmU:b-jzinuz) ([raw file](https://github.com/starkware-libs/cairo/blob/d84967a03c531f7805c3ab452dbf0db2528a2210/crates/cairo-lang-semantic/src/corelib.rs#L510)):*
> ```XML
>     )
> }
> /// Given a core library function name and its generic arguments, returns [FunctionId].
> ```

this is going to be rebased and using upcast instead in the end.



_Code quote:_
```XML
pub fn core_constrain_range(db: &dyn SemanticGroup, input: TypeId, output: TypeId) -> FunctionId {
    let internal = core_submodule(db, "internal");

    get_function_id(
        db,
        internal,
        "constrain_range".into(),
        vec![GenericArgumentId::Type(input), GenericArgumentId::Type(output)],
    )
}
/// Given a core library function name and its generic arguments, returns [FunctionId].
```
___
*[`crates/cairo-lang-sierra-generator/src/db.rs` line 63 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4429#-No6zwb440DgDLlN915N:-No6zwb5EfeOJ8Z7FDzf:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/d84967a03c531f7805c3ab452dbf0db2528a2210/crates/cairo-lang-sierra-generator/src/db.rs#L63)):*
> ```XML
> 
>     #[salsa::invoke(crate::types::get_index_type_id)]
>     fn get_index_type_id(
> ```

doc
___
*[`crates/cairo-lang-sierra-generator/src/types.rs` line 41 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4429#-No7--Nx-9qGpeM3i4Xv:-No7--Nx-9qGpeM3i4Xw:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d84967a03c531f7805c3ab452dbf0db2528a2210/crates/cairo-lang-sierra-generator/src/types.rs#L41)):*
> ```XML
> }
> 
> pub fn get_index_type_id(
> ```





_Suggestion:_
```XML
/// See [SierraGenGroup::get_index_type_id] for documentation.
pub fn get_index_type_id(
```
___
*[`crates/cairo-lang-sierra-generator/src/types.rs` line 52 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4429#-No70Htp82gY3uxtWUdR:-No70Htp82gY3uxtWUdS:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d84967a03c531f7805c3ab452dbf0db2528a2210/crates/cairo-lang-sierra-generator/src/types.rs#L52)):*
> ```XML
>             .get_concrete_type_id(*generic_arg_ty)
>             .map(SierraGenericArg::Type))
>     )
> ```





_Suggestion:_
```XML
    let deps: Arc<Vec<TypeId>> = vec![unit; index_count].into();
    let generic_args = chain!(
        [Ok(SierraGenericArg::UserType(format!("match_value_enum_{}", index_count).into()))],
        deps.iter().map(|generic_arg_ty| db
            .get_concrete_type_id(*generic_arg_ty)
            .map(SierraGenericArg::Type))
    )
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4429)* status: 46 of 55 files reviewed, 10 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-sierra-generator/src/types.rs` line 49 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4429#-No70a3-5ql6j1IMpzPo:-No70a3-5ql6j1IMpzPp:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d84967a03c531f7805c3ab452dbf0db2528a2210/crates/cairo-lang-sierra-generator/src/types.rs#L49)):*
> ```XML
>     let generic_args = chain!(
>         [Ok(SierraGenericArg::UserType(format!("match_value_enum {}", index_count).into()))],
>         deps.iter().map(|generic_arg_ty| db
> ```





_Suggestion:_
```XML
    let generic_args = chain!(
        [Ok(SierraGenericArg::UserType(format!("index_enum_type<{}>", index_count).into()))],
        deps.iter().map(|generic_arg_ty| db
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 29 files at r1, 1 of 33 files at r5, 1 of 32 files at r6, 3 of 24 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4429)* status: 54 of 55 files reviewed, 11 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-sierra-generator/src/block_generator.rs` line 552 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4429#-No710ea19jyUpTaSFVw:-No710ea19jyUpTaSFVx:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/d84967a03c531f7805c3ab452dbf0db2528a2210/crates/cairo-lang-sierra-generator/src/block_generator.rs#L552)):*
> ```XML
> }
> 
> fn generate_match_value_code(
> ```

doc

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r8, 1 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4429)* status: 54 of 55 files reviewed, 10 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 68 at r9](https://reviewable.io/reviews/starkware-libs/cairo/4429#-No78wvk1F0CN6fn_YKq:-No78wvk1F0CN6fn_YKr:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7753f9d8f78beaf429a79bed0ec7f963299a1189/crates/cairo-lang-semantic/src/corelib.rs#L68)):*
> ```XML
> }
> 
> /// Returns the concrete type of a bounded int type.with a given min and max.
> ```





_Suggestion:_
```XML
/// Returns the concrete type of a bounded int type with a given min and max.
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4429)* status: 54 of 55 files reviewed, 10 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 2042 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4429#-No6z4uJ6AE7MxJwdKCa:-No74RFICoQ1wZ0qlw46:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d84967a03c531f7805c3ab452dbf0db2528a2210/crates/cairo-lang-lowering/src/lower/mod.rs#L2042)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 94 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4429#-No6zXYgBs5d8mwQMh1q:-No76U4c5M6AERJGOlgl:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d84967a03c531f7805c3ab452dbf0db2528a2210/crates/cairo-lang-semantic/src/corelib.rs#L94)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

and doc all.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 510 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4429#-No6znIm0mE5e2UHifmT:-No76xHzAFdfdYtVf59e:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d84967a03c531f7805c3ab452dbf0db2528a2210/crates/cairo-lang-semantic/src/corelib.rs#L510)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is going to be rebased and using upcast instead in the end.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/block_generator.rs` line 552 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4429#-No710ea19jyUpTaSFVw:-No783RY4LtOZFMmp-sC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d84967a03c531f7805c3ab452dbf0db2528a2210/crates/cairo-lang-sierra-generator/src/block_generator.rs#L552)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/db.rs` line 63 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4429#-No6zwb440DgDLlN915N:-No7A9Mz6tEBXwnCIgQ7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d84967a03c531f7805c3ab452dbf0db2528a2210/crates/cairo-lang-sierra-generator/src/db.rs#L63)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/types.rs` line 41 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4429#-No7--Nx-9qGpeM3i4Xv:-No7AB1_Db7yWqq0PnWD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d84967a03c531f7805c3ab452dbf0db2528a2210/crates/cairo-lang-sierra-generator/src/types.rs#L41)):*
> ```XML
> }
> 
> pub fn get_index_type_id(
> ```

Done.
___
*[`crates/cairo-lang-sierra-generator/src/types.rs` line 49 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4429#-No70a3-5ql6j1IMpzPo:-No7Aecl654TlgWOA8_9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d84967a03c531f7805c3ab452dbf0db2528a2210/crates/cairo-lang-sierra-generator/src/types.rs#L49)):*
> ```XML
>     let generic_args = chain!(
>         [Ok(SierraGenericArg::UserType(format!("match_value_enum {}", index_count).into()))],
>         deps.iter().map(|generic_arg_ty| db
> ```

Done.
___
*[`crates/cairo-lang-sierra-generator/src/types.rs` line 52 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4429#-No70Htp82gY3uxtWUdR:-No7Af-I-O2HGHuDLCXG:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/d84967a03c531f7805c3ab452dbf0db2528a2210/crates/cairo-lang-sierra-generator/src/types.rs#L52)):*
> ```XML
>             .get_concrete_type_id(*generic_arg_ty)
>             .map(SierraGenericArg::Type))
>     )
> ```

done

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 2 files at r9, 7 of 7 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4429)* status: all files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4429)* status: 47 of 56 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4429#-Nnsy4qT7mR-qh0mjRTJ:-No7CAhC558-6Y3Gz87A:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rebase
</blockquote></details>

Done.

___
___
*[`corelib/src/internal.cairo` line 10 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4429#-No6yTj91drPga2TLIAD:-No7QuwV6ZeBIooxrmTM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d84967a03c531f7805c3ab452dbf0db2528a2210/corelib/src/internal.cairo#L10)):*
> ```Cairo
> extern type index_enum_type<const NUM_VARIANTS: felt252>;
> 
> extern type BoundedInt<const min: felt252, const max: felt252>;
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/objects.rs` line 342 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4429#-No6yjgN7c5NNcpcoQPv:-No7FeBP4Mx-TVUo8d_-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d84967a03c531f7805c3ab452dbf0db2528a2210/crates/cairo-lang-lowering/src/objects.rs#L342)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is an enum value - doc should be different from previous struct.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 2167 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4429#-No6z7A07ZPqliIiMaVt:-No7QqE74Z-MQv0ObiUf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d84967a03c531f7805c3ab452dbf0db2528a2210/crates/cairo-lang-lowering/src/lower/mod.rs#L2167)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

make this a flag - so would be easily disabled and be an argument for testing.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 68 at r9](https://reviewable.io/reviews/starkware-libs/cairo/4429#-No78wvk1F0CN6fn_YKq:-No7EnGH6WoxBUnMGmo3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7753f9d8f78beaf429a79bed0ec7f963299a1189/crates/cairo-lang-semantic/src/corelib.rs#L68)):*
> ```XML
> }
> 
> /// Returns the concrete type of a bounded int type.with a given min and max.
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r11.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4429)* status: 50 of 56 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 2250 at r11](https://reviewable.io/reviews/starkware-libs/cairo/4429#-No7ReAD4huEnWVYdi57:-No7ReAD4huEnWVYdi58:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/39c6bc73f2838c6d4fd19bf0e91c8d38c26d0dc5/crates/cairo-lang-lowering/src/lower/mod.rs#L2250)):*
> ```XML
>         })
>         .unwrap_or(usize::MAX)
> }
> ```





_Suggestion:_
```XML
/// Returns the threshold for the number of arms for optimising numeric match expressions, by using
/// a jump table instead of an if-else construct.
fn numeric_match_optimization_threshold(ctx: &mut LoweringContext<'_, '_>) -> usize {
    // Use [usize::max] as the default value, so that the optimization is not used by default.
    // TODO(tomer): Make the default to 3 on `sierra-minor-update` branch.
    ctx.db
        .get_flag(FlagId::new(ctx.db.upcast(), "numeric_match_optimization_min_arms_threshold"))
        .map(|flag| match *flag {
            Flag::NumericMatchOptimizationMinArmsThreshold(threshold) => threshold,
            _ => panic!("Wrong type flag `{flag:?}`."),
        })
        .unwrap_or(usize::MAX)
}
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r11.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4429)* status: 54 of 56 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-sierra-generator/src/types.rs` line 63 at r11](https://reviewable.io/reviews/starkware-libs/cairo/4429#-No7SSrSBCGNoC60aPzR:-No7SSrSBCGNoC60aPzS:b-l6hdjr) ([raw file](https://github.com/starkware-libs/cairo/blob/39c6bc73f2838c6d4fd19bf0e91c8d38c26d0dc5/crates/cairo-lang-sierra-generator/src/types.rs#L63)):*
> ```XML
>         1 => 5,
>         3 | _ => 6,
>     };
> ```

revert



_Code quote:_
```XML
    let y = 5;
    match y {
        0 => 4,
        1 => 5,
        3 | _ => 6,
    };
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4429#-:-No7_j_BCHLyM171BNr3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4429)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4429)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
