### PR TITLE
add conescutive math operator diagnostic to the parser

### PR DESCRIPTION
**Pull request by dean-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6392)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6392)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1101 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6392#-O79AD6m-QwlKfJPtVZK:-O79AD6nE58zoX38wYtX:b-hykxp5) ([raw file](https://github.com/starkware-libs/cairo/blob/ac8ec091a0af5600d61e26f30f9cccf807fc417c/crates/cairo-lang-parser/src/parser.rs#L1101)):*
> ```XML
>     /// # Returns:
>     /// `true` if the token is a relational or equality operator, otherwise `false`.
>     fn is_math_operator(&self, kind: SyntaxKind) -> bool {
> ```

rename method.
+ - / * are all math operators as well.
___
*[`crates/cairo-lang-parser/src/parser.rs` line 1109 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6392#-O79AB7P3lku7rRnbAZG:-O79AB7P3lku7rRnbAZH:b-quot75) ([raw file](https://github.com/starkware-libs/cairo/blob/ac8ec091a0af5600d61e26f30f9cccf807fc417c/crates/cairo-lang-parser/src/parser.rs#L1109)):*
> ```XML
>                     | SyntaxKind::TerminalGE   // >=
>                     | SyntaxKind::TerminalEqEq // ==
>                     | SyntaxKind::TerminalNeq // !=
> ```

properly align doc.



_Code quote:_
```XML
                    | SyntaxKind::TerminalGT   // >
                    | SyntaxKind::TerminalLE   // <=
                    | SyntaxKind::TerminalGE   // >=
                    | SyntaxKind::TerminalEqEq // ==
                    | SyntaxKind::TerminalNeq // !=
```
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/expr` line 63 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6392#-O798jiV-mEw9g0_PTVm:-O798jiV-mEw9g0_PTVn:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/ac8ec091a0af5600d61e26f30f9cccf807fc417c/crates/cairo-lang-parser/src/parser_test_data/partial_trees/expr#L63)):*
> ```
> //! > ==========================================================================
> 
> //! > Test precedence between unary and binary operators1231233
> ```

?



_Code quote:_
```
1231233
```

**Review by dean-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6392)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1101 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6392#-O79AD6m-QwlKfJPtVZK:-O79Ubu_-0jYxspIBVE6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ac8ec091a0af5600d61e26f30f9cccf807fc417c/crates/cairo-lang-parser/src/parser.rs#L1101)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rename method.
+ - / * are all math operators as well.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser.rs` line 1109 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6392#-O79AB7P3lku7rRnbAZG:-O79Ueqe-YH-WmI-YnM6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ac8ec091a0af5600d61e26f30f9cccf807fc417c/crates/cairo-lang-parser/src/parser.rs#L1109)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

properly align doc.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/expr` line 63 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6392#-O798jiV-mEw9g0_PTVm:-O79UgWw1I0pA7Vs-7UE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ac8ec091a0af5600d61e26f30f9cccf807fc417c/crates/cairo-lang-parser/src/parser_test_data/partial_trees/expr#L63)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6392)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-parser/src/diagnostic.rs` line 42 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6392#-O79UttTBKjRJlqw88BQ:-O79UttTBKjRJlqw88BR:b88473x) ([raw file](https://github.com/starkware-libs/cairo/blob/0931d0a6ed76988ed09cac535037aa91f2bd1de2/crates/cairo-lang-parser/src/diagnostic.rs#L42)):*
> ```XML
>     AttributesWithoutStatement,
>     DisallowedTrailingSeparatorOr,
>     ConsecutiveMathOperators { first_op: SyntaxKind, second_op: SyntaxKind },
> ```

here as well.
___
*[`crates/cairo-lang-parser/src/parser_test_data/full_trees/test1` line 875 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6392#-O79V5XzEK57Ur7GBMXJ:-O79V5XzEK57Ur7GBMXK:b-bzstcz) ([raw file](https://github.com/starkware-libs/cairo/blob/0931d0a6ed76988ed09cac535037aa91f2bd1de2/crates/cairo-lang-parser/src/parser_test_data/full_trees/test1#L875)):*
> ```
> error: Consecutive math operators are not allowed: 'TerminalEqEq' followed by 'TerminalEqEq'
>  --> src/parser_test_data/cairo_test_files/test1.cairo:15:20
>     let z = if 0 + x == y {
> ```

this doesn't seem right.



_Code quote:_
```
 let z = if 0 + x == y {
```

**Review by dean-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6392)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-parser/src/diagnostic.rs` line 42 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6392#-O79UttTBKjRJlqw88BQ:-O79WbSw02tO3mLLQRw4:bte2x37) ([raw file](https://github.com/starkware-libs/cairo/blob/0931d0a6ed76988ed09cac535037aa91f2bd1de2/crates/cairo-lang-parser/src/diagnostic.rs#L42)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

here as well.
</blockquote></details>

Please elaborate. It seems fine to me.

**Review by dean-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6392)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-parser/src/parser_test_data/full_trees/test1` line 875 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6392#-O79V5XzEK57Ur7GBMXJ:-O79fEJa7Z7stxCK6jUE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0931d0a6ed76988ed09cac535037aa91f2bd1de2/crates/cairo-lang-parser/src/parser_test_data/full_trees/test1#L875)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this doesn't seem right.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6392)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1109 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6392#-O79jw9A7DrA5YChmZNH:-O79jw9A7DrA5YChmZNI:bwecfet) ([raw file](https://github.com/starkware-libs/cairo/blob/cee39089e9bf568e928083e6ba2b9cec3be97bed/crates/cairo-lang-parser/src/parser.rs#L1109)):*
> ```XML
>                     | SyntaxKind::TerminalGE    // >=
>                     | SyntaxKind::TerminalEqEq  // ==
>                     | SyntaxKind::TerminalNeq // !=
> ```

i think you can just drop the comments here - the original names are clear enough.



_Suggestion:_
```XML
            SyntaxKind::TerminalLT
                    | SyntaxKind::TerminalGT
                    | SyntaxKind::TerminalLE
                    | SyntaxKind::TerminalGE
                    | SyntaxKind::TerminalEqEq
                    | SyntaxKind::TerminalNeq
```
___
*[`crates/cairo-lang-parser/src/parser_test_data/full_trees/test1` line 875 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6392#-O79V5XzEK57Ur7GBMXJ:-O79kGhZAVJYJThcwwvK:b3uch6l) ([raw file](https://github.com/starkware-libs/cairo/blob/0931d0a6ed76988ed09cac535037aa91f2bd1de2/crates/cairo-lang-parser/src/parser_test_data/full_trees/test1#L875)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

still doesn't seem right.

**Review by dean-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6392)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1109 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6392#-O79jw9A7DrA5YChmZNH:-O7ECxgo93MbpiT8xrwG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cee39089e9bf568e928083e6ba2b9cec3be97bed/crates/cairo-lang-parser/src/parser.rs#L1109)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i think you can just drop the comments here - the original names are clear enough.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/full_trees/test1` line 875 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6392#-O79V5XzEK57Ur7GBMXJ:-O7EKf1i8djq5mX1zXZP:br54sof) ([raw file](https://github.com/starkware-libs/cairo/blob/0931d0a6ed76988ed09cac535037aa91f2bd1de2/crates/cairo-lang-parser/src/parser_test_data/full_trees/test1#L875)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

still doesn't seem right.
</blockquote></details>

I think it's fine now.
All tests are successfull now:
https://github.com/starkware-libs/cairo/actions/runs/10958733543

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, 3 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6392)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1101 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6392#-O7ESGt7BTbv-9otV25T:-O7ESGt7BTbv-9otV25U:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/f97360447ab531e032efb94653c9b69e38ff8c32/crates/cairo-lang-parser/src/parser.rs#L1101)):*
> ```XML
>     /// # Returns:
>     /// `true` if the token is a relational or equality operator, otherwise `false`.
>     fn is_comperison_operator(&self, kind: SyntaxKind) -> bool {
> ```





_Suggestion:_
```XML
    fn is_comparison_operator(&self, kind: SyntaxKind) -> bool {
```
___
*[`crates/cairo-lang-parser/src/parser.rs` line 1154 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6392#-O7ERkIJ1XfLxG6L1uDR:-O7ERkIJ1XfLxG6L1uDS:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f97360447ab531e032efb94653c9b69e38ff8c32/crates/cairo-lang-parser/src/parser.rs#L1154)):*
> ```XML
>                     }
>                 }
>                 child_op = Some(self.peek().kind);
> ```





_Suggestion:_
```XML
                child_op = Some(current_op);
```

**Review by dean-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6392)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1101 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6392#-O7ESGt7BTbv-9otV25T:-O7EUCBZ19ejZwqYDury:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f97360447ab531e032efb94653c9b69e38ff8c32/crates/cairo-lang-parser/src/parser.rs#L1101)):*
> ```XML
>     /// # Returns:
>     /// `true` if the token is a relational or equality operator, otherwise `false`.
>     fn is_comperison_operator(&self, kind: SyntaxKind) -> bool {
> ```

Done.
___
*[`crates/cairo-lang-parser/src/parser.rs` line 1154 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6392#-O7ERkIJ1XfLxG6L1uDR:-O7EURsJEn9kTlzIFtMp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f97360447ab531e032efb94653c9b69e38ff8c32/crates/cairo-lang-parser/src/parser.rs#L1154)):*
> ```XML
>                     }
>                 }
>                 child_op = Some(self.peek().kind);
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6392)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/expr` line 79 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6392#-O7EVNlf6tmIHjjn_XbT:-O7EVNlf6tmIHjjn_XbU:b-eno3k2) ([raw file](https://github.com/starkware-libs/cairo/blob/f97360447ab531e032efb94653c9b69e38ff8c32/crates/cairo-lang-parser/src/parser_test_data/partial_trees/expr#L79)):*
> ```
> 
> //! > expected_diagnostics
> error: Consecutive math operators are not allowed: 'TerminalLT' followed by 'TerminalGT'
> ```

Should be comparison

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6392)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/expr` line 79 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6392#-O7EVX8-D7lCsUMKfswn:-O7EVX8-D7lCsUMKfswo:bn1xzt8) ([raw file](https://github.com/starkware-libs/cairo/blob/f97360447ab531e032efb94653c9b69e38ff8c32/crates/cairo-lang-parser/src/parser_test_data/partial_trees/expr#L79)):*
> ```
> 
> //! > expected_diagnostics
> error: Consecutive math operators are not allowed: 'TerminalLT' followed by 'TerminalGT'
> ```

Also, can you print the actual operators instead, or.only the names are possible?

**Review by orizi — COMMENTED** [review]
> Reviewed 8 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6392)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @dean-starkware, @Draggu, @gilbens-starkware, and @mkaput)

**Review by dean-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6392)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, and @orizi)

___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/expr` line 79 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6392#-O7EVX8-D7lCsUMKfswn:-O7IzS0t2h6lxc1xIcaz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f97360447ab531e032efb94653c9b69e38ff8c32/crates/cairo-lang-parser/src/parser_test_data/partial_trees/expr#L79)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Also, can you print the actual operators instead, or.only the names are possible?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/expr` line 79 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6392#-O7EVNlf6tmIHjjn_XbT:-O7Izbzs0AXuufl-VeIE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f97360447ab531e032efb94653c9b69e38ff8c32/crates/cairo-lang-parser/src/parser_test_data/partial_trees/expr#L79)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Should be comparison
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6392#-:-O7KTNKYChe2Wx40036R:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, @gilbens-starkware, and @mkaput)

**Review by dean-starkware — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6392#-:-O7N25S7B2lS5tA3yN6G:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, @gilbens-starkware, and @mkaput)

**Pull request merged**
