### PR TITLE
Print usage locations.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3679)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 8 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3679)* status: 8 of 13 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/fmt.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3679#-N_S_js598R4Fe4Z8AVS:-N_S_js598R4Fe4Z8AVT:b-nxq5s5) ([raw file](https://github.com/starkware-libs/cairo/blob/0187836a5109675c9cd3e6657fd88db8e06cdfb4/crates/cairo-lang-lowering/src/fmt.rs#L21)):*
> ```XML
>     pub db: &'db dyn LoweringGroup,
>     pub variables: &'db Arena<Variable>,
>     pub print_usage_location: bool,
> ```

as this is a formatter (used for printing, but not a printer exactly)



_Suggestion:_
```XML
include_usage_location
```
___
*[`crates/cairo-lang-lowering/src/fmt.rs` line 145 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3679#-N_Sa86i66reR3XjTRrU:-N_Sa86i66reR3XjTRrV:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/0187836a5109675c9cd3e6657fd88db8e06cdfb4/crates/cairo-lang-lowering/src/fmt.rs#L145)):*
> ```XML
>             write!(
>                 f,
>                 "/* {} */",
> ```

?



_Suggestion:_
```XML
 /* usage: `{}` */
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/fmt.rs` line 145 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3679#-N_Sa86i66reR3XjTRrU:-N_SaWG03z7cFJ9eKu2m:b-bywfcl) ([raw file](https://github.com/starkware-libs/cairo/blob/0187836a5109675c9cd3e6657fd88db8e06cdfb4/crates/cairo-lang-lowering/src/fmt.rs#L145)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

it is longer :(

Also I think we should remove the `/*` if we have to world `usage`

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3679)* status: 8 of 13 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/fmt.rs` line 145 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3679#-N_Sa86i66reR3XjTRrU:-N_SayCd5IdHiUYhhyx6:baiefol) ([raw file](https://github.com/starkware-libs/cairo/blob/0187836a5109675c9cd3e6657fd88db8e06cdfb4/crates/cairo-lang-lowering/src/fmt.rs#L145)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it is longer :(

Also I think we should remove the `/*` if we have to world `usage`
</blockquote></details>

i'm fine with it - the current one was kind confusing in the actual print IMO.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/fmt.rs` line 145 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3679#-N_Sa86i66reR3XjTRrU:-N_TPaDp2h5TqiQhfN1z:b-v5n5ji) ([raw file](https://github.com/starkware-libs/cairo/blob/0187836a5109675c9cd3e6657fd88db8e06cdfb4/crates/cairo-lang-lowering/src/fmt.rs#L145)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i'm fine with it - the current one was kind confusing in the actual print IMO.
</blockquote></details>

why is it confusing?

how come the var is not confusing?

you just need to get used to it.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 13 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3679#-:-N_TQldTCgIoZ9TeM2Cg:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/fmt.rs` line 145 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3679#-N_Sa86i66reR3XjTRrU:-N_TQMR23SidJCM5zfcz:b-de46i7) ([raw file](https://github.com/starkware-libs/cairo/blob/0187836a5109675c9cd3e6657fd88db8e06cdfb4/crates/cairo-lang-lowering/src/fmt.rs#L145)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why is it confusing?

how come the var is not confusing?

you just need to get used to it.
</blockquote></details>

because it wasn't in any sort of section - just a comment like section within something that isn't code.
i'm good with the new one.

**Pull request merged**
