### PR TITLE
Properly printing panics in the cairo runner.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6333)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/bin/cairo-run/src/main.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6333#-O5qXjdu2Rj-qa1UJfHw:-O5qXjdu2Rj-qa1UJfHx:biwggnw) ([raw file](https://github.com/starkware-libs/cairo/blob/55d45eb8954b4209a59c747a2bcc54e3d417138e/crates/bin/cairo-run/src/main.rs#L118)):*
> ```XML
>         cairo_lang_runner::RunResultValue::Panic(values) => {
>             print!("Run panicked with [");
>             let mut felts = values.into_iter();
> ```

Aren't we supposed to parse from end to start?



_Code quote:_
```XML
        let mut felts = values.into_iter();
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6333)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/bin/cairo-run/src/main.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6333#-O5qXjdu2Rj-qa1UJfHw:-O5qaEHn1bNy5MYpXzWn:b-xp0488) ([raw file](https://github.com/starkware-libs/cairo/blob/55d45eb8954b4209a59c747a2bcc54e3d417138e/crates/bin/cairo-run/src/main.rs#L118)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Aren't we supposed to parse from end to start?
</blockquote></details>

AFAIU - we should maybe read from end to start - but parse from start to end.
(as the bytearray markers appear before the data

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6333)* status: 0 of 1 files reviewed, all discussions resolved

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/bin/cairo-run/src/main.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6333#-O5qXjdu2Rj-qa1UJfHw:-O5qd6zkE_pbiVBUfAfC:bl8bh71) ([raw file](https://github.com/starkware-libs/cairo/blob/55d45eb8954b4209a59c747a2bcc54e3d417138e/crates/bin/cairo-run/src/main.rs#L118)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

AFAIU - we should maybe read from end to start - but parse from start to end.
(as the bytearray markers appear before the data
</blockquote></details>

do we want to implement that in the code?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/bin/cairo-run/src/main.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6333#-O5qXjdu2Rj-qa1UJfHw:-O5qd9Cm0sJY9rD-CUzp:b-lvptzs) ([raw file](https://github.com/starkware-libs/cairo/blob/55d45eb8954b4209a59c747a2bcc54e3d417138e/crates/bin/cairo-run/src/main.rs#L118)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

do we want to implement that in the code?
</blockquote></details>

Parse each entry from start to end but print the entries in reverse order?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6333)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`crates/bin/cairo-run/src/main.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6333#-O5qXjdu2Rj-qa1UJfHw:-O5qdi8sCTnmP_TrNvPR:bsu68kv) ([raw file](https://github.com/starkware-libs/cairo/blob/55d45eb8954b4209a59c747a2bcc54e3d417138e/crates/bin/cairo-run/src/main.rs#L118)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Parse each entry from start to end but print the entries in reverse order?
</blockquote></details>

possibly - in any case - we currently don't do it anywhere else.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6333#-:-O5r5bMF8ef-pUne_MXz:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Pull request merged**
