### PR TITLE
feat: saturating traits

### LINKED ISSUE #5614: feat: add `Saturating<Add/Sub/Mul>`
# Feature Request

**Describe the Feature Request**

Rather than using CheckedOps and doing `unwrap_or_default()` for sub, `unwrap_or(T::max())` for `add` and `mul`, we could add a `Saturating` trait that will perform the operation and return the bound if it is exceeded during the operation.

**Describe Preferred Solution**

Copy the way `ops::Checked` was done, except returning `0` or `MAX` instead of `None` when an overflow occur

**Related Code**

https://github.com/starkware-libs/cairo/blob/cc5d51a257846b3508c2c186d81ac4f027c6f5bb/corelib/src/num/traits/ops/checked.cairo
https://doc.rust-lang.org/std/primitive.u32.html#method.saturating_add

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

No

It can be done by OnlyDust contributor quite easely

### PR DESCRIPTION
**Pull request by enitrat**
Closes #5614

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5621)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5621)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @enitrat)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5621#-Ny_2PW777plddwBHc3A:-Ny_2PW777plddwBHc3B:buuspfc) (no related file):*
@gilbens-starkware @Tomer-StarkWare 

___

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5621)* status: 0 of 5 files reviewed, all discussions resolved

**Review by Tomer-StarkWare — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5621)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @enitrat)

**Review by Tomer-StarkWare — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5621)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @enitrat)

**Review by Tomer-StarkWare — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5621#-:-Ny_7KgH7yDxZyk22yvI:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @enitrat)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5621#-:-Ny_7CEkA0VVMHE2ANUv:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @enitrat)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5621)* status: all files reviewed, 1 unresolved discussion (waiting on @enitrat)

___
*[`corelib/src/integer.cairo` line 3166 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5621#-Ny_AV824fvwAPUNmJM_:-Ny_AV824fvwAPUNmJMa:b-otzwx4) ([raw file](https://github.com/starkware-libs/cairo/blob/88559d0badac2e678c957875ad3f78fc337c7254/corelib/src/integer.cairo#L3166)):*
> ```Cairo
> 
> /// SaturatingMul implementations
> impl U8SaturatingMul = core::num::traits::ops::saturating::overflow_based::TSaturatingMul<u8>;
> ```

As this isn't the doc of a syntax node.



_Suggestion:_
```Cairo
// SaturatingAdd implementations
impl U8SaturatingAdd = core::num::traits::ops::saturating::overflow_based::TSaturatingAdd<u8>;
impl U16SaturatingAdd = core::num::traits::ops::saturating::overflow_based::TSaturatingAdd<u16>;
impl U32SaturatingAdd = core::num::traits::ops::saturating::overflow_based::TSaturatingAdd<u32>;
impl U64SaturatingAdd = core::num::traits::ops::saturating::overflow_based::TSaturatingAdd<u64>;
impl U128SaturatingAdd = core::num::traits::ops::saturating::overflow_based::TSaturatingAdd<u128>;
impl U256SaturatingAdd = core::num::traits::ops::saturating::overflow_based::TSaturatingAdd<u256>;
impl I8SaturatingAdd = core::num::traits::ops::saturating::overflow_based::TSaturatingAdd<i8>;
impl I16SaturatingAdd = core::num::traits::ops::saturating::overflow_based::TSaturatingAdd<i16>;
impl I32SaturatingAdd = core::num::traits::ops::saturating::overflow_based::TSaturatingAdd<i32>;
impl I64SaturatingAdd = core::num::traits::ops::saturating::overflow_based::TSaturatingAdd<i64>;
impl I128SaturatingAdd = core::num::traits::ops::saturating::overflow_based::TSaturatingAdd<i128>;

// SaturatingSub implementations
impl U8SaturatingSub = core::num::traits::ops::saturating::overflow_based::TSaturatingSub<u8>;
impl U16SaturatingSub = core::num::traits::ops::saturating::overflow_based::TSaturatingSub<u16>;
impl U32SaturatingSub = core::num::traits::ops::saturating::overflow_based::TSaturatingSub<u32>;
impl U64SaturatingSub = core::num::traits::ops::saturating::overflow_based::TSaturatingSub<u64>;
impl U128SaturatingSub = core::num::traits::ops::saturating::overflow_based::TSaturatingSub<u128>;
impl U256SaturatingSub = core::num::traits::ops::saturating::overflow_based::TSaturatingSub<u256>;
impl I8SaturatingSub = core::num::traits::ops::saturating::overflow_based::TSaturatingSub<i8>;
impl I16SaturatingSub = core::num::traits::ops::saturating::overflow_based::TSaturatingSub<i16>;
impl I32SaturatingSub = core::num::traits::ops::saturating::overflow_based::TSaturatingSub<i32>;
impl I64SaturatingSub = core::num::traits::ops::saturating::overflow_based::TSaturatingSub<i64>;
impl I128SaturatingSub = core::num::traits::ops::saturating::overflow_based::TSaturatingSub<i128>;

// SaturatingMul implementations
impl U8SaturatingMul = core::num::traits::ops::saturating::overflow_based::TSaturatingMul<u8>;
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5621)* status: all files reviewed, 1 unresolved discussion (waiting on @enitrat)

**Review by enitrat — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5621)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi and @Tomer-StarkWare)

___
*[`corelib/src/integer.cairo` line 3166 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5621#-Ny_AV824fvwAPUNmJM_:-Ny_Izbz-RgzrbmuGx2d:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/88559d0badac2e678c957875ad3f78fc337c7254/corelib/src/integer.cairo#L3166)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

As this isn't the doc of a syntax node.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5621#-:-Ny_JITtCAYxOP_-rTfd:bnfp4nl)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @Tomer-StarkWare)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5621)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @enitrat)

**Pull request merged**
