### PR TITLE
Add compute_costs.rs with initial implementation.

### PR DESCRIPTION
**Pull request by liorgold2**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2783)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2783)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-utils/src/unordered_hash_map.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2783#-NSrQh6NADGy6E9u02RQ:-NSrQh6O4ecvhwoo41Ti:b-5ptv7x) ([raw file](https://github.com/starkware-libs/cairo/blob/ff16db11303d8cdd8b5d5b642fe0c2914b63dbd9/crates/cairo-lang-utils/src/unordered_hash_map.rs#L15)):*
> ```XML
>     /// Returns a reference to the value corresponding to the key.
>     ///
>     /// The key may be any borrowed form of the map's key type, but [`Hash`] and [`Eq`] on the
> ```

Why did you add []?
This sometimes breaks the doc build, so I want to make sure.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2783)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-gas/src/compute_costs.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2783#-NSsHq3z99apWBHvlNHJ:-NSsHq3z99apWBHvlNHK:b7q37oa) ([raw file](https://github.com/starkware-libs/cairo/blob/ff16db11303d8cdd8b5d5b642fe0c2914b63dbd9/crates/cairo-lang-sierra-gas/src/compute_costs.rs#L143)):*
> ```XML
>                 // The wallet value at the beginning of the statement is the maximal value
>                 // required by all the branches.
>                 CostType::max(branch_requirements.into_iter())
> ```

is it really? we do `branch_align` for this - so all branches should have the actual same values



_Code quote:_
```XML
 CostType::max(branch_requirements.into_iter())
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2783)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-gas/src/compute_costs.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2783#-NStRK8o7qKBiGAN_Kc_:-NStRK8o7qKBiGAN_Kca:b-a0ay2q) ([raw file](https://github.com/starkware-libs/cairo/blob/ff16db11303d8cdd8b5d5b642fe0c2914b63dbd9/crates/cairo-lang-sierra-gas/src/compute_costs.rs#L94)):*
> ```XML
>         match self.costs.get_mut(idx) {
>             Some(CostComputationStatus::InProgress) => {
>                 panic!("Found an unexpected cycle during cost computation.")
> ```

Is panic ok in this case? Or should it be `Err`?
___
*[`crates/cairo-lang-sierra-gas/src/compute_costs.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2783#-NSsHq3z99apWBHvlNHJ:-NStQyowAaUyQDWrBr5G:bbjho1x) ([raw file](https://github.com/starkware-libs/cairo/blob/ff16db11303d8cdd8b5d5b642fe0c2914b63dbd9/crates/cairo-lang-sierra-gas/src/compute_costs.rs#L143)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is it really? we do `branch_align` for this - so all branches should have the actual same values
</blockquote></details>

At this point in the computation branch_aligns are not known and treated as nops.
See the documentation of `wallet_at`.
So we take the maximum here, and later (next PR) we use it to determine the alignment of each branch.
___
*[`crates/cairo-lang-utils/src/unordered_hash_map.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2783#-NSrQh6NADGy6E9u02RQ:-NStRW0Y44w99O18dYVh:b-csii88) ([raw file](https://github.com/starkware-libs/cairo/blob/ff16db11303d8cdd8b5d5b642fe0c2914b63dbd9/crates/cairo-lang-utils/src/unordered_hash_map.rs#L15)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Why did you add []?
This sometimes breaks the doc build, so I want to make sure.
</blockquote></details>

This is taken from the documentation of `use std::hash::Hash;`.
`[]` makes it a clickable (link) in the output, so it's better than \`\` which just makes it look like code.
Thus `[]` also checks that it's a valid name so if you rename it you will remember to change the `[]` otherwise the CI will fail.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2783#-:-NStTZ6S9RQGCviqut7l:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
