### PR TITLE
Change fixed size array size to ConstValue and restrict the size to 2…

### PR DESCRIPTION
**Pull request by gilbens-starkware**
…^15.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5187)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5187)* status: 2 of 11 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 433 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5187#-Ns461K04p3bnqe5GKov:-Ns461K04p3bnqe5GKow:btvazqt) ([raw file](https://github.com/starkware-libs/cairo/blob/afab8a449af640ae15950d94506283ca5939ee94/crates/cairo-lang-semantic/src/types.rs#L433)):*
> ```XML
>                             value_as_const_value(db, get_usize_ty(db), &size).unwrap(),
>                         )))
>                     }
> ```

and move the warning to the type area so it would always work.



_Suggestion:_
```XML
                    // We only support fixed size arrays with sizes that are smaller than 2^15.
                    Some(size) if size <= BigInt::from(i16::MAX) => {
                        Ok(Some(db.intern_const_value(
                            value_as_const_value(db, get_usize_ty(db), &size).unwrap(),
                        )))
                    }
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 11 files at r1, 1 of 4 files at r2, 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5187)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 536 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5187#-Ns4JjQc2MgQcm1zDTv2:-Ns4JjQc2MgQcm1zDTv3:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2d0711449bc50fa441c8e0f1517f1a3396366622/crates/cairo-lang-semantic/src/types.rs#L536)):*
> ```XML
>                 .to_usize()
>                 .unwrap();
>             db.single_value_type(type_id)? || size == 0
> ```





_Suggestion:_
```XML
            db.single_value_type(type_id)? || matches!(db.lookup_intern_const_value(size), ConstValue::Int(value) if value.is_zero())
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5187)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1732 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5187#-Ns4KJK_5jpgsbAeNKsm:-Ns4KJK_5jpgsbAeNKsn:bhpgqbi) ([raw file](https://github.com/starkware-libs/cairo/blob/2d0711449bc50fa441c8e0f1517f1a3396366622/crates/cairo-lang-semantic/src/expr/compute.rs#L1732)):*
> ```XML
>         TypeLongId::Tuple(inner_tys) => inner_tys,
>         TypeLongId::FixedSizeArray { type_id: inner_ty, size } => {
>             let size = extract_matches!(ctx.db.lookup_intern_const_value(size), ConstValue::Int)
> ```

add a todo to extract and conform.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5187)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 536 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5187#-Ns4JjQc2MgQcm1zDTv2:-Ns7pfj06xLz0PfpZXtS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2d0711449bc50fa441c8e0f1517f1a3396366622/crates/cairo-lang-semantic/src/types.rs#L536)):*
> ```XML
>                 .to_usize()
>                 .unwrap();
>             db.single_value_type(type_id)? || size == 0
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1732 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5187#-Ns4KJK_5jpgsbAeNKsm:-Ns7uz6r-eFqeN8-s0mE:bb4ke01) ([raw file](https://github.com/starkware-libs/cairo/blob/2d0711449bc50fa441c8e0f1517f1a3396366622/crates/cairo-lang-semantic/src/expr/compute.rs#L1732)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add a todo to extract and conform.
</blockquote></details>

Not sure I understand, conform the pattern types?

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5187)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 534 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5187#-Ns7zmM14UPRiWb_PTM8:-Ns7zmM14UPRiWb_PTM9:b2ni2qw) ([raw file](https://github.com/starkware-libs/cairo/blob/f6c394d26bc43791c39fd7850010cd7c21514e70/crates/cairo-lang-semantic/src/types.rs#L534)):*
> ```XML
>         semantic::TypeLongId::FixedSizeArray { type_id, size } => {
>             db.single_value_type(type_id)?
>                 || matches!(db.lookup_intern_const_value(size), ConstValue::Int(value) if value.is_zero())
> ```

fmt
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1732 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5187#-Ns4KJK_5jpgsbAeNKsm:-Ns7zpSzB4lEmTHjSCnz:bls5lqy) ([raw file](https://github.com/starkware-libs/cairo/blob/2d0711449bc50fa441c8e0f1517f1a3396366622/crates/cairo-lang-semantic/src/expr/compute.rs#L1732)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Not sure I understand, conform the pattern types?
</blockquote></details>

discussed f2f.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5187)* status: 7 of 11 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 534 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5187#-Ns7zmM14UPRiWb_PTM8:-Ns8CPSPBs7BfyBXRhsV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f6c394d26bc43791c39fd7850010cd7c21514e70/crates/cairo-lang-semantic/src/types.rs#L534)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fmt
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1732 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5187#-Ns4KJK_5jpgsbAeNKsm:-Ns8CC3y8upvTEeQ5xDv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2d0711449bc50fa441c8e0f1517f1a3396366622/crates/cairo-lang-semantic/src/expr/compute.rs#L1732)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

discussed f2f.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5187)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/fixed_size_array` line 38 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5187#-Ns8Dm-YAEg3E8kp_fAS:-Ns8Dm-YAEg3E8kp_fAT:buzc583) ([raw file](https://github.com/starkware-libs/cairo/blob/d2f097e21ca996e0376a02b76c717c19555af474/crates/cairo-lang-semantic/src/expr/test_data/fixed_size_array#L38)):*
> ```
> 
> //! > module_code
> const SIZE: usize = 3;
> ```

unused.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5187)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/fixed_size_array` line 38 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5187#-Ns8Dm-YAEg3E8kp_fAS:-Ns8EFZYAxTwb1_072fv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d2f097e21ca996e0376a02b76c717c19555af474/crates/cairo-lang-semantic/src/expr/test_data/fixed_size_array#L38)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

unused.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5187#-:-Ns8ENza5q1T1AD7sbDw:bnfp4nl)* status: 10 of 11 files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5187)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
