### PR TITLE
Bugfix - dups of literals

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2143)

### CODE REVIEW

**Review by ilyalesokhin-starkware — DISMISSED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2143)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @liorgold2, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/literals` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2143#-NOK5T9C6QyJdJ-74d-X:-NOK5T9C6QyJdJ-74d-Y:bv0jsv2) ([raw file](https://github.com/starkware-libs/cairo/blob/5f024d2094060dac044f2a8834598d7fb3c67851/crates/cairo-lang-sierra-generator/src/function_generator_test_data/literals#L42)):*
> ```
> 
> //! > comment
> When fixing this test, Make sure that the added dups are on the const, and not the temps.
> ```

It is not obvious to me that this is what you want to do.

is the goal to avoid locals?



_Code quote:_
```
Make sure that the added dups are on the const, and not the temps.
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2143)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware, @liorgold2, and @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/literals` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2143#-NOK5T9C6QyJdJ-74d-X:-NOK7CTv-cQJZWMYJSuI:b-wdslm1) ([raw file](https://github.com/starkware-libs/cairo/blob/5f024d2094060dac044f2a8834598d7fb3c67851/crates/cairo-lang-sierra-generator/src/function_generator_test_data/literals#L42)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

It is not obvious to me that this is what you want to do.

is the goal to avoid locals?
</blockquote></details>

Yes, but mainly to avoid panics. Before this fix, locals were not generated, the dups happened on the tempvar, and then they were revoked, but the revoking mechanism didnt see them as revokable, since they are constant.

When changing to locals we get another issue with uninitialized things beings unused (plus, it's less optimized).

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2143#-:-NOKDbvV7tvKQQKEsMxb:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware, @liorgold2, and @spapinistarkware)

___
*[`corelib/test.cairo` line 874 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2143#-NOKDM3c2AP9jrPcp2fl:-NOKDM3c2AP9jrPcp2fm:b7v8ziw) ([raw file](https://github.com/starkware-libs/cairo/blob/5f024d2094060dac044f2a8834598d7fb3c67851/corelib/test.cairo#L874)):*
> ```Cairo
> 
> #[test]
> fn test_bug_test() {
> ```

These tests generally should test the library logics, but if it's here, it should at least have a deceptive name

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2143)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware, @liorgold2, and @orizi)

___
*[`corelib/test.cairo` line 874 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2143#-NOKDM3c2AP9jrPcp2fl:-NOKMYVG1TxL8GeHbNqP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5f024d2094060dac044f2a8834598d7fb3c67851/corelib/test.cairo#L874)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

These tests generally should test the library logics, but if it's here, it should at least have a deceptive name
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2143)* status: 4 of 8 files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @orizi)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2143)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @orizi)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2143#-:-NOKUpMl-6Tdz6B7TCL6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2143)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
