### PR TITLE
Small fixes for empty enum variant syntax

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3640)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3640)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser_test_data/enum` line 23 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3640#-NZzzyq139MEwpr-VoO1:-NZzzyq2CJkbYwaKh6sI:b182sv7) ([raw file](https://github.com/starkware-libs/cairo/blob/6d36d4cb1a081b9b811377a5131bfdc6dbf13144/crates/cairo-lang-parser/src/parser_test_data/enum#L23)):*
> ```
>  --> dummy_file.cairo:3:16
>     B: (felt252),
>                ^
> ```

is this already tested somewhere else?



_Code quote:_
```
error: Missing token TokenComma.
 --> dummy_file.cairo:3:16
    B: (felt252),
               ^
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3640)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3640)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-parser/src/parser_test_data/enum` line 23 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3640#-NZzzyq139MEwpr-VoO1:-N_8z0bmBPfu9kpTwoIy:b4coqqs) ([raw file](https://github.com/starkware-libs/cairo/blob/6d36d4cb1a081b9b811377a5131bfdc6dbf13144/crates/cairo-lang-parser/src/parser_test_data/enum#L23)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is this already tested somewhere else?
</blockquote></details>

Not sure, but it's not the purpose here. It was changed in the empty-variant PR from an invalid (Rust) syntax (`B(felt252)`).

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3640)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser_test_data/enum` line 23 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3640#-NZzzyq139MEwpr-VoO1:-N_9-OF6C0bCZhwr00Na:b-gme3y) ([raw file](https://github.com/starkware-libs/cairo/blob/6d36d4cb1a081b9b811377a5131bfdc6dbf13144/crates/cairo-lang-parser/src/parser_test_data/enum#L23)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Not sure, but it's not the purpose here. It was changed in the empty-variant PR from an invalid (Rust) syntax (`B(felt252)`).
</blockquote></details>

oh - if so - revert it to the previous format that makes sure this fails.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3640)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-parser/src/parser_test_data/enum` line 23 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3640#-NZzzyq139MEwpr-VoO1:-N_Tm3CNE0PiccAo-5MK:b-74r6cc) ([raw file](https://github.com/starkware-libs/cairo/blob/6d36d4cb1a081b9b811377a5131bfdc6dbf13144/crates/cairo-lang-parser/src/parser_test_data/enum#L23)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

This is too many diagnostics that distract from the real purpose of the test. It could be tested in a separate test, but I don't see the point. We don't test for infinite number of syntaxes we don't support.
</blockquote></details>

Added in a separate file

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3640#-:-N_Tnets901JbQhS0jnI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
