### PR TITLE
Added basic cairo-prove binary.

### PR DESCRIPTION
**Pull request by orizi**

### CODE REVIEW

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6710)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`Cargo.toml` line 71 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6710#-OCCeMk37yh6VrnRE3my:-OCCeMk37yh6VrnRE3mz:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/65847311a5a86908410584680662babce17f1073/Cargo.toml#L71)):*
> ```TOML
>     "crates/bin/get-lowering",
>     "crates/bin/starknet-sierra-upgrade-validate",
>     "tests", "crates/bin/cairo-prove",
> ```





_Suggestion:_
```TOML
    "crates/bin/cairo-language-server",
    "crates/bin/cairo-run",
    "crates/bin/cairo-test",
    "crates/bin/generate-syntax",
    "crates/bin/cairo-prove",
    "crates/bin/sierra-compile",
    "crates/bin/starknet-compile",
    "crates/bin/starknet-sierra-compile",
    "crates/bin/starknet-sierra-extract-code",
    "crates/bin/get-lowering",
    "crates/bin/starknet-sierra-upgrade-validate",
    "tests",
```

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6710)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/bin/cairo-prove/Cargo.toml` line 15 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6710#-OCCgpRW6qkiG6bgYyQC:-OCCgpRW6qkiG6bgYyQD:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/65847311a5a86908410584680662babce17f1073/crates/bin/cairo-prove/Cargo.toml#L15)):*
> ```TOML
> cairo-lang-runner = { path = "../../cairo-lang-runner", version = "~2.8.5" }
> cairo-lang-compiler = { path = "../../cairo-lang-compiler", version = "~2.8.5" }
> cairo-lang-runnable = { path = "../../cairo-lang-runnable", version = "~2.8.5" }
> ```





_Suggestion:_
```TOML

cairo-lang-compiler = { path = "../../cairo-lang-compiler", version = "~2.8.5" }
cairo-lang-runnable = { path = "../../cairo-lang-runnable", version = "~2.8.5" }
cairo-lang-runner = { path = "../../cairo-lang-runner", version = "~2.8.5" }
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6710)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`Cargo.toml` line 71 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6710#-OCCeMk37yh6VrnRE3my:-OCCsizS6fq1vkuyDM2E:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/65847311a5a86908410584680662babce17f1073/Cargo.toml#L71)):*
> ```TOML
>     "crates/bin/get-lowering",
>     "crates/bin/starknet-sierra-upgrade-validate",
>     "tests", "crates/bin/cairo-prove",
> ```

Done.
___
*[`crates/bin/cairo-prove/Cargo.toml` line 15 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6710#-OCCgpRW6qkiG6bgYyQC:-OCD3Hf45b4nFi0nlz5N:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/65847311a5a86908410584680662babce17f1073/crates/bin/cairo-prove/Cargo.toml#L15)):*
> ```TOML
> cairo-lang-runner = { path = "../../cairo-lang-runner", version = "~2.8.5" }
> cairo-lang-compiler = { path = "../../cairo-lang-compiler", version = "~2.8.5" }
> cairo-lang-runnable = { path = "../../cairo-lang-runnable", version = "~2.8.5" }
> ```

Done.

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6710)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/bin/cairo-prove/src/main.rs` line 50 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6710#-OCT3OloEIpedWlk__ee:-OCT3OloEIpedWlk__ef:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/1c1c5941b74be656b07ccfc33c77bf4f614de53b/crates/bin/cairo-prove/src/main.rs#L50)):*
> ```XML
>     #[clap(long, value_parser, value_hint=ValueHint::FilePath)]
>     memory_file: Option<PathBuf>,
>     /// When using dynamic layout, it's parameters must be specified through a layout params file.
> ```





_Suggestion:_
```XML
/// When using dynamic layout, its parameters must be specified through a layout params file.
```
___
*[`crates/bin/cairo-prove/src/main.rs` line 63 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6710#-OCT3hXL0f0gh891Hp2C:-OCT3hXL0f0gh891Hp2D:b-2uc5zm) ([raw file](https://github.com/starkware-libs/cairo/blob/1c1c5941b74be656b07ccfc33c77bf4f614de53b/crates/bin/cairo-prove/src/main.rs#L63)):*
> ```XML
>     #[clap(long)]
>     secure_run: Option<bool>,
>     /// The resulting air public input file.
> ```

Same below



_Suggestion:_
```XML
/// The resulting AIR public input file.
```
___
*[`crates/bin/cairo-prove/src/main.rs` line 69 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6710#-OCT3nh5DAV69oqHUyM4:-OCT3nh5DAV69oqHUyM5:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/1c1c5941b74be656b07ccfc33c77bf4f614de53b/crates/bin/cairo-prove/src/main.rs#L69)):*
> ```XML
>     #[clap(long, requires_all = ["proof_mode", "trace_file", "memory_file"])]
>     air_private_input: Option<PathBuf>,
>     /// The resulting cairo pie file.
> ```





_Suggestion:_
```XML
/// The resulting cairo PIE file.
```

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 1 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6710)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
