### PR TITLE
Added a pop front array command.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:21900494

---

**Stack**:
- #1508
- #1504
- #1503 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1503#-:-NKHZO_Q7tOIC60404v8:bnfp4nl)* status: 5 of 9 files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 4 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1503)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1503)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/sierra/src/simulation/core.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1503#-NKHm2lI6RTAK6OGhGRn:-NKHm2lI6RTAK6OGhGRo:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/4c6201c528fbb8711fc820c19c2cd8ca1f581055/crates/sierra/src/simulation/core.rs#L130)):*
> ```XML
>                 }
>             }
>             [_, _] => Err(LibFuncSimulationError::MemoryLayoutMismatch),
> ```





_Suggestion:_
```XML
[_] => 
```
___
*[`crates/sierra/src/simulation/core.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1503#-NKHmHXHAaHMiZbXGp4v:-NKHmHXIByCPuxG2iU6r:bdgfutz) ([raw file](https://github.com/starkware-libs/cairo/blob/4c6201c528fbb8711fc820c19c2cd8ca1f581055/crates/sierra/src/simulation/core.rs#L130)):*
> ```XML
>                 }
>             }
>             [_, _] => Err(LibFuncSimulationError::MemoryLayoutMismatch),
> ```

Shouldn't it be WrongArgType?



_Code quote:_
```XML
MemoryLayoutMismatch
```
___
*[`crates/sierra_to_casm/src/invocations/array.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1503#-NKHpDDsDOywbPED3SNH:-NKHpDDsDOywbPED3SNI:b-79egy0) ([raw file](https://github.com/starkware-libs/cairo/blob/4c6201c528fbb8711fc820c19c2cd8ca1f581055/crates/sierra_to_casm/src/invocations/array.rs#L76)):*
> ```XML
>     casm_build_extend! {casm_builder,
>         tempvar is_empty = arr_end - arr_start;
>         jump Failure if is_empty != 0;
> ```

This should be the other way around - array is empty (failure) if is_empty == 0. Maybe better to change the name of is_empty -> length/size or similar

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 2 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1503)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1503)* status: 5 of 9 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`crates/sierra/src/simulation/core.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1503#-NKHm2lI6RTAK6OGhGRn:-NKHqhse1Z7DZz1XTjui:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4c6201c528fbb8711fc820c19c2cd8ca1f581055/crates/sierra/src/simulation/core.rs#L130)):*
> ```XML
>                 }
>             }
>             [_, _] => Err(LibFuncSimulationError::MemoryLayoutMismatch),
> ```

Done.
___
*[`crates/sierra/src/simulation/core.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1503#-NKHmHXHAaHMiZbXGp4v:-NKHqiA97y86FPMQ-mju:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4c6201c528fbb8711fc820c19c2cd8ca1f581055/crates/sierra/src/simulation/core.rs#L130)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Shouldn't it be WrongArgType?
</blockquote></details>

Done.
___
*[`crates/sierra_to_casm/src/invocations/array.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1503#-NKHpDDsDOywbPED3SNH:-NKHqjJU2xkQODhNApmw:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4c6201c528fbb8711fc820c19c2cd8ca1f581055/crates/sierra_to_casm/src/invocations/array.rs#L76)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

This should be the other way around - array is empty (failure) if is_empty == 0. Maybe better to change the name of is_empty -> length/size or similar
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1503)* status: all files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1503)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
