### PR TITLE
Removed block_id from lowered representations

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2263)

### CODE REVIEW

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2263)* status: 0 of 16 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 347 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2263#-NOzS8lL4bM68Z3EG-G3:-NOzS8lM8hiv8WEmMjaR:blq7ya0) ([raw file](https://github.com/starkware-libs/cairo/blob/6ecdfa8775223397274540e08cfcd73bd4e130ad/crates/cairo-lang-lowering/src/inline/mod.rs#L347)):*
> ```XML
>         }
> 
>         let root = if rewriter.inlining_failed { Err(skip_diagnostic()) } else { Ok(orig_root) };
> ```

@ilyalesokhin-starkware,

The only place where self.inlining_failed was uses is in get_function_code in an indirect way (root block was Err so it returned Err instead of getting the function code). I don't understnad why that makes sense - in other places the fact that inlining failed was treated softly.
Do you think we still need `inlining_failed`? If so - where? And in that case, I suggest to add such a bollean to FlatLowered or find another way to propagate it.
WDYT?

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2263)* status: 0 of 16 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2263#-NOznBks2bDnxNp_TFhm:-NOznBks2bDnxNp_TFhn:b-3yf84a) (no related file):*
change target branch

___

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2263)* status: 0 of 16 files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/objects.rs` line 36 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2263#-NOzr37l3puJFUiHqNsD:-NOzr37l3puJFUiHqNsE:bemvw77) ([raw file](https://github.com/starkware-libs/cairo/blob/c1321112b36feae437428635daad4257b1b7326b/crates/cairo-lang-lowering/src/objects.rs#L36)):*
> ```XML
>     /// Arena of allocated lowered variables.
>     pub variables: Arena<Variable>,
>     /// Arena of allocated lowered blocks.
> ```

why not make it a Maybe?



_Code quote:_
```XML
    /// Arena of allocated lowered blocks. Empty if an error prevented it from being computed.
    pub blocks: StructuredBlocks,
```
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 347 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2263#-NOzS8lL4bM68Z3EG-G3:-NOzrQmvAq0MK7krelSJ:b1vs9bl) ([raw file](https://github.com/starkware-libs/cairo/blob/6ecdfa8775223397274540e08cfcd73bd4e130ad/crates/cairo-lang-lowering/src/inline/mod.rs#L347)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

@ilyalesokhin-starkware,

The only place where self.inlining_failed was uses is in get_function_code in an indirect way (root block was Err so it returned Err instead of getting the function code). I don't understnad why that makes sense - in other places the fact that inlining failed was treated softly.
Do you think we still need `inlining_failed`? If so - where? And in that case, I suggest to add such a bollean to FlatLowered or find another way to propagate it.
WDYT?

</blockquote></details>

I added it because we had functions with
#[inline(always)] that weren't inlined.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2263)* status: 0 of 16 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/objects.rs` line 36 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2263#-NOzr37l3puJFUiHqNsD:-NOzu0eP4e7nPCQ_cxDe:bg2os4k) ([raw file](https://github.com/starkware-libs/cairo/blob/c1321112b36feae437428635daad4257b1b7326b/crates/cairo-lang-lowering/src/objects.rs#L36)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why not make it a Maybe?
</blockquote></details>

Because there is no need. When would it be ok(vec![])?
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 347 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2263#-NOzS8lL4bM68Z3EG-G3:-NOzueCKAhxNq7QdCrih:b-4yzo9i) ([raw file](https://github.com/starkware-libs/cairo/blob/6ecdfa8775223397274540e08cfcd73bd4e130ad/crates/cairo-lang-lowering/src/inline/mod.rs#L347)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I added it because we had functions with
#[inline(always)] that weren't inlined.
</blockquote></details>

So can it be removed? Should we always be allow inline-always functions that failed inlining, only with added diagnostic?

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 12 of 16 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2263)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 347 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2263#-NOzS8lL4bM68Z3EG-G3:-NPBFGHm4edsWtlfQrw6:b-xnwmgi) ([raw file](https://github.com/starkware-libs/cairo/blob/6ecdfa8775223397274540e08cfcd73bd4e130ad/crates/cairo-lang-lowering/src/inline/mod.rs#L347)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

So can it be removed? Should we always be allow inline-always functions that failed inlining, only with added diagnostic?
</blockquote></details>

Maybe you should just return emtpy blocks vector when inlineing fails?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2263)* status: all files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/objects.rs` line 36 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2263#-NOzr37l3puJFUiHqNsD:-NPBG_Pr3VT5vfU_T1dm:btf564g) ([raw file](https://github.com/starkware-libs/cairo/blob/c1321112b36feae437428635daad4257b1b7326b/crates/cairo-lang-lowering/src/objects.rs#L36)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Because there is no need. When would it be ok(vec![])?
</blockquote></details>

Is an empty funciton impossible because it must include a return?

if it was possible you might want to have a way of differentiating between failure and an empty function.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2263)* status: 16 of 17 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/objects.rs` line 36 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2263#-NOzr37l3puJFUiHqNsD:-NPBkQ7eB8cjeR-vrMT6:b8v1y0v) ([raw file](https://github.com/starkware-libs/cairo/blob/c1321112b36feae437428635daad4257b1b7326b/crates/cairo-lang-lowering/src/objects.rs#L36)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Is an empty funciton impossible because it must include a return?

if it was possible you might want to have a way of differentiating between failure and an empty function.
</blockquote></details>

Every function has to have a root block.
I also added a test now for an empty function.
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 347 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2263#-NOzS8lL4bM68Z3EG-G3:-NPBluBZ4ljho35Y23-t:b-1aixqa) ([raw file](https://github.com/starkware-libs/cairo/blob/6ecdfa8775223397274540e08cfcd73bd4e130ad/crates/cairo-lang-lowering/src/inline/mod.rs#L347)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Maybe you should just return emtpy blocks vector when inlineing fails?
</blockquote></details>

That's what I did in the first place, but then the relevant test results changes to:
before inlining - no change, one block.
After inlining - No blocks.


As in this PR:
//! > Test inlining diagnostics for a recursive function.

//! > test_runner_name
test_function_inlining

//! > function
#[inline(always)]
fn foo(ref a: felt, b: felt) -> felt {
  foo(ref a, b);
  b
}

//! > function_name
foo

//! > module_code

//! > semantic_diagnostics

//! > lowering_diagnostics
error: Cannot inline a function that might call itself.
 --> lib.cairo:1:1
#[inline(always)]
^***************^

//! > before
blk0 (root):
Inputs: v0: core::felt, v1: core::felt
Statements:
  (v3: core::felt, v2: core::felt) <- test::foo(v0, v1)
End:
  Return(v3, v1)

//! > after
blk0 (root):
Inputs: v0: core::felt, v1: core::felt
Statements:
  (v3: core::felt, v2: core::felt) <- test::foo(v0, v1)
End:
  Return(v3, v1)


With returning empty blocks in case of failure, same besides empty "after":
//! > after

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 347 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2263#-NOzS8lL4bM68Z3EG-G3:-NPBoqFK9e6mU6yTKZpl:b-7d3r5n) ([raw file](https://github.com/starkware-libs/cairo/blob/6ecdfa8775223397274540e08cfcd73bd4e130ad/crates/cairo-lang-lowering/src/inline/mod.rs#L347)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

That's what I did in the first place, but then the relevant test results changes to:
before inlining - no change, one block.
After inlining - No blocks.


As in this PR:
//! > Test inlining diagnostics for a recursive function.

//! > test_runner_name
test_function_inlining

//! > function
#[inline(always)]
fn foo(ref a: felt, b: felt) -> felt {
  foo(ref a, b);
  b
}

//! > function_name
foo

//! > module_code

//! > semantic_diagnostics

//! > lowering_diagnostics
error: Cannot inline a function that might call itself.
 --> lib.cairo:1:1
#[inline(always)]
^***************^

//! > before
blk0 (root):
Inputs: v0: core::felt, v1: core::felt
Statements:
  (v3: core::felt, v2: core::felt) <- test::foo(v0, v1)
End:
  Return(v3, v1)

//! > after
blk0 (root):
Inputs: v0: core::felt, v1: core::felt
Statements:
  (v3: core::felt, v2: core::felt) <- test::foo(v0, v1)
End:
  Return(v3, v1)


With returning empty blocks in case of failure, same besides empty "after":
//! > after
</blockquote></details>

I think its ok to have no block in the output when you have diagnostics.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2263)* status: 14 of 17 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 347 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2263#-NOzS8lL4bM68Z3EG-G3:-NPBpQdH5eUPoH77uC1k:b20unbg) ([raw file](https://github.com/starkware-libs/cairo/blob/6ecdfa8775223397274540e08cfcd73bd4e130ad/crates/cairo-lang-lowering/src/inline/mod.rs#L347)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I think its ok to have no block in the output when you have diagnostics.
</blockquote></details>

OK - but it's not for any diagnostic. Only diagnostics in the inlining.
(A thought, not for this PR - Maybe we should consider separating the diagnostics in the different lowering phases?)
Anyway, for now - done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, 16 of 61 files at r5, 8 of 17 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2263)* status: 24 of 63 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2263)* status: 24 of 63 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`-- commits` line 7 at r8](https://reviewable.io/reviews/starkware-libs/cairo/2263#-NPBv9DS30gxa55tk7uz):*
this looks wrong



_Code quote:_
```
- 21aa2a0: Renamed `get_gas*` to `try_fetch_gas*`. (#2247)

- 86e38f9: Added get_available_gas libfunc. (#2248)

New commits in r6 on 26/02/2023 at 10:14:
- 6c78a86: Removed `success` from BorrowChecker (#2264)

New commits in r7 on 26/02/2023 at 10:14 by ilyalesokhin-starkware:
- cac78b4: Use the correct public_key in __validate_deploy__. (#2270)
```

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 9 of 17 files at r8, 46 of 46 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2263#-:-NPByO7d4c--Q30EkOp-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
