### PR TITLE
Added proper diags for bad starknet interfaces.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4085)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4085)* status: all files reviewed, 13 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4085#-NedLeRvB-vVFKSwOyax:-NedLeRw1BHC-IBJXXIn:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/eb484c66469e18a2e4dde7d4a70d2cf9191787e6/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L14)):*
> ```XML
> use super::{DEPRECATED_ABI_ATTR, INTERFACE_ATTR, STORE_TRAIT};
> 
> /// If the trait is annotated with ABI_ATTR, generate the relevant dispatcher logic.
> ```





_Suggestion:_
```XML
annotated with INTERFACE_ATTR, generate the relevant dispatcher logic.
```
___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4085#-NedJrAb2JiyKxCHgEdS:-NedJrAcADY7w69gEyg9:b-8s3rc0) ([raw file](https://github.com/starkware-libs/cairo/blob/eb484c66469e18a2e4dde7d4a70d2cf9191787e6/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L46)):*
> ```XML
>     };
>     let generic_params = trait_ast.generic_params(db);
>     let Some(single_generic_param) = (match &generic_params {
> ```

remove parens



_Code quote:_
```XML
(
```
___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4085#-NedLjAx7rIHmoPSODAB:-NedLjAx7rIHmoPSODAC:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/eb484c66469e18a2e4dde7d4a70d2cf9191787e6/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L61)):*
> ```XML
>             code: None,
>             diagnostics: vec![PluginDiagnostic {
>                 message: "ABIs must have exactly one generic param, which is a type.".to_string(),
> ```





_Suggestion:_
```XML
ge: "Starknet interfaces must have exactly one generic parameter, which is a type.".
```
___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4085#-NedNS4T62MkgTINwehh:-NedNS4T62MkgTINwehi:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/eb484c66469e18a2e4dde7d4a70d2cf9191787e6/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L94)):*
> ```XML
>                 let Some(self_param) = params.next() else {
>                     diagnostics.push(PluginDiagnostic {
>                         message: "ABI functions must have a `self` parameter.".to_string(),
> ```





_Suggestion:_
```XML
: "Starknet interface functions must have
```
___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4085#-NedMBeA66M3ll3kwjNB:-NedMBeA66M3ll3kwjNC:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/eb484c66469e18a2e4dde7d4a70d2cf9191787e6/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L101)):*
> ```XML
>                 if self_param.name(db).text(db) != "self" {
>                     diagnostics.push(PluginDiagnostic {
>                         message: "The `self` parameter must be named `self`.".to_string(),
> ```





_Suggestion:_
```XML
The first parameter
```
___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4085#-NedMV_k2wuA74eYx7B3:-NedMV_k2wuA74eYx7B4:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/eb484c66469e18a2e4dde7d4a70d2cf9191787e6/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L109)):*
> ```XML
>                     if !self_param.type_clause(db).ty(db).is_identifier(db, &single_generic_param) {
>                         diagnostics.push(PluginDiagnostic {
>                             message: "The `self` parameter type must match the generic param."
> ```





_Suggestion:_
```XML
message: "The type of the first parameter of an interface function must match the generic parameter of the interface trait."
```
___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4085#-NedN8AD7_c5LcsrF5E2:-NedN8AD7_c5LcsrF5E3:b-u5y9mo) ([raw file](https://github.com/starkware-libs/cairo/blob/eb484c66469e18a2e4dde7d4a70d2cf9191787e6/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L128)):*
> ```XML
>                         message: "The `self` parameter must either be a snapshot of the generic \
>                                   param or a `ref` to it."
>                             .to_string(),
> ```

This one fits the above 2 as well. You can reduce them to one place generating the diagnostic.



_Suggestion:_
```XML
                    diagnostics.push(PluginDiagnostic {
                        message: "The type of the first parameter of an interface function must be either a snapshot of the generic parameter of the interface trait, or a `ref` to it."
                            .to_string(),
```
___
*[`crates/cairo-lang-starknet/src/plugin/utils.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4085#-NedOrTbAGx37vDecCH1:-NedOrTbAGx37vDecCH2:bb7f2bf) ([raw file](https://github.com/starkware-libs/cairo/blob/eb484c66469e18a2e4dde7d4a70d2cf9191787e6/crates/cairo-lang-starknet/src/plugin/utils.rs#L8)):*
> ```XML
> use cairo_lang_utils::try_extract_matches;
> 
> pub trait ParamEx {
> ```

doc.
___
*[`crates/cairo-lang-starknet/src/plugin/utils.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4085#-NedOwg35O0G6FP6a5Sw:-NedOwg35O0G6FP6a5Sx:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/eb484c66469e18a2e4dde7d4a70d2cf9191787e6/crates/cairo-lang-starknet/src/plugin/utils.rs#L11)):*
> ```XML
>     /// Checks if the parameter is defined as a ref parameter.
>     fn is_ref_param(&self, db: &dyn SyntaxGroup) -> bool;
>     /// Checks if the parameter is defined as a ref parameter.
> ```





_Suggestion:_
```XML
 as a mutable parameter.
```
___
*[`crates/cairo-lang-starknet/src/plugin/utils.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4085#-NedP2-q71Ga8snhA9SN:-NedP2-q71Ga8snhA9SO:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/eb484c66469e18a2e4dde7d4a70d2cf9191787e6/crates/cairo-lang-starknet/src/plugin/utils.rs#L13)):*
> ```XML
>     /// Checks if the parameter is defined as a ref parameter.
>     fn is_mut_param(&self, db: &dyn SyntaxGroup) -> bool;
>     /// Extract snapshot type if the parameter is a snapshot parameter. Otherwise, returns None.
> ```





_Suggestion:_
```XML
/ Extracts the snapshot type if the parameter's type is a snapshot. Otherwise, returns None.
```
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 2492 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4085#-NedPrE38EFCg8YSuW2S:-NedPrE38EFCg8YSuW2T:bo7tdqo) ([raw file](https://github.com/starkware-libs/cairo/blob/eb484c66469e18a2e4dde7d4a70d2cf9191787e6/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L2492)):*
> ```
> trait IContract<T, S> {
>     fn foo(ref self: T, other: felt252) -> felt252;
> }
> ```

please add another interface (ok here) with 0 generic params, and an interface with a single impl generic param.



_Code quote:_
```
#[starknet::interface]
trait IContract<T, S> {
    fn foo(ref self: T, other: felt252) -> felt252;
}
```
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 2519 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4085#-NedQ9Ix71h9sJiJKUan:-NedQ9Ix71h9sJiJKUao:btkzflu) ([raw file](https://github.com/starkware-libs/cairo/blob/eb484c66469e18a2e4dde7d4a70d2cf9191787e6/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L2519)):*
> ```
> trait IContract<T> {
>     fn ref_bad_name(ref wrong_name: T, other: felt252) -> felt252;
>     fn snap_bad_name(wrong_name: @T, other: felt252) -> felt252;
> ```

please add another test with a function without parameters at all.

(BTW, ok by me to have all tests for bad function signatures in the same test, with a comment on each saying why it's bad / a good name saying it. It's a little easier for the reader with all the generated code here)
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 2779 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4085#-NedQPJLEaomK2edmCPD:-NedQPJLEaomK2edmCPE:bg6wk88) ([raw file](https://github.com/starkware-libs/cairo/blob/eb484c66469e18a2e4dde7d4a70d2cf9191787e6/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L2779)):*
> ```
> }
> 
> //! > expected_diagnostics
> ```

please move section to before generated code, as this is the important part of this test. same in others.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4085)* status: all files reviewed, 11 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4085#-NedJrAb2JiyKxCHgEdS:-Nedbk806dwtIPZDnuJm:bmbve3a) ([raw file](https://github.com/starkware-libs/cairo/blob/eb484c66469e18a2e4dde7d4a70d2cf9191787e6/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L46)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

remove parens
</blockquote></details>

Required, can't 'else' otherwise
___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4085#-NedLjAx7rIHmoPSODAB:-Nedxs-U5msva7Ud3rdC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/eb484c66469e18a2e4dde7d4a70d2cf9191787e6/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L61)):*
> ```XML
>             code: None,
>             diagnostics: vecPluginDiagnostic {
>                 message: "ABIs must have exactly one generic param, which is a type.".to_string(),
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 94 at r1 ([raw file](https://github.com/starkware-libs/cairo/blob/eb484c66469e18a2e4dde7d4a70d2cf9191787e6/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L94)):*
> ```XML
>                 let Some(self_param) = params.next() else {
>                     diagnostics.push(PluginDiagnostic {
>                         message: "ABI functions must have a `self` parameter.".to_string(),
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4085#-NedMBeA66M3ll3kwjNB:-Nedy0TR8r-i7RLuMwk5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/eb484c66469e18a2e4dde7d4a70d2cf9191787e6/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L101)):*
> ```XML
>                 if self_param.name(db).text(db) != "self" {
>                     diagnostics.push(PluginDiagnostic {
>                         message: "The `self` parameter must be named `self`.".to_string(),
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4085#-NedN8AD7_c5LcsrF5E2:-NedyiCs45FcjqWIIszZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/eb484c66469e18a2e4dde7d4a70d2cf9191787e6/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L128)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

This one fits the above 2 as well. You can reduce them to one place generating the diagnostic.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/utils.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4085#-NedOrTbAGx37vDecCH1:-Nedyp0f2Vh20Ya236Ex:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/eb484c66469e18a2e4dde7d4a70d2cf9191787e6/crates/cairo-lang-starknet/src/plugin/utils.rs#L8)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

doc.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/utils.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4085#-NedOwg35O0G6FP6a5Sw:-Nedyvi04DFUDsaD0OWA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/eb484c66469e18a2e4dde7d4a70d2cf9191787e6/crates/cairo-lang-starknet/src/plugin/utils.rs#L11)):*
> ```XML
>     /// Checks if the parameter is defined as a ref parameter.
>     fn is_ref_param(&self, db: &dyn SyntaxGroup) -> bool;
>     /// Checks if the parameter is defined as a ref parameter.
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/utils.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4085#-NedP2-q71Ga8snhA9SN:-Nedz-wnDh_PXvaBnMuT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/eb484c66469e18a2e4dde7d4a70d2cf9191787e6/crates/cairo-lang-starknet/src/plugin/utils.rs#L13)):*
> ```XML
>     /// Checks if the parameter is defined as a ref parameter.
>     fn is_mut_param(&self, db: &dyn SyntaxGroup) -> bool;
>     /// Extract snapshot type if the parameter is a snapshot parameter. Otherwise, returns None.
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 2492 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4085#-NedPrE38EFCg8YSuW2S:-NedzT3hBdhl3Obouq45:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/eb484c66469e18a2e4dde7d4a70d2cf9191787e6/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L2492)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

please add another interface (ok here) with 0 generic params, and an interface with a single impl generic param.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 2519 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4085#-NedQ9Ix71h9sJiJKUan:-Nedzbj15lfzyMnM54CK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/eb484c66469e18a2e4dde7d4a70d2cf9191787e6/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L2519)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

please add another test with a function without parameters at all.

(BTW, ok by me to have all tests for bad function signatures in the same test, with a comment on each saying why it's bad / a good name saying it. It's a little easier for the reader with all the generated code here)
</blockquote></details>

Done.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4085)* status: all files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 111 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4085#-NegJ_b9-zzvanJP_UJu:-NegJ_b9-zzvanJP_UJv:bbhclrz) ([raw file](https://github.com/starkware-libs/cairo/blob/6d61eacd72932d8774b74bcf563060379c2f74b9/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L111)):*
> ```XML
>                 const BAD_SELF_PARAM_TYPE_MESSAGE: &str =
>                     "The first parameter of an interface function must be a reference to the \
>                      generic parameter of the interface trait.";
> ```

or a snapshot of it.



_Code quote:_
```XML
eneric parameter of the interface trait.";
```
___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 130 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4085#-NegJdHI7GSUYILJrW8D:-NegJdHI7GSUYILJrW8E:brsathk) ([raw file](https://github.com/starkware-libs/cairo/blob/6d61eacd72932d8774b74bcf563060379c2f74b9/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L130)):*
> ```XML
>                 } else {
>                     diagnostics.push(PluginDiagnostic {
>                         message: "The `self` parameter must either be a snapshot of the generic \
> ```

BAD_SELF_PARAM_TYPE_MESSAGE
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 2467 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4085#-NegK0VYBMwPuNMvAbFH:-NegK0VYBMwPuNMvAbFI:b-c4u30p) ([raw file](https://github.com/starkware-libs/cairo/blob/6d61eacd72932d8774b74bcf563060379c2f74b9/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L2467)):*
> ```
> //! > cairo_code
> #[starknet::interface]
> trait IContract<T, S>;
> ```

leave only one generic



_Code quote:_
```
act<T, S>;
```
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 2470 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4085#-NegJs2L1NJMfUjsMuOx:-NegJs2L1NJMfUjsMuOy:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6d61eacd72932d8774b74bcf563060379c2f74b9/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L2470)):*
> ```
> 
> //! > expected_diagnostics
> error: Plugin diagnostic: ABIs without body are not supported.
> ```





_Suggestion:_
```
ic: Starknet interfaces without 
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4085)* status: all files reviewed, 5 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4085#-NedMV_k2wuA74eYx7B3:-Negl0Ni5dYrsIrck0jk:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/eb484c66469e18a2e4dde7d4a70d2cf9191787e6/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L109)):*
> ```XML
>                     if !self_param.type_clause(db).ty(db).is_identifier(db, &single_generic_param) {
>                         diagnostics.push(PluginDiagnostic {
>                             message: "The `self` parameter type must match the generic param."
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 111 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4085#-NegJ_b9-zzvanJP_UJu:-Negl1zj5UIYwWnaxvda:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6d61eacd72932d8774b74bcf563060379c2f74b9/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L111)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

or a snapshot of it.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 130 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4085#-NegJdHI7GSUYILJrW8D:-Negl2e684iwEfVkGo2E:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6d61eacd72932d8774b74bcf563060379c2f74b9/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L130)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

BAD_SELF_PARAM_TYPE_MESSAGE
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 2467 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4085#-NegK0VYBMwPuNMvAbFH:-Neglh3T49HC5jyocMJk:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6d61eacd72932d8774b74bcf563060379c2f74b9/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L2467)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

leave only one generic
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 2470 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4085#-NegJs2L1NJMfUjsMuOx:-Neglnaq8I_SfT-3DixO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6d61eacd72932d8774b74bcf563060379c2f74b9/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L2470)):*
> ```
> 
> //! > expected_diagnostics
> error: Plugin diagnostic: ABIs without body are not supported.
> ```

Done.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4085#-:-NehOpbb519-HhhjL2UQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
