### PR TITLE
Fix hint.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5698)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-runner/src/casm_run/circuit.rs` line 176 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5698#-NzO7B7DAD6QKQNCl3hu:-NzO7B7EC2MyLu3r8p_A:b-1fx9a2) ([raw file](https://github.com/starkware-libs/cairo/blob/035d10cad645ea47002d0ebf4f083076a5d5210e/crates/cairo-lang-runner/src/casm_run/circuit.rs#L176)):*
> ```XML
> pub(crate) fn invert_or_nullify(value: BigUint, modulus: &BigUint) -> (bool, BigUint) {
>     let ExtendedGcd::<_> { gcd, x, y: _ } =
>         value.to_bigint().unwrap().extended_gcd(&modulus.to_bigint().unwrap());
> ```

This fails in runtime for BigUint.



_Code quote:_
```XML
.extended_gcd
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5698)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-runner/src/casm_run/circuit.rs` line 91 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5698#-NzOLP7n847NHaqFX8HF:-NzOLP7n847NHaqFX8HG:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/035d10cad645ea47002d0ebf4f083076a5d5210e/crates/cairo-lang-runner/src/casm_run/circuit.rs#L91)):*
> ```XML
>                 let (success, res) = if self.modulus.is_one() {
>                     // if modulus is 1, we need to to fails as the builtin cannot prove that
>                     // 0 * 0 === 1 (module 1)
> ```





_Suggestion:_
```XML
                    // if modulus is 1, we need to fail as the builtin cannot prove that
                    // 0 * 0 === 1 (modulo 1)
```
___
*[`crates/cairo-lang-runner/src/casm_run/circuit.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5698#-NzOMX-hC1GjZmuHLcxj:-NzOMX-hC1GjZmuHLcxk:bggqr3s) ([raw file](https://github.com/starkware-libs/cairo/blob/035d10cad645ea47002d0ebf4f083076a5d5210e/crates/cairo-lang-runner/src/casm_run/circuit.rs#L174)):*
> ```XML
> ///
> /// If the value is invertible, returns (true, inverse), otherwise returns (false, nullifier).
> pub(crate) fn invert_or_nullify(value: BigUint, modulus: &BigUint) -> (bool, BigUint) {
> ```

is this just for the test?
if so - maybe just add a `circuit_test.rs` file and include it here?



_Code quote:_
```XML
pub(crate)
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5698)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/casm_run/circuit.rs` line 91 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5698#-NzOLP7n847NHaqFX8HF:-NzRRTry-_24xO6LAnq9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/035d10cad645ea47002d0ebf4f083076a5d5210e/crates/cairo-lang-runner/src/casm_run/circuit.rs#L91)):*
> ```XML
>                 let (success, res) = if self.modulus.is_one() {
>                     // if modulus is 1, we need to to fails as the builtin cannot prove that
>                     // 0 * 0 === 1 (module 1)
> ```

Done.
___
*[`crates/cairo-lang-runner/src/casm_run/circuit.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5698#-NzOMX-hC1GjZmuHLcxj:-NzRRV9DASnYjHWmKPeS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/035d10cad645ea47002d0ebf4f083076a5d5210e/crates/cairo-lang-runner/src/casm_run/circuit.rs#L174)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is this just for the test?
if so - maybe just add a `circuit_test.rs` file and include it here?
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5698)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
