### PR TITLE
added Iterator as associated impl in intoIter trait

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5868)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5868)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @Tomer-StarkWare and @TomerStarkware)

___
*[`corelib/src/iter/traits/iterator.cairo` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5868#-O09ecY12_PgI-f-LyoH:-O09ecY12_PgI-f-LyoI:bvs28k7) ([raw file](https://github.com/starkware-libs/cairo/blob/7f46c38c56d99272cbc847abbef485d655f48cdf/corelib/src/iter/traits/iterator.cairo#L14)):*
> ```Cairo
>     /// The iterator type that will be created.
>     type IntoIter;
>     impl IteratorImpl: Iterator<Self::IntoIter>;
> ```

other suggestions for name?



_Code quote:_
```Cairo
    impl IteratorImpl: Iterator<Self::IntoIter>;
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5868)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi and @Tomer-StarkWare)

___
*[`corelib/src/iter/traits/iterator.cairo` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5868#-O09ecY12_PgI-f-LyoH:-O0DJtvi7EPTQ3A1xpmY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7f46c38c56d99272cbc847abbef485d655f48cdf/corelib/src/iter/traits/iterator.cairo#L14)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

other suggestions for name?
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5868)* status: 5 of 13 files reviewed, all discussions resolved (waiting on @Tomer-StarkWare)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 11 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5868#-:-O0DLNhY2JCC8C3pyC_-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Tomer-StarkWare)

**Pull request merged**
