### PR TITLE
Doc storage module.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
**Stack**:
- #6055
- #6046 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6046)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6046)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, and @ilyalesokhin-starkware)

___
*[`corelib/src/starknet.cairo` line 73 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6046#-O2TzCmN9TlwTNwlLIlH:-O2TzCmN9TlwTNwlLIlI:bui2gwr) ([raw file](https://github.com/starkware-libs/cairo/blob/6dd1a809564de1e8669058628d8db65556aaf462/corelib/src/starknet.cairo#L73)):*
> ```Cairo
> 
> /// This module contains the storage-related types and traits for Cairo contracts. It provides
> /// abstractions for reading and writing to Starknet storage.
> ```

add a short example that shows that usage is actually simple.
___
*[`corelib/src/starknet.cairo` line 110 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6046#-O2TyqlJ9fF8-dzAezaf:-O2TyqlJ9fF8-dzAezag:b-8r7dmn) ([raw file](https://github.com/starkware-libs/cairo/blob/6dd1a809564de1e8669058628d8db65556aaf462/corelib/src/starknet.cairo#L110)):*
> ```Cairo
> /// indicates that the storage object is mutable, i.e., it was created from a `ref` contract state,
> /// and thus the object can be written to.
> // TODO(Gil): Move it inside the module when inner doc comments are supported.
> ```

Remove this - this is going to be true all around in any case.



_Code quote:_
```Cairo
// TODO(Gil): Move it inside the module when inner doc comments are supported.
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6046)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, and @ilyalesokhin-starkware)

___
*[`corelib/src/starknet.cairo` line 88 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6046#-O2TzKjbEFjMVzJcPzZQ:-O2TzKjbEFjMVzJcPzZR:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/6dd1a809564de1e8669058628d8db65556aaf462/corelib/src/starknet.cairo#L88)):*
> ```Cairo
> ///    a wrapper around a `HashState` instance, used to account for more values when computing the
> ///    address of the storage object. `StoragePath` instances can be updated with values coming from
> ///    two sources:
> ```

.



_Suggestion:_
```Cairo
/// 3. `StorageBase` members are then converted to `StoragePath` instances, which are essentially
///    a wrapper around a `HashState` instance, used to account for more values when computing the
///    address of the storage object. `StoragePath` instances can be updated with values coming from
///    two sources:
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6046)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ArielElp, @ilyalesokhin-starkware, and @orizi)

___
*[`corelib/src/starknet.cairo` line 73 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6046#-O2TzCmN9TlwTNwlLIlH:-O2U16B_CkDtASkwbXH8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6dd1a809564de1e8669058628d8db65556aaf462/corelib/src/starknet.cairo#L73)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add a short example that shows that usage is actually simple.
</blockquote></details>

Done.
___
*[`corelib/src/starknet.cairo` line 88 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6046#-O2TzKjbEFjMVzJcPzZQ:-O2U-RY46S8FfXfaEz15:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6dd1a809564de1e8669058628d8db65556aaf462/corelib/src/starknet.cairo#L88)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`corelib/src/starknet.cairo` line 110 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6046#-O2TyqlJ9fF8-dzAezaf:-O2U-R8A2lptZyPYLba-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6dd1a809564de1e8669058628d8db65556aaf462/corelib/src/starknet.cairo#L110)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Remove this - this is going to be true all around in any case.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6046)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp, @gilbens-starkware, and @ilyalesokhin-starkware)

___
*[`corelib/src/starknet.cairo` line 98 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6046#-O2U5BSF1uPsUewt9IT9:-O2U5BSGDKNyTuh_Gdmr:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/272773a7d5d442aa3128e08e7e9f3217a010c972/corelib/src/starknet.cairo#L98)):*
> ```Cairo
> ///     let c_value = self.c.entry(42).read(43);
> /// }
> ///  ```
> ```

?



_Suggestion:_
```Cairo
/// ```cairo
/// #[storage]
/// struct Storage {
///     a: felt252,
///     b: Map<felt252, felt52>,
///     c: Map<felt52, Map<felt52, felt52>>,
/// }
/// ```
/// The user can access the storage members `a` and `b` using the following code:
/// ```cairo
/// fn use_storage(self: @ContractState) {
///     let a_value = self.a.read();
///     // For a Map, the user can use the `entry` method to access the value at a specific key:
///     let b_value = self.b.entry(42).read();
///     // Or simply pass the key to the `read` method:
///     let b_value = self.b.read(42);
///     // Accessing a nested Map must be done using the `entry` method, either:
///     let c_value = self.c.entry(42).entry(43).read()
///     // Or:
///     let c_value = self.c.entry(42).read(43);
/// }
///  ```
```

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/starknet.cairo` line 107 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6046#-O2U5yTK6URwST5s9Ht7:-O2U5yTK6URwST5s9Ht8:ba9lfeq) ([raw file](https://github.com/starkware-libs/cairo/blob/272773a7d5d442aa3128e08e7e9f3217a010c972/corelib/src/starknet.cairo#L107)):*
> ```Cairo
> ///    backward compatibility) or `#[flat]`. `FlattenedStorage` is used to structure the storage
> ///    access; however, it does not affect the address of the storage object.
> /// 2. `StorageBase` members of a `FlattenedStorage` struct hold a single `felt252` value, which is
> ```

The size of FlattenedStorage is not 0? how can it hold members with felts?



_Code quote:_
```Cairo
FlattenedStorage
```

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/starknet.cairo` line 128 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6046#-O2U6joU3kuWKMDtEwQa:-O2U6joU3kuWKMDtEwQb:b2kccm0) ([raw file](https://github.com/starkware-libs/cairo/blob/272773a7d5d442aa3128e08e7e9f3217a010c972/corelib/src/starknet.cairo#L128)):*
> ```Cairo
> ///
> /// Each of the types mentioned above has a phantom generic type, which is the type of the stored
> /// object, carried through the whole life cycle of the storage object. This is done to
> ```

Isn't the stored object a real type?


if I have a felt252 in the storage? what is the phantom generic type?



_Code quote:_
```Cairo
/// Each of the types mentioned above has a phantom generic type, which is the type of the stored
/// object, carried through the whole life cycle of the storage object. This is done to
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6046)* status: all files reviewed, 3 unresolved discussions (waiting on @ArielElp, @ilyalesokhin-starkware, and @orizi)

___
*[`corelib/src/starknet.cairo` line 98 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6046#-O2U5BSF1uPsUewt9IT9:-O2U9b_11mfKVr4QqYQA:b-wblbdm) ([raw file](https://github.com/starkware-libs/cairo/blob/272773a7d5d442aa3128e08e7e9f3217a010c972/corelib/src/starknet.cairo#L98)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

Not according to Murek, he suggested using bare quotes .
___
*[`corelib/src/starknet.cairo` line 107 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6046#-O2U5yTK6URwST5s9Ht7:-O2UAGPoEpiALorJBAzN:b-yys7a5) ([raw file](https://github.com/starkware-libs/cairo/blob/272773a7d5d442aa3128e08e7e9f3217a010c972/corelib/src/starknet.cairo#L107)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

The size of FlattenedStorage is not 0? how can it hold members with felts?
</blockquote></details>

It is 0, it can be derefed into a struct containing the members, added an explanation
___
*[`corelib/src/starknet.cairo` line 128 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6046#-O2U6joU3kuWKMDtEwQa:-O2UAVEQ7HrfGQasK3JR:blffmyk) ([raw file](https://github.com/starkware-libs/cairo/blob/272773a7d5d442aa3128e08e7e9f3217a010c972/corelib/src/starknet.cairo#L128)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Isn't the stored object a real type?


if I have a felt252 in the storage? what is the phantom generic type?
</blockquote></details>

The generic type is `felt252`, it is "phantom" in the manner that it isn't used in the struct itself as a member, just as a generic type. This allows the generic type to also be real phantom types such as `Map`, but yes, maybe phantom type is not the correct term, any suggestions?

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6046)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ArielElp and @ilyalesokhin-starkware)

___
*[`corelib/src/starknet.cairo` line 98 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6046#-O2U5BSF1uPsUewt9IT9:-O2UBsZW03wnrUzLbCgJ:b2ni9bh) ([raw file](https://github.com/starkware-libs/cairo/blob/272773a7d5d442aa3128e08e7e9f3217a010c972/corelib/src/starknet.cairo#L98)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Not according to Murek, he suggested using bare quotes .
</blockquote></details>

ok.

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/starknet.cairo` line 83 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6046#-O2UZOS3E-GstG7pjRNM:-O2UZOS3E-GstG7pjRNN:b-fdprz3) ([raw file](https://github.com/starkware-libs/cairo/blob/e63517bed1e5e608639ab8c30eca561f13b111bd/corelib/src/starknet.cairo#L83)):*
> ```Cairo
> ///     b: Map<felt252, felt52>,
> ///     c: Map<felt52, Map<felt52, felt52>>,
> /// }
> ```

can you add struct with and without flat?



_Code quote:_
```Cairo
/// struct Storage {
///     a: felt252,
///     b: Map<felt252, felt52>,
///     c: Map<felt52, Map<felt52, felt52>>,
/// }
```

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/starknet.cairo` line 122 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6046#-O2UZlIX-kzlxPQyVtV7:-O2UZlIX-kzlxPQyVtV8:b-b34hpz) ([raw file](https://github.com/starkware-libs/cairo/blob/e63517bed1e5e608639ab8c30eca561f13b111bd/corelib/src/starknet.cairo#L122)):*
> ```Cairo
> ///       updating the hash state with the key or index of the collection member.
> /// 4. After finishing the updates, the `StoragePath` instance is finalized, resulting in a
> ///    `StoragePointer0Offset` instance, which is a pointer to the address of the storage object. If
> ```

Reading 0O is confusing in some fonts.



_Suggestion:_
```Cairo
StoragePointerOffset0
```

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/starknet.cairo` line 128 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6046#-O2U6joU3kuWKMDtEwQa:-O2U_phg3pkeVn8TgFrj:b-rbmmg6) ([raw file](https://github.com/starkware-libs/cairo/blob/272773a7d5d442aa3128e08e7e9f3217a010c972/corelib/src/starknet.cairo#L128)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

The generic type is `felt252`, it is "phantom" in the manner that it isn't used in the struct itself as a member, just as a generic type. This allows the generic type to also be real phantom types such as `Map`, but yes, maybe phantom type is not the correct term, any suggestions?
</blockquote></details>

why does it matter if they type is actually part of the struct or not?

also, is 
StorageBase generic in some stored type?

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6046)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ArielElp, @ilyalesokhin-starkware, and @orizi)

___
*[`corelib/src/starknet.cairo` line 128 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6046#-O2U6joU3kuWKMDtEwQa:-O2UvPCDCkH8_cVKF-m4:bct9tb8) ([raw file](https://github.com/starkware-libs/cairo/blob/272773a7d5d442aa3128e08e7e9f3217a010c972/corelib/src/starknet.cairo#L128)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why does it matter if they type is actually part of the struct or not?

also, is 
StorageBase generic in some stored type?
</blockquote></details>

It allows for real phantom types to be used as a generic arg for this type, but maybe it can be removed.

And StorageBase is generic in the type of the member, it can be the stored type, in the case of `a` where it will be `StorageBase<felt252>`, but in the case of `b` and `c` it will be generic in `Map<...>`, which is not the stored type, and only after calling `entry` we'll get a type generic in `felt252` and we'll have `read` and `write` as methods.
___
*[`corelib/src/starknet.cairo` line 83 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6046#-O2UZOS3E-GstG7pjRNM:-O2UxQr77OpP5L61LmsA:btdv9ar) ([raw file](https://github.com/starkware-libs/cairo/blob/e63517bed1e5e608639ab8c30eca561f13b111bd/corelib/src/starknet.cairo#L83)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

can you add struct with and without flat?
</blockquote></details>

I think it is more relevant in storage node, adding it there.
___
*[`corelib/src/starknet.cairo` line 122 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6046#-O2UZlIX-kzlxPQyVtV7:-O2UtDlWC8WRf6gOO3Qf:b5u5vfs) ([raw file](https://github.com/starkware-libs/cairo/blob/e63517bed1e5e608639ab8c30eca561f13b111bd/corelib/src/starknet.cairo#L122)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Reading 0O is confusing in some fonts.
</blockquote></details>

Maybe in a different PR.

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/starknet.cairo` line 117 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6046#-O2YHX2CBd-BFfjCEyU8:-O2YHX2CBd-BFfjCEyU9:b-us27au) ([raw file](https://github.com/starkware-libs/cairo/blob/2bfb8d310af4c4ed754703f129805312cde9e986/corelib/src/starknet.cairo#L117)):*
> ```Cairo
> ///     - Storage nodes, which are structs that represent another struct with all its members
> ///       in the storage, similar to `FlattenedStorage`. However, unlike `FlattenedStorage`, the
> ///       members of a storage node do affect the address of the storage object. See `StorageNode`
> ```

Not sure what you mean when you say that the the address of the storage object depends on its members,
did you mean that path to it effect its address?



_Suggestion:_
```Cairo
///       in the storage, similar to `FlattenedStorage`. However, unlike `FlattenedStorage`, the
///       path to the storage node does affect the address of the storage object. See `StorageNode`
```

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/starknet.cairo` line 133 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6046#-O2YKvEh12ziopw4IwV2:-O2YKvEh12ziopw4IwV3:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2bfb8d310af4c4ed754703f129805312cde9e986/corelib/src/starknet.cairo#L133)):*
> ```Cairo
> ///
> /// Each of the types mentioned above has a phantom generic type, which is the type of the stored
> /// object, carried through the whole life cycle of the storage object. This is done to
> ```





_Suggestion:_
```Cairo
/// The types mentioned above are generic in the stored object type. This is done to
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6046)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @ArielElp, @ilyalesokhin-starkware, and @orizi)

___
*[`corelib/src/starknet.cairo` line 117 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6046#-O2YHX2CBd-BFfjCEyU8:-O36ecB6DcJBsQUIJeax:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2bfb8d310af4c4ed754703f129805312cde9e986/corelib/src/starknet.cairo#L117)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Not sure what you mean when you say that the the address of the storage object depends on its members,
did you mean that path to it effect its address?
</blockquote></details>

Done.
___
*[`corelib/src/starknet.cairo` line 133 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6046#-O2YKvEh12ziopw4IwV2:-O36dzo807HOFvbd1DlI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2bfb8d310af4c4ed754703f129805312cde9e986/corelib/src/starknet.cairo#L133)):*
> ```Cairo
> ///
> /// Each of the types mentioned above has a phantom generic type, which is the type of the stored
> /// object, carried through the whole life cycle of the storage object. This is done to
> ```

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6046#-:-O36lGcM3ugWk-lgSyt4:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArielElp)

**Pull request merged**
