### PR TITLE
Handle consts segment in contract segmenetation.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4722)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4722)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @liorgold2)

___
*[`crates/cairo-lang-starknet/src/contract_segmentation.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4722#-NnEI2to2bHUwYNVThv4:-NnEI2to2bHUwYNVThv5:b-8c8w7l) ([raw file](https://github.com/starkware-libs/cairo/blob/8c3b08eeb05b29bf4d612af0b88f8aa370343bc6/crates/cairo-lang-starknet/src/contract_segmentation.rs#L37)):*
> ```XML
>     program: &Program,
>     cairo_program: &CairoProgram,
>     bytecode_len: usize,
> ```

this change makes it no clearer.

instead do this, and do the meaning.



_Suggestion:_
```XML
    instructions_bytecode_size: usize,
```
___
*[`crates/cairo-lang-starknet/src/contract_segmentation_test.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4722#-NnEIzoS1mKV5GO_hQoI:-NnEIzoS1mKV5GO_hQoJ:b-xcyxz2) ([raw file](https://github.com/starkware-libs/cairo/blob/8c3b08eeb05b29bf4d612af0b88f8aa370343bc6/crates/cairo-lang-starknet/src/contract_segmentation_test.rs#L9)):*
> ```XML
> /// Tests `find_functions_segments` returns the correct result.
> #[derive(Default)]
> struct FindFunctionsSegmentsTest;
> ```

merge and test by both.
no need for separate tester.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4722)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-starknet/src/contract_segmentation.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4722#-NnEI2to2bHUwYNVThv4:-NnEJiQK59AIvyYByPdz:b9y4mws) ([raw file](https://github.com/starkware-libs/cairo/blob/8c3b08eeb05b29bf4d612af0b88f8aa370343bc6/crates/cairo-lang-starknet/src/contract_segmentation.rs#L37)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this change makes it no clearer.

instead do this, and do the meaning.
</blockquote></details>

The `len -> size` is just for consistency throughout the file. Notice that it's not just the instructions, it includes all the assembled code, i.e. with the const segment. Do you still want this change?
___
*[`crates/cairo-lang-starknet/src/contract_segmentation_test.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4722#-NnEIzoS1mKV5GO_hQoI:-NnEZqh09rj9dF847SPR:b-uw9m4b) ([raw file](https://github.com/starkware-libs/cairo/blob/8c3b08eeb05b29bf4d612af0b88f8aa370343bc6/crates/cairo-lang-starknet/src/contract_segmentation_test.rs#L9)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

merge and test by both.
no need for separate tester.
</blockquote></details>

Done (with some minor changes to the existing tests to make the compilation succeed).

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4722)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-starknet/src/contract_segmentation.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4722#-NnEI2to2bHUwYNVThv4:-NnE_77vDktukt3raevZ:b7y3scw) ([raw file](https://github.com/starkware-libs/cairo/blob/8c3b08eeb05b29bf4d612af0b88f8aa370343bc6/crates/cairo-lang-starknet/src/contract_segmentation.rs#L37)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

The `len -> size` is just for consistency throughout the file. Notice that it's not just the instructions, it includes all the assembled code, i.e. with the const segment. Do you still want this change?
</blockquote></details>

Now, I see that you wrote `do the meaning` do you want the calculation of the instruction length to be outside this function?
Notice that it is used (as is) in `get_segment_lengths`

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4722)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-starknet/src/contract_segmentation.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4722#-NnEI2to2bHUwYNVThv4:-NnEhm1t7QlmY6WTz-S1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8c3b08eeb05b29bf4d612af0b88f8aa370343bc6/crates/cairo-lang-starknet/src/contract_segmentation.rs#L37)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

if so that's fine.
</blockquote></details>

Done.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4722)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-starknet/src/contract_segmentation_test.rs` line 21 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4722#-NnEiI8jEwLUvgdrm-zV:-NnF2Fhm1oMyDTIzcljV:b-l2wi0s) ([raw file](https://github.com/starkware-libs/cairo/blob/0b4d15a9782c48068107e992049c1705d6aa3829/crates/cairo-lang-starknet/src/contract_segmentation_test.rs#L21)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

split the test refactor to another PR.
currently i can't see any of the changes in the existing test.
</blockquote></details>

Done, I also moved the new tests there, so now the tests here are exactly the same as the old tests, just with the updated runner.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4722)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @liorgold2)

___
*[`crates/cairo-lang-starknet/src/contract_segmentation_test.rs` line 60 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4722#-NnF3pTO01mgqnzmtyMB:-NnF3pTO01mgqnzmtyMC:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d634e34c670a914a670e213f2011906f05ad2c3b/crates/cairo-lang-starknet/src/contract_segmentation_test.rs#L60)):*
> ```XML
>     test_bytecode_segment_lengths,
>     "src/contract_segmentation_test_data",
>     { find_functions_segments: "bytecode_segment_lengths" },
> ```





_Suggestion:_
```XML
    { find_segment: "find_segment" },
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4722)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-starknet/src/contract_segmentation_test.rs` line 60 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4722#-NnF3pTO01mgqnzmtyMB:-NnF6EM0BS-RJasmgxbW:b9usdob) ([raw file](https://github.com/starkware-libs/cairo/blob/d634e34c670a914a670e213f2011906f05ad2c3b/crates/cairo-lang-starknet/src/contract_segmentation_test.rs#L60)):*
> ```XML
>     test_bytecode_segment_lengths,
>     "src/contract_segmentation_test_data",
>     { find_functions_segments: "bytecode_segment_lengths" },
> ```

Change the name to `bytecode_segment_lengths`.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4722)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-starknet/src/contract_segmentation_test.rs` line 60 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4722#-NnF3pTO01mgqnzmtyMB:-NnIFGDLBsToPNmOnClO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d634e34c670a914a670e213f2011906f05ad2c3b/crates/cairo-lang-starknet/src/contract_segmentation_test.rs#L60)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i know. Don't - this makes this PR non-reviewable - for no reason.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r2, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4722#-:-NnIqN5BBAUOxenQS6uW:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
