### PR TITLE
Tomerc/changing semantic structure for loop

### PR DESCRIPTION
**Pull request by Tomer-StarkWare**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5916)

### CODE REVIEW

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5916)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi, @Tomer-StarkWare, and @TomerStarkware)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5916#-O0cB78383yaDkjovcTM):*
Make it one commit.



_Code quote:_
```
New commits in r1 on 30/06/2024 at 11:00:

- a6a46dc: changing-for-loop-semantics

- 885b115: changing for loop semantic
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5916#-:-O0cCuqV5aV2rQFt_1mw:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Tomer-StarkWare and @TomerStarkware)

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5916)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5916#-O0cB78383yaDkjovcTM):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Make it one commit.
</blockquote></details>

Done.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5916#-:-O0cP2_r8WO7i554ezx0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
