### PR TITLE
Allow merging local variable even if empty.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3352)

### CODE REVIEW

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3352)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3352#-:-NXdw1QU81N9q5h1tyvc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3352)* status: all files reviewed, 1 unresolved discussion

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 208 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3352#-NXeDzDWDirrWylVOPIm:-NXeDzDWDirrWylVOPIn:b-sedahb) ([raw file](https://github.com/starkware-libs/cairo/blob/6670973d86a988e34bb430c4e2e28521d86e5042/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L208)):*
> ```XML
>             if !(actual_ref.ty == expected_ref.ty
>                 && actual_ref.expression == expected_ref.expression
>                 && actual_ref.ap_independent_location_info
> ```

Can this be non-backward-compatible?

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3352)* status: all files reviewed, 2 unresolved discussions

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 276 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3352#-NXeEC9y4TjRBMNlpDT8:-NXeEC9y4TjRBMNlpDT9:b6dor0x) ([raw file](https://github.com/starkware-libs/cairo/blob/6670973d86a988e34bb430c4e2e28521d86e5042/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L276)):*
> ```XML
>                         })?,
>                     ty: ref_value.ty.clone(),
>                     ap_independent_location_info: match &ref_value.ap_independent_location_info {
> ```

Can `if matches!() && branch_changes.clear_old_stack` be more clear here?

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3352)* status: all files reviewed, 3 unresolved discussions

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 288 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3352#-NXeEVLd3EM02joNcMpw:-NXeEVLd3EM02joNcMpx:b8v6o4h) ([raw file](https://github.com/starkware-libs/cairo/blob/6670973d86a988e34bb430c4e2e28521d86e5042/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L288)):*
> ```XML
>             );
>         }
>         let mut refs = put_results(
> ```

Can you add a comment explaining what's done by `put_results()`?

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3352)* status: all files reviewed, 4 unresolved discussions

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 335 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3352#-NXeEuhL-GlDcTmlNcxI:-NXeEuhL-GlDcTmlNcxJ:b-il6sha) ([raw file](https://github.com/starkware-libs/cairo/blob/6670973d86a988e34bb430c4e2e28521d86e5042/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L335)):*
> ```XML
>             let stack_removal = branch_changes.new_stack_size - new_stack_size;
>             for r in refs.values_mut() {
>                 r.ap_independent_location_info = match &r.ap_independent_location_info {
> ```

```
if let ... {
    r.ap_independent_location_info = match stack_idx.checked_sub(stack_removal) { ... }
}
```

Also, consider replacing the inner `match` with something like `map_or_else`.

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3352)* status: all files reviewed, 5 unresolved discussions

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 338 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3352#-NXeFZlT16v6Nl6Pr5BM:-NXeFZlT16v6Nl6Pr5BN:bols8kh) ([raw file](https://github.com/starkware-libs/cairo/blob/6670973d86a988e34bb430c4e2e28521d86e5042/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L338)):*
> ```XML
>                     VariableApIndependentLocationInfo::ContinuousStack(stack_idx) => {
>                         // Subtract the number of stack elements removed. If the result is negative,
>                         // `stack_idx` is set to `None` and the variable is removed from the stack.
> ```

Update comment.

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3352)* status: all files reviewed, 5 unresolved discussions

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 335 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3352#-NXeEuhL-GlDcTmlNcxI:-NXeFfKq55R1n5m0ez6J:bd34ptl) ([raw file](https://github.com/starkware-libs/cairo/blob/6670973d86a988e34bb430c4e2e28521d86e5042/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L335)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

```
if let ... {
    r.ap_independent_location_info = match stack_idx.checked_sub(stack_removal) { ... }
}
```

Also, consider replacing the inner `match` with something like `map_or_else`.
</blockquote></details>

Consider refactoring this logic to a function of `anchor` (e.g. `reduce_stack_size()`).

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3352)* status: all files reviewed, 6 unresolved discussions

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 470 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3352#-NXeFqtl1c7RIcad48OL:-NXeFqtmE80QsuXdRkGI:b-aqvz9l) ([raw file](https://github.com/starkware-libs/cairo/blob/6670973d86a988e34bb430c4e2e28521d86e5042/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L470)):*
> ```XML
>     // We consider empty variables as ap-dependent since we don't know their actual
>     // source.
>     if !actual.expression.cells.is_empty() && actual.expression.can_apply_unknown() {
> ```

I expected the `is_empty` here to change (be removed?).

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3352)* status: all files reviewed, 6 unresolved discussions

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 470 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3352#-NXeFqtl1c7RIcad48OL:-NXeG7MP1CQ3QB45tcdf:b-pzx4qx) ([raw file](https://github.com/starkware-libs/cairo/blob/6670973d86a988e34bb430c4e2e28521d86e5042/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L470)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

I expected the `is_empty` here to change (be removed?).
</blockquote></details>

Or this entire `if`?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3352)* status: all files reviewed, 6 unresolved discussions

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 208 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3352#-NXeDzDWDirrWylVOPIm:-NXeETvt3-HNEjQRy4DM:betdkdr) ([raw file](https://github.com/starkware-libs/cairo/blob/6670973d86a988e34bb430c4e2e28521d86e5042/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L208)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Can this be non-backward-compatible?
</blockquote></details>

no - this is more permissive than before - this would only catch things that are now local.
so they were exactly at [fp + k] set, and previously were just None.
___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 276 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3352#-NXeEC9y4TjRBMNlpDT8:-NXeFTSu6qefcN4fX5sa:b-7u3o0x) ([raw file](https://github.com/starkware-libs/cairo/blob/6670973d86a988e34bb430c4e2e28521d86e5042/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L276)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Can `if matches!() && branch_changes.clear_old_stack` be more clear here?
</blockquote></details>

updated in the next pr.
___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 288 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3352#-NXeEVLd3EM02joNcMpw:-NXeFvcb6kXTrUaIXV7z:b-7u3o0x) ([raw file](https://github.com/starkware-libs/cairo/blob/6670973d86a988e34bb430c4e2e28521d86e5042/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L288)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Can you add a comment explaining what's done by `put_results()`?
</blockquote></details>

updated in the next pr.
___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 335 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3352#-NXeEuhL-GlDcTmlNcxI:-NXeG3CVBh0E3r4MXMzI:b-wtfykr) ([raw file](https://github.com/starkware-libs/cairo/blob/6670973d86a988e34bb430c4e2e28521d86e5042/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L335)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Consider refactoring this logic to a function of `anchor` (e.g. `reduce_stack_size()`).
</blockquote></details>

1. Done in next pr. (clippy complained there)
2. this does not sound to me like a functionality of anchor.
___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 338 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3352#-NXeFZlT16v6Nl6Pr5BM:-NXeGEtiATdvzK-9Znb2:b-7u3o0x) ([raw file](https://github.com/starkware-libs/cairo/blob/6670973d86a988e34bb430c4e2e28521d86e5042/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L338)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Update comment.
</blockquote></details>

updated in the next pr.
___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 470 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3352#-NXeFqtl1c7RIcad48OL:-NXeGHZlD03X6fuKDcc1:b-ft3038) ([raw file](https://github.com/starkware-libs/cairo/blob/6670973d86a988e34bb430c4e2e28521d86e5042/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L470)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Or this entire `if`?
</blockquote></details>

the fix is that now `local` versions of empty vars don't get to this stage - it is still required for regular `temp` empty vars.

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3352)* status: all files reviewed, 8 unresolved discussions

___
*[`crates/cairo-lang-sierra-to-casm/src/references.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3352#-NXeGRU58C9ZxJvB3yKH:-NXeGRU58C9ZxJvB3yKI:ba3mt7g) ([raw file](https://github.com/starkware-libs/cairo/blob/6670973d86a988e34bb430c4e2e28521d86e5042/crates/cairo-lang-sierra-to-casm/src/references.rs#L29)):*
> ```XML
> pub type StatementRefs = HashMap<VarId, ReferenceValue>;
> 
> /// Information about the location of a variable that is not dependent on the actual AP values.
> ```

This part is not clear, but I don't know how to phrase it better.



_Code quote:_
```XML
 that is not dependent on the actual AP values
```
___
*[`crates/cairo-lang-sierra-to-casm/src/references.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3352#-NXeGbrR3tTE5bMkzyDS:-NXeGbrR3tTE5bMkzyDT:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/6670973d86a988e34bb430c4e2e28521d86e5042/crates/cairo-lang-sierra-to-casm/src/references.rs#L37)):*
> ```XML
>     ContinuousStack(usize),
>     /// The variable was defined as a local variable. May be a function param, or an explicitly
>     /// defined local.
> ```





_Suggestion:_
```XML
    /// The variable was defined as a local variable. May be a function parameter, or an explicitly
    /// defined local.
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3352)* status: all files reviewed, 8 unresolved discussions

___
*[`crates/cairo-lang-sierra-to-casm/src/references.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3352#-NXeGRU58C9ZxJvB3yKH:-NXeGzFx4HyrRbTo3pg0:by36ofl) ([raw file](https://github.com/starkware-libs/cairo/blob/6670973d86a988e34bb430c4e2e28521d86e5042/crates/cairo-lang-sierra-to-casm/src/references.rs#L29)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

This part is not clear, but I don't know how to phrase it better.
</blockquote></details>

check again in the anchor PR maybe you'd like it more.
___
*[`crates/cairo-lang-sierra-to-casm/src/references.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3352#-NXeGbrR3tTE5bMkzyDS:-NXeHHZOEzM8po3jrQs_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6670973d86a988e34bb430c4e2e28521d86e5042/crates/cairo-lang-sierra-to-casm/src/references.rs#L37)):*
> ```XML
>     ContinuousStack(usize),
>     /// The variable was defined as a local variable. May be a function param, or an explicitly
>     /// defined local.
> ```

Done.

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3352)* status: all files reviewed, 11 unresolved discussions

___
*[`crates/cairo-lang-sierra-to-casm/src/references.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3352#-NXeGefF-1lBtOTMU8fe:-NXeGefF-1lBtOTMU8ff:bsou1ge) ([raw file](https://github.com/starkware-libs/cairo/blob/6670973d86a988e34bb430c4e2e28521d86e5042/crates/cairo-lang-sierra-to-casm/src/references.rs#L36)):*
> ```XML
>     /// element on the stack.
>     ContinuousStack(usize),
>     /// The variable was defined as a local variable. May be a function param, or an explicitly
> ```

What about deferred variable that depends only on a local var?
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs` line 201 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3352#-NXeH99kCLbEVnoLabVu:-NXeH99kCLbEVnoLabVv:bya1blr) ([raw file](https://github.com/starkware-libs/cairo/blob/6670973d86a988e34bb430c4e2e28521d86e5042/crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs#L201)):*
> ```XML
> }
> 
> /// Calculates the continuous stack index for an output var of a branch.
> ```

Fix comment.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs` line 219 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3352#-NXeHMiF-z4fBaDvj4Pg:-NXeHMiF-z4fBaDvj4Ph:bzbwl9e) ([raw file](https://github.com/starkware-libs/cairo/blob/6670973d86a988e34bb430c4e2e28521d86e5042/crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs#L219)):*
> ```XML
>         OutputVarReferenceInfo::SameAsParam { .. }
>         | OutputVarReferenceInfo::SimpleDerefs
>         | OutputVarReferenceInfo::PartialParam { .. }
> ```

Shouldn't partial param of local be local?

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3352)* status: all files reviewed, 12 unresolved discussions

___
*[`tests/bug_samples/issue3345.cairo` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3352#-NXeH_OrBzIowfqcXT0E:-NXeH_OrBzIowfqcXT0F:bdcpb3s) ([raw file](https://github.com/starkware-libs/cairo/blob/6670973d86a988e34bb430c4e2e28521d86e5042/tests/bug_samples/issue3345.cairo#L1)):*
> ```Cairo
> #[derive(Copy, Drop, storage_access::StorageAccess)]
> ```

Is this the smaller possible example?

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3352)* status: all files reviewed, 13 unresolved discussions

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/test_utils.rs` line 272 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3352#-NXeHl4XEw7sC9kYreA6:-NXeHl4XEw7sC9kYreA7:b-3y4znb) ([raw file](https://github.com/starkware-libs/cairo/blob/6670973d86a988e34bb430c4e2e28521d86e5042/crates/cairo-lang-sierra-to-casm/src/invocations/test_utils.rs#L272)):*
> ```XML
>             expression,
>             ty: param.ty.clone(),
>             ap_independent_location_info: VariableApIndependentLocationInfo::Other,
> ```

What happens here?

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3352)* status: all files reviewed, 13 unresolved discussions

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3352)* status: all files reviewed, 13 unresolved discussions

___
*[`crates/cairo-lang-sierra-to-casm/src/references.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3352#-NXeGefF-1lBtOTMU8fe:-NXeHiOa8rZ1rhsCTO7L:buf8usd) ([raw file](https://github.com/starkware-libs/cairo/blob/6670973d86a988e34bb430c4e2e28521d86e5042/crates/cairo-lang-sierra-to-casm/src/references.rs#L36)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

What about deferred variable that depends only on a local var?
</blockquote></details>

It would not be empty - and it would be allowed as ap-independent.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs` line 201 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3352#-NXeH99kCLbEVnoLabVu:-NXeHsyt6oa4yDwLP-mO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6670973d86a988e34bb430c4e2e28521d86e5042/crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs#L201)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Fix comment.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs` line 219 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3352#-NXeHMiF-z4fBaDvj4Pg:-NXeHwm4Dv0xHhc5PyAd:ba34lb0) ([raw file](https://github.com/starkware-libs/cairo/blob/6670973d86a988e34bb430c4e2e28521d86e5042/crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs#L219)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Shouldn't partial param of local be local?
</blockquote></details>

sounds correct - Done in next PR.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/test_utils.rs` line 272 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3352#-NXeHl4XEw7sC9kYreA6:-NXeJZYz4GhGNkaibk_1:b-xnrokn) ([raw file](https://github.com/starkware-libs/cairo/blob/6670973d86a988e34bb430c4e2e28521d86e5042/crates/cairo-lang-sierra-to-casm/src/invocations/test_utils.rs#L272)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

What happens here?
</blockquote></details>

this was logically None before - as this test was the libfunc test - no recompilability tests here.
___
*[`tests/bug_samples/issue3345.cairo` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3352#-NXeH_OrBzIowfqcXT0E:-NXeJid1BxR6qGHPSSwq:bk378tf) ([raw file](https://github.com/starkware-libs/cairo/blob/6670973d86a988e34bb430c4e2e28521d86e5042/tests/bug_samples/issue3345.cairo#L1)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Is this the smaller possible example?
</blockquote></details>

probably - any merge should fail, would attempt to add something in compiler_test.

**Pull request merged**
