### PR TITLE
Add int_range_pop_front libfunc.

### PR DESCRIPTION
**Pull request by liorgold2**
**Stack**:
- #6298
- #6289
- #6288
- #6286 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6286)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 7 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6286)* status: 7 of 10 files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6286#-O5ItyLyBaBLQS0AMq1H:-O5ItyLyBaBLQS0AMq1I:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/95ccbe1704aefde353ee4c51b8c44e698106ded7/crates/cairo-lang-sierra-to-casm/src/invocations/range.rs#L35)):*
> ```XML
>         NonEmpty:
>         const one = 1;
>         let new_start = start + one;
> ```





_Suggestion:_
```XML
        let new_start = start + one;
        const one = 1;
        tempvar is_non_empty = end - start;
        jump NonEmpty if is_non_empty != 0;
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6286#-O5IuAWI4jJnWfDmvzVd:-O5IuAWI4jJnWfDmvzVe:br16kdu) ([raw file](https://github.com/starkware-libs/cairo/blob/95ccbe1704aefde353ee4c51b8c44e698106ded7/crates/cairo-lang-sierra-to-casm/src/invocations/range.rs#L43)):*
> ```XML
>             ("Fallthrough", &[&[new_start, end], &[start]], None),
>             ("Failure", &[], Some(failure_handle)),
>         ],
> ```

and change the signature - will require an enum.
(we may consider adding in `core::internal::OptionReversed` just to help all the "upside-down" libfuncs)



_Suggestion:_
```XML
        [
            ("Fallthrough", &[], None),
            ("NonEmpty", &[&[new_start, end], &[start]], Some(non_empty_handle)),
        ],
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6286)* status: 4 of 10 files reviewed, 4 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra/src/extensions/core.rs` line 142 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6286#-O5JGJcnAvP6bq0G3YHH:-O5JGJcnAvP6bq0G3YHI:b68o5c5) ([raw file](https://github.com/starkware-libs/cairo/blob/be1999d751f16880e8b4d62de2e75a6f3bc4489c/crates/cairo-lang-sierra/src/extensions/core.rs#L142)):*
> ```XML
>         Pedersen(PedersenLibfunc),
>         Poseidon(PoseidonLibfunc),
>         Range(IntRangeLibfunc),
> ```

Int at the variant as well 
___
*[`crates/cairo-lang-sierra/src/extensions/modules/range.rs` line 91 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6286#-O5JGtb319bYvHgZ8XGu:-O5JGtb45bnOC_qXpBw3:b3ncbf9) ([raw file](https://github.com/starkware-libs/cairo/blob/be1999d751f16880e8b4d62de2e75a6f3bc4489c/crates/cairo-lang-sierra/src/extensions/modules/range.rs#L91)):*
> ```XML
>         args: &[GenericArg],
>     ) -> Result<LibfuncSignature, SpecializationError> {
>         let ty = args_as_single_type(args)?;
> ```

Probably need to be blocked for large ranges (over 2 pow 128 size)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6286)* status: 4 of 10 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/range.rs` line 91 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6286#-O5JGtb319bYvHgZ8XGu:-O5J__qz1yKc8vd8N6Rt:b-ne7pqd) ([raw file](https://github.com/starkware-libs/cairo/blob/be1999d751f16880e8b4d62de2e75a6f3bc4489c/crates/cairo-lang-sierra/src/extensions/modules/range.rs#L91)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Probably need to be blocked for large ranges (over 2 pow 128 size)
</blockquote></details>

Not this libfunc, just the construction of `Range`.

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6286)* status: 2 of 11 files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-sierra/src/extensions/core.rs` line 142 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6286#-O5JGJcnAvP6bq0G3YHH:-O5JhTKF3vliB8MxB-WZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/be1999d751f16880e8b4d62de2e75a6f3bc4489c/crates/cairo-lang-sierra/src/extensions/core.rs#L142)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Int at the variant as well
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6286#-O5ItyLyBaBLQS0AMq1H:-O5JmdyL4vWFA40WZuOi:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/95ccbe1704aefde353ee4c51b8c44e698106ded7/crates/cairo-lang-sierra-to-casm/src/invocations/range.rs#L35)):*
> ```XML
>         NonEmpty:
>         const one = 1;
>         let new_start = start + one;
> ```

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6286#-O5IuAWI4jJnWfDmvzVd:-O5JmcpwDv5ZfE3C6rW_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/95ccbe1704aefde353ee4c51b8c44e698106ded7/crates/cairo-lang-sierra-to-casm/src/invocations/range.rs#L43)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

and change the signature - will require an enum.
(we may consider adding in `core::internal::OptionReversed` just to help all the "upside-down" libfuncs)
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6286)* status: 2 of 11 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6286#-:-O5KKSi5-88ROHbnRF5v:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6286)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @liorgold2, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range.rs` line 42 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6286#-O5KLhyB92OCtyWobtnX:-O5KLhyC7sMBYtdEjbO7:bpykta) ([raw file](https://github.com/starkware-libs/cairo/blob/d7982446b9352d151004d70498660c8162a1c677/crates/cairo-lang-sierra-to-casm/src/invocations/range.rs#L42)):*
> ```XML
>             ("NonEmpty", &[&[new_start, end], &[start]], Some(non_empty_handle)),
>         ],
>         Default::default(),
> ```

maybe we should return all options?
* no need for multiple checks for different pops.
* less libfuncs.



_Suggestion:_
```XML
    };
    casm_build_extend! {casm_builder,
        const one = 1;
        let new_start = start + one;
        let new_end = end - one;
        tempvar is_non_empty = end - start;
        jump NonEmpty if is_non_empty != 0;
    };
    let non_empty_handle = get_non_fallthrough_statement_id(&builder);
    Ok(builder.build_from_casm_builder(
        casm_builder,
        [
            ("Fallthrough", &[], None),
            ("NonEmpty", &[&[new_start, end], &[start, new_end], &[start], &[new_end]], Some(non_empty_handle)),
        ],
        Default::default(),
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6286)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range.rs` line 42 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6286#-O5KLhyB92OCtyWobtnX:-O5Mf3xY0EcR6GETarhk:b-djfizv) ([raw file](https://github.com/starkware-libs/cairo/blob/d7982446b9352d151004d70498660c8162a1c677/crates/cairo-lang-sierra-to-casm/src/invocations/range.rs#L42)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe we should return all options?
* no need for multiple checks for different pops.
* less libfuncs.
</blockquote></details>

Makes sense, but I'll do it in another PR.

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6286#-:-O5MgPP96v0_frcULeMx:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

**Pull request merged**
