### PR TITLE
Added traits from impl aliases in the module, to the context

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4042)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4042)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/Cargo.toml` line 22 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4042#-NdzWY6y0h-yrQ3Dthn4:-NdzWY6y0h-yrQ3Dthn5:bq185w) ([raw file](https://github.com/starkware-libs/cairo/blob/df911bee5231e874c927253bf62388e0e9d42de7/crates/cairo-lang-semantic/Cargo.toml#L22)):*
> ```TOML
> cairo-lang-syntax = { path = "../cairo-lang-syntax", version = "2.2.0" }
> cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.2.0" }
> cairo-lang-test-utils = { path = "../cairo-lang-test-utils", optional = true, features = ["testing"] }
> ```

is version not required here?

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4042)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4042#-:-NdzYXJO2CH9sZ80oUK3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Comment by yuvalsw** [comment]
*[`crates/cairo-lang-semantic/Cargo.toml` line 22 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4042#-NdzWY6y0h-yrQ3Dthn4:-Ndza4pa7x3SwO0JArdD:bat7f2z) ([raw file](https://github.com/starkware-libs/cairo/blob/df911bee5231e874c927253bf62388e0e9d42de7/crates/cairo-lang-semantic/Cargo.toml#L22)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is version not required here?
</blockquote></details>

Probably not

**Pull request merged**
