### PR TITLE
Added generation of starknet wrappers for entry points

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1225)

### CODE REVIEW

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1225)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1225#-NIYBV8c0ViUWAx0O27F:-NIYBV8c0ViUWAx0O27G:b-54jaiu) (no related file):*
This PR is based on yuval/array_len_libfunc and yuval/format_string_util so it would pass CI only after they are merged.

___

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/starknet/src/plugin.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1225#-NIaDWWd9382hTE5CGST:-NIaDWWd9382hTE5CGSU:b-hmrffr) ([raw file](https://github.com/starkware-libs/cairo/blob/ea864ecb7e74651e40fddf99e06e114eadb9acea/crates/starknet/src/plugin.rs#L56)):*
> ```XML
>             let first_param_type = first_param.type_clause(db).ty(db).as_syntax_node().get_text(db);
>             if first_param_type != "SyscallPtr" {
>                 return PluginResult::default();
> ```

why not report diagnostics and continue?



_Code quote:_
```XML
return PluginResult::default();
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1225)* status: 3 of 7 files reviewed, 4 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/starknet/src/plugin.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1225#-NIaJLz59X-7qQguXN9f:-NIaJLz59X-7qQguXN9g:b-cvuv84) ([raw file](https://github.com/starkware-libs/cairo/blob/ea864ecb7e74651e40fddf99e06e114eadb9acea/crates/starknet/src/plugin.rs#L89)):*
> ```XML
>             // TODO(yuval): change to uint128 literal once it's supported.
>             functions_tokens.append(quote! {
>                 func $wrapper_name(ref syscall_ptr: SyscallPtr, data: Array::<felt>) -> Array::<felt> {
> ```

I think it is better to just



_Code quote:_
```XML
ref syscall_ptr: SyscallPtr
```
___
*[`crates/starknet/src/plugin.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1225#-NIaKQA9-dkcLQvwUCYm:-NIaKQA9-dkcLQvwUCYn:b-s1z24x) ([raw file](https://github.com/starkware-libs/cairo/blob/ea864ecb7e74651e40fddf99e06e114eadb9acea/crates/starknet/src/plugin.rs#L115)):*
> ```XML
>     // TODO(yuval): This works only if "ref" is the only modifier. If the expansion was at the
>     // semantic level, we could just ask if it's a reference.
>     param_modifiers.len() == 1 && param_modifiers[0].identifier(db) == "ref"
> ```

why not check that it is
Modifier::Ref
?



_Code quote:_
```XML
param_modifiers[0].identifier(db) == "ref"
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1225)* status: 6 of 7 files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`crates/starknet/src/plugin.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1225#-NIaOP4O6WLEZl9psi9z:-NIaOP4O6WLEZl9psiA-:bs8xzuh) ([raw file](https://github.com/starkware-libs/cairo/blob/ea864ecb7e74651e40fddf99e06e114eadb9acea/crates/starknet/src/plugin.rs#L66)):*
> ```XML
>             let mut ref_appends = quote! {};
>             for (idx, param) in params_iter.enumerate() {
>                 let arg_name = format!("__arg_{}", param.name(db).identifier(db));
> ```

why not use the original identifier?



_Code quote:_
```XML
                let arg_name = format!("__arg_{}", param.name(db).identifier(db));
```
___
*[`crates/starknet/src/plugin.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1225#-NIaO4AS4ClREvYKWFMI:-NIaO4AS4ClREvYKWFMJ:b3pr8yh) ([raw file](https://github.com/starkware-libs/cairo/blob/ea864ecb7e74651e40fddf99e06e114eadb9acea/crates/starknet/src/plugin.rs#L85)):*
> ```XML
> 
>             let wrapped_name = item_function.name(db).text(db).to_string();
>             let wrapper_name = format!("__wrapper_{}", wrapped_name.clone());
> ```

is this the final name?
if not add todo.



_Code quote:_
```XML
__wrapper_
```
___
*[`crates/starknet/src/plugin.rs` line 111 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1225#-NIaIth6D4pbDuaWfFMQ:-NIaIth6D4pbDuaWfFMR:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/ea864ecb7e74651e40fddf99e06e114eadb9acea/crates/starknet/src/plugin.rs#L111)):*
> ```XML
> }
> 
> fn is_ref_param(db: &dyn SyntaxGroup, param: &Param) -> bool {
> ```

doc



_Code quote:_
```XML
fn is_ref_param(db: &dyn SyntaxGroup, param: &Param) -> bool {
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1225)* status: 6 of 7 files reviewed, 5 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/starknet/src/plugin.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1225#-NIaDWWd9382hTE5CGST:-NIbhcVN-ZtKPmOM2wft:b5rq770) ([raw file](https://github.com/starkware-libs/cairo/blob/ea864ecb7e74651e40fddf99e06e114eadb9acea/crates/starknet/src/plugin.rs#L56)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Note the TODO above ("// TODO(yuval): diagnostic for each early return.").
Do you think we should continue in that case? The generated wrapper won't work...
</blockquote></details>

move ithe code inside the loop to a function that generations a wrapper for a single function.



_Code quote:_
```XML
 let item_function = match item {
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1225)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/starknet/src/plugin.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1225#-NIaJLz59X-7qQguXN9f:-NIbhkjQAEciANVPyNbY:b-kk03ey) ([raw file](https://github.com/starkware-libs/cairo/blob/ea864ecb7e74651e40fddf99e06e114eadb9acea/crates/starknet/src/plugin.rs#L89)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

?
</blockquote></details>

sorry.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1225)* status: 4 of 8 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/starknet/src/plugin.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1225#-NIaDWWd9382hTE5CGST:-NIbxsXZ3l140hC1I-LX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ea864ecb7e74651e40fddf99e06e114eadb9acea/crates/starknet/src/plugin.rs#L56)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

move ithe code inside the loop to a function that generations a wrapper for a single function.
</blockquote></details>

Done.
___
*[`crates/starknet/src/plugin.rs` line 111 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1225#-NIaIth6D4pbDuaWfFMQ:-NIbchOY6d3jNlVqLc0f:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ea864ecb7e74651e40fddf99e06e114eadb9acea/crates/starknet/src/plugin.rs#L111)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/starknet/src/plugin.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1225#-NIaKQA9-dkcLQvwUCYm:-NIbcgcM2L6xxm3tPTYt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ea864ecb7e74651e40fddf99e06e114eadb9acea/crates/starknet/src/plugin.rs#L115)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why not check that it is
Modifier::Ref
?
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, 3 of 4 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1225)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/starknet/src/plugin.rs` line 68 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1225#-NIcAOVW1AD1HNe1IIdR:-NIcAOVW1AD1HNe1IIdS:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7cd70425f117c17627d8a99c72f3d2ab602b97b4/crates/starknet/src/plugin.rs#L68)):*
> ```XML
>     let sig = function.signature(db);
>     let params = sig.parameters(db).elements(db);
>     // TODO(yuval): support types of size >1.
> ```





_Suggestion:_
```XML
support types != felt
```
___
*[`crates/starknet/src/plugin.rs` line 74 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1225#-NIcALDy0pVqeVi5UUDc:-NIcALDy0pVqeVi5UUDd:b-1mwkfo) ([raw file](https://github.com/starkware-libs/cairo/blob/7cd70425f117c17627d8a99c72f3d2ab602b97b4/crates/starknet/src/plugin.rs#L74)):*
> ```XML
>     // Assert the first parameter is SyscallPtr.
>     // TODO(yuval): get_text includes trivia... This wouldn't always work.
>     let first_param = params_iter.next().unwrap();
> ```

don't panic.



_Code quote:_
```XML
.unwrap();
```
___
*[`crates/starknet/src/plugin.rs` line 120 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1225#-NIcB6qO8WNrXbfh5RNb:-NIcB6qO8WNrXbfh5RNc:b-et10gh) ([raw file](https://github.com/starkware-libs/cairo/blob/7cd70425f117c17627d8a99c72f3d2ab602b97b4/crates/starknet/src/plugin.rs#L120)):*
> ```XML
>             if array::array_len::<felt>(data) == integer::uint128_from_felt($params_len) {
>             } else {
>                 panic(array::array_new::<felt>());
> ```

TODO: add error message.



_Code quote:_
```XML
panic(array::array_new::<felt>());
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1225)* status: 7 of 8 files reviewed, 5 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/starknet/src/plugin.rs` line 60 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1225#-NIcBIQO4_e_LTmTfvEF:-NIcBIQO4_e_LTmTfvEG:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/7cd70425f117c17627d8a99c72f3d2ab602b97b4/crates/starknet/src/plugin.rs#L60)):*
> ```XML
> }
> 
> fn generate_entry_point_wrapper(
> ```

doc



_Code quote:_
```XML
generate_entry_point_wrapper
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1225)* status: 7 of 8 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/starknet/src/plugin.rs` line 60 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1225#-NIcBIQO4_e_LTmTfvEF:-NIcCxQ4EdxDT5q7mwLq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7cd70425f117c17627d8a99c72f3d2ab602b97b4/crates/starknet/src/plugin.rs#L60)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/starknet/src/plugin.rs` line 68 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1225#-NIcAOVW1AD1HNe1IIdR:-NIcDJfc4RoB6D633S2A:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7cd70425f117c17627d8a99c72f3d2ab602b97b4/crates/starknet/src/plugin.rs#L68)):*
> ```XML
>     let sig = function.signature(db);
>     let params = sig.parameters(db).elements(db);
>     // TODO(yuval): support types of size >1.
> ```

Done.
___
*[`crates/starknet/src/plugin.rs` line 74 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1225#-NIcALDy0pVqeVi5UUDc:-NIcDnBO1yOsxrPBMu0b:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7cd70425f117c17627d8a99c72f3d2ab602b97b4/crates/starknet/src/plugin.rs#L74)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

don't panic.
</blockquote></details>

Done.
___
*[`crates/starknet/src/plugin.rs` line 120 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1225#-NIcB6qO8WNrXbfh5RNb:-NIcCkWV1W_lT3HNHthR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7cd70425f117c17627d8a99c72f3d2ab602b97b4/crates/starknet/src/plugin.rs#L120)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

TODO: add error message.
</blockquote></details>

Done.

**Pull request merged**
