### PR TITLE
Added functions documentation to reference

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2694)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
Mention somewhere about `local compilability` (not necessarily in this name). Signature is key, the validity of a function depends only on the signatures of the items it depends on.
This is also why the signature must be specified completely, and not infer the return type, for example.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2694#-:-NS4Ze_J-db-TmdF8sUc:b86t2hv)* status: 0 of 3 files reviewed, 12 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`docs/reference/src/functions.adoc` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4WKr6Bc_dk5dmyOxc:-NS4WKr6Bc_dk5dmyOxd:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L3)):*
> ```AsciiDoc
> = Functions
> 
> Functions are units of code to perform specific logics. They are defined using the `fn` keyword.
> ```





_Suggestion:_
```AsciiDoc
A functions is a unit of code that performs some specific logic. 
```
___
*[`docs/reference/src/functions.adoc` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4W_-M5OVAK_GPx6t4:-NS4W_-M5OVAK_GPx6t5:b60xd74) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L18)):*
> ```AsciiDoc
> 
> A function consists of 2 main parts: the function signature and the function body.
> For example,
> ```

It's not clear in this example what is the signature and what is the body. Suggestions:
1. Move this into the previous example, instead of inc.
2. Add comment inside this example for what is the signature and what is the boy.
___
*[`docs/reference/src/functions.adoc` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4WvtXCFPP2Abbh0IX:-NS4WvtYCcXIq6p_pqOp:benx0sv) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L28)):*
> ```AsciiDoc
> == Function Signature
> 
> The function signature defines the function name, the generic parameters, the parameters and the
> ```

I think this part can really benefit from an ebnf style syntax, or something similar.
Suggestion:
```
fn Name[<GenericParams>](Params) -> Type
```
___
*[`docs/reference/src/functions.adoc` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4Y4JG0Ww4Mi8J-nj-:-NS4Y4JG0Ww4Mi8J-nj0:b-sczmd9) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L35)):*
> ```AsciiDoc
> === Function Name
> 
> The function name is the name used to refer to the function. It should have the snake_case form.
> ```

Rephrase to inform this is only Cairo conventions.



_Code quote:_
```AsciiDoc
 It should have the snake_case form
```
___
*[`docs/reference/src/functions.adoc` line 40 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4YHR0BI6KEAo1zpeh:-NS4YHR0BI6KEAo1zpei:bfy4q5c) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L40)):*
> ```AsciiDoc
> 
> === Generic Parameters
> ```

Here, I would just refer to another document about generic params.
___
*[`docs/reference/src/functions.adoc` line 62 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4Yc6N34Gks_cJTGnq:-NS4Yc6N34Gks_cJTGnr:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L62)):*
> ```AsciiDoc
> === Parameters
> 
> Parameters define the types of the values that should be passed to the function when it is called,
> ```





_Suggestion:_
```AsciiDoc
are passed to the funct
```
___
*[`docs/reference/src/functions.adoc` line 62 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4YmoC7TR6iKbdAZIy:-NS4YmoC7TR6iKbdAZIz:b-g2a8zr) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L62)):*
> ```AsciiDoc
> === Parameters
> 
> Parameters define the types of the values that should be passed to the function when it is called,
> ```

There is no need to have ", and". In this cases I usually remove the ","
___
*[`docs/reference/src/functions.adoc` line 63 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4ZAVo6t9FR7EXA53K:-NS4YvU19_4mX9SLTIEM:b-hu39p1) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L63)):*
> ```AsciiDoc
> 
> Parameters define the types of the values that should be passed to the function when it is called,
> and define variables to the function's body. These variables can be referred using the parameter
> ```

Here I would refer to the Variables section, which will explain about the mut modifier.
you do need to explain about `ref` params somewhere.
___
*[`docs/reference/src/functions.adoc` line 63 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4ZEe5E6H8n8BHlVli:-NS4ZEe5E6H8n8BHlVlj:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L63)):*
> ```AsciiDoc
> 
> Parameters define the types of the values that should be passed to the function when it is called,
> and define variables to the function's body. These variables can be referred using the parameter
> ```





_Suggestion:_
```AsciiDoc
e referred to using the param
```
___
*[`docs/reference/src/functions.adoc` line 63 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4ZIOqA34hfTkgBq-0:-NS4ZIOqA34hfTkgBq-1:b-6m9a51) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L63)):*
> ```AsciiDoc
> 
> Parameters define the types of the values that should be passed to the function when it is called,
> and define variables to the function's body. These variables can be referred using the parameter
> ```

I usually prefer signular form. e.g. "A parameter can be ..."



_Code quote:_
```AsciiDoc
 These variables ca
```
___
*[`docs/reference/src/functions.adoc` line 65 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4ZRDrAtXl-UFes4mr:-NS4ZRDrAtXl-UFes4ms:bp309w7) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L65)):*
> ```AsciiDoc
> and define variables to the function's body. These variables can be referred using the parameter
> names to be used in the function body.
> They are defined using a comma-separated list of `name: Type` items, enclosed by
> ```

modifiers



_Code quote:_
```AsciiDoc
`name: Type`
```
___
*[`docs/reference/src/functions.adoc` line 99 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4ZZ_s9CyfM0QYK-SR:-NS4ZZ_s9CyfM0QYK-SS:bidiyic) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L99)):*
> ```AsciiDoc
> 
> == Calling a Function
> ```

Mention named arguments

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2694)* status: 0 of 3 files reviewed, 14 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`docs/reference/src/functions.adoc` line 73 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4_2Uo0I9FptwClFEe:-NS4_2Uo0I9FptwClFEf:bcsnec3) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L73)):*
> ```AsciiDoc
> 
> The return type defines the type of the value that is returned by the function when it is called.
> It is defined using the `\->` operator.
> ```

This is not an operator. Just say it's the part of the signature that comes after the `->` symbol/token.



_Code quote:_
```AsciiDoc
 the `\->` operator
```
___
*[`docs/reference/src/functions.adoc` line 76 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4_C6TEemdTHbqU_Kh:-NS4_C6TEemdTHbqU_Ki:b-xv99yv) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L76)):*
> ```AsciiDoc
> 
> Note that is Cairo, functions always return a value.
> To simulate "not returning a value", a function can return the unit type (`()`).
> ```

I don;t like that phrasing, it's not simulating anything.



_Code quote:_
```AsciiDoc
To simulate "not returning a value",
```

**Review by spapinistarkware — COMMENTED** [review]
Mention somewhere about inline

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2694#-:-NS4_Jny9Sp2KMCHE4rk:b-cb6mbw)* status: 0 of 3 files reviewed, 14 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2694)* status: 0 of 3 files reviewed, 18 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`docs/reference/src/functions.adoc` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4eWrk3VQ1uH5KI8sh:-NS4eWrk3VQ1uH5KI8si:bp0oy00) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L84)):*
> ```AsciiDoc
> 
> The function body is the code that is executed when the function is called.
> It is enclosed by the curly braces (`{...}`) and consists of a list of 0 or more statements,
> ```

This should appear on another page about block expression,



_Code quote:_
```AsciiDoc
The function body is the code that is executed when the function is called.
It is enclosed by the curly braces (`{...}`) and consists of a list of 0 or more statements,
executed one after the other in the defined order.

The last statement of a function body (if any) has a special meaning, and is called the
"tail statement".
It is evaluated like any other statement, but if it is not followed by a semicolon (`;`),
its evaluated value is returned by the function. If it is followed by a semicolon,
the function returns the unit type (`()`).
If the function has no statements at all, and thus no tail statement, it returns the unit type
(`()`).
```
___
*[`docs/reference/src/functions.adoc` line 87 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4ee6NEJ0ow7yzXQiW:-NS4ee6NEJ0ow7yzXQiX:bmy37qp) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L87)):*
> ```AsciiDoc
> executed one after the other in the defined order.
> 
> The last statement of a function body (if any) has a special meaning, and is called the
> ```

It's not the last statement really, and it's just if there is no trailing `;`, and it's called a tail expression. Try to follow rust's docs here.



_Code quote:_
```AsciiDoc
The last statement of a function body (if any) has a special meaning, and is called the
"tail statement".
```
___
*[`docs/reference/src/functions.adoc` line 89 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4eqLR5e97xHA_z-lh:-NS4eqLR5e97xHA_z-li:bqfayve) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L89)):*
> ```AsciiDoc
> The last statement of a function body (if any) has a special meaning, and is called the
> "tail statement".
> It is evaluated like any other statement, but if it is not followed by a semicolon (`;`),
> ```

again, its an expression.



_Code quote:_
```AsciiDoc
It is evaluated like any other statement, but if it is not followed by a semicolon (`;`),
its evaluated value is returned by the function. If it is followed by a semicolon,
the function returns the unit type (`()`).
If the function has no statements at all, and thus no tail statement, it returns the unit type
(`()`).
```
___
*[`docs/reference/src/functions.adoc` line 98 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4ez-5Cv5lPx9rJgIv:-NS4ez-5Cv5lPx9rJgIw:bfbvj07) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L98)):*
> ```AsciiDoc
> which is the tail statement. Its value is the return value of the function.
> 
> == Calling a Function
> ```

This shoulf refer to the function call expression page.

**Review by yuvalsw — COMMENTED** [review]
TODOs for now.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2694#-:-NS6k6GT5TRT_dOfwTkS:b-cbwue1)* status: 0 of 3 files reviewed, 17 unresolved discussions (waiting on @gilbens-starkware and @spapinistarkware)

___
*[`docs/reference/src/functions.adoc` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4WKr6Bc_dk5dmyOxc:-NS6asI3DO9NM7ZvduRC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L3)):*
> ```AsciiDoc
> = Functions
> 
> Functions are units of code to perform specific logics. They are defined using the `fn` keyword.
> ```

Done.
___
*[`docs/reference/src/functions.adoc` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4W_-M5OVAK_GPx6t4:-NS6b-dh1_9ugaa8mHpQ:byo4coj) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L18)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

It's not clear in this example what is the signature and what is the body. Suggestions:
1. Move this into the previous example, instead of inc.
2. Add comment inside this example for what is the signature and what is the boy.
</blockquote></details>

Added a comment (not sure if it's nice enough...). Anyway - I described below what is the sig and what is the body.
I didn't want to have a complex example with generics in the first example.
___
*[`docs/reference/src/functions.adoc` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4Y4JG0Ww4Mi8J-nj-:-NS6cayH6IQG6uKK_gCp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L35)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Rephrase to inform this is only Cairo conventions.
</blockquote></details>

Done.
___
*[`docs/reference/src/functions.adoc` line 40 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4YHR0BI6KEAo1zpeh:-NS6cgTA700QRrWEYT9o:b-v1pti) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L40)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Here, I would just refer to another document about generic params.
</blockquote></details>

I wanted to show how it's used in a function. So I need an example and for this I wanted to have a simple (partial) explanation. I linked to a separate doc below for more info (e.g. generic parameters that are impls)
___
*[`docs/reference/src/functions.adoc` line 62 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4Yc6N34Gks_cJTGnq:-NS6d2E16aLL2sjAESWA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L62)):*
> ```AsciiDoc
> === Parameters
> 
> Parameters define the types of the values that should be passed to the function when it is called,
> ```

Done.
___
*[`docs/reference/src/functions.adoc` line 63 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4ZAVo6t9FR7EXA53K:-NS6hXrl5ZqsbYcfXGAL:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L63)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Here I would refer to the Variables section, which will explain about the mut modifier.
you do need to explain about `ref` params somewhere.
</blockquote></details>

Done.
___
*[`docs/reference/src/functions.adoc` line 63 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4ZEe5E6H8n8BHlVli:-NS6hbPG1bguPC-QNEDi:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L63)):*
> ```AsciiDoc
> 
> Parameters define the types of the values that should be passed to the function when it is called,
> and define variables to the function's body. These variables can be referred using the parameter
> ```

Done.
___
*[`docs/reference/src/functions.adoc` line 63 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4ZIOqA34hfTkgBq-0:-NS6hpsd1ayDacjO3JJO:b3vgnpr) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L63)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I usually prefer signular form. e.g. "A parameter can be ..."
</blockquote></details>

I accept it in a definition of something. Here I refer to the "variables" (plural) from the previous statement. LMK if you still don't agree.
___
*[`docs/reference/src/functions.adoc` line 65 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4ZRDrAtXl-UFes4mr:-NS6i05A9S5arTaYTQN3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L65)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

modifiers
</blockquote></details>

Done.
___
*[`docs/reference/src/functions.adoc` line 73 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4_2Uo0I9FptwClFEe:-NS6iOJ5EnIBRbiopc6X:bmepcco) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L73)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This is not an operator. Just say it's the part of the signature that comes after the `->` symbol/token.
</blockquote></details>

copilot :)



_Code quote:_
```AsciiDoc
 is defined using the `\->` oper
```
___
*[`docs/reference/src/functions.adoc` line 76 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4_C6TEemdTHbqU_Kh:-NS6iYd39erbcIEzm6o-:b80ph3b) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L76)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I don;t like that phrasing, it's not simulating anything.
</blockquote></details>

Please suggest an alternative.
___
*[`docs/reference/src/functions.adoc` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4eWrk3VQ1uH5KI8sh:-NS6ihC497GEqY-RAdxY:bovrmk4) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L84)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This should appear on another page about block expression,
</blockquote></details>

OK, for now I added a TODO (as we don't yet have this other page).
___
*[`docs/reference/src/functions.adoc` line 87 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4ee6NEJ0ow7yzXQiW:-NS6j6VE5rOywuNQpNWw:b-6q895w) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L87)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

It's not the last statement really, and it's just if there is no trailing `;`, and it's called a tail expression. Try to follow rust's docs here.
</blockquote></details>

I the code we refer to it as the last statement, even if it has a `;`. I think that you describe what Rust does, but let's discuss and decide what's the correct terminology.
___
*[`docs/reference/src/functions.adoc` line 89 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4eqLR5e97xHA_z-lh:-NS6jNyX9rISo8Uf7y_G:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L89)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

again, its an expression.
</blockquote></details>

Done.
___
*[`docs/reference/src/functions.adoc` line 98 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4ez-5Cv5lPx9rJgIv:-NS6je34-ZaS1ffxwOkO:b-dyikak) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L98)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This shoulf refer to the function call expression page.
</blockquote></details>

TODO for now.
___
*[`docs/reference/src/functions.adoc` line 99 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4ZZ_s9CyfM0QYK-SR:-NS6j_E5DKOuMRGzWq-h:b-dyikak) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L99)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Mention named arguments
</blockquote></details>

TODO for now.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2694)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`docs/reference/src/functions.adoc` line 40 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4YHR0BI6KEAo1zpeh:-NSA-Skk0KKwpwK2KrqJ:b-c22lpp) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L40)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I wanted to show how it's used in a function. So I need an example and for this I wanted to have a simple (partial) explanation. I linked to a separate doc below for more info (e.g. generic parameters that are impls)
</blockquote></details>

Consider adding a link on the first usage of the word 'Generics' as well
___
*[`docs/reference/src/functions.adoc` line 63 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4ZIOqA34hfTkgBq-0:-NSA-l735qwVek9V7V9E:bxvxst1) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L63)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I accept it in a definition of something. Here I refer to the "variables" (plural) from the previous statement. LMK if you still don't agree.
</blockquote></details>

Consider "Each parameter/variable..."
___
*[`docs/reference/src/functions.adoc` line 76 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4_C6TEemdTHbqU_Kh:-NSA00EO7SRPqQ2mFOst:boibcuc) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L76)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Please suggest an alternative.
</blockquote></details>

When the function has no particular value it should return, it is common to return the link:..[unit type] `()`
___
*[`docs/reference/src/functions.adoc` line 87 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4ee6NEJ0ow7yzXQiW:-NSA0RFj4-Of9VgQmjpo:b-s1rkjc) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L87)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I the code we refer to it as the last statement, even if it has a `;`. I think that you describe what Rust does, but let's discuss and decide what's the correct terminology.
</blockquote></details>

That's just an implementation details though. In the code, we make sure the statement is an expr statement, so it's effectively just an expression.
I just think it's confusing a bit because in `{a;}`, the last statement is `a`, which is not the tail expression.

I would like to say somethin like: the block may end with an expression not followed by `;`. in this case ...
___
*[`docs/reference/src/functions.adoc` line 89 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4eqLR5e97xHA_z-lh:-NSA0rPj2RxtvghdqMUc:b98afm6) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L89)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Done.
</blockquote></details>

statement -> expression?
___
*[`docs/reference/src/functions.adoc` line 112 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NSA0zAuDiZho8zmxyhY:-NSA0zAuDiZho8zmxyhZ:b-wfbjb) ([raw file](https://github.com/starkware-libs/cairo/blob/522fdde67191bf82568df7ae5a6533af55ea48f4/docs/reference/src/functions.adoc#L112)):*
> ```AsciiDoc
> "tail expression".
> It is evaluated like any other statement, but if it is not followed by a semicolon (`;`),
> its evaluated value is returned by the function. If it is followed by a semicolon,
> ```

I'd like to rephrase it, as a continuation of my previous suggestion:
Otherwise, when the block ends with `;`, it returns a value of the unit type...



_Code quote:_
```AsciiDoc
its evaluated value is returned by the function. If it is followed by a semicolon,
the function returns the unit type (`()`).
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2694)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @spapinistarkware)

___
*[`docs/reference/src/functions.adoc` line 87 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4ee6NEJ0ow7yzXQiW:-NSAZQZgBFx1J-pYTYdH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L87)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

That's just an implementation details though. In the code, we make sure the statement is an expr statement, so it's effectively just an expression.
I just think it's confusing a bit because in `{a;}`, the last statement is `a`, which is not the tail expression.

I would like to say somethin like: the block may end with an expression not followed by `;`. in this case ...
</blockquote></details>

Done.
___
*[`docs/reference/src/functions.adoc` line 112 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NSA0zAuDiZho8zmxyhY:-NSAZUEtBTUcQhl1p_me:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/522fdde67191bf82568df7ae5a6533af55ea48f4/docs/reference/src/functions.adoc#L112)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I'd like to rephrase it, as a continuation of my previous suggestion:
Otherwise, when the block ends with `;`, it returns a value of the unit type...
</blockquote></details>

Done.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2694)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @spapinistarkware)

___
*[`docs/reference/src/functions.adoc` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2694#-NS4WvtXCFPP2Abbh0IX:-NSA_sVz-tpC4Jb1ynnV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a786b264c08d95146770bae869d45ae62b8665/docs/reference/src/functions.adoc#L28)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I think this part can really benefit from an ebnf style syntax, or something similar.
Suggestion:
```
fn Name[<GenericParams>](Params) -> Type
```
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2694#-:-NSB54pRBAMynLYBarN_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
