### PR TITLE
added while-let in semantic

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5024)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5024)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 367 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5024#-Nq1ume67IGG9A3lBG4c:-Nq1ume67IGG9A3lBG4d:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/59925be86b9b49a90b09d2ae6a388c51302e3470/crates/cairo-lang-semantic/src/diagnostic.rs#L367)):*
> ```XML
>             }
>             SemanticDiagnosticKind::LogicalOperatorNotAllowedInWhileLet => {
>                 "Logical operator not allowed in While-let.".into()
> ```





_Suggestion:_
```XML
                "Logical operator not allowed in while-let.".into()
```
___
*[`crates/cairo-lang-semantic/src/expr/test_data/while` line 71 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5024#-Nq1vMdZ9z5dscrIafbK:-Nq1vMdZ9z5dscrIafbL:bz18z6w) ([raw file](https://github.com/starkware-libs/cairo/blob/59925be86b9b49a90b09d2ae6a388c51302e3470/crates/cairo-lang-semantic/src/expr/test_data/while#L71)):*
> ```
>  --> lib.cairo:4:9
>         break x;
>         ^******^
> ```

why is this happening?



_Code quote:_
```
error: Can only break with a value inside a `loop`.
 --> lib.cairo:4:9
        break x;
        ^******^
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5024)* status: 4 of 8 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 367 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5024#-Nq1ume67IGG9A3lBG4c:-Nq2hBxx8e7p9F2fW-wY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/59925be86b9b49a90b09d2ae6a388c51302e3470/crates/cairo-lang-semantic/src/diagnostic.rs#L367)):*
> ```XML
>             }
>             SemanticDiagnosticKind::LogicalOperatorNotAllowedInWhileLet => {
>                 "Logical operator not allowed in While-let.".into()
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/while` line 71 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5024#-Nq1vMdZ9z5dscrIafbK:-Nq2hxTWE1He5gIlZTTZ:bwzofnk) ([raw file](https://github.com/starkware-libs/cairo/blob/59925be86b9b49a90b09d2ae6a388c51302e3470/crates/cairo-lang-semantic/src/expr/test_data/while#L71)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why is this happening?
</blockquote></details>

should it not happend? 
it is the same for regular while code

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5024#-:-Nq2kVQ_DC0UUw27vfJt:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/while` line 71 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5024#-Nq1vMdZ9z5dscrIafbK:-Nq2kINR3qKMS4XgIaB7:b9rs53o) ([raw file](https://github.com/starkware-libs/cairo/blob/59925be86b9b49a90b09d2ae6a388c51302e3470/crates/cairo-lang-semantic/src/expr/test_data/while#L71)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

should it not happend? 
it is the same for regular while code
</blockquote></details>

oh - nm

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5024)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5024)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
