### PR TITLE
Pass plugin env variable to LS subprocess

### LINKED ISSUE #6164: LS fails to run `scarb metadata` which errors dues to git exec run
> so I still had some issue with the LS, managed to track it down to this - if I have `snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.27.0" }` in `[dev-dependencies]` I get the following stack trace in the debug output
> 
> ```
> Caused by:
>     0: failed to execute: scarb metadata
>     1: `scarb metadata` exited with error
> 
>        stdout:
>            Updating git repository https://github.com/foundry-rs/starknet-foundry
>        error: failed to fetch into: /Users/m/Library/Caches/com.swmansion.scarb/registry/git/db/starknet-foundry-v6206fshfutuo.git
> 
>        Caused by:
>            0: could not execute process: git fetch --force --update-head-ok https://github.com/foundry-rs/starknet-foundry +refs/tags/v0.27.0:refs/remotes/origin/tags/v0.27.0
>            1: No such file or directory (os error 2)
> 
>        Stack backtrace:
>           0: std::backtrace::Backtrace::capture
>           1: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
>           2: <scarb::core::registry::cache::RegistryCache as scarb::core::registry::Registry>::query::{{closure}}
>           3: <scarb::core::registry::patcher::RegistryPatcher as scarb::core::registry::Registry>::query::{{closure}}::{{closure}}
>           4: <scarb::core::registry::patcher::RegistryPatcher as scarb::core::registry::Registry>::query::{{closure}}
>           5: scarb::resolver::resolve::{{closure}}::{{closure}}
>           6: tokio::runtime::handle::Handle::block_on
>           7: scarb::ops::resolve::resolve_workspace_with_opts
>           8: scarb::ops::metadata::collect_metadata
>           9: scarb::commands::run
>          10: scarb::main
>          11: std::sys_common::backtrace::__rust_begin_short_backtrace
>          12: _main
> 
>        stderr:
> ```
> 
> when commenting out the dev-dependency it all works

https://t.me/cairo_ls_support/49
also: https://swmansion.slack.com/archives/C074KU689K5/p1722604683907109

this problem reportedly does not occur on regular `scarb build` calls

we have no reliable reproduction

### PR DESCRIPTION
**Pull request by Arcticae**
This fixes the issue with the crashes, envs are not inherited by default in the server process, so path is ambiguous for the scarb process invoked by server

Closes #6164

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6176)

### CODE REVIEW

**Review by mkaput — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6176)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

**Review by Arcticae — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6176)* status: all files reviewed, 1 unresolved discussion (waiting on @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`vscode-cairo/src/cairols.ts` line 178 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6176#-O3mRhX4EhN-aImp-Fzx:-O3mSnCABOSdhaU4uyMD:b-wmheq6) ([raw file](https://github.com/starkware-libs/cairo/blob/f460b37af6c62ea81f9ae840a4255eb50848ed4a/vscode-cairo/src/cairols.ts#L178)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

question: are you able to provide documentation reference for this fact?
</blockquote></details>

Sadly no :/
___
*[`vscode-cairo/src/cairols.ts` line 193 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6176#-O3mRXhE8YkR5e4Onji1:-O3mSmav7mfsITm7ah2Q:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f460b37af6c62ea81f9ae840a4255eb50848ed4a/vscode-cairo/src/cairols.ts#L193)):*
> ```XML
>   serverExecutable.options.env.PATH = process.env["PATH"];
>   Object.assign(serverExecutable.options.env, logEnv, extraEnv);
> }
> ```

Done.

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6176)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`vscode-cairo/src/cairols.ts` line 178 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6176#-O3mRhX4EhN-aImp-Fzx:-O3mVQUF2yKTmtlBOQxT:bhykeil) ([raw file](https://github.com/starkware-libs/cairo/blob/f460b37af6c62ea81f9ae840a4255eb50848ed4a/vscode-cairo/src/cairols.ts#L178)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

Sadly no :/
</blockquote></details>

Hmm this looks to be the line that is spawning the process:

https://github.com/microsoft/vscode-languageserver-node/blob/4f1646c3f4ad56dc91d2fc66232c9a292fb288e8/client/src/node/main.ts#L466

I could not find any shenanigans with the `env` property in any code path leading to this line.

Node.js docs suggest that `env` is defaulted to `process.env`.

So, maybe the problem is the fact that we are `??=`-initializing `serverExecutable.options.env` to `{}` instead of `process.env`?

So maybe the proper fix should be different?

**Review by mkaput — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6176)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6176)* status: all files reviewed, 1 unresolved discussion (waiting on @Draggu, @mkaput, and @orizi)

___
*[`vscode-cairo/src/cairols.ts` line 178 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6176#-O3mRhX4EhN-aImp-Fzx:-O3mXQ2y1DVafBlfli2Z:b-95b5do) ([raw file](https://github.com/starkware-libs/cairo/blob/f460b37af6c62ea81f9ae840a4255eb50848ed4a/vscode-cairo/src/cairols.ts#L178)):*
>So, maybe the problem is the fact that we are `??=`\-initializing `serverExecutable.options.env` to `{}` instead of `process.env`?

Seems like it tbh

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6176)* status: all files reviewed, 1 unresolved discussion (waiting on @Draggu and @orizi)

___
*[`vscode-cairo/src/cairols.ts` line 191 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6176#-O3mZbwh8AjyQxg8lCvV:-O3mZbwh8AjyQxg8lCvW:b2ni30x) ([raw file](https://github.com/starkware-libs/cairo/blob/7bf1c44dc6f36c545f384fbce9cfcc0b456ebb62/vscode-cairo/src/cairols.ts#L191)):*
> ```XML
>   // By default, the server environment variables are not inherited from the parent process.
>   serverExecutable.options.env = process.env;
>   Object.assign(serverExecutable.options.env, logEnv, extraEnv);
> ```

fyi



_Suggestion:_
```XML
  serverExecutable.options ??= {};
  serverExecutable.options.env = {
    // Inherit env from parent process.
    ...process.env,
    ...(serverExecutable.options.env ?? {}),
    ...logEnv,
    ...extraEnv,
  };
```

**Review by Arcticae — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6176)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Draggu, @mkaput, and @orizi)

___
*[`vscode-cairo/src/cairols.ts` line 178 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6176#-O3mRhX4EhN-aImp-Fzx:-O3m_TOA55vU1zauu7vp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f460b37af6c62ea81f9ae840a4255eb50848ed4a/vscode-cairo/src/cairols.ts#L178)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

>So, maybe the problem is the fact that we are `??=`\-initializing `serverExecutable.options.env` to `{}` instead of `process.env`?

Seems like it tbh
</blockquote></details>

Done.

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6176)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, and @orizi)

**Review by Arcticae — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6176)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Draggu, @mkaput, and @orizi)

___
*[`vscode-cairo/src/cairols.ts` line 191 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6176#-O3mZbwh8AjyQxg8lCvV:-O3mab9JEdPxEK4HCx4f:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7bf1c44dc6f36c545f384fbce9cfcc0b456ebb62/vscode-cairo/src/cairols.ts#L191)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

fyi
</blockquote></details>

Done.

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6176#-:-O3mbSXE0gXxlaLTOhhA:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Draggu and @orizi)

**Review by piotmag769 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6176#-:-O3mcW3u6lZEThkwLQ9F:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Draggu and @orizi)

**Pull request merged**
