### PR TITLE
Let `compile_path` accept `CompilerConfig`

### PR DESCRIPTION
**Pull request by mkaput**
commit-id:45a97bff

---

**Stack**:
- #1993
- #1992
- #1991
- #1989 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1989)

### CODE REVIEW

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1989)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1989#-NN5hYsSDDK5C5ieOZOw:-NN5hYsSDDK5C5ieOZOx:b55033c) ([raw file](https://github.com/starkware-libs/cairo/blob/66b40943f2467b1de21b5ccc234dc9099ccfc16c/crates/cairo-lang-starknet/src/contract_class.rs#L90)):*
> ```XML
>             bail!("Compilation unit must include only one contract.",)
>         }
>     };
> ```

Is anything blocking from compiling multiple contracts at once?

I would love to have this as a compiler diagnostic, would make handling errors much easier downstream if everything is a diagnostic and there's single error for compilation failure.



_Code quote:_
```XML
    let contract = match &contracts[..] {
        [contract] => contract,
        [] => bail!("Contract not found."),
        _ => {
            // TODO(ilya): Add contract names.
            bail!("Compilation unit must include only one contract.",)
        }
    };
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1989#-NN5hYsSDDK5C5ieOZOw:-NN5iMqY9ku7TGU6p7NX:bqb1jps) ([raw file](https://github.com/starkware-libs/cairo/blob/66b40943f2467b1de21b5ccc234dc9099ccfc16c/crates/cairo-lang-starknet/src/contract_class.rs#L90)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Is anything blocking from compiling multiple contracts at once?

I would love to have this as a compiler diagnostic, would make handling errors much easier downstream if everything is a diagnostic and there's single error for compilation failure.
</blockquote></details>

We need to decide what the output is going to be in that case.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1989#-:-NN5ibG63h-0bZM51vmw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1989#-:-NN5k-kXDvalRUE05iL8:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)

___
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1989#-NN5jyQV8Zc3hDUfR-vA:-NN5jyQV8Zc3hDUfR-vB:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/66b40943f2467b1de21b5ccc234dc9099ccfc16c/crates/cairo-lang-starknet/src/contract_class.rs#L79)):*
> ```XML
> 
>     if check_diagnostics(db, compiler_config.on_diagnostic) {
>         bail!("Compilation failed.");
> ```





_Suggestion:_
```XML
        bail!("Failed to compile: {}", path.display());
```

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1989)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1989)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mkaput)

___
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1989#-NN5hYsSDDK5C5ieOZOw:-NN5zqfZDIKgFZIQPt4R:bk36anq) ([raw file](https://github.com/starkware-libs/cairo/blob/66b40943f2467b1de21b5ccc234dc9099ccfc16c/crates/cairo-lang-starknet/src/contract_class.rs#L90)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

We need to decide what the output is going to be in that case.
</blockquote></details>

I am thinking of adding `find_contracts` as a query to RootDatabase (via extension trait) which either returns one or more contracts, or emits an error diagnostic.

Furthermore, nothing prevents extending this to also have a query which returns either one contract or emits an error.

This would be a public API. This CLI could use the one-or-error variant and maintain its behaviour if that's imporatant, while for Scarb I find possible to let it emit multiple `contract.json` files, where `contract` is the actual Cairo module name holding the contract, and this is the output I can imagine possible also to be done in this CLI.

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1989)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mkaput)

___
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1989#-NN5hYsSDDK5C5ieOZOw:-NN6-j1D9wEdkTggMptn:b-g3n74f) ([raw file](https://github.com/starkware-libs/cairo/blob/66b40943f2467b1de21b5ccc234dc9099ccfc16c/crates/cairo-lang-starknet/src/contract_class.rs#L90)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I am thinking of adding `find_contracts` as a query to RootDatabase (via extension trait) which either returns one or more contracts, or emits an error diagnostic.

Furthermore, nothing prevents extending this to also have a query which returns either one contract or emits an error.

This would be a public API. This CLI could use the one-or-error variant and maintain its behaviour if that's imporatant, while for Scarb I find possible to let it emit multiple `contract.json` files, where `contract` is the actual Cairo module name holding the contract, and this is the output I can imagine possible also to be done in this CLI.
</blockquote></details>

In general, I want to extract everything after this expression as a function `pub fn compile_contract_with_prepared_db`, in similar fashion to one in `compiler` crate -- and this is what I want to use as an API for Scarb

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1989)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Pull request merged**
