### PR TITLE
Add final lowering to test_generated_function.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4672)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4672)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/lower/generated_test.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4672#-NmkT8XFC4wHHj-wjRTr:-NmkT8XFC4wHHj-wjRTs:b-sw9jug) ([raw file](https://github.com/starkware-libs/cairo/blob/bfdec56a3e0a696518752ec802274136cd117d9c/crates/cairo-lang-lowering/src/lower/generated_test.rs#L47)):*
> ```XML
>                 .debug(&LoweredFormatter::new(db, &multi_lowering.main_lowering.variables))
>         )
>         .unwrap();
> ```

shouldn't we have the final for the main as well?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/generated_test.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4672#-NmkT8XFC4wHHj-wjRTr:-NmkUrQc6OFEw0goP87Z:bfeim9k) ([raw file](https://github.com/starkware-libs/cairo/blob/bfdec56a3e0a696518752ec802274136cd117d9c/crates/cairo-lang-lowering/src/lower/generated_test.rs#L47)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

shouldn't we have the final for the main as well?
</blockquote></details>

what is the main?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/generated_test.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4672#-NmkT8XFC4wHHj-wjRTr:-NmkV5GKBhRnwxK_xhge:b-940j85) ([raw file](https://github.com/starkware-libs/cairo/blob/bfdec56a3e0a696518752ec802274136cd117d9c/crates/cairo-lang-lowering/src/lower/generated_test.rs#L47)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what is the main?
</blockquote></details>

nvm, I see.
not sure it  is useful in the test.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4672#-:-Nmk_-Y--D3U_JnDaSIq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/generated_test.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4672#-NmkT8XFC4wHHj-wjRTr:-NmkxvzZ40g-Bu4MhdQA:b-q2xodo) ([raw file](https://github.com/starkware-libs/cairo/blob/bfdec56a3e0a696518752ec802274136cd117d9c/crates/cairo-lang-lowering/src/lower/generated_test.rs#L47)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

nvm, I see.
not sure it  is useful in the test.
</blockquote></details>

nvm, you are right :)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4672)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
