### PR TITLE
Internal audit fixes.

### PR DESCRIPTION
**Pull request by liorgold2**
**Stack**:
- #5742
- #5741 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5741)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5741)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @liorgold2)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 542 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5741#-Nzhst6D9JPNi3SLFdQJ:-Nzhst6D9JPNi3SLFdQK:b-6kxexn) ([raw file](https://github.com/starkware-libs/cairo/blob/85b41eca7291ccc6ad7708cce9fc84663fd8f6f6/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L542)):*
> ```XML
>                         OutputVarInfo {
>                             ty: arr_snapshot_ty.clone(),
>                             ref_info: OutputVarReferenceInfo::SimpleDerefs,
> ```

why not add const?



_Code quote:_
```XML
                            ref_info: OutputVarReferenceInfo::SimpleDerefs,
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 612 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5741#-Nzhsv7z3_vxYUuWV6Xl:-Nzhsv7z3_vxYUuWV6Xm:b-6kxexn) ([raw file](https://github.com/starkware-libs/cairo/blob/85b41eca7291ccc6ad7708cce9fc84663fd8f6f6/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L612)):*
> ```XML
>                         OutputVarInfo {
>                             ty: arr_snapshot_ty.clone(),
>                             ref_info: OutputVarReferenceInfo::SimpleDerefs,
> ```

why not add const?

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5741)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 542 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5741#-Nzhst6D9JPNi3SLFdQJ:-Nzi16sM6uUQvOqU-fFM:b-g7b2i4) ([raw file](https://github.com/starkware-libs/cairo/blob/85b41eca7291ccc6ad7708cce9fc84663fd8f6f6/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L542)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why not add const?
</blockquote></details>

Because `new_start` is defined as `tempvar`

```
tempvar new_start = arr_start + popped_size;
...
("Fallthrough", &[&[range_check], &[new_start, arr_end], &[arr_start]], None),
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 612 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5741#-Nzhsv7z3_vxYUuWV6Xl:-Nzi1EmB5e-HUnw565Au:b-aotr0b) ([raw file](https://github.com/starkware-libs/cairo/blob/85b41eca7291ccc6ad7708cce9fc84663fd8f6f6/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L612)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why not add const?
</blockquote></details>

Similarly to above

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5741#-:-NziGlOhCwx99-uQBiTA:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5741)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
