### PR TITLE
LS: Set a special panic hook that skips for Salsa cancellation panics.

### PR DESCRIPTION
**Pull request by mkaput**

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6556#-:-OAWtWsx4TYPQXy6Ppi4:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @piotmag769)

**Review by Draggu — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6556#-:-OAWwZdr88LuLhWKRHMn:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 219 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6556#-OAWwR1w5dYhqcackj57:-OAWwR1w5dYhqcackj58:b6y6qx0) ([raw file](https://github.com/starkware-libs/cairo/blob/62fb4f3b6e628be69a2830815503d371e6eeadf3/crates/cairo-lang-language-server/src/lib.rs#L219)):*
> ```XML
> /// Sets a special panic hook that skips execution for Salsa cancellation panics.
> fn set_panic_hook() {
>     let default_hook = panic::take_hook();
> ```

This is default only because we did not set anything earlier.



_Suggestion:_
```XML
previous_hook
```

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6556)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @piotmag769)

**Review by piotmag769 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6556#-:-OAXlN8U3jzxZ053BWNl:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae)

**Pull request merged**
