### PR TITLE
Added `verify_eth_signature` to secp256k1

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2929)

### CODE REVIEW

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2929)* status: 0 of 1 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2929#-NToKn-U79gAwPZ7Pa5h:-NToKn-V86EsNI9ySYMP:bagld1g) (no related file):*
change target branch to main

___

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2929)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/starknet/secp256k1.cairo` line 109 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2929#-NV9HQ2i65ITKdqkdhlz:-NV9HQ2i65ITKdqkdhm-:b-1bhkce) ([raw file](https://github.com/starkware-libs/cairo/blob/5188e6eeb43e45309dba0788a643d0912e967d1c/corelib/src/starknet/secp256k1.cairo#L109)):*
> ```Cairo
>     // TODO(yg): either have 2 syscalls to get x and y of a point, and use the keccak libfunc (if
>     // it makes sense), or have a single syscall to get the keccak of a point. Seconds seems better,
>     //  unless getters of x and y are needed anywhere else.
> ```

I think having a syscall returning x and y is better - since it makes the other libfuncs usable.
otherwise we simply would have had the recover libfunc and nothing else.



_Code quote:_
```Cairo
    // TODO(yg): either have 2 syscalls to get x and y of a point, and use the keccak libfunc (if
    // it makes sense), or have a single syscall to get the keccak of a point. Seconds seems better,
    //  unless getters of x and y are needed anywhere else.
```
___
*[`corelib/src/starknet/secp256k1.cairo` line 112 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2929#-NV9HlfvAxoyyuADIoft:-NV9HlfvAxoyyuADIofu:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5188e6eeb43e45309dba0788a643d0912e967d1c/corelib/src/starknet/secp256k1.cairo#L112)):*
> ```Cairo
>     let x = secp256k1_ec_point_get_x(public_key_point);
>     let y = secp256k1_ec_point_get_y(public_key_point);
>     let point_hash = keccak(x, y);
> ```





_Suggestion:_
```Cairo
    let mut keccak_input = ArrayTrait::new();
    keccak::keccak_add_uint256_be(ref keccak_input, x);
    keccak::keccak_add_uint256_be(ref keccak_input, y);
    keccak::add_padding(ref keccak_input);
    let point_hash = starknet::syscalls::keccak_syscall(keccak_input.span()).unwrap_syscall();
```
___
*[`corelib/src/starknet/secp256k1.cairo` line 120 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2929#-NV9Id6I3mTT6boDulVI:-NV9Id6I3mTT6boDulVJ:bvowq16) ([raw file](https://github.com/starkware-libs/cairo/blob/5188e6eeb43e45309dba0788a643d0912e967d1c/corelib/src/starknet/secp256k1.cairo#L120)):*
> ```Cairo
>     let address_u256 = u256 { high: high_32_bits, low: point_hash.low };
>     // TODO(yg): need U256TryIntoFelt, and use the relevant trait.
>     EthAddress { address: address_u256.try_into().unwrap() }
> ```

    let high_32_bits = point_hash.high % 0x100000000;



_Suggestion:_
```Cairo
    // The Ethereum address is the 160 (128+32) least significant bits of the keccak of the public key.
    let high_32_bits = point_hash.high % 0x100000000;
    let address: felt252 = high_32_bits * 0x100000000000000000000000000000000 + point_hash.low;
    EthAddress { address }
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 36 of 36 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2929)* status: 36 of 37 files reviewed, 5 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/starknet/secp256k1.cairo` line 109 at r8](https://reviewable.io/reviews/starkware-libs/cairo/2929#-NVz04bQEzd5Gj33AdFQ:-NVz04bQEzd5Gj33AdFR:b4bf1gy) ([raw file](https://github.com/starkware-libs/cairo/blob/b2f3edb7b1a70d5244e08a4710d46f05d5614be4/corelib/src/starknet/secp256k1.cairo#L109)):*
> ```Cairo
> /// Checks whether `value` is in the range [1, N).
> fn is_signature_entry_valid(value: u256) -> bool {
>     value > u256 { high: 0, low: 0 } & value < get_N()
> ```

no need for the rangechecks



_Suggestion:_
```Cairo
value != u256 { high: 0, low: 0 }
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2929)* status: 32 of 39 files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/starknet/secp256k1.cairo` line 109 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2929#-NV9HQ2i65ITKdqkdhlz:-NW7c7X889MBoCSFi3NW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5188e6eeb43e45309dba0788a643d0912e967d1c/corelib/src/starknet/secp256k1.cairo#L109)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I think having a syscall returning x and y is better - since it makes the other libfuncs usable.
otherwise we simply would have had the recover libfunc and nothing else.
</blockquote></details>

Done.
___
*[`corelib/src/starknet/secp256k1.cairo` line 112 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2929#-NV9HlfvAxoyyuADIoft:-NWDFY9MBXZ93zixQ03k:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5188e6eeb43e45309dba0788a643d0912e967d1c/corelib/src/starknet/secp256k1.cairo#L112)):*
> ```Cairo
>     let x = secp256k1_ec_point_get_x(public_key_point);
>     let y = secp256k1_ec_point_get_y(public_key_point);
>     let point_hash = keccak(x, y);
> ```

Done.
___
*[`corelib/src/starknet/secp256k1.cairo` line 120 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2929#-NV9Id6I3mTT6boDulVI:-NWW9bxpCySlaNZ1n709:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5188e6eeb43e45309dba0788a643d0912e967d1c/corelib/src/starknet/secp256k1.cairo#L120)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

    let high_32_bits = point_hash.high % 0x100000000;
</blockquote></details>

Done.
___
*[`corelib/src/starknet/secp256k1.cairo` line 109 at r8](https://reviewable.io/reviews/starkware-libs/cairo/2929#-NVz04bQEzd5Gj33AdFQ:-NWDFXSI0MFoJ-aXs2YV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b2f3edb7b1a70d5244e08a4710d46f05d5614be4/corelib/src/starknet/secp256k1.cairo#L109)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no need for the rangechecks
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2929)* status: 34 of 39 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/test/secp256k1_test.cairo` line 94 at r12](https://reviewable.io/reviews/starkware-libs/cairo/2929#-NWWFrvfDKSjgX8XHJMs:-NWWFrvfDKSjgX8XHJMt:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/fdb6b8359835eeed3f4a91a300eb5ae9b4c0cb41/corelib/src/test/secp256k1_test.cairo#L94)):*
> ```Cairo
> 
> #[test]
> #[should_panic]
> ```





_Suggestion:_
```Cairo
#[should_panic(expected: ('Invalid signature', ))]
```
___
*[`corelib/src/test/secp256k1_test.cairo` line 107 at r12](https://reviewable.io/reviews/starkware-libs/cairo/2929#-NWWG9OZ4uFn2KiYNudV:-NWWG9O_6iCqA16WIZSj:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/fdb6b8359835eeed3f4a91a300eb5ae9b4c0cb41/corelib/src/test/secp256k1_test.cairo#L107)):*
> ```Cairo
> 
> #[test]
> #[should_panic]
> ```





_Suggestion:_
```Cairo
#[should_panic(expected: ('Signature out of range', ))]
```

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 6 files at r9, 1 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2929)* status: 37 of 39 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 6 files at r9, 1 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2929)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2929#-:-NWXC4UV90t_pyQjBe8B:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2929)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

___
*[`corelib/src/test/secp256k1_test.cairo` line 94 at r12](https://reviewable.io/reviews/starkware-libs/cairo/2929#-NWWFrvfDKSjgX8XHJMs:-NWX2SXf2j1jR5XxIicp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fdb6b8359835eeed3f4a91a300eb5ae9b4c0cb41/corelib/src/test/secp256k1_test.cairo#L94)):*
> ```Cairo
> 
> #[test]
> #[should_panic]
> ```

Done.
___
*[`corelib/src/test/secp256k1_test.cairo` line 107 at r12](https://reviewable.io/reviews/starkware-libs/cairo/2929#-NWWG9OZ4uFn2KiYNudV:-NWX2SsW4ShrAkdLu3uB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fdb6b8359835eeed3f4a91a300eb5ae9b4c0cb41/corelib/src/test/secp256k1_test.cairo#L107)):*
> ```Cairo
> 
> #[test]
> #[should_panic]
> ```

Done.

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2929)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
