### PR TITLE
Moved generation data structs

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3931)

### CODE REVIEW

**Comment by yuvalsw** [comment]
change target branch

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3931)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3931#-Nc2hjE52PfKkNbp8Qbo:-Nc2hjE60FJL5S1aqobm:be233hb) ([raw file](https://github.com/starkware-libs/cairo/blob/c8194fd7d8516ec6d8e8ca544bea4cd2e33e7661/crates/cairo-lang-starknet/src/plugin/contract.rs#L132)):*
> ```XML
>     }
> 
>     // Getters for generated names in the code, according to the module kind.
> ```

do a /// doc per func.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3931)* status: 0 of 17 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3931#-Nc2hjE52PfKkNbp8Qbo:-NcHjJ6uC0cak86xgUoe:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c8194fd7d8516ec6d8e8ca544bea4cd2e33e7661/crates/cairo-lang-starknet/src/plugin/contract.rs#L132)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

do a /// doc per func.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 2 of 15 files at r2, 14 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3931#-:-NcI31l19OxNshKlQJG5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
