### PR TITLE
Made recursive type diag `size` concept based.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #5494
- #5493 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5493)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/db.rs` line 1142 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5493#-NwmrDqT0R-5ezhcHdWP:-NwmrDqT0R-5ezhcHdWQ:bvk7d9b) ([raw file](https://github.com/starkware-libs/cairo/blob/0fdc53105dc8726a94cca1306d33bacffba683fc/crates/cairo-lang-semantic/src/db.rs#L1142)):*
> ```XML
> 
>     /// Returns true if the given type directly holds itself recursively, without any additional
>     /// indirection, such as `Box` or `Array`.
> ```

fix comment.



_Code quote:_
```XML
    /// Returns true if the given type directly holds itself recursively, without any additional
    /// indirection, such as `Box` or `Array`.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/types.rs` line 835 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5493#-Nwms5VzCtHBz9X_b1K4:-Nwms5VzCtHBz9X_b1K5:b2jptm6) ([raw file](https://github.com/starkware-libs/cairo/blob/0fdc53105dc8726a94cca1306d33bacffba683fc/crates/cairo-lang-semantic/src/types.rs#L835)):*
> ```XML
>             ConcreteTypeId::Enum(id) => {
>                 for (_, variant) in db.enum_variants(id.enum_id(db))? {
>                     db.type_size_info(db.variant_semantic(id.enum_id(db), variant)?.ty)?;
> ```

Is this just for cycle detection?



_Code quote:_
```XML
 db.type_size_info(db.variant_semantic(id.enum_id(db), variant)?.ty)?;
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/types.rs` line 846 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5493#-NwmsDlP-_aI1rqJEhxb:-NwmsDlP-_aI1rqJEhxc:b-kn52m1) ([raw file](https://github.com/starkware-libs/cairo/blob/0fdc53105dc8726a94cca1306d33bacffba683fc/crates/cairo-lang-semantic/src/types.rs#L846)):*
> ```XML
>                     zero_sized = false;
>                 }
>                 db.type_size_info(ty)?;
> ```

already called above



_Code quote:_
```XML
  db.type_size_info(ty)?;
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/types.rs` line 835 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5493#-Nwms5VzCtHBz9X_b1K4:-NwmsWET4TcJDlMLjAH2:b4rbbwc) ([raw file](https://github.com/starkware-libs/cairo/blob/0fdc53105dc8726a94cca1306d33bacffba683fc/crates/cairo-lang-semantic/src/types.rs#L835)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Is this just for cycle detection?
</blockquote></details>

add a comment

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5493)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5493)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 1142 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5493#-NwmrDqT0R-5ezhcHdWP:-Nwn_6Ec58-tjA4PK0EC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0fdc53105dc8726a94cca1306d33bacffba683fc/crates/cairo-lang-semantic/src/db.rs#L1142)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

fix comment.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/types.rs` line 835 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5493#-Nwms5VzCtHBz9X_b1K4:-Nwn_gft-B7BZXI23J_N:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0fdc53105dc8726a94cca1306d33bacffba683fc/crates/cairo-lang-semantic/src/types.rs#L835)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

add a comment
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/types.rs` line 846 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5493#-NwmsDlP-_aI1rqJEhxb:-Nwn__t_EGbHJKCShgKl:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0fdc53105dc8726a94cca1306d33bacffba683fc/crates/cairo-lang-semantic/src/types.rs#L846)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

already called above
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5493#-:-Nwnhrpl4rWWM9-8h0g5:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
