### PR TITLE
Use IntRange libfuncs in range.cairo.

### PR DESCRIPTION
**Pull request by liorgold2**
**Stack**:
- #6298
- #6289 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6289)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6289)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @liorgold2)

___
*[`corelib/src/ops/range.cairo` line 21 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6289#-O5MLL5Y7rUyh-aVvyvV:-O5MLL5Y7rUyh-aVvyvW:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/66cac9cf17c8b447321b2ee3525b82166f5d3b90/corelib/src/ops/range.cairo#L21)):*
> ```Cairo
>         Range::<T> { start: start, end: end }
>     }
> }
> ```





_Suggestion:_
```Cairo
/// Handles the range operator (`..`).
#[generate_trait]
pub impl RangeOpImpl<T> of RangeOp<T> {
    /// Handles the `..` operator. Returns the value of the expression `start..end`.
    fn range(start: T, end: T) -> Range<T> {
        Range { start, end }
    }
}
```
___
*[`corelib/src/ops/range.cairo` line 93 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6289#-O5MLlVR2ZZalr3kEHan:-O5MLlVR2ZZalr3kEHao:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/66cac9cf17c8b447321b2ee3525b82166f5d3b90/corelib/src/ops/range.cairo#L93)):*
> ```Cairo
> }
> 
> trait SierraRange<T>;
> ```





_Suggestion:_
```Cairo
/// Marker trait to enable using the Sierra libfuncs for integer range iteration.
trait SierraIntRangeSupport<T>;
```
___
*[`corelib/src/ops/range.cairo` line 104 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6289#-O5MMEme9ppuj4QKU9vY:-O5MMEme9ppuj4QKU9vZ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/66cac9cf17c8b447321b2ee3525b82166f5d3b90/corelib/src/ops/range.cairo#L104)):*
> ```Cairo
> impl SierraRangeI32 of SierraRange<i32>;
> impl SierraRangeI64 of SierraRange<i64>;
> impl SierraRangeI128 of SierraRange<i128>;
> ```





_Suggestion:_
```Cairo
#[cfg(sierra: '1.7.0')]
impl SierraRangeU8 of SierraRange<u8>;
#[cfg(sierra: '1.7.0')]
impl SierraRangeU16 of SierraRange<u16>;
#[cfg(sierra: '1.7.0')]
impl SierraRangeU32 of SierraRange<u32>;
#[cfg(sierra: '1.7.0')]
impl SierraRangeU64 of SierraRange<u64>;
#[cfg(sierra: '1.7.0')]
impl SierraRangeU128 of SierraRange<u128>;
#[cfg(sierra: '1.7.0')]
impl SierraRangeI8 of SierraRange<i8>;
#[cfg(sierra: '1.7.0')]
impl SierraRangeI16 of SierraRange<i16>;
#[cfg(sierra: '1.7.0')]
impl SierraRangeI32 of SierraRange<i32>;
#[cfg(sierra: '1.7.0')]
impl SierraRangeI64 of SierraRange<i64>;
#[cfg(sierra: '1.7.0')]
impl SierraRangeI128 of SierraRange<i128>;
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6289)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`corelib/src/ops/range.cairo` line 104 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6289#-O5MMEme9ppuj4QKU9vY:-O5N5aOE98sgF8WOBtRM:bpcy5ct) ([raw file](https://github.com/starkware-libs/cairo/blob/66cac9cf17c8b447321b2ee3525b82166f5d3b90/corelib/src/ops/range.cairo#L104)):*
> ```Cairo
> impl SierraRangeI32 of SierraRange<i32>;
> impl SierraRangeI64 of SierraRange<i64>;
> impl SierraRangeI128 of SierraRange<i128>;
> ```

as discussed - can't happen for now.

lets remove all the impls - and add a direct Marker impl in the tests for now.

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6289)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/ops/range.cairo` line 21 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6289#-O5MLL5Y7rUyh-aVvyvV:-O5MfX57DihAFmb3uQNZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/66cac9cf17c8b447321b2ee3525b82166f5d3b90/corelib/src/ops/range.cairo#L21)):*
> ```Cairo
>         Range::<T> { start: start, end: end }
>     }
> }
> ```

Done.
___
*[`corelib/src/ops/range.cairo` line 93 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6289#-O5MLlVR2ZZalr3kEHan:-O5MflqhCKp6ugeNLYmg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/66cac9cf17c8b447321b2ee3525b82166f5d3b90/corelib/src/ops/range.cairo#L93)):*
> ```Cairo
> }
> 
> trait SierraRange<T>;
> ```

Done.
___
*[`corelib/src/ops/range.cairo` line 104 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6289#-O5MMEme9ppuj4QKU9vY:-O5NXABI2EUyQG2e2lup:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/66cac9cf17c8b447321b2ee3525b82166f5d3b90/corelib/src/ops/range.cairo#L104)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

as discussed - can't happen for now.

lets remove all the impls - and add a direct Marker impl in the tests for now.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6289)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6289#-:-O5NhS5NDBl1P4gOSZKR:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
