### PR TITLE
match_optimization: Track reachable blocks.

### PR DESCRIPTION
**Pull request by liorgold2**
**Stack**:
- #6337
- #6339
- #6338
- #6341
- #6336 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6336)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 289 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6336#-O5rSWZ73U1B3f39YE3b:-O5rSWZ73U1B3f39YE3c:b9a64cn) ([raw file](https://github.com/starkware-libs/cairo/blob/6238865bcf4da15509e255a61d57c0993afe33e7/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L289)):*
> ```XML
>             &mut EmptyDemandReporter {},
>             vars.iter().map(|VarUsage { var_id, .. }| (var_id, ())),
>         );
> ```

Why are the infos collected into a vector here?



_Code quote:_
```XML
    let infos: Vec<_> = infos.collect();
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6336)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @orizi)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 305 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6336#-O5rTILa8y-fLnummVZW:-O5rTILa8y-fLnummVZX:b-8igcua) ([raw file](https://github.com/starkware-libs/cairo/blob/8aeca8a018f87c2ce6e8fc8185dd78eae040b38d/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L305)):*
> ```XML
>             infos.iter().map(|info| info.reachable_blocks.clone()).collect_vec();
>         let mut reachable_blocks = OrderedHashSet::default();
>         let mut found_collision = false;
> ```

is it used?



_Code quote:_
```XML
found_collision
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 303 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6336#-O5rU45m9w2C2g4T73oh:-O5rU45n3K8gFMHcKW5D:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8aeca8a018f87c2ce6e8fc8185dd78eae040b38d/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L303)):*
> ```XML
>         // Union the reachable blocks for all the infos.
>         let arm_reachable_blocks =
>             infos.iter().map(|info| info.reachable_blocks.clone()).collect_vec();
> ```





_Suggestion:_
```XML
        let per_arm_reachable_blocks_iter =
            infos.iter().map(|info| info.reachable_blocks)
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6336)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 289 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6336#-O5rSWZ73U1B3f39YE3b:-O5rXRDY4bIhN2yHvyMD:b-puyw0h) ([raw file](https://github.com/starkware-libs/cairo/blob/63fb73ede63a25e4ac20499663450507c833e666/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L289)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why are the infos collected into a vector here?
</blockquote></details>

This comment seems to be in the wrong place.
It was like that before my changes, I think it is because we iterate over infos more than once. Do you think we should change this?
___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 303 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6336#-O5rU45m9w2C2g4T73oh:-O5rWkbkBYThpcdl_zCN:b-k2m05u) ([raw file](https://github.com/starkware-libs/cairo/blob/eeb3f607828ba0295512e9b2e23ab61e29659d30/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L303)):*
> ```XML
>         // Union the reachable blocks for all the infos.
>         let arm_reachable_blocks =
>             infos.iter().map(|info| info.reachable_blocks.clone()).collect_vec();
> ```

Note that I'm storing it in the OptimizationCandidate, so I think I need it as a vector, right?
___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 305 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6336#-O5rTILa8y-fLnummVZW:-O5rWrDl4wJtya5-27WQ:blqqciy) ([raw file](https://github.com/starkware-libs/cairo/blob/eeb3f607828ba0295512e9b2e23ab61e29659d30/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L305)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

is it used?
</blockquote></details>

Yes, stored in `OptimizationCandidate`. Will be used in one of the next PRs to determine whether the optimization can be applied.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 289 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6336#-O5rSWZ73U1B3f39YE3b:-O5rZeMU4GKtO3HAAX5r:bw942v4) ([raw file](https://github.com/starkware-libs/cairo/blob/63fb73ede63a25e4ac20499663450507c833e666/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L289)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

This comment seems to be in the wrong place.
It was like that before my changes, I think it is because we iterate over infos more than once. Do you think we should change this?
</blockquote></details>

yes, reviewable jumped for some reason.
I think we need to fix it but in a separate PR

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6336)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 303 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6336#-O5rU45m9w2C2g4T73oh:-O5rZvhg3O03CiCi3NBp:b-dfuont) ([raw file](https://github.com/starkware-libs/cairo/blob/eeb3f607828ba0295512e9b2e23ab61e29659d30/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L303)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Note that I'm storing it in the OptimizationCandidate, so I think I need it as a vector, right?
</blockquote></details>

ok, right.
___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 305 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6336#-O5rTILa8y-fLnummVZW:-O5rZy755TI8JEqtYzjd:b2ni9bh) ([raw file](https://github.com/starkware-libs/cairo/blob/eeb3f607828ba0295512e9b2e23ab61e29659d30/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L305)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Yes, stored in `OptimizationCandidate`. Will be used in one of the next PRs to determine whether the optimization can be applied.
</blockquote></details>

ok.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6336)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 308 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6336#-O5rbflY9BePVNwJjgnX:-O5rbflY9BePVNwJjgnY:b-d9gdw2) ([raw file](https://github.com/starkware-libs/cairo/blob/eeb3f607828ba0295512e9b2e23ab61e29659d30/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L308)):*
> ```XML
>         for cur_reachable_blocks in &arm_reachable_blocks {
>             if !found_collision {
>                 found_collision = cur_reachable_blocks.intersects(&reachable_blocks);
> ```

You can do it more efficiently by checking the size change of 'cur_reachable_blocks'



_Code quote:_
```XML
 cur_reachable_blocks.intersects(&reachable_blocks);
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6336)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 303 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6336#-O5r_d5y4kA1GR47i5UT:-O5rdsmUCp5dFs2oFdyF:bjxazu4) ([raw file](https://github.com/starkware-libs/cairo/blob/eeb3f607828ba0295512e9b2e23ab61e29659d30/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L303)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I think the clone can be avoided.
</blockquote></details>

can you use unzip to get the demands and the reachable blocks from the info?

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6336)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 303 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6336#-O5r_d5y4kA1GR47i5UT:-O5rtMCOCAVVyaPi0jf6:b-a98cln) ([raw file](https://github.com/starkware-libs/cairo/blob/16926645c4ad34094ad2aeed6da47f40317e128a/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L303)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

can you use unzip to get the demands and the reachable blocks from the info?
</blockquote></details>

Done in https://reviewable.io/reviews/starkware-libs/cairo/6341.
___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 308 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6336#-O5rbflY9BePVNwJjgnX:-O5ru8SJC6aFTSUoVb8u:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/16926645c4ad34094ad2aeed6da47f40317e128a/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L308)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

You can do it more efficiently by checking the size change of 'cur_reachable_blocks'
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6336#-:-O5sFW1eBQ0AKzJsqHZu:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6336)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 305 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6336#-O5sHbtl8VLNBLytq7sU:-O5sHbtl8VLNBLytq7sV:b-suanwr) ([raw file](https://github.com/starkware-libs/cairo/blob/0df6a139c1d0366a346f3e63b79a4803f9067044/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L305)):*
> ```XML
>             infos.iter().map(|info| info.reachable_blocks.clone()).collect_vec();
>         let mut reachable_blocks = OrderedHashSet::default();
>         let mut expected_size = 0;
> ```

it is more like - `max_possible_size`

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6336)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6336)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 305 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6336#-O5sHbtl8VLNBLytq7sU:-O5tTw4328ZJzrB112ge:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0df6a139c1d0366a346f3e63b79a4803f9067044/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L305)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it is more like - `max_possible_size`
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6336#-:-O5tmBJmDwHzV6WkqENE:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
