### PR TITLE
Named generic arguments

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3903)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3903** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3903" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/3903?utm_source=stack-comment).

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3903)* status: 1 of 23 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 292 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3903#-NbtSWUdDkhHvNeSJkL0:-NbtSWUe2wWWw-6WScmX:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a89e43209e26095d6f58f567ac3357816828f68c/crates/cairo-lang-semantic/src/diagnostic.rs#L292)):*
> ```XML
>                 )
>             }
>             SemanticDiagnosticKind::WrongNumberOfGenericParamsForImpl { expected, actual } => {
> ```





_Suggestion:_
```XML
WrongNumberOfGenericParamsForImplFunction
```
___
*[`crates/cairo-lang-semantic/src/expr/test_data/generics` line 114 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3903#-NbtSa699GTRV9Gf4D8z:-NbtSa699GTRV9Gf4D9-:b1cs9q0) ([raw file](https://github.com/starkware-libs/cairo/blob/a89e43209e26095d6f58f567ac3357816828f68c/crates/cairo-lang-semantic/src/expr/test_data/generics#L114)):*
> ```
>                                   ^*****^
> 
> error: Too many generic arguments.
> ```

Add the lengths as well.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3903)* status: 3 of 23 files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 795 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3903#-NbtT1e13OemYiTA8vol:-NbtT1e13OemYiTA8vom:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a89e43209e26095d6f58f567ac3357816828f68c/crates/cairo-lang-semantic/src/resolve/mod.rs#L795)):*
> ```XML
>         let mut substitution = GenericSubstitution::default();
>         let mut resolved_args = vec![];
>         let mut arg_syntax_for_param = HashMap::<GenericParamId, ast::Expr>::default();
> ```





_Suggestion:_
```XML
UnorderedHashMap::
```
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 801 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3903#-NbtTRaq5ZNowMdyyEOy:-NbtTRarBInH3lAi42RJ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a89e43209e26095d6f58f567ac3357816828f68c/crates/cairo-lang-semantic/src/resolve/mod.rs#L801)):*
> ```XML
>             .enumerate()
>             .map(|(i, param)| (param.id().name(self.db.upcast()), (i, param.id())))
>             .collect::<HashMap<_, _>>();
> ```





_Suggestion:_
```XML
UnorderedHashMap
```

**Review by orizi — COMMENTED** [review]
> Reviewed 14 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3903)* status: all files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3903)* status: 15 of 26 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 292 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3903#-NbtSWUdDkhHvNeSJkL0:-NbxTt5g2cNFZec7wiJN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a89e43209e26095d6f58f567ac3357816828f68c/crates/cairo-lang-semantic/src/diagnostic.rs#L292)):*
> ```XML
>                 )
>             }
>             SemanticDiagnosticKind::WrongNumberOfGenericParamsForImpl { expected, actual } => {
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/generics` line 114 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3903#-NbtSa699GTRV9Gf4D8z:-NbxUJtfCC7A8CyVdlC_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a89e43209e26095d6f58f567ac3357816828f68c/crates/cairo-lang-semantic/src/expr/test_data/generics#L114)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Add the lengths as well.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 795 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3903#-NbtT1e13OemYiTA8vol:-NbxUVZN5vz5gSMq4zZV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a89e43209e26095d6f58f567ac3357816828f68c/crates/cairo-lang-semantic/src/resolve/mod.rs#L795)):*
> ```XML
>         let mut substitution = GenericSubstitution::default();
>         let mut resolved_args = vec![];
>         let mut arg_syntax_for_param = HashMap::<GenericParamId, ast::Expr>::default();
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 801 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3903#-NbtTRaq5ZNowMdyyEOy:-NbxUW4x3MA36bXccGYI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a89e43209e26095d6f58f567ac3357816828f68c/crates/cairo-lang-semantic/src/resolve/mod.rs#L801)):*
> ```XML
>             .enumerate()
>             .map(|(i, param)| (param.id().name(self.db.upcast()), (i, param.id())))
>             .collect::<HashMap<_, _>>();
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 22 of 22 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3903#-:-Nbz1dYc2oQp8K0qCCuA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
