### PR TITLE
Fix clippy errors.

### PR DESCRIPTION
**Pull request by liorgold2**
**Stack**:
- #4664
- #4689 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4689)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4689#-:-Nmp-T7Q-n0tR85amLqW:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4689)* status: all files reviewed, 1 unresolved discussion

___
*[`crates/cairo-lang-starknet/src/contract.rs` line 333 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4689#-NmyppTT8TKLUfRPcCzQ:-NmyppTT8TKLUfRPcCzR:bqcr710) ([raw file](https://github.com/starkware-libs/cairo/blob/917f8324c9e3669c2b31bc5ea7005849d1894ca4/crates/cairo-lang-starknet/src/contract.rs#L333)):*
> ```XML
>         extract_matches!(db.constant_semantic_data(constant_id).unwrap().value, Expr::Literal)
>             .value;
>     let class_hash: Felt252 = value.into();
> ```

Isn't it wrong that there is a "into" conversion from bigint to felt? If so, we should keep using try_from and ask for this from/into to be removed.
WDYT?

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4689)* status: all files reviewed, 1 unresolved discussion

___
*[`crates/cairo-lang-starknet/src/contract.rs` line 333 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4689#-NmyppTT8TKLUfRPcCzQ:-NmyrUdI8Uhv_fGKZfSt:bvqzjvd) ([raw file](https://github.com/starkware-libs/cairo/blob/917f8324c9e3669c2b31bc5ea7005849d1894ca4/crates/cairo-lang-starknet/src/contract.rs#L333)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Isn't it wrong that there is a "into" conversion from bigint to felt? If so, we should keep using try_from and ask for this from/into to be removed.
WDYT?
</blockquote></details>

If the `into` is doing modulo then it's fine (at least from a mathematical perspective), since indeed any bigint can be converted to a felt. If `into` behaves differently than `try_from().unwrap()` then it's not fine and one of them need to change.

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4689)* status: all files reviewed, 1 unresolved discussion

___
*[`crates/cairo-lang-starknet/src/contract.rs` line 333 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4689#-NmyppTT8TKLUfRPcCzQ:-NmyxArmBtw2tJMbbAuC:b-2eei6c) ([raw file](https://github.com/starkware-libs/cairo/blob/917f8324c9e3669c2b31bc5ea7005849d1894ca4/crates/cairo-lang-starknet/src/contract.rs#L333)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

If the `into` is doing modulo then it's fine (at least from a mathematical perspective), since indeed any bigint can be converted to a felt. If `into` behaves differently than `try_from().unwrap()` then it's not fine and one of them need to change.
</blockquote></details>

Yeah, it seems fine. Didn't get into all the details but:
1. conversions from bigint/biguint are doing some modulo, so seems fine.
2. I didn't find a specific TryFrom impl, in which case it's auto-implemented by rust and try_into.unwrap is equivalent to into.

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4689)* status: all files reviewed, 1 unresolved discussion

___
*[`crates/cairo-lang-starknet/src/contract.rs` line 333 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4689#-NmyppTT8TKLUfRPcCzQ:-Nmyxs5k63IIRV5MhiD6:b32w1t) ([raw file](https://github.com/starkware-libs/cairo/blob/917f8324c9e3669c2b31bc5ea7005849d1894ca4/crates/cairo-lang-starknet/src/contract.rs#L333)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Yeah, it seems fine. Didn't get into all the details but:
1. conversions from bigint/biguint are doing some modulo, so seems fine.
2. I didn't find a specific TryFrom impl, in which case it's auto-implemented by rust and try_into.unwrap is equivalent to into.
</blockquote></details>

Ok

**Pull request merged**
