### PR TITLE
Rename jump_nz to is_zero.

### PR DESCRIPTION
**Pull request by liorgold2**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1931)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 39 of 40 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1931)* status: 39 of 40 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/jump_not_zero.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1931#-NMiQu4kBfHW6WGML-LC:-NMiQu4lBNjApZja3wre:b467pt2) ([raw file](https://github.com/starkware-libs/cairo/blob/6e934605a81ab7a440642022344b808aacaf4580/crates/cairo-lang-sierra/src/extensions/modules/jump_not_zero.rs#L22)):*
> ```XML
> /// value in case of success.
> #[derive(Default)]
> pub struct IsZeroLibfunc<TIsZeroTraits: IsZeroTraits> {
> ```

rename file?



_Code quote:_
```XML
IsZeroLibfunc
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 40 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1931)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1931)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1931)* status: 37 of 42 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/jump_not_zero.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1931#-NMiQu4kBfHW6WGML-LC:-NMibGHy-SrvtZ-iGVw6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6e934605a81ab7a440642022344b808aacaf4580/crates/cairo-lang-sierra/src/extensions/modules/jump_not_zero.rs#L22)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rename file?
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1931#-:-NMicIg49uyzbFqduNyK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1931)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1931)* status: 41 of 42 files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/cairo-lang-debug/src/debug.rs` line 169 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1931#-NMiiM_W8KgLml85v6Qi:-NMiiM_W8KgLml85v6Qj:b-x250rp) ([raw file](https://github.com/starkware-libs/cairo/blob/9f10336a81fbdb4c95dd215637ec72451064b6bd/crates/cairo-lang-debug/src/debug.rs#L169)):*
> ```XML
> 
>     pub trait Fallback<T: fmt::Debug, Db: ?Sized> {
>         fn helper_debug<'a>(a: &'a T, _db: &Db) -> &'a dyn fmt::Debug {
> ```

Because of new clippy version

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1931)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
> Reviewed 11 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1931)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1931)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
