### PR TITLE
Added `match_nullable_snapshot`.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4253)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4253)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4253#-NgmI5nYC-ZxWFzNYOqC):*
Why is it needed?
___
*[`corelib/src/nullable.cairo` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4253#-NgmICAI3k1bWjgjrzMk:-NgmICAI3k1bWjgjrzMl:bkxs5x4) ([raw file](https://github.com/starkware-libs/cairo/blob/c083956d72a5a732c36b15c669cdd8b41f8da163/corelib/src/nullable.cairo#L35)):*
> ```Cairo
>         nullable_from_box(BoxTrait::new(value))
>     }
>     fn is_null(self: @Nullable<T>) -> bool {
> ```

please also test is_null.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/nullable.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4253#-NgmIICj89ZEZzfHNlb1:-NgmIICj89ZEZzfHNlb2:b-8a3xib) ([raw file](https://github.com/starkware-libs/cairo/blob/c083956d72a5a732c36b15c669cdd8b41f8da163/crates/cairo-lang-sierra-to-casm/src/invocations/nullable.rs#L27)):*
> ```XML
>         NullableConcreteLibfunc::MatchNullable(_)
>         | NullableConcreteLibfunc::MatchNullableSnapshot(_) => {
>             build_nullable_match_nullable(builder)
> ```

If it's the exact same casm, why do we need another libfunc?
___
*[`tests/e2e_test_data/libfuncs/nullable` line 121 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4253#-NgmHygv24BmjA10YS5P:-NgmHygv24BmjA10YS5Q:bnqwx06) ([raw file](https://github.com/starkware-libs/cairo/blob/c083956d72a5a732c36b15c669cdd8b41f8da163/tests/e2e_test_data/libfuncs/nullable#L121)):*
> ```
> 
> //! > cairo
> fn foo(x: @Nullable::<Array<felt252>>, y: Box::<@Array<felt252>>) -> Box::<@Array<felt252>> {
> ```

remove all "::"



_Code quote:_
```
able::<Array<felt252>>, y: Box::<@Array<felt252>>) -> Box::<@Array<felt252>>
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4253)* status: 6 of 9 files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4253#-NgmI5nYC-ZxWFzNYOqC):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Why is it needed?
</blockquote></details>

specifically for the non-consuming is_null.
___
*[`corelib/src/nullable.cairo` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4253#-NgmICAI3k1bWjgjrzMk:-NgoE-O02YHkYzfgY1AE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c083956d72a5a732c36b15c669cdd8b41f8da163/corelib/src/nullable.cairo#L35)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

please also test is_null.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/nullable.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4253#-NgmIICj89ZEZzfHNlb1:-NgoBHZ_7hyzPVnxdNME:bwic5ib) ([raw file](https://github.com/starkware-libs/cairo/blob/c083956d72a5a732c36b15c669cdd8b41f8da163/crates/cairo-lang-sierra-to-casm/src/invocations/nullable.rs#L27)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

If it's the exact same casm, why do we need another libfunc?
</blockquote></details>

it is a different signature - same code - as always with snapshots.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4253#-:-Ngs5IjjAW38CeDecLIT:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/test/nullable_test.cairo` line 8 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4253#-Ngs48iODbD4C12nh1fM:-Ngs48iP7GFnC_hkeBLf:bdqgf8k) ([raw file](https://github.com/starkware-libs/cairo/blob/3b68660fa92b91b03581eb1021605216ea7e3fd1/corelib/src/test/nullable_test.cairo#L8)):*
> ```Cairo
>     let nullable_x = NullableTrait::new(x);
>     assert(!nullable_x.is_null(), 'nullable_x.is_null() true');
>     assert_eq(@nullable_x.deref(), @x, 'x != 10');
> ```

x is 10 anyway, rephrase?



_Code quote:_
```Cairo
x != 10
```
___
*[`corelib/src/test/nullable_test.cairo` line 17 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4253#-Ngs4VQu1_Gl0oXmo6Eo:-Ngs4VQu1_Gl0oXmo6Ep:b-dvldw4) ([raw file](https://github.com/starkware-libs/cairo/blob/3b68660fa92b91b03581eb1021605216ea7e3fd1/corelib/src/test/nullable_test.cairo#L17)):*
> ```Cairo
> }
> 
> // Test objects of size>1.
> ```

rename the function accordingly?



_Code quote:_
```Cairo
// Test objects of size>1.
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4253)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`corelib/src/test/nullable_test.cairo` line 8 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4253#-Ngs48iODbD4C12nh1fM:-Ngsp46bCzetL-4oxGLc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3b68660fa92b91b03581eb1021605216ea7e3fd1/corelib/src/test/nullable_test.cairo#L8)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

x is 10 anyway, rephrase?
</blockquote></details>

Done.
___
*[`corelib/src/test/nullable_test.cairo` line 17 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4253#-Ngs4VQu1_Gl0oXmo6Eo:-Ngsor0BEvpqsOzINM4z:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3b68660fa92b91b03581eb1021605216ea7e3fd1/corelib/src/test/nullable_test.cairo#L17)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

rename the function accordingly?
</blockquote></details>

Done.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4253#-:-NgtzTXg3QMELu-bqZ3G:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/test/nullable_test.cairo` line 17 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4253#-NgtzPgO7HyEh355awX-:-NgtzPgO7HyEh355awX0:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/4e2c005867fdb297258812f412266888ff154e14/corelib/src/test/nullable_test.cairo#L17)):*
> ```Cairo
> }
> 
> // Testing `u256` as a tests for objects of size larger than 1.
> ```





_Suggestion:_
```Cairo
s a test fo
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4253)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
