### PR TITLE
compute queries in on other threads.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6026)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
includes:
https://reviewable.io/reviews/starkware-libs/cairo/6025#-

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6026#-:-O1vDmrnAcU4bjnPrldX:bro8poo)* status: 0 of 6 files reviewed, all discussions resolved

**Comment by maciektr** [comment]
*[`crates/cairo-lang-compiler/src/lib.rs` line 201 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6026#-O1vNU9nAI-VefhKe2by:-O1vNU9nAI-VefhKe2bz:bd45qkd) ([raw file](https://github.com/starkware-libs/cairo/blob/1257f493ae029965edc1cf9f8901fa499b761eb1/crates/cairo-lang-compiler/src/lib.rs#L201)):*
> ```XML
> ///  Checks if there are diagnostics in the database and if there are None, returns
> ///  the [SierraProgramWithDebug] object of the requested functions
> pub fn get_sierra_program_for_functions(
> ```

Will this be used by `compile_prepared_db`?

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6026)* status: 5 of 8 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @maciektr)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6026#-O1vO-NIB8edpBb1nNfH):*
rebase



_Code quote:_
```
New commits in r1 on 7/16/2024 at 2:49 PM:

- a2ff8ae: Delay error reporting.
```
___
*[`crates/cairo-lang-compiler/src/lib.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6026#-O1vOhoO08rFQH6HhUOr:-O1vOhoO08rFQH6HhUOs:b-qlppx) ([raw file](https://github.com/starkware-libs/cairo/blob/1257f493ae029965edc1cf9f8901fa499b761eb1/crates/cairo-lang-compiler/src/lib.rs#L190)):*
> ```XML
>                             }
>                         });
>                     }
> ```

maybe move out of function for smaller indentation.



_Code quote:_
```XML
                fn handle_func_inner(
                    processed_function_ids: &Mutex<UnorderedHashSet<ConcreteFunctionWithBodyId>>,
                    snapshot: salsa::Snapshot<RootDatabase>,
                    func_id: ConcreteFunctionWithBodyId,
                ) {
                    if processed_function_ids.lock().unwrap().insert(func_id) {
                        rayon::scope(move |s| {
                            let db = &*snapshot;
                            let Ok(function) = db.function_with_body_sierra(func_id) else {
                                return;
                            };
                            for statement in &function.body {
                                let Some(related_function_id) =
                                    try_get_function_with_body_id(db, statement)
                                else {
                                    continue;
                                };

                                let snapshot = salsa::ParallelDatabase::snapshot(&*snapshot);
                                s.spawn(move |_| {
                                    handle_func_inner(
                                        processed_function_ids,
                                        snapshot,
                                        related_function_id,
                                    )
                                })
                            }
                        });
                    }
```
___
*[`crates/cairo-lang-compiler/src/lib.rs` line 209 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6026#-O1vOMQx5BmhjKpkf8Jv:-O1vOMQx5BmhjKpkf8Jw:bdubirl) ([raw file](https://github.com/starkware-libs/cairo/blob/1257f493ae029965edc1cf9f8901fa499b761eb1/crates/cairo-lang-compiler/src/lib.rs#L209)):*
> ```XML
> 
>     let requested_function_ids_copy = requested_function_ids.clone();
>     rayon::spawn(move || compute_queries(snapshot, requested_function_ids_copy));
> ```

include the `spawn` in the function - and call the function `warmup_db` so it would be easily callable.



_Code quote:_
```XML
    rayon::spawn(move || compute_queries(snapshot, requested_function_ids_copy));
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-compiler/src/lib.rs` line 209 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6026#-O1vOMQx5BmhjKpkf8Jv:-O1vP7IREkVwxbOosIQD:b-ygchil) ([raw file](https://github.com/starkware-libs/cairo/blob/1257f493ae029965edc1cf9f8901fa499b761eb1/crates/cairo-lang-compiler/src/lib.rs#L209)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

include the `spawn` in the function - and call the function `warmup_db` so it would be easily callable.
</blockquote></details>

It will add indentation, and it won't be obvious that the warmup happens on a separate thread.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-compiler/src/lib.rs` line 201 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6026#-O1vNU9nAI-VefhKe2by:-O1vPmJS262wZymzPApb:b-q9ojid) ([raw file](https://github.com/starkware-libs/cairo/blob/1257f493ae029965edc1cf9f8901fa499b761eb1/crates/cairo-lang-compiler/src/lib.rs#L201)):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

Will this be used by `compile_prepared_db`?
</blockquote></details>

Ideally, yes, but it is not apparent how to make it work since `compile_prepared_db` does not have all the requested Ids.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6026)* status: 5 of 8 files reviewed, 4 unresolved discussions (waiting on @maciektr and @orizi)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6026#-O1vO-NIB8edpBb1nNfH):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rebase
</blockquote></details>

I didn't merge ` Delay error reporting`, as I think it is a regression unless we merge this PR.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6026)* status: 5 of 8 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @maciektr)

___
*[`crates/cairo-lang-compiler/src/lib.rs` line 209 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6026#-O1vOMQx5BmhjKpkf8Jv:-O1vQqAjC0eOo4z7brfy:b-lshdrc) ([raw file](https://github.com/starkware-libs/cairo/blob/1257f493ae029965edc1cf9f8901fa499b761eb1/crates/cairo-lang-compiler/src/lib.rs#L209)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

It will add indentation, and it won't be obvious that the warmup happens on a separate thread.
</blockquote></details>

i already supplied a basic solution for the indentation issue - for the other part - HEAVILY DOC.
and maybe `spawn_db_warmup` or something of that sort.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-compiler/src/lib.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6026#-O1vOhoO08rFQH6HhUOr:-O1vRBBp2nhIins27yb1:bsxnpp6) ([raw file](https://github.com/starkware-libs/cairo/blob/1257f493ae029965edc1cf9f8901fa499b761eb1/crates/cairo-lang-compiler/src/lib.rs#L190)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe move out of function for smaller indentation.
</blockquote></details>

I need `s` from the lambda for `s.spawn`.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6026)* status: 5 of 8 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @maciektr)

___
*[`crates/cairo-lang-compiler/src/lib.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6026#-O1vOhoO08rFQH6HhUOr:-O1vScFj0bFT-TIHBSnN:b-wl0xrf) ([raw file](https://github.com/starkware-libs/cairo/blob/1257f493ae029965edc1cf9f8901fa499b761eb1/crates/cairo-lang-compiler/src/lib.rs#L190)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I need `s` from the lambda for `s.spawn`.
</blockquote></details>

you can just add it to the function arguments - no?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-compiler/src/lib.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6026#-O1vWmE8747hopQBPMUJ:-O1vXjSd3SlTQbteUGHU:b-xn5k4g) ([raw file](https://github.com/starkware-libs/cairo/blob/1257f493ae029965edc1cf9f8901fa499b761eb1/crates/cairo-lang-compiler/src/lib.rs#L190)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you may consider extracting this into a regular function, and just calling it from the inner function.
</blockquote></details>

I don't follow, where would the rayon scope come from?

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2, 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6026)* status: 3 of 8 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @maciektr)

___
*[`crates/cairo-lang-compiler/src/lib.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6026#-O1vWmE8747hopQBPMUJ:-O1vYPNL6faaN6HdBwrB:b-jok1mj) ([raw file](https://github.com/starkware-libs/cairo/blob/1257f493ae029965edc1cf9f8901fa499b761eb1/crates/cairo-lang-compiler/src/lib.rs#L190)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't follow, where would the rayon scope come from?
</blockquote></details>

would be a param to the external function.
but now i realise this won't actually work in this case.
___
*[`crates/cairo-lang-compiler/src/lib.rs` line 159 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6026#-O1vZgVF4irZZoOC19ZH:-O1vZgVF4irZZoOC19ZI:b-gk07bq) ([raw file](https://github.com/starkware-libs/cairo/blob/e592d6395b0907063633fe6dd6ebf9adac2ca7fa/crates/cairo-lang-compiler/src/lib.rs#L159)):*
> ```XML
>     let processed_function_ids =
>         &Mutex::new(UnorderedHashSet::<ConcreteFunctionWithBodyId>::default());
>     rayon::scope(move |s| {
> ```

how does this compare?



_Suggestion:_
```XML
  rayon::scope_fifo(move |s| {
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-compiler/src/lib.rs` line 159 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6026#-O1vZgVF4irZZoOC19ZH:-O2-AZLVBjHiHfezY_zc:b-f1yloh) ([raw file](https://github.com/starkware-libs/cairo/blob/e592d6395b0907063633fe6dd6ebf9adac2ca7fa/crates/cairo-lang-compiler/src/lib.rs#L159)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

how does this compare?
</blockquote></details>

I didn't see a differnece

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6026)* status: 3 of 8 files reviewed, 4 unresolved discussions (waiting on @maciektr and @orizi)

___
*[`crates/cairo-lang-compiler/src/lib.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6026#-O1vWmE8747hopQBPMUJ:-O2-AYYK4kT2AYPGMhaZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1257f493ae029965edc1cf9f8901fa499b761eb1/crates/cairo-lang-compiler/src/lib.rs#L190)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

would be a param to the external function.
but now i realise this won't actually work in this case.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-compiler/src/lib.rs` line 209 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6026#-O1vOMQx5BmhjKpkf8Jv:-O2-AruT3FMUT_9AjGcW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1257f493ae029965edc1cf9f8901fa499b761eb1/crates/cairo-lang-compiler/src/lib.rs#L209)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

in any case - just add a wrapper function - won't cause indentation.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6026)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @maciektr)

___
*[`crates/cairo-lang-compiler/src/lib.rs` line 201 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6026#-O2-OWS4A9uY48nigm2G:-O2-OWS4A9uY48nigm2H:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/13e657748f8faa8056076a205c6ce1358d854c11/crates/cairo-lang-compiler/src/lib.rs#L201)):*
> ```XML
> }
> 
> // Spawns a task to warm up the db.
> ```





_Suggestion:_
```XML
/// Spawns a task to warm up the db.
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6026)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @maciektr and @orizi)

___
*[`crates/cairo-lang-compiler/src/lib.rs` line 201 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6026#-O2-OWS4A9uY48nigm2G:-O2-R19e4tv-JneQPW9o:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/13e657748f8faa8056076a205c6ce1358d854c11/crates/cairo-lang-compiler/src/lib.rs#L201)):*
> ```XML
> }
> 
> // Spawns a task to warm up the db.
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6026#-:-O2-Rg5CCs720YD7tj5X:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @maciektr)

**Pull request merged**
