### PR TITLE
Make function to get all syntax tree leaves / Serialization of Span

### PR DESCRIPTION
**Pull request by wawel37**
It's related to [this](https://github.com/software-mansion/scarb/pull/1639) in Scarb.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6475)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6475)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @wawel37)

___
*[`crates/cairo-lang-syntax/src/node/mod.rs` line 294 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6475#-O8r-TXW4p8EsqJGVFoe:-O8r-TXW4p8EsqJGVFof:bo42ant) ([raw file](https://github.com/starkware-libs/cairo/blob/4436584aaa3769507862b92ec59b9830e7d9a957/crates/cairo-lang-syntax/src/node/mod.rs#L294)):*
> ```XML
> 
>     /// Gets all the leaves of the SyntaxTree, where the self node is the root of a tree.
>     pub fn get_node_tree_leaves<'db>(&self, db: &'db dyn SyntaxGroup) -> Vec<Self> {
> ```

can't you just use `descendants`?



_Code quote:_
```XML
pub fn get_node_tree_leaves<
```

**Review by wawel37 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6475)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-syntax/src/node/mod.rs` line 294 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6475#-O8r-TXW4p8EsqJGVFoe:-O8v95-41Bvt8rGbrVLA:b-h9fs1b) ([raw file](https://github.com/starkware-libs/cairo/blob/4436584aaa3769507862b92ec59b9830e7d9a957/crates/cairo-lang-syntax/src/node/mod.rs#L294)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can't you just use `descendants`?
</blockquote></details>

The `preorder` (used inside `descendants`) excludes tokens, and that's what I actually want to get

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6475)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @wawel37)

___
*[`crates/cairo-lang-syntax/src/node/mod.rs` line 315 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6475#-O93io7t02LBGO4XrCso:-O93io7t02LBGO4XrCsp:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/026682190953f02196fbc9d75d4b91bf1dd1210c/crates/cairo-lang-syntax/src/node/mod.rs#L315)):*
> ```XML
>             }
>         }
>     }
> ```





_Suggestion:_
```XML
    /// Gets all the leaves of the SyntaxTree, where the self node is the root of a tree.
    pub fn tokens(&self, db: &dyn SyntaxGroup) -> Vec<Self> {
        self.preorder(db).filter_map(|event| match event {
            WalkEvent::Enter(node) if node.green_node(db).kind.is_terminal() => Some(node),
            _ => None,
        })
    }
```

**Review by wawel37 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6475)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-syntax/src/node/mod.rs` line 315 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6475#-O93io7t02LBGO4XrCso:-O998rEE9ZEzkLTUpNQF:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/026682190953f02196fbc9d75d4b91bf1dd1210c/crates/cairo-lang-syntax/src/node/mod.rs#L315)):*
> ```XML
>             }
>         }
>     }
> ```

Done.

**Review by wawel37 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6475)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-filesystem/src/span.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6475#-O99O_-e6V8RApjXVu_t:-O99Qfvc2KvjegI2tdNS:b4ghmmb) ([raw file](https://github.com/starkware-libs/cairo/blob/026682190953f02196fbc9d75d4b91bf1dd1210c/crates/cairo-lang-filesystem/src/span.rs#L16)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why are these a part of the PR?
</blockquote></details>

We need to be able to serialize it and deserialize it during Scarb host <-> macro communication.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6475)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @wawel37)

___
*[`crates/cairo-lang-syntax/src/node/mod.rs` line 315 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6475#-O93io7t02LBGO4XrCso:-O99h6R74OZ1gnWPLPPU:bmm6348) ([raw file](https://github.com/starkware-libs/cairo/blob/026682190953f02196fbc9d75d4b91bf1dd1210c/crates/cairo-lang-syntax/src/node/mod.rs#L315)):*
<details><summary><i>Previously, wawel37 (Mateusz Kowalski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

probably didn't push.

**Review by wawel37 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6475)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-syntax/src/node/mod.rs` line 315 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6475#-O93io7t02LBGO4XrCso:-O99pJ7r6OGrwyoI_8Jd:b-8jueuv) ([raw file](https://github.com/starkware-libs/cairo/blob/026682190953f02196fbc9d75d4b91bf1dd1210c/crates/cairo-lang-syntax/src/node/mod.rs#L315)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

probably didn't push.
</blockquote></details>

It was pushed but github decided not to sync the fork with the PR. Changed base of the PR again to `starknet/cairo/main` and it resynced after that. Everything's fine now

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6475)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @wawel37)

___
*[`crates/cairo-lang-syntax/src/node/mod.rs` line 315 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6475#-O93io7t02LBGO4XrCso:-O9AEJD705B_d94eArBf:b-1mlobc) ([raw file](https://github.com/starkware-libs/cairo/blob/026682190953f02196fbc9d75d4b91bf1dd1210c/crates/cairo-lang-syntax/src/node/mod.rs#L315)):*
<details><summary><i>Previously, wawel37 (Mateusz Kowalski) wrote…</i></summary><blockquote>

It was pushed but github decided not to sync the fork with the PR. Changed base of the PR again to `starknet/cairo/main` and it resynced after that. Everything's fine now
</blockquote></details>

return iterator - remove `.collect`.

**Review by wawel37 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6475)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-syntax/src/node/mod.rs` line 315 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6475#-O93io7t02LBGO4XrCso:-O9ATPNq4W3cHwDImVt6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/026682190953f02196fbc9d75d4b91bf1dd1210c/crates/cairo-lang-syntax/src/node/mod.rs#L315)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

return iterator - remove `.collect`.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6475#-:-O9Bt_Yi2ptBdi-lknwe:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wawel37)

**Pull request merged**
