### PR TITLE
Check for deref impls cycles and refactor special impls check.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
**Stack**:
- #5749
- #5746 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5746)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5746)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 1153 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5746#-Nzti6zmDI81oFvYEw2f:-Nzti6zmDI81oFvYEw2g:bar0xpn) ([raw file](https://github.com/starkware-libs/cairo/blob/24e92494547d750112b80516d2b5c28e8a703c2e/crates/cairo-lang-semantic/src/items/tests/trait#L1153)):*
> ```
>  --> lib.cairo:4:1
> impl ADeref of core::ops::Deref<A> {
> ^**********************************^
> ```

Do we want to emit diagnostic only for a canonic representative impl (e.g. smallest lexicographic) or do we want to keep all for the locations pointers?



_Code quote:_
```
//! > expected_diagnostics
error: Deref impls cycle detected:
core::ops::deref::Deref::<test::B> -> core::ops::deref::Deref::<test::A>
 --> lib.cairo:11:1
impl BDeref of core::ops::Deref<B> {
^**********************************^

error: Deref impls cycle detected:
core::ops::deref::Deref::<test::A> -> core::ops::deref::Deref::<test::B>
 --> lib.cairo:4:1
impl ADeref of core::ops::Deref<A> {
^**********************************^
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5746)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2405 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5746#-NzvEl3N-FRBl-FcbziA:-NzvEl3O0CH89kVcOoO7:b-xm93uu) ([raw file](https://github.com/starkware-libs/cairo/blob/24e92494547d750112b80516d2b5c28e8a703c2e/crates/cairo-lang-semantic/src/expr/compute.rs#L2405)):*
> ```XML
>     let mut res = OrderedHashMap::default();
>     let mut deref_functions = vec![];
>     let mut visited_types: OrderedHashSet<TypeId> = OrderedHashSet::default();
> ```

this sounds like getting enriched members should be a db query specifically.
at least add a TODO.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 543 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5746#-NzvCJ64Bt48Krp5Hsgs:-NzvCJ64Bt48Krp5Hsgt:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/24e92494547d750112b80516d2b5c28e8a703c2e/crates/cairo-lang-semantic/src/items/imp.rs#L543)):*
> ```XML
> }
> 
> fn handle_into_iterator_impl(
> ```

doc
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 556 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5746#-NzvD0r51yznR-DA-jMc:-NzvD0r51yznR-DA-jMd:b9sdp0i) ([raw file](https://github.com/starkware-libs/cairo/blob/24e92494547d750112b80516d2b5c28e8a703c2e/crates/cairo-lang-semantic/src/items/imp.rs#L556)):*
> ```XML
>         generic_params.iter().map(|generic_param| generic_param.id()).collect();
>     let lookup_context = ImplLookupContext::new(module_file_id.0, generic_params_ids);
>     if let Err(err) = get_impl_at_context(db, lookup_context, concrete_iterator_trait(db, ty), None)
> ```

this can be extracted as a function for both special impl checks:
assuming we have it called - `try_get_single_impl_type`:



_Suggestion:_
```XML
    if let Err(err) = try_get_single_impl_type(db, impl_def_id, |ty|concrete_iterator_trait(db, ty))
```
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 602 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5746#-NzvDp7D2dwIpW4TDD0G:-NzvDp7D2dwIpW4TDD0H:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/24e92494547d750112b80516d2b5c28e8a703c2e/crates/cairo-lang-semantic/src/items/imp.rs#L602)):*
> ```XML
>             // for cycles.
>             return;
>         };
> ```





_Suggestion:_
```XML
        let Ok(impl_id) =
            try_get_single_impl_type(db, impl_def_id, |ty| ConcreteTraitLongId {
            trait_id: deref_trait_id,
            generic_args: vec![GenericArgumentId::Type(ty)],
        }
        .intern(db))
        else {
            // Inference errors are handled when the impl is in actual use. In here we only check
            // for cycles.
            return;
        };
```
___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 1153 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5746#-Nzti6zmDI81oFvYEw2f:-NzvBmRB-WbMwANWXXWQ:b-cmkhhv) ([raw file](https://github.com/starkware-libs/cairo/blob/24e92494547d750112b80516d2b5c28e8a703c2e/crates/cairo-lang-semantic/src/items/tests/trait#L1153)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Do we want to emit diagnostic only for a canonic representative impl (e.g. smallest lexicographic) or do we want to keep all for the locations pointers?
</blockquote></details>

all is fine IMO:
1. easier to impl - points to all possible culprits.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5746)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2405 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5746#-NzvEl3N-FRBl-FcbziA:-NzwCJ5Y6ZqDAXftSkbW:b-okzgl6) ([raw file](https://github.com/starkware-libs/cairo/blob/24e92494547d750112b80516d2b5c28e8a703c2e/crates/cairo-lang-semantic/src/expr/compute.rs#L2405)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this sounds like getting enriched members should be a db query specifically.
at least add a TODO.
</blockquote></details>

But it is context dependent, I don't think we have queries depend on the computation context.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 543 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5746#-NzvCJ64Bt48Krp5Hsgs:-Nzvsg0PEIEWFd34ZzOh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/24e92494547d750112b80516d2b5c28e8a703c2e/crates/cairo-lang-semantic/src/items/imp.rs#L543)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 556 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5746#-NzvD0r51yznR-DA-jMc:-NzwBTFMEtZQfQjst74A:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/24e92494547d750112b80516d2b5c28e8a703c2e/crates/cairo-lang-semantic/src/items/imp.rs#L556)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this can be extracted as a function for both special impl checks:
assuming we have it called - `try_get_single_impl_type`:
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 602 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5746#-NzvDp7D2dwIpW4TDD0G:-NzwC8EZDZw5YCtT-mqO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/24e92494547d750112b80516d2b5c28e8a703c2e/crates/cairo-lang-semantic/src/items/imp.rs#L602)):*
> ```XML
>             // for cycles.
>             return;
>         };
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5746)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 556 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5746#-NzvD0r51yznR-DA-jMc:-NzwJUeiEwmaLzNjGdox:b2ni1bp) ([raw file](https://github.com/starkware-libs/cairo/blob/24e92494547d750112b80516d2b5c28e8a703c2e/crates/cairo-lang-semantic/src/items/imp.rs#L556)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

f2f
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 602 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5746#-NzvDp7D2dwIpW4TDD0G:-NzwJSuzC3pKubhyoE6P:b2ni1bp) ([raw file](https://github.com/starkware-libs/cairo/blob/24e92494547d750112b80516d2b5c28e8a703c2e/crates/cairo-lang-semantic/src/items/imp.rs#L602)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

f2f

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5746)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 556 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5746#-NzvD0r51yznR-DA-jMc:-NzwmsYN4A-2BZLjG-tL:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/24e92494547d750112b80516d2b5c28e8a703c2e/crates/cairo-lang-semantic/src/items/imp.rs#L556)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

f2f
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 602 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5746#-NzvDp7D2dwIpW4TDD0G:-NzwmtA28UM_EawQSJpW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/24e92494547d750112b80516d2b5c28e8a703c2e/crates/cairo-lang-semantic/src/items/imp.rs#L602)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

f2f
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5746)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 559 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5746#-Nzwo5PpBZbTMR2eEDbm:-Nzwo5PpBZbTMR2eEDbn:bs726x8) ([raw file](https://github.com/starkware-libs/cairo/blob/ab7b3ecb8e84b87726c4dc2f6b65f0c1c2861817/crates/cairo-lang-semantic/src/items/imp.rs#L559)):*
> ```XML
>                 .next()
>                 .unwrap()
>                 .stable_ptr(db.upcast()),
> ```

can you return this as well in the error case instead of the additional lookup?



_Code quote:_
```XML
            db.priv_impl_definition_data(impl_def_id)
                .unwrap()
                .item_type_asts
                .keys()
                .next()
                .unwrap()
                .stable_ptr(db.upcast()),
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5746)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 559 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5746#-Nzwo5PpBZbTMR2eEDbm:-Nzx5mZTCTQGvMJj08Y4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ab7b3ecb8e84b87726c4dc2f6b65f0c1c2861817/crates/cairo-lang-semantic/src/items/imp.rs#L559)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can you return this as well in the error case instead of the additional lookup?
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5746#-:-NzxCyhw35WibeA4RAYU:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
