### PR TITLE
fix(vscode-cairo): fix compile build error

### PR DESCRIPTION
**Pull request by chongqiangchen**
try fix compile error: 

```
> cairo1@2.3.1 compile
> tsc -p ./

node_modules/@types/node/globals.d.ts:84:11 - error TS2300: Duplicate identifier 'AbortController'.

84 interface AbortController {
…

Found 55 errors in 18 files.

Errors  Files
     4  node_modules/@types/node/globals.d.ts:84
     4  node_modules/@types/node/url.d.ts:119
…
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4398)

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
can you give more information about you version?
this works for me currently without your update.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4398#-:-NjDRpPW0RrDFCXVUAvt:b-rrj8vw)* status: 0 of 1 files reviewed, all discussions resolved

**Comment by chongqiangchen** [comment]
> can you give more information about you version? this works for me currently without your update.
> 
> > _[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4398#-:-NjDRpPW0RrDFCXVUAvt:b-rrj8vw)_ status: 0 of 1 files reviewed, all discussions resolved

local env?

**Operating System:**
ProductName: macOS
ProductVersion: 14.0
BuildVersion: 23A344

**Node.js Version:**
v18.18.2

**npm Version:**
9.8.1


**package**
cairo1@2.3.1 /Users/xxxx/Desktop/Projects/web3/cairo/cairo/vscode-cairo
├── @types/node@14.18.36
├── @types/vscode@1.77.0
├── @typescript-eslint/eslint-plugin@5.59.0
├── @vscode/test-electron@2.3.6
├── eslint-config-prettier@8.8.0
├── eslint@8.38.0
├── prettier@2.8.7
├── typescript@4.9.5
└── vscode-languageclient@7.0.0


**Full error:**

```

> cairo1@2.3.1 compile
> tsc -p ./

node_modules/@types/node/globals.d.ts(84,11): error TS2300: Duplicate identifier 'AbortController'.
node_modules/@types/node/globals.d.ts(101,11): error TS2300: Duplicate identifier 'AbortSignal'.
node_modules/@types/node/globals.d.ts(109,13): error TS2300: Duplicate identifier 'AbortController'.
node_modules/@types/node/globals.d.ts(114,13): error TS2300: Duplicate identifier 'AbortSignal'.
node_modules/@types/node/url.d.ts(119,19): error TS2300: Duplicate identifier 'URLSearchParams'.
node_modules/@types/node/url.d.ts(120,19): error TS2300: Duplicate identifier 'URL'.
node_modules/@types/node/url.d.ts(130,13): error TS2300: Duplicate identifier 'URL'.
node_modules/@types/node/url.d.ts(140,13): error TS2300: Duplicate identifier 'URLSearchParams'.
../../../../../../node_modules/@types/react-dom/index.d.ts(20,19): error TS2724: '"react"' has no exported member named 'SFCElement'. Did you mean 'CElement'?
../../../../../../node_modules/@types/react-native/index.d.ts(143,11): error TS2451: Cannot redeclare block-scoped variable 'originalXMLHttpRequest'.
../../../../../../node_modules/@types/react-native/index.d.ts(145,11): error TS2451: Cannot redeclare block-scoped variable '__BUNDLE_START_TIME__'.
../../../../../../node_modules/@types/react-native/index.d.ts(146,11): error TS2451: Cannot redeclare block-scoped variable 'ErrorUtils'.
../../../../../../node_modules/@types/react-native/index.d.ts(153,11): error TS2451: Cannot redeclare block-scoped variable '__DEV__'.
../../../../../../node_modules/@types/react-native/index.d.ts(155,11): error TS2451: Cannot redeclare block-scoped variable 'HermesInternal'.
../../../../../../node_modules/@types/react-native/Libraries/Lists/SectionList.d.ts(47,18): error TS2430: Interface 'SectionListProps<ItemT, SectionT>' incorrectly extends interface 'VirtualizedListWithoutRenderItemProps<ItemT>'.
  Types of property 'renderScrollComponent' are incompatible.
    Type '((props: import("/Users/chenchongqiang/node_modules/@types/react-native/Libraries/Components/ScrollView/ScrollView").ScrollViewProps) => React.ReactElement<import("/Users/chenchongqiang/node_modules/@types/react-native/Libraries/Components/ScrollView/ScrollView").ScrollViewProps, string | React.JSXElementConstructor...' is not assignable to type '((props: import("/Users/chenchongqiang/node_modules/react-native/Libraries/Components/ScrollView/ScrollView").ScrollViewProps) => React.ReactElement<import("/Users/chenchongqiang/node_modules/react-native/Libraries/Components/ScrollView/ScrollView").ScrollViewProps, string | React.JSXElementConstructor<...>>) | unde...'.
      Type '(props: import("/Users/chenchongqiang/node_modules/@types/react-native/Libraries/Components/ScrollView/ScrollView").ScrollViewProps) => React.ReactElement<import("/Users/chenchongqiang/node_modules/@types/react-native/Libraries/Components/ScrollView/ScrollView").ScrollViewProps, string | React.JSXElementConstructor<...' is not assignable to type '(props: import("/Users/chenchongqiang/node_modules/react-native/Libraries/Components/ScrollView/ScrollView").ScrollViewProps) => React.ReactElement<import("/Users/chenchongqiang/node_modules/react-native/Libraries/Components/ScrollView/ScrollView").ScrollViewProps, string | React.JSXElementConstructor<...>>'.
        Types of parameters 'props' and 'props' are incompatible.
          Type 'import("/Users/chenchongqiang/node_modules/react-native/Libraries/Components/ScrollView/ScrollView").ScrollViewProps' is not assignable to type 'import("/Users/chenchongqiang/node_modules/@types/react-native/Libraries/Components/ScrollView/ScrollView").ScrollViewProps'.
            Types of property 'contentContainerStyle' are incompatible.
              Type 'import("/Users/chenchongqiang/node_modules/react-native/Libraries/StyleSheet/StyleSheet").StyleProp<import("/Users/chenchongqiang/node_modules/react-native/Libraries/StyleSheet/StyleSheetTypes").ViewStyle>' is not assignable to type 'import("/Users/chenchongqiang/node_modules/@types/react-native/Libraries/StyleSheet/StyleSheet").StyleProp<import("/Users/chenchongqiang/node_modules/@types/react-native/Libraries/StyleSheet/StyleSheetTypes").ViewStyle>'.
                Type 'ViewStyle' is not assignable to type 'StyleProp<ViewStyle>'.
                  Type 'import("/Users/chenchongqiang/node_modules/react-native/Libraries/StyleSheet/StyleSheetTypes").ViewStyle' is not assignable to type 'import("/Users/chenchongqiang/node_modules/@types/react-native/Libraries/StyleSheet/StyleSheetTypes").ViewStyle'.
                    Types of property 'transform' are incompatible.
                      Type 'string | (PerpectiveTransform | RotateTransform | RotateXTransform | RotateYTransform | RotateZTransform | ... 7 more ... | MatrixTransform)[] | undefined' is not assignable to type '(PerpectiveTransform | RotateTransform | RotateXTransform | RotateYTransform | RotateZTransform | ... 7 more ... | MatrixTransform)[] | undefined'.
                        Type 'string' is not assignable to type '(PerpectiveTransform | RotateTransform | RotateXTransform | RotateYTransform | RotateZTransform | ... 7 more ... | MatrixTransform)[]'.
../../../../../../node_modules/@types/react-native/modules/BatchedBridge.d.ts(8,15): error TS2300: Duplicate identifier 'MessageQueue'.
../../../../../../node_modules/@types/react-native/modules/BatchedBridge.d.ts(18,20): error TS2300: Duplicate identifier 'BatchedBridge'.
../../../../../../node_modules/@types/react-native/modules/BatchedBridge.d.ts(22,20): error TS2300: Duplicate identifier 'MessageQueue'.
../../../../../../node_modules/@types/react-native/modules/Codegen.d.ts(1,1): error TS6200: Definitions of the following identifiers conflict with those in another file: codegenNativeCommands, NativeComponentType, codegenNativeComponent, BubblingEventHandler, DirectEventHandler, Double, Float, Int32, UnsafeObject, DefaultTypes, WithDefault
../../../../../../node_modules/@types/react-native/modules/Devtools.d.ts(2,17): error TS2300: Duplicate identifier 'StackFrame'.
../../../../../../node_modules/@types/react-native/modules/globals.d.ts(10,1): error TS6200: Definitions of the following identifiers conflict with those in another file: FormDataValue, FormDataPart, BodyInit_, RequestInfo, HeadersInit_, RequestCredentials_, RequestMode_, ResponseType_, XMLHttpRequestResponseType, URL, URLSearchParams, WebsocketMessageEventListener, WebsocketErrorEventListener, WebsocketOpenEventListener, WebsocketCloseEventListener, WebsocketEventListener
../../../../../../node_modules/@types/react-native/modules/globals.d.ts(90,15): error TS2300: Duplicate identifier 'FormData'.
../../../../../../node_modules/@types/react-native/modules/globals.d.ts(126,5): error TS2374: Duplicate index signature for type 'string'.
../../../../../../node_modules/@types/react-native/modules/globals.d.ts(471,15): error TS2300: Duplicate identifier 'AbortSignal'.
../../../../../../node_modules/@types/react-native/modules/globals.d.ts(506,15): error TS2300: Duplicate identifier 'AbortController'.
../../../../../../node_modules/@types/react-native/modules/LaunchScreen.d.ts(4,18): error TS2451: Cannot redeclare block-scoped variable 'Header'.
../../../../../../node_modules/@types/react-native/modules/LaunchScreen.d.ts(5,18): error TS2451: Cannot redeclare block-scoped variable 'LearnMoreLinks'.
../../../../../../node_modules/@types/react-native/modules/LaunchScreen.d.ts(6,18): error TS2451: Cannot redeclare block-scoped variable 'Colors'.
../../../../../../node_modules/@types/react-native/modules/LaunchScreen.d.ts(7,18): error TS2451: Cannot redeclare block-scoped variable 'DebugInstructions'.
../../../../../../node_modules/@types/react-native/modules/LaunchScreen.d.ts(8,18): error TS2451: Cannot redeclare block-scoped variable 'ReloadInstructions'.
../../../../../../node_modules/@types/react/ts5.0/global.d.ts(152,11): error TS2300: Duplicate identifier 'FormData'.
../../../../../../node_modules/@types/styled-components/ts3.7/index.d.ts(106,68): error TS2344: Type 'P' does not satisfy the constraint '{ theme?: T | undefined; }'.
../../../../../../node_modules/@types/styled-components/ts3.7/index.d.ts(163,8): error TS2615: Type of property 'propTypes' circularly references itself in mapped type 'ForwardRefExoticBase<Omit<Omit<any, any> & Partial<Pick<any, any>>, "theme"> & { theme?: any; } & WithChildrenIfReactComponentClass<StyledComponentInnerComponent<WithC>>>'.
../../../../../../node_modules/react-native/types/index.d.ts(200,9): error TS2451: Cannot redeclare block-scoped variable 'originalXMLHttpRequest'.
../../../../../../node_modules/react-native/types/index.d.ts(202,9): error TS2451: Cannot redeclare block-scoped variable '__BUNDLE_START_TIME__'.
../../../../../../node_modules/react-native/types/index.d.ts(203,9): error TS2451: Cannot redeclare block-scoped variable 'ErrorUtils'.
../../../../../../node_modules/react-native/types/index.d.ts(210,9): error TS2451: Cannot redeclare block-scoped variable '__DEV__'.
../../../../../../node_modules/react-native/types/index.d.ts(212,9): error TS2451: Cannot redeclare block-scoped variable 'HermesInternal'.
../../../../../../node_modules/react-native/types/modules/BatchedBridge.d.ts(17,15): error TS2300: Duplicate identifier 'MessageQueue'.
../../../../../../node_modules/react-native/types/modules/BatchedBridge.d.ts(27,18): error TS2300: Duplicate identifier 'BatchedBridge'.
../../../../../../node_modules/react-native/types/modules/BatchedBridge.d.ts(31,18): error TS2300: Duplicate identifier 'MessageQueue'.
../../../../../../node_modules/react-native/types/modules/Codegen.d.ts(10,1): error TS6200: Definitions of the following identifiers conflict with those in another file: codegenNativeCommands, NativeComponentType, codegenNativeComponent, BubblingEventHandler, DirectEventHandler, Double, Float, Int32, UnsafeObject, DefaultTypes, WithDefault
../../../../../../node_modules/react-native/types/modules/Devtools.d.ts(11,15): error TS2300: Duplicate identifier 'StackFrame'.
../../../../../../node_modules/react-native/types/modules/globals.d.ts(19,1): error TS6200: Definitions of the following identifiers conflict with those in another file: FormDataValue, FormDataPart, BodyInit_, RequestInfo, HeadersInit_, RequestCredentials_, RequestMode_, ResponseType_, XMLHttpRequestResponseType, URL, URLSearchParams, WebsocketMessageEventListener, WebsocketErrorEventListener, WebsocketOpenEventListener, WebsocketCloseEventListener, WebsocketEventListener
../../../../../../node_modules/react-native/types/modules/globals.d.ts(99,15): error TS2300: Duplicate identifier 'FormData'.
../../../../../../node_modules/react-native/types/modules/globals.d.ts(135,3): error TS2374: Duplicate index signature for type 'string'.
../../../../../../node_modules/react-native/types/modules/globals.d.ts(365,15): error TS2300: Duplicate identifier 'URL'.
../../../../../../node_modules/react-native/types/modules/globals.d.ts(390,15): error TS2300: Duplicate identifier 'URLSearchParams'.
../../../../../../node_modules/react-native/types/modules/globals.d.ts(480,15): error TS2300: Duplicate identifier 'AbortSignal'.
../../../../../../node_modules/react-native/types/modules/globals.d.ts(515,15): error TS2300: Duplicate identifier 'AbortController'.
../../../../../../node_modules/react-native/types/modules/LaunchScreen.d.ts(13,16): error TS2451: Cannot redeclare block-scoped variable 'Header'.
../../../../../../node_modules/react-native/types/modules/LaunchScreen.d.ts(14,16): error TS2451: Cannot redeclare block-scoped variable 'LearnMoreLinks'.
../../../../../../node_modules/react-native/types/modules/LaunchScreen.d.ts(15,16): error TS2451: Cannot redeclare block-scoped variable 'Colors'.
../../../../../../node_modules/react-native/types/modules/LaunchScreen.d.ts(16,16): error TS2451: Cannot redeclare block-scoped variable 'DebugInstructions'.
../../../../../../node_modules/react-native/types/modules/LaunchScreen.d.ts(17,16): error TS2451: Cannot redeclare block-scoped variable 'ReloadInstructions'.

```

**Comment by mkaput** [comment]
I redone tsconfig.json couple weeks ago and this problem should not happen anymore

**Comment by chongqiangchen** [comment]
> I redone tsconfig.json couple weeks ago and this problem should not happen anymore

thx

**Pull request closed without merging**
