### PR TITLE
Move cairo-test compilation plugin to new crate

### PR DESCRIPTION
**Pull request by maciektr**
Enables downstream dependencies to compile test cases without pulling whole test-runner crate as dep.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4060)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4060)* status: all files reviewed, 1 unresolved discussion (waiting on @maciektr and @mkaput)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4060#-Ne8aDTL4KdZzjMj2Ea4:-Ne8aDTL4KdZzjMj2Ea5:b-l4u7ye) (no related file):*
add it to `scripts/release_crates.sh` as well.

___

**Review by mkaput — APPROVED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4060)* status: all files reviewed, 1 unresolved discussion (waiting on @maciektr)

**Review by maciektr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4060)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4060#-Ne8aDTL4KdZzjMj2Ea4:-Ne8eGmf1vdCQd9WJ57P:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add it to `scripts/release_crates.sh` as well.
</blockquote></details>

Done.

___

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4060)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @maciektr and @mkaput)

___
*[`scripts/release_crates.sh` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4060#-Ne8rL3YAX1mltmpWBtB:-Ne8rL3Z7mqlvDmcR3sa:b3lwctl) ([raw file](https://github.com/starkware-libs/cairo/blob/fdde25650066252ef011f58b6011f5445ed699e2/scripts/release_crates.sh#L1)):*
> ```Shell
> cargo publish --package cairo-lang-utils && \
> ```

ordering here is VERY important.
revert.

**Comment by maciektr** [comment]
*[`scripts/release_crates.sh` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4060#-Ne8rL3YAX1mltmpWBtB:-Ne8urK93vT0LYYeN7Es:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fdde25650066252ef011f58b6011f5445ed699e2/scripts/release_crates.sh#L1)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

ordering here is VERY important.
revert.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4060#-:-Ne8va2e6Shs0RQvyd-N:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @maciektr)

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4060)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciektr)

**Pull request merged**
