### PR TITLE
Update cairo-vm version.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3566)

### CODE REVIEW

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3566#-:-NZLcrWU7IB6Mac6zecu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3566)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3566#-NZLnhuN9PYnqWFu49-l:-NZLnhuO8EED7L77Qa8y:b9wkz3f) (no related file):*
If you need it for this release, you need it to dev-2.0.0

___
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3566#-NZLnx9w0sIjFWIOHCQz:-NZLnx9x6wUGc03bW5ho:b2nhdkj) ([raw file](https://github.com/starkware-libs/cairo/blob/044d28b56197396bcbf3b3e20447d475268a96a0/crates/cairo-lang-runner/src/casm_run/mod.rs#L97)):*
> ```XML
>     // The starknet state.
>     pub starknet_state: StarknetState,
>     pub run_resources: RunResources,
> ```

Doc

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3566)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5)

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3566)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3566#-NZLnhuN9PYnqWFu49-l:-NZLumstDbvWuRRqy5Kg:b-ivcd9b) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

If you need it for this release, you need it to dev-2.0.0
</blockquote></details>

We won't include it in this release.

___
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3566#-NZLnx9w0sIjFWIOHCQz:-NZLutFtEbruCY9wwzvh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/044d28b56197396bcbf3b3e20447d475268a96a0/crates/cairo-lang-runner/src/casm_run/mod.rs#L97)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Doc
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3566#-:-NZM0mvR62jpojaWi4v5:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3566)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3566)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
