### PR TITLE
Remove unnamed parameter support

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1722)

### CODE REVIEW

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1722)* status: 1 of 11 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-formatter/src/test.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1722#-NLPvUwr2k9hUXW91_fU:-NLPvUwr2k9hUXW91_fV:ba3dfmt) ([raw file](https://github.com/starkware-libs/cairo/blob/51f58e300de67117f027b863782b3fc349b7d861/crates/cairo-lang-formatter/src/test.rs#L36)):*
> ```XML
>     let (syntax_root, diagnostics) =
>         get_syntax_root_and_diagnostics_from_file(db, unformatted_filename);
>     println!("{}", diagnostics.format(db));
> ```

Remove.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1722)* status: 3 of 11 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser_test_data/underscore_not_supported` line 234 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1722#-NLPvjj_Al68TFj0aGIx:-NLPvjj_Al68TFj0aGIy:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/51f58e300de67117f027b863782b3fc349b7d861/crates/cairo-lang-parser/src/parser_test_data/underscore_not_supported#L234)):*
> ```
> //! > ==========================================================================
> 
> //! > Param name without modifiers - underscore *is* supported
> ```





_Suggestion:_
```
//! > Param name without modifiers
```

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 5 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1722)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1722)* status: all files reviewed, 4 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1722#-NLPz9000sv5uXbYk4Lf:-NLPz9000sv5uXbYk4Lg:blni629) ([raw file](https://github.com/starkware-libs/cairo/blob/0cc476008a5f95526dcebb7ac2c2e2f87623e0fa/crates/cairo-lang-semantic/src/expr/compute.rs#L132)):*
> ```XML
>             None => {
>                 self.unnamed_variables.push(Variable::Param(semantic_param));
>                 return Ok(());
> ```

This is still used?



_Code quote:_
```XML
self.unnamed_variables
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1722)* status: all files reviewed, 4 unresolved discussions (waiting on @liorgold2 and @yuvalsw)

___
*[`crates/cairo-lang-formatter/src/test.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1722#-NLPvUwr2k9hUXW91_fU:-NLQ5BaIDMVRmfN5hP2l:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/51f58e300de67117f027b863782b3fc349b7d861/crates/cairo-lang-formatter/src/test.rs#L36)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Remove.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/underscore_not_supported` line 234 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1722#-NLPvjj_Al68TFj0aGIx:-NLQ5HOx7dGkOyqfh3wl:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/51f58e300de67117f027b863782b3fc349b7d861/crates/cairo-lang-parser/src/parser_test_data/underscore_not_supported#L234)):*
> ```
> //! > ==========================================================================
> 
> //! > Param name without modifiers - underscore *is* supported
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1722#-NLPz9000sv5uXbYk4Lf:-NLQ5Zl_96QjlzIbDkeS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0cc476008a5f95526dcebb7ac2c2e2f87623e0fa/crates/cairo-lang-semantic/src/expr/compute.rs#L132)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

This is still used?
</blockquote></details>

Done.



_Code quote:_
```XML
unnamed_variables
```
___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1722#-NLPw48u0-sBmjKXvL5F:-NLQ5pGu0uXJNbWNOhh1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/51f58e300de67117f027b863782b3fc349b7d861/crates/cairo-lang-semantic/src/items/functions.rs#L9)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Revert this change (or move the other syntax things from `use cairo_lang_syntax::node::{ast, TypedSyntaxNode};`).
</blockquote></details>

Done.

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1722)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1722#-:-NLQ6LG079k72aWs_-ZH:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by liorgold2 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1722)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
