### PR TITLE
Optimize and simplify EC add_to_state and finalize

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
Signed-off-by: Dori Medini <dori@starkware.co>

commit-id:d74888e5

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1696)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1696)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1696#-NLH1BxO49T_OAWph4db:-NLHGfezB3WNNhYWrACz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/37aec16d13ed8b03316c13085ebc183152e6dbaf/crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs#L57)):*
> ```XML
> fn add_ec_points(
>     casm_builder: &mut CasmBuilder,
>     p0: (Var, Var),
> ```

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs` line 224 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1696#-NLH1tOe2NmE4gkiqq9G:-NLHGxxE1IUX40dlzzE0:bb7lbs2) ([raw file](https://github.com/starkware-libs/cairo/blob/37aec16d13ed8b03316c13085ebc183152e6dbaf/crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs#L224)):*
> ```XML
>         SumIsNotInfinity:
>         // X coordinate is identical; either `p0 + p1` is the point at infinity (either not allowed
>         // or already handled), or `p0 = p1`, which is not allowed (doubling).
> ```

nice

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1696)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs` line 224 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1696#-NLH1tOe2NmE4gkiqq9G:-NLHNSwt5PMlfCA2eE1g:b-6ncgpa) ([raw file](https://github.com/starkware-libs/cairo/blob/37aec16d13ed8b03316c13085ebc183152e6dbaf/crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs#L224)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

nice
</blockquote></details>

lior has a better suggestion:
replying again.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs` line 221 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1696#-NLHNbZwBcSs6p29mXJW:-NLHNbZwBcSs6p29mXJX:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/93880541f8dc6f28971d0b3b7d1b91be6caa4ee4/crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs#L221)):*
> ```XML
>         jump NotSameX if denominator != 0;
>         // We compute `p0 + (-p1)`, and `-(x, y)` is `(x, -y)`. As such, the sum of the Y
>         // coordinates is `y - random_y`.
> ```





_Suggestion:_
```XML
        // We compute `p0 + (-p1)`, and `-(x, y)` is `(x, -y)`. As such, the sum of the Y
        // coordinates is `y - random_y`.
        assert y = random_y;

        // X coordinate is identical; either `p0 + p1` is the point at infinity (either not allowed
        // or already handled), or `p0 = p1`, which is not allowed (doubling).
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1696)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs` line 221 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1696#-NLHNbZwBcSs6p29mXJW:-NLHXyw6Bq5JcwTdy7oQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/93880541f8dc6f28971d0b3b7d1b91be6caa4ee4/crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs#L221)):*
> ```XML
>         jump NotSameX if denominator != 0;
>         // We compute `p0 + (-p1)`, and `-(x, y)` is `(x, -y)`. As such, the sum of the Y
>         // coordinates is `y - random_y`.
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1696#-:-NLHZHTKBmfKsC2Q7gPf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
