### PR TITLE
Added `super::` usages in inner contract modules.

### PR DESCRIPTION
**Pull request by orizi**
for support of inline and general user types as part of the interfaces.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2051)

### CODE REVIEW

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2051#-:-NNkEUKo7eEzep3-E6yG:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin_test_data/user_defined_types` line 7 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2051#-NNkD1ER5WmiymnkgN97:-NNkD1ER5WmiymnkgN98:byp18fd) ([raw file](https://github.com/starkware-libs/cairo/blob/3f904a68d1f3ba80272130b350295daba8dc90e1/crates/cairo-lang-starknet/src/plugin_test_data/user_defined_types#L7)):*
> ```
> 
> //! > cairo_code
> // TODO(ilya): update format.
> ```

Remove



_Code quote:_
```
// TODO(ilya): update format.
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2051)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin_test_data/user_defined_types` line 7 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2051#-NNkD1ER5WmiymnkgN97:-NNkEr5Q1RWv6BYTp5dm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3f904a68d1f3ba80272130b350295daba8dc90e1/crates/cairo-lang-starknet/src/plugin_test_data/user_defined_types#L7)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.

**Review by yuvalsw — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2051)* status: all files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 307 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2051#-NNkHI3l2vVG7rN2nV5R:-NNkHI3mCmDRsavnsi88:b-hsyd1c) ([raw file](https://github.com/starkware-libs/cairo/blob/3f904a68d1f3ba80272130b350295daba8dc90e1/crates/cairo-lang-starknet/src/plugin.rs#L307)):*
> ```XML
>     };
>     let mut diagnostics = vec![];
>     let mut original_items = Vec::new();
> ```

please either doc that these are original items *to keep*, or call it something like original_items_to_keep.



_Code quote:_
```XML
original_items
```
___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 318 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2051#-NNkH2iA-Hmsn04B6Cr8:-NNkH2iA-Hmsn04B6Cr9:b-iviqs1) ([raw file](https://github.com/starkware-libs/cairo/blob/3f904a68d1f3ba80272130b350295daba8dc90e1/crates/cairo-lang-starknet/src/plugin.rs#L318)):*
> ```XML
>         if let Some(ident) = match item {
>             ast::Item::Constant(item) => Some(item.name(db)),
>             ast::Item::Module(item) => Some(item.name(db)),
> ```

Please document when/what/why items are in original_items and when/what/why in extra uses.



_Code quote:_
```XML
        if matches!(&item, ast::Item::FreeFunction(item) if item.has_attr(db, EVENT_ATTR))
            || matches!(&item, ast::Item::Struct(item) if item.name(db).text(db) == STORAGE_STRUCT_NAME)
        {
            continue;
        }
        original_items.push(RewriteNode::Copied(item.as_syntax_node()));
        if let Some(ident) = match item {
            ast::Item::Constant(item) => Some(item.name(db)),
            ast::Item::Module(item) => Some(item.name(db)),
            ast::Item::Use(item) => {
                if let Some(ast::PathSegment::Simple(final_section)) =
                    item.name(db).elements(db).last()
                {
                    Some(final_section.ident(db))
                } else {
                    None
                }
            }
            ast::Item::Impl(item) => Some(item.name(db)),
            ast::Item::Struct(item) => Some(item.name(db)),
            ast::Item::Enum(item) => Some(item.name(db)),
            ast::Item::TypeAlias(item) => Some(item.name(db)),
            ast::Item::ExternFunction(_)
            | ast::Item::ExternType(_)
            | ast::Item::Trait(_)
            | ast::Item::FreeFunction(_) => None,
        } {
            extra_uses.push(RewriteNode::Text(format!("\n        use super::{};", ident.text(db))));
```
___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 337 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2051#-NNkGpvs0sUXZc5A6RiR:-NNkGpvs0sUXZc5A6RiS:b-nab7me) ([raw file](https://github.com/starkware-libs/cairo/blob/3f904a68d1f3ba80272130b350295daba8dc90e1/crates/cairo-lang-starknet/src/plugin.rs#L337)):*
> ```XML
>             | ast::Item::FreeFunction(_) => None,
>         } {
>             extra_uses.push(RewriteNode::Text(format!("\n        use super::{};", ident.text(db))));
> ```

Is this a temporary solution until we add use super::*? Or should it remain that way?
___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 473 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2051#-NNkGUNsB88Ropd2DvLE:-NNkGUNsB88Ropd2DvLF:byow9av) ([raw file](https://github.com/starkware-libs/cairo/blob/3f904a68d1f3ba80272130b350295daba8dc90e1/crates/cairo-lang-starknet/src/plugin.rs#L473)):*
> ```XML
>             ),
>             (
>                 "extra_uses".to_string(),
> ```

It's not required, but I think it's a bit easier to read if the order is similar to the order they appear in the text, so if you could, please move this and "event_functions" to their relevant position. Thanks



_Code quote:_
```XML
extra_uses".to_string(),
```
___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 629 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2051#-NNkIGNW0qWZ6boYmbBL:-NNkIGNW0qWZ6boYmbBM:b-wps8tj) ([raw file](https://github.com/starkware-libs/cairo/blob/3f904a68d1f3ba80272130b350295daba8dc90e1/crates/cairo-lang-starknet/src/plugin.rs#L629)):*
> ```XML
>             Some((key_type_ast, value_type_ast, MappingType::Legacy)) => {
>                 members_code.push(RewriteNode::interpolate_patched(
>                     handle_legacy_mapping_storage_var(&address).as_str(),
> ```

I know it's not from this PR, and I don't currently have a good solution, but I really don't like it that the string with the patch-variables is in a completely different place that the patch substitutions.
___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 645 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2051#-NNkInp6AWFgsiq0U4Qt:-NNkInp6AWFgsiq0U4Qu:b-j1ya5a) ([raw file](https://github.com/starkware-libs/cairo/blob/3f904a68d1f3ba80272130b350295daba8dc90e1/crates/cairo-lang-starknet/src/plugin.rs#L645)):*
> ```XML
>                         (
>                             "extra_uses".to_string(),
>                             RewriteNode::Modified(ModifiedNode { children: extra_uses.to_vec() }),
> ```

suggest to pass a RewriteNode as the param.



_Code quote:_
```XML
RewriteNode::Modified(ModifiedNode { children: extra_uses.to_vec() })
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2051)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 337 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2051#-NNkGpvs0sUXZc5A6RiR:-NNkKU6R7HlelcCl_QZE:b-f3q5b4) ([raw file](https://github.com/starkware-libs/cairo/blob/3f904a68d1f3ba80272130b350295daba8dc90e1/crates/cairo-lang-starknet/src/plugin.rs#L337)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Is this a temporary solution until we add use super::*? Or should it remain that way?
</blockquote></details>

i don't know - but it works without relation to that question.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2051#-:-NNkQhelArums3MSwE88:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
