### PR TITLE
Core Lib Documentation: `Clone` module

### PR DESCRIPTION
**Pull request by TAdev0**

### CODE REVIEW

**Review by enitrat — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6665)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @TAdev0)

___
*[`corelib/src/clone.cairo` line 38 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6665#-OBtFzxk7LeTkwmCWXiJ:-OBtFzxk7LeTkwmCWXiK:b-qh4y80) ([raw file](https://github.com/starkware-libs/cairo/blob/1d3150c2de7a2764e279c8eec48743ddd75bda1c/corelib/src/clone.cairo#L38)):*
> ```Cairo
> //! ```
> 
> /// `Clone` trait defines the interface for cloning values.
> ```

I would add more details than just this

```
/// A common trait for the ability to explicitly duplicate an object.
///
/// Differs from `Copy` in that `Copy` is implicit and inexpensive, while
/// `Clone` is always explicit and may or may not be expensive.
///
/// Since `Clone` is more general than `Copy`, you can automatically make anything
/// `Copy` be `Clone` as well.
///
/// ## Derivable
///
/// This trait can be used with `#[derive]` if all fields are `Clone`. The `derive`d
/// implementation of `Clone` calls `clone` on each field.
///
```

Question to @orizi: what's the compiler behavior when deriving a trait on a generic struct?

Would it be true to say that "For a generic struct, `#[derive]` implements `Clone` conditionally by adding bound `Clone` on generic parameters." (as in Rust) ? 
```
```

___
*[`corelib/src/clone.cairo` line 40 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6665#-OBtIpRc95az1q3gj53P:-OBtIpRc95az1q3gj53Q:b-fbxn3z) ([raw file](https://github.com/starkware-libs/cairo/blob/1d3150c2de7a2764e279c8eec48743ddd75bda1c/corelib/src/clone.cairo#L40)):*
> ```Cairo
> /// `Clone` trait defines the interface for cloning values.
> pub trait Clone<T> {
>     /// Takes a snapshot of a copyable value and returns a clone of that value.
> ```

T is not "copyable" here (if you mean a trait bound on +Copy<T>)



_Suggestion:_
```Cairo
/// Returns a copy of the value.
```

**Comment by TAdev0** [comment]
@orizi  any update regarding @enitrat  comment?

**Comment by TAdev0** [comment]
@orizi  ready for review

**Review by orizi — COMMENTED** [review]
no it isn't - as long as @enitrat is blocking i'm not having a look.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6665#-:-OCmP4XQ-ziOS6HpGa8f:bwcwmpo)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @enitrat and @TAdev0)

**Review by enitrat — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6665#-:-OCq7Lyt8iygbvPPgzm_:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6665#-:-OCqul-PB2DiFFmZoclN:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TAdev0)

**Pull request merged**
