### PR TITLE
use items to parser

### PR DESCRIPTION
**Pull request by Tomer-StarkWare**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6304)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6304)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/use` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6304#-O5OVSJ7C4EjTcWcGUcK:-O5OVSJ7C4EjTcWcGUcL:b-th5rd5) ([raw file](https://github.com/starkware-libs/cairo/blob/838dfe4b960c69682fb260dc5dff2c5099da6745/crates/cairo-lang-parser/src/parser_test_data/partial_trees/use#L9)):*
> ```
> mod X {
>     fn in_X() {}
> }
> ```

remove - as this is only helpful for semantics and is fully ignored here.

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6304)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @piotmag769, and @Tomer-StarkWare)

___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/use` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6304#-O5RrSRZ1odYgC6WQdTp:-O5RrSRZ1odYgC6WQdTq:b-nkqhaw) ([raw file](https://github.com/starkware-libs/cairo/blob/838dfe4b960c69682fb260dc5dff2c5099da6745/crates/cairo-lang-parser/src/parser_test_data/partial_trees/use#L2)):*
> ```
> //! > Test use
> ```

Add a test with attributes.

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6304)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/use` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6304#-O5RrSRZ1odYgC6WQdTp:-O5S0LDTEugU2PQlSkNn:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/838dfe4b960c69682fb260dc5dff2c5099da6745/crates/cairo-lang-parser/src/parser_test_data/partial_trees/use#L2)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Add a test with attributes.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/use` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6304#-O5OVSJ7C4EjTcWcGUcK:-O5S0LX20x9RAW90Vltg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/838dfe4b960c69682fb260dc5dff2c5099da6745/crates/cairo-lang-parser/src/parser_test_data/partial_trees/use#L9)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove - as this is only helpful for semantics and is fully ignored here.
</blockquote></details>

Done.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6304#-:-O5S2N1BElVj3ikSPN42:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6304#-:-O5SEogv-rQM2qkbBIAR:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, and @piotmag769)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6304)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @gilbens-starkware, and @mkaput)

**Pull request merged**
