### PR TITLE
Add version vs. discriminator docs section

### PR DESCRIPTION
**Pull request by mkaput**
**Stack**:
- #6470
- #6466 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6466)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6466#-:-O8ffd2h4_8IMBqMWiq1:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Review by piotmag769 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6466)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6466#-O8hFzGk5o8l8ajh98gM:-O8hFzGk5o8l8ajh98gN:bv59g4z) ([raw file](https://github.com/starkware-libs/cairo/blob/0da6763d5a3acee8e8d56e69dacb813cfa06eee7/crates/cairo-lang-filesystem/src/db.rs#L48)):*
> ```XML
>     /// The crate's version.
>     ///
>     /// ## Version vs. Discriminator
> ```

So we know what discriminator are we referring to



_Suggestion:_
```XML
/// ## `[CrateSettings::version]` vs. `[DependencySettings::discriminator]`
```

**Review by piotmag769 — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6466)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)

**Review by piotmag769 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6466#-:-O8hGhLDAyHll-TVy31B:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6466)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @orizi and @piotmag769)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6466#-O8hFzGk5o8l8ajh98gM:-O8k3cAH2TnkUuhW-jm-:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/0da6763d5a3acee8e8d56e69dacb813cfa06eee7/crates/cairo-lang-filesystem/src/db.rs#L48)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

So we know what discriminator are we referring to
</blockquote></details>

Done

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6466)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Pull request merged**
