### PR TITLE
feat(corelib): OptionTrait boolean operators

### PR DESCRIPTION
**Pull request by julio4**
## Boolean operators

These methods treat the [`Option`] as a boolean value, where [`Some`] acts like [`true`] and [`None`] acts like [`false`]. There are two categories of these methods: ones that take an [`Option`] as input, and ones that take a function as input (to be lazily evaluated).

The [`and`], [`or`], and [`xor`] methods take another [`Option`] as input, and produce an [`Option`] as output. Only the [`and`] method can produce an [`Option<U>`] value having a different inner type `U` than [`Option<T>`].

| method  | self      | input     | output    |
|---------|-----------|-----------|-----------|
| [`and`] | `None`    | (ignored) | `None`    |
| [`and`] | `Some(x)` | `None`    | `None`    |
| [`and`] | `Some(x)` | `Some(y)` | `Some(y)` |
| [`or`]  | `None`    | `None`    | `None`    |
| [`or`]  | `None`    | `Some(y)` | `Some(y)` |
| [`or`]  | `Some(x)` | (ignored) | `Some(x)` |
| [`xor`] | `None`    | `None`    | `None`    |
| [`xor`] | `None`    | `Some(y)` | `Some(y)` |
| [`xor`] | `Some(x)` | `None`    | `Some(x)` |
| [`xor`] | `Some(x)` | `Some(y)` | `None`    |

[`and`]: OptionTrait::and
[`or`]: OptionTrait::or
[`xor`]: OptionTrait::xor

The [`and_then`] and [`or_else`] methods take a function as input, and
only evaluate the function when they need to produce a new value. Only
the [`and_then`] method can produce an [`Option<U>`] value having a
different inner type `U` than [`Option<T>`].

| method       | self      | function input | function result | output    |
|--------------|-----------|----------------|-----------------|-----------|
| [`and_then`] | `None`    | (not provided) | (not evaluated) | `None`    |
| [`and_then`] | `Some(x)` | `x`            | `None`          | `None`    |
| [`and_then`] | `Some(x)` | `x`            | `Some(y)`       | `Some(y)` |
| [`or_else`]  | `None`    | (not provided) | `None`          | `None`    |
| [`or_else`]  | `None`    | (not provided) | `Some(y)`       | `Some(y)` |
| [`or_else`]  | `Some(x)` | (not provided) | (not evaluated) | `Some(x)` |

[`and_then`]: OptionTrait::and_then
[`or_else`]: OptionTrait::or_else

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6936)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @julio4)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6936#-OF4Iv9J3jLPSX90X5iw:-OF4Iv9J3jLPSX90X5ix:bd79guq) (no related file):*
@enitat @TomerStarkware 2nd eye

**Review by TomerStarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6936#-:-OF4hFsU8l53lMBPBVnj:bnfp4nl)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @julio4 and @orizi)

**Review by enitrat — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6936#-:-OF8r_Vf3wZw8nw7w5sq:bnfp4nl)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @julio4 and @orizi)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6936#-:-OFBmozX7lufBXlxP2L1:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @julio4)

**Pull request merged**
