### PR TITLE
Implemented a high level implementation of uint128 wide mul.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:75e2ced9

---

**Stack**:
- #1232
- #1231
- #1230
- #1229
- #1228
- #1227
- #1205 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by spapinistarkware — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1205)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/integer.cairo` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1205#-NIRt4IG4otrlXV2nvrD:-NIRt4IG4otrlXV2nvrE:b-bqpl98) ([raw file](https://github.com/starkware-libs/cairo/blob/47e68ac9e69760b7998d008e428af68140c6d82b/corelib/integer.cairo#L42)):*
> ```Cairo
> 
> // TODO(orizi): Change to extern when added.
> func uint128_wide_mul(
> ```

This doesn't make sense.
The basic extern func should return low and high.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1205)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`corelib/integer.cairo` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1205#-NIRt4IG4otrlXV2nvrD:-NISHQN5-Wbl6wliGBz4:bpgphqj) ([raw file](https://github.com/starkware-libs/cairo/blob/47e68ac9e69760b7998d008e428af68140c6d82b/corelib/integer.cairo#L42)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This doesn't make sense.
The basic extern func should return low and high.
</blockquote></details>

as discussed - this is what it does.

**Review by orizi — COMMENTED** [review]
> Dismissed @spapinistarkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1205)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1205)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`corelib/integer.cairo` line 47 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1205#-NIba5XS1lUmdFIwpWCd:-NIbc9ku1VR1Ud9RknjJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2d6bc59db5c3935841211c41eb39edfc3e5a6b29/corelib/integer.cairo#L47)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

document that this can't happen.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1205)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
