### PR TITLE
Dori/ec op builtin

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1657)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1657)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/cairo-lang-starknet/src/db.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1657#-NLH_d3pDnHeIc03ERRw:-NLH_d3pDnHeIc03ERRx:b44etou) ([raw file](https://github.com/starkware-libs/cairo/blob/1d3f21765609e2236f28d89e315068aa1b46edd4/crates/cairo-lang-starknet/src/db.rs#L19)):*
> ```XML
>     // Override implicit precedence for compatibility with the StarkNet OS.
>     db.set_implicit_precedence(Arc::new(
>         ["Pedersen", "RangeCheck", "Bitwise", "GasBuiltin", "System", "EcOp"]
> ```

this is certainly not the correct order.
i think it is:



_Suggestion:_
```XML
        ["Pedersen", "RangeCheck", "Bitwise", "EcOp", "GasBuiltin", "System"]
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1657)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/builtin_cost.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1657#-NLHaWzx4i0eRSAK5C_w:-NLHaWzx4i0eRSAK5C_x:b-glzqbo) ([raw file](https://github.com/starkware-libs/cairo/blob/1d3f21765609e2236f28d89e315068aa1b46edd4/crates/cairo-lang-sierra/src/extensions/modules/builtin_cost.rs#L49)):*
> ```XML
>             CostTokenType::Step => panic!("offset_in_builtin_costs is not supported for 'Step'."),
>             CostTokenType::Pedersen => 0,
>             CostTokenType::EcOp => 2,
> ```

why did you decide on this number?



_Code quote:_
```XML
            CostTokenType::EcOp => 2,
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1657)* status: 11 of 13 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/builtin_cost.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1657#-NLHaWzx4i0eRSAK5C_w:-NLKa6vQ4RuGQm--Llwj:b-wugq8q) ([raw file](https://github.com/starkware-libs/cairo/blob/1d3f21765609e2236f28d89e315068aa1b46edd4/crates/cairo-lang-sierra/src/extensions/modules/builtin_cost.rs#L49)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

because I'm prepping for [this](https://reviewable.io/reviews/starkware-libs/cairo/1629) to be merged first
</blockquote></details>

And actually, I just assumed sequential is fine. Where can I see the actual builtin cost buffer values?

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1657)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/builtin_cost.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1657#-NLHaWzx4i0eRSAK5C_w:-NLKbuPWAlGG5K2QMgvj:b-s5h9ax) ([raw file](https://github.com/starkware-libs/cairo/blob/1d3f21765609e2236f28d89e315068aa1b46edd4/crates/cairo-lang-sierra/src/extensions/modules/builtin_cost.rs#L49)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

And actually, I just assumed sequential is fine. Where can I see the actual builtin cost buffer values?
</blockquote></details>

It will be created in the OS, so this is fine
___
*[`crates/cairo-lang-starknet/src/db.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1657#-NLH_d3pDnHeIc03ERRw:-NLKbjsvBM5UiK2iGyv9:b-p7y7in) ([raw file](https://github.com/starkware-libs/cairo/blob/1d3f21765609e2236f28d89e315068aa1b46edd4/crates/cairo-lang-starknet/src/db.rs#L19)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Done. Where can I see the correct order?
</blockquote></details>

In the OS and in lamdaclass code

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1657#-:-NLKdnmi1R9NNqRnpQJj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1657)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
