### PR TITLE
Implement ec_finalize_state

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
Signed-off-by: Dori Medini <dori@starkware.co>

commit-id:0ec6f748

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1647)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1647)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1647#-NL1DTZVANmeZgSko25e:-NL1DTZVANmeZgSko25f:b7sa2ot) (no related file):*
(blocking note to self)
this can be slightly optimized: instead of allocating space on the AP stack for `random_neg_y` we can change the computation of the `numerator` depending on whether or not we are computing `p0 + p1` or `p0 - p1`.

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1647)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1647#-NL1DTZVANmeZgSko25e:-NLGixnP-PzCVI4jbc4P:b-fjin5x) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

(blocking note to self)
this can be slightly optimized: instead of allocating space on the AP stack for `random_neg_y` we can change the computation of the `numerator` depending on whether or not we are computing `p0 + p1` or `p0 - p1`.
</blockquote></details>

Done, in separate PR: https://reviewable.io/reviews/starkware-libs/cairo/1693

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1647)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1647#-NL1DTZVANmeZgSko25e:-NLGvZpA3RlU_E4gqqe-:b-hnui0k) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Done, in separate PR: https://reviewable.io/reviews/starkware-libs/cairo/1693
</blockquote></details>

Nevermind the above PR... this is better: https://reviewable.io/reviews/starkware-libs/cairo/1696

___

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 8 files at r1, 5 of 5 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1647#-:-NLH2ukO-GExZRhQUloL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1647)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1647)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 280 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1647#-NLHINPHDLCndYxfjleO:-NLHINPI5WxEPeezMcZ9:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/143306b2597753626e32a9e948d1445cbf366d16/crates/cairo-lang-casm/src/hints/mod.rs#L280)):*
> ```XML
>                 f,
>                 "
> ```





_Suggestion:_
```XML
            Hint::PrimeDiv { lhs, rhs, result } => write!(
                f,
                "memory{result} = fdiv({}, {})",
                ResOperandFormatter(lhs),
                ResOperandFormatter(rhs),
            ),
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1647)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 280 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1647#-NLHINPHDLCndYxfjleO:-NLHJLd2EOtE_5CTpZo1:byti3ag) ([raw file](https://github.com/starkware-libs/cairo/blob/143306b2597753626e32a9e948d1445cbf366d16/crates/cairo-lang-casm/src/hints/mod.rs#L280)):*
> ```XML
>                 f,
>                 "
> ```

1. never seen `fdiv` before but ok
2. all other functions have the extra whitespace, I remember Gil mentioning this is currently required... is it no longer needed?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1647)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 280 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1647#-NLHINPHDLCndYxfjleO:-NLHJjQpEHpEdAKlsDK1:b-xbtykp) ([raw file](https://github.com/starkware-libs/cairo/blob/143306b2597753626e32a9e948d1445cbf366d16/crates/cairo-lang-casm/src/hints/mod.rs#L280)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. never seen `fdiv` before but ok
2. all other functions have the extra whitespace, I remember Gil mentioning this is currently required... is it no longer needed?
</blockquote></details>

ah nevermind... required for `writedoc` not `write`

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1647)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
