### PR TITLE
Use patch builder in generate trait.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #4027
- #4025
- #4013
- #4019 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4019)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4019)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-plugins/src/plugins/generate_trait.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4019#-Ndf-I5K4OtY17gNfq2t:-Ndf-I5K4OtY17gNfq2u:bpf1w9q) ([raw file](https://github.com/starkware-libs/cairo/blob/49f7a849d436331ff2a9c540e3aed5756bb0193e/crates/cairo-lang-plugins/src/plugins/generate_trait.rs#L50)):*
> ```XML
>                     builder.add_str("#[");
>                     builder.add_modified(RewriteNode::new_trimmed(arg.as_syntax_node()));
>                     builder.add_str("]\n");
> ```

please use interpolate_patched("#[$attr$]").
It's much clearer.



_Code quote:_
```XML
                    builder.add_str("#[");
                    builder.add_modified(RewriteNode::new_trimmed(arg.as_syntax_node()));
                    builder.add_str("]\n");
```
___
*[`crates/cairo-lang-plugins/src/plugins/generate_trait.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4019#-Ndezued-iFBFhKbOc2J:-Ndezued-iFBFhKbOc2K:b-4h9zte) ([raw file](https://github.com/starkware-libs/cairo/blob/49f7a849d436331ff2a9c540e3aed5756bb0193e/crates/cairo-lang-plugins/src/plugins/generate_trait.rs#L136)):*
> ```XML
>                     if i != 0 {
>                         builder.add_str(", ");
>                     }
> ```

I prefer the first one to be handled separately before the for.



_Code quote:_
```XML
                    if i != 0 {
                        builder.add_str(", ");
                    }
```
___
*[`crates/cairo-lang-plugins/src/test_data/generate_trait` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4019#-Ndf3bLK4rdsu95bT5gx:-Ndf3bLK4rdsu95bT5gy:b-2bfwaq) ([raw file](https://github.com/starkware-libs/cairo/blob/49f7a849d436331ff2a9c540e3aed5756bb0193e/crates/cairo-lang-plugins/src/test_data/generate_trait#L94)):*
> ```
> #[some(attr)]
> #[other(attr2)]
> trait TraitWithAttrs<T> ;
> ```

Can you get rid of the space?



_Suggestion:_
```
WithAttrs<T>;
```
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 2059 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4019#-Ndf3tg8BEkiWcwRYA5I:-Ndf3tg8BEkiWcwRYA5J:bf1vhhn) ([raw file](https://github.com/starkware-libs/cairo/blob/49f7a849d436331ff2a9c540e3aed5756bb0193e/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L2059)):*
> ```
>         fn foo_l1_handler(ref self: ContractState);
>         fn foo_constructor(ref self: ContractState);
>     }
> ```

Can you remove the added indentation?



_Code quote:_
```
        fn foo_external(ref self: ContractState);
        fn foo_l1_handler(ref self: ContractState);
        fn foo_constructor(ref self: ContractState);
    }
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4019)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-plugins/src/plugins/generate_trait.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4019#-Ndf-I5K4OtY17gNfq2t:-NdiGmNO0Kk4-7vsLreW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/49f7a849d436331ff2a9c540e3aed5756bb0193e/crates/cairo-lang-plugins/src/plugins/generate_trait.rs#L50)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

please use interpolate_patched("#[$attr$]").
It's much clearer.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-plugins/src/plugins/generate_trait.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4019#-Ndezued-iFBFhKbOc2J:-NdiH6tRC7O6_ECJOiC_:bgyjzll) ([raw file](https://github.com/starkware-libs/cairo/blob/49f7a849d436331ff2a9c540e3aed5756bb0193e/crates/cairo-lang-plugins/src/plugins/generate_trait.rs#L136)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I prefer the first one to be handled separately before the for.
</blockquote></details>

i don't want to duplicate the rest of the loop.
___
*[`crates/cairo-lang-plugins/src/test_data/generate_trait` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4019#-Ndf3bLK4rdsu95bT5gx:-NdiIYjz2tdlNWK8KHZi:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/49f7a849d436331ff2a9c540e3aed5756bb0193e/crates/cairo-lang-plugins/src/test_data/generate_trait#L94)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Can you get rid of the space?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 2059 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4019#-Ndf3tg8BEkiWcwRYA5I:-NdiIfWn6MB9yedtRqGs:bex96iq) ([raw file](https://github.com/starkware-libs/cairo/blob/49f7a849d436331ff2a9c540e3aed5756bb0193e/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L2059)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Can you remove the added indentation?
</blockquote></details>

these aren't really extra spaces - these are the original spaces.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4019)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-plugins/src/plugins/generate_trait.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4019#-Ndezued-iFBFhKbOc2J:-NdisDPpEb4AXffs4mkD:butvlp2) ([raw file](https://github.com/starkware-libs/cairo/blob/49f7a849d436331ff2a9c540e3aed5756bb0193e/crates/cairo-lang-plugins/src/plugins/generate_trait.rs#L136)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i don't want to duplicate the rest of the loop.
</blockquote></details>

You can extract to a function then
___
*[`crates/cairo-lang-plugins/src/plugins/generate_trait.rs` line 74 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4019#-NdiuXnS7DuckaD9GrEY:-NdiuXnTBcJHdrKs7kDq:b4fis38) ([raw file](https://github.com/starkware-libs/cairo/blob/8b63a35be73a1f381223fd720bb792dd9691b0c6/crates/cairo-lang-plugins/src/plugins/generate_trait.rs#L74)):*
> ```XML
>     }
>     builder.add_str(extra_ident);
>     builder.add_str("trait ");
> ```

Can add at once.



_Code quote:_
```XML
    builder.add_str(extra_ident);
    builder.add_str("trait ");
```
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 2059 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4019#-Ndf3tg8BEkiWcwRYA5I:-Ndiv4wZC8Wy5SBN5D8z:b3vdc9m) ([raw file](https://github.com/starkware-libs/cairo/blob/49f7a849d436331ff2a9c540e3aed5756bb0193e/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L2059)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

these aren't really extra spaces - these are the original spaces.
</blockquote></details>

They are added relative to before this PR, but I agree it's OK.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4019)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-plugins/src/plugins/generate_trait.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4019#-Ndezued-iFBFhKbOc2J:-Ndivvcb-tTBLxY7wMYN:bt5cyki) ([raw file](https://github.com/starkware-libs/cairo/blob/49f7a849d436331ff2a9c540e3aed5756bb0193e/crates/cairo-lang-plugins/src/plugins/generate_trait.rs#L136)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

You can extract to a function then
</blockquote></details>

this would be less readable
___
*[`crates/cairo-lang-plugins/src/plugins/generate_trait.rs` line 74 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4019#-NdiuXnS7DuckaD9GrEY:-Ndiw64W5xIJHpFHd3Lg:b-b42d5q) ([raw file](https://github.com/starkware-libs/cairo/blob/8b63a35be73a1f381223fd720bb792dd9691b0c6/crates/cairo-lang-plugins/src/plugins/generate_trait.rs#L74)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Can add at once.
</blockquote></details>

only if i create an additional string that isn't actually required.

**Review by yuvalsw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4019)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-plugins/src/plugins/generate_trait.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4019#-Ndezued-iFBFhKbOc2J:-Ndk6SHcB5gag8eDcrTW:b-aixkr8) ([raw file](https://github.com/starkware-libs/cairo/blob/49f7a849d436331ff2a9c540e3aed5756bb0193e/crates/cairo-lang-plugins/src/plugins/generate_trait.rs#L136)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this would be less readable
</blockquote></details>

why? This function is super long anyway...
But again, I don't insist here - your call.
___
*[`crates/cairo-lang-plugins/src/plugins/generate_trait.rs` line 74 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4019#-NdiuXnS7DuckaD9GrEY:-Ndk4yyd6S3933c_zeYu:bywo9i7) ([raw file](https://github.com/starkware-libs/cairo/blob/8b63a35be73a1f381223fd720bb792dd9691b0c6/crates/cairo-lang-plugins/src/plugins/generate_trait.rs#L74)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

only if i create an additional string that isn't actually required.
</blockquote></details>

I meant `builder.add_str(&format!("{extra_indent}trait "));`. Seems clearer to me, but your call.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4019)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-plugins/src/plugins/generate_trait.rs` line 74 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4019#-NdiuXnS7DuckaD9GrEY:-Ndk7kaC9HJKThab7ESj:b-10104z) ([raw file](https://github.com/starkware-libs/cairo/blob/8b63a35be73a1f381223fd720bb792dd9691b0c6/crates/cairo-lang-plugins/src/plugins/generate_trait.rs#L74)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I meant `builder.add_str(&format!("{extra_indent}trait "));`. Seems clearer to me, but your call.
</blockquote></details>

I understood, I don't see much of a benefit

**Pull request merged**
