### PR TITLE
Add circuit_failure_guarantee_verify.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5692)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5692)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/circuit.cairo` line 190 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5692#-Nz8BUiiALgZXOMt3xDH:-Nz8BUiiALgZXOMt3xDI:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/3e21a59eb045cbb5e9fe67d771dd0139da033aa7/corelib/src/circuit.cairo#L190)):*
> ```Cairo
> 
> 
> /// Verifies the guarantee and getting rid of it.
> ```





_Suggestion:_
```Cairo
/// Verifies the guarantee in order to drop it.
```
___
*[`corelib/src/circuit.cairo` line 192 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5692#-Nz8BJCJAbSnp0LJ7QkR:-Nz8BJCJAbSnp0LJ7QkS:b-ktoa05) ([raw file](https://github.com/starkware-libs/cairo/blob/3e21a59eb045cbb5e9fe67d771dd0139da033aa7/corelib/src/circuit.cairo#L192)):*
> ```Cairo
> /// Verifies the guarantee and getting rid of it.
> extern fn circuit_failure_guarantee_verify<C>(
>     guarantee: CircuitFailureGuarantee<C>, zero: ConstZero, one: ConstOne,
> ```

consider already adding a destructor for the type.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5692)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/circuit.cairo` line 192 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5692#-Nz8BJCJAbSnp0LJ7QkR:-NzMUeH91D5bEHYlm9_0:b-9s8od5) ([raw file](https://github.com/starkware-libs/cairo/blob/3e21a59eb045cbb5e9fe67d771dd0139da033aa7/corelib/src/circuit.cairo#L192)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

consider already adding a destructor for the type.
</blockquote></details>

let's do that in a separate PR.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5692)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/circuit.cairo` line 190 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5692#-Nz8BUiiALgZXOMt3xDH:-NzMVZOeBoZMi8-1KGLR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3e21a59eb045cbb5e9fe67d771dd0139da033aa7/corelib/src/circuit.cairo#L190)):*
> ```Cairo
> 
> 
> /// Verifies the guarantee and getting rid of it.
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5692)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/circuit.rs` line 419 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5692#-NzN7q5PAl4HgvSfJSfV:-NzN7q5PAl4HgvSfJSfW:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/abf39e7a34fcabd48dc754464cfd58fee13c3469/crates/cairo-lang-sierra/src/extensions/modules/circuit.rs#L419)):*
> ```XML
>                 storable: true,
>                 zero_sized: false,
>             },
> ```





_Suggestion:_
```XML
                },
                duplicatable: false,
                droppable: false,
                storable: true,
                zero_sized: false,
            },
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs` line 353 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5692#-NzN95_V6IY01T9flJ51:-NzN95_V6IY01T9flJ52:b-punpc9) ([raw file](https://github.com/starkware-libs/cairo/blob/abf39e7a34fcabd48dc754464cfd58fee13c3469/crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs#L353)):*
> ```XML
>              n_mul_mods: one, mul_mod_offsets: mul_mod_offsets,
>              modulus: modulus0
>         };
> ```

is this a place holder?
you just need to find the inverse proof - no?



_Code quote:_
```XML
        hint CoreHint::EvalCircuit {
             values_ptr: failing_value_ptr,
             n_add_mods: zero, add_mod_offsets: mul_mod_offsets,
             n_mul_mods: one, mul_mod_offsets: mul_mod_offsets,
             modulus: modulus0
        };
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5692)* status: 2 of 9 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/circuit.rs` line 419 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5692#-NzN7q5PAl4HgvSfJSfV:-NzRoQ2m8po6lzqtxlpz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/abf39e7a34fcabd48dc754464cfd58fee13c3469/crates/cairo-lang-sierra/src/extensions/modules/circuit.rs#L419)):*
> ```XML
>                 storable: true,
>                 zero_sized: false,
>             },
> ```

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5692)* status: 2 of 9 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs` line 353 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5692#-NzN95_V6IY01T9flJ51:-NzRoRXy0aWKVM2sPzjl:brpmqc3) ([raw file](https://github.com/starkware-libs/cairo/blob/abf39e7a34fcabd48dc754464cfd58fee13c3469/crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs#L353)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is this a place holder?
you just need to find the inverse proof - no?
</blockquote></details>

removed.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5692#-:-NzRtLJf3Zbb8aM7yYZ-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5692)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs` line 373 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5692#-NzTfXE9Dxuy7itE8aM6:-NzTfXE9Dxuy7itE8aM7:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6910f212667dd50d63b3cfcac9e99fb3242ab693/crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs#L373)):*
> ```XML
> 
>         done:
>         const mul_mod_usage = BUILTIN_INSTANCE_SIZE;
> ```





_Suggestion:_
```XML
        tempvar nullifier3 = nullifier_ptr[3];
        jump Done if nullifier0 != 0;
        jump Done if nullifier1 != 0;
        jump Done if nullifier2 != 0;
        jump Done if nullifier3 != 0;

        // If the nullifer is zero, enter an infinite loop.
        infinite_loop:
        jump infinite_loop;

    Done:
        const mul_mod_usage = BUILTIN_INSTANCE_SIZE;
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs` line 376 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5692#-NzTfewRA48sk4swDvXt:-NzTfewRA48sk4swDvXu:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6910f212667dd50d63b3cfcac9e99fb3242ab693/crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs#L376)):*
> ```XML
>         let new_mul_mod = mul_mod + mul_mod_usage;
> 
>         // TODO: Verify that 0 nullifier < modulues.
> ```





_Suggestion:_
```XML
        // TODO(..): Verify that 0 nullifier < modulues.
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5692)* status: 5 of 9 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs` line 373 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5692#-NzTfXE9Dxuy7itE8aM6:-NzWsEk-6kACbTvsN3GG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6910f212667dd50d63b3cfcac9e99fb3242ab693/crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs#L373)):*
> ```XML
> 
>         done:
>         const mul_mod_usage = BUILTIN_INSTANCE_SIZE;
> ```

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs` line 376 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5692#-NzTfewRA48sk4swDvXt:-NzWsDsy0aN0L6vZxQSq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6910f212667dd50d63b3cfcac9e99fb3242ab693/crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs#L376)):*
> ```XML
>         let new_mul_mod = mul_mod + mul_mod_usage;
> 
>         // TODO: Verify that 0 nullifier < modulues.
> ```

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 4 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5692)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
