### PR TITLE
Fix issue #2820

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2836)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2836** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2836" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2836?utm_source=stack-comment).

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2836)* status: 6 of 9 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`tests/bug_samples/issue2820.cairo` line 4 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2836#-NT9YFK8CeCXj4r_qVtm:-NT9YFK8CeCXj4r_qVtn:b-m27nif) ([raw file](https://github.com/starkware-libs/cairo/blob/217a48c65244de06d00ff27853b9c0c8360a47ca/tests/bug_samples/issue2820.cairo#L4)):*
> ```Cairo
> 
> fn foo(ref item_index: usize, index: usize) {
>     gas::withdraw_gas_all(get_builtin_costs()).expect('Out of gas');
> ```

is this needed?



_Code quote:_
```Cairo
gas::withdraw_gas_all(get_builtin_costs()).expect('Out of gas')
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2836)* status: 6 of 9 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`tests/bug_samples/issue2820.cairo` line 4 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2836#-NT9YFK8CeCXj4r_qVtm:-NT9YuKq2QrLipFHsfIU:bbrxhuc) ([raw file](https://github.com/starkware-libs/cairo/blob/217a48c65244de06d00ff27853b9c0c8360a47ca/tests/bug_samples/issue2820.cairo#L4)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

is this needed?
</blockquote></details>

It's recursive. It didn't pop the error without that call.

**Comment by ilyalesokhin-starkware** [comment]
*[`tests/bug_samples/issue2820.cairo` line 4 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2836#-NT9YFK8CeCXj4r_qVtm:-NT9Z68_4dpiRyCkZ7sy:b-d459hl) ([raw file](https://github.com/starkware-libs/cairo/blob/217a48c65244de06d00ff27853b9c0c8360a47ca/tests/bug_samples/issue2820.cairo#L4)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

It's recursive. It didn't pop the error without that call.
</blockquote></details>

Can't you just use index after the 'if'?



_Code quote:_
```Cairo
index
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2836)* status: 6 of 12 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`tests/bug_samples/issue2820.cairo` line 4 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2836#-NT9YFK8CeCXj4r_qVtm:-NTC20d979KMCsmVDXjI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/217a48c65244de06d00ff27853b9c0c8360a47ca/tests/bug_samples/issue2820.cairo#L4)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Can't you just use index after the 'if'?
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 9 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2836#-:-NTCfq7-22sNyyTI-Ch9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
