### PR TITLE
sync write! and writeln! diagnostics tests

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4592)

### CODE REVIEW

**Comment by yuvalsw** [comment]
change target branch

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4592#-:-NlwhBKB43lSqZEUGOBA:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/inline_macros` line 336 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4592#-NlwgxPXEF_BlHfdjoKX:-NlwgxPXEF_BlHfdjoKY:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8f3bcf78e72bb3cfdd21484c09fb3201f156e7fe/crates/cairo-lang-semantic/src/expr/test_data/inline_macros#L336)):*
> ```
>     writeln!(f, "{x|}");
>     writeln!(f, "{");
>     writeln!(f, "{x");
> ```





_Suggestion:_
```
   // Badly terminated `{`.
   writeln!(f, "{?}");
   writeln!(f, "{x|}");
   writeln!(f, "{");
   writeln!(f, "{x");
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4592)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/inline_macros` line 336 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4592#-NlwgxPXEF_BlHfdjoKX:-Nlwp5nu0LMHpWQTOdGI:b-kflyd4) ([raw file](https://github.com/starkware-libs/cairo/blob/8f3bcf78e72bb3cfdd21484c09fb3201f156e7fe/crates/cairo-lang-semantic/src/expr/test_data/inline_macros#L336)):*
> ```
>     writeln!(f, "{x|}");
>     writeln!(f, "{");
>     writeln!(f, "{x");
> ```

I can change to "badly indented" ;)
Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4592#-:-NlwyudcBmnWdY2AzCj0:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
