### PR TITLE
Feat/return empty

### PR DESCRIPTION
**Pull request by gaetbout**
The return and break expression have to return something, and this something is mandatory.
In the case of returning unit type, it was mandatory to make it explicit by adding ();
```rust
return ();
break ();
```

With this PR it is not mandatory anymore. These will be added automatically:
```rust
return;
break;
```

This should fix https://github.com/starkware-libs/cairo/issues/3034

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3134)

### CODE REVIEW

**Comment by gaetbout** [comment]
@spapinistarkware Thanks for all the help you provided, I hope this fits SW requirements and solve the issue

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 15 of 18 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3134)* status: all files reviewed, 3 unresolved discussions (waiting on @gaetbout)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 329 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3134#-NVPavcY0T_zc-AThPET:-NVPavcZD8mtGbHomO2d:b-saamqy) ([raw file](https://github.com/starkware-libs/cairo/blob/df9b0b46c715ffd6ac853b38b301bdf4b0d168f0/crates/cairo-lang-lowering/src/lower/mod.rs#L329)):*
> ```XML
>         | semantic::Statement::Break(semantic::StatementBreak { expr_option, stable_ptr }) => {
>             log::trace!("Lowering a return | break statement.");
>             match expr_option {
> ```

Only ret_var is different. Unite two branches as much as possible.
___
*[`crates/cairo-lang-lowering/src/lower/usage.rs` line 102 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3134#-NVPb6CDBhLiQdmow80x:-NVPb6CDBhLiQdmow80y:bm2lcb1) ([raw file](https://github.com/starkware-libs/cairo/blob/df9b0b46c715ffd6ac853b38b301bdf4b0d168f0/crates/cairo-lang-lowering/src/lower/usage.rs#L102)):*
> ```XML
>                         }
>                         Statement::Continue(_) => (),
>                         Statement::Return(stmt) => match stmt.expr_option {
> ```

Use .map()
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1843 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3134#-NVPcIjODV4NtKOHi3d1:-NVPcIjODV4NtKOHi3d2:bsw1nfx) ([raw file](https://github.com/starkware-libs/cairo/blob/df9b0b46c715ffd6ac853b38b301bdf4b0d168f0/crates/cairo-lang-semantic/src/expr/compute.rs#L1843)):*
> ```XML
>                 return Err(ctx.diagnostics.report(return_syntax, ReturnNotAllowedInsideALoop));
>             }
> ```

More code reuse. Less indentation. For now example, in both branches, I would just do
let (expr_option, expr_ty) = match ...
old code...

**Comment by gaetbout** [comment]
@spapinistarkware due to type mismatch I had to modify compute.rs.
Probably I'm missing smthng, let me know

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3134#-:-NV_3RSb0Q9R4BM32Pp4:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gaetbout)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 15 of 18 files at r1, 1 of 3 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3134)* status: all files reviewed, 2 unresolved discussions (waiting on @gaetbout)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3134#-NV_LnVT4XkGGhFH_UO_:-NV_LnVT4XkGGhFH_UOa:bpyjakl) (no related file):*
please add diagnostics tests that `break;`and `return;` provides sensible diagnostics when they don't make sense.

___

**Comment by gaetbout** [comment]
Hi @orizi 
I hope I did what you were asking me 😅 
Otherwise, could you please provide some pointer on what I should be looking at?

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3134)* status: 19 of 20 files reviewed, 3 unresolved discussions (waiting on @gaetbout and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/loop` line 137 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3134#-NVcCGLECjtixLzQCXQF:-NVcCGLF6bFjt2jYrYzw:be8s9x3) ([raw file](https://github.com/starkware-libs/cairo/blob/c4d3f2375dc875f14694c30745a7b15ed52f3ea3/crates/cairo-lang-semantic/src/expr/test_data/loop#L137)):*
> ```
> //! > module_code
> 
> //! > expected_diagnostics
> ```

some diagnostic needs to appear here - `()` is not a valid bool.



_Code quote:_
```
//! > expected_diagnostics
```

**Review by orizi — COMMENTED** [review]
looks good - just one last comment :)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3134#-:-NVcCZTc37wiZvURXYmB:b-jzrvv3)* status: 19 of 20 files reviewed, 2 unresolved discussions (waiting on @gaetbout and @spapinistarkware)

**Comment by gaetbout** [comment]
@orizi 
As no test is red, it appears I'm missing something somewhere, isn't it?

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
Ori left a comment

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3134#-:-NVcOFli83HwSDMbXbwv:bbvwu1y)* status: 19 of 20 files reviewed, 2 unresolved discussions (waiting on @gaetbout and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1864 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3134#-NVcOUkj0cV3gr_5xleA:-NVcOUkj0cV3gr_5xleB:b-ffnp6w) ([raw file](https://github.com/starkware-libs/cairo/blob/f19fcf032c04f59c665af1e206e28d6298eef984/crates/cairo-lang-semantic/src/expr/compute.rs#L1864)):*
> ```XML
>                             WrongReturnType { expected_ty, actual_ty: expr_ty },
>                         );
>                     }
> ```

This should be outside



_Code quote:_
```XML
                    let expr_ty = expr.ty();
                    let expected_ty = ctx
                        .get_signature(
                            return_syntax.stable_ptr().untyped(),
                            UnsupportedOutsideOfFunctionFeatureName::ReturnStatement,
                        )?
                        .return_type;
                    if !expected_ty.is_missing(db)
                        && !expr_ty.is_missing(db)
                        && ctx.resolver.inference().conform_ty(expr_ty, expected_ty).is_err()
                    {
                        ctx.diagnostics.report(
                            &expr_syntax,
                            WrongReturnType { expected_ty, actual_ty: expr_ty },
                        );
                    }
```

**Comment by gaetbout** [comment]
@orizi 
Should be fine now 😄 
Tried to extract some code out but due to miss-matched type I couldn't...
Maybe there is a way to make the last argument matching?
(Option<Id<Expr>>, TypeId, ???)
Couldn't find a matching type between `OptionExprClauseEmpty` and `ExprClause`

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3134)* status: 19 of 20 files reviewed, 2 unresolved discussions (waiting on @gaetbout and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1861 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3134#-NVcbXHwDMOr5O6yUgxA:-NVcbXHwDMOr5O6yUgxB:b-1la93n) ([raw file](https://github.com/starkware-libs/cairo/blob/993bd76fefa9b053c674171183bbbf8562504630/crates/cairo-lang-semantic/src/expr/compute.rs#L1861)):*
> ```XML
>                             WrongReturnType { expected_ty, actual_ty: expr_ty },
>                         );
>                     }
> ```

extract this into a closure or something just before (as it is basically the same code



_Code quote:_
```XML
                    let expected_ty = ctx
                        .get_signature(
                            return_syntax.stable_ptr().untyped(),
                            UnsupportedOutsideOfFunctionFeatureName::ReturnStatement,
                        )?
                        .return_type;
                    if !expected_ty.is_missing(db)
                        && !expr_ty.is_missing(db)
                        && ctx.resolver.inference().conform_ty(expr_ty, expected_ty).is_err()
                    {
                        ctx.diagnostics.report(
                            &empty_clause,
                            WrongReturnType { expected_ty, actual_ty: expr_ty },
                        );
                    }
```

**Comment by gaetbout** [comment]
@orizi 
Should be fine now 🥳

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3134#-:-NVd6_cJCqm6iLE3C5Tf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gaetbout)

**Review by spapinistarkware — APPROVED** [review]

**Pull request merged**
