### PR TITLE
Updated u256-divmod to be guarantee based.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3402)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3402)* status: 1 of 8 files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3402#-NXoMMy357d-K_h7_F4M:-NXoMMy357d-K_h7_F4N:btqer9n) ([raw file](https://github.com/starkware-libs/cairo/blob/96a4b269366beb942226899d0a80d37a5a4c8435/crates/cairo-lang-casm/src/hints/mod.rs#L134)):*
> ```XML
>     #[codec(index = 4)]
>     DivMod { lhs: ResOperand, rhs: ResOperand, quotient: CellRef, remainder: CellRef },
>     /// Divides dividend_low<<128+dividend_high by divisor_low<<128+divisor_high.
> ```

Fix docs

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3402)* status: 1 of 8 files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @spapinistarkware)

___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3402#-NXoMMy357d-K_h7_F4M:-NXoWtrGBCnYS0581fXp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/96a4b269366beb942226899d0a80d37a5a4c8435/crates/cairo-lang-casm/src/hints/mod.rs#L134)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Fix docs
</blockquote></details>

Done.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, 5 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3402)* status: 6 of 8 files reviewed, 4 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned256.rs` line 116 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3402#-NXtksHiDT5yoU3AkR1n:-NXtksHiDT5yoU3AkR1o:byy6ns9) ([raw file](https://github.com/starkware-libs/cairo/blob/df8b6f428d69e329e5a9b093bf897dfad16ed8ed/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned256.rs#L116)):*
> ```XML
>     casm_build_extend! {casm_builder,
>         // Validating `quotient * divisor + remainder - dividend = 0`.
>         // Validate limb0.
> ```

Add comments like before.
e.g. They are bounded by ? sop no overflow can happen.
The result is in [...]
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned256.rs` line 119 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3402#-NXtlAIO4DBjPGbkPfBb:-NXtlAIO4DBjPGbkPfBc:bvzg6ae) ([raw file](https://github.com/starkware-libs/cairo/blob/df8b6f428d69e329e5a9b093bf897dfad16ed8ed/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned256.rs#L119)):*
> ```XML
>         tempvar part0 = q0d0_low + remainder0;
>         tempvar part1 = part0 - dividend0;
>         tempvar leftover = part1 / u128_limit;
> ```

` Divide by 2**128 and check that we got an integer in [?,?)`
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned256.rs` line 136 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3402#-NXtm2Rh6Wz6P0Sxy7YO:-NXtm2Rh6Wz6P0Sxy7YP:bwm8e9o) ([raw file](https://github.com/starkware-libs/cairo/blob/df8b6f428d69e329e5a9b093bf897dfad16ed8ed/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned256.rs#L136)):*
> ```XML
>         tempvar quotient0_less_than_divisor1;
>         hint TestLessThan { lhs: quotient0, rhs: divisor1 } into { dst: quotient0_less_than_divisor1 };
>         jump QUOTIENT0_LESS_THAN_DIVISOR1 if quotient0_less_than_divisor1 != 0;
> ```

Make sure to add tests for all 4 cases

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3402#-:-NXu63EuBVsAn0yYxjsh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
