### PR TITLE
added impls to impl-lookup for impls impls

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5856)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 7 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5856)* status: 7 of 10 files reviewed, 3 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 1198 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5856#-O0566520kwRrFlBlmGv:-O0566520kwRrFlBlmGw:b-vbhx5g) ([raw file](https://github.com/starkware-libs/cairo/blob/68c8b65d1e02b85fbb82ddf27823b7d3038e33ac/crates/cairo-lang-semantic/src/expr/inference.rs#L1198)):*
> ```XML
>                     }
>                     ImplLongId::ImplImpl(impl_impl) => {
>                         assert!(impl_impl.impl_id().is_var_free(self.db));
> ```

add explanation for the assertions.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1503 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5856#-O056hVj7AFeRuNMRl81:-O056hVj7AFeRuNMRl82:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/68c8b65d1e02b85fbb82ddf27823b7d3038e33ac/crates/cairo-lang-semantic/src/items/imp.rs#L1503)):*
> ```XML
>                 }
>             }
>         }
> ```





_Suggestion:_
```XML
        let Ok(imps) = match module_or_impl_id {
            ImplOrModuleById::Module(module_id) => {
                db.module_impl_ids_for_trait_filter(*module_id, filter.clone())
            },
            ImplOrModuleById::Impl(impl_id) => {
                db.impl_impl_ids_for_trait_filter(*impl_id, filter.clone())
            }
        } else {
            continue;
        }
        for imp in imps {
            res.insert(imp);
        }
```
___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 1189 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5856#-O0575OAD3UouKH6xdTz:-O0575OBDdErBctP1zlj:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/68c8b65d1e02b85fbb82ddf27823b7d3038e33ac/crates/cairo-lang-semantic/src/items/tests/trait#L1189)):*
> ```
> //! > ==========================================================================
> 
> //! > ==========================================================================
> ```

?



_Code quote:_
```
//! > ==========================================================================

//! > ==========================================================================
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5856)* status: 5 of 10 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 1198 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5856#-O0566520kwRrFlBlmGv:-O0888-O-bd_Lfyv6QVl:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/68c8b65d1e02b85fbb82ddf27823b7d3038e33ac/crates/cairo-lang-semantic/src/expr/inference.rs#L1198)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add explanation for the assertions.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1503 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5856#-O056hVj7AFeRuNMRl81:-O088m1876Trbja_ddcB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/68c8b65d1e02b85fbb82ddf27823b7d3038e33ac/crates/cairo-lang-semantic/src/items/imp.rs#L1503)):*
> ```XML
>                 }
>             }
>         }
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 1189 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5856#-O0575OAD3UouKH6xdTz:-O088sNkCobxdBfGlOlV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/68c8b65d1e02b85fbb82ddf27823b7d3038e33ac/crates/cairo-lang-semantic/src/items/tests/trait#L1189)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 10 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5856#-:-O096I7T07hcwe_NIItq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5856)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5856#-:-O09bck_9XIxc26zw9ty:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
