### PR TITLE
support match on felt252

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4284)

### CODE REVIEW

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4284)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @orizi and @TomerStarkware)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4284#-Nh72ln6-CPrjKRwdFLp):*
Squash as disscussed.



_Code quote:_
```
- 4b715d6: support match on felt252

- 282637c: mend

- 656bd54: mend
```
___
*[`crates/cairo-lang-lowering/src/test_data/match` line 24 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4284#-Nh73UC573ReD1U2l0t1:-Nh73UC573ReD1U2l0t2:b-sxczls) ([raw file](https://github.com/starkware-libs/cairo/blob/656bd5498102aef5069e5f9f10ca59acbcce7421/crates/cairo-lang-lowering/src/test_data/match#L24)):*
> ```
> 
> //! > lowering_diagnostics
> error: Unsupported match arm - variants must be the same order as enum declaration.
> ```

That's not an enum match, change the diagnostic.
___
*[`crates/cairo-lang-lowering/src/test_data/match` line 287 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4284#-Nh731yL1Z2zWcuZdhMv:-Nh731yL1Z2zWcuZdhMw:b-2sub08) ([raw file](https://github.com/starkware-libs/cairo/blob/656bd5498102aef5069e5f9f10ca59acbcce7421/crates/cairo-lang-lowering/src/test_data/match#L287)):*
> ```
> 
> //! > lowering_diagnostics
> error: Match is Non Exhaustive - ensure that all possible cases are being handled by adding a match arm with a wildcard pattern or an explicit pattern
> ```

If possible, add an error specific for the match of `felt252`, the "pattern" is more about enums.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4284)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4284#-Nh72ln6-CPrjKRwdFLp):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Squash as disscussed.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/test_data/match` line 24 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4284#-Nh73UC573ReD1U2l0t1:-Nh7FmUKAVPoIC8bLKIh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/656bd5498102aef5069e5f9f10ca59acbcce7421/crates/cairo-lang-lowering/src/test_data/match#L24)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

That's not an enum match, change the diagnostic.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/test_data/match` line 287 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4284#-Nh731yL1Z2zWcuZdhMv:-Nh7FzFi1s5orRDmRXaF:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/656bd5498102aef5069e5f9f10ca59acbcce7421/crates/cairo-lang-lowering/src/test_data/match#L287)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

If possible, add an error specific for the match of `felt252`, the "pattern" is more about enums.
</blockquote></details>

Done

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, 1 of 4 files at r2, 2 of 3 files at r4, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4284)* status: 6 of 9 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`examples/fib_match.cairo` line 10 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4284#-NhGq0dY2xCTQinP_kKR:-NhGq0dY2xCTQinP_kKS:b8e5sd8) ([raw file](https://github.com/starkware-libs/cairo/blob/61de34975167b07ca287fd09bb209bdac98c94f9/examples/fib_match.cairo#L10)):*
> ```Cairo
>         4 => 5,
>         _ => { fib(n - 1) + fib(n - 2) }
>     }
> ```

consider (just to make getting the extra values make algorithmic sense)



_Suggestion:_
```Cairo
    match n {
        0 => 1,
        1 => 1,
        2 => 2,
        3 => 3,
        4 => 5,
        _ => { 5 * fib(n - 4) + 3 * fib(n - 5) }
    }
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4284)* status: 5 of 9 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/test_data/match` line 17 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4284#-NhLO2v3EaQ41rU8xETF:-NhLO2v3EaQ41rU8xETG:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/61de34975167b07ca287fd09bb209bdac98c94f9/crates/cairo-lang-lowering/src/test_data/match#L17)):*
> ```
> 
> //! > function_name
> foo1
> ```





_Suggestion:_
```
//! > function
fn foo(a: felt252) -> felt252 {
  let b=match a {
    5=> {550},
    6 => {70},
    _=>{90}
  };
  return b;
}

//! > function_name
foo
```
___
*[`crates/cairo-lang-lowering/src/test_data/match` line 256 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4284#-NhLPA0e0hdy8naMu2Iu:-NhLPA0e0hdy8naMu2Iv:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/61de34975167b07ca287fd09bb209bdac98c94f9/crates/cairo-lang-lowering/src/test_data/match#L256)):*
> ```
> //! > lowering_diagnostics
> error: Unsupported match arm - numbers must be sequential starting from 0
>  --> lib.cairo:4:7
> ```





_Suggestion:_
```
error: Unsupported match arm - numbers must be sequential starting from 0.
 --> lib.cairo:4:7
```
___
*[`crates/cairo-lang-lowering/src/test_data/match` line 287 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4284#-NhLP6Ad4TNRyrk9ZTwO:-NhLP6Ad4TNRyrk9ZTwP:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/61de34975167b07ca287fd09bb209bdac98c94f9/crates/cairo-lang-lowering/src/test_data/match#L287)):*
> ```
> 
> //! > lowering_diagnostics
> error: Match is Non Exhaustive - ensure that all possible cases are being handled by adding a match arm with a wildcard pattern
> ```





_Suggestion:_
```
Match is non exhaustive - ensure that all possible cases are being handled by adding a match arm with a wildcard pattern.
```
___
*[`crates/cairo-lang-sierra-generator/src/block_generator_test_data/match` line 54 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4284#-NhLORJvE6ZYwDkGQIyI:-NhLORJvE6ZYwDkGQIyJ:buka4lz) ([raw file](https://github.com/starkware-libs/cairo/blob/f720efa106157f38674421922a0a28ea24fa04a9/crates/cairo-lang-sierra-generator/src/block_generator_test_data/match#L54)):*
> ```
>   Match(match core::felt252_is_zero(v0) {
>     IsZeroResult::Zero => blk1,
>     IsZeroResult::NonZero(v3) => blk2,
> ```

can you prevent the ids here from changing?
(or explain well enough why they *should* change)



_Code quote:_
```
(v3)
```

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4284)* status: 7 of 9 files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4284)* status: 4 of 9 files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/test_data/match` line 17 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4284#-NhLO2v3EaQ41rU8xETF:-NhLkCwo6XcYmxj7CxpA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/61de34975167b07ca287fd09bb209bdac98c94f9/crates/cairo-lang-lowering/src/test_data/match#L17)):*
> ```
> 
> //! > function_name
> foo1
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/test_data/match` line 256 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4284#-NhLPA0e0hdy8naMu2Iu:-NhLkETr3NtNdvUD_F05:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/61de34975167b07ca287fd09bb209bdac98c94f9/crates/cairo-lang-lowering/src/test_data/match#L256)):*
> ```
> //! > lowering_diagnostics
> error: Unsupported match arm - numbers must be sequential starting from 0
>  --> lib.cairo:4:7
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/test_data/match` line 287 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4284#-NhLP6Ad4TNRyrk9ZTwO:-NhLkG6o5ZoaVUthM01m:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/61de34975167b07ca287fd09bb209bdac98c94f9/crates/cairo-lang-lowering/src/test_data/match#L287)):*
> ```
> 
> //! > lowering_diagnostics
> error: Match is Non Exhaustive - ensure that all possible cases are being handled by adding a match arm with a wildcard pattern
> ```

Done.
___
*[`examples/fib_match.cairo` line 10 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4284#-NhGq0dY2xCTQinP_kKR:-NhLkI0U1Nsy1rjc1Es8:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/61de34975167b07ca287fd09bb209bdac98c94f9/examples/fib_match.cairo#L10)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

consider (just to make getting the extra values make algorithmic sense)
</blockquote></details>

Done
___
*[`crates/cairo-lang-sierra-generator/src/block_generator_test_data/match` line 54 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4284#-NhLORJvE6ZYwDkGQIyI:-NhLkJX10I1OWGppO7p-:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/f720efa106157f38674421922a0a28ea24fa04a9/crates/cairo-lang-sierra-generator/src/block_generator_test_data/match#L54)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can you prevent the ids here from changing?
(or explain well enough why they *should* change)
</blockquote></details>

Done

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r8, 1 of 2 files at r9, 2 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4284)* status: 8 of 9 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1169 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4284#-NhMEh9EAh0lfZvB8n67:-NhMEh9EAh0lfZvB8n68:b2nhdkj) ([raw file](https://github.com/starkware-libs/cairo/blob/79f0d10676aa99288c5d05994bf6f42f252fb777/crates/cairo-lang-lowering/src/lower/mod.rs#L1169)):*
> ```XML
> }
> 
> fn lower_felt252_arm_block(
> ```

Doc
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1184 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4284#-NhMEj_N7rjD0so5XBIq:-NhMEj_N7rjD0so5XBIr:b2nhdkj) ([raw file](https://github.com/starkware-libs/cairo/blob/79f0d10676aa99288c5d05994bf6f42f252fb777/crates/cairo-lang-lowering/src/lower/mod.rs#L1184)):*
> ```XML
> }
> 
> fn lower_expr_felt252_arm(
> ```

Doc

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4284)* status: 8 of 9 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1169 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4284#-NhMEh9EAh0lfZvB8n67:-NhQSfmR4l6E2EOQY21N:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/79f0d10676aa99288c5d05994bf6f42f252fb777/crates/cairo-lang-lowering/src/lower/mod.rs#L1169)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1184 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4284#-NhMEj_N7rjD0so5XBIq:-NhQShD57TcDpNj5Z5X-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/79f0d10676aa99288c5d05994bf6f42f252fb777/crates/cairo-lang-lowering/src/lower/mod.rs#L1184)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Doc
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4284)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 1 of 7 files at r1, 1 of 3 files at r4, 2 of 3 files at r7, 1 of 1 files at r8, 1 of 2 files at r9, 2 of 3 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4284)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/diagnostic.rs` line 82 at r11](https://reviewable.io/reviews/starkware-libs/cairo/4284#-Nhf6VmV9HYveArJ0Pm-:-Nhf6VmV9HYveArJ0Pm0:b-zbpw34) ([raw file](https://github.com/starkware-libs/cairo/blob/87507681df1d7d75044d1f256d18d4233a9df17b/crates/cairo-lang-lowering/src/diagnostic.rs#L82)):*
> ```XML
>             "Unsupported match arm - numbers must be sequential starting from 0.".into(),
>             LoweringDiagnosticKind::NonExhaustiveMatch => {
>                 "Match is non exhaustive - ensure that all possible cases are being handled by adding a match arm with a wildcard pattern."
> ```

I think it should be clearer that numerical match must have a wildcard pattern (or `~2^251` arms).



_Suggestion:_
```XML
"Match is non exhaustive - match over a numerical value must have a wildcard card pattern (`_`).
```
___
*[`crates/cairo-lang-lowering/src/diagnostic.rs` line 98 at r11](https://reviewable.io/reviews/starkware-libs/cairo/4284#-Nhf74RSB58Zr1muYbjT:-Nhf74RSB58Zr1muYbjU:b-hfpv23) ([raw file](https://github.com/starkware-libs/cairo/blob/87507681df1d7d75044d1f256d18d4233a9df17b/crates/cairo-lang-lowering/src/diagnostic.rs#L98)):*
> ```XML
>             }
>             LoweringDiagnosticKind::LiteralError(literal_error) => literal_error.format(db),
> ```

remove.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4284#-:-NhfQnGt2WrULPQF0cZ6:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4284#-:-NhubFQd5kNVT0UPKGWU:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4284)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4284)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/diagnostic.rs` line 80 at r13](https://reviewable.io/reviews/starkware-libs/cairo/4284#-NhutpOGByBtjAgTr2SC:-NhutpOGByBtjAgTr2SD:b-o3r75r) ([raw file](https://github.com/starkware-libs/cairo/blob/42182f82345aed9d87d51d8fd0be5e4e3809ae52/crates/cairo-lang-lowering/src/diagnostic.rs#L80)):*
> ```XML
>             LoweringDiagnosticKind::UnsupportedMatchArmNonSequential=>
>             "Unsupported match arm - numbers must be sequential starting from 0.".into(),
>             LoweringDiagnosticKind::NonExhaustiveMatch => {
> ```

If the diag now only makes sense for match on numeric values, rename err variant as well.



_Code quote:_
```XML
NonExhaustiveMatch
```

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4284)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4284)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/diagnostic.rs` line 80 at r13](https://reviewable.io/reviews/starkware-libs/cairo/4284#-NhutpOGByBtjAgTr2SC:-Ni4ZCuH-d7tgsM8798O:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/42182f82345aed9d87d51d8fd0be5e4e3809ae52/crates/cairo-lang-lowering/src/diagnostic.rs#L80)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

If the diag now only makes sense for match on numeric values, rename err variant as well.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4284)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
