### PR TITLE
Fix return at end of function

### PR DESCRIPTION
**Pull request by spapinistarkware**
Is this the correct fix?

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1263)

### CODE REVIEW

**Review by liorgold2 — COMMENTED** [review]
I guess. If there's no difference between `lowering::BlockEnd::Return` and `lowering::BlockEnd::Callsite` at the end of the function then yes.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1263#-:-NIxb97FDse9VqNBwFEl:b-zd0nqx)* status: 0 of 2 files reviewed, all discussions resolved

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1263)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/sierra_generator/src/function_generator.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1263#-NIxbTGV3-quQrdobx1_:-NIxbTGV3-quQrdobx1a:b-4p4yxj) ([raw file](https://github.com/starkware-libs/cairo/blob/dfe3a7056b8e5b8796046e96a533142519895f46/crates/sierra_generator/src/function_generator.rs#L114)):*
> ```XML
>             statements.extend(generate_return_code(&mut context, returned_variables)?);
>         }
>         lowering::BlockEnd::Return(returned_variables) => {
> ```

Can you unite this with `Callsite`?
```
lowering::BlockEnd::Callsite(returned_variables)
        | lowering::BlockEnd::Return(returned_variables) => {
            statements.extend(generate_return_code(&mut context, returned_variables)?);
        }
```

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1263)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1263)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/sierra_generator/src/function_generator.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1263#-NIxbTGV3-quQrdobx1_:-NJe2Z2s99Xttuj17G32:b-oquqx8) ([raw file](https://github.com/starkware-libs/cairo/blob/dfe3a7056b8e5b8796046e96a533142519895f46/crates/sierra_generator/src/function_generator.rs#L114)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Can you unite this with `Callsite`?
```
lowering::BlockEnd::Callsite(returned_variables)
        | lowering::BlockEnd::Return(returned_variables) => {
            statements.extend(generate_return_code(&mut context, returned_variables)?);
        }
```
</blockquote></details>

I'm really suprised this works

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1263#-:-NJl4XdJ-LwN1boKI0YU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
