### PR TITLE
Extracted add and sub from u128 to general uint.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:734e5182

---

**Stack**:
- #1816
- #1815
- #1814 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1814#-:-NM8tDwO4tYItQMm4zll:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/uint.rs` line 312 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1814#-NM8sF9y2dpZorPJBGsB:-NM8sF9y2dpZorPJBGsC:b-lnon2c) ([raw file](https://github.com/starkware-libs/cairo/blob/03c2deca17ecaaae69d601be5034be0ba04ac8bb/crates/cairo-lang-sierra/src/extensions/modules/uint.rs#L312)):*
> ```XML
>             ],
>             fallthrough: Some(0),
>         })
> ```

consider:



_Suggestion:_
```XML
        let branch_signature = BranchSignature {
                    vars: vec![
                        OutputVarInfo {
                            ty: range_check_type.clone(),
                            ref_info: OutputVarReferenceInfo::Deferred(
                                DeferredOutputKind::AddConst { param_idx: 0 },
                            ),
                        },
                        OutputVarInfo {
                            ty: ty.clone(),
                            ref_info: OutputVarReferenceInfo::NewTempVar { idx: Some(0) },
                        },
                    ],
                    ap_change: SierraApChange::Known { new_vars_only: false },
                };
Ok(LibfuncSignature {
            param_signatures: vec![
                ParamSignature {
                    ty: range_check_type.clone(),
                    allow_deferred: false,
                    allow_add_const: true,
                    allow_const: false,
                },
                ParamSignature::new(ty.clone()),
                ParamSignature::new(ty.clone()),
            ],
            branch_signatures: vec![branch_signature.clone(), branch_signature],
            fallthrough: Some(0),
        })
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1814)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/uint.rs` line 312 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1814#-NM8sF9y2dpZorPJBGsB:-NM9rwzs8FRULUqrUqTD:b45631b) ([raw file](https://github.com/starkware-libs/cairo/blob/03c2deca17ecaaae69d601be5034be0ba04ac8bb/crates/cairo-lang-sierra/src/extensions/modules/uint.rs#L312)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

consider:
</blockquote></details>

this won't be true in the next pr anyway.

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1814)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @gilbens-starkware and @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1814)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
