### PR TITLE
Fix `impl abc of abc` and re-enable semantic of impl body.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1645)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1645#-:-NKwaNXq5fqeEQdn6b5E:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1645#-NKw_M5V6FN6UxG6FxTC:-NKw_M5W79Eg2zenrySu:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/40857a38c19b02d305e608339a6a4f5ee457acec/crates/cairo-lang-semantic/src/items/imp.rs#L141)):*
> ```XML
> 
>     let mut option_concrete_trait = None;
>     if resolve_trait {
> ```





_Suggestion:_
```XML
    let option_concrete_trait = if resolve_trait {
        resolver.resolve_concrete_path(
            &mut diagnostics,
            &trait_path_syntax,
            NotFoundItemType::Trait,
        ).ok().and_than(|concrete_path| try_extract_matches!(concrete_path, ResolvedConcreteItem::Trait))
    } else {
        None
    }
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1645)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1645#-NKw_M5V6FN6UxG6FxTC:-NKwclKMB-jnT4Q16hW_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/40857a38c19b02d305e608339a6a4f5ee457acec/crates/cairo-lang-semantic/src/items/imp.rs#L141)):*
> ```XML
> 
>     let mut option_concrete_trait = None;
>     if resolve_trait {
> ```

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1645)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1645)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
