### PR TITLE
Added support for most syscalls, and framework for interoperability.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #2182
- #2181 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2181)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 316 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2181#-NOdUFoe9GE2npbzJk8z:-NOdUFoe9GE2npbzJk9-:b-165ydq) ([raw file](https://github.com/starkware-libs/cairo/blob/9dbc5e97628f10fd1a177694c64b32b1ab56bab9/crates/cairo-lang-runner/src/casm_run/mod.rs#L316)):*
> ```XML
>                         if !addr_domain.is_zero() {
>                             // Only address_domain 0 is currently supported.
>                             return Ok(false);
> ```

what is this bool?



_Code quote:_
```XML
false
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 316 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2181#-NOdUFoe9GE2npbzJk8z:-NOdUz_sBnFN_QAZYB45:b-1ca54b) ([raw file](https://github.com/starkware-libs/cairo/blob/9dbc5e97628f10fd1a177694c64b32b1ab56bab9/crates/cairo-lang-runner/src/casm_run/mod.rs#L316)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what is this bool?
</blockquote></details>

I'm probably missing something, but it looks like you are returning a bool in a function that returns a uint.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2181)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 316 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2181#-NOdUFoe9GE2npbzJk8z:-NOeFz3wBjc0081CtPS1:b-tl54yc) ([raw file](https://github.com/starkware-libs/cairo/blob/9dbc5e97628f10fd1a177694c64b32b1ab56bab9/crates/cairo-lang-runner/src/casm_run/mod.rs#L316)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I'm probably missing something, but it looks like you are returning a bool in a function that returns a uint.
</blockquote></details>

added comment above `check_handle_oog`.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2181#-:-NOiAwDP1RG-mKskQGKU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
