### PR TITLE
Tomer/impl impl stores concrete trait

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6472)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6472)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/items/tests/trait_impl` line 1240 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6472#-O8p_gAP2O5CccyA7EyU:-O8p_gAP2O5CccyA7EyV:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/768fd0ed5b3aef4c6ccc1fd1eca9a39cff9631fd/crates/cairo-lang-semantic/src/items/tests/trait_impl#L1240)):*
> ```
> 
> //! > expected_diagnostics
> //! > ==========================================================================
> ```





_Suggestion:_
```
//! > expected_diagnostics

//! > ==========================================================================
```
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_impl` line 1277 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6472#-O8pabcq9T7QnFH_PpSE:-O8pabcq9T7QnFH_PpSF:b214w74) ([raw file](https://github.com/starkware-libs/cairo/blob/768fd0ed5b3aef4c6ccc1fd1eca9a39cff9631fd/crates/cairo-lang-semantic/src/items/tests/trait_impl#L1277)):*
> ```
>         bar(2_u32)
>     }
> }
> ```

doc every part as to why it is required for the test.



_Code quote:_
```
mod MyMod {
    impl MyIn<T> of super::InnerTrait<T> {
        type X = u16;
        fn foo() -> u16 {
            5
        }
    }
    fn bar<F, impl A: super::MyTrait<F>>(_x: F) -> A::MyImpl::X {
        A::MyImpl::foo()
    }
    fn bar2() -> u16 {
        bar(2_u32)
    }
}
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6472)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

___
*[`Cargo.lock` line 290 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6472#-O99OP74CZmjAwNCs6Ph:-O99OP74CZmjAwNCs6Pi:bxwndzt) ([raw file](https://github.com/starkware-libs/cairo/blob/768fd0ed5b3aef4c6ccc1fd1eca9a39cff9631fd/Cargo.lock#L290)):*
> ```TOML
> 
> [[package]]
> name = "async-trait"
> ```

the changes should not be a part of this PR.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6472#-:-O9F92OGApV5mN7GuTbd:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6472)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6472)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/items/tests/trait_impl` line 1240 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6472#-O8p_gAP2O5CccyA7EyU:-O99Px0wA38aVypiQ_rH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/768fd0ed5b3aef4c6ccc1fd1eca9a39cff9631fd/crates/cairo-lang-semantic/src/items/tests/trait_impl#L1240)):*
> ```
> 
> //! > expected_diagnostics
> //! > ==========================================================================
> ```

Done.
___
*[`Cargo.lock` line 290 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6472#-O99OP74CZmjAwNCs6Ph:-O9F7dZA1GP6U-axbfM5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/768fd0ed5b3aef4c6ccc1fd1eca9a39cff9631fd/Cargo.lock#L290)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the changes should not be a part of this PR.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6472)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
