### PR TITLE
Bundle Cairo-LS within Scarb 

### PR DESCRIPTION
**Pull request by maciektr**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2851)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2851)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @maciektr and @mkaput)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2851#-NTDiIen493IKBeqGtaQ:-NTDiIeo3K7K58BIfNjR:b-4k7sk1) (no related file):*
Hurray!
Making sure:
1. Does this work for developing the corelib inside the cairo-lang project, with no scarb installed?
2. Does the LS still work without scarb for normal users?

___

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2851)* status: 2 of 6 files reviewed, 6 unresolved discussions (waiting on @maciektr and @spapinistarkware)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 85 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2851#-NTDn5eC9uUq4hiJobd4:-NTDn5eC9uUq4hiJobd5:b5lhupe) ([raw file](https://github.com/starkware-libs/cairo/blob/8ea99782579350ccd9604c4ef3015339d789cb20/crates/cairo-lang-language-server/src/lib.rs#L85)):*
> ```XML
>         .with_starknet_plugins()
>         .build()
>         .expect("Failed to initialize Cairo compiler database.");
> ```

I thing the need to do so much changes regarding `RootDatabase` is a manifest of our bad understanding how should it be managed in LS context. I think, that as for now it should always have starknet and test plugins enabled (including using starknet's implicit precedence). It should start with no corelib and instead use it only if running outside scarb.

In long term though I think LS should always start with clean/empty root database, and then dynamically add plugins/config items etc. when project changes.



_Code quote:_
```XML
    let db = RootDatabase::builder()
        .with_cfg(CfgSet::from_iter([Cfg::tag("test")]))
        .with_starknet_plugins()
        .build()
        .expect("Failed to initialize Cairo compiler database.");
```

**Comment by maciektr** [comment]
*[`vscode-cairo/src/extension.ts` line 156 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2851#-NTDk-mG2Uw_zBKmG_q_:-NTP2D2G2UWVi5raOZLM:b-h64sai) ([raw file](https://github.com/starkware-libs/cairo/blob/8ea99782579350ccd9604c4ef3015339d789cb20/vscode-cairo/src/extension.ts#L156)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

While this trick with wrapping stdout in JSON array is **very smart**, it does not comply to Scarb's JSON output contract, because Scarb promises to output JSON-ND. This means, each message is separated just with `\n` instead of `,` as expected by this trick. What would be more correct is to split stdout by newlines, and then parse each line.
</blockquote></details>

🤦🤦🤦 Sorry

**Comment by maciektr** [comment]
*[`vscode-cairo/src/extension.ts` line 156 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2851#-NTDk-mG2Uw_zBKmG_q_:-NTP2YgnBgUEMvTucbsE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8ea99782579350ccd9604c4ef3015339d789cb20/vscode-cairo/src/extension.ts#L156)):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

🤦🤦🤦 Sorry 
</blockquote></details>

Done.

**Comment by maciektr** [comment]
*[`crates/cairo-lang-language-server/src/scarb_service.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2851#-NTDlyfy6YcZiqXkn_XK:-NTQ1OEuAeQIFqeO_HDa:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8ea99782579350ccd9604c4ef3015339d789cb20/crates/cairo-lang-language-server/src/scarb_service.rs#L53)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Please add some anyhow contexts here
</blockquote></details>

Done.

**Comment by maciektr** [comment]
*[`crates/cairo-lang-language-server/src/lib.rs` line 85 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2851#-NTDn5eC9uUq4hiJobd4:-NTT3KKgB4EQMPqF3iw0:b-1hi312) ([raw file](https://github.com/starkware-libs/cairo/blob/8ea99782579350ccd9604c4ef3015339d789cb20/crates/cairo-lang-language-server/src/lib.rs#L85)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I thing the need to do so much changes regarding `RootDatabase` is a manifest of our bad understanding how should it be managed in LS context. I think, that as for now it should always have starknet and test plugins enabled (including using starknet's implicit precedence). It should start with no corelib and instead use it only if running outside scarb.

In long term though I think LS should always start with clean/empty root database, and then dynamically add plugins/config items etc. when project changes.
</blockquote></details>

I have moved the resolution of implicit precedence from string values to types downwards, as discussed offline.

**Review by mkaput — COMMENTED** [review]
> Reviewed 5 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2851)* status: 6 of 10 files reviewed, 1 unresolved discussion (waiting on @maciektr and @spapinistarkware)

**Comment by maciektr** [comment]
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Hurray!
Making sure:
1. Does this work for developing the corelib inside the cairo-lang project, with no scarb installed?
2. Does the LS still work without scarb for normal users?
</blockquote></details>

@spapinistarkware yes, it works for both of this use cases. In case Scarb is not installed, the old way of project initialization is run.

**Review by mkaput — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2851)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by spapinistarkware — APPROVED** [review]

**Pull request merged**
