### PR TITLE
Added `Pow` trait and implementations for base numeric types and `usize`.

### PR DESCRIPTION
**Pull request by orizi**
…ze`.

### CODE REVIEW

**Review by TomerStarkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6694#-:-OC2xx9mCf8w2mXBK5Kf:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArielElp and @gilbens-starkware)

**Review by TomerStarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6694)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @ArielElp, @Draggu, @gilbens-starkware, @mkaput, and @piotmag769)

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6694)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @ArielElp, @Draggu, @mkaput, and @orizi)

___
*[`corelib/src/num/traits/ops/pow.cairo` line 27 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6694#-OC5AIF95odF7RzQpmSI:-OC5AIF95odF7RzQpmSJ:b-nms4pr) ([raw file](https://github.com/starkware-libs/cairo/blob/a0bfbc460e23630aa987db35d6a4391f1871f01f/corelib/src/num/traits/ops/pow.cairo#L27)):*
> ```Cairo
>             } else {
>                 tail_result * self
>             }
> ```

Consider changing to an iterative implementation, it is a bit more readable.
 And if not, make `exp` and `self` immutable.



_Suggestion:_
```Cairo
            let mut res =  core::num::traits::One::one();
            let mut cur_multiplier = self;
            while exp != 0 {
                let (exp, rem) = DivRem::div_rem(exp,2);
                if rem == 1 {
                    res *= cur_multiplier;
                }
                cur_multiplier = cur_multiplier * cur_multiplier; 
            }
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6694)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @ArielElp, @Draggu, @gilbens-starkware, @integraledelebesgue, @mkaput, and @TomerStarkware)

___
*[`corelib/src/num/traits/ops/pow.cairo` line 27 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6694#-OC5AIF95odF7RzQpmSI:-OC5avsEBcFDIBxeJknx:b-5z7a4a) ([raw file](https://github.com/starkware-libs/cairo/blob/a0bfbc460e23630aa987db35d6a4391f1871f01f/corelib/src/num/traits/ops/pow.cairo#L27)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Consider changing to an iterative implementation, it is a bit more readable.
 And if not, make `exp` and `self` immutable.
</blockquote></details>

that was my original implementation - but this solution overflows in cases when no overflow may occur.
(because of the squaring happening at the end of the loop).
`mut` removed.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6694#-:-OC7VRdGDOsMOFvmWFoy:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @ArielElp, @Draggu, @integraledelebesgue, and @mkaput)

**Pull request merged**
