### PR TITLE
Tests in fix mode write outputs even on failure.

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4031)

### CODE REVIEW

**Comment by yuvalsw** [comment]
change target branch

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 30 of 30 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4031)* status: all files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-test-utils/src/lib.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4031#-Ndk-dD4AGQt6bGt9QG-:-Ndk-dD4AGQt6bGt9QG0:b2ngwfe) ([raw file](https://github.com/starkware-libs/cairo/blob/00c25923e6a80628da81b621dbd988a2fed451b1/crates/cairo-lang-test-utils/src/lib.rs#L40)):*
> ```XML
> }
> 
> // Returns an error string if there are diagnostics when args.expect_diagnostics == false.
> ```

///
___
*[`crates/cairo-lang-test-utils/src/parse_test_file.rs` line 210 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4031#-Ndk-h8X9pR_gtF7y5A5:-Ndk-h8X9pR_gtF7y5A6:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/00c25923e6a80628da81b621dbd988a2fed451b1/crates/cairo-lang-test-utils/src/parse_test_file.rs#L210)):*
> ```XML
> }
> 
> // TODO(yg): doc
> ```

.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4031)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-test-utils/src/lib.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4031#-Ndk-dD4AGQt6bGt9QG-:-NdkQhCrCxPxqstk1Z6u:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/00c25923e6a80628da81b621dbd988a2fed451b1/crates/cairo-lang-test-utils/src/lib.rs#L40)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

///
</blockquote></details>

Done.
___
*[`crates/cairo-lang-test-utils/src/parse_test_file.rs` line 210 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4031#-Ndk-h8X9pR_gtF7y5A5:-NdkQWCT0HzsIBlPQE9D:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/00c25923e6a80628da81b621dbd988a2fed451b1/crates/cairo-lang-test-utils/src/parse_test_file.rs#L210)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4031#-:-NdkXaYd1_7xdoX7qlXT:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Review by orizi — APPROVED** [review]
> Reviewed 53 of 53 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4031)* status: all files reviewed, 1 unresolved discussion

**Review by orizi — APPROVED** [review]
> Reviewed 59 of 59 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4031)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
