### PR TITLE
Add builtins to entry points to CasmContractClass.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1403)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1403)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/starknet/src/casm_contract_class.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1403#-NJiOWz6-s0FGVbwfFTU:-NJiOWz6-s0FGVbwfFTV:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0341676e4539f39b9f80ca17369783313997b26a/crates/starknet/src/casm_contract_class.rs#L87)):*
> ```XML
>         let name_by_long_id: HashMap<u64, String> = [
>             (RangeCheckType::ID, "RangeCheck"),
>             (PedersenType::ID, "Pedersen"),
> ```





_Suggestion:_
```XML
        let name_by_debug_id = HashMap<u64, &str>::from([RangeCheckType::ID, PedersenType::ID, GasBuiltinType::ID]
        .map(|generic_id| (generic_id.id, generic_id.debug_name.expect("Sierra generic types have a full name.").as_str())));
```
___
*[`crates/starknet/src/casm_contract_class.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1403#-NJiPK3j-nv2O9Icabqc:-NJiPK3j-nv2O9Icabqd:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0341676e4539f39b9f80ca17369783313997b26a/crates/starknet/src/casm_contract_class.rs#L114)):*
> ```XML
>             let mut builtins = vec![];
> 
>             // The expect return types are [builtins.., System, RangeCheck, PanicResult],
> ```





_Suggestion:_
```XML
            // The expect return types are [builtins.., System, PanicResult],
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1403)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/starknet/src/casm_contract_class.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1403#-NJiOWz6-s0FGVbwfFTU:-NJiY1HD-B-dySnCn9oW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0341676e4539f39b9f80ca17369783313997b26a/crates/starknet/src/casm_contract_class.rs#L87)):*
> ```XML
>         let name_by_long_id: HashMap<u64, String> = [
>             (RangeCheckType::ID, "RangeCheck"),
>             (PedersenType::ID, "Pedersen"),
> ```

Done.
___
*[`crates/starknet/src/casm_contract_class.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1403#-NJiPK3j-nv2O9Icabqc:-NJiY2OQBlzixLOaMzv-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0341676e4539f39b9f80ca17369783313997b26a/crates/starknet/src/casm_contract_class.rs#L114)):*
> ```XML
>             let mut builtins = vec![];
> 
>             // The expect return types are [builtins.., System, RangeCheck, PanicResult],
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1403#-:-NJib7mhCMePc2rkPY2n:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/starknet/src/casm_contract_class.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1403#-NJib-ts2Py-SG_nCSut:-NJib-tt0p2b8dM0F_df:b28i3v9) ([raw file](https://github.com/starkware-libs/cairo/blob/1e0811f2316990b857d1dd6ecb05a4d0f675dadd/crates/starknet/src/casm_contract_class.rs#L92)):*
> ```XML
>                         .debug_name
>                         .expect("Sierra generic types have a full name.")
>                         .to_string(),
> ```

is this actually needed?
(you can change the type of the map of course)



_Code quote:_
```XML
.to_string()
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1403)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/starknet/src/casm_contract_class.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1403#-NJib-ts2Py-SG_nCSut:-NJigIHUAsdYN4_MY_by:b-8pah8a) ([raw file](https://github.com/starkware-libs/cairo/blob/1e0811f2316990b857d1dd6ecb05a4d0f675dadd/crates/starknet/src/casm_contract_class.rs#L92)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is this actually needed?
(you can change the type of the map of course)
</blockquote></details>

yes,
the compiler complained that 
                    generic_id
                        .debug_name
                        .expect("Sierra generic types have a full name.")

creates a temporary and I'm returning it.

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1403)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
