### PR TITLE
Added panic! macro

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4341)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4341)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`corelib/src/test/panics_test.cairo` line 139 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4341#-NiDm6jQ91gGmebZ5Q3Y:-NiDm6jR0dOjDS8aVe16:bgnsupa) ([raw file](https://github.com/starkware-libs/cairo/blob/3b46378e84e74b3df330d9ee72b55b1017f3bd57/corelib/src/test/panics_test.cairo#L139)):*
> ```Cairo
> fn test_panic_macro_single_arg() {
>     let ba: ByteArray = "panic data";
>     panic!(ba);
> ```

this one shouldn't be supported.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4341)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/test/panics_test.cairo` line 139 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4341#-NiDm6jQ91gGmebZ5Q3Y:-NiEL7ALEnLdQLltB2Tc:bdy586x) ([raw file](https://github.com/starkware-libs/cairo/blob/3b46378e84e74b3df330d9ee72b55b1017f3bd57/corelib/src/test/panics_test.cairo#L139)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this one shouldn't be supported.
</blockquote></details>

Why not? In Rust it is supported.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4341)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`corelib/src/test/panics_test.cairo` line 139 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4341#-NiDm6jQ91gGmebZ5Q3Y:-NiETRj57QhzAE_pj0Rw:bygruqm) ([raw file](https://github.com/starkware-libs/cairo/blob/3b46378e84e74b3df330d9ee72b55b1017f3bd57/corelib/src/test/panics_test.cairo#L139)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Why not? In Rust it is supported.
</blockquote></details>

as discussed f2f.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4341)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/test/panics_test.cairo` line 139 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4341#-NiDm6jQ91gGmebZ5Q3Y:-NiFpENF55K1ihJYp0mC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3b46378e84e74b3df330d9ee72b55b1017f3bd57/corelib/src/test/panics_test.cairo#L139)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

as discussed f2f.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4341)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/inline_macros/panic.rs` line 67 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4341#-NiFryNj2xt6WT1v04CI:-NiFryNk151QtncPXo4e:b-g0cp6f) ([raw file](https://github.com/starkware-libs/cairo/blob/1e663691d7567e2836c00c2fa878155bfa75af67/crates/cairo-lang-semantic/src/inline_macros/panic.rs#L67)):*
> ```XML
>             }];
>             return InlinePluginResult { code: None, diagnostics };
>         };
> ```

after rebase - is this reparsing fully required? or would the error be nice?



_Code quote:_
```XML
        let arguments = macro_args.elements(db).iter().map(|arg| arg.arg_clause(db)).collect_vec();
        let Some(arguments) = arguments
            .iter()
            .map(|arg| {
                Some(RewriteNode::new_trimmed(
                    try_extract_matches!(arg, ast::ArgClause::Unnamed)?.as_syntax_node(),
                ))
            })
            .collect::<Option<Vec<_>>>()
        else {
            let diagnostics = vec![PluginDiagnostic {
                stable_ptr: syntax.stable_ptr().untyped(),
                message: format!(
                    "All arguments of the `{}` macro must be unnamed.",
                    PanicMacro::NAME
                ),
            }];
            return InlinePluginResult { code: None, diagnostics };
        };
```

**Comment by yuvalsw** [comment]
*[`crates/cairo-lang-semantic/src/inline_macros/panic.rs` line 67 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4341#-NiFryNj2xt6WT1v04CI:-NiFyKw33oD5mIxF7SN9:b-jnzead) ([raw file](https://github.com/starkware-libs/cairo/blob/1e663691d7567e2836c00c2fa878155bfa75af67/crates/cairo-lang-semantic/src/inline_macros/panic.rs#L67)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

after rebase - is this reparsing fully required? or would the error be nice?
</blockquote></details>

I don't understand the question

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4341)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/inline_macros/panic.rs` line 67 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4341#-NiFryNj2xt6WT1v04CI:-NiFzO_m929GCb7p06rz:b-9viq6d) ([raw file](https://github.com/starkware-libs/cairo/blob/1e663691d7567e2836c00c2fa878155bfa75af67/crates/cairo-lang-semantic/src/inline_macros/panic.rs#L67)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I don't understand the question
</blockquote></details>

internal errors (not pointing to the entire macro) - should be automatically remapped well.
so if this rechecks if the arguments are valid, the forwarding to `format` should be enough.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4341)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/inline_macros/panic.rs` line 67 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4341#-NiFryNj2xt6WT1v04CI:-Nif8oNX-sji6rpX1NXE:bmtl4ow) ([raw file](https://github.com/starkware-libs/cairo/blob/1e663691d7567e2836c00c2fa878155bfa75af67/crates/cairo-lang-semantic/src/inline_macros/panic.rs#L67)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

internal errors (not pointing to the entire macro) - should be automatically remapped well.
so if this rechecks if the arguments are valid, the forwarding to `format` should be enough.
</blockquote></details>

I know it's less relevant now, but for the comment I added in your PR - when I removed those I got the diagnostic (of the new test for named argument) pointing to the format macro in the generated code.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4341)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/inline_macros/panic.rs` line 67 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4341#-NiFryNj2xt6WT1v04CI:-NimoTMPE6an336v5Fzc:bnpkute) ([raw file](https://github.com/starkware-libs/cairo/blob/1e663691d7567e2836c00c2fa878155bfa75af67/crates/cairo-lang-semantic/src/inline_macros/panic.rs#L67)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I know it's less relevant now, but for the comment I added in your PR - when I removed those I got the diagnostic (of the new test for named argument) pointing to the format macro in the generated code.
</blockquote></details>

that is why i changed the error to point to the `(` - and added it as a rewrite node when writing the internal `write`.

**Pull request closed without merging**
