### PR TITLE
Add Secp256K1 Libfuncs to SERDE_SUPPORTED_LONG_IDS.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3256)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3256)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/test_data/test_contract.cairo` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3256#-NWbIMC1-vHsBtA03NM8:-NWbIMC1-vHsBtA03NM9:b-nk8ayy) ([raw file](https://github.com/starkware-libs/cairo/blob/733893826deab5e34d74bf00b416445c56793f72/crates/cairo-lang-starknet/test_data/test_contract.cairo#L55)):*
> ```Cairo
> 
>     #[external]
>     fn test_recover_public_key(msg_hash: u256, r: u256, s: u256, y_parity: bool) {
> ```

This is unrelated I assume

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/test_data/test_contract.cairo` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3256#-NWbIMC1-vHsBtA03NM8:-NWbJXfHDX-0fhPpOGaZ:bfgv94r) ([raw file](https://github.com/starkware-libs/cairo/blob/733893826deab5e34d74bf00b416445c56793f72/crates/cairo-lang-starknet/test_data/test_contract.cairo#L55)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

This is unrelated I assume 
</blockquote></details>

it is a way to trigger the issue.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3256)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/test_data/test_contract.cairo` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3256#-NWbIMC1-vHsBtA03NM8:-NWbJ_VvA7B4CBSbTZz-:bwn9tte) ([raw file](https://github.com/starkware-libs/cairo/blob/733893826deab5e34d74bf00b416445c56793f72/crates/cairo-lang-starknet/test_data/test_contract.cairo#L55)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it is a way to trigger the issue.
</blockquote></details>

can you think of a simpler way of triggering it?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3256)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/test_data/test_contract.cairo` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3256#-NWbIMC1-vHsBtA03NM8:-NWbLF0L0z-JyMRAZPSq:bzi8vxv) ([raw file](https://github.com/starkware-libs/cairo/blob/733893826deab5e34d74bf00b416445c56793f72/crates/cairo-lang-starknet/test_data/test_contract.cairo#L55)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

can you think of a simpler way of triggering it?
</blockquote></details>

Adding a specific validation test for this as well would make sense.
Near the basic lists tests

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3256)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/test_data/test_contract.cairo` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3256#-NWbIMC1-vHsBtA03NM8:-NWbPNY09fgYBsEZiuge:bw1j2i5) ([raw file](https://github.com/starkware-libs/cairo/blob/733893826deab5e34d74bf00b416445c56793f72/crates/cairo-lang-starknet/test_data/test_contract.cairo#L55)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Adding a specific validation test for this as well would make sense.
Near the basic lists tests
</blockquote></details>

what are the basic lists tests?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3256)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/test_data/test_contract.cairo` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3256#-NWbIMC1-vHsBtA03NM8:-NWbRF3s4MXC1UpVl3WH:brzxkka) ([raw file](https://github.com/starkware-libs/cairo/blob/733893826deab5e34d74bf00b416445c56793f72/crates/cairo-lang-starknet/test_data/test_contract.cairo#L55)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what are the basic lists tests?
</blockquote></details>

The one that check that all libfuncs appear in experimental, and that all libfuncs within a list actually exist.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/test_data/test_contract.cairo` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3256#-NWbIMC1-vHsBtA03NM8:-NWbSB5t1lh4iH5qpeKQ:bt5sbf8) ([raw file](https://github.com/starkware-libs/cairo/blob/733893826deab5e34d74bf00b416445c56793f72/crates/cairo-lang-starknet/test_data/test_contract.cairo#L55)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

The one that check that all libfuncs appear in experimental, and that all libfuncs within a list actually exist.
</blockquote></details>

It seems to me that:
https://github.com/starkware-libs/cairo/blob/70b3a5197fff684a87ed35b433a82a00eac54ea4/crates/cairo-lang-starknet/src/felt252_serde_test.rs#L14

is the most relevant test.

So I need to add it to either
test_contract
or 
hello_starknet.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3256#-:-NWbSabP5XBdRSRop71B:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3256)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/test_data/test_contract.cairo` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3256#-NWbIMC1-vHsBtA03NM8:-NWba_HN9VBavWmcuzy7:ba6oovv) ([raw file](https://github.com/starkware-libs/cairo/blob/733893826deab5e34d74bf00b416445c56793f72/crates/cairo-lang-starknet/test_data/test_contract.cairo#L55)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

It seems to me that:
https://github.com/starkware-libs/cairo/blob/70b3a5197fff684a87ed35b433a82a00eac54ea4/crates/cairo-lang-starknet/src/felt252_serde_test.rs#L14

is the most relevant test.

So I need to add it to either
test_contract
or 
hello_starknet.
</blockquote></details>

Ok, I though of a better test.

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3256)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
