### PR TITLE
Implemented uint128s_from_felt using casm builder.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:4dada687

---

**Stack**:
- #1328
- #1324
- #1322
- #1321 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1321)* status: all files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware, @liorgold2, and @orizi)

___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 205 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1321#-NJFTmz_-YUkYrALYGbI:-NJFTmz_-YUkYrALYGbJ:b-xvcvy6) ([raw file](https://github.com/starkware-libs/cairo/blob/eafc72ecaeb87e664040837fa8a1bb884132d046/crates/sierra_to_casm/src/invocations/uint128.rs#L205)):*
> ```XML
>     // Check x in [0, 2**128).
>     let rc0 = casm.double_deref(range_check, 0);
>     casm.assert_vars_eq(x, rc0);
> ```

if it isn't in your pipeline anyway: consider constructing the CasmBuilder directly with all builtins you intend to use, and then implement something like `casm.range_check(value)` which panics if no RC builtin was provided on init.
(noticing this because I see RC offset is still manually managed)
In any case, out of scope in this PR



_Code quote:_
```XML
    let rc0 = casm.double_deref(range_check, 0);


    casm.assert_vars_eq(x, rc0);
```
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 240 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1321#-NJFVG2d3AJMx06sVD2G:-NJFVG2d3AJMx06sVD2H:bhm8l0z) ([raw file](https://github.com/starkware-libs/cairo/blob/eafc72ecaeb87e664040837fa8a1bb884132d046/crates/sierra_to_casm/src/invocations/uint128.rs#L240)):*
> ```XML
>     let rc0 = casm.double_deref(range_check, 0);
>     casm.assert_vars_eq(value, rc0);
>     let r = casm.build();
> ```

why `r`...? maybe `built`?



_Code quote:_
```XML
r
```
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 242 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1321#-NJFZ8-MBNazu6kpGOzq:-NJFZ8-MBNazu6kpGOzr:b-wx77k0) ([raw file](https://github.com/starkware-libs/cairo/blob/eafc72ecaeb87e664040837fa8a1bb884132d046/crates/sierra_to_casm/src/invocations/uint128.rs#L242)):*
> ```XML
>     let r = casm.build();
> 
>     assert_eq!(r.fallthrough_state.ap_change, 1);
> ```

Why are these needed?
I don't see these `1` and `6` values used later



_Code quote:_
```XML
    assert_eq!(r.fallthrough_state.ap_change, 1);
    assert_eq!(r.label_state["FailureHandle"].ap_change, 6);
```
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 244 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1321#-NJFZPoc7NQwCTp2knCV:-NJFZPoc7NQwCTp2knCW:bddy03e) ([raw file](https://github.com/starkware-libs/cairo/blob/eafc72ecaeb87e664040837fa8a1bb884132d046/crates/sierra_to_casm/src/invocations/uint128.rs#L244)):*
> ```XML
>     assert_eq!(r.fallthrough_state.ap_change, 1);
>     assert_eq!(r.label_state["FailureHandle"].ap_change, 6);
>     let [relocation_index] = &r.awaiting_relocations[..] else { panic!("Malformed casm builder usage.") };
> ```

consider adding a `n_expected_relocations` parameter to `CasmBuilder.build` that does this verification (so this assert won't be copied in every libfunc implementation)
Or is this going to be handled in `CompiledInvocationBuilder`?



_Code quote:_
```XML
let [relocation_index] = &r.awaiting_relocations[..] else { panic!("Malformed casm builder usage.") };
```
___
*[`crates/starknet/test_data/test_contract.casm` line 117 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1321#-NJF_A_I0Vd4GEHOFhSy:-NJF_A_I0Vd4GEHOFhSz:b79s5qn) ([raw file](https://github.com/starkware-libs/cairo/blob/eafc72ecaeb87e664040837fa8a1bb884132d046/crates/starknet/test_data/test_contract.casm#L117)):*
> ```
>     "0x2f",
>     "0x208b7fff7fff7ffe",
>     "0xa0680017fff8000",
> ```

Why would we even see regression changes? Shouldn't the resulting CASM be identical?

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1321)* status: all files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware, @liorgold2, and @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1321)* status: all files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware, @gilbens-starkware, and @liorgold2)

___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 205 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1321#-NJFTmz_-YUkYrALYGbI:-NJFehyB3o8rV6w0ErX6:b-14pj3e) ([raw file](https://github.com/starkware-libs/cairo/blob/eafc72ecaeb87e664040837fa8a1bb884132d046/crates/sierra_to_casm/src/invocations/uint128.rs#L205)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if it isn't in your pipeline anyway: consider constructing the CasmBuilder directly with all builtins you intend to use, and then implement something like `casm.range_check(value)` which panics if no RC builtin was provided on init.
(noticing this because I see RC offset is still manually managed)
In any case, out of scope in this PR
</blockquote></details>

i don't want to handle general builtins - but in the next pr this pattern is significantly improved.
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 240 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1321#-NJFVG2d3AJMx06sVD2G:-NJFgMRW0imxhEy6djTl:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/eafc72ecaeb87e664040837fa8a1bb884132d046/crates/sierra_to_casm/src/invocations/uint128.rs#L240)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why `r`...? maybe `built`?
</blockquote></details>

Done.
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 242 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1321#-NJFZ8-MBNazu6kpGOzq:-NJFeqsV-9bKLBgCu6mo:b-x6xqkq) ([raw file](https://github.com/starkware-libs/cairo/blob/eafc72ecaeb87e664040837fa8a1bb884132d046/crates/sierra_to_casm/src/invocations/uint128.rs#L242)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Why are these needed?
I don't see these `1` and `6` values used later
</blockquote></details>

Fixed to comparison with the constant values.
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 244 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1321#-NJFZPoc7NQwCTp2knCV:-NJFfCcs5NnVeZs-Y_Qt:b-22r5ne) ([raw file](https://github.com/starkware-libs/cairo/blob/eafc72ecaeb87e664040837fa8a1bb884132d046/crates/sierra_to_casm/src/invocations/uint128.rs#L244)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

consider adding a `n_expected_relocations` parameter to `CasmBuilder.build` that does this verification (so this assert won't be copied in every libfunc implementation)
Or is this going to be handled in `CompiledInvocationBuilder`?
</blockquote></details>

you'd need to unpack in each and every case anyway - this would probably wait for some minor builder refactor.
___
*[`crates/starknet/test_data/test_contract.casm` line 117 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1321#-NJF_A_I0Vd4GEHOFhSy:-NJFf2-2APtGqu5lbtaK:b-h3yjb4) ([raw file](https://github.com/starkware-libs/cairo/blob/eafc72ecaeb87e664040837fa8a1bb884132d046/crates/starknet/test_data/test_contract.casm#L117)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Why would we even see regression changes? Shouldn't the resulting CASM be identical?
</blockquote></details>

no it isn't - i reordered the allocated vars.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1321#-:-NJG-F5Z6oaiAclly7Cu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware and @liorgold2)

**Pull request merged**
