### PR TITLE
LS: Restart LSP client instead of window reload

### LINKED ISSUE #6262: Restart just the language client instead of entire window from core mismatch notification
Address https://reviewable.io/reviews/starkware-libs/cairo/6253#-O4tVLNr7_dsA4mSuElm

### PR DESCRIPTION
**Pull request by Draggu**
fix #6262

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6312)

### CODE REVIEW

**Review by piotmag769 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6312)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @mkaput, and @orizi)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6312#-:-O5TVYLQ8pFVAZ5M5tan:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @mkaput)

**Review by Draggu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6312)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @mkaput, @orizi, and @piotmag769)

___
*[`vscode-cairo/src/cairols.ts` line 95 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6312#-O5TpZRECVndItkMRVHq:-O5XbBzI6wqRuRozvz21:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/190ea8abf407d8508152e25dca0868e7ba163715/vscode-cairo/src/cairols.ts#L95)):*
> ```XML
>   });
> 
>   const restartClient = async () => {
> ```

Done.
___
*[`vscode-cairo/src/cairols.ts` line 105 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6312#-O5TpbtI3Hsw5SzIz3GT:-O5XbBS68G5FjdiThEws:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/190ea8abf407d8508152e25dca0868e7ba163715/vscode-cairo/src/cairols.ts#L105)):*
> ```XML
>     new lc.NotificationType<string>("cairo/corelib-version-mismatch"),
>     async (errorMessage) => {
>       const restartExtension = "Restart Cairo extension";
> ```

Done.
___
*[`vscode-cairo/src/cairols.ts` line 105 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6312#-O5Tpai6B1TEjrhowH4X:-O5XbBc1AVzv8tuKwN-O:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/190ea8abf407d8508152e25dca0868e7ba163715/vscode-cairo/src/cairols.ts#L105)):*
> ```XML
>     new lc.NotificationType<string>("cairo/corelib-version-mismatch"),
>     async (errorMessage) => {
>       const restartExtension = "Restart Cairo extension";
> ```

Done.

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6312#-:-O5Xd7g2EBbWBi4ueqiu:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae)

**Pull request merged**
