### PR TITLE
support for match on tuples

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4646)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4646)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1014 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4646#-NmRYeyMAv2ASShFgziM:-NmRYeyMAv2ASShFgziN:b-5gdub3) ([raw file](https://github.com/starkware-libs/cairo/blob/4515fc97bf404dd62ace3f60eb61bbd79cccafbf/crates/cairo-lang-lowering/src/lower/mod.rs#L1014)):*
> ```XML
>     Ok(ExtractedEnumDetails { concrete_enum_id, concrete_variants, n_snapshots })
> }
> fn extract_concrete_enum_tuple(
> ```

doc and empty line.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1097 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4646#-NmRYhFI9k700b5eA2k-:-NmRYhFI9k700b5eA2k0:bu5qq8i) ([raw file](https://github.com/starkware-libs/cairo/blob/4515fc97bf404dd62ace3f60eb61bbd79cccafbf/crates/cairo-lang-lowering/src/lower/mod.rs#L1097)):*
> ```XML
>     Ok(map)
> }
> /// Returns a map from variants to their corresponding arm index.
> ```

emptyline.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1190 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4646#-NmRYjLH6ZVKjrIr9ZVW:-NmRYjLH6ZVKjrIr9ZVX:b-o7ykf1) ([raw file](https://github.com/starkware-libs/cairo/blob/4515fc97bf404dd62ace3f60eb61bbd79cccafbf/crates/cairo-lang-lowering/src/lower/mod.rs#L1190)):*
> ```XML
>     Ok(map)
> }
> fn lower_expr_match_tuple(
> ```

doc and emptyline.
___
*[`crates/cairo-lang-lowering/src/test_data/match` line 697 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4646#-NmRYxP77dxbs_VUrLGB:-NmRYxP77dxbs_VUrLGC:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/4515fc97bf404dd62ace3f60eb61bbd79cccafbf/crates/cairo-lang-lowering/src/test_data/match#L697)):*
> ```
> 
> //! > lowering_diagnostics
> error: Unsupported matched value. Currently, match on tuples only supports enums.
> ```





_Suggestion:_
```
error: Unsupported matched value. Currently, match on tuples only supports enums as tuple members.
```
___
*[`crates/cairo-lang-lowering/src/test_data/match` line 839 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4646#-NmRZ2Pj0i3qLzLVT4PH:-NmRZ2Pj0i3qLzLVT4PI:bndnk6h) ([raw file](https://github.com/starkware-libs/cairo/blob/4515fc97bf404dd62ace3f60eb61bbd79cccafbf/crates/cairo-lang-lowering/src/test_data/match#L839)):*
> ```
> //! > function
> fn foo(a: A,b: A) -> felt252 {
>   let x= (@a,b);
> ```

fmt all

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4646)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1014 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4646#-NmRYeyMAv2ASShFgziM:-NmRaBW8EYLuh_Phr02O:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4515fc97bf404dd62ace3f60eb61bbd79cccafbf/crates/cairo-lang-lowering/src/lower/mod.rs#L1014)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc and empty line.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1097 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4646#-NmRYhFI9k700b5eA2k-:-NmRaPs45_Ozl5jIO_Ea:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4515fc97bf404dd62ace3f60eb61bbd79cccafbf/crates/cairo-lang-lowering/src/lower/mod.rs#L1097)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

emptyline.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1190 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4646#-NmRYjLH6ZVKjrIr9ZVW:-NmRfm8u0fKQjcsvki08:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4515fc97bf404dd62ace3f60eb61bbd79cccafbf/crates/cairo-lang-lowering/src/lower/mod.rs#L1190)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc and emptyline.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/test_data/match` line 697 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4646#-NmRYxP77dxbs_VUrLGB:-NmRfknoAN2N40f2eVFC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4515fc97bf404dd62ace3f60eb61bbd79cccafbf/crates/cairo-lang-lowering/src/test_data/match#L697)):*
> ```
> 
> //! > lowering_diagnostics
> error: Unsupported matched value. Currently, match on tuples only supports enums.
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/test_data/match` line 839 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4646#-NmRZ2Pj0i3qLzLVT4PH:-NmRfk4N9jIDhpzndUgY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4515fc97bf404dd62ace3f60eb61bbd79cccafbf/crates/cairo-lang-lowering/src/test_data/match#L839)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fmt all
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4646)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1249 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4646#-NmRzJv45Nv4p4nN3SlM:-NmRzJv45Nv4p4nN3SlN:b-409isb) ([raw file](https://github.com/starkware-libs/cairo/blob/1b5912893a3322afd5bc2b32ed134e7d8845e726/crates/cairo-lang-lowering/src/lower/mod.rs#L1249)):*
> ```XML
>         )?;
> 
>     struct LoweringMatchTupleContext {
> ```

dont write inner functions.

extract and doc all.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4646)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1249 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4646#-NmRzJv45Nv4p4nN3SlM:-NmV3U37BHonfzW41fG2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1b5912893a3322afd5bc2b32ed134e7d8845e726/crates/cairo-lang-lowering/src/lower/mod.rs#L1249)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

dont write inner functions.

extract and doc all.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4646)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1016 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4646#-NmVH24v7NwsXzQhFxIX:-NmVH24v7NwsXzQhFxIY:baqu604) ([raw file](https://github.com/starkware-libs/cairo/blob/9bf288a39b4c94d4fb83556478f29608bcb6bc87/crates/cairo-lang-lowering/src/lower/mod.rs#L1016)):*
> ```XML
> 
> /// Extracts concrete enums and variants from a match expression on a tuple of enums. Assumes the
> /// tuple contains only enums.
> ```

You don't assume that - you handle the other cases and return diagnostics.



_Code quote:_
```XML
/// Extracts concrete enums and variants from a match expression on a tuple of enums. Assumes the
/// tuple contains only enums.
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4646)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1197 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4646#-NmVf4f06ULNntGMCR-X:-NmVf4f06ULNntGMCR-Y:b-cijyam) ([raw file](https://github.com/starkware-libs/cairo/blob/9bf288a39b4c94d4fb83556478f29608bcb6bc87/crates/cairo-lang-lowering/src/lower/mod.rs#L1197)):*
> ```XML
> /// Information needed to lower a match on tuple expression.
> struct LoweringMatchTupleContext {
>     match_location: LocationId,
> ```

doc members.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4646)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1117 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4646#-NmVgSjCBXKRLhHfDRvt:-NmVgSjCBXKRLhHfDRvu:b4bifkf) ([raw file](https://github.com/starkware-libs/cairo/blob/9bf288a39b4c94d4fb83556478f29608bcb6bc87/crates/cairo-lang-lowering/src/lower/mod.rs#L1117)):*
> ```XML
>                 )
>             })?;
>         fn insert_arm_patterns(
> ```

write as a function.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4646)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1016 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4646#-NmVH24v7NwsXzQhFxIX:-NmVwV-N19XgxH8XrJRU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9bf288a39b4c94d4fb83556478f29608bcb6bc87/crates/cairo-lang-lowering/src/lower/mod.rs#L1016)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

You don't assume that - you handle the other cases and return diagnostics.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1117 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4646#-NmVgSjCBXKRLhHfDRvt:-NmVwwZcEJ4oBZCN6ITz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9bf288a39b4c94d4fb83556478f29608bcb6bc87/crates/cairo-lang-lowering/src/lower/mod.rs#L1117)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

write as a function.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1197 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4646#-NmVf4f06ULNntGMCR-X:-NmVxrel0AUoo0PdOyoP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9bf288a39b4c94d4fb83556478f29608bcb6bc87/crates/cairo-lang-lowering/src/lower/mod.rs#L1197)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc members.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4646)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1026 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4646#-NmWFG6aEDjVpXWgaPDJ:-NmWFG6aEDjVpXWgaPDK:bubiigr) ([raw file](https://github.com/starkware-libs/cairo/blob/fcbc87ed00c451d93f98b15ab65f8b16ff1769a3/crates/cairo-lang-lowering/src/lower/mod.rs#L1026)):*
> ```XML
>             ctx.diagnostics.report(matched_expr.stable_ptr().untyped(), UnsupportedMatchedValue),
>         ));
>     };
> ```

this is matched from outside.
pass the types vector from the outer match.



_Code quote:_
```XML
    let TypeLongId::Tuple(types) = long_ty else {
        return Err(LoweringFlowError::Failed(
            ctx.diagnostics.report(matched_expr.stable_ptr().untyped(), UnsupportedMatchedValue),
        ));
    };
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4646)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1026 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4646#-NmWFG6aEDjVpXWgaPDJ:-NmWfAhj8Aj3gX6_nPMa:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fcbc87ed00c451d93f98b15ab65f8b16ff1769a3/crates/cairo-lang-lowering/src/lower/mod.rs#L1026)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is matched from outside.
pass the types vector from the outer match.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4646)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1359 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4646#-Nm_DgfQ3ciBpXOIzCOF:-Nm_DgfREfcuKLCnTLnU:b-izujxp) ([raw file](https://github.com/starkware-libs/cairo/blob/551f2b5f715ffa4c6c874d604d2884666b628877/crates/cairo-lang-lowering/src/lower/mod.rs#L1359)):*
> ```XML
> ) -> LoweringResult<LoweredExpr> {
>     let location = expr.location();
>     let types = extract_matches!(long_type_id, TypeLongId::Tuple);
> ```

do not reextract - extract outside the function and pass it in (as you already call `matches!`)



_Code quote:_
```XML
    let types = extract_matches!(long_type_id, TypeLongId::Tuple);
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4646)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1095 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4646#-Nm_IEDv0QajkqTOpbMt:-Nm_IEDv0QajkqTOpbMu:b6vohse) ([raw file](https://github.com/starkware-libs/cairo/blob/551f2b5f715ffa4c6c874d604d2884666b628877/crates/cairo-lang-lowering/src/lower/mod.rs#L1095)):*
> ```XML
> 
> /// Inserts the arm index to the map for each variants list it can match.
> fn insert_arm_patterns(
> ```

doc this is a helper for the other function.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1101 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4646#-Nm_G0P00UIOQcia0xon:-Nm_G0P13Im6rxTz0IbP:b-pxoxae) ([raw file](https://github.com/starkware-libs/cairo/blob/551f2b5f715ffa4c6c874d604d2884666b628877/crates/cairo-lang-lowering/src/lower/mod.rs#L1101)):*
> ```XML
>     extracted_enums_details: &[ExtractedEnumDetails],
>     mut current_variants: Vec<semantic::ConcreteVariant>,
>     map: &mut UnorderedHashMap<Vec<semantic::ConcreteVariant>, usize>,
> ```

struct MatchingPath {
    variants: Vec<semantic::ConcreteVariant>
}



_Code quote:_
```XML
Vec<semantic::ConcreteVariant>
```
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1112 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4646#-Nm_Gp4oCLL1XNLPbmPh:-Nm_Gp4oCLL1XNLPbmPi:b-ib90gb) ([raw file](https://github.com/starkware-libs/cairo/blob/551f2b5f715ffa4c6c874d604d2884666b628877/crates/cairo-lang-lowering/src/lower/mod.rs#L1112)):*
> ```XML
>         };
>         return Ok(());
>     }
> ```

add comment explaining what you are handling here and how.



_Code quote:_
```XML
    let index = current_variants.len();
    if index == patterns.len() {
        match map.entry(current_variants) {
            std::collections::hash_map::Entry::Occupied(_) => {}
            std::collections::hash_map::Entry::Vacant(entry) => {
                entry.insert(arm_index);
            }
        };
        return Ok(());
    }
```
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1139 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4646#-Nm_HrDBAe4ejWMZo4Se:-Nm_HrDBAe4ejWMZo4Sf:bf45h57) ([raw file](https://github.com/starkware-libs/cairo/blob/551f2b5f715ffa4c6c874d604d2884666b628877/crates/cairo-lang-lowering/src/lower/mod.rs#L1139)):*
> ```XML
>             extracted_enums_details[index].concrete_variants.iter().try_for_each(|variant| {
>                 let mut current_variants = current_variants.clone();
>                 current_variants.push(variant.clone());
> ```

add todo for shortcut if not previously handled.



_Code quote:_
```XML
                let mut current_variants = current_variants.clone();
                current_variants.push(variant.clone());
```
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1156 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4646#-Nm_IO8_8uMzOL0WyWVJ:-Nm_IO8_8uMzOL0WyWVK:baula1z) ([raw file](https://github.com/starkware-libs/cairo/blob/551f2b5f715ffa4c6c874d604d2884666b628877/crates/cairo-lang-lowering/src/lower/mod.rs#L1156)):*
> ```XML
> }
> 
> /// Returns a map from variants vector to their corresponding arm index.
> ```

fix doc after adding the struct.



_Code quote:_
```XML
variants vector 
```
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1208 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4646#-Nm_Iq0k9ysh0o-Kr3q1:-Nm_Iq0k9ysh0o-Kr3q2:b-5qbzt) ([raw file](https://github.com/starkware-libs/cairo/blob/551f2b5f715ffa4c6c874d604d2884666b628877/crates/cairo-lang-lowering/src/lower/mod.rs#L1208)):*
> ```XML
> 
> /// Lowers the arm of a match on a tuple expression.
> fn lower_tuple_match_arm(
> ```

rename and fix doc.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4646)* status: all files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1291 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4646#-Nnd2Xe_AEJZc2TsmN9v:-Nnd2XeaBM-xhWwXQXDm:bqguwqk) ([raw file](https://github.com/starkware-libs/cairo/blob/c3d02ce8974c6e25f0708dc7fb884d8232397e59/crates/cairo-lang-lowering/src/lower/mod.rs#L1291)):*
> ```XML
>         Pattern::Otherwise(_) => {
>             extracted_enums_details[index].concrete_variants.iter().try_for_each(|variant| {
>                 // TODO(TomerStarkware): shortcut if no varinat was caught before.
> ```

Make the Todo clearer
___
*[`crates/cairo-lang-lowering/src/test_data/lowering_phases` line 1280 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4646#-Nnd2uMGEBt2N6iTN2GJ:-Nnd2uMGEBt2N6iTN2GK:ba854hj) ([raw file](https://github.com/starkware-libs/cairo/blob/c3d02ce8974c6e25f0708dc7fb884d8232397e59/crates/cairo-lang-lowering/src/test_data/lowering_phases#L1280)):*
> ```
>   (v24: core::panics::PanicResult::<((),)>) <- PanicResult::Err(v15)
> End:
>   Return(v30, v31, v24)
> ```

Revert

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4646)* status: all files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1095 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4646#-Nm_IEDv0QajkqTOpbMt:-NncJKbBD7tkFMsP269N:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/551f2b5f715ffa4c6c874d604d2884666b628877/crates/cairo-lang-lowering/src/lower/mod.rs#L1095)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc this is a helper for the other function.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1101 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4646#-Nm_G0P00UIOQcia0xon:-NncQ4Kx7RIf7l_5YQcI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/551f2b5f715ffa4c6c874d604d2884666b628877/crates/cairo-lang-lowering/src/lower/mod.rs#L1101)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

struct MatchingPath {
    variants: Vec<semantic::ConcreteVariant>
}
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1112 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4646#-Nm_Gp4oCLL1XNLPbmPh:-NncQVP6DMFyv7mBYe6Y:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/551f2b5f715ffa4c6c874d604d2884666b628877/crates/cairo-lang-lowering/src/lower/mod.rs#L1112)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add comment explaining what you are handling here and how.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1139 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4646#-Nm_HrDBAe4ejWMZo4Se:-NncRPRKEhpC4wgaWNY0:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/551f2b5f715ffa4c6c874d604d2884666b628877/crates/cairo-lang-lowering/src/lower/mod.rs#L1139)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add todo for shortcut if not previously handled.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1156 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4646#-Nm_IO8_8uMzOL0WyWVJ:-NncRfFL0bLYxBYAkoLh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/551f2b5f715ffa4c6c874d604d2884666b628877/crates/cairo-lang-lowering/src/lower/mod.rs#L1156)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix doc after adding the struct.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1208 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4646#-Nm_Iq0k9ysh0o-Kr3q1:-NncTbQZ4pCC0tgUanJr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/551f2b5f715ffa4c6c874d604d2884666b628877/crates/cairo-lang-lowering/src/lower/mod.rs#L1208)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rename and fix doc.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1359 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4646#-Nm_DgfQ3ciBpXOIzCOF:-NncWNVYD2FzhzVtLlbt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/551f2b5f715ffa4c6c874d604d2884666b628877/crates/cairo-lang-lowering/src/lower/mod.rs#L1359)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

do not reextract - extract outside the function and pass it in (as you already call `matches!`)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1291 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4646#-Nnd2Xe_AEJZc2TsmN9v:-NndPKWl1jRmurEctPtm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c3d02ce8974c6e25f0708dc7fb884d8232397e59/crates/cairo-lang-lowering/src/lower/mod.rs#L1291)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Make the Todo clearer
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/test_data/lowering_phases` line 1280 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4646#-Nnd2uMGEBt2N6iTN2GJ:-NndPhX34tM_39Du2voH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c3d02ce8974c6e25f0708dc7fb884d8232397e59/crates/cairo-lang-lowering/src/test_data/lowering_phases#L1280)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Revert
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4646)* status: 2 of 4 files reviewed, 9 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1242 at r8](https://reviewable.io/reviews/starkware-libs/cairo/4646#-NneLjzmBwfIOdopWgFc:-NneLjzn3GCYGbLyuavH:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/59ee274632cad57b02e3f826172b08b71ccd8716/crates/cairo-lang-lowering/src/lower/mod.rs#L1242)):*
> ```XML
> struct MatchingPath {
>     variants: Vec<semantic::ConcreteVariant>,
> }
> ```





_Suggestion:_
```XML
/// Represents a path in a match tree.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Default)]
struct MatchingPath {
    /// The variants per member of the tuple matched until this point.
    variants: Vec<semantic::ConcreteVariant>,
}
```
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1245 at r8](https://reviewable.io/reviews/starkware-libs/cairo/4646#-NneLvMu8s9rE7xFOjEx:-NneLvMu8s9rE7xFOjEy:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/59ee274632cad57b02e3f826172b08b71ccd8716/crates/cairo-lang-lowering/src/lower/mod.rs#L1245)):*
> ```XML
> 
> /// an helper function for [get_variants_to_arm_map_tuple] Inserts the pattern path to the map for
> /// each variants list it can match.
> ```





_Suggestion:_
```XML
/// A helper function for [get_variants_to_arm_map_tuple] Inserts the pattern path to the map for
/// each variants list it can match.
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4646)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1292 at r8](https://reviewable.io/reviews/starkware-libs/cairo/4646#-NneQ7Rf-tiNxma2nniF:-NneQ7Rf-tiNxma2nniG:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/59ee274632cad57b02e3f826172b08b71ccd8716/crates/cairo-lang-lowering/src/lower/mod.rs#L1292)):*
> ```XML
>             extracted_enums_details[index].concrete_variants.iter().try_for_each(|variant| {
>                 // TODO(TomerStarkware): remove the split in the tree if the variant choice will not
>                 // change the arm (if no variant was in the path before).
> ```





_Suggestion:_
```XML
                // TODO(TomerStarkware): Remove the match on the variant options in this case if there's no other conflicting arm.
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4646)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4646)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1242 at r8](https://reviewable.io/reviews/starkware-libs/cairo/4646#-NneLjzmBwfIOdopWgFc:-Nni0rqp01EmhavQCeju:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/59ee274632cad57b02e3f826172b08b71ccd8716/crates/cairo-lang-lowering/src/lower/mod.rs#L1242)):*
> ```XML
> struct MatchingPath {
>     variants: Vec<semantic::ConcreteVariant>,
> }
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1245 at r8](https://reviewable.io/reviews/starkware-libs/cairo/4646#-NneLvMu8s9rE7xFOjEx:-Nni0wHX6I2bCee-bpfD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/59ee274632cad57b02e3f826172b08b71ccd8716/crates/cairo-lang-lowering/src/lower/mod.rs#L1245)):*
> ```XML
> 
> /// an helper function for [get_variants_to_arm_map_tuple] Inserts the pattern path to the map for
> /// each variants list it can match.
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1292 at r8](https://reviewable.io/reviews/starkware-libs/cairo/4646#-NneQ7Rf-tiNxma2nniF:-Nni12rO0cEyCRM80xqs:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/59ee274632cad57b02e3f826172b08b71ccd8716/crates/cairo-lang-lowering/src/lower/mod.rs#L1292)):*
> ```XML
>             extracted_enums_details[index].concrete_variants.iter().try_for_each(|variant| {
>                 // TODO(TomerStarkware): remove the split in the tree if the variant choice will not
>                 // change the arm (if no variant was in the path before).
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4646#-:-Nni1h7Z3ZMVcfqU4hOj:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4646)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4646)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
