### PR TITLE
Impl/trait types semantic resolution - phase 0

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5323)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 24 files at r1, 3 of 9 files at r2, 3 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5323)* status: 9 of 27 files reviewed, 5 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 176 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NtqKMUw1CjDvQO-fbFo:-NtqKMUw1CjDvQO-fbFp:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/157c3cc7a015fcc7dca1c124d8dcc55931e46237/crates/cairo-lang-semantic/src/types.rs#L176)):*
> ```XML
> /// the context.
> ///
> /// First `solve()`s the inference once, and then only uses it as a "read-only".
> ```





_Suggestion:_
```XML
///
/// First calls `inference.solve()` once, and then only uses it as a "read-only".
```
___
*[`crates/cairo-lang-semantic/src/types.rs` line 199 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NtqKXdnDIBoTh_KL8Gs:-NtqKXdnDIBoTh_KL8Gt:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/157c3cc7a015fcc7dca1c124d8dcc55931e46237/crates/cairo-lang-semantic/src/types.rs#L199)):*
> ```XML
> /// Tries to implize a type, recursively, according to known inference data.
> ///
> /// Assumes `inference` is `solve()`d and doesn't change it (although it's passed as &mut which is
> ```





_Suggestion:_
```XML
 Assumes `inference.solve()` was calledd and doesn't change the inference structure 
```
___
*[`crates/cairo-lang-semantic/src/types.rs` line 274 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NtqKkDfBTURqin-SUIi:-NtqKkDfBTURqin-SUIj:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/157c3cc7a015fcc7dca1c124d8dcc55931e46237/crates/cairo-lang-semantic/src/types.rs#L274)):*
> ```XML
> /// is only a single impl for MyTrait in the context.
> ///
> /// Assumes the given inference is `solve()`ed.
> ```





_Suggestion:_
```XML
/// Assumes the given `inference.solve()` was called.
```
___
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/neg_impl` line 54 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NtqKrUp3i25cNKalW1V:-NtqKrUp3i25cNKalW1W:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/157c3cc7a015fcc7dca1c124d8dcc55931e46237/crates/cairo-lang-semantic/src/diagnostic_test_data/neg_impl#L54)):*
> ```
> 
> //! > test_runner_name
> test_expr_diagnostics(expect_diagnostics: *)
> ```

?
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1158 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NtqL4aRB6AM1p9QqGwI:-NtqL4aRB6AM1p9QqGwJ:bmaeoqt) ([raw file](https://github.com/starkware-libs/cairo/blob/157c3cc7a015fcc7dca1c124d8dcc55931e46237/crates/cairo-lang-semantic/src/expr/compute.rs#L1158)):*
> ```XML
> 
>     let mut helper = FlowMergeTypeHelper::new(ctx.db);
>     let if_block_ty = ctx.implize_type(if_block.ty())?;
> ```

isn't it it still reduce in all these cases?



_Code quote:_
```XML
    let if_block_ty = ctx.implize_type(if_block.ty())?;
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5323)* status: 9 of 27 files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 176 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NtqKMUw1CjDvQO-fbFo:-NtqP1-x7xHLtwYp_xSs:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/157c3cc7a015fcc7dca1c124d8dcc55931e46237/crates/cairo-lang-semantic/src/types.rs#L176)):*
> ```XML
> /// the context.
> ///
> /// First `solve()`s the inference once, and then only uses it as a "read-only".
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/types.rs` line 199 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NtqKXdnDIBoTh_KL8Gs:-NtqPC1A95djoq-RH5Ng:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/157c3cc7a015fcc7dca1c124d8dcc55931e46237/crates/cairo-lang-semantic/src/types.rs#L199)):*
> ```XML
> /// Tries to implize a type, recursively, according to known inference data.
> ///
> /// Assumes `inference` is `solve()`d and doesn't change it (although it's passed as &mut which is
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/types.rs` line 274 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NtqKkDfBTURqin-SUIi:-NtqPGix0rhrnHvsZozI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/157c3cc7a015fcc7dca1c124d8dcc55931e46237/crates/cairo-lang-semantic/src/types.rs#L274)):*
> ```XML
> /// is only a single impl for MyTrait in the context.
> ///
> /// Assumes the given inference is `solve()`ed.
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/neg_impl` line 54 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NtqKrUp3i25cNKalW1V:-NtqOfU86b9zVnJqhllm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/157c3cc7a015fcc7dca1c124d8dcc55931e46237/crates/cairo-lang-semantic/src/diagnostic_test_data/neg_impl#L54)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1158 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NtqL4aRB6AM1p9QqGwI:-NtqOqqF2nS06Ba-rBaC:bz8izcu) ([raw file](https://github.com/starkware-libs/cairo/blob/157c3cc7a015fcc7dca1c124d8dcc55931e46237/crates/cairo-lang-semantic/src/expr/compute.rs#L1158)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

isn't it it still reduce in all these cases?
</blockquote></details>

Can you clarify the question please?

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 24 files at r1, 1 of 9 files at r2, 5 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5323)* status: 13 of 27 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 24 files at r1, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5323)* status: 18 of 27 files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 223 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NtuTXq75DUkV-QJQWiJ:-NtuTXq75DUkV-QJQWiK:b-2xxycf) ([raw file](https://github.com/starkware-libs/cairo/blob/b4667702ed2c4b793420bfd0ee2c1bbb0422d595/crates/cairo-lang-semantic/src/expr/compute.rs#L223)):*
> ```XML
>             &mut tmp_inference,
>         )
>     }
> ```

These 2 functions seem redundant to me.

probably rename `implize_type` into `reduce_ty`, and remove `reduce_ty`.

Also possibly change return type `TypeId` and just returning missing on failure.



_Code quote:_
```XML
    fn reduce_ty(&mut self, ty: TypeId) -> TypeId {
        // TODO(spapini): Propagate error to diagnostics.
        self.resolver.inference().rewrite(ty).unwrap()
    }

    /// Tries to implize a type, according to the computation context. See [implize_type] for more
    /// details.
    fn implize_type(&mut self, type_to_reduce: TypeId) -> Maybe<TypeId> {
        // TODO(yuval): this is a temporary measure for inference cycle errors to not disappear
        // until fixing inference errors wrong consumption. Remove it once fixed.
        let tmp_inference_data = &mut self.resolver.inference().temporary_clone();
        let mut tmp_inference = tmp_inference_data.inference(self.db);
        implize_type(
            self.db,
            type_to_reduce,
            self.resolver.data.trait_or_impl_ctx.impl_context(),
            &mut tmp_inference,
        )
    }
```
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1640 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NtuU3II5Atw_CDpio8o:-NtuU3II5Atw_CDpio8p:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/b4667702ed2c4b793420bfd0ee2c1bbb0422d595/crates/cairo-lang-semantic/src/items/imp.rs#L1640)):*
> ```XML
> }
> 
> struct ValidateImplFunctionSignatureParams<'a> {
> ```

doc
___
*[`crates/cairo-lang-semantic/src/items/test.rs` line 16 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NtuUCbx2XzeGC0q2lcL:-NtuUCbx2XzeGC0q2lcM:bke3d0u) ([raw file](https://github.com/starkware-libs/cairo/blob/b4667702ed2c4b793420bfd0ee2c1bbb0422d595/crates/cairo-lang-semantic/src/items/test.rs#L16)):*
> ```XML
>         trait_type: "trait_type",
>         trait_type2: "trait_type2",
>         trait_type3: "trait_type3",
> ```

why not same file?
use longer name for differentiation.



_Code quote:_
```XML
        trait_type: "trait_type",
        trait_type2: "trait_type2",
        trait_type3: "trait_type3",
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5323)* status: 13 of 50 files reviewed, 4 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1158 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NtqL4aRB6AM1p9QqGwI:-NtyreIR8rV-1Tb_YNkW:b-gpcjx3) ([raw file](https://github.com/starkware-libs/cairo/blob/157c3cc7a015fcc7dca1c124d8dcc55931e46237/crates/cairo-lang-semantic/src/expr/compute.rs#L1158)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is the type of a block - why is an implize required - and not a reduce?
or do you consider implize a "super" reduce?
</blockquote></details>

yes, implize is a "super" reduce. 
It is possible that it can remain reduce here, but it needs a thorough check to make sure there are no missed cases. I prefer to first bring it to a state where it completely works, then later optimize what we can.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 223 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NtuTXq75DUkV-QJQWiJ:-NtyrHv9CTZd4XIIaFwI:bllmqc2) ([raw file](https://github.com/starkware-libs/cairo/blob/b4667702ed2c4b793420bfd0ee2c1bbb0422d595/crates/cairo-lang-semantic/src/expr/compute.rs#L223)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

These 2 functions seem redundant to me.

probably rename `implize_type` into `reduce_ty`, and remove `reduce_ty`.

Also possibly change return type `TypeId` and just returning missing on failure.
</blockquote></details>

implize contains reduce. Sometimes it's not necessary to implize, in which case it's more efficient to only reduce.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1640 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NtuU3II5Atw_CDpio8o:-Ntyr7K8DWbzlNB72TtO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b4667702ed2c4b793420bfd0ee2c1bbb0422d595/crates/cairo-lang-semantic/src/items/imp.rs#L1640)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/test.rs` line 16 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NtuUCbx2XzeGC0q2lcL:-NtyqR7rDFrnFJhfb-Uj:bslem4n) ([raw file](https://github.com/starkware-libs/cairo/blob/b4667702ed2c4b793420bfd0ee2c1bbb0422d595/crates/cairo-lang-semantic/src/items/test.rs#L16)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why not same file?
use longer name for differentiation.
</blockquote></details>

2 and 3 are just temporary test files for my convenience, they will be removed. added a TODO.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r2, 1 of 11 files at r3, 6 of 32 files at r7, 26 of 27 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5323)* status: 46 of 50 files reviewed, 8 unresolved discussions (waiting on @mkaput and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 223 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NtuTXq75DUkV-QJQWiJ:-Ntz9eyQ2hsp4MUjQUus:b2a3ufk) ([raw file](https://github.com/starkware-libs/cairo/blob/b4667702ed2c4b793420bfd0ee2c1bbb0422d595/crates/cairo-lang-semantic/src/expr/compute.rs#L223)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

implize contains reduce. Sometimes it's not necessary to implize, in which case it's more efficient to only reduce.
</blockquote></details>

what are the cases where you don't need?
___
*[`crates/cairo-lang-semantic/src/items/test.rs` line 15 at r8](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NtzBX3vCn_ND4CbtpXb:-NtzBX3vCn_ND4CbtpXc:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/990e16e6da8b942d023c33309723dc094e2d7f38/crates/cairo-lang-semantic/src/items/test.rs#L15)):*
> ```XML
>         trait_: "trait",
>         trait_type: "trait_type",
>         // TODO(yg): remove.
> ```

.
___
*[`crates/cairo-lang-semantic/src/items/trt.rs` line 805 at r8](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NtzB_UO4G_-SSQNmnAi:-NtzB_UO4G_-SSQNmnAj:b-y75ng8) ([raw file](https://github.com/starkware-libs/cairo/blob/990e16e6da8b942d023c33309723dc094e2d7f38/crates/cairo-lang-semantic/src/items/trt.rs#L805)):*
> ```XML
>     let function_generic_params = inference.rewrite(function_generic_params).no_err();
> 
>     // Validations on the signature.
> ```

this comment seems redundant



_Code quote:_
```XML
    // Validations on the signature.
```
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 283 at r8](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NtzCtnt7nasbqoS7g9r:-NtzCtnt7nasbqoS7g9s:bbzz0si) ([raw file](https://github.com/starkware-libs/cairo/blob/990e16e6da8b942d023c33309723dc094e2d7f38/crates/cairo-lang-semantic/src/items/tests/trait_type#L283)):*
> ```
>     }
> }
> fn main() {
> ```

why not put these in foo?
also everywhere else



_Code quote:_
```
fn main() {
```
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 285 at r8](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NtzCbeK28IDe12fPo42:-NtzCbeK28IDe12fPo43:b-cj3b4g) ([raw file](https://github.com/starkware-libs/cairo/blob/990e16e6da8b942d023c33309723dc094e2d7f38/crates/cairo-lang-semantic/src/items/tests/trait_type#L285)):*
> ```
> fn main() {
>     let x = MyStruct { value: 3_u32 };
>     let _: MyStruct<u32> = MyImpl::foo(x);
> ```

this isn't member access.



_Code quote:_
```
    let _: MyStruct<u32> = MyImpl::foo(x);
```
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type2` line 1 at r8](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NtzDa--93d3rIdDP-DX:-NtzDa--93d3rIdDP-DY:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/990e16e6da8b942d023c33309723dc094e2d7f38/crates/cairo-lang-semantic/src/items/tests/trait_type2#L1)):*
> ```
> //! > impl types cycle
> ```

remove
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type3` line 1 at r8](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NtzDbk6-40h3FX1u5It:-NtzDbk6-40h3FX1u5Iu:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/990e16e6da8b942d023c33309723dc094e2d7f38/crates/cairo-lang-semantic/src/items/tests/trait_type3#L1)):*
> ```
> //! > bla  add as test.
> ```

remove
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 534 at r8](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NtzDtUA3A_0fXemOGD1:-NtzDtUA3A_0fXemOGD2:bav9nf) ([raw file](https://github.com/starkware-libs/cairo/blob/990e16e6da8b942d023c33309723dc094e2d7f38/crates/cairo-lang-semantic/src/resolve/mod.rs#L534)):*
> ```XML
>                     .ok_or_else(|| diagnostics.report(identifier, PathNotFound(item_type)))?;
> 
>                 self.forbid_same_impl_trait(diagnostics, &inner_item_info, identifier)?;
> ```

any reason for this to block the rest of the possible diags?



_Suggestion:_
```XML
                self.forbid_same_impl_trait(diagnostics, &inner_item_info, identifier);
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 32 files at r7, 1 of 27 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5323)* status: 48 of 50 files reviewed, 8 unresolved discussions (waiting on @mkaput and @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5323)* status: 44 of 50 files reviewed, 8 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 223 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NtuTXq75DUkV-QJQWiJ:-NuIa72V9LP3MMpTtiiL:b-q89z6w) ([raw file](https://github.com/starkware-libs/cairo/blob/b4667702ed2c4b793420bfd0ee2c1bbb0422d595/crates/cairo-lang-semantic/src/expr/compute.rs#L223)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

what are the cases where you don't need?
</blockquote></details>

If I know I could not have an impl type. E.g. in a free function signature.
Also if all code paths guarantee the type is already implized (this might be the case in the other comment about the if block type for example), but this requires thorough check or coverage to guarantee.
___
*[`crates/cairo-lang-semantic/src/items/test.rs` line 15 at r8](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NtzBX3vCn_ND4CbtpXb:-NuIjc606nWmdt5c5pRP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/990e16e6da8b942d023c33309723dc094e2d7f38/crates/cairo-lang-semantic/src/items/test.rs#L15)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/trt.rs` line 805 at r8](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NtzB_UO4G_-SSQNmnAi:-NuIjfUK01G3u32YSl73:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/990e16e6da8b942d023c33309723dc094e2d7f38/crates/cairo-lang-semantic/src/items/trt.rs#L805)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this comment seems redundant
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 283 at r8](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NtzCtnt7nasbqoS7g9r:-NuIkZC_AEJfx2hKAA3d:b-jwyzr2) ([raw file](https://github.com/starkware-libs/cairo/blob/990e16e6da8b942d023c33309723dc094e2d7f38/crates/cairo-lang-semantic/src/items/tests/trait_type#L283)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why not put these in foo?
also everywhere else
</blockquote></details>

I find it less readable, but I anyway want to change it sometime to be more readable, so moved to foo for now, here and in other tests
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 285 at r8](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NtzCbeK28IDe12fPo42:-NuIhoA9B994_IWBwnM-:bsucu1n) ([raw file](https://github.com/starkware-libs/cairo/blob/990e16e6da8b942d023c33309723dc094e2d7f38/crates/cairo-lang-semantic/src/items/tests/trait_type#L285)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this isn't member access.
</blockquote></details>

There is member access in foo, which I wanted to also call in the test
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type2` line 1 at r8](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NtzDa--93d3rIdDP-DX:-NuIjh9LBB1Fqw3Q8JdX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/990e16e6da8b942d023c33309723dc094e2d7f38/crates/cairo-lang-semantic/src/items/tests/trait_type2#L1)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type3` line 1 at r8](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NtzDbk6-40h3FX1u5It:-NuIjbL2EAqbPDKOnmrg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/990e16e6da8b942d023c33309723dc094e2d7f38/crates/cairo-lang-semantic/src/items/tests/trait_type3#L1)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 534 at r8](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NtzDtUA3A_0fXemOGD1:-NuIhHPGA8XrDNc8_37u:b-w68376) ([raw file](https://github.com/starkware-libs/cairo/blob/990e16e6da8b942d023c33309723dc094e2d7f38/crates/cairo-lang-semantic/src/resolve/mod.rs#L534)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

any reason for this to block the rest of the possible diags?
</blockquote></details>

Probably right, but moving this to a following PR, will change there.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5323#-:-NuIujul0_7DBI_DOimo:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 17 of 27 files at r10, 7 of 8 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5323)* status: 53 of 56 files reviewed, 4 unresolved discussions (waiting on @mkaput and @yuvalsw)

___
*[`crates/cairo-lang-debug/src/debug.rs` line 57 at r11](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NvVKjkZBc-2SK7eyHq2:-NvVKjkZBc-2SK7eyHq3:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/acab7c84de6dd7d77d81a05a9836d58a750188ad/crates/cairo-lang-debug/src/debug.rs#L57)):*
> ```XML
>     fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
>         DebugWithDb::fmt(&*self.value, f, self.db)
>         // (&*self.value).fmt(f, self.db)
> ```

.
___
*[`crates/cairo-lang-debug/src/debug.rs` line 128 at r11](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NvVKokt0A0GG-lstssW:-NvVKokt0A0GG-lstssX:blzgvx8) ([raw file](https://github.com/starkware-libs/cairo/blob/acab7c84de6dd7d77d81a05a9836d58a750188ad/crates/cairo-lang-debug/src/debug.rs#L128)):*
> ```XML
> }
> 
> impl<Db: ?Sized, K, V> DebugWithDb<Db> for BTreeMap<K, V>
> ```

out of this PR.
___
*[`crates/cairo-lang-defs/src/ids.rs` line 265 at r11](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NvVKuOu07UmTkaK38ei:-NvVKuOu07UmTkaK38ej:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/acab7c84de6dd7d77d81a05a9836d58a750188ad/crates/cairo-lang-defs/src/ids.rs#L265)):*
> ```XML
> /// Id for a module. Either the root module of a crate, or a submodule.
> #[derive(Copy, Clone, Debug, Hash, PartialEq, Eq /* , DebugWithDb */)]
> // #[debug_db(dyn DefsGroup + 'static)]
> ```

.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1090 at r11](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NvVMB616RT0Xt9xf0M7:-NvVMB616RT0Xt9xf0M8:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/acab7c84de6dd7d77d81a05a9836d58a750188ad/crates/cairo-lang-semantic/src/items/imp.rs#L1090)):*
> ```XML
>         return false;
>     };
>     // enrich_lookup_context(ctx.db, concrete_trait_id, &mut lookup_context);
> ```

.

**Review by mkaput — APPROVED** [review]
> Reviewed 1 of 11 files at r3, 3 of 6 files at r5, 1 of 32 files at r7, 22 of 27 files at r8, 2 of 8 files at r9, 19 of 27 files at r10, 8 of 8 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5323)* status: all files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5323)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-debug/src/debug.rs` line 57 at r11](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NvVKjkZBc-2SK7eyHq2:-NvVt2Vq9QX-1ZyFOIcZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/acab7c84de6dd7d77d81a05a9836d58a750188ad/crates/cairo-lang-debug/src/debug.rs#L57)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-debug/src/debug.rs` line 128 at r11](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NvVKokt0A0GG-lstssW:-NvVt2qQ62imaJOuhFfc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/acab7c84de6dd7d77d81a05a9836d58a750188ad/crates/cairo-lang-debug/src/debug.rs#L128)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

out of this PR.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-defs/src/ids.rs` line 265 at r11](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NvVKuOu07UmTkaK38ei:-NvVtiyw0DA83bP7vpub:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/acab7c84de6dd7d77d81a05a9836d58a750188ad/crates/cairo-lang-defs/src/ids.rs#L265)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1090 at r11](https://reviewable.io/reviews/starkware-libs/cairo/5323#-NvVMB616RT0Xt9xf0M7:-NvVu2TTEZ5oO59O1Vvu:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/acab7c84de6dd7d77d81a05a9836d58a750188ad/crates/cairo-lang-semantic/src/items/imp.rs#L1090)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 3 of 6 files at r5, 22 of 27 files at r8, 2 of 8 files at r9, 1 of 27 files at r10, 1 of 3 files at r12, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5323)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
