### PR TITLE
adding for loop to lowering

### PR DESCRIPTION
**Pull request by Tomer-StarkWare**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5917)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5917)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware, @Tomer-StarkWare, and @TomerStarkware)

___
*[`corelib/src/test/array_test.cairo` line 222 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5917#-O0cDZj_CXmxgJ9if1oT:-O0cDZj_CXmxgJ9if1oU:b52818h) ([raw file](https://github.com/starkware-libs/cairo/blob/d10f0c6a504554e03813c02556fb5d8cbe5c9623/corelib/src/test/array_test.cairo#L222)):*
> ```Cairo
> 
> #[test]
> fn test_for_loop_array_sum() {
> ```

move tests to `language_features` directory.
___
*[`corelib/src/test/array_test.cairo` line 249 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5917#-O0cDWQp74r_v0TXpUqI:-O0cDWQp74r_v0TXpUqJ:b-kgpoxp) ([raw file](https://github.com/starkware-libs/cairo/blob/d10f0c6a504554e03813c02556fb5d8cbe5c9623/corelib/src/test/array_test.cairo#L249)):*
> ```Cairo
>         i += 1;
>     };
> }
> ```

add empty line.

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5917)* status: 6 of 13 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware, @orizi, and @TomerStarkware)

___
*[`corelib/src/test/array_test.cairo` line 222 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5917#-O0cDZj_CXmxgJ9if1oT:-O0cRhuE2njZ050OsIrz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d10f0c6a504554e03813c02556fb5d8cbe5c9623/corelib/src/test/array_test.cairo#L222)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

move tests to `language_features` directory.
</blockquote></details>

Done.
___
*[`corelib/src/test/array_test.cairo` line 249 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5917#-O0cDWQp74r_v0TXpUqI:-O0cNRbgD3EZ_XUTXKyM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d10f0c6a504554e03813c02556fb5d8cbe5c9623/corelib/src/test/array_test.cairo#L249)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add empty line.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1, 2 of 5 files at r3, 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5917)* status: 11 of 13 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware, @Tomer-StarkWare, and @TomerStarkware)

___
*[`corelib/src/test/language_features/for_test.cairo` line 1 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5917#-O0cSOLQ21Z7nByFKnS5:-O0cSOLQ21Z7nByFKnS6:b44635h) ([raw file](https://github.com/starkware-libs/cairo/blob/13d1ebeb004b939fde11f7a30ad50d40dd9fd372/corelib/src/test/language_features/for_test.cairo#L1)):*
> ```Cairo
> use core::test::test_utils::{assert_eq, assert_ne};
> ```

remove imports - not actually used.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 198 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5917#-O0cT-UL3O3WZV2eyX63:-O0cT-UL3O3WZV2eyX64:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/13d1ebeb004b939fde11f7a30ad50d40dd9fd372/crates/cairo-lang-lowering/src/lower/mod.rs#L198)):*
> ```XML
>             }
>             _ => unreachable!(),
>         };
> ```





_Suggestion:_
```XML
    let ErrorPropagationType::Option { some_variant, none_variant } =
        match unwrap_error_propagation_type(semantic_db, ctx.variables[next_value.var_id].ty)
            .expect("proper-reason-why-propagation-type")
        else {
            unreachable!("proper reason why unreachable"),
        };
```

**Review by TomerStarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 9 files at r1, 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5917#-:-O0ca04TEGbg0bvfg_sS:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5917)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`corelib/src/test/language_features/for_test.cairo` line 1 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5917#-O0cSOLQ21Z7nByFKnS5:-O0c_XFu4IibNdl4uDOp:bz6h33w) ([raw file](https://github.com/starkware-libs/cairo/blob/13d1ebeb004b939fde11f7a30ad50d40dd9fd372/corelib/src/test/language_features/for_test.cairo#L1)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove imports - not actually used.
</blockquote></details>

Alright, I removed in the while_test as well then
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 198 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5917#-O0cT-UL3O3WZV2eyX63:-O0ccCj66rxD8o2sls_7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/13d1ebeb004b939fde11f7a30ad50d40dd9fd372/crates/cairo-lang-lowering/src/lower/mod.rs#L198)):*
> ```XML
>             }
>             _ => unreachable!(),
>         };
> ```

Done.

**Review by TomerStarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5917#-:-O0cnmuQ9jZD_IjjsauJ:bnfp4nl)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5917)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by TomerStarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5917)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5917)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
