### PR TITLE
fix(formatter): incorrect exit code on files with syntax errors

### LINKED ISSUE #1088: bug: files with syntax error incorrectly reported as well-formatted
# Bug Report

**Cairo version:**

Using the current `main` at `5435626`.

**Steps to reproduce:**

Create an empty folder containing only an unparseable cairo file. Then try to run a formatter check:

```console
$ mkdir fmt_test && cd fmt_test
$ echo "asdf" > file.cairo
$ formatter_cli --check
$ echo $?
```

**Current behavior:**

The formatter _does indeed_ report an error regarding the issue: `A parsing error occurred in file: ./file.cairo. The file was not formatted.`

However, the exit code is `0`, indicating a success:

```console
$ echo $?
0
```

This would cause CI workflows to give false negative on format errors, since CI workflows would only check the exit code. Editors would also interpret the result as successful and replace file content with the error message.

**Expected behavior:**

The exit code should be non-zero.

**Related code:**

This is what's causing the false negative.

https://github.com/starkware-libs/cairo/blob/5435626b17538dbbec6ae1f7706abc8bec212863/crates/formatter/src/bin/cli.rs#L26-L33

**Other information:**

N/A

### PR DESCRIPTION
**Pull request by xJonathanLEI**
Fixes #1088.

For the PR title and commit message, since I failed to find a consistent commit style across the recent Git history, I'm using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) instead. Please let me know if there's a desired style, thanks!

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1089)

### CODE REVIEW

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1089#-:-NHn_oL_0wUhplNrwJdn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @xJonathanLEI)

**Comment by mkaput** [comment]
> For the PR title and commit message, since I failed to find a consistent commit style across the recent Git history, I'm using Conventional Commits instead. Please let me know if there's a desired style, thanks!

I do not recall any conversations about message style so in general I'd simply assume using descriptive titles 😃 your title is perfectly fine!

**Comment by xJonathanLEI** [comment]
Thanks for the reviews! Please let me know if anything is pending from my side.

**Review by spapinistarkware — APPROVED** [review]
Yeah, the PR should be up to date with origin/main to merge - to make sure CI runs on the latest version. So, update the PR, and we can merge when everything passes.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1089#-:-NHyYCNG1D0VBROfKv-J:bbsh66f)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @xJonathanLEI)

**Comment by xJonathanLEI** [comment]
Ah I wasn't aware of that being a requirement. Rebased now :)

**Review by spapinistarkware — APPROVED** [review]
lol, there are now error in the CI, since we have test files which are not formatted correctly. Care to fix this too?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1089#-:-NHyZOCr53sPNSDvn1cE:bpekqrw)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @xJonathanLEI)

**Comment by xJonathanLEI** [comment]
Wait that's auto-merged? lol

**Comment by spapinistarkware** [comment]
Oops, I tihnk we broke main :S weird, Ill check why CI didnt stop it

**Comment by xJonathanLEI** [comment]
Yeah I thought the auto-merge were going through only if CI passes.

**Comment by spapinistarkware** [comment]
Seems it's not a mandatory check

**Pull request merged**
