### PR TITLE
Added support for `!=`.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #1244
- #1232 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1232)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1232)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`corelib/integer.cairo` line 167 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1232#-NIbZYK58P-V0XRJSjJh:-NIbZYK58P-V0XRJSjJi:btacd42) ([raw file](https://github.com/starkware-libs/cairo/blob/7b306c2b28a4956b373156a6cc08982e04e7f5a7/corelib/integer.cairo#L167)):*
> ```Cairo
> }
> 
> func uint128_ne(a: uint128, b: uint128) -> bool implicits() nopanic {
> ```

why are you adding it if the
!(a == b)
works?



_Code quote:_
```Cairo
uint128_ne
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1232)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`corelib/integer.cairo` line 167 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1232#-NIbZYK58P-V0XRJSjJh:-NIbZgqLCg2yVB60-tbz:b-olm8dl) ([raw file](https://github.com/starkware-libs/cairo/blob/7b306c2b28a4956b373156a6cc08982e04e7f5a7/corelib/integer.cairo#L167)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why are you adding it if the
!(a == b)
works?
</blockquote></details>

is it a place holder for a more optimized implementation?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1232)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`corelib/integer.cairo` line 167 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1232#-NIbZYK58P-V0XRJSjJh:-NIcPg-E0BkZmomtDexw:bi9vc8e) ([raw file](https://github.com/starkware-libs/cairo/blob/2aae96e7127419163967f5a6e464fb7ee917e632/corelib/integer.cairo#L167)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

is it a place holder for a more optimized implementation?
</blockquote></details>

So I'd be able to call the operator

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1232)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
