### PR TITLE
Avoid recursion by keeping the list of pending statement in a vector.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1915)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1915)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 309 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1915#-NMgw-aY00RLZ9f921Pn:-NMgw-aY00RLZ9f921Po:b-7fcin2) ([raw file](https://github.com/starkware-libs/cairo/blob/a9387503e1f74c3fc15ea6e3a335b8237ff8d156/crates/cairo-lang-lowering/src/inline/mod.rs#L309)):*
> ```XML
>     // Rewrites statement and either appends it to self.statements or
>     // adds a a list of statements that needs rewritting to self.pending
>     fn rewrite(&mut self, statement: Statement) -> Maybe<()> {
> ```

The interface is more cumbersome, but at least we don't have recursion.

If you have better Idea I'll be happy to hear them.



_Code quote:_
```XML
    // Rewrites statement and either appends it to self.statements or
    // adds a a list of statements that needs rewritting to self.pending
    fn rewrite(&mut self, statement: Statement) -> Maybe<()> {
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1915)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 170 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1915#-NMgzJdNEHY9ENbKuKCb:-NMgzJdNEHY9ENbKuKCc:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/a9387503e1f74c3fc15ea6e3a335b8237ff8d156/crates/cairo-lang-lowering/src/inline/mod.rs#L170)):*
> ```XML
> 
>     // Statements that require rewriting in reverse order..
>     rev_pending: Vec<Statement>,
> ```

?



_Suggestion:_
```XML
statement_rewrite_stack: Vec<Statement>,
```
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 389 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1915#-NMgzR7k64nSZTQBRwdE:-NMgzR7k64nSZTQBRwdF:b1mji6a) ([raw file](https://github.com/starkware-libs/cairo/blob/a9387503e1f74c3fc15ea6e3a335b8237ff8d156/crates/cairo-lang-lowering/src/inline/mod.rs#L389)):*
> ```XML
>         }
> 
>         for statement in root_block.statements.iter().rev() {
> ```

doc here why to do the reverse ordering.



_Code quote:_
```XML
        for statement in root_block.statements.iter().rev() {
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 389 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1915#-NMgzR7k64nSZTQBRwdE:-NMgzcgy2uR8UCsW44BX:b-ovv9k6) ([raw file](https://github.com/starkware-libs/cairo/blob/a9387503e1f74c3fc15ea6e3a335b8237ff8d156/crates/cairo-lang-lowering/src/inline/mod.rs#L389)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc here why to do the reverse ordering.
</blockquote></details>

because the stack is in reverse order?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1915)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 389 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1915#-NMgzR7k64nSZTQBRwdE:-NMgzqCI688wODGr2bce:b4ikb01) ([raw file](https://github.com/starkware-libs/cairo/blob/a9387503e1f74c3fc15ea6e3a335b8237ff8d156/crates/cairo-lang-lowering/src/inline/mod.rs#L389)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

because the stack is in reverse order?
</blockquote></details>

i mean - why do you need to rebuild these in reverse order (that is the reason for the stack)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 170 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1915#-NMgzJdNEHY9ENbKuKCb:-NMh1Qzc5b4UR6mKXr21:b2d5fky) ([raw file](https://github.com/starkware-libs/cairo/blob/a9387503e1f74c3fc15ea6e3a335b8237ff8d156/crates/cairo-lang-lowering/src/inline/mod.rs#L170)):*
> statement_rewrite_stack
Good name, thanks!

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1915)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 389 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1915#-NMgzR7k64nSZTQBRwdE:-NMh1VoJ0S7e28n_elzq:bhge2o3) ([raw file](https://github.com/starkware-libs/cairo/blob/a9387503e1f74c3fc15ea6e3a335b8237ff8d156/crates/cairo-lang-lowering/src/inline/mod.rs#L389)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i mean - why do you need to rebuild these in reverse order (that is the reason for the stack)
</blockquote></details>

I don't want to rebuild them in reverse order.

The problem is that pushing and poping from the stack reverses the order and I want to avoid reversing the order.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1915)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 389 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1915#-NMh1e3L9WioZrD91T3g:-NMh1e3M3c0tzFOjJaP8:bhnxaxb) ([raw file](https://github.com/starkware-libs/cairo/blob/ac59e31fe200fc581b47204d3f82b2b201aac567/crates/cairo-lang-lowering/src/inline/mod.rs#L389)):*
> ```XML
>         }
> 
>         // Inline enqueue_statments() to avoid self lifetime issue.
> ```

This is very annoying.

Is there a way to borrow self.ctx without borrowing self?



_Code quote:_
```XML
Inline enqueue_statments() 
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1915)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 389 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1915#-NMh1e3L9WioZrD91T3g:-NMh2NwcBc6YvsLTSQjO:b-qv5656) ([raw file](https://github.com/starkware-libs/cairo/blob/ac59e31fe200fc581b47204d3f82b2b201aac567/crates/cairo-lang-lowering/src/inline/mod.rs#L389)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

This is very annoying.

Is there a way to borrow self.ctx without borrowing self?
</blockquote></details>

error[E0499]: cannot borrow `*self` as mutable more than once at a time
   --> crates/cairo-lang-lowering/src/inline/mod.rs:390:9
    |
347 |               ctx: &mut self.ctx,
    |                    ------------- first mutable borrow occurs here
...
390 | /         self.enqueue_statments(
391 | |             root_block.statements.iter().map(|statement| mapper.rebuild_statement(statement)),
    | |                                                          ------ first borrow later captured here by closure
392 | |         );
    | |_________^ second mutable borrow occurs here

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1915)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 169 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1915#-NMh2_zzDl9XuDlwcnyo:-NMh2_zzDl9XuDlwcnyp:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ac59e31fe200fc581b47204d3f82b2b201aac567/crates/cairo-lang-lowering/src/inline/mod.rs#L169)):*
> ```XML
>     statements: Vec<Statement>,
> 
>     // Statements that require rewriting in reverse order..
> ```





_Suggestion:_
```XML
    /// A Queue of blocks on which we want to apply the FunctionInlinerRewriter.
    block_queue: BlockQueue,

    /// rewritten statments.
    statements: Vec<Statement>,

    /// Statements that require rewriting in reverse order.
    statement_rewrite_stack: Vec<Statement>,
```
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 389 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1915#-NMh1e3L9WioZrD91T3g:-NMh3Ko646LIb__eUob5:b-1k9slb) ([raw file](https://github.com/starkware-libs/cairo/blob/ac59e31fe200fc581b47204d3f82b2b201aac567/crates/cairo-lang-lowering/src/inline/mod.rs#L389)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

error[E0499]: cannot borrow `*self` as mutable more than once at a time
   --> crates/cairo-lang-lowering/src/inline/mod.rs:390:9
    |
347 |               ctx: &mut self.ctx,
    |                    ------------- first mutable borrow occurs here
...
390 | /         self.enqueue_statments(
391 | |             root_block.statements.iter().map(|statement| mapper.rebuild_statement(statement)),
    | |                                                          ------ first borrow later captured here by closure
392 | |         );
    | |_________^ second mutable borrow occurs here
</blockquote></details>

the solution i see is adding the ref to the rewrite stack to the mapper as well.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1915)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 308 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1915#-NMh67B0B8JpQ2vdaHMe:-NMh67B0B8JpQ2vdaHMf:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/ac59e31fe200fc581b47204d3f82b2b201aac567/crates/cairo-lang-lowering/src/inline/mod.rs#L308)):*
> ```XML
> 
>     // Rewrites statement and either appends it to self.statements or
>     // adds a a list of statements that needs rewritting to self.pending
> ```

.



_Suggestion:_
```XML
    /// Rewrites statement and either appends it to self.statements or
    /// adds a a list of statements that needs rewritting to self.pending.
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1915)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 169 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1915#-NMh2_zzDl9XuDlwcnyo:-NMhBEmu8NcgGK_1f2vf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ac59e31fe200fc581b47204d3f82b2b201aac567/crates/cairo-lang-lowering/src/inline/mod.rs#L169)):*
> ```XML
>     statements: Vec<Statement>,
> 
>     // Statements that require rewriting in reverse order..
> ```

Done.



_Code quote:_
```XML
statement_rewrite_stack
```
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 308 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1915#-NMh67B0B8JpQ2vdaHMe:-NMhBFp2CCCFRLfU5gGc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ac59e31fe200fc581b47204d3f82b2b201aac567/crates/cairo-lang-lowering/src/inline/mod.rs#L308)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 389 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1915#-NMh1e3L9WioZrD91T3g:-NMhBQo08bbMapWgdfyd:bmghlph) ([raw file](https://github.com/starkware-libs/cairo/blob/ac59e31fe200fc581b47204d3f82b2b201aac567/crates/cairo-lang-lowering/src/inline/mod.rs#L389)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the solution i see is adding the ref to the rewrite stack to the mapper as well.
</blockquote></details>

It seems that the solution is to wrap Statement_rewrite_stack inside another struct :)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1915)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 308 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1915#-NMh67B0B8JpQ2vdaHMe:-NMhDXuP3gytDm7ZU_Mm:b-284aay) ([raw file](https://github.com/starkware-libs/cairo/blob/ac59e31fe200fc581b47204d3f82b2b201aac567/crates/cairo-lang-lowering/src/inline/mod.rs#L308)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

no it isn't
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 185 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1915#-NMhDjoZDQSWAJNUfV9Z:-NMhDjoZDQSWAJNUfV9_:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7b228b77431133a322e1d432264fd068c0cdbd8a/crates/cairo-lang-lowering/src/inline/mod.rs#L185)):*
> ```XML
>     }
> 
>     fn push_statment(&mut self) -> Option<Statement> {
> ```





_Suggestion:_
```XML
    fn pop_statment(&mut self) -> Option<Statement> {
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1915)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 408 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1915#-NMhDwxE9TQWWKhRvn1w:-NMhDwxE9TQWWKhRvn1x:b83danx) ([raw file](https://github.com/starkware-libs/cairo/blob/7b228b77431133a322e1d432264fd068c0cdbd8a/crates/cairo-lang-lowering/src/inline/mod.rs#L408)):*
> ```XML
>         }
> 
>         // Inline enqueue_statments() to avoid self lifetime issue.
> ```

probably fix



_Code quote:_
```XML
        // Inline enqueue_statments() to avoid self lifetime issue.
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1915)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 308 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1915#-NMh67B0B8JpQ2vdaHMe:-NMhE2gx2PbB2s4vdLYx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ac59e31fe200fc581b47204d3f82b2b201aac567/crates/cairo-lang-lowering/src/inline/mod.rs#L308)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no it isn't
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 185 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1915#-NMhDjoZDQSWAJNUfV9Z:-NMhE3-c43WzH2TW8iyn:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7b228b77431133a322e1d432264fd068c0cdbd8a/crates/cairo-lang-lowering/src/inline/mod.rs#L185)):*
> ```XML
>     }
> 
>     fn push_statment(&mut self) -> Option<Statement> {
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 408 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1915#-NMhDwxE9TQWWKhRvn1w:-NMhEaxI3-p6ZqJx6zrp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7b228b77431133a322e1d432264fd068c0cdbd8a/crates/cairo-lang-lowering/src/inline/mod.rs#L408)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

probably fix
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1915#-:-NMhErov6T6XyffCfYDl:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1915)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
