### PR TITLE
Extracted runner code into a runner lib - using it in tests as well.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:c9eb9c63

---

**Stack**:
- #1232
- #1231
- #1230
- #1229
- #1228
- #1227
- #1205
- #1204
- #1201
- #1200
- #1199
- #1194 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by Alon-Ti — APPROVED** [review]
> Reviewed 6 of 8 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1194)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware, @orizi, and @spapinistarkware)

___
*[`crates/runner/src/cli.rs` line 58 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1194#-NIXdgqQ82J60Fsyo_jZ:-NIXdgqRCzI7yoeWbMEv:b-h8og3s) ([raw file](https://github.com/starkware-libs/cairo/blob/9c4a5eb43afa1086b8a6ff485e2ac4f5e9e5c0b8/crates/runner/src/cli.rs#L58)):*
> ```XML
>         }
>         runner::RunResultValue::Panic(values) => {
>             println!("Run paniced with err values: {values:?}")
> ```

panicked

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1194)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/runner/src/lib.rs` line 225 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1194#-NIaP3t61o-Hozk8UCXp:-NIaP3t61o-Hozk8UCXq:b-ic4bii) ([raw file](https://github.com/starkware-libs/cairo/blob/792e8f6407dbbf7dcbd16adaea070b681b51da85/crates/runner/src/lib.rs#L225)):*
> ```XML
>                     casm_extend! {ctx,
>                         [ap + 0] = (value.clone()), ap++;
>                     }
> ```

shouldn't you have a loop here based on the size of the type?



_Code quote:_
```XML
                    casm_extend! {ctx,
                        [ap + 0] = (value.clone()), ap++;
                    }
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1194)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/runner/src/lib.rs` line 200 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1194#-NIaO49zDJiNeWvKZ4NZ:-NIaPBSO6_bDmJkaD1q7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/792e8f6407dbbf7dcbd16adaea070b681b51da85/crates/runner/src/lib.rs#L200)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Add a todo to use the range check segment.
</blockquote></details>

Done.
___
*[`crates/runner/src/lib.rs` line 208 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1194#-NIaOl-l3SFG-QgdB4Nl:-NIaPIEO5WT7zjCqQzmH:brjgqsu) ([raw file](https://github.com/starkware-libs/cairo/blob/792e8f6407dbbf7dcbd16adaea070b681b51da85/crates/runner/src/lib.rs#L208)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why?
</blockquote></details>

we take the actual cost of the functions in the cases we run with gas.
___
*[`crates/runner/src/lib.rs` line 225 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1194#-NIaP3t61o-Hozk8UCXp:-NIaPEicD1yqQnOqwDHp:b-wkzvga) ([raw file](https://github.com/starkware-libs/cairo/blob/792e8f6407dbbf7dcbd16adaea070b681b51da85/crates/runner/src/lib.rs#L225)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

shouldn't you have a loop here based on the size of the type?
</blockquote></details>

no - as these are raw params.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/runner/src/lib.rs` line 79 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1194#-NIaTwd35EhiGCjQguvB:-NIaTwd35EhiGCjQguvC:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/792e8f6407dbbf7dcbd16adaea070b681b51da85/crates/runner/src/lib.rs#L79)):*
> ```XML
>     }
> 
>     /// Runs the vm starting from a function. Function may have implicits, but no other ref params.
> ```





_Suggestion:_
```XML
  /// Runs the vm starting from a function. Function may have implicits, but no other ref params.
  /// The cost of the function is deducted from available_gas before the execution begins.
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1194)* status: 6 of 8 files reviewed, 4 unresolved discussions (waiting on @Alon-Ti, @orizi, and @spapinistarkware)

___
*[`crates/runner/src/lib.rs` line 208 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1194#-NIaOl-l3SFG-QgdB4Nl:-NIaUMASAEnnzGYuUb1J:b-4jk3nl) ([raw file](https://github.com/starkware-libs/cairo/blob/792e8f6407dbbf7dcbd16adaea070b681b51da85/crates/runner/src/lib.rs#L208)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

we take the actual cost of the functions in the cases we run with gas.
</blockquote></details>

this should be mentioned somewhere.
___
*[`crates/runner/src/lib.rs` line 225 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1194#-NIaP3t61o-Hozk8UCXp:-NIaUlfB-jUQZB8PkmQV:b7nsvmr) ([raw file](https://github.com/starkware-libs/cairo/blob/792e8f6407dbbf7dcbd16adaea070b681b51da85/crates/runner/src/lib.rs#L225)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no - as these are raw params.
</blockquote></details>

either fix or assert that 
 self.sierra_program_registry.get_type(ty)?.info().size is 1

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1194)* status: 0 of 14 files reviewed, 3 unresolved discussions (waiting on @Alon-Ti, @ilyalesokhin-starkware, and @spapinistarkware)

___
*[`crates/runner/src/lib.rs` line 79 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1194#-NIaTwd35EhiGCjQguvB:-NIaVeBk94Sgk-xDV3AI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/792e8f6407dbbf7dcbd16adaea070b681b51da85/crates/runner/src/lib.rs#L79)):*
> ```XML
>     }
> 
>     /// Runs the vm starting from a function. Function may have implicits, but no other ref params.
> ```

Done.
___
*[`crates/runner/src/lib.rs` line 225 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1194#-NIaP3t61o-Hozk8UCXp:-NIaVVuA1mnokWFOY0tF:b-qssebl) ([raw file](https://github.com/starkware-libs/cairo/blob/792e8f6407dbbf7dcbd16adaea070b681b51da85/crates/runner/src/lib.rs#L225)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

either fix or assert that 
 self.sierra_program_registry.get_type(ty)?.info().size is 1
</blockquote></details>

fixed.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1194)* status: 0 of 14 files reviewed, 4 unresolved discussions (waiting on @Alon-Ti, @orizi, and @spapinistarkware)

___
*[`crates/sierra_to_casm/src/invocations/dict_felt_to.rs` line 194 at r7](https://reviewable.io/reviews/starkware-libs/cairo/1194#-NIaXVy6ClfpZ_V_R8zI:-NIaXVy70l8gwy0IcB7k:b77xz9y) ([raw file](https://github.com/starkware-libs/cairo/blob/8eb4194cd29ad05356592d7d41b7a4ef75b90f33/crates/sierra_to_casm/src/invocations/dict_felt_to.rs#L194)):*
> ```XML
> 
> /// Handles the dict_squash instruction.
> fn build_dict_felt_to_squash(
> ```

why is this in that PR?



_Code quote:_
```XML
build_dict_felt_to_squash
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1194)* status: 0 of 14 files reviewed, 4 unresolved discussions (waiting on @Alon-Ti, @ilyalesokhin-starkware, and @spapinistarkware)

___
*[`crates/sierra_to_casm/src/invocations/dict_felt_to.rs` line 194 at r7](https://reviewable.io/reviews/starkware-libs/cairo/1194#-NIaXVy6ClfpZ_V_R8zI:-NIaZGDb6mobwNa0jeMn:b-debodo) ([raw file](https://github.com/starkware-libs/cairo/blob/8eb4194cd29ad05356592d7d41b7a4ef75b90f33/crates/sierra_to_casm/src/invocations/dict_felt_to.rs#L194)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why is this in that PR?
</blockquote></details>

reviewable stuff - ignore.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1194)* status: 0 of 14 files reviewed, 5 unresolved discussions (waiting on @Alon-Ti, @orizi, and @spapinistarkware)

___
*[`crates/runner/src/lib.rs` line 226 at r8](https://reviewable.io/reviews/starkware-libs/cairo/1194#-NIabGmM5Dx3v2oLMZv-:-NIabGmM5Dx3v2oLMZv0:bpllu37) ([raw file](https://github.com/starkware-libs/cairo/blob/5233c4c1d91df9d5ab2d40b02196195a215f4c90/crates/runner/src/lib.rs#L226)):*
> ```XML
>                 expected_arguments_size += arg_size;
>                 for _ in 0..arg_size {
>                     if let Some(value) = arg_iter.next() {
> ```

what if it fails?



_Code quote:_
```XML
let Some(value) = arg_iter.next()
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1194)* status: 0 of 14 files reviewed, 5 unresolved discussions (waiting on @Alon-Ti, @ilyalesokhin-starkware, and @spapinistarkware)

___
*[`crates/runner/src/lib.rs` line 226 at r8](https://reviewable.io/reviews/starkware-libs/cairo/1194#-NIabGmM5Dx3v2oLMZv-:-NIabbEU6lT5cnhGUc3T:b-t75wss) ([raw file](https://github.com/starkware-libs/cairo/blob/5233c4c1d91df9d5ab2d40b02196195a215f4c90/crates/runner/src/lib.rs#L226)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what if it fails?
</blockquote></details>

the size test is at the end of the function - so there might not be enough outputs.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r7, 1 of 7 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1194)* status: 2 of 14 files reviewed, 6 unresolved discussions (waiting on @Alon-Ti, @orizi, and @spapinistarkware)

___
*[`tests/cairo_level_tests.rs` line 22 at r8](https://reviewable.io/reviews/starkware-libs/cairo/1194#-NIacehS-FnG-6Xpp-Ge:-NIacehS-FnG-6Xpp-Gf:b-40kwvj) ([raw file](https://github.com/starkware-libs/cairo/blob/5233c4c1d91df9d5ab2d40b02196195a215f4c90/tests/cairo_level_tests.rs#L22)):*
> ```XML
>         SierraCasmRunner::new((*sierra_program).clone(), false).expect("Failed setting up runner.");
>     let result =
>         runner.run_function(/* find first */ "", &[], &None).expect("Failed running the function.");
> ```

what does that mean?



_Code quote:_
```XML
* find first */
```

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1194#-:-NIaf5aw6DWtjwKmy-vD:bnfp4nl)* status: 2 of 14 files reviewed, all discussions resolved (waiting on @Alon-Ti and @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1194)* status: 2 of 14 files reviewed, all discussions resolved (waiting on @Alon-Ti, @ilyalesokhin-starkware, and @spapinistarkware)

___
*[`crates/runner/src/lib.rs` line 89 at r8](https://reviewable.io/reviews/starkware-libs/cairo/1194#-NIadJ9a2Pm0ArsE-C64:-NIafGzj-Sv5YCPcWwOM:bls5lqy) ([raw file](https://github.com/starkware-libs/cairo/blob/5233c4c1d91df9d5ab2d40b02196195a215f4c90/crates/runner/src/lib.rs#L89)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why?
</blockquote></details>

discussed f2f.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1194)* status: 1 of 14 files reviewed, all discussions resolved (waiting on @Alon-Ti and @spapinistarkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 8 files at r7, 4 of 7 files at r8, 1 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1194)* status: 7 of 14 files reviewed, all discussions resolved (waiting on @Alon-Ti and @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1194)* status: 7 of 14 files reviewed, all discussions resolved (waiting on @Alon-Ti, @ilyalesokhin-starkware, and @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1194)* status: 8 of 14 files reviewed, all discussions resolved (waiting on @Alon-Ti, @ilyalesokhin-starkware, and @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 8 files at r7, 2 of 7 files at r8, 1 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1194)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 8 files at r7, 1 of 7 files at r8, 1 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1194)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
