### PR TITLE
Added `zero_constructible` to type info.

### PR DESCRIPTION
**Pull request by orizi**
Useful for support of more types in dictionaries.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1937)

### CODE REVIEW

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 24 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1937)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/test.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1937#-NMwMIqI8agh0ZeJhPyj:-NMwMIqI8agh0ZeJhPyk:b-aockox) ([raw file](https://github.com/starkware-libs/cairo/blob/73b58405bc26a7c58cb572bfc68242aef54cac74/crates/cairo-lang-sierra/src/extensions/test.rs#L57)):*
> ```XML
>                 droppable: true,
>                 duplicatable: true,
>                 zero_constructible: true,
> ```

Not all are zero_constructible.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/enm.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1937#-NMwNAZD3p1W0KIDArNb:-NMwNAZD3p1W0KIDArNc:b-ortz5k) ([raw file](https://github.com/starkware-libs/cairo/blob/73b58405bc26a7c58cb572bfc68242aef54cac74/crates/cairo-lang-sierra/src/extensions/modules/enm.rs#L84)):*
> ```XML
>             duplicatable &= info.duplicatable;
>             droppable &= info.droppable;
>             zero_constructible &= info.zero_constructible;
> ```

Not sure about that, even if all variants are zero_constructible, the selector is zero only for the first one, so the behaviour can be confusing.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1937)* status: 23 of 24 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware, @liorgold2, and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/test.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1937#-NMwMIqI8agh0ZeJhPyj:-NMwRFjHAbNBT41RbHCM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/73b58405bc26a7c58cb572bfc68242aef54cac74/crates/cairo-lang-sierra/src/extensions/test.rs#L57)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Not all are zero_constructible.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/enm.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1937#-NMwNAZD3p1W0KIDArNb:-NMwQ38y4YB3sBSQb734:b-q8xt2e) ([raw file](https://github.com/starkware-libs/cairo/blob/73b58405bc26a7c58cb572bfc68242aef54cac74/crates/cairo-lang-sierra/src/extensions/modules/enm.rs#L84)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Not sure about that, even if all variants are zero_constructible, the selector is zero only for the first one, so the behaviour can be confusing.
</blockquote></details>

that is the idea - that is the meaning in this case for the zero construction.

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1937)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2 and @spapinistarkware)

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1937)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1937#-NMweyJR4Gsm8fQOllfw:-NMweyJR4Gsm8fQOllfx:b-9e7b9w) (no related file):*
Alternative suggestion:
At the high level: Require Default for `V`.
At the lower level: keep the default_value in the dict (along with start and end ptrs). squash reads it and uses for determining stuff.

In the future:
At the low level: be generic in the default value. OR maybe we should have both versions.

___

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1937)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/types.rs` line 160 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1937#-NMx53iH07_o7BHfplLm:-NMx53iH07_o7BHfplLn:b5ia2l5) ([raw file](https://github.com/starkware-libs/cairo/blob/3d6a3063220ad6cfb5e1eaceb787fdd81390600c/crates/cairo-lang-sierra/src/extensions/types.rs#L160)):*
> ```XML
>     /// Can the type be (trivially) duplicated.
>     pub duplicatable: bool,
>     /// Can the type be (trivially) parsed from zeroed out memory.
> ```

Add something like:



_Suggestion:_
```XML
    /// Can the type be (trivially) parsed from zeroed-out memory.
    /// In other words, does zero represents a valid (and constructible) value for the type.
    /// Note that some generic libfuncs may construct the zero value of this type if
    /// the value of this parameter is `true`.
    pub zero_constructible: bool,
```

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1937)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 24 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1937)* status: all files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/boxing.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1937#-NMx6UVfELwpZRBsXIkl:-NMx6UVg1c_S3JXeniAl:b-d7qino) ([raw file](https://github.com/starkware-libs/cairo/blob/3d6a3063220ad6cfb5e1eaceb787fdd81390600c/crates/cairo-lang-sierra/src/extensions/modules/boxing.rs#L27)):*
> ```XML
>             Err(SpecializationError::UnsupportedGenericArg)
>         } else {
>             Ok(TypeInfo { long_id, size: 1, zero_constructible: false, ..wrapped_info })
> ```

Let's not use this syntax here (and in other TypeInfo-related constructors). This is dangerous, exactly in this kind of PRs.



_Code quote:_
```XML
..wrapped_info
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/dict_felt_to.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1937#-NMx70VG9IxI7u4q6b6e:-NMx70VG9IxI7u4q6b6f:b-jdy22a) ([raw file](https://github.com/starkware-libs/cairo/blob/3d6a3063220ad6cfb5e1eaceb787fdd81390600c/crates/cairo-lang-sierra/src/extensions/modules/dict_felt_to.rs#L33)):*
> ```XML
>         // TODO(Gil): Check in the higher level compiler and raise proper diagnostic (when we'll
>         // have a 'where' equivalent).
>         if wrapped_info.size != 1
> ```

Convert to `!(... && ... && ...)` which better represents what you want to say here.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/dict_felt_to.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1937#-NMx7FHA1Ga_jESiQ5Si:-NMx7FHA1Ga_jESiQ5Sj:b-667e3d) ([raw file](https://github.com/starkware-libs/cairo/blob/3d6a3063220ad6cfb5e1eaceb787fdd81390600c/crates/cairo-lang-sierra/src/extensions/modules/dict_felt_to.rs#L36)):*
> ```XML
>             || !wrapped_info.storable
>             || !wrapped_info.droppable
>             || !wrapped_info.duplicatable
> ```

Not sure this (duplicatable) should be here, but this is for another PR.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1937)* status: all files reviewed, 7 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/enm.rs` line 84 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1937#-NMx7ht67RVu-M2Z4iyW:-NMx7ht67RVu-M2Z4iyX:b-31gz0c) ([raw file](https://github.com/starkware-libs/cairo/blob/3d6a3063220ad6cfb5e1eaceb787fdd81390600c/crates/cairo-lang-sierra/src/extensions/modules/enm.rs#L84)):*
> ```XML
>             duplicatable &= info.duplicatable;
>             droppable &= info.droppable;
>             zero_constructible &= info.zero_constructible;
> ```

This is wrong. Only the first variant is interesting.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/enm.rs` line 88 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1937#-NMx7rhf8iI9nxgS_3PB:-NMx7rhf8iI9nxgS_3PC:b-jpndzt) ([raw file](https://github.com/starkware-libs/cairo/blob/3d6a3063220ad6cfb5e1eaceb787fdd81390600c/crates/cairo-lang-sierra/src/extensions/modules/enm.rs#L88)):*
> ```XML
>             variant_max_size = cmp::max(variant_max_size, info.size);
>         }
>         // A 0 valued variant indicator must be supported.
> ```

Explain more. Mention that if there are more than 2 variants then the selector starts from 2 (IIRC) and thus 0 is not a valid value.



_Code quote:_
```XML
      // A 0 valued variant indicator must be supported.
```

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 14 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1937)* status: all files reviewed, 10 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/non_zero.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1937#-NMxOxoMDeBUa0p039tX:-NMxOxoMDeBUa0p039tY:b-rqu0co) ([raw file](https://github.com/starkware-libs/cairo/blob/3d6a3063220ad6cfb5e1eaceb787fdd81390600c/crates/cairo-lang-sierra/src/extensions/modules/non_zero.rs#L28)):*
> ```XML
>             Err(SpecializationError::UnsupportedGenericArg)
>         } else {
>             Ok(TypeInfo { long_id, zero_constructible: false, ..wrapped_info })
> ```

Same here. Avoid using `..wrapped_info`.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/nullable.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1937#-NMxP1IvBybnHU2creAz:-NMxP1IvBybnHU2creB-:b-rqu0co) ([raw file](https://github.com/starkware-libs/cairo/blob/3d6a3063220ad6cfb5e1eaceb787fdd81390600c/crates/cairo-lang-sierra/src/extensions/modules/nullable.rs#L35)):*
> ```XML
>             Err(SpecializationError::UnsupportedGenericArg)
>         } else {
>             Ok(TypeInfo { long_id, size: 1, zero_constructible: true, ..wrapped_info })
> ```

Same here. Avoid using `..wrapped_info`.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/squashed_dict_felt_to.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1937#-NMxPBex1AVOROIX9M_R:-NMxPBex1AVOROIX9M_S:banh8x7) ([raw file](https://github.com/starkware-libs/cairo/blob/3d6a3063220ad6cfb5e1eaceb787fdd81390600c/crates/cairo-lang-sierra/src/extensions/modules/squashed_dict_felt_to.rs#L20)):*
> ```XML
>         // TODO(Gil): Check in the higher level compiler and raise proper diagnostic (when we'll
>         // have a 'where' equivalent).
>         if wrapped_info.size != 1
> ```

Convert to `!( ... && ...)`.

**Pull request closed without merging**
