### PR TITLE
Handle cairofmt::skip in the formatter.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4387)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4387)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4387#-NiodE0cDLeByhzGXaW_:-NiodE0cDLeByhzGXaWa:b-lefas8) (no related file):*
Change target branch.

___

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 8 of 9 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4387#-:-Nj7tXwv-PXOF9wdwfi-:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/Cargo.toml` line 16 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4387#-Nj7scUZ6FxONzpyAjVZ:-Nj7scUZ6FxONzpyAjV_:bb7onj7) ([raw file](https://github.com/starkware-libs/cairo/blob/7a20ed1416d58e5f89650ba2ec6daf56f4db13cc/crates/cairo-lang-formatter/Cargo.toml#L16)):*
> ```TOML
> cairo-lang-syntax = { path = "../cairo-lang-syntax", version = "2.3.1" }
> cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.3.1" }
> cairo-lang-defs = { path = "../cairo-lang-defs", version = "2.3.1" }
> ```

sort

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4387)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4387)* status: all files reviewed, 2 unresolved discussions

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4387)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4387)* status: all files reviewed, 2 unresolved discussions

**Pull request merged**
