### PR TITLE
Implement array_at

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
Signed-off-by: Dori Medini <dori@<a href="starkware.co">starkware.co</a>>

---

**Stack**:
- #1098 ⬅
- #1096

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1098)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1098)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/sierra/src/extensions/modules/array.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1098#-NHski9EAfpMIIJJRuQn:-NHski9EAfpMIIJJRuQo:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/3dcfb6785d9c74908561c9a04e4ff3a356d884b7/crates/sierra/src/extensions/modules/array.rs#L125)):*
> ```XML
>         args: &[GenericArg],
>     ) -> Result<LibFuncSignature, SpecializationError> {
>         let ty = as_single_type(args)?;
> ```





_Suggestion:_
```XML
        let ty = as_single_type(args)?;
        if !context.get_type_info(ty.clone()).duplicatable {
            return Err(SpecializationError::UnsupportedGenericArg)
        }
```
___
*[`crates/sierra/src/extensions/modules/array.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1098#-NHslWlnA0UkonZG9f7Z:-NHslWlnA0UkonZG9f7_:b-7y1d44) ([raw file](https://github.com/starkware-libs/cairo/blob/3dcfb6785d9c74908561c9a04e4ff3a356d884b7/crates/sierra/src/extensions/modules/array.rs#L141)):*
> ```XML
>         };
>         let arr_output = OutputVarInfo {
>             ty: arr_type,
> ```

avoid cloning until further discussion (which means remove the derive;s as well)



_Code quote:_
```XML
        let rc_output = OutputVarInfo {
            ty: range_check_type,
            ref_info: OutputVarReferenceInfo::Deferred(DeferredOutputKind::AddConst {
                param_idx: 0,
            }),
        };
        let arr_output = OutputVarInfo {
            ty: arr_type,
            ref_info: OutputVarReferenceInfo::SameAsParam { param_idx: 1 },
        };
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1098)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @orizi)

___
*[`crates/sierra/src/extensions/modules/array.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1098#-NHski9EAfpMIIJJRuQn:-NHsrxZR6b9f6bgPABFG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0e12997b3fa3c45b247a520ce0e34464d48d7a0e/crates/sierra/src/extensions/modules/array.rs#L125)):*
> ```XML
>         args: &[GenericArg],
>     ) -> Result<LibFuncSignature, SpecializationError> {
>         let ty = as_single_type(args)?;
> ```

Done.
___
*[`crates/sierra/src/extensions/modules/array.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1098#-NHslWlnA0UkonZG9f7Z:-NHssDCwEFALhMDLXNyZ:bijjj2s) ([raw file](https://github.com/starkware-libs/cairo/blob/0e12997b3fa3c45b247a520ce0e34464d48d7a0e/crates/sierra/src/extensions/modules/array.rs#L141)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

avoid cloning until further discussion (which means remove the derive;s as well)
</blockquote></details>

Done, but this incurs code duplication... why not clone?

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1098)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1098#-NHstfPm4KlDd8n7I70e:-NHstfPm4KlDd8n7I70f:b-ouwr6j) (no related file):*
separate sierra-to-casm from generic sierra prs.

___
___
*[`crates/sierra/src/extensions/modules/array.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1098#-NHslWlnA0UkonZG9f7Z:-NHst-9q55VC5DzsfnfY:b-y5m35c) ([raw file](https://github.com/starkware-libs/cairo/blob/0e12997b3fa3c45b247a520ce0e34464d48d7a0e/crates/sierra/src/extensions/modules/array.rs#L141)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Done, but this incurs code duplication... why not clone?
</blockquote></details>

i want these to happen only if and when we add a "refs" section - i currently want us to be as explicit as possible per branch.
if we will have some concise way of describing a branch, all the cloning would confuse the ability to do so.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1098)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/sierra/src/extensions/modules/array.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1098#-NHslWlnA0UkonZG9f7Z:-NHsu7PO1YQxNZ7prFLT:b-krzsmn) ([raw file](https://github.com/starkware-libs/cairo/blob/0e12997b3fa3c45b247a520ce0e34464d48d7a0e/crates/sierra/src/extensions/modules/array.rs#L141)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i want these to happen only if and when we add a "refs" section - i currently want us to be as explicit as possible per branch.
if we will have some concise way of describing a branch, all the cloning would confuse the ability to do so.
</blockquote></details>

sababa

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1098)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/sierra/src/extensions/modules/array.rs` line 114 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1098#-NHstxML56W6JY854DCH:-NHstxMM55dL2C9snWUl:b2ni2nk) ([raw file](https://github.com/starkware-libs/cairo/blob/4c37437ff766f0d26615c8264954c4891e7bc44f/crates/sierra/src/extensions/modules/array.rs#L114)):*
> ```XML
> }
> 
> /// LibFunc for pushing a value into the end of an array.
> ```

fix



_Code quote:_
```XML
 LibFunc for pushing a value into the end of an array.
```
___
*[`crates/sierra_to_casm/src/invocations/array.rs` line 185 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1098#-NHsumhtCMpWioiIDS9M:-NHsumhtCMpWioiIDS9N:b-asaeaa) ([raw file](https://github.com/starkware-libs/cairo/blob/4c37437ff766f0d26615c8264954c4891e7bc44f/crates/sierra_to_casm/src/invocations/array.rs#L185)):*
> ```XML
> 
>             // Backpatch the JNZ target. It's the third instruction.
>             patch_jnz_to_end(&mut index_out_of_bounds_branch, 2);
> ```

it is not the third - it is the second.
hints are not instructions.



_Suggestion:_
```XML
            patch_jnz_to_end(&mut index_out_of_bounds_branch, 1);
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1098)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1098#-NHstfPm4KlDd8n7I70e:-NHsu_fk0p4lwvpgsOBj:b-qdiex4) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

separate sierra-to-casm from generic sierra prs.
</blockquote></details>

Not sure I follow; would you like me to implement `build_array_at` in a bottom PR, then add the `ArrayLibFunc::At` enum and string everything together in a speparate PR?

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1098)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @orizi)

___
*[`crates/sierra/src/extensions/modules/array.rs` line 114 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1098#-NHstxML56W6JY854DCH:-NHsvHJU0etN0CCltFVc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4c37437ff766f0d26615c8264954c4891e7bc44f/crates/sierra/src/extensions/modules/array.rs#L114)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix
</blockquote></details>

Done.
___
*[`crates/sierra_to_casm/src/invocations/array.rs` line 185 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1098#-NHsumhtCMpWioiIDS9M:-NHsvPhh6yTIkTLu21DB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4c37437ff766f0d26615c8264954c4891e7bc44f/crates/sierra_to_casm/src/invocations/array.rs#L185)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it is not the third - it is the second.
hints are not instructions.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1098)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1098#-NHstfPm4KlDd8n7I70e:-NHt8eBs8E6S4_eQSALV:b-vi7llf) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Not sure I follow; would you like me to implement `build_array_at` in a bottom PR, then add the `ArrayLibFunc::At` enum and string everything together in a speparate PR?
</blockquote></details>

First add sierra structure - than add sierra to casm in another pr

___

**Comment by dorimedini-starkware** [comment]
Closing pull request: commit has gone away

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1098)* status: 2 of 5 files reviewed, 5 unresolved discussions

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1098#-NHstfPm4KlDd8n7I70e:-NHtFW4S8SjQcDT7IP9N:b4qf680) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

First add sierra structure - than add sierra to casm in another pr
</blockquote></details>

Done (see https://reviewable.io/reviews/starkware-libs/cairo/1104)

___

**Pull request closed without merging**
