### PR TITLE
Refactor statement_can_be_optimized_out.

### PR DESCRIPTION
**Pull request by liorgold2**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6328)

### CODE REVIEW

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6328#-:-O5lZy3TDWJJJaQ8qVRz:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6328)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6328#-O5lhQRk1QyLeAxAmmno:-O5lhQRk1QyLeAxAmmnp:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/71ee0854ab681df1e5f446446337d396b7a031ec/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L105)):*
> ```XML
>     let Some(ref mut candidate) = &mut info.candidate else {
>         return None;
>     };
> ```

.



_Suggestion:_
```XML
    let mut candidate = info.candidate.as_mut()?;
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6328)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6328#-O5lhQRk1QyLeAxAmmno:-O5mb15eBTsAvBb_DMJG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/71ee0854ab681df1e5f446446337d396b7a031ec/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L105)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6328#-:-O5mbgkNDd8eAufiByjn:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6328)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 109 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6328#-O5mvdt5Efy2wWcc-IRy:-O5mvdt69d9whADyNtTO:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/69ef8e542f28e5db1448f5dffd6008459c6b6b76/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L109)):*
> ```XML
>         .match_arms
>         .iter()
>         .find_position(|arm| arm.arm_selector == MatchArmSelector::VariantId((*variant).clone()))
> ```





_Suggestion:_
```XML
        .find_position(|arm| matches!(arm.arm_selector, MatchArmSelector::VariantId(v) if v == *variant))
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6328#-:-O5n6Q89-szmRd6QlRlf:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
