### PR TITLE
Allow deduction for variable from other inference_ids.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5321)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 617 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5321#-Ntkiqc76vvUP15kvpWq:-Ntkiqc8EfenIEmlODfk:bmq11qm) ([raw file](https://github.com/starkware-libs/cairo/blob/6e3cd4c66bb8db5ea7545a2c29eea3b49cd71593/crates/cairo-lang-semantic/src/expr/inference.rs#L617)):*
> ```XML
>                 ty1: ty,
>             });
>         }
> ```

It seems that removing this improves the error message.



_Code quote:_
```XML
        if var.inference_id != self.inference_id {
            return Err(InferenceError::TypeKindMismatch {
                ty0: self.db.intern_type(TypeLongId::Var(var)),
                ty1: ty,
            });
        }
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 617 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5321#-Ntkiqc76vvUP15kvpWq:-Ntkiu4yEARPtvbdzsB1:bwushhb) ([raw file](https://github.com/starkware-libs/cairo/blob/6e3cd4c66bb8db5ea7545a2c29eea3b49cd71593/crates/cairo-lang-semantic/src/expr/inference.rs#L617)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

It seems that removing this improves the error message.
</blockquote></details>

but it might be safer to rewrite the inference_id of the return type
from:
LookupItemDeclaration
to 
LookupItemDefinition

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5321)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 617 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5321#-Ntkiqc76vvUP15kvpWq:-NtlEWbl0Pl8o7aj3Z3E:beqjgv5) ([raw file](https://github.com/starkware-libs/cairo/blob/6e3cd4c66bb8db5ea7545a2c29eea3b49cd71593/crates/cairo-lang-semantic/src/expr/inference.rs#L617)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

but it might be safer to rewrite the inference_id of the return type
from:
LookupItemDeclaration
to 
LookupItemDefinition
</blockquote></details>

I think instead it should just be considered as a `missing` type - would cause no diagnostics - but won't cause possible weird interaction between different lookup contexts.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5321)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Pull request closed without merging**
