### PR TITLE
Added support for secp256r1 in Cairo

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3269)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3269)* status: 2 of 21 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/starknet/secp256.cairo` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3269#-NWgx8ezC-tMuz7ds-2l:-NWgx8ezC-tMuz7ds-2m:bahyr7t) ([raw file](https://github.com/starkware-libs/cairo/blob/982a6ba955b025c59e21c03700ee64540a3150b5/corelib/src/starknet/secp256.cairo#L12)):*
> ```Cairo
> 
> #[derive(Copy, Drop)]
> extern type Secp256EcPoint;
> ```

re-separate to k1 and r1.



_Code quote:_
```Cairo
#[derive(Copy, Drop)]
extern type Secp256EcPoint;
```
___
*[`corelib/src/starknet/secp256.cairo` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3269#-NWgwNAMDXfwdGrzJl0J:-NWgwNANCvd5UhGZFgwN:b3ci8mq) ([raw file](https://github.com/starkware-libs/cairo/blob/982a6ba955b025c59e21c03700ee64540a3150b5/corelib/src/starknet/secp256.cairo#L14)):*
> ```Cairo
> extern type Secp256EcPoint;
> 
> trait Secp256 {
> ```

and probably filename as well - just as to not make it look too usable for users.



_Suggestion:_
```Cairo
trait Secp256Generic
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3269)* status: 2 of 23 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/starknet/secp256.cairo` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3269#-NWgx8ezC-tMuz7ds-2l:-NWqetmaAqEuU9OO9syX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/982a6ba955b025c59e21c03700ee64540a3150b5/corelib/src/starknet/secp256.cairo#L12)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

re-separate to k1 and r1.
</blockquote></details>

Done.
___
*[`corelib/src/starknet/secp256.cairo` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3269#-NWgwNAMDXfwdGrzJl0J:-NWhB5tN82oSZqTyc08q:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/982a6ba955b025c59e21c03700ee64540a3150b5/corelib/src/starknet/secp256.cairo#L14)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

and probably filename as well - just as to not make it look too usable for users.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 21 files at r1, 11 of 16 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3269)* status: 18 of 23 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`corelib/src/starknet/secp256k1.cairo` line 51 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3269#-NWqkhre9t6pQfdzVmrR:-NWqkhre9t6pQfdzVmrS:b-n74utd) ([raw file](https://github.com/starkware-libs/cairo/blob/fd426072091f25dc5ff6c52254befed57fc0656b/corelib/src/starknet/secp256k1.cairo#L51)):*
> ```Cairo
>     ) -> Option<Secp256k1EcPoint> {
>         super::secp256_trait::recover_public_key::<Secp256k1EcPoint>(msg_hash, r, s, y_parity)
>     }
> ```

i think these should just be out of the trait and the impl (as using the function just through the module is much more neat)



_Code quote:_
```Cairo
    fn recover_public_key(
        msg_hash: u256, r: u256, s: u256, y_parity: bool
    ) -> Option<Secp256k1EcPoint> {
        super::secp256_trait::recover_public_key::<Secp256k1EcPoint>(msg_hash, r, s, y_parity)
    }
```

**Comment by yuvalsw** [comment]
*[`corelib/src/starknet/secp256k1.cairo` line 51 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3269#-NWqkhre9t6pQfdzVmrR:-NWrG6Hw26_2tF8boJ3P:brp5ouq) ([raw file](https://github.com/starkware-libs/cairo/blob/fd426072091f25dc5ff6c52254befed57fc0656b/corelib/src/starknet/secp256k1.cairo#L51)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i think these should just be out of the trait and the impl (as using the function just through the module is much more neat)
</blockquote></details>

Why is it more neat?
Why specifically this?
This is part of the interface for secp, why not in the trait and impl?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3269)* status: 18 of 23 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`corelib/src/starknet/secp256k1.cairo` line 51 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3269#-NWqkhre9t6pQfdzVmrR:-NX3gvkY7_9Pj2OSWDo5:bn25nsj) ([raw file](https://github.com/starkware-libs/cairo/blob/fd426072091f25dc5ff6c52254befed57fc0656b/corelib/src/starknet/secp256k1.cairo#L51)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Why is it more neat?
Why specifically this?
This is part of the interface for secp, why not in the trait and impl?
</blockquote></details>

Not just this one, all the outer ones, as the aim of this trait was to more easily implement the generics.
The usage itself from the user side would still be more fitting if it is just a normal module and not an impl.
Impl would have made more sense to me if some type would have carried all the secp information, and than a trait and impl would easily allow users to access it, which is not the case here.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3269)* status: 18 of 23 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/starknet/secp256k1.cairo` line 51 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3269#-NWqkhre9t6pQfdzVmrR:-NX4JZF9EN4IckyEUHAC:b-j3q8kj) ([raw file](https://github.com/starkware-libs/cairo/blob/fd426072091f25dc5ff6c52254befed57fc0656b/corelib/src/starknet/secp256k1.cairo#L51)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Not just this one, all the outer ones, as the aim of this trait was to more easily implement the generics.
The usage itself from the user side would still be more fitting if it is just a normal module and not an impl.
Impl would have made more sense to me if some type would have carried all the secp information, and than a trait and impl would easily allow users to access it, which is not the case here.
</blockquote></details>

I think the interface should be consistent.
With your suggestion, a test would now look like:
```
    let public_key = secp256_trait::recover_public_key::<Secp256k1EcPoint>(msg_hash, r, s, y_parity).unwrap();
    let (x, y) = Secp256k1Impl::secp256_ec_get_coordinates_syscall(public_key).unwrap_syscall();
```

(adding to the inconsistency, with it now being called secp256_trait, it's even weirder to have function in it as a module)

I prefer leaving it as is, let me know if you strongly object.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3269)* status: 18 of 23 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`corelib/src/starknet/secp256k1.cairo` line 51 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3269#-NWqkhre9t6pQfdzVmrR:-NX4QaFg1U6UL8cdEKkW:b-tglclm) ([raw file](https://github.com/starkware-libs/cairo/blob/fd426072091f25dc5ff6c52254befed57fc0656b/corelib/src/starknet/secp256k1.cairo#L51)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I think the interface should be consistent.
With your suggestion, a test would now look like:
```
    let public_key = secp256_trait::recover_public_key::<Secp256k1EcPoint>(msg_hash, r, s, y_parity).unwrap();
    let (x, y) = Secp256k1Impl::secp256_ec_get_coordinates_syscall(public_key).unwrap_syscall();
```

(adding to the inconsistency, with it now being called secp256_trait, it's even weirder to have function in it as a module)

I prefer leaving it as is, let me know if you strongly object.
</blockquote></details>

What I want is to simply leave the original interface for the user as is, and use the trait just to reduce the code duplication between r1 and k1

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3269)* status: 18 of 23 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/starknet/secp256k1.cairo` line 51 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3269#-NWqkhre9t6pQfdzVmrR:-NX5ku9KEJrVr91J15g9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fd426072091f25dc5ff6c52254befed57fc0656b/corelib/src/starknet/secp256k1.cairo#L51)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

What I want is to simply leave the original interface for the user as is, and use the trait just to reduce the code duplication between r1 and k1
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 5 files at r4, 5 of 5 files at r5, 11 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3269#-:-NX5vIFV5wV21-nsDm6H:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 1 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3269)* status: 24 of 25 files reviewed, all discussions resolved (waiting on @orizi)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 1 of 11 files at r6, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3269)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3269)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
