### PR TITLE
Fix possibly missed optimization.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6660)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @liorgold2)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 330 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6660#-OBfHSL_A0AfBqaWkx_W:-OBfHSL_A0AfBqaWkx_X:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/abbd7c8efcf58ac8b72f611f0c92b4d96ddecccd/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L330)):*
> ```XML
>             candidate.match_variable = var_usage.var_id;
>             handled_remmapings = 1;
>         };
> ```





_Suggestion:_
```XML
        if remapping.is_empty() { <----- Doesn't this already do that?
            // Do nothing. Keep the candidate if exists.
            return;
        }

        info.demand.apply_remapping(
            &mut EmptyDemandReporter {},
            remapping.iter().map(|(dst, src)| (dst, (&src.var_id, ()))),
        );

        let Some(ref mut candidate) = &mut info.candidate else {
            return;
        };

        let orig_match_variable = candidate.match_variable;
        let mut handled_remmapings = 0;
        if let Some(var_usage) = remapping.get(&candidate.match_variable) {
            candidate.match_variable = var_usage.var_id;
            handled_remmapings = 1;
        };
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 330 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6660#-OBfHSL_A0AfBqaWkx_W:-OBt-Ebt25Kl2teWflMq:brt4n2x) ([raw file](https://github.com/starkware-libs/cairo/blob/abbd7c8efcf58ac8b72f611f0c92b4d96ddecccd/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L330)):*
> ```XML
>             candidate.match_variable = var_usage.var_id;
>             handled_remmapings = 1;
>         };
> ```

No, the fix is for the case where remapping.len() ==1, but the match variable is not remapped.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6660)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @liorgold2)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 330 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6660#-OBfHSL_A0AfBqaWkx_W:-OBtKBB179ti8WjT78s8:b-pf95sw) ([raw file](https://github.com/starkware-libs/cairo/blob/abbd7c8efcf58ac8b72f611f0c92b4d96ddecccd/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L330)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

No, the fix is for the case where remapping.len() ==1, but the match variable is not remapped.
</blockquote></details>

but this is exactly the deleted line:
```
        let Some(var_usage) = remapping.get(&candidate.match_variable) else {
            // Revoke the candidate.
            info.candidate = None;
            return;
        };
```
isn't it?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 330 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6660#-OBfHSL_A0AfBqaWkx_W:-OBtV8HTBmIR-aRvxd5k:bckzo8d) ([raw file](https://github.com/starkware-libs/cairo/blob/abbd7c8efcf58ac8b72f611f0c92b4d96ddecccd/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L330)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

but this is exactly the deleted line:
```
        let Some(var_usage) = remapping.get(&candidate.match_variable) else {
            // Revoke the candidate.
            info.candidate = None;
            return;
        };
```
isn't it?
</blockquote></details>

Before the fix, the candidate is always revoked in that case.
after the fix it is not revoked unless there are other issues.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6660)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @liorgold2)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 330 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6660#-OBfHSL_A0AfBqaWkx_W:-OBtlAGFBWuxM2D7aRef:bmdp76d) ([raw file](https://github.com/starkware-libs/cairo/blob/abbd7c8efcf58ac8b72f611f0c92b4d96ddecccd/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L330)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Before the fix, the candidate is always revoked in that case.
after the fix it is not revoked unless there are other issues.
</blockquote></details>

can you think of an example this actually happens?
___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 334 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6660#-OBtm-h0Dy8iTCyGOQPl:-OBtm-h0Dy8iTCyGOQPm:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/d296364e19e651272e35c7b1604cd77ab03788a9/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L334)):*
> ```XML
> 
>         if remapping.len() > handled_remappings {
>             // here, we have remappings for variables other than the match variable.
> ```





_Suggestion:_
```XML
        let mut has_unhandled_remappings = true;
        if let Some(var_usage) = remapping.get(&candidate.match_variable) {
            candidate.match_variable = var_usage.var_id;
            has_unhandled_remappings = remappings.len() > 1;
        };

        if has_unhandled_remappings {
            // here, we have remappings for variables other than the match variable.
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6660)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @liorgold2)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 333 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6660#-OBtmWL_8FVaKqLQrcpK:-OBtmWLaAsG9JOirrr-y:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d296364e19e651272e35c7b1604cd77ab03788a9/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L333)):*
> ```XML
>         };
> 
>         if remapping.len() > handled_remappings {
> ```





_Suggestion:_
```XML
        let has_handled_remappings = 
        if let Some(var_usage) = remapping.get(&candidate.match_variable) {
            candidate.match_variable = var_usage.var_id;
            remappings.len() > 1
        } else { true };

        if has_handled_remappings {
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6660)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 330 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6660#-OBfHSL_A0AfBqaWkx_W:-OBtqiH09gt8zmduB5h4:b32wsm) ([raw file](https://github.com/starkware-libs/cairo/blob/abbd7c8efcf58ac8b72f611f0c92b4d96ddecccd/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L330)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can you think of an example this actually happens?
</blockquote></details>

no
___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 333 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6660#-OBtmWL_8FVaKqLQrcpK:-OBtynJMDZxCrZyK0q3g:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d296364e19e651272e35c7b1604cd77ab03788a9/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L333)):*
> ```XML
>         };
> 
>         if remapping.len() > handled_remappings {
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6660)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @liorgold2)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6660#-OBu0wd29r9S5U-tbBTQ:-OBu0wd29r9S5U-tbBTR:b-gfli0d) (no related file):*
note you probably need to rebase and update your rust formatter.
___
*[`crates/cairo-lang-lowering/src/optimizations/test_data/match_optimization` line 1163 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6660#-OBu17MI8WttQjzqnUSo:-OBu17MI8WttQjzqnUSp:bkpc8mn) ([raw file](https://github.com/starkware-libs/cairo/blob/2c1eb9d10978d9886553a3914f83df7b5d21bdc7/crates/cairo-lang-lowering/src/optimizations/test_data/match_optimization#L1163)):*
> ```
> //! > ==========================================================================
> 
> //! > Remapping where input var is not renamed.
> ```

what is the test case?



_Code quote:_
```
//! > Remapping where input var is not renamed.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/test_data/match_optimization` line 1163 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6660#-OBu17MI8WttQjzqnUSo:-OBu3gtUC5Kpu8iX-R9N:bv4so2d) ([raw file](https://github.com/starkware-libs/cairo/blob/2c1eb9d10978d9886553a3914f83df7b5d21bdc7/crates/cairo-lang-lowering/src/optimizations/test_data/match_optimization#L1163)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

what is the test case?
</blockquote></details>

I tried to reproduce the issue but couldn't

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 330 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6660#-OBfHSL_A0AfBqaWkx_W:-OBu3kuB8-by23z9RElu:bbg89qm) ([raw file](https://github.com/starkware-libs/cairo/blob/abbd7c8efcf58ac8b72f611f0c92b4d96ddecccd/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L330)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

no
</blockquote></details>

I guess it can't happen.

but the origianl code still fills strange to me.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6660)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @liorgold2)

___
*[`crates/cairo-lang-lowering/src/optimizations/test_data/match_optimization` line 1177 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6660#-OBu4Vwn6Yz-ppzDZrnx:-OBu4Vwn6Yz-ppzDZrny:b-p2b0yd) ([raw file](https://github.com/starkware-libs/cairo/blob/2c1eb9d10978d9886553a3914f83df7b5d21bdc7/crates/cairo-lang-lowering/src/optimizations/test_data/match_optimization#L1177)):*
> ```
>     if v {
>         a = 2;
>     }
> ```

maybe?
so you'd have a longer merge with possibly more vars?



_Suggestion:_
```
    if v {
        a = 1;
        if v {
            a = 2;
        }
    }
    let v = true;
    if v {
        a = 2;
    }
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6660)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @liorgold2)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 330 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6660#-OBfHSL_A0AfBqaWkx_W:-OBu4gvQE8OS5IxiJghj:b-mudyqv) ([raw file](https://github.com/starkware-libs/cairo/blob/abbd7c8efcf58ac8b72f611f0c92b4d96ddecccd/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L330)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I guess it can't happen.

but the origianl code still fills strange to me.
</blockquote></details>

i can't conceptualize it right now - so i'm really not sure.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6660)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/test_data/match_optimization` line 1177 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6660#-OBu4Vwn6Yz-ppzDZrnx:-OBuBePP2Mc64WUwu-_n:bhdpwis) ([raw file](https://github.com/starkware-libs/cairo/blob/2c1eb9d10978d9886553a3914f83df7b5d21bdc7/crates/cairo-lang-lowering/src/optimizations/test_data/match_optimization#L1177)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe?
so you'd have a longer merge with possibly more vars?
</blockquote></details>

the merge will always happen before the assignment to v, so I can't trillger the issue.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6660#-:-OBuGaFY7MWkxGvzv_WS:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
