### PR TITLE
Faster e2e tests

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3860)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3831** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3831" target="_blank">Graphite</a> 
    * **PR #3860** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3860" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/3860?utm_source=stack-comment).

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3860#-:-NbJA7U25hpQTgTpEXMP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 55 of 68 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3860)* status: 64 of 77 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/tests` line 74 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3860#-NbJLADG6Bv4t1j4QHQG:-NbJLADH00_jQGp93PfU:bb7r2f0) ([raw file](https://github.com/starkware-libs/cairo/blob/c9de8c7175258fc27b4d721b28c68da93b83bbff/crates/cairo-lang-semantic/src/diagnostic_test_data/tests#L74)):*
> ```
> error: Function not found.
>  --> lib.cairo:7:9
>   test::foo();
> ```

why?



_Code quote:_
```
error: Function not found.
 --> lib.cairo:7:9
  test::foo();
```

**Review by orizi — COMMENTED** [review]
> Reviewed 13 of 68 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3860)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Pull request merged**
