### PR TITLE
Fix Circuit type info.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5747)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5747#-:-Nzw0TTX-20JeTpKoZyD:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5747)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet-classes/src/contract_segmentation_test_data/find_segment` line 371 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5747#-NzwC0pt3d5xIjYmT5U5:-NzwC0pt3d5xIjYmT5U6:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/fb06be1b2090c950cb94058f463562384d1e625f/crates/cairo-lang-starknet-classes/src/contract_segmentation_test_data/find_segment#L371)):*
> ```
> 
> //! > cairo_program
> Casm compilation failed.
> ```

?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5747)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-starknet-classes/src/contract_segmentation_test_data/find_segment` line 371 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5747#-NzwC0pt3d5xIjYmT5U5:-NzwG0ca83Dc9m8Wl519:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fb06be1b2090c950cb94058f463562384d1e625f/crates/cairo-lang-starknet-classes/src/contract_segmentation_test_data/find_segment#L371)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5747)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5747)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
