### PR TITLE
Add notification on corelib mismatch

### LINKED ISSUE #6174: Deal with panics on `core` crate mismatch
# Bug Report

**Cairo version:** `2.7.0`

**Current behavior:**

Users happen to get into situation when LS is fed with `core` crate coming from different compiler release. This results in all analysis actions to panic because the compiler expects existence and particular implementation of various language items in `core`, that is fulfilled by the _exactly_ same `core` version, but usually is not happening in past and future releases.

**Expected behavior:**

Although panicking (at the place that does it) makes sense implementation-wise, we have to think how and implement a feature that will tell users what is the problem and how they could fix it. The exact UX is not decided on right now.

One idea that is the most pleasing right now is to implement a way of checking `core` and LS' compiler compatibility. Perhaps by comparing versions of both?

**Steps to reproduce:**

We know of several scenarios that trigger the invalid state, but there are probably more. Users are almost always unable to tell what they did.

1. The easiest unrealistic reproduction:
    1. Open some regular Cairo codebase in VSCode.
    2. Put the following in `.vscode/settings.json` (adjust versions to whatever you have installed, but they must be different):

        ```json
        {
            "cairo1.languageServerPath": "${userHome}/.asdf/installs/scarb/2.7.0/bin/scarb-cairo-language-server",
            "cairo1.scarbPath": "${userHome}/.asdf/installs/scarb/2.6.4/bin/scarb",
            "cairo1.preferScarbLanguageServer": false
        }
        ```
    3. You can also do this with manually built the LS.
2. A possible scenario that happens when users are reporting when new release is happening, and then they say that the issue solved magically:
    1. Use `asdf local scarb 2.6.4` to set Scarb locally in some Cairo codebase.
    2. Launch VSCode, open some `*.cairo` file and thus let CairoLS load and analyse the project.
    3. Open terminal panel.
    4. Run `asdf local scarb 2.7.0`.
    5. Open another `*.cairo` file and thus let CairoLS call `detect_crate_for` again and query `scarb metadata` from a **new** Scarb installation. This should replace the `core` crate that is already loaded in analyzer database (2.6.4) with new one that new Scarb provides (2.7.0).
    6. **Note**: This scenario interferes with #6124 that drops `detect_crate_for`. Perhaps we should resolve this case specifically in this feature implementation?
    7. **Note**: Reloading VSCode will fix the problem because it will restart with newer CairoLS.

**Related code:**

Mostly this function panics, but in general, this applies to this entire file: https://github.com/starkware-libs/cairo/blob/106bb50f54e615ac7339e9ca1cb18743d0114579/crates/cairo-lang-semantic/src/corelib.rs#L692-L728

### PR DESCRIPTION
**Pull request by piotmag769**
Closes #6174

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6213)

### CODE REVIEW

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6213)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6213#-:-O4GOoyp9kJ5Y4f-2f2c:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

**Review by Draggu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6213)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @Arcticae, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 605 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6213#-O4PGaO65acozS3mGfW-:-O4PGaO65acozS3mGfW0:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/1e67874aed5d6e7f4782c3fc2253bd84979499ec/crates/cairo-lang-language-server/src/lib.rs#L605)):*
> ```XML
>                 let corelib_validation = validate_corelib(db);
>                 if let Err(result) = corelib_validation {
>                     let notifier = Notifier::new(&self.client);
> ```


___
*[`crates/cairo-lang-language-server/src/lib.rs` line 608 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6213#-O4PFxHw0sa-SSBIb_pb:-O4PFxHw0sa-SSBIb_pc:bumdvd7) ([raw file](https://github.com/starkware-libs/cairo/blob/1e67874aed5d6e7f4782c3fc2253bd84979499ec/crates/cairo-lang-language-server/src/lib.rs#L608)):*
> ```XML
>                     spawn_blocking(move || {
>                         notifier.send_notification::<CorelibVersionMismatch>(result.to_string());
>                     });
> ```

`Notifier` is wrapper that makes it synchronous, if you want make it async just use client directly



_Suggestion:_
```XML
                    self.client.send_notification::<CorelibVersionMismatch>(result.to_string()).await;
```
___
*[`vscode-cairo/src/cairols.ts` line 86 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6213#-O4PGM40DpkbmbgYPwTq:-O4PGM40DpkbmbgYPwTr:b-imgx6q) ([raw file](https://github.com/starkware-libs/cairo/blob/1e67874aed5d6e7f4782c3fc2253bd84979499ec/vscode-cairo/src/cairols.ts#L86)):*
> ```XML
>   });
> 
>   client.onNotification(new NotificationType<string>("corelib/version-mismatch"), (params) => {
> ```

Make it clear that payload of this notification is error message from server



_Suggestion:_
```XML
errMessage
```
___
*[`vscode-cairo/src/cairols.ts` line 89 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6213#-O4PGOwW63HfhzeosZQ4:-O4PGOwW63HfhzeosZQ5:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/1e67874aed5d6e7f4782c3fc2253bd84979499ec/vscode-cairo/src/cairols.ts#L89)):*
> ```XML
>     const errorMessage =
>       "Corelib version mismatch. If you are using Scarb try reopening the project to fix this error. Resort to `scarb cache clean` if it doesn't help. ERROR: " +
>       params;
> ```





_Suggestion:_
```XML
errMessage
```

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6213)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @mkaput, and @piotmag769)

**Review by mkaput — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6213)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 608 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6213#-O4PFxHw0sa-SSBIb_pb:-O4dmu9-8Z20uU4jPGZu:bium2wx) ([raw file](https://github.com/starkware-libs/cairo/blob/1e67874aed5d6e7f4782c3fc2253bd84979499ec/crates/cairo-lang-language-server/src/lib.rs#L608)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

`Notifier` is wrapper that makes it synchronous, if you want make it async just use client directly
</blockquote></details>

Not exactly. I want `Notifier` to be **the** object for sending notifications long term (which is separate from client to reduce scope). It's sync because we are aiming to refactor our entire codebase to sync world (as part of `lsp-server` migration).

But your code suggestion is totally valid here!

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6213)* status: all files reviewed, 9 unresolved discussions (waiting on @Arcticae, @Draggu, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 604 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6213#-O4dnT18832SpjQFxEPV:-O4dnT18832SpjQFxEPW:b2ni8l0) ([raw file](https://github.com/starkware-libs/cairo/blob/1e67874aed5d6e7f4782c3fc2253bd84979499ec/crates/cairo-lang-language-server/src/lib.rs#L604)):*
> ```XML
> 
>                 let corelib_validation = validate_corelib(db);
>                 if let Err(result) = corelib_validation {
> ```

nit



_Suggestion:_
```XML
                if let Err(result) = validate_corelib(db) {
```
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 662 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6213#-O4docvyB_EOpDY9ECQJ:-O4docvyB_EOpDY9ECQK:bqvhdr3) ([raw file](https://github.com/starkware-libs/cairo/blob/1e67874aed5d6e7f4782c3fc2253bd84979499ec/crates/cairo-lang-language-server/src/lib.rs#L662)):*
> ```XML
> 
> #[derive(Debug)]
> struct CorelibVersionMismatch {}
> ```

I'm thinking if we shouldn't move all our LSP extensions to `crates/cairo-lang-language-server/src/lsp/ext.rs`, so that they all will be discoverable.

Forget about Scarb notifications - they are to be redone.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 666 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6213#-O4doMEi-R_4PuNitpW0:-O4doMEi-R_4PuNitpW1:b-kp61ie) ([raw file](https://github.com/starkware-libs/cairo/blob/1e67874aed5d6e7f4782c3fc2253bd84979499ec/crates/cairo-lang-language-server/src/lib.rs#L666)):*
> ```XML
> impl Notification for CorelibVersionMismatch {
>     type Params = String;
>     const METHOD: &'static str = "corelib/version-mismatch";
> ```

I noticed LSP extensions tend to use the part before `/` for namespacing, so let's establish that all our custom stuff is `cairo/`. (RA has `rust-analyzer/`)

Forget about Scarb notifications - they are to be redone.



_Suggestion:_
```XML
cairo/corelib-version-mismatch
```
___
*[`vscode-cairo/src/cairols.ts` line 88 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6213#-O4dp6J1Es07eUdbYGY2:-O4dp6J1Es07eUdbYGY3:b-l58h0j) ([raw file](https://github.com/starkware-libs/cairo/blob/1e67874aed5d6e7f4782c3fc2253bd84979499ec/vscode-cairo/src/cairols.ts#L88)):*
> ```XML
>   client.onNotification(new NotificationType<string>("corelib/version-mismatch"), (params) => {
>     const errorMessage =
>       "Corelib version mismatch. If you are using Scarb try reopening the project to fix this error. Resort to `scarb cache clean` if it doesn't help. ERROR: " +
> ```

Avoid term `corelib` in user-facing communication. It's a "`core` crate".
___
*[`vscode-cairo/src/cairols.ts` line 88 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6213#-O4dpGvNBDYiTT3G8GYu:-O4dpGvNBDYiTT3G8GYv:bjcyn2i) ([raw file](https://github.com/starkware-libs/cairo/blob/1e67874aed5d6e7f4782c3fc2253bd84979499ec/vscode-cairo/src/cairols.ts#L88)):*
> ```XML
>   client.onNotification(new NotificationType<string>("corelib/version-mismatch"), (params) => {
>     const errorMessage =
>       "Corelib version mismatch. If you are using Scarb try reopening the project to fix this error. Resort to `scarb cache clean` if it doesn't help. ERROR: " +
> ```

* What does this message look like in real life?
* Can you post a screenshot?
* From bare looking at this, this looks to be ugly. Can it be markdown?
* Can you split this into paragraphs: User digestible gist of the problem, Technical full reason, Troubleshooting steps?

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6213)* status: all files reviewed, 9 unresolved discussions (waiting on @Arcticae, @Draggu, and @piotmag769)

**Review by mkaput — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6213)* status: all files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, and @piotmag769)

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6213)* status: all files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, and @mkaput)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 604 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6213#-O4dnT18832SpjQFxEPV:-O4iz0Me4VY-kZh9WmRS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1e67874aed5d6e7f4782c3fc2253bd84979499ec/crates/cairo-lang-language-server/src/lib.rs#L604)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

nit
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 605 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6213#-O4PGaO65acozS3mGfW-:-O4iyvK-8Uhmo8Y993ZR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1e67874aed5d6e7f4782c3fc2253bd84979499ec/crates/cairo-lang-language-server/src/lib.rs#L605)):*
> ```XML
>                 let corelib_validation = validate_corelib(db);
>                 if let Err(result) = corelib_validation {
>                     let notifier = Notifier::new(&self.client);
> ```

Done.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 608 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6213#-O4PFxHw0sa-SSBIb_pb:-O4iyuf5BQZCfl7nLZFx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1e67874aed5d6e7f4782c3fc2253bd84979499ec/crates/cairo-lang-language-server/src/lib.rs#L608)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Not exactly. I want `Notifier` to be **the** object for sending notifications long term (which is separate from client to reduce scope). It's sync because we are aiming to refactor our entire codebase to sync world (as part of `lsp-server` migration).

But your code suggestion is totally valid here!
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 662 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6213#-O4docvyB_EOpDY9ECQJ:-O4ix_KI82pqHYfxyoK7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1e67874aed5d6e7f4782c3fc2253bd84979499ec/crates/cairo-lang-language-server/src/lib.rs#L662)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I'm thinking if we shouldn't move all our LSP extensions to `crates/cairo-lang-language-server/src/lsp/ext.rs`, so that they all will be discoverable.

Forget about Scarb notifications - they are to be redone.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 666 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6213#-O4doMEi-R_4PuNitpW0:-O4ixfEh3vURt7mp4lKj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1e67874aed5d6e7f4782c3fc2253bd84979499ec/crates/cairo-lang-language-server/src/lib.rs#L666)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I noticed LSP extensions tend to use the part before `/` for namespacing, so let's establish that all our custom stuff is `cairo/`. (RA has `rust-analyzer/`)

Forget about Scarb notifications - they are to be redone.
</blockquote></details>

Done.
___
*[`vscode-cairo/src/cairols.ts` line 86 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6213#-O4PGM40DpkbmbgYPwTq:-O4iz8ra9fUrDP6GOn8Q:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1e67874aed5d6e7f4782c3fc2253bd84979499ec/vscode-cairo/src/cairols.ts#L86)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

Make it clear that payload of this notification is error message from server
</blockquote></details>

Done.
___
*[`vscode-cairo/src/cairols.ts` line 88 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6213#-O4dp6J1Es07eUdbYGY2:-O4izA-mBL0ddFMciPsc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1e67874aed5d6e7f4782c3fc2253bd84979499ec/vscode-cairo/src/cairols.ts#L88)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Avoid term `corelib` in user-facing communication. It's a "`core` crate".
</blockquote></details>

Done.
___
*[`vscode-cairo/src/cairols.ts` line 88 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6213#-O4dpGvNBDYiTT3G8GYu:-O4j-L-903MhsqV5AC_J:b-c6n3nt) ([raw file](https://github.com/starkware-libs/cairo/blob/1e67874aed5d6e7f4782c3fc2253bd84979499ec/vscode-cairo/src/cairols.ts#L88)):*
>Can it be a markdown?
>Can you split this into paragraphs

Not really

https://github.com/microsoft/vscode/issues/48900#issuecomment-385332787
https://github.com/microsoft/vscode/issues/50512#issuecomment-422446105


___
*[`vscode-cairo/src/cairols.ts` line 89 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6213#-O4PGOwW63HfhzeosZQ4:-O4izJuz7OoopsWLHnsO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1e67874aed5d6e7f4782c3fc2253bd84979499ec/vscode-cairo/src/cairols.ts#L89)):*
> ```XML
>     const errorMessage =
>       "Corelib version mismatch. If you are using Scarb try reopening the project to fix this error. Resort to `scarb cache clean` if it doesn't help. ERROR: " +
>       params;
> ```

Done.

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6213)* status: all files reviewed, 6 unresolved discussions (waiting on @Arcticae, @Draggu, and @piotmag769)

___
*[`vscode-cairo/src/cairols.ts` line 87 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6213#-O4jgoLd6-BzKFbmYWOS:-O4jgoLd6-BzKFbmYWOT:b-cfkz9x) ([raw file](https://github.com/starkware-libs/cairo/blob/d1b3d6c82284ba0efa31609c098a817fd69b7c7e/vscode-cairo/src/cairols.ts#L87)):*
> ```XML
> 
>   client.onNotification(
>     new NotificationType<string>("cairo/corelib-version-mismatch"),
> ```

is there a reason why are you using NotificationType here? just curious



_Suggestion:_
```XML
"cairo/corelib-version-mismatch"
```

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6213)* status: all files reviewed, 6 unresolved discussions (waiting on @Arcticae, @Draggu, and @piotmag769)

___
*[`vscode-cairo/src/cairols.ts` line 88 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6213#-O4dpGvNBDYiTT3G8GYu:-O4jhAhp8ylbZqchxlOE:bk0mn56) ([raw file](https://github.com/starkware-libs/cairo/blob/1e67874aed5d6e7f4782c3fc2253bd84979499ec/vscode-cairo/src/cairols.ts#L88)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

>Can it be a markdown?
>Can you split this into paragraphs

Not really

https://github.com/microsoft/vscode/issues/48900#issuecomment-385332787
https://github.com/microsoft/vscode/issues/50512#issuecomment-422446105


</blockquote></details>

I see you can register actions/buttons. Perhaps we should add buttons for reloading the window and/or running scarb cache clean. Wdyt?

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6213)* status: all files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, and @mkaput)

___
*[`vscode-cairo/src/cairols.ts` line 88 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6213#-O4dpGvNBDYiTT3G8GYu:-O4kI2q_4iXS6f2WNCiz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1e67874aed5d6e7f4782c3fc2253bd84979499ec/vscode-cairo/src/cairols.ts#L88)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Good idea, will do
</blockquote></details>

Done.

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6213)* status: all files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, and @mkaput)

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6213)* status: all files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, and @piotmag769)

___
*[`vscode-cairo/src/cairols.ts` line 94 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6213#-O4nr1emDlyqnriXlbZS:-O4nr1emDlyqnriXlbZT:b-ttvpk8) ([raw file](https://github.com/starkware-libs/cairo/blob/7df0e370a4c3a73044341a7a0c6f9bbc16d0b902/vscode-cairo/src/cairols.ts#L94)):*
> ```XML
>         errMessage;
> 
>       ctx.log.error(errorMessage);
> ```

IMHO now the extra stuff you put in the error message does not bring anything, so it can be removed



_Suggestion:_
```XML
    async (errorMessage) => {
      ctx.log.error(errorMessage);
```

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6213#-:-O4o0OKPEcAbS4pTeFfF:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae and @Draggu)

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6213)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae and @Draggu)

___
*[`vscode-cairo/src/cairols.ts` line 94 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6213#-O4nr1emDlyqnriXlbZS:-O4nz8Gy3Qu_JS8YZOJQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7df0e370a4c3a73044341a7a0c6f9bbc16d0b902/vscode-cairo/src/cairols.ts#L94)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

IMHO now the extra stuff you put in the error message does not bring anything, so it can be removed
</blockquote></details>

Done.

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6213)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae and @Draggu)

**Review by Draggu — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6213#-:-O4oIEz985owrtOgff0f:bnfp4nl)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @Arcticae and @mkaput)

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6213)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae)

**Pull request merged**
