### PR TITLE
Improved parser diagnostic about missing items

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1530)

### CODE REVIEW

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1530)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1530#-NKMwXr2EMzCvOiEdg1E:-NKMwXr2EMzCvOiEdg1F:b-3yf84a) (no related file):*
change target branch

___

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1530)* status: 1 of 8 files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/parser/src/parser.rs` line 1243 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1530#-NKN6NRH6hcrdEm0YDKq:-NKN6NRH6hcrdEm0YDKr:bo5lnk) ([raw file](https://github.com/starkware-libs/cairo/blob/d712bf071ef1e466dc27edc82107a68470049711/crates/parser/src/parser.rs#L1243)):*
> ```XML
>                 }
>                 self.skip_token(ParserDiagnosticKind::SkippedElement {
>                     element_name: expected_element.to_string().into(),
> ```

cant you convert str -> SmolStr?



_Suggestion:_
```XML
expected_element.into()
```
___
*[`crates/parser/src/parser.rs` line 1309 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1530#-NKN6lTV9jQREfYx0bt2:-NKN6lTV9jQREfYx0bt3:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d712bf071ef1e466dc27edc82107a68470049711/crates/parser/src/parser.rs#L1309)):*
> ```XML
>                 None => {
>                     self.skip_token(ParserDiagnosticKind::SkippedElement {
>                         element_name: expected_element.to_string().into(),
> ```





_Suggestion:_
```XML
.into()
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1530)* status: 1 of 8 files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/parser/src/parser_test_data/item_trait` line 146 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1530#-NKN7ENC4RpM4gFT4pg0:-NKN7ENC4RpM4gFT4pg1:b-hyifor) ([raw file](https://github.com/starkware-libs/cairo/blob/d712bf071ef1e466dc27edc82107a68470049711/crates/parser/src/parser_test_data/item_trait#L146)):*
> ```
>     │   │       │       │       └── optional_no_panic (kind: OptionTerminalNoPanicEmpty) []
>     │   │       │       └── semicolon (kind: TokenSemicolon): ';'
>     │   │       └── rbrace: Missing
> ```

why is it missing?



_Code quote:_
```
rbrace: Missing
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1530)* status: 1 of 8 files reviewed, 5 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/parser/src/parser_test_data/reserved_identifier` line 128 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1530#-NKN7Lnw98Qz2Jlbse3-:-NKN7Lnw98Qz2Jlbse30:bco5g1i) ([raw file](https://github.com/starkware-libs/cairo/blob/d712bf071ef1e466dc27edc82107a68470049711/crates/parser/src/parser_test_data/reserved_identifier#L128)):*
> ```
>       ^*^
> 
> error: Skipped tokens. Expected: trait item or an attribute.
> ```

a trait can't be empty?



_Code quote:_
```
pected: trait item or an attribute
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1530)* status: 1 of 8 files reviewed, 6 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/parser/test_data/expected_results/test2_tree_no_trivia` line 269 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1530#-NKN7U-W8nGggSAALneF:-NKN7U-W8nGggSAALneG:b7c32cj) ([raw file](https://github.com/starkware-libs/cairo/blob/d712bf071ef1e466dc27edc82107a68470049711/crates/parser/test_data/expected_results/test2_tree_no_trivia#L269)):*
> ```
> ^*****^
> 
> error: Skipped tokens. Expected: Module/Use/FreeFunction/ExternFunction/ExternType/Trait/Impl/Struct/Enum or an attribute.
> ```

why is attribute special?



_Code quote:_
```
attribute
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1530)* status: 1 of 18 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/parser/src/parser.rs` line 1243 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1530#-NKN6NRH6hcrdEm0YDKq:-NKNSq0f5UMDlmHF4ECm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d712bf071ef1e466dc27edc82107a68470049711/crates/parser/src/parser.rs#L1243)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

cant you convert str -> SmolStr?
</blockquote></details>

Done.
___
*[`crates/parser/src/parser.rs` line 1309 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1530#-NKN6lTV9jQREfYx0bt2:-NKNSqH75OdELnzpaBKe:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d712bf071ef1e466dc27edc82107a68470049711/crates/parser/src/parser.rs#L1309)):*
> ```XML
>                 None => {
>                     self.skip_token(ParserDiagnosticKind::SkippedElement {
>                         element_name: expected_element.to_string().into(),
> ```

Done.
___
*[`crates/parser/src/parser_test_data/item_trait` line 146 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1530#-NKN7ENC4RpM4gFT4pg0:-NKN_6pFErH3THHk1gDx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d712bf071ef1e466dc27edc82107a68470049711/crates/parser/src/parser_test_data/item_trait#L146)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why is it missing?
</blockquote></details>

Done.
___
*[`crates/parser/test_data/expected_results/test2_tree_no_trivia` line 269 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1530#-NKN7U-W8nGggSAALneF:-NKNRu7j-J4IIuECtqnO:bndazb8) ([raw file](https://github.com/starkware-libs/cairo/blob/d712bf071ef1e466dc27edc82107a68470049711/crates/parser/test_data/expected_results/test2_tree_no_trivia#L269)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why is attribute special?
</blockquote></details>

Because I wanted to add it in the parse_attributes so that it's not forgotten.
Then, there are places where it says "expected trait item". So I had to choose between "expected trait item/attribute" and "expected x/y/z or an attribute". I chose the latter as attribute is indeed special.
___
*[`crates/parser/src/parser_test_data/reserved_identifier` line 128 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1530#-NKN7Lnw98Qz2Jlbse3-:-NKN_7SX3uKtfA5HXEkN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d712bf071ef1e466dc27edc82107a68470049711/crates/parser/src/parser_test_data/reserved_identifier#L128)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

a trait can't be empty?
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r1, 11 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1530)* status: 14 of 18 files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/parser/test_data/expected_results/test2_tree_no_trivia` line 269 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1530#-NKN7U-W8nGggSAALneF:-NKNfx_r9IwYMUOY5yTb:b7qdkxt) ([raw file](https://github.com/starkware-libs/cairo/blob/d712bf071ef1e466dc27edc82107a68470049711/crates/parser/test_data/expected_results/test2_tree_no_trivia#L269)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Because I wanted to add it in the parse_attributes so that it's not forgotten.
Then, there are places where it says "expected trait item". So I had to choose between "expected trait item/attribute" and "expected x/y/z or an attribute". I chose the latter as attribute is indeed special.
</blockquote></details>

Why not

Expected: Module/Use/FreeFunction/ExternFunction/ExternType/Trait/Impl/Struct/Enum/Attribute
?

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1530)* status: 14 of 18 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/parser/test_data/expected_results/test2_tree_no_trivia` line 269 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1530#-NKN7U-W8nGggSAALneF:-NKNirE5523pzWRR8TbU:b3qdjz6) ([raw file](https://github.com/starkware-libs/cairo/blob/d712bf071ef1e466dc27edc82107a68470049711/crates/parser/test_data/expected_results/test2_tree_no_trivia#L269)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why not

Expected: Module/Use/FreeFunction/ExternFunction/ExternType/Trait/Impl/Struct/Enum/Attribute
?
</blockquote></details>

It uses a string param. It is sometimes "Module/Use/FreeFunction/ExternFunction/ExternType/Trait/Impl/Struct/Enum" and sometimes "trait item". If I always add /Attribute, I'll get in other places "expected trait item/Attribute". This seems weird to me.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 25 of 25 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1530#-:-NKNmCKcAlZdabKxCxyA:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

___
*[`crates/parser/test_data/expected_results/test2_tree_no_trivia` line 269 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1530#-NKN7U-W8nGggSAALneF:-NKNm4cMEi_Rw_HWO8t8:b32wtd) ([raw file](https://github.com/starkware-libs/cairo/blob/d712bf071ef1e466dc27edc82107a68470049711/crates/parser/test_data/expected_results/test2_tree_no_trivia#L269)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

It uses a string param. It is sometimes "Module/Use/FreeFunction/ExternFunction/ExternType/Trait/Impl/Struct/Enum" and sometimes "trait item". If I always add /Attribute, I'll get in other places "expected trait item/Attribute". This seems weird to me.
</blockquote></details>

ok

**Pull request merged**
