### PR TITLE
Allow brackets and braces in inline_macro.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3514)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3514)* status: 1 of 17 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 961 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3514#-NYvXD0lDAxhHIGEluzC:-NYvXD0lDAxhHIGEluzD:bat2idz) ([raw file](https://github.com/starkware-libs/cairo/blob/77c92bb395f39ed9e48da625531a4f01e2354800/crates/cairo-lang-parser/src/parser.rs#L961)):*
> ```XML
>             .parse_separated_list::<Expr, TerminalComma, ExprListElementOrSeparatorGreen>(
>                 Self::try_parse_expr,
>                 is_of_kind!(rparen, block, rbrace, top_level),
> ```

shouldn't you always add all the r{brace,paren,brack}?



_Code quote:_
```XML
             is_of_kind!(rparen, block, rbrace, top_level),
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3514)* status: 1 of 17 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 961 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3514#-NYvXD0lDAxhHIGEluzC:-NYvfuJ59F_pumZfWbia:bo8rq7e) ([raw file](https://github.com/starkware-libs/cairo/blob/77c92bb395f39ed9e48da625531a4f01e2354800/crates/cairo-lang-parser/src/parser.rs#L961)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

shouldn't you always add all the r{brace,paren,brack}?
</blockquote></details>

`rbrack` won't close anything in this context, but if appears there will be parsing problems anyway, so I guess it won't hurt.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3514)* status: 1 of 17 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 970 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3514#-NYxj79v16XSgmmffQkJ:-NYxj79v16XSgmmffQkK:b-reg0f6) ([raw file](https://github.com/starkware-libs/cairo/blob/c210b76f4e27f9ba355f8592f2bcb5dddc83c35e/crates/cairo-lang-parser/src/parser.rs#L970)):*
> ```XML
>             ExprList::new_green(self.db, exprs),
>             rparen,
>         )
> ```

it seems all three functions contains the exact same basic logic - maybe extract it to a function returning the 2 terminals and the exprs - and externally build the different greens?



_Code quote:_
```XML
        let lparen = self.take::<TerminalLParen>();
        let exprs: Vec<ExprListElementOrSeparatorGreen> = self
            .parse_separated_list::<Expr, TerminalComma, ExprListElementOrSeparatorGreen>(
                Self::try_parse_expr,
                is_of_kind!(rparen, rbrace, rbrack, block, top_level),
                "expression",
            );
        let rparen = self.parse_token::<TerminalRParen>();
        ExprListParenthesized::new_green(
            self.db,
            lparen,
            ExprList::new_green(self.db, exprs),
            rparen,
        )
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3514)* status: 1 of 17 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 970 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3514#-NYxj79v16XSgmmffQkJ:-NZ0JEtr5gRNjQZdwfRV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c210b76f4e27f9ba355f8592f2bcb5dddc83c35e/crates/cairo-lang-parser/src/parser.rs#L970)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it seems all three functions contains the exact same basic logic - maybe extract it to a function returning the 2 terminals and the exprs - and externally build the different greens?
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 15 of 17 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3514#-:-NZ0Mxq11b-uzLLlMtiM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
