### PR TITLE
Add array! macro.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3501)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3501)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3501#-NYmtM1H6VH3YA1B2XCh:-NYmtM1H6VH3YA1B2XCi:b-lefas8) (no related file):*
Change target branch.

___

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3501)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-plugins/src/test_data/inline_macros` line 206 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3501#-NYmthJW0KiwAiqusAVi:-NYmthJW0KiwAiqusAVj:b-tzqcu8) ([raw file](https://github.com/starkware-libs/cairo/blob/8aa88211210ab3e7c5ca0881fa0a66a1bcd6b0da/crates/cairo-lang-plugins/src/test_data/inline_macros#L206)):*
> ```
>                            _temp_array.append(2);
>                            _temp_array.append(3);
>                         
> ```

Trying to remove these whitespaces.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3501)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-plugins/src/plugins/inline_macros/array.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3501#-NYmtWo_EKb6If9t0F7l:-NYmtWo_EKb6If9t0F7m:b-ozws21) ([raw file](https://github.com/starkware-libs/cairo/blob/8aa88211210ab3e7c5ca0881fa0a66a1bcd6b0da/crates/cairo-lang-plugins/src/plugins/inline_macros/array.rs#L17)):*
> ```XML
>         let mut expanded_code = 
>             "{
>                 let mut _temp_array = ArrayTrait::new();
> ```

make this name worse.
?



_Suggestion:_
```XML
 __array_builder_macro_result___
```

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3501)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3501#-NYmzlQT6bLNNREz3hQ9:-NYmzlQT6bLNNREz3hQA:b-9b76ke) (no related file):*
Do we want square brackets? `array![a,b,c]`?

___

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3501)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3501)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @orizi and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3501#-NYmzlQT6bLNNREz3hQ9:-NYnaoku7ltnVRfRGAQl:bw7yei3) (no related file):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Do we want square brackets? `array![a,b,c]`?
</blockquote></details>

Yes, I am adding it.

___
___
*[`crates/cairo-lang-plugins/src/plugins/inline_macros/array.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3501#-NYmtWo_EKb6If9t0F7l:-NYnanLy5YCauWTidc4R:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8aa88211210ab3e7c5ca0881fa0a66a1bcd6b0da/crates/cairo-lang-plugins/src/plugins/inline_macros/array.rs#L17)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

make this name worse.
?
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3501)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3501)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3501#-NYmzlQT6bLNNREz3hQ9:-NYqfSaP-Hcq3Sd3gVa8:bhgv232) (no related file):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Yes, I am adding it.
</blockquote></details>

adding a block for this :)

___

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3501)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3501#-NYmzlQT6bLNNREz3hQ9:-NYsIzWm2Dyw6aqbcVCS:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

adding a block for this :)
</blockquote></details>

Done.

___

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3501)* status: 2 of 26 files reviewed, 5 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-plugins/src/plugins/inline_macros/array.rs` line 24 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3501#-NYxk7y555vfC3Oi-_fc:-NZ-eRMj-Rf6YHnJ6kmu:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/823487bb428f3124d2e9c811cc6541657d783801/crates/cairo-lang-plugins/src/plugins/inline_macros/array.rs#L24)):*
> ```XML
>                 arg.as_syntax_node().get_text(db)
>             ));
>         }
> ```

Done.
___
*[`crates/cairo-lang-plugins/src/plugins/inline_macros/array.rs` line 29 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3501#-NYxkfib7gPj27jPBwsh:-NZ-eRoQ0QLRt4ZptORg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/823487bb428f3124d2e9c811cc6541657d783801/crates/cairo-lang-plugins/src/plugins/inline_macros/array.rs#L29)):*
> ```XML
>                 __array_builder_macro_result__
>             }",
>         );
> ```

Done.
___
*[`crates/cairo-lang-plugins/src/plugins/inline_macros/array.rs` line 34 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3501#-NYxk34Y4tK7oLYtLRP3:-NZ-eSWRAYL9ZK1KUDTN:bbc7y7w) ([raw file](https://github.com/starkware-libs/cairo/blob/823487bb428f3124d2e9c811cc6541657d783801/crates/cairo-lang-plugins/src/plugins/inline_macros/array.rs#L34)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

It is docd in the trait.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 23 files at r7, 23 of 23 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3501)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-plugins/src/plugins/inline_macros/array.rs` line 19 at r8](https://reviewable.io/reviews/starkware-libs/cairo/3501#-NZ-kYHlAMBzbmWGt6bX:-NZ-kYHlAMBzbmWGt6bY:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9362fc157b14bef3438639460ff488dc1e6d3314/crates/cairo-lang-plugins/src/plugins/inline_macros/array.rs#L19)):*
> ```XML
>         for arg in args {
>             expanded_code.push_str(&format!(
>                 "\n                __array_builder_macro_result__.append({});",
> ```





_Suggestion:_
```XML
            expanded_code.push_str(&format!(
                "\n            __array_builder_macro_result__.append({});",
```
___
*[`crates/cairo-lang-plugins/src/plugins/inline_macros/array.rs` line 25 at r8](https://reviewable.io/reviews/starkware-libs/cairo/3501#-NZ-klMMDBJVSt6b90eB:-NZ-klMNBM2UNoUDM0Oc:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9362fc157b14bef3438639460ff488dc1e6d3314/crates/cairo-lang-plugins/src/plugins/inline_macros/array.rs#L25)):*
> ```XML
>         expanded_code.push_str(
>             "\n                __array_builder_macro_result__
>         }",
> ```





_Suggestion:_
```XML
        expanded_code.push_str(
            "\n            __array_builder_macro_result__

        }",
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3501)* status: 25 of 26 files reviewed, 3 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-plugins/src/plugins/inline_macros/array.rs` line 19 at r8](https://reviewable.io/reviews/starkware-libs/cairo/3501#-NZ-kYHlAMBzbmWGt6bX:-NZ-oMF205P4HWEa4JnC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9362fc157b14bef3438639460ff488dc1e6d3314/crates/cairo-lang-plugins/src/plugins/inline_macros/array.rs#L19)):*
> ```XML
>         for arg in args {
>             expanded_code.push_str(&format!(
>                 "\n                __array_builder_macro_result__.append({});",
> ```

Done.
___
*[`crates/cairo-lang-plugins/src/plugins/inline_macros/array.rs` line 25 at r8](https://reviewable.io/reviews/starkware-libs/cairo/3501#-NZ-klMMDBJVSt6b90eB:-NZ-oMyFAeGZ0bOTjBTg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9362fc157b14bef3438639460ff488dc1e6d3314/crates/cairo-lang-plugins/src/plugins/inline_macros/array.rs#L25)):*
> ```XML
>         expanded_code.push_str(
>             "\n                __array_builder_macro_result__
>         }",
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3501#-:-NZ-tcjWDGaR6RZ1b7ml:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Comment by gilbens-starkware** [comment]
Resolves #3220.

**Pull request merged**
