### PR TITLE
Use whole locations vector in statements functions map

### PR DESCRIPTION
**Pull request by piotmag769**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5601)

### CODE REVIEW

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5601)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/statements_functions.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5601#-NyR2ygH4ovY-znanjFc:-NyR8Yt01bF2R3biYeYj:bvpj436) ([raw file](https://github.com/starkware-libs/cairo/blob/22557d59af8ccb9374cf4a7cd1fb6cd94ca82892/crates/cairo-lang-sierra-generator/src/statements_functions.rs#L13)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is it any better than just a vec?
are you using the extra information from that case?
</blockquote></details>

It is, but I don't want the compiler to panic suddenly when I unwrap, I can handle it on my side

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5601)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/statements_functions.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5601#-NyR2ygH4ovY-znanjFc:-NyV10lpCg6NCcuGdUL2:b-b23apk) ([raw file](https://github.com/starkware-libs/cairo/blob/22557d59af8ccb9374cf4a7cd1fb6cd94ca82892/crates/cairo-lang-sierra-generator/src/statements_functions.rs#L13)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i meant just filtering out `None`s
</blockquote></details>

Actually true, I will add tests in the compiler to be sure that if the `None` appears we are aware of that

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5601)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @piotmag769)

___
*[`crates/cairo-lang-sierra-generator/src/statements_functions.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5601#-NyR2ygH4ovY-znanjFc:-NyV3Ygh9b_ilsMaT2f9:b8i4ldc) ([raw file](https://github.com/starkware-libs/cairo/blob/22557d59af8ccb9374cf4a7cd1fb6cd94ca82892/crates/cairo-lang-sierra-generator/src/statements_functions.rs#L13)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Actually true, I will add tests in the compiler to be sure that if the `None` appears we are aware of that
</blockquote></details>

i don't understand if you are doing a change here.

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5601)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/statements_functions.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5601#-NyR2ygH4ovY-znanjFc:-NyV5Bjf-4ywsZ9RhhoJ:by827el) ([raw file](https://github.com/starkware-libs/cairo/blob/22557d59af8ccb9374cf4a7cd1fb6cd94ca82892/crates/cairo-lang-sierra-generator/src/statements_functions.rs#L13)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i don't understand if you are doing a change here.
</blockquote></details>

Done, will add tests in another PR (not that high prio for me rn).

**Pull request merged**
