### PR TITLE
Extract extract_semantic_entrypoints()

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2908)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2907** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2907" target="_blank">Graphite</a> 
    * **PR #2908** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2908" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2908?utm_source=stack-comment).

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2908#-:-NTdmkx3CEziveIjzs-u:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2908)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/contract.rs` line 151 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2908#-NTds-yA49vDsrxtsR4Y:-NTds-yA49vDsrxtsR4Z:b8uywyj) ([raw file](https://github.com/starkware-libs/cairo/blob/728b9a7c36773224184825092ad69f356387528d/crates/cairo-lang-starknet/src/contract.rs#L151)):*
> ```XML
> 
> /// Converts a function to a Sierra function.
> pub fn to_sierra_function<T: SierraIdReplacer>(
> ```

Doc the other ret val.
And maybe also rename, as the selector is not trivial from the name itself

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2908)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/contract.rs` line 151 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2908#-NTds-yA49vDsrxtsR4Y:-NTe7-JQ57SWyu2dWQS5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/728b9a7c36773224184825092ad69f356387528d/crates/cairo-lang-starknet/src/contract.rs#L151)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Doc the other ret val.
And maybe also rename, as the selector is not trivial from the name itself 
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2908)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
