### PR TITLE
Made const folding handle lower-if optimization.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #5135
- #5134
- #5133 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5133)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5133)* status: 0 of 21 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/lower_if.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5133#-NrU-C7JAmXzLQvQ1iGs:-NrU-C7JAmXzLQvQ1iGt:ba3tmbi) ([raw file](https://github.com/starkware-libs/cairo/blob/91c0fedb5cdb0cdac6e64b9becb99c6e40c8838c/crates/cairo-lang-lowering/src/lower/lower_if.rs#L35)):*
> ```XML
> /// optimizations.
> // TODO(lior): Make it an actual tree (handling && and ||).
> fn analyze_condition(ctx: &LoweringContext<'_, '_>, expr_id: semantic::ExprId) -> IfCondition {
> ```

Can you remove this in a separate PR?



_Code quote:_
```XML
fn analyze_condition(ctx: &LoweringContext<'_, '_>, expr_id: semantic::ExprId) -> IfCondition {
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5133)* status: 0 of 21 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/lower/lower_if.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5133#-NrU-C7JAmXzLQvQ1iGs:-NrU-X117akAMCEpOzFI:b-ozz772) ([raw file](https://github.com/starkware-libs/cairo/blob/91c0fedb5cdb0cdac6e64b9becb99c6e40c8838c/crates/cairo-lang-lowering/src/lower/lower_if.rs#L35)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Can you remove this in a separate PR?
</blockquote></details>

this PR will do nothing if this isn't removed with it.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/const_folding.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5133#-NrU00GWD18RHQmYMbaP:-NrU00GWD18RHQmYMbaQ:b-c7r430) ([raw file](https://github.com/starkware-libs/cairo/blob/d38def43ca53cf42fbf7339d60c2afcaa72c0489/crates/cairo-lang-lowering/src/optimizations/const_folding.rs#L167)):*
> ```XML
>                             Some(VarInfo::Const(ConstValue::Int(value))) => {
>                                 let arm = &arms[value.to_usize().unwrap()];
>                                 block.end = FlatBlockEnd::Goto(arm.block_id, Default::default());
> ```

can you add an assert that
arm.var_ids.is_empty
?



_Code quote:_
```XML
                                let arm = &arms[value.to_usize().unwrap()];
                                block.end = FlatBlockEnd::Goto(arm.block_id, Default::default());
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5133)* status: 0 of 21 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/const_folding.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5133#-NrU00GWD18RHQmYMbaP:-NrU9dhu0EBk8xJgmaIN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d38def43ca53cf42fbf7339d60c2afcaa72c0489/crates/cairo-lang-lowering/src/optimizations/const_folding.rs#L167)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

can you add an assert that
arm.var_ids.is_empty
?
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/test_data/loop` line 236 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5133#-NrUB33hEZD_QBLnt6iA:-NrUB33hEZD_QBLnt6iB:b7otwog) ([raw file](https://github.com/starkware-libs/cairo/blob/8005767de97b2f29e13e0d9dcc829420ec463ec7/crates/cairo-lang-lowering/src/lower/test_data/loop#L236)):*
> ```
>   (v8: core::bool) <- core::Felt252PartialEq::eq(v4, v7)
> End:
>   Match(match_enum(v8) {
> ```

this is a regression, right?



_Code quote:_
```
  (v3: core::felt252, v4: @core::felt252) <- snapshot(v2)
  (v5: core::felt252) <- 10u
  (v6: core::felt252, v7: @core::felt252) <- snapshot(v5)
  (v8: core::bool) <- core::Felt252PartialEq::eq(v4, v7)
End:
  Match(match_enum(v8) {
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5133)* status: 0 of 22 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/lower_if.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5133#-NrU-C7JAmXzLQvQ1iGs:-NrUB7qJ4OnkhiEKZ8n0:b-vfqgbs) ([raw file](https://github.com/starkware-libs/cairo/blob/91c0fedb5cdb0cdac6e64b9becb99c6e40c8838c/crates/cairo-lang-lowering/src/lower/lower_if.rs#L35)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this PR will do nothing if this isn't removed with it.
</blockquote></details>

can you add a test where you do

let c = b - 0;
if c == 0 {
...
}

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5133)* status: 0 of 22 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/lower/lower_if.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5133#-NrU-C7JAmXzLQvQ1iGs:-NrUHATp3e8lnv0A7oDa:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/91c0fedb5cdb0cdac6e64b9becb99c6e40c8838c/crates/cairo-lang-lowering/src/lower/lower_if.rs#L35)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

can you add a test where you do

let c = b - 0;
if c == 0 {
...
}
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/test_data/loop` line 236 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5133#-NrUB33hEZD_QBLnt6iA:-NrUBDXm-OWSKrA_gv4K:bzgrmul) ([raw file](https://github.com/starkware-libs/cairo/blob/8005767de97b2f29e13e0d9dcc829420ec463ec7/crates/cairo-lang-lowering/src/lower/test_data/loop#L236)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

this is a regression, right?
</blockquote></details>

it seems inline didn't kick in in this area just yet.
as you see - `core::Felt252PartialEq::eq` is called here directly - but this should definitely be inlined (and is inlined ) in reality.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/lower_if.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5133#-NrU-C7JAmXzLQvQ1iGs:-NrUN4zl-qA47PgSsbhL:b-qtllnu) ([raw file](https://github.com/starkware-libs/cairo/blob/91c0fedb5cdb0cdac6e64b9becb99c6e40c8838c/crates/cairo-lang-lowering/src/lower/lower_if.rs#L35)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Done.
</blockquote></details>

actually this, worked before the changes, right?

Can you add tests for the new optimizations?

**Comment by orizi** [comment]
Closing pull request: commit has gone away

**Pull request closed without merging**
