### PR TITLE
Refactored ec user code.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #3728
- #3691
- #3690 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3690)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3690)* status: 1 of 7 files reviewed, 4 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`corelib/src/ec.cairo` line 78 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3690#-N_TxnZhBz2NsQ5Bffi1:-N_TxnZhBz2NsQ5Bffi2:bs9w08p) ([raw file](https://github.com/starkware-libs/cairo/blob/a64260ad447705e0ba466a48d479b6593a4b5a5a/corelib/src/ec.cairo#L78)):*
> ```Cairo
> impl EcStateImpl of EcStateTrait {
>     /// Initializes an EC computation with the zero point.
>     fn init() -> EcState {
> ```

Shouldn't it be inlined?
___
*[`corelib/src/ec.cairo` line 92 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3690#-N_TxywHBgyHUyQvxUgq:-N_TxywHBgyHUyQvxUgr:bb6umqj) ([raw file](https://github.com/starkware-libs/cairo/blob/a64260ad447705e0ba466a48d479b6593a4b5a5a/corelib/src/ec.cairo#L92)):*
> ```Cairo
>     }
>     #[inline(always)]
>     fn finalize_nz(self: EcState) -> Option<NonZeroEcPoint> {
> ```

Doc.
___
*[`corelib/src/ec.cairo` line 119 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3690#-N_TzIgB3FfK8JOTeUSh:-N_TzIgB3FfK8JOTeUSi:b-x451fe) ([raw file](https://github.com/starkware-libs/cairo/blob/a64260ad447705e0ba466a48d479b6593a4b5a5a/corelib/src/ec.cairo#L119)):*
> ```Cairo
>     /// Tests whether the given EC point is the zero point.
>     #[inline(always)]
>     fn test_zero(self: EcPoint) -> IsZeroResult<EcPoint> {
> ```

Why not `is_zero`?
___
*[`corelib/src/ec.cairo` line 187 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3690#-N_TyzUc23pVYKqIt-GW:-N_TyzUc23pVYKqIt-GX:bbhfcik) ([raw file](https://github.com/starkware-libs/cairo/blob/a64260ad447705e0ba466a48d479b6593a4b5a5a/corelib/src/ec.cairo#L187)):*
> ```Cairo
>         };
>         // lhs - rhs = lhs + (-rhs).
>         lhs + -rhs
> ```

Consider:



_Suggestion:_
```Cairo
lhs + (-rhs)
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3690)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @liorgold2)

___
*[`corelib/src/ec.cairo` line 78 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3690#-N_TxnZhBz2NsQ5Bffi1:-N_XRGDGDgMNqEhKLEMZ:bfdksf8) ([raw file](https://github.com/starkware-libs/cairo/blob/a64260ad447705e0ba466a48d479b6593a4b5a5a/corelib/src/ec.cairo#L78)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Shouldn't it be inlined?
</blockquote></details>

single line no inputs - automatically inlined.
___
*[`corelib/src/ec.cairo` line 119 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3690#-N_TzIgB3FfK8JOTeUSh:-N_XSIWj5AUnrF9M9k9l:b8j462k) ([raw file](https://github.com/starkware-libs/cairo/blob/a64260ad447705e0ba466a48d479b6593a4b5a5a/corelib/src/ec.cairo#L119)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Why not `is_zero`?
</blockquote></details>

just using TryInto instead.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r1, 3 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3690#-:-N_Xr7j-CS8ft15PxmAT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/ec.cairo` line 41 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3690#-N_n5v8H9t54OED5sDIH:-N_n5v8H9t54OED5sDII:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d9c4677b0bb6e461ae4793683c97fe612018e3bd/corelib/src/ec.cairo#L41)):*
> ```Cairo
> extern fn ec_point_is_zero(p: EcPoint) -> IsZeroResult<EcPoint> nopanic;
> 
> /// Converts `EcPoint` to `NonZeroEcPoint`.
> ```





_Suggestion:_
```Cairo
Option<NonZeroEcPoint?
```

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/ec.cairo` line 64 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3690#-N_n6HIy3MPeJlsPCwAj:-N_n6HIy3MPeJlsPCwAk:bebqwa6) ([raw file](https://github.com/starkware-libs/cairo/blob/d9c4677b0bb6e461ae4793683c97fe612018e3bd/corelib/src/ec.cairo#L64)):*
> ```Cairo
> extern fn ec_state_add(ref s: EcState, p: NonZeroEcPoint) nopanic;
> /// Adds the product p * m to the state.
> extern fn ec_state_add_mul(ref s: EcState, m: felt252, p: NonZeroEcPoint) implicits(EcOp) nopanic;
> ```

Lior decided to rename it it in the secp code.



_Suggestion:_
```Cairo
scalar
```

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/ec.cairo` line 115 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3690#-N_n6jUgC2E06YbHFPdz:-N_n6jUgC2E06YbHFPe-:bvk7d9b) ([raw file](https://github.com/starkware-libs/cairo/blob/d9c4677b0bb6e461ae4793683c97fe612018e3bd/corelib/src/ec.cairo#L115)):*
> ```Cairo
>     /// Tests whether the given EC point is the zero point.
>     #[inline(always)]
>     fn coordinates(self: NonZeroEcPoint) -> (felt252, felt252) {
> ```

fix comment.



_Code quote:_
```Cairo
    /// Tests whether the given EC point is the zero point.
    #[inline(always)]
    fn coordinates(self: NonZeroEcPoint) -> (felt252, felt252) {
```

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/ec.cairo` line 141 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3690#-N_n74Cp3bcZhX7Je8-K:-N_n74Cp3bcZhX7Je8-L:b-sf1rs6) ([raw file](https://github.com/starkware-libs/cairo/blob/d9c4677b0bb6e461ae4793683c97fe612018e3bd/corelib/src/ec.cairo#L141)):*
> ```Cairo
>     // TODO(lior): Implement using a libfunc to make it more efficient.
>     fn add(lhs: EcPoint, rhs: EcPoint) -> EcPoint {
>         let lhs_nz = match lhs.try_into() {
> ```

I think it is a bad idea to use try_into here.
it is not clear what the type is.



_Code quote:_
```Cairo
lhs.try_into()
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3690)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware, @ilyalesokhin-starkware, and @liorgold2)

___
*[`corelib/src/ec.cairo` line 35 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3690#-N_n66_w1we-dGs9wUhZ:-N_nHVDD4Q1-7kojAOAb:b-bg72ao) ([raw file](https://github.com/starkware-libs/cairo/blob/d9c4677b0bb6e461ae4793683c97fe612018e3bd/corelib/src/ec.cairo#L35)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why is it called unwrap?

maybe it should be get_xy?
</blockquote></details>

this is the name of the libfunc - so not relevant to the pr in any case.
___
*[`corelib/src/ec.cairo` line 41 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3690#-N_n5v8H9t54OED5sDIH:-N_nHab94aMNtv4HSx0i:b4vopur) ([raw file](https://github.com/starkware-libs/cairo/blob/d9c4677b0bb6e461ae4793683c97fe612018e3bd/corelib/src/ec.cairo#L41)):*
> ```Cairo
> extern fn ec_point_is_zero(p: EcPoint) -> IsZeroResult<EcPoint> nopanic;
> 
> /// Converts `EcPoint` to `NonZeroEcPoint`.
> ```

try_into converts x into y - it returns Option<y> to allow failure.
___
*[`corelib/src/ec.cairo` line 64 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3690#-N_n6HIy3MPeJlsPCwAj:-N_nI2_z2EDmlPdtzx2G:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d9c4677b0bb6e461ae4793683c97fe612018e3bd/corelib/src/ec.cairo#L64)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Lior decided to rename it it in the secp code.
</blockquote></details>

Done.
___
*[`corelib/src/ec.cairo` line 115 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3690#-N_n6jUgC2E06YbHFPdz:-N_nJ3S3EGp3F47U7tSZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d9c4677b0bb6e461ae4793683c97fe612018e3bd/corelib/src/ec.cairo#L115)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

fix comment.
</blockquote></details>

Done.
___
*[`corelib/src/ec.cairo` line 141 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3690#-N_n74Cp3bcZhX7Je8-K:-N_nJ9FI3mwe22OyjDJG:b-2nq8pa) ([raw file](https://github.com/starkware-libs/cairo/blob/d9c4677b0bb6e461ae4793683c97fe612018e3bd/corelib/src/ec.cairo#L141)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I think it is a bad idea to use try_into here.
it is not clear what the type is.
</blockquote></details>

i agree that we need a general way to be explicit about that, but we are yet to have it.

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/ec.cairo` line 141 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3690#-N_n74Cp3bcZhX7Je8-K:-Na0QDfA1GdxgSOxzFsK:b3lu8hc) ([raw file](https://github.com/starkware-libs/cairo/blob/d9c4677b0bb6e461ae4793683c97fe612018e3bd/corelib/src/ec.cairo#L141)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i agree that we need a general way to be explicit about that, but we are yet to have it.
</blockquote></details>

why not keep the original code with
ec_point_is_zero(
?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3690)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware, @ilyalesokhin-starkware, and @liorgold2)

___
*[`corelib/src/ec.cairo` line 141 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3690#-N_n74Cp3bcZhX7Je8-K:-Na0QZSY0OukMe7QmoWb:bfzab6i) ([raw file](https://github.com/starkware-libs/cairo/blob/d9c4677b0bb6e461ae4793683c97fe612018e3bd/corelib/src/ec.cairo#L141)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why not keep the original code with
ec_point_is_zero(
?
</blockquote></details>

because that is our general way to convert into non-zero's all over the code base.
so i'd rather be consistent.

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/ec.cairo` line 141 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3690#-N_n74Cp3bcZhX7Je8-K:-Na0Zy3m1PJ7BKHTI1u8:b-wazykm) ([raw file](https://github.com/starkware-libs/cairo/blob/d9c4677b0bb6e461ae4793683c97fe612018e3bd/corelib/src/ec.cairo#L141)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

because that is our general way to convert into non-zero's all over the code base.
so i'd rather be consistent.
</blockquote></details>

Where else is it used?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3690)* status: 3 of 7 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware, @ilyalesokhin-starkware, and @liorgold2)

___
*[`corelib/src/ec.cairo` line 141 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3690#-N_n74Cp3bcZhX7Je8-K:-Na0bdCMEynGpV22FepF:b-e95p9u) ([raw file](https://github.com/starkware-libs/cairo/blob/d9c4677b0bb6e461ae4793683c97fe612018e3bd/corelib/src/ec.cairo#L141)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Where else is it used?
</blockquote></details>

all integer divisions.

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/ec.cairo` line 141 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3690#-N_n74Cp3bcZhX7Je8-K:-Na0iKLV6g3Z0bTEuBRI:b-bucwsj) ([raw file](https://github.com/starkware-libs/cairo/blob/d9c4677b0bb6e461ae4793683c97fe612018e3bd/corelib/src/ec.cairo#L141)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

all integer divisions.
</blockquote></details>

I think we should have a special trait for that.

but Unblocking for now.

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 1 of 7 files at r1, 2 of 6 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3690)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Comment by orizi** [comment]
Closing pull request: commit has gone away

**Pull request closed without merging**
