### PR TITLE
Added widemul for u256.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #3112
- #3108 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3108)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3108)* status: all files reviewed, 5 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`corelib/src/integer.cairo` line 1092 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3108#-NV3Zgj61AwTN5soscvi:-NV3Zgj61AwTN5soscvj:b-i6aceu) ([raw file](https://github.com/starkware-libs/cairo/blob/72edd72d896af62aa52ec386583a30ec8789e3dd/corelib/src/integer.cairo#L1092)):*
> ```Cairo
> 
> #[inline(always)]
> fn u256_wide_mul_add_limb2_helper(ref value: u512, limb: u128) {
> ```

doc + why needed specifically for limb2...
___
*[`corelib/src/integer.cairo` line 1099 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3108#-NV3Zcyf-3DrI3yoYmuC:-NV3Zcyf-3DrI3yoYmuD:bx58r) ([raw file](https://github.com/starkware-libs/cairo/blob/72edd72d896af62aa52ec386583a30ec8789e3dd/corelib/src/integer.cairo#L1099)):*
> ```Cairo
>         Result::Err(v) => {
>             value.limb2 = v;
>             value.limb3 += 1;
> ```

what if limb3 overflows now?
I know it should not happen when these are called from u256_wide_mul, but this is a public function. Either handle the case, or document that it doesn't handle limb3 overflow and that it's only to be used by u256_wide_mul, the way it is used now.
___
*[`corelib/src/integer.cairo` line 1105 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3108#-NV3ZwMGA9Y9V_vPbfQW:-NV3ZwMGA9Y9V_vPbfQX:bb7od0r) ([raw file](https://github.com/starkware-libs/cairo/blob/72edd72d896af62aa52ec386583a30ec8789e3dd/corelib/src/integer.cairo#L1105)):*
> ```Cairo
> 
> #[inline(always)]
> fn u256_wide_mul_add_limb1_helper(ref value: u512, limb: u128) {
> ```

same
___
*[`corelib/src/integer.cairo` line 1124 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3108#-NV3aTGcA5EopZhFck7M:-NV3aTGcA5EopZhFck7N:b-p4k1sf) ([raw file](https://github.com/starkware-libs/cairo/blob/72edd72d896af62aa52ec386583a30ec8789e3dd/corelib/src/integer.cairo#L1124)):*
> ```Cairo
>     u256_wide_mul_add_limb1_helper(ref result, limb1_part);
>     u256_wide_mul_add_limb2_helper(ref result, limb2_part);
>     let (limb2_part, limb1_part) = u128_wide_mul(a.high, b.low);
> ```

As you call each helper twice, it has the potential to add 1 (to the next limb) twice. To easily improve it a bit, you can change the helper to return the addition you need to the next limb (either a bool or a u128). Then you call the limb1 helper twice and aggregate the addition to limb2 to add it at once. Same for limb2 and the addition to limb3 (here you actually call the limb2 helper 3 times (once again with the overflow from limb1))
___
*[`corelib/src/test/integer_test.cairo` line 681 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3108#-NV3bR6p8PF4hP1yproL:-NV3bR6p8PF4hP1yproM:bs3s93p) ([raw file](https://github.com/starkware-libs/cairo/blob/72edd72d896af62aa52ec386583a30ec8789e3dd/corelib/src/test/integer_test.cairo#L681)):*
> ```Cairo
> #[test]
> fn test_u256_wide_mul() {
>     assert(u256_wide_mul(0, 0) == u512 { limb0: 0, limb1: 0, limb2: 0, limb3: 0 }, '0 * 0 == 0');
> ```

'0 * 0 != 0'.
This is the error message in case of assertion failure.

Also below: 'long calculation failed'

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3108)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`corelib/src/integer.cairo` line 1092 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3108#-NV3Zgj61AwTN5soscvi:-NV3eGBf0ju6N-PIrIsY:b-eiayuz) ([raw file](https://github.com/starkware-libs/cairo/blob/72edd72d896af62aa52ec386583a30ec8789e3dd/corelib/src/integer.cairo#L1092)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

doc + why needed specifically for limb2...
</blockquote></details>

Done.
It is needed since i call it.
___
*[`corelib/src/integer.cairo` line 1099 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3108#-NV3Zcyf-3DrI3yoYmuC:-NV3cXam6eJT6lN7_B8E:bj5xgpn) ([raw file](https://github.com/starkware-libs/cairo/blob/72edd72d896af62aa52ec386583a30ec8789e3dd/corelib/src/integer.cairo#L1099)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

what if limb3 overflows now?
I know it should not happen when these are called from u256_wide_mul, but this is a public function. Either handle the case, or document that it doesn't handle limb3 overflow and that it's only to be used by u256_wide_mul, the way it is used now.
</blockquote></details>

added doc.
___
*[`corelib/src/integer.cairo` line 1124 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3108#-NV3aTGcA5EopZhFck7M:-NV3e2LE-djYoUrL-sWI:bj60dey) ([raw file](https://github.com/starkware-libs/cairo/blob/72edd72d896af62aa52ec386583a30ec8789e3dd/corelib/src/integer.cairo#L1124)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

As you call each helper twice, it has the potential to add 1 (to the next limb) twice. To easily improve it a bit, you can change the helper to return the addition you need to the next limb (either a bool or a u128). Then you call the limb1 helper twice and aggregate the addition to limb2 to add it at once. Same for limb2 and the addition to limb3 (here you actually call the limb2 helper 3 times (once again with the overflow from limb1))
</blockquote></details>

this isn't as simple as you claim here - if it is - please give a code suggestion.
___
*[`corelib/src/test/integer_test.cairo` line 681 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3108#-NV3bR6p8PF4hP1yproL:-NV3eNYRCTWUd8Unh19F:b1yq4zw) ([raw file](https://github.com/starkware-libs/cairo/blob/72edd72d896af62aa52ec386583a30ec8789e3dd/corelib/src/test/integer_test.cairo#L681)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

'0 * 0 != 0'.
This is the error message in case of assertion failure.

Also below: 'long calculation failed'
</blockquote></details>

we don't have that many chars for error - my main aim is to easily find the the failed assertion, while being economic with the err msg - suggestions for better assertion strings?

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3108)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`corelib/src/integer.cairo` line 1124 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3108#-NV3aTGcA5EopZhFck7M:-NV4LMkn18chRhH5trIf:b-xie6p0) ([raw file](https://github.com/starkware-libs/cairo/blob/72edd72d896af62aa52ec386583a30ec8789e3dd/corelib/src/integer.cairo#L1124)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this isn't as simple as you claim here - if it is - please give a code suggestion.
</blockquote></details>

#[derive(Copy, Drop, PartialEq, Serde)]
struct u512 {
    limb0: u128,
    limb1: u128,
    limb2: u128,
    limb3: u128,
}

#[inline(always)]
fn u256_wide_mul_add_limb2_helper(ref value: u512, limb: u128) -> u128 nopanic {
    match u128_overflowing_add(value.limb2, limb) {
        Result::Ok(v) => {
            value.limb2 = v;
            0
        },
        Result::Err(v) => {
            value.limb2 = v;
            1
        },
    }
}

#[inline(always)]
fn u256_wide_mul_add_limb1_helper(ref value: u512, limb: u128) -> u128 nopanic {
    match u128_overflowing_add(value.limb1, limb) {
        Result::Ok(v) => {
            value.limb1 = v;
            0
        },
        Result::Err(v) => {
            value.limb1 = v;
            1
        },
    }
}

fn u256_wide_mul(a: u256, b: u256) -> u512 nopanic {
    let (limb1, limb0) = u128_wide_mul(a.low, b.low);
    let (limb3, limb2) = u128_wide_mul(a.high, b.high);
    let mut result = u512 { limb0, limb1, limb2, limb3 };

    let (ab_limb2_part, ab_limb1_part) = u128_wide_mul(a.low, b.high);
    let (ba_limb2_part, ba_limb1_part) = u128_wide_mul(b.low, a.high);

    let limb1_overflow1 = u256_wide_mul_add_limb1_helper(ref result, ab_limb1_part);
    let limb1_overflow2 = u256_wide_mul_add_limb1_helper(ref result, ba_limb1_part);
    // No overflow possible in this addition since both operands are 0/1.
    let limb1_overflow = u128_wrapping_add(limb1_overflow1, limb1_overflow2);

    let limb2_overflow1 = u256_wide_mul_add_limb2_helper(ref result, ab_limb2_part);
    let limb2_overflow2 = u256_wide_mul_add_limb2_helper(ref result, ba_limb2_part);
    let limb2_overflow3 = u256_wide_mul_add_limb2_helper(ref result, limb1_overflow);
    // No overflow possible in this additions since all operands are 0/1.
    let limb2_overflow = u128_wrapping_add(
        u128_wrapping_add(limb2_overflow1, limb2_overflow2), limb2_overflow3
    );

    // No overflow possible since the product of 2 u256s can't overflow a u512.
    value.limb3 = u128_wrapping_add(value.limb3, limb2_overflow);

    result
}
___
*[`corelib/src/test/integer_test.cairo` line 681 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3108#-NV3bR6p8PF4hP1yproL:-NV4LbQWC3L-VjxGGbeV:bio2zrc) ([raw file](https://github.com/starkware-libs/cairo/blob/72edd72d896af62aa52ec386583a30ec8789e3dd/corelib/src/test/integer_test.cairo#L681)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

we don't have that many chars for error - my main aim is to easily find the the failed assertion, while being economic with the err msg - suggestions for better assertion strings?
</blockquote></details>

We have 31 chars, don't we?
My suggestions are less than 31:
'0 \* 0 != 0'
'long calculation failed'

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3108)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware and @yuvalsw)

___
*[`corelib/src/integer.cairo` line 1124 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3108#-NV3aTGcA5EopZhFck7M:-NV4TAX04CxNTBmcQk_3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/72edd72d896af62aa52ec386583a30ec8789e3dd/corelib/src/integer.cairo#L1124)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

#[derive(Copy, Drop, PartialEq, Serde)]
struct u512 {
    limb0: u128,
    limb1: u128,
    limb2: u128,
    limb3: u128,
}

#[inline(always)]
fn u256_wide_mul_add_limb2_helper(ref value: u512, limb: u128) -> u128 nopanic {
    match u128_overflowing_add(value.limb2, limb) {
        Result::Ok(v) => {
            value.limb2 = v;
            0
        },
        Result::Err(v) => {
            value.limb2 = v;
            1
        },
    }
}

#[inline(always)]
fn u256_wide_mul_add_limb1_helper(ref value: u512, limb: u128) -> u128 nopanic {
    match u128_overflowing_add(value.limb1, limb) {
        Result::Ok(v) => {
            value.limb1 = v;
            0
        },
        Result::Err(v) => {
            value.limb1 = v;
            1
        },
    }
}

fn u256_wide_mul(a: u256, b: u256) -> u512 nopanic {
    let (limb1, limb0) = u128_wide_mul(a.low, b.low);
    let (limb3, limb2) = u128_wide_mul(a.high, b.high);
    let mut result = u512 { limb0, limb1, limb2, limb3 };

    let (ab_limb2_part, ab_limb1_part) = u128_wide_mul(a.low, b.high);
    let (ba_limb2_part, ba_limb1_part) = u128_wide_mul(b.low, a.high);

    let limb1_overflow1 = u256_wide_mul_add_limb1_helper(ref result, ab_limb1_part);
    let limb1_overflow2 = u256_wide_mul_add_limb1_helper(ref result, ba_limb1_part);
    // No overflow possible in this addition since both operands are 0/1.
    let limb1_overflow = u128_wrapping_add(limb1_overflow1, limb1_overflow2);

    let limb2_overflow1 = u256_wide_mul_add_limb2_helper(ref result, ab_limb2_part);
    let limb2_overflow2 = u256_wide_mul_add_limb2_helper(ref result, ba_limb2_part);
    let limb2_overflow3 = u256_wide_mul_add_limb2_helper(ref result, limb1_overflow);
    // No overflow possible in this additions since all operands are 0/1.
    let limb2_overflow = u128_wrapping_add(
        u128_wrapping_add(limb2_overflow1, limb2_overflow2), limb2_overflow3
    );

    // No overflow possible since the product of 2 u256s can't overflow a u512.
    value.limb3 = u128_wrapping_add(value.limb3, limb2_overflow);

    result
}
</blockquote></details>

Done.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3108#-:-NV4WHOTDTbagmJPhzAL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
