### PR TITLE
Introduce `cairo-lang-doc` crate and move all item doc/sig/md code there

### PR DESCRIPTION
**Pull request by mkaput**
**Stack**:
- #5904
- #5903
- #5900 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5900)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5900)* status: 1 of 15 files reviewed, 1 unresolved discussion (waiting on @mkaput)

___
*[`crates/cairo-lang-defs/src/db.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5900#-O0J2eak0bDZmbx0GSsv:-O0J2eak0bDZmbx0GSsw:b-834tlz) ([raw file](https://github.com/starkware-libs/cairo/blob/fcdd4b0560cf1f9fe7bcd668d898f0ba5b618dfb/crates/cairo-lang-defs/src/db.rs#L117)):*
> ```XML
>     fn module_dir(&self, module_id: ModuleId) -> Maybe<Directory>;
> 
>     // TODO(mkaput): Add tests.
> ```

why should doc be about items defs?

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5900)* status: 1 of 15 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-defs/src/db.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5900#-O0J2eak0bDZmbx0GSsv:-O0J9m607vHiqqx4s06t:b-k4k1xs) ([raw file](https://github.com/starkware-libs/cairo/blob/fcdd4b0560cf1f9fe7bcd668d898f0ba5b618dfb/crates/cairo-lang-defs/src/db.rs#L117)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why should doc be about items defs?
</blockquote></details>

I don't understand your question and why it's asked at the removed place :/ Could you please elaborte?

**Review by piotmag769 — COMMENTED** [review]
:lgtm:

> Reviewed 7 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5900#-:-O0JAfd_ALoL9ZyyqoZS:bnfp4nl)* status: 7 of 15 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-defs/src/db.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5900#-O0J2eak0bDZmbx0GSsv:-O0JA7xg1KU-4BgBgXdm:bbc5h5z) ([raw file](https://github.com/starkware-libs/cairo/blob/fcdd4b0560cf1f9fe7bcd668d898f0ba5b618dfb/crates/cairo-lang-defs/src/db.rs#L117)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I don't understand your question and why it's asked at the removed place :/ Could you please elaborte?
</blockquote></details>

The item signatures are needed for docs, imo it's a correct place for that

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5900)* status: 7 of 15 files reviewed, 1 unresolved discussion (waiting on @orizi and @piotmag769)

___
*[`crates/cairo-lang-defs/src/db.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5900#-O0J2eak0bDZmbx0GSsv:-O0Jrnnm52_cPJKAh_E3:bnk4i8a) ([raw file](https://github.com/starkware-libs/cairo/blob/fcdd4b0560cf1f9fe7bcd668d898f0ba5b618dfb/crates/cairo-lang-defs/src/db.rs#L117)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i mean - why does the new db exists at all - and it isn't just a basic part of the defs db.
</blockquote></details>

My primary reason is that the defs group doesn't quite sound like the place for these queries. It's not something that everybody needs, and definitely not something that `cairo-lang-compiler::RootDatabase` uses. So this is why I moved it into a separate group.

Then I moved this into a separate crate, because this thought can go further: why does doc processing logic (which will grow esp. for signatures) has to be shipped in `cairo-lang-defs` and thus be compiled just to end up being unused. We already kinda do this approach given all the crates that the compiler is chopped into.

---

But I'm not 100% pushing for the current approach and I can put this back in if there are good reasons.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5900)* status: 7 of 15 files reviewed, 1 unresolved discussion (waiting on @mkaput and @piotmag769)

___
*[`crates/cairo-lang-defs/src/db.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5900#-O0J2eak0bDZmbx0GSsv:-O0JulvfDif940KTQwqK:bhxk4vc) ([raw file](https://github.com/starkware-libs/cairo/blob/fcdd4b0560cf1f9fe7bcd668d898f0ba5b618dfb/crates/cairo-lang-defs/src/db.rs#L117)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

My primary reason is that the defs group doesn't quite sound like the place for these queries. It's not something that everybody needs, and definitely not something that `cairo-lang-compiler::RootDatabase` uses. So this is why I moved it into a separate group.

Then I moved this into a separate crate, because this thought can go further: why does doc processing logic (which will grow esp. for signatures) has to be shipped in `cairo-lang-defs` and thus be compiled just to end up being unused. We already kinda do this approach given all the crates that the compiler is chopped into.

---

But I'm not 100% pushing for the current approach and I can put this back in if there are good reasons.
</blockquote></details>

do you think there should be diagnostics on documentation?
`///` that is in the wrong spot - and so on?
if so - root may logically know about it.

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5900)* status: 7 of 15 files reviewed, 1 unresolved discussion (waiting on @orizi and @piotmag769)

___
*[`crates/cairo-lang-defs/src/db.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5900#-O0J2eak0bDZmbx0GSsv:-O0Jw0ZMDIQc9Q8uZUGX:b-pps2vf) ([raw file](https://github.com/starkware-libs/cairo/blob/fcdd4b0560cf1f9fe7bcd668d898f0ba5b618dfb/crates/cairo-lang-defs/src/db.rs#L117)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

do you think there should be diagnostics on documentation?
`///` that is in the wrong spot - and so on?
if so - root may logically know about it.
</blockquote></details>

Interesting take.

`///` has to stop being a comment token and instead to be a separate AST element (in Rust it's called _DocComment_ etc.), that **is not** a trivium. This will solve the _`///` is in wrong spot_ problem on its own, and will play nicely with the `#[doc]` attribute idea.

The trick is what about contents of the documentation. I sense two potential errors there:
1. Invalid Markdown markup.
2. Invalid references to code items.

For reference, these two errors are only validated by `rustdoc` and this is why we run rustdoc in CI.

Technically the DocGroup would be the logical place to put diagnostics for this. I also tend to like the idea of validating docs while compiling regular Code (so unlike Rust) to enforce some uniformity in the ecosystem.

But what could block the RootDatabase from just pulling DocGroup when such diagnostics will appear? So I think this actually is another reason to extract this logic from `DefsGroup` -- to avoid cluttering it with even more code.

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5900)* status: 7 of 15 files reviewed, 2 unresolved discussions (waiting on @mkaput, @orizi, and @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5900#-O0JzpUi2HSp8f4aE1uP:-O0JzpUi2HSp8f4aE1uQ:byde601) (no related file):*
Blocked because @piotmag769 cannot be set as a codeowner yet.

___

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5900)* status: 7 of 15 files reviewed, 2 unresolved discussions (waiting on @orizi and @piotmag769)

___
*[`crates/cairo-lang-defs/src/db.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5900#-O0J2eak0bDZmbx0GSsv:-O0K0UWs0CGIWbD7YHln:bs018jr) ([raw file](https://github.com/starkware-libs/cairo/blob/cdaceb909ccf0644b7e385669d2c48417ceb90d4/crates/cairo-lang-defs/src/db.rs#L117)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Interesting take.

`///` has to stop being a comment token and instead to be a separate AST element (in Rust it's called _DocComment_ etc.), that **is not** a trivium. This will solve the _`///` is in wrong spot_ problem on its own, and will play nicely with the `#[doc]` attribute idea.

The trick is what about contents of the documentation. I sense two potential errors there:
1. Invalid Markdown markup.
2. Invalid references to code items.

For reference, these two errors are only validated by `rustdoc` and this is why we run rustdoc in CI.

Technically the DocGroup would be the logical place to put diagnostics for this. I also tend to like the idea of validating docs while compiling regular Code (so unlike Rust) to enforce some uniformity in the ecosystem.

But what could block the RootDatabase from just pulling DocGroup when such diagnostics will appear? So I think this actually is another reason to extract this logic from `DefsGroup` -- to avoid cluttering it with even more code.
</blockquote></details>

Oh, and I want to (at least temporarily) call cairo formatter from the `get_item_signature` query. The PR will be pushed later today :)

**Review by piotmag769 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5900#-:-O0KSUuZ74OHFvAm6vhP:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)

**Pull request merged**
