### PR TITLE
feat: add unwrap_or and unwrap_default

### PR DESCRIPTION
**Pull request by Eikix**
- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4203)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4203)* status: all files reviewed, 1 unresolved discussion (waiting on @Eikix)

___
*[`corelib/src/option.cairo` line 22 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4203#-NgYQ2fgDs3ogD0b1zlA:-NgYQ2fgDs3ogD0b1zlB:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/575991bac521fd0f0391d006221cd3dcb7cb3ac1/corelib/src/option.cairo#L22)):*
> ```Cairo
>     fn unwrap_or<+Drop<T>>(self: Option<T>, default: T) -> T;
>     /// Returns x if Option is Option::some(x), otherwise returns Default::<T>::default()
>     fn unwrap_or_default<+Default<T>>(self: Option<T>) -> T;
> ```





_Suggestion:_
```Cairo
    fn is_none(self: @Option<T>) -> bool;
    /// Returns x if Option is Option::some(x), otherwise returns the provided default value.
    fn unwrap_or<+Drop<T>>(self: Option<T>, default: T) -> T;
    /// Returns x if Option is Option::some(x), otherwise returns Default::<T>::default().
    fn unwrap_or_default<+Default<T>>(self: Option<T>) -> T;
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4203)* status: all files reviewed, 1 unresolved discussion (waiting on @Eikix)

___
*[`corelib/src/option.cairo` line 22 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4203#-NgYZgw-5ND7KVT1Sk0U:-NgYZgw-5ND7KVT1Sk0V:b-89xs5u) ([raw file](https://github.com/starkware-libs/cairo/blob/904b7b4ceac3611d3932397066539ebee35448d7/corelib/src/option.cairo#L22)):*
> ```Cairo
>     fn unwrap_or<+Drop<T>>(self: Option<T>, default: T) -> T;
>     /// Returns x if Option is Option::some(x), otherwise returns Default::<T>::default().
>     fn unwrap_or_default<+Default<T>>(self: Option<T>) -> T;
> ```

just more conforming to the rest of the doc.



_Suggestion:_
```Cairo
    /// If `self` is `Option::Some(x)`, returns `x`. Otherwise, returns the provided default.
    fn unwrap_or<+Drop<T>>(self: Option<T>, default: T) -> T;
    /// If `self` is `Option::Some(x)`, returns `x`. Otherwise, returns `Default::<T>::default()`.
    fn unwrap_or_default<+Default<T>>(self: Option<T>) -> T;
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4203#-:-NgZKzY69ksHXLsFl_x4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Eikix)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4203#-:-NgZLEaN4jO8EXIS-pYY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Eikix)

**Pull request merged**
