### PR TITLE
Fix divmod

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
Signed-off-by: Dori Medini <dori@starkware.co>

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1308)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1308)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1308#-NJA_Mn0-iCcBXg9P_BI:-NJA_Mn0-iCcBXg9P_BJ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/75a8fb4289d13240a74cdaec0acbe1018e373f6e/crates/sierra_to_casm/src/invocations/uint128.rs#L123)):*
> ```XML
>         }
>         IntOperator::DivMod => {
>             let ui64 = BigInt::from(2).pow(64);
> ```





_Suggestion:_
```XML
u64_bound
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1308)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @orizi)

___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1308#-NJA_Mn0-iCcBXg9P_BI:-NJBDiRO1WhZEQsTWzdz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/75a8fb4289d13240a74cdaec0acbe1018e373f6e/crates/sierra_to_casm/src/invocations/uint128.rs#L123)):*
> ```XML
>         }
>         IntOperator::DivMod => {
>             let ui64 = BigInt::from(2).pow(64);
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1308)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 179 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1308#-NJdo3l884S9z33gsCHT:-NJdo3l90r_r11qcGcYF:bdssqvq) ([raw file](https://github.com/starkware-libs/cairo/blob/c6671b064b0952a63ba02808ff0ba96d15ea84ec/crates/sierra_to_casm/src/invocations/uint128.rs#L179)):*
> ```XML
>                 alloc u64_bound_minus_b_or_q;
>                 alloc q_is_small;
>                 alloc allocated_u64_bound; // Can't use immediate value on LHS of assert.
> ```

on the left side immediates should work - not in destination.



_Code quote:_
```XML
                alloc allocated_u64_bound; // Can't use immediate value on LHS of assert.
                assert allocated_u64_bound = u64_bound;
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1308#-:-NJf1gjgAmyVDY05M1PE:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 212 at r6](https://reviewable.io/reviews/starkware-libs/cairo/1308#-NJf1Vnw7I5kJn6QjC9s:-NJf1Vnw7I5kJn6QjC9t:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/70259ae75c61373dec431d6bc75ddf6a81ae42e2/crates/sierra_to_casm/src/invocations/uint128.rs#L212)):*
> ```XML
>             );
> 
>             if !awaiting_relocations.is_empty() {
> ```





_Suggestion:_
```XML
            assert!(awaiting_relocations.is_empty(), "Malformed casm builder usage (no non-fallthrough branch in divmod).");
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1308)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 212 at r6](https://reviewable.io/reviews/starkware-libs/cairo/1308#-NJf1Vnw7I5kJn6QjC9s:-NJfEz-L1Lod6kSk46Cr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/70259ae75c61373dec431d6bc75ddf6a81ae42e2/crates/sierra_to_casm/src/invocations/uint128.rs#L212)):*
> ```XML
>             );
> 
>             if !awaiting_relocations.is_empty() {
> ```

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1308)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
