### PR TITLE
Added wrong number of argument error in starknet plugin

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1492)

### CODE REVIEW

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1492#-:-NKDo2xq-VgCVIgyTRGH:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/starknet/src/plugin.rs` line 208 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1492#-NKDnmGc12ecMw9C6r51:-NKDnmGd2R-LuLHa3il-:b-sgbi1n) ([raw file](https://github.com/starkware-libs/cairo/blob/cf8bf53f600f37d9b371b9ef39940b06a1634868/crates/starknet/src/plugin.rs#L208)):*
> ```XML
>     };
> 
>     let oog_err = "'OOG'";
> ```

I guess we want the error format to be consistent.



_Suggestion:_
```XML
Out of gas
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1492)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/starknet/src/plugin.rs` line 208 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1492#-NKDnmGc12ecMw9C6r51:-NKDsGnY45Ki19-BwF-h:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cf8bf53f600f37d9b371b9ef39940b06a1634868/crates/starknet/src/plugin.rs#L208)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I guess we want the error format to be consistent.
</blockquote></details>

Done.

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1492)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by yuvalsw — COMMENTED** [review]
> Dismissed @ilyalesokhin-starkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1492)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
