### PR TITLE
Add uint128 sqrt

### PR DESCRIPTION
**Pull request by amosStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1902)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 11 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1902)* status: 11 of 14 files reviewed, 6 unresolved discussions (waiting on @amosStarkware)

___
*[`corelib/test.cairo` line 261 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1902#-NNa9QbDEQNM0Xk6KQz7:-NNa9QbDEQNM0Xk6KQz8:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/93435bbf1ec3e4224b08a615aab5e75dec6f8e66/corelib/test.cairo#L261)):*
> ```Cairo
>     assert(u128_sqrt(9_u128) == 3_u128, 'u128_sqrt(9) == 3');
>     assert(u128_sqrt(10_u128) == 3_u128, 'u128_sqrt(10) == 3');
>     assert(u128_sqrt(1_u128) == 3_u128, 'u128_sqrt(1) == 1');
> ```





_Suggestion:_
```Cairo
    assert(u128_sqrt(1_u128) == 1_u128, 'u128_sqrt(1) == 1');
```
___
*[`corelib/test.cairo` line 262 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1902#-NNa9TVN9Tcbhvd96G6J:-NNa9TVN9Tcbhvd96G6K:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/93435bbf1ec3e4224b08a615aab5e75dec6f8e66/corelib/test.cairo#L262)):*
> ```Cairo
>     assert(u128_sqrt(10_u128) == 3_u128, 'u128_sqrt(10) == 3');
>     assert(u128_sqrt(1_u128) == 3_u128, 'u128_sqrt(1) == 1');
>     assert(u128_sqrt(0_u128) == 2_u128, 'u128_sqrt(0) == 0');
> ```





_Suggestion:_
```Cairo
assert(u128_sqrt(0_u128) == 0_u128, 'u128_sqrt(0) == 0');
```
___
*[`crates/cairo-lang-casm/src/inline.rs` line 200 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1902#-NNa9Y0SE8Rlz7D7YAtq:-NNa9Y0SE8Rlz7D7YAtr:b-mvwjn3) ([raw file](https://github.com/starkware-libs/cairo/blob/93435bbf1ec3e4224b08a615aab5e75dec6f8e66/crates/cairo-lang-casm/src/inline.rs#L200)):*
> ```XML
>     ($ctx:ident, %{ ( memory $dest:tt) = sqrt ( memory $value:tt ) %} $($tok:tt)*) => {
>        $ctx.current_hints.push($crate::hints::Hint::SquareRoot{
>            value: $crate::res!($value),
> ```

not required - just use like all the other hints:
hint SquareRoot { value: <var_name> } into { dst: <var_name> }

add just a print - not an inliner



_Code quote:_
```XML
    ($ctx:ident, %{ ( memory $dest:tt) = sqrt ( memory $value:tt ) %} $($tok:tt)*) => {
       $ctx.current_hints.push($crate::hints::Hint::SquareRoot{
           value: $crate::res!($value),
           dest: $crate::deref!($dest),
       });
       $crate::casm_extend!($ctx, $($tok)*)
   };
   ($ctx:ident, %{ ( memory $dest:tt) = sqrt ( $value:tt ) %} $($tok:tt)*) => {
    $ctx.current_hints.push($crate::hints::Hint::SquareRoot{
        value: $crate::res!($value),
        dest: $crate::deref!($dest),
    });
    $crate::casm_extend!($ctx, $($tok)*)
};
```
___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1902#-NNaA053-ly3yt5U_hCD:-NNaA053-ly3yt5U_hCE:b-r238y0) ([raw file](https://github.com/starkware-libs/cairo/blob/93435bbf1ec3e4224b08a615aab5e75dec6f8e66/crates/cairo-lang-casm/src/hints/mod.rs#L34)):*
> ```XML
>     SquareRoot {
>         value: ResOperand,
>         dest: CellRef,
> ```

conform to other hints.



_Suggestion:_
```XML

    SquareRoot {
        value: ResOperand,
        dst: CellRef,
    },
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/uint128.rs` line 325 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1902#-NNaAG1s8vYJ0NGQXZvJ:-NNaAG1s8vYJ0NGQXZvK:b-l11g0r) ([raw file](https://github.com/starkware-libs/cairo/blob/93435bbf1ec3e4224b08a615aab5e75dec6f8e66/crates/cairo-lang-sierra/src/extensions/modules/uint128.rs#L325)):*
> ```XML
>                 },
>                 ParamSignature {
>                     ty: ty.clone(),
> ```

don't allow consts - as you use it as deferred.



_Suggestion:_
```XML
                ParamSignature::new(ty.clone()),
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/uint128.rs` line 352 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1902#-NNaBUro4xgucURI22Cx:-NNaBUro4xgucURI22Cy:bg0vybq) ([raw file](https://github.com/starkware-libs/cairo/blob/93435bbf1ec3e4224b08a615aab5e75dec6f8e66/crates/cairo-lang-sierra-to-casm/src/invocations/uint128.rs#L352)):*
> ```XML
> 
>         casm_build_extend! {casm_builder,
>         tempvar root;
> ```

if you promise (as you do) in the signature that the result is in `new temp var 0` you must declare all of you're other temp vars after it.



_Code quote:_
```XML
        tempvar root;
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1902)* status: 11 of 14 files reviewed, 7 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/uint128.rs` line 358 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1902#-NNbTVs589bLOvANe5Ro:-NNbTVs589bLOvANe5Rp:b-ldzcjk) ([raw file](https://github.com/starkware-libs/cairo/blob/93435bbf1ec3e4224b08a615aab5e75dec6f8e66/crates/cairo-lang-sierra-to-casm/src/invocations/uint128.rs#L358)):*
> ```XML
>         const u64_upper_fixer = u128::MAX - u64::MAX as u128;
>         tempvar fixed_root = root + u64_upper_fixer;
>         assert root = *(range_check++);
> ```

had some time in the sessions:

Get root  = sqrt(value) by hint:
Use one calc + range checks to assert root <= 2**125. (just to allow this to work up to u250, because why not)
Calc root**2
Calc value - root**2 - and range check (root**2 <= value)
Calc (2*root) - (value - root**2) == (root**2 + 2*root + 1) - (value + 1) == (root + 1)**2 - value -1
And range check (therefore (root + 1)**2 - value -1 >= 0 → (root + 1)**2 - value > 0 → (root + 1)**2 > value

this should be enough to prove root*root <= value < (root+1)*(root+1)



_Code quote:_
```XML
        hint SquareRoot { value: x} into { dest: root };

        // Assert root < 2^64 by asserting: root + (2**128-1) - (2**64-1) < 2**128.
        const u64_upper_fixer = u128::MAX - u64::MAX as u128;
        tempvar fixed_root = root + u64_upper_fixer;
        assert root = *(range_check++);
        assert fixed_root = *(range_check++);

        // Assert x >= root^2
        tempvar root_squared = root * root;
        tempvar x_minus_root_squared = x - root_squared;
        assert x_minus_root_squared = *(range_check++);

        // Assert (root + 1)^2 > x
        tempvar root_times_two = root + root;
        // if ((root + 1)^2) - (x+1) in [0, 2^128) then (root + 1)^2 > x.
        // ((root + 1)^2) - (x+1) = root^2 + 2*root + 1 - x - 1 = root^2 + 2*root -x
        tempvar root_times_two_plus_root_squared = root_squared + root_times_two;
        tempvar diff = root_times_two_plus_root_squared - x;
        assert diff = *(range_check++);
    };
```

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1902)* status: 11 of 14 files reviewed, 7 unresolved discussions (waiting on @amosStarkware and @orizi)

___
*[`corelib/test.cairo` line 261 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1902#-NNa9QbDEQNM0Xk6KQz7:-NNfNBIND36W2fgtYg0V:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/93435bbf1ec3e4224b08a615aab5e75dec6f8e66/corelib/test.cairo#L261)):*
> ```Cairo
>     assert(u128_sqrt(9_u128) == 3_u128, 'u128_sqrt(9) == 3');
>     assert(u128_sqrt(10_u128) == 3_u128, 'u128_sqrt(10) == 3');
>     assert(u128_sqrt(1_u128) == 3_u128, 'u128_sqrt(1) == 1');
> ```

Done.
___
*[`corelib/test.cairo` line 262 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1902#-NNa9TVN9Tcbhvd96G6J:-NNfNE_i8r-v7ewOB2OY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/93435bbf1ec3e4224b08a615aab5e75dec6f8e66/corelib/test.cairo#L262)):*
> ```Cairo
>     assert(u128_sqrt(10_u128) == 3_u128, 'u128_sqrt(10) == 3');
>     assert(u128_sqrt(1_u128) == 3_u128, 'u128_sqrt(1) == 1');
>     assert(u128_sqrt(0_u128) == 2_u128, 'u128_sqrt(0) == 0');
> ```

Done.
___
*[`crates/cairo-lang-casm/src/inline.rs` line 200 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1902#-NNa9Y0SE8Rlz7D7YAtq:-NNfO7HM6deL319guRou:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/93435bbf1ec3e4224b08a615aab5e75dec6f8e66/crates/cairo-lang-casm/src/inline.rs#L200)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

not required - just use like all the other hints:
hint SquareRoot { value: <var_name> } into { dst: <var_name> }

add just a print - not an inliner
</blockquote></details>

Done.
___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1902#-NNaA053-ly3yt5U_hCD:-NNfPGkr1p4Vcn9xDwxI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/93435bbf1ec3e4224b08a615aab5e75dec6f8e66/crates/cairo-lang-casm/src/hints/mod.rs#L34)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

conform to other hints.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/uint128.rs` line 325 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1902#-NNaAG1s8vYJ0NGQXZvJ:-NNfPbmz7okI5oghPU-M:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/93435bbf1ec3e4224b08a615aab5e75dec6f8e66/crates/cairo-lang-sierra/src/extensions/modules/uint128.rs#L325)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

don't allow consts - as you use it as deferred.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/uint128.rs` line 352 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1902#-NNaBUro4xgucURI22Cx:-NNfPhz497nSxylYgC3Q:b-t20n8n) ([raw file](https://github.com/starkware-libs/cairo/blob/93435bbf1ec3e4224b08a615aab5e75dec6f8e66/crates/cairo-lang-sierra-to-casm/src/invocations/uint128.rs#L352)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

if you promise (as you do) in the signature that the result is in `new temp var 0` you must declare all of you're other temp vars after it.
</blockquote></details>

It's already the first though?
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/uint128.rs` line 358 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1902#-NNbTVs589bLOvANe5Ro:-NNfveSx7dBBZ6q2nAcN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/93435bbf1ec3e4224b08a615aab5e75dec6f8e66/crates/cairo-lang-sierra-to-casm/src/invocations/uint128.rs#L358)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

had some time in the sessions:

Get root  = sqrt(value) by hint:
Use one calc + range checks to assert root <= 2**125. (just to allow this to work up to u250, because why not)
Calc root**2
Calc value - root**2 - and range check (root**2 <= value)
Calc (2*root) - (value - root**2) == (root**2 + 2*root + 1) - (value + 1) == (root + 1)**2 - value -1
And range check (therefore (root + 1)**2 - value -1 >= 0 → (root + 1)**2 - value > 0 → (root + 1)**2 > value

this should be enough to prove root*root <= value < (root+1)*(root+1)
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 13 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1902)* status: 13 of 14 files reviewed, 3 unresolved discussions (waiting on @amosStarkware)

___
*[`corelib/test.cairo` line 294 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1902#-NNgG50yE8zDZ6z9y3cK:-NNgG50yE8zDZ6z9y3cL:b5nvwsg) ([raw file](https://github.com/starkware-libs/cairo/blob/2e5a380210af7ad292aeffb8affd2ed41cff554d/corelib/test.cairo#L294)):*
> ```Cairo
>     assert((3_u128 ^ 6_u128) == 5_u128, '3 ^ 6 == 5');
>     assert(u128_sqrt(9_u128) == 3_u128, 'u128_sqrt(9) == 3');
>     assert(u128_sqrt(10_u128) == 3_u128, 'u128_sqrt(10) == 3');
> ```

add some larger examples. (close to the actual limit)



_Code quote:_
```Cairo
    assert(u128_sqrt(10_u128) == 3_u128, 'u128_sqrt(10) == 3');
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/uint128.rs` line 264 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1902#-NNgGIxqDT_ALRoLU_I8:-NNgGIxqDT_ALRoLU_I9:baqa2fa) ([raw file](https://github.com/starkware-libs/cairo/blob/2e5a380210af7ad292aeffb8affd2ed41cff554d/crates/cairo-lang-sierra/src/extensions/modules/uint128.rs#L264)):*
> ```XML
> #[derive(Default)]
> pub struct Uint128SquareRootLibfunc {}
> impl NoGenericArgsGenericLibfunc for Uint128SquareRootLibfunc {
> ```

move this to uint.rs file as a generic - as it works for all.



_Code quote:_
```XML
/// Libfunc for u128 square root.
#[derive(Default)]
pub struct Uint128SquareRootLibfunc {}
impl NoGenericArgsGenericLibfunc for Uint128SquareRootLibfunc {
    const STR_ID: &'static str = "u128_sqrt";

    fn specialize_signature(
        &self,
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/uint128.rs` line 352 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1902#-NNaBUro4xgucURI22Cx:-NNgGayv1ZgBeTpsJ8xx:b-ot7xja) ([raw file](https://github.com/starkware-libs/cairo/blob/93435bbf1ec3e4224b08a615aab5e75dec6f8e66/crates/cairo-lang-sierra-to-casm/src/invocations/uint128.rs#L352)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

It's already the first though?
</blockquote></details>

i meant - declare it after all the rest - so it is on top of stack.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1902)* status: 13 of 14 files reviewed, 4 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/uint128.rs` line 400 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1902#-NNgH-5FAlctUzV-gVcT:-NNgH-5FAlctUzV-gVcU:b-9x3njt) ([raw file](https://github.com/starkware-libs/cairo/blob/2e5a380210af7ad292aeffb8affd2ed41cff554d/crates/cairo-lang-sierra-to-casm/src/invocations/uint128.rs#L400)):*
> ```XML
>         // Assert (root + 1)^2 > value.
>         tempvar root_times_two = root + root;
>         // let us notice that (root + 1)^2 - 1 - value = 2*root - (value - root^2).
> ```

add all the stages in the doc.



_Code quote:_
```XML
        // let us notice that (root + 1)^2 - 1 - value = 2*root - (value - root^2).
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1902)* status: 13 of 14 files reviewed, 5 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/uint128.rs` line 401 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1902#-NNgTQEL23fEJBFfWozL:-NNgTQEL23fEJBFfWozM:b2678vi) ([raw file](https://github.com/starkware-libs/cairo/blob/2e5a380210af7ad292aeffb8affd2ed41cff554d/crates/cairo-lang-sierra-to-casm/src/invocations/uint128.rs#L401)):*
> ```XML
>         tempvar root_times_two = root + root;
>         // let us notice that (root + 1)^2 - 1 - value = 2*root - (value - root^2).
>         tempvar diff = root_times_two + value_minus_root_squared;
> ```

sign mistake.



_Suggestion:_
```XML
        tempvar diff = root_times_two - value_minus_root_squared;
```

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1902)* status: 4 of 15 files reviewed, 5 unresolved discussions (waiting on @amosStarkware and @orizi)

___
*[`corelib/test.cairo` line 294 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1902#-NNgG50yE8zDZ6z9y3cK:-NNgMDRF2f_nZIlDae3d:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2e5a380210af7ad292aeffb8affd2ed41cff554d/corelib/test.cairo#L294)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add some larger examples. (close to the actual limit)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/uint128.rs` line 264 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1902#-NNgGIxqDT_ALRoLU_I8:-NNkNUzw8s6U9fcoGhnj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2e5a380210af7ad292aeffb8affd2ed41cff554d/crates/cairo-lang-sierra/src/extensions/modules/uint128.rs#L264)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

move this to uint.rs file as a generic - as it works for all.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/uint128.rs` line 352 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1902#-NNaBUro4xgucURI22Cx:-NNkOVXc0rS35qtwqV4g:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/93435bbf1ec3e4224b08a615aab5e75dec6f8e66/crates/cairo-lang-sierra-to-casm/src/invocations/uint128.rs#L352)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i meant - declare it after all the rest - so it is on top of stack.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/uint128.rs` line 400 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1902#-NNgH-5FAlctUzV-gVcT:-NNkOc1y0gRLkSFlIJL4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2e5a380210af7ad292aeffb8affd2ed41cff554d/crates/cairo-lang-sierra-to-casm/src/invocations/uint128.rs#L400)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add all the stages in the doc.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/uint128.rs` line 401 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1902#-NNgTQEL23fEJBFfWozL:-NNkOgkL1ICNvDFHWANN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2e5a380210af7ad292aeffb8affd2ed41cff554d/crates/cairo-lang-sierra-to-casm/src/invocations/uint128.rs#L401)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

sign mistake.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1902#-:-NNlCopEBuJbHGbWzEwp:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/uint.rs` line 330 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1902#-NNlBquG-9qRDaxvpisu:-NNlBquG-9qRDaxvpisv:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/be0314416c70c07cc0a2dce2792d7515047002b3/crates/cairo-lang-sierra-to-casm/src/invocations/uint.rs#L330)):*
> ```XML
>     add_input_variables! {casm_builder,
>         buffer(3) range_check;
>         deref value;
> ```





_Suggestion:_
```XML
    add_input_variables! {casm_builder,
        buffer(3) range_check;
        deref value;
    };

    casm_build_extend! {casm_builder,
        let orig_range_check = range_check;
        tempvar fixed_root;
        tempvar root_squared;
        tempvar value_minus_root_squared;
        tempvar root_times_two;
        tempvar diff;
        tempvar root;

        // Calculate the square root.
        hint SquareRoot { value: value} into { dst: root };

        // Assert root is in [0, 2**125) by asserting:
        // (root + (2**128-1) - (2**125-1)) is in [0, 2**128) and root is in [0, 2**128).
        // The second assertion is needed because if root is very large (e.g., P - 1) the first
        // assertion may be true.
        const u125_upper_fixer = BigInt::from(u128::MAX - (u128::pow(2, 125) - 1)) as BigInt;
        assert fixed_root = root + u125_upper_fixer;
        assert root = *(range_check++);
        assert fixed_root = *(range_check++);
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/uint.rs` line 362 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1902#-NNlCVsE3ORIVcQ11JDD:-NNlCVsE3ORIVcQ11JDE:bv9gu5m) ([raw file](https://github.com/starkware-libs/cairo/blob/be0314416c70c07cc0a2dce2792d7515047002b3/crates/cairo-lang-sierra-to-casm/src/invocations/uint.rs#L362)):*
> ```XML
> 
>         // Assert value is in [0, (root + 1)^2 ) by asserting (2*root - (value - root^2)) is in
>         // [0, 2**128). this is equivalent because
> ```

be consistent



_Suggestion:_
```XML
        // Assert value is in [0, (root + 1)**2) by asserting (2*root - (value - root**2)) is in
        // [0, 2**128). this is equivalent because
        // (root + 1)**2 - 1 - value = 2*root - (value - root**2).
```

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1902)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/uint.rs` line 330 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1902#-NNlBquG-9qRDaxvpisu:-NNlGvUN2A3jr28eYxGN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/be0314416c70c07cc0a2dce2792d7515047002b3/crates/cairo-lang-sierra-to-casm/src/invocations/uint.rs#L330)):*
> ```XML
>     add_input_variables! {casm_builder,
>         buffer(3) range_check;
>         deref value;
> ```

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/uint.rs` line 362 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1902#-NNlCVsE3ORIVcQ11JDD:-NNlFxTj7S0FtO1MEHCn:b-8cj9xv) ([raw file](https://github.com/starkware-libs/cairo/blob/be0314416c70c07cc0a2dce2792d7515047002b3/crates/cairo-lang-sierra-to-casm/src/invocations/uint.rs#L362)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

be consistent
</blockquote></details>

changed ^ -> **
the spaces are their intentionally because IMO it's less readable without them, but if you want I'll delete them.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1902)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
