### PR TITLE
Add ArrayIter implementation of IntoIter

### PR DESCRIPTION
**Pull request by Tomer-StarkWare**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5928)

### CODE REVIEW

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5928)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi, @Tomer-StarkWare, and @TomerStarkware)

___
*[`corelib/src/array.cairo` line 431 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5928#-O0iH0cr2fNYq_s41XfJ:-O0iH0cr2fNYq_s41XfK:b-ug6zo8) ([raw file](https://github.com/starkware-libs/cairo/blob/4732a097ae73b37fc20f9b95f9b2afc58dadf1cb/corelib/src/array.cairo#L431)):*
> ```Cairo
>         self
>     }
> }
> ```

Same for span. 



_Code quote:_
```Cairo
#[feature("collections-into-iter")]
impl ArrayIterIntoIterator<T> of core::iter::IntoIterator<ArrayIter<T>> {
    type IntoIter = ArrayIter<T>;
    impl Iterator = ArrayIterator<T>;
    fn into_iter(self: ArrayIter<T>) -> ArrayIter<T> {
        self
    }
}
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5928)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @Tomer-StarkWare and @TomerStarkware)

___
*[`corelib/src/array.cairo` line 425 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5928#-O0iIWMz3a8tyvFj065h:-O0iIWMz3a8tyvFj065i:bav6usj) ([raw file](https://github.com/starkware-libs/cairo/blob/4732a097ae73b37fc20f9b95f9b2afc58dadf1cb/corelib/src/array.cairo#L425)):*
> ```Cairo
> 
> #[feature("collections-into-iter")]
> impl ArrayIterIntoIterator<T> of core::iter::IntoIterator<ArrayIter<T>> {
> ```

Do instead an implementation for any T with Iterators.
Not 1 by 1.

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5928)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware, @orizi, and @TomerStarkware)

___
*[`corelib/src/array.cairo` line 425 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5928#-O0iIWMz3a8tyvFj065h:-O0iZMFeCRsZjtwzJdxU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4732a097ae73b37fc20f9b95f9b2afc58dadf1cb/corelib/src/array.cairo#L425)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Do instead an implementation for any T with Iterators.
Not 1 by 1.
</blockquote></details>

Done.
___
*[`corelib/src/array.cairo` line 431 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5928#-O0iH0cr2fNYq_s41XfJ:-O0iZMYvEJxu4mczNU8C:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4732a097ae73b37fc20f9b95f9b2afc58dadf1cb/corelib/src/array.cairo#L431)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Same for span.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5928)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware, @Tomer-StarkWare, and @TomerStarkware)

___
*[`corelib/src/iter/traits/iterator.cairo` line 21 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5928#-O0ih3U5DdZMRuL4ncrt:-O0ih3U66ZGXBan_zwZr:b51ngpw) ([raw file](https://github.com/starkware-libs/cairo/blob/521d959c4f01e96dfc485ead5aa21f494df7295e/corelib/src/iter/traits/iterator.cairo#L21)):*
> ```Cairo
> impl IteratorIntoIterator<T, +Iterator<T>> of IntoIterator<T> {
>     type IntoIter = T;
>     impl Iterator = Iterator<T>;
> ```

Does it work without this line after implicit impl impl items?
If so, remove.
Else add name for the impl param and use it.

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5928)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware, @orizi, and @TomerStarkware)

___
*[`corelib/src/iter/traits/iterator.cairo` line 21 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5928#-O0ih3U5DdZMRuL4ncrt:-O0jIsgC91FHGVfngu4p:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/521d959c4f01e96dfc485ead5aa21f494df7295e/corelib/src/iter/traits/iterator.cairo#L21)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Does it work without this line after implicit impl impl items?
If so, remove.
Else add name for the impl param and use it.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5928#-:-O0jM4zU1sbnKzoZLQZO:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5928)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5928#-:-O0jtF1LDlGtNEB4UYnR:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

**Pull request merged**
