### PR TITLE
Add U96Guarantee and into_u96_guarantee.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5728)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5728)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/circuit.cairo` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5728#-Nzced7D24gSALCKvjj7:-Nzced7D24gSALCKvjj8:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/cd513180716e94fe40af90731de50210491db262/corelib/src/circuit.cairo#L46)):*
> ```Cairo
> extern fn into_u96_guarantee<T>(val: T) -> U96Guarantee nopanic;
> 
> /// A guaranteed that a value can fit in a u96.
> ```





_Suggestion:_
```Cairo
/// A value that is guaranteed to fit in a u96.
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/circuit.rs` line 571 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5728#-NzcemBh9iD9qCXydNJV:-NzcemBh9iD9qCXydNJW:b-7jl271) ([raw file](https://github.com/starkware-libs/cairo/blob/cd513180716e94fe40af90731de50210491db262/crates/cairo-lang-sierra/src/extensions/modules/circuit.rs#L571)):*
> ```XML
> }
> 
> /// A guaranteed that a value can fit in a u96.
> ```

same.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/circuit.rs` line 967 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5728#-NzcfLanErVEu-tRY968:-NzcfLanErVEu-tRY969:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/cd513180716e94fe40af90731de50210491db262/crates/cairo-lang-sierra/src/extensions/modules/circuit.rs#L967)):*
> ```XML
>         Ok(reinterpret_cast_signature(ty, guarantee_ty))
>     }
> }
> ```





_Suggestion:_
```XML
#[derive(Default)]
pub struct IntoU96GuaranteeLibFunc {}
impl SignatureOnlyGenericLibfunc for IntoU96GuaranteeLibFunc {
    const STR_ID: &'static str = "into_u96_guarantee";

    fn specialize_signature(
        &self,
        context: &dyn SignatureSpecializationContext,
        ty: ConcreteTypeId,
    ) -> Result<LibfuncSignature, SpecializationError> {
        let range = Range::from_type(context, ty.clone())?;
        require(ange.lower.is_negative() && range.upper >= BigInt::one().shl(96))
        .ok_or(SpecializationError::UnsupportedGenericArg)?;

        let guarantee_ty = context.get_concrete_type(U96Guarantee::id(), &[])?;
        Ok(reinterpret_cast_signature(ty, guarantee_ty))
    }
}
```
___
*[`tests/e2e_test_data/libfuncs/circuit` line 581 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5728#-Nzcfs551OZvmkvk-j27:-Nzcfs551OZvmkvk-j28:b-7ql1sz) ([raw file](https://github.com/starkware-libs/cairo/blob/cd513180716e94fe40af90731de50210491db262/tests/e2e_test_data/libfuncs/circuit#L581)):*
> ```
> 
> //! > casm
> [ap + 0] = [fp + -7] + 20, ap++;
> ```

fixer

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra/src/extensions/modules/circuit.rs` line 967 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5728#-NzcfLanErVEu-tRY968:-NzchZpn4cPgUi7tf4Ht:b-yt6yv5) ([raw file](https://github.com/starkware-libs/cairo/blob/cd513180716e94fe40af90731de50210491db262/crates/cairo-lang-sierra/src/extensions/modules/circuit.rs#L967)):*
> ```XML
>         Ok(reinterpret_cast_signature(ty, guarantee_ty))
>     }
> }
> ```

hy not use an if?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5728)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/circuit.cairo` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5728#-Nzced7D24gSALCKvjj7:-Nzci23F7_OS9Fe_Qg95:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cd513180716e94fe40af90731de50210491db262/corelib/src/circuit.cairo#L46)):*
> ```Cairo
> extern fn into_u96_guarantee<T>(val: T) -> U96Guarantee nopanic;
> 
> /// A guaranteed that a value can fit in a u96.
> ```

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/circuit.rs` line 571 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5728#-NzcemBh9iD9qCXydNJV:-Nzci2RFDWzyRspuD2a7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cd513180716e94fe40af90731de50210491db262/crates/cairo-lang-sierra/src/extensions/modules/circuit.rs#L571)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

same.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5728)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/circuit.cairo` line 46 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5728#-NzcjYHyBjMpCCUNkR3g:-NzcjYHyBjMpCCUNkR3h:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ea0ffd00e8ca5e7177e82df44c93ded98c9d3812/corelib/src/circuit.cairo#L46)):*
> ```Cairo
> extern fn into_u96_guarantee<T>(val: T) -> U96Guarantee nopanic;
> 
> // A value that is guaranteed to fit in a u96.
> ```





_Suggestion:_
```Cairo
/// A value that is guaranteed to fit in a u96.
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/circuit.rs` line 573 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5728#-NzcjWCd8zcdYdRhttXy:-NzcjWCd8zcdYdRhttXz:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ea0ffd00e8ca5e7177e82df44c93ded98c9d3812/crates/cairo-lang-sierra/src/extensions/modules/circuit.rs#L573)):*
> ```XML
> // A value that is guaranteed to fit in a u96.
> // This value can only be dropped by being written to a 96bit range check.
> #[derive(Default)]
> ```





_Suggestion:_
```XML
/// A value that is guaranteed to fit in a u96.
/// This value can only be dropped by being written to a 96bit range check.
#[derive(Default)]
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5728)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/circuit.cairo` line 46 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5728#-NzcjYHyBjMpCCUNkR3g:-NzcmodeEsWp8uQ4Na4t:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ea0ffd00e8ca5e7177e82df44c93ded98c9d3812/corelib/src/circuit.cairo#L46)):*
> ```Cairo
> extern fn into_u96_guarantee<T>(val: T) -> U96Guarantee nopanic;
> 
> // A value that is guaranteed to fit in a u96.
> ```

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/circuit.rs` line 573 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5728#-NzcjWCd8zcdYdRhttXy:-Nzcmt-T14mqp-tD83ce:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ea0ffd00e8ca5e7177e82df44c93ded98c9d3812/crates/cairo-lang-sierra/src/extensions/modules/circuit.rs#L573)):*
> ```XML
> // A value that is guaranteed to fit in a u96.
> // This value can only be dropped by being written to a 96bit range check.
> #[derive(Default)]
> ```

Done.

**Pull request merged**
