### PR TITLE
added as expressions in parser

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5252)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 7 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5252)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @TomerStarkware, and @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/expr` line 71 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5252#-NsnVgRa7fU4k1R-GoAT:-NsnVgRb2JY9AIcer7nE:bb6zmhl) ([raw file](https://github.com/starkware-libs/cairo/blob/1b1c2721dd0dec95f8f7b0d461a9fd23388934ca/crates/cairo-lang-parser/src/parser_test_data/partial_trees/expr#L71)):*
> ```
> fn f() -> u32 {
>     ((foo() as Array<u8>) + 5,7 as u9);
>     
> ```

Line

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5252)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @orizi, and @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/expr` line 71 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5252#-NsnVgRa7fU4k1R-GoAT:-NsqfC_Z7007FpigsxOb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1b1c2721dd0dec95f8f7b0d461a9fd23388934ca/crates/cairo-lang-parser/src/parser_test_data/partial_trees/expr#L71)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Line
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5252)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @TomerStarkware, and @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/expr` line 70 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5252#-NsqtIq70xAZqYLpeHBF:-NsqtIq70xAZqYLpeHBG:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5f43360075fdda120ced17a37fa7aaf571b33aef/crates/cairo-lang-parser/src/parser_test_data/partial_trees/expr#L70)):*
> ```
> //! > cairo_code
> fn f() -> u32 {
>     ((foo() as Array<u8>) + 5,7 as u9);
> ```





_Suggestion:_
```
    ((foo() as Array<u8>) + 5, 7 as u9);
```

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 6 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5252)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware and @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1098 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5252#-NsrXdPkAN08H-FELRt5:-NsrXdPlDLsQA4SMs8Bc:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5f43360075fdda120ced17a37fa7aaf571b33aef/crates/cairo-lang-parser/src/parser.rs#L1098)):*
> ```XML
>         let mut expr = self.try_parse_atom_or_unary(lbrace_allowed)?;
> 
>         // If expr is [SyntaxKind::ExprTypeCast], we don't want to parse an operator.
> ```





_Suggestion:_
```XML
we don't allow any operator to follow immediately.
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5252)* status: 7 of 12 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @orizi, and @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/expr` line 70 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5252#-NsqtIq70xAZqYLpeHBF:-Nsr_XQSBVD-wh3fwTf8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5f43360075fdda120ced17a37fa7aaf571b33aef/crates/cairo-lang-parser/src/parser_test_data/partial_trees/expr#L70)):*
> ```
> //! > cairo_code
> fn f() -> u32 {
>     ((foo() as Array<u8>) + 5,7 as u9);
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5252)* status: 10 of 12 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware, @TomerStarkware, and @yuvalsw)

___
*[`crates/cairo-lang-syntax-codegen/src/cairo_spec.rs` line 40 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5252#-NsrluFk4vkzBLzukMvi:-NsrluFk4vkzBLzukMvj:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/031f1d676d76f166ddf70e67811f3a5aef8a9501/crates/cairo-lang-syntax-codegen/src/cairo_spec.rs#L40)):*
> ```XML
>         .node("InlineMacro")
>         .node("FixedSizeArray")
>         .node("TypeCast")
> ```





_Suggestion:_
```XML
        .node("TypeCoerce")
```

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5252)* status: 10 of 12 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware, @orizi, and @TomerStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5252#-Nsrnrr_0nxIb5eXBLm9:-Nsrnrr_0nxIb5eXBLmA:b-498fmv) (no related file):*
blocking until resolution of the syntax discussion

___

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5252)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5252#-:-NsrrK6nAABgYio_-UNz:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 9 files at r1, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5252#-:-Nss-G152gC8QAV6I0w0:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

**Comment by TomerStarkware** [comment]
irrelavant

**Pull request closed without merging**
