### PR TITLE
Resilient patterns

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3756)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3744** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3744" target="_blank">Graphite</a> 
    * **PR #3745** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3745" target="_blank">Graphite</a> 
      * **PR #3746** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3746" target="_blank">Graphite</a> 
        * **PR #3747** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3747" target="_blank">Graphite</a> 
          * **PR #3748** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3748" target="_blank">Graphite</a> 
            * **PR #3749** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3749" target="_blank">Graphite</a> 
              * **PR #3750** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3750" target="_blank">Graphite</a> 
                * **PR #3751** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3751" target="_blank">Graphite</a> 
                  * **PR #3752** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3752" target="_blank">Graphite</a> 
                    * **PR #3753** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3753" target="_blank">Graphite</a> 
                      * **PR #3754** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3754" target="_blank">Graphite</a> 
                        * **PR #3755** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3755" target="_blank">Graphite</a> 
                          * **PR #3756** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3756" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/3756?utm_source=stack-comment).

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3744** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3744" target="_blank">Graphite</a> 
    * **PR #3745** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3745" target="_blank">Graphite</a> 
      * **PR #3746** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3746" target="_blank">Graphite</a> 
        * **PR #3747** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3747" target="_blank">Graphite</a> 
          * **PR #3748** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3748" target="_blank">Graphite</a> 
            * **PR #3749** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3749" target="_blank">Graphite</a> 
              * **PR #3750** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3750" target="_blank">Graphite</a> 
                * **PR #3751** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3751" target="_blank">Graphite</a> 
                  * **PR #3752** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3752" target="_blank">Graphite</a> 
                    * **PR #3753** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3753" target="_blank">Graphite</a> 
                      * **PR #3754** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3754" target="_blank">Graphite</a> 
                        * **PR #3755** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3755" target="_blank">Graphite</a> 
                          * **PR #3756** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3756" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/3756?utm_source=stack-comment).

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3756)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3756#-NaBSk879pD2WHDY32oJ:-NaBSk88-UnLGmZlbK2n:b-ms88he) ([raw file](https://github.com/starkware-libs/cairo/blob/87cfb925e7f74b2ee469597b5b77e391569179dd/crates/cairo-lang-semantic/src/expr/compute.rs#L72)):*
> ```XML
> 
> #[derive(Debug, Clone)]
> pub struct PatternAndId {
> ```

is this struct required?

it seems `compute_pattern_semantic` is only called and its returned id is used.



_Code quote:_
```XML
PatternAndId
```
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3756#-NaBSIlx2IDRAEVzLAs9:-NaBSIlx2IDRAEVzLAsA:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/87cfb925e7f74b2ee469597b5b77e391569179dd/crates/cairo-lang-semantic/src/expr/compute.rs#L73)):*
> ```XML
> #[derive(Debug, Clone)]
> pub struct PatternAndId {
>     pub pat: Pattern,
> ```





_Suggestion:_
```XML
pub struct PatternAndId {
    pub pattern: Pattern,
```
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1047 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3756#-NaBRnmFAyE5Yx9VjOmO:-NaBRnmFAyE5Yx9VjOmP:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/87cfb925e7f74b2ee469597b5b77e391569179dd/crates/cairo-lang-semantic/src/expr/compute.rs#L1047)):*
> ```XML
> }
> 
> pub fn compute_pattern_semantic(
> ```

doc

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3756)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3756#-NaBSk879pD2WHDY32oJ:-NaFy2zxEQoqjGwCqe4l:bdx1o21) ([raw file](https://github.com/starkware-libs/cairo/blob/87cfb925e7f74b2ee469597b5b77e391569179dd/crates/cairo-lang-semantic/src/expr/compute.rs#L72)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is this struct required?

it seems `compute_pattern_semantic` is only called and its returned id is used.
</blockquote></details>

The id is used explicitly. The pattern is used implicitly using Deref.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3756#-NaBSIlx2IDRAEVzLAs9:-NaFy8974qwLnktBqUDx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/87cfb925e7f74b2ee469597b5b77e391569179dd/crates/cairo-lang-semantic/src/expr/compute.rs#L73)):*
> ```XML
> #[derive(Debug, Clone)]
> pub struct PatternAndId {
>     pub pat: Pattern,
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1047 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3756#-NaBRnmFAyE5Yx9VjOmO:-NaFyVrw6nMRkLgTT8mm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/87cfb925e7f74b2ee469597b5b77e391569179dd/crates/cairo-lang-semantic/src/expr/compute.rs#L1047)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3756#-:-NaG-adk3rb1Cl9w77MZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
