### PR TITLE
added impl type constraints when solving them in lowering and in cano…

### PR DESCRIPTION
**Pull request by TomerStarkware**
…nical inference

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 7 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6873)* status: 7 of 9 files reviewed, 6 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 959 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6873#-OEIWDbh9sd6jyOatjY_:-OEIWDbh9sd6jyOatjYa:b-2qa7yp) ([raw file](https://github.com/starkware-libs/cairo/blob/eb4370da783aa025fc938df9ec16b6cfa86d2d15/crates/cairo-lang-semantic/src/expr/inference.rs#L959)):*
> ```XML
>             canonical_trait,
>             lookup_context,
>             self.data.impl_type_bounds.clone(),
> ```

is the order here fully stable? how is it originally initiated? we should make sure at the very least the internal ordering is consistent to not recall queries on that.



_Code quote:_
```XML
            self.data.impl_type_bounds.clone(),
```
___
*[`crates/cairo-lang-semantic/src/expr/inference/solver.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6873#-OEIVGHdBa7vAkp0dNlO:-OEIVGHdBa7vAkp0dNlP:b-j2r6a3) ([raw file](https://github.com/starkware-libs/cairo/blob/eb4370da783aa025fc938df9ec16b6cfa86d2d15/crates/cairo-lang-semantic/src/expr/inference/solver.rs#L171)):*
> ```XML
>         canonical_trait: CanonicalTrait,
>         lookup_context: ImplLookupContext,
>         impl_type_bounds: &OrderedHashMap<ImplTypeId, TypeId>,
> ```

move it in - this is already an extra clone.



_Suggestion:_
```XML
        impl_type_bounds: OrderedHashMap<ImplTypeId, TypeId>,
```
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1056 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6873#-OEITwW69rqmVezkS83F:-OEITwW71jP2Z5AYgApO:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/eb4370da783aa025fc938df9ec16b6cfa86d2d15/crates/cairo-lang-semantic/src/expr/compute.rs#L1056)):*
> ```XML
>         let ConcreteTraitLongId { trait_id, generic_args: _ } =
>             concrete_trait_id.lookup_intern(ctx.db);
>         if crate::corelib::fn_traits(ctx.db).contains(&trait_id) {
> ```





_Suggestion:_
```XML
        if crate::corelib::fn_traits(ctx.db).contains(&concrete_trait_id.trait_id()) {
```
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 3076 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6873#-OEIUXBDETnIX9lCVkg9:-OEIUXBDETnIX9lCVkgA:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/eb4370da783aa025fc938df9ec16b6cfa86d2d15/crates/cairo-lang-semantic/src/items/tests/trait_type#L3076)):*
> ```
> //! > ==========================================================================
> 
> //! > using an impl with generic args which is a constrained trait type
> ```





_Suggestion:_
```
//! > Using an impl with generic args which is a constrained trait type.
```
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 3103 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6873#-OEIUUoR4eIvEM_Jd4MS:-OEIUUoR4eIvEM_Jd4MT:buj1cxa) ([raw file](https://github.com/starkware-libs/cairo/blob/eb4370da783aa025fc938df9ec16b6cfa86d2d15/crates/cairo-lang-semantic/src/items/tests/trait_type#L3103)):*
> ```
> //! > ==========================================================================
> 
> //! > using an impl with generic args which is a constrained trait type with the impl of the real type.
> ```

shorten.
___
*[`crates/cairo-lang-utils/src/ordered_hash_map.rs` line 239 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6873#-OEIWZqt4FHg2pS5gHwo:-OEIWZqt4FHg2pS5gHwp:b-x7qked) ([raw file](https://github.com/starkware-libs/cairo/blob/eb4370da783aa025fc938df9ec16b6cfa86d2d15/crates/cairo-lang-utils/src/ordered_hash_map.rs#L239)):*
> ```XML
>             k.hash(state);
>             v.hash(state);
>         });
> ```

probably required as well.



_Suggestion:_
```XML
        self.len().hash(state);
        self.iter().for_each(|(k, v)| {
            k.hash(state);
            v.hash(state);
        });
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6873)* status: 7 of 9 files reviewed, 6 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/inference/solver.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6873#-OEIVGHdBa7vAkp0dNlO:-OEIdxseACyM_wPS8d_a:bvjnjv8) ([raw file](https://github.com/starkware-libs/cairo/blob/eb4370da783aa025fc938df9ec16b6cfa86d2d15/crates/cairo-lang-semantic/src/expr/inference/solver.rs#L171)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

move it in - this is already an extra clone.
</blockquote></details>

used Arc
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 3103 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6873#-OEIUUoR4eIvEM_Jd4MS:-OEIfC0I0ESBf3kcFJMr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/eb4370da783aa025fc938df9ec16b6cfa86d2d15/crates/cairo-lang-semantic/src/items/tests/trait_type#L3103)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

shorten.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-utils/src/ordered_hash_map.rs` line 239 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6873#-OEIWZqt4FHg2pS5gHwo:-OEIfJiM6Kc3seB9Vnby:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/eb4370da783aa025fc938df9ec16b6cfa86d2d15/crates/cairo-lang-utils/src/ordered_hash_map.rs#L239)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

probably required as well.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 3076 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6873#-OEIUXBDETnIX9lCVkg9:-OEIeP7v333d39_y-BrL:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/eb4370da783aa025fc938df9ec16b6cfa86d2d15/crates/cairo-lang-semantic/src/items/tests/trait_type#L3076)):*
> ```
> //! > ==========================================================================
> 
> //! > using an impl with generic args which is a constrained trait type
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1056 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6873#-OEITwW69rqmVezkS83F:-OEIdaiP2xQ3KcYfOhJN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/eb4370da783aa025fc938df9ec16b6cfa86d2d15/crates/cairo-lang-semantic/src/expr/compute.rs#L1056)):*
> ```XML
>         let ConcreteTraitLongId { trait_id, generic_args: _ } =
>             concrete_trait_id.lookup_intern(ctx.db);
>         if crate::corelib::fn_traits(ctx.db).contains(&trait_id) {
> ```

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6873)* status: 6 of 9 files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6873)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 427 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6873#-OEJ44656ofS93x5k8Mc:-OEJ44656ofS93x5k8Md:b-dlq8lu) ([raw file](https://github.com/starkware-libs/cairo/blob/677fcae31026b6e975aaf631dbee9a3a0a2372d9/crates/cairo-lang-semantic/src/expr/inference.rs#L427)):*
> ```XML
>             solved: inference_id_replacer.rewrite(self.solved.clone()).no_err(),
>             ambiguous: inference_id_replacer.rewrite(self.ambiguous.clone()).no_err(),
>             impl_type_bounds: self.impl_type_bounds.clone(),
> ```

doc why rewrites not required.
___
*[`crates/cairo-lang-semantic/src/expr/inference/conform.rs` line 734 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6873#-OEJ4L6IApZwthzCi9XR:-OEJ4L6IApZwthzCi9XS:b-ybcll4) ([raw file](https://github.com/starkware-libs/cairo/blob/677fcae31026b6e975aaf631dbee9a3a0a2372d9/crates/cairo-lang-semantic/src/expr/inference/conform.rs#L734)):*
> ```XML
>     /// an helper function for getting for an impl type assignment.
>     /// Creates a new type var if the impl type is not yet assigned.
>     fn impl_type_assignment(
> ```

this is still unclear by name ad doc the fact it finds assigns to the map.



_Suggestion:_
```XML
    /// An helper function for getting for an impl type assignment.
    /// Creates a new type var if the impl type is not yet assigned.
    fn impl_type_assignment(
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6873)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 427 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6873#-OEJ44656ofS93x5k8Mc:-OEOqjMN7zf0XJB9qH7k:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/677fcae31026b6e975aaf631dbee9a3a0a2372d9/crates/cairo-lang-semantic/src/expr/inference.rs#L427)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc why rewrites not required.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/inference/conform.rs` line 734 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6873#-OEJ4L6IApZwthzCi9XR:-OEP3yC51xAJxyovlR6M:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/677fcae31026b6e975aaf631dbee9a3a0a2372d9/crates/cairo-lang-semantic/src/expr/inference/conform.rs#L734)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is still unclear by name ad doc the fact it finds assigns to the map.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6873)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 492 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6873#-OEP5lVi4uHxb5i-bY52:-OEP5lVi4uHxb5i-bY53:b-odjzzi) ([raw file](https://github.com/starkware-libs/cairo/blob/10636e2264efb8afb841a0e6570e49e14ce5820e/crates/cairo-lang-semantic/src/types.rs#L492)):*
> ```XML
>     fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
>         Some(self.cmp(other))
>     }
> ```

remove - use a specific wrapper type that would have an ordering to support this instead.



_Code quote:_
```XML
impl Ord for ImplTypeId {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        let a = self.impl_id.get_internal_id().cmp(other.impl_id.get_internal_id());
        let b = self.ty.get_internal_id().cmp(other.ty.get_internal_id());
        a.then(b)
    }
}
impl PartialOrd for ImplTypeId {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
```
___
*[`crates/cairo-lang-utils/src/ordered_hash_map.rs` line 230 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6873#-OEP5aeB2DGW0cTMYDMP:-OEP5aeB2DGW0cTMYDMQ:b-hay66z) ([raw file](https://github.com/starkware-libs/cairo/blob/10636e2264efb8afb841a0e6570e49e14ce5820e/crates/cairo-lang-utils/src/ordered_hash_map.rs#L230)):*
> ```XML
> }
> 
> impl<K, V> Hash for OrderedHashMap<K, V>
> ```

revert.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6873)* status: 5 of 10 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 492 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6873#-OEP5lVi4uHxb5i-bY52:-OEPLSsg59HVBMPKX363:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/10636e2264efb8afb841a0e6570e49e14ce5820e/crates/cairo-lang-semantic/src/types.rs#L492)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove - use a specific wrapper type that would have an ordering to support this instead.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-utils/src/ordered_hash_map.rs` line 230 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6873#-OEP5aeB2DGW0cTMYDMP:-OEPLY1cDvC_TnkfnCic:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/10636e2264efb8afb841a0e6570e49e14ce5820e/crates/cairo-lang-utils/src/ordered_hash_map.rs#L230)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

revert.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6873)* status: 6 of 10 files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 493 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6873#-OEPMvTIBizZXuQFbf-o:-OEPMvTIBizZXuQFbf-p:byjcyj) ([raw file](https://github.com/starkware-libs/cairo/blob/c57612370f533314af7bfe6ff43c72636b529da1/crates/cairo-lang-semantic/src/types.rs#L493)):*
> ```XML
>     fn cmp(&self, other: &Self) -> std::cmp::Ordering {
>         let a = self.0.impl_id.get_internal_id().cmp(other.0.impl_id.get_internal_id());
>         let b = self.0.ty.get_internal_id().cmp(other.0.ty.get_internal_id());
> ```

call this only if `a` is equal.



_Code quote:_
```XML
        let b = self.0.ty.get_internal_id().cmp(other.0.ty.get_internal_id());
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6873)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 483 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6873#-OEPN2nz-B3pTG2s_onz:-OEPN2nz-B3pTG2s_oo-:bp6h9uj) ([raw file](https://github.com/starkware-libs/cairo/blob/c57612370f533314af7bfe6ff43c72636b529da1/crates/cairo-lang-semantic/src/types.rs#L483)):*
> ```XML
> }
> #[derive(Copy, Clone, Debug, Hash, PartialEq, Eq)]
> pub struct ImplTypeById(ImplTypeId);
> ```

doc type.
probably also move it

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6873)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 483 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6873#-OEPN2nz-B3pTG2s_onz:-OEPRCHu5QpVs6NCQW72:b-qy3w3m) ([raw file](https://github.com/starkware-libs/cairo/blob/c57612370f533314af7bfe6ff43c72636b529da1/crates/cairo-lang-semantic/src/types.rs#L483)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc type.
probably also move it
</blockquote></details>

is infrence.rs a good place?

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6873)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 483 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6873#-OEPN2nz-B3pTG2s_onz:-OEPfKzwDX8KIKUR2c1e:bw4sfke) ([raw file](https://github.com/starkware-libs/cairo/blob/c57612370f533314af7bfe6ff43c72636b529da1/crates/cairo-lang-semantic/src/types.rs#L483)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

is infrence.rs a good place?
</blockquote></details>

nevermind, here's ok, just doc it.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6873)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 483 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6873#-OEPN2nz-B3pTG2s_onz:-OESzjzoCpi8ULMy6QKh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c57612370f533314af7bfe6ff43c72636b529da1/crates/cairo-lang-semantic/src/types.rs#L483)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

nevermind, here's ok, just doc it.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6873#-:-OESzzoD8BqWA6kmY4jr:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
