### PR TITLE
Add segment arena cost to dict new.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2852)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2852)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @liorgold2)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2852#-NTEBPeo44UCpeAO62ws:-NTEBPeo44UCpeAO62wt:b-hww3p1) (no related file):*
this is really that much more costly than a normal step?
@liorgold2 

___

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2852)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2852#-NTEBPeo44UCpeAO62ws:-NTECbswBycCD6vqCs-d:bpdhru7) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is really that much more costly than a normal step?
@liorgold2 
</blockquote></details>

It's 8 steps as for yesterday, I can add it as const cost.

___

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2852#-:-NTER5_U5E6s1ZKRTjM3:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2852#-NTEBPeo44UCpeAO62ws:-NTEQg-f0mgI3hKqp9oN:bak13zw) (no related file):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

It's 8 steps as for yesterday, I can add it as const cost.
</blockquote></details>

I guess this is an os price, so it makes sense it'd be handled by it.

___

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2852)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2852#-NTEBPeo44UCpeAO62ws:-NTERa7f6mumHStPIsG_:b-v85ze4) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I guess this is an os price, so it makes sense it'd be handled by it.
</blockquote></details>

Yes, it's the cost of the arena finalize function.

___

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2852)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/gas.rs` line 165 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2852#-NTESSsLATt2UhosOO3q:-NTESSsMCA29KgpYe8fo:b-2wrenw) ([raw file](https://github.com/starkware-libs/cairo/blob/e49d404632430ab186dae2e17b9f3b14ca44c822/crates/cairo-lang-sierra/src/extensions/modules/gas.rs#L165)):*
> ```XML
>     EcOp,
>     /// One allocation of a segment in the segment arena.
>     SegmentArena,
> ```

I thought we agreed on adding a const number of steps, after what Yuval said. I'm confused.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2852)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/gas.rs` line 165 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2852#-NTESSsLATt2UhosOO3q:-NTEsK6QCYPF89mDQgAt:b-7uu0di) ([raw file](https://github.com/starkware-libs/cairo/blob/e49d404632430ab186dae2e17b9f3b14ca44c822/crates/cairo-lang-sierra/src/extensions/modules/gas.rs#L165)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

I thought we agreed on adding a const number of steps, after what Yuval said. I'm confused.
</blockquote></details>

Then I misunderstood. Should I change it to const cost?

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2852)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/gas.rs` line 165 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2852#-NTESSsLATt2UhosOO3q:-NTG2iEL7QuUUv3q1qM9:b-ps8idt) ([raw file](https://github.com/starkware-libs/cairo/blob/e49d404632430ab186dae2e17b9f3b14ca44c822/crates/cairo-lang-sierra/src/extensions/modules/gas.rs#L165)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Then I misunderstood. Should I change it to const cost?
</blockquote></details>

Let's decide tomorrow.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2852)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/gas.rs` line 165 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2852#-NTESSsLATt2UhosOO3q:-NTT9LcF342U8y7pFRq9:b-udmf5u) ([raw file](https://github.com/starkware-libs/cairo/blob/e49d404632430ab186dae2e17b9f3b14ca44c822/crates/cairo-lang-sierra/src/extensions/modules/gas.rs#L165)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Let's decide tomorrow.
</blockquote></details>

I changed it to const cost.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2852)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @liorgold2)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2852#-NTTAKeg1-e5bJSs_4ue:-NTTAKeh-0sPbiGa-cjn:bi9vy32) (no related file):*
Do the same thing we did in felt div, no need for all the extra games.

___

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2852)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @liorgold2 and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2852#-NTTAKeg1-e5bJSs_4ue:-NTTHIEC8bHo52FWYK26:bb6un1j) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Do the same thing we did in felt div, no need for all the extra games.
</blockquote></details>

Done

___

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 8 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2852#-:-NTTPIlP0oEFkYRv6JIH:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @liorgold2)

___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 282 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2852#-NTTOrVHE7YHVebn3Nsm:-NTTOrVI2wju977gzvQZ:b-qc8yi8) ([raw file](https://github.com/starkware-libs/cairo/blob/e49d404632430ab186dae2e17b9f3b14ca44c822/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L282)):*
> ```XML
>         Felt252Dict(libfunc) => match libfunc {
>             Felt252DictConcreteLibfunc::New(_) => {
>                 vecBranchCost::Regular {
> ```

No need to comment here, as this is auto checked.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs` line 58 at r3 ([raw file](https://github.com/starkware-libs/cairo/blob/651aeafe98c32f06ec30cbf9e35dc95b9965554c/crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs#L58)):*
> ```XML
>         [("Fallthrough", &[&[segment_arena_ptr], &[new_dict_end]], None)],
>         CostValidationInfo {
>             range_check_info: None,
> ```

This is the place for the comment , also, probably write the 8 as a constant somewhere near the SegmentArena def

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2852)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs` line 58 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2852#-NTTOyd16oB3SgRFt9p7:-NTUR3hqDG2LSLmn-l6t:b-hlphw1) ([raw file](https://github.com/starkware-libs/cairo/blob/651aeafe98c32f06ec30cbf9e35dc95b9965554c/crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs#L58)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Done, except for the const, the segment arena is only defined in sierra as there are no libfuncs related to it. Maybe the const should be in core_libfunc_cost_base.rs?
</blockquote></details>

I mostly that it should be exactly near it in the sierra crate.
but for now can be here as well

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2852)* status: 6 of 9 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs` line 58 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2852#-NTTOyd16oB3SgRFt9p7:-NTi6v1gEmR3J0_7KQr_:b-9htl7d) ([raw file](https://github.com/starkware-libs/cairo/blob/651aeafe98c32f06ec30cbf9e35dc95b9965554c/crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs#L58)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I mostly that it should be exactly near it in the sierra crate.
but for now can be here as well
</blockquote></details>

I've added it next to the dict cost consts.

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2852)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2852)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 8 files at r2, 2 of 4 files at r3, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2852#-:-NTjzb3JAX_tWc96a5fq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
