### PR TITLE
Profiler: calculate scoped sierra statement weights

### PR DESCRIPTION
**Pull request by m-kus**
This PR extends the raw profiling info structure with a new field `scoped_sierra_statement_weights` which is basically stack trace and sierra statements weights combined.

The reason why this is necessary is because neither stack trace nor statements weights are informative enough for profiling a large execution trace. Additionally, recursive calls and loops make analysis harder, so in the proposed implementation recursive calls are collapsed and their weights are aggregated.

How is this used: for rendering flamegraph charts.

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6569)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @m-kus)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 369 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6569#-OB52aBG8_OtMMh5yryj:-OB52aBG8_OtMMh5yryk:btsu6a7) ([raw file](https://github.com/starkware-libs/cairo/blob/a349638c44400157fbec1314b49a4c5d56a2233a/crates/cairo-lang-runner/src/lib.rs#L369)):*
> ```XML
>                 chain!(function_stack.iter().map(|&(idx, _)| idx), [user_function_idx])
>                     .dedup()
>                     .collect();
> ```

this stack may overflow too much in cases of recursion with more than one step.
this still needs to be blocked.



_Code quote:_
```XML
            let cur_stack: Vec<usize> =
                chain!(function_stack.iter().map(|&(idx, _)| idx), [user_function_idx])
                    .dedup()
                    .collect();
```

**Review by m-kus — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6569)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 369 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6569#-OB52aBG8_OtMMh5yryj:-OB5jaCPBPX8-Gwcjmjo:b-dw36va) ([raw file](https://github.com/starkware-libs/cairo/blob/a349638c44400157fbec1314b49a4c5d56a2233a/crates/cairo-lang-runner/src/lib.rs#L369)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this stack may overflow too much in cases of recursion with more than one step.
this still needs to be blocked.
</blockquote></details>

You mean that `function_stack` can be of `max_stack_trace_depth` size at this point? Or that we can overflow `usize` due to aggregation of large number of recursion steps?

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6569)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @m-kus)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 369 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6569#-OB52aBG8_OtMMh5yryj:-OB5yU2C3PIwuv47ADJj:bz74w5m) ([raw file](https://github.com/starkware-libs/cairo/blob/a349638c44400157fbec1314b49a4c5d56a2233a/crates/cairo-lang-runner/src/lib.rs#L369)):*
<details><summary><i>Previously, m-kus (Michael Zaikin) wrote…</i></summary><blockquote>

You mean that `function_stack` can be of `max_stack_trace_depth` size at this point? Or that we can overflow `usize` due to aggregation of large number of recursion steps?
</blockquote></details>

No overflow,  but we would get a lot of different values there, with a size the square of the size of the run.

**Review by m-kus — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6569)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 369 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6569#-OB52aBG8_OtMMh5yryj:-OBAQ-h88t_gMvAIsbfX:b-r1mu99) ([raw file](https://github.com/starkware-libs/cairo/blob/a349638c44400157fbec1314b49a4c5d56a2233a/crates/cairo-lang-runner/src/lib.rs#L369)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

No overflow,  but we would get a lot of different values there, with a size the square of the size of the run.
</blockquote></details>

Sorry, I don't get it
`cur_stack` can be maximum `max_stack_trace_depth+1` elements,
`sierra_statement_weights` can have at most the same number of entries as the trace (worst case).

Do you mean that the overall memory size for `sierra_statement_weights` can be square the size of the trace worst case?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6569)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @m-kus)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 369 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6569#-OB52aBG8_OtMMh5yryj:-OBKIQ4SEzHNnP9RzuDo:b6af2ta) ([raw file](https://github.com/starkware-libs/cairo/blob/a349638c44400157fbec1314b49a4c5d56a2233a/crates/cairo-lang-runner/src/lib.rs#L369)):*
<details><summary><i>Previously, m-kus (Michael Zaikin) wrote…</i></summary><blockquote>

Sorry, I don't get it
`cur_stack` can be maximum `max_stack_trace_depth+1` elements,
`sierra_statement_weights` can have at most the same number of entries as the trace (worst case).

Do you mean that the overall memory size for `sierra_statement_weights` can be square the size of the trace worst case?
</blockquote></details>

oh - you are correct - but do note this will still vastly increase the size of the result, as now we get a per statement info inside the function itself.

**Review by m-kus — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6569)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 369 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6569#-OB52aBG8_OtMMh5yryj:-OBOXpvM229YTkbUaqnX:b-bchpw4) ([raw file](https://github.com/starkware-libs/cairo/blob/a349638c44400157fbec1314b49a4c5d56a2233a/crates/cairo-lang-runner/src/lib.rs#L369)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

oh - you are correct - but do note this will still vastly increase the size of the result, as now we get a per statement info inside the function itself.
</blockquote></details>

Right, would it be ok if I make it optional feature behind a flag in `ProfilingInfoCollectionConfig`?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6569)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @m-kus)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 369 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6569#-OB52aBG8_OtMMh5yryj:-OBOssaA2G22HmYcEllY:bljekwg) ([raw file](https://github.com/starkware-libs/cairo/blob/a349638c44400157fbec1314b49a4c5d56a2233a/crates/cairo-lang-runner/src/lib.rs#L369)):*
<details><summary><i>Previously, m-kus (Michael Zaikin) wrote…</i></summary><blockquote>

Right, would it be ok if I make it optional feature behind a flag in `ProfilingInfoCollectionConfig`?
</blockquote></details>

Sounds good.
Additionally, print it in the profiler tests so we'd see it in action

**Review by m-kus — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6569)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 369 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6569#-OB52aBG8_OtMMh5yryj:-OB_BRqaBilXnzepyF9p:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a349638c44400157fbec1314b49a4c5d56a2233a/crates/cairo-lang-runner/src/lib.rs#L369)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Sounds good.
Additionally, print it in the profiler tests so we'd see it in action
</blockquote></details>

Done.

**Review by m-kus — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6569)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/profiling.rs` line 517 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6569#-OB_IVDkAuH0wc1Yi3kp:-OBczt1h1_-PAIZ9QX7m:b-eehp6) ([raw file](https://github.com/starkware-libs/cairo/blob/a2a83b47f68fad484dbe29d0a68478a006e12a18/crates/cairo-lang-runner/src/profiling.rs#L517)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

do you actually want to "forget" the statement-idx itself here?
</blockquote></details>

Yeah, it's replaced with the debug name and we no longer need it
___
*[`crates/cairo-lang-runner/src/profiling.rs` line 607 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6569#-OB_HLVEDAWOrh0Kwvji:-OBcy5qbCxLuMmfhkHvV:b5ecq4l) ([raw file](https://github.com/starkware-libs/cairo/blob/a2a83b47f68fad484dbe29d0a68478a006e12a18/crates/cairo-lang-runner/src/profiling.rs#L607)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i think this might be a bit better.
</blockquote></details>

That's the folded stack trace format supported by flamegraph.pl
___
*[`crates/cairo-lang-runner/src/profiling.rs` line 527 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6569#-OB_Ier66u4KRJ0DzwNk:-OBd--up-yqmlLgzrivV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a2a83b47f68fad484dbe29d0a68478a006e12a18/crates/cairo-lang-runner/src/profiling.rs#L527)):*
> ```XML
>                                     .unwrap_or(format!("<{}>", invocation.libfunc_id.id)),
>                                 GenStatement::Return(_) => "return".into(),
>                             };
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6569#-:-OBd8peWBl-bf33q9rZY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @m-kus)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6569)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @m-kus)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6569)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @m-kus)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6569#-OBfHl6AALQEfS-twW26:-OBfHl6B0-qnBXw65vhL:b-uuj1x0) (no related file):*
@gilbens-starkware for 2nd eye.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6569#-:-OBviXueAHSy8WKQZgMV:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @m-kus)

___
*[`crates/cairo-lang-runner/src/profiling_test.rs` line 24 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6569#-OBvjTt56WoNNPLE5unL:-OBvjTt56WoNNPLE5unM:b-5r5d21) ([raw file](https://github.com/starkware-libs/cairo/blob/8ec75d15a56fc2a1cfc969545578c3c2b4853c6c/crates/cairo-lang-runner/src/profiling_test.rs#L24)):*
> ```XML
>         profiling: "profiling",
>         circuit: "circuit",
>         flamegraph: "flamegraph"
> ```

As this is not clear why it is related to flamegraph without the explanations above, and it hints that the output of this test is a flamegraph. 



_Suggestion:_
```XML
scoped_statements: "scoped_statements"
```
___
*[`crates/cairo-lang-runner/src/profiling_test.rs` line 85 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6569#-OBvjZZL5yExNdqQgu4S:-OBvjZZL5yExNdqQgu4T:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8ec75d15a56fc2a1cfc969545578c3c2b4853c6c/crates/cairo-lang-runner/src/profiling_test.rs#L85)):*
> ```XML
>         sierra_program,
>         statements_functions,
>         if inputs.contains_key("flamegraph_mode") {
> ```





_Suggestion:_
```XML
("scoped_mode")
```

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6569)* status: all files reviewed, 2 unresolved discussions (waiting on @m-kus)

**Review by m-kus — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6569)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-runner/src/profiling_test.rs` line 24 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6569#-OBvjTt56WoNNPLE5unL:-OBzuqkA09H0-CDXZnRA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8ec75d15a56fc2a1cfc969545578c3c2b4853c6c/crates/cairo-lang-runner/src/profiling_test.rs#L24)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

As this is not clear why it is related to flamegraph without the explanations above, and it hints that the output of this test is a flamegraph.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runner/src/profiling_test.rs` line 85 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6569#-OBvjZZL5yExNdqQgu4S:-OBzur1M6TDUjco4OTNa:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8ec75d15a56fc2a1cfc969545578c3c2b4853c6c/crates/cairo-lang-runner/src/profiling_test.rs#L85)):*
> ```XML
>         sierra_program,
>         statements_functions,
>         if inputs.contains_key("flamegraph_mode") {
> ```

Done.

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6569)* status: all files reviewed, 2 unresolved discussions (waiting on @m-kus)

**Review by gilbens-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6569)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @m-kus)

**Pull request merged**
