### PR TITLE
Moved serde to be trait based.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:42677340

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1835)* status: 5 of 11 files reviewed, 6 unresolved discussions (waiting on @orizi)

___
*[`corelib/serde.cairo` line 76 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1835#-NMMkgNi7QM4rQBgX_oE:-NMMkgNi7QM4rQBgX_oF:bditlsu) ([raw file](https://github.com/starkware-libs/cairo/blob/a8266881706a2b3322c255bf01c5d37817613a68/corelib/serde.cairo#L76)):*
> ```Cairo
>     match array_pop_front::<felt>(ref input) {
>         Option::Some(value) => {
>             Serde::<felt>::serialize(ref serialized, value);
> ```

Can't this felt be inferred?
___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1835#-NMKt0Gv3bJV7xGcB_4F:-NMKt0Gw4dKY19WHt8sS:buo9nn6) ([raw file](https://github.com/starkware-libs/cairo/blob/a8266881706a2b3322c255bf01c5d37817613a68/crates/cairo-lang-starknet/src/plugin.rs#L146)):*
> ```XML
>                     serialization_code.push(RewriteNode::interpolate_patched(
>                         &formatdoc!(
>                             "        serde::Serde::<{type_name}>::serialize(calldata, \
> ```

Same herr
___
*[`crates/cairo-lang-starknet/src/plugin_test_data/diagnostics` line 54 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1835#-NMMlHwnBjqpkB12OJ8D:-NMMlHwnBjqpkB12OJ8E:b9jnlhv) ([raw file](https://github.com/starkware-libs/cairo/blob/a8266881706a2b3322c255bf01c5d37817613a68/crates/cairo-lang-starknet/src/plugin_test_data/diagnostics#L54)):*
> ```
>                 },
>                 Option::None(_) => {
>                     let mut err_data = array_new::<felt>();
> ```

This can be inferred
___
*[`crates/cairo-lang-starknet/src/plugin_test_data/diagnostics` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1835#-NMMlFof1B2LWLw-PYbE:-NMMlFof1B2LWLw-PYbF:b9jnlhv) ([raw file](https://github.com/starkware-libs/cairo/blob/a8266881706a2b3322c255bf01c5d37817613a68/crates/cairo-lang-starknet/src/plugin_test_data/diagnostics#L55)):*
> ```
>                 Option::None(_) => {
>                     let mut err_data = array_new::<felt>();
>                     array_append::<felt>(ref err_data, 'Out of gas');
> ```

This can be inferred
___
*[`crates/cairo-lang-starknet/src/plugin_test_data/diagnostics` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1835#-NMMlxL8BlQa0j2wduHw:-NMMlxL8BlQa0j2wduHx:bwpkm0p) ([raw file](https://github.com/starkware-libs/cairo/blob/a8266881706a2b3322c255bf01c5d37817613a68/crates/cairo-lang-starknet/src/plugin_test_data/diagnostics#L61)):*
> ```
>             
>             let __arg_x =
>                 match serde::Serde::<(felt, felt)>::deserialize(ref data) {
> ```

Did you inplemebt this serde somewhere?
Does this even work?
___
*[`crates/cairo-lang-starknet/src/plugin_test_data/diagnostics` line 65 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1835#-NMMlKkh04-AtcKJbH2k:-NMMlKkh04-AtcKJbH2l:ben2lv7) ([raw file](https://github.com/starkware-libs/cairo/blob/a8266881706a2b3322c255bf01c5d37817613a68/crates/cairo-lang-starknet/src/plugin_test_data/diagnostics#L65)):*
> ```
>                     Option::None(()) => {
>                         let mut err_data = array_new::<felt>();
>                         array_append::<felt>(ref err_data, 'Input too short for arguments');
> ```

This tio, and below as well

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1835)* status: 5 of 11 files reviewed, 6 unresolved discussions (waiting on @spapinistarkware)

___
*[`corelib/serde.cairo` line 76 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1835#-NMMkgNi7QM4rQBgX_oE:-NMNHx7m2MC5CjptCHVX:b-74yxmr) ([raw file](https://github.com/starkware-libs/cairo/blob/a8266881706a2b3322c255bf01c5d37817613a68/corelib/serde.cairo#L76)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Can't this felt be inferred?
</blockquote></details>

currently - did not work :(
___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1835#-NMKt0Gv3bJV7xGcB_4F:-NMNI79q2JarqQQOpFLW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a8266881706a2b3322c255bf01c5d37817613a68/crates/cairo-lang-starknet/src/plugin.rs#L146)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Same herr
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin_test_data/diagnostics` line 54 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1835#-NMMlHwnBjqpkB12OJ8D:-NMNJdWk70Qe3DE9GFKY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a8266881706a2b3322c255bf01c5d37817613a68/crates/cairo-lang-starknet/src/plugin_test_data/diagnostics#L54)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This can be inferred
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin_test_data/diagnostics` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1835#-NMMlFof1B2LWLw-PYbE:-NMNJdkU1Rj1HS9K2tj6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a8266881706a2b3322c255bf01c5d37817613a68/crates/cairo-lang-starknet/src/plugin_test_data/diagnostics#L55)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This can be inferred
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin_test_data/diagnostics` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1835#-NMMlxL8BlQa0j2wduHw:-NMNJbRS3JtJ-ZSlFB9g:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a8266881706a2b3322c255bf01c5d37817613a68/crates/cairo-lang-starknet/src/plugin_test_data/diagnostics#L61)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Did you inplemebt this serde somewhere?
Does this even work?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin_test_data/diagnostics` line 65 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1835#-NMMlKkh04-AtcKJbH2k:-NMNJbeh19NMAIxu5DKt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a8266881706a2b3322c255bf01c5d37817613a68/crates/cairo-lang-starknet/src/plugin_test_data/diagnostics#L65)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This tio, and below as well
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1835#-:-NMNJhU419NCfZhQwYsU:bnfp4nl)* status: 5 of 11 files reviewed, all discussions resolved

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 6 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1835)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
