### PR TITLE
Add wrapper function to squash dict casm.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2082)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2082#-:-NNq-iT_7DLHqvDLkn-m:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/dict_felt_to.rs` line 160 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2082#-NNq-aHk4sT6qfjocSw5:-NNq-aHk4sT6qfjocSw6:bdvwguq) ([raw file](https://github.com/starkware-libs/cairo/blob/f1e070d61c3850c866de273ec59216100b70d843/crates/cairo-lang-sierra-to-casm/src/invocations/dict_felt_to.rs#L160)):*
> ```XML
>             let (final_range_check_ptr,
>                 final_gas_builtin,
>                 final_dict_manager_ptr,
> ```

explain



_Code quote:_
```XML
            let (final_range_check_ptr,
                final_gas_builtin,
                final_dict_manager_ptr,
                final_squashed_dict_start,
                final_squashed_dict_end) = call DestructDict;
            jump DONE;
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2082)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/dict_felt_to.rs` line 160 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2082#-NNq-aHk4sT6qfjocSw5:-NNqQW7R2uCwpJFKc2aD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f1e070d61c3850c866de273ec59216100b70d843/crates/cairo-lang-sierra-to-casm/src/invocations/dict_felt_to.rs#L160)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

explain
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2082#-:-NNqWLOL4e3FiYmbN0dc:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/dict_felt_to.rs` line 153 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2082#-NNqWCBR5nZza-BB20vu:-NNqWCBR5nZza-BB20vv:b7av3nl) ([raw file](https://github.com/starkware-libs/cairo/blob/0fd7e88315388936a47f0593697c0e90d018fc2b/crates/cairo-lang-sierra-to-casm/src/invocations/dict_felt_to.rs#L153)):*
> ```XML
>             const zero = 0;
>             const gas_refund_per_access = DICT_SQUASH_UNIQUE_KEY_COST;
>             // DestructDict is a wrapper for that provides a clean scope for dict_squash where local variables can be allocated.
> ```

and i think this line may be too long.



_Suggestion:_
```XML
            // DestructDict is a wrapper that provides a clean scope for dict_squash where local variables can be allocated.
```

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2082)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2082)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
