### PR TITLE
Added support for minus in constants.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #5088
- #5087
- #5086
- #5085
- #5082 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5082)

### CODE REVIEW

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 9 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5082#-:-Nr-pLX4DDDIaN1BzmAY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5082)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5082#-Nr08A2wEXAD3Hrg3WUT:-Nr08A2wEXAD3Hrg3WUU:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8b978b1e5e3d36cba815c516ea1db977cd5aa16f/crates/cairo-lang-semantic/src/items/constant.rs#L26)):*
> ```XML
> pub struct Constant {
>     /// The actual id of the const expression value.
>     pub value: ExprId,
> ```





_Suggestion:_
```XML
const_id
```
___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 30 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5082#-Nr08Cz29OOsBBYg02Wq:-Nr08Cz29OOsBBYg02Wr:b-5qwfio) ([raw file](https://github.com/starkware-libs/cairo/blob/8b978b1e5e3d36cba815c516ea1db977cd5aa16f/crates/cairo-lang-semantic/src/items/constant.rs#L30)):*
> ```XML
>     pub ty: TypeId,
>     /// The arena of all the expressions for the const calculation.
>     pub exprs: Arc<Arena<Expr>>,
> ```

It will make all constant related queries invalidated with any change to the `exprs`, I am not sure if it will be noticeable, but can this be avoided?



_Code quote:_
```XML
exprs
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5082)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5082#-Nr08A2wEXAD3Hrg3WUT:-Nr0tah9-o5fo_rM-7sQ:b-ud388c) ([raw file](https://github.com/starkware-libs/cairo/blob/2cb80dda6396c404bc2ba88f606ae431de82ec36/crates/cairo-lang-semantic/src/items/constant.rs#L26)):*
> ```XML
> pub struct Constant {
>     /// The actual id of the const expression value.
>     pub value: ExprId,
> ```

it isn't the const_id - it is the actual id of the value of the expression.
___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 30 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5082#-Nr08Cz29OOsBBYg02Wq:-Nr0tjw47CKRY-L1Z82P:buh32td) ([raw file](https://github.com/starkware-libs/cairo/blob/2cb80dda6396c404bc2ba88f606ae431de82ec36/crates/cairo-lang-semantic/src/items/constant.rs#L30)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

It will make all constant related queries invalidated with any change to the `exprs`, I am not sure if it will be noticeable, but can this be avoided?
</blockquote></details>

the `exprs` arena will be changed by any change in the constant - and by nothing else, so this works as intended.
note the arena is exactly the arena for the constant only.

**Review by gilbens-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5082)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
