### PR TITLE
merged ExprConstant ExprParamConstant

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5468)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5468)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 547 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5468#-NwFASFe2u8ctrNSyaXW:-NwFASFe2u8ctrNSyaXX:bbfd7jb) ([raw file](https://github.com/starkware-libs/cairo/blob/6561690e6811dbfacc4dbfdf910b8e8233354c8a/crates/cairo-lang-semantic/src/items/constant.rs#L547)):*
> ```XML
> }
> 
> /// Cycle handling for [crate::db::SemanticGroup::constant_const_value].
> ```

is this an actual part of this PR?

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5468)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 547 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5468#-NwFASFe2u8ctrNSyaXW:-NwJS6Pa7RWgnABq1bAu:b-fiwa0p) ([raw file](https://github.com/starkware-libs/cairo/blob/6561690e6811dbfacc4dbfdf910b8e8233354c8a/crates/cairo-lang-semantic/src/items/constant.rs#L547)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is this an actual part of this PR?
</blockquote></details>

yes there are cycles otherwise

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 7 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5468#-:-NwJUlQT7TfN-pU1YIjk:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 5 of 68 files at r3, 63 of 63 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5468)* status: 62 of 70 files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 8 files at r5, 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5468#-:-NxNkXwt6mnX7TNvc_Y6:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5468#-:-NxT04a3Cn4I6FSNJs78:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5468)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5468)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Review by mkaput — APPROVED** [review]
> Reviewed 1 of 7 files at r1, 57 of 63 files at r4, 3 of 8 files at r5, 2 of 9 files at r6, 3 of 6 files at r7, 3 of 3 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5468)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request closed without merging**
