### PR TITLE
Extract jnz-patch function

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
Signed-off-by: Dori Medini <dori@<a href="starkware.co">starkware.co</a>>

---

**Stack**:
- #1105
- #1104
- #1096 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1096)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1096#-:-NHskHIP787bKSKmeEeh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
squashed with Cargo.lock update (ran `rustup override set stable && rustup update && cargo test`, tests passed, no additional changes)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1096#-:-NHsrdlgAnK5l2UxJEyC:b-8fsj4l)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1096)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Comment by dorimedini-starkware** [comment]
✓ Commit merged in pull request [#1104](https://github.com/starkware-libs/cairo2/pull/1104)

**Pull request merged**
