### PR TITLE
Using `Arc<[T]>` instead of `Arc<Vec<T>>`.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5978)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5978#-O1LuTxw6S7CgYhv7Gae:-O1LuTxw6S7CgYhv7Gaf:bmhqgbd) ([raw file](https://github.com/starkware-libs/cairo/blob/47fdf03825c2a92b981a0ea5d10d21b2c5116026/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L135)):*
> ```XML
>         ResolvedConcreteItem::Module(module_id) => db
>             .module_items(module_id)
>             .ok()?
> ```

Why is it ok to early return here?



_Code quote:_
```XML
 .ok()?
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5978)* status: 0 of 31 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @mkaput)

___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5978#-O1LuTxw6S7CgYhv7Gae:-O1Lv-oSCUS8L06DiQX1:bn6a1yb) ([raw file](https://github.com/starkware-libs/cairo/blob/47fdf03825c2a92b981a0ea5d10d21b2c5116026/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L135)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why is it ok to early return here?
</blockquote></details>

i think it is - this is for suggestions for completions - we would return `None` (so - no suggestions) instead of an empty vector.
@mkaput ?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-syntax/src/node/iter.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5978#-O1LvNvf4IXHkT8xNSaM:-O1LvNvf4IXHkT8xNSaN:bfgp40q) ([raw file](https://github.com/starkware-libs/cairo/blob/47fdf03825c2a92b981a0ea5d10d21b2c5116026/crates/cairo-lang-syntax/src/node/iter.rs#L36)):*
> ```XML
> struct PreorderLayer {
>     start: SyntaxNode,
>     children: Option<(Arc<[SyntaxNode]>, usize)>,
> ```

Why did you add another argument?
does the slice not have a length?



_Code quote:_
```XML
, usize
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 25 of 31 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5978)* status: 25 of 31 files reviewed, 2 unresolved discussions (waiting on @mkaput and @orizi)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5978)* status: 25 of 31 files reviewed, 1 unresolved discussion (waiting on @mkaput)

___
*[`crates/cairo-lang-syntax/src/node/iter.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5978#-O1LvNvf4IXHkT8xNSaM:-O1Lxh104ckmvmCzb1ec:b-sgbnhc) ([raw file](https://github.com/starkware-libs/cairo/blob/47fdf03825c2a92b981a0ea5d10d21b2c5116026/crates/cairo-lang-syntax/src/node/iter.rs#L36)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why did you add another argument?
does the slice not have a length?
</blockquote></details>

Ok, I guess you are implementing an iterator here.

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 31 of 31 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5978#-:-O1MLEyz6Um-hLFDSb-o:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5978#-O1LuTxw6S7CgYhv7Gae:-O1MLAXqEEHsmGj3UCe1:b-joddjj) ([raw file](https://github.com/starkware-libs/cairo/blob/47fdf03825c2a92b981a0ea5d10d21b2c5116026/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L135)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i think it is - this is for suggestions for completions - we would return `None` (so - no suggestions) instead of an empty vector.
@mkaput ?
</blockquote></details>

sounds good to me

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5978)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Pull request merged**
