### PR TITLE
Update account contract signature.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2363)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2363#-:-NPmUbwz7q1mfYz5k1Zt:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2363)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 68 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2363#-NPnpHgn6W_FCn5yXWvn:-NPnpHgn6W_FCn5yXWvo:bbwk1xs) ([raw file](https://github.com/starkware-libs/cairo/blob/1ae57c482447c116f553e23585b54c6be16bfa56/crates/cairo-lang-starknet/test_data/account.cairo#L68)):*
> ```Cairo
>     #[external]
>     #[raw_output]
>     fn __execute__(mut calls: Array<Call>) -> Array::<felt> {
> ```

Shouldn't it be span?



_Code quote:_
```Cairo
mut calls: Array<Call>
```

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2363)* status: all files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 78 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2363#-NPnpU9o7KgRqHb-aLc8:-NPnpU9o7KgRqHb-aLc9:b4tqcxh) ([raw file](https://github.com/starkware-libs/cairo/blob/1ae57c482447c116f553e23585b54c6be16bfa56/crates/cairo-lang-starknet/test_data/account.cairo#L78)):*
> ```Cairo
>         // TODO(ilya): Implement multi call.
>         assert(calls.len() == 1_u32, 'MULTI_CALL_NOT_SUPPORTED');
>         let Call{to, selector, calldata } = calls.pop_front().unwrap();
> ```

Autoformatter bug? (same below)



_Suggestion:_
```Cairo
let Call{to, selector, calldata} = calls.pop_front().unwrap();
```
___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 81 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2363#-NPnpmlPBedcm6mgrxLP:-NPnpmlPBedcm6mgrxLQ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/1ae57c482447c116f553e23585b54c6be16bfa56/crates/cairo-lang-starknet/test_data/account.cairo#L81)):*
> ```Cairo
> 
>         starknet::call_contract_syscall(
>             address: to, entry_point_selector: selector, calldata: calldata
> ```





_Suggestion:_
```Cairo
address: to, entry_point_selector: selector, :calldata
```
___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 98 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2363#-NPnq5BECUj6zJq_gV3A:-NPnq5BECUj6zJq_gV3B:b-uwm7hn) ([raw file](https://github.com/starkware-libs/cairo/blob/1ae57c482447c116f553e23585b54c6be16bfa56/crates/cairo-lang-starknet/test_data/account.cairo#L98)):*
> ```Cairo
>     fn serialize(ref serialized: Array<felt>, input: Call) {
>         let Call{to, selector, calldata } = input;
>         Serde::<ContractAddress>::serialize(ref serialized, to);
> ```

Will this work?



_Suggestion:_
```Cairo
        Serde::serialize(ref serialized, to);
        Serde::serialize(ref serialized, selector);
        Serde::serialize(ref serialized, calldata);
```
___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 102 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2363#-NPnqDDPDKambsOWH-qa:-NPnqDDPDKambsOWH-qb:bwmsiaw) ([raw file](https://github.com/starkware-libs/cairo/blob/1ae57c482447c116f553e23585b54c6be16bfa56/crates/cairo-lang-starknet/test_data/account.cairo#L102)):*
> ```Cairo
>         Serde::<Array::<felt>>::serialize(ref serialized, calldata);
>     }
>     fn deserialize(ref serialized: Span<felt>) -> Option<Call> {
> ```

Add a blank line between functions.
___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 104 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2363#-NPnqioM8pi6VjfT8OUs:-NPnqioM8pi6VjfT8OUt:bhzndbv) ([raw file](https://github.com/starkware-libs/cairo/blob/1ae57c482447c116f553e23585b54c6be16bfa56/crates/cairo-lang-starknet/test_data/account.cairo#L104)):*
> ```Cairo
>     fn deserialize(ref serialized: Span<felt>) -> Option<Call> {
>         Option::Some(
>             Call {
> ```

Avoid relying on the order of member computation by storing the result of deserialize in variables.



_Suggestion:_
```Cairo
        let to = Serde::<ContractAddress>::deserialize(ref serialized)?;
        let selector = Serde::<felt>::deserialize(ref serialized)?;
        let calldata = Serde::<Array::<felt>>::deserialize(ref serialized)?;
        Option::Some(Call {to, selector, calldata})
```
___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 114 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2363#-NPnsz2KDeO_DQgykzwu:-NPnsz2KDeO_DQgykzwv:b-1fevyd) ([raw file](https://github.com/starkware-libs/cairo/blob/1ae57c482447c116f553e23585b54c6be16bfa56/crates/cairo-lang-starknet/test_data/account.cairo#L114)):*
> ```Cairo
> 
> impl ArrayCallSerde of Serde::<Array<Call>> {
>     fn serialize(ref serialized: Array<felt>, mut input: Array<Call>) {
> ```

(I'd prefer the argument name to be called `output`, since `serialized` sounds like it was already computed.)



_Code quote:_
```Cairo
ref serialized: Array<felt>
```
___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 156 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2363#-NPnsTG108iDgY1hYrzg:-NPnrk8u5OwgzsycE20c:b-o221so) ([raw file](https://github.com/starkware-libs/cairo/blob/1ae57c482447c116f553e23585b54c6be16bfa56/crates/cairo-lang-starknet/test_data/account.cairo#L156)):*
> ```Cairo
>         },
>     }
>     if remaining == 0 {
> ```

I guess it's more efficient to put it over the get_gas call. But it probably doesn't matter, as get_gas will be added automatically.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 68 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2363#-NPnpHgn6W_FCn5yXWvn:-NPptKD86Vdbx0VMZ0_g:bfwcjlu) ([raw file](https://github.com/starkware-libs/cairo/blob/1ae57c482447c116f553e23585b54c6be16bfa56/crates/cairo-lang-starknet/test_data/account.cairo#L68)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Shouldn't it be span?
</blockquote></details>

It's a result of deserialization, I'm not sure if there is an advantage in limiting what the user can do with it.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2363)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 78 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2363#-NPnpU9o7KgRqHb-aLc8:-NPpvcqR2m2Ze2ebwitU:bb7sa0c) ([raw file](https://github.com/starkware-libs/cairo/blob/1ae57c482447c116f553e23585b54c6be16bfa56/crates/cairo-lang-starknet/test_data/account.cairo#L78)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Autoformatter bug? (same below)
</blockquote></details>

yes.



_Code quote:_
```Cairo
call_contract_syscall(
```
___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 81 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2363#-NPnpmlPBedcm6mgrxLP:-NPq5f-b5ZVaveGn2w1n:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1ae57c482447c116f553e23585b54c6be16bfa56/crates/cairo-lang-starknet/test_data/account.cairo#L81)):*
> ```Cairo
> 
>         starknet::call_contract_syscall(
>             address: to, entry_point_selector: selector, calldata: calldata
> ```

Done.
___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 98 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2363#-NPnq5BECUj6zJq_gV3A:-NPpvW5z02h8rhV5U2Ev:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1ae57c482447c116f553e23585b54c6be16bfa56/crates/cairo-lang-starknet/test_data/account.cairo#L98)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Will this work?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 102 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2363#-NPnqDDPDKambsOWH-qa:-NPq5h9o40HyaCXWVc3g:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1ae57c482447c116f553e23585b54c6be16bfa56/crates/cairo-lang-starknet/test_data/account.cairo#L102)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Add a blank line between functions.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 104 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2363#-NPnqioM8pi6VjfT8OUs:-NPq5higDktibXEmHcia:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1ae57c482447c116f553e23585b54c6be16bfa56/crates/cairo-lang-starknet/test_data/account.cairo#L104)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Avoid relying on the order of member computation by storing the result of deserialize in variables.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 114 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2363#-NPnsz2KDeO_DQgykzwu:-NPpvTB44_1c_I3LLz9u:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/1ae57c482447c116f553e23585b54c6be16bfa56/crates/cairo-lang-starknet/test_data/account.cairo#L114)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

(I'd prefer the argument name to be called `output`, since `serialized` sounds like it was already computed.)
</blockquote></details>

done
___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 156 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2363#-NPnsTG108iDgY1hYrzg:-NPptvtv3BzJN2gaQ74_:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/1ae57c482447c116f553e23585b54c6be16bfa56/crates/cairo-lang-starknet/test_data/account.cairo#L156)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

I guess it's more efficient to put it over the get_gas call. But it probably doesn't matter, as get_gas will be added automatically.
</blockquote></details>

done.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2363)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 68 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2363#-NPnpHgn6W_FCn5yXWvn:-NPwuVOkA23Bh6Uaadh7:b-57tcb5) ([raw file](https://github.com/starkware-libs/cairo/blob/1ae57c482447c116f553e23585b54c6be16bfa56/crates/cairo-lang-starknet/test_data/account.cairo#L68)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

It's a result of deserialization, I'm not sure if there is an advantage in limiting what the user can do with it.
</blockquote></details>

If this was `Array<felt>` vs `Span<felt>` then deserialization could be cheaper using slicing. However, it's a very specific case. Anyway, that's ok for now.
___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 102 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2363#-NPnqDDPDKambsOWH-qa:-NPwv5QbBj3cQbRe3yfh:blfspul) ([raw file](https://github.com/starkware-libs/cairo/blob/1ae57c482447c116f553e23585b54c6be16bfa56/crates/cairo-lang-starknet/test_data/account.cairo#L102)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Here as well.
___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 114 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2363#-NPnsz2KDeO_DQgykzwu:-NPwvC2xEeaUrVG4jPT5:b17td2u) ([raw file](https://github.com/starkware-libs/cairo/blob/1ae57c482447c116f553e23585b54c6be16bfa56/crates/cairo-lang-starknet/test_data/account.cairo#L114)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

done
</blockquote></details>

Fix in other places in this file as well.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2363)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 102 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2363#-NPnqDDPDKambsOWH-qa:-NQ-3D9K4mMLo-ZnvNWZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1ae57c482447c116f553e23585b54c6be16bfa56/crates/cairo-lang-starknet/test_data/account.cairo#L102)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Here as well.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 114 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2363#-NPnsz2KDeO_DQgykzwu:-NQ-3ZzrCb1p15KDoY0i:b-eoa3cy) ([raw file](https://github.com/starkware-libs/cairo/blob/1ae57c482447c116f553e23585b54c6be16bfa56/crates/cairo-lang-starknet/test_data/account.cairo#L114)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Fix in other places in this file as well.
</blockquote></details>

I don't want to touch serde.cairo in this PR.

**Review by orizi — APPROVED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2363)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2)

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2363#-:-NQB17yP3yKa8pnyAMuF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 114 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2363#-NPnsz2KDeO_DQgykzwu:-NQB10uH1cpfAfagsl3M:b-c9a1b3) ([raw file](https://github.com/starkware-libs/cairo/blob/1ae57c482447c116f553e23585b54c6be16bfa56/crates/cairo-lang-starknet/test_data/account.cairo#L114)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't want to touch serde.cairo in this PR.
</blockquote></details>

I agree (that's why I wrote "in this file").

**Pull request merged**
