### PR TITLE
LS: Make diagnostics state be `FileId` based instead of `Uri`

### PR DESCRIPTION
**Pull request by mkaput**
**Stack**:
- #6615
- #6614 ⬅
- #6613

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6614)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6614#-OBBdFeY6TucmYJqNHUf:-OBBdFeY6TucmYJqNHUg:b885amw) (no related file):*
TODO: Test this manually

**Review by piotmag769 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6614#-:-OBBrhcQ7g5IdbwvNYBL:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6614)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, and @mkaput)

___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/refresh.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6614#-OBKXber8_42-BQoRsYl:-OBKXber8_42-BQoRsYm:bj69kue) ([raw file](https://github.com/starkware-libs/cairo/blob/f736594b8b80602f82d756239c62635bbc0cdfe0/crates/cairo-lang-language-server/src/lang/diagnostics/refresh.rs#L92)):*
> ```XML
>         for file in removed_files {
>             let Some(params) = FileDiagnostics::empty(file).to_lsp(db, trace_macro_diagnostics)
>             else {
> ```

what would happen if there's a db switch for the given `file_id`?



_Code quote:_
```XML
        for file in removed_files {
            let Some(params) = FileDiagnostics::empty(file).to_lsp(db, trace_macro_diagnostics)
            else {
```

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6614)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae and @Draggu)

___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/refresh.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6614#-OBKXber8_42-BQoRsYl:-OBUsPNk3ygsSq-0FzW9:bb757cq) ([raw file](https://github.com/starkware-libs/cairo/blob/f736594b8b80602f82d756239c62635bbc0cdfe0/crates/cairo-lang-language-server/src/lang/diagnostics/refresh.rs#L92)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

what would happen if there's a db switch for the given `file_id`?
</blockquote></details>

:facepalm: This is the reason we went for URLs! I need to document this because it looks like we're losing this tribal knowledge.

I'll drop this PR then

**Comment by mkaput** [comment]
Closing pull request: commit has gone away

**Pull request closed without merging**
