### PR TITLE
Add an inline(should) attribute.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2972)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2972)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2972#-NUG2Gai513qc0aT3ZbP:-NUG2Gai513qc0aT3ZbQ:b-lefas8) (no related file):*
Change target branch.

___

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2972)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2972#-NUG9XD-BIIvDcocdC9n:-NUG9XD-BIIvDcocdC9o:b-hq5eu8) ([raw file](https://github.com/starkware-libs/cairo/blob/1997f833d088b2bb7523e3d929fed9f7d75f8b5a/crates/cairo-lang-lowering/src/inline/mod.rs#L83)):*
> ```XML
>         return Ok(InlineInfo {
>             is_inlinable: true,
>             should_inline: function_id != calling_function_id,
> ```

cant you change it as follows, and avoiding inlining in the actual implementation?



_Suggestion:_
```XML
should_inline: true,
```
___
*[`crates/cairo-lang-lowering/src/inline/test_data/inline` line 1043 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2972#-NUG796pE0T7e5ctuvRe:-NUG796pE0T7e5ctuvRf:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/1997f833d088b2bb7523e3d929fed9f7d75f8b5a/crates/cairo-lang-lowering/src/inline/test_data/inline#L1043)):*
> ```
> //! > ==========================================================================
> 
> //! > Test inlining should indirect self call.
> ```





_Suggestion:_
```
//! > Test #[inline(should)] with indirect self call.
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2972)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2972#-NUG9XD-BIIvDcocdC9n:-NUGx7jMA3H4zRtM3CTG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1997f833d088b2bb7523e3d929fed9f7d75f8b5a/crates/cairo-lang-lowering/src/inline/mod.rs#L83)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

cant you change it as follows, and avoiding inlining in the actual implementation?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/inline/test_data/inline` line 1043 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2972#-NUG796pE0T7e5ctuvRe:-NUGx7-oAVvWw4Nwm8ID:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1997f833d088b2bb7523e3d929fed9f7d75f8b5a/crates/cairo-lang-lowering/src/inline/test_data/inline#L1043)):*
> ```
> //! > ==========================================================================
> 
> //! > Test inlining should indirect self call.
> ```

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 318 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2972#-NUH2F2l5jYREH5Pk-qD:-NUH2F2l5jYREH5Pk-qE:b-rjlmw4) ([raw file](https://github.com/starkware-libs/cairo/blob/01a4f8c6b78152a7d86451f2c1db21dc85f162ef/crates/cairo-lang-lowering/src/inline/mod.rs#L318)):*
> ```XML
>                     if matches!(inline_data.config, InlineConfiguration::Should(_)) {
>                         if !self.is_function_in_call_stack(function_id) {
>                             return self.inline_function(function_id, &stmt.inputs, &stmt.outputs);
> ```

can you avoid calling this twice?



_Code quote:_
```XML
return self.inline_function(function_id, &stmt.inputs, &stmt.outputs);
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 260 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2972#-NUH2__dCk5dCxw7jdYq:-NUH2__dCk5dCxw7jdYr:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/01a4f8c6b78152a7d86451f2c1db21dc85f162ef/crates/cairo-lang-lowering/src/inline/mod.rs#L260)):*
> ```XML
>                 .blocks
>                 .get()
>                 .iter()
> ```





_Suggestion:_
```XML
                .blocks
                .iter()
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 264 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2972#-NUH30xj5bvX1UFiIoK0:-NUH30xj5bvX1UFiIoK1:b7dmr7d) ([raw file](https://github.com/starkware-libs/cairo/blob/01a4f8c6b78152a7d86451f2c1db21dc85f162ef/crates/cairo-lang-lowering/src/inline/mod.rs#L264)):*
> ```XML
>                 .map(|(i, _)| (BlockId(i), calling_function_id))
>                 .collect(),
>         };
> ```

actually, you don't really need the blocks here:



_Suggestion:_
```XML
            block_to_function: (0..flat_lower
                .blocks
                .len())
                .map(BlockId)
                .collect(),
        };
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 366 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2972#-NUH53cUBMyYLsYYo4ZK:-NUH53cUBMyYLsYYo4ZL:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/01a4f8c6b78152a7d86451f2c1db21dc85f162ef/crates/cairo-lang-lowering/src/inline/mod.rs#L366)):*
> ```XML
>             end: self.block_end.clone(),
>         });
>         self.block_to_parent.insert(return_block_id, self.current_block_id.unwrap());
> ```





_Suggestion:_
```XML
 self.block_to_parent.insert(return_block_id, self.block_to_parent[self.current_block_id.unwrap()]);
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2972)* status: 0 of 7 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 260 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2972#-NUH2__dCk5dCxw7jdYq:-NUH9IpFCZGaRH1VtG0C:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/01a4f8c6b78152a7d86451f2c1db21dc85f162ef/crates/cairo-lang-lowering/src/inline/mod.rs#L260)):*
> ```XML
>                 .blocks
>                 .get()
>                 .iter()
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 264 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2972#-NUH30xj5bvX1UFiIoK0:-NUHGelK-B8zz4ZYxpw-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/01a4f8c6b78152a7d86451f2c1db21dc85f162ef/crates/cairo-lang-lowering/src/inline/mod.rs#L264)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

actually, you don't really need the blocks here:
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 318 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2972#-NUH2F2l5jYREH5Pk-qD:-NUHGfR23K5M822IR7Nr:b-xhr90l) ([raw file](https://github.com/starkware-libs/cairo/blob/01a4f8c6b78152a7d86451f2c1db21dc85f162ef/crates/cairo-lang-lowering/src/inline/mod.rs#L318)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

can you avoid calling this twice?
</blockquote></details>

I can, but the condition will be unreadable.
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 366 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2972#-NUH53cUBMyYLsYYo4ZK:-NUHGldw7byKXi73Rwhr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/01a4f8c6b78152a7d86451f2c1db21dc85f162ef/crates/cairo-lang-lowering/src/inline/mod.rs#L366)):*
> ```XML
>             end: self.block_end.clone(),
>         });
>         self.block_to_parent.insert(return_block_id, self.current_block_id.unwrap());
> ```

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 6 files at r1, 3 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2972#-:-NUKw7WK63DEfLjEojxM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
