### PR TITLE
Add option_is_none and option_is_some.

### PR DESCRIPTION
**Pull request by liorgold2**
commit-id:afd62ca1

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1846)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`corelib/option.cairo` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1846#-NMOGlS663VH7U9zXi19:-NMOGlS663VH7U9zXi1A:b-ijc4ux) ([raw file](https://github.com/starkware-libs/cairo/blob/258f565a9bffddd3c8b3865444a4fa6ad32b6f60/corelib/option.cairo#L28)):*
> ```Cairo
> fn option_is_none<T>(val: Option::<T>) -> bool {
>     match val {
>         Option::Some(x) => false,
> ```

why not reuse? optimization?



_Suggestion:_
```Cairo
    !option_is_some(val)
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1846)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @orizi)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1846)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @orizi)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1846)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

___
*[`corelib/option.cairo` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1846#-NMOGlS663VH7U9zXi19:-NMOmVBz3chNQ9EJHmXA:b-2r0pmw) ([raw file](https://github.com/starkware-libs/cairo/blob/482280b1a6e9bd8e6b319b8af55bc1b75f7a275c/corelib/option.cairo#L28)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why not reuse? optimization?
</blockquote></details>

yep. We don't have enough compiler optimizations to make it as efficient, so I just duplicated the code. Maybe in the future...

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1846#-:-NMOnUPNE_s-9zLKnxSz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
