### PR TITLE
Core Lib Documentation: `Debug` module

### PR DESCRIPTION
**Pull request by TAdev0**

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6664)* status: all files reviewed, 1 unresolved discussion (waiting on @TAdev0)

___
*[`corelib/src/debug.cairo` line 22 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6664#-OBu_3ys1ah9NpUYE94g:-OBu_3ys1ah9NpUYE94h:b-2o8mh8) ([raw file](https://github.com/starkware-libs/cairo/blob/8e049326ae0e4af62f8ef403717d95815ce67d3c/corelib/src/debug.cairo#L22)):*
> ```Cairo
> /// arr.append('SomeVeryLongMessage');
> /// arr.print();
> /// ```
> ```

this should probably just move to be over the `PrintTrait`.



_Code quote:_
```Cairo
/// Usage:
/// ```
/// use crate::debug::PrintTrait;
///
/// 1.print();
///
/// (1 == 2).print();
///
/// get_caller_address().print();
///
/// let mut arr = array![];
/// arr.append('1234567890123456789012345678901');
/// arr.append('Sca');
/// arr.append('SomeVeryLongMessage');
/// arr.print();
/// ```
```

**Comment by TAdev0** [comment]
@orizi  `PrintTrait` is `pub(crate)` as well as `PrintTrait` implementations.  We cannot use `print` method directly anymore, thats why we removed this example

**Review by orizi — CHANGES_REQUESTED** [review]
This is incorrect.
It can still be used in older edition.
Additionally correct doc should not be removed, if for some reason scarb doc exports private doc, it shouldn't, but the doc should remain.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6664#-:-OBzBpkI5I8fLsj7n_Rp:brl8rtw)* status: all files reviewed, 2 unresolved discussions (waiting on @TAdev0)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6664#-OBzC75S7BBliR6h_sQe:-OBzC75S7BBliR6h_sQf:b-nuhchg) (no related file):*
Please look at reviews in https://reviewable.io/reviews/starkware-libs/cairo/6664#-

Also for all other PRs.

___

**Comment by TAdev0** [comment]
@orizi  indeed, we can use it with priori editions, my bad.
I restored and slightly updated the comment, moving it over the `PrintTrait` .

**Review by TAdev0 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6664)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6664#-OBzC75S7BBliR6h_sQe:-OBzj4wK128Z8VBUN-WV:b-udxyyq) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

please - use reviewable - checking your PRs without that is harder.
</blockquote></details>

no problem, will do that. Thanks.

**Pull request merged**
