### PR TITLE
Printed all diagnostics in semantic tests (inc. inner modules)

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4005)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4005)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`tests/e2e_test_data/libfuncs/starknet/class_hash` line 8 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4005#-NdUmezY4z8fk-7-Ogbz:-NdUmezZ0Yhqr7da8nPa:b-u2q5ey) ([raw file](https://github.com/starkware-libs/cairo/blob/7bcbb1d0331cb3fb08724325dfab58d6f125a017/tests/e2e_test_data/libfuncs/starknet/class_hash#L8)):*
> ```
> SmallE2ETestRunner
> 
> //! > cairo
> ```

This seems irrelevant

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4005)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`tests/e2e_test_data/libfuncs/starknet/class_hash` line 8 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4005#-NdUmezY4z8fk-7-Ogbz:-NdV-OOg-h_22eADzLBm:br01qyq) ([raw file](https://github.com/starkware-libs/cairo/blob/7bcbb1d0331cb3fb08724325dfab58d6f125a017/tests/e2e_test_data/libfuncs/starknet/class_hash#L8)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

This seems irrelevant
</blockquote></details>

Leftover, removed.

**Comment by yuvalsw** [comment]
*[`crates/cairo-lang-semantic/src/expr/test_data/method` line 126 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4005#-NdVlxxu66JFq3DjlWef:-NdVm6ZdEGTu9u2Pq_r0:bkmw01w) ([raw file](https://github.com/starkware-libs/cairo/blob/0733feb8d63b07c1be02502ff973386e2ce91dd9/crates/cairo-lang-semantic/src/expr/test_data/method#L126)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

This is the error that triggered this PR.
T doesn't exist here. And we didn't get the diagnostic for it in the test.
Now we do, and this fixes it, which is why we don't see added diagnostics in the test.

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4005#-:-NdVvTn26MiUyUEs6VGm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4005)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
