### PR TITLE
Added enable_ap_tracking libfunc.

### PR DESCRIPTION
**Pull request by orizi**
Preparation for major sierra gen performance.

---

**Stack**:
- #2292
- #2288
- #2273
- #2272
- #2271 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2271)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2271)* status: 2 of 9 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/ap_tracking.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2271#-NPI3esyCCNEgs4FNNBN:-NPI3esyCCNEgs4FNNBO:b-st9xgf) ([raw file](https://github.com/starkware-libs/cairo/blob/6f69d42776c2ea3cca2dc99f645fda7770c513e6/crates/cairo-lang-sierra/src/extensions/modules/ap_tracking.rs#L9)):*
> ```XML
> define_libfunc_hierarchy! {
>     pub enum ApTrackingLibfunc {
>         Revoke(RevokeApTrackingLibfunc),
> ```

why not disable?



_Code quote:_
```XML
Revoke
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2271)* status: 2 of 9 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/ap_tracking.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2271#-NPI3esyCCNEgs4FNNBN:-NPI4RX09gvxUXKfrLLf:buvitwt) ([raw file](https://github.com/starkware-libs/cairo/blob/6f69d42776c2ea3cca2dc99f645fda7770c513e6/crates/cairo-lang-sierra/src/extensions/modules/ap_tracking.rs#L9)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why not disable?
</blockquote></details>

revoke does something different - it also invalidates everything on ap.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2271)* status: 3 of 9 files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-ap-change/src/generate_equations.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2271#-NPI5ZGF9b2AUUQoknmR:-NPI5ZGF9b2AUUQoknmS:b-uaz8w6) ([raw file](https://github.com/starkware-libs/cairo/blob/6f69d42776c2ea3cca2dc99f645fda7770c513e6/crates/cairo-lang-sierra-ap-change/src/generate_equations.rs#L40)):*
> ```XML
> #[derive(Clone, Debug, Hash, PartialEq, Eq)]
> enum ChangeBase {
>     FunctionStart(FunctionId),
> ```

why cant you use 
 EnableApTrackingPoint(0),
for that?



_Code quote:_
```XML
FunctionStart(FunctionId),
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2271)* status: 3 of 9 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-ap-change/src/generate_equations.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2271#-NPI5ZGF9b2AUUQoknmR:-NPI8Pos4Zp9ejesvvz_:bw39ske) ([raw file](https://github.com/starkware-libs/cairo/blob/6f69d42776c2ea3cca2dc99f645fda7770c513e6/crates/cairo-lang-sierra-ap-change/src/generate_equations.rs#L40)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why cant you use 
 EnableApTrackingPoint(0),
for that?
</blockquote></details>

Since I need to validate function ap change if I reach a return.
Note that several functions may be solved at the same time.
___
*[`crates/cairo-lang-sierra-ap-change/src/generate_equations.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2271#-NPI5RfO79H7Vbmj7VsR:-NPI8fKe6ezjKAyncLqb:barut9o) ([raw file](https://github.com/starkware-libs/cairo/blob/6f69d42776c2ea3cca2dc99f645fda7770c513e6/crates/cairo-lang-sierra-ap-change/src/generate_equations.rs#L48)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

do you allow two functions to reach the same statement now?
</blockquote></details>

This can allow that in the future, but in this case it is an additional constraint.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs` line 281 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2271#-NPIRks-D4oOLzJO84EI:-NPIRks-D4oOLzJO84EJ:b-u7z1x7) ([raw file](https://github.com/starkware-libs/cairo/blob/6f69d42776c2ea3cca2dc99f645fda7770c513e6/crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs#L281)):*
> ```XML
>                     cairo_lang_sierra_ap_change::ApChange::Known(x) => ApChange::Known(x),
>                     cairo_lang_sierra_ap_change::ApChange::AtLocalsFinalization(_)
>                     | cairo_lang_sierra_ap_change::ApChange::EnableApTracking => ApChange::Known(0),
> ```

why 0?

Note that I also don't understand it for the `AtLocalsFinalization` case



_Code quote:_
```XML
 ApChange::Known(0),
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2271)* status: 7 of 9 files reviewed, 6 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-ap-change/src/generate_equations.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2271#-NPIPh9G7a3kjk0d3BEu:-NPIPh9G7a3kjk0d3BEv:bj1uuba) ([raw file](https://github.com/starkware-libs/cairo/blob/6f69d42776c2ea3cca2dc99f645fda7770c513e6/crates/cairo-lang-sierra-ap-change/src/generate_equations.rs#L46)):*
> ```XML
> /// Information per statement in the analyzed Sierra program.
> #[derive(Clone, Debug)]
> struct StatementInfo {
> ```

what is the StatementInfo when the ap tracking is lost?

 past_ap_change = None?



_Code quote:_
```XML
StatementInfo
```
___
*[`crates/cairo-lang-sierra-ap-change/src/generate_equations.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2271#-NPI5RfO79H7Vbmj7VsR:-NPIPZd_0xfGpFqngH2W:bbgoyoy) ([raw file](https://github.com/starkware-libs/cairo/blob/6f69d42776c2ea3cca2dc99f645fda7770c513e6/crates/cairo-lang-sierra-ap-change/src/generate_equations.rs#L48)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

This can allow that in the future, but in this case it is an additional constraint.
</blockquote></details>

it shouldn't be supported I was just confused because you removed the func_id.
___
*[`crates/cairo-lang-sierra-ap-change/src/generate_equations.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2271#-NPI62MW6pBTJaenHw34:-NPI62MW6pBTJaenHw35:bb3jsdl) ([raw file](https://github.com/starkware-libs/cairo/blob/6f69d42776c2ea3cca2dc99f645fda7770c513e6/crates/cairo-lang-sierra-ap-change/src/generate_equations.rs#L99)):*
> ```XML
>                     let enable_tracking =
>                         matches!(branch_effects.ap_change, ApChange::EnableApTracking)
>                             && base_info.past_ap_change.is_none();
> ```

What happens if this is not None?



_Code quote:_
```XML
base_info.past_ap_change.is_none()
```
___
*[`crates/cairo-lang-sierra-to-casm/src/environment/mod.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2271#-NPIQG8g90UKWakm-VAa:-NPIQG8g90UKWakm-VAb:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6f69d42776c2ea3cca2dc99f645fda7770c513e6/crates/cairo-lang-sierra-to-casm/src/environment/mod.rs#L28)):*
> ```XML
> #[derive(Clone, Debug, Eq, PartialEq)]
> pub struct Environment {
>     /// The ap tracking from the beginning of the current function.
> ```





_Suggestion:_
```XML
// The ap change starting from `ap_tracking_base`.
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2271)* status: 7 of 9 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-ap-change/src/generate_equations.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2271#-NPIPh9G7a3kjk0d3BEu:-NPISiCBCd5Th6EFUKIb:bpiaa84) ([raw file](https://github.com/starkware-libs/cairo/blob/6f69d42776c2ea3cca2dc99f645fda7770c513e6/crates/cairo-lang-sierra-ap-change/src/generate_equations.rs#L46)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what is the StatementInfo when the ap tracking is lost?

 past_ap_change = None?
</blockquote></details>

indeed - the same way as it is currenty in the revoke case (this is the "solve" for unknown ap change functions)
___
*[`crates/cairo-lang-sierra-ap-change/src/generate_equations.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2271#-NPI5RfO79H7Vbmj7VsR:-NPISvZ0DtXT5sxwkCwv:b-lfxz9z) ([raw file](https://github.com/starkware-libs/cairo/blob/6f69d42776c2ea3cca2dc99f645fda7770c513e6/crates/cairo-lang-sierra-ap-change/src/generate_equations.rs#L48)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it shouldn't be supported I was just confused because you removed the func_id.
</blockquote></details>

only removed here - not in sierra-to-casm
___
*[`crates/cairo-lang-sierra-ap-change/src/generate_equations.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2271#-NPI62MW6pBTJaenHw34:-NPIT2SlBOPZPuPcNi4Z:b-ixzqoq) ([raw file](https://github.com/starkware-libs/cairo/blob/6f69d42776c2ea3cca2dc99f645fda7770c513e6/crates/cairo-lang-sierra-ap-change/src/generate_equations.rs#L99)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

What happens if this is not None?
</blockquote></details>

we are already tracked - no need to enable - it already is enabled.
___
*[`crates/cairo-lang-sierra-to-casm/src/environment/mod.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2271#-NPIQG8g90UKWakm-VAa:-NPITRNT52G9M2D9VdPm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6f69d42776c2ea3cca2dc99f645fda7770c513e6/crates/cairo-lang-sierra-to-casm/src/environment/mod.rs#L28)):*
> ```XML
> #[derive(Clone, Debug, Eq, PartialEq)]
> pub struct Environment {
>     /// The ap tracking from the beginning of the current function.
> ```

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs` line 281 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2271#-NPIRks-D4oOLzJO84EI:-NPITThF2wQTTvBXeayM:b-1tx2kv) ([raw file](https://github.com/starkware-libs/cairo/blob/6f69d42776c2ea3cca2dc99f645fda7770c513e6/crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs#L281)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why 0?

Note that I also don't understand it for the `AtLocalsFinalization` case
</blockquote></details>

the enabling does not change ap what so ever - also - a future allocation of a variable does not change ap. (it would just change it in the locals finalization stage)

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2271)* status: all files reviewed, 6 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2271#-NPLjTTn2WjfjudSjfHH:-NPLjTTn2WjfjudSjfHI:bhljsrt) ([raw file](https://github.com/starkware-libs/cairo/blob/4704693b343c339fbde7109e6d3e68b19bb1c55a/crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs#L92)):*
> ```XML
>     /// The change to AP caused by the libfunc in the branch.
>     pub ap_change: ApChange,
>     /// This libfunc is the enable ap tracking libfunc.
> ```

This seems a strange place to put it.

Can't you do a match on the libfunc or something like that?



_Code quote:_
```XML
    /// This libfunc is the enable ap tracking libfunc.
    pub enable_ap_tracking: bool,
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2271)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-ap-change/src/generate_equations.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2271#-NPI62MW6pBTJaenHw34:-NPLkVtp7JL5ZHr2qgn7:b-3ku0ib) ([raw file](https://github.com/starkware-libs/cairo/blob/6f69d42776c2ea3cca2dc99f645fda7770c513e6/crates/cairo-lang-sierra-ap-change/src/generate_equations.rs#L99)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

we are already tracked - no need to enable - it already is enabled.
</blockquote></details>

then maybe you should replace this with an assert.
forbidding enable_tracking when it is already enabled?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2271)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-ap-change/src/generate_equations.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2271#-NPI62MW6pBTJaenHw34:-NPLoA1w1C4KHLKCkYgd:brbijnh) ([raw file](https://github.com/starkware-libs/cairo/blob/6f69d42776c2ea3cca2dc99f645fda7770c513e6/crates/cairo-lang-sierra-ap-change/src/generate_equations.rs#L99)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

then maybe you should replace this with an assert.
forbidding enable_tracking when it is already enabled?
</blockquote></details>

i think generating sierra code would be simpler this way (as when trying to make sure two branches merge correctly - you don't need to have the outside context) - but can do - adding a todo to consider.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2271#-NPLjTTn2WjfjudSjfHH:-NPLoZcZ2lCGB085e8rm:b-2yab) ([raw file](https://github.com/starkware-libs/cairo/blob/4704693b343c339fbde7109e6d3e68b19bb1c55a/crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs#L92)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

This seems a strange place to put it.

Can't you do a match on the libfunc or something like that?
</blockquote></details>

this changes some more in the following prs - this is a configuration it generally could have been called by something else.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2271#-:-NPLtOm0-bJvoQF0zNtl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
