### PR TITLE
Refactor Inliner to use a mapper.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1792)

### CODE REVIEW

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1792#-:-NM36Boh3gjH2KM99h4E:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1792)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1792#-NM3271q07mlacT2fRpb:-NM37ve84dzO-2htdCTP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e42ec4703321f539adcf3d21161a4f0bff451355/crates/cairo-lang-lowering/src/inline/mod.rs#L167)):*
> ```XML
>     }
>     // Pops a block from the queue
>     fn dequeue(&mut self) -> Option<FlatBlock> {
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 175 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1792#-NM32EtI3g0kplbLOAQt:-NM3C9G4-wRQDnLmVMXy:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e42ec4703321f539adcf3d21161a4f0bff451355/crates/cairo-lang-lowering/src/inline/mod.rs#L175)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 176 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1792#-NM32DEJ1ukVN8ish2E3:-NM3C8Q83aMn3rqD8UOI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e42ec4703321f539adcf3d21161a4f0bff451355/crates/cairo-lang-lowering/src/inline/mod.rs#L176)):*
> ```XML
> }
> pub struct Mapper<'a, 'b> {
>     ctx: &'a mut LoweringContext<'b>,
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 191 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1792#-NM32JAKEATsm22FUVKa:-NM3C8s_3PCJ3mS38aZc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e42ec4703321f539adcf3d21161a4f0bff451355/crates/cairo-lang-lowering/src/inline/mod.rs#L191)):*
> ```XML
>     }
>     // Rebuilds the statement with renamed var and block ids.
>     fn rebuild_statement(&mut self, statement: &Statement) -> Statement {
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1792)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 171 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1792#-NM3XuMA5I13_BO5ckoP:-NM3XuMA5I13_BO5ckoQ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5fa35faa68ceed56c216b47f7089a5cf4d7bd3e5/crates/cairo-lang-lowering/src/inline/mod.rs#L171)):*
> ```XML
>     }
>     /// Finalizes a block.
>     fn finalize(&mut self, block: FlatBlock) -> BlockId {
> ```





_Suggestion:_
```XML
    /// A Queue of blocks on which we want to apply the FunctionInlinerRewriter.
    block_queue: BlockQueue,
}

pub struct BlockQueue {
    /// A Queue of blocks that require processing.
    block_queue: VecDeque<FlatBlock>,
    /// The new blocks that are were created during the inlining.
    flat_blocks: FlatBlocks,
}
impl BlockQueue {
    /// Enqueues the block for processing and returns the block_id that this
    /// block is going to get in self.flat_blocks.
    fn enqueue_block(&mut self, block: FlatBlock) -> BlockId {
        self.block_queue.push_back(block);
        BlockId(self.flat_blocks.len() + self.block_queue.len())
    }
    
    /// Pops a block from the queue.
    fn dequeue(&mut self) -> Option<FlatBlock> {
        self.block_queue.pop_front()
    }
    
    /// Finalizes a block.
    fn finalize(&mut self, block: FlatBlock) -> BlockId {
        self.flat_blocks.alloc(block)
    }
}
```

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1792#-:-NM3XyhI-lV2ov5ZucbX:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1792)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 171 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1792#-NM3XuMA5I13_BO5ckoP:-NM3ZlEJCHyI0PZwYywz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5fa35faa68ceed56c216b47f7089a5cf4d7bd3e5/crates/cairo-lang-lowering/src/inline/mod.rs#L171)):*
> ```XML
>     }
>     /// Finalizes a block.
>     fn finalize(&mut self, block: FlatBlock) -> BlockId {
> ```

Done.

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1792)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1792)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
