### PR TITLE
Refactored debug print to be based on format, for testing

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4324)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4324)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1938 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4324#-Ni3Q_OvEGuyeReHfugl:-Ni3Q_OvEGuyeReHfugm:bipxsh7) ([raw file](https://github.com/starkware-libs/cairo/blob/7619ead34ee6f30373d84b14b0b179234ed2ca36/crates/cairo-lang-runner/src/casm_run/mod.rs#L1938)):*
> ```XML
>         }
>         CoreHint::DebugPrint { start, end } => {
>             println!("{}", format_for_debug(read_felts(vm, start, end)?.into_iter()));
> ```

maybe separate the case of getting a single long string to not print the debug?
(just to remove the need for the extra print hint)



_Code quote:_
```XML
 println!("{}", format_for_debug(read_felts(vm, start, end)?.into_iter()));
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4324)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1938 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4324#-Ni3Q_OvEGuyeReHfugl:-Ni4wX9e6Y7KOor1k1g8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7619ead34ee6f30373d84b14b0b179234ed2ca36/crates/cairo-lang-runner/src/casm_run/mod.rs#L1938)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe separate the case of getting a single long string to not print the debug?
(just to remove the need for the extra print hint)
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4324)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 2136 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4324#-Ni57yRc1ZBO22plTXz4:-Ni57yRc1ZBO22plTXz5:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/7842ede5e69b36ce245ede0c95f0dbfb0d277317/crates/cairo-lang-runner/src/casm_run/mod.rs#L2136)):*
> ```XML
>             }
>         })
>         .join("")
> ```





_Suggestion:_
```XML
    if let [item] = items {
        if item.is_string {
            return item.item.to_string(); // no endline.
        }
    }
    items
        .into_iter()
        .map(|item| format!("[DEBUG]\t{}\n", item.item))
        .join("")
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4324)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 2136 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4324#-Ni57yRc1ZBO22plTXz4:-Ni5IcciD2WsYZCvzZHl:b-z8uxpu) ([raw file](https://github.com/starkware-libs/cairo/blob/7842ede5e69b36ce245ede0c95f0dbfb0d277317/crates/cairo-lang-runner/src/casm_run/mod.rs#L2136)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Why? I think that if we have a string together with another item we still need to print the string as is.
</blockquote></details>

We shouldn't print any newlines for the normal bytearray print.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4324)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 2136 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4324#-Ni57yRc1ZBO22plTXz4:-Ni5UdgF4L-9m-qt25vY:b-seo9k0) ([raw file](https://github.com/starkware-libs/cairo/blob/7842ede5e69b36ce245ede0c95f0dbfb0d277317/crates/cairo-lang-runner/src/casm_run/mod.rs#L2136)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

We shouldn't print any newlines for the normal bytearray print.
</blockquote></details>

Changed so that if we have a single one we print as is. If it comes with more, they are separated with newlines as before.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4324#-:-Ni5vV298ahbYBSsUbCe:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
