### PR TITLE
Fix formatting of generic args.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4081)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4081)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`corelib/src/starknet/syscalls.cairo` line 44 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4081#-NebIQ89-k1N0gW-ezuy:-NebIQ8A0E_gece7kIh1:bpdth9i) ([raw file](https://github.com/starkware-libs/cairo/blob/92eb4819e809b954b6ee12fb13ea00e9ac7d2851/corelib/src/starknet/syscalls.cairo#L44)):*
> ```Cairo
> extern fn get_execution_info_syscall() -> SyscallResult<
>     Box<starknet::info::ExecutionInfo>
> > implicits(GasBuiltin, System) nopanic;
> ```

Not sure about the breaking order here, if that's better or the function params should break before, WDYT?



_Code quote:_
```Cairo
// Gets information about the current execution.
extern fn get_execution_info_syscall() -> SyscallResult<
    Box<starknet::info::ExecutionInfo>
> implicits(GasBuiltin, System) nopanic;
```

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4081)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`corelib/src/starknet/syscalls.cairo` line 44 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4081#-NebIQ89-k1N0gW-ezuy:-Nec_0Rl5BMHrl1Gu6w7:b5rmnp8) ([raw file](https://github.com/starkware-libs/cairo/blob/92eb4819e809b954b6ee12fb13ea00e9ac7d2851/corelib/src/starknet/syscalls.cairo#L44)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Not sure about the breaking order here, if that's better or the function params should break before, WDYT?
</blockquote></details>

Let's discuss f2f

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4081)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4081)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`corelib/src/starknet/syscalls.cairo` line 44 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4081#-NebIQ89-k1N0gW-ezuy:-NfH5ORWCaSCzjXM2y7K:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/92eb4819e809b954b6ee12fb13ea00e9ac7d2851/corelib/src/starknet/syscalls.cairo#L44)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Let's discuss f2f
</blockquote></details>

Done.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4081#-:-NfH8CoL8dZYsOI8z1o_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
