### PR TITLE
Added get_caller_address libfunc.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:5f05488c

---

**Stack**:
- #1866
- #1864
- #1863
- #1862
- #1860
- #1857 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 9 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1857)* status: 9 of 13 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/starknet/getter.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1857#-NMSFEcv4CxFiNUBPMSC:-NMSFEcv4CxFiNUBPMSD:bng2urm) ([raw file](https://github.com/starkware-libs/cairo/blob/0921406a97b579b708cefc501830133bebab463f/crates/cairo-lang-sierra-to-casm/src/invocations/starknet/getter.rs#L8)):*
> ```XML
> use crate::invocations::{add_input_variables, get_non_fallthrough_statement_id};
> 
> /// Builds instructions for StarkNet getter system call.
> ```

+ consider getting an assert on the info type.



_Suggestion:_
```XML
/// Builds instructions for StarkNet getter system call that return a result of size 1.
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1857)* status: 9 of 13 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/starknet/getter.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1857#-NMSFEcv4CxFiNUBPMSC:-NMSGApf4TaUrsQh2DxY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2bf56ce14186a8b0d4733ed63158fae928ecbbcb/crates/cairo-lang-sierra-to-casm/src/invocations/starknet/getter.rs#L8)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

+ consider getting an assert on the info type.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 13 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1857#-:-NMSK5xBDyi_TsgyYjRB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1857)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1857)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1857)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
