### PR TITLE
Change verification to in Identifier to parser

### PR DESCRIPTION
**Pull request by Tomer-StarkWare**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5788)

### CODE REVIEW

**Review by TomerStarkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5788)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware, @orizi, and @Tomer-StarkWare)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1700 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5788#-O-FSLrkEtsiOsX2QWOv:-O-FSLrkEtsiOsX2QWOw:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/8d39f2d5d518a1ac4d3b0ed4e60e32b5491f0eb6/crates/cairo-lang-parser/src/parser.rs#L1700)):*
> ```XML
>         let for_kw = self.take::<TerminalFor>();
>         let pattern = self.parse_pattern();
>         // TODO(Tomer-StarkWare): Check identifier is 'in'.
> ```

remove
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/for` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5788#-O-FSSqh6RrrTQChO12Y:-O-FSSqh6RrrTQChO12Z:bqon74d) ([raw file](https://github.com/starkware-libs/cairo/blob/8d39f2d5d518a1ac4d3b0ed4e60e32b5491f0eb6/crates/cairo-lang-parser/src/parser_test_data/partial_trees/for#L42)):*
> ```
> //! > ==========================================================================
> 
> //! > Test bad identifier for loop
> ```

this test can go in the diagnostics folder (in a separate file)
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/for` line 72 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5788#-O-FSgew5Tin5AFql4Sh:-O-FSgew5Tin5AFql4Si:bhlvvry) ([raw file](https://github.com/starkware-libs/cairo/blob/8d39f2d5d518a1ac4d3b0ed4e60e32b5491f0eb6/crates/cairo-lang-parser/src/parser_test_data/partial_trees/for#L72)):*
> ```
>     │   └── item #0 (kind: PathSegmentSimple)
>     │       └── ident (kind: TokenIdentifier): 'index'
>     ├── identifier (kind: TokenIdentifier): 'at'
> ```

I think we want at to parsed as expr and "in" to be missing

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5788)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @orizi, @Tomer-StarkWare, and @TomerStarkware)

___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/for` line 72 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5788#-O-FSgew5Tin5AFql4Sh:-O-FT5bH3cO7YFRzTy3R:b-ebdh4d) ([raw file](https://github.com/starkware-libs/cairo/blob/8d39f2d5d518a1ac4d3b0ed4e60e32b5491f0eb6/crates/cairo-lang-parser/src/parser_test_data/partial_trees/for#L72)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

I think we want at to parsed as expr and "in" to be missing
</blockquote></details>

Agree, I think you'll have to do it with `take_raw` tricks.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5788)* status: all files reviewed, 4 unresolved discussions (waiting on @Tomer-StarkWare and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/for` line 85 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5788#-O-F_A141wIdwSDcuIjZ:-O-F_A15-gOAxrPLc9oH:bae0wit) ([raw file](https://github.com/starkware-libs/cairo/blob/8d39f2d5d518a1ac4d3b0ed4e60e32b5491f0eb6/crates/cairo-lang-semantic/src/expr/test_data/for#L85)):*
> ```
> error: Missing identifier token, expected in.
>  --> lib.cairo:3:12
>     for _x at _iter {
> ```

after moving the test to diagnostics - remove the test here.

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5788)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi and @TomerStarkware)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1700 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5788#-O-FSLrkEtsiOsX2QWOv:-O-FTITx8Yh9CIg1EHhU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8d39f2d5d518a1ac4d3b0ed4e60e32b5491f0eb6/crates/cairo-lang-parser/src/parser.rs#L1700)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/for` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5788#-O-FSSqh6RrrTQChO12Y:-O-FgFYi8lNNDkH_AR50:b-lnmzu5) ([raw file](https://github.com/starkware-libs/cairo/blob/8d39f2d5d518a1ac4d3b0ed4e60e32b5491f0eb6/crates/cairo-lang-parser/src/parser_test_data/partial_trees/for#L42)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

this test can go in the diagnostics folder (in a separate file)
</blockquote></details>

We want to see the expected_tree; maybe it should stay here.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/for` line 72 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5788#-O-FSgew5Tin5AFql4Sh:-O-G528dDOpdMMM_6xnL:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8d39f2d5d518a1ac4d3b0ed4e60e32b5491f0eb6/crates/cairo-lang-parser/src/parser_test_data/partial_trees/for#L72)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Agree, I think you'll have to do it with `take_raw` tricks.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/for` line 85 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5788#-O-F_A141wIdwSDcuIjZ:-O-FgZhT2ASci-KvXHJr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8d39f2d5d518a1ac4d3b0ed4e60e32b5491f0eb6/crates/cairo-lang-semantic/src/expr/test_data/for#L85)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

after moving the test to diagnostics - remove the test here.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5788)* status: all files reviewed, 3 unresolved discussions (waiting on @TomerStarkware)

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5788)* status: all files reviewed, 4 unresolved discussions (waiting on @Tomer-StarkWare and @TomerStarkware)

___
*[`crates/cairo-lang-parser/src/diagnostic.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5788#-O-G90Bo3x4QI43GFRX4:-O-G90Bo3x4QI43GFRX5:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f335b25211b00ab083ae6ac4f015033fead6f72b/crates/cairo-lang-parser/src/diagnostic.rs#L25)):*
> ```XML
>     MissingWrappedArgList,
>     MissingPatteren,
>     ExpectedToken,
> ```





_Suggestion:_
```XML
ExpectedInToken,
```

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5788)* status: all files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5788#-:-O-GA_-W4eOAkYdWX8He:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @TomerStarkware)

**Review by TomerStarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5788)* status: all files reviewed, 3 unresolved discussions (waiting on @Tomer-StarkWare)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1706 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5788#-O-GMnIH6wfRyBXJRKMz:-O-GMnIH6wfRyBXJRKN-:b-5ssggy) ([raw file](https://github.com/starkware-libs/cairo/blob/ec153ca18697f5999693eedefcd854831c6ddc4c/crates/cairo-lang-parser/src/parser.rs#L1706)):*
> ```XML
>                     ident,
>                     ParserDiagnosticKind::SkippedElement {
>                         element_name: or_an_attribute!(MODULE_ITEM_DESCRIPTION).into(),
> ```

element_name: "'in'"
___
*[`crates/cairo-lang-parser/src/parser.rs` line 1710 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5788#-O-GMidp50-2Pi8k-VA7:-O-GMidp50-2Pi8k-VA8:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/ec153ca18697f5999693eedefcd854831c6ddc4c/crates/cairo-lang-parser/src/parser.rs#L1710)):*
> ```XML
>                 );
>                 self.create_and_report_missing::<TerminalIdentifier>(
>                     ParserDiagnosticKind::ExpectedInToken,
> ```

remove
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/for` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5788#-O-FSSqh6RrrTQChO12Y:-O-GLogf4iZaRI5u8oPx:b32wtd) ([raw file](https://github.com/starkware-libs/cairo/blob/8d39f2d5d518a1ac4d3b0ed4e60e32b5491f0eb6/crates/cairo-lang-parser/src/parser_test_data/partial_trees/for#L42)):*
<details><summary><i>Previously, Tomer-StarkWare wrote…</i></summary><blockquote>

We want to see the expected_tree; maybe it should stay here.
</blockquote></details>

ok

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5788)* status: all files reviewed, 3 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1706 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5788#-O-GMnIH6wfRyBXJRKMz:-O-GPoXi2eJrBbaa9gof:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ec153ca18697f5999693eedefcd854831c6ddc4c/crates/cairo-lang-parser/src/parser.rs#L1706)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

element_name: "'in'"
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser.rs` line 1710 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5788#-O-GMidp50-2Pi8k-VA7:-O-GPon5DBIFp4b1BAOv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ec153ca18697f5999693eedefcd854831c6ddc4c/crates/cairo-lang-parser/src/parser.rs#L1710)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5788)* status: all files reviewed, 3 unresolved discussions (waiting on @Tomer-StarkWare and @TomerStarkware)

**Review by TomerStarkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5788#-:-O-GxHHE9vLJJBxi03TL:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Tomer-StarkWare)

**Pull request merged**
