### PR TITLE
Check ref compatability with trait.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1179)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1179)* status: all files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/semantic/src/diagnostic.rs` line 162 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1179#-NI7MxqrAZaQv9jXlHt8:-NI7MxqrAZaQv9jXlHt9:busu1vd) ([raw file](https://github.com/starkware-libs/cairo/blob/e240b6fea6929afa9f7d6020cb13eba8708f4694/crates/semantic/src/diagnostic.rs#L162)):*
> ```XML
>                 let function_name = impl_function_id.name(defs_db);
>                 format!(
>                     "Parameter mutability of impl function `{}::{}` is incompatible with `{}::{}`.",
> ```

How about adding the existing/desired mutability (existing is visible via the pointers, desired is not, so at least the desired)



_Code quote:_
```XML
mutability
```
___
*[`crates/semantic/src/diagnostic.rs` line 165 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1179#-NI7JRxv3i1XEhw5aLAU:-NI7JRxv3i1XEhw5aLAV:bb74rda) ([raw file](https://github.com/starkware-libs/cairo/blob/e240b6fea6929afa9f7d6020cb13eba8708f4694/crates/semantic/src/diagnostic.rs#L165)):*
> ```XML
>                     impl_id.name(defs_db),
>                     function_name,
>                     trait_id.name(defs_db),
> ```

Also in other similar diagnostics...



_Suggestion:_
```XML
                format!(
                    "Parameter mutability of impl function `{}::{function_name}` is incompatible with `{}::{function_name}`.",
                    impl_id.name(defs_db),
                    trait_id.name(defs_db),
                )
```
___
*[`crates/semantic/src/items/imp.rs` line 513 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1179#-NI7Kppi6DlL7vWC5jms:-NI7Kppi6DlL7vWC5jmt:bpogeer) ([raw file](https://github.com/starkware-libs/cairo/blob/e240b6fea6929afa9f7d6020cb13eba8708f4694/crates/semantic/src/items/imp.rs#L513)):*
> ```XML
>     {
>         let expected_ty = trait_param.ty;
>         let actual_ty = param.ty;
> ```

move it right before the relevant validation.



_Code quote:_
```XML
        let expected_ty = trait_param.ty;
        let actual_ty = param.ty;
```
___
*[`crates/semantic/src/items/imp.rs` line 517 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1179#-NI7KvW5CpMge8MPbos1:-NI7KvW5CpMge8MPbos2:b9xajbd) ([raw file](https://github.com/starkware-libs/cairo/blob/e240b6fea6929afa9f7d6020cb13eba8708f4694/crates/semantic/src/items/imp.rs#L517)):*
> ```XML
>         if trait_param.mutability != param.mutability {
>             diagnostics.report(
>                 &signature_syntax.parameters(syntax_db).elements(syntax_db)[idx],
> ```

Which one should be first?
What happens if both type and mutability differ? 

I checked rust.
1. It says both at once: "change the parameter type to match the trait: `&mut u32`"
2. It points only to the type, not to the whole param with its type.



_Code quote:_
```XML
        if trait_param.mutability != param.mutability {
            diagnostics.report(
                &signature_syntax.parameters(syntax_db).elements(syntax_db)[idx],
                WrongParameterMutability { impl_id, impl_function_id, trait_id },
            );
        }
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1179)* status: all files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/semantic/src/diagnostic.rs` line 162 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1179#-NI7MxqrAZaQv9jXlHt8:-NIB_dLZAoYTLXjfljLC:bh9igip) ([raw file](https://github.com/starkware-libs/cairo/blob/e240b6fea6929afa9f7d6020cb13eba8708f4694/crates/semantic/src/diagnostic.rs#L162)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

How about adding the existing/desired mutability (existing is visible via the pointers, desired is not, so at least the desired)
</blockquote></details>

The problem is that the Immutable -> no modifiers connection is not obvious.
___
*[`crates/semantic/src/diagnostic.rs` line 165 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1179#-NI7JRxv3i1XEhw5aLAU:-NIB_of3-NY9lAyOXnfd:b-ju85na) ([raw file](https://github.com/starkware-libs/cairo/blob/e240b6fea6929afa9f7d6020cb13eba8708f4694/crates/semantic/src/diagnostic.rs#L165)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Also in other similar diagnostics...
</blockquote></details>

I find it strange the some of the argument are inlined and some of them are not.
___
*[`crates/semantic/src/items/imp.rs` line 513 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1179#-NI7Kppi6DlL7vWC5jms:-NIBYdqY5q23pq2BBHRe:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e240b6fea6929afa9f7d6020cb13eba8708f4694/crates/semantic/src/items/imp.rs#L513)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

move it right before the relevant validation.
</blockquote></details>

Done.
___
*[`crates/semantic/src/items/imp.rs` line 517 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1179#-NI7KvW5CpMge8MPbos1:-NIBYeVf9Mi5J0Qy6RLf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e240b6fea6929afa9f7d6020cb13eba8708f4694/crates/semantic/src/items/imp.rs#L517)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Which one should be first?
What happens if both type and mutability differ? 

I checked rust.
1. It says both at once: "change the parameter type to match the trait: `&mut u32`"
2. It points only to the type, not to the whole param with its type.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1179)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/semantic/src/diagnostic.rs` line 162 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1179#-NI7MxqrAZaQv9jXlHt8:-NIB_xYF-Co44JXbDUy3:b-rzp6ci) ([raw file](https://github.com/starkware-libs/cairo/blob/e240b6fea6929afa9f7d6020cb13eba8708f4694/crates/semantic/src/diagnostic.rs#L162)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

The problem is that the Immutable -> no modifiers connection is not obvious.
</blockquote></details>

the pointer availability depends on the the code. I can make an example where it is the otherway around.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1179)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/semantic/src/items/imp.rs` line 517 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1179#-NI7KvW5CpMge8MPbos1:-NIBcq53DGNlI0zk9BpZ:b-s8m4gn) ([raw file](https://github.com/starkware-libs/cairo/blob/e240b6fea6929afa9f7d6020cb13eba8708f4694/crates/semantic/src/items/imp.rs#L517)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

btw, did we put the modifiers in the wrong place for parameters?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1179)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/semantic/src/items/imp.rs` line 517 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1179#-NI7KvW5CpMge8MPbos1:-NIBcuMtENBRPnvnI2DF:b9md8co) ([raw file](https://github.com/starkware-libs/cairo/blob/e240b6fea6929afa9f7d6020cb13eba8708f4694/crates/semantic/src/items/imp.rs#L517)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

btw, did we put the modifiers in the wrong place for parameters?
</blockquote></details>

should they be in the type?

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1179)* status: all files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/semantic/src/items/imp.rs` line 517 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1179#-NI7KvW5CpMge8MPbos1:-NIBm8GG36kqLwhsHKE_:bdawyh3) ([raw file](https://github.com/starkware-libs/cairo/blob/e240b6fea6929afa9f7d6020cb13eba8708f4694/crates/semantic/src/items/imp.rs#L517)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

should they be in the type?
</blockquote></details>

Hmmm, maybe ref?
In Rust they can be on both. On the type mut can only come with & and it means you can change the variable that was received from outside (somewhat like our ref). On the var name means the var can be changed locally. Ideally it would probably appear elsewhere, but there is no good place for it. BTW, it doesn't have to match the signature in this case.
And for us:
I think 'mut' is in the right place, but it's not an error if it doesn't match the trait function signature. Actually, it should not be allowed at all in trait function signature.
And 'ref' - it should match the trait function signature, and thus should be on the type.

So we probably need some changes around here...
___
*[`crates/semantic/src/items/tests/trait` line 107 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1179#-NIBnk2P7oeQWlCFHlPM:-NIBnk2P7oeQWlCFHlPN:b-qmji3r) ([raw file](https://github.com/starkware-libs/cairo/blob/807fe4d7f7606b372f7cb509dde0ecde8ea3f9b8/crates/semantic/src/items/tests/trait#L107)):*
> ```
>                        ^**^
> 
> error: Parameter mutability of impl function `MyImpl2::param_test` is incompatible with `MyTrait::param_test`.
> ```

I'd say we need to add the expected mutability here, but it's gonna change to only be a ref, so the message would be different...



_Code quote:_
```
rameter mutability 
```

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1179)* status: all files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/semantic/src/items/imp.rs` line 517 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1179#-NI7KvW5CpMge8MPbos1:-NIBqEua2aGKtcJh9cfr:b-gl2xts) ([raw file](https://github.com/starkware-libs/cairo/blob/e240b6fea6929afa9f7d6020cb13eba8708f4694/crates/semantic/src/items/imp.rs#L517)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Hmmm, maybe ref?
In Rust they can be on both. On the type mut can only come with & and it means you can change the variable that was received from outside (somewhat like our ref). On the var name means the var can be changed locally. Ideally it would probably appear elsewhere, but there is no good place for it. BTW, it doesn't have to match the signature in this case.
And for us:
I think 'mut' is in the right place, but it's not an error if it doesn't match the trait function signature. Actually, it should not be allowed at all in trait function signature.
And 'ref' - it should match the trait function signature, and thus should be on the type.

So we probably need some changes around here...
</blockquote></details>

I talked with Shahar about it. We agreed on this:
1. The ref/mut remain on the variable name (the reason is that ref is not part of a real type as opposed to &mut in Rust).
2. mut is not allowed on trait function signatures (semantically).
3. Only ref in the impl function signature is matched against the trait function signature.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1179)* status: all files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/semantic/src/diagnostic.rs` line 162 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1179#-NI7MxqrAZaQv9jXlHt8:-NIBrAkKEg0KFb-gGDnE:b-1ggo7j) ([raw file](https://github.com/starkware-libs/cairo/blob/e240b6fea6929afa9f7d6020cb13eba8708f4694/crates/semantic/src/diagnostic.rs#L162)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

the pointer availability depends on the the code. I can make an example where it is the otherway around.
</blockquote></details>

I don't completely follow. Please clarify.
___
*[`crates/semantic/src/diagnostic.rs` line 165 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1179#-NI7JRxv3i1XEhw5aLAU:-NIBrICyEgw_zNYtavkE:b9ntn0o) ([raw file](https://github.com/starkware-libs/cairo/blob/e240b6fea6929afa9f7d6020cb13eba8708f4694/crates/semantic/src/diagnostic.rs#L165)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I find it strange the some of the argument are inlined and some of them are not.
</blockquote></details>

I understand, but IMO it's a bit easier to read as you need less matching of params to their location in the string.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1179)* status: all files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/semantic/src/items/imp.rs` line 517 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1179#-NI7KvW5CpMge8MPbos1:-NIBrZbf8aco3KymMtam:b-bdqkxa) ([raw file](https://github.com/starkware-libs/cairo/blob/e240b6fea6929afa9f7d6020cb13eba8708f4694/crates/semantic/src/items/imp.rs#L517)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I talked with Shahar about it. We agreed on this:
1. The ref/mut remain on the variable name (the reason is that ref is not part of a real type as opposed to &mut in Rust).
2. mut is not allowed on trait function signatures (semantically).
3. Only ref in the impl function signature is matched against the trait function signature.
</blockquote></details>

Do I need different messages for `ref` missing and should not be `ref` ?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/semantic/src/diagnostic.rs` line 162 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1179#-NI7MxqrAZaQv9jXlHt8:-NICoqVF0Gp1oFGr2ad_:b2md9nb) ([raw file](https://github.com/starkware-libs/cairo/blob/e240b6fea6929afa9f7d6020cb13eba8708f4694/crates/semantic/src/diagnostic.rs#L162)):*
> existing is visible via the pointers, desired is not, so at least the desired
it might be the case that existing is nothing and the desired is `ref`.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1179)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/semantic/src/diagnostic.rs` line 177 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1179#-NIDK88m7EPs9210dnX3:-NIDK88n-IZcwwi2RkVr:b-h7esqi) ([raw file](https://github.com/starkware-libs/cairo/blob/9d0be644332205f891da992cfd0cd8918bc5d92b/crates/semantic/src/diagnostic.rs#L177)):*
> ```XML
>                 let function_name = impl_function_id.name(defs_db);
>                 format!(
>                     "`{}::{}` has an incompatible type for trait `{}::{}`. Remove `ref` modifier.",
> ```

The error messages are inconsistent.
Also, for now we don't suggest anything, so let's keep it this way for now. I suggest:
"Parameter of impl function`{}::{}` is incompatible with `{}::{}`. It should be a reference".
"Parameter of impl function`{}::{}` is incompatible with `{}::{}`. It should not be a reference".



_Code quote:_
```XML
{}::{}` has an incompatible type for trait `{}::{}`. Remove 
```
___
*[`crates/semantic/src/diagnostic.rs` line 419 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1179#-NIDLxXg948qoQke-tBq:-NIDLxXg948qoQke-tBr:b-a8i724) ([raw file](https://github.com/starkware-libs/cairo/blob/9d0be644332205f891da992cfd0cd8918bc5d92b/crates/semantic/src/diagnostic.rs#L419)):*
> ```XML
>         trait_id: TraitId,
>     },
>     ParamaterCannotBeReference {
> ```

consider changing here too, to "Should" and "ShouldNot"



_Code quote:_
```XML
    ParamaterMustBeReference {
        impl_id: ImplId,
        impl_function_id: ImplFunctionId,
        trait_id: TraitId,
    },
    ParamaterCannotBeReference {
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1179)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/semantic/src/diagnostic.rs` line 177 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1179#-NIDK88m7EPs9210dnX3:-NIR9NFr9CollX4Kmte-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9d0be644332205f891da992cfd0cd8918bc5d92b/crates/semantic/src/diagnostic.rs#L177)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

The error messages are inconsistent.
Also, for now we don't suggest anything, so let's keep it this way for now. I suggest:
"Parameter of impl function`{}::{}` is incompatible with `{}::{}`. It should be a reference".
"Parameter of impl function`{}::{}` is incompatible with `{}::{}`. It should not be a reference".
</blockquote></details>

Done.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1179#-:-NIRNv0-9-nVb-GVUlVv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
