### PR TITLE
Added external files.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #6227
- #6225
- #6224
- #6223 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6223)

### CODE REVIEW

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6223#-:-O4_cAOK5jsDYx9wJVJS:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6223)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-filesystem/src/ids.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6223#-O4eaqa46GZarupNoLaR:-O4eQFkM9phWivE74zw8:bi36q6s) ([raw file](https://github.com/starkware-libs/cairo/blob/b23f1ca2aaacd669559566cdceb5566ae9c06bdf/crates/cairo-lang-filesystem/src/ids.rs#L65)):*
> ```XML
>     OnDisk(PathBuf),
>     Virtual(VirtualFile),
>     External(u32),
> ```

please add:

```rust
struct ExternalFileId(u32)
```

to hide `u32` as implementation detail

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6223)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-filesystem/src/ids.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6223#-O4eaqa46GZarupNoLaR:-O4ekYPB2Vu5oItrgdIs:b5ck8vn) ([raw file](https://github.com/starkware-libs/cairo/blob/b23f1ca2aaacd669559566cdceb5566ae9c06bdf/crates/cairo-lang-filesystem/src/ids.rs#L65)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

please add:

```rust
struct ExternalFileId(u32)
```

to hide `u32` as implementation detail
</blockquote></details>

this becomes a `salsa::InternId` in a followup PR - so not really sensible.

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6223)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-filesystem/src/ids.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6223#-O4eaqa46GZarupNoLaR:-O4eqMiKCl-znz5mg1ri:b-ch9qex) ([raw file](https://github.com/starkware-libs/cairo/blob/b23f1ca2aaacd669559566cdceb5566ae9c06bdf/crates/cairo-lang-filesystem/src/ids.rs#L65)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this becomes a `salsa::InternId` in a followup PR - so not really sensible.
</blockquote></details>

`salsa::InternId` is also an implementation-detail-kind type just like `u32`, isn't it?

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6223)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6223)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 111 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6223#-O4ezAci3rdpZqewMCZy:-O4ezAci3rdpZqewMCZz:b-wcxpy1) ([raw file](https://github.com/starkware-libs/cairo/blob/b23f1ca2aaacd669559566cdceb5566ae9c06bdf/crates/cairo-lang-filesystem/src/db.rs#L111)):*
> ```XML
> 
> /// A trait for defining files external to the `filesystem` crate.
> pub trait ExternalFiles {
> ```

why couldn't this be just a new query group?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6223)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 111 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6223#-O4ezAci3rdpZqewMCZy:-O4f3N9t4y3Srd2lFJTb:b-7k3kzk) ([raw file](https://github.com/starkware-libs/cairo/blob/b23f1ca2aaacd669559566cdceb5566ae9c06bdf/crates/cairo-lang-filesystem/src/db.rs#L111)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

why couldn't this be just a new query group?
</blockquote></details>

how would that work?
the idea is using it by a QueryGroup that already depends on filesystem - so that would be a cyclic dependency.
___
*[`crates/cairo-lang-filesystem/src/ids.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6223#-O4eaqa46GZarupNoLaR:-O4f3Zf56gftbCcV9sS1:bcn2j5r) ([raw file](https://github.com/starkware-libs/cairo/blob/b23f1ca2aaacd669559566cdceb5566ae9c06bdf/crates/cairo-lang-filesystem/src/ids.rs#L65)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

`salsa::InternId` is also an implementation-detail-kind type just like `u32`, isn't it?
</blockquote></details>

but that wrap is meaningless.

the entire idea is that it is an external implementation using another query - the wrapper type would not solve anything.

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6223)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 111 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6223#-O4ezAci3rdpZqewMCZy:-O4izBAV4baQG_Ck-5BM:b-nvddm) ([raw file](https://github.com/starkware-libs/cairo/blob/efc94cf2745c0b20d51946f33280f029ccd4238e/crates/cairo-lang-filesystem/src/db.rs#L111)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

how would that work?
the idea is using it by a QueryGroup that already depends on filesystem - so that would be a cyclic dependency.
</blockquote></details>

closing this thread, I'll open new one with my recent thoughts on this
___
*[`crates/cairo-lang-filesystem/src/ids.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6223#-O4eaqa46GZarupNoLaR:-O4iywlECJgWn1Ogo5Jf:befrcto) ([raw file](https://github.com/starkware-libs/cairo/blob/efc94cf2745c0b20d51946f33280f029ccd4238e/crates/cairo-lang-filesystem/src/ids.rs#L65)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

but that wrap is meaningless.

the entire idea is that it is an external implementation using another query - the wrapper type would not solve anything.
</blockquote></details>

yeah, you're right it's meaningless in this context. resolving this thread but I'll post my thoughts in another one
___
*[`crates/cairo-lang-filesystem/src/ids.rs` line 66 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6223#-O4izYD40XHS8OuEZG2h:-O4izYD40XHS8OuEZG2i:b-3mizs) ([raw file](https://github.com/starkware-libs/cairo/blob/315792e95d387eadb010c220e8e4702bb95fb7a2/crates/cairo-lang-filesystem/src/ids.rs#L66)):*
> ```XML
>     Virtual(VirtualFile),
>     External(u32),
> }
> ```

The more I think and try to reason about this, the more I believe this is an unnecessary abstraction. Why can't we just put plugin generated file ID here directly? This should reduce much of the indirections that are happening here, and thus make the code easier to reason about + I really don't believe we'll need another file generation method anytime soon.



_Suggestion:_
```XML
pub enum FileLongId {
    OnDisk(PathBuf),
    Virtual(VirtualFile),
    PluginGenerated(PluginGeneratedFileId),
}
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6223)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-filesystem/src/ids.rs` line 66 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6223#-O4izYD40XHS8OuEZG2h:-O4j2PRn5cZLXxqx6iLu:bxzzzor) ([raw file](https://github.com/starkware-libs/cairo/blob/315792e95d387eadb010c220e8e4702bb95fb7a2/crates/cairo-lang-filesystem/src/ids.rs#L66)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

The more I think and try to reason about this, the more I believe this is an unnecessary abstraction. Why can't we just put plugin generated file ID here directly? This should reduce much of the indirections that are happening here, and thus make the code easier to reason about + I really don't believe we'll need another file generation method anytime soon.
</blockquote></details>

this is a circular dependency - the entire idea is to break it.

**Review by mkaput — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6223#-:-O4jpOoy-tM9prnHnznE:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @piotmag769)

**Pull request merged**
