### PR TITLE
Made array runner test actually run.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1382)

### CODE REVIEW

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1382#-:-NJdn0ng3SlzAnhQvYyB:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @orizi)

___
*[`examples/fib_array.cairo` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1382#-NJdmNKdEPBFHG7vnm2o:-NJdmNKdEPBFHG7vnm2p:b-610l9e) ([raw file](https://github.com/starkware-libs/cairo/blob/4acbcc06ea18b429f7b6083198151362aaae179f/examples/fib_array.cairo#L1)):*
> ```Cairo
> // Returns an array of size n with the values of the Fibonacci sequence, each element twice as well
> ```

// Returns an array of size 2n with the values of the Fibonacci sequence, each element appear twice, as well
// as the length of the array.



_Code quote:_
```Cairo
// Returns an array of size n with the values of the Fibonacci sequence, each element twice as well
// as the length of the array.
```

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1382)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1382)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @orizi)

___
*[`examples/fib_array.cairo` line 2 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1382#-NJe0QFSDQXCt60rwAAU:-NJe0QFSDQXCt60rwAAV:b-rr40z3) ([raw file](https://github.com/starkware-libs/cairo/blob/c0aaf4ee5c784745ebb6b4d65db125664793e5a7/examples/fib_array.cairo#L2)):*
> ```Cairo
> // Returns an array of size 2n with the values of the Fibonacci sequence, each element appear twice,
>  as well as the length of the array.
> ```

// as well as the length of the array.



_Code quote:_
```Cairo
 as well as the length of the array.
```

**Review by gilbens-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1382)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1382)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @gilbens-starkware and @liorgold2)

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1382)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1382)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
