### PR TITLE
Renamed DictManager to SegmentArena.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2393)

### CODE REVIEW

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2393)* status: 4 of 13 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 219 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2393#-NPvOqTK1AXcasli4SCD:-NPvOqTK1AXcasli4SCE:ba854hx) ([raw file](https://github.com/starkware-libs/cairo/blob/2f8882ee9f70d203637e552d76c6a7f188226fee/crates/cairo-lang-casm/src/hints/mod.rs#L219)):*
> ```XML
> 
>                         if '__dict_manager' not in globals():
>                             from starkware.cairo.common.dict import SegmentArena
> ```

Revert.
___
*[`crates/cairo-lang-runner/src/lib.rs` line 272 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2393#-NPvOz2v1HtY5PsZX8oD:-NPvOz2v1HtY5PsZX8oE:b-r1dun5) ([raw file](https://github.com/starkware-libs/cairo/blob/2f8882ee9f70d203637e552d76c6a7f188226fee/crates/cairo-lang-runner/src/lib.rs#L272)):*
> ```XML
>                 ap += 2;
>                 [ap + 0] = 0, ap++;
>                 // Write DictInfos segment, n_dicts (0), and n_destructed (0) to the SegmentArena segment.
> ```

Line too long.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2393)* status: 11 of 13 files reviewed, 6 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/casm_run/dict_manager.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2393#-NPvP3io3gz-d6PVGd6X:-NPvP3io3gz-d6PVGd6Y:b-4i6j18) ([raw file](https://github.com/starkware-libs/cairo/blob/2f8882ee9f70d203637e552d76c6a7f188226fee/crates/cairo-lang-runner/src/casm_run/dict_manager.rs#L16)):*
> ```XML
> }
> 
> /// Helper object to allocate, track and destruct all dictionaries in the run.
> ```

Fix documentation.
You can take inspiration from:
```
// The segment arena builtin allows Sierra libfuncs to allocate memory segments and only track their
// ends (rather than both the start and the end). When the segment is finalized, the arena can
// provide the start pointer that corresponds to the segment (given its end).
```



_Code quote:_
```XML
/// Helper object to allocate, track and destruct all dictionaries in the run.
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/dict_felt_to.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2393#-NPvPTSW-t6XJqcAxlbw:-NPvPTSW-t6XJqcAxlbx:byp1ktf) ([raw file](https://github.com/starkware-libs/cairo/blob/2f8882ee9f70d203637e552d76c6a7f188226fee/crates/cairo-lang-sierra/src/extensions/modules/dict_felt_to.rs#L74)):*
> ```XML
>     ) -> Result<LibfuncSignature, SpecializationError> {
>         let ty = args_as_single_type(args)?;
>         let dict_manager_ty = context.get_concrete_type(SegmentArenaType::id(), &[])?;
> ```

Rename



_Code quote:_
```XML
dict_manager_ty
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/dict_felt_to.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2393#-NPvPVs0AK29-SK8yic0:-NPvPVs0AK29-SK8yic1:brhumzt) ([raw file](https://github.com/starkware-libs/cairo/blob/2f8882ee9f70d203637e552d76c6a7f188226fee/crates/cairo-lang-sierra/src/extensions/modules/dict_felt_to.rs#L167)):*
> ```XML
>         let range_check_type = context.get_concrete_type(RangeCheckType::id(), &[])?;
>         let gas_builtin_type = context.get_concrete_type(GasBuiltinType::id(), &[])?;
>         let dict_manager_ty = context.get_concrete_type(SegmentArenaType::id(), &[])?;
> ```

Same here.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/segment_arena.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2393#-NPvPdic88cGEPvoJ5z1:-NPvPdic88cGEPvoJ5z2:br18gio) ([raw file](https://github.com/starkware-libs/cairo/blob/2f8882ee9f70d203637e552d76c6a7f188226fee/crates/cairo-lang-sierra/src/extensions/modules/segment_arena.rs#L14)):*
> ```XML
> /// The data segment contains the following info for each allocated segment:
> /// The start of the segment (written on allocation).
> /// The end of the dict (written on finalization).
> ```

Fix `dict`.

You can take inspiration from:
```
// Represents the information about a single segment allocated by the arena.
struct SegmentInfo {
    // A pointer to the first element of this segment.
    start: felt*,
    // A pointer to the end of this segment (the first unused element).
    end: felt*,
    // A sequential id, assigned to the segment when it is destructed.
    // This value is used to guarantee that 'end' is not assigned twice.
    end_index: felt,
}

// Represents the status of the segment arena.
struct SegmentArenaBuiltin {
    infos: SegmentInfo*,
    // The number of segments that were created so far.
    n_segments: felt,
    // The number of segments that were destructed so far.
    n_destructed: felt,
}
```

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2393)* status: 12 of 13 files reviewed, 6 unresolved discussions (waiting on @orizi)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2393)* status: all files reviewed, 6 unresolved discussions (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2393)* status: all files reviewed, 6 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 219 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2393#-NPvOqTK1AXcasli4SCD:-NPvQDdq2kpHrYwE0din:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2f8882ee9f70d203637e552d76c6a7f188226fee/crates/cairo-lang-casm/src/hints/mod.rs#L219)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Revert.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runner/src/lib.rs` line 272 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2393#-NPvOz2v1HtY5PsZX8oD:-NPvQgG19d8dMIsE7vhH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2f8882ee9f70d203637e552d76c6a7f188226fee/crates/cairo-lang-runner/src/lib.rs#L272)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Line too long.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runner/src/casm_run/dict_manager.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2393#-NPvP3io3gz-d6PVGd6X:-NPvQvbS1tzTZJmEzd6F:bdbko6o) ([raw file](https://github.com/starkware-libs/cairo/blob/2f8882ee9f70d203637e552d76c6a7f188226fee/crates/cairo-lang-runner/src/casm_run/dict_manager.rs#L16)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Fix documentation.
You can take inspiration from:
```
// The segment arena builtin allows Sierra libfuncs to allocate memory segments and only track their
// ends (rather than both the start and the end). When the segment is finalized, the arena can
// provide the start pointer that corresponds to the segment (given its end).
```
</blockquote></details>

reverted - this is not the same object.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/dict_felt_to.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2393#-NPvPTSW-t6XJqcAxlbw:-NPvRkQP3jmJyYbrmOyt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2f8882ee9f70d203637e552d76c6a7f188226fee/crates/cairo-lang-sierra/src/extensions/modules/dict_felt_to.rs#L74)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Rename
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/dict_felt_to.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2393#-NPvPVs0AK29-SK8yic0:-NPvRkAL8tohGt4vrkvs:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2f8882ee9f70d203637e552d76c6a7f188226fee/crates/cairo-lang-sierra/src/extensions/modules/dict_felt_to.rs#L167)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/segment_arena.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2393#-NPvPdic88cGEPvoJ5z1:-NPvS4PF6_jaJ6-efJi_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2f8882ee9f70d203637e552d76c6a7f188226fee/crates/cairo-lang-sierra/src/extensions/modules/segment_arena.rs#L14)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Fix `dict`.

You can take inspiration from:
```
// Represents the information about a single segment allocated by the arena.
struct SegmentInfo {
    // A pointer to the first element of this segment.
    start: felt*,
    // A pointer to the end of this segment (the first unused element).
    end: felt*,
    // A sequential id, assigned to the segment when it is destructed.
    // This value is used to guarantee that 'end' is not assigned twice.
    end_index: felt,
}

// Represents the status of the segment arena.
struct SegmentArenaBuiltin {
    infos: SegmentInfo*,
    // The number of segments that were created so far.
    n_segments: felt,
    // The number of segments that were destructed so far.
    n_destructed: felt,
}
```
</blockquote></details>

Done.

**Review by liorgold2 — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2393)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2393)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`tests/e2e_test_data/libfuncs/dict_felt_to` line 16 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2393#-NPvUMCq6R7A0UsQmBiL:-NPvUMCq6R7A0UsQmBiM:bsgbqrg) ([raw file](https://github.com/starkware-libs/cairo/blob/1a01ff2cb6865c5b087ae1f8c75848472df202bb/tests/e2e_test_data/libfuncs/dict_felt_to#L16)):*
> ```
> %{
> if '__dict_manager' not in globals():
>     from starkware.cairo.common.dict import SegmentArena
> ```

This should be fixes as well.

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2393#-:-NPvUQx77YNfG3HcIpgj:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2393)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`tests/e2e_test_data/libfuncs/dict_felt_to` line 16 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2393#-NPvUMCq6R7A0UsQmBiL:-NPvUZAv-anjCPtR4tO2:b-avug5f) ([raw file](https://github.com/starkware-libs/cairo/blob/1a01ff2cb6865c5b087ae1f8c75848472df202bb/tests/e2e_test_data/libfuncs/dict_felt_to#L16)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

This should be fixes as well.
</blockquote></details>

didn;t run the fixer - will do.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2393)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @liorgold2)

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2393)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
