### PR TITLE
Add support for logical operators.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3323)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3323)* status: 3 of 10 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 455 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3323#-NXLl9WG8G5b8B61bb7P:-NXLl9WG8G5b8B61bb7Q:b-4ueu4i) ([raw file](https://github.com/starkware-libs/cairo/blob/83dd5f453b507b138f8745a7a699e3a06fb983b3/crates/cairo-lang-lowering/src/lower/mod.rs#L455)):*
> ```XML
>         semantic::Expr::Desnap(expr) => lower_expr_desnap(ctx, expr, builder),
>         semantic::Expr::Assignment(expr) => lower_expr_assignment(ctx, expr, builder),
>         semantic::Expr::BinaryOperator(expr) => lower_binary_op(ctx, builder, expr),
> ```

Isn't it kinda wierd that binary op is only && and ||?
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 379 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3323#-NXLkI9u2QSLxmpCpUyX:-NXLkI9u2QSLxmpCpUyY:bk72yyp) ([raw file](https://github.com/starkware-libs/cairo/blob/83dd5f453b507b138f8745a7a699e3a06fb983b3/crates/cairo-lang-semantic/src/expr/compute.rs#L379)):*
> ```XML
> 
>             let bool_ty = core_bool_ty(db);
>             if lexpr.expr.ty() != bool_ty {
> ```

If we always expect bool, conform_ty instead (look at if lowering)
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 386 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3323#-NXLkTX64BuUqks8B4k3:-NXLkTX64BuUqks8B4k4:bs6qvsh) ([raw file](https://github.com/starkware-libs/cairo/blob/83dd5f453b507b138f8745a7a699e3a06fb983b3/crates/cairo-lang-semantic/src/expr/compute.rs#L386)):*
> ```XML
>             }
> 
>             if rexpr.expr.ty() != bool_ty {
> ```

Here as well

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 455 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3323#-NXLl9WG8G5b8B61bb7P:-NXOUG7W4ojyANAsQy0c:b-9jladf) ([raw file](https://github.com/starkware-libs/cairo/blob/83dd5f453b507b138f8745a7a699e3a06fb983b3/crates/cairo-lang-lowering/src/lower/mod.rs#L455)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Isn't it kinda wierd that binary op is only && and ||?
</blockquote></details>

I can rename it, but I think (and shachar agreed) that long term we want to use it for all binary ops.
In the current implementation, the semantic module does not know if the original code had a binary op or a function call.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 455 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3323#-NXLl9WG8G5b8B61bb7P:-NXOW81nBpy7I65iChxd:b-wy66gb) ([raw file](https://github.com/starkware-libs/cairo/blob/83dd5f453b507b138f8745a7a699e3a06fb983b3/crates/cairo-lang-lowering/src/lower/mod.rs#L455)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I can rename it, but I think (and shachar agreed) that long term we want to use it for all binary ops.
In the current implementation, the semantic module does not know if the original code had a binary op or a function call.
</blockquote></details>

Though I'm not sure how it will work with the inference in the semantic.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3323)* status: 3 of 10 files reviewed, 3 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 455 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3323#-NXLl9WG8G5b8B61bb7P:-NXOWXCX6cQQt6asuVGH:b-sby12w) ([raw file](https://github.com/starkware-libs/cairo/blob/83dd5f453b507b138f8745a7a699e3a06fb983b3/crates/cairo-lang-lowering/src/lower/mod.rs#L455)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Though I'm not sure how it will work with the inference in the semantic.
</blockquote></details>

Do you want me to rename it to LogicalOperator?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3323)* status: 3 of 10 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 455 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3323#-NXLl9WG8G5b8B61bb7P:-NXObA0G4rJJadLZF16P:b3icy4) ([raw file](https://github.com/starkware-libs/cairo/blob/83dd5f453b507b138f8745a7a699e3a06fb983b3/crates/cairo-lang-lowering/src/lower/mod.rs#L455)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Do you want me to rename it to LogicalOperator?
</blockquote></details>

i think we should rename - we might want to add the `Call` function some information about this being an operator for better diagnostics - but && and || are very different from other operators IMO (as these actually control the flow of the run)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 379 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3323#-NXLkI9u2QSLxmpCpUyX:-NXOcC_66MTpqO5VpgWH:bs4gzx1) ([raw file](https://github.com/starkware-libs/cairo/blob/83dd5f453b507b138f8745a7a699e3a06fb983b3/crates/cairo-lang-semantic/src/expr/compute.rs#L379)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

If we always expect bool, conform_ty instead (look at if lowering)
</blockquote></details>

Done, thanks.
Not sure how to test it though.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3323)* status: 3 of 10 files reviewed, 3 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 455 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3323#-NXLl9WG8G5b8B61bb7P:-NXOdCJa8RxdjxMxjopr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/83dd5f453b507b138f8745a7a699e3a06fb983b3/crates/cairo-lang-lowering/src/lower/mod.rs#L455)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i think we should rename - we might want to add the `Call` function some information about this being an operator for better diagnostics - but && and || are very different from other operators IMO (as these actually control the flow of the run)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 386 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3323#-NXLkTX64BuUqks8B4k3:-NXOd8CtDJeMU3YCxEge:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/83dd5f453b507b138f8745a7a699e3a06fb983b3/crates/cairo-lang-semantic/src/expr/compute.rs#L386)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Here as well
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 10 files at r1, 1 of 2 files at r2, 1 of 7 files at r3, 1 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3323)* status: 5 of 11 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/expr/objects.rs` line 356 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3323#-NXOe3Gq0useBBZ9aLrX:-NXOe3Gq0useBBZ9aLrY:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/fb40b13427560e23f189f5466541d3cbe44e6215/crates/cairo-lang-semantic/src/expr/objects.rs#L356)):*
> ```XML
>     pub op: LogicalOperator,
>     pub rhs: semantic::ExprId,
>     pub ty: semantic::TypeId,
> ```





_Suggestion:_
```XML
// ExprLogicalOperator is always of bool type.
pub ty: semantic::TypeId,
```
___
*[`crates/cairo-lang-semantic/src/expr/test_data/logical_operator` line 41 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3323#-NXOe_is76LU1W-UVIFf:-NXOe_is76LU1W-UVIFg:b-infx8o) ([raw file](https://github.com/starkware-libs/cairo/blob/2d882f377e4b806124875b0d24da6e04d7747dec/crates/cairo-lang-semantic/src/expr/test_data/logical_operator#L41)):*
> ```
> //! > function
> fn foo(a: u128, b: bool, c: u128) -> bool {
>     bar(a.into(), b, c.into());
> ```

why the `into`s?



_Code quote:_
```
   bar(a.into(), b, c.into());
```
___
*[`crates/cairo-lang-lowering/src/diagnostic.rs` line 122 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3323#-NXOdBlZA1rfIlcNimz1:-NXOdBlZA1rfIlcNimz2:b-ver8lu) ([raw file](https://github.com/starkware-libs/cairo/blob/2d882f377e4b806124875b0d24da6e04d7747dec/crates/cairo-lang-lowering/src/diagnostic.rs#L122)):*
> ```XML
>     UnsupportedMatchArmNotAVariant,
>     UnsupportedMatchArmOutOfOrder,
>     LogicalOperatorsNotSupported,
> ```

you add it but not use it.



_Code quote:_
```XML
    LogicalOperatorsNotSupported,
```
___
*[`crates/cairo-lang-lowering/src/test_data/lazy_bool_expr` line 24 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3323#-NXOefst6wycQBjUFWJO:-NXOefst6wycQBjUFWJP:bb7r2f0) ([raw file](https://github.com/starkware-libs/cairo/blob/f41ba5c75603dd46d659433a0403ef1c3ea826a8/crates/cairo-lang-lowering/src/test_data/lazy_bool_expr#L24)):*
> ```
>  --> lib.cairo:2:10
>     if a && (x == 0) {
>          ^^
> ```

why?



_Code quote:_
```
error: Unknown binary operator.
 --> lib.cairo:2:10
    if a && (x == 0) {
         ^^
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/test_data/lazy_bool_expr` line 24 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3323#-NXOefst6wycQBjUFWJO:-NXOewZW7Lws_YrGYoT-:b-xtocuk) ([raw file](https://github.com/starkware-libs/cairo/blob/f41ba5c75603dd46d659433a0403ef1c3ea826a8/crates/cairo-lang-lowering/src/test_data/lazy_bool_expr#L24)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why?
</blockquote></details>

sorry this file is not relevent.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3323)* status: 5 of 11 files reviewed, 6 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/diagnostic.rs` line 122 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3323#-NXOdBlZA1rfIlcNimz1:-NXOetwP-_zT9GdVrf3C:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2d882f377e4b806124875b0d24da6e04d7747dec/crates/cairo-lang-lowering/src/diagnostic.rs#L122)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you add it but not use it.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3323)* status: 5 of 11 files reviewed, 6 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/logical_operator` line 41 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3323#-NXOe_is76LU1W-UVIFf:-NXOfGnpAq12maMgKvCz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2d882f377e4b806124875b0d24da6e04d7747dec/crates/cairo-lang-semantic/src/expr/test_data/logical_operator#L41)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why the `into`s?
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r1, 1 of 2 files at r2, 2 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3323)* status: 5 of 11 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/binary_op.rs` line 138 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3323#-NXOgvG38bPRsJf07Ziy:-NXOgvG38bPRsJf07Ziz:b-9ews7i) ([raw file](https://github.com/starkware-libs/cairo/blob/2d882f377e4b806124875b0d24da6e04d7747dec/crates/cairo-lang-lowering/src/lower/binary_op.rs#L138)):*
> ```XML
>         semantic::BinaryOperator::OrOr => lower_or_or(ctx, builder, location, expr.lhs, expr.rhs),
>     }
> }
> ```

or something similar?
this seems very duplicated



_Suggestion:_
```XML
/// Lowers an expression of type [semantic::ExprBinaryOperator].
pub fn lower_binary_op(
    ctx: &mut LoweringContext<'_, '_>,
    builder: &mut BlockBuilder,
    expr: &semantic::ExprBinaryOperator,
) -> LoweringResult<LoweredExpr> {
    let location = ctx.get_location(expr.stable_ptr.untyped());    let semantic_db = ctx.db.upcast();
    let unit_ty = corelib::unit_ty(semantic_db);
    let lhs_var = lower_expr(ctx, builder, lhs)?.var(ctx, builder)?;

    let mut subscope_lhs_true = create_subscope_with_bound_refs(ctx, builder);
    let lhs_true_block_id = subscope_lhs_true.block_id;

    let rhs_var = lower_expr(ctx, &mut subscope_lhs_true, rhs)?.var(ctx, &mut subscope_lhs_true)?;
    let mut subscope_lhs_true = create_subscope_with_bound_refs(ctx, builder);
    let lhs_true_block_id = subscope_lhs_true.block_id;

    let (sealed_block_lhs_true, lhs_false_block_id, sealed_block_lhs_false) = match expr.op {
        // Lowers `lhs && rhs` to `if lhs { rhs } else { false }`.
        semantic::BinaryOperator::AndAnd => {
            let rhs_var = lower_expr(ctx, &mut subscope_lhs_true, rhs)?.var(ctx, &mut subscope_lhs_true)?;
        
            let sealed_block_lhs_true = subscope_lhs_true.goto_callsite(Some(rhs_var));
            let mut subscope_lhs_false = create_subscope_with_bound_refs(ctx, builder);
            let lhs_false_block_id = subscope_lhs_false.block_id;
            let false_var =
                create_bool(ctx, &mut subscope_lhs_false, corelib::false_variant(semantic_db), location);
            let sealed_block_lhs_false = subscope_lhs_false.goto_callsite(Some(false_var));
            (sealed_block_lhs_true, lhs_false_block_id, sealed_block_lhs_false)
        }
        // Lowers `lhs || rhs` to `if lhs { true } else { rhs }`.
        semantic::BinaryOperator::OrOr => {
            let true_var =
                create_bool(ctx, &mut subscope_lhs_true, corelib::true_variant(semantic_db), location);
        
            let sealed_block_lhs_true = subscope_lhs_true.goto_callsite(Some(true_var));
            let mut subscope_lhs_false = create_subscope_with_bound_refs(ctx, builder);
            let lhs_false_block_id = subscope_lhs_false.block_id;
            let rhs_var =
                lower_expr(ctx, &mut subscope_lhs_false, rhs)?.var(ctx, &mut subscope_lhs_false)?;
        
            let sealed_block_lhs_false = subscope_lhs_false.goto_callsite(Some(rhs_var));
            (sealed_block_lhs_true, lhs_false_block_id, sealed_block_lhs_false)or 
        },
    }

    let match_info = MatchInfo::Enum(MatchEnumInfo {
        concrete_enum_id: corelib::core_bool_enum(semantic_db),
        input: lhs_var,
        arms: vec![
            MatchArm {
                variant_id: corelib::false_variant(semantic_db),
                block_id: lhs_true_block_id,
                var_ids: vec![ctx.new_var(VarRequest { ty: unit_ty, location })],
            },
            MatchArm {
                variant_id: corelib::true_variant(semantic_db),
                block_id: lhs_false_block_id,
                var_ids: vec![ctx.new_var(VarRequest { ty: unit_ty, location })],
            },
        ],
    });
    builder.merge_and_end_with_match(
        ctx,
        match_info,
        vec![sealed_block_lhs_true, sealed_block_lhs_false],
        location,
    )
}
```
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 455 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3323#-NXOf_d59GNn9UWvHezj:-NXOf_d59GNn9UWvHezk:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f9da2ce1a101c097b73cbb3871d520cd85437c81/crates/cairo-lang-lowering/src/lower/mod.rs#L455)):*
> ```XML
>         semantic::Expr::Desnap(expr) => lower_expr_desnap(ctx, expr, builder),
>         semantic::Expr::Assignment(expr) => lower_expr_assignment(ctx, expr, builder),
>         semantic::Expr::LogicalOperator(expr) => lower_binary_op(ctx, builder, expr),
> ```





_Suggestion:_
```XML
ower_logical_op
```
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 379 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3323#-NXLkI9u2QSLxmpCpUyX:-NXOjYrX4OXYOYDyRbdU:b67tqcy) ([raw file](https://github.com/starkware-libs/cairo/blob/83dd5f453b507b138f8745a7a699e3a06fb983b3/crates/cairo-lang-semantic/src/expr/compute.rs#L379)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Done, thanks.
Not sure how to test it though.
</blockquote></details>

this already tests if it is the correct type for now - so sgtm.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3323)* status: 6 of 11 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/test_data/logical_operator` line 56 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3323#-NXOjj2092QlNzqRtoTv:-NXOjj2092QlNzqRtoTw:bp8971v) ([raw file](https://github.com/starkware-libs/cairo/blob/f9da2ce1a101c097b73cbb3871d520cd85437c81/crates/cairo-lang-semantic/src/expr/test_data/logical_operator#L56)):*
> ```
>  --> lib.cairo:2:5
>     a && b || c
>     ^
> ```

Is this supposed to work?



_Code quote:_
```
error: Expected type "core::bool", found: "S".
 --> lib.cairo:2:5
    a && b || c
    ^
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 7 files at r3, 2 of 5 files at r4, 2 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3323)* status: 9 of 11 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3323)* status: 8 of 11 files reviewed, 3 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/binary_op.rs` line 138 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3323#-NXOgvG38bPRsJf07Ziy:-NXP-Xu1ArODr8HC1Aig:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2d882f377e4b806124875b0d24da6e04d7747dec/crates/cairo-lang-lowering/src/lower/binary_op.rs#L138)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

or something similar?
this seems very duplicated
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 455 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3323#-NXOf_d59GNn9UWvHezj:-NXOmA1xD_Jxsy1PqzOO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f9da2ce1a101c097b73cbb3871d520cd85437c81/crates/cairo-lang-lowering/src/lower/mod.rs#L455)):*
> ```XML
>         semantic::Expr::Desnap(expr) => lower_expr_desnap(ctx, expr, builder),
>         semantic::Expr::Assignment(expr) => lower_expr_assignment(ctx, expr, builder),
>         semantic::Expr::LogicalOperator(expr) => lower_binary_op(ctx, builder, expr),
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 379 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3323#-NXLkI9u2QSLxmpCpUyX:-NXOm19L8G32WZc-qLLg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/83dd5f453b507b138f8745a7a699e3a06fb983b3/crates/cairo-lang-semantic/src/expr/compute.rs#L379)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this already tests if it is the correct type for now - so sgtm.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/objects.rs` line 356 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3323#-NXOe3Gq0useBBZ9aLrX:-NXOlzCa1FqtD52B-y9a:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fb40b13427560e23f189f5466541d3cbe44e6215/crates/cairo-lang-semantic/src/expr/objects.rs#L356)):*
> ```XML
>     pub op: LogicalOperator,
>     pub rhs: semantic::ExprId,
>     pub ty: semantic::TypeId,
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3323#-:-NXP00nODm74v7NANiwd:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
