### PR TITLE
Enable match optimization with remapping when there is no future merge.

### PR DESCRIPTION
**Pull request by liorgold2**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6337)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 332 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6337#-O5rHy7UCpC2CCqiLsnC:-O5rHy7UCpC2CCqiLsnD:ba3dfmt) ([raw file](https://github.com/starkware-libs/cairo/blob/f4795ee1f4ba63583c9c00e2a25d542947defdf3/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L332)):*
> ```XML
>             if candidate.future_merge || candidate.additional_remappings.is_some() {
>                 // Don't apply the optimization in this case, as it breaks SSA when we use the same
>                 // remapping with different destination blocks.
> ```

Remove.



_Code quote:_
```XML
                // Don't apply the optimization in this case, as it breaks SSA when we use the same
                // remapping with different destination blocks.
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6337)* status: 0 of 40 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 332 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6337#-O5rHy7UCpC2CCqiLsnC:-O5rY1Q52z_jIw5U4rUg:be8vlgl) ([raw file](https://github.com/starkware-libs/cairo/blob/f4795ee1f4ba63583c9c00e2a25d542947defdf3/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L332)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Remove.
</blockquote></details>

Done (in a previous PR).

**Review by orizi — COMMENTED** [review]
> Reviewed 23 of 40 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6337)* status: 24 of 40 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 16 of 40 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6337)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6337#-:-O5wWkWl7kaoCLsR-7iN:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6337)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 40 files at r1, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6337#-:-O611h7Q3hiRn55WxZEW:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 4 of 40 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6337)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
