### PR TITLE
Used `maybe_tempvar` for downcast into BoundedInt as well.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4848)

### CODE REVIEW

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4848)* status: 2 of 4 files reviewed, all discussions resolved

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4848)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4848#-NoorAMu5vu2g1EZ7Cv_:-NoorAMu5vu2g1EZ7Cva:b-vl6b3y) (no related file):*
Please change the comments `// Since range_upper may be 0.` in `range_reduction.rs` to `Use maybe _tempvar since ...` otherwise it's not clear what "since" refers to.

___

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4848)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 206 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4848#-NootOOa28v6d8bZXUMy:-NootOOa28v6d8bZXUMz:b-3cwigu) ([raw file](https://github.com/starkware-libs/cairo/blob/32da3a3692337cd7f7dec8303695a1d734979987/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L206)):*
> ```XML
>         // value < bound  <=>  value + (2**128 - bound) < 2**128.
>         const pos_shift = (BigInt::from(u128::MAX) + 1 - bound) as BigInt;
>         maybe_tempvar shifted_value = value + pos_shift;
> ```

IIUC this is backward compatible since the only places validate_lt is used are:
1. add_downcast_overflow_above on upper bound - if the bound is `2**128`, it means the from range allowed values >= `2**128`.
2. add_downcast_overflow_below on lower bound - lower bound couldn't be `2**128`
3. add_downcast_overflow_both on lower bound - lower bound couldn't be `2**128`
4. add_downcast_overflow_both on upper bound - if the bound is `2**128`, it means the from range allowed values >= `2**128`.

Is this true?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4848)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4848#-NoorAMu5vu2g1EZ7Cv_:-NopCMNn0dsgkrCHov3K:b-896fix) (no related file):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Please change the comments `// Since range_upper may be 0.` in `range_reduction.rs` to `Use maybe _tempvar since ...` otherwise it's not clear what "since" refers to.
</blockquote></details>

Done.

___
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 206 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4848#-NootOOa28v6d8bZXUMy:-NopBadU8F7rl3MDdwMP:b-2y03dl) ([raw file](https://github.com/starkware-libs/cairo/blob/32da3a3692337cd7f7dec8303695a1d734979987/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L206)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

IIUC this is backward compatible since the only places validate_lt is used are:
1. add_downcast_overflow_above on upper bound - if the bound is `2**128`, it means the from range allowed values >= `2**128`.
2. add_downcast_overflow_below on lower bound - lower bound couldn't be `2**128`
3. add_downcast_overflow_both on lower bound - lower bound couldn't be `2**128`
4. add_downcast_overflow_both on upper bound - if the bound is `2**128`, it means the from range allowed values >= `2**128`.

Is this true?
</blockquote></details>

exactly.

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4848#-:-NopHsTZChAOdVAF4_yL:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
