### PR TITLE
Removed unary operator cell-expr.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:7af5e129

---

**Stack**:
- #1523
- #1522
- #1508 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

Is the libfunc itself needed?
Add a todo to remove it.+

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1508#-:-NKIkmFsDR1mrExH5j08:bjholbx)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
done in the next pr.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1508#-:-NKJUP2KAUm15qJV2Ldj:b-8zxai8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by ilyalesokhin-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1508)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1508)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
