### PR TITLE
Add CostTokenType::RangeCheck96.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5558)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5558)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/gas.rs` line 154 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5558#-NxvHisdCLAc68PA8zRc:-NxvHisdCLAc68PA8zRd:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0e948d41001f4e2d060106e8d023eac5a52a11f2/crates/cairo-lang-sierra/src/extensions/modules/gas.rs#L154)):*
> ```XML
> 
>     /// The number of 96-bit range check builtins.
>     RangeCheck96,
> ```





_Suggestion:_
```XML
    Hole,
    /// The number of 128-bit range check builtins.
    RangeCheck,
    /// The number of 96-bit range check builtins.
    RangeCheck96,
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5558)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 145 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5558#-NxvN7lD4ZhG37wbimcf:-NxvN7lD4ZhG37wbimcg:b-l6wpjp) ([raw file](https://github.com/starkware-libs/cairo/blob/0e948d41001f4e2d060106e8d023eac5a52a11f2/crates/cairo-lang-runner/src/lib.rs#L145)):*
> ```XML
>         CostTokenType::Bitwise => 594,
>         CostTokenType::EcOp => 4166,
>         CostTokenType::RangeCheck96 => 70,
> ```

I don't know if this is really the cost :(



_Code quote:_
```XML
 CostTokenType::RangeCheck96 => 70,
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5558)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/gas.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5558#-NxvNDaX5a_ScYPcM0TW:-NxvNDaX5a_ScYPcM0TX:bz4fkgj) ([raw file](https://github.com/starkware-libs/cairo/blob/0e948d41001f4e2d060106e8d023eac5a52a11f2/crates/cairo-lang-sierra/src/extensions/modules/gas.rs#L213)):*
> ```XML
>                 panic!("offset_in_builtin_costs is not supported for '{}'.", self.camel_case_name())
>             }
>             CostTokenType::RangeCheck96 => 4,
> ```

note that I didn't fix the actual table



_Code quote:_
```XML
 CostTokenType::RangeCheck96 => 4,
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5558)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 145 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5558#-NxvN7lD4ZhG37wbimcf:-NxvNV6x3cML9gLwTYS-:bkmzk1g) ([raw file](https://github.com/starkware-libs/cairo/blob/0e948d41001f4e2d060106e8d023eac5a52a11f2/crates/cairo-lang-runner/src/lib.rs#L145)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't know if this is really the cost :(
</blockquote></details>

so add a TODO over it.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/gas.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5558#-NxvNDaX5a_ScYPcM0TW:-NxvNc8YEy5-r_qqo_oU:bu4h6uo) ([raw file](https://github.com/starkware-libs/cairo/blob/0e948d41001f4e2d060106e8d023eac5a52a11f2/crates/cairo-lang-sierra/src/extensions/modules/gas.rs#L213)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

note that I didn't fix the actual table
</blockquote></details>

so add a TODO - and also add it after `3` instead of before all.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5558)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/gas.rs` line 154 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5558#-NxvHisdCLAc68PA8zRc:-Ny-d4hH4Tn16GDdhW_l:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0e948d41001f4e2d060106e8d023eac5a52a11f2/crates/cairo-lang-sierra/src/extensions/modules/gas.rs#L154)):*
> ```XML
> 
>     /// The number of 96-bit range check builtins.
>     RangeCheck96,
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5558#-:-Ny-t7ax5Zm2mTnpPZr3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
