### PR TITLE
Streamline `PanicablePlugin` implementation

### PR DESCRIPTION
**Pull request by mkaput**
**Stack**:
- #2780
- #2767
- #2731
- #2730
- #2738
- #2765
- #2737
- #2736
- #2732 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2732)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2732)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-plugins/src/plugins/panicable.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2732#-NSZaQoQ73qwB-6qZ1Ps:-NSZaQoQ73qwB-6qZ1Pt:bz3wulm) ([raw file](https://github.com/starkware-libs/cairo/blob/a84bc8eb879738eb305f9b6727ddc7d8581ee67d/crates/cairo-lang-plugins/src/plugins/panicable.rs#L61)):*
> ```XML
>             diagnostics: vec![PluginDiagnostic {
>                 stable_ptr: signature.ret_ty(db).stable_ptr().untyped(),
>                 message: "Currently only wrapping functions returning an Option<T> or Result<T, E>".into(),
> ```

Please keep line lengths <= 100 chars.

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2732)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-plugins/src/plugins/panicable.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2732#-NSZaQoQ73qwB-6qZ1Ps:-NSjP_WlBIomH_qAYKzS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a84bc8eb879738eb305f9b6727ddc7d8581ee67d/crates/cairo-lang-plugins/src/plugins/panicable.rs#L61)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Please keep line lengths <= 100 chars.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2732)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @mkaput and @spapinistarkware)

___
*[`crates/cairo-lang-plugins/src/plugins/panicable.rs` line 161 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2732#-NSojBYJ12CjjOytF8pN:-NSojBYJ12CjjOytF8pO:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/1f2c292cbfa4281964e9391abcf990e148ba04dc/crates/cairo-lang-plugins/src/plugins/panicable.rs#L161)):*
> ```XML
> }
> 
> fn parse_arguments(db: &dyn SyntaxGroup, attr: &Attribute) -> Option<(SmolStr, SmolStr)> {
> ```

doc



_Code quote:_
```XML
parse_arguments
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2732)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @mkaput and @spapinistarkware)

___
*[`crates/cairo-lang-plugins/src/plugins/panicable.rs` line 161 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2732#-NSojBYJ12CjjOytF8pN:-NSp4Fq-3wMl2Q9cmyQk:b-94747k) ([raw file](https://github.com/starkware-libs/cairo/blob/1f2c292cbfa4281964e9391abcf990e148ba04dc/crates/cairo-lang-plugins/src/plugins/panicable.rs#L161)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

also expand about what we return (since we expect something specific about the args)

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2732)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-plugins/src/plugins/panicable.rs` line 161 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2732#-NSojBYJ12CjjOytF8pN:-NSpBt_A-OpqcDHJJqCl:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1f2c292cbfa4281964e9391abcf990e148ba04dc/crates/cairo-lang-plugins/src/plugins/panicable.rs#L161)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

also expand about what we return (since we expect something specific about the args)
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2732#-:-NSpDtl526yDA06y_1fX:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by spapinistarkware — APPROVED** [review]

**Pull request merged**
