### PR TITLE
Removed empty explicit implicits in libfuncs

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3544)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3544)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3544#-NZ0vmS07geUvX6B6nSN):*
don't we want that?
maybe we want the opposite - make sure we always have it.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3544)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/integer.cairo` line 651 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3544#-NZ0w0EP-KKO9O9BpZot:-NZ0w0EP-KKO9O9BpZou:b-6x370s) ([raw file](https://github.com/starkware-libs/cairo/blob/b3c190a606f74a5d884e2e89a851866e13584eca/corelib/src/integer.cairo#L651)):*
> ```Cairo
>     fn bitand(lhs: u16, rhs: u16) -> u16 {
>         let (v, _, _) = u16_bitwise(lhs, rhs);
>         v
> ```

fix rebase

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3544)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3544#-NZ0vmS07geUvX6B6nSN):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Why? It adds characters to the code that add no info. It makes it less readable as it's harder to focus on the important stuff. See testing.cairo for example
</blockquote></details>

it adds info - same info as nopanic for extern funcs.

**Comment by yuvalsw** [comment]
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3544#-NZ0vmS07geUvX6B6nSN):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it adds info - same info as nopanic for extern funcs.
</blockquote></details>

No. nopanic means there is no panic. Different than nothing, which means may-panic. implicits() means exactly the same as nothing.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3544)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3544#-NZ0vmS07geUvX6B6nSN):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

No. nopanic means there is no panic. Different than nothing, which means may-panic. implicits() means exactly the same as nothing.
</blockquote></details>

if we disallow it for user code - no it does not.

**Pull request closed without merging**
