### PR TITLE
Use #always[inline] attribute.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1788)

### CODE REVIEW

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 11 files at r1, 7 of 7 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1788#-:-NM35oxABwNs1wJQa2jw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 9 of 11 files at r1, 7 of 7 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1788#-:-NM36_Xy6r5DEF_pBPnT:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 300 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1788#-NM36K8k-cluXNNnyBbn:-NM36K8k-cluXNNnyBbo:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ba1cb9d3f10a9447ef2377e4be9f8fd9707637a3/crates/cairo-lang-lowering/src/inline/mod.rs#L300)):*
> ```XML
> }
> 
> // Rebuilds the statement with renamed var and block ids.
> ```





_Suggestion:_
```XML
/// Rebuilds the statement with renamed var and block ids.
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1788)* status: 10 of 12 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 300 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1788#-NM36K8k-cluXNNnyBbn:-NM3A2lk6ajnv_MYTCtw:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ba1cb9d3f10a9447ef2377e4be9f8fd9707637a3/crates/cairo-lang-lowering/src/inline/mod.rs#L300)):*
> ```XML
> }
> 
> // Rebuilds the statement with renamed var and block ids.
> ```

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1788)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 4 of 11 files at r1, 2 of 7 files at r2, 2 of 2 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1788)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
