### PR TITLE
Removed addtional block info copies.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5307)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 9 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5307)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/reorder_statements.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5307#-NtjC-Sp2KfGqufl6Omp:-NtjC-Sp2KfGqufl6Omq:b-j5gy93) ([raw file](https://github.com/starkware-libs/cairo/blob/249dac33cb106c861f58b27c0248c607d82f658b/crates/cairo-lang-lowering/src/optimizations/reorder_statements.rs#L164)):*
> ```XML
>             for var_id in &arm.var_ids {
>                 info.next_use.remove(var_id);
>             }
> ```

Now you can do this before the merge.



_Code quote:_
```XML
            for var_id in &arm.var_ids {
                info.next_use.remove(var_id);
            }
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/reorder_statements.rs` line 176 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5307#-NtjCJ3a9WvrCidx9vHc:-NtjCJ3b3uxeVfIkj9JB:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/249dac33cb106c861f58b27c0248c607d82f658b/crates/cairo-lang-lowering/src/optimizations/reorder_statements.rs#L176)):*
> ```XML
>                 *e.into_mut() = statement_location;
>             });
>             remove_arm_outputs(&mut info, arm);
> ```





_Suggestion:_
```XML
            remove_arm_outputs(&mut arm_info, arm);
            info.next_use.merge(&arm_info.next_use, |e, _| {
                *e.into_mut() = statement_location;
            });
            
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5307)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/reorder_statements.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5307#-NtjC-Sp2KfGqufl6Omp:-Ntjz3dF8KSN0F1-I-mA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/249dac33cb106c861f58b27c0248c607d82f658b/crates/cairo-lang-lowering/src/optimizations/reorder_statements.rs#L164)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Now you can do this before the merge.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/optimizations/reorder_statements.rs` line 176 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5307#-NtjCJ3a9WvrCidx9vHc:-Ntjz51G373LKr5HZXYq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/249dac33cb106c861f58b27c0248c607d82f658b/crates/cairo-lang-lowering/src/optimizations/reorder_statements.rs#L176)):*
> ```XML
>                 *e.into_mut() = statement_location;
>             });
>             remove_arm_outputs(&mut info, arm);
> ```

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 11 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5307#-:-Ntk15_z-eWxCPCHl0wA:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
