### PR TITLE
Allow providing custom path to corelib 

### PR DESCRIPTION
**Pull request by maciektr**
fix: https://github.com/starkware-libs/cairo/issues/1595

This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1763)

### CODE REVIEW

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1763)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @maciektr, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1763#-NLfANH2BaKhyLUhrf0a:-NLfANH2BaKhyLUhrf0b:bf1y104) ([raw file](https://github.com/starkware-libs/cairo/blob/b2322f74a87aadc0ea5928406f5a5e226748a5dc/crates/cairo-lang-filesystem/src/db.rs#L55)):*
> ```XML
> 
>     // Set builtin core config if detected.
>     match detect_corelib() {
> ```

Can we call this code only if corelib crate name is not interned yet in the db?
___
*[`crates/cairo-lang-filesystem/src/db.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1763#-NLfAUMNDLnNr5YrfCEY:-NLfAUMNDLnNr5YrfCEZ:b-mvpiie) ([raw file](https://github.com/starkware-libs/cairo/blob/b2322f74a87aadc0ea5928406f5a5e226748a5dc/crates/cairo-lang-filesystem/src/db.rs#L61)):*
> ```XML
>             db.set_crate_root(core_crate, Some(core_root_dir));
>         }
>         None => {}
> ```

With the suggested condition, we can safely assume a failure here and raise error, explaining what is wrong.
___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1763#-NLfA4399dtly_wddqsv:-NLfA4399dtly_wddqsw:b-gip3ja) ([raw file](https://github.com/starkware-libs/cairo/blob/b2322f74a87aadc0ea5928406f5a5e226748a5dc/crates/cairo-lang-semantic/src/corelib.rs#L76)):*
> ```XML
>             )
>         }
>     }
> ```

Hmm, I think we shouldn't change this function's code as it is too specific, and instead raise this error (preferably via `Result::Err` I think?), in `init_files_group`. See my comment for suggestion of the flow.

**Review by mkaput — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1763)* status: all files reviewed, 3 unresolved discussions (waiting on @maciektr, @orizi, and @spapinistarkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1763)* status: all files reviewed, 4 unresolved discussions (waiting on @maciektr and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1763#-NLgopp_2elOFvJPbG-F:-NLgopp_2elOFvJPbG-G:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b2322f74a87aadc0ea5928406f5a5e226748a5dc/crates/cairo-lang-semantic/src/corelib.rs#L69)):*
> ```XML
> ) -> TypeId {
>     match try_get_core_ty_by_name(db, name, generic_args) {
>         Ok(value) => value,
> ```





_Suggestion:_
```XML
    try_get_core_ty_by_name(db, name, generic_args).unwrap_or_else(|_| panic!(
                "Corelib not found! You can provide custom path to corelib by placing \"core\" \
                 crate in the cairo project toml file."
            ))
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1763)* status: all files reviewed, 4 unresolved discussions (waiting on @maciektr and @orizi)

___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1763#-NLgopp_2elOFvJPbG-F:-NLpJDPx5KUrBATbdod8:b-sypttw) ([raw file](https://github.com/starkware-libs/cairo/blob/b2322f74a87aadc0ea5928406f5a5e226748a5dc/crates/cairo-lang-semantic/src/corelib.rs#L69)):*
> ```XML
> ) -> TypeId {
>     match try_get_core_ty_by_name(db, name, generic_args) {
>         Ok(value) => value,
> ```

.expect()?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1763)* status: all files reviewed, 4 unresolved discussions (waiting on @maciektr and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1763#-NLgopp_2elOFvJPbG-F:-NLqMRZ58mEIHTL6J-WF:bzdsebp) ([raw file](https://github.com/starkware-libs/cairo/blob/b2322f74a87aadc0ea5928406f5a5e226748a5dc/crates/cairo-lang-semantic/src/corelib.rs#L69)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

.expect()?
</blockquote></details>

agreed - unless any extra info should be provided.

**Comment by maciektr** [comment]
*[`crates/cairo-lang-semantic/src/corelib.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1763#-NLgopp_2elOFvJPbG-F:-NLwQaWp91LeZieAuHnB:bb74ptu) ([raw file](https://github.com/starkware-libs/cairo/blob/b2322f74a87aadc0ea5928406f5a5e226748a5dc/crates/cairo-lang-semantic/src/corelib.rs#L69)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

agreed - unless any extra info should be provided.
</blockquote></details>

Thx!

**Review by maciektr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1763)* status: 1 of 10 files reviewed, 4 unresolved discussions (waiting on @mkaput, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1763#-NLfANH2BaKhyLUhrf0a:-NLwQYIiA5Cn3GCkHiIZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b2322f74a87aadc0ea5928406f5a5e226748a5dc/crates/cairo-lang-filesystem/src/db.rs#L55)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Can we call this code only if corelib crate name is not interned yet in the db?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-filesystem/src/db.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1763#-NLfAUMNDLnNr5YrfCEY:-NLwQZOVBN_rotW6-bsg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b2322f74a87aadc0ea5928406f5a5e226748a5dc/crates/cairo-lang-filesystem/src/db.rs#L61)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

With the suggested condition, we can safely assume a failure here and raise error, explaining what is wrong.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1763#-NLfA4399dtly_wddqsv:-NLwR2JU8BHYa8OWaSN-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b2322f74a87aadc0ea5928406f5a5e226748a5dc/crates/cairo-lang-semantic/src/corelib.rs#L76)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Hmm, I think we shouldn't change this function's code as it is too specific, and instead raise this error (preferably via `Result::Err` I think?), in `init_files_group`. See my comment for suggestion of the flow.
</blockquote></details>

Done.

**Comment by maciektr** [comment]
*[`crates/cairo-lang-semantic/src/corelib.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1763#-NLgopp_2elOFvJPbG-F:-NLwRECT9FH8v5XGVBLd:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b2322f74a87aadc0ea5928406f5a5e226748a5dc/crates/cairo-lang-semantic/src/corelib.rs#L69)):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

Thx!
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 8 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1763)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @mkaput)

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1763#-:-NLzOeV0D9KQREfcM8TQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciektr)

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1763)* status: 7 of 11 files reviewed, 1 unresolved discussion (waiting on @maciektr, @mkaput, and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1763#-NM2zi0G91HgY6OiQV2U:-NM2zi0G91HgY6OiQV2V:b7qc1fg) (no related file):*
I don't want API consumers to have to call something extra (init_dev_corelib_crate). I want it to "just work". Here are the use cases I think we need to support:
1. The compiler itself in dev and exe mode
2. The compiler itself in dev and exe mode
3. scarb

How about we provide multiple ctors for RootDatabase:
1. One that initializes without corelib. Mainly for parsing, I guess. Not sure if important.
2. One that tries to detect corelib and returns Option<RootDatabase>, with Non when not found.
3. One with provided corelib path.

WDYT?

___

**Review by orizi — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1763)* status: all files reviewed, 1 unresolved discussion (waiting on @maciektr)

**Comment by mkaput** [comment]
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I don't want API consumers to have to call something extra (init_dev_corelib_crate). I want it to "just work". Here are the use cases I think we need to support:
1. The compiler itself in dev and exe mode
2. The compiler itself in dev and exe mode
3. scarb

How about we provide multiple ctors for RootDatabase:
1. One that initializes without corelib. Mainly for parsing, I guess. Not sure if important.
2. One that tries to detect corelib and returns Option<RootDatabase>, with Non when not found.
3. One with provided corelib path.

WDYT?
</blockquote></details>

Generally, I don't think that `corelib` detection "just works" at all for API consumers. It is based on very limited heuristics about filesystem structure, and what I am afraid of is that I see people seem to forcibly adjust their repositories structure to let it "just work". Additionally, I thought we want to hide salsa databases from user-focused APIs?

What I think would "just work" be is to bundle the corelib as a virtual fs object as a Rust crate, downloadable from crates.io, that you could pass to the ProjectConfig.

That's the reason we pushed for the extra `init_dev_corelib_crate` call -- we meant this to be a private compiler implementation detail, while what is public is passing `core` as a regular crate_root in ProjectConfig. Indeed, this may not seem obvious and may need proper documentation.

In long term what I imagine is that as API user you could do something like this:

```
cairo_lang_compiler::compile(ProjectConfig {
  content: ProjectConfigContent {
    crate_roots: HashMap::from([
      ("core".into(), CrateRoot::from_virtual(cairo_lang_corelib::get_virtual())),
      ("my_package".into(), CrateRoot::from_path("/path/to/package")),
    ])
  }
}, CompilerConfig {...})
```

and perhaps what we could provide is a shortcut to build this hashmap with core included + extra validation..?

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1763)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1763#-NM2zi0G91HgY6OiQV2U:-NM3BAFu-LTO-6VYgeh1:b-rze1cn) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Generally, I don't think that `corelib` detection "just works" at all for API consumers. It is based on very limited heuristics about filesystem structure, and what I am afraid of is that I see people seem to forcibly adjust their repositories structure to let it "just work". Additionally, I thought we want to hide salsa databases from user-focused APIs?

What I think would "just work" be is to bundle the corelib as a virtual fs object as a Rust crate, downloadable from crates.io, that you could pass to the ProjectConfig.

That's the reason we pushed for the extra `init_dev_corelib_crate` call -- we meant this to be a private compiler implementation detail, while what is public is passing `core` as a regular crate_root in ProjectConfig. Indeed, this may not seem obvious and may need proper documentation.

In long term what I imagine is that as API user you could do something like this:

```
cairo_lang_compiler::compile(ProjectConfig {
  content: ProjectConfigContent {
    crate_roots: HashMap::from([
      ("core".into(), CrateRoot::from_virtual(cairo_lang_corelib::get_virtual())),
      ("my_package".into(), CrateRoot::from_path("/path/to/package")),
    ])
  }
}, CompilerConfig {...})
```

and perhaps what we could provide is a shortcut to build this hashmap with core included + extra validation..?
</blockquote></details>

1. Today it doesn't work, agreed. I want it to, though.
2. init_dev_corelib_crate() being private isn't an excuse - at the level that does need to use it, the devleoper will need to remmeber to use it all the time, instead of having a good safe API for it. Swipping the dirt to the compiler project isn't a solution.
3. Right now, salsa is the API. We can wrap it in a higher layer, but it should definitely provide the same functionality. Queries to different levels of the compiler. So, that ctors would also translate to that Wrapper when the time comes.
4. I had the same thought about bundling. that would go into ctor No 2 detection. But Scarb won't use it I believe, right? Scarb would need Ctor 3.
5. Passing "core" crate in the project config is a bit dangerous. Instead of heavily documenting, and instead of Ctor 3, maybe we could have a ctor for RootDatabase (which is the API today defacto) from a ProjectConfig, and ProjectConfig will only have a ctor that accepts corelib as a separate parameter?

___

**Review by mkaput — COMMENTED** [review]
> Reviewed 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1763)* status: all files reviewed, 1 unresolved discussion (waiting on @maciektr)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1763#-NM2zi0G91HgY6OiQV2U:-NM3O5RQ0eky7_jHXAeT:bmknyap) (no related file):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

1. Today it doesn't work, agreed. I want it to, though.
2. init_dev_corelib_crate() being private isn't an excuse - at the level that does need to use it, the devleoper will need to remmeber to use it all the time, instead of having a good safe API for it. Swipping the dirt to the compiler project isn't a solution.
3. Right now, salsa is the API. We can wrap it in a higher layer, but it should definitely provide the same functionality. Queries to different levels of the compiler. So, that ctors would also translate to that Wrapper when the time comes.
4. I had the same thought about bundling. that would go into ctor No 2 detection. But Scarb won't use it I believe, right? Scarb would need Ctor 3.
5. Passing "core" crate in the project config is a bit dangerous. Instead of heavily documenting, and instead of Ctor 3, maybe we could have a ctor for RootDatabase (which is the API today defacto) from a ProjectConfig, and ProjectConfig will only have a ctor that accepts corelib as a separate parameter?
</blockquote></details>

Hmm, what to you say makes sense to me now :thinking: 

Ad 4. Yes, Scarb would use ctor 3, things like creative playground would use ctor 2
Ad 5. @maciektr could you please experiment with that?

In general this looks like much more work than what's in this PR already, so I think we will keep Scarb linked to this temporary branch in the first release..

___

**Comment by mkaput** [comment]
superseded by #1824

**Pull request closed without merging**
