### PR TITLE
Add u96 type.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5462)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5462)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/starknet.cairo` line 51 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5462#-NwEMjC86phN8aReVIOT:-NwEMjC99zW0jWHlwxn8:bhdyb9l) ([raw file](https://github.com/starkware-libs/cairo/blob/fca77e82960344dc561a3eb45461eba4ddc9ed79/corelib/src/starknet.cairo#L51)):*
> ```Cairo
> 
> /// Circuits
> pub mod circuits;
> ```

Maybe add it not in starknet?
espcially since we are talking about not adding it only on starknet.



_Suggestion:_
```Cairo
/// 
pub mod circuit;
```

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/starknet.cairo` line 51 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5462#-NwEMjC86phN8aReVIOT:-NwEe9fw2tnSAGzHjzI8:b-48lrs1) ([raw file](https://github.com/starkware-libs/cairo/blob/fca77e82960344dc561a3eb45461eba4ddc9ed79/corelib/src/starknet.cairo#L51)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Maybe add it not in starknet?
espcially since we are talking about not adding it only on starknet.
</blockquote></details>

Why not 'circuits'?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5462)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/starknet.cairo` line 51 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5462#-NwEMjC86phN8aReVIOT:-NwEgrux14ELibGVujx1:bqzwhhc) ([raw file](https://github.com/starkware-libs/cairo/blob/fca77e82960344dc561a3eb45461eba4ddc9ed79/corelib/src/starknet.cairo#L51)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why not 'circuits'?
</blockquote></details>

plural is different from the rest of the project.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5462)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/starknet.cairo` line 51 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5462#-NwEMjC86phN8aReVIOT:-NwElEJs-r0WuGMPAhyo:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fca77e82960344dc561a3eb45461eba4ddc9ed79/corelib/src/starknet.cairo#L51)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

plural is different from the rest of the project.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5462#-:-NwEpOK-4mJDXLjDfWjX:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
