### PR TITLE
Avoid unnecessary struct reconstruction.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3739)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/refs.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3739#-Na1k0G3E_73i0lQEfYs:-Na1k0G3E_73i0lQEfYt:b-ivgdtg) ([raw file](https://github.com/starkware-libs/cairo/blob/17ab4def066ffc01b71cf74f91eabc13d72ad8c9/crates/cairo-lang-lowering/src/lower/refs.rs#L37)):*
> ```XML
>         Some(match self.scattered.get(path)? {
>             Value::Var(var) => ctx.var_ty(*var),
>             Value::Scattered(scattered) => ctx.db().intern_type(TypeLongId::Concrete(
> ```

Another option is to get the db as an argument to this function.



_Code quote:_
```XML
 ctx.db().
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3739)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 682 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3739#-Na1kxDX3cvCPA4n9KjU:-Na1kxDX3cvCPA4n9KjV:b-6txhio) ([raw file](https://github.com/starkware-libs/cairo/blob/539a514181be7b7d830df1e7388ff0b01562e2aa/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L682)):*
> ```
>   Return(v13, v16)
> 
> //! > ==========================================================================
> ```

test deleted



_Code quote:_
```
==========================================================================
```
___
*[`crates/cairo-lang-lowering/src/lower/block_builder.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3739#-Na1lNiC8UemHhalriF9:-Na1lNiC8UemHhalriFA:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/17ab4def066ffc01b71cf74f91eabc13d72ad8c9/crates/cairo-lang-lowering/src/lower/block_builder.rs#L120)):*
> ```XML
>     }
> 
>     pub fn get_ty(
> ```

doc

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3739)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 682 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3739#-Na1kxDX3cvCPA4n9KjU:-Na1msVS1R6GItx6EWKv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/539a514181be7b7d830df1e7388ff0b01562e2aa/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L682)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

test deleted
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/block_builder.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3739#-Na1lNiC8UemHhalriF9:-Na1mrg_-fWfdNUzYI9C:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/17ab4def066ffc01b71cf74f91eabc13d72ad8c9/crates/cairo-lang-lowering/src/lower/block_builder.rs#L120)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3739#-:-Na1njJJCDQH_qbum7eC:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3739)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
