### PR TITLE
added support for return statement and error propagation inside closures

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6254)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6254#-:-O4pLi9j6xdHQBOrEi-q:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 256 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6254#-O4smP2xEBqbcwhCKU2e:-O4smP2xEBqbcwhCKU2f:bgnhthn) ([raw file](https://github.com/starkware-libs/cairo/blob/4ef2565159f8a6d4b80c15d9034150266e2a9552/crates/cairo-lang-semantic/src/expr/compute.rs#L256)):*
> ```XML
>     /// Returns whether the current context is inside a loop.
>     fn is_inside_loop(&self) -> bool {
>         self.inner_ctx.is_some() && !matches!(self.inner_ctx, Some(InnerContext::Closure { .. }))
> ```

It is better to cover all the cases in case the enum is extended.



_Suggestion:_
```XML
fn is_inside_loop(&self) -> bool {
        let Some(inner_ctx) = &self.inner_ctx else { return false };

        match inner_ctx {
            InnerContext::Loop { .. } | InnerContext::While | InnerContext::For => true,
            InnerContext::Closure { .. } => false,
        }
    }
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1614 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6254#-O4snz7q4UOCCjmoNuNL:-O4snz7q4UOCCjmoNuNM:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/4ef2565159f8a6d4b80c15d9034150266e2a9552/crates/cairo-lang-semantic/src/expr/compute.rs#L1614)):*
> ```XML
>             }
>         };
>         let old_loop_ctx =
> ```





_Suggestion:_
```XML
prev_inner_ctx
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1718 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6254#-O4so78Y1BUUPwxnc-ZV:-O4so78Y1BUUPwxnc-ZW:bultz5w) ([raw file](https://github.com/starkware-libs/cairo/blob/4ef2565159f8a6d4b80c15d9034150266e2a9552/crates/cairo-lang-semantic/src/expr/compute.rs#L1718)):*
> ```XML
>     let return_type = match ctx.inner_ctx {
>         Some(InnerContext::Closure { return_type }) => return_type,
>         _ => {
> ```

use exhaustive pattern 



_Code quote:_
```XML
 _ 
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6254)* status: all files reviewed, 3 unresolved discussions (waiting on @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6254)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 256 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6254#-O4smP2xEBqbcwhCKU2e:-O4t6yVFAdqp3WsXlJzC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4ef2565159f8a6d4b80c15d9034150266e2a9552/crates/cairo-lang-semantic/src/expr/compute.rs#L256)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

It is better to cover all the cases in case the enum is extended.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1614 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6254#-O4snz7q4UOCCjmoNuNL:-O4t6vgoCMngMwDM6xV6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4ef2565159f8a6d4b80c15d9034150266e2a9552/crates/cairo-lang-semantic/src/expr/compute.rs#L1614)):*
> ```XML
>             }
>         };
>         let old_loop_ctx =
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1718 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6254#-O4so78Y1BUUPwxnc-ZV:-O4t6vNj3z-c2UNSy_gI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4ef2565159f8a6d4b80c15d9034150266e2a9552/crates/cairo-lang-semantic/src/expr/compute.rs#L1718)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

use exhaustive pattern
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6254)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1726 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6254#-O4tGS1UDBNcX9uWk6Lu:-O4tGS1VCnWMR_xiRJmQ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/95b06c40e787b6d353fe34e911fbc847b4bb1976/crates/cairo-lang-semantic/src/expr/compute.rs#L1726)):*
> ```XML
>         | Some(InnerContext::Loop { .. })
>         | Some(InnerContext::While)
>         | Some(InnerContext::For) => {
> ```





_Suggestion:_
```XML
        | Some(InnerContext::Loop { .. } | InnerContext::While | InnerContext::For) => {
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6254)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1726 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6254#-O4tGS1UDBNcX9uWk6Lu:-O4tKYtt5c00R3TfH4he:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/95b06c40e787b6d353fe34e911fbc847b4bb1976/crates/cairo-lang-semantic/src/expr/compute.rs#L1726)):*
> ```XML
>         | Some(InnerContext::Loop { .. })
>         | Some(InnerContext::While)
>         | Some(InnerContext::For) => {
> ```

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6254#-:-O4tYILT9U5G4MCnN1nw:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
