### PR TITLE
Bug fix in store_variables: clear known stack if ap is changed.

### PR DESCRIPTION
**Pull request by liorgold2**
commit-id:12023fae

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1092)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/sierra_generator/src/store_variables/state.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1092#-NHs3XlU7vynIJE7B3HL:-NHs3XlU7vynIJE7B3HM:bo09d2e) ([raw file](https://github.com/starkware-libs/cairo/blob/38bab6cd7a60e8fc6705cea44e0808492d449aaa/crates/sierra_generator/src/store_variables/state.rs#L53)):*
> ```XML
>                 self.clear_known_stack();
>             }
>             SierraApChange::Known(value) if value != 0 => {
> ```

Didn't we want to keep the stack on store_temp?



_Code quote:_
```XML
            SierraApChange::Known(value) if value != 0 => 
```

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1092#-:-NHs4Gib-LXAq_Io2kYi:bnfp4nl)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/sierra_generator/src/store_variables/test.rs` line 369 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1092#-NHs3yr9Br2w-DVSP68V:-NHs3yr9Br2w-DVSP68W:b-iqtdjc) ([raw file](https://github.com/starkware-libs/cairo/blob/38bab6cd7a60e8fc6705cea44e0808492d449aaa/crates/sierra_generator/src/store_variables/test.rs#L369)):*
> ```XML
>             "store_temp<felt>(100) -> (200)",
>             "store_temp<felt>(101) -> (201)",
>             "nope() -> ()",
> ```

is this valid sierra?



_Code quote:_
```XML
"nope() -> ()",
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1092)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/sierra_generator/src/store_variables/state.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1092#-NHs3XlU7vynIJE7B3HL:-NHs5eHg9BQOmdpTGTRT:bs8fa0n) ([raw file](https://github.com/starkware-libs/cairo/blob/38bab6cd7a60e8fc6705cea44e0808492d449aaa/crates/sierra_generator/src/store_variables/state.rs#L53)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Didn't we want to keep the stack on store_temp?
</blockquote></details>

No. We decided to start without it. We almost never have an explicit store_temp statement, instead, we have PushValues, which behaves differently.
___
*[`crates/sierra_generator/src/store_variables/test.rs` line 369 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1092#-NHs3yr9Br2w-DVSP68V:-NHs5yMaBdhON_wxDOu6:byqdjil) ([raw file](https://github.com/starkware-libs/cairo/blob/38bab6cd7a60e8fc6705cea44e0808492d449aaa/crates/sierra_generator/src/store_variables/test.rs#L369)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

is this valid sierra?
</blockquote></details>

It's mocked

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1092)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
