### PR TITLE
Implemented array_len libfunc

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1222)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1222)* status: all files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1222)* status: 2 of 7 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @orizi)

___
*[`corelib/array.cairo` line 8 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1222#-NIYAR-1-IXUwTdgw6Xa:-NIafR0F-6VoY2XRKEG6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/353bf0ba576bcdcd03157c1da4de430c76746246/corelib/array.cairo#L8)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`crates/sierra/src/extensions/modules/array.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1222#-NIY9ybe6shTYdps_Srd:-NIagF5yCwJRnbNt9ldr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/353bf0ba576bcdcd03157c1da4de430c76746246/crates/sierra/src/extensions/modules/array.rs#L101)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

return arr_ty as well - as this action is possible even for Array<T> of T that is not duplicatable.
(the high level signature would be:
`extern array_len<T>(ref arr: Array::<T>) -> uint128 nopanic;`
)
</blockquote></details>

Done.
___
*[`crates/sierra_to_casm/src/invocations/array.rs` line 230 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1222#-NIY9OGeDgw1i5v9XdjT:-NIal8065XE02cYk60Jg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/353bf0ba576bcdcd03157c1da4de430c76746246/crates/sierra_to_casm/src/invocations/array.rs#L230)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

either implement (this is the result of subtraction, basically as long as the current code) - or use the todo! macro.

also - use it instead of writing the function itself.
</blockquote></details>

Done.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 4 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1222)* status: all files reviewed, 5 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/sierra/src/extensions/modules/array.rs` line 107 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1222#-NIasTGM0i0FLtyapRtl:-NIasTGM0i0FLtyapRtm:b4ezybz) ([raw file](https://github.com/starkware-libs/cairo/blob/0926c7ac5a7c4e1105e64c5fc39e7e245dd849dc/crates/sierra/src/extensions/modules/array.rs#L107)):*
> ```XML
>                 OutputVarInfo {
>                     ty: arr_type,
>                     ref_info: OutputVarReferenceInfo::SameAsParam { param_idx: 1 },
> ```

shouldn't this be zero? it's the first and only input parameter



_Code quote:_
```XML
1
```
___
*[`crates/sierra_to_casm/src/invocations/array.rs` line 264 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1222#-NIasyzW40HDfW8TP9if:-NIasyzW40HDfW8TP9ig:b-k0xmmx) ([raw file](https://github.com/starkware-libs/cairo/blob/0926c7ac5a7c4e1105e64c5fc39e7e245dd849dc/crates/sierra_to_casm/src/invocations/array.rs#L264)):*
> ```XML
>     /// array is in the address \[end\] + end_offset.
>     /// Never negative.
>     pub end_offset: i16,
> ```

...why not `u16`?



_Code quote:_
```XML
i
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1222)* status: all files reviewed, 6 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/sierra_to_casm/src/invocations/array.rs` line 250 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1222#-NIb51qhBTD-iOTd09h-:-NIb51qhBTD-iOTd09h0:b-aq9c79) ([raw file](https://github.com/starkware-libs/cairo/blob/44dc548adf83addafa7117eaa4970df64c1472c0/crates/sierra_to_casm/src/invocations/array.rs#L250)):*
> ```XML
>         return Err(InvocationError::InvalidReferenceExpressionForArgument);
>     }
>     // let len = array_view.end.offset - array_view.start.offset;
> ```

dead code?



_Code quote:_
```XML
// let len = array_view.end.offset - array_view.start.offset;
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1222)* status: all files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @yuvalsw)

___
*[`crates/sierra/src/extensions/modules/array.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1222#-NIao18W32M3K42_eSVq:-NIao18W32M3K42_eSVr:b-m01qis) ([raw file](https://github.com/starkware-libs/cairo/blob/85fd05c4c304d0c0daeaf5db7bff1f7e202b1e27/crates/sierra/src/extensions/modules/array.rs#L62)):*
> ```XML
>         At(ArrayAtLibFunc),
>         Len(ArrayLenLibFunc),
>         // TODO(orizi): Add access after enums are supported.
> ```

remove this as well (at was already added)



_Code quote:_
```XML
 // TODO(orizi): Add access after enums are supported.
```
___
*[`crates/sierra_to_casm/src/invocations/array.rs` line 264 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1222#-NIasyzW40HDfW8TP9if:-NIawTY_BJ9YBEF3Z9li:b-d8afal) ([raw file](https://github.com/starkware-libs/cairo/blob/0926c7ac5a7c4e1105e64c5fc39e7e245dd849dc/crates/sierra_to_casm/src/invocations/array.rs#L264)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

...why not `u16`?
</blockquote></details>

because the support for offsets in casm is i16.
___
*[`crates/sierra_to_casm/src/invocations/array.rs` line 229 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1222#-NIbLB3gE_Vmfr0Z2ZEm:-NIbLB3gE_Vmfr0Z2ZEn:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/44dc548adf83addafa7117eaa4970df64c1472c0/crates/sierra_to_casm/src/invocations/array.rs#L229)):*
> ```XML
> }
> 
> fn build_array_len(
> ```

doc



_Code quote:_
```XML
build_array_len
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1222)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @orizi)

___
*[`crates/sierra/src/extensions/modules/array.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1222#-NIao18W32M3K42_eSVq:-NIbOHxl121lJKKa-Kd6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/85fd05c4c304d0c0daeaf5db7bff1f7e202b1e27/crates/sierra/src/extensions/modules/array.rs#L62)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove this as well (at was already added)
</blockquote></details>

Done.
___
*[`crates/sierra/src/extensions/modules/array.rs` line 107 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1222#-NIasTGM0i0FLtyapRtl:-NIbNwTP6RIKnRKBBGV-:b-x0ndmj) ([raw file](https://github.com/starkware-libs/cairo/blob/0926c7ac5a7c4e1105e64c5fc39e7e245dd849dc/crates/sierra/src/extensions/modules/array.rs#L107)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

shouldn't this be zero? it's the first and only input parameter
</blockquote></details>

Good catch! Thanks
___
*[`crates/sierra_to_casm/src/invocations/array.rs` line 229 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1222#-NIbLB3gE_Vmfr0Z2ZEm:-NIbOrmB8vKWEeZEPHey:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/44dc548adf83addafa7117eaa4970df64c1472c0/crates/sierra_to_casm/src/invocations/array.rs#L229)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/sierra_to_casm/src/invocations/array.rs` line 250 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1222#-NIb51qhBTD-iOTd09h-:-NIbOP-k4zOMyalY8XBO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/44dc548adf83addafa7117eaa4970df64c1472c0/crates/sierra_to_casm/src/invocations/array.rs#L250)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

dead code?
</blockquote></details>

Done.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1222)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @orizi)

___
*[`crates/sierra_gas/src/core_libfunc_cost_base.rs` line 70 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1222#-NIbUrB6B9EwmQLYKwW2:-NIbb_0uCYfckGFImn_N:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d832009d33d022d8bf99df7aa7a5cee1eb860e74/crates/sierra_gas/src/core_libfunc_cost_base.rs#L70)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you just added cost.
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1222#-:-NIbhQiWEH-nxgtrKSmW:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1222#-:-NIbhxoq35yJd0kpFwHp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
