### PR TITLE
Change pop_front to return a box.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2515)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2515#-:-NQdjZ-o3cyPRgXlfwss:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2515#-NQdjARvDXG3Yn-N7o9p:-NQdjARw2xrO2UYu5Ss0:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/cf1c7eb59e0989c55b04f6a870b8757428710bbb/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L159)):*
> ```XML
>                         OutputVarInfo {
>                             ty: boxed_ty(context, ty)?,
>                             ref_info: OutputVarReferenceInfo::SameAsParam { param_idx: 0 },
> ```





_Suggestion:_
```XML
PartialParam
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 257 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2515#-NQdjG2-BSKhxo5CFt8T:-NQdjG2-BSKhxo5CFt8U:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/cf1c7eb59e0989c55b04f6a870b8757428710bbb/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L257)):*
> ```XML
>                         OutputVarInfo {
>                             ty: boxed_ty(context, snapshot_ty(context, ty)?)?,
>                             ref_info: OutputVarReferenceInfo::SameAsParam { param_idx: 0 },
> ```





_Suggestion:_
```XML
PartialParam
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2515)* status: 14 of 16 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2515#-NQdjARvDXG3Yn-N7o9p:-NQdl90E6WsCSoVOD6t3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cf1c7eb59e0989c55b04f6a870b8757428710bbb/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L159)):*
> ```XML
>                         OutputVarInfo {
>                             ty: boxed_ty(context, ty)?,
>                             ref_info: OutputVarReferenceInfo::SameAsParam { param_idx: 0 },
> ```

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 257 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2515#-NQdjG2-BSKhxo5CFt8T:-NQdl9KsBtx2_4pcVuaw:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cf1c7eb59e0989c55b04f6a870b8757428710bbb/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L257)):*
> ```XML
>                         OutputVarInfo {
>                             ty: boxed_ty(context, snapshot_ty(context, ty)?)?,
>                             ref_info: OutputVarReferenceInfo::SameAsParam { param_idx: 0 },
> ```

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2515)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2515)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2515)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2515)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
