### PR TITLE
Added events and functions' state mutability to contract json

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1732)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1732)* status: 3 of 9 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/abi.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1732#-NLUaO8GD3Lyh20xVDk-:-NLUaO8GD3Lyh20xVDk0:bmriryr) ([raw file](https://github.com/starkware-libs/cairo/blob/cae7adbbf14d0d842dc0fee94c2d93391a10953b/crates/cairo-lang-starknet/src/abi.rs#L49)):*
> ```XML
>             StateMutability::View
>         } else {
>             StateMutability::Unknown
> ```

I think the default should be external



_Code quote:_
```XML
  StateMutability::Unknown
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1732)* status: 2 of 9 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/abi.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1732#-NLUaO8GD3Lyh20xVDk-:-NLVKKlr0DeR5xyW5jJv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cae7adbbf14d0d842dc0fee94c2d93391a10953b/crates/cairo-lang-starknet/src/abi.rs#L49)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I think the default should be external
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/abi.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1732#-NLUaO8GD3Lyh20xVDk-:-NL_1fdTEUARvLxq14A8:busef2p) ([raw file](https://github.com/starkware-libs/cairo/blob/cae7adbbf14d0d842dc0fee94c2d93391a10953b/crates/cairo-lang-starknet/src/abi.rs#L49)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Done.
</blockquote></details>

what happens if you have attribue event?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/abi.rs` line 104 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1732#-NL_OILhCGJibiTGlS5Y:-NL_OILhCGJibiTGlS5Z:bvk7d9b) ([raw file](https://github.com/starkware-libs/cairo/blob/6d572cbf09614a0ec24c86e867c5b0245c11710c/crates/cairo-lang-starknet/src/abi.rs#L104)):*
> ```XML
> }
> 
> /// Checks whether the
> ```

fix comment.



_Code quote:_
```XML
/// Checks whether the
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1732)* status: 3 of 10 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 297 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1732#-NL_gjuA2r99Fuk0rDDm:-NL_gjuA2r99Fuk0rDDn:bhsmmxn) ([raw file](https://github.com/starkware-libs/cairo/blob/6d572cbf09614a0ec24c86e867c5b0245c11710c/crates/cairo-lang-starknet/src/plugin.rs#L297)):*
> ```XML
>                 abi_functions.push(RewriteNode::Modified(ModifiedNode {
>                     children: vec![
>                         RewriteNode::Text(format!("#[{attr}]\n        ")),
> ```

are you adding attributes to function witout attributes here?



_Code quote:_
```XML
   RewriteNode::Text(format!("#[{attr}]\n        ")),
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1732)* status: 1 of 10 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/abi.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1732#-NLUaO8GD3Lyh20xVDk-:-NLa0PJRBNj2I2Hvm_wN:b-1jo1nb) ([raw file](https://github.com/starkware-libs/cairo/blob/cae7adbbf14d0d842dc0fee94c2d93391a10953b/crates/cairo-lang-starknet/src/abi.rs#L49)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what happens if you have attribue event?
</blockquote></details>

I don't call this function, I call add_event in that case.
___
*[`crates/cairo-lang-starknet/src/abi.rs` line 104 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1732#-NL_OILhCGJibiTGlS5Y:-NLa0pe39DgyyaVUbwNE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6d572cbf09614a0ec24c86e867c5b0245c11710c/crates/cairo-lang-starknet/src/abi.rs#L104)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

fix comment.
</blockquote></details>

Done.



_Code quote:_
```XML
hecks whether the
```
___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 297 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1732#-NL_gjuA2r99Fuk0rDDm:-NLa04INDqt482LtthtW:b-qgzn3c) ([raw file](https://github.com/starkware-libs/cairo/blob/6d572cbf09614a0ec24c86e867c5b0245c11710c/crates/cairo-lang-starknet/src/plugin.rs#L297)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

are you adding attributes to function witout attributes here?
</blockquote></details>

I am not sure what you mean. If I get here, I either have external or view (or both...).

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1732)* status: 4 of 10 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 297 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1732#-NL_gjuA2r99Fuk0rDDm:-NLaHbtN0fQyF-x0xM5_:b45c9qn) ([raw file](https://github.com/starkware-libs/cairo/blob/6d572cbf09614a0ec24c86e867c5b0245c11710c/crates/cairo-lang-starknet/src/plugin.rs#L297)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

It can have neither.
</blockquote></details>

It can't. It's inside this match branch:
            ast::Item::FreeFunction(item_function)
                if item_function.has_attr(db, EXTERNAL_ATTR)
                    || item_function.has_attr(db, VIEW_ATTR) =>



_Code quote:_
```XML
            ast::Item::FreeFunction(item_function)
                if item_function.has_attr(db, EXTERNAL_ATTR)
                    || item_function.has_attr(db, VIEW_ATTR) =>
```

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 9 files at r1, 3 of 6 files at r3, 2 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1732#-:-NLaN9TQ0OukurpkJbSL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 2 of 9 files at r1, 4 of 6 files at r3, 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1732)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1732)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
