### PR TITLE
Snapshot e2e support

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2120)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 8 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2120)* status: 8 of 11 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-sierra-generator/src/utils.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2120#-NOEYmpxD65T8b1j01dr:-NOEYmpxD65T8b1j01ds:b2nhdkj) ([raw file](https://github.com/starkware-libs/cairo/blob/acc2f168bd9e27977c2aeb7c981c5fe57907b935/crates/cairo-lang-sierra-generator/src/utils.rs#L106)):*
> ```XML
> }
> 
> pub fn snapshot_take_libfunc_id(
> ```

Doc

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2120#-:-NOEYvdCDwXlz8pnBoCs:bnfp4nl)* status: 8 of 11 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2120)* status: 3 of 14 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/utils.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2120#-NOEYmpxD65T8b1j01dr:-NOEecS51Lo4Jq_gIDyV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/acc2f168bd9e27977c2aeb7c981c5fe57907b935/crates/cairo-lang-sierra-generator/src/utils.rs#L106)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Doc
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 11 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2120#-:-NOEgSEo2o5qnvNSLzQO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
