### PR TITLE
Export serialized cairo program

### PR DESCRIPTION
**Pull request by tohrnii**
This is for non rust cairo VMs that need the compiled cairo program in serialized format.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5649)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5649)* status: 2 of 8 files reviewed, 4 unresolved discussions (waiting on @tohrnii)

___
*[`crates/bin/sierra-compile/Cargo.toml` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5649#-NytrMla1s84lvmymmNW:-NytrMla1s84lvmymmNX:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7c5659f8afbb3960da8683b78b6be33a32c7bbe4/crates/bin/sierra-compile/Cargo.toml#L14)):*
> ```TOML
> clap.workspace = true
> indoc.workspace = true
> serde_json = "1.0.116"
> ```





_Suggestion:_
```TOML
serde_json.workspace = true
```
___
*[`crates/cairo-lang-sierra-to-casm/Cargo.toml` line 22 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5649#-NytrctJ16NYGqhA-Ff-:-NytrctJ16NYGqhA-Ff0:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7c5659f8afbb3960da8683b78b6be33a32c7bbe4/crates/cairo-lang-sierra-to-casm/Cargo.toml#L22)):*
> ```TOML
> num-bigint = { workspace = true, default-features = true }
> num-traits = { workspace = true, default-features = true }
> serde = { version = "1.0.200", default-features = false, features = ["derive"] }
> ```





_Suggestion:_
```TOML
serde = { workspace = true, default-features = false, features = ["derive"] }
```
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 232 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5649#-Nyts16b8DkduP2PU0fW:-Nyts16b8DkduP2PU0fX:b-4iydpd) ([raw file](https://github.com/starkware-libs/cairo/blob/7c5659f8afbb3960da8683b78b6be33a32c7bbe4/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L232)):*
> ```XML
>         map.end()
>     }
> }
> ```

this entire code is not relevant for sierra-to-casm.
especially anything related to main finding.
move this to somewhere else, possible the actual main file.



_Code quote:_
```XML
pub struct CairoProgramWithSierraContext<'a> {
    pub cairo_program: &'a CairoProgram,
    pub sierra_program: &'a Program,
}

impl<'a> CairoProgramWithSierraContext<'a> {
    pub fn new(
        cairo_program: &'a CairoProgram,
        sierra_program: &'a Program,
    ) -> CairoProgramWithSierraContext<'a> {
        CairoProgramWithSierraContext { cairo_program, sierra_program }
    }
}

impl<'a> Serialize for CairoProgramWithSierraContext<'a> {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        let mut map = serializer.serialize_map(None)?;
        let main_func = self
            .sierra_program
            .find_function("::main")
            .ok_or_else(|| S::Error::custom("Main function not found"))?;
        let entry_point = main_func.entry_point.0;
        let builtins = vec![
            "pedersen_builtin",
            "range_check_builtin",
            "bitwise_builtin",
            "ec_op_builtin",
            "poseidon_builtin",
        ];
        let assembled_cairo_program = self.cairo_program.assemble();
        map.serialize_entry("bytecode", &assembled_cairo_program.bytecode)?;
        map.serialize_entry("hints", &assembled_cairo_program.hints)?;
        map.serialize_entry("entry_point", &entry_point)?;
        map.serialize_entry("builtins", &builtins)?;
        let debug_info = self.cairo_program.debug_info
            .sierra_statement_info
            .iter()
            .map(|statement_debug_info| {
                (
                    statement_debug_info.start_offset,
                    statement_debug_info.instruction_idx,
                )
            })
            .collect::<Vec<(usize, usize)>>();
        map.serialize_entry("debug_info", &debug_info)?;
        map.serialize_entry("consts_info", &self.cairo_program.consts_info)?;
        map.end()
    }
}
```
___
*[`crates/cairo-lang-utils/Cargo.toml` line 15 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5649#-NytrjUD5oC30LXhw7at:-NytrjUD5oC30LXhw7au:bizgmsq) ([raw file](https://github.com/starkware-libs/cairo/blob/7c5659f8afbb3960da8683b78b6be33a32c7bbe4/crates/cairo-lang-utils/Cargo.toml#L15)):*
> ```TOML
> num-traits.workspace = true
> hashbrown = { workspace = true, features = ["serde"] }
> serde = { workspace = true, features = ["alloc", "derive"], optional = true }
> ```

i think it has to stay in optional to remain with no-std

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5649)* status: 3 of 8 files reviewed, 4 unresolved discussions (waiting on @tohrnii)

___
*[`crates/bin/sierra-compile/src/main.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5649#-NyvNMfL5uqZTLS4l603:-NyvNMfL5uqZTLS4l604:bslg4iu) ([raw file](https://github.com/starkware-libs/cairo/blob/14ea0b5073683171077e1eb86681ede0158fbf0c/crates/bin/sierra-compile/src/main.rs#L64)):*
> ```XML
>             .collect::<Vec<(usize, usize)>>();
>         map.serialize_entry("debug_info", &debug_info)?;
>         map.serialize_entry("consts_info", &self.cairo_program.consts_info)?;
> ```

this becomes a commitment to the internal structure of casm for calculations - we should really avoid it.
what is the exact required data?
this needs to be understood - and only this data should be outputed.
___
*[`crates/cairo-lang-sierra/src/program.rs` line 138 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5649#-NyvMnIECnBdGrZAAwcd:-NyvMnIECnBdGrZAAwce:bbnbiiy) ([raw file](https://github.com/starkware-libs/cairo/blob/14ea0b5073683171077e1eb86681ede0158fbf0c/crates/cairo-lang-sierra/src/program.rs#L138)):*
> ```XML
>     }
> 
>     /// Finds first function ending with `name_suffix`.
> ```

this probably needs to move as well - as

**Comment by tohrnii** [comment]
@orizi
>this becomes a commitment to the internal structure of casm for calculations - we should really avoid it.

Do you mean this specifically for consts_info field or the `CairoProgram` struct in general? I'm not sure about consts_info, but I think all the rest of the info is required for the runner?

Another question, if we are outputting casm json from the compiler, should it also output sierra.json? It's currently possible to get the serialized sierra using tools like scarb but if the compiler allows to output casm json, it might be better to output sierra.json from cairo-compiler binary as well.

**Review by orizi — COMMENTED** [review]
the runner does should not require most of them.
the order of action items should probably be:
* refactor runner to have a runner part, and a prep part.
* extract the prep part to the binary.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5649#-:-Nyy6vPcExyJ7Pgin8Xs:b-cyj8mx)* status: 3 of 8 files reviewed, 4 unresolved discussions (waiting on @tohrnii)

**Comment by tohrnii** [comment]
@orizi 
> extract the prep part to the binary.

That is the motivation with this PR. Essentially, non rust VMs should be able to run cairo programs without needing sierra files. Non rust VMs that can't access the sierra or cairo compiler directly will probably need to do some pre-processing anyway. It seemed like exporting all the serialized info we can from the compiler that other rust VMs have access to might be the best strategy at the compiler level. As to your point about avoiding commitment to the CASM's internal structure, that might be unavoidable if we want to serialize the info? One way to abstract it might be to implement `Serialize` for `CairoProgram` but that would require `CairoProgram` struct to also have access to `SierraProgram` info but that might not be a good solution.

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5649)* status: 3 of 8 files reviewed, 5 unresolved discussions (waiting on @orizi and @tohrnii)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5649#-NzSo_2q8MG-QyM6_THL:-NzSo_2q8MG-QyM6_THM:b-jvxit2) (no related file):*
BTW How does this PR relate to https://github.com/software-mansion/universal-sierra-compiler ?

___

**Comment by tohrnii** [comment]
@mkaput With a few changes to USC, we can accomplish the same (as discussed in a PR in scarb) but the motivation here is to avoid depending on multiple build tools (scarb to compile to sierra and the USC to compile to CASM). Please tell me if you disagree.

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5649)* status: 3 of 8 files reviewed, 5 unresolved discussions (waiting on @orizi and @tohrnii)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5649#-NzSo_2q8MG-QyM6_THL:-NzSpufk-n9iEo52NXSy:b-nwwjhg) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

BTW How does this PR relate to https://github.com/software-mansion/universal-sierra-compiler ?
</blockquote></details>

@tohrnii please use Reviewable for discussions, thanks :)

I'm totally out of the loop, so I may not know something. You seem to be using some Rust wrapper over the Cairo compiler anyway, so you can technically put https://crates.io/crates/universal-sierra-compiler crate there.

If not, then USC is giving you a ready-to-use binary, that you'd be building on your own, aren't you?

Then I don't see any benefits of integrating something into the compiler, because you would end up with an additional tool anyway

___

**Pull request closed without merging**
