### PR TITLE
Added get_gas_all as part of the plugin.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:73cc8f29

---

**Stack**:
- #1857
- #1855
- #1854
- #1853
- #1852 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1852)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin_test_data/hello_starknet` line 112 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1852#-NMS65DFB3cFuFPFLhPh:-NMS65DFB3cFuFPFLhPi:by4u8e) ([raw file](https://github.com/starkware-libs/cairo/blob/81feb1e3adbf5a7b3d269c2229f0bd62f6264f80/crates/cairo-lang-starknet/src/plugin_test_data/hello_starknet#L112)):*
> ```
>                 panic(err_data);
>             }
>             match get_gas_all(get_builtin_costs()) {
> ```

why is it called in addition to get_gas rather than instead of get_gas?

where is the implementation in sierra to casm?
build_get_builtin_costs?



_Code quote:_
```
get_gas_all
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1852)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin_test_data/hello_starknet` line 112 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1852#-NMS65DFB3cFuFPFLhPh:-NMSE8MB4n3fdF6EEbTn:blo4hky) ([raw file](https://github.com/starkware-libs/cairo/blob/818dbb76e574dc94656464fff6613514e857fca5/crates/cairo-lang-starknet/src/plugin_test_data/hello_starknet#L112)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why is it called in addition to get_gas rather than instead of get_gas?

where is the implementation in sierra to casm?
build_get_builtin_costs?

</blockquote></details>

this should cause the cost of the entrypoint to be more stable - but i guess we can drop it if we will enforce it through another method.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1852)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin_test_data/hello_starknet` line 112 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1852#-NMS65DFB3cFuFPFLhPh:-NMSF_s07av72rudnCST:btqjtzc) ([raw file](https://github.com/starkware-libs/cairo/blob/818dbb76e574dc94656464fff6613514e857fca5/crates/cairo-lang-starknet/src/plugin_test_data/hello_starknet#L112)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this should cause the cost of the entrypoint to be more stable - but i guess we can drop it if we will enforce it through another method.
</blockquote></details>

We should optimize for the good case, not for the stability of the entry point gas cost.

you can add it with a TODO.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1852)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin_test_data/hello_starknet` line 112 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1852#-NMS65DFB3cFuFPFLhPh:-NMSGIPAAwxQGe2UHI_9:bess05o) ([raw file](https://github.com/starkware-libs/cairo/blob/818dbb76e574dc94656464fff6613514e857fca5/crates/cairo-lang-starknet/src/plugin_test_data/hello_starknet#L112)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

We should optimize for the good case, not for the stability of the entry point gas cost.

you can add it with a TODO.
</blockquote></details>

stability is the constant case - good or not good.
if it enabled us to bind the initial gas cost at a lower cost, it would be good (otherwise, we need to always collect for the `get_gas_all` worst case, which can get quite large)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/plugin_test_data/hello_starknet` line 112 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1852#-NMS65DFB3cFuFPFLhPh:-NMSHLUl071Yc9EnSk9p:b-jlfjze) ([raw file](https://github.com/starkware-libs/cairo/blob/818dbb76e574dc94656464fff6613514e857fca5/crates/cairo-lang-starknet/src/plugin_test_data/hello_starknet#L112)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

stability is the constant case - good or not good.
if it enabled us to bind the initial gas cost at a lower cost, it would be good (otherwise, we need to always collect for the `get_gas_all` worst case, which can get quite large)
</blockquote></details>

If you start with a value that is too high, you can get a refund in the good case right?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1852)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin_test_data/hello_starknet` line 112 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1852#-NMS65DFB3cFuFPFLhPh:-NMSI2LA-Wt_U_mMHZaX:b-htjv0t) ([raw file](https://github.com/starkware-libs/cairo/blob/818dbb76e574dc94656464fff6613514e857fca5/crates/cairo-lang-starknet/src/plugin_test_data/hello_starknet#L112)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

If you start with a value that is too high, you can get a refund in the good case right?
</blockquote></details>

you can refund - but it means you won't be able to call if you don't have a large enough amount of gas for the heavy cases.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1852)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin_test_data/hello_starknet` line 112 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1852#-NMS65DFB3cFuFPFLhPh:-NMSJFkOCWwu7xwr52yg:btsm49h) ([raw file](https://github.com/starkware-libs/cairo/blob/818dbb76e574dc94656464fff6613514e857fca5/crates/cairo-lang-starknet/src/plugin_test_data/hello_starknet#L112)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you can refund - but it means you won't be able to call if you don't have a large enough amount of gas for the heavy cases.
</blockquote></details>

ok.

Can you explain why I can't find  get_gas_all in sierra_to_casm?

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1852#-:-NMSJMTbEd3mvCHPhlMt:bnfp4nl)* status: 0 of 10 files reviewed, all discussions resolved

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1852)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin_test_data/hello_starknet` line 112 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1852#-NMS65DFB3cFuFPFLhPh:-NMSOIfuD-XlUPMBTlfv:bumg7f8) ([raw file](https://github.com/starkware-libs/cairo/blob/818dbb76e574dc94656464fff6613514e857fca5/crates/cairo-lang-starknet/src/plugin_test_data/hello_starknet#L112)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

ok.

Can you explain why I can't find  get_gas_all in sierra_to_casm?
</blockquote></details>

it is in builtin cost file iirc

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1852)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
