### PR TITLE
Sierra-to-CASM for array_at

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
Signed-off-by: Dori Medini <dori@<a href="starkware.co">starkware.co</a>>

commit-id:aaa53133

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1105)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1105#-NHxNSD88Cf2U8ZYRtYm:-NI1LfLd7W_9jdQv3ceH:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

did you try writing a snippets_test?
</blockquote></details>

Done.

___

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1105)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`tests/snippets_test.rs` line 66 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1105#-NI1N_5e7SWFj2agiGRE:-NI1N_5e7SWFj2agiGRF:b-r2e6ni) ([raw file](https://github.com/starkware-libs/cairo/blob/eb2d9ea2d8eeb2a7b1598936b6406c333b349898/tests/snippets_test.rs#L66)):*
> ```XML
> )]
> #[test_case(
>     "func foo(idx: uint128) -> Option<felt> {
> ```

add tests for other accesses.



_Code quote:_
```XML
#[test_case(
    "func foo(idx: uint128) -> Option<felt> {
```
___
*[`tests/snippets_test.rs` line 71 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1105#-NI1NSsMExOPZIE61iaJ:-NI1NSsMExOPZIE61iaK:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/eb2d9ea2d8eeb2a7b1598936b6406c333b349898/tests/snippets_test.rs#L71)):*
> ```XML
>         arr.append(11);
>         arr.append(12);
>         return arr[idx];
> ```





_Suggestion:_
```XML
        arr[idx]
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1105)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`tests/snippets_test.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1105#-NI1NkRBBbf5UpToI6da:-NI1NkRCDgtLMHKILZk7:bdf9ak1) ([raw file](https://github.com/starkware-libs/cairo/blob/eb2d9ea2d8eeb2a7b1598936b6406c333b349898/tests/snippets_test.rs#L69)):*
> ```XML
>         let arr = array_new::<felt>();
>         arr.append(10);
>         arr.append(11);
> ```

use actual libfunc names.



_Suggestion:_
```XML
        let arr = array_new::<felt>();
        array_append(arr, 10);
        array_append(arr, 11);
        array_append(arr, 12);
        array_at(arr, idx)
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1105)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @orizi)

___
*[`tests/snippets_test.rs` line 66 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1105#-NI1N_5e7SWFj2agiGRE:-NI2UIrQ8gonasE5L6-5:b-q19l34) ([raw file](https://github.com/starkware-libs/cairo/blob/eb2d9ea2d8eeb2a7b1598936b6406c333b349898/tests/snippets_test.rs#L66)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add tests for other accesses.
</blockquote></details>

one positive test, planning a negative one. you want more accesses i.e. different indices?
___
*[`tests/snippets_test.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1105#-NI1NkRBBbf5UpToI6da:-NI2UEMICcNMWRT3rbtU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/eb2d9ea2d8eeb2a7b1598936b6406c333b349898/tests/snippets_test.rs#L69)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

use actual libfunc names.
</blockquote></details>

Done.
___
*[`tests/snippets_test.rs` line 71 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1105#-NI1NSsMExOPZIE61iaJ:-NI2UEw21eodZRgsG-Z7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/eb2d9ea2d8eeb2a7b1598936b6406c333b349898/tests/snippets_test.rs#L71)):*
> ```XML
>         arr.append(11);
>         arr.append(12);
>         return arr[idx];
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1105)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`tests/snippets_test.rs` line 66 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1105#-NI1N_5e7SWFj2agiGRE:-NI2ajjH8-wMn5uuKRaW:b2nign6) ([raw file](https://github.com/starkware-libs/cairo/blob/eb2d9ea2d8eeb2a7b1598936b6406c333b349898/tests/snippets_test.rs#L66)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

one positive test, planning a negative one. you want more accesses i.e. different indices?
</blockquote></details>

yes
___
*[`tests/snippets_test.rs` line 70 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1105#-NI2anNi1Xa2DJ4z7Aql:-NI2anNi1Xa2DJ4z7Aqm:b-o6cjf9) ([raw file](https://github.com/starkware-libs/cairo/blob/56be37776d53bc0919a379bf4398b21476b359c8/tests/snippets_test.rs#L70)):*
> ```XML
>         array_at::<felt>(arr, idx)
>     }
>     func bar(ref arr: Array::<felt>, val: felt) -> felt {
> ```

rename and add todo to remove helper when direct support is working.



_Code quote:_
```XML
bar
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, 19 of 19 files at r6, 20 of 20 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1105#-:-NI3WPOnBJE-yHeQrQZL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1105#-:-NI7HOuz9YQBFkYEYmjY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1105)* status: 27 of 28 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @orizi)

___
*[`tests/cairo_level/lib.cairo` line 90 at r8](https://reviewable.io/reviews/starkware-libs/cairo/1105#-NI7J403BQ59RLYDvwTl:-NI7J403BQ59RLYDvwTm:b-6759xh) ([raw file](https://github.com/starkware-libs/cairo/blob/88e6f7211455273d63c6294e76ad8765ff48dcb0/tests/cairo_level/lib.cairo#L90)):*
> ```Cairo
>     let arr = create_array();
>     assert_and_count(test_count, match array_at::<felt>(arr, uint128_from_felt(0)) {
>         Option::Some(x) => x == 10,
> ```

the autoformatter didn't like this, and suggested this change... wtf



_Code quote:_
```Cairo
    assert_and_count(test_count, match array_at::<felt>(arr, uint128_from_felt(0)) {
        Option::Some(x) => x == 10,
        Option::None(()) => false
    });
    assert_and_count(test_count, match array_at::<felt>(arr, uint128_from_felt(1)) {
        Option::Some(x) => x == 11,
        Option::None(()) => false
    });
    assert_and_count(test_count, match array_at::<felt>(arr, uint128_from_felt(2)) {
        Option::Some(x) => x == 12,
        Option::None(()) => false
    });
    assert_and_count(test_count, match array_at::<felt>(arr, uint128_from_felt(5)) {
        Option::Some(x) => false,
        Option::None(()) => true
    });
```

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1105)* status: 27 of 28 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`tests/cairo_level/lib.cairo` line 90 at r8](https://reviewable.io/reviews/starkware-libs/cairo/1105#-NI7J403BQ59RLYDvwTl:-NI7NCsrCIDbjuP5SMtb:blv5qp2) ([raw file](https://github.com/starkware-libs/cairo/blob/88e6f7211455273d63c6294e76ad8765ff48dcb0/tests/cairo_level/lib.cairo#L90)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the autoformatter didn't like this, and suggested this change... wtf
</blockquote></details>

add a comma after the None handling arm.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1105)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1105)* status: 27 of 28 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`tests/cairo_level/lib.cairo` line 80 at r11](https://reviewable.io/reviews/starkware-libs/cairo/1105#-NI7xdax45rT9h4o3iqF:-NI7xday6YlbihBgfVfv:bk9yd9p) ([raw file](https://github.com/starkware-libs/cairo/blob/3b5badde508c6b57dde0637c3f4413d5daffe9e6/tests/cairo_level/lib.cairo#L80)):*
> ```Cairo
> 
> func create_array() -> Array::<felt> {
>     let arr = array_new::<felt>();
> ```

inline it



_Code quote:_
```Cairo
func create_array() -> Array::<felt> {
    let arr = array_new::<felt>();
    array_append::<felt>(arr, 10);
    array_append::<felt>(arr, 11);
    array_append::<felt>(arr, 12);
    arr
}
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1105)* status: 27 of 28 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`tests/cairo_level/lib.cairo` line 80 at r11](https://reviewable.io/reviews/starkware-libs/cairo/1105#-NI7xdax45rT9h4o3iqF:-NI80UTgApMcmK2oq4gH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3b5badde508c6b57dde0637c3f4413d5daffe9e6/tests/cairo_level/lib.cairo#L80)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

inline it
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1105#-:-NI82A4n1_faIl_xRUdv:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`tests/cairo_level/lib.cairo` line 95 at r12](https://reviewable.io/reviews/starkware-libs/cairo/1105#-NI820xdD4k5ssHmkHxT:-NI820xeBzt1Zq3yEc8z:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/30a3e13c5dc3e8533b8d9e7e84c476d53416847f/tests/cairo_level/lib.cairo#L95)):*
> ```Cairo
>             Option::Some(x) => x == 12,
>             Option::None(()) => false,
>     });
> ```





_Suggestion:_
```Cairo
    array_append::<felt>(arr, 12);
    assert_and_count(test_count, match array_at::<felt>(arr, uint128_from_felt(0)) {
        Option::Some(x) => x == 10,
        Option::None(()) => false,
    });
    assert_and_count(test_count, match array_at::<felt>(arr, uint128_from_felt(1)) {
        Option::Some(x) => x == 11,
        Option::None(()) => false,
    });
    assert_and_count(test_count, match array_at::<felt>(arr, uint128_from_felt(2)) {
        Option::Some(x) => x == 12,
        Option::None(()) => false,
    });
    assert_and_count(test_count, match array_at::<felt>(arr, uint128_from_felt(5)) {
        Option::Some(x) => false,
        Option::None(()) => true,
    });
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1105)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`tests/cairo_level/lib.cairo` line 95 at r12](https://reviewable.io/reviews/starkware-libs/cairo/1105#-NI820xdD4k5ssHmkHxT:-NI82TJL2b4uAtBxyi4p:bv9oweb) ([raw file](https://github.com/starkware-libs/cairo/blob/30a3e13c5dc3e8533b8d9e7e84c476d53416847f/tests/cairo_level/lib.cairo#L95)):*
> ```Cairo
>             Option::Some(x) => x == 12,
>             Option::None(()) => false,
>     });
> ```

This fails cairo-format phase. Will this pass now after rebase?

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1105)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1105)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1105)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
