### PR TITLE
Added support for felt-array contract params.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:85a8a0ac

---

**Stack**:
- #1577
- #1576
- #1575
- #1574
- #1573
- #1572
- #1571
- #1557 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1557)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/serde.cairo` line 47 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1557#-NKRjopx1OqSc7DcGvuO:-NKRjopx1OqSc7DcGvuP:bvm0d4z) ([raw file](https://github.com/starkware-libs/cairo/blob/d2ac832ed4bccc16c6425a964bad2fa13ae1c012/corelib/serde.cairo#L47)):*
> ```Cairo
>         Option::None(_) => {
>             let mut data = array_new::<felt>();
>             array_append::<felt>(data, 'OOG');
> ```

We changed the OOG Message

We need to put the error messages in some errors file.



_Suggestion:_
```Cairo
Out of gas
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1557)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`corelib/serde.cairo` line 47 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1557#-NKRjopx1OqSc7DcGvuO:-NKSsi6n0vBBLOiCA2BR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d2ac832ed4bccc16c6425a964bad2fa13ae1c012/corelib/serde.cairo#L47)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

We changed the OOG Message

We need to put the error messages in some errors file.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1557)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-starknet/src/plugin.rs` line 98 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1557#-NKTAYQB3eND3F74jqPE:-NKTAYQB3eND3F74jqPF:b75ynj8) ([raw file](https://github.com/starkware-libs/cairo/blob/a90061ada14361177431475a2a12466238a590c1/crates/cairo-starknet/src/plugin.rs#L98)):*
> ```XML
>                             return PluginResult {
>                                 code: None,
>                                 diagnostics: vec![diag],
> ```

Can you collect the diagnostics and return them at the end of the function?



_Code quote:_
```XML
diag
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1557)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-starknet/src/plugin.rs` line 98 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1557#-NKTAYQB3eND3F74jqPE:-NKTMPm55hKs-hdOYxbT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a90061ada14361177431475a2a12466238a590c1/crates/cairo-starknet/src/plugin.rs#L98)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Can you collect the diagnostics and return them at the end of the function?
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1557)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-starknet/src/plugin.rs` line 98 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1557#-NKTAYQB3eND3F74jqPE:-NKTO0UKBF4KXZqR6kiU:b-nhhq4j) ([raw file](https://github.com/starkware-libs/cairo/blob/a90061ada14361177431475a2a12466238a590c1/crates/cairo-starknet/src/plugin.rs#L98)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not pushed?

I still see a return here.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1557)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-starknet/src/plugin.rs` line 98 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1557#-NKTAYQB3eND3F74jqPE:-NKTOGp8E09LTz86Gv02:br56xs8) ([raw file](https://github.com/starkware-libs/cairo/blob/a90061ada14361177431475a2a12466238a590c1/crates/cairo-starknet/src/plugin.rs#L98)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

not pushed?

I still see a return here.
</blockquote></details>

i changed the intenal function to collect - changing the external functions seems to me out of scope for this pr.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1557)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-starknet/src/plugin.rs` line 98 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1557#-NKTAYQB3eND3F74jqPE:-NKTRgTJ44yNtETYtbFj:b-f2dka8) ([raw file](https://github.com/starkware-libs/cairo/blob/a90061ada14361177431475a2a12466238a590c1/crates/cairo-starknet/src/plugin.rs#L98)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i changed the intenal function to collect - changing the external functions seems to me out of scope for this pr.
</blockquote></details>

nm - adding

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1557#-:-NKTXR_jAjmHQE3GR-IV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1557)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
