### PR TITLE
LS: fix missing module panic

### PR DESCRIPTION
**Pull request by piotmag769**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6172)

### CODE REVIEW

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6172)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6172#-O3mJ-P08wQsrX-J_r2l:-O3mJ-P08wQsrX-J_r2m:b-rpg5ja) (no related file):*
can you please add a test for this?

___

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6172#-:-O3mJOfgAeYkZzNeHsYQ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, and @piotmag769)

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6172)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, and @mkaput)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6172#-O3mJ-P08wQsrX-J_r2l:-O3mWkrT2QZ6NwUoOYzE:b-896fix) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

can you please add a test for this?
</blockquote></details>

Done.

___

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6172#-:-O3mWy5lDGcZ1itfWlXX:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)

**Pull request merged**
