### PR TITLE
Rename `get_item_definition` to `get_item_signature`

### PR DESCRIPTION
**Pull request by mkaput**
**Stack**:
- #5784
- #5783 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5783)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5783)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @mkaput)

___
*[`crates/cairo-lang-language-server/src/ide/hover/render/definition.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5783#-O-BA8_A-MygAC47ciNR:-O-BA8_A-MygAC47ciNS:b-7bhgxk) ([raw file](https://github.com/starkware-libs/cairo/blob/ac534366b6d19c55a48c342291abe0db41e85a05/crates/cairo-lang-language-server/src/ide/hover/render/definition.rs#L33)):*
> ```XML
>     let mut md = Markdown::empty();
> 
>     let definition = db.get_item_declaration(lookup_item_id);
> ```

rename var as well.

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5783)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-language-server/src/ide/hover/render/definition.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5783#-O-BA8_A-MygAC47ciNR:-O-FXjGa-JSWTwPV02M8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ac534366b6d19c55a48c342291abe0db41e85a05/crates/cairo-lang-language-server/src/ide/hover/render/definition.rs#L33)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rename var as well.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5783)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @mkaput)

___
*[`crates/cairo-lang-language-server/src/ide/hover/render/definition.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5783#-O-BA8_A-MygAC47ciNR:-O-FYTxDBIDw1Kt63Sf6:b-jz9rek) ([raw file](https://github.com/starkware-libs/cairo/blob/ac534366b6d19c55a48c342291abe0db41e85a05/crates/cairo-lang-language-server/src/ide/hover/render/definition.rs#L33)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

missing push probably.

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5783)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-language-server/src/ide/hover/render/definition.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5783#-O-BA8_A-MygAC47ciNR:-O-FZIdw3S5E4bzT_puO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ac534366b6d19c55a48c342291abe0db41e85a05/crates/cairo-lang-language-server/src/ide/hover/render/definition.rs#L33)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

missing push probably.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5783#-:-O-F_Vwu4-NUTNacWv_s:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Pull request merged**
