### PR TITLE
Fix unsplitting to unsplit in the correct block.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5084)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5084)* status: 0 of 2 files reviewed, 1 unresolved discussion

___
*[`crates/cairo-lang-lowering/src/optimizations/test_data/split_structs` line 491 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5084#-Nqvfep_D2h0vHhUL_C3:-Nqvfep_D2h0vHhUL_C4:b-goo01y) ([raw file](https://github.com/starkware-libs/cairo/blob/5304e83eea3e259d36ac02190db26e48dd3adc77/crates/cairo-lang-lowering/src/optimizations/test_data/split_structs#L491)):*
> ```
>   (v7: ()) <- struct_construct()
> End:
>   Return(v7)
> ```

This is the result before the fix:



_Suggestion:_
```
//! > after
Parameters: v0: core::felt252
blk0 (root):
Statements:
End:
  Match(match core::felt252_is_zero(v0) {
    IsZeroResult::Zero => blk1,
    IsZeroResult::NonZero(v2) => blk2,
  })

blk1:
Statements:
  (v1: (core::felt252, core::felt252)) <- struct_construct(v0, v0)
  () <- test::use_tuple::<core::felt252>(v1)
End:
  Goto(blk3, {})

blk2:
Statements:
  (v1: (core::felt252, core::felt252)) <- struct_construct(v0, v0)
  () <- test::use_tuple::<core::felt252>(v1)
End:
  Goto(blk3, {})

blk3:
Statements:
  (v7: ()) <- struct_construct()
End:
  Return(v7)
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5084)* status: all files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/split_structs.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5084#-Nqvllro-2VXKcHhFDIx:-Nqvllro-2VXKcHhFDIy:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5304e83eea3e259d36ac02190db26e48dd3adc77/crates/cairo-lang-lowering/src/optimizations/split_structs.rs#L44)):*
> ```XML
>     EndOFlock(BlockId),
>     Location(StatementLocation),
> }
> ```





_Suggestion:_
```XML
/// Information about a split variable.
struct SplitInfo {
    /// The block_id where the variable was defined.
    block_id: BlockId,
    /// The variables resulting from the split.
    vars: Vec<VariableId>,
}

/// The location where a variable should be reconstructed.
enum ReconstructLocation {
    EndOFlock(BlockId),
    Location(StatementLocation),
}
```
___
*[`crates/cairo-lang-lowering/src/optimizations/split_structs.rs` line 172 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5084#-NqvmKNy42fYS8Vp0pqQ:-NqvmKNy42fYS8Vp0pqR:b-19p5nw) ([raw file](https://github.com/starkware-libs/cairo/blob/5304e83eea3e259d36ac02190db26e48dd3adc77/crates/cairo-lang-lowering/src/optimizations/split_structs.rs#L172)):*
> ```XML
>                     } else {
>                         block.statements.push(Statement::StructDestructure(stmt));
>                         stmt_idx += 1;
> ```

is `stmt_idx` the same as `block.statements.len()`?



_Code quote:_
```XML
                        stmt_idx += 1;
```
___
*[`crates/cairo-lang-lowering/src/optimizations/split_structs.rs` line 275 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5084#-Nqvn3Oh9rg3n9iPIMIc:-Nqvn3Oh9rg3n9iPIMId:b-gj1lx6) ([raw file](https://github.com/starkware-libs/cairo/blob/5304e83eea3e259d36ac02190db26e48dd3adc77/crates/cairo-lang-lowering/src/optimizations/split_structs.rs#L275)):*
> ```XML
>     // If not we need to unsplit it at the end of the of the original block as it might be used
>     // by more then one of the childrent.
>     let unsplit_location = if block_id == split_info.block_id {
> ```

consider rename of all unsplit to reconstruct

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/split_structs.rs` line 172 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5084#-NqvmKNy42fYS8Vp0pqQ:-NqvuRMsB5QwYabqrhYk:bml2nt5) ([raw file](https://github.com/starkware-libs/cairo/blob/5304e83eea3e259d36ac02190db26e48dd3adc77/crates/cairo-lang-lowering/src/optimizations/split_structs.rs#L172)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is `stmt_idx` the same as `block.statements.len()`?
</blockquote></details>

No, stmt_idx also counts reconstruct statement.
I'll try to add the statement in ` check_if_var_needs_reconstruction`

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5084)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/split_structs.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5084#-Nqvllro-2VXKcHhFDIx:-Nqw2oh073qQySpDWG1h:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5304e83eea3e259d36ac02190db26e48dd3adc77/crates/cairo-lang-lowering/src/optimizations/split_structs.rs#L44)):*
> ```XML
>     EndOFlock(BlockId),
>     Location(StatementLocation),
> }
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/optimizations/split_structs.rs` line 275 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5084#-Nqvn3Oh9rg3n9iPIMIc:-Nqw3Jix6BvNh0w6gjOj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5304e83eea3e259d36ac02190db26e48dd3adc77/crates/cairo-lang-lowering/src/optimizations/split_structs.rs#L275)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

consider rename of all unsplit to reconstruct
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5084#-:-Nqw3ztADD5BvQH416mA:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/split_structs.rs` line 172 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5084#-NqvmKNy42fYS8Vp0pqQ:-Nqw8SxA7UxqpA--O_ft:bz9p7tv) ([raw file](https://github.com/starkware-libs/cairo/blob/5304e83eea3e259d36ac02190db26e48dd3adc77/crates/cairo-lang-lowering/src/optimizations/split_structs.rs#L172)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

No, stmt_idx also counts reconstruct statement.
I'll try to add the statement in ` check_if_var_needs_reconstruction`
</blockquote></details>

Removed stmt_idx.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5084)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
