### PR TITLE
United imports

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2944)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2944** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2944" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2944?utm_source=stack-comment).

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 17 of 20 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2944)* status: 18 of 20 files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-defs/src/db.rs` line 436 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2944#-NU105XN1D-aan5Fpo3o:-NU105XN1D-aan5Fpo3p:b-i6kzw3) ([raw file](https://github.com/starkware-libs/cairo/blob/eb7efdd957f9aa326c117d9c4a3f5b54c40bf208/crates/cairo-lang-defs/src/db.rs#L436)):*
> ```XML
> 
> /// Returns all the path leaves under a given use path.
> pub fn get_all_path_leafs(
> ```

consider renaming to `_helper` or something similar, removing `pub` and adding a wrapper returning a vector.



_Code quote:_
```XML
get_all_path_leafs
```
___
*[`crates/cairo-lang-parser/src/parser_test_data/reserved_identifier` line 277 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2944#-NU13-2C2WjQwOiHxTr2:-NU13-2C2WjQwOiHxTr3:b54zkon) ([raw file](https://github.com/starkware-libs/cairo/blob/b32dbb9d78e0722c9717a65981190a5d770458b1/crates/cairo-lang-parser/src/parser_test_data/reserved_identifier#L277)):*
> ```
> 
> //! > expected_diagnostics
> error: 'mod' is a reserved identifier.
> ```

why is this gone?



_Code quote:_
```
//! > expected_diagnostics
error: 'mod' is a reserved identifier.
```
___
*[`crates/cairo-lang-parser/src/parser_test_data/underscore_not_supported` line 277 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2944#-NU1322Y0arH-xpvsaVx:-NU1322Y0arH-xpvsaVy:b-7ropln) ([raw file](https://github.com/starkware-libs/cairo/blob/b32dbb9d78e0722c9717a65981190a5d770458b1/crates/cairo-lang-parser/src/parser_test_data/underscore_not_supported#L277)):*
> ```
> 
> //! > expected_diagnostics
> error: An underscore ('_') is not allowed as an identifier in this context.
> ```

ditto



_Code quote:_
```
//! > expected_diagnostics
error: An underscore ('_') is not allowed as an identifier in this context.
```
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 126 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2944#-NU13Yb14ojkSMP_WOfJ:-NU13Yb14ojkSMP_WOfK:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/eb7efdd957f9aa326c117d9c4a3f5b54c40bf208/crates/cairo-lang-semantic/src/resolve/mod.rs#L126)):*
> ```XML
> }
> 
> pub trait AsSegments {
> ```

doc



_Code quote:_
```XML
pub trait AsSegments {
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2944#-:-NU1NeDj4gllIzWWdjx4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2944)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-defs/src/db.rs` line 436 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2944#-NU105XN1D-aan5Fpo3o:-NU1N5Vs9aZ7ulfd5PWf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/eb7efdd957f9aa326c117d9c4a3f5b54c40bf208/crates/cairo-lang-defs/src/db.rs#L436)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

consider renaming to `_helper` or something similar, removing `pub` and adding a wrapper returning a vector.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 126 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2944#-NU13Yb14ojkSMP_WOfJ:-NU1MHfq7eX9WFxS8A8C:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/eb7efdd957f9aa326c117d9c4a3f5b54c40bf208/crates/cairo-lang-semantic/src/resolve/mod.rs#L126)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/reserved_identifier` line 277 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2944#-NU13-2C2WjQwOiHxTr2:-NU1N6LyCf8nyO-X7vaq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b32dbb9d78e0722c9717a65981190a5d770458b1/crates/cairo-lang-parser/src/parser_test_data/reserved_identifier#L277)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why is this gone?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/underscore_not_supported` line 277 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2944#-NU1322Y0arH-xpvsaVx:-NU1M2V27dWittT1XAyX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b32dbb9d78e0722c9717a65981190a5d770458b1/crates/cairo-lang-parser/src/parser_test_data/underscore_not_supported#L277)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Pull request merged**
