### PR TITLE
Fixed contract code to not copy mut modifier to ABI

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2297)

### CODE REVIEW

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2297)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2297#-NPHtWkD3Uiiz6pkFyqG:-NPHtWkE0KRt2F-D11hi:b-3yf84a) (no related file):*
change target branch

___

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2297#-:-NPHyeguCj46Z3rHTlsP:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 145 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2297#-NPHy9EY2nulqu4n2hGy:-NPHy9EZ6CUrks7A4ldC:b-fc1o61) ([raw file](https://github.com/starkware-libs/cairo/blob/b554faa4367e925d7514fdfe7fa003c7386619de/crates/cairo-lang-starknet/src/plugin/contract.rs#L145)):*
> ```XML
>                     declaration.signature(db).parameters(db).elements(db).iter().enumerate()
>                 {
>                     // TODO(yuval): this assumes `mut` can only appear alone.
> ```

this is also true - so just add it as a note - not a todo.



_Code quote:_
```XML
                {
                    // TODO(yuval): this assumes `mut` can only appear alone.
```
___
*[`crates/cairo-lang-starknet/src/plugin/utils.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2297#-NPHyZ3v0WZSwE81rFk3:-NPHyZ3v0WZSwE81rFk4:buznniu) ([raw file](https://github.com/starkware-libs/cairo/blob/b554faa4367e925d7514fdfe7fa003c7386619de/crates/cairo-lang-starknet/src/plugin/utils.rs#L17)):*
> ```XML
>     // TODO(yuval): This works only if "mut" is the only modifier. If the expansion was at the
>     // semantic level, we could just ask if it's a reference.
>     param_modifiers.len() == 1 && matches!(param_modifiers[0], Modifier::Mut(_))
> ```

i think



_Suggestion:_
```XML
    matches!(&param_modifiers[..], [Modifier::Mut(_)])
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2297)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 145 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2297#-NPHy9EY2nulqu4n2hGy:-NPIgpCL4EA1_9ofgM9G:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2ded6405e969b20cc05a4a9800fe763915db829d/crates/cairo-lang-starknet/src/plugin/contract.rs#L145)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is also true - so just add it as a note - not a todo.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/utils.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2297#-NPHyZ3v0WZSwE81rFk3:-NPIhUir5U0Fqlvw_Z_7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2ded6405e969b20cc05a4a9800fe763915db829d/crates/cairo-lang-starknet/src/plugin/utils.rs#L17)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i think
</blockquote></details>

Done.

**Review by yuvalsw — COMMENTED** [review]
> Dismissed @orizi from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2297)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2297#-:-NPIiAwQ7SzHdVg9--DD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2297)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2297)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
