### PR TITLE
Replace CostValidationInfo.range_check_info with builtin_infos.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5840)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5840)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs` line 351 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5840#-O-q5dA2DTsJAjZwOiAC:-O-q5dA2DTsJAjZwOiAD:b-cijyam) ([raw file](https://github.com/starkware-libs/cairo/blob/8c1a968d4430638169699cf7b4b445abcf38e757/crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs#L351)):*
> ```XML
> /// Cost validation info for a builtin.
> struct BuiltinInfo {
>     const_token_ty: CostTokenType,
> ```

doc members.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs` line 360 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5840#-O-q69WC8F7KMOmXneD5:-O-q69WC8F7KMOmXneD6:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8c1a968d4430638169699cf7b4b445abcf38e757/crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs#L360)):*
> ```XML
> struct CostValidationInfo<const BRANCH_COUNT: usize> {
>     // infos about builtin usage.
>     pub builtin_infos: Vec<BuiltinInfo>,
> ```





_Suggestion:_
```XML
    /// infos about builtin usage.
    pub builtin_infos: Vec<BuiltinInfo>,
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs` line 353 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5840#-O02bSlK1ciH7LkGxeyo:-O02bSlK1ciH7LkGxeyp:b-aq10b1) ([raw file](https://github.com/starkware-libs/cairo/blob/8c1a968d4430638169699cf7b4b445abcf38e757/crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs#L353)):*
> ```XML
>     const_token_ty: CostTokenType,
>     start: Var,
>     end: Var,
> ```

it has to be the same var at the end of all the branches, right?



_Code quote:_
```XML
 end: Var,
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5840)* status: 3 of 18 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs` line 351 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5840#-O-q5dA2DTsJAjZwOiAC:-O02bq306GuuR5oydfg2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8c1a968d4430638169699cf7b4b445abcf38e757/crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs#L351)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc members.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs` line 360 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5840#-O-q69WC8F7KMOmXneD5:-O02bqYl9hT2kQWbGIa4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8c1a968d4430638169699cf7b4b445abcf38e757/crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs#L360)):*
> ```XML
> struct CostValidationInfo<const BRANCH_COUNT: usize> {
>     // infos about builtin usage.
>     pub builtin_infos: Vec<BuiltinInfo>,
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5840#-:-O02cTFM1PrebNsHDGSs:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs` line 353 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5840#-O02bSlK1ciH7LkGxeyo:-O02cIXVCTUxkYKKzDk7:bsq3umv) ([raw file](https://github.com/starkware-libs/cairo/blob/8c1a968d4430638169699cf7b4b445abcf38e757/crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs#L353)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it has to be the same var at the end of all the branches, right?
</blockquote></details>

Yes, as it is the vat passed for all branches.

**Pull request merged**
