### PR TITLE
Fix licence file.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1300)

### CODE REVIEW

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1300#-:-NJ4Eoey2EcwVmK_ykUX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1300#-:-NJ4Fp_dDyrrR9-bEpYb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Comment by musalbas** [comment]
My understanding is that the LICENSE file itself shouldn't be edited, because those are instructions on _how_ to use the Apache 2.0 license (it's a paragraph in the appendix about how apply the notice):

image

Rather, the notice itself should be in the source code or a separate NOTICE file, eg: https://github.com/apache/spark/blob/master/NOTICE or https://github.com/kubernetes/kubernetes/blob/master/hack/ginkgo-e2e.sh

(In both of those example repos they didn't edit the LICENSE file itself)

**Comment by ilyalesokhin-starkware** [comment]
Thank you, I will look into it.

**Comment by ilyalesokhin-starkware** [comment]
@musalbas 
Is https://reviewable.io/reviews/starkware-libs/cairo/2795#- 
ok?

**Comment by musalbas** [comment]
Not quite. Rather than removing the appendix in the LICENSE, you should restore the original copy of the Apache 2.0, completely unedited and untouched, and then add a file called NOTICE that mentions Starkware Industries as the copyright owner, such ashttps://github.com/apache/spark/blob/master/NOTICE

To restore the original apache 2.0 license, you would need to restore the appendix and change line 189 back to "Copyright [yyyy] [name of copyright owner]" exactly as is - ie do not fill in anything and it should literally say the words "name of copyright owner", not starkware industries.

You can see the apache spark repo linked above as an example.

**Comment by ilyalesokhin-starkware** [comment]
@dan-starkware

**Comment by ilyalesokhin-starkware** [comment]
@musalbas 
According to
https://github.com/playframework/play-ws/pull/712
the notice file is for Apache Software Foundation projects

**Comment by musalbas** [comment]
Yes the NOTICE file is optional, if you already have a copyright notice as a comment at the top of every source code file, like playframework does, but this repo does not. Also, playframework did not modify the LICENSE file. You either need to include a copyright notice at the top of every source code file like playframework, or add a NOTICE file like apache spark. It's not true that a NOTICE file can only be used by apache projects, kubernetes uses it too for example.

**Pull request merged**
