### PR TITLE
Add a deprecated hint variant.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2994)

### CODE REVIEW

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2994)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2994#-NULXPTB6hoDIzhy9jWc:-NULXPTB6hoDIzhy9jWd:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/15a80e0a45fe2a977547340ea788ef5f99b1c824/crates/cairo-lang-casm/src/hints/mod.rs#L35)):*
> ```XML
>             Hint::Core(hint) => hint.fmt(f),
>             Hint::Starknet(hint) => hint.fmt(f),
>             Hint::Deprecated(_) => unreachable!("Deprecated hints should not be printed."),
> ```





_Suggestion:_
```XML
Hint::Deprecated(_) => unreachable!("Deprecated hints do not have a pythonic version."),
```
___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 234 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2994#-NULXb-X1kYohqlISVz0:-NULXb-X1kYohqlISVz1:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/15a80e0a45fe2a977547340ea788ef5f99b1c824/crates/cairo-lang-casm/src/hints/mod.rs#L234)):*
> ```XML
> }
> 
> /// Represents a deprecated hint which is kept for backwards compatibility of previously deployed
> ```





_Suggestion:_
```XML
/// Represents a deprecated hint which is kept for backward compatibility of previously deployed
/// contracts.
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2994)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2994#-NULXsMK5P8Kj9lkKtdr:-NULXsML1JqwieYF4QcL:b-dwqpje) (no related file):*
Can you take a contract from a previous commit that used one of these hints, and make sure it is parsed successfully with the new code? (non-blocking for the version, but we should check it this week)

___

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2994)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2994#-NULXsMK5P8Kj9lkKtdr:-NULkWZ4416vhZVQlGFw:b-s0g2hx) (no related file):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Can you take a contract from a previous commit that used one of these hints, and make sure it is parsed successfully with the new code? (non-blocking for the version, but we should check it this week)
</blockquote></details>

Already did for the previous version, rechecking now that I've added another untagged layer.

___
___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2994#-NULXPTB6hoDIzhy9jWc:-NUM60P9ExIl9wWTZPCZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/15a80e0a45fe2a977547340ea788ef5f99b1c824/crates/cairo-lang-casm/src/hints/mod.rs#L35)):*
> ```XML
>             Hint::Core(hint) => hint.fmt(f),
>             Hint::Starknet(hint) => hint.fmt(f),
>             Hint::Deprecated(_) => unreachable!("Deprecated hints should not be printed."),
> ```

Done.
___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 234 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2994#-NULXb-X1kYohqlISVz0:-NUM61Yr08jDUX4TiWQR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/15a80e0a45fe2a977547340ea788ef5f99b1c824/crates/cairo-lang-casm/src/hints/mod.rs#L234)):*
> ```XML
> }
> 
> /// Represents a deprecated hint which is kept for backwards compatibility of previously deployed
> ```

Done.

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2994#-:-NUMLKTo7HQLI331ezED:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
