### PR TITLE
Adding casm instruction index to the compiled sierra debug info.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4519)

### CODE REVIEW

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4519)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 139 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4519#-Nkz3eIPEq6qsv8YDCnf:-Nkz3eIPEq6qsv8YDCng:b-lahc2e) ([raw file](https://github.com/starkware-libs/cairo/blob/e903a255f5aa776e226f53107b6dd72db38f6865/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L139)):*
> ```XML
>     for (statement_id, statement) in program.statements.iter().enumerate() {
>         let statement_idx = StatementIdx(statement_id);
>         statement_indices.push(statement_offsets.len());
> ```

I don't get it, won't it simply be `[0, 1, 2,...]`?



_Code quote:_
```XML
statement_indices.push(statement_offsets.len());
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4519)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 139 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4519#-Nkz3eIPEq6qsv8YDCnf:-Nkz8PrhA38SQQpgmffs:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e903a255f5aa776e226f53107b6dd72db38f6865/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L139)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

I don't get it, won't it simply be `[0, 1, 2,...]`?
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4519)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 117 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4519#-NkzibkCEDhF6ObbGb34:-Nkzz_oR4zAKOhIMq9gZ:bjtuuew) ([raw file](https://github.com/starkware-libs/cairo/blob/b829717dc31132dd2a4f27055dc6de6fb23fa7ba/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L117)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Since the two vectors are always changed together, why not a vector of `SierraStatementDebugInfo`?
</blockquote></details>

Since later code (relocate part) uses the offsets directly

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4519#-:-Nl2ZdF_7DJIpbMOq0WL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
