### PR TITLE
LSP better goto definition

### PR DESCRIPTION
**Pull request by spapinistarkware**
Now, it works for all items, not just free functions.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1114)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 7 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1114)* status: 7 of 10 files reviewed, 6 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/languageserver/src/lib.rs` line 336 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1114#-NHx6VwT0X47xzGhAhth:-NHx6VwU3qHjLb6G6tD-:b8czike) ([raw file](https://github.com/starkware-libs/cairo/blob/526686811f1eb63b6d85196b037bcf141359ecfb/crates/languageserver/src/lib.rs#L336)):*
> ```XML
> 
>         // Build texts.
>         eprintln!("Got node");
> ```

remove or make into log.



_Code quote:_
```XML
eprintln!("Got node");
```
___
*[`crates/languageserver/src/lib.rs` line 421 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1114#-NHx7DU_3ONzKclaOEhS:-NHx7DU_3ONzKclaOEhT:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/526686811f1eb63b6d85196b037bcf141359ecfb/crates/languageserver/src/lib.rs#L421)):*
> ```XML
> }
> 
> fn lookup_item_from_ast(
> ```

doc



_Code quote:_
```XML
lookup_item_from_ast
```
___
*[`crates/languageserver/src/lib.rs` line 472 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1114#-NHx7CAN1DojNRUa9216:-NHx7CAN1DojNRUa9217:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/526686811f1eb63b6d85196b037bcf141359ecfb/crates/languageserver/src/lib.rs#L472)):*
> ```XML
> }
> 
> fn get_node_and_item(
> ```

doc



_Code quote:_
```XML
get_node_and_item
```
___
*[`crates/languageserver/src/lib.rs` line 524 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1114#-NHx7IWBBnpLlJ9M67yQ:-NHx7IWBBnpLlJ9M67yR:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/526686811f1eb63b6d85196b037bcf141359ecfb/crates/languageserver/src/lib.rs#L524)):*
> ```XML
> }
> 
> fn get_identifier_hint(
> ```

doc



_Code quote:_
```XML
get_identifier_hint(
```
___
*[`crates/languageserver/src/lib.rs` line 534 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1114#-NHx7Atk6tkw_ei_8xqD:-NHx7Atk6tkw_ei_8xqE:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/526686811f1eb63b6d85196b037bcf141359ecfb/crates/languageserver/src/lib.rs#L534)):*
> ```XML
>     }
>     let identifier = ast::TerminalIdentifier::from_syntax_node(syntax_db, node.parent().unwrap());
>     eprintln!("id:{:?}", free_function_id.debug(db));
> ```

remove



_Code quote:_
```XML
 eprintln!("id:{:?}", free_function_id.debug(db));
```
___
*[`crates/languageserver/src/lib.rs` line 539 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1114#-NHx78qt1NJXzd12fdx5:-NHx78qt1NJXzd12fdx6:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/526686811f1eb63b6d85196b037bcf141359ecfb/crates/languageserver/src/lib.rs#L539)):*
> ```XML
>         identifier.stable_ptr(),
>     )?;
>     eprintln!("item:{item:?}");
> ```

remove



_Code quote:_
```XML
    eprintln!("item:{item:?}");
```

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1114)* status: all files reviewed, 6 unresolved discussions (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1114)* status: 8 of 13 files reviewed, 6 unresolved discussions (waiting on @orizi)

___
*[`crates/languageserver/src/lib.rs` line 336 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1114#-NHx6VwT0X47xzGhAhth:-NHx9T9QBVExL_1yKYnE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/526686811f1eb63b6d85196b037bcf141359ecfb/crates/languageserver/src/lib.rs#L336)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove or make into log.
</blockquote></details>

Done.
___
*[`crates/languageserver/src/lib.rs` line 421 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1114#-NHx7DU_3ONzKclaOEhS:-NHx9TmA8wkhqPtshGJt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/526686811f1eb63b6d85196b037bcf141359ecfb/crates/languageserver/src/lib.rs#L421)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/languageserver/src/lib.rs` line 472 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1114#-NHx7CAN1DojNRUa9216:-NHx9U9h6YTw9c9NMGSV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/526686811f1eb63b6d85196b037bcf141359ecfb/crates/languageserver/src/lib.rs#L472)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/languageserver/src/lib.rs` line 524 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1114#-NHx7IWBBnpLlJ9M67yQ:-NHx9kQd-xj7lFZXjRgV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/526686811f1eb63b6d85196b037bcf141359ecfb/crates/languageserver/src/lib.rs#L524)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/languageserver/src/lib.rs` line 534 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1114#-NHx7Atk6tkw_ei_8xqD:-NHx9kdO7aXD3f4uNPYG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/526686811f1eb63b6d85196b037bcf141359ecfb/crates/languageserver/src/lib.rs#L534)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`crates/languageserver/src/lib.rs` line 539 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1114#-NHx78qt1NJXzd12fdx5:-NHx9l6X4fyr0m4jHbVr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/526686811f1eb63b6d85196b037bcf141359ecfb/crates/languageserver/src/lib.rs#L539)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1114#-:-NHxDF-L0weZo4dt8Kdj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
