### PR TITLE
Audit comments.

### PR DESCRIPTION
**Pull request by liorgold2**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4885)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4885)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs` line 124 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4885#-NoqNfDy3-xMlb1QL5WF:-NoqNfDy3-xMlb1QL5WG:b-7wl8ep) ([raw file](https://github.com/starkware-libs/cairo/blob/2abcd5ffb78d9dd5d6982a11534edfde689164ca/crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs#L124)):*
> ```XML
>         ));
>     }
>     // TODO: Can we move this up and replace `unwrap_or` -> `unwrap`?
> ```

checking.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4885#-NoqNgHq7lL4a8Lrkl9S:-NoqNgHq7lL4a8Lrkl9T:bnqzhxr) ([raw file](https://github.com/starkware-libs/cairo/blob/2abcd5ffb78d9dd5d6982a11534edfde689164ca/crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs#L125)):*
> ```XML
>     }
>     // TODO: Can we move this up and replace `unwrap_or` -> `unwrap`?
>     // TODO: Note this is also verified inside `add_get_total_requested_count_code`.
> ```

i know - but it is still easier.
suggestions?
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs` line 139 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4885#-NoqMKAb6oOxBt20lzKl:-NoqMKAb6oOxBt20lzKm:bbhzu5s) ([raw file](https://github.com/starkware-libs/cairo/blob/2abcd5ffb78d9dd5d6982a11534edfde689164ca/crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs#L139)):*
> ```XML
>         tempvar builtin_cost = cost_builtin_ptr;
>     };
>     let (_, total_requested_count) =
> ```

it is required for the `extra_costs` at line 148.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4885)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs` line 124 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4885#-NoqNfDy3-xMlb1QL5WF:-NoqTxkE3tQ9lVjnbQKh:b-vjou2r) ([raw file](https://github.com/starkware-libs/cairo/blob/2abcd5ffb78d9dd5d6982a11534edfde689164ca/crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs#L124)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

checking.
</blockquote></details>

Updated by https://reviewable.io/reviews/starkware-libs/cairo/4890
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4885#-NoqNgHq7lL4a8Lrkl9S:-NoqTu_R9VSmCEkPTmOK:b-vjou2r) ([raw file](https://github.com/starkware-libs/cairo/blob/2abcd5ffb78d9dd5d6982a11534edfde689164ca/crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs#L125)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i know - but it is still easier.
suggestions?
</blockquote></details>

Updated by https://reviewable.io/reviews/starkware-libs/cairo/4890

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4885)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs` line 124 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4885#-NoqNfDy3-xMlb1QL5WF:-Np-IXfnENpp-dwkyGB7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2abcd5ffb78d9dd5d6982a11534edfde689164ca/crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs#L124)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Updated by https://reviewable.io/reviews/starkware-libs/cairo/4890
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4885#-NoqNgHq7lL4a8Lrkl9S:-Np-IYNU4sDuhnViq2sS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2abcd5ffb78d9dd5d6982a11534edfde689164ca/crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs#L125)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Updated by https://reviewable.io/reviews/starkware-libs/cairo/4890
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4885)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs` line 139 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4885#-NoqMKAb6oOxBt20lzKl:-Np-WBtPAL-Hby8E7XZC:b-6dyg0v) ([raw file](https://github.com/starkware-libs/cairo/blob/2abcd5ffb78d9dd5d6982a11534edfde689164ca/crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs#L139)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it is required for the `extra_costs` at line 148.
</blockquote></details>

https://reviewable.io/reviews/starkware-libs/cairo/4922

**Pull request closed without merging**
