### PR TITLE
Added u8 basic operators support.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:60ca4c6b

---

**Stack**:
- #1816
- #1815
- #1814
- #1813
- #1807 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1807#-:-NM82uc0E5Nsp67mh8dh:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`corelib/integer.cairo` line 144 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1807#-NM82EcR-awsOpsY-A2E:-NM82EcS4xhA9s6PUAKq:b-i6z4tn) ([raw file](https://github.com/starkware-libs/cairo/blob/1544f41765c797bed8ebbf8688ef9bfb60cf37ee/corelib/integer.cairo#L144)):*
> ```Cairo
> 
> #[inline(always)]
> fn u8_gt(a: u8, b: u8) -> bool implicits(RangeCheck) nopanic {
> ```

Consider making the implicits implicit.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1807#-:-NM8F5qD9koAhud5-YE3:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1807)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`corelib/integer.cairo` line 144 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1807#-NM82EcR-awsOpsY-A2E:-NM8sKgCACL53LWZba9s:b-3q0to2) ([raw file](https://github.com/starkware-libs/cairo/blob/1544f41765c797bed8ebbf8688ef9bfb60cf37ee/corelib/integer.cairo#L144)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Consider making the implicits implicit.
</blockquote></details>

In the corelib - I generally prefer them explicit, to allow usage by libs that may decide to be explicit as well.

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1807)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @gilbens-starkware and @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1807)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
