### PR TITLE
Use store_deferred instead of store_temp.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4173)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4173)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4173#-NfespgO68gAN-3zXWCr:-NfespgQ1Dva73lsVDpO:b-euvf7s) (no related file):*
Can you explain the reasoning in the later lines of the commit message?

___

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/local_variables_test_data/e2e` line 362 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4173#-Nff7sSM0w_OW4hkunpq:-Nff7sSM0w_OW4hkunpr:b-z9rcpw) ([raw file](https://github.com/starkware-libs/cairo/blob/0af7e58234d0653608e44864580c625e7c044d86/crates/cairo-lang-sierra-generator/src/local_variables_test_data/e2e#L362)):*
> ```
> felt252_add([0], [4]) -> ([2])
> store_local<felt252>([3], [2]) -> ([2])
> felt252_is_zero([1]) { fallthrough() label_test::foo::1([5]) }
> ```

Before the fix, you have an additional store temp here:



_Suggestion:_
```
felt252_add([0], [4]) -> ([2])
store_temp<felt252>([2]) -> ([2])
store_local<felt252>([3], [2]) -> ([2])
felt252_is_zero([1]) { fallthrough() label_test::foo::1([5]) }
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4173)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4173#-NfespgO68gAN-3zXWCr:-Nff4Cr-BrrBf6ttBaKs:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Can you explain the reasoning in the later lines of the commit message?
</blockquote></details>

Done.

___

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4173#-:-NffOQEV7STHs5HUMh1y:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
