### PR TITLE
Module scope

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2681)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2680** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2680" target="_blank">Graphite</a> 
    * **PR #2681** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2681" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2681?utm_source=stack-comment).

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2681)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2681#-NS0KcFUASk6FVmjuJgF:-NS0KcFVEixu2uCt9T6m:b-7bsl0y) ([raw file](https://github.com/starkware-libs/cairo/blob/564b3e43356f88731130b83d4f6d9fc04732e8f6/crates/cairo-lang-semantic/src/db.rs#L134)):*
> ```XML
>     fn priv_module_semantic_data(&self, module_id: ModuleId) -> Maybe<Arc<ModuleSemanticData>>;
> 
>     /// Returns the module [Scope]
> ```

make this make more sense.



_Code quote:_
```XML
    /// Returns the module [Scope]
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2681)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2681#-NS0KcFUASk6FVmjuJgF:-NSB8Nnx92LCPP4GA4GX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/564b3e43356f88731130b83d4f6d9fc04732e8f6/crates/cairo-lang-semantic/src/db.rs#L134)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

make this make more sense.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2681#-:-NSBBlmpBFc7g17gevJq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
