### PR TITLE
Add delay_var_def optimization.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2629)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2629)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/delay_var_def.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2629#-NRcPiUD5CfOZbuDSL6V:-NRcPiUD5CfOZbuDSL6W:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/fffc521258521bb44250a881a6ea44a44a1d4449/crates/cairo-lang-lowering/src/optimizations/delay_var_def.rs#L14)):*
> ```XML
> use crate::{BlockId, FlatLowered, MatchInfo, Statement, VarRemapping, VariableId};
> 
> /// Moves var definitions closer to thier use point.
> ```





_Suggestion:_
```XML
/// Moves var definitions closer to their usage point.
```
___
*[`crates/cairo-lang-lowering/src/optimizations/delay_var_def.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2629#-NRcPnHyB1t1efzui31Y:-NRcPnHyB1t1efzui31Z:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/fffc521258521bb44250a881a6ea44a44a1d4449/crates/cairo-lang-lowering/src/optimizations/delay_var_def.rs#L15)):*
> ```XML
> 
> /// Moves var definitions closer to thier use point.
> /// Currently only moves consts.
> ```





_Suggestion:_
```XML
/// Currently only moves single use consts.
```
___
*[`crates/cairo-lang-lowering/src/optimizations/delay_var_def.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2629#-NRcPzMv4i99p8oD1l45:-NRcPzMv4i99p8oD1l46:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/fffc521258521bb44250a881a6ea44a44a1d4449/crates/cairo-lang-lowering/src/optimizations/delay_var_def.rs#L24)):*
> ```XML
>         let ctx = analysis.analyzer;
> 
>         let mut changes_by_block = HashMap::<BlockId, Vec<(usize, Option<Statement>)>, _>::new();
> ```





_Suggestion:_
```XML
        let mut changes_by_block = OrderedHashMap::<BlockId, Vec<(usize, Option<Statement>)>, _>::new();
```
___
*[`crates/cairo-lang-lowering/src/optimizations/delay_var_def.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2629#-NRcQZgG6TZqEnl4OiKY:-NRcQZgG6TZqEnl4OiKZ:bqsp5tq) ([raw file](https://github.com/starkware-libs/cairo/blob/fffc521258521bb44250a881a6ea44a44a1d4449/crates/cairo-lang-lowering/src/optimizations/delay_var_def.rs#L37)):*
> ```XML
>             // Apply block changes in revese order to prevent a change from invalidating the
>             // indices of the other changes.
>             block_changes.sort_by_key(|(index, _)| Reverse(*index));
> ```

consider



_Suggestion:_
```XML
            // Apply block changes in revese order to prevent a change from invalidating the
            // indices of the other changes.
            for (index, opt_statment) in block_changes.into_iter().sorted_by_key(|(index, _)| Reverse(*index)) {
                match opt_statment {
                    Some(stmt) => statments.insert(index, stmt),
                    None => {
                        statments.remove(index);
                    }
                }
            }
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/delay_var_def.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2629#-NRcPnHyB1t1efzui31Y:-NRcWm812wOOs6K4VRN4:b-e6tfgl) ([raw file](https://github.com/starkware-libs/cairo/blob/fffc521258521bb44250a881a6ea44a44a1d4449/crates/cairo-lang-lowering/src/optimizations/delay_var_def.rs#L15)):*
> ```XML
> 
> /// Moves var definitions closer to thier use point.
> /// Currently only moves consts.
> ```

What is a single use const?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2629)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/delay_var_def.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2629#-NRcQZgG6TZqEnl4OiKY:-NRcX7uyEEmaxIxlNjB9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fffc521258521bb44250a881a6ea44a44a1d4449/crates/cairo-lang-lowering/src/optimizations/delay_var_def.rs#L37)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

consider
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/optimizations/delay_var_def.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2629#-NRcRohaBCgIb1xyKLST:-NRcX8XO0D0NHRvOgTZb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fffc521258521bb44250a881a6ea44a44a1d4449/crates/cairo-lang-lowering/src/optimizations/delay_var_def.rs#L57)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc - are these all the uses?
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2629)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/delay_var_def.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2629#-NRcPiUD5CfOZbuDSL6V:-NRcZQmK2TPNxmrPZ7xP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fffc521258521bb44250a881a6ea44a44a1d4449/crates/cairo-lang-lowering/src/optimizations/delay_var_def.rs#L14)):*
> ```XML
> use crate::{BlockId, FlatLowered, MatchInfo, Statement, VarRemapping, VariableId};
> 
> /// Moves var definitions closer to thier use point.
> ```

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2629)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/delay_var_def.rs` line 108 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2629#-NRcS1i_2CglA41HxHhT:-NRcZVlE60i7savC6ikQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fffc521258521bb44250a881a6ea44a44a1d4449/crates/cairo-lang-lowering/src/optimizations/delay_var_def.rs#L108)):*
> ```XML
>                 match info.movable_vars.entry(*var_id) {
>                     indexmap::map::Entry::Occupied(mut e) => {
>                         // A variable that is used in multiple arms can be move to
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2629)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/delay_var_def.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2629#-NRcPzMv4i99p8oD1l45:-NRcZ-xp0kLuPrio5HhE:bny3nfm) ([raw file](https://github.com/starkware-libs/cairo/blob/fffc521258521bb44250a881a6ea44a44a1d4449/crates/cairo-lang-lowering/src/optimizations/delay_var_def.rs#L24)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why?
</blockquote></details>

because we try to avoid using the regular HashMaps.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2629)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/delay_var_def.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2629#-NRcPzMv4i99p8oD1l45:-NRca2M66CsDfcA_mEUm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fffc521258521bb44250a881a6ea44a44a1d4449/crates/cairo-lang-lowering/src/optimizations/delay_var_def.rs#L24)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

because we try to avoid using the regular HashMaps.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2629)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2629)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
