### PR TITLE
support for match with or_pattern_list in the paser

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4453)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 12 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4453)* status: 12 of 16 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1370 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4453#-NjriOha9QsWHlQ7Rgpj:-NjriOha9QsWHlQ7Rgpk:b-9i7fx9) ([raw file](https://github.com/starkware-libs/cairo/blob/72cf1bc15330f7baf15b112b42c522e6a24f829c/crates/cairo-lang-lowering/src/lower/mod.rs#L1370)):*
> ```XML
>     expr: &semantic::ExprEnumVariantCtor,
>     builder: &mut BlockBuilder,
> ) -> LoweringResult<LoweredExpr> {
> ```

remove line.
___
*[`crates/cairo-lang-parser/src/parser_test.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4453#-NjriXT59lbmArC_0yzl:-NjriXT59lbmArC_0yzm:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/72cf1bc15330f7baf15b112b42c522e6a24f829c/crates/cairo-lang-parser/src/parser_test.rs#L171)):*
> ```XML
>         function_signature: "function_signature",
>         function_call: "function_call",
>         match1: "match",
> ```





_Suggestion:_
```XML
        match_: "match",
```
___
*[`crates/cairo-lang-parser/src/parser_test_data/diagnostics/match` line 67 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4453#-Njrid2E-kWREsPmuxVI:-Njrid2F8SLDxgpFhViq:bgh737x) ([raw file](https://github.com/starkware-libs/cairo/blob/72cf1bc15330f7baf15b112b42c522e6a24f829c/crates/cairo-lang-parser/src/parser_test_data/diagnostics/match#L67)):*
> ```
>    let e = MyEnumLong::a;
>    match e {
>        MyEnumLong::a | MyEnumLong::b=> {
> ```

format properly.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/match` line 10 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4453#-Njrih5t-qPVI-sLfQQ4:-Njrih5t-qPVI-sLfQQ5:batpvwm) ([raw file](https://github.com/starkware-libs/cairo/blob/72cf1bc15330f7baf15b112b42c522e6a24f829c/crates/cairo-lang-parser/src/parser_test_data/partial_trees/match#L10)):*
> ```
>     let x = 5;
>     match x {
>         0=>1,
> ```

format properly.
also everywhere.

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 13 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4453)* status: 13 of 16 files reviewed, 9 unresolved discussions (waiting on @orizi and @TomerStarkware)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1579 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4453#-NjvRFyZ6QJfUxViNaIM:-NjvRFyZ6QJfUxViNaIN:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/72cf1bc15330f7baf15b112b42c522e6a24f829c/crates/cairo-lang-parser/src/parser.rs#L1579)):*
> ```XML
>         }
> 
>         let pattern_list_grreen = PatternListOr::new_green(self.db, pattern_list);
> ```





_Suggestion:_
```XML
pattern_list_green
```
___
*[`crates/cairo-lang-parser/src/parser_test_data/diagnostics/match` line 22 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4453#-NjvHogc9xb_vmxGzoUV:-NjvHogc9xb_vmxGzoUW:bh62lqf) ([raw file](https://github.com/starkware-libs/cairo/blob/72cf1bc15330f7baf15b112b42c522e6a24f829c/crates/cairo-lang-parser/src/parser_test_data/diagnostics/match#L22)):*
> ```
> 
> //! > expected_diagnostics
> error: Missing token TerminalOr.
> ```

The diagnostics was bad to begin with, but I think that missing `MatchArrow` is still better than missing or.
Try to check if this can be improved.
___
*[`crates/cairo-lang-parser/src/parser_test_data/diagnostics/match` line 52 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4453#-NjvIOZB3Ztw_88AyGvH:-NjvIOZB3Ztw_88AyGvI:b499mc6) ([raw file](https://github.com/starkware-libs/cairo/blob/72cf1bc15330f7baf15b112b42c522e6a24f829c/crates/cairo-lang-parser/src/parser_test_data/diagnostics/match#L52)):*
> ```
> 
> //! > test_comments
> // TODO(spapini): Improve diagnostics.
> ```

There are no diagnostics to improve here, so remove.
 And this is the diagnostics test file, I think this test will fill better in the partial tree test file.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/match` line 4 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4453#-NjvIvX94MG7ZRRPMowS:-NjvIvX94MG7ZRRPMowT:b55bd4r) ([raw file](https://github.com/starkware-libs/cairo/blob/72cf1bc15330f7baf15b112b42c522e6a24f829c/crates/cairo-lang-parser/src/parser_test_data/partial_trees/match#L4)):*
> ```
> 
> //! > test_runner_name
> test_partial_parser_tree(expect_diagnostics: *)
> ```

Change the * to false, also in other tests. (* is useful mostly when writing the test)
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 801 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4453#-NjvQc4D44URCCjtqkG-:-NjvQc4E9lMTWcwbdZwK:b-seyfoy) ([raw file](https://github.com/starkware-libs/cairo/blob/72cf1bc15330f7baf15b112b42c522e6a24f829c/crates/cairo-lang-semantic/src/expr/compute.rs#L801)):*
> ```XML
>                 let pattern = compute_pattern_semantic(
>                     new_ctx,
>                     syntax_arm.patterns(syntax_db).elements(syntax_db).first().unwrap(),
> ```

Assert that there is only one pattern in the list.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 16 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4453)* status: 15 of 16 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-parser/src/parser_test_data/diagnostics/match` line 73 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4453#-NjwIRKL96dONmcUXNYh:-NjwIRKM4iB9Sqnl0-fz:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9b3291f887d2bf29e19493bdfd68f1769bef823b/crates/cairo-lang-parser/src/parser_test_data/diagnostics/match#L73)):*
> ```
>            1
>        },
>    }
> ```





_Suggestion:_
```
       MyEnumLong::a | MyEnumLong::b => {
           3
       },
       MyEnumLong::c => {
           1
       },
   }
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4453)* status: 13 of 16 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1579 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4453#-NjvRFyZ6QJfUxViNaIM:-NjwGuid0ndEFbuHmHtF:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/72cf1bc15330f7baf15b112b42c522e6a24f829c/crates/cairo-lang-parser/src/parser.rs#L1579)):*
> ```XML
>         }
> 
>         let pattern_list_grreen = PatternListOr::new_green(self.db, pattern_list);
> ```

Done.
___
*[`crates/cairo-lang-parser/src/parser_test.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4453#-NjriXT59lbmArC_0yzl:-NjsYZvLDeHIL9i2YhEe:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/72cf1bc15330f7baf15b112b42c522e6a24f829c/crates/cairo-lang-parser/src/parser_test.rs#L171)):*
> ```XML
>         function_signature: "function_signature",
>         function_call: "function_call",
>         match1: "match",
> ```

Done
___
*[`crates/cairo-lang-parser/src/parser_test_data/diagnostics/match` line 22 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4453#-NjvHogc9xb_vmxGzoUV:-NjwXsiP08GmZQFx7hsJ:bviblwt) ([raw file](https://github.com/starkware-libs/cairo/blob/72cf1bc15330f7baf15b112b42c522e6a24f829c/crates/cairo-lang-parser/src/parser_test_data/diagnostics/match#L22)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

The diagnostics was bad to begin with, but I think that missing `MatchArrow` is still better than missing or.
Try to check if this can be improved.
</blockquote></details>

From my understanding this will require `parse_separated_list_inner` to accept two `should_stop` predicates in case the list cannot end with a separator
one for the separator and for the element.
Do you think this change is recommended
___
*[`crates/cairo-lang-parser/src/parser_test_data/diagnostics/match` line 52 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4453#-NjvIOZB3Ztw_88AyGvH:-NjwXkPY-0GcO-Xp64iM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/72cf1bc15330f7baf15b112b42c522e6a24f829c/crates/cairo-lang-parser/src/parser_test_data/diagnostics/match#L52)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

There are no diagnostics to improve here, so remove.
 And this is the diagnostics test file, I think this test will fill better in the partial tree test file.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/diagnostics/match` line 67 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4453#-Njrid2E-kWREsPmuxVI:-NjwIng41Ben-9Ck3epO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/72cf1bc15330f7baf15b112b42c522e6a24f829c/crates/cairo-lang-parser/src/parser_test_data/diagnostics/match#L67)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

format properly.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/diagnostics/match` line 73 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4453#-NjwIRKL96dONmcUXNYh:-NjwIkhK9C2b90GasZ46:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9b3291f887d2bf29e19493bdfd68f1769bef823b/crates/cairo-lang-parser/src/parser_test_data/diagnostics/match#L73)):*
> ```
>            1
>        },
>    }
> ```

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/match` line 4 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4453#-NjvIvX94MG7ZRRPMowS:-NjwXaW93keseHBvR9WV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/72cf1bc15330f7baf15b112b42c522e6a24f829c/crates/cairo-lang-parser/src/parser_test_data/partial_trees/match#L4)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Change the * to false, also in other tests. (* is useful mostly when writing the test)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/match` line 10 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4453#-Njrih5t-qPVI-sLfQQ4:-NjwIqkG3eXrVthr9LB6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/72cf1bc15330f7baf15b112b42c522e6a24f829c/crates/cairo-lang-parser/src/parser_test_data/partial_trees/match#L10)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

format properly.
also everywhere.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1370 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4453#-NjriOha9QsWHlQ7Rgpj:-NjwGvFg9fiUyWu45dfC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/72cf1bc15330f7baf15b112b42c522e6a24f829c/crates/cairo-lang-lowering/src/lower/mod.rs#L1370)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove line.
</blockquote></details>

Done.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4453)* status: 11 of 16 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 801 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4453#-NjvQc4D44URCCjtqkG-:-NjwavDrD95Epqm6-ch8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/72cf1bc15330f7baf15b112b42c522e6a24f829c/crates/cairo-lang-semantic/src/expr/compute.rs#L801)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Assert that there is only one pattern in the list.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4453)* status: 14 of 16 files reviewed, 8 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-parser/src/parser_test_data/diagnostics/match` line 61 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4453#-Njwlg6Z0DUwlFMuNZK0:-Njwlg6Z0DUwlFMuNZK1:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/44b6103f1dc474cb4ec6e36542190b3960671351/crates/cairo-lang-parser/src/parser_test_data/diagnostics/match#L61)):*
> ```
>         0 = 1,
>         _=>2,
>     };
> ```





_Suggestion:_
```
        _ => 2,
    };
```
___
*[`crates/cairo-lang-parser/src/parser_test_data/diagnostics/match` line 98 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4453#-Njwloc41pUbJLvkX4WH:-Njwloc41pUbJLvkX4WI:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/44b6103f1dc474cb4ec6e36542190b3960671351/crates/cairo-lang-parser/src/parser_test_data/diagnostics/match#L98)):*
> ```
>         0|1| =>1,
>         _=>2,
>     };
> ```





_Suggestion:_
```
    let x = 5;
    match x {
        0 | 1 | => 1,
        _ => 2,
    };
```
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 799 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4453#-Njwm5Vm9x17GQlc3_7j:-Njwm5Vm9x17GQlc3_7k:b6i2p5l) ([raw file](https://github.com/starkware-libs/cairo/blob/44b6103f1dc474cb4ec6e36542190b3960671351/crates/cairo-lang-semantic/src/expr/compute.rs#L799)):*
> ```XML
>                 // for it.
> 
>                 assert_eq!(syntax_arm.patterns(syntax_db).elements(syntax_db).len(), 1);
> ```

is this logically a `todo!`?
if so - make it an actual todo and not an assert.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4453)* status: 12 of 16 files reviewed, 8 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-parser/src/parser_test_data/diagnostics/match` line 61 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4453#-Njwlg6Z0DUwlFMuNZK0:-Njwp2Vx4s5Sg2w3K8px:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/44b6103f1dc474cb4ec6e36542190b3960671351/crates/cairo-lang-parser/src/parser_test_data/diagnostics/match#L61)):*
> ```
>         0 = 1,
>         _=>2,
>     };
> ```

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/diagnostics/match` line 98 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4453#-Njwloc41pUbJLvkX4WH:-Njwp2-Q3qUnuoViO2ZC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/44b6103f1dc474cb4ec6e36542190b3960671351/crates/cairo-lang-parser/src/parser_test_data/diagnostics/match#L98)):*
> ```
>         0|1| =>1,
>         _=>2,
>     };
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 799 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4453#-Njwm5Vm9x17GQlc3_7j:-Njwp4007CJGpoVr8NHu:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/44b6103f1dc474cb4ec6e36542190b3960671351/crates/cairo-lang-semantic/src/expr/compute.rs#L799)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is this logically a `todo!`?
if so - make it an actual todo and not an assert.
</blockquote></details>

Done

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4453)* status: all files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 799 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4453#-Njwm5Vm9x17GQlc3_7j:-NjwtTFv1tJj6X5MKNXk:b4xrwpw) ([raw file](https://github.com/starkware-libs/cairo/blob/44b6103f1dc474cb4ec6e36542190b3960671351/crates/cairo-lang-semantic/src/expr/compute.rs#L799)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

Done
</blockquote></details>

do you have an immediate following PR?
If not - add `SemanticDiagnosticKind::Unsupported`diagnostic instead.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4453)* status: 14 of 16 files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 799 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4453#-Njwm5Vm9x17GQlc3_7j:-NkAWusZBcwcyw0CRadP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/44b6103f1dc474cb4ec6e36542190b3960671351/crates/cairo-lang-semantic/src/expr/compute.rs#L799)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

do you have an immediate following PR?
If not - add `SemanticDiagnosticKind::Unsupported`diagnostic instead.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4453#-:-NkBkhvO5-ZJ2mK-U5QM:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware)

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 3 files at r3, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4453)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-parser/src/parser_test_data/diagnostics/match` line 22 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4453#-NjvHogc9xb_vmxGzoUV:-NkEsLqe6pfybCNsq5J2:bqe3b2t) ([raw file](https://github.com/starkware-libs/cairo/blob/72cf1bc15330f7baf15b112b42c522e6a24f829c/crates/cairo-lang-parser/src/parser_test_data/diagnostics/match#L22)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

From my understanding this will require `parse_separated_list_inner` to accept two `should_stop` predicates in case the list cannot end with a separator
one for the separator and for the element.
Do you think this change is recommended
</blockquote></details>

No, this will be too complicated. For now just change the TODO above to:
`Improve diagnostics in case of braces in a match argument.`
And also change the spapini, you can put it on me.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 16 files at r1, 1 of 2 files at r4, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4453#-:-NkL5UTM1Jbh2uZAmCQW:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 7 of 7 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4453)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
