### PR TITLE
Added syntax and parsing for associated type

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4640)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4640)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 958 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4640#-NmCuUBRCedDnaaLEexh:-NmCuUBRCedDnaaLEexi:b-allkuu) ([raw file](https://github.com/starkware-libs/cairo/blob/8c16476896bc434574d03e11f5fc127cb7c60cad/crates/cairo-lang-parser/src/parser.rs#L958)):*
> ```XML
>     /// Assumes the current token is Type.
>     /// Expected pattern: `type <name> = <type>;`
>     fn expect_impl_associated_type(
> ```

isn't it the exact same as the type alias definition?

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4640)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 958 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4640#-NmCuUBRCedDnaaLEexh:-NmPqYph8EWx2xY217uL:bcg5y80) ([raw file](https://github.com/starkware-libs/cairo/blob/8c16476896bc434574d03e11f5fc127cb7c60cad/crates/cairo-lang-parser/src/parser.rs#L958)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

isn't it the exact same as the type alias definition?
</blockquote></details>

no visibility and generic params. Seemed better to have a different syntax for it to avoid ugly adjustments. (I took a similar decision for associated impls down the PR road, used item const for associated const as the only diff was visibility)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4640)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 958 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4640#-NmCuUBRCedDnaaLEexh:-NmPs2iY5okwxUAFO0Rb:bep5av3) ([raw file](https://github.com/starkware-libs/cairo/blob/8c16476896bc434574d03e11f5fc127cb7c60cad/crates/cairo-lang-parser/src/parser.rs#L958)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

no visibility and generic params. Seemed better to have a different syntax for it to avoid ugly adjustments. (I took a similar decision for associated impls down the PR road, used item const for associated const as the only diff was visibility)
</blockquote></details>

i'm not sure that in the end it shouldn't be the same (any particular reason to not allow a generic type, const or impl there?)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 13 files at r2, 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4640#-:-NmR6fclBwgFFKC-WB6B:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
