### PR TITLE
adding support to use statements in semantics

### PR DESCRIPTION
**Pull request by Tomer-StarkWare**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6356)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6356)* status: 1 of 8 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-defs/src/ids.rs` line 968 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6356#-O61IXnU0jkTZ89uCLZg:-O61IXnU0jkTZ89uCLZh:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/39b09076f3273775c343f1d6519355fd9cebe5c7/crates/cairo-lang-defs/src/ids.rs#L968)):*
> ```XML
>     lookup_intern_local_use,
>     intern_local_use
> );
> ```





_Suggestion:_
```XML
define_top_level_language_element_id!(
    StatementUseId,
    StatementUseLongId,
    ast::UsePathLeaf,
    lookup_intern_statement_use,
    intern_statement_use
);
```

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6356#-:-O61zuZfC8O274RQVpP2:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @gilbens-starkware, and @Tomer-StarkWare)

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6356)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, and @orizi)

___
*[`crates/cairo-lang-defs/src/ids.rs` line 968 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6356#-O61IXnU0jkTZ89uCLZg:-O61Qtjs-mBmUNASS2Qw:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/39b09076f3273775c343f1d6519355fd9cebe5c7/crates/cairo-lang-defs/src/ids.rs#L968)):*
> ```XML
>     lookup_intern_local_use,
>     intern_local_use
> );
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6356)* status: 3 of 69 files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 3509 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6356#-O6FdFv346XCIPXv3tQu:-O6FdFv346XCIPXv3tQv:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f005ce92ddd67425de7f9cc9664a680c2feffd77/crates/cairo-lang-semantic/src/expr/compute.rs#L3509)):*
> ```XML
>                         name,
>                         var_def,
>                         name_syntax.stable_ptr().untyped(),
> ```





_Suggestion:_
```XML
                        &name_syntax,
```
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 3548 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6356#-O6FdIAi3msH7UsYDzk_:-O6FdIAi3msH7UsYDzka:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f005ce92ddd67425de7f9cc9664a680c2feffd77/crates/cairo-lang-semantic/src/expr/compute.rs#L3548)):*
> ```XML
>                                     name,
>                                     var_def,
>                                     leaf.stable_ptr().untyped(),
> ```





_Suggestion:_
```XML
                                    &leaf,
```
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 3603 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6356#-O6Fd7-o6EprKHRxC_uE:-O6Fd7-o6EprKHRxC_uF:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f005ce92ddd67425de7f9cc9664a680c2feffd77/crates/cairo-lang-semantic/src/expr/compute.rs#L3603)):*
> ```XML
>     var_def: Binding,
>     stable_ptr: SyntaxStablePtrId,
> ) {
> ```





_Suggestion:_
```XML
    stable_ptr: impl Into<SyntaxStablePtrId>,
) {
```
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 3609 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6356#-O6FbW_T5FK-LkyPNN2S:-O6FbW_T5FK-LkyPNN2T:b-4xai4b) ([raw file](https://github.com/starkware-libs/cairo/blob/f005ce92ddd67425de7f9cc9664a680c2feffd77/crates/cairo-lang-semantic/src/expr/compute.rs#L3609)):*
> ```XML
>             match old_var {
>                 Binding::LocalItem(_) => MultipleConstantDefinition(name),
>                 Binding::LocalVar(_) | Binding::Param(_) => MultipleDefinitionforItem(name),
> ```

this seems wrong.



_Code quote:_
```XML
                Binding::LocalItem(_) => MultipleConstantDefinition(name),
                Binding::LocalVar(_) | Binding::Param(_) => MultipleDefinitionforItem(name),
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6356)* status: 2 of 69 files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 3509 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6356#-O6FdFv346XCIPXv3tQu:-O6FestsA_a4AZbC_pkq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f005ce92ddd67425de7f9cc9664a680c2feffd77/crates/cairo-lang-semantic/src/expr/compute.rs#L3509)):*
> ```XML
>                         name,
>                         var_def,
>                         name_syntax.stable_ptr().untyped(),
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 3548 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6356#-O6FdIAi3msH7UsYDzk_:-O6Fesd55AYGJp1mwYrc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f005ce92ddd67425de7f9cc9664a680c2feffd77/crates/cairo-lang-semantic/src/expr/compute.rs#L3548)):*
> ```XML
>                                     name,
>                                     var_def,
>                                     leaf.stable_ptr().untyped(),
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 3603 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6356#-O6Fd7-o6EprKHRxC_uE:-O6FesAx-BEadRKWFE-9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f005ce92ddd67425de7f9cc9664a680c2feffd77/crates/cairo-lang-semantic/src/expr/compute.rs#L3603)):*
> ```XML
>     var_def: Binding,
>     stable_ptr: SyntaxStablePtrId,
> ) {
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 3609 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6356#-O6FbW_T5FK-LkyPNN2S:-O6FerowDOLxSObHcC9N:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f005ce92ddd67425de7f9cc9664a680c2feffd77/crates/cairo-lang-semantic/src/expr/compute.rs#L3609)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this seems wrong.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, 2 of 6 files at r2, 1 of 63 files at r3, 61 of 61 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6356)* status: 68 of 69 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 1 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6356#-O6Fg0ta66SlvrYyafDB:-O6Fg0ta66SlvrYyafDC:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/1398ecf2f512c82804e551c154207a4637c971fe/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L1)):*
> ```
> //! > Test use initialization
> ```

?



_Code quote:_
```
initialization
```
___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 91 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6356#-O6Fg9leEDULoN5T7kRn:-O6Fg9leEDULoN5T7kRo:b-v9q54w) ([raw file](https://github.com/starkware-libs/cairo/blob/1398ecf2f512c82804e551c154207a4637c971fe/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L91)):*
> ```
> 
> //! > expr_code
> Y
> ```

remove irrelevant errors.



_Suggestion:_
```
{}
```
___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 108 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6356#-O6FgLcp70vnSGRqkxKb:-O6FgLcp70vnSGRqkxKc:b-d1f2nx) ([raw file](https://github.com/starkware-libs/cairo/blob/1398ecf2f512c82804e551c154207a4637c971fe/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L108)):*
> ```
> //! > ==========================================================================
> 
> //! > Test use the wrong const
> ```

bad name.

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6356)* status: 68 of 69 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 1 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6356#-O6Fg0ta66SlvrYyafDB:-O6Fi4uV6NAP5UVG9_9r:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1398ecf2f512c82804e551c154207a4637c971fe/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L1)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 91 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6356#-O6Fg9leEDULoN5T7kRn:-O6FiFVs5TNSwUQZ6sYZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1398ecf2f512c82804e551c154207a4637c971fe/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L91)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove irrelevant errors.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 108 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6356#-O6FgLcp70vnSGRqkxKb:-O6FkXVN89BNiLHJwivE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1398ecf2f512c82804e551c154207a4637c971fe/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L108)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

bad name.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6356)* status: 68 of 69 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 25 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6356#-O6Fnps_7v4MauCGxRSL:-O6Fnps_7v4MauCGxRSM:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c76be663a1aa7b4efbcadc405c3b46b8f9885fd1/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L25)):*
> ```
> )
> 
> //! > expected_diagnostics
> ```





_Suggestion:_
```
//! > function_body

//! > expr_code
{ use X::Y; }

//! > expected_semantics
Constant(
    ExprConstant {
        const_value_id: 2,
        ty: core::integer::u8,
    },
)

//! > expected_diagnostics
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6356)* status: 68 of 69 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 25 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6356#-O6Fnps_7v4MauCGxRSL:-O6FofGo-59DlFT_uDyU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c76be663a1aa7b4efbcadc405c3b46b8f9885fd1/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L25)):*
> ```
> )
> 
> //! > expected_diagnostics
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6356)* status: 68 of 69 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 4 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6356#-O6Fuyyz7nRCBGC1ss_L:-O6Fuyyz7nRCBGC1ss_M:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/69a1a7d4221b31f022f34df4e824a0a031ff1c57/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L4)):*
> ```
> 
> //! > test_runner_name
> test_expr_semantics(expect_diagnostics: true)
> ```





_Suggestion:_
```
test_expr_semantics(expect_diagnostics: warnings_only)
```
___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 54 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6356#-O6FvCtX0MIvxFUJEZpD:-O6FvCtX0MIvxFUJEZpE:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/69a1a7d4221b31f022f34df4e824a0a031ff1c57/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L54)):*
> ```
> { use X::{X, Y, Z}; 
> X + Y
> }
> ```





_Suggestion:_
```
//! > function_body
use X::{X, Y, Z};
let _ = X + Y;

//! > expr_code
{}
```
___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 118 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6356#-O6FvS48CuXUzrUu8QNm:-O6FvS48CuXUzrUu8QNn:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/69a1a7d4221b31f022f34df4e824a0a031ff1c57/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L118)):*
> ```
> 
> //! > expr_code
> A
> ```





_Suggestion:_
```
use X::A;
const A: u8 = 4;
let _ = A;

//! > expr_code
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6356)* status: 68 of 69 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 4 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6356#-O6Fuyyz7nRCBGC1ss_L:-O6FwnTn6fkqIecrsWYD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/69a1a7d4221b31f022f34df4e824a0a031ff1c57/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L4)):*
> ```
> 
> //! > test_runner_name
> test_expr_semantics(expect_diagnostics: true)
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 54 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6356#-O6FvCtX0MIvxFUJEZpD:-O6FxPIYBeN73txa40rt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/69a1a7d4221b31f022f34df4e824a0a031ff1c57/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L54)):*
> ```
> { use X::{X, Y, Z}; 
> X + Y
> }
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 118 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6356#-O6FvS48CuXUzrUu8QNm:-O6FxOuB-P4yDI0ZJ8l7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/69a1a7d4221b31f022f34df4e824a0a031ff1c57/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L118)):*
> ```
> 
> //! > expr_code
> A
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6356#-:-O6Fyx8627d84cvs8zrb:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @gilbens-starkware)

**Pull request merged**
