### PR TITLE
TODO

### PR DESCRIPTION
**Pull request by liorgold2**
**Stack**:
- #5742 ⬅
- #5741

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5742)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5742)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 596 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5742#-NziifV13Ajq7uL3S6wb:-NziifV13Ajq7uL3S6wc:bfybbi9) ([raw file](https://github.com/starkware-libs/cairo/blob/622b7ca21dd966f660d2d52a382046e95e1c3cb0/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L596)):*
> ```XML
>         let (ty, popped_ty) = args_as_two_types(args)?;
>         let member_type = validate_tuple_and_fetch_ty(context, &popped_ty)?;
>         // Given the following line, do we still need the type as a generic arg?
> ```

we don't have to - but the function signature itself would be somewhat surprising this way.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 203 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5742#-NzijVGhBpQJiEQxxUjr:-NzijVGhBpQJiEQxxUjs:b-6q2r3t) ([raw file](https://github.com/starkware-libs/cairo/blob/622b7ca21dd966f660d2d52a382046e95e1c3cb0/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L203)):*
> ```XML
>             return Err(SpecializationError::UnsupportedGenericArg);
>         }
>         // Add a require that rhs_range.upper >= 2 (also assumed below).
> ```

is this just for clarity? as the size is at least one - so upper will be at least 2.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 465 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5742#-NzijHoDENZYD2TUJniu:-NzijHoDENZYD2TUJniv:bclq34s) ([raw file](https://github.com/starkware-libs/cairo/blob/622b7ca21dd966f660d2d52a382046e95e1c3cb0/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L465)):*
> ```XML
>             .ok_or(SpecializationError::UnsupportedGenericArg)?;
>         let prime: BigInt = Felt252::prime().to_bigint().unwrap();
>         // The following is not really necessary for this function. Once we support ranges
> ```

still feels somewhat dangerous.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs` line 496 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5742#-NzhwKc0-GNK54I88Cf_:-NzhwKc0-GNK54I88Cfa:b-7sqrgi) ([raw file](https://github.com/starkware-libs/cairo/blob/8d401238781c144b8d0cd98cac236156be2cc1cd/crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs#L496)):*
> ```XML
>     // a generic builtin and not like rc128?
>     // Probably need to add rc96 to CostValidationInfo.
>     // Consider changing rc96 to be priced like rc128 (hard-coded pricing).
> ```

automatic validation is only for steps and basic range-check for the time being.
___
*[`crates/cairo-lang-sierra-type-size/src/lib.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5742#-NzhwANC5wOOvC5ou3OW:-NzhwANC5wOOvC5ou3OX:b-fgv4m9) ([raw file](https://github.com/starkware-libs/cairo/blob/8d401238781c144b8d0cd98cac236156be2cc1cd/crates/cairo-lang-sierra-type-size/src/lib.rs#L102)):*
> ```XML
>             | CoreTypeConcrete::Circuit(CircuitTypeConcrete::MulModGate(_))
>             | CoreTypeConcrete::Circuit(CircuitTypeConcrete::SubModGate(_)) => continue,
>             // TODO: What's the difference between using continue and setting their size to 0?
> ```

not having bad types in the map makes sure it won't be built by mistake.

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5742)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs` line 496 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5742#-NzhwKc0-GNK54I88Cf_:-Nzin71r-F0xSZ2Wdk_H:b-f99vum) ([raw file](https://github.com/starkware-libs/cairo/blob/8d401238781c144b8d0cd98cac236156be2cc1cd/crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs#L496)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

automatic validation is only for steps and basic range-check for the time being.
</blockquote></details>

We're suggesting to price rc96 exactly like rc128 (same price)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5742)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 465 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5742#-NzijHoDENZYD2TUJniu:-Nzio_nlCgPOa7delsWU:bvndsbb) ([raw file](https://github.com/starkware-libs/cairo/blob/622b7ca21dd966f660d2d52a382046e95e1c3cb0/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L465)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

still feels somewhat dangerous.
</blockquote></details>

Let's discuss f2f. Keep it for now.

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5742)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 203 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5742#-NzijVGhBpQJiEQxxUjr:-Nzip-VR3ez9eSX_etLZ:b-z3bwqi) ([raw file](https://github.com/starkware-libs/cairo/blob/622b7ca21dd966f660d2d52a382046e95e1c3cb0/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L203)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is this just for clarity? as the size is at least one - so upper will be at least 2.
</blockquote></details>

No, due to the NonZero change (You can choose `NonZero<[0, 1)>`)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5742)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 203 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5742#-NzijVGhBpQJiEQxxUjr:-NziuT767OquI0CNcINu:b-w0yspi) ([raw file](https://github.com/starkware-libs/cairo/blob/622b7ca21dd966f660d2d52a382046e95e1c3cb0/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L203)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

No, due to the NonZero change (You can choose `NonZero<[0, 1)>`)
</blockquote></details>

got it.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs` line 496 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5742#-NzhwKc0-GNK54I88Cf_:-NziuyJO3gm0d8TnraSc:b45iua9) ([raw file](https://github.com/starkware-libs/cairo/blob/8d401238781c144b8d0cd98cac236156be2cc1cd/crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs#L496)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

We're suggesting to price rc96 exactly like rc128 (same price)
</blockquote></details>

so removing it from the token style pool? and just adding it to the normally counted range check.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5742)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 596 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5742#-NziifV13Ajq7uL3S6wb:-Nzj1QMY88jGeFpUWMn0:bgaby14) ([raw file](https://github.com/starkware-libs/cairo/blob/622b7ca21dd966f660d2d52a382046e95e1c3cb0/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L596)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

we don't have to - but the function signature itself would be somewhat surprising this way.
</blockquote></details>

but Done.

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5742)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 596 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5742#-NziifV13Ajq7uL3S6wb:-Nzj5xwxCvMM6zQ3wMC5:bdyfqwq) ([raw file](https://github.com/starkware-libs/cairo/blob/622b7ca21dd966f660d2d52a382046e95e1c3cb0/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L596)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

but Done.
</blockquote></details>

Yes, I think I agree

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5742)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 596 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5742#-NziifV13Ajq7uL3S6wb:-Nzj64jS8VhfE50Oq1bg:b-clmeo0) ([raw file](https://github.com/starkware-libs/cairo/blob/622b7ca21dd966f660d2d52a382046e95e1c3cb0/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L596)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Yes, I think I agree
</blockquote></details>

This was in reply to the original message :) I'm fine with keeping the additional type for improving clarity.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5742)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 596 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5742#-NziifV13Ajq7uL3S6wb:-NzlqMQL9uvz45IIIyB4:bbtq2pw) ([raw file](https://github.com/starkware-libs/cairo/blob/622b7ca21dd966f660d2d52a382046e95e1c3cb0/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L596)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

This was in reply to the original message :) I'm fine with keeping the additional type for improving clarity.
</blockquote></details>

after i did it i got convinced it is better (was rather clean and consistent with the {span_from_tuple,tuple_from_span} functions.

**Pull request closed without merging**
