### PR TITLE
Let DiagnosticsReporter `ensure` function take only necessary type

### PR DESCRIPTION
**Pull request by wawel37**
related to [#1445](https://github.com/software-mansion/scarb/issues/1445) in scarb.

This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6376)

### CODE REVIEW

**Review by maciektr — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6376)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput and @orizi)

**Review by Draggu — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6376#-:-O6VUZUWCPaG5NQFymJ4:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput and @orizi)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6376#-:-O6aGI3sA0jhQ45weB-3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Review by piotmag769 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6376#-:-O6aGWyy8wY-XY8wI4PJ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Pull request merged**
