### PR TITLE
Infer traits

### PR DESCRIPTION
**Pull request by spapinistarkware**
commit-id:d39a4aa8

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1842)* status: all files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/resolve_path.rs` line 451 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1842#-NMNyih9AntZdMDpWNYt:-NMNyih9AntZdMDpWNYu:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b06fc709a88184bf46565cfe7af2b61338d750d0/crates/cairo-lang-semantic/src/resolve_path.rs#L451)):*
> ```XML
>             }
>             ResolvedConcreteItem::Trait(concrete_trait_id) => {
>                 // TODO(spapini): Currently, generics of the trait function itslef (not the trait)
> ```





_Suggestion:_
```XML
                // TODO(spapini): Currently, generics of the trait function itself (not the trait)
                // are not handled. Use `generic_args` to handle them.
```
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1842#-NMNyZZJ7mPMhF_xVCYR:-NMNyZZJ7mPMhF_xVCYS:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b06fc709a88184bf46565cfe7af2b61338d750d0/crates/cairo-lang-semantic/src/expr/inference.rs#L32)):*
> ```XML
> }
> 
> /// State of inference
> ```





_Suggestion:_
```XML
/// State of inference.
```
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 218 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1842#-NMNyLwm81JNoOrBVpY3:-NMNyLwn8sv4kucz6mWt:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/b06fc709a88184bf46565cfe7af2b61338d750d0/crates/cairo-lang-semantic/src/expr/inference.rs#L218)):*
> ```XML
>     }
> 
>     fn conform_generic_args(
> ```

doc



_Code quote:_
```XML
    fn conform_generic_args(
```
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 289 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1842#-NMNyVQyDdB5OG6m6WrG:-NMNyVQyDdB5OG6m6WrH:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b06fc709a88184bf46565cfe7af2b61338d750d0/crates/cairo-lang-semantic/src/expr/inference.rs#L289)):*
> ```XML
>     }
> 
>     /// Determines if an assignment to `generic_params` cab be chosen s.t. generic_args will be
> ```





_Suggestion:_
```XML
    /// Determines if an assignment to `generic_params` can be chosen s.t. generic_args will be
    /// substituted to expected_generic_args.
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1842)* status: 13 of 15 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/resolve_path.rs` line 451 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1842#-NMNyih9AntZdMDpWNYt:-NMO-KSGDdkJqX0gKFZW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b06fc709a88184bf46565cfe7af2b61338d750d0/crates/cairo-lang-semantic/src/resolve_path.rs#L451)):*
> ```XML
>             }
>             ResolvedConcreteItem::Trait(concrete_trait_id) => {
>                 // TODO(spapini): Currently, generics of the trait function itslef (not the trait)
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1842#-NMNyZZJ7mPMhF_xVCYR:-NMO-H4n6-KQ7QlsYdly:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b06fc709a88184bf46565cfe7af2b61338d750d0/crates/cairo-lang-semantic/src/expr/inference.rs#L32)):*
> ```XML
> }
> 
> /// State of inference
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 218 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1842#-NMNyLwm81JNoOrBVpY3:-NMO-HUS7lfUcEx3qj7T:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b06fc709a88184bf46565cfe7af2b61338d750d0/crates/cairo-lang-semantic/src/expr/inference.rs#L218)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 289 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1842#-NMNyVQyDdB5OG6m6WrG:-NMO-JNsEYv1Olt74bsj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b06fc709a88184bf46565cfe7af2b61338d750d0/crates/cairo-lang-semantic/src/expr/inference.rs#L289)):*
> ```XML
>     }
> 
>     /// Determines if an assignment to `generic_params` cab be chosen s.t. generic_args will be
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1842)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1842#-NMO7-DI2i_qyTIpDeFS:-NMO7-DI2i_qyTIpDeFT:b-ov3eai) (no related file):*
can you add a tests that trait inference now works?

___

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1842)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1842#-:-NMO7j_77tlDKSM9SS3M:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
