### PR TITLE
Added sqrt to uints 8,16,32,64.

### PR DESCRIPTION
**Pull request by amosStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2090)

### CODE REVIEW

**Review by amosStarkware — COMMENTED** [review]
+reviewer:@orizi 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2090#-:-NNqqr8Z2noaMYorwEJ8:bqa6z7g)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2090)* status: all files reviewed, 5 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/cairo-lang-sierra/src/simulation/core.rs` line 568 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2090#-NNqtWqd4VCCOoiTPzrf:-NNqtWqd4VCCOoiTPzrg:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a0c5cb392619f4c68978266d332ec22cb086c6b9/crates/cairo-lang-sierra/src/simulation/core.rs#L568)):*
> ```XML
>             [CoreValue::RangeCheck, CoreValue::Uint8(value)] => {
>                 let root = BigInt::from(*value).sqrt();
>                 Ok((vec![CoreValue::RangeCheck, CoreValue::Uint128(root.to_u128().unwrap())], 0))
> ```





_Suggestion:_
```XML
                Ok((vec![CoreValue::RangeCheck, CoreValue::Uint8(root.to_u8().unwrap())], 0))
```
___
*[`crates/cairo-lang-sierra/src/simulation/core.rs` line 654 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2090#-NNqtZBI9I72gEXKmKv5:-NNqtZBI9I72gEXKmKv6:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a0c5cb392619f4c68978266d332ec22cb086c6b9/crates/cairo-lang-sierra/src/simulation/core.rs#L654)):*
> ```XML
>             [CoreValue::RangeCheck, CoreValue::Uint16(value)] => {
>                 let root = BigInt::from(*value).sqrt();
>                 Ok((vec![CoreValue::RangeCheck, CoreValue::Uint128(root.to_u128().unwrap())], 0))
> ```





_Suggestion:_
```XML
                Ok((vec![CoreValue::RangeCheck, CoreValue::Uint16(root.to_u16().unwrap())], 0))
```
___
*[`crates/cairo-lang-sierra/src/simulation/core.rs` line 740 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2090#-NNqtbKEETZpJGd_fQhs:-NNqtbKEETZpJGd_fQht:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a0c5cb392619f4c68978266d332ec22cb086c6b9/crates/cairo-lang-sierra/src/simulation/core.rs#L740)):*
> ```XML
>             [CoreValue::RangeCheck, CoreValue::Uint32(value)] => {
>                 let root = BigInt::from(*value).sqrt();
>                 Ok((vec![CoreValue::RangeCheck, CoreValue::Uint128(root.to_u128().unwrap())], 0))
> ```





_Suggestion:_
```XML
                Ok((vec![CoreValue::RangeCheck, CoreValue::Uint32(root.to_u32().unwrap())], 0))
```
___
*[`crates/cairo-lang-sierra/src/simulation/core.rs` line 825 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2090#-NNqti914YnXTd52vJ4N:-NNqti914YnXTd52vJ4O:b-l9y2np) ([raw file](https://github.com/starkware-libs/cairo/blob/a0c5cb392619f4c68978266d332ec22cb086c6b9/crates/cairo-lang-sierra/src/simulation/core.rs#L825)):*
> ```XML
>         Uint64Concrete::SquareRoot(_) => match inputs {
>             [CoreValue::RangeCheck, CoreValue::Uint64(value)] => {
>                 let root = BigInt::from(*value).sqrt();
> ```

no need for all the casting here, find out if there's a native normal sqrt impl for uints.



_Code quote:_
```XML
                let root = BigInt::from(*value).sqrt();
```
___
*[`crates/cairo-lang-sierra/src/simulation/core.rs` line 827 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2090#-NNqteG_4FE4THhdDqCt:-NNqteG_4FE4THhdDqCu:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a0c5cb392619f4c68978266d332ec22cb086c6b9/crates/cairo-lang-sierra/src/simulation/core.rs#L827)):*
> ```XML
>                 let root = BigInt::from(*value).sqrt();
>                 Ok((vec![CoreValue::RangeCheck, CoreValue::Uint128(root.to_u128().unwrap())], 0))
>             }
> ```





_Suggestion:_
```XML
                Ok((vec![CoreValue::RangeCheck, CoreValue::Uint64(root.to_u64().unwrap())], 0))
```

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2090)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/simulation/core.rs` line 568 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2090#-NNqtWqd4VCCOoiTPzrf:-NO-XVq5B5cPWJ9epimF:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a0c5cb392619f4c68978266d332ec22cb086c6b9/crates/cairo-lang-sierra/src/simulation/core.rs#L568)):*
> ```XML
>             [CoreValue::RangeCheck, CoreValue::Uint8(value)] => {
>                 let root = BigInt::from(*value).sqrt();
>                 Ok((vec![CoreValue::RangeCheck, CoreValue::Uint128(root.to_u128().unwrap())], 0))
> ```

Done.
___
*[`crates/cairo-lang-sierra/src/simulation/core.rs` line 654 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2090#-NNqtZBI9I72gEXKmKv5:-NO-XYgM8puuV4_pBBrG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a0c5cb392619f4c68978266d332ec22cb086c6b9/crates/cairo-lang-sierra/src/simulation/core.rs#L654)):*
> ```XML
>             [CoreValue::RangeCheck, CoreValue::Uint16(value)] => {
>                 let root = BigInt::from(*value).sqrt();
>                 Ok((vec![CoreValue::RangeCheck, CoreValue::Uint128(root.to_u128().unwrap())], 0))
> ```

Done.
___
*[`crates/cairo-lang-sierra/src/simulation/core.rs` line 740 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2090#-NNqtbKEETZpJGd_fQhs:-NO-X_RV168KrxHpk9Jw:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a0c5cb392619f4c68978266d332ec22cb086c6b9/crates/cairo-lang-sierra/src/simulation/core.rs#L740)):*
> ```XML
>             [CoreValue::RangeCheck, CoreValue::Uint32(value)] => {
>                 let root = BigInt::from(*value).sqrt();
>                 Ok((vec![CoreValue::RangeCheck, CoreValue::Uint128(root.to_u128().unwrap())], 0))
> ```

Done.
___
*[`crates/cairo-lang-sierra/src/simulation/core.rs` line 825 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2090#-NNqti914YnXTd52vJ4N:-NO-_POQ184MPDcVUUro:bz0svab) ([raw file](https://github.com/starkware-libs/cairo/blob/a0c5cb392619f4c68978266d332ec22cb086c6b9/crates/cairo-lang-sierra/src/simulation/core.rs#L825)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no need for all the casting here, find out if there's a native normal sqrt impl for uints.
</blockquote></details>

I don't think there is a native one ( https://users.rust-lang.org/t/integer-square-root/96 ).
I could use this package:
https://crates.io/crates/integer-sqrt
all the casting is a bit excessive, I thought it doesn't matter because this is only for simulation.  
___
*[`crates/cairo-lang-sierra/src/simulation/core.rs` line 827 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2090#-NNqteG_4FE4THhdDqCt:-NO-XdIm9FrxbUPERHtI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a0c5cb392619f4c68978266d332ec22cb086c6b9/crates/cairo-lang-sierra/src/simulation/core.rs#L827)):*
> ```XML
>                 let root = BigInt::from(*value).sqrt();
>                 Ok((vec![CoreValue::RangeCheck, CoreValue::Uint128(root.to_u128().unwrap())], 0))
>             }
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2090#-:-NO-cM1TCifXPMqFw4Qg:bnfp4nl)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @amosStarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2090)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2090#-:-NO46_FA8e0qRQyC82vD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
