### PR TITLE
Add starknet serde.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2109)

### CODE REVIEW

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2109#-:-NO8vPtG5-KsaKgL9nP6:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/test_data/test_contract.cairo` line 29 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2109#-NO8ukEw9xRiqqNJofj7:-NO8ukEw9xRiqqNJofj8:bhxiaqj) ([raw file](https://github.com/starkware-libs/cairo/blob/9476d2f832a63134e7496919aacfce0c31d07985/crates/cairo-lang-starknet/test_data/test_contract.cairo#L29)):*
> ```Cairo
> 
>     #[external]
>     fn call_foo(foo_address: ContractAddress, a: u128) -> u128 {
> ```

This is the contract address, not the foo function address, right?



_Suggestion:_
```Cairo
another_contract_address
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2109)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-starknet/test_data/test_contract.cairo` line 29 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2109#-NO8ukEw9xRiqqNJofj7:-NO8wC3z3U9JWwwZGRte:b-r18wie) ([raw file](https://github.com/starkware-libs/cairo/blob/9476d2f832a63134e7496919aacfce0c31d07985/crates/cairo-lang-starknet/test_data/test_contract.cairo#L29)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

This is the contract address, not the foo function address, right?
</blockquote></details>

done, thanks.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 17 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2109)* status: 9 of 26 files reviewed, all discussions resolved (waiting on @spapinistarkware and @yuvalsw)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 17 files at r2, 15 of 15 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2109)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
