### PR TITLE
Sierra declarations

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
Signed-off-by: Dori Medini <dori@<a href="starkware.co">starkware.co</a>>

---

**Stack**:
- #1189
- #1188
- #1187
- #1186 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1186)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1186)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/sierra/src/extensions/modules/integer.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1186#-NI82LlHB9lRkyAwJ1Xs:-NI82LlHB9lRkyAwJ1Xt:br3r69m) ([raw file](https://github.com/starkware-libs/cairo/blob/240a92d6855c82ae94a568acc6402d4d73707c46/crates/sierra/src/extensions/modules/integer.rs#L153)):*
> ```XML
>                     OutputVarInfo {
>                         ty: ty.clone(),
>                         ref_info: OutputVarReferenceInfo::Deferred(DeferredOutputKind::Generic),
> ```

aren't these new temp?



_Code quote:_
```XML
OutputVarReferenceInfo::Deferred(DeferredOutputKind::Generic)
```
___
*[`crates/sierra/src/extensions/modules/integer.rs` line 247 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1186#-NI82Pn0EC9zrTXH6yko:-NI82Pn0EC9zrTXH6ykp:b-7ropln) ([raw file](https://github.com/starkware-libs/cairo/blob/240a92d6855c82ae94a568acc6402d4d73707c46/crates/sierra/src/extensions/modules/integer.rs#L247)):*
> ```XML
>                         OutputVarInfo {
>                             ty: ty.clone(),
>                             ref_info: OutputVarReferenceInfo::Deferred(DeferredOutputKind::Generic),
> ```

ditto



_Code quote:_
```XML
                        OutputVarInfo {
                            ty: ty.clone(),
                            ref_info: OutputVarReferenceInfo::Deferred(DeferredOutputKind::Generic),
                        },
                        OutputVarInfo {
                            ty,
                            ref_info: OutputVarReferenceInfo::Deferred(DeferredOutputKind::Generic),
                        },
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1186)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/sierra/src/extensions/modules/integer.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1186#-NI82LlHB9lRkyAwJ1Xs:-NI82j0HEFAyFxRtxNag:bbgp5rt) ([raw file](https://github.com/starkware-libs/cairo/blob/240a92d6855c82ae94a568acc6402d4d73707c46/crates/sierra/src/extensions/modules/integer.rs#L153)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

aren't these new temp?
</blockquote></details>

I see other AP-based return-values use this; particularly the Div, Mul, Add, Sub operations above.
In sierra_to_casm I return `ReferenceExpression::from_cell(CellExpression::Deref(ap_cell_ref(-X)))`, just like the other operators.
Doesn't this mean I should use `DeferredOutputKind::Generic`?
___
*[`crates/sierra/src/extensions/modules/integer.rs` line 247 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1186#-NI82Pn0EC9zrTXH6yko:-NI83OR4-ZzXYtpKjwi-:b-dpwbz8) ([raw file](https://github.com/starkware-libs/cairo/blob/240a92d6855c82ae94a568acc6402d4d73707c46/crates/sierra/src/extensions/modules/integer.rs#L247)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto on my reply

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1186)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/sierra/src/extensions/modules/integer.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1186#-NI82LlHB9lRkyAwJ1Xs:-NI85Op7DujbMmJbJPyO:b-mhxcl8) ([raw file](https://github.com/starkware-libs/cairo/blob/240a92d6855c82ae94a568acc6402d4d73707c46/crates/sierra/src/extensions/modules/integer.rs#L153)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I see other AP-based return-values use this; particularly the Div, Mul, Add, Sub operations above.
In sierra_to_casm I return `ReferenceExpression::from_cell(CellExpression::Deref(ap_cell_ref(-X)))`, just like the other operators.
Doesn't this mean I should use `DeferredOutputKind::Generic`?
</blockquote></details>

no - it is a variable on stack - the others are the mistake.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1186)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1186)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1186)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Comment by dorimedini-starkware** [comment]
✓ Commit merged in pull request [#1187](https://github.com/starkware-libs/cairo2/pull/1187)

**Pull request merged**
