### PR TITLE
Formatter: replace break line points with spaces (Formatter temporary…

### PR DESCRIPTION
**Pull request by gilbens-starkware**
… broken)

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1584)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1584)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/formatter/src/formatter.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1584#-NKqztxS9MCHVdLUMFdN:-NKqztxS9MCHVdLUMFdO:b-3qnc53) ([raw file](https://github.com/starkware-libs/cairo/blob/60f288601d32003f0bf88c8cf1447e3bf7273412/crates/formatter/src/formatter.rs#L54)):*
> ```XML
>     /// the line is too long. A non-optional breakpoint is always broken.
>     pub is_optional: bool,
>     /// Indicates to put a space instead of the break line point if it were not broken.
> ```

suggestion



_Suggestion:_
```XML
    /// Indicates whether to put a space in the place of the break line point if it was not broken.
    pub space_if_not_broken: bool,
```
___
*[`crates/formatter/src/formatter.rs` line 681 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1584#-NKr0mr--SLi1-AaFupf:-NKr0mr--SLi1-AaFupg:b-a63qkr) ([raw file](https://github.com/starkware-libs/cairo/blob/60f288601d32003f0bf88c8cf1447e3bf7273412/crates/formatter/src/formatter.rs#L681)):*
> ```XML
>         if let Some(properties) = properties {
>             self.line_state.line_buffer.push_break_line_point(properties);
>             self.line_state.no_space_after = true;
> ```

is this the force-no-space-after?
If it is, a bit unrelated, but can you rename it to add the force? Even in a separate pr if you prefer

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1584)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/formatter/src/node_properties.rs` line 212 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1584#-NKr3c16-gSpIyGkwU0n:-NKr3c16-gSpIyGkwU0o:bxh3cnm) ([raw file](https://github.com/starkware-libs/cairo/blob/60f288601d32003f0bf88c8cf1447e3bf7273412/crates/formatter/src/node_properties.rs#L212)):*
> ```XML
>                 }),
>             },
>             SyntaxKind::TerminalComma if parent_kind(db, self) != Some(SyntaxKind::MatchArms) => {
> ```

is this to prevent spaces in the end of the line when there is a linebreak right after the breakpoint that was ignored? I think it should always be the case (that we don't add spaces right before the line break) and we should not handle specific cases.
But we can handle this in a separate PR.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1584)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/formatter/src/formatter.rs` line 681 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1584#-NKr0mr--SLi1-AaFupf:-NKrZs-8E4nYJOgxhWfA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/60f288601d32003f0bf88c8cf1447e3bf7273412/crates/formatter/src/formatter.rs#L681)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

is this the force-no-space-after?
If it is, a bit unrelated, but can you rename it to add the force? Even in a separate pr if you prefer
</blockquote></details>

Done.
___
*[`crates/formatter/src/node_properties.rs` line 212 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1584#-NKr3c16-gSpIyGkwU0n:-NKr_Q9ECAjeqskDXYT1:b2elfp4) ([raw file](https://github.com/starkware-libs/cairo/blob/60f288601d32003f0bf88c8cf1447e3bf7273412/crates/formatter/src/node_properties.rs#L212)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

is this to prevent spaces in the end of the line when there is a linebreak right after the breakpoint that was ignored? I think it should always be the case (that we don't add spaces right before the line break) and we should not handle specific cases.
But we can handle this in a separate PR.
</blockquote></details>

It is because matcharms are currently line finalizing (force_line_break) and have no break point after it. I want to remove the force_line_break and use only break_line_points as discussed.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1584#-:-NKs4BYf26E5nTJ_uxpu:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/formatter/src/node_properties.rs` line 212 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1584#-NKr3c16-gSpIyGkwU0n:-NKs46EH9DeKO9Gjyydq:bnyytg) ([raw file](https://github.com/starkware-libs/cairo/blob/60f288601d32003f0bf88c8cf1447e3bf7273412/crates/formatter/src/node_properties.rs#L212)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

It is because matcharms are currently line finalizing (force_line_break) and have no break point after it. I want to remove the force_line_break and use only break_line_points as discussed.
</blockquote></details>

Please add a todo as discussed

**Review by yuvalsw — APPROVED** [review]
> Reviewed 3 of 4 files at r3, 18 of 18 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1584)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1584#-:-NMUWng07G0M-0vZNOvJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 6 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1584)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1584)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1584)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1584)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
