### PR TITLE
Added test for starknet plugin expansion.

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1215)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 4 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1215)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/starknet/src/plugin_test.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1215#-NISU8UECe4Ns8O-oGxy:-NISU8UECe4Ns8O-oGxz:b-ivoyou) ([raw file](https://github.com/starkware-libs/cairo/blob/6b25bb1ae22e8f44e5e16efb0eb5fbae365cb927/crates/starknet/src/plugin_test.rs#L16)):*
> ```XML
>     let file_id = create_virtual_file(db, "dummy_file.cairo", cairo_code);
>     let (syntax_file, diagnostics) = get_syntax_file_and_diagnostics(db, file_id, cairo_code);
>     assert_eq!(diagnostics.format(db), "");
> ```

Can we use this test to test diagnostics as well?



_Code quote:_
```XML
assert_eq!(diagnostics.format(db), "");
```

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1215#-:-NISV-BTByniiJ4uyR6z:bnfp4nl)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1215)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/starknet/src/plugin_test.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1215#-NISU8UECe4Ns8O-oGxy:-NIWHgd6AqQ0okEnPllv:b-n97a8e) ([raw file](https://github.com/starkware-libs/cairo/blob/6b25bb1ae22e8f44e5e16efb0eb5fbae365cb927/crates/starknet/src/plugin_test.rs#L16)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Can we use this test to test diagnostics as well?
</blockquote></details>

Yes, but we currently don't have any. We can add it once we have.

**Review by yuvalsw — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1215)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1215)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
