### PR TITLE
changed generated function key to concrete function

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6342)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6342)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @TomerStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6342#-O5sBUnp7R4S9x7VNBbX:-O5sBUnp7R4S9x7VNBbY:bvso5h2) (no related file):*
why are there changes in tests? - unless the PR description is wrong.

___

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6342)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6342#-O5sBUnp7R4S9x7VNBbX:-O5sKr8c-sErf0WAgqi2:boonyj) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why are there changes in tests? - unless the PR description is wrong.
</blockquote></details>

now the body function of FunctionLongId of call function, returns the correct key instead of none

___

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6342)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/closure` line 71 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6342#-O5sO0JL2q_02W3THNIY:-O5sO0JM0Vv_nlTKNE8k:b43czo5) ([raw file](https://github.com/starkware-libs/cairo/blob/e7689719a59fd70b8f014741925dcc86d2070dbf/crates/cairo-lang-lowering/src/borrow_check/test_data/closure#L71)):*
> ```
> error: Unsupported feature.
>  --> lib.cairo:9:5
>     || {
> ```

how is this related?



_Code quote:_
```
 --> lib.cairo:9:5
    || {
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6342)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/test_data/closure` line 38 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6342#-O5sSJ-dDO9ueLU0M1GM:-O5viNTF2cqcDBNgAZ9q:b-lpzit8) ([raw file](https://github.com/starkware-libs/cairo/blob/55c6313a89f7bb40b2c0fe79f31bddfd63cd48b4/crates/cairo-lang-lowering/src/lower/test_data/closure#L38)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

here as well.
</blockquote></details>

This is the result of returning the correct function body id instead of None when the function if generated.
___
*[`crates/cairo-lang-lowering/src/panic/mod.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6342#-O5sSM1p9RXR9DwpibAn:-O5vikEa4KmADOQQSgqZ:b-5sqqo3) ([raw file](https://github.com/starkware-libs/cairo/blob/55c6313a89f7bb40b2c0fe79f31bddfd63cd48b4/crates/cairo-lang-lowering/src/panic/mod.rs#L51)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

and here.
</blockquote></details>

Before the fix, the signature here was not fully concrete, @ilyalesokhin-starkware suggested adding the assert for easier debugging in the future
___
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/closure` line 71 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6342#-O5sO0JL2q_02W3THNIY:-O5viBVn8OtzpuRSQ1rR:bfylb9h) ([raw file](https://github.com/starkware-libs/cairo/blob/173806e1c7e50709ac074977d25d7afbfe2d2019/crates/cairo-lang-lowering/src/borrow_check/test_data/closure#L71)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

how is this related?
</blockquote></details>

This was due to accidental removal of unsupported error.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r1, 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6342#-:-O5vkhM07c5K2QVtcbJ8:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 7 files at r1, 1 of 2 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6342#-:-O5vmxkUAWPFXylKmehn:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
