### PR TITLE
LS: Skip warnings in deps

### LINKED ISSUE #6310: LS: Ignore warning diagnostics from deps
Currently we are showing warning diagnostics from dependencies, they should be ignored

Scarb has added this behavior recently: https://github.com/starkware-libs/cairo/pull/6279

### PR DESCRIPTION
**Pull request by Draggu**
fix #6310

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6358)

### CODE REVIEW

**Review by piotmag769 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6358)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 376 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6358#-O61ftHF5Xl1fmdPWeTP:-O61ftHF5Xl1fmdPWeTQ:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/15243915ae2fc0ec7db50f307604083caa118a11/crates/cairo-lang-language-server/src/lib.rs#L376)):*
> ```XML
>     #[tracing::instrument(level = "debug", skip_all)]
>     async fn refresh_diagnostics(&self) -> LSPResult<()> {
>         fn is_virtual_file(db: &AnalysisDatabase, file: FileId) -> bool {
> ```





_Suggestion:_
```XML
is_compiler_generated_file
```
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 377 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6358#-O61d4wKBs_IdVD0RHIy:-O61d4wKBs_IdVD0RHIz:b-m09il0) ([raw file](https://github.com/starkware-libs/cairo/blob/15243915ae2fc0ec7db50f307604083caa118a11/crates/cairo-lang-language-server/src/lib.rs#L377)):*
> ```XML
>     async fn refresh_diagnostics(&self) -> LSPResult<()> {
>         fn is_virtual_file(db: &AnalysisDatabase, file: FileId) -> bool {
>             !matches!(
> ```

Better to do exhaustive match here I think (without `_` pattern) so compiler complains when a new variant is added
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 412 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6358#-O61fayr1qMTmpVJ9yIm:-O61fayr1qMTmpVJ9yIn:b-8nqvzi) ([raw file](https://github.com/starkware-libs/cairo/blob/15243915ae2fc0ec7db50f307604083caa118a11/crates/cairo-lang-language-server/src/lib.rs#L412)):*
> ```XML
>                     &file,
>                     &file_modules_ids,
>                     is_virtual_file(&db, file), // Show warnings for open files even if this is dependency.
> ```

You can also add sth like this if u want:
```
 We don't check if the open file belongs to a dependency - we want to show warnings for open files from dependencies.
```



_Suggestion:_
```XML
// Ignore warnings for compiler generated files.
```
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 424 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6358#-O61eouT7lW6x7NQCx0G:-O61eouT7lW6x7NQCx0H:b6y7bmg) ([raw file](https://github.com/starkware-libs/cairo/blob/15243915ae2fc0ec7db50f307604083caa118a11/crates/cairo-lang-language-server/src/lib.rs#L424)):*
> ```XML
>         let (rest_of_files, skip_warnings_files) = async {
>             let mut rest_of_files: HashSet<FileId> = HashSet::default();
>             let mut skip_warnings_files: HashSet<FileId> = HashSet::default();
> ```

This way this logic is immediately obvious
```rs
let skip_warnings = files_from_dependencies.contains(&file);
```



_Suggestion:_
```XML
files_from_dependencies
```
___
*[`crates/cairo-lang-language-server/src/project/scarb.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6358#-O61droe9aqNMdyZNDkk:-O61droe9aqNMdyZNDkl:bffhdkd) ([raw file](https://github.com/starkware-libs/cairo/blob/15243915ae2fc0ec7db50f307604083caa118a11/crates/cairo-lang-language-server/src/project/scarb.rs#L34)):*
> ```XML
>     let mut crates_grouped_by_group_id = HashMap::new();
> 
>     *deps = metadata
> ```

This will only work when we support multiroot workspaces and separate LS instance will be spawned for each scarb workspace - otherwise you will override the dependencies when a file from a different package is opened. Cc @Arcticae @mkaput to double check if I'm right

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6358)* status: 1 of 4 files reviewed, 7 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 376 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6358#-O61ftHF5Xl1fmdPWeTP:-O61pUa_4IfaFxVDXAg4:bj5erph) ([raw file](https://github.com/starkware-libs/cairo/blob/15243915ae2fc0ec7db50f307604083caa118a11/crates/cairo-lang-language-server/src/lib.rs#L376)):*
> ```XML
>     #[tracing::instrument(level = "debug", skip_all)]
>     async fn refresh_diagnostics(&self) -> LSPResult<()> {
>         fn is_virtual_file(db: &AnalysisDatabase, file: FileId) -> bool {
> ```

disagree given the broader context, see my comment: https://reviewable.io/reviews/starkware-libs/cairo/6358#-O61qK6C1upZzvByW8x4
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 377 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6358#-O61d4wKBs_IdVD0RHIy:-O61pXYB17C5ll74gZwN:bl9jxpf) ([raw file](https://github.com/starkware-libs/cairo/blob/15243915ae2fc0ec7db50f307604083caa118a11/crates/cairo-lang-language-server/src/lib.rs#L377)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Better to do exhaustive match here I think (without `_` pattern) so compiler complains when a new variant is added
</blockquote></details>

I think we should match for `FileLongId::External(PluginGeneratedFileId(...) as salsa::InternId)` here. `FileLongId::Virtual` are completely fine for our purposes and I don't think we should hide diags for them

cc @orizi how could this be expressed efficiently? I'd definitely like this check to be present in compiler APIs instead of being done on LS side
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 375 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6358#-O61qK6C1upZzvByW8x4:-O61qK6C1upZzvByW8x5:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/675ec0f59e2c92f3f1fae5ce1f8aeedabf7a9959/crates/cairo-lang-language-server/src/lib.rs#L375)):*
> ```XML
>     #[tracing::instrument(level = "debug", skip_all)]
>     async fn refresh_diagnostics(&self) -> LSPResult<()> {
>         fn is_virtual_file(db: &AnalysisDatabase, file: FileId) -> bool {
> ```





_Suggestion:_
```XML
show_warnings_for_file
```
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 411 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6358#-O61pyIhElwHSEk7RZcV:-O61pyIhElwHSEk7RZcW:b-hoz82t) ([raw file](https://github.com/starkware-libs/cairo/blob/675ec0f59e2c92f3f1fae5ce1f8aeedabf7a9959/crates/cairo-lang-language-server/src/lib.rs#L411)):*
> ```XML
>                     &file,
>                     &file_modules_ids,
>                     is_virtual_file(&db, file), /* Show warnings for open files even if this is
> ```

what is this comment man, plz use `//` like everywhere :laughing:

**Review by Draggu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6358)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @Arcticae, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 375 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6358#-O61qK6C1upZzvByW8x4:-O61u9t03pqtA4m2f8dX:bmvesrf) ([raw file](https://github.com/starkware-libs/cairo/blob/675ec0f59e2c92f3f1fae5ce1f8aeedabf7a9959/crates/cairo-lang-language-server/src/lib.rs#L375)):*
> ```XML
>     #[tracing::instrument(level = "debug", skip_all)]
>     async fn refresh_diagnostics(&self) -> LSPResult<()> {
>         fn is_virtual_file(db: &AnalysisDatabase, file: FileId) -> bool {
> ```

This is partially true, later is check if this file is from dependency crate, and this is checking only for virtual file. I don't think that naming it `show_warnings_for_file` is good here.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 411 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6358#-O61pyIhElwHSEk7RZcV:-O61tx_rEnOt-dIfLESj:bouc3qr) ([raw file](https://github.com/starkware-libs/cairo/blob/675ec0f59e2c92f3f1fae5ce1f8aeedabf7a9959/crates/cairo-lang-language-server/src/lib.rs#L411)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

what is this comment man, plz use `//` like everywhere :laughing:
</blockquote></details>

This was done by formatter XD, missed it.

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6358)* status: all files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 376 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6358#-O61ftHF5Xl1fmdPWeTP:-O61tquzDwKlpThSVSl8:b-aanflz) ([raw file](https://github.com/starkware-libs/cairo/blob/15243915ae2fc0ec7db50f307604083caa118a11/crates/cairo-lang-language-server/src/lib.rs#L376)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

disagree given the broader context, see my comment: https://reviewable.io/reviews/starkware-libs/cairo/6358#-O61qK6C1upZzvByW8x4
</blockquote></details>

Agree, ur name is better

**Review by mkaput — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6358)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6358)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae and @orizi)

___
*[`crates/cairo-lang-language-server/src/project/scarb.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6358#-O61droe9aqNMdyZNDkk:-O61uefWCqz3ZAEXf7hy:b-cy2gu0) ([raw file](https://github.com/starkware-libs/cairo/blob/15243915ae2fc0ec7db50f307604083caa118a11/crates/cairo-lang-language-server/src/project/scarb.rs#L34)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

This will only work when we support multiroot workspaces and separate LS instance will be spawned for each scarb workspace - otherwise you will override the dependencies when a file from a different package is opened. Cc @Arcticae @mkaput to double check if I'm right
</blockquote></details>

Yeah, I think we should invert this logic. Let's discuss this offline.

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6358)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, and @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 375 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6358#-O61qK6C1upZzvByW8x4:-O61vzlc2OPGfsFzSOdu:b-ejsg11) ([raw file](https://github.com/starkware-libs/cairo/blob/675ec0f59e2c92f3f1fae5ce1f8aeedabf7a9959/crates/cairo-lang-language-server/src/lib.rs#L375)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

This is partially true, later is check if this file is from dependency crate, and this is checking only for virtual file. I don't think that naming it `show_warnings_for_file` is good here.
</blockquote></details>

we're checking if file is generated precisely because we want to identify if we want to show warnings for it. this way we are explicitly saying our intention, which is esp. useful because you're passing this as unnamed argument

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6358)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, and @orizi)

___
*[`crates/cairo-lang-language-server/src/state.rs` line 23 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6358#-O61wRzc0ESXTt6KjU41:-O61wRzd5LggqZIFh9ad:b9kxzmz) ([raw file](https://github.com/starkware-libs/cairo/blob/44c0b23f10f5a5d6f32a3ff6a8a961e12421aaed/crates/cairo-lang-language-server/src/state.rs#L23)):*
> ```XML
>     pub config: Owned<Config>,
>     pub client_capabilities: Owned<ClientCapabilities>,
>     pub dependencies: Owned<Dependencies>,
> ```

why not keep this in AnalysisDatabase in custom query group?

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6358)* status: all files reviewed, 5 unresolved discussions (waiting on @Arcticae and @Draggu)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 387 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6358#-O6FeWp43wYCV9Hfc6FQ:-O6FeWp43wYCV9Hfc6FR:b-3xgrnl) ([raw file](https://github.com/starkware-libs/cairo/blob/44c0b23f10f5a5d6f32a3ff6a8a961e12421aaed/crates/cairo-lang-language-server/src/lib.rs#L387)):*
> ```XML
>         // Refresh open files modules first for better UX
>         async {
>             let db = self.db_snapshot().await;
> ```

do note this lock locks across all files handling.

is it what you actually want?



_Code quote:_
```XML
            let db = self.db_snapshot().await;
```

**Comment by Draggu** [comment]
Need to be redone after #6469

**Pull request closed without merging**
