### PR TITLE
Support moving `bool_not_impl` statements.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3597)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3597)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/reorder_statements.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3597#-NZZzJjk6CSOKujYoLwp:-NZZzJjk6CSOKujYoLwq:bk0amrd) ([raw file](https://github.com/starkware-libs/cairo/blob/bec329691f9ca5c0ba2f982e8faf0ec6a8c28c1a/crates/cairo-lang-lowering/src/optimizations/reorder_statements.rs#L34)):*
> ```XML
>         let ctx = ReorderStatementsContext {
>             lowered: &*lowered,
>             moveable_functions: UnorderedHashSet::from_iter(std::iter::once(bool_not_func_id)),
> ```

[bool_not_func_id].into_iter().collect()

**Comment by ilyalesokhin-starkware** [comment]
Actually, this does not work :(

**Comment by ilyalesokhin-starkware** [comment]
I need to figure out how to update the demand for the inputs of the statement.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3597)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/reorder_statements.rs` line 141 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3597#-NZ_HaJT1ubXTC5NQXU-:-NZ_HaJT1ubXTC5NQXU0:br742kg) ([raw file](https://github.com/starkware-libs/cairo/blob/0e5cb0aa22a53eff7bfc282167e309a75ccf2f8e/crates/cairo-lang-lowering/src/optimizations/reorder_statements.rs#L141)):*
> ```XML
>         }
> 
>         self.statement_to_move.push((statement_location, optional_target_block));
> ```

will this remove a !!a?
if so - add a test.



_Code quote:_
```XML
        let optional_target_block = info.next_use.swap_remove(&var_to_move);
        if let Some(target_block) = optional_target_block {
            // If the statement is not removed add demand for its inputs.
            for var_usage in stmt.inputs() {
                match info.next_use.entry(var_usage.var_id) {
                    indexmap::map::Entry::Occupied(mut e) => {
                        // Since we don't know where e.get() and `target_locaton` converge
                        // we use `statement_location` as a conservative estimate.
                        &e.insert(statement_location)
                    }
                    indexmap::map::Entry::Vacant(e) => e.insert(target_block),
                };
            }
        }

        self.statement_to_move.push((statement_location, optional_target_block));
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3597)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/reorder_statements.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3597#-NZZzJjk6CSOKujYoLwp:-NZ_axxjD-QyB4hYRJD9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bec329691f9ca5c0ba2f982e8faf0ec6a8c28c1a/crates/cairo-lang-lowering/src/optimizations/reorder_statements.rs#L34)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

[bool_not_func_id].into_iter().collect()
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/optimizations/reorder_statements.rs` line 141 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3597#-NZ_HaJT1ubXTC5NQXU-:-NZ_ayP_761nc35_i4Hp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0e5cb0aa22a53eff7bfc282167e309a75ccf2f8e/crates/cairo-lang-lowering/src/optimizations/reorder_statements.rs#L141)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

will this remove a !!a?
if so - add a test.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3597)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/reorder_statements.rs` line 136 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3597#-NZ_by0yE6ul6paSEPb5:-NZ_by0yE6ul6paSEPb6:b-3wzbt2) ([raw file](https://github.com/starkware-libs/cairo/blob/4b177c12973b02bb54930e66b6ec60c26007f27c/crates/cairo-lang-lowering/src/optimizations/reorder_statements.rs#L136)):*
> ```XML
>                         &e.insert(statement_location)
>                     }
>                     indexmap::map::Entry::Vacant(e) => e.insert(target_location),
> ```

is there a way to return a unit here without adding `{... ;}`?



_Code quote:_
```XML
 indexmap::map::Entry::Vacant(e) => e.insert(target_location),
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3597#-:-NZ_iocv1UCl3F9GMXwA:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/reorder_statements.rs` line 136 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3597#-NZ_by0yE6ul6paSEPb5:-NZ_iNe2C30Kgo2HQSq8:b-qxm5bc) ([raw file](https://github.com/starkware-libs/cairo/blob/4b177c12973b02bb54930e66b6ec60c26007f27c/crates/cairo-lang-lowering/src/optimizations/reorder_statements.rs#L136)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

is there a way to return a unit here without adding `{... ;}`?
</blockquote></details>

i don't think so.

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3597)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3597)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
