### PR TITLE
Orizi/merge sierra v1.1.0 into main

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3330)

### CODE REVIEW

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 11 of 49 files at r2, 5 of 28 files at r3, 9 of 15 files at r4, 19 of 53 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3330)* status: 44 of 89 files reviewed, all discussions resolved

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 49 files at r2, 1 of 15 files at r4, 9 of 53 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3330)* status: 55 of 89 files reviewed, all discussions resolved

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 49 files at r2, 2 of 28 files at r3, 1 of 15 files at r4, 1 of 3 files at r5, 1 of 1 files at r6, 21 of 53 files at r7, 15 of 15 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3330#-:-NXcpNPIDs7A309qFhAx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 12 of 12 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3330)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 12 of 12 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3330)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
