### PR TITLE
Renamed infer_all->rewrite_all

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5419)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5419)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 805 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5419#-NvRrl5xBfHrSA_RkRr1:-NvRrl5yAtJOYY__6fUD:b5k2c83) ([raw file](https://github.com/starkware-libs/cairo/blob/35542b4472f69bb7f42e9aba464746c881c8de93/crates/cairo-lang-semantic/src/expr/compute.rs#L805)):*
> ```XML
> 
>     // Apply inference.
>     rewrite_all(ctx).ok();
> ```

Maybe apply_inference like the comment?



_Suggestion:_
```XML
apply_inference
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 805 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5419#-NvRrl5xBfHrSA_RkRr1:-NvRrutX7X_RsTKVXtjN:bci13lz) ([raw file](https://github.com/starkware-libs/cairo/blob/35542b4472f69bb7f42e9aba464746c881c8de93/crates/cairo-lang-semantic/src/expr/compute.rs#L805)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Maybe apply_inference like the comment?
</blockquote></details>

or

rewrite_inferred_types?

**Comment by yuvalsw** [comment]
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 805 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5419#-NvRrl5xBfHrSA_RkRr1:-NvSBfKF4d0jZLlKX5Vm:b-ucij96) ([raw file](https://github.com/starkware-libs/cairo/blob/35542b4472f69bb7f42e9aba464746c881c8de93/crates/cairo-lang-semantic/src/expr/compute.rs#L805)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

or

rewrite_inferred_types?
</blockquote></details>

`rewrite` is used everywhere, and what this function does is exactly to call rewrite on everything. I am for removing the comment "apply inference".
This argument is for the sake of consistency. I agree apply_inference, or maybe even rewrite_inferred_types (a bit longer) may be a better name, but only if we change `rewrite` to it everywhere. (the current rewrite/reduce is not clear without diving into the context or knowing it in advance).

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 805 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5419#-NvRrl5xBfHrSA_RkRr1:-NvSG4eg3hq-jSfvGYWM:b-owgui6) ([raw file](https://github.com/starkware-libs/cairo/blob/35542b4472f69bb7f42e9aba464746c881c8de93/crates/cairo-lang-semantic/src/expr/compute.rs#L805)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

`rewrite` is used everywhere, and what this function does is exactly to call rewrite on everything. I am for removing the comment "apply inference".
This argument is for the sake of consistency. I agree apply_inference, or maybe even rewrite_inferred_types (a bit longer) may be a better name, but only if we change `rewrite` to it everywhere. (the current rewrite/reduce is not clear without diving into the context or knowing it in advance).
</blockquote></details>

rewrite has a self-argument.
so typically it:
inference.rewrite(...)


Here it is not clear what rewrite is being applied without looking at the implementation.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5419)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 805 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5419#-NvRrl5xBfHrSA_RkRr1:-NvSQvUn7XbrpCsig1Ou:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/35542b4472f69bb7f42e9aba464746c881c8de93/crates/cairo-lang-semantic/src/expr/compute.rs#L805)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

rewrite has a self-argument.
so typically it:
inference.rewrite(...)


Here it is not clear what rewrite is being applied without looking at the implementation.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5419#-:-NvSVH3V28IXdYYuRDGs:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5419)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 805 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5419#-NvRrl5xBfHrSA_RkRr1:-NvSWQUC7Y7DHlFi7TaS:b-fxdbxx) ([raw file](https://github.com/starkware-libs/cairo/blob/35542b4472f69bb7f42e9aba464746c881c8de93/crates/cairo-lang-semantic/src/expr/compute.rs#L805)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Done.
</blockquote></details>

actually it rewrites impls as well

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 805 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5419#-NvRrl5xBfHrSA_RkRr1:-NvSX-9T8FdHQuntnqq0:b-bundul) ([raw file](https://github.com/starkware-libs/cairo/blob/35542b4472f69bb7f42e9aba464746c881c8de93/crates/cairo-lang-semantic/src/expr/compute.rs#L805)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

actually it rewrites impls as well
</blockquote></details>

I guess 
rewrite_all
sorry for indecisiveness

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5419#-:-NvSbS3n8-l-Xy-rLNj8:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5419)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 805 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5419#-NvRrl5xBfHrSA_RkRr1:-NvVGRvA8ONa3tONxE7Y:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/35542b4472f69bb7f42e9aba464746c881c8de93/crates/cairo-lang-semantic/src/expr/compute.rs#L805)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I guess 
rewrite_all
sorry for indecisiveness
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5419#-:-NvVSC_zB1tYGnhF9I3D:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
