### PR TITLE
Refactored and added verification for less than guarantee.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #5734 ⬅
- #5736

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5734)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs` line 526 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5734#-Nzg-_rG5KEu4FbR3qtZ:-Nzg-_rG5KEu4FbR3qt_:b-mxyh02) ([raw file](https://github.com/starkware-libs/cairo/blob/4a3f8a0d235f6381bb6eaa54298324c41c2583ae/crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs#L526)):*
> ```XML
>     let mut casm_builder = CasmBuilder::default();
>     let small_num_limb_0 = casm_builder.add_var(guarantee[0].clone());
>     let large_num_limb_0 = casm_builder.add_var(guarantee[limb_count].clone());
> ```

Don't you need to compare the most significant limb first?



_Code quote:_
```XML
    let small_num_limb_0 = casm_builder.add_var(guarantee[0].clone());
    let large_num_limb_0 = casm_builder.add_var(guarantee[limb_count].clone());
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra/src/extensions/modules/circuit.rs` line 1144 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5734#-Nzg6O0XAQUv8Js9SBoo:-Nzg6O0Y6ZiZwbj9q6cM:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/4a3f8a0d235f6381bb6eaa54298324c41c2583ae/crates/cairo-lang-sierra/src/extensions/modules/circuit.rs#L1144)):*
> ```XML
>         require(limb_count > 0).ok_or(SpecializationError::UnsupportedGenericArg)?;
>         let in_guarantee_ty = u96_limbs_less_than_guarantee_ty(context, limb_count)?;
>         let lt_guarantee_ty = context.get_concrete_type(U96Guarantee::id(), &[])?;
> ```





_Suggestion:_
```XML
u96_lt_guarantee_ty
```

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/circuit.cairo` line 261 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5734#-Nzg6bqv8oDqPNHxFZX5:-Nzg6bqv8oDqPNHxFZX6:bj2juu6) ([raw file](https://github.com/starkware-libs/cairo/blob/4a3f8a0d235f6381bb6eaa54298324c41c2583ae/corelib/src/circuit.cairo#L261)):*
> ```Cairo
>     Next: NextGuarantee,
>     First: U96Guarantee,
> }
> ```

Is it used?



_Code quote:_
```Cairo
enum GuaranteeVerificationOptions<NextGuarantee> {
    Next: NextGuarantee,
    First: U96Guarantee,
}
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 6 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5734)* status: 6 of 9 files reviewed, 3 unresolved discussions (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5734)* status: 6 of 9 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/circuit.cairo` line 261 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5734#-Nzg6bqv8oDqPNHxFZX5:-NzgJ0rlDdW3eihLnrB7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4a3f8a0d235f6381bb6eaa54298324c41c2583ae/corelib/src/circuit.cairo#L261)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Is it used?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/circuit.rs` line 1144 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5734#-Nzg6O0XAQUv8Js9SBoo:-NzgJ8v2AM5JsQ_8hSSd:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4a3f8a0d235f6381bb6eaa54298324c41c2583ae/crates/cairo-lang-sierra/src/extensions/modules/circuit.rs#L1144)):*
> ```XML
>         require(limb_count > 0).ok_or(SpecializationError::UnsupportedGenericArg)?;
>         let in_guarantee_ty = u96_limbs_less_than_guarantee_ty(context, limb_count)?;
>         let lt_guarantee_ty = context.get_concrete_type(U96Guarantee::id(), &[])?;
> ```

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs` line 526 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5734#-Nzg-_rG5KEu4FbR3qtZ:-NzgJBD35rRJ410MXLu9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4a3f8a0d235f6381bb6eaa54298324c41c2583ae/crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs#L526)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Don't you need to compare the most significant limb first?
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/circuit.cairo` line 288 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5734#-NzvnOQ52Ir_P1JqY1jB:-NzvnOQ52Ir_P1JqY1jC:b-7154uz) ([raw file](https://github.com/starkware-libs/cairo/blob/033d86000c4e528c9717f9f8b3f13bd9db07aae0/corelib/src/circuit.cairo#L288)):*
> ```Cairo
>         match multi_limb::u96_limbs_less_than_guarantee_verify(self) {
>             Result::Ok(next) => next.into_u96_guarantee(),
>             Result::Err(guarantee) => guarantee,
> ```

I don't think this is an error.

maybe don't use result.



_Code quote:_
```Cairo
  Result::Err(guarantee)
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 9 files at r1, 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5734)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/circuit.cairo` line 265 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5734#-NzvmcwM30o_H-u8uDzJ:-NzvmcwM30o_H-u8uDzK:b6gqu4g) ([raw file](https://github.com/starkware-libs/cairo/blob/033d86000c4e528c9717f9f8b3f13bd9db07aae0/corelib/src/circuit.cairo#L265)):*
> ```Cairo
> 
> /// Helper trait for finding the value of a const minus 1.
> trait MinusOne<const NUM: usize> {
> ```

Maybe predecssor?



_Suggestion:_
```Cairo
Predecssor
```

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/circuit.cairo` line 278 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5734#-Nzvod0o8NlKT-5Z6jHJ:-Nzvod0o8NlKT-5Z6jHK:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/033d86000c4e528c9717f9f8b3f13bd9db07aae0/corelib/src/circuit.cairo#L278)):*
> ```Cairo
> }
> 
> /// Trait helper to convert a multi limb guarantee to a `U96Guarantee`.
> ```





_Suggestion:_
```Cairo
/// Trait helper to convert a multi-limb guarantee to a `U96Guarantee` of the first pair of limbs that differ.
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5734)* status: 1 of 10 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/circuit.cairo` line 265 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5734#-NzvmcwM30o_H-u8uDzJ:-NzwClKLB0MroY78pdJz:bqfoenw) ([raw file](https://github.com/starkware-libs/cairo/blob/033d86000c4e528c9717f9f8b3f13bd9db07aae0/corelib/src/circuit.cairo#L265)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Maybe predecssor?
</blockquote></details>

it is exactly minus 1 IMO - as predecessor would need to define in what sense.
___
*[`corelib/src/circuit.cairo` line 278 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5734#-Nzvod0o8NlKT-5Z6jHJ:-NzwE8jQ1DVi1YEIfIqE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/033d86000c4e528c9717f9f8b3f13bd9db07aae0/corelib/src/circuit.cairo#L278)):*
> ```Cairo
> }
> 
> /// Trait helper to convert a multi limb guarantee to a `U96Guarantee`.
> ```

Done.
___
*[`corelib/src/circuit.cairo` line 288 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5734#-NzvnOQ52Ir_P1JqY1jB:-NzwI_1X4MpdDrB5e1Y2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/033d86000c4e528c9717f9f8b3f13bd9db07aae0/corelib/src/circuit.cairo#L288)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't think this is an error.

maybe don't use result.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5734#-:-NzwR8FX1PcEZVKOLgYH:bnfp4nl)* status: 2 of 10 files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
