### PR TITLE
Created a calc metadata function, to enable stages in equation solving.

### PR DESCRIPTION
**Pull request by orizi**
Fixed recursive_fib to have a valid ap-change solution, in order to use
the new calc metadata on it.

commit-id:50b1d1ab

---

**Stack**:
- #1717
- #1716
- #1715
- #1691 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1691)* status: 7 of 11 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/metadata.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1691#-NLHC9BdBzT5qYxU8FbY:-NLHC9BdBzT5qYxU8FbZ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7491fff3c15b6ca67b933e367c6b05b97744c06e/crates/cairo-lang-sierra-to-casm/src/metadata.rs#L31)):*
> ```XML
> /// Calculates the metadata for a Sierra program.
> pub fn calc_metadata(program: &Program) -> Result<Metadata, MetadataError> {
>     let token_gas_info = calc_gas_info(program, &HashSet::from([CostTokenType::Pedersen]))?;
> ```





_Suggestion:_
```XML
UnorderedHashSet
```
___
*[`crates/cairo-lang-sierra-to-casm/src/metadata.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1691#-NLHD3mx75F2BT7xu6tp:-NLHD3my4fHjfdSkjjNb:b-3qmzpa) ([raw file](https://github.com/starkware-libs/cairo/blob/7491fff3c15b6ca67b933e367c6b05b97744c06e/crates/cairo-lang-sierra-to-casm/src/metadata.rs#L37)):*
> ```XML
>     for (func_id, costs) in token_gas_info.function_costs.into_iter() {
>         match gas_info.function_costs.entry(func_id) {
>             Entry::Occupied(mut e) => e.get_mut().extend(costs.into_iter()),
> ```

Extract this code to a function of `gas_info` (e.g., `gas_info.extend(token_gas_info)`).



_Code quote:_
```XML
    gas_info.variable_values.extend(token_gas_info.variable_values.into_iter());
    for (func_id, costs) in token_gas_info.function_costs.into_iter() {
        match gas_info.function_costs.entry(func_id) {
            Entry::Occupied(mut e) => e.get_mut().extend(costs.into_iter()),
            Entry::Vacant(e) => {
                e.insert(costs);
            }
        };
    }
```
___
*[`crates/cairo-lang-sierra-to-casm/src/test_utils.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1691#-NLHEPMk0AR2TKb-cId9:-NLHEPMk0AR2TKb-cIdA:b5p00re) ([raw file](https://github.com/starkware-libs/cairo/blob/7491fff3c15b6ca67b933e367c6b05b97744c06e/crates/cairo-lang-sierra-to-casm/src/test_utils.rs#L16)):*
> ```XML
> pub fn build_metadata(program: &Program, calculate_gas_info: bool) -> Metadata {
>     if calculate_gas_info {
>         calc_metadata(program).expect("Failed calculating expected gas or ap change.")
> ```

Why `expected`?



_Code quote:_
```XML
expected
```
___
*[`crates/cairo-lang-utils/src/ordered_hash_map.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1691#-NLHBUzjAsuDEsDV7151:-NLHBUzjAsuDEsDV7152:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7491fff3c15b6ca67b933e367c6b05b97744c06e/crates/cairo-lang-utils/src/ordered_hash_map.rs#L106)):*
> ```XML
> 
>     /// Scan through each key-value pair in the map and keep those where the
>     /// closure `keep` returns `true`.
> ```





_Suggestion:_
```XML
    /// Scans through each key-value pair in the map and keeps those where the
    /// closure `keep` returns `true`.
    ///
    /// The elements are visited in order, and remaining elements keep their
    /// order.
    ///
    /// Computes in **O(n)** time (average).
```

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1691)* status: 8 of 11 files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1691#-NLHEnhs9bm1cwsYVlY2:-NLHEnhs9bm1cwsYVlY3:b2jape0) ([raw file](https://github.com/starkware-libs/cairo/blob/7491fff3c15b6ca67b933e367c6b05b97744c06e/crates/cairo-lang-sierra-gas/src/lib.rs#L49)):*
> ```XML
>                 .get_libfunc(libfunc_id)
>                 .expect("Program registery creation would have already failed.");
>             // Retaining only cost tokens that are required by the function.
> ```

Remove after passing `token_types` into `generate_equations`.

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 2 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1691)* status: 10 of 11 files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 314 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1691#-NLHHuJ14zCrWmz20xg1:-NLHHuJ14zCrWmz20xg2:b-awezib) ([raw file](https://github.com/starkware-libs/cairo/blob/7491fff3c15b6ca67b933e367c6b05b97744c06e/crates/cairo-lang-runner/src/lib.rs#L314)):*
> ```XML
> 
> /// Creates the metadata required for a Sierra program lowering to casm.
> fn create_metadata(
> ```

Suggestion: merge with the main `calc_metadata` function (not necessarily in this PR).

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1691)* status: 5 of 11 files reviewed, 5 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1691#-NLHEnhs9bm1cwsYVlY2:-NLHbzE2Bghu4d2lBT2-:buvflm3) ([raw file](https://github.com/starkware-libs/cairo/blob/7491fff3c15b6ca67b933e367c6b05b97744c06e/crates/cairo-lang-sierra-gas/src/lib.rs#L49)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Remove after passing `token_types` into `generate_equations`.
</blockquote></details>

already removed - will instead treat steps as a worst case in second run - so changing strategy for now.
___
*[`crates/cairo-lang-sierra-to-casm/src/metadata.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1691#-NLHC9BdBzT5qYxU8FbY:-NLHc7GYBd3AXF8nkeW9:bvth56w) ([raw file](https://github.com/starkware-libs/cairo/blob/7491fff3c15b6ca67b933e367c6b05b97744c06e/crates/cairo-lang-sierra-to-casm/src/metadata.rs#L31)):*
> ```XML
> /// Calculates the metadata for a Sierra program.
> pub fn calc_metadata(program: &Program) -> Result<Metadata, MetadataError> {
>     let token_gas_info = calc_gas_info(program, &HashSet::from([CostTokenType::Pedersen]))?;
> ```

reverted
___
*[`crates/cairo-lang-sierra-to-casm/src/metadata.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1691#-NLHD3mx75F2BT7xu6tp:-NLHc9378KvUSsThBFBZ:bvth56w) ([raw file](https://github.com/starkware-libs/cairo/blob/7491fff3c15b6ca67b933e367c6b05b97744c06e/crates/cairo-lang-sierra-to-casm/src/metadata.rs#L37)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Extract this code to a function of `gas_info` (e.g., `gas_info.extend(token_gas_info)`).
</blockquote></details>

reverted
___
*[`crates/cairo-lang-sierra-to-casm/src/test_utils.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1691#-NLHEPMk0AR2TKb-cId9:-NLHcImQ7F-Gvuo3uxz_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7491fff3c15b6ca67b933e367c6b05b97744c06e/crates/cairo-lang-sierra-to-casm/src/test_utils.rs#L16)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Why `expected`?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-utils/src/ordered_hash_map.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1691#-NLHBUzjAsuDEsDV7151:-NLHcYr75Ys2zHXkuG9d:b-81taoq) ([raw file](https://github.com/starkware-libs/cairo/blob/7491fff3c15b6ca67b933e367c6b05b97744c06e/crates/cairo-lang-utils/src/ordered_hash_map.rs#L106)):*
> ```XML
> 
>     /// Scan through each key-value pair in the map and keep those where the
>     /// closure `keep` returns `true`.
> ```

reverted.



_Code quote (from crates/cairo-lang-sierra-to-casm/src/test_utils.rs):_
```XML
"Failed calculating expected gas or ap change."
```

**Review by liorgold2 — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1691)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1691#-:-NLPzafX9gkcmMYtrFuz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
