### PR TITLE
Add Maybe<> type to help guaranteeing that diagnostics are reported.

### PR DESCRIPTION
**Pull request by liorgold2**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1315)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1315#-:-NJEUHEk-2Fadqnf4wOa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware, @spapinistarkware, and @yuvalsw)

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1315#-:-NJF0Q7P9RKTFJYW0gFC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware and @yuvalsw)

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1315)* status: all files reviewed, 5 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

___
*[`crates/diagnostics/src/diagnostics.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1315#-NJEyxU5Bs11mJXskwjj:-NJEyxU61JbQDU_KNKVY:b32wof) ([raw file](https://github.com/starkware-libs/cairo/blob/6eea3cdb58918d66aa1f0a75c1bad581f649804c/crates/diagnostics/src/diagnostics.rs#L29)):*
> ```XML
> }
> 
> /// This struct is used to ensure that when an error occurs, a diagnostic was properly reported.
> ```

is



_Code quote:_
```XML
was
```
___
*[`crates/diagnostics/src/diagnostics.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1315#-NJEzWexBIKEqYYYrIOa:-NJEzWey2zDt9Zs7pHjV:bfuvsu7) ([raw file](https://github.com/starkware-libs/cairo/blob/6eea3cdb58918d66aa1f0a75c1bad581f649804c/crates/diagnostics/src/diagnostics.rs#L36)):*
> ```XML
> pub struct DiagnosticAdded {}
> 
> pub fn skip_diagnostic() -> DiagnosticAdded {
> ```

Add log?
___
*[`crates/diagnostics/src/diagnostics.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1315#-NJEzzAxAERZrg4y8NB_:-NJEzzAxAERZrg4y8NBa:bt64ckd) ([raw file](https://github.com/starkware-libs/cairo/blob/6eea3cdb58918d66aa1f0a75c1bad581f649804c/crates/diagnostics/src/diagnostics.rs#L46)):*
> ```XML
> /// Temporary trait to allow conversions from the old [Option<T>] mechanism to [Maybe<T>].
> // TODO(lior): Remove this trait after converting all the functions.
> pub trait ToMaybe<T> {
> ```

is it implemented to something else or only option? If only for Option, you can have a free function instead:
pub fn<T> option_to_maybe(option: Option<T>) -> Maybe<T> {...}



_Code quote:_
```XML
ub trait
```
___
*[`crates/diagnostics/src/diagnostics.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1315#-NJF0zOR1eN9l3u7TQrD:-NJF0zOS5T4d_tUeqqHG:byzaf07) ([raw file](https://github.com/starkware-libs/cairo/blob/6eea3cdb58918d66aa1f0a75c1bad581f649804c/crates/diagnostics/src/diagnostics.rs#L83)):*
> ```XML
>     pub fn add(&mut self, diagnostic: TEntry) -> DiagnosticAdded {
>         self.leaves.push(diagnostic);
>         DiagnosticAdded {}
> ```

I suggest 1 of 2:
1. remove the {} from the definition of the struct. Then here you can remove them too.
2. Derive Default and then call here ::default().



_Code quote:_
```XML
DiagnosticAdded {}
```
___
*[`crates/lowering/src/lower.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1315#-NJF1pGS6kk2GRiwFR3g:-NJF1pGS6kk2GRiwFR3h:bxkloc) ([raw file](https://github.com/starkware-libs/cairo/blob/6eea3cdb58918d66aa1f0a75c1bad581f649804c/crates/lowering/src/lower.rs#L47)):*
> ```XML
>     pub diagnostics: Diagnostics<LoweringDiagnostic>,
>     /// Block id for the start of the lowered function.
>     pub root: Maybe<BlockId>,
> ```

I'd use here diagnostics::Maybe to better understand in this context.

Same for the rest of this file.



_Code quote:_
```XML
Maybe
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1315)* status: all files reviewed, 3 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/diagnostics/src/diagnostics.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1315#-NJEyxU5Bs11mJXskwjj:-NJFJc8pEnztqNbzqBBa:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6eea3cdb58918d66aa1f0a75c1bad581f649804c/crates/diagnostics/src/diagnostics.rs#L29)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

is
</blockquote></details>

Done.
___
*[`crates/diagnostics/src/diagnostics.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1315#-NJEzWexBIKEqYYYrIOa:-NJFJERX2S_LY3QytQnb:b-26p9sh) ([raw file](https://github.com/starkware-libs/cairo/blob/6eea3cdb58918d66aa1f0a75c1bad581f649804c/crates/diagnostics/src/diagnostics.rs#L36)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Add log?
</blockquote></details>

Not in this PR. Maybe after the migration is completed.
___
*[`crates/diagnostics/src/diagnostics.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1315#-NJEzzAxAERZrg4y8NB_:-NJFJMBQBGVGlxgnweJd:boegn5m) ([raw file](https://github.com/starkware-libs/cairo/blob/6eea3cdb58918d66aa1f0a75c1bad581f649804c/crates/diagnostics/src/diagnostics.rs#L46)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

is it implemented to something else or only option? If only for Option, you can have a free function instead:
pub fn<T> option_to_maybe(option: Option<T>) -> Maybe<T> {...}
</blockquote></details>

I want to keep the code readable by adding it as a suffix `.to_maybe()` instead of `to_maybe(...)`.
___
*[`crates/diagnostics/src/diagnostics.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1315#-NJF0zOR1eN9l3u7TQrD:-NJFJpNF5gqdi1OtfEme:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6eea3cdb58918d66aa1f0a75c1bad581f649804c/crates/diagnostics/src/diagnostics.rs#L83)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I suggest 1 of 2:
1. remove the {} from the definition of the struct. Then here you can remove them too.
2. Derive Default and then call here ::default().
</blockquote></details>

Done.
___
*[`crates/lowering/src/lower.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1315#-NJF1pGS6kk2GRiwFR3g:-NJFK1ZO-zI1w1ZLCZ5o:b-pp1vop) ([raw file](https://github.com/starkware-libs/cairo/blob/6eea3cdb58918d66aa1f0a75c1bad581f649804c/crates/lowering/src/lower.rs#L47)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I'd use here diagnostics::Maybe to better understand in this context.

Same for the rest of this file.
</blockquote></details>

Noted. We'll have `Maybe` everywhere; people will need to check what this is when reading our codebase.

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1315)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

___
*[`crates/diagnostics/src/diagnostics.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1315#-NJEyxU5Bs11mJXskwjj:-NJFVGTG0C-FMazE5XTO:bm2rh69) ([raw file](https://github.com/starkware-libs/cairo/blob/6eea3cdb58918d66aa1f0a75c1bad581f649804c/crates/diagnostics/src/diagnostics.rs#L29)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I don't see the change. Did you push it?
</blockquote></details>

I accidentally changed it below. Fixed.
___
*[`crates/diagnostics/src/diagnostics.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1315#-NJEzWexBIKEqYYYrIOa:-NJFVOTT7OwTzMQFy6n2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6eea3cdb58918d66aa1f0a75c1bad581f649804c/crates/diagnostics/src/diagnostics.rs#L36)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Then a TODO would be nice
</blockquote></details>

Done.

**Review by yuvalsw — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1315)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1315)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
