### PR TITLE
Added format_string utility to formatter

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1224)

### CODE REVIEW

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1224#-:-NIZF2q6B2bdKt21q99V:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/formatter/src/lib.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1224#-NIZEH-F27xxz60rZ2iN:-NIZEH-F27xxz60rZ2iO:b-zg3869) ([raw file](https://github.com/starkware-libs/cairo/blob/3a61655a1636ce06e2b8faa665bbd3e83b4133f6/crates/formatter/src/lib.rs#L33)):*
> ```XML
>     let virtual_file = db.upcast().intern_file(FileLongId::Virtual(VirtualFile {
>         parent: None,
>         name: "name".into(),
> ```

I guess it won't be used anywhere, but consider "string_to_format" or something similar.



_Code quote:_
```XML
name: "name".into(),
```

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1224)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1224)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, 1 of 2 files at r2, 3 of 4 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1224)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
