### PR TITLE
Add an option to format tests inputs, and format all the tests.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5287)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5287)* status: 0 of 123 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-test-utils/src/parse_test_file.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5287#-NtQMFh379Cp1Sf49IsD:-NtQMFh379Cp1Sf49IsE:b-7u1ss9) ([raw file](https://github.com/starkware-libs/cairo/blob/4521021003cc498939e1c6ecb934d2865821c948/crates/cairo-lang-test-utils/src/parse_test_file.rs#L46)):*
> ```XML
>                 // The testing framework adds a newline at the end of each test, and so does the
>                 // formatter.
>                 *value = formatted_value.trim_end().to_string();
> ```

Should I assert that the values are equal if not with `CAIRO_FIX_TESTS` and fail the test if so?
Then we can add `CAIRO_FORMAT_TESTS` to the CI to enforce it.



_Code quote:_
```XML
*value = formatted_value.trim_end().to_string();
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 27 of 123 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5287)* status: 27 of 123 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-lowering/src/test_data/error_propagate` line 8 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5287#-NtQWTsG523j1Z7tSQ-o:-NtQWTsG523j1Z7tSQ-p:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/bd0e01dae2f53d019c08581a27c6046dea6d032c/crates/cairo-lang-lowering/src/test_data/error_propagate#L8)):*
> ```
> //! > function
> fn foo(a: Result::<Result<u128, felt252>, felt252>) -> Result::<felt252, felt252> {
>     a??;
> ```





_Suggestion:_
```
fn foo(a: Result<Result<u128, felt252>, felt252>) -> Result<felt252, felt252> {
    a??;
```
___
*[`crates/cairo-lang-lowering/src/test_data/literal` line 138 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5287#-NtQWcXn6S9D63UcqM47:-NtQWcXn6S9D63UcqM48:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/bd0e01dae2f53d019c08581a27c6046dea6d032c/crates/cairo-lang-lowering/src/test_data/literal#L138)):*
> ```
> //! > function
> fn foo() -> (felt252, u8, u16, u32, u64, u128, i8, i16, i32, i64, i128, u256) {
>     (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,)
> ```





_Suggestion:_
```
    (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 42 of 123 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5287)* status: 70 of 123 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/item_trait` line 73 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5287#-NtQX3rW3_JKZ_XFzeb1:-NtQX3rW3_JKZ_XFzeb2:b-l6hdjr) ([raw file](https://github.com/starkware-libs/cairo/blob/bd0e01dae2f53d019c08581a27c6046dea6d032c/crates/cairo-lang-parser/src/parser_test_data/partial_trees/item_trait#L73)):*
> ```
>     fn foo<S>(x: T, y: S);
> }
> impl FooImpl<W> of Foo<u8> {
> ```

revert
___
*[`crates/cairo-lang-semantic/src/expr/test_data/coupon` line 150 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5287#-NtQXj138Af1NrhBBVBF:-NtQXj138Af1NrhBBVBG:buh9hkh) ([raw file](https://github.com/starkware-libs/cairo/blob/bd0e01dae2f53d019c08581a27c6046dea6d032c/crates/cairo-lang-semantic/src/expr/test_data/coupon#L150)):*
> ```
>         fn trait_fn() {}
>     }
>     impl DropMyImplCoupon<T> of Drop<MyImpl<T>::trait_fn::Coupon>;
> ```

revert.
also make sure this wont happen elsewhere.

**Review by orizi — COMMENTED** [review]
> Reviewed 52 of 123 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5287)* status: 122 of 123 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-test-utils/src/parse_test_file.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5287#-NtQMFh379Cp1Sf49IsD:-NtQZTx7CKXVqbjEN2EC:b-3gh852) ([raw file](https://github.com/starkware-libs/cairo/blob/4521021003cc498939e1c6ecb934d2865821c948/crates/cairo-lang-test-utils/src/parse_test_file.rs#L46)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Should I assert that the values are equal if not with `CAIRO_FIX_TESTS` and fail the test if so?
Then we can add `CAIRO_FORMAT_TESTS` to the CI to enforce it.
</blockquote></details>

this sounds like a valid idea.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5287)* status: 122 of 123 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/test_data/error_propagate` line 8 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5287#-NtQWTsG523j1Z7tSQ-o:-NtQh5SqAkdjTj75yo1S:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bd0e01dae2f53d019c08581a27c6046dea6d032c/crates/cairo-lang-lowering/src/test_data/error_propagate#L8)):*
> ```
> //! > function
> fn foo(a: Result::<Result<u128, felt252>, felt252>) -> Result::<felt252, felt252> {
>     a??;
> ```

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees/item_trait` line 73 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5287#-NtQX3rW3_JKZ_XFzeb1:-NtQhTG92iIAlR0wG-ri:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bd0e01dae2f53d019c08581a27c6046dea6d032c/crates/cairo-lang-parser/src/parser_test_data/partial_trees/item_trait#L73)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

revert
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/coupon` line 150 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5287#-NtQXj138Af1NrhBBVBF:-NtQhUyY6k2uLkpgEC-I:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bd0e01dae2f53d019c08581a27c6046dea6d032c/crates/cairo-lang-semantic/src/expr/test_data/coupon#L150)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

revert.
also make sure this wont happen elsewhere.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-test-utils/src/parse_test_file.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5287#-NtQMFh379Cp1Sf49IsD:-NtQg_A009X7rb4PIydw:b-pnfrig) ([raw file](https://github.com/starkware-libs/cairo/blob/4521021003cc498939e1c6ecb934d2865821c948/crates/cairo-lang-test-utils/src/parse_test_file.rs#L46)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this sounds like a valid idea.
</blockquote></details>

Done.
Also changed the default behaviour to format (can be overridden with `CAIRO_SKIP_FORMAT_TESTS=1`) to avoid adding `CAIRO_FORMAT_TESTS`.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5287)* status: 106 of 124 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/coupon` line 150 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5287#-NtQXj138Af1NrhBBVBF:-NtQiCD1ESjEEKHBnnkr:bujcj81) ([raw file](https://github.com/starkware-libs/cairo/blob/bd0e01dae2f53d019c08581a27c6046dea6d032c/crates/cairo-lang-semantic/src/expr/test_data/coupon#L150)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done, fixing.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5287)* status: 118 of 123 files reviewed, 4 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5287#-NtR7TtB9qjwqH0SwI1F:-NtR7TtB9qjwqH0SwI1G:b-tmwjk4) (no related file):*
Change target

___
___
*[`crates/cairo-lang-lowering/src/test_data/error_propagate` line 8 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5287#-NtQWTsG523j1Z7tSQ-o:-NtR0F-a-gcfHpO5otPj:b-ssy3xh) ([raw file](https://github.com/starkware-libs/cairo/blob/bd0e01dae2f53d019c08581a27c6046dea6d032c/crates/cairo-lang-lowering/src/test_data/error_propagate#L8)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done manually. I want to take a closer look at when exactly the parser allows skipped `::` before adding it to the formatter skipped tokens.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/coupon` line 150 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5287#-NtQXj138Af1NrhBBVBF:-NtR7cgQ0M6xMP-oIFh5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bd0e01dae2f53d019c08581a27c6046dea6d032c/crates/cairo-lang-semantic/src/expr/test_data/coupon#L150)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Not done, fixing.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5287#-:-NtRELbk3Ak18TcRzEKh:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
