### PR TITLE
Removed all BNFs from documentation

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2801)

### CODE REVIEW

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 13 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2801)* status: 13 of 14 files reviewed, 4 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/block-expression.adoc` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2801#-NTFkdDp1uQlCLKz4tEy:-NTFkdDp1uQlCLKz4tEz:ba3dfna) ([raw file](https://github.com/starkware-libs/cairo/blob/97881f108d732c85d14994529ab32a2fef0f4f31/docs/reference/src/components/cairo/modules/language_constructs/pages/block-expression.adoc#L2)):*
> ```AsciiDoc
> = Block expression
> TODO
> ```

Remove?
___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/unit-type.adoc` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2801#-NTFlOF-BtWJD0PlWOux:-NTFlOF-BtWJD0PlWOuy:btmtzgx) ([raw file](https://github.com/starkware-libs/cairo/blob/97881f108d732c85d14994529ab32a2fef0f4f31/docs/reference/src/components/cairo/modules/language_constructs/pages/unit-type.adoc#L3)):*
> ```AsciiDoc
> = Unit type
> 
> A _unit type_ is a type which has only one value (xref:literal-expressions.adoc[unit literal], `
> ```

It is represented by a tuple with no elements.



_Code quote:_
```AsciiDoc
A _unit type_ is a type which has only one value (xref:literal-expressions.adoc[unit literal], `
()`).
```
___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/unit-type.adoc` line 5 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2801#-NTFlICUE4eK89-mR5zN:-NTFlICUE4eK89-mR5zO:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/97881f108d732c85d14994529ab32a2fef0f4f31/docs/reference/src/components/cairo/modules/language_constructs/pages/unit-type.adoc#L5)):*
> ```AsciiDoc
> A _unit type_ is a type which has only one value (xref:literal-expressions.adoc[unit literal], `
> ()`).
> Its size is always zero, and it is guaranteed to be eliminated from output code in compilation time.
> ```





_Suggestion:_
```AsciiDoc
Its size is always zero, and it is guaranteed to be eliminated from the compiled code.
```
___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/whitespace.adoc` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2801#-NTFlZ09B-e3pkA6QBLZ:-NTFlZ09B-e3pkA6QBL_:b-r1dun5) ([raw file](https://github.com/starkware-libs/cairo/blob/97881f108d732c85d14994529ab32a2fef0f4f31/docs/reference/src/components/cairo/modules/language_constructs/pages/whitespace.adoc#L3)):*
> ```AsciiDoc
> = Whitespace
> 
> Whitespace is any non-empty string containing only characters that have the https://www.unicode.org/reports/tr31/[`Pattern_White_Space`]
> ```

Line too long.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2801)* status: all files reviewed, 7 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/identifiers.adoc` line 7 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2801#-NTFlmoZCdkQbf8KxIzR:-NTFlmoZCdkQbf8KxIzS:b-mf9y8z) ([raw file](https://github.com/starkware-libs/cairo/blob/97881f108d732c85d14994529ab32a2fef0f4f31/docs/reference/src/components/cairo/modules/language_constructs/pages/identifiers.adoc#L7)):*
> ```AsciiDoc
> The exceptions are:
> 
> - A single underscore character does not form an identifier.
> ```

Add `Instead, it represents ...` + link to documentation if exists.
___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/identifiers.adoc` line 8 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2801#-NTFluKa1FQIkanRiS2m:-NTFluKa1FQIkanRiS2n:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/97881f108d732c85d14994529ab32a2fef0f4f31/docs/reference/src/components/cairo/modules/language_constructs/pages/identifiers.adoc#L8)):*
> ```AsciiDoc
> 
> - A single underscore character does not form an identifier.
> - Cairo xref:keywords.adoc[keywords] can't be used as identifiers.
> ```





_Suggestion:_
```AsciiDoc
- Cairo xref:keywords.adoc[keywords] cannot be used as identifiers.
```
___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/identifiers.adoc` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2801#-NTFm8UeBsJ6UiNlReh5:-NTFm8UfAKKUBfevkAVU:b-r1dun5) ([raw file](https://github.com/starkware-libs/cairo/blob/97881f108d732c85d14994529ab32a2fef0f4f31/docs/reference/src/components/cairo/modules/language_constructs/pages/identifiers.adoc#L12)):*
> ```AsciiDoc
> [NOTE]
> ====
> Identifiers starting with an underscore are typically used to indicate an identifier that is intentionally unused, and will silence the unused warning.
> ```

Line too long.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2801)* status: 11 of 14 files reviewed, 7 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/block-expression.adoc` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2801#-NTFkdDp1uQlCLKz4tEy:-NTNMCgL1seokfcAG3HA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/97881f108d732c85d14994529ab32a2fef0f4f31/docs/reference/src/components/cairo/modules/language_constructs/pages/block-expression.adoc#L2)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

Done.
___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/identifiers.adoc` line 7 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2801#-NTFlmoZCdkQbf8KxIzR:-NTNLZ6MDpxXunzq5gfx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/97881f108d732c85d14994529ab32a2fef0f4f31/docs/reference/src/components/cairo/modules/language_constructs/pages/identifiers.adoc#L7)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Add `Instead, it represents ...` + link to documentation if exists.
</blockquote></details>

Done.
___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/identifiers.adoc` line 8 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2801#-NTFluKa1FQIkanRiS2m:-NTIzfGXDjV_Wb9UJDC_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/97881f108d732c85d14994529ab32a2fef0f4f31/docs/reference/src/components/cairo/modules/language_constructs/pages/identifiers.adoc#L8)):*
> ```AsciiDoc
> 
> - A single underscore character does not form an identifier.
> - Cairo xref:keywords.adoc[keywords] can't be used as identifiers.
> ```

Done.
___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/identifiers.adoc` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2801#-NTFm8UeBsJ6UiNlReh5:-NTNLc5y8ytSm4teLN-W:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/97881f108d732c85d14994529ab32a2fef0f4f31/docs/reference/src/components/cairo/modules/language_constructs/pages/identifiers.adoc#L12)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Line too long.
</blockquote></details>

Done.



_Code quote:_
```AsciiDoc
nd will silence the unused warni
```
___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/unit-type.adoc` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2801#-NTFlOF-BtWJD0PlWOux:-NTNM0oJ23QmjcXBEsh4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/97881f108d732c85d14994529ab32a2fef0f4f31/docs/reference/src/components/cairo/modules/language_constructs/pages/unit-type.adoc#L3)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

It is represented by a tuple with no elements.
</blockquote></details>

Done.
___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/unit-type.adoc` line 5 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2801#-NTFlICUE4eK89-mR5zN:-NTNM22h7atLeXSKMEqX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/97881f108d732c85d14994529ab32a2fef0f4f31/docs/reference/src/components/cairo/modules/language_constructs/pages/unit-type.adoc#L5)):*
> ```AsciiDoc
> A _unit type_ is a type which has only one value (xref:literal-expressions.adoc[unit literal], `
> ()`).
> Its size is always zero, and it is guaranteed to be eliminated from output code in compilation time.
> ```

Done.
___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/whitespace.adoc` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2801#-NTFlZ09B-e3pkA6QBLZ:-NTNM61s2qK1f75fjHtZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/97881f108d732c85d14994529ab32a2fef0f4f31/docs/reference/src/components/cairo/modules/language_constructs/pages/whitespace.adoc#L3)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Line too long.
</blockquote></details>

Done.

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2801#-:-NTjyP0H4NrsDhFNp9QS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
