### PR TITLE
Refactored Hash trait.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3714)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 1 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3714)* status: 1 of 10 files reviewed, 2 unresolved discussions (waiting on @ArielElp, @ilyalesokhin-starkware, @orizi, and @spapinistarkware)

___
*[`corelib/src/hash.cairo` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3714#-N_jVJml7pwMMFTMlBeG:-N_jVJml7pwMMFTMlBeH:b-vbssxo) ([raw file](https://github.com/starkware-libs/cairo/blob/6ab42cc7714d2334e9764866165a63c5cab2c6d2/corelib/src/hash.cairo#L17)):*
> ```Cairo
> trait Hash<T, S, impl SHashState: HashStateTrait<S>> {
>     /// Updates the hash state with the given value.
>     fn update_state(state: S, value: T) -> S;
> ```

I'm not sure both `update_state` and `update_with` are needed.
___
*[`corelib/src/hash.cairo` line 62 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3714#-N_jWk5UEKL9GOyO5diA:-N_jWk5UEKL9GOyO5diB:bmdh0wx) ([raw file](https://github.com/starkware-libs/cairo/blob/6ab42cc7714d2334e9764866165a63c5cab2c6d2/corelib/src/hash.cairo#L62)):*
> ```Cairo
> }
> 
> /// State for Poseidon hash.
> ```

Shouldn't this be in `poseidon.cairo`?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3714)* status: 1 of 10 files reviewed, 2 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, @ilyalesokhin-starkware, and @spapinistarkware)

___
*[`corelib/src/hash.cairo` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3714#-N_jVJml7pwMMFTMlBeG:-N_jwFVz-zlBpkgC8iDY:bxfnhce) ([raw file](https://github.com/starkware-libs/cairo/blob/6ab42cc7714d2334e9764866165a63c5cab2c6d2/corelib/src/hash.cairo#L17)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

I'm not sure both `update_state` and `update_with` are needed.
</blockquote></details>

`update_with` is in order to get the method - otherwise you won't have that option within implementations.
___
*[`corelib/src/hash.cairo` line 62 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3714#-N_jWk5UEKL9GOyO5diA:-N_jwVHkBMMpu0owaeXx:bbsc7w8) ([raw file](https://github.com/starkware-libs/cairo/blob/6ab42cc7714d2334e9764866165a63c5cab2c6d2/corelib/src/hash.cairo#L62)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Shouldn't this be in `poseidon.cairo`?
</blockquote></details>

maybe - maybe poseidon file should just be consolidated here.

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/poseidon.cairo` line 31 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3714#-Na0lYxtC5N3XbB0xUn-:-Na0lYxtC5N3XbB0xUn0:b-17ae3p) ([raw file](https://github.com/starkware-libs/cairo/blob/2470cf920ca3deea12361258c4e2270d51724bf0/corelib/src/poseidon.cairo#L31)):*
> ```Cairo
> impl HashStateImpl of HashStateTrait<HashState> {
>     #[inline(always)]
>     fn update(self: HashState, value: felt252) -> HashState {
> ```

Isn't it better to build an array here and do all the computation in finalize?



_Code quote:_
```Cairo
   fn update(self: HashState, value: felt252) -> HashState {
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3714)* status: 0 of 18 files reviewed, 3 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, @ilyalesokhin-starkware, and @spapinistarkware)

___
*[`corelib/src/poseidon.cairo` line 31 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3714#-Na0lYxtC5N3XbB0xUn-:-Na0t7PkC1qb3S_1jwe_:bq0ru77) ([raw file](https://github.com/starkware-libs/cairo/blob/2470cf920ca3deea12361258c4e2270d51724bf0/corelib/src/poseidon.cairo#L31)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Isn't it better to build an array here and do all the computation in finalize?
</blockquote></details>

no - at the very least for cases where we do a a compile time constant number of hashes (e.g. a key struct for a storage variable).

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 16 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3714)* status: 8 of 18 files reviewed, 1 unresolved discussion (waiting on @ArielElp, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/user_defined_types` line 14 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3714#-Na1MIxu61wkgq4v49E8:-Na1MIxu61wkgq4v49E9:b-uc6ko5) ([raw file](https://github.com/starkware-libs/cairo/blob/b5c44f86ce831d5e39ee87403788d6d2489de14d/crates/cairo-lang-starknet/src/plugin/plugin_test_data/user_defined_types#L14)):*
> ```
>         mapping: LegacyMap::<WrappedFelt252, WrappedFelt252>,
>     }
>     #[derive(Drop, Serde, starknet::Store)]
> ```

Stray commit.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3714)* status: 8 of 18 files reviewed, 1 unresolved discussion (waiting on @ArielElp, @gilbens-starkware, @ilyalesokhin-starkware, and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/user_defined_types` line 14 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3714#-Na1MIxu61wkgq4v49E8:-Na1WA9oEMttFyrpiqEF:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b5c44f86ce831d5e39ee87403788d6d2489de14d/crates/cairo-lang-starknet/src/plugin/plugin_test_data/user_defined_types#L14)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Stray commit.
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/poseidon.cairo` line 31 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3714#-Na0lYxtC5N3XbB0xUn-:-Na1ipMr2raUfziFJhj2:bnyv8aq) ([raw file](https://github.com/starkware-libs/cairo/blob/2470cf920ca3deea12361258c4e2270d51724bf0/corelib/src/poseidon.cairo#L31)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no - at the very least for cases where we do a a compile time constant number of hashes (e.g. a key struct for a storage variable).
</blockquote></details>

I think we should have an efficient version of hash_many with variable length input.

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3714)* status: 10 of 18 files reviewed, 1 unresolved discussion (waiting on @ArielElp, @ilyalesokhin-starkware, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/user_defined_types` line 306 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3714#-Na1mOtu0LOwgAP7ce8N:-Na1mOtu0LOwgAP7ce8O:br92wsx) ([raw file](https://github.com/starkware-libs/cairo/blob/a8849845a1475267e6b6c2c424d63c6934a88d5b/crates/cairo-lang-starknet/src/plugin/plugin_test_data/user_defined_types#L306)):*
> ```
> 
> //! > expected_diagnostics
> error: Method `update_with` not found on type "S". Did you import the correct trait and impl?
> ```

Notice.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3714)* status: 10 of 18 files reviewed, 1 unresolved discussion (waiting on @ArielElp, @ilyalesokhin-starkware, and @spapinistarkware)

___
*[`corelib/src/poseidon.cairo` line 31 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3714#-Na0lYxtC5N3XbB0xUn-:-Na1tLkc5ICdweGP-p8B:bpvlr32) ([raw file](https://github.com/starkware-libs/cairo/blob/2470cf920ca3deea12361258c4e2270d51724bf0/corelib/src/poseidon.cairo#L31)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I think we should have an efficient version of hash_many with variable length input.
</blockquote></details>

maybe we should - but for the generic case for the Hash for Map in storage access - this is much better.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3714)* status: 10 of 18 files reviewed, 1 unresolved discussion (waiting on @ArielElp, @gilbens-starkware, @ilyalesokhin-starkware, and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/user_defined_types` line 306 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3714#-Na1mOtu0LOwgAP7ce8N:-Na1tX0S3meGw7wzC1Me:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a8849845a1475267e6b6c2c424d63c6934a88d5b/crates/cairo-lang-starknet/src/plugin/plugin_test_data/user_defined_types#L306)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Notice.
</blockquote></details>

Done.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 10 files at r1, 6 of 16 files at r2, 1 of 2 files at r4, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3714#-:-Na1xclu5zaSRhdFCJ8g:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp, @ilyalesokhin-starkware, and @spapinistarkware)

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3714)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp, @ilyalesokhin-starkware, and @spapinistarkware)

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3714)* status: all files reviewed, 2 unresolved discussions (waiting on @ArielElp, @ilyalesokhin-starkware, and @orizi)

___
*[`corelib/src/pedersen.cairo` line 9 at r8](https://reviewable.io/reviews/starkware-libs/cairo/3714#-Na6kWtG5kjy9oLbMAFb:-Na6kWtG5kjy9oLbMAFc:bvgfy8d) ([raw file](https://github.com/starkware-libs/cairo/blob/ffd547dca57b566fe2fa6c19a3ac883cf3bdc194/corelib/src/pedersen.cairo#L9)):*
> ```Cairo
> #[derive(Copy, Drop)]
> struct HashState {
>     state: felt252, 
> ```

Remove whitespace.
Why does this pass CI?



_Code quote:_
```Cairo
·
```
___
*[`corelib/src/pedersen.cairo` line 13 at r8](https://reviewable.io/reviews/starkware-libs/cairo/3714#-Na6kgDD5ot9IbmHtkIQ:-Na6kgDD5ot9IbmHtkIR:b-5f2b3g) ([raw file](https://github.com/starkware-libs/cairo/blob/ffd547dca57b566fe2fa6c19a3ac883cf3bdc194/corelib/src/pedersen.cairo#L13)):*
> ```Cairo
> 
> #[generate_trait]
> impl PedersenImpl of PedersenTrait {
> ```

Make a Default impl?

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3714)* status: all files reviewed, 3 unresolved discussions (waiting on @ArielElp, @ilyalesokhin-starkware, and @orizi)

___
*[`corelib/src/poseidon.cairo` line 24 at r8](https://reviewable.io/reviews/starkware-libs/cairo/3714#-Na6klgG5RkvsSeXGs57:-Na6klgG5RkvsSeXGs58:bjvlx6s) ([raw file](https://github.com/starkware-libs/cairo/blob/ffd547dca57b566fe2fa6c19a3ac883cf3bdc194/corelib/src/poseidon.cairo#L24)):*
> ```Cairo
> impl PoseidonImpl of PoseidonTrait {
>     /// Creates an initial state.
>     fn new() -> HashState {
> ```

Default impl

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3714)* status: all files reviewed, 6 unresolved discussions (waiting on @ArielElp, @ilyalesokhin-starkware, and @orizi)

___
*[`corelib/src/hash.cairo` line 20 at r8](https://reviewable.io/reviews/starkware-libs/cairo/3714#-Na6lfKO2qouMyJTx-t4:-Na6lfKP4syhB3s9PKdP:bo5g0o0) ([raw file](https://github.com/starkware-libs/cairo/blob/ffd547dca57b566fe2fa6c19a3ac883cf3bdc194/corelib/src/hash.cairo#L20)):*
> ```Cairo
>     /// Updates the hash state with the given value.
>     fn update_with(self: S, value: T) -> S;
> }
> ```

Consider adding a function to compute the entire hash off of a single value T. Does new(), update() and finalize().
___
*[`corelib/src/poseidon.cairo` line 43 at r8](https://reviewable.io/reviews/starkware-libs/cairo/3714#-Na6lLTVDm7KZK0BI6CJ:-Na6lLTVDm7KZK0BI6CK:b-nr9guy) ([raw file](https://github.com/starkware-libs/cairo/blob/ffd547dca57b566fe2fa6c19a3ac883cf3bdc194/corelib/src/poseidon.cairo#L43)):*
> ```Cairo
>     fn finalize(self: HashState) -> felt252 {
>         let (s0, s1) = if self.odd {
>             (self.s0, self.s1 + 1)
> ```

I tihnk it's more efficient to do everything inside the if. call hades_permutation and extract.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/storage` line 509 at r8](https://reviewable.io/reviews/starkware-libs/cairo/3714#-Na6mJF_89t7mkNyhFDE:-Na6mJF_89t7mkNyhFDF:b-ob4cy1) ([raw file](https://github.com/starkware-libs/cairo/blob/ffd547dca57b566fe2fa6c19a3ac883cf3bdc194/crates/cairo-lang-starknet/src/plugin/plugin_test_data/storage#L509)):*
> ```
>                 let base = pedersen::PedersenTrait::new(0x11ddb648d7a85d8ff1f89f86feb50fd8bd26a25e6837cff5c3c38d8c3a0bb93);
>                 let state = hash::HashStateExTrait::update_with(base, key);
>                 starknet::storage_base_address_from_felt252(hash::HashStateTrait::finalize(state))
> ```

Why not this?



_Suggestion:_
```
state.finalize()
```

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3714)* status: all files reviewed, 7 unresolved discussions (waiting on @ArielElp, @ilyalesokhin-starkware, and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3714#-Na6mYPT7Cn696Pxf2oX:-Na6mYPT7Cn696Pxf2oY:b1gnbix) (no related file):*
Poseidon is really cheap, so every overhead instruction hurts. Can you add some casm test to show the instruction before and after?

___

**Review by gilbens-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3714)* status: all files reviewed, 7 unresolved discussions (waiting on @ArielElp, @ilyalesokhin-starkware, @orizi, and @spapinistarkware)

___
*[`corelib/src/pedersen.cairo` line 9 at r8](https://reviewable.io/reviews/starkware-libs/cairo/3714#-Na6kWtG5kjy9oLbMAFb:-Na6n6983rlqbwOnjoAO:b-iyxxk8) ([raw file](https://github.com/starkware-libs/cairo/blob/ffd547dca57b566fe2fa6c19a3ac883cf3bdc194/corelib/src/pedersen.cairo#L9)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Remove whitespace.
Why does this pass CI?
</blockquote></details>

It's the foramtter behaviour when there is a `,` after the last element of the list. I need to add the ability to define different formatting for the last element.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3714)* status: 17 of 18 files reviewed, 7 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, @ilyalesokhin-starkware, and @spapinistarkware)

___
*[`corelib/src/hash.cairo` line 20 at r8](https://reviewable.io/reviews/starkware-libs/cairo/3714#-Na6lfKO2qouMyJTx-t4:-Na6oRO2DPTVRc1sg4f5:b9a6pz6) ([raw file](https://github.com/starkware-libs/cairo/blob/ffd547dca57b566fe2fa6c19a3ac883cf3bdc194/corelib/src/hash.cairo#L20)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Consider adding a function to compute the entire hash off of a single value T. Does new(), update() and finalize().
</blockquote></details>

the meaning of `new` is not totally clear in all cases (pedersen for example requires some base) - so let us postpone for now.
___
*[`corelib/src/pedersen.cairo` line 9 at r8](https://reviewable.io/reviews/starkware-libs/cairo/3714#-Na6kWtG5kjy9oLbMAFb:-Na6obxhCJldnDRTzrr6:bhlibi6) ([raw file](https://github.com/starkware-libs/cairo/blob/ffd547dca57b566fe2fa6c19a3ac883cf3bdc194/corelib/src/pedersen.cairo#L9)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

It's the foramtter behaviour when there is a `,` after the last element of the list. I need to add the ability to define different formatting for the last element.
</blockquote></details>

as gil said - not part of this PR.
___
*[`corelib/src/pedersen.cairo` line 13 at r8](https://reviewable.io/reviews/starkware-libs/cairo/3714#-Na6kgDD5ot9IbmHtkIQ:-Na6ogGUAT8UH4aWvTHw:bb3i9vx) ([raw file](https://github.com/starkware-libs/cairo/blob/ffd547dca57b566fe2fa6c19a3ac883cf3bdc194/corelib/src/pedersen.cairo#L13)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Make a Default impl?
</blockquote></details>

this does not have a default.
___
*[`corelib/src/poseidon.cairo` line 24 at r8](https://reviewable.io/reviews/starkware-libs/cairo/3714#-Na6klgG5RkvsSeXGs57:-Na6pO_I68fJ6eRffXIM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ffd547dca57b566fe2fa6c19a3ac883cf3bdc194/corelib/src/poseidon.cairo#L24)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Default impl
</blockquote></details>

Done.
___
*[`corelib/src/poseidon.cairo` line 43 at r8](https://reviewable.io/reviews/starkware-libs/cairo/3714#-Na6lLTVDm7KZK0BI6CJ:-Na6qYwP9gL9rKDLeWbe:bwgslld) ([raw file](https://github.com/starkware-libs/cairo/blob/ffd547dca57b566fe2fa6c19a3ac883cf3bdc194/corelib/src/poseidon.cairo#L43)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I tihnk it's more efficient to do everything inside the if. call hades_permutation and extract.
</blockquote></details>

Gas estimation was exactly the same - so i prefer this.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/storage` line 509 at r8](https://reviewable.io/reviews/starkware-libs/cairo/3714#-Na6mJF_89t7mkNyhFDE:-Na6pmJV4hxDxUw7b61q:b-qsy30u) ([raw file](https://github.com/starkware-libs/cairo/blob/ffd547dca57b566fe2fa6c19a3ac883cf3bdc194/crates/cairo-lang-starknet/src/plugin/plugin_test_data/storage#L509)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Why not this?
</blockquote></details>

adding `use` in this context is annoying - can easily cause multiple usages of the same item.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3714)* status: 17 of 18 files reviewed, 7 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, @ilyalesokhin-starkware, and @orizi)

___
*[`corelib/src/hash.cairo` line 20 at r8](https://reviewable.io/reviews/starkware-libs/cairo/3714#-Na6lfKO2qouMyJTx-t4:-Na6tVzy3f3M9TEKGf-H:b-cswdyf) ([raw file](https://github.com/starkware-libs/cairo/blob/ffd547dca57b566fe2fa6c19a3ac883cf3bdc194/corelib/src/hash.cairo#L20)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the meaning of `new` is not totally clear in all cases (pedersen for example requires some base) - so let us postpone for now.
</blockquote></details>

Ok, new suggestion. Add a new trait that depends on Default<HashState>. Then this becomes clear, but only if HashState has a default.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3714)* status: 17 of 18 files reviewed, 4 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, @ilyalesokhin-starkware, and @orizi)

___
*[`corelib/src/poseidon.cairo` line 43 at r8](https://reviewable.io/reviews/starkware-libs/cairo/3714#-Na6lLTVDm7KZK0BI6CJ:-Na6tqIA0zd6h3j_pL5V:bze3di5) ([raw file](https://github.com/starkware-libs/cairo/blob/ffd547dca57b566fe2fa6c19a3ac883cf3bdc194/corelib/src/poseidon.cairo#L43)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Gas estimation was exactly the same - so i prefer this.
</blockquote></details>

I don't see why this is true. Where can I see this gas estimation?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3714)* status: 17 of 18 files reviewed, 3 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, @ilyalesokhin-starkware, and @spapinistarkware)

___
*[`corelib/src/poseidon.cairo` line 43 at r8](https://reviewable.io/reviews/starkware-libs/cairo/3714#-Na6lLTVDm7KZK0BI6CJ:-Na6xRry9VP3grifl71A:b-kulnro) ([raw file](https://github.com/starkware-libs/cairo/blob/ffd547dca57b566fe2fa6c19a3ac883cf3bdc194/corelib/src/poseidon.cairo#L43)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I don't see why this is true. Where can I see this gas estimation?
</blockquote></details>

when running `./scripts/cairo_test.sh`

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3714)* status: 17 of 18 files reviewed, 3 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, @ilyalesokhin-starkware, and @orizi)

___
*[`corelib/src/poseidon.cairo` line 43 at r8](https://reviewable.io/reviews/starkware-libs/cairo/3714#-Na6lLTVDm7KZK0BI6CJ:-Na7-Fum8a3G7jCBSiWt:bas1j8v) ([raw file](https://github.com/starkware-libs/cairo/blob/ffd547dca57b566fe2fa6c19a3ac883cf3bdc194/corelib/src/poseidon.cairo#L43)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

when running `./scripts/cairo_test.sh`
</blockquote></details>

I still don't believe you

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3714)* status: 13 of 20 files reviewed, 3 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, @ilyalesokhin-starkware, and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3714#-Na6mYPT7Cn696Pxf2oX:-Na7IbzoBV32s4_LWoCV:b-896fix) (no related file):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Poseidon is really cheap, so every overhead instruction hurts. Can you add some casm test to show the instruction before and after?
</blockquote></details>

Done.

___
___
*[`corelib/src/hash.cairo` line 20 at r8](https://reviewable.io/reviews/starkware-libs/cairo/3714#-Na6lfKO2qouMyJTx-t4:-Na7IdsbDK1WHULyJlxw:b9101j8) ([raw file](https://github.com/starkware-libs/cairo/blob/ffd547dca57b566fe2fa6c19a3ac883cf3bdc194/corelib/src/hash.cairo#L20)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Ok, new suggestion. Add a new trait that depends on Default<HashState>. Then this becomes clear, but only if HashState has a default.
</blockquote></details>

maybe - but i still think would be more relevant for a later PR.
___
*[`corelib/src/poseidon.cairo` line 43 at r8](https://reviewable.io/reviews/starkware-libs/cairo/3714#-Na6lLTVDm7KZK0BI6CJ:-Na7IjI19NEY0WEhNvpT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ffd547dca57b566fe2fa6c19a3ac883cf3bdc194/corelib/src/poseidon.cairo#L43)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I still don't believe you
</blockquote></details>

Done.

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3714)* status: 11 of 20 files reviewed, 3 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, @ilyalesokhin-starkware, and @orizi)

___
*[`corelib/src/hash.cairo` line 20 at r8](https://reviewable.io/reviews/starkware-libs/cairo/3714#-Na6lfKO2qouMyJTx-t4:-NaH6IeQ2v4SsNRPy0sh:b-y7v20a) ([raw file](https://github.com/starkware-libs/cairo/blob/ffd547dca57b566fe2fa6c19a3ac883cf3bdc194/corelib/src/hash.cairo#L20)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe - but i still think would be more relevant for a later PR.
</blockquote></details>

You are making some of the code worse now. The experience of usinh a hash for simple cases is worstened. common things should be easy to do. like `hash(my_data)`.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 10 files at r1, 9 of 16 files at r2, 1 of 2 files at r3, 2 of 7 files at r10, 1 of 2 files at r11, 5 of 5 files at r12, 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3714#-:-NaH7Sq01YWBiSwg6IM2:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @ArielElp, @ilyalesokhin-starkware, and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3714#-NaH73S9BW0R3_X6kiYD:-NaH73S9BW0R3_X6kiYE:b-9mitz1) (no related file):*
Should this go to main or major version change?

___

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3714)* status: all files reviewed, 3 unresolved discussions (waiting on @ArielElp, @ilyalesokhin-starkware, and @orizi)

___
*[`corelib/src/poseidon.cairo` line 51 at r13](https://reviewable.io/reviews/starkware-libs/cairo/3714#-NaH8V4w3iNF85BVN_mV:-NaH8V4w3iNF85BVN_mW:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/189493581b14fb2554eec4ea1255a663c30222a2/corelib/src/poseidon.cairo#L51)):*
> ```Cairo
>         if self.odd {
>             let (r, _, _) = hades_permutation(self.s0, self.s1 + 1, self.s2);
>             r
> ```

.



_Suggestion:_
```Cairo
return r
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3714)* status: all files reviewed, 3 unresolved discussions (waiting on @ArielElp, @ilyalesokhin-starkware, and @spapinistarkware)

___
*[`corelib/src/hash.cairo` line 20 at r8](https://reviewable.io/reviews/starkware-libs/cairo/3714#-Na6lfKO2qouMyJTx-t4:-NaHQ7imDzC6M7KeWnky:b-rsjdfd) ([raw file](https://github.com/starkware-libs/cairo/blob/ffd547dca57b566fe2fa6c19a3ac883cf3bdc194/corelib/src/hash.cairo#L20)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

You are making some of the code worse now. The experience of usinh a hash for simple cases is worstened. common things should be easy to do. like `hash(my_data)`.
</blockquote></details>

hash "my_data" is something that never existed in cairo context.
so none of the current code is worse.
___
*[`corelib/src/poseidon.cairo` line 51 at r13](https://reviewable.io/reviews/starkware-libs/cairo/3714#-NaH8V4w3iNF85BVN_mV:-NaHQlxiBpoKyaMAQhzM:baroyi0) ([raw file](https://github.com/starkware-libs/cairo/blob/189493581b14fb2554eec4ea1255a663c30222a2/corelib/src/poseidon.cairo#L51)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

.
</blockquote></details>

this does not change the compilation - since the function is inlined. (checked)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3714)* status: all files reviewed, 3 unresolved discussions (waiting on @ArielElp, @ilyalesokhin-starkware, and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3714#-NaH73S9BW0R3_X6kiYD:-NaH_Y08Er5HfYAb_R1M:basyuoe) (no related file):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Should this go to main or major version change?
</blockquote></details>

To main IMO, as it doesn't break the central usages, and the fixes are easy.
(Especially after derive hash is added)

___

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 4 of 4 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3714)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp and @ilyalesokhin-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3714)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp and @ilyalesokhin-starkware)

**Comment by gaetbout** [comment]
GM,

Any ETA on when this will be merged?

K.R.,
G.

**Review by orizi — COMMENTED** [review]
today - just readding a LegacyHash trait so we won't break existing impls.

> Reviewed 5 of 6 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3714#-:-Najvf-J76FPGbKeypXa:b-19wvl5)* status: 19 of 20 files reviewed, all discussions resolved (waiting on @ArielElp, @ilyalesokhin-starkware, and @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 6 files at r16.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3714)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp and @ilyalesokhin-starkware)

**Pull request merged**
