### PR TITLE
Adding bitwise to generic uint ops.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3411)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3411)* status: 2 of 14 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3411#-NYCO2lq4mDaiJbfWIQc:-NYCO2lrDPx1XoITDFMD:b-4ljbwq) (no related file):*
You are removing functions from sierra, right?
1. Should this be targeted to a sierra breaking branch?
2. If so, why did't the script catch it?

___

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3411)* status: 2 of 14 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3411#-NYCO2lq4mDaiJbfWIQc:-NYCOOiF7rmZxviWKe0m:b2leaft) (no related file):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

You are removing functions from sierra, right?
1. Should this be targeted to a sierra breaking branch?
2. If so, why did't the script catch it?
</blockquote></details>

Nevermind

___

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3411#-:-NYCOUlQ2SA3Kc4Qc4_8:bnfp4nl)* status: 2 of 14 files reviewed, all discussions resolved

**Review by orizi — COMMENTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3411)* status: 6 of 14 files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 8 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3411)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
