### PR TITLE
Add get-lowering utility.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4926)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4926)* status: 2 of 8 files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/bin/get-lowering/src/main.rs` line 3 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4926#-NrB9Ykg5eDvSWAhGJgk:-NrB9Ykg5eDvSWAhGJgl:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8a4c5ad5f150429be694d57e386b43be1ebe65a3/crates/bin/get-lowering/src/main.rs#L3)):*
> ```XML
> use std::ops::Deref;
> use std::path::{Path, PathBuf};
> use std::{fmt, fs};
> ```





_Suggestion:_
```XML
//! Internal debug utility for printing lowering phases.

use std::ops::Deref;
use std::path::{Path, PathBuf};
use std::{fmt, fs};
```
___
*[`crates/bin/get-lowering/src/main.rs` line 39 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4926#-NrB9PV84r4AZez6VITR:-NrB9PV84r4AZez6VITS:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8a4c5ad5f150429be694d57e386b43be1ebe65a3/crates/bin/get-lowering/src/main.rs#L39)):*
> ```XML
> /// Tests that `PhasesFormatter` is consistent with the lowering phases.
> fn test_lowering_consistency() {
>     let db_val = RootDatabase::builder()
> ```





_Suggestion:_
```XML
/// Tests that `PhasesFormatter` is consistent with the lowering phases.
#[test]
fn test_lowering_consistency() {
    let db_val = RootDatabase::builder()
```
___
*[`crates/bin/get-lowering/src/main.rs` line 56 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4926#-NrB9TOCDKA4rDqYhqPw:-NrB9TOCDKA4rDqYhqPx:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8a4c5ad5f150429be694d57e386b43be1ebe65a3/crates/bin/get-lowering/src/main.rs#L56)):*
> ```XML
> ///     cargo run --bin get-lowering corelib/ core::poseidon::poseidon_hash_span
> ///
> /// Exits with 0/1 if the input is formatted correctly/incorrectly.
> ```





_Suggestion:_
```XML
/// Prints the lowering of a concrete function:
///
/// Usage example:
///     cargo run --bin get-lowering corelib/ core::poseidon::poseidon_hash_span
///
/// Exits with 0/1 if the input is formatted correctly/incorrectly.
```
___
*[`crates/bin/get-lowering/src/main.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4926#-NrBAKWR0CBE0ZWLhfrJ:-NrBAKWR0CBE0ZWLhfrK:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8a4c5ad5f150429be694d57e386b43be1ebe65a3/crates/bin/get-lowering/src/main.rs#L62)):*
> ```XML
>     /// The crate to compile.
>     path: PathBuf,
>     // The functions fully qualified path.
> ```





_Suggestion:_
```XML
    // The concrete function's fully qualified path.
```
___
*[`crates/bin/get-lowering/src/main.rs` line 72 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4926#-NrBAHuNBJqm4Pbh0LQo:-NrBAHuNBJqm4Pbh0LQp:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/8a4c5ad5f150429be694d57e386b43be1ebe65a3/crates/bin/get-lowering/src/main.rs#L72)):*
> ```XML
> }
> 
> struct PhasesFormatter<'a> {
> ```

doc
___
*[`crates/bin/get-lowering/src/main.rs` line 136 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4926#-NrBAGwK8y-y3IPKbwDn:-NrBAGwK8y-y3IPKbwDo:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/8a4c5ad5f150429be694d57e386b43be1ebe65a3/crates/bin/get-lowering/src/main.rs#L136)):*
> ```XML
> }
> 
> fn get_func_id_by_name(
> ```

doc
___
*[`crates/bin/get-lowering/src/main.rs` line 184 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4926#-NrBAEcGBBzydlJbFo2r:-NrBAEcGBBzydlJbFo2s:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/8a4c5ad5f150429be694d57e386b43be1ebe65a3/crates/bin/get-lowering/src/main.rs#L184)):*
> ```XML
> }
> 
> fn format_phases_by_name(
> ```

doc

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4926)* status: 2 of 8 files reviewed, 7 unresolved discussions (waiting on @orizi)

___
*[`crates/bin/get-lowering/src/main.rs` line 39 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4926#-NrB9PV84r4AZez6VITR:-NrBGGNB6r_24I6qwKtd:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8a4c5ad5f150429be694d57e386b43be1ebe65a3/crates/bin/get-lowering/src/main.rs#L39)):*
> ```XML
> /// Tests that `PhasesFormatter` is consistent with the lowering phases.
> fn test_lowering_consistency() {
>     let db_val = RootDatabase::builder()
> ```

Done.
___
*[`crates/bin/get-lowering/src/main.rs` line 56 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4926#-NrB9TOCDKA4rDqYhqPw:-NrBGT7HB5gljT1_EhSI:b-cvsltt) ([raw file](https://github.com/starkware-libs/cairo/blob/8a4c5ad5f150429be694d57e386b43be1ebe65a3/crates/bin/get-lowering/src/main.rs#L56)):*
> ```XML
> ///     cargo run --bin get-lowering corelib/ core::poseidon::poseidon_hash_span
> ///
> /// Exits with 0/1 if the input is formatted correctly/incorrectly.
> ```

Done.

I think the 'concrete' is not nessiary.
___
*[`crates/bin/get-lowering/src/main.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4926#-NrBAKWR0CBE0ZWLhfrJ:-NrBGjWaBiLDj0sld-P8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8a4c5ad5f150429be694d57e386b43be1ebe65a3/crates/bin/get-lowering/src/main.rs#L62)):*
> ```XML
>     /// The crate to compile.
>     path: PathBuf,
>     // The functions fully qualified path.
> ```

Done.
___
*[`crates/bin/get-lowering/src/main.rs` line 72 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4926#-NrBAHuNBJqm4Pbh0LQo:-NrBGovp6ZfGEXktUy7Q:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8a4c5ad5f150429be694d57e386b43be1ebe65a3/crates/bin/get-lowering/src/main.rs#L72)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/bin/get-lowering/src/main.rs` line 136 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4926#-NrBAGwK8y-y3IPKbwDn:-NrBGxSu060ufOmRGRv6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8a4c5ad5f150429be694d57e386b43be1ebe65a3/crates/bin/get-lowering/src/main.rs#L136)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/bin/get-lowering/src/main.rs` line 184 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4926#-NrBAEcGBBzydlJbFo2r:-NrBH8DyD2xTbueFVjhw:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8a4c5ad5f150429be694d57e386b43be1ebe65a3/crates/bin/get-lowering/src/main.rs#L184)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4926)* status: all files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/bin/get-lowering/Cargo.toml` line 20 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4926#-NrBIO856UstF6Sz0tg2:-NrBIO856UstF6Sz0tg3:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8aa2787e41dc6bc7cc691a386d664a0edd81a2ed/crates/bin/get-lowering/Cargo.toml#L20)):*
> ```TOML
> cairo-lang-starknet = { path = "../../cairo-lang-starknet", version = "2.5.0" }
> cairo-lang-semantic = { path = "../../cairo-lang-semantic", version = "2.5.0" }
> cairo-lang-utils = { path = "../../cairo-lang-utils", version = "2.5.4" }
> ```





_Suggestion:_
```TOML
cairo-lang-compiler = { path = "../../cairo-lang-compiler", version = "2.5.4" }
cairo-lang-debug = { path = "../../cairo-lang-debug", version = "2.5.4" }
cairo-lang-defs = { path = "../../cairo-lang-defs", version = "2.5.4" }
cairo-lang-filesystem = { path = "../../cairo-lang-filesystem", version = "2.5.4" }
cairo-lang-lowering = { path = "../../cairo-lang-lowering", version = "2.5.4" }
cairo-lang-starknet = { path = "../../cairo-lang-starknet", version = "2.5.4" }
cairo-lang-semantic = { path = "../../cairo-lang-semantic", version = "2.5.4" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "2.5.4" }
```
___
*[`crates/bin/get-lowering/src/main.rs` line 66 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4926#-NrBIW7W86cUhX4f8t5-:-NrBIW7W86cUhX4f8t50:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8aa2787e41dc6bc7cc691a386d664a0edd81a2ed/crates/bin/get-lowering/src/main.rs#L66)):*
> ```XML
>     /// The crate to compile.
>     path: PathBuf,
>     // The concrete functions fully qualified path, if None print all functions.
> ```





_Suggestion:_
```XML
    /// The concrete functions fully qualified path, if None print all functions.
```
___
*[`crates/bin/get-lowering/src/main.rs` line 181 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4926#-NrBIc257R6rO9G1wDqO:-NrBIc257R6rO9G1wDqP:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/8aa2787e41dc6bc7cc691a386d664a0edd81a2ed/crates/bin/get-lowering/src/main.rs#L181)):*
> ```XML
> }
> 
> fn get_func_id_by_name(
> ```

doc
___
*[`crates/bin/get-lowering/src/main.rs` line 201 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4926#-NrBIb7_2l0YRCKB-Nhj:-NrBIb7_2l0YRCKB-Nhk:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8aa2787e41dc6bc7cc691a386d664a0edd81a2ed/crates/bin/get-lowering/src/main.rs#L201)):*
> ```XML
> 
> // Given a function name and list of crates, returns a string representing the lowering phases of
> // the function.
> ```





_Suggestion:_
```XML
/// Given a function name and list of crates, returns a string representing the lowering phases of
/// the function.
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4926)* status: 6 of 8 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/bin/get-lowering/Cargo.toml` line 20 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4926#-NrBIO856UstF6Sz0tg2:-NrBVO9a4mg-GzjL-xF-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8aa2787e41dc6bc7cc691a386d664a0edd81a2ed/crates/bin/get-lowering/Cargo.toml#L20)):*
> ```TOML
> cairo-lang-starknet = { path = "../../cairo-lang-starknet", version = "2.5.0" }
> cairo-lang-semantic = { path = "../../cairo-lang-semantic", version = "2.5.0" }
> cairo-lang-utils = { path = "../../cairo-lang-utils", version = "2.5.4" }
> ```

Done.
___
*[`crates/bin/get-lowering/src/main.rs` line 66 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4926#-NrBIW7W86cUhX4f8t5-:-NrBV6y0CMrQOPHONkq4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8aa2787e41dc6bc7cc691a386d664a0edd81a2ed/crates/bin/get-lowering/src/main.rs#L66)):*
> ```XML
>     /// The crate to compile.
>     path: PathBuf,
>     // The concrete functions fully qualified path, if None print all functions.
> ```

Done.
___
*[`crates/bin/get-lowering/src/main.rs` line 181 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4926#-NrBIc257R6rO9G1wDqO:-NrBV4h43zrtZtJyHvBC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8aa2787e41dc6bc7cc691a386d664a0edd81a2ed/crates/bin/get-lowering/src/main.rs#L181)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/bin/get-lowering/src/main.rs` line 201 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4926#-NrBIb7_2l0YRCKB-Nhj:-NrBV5194PrBVEg_aI-o:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8aa2787e41dc6bc7cc691a386d664a0edd81a2ed/crates/bin/get-lowering/src/main.rs#L201)):*
> ```XML
> 
> // Given a function name and list of crates, returns a string representing the lowering phases of
> // the function.
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4926#-:-NrB_4Zi786DggfCe7oI:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
