### PR TITLE
Added more `starknet::interface` code generation fixes.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #4129
- #4119 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4119)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4119)* status: all files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4119#-Nesxh7h-7ak1_QdgVwz:-Nesxh7i2mPzrOnIEV_V:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/dbbe1a1c56918ffdb59ae3361ef1aafde5f3651d/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L119)):*
> ```XML
>                     diagnostics.push(PluginDiagnostic {
>                         message: "`starknet::interface` function first parameter must be a \
>                                   reference to trait's generic parameter or a snapshot of it."
> ```





_Suggestion:_
```XML
rence to the trait's gen
```
___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4119#-NesxooA37uIinD0vfK3:-NesxooA37uIinD0vfK4:b-3qnc53) ([raw file](https://github.com/starkware-libs/cairo/blob/dbbe1a1c56918ffdb59ae3361ef1aafde5f3651d/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L132)):*
> ```XML
>                         diagnostics.push(PluginDiagnostic {
>                             message: "`starknet::interface` function non-first `ref` parameters \
>                                       are not supported."
> ```

suggestion



_Suggestion:_
```XML
                            message: "`starknet::interface` functions don't support `ref` parameters other than the first one."
```
___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 142 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4119#-NesyZ3-DcfTVtGdw_rt:-NesyZ3-DcfTVtGdw_ru:bjnx72j) ([raw file](https://github.com/starkware-libs/cairo/blob/dbbe1a1c56918ffdb59ae3361ef1aafde5f3651d/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L142)):*
> ```XML
>                         diagnostics.push(PluginDiagnostic {
>                             message: "`starknet::interface` function non-first parameters cannot \
>                                       depend on the trait's generic param type."
> ```

if you accept the suggestion above, better to make this phrasing similar.



_Code quote:_
```XML
                            message: "`starknet::interface` function non-first parameters cannot \
                                      depend on the trait's generic param type."
```
___
*[`crates/cairo-lang-starknet/src/plugin/utils.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4119#-Net-F583qjo7yyCGohF:-Net-F583qjo7yyCGohG:b-avefx3) ([raw file](https://github.com/starkware-libs/cairo/blob/dbbe1a1c56918ffdb59ae3361ef1aafde5f3651d/crates/cairo-lang-starknet/src/plugin/utils.rs#L104)):*
> ```XML
>                 head.is_empty() && arg_segment.ident(db).text(db) == identifier
>             }
>             ast::PathSegment::WithGenericArgs(with_generics) => {
> ```

also need to check with_generics.ident in this arm.
___
*[`crates/cairo-lang-starknet/src/plugin/utils.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4119#-Net-umF2dF_ps4XFOPf:-Net-umF2dF_ps4XFOPg:b-nvon8y) ([raw file](https://github.com/starkware-libs/cairo/blob/dbbe1a1c56918ffdb59ae3361ef1aafde5f3651d/crates/cairo-lang-starknet/src/plugin/utils.rs#L151)):*
> ```XML
>                 .iter()
>                 .any(|expr| expr.is_dependent_type(db, identifier)),
>             _ => false,
> ```

also need to check parenthesized. I think that also inline macro?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4119)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/utils.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4119#-Net-F583qjo7yyCGohF:-Nevad0P1ZH5lVIr8kKB:b-gwuikr) ([raw file](https://github.com/starkware-libs/cairo/blob/9d0954851668a27bd27cc8cddd4019eb58dbfcdf/crates/cairo-lang-starknet/src/plugin/utils.rs#L104)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

also need to check with_generics.ident in this arm.
</blockquote></details>

we check the generic args - the type cannot be used as part of the path.
___
*[`crates/cairo-lang-starknet/src/plugin/utils.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4119#-Net-umF2dF_ps4XFOPf:-NevaT1D3sgMex6ihYLu:bdoy80b) ([raw file](https://github.com/starkware-libs/cairo/blob/9d0954851668a27bd27cc8cddd4019eb58dbfcdf/crates/cairo-lang-starknet/src/plugin/utils.rs#L151)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

also need to check parenthesized. I think that also inline macro?
</blockquote></details>

these won't be present in a valid type expression.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4119)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/utils.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4119#-Net-umF2dF_ps4XFOPf:-NfFMEq06RAP35pHPFBY:b-qzmve3) ([raw file](https://github.com/starkware-libs/cairo/blob/9d0954851668a27bd27cc8cddd4019eb58dbfcdf/crates/cairo-lang-starknet/src/plugin/utils.rs#L151)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

these won't be present in a valid type expression.
</blockquote></details>

why not?
not sure about parenthesized, but e.g. if I have a inline macro that adds '@', wouldn't `fn foo(x: snap!(T))` work?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4119)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/utils.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4119#-Net-umF2dF_ps4XFOPf:-NfFQH5yAEXoNJCzeila:b-lfu6o) ([raw file](https://github.com/starkware-libs/cairo/blob/9d0954851668a27bd27cc8cddd4019eb58dbfcdf/crates/cairo-lang-starknet/src/plugin/utils.rs#L151)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

why not?
not sure about parenthesized, but e.g. if I have a inline macro that adds '@', wouldn't `fn foo(x: snap!(T))` work?
</blockquote></details>

we don't actually know what this possibly does - it can decide to be whatever - i feel that case is future proofing something we are yet to fully understand.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4119)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/utils.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4119#-Net-umF2dF_ps4XFOPf:-NfFZoon6Gaq8VcDis4H:b-5x1qme) ([raw file](https://github.com/starkware-libs/cairo/blob/9d0954851668a27bd27cc8cddd4019eb58dbfcdf/crates/cairo-lang-starknet/src/plugin/utils.rs#L151)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

we don't actually know what this possibly does - it can decide to be whatever - i feel that case is future proofing something we are yet to fully understand.
</blockquote></details>

Maybe just simply don't allow inline macros in there?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4119)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/utils.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4119#-Net-umF2dF_ps4XFOPf:-NfFaxgaEsMvFaRQd5Lf:b-rz2t5d) ([raw file](https://github.com/starkware-libs/cairo/blob/9d0954851668a27bd27cc8cddd4019eb58dbfcdf/crates/cairo-lang-starknet/src/plugin/utils.rs#L151)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Maybe just simply don't allow inline macros in there?
</blockquote></details>

We already do, as there's no relevant inline macro writable in types

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4119#-:-NfG6vNC-V1xHaXhACQO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
