### PR TITLE
Change EC add, sub and mul to work with EcPoint.

### PR DESCRIPTION
**Pull request by liorgold2**
commit-id:bab0b1aa

---

**Stack**:
- #1950
- #1949 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1949#-:-NMt70ej7XRmuCHPUwkQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1949)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`corelib/lib.cairo` line 113 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1949#-NMtmO7dENMxH2EmhlGJ:-NMtmO7eCDACDp_MbvfG:b-h5ht3r) ([raw file](https://github.com/starkware-libs/cairo/blob/3b6a0e01613c67e308892b1646314af6ff9ae1f9/corelib/lib.cairo#L113)):*
> ```Cairo
> extern fn unwrap_nz<T>(a: NonZero::<T>) -> T nopanic;
> 
> trait ToBool<T> {
> ```

Assuming this is not just for nz-result, move the trait to the traits module

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1949)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/lib.cairo` line 113 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1949#-NMtmO7dENMxH2EmhlGJ:-NMwh1oU7Z5_7GSaNqQo:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fa7139660a3e0bccf097483454d167d559a8d1fb/corelib/lib.cairo#L113)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Assuming this is not just for nz-result, move the trait to the traits module
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1949#-:-NMwhFo83rL1Ff-JVB5R:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1949)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
