### PR TITLE
Changed span pointed to by wrong number of args diags.

### LINKED ISSUE #5430: feat: better error reporting with wrong use of unwrap
# Feature Request

**Describe the Feature Request**

I have a simple piece of code where I made an error:

```rust
    pub fn foo() -> ContractAddress {
        0x3240581234501345134513451341345134512451234521.try_into().unwrap('no')
    }
```

I should have used `except` instead of `unwrap`, made the error while copy-pasting stuff and generally focusing on fixing something else. It took me a while to spot the mistake for two reasons.

This is how the error is reported by the compiler:

```
error: Wrong number of arguments. Expected 1, found: 2
 --> /Users/m/projects/foo/src/constants.cairo:87:9
        0x3240581234501345134513451341345134512451234521.try_into().unwrap('no')
        ^**********************************************************************^
```

And in VSCode:

Screenshot 2024-04-17 at 11 55 51

**Describe Preferred Solution**

None of the hints above pinpoint the error on the wrong use of `unwrap`. Quite contrary, they mislead me.

It would be better if the red squiggly lines were only under the unwrap('no') part of the code and if the error coming from the compiler would look something like this:

```
error: Wrong number of arguments. Expected 0, found: 1
 --> /Users/m/projects/foo/src/constants.cairo:87:9
        0x3240581234501345134513451341345134512451234521.try_into().unwrap('no')
                                                                   ^***********^
```

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [x] No

### PR DESCRIPTION
**Pull request by orizi**
Closes #5430

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5436)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
lgtm if we decide to point to the args (it is indeed consistent), but maybe it should be to the last segment of the function call?

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5436#-:-Nvi3yHT1OIzvDMy611_:bu9vu9j)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
updated to use the last part of the path.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5436#-:-Nvk-bJS28yR7eIowLFX:b-ii31ah)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Comment by mkaput** [comment]
For reference, intellij rust is highlighting the affected function **and** the extra arguments

image

The main error reports the function, while there are notes attached that report individual arguments

**Review by gilbens-starkware — APPROVED** [review]
The intellij version looks to me like two different errors.

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5436#-:-Nvk2Na30B6RZmuLdJA1:b2qx2fz)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5436#-:-Nvk36tODe1PIqPD6jx9:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 5 files at r2, 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5436)* status: 4 of 7 files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
