### PR TITLE
Add const to defs.

### PR DESCRIPTION
**Pull request by liorgold2**
commit-id:fd379afa

---

**Stack**:
- #1757
- #1758
- #1751
- #1750 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1750#-:-NLa5lND80uQh1UsBY2Z:bnfp4nl)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1750#-:-NLaPzBe7y5kHwDSivgw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 3 of 6 files at r1, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1750#-:-NLaS9Kz3pIhtQ1_vVGi:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-defs/src/db.rs` line 30 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1750#-NLaQMEWDXmIT4IZagt8:-NLaQMEWDXmIT4IZagt9:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/265b87cb88060dc8a06a1d2c58ea13c92c9208cb/crates/cairo-lang-defs/src/db.rs#L30)):*
> ```XML
> {
>     #[salsa::interned]
>     fn intern_const(&self, id: ConstLongId) -> ConstId;
> ```





_Suggestion:_
```XML
    fn intern_constant(&self, id: ConstantLongId) -> ConstantId;
    #[salsa::interned]
```
___
*[`crates/cairo-lang-defs/src/db.rs` line 234 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1750#-NLaQr3J2vSj0REzdNDG:-NLaQr3J2vSj0REzdNDH:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/265b87cb88060dc8a06a1d2c58ea13c92c9208cb/crates/cairo-lang-defs/src/db.rs#L234)):*
> ```XML
> #[derive(Clone, Debug, Default, PartialEq, Eq)]
> pub struct ModuleData {
>     constants: OrderedHashMap<ConstId, ast::ItemConst>,
> ```





_Suggestion:_
```XML
constants: OrderedHashMap<ConstId, ast::ItemConstant>,
```
___
*[`crates/cairo-lang-defs/src/db.rs` line 331 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1750#-NLaQm_sBoRUBKb_jbIU:-NLaQm_sBoRUBKb_jbIV:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/265b87cb88060dc8a06a1d2c58ea13c92c9208cb/crates/cairo-lang-defs/src/db.rs#L331)):*
> ```XML
>             }
>             match item_ast {
>                 ast::Item::Const(const_) => {
> ```





_Suggestion:_
```XML
ast::Item::Constant(constant)
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1750)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-defs/src/db.rs` line 30 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1750#-NLaQMEWDXmIT4IZagt8:-NLa_FDd3k1k-l4MndEn:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/265b87cb88060dc8a06a1d2c58ea13c92c9208cb/crates/cairo-lang-defs/src/db.rs#L30)):*
> ```XML
> {
>     #[salsa::interned]
>     fn intern_const(&self, id: ConstLongId) -> ConstId;
> ```

Done
___
*[`crates/cairo-lang-defs/src/db.rs` line 234 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1750#-NLaQr3J2vSj0REzdNDG:-NLa_qBqCmCPgGyCIT-J:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/265b87cb88060dc8a06a1d2c58ea13c92c9208cb/crates/cairo-lang-defs/src/db.rs#L234)):*
> ```XML
> #[derive(Clone, Debug, Default, PartialEq, Eq)]
> pub struct ModuleData {
>     constants: OrderedHashMap<ConstId, ast::ItemConst>,
> ```

Done
___
*[`crates/cairo-lang-defs/src/db.rs` line 331 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1750#-NLaQm_sBoRUBKb_jbIU:-NLa_rZt2OFmX_K4e5QJ:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/265b87cb88060dc8a06a1d2c58ea13c92c9208cb/crates/cairo-lang-defs/src/db.rs#L331)):*
> ```XML
>             }
>             match item_ast {
>                 ast::Item::Const(const_) => {
> ```

Done

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 12 of 12 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1750)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
