### PR TITLE
Added .lookup_intern() methods to all IDs

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5424)

### CODE REVIEW

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 47 of 47 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5424)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-utils/src/lib.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5424#-NvaTPlqA2QV5F-AKrpE:-NvaTPlqA2QV5F-AKrpF:b-jya25h) ([raw file](https://github.com/starkware-libs/cairo/blob/386b09cd590e4c518f3583e53d4dc005c3368bb5/crates/cairo-lang-utils/src/lib.rs#L167)):*
> ```XML
> //         *self
> //     }
> // }
> ```

removed till this is wip, right?

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5424)* status: 55 of 57 files reviewed, 1 unresolved discussion (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-utils/src/lib.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5424#-NvaTPlqA2QV5F-AKrpE:-NvbTmpI19nl1fMN3MtO:bg4p478) ([raw file](https://github.com/starkware-libs/cairo/blob/386b09cd590e4c518f3583e53d4dc005c3368bb5/crates/cairo-lang-utils/src/lib.rs#L167)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

removed till this is wip, right?
</blockquote></details>

Thanks, it was a leftover

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5424#-:-Nvba8eTC4hLx1iUeyGU:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)

**Review by mkaput — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5424)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
