### PR TITLE
Semantic: Support named arguments.

### PR DESCRIPTION
**Pull request by liorgold2**
commit-id:fbe032e0

---

**Stack**:
- #1669
- #1668 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1668#-:-NL5_ApxESPV8KJ7x7eY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1668)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1077 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1668#-NLL-T2H-nJwKaa6hP3x:-NLL-T2H-nJwKaa6hP3y:b6z5jzc) ([raw file](https://github.com/starkware-libs/cairo/blob/408afe8e740e3b067f395a7e7dc5a1af429bc21e/crates/cairo-lang-semantic/src/expr/compute.rs#L1077)):*
> ```XML
>     // Indicates whether we saw a named argument. Used to report a diagnostic if an unnamed argument
>     // will follow it.
>     let mut saw_named_arguments: bool = false;
> ```

`saw` is ambiguous :carpentry_saw: 



_Suggestion:_
```XML
seen
```

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1668)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1092 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1668#-NLL8vMV14iBI0d3fN1y:-NLL8vMV14iBI0d3fN1z:b-zef0db) ([raw file](https://github.com/starkware-libs/cairo/blob/408afe8e740e3b067f395a7e7dc5a1af429bc21e/crates/cairo-lang-semantic/src/expr/compute.rs#L1092)):*
> ```XML
>                     name_terminal.stable_ptr().untyped(),
>                     NamedArgumentMismatch { expected: param.name.clone(), found: name },
>                 );
> ```

If it's the wrong parameter, I think you should exit and give MissingExpr, so we won't give more type diagnostics on it.

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1668)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1077 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1668#-NLL-T2H-nJwKaa6hP3x:-NLRmPQgDV9wb0kDk04_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/408afe8e740e3b067f395a7e7dc5a1af429bc21e/crates/cairo-lang-semantic/src/expr/compute.rs#L1077)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

`saw` is ambiguous :carpentry_saw: 
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1092 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1668#-NLL8vMV14iBI0d3fN1y:-NLRmRQZ38sjiaiklXea:b-7wtgln) ([raw file](https://github.com/starkware-libs/cairo/blob/408afe8e740e3b067f395a7e7dc5a1af429bc21e/crates/cairo-lang-semantic/src/expr/compute.rs#L1092)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

If it's the wrong parameter, I think you should exit and give MissingExpr, so we won't give more type diagnostics on it.
</blockquote></details>

Done. Currently not continuing at all if there's a name mismatch. If you want something else, let's discuss and do it in a separate PR.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1668)* status: all files reviewed, 3 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1100 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1668#-NLSCcGY6CDx32wZaYa_:-NLSCcGY6CDx32wZaYaa:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/be7eeddb15f23605c6a50f3fccd0ec462764fc8f/crates/cairo-lang-semantic/src/expr/compute.rs#L1100)):*
> ```XML
> }
> 
> //// Checks the correctness of the named arguments, and outputs diagnostics on errors.
> ```





_Suggestion:_
```XML
/// Checks the correctness of the named arguments, and outputs diagnostics on errors.
```

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1668#-:-NLUnvvs-mbgsb5p5NP4:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/function_call` line 8 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1668#-NLUjq5j4FBjkErMpqmW:-NLUjq5j4FBjkErMpqmX:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/be7eeddb15f23605c6a50f3fccd0ec462764fc8f/crates/cairo-lang-semantic/src/expr/test_data/function_call#L8)):*
> ```
> //! > function
> fn foo() {
>     // Valid (excect for one wrong type).
> ```





_Suggestion:_
```
except
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1668)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1100 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1668#-NLSCcGY6CDx32wZaYa_:-NLUwYgL8fgL_5RGE2UO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/be7eeddb15f23605c6a50f3fccd0ec462764fc8f/crates/cairo-lang-semantic/src/expr/compute.rs#L1100)):*
> ```XML
> }
> 
> //// Checks the correctness of the named arguments, and outputs diagnostics on errors.
> ```

Done.



_Code quote (from -- commits):_
```
be7eedd
```

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1668)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
