### PR TITLE
shorten libfunc names.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3279)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3279)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3279#-NWmAU8r6Trqp_OHnRUW:-NWmAU8r6Trqp_OHnRUX:bmcw135) (no related file):*
remove unrelated stuff.

+ are we sure having long names is an actual issue?

___

**Comment by ilyalesokhin-starkware** [comment]
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove unrelated stuff.

+ are we sure having long names is an actual issue?
</blockquote></details>

No, @liorgold2  suggested we shorten the names.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3279)* status: 8 of 9 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @liorgold2)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/simple_syscall.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3279#-NWqTy8H2d11ip2gvh3i:-NWqTy8H2d11ip2gvh3j:b-89vkgm) ([raw file](https://github.com/starkware-libs/cairo/blob/7606a8da15938247e3bf12da7d12e3a6feb9c204/crates/cairo-lang-sierra/src/extensions/modules/starknet/simple_syscall.rs#L19)):*
> ```XML
> pub struct StorageReadLibfunc {}
> impl NoGenericArgsGenericLibfunc for StorageReadLibfunc {
>     const ID: GenericLibfuncId = GenericLibfuncId::new_inline("simple_syscall");
> ```

How is this related to this PR?
___
*[`crates/cairo-lang-starknet/src/felt252_serde_test.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3279#-NWqSruO7mIxqdwDyD6y:-NWqSruP81XlxIHnCWPj:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7606a8da15938247e3bf12da7d12e3a6feb9c204/crates/cairo-lang-starknet/src/felt252_serde_test.rs#L55)):*
> ```XML
> fn test_long_ids() {
>     for libfunc_id in SERDE_SUPPORTED_LONG_IDS.iter() {
>         assert!(libfunc_id.len() > 31, "serde long ids should be longer than 31 bytes.");
> ```





_Suggestion:_
```XML
assert!(libfunc_id.len() > 31, "serde long ids shouldn't be longer than 31 bytes.");
```
___
*[`crates/cairo-lang-starknet/src/allowed_libfuncs_lists/experimental_v0.1.0.json` line 82 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3279#-NWqT1mr0PoRi30KFNsP:-NWqT1mr0PoRi30KFNsQ:b-voip34) ([raw file](https://github.com/starkware-libs/cairo/blob/7606a8da15938247e3bf12da7d12e3a6feb9c204/crates/cairo-lang-starknet/src/allowed_libfuncs_lists/experimental_v0.1.0.json#L82)):*
> ```JSON
>         "secp256k1_ec_pt_from_x_syscall",
>         "secp256k1_ec_mul_syscall",
>         "secp256k1_ec_new_syscall",
> ```

I suggest removing the "_ec" from all. This is better then point->pt IMO, and both shorten them by 3.



_Code quote:_
```JSON
        "secp256k1_ec_add_syscall",
        "secp256k1_ec_get_xy_syscall",
        "secp256k1_ec_pt_from_x_syscall",
        "secp256k1_ec_mul_syscall",
        "secp256k1_ec_new_syscall",
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/felt252_serde_test.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3279#-NWqSruO7mIxqdwDyD6y:-NX5Tbct2dJNIS1cyB8l:b-gh9xvm) ([raw file](https://github.com/starkware-libs/cairo/blob/7606a8da15938247e3bf12da7d12e3a6feb9c204/crates/cairo-lang-starknet/src/felt252_serde_test.rs#L55)):*
> ```XML
> fn test_long_ids() {
>     for libfunc_id in SERDE_SUPPORTED_LONG_IDS.iter() {
>         assert!(libfunc_id.len() > 31, "serde long ids should be longer than 31 bytes.");
> ```

I'm going over the SERDE_SUPPORTED_LONG_IDS here, they should be longer.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3279)* status: 1 of 10 files reviewed, 3 unresolved discussions (waiting on @liorgold2 and @yuvalsw)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/simple_syscall.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3279#-NWqTy8H2d11ip2gvh3i:-NX5Tv2fArgqCPDnjESG:b-81taoq) ([raw file](https://github.com/starkware-libs/cairo/blob/7606a8da15938247e3bf12da7d12e3a6feb9c204/crates/cairo-lang-sierra/src/extensions/modules/starknet/simple_syscall.rs#L19)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

How is this related to this PR?
</blockquote></details>

reverted.

**Review by orizi — APPROVED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3279)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @yuvalsw)

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3279)* status: all files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @liorgold2)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 593 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3279#-NX5mIx_8umLa-e3wktI:-NX5mIx_8umLa-e3wktJ:bx3kge4) ([raw file](https://github.com/starkware-libs/cairo/blob/59fa22726694421d2c269454fd32671286ff0ca0/crates/cairo-lang-runner/src/casm_run/mod.rs#L593)):*
> ```XML
>                 keccak(gas_counter, system_buffer.next_arr()?)
>             }),
>             "Secp256k1EcNew" => execute_handle_helper(&mut |system_buffer, gas_counter| {
> ```

How about removing the `Ec` from the selectors too? 



_Code quote:_
```XML
Secp256k1EcNew
```
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 629 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3279#-NX5mSOcCk_Gt2GNNxrD:-NX5mSOd7-1RQA9kZUnp:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/59fa22726694421d2c269454fd32671286ff0ca0/crates/cairo-lang-runner/src/casm_run/mod.rs#L629)):*
> ```XML
>             "Secp256k1EcGetCoordinates" => {
>                 execute_handle_helper(&mut |system_buffer, gas_counter| {
>                     secp256k1_get_coordinates(gas_counter, system_buffer.next_usize()?, exec_scopes)
> ```





_Suggestion:_
```XML
secp256k1_get_xy
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/secp256k1.rs` line 100 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3279#-NX5maJn4KT4a24xI8mS:-NX5maJn4KT4a24xI8mT:b-jzqtf9) ([raw file](https://github.com/starkware-libs/cairo/blob/59fa22726694421d2c269454fd32671286ff0ca0/crates/cairo-lang-sierra/src/extensions/modules/starknet/secp256k1.rs#L100)):*
> ```XML
> /// `x` coordinate and the parity of the relevant y coordinate.
> #[derive(Default)]
> pub struct Secp256K1EcGetPointFromXLibfunc {}
> ```

Also in all Rust structs/traits/impls - please remove `ec`



_Code quote:_
```XML
Secp256K1EcGetPointFromXLibfunc
```
___
*[`crates/cairo-lang-starknet/src/felt252_serde.rs` line 185 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3279#-NX5loVa8piJTyJvHY-3:-NX5loVa8piJTyJvHY-4:b-xzom24) ([raw file](https://github.com/starkware-libs/cairo/blob/59fa22726694421d2c269454fd32671286ff0ca0/crates/cairo-lang-starknet/src/felt252_serde.rs#L185)):*
> ```XML
>             StorageBaseAddressFromFelt252Libfunc::STR_ID,
>             StorageAddressTryFromFelt252Trait::STR_ID,
>             Secp256K1EcGetPointFromXLibfunc::STR_ID,
> ```

Why is it suddenly required?



_Code quote:_
```XML
Secp256K1EcGetPointFromXLibfunc::STR_ID,
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3279)* status: 2 of 21 files reviewed, 4 unresolved discussions (waiting on @liorgold2, @orizi, and @yuvalsw)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/secp256k1.rs` line 100 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3279#-NX5maJn4KT4a24xI8mS:-NXEWjjgExVseMEodu2r:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/59fa22726694421d2c269454fd32671286ff0ca0/crates/cairo-lang-sierra/src/extensions/modules/starknet/secp256k1.rs#L100)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Also in all Rust structs/traits/impls - please remove `ec`
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/felt252_serde.rs` line 185 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3279#-NX5loVa8piJTyJvHY-3:-NXEWqXGBvc91PzQaSxX:b-rb7eh8) ([raw file](https://github.com/starkware-libs/cairo/blob/59fa22726694421d2c269454fd32671286ff0ca0/crates/cairo-lang-starknet/src/felt252_serde.rs#L185)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Why is it suddenly required?
</blockquote></details>

I didn't replace point with pt.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 593 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3279#-NX5mIx_8umLa-e3wktI:-NXEL2pn-cQQvP388EBr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/59fa22726694421d2c269454fd32671286ff0ca0/crates/cairo-lang-runner/src/casm_run/mod.rs#L593)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

How about removing the `Ec` from the selectors too? 
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3279)* status: 2 of 21 files reviewed, 4 unresolved discussions (waiting on @liorgold2, @orizi, and @yuvalsw)

___
*[`tests/e2e_test.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3279#-NXEXPIg-k7y1TneRRNZ:-NXEXPIg-k7y1TneRRN_:bk4vb0s) ([raw file](https://github.com/starkware-libs/cairo/blob/9cfb99e3134839df2c36080b4830b80e3ba9a12c/tests/e2e_test.rs#L80)):*
> ```XML
>         contract_address: "contract_address",
>         secp256k1: "secp256k1",
>         secp256r1: "secp256r1",
> ```

@yuvalsw 
It seems that this was missing.



_Code quote:_
```XML
secp256r1: "secp256r1",
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3279)* status: 2 of 21 files reviewed, 4 unresolved discussions (waiting on @liorgold2, @orizi, and @yuvalsw)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 629 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3279#-NX5mSOcCk_Gt2GNNxrD:-NXEZw7u9IVFOK5v5aTt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/59fa22726694421d2c269454fd32671286ff0ca0/crates/cairo-lang-runner/src/casm_run/mod.rs#L629)):*
> ```XML
>             "Secp256k1EcGetCoordinates" => {
>                 execute_handle_helper(&mut |system_buffer, gas_counter| {
>                     secp256k1_get_coordinates(gas_counter, system_buffer.next_usize()?, exec_scopes)
> ```

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3279)* status: 14 of 21 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @yuvalsw)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 593 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3279#-NX5mIx_8umLa-e3wktI:-NXEqprdEg4z4_5KlhwG:b-3k2z1c) ([raw file](https://github.com/starkware-libs/cairo/blob/59fa22726694421d2c269454fd32671286ff0ca0/crates/cairo-lang-runner/src/casm_run/mod.rs#L593)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I still see Ec in the selectors, e.g. "Secp256k1EcNew"
</blockquote></details>

hopefully done now :)
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 633 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3279#-NXEqsr25qKiTESHBbqv:-NXEqsr25qKiTESHBbqw:b-imw2x5) ([raw file](https://github.com/starkware-libs/cairo/blob/0a08314b5373b898f503574efed0b0e7e6b238b9/crates/cairo-lang-runner/src/casm_run/mod.rs#L633)):*
> ```XML
>                 )
>             }),
>             "Secp256k1GetXy" => {
> ```

Are we happy with this selector?

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 6 of 7 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3279#-:-NXFbmBg2aw-J6JdlkTX:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @liorgold2)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 633 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3279#-NXEqsr25qKiTESHBbqv:-NXFbIAOC09G90Ux1C1z:b-j4kz46) ([raw file](https://github.com/starkware-libs/cairo/blob/0a08314b5373b898f503574efed0b0e7e6b238b9/crates/cairo-lang-runner/src/casm_run/mod.rs#L633)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Are we happy with this selector?
</blockquote></details>

I am, you can consult with others if you think they might not like it.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/starknet/secp256.rs` line 43 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3279#-NXFbXAT2UfFBjuq7QeQ:-NXFbXAT2UfFBjuq7QeR:b32x1i) ([raw file](https://github.com/starkware-libs/cairo/blob/cd0909b68cc0dad9069a259846a5502279ce3dfb/crates/cairo-lang-sierra-to-casm/src/invocations/starknet/secp256.rs#L43)):*
> ```XML
>                 build_syscalls(builder, "Secp256r1GetPointFromX", [2, 1], [2])
>             }
>             Secp256OpConcreteLibfunc::GetCoordinates(_) => {
> ```

xy



_Code quote:_
```XML
Coordinates
```

**Pull request merged**
