### PR TITLE
Added ecdsa recovery.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #3736
- #3735 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3735)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3735)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ArielElp, @liorgold2, and @orizi)

___
*[`corelib/src/test/ec_test.cairo` line 135 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3735#-Na1t38W7uEf8VoZIAl0:-Na1t38W7uEf8VoZIAl1:b17x13) ([raw file](https://github.com/starkware-libs/cairo/blob/790a14a0091d7559de08cb046b481ed9dfd9c2f8/corelib/src/test/ec_test.cairo#L135)):*
> ```Cairo
>         ),
>         'ecdsa returned false'
>     );
> ```

please test
recover_public_key

without using check_ecdsa_signature



_Code quote:_
```Cairo
    assert(
        ecdsa::check_ecdsa_signature(
            :message_hash,
            public_key: ecdsa::recover_public_key(
                :message_hash, :signature_r, :signature_s, y_parity: true
            )
                .unwrap(),
            :signature_r,
            :signature_s
        ),
        'ecdsa returned false'
    );
```

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/ecdsa.cairo` line 134 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3735#-Na1tJTd8Taobl5h1ObM:-Na1tJTd8Taobl5h1ObN:b-xnxlxu) ([raw file](https://github.com/starkware-libs/cairo/blob/790a14a0091d7559de08cb046b481ed9dfd9c2f8/corelib/src/ecdsa.cairo#L134)):*
> ```Cairo
>     //   +/- rQ = sR - zG.
>     //   +/- Q = (s/r)R - (z/r)G, or more efficiently that:
>     //   Q.x = ((s/r)R - (z/r)G).x.
> ```

is the comment here:
https://github.com/starkware-libs/cairo/blob/f5584959b6d597a4744241929bd5543d44631a15/corelib/src/starknet/secp256_trait.cairo#L60

incorrect?

why do we need all the +/-?



_Code quote:_
```Cairo
    // To verify ECDSA, obtain:
    //   zG = z * G, where z is the message and G is a generator of the EC.
    //   rQ = r * Q, where Q.x = public_key.
    //   sR = s * R, where R.x = r.
    // and check that:
    //   zG +/- rQ = +/- sR.
    //
    // Since this is a recovery, and we've bound R's parity we can find values such that:
    //   zG +/- rQ = sR.
    //   +/- rQ = sR - zG.
    //   +/- Q = (s/r)R - (z/r)G, or more efficiently that:
    //   Q.x = ((s/r)R - (z/r)G).x.
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3735)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ArielElp, @ilyalesokhin-starkware, and @liorgold2)

___
*[`corelib/src/ecdsa.cairo` line 134 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3735#-Na1tJTd8Taobl5h1ObM:-Na1uLvd8s-A-IU7DRyZ:b-u0ol12) ([raw file](https://github.com/starkware-libs/cairo/blob/790a14a0091d7559de08cb046b481ed9dfd9c2f8/corelib/src/ecdsa.cairo#L134)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

is the comment here:
https://github.com/starkware-libs/cairo/blob/f5584959b6d597a4744241929bd5543d44631a15/corelib/src/starknet/secp256_trait.cairo#L60

incorrect?

why do we need all the +/-?
</blockquote></details>

it seems correct - but i don't fully know.
what i've done here is actually use the formula we used in validation and shown that it works at recovery.

do note that the code you mentioned does a very similar actual calculation.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3735)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ArielElp, @ilyalesokhin-starkware, and @liorgold2)

___
*[`corelib/src/test/ec_test.cairo` line 135 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3735#-Na1t38W7uEf8VoZIAl0:-Na1uhdm1wczZwjyvvM8:bw4onzq) ([raw file](https://github.com/starkware-libs/cairo/blob/790a14a0091d7559de08cb046b481ed9dfd9c2f8/corelib/src/test/ec_test.cairo#L135)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

please test
recover_public_key

without using check_ecdsa_signature
</blockquote></details>

i do - it happens in the y_parity: false case.

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/test/ec_test.cairo` line 135 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3735#-Na1t38W7uEf8VoZIAl0:-Na1uy3OBgstQy4-A2Sk:bqwkn8u) ([raw file](https://github.com/starkware-libs/cairo/blob/790a14a0091d7559de08cb046b481ed9dfd9c2f8/corelib/src/test/ec_test.cairo#L135)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i do - it happens in the y_parity: false case.
</blockquote></details>

but not int the y\_parity:true case.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3735)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ArielElp, @ilyalesokhin-starkware, and @liorgold2)

___
*[`corelib/src/test/ec_test.cairo` line 135 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3735#-Na1t38W7uEf8VoZIAl0:-Na1vo-OBH4xY6iXVsPQ:b-x6b71z) ([raw file](https://github.com/starkware-libs/cairo/blob/790a14a0091d7559de08cb046b481ed9dfd9c2f8/corelib/src/test/ec_test.cairo#L135)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

but not int the y\_parity:true case.
</blockquote></details>

true - since the golden case was the true case - i validate the minimal false case -
which is "the result is still valid" meaning - the result passes ecdsa validation.

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/test/ec_test.cairo` line 135 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3735#-Na1t38W7uEf8VoZIAl0:-Na20YN-2F8GFBUPR9RP:b-onzt67) ([raw file](https://github.com/starkware-libs/cairo/blob/790a14a0091d7559de08cb046b481ed9dfd9c2f8/corelib/src/test/ec_test.cairo#L135)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

true - since the golden case was the true case - i validate the minimal false case -
which is "the result is still valid" meaning - the result passes ecdsa validation.
</blockquote></details>

you are doing and end to end test instead of a unit test for no reason.

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/test/ec_test.cairo` line 135 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3735#-Na20k6rBubVBiF3Qh5N:-Na20k6rBubVBiF3Qh5O:b78km5l) ([raw file](https://github.com/starkware-libs/cairo/blob/790a14a0091d7559de08cb046b481ed9dfd9c2f8/corelib/src/test/ec_test.cairo#L135)):*
> ```Cairo
>         ),
>         'ecdsa returned false'
>     );
> ```

why not?



_Suggestion:_
```Cairo
    let public_key = 0x7b7454acbe7845da996377f85eb0892044d75ae95d04d3325a391951f35d2ec;
    assert(
         public_key: ecdsa::recover_public_key(
                :message_hash, :signature_r, :signature_s, y_parity: true
            ) == public_key,
        'recover_public_key failed.'
    );
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3735)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @ArielElp, @ilyalesokhin-starkware, and @liorgold2)

___
*[`corelib/src/test/ec_test.cairo` line 135 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3735#-Na1t38W7uEf8VoZIAl0:-Na212gK0ZnDxAxrPaPN:b-nnsal6) ([raw file](https://github.com/starkware-libs/cairo/blob/790a14a0091d7559de08cb046b481ed9dfd9c2f8/corelib/src/test/ec_test.cairo#L135)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

you are doing and end to end test instead of a unit test for no reason.
</blockquote></details>

this is a unit test - since i cannot (and do not) want to divinate the other possible public keys for a (r,s,msg) triplet, all i need to make sure is that i got a valid result - using a cross test for that is actually more sensible than writing a value that is not obviously correct by looking at it.
___
*[`corelib/src/test/ec_test.cairo` line 135 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3735#-Na20k6rBubVBiF3Qh5N:-Na2184m93JnYFHOQ4ri:bq7zhpp) ([raw file](https://github.com/starkware-libs/cairo/blob/790a14a0091d7559de08cb046b481ed9dfd9c2f8/corelib/src/test/ec_test.cairo#L135)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why not?
</blockquote></details>

because i use it only once - and the variable is not helpful.

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/ecdsa.cairo` line 134 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3735#-Na1tJTd8Taobl5h1ObM:-Na22jvD6lQTsaxp3XUH:b3odu9a) ([raw file](https://github.com/starkware-libs/cairo/blob/790a14a0091d7559de08cb046b481ed9dfd9c2f8/corelib/src/ecdsa.cairo#L134)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it seems correct - but i don't fully know.
what i've done here is actually use the formula we used in validation and shown that it works at recovery.

do note that the code you mentioned does a very similar actual calculation.
</blockquote></details>

I understand that you've compied this from check\_ecdsa\_signature, but this is confusing 
if you don't read check\_ecdsa\_signature. aswell.

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/test/ec_test.cairo` line 135 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3735#-Na1t38W7uEf8VoZIAl0:-Na239chAd_BXj5UcB4Q:b-niddsx) ([raw file](https://github.com/starkware-libs/cairo/blob/790a14a0091d7559de08cb046b481ed9dfd9c2f8/corelib/src/test/ec_test.cairo#L135)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is a unit test - since i cannot (and do not) want to divinate the other possible public keys for a (r,s,msg) triplet, all i need to make sure is that i got a valid result - using a cross test for that is actually more sensible than writing a value that is not obviously correct by looking at it.
</blockquote></details>

this test may pass if both check_ecdsa_signature and recover_public_key are incorrect.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3735)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @ArielElp, @ilyalesokhin-starkware, and @liorgold2)

___
*[`corelib/src/ecdsa.cairo` line 134 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3735#-Na1tJTd8Taobl5h1ObM:-Na24I3YDF7IOrXRj9dO:b-ctot77) ([raw file](https://github.com/starkware-libs/cairo/blob/790a14a0091d7559de08cb046b481ed9dfd9c2f8/corelib/src/ecdsa.cairo#L134)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I understand that you've compied this from check\_ecdsa\_signature, but this is confusing 
if you don't read check\_ecdsa\_signature. aswell.
</blockquote></details>

please give a suggestion.
___
*[`corelib/src/test/ec_test.cairo` line 135 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3735#-Na1t38W7uEf8VoZIAl0:-Na24Lfc3StxPVA0kmfz:blycttk) ([raw file](https://github.com/starkware-libs/cairo/blob/790a14a0091d7559de08cb046b481ed9dfd9c2f8/corelib/src/test/ec_test.cairo#L135)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

this test may pass if both check_ecdsa_signature and recover_public_key are incorrect.
</blockquote></details>

it can happen - but this isn't the only test.

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/ecdsa.cairo` line 134 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3735#-Na268OY5sWW7ZbkNPeg:-Na268OY5sWW7ZbkNPeh:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/790a14a0091d7559de08cb046b481ed9dfd9c2f8/corelib/src/ecdsa.cairo#L134)):*
> ```Cairo
>     //   +/- rQ = sR - zG.
>     //   +/- Q = (s/r)R - (z/r)G, or more efficiently that:
>     //   Q.x = ((s/r)R - (z/r)G).x.
> ```





_Suggestion:_
```Cairo
    // a Valid signature should satisfy:
    // zG + rQ = sR.
    // Where:
    //   zG = z * G, z is the message and G is a generator of the EC.
    //   rQ = r * Q, Q.x = public_key.
    //   sR = s * R, where R.x = r and R.y is determined by y_parity.
   
   Hence 
    //   rQ = sR - zG.
    //   Q = (s/r)R - (z/r)G
   and we can recover the public keys using:
    //   Q.x = ((s/r)R - (z/r)G).x.
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3735)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @ArielElp, @liorgold2, and @orizi)

___
*[`corelib/src/test/ec_test.cairo` line 135 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3735#-Na20k6rBubVBiF3Qh5N:-Na26ipQDXLWtRYZPLBT:bx38sua) ([raw file](https://github.com/starkware-libs/cairo/blob/790a14a0091d7559de08cb046b481ed9dfd9c2f8/corelib/src/test/ec_test.cairo#L135)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

because i use it only once - and the variable is not helpful.
</blockquote></details>

It allows you to test ecdsa::recover_public_key without making any assumptions about ecdsa::check_ecdsa_signature.

in any case, this is not that critical.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3735)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ArielElp, @liorgold2, and @orizi)

___
*[`corelib/src/ecdsa.cairo` line 134 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3735#-Na1tJTd8Taobl5h1ObM:-Na270_R10ApjbFz5HXG:btk0229) ([raw file](https://github.com/starkware-libs/cairo/blob/790a14a0091d7559de08cb046b481ed9dfd9c2f8/corelib/src/ecdsa.cairo#L134)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

please give a suggestion.
</blockquote></details>

see bellow.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3735)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ArielElp, @ilyalesokhin-starkware, and @liorgold2)

___
*[`corelib/src/ecdsa.cairo` line 134 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3735#-Na268OY5sWW7ZbkNPeg:-Na2FjWZ0NT8ZKWABBM5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/790a14a0091d7559de08cb046b481ed9dfd9c2f8/corelib/src/ecdsa.cairo#L134)):*
> ```Cairo
>     //   +/- rQ = sR - zG.
>     //   +/- Q = (s/r)R - (z/r)G, or more efficiently that:
>     //   Q.x = ((s/r)R - (z/r)G).x.
> ```

Done.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3735)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ArielElp, @ilyalesokhin-starkware, and @liorgold2)

___
*[`corelib/src/ecdsa.cairo` line 134 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3735#-Na1tJTd8Taobl5h1ObM:-Na2Gtcs6MrGeMCUhyQc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/790a14a0091d7559de08cb046b481ed9dfd9c2f8/corelib/src/ecdsa.cairo#L134)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

see bellow.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3735#-:-Na2H-H11Agb-QxSQDKZ:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @ArielElp and @liorgold2)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3735)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ArielElp and @liorgold2)

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3735)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp and @liorgold2)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3735)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp and @liorgold2)

**Pull request merged**
