### PR TITLE
Support goto in find_local_variables.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2022)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2022)* status: 0 of 11 files reviewed, all discussions resolved (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/local_variables_test.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2022#-NNGUQ9a5jwKDrsqTb4R:-NNGUQ9a5jwKDrsqTb4S:b-7pd775) ([raw file](https://github.com/starkware-libs/cairo/blob/9eff69cc6b1800810ed608d86f2baa4acea22595/crates/cairo-lang-sierra-generator/src/local_variables_test.rs#L21)):*
> ```XML
>         construct_enum: "construct_enum",
>         // TODO(ilya): Enable inline test.
>         //  inline: "inline",
> ```

This is disabled as I can't enable inlining with early return yet.

I've brought the test_data from a branch where the inlining is enabled.



_Code quote:_
```XML
        // TODO(ilya): Enable inline test.
        //  inline: "inline",
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2022)* status: 3 of 11 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @liorgold2)

___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2022#-NNHNSXkD4g8sCdNhITF:-NNHNSXkD4g8sCdNhITG:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/9eff69cc6b1800810ed608d86f2baa4acea22595/crates/cairo-lang-sierra-generator/src/local_variables.rs#L38)):*
> ```XML
> }
> 
> #[derive(Clone, Debug)]
> ```

doc



_Code quote:_
```XML
#[derive(Clone, Debug)]
struct BlockInfo {
```
___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2022#-NNHNTfM6niywInjA9xu:-NNHNTfM6niywInjA9xv:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9eff69cc6b1800810ed608d86f2baa4acea22595/crates/cairo-lang-sierra-generator/src/local_variables.rs#L41)):*
> ```XML
> struct BlockInfo {
>     // Indicates there there is a branch that reaches the block_id with unknown ap change.
>     known_ap_change: bool,
> ```





_Suggestion:_
```XML
    /// Indicates there there is a branch that reaches the block_id with unknown ap change.
```
___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2022#-NNHNWWCBMY7HwrDH6M7:-NNHNWWCBMY7HwrDH6M8:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/9eff69cc6b1800810ed608d86f2baa4acea22595/crates/cairo-lang-sierra-generator/src/local_variables.rs#L44)):*
> ```XML
> }
> 
> struct FindLocalsContext<'a> {
> ```

doc



_Code quote:_
```XML
struct FindLocalsContext<'a> {
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2022)* status: 1 of 11 files reviewed, 3 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2022#-NNHNSXkD4g8sCdNhITF:-NNHxIe5605D_xzjaOQK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9eff69cc6b1800810ed608d86f2baa4acea22595/crates/cairo-lang-sierra-generator/src/local_variables.rs#L38)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2022#-NNHNTfM6niywInjA9xu:-NNHxINK6udAN-SlF4VM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9eff69cc6b1800810ed608d86f2baa4acea22595/crates/cairo-lang-sierra-generator/src/local_variables.rs#L41)):*
> ```XML
> struct BlockInfo {
>     // Indicates there there is a branch that reaches the block_id with unknown ap change.
>     known_ap_change: bool,
> ```

Done.
___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2022#-NNHNWWCBMY7HwrDH6M7:-NNHxNL00AQJBBPeR8dG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9eff69cc6b1800810ed608d86f2baa4acea22595/crates/cairo-lang-sierra-generator/src/local_variables.rs#L44)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 8 of 11 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2022#-:-NNI2mEjCzFI0bmGG7Np:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2022)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 9 of 11 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2022)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2022)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @liorgold2)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2022)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
