### PR TITLE
Fix CLIs documentation.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5053)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
Most documentation were copy/paste from the formatter. Notice that the documentation appears when running with `--help`.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5053#-:-NqShoJa79SB6SCQs4MF:b-8kgdwp)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/bin/starknet-compile/src/main.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5053#-NqShZBz9AM161sjmzh_:-NqShZBz9AM161sjmzha:bg7wzil) ([raw file](https://github.com/starkware-libs/cairo/blob/7c877404725309f108ae01c3c8ce40bee8e97af4/crates/bin/starknet-compile/src/main.rs#L12)):*
> ```XML
> use clap::Parser;
> 
> /// Compiles a Cairo project containing a contract.
> ```

Not sure how we want to call the result, as `ContractClass` doesn't say much outside of the compiler code.



_Code quote:_
```XML
/// Compiles a Cairo project containing a contract.
```
___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5053#-NqShiKnDr7Hm5TaX5eH:-NqShiKnDr7Hm5TaX5eI:b-xbezq7) ([raw file](https://github.com/starkware-libs/cairo/blob/7c877404725309f108ae01c3c8ce40bee8e97af4/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L18)):*
> ```XML
> use serde::Deserialize;
> ```

Not sure what to write here, as it is mainly for internal use.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5053)* status: 4 of 8 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/bin/starknet-compile/src/main.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5053#-NqSjRnuBXpuXxP85-I5:-NqSjRnuBXpuXxP85-I6:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7c877404725309f108ae01c3c8ce40bee8e97af4/crates/bin/starknet-compile/src/main.rs#L12)):*
> ```XML
> use clap::Parser;
> 
> /// Compiles a Cairo project containing a contract.
> ```





_Suggestion:_
```XML
/// Compiles a Cairo project containing a contract into a contract class file.
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5053)* status: 5 of 8 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/bin/starknet-sierra-extract-code/src/main.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5053#-NqSjYuz5xRyJRTUGX2M:-NqSjYuz5xRyJRTUGX2N:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7c877404725309f108ae01c3c8ce40bee8e97af4/crates/bin/starknet-sierra-extract-code/src/main.rs#L8)):*
> ```XML
> 
> /// Compiles a Cairo project containing a contract into Sierra.
> /// Exits with 0/1 if the compilation succeeds/fails.
> ```





_Suggestion:_
```XML
/// Extracts sierra code from a contract class file.
/// Exits with 0/1 if the extraction succeeds/fails.
```
___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5053#-NqShiKnDr7Hm5TaX5eH:-NqSjpW8CFIBeNjIXTHK:b-8y57k9) ([raw file](https://github.com/starkware-libs/cairo/blob/7c877404725309f108ae01c3c8ce40bee8e97af4/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L18)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Not sure what to write here, as it is mainly for internal use.
</blockquote></details>

Runs validation on existing contract classes to make sure they are still valid and compilable.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5053)* status: 4 of 8 files reviewed, 3 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/bin/starknet-compile/src/main.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5053#-NqSjRnuBXpuXxP85-I5:-NqSprna0aHLnriGbzlq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7c877404725309f108ae01c3c8ce40bee8e97af4/crates/bin/starknet-compile/src/main.rs#L12)):*
> ```XML
> use clap::Parser;
> 
> /// Compiles a Cairo project containing a contract.
> ```

Done.
___
*[`crates/bin/starknet-sierra-extract-code/src/main.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5053#-NqSjYuz5xRyJRTUGX2M:-NqSprU1A9GvwyLSHs7V:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7c877404725309f108ae01c3c8ce40bee8e97af4/crates/bin/starknet-sierra-extract-code/src/main.rs#L8)):*
> ```XML
> 
> /// Compiles a Cairo project containing a contract into Sierra.
> /// Exits with 0/1 if the compilation succeeds/fails.
> ```

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5053)* status: all files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5053)* status: 1 of 9 files reviewed, 4 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/bin/cairo-compile/src/main.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5053#-NqSpPm3DcD4EKk2GRI-:-NqSvrnIDzlzzto53TPe:b91h77x) ([raw file](https://github.com/starkware-libs/cairo/blob/7c877404725309f108ae01c3c8ce40bee8e97af4/crates/bin/cairo-compile/src/main.rs#L10)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

this goes on main. Also doc the args struct.
Same in others.
</blockquote></details>

The doc of the args struct is what shown to the user, so this should be here although this is not exactly the function that's doing what described.
___
*[`crates/bin/starknet-compile/src/main.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5053#-NqSqB1U1Lzm8z4w_4k7:-NqSwOEy0GoL7Znhowja:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5de5bfc8d976a6f78cf9e658e2b64e167e3bbd4d/crates/bin/starknet-compile/src/main.rs#L12)):*
> ```XML
> use clap::Parser;
> 
> /// Compiles a Cairo project containing a contract into a contract class file.
> ```

Done.
___
*[`crates/bin/starknet-sierra-compile/src/main.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5053#-NqSqUEt-KY-wzEOrH-v:-NqT34peDcKzi2zoXM_j:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7c877404725309f108ae01c3c8ce40bee8e97af4/crates/bin/starknet-sierra-compile/src/main.rs#L11)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Also - what happens if it's not a sierra of a contract?
</blockquote></details>

Done.
___
*[`crates/bin/starknet-sierra-extract-code/src/main.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5053#-NqSqrnR6j7ZUc9j2XUe:-NqT37Bm0yeR_XYf7l-b:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5de5bfc8d976a6f78cf9e658e2b64e167e3bbd4d/crates/bin/starknet-sierra-extract-code/src/main.rs#L12)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

consider renaming the member (in all/most args structs?).
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5053)* status: all files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5053)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

___
*[`crates/bin/starknet-sierra-compile/src/main.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5053#-NqSqUEt-KY-wzEOrH-v:-NqcEroF4uONqzQjXFUq:bqbf6s5) ([raw file](https://github.com/starkware-libs/cairo/blob/7c877404725309f108ae01c3c8ce40bee8e97af4/crates/bin/starknet-sierra-compile/src/main.rs#L11)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

"Also - what happens if it's not a sierra of a contract?"
(unblocking as I won't be here for a few days)
</blockquote></details>

Notice I changed it to Sierra contract class, so there is a contract by definition.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5053#-:-NqcHhJiAN2YjNXi-8Es:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
