### PR TITLE
feat(span):  add to_str_range for `TextSpan`

### PR DESCRIPTION
**Pull request by 0xLucqs**
I need that to fix the text from the diagnostic

This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6122)

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
i don't understand.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6122#-:-O3R6-95B8SiS8zeV6EZ:bptu5ic)* status: 0 of 1 files reviewed, all discussions resolved

**Comment by 0xLucqs** [comment]
I do something similar to clippy which is `file.replace_range(span.start..span.end, fix);` so i need to convert the `TextOffset` to `u32`

**Comment by 0xLucqs** [comment]
A function that is similar to `take_from` would work as well but maybe the `to_u32` can serve other purposes

**Review by orizi — COMMENTED** [review]
if we can not actually expose this - would be better- that was the idea up until now.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6122#-:-O3RnPz42KKt-AVRLAeZ:b-u7niab)* status: 0 of 1 files reviewed, all discussions resolved

**Comment by 0xLucqs** [comment]
What do you prefer, the `Range` trait or `replace_range_to`

**Review by orizi — COMMENTED** [review]
range as a concept of offsets sounds good. (don't know if workable here, but please do try)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6122#-:-O3SPo7gE87AWxF6Lifd:b-ty7fwi)* status: 0 of 1 files reviewed, all discussions resolved

**Pull request merged**
