### PR TITLE
Add wrappers for external functions.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1344)

### CODE REVIEW

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1344#-:-NJKIRJr1pPEChkS0jo_:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/starknet/src/plugin.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1344#-NJKGASs5N4VRTm5NMLU:-NJKGASs5N4VRTm5NMLV:bwkbgsz) ([raw file](https://github.com/starkware-libs/cairo/blob/bc239671df9a8a3feca429d7c7ac48399316e47e/crates/starknet/src/plugin.rs#L66)):*
> ```XML
>             ast::Item::FreeFunction(f) => f,
>             // Impl should only have free functions.
>             _ => continue,
> ```

unreachable!()



_Code quote:_
```XML
continue
```
___
*[`crates/starknet/src/plugin.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1344#-NJKH5K1151QPvfe-46w:-NJKH5K1151QPvfe-46x:bvoe31q) ([raw file](https://github.com/starkware-libs/cairo/blob/bc239671df9a8a3feca429d7c7ac48399316e47e/crates/starknet/src/plugin.rs#L75)):*
> ```XML
>             .any(|attr| attr.attr(db).text(db) == EXTERNAL_ATTR)
>         {
>             if let Some(generated_function) = generate_entry_point_wrapper(db, &item_function) {
> ```

TODO to propagate the diagnostics in case of failure.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/starknet/src/plugin.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1344#-NJKGASs5N4VRTm5NMLU:-NJKXz4l8EF__x4YYkH4:brgt0dv) ([raw file](https://github.com/starkware-libs/cairo/blob/d9368839554346b8f2d59bfa4e4d91701bb71a14/crates/starknet/src/plugin.rs#L66)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

unreachable!()
</blockquote></details>

Its is a moudle, other items are reachable.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1344)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/starknet/src/plugin.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1344#-NJKH5K1151QPvfe-46w:-NJKYVR20Y569kaEmLax:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d9368839554346b8f2d59bfa4e4d91701bb71a14/crates/starknet/src/plugin.rs#L75)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

TODO to propagate the diagnostics in case of failure.
</blockquote></details>

Done.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1344)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/starknet/src/plugin.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1344#-NJKGASs5N4VRTm5NMLU:-NJLLAbxAq-OqlIlCt7D:bv3zkur) ([raw file](https://github.com/starkware-libs/cairo/blob/d9368839554346b8f2d59bfa4e4d91701bb71a14/crates/starknet/src/plugin.rs#L66)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Its is a moudle, other items are reachable.
</blockquote></details>

Oh, right, it's a module. Then change the comment...
___
*[`crates/starknet/src/plugin.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1344#-NJKH5K1151QPvfe-46w:-NJLLlZZ23nemuEjptMx:b-l04umh) ([raw file](https://github.com/starkware-libs/cairo/blob/d9368839554346b8f2d59bfa4e4d91701bb71a14/crates/starknet/src/plugin.rs#L75)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You added in handle_impl. Add here too.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1344)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/starknet/src/plugin.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1344#-NJKGASs5N4VRTm5NMLU:-NJLUUm0Bsz-79WIf3pQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d9368839554346b8f2d59bfa4e4d91701bb71a14/crates/starknet/src/plugin.rs#L66)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Oh, right, it's a module. Then change the comment...
</blockquote></details>

Done.

**Review by yuvalsw — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1344)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
