### PR TITLE
filter diagnostics

### PR DESCRIPTION
**Pull request by Tomer-StarkWare**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6001)

### CODE REVIEW

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6001)* status: 1 of 15 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @orizi, and @Tomer-StarkWare)

___
*[`crates/cairo-lang-diagnostics/src/diagnostics.rs` line 309 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6001#-O1RJjI85_DG9V-KChiA:-O1RJjI85_DG9V-KChiB:b5hm0i1) ([raw file](https://github.com/starkware-libs/cairo/blob/b0b7cde62e32eefa478cb4c361ae93d529620cc0/crates/cairo-lang-diagnostics/src/diagnostics.rs#L309)):*
> ```XML
>     }
> 
>     pub fn get_all(&self, with_duplicates: bool, db: &TEntry::DbType) -> Vec<TEntry> {
> ```

plz doc. Explain what "duplicates" are because this is not obvious to me.

**Review by mkaput — COMMENTED** [review]
> Reviewed 14 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6001)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @orizi, and @Tomer-StarkWare)

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6001)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @mkaput, and @orizi)

___
*[`crates/cairo-lang-diagnostics/src/diagnostics.rs` line 309 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6001#-O1RJjI85_DG9V-KChiA:-O1RWfDx9lC90mZpSDAQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b0b7cde62e32eefa478cb4c361ae93d529620cc0/crates/cairo-lang-diagnostics/src/diagnostics.rs#L309)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

plz doc. Explain what "duplicates" are because this is not obvious to me.
</blockquote></details>

Done.

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6001)* status: 11 of 15 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @orizi, and @Tomer-StarkWare)

___
*[`crates/cairo-lang-diagnostics/src/diagnostics.rs` line 309 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6001#-O1RJjI85_DG9V-KChiA:-O1RaXne8h4SnEUpmRIZ:b-quw6wd) ([raw file](https://github.com/starkware-libs/cairo/blob/b0b7cde62e32eefa478cb4c361ae93d529620cc0/crates/cairo-lang-diagnostics/src/diagnostics.rs#L309)):*
<details><summary><i>Previously, Tomer-StarkWare (TomerC-StarkWare) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

please doc what is considered a "duplicate". same message? same location? both?

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6001)* status: 11 of 15 files reviewed, 3 unresolved discussions (waiting on @mkaput, @orizi, and @Tomer-StarkWare)

___
*[`crates/cairo-lang-diagnostics/src/diagnostics.rs` line 309 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6001#-O1RJjI85_DG9V-KChiA:-O1Rb51fDfO0m04BBH1S:b32v57) ([raw file](https://github.com/starkware-libs/cairo/blob/b0b7cde62e32eefa478cb4c361ae93d529620cc0/crates/cairo-lang-diagnostics/src/diagnostics.rs#L309)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

please doc what is considered a "duplicate". same message? same location? both?
</blockquote></details>

+1
___
*[`crates/cairo-lang-diagnostics/src/diagnostics.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6001#-O1RagBh8kdDkwfugifL:-O1RagBh8kdDkwfugifM:b-n9h2rb) ([raw file](https://github.com/starkware-libs/cairo/blob/52067c2492ab24944bf09fb2c14927d8a453773f/crates/cairo-lang-diagnostics/src/diagnostics.rs#L49)):*
> ```XML
>         None
>     }
>     /// Returns true if the two diagnostics are of the same kind.
> ```

As not any diagnostic must have a `kind` field, it is worth adding this clarification.



_Suggestion:_
```XML
/// Returns true if the two should be regarded as the same kind when filtering duplicate diagnostics.
```
___
*[`crates/cairo-lang-diagnostics/src/diagnostics.rs` line 317 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6001#-O1RcJp71TCKAk9G8VTG:-O1RcJp71TCKAk9G8VTH:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/52067c2492ab24944bf09fb2c14927d8a453773f/crates/cairo-lang-diagnostics/src/diagnostics.rs#L317)):*
> ```XML
>         for (idx, diag) in diagnostic_with_dup.iter().enumerate() {
>             indexed_dup_diagnostic.push((idx, diag));
>         }
> ```





_Suggestion:_
```XML
        let indexed_dup_diagnostic = diagnostic_with_dup.iter().enumerate().map(|idx, diag| (idx, diag));
```

**Review by mkaput — APPROVED** [review]
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6001)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi and @Tomer-StarkWare)

___
*[`crates/cairo-lang-diagnostics/src/diagnostics.rs` line 308 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6001#-O1Re3N56QUNRZbwJ6EM:-O1Re3N56QUNRZbwJ6EN:b2ni8l0) ([raw file](https://github.com/starkware-libs/cairo/blob/21c27ea499f85b01eb4e6fc03696847e10cf6b10/crates/cairo-lang-diagnostics/src/diagnostics.rs#L308)):*
> ```XML
> 
>     /// Get diagnostics without duplication, such that there will be no 2 diagnostics that points to
>     /// the same location in the user code, and are of the same kind.
> ```

nit



_Suggestion:_
```XML
    /// Get diagnostics without duplication.
    ///
    /// Two diagnostics are considered duplicated if both point to
    /// the same location in the user code, and are of the same kind.
```

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6001)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi and @Tomer-StarkWare)

___
*[`crates/cairo-lang-diagnostics/src/diagnostics.rs` line 335 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6001#-O1RnuzWBMA0vyB2wS6S:-O1RnuzWBMA0vyB2wS6T:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8727e55827dcbef0aede2a9bce8c9b3cfe8be87f/crates/cairo-lang-diagnostics/src/diagnostics.rs#L335)):*
> ```XML
>             diagnostic_without_dup.push(diag);
>             prev_diagnostic_indexed = Some(diag);
>         }
> ```





_Suggestion:_
```XML
        let mut prev_diagnostic_indexed = indexed_dup_doagnostic.next().unwrap();
        let mut diagnostic_without_dup = vec![prev_diagnostic_indexed];

        for diag in indexed_dup_diagnostic {
            if prev_diagnostic_indexed.1.is_same_kind(diag.1)
                && prev_diagnostic_indexed.1.location(db).user_location(files_db).span
                    == diag.1.location(db).user_location(files_db).span
            {
                continue;
            }
            diagnostic_without_dup.push(diag);
            prev_diagnostic_indexed = diag;
        }
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6001)* status: 12 of 15 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware, @mkaput, and @orizi)

___
*[`crates/cairo-lang-diagnostics/src/diagnostics.rs` line 335 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6001#-O1RnuzWBMA0vyB2wS6S:-O1Rt90P-12T2uQQFk1I:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8727e55827dcbef0aede2a9bce8c9b3cfe8be87f/crates/cairo-lang-diagnostics/src/diagnostics.rs#L335)):*
> ```XML
>             diagnostic_without_dup.push(diag);
>             prev_diagnostic_indexed = Some(diag);
>         }
> ```

Done.

**Review by mkaput — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6001)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6001#-:-O1RvPQ109beqxLyP7rd:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by mkaput — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6001#-:-O1RwW_69YBmCPigEC0L:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6001)* status: all files reviewed, 1 unresolved discussion (waiting on @Tomer-StarkWare)

___
*[`crates/cairo-lang-lowering/src/diagnostic.rs` line 105 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6001#-O1RzUYO7EqNlpbSJsuk:-O1RzUYO7EqNlpbSJsul:b6w2ndg) ([raw file](https://github.com/starkware-libs/cairo/blob/c9c3d12d3d51f09ec852acf9e88c34ebff6991e8/crates/cairo-lang-lowering/src/diagnostic.rs#L105)):*
> ```XML
>     }
> 
>     fn is_same_kind(&self, _other: &Self) -> bool {
> ```

doc.
remove `_`

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 15 files at r1, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6001#-:-O1S0wGY0R7rJJzAZUOs:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Tomer-StarkWare)

**Review by mkaput — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6001)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Tomer-StarkWare)

**Pull request merged**
