### PR TITLE
Compute offsets for mod builtins.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5507)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5507)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/circuit.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5507#-NxBYSgY9asrjgnk0OiW:-NxBYSgZ17blEWG8CPjP:bvdy5b4) ([raw file](https://github.com/starkware-libs/cairo/blob/ccb33b8d8eb09becd30b523422776f4e3649872e/crates/cairo-lang-sierra-to-casm/src/circuit.rs#L24)):*
> ```XML
>     pub values: UnorderedHashMap<ConcreteTypeId, usize>,
>     /// The offsets for the add gates.
>     pub add_offsets: Vec<(usize, usize, usize)>,
> ```

maybe extract the triplet into a struct?



_Code quote:_
```XML
    pub add_offsets: Vec<(usize, usize, usize)>,
```
___
*[`crates/cairo-lang-sierra-to-casm/src/circuit.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5507#-NxBZoLaBcQI0FISBuCG:-NxBZoLaBcQI0FISBuCH:bgjkl68) ([raw file](https://github.com/starkware-libs/cairo/blob/ccb33b8d8eb09becd30b523422776f4e3649872e/crates/cairo-lang-sierra-to-casm/src/circuit.rs#L112)):*
> ```XML
>     // We visit each gate in the circuit twice, in the first visit push all its inputs
>     // and in the second visit we assume that all the inputs were already visited and we can
>     // allocate a value for the outputs and prepare the offsets in the relevant builtin.
> ```

can't a simple DFS just work?



_Code quote:_
```XML
    // We visit each gate in the circuit twice, in the first visit push all its inputs
    // and in the second visit we assume that all the inputs were already visited and we can
    // allocate a value for the outputs and prepare the offsets in the relevant builtin.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-to-casm/src/circuit.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5507#-NxBZoLaBcQI0FISBuCG:-NxBkkcG3ErtE6afZxxv:b91fqww) ([raw file](https://github.com/starkware-libs/cairo/blob/ccb33b8d8eb09becd30b523422776f4e3649872e/crates/cairo-lang-sierra-to-casm/src/circuit.rs#L112)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can't a simple DFS just work?
</blockquote></details>

What do you mean by simple DFS?
using recursion instead of having the stack in a local variable?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5507)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/circuit.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5507#-NxBYSgY9asrjgnk0OiW:-NxBmbNwE8y3EYsOm5n4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ccb33b8d8eb09becd30b523422776f4e3649872e/crates/cairo-lang-sierra-to-casm/src/circuit.rs#L24)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe extract the triplet into a struct?
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5507)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/circuit.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5507#-NxBZoLaBcQI0FISBuCG:-NxBqPik4Gwdbj8-uSbu:b-othip2) ([raw file](https://github.com/starkware-libs/cairo/blob/ccb33b8d8eb09becd30b523422776f4e3649872e/crates/cairo-lang-sierra-to-casm/src/circuit.rs#L112)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

What do you mean by simple DFS?
using recursion instead of having the stack in a local variable?
</blockquote></details>

nm - my basic idea was a bit too much.
___
*[`crates/cairo-lang-sierra-to-casm/src/circuit.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5507#-NxBq7AE9mLPOUxEwJMc:-NxBq7AE9mLPOUxEwJMd:btyta5e) ([raw file](https://github.com/starkware-libs/cairo/blob/e4080e40a02d2f02d73e097c94b21c774c085644/crates/cairo-lang-sierra-to-casm/src/circuit.rs#L15)):*
> ```XML
> // TODO(ilya): Remove 'dead_code' once we use the gate offsets.
> #[allow(dead_code)]
> pub struct GateOffsets {
> ```

Doc struct

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5507)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/circuit.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5507#-NxBq7AE9mLPOUxEwJMc:-NxByRQcBENn9IXBX67-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e4080e40a02d2f02d73e097c94b21c774c085644/crates/cairo-lang-sierra-to-casm/src/circuit.rs#L15)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Doc struct
</blockquote></details>

Done.

**Pull request merged**
