### PR TITLE
Refactored `get_use_segments` to contain less stages.

### PR DESCRIPTION
**Pull request by orizi**
Additionally removed recursion.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6361)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/items/us.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6361#-O6FZf2P6XTAwRZt6fo3:-O6FZf2P6XTAwRZt6fo4:b-g04cfb) ([raw file](https://github.com/starkware-libs/cairo/blob/c55d37c462f53444a9d8043740fc36dc4b658ac5/crates/cairo-lang-semantic/src/items/us.rs#L84)):*
> ```XML
>             SyntaxKind::UsePathMulti => {
>                 Some(ast::UsePath::Multi(ast::UsePathMulti::from_syntax_node(db, node)))
>             }
> ```

why was this changed?



_Code quote:_
```XML
            SyntaxKind::UsePathMulti => {
                Some(ast::UsePath::Multi(ast::UsePathMulti::from_syntax_node(db, node)))
            }
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6361)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi and @Tomer-StarkWare)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6361)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/items/us.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6361#-O6FZf2P6XTAwRZt6fo3:-O6FZpLg-WU3fH_yzTQE:bo2pd2c) ([raw file](https://github.com/starkware-libs/cairo/blob/c55d37c462f53444a9d8043740fc36dc4b658ac5/crates/cairo-lang-semantic/src/items/us.rs#L84)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why was this changed?
</blockquote></details>

because it was unnecessary.
`multi` just holds a list - i changed the function to only return the interesting segments (which are `single`)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/items/us.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6361#-O6FZf2P6XTAwRZt6fo3:-O6F_cq80RLcThe80Zid:bthsjky) ([raw file](https://github.com/starkware-libs/cairo/blob/c55d37c462f53444a9d8043740fc36dc4b658ac5/crates/cairo-lang-semantic/src/items/us.rs#L84)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

because it was unnecessary.
`multi` just holds a list - i changed the function to only return the interesting segments (which are `single`)
</blockquote></details>

Can we have a use item whose parent is a multi  UsePathMulti?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/items/us.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6361#-O6FaDvE0c-GiMZ8w5gT:-O6FaDvE0c-GiMZ8w5gU:b-9h9iz5) ([raw file](https://github.com/starkware-libs/cairo/blob/8fdbc18b0e177ae57e34b8ae2639b714847dfee8/crates/cairo-lang-semantic/src/items/us.rs#L56)):*
> ```XML
>         ast::UsePath::Leaf(use_ast) => vec![use_ast.ident(db)],
>         ast::UsePath::Single(use_ast) => vec![use_ast.ident(db)],
>         ast::UsePath::Multi(_) => vec![],
> ```

why empty?



_Code quote:_
```XML
 ast::UsePath::Multi(_) => vec![],
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6361)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/items/us.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6361#-O6FaDvE0c-GiMZ8w5gT:-O6FaH_Y40ElkbLPebr1:bt91d7z) ([raw file](https://github.com/starkware-libs/cairo/blob/8fdbc18b0e177ae57e34b8ae2639b714847dfee8/crates/cairo-lang-semantic/src/items/us.rs#L56)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why empty?
</blockquote></details>

because it has no name - only `Single` and `Leaf` has identifiers in them.
___
*[`crates/cairo-lang-semantic/src/items/us.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6361#-O6FZf2P6XTAwRZt6fo3:-O6Fa13f4dbGrNNjD-Gc:b5sr689) ([raw file](https://github.com/starkware-libs/cairo/blob/c55d37c462f53444a9d8043740fc36dc4b658ac5/crates/cairo-lang-semantic/src/items/us.rs#L84)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Can we have a use item whose parent is a multi  UsePathMulti?
</blockquote></details>

we can - but:
* ItemUse
  * UsePathMulti
    * UsePathList
      * UsePathMulti
        * UsePathList
          * UsePathLeaf

```
use {{leaf}};
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/items/us.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6361#-O6FbwPB2pxFHya_QdAe:-O6FbwPB2pxFHya_QdAf:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c55d37c462f53444a9d8043740fc36dc4b658ac5/crates/cairo-lang-semantic/src/items/us.rs#L48)):*
> ```XML
>     Ok(UseData { diagnostics: diagnostics.build(), resolved_item, resolver_data })
> }
> ```





_Suggestion:_
```XML
/// Returns the `UsePathSingle` segments that appear in the use path.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/items/us.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6361#-O6FZf2P6XTAwRZt6fo3:-O6FcJWeCfFFaiJ8C_wt:b-gen1g5) ([raw file](https://github.com/starkware-libs/cairo/blob/c55d37c462f53444a9d8043740fc36dc4b658ac5/crates/cairo-lang-semantic/src/items/us.rs#L84)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

we can - but:
* ItemUse
  * UsePathMulti
    * UsePathList
      * UsePathMulti
        * UsePathList
          * UsePathLeaf

```
use {{leaf}};
```
</blockquote></details>

don't you want to return leaf in this case?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6361)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/items/us.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6361#-O6FZf2P6XTAwRZt6fo3:-O6FdX-Z-G5PA-Q9RD7c:b-c6zxay) ([raw file](https://github.com/starkware-libs/cairo/blob/c55d37c462f53444a9d8043740fc36dc4b658ac5/crates/cairo-lang-semantic/src/items/us.rs#L84)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

don't you want to return leaf in this case?
</blockquote></details>

i start from the leaf - this function only returns parents.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6361)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/items/us.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6361#-O6FbwPB2pxFHya_QdAe:-O6FdeJI1eWz6QyuESWi:bmtksk8) ([raw file](https://github.com/starkware-libs/cairo/blob/c55d37c462f53444a9d8043740fc36dc4b658ac5/crates/cairo-lang-semantic/src/items/us.rs#L48)):*
> ```XML
>     Ok(UseData { diagnostics: diagnostics.build(), resolved_item, resolver_data })
> }
> ```

these are all the path segments of the use items we got.
it isn't just `single` (currently, it just means `leaf` as well).

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/items/us.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6361#-O6FbwPB2pxFHya_QdAe:-O6FeRJw63OsULlTLyKh:b310rvn) ([raw file](https://github.com/starkware-libs/cairo/blob/c55d37c462f53444a9d8043740fc36dc4b658ac5/crates/cairo-lang-semantic/src/items/us.rs#L48)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

these are all the path segments of the use items we got.
it isn't just `single` (currently, it just means `leaf` as well).
</blockquote></details>

If you have
{a, b}
doesn't it include the segments 'a' and 'b'?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6361)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/items/us.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6361#-O6FZf2P6XTAwRZt6fo3:-O6Fei1R0lOHA3jVxgBt:b-s7sckj) ([raw file](https://github.com/starkware-libs/cairo/blob/c55d37c462f53444a9d8043740fc36dc4b658ac5/crates/cairo-lang-semantic/src/items/us.rs#L84)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i start from the leaf - this function only returns parents.
</blockquote></details>

what happens if you have:

{{ parent }} :: {{leaf}}
?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6361)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/items/us.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6361#-O6FbwPB2pxFHya_QdAe:-O6FeivU6YSV51P1gBmX:b-qkehr6) ([raw file](https://github.com/starkware-libs/cairo/blob/c55d37c462f53444a9d8043740fc36dc4b658ac5/crates/cairo-lang-semantic/src/items/us.rs#L48)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

If you have
{a, b}
doesn't it include the segments 'a' and 'b'?
</blockquote></details>

no - this gets `a` or `b` as an input - and will return [`a`] for `a` and [`b`] for `b`.
___
*[`crates/cairo-lang-semantic/src/items/us.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6361#-O6FZf2P6XTAwRZt6fo3:-O6FevBm9bfK285fHHL6:b72ytlm) ([raw file](https://github.com/starkware-libs/cairo/blob/c55d37c462f53444a9d8043740fc36dc4b658ac5/crates/cairo-lang-semantic/src/items/us.rs#L84)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what happens if you have:

{{ parent }} :: {{leaf}}
?
</blockquote></details>

this doesn't parse.

`use` is a tree, not a DAG.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/items/us.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6361#-O6FbwPB2pxFHya_QdAe:-O6FgR6lA5ox_npHmuI0:b-5baayv) ([raw file](https://github.com/starkware-libs/cairo/blob/c55d37c462f53444a9d8043740fc36dc4b658ac5/crates/cairo-lang-semantic/src/items/us.rs#L48)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no - this gets `a` or `b` as an input - and will return [`a`] for `a` and [`b`] for `b`.
</blockquote></details>

why can't it get {a, b} as input?
.

shouldn't the first match be:

 ast::UsePath::Multi(_) => unreachable,

if this is the case?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6361)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/items/us.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6361#-O6FbwPB2pxFHya_QdAe:-O6FgzMm-7Mg-W224JiZ:btzas0e) ([raw file](https://github.com/starkware-libs/cairo/blob/c55d37c462f53444a9d8043740fc36dc4b658ac5/crates/cairo-lang-semantic/src/items/us.rs#L48)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why can't it get {a, b} as input?
.

shouldn't the first match be:

 ast::UsePath::Multi(_) => unreachable,

if this is the case?
</blockquote></details>

but it is reachable.

calling this function with the node of `{a, b}` of `d::c::{a, b}` is valid.
i don't know who will do that exactly - but it is.
might be useful for some formatter or LS stuff.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/items/us.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6361#-O6FbwPB2pxFHya_QdAe:-O6FhZB7BOBfivPZ5FyO:brvyaso) ([raw file](https://github.com/starkware-libs/cairo/blob/c55d37c462f53444a9d8043740fc36dc4b658ac5/crates/cairo-lang-semantic/src/items/us.rs#L48)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

but it is reachable.

calling this function with the node of `{a, b}` of `d::c::{a, b}` is valid.
i don't know who will do that exactly - but it is.
might be useful for some formatter or LS stuff.
</blockquote></details>

Ok, why are 'a' anb 'b' not segments of the path `d::c::{a, b}`?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6361)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/items/us.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6361#-O6FbwPB2pxFHya_QdAe:-O6Fhy-wDBv-ccur3Fbj:bm8gvhe) ([raw file](https://github.com/starkware-libs/cairo/blob/c55d37c462f53444a9d8043740fc36dc4b658ac5/crates/cairo-lang-semantic/src/items/us.rs#L48)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Ok, why are 'a' anb 'b' not segments of the path `d::c::{a, b}`?
</blockquote></details>

because this function starts from some node in the use tree - and goes up.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/items/us.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6361#-O6FbwPB2pxFHya_QdAe:-O6Fj9AyE-fH1Hh4dI35:byiv7ov) ([raw file](https://github.com/starkware-libs/cairo/blob/c55d37c462f53444a9d8043740fc36dc4b658ac5/crates/cairo-lang-semantic/src/items/us.rs#L48)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

because this function starts from some node in the use tree - and goes up.
</blockquote></details>

`d::c::a' includes 'a'
why doesn't
`d::c::{a, b}` 
include 'a' and 'b'?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6361)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/items/us.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6361#-O6FbwPB2pxFHya_QdAe:-O6FjaaE8jlz6yaJGR9N:b3f84o3) ([raw file](https://github.com/starkware-libs/cairo/blob/c55d37c462f53444a9d8043740fc36dc4b658ac5/crates/cairo-lang-semantic/src/items/us.rs#L48)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

`d::c::a' includes 'a'
why doesn't
`d::c::{a, b}` 
include 'a' and 'b'?
</blockquote></details>

because `{a, b}` is the parent of `a` and `b` - not the other way around.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6361#-:-O6GEJVJDTrOcLVNMoHY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Tomer-StarkWare)

**Pull request merged**
