### PR TITLE
Extract `ProjectConfig::absolute_crate_root`

### PR DESCRIPTION
**Pull request by mkaput**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5980)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5980#-:-O1Mo7_16We4ZwtFNUHa:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5980)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)

___
*[`crates/cairo-lang-project/src/lib.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5980#-O1MoALRA90chRrLVCdj:-O1MoALRA90chRrLVCdk:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/88866d18db6c343d98dd29a87098a9a5362b173d/crates/cairo-lang-project/src/lib.rs#L76)):*
> ```XML
>     }
> 
>     /// Makes the crate root absolute, according to the base path of this project.
> ```

.



_Suggestion:_
```XML
    /// Returns the crate root's absolute path, according to the base path of this project.
```

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5980)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-project/src/lib.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5980#-O1MoALRA90chRrLVCdj:-O1Mq7wzD9mS0pbqtUqn:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/88866d18db6c343d98dd29a87098a9a5362b173d/crates/cairo-lang-project/src/lib.rs#L76)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5980#-:-O1MqTVkDKESnzyq7gE5:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Pull request merged**
