### PR TITLE
Added profiling aggregations by user functions

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4810)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4810)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-runner/src/profiling_test_data/profiling` line 220 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4810#-NoCogU80NfqocvN2h1U:-NoCogU80NfqocvN2h1V:b-8fi342) ([raw file](https://github.com/starkware-libs/cairo/blob/4fc55f1aab955a29c945f91a14fc2362159041ca/crates/cairo-lang-runner/src/profiling_test_data/profiling#L220)):*
> ```
> 
> //! > sierra_code
> >>> file: ../../tests/test_data/fib_loop.sierra
> ```

maybe just do a trivial loop example here instead.
___
*[`examples/fib_loop.cairo` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4810#-NoCoSOn3S7zxSSsw7ji:-NoCoSOn3S7zxSSsw7jj:b-l6hdjr) ([raw file](https://github.com/starkware-libs/cairo/blob/4fc55f1aab955a29c945f91a14fc2362159041ca/examples/fib_loop.cairo#L2)):*
> ```Cairo
> 
> fn main() -> felt252 {
> ```

revert

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4810)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/profiling_test_data/profiling` line 220 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4810#-NoCogU80NfqocvN2h1U:-NopU178C2qtkl7Nm8kh:b-ogpmbj) ([raw file](https://github.com/starkware-libs/cairo/blob/4fc55f1aab955a29c945f91a14fc2362159041ca/crates/cairo-lang-runner/src/profiling_test_data/profiling#L220)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe just do a trivial loop example here instead.
</blockquote></details>

I can, but what's wrong with using fib_loop?
___
*[`examples/fib_loop.cairo` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4810#-NoCoSOn3S7zxSSsw7ji:-NopTuHM6_dEXjU6L3d5:b-ukxxx3) ([raw file](https://github.com/starkware-libs/cairo/blob/4fc55f1aab955a29c945f91a14fc2362159041ca/examples/fib_loop.cairo#L2)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

revert
</blockquote></details>

why? what's wrong with changing this?

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4810)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-runner/src/profiling.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4810#-NopbwikAUN7YRZWVB_Y:-NopbwikAUN7YRZWVB_Z:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/4fc55f1aab955a29c945f91a14fc2362159041ca/crates/cairo-lang-runner/src/profiling.rs#L98)):*
> ```XML
>             process_by_concrete_libfunc: true,
>             process_by_generic_libfunc: true,
>             process_by_user_function: true,          // TODO(yg): false
> ```

?
___
*[`crates/cairo-lang-runner/src/profiling_test_data/profiling` line 220 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4810#-NoCogU80NfqocvN2h1U:-Nopc8xzB4rZvc8mqy65:b1gd01n) ([raw file](https://github.com/starkware-libs/cairo/blob/4fc55f1aab955a29c945f91a14fc2362159041ca/crates/cairo-lang-runner/src/profiling_test_data/profiling#L220)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I can, but what's wrong with using fib_loop?
</blockquote></details>

since the testing is actually clear if i directly see what i'm seeing.
___
*[`examples/fib_loop.cairo` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4810#-NoCoSOn3S7zxSSsw7ji:-NopcEKuEqQ609xUUfV8:b-jjpvew) ([raw file](https://github.com/starkware-libs/cairo/blob/4fc55f1aab955a29c945f91a14fc2362159041ca/examples/fib_loop.cairo#L2)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

why? what's wrong with changing this?
</blockquote></details>

i don't want us to have this sort of changes in the examples - that is why i'd rather have the code directly at the profiling test.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4810#-:-NopqIol9IxDy6owejrF:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

___
*[`crates/cairo-lang-runner/src/profiling_test_data/profiling` line 216 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4810#-NopqCV61iZ6FNlzITsR:-NopqCV61iZ6FNlzITsS:b-7m74ox) ([raw file](https://github.com/starkware-libs/cairo/blob/82650c3bb4907d49216afa0e8879e09eee5c0c3f/crates/cairo-lang-runner/src/profiling_test_data/profiling#L216)):*
> ```
> //! > Test profiling info of a program with a simple loop
> 
> //! > TODO(yuval): change to Cairo code once the tests get Cairo:
> ```

nice!

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4810)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
