### PR TITLE
Added phantom types checks.

### PR DESCRIPTION
**Pull request by orizi**
Additionally prevented recursive type checks for phantom.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5482)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/items/enm.rs` line 253 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5482#-Nwhb5sX1wb5JTmUXSjM:-Nwhb5sX1wb5JTmUXSjN:bih9ei9) ([raw file](https://github.com/starkware-libs/cairo/blob/b327fb273c2497ef6ee7a82b7692f1a3de9acd0e/crates/cairo-lang-semantic/src/items/enm.rs#L253)):*
> ```XML
>     if enum_id.has_attr(db, PHANTOM_ATTR).unwrap_or_default() {
>         return data.diagnostics;
>     }
> ```

?

why not '?'
and why are you returning data.diagnostics in case has_attr is true??



_Code quote:_
```XML
    if enum_id.has_attr(db, PHANTOM_ATTR).unwrap_or_default() {
        return data.diagnostics;
    }
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5482)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/items/enm.rs` line 253 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5482#-Nwhb5sX1wb5JTmUXSjM:-NwhdRH60rbfVWWRCGTP:bl3lomc) ([raw file](https://github.com/starkware-libs/cairo/blob/b327fb273c2497ef6ee7a82b7692f1a3de9acd0e/crates/cairo-lang-semantic/src/items/enm.rs#L253)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

?

why not '?'
and why are you returning data.diagnostics in case has_attr is true??
</blockquote></details>

it isn't an error if the enum is phantom - non of the extra checks are relevant if the type is phantom - just returning the existing diagnostics (if any)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/items/enm.rs` line 253 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5482#-Nwhb5sX1wb5JTmUXSjM:-NwhdyKo49dm2P3EObTX:b-uxucgc) ([raw file](https://github.com/starkware-libs/cairo/blob/b327fb273c2497ef6ee7a82b7692f1a3de9acd0e/crates/cairo-lang-semantic/src/items/enm.rs#L253)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it isn't an error if the enum is phantom - non of the extra checks are relevant if the type is phantom - just returning the existing diagnostics (if any)
</blockquote></details>

the unwrap_or_default instead of `?` is also weird to we do it elsewhere in the code?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/items/enm.rs` line 253 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5482#-Nwhb5sX1wb5JTmUXSjM:-NwhehA3D-iifAfhFX2X:b8mqu5h) ([raw file](https://github.com/starkware-libs/cairo/blob/b327fb273c2497ef6ee7a82b7692f1a3de9acd0e/crates/cairo-lang-semantic/src/items/enm.rs#L253)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

the unwrap_or_default instead of `?` is also weird to we do it elsewhere in the code?
</blockquote></details>

can you document it?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5482)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/items/enm.rs` line 253 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5482#-Nwhb5sX1wb5JTmUXSjM:-NwhgLnp0xNVfc5ORu-F:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b327fb273c2497ef6ee7a82b7692f1a3de9acd0e/crates/cairo-lang-semantic/src/items/enm.rs#L253)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

can you document it?
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5482#-:-NwhiUkX2oOtJtytvU0L:bnfp4nl)* status: 3 of 5 files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
