### PR TITLE
Enabling gas calculation not based on lp.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #4447
- #4439 ⬅
- #4438

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4439)

### CODE REVIEW

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4439#-:-Njqfweu4odWMV6xTlEo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4439)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs` line 127 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4439#-NmVXOTTBOV3zmV5v85e:-NmVXOTTBOV3zmV5v85f:b-hqv5hk) ([raw file](https://github.com/starkware-libs/cairo/blob/4a00cf2c876f30c1789687275aab4f6152eedc2a/crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs#L127)):*
> ```XML
>         .ok_or(InvocationError::UnknownVariableData)?;
> 
>     check_zero_precost_values(variable_values, builder.idx)?;
> ```

Revert. This libfunc is still not supported for builtins.
___
*[`crates/cairo-lang-starknet/src/casm_contract_class.rs` line 351 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4439#-NmVX4tg8a6101BPurHM:-NmVX4tg8a6101BPurHN:b-tit9d2) ([raw file](https://github.com/starkware-libs/cairo/blob/61791e5298cd92ea50fdedeb2fe390ec510e4d85/crates/cairo-lang-starknet/src/casm_contract_class.rs#L351)):*
> ```XML
>             linear_gas_solver: no_eq_solver,
>             linear_ap_change_solver: no_eq_solver,
>             skip_comparisons: false,
> ```

Shouldn't this depend on `sierra_version >= 5`?

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4439)* status: 7 of 9 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/metadata.rs` line 44 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4439#-NmVXzyC8s6l-E6QJoW5:-NmVXzyC8s6l-E6QJoW6:bt22p6x) ([raw file](https://github.com/starkware-libs/cairo/blob/61791e5298cd92ea50fdedeb2fe390ec510e4d85/crates/cairo-lang-sierra-to-casm/src/metadata.rs#L44)):*
> ```XML
>     /// equations.
>     pub linear_ap_change_solver: bool,
>     /// Do not check for contradictions between solutions.
> ```

This flag is relevant only if `linear_gas_solver = false`, right? Mention this in the doc.

Consider putting this field directly after `linear_gas_solver`, and consider adding the word `gas` to it.
___
*[`crates/cairo-lang-sierra-to-casm/src/metadata.rs` line 88 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4439#-NmVYOhK6n0yaFFiZt31:-NmVYOhK6n0yaFFiZt32:b-4n6dqo) ([raw file](https://github.com/starkware-libs/cairo/blob/4a00cf2c876f30c1789687275aab4f6152eedc2a/crates/cairo-lang-sierra-to-casm/src/metadata.rs#L88)):*
> ```XML
>         .collect();
>     let pre_gas_info_new = compute_precost_info(program)?;
>     let pre_gas_info_old = calc_gas_precost_info(program, pre_function_set_costs)?;
> ```

Are you sure it's ok to remove this check starting from 0.1.4? (which is what this PR is doing)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4439)* status: 7 of 9 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/metadata.rs` line 88 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4439#-NmVYOhK6n0yaFFiZt31:-NmVZ2H1BVy8mgv8L3en:b-3t38oy) ([raw file](https://github.com/starkware-libs/cairo/blob/4a00cf2c876f30c1789687275aab4f6152eedc2a/crates/cairo-lang-sierra-to-casm/src/metadata.rs#L88)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Are you sure it's ok to remove this check starting from 0.1.4? (which is what this PR is doing)
</blockquote></details>

Sorry - 1.4.0
___
*[`crates/cairo-lang-sierra-to-casm/src/metadata.rs` line 134 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4439#-NmVZ-lg561-7m0xxw4o:-NmVZ-lg561-7m0xxw4p:b-7gbo4p) ([raw file](https://github.com/starkware-libs/cairo/blob/4a00cf2c876f30c1789687275aab4f6152eedc2a/crates/cairo-lang-sierra-to-casm/src/metadata.rs#L134)):*
> ```XML
>         )?;
> 
>         post_gas_info.assert_eq_functions(&post_gas_info2);
> ```

Is it ok to remove this assert starting 1.4.0?

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 2 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4439)* status: all files reviewed, 5 unresolved discussions (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4439)* status: all files reviewed, 5 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/metadata.rs` line 88 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4439#-NmVYOhK6n0yaFFiZt31:-NmVbHb-CTGbyvVrxNY6:b-x738c1) ([raw file](https://github.com/starkware-libs/cairo/blob/4a00cf2c876f30c1789687275aab4f6152eedc2a/crates/cairo-lang-sierra-to-casm/src/metadata.rs#L88)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Sorry - 1.4.0
</blockquote></details>

must be removed for the tests not to crash.
___
*[`crates/cairo-lang-sierra-to-casm/src/metadata.rs` line 134 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4439#-NmVZ-lg561-7m0xxw4o:-NmVcSI98UAwII1wS7jk:b-x738c1) ([raw file](https://github.com/starkware-libs/cairo/blob/4a00cf2c876f30c1789687275aab4f6152eedc2a/crates/cairo-lang-sierra-to-casm/src/metadata.rs#L134)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Is it ok to remove this assert starting 1.4.0?
</blockquote></details>

must be removed for the tests not to crash.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs` line 127 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4439#-NmVXOTTBOV3zmV5v85e:-NmVbzt64GbZBpB7Dkrx:b-3lsymo) ([raw file](https://github.com/starkware-libs/cairo/blob/4a00cf2c876f30c1789687275aab4f6152eedc2a/crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs#L127)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Revert. This libfunc is still not supported for builtins.
</blockquote></details>

it is supported for builtin - the metadata_computations and gas tests call it.
(after i do a simple rebase)
___
*[`crates/cairo-lang-starknet/src/casm_contract_class.rs` line 351 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4439#-NmVX4tg8a6101BPurHM:-NmVbaws8ky8oiwC_gwM:bomn411) ([raw file](https://github.com/starkware-libs/cairo/blob/61791e5298cd92ea50fdedeb2fe390ec510e4d85/crates/cairo-lang-starknet/src/casm_contract_class.rs#L351)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Shouldn't this depend on `sierra_version >= 5`?
</blockquote></details>

not really - it would only be provided with functions requiring it post 5, but would work just fine with 4s as well.

**Pull request closed without merging**
