### PR TITLE
Moved cairo corelib tests into the corelib.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:e5751420

---

**Stack**:
- #1232
- #1231
- #1230
- #1229
- #1228 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1228)* status: all files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`corelib/test.cairo` line 11 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1228#-NIaiJfN53OGWr0kUeP0:-NIaiJfN53OGWr0kUeP1:b-muxamk) ([raw file](https://github.com/starkware-libs/cairo/blob/21409a9e96633cce3bc98e45603b7bfef238920f/corelib/test.cairo#L11)):*
> ```Cairo
>     assert(true, 1);
> }
> ```

consider defining the uint128 powers of 2 you use here in the global test scope, and reuse them (if possible)
___
*[`corelib/test.cairo` line 103 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1228#-NIahQ0VEfvIdx6T1Q1e:-NIahQ0VEfvIdx6T1Q1f:b867ifd) ([raw file](https://github.com/starkware-libs/cairo/blob/21409a9e96633cce3bc98e45603b7bfef238920f/corelib/test.cairo#L103)):*
> ```Cairo
> #[should_panic]
> func test_uint128_sub_overflow_4() {
>     uint128_from_felt(100) - uint128_from_felt(1000);
> ```

are all four of these really necessary?



_Code quote:_
```Cairo
#[test]
#[should_panic]
func test_uint128_sub_overflow_1() {
    uint128_from_felt(0) - uint128_from_felt(1);
}

#[test]
#[should_panic]
func test_uint128_sub_overflow_2() {
    uint128_from_felt(0) - uint128_from_felt(3);
}

#[test]
#[should_panic]
func test_uint128_sub_overflow_3() {
    uint128_from_felt(1) - uint128_from_felt(3);
}

#[test]
#[should_panic]
func test_uint128_sub_overflow_4() {
    uint128_from_felt(100) - uint128_from_felt(1000);
}
```
___
*[`corelib/test.cairo` line 110 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1228#-NIahpaP7wCXiTeZUeb_:-NIahpaP7wCXiTeZUeba:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/21409a9e96633cce3bc98e45603b7bfef238920f/corelib/test.cairo#L110)):*
> ```Cairo
> func test_uint128_add_overflow_1() {
>     let pow_2_127 = 170141183460469231731687303715884105728;
>     uint128_from_felt(pow_2_127) + uint128_from_felt(pow_2_127);
> ```





_Suggestion:_
```Cairo
    let pow_2_127 = uint128_from_felt(170141183460469231731687303715884105728);
    pow_2_127 + pow_2_127;
```
___
*[`corelib/test.cairo` line 123 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1228#-NIaiFcB9f8N5Df7dLGB:-NIaiFcB9f8N5Df7dLGC:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/21409a9e96633cce3bc98e45603b7bfef238920f/corelib/test.cairo#L123)):*
> ```Cairo
> #[should_panic]
> func test_uint128_mul_overflow_1() {
>     uint128_from_felt(18446744073709551616) * uint128_from_felt(18446744073709551616);
> ```





_Suggestion:_
```Cairo
let pow_2_64 = uint128_from_felt(18446744073709551616);
pow_2_64 * pow_2_64;
```
___
*[`corelib/test.cairo` line 129 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1228#-NIai492EJhU30YQe_T9:-NIai492EJhU30YQe_TA:b196v1b) ([raw file](https://github.com/starkware-libs/cairo/blob/21409a9e96633cce3bc98e45603b7bfef238920f/corelib/test.cairo#L129)):*
> ```Cairo
> #[should_panic]
> func test_uint128_mul_overflow_2() {
>     uint128_from_felt(18446744073709551617) * uint128_from_felt(18446744073709551616);
> ```

```
let pow_2_64 = uint128_from_felt(18446744073709551616);
(pow_2_64 + uint128_from_felt(1)) * pow_2_64;
```
?



_Code quote:_
```Cairo
uint128_from_felt(18446744073709551617) * uint128_from_felt(18446744073709551616);
```
___
*[`corelib/test.cairo` line 146 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1228#-NIaia403uBVX9PHdTBY:-NIaia403uBVX9PHdTBZ:boaffr2) ([raw file](https://github.com/starkware-libs/cairo/blob/21409a9e96633cce3bc98e45603b7bfef238920f/corelib/test.cairo#L146)):*
> ```Cairo
> #[test]
> #[should_panic]
> func test_uint128_div_by_0() {
> ```

duplicated



_Code quote:_
```Cairo
#[test]
#[should_panic]
func test_uint128_div_by_0() {
    uint128_from_felt(2) / uint128_from_felt(0);
}

#[test]
#[should_panic]
func test_uint128_div_by_0() {
    uint128_from_felt(2) / uint128_from_felt(0);
}
```
___
*[`corelib/test.cairo` line 186 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1228#-NIaij0F5nJeAr5a9N0v:-NIaij0F5nJeAr5a9N0w:br9fiti) ([raw file](https://github.com/starkware-libs/cairo/blob/21409a9e96633cce3bc98e45603b7bfef238920f/corelib/test.cairo#L186)):*
> ```Cairo
> #[test]
> #[should_panic]
> func test_array_out_of_bound_2() {
> ```

I think one of these is enough, no?



_Code quote:_
```Cairo
#[test]
#[should_panic]
func test_array_out_of_bound_1() {
    test_array_helper(3);
}

#[test]
#[should_panic]
func test_array_out_of_bound_2() {
    test_array_helper(11);
}
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1228)* status: all files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware and @ilyalesokhin-starkware)

___
*[`corelib/test.cairo` line 103 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1228#-NIahQ0VEfvIdx6T1Q1e:-NIal2hd5ZdreZA02ldk:biix8ty) ([raw file](https://github.com/starkware-libs/cairo/blob/2bb0e64ddeb735b52828f8777478bfc3554d67c2/corelib/test.cairo#L103)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

are all four of these really necessary?
</blockquote></details>

wanted some variance -generally - i think maybe later we might add some extreme test suite auto generated from some random.
___
*[`corelib/test.cairo` line 110 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1228#-NIahpaP7wCXiTeZUeb_:-NIalaZ5-yo6rD_t3kh4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2bb0e64ddeb735b52828f8777478bfc3554d67c2/corelib/test.cairo#L110)):*
> ```Cairo
> func test_uint128_add_overflow_1() {
>     let pow_2_127 = 170141183460469231731687303715884105728;
>     uint128_from_felt(pow_2_127) + uint128_from_felt(pow_2_127);
> ```

Done.



_Code quote:_
```Cairo
test_uint128_add_overflow_1
```
___
*[`corelib/test.cairo` line 123 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1228#-NIaiFcB9f8N5Df7dLGB:-NIalrxv2MNWXoCcK7x9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2bb0e64ddeb735b52828f8777478bfc3554d67c2/corelib/test.cairo#L123)):*
> ```Cairo
> #[should_panic]
> func test_uint128_mul_overflow_1() {
>     uint128_from_felt(18446744073709551616) * uint128_from_felt(18446744073709551616);
> ```

Done.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1228)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @ilyalesokhin-starkware)

___
*[`corelib/test.cairo` line 129 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1228#-NIai492EJhU30YQe_T9:-NIaoz2n9X4jOTIkfeDN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2bb0e64ddeb735b52828f8777478bfc3554d67c2/corelib/test.cairo#L129)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

```
let pow_2_64 = uint128_from_felt(18446744073709551616);
(pow_2_64 + uint128_from_felt(1)) * pow_2_64;
```
?
</blockquote></details>

Done.
___
*[`corelib/test.cairo` line 146 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1228#-NIaia403uBVX9PHdTBY:-NIap4TmDkYkE4Hnv8aI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2bb0e64ddeb735b52828f8777478bfc3554d67c2/corelib/test.cairo#L146)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

duplicated
</blockquote></details>

Done.
___
*[`corelib/test.cairo` line 186 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1228#-NIaij0F5nJeAr5a9N0v:-NIap6N4AOTNuIBbhvd3:b-qraccn) ([raw file](https://github.com/starkware-libs/cairo/blob/2bb0e64ddeb735b52828f8777478bfc3554d67c2/corelib/test.cairo#L186)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think one of these is enough, no?
</blockquote></details>

definitely not - access one over the size of the array - and further ahead are very different.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1228#-:-NIbClqeBZvQZiBep6sT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1228)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
