### PR TITLE
ABI generation for the new contract syntax

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3316)

### CODE REVIEW

**Comment by yuvalsw** [comment]
change target branch

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3316)* status: 0 of 22 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-plugins/src/test_data/generate_trait` line 185 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3316#-NXJlnJo4cEnw1gLF3ZF:-NXJlnJo4cEnw1gLF3ZG:b2nhexc) ([raw file](https://github.com/starkware-libs/cairo/blob/9ce64ffff08337f3b1d4dfb6bbeadcf6dfe58716/crates/cairo-lang-plugins/src/test_data/generate_trait#L185)):*
> ```
> //! > ==========================================================================
> 
> //! > TODO(yg)
> ```

Fix



_Code quote:_
```
 TODO(yg)
```

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3316)* status: 0 of 22 files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/items/trt.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3316#-NXJm0_5Adm6QGYKOmiN:-NXJm0_5Adm6QGYKOmiO:b-8uyvmm) ([raw file](https://github.com/starkware-libs/cairo/blob/9ce64ffff08337f3b1d4dfb6bbeadcf6dfe58716/crates/cairo-lang-semantic/src/items/trt.rs#L76)):*
> ```XML
>         db.lookup_intern_concrete_trait(*self).generic_args
>     }
>     pub fn name(&self, db: &dyn SemanticGroup) -> SmolStr {
> ```

When exporting to ABI I tihnk we should use the full path

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3316)* status: 0 of 22 files reviewed, 6 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/abi.rs` line 72 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3316#-NXJzgcxA7T7g6VcfiPb:-NXJzgcxA7T7g6VcfiPc:b-1pjqef) ([raw file](https://github.com/starkware-libs/cairo/blob/9ce64ffff08337f3b1d4dfb6bbeadcf6dfe58716/crates/cairo-lang-starknet/src/abi.rs#L72)):*
> ```XML
>                             generic_args: vec![],
>                         })),
>                     )));
> ```

Move out of the else.



_Code quote:_
```XML
                    storage_type = Some(db.intern_type(TypeLongId::Concrete(
                        ConcreteTypeId::Struct(db.intern_concrete_struct(ConcreteStructLongId {
                            struct_id: id,
                            generic_args: vec![],
                        })),
                    )));
```
___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 91 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3316#-NXK-D8hC0U-sLd2H5Lh:-NXK-D8hC0U-sLd2H5Li:ba854ie) ([raw file](https://github.com/starkware-libs/cairo/blob/9ce64ffff08337f3b1d4dfb6bbeadcf6dfe58716/crates/cairo-lang-starknet/src/plugin/contract.rs#L91)):*
> ```XML
>         return None;
>     }
>     let module_ast: ast::ItemModule = ast::ItemModule::from_syntax_node(db, module_node);
> ```

Revert?

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 22 files at r5, 1 of 15 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3316)* status: 2 of 34 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/test_data/new_syntax_test_contract.sierra.json` line 2368 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3316#-NXKIpmE4XLnSIMD7MyB:-NXKIpmE4XLnSIMD7MyC:b69z4x1) ([raw file](https://github.com/starkware-libs/cairo/blob/a9e91e8f29587d9abaa202f057249165136f16a8/crates/cairo-lang-starknet/test_data/new_syntax_test_contract.sierra.json#L2368)):*
> ```JSON
>     {
>       "type": "interface",
>       "name": "ICounterContract",
> ```

Again, I tihnk this should be fully qualified, like in types.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3316)* status: 1 of 34 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-starknet/test_data/new_syntax_test_contract.sierra.json` line 2368 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3316#-NXKIpmE4XLnSIMD7MyB:-NXKXmoC5vkQUlhwqOCD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a9e91e8f29587d9abaa202f057249165136f16a8/crates/cairo-lang-starknet/test_data/new_syntax_test_contract.sierra.json#L2368)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Again, I tihnk this should be fully qualified, like in types.
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 14 of 22 files at r5, 13 of 15 files at r6, 2 of 5 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3316#-:-NXKjdyB6va_1q1-mV23:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
