### PR TITLE
added associated type args in semantic

### PR DESCRIPTION
**Pull request by TomerStarkware**

### CODE REVIEW

**Review by mkaput — COMMENTED** [review]
> Reviewed 1 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6745)* status: 1 of 12 files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

**Review by mkaput — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6745)* status: 1 of 12 files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6745)* status: 1 of 12 files reviewed, 3 unresolved discussions (waiting on @mkaput and @TomerStarkware)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6745#-OCcgg5V-0OZLES0iYZ1:-OCcgg5V-0OZLES0iYZ2:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c0171474befa40a403f386c7a0a5912d35c54557/crates/cairo-lang-filesystem/src/db.rs#L153)):*
> ```XML
> pub struct ExperimentalFeaturesConfig {
>     pub negative_impls: bool,
>     pub type_constraints_syntax: bool,
> ```





_Suggestion:_
```XML
    pub associated_item_constraints: bool,
```
___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 884 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6745#-OCcgv0V3BqJDxWyiYiL:-OCcgv0X6NuqjdMAT2lI:bqwwc1f) ([raw file](https://github.com/starkware-libs/cairo/blob/c0171474befa40a403f386c7a0a5912d35c54557/crates/cairo-lang-semantic/src/diagnostic.rs#L884)):*
> ```XML
>                     "associated type `{}` not found for `{:?}`",
>                     identifier,
>                     concrete_trait_id.debug(db)
> ```

or something of that sort?



_Suggestion:_
```XML
                    concrete_trait_id.full_path(db)
```
___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 893 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6745#-OCcgzuL2xcRLwyzbcD6:-OCcgzuL2xcRLwyzbcD7:b-5h08c7) ([raw file](https://github.com/starkware-libs/cairo/blob/c0171474befa40a403f386c7a0a5912d35c54557/crates/cairo-lang-semantic/src/diagnostic.rs#L893)):*
> ```XML
>                     "the value of the associated type `{:?}` in trait `{:?}` is already specified",
>                     trait_type_id.trait_type(db).name(db.upcast()),
>                     trait_type_id.concrete_trait(db).debug(db)
> ```

same here.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6745)* status: 0 of 15 files reviewed, 3 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 884 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6745#-OCcgv0V3BqJDxWyiYiL:-OCd2UFi50gRLN6vu5o4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c0171474befa40a403f386c7a0a5912d35c54557/crates/cairo-lang-semantic/src/diagnostic.rs#L884)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

or something of that sort?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 893 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6745#-OCcgzuL2xcRLwyzbcD6:-OCd2kYhDOUjU2MnEKjg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c0171474befa40a403f386c7a0a5912d35c54557/crates/cairo-lang-semantic/src/diagnostic.rs#L893)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

same here.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-filesystem/src/db.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6745#-OCcgg5V-0OZLES0iYZ1:-OCd2Ncl0g5kRM_ha5Ji:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c0171474befa40a403f386c7a0a5912d35c54557/crates/cairo-lang-filesystem/src/db.rs#L153)):*
> ```XML
> pub struct ExperimentalFeaturesConfig {
>     pub negative_impls: bool,
>     pub type_constraints_syntax: bool,
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 12 files at r1, 2 of 5 files at r2, 4 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6745)* status: 9 of 15 files reviewed, 7 unresolved discussions (waiting on @mkaput and @TomerStarkware)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 153 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6745#-OCd4SvrCI6EScZKK2Xx:-OCd4SvrCI6EScZKK2Xy:bvs1fqt) ([raw file](https://github.com/starkware-libs/cairo/blob/497377de1f1e2c810a7ace4561e07dd81383ed30/crates/cairo-lang-filesystem/src/db.rs#L153)):*
> ```XML
> pub struct ExperimentalFeaturesConfig {
>     pub negative_impls: bool,
>     pub associated_item_constraints: bool,
> ```

doc flag.
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 1373 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6745#-OCd48DMCXTVvotQT5e6:-OCd48DMCXTVvotQT5e7:bmfw81a) ([raw file](https://github.com/starkware-libs/cairo/blob/cec807a2c087a16b65e1e13ac6d26abaca186fd6/crates/cairo-lang-semantic/src/resolve/mod.rs#L1373)):*
> ```XML
>                     ))
>                     .intern(self.db);
>                     self.inference().conform_ty(ty0, *ty1).ok();
> ```

why is ignoring the error ok?
doc and explain.



_Code quote:_
```XML
                    self.inference().conform_ty(ty0, *ty1).ok();
```
___
*[`crates/cairo-lang-semantic/src/expr/inference/infers.rs` line 384 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6745#-OCd4iVPEUCDuOdskWxP:-OCd4iVPEUCDuOdskWxQ:b-e40a5d) ([raw file](https://github.com/starkware-libs/cairo/blob/cec807a2c087a16b65e1e13ac6d26abaca186fd6/crates/cairo-lang-semantic/src/expr/inference/infers.rs#L384)):*
> ```XML
>                         self.db,
>                     ))?;
>                     self.conform_ty(ty0, *ty1).ok();
> ```

again - why is ignoring the conform is ok?
doc.
___
*[`crates/cairo-lang-semantic/src/test_utils.rs` line 139 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6745#-OCd4a6-3XtZe8Lx3Lip:-OCd4a6-3XtZe8Lx3Liq:b-hay66z) ([raw file](https://github.com/starkware-libs/cairo/blob/cec807a2c087a16b65e1e13ac6d26abaca186fd6/crates/cairo-lang-semantic/src/test_utils.rs#L139)):*
> ```XML
> 
>     let settings: CrateSettings = if let Some(crate_settings) = crate_settings {
>         println!("crate_settings: {}", crate_settings);
> ```

revert.
___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 457 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6745#-OCd2tav9Bn36fOO15tx:-OCd2tav9Bn36fOO15ty:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/cec807a2c087a16b65e1e13ac6d26abaca186fd6/crates/cairo-lang-semantic/src/items/generics.rs#L457)):*
> ```XML
>     let owning_crate = module_file_id.0.owning_crate(db.upcast());
>     let Some(config) = db.crate_config(owning_crate) else { return false };
>     config.settings.experimental_features.type_constraints_syntax
> ```





_Suggestion:_
```XML
    db.crate_config(owning_crate).is_some_and(|c| c.settings.experimental_features.type_constraints_syntax);
```
___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 510 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6745#-OCd3fT_CaxVDgRbSFlV:-OCd3fT_CaxVDgRbSFlW:bbkszva) ([raw file](https://github.com/starkware-libs/cairo/blob/cec807a2c087a16b65e1e13ac6d26abaca186fd6/crates/cairo-lang-semantic/src/items/generics.rs#L510)):*
> ```XML
>                 item_constrains,
>                 id,
>             ))
> ```

seems like a function to be extracted as well.



_Code quote:_
```XML
            let path_syntax = syntax.trait_path(db.upcast());
            let item_constrains = item_constraints_into_option(syntax.type_constrains(db.upcast()));
            GenericParam::Impl(impl_generic_param_semantic(
                db,
                resolver,
                diagnostics,
                &path_syntax,
                item_constrains,
                id,
            ))
        }
        ast::GenericParam::ImplAnonymous(syntax) => {
            let path_syntax = syntax.trait_path(db.upcast());
            let item_constrains = item_constraints_into_option(syntax.type_constrains(db.upcast()));
            GenericParam::Impl(impl_generic_param_semantic(
                db,
                resolver,
                diagnostics,
                &path_syntax,
                item_constrains,
                id,
            ))
```
___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 550 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6745#-OCd56rZ95fndGbBMUmm:-OCd56rZ95fndGbBMUmn:b-llgkir) ([raw file](https://github.com/starkware-libs/cairo/blob/cec807a2c087a16b65e1e13ac6d26abaca186fd6/crates/cairo-lang-semantic/src/items/generics.rs#L550)):*
> ```XML
>             })
>         });
>     let type_constraints = concrete_trait
> ```

you should probably just built incrementally - this seems unclear, specifically the level of indenetation.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 12 files at r1, 3 of 10 files at r3, 6 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6745)* status: 14 of 15 files reviewed, 3 unresolved discussions (waiting on @mkaput and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 2649 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6745#-OCiIzwH--RbkB_4WDVx:-OCiIzwH--RbkB_4WDVy:b99h8jh) ([raw file](https://github.com/starkware-libs/cairo/blob/72c60a6a7d01425fc2cd86758970aeaf7ae0c180/crates/cairo-lang-semantic/src/items/tests/trait_type#L2649)):*
> ```
> //! > ==========================================================================
> 
> //! > Associated type bounds syntax.
> ```

i dont understand.



_Code quote:_
```
/! > Associated type bounds syntax.
```
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 2656 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6745#-OCiIr9rB8ddBHIJp0EZ:-OCiIr9sCbcjovIPonu5:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/72c60a6a7d01425fc2cd86758970aeaf7ae0c180/crates/cairo-lang-semantic/src/items/tests/trait_type#L2656)):*
> ```
> //! > function
> fn bar<+MyTrait[ty: felt252]>(_y: MyTrait::ty) -> felt252 {
>     _y + 3
> ```





_Suggestion:_
```
fn bar<+MyTrait[ty: felt252]>(y: MyTrait::ty) -> felt252 {
    y + 3
```
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 2672 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6745#-OCiJ1fH2StCv3SZ6nfc:-OCiJ1fH2StCv3SZ6nfd:b-xqiwis) ([raw file](https://github.com/starkware-libs/cairo/blob/72c60a6a7d01425fc2cd86758970aeaf7ae0c180/crates/cairo-lang-semantic/src/items/tests/trait_type#L2672)):*
> ```
> //! > ==========================================================================
> 
> //! > Associated type bounds syntax transitive.
> ```

i dont understand - these are semantic tests.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6745)* status: 14 of 15 files reviewed, 4 unresolved discussions (waiting on @mkaput and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 2767 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6745#-OCiJD9r2i2hyE0kdHRZ:-OCiJD9r2i2hyE0kdHR_:bp2s6zn) ([raw file](https://github.com/starkware-libs/cairo/blob/72c60a6a7d01425fc2cd86758970aeaf7ae0c180/crates/cairo-lang-semantic/src/items/tests/trait_type#L2767)):*
> ```
> //! > ==========================================================================
> 
> //! > Associated type bounds syntax, only bound associated types to another associated type wrong type. 
> ```

shorten name.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6745)* status: 14 of 15 files reviewed, 4 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 2649 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6745#-OCiIzwH--RbkB_4WDVx:-OCiJrh8DFZbgXzLc3eb:b-xvwh2m) ([raw file](https://github.com/starkware-libs/cairo/blob/72c60a6a7d01425fc2cd86758970aeaf7ae0c180/crates/cairo-lang-semantic/src/items/tests/trait_type#L2649)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i dont understand.
</blockquote></details>

just a simple test
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 2672 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6745#-OCiJ1fH2StCv3SZ6nfc:-OCiJz_L5sBj8P2Rhjaa:brmy2ew) ([raw file](https://github.com/starkware-libs/cairo/blob/72c60a6a7d01425fc2cd86758970aeaf7ae0c180/crates/cairo-lang-semantic/src/items/tests/trait_type#L2672)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i dont understand - these are semantic tests.
</blockquote></details>

? it checks that I1::ty = u8 && I2::ty == I1::ty => I2::ty = u8
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 2767 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6745#-OCiJD9r2i2hyE0kdHRZ:-OCiKTCwCDGp_cPoBZMs:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/72c60a6a7d01425fc2cd86758970aeaf7ae0c180/crates/cairo-lang-semantic/src/items/tests/trait_type#L2767)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

shorten name.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 2656 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6745#-OCiIr9rB8ddBHIJp0EZ:-OCiJu9_0qLROEchEVTx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/72c60a6a7d01425fc2cd86758970aeaf7ae0c180/crates/cairo-lang-semantic/src/items/tests/trait_type#L2656)):*
> ```
> //! > function
> fn bar<+MyTrait[ty: felt252]>(_y: MyTrait::ty) -> felt252 {
>     _y + 3
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6745)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 2697 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6745#-OCiLYQD5r4ZP2AagD8o:-OCiLYQD5r4ZP2AagD8p:b-o1t0sx) ([raw file](https://github.com/starkware-libs/cairo/blob/87f24676da9122d28a836c39d07cc6411a72fffc/crates/cairo-lang-semantic/src/items/tests/trait_type#L2697)):*
> ```
>                                                                             ^
> 
> //! > ==========================================================================
> ```

remove the word `syntax` all around.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6745)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 2697 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6745#-OCiLYQD5r4ZP2AagD8o:-OCljal59yjA3cojtrPf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/87f24676da9122d28a836c39d07cc6411a72fffc/crates/cairo-lang-semantic/src/items/tests/trait_type#L2697)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove the word `syntax` all around.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6745#-:-OCllw1W-F5J4ZQ94v2z:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6745)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
