### PR TITLE
Specify a single contract to compile

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2846)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2846)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2846#-NTC_RSF7qmi9UK57i9z:-NTC_RSF7qmi9UK57iA-:b4i0212) ([raw file](https://github.com/starkware-libs/cairo/blob/a16aa5d3abc3aba0430123cf3f648c2d002aa496/crates/cairo-lang-starknet/src/contract_class.rs#L78)):*
> ```XML
> /// Compile the contract given by path.
> ///
> /// Errors if no contracts or more than 1 are found.
> ```

Update doc
___
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2846#-NTC_ZY21j8fUrcbX84_:-NTC_ZY21j8fUrcbX84a:b-2k6d0m) ([raw file](https://github.com/starkware-libs/cairo/blob/a16aa5d3abc3aba0430123cf3f648c2d002aa496/crates/cairo-lang-starknet/src/contract_class.rs#L94)):*
> ```XML
> /// If no contract was specified, verify that there is only one.
> ///
> /// This function will return an error if no, or more than 1 contract is found.
> ```

Update doc

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2846#-:-NTC_pnp7ZwEofliNBZ2:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2846#-NTCaQGb6bOrI-NNcHhU:-NTCaQGcBVfUFqLel0cZ:b-o3ykg5) ([raw file](https://github.com/starkware-libs/cairo/blob/a16aa5d3abc3aba0430123cf3f648c2d002aa496/crates/cairo-lang-starknet/src/contract_class.rs#L118)):*
> ```XML
>                 contract_names
>             );
>         } else if contracts.is_empty() {
> ```

isn't it checked twice now?



_Code quote:_
```XML
if contracts.is_empty()
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2846)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2846#-NTC_RSF7qmi9UK57i9z:-NTCe0W5DKgK94nGo0y1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a16aa5d3abc3aba0430123cf3f648c2d002aa496/crates/cairo-lang-starknet/src/contract_class.rs#L78)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Update doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2846#-NTC_ZY21j8fUrcbX84_:-NTCdeuf5NI1d9VaHEea:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a16aa5d3abc3aba0430123cf3f648c2d002aa496/crates/cairo-lang-starknet/src/contract_class.rs#L94)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Update doc 
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2846#-NTCaQGb6bOrI-NNcHhU:-NTCdkpfBL2Ua_eosB7f:bp34mgv) ([raw file](https://github.com/starkware-libs/cairo/blob/a16aa5d3abc3aba0430123cf3f648c2d002aa496/crates/cairo-lang-starknet/src/contract_class.rs#L118)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

isn't it checked twice now?
</blockquote></details>

Done.
I should have listened to copilot!! He was right, and I changed it:(

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2846)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2846#-NTCaQGb6bOrI-NNcHhU:-NTCg38q8MDZADhnXq__:b-nc9d90) ([raw file](https://github.com/starkware-libs/cairo/blob/a16aa5d3abc3aba0430123cf3f648c2d002aa496/crates/cairo-lang-starknet/src/contract_class.rs#L118)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Done.
I should have listened to copilot!! He was right, and I changed it:(
</blockquote></details>

I think you should me the
  ensure!(!contracts.is_empty(), "Contract not found.");
here.



_Code quote:_
```XML
  ensure!(!contracts.is_empty(), "Contract not found.");
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 5 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2846)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2846#-:-NTCgSD54DSyR3jRmehO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2846)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
