### PR TITLE
Removed equation when partially solving vars instead of adding.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3255)

### CODE REVIEW

**Comment by moodysalem** [comment]
Fixes #3031  (wasn't linked)

**Comment by tserg** [comment]
This fixes the issue for me as well. A single file of 60+ tests is working, and the test suite of around 120 tests can be run together.  :100:

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3255)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3255#-:-NWaJ9Sj7EGs3GLL5n6N:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
