### PR TITLE
Change StorageNode plugin to StorageInterfaces and add StorageTrait there.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6032)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 20 of 33 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6032)* status: 20 of 33 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/components/component` line 845 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6032#-O2-hZZlB8zn9X5yTESQ:-O2-hZZm5WHJSH2O36QF:b-2z12hk) ([raw file](https://github.com/starkware-libs/cairo/blob/f8c2c554bbc07560dffd930320c9abc9cef1b7ce/crates/cairo-lang-starknet/src/plugin/plugin_test_data/components/component#L845)):*
> ```
> type BaseType = StorageStorageBase;
>    fn storage(self: starknet::storage::FlattenedStorage<Storage>) -> StorageStorageBase {
>        
> ```

prevent whitespace here.



_Code quote:_
```
······
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6032)* status: 5 of 38 files reviewed, 1 unresolved discussion (waiting on @orizi and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/components/component` line 845 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6032#-O2-hZZlB8zn9X5yTESQ:-O2-q1JD5n79L6QkAjfW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f8c2c554bbc07560dffd930320c9abc9cef1b7ce/crates/cairo-lang-starknet/src/plugin/plugin_test_data/components/component#L845)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

prevent whitespace here.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 12 of 33 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6032)* status: 18 of 38 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/events` line 167 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6032#-O2-uvhA2_uy2jpRLsgg:-O2-uvhA2_uy2jpRLsgh:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/71473b03076c7c7388f0f45855eda51dd19a037c/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/events#L167)):*
> ```
> impl ASubPointersImpl of starknet::storage::SubPointers<A> {
>        type SubPointersType = ASubPointers;
>        fn sub_pointers(self: starknet::storage::StoragePointer<A>) -> ASubPointers {
> ```





_Suggestion:_
```
impl ASubPointersImpl of starknet::storage::SubPointers<A> {
    type SubPointersType = ASubPointers;
    fn sub_pointers(self: starknet::storage::StoragePointer<A>) -> ASubPointers {
```

**Review by orizi — COMMENTED** [review]
> Reviewed 20 of 33 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6032)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @Tomer-StarkWare)

**Pull request merged**
