### PR TITLE
LS: Expand Macro command (VSC)

### PR DESCRIPTION
**Pull request by Draggu**
**Stack**:
- #6076
- #6075
- #6074 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6074)* status: all files reviewed, 3 unresolved discussions (waiting on @Draggu and @orizi)

___
*[`vscode-cairo/package.json` line 176 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6074#-O2iJQRqB4Rhm2rGIEMR:-O2iJQRqB4Rhm2rGIEMS:b-i1vldf) ([raw file](https://github.com/starkware-libs/cairo/blob/3468f2213c8bbba2329774b0e69b57e83d24a669/vscode-cairo/package.json#L176)):*
> ```JSON
>     "vscode-textmate": "^9.0.0"
>   }
> }
> ```

missing endline. seems like your editor is missing EditorConfig integration
___
*[`vscode-cairo/src/textDocumentProviders.ts` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6074#-O2iL0KL0PjWK4QmcfQg:-O2iL0KL0PjWK4QmcfQh:bsbw582) ([raw file](https://github.com/starkware-libs/cairo/blob/3468f2213c8bbba2329774b0e69b57e83d24a669/vscode-cairo/src/textDocumentProviders.ts#L56)):*
> ```XML
>     };
> 
>     vscode.workspace.registerTextDocumentContentProvider("cairo-expand-macro", tdcp);
> ```

this returns disposables. can you please submit a PR to subscribe them when the language client is dropped (I think that's the correct place, but I might be wrong)
___
*[`vscode-cairo/src/textDocumentProviders.ts` line 65 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6074#-O2iKTqX3MJDMV33Dtbz:-O2iKTqX3MJDMV33Dtc-:b8gaiyn) ([raw file](https://github.com/starkware-libs/cairo/blob/3468f2213c8bbba2329774b0e69b57e83d24a669/vscode-cairo/src/textDocumentProviders.ts#L65)):*
> ```XML
>         return vscode.window.showTextDocument(document, vscode.ViewColumn.Two, true);
>     });
> }
> ```

same here with EOF EOL

**Review by mkaput — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6074)* status: all files reviewed, 3 unresolved discussions (waiting on @Draggu and @orizi)

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6074)* status: all files reviewed, 3 unresolved discussions (waiting on @Draggu)

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6074)* status: all files reviewed, 3 unresolved discussions (waiting on @Draggu)

___
*[`vscode-cairo/src/cairols.ts` line 48 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6074#-O2jO1sg6f16IHSajQU6:-O2jO1sg6f16IHSajQU7:bajaaqr) ([raw file](https://github.com/starkware-libs/cairo/blob/d0ac85617642bf93468d20fb20340e83fe24971b/vscode-cairo/src/cairols.ts#L48)):*
> ```XML
>   const registerDisposable = (disposable: { dispose(): unknown }) => {
>     ctx.extension.subscriptions.push(disposable);
>   };
> ```

It would be much more idiomatic to pass `ctx` around and push it to subscriptions as close to creation as possible

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6074)* status: all files reviewed, 1 unresolved discussion (waiting on @Draggu)

___
*[`vscode-cairo/src/textDocumentProviders.ts` line 34 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6074#-O3Dj6efBY_K3E-Lagpu:-O3Dj6efBY_K3E-Lagpv:bw09ecu) ([raw file](https://github.com/starkware-libs/cairo/blob/f39316c430b321d826519586ab4e99f345529436/vscode-cairo/src/textDocumentProviders.ts#L34)):*
> ```XML
>   string | null,
>   void
> >("cairo/expandMacro");
> ```

Could we please collect all LSP types in a separate module for visibility/discoverability?

**Review by Draggu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6074)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @mkaput and @orizi)

___
*[`vscode-cairo/src/textDocumentProviders.ts` line 34 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6074#-O3Dj6efBY_K3E-Lagpu:-O3HfSY71u4BoX4afWhk:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f39316c430b321d826519586ab4e99f345529436/vscode-cairo/src/textDocumentProviders.ts#L34)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Could we please collect all LSP types in a separate module for visibility/discoverability?
</blockquote></details>

Done.

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6074#-:-O3IYfQQEbPmszcCJDNT:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Draggu)

**Review by mkaput — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6074)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Draggu)

**Review by Arcticae — APPROVED** [review]

**Review by Arcticae — APPROVED** [review]
> Reviewed 2 of 3 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6074)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @piotmag769)

**Review by piotmag769 — APPROVED** [review]
> Reviewed 2 of 3 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6074)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Draggu)

**Comment by Draggu** [comment]
✓ Commit merged in pull request [#6076](https://github.com/starkware-libs/cairo/pull/6076)

**Pull request closed without merging**
