### PR TITLE
Support 0 length enum matches

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2575)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2575** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2575" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2575?utm_source=stack-comment).

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2575#-:-NR3TQTaEeoFTE4pIvHV:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 322 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2575#-NR3Suy51DPJEsDgsHo4:-NR3Suy51DPJEsDgsHo5:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d2d5aceb2a94fcfa8ca9cf6563807eb0c5252ccb/crates/cairo-lang-lowering/src/lower/context.rs#L322)):*
> ```XML
>     Panic(VariableId),
>     Return(VariableId, StableLocationOption),
>     /// Every match are is terminating - does not flow to parent scope
> ```





_Suggestion:_
```XML
/// Every match is terminating - does not flow to parent scope
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra/src/extensions/modules/enm.rs` line 231 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2575#-NR3TpIV9K7T71GUjg-f:-NR3TpIV9K7T71GUjg-g:b-iwt4jx) ([raw file](https://github.com/starkware-libs/cairo/blob/d2d5aceb2a94fcfa8ca9cf6563807eb0c5252ccb/crates/cairo-lang-sierra/src/extensions/modules/enm.rs#L231)):*
> ```XML
>             param_signatures: vec![enum_type.into()],
>             branch_signatures,
>             fallthrough: if is_empty { None } else { Some(0) },
> ```

why did you need to fix that?



_Code quote:_
```XML
 fallthrough: if is_empty { None } else { Some(0) },
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2575)* status: 9 of 11 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 322 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2575#-NR3R81_0uffmohuCvEN:-NR3_wPJ0e7auRj6xMv_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d2d5aceb2a94fcfa8ca9cf6563807eb0c5252ccb/crates/cairo-lang-lowering/src/lower/context.rs#L322)):*
> ```XML
>     Panic(VariableId),
>     Return(VariableId, StableLocationOption),
>     /// Every match are is terminating - does not flow to parent scope
> ```

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/enm.rs` line 231 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2575#-NR3TpIV9K7T71GUjg-f:-NR3_z5T4vpnrcxZxmRn:b-r7ubhr) ([raw file](https://github.com/starkware-libs/cairo/blob/d2d5aceb2a94fcfa8ca9cf6563807eb0c5252ccb/crates/cairo-lang-sierra/src/extensions/modules/enm.rs#L231)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why did you need to fix that?
</blockquote></details>

Because on 0 variant, we have no fallthrough. It failed down the line otherwise.
___
*[`tests/bug_samples/issue2567.cairo` line 12 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2575#-NR3YSLv2zpfix8TCa0W:-NR3_u6d0R2fIy71afMF:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f04bb85e1f9b1017e6e320ececbc978b9a1fe02b/tests/bug_samples/issue2567.cairo#L12)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

add a test that putting code after such much does not generate sierra code that fails the sierra_to_casm compilation.
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-to-casm/src/compiler_test.rs` line 384 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2575#-NR3fwLZ1o5IfsQM4Sk6:-NR3fwLZ1o5IfsQM4Sk7:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/d533f3fb1efd3eedbed3eeeb6f0de3a1e63adcc4/crates/cairo-lang-sierra-to-casm/src/compiler_test.rs#L384)):*
> ```XML
>             enum_match<never>([0]) { };
>             return();
>             
> ```

remove



_Code quote:_
```XML
············
```

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2575#-:-NR3gPEz6zP1EWK-0BPW:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
