### PR TITLE
Add storage getter.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1291)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1291)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`corelib/lib.cairo` line 189 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1291#-NJ4oo0Q87FwIz8I_cPm:-NJ4oo0Q87FwIz8I_cPn:btn27me) ([raw file](https://github.com/starkware-libs/cairo/blob/8ca227afca66655f5fbef46c5a21331ada4a2a4c/corelib/lib.cairo#L189)):*
> ```Cairo
> extern type StorageAddress;
> 
> extern func storage_address_const<address>() -> StorageAddress nopanic;
> ```

move all under starknet submodule (not necessarily in this pr)



_Code quote:_
```Cairo
// StarkNet

// Syscall Ptr
extern type SyscallPtr;
extern type StorageAddress;

extern func storage_address_const<address>() -> StorageAddress nopanic;
extern func storage_read_syscall(ref syscall_ptr: SyscallPtr, address: StorageAddress) -> felt nopanic;
```
___
*[`crates/starknet/src/plugin.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1291#-NJ4pjo9EGclJsiJb19C:-NJ4pjo9EGclJsiJb19D:b-o4tagw) ([raw file](https://github.com/starkware-libs/cairo/blob/8ca227afca66655f5fbef46c5a21331ada4a2a4c/crates/starknet/src/plugin.rs#L43)):*
> ```XML
> 
>     for member in struct_ast.members(db).elements(db) {
>         // TODO(ilya): Put this logic inside an inline module once inline modules are supported.
> ```

all the data is created in a virtual file - no need for inline modules at all currently, as the virtual files can generate actual modules.



_Code quote:_
```XML
// TODO(ilya): Put this logic inside an inline module once inline modules are supported.
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1291)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`crates/starknet/src/plugin.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1291#-NJ4pjo9EGclJsiJb19C:-NJ53IAP9a0B36bR1NqB:b9afdvi) ([raw file](https://github.com/starkware-libs/cairo/blob/8ca227afca66655f5fbef46c5a21331ada4a2a4c/crates/starknet/src/plugin.rs#L43)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't understand

How do I put 
read() under the name namespace without inline modules?
</blockquote></details>

the `code` field in the PluginResult means - which file + module would you put this data in.
since you are already within a module, this plugin result would say where to write the code.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1291)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/starknet/src/plugin.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1291#-NJ4pjo9EGclJsiJb19C:-NJ55O3d9st5bFNMfkzf:b-c4gofo) ([raw file](https://github.com/starkware-libs/cairo/blob/8ca227afca66655f5fbef46c5a21331ada4a2a4c/crates/starknet/src/plugin.rs#L43)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the `code` field in the PluginResult means - which file + module would you put this data in.
since you are already within a module, this plugin result would say where to write the code.
</blockquote></details>

I want the following code:
mod $name {
            func read(ref syscall_ptr: SyscallPtr) -> felt {
                let address = storage_address_const::<$address>();
                storage_read_syscall(syscall_ptr, address)
            }
}

but it requires inline modules.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1291)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`corelib/lib.cairo` line 189 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1291#-NJ4oo0Q87FwIz8I_cPm:-NJ56O6E6EpHar6bHck1:b-5yfh0m) ([raw file](https://github.com/starkware-libs/cairo/blob/8ca227afca66655f5fbef46c5a21331ada4a2a4c/corelib/lib.cairo#L189)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

What is the benefit? I would have to add a use statement for each item, right?
</blockquote></details>

yes - but we do that for everything else, and we can not actually put all the using statements here for now.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1291)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`crates/starknet/src/plugin.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1291#-NJ58mm2-WbpEVL95LBk:-NJ58mm2-WbpEVL95LBl:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/8ca227afca66655f5fbef46c5a21331ada4a2a4c/crates/starknet/src/plugin.rs#L33)):*
> ```XML
> }
> 
> fn handle_struct(db: &dyn SyntaxGroup, struct_ast: ast::ItemStruct) -> PluginResult {
> ```

doc



_Code quote:_
```XML
handle_struct
```
___
*[`crates/starknet/src/plugin.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1291#-NJ58nqFBWERqc5xo-ZW:-NJ58nqFBWERqc5xo-ZX:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/8ca227afca66655f5fbef46c5a21331ada4a2a4c/crates/starknet/src/plugin.rs#L63)):*
> ```XML
> }
> 
> fn handle_impl(db: &dyn SyntaxGroup, impl_ast: ast::ItemImpl) -> PluginResult {
> ```

doc



_Code quote:_
```XML
handle_impl
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1291#-:-NJ5HsnM0eLKya7d0IOO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1291)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 6 of 7 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1291#-:-NJ5N8KD1qe6HzBG3GY6:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/starknet/src/plugin.rs` line 65 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1291#-NJ5N0jq-3gUIYJuYSG1:-NJ5N0jq-3gUIYJuYSG2:bb7i84l) ([raw file](https://github.com/starkware-libs/cairo/blob/5a42db0f3b7a16edcdcd65b961cc46316ecec502/crates/starknet/src/plugin.rs#L65)):*
> ```XML
> }
> 
> /// If the struct is annotated with CONTRACT_IMPL_ATTR, generates wrappers for
> ```

impl



_Code quote:_
```XML
truct
```
___
*[`crates/starknet/src/plugin_test_data/starknet` line 18 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1291#-NJ5Ks9O4NYUcNMFUxA1:-NJ5Ks9O4NYUcNMFUxA2:bzi77ws) ([raw file](https://github.com/starkware-libs/cairo/blob/5a42db0f3b7a16edcdcd65b961cc46316ecec502/crates/starknet/src/plugin_test_data/starknet#L18)):*
> ```
> #[contract(TestContractImpl)]
> struct TestContract {
>     storage_var: felt,
> ```

to make it easier to understand this is a specific storage var.



_Suggestion:_
```
my_storage_var
```
___
*[`crates/starknet/src/plugin_test_data/starknet` line 46 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1291#-NJ5KRZ4--F4LEecIMXq:-NJ5KRZ551shHvOduraC:bifxgak) ([raw file](https://github.com/starkware-libs/cairo/blob/5a42db0f3b7a16edcdcd65b961cc46316ecec502/crates/starknet/src/plugin_test_data/starknet#L46)):*
> ```
> func get_storage_var(ref syscall_ptr: SyscallPtr) -> felt {
>     let address = starknet::storage_address_const::<0x37fe6583f0b27bf0827d87f21c448b20f8709dfc8e4efbdddb75a0b443df714>();
>     starknet::storage_read_syscall(syscall_ptr, address)
> ```

is this var needed? I think it's better to inline.



_Code quote:_
```
address
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1291)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @orizi and @yuvalsw)

___
*[`crates/starknet/src/plugin.rs` line 65 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1291#-NJ5N0jq-3gUIYJuYSG1:-NJ5OAzn0Pyk_Um1XQGp:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/5a42db0f3b7a16edcdcd65b961cc46316ecec502/crates/starknet/src/plugin.rs#L65)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

impl
</blockquote></details>

done.
___
*[`crates/starknet/src/plugin_test_data/starknet` line 18 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1291#-NJ5Ks9O4NYUcNMFUxA1:-NJ5OC47CoTPX4AJH42l:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/5a42db0f3b7a16edcdcd65b961cc46316ecec502/crates/starknet/src/plugin_test_data/starknet#L18)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

to make it easier to understand this is a specific storage var.
</blockquote></details>

done.
___
*[`crates/starknet/src/plugin_test_data/starknet` line 46 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1291#-NJ5KRZ4--F4LEecIMXq:-NJ5OCjZ4a_XfgMskyoc:b-vhhjxn) ([raw file](https://github.com/starkware-libs/cairo/blob/5a42db0f3b7a16edcdcd65b961cc46316ecec502/crates/starknet/src/plugin_test_data/starknet#L46)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

is this var needed? I think it's better to inline.
</blockquote></details>

not sure it is better, but ok.

**Review by orizi — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1291)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 7 files at r2, 1 of 2 files at r3, 5 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1291)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
