### PR TITLE
Added blocker for test assertions on none test mode.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5949)

### CODE REVIEW

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5949)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @maciektr, and @orizi)

___
*[`crates/cairo-lang-test-plugin/src/inline_macros/assert.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5949#-O0rvmxq8kE9SSF1CTu0:-O0rvmxq8kE9SSF1CTu1:b-ip91v1) ([raw file](https://github.com/starkware-libs/cairo/blob/103d4ed1fed3f9c40f2ef267edc8afebb095be7e/crates/cairo-lang-test-plugin/src/inline_macros/assert.rs#L174)):*
> ```XML
>                 format!("`{}` macro is only available in test mode.", Self::NAME),
>             ));
>         }
> ```

I remember from Slack discussions that the idea was to reduce the complexity of this macro on non-test `cfg` instead of erroring it. Have some discussions been happening out of my sight on this?

**Comment by maciektr** [comment]
*[`crates/cairo-lang-test-plugin/src/inline_macros/assert.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5949#-O0rvmxq8kE9SSF1CTu0:-O0rwdtW10Z_c31qkyOA:bf1qs3k) ([raw file](https://github.com/starkware-libs/cairo/blob/103d4ed1fed3f9c40f2ef267edc8afebb095be7e/crates/cairo-lang-test-plugin/src/inline_macros/assert.rs#L174)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I remember from Slack discussions that the idea was to reduce the complexity of this macro on non-test `cfg` instead of erroring it. Have some discussions been happening out of my sight on this?
</blockquote></details>

If we did what Marek suggests here, wouldn't it be possible to just add cfg attrs in Cairo, without passing the metadata to InlineMacro trait? :thinking:

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5949)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @maciektr, and @mkaput)

___
*[`crates/cairo-lang-test-plugin/src/inline_macros/assert.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5949#-O0rvmxq8kE9SSF1CTu0:-O0rx-Fq-KkCr32LpsjJ:b-9ekep9) ([raw file](https://github.com/starkware-libs/cairo/blob/103d4ed1fed3f9c40f2ef267edc8afebb095be7e/crates/cairo-lang-test-plugin/src/inline_macros/assert.rs#L174)):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

If we did what Marek suggests here, wouldn't it be possible to just add cfg attrs in Cairo, without passing the metadata to InlineMacro trait? :thinking:
</blockquote></details>

Agree with @maciektr here

**Comment by Arcticae** [comment]
*[`crates/cairo-lang-test-plugin/src/inline_macros/assert.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5949#-O0rvmxq8kE9SSF1CTu0:-O0rwSrq2BidmYJY8Wny:blvjwhd) ([raw file](https://github.com/starkware-libs/cairo/blob/103d4ed1fed3f9c40f2ef267edc8afebb095be7e/crates/cairo-lang-test-plugin/src/inline_macros/assert.rs#L174)):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

If we did what Marek suggests here, wouldn't it be possible to just add cfg attrs in Cairo, without passing the metadata to InlineMacro trait? :thinking:
</blockquote></details>

The idea was to fail with a simple "assert_eq failed" (or something similar), and while `cfg(test)` is turned on, have this simpler assertion version which wouldn't leak all the info when deployed

**Review by mkaput — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5949)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @maciektr, and @piotmag769)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5949)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @maciektr, and @mkaput)

___
*[`crates/cairo-lang-test-plugin/src/inline_macros/assert.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5949#-O0rvmxq8kE9SSF1CTu0:-O0ryLWLC2W5ii7Jw7Uf:b-62e05n) ([raw file](https://github.com/starkware-libs/cairo/blob/103d4ed1fed3f9c40f2ef267edc8afebb095be7e/crates/cairo-lang-test-plugin/src/inline_macros/assert.rs#L174)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

The idea was to fail with a simple "assert_eq failed" (or something similar), and while `cfg(test)` is turned on, have this simpler assertion version which wouldn't leak all the info when deployed
</blockquote></details>

for "reducing complexity of a macro" - you should have another macro. otherwise you have a "works in surprising ways" macro.

it isn't about "leaking info" it is about having a complex returned structure.

for varying options macro - we should have a much more complex name than `assert_eq`.

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5949)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @gilbens-starkware, @maciektr, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-test-plugin/src/inline_macros/assert.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5949#-O0rvmxq8kE9SSF1CTu0:-O0rzwQM7NaogWEioTYs:b-kivxvx) ([raw file](https://github.com/starkware-libs/cairo/blob/103d4ed1fed3f9c40f2ef267edc8afebb095be7e/crates/cairo-lang-test-plugin/src/inline_macros/assert.rs#L174)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

for "reducing complexity of a macro" - you should have another macro. otherwise you have a "works in surprising ways" macro.

it isn't about "leaking info" it is about having a complex returned structure.

for varying options macro - we should have a much more complex name than `assert_eq`.
</blockquote></details>

TBH, The fact that this macro is erroring compilation could also be interpreted as "works in surprising way". But I get your point.

Returning a static message (essentially boiling down to `assert!(lhs == rhs)`) seems to also be reducing complexity, isn't it?

I actually think if it wouldn't be more intuitive to use dev/release profile difference here instead of test/non-test

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5949)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @maciektr, and @mkaput)

___
*[`crates/cairo-lang-test-plugin/src/inline_macros/assert.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5949#-O0rvmxq8kE9SSF1CTu0:-O0sQEe96CaKV0gmVEmU:bs5l04u) ([raw file](https://github.com/starkware-libs/cairo/blob/103d4ed1fed3f9c40f2ef267edc8afebb095be7e/crates/cairo-lang-test-plugin/src/inline_macros/assert.rs#L174)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

TBH, The fact that this macro is erroring compilation could also be interpreted as "works in surprising way". But I get your point.

Returning a static message (essentially boiling down to `assert!(lhs == rhs)`) seems to also be reducing complexity, isn't it?

I actually think if it wouldn't be more intuitive to use dev/release profile difference here instead of test/non-test
</blockquote></details>

yes - but then i would expect the user to explicitly write it - as it is rather easy and clear.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5949)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @maciektr, and @mkaput)

___
*[`crates/cairo-lang-test-plugin/src/inline_macros/assert.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5949#-O0rvmxq8kE9SSF1CTu0:-O0sRS847pPWHQDNfGgz:b-cgll5m) ([raw file](https://github.com/starkware-libs/cairo/blob/103d4ed1fed3f9c40f2ef267edc8afebb095be7e/crates/cairo-lang-test-plugin/src/inline_macros/assert.rs#L174)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

yes - but then i would expect the user to explicitly write it - as it is rather easy and clear.
</blockquote></details>

and i wouldn't consider something that fails with an attached reason as surprising as something that works differently in different situations with it being apparent in any way.

**Review by piotmag769 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5949#-:-O0sRtu49nL7tj9WrfoY:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @maciektr, and @mkaput)

**Review by piotmag769 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5949)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @maciektr, and @mkaput)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5949#-:-O0sTMz5AUD4izR-FHOq:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @maciektr and @mkaput)

**Review by mkaput — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5949#-:-O0sTeqgD4pGuJ_u5vvK:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @maciektr)

**Pull request merged**
