### PR TITLE
Support negative impls.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4484)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/neg_impl` line 72 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4484#-NkFXasQ3gDKrSGULQHu:-NkF_yi-2np8V8fnPs_W:bkzqk50) ([raw file](https://github.com/starkware-libs/cairo/blob/42144ad1088916ba07f99748f48a884a2301bc5c/crates/cairo-lang-semantic/src/diagnostic_test_data/neg_impl#L72)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why does it point here?
</blockquote></details>

The cycle doesn't have a location:
https://github.com/starkware-libs/cairo/blob/42144ad1088916ba07f99748f48a884a2301bc5c/crates/cairo-lang-semantic/src/expr/inference/solver.rs#L82

so a fallback is used:
https://github.com/starkware-libs/cairo/blob/8b4f574899a654acf70770189a8bce2c92392f97/crates/cairo-lang-semantic/src/expr/compute.rs#L681

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4484)* status: 5 of 8 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/option.cairo` line 7 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4484#-NkPSg4u95to8vM0VNAN:-NkPSg4u95to8vM0VNAO:b55d2di) ([raw file](https://github.com/starkware-libs/cairo/blob/8dcfd8d85b18b97e1d5eb5b2c0446552865dc778/corelib/src/option.cairo#L7)):*
> ```Cairo
> }
> 
> use core::felt252;
> ```

why is this here?
___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 596 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4484#-NkPSqulCqd5OmZVz-JV:-NkPSqulCqd5OmZVz-JW:b-q941qu) ([raw file](https://github.com/starkware-libs/cairo/blob/8dcfd8d85b18b97e1d5eb5b2c0446552865dc778/crates/cairo-lang-semantic/src/diagnostic.rs#L596)):*
> ```XML
>             }
>             SemanticDiagnosticKind::NegativeImplsNotEnabled => {
>                 "Negative impls are not enabled in this context.".into()
> ```

will you update this to the missing flag when added?
___
*[`crates/cairo-lang-semantic/src/expr/test.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4484#-NkPSKv6CPaBlvMH-Uxs:-NkPSKv6CPaBlvMH-Uxt:b-ch7xg7) ([raw file](https://github.com/starkware-libs/cairo/blob/42144ad1088916ba07f99748f48a884a2301bc5c/crates/cairo-lang-semantic/src/expr/test.rs#L36)):*
> ```XML
>         match_: "match",
>         method: "method",
>         neg_impl: "neg_impl",
> ```

?
don't we want the test?
or are adding these tests after adding the experimental flag?

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4484)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/test.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4484#-NkPSKv6CPaBlvMH-Uxs:-NkQ1MUn06Q9Z2osi8AI:b-9igkp) ([raw file](https://github.com/starkware-libs/cairo/blob/42144ad1088916ba07f99748f48a884a2301bc5c/crates/cairo-lang-semantic/src/expr/test.rs#L36)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

we need an experimental flag for testing.
</blockquote></details>

that wasn't an answer.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 596 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4484#-NkPSqulCqd5OmZVz-JV:-NkQ6XmL09nuOa2AjoQQ:b-d9osr1) ([raw file](https://github.com/starkware-libs/cairo/blob/8dcfd8d85b18b97e1d5eb5b2c0446552865dc778/crates/cairo-lang-semantic/src/diagnostic.rs#L596)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

will you update this to the missing flag when added?
</blockquote></details>

how do you want to update it?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/test.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4484#-NkPSKv6CPaBlvMH-Uxs:-NkoEzUB1BOWMq2JSPyw:bx1umfg) ([raw file](https://github.com/starkware-libs/cairo/blob/42144ad1088916ba07f99748f48a884a2301bc5c/crates/cairo-lang-semantic/src/expr/test.rs#L36)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

a test would be nice to have, but I can't write it since this feature is disabled in tests.
</blockquote></details>

do you want all the logic for enabling this feature to be in this PR?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4484)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 596 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4484#-NkPSqulCqd5OmZVz-JV:-NkpCm7OCsOrYCbVokXM:bsa3vkr) ([raw file](https://github.com/starkware-libs/cairo/blob/8dcfd8d85b18b97e1d5eb5b2c0446552865dc778/crates/cairo-lang-semantic/src/diagnostic.rs#L596)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

how do you want to update it?
</blockquote></details>

'not supported without experimental flag blablabla.'

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 596 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4484#-NkPSqulCqd5OmZVz-JV:-Nktimd16viFWSEyYt93:bkc8bii) ([raw file](https://github.com/starkware-libs/cairo/blob/8dcfd8d85b18b97e1d5eb5b2c0446552865dc778/crates/cairo-lang-semantic/src/diagnostic.rs#L596)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

'not supported without experimental flag blablabla.'
</blockquote></details>

There is currently no way to enable it.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/test.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4484#-NkPSKv6CPaBlvMH-Uxs:-NktitXzBZzYV-2fbG7D:b-b62izt) ([raw file](https://github.com/starkware-libs/cairo/blob/42144ad1088916ba07f99748f48a884a2301bc5c/crates/cairo-lang-semantic/src/expr/test.rs#L36)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it is ok having it in a followup PR - but i want all to be available.
</blockquote></details>

what does 'all' mean?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/test.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4484#-NkPSKv6CPaBlvMH-Uxs:-Nktiy-MEgKmVP8HU5aW:boiajl3) ([raw file](https://github.com/starkware-libs/cairo/blob/42144ad1088916ba07f99748f48a884a2301bc5c/crates/cairo-lang-semantic/src/expr/test.rs#L36)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what does 'all' mean?
</blockquote></details>

I can just use it in the core lib instead of adding tests.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4484)* status: 6 of 8 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/option.cairo` line 7 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4484#-NkPSg4u95to8vM0VNAN:-Nkoe3jZDx8vCWfcAhOD:brpmqc3) ([raw file](https://github.com/starkware-libs/cairo/blob/8dcfd8d85b18b97e1d5eb5b2c0446552865dc778/corelib/src/option.cairo#L7)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why is this here?
</blockquote></details>

removed.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4484)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 596 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4484#-NkPSqulCqd5OmZVz-JV:-Nktmu84-Ku5iPsqAZfg:b-tg4q5q) ([raw file](https://github.com/starkware-libs/cairo/blob/8dcfd8d85b18b97e1d5eb5b2c0446552865dc778/crates/cairo-lang-semantic/src/diagnostic.rs#L596)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

There is currently no way to enable it.
</blockquote></details>

True, so it either isn't supported outside of corelib, or not supported without the flag.
Current message is missing relevant info.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/test_data/neg_impl` line 27 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4484#-NkFXj0DEvzwQkdoYU5M:-NktnNOYDG4fv7jYmSKP:b-hfpv0l) ([raw file](https://github.com/starkware-libs/cairo/blob/42144ad1088916ba07f99748f48a884a2301bc5c/crates/cairo-lang-semantic/src/expr/test_data/neg_impl#L27)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

split to lines.
</blockquote></details>

removed

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4484)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 596 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4484#-NkPSqulCqd5OmZVz-JV:-NktqC7OBnO1ltmrTnDb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8dcfd8d85b18b97e1d5eb5b2c0446552865dc778/crates/cairo-lang-semantic/src/diagnostic.rs#L596)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

True, so it either isn't supported outside of corelib, or not supported without the flag.
Current message is missing relevant info.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4484#-:-Nkud-2M72vgrPUFgxk-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
