### PR TITLE
Added `unstable` and `feature` attributes.

### PR DESCRIPTION
**Pull request by orizi**
Used them for safe dispatchers.

---

**Stack**:
- #4822
- #4816 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4816)

### CODE REVIEW

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4816)* status: 1 of 18 files reviewed, 2 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4816#-NoHHCvY9w9_jSFaJGGu:-NoHHCvY9w9_jSFaJGGv:b-bldeee) (no related file):*
Don't you want the allowed features to be declared in the scarb.toml?

___
___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 199 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4816#-NoHH2Mq4XeJ_jbAt_jS:-NoHH2Mr5ib6dJ4txGWy:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a67ba881629e1cd73c618ce8f9f6bb9dc5ab5a59/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L199)):*
> ```XML
>                 ));
>                 safe_dispatcher_signatures.push(RewriteNode::interpolate_patched(
>                     "\n#[unstable(feature: \"safe_dispatcher\")]\n$func_decl$;",
> ```





_Suggestion:_
```XML
"\n    #[unstable(feature: \"safe_dispatcher\")]\n
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4816)* status: 1 of 18 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4816#-NoHHCvY9w9_jSFaJGGu:-NoHKXYECg9ajvp7ZrPQ:b-of3f82) (no related file):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Don't you want the allowed features to be declared in the scarb.toml?
</blockquote></details>

maybe at some point - not today - and preferably in the same way it is done in rust - which is `#![feature("affects-everywhere-in-context")]`

___
___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 199 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4816#-NoHH2Mq4XeJ_jbAt_jS:-NoHM_6i3XP-z7fX631g:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a67ba881629e1cd73c618ce8f9f6bb9dc5ab5a59/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L199)):*
> ```XML
>                 ));
>                 safe_dispatcher_signatures.push(RewriteNode::interpolate_patched(
>                     "\n#[unstable(feature: \"safe_dispatcher\")]\n$func_decl$;",
> ```

Done.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4816)* status: 11 of 19 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 408 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4816#-NoHmS3RCRZauWmHdC30:-NoIb4Xk67mTTa3cKEkI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/72dfd72a4e287d10799b2061550019e61eb6aaeb/crates/cairo-lang-semantic/src/diagnostic.rs#L408)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Add a test for it.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2472 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4816#-NoHkeOp9yyfnJgOehAC:-NoI-wqYB9Iz2jPlCVQn:b-lk6iea) ([raw file](https://github.com/starkware-libs/cairo/blob/72dfd72a4e287d10799b2061550019e61eb6aaeb/crates/cairo-lang-semantic/src/expr/compute.rs#L2472)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Otherwise a typo will never be noticed.
</blockquote></details>

i can't add a diagnostic here - as it is on the users side, and not the declration side.
Adding a todo instead.
___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 159 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4816#-NoHj7F43l4ushGsk04-:-NoI0Jmb19pzenXUNohR:bw7a288) ([raw file](https://github.com/starkware-libs/cairo/blob/72dfd72a4e287d10799b2061550019e61eb6aaeb/crates/cairo-lang-semantic/src/items/functions.rs#L159)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Why `None`? We may want to add unstable libfuncs in the future, maybe even as a parallel verification to   the allowed libfuncs list.
</blockquote></details>

why isn't the same true for the `must_use` case?
in any case, None since we don't have `find_attr` for it - and it isn't relevant for the PR.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 18 files at r1, 1 of 11 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4816#-:-NoLgXHv9mA_M4JuUB5G:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
