### PR TITLE
resolved associated consts

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5496)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 16 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5496)* status: 15 of 17 files reviewed, 2 unresolved discussions (waiting on @mkaput and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5496#-Nwnun8c3UmJhF0ddZLR:-Nwnun8c3UmJhF0ddZLS:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/8623310c027d416f64e069f59407550b93d73975/crates/cairo-lang-semantic/src/items/constant.rs#L190)):*
> ```XML
> }
> 
> pub fn reduce_impl_constant_id(
> ```

doc
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 1137 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5496#-NwnuZqd1uHdDf3niBrr:-NwnuZqd1uHdDf3niBrs:b2ni2nk) ([raw file](https://github.com/starkware-libs/cairo/blob/8623310c027d416f64e069f59407550b93d73975/crates/cairo-lang-semantic/src/resolve/mod.rs#L1137)):*
> ```XML
>                 // when we support constant expressions, which need inference.
>                 let environment = Environment::empty();
>                 // let mut resolver = Resolver::with_data(
> ```

fix

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5496)* status: 16 of 17 files reviewed, 2 unresolved discussions (waiting on @mkaput and @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5496)* status: 15 of 17 files reviewed, 2 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5496#-Nwnun8c3UmJhF0ddZLR:-NwnyIEl0xmtj1bP1d4F:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8623310c027d416f64e069f59407550b93d73975/crates/cairo-lang-semantic/src/items/constant.rs#L190)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 1137 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5496#-NwnuZqd1uHdDf3niBrr:-NwnyHzgB1CbPiLuXIsh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8623310c027d416f64e069f59407550b93d73975/crates/cairo-lang-semantic/src/resolve/mod.rs#L1137)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5496#-:-Nwo6eN-A7cjzN-abYWt:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Review by mkaput — APPROVED** [review]
> Reviewed 15 of 17 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5496)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5496)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5496)* status: 11 of 19 files reviewed, 3 unresolved discussions (waiting on @mkaput and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/substitution.rs` line 475 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5496#-NxSwVdd32m6AdEG6MeT:-NxSwVdd32m6AdEG6MeU:b-x3zcgx) ([raw file](https://github.com/starkware-libs/cairo/blob/978202b801803b3a515d6f3b43e0d5672fddc082/crates/cairo-lang-semantic/src/substitution.rs#L475)):*
> ```XML
>                     .impl_constant_concrete_implized_value(*impl_constant_id)?
>                     .lookup_intern(self.db);
>                 return Ok(RewriteResult::Modified);
> ```

return modified iif modified.



_Code quote:_
```XML
                self.internal_rewrite(impl_constant_id)?;
                *value = self
                    .db
                    .impl_constant_concrete_implized_value(*impl_constant_id)?
                    .lookup_intern(self.db);
                return Ok(RewriteResult::Modified);
```
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2723 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5496#-NxSwqdiCZhY5AgRDfmc:-NxSwqdiCZhY5AgRDfmd:bn5m89l) ([raw file](https://github.com/starkware-libs/cairo/blob/978202b801803b3a515d6f3b43e0d5672fddc082/crates/cairo-lang-semantic/src/expr/compute.rs#L2723)):*
> ```XML
>         }
>         ResolvedConcreteItem::ImplConstant(impl_constant_id) => {
>             let (const_value_id, ty) = implize_constant(
> ```

it is probably not fully required
___
*[`crates/cairo-lang-semantic/src/expr/inference/canonic.rs` line 308 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5496#-NxSxJqm7XIWyvcotYwm:-NxSxJqm7XIWyvcotYwn:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/978202b801803b3a515d6f3b43e0d5672fddc082/crates/cairo-lang-semantic/src/expr/inference/canonic.rs#L308)):*
> ```XML
>             self.inference.new_impl_var_raw(var.lookup_context.clone(), concrete_trait_id, None)
>         });
>         ImplId::ImplVar(self.inference.impl_vars[new_id.0].intern(self.get_db()));
> ```

?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5496)* status: 5 of 26 files reviewed, 4 unresolved discussions (waiting on @mkaput and @TomerStarkware)

___
*[`-- commits` line 3 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5496#-Nxg6ReRD6yMqNTIBksI):*
rebase pr.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5496)* status: 5 of 26 files reviewed, 4 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`-- commits` line 3 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5496#-Nxg6ReRD6yMqNTIBksI):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rebase pr.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/substitution.rs` line 475 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5496#-NxSwVdd32m6AdEG6MeT:-Nxg7YYcBwEkGZ_tIsXG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/978202b801803b3a515d6f3b43e0d5672fddc082/crates/cairo-lang-semantic/src/substitution.rs#L475)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

return modified iif modified.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2723 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5496#-NxSwqdiCZhY5AgRDfmc:-Nxg7iNMCsEkm4xSMpMj:b-hfpv0l) ([raw file](https://github.com/starkware-libs/cairo/blob/978202b801803b3a515d6f3b43e0d5672fddc082/crates/cairo-lang-semantic/src/expr/compute.rs#L2723)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it is probably not fully required
</blockquote></details>

removed
___
*[`crates/cairo-lang-semantic/src/expr/inference/canonic.rs` line 308 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5496#-NxSxJqm7XIWyvcotYwm:-NxgIyxaCZ2g7rZQL0uM:bvth56w) ([raw file](https://github.com/starkware-libs/cairo/blob/978202b801803b3a515d6f3b43e0d5672fddc082/crates/cairo-lang-semantic/src/expr/inference/canonic.rs#L308)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

reverted

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 9 of 21 files at r6, 11 of 11 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5496)* status: 25 of 26 files reviewed, 3 unresolved discussions (waiting on @mkaput and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 1027 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5496#-NxgMoRV8MivrUHPhpWv:-NxgMoRV8MivrUHPhpWw:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5cb999babd69e6b63ad0994e497f60685f76f77b/crates/cairo-lang-semantic/src/expr/inference.rs#L1027)):*
> ```XML
>                     return Ok(RewriteResult::Modified);
>                 }
>             }
> ```





_Suggestion:_
```XML
            ConstValue::Var(var) => {
                return Ok(if let Some(const_value_id) = self.const_assignment.get(&var.id) {
                    let mut const_value = const_value_id.lookup_intern(self.db);
                    if let RewriteResult::Modified = self.internal_rewrite(&mut const_value)? {
                        *self.const_assignment.get_mut(&var.id).unwrap() =
                            const_value.clone().intern(self.db);
                    }
                    *value = const_value;
                    RewriteResult::Modified
                } else { RewriteResult::NoChange });
            }
```
___
*[`crates/cairo-lang-semantic/src/expr/inference/conform.rs` line 523 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5496#-NxgNdYe0q7BH40VxICm:-NxgNdYe0q7BH40VxICn:b-s721jk) ([raw file](https://github.com/starkware-libs/cairo/blob/5cb999babd69e6b63ad0994e497f60685f76f77b/crates/cairo-lang-semantic/src/expr/inference/conform.rs#L523)):*
> ```XML
>         } else {
>             impl_const_id.impl_id()
>         };
> ```

extract into another private fn.



_Code quote:_
```XML
        let reduced_impl = if let ImplId::ImplVar(var) = impl_const_id.impl_id() {
            self.solve_single_pending(var.id(self.db))?;
            self.rewrite(impl_const_id.impl_id()).no_err()
        } else {
            impl_const_id.impl_id()
        };
```
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 1165 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5496#-NxgPJJPA-Q1_7nfpwTv:-NxgPJJPA-Q1_7nfpwTw:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5cb999babd69e6b63ad0994e497f60685f76f77b/crates/cairo-lang-semantic/src/resolve/mod.rs#L1165)):*
> ```XML
> 
>                     _ => unreachable!("Invalid const value."),
>                 }
> ```





_Suggestion:_
```XML
                        ConstValue::ImplConstant(impl_const_id).intern(self.db),
                    ),
                    ConstValue::Missing(err) => return Err(err),
                    _ => unreachable!("Invalid const value."),
                }
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 21 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5496)* status: all files reviewed, 3 unresolved discussions (waiting on @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5496)* status: 22 of 26 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 1027 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5496#-NxgMoRV8MivrUHPhpWv:-NxgRchK3iDwPNqSq8wI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5cb999babd69e6b63ad0994e497f60685f76f77b/crates/cairo-lang-semantic/src/expr/inference.rs#L1027)):*
> ```XML
>                     return Ok(RewriteResult::Modified);
>                 }
>             }
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/inference/conform.rs` line 523 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5496#-NxgNdYe0q7BH40VxICm:-NxgVAcb36MLdh34xbhQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5cb999babd69e6b63ad0994e497f60685f76f77b/crates/cairo-lang-semantic/src/expr/inference/conform.rs#L523)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

extract into another private fn.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 1165 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5496#-NxgPJJPA-Q1_7nfpwTv:-NxgVFQN2o76_ilj6uQr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5cb999babd69e6b63ad0994e497f60685f76f77b/crates/cairo-lang-semantic/src/resolve/mod.rs#L1165)):*
> ```XML
> 
>                     _ => unreachable!("Invalid const value."),
>                 }
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5496)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference/conform.rs` line 476 at r8](https://reviewable.io/reviews/starkware-libs/cairo/5496#-NxgVbPQ475e0lvuWr24:-NxgVbPQ475e0lvuWr25:bjmksjn) ([raw file](https://github.com/starkware-libs/cairo/blob/9f59125969854465b1035debd9b9690535369cb2/crates/cairo-lang-semantic/src/expr/inference/conform.rs#L476)):*
> ```XML
> 
> impl Inference<'_> {
>     fn reduce_impl(&mut self, impl_id: ImplId) -> InferenceResult<ImplId> {
> ```

doc - and put after usages - as it is a helper func.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5496)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/inference/conform.rs` line 476 at r8](https://reviewable.io/reviews/starkware-libs/cairo/5496#-NxgVbPQ475e0lvuWr24:-NxgWweD1fE6AyhVymC0:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9f59125969854465b1035debd9b9690535369cb2/crates/cairo-lang-semantic/src/expr/inference/conform.rs#L476)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc - and put after usages - as it is a helper func.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5496)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference/conform.rs` line 530 at r9](https://reviewable.io/reviews/starkware-libs/cairo/5496#-NxgwrD_-WnlJh8wIlvX:-NxgwrD_-WnlJh8wIlvY:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/74791a1524a876eeb0181224095c2181506ed68c/crates/cairo-lang-semantic/src/expr/inference/conform.rs#L530)):*
> ```XML
>         }
>     }
>     /// Reduces an impl var to a concrete impl.
> ```





_Suggestion:_
```XML
    }
    
    /// Reduces an impl var to a concrete impl.
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 19 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5496)* status: 10 of 27 files reviewed, 2 unresolved discussions (waiting on @mkaput and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference/infers.rs` line 444 at r10](https://reviewable.io/reviews/starkware-libs/cairo/5496#-NyubI450p-MuU38xzIY:-NyubI450p-MuU38xzIZ:bcrve3x) ([raw file](https://github.com/starkware-libs/cairo/blob/fb5fbfd409081d08cd899dbd0e6a50c4589d6e17/crates/cairo-lang-semantic/src/expr/inference/infers.rs#L444)):*
> ```XML
>             lookup_context.clone(),
>         )?;
>         println!("{:?} ---- {:?}", self.inference_id, impl_id);
> ```

prints all around - ignoring PR.

**Review by mkaput — APPROVED** [review]
> Reviewed 1 of 11 files at r5, 7 of 11 files at r7, 19 of 19 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5496)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 9 of 14 files at r11.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5496)* status: 22 of 28 files reviewed, 4 unresolved discussions (waiting on @mkaput and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference/conform.rs` line 226 at r12](https://reviewable.io/reviews/starkware-libs/cairo/5496#-NzNXdg_5fLAME5pPazA:-NzNXdg_5fLAME5pPazB:b-3sfxa) ([raw file](https://github.com/starkware-libs/cairo/blob/734d6b4d139b8f8b6b05bafb045f26fcf05b2a00/crates/cairo-lang-semantic/src/expr/inference/conform.rs#L226)):*
> ```XML
>                     return self.conform_const(id0, constant);
>                 }
>             }
> ```

same as in types - no need here - as conform shouldn't solve - and the rewrite already replaced with a proper var.



_Code quote:_
```XML
                if !impl_const_id.impl_id().is_var_free(self.db) {
                    let constant = self.reduce_impl_constant(impl_const_id)?;
                    return self.conform_const(id0, constant);
                }
            }
```
___
*[`crates/cairo-lang-semantic/src/expr/inference/conform.rs` line 231 at r12](https://reviewable.io/reviews/starkware-libs/cairo/5496#-NzNXoUt37pLM2s7qLU6:-NzNXoUt37pLM2s7qLU7:b-7jl271) ([raw file](https://github.com/starkware-libs/cairo/blob/734d6b4d139b8f8b6b05bafb045f26fcf05b2a00/crates/cairo-lang-semantic/src/expr/inference/conform.rs#L231)):*
> ```XML
>         match const_value0 {
>             ConstValue::Var(var, _) => Ok(self.assign_const(var, id1)?),
>             ConstValue::ImplConstant(impl_const_id) => {
> ```

same.
___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 119 at r11](https://reviewable.io/reviews/starkware-libs/cairo/5496#-NzNY0IoCmHFa6uOaReR:-NzNY0IoCmHFa6uOaReS:b-fupmed) ([raw file](https://github.com/starkware-libs/cairo/blob/149ea1538ea87d54b457711137b8b6ef476be37b/crates/cairo-lang-semantic/src/items/constant.rs#L119)):*
> ```XML
>         self.ty(db).unwrap().is_fully_concrete(db)
>             && match self {
>                 ConstValue::Int(_, _) => true,
> ```

fully concrete must refer to the type as well.
___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 135 at r11](https://reviewable.io/reviews/starkware-libs/cairo/5496#-NzNY4JaE7FVtNAw2HOX:-NzNY4JaE7FVtNAw2HOY:b-ebb4fv) ([raw file](https://github.com/starkware-libs/cairo/blob/149ea1538ea87d54b457711137b8b6ef476be37b/crates/cairo-lang-semantic/src/items/constant.rs#L135)):*
> ```XML
> 
>     /// Returns true if the const does not contain any inference variables.
>     pub fn is_var_free(&self, db: &dyn SemanticGroup) -> bool {
> ```

var free must refer to the type as well.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 19 files at r10, 5 of 14 files at r11, 1 of 1 files at r12, 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5496#-:-NzNnM1p6e1JljfcfrHM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5496)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by mkaput — APPROVED** [review]
> Reviewed 9 of 14 files at r11, 1 of 1 files at r12, 2 of 3 files at r13, 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5496)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
