### PR TITLE
Added Into and TryInto traits.

### PR DESCRIPTION
**Pull request by orizi**
Using these for all conversions.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2086)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2086)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/hash.cairo` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2086#-NO3v2JNAGvIcppwBOMv:-NO3v2JNAGvIcppwBOMw:b76j3z1) ([raw file](https://github.com/starkware-libs/cairo/blob/c6e07000524801c8349e53d9ddfdc2890f8760b8/corelib/hash.cairo#L35)):*
> ```Cairo
> impl LegacyHashU16 of LegacyHash::<u16> {
>     fn hash(state: felt, value: u16) -> felt {
>         LegacyHash::<felt>::hash(state, value.into())
> ```

Are you sure this is necessary?



_Code quote:_
```Cairo
<felt>
```

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2086)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2086)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/test_data/erc20.sierra` line 244 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2086#-NO3v_lEEspatPgRUsxu:-NO3v_lEEspatPgRUsxv:b-rscwe7) ([raw file](https://github.com/starkware-libs/cairo/blob/c6e07000524801c8349e53d9ddfdc2890f8760b8/crates/cairo-lang-starknet/test_data/erc20.sierra#L244)):*
> ```
> libfunc function_call<user@core::integer::u256_checked_sub> = function_call<user@core::integer::u256_checked_sub>;
> libfunc felt_const<39879774624085075084607933104993585622903> = felt_const<39879774624085075084607933104993585622903>;
> libfunc u8_try_from_felt = u8_try_from_felt;
> ```

IS this because the function is not yet inlined?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2086)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`corelib/hash.cairo` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2086#-NO3v2JNAGvIcppwBOMv:-NO4O5tVBMUf6fCCNOXH:bb0yide) ([raw file](https://github.com/starkware-libs/cairo/blob/c6e07000524801c8349e53d9ddfdc2890f8760b8/corelib/hash.cairo#L35)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Are you sure this is necessary?
</blockquote></details>

When we also have the `into` definitely 
___
*[`crates/cairo-lang-starknet/test_data/erc20.sierra` line 244 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2086#-NO3v_lEEspatPgRUsxu:-NO4OCCJ3eTRGP-6bVf4:b-vl7e3l) ([raw file](https://github.com/starkware-libs/cairo/blob/c6e07000524801c8349e53d9ddfdc2890f8760b8/crates/cairo-lang-starknet/test_data/erc20.sierra#L244)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

IS this because the function is not yet inlined?
</blockquote></details>

I thinks so

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 4 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2086)* status: 12 of 15 files reviewed, all discussions resolved (waiting on @orizi)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2086#-:-NOErOUJERlyE_b6cyPE:bnfp4nl)* status: 12 of 15 files reviewed, all discussions resolved (waiting on @orizi)

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2086)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
