### PR TITLE
Added Sub trait.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:f708b94d

---

**Stack**:
- #1894
- #1895
- #1892 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 30 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1892#-:-NMZtl7t1xKjyytnO_RD:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/traits.cairo` line 7 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1892#-NMZsXDqEXY4MMt6mHoI:-NMZsXDqEXY4MMt6mHoJ:b2nhou3) ([raw file](https://github.com/starkware-libs/cairo/blob/6bd39f7d813f7f2e680c53de33269a281d34053a/corelib/traits.cairo#L7)):*
> ```Cairo
>     fn add(a: T, b: T) -> T;
> }
> // TODO(spapini): When associated types are supported, support the general trait Add<X, Y>.
> ```

Sub
___
*[`crates/cairo-lang-semantic/src/expr/test_data/operators` line 57 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1892#-NMZsqmj0o6jTvRkcMCq:-NMZsqmj0o6jTvRkcMCr:b-sxvtgr) ([raw file](https://github.com/starkware-libs/cairo/blob/6bd39f7d813f7f2e680c53de33269a281d34053a/crates/cairo-lang-semantic/src/expr/test_data/operators#L57)):*
> ```
>         ^
> 
> error: Unexpected return type. Expected: "()", found: "?2".
> ```

Can you fix this error message? The type is not reduced fir some reason, and we should call reduce_ty on it before reporting

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1892)* status: 29 of 30 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/operators` line 57 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1892#-NMZsqmj0o6jTvRkcMCq:-NM_3PFO7x8WwHOIj8lK:b-acp3nh) ([raw file](https://github.com/starkware-libs/cairo/blob/6bd39f7d813f7f2e680c53de33269a281d34053a/crates/cairo-lang-semantic/src/expr/test_data/operators#L57)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Can you fix this error message? The type is not reduced fir some reason, and we should call reduce_ty on it before reporting 
</blockquote></details>

not in this pr - adding to the list.

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1892)* status: 29 of 30 files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1892)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1892)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
