### PR TITLE
Add containing function to StatementWithLocation.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
**Stack**:
- #4878
- #4877
- #4876 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4876)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4876)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/statements_locations.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4876#-NomGb0HE9AM_lEWAwav:-NomGb0HE9AM_lEWAwaw:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/4dd02fef9b156abd2ee5d3732f9243f4e2e60802/crates/cairo-lang-sierra-generator/src/statements_locations.rs#L74)):*
> ```XML
> #[derive(Clone, Debug, Default, Eq, PartialEq)]
> pub struct StatementsLocations {
>     pub locations: HashMap<StatementIdx, StableLocation>,
> ```





_Suggestion:_
```XML
    pub locations: UnorderedHashMap<StatementIdx, StableLocation>,
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4876)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4876)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/statements_locations.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4876#-NomGb0HE9AM_lEWAwav:-Noq7UZg7vQX8WrLpTT0:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e4ccd78bd795b853862d4c6b9fc6ac413eef7503/crates/cairo-lang-sierra-generator/src/statements_locations.rs#L74)):*
> ```XML
> #[derive(Clone, Debug, Default, Eq, PartialEq)]
> pub struct StatementsLocations {
>     pub locations: HashMap<StatementIdx, StableLocation>,
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4876)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/statements_locations.rs` line 1 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4876#-Noq82mO1zWwlgZuA94f:-Noq82mO1zWwlgZuA94g:bybsnzy) ([raw file](https://github.com/starkware-libs/cairo/blob/b90303f8633e7e260d49986fe817346250d86b04/crates/cairo-lang-sierra-generator/src/statements_locations.rs#L1)):*
> ```XML
> use std::collections::HashMap;
> ```

shouldn't be here.



_Code quote:_
```XML
use std::collections::HashMap;
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4876)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/statements_locations.rs` line 1 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4876#-Noq82mO1zWwlgZuA94f:-NoqKkfA8rB42j1Nlt9A:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4ce4d538eabb087d4f9b9df43855fc3df9b51ef2/crates/cairo-lang-sierra-generator/src/statements_locations.rs#L1)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

shouldn't be here.
</blockquote></details>

Done.

**Pull request merged**
