### PR TITLE
Made the basic derive handle based, instead of `get_impl`.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #3936
- #3935
- #3948
- #3934 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3934)

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3934)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-plugins/src/plugins/derive/mod.rs` line 260 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3934#-NcWDmxgBTnaBKViiO2d:-NcWFj3y1Zfr1T9JNIek:b1vs8gy) ([raw file](https://github.com/starkware-libs/cairo/blob/9fa74ef0b0de6cfa9f0e302516c5eb7134f08d4d/crates/cairo-lang-plugins/src/plugins/derive/mod.rs#L260)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Why not `handle_empty_impl`?
</blockquote></details>

because it does not generate actual code - will change if required in the future.

**Review by orizi — COMMENTED** [review]
> Reviewed 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3934)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 1 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3934)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3934#-:-NcWIae46jTK0gssV85j:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
