### PR TITLE
Added 2 major test cases.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #4985
- #4984 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4984)

### CODE REVIEW

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4984)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/profiling_test_data/major_test_cases` line 498 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4984#-NpnJxFt4YRHtAud7Qw7:-NpnJxFt4YRHtAud7Qw8:bigqfld) ([raw file](https://github.com/starkware-libs/cairo/blob/11c95666b53e6e3415805392d99033307007726d/crates/cairo-lang-runner/src/profiling_test_data/major_test_cases#L498)):*
> ```
>   fn __validate__(ref self: ContractState, calls: Array<Call>) {}
>   #[external(v0)]
>   fn __execute__(ref self: ContractState, mut calls: Array<Call>) -> Array<Span<felt252>> {
> ```

Shouldn't there be a test for this too? (The title say 2 tests so I guess that's the second)



_Code quote:_
```
fn __execute__(ref self: ContractState, mut calls: Array<Call>) -> Array<Span<felt252>> {
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4984)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-runner/src/profiling_test_data/major_test_cases` line 498 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4984#-NpnJxFt4YRHtAud7Qw7:-NpnLFzPAlSv3YcFPo1a:bvnjdji) ([raw file](https://github.com/starkware-libs/cairo/blob/11c95666b53e6e3415805392d99033307007726d/crates/cairo-lang-runner/src/profiling_test_data/major_test_cases#L498)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Shouldn't there be a test for this too? (The title say 2 tests so I guess that's the second)
</blockquote></details>

it is the size of the calls array.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4984)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/profiling_test_data/major_test_cases` line 498 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4984#-NpnJxFt4YRHtAud7Qw7:-NpnPYNX2KQEW1RJCp1C:bbuqpmh) ([raw file](https://github.com/starkware-libs/cairo/blob/11c95666b53e6e3415805392d99033307007726d/crates/cairo-lang-runner/src/profiling_test_data/major_test_cases#L498)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it is the size of the calls array.
</blockquote></details>

I meant the ` Added 2 major test cases.` pr title, but now I see that an account contract must have `__execute__`, so retract.
___
*[`crates/cairo-lang-runner/src/profiling_test_data/major_test_cases` line 505 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4984#-NpnPZdK5-nx_7-lW_yf:-NpnPZdK5-nx_7-lW_yg:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/11c95666b53e6e3415805392d99033307007726d/crates/cairo-lang-runner/src/profiling_test_data/major_test_cases#L505)):*
> ```
> fn validate_call() {
>   let serialized_args = array![
>     0x1, // Array with 2 `Call`s.
> ```





_Suggestion:_
```
Array with 1 `Call`s.
```

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4984)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Pull request merged**
