### PR TITLE
Added query and functions caching if a type or impl contains vars.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5341)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/types.rs` line 246 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5341#-NuNK3ZXA3KvtyCE_bsf:-NuNK3ZYBuu7faqk4oIm:b-dbd4ob) ([raw file](https://github.com/starkware-libs/cairo/blob/895162fc56b095451d0f200b804c4332d8e898b3/crates/cairo-lang-semantic/src/types.rs#L246)):*
> ```XML
>     }
>     /// Returns true if the type does not depend on any generics.
>     pub fn contains_no_var(&self, db: &dyn SemanticGroup) -> bool {
> ```

why do you need the negative in the name?



_Suggestion:_
```XML
contains_var
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5341)* status: 2 of 7 files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5341)* status: 2 of 7 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 246 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5341#-NuNK3ZXA3KvtyCE_bsf:-NuNOkt-11Ew_UbhaZz-:b-sqad16) ([raw file](https://github.com/starkware-libs/cairo/blob/895162fc56b095451d0f200b804c4332d8e898b3/crates/cairo-lang-semantic/src/types.rs#L246)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why do you need the negative in the name?
</blockquote></details>

was much easier to make it almost the same as `is_fully_concrete` .
maybe just rename to `var_free`?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/types.rs` line 246 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5341#-NuNK3ZXA3KvtyCE_bsf:-NuNPQxT8Gy717nmbVgu:b16mk17) ([raw file](https://github.com/starkware-libs/cairo/blob/895162fc56b095451d0f200b804c4332d8e898b3/crates/cairo-lang-semantic/src/types.rs#L246)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

was much easier to make it almost the same as `is_fully_concrete` .
maybe just rename to `var_free`?
</blockquote></details>

is_var_free?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/types.rs` line 245 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5341#-NuNPU_c3omg1WDUvSpO:-NuNPU_c3omg1WDUvSpP:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/895162fc56b095451d0f200b804c4332d8e898b3/crates/cairo-lang-semantic/src/types.rs#L245)):*
> ```XML
>             .all(|generic_argument_id| generic_argument_id.is_fully_concrete(db))
>     }
>     /// Returns true if the type does not depend on any generics.
> ```





_Suggestion:_
```XML
   /// Returns true if the type does not contain any inference variables.
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5341)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 245 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5341#-NuNPU_c3omg1WDUvSpO:-NuNtmnM2s1ANw1KPohc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/895162fc56b095451d0f200b804c4332d8e898b3/crates/cairo-lang-semantic/src/types.rs#L245)):*
> ```XML
>             .all(|generic_argument_id| generic_argument_id.is_fully_concrete(db))
>     }
>     /// Returns true if the type does not depend on any generics.
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/types.rs` line 246 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5341#-NuNK3ZXA3KvtyCE_bsf:-NuNtmY45qZyNOdq68Hp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/895162fc56b095451d0f200b804c4332d8e898b3/crates/cairo-lang-semantic/src/types.rs#L246)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

is_var_free?
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5341#-:-NuO-XNQ4LwQivRxJof2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5341)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @orizi)

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5341)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
