### PR TITLE
Support Fallthrough and Goto in sierra_gen lifetime module.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2001)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2001)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @liorgold2)

___
*[`crates/cairo-lang-sierra-generator/src/block_generator_test_data/inline` line 4 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2001#-NN7dxkK07pOj1DOyOXy:-NN7dxkK07pOj1DOyOXz:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/fcc5b8ea471368914a5ec1b61f32479a1e63ba5f/crates/cairo-lang-sierra-generator/src/block_generator_test_data/inline#L4)):*
> ```
> 
> //! > test_function_name
> block_generator_test
> ```

remove



_Code quote:_
```
//! > Test function call.

//! > test_function_name
block_generator_test

//! > function
fn foo(n: felt) -> felt {
  -n
}

//! > function_name
foo

//! > module_code
extern type MyStruct;

//! > semantic_diagnostics

//! > lowering_diagnostics

//! > sierra_gen_diagnostics

//! > sierra_code
felt_const<-1>() -> ([0])
felt_mul([1], [0]) -> ([2])
drop<felt>([2]) -> ()

//! > ==========================================================================

//! > Test function call 2.

//! > test_function_name
block_generator_test

//! > function
fn foo() -> felt {
    let x = 7;
    bar(x, 7);
    bar2(bar(x, 7), bar(x, 7))
}

//! > function_name
foo

//! > module_code
fn bar(a: felt, b: felt) -> felt {
    0
}
fn bar2(a: felt, b: felt) -> felt {
    0
}

//! > semantic_diagnostics

//! > lowering_diagnostics

//! > sierra_gen_diagnostics

//! > sierra_code
felt_const<7>() -> ([0])
felt_const<7>() -> ([1])
PushValues([0]: felt, [1]: felt) -> ([4] [3], [5])
function_call<user@test::bar>([4], [5]) -> ([2])
drop<felt>([2]) -> ()
felt_const<7>() -> ([6])
PushValues([0]: felt, [6]: felt) -> ([9] [8], [10])
function_call<user@test::bar>([9], [10]) -> ([7])
felt_const<7>() -> ([11])
PushValues([0]: felt, [11]: felt) -> ([13], [14])
function_call<user@test::bar>([13], [14]) -> ([12])
PushValues([7]: felt, [12]: felt) -> ([16], [17])
function_call<user@test::bar2>([16], [17]) -> ([15])

//! > ==========================================================================

//! > Call libfunc explicitly

//! > test_function_name
block_generator_test

//! > function
fn foo() -> felt {
    my_libfunc(3, 6)
}

//! > function_name
foo

//! > module_code
extern fn my_libfunc(a: felt, b: felt) -> felt;

//! > semantic_diagnostics
error: An extern function must be marked as nopanic.
 --> lib.cairo:1:1
extern fn my_libfunc(a: felt, b: felt) -> felt;
^*********************************************^

//! > lowering_diagnostics

//! > sierra_gen_diagnostics

//! > sierra_code
felt_const<3>() -> ([0])
felt_const<6>() -> ([1])
my_libfunc([0], [1]) -> ([2])
enum_init<core::PanicResult::<core::felt>, 0>([2]) -> ([3])
```
___
*[`crates/cairo-lang-sierra-generator/src/lifetime_test_data/inline` line 64 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2001#-NN7f0Rw-heJp3Xqyh4O:-NN7f0Rw-heJp3Xqyh4P:b-jlmcj6) ([raw file](https://github.com/starkware-libs/cairo/blob/fcc5b8ea471368914a5ec1b61f32479a1e63ba5f/crates/cairo-lang-sierra-generator/src/lifetime_test_data/inline#L64)):*
> ```
> //! > ==========================================================================
> 
> //! > Test variable lifetime in inlining scenario with callsite
> ```

update



_Code quote:_
```
//! > drops
BeginningOfBlock(BlockId(3)): v3, v1

//! > ==========================================================================

//! > Test variable lifetime in inlining scenario with callsite

//! > test_function_name
check_variable_lifetime

//! > function_code
fn foo(a: felt) -> felt {
  bar(a)
}

//! > function_name
foo

//! > module_code
#[inline(always)]
fn bar(a: felt) -> felt {
  if a == 0 {
    return 1;
  }
  0
}
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2001)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/lifetime_test_data/inline` line 64 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2001#-NN7f0Rw-heJp3Xqyh4O:-NN7fmTADdqUU5kHU5_I:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fcc5b8ea471368914a5ec1b61f32479a1e63ba5f/crates/cairo-lang-sierra-generator/src/lifetime_test_data/inline#L64)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

update
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/block_generator_test_data/inline` line 4 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2001#-NN7dxkK07pOj1DOyOXy:-NN7fpR7CrukVBCYq60R:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fcc5b8ea471368914a5ec1b61f32479a1e63ba5f/crates/cairo-lang-sierra-generator/src/block_generator_test_data/inline#L4)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2001)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @liorgold2)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2001)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/lifetime_test_data/inline` line 140 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2001#-NN7u35-2enH9pTSuj-2:-NNAZPSI7GD3CCE9-OpY:b-ypgifd) ([raw file](https://github.com/starkware-libs/cairo/blob/6116e4644cce64bd969b6198ab6f10044d558c5d/crates/cairo-lang-sierra-generator/src/lifetime_test_data/inline#L140)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this seems wrong.
the last usage of v3 does not seem to be in the first line of block 2
</blockquote></details>

The last tuple entry is ( /// The index of the argument within the statement.)
So it means that v2 is last used in statement 3 of blk 2 which is true.


I don't know why this it the format of last used :(



_Code quote:_
```
v2
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/lifetime_test_data/inline` line 140 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2001#-NN7u35-2enH9pTSuj-2:-NNA_WyGDZpS1ijfZWwK:bg1pjw9) ([raw file](https://github.com/starkware-libs/cairo/blob/6116e4644cce64bd969b6198ab6f10044d558c5d/crates/cairo-lang-sierra-generator/src/lifetime_test_data/inline#L140)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

The last tuple entry is ( /// The index of the argument within the statement.)
So it means that v2 is last used in statement 3 of blk 2 which is true.


I don't know why this it the format of last used :(
</blockquote></details>

I guess it is because it is a location.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2001)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/lifetime_test_data/inline` line 140 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2001#-NN7u35-2enH9pTSuj-2:-NNAk0fN6CJ6BO7hyjSC:b-av51q6) ([raw file](https://github.com/starkware-libs/cairo/blob/6116e4644cce64bd969b6198ab6f10044d558c5d/crates/cairo-lang-sierra-generator/src/lifetime_test_data/inline#L140)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I guess it is because it is a location.
</blockquote></details>

Here is an improvement to the test.
https://reviewable.io/reviews/starkware-libs/cairo/2009#-

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2001)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2001#-:-NNAymRZ9HybEWeuedIc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2001)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
