### PR TITLE
Return Error Ptr

### PR DESCRIPTION
**Pull request by Tomer-StarkWare**

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6792)* status: 1 of 17 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/function_call` line 185 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6792#-OD5mqJ9Cs5mBJBCIbO-:-OD5mqJ9Cs5mBJBCIbO0:bge94jg) ([raw file](https://github.com/starkware-libs/cairo/blob/d5a2c11b4d65c259d40e20c0d6fd54ab18c5aeec/crates/cairo-lang-semantic/src/expr/test_data/function_call#L185)):*
> ```
>     ^***^
> 
> //! > ==========================================================================
> ```

please add a comment with a diff to what was before in the diagnostics.
(just to make it more easy to review)
___
*[`crates/cairo-lang-semantic/src/expr/test_data/function_call` line 212 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6792#-OD5myG-1y1OEsDzJSYT:-OD5myG-1y1OEsDzJSYU:b-an9mfj) ([raw file](https://github.com/starkware-libs/cairo/blob/d5a2c11b4d65c259d40e20c0d6fd54ab18c5aeec/crates/cairo-lang-semantic/src/expr/test_data/function_call#L212)):*
> ```
>  --> lib.cairo:2:13
> fn foo() -> () {
>             ^^
> ```

split test.



_Code quote:_
```
//! > expected_diagnostics
error: Unexpected return type. Expected: "core::integer::u8", found: "()".
 --> lib.cairo:1:13
fn bar() -> u8 {}
            ^^

error: Unexpected return type. Expected: "()", found: "core::integer::u16".
 --> lib.cairo:2:13
fn foo() -> () {
            ^^
```
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1105 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6792#-OD5nn2m1Om3fhsFQtxZ:-OD5nn2m1Om3fhsFQtx_:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d5a2c11b4d65c259d40e20c0d6fd54ab18c5aeec/crates/cairo-lang-semantic/src/expr/compute.rs#L1105)):*
> ```XML
>                 ctx.diagnostics.report(stable_ptr, WrongReturnType { expected_ty, actual_ty })
>             }
>         };
> ```





_Suggestion:_
```XML
) -> Maybe<ExprId> {
    // Conform TypeEqual constraints for Associated type bounds.
    let inference = &mut ctx.resolver.data.inference_data.inference(ctx.db);
    if let Err((err_set, actual_ty, expected_ty)) =
        inference.conform_ty_for_diag(res_ty, return_type)
    {
        let diag_added = ctx.diagnostics.report(
            ctx.signature.map(|s|s.stable_ptr.lookup().ret_ty(dp.upcast()).untyped()).unwrap_or_else(|_|syntax.into())
            }, WrongReturnType { expected_ty, actual_ty });
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6792)* status: 1 of 17 files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/items/free_function.rs` line 251 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6792#-OD5pOAK5NsCDciHIZHA:-OD5pOAK5NsCDciHIZHB:b-27bshu) ([raw file](https://github.com/starkware-libs/cairo/blob/d5a2c11b4d65c259d40e20c0d6fd54ab18c5aeec/crates/cairo-lang-semantic/src/items/free_function.rs#L251)):*
> ```XML
>     let return_type = declaration.signature.return_type;
>     let body_expr = compute_root_expr(
>         &mut ctx,
> ```

revert all of these.
___
*[`crates/cairo-lang-semantic/src/items/trt.rs` line 1400 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6792#-OD5pLLM9Z2cdDBRElZh:-OD5pLLM9Z2cdDBRElZi:b-27bshu) ([raw file](https://github.com/starkware-libs/cairo/blob/d5a2c11b4d65c259d40e20c0d6fd54ab18c5aeec/crates/cairo-lang-semantic/src/items/trt.rs#L1400)):*
> ```XML
>     };
>     let return_type = trait_function_declaration_data.signature.return_type;
>     let body_expr = compute_root_expr(
> ```

revert all of these.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 3340 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6792#-OD5pHLp6KdRo1QSJ2l4:-OD5pHLp6KdRo1QSJ2l5:b-27bshu) ([raw file](https://github.com/starkware-libs/cairo/blob/d5a2c11b4d65c259d40e20c0d6fd54ab18c5aeec/crates/cairo-lang-semantic/src/items/imp.rs#L3340)):*
> ```XML
>                 Some(return_type_clause.ty(db.upcast()).stable_ptr())
>             }
>         },
> ```

revert all of these.



_Code quote:_
```XML
        &mut ctx,
        &function_body,
        return_type,
        match function_syntax.declaration(db.upcast()).signature(db.upcast()).ret_ty(db.upcast()) {
            OptionReturnTypeClause::Empty(_) => None,
            OptionReturnTypeClause::ReturnTypeClause(return_type_clause) => {
                Some(return_type_clause.ty(db.upcast()).stable_ptr())
            }
        },
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6792)* status: 1 of 17 files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/function_call` line 185 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6792#-OD5mqJ9Cs5mBJBCIbO-:-OD5pRFJ-EST7eD_CB2g:b-cycbx7) ([raw file](https://github.com/starkware-libs/cairo/blob/d5a2c11b4d65c259d40e20c0d6fd54ab18c5aeec/crates/cairo-lang-semantic/src/expr/test_data/function_call#L185)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

please add a comment with a diff to what was before in the diagnostics.
(just to make it more easy to review)
</blockquote></details>

nm - i saw the change in other places now.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6792)* status: 1 of 17 files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1105 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6792#-OD5nn2m1Om3fhsFQtxZ:-OD5pW1R9tx76Nxqo5iP:b-k66x2b) ([raw file](https://github.com/starkware-libs/cairo/blob/d5a2c11b4d65c259d40e20c0d6fd54ab18c5aeec/crates/cairo-lang-semantic/src/expr/compute.rs#L1105)):*
> ```XML
>                 ctx.diagnostics.report(stable_ptr, WrongReturnType { expected_ty, actual_ty })
>             }
>         };
> ```

additionally handle the empty vs non-empty return type - just too much work doing it in reviewable.

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6792)* status: 1 of 17 files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1105 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6792#-OD5nn2m1Om3fhsFQtxZ:-OD6Ztc16FEKI6sm99W-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d5a2c11b4d65c259d40e20c0d6fd54ab18c5aeec/crates/cairo-lang-semantic/src/expr/compute.rs#L1105)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

additionally handle the empty vs non-empty return type - just too much work doing it in reviewable.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/function_call` line 212 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6792#-OD5myG-1y1OEsDzJSYT:-OD6ewwdD1y9c7JfBFiF:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d5a2c11b4d65c259d40e20c0d6fd54ab18c5aeec/crates/cairo-lang-semantic/src/expr/test_data/function_call#L212)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

split test.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/free_function.rs` line 251 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6792#-OD5pOAK5NsCDciHIZHA:-OD6_W5w9ac1ouX3zvjU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d5a2c11b4d65c259d40e20c0d6fd54ab18c5aeec/crates/cairo-lang-semantic/src/items/free_function.rs#L251)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

revert all of these.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 3340 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6792#-OD5pHLp6KdRo1QSJ2l4:-OD6_WmVEqz3cWhcxqyY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d5a2c11b4d65c259d40e20c0d6fd54ab18c5aeec/crates/cairo-lang-semantic/src/items/imp.rs#L3340)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

revert all of these.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/trt.rs` line 1400 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6792#-OD5pLLM9Z2cdDBRElZh:-OD6_XNKEdXbB3lZTwM2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d5a2c11b4d65c259d40e20c0d6fd54ab18c5aeec/crates/cairo-lang-semantic/src/items/trt.rs#L1400)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

revert all of these.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6792#-:-OD73wMg0i2PlmfNCvHw:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
