### PR TITLE
#[key] attr

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3292)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3292)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo` line 320 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3292#-NWs401U5ckVI42BUKas:-NWs401U5ckVI42BUKat:b-uacgp6) ([raw file](https://github.com/starkware-libs/cairo/blob/25746aee7450c88660af4c17f425bfba2d74503e/crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo#L320)):*
> ```Cairo
> struct MyEventStruct {
>     x: felt252,
>     #[key]
> ```

starknet:: prefix?



_Code quote:_
```Cairo
#[key]
```
___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3292#-NWs46S6AIZvU8YLG56k:-NWs46S6AIZvU8YLG56l:bg4ac8j) ([raw file](https://github.com/starkware-libs/cairo/blob/25746aee7450c88660af4c17f425bfba2d74503e/crates/cairo-lang-starknet/src/plugin/events.rs#L28)):*
> ```XML
> 
> #[derive(Copy, Clone, Debug)]
> enum MemberKind {
> ```

please doc the enum and its variant.
specifically event variant - can we have nested events? Is there a test for it? What if key/value/event are mixed in a struct? Isn't `event` for enums anyway?
I am confused/missing something.
___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3292#-NWs6BCjDEmOtzl3SFvv:-NWs6BCjDEmOtzl3SFvw:bsda7ss) ([raw file](https://github.com/starkware-libs/cairo/blob/25746aee7450c88660af4c17f425bfba2d74503e/crates/cairo-lang-starknet/src/plugin/events.rs#L118)):*
> ```XML
>     diagnostics: &mut Vec<PluginDiagnostic>,
>     member: ast::Member,
>     db: &dyn SyntaxGroup,
> ```

not sure if db or diagnostics should be first, but member should be last.
___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3292#-NWs5K8w4iuDCRFz23U4:-NWs5K8w4iuDCRFz23U5:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/25746aee7450c88660af4c17f425bfba2d74503e/crates/cairo-lang-starknet/src/plugin/events.rs#L120)):*
> ```XML
>     db: &dyn SyntaxGroup,
> ) -> MemberKind {
>     let as_event = member.has_attr(db, "event");
> ```





_Suggestion:_
```XML
 let is_event =
```
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/events` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3292#-NWs8yDG6-f6YN6dFIUO:-NWs8yDG6-f6YN6dFIUP:bxfd0q5) ([raw file](https://github.com/starkware-libs/cairo/blob/25746aee7450c88660af4c17f425bfba2d74503e/crates/cairo-lang-starknet/src/plugin/plugin_test_data/events#L61)):*
> ```
>                     ref keys
>                 )?;
>         Option::Some(MyEventStruct {x, data, })
> ```

Probably out of scope of this PR, but this means we can't allow `values` and `keys` as members in structs... Unless this is enforced somehow, could you please add a TODO? (also would be better to change them to less common names).



_Code quote:_
```
    fn deserialize(
        ref keys: Span<felt252>, ref values: Span<felt252>,
    ) -> Option<MyEventStruct> {
                let x = serde::Serde::deserialize(
                    ref values
                )?;
                let data = serde::Serde::deserialize(
                    ref keys
                )?;
        Option::Some(MyEventStruct {x, data, })
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3292)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo` line 320 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3292#-NWs401U5ckVI42BUKas:-NX93iYT2KwYQbKjnc4X:b-j7cjfm) ([raw file](https://github.com/starkware-libs/cairo/blob/25746aee7450c88660af4c17f425bfba2d74503e/crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo#L320)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

starknet:: prefix?
</blockquote></details>

This is on a member, so not necessary IMO
___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3292#-NWs46S6AIZvU8YLG56k:-NX95nwo6GrnsUuaNHHQ:b-c48n2a) ([raw file](https://github.com/starkware-libs/cairo/blob/25746aee7450c88660af4c17f425bfba2d74503e/crates/cairo-lang-starknet/src/plugin/events.rs#L28)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

please doc the enum and its variant.
specifically event variant - can we have nested events? Is there a test for it? What if key/value/event are mixed in a struct? Isn't `event` for enums anyway?
I am confused/missing something.
</blockquote></details>

We can have nested.
`event_serde_tester` tests it.
`event` is also for structs.
___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3292#-NWs6BCjDEmOtzl3SFvv:-NX94ARy80foHjxDdQNj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/25746aee7450c88660af4c17f425bfba2d74503e/crates/cairo-lang-starknet/src/plugin/events.rs#L118)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

not sure if db or diagnostics should be first, but member should be last.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/events` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3292#-NWs8yDG6-f6YN6dFIUO:-NX94hju7Ij6DY3HwYTn:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/25746aee7450c88660af4c17f425bfba2d74503e/crates/cairo-lang-starknet/src/plugin/plugin_test_data/events#L61)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Probably out of scope of this PR, but this means we can't allow `values` and `keys` as members in structs... Unless this is enforced somehow, could you please add a TODO? (also would be better to change them to less common names).
</blockquote></details>

Done.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3292)* status: all files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo` line 320 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3292#-NWs401U5ckVI42BUKas:-NXA3XrjB2z7GrUmSqrx:b-t4p0sw) ([raw file](https://github.com/starkware-libs/cairo/blob/25746aee7450c88660af4c17f425bfba2d74503e/crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo#L320)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This is on a member, so not necessary IMO
</blockquote></details>

I thought we decided to have it on all, didn't we?
___
*[`crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo` line 326 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3292#-NXA3uga64HDMYDgGZKp:-NXA3uga64HDMYDgGZKq:b-2gjabe) ([raw file](https://github.com/starkware-libs/cairo/blob/1d61f4e68af487f006d2ede1b1a51f22061a314c/crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo#L326)):*
> ```Cairo
> #[derive(starknet::Event, PartialEq, Drop, Clone)]
> enum MyEventEnum {
>     #[event]
> ```

shouldn't this be on the enum?
___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3292#-NWs46S6AIZvU8YLG56k:-NXA5MPx0gLenz0QWY4L:bvy1hyy) ([raw file](https://github.com/starkware-libs/cairo/blob/25746aee7450c88660af4c17f425bfba2d74503e/crates/cairo-lang-starknet/src/plugin/events.rs#L28)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

We can have nested.
`event_serde_tester` tests it.
`event` is also for structs.
</blockquote></details>

I am still confused. Thought we wanted #[event] to be for the enum. Let's discuss f2f.
___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 393 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3292#-NXA4ldCDSNqcUSW576u:-NXA4ldCDSNqcUSW576v:b8p4i90) ([raw file](https://github.com/starkware-libs/cairo/blob/25746aee7450c88660af4c17f425bfba2d74503e/crates/cairo-lang-starknet/src/plugin/events.rs#L393)):*
> ```XML
>                     "
>     $declaration$ {{
>         let mut __keys = array::array_new();
> ```

why did you remove the __ from __keys?
It's there to avoid name collisions.



_Code quote:_
```XML
__keys
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3292)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo` line 320 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3292#-NWs401U5ckVI42BUKas:-NXAWCeb-Sf1UqZXbZN1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/25746aee7450c88660af4c17f425bfba2d74503e/crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo#L320)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I thought we decided to have it on all, didn't we?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo` line 326 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3292#-NXA3uga64HDMYDgGZKp:-NXAWFfHAOJZgVdYKXkw:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1d61f4e68af487f006d2ede1b1a51f22061a314c/crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo#L326)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

shouldn't this be on the enum?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3292#-NWs46S6AIZvU8YLG56k:-NXAWHQbCL7wkdJo1jvv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/25746aee7450c88660af4c17f425bfba2d74503e/crates/cairo-lang-starknet/src/plugin/events.rs#L28)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I am still confused. Thought we wanted #[event] to be for the enum. Let's discuss f2f.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 393 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3292#-NXA4ldCDSNqcUSW576u:-NXEd6646EfYI1M1Z2wb:b-y938a5) ([raw file](https://github.com/starkware-libs/cairo/blob/25746aee7450c88660af4c17f425bfba2d74503e/crates/cairo-lang-starknet/src/plugin/events.rs#L393)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

why did you remove the __ from __keys?
It's there to avoid name collisions.
</blockquote></details>

Bad search and replace

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3292#-:-NXEhvpiE9--IzvIZwn8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
