### PR TITLE
Renamed DictFelt252To -> Felt252Dict

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2524)

### CODE REVIEW

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 6 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2524)* status: 6 of 23 files reviewed, all discussions resolved

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 2 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2524)* status: 8 of 23 files reviewed, all discussions resolved

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 5 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2524)* status: 13 of 23 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/allowed_libfuncs_lists/testnet_v0.1.0.json` line 25 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2524#-NQesQxc7EqdGbteb5js:-NQesQxc7EqdGbteb5jt:bb747yb) ([raw file](https://github.com/starkware-libs/cairo/blob/e05e4353db96e4b76f6a5eb7c7b20e4f751209fa/crates/cairo-lang-starknet/src/allowed_libfuncs_lists/testnet_v0.1.0.json#L25)):*
> ```JSON
>                 "contract_address_try_from_felt252",
>                 "deploy_syscall",
>                 "felt252_dict_new",
> ```

Sort

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 4 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2524)* status: 17 of 23 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2524)* status: 18 of 23 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2524#-:-NQesw3WBnLM821qAp2v:bnfp4nl)* status: 16 of 23 files reviewed, all discussions resolved

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2524)* status: 18 of 23 files reviewed, all discussions resolved

**Review by orizi — APPROVED** [review]
> Reviewed 4 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2524)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 6 of 23 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2524#-:-NQeyVn66sDz6twZ5h3-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2524)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
