### PR TITLE
BorrowChecker

### PR DESCRIPTION
**Pull request by spapinistarkware**
commit-id:07821bc4

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1737)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/demand.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1737#-NLVUPOoAOjldHntmH8i:-NLVUPOoAOjldHntmH8j:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/29598e462362cff2528368facf055776dfa97eef/crates/cairo-lang-lowering/src/borrow_check/demand.rs#L7)):*
> ```XML
> use crate::VariableId;
> 
> /// Demanded variables from a certain point int the flow until the end of the function.
> ```





_Suggestion:_
```XML
/// Demanded variables from a certain point in the flow until the end of the function.
```
___
*[`crates/cairo-lang-lowering/src/borrow_check/demand.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1737#-NLVUtxb58RoGGP9YgPJ:-NLVUtxb58RoGGP9YgPK:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/29598e462362cff2528368facf055776dfa97eef/crates/cairo-lang-lowering/src/borrow_check/demand.rs#L39)):*
> ```XML
>                 // Variable introduced, but not demanded. If it's not drop, that is an issue.
>                 // Currently disabled, since Drop is not proerpyl implements everywhere.
>                 #[allow(clippy::overly_complex_bool_expr)]
> ```





_Suggestion:_
```XML
                // Variable introduced, but not demanded. If it's not drop, that is an issue.
                // Currently disabled, since Drop is not properply implemented everywhere.
```
___
*[`crates/cairo-lang-lowering/src/borrow_check/mod.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1737#-NLVVbPj0qenJ8aBhIJQ:-NLVVbPj0qenJ8aBhIJR:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/29598e462362cff2528368facf055776dfa97eef/crates/cairo-lang-lowering/src/borrow_check/mod.rs#L23)):*
> ```XML
> 
> /// Information about the callsite of the current block. When lowering uses Goto, this won'st be
> /// necessary.
> ```





_Suggestion:_
```XML
/// Information about the callsite of the current block. When lowering uses Goto, this won't be
/// necessary.
#[derive(Clone)]
pub struct CallsiteInfo<'a> {
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1737)* status: all files reviewed, 6 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/mod.rs` line 156 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1737#-NLVbEDEBYGoIL3mRRjm:-NLVbEDEBYGoIL3mRRjn:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/29598e462362cff2528368facf055776dfa97eef/crates/cairo-lang-lowering/src/borrow_check/mod.rs#L156)):*
> ```XML
>     }
> 
>     fn merge_demands(&self, arm_demands: Vec<Demand>) -> Demand {
> ```

doc



_Code quote:_
```XML
merge_demands
```
___
*[`crates/cairo-lang-lowering/src/borrow_check/mod.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1737#-NLVbsFrAOHTBYDZoJvG:-NLVbsFrAOHTBYDZoJvH:b-cthzbp) ([raw file](https://github.com/starkware-libs/cairo/blob/29598e462362cff2528368facf055776dfa97eef/crates/cairo-lang-lowering/src/borrow_check/mod.rs#L161)):*
> ```XML
>         for arm_demand in &arm_demands {
>             for var in arm_demand.vars.iter() {
>                 demand.vars.insert(*var);
> ```

consider adding .extend



_Code quote:_
```XML
            for var in arm_demand.vars.iter() {
                demand.vars.insert(*var);
            }
```
___
*[`crates/cairo-lang-lowering/src/borrow_check/mod.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1737#-NLVc2jc4UV6u4zKfGCS:-NLVc2jc4UV6u4zKfGCT:b32wk0) ([raw file](https://github.com/starkware-libs/cairo/blob/29598e462362cff2528368facf055776dfa97eef/crates/cairo-lang-lowering/src/borrow_check/mod.rs#L171)):*
> ```XML
>                     // TODO(spapini): add a drop.
>                     if !self.lowered.variables[*var].droppable {
>                         // TODO: Diagnostics.
> ```

do



_Code quote:_
```XML
// TODO: Diagnostics.
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1737)* status: 7 of 9 files reviewed, 6 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/borrow_check/demand.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1737#-NLVUPOoAOjldHntmH8i:-NLVf5TfDNwd6gNjN9im:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/29598e462362cff2528368facf055776dfa97eef/crates/cairo-lang-lowering/src/borrow_check/demand.rs#L7)):*
> ```XML
> use crate::VariableId;
> 
> /// Demanded variables from a certain point int the flow until the end of the function.
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/borrow_check/demand.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1737#-NLVUtxb58RoGGP9YgPJ:-NLVctjIETGIHmV8tiAD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/29598e462362cff2528368facf055776dfa97eef/crates/cairo-lang-lowering/src/borrow_check/demand.rs#L39)):*
> ```XML
>                 // Variable introduced, but not demanded. If it's not drop, that is an issue.
>                 // Currently disabled, since Drop is not proerpyl implements everywhere.
>                 #[allow(clippy::overly_complex_bool_expr)]
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/borrow_check/mod.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1737#-NLVVbPj0qenJ8aBhIJQ:-NLVcylhAN3XQHHbMcHu:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/29598e462362cff2528368facf055776dfa97eef/crates/cairo-lang-lowering/src/borrow_check/mod.rs#L23)):*
> ```XML
> 
> /// Information about the callsite of the current block. When lowering uses Goto, this won'st be
> /// necessary.
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/borrow_check/mod.rs` line 156 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1737#-NLVbEDEBYGoIL3mRRjm:-NLVdOp_EIMeZ6f9qUah:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/29598e462362cff2528368facf055776dfa97eef/crates/cairo-lang-lowering/src/borrow_check/mod.rs#L156)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/borrow_check/mod.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1737#-NLVbsFrAOHTBYDZoJvG:-NLVdOe29EV6h43t4_RM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/29598e462362cff2528368facf055776dfa97eef/crates/cairo-lang-lowering/src/borrow_check/mod.rs#L161)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

consider adding .extend
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/borrow_check/mod.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1737#-NLVc2jc4UV6u4zKfGCS:-NLVf4RL34FVWkHMAIqv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/29598e462362cff2528368facf055776dfa97eef/crates/cairo-lang-lowering/src/borrow_check/mod.rs#L171)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

do
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1737#-:-NLVga5k2ck-6-ylk5Yi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
