### PR TITLE
Implement divmod

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
Signed-off-by: Dori Medini <dori@<a href="starkware.co">starkware.co</a>>

---

**Stack**:
- #1189
- #1188 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1188)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1188#-:-NI86Esj3oYvdCmxhRGs:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1188#-NI85hP9AoLD7A3o2vdd:-NI85hP9AoLD7A3o2vde:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/665661531a229da79fe5f4815e9bdde6c3e75c76/crates/sierra_to_casm/src/invocations/uint128.rs#L125)):*
> ```XML
>                 // We must also check q explicitly; the only arithmetic constraint on q is bq+r=a,
>                 // and if b=2, a=1 and r=0, we can take q to be the inverse of 2 (much larger than
>                 // 2^128) and pass this constraint.
> ```





_Suggestion:_
```XML
                // Both `q` and `r` must be uint128.
                // We must check `r` explicitly: we later check that `0 <= b - (r + 1)` and `b * q + r = a`, however,
                // if `r = -1` we may pass both of these checks (say, if `b = a + 1` and `q = 1`).
                // We must also check q explicitly; the only arithmetic constraint on q is `b * q + r = a`,
                // and if `b = 2`, `a = 1` and `r = 0`, we can take `q` to be the inverse of 2 (much larger than
                // 2^128) and pass this constraint.
```
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1188#-NI864OX784HVgyWlORF:-NI864OX784HVgyWlORG:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/665661531a229da79fe5f4815e9bdde6c3e75c76/crates/sierra_to_casm/src/invocations/uint128.rs#L128)):*
> ```XML
>                 [ap + 0] = [[range_check]], ap++;
>                 [ap + 0] = [[range_check.unchecked_apply_known_ap_change(1)] + 1], ap++;
>                 // Verify r<b by constraining 0<=b-(r+1).
> ```





_Suggestion:_
```XML
                // Verify `r < b` by constraining `0 <= b - (r + 1)`.
```
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1188#-NI86AkECiOVxOqiCo03:-NI86AkECiOVxOqiCo04:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/665661531a229da79fe5f4815e9bdde6c3e75c76/crates/sierra_to_casm/src/invocations/uint128.rs#L132)):*
> ```XML
>                 (b.unchecked_apply_known_ap_change(3)) = [ap + 0] + [ap + -1], ap++;
>                 [ap + -1] = [[range_check.unchecked_apply_known_ap_change(4)] + 2], ap++;
>                 // Verify bq+r=a.
> ```





_Suggestion:_
```XML
                // Verify `b * q + r = a`.
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1188)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1188#-NI85hP9AoLD7A3o2vdd:-NI87tYX0FHilG44jRQ9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/665661531a229da79fe5f4815e9bdde6c3e75c76/crates/sierra_to_casm/src/invocations/uint128.rs#L125)):*
> ```XML
>                 // We must also check q explicitly; the only arithmetic constraint on q is bq+r=a,
>                 // and if b=2, a=1 and r=0, we can take q to be the inverse of 2 (much larger than
>                 // 2^128) and pass this constraint.
> ```

Done.
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1188#-NI864OX784HVgyWlORF:-NI87tOpBY3sXIMNDk7L:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/665661531a229da79fe5f4815e9bdde6c3e75c76/crates/sierra_to_casm/src/invocations/uint128.rs#L128)):*
> ```XML
>                 [ap + 0] = [[range_check]], ap++;
>                 [ap + 0] = [[range_check.unchecked_apply_known_ap_change(1)] + 1], ap++;
>                 // Verify r<b by constraining 0<=b-(r+1).
> ```

Done.
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1188#-NI86AkECiOVxOqiCo03:-NI87tta6LfleMQsHWE2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/665661531a229da79fe5f4815e9bdde6c3e75c76/crates/sierra_to_casm/src/invocations/uint128.rs#L132)):*
> ```XML
>                 (b.unchecked_apply_known_ap_change(3)) = [ap + 0] + [ap + -1], ap++;
>                 [ap + -1] = [[range_check.unchecked_apply_known_ap_change(4)] + 2], ap++;
>                 // Verify bq+r=a.
> ```

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1188)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1188)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Comment by dorimedini-starkware** [comment]
✓ Commit merged in pull request [#1189](https://github.com/starkware-libs/cairo2/pull/1189)

**Pull request merged**
