### PR TITLE
Coupons: add coupon_buy libfunc.

### PR DESCRIPTION
**Pull request by liorgold2**
**Stack**:
- #4661
- #4630 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4630)

### CODE REVIEW

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4630)* status: 0 of 9 files reviewed, 1 unresolved discussion

___
*[`tests/e2e_test_data/libfuncs/coupon` line 66 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4630#-Nm7E_PqC0jM16qrvs9I:-Nm7E_Pr2H_yu8vlrHa7:b-pkedby) ([raw file](https://github.com/starkware-libs/cairo/blob/36e72a2519f7b09a566aac83d084db5429f3a02a/tests/e2e_test_data/libfuncs/coupon#L66)):*
> ```
> //! > cairo
> impl DropCoupon<T, impl DropImpl: Drop<T>> of Drop<bar::<T, DropImpl>::Coupon>;
> extern fn coupon_buy<T>() -> T nopanic;
> ```

The fact that coupon_buy is generic in the type and not the function allows me to declare it as a normal extern function without adding to the compiler. The downside is that this high level definition is too generic - it can accept things that are not `Coupon` (of course the low level compiler will check this). I think it's worth it.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4630)* status: 4 of 11 files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/coupon.rs` line 85 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4630#-NmB7FKS9GjsEzKrUYMg:-NmB7FKS9GjsEzKrUYMh:b-duak4a) ([raw file](https://github.com/starkware-libs/cairo/blob/c9651b11ed0227c7fee0e2c639a840cd997eb8a2/crates/cairo-lang-sierra/src/extensions/modules/coupon.rs#L85)):*
> ```XML
>     const STR_ID: &'static str = "coupon_buy";
> 
>     fn specialize_signature(
> ```

`Obtain` sounds better to me - as it sounds less like getting it actually out of the gas counter.



_Code quote:_
```XML
/// Libfunc for buying a coupon for a function. The cost of the coupon is the cost of running the
/// function (not including the `call` and `ret` instructions).
/// The coupon can be used to pay in advance for running the function, and run it later for
/// free (paying only for the `call` and `ret` instructions) using `coupon_call`.
#[derive(Default)]
pub struct CouponBuyLibfunc {}
impl NamedLibfunc for CouponBuyLibfunc {
    type Concrete = SignatureAndFunctionConcreteLibfunc;
    const STR_ID: &'static str = "coupon_buy";

    fn specialize_signature(
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4630)* status: 6 of 11 files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/coupon.rs` line 85 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4630#-NmB7FKS9GjsEzKrUYMg:-NmBlB8b8vErgM23kxgO:bnh225z) ([raw file](https://github.com/starkware-libs/cairo/blob/c9651b11ed0227c7fee0e2c639a840cd997eb8a2/crates/cairo-lang-sierra/src/extensions/modules/coupon.rs#L85)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Umm... To me "buy" sounds ok since you pay from the wallet. `coupon_withdraw` can be the one that takes it from the gas counter (if we decide to have it). We can discuss f2f.
BTW, the current terminology I used for the opposite action (sell coupon and get the refund to the wallet) is `refund` (in contrast with the `redeposit` terminology that has to do with the gas counter).
</blockquote></details>

i know you pay from the wallet - but this still sounds confusing for me.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 9 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4630)* status: 8 of 11 files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`tests/e2e_test_data/libfuncs/coupon` line 66 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4630#-Nm7E_PqC0jM16qrvs9I:-NmBpAk_8e3FAnLFdlPv:bjjdvk5) ([raw file](https://github.com/starkware-libs/cairo/blob/36e72a2519f7b09a566aac83d084db5429f3a02a/tests/e2e_test_data/libfuncs/coupon#L66)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

The fact that coupon_buy is generic in the type and not the function allows me to declare it as a normal extern function without adding to the compiler. The downside is that this high level definition is too generic - it can accept things that are not `Coupon` (of course the low level compiler will check this). I think it's worth it.
</blockquote></details>

If so - it does require a higher level wrapper, making sure the type is a coupon.
since we really should not make the user writing fully generic coupon code just crash the compiler.

In other similar places (such as Felt252Dict) we have such a protection.

Here this will still require some validation, and something automatic to be known about coupons.

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4630)* status: 8 of 11 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/coupon.rs` line 85 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4630#-NmB7FKS9GjsEzKrUYMg:-Nmax1ZZ39rNegxRSYh8:b-joa4d8) ([raw file](https://github.com/starkware-libs/cairo/blob/c9651b11ed0227c7fee0e2c639a840cd997eb8a2/crates/cairo-lang-sierra/src/extensions/modules/coupon.rs#L85)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i know you pay from the wallet - but this still sounds confusing for me.
</blockquote></details>

Keeping this `buy` for now. We can change later if we agree on something else.
___
*[`tests/e2e_test_data/libfuncs/coupon` line 66 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4630#-Nm7E_PqC0jM16qrvs9I:-NmaxI4-4nrmgsZ1YhHc:b-6ikunl) ([raw file](https://github.com/starkware-libs/cairo/blob/36e72a2519f7b09a566aac83d084db5429f3a02a/tests/e2e_test_data/libfuncs/coupon#L66)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

If so - it does require a higher level wrapper, making sure the type is a coupon.
since we really should not make the user writing fully generic coupon code just crash the compiler.

In other similar places (such as Felt252Dict) we have such a protection.

Here this will still require some validation, and something automatic to be known about coupons.
</blockquote></details>

So we agreed on an empty `CouponTrait` that will allow us to define the wrapper assuming this trait. Not relevant for the test ATM. Will be relevant once we add `coupons.cairo` to the library.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 9 files at r1, 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4630#-:-NmbZcYT1eZEwsf_bpZe:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
