### PR TITLE
`ModuleFileNotFound` error code.

### LINKED ISSUE #6696: Implement code action for creating module files
Basically copy this from IntelliJ Rust:

https://github.com/user-attachments/assets/c5fef694-3a5a-4d2c-b864-2fbaa84eba3a

### PR DESCRIPTION
**Pull request by Draggu**
Closes #6696

### CODE REVIEW

**Review by piotmag769 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6720)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @mkaput, and @orizi)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6720#-OCEnfcO9PfjNNLH73Ol:-OCEnfcO9PfjNNLH73Om:b-ez0ib3) (no related file):*
Please add tests
___
*[`crates/cairo-lang-language-server/src/ide/code_actions/create_module_file.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6720#-OCEnbt_BOTYpCXZpt__:-OCEnbt_BOTYpCXZpt_a:b-6ws3by) ([raw file](https://github.com/starkware-libs/cairo/blob/67c4bfb36ec8d8e9a273ce02c4d3d47130a6dec0/crates/cairo-lang-language-server/src/ide/code_actions/create_module_file.rs#L23)):*
> ```XML
>             if let Ok(mut path) = url.path_segments_mut() {
>                 path.pop();
>                 path.push(&format!("{module_name}.cairo"));
> ```

Only works for creating module in `src/lib.cairo`

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6720)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @mkaput, and @orizi)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 1260 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6720#-OCHWvsM7QgqbOiWxmQ9:-OCHWvsN7KruiYLdX2xX:b-ji983r) ([raw file](https://github.com/starkware-libs/cairo/blob/67c4bfb36ec8d8e9a273ce02c4d3d47130a6dec0/crates/cairo-lang-semantic/src/diagnostic.rs#L1260)):*
> ```XML
>             }
>             Self::MissingMember(_) => error_code!(E0003),
>             Self::ModuleFileNotFound(_) => error_code!(E0004),
> ```

this conflicts with https://github.com/starkware-libs/cairo/pull/6690 by @integraledelebesgue as it also adds E0004. I think first PR merged wins this number, so just please be aware of this guys

**Review by piotmag769 — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6720)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, and @integraledelebesgue)

**Review by orizi — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6720)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, and @mkaput)

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6720#-:-OD6aDgOBe48dN-ID6El:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @integraledelebesgue)

**Pull request merged**
