### PR TITLE
Split storage_access and contract_address in corelib

### PR DESCRIPTION
**Pull request by gaetbout**
Put all ContractAddress related stuff within its own file
Same for StorageAddress related stuff

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2175)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2175)* status: 7 of 18 files reviewed, 1 unresolved discussion (waiting on @gaetbout)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/storage` line 31 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2175#-NOYqLJL6MbIwWYUeUOq:-NOYqLJL6MbIwWYUeUOr:bx86lj3) ([raw file](https://github.com/starkware-libs/cairo/blob/74f400d340ef1fef55601322c6dfe88aba6a1714/crates/cairo-lang-starknet/src/plugin/plugin_test_data/storage#L31)):*
> ```
>         use starknet::SyscallResultTraitImpl;
> 
>         fn address() -> storage_access::StorageBaseAddress {
> ```

I don't want consumer to have to know necessarily to look inside storage_address. Maybe reexport it at starknet.cairo?



_Code quote:_
```
storage_access::
```

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 11 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2175)* status: all files reviewed, 1 unresolved discussion (waiting on @gaetbout)

**Comment by gaetbout** [comment]
To make sure I understand correctly, you want me to move the type 
StorageBaseAddress
back to starknet.cairo?

**Comment by spapinistarkware** [comment]
No, I mean to add "use" in starknet.core, so that the rest of the uses remain as they were.

**Comment by gaetbout** [comment]
And thus reverting all places I used 
`storage_access::StorageBaseAddress`
to use
`starknet::StorageBaseAddress`
?

**Comment by gaetbout** [comment]
@spapinistarkware could you let me know if this is what you meant?
If yes, I'll proceed and fix the failing tests.

**Review by spapinistarkware — COMMENTED** [review]
Yes, that's a lot better.
Also, the new modules should be submodules of the starknet module. The whole starknet module will move in the future.

> Reviewed 1 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2175#-:-NOZCsvQ2QQ_t_sPTUfB:bqmzfop)* status: 3 of 18 files reviewed, 1 unresolved discussion (waiting on @gaetbout)

**Comment by gaetbout** [comment]
@spapinistarkware is this what you meant?

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 14 of 15 files at r2, 1 of 1 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2175#-:-NOZHgPIDz3mFsWoHTGJ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gaetbout)

**Comment by gaetbout** [comment]
@spapinistarkware 
Is there a way to automatically generate those files (check https://github.com/starkware-libs/cairo/actions/runs/4210956789/jobs/7308977599) or should I update them manually?

**Comment by spapinistarkware** [comment]
Run the tests with CAIRO_FOX_TESTS=1 env var

**Pull request merged**
