### PR TITLE
Enforced v0 for attribute 'external'

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3436)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 209 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3436#-NYCWHQ3-ND17DDlmP1m:-NYCWHQ3-ND17DDlmP1n:b-yy1cd7) ([raw file](https://github.com/starkware-libs/cairo/blob/b7221986d74b7d119f0c9af3718e7ca559ed0972/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L209)):*
> ```XML
> 
> /// Checks if the only arg of the given attribute is "v0".
> fn is_arg_v0(db: &dyn SyntaxGroup, attr: &Attribute) -> bool {
> ```

where are you checking that the attribute is 'external'?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 209 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3436#-NYCWHQ3-ND17DDlmP1m:-NYCX5We3RSeiWIm8Pwg:b-439p46) ([raw file](https://github.com/starkware-libs/cairo/blob/b7221986d74b7d119f0c9af3718e7ca559ed0972/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L209)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

where are you checking that the attribute is 'external'?
</blockquote></details>

nvm, I see that it is checked in the callsite.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3436#-NYCXgZ50L8nl9pFOFs_:-NYCXgZ50L8nl9pFOFsa:bu8c941) ([raw file](https://github.com/starkware-libs/cairo/blob/b7221986d74b7d119f0c9af3718e7ca559ed0972/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L31)):*
> ```XML
>     ) -> Option<Self> {
>         if let Some(attr) = item_function.find_attr(db, EXTERNAL_ATTR) {
>             validate_external_v0(db, diagnostics, &attr);
> ```

Maybe this should be a function?

`try_get_external_attribute`?



_Code quote:_
```XML
        if let Some(attr) = item_function.find_attr(db, EXTERNAL_ATTR) {
            validate_external_v0(db, diagnostics, &attr);
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3436)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3436#-NYCXgZ50L8nl9pFOFs_:-NYCumf7AL_il8U4JT5w:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b7221986d74b7d119f0c9af3718e7ca559ed0972/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L31)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Maybe this should be a function?

`try_get_external_attribute`?
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3436#-NYCzWvT5A0ovQCRrsnL:-NYCzWvT5A0ovQCRrsnM:b2iwfeq) ([raw file](https://github.com/starkware-libs/cairo/blob/b7221986d74b7d119f0c9af3718e7ca559ed0972/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L28)):*
> ```XML
>         db: &dyn SyntaxGroup,
>         diagnostics: &mut Vec<PluginDiagnostic>,
>         item_function: &FunctionWithBody,
> ```

why did you decide to accept any item here?



_Code quote:_
```XML
 item_function: &FunctionWithBody,
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3436)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3436)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3436#-NYCzWvT5A0ovQCRrsnL:-NYDYbAB2cYuY6flh0KJ:b-13o4ux) ([raw file](https://github.com/starkware-libs/cairo/blob/b7221986d74b7d119f0c9af3718e7ca559ed0972/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L28)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why did you decide to accept any item here?
</blockquote></details>

To not recreate the item as I do now. But maybe it's indeed better to not allow any item.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3436#-:-NYDdaPN8ZQxwAvJRRB1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3436#-:-NYDmTDJ8h61RYpV_tb4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
