### PR TITLE
Move ap_tracking_base into ApTracking.

### PR DESCRIPTION
**Pull request by liorgold2**
**Stack**:
- #3169
- #3154
- #3151
- #3150 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3150)

### CODE REVIEW

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3150)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 351 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3150#-NVUybri73UtDdghDd1s:-NVUybri73UtDdghDd1t:brsr4g9) ([raw file](https://github.com/starkware-libs/cairo/blob/6adb2ec9d25840ef263f2b809e9d006d0bebc906/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L351)):*
> ```XML
>                 })?,
>         };
>         let ap_tracking_base = if matches!(ap_tracking, ApTracking::Disabled) {
> ```

The logic that was here should be exactly equivalent to the new behavior.
(I think the new one is much more readable.)

**Review by orizi — APPROVED** [review]
> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3150)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3150#-:-NVVBJaO0_Bgb0RMtKdk:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3150#-:-NVZ97IOAg85B4O6YB_h:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3150)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
