### PR TITLE
Struct pattern: don't stop at the first diagnostic + refined diag poi…

### PR DESCRIPTION
**Pull request by yuvalsw**
…nters.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4185)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4185#-:-Nfp9jF97VrdoAhEQIDx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4185)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4185)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/items/test.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4185#-NfpDBNS4m5SJ8FxHtH1:-NfpDBNTCRIuSrseMdJN:b-8dz1df) ([raw file](https://github.com/starkware-libs/cairo/blob/0ba1c8c49c3d367154aa1185b45a3d62400eedc5/crates/cairo-lang-semantic/src/items/test.rs#L17)):*
> ```XML
>         use_: "use_",
>         module: "module",
>         pattern: "pattern",
> ```

deleted by mistake i guess.

**Comment by yuvalsw** [comment]
*[`crates/cairo-lang-semantic/src/items/test.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4185#-NfpDBNS4m5SJ8FxHtH1:-NfpEZ_u0oUUZHRzvsKL:b8qysun) ([raw file](https://github.com/starkware-libs/cairo/blob/0ba1c8c49c3d367154aa1185b45a3d62400eedc5/crates/cairo-lang-semantic/src/items/test.rs#L17)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

deleted by mistake i guess.
</blockquote></details>

No, moved test to existing "pattern" file.

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4185#-:-NfpG22KC4t2NK2A_FBd:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
