### PR TITLE
snippet change

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3761)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3744** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3744" target="_blank">Graphite</a> 
    * **PR #3745** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3745" target="_blank">Graphite</a> 
      * **PR #3746** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3746" target="_blank">Graphite</a> 
        * **PR #3747** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3747" target="_blank">Graphite</a> 
          * **PR #3748** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3748" target="_blank">Graphite</a> 
            * **PR #3749** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3749" target="_blank">Graphite</a> 
              * **PR #3750** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3750" target="_blank">Graphite</a> 
                * **PR #3751** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3751" target="_blank">Graphite</a> 
                  * **PR #3752** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3752" target="_blank">Graphite</a> 
                    * **PR #3753** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3753" target="_blank">Graphite</a> 
                      * **PR #3754** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3754" target="_blank">Graphite</a> 
                        * **PR #3755** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3755" target="_blank">Graphite</a> 
                          * **PR #3756** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3756" target="_blank">Graphite</a> 
                            * **PR #3757** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3757" target="_blank">Graphite</a> 
                              * **PR #3759** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3759" target="_blank">Graphite</a> 
                                * **PR #3760** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3760" target="_blank">Graphite</a> 
                                  * **PR #3761** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3761" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/3761?utm_source=stack-comment).

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3744** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3744" target="_blank">Graphite</a> 
    * **PR #3745** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3745" target="_blank">Graphite</a> 
      * **PR #3746** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3746" target="_blank">Graphite</a> 
        * **PR #3747** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3747" target="_blank">Graphite</a> 
          * **PR #3748** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3748" target="_blank">Graphite</a> 
            * **PR #3749** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3749" target="_blank">Graphite</a> 
              * **PR #3750** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3750" target="_blank">Graphite</a> 
                * **PR #3751** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3751" target="_blank">Graphite</a> 
                  * **PR #3752** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3752" target="_blank">Graphite</a> 
                    * **PR #3753** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3753" target="_blank">Graphite</a> 
                      * **PR #3754** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3754" target="_blank">Graphite</a> 
                        * **PR #3755** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3755" target="_blank">Graphite</a> 
                          * **PR #3756** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3756" target="_blank">Graphite</a> 
                            * **PR #3757** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3757" target="_blank">Graphite</a> 
                              * **PR #3759** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3759" target="_blank">Graphite</a> 
                                * **PR #3760** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3760" target="_blank">Graphite</a> 
                                  * **PR #3761** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3761" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/3761?utm_source=stack-comment).

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3761)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 553 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3761#-NaHRwb6ES15nSs2lMrK:-NaHRwb7BX6y9kyxHaVo:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e6ef61983ed835aa5c640160f5471152e7aba40e/crates/cairo-lang-semantic/src/corelib.rs#L553)):*
> ```XML
>         db.module_item_by_name(core_module, name.clone())
>             .unwrap_or_else(|_| panic!("Trait '{name}' was not found in core lib."))
>             .unwrap_or_else(|| panic!("Trait '{name}' was not found in core lib.")),
> ```





_Suggestion:_
```XML
        db.module_item_by_name(core_module, name.clone())
            .expect("Failed to load core lib.")
            .unwrap_or_else(|| panic!("Trait '{name}' was not found in core lib.")),
```

**Review by spapinistarkware — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3761#-:-Ns1zznWDHRxUlP_KJvT:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 553 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3761#-NaHRwb6ES15nSs2lMrK:-Ns1zz7V9T2JVcNe6Mls:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e6ef61983ed835aa5c640160f5471152e7aba40e/crates/cairo-lang-semantic/src/corelib.rs#L553)):*
> ```XML
>         db.module_item_by_name(core_module, name.clone())
>             .unwrap_or_else(|_| panic!("Trait '{name}' was not found in core lib."))
>             .unwrap_or_else(|| panic!("Trait '{name}' was not found in core lib.")),
> ```

Done.

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3761)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Pull request closed without merging**
