### PR TITLE
Support raw_output.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2246)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2246)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NOtPwWU-Hy5AG1xDxI0:-NOtPwWU-Hy5AG1xDxI1:b-r1ub6u) ([raw file](https://github.com/starkware-libs/cairo/blob/92f2212dca72d510fb54ec97a6434fb75738c498/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L82)):*
> ```XML
>         OptionReturnTypeClause::ReturnTypeClause(ty) => {
>             let ret_type_ast = ty.ty(db);
>             let ret_type_name = ret_type_ast.as_syntax_node().get_text_without_trivia(db);
> ```

this would not work with return type `Array :: < felt>` (due to the spaces) - you need to fully open it.



_Code quote:_
```XML
            let ret_type_ast = ty.ty(db);
            let ret_type_name = ret_type_ast.as_syntax_node().get_text_without_trivia(db);
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NOtPwWU-Hy5AG1xDxI0:-NOtlDcQ5yjewSmTnJKd:bavbdbn) ([raw file](https://github.com/starkware-libs/cairo/blob/92f2212dca72d510fb54ec97a6434fb75738c498/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L82)):*
> Array :: < felt>
is it bad to give an error in that case?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2246)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NOtPwWU-Hy5AG1xDxI0:-NOtmubL5BRFfEHNHLMi:b-tnw1j4) ([raw file](https://github.com/starkware-libs/cairo/blob/92f2212dca72d510fb54ec97a6434fb75738c498/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L82)):*
> Array :: < felt>
do you prefer something like:
    Error: Unexpected argument type. Expected: "core::array::Array::<core::felt>", found: "()".
 --> contract:115:38
            let res: Array::<felt> = super::bar2(__arg_a);
                                     ^******************^

The error reveals lots of implementation details.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2246)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NOtPwWU-Hy5AG1xDxI0:-NOtnLiN62cNVGqkfd4U:b-mfvbf3) ([raw file](https://github.com/starkware-libs/cairo/blob/92f2212dca72d510fb54ec97a6434fb75738c498/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L82)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

> Array :: < felt>
do you prefer something like:
    Error: Unexpected argument type. Expected: "core::array::Array::<core::felt>", found: "()".
 --> contract:115:38
            let res: Array::<felt> = super::bar2(__arg_a);
                                     ^******************^

The error reveals lots of implementation details.
</blockquote></details>

it is bad to give an error in such a case - and we can at the very least handle the simple case where the actual class was written at least.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2246)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NOtPwWU-Hy5AG1xDxI0:-NOtoAqj-OpWiUbfBRsQ:b75xutz) ([raw file](https://github.com/starkware-libs/cairo/blob/92f2212dca72d510fb54ec97a6434fb75738c498/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L82)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it is bad to give an error in such a case - and we can at the very least handle the simple case where the actual class was written at least.
</blockquote></details>

(just check that the type is `Array` wrapping a `felt` (can be easily tested in the syntax level)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NOtPwWU-Hy5AG1xDxI0:-NPBNo1-0okmkJjXuWMF:ba50w0d) ([raw file](https://github.com/starkware-libs/cairo/blob/92f2212dca72d510fb54ec97a6434fb75738c498/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L82)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I agree - 
Option 1 is not good as we shouldn't have an error in this case, or if someone specifies the same type using an alias or a different path.
Option 2 indeed is not clear and points to the generated code.

As suggested f2f - semantic module does similar stuff - processing the AST to examine the semantic meaning. You can export some functions used there to some shared library and use the same logic here and there. If this specific logic isn't really shared with semantic, you can just do stuff similar to the way semantic does it.
</blockquote></details>

Resolving paths and aliases feels wrong.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 124 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NOzkGjrEQc9hvSoCCRZ:-NPBO7EB4tlIYytD2PX8:bsukev3) ([raw file](https://github.com/starkware-libs/cairo/blob/92f2212dca72d510fb54ec97a6434fb75738c498/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L124)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Option for raw_output doesn't have `ref_appends`.
</blockquote></details>

Why is that a problem?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2246)* status: all files reviewed, 8 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NOzjiOF5TaeYX494B4z:-NPBbxEe7Yk86qYiQi00:brpmqc3) ([raw file](https://github.com/starkware-libs/cairo/blob/92f2212dca72d510fb54ec97a6434fb75738c498/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L75)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

const?
</blockquote></details>

removed.
___
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NOziAoA58AAbjf8M8RO:-NPBbwdGAc-1wE6v1ybS:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/92f2212dca72d510fb54ec97a6434fb75738c498/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L76)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

suggestion
</blockquote></details>

done



_Code quote:_
```XML
   let felt_array_type_str = "Array::<fel
```
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/diagnostics` line 1064 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NOzm38p1rtslmk5ZCBW:-NPBcsDg5UYjRpzAqho8:b-tcield) ([raw file](https://github.com/starkware-libs/cairo/blob/92f2212dca72d510fb54ec97a6434fb75738c498/crates/cairo-lang-starknet/src/plugin/plugin_test_data/diagnostics#L1064)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Please add a test for the case of Array::<felt> with spaces or a different path.
However you choose to treat it - either here or in the "good" flow test file.
</blockquote></details>

it seems that spaces are not allowed
+error: Skipped tokens. Expected: '{'.
+ --> lib.cairo:25:31
+    fn bar4(a: felt) -> Array : : <felt > {
+                              ^*********^

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/diagnostics` line 1064 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NOzm38p1rtslmk5ZCBW:-NPBdGiC0xFC5aJMvpdk:b-8iweq0) ([raw file](https://github.com/starkware-libs/cairo/blob/92f2212dca72d510fb54ec97a6434fb75738c498/crates/cairo-lang-starknet/src/plugin/plugin_test_data/diagnostics#L1064)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it seems that spaces are not allowed
+error: Skipped tokens. Expected: '{'.
+ --> lib.cairo:25:31
+    fn bar4(a: felt) -> Array : : <felt > {
+                              ^*********^
</blockquote></details>

Nvm, I put the spaces inside the seperator.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2246)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NOzjm_Q5XLImUffQcXe:-NPBeybs7krhj_bvwyKJ:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/92f2212dca72d510fb54ec97a6434fb75738c498/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L94)):*
> ```XML
>     if raw_output && !returns_felt_array {
>         diagnostics.push(PluginDiagnostic {
>             message: format!("`{RAW_OUTPUT_ATTR}` must return `{felt_array_type_str}`"),
> ```

done.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contract` line 23 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NOzkvB1BlLUFmlrpOk0:-NPBeAEW905eQe6JDxCH:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/92f2212dca72d510fb54ec97a6434fb75738c498/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contract#L23)):*
> ```
>     #[external]
>     #[raw_output]
>     fn test_raw_output(num: felt) -> Array::<felt>{
> ```

done
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contract` line 23 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NOzlGnz4mCTJhWfiuOo:-NPBeE346aYKX-DzG7Ei:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/92f2212dca72d510fb54ec97a6434fb75738c498/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contract#L23)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I think removing the param would focus better on the purpose of this test.
</blockquote></details>

done
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/diagnostics` line 1092 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NOzlw-7-fSLX2pjoz6H:-NPBfDqx2qBxCbUvrkTA:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/92f2212dca72d510fb54ec97a6434fb75738c498/crates/cairo-lang-starknet/src/plugin/plugin_test_data/diagnostics#L1092)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

This is unrelated. Return 0 from bar1.
</blockquote></details>

done

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2246#-:-NPD8MD-Eg9alNMzf6XN:bnfp4nl)* status: all files reviewed, 8 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 124 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NOzkGjrEQc9hvSoCCRZ:-NPD2XjLDPEbLabReZiI:b-jwfsea) ([raw file](https://github.com/starkware-libs/cairo/blob/92f2212dca72d510fb54ec97a6434fb75738c498/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L124)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why is that a problem?
</blockquote></details>

it's strange that you "try to replace" something that doesn't exist.
It may be nicer to replace ref_appends only in this option, and then replace here only what's relevant to all the options - wrapped_name.
But I don't feel strongly about it - I'm not sure I prefer it now. So just consider, and I'm OK with both options.
___
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NPD2Mgv3Cn5pU7Rnh1E:-NPD2Mgv3Cn5pU7Rnh1F:b89wscc) ([raw file](https://github.com/starkware-libs/cairo/blob/adfa356fc9b777d846aa9ca28dccadd4ce244052/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L110)):*
> ```XML
>         format!(
>             "let res: Array::<felt> = $wrapped_name$({arg_names_str});
>             res"
> ```

why not inline?



_Code quote:_
```XML
res
```
___
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 177 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NPD371MBW2muCv_5kn5:-NPD371MBW2muCv_5kn6:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/adfa356fc9b777d846aa9ca28dccadd4ce244052/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L177)):*
> ```XML
> }
> 
> // Returns true if type_ast is `Array::<felt>.
> ```





_Suggestion:_
```XML
/ Returns true if type_ast is `Array::<felt>`.
```
___
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 178 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NPD39rREhfR5j76NfSn:-NPD39rREhfR5j76NfSo:b2ngwfe) ([raw file](https://github.com/starkware-libs/cairo/blob/adfa356fc9b777d846aa9ca28dccadd4ce244052/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L178)):*
> ```XML
> 
> // Returns true if type_ast is `Array::<felt>.
> // Does not resolve paths or type aliases.
> ```

///
___
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 194 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NPD4f2984zVGiQa_A02:-NPD4f2984zVGiQa_A03:b99i0o9) ([raw file](https://github.com/starkware-libs/cairo/blob/adfa356fc9b777d846aa9ca28dccadd4ce244052/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L194)):*
> ```XML
>         if let [ast::Expr::Path(arg_path)] = args.as_slice() {
>             let arg_path_elements = arg_path.elements(db);
>             if let [ast::PathSegment::Simple(arg_segment)] = arg_path_elements.as_slice() {
> ```

I prefer it this way:
(less indentations, more readable)



_Suggestion:_
```XML
    
    if path_segment_with_generics.ident(db).text(db) != "Array" {return false;}
    let args = path_segment_with_generics.generic_args(db).generic_args(db).elements(db);
    let [ast::Expr::Path(arg_path)] = args.as_slice() else {return false;};
    let arg_path_elements = arg_path.elements(db);
    let [ast::PathSegment::Simple(arg_segment)] = arg_path_elements.as_slice() else {return false;};
    
    arg_segment.ident(db).text(db) == "felt"
        
```
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/diagnostics` line 1020 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NPD6MrqBFO6766R9l8Y:-NPD6MrqBFO6766R9l8Z:b4i6g20) ([raw file](https://github.com/starkware-libs/cairo/blob/adfa356fc9b777d846aa9ca28dccadd4ce244052/crates/cairo-lang-starknet/src/plugin/plugin_test_data/diagnostics#L1020)):*
> ```
> 
> 
>     // Should generate diagnistic as path resolving is not supported.
> ```

add a similar test for type alias?
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/diagnostics` line 1027 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NPD6JG80DjzvOkM4Wm_:-NPD6JG80DjzvOkM4Wma:b-71dbvl) ([raw file](https://github.com/starkware-libs/cairo/blob/adfa356fc9b777d846aa9ca28dccadd4ce244052/crates/cairo-lang-starknet/src/plugin/plugin_test_data/diagnostics#L1027)):*
> ```
>     }
> 
>     // Return type with spaces, should not generate diagnostics
> ```

move to other test file



_Code quote:_
```
 // Return type with spaces, should not generate diagnostics
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NPD2Mgv3Cn5pU7Rnh1E:-NPD8tN-9IHh-0q3kMZP:bf12h1v) ([raw file](https://github.com/starkware-libs/cairo/blob/adfa356fc9b777d846aa9ca28dccadd4ce244052/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L110)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

why not inline?
</blockquote></details>

Better type enforcement when its not inlined.

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2246)* status: all files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware and @yuvalsw)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 124 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NOzkGjrEQc9hvSoCCRZ:-NPD98qJD-eb4pKKLZlY:b-i23fq0) ([raw file](https://github.com/starkware-libs/cairo/blob/92f2212dca72d510fb54ec97a6434fb75738c498/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L124)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

it's strange that you "try to replace" something that doesn't exist.
It may be nicer to replace ref_appends only in this option, and then replace here only what's relevant to all the options - wrapped_name.
But I don't feel strongly about it - I'm not sure I prefer it now. So just consider, and I'm OK with both options.
</blockquote></details>

I don't know how to do that without calling
RewriteNode::interpolate_patched
in both the `if` and the `else`

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2246)* status: all files reviewed, 7 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/diagnostics` line 1027 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NPD6JG80DjzvOkM4Wm_:-NPD9M2c1YC_FeFPbRJr:buj64q4) ([raw file](https://github.com/starkware-libs/cairo/blob/adfa356fc9b777d846aa9ca28dccadd4ce244052/crates/cairo-lang-starknet/src/plugin/plugin_test_data/diagnostics#L1027)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

move to other test file
</blockquote></details>

what test file?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2246)* status: all files reviewed, 7 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/diagnostics` line 1027 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NPD6JG80DjzvOkM4Wm_:-NPD9P73ExLpuyoeXbFN:bbo758z) ([raw file](https://github.com/starkware-libs/cairo/blob/adfa356fc9b777d846aa9ca28dccadd4ce244052/crates/cairo-lang-starknet/src/plugin/plugin_test_data/diagnostics#L1027)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what test file?
</blockquote></details>

its a natural extenstion of this test.

**Review by yuvalsw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2246)* status: all files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NPD2Mgv3Cn5pU7Rnh1E:-NPD9EUd2_wdGVuFmZ98:bqbfv5d) ([raw file](https://github.com/starkware-libs/cairo/blob/adfa356fc9b777d846aa9ca28dccadd4ce244052/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L110)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Better type enforcement when its not inlined.
</blockquote></details>

You can do ```Array::<felt>($wrapped_name$({arg_names_str}))```

**Review by yuvalsw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2246)* status: all files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/diagnostics` line 1027 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NPD6JG80DjzvOkM4Wm_:-NPD9YF159oxqdVaTXvi:b-ptc43g) ([raw file](https://github.com/starkware-libs/cairo/blob/adfa356fc9b777d846aa9ca28dccadd4ce244052/crates/cairo-lang-starknet/src/plugin/plugin_test_data/diagnostics#L1027)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

its a natural extenstion of this test.
</blockquote></details>

crates/cairo-lang-starknet/src/plugin/plugin_test_data/contract
I thought it's for tests without diagnostics, and this one is for ones with diagnostics.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NPD2Mgv3Cn5pU7Rnh1E:-NPDIy1Y3eIbGSZpYiGa:baimzvm) ([raw file](https://github.com/starkware-libs/cairo/blob/adfa356fc9b777d846aa9ca28dccadd4ce244052/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L110)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

You can do ```Array::<felt>($wrapped_name$({arg_names_str}))```
</blockquote></details>

I would expect 
Array::<felt>(x)
to work for any x that can be converted into an array.

**Review by yuvalsw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2246)* status: all files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NPD2Mgv3Cn5pU7Rnh1E:-NPDK1NKEyAEbR3VxR7X:by7zahp) ([raw file](https://github.com/starkware-libs/cairo/blob/adfa356fc9b777d846aa9ca28dccadd4ce244052/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L110)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I would expect 
Array::<felt>(x)
to work for any x that can be converted into an array.
</blockquote></details>

I don't follow

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2246)* status: all files reviewed, 6 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NPD2Mgv3Cn5pU7Rnh1E:-NPDLG1N4mJBCCV_6_FH:b-eufj6r) ([raw file](https://github.com/starkware-libs/cairo/blob/adfa356fc9b777d846aa9ca28dccadd4ce244052/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L110)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I don't follow
</blockquote></details>

You suggested using
`Array::<felt>($wrapped_name$({arg_names_str}))`
I'm not sure
what
`Array::<felt>(x)`
means



_Code snippet:_
```XML
 Array::<felt>($wrapped_name$({arg_names_str}))
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2246)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NPD2Mgv3Cn5pU7Rnh1E:-NPDNYo4Cl9o9dxI6_Wv:b-s2j3bx) ([raw file](https://github.com/starkware-libs/cairo/blob/adfa356fc9b777d846aa9ca28dccadd4ce244052/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L110)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

You suggested using
`Array::<felt>($wrapped_name$({arg_names_str}))`
I'm not sure
what
`Array::<felt>(x)`
means
</blockquote></details>

Decided to remove it.
___
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 177 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NPD371MBW2muCv_5kn5:-NPDMV0BC8sB4IJXbk1f:bcgj6m2) ([raw file](https://github.com/starkware-libs/cairo/blob/adfa356fc9b777d846aa9ca28dccadd4ce244052/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L177)):*
>  Returns true if type_ast is `Array::<felt>`
done
___
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 178 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NPD39rREhfR5j76NfSn:-NPDMW4kAu_Wc1-joQEj:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/adfa356fc9b777d846aa9ca28dccadd4ce244052/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L178)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

///
</blockquote></details>

done
___
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 194 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NPD4f2984zVGiQa_A02:-NPDN0MeDqeGoXN3SXI6:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/adfa356fc9b777d846aa9ca28dccadd4ce244052/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L194)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I prefer it this way:
(less indentations, more readable)
</blockquote></details>

done
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/diagnostics` line 1020 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NPD6MrqBFO6766R9l8Y:-NPDMx7r5hBHrrIZ7XDs:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/adfa356fc9b777d846aa9ca28dccadd4ce244052/crates/cairo-lang-starknet/src/plugin/plugin_test_data/diagnostics#L1020)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

add a similar test for type alias?
</blockquote></details>

done
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/diagnostics` line 1027 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2246#-NPD6JG80DjzvOkM4Wm_:-NPDMxnc8gISusYqGAct:b-xej2ef) ([raw file](https://github.com/starkware-libs/cairo/blob/adfa356fc9b777d846aa9ca28dccadd4ce244052/crates/cairo-lang-starknet/src/plugin/plugin_test_data/diagnostics#L1027)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

crates/cairo-lang-starknet/src/plugin/plugin_test_data/contract
I thought it's for tests without diagnostics, and this one is for ones with diagnostics.
</blockquote></details>

added raw_output test.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 2 of 5 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2246)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
