### PR TITLE
Plugin generation errors

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1122)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1122)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/plugins/src/panicable.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1122#-NHyfLWM5PFMdqAGyqUT:-NHyfLWN12hiEm1bvP2_:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/f3c1915fa8eeec266d8bc9bfb1c309e1613232b4/crates/plugins/src/panicable.rs#L115)):*
> ```XML
> }
> 
> fn extract_option_ty(db: &dyn SyntaxGroup, signature: &ast::FunctionSignature) -> Option<String> {
> ```

doc



_Code quote:_
```XML
extract_option_ty
```
___
*[`crates/semantic/src/items/us.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1122#-NHyff670rNFSHCLiI4w:-NHyff68EAW6O2pH8kxC:b-53ddzh) ([raw file](https://github.com/starkware-libs/cairo/blob/f3c1915fa8eeec266d8bc9bfb1c309e1613232b4/crates/semantic/src/items/us.rs#L46)):*
> ```XML
>     let module_data = db.module_data(module_file_id.0)?;
>     let use_ast = module_data.uses.get(use_id)?;
>     let syntax_db = db.upcast();
> ```

is this change related?



_Code quote:_
```XML
    let syntax_db = db.upcast();

    diagnostics.report(&use_ast.name(syntax_db), SemanticDiagnosticKind::UseCycle);



    Some(UseData {
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1122)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1122)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/plugins/src/panicable.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1122#-NHyfLWM5PFMdqAGyqUT:-NI1LGDxAJJgKb01-x-Q:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f3c1915fa8eeec266d8bc9bfb1c309e1613232b4/crates/plugins/src/panicable.rs#L115)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/semantic/src/items/us.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1122#-NHyff670rNFSHCLiI4w:-NI1LHNRDC1TNpTDDQY8:bguai5d) ([raw file](https://github.com/starkware-libs/cairo/blob/f3c1915fa8eeec266d8bc9bfb1c309e1613232b4/crates/semantic/src/items/us.rs#L46)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is this change related?
</blockquote></details>

I thought I'd tax you.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1122)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/plugins/src/panicable.rs` line 115 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1122#-NI1N8oI3DK2RKWKtcUJ:-NI1N8oJ0RS45qfk2bHR:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/92e0d53c6c8d0f3322cd5723404b820ff4d57ed1/crates/plugins/src/panicable.rs#L115)):*
> ```XML
> }
> 
> /// EGiven a function signature, if it returns Option::<T>, returns T. Otherwise, returns None.
> ```





_Suggestion:_
```XML
/// Given a function signature, if it returns Option::<T>, returns T. Otherwise, returns None.
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1122)* status: 6 of 9 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/plugins/src/panicable.rs` line 115 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1122#-NI1N8oI3DK2RKWKtcUJ:-NI25sAq5YzXVHmNk3td:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/92e0d53c6c8d0f3322cd5723404b820ff4d57ed1/crates/plugins/src/panicable.rs#L115)):*
> ```XML
> }
> 
> /// EGiven a function signature, if it returns Option::<T>, returns T. Otherwise, returns None.
> ```

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1122)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 6 of 9 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1122)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
