### PR TITLE
Support sierra integer consts.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4624)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4624)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4624#-Nm8MqFR47GtpdXK3oqF:-Nm8MqFR47GtpdXK3oqG:bllfjoz) ([raw file](https://github.com/starkware-libs/cairo/blob/0e45736eca381d702f8b910230c3c50d2cd4f3ee/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L159)):*
> ```XML
>     let const_core_type = registry.get_type(&const_type.inner_ty).unwrap();
>     match const_core_type {
>         cairo_lang_sierra::extensions::core::CoreTypeConcrete::Felt252(_)
> ```

maybe just use the "type" + "value" args, and just make sure that the "type" has a valid range?

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4624)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 125 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4624#-NmA_Cor2w-6Gm7WSCug:-NmA_Cor2w-6Gm7WSCuh:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0db845d74d613ab684c0df1c5da8da94e4b19b78/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L125)):*
> ```XML
>             [_] => return Err(SpecializationError::UnsupportedGenericArg),
>             _ => return Err(SpecializationError::WrongNumberOfGenericArgs),
>         };
> ```





_Suggestion:_
```XML
        let ty = args_as_single_type(args)?;
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 129 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4624#-NmA_SMaEi1TtlyYKueE:-NmA_SMaEi1TtlyYKueF:burjluw) ([raw file](https://github.com/starkware-libs/cairo/blob/0db845d74d613ab684c0df1c5da8da94e4b19b78/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L129)):*
> ```XML
>         let [GenericArg::Type(inner_ty), ..] = generic_args.as_slice() else {
>             return Err(SpecializationError::UnsupportedGenericArg);
>         };
> ```

where is the validation this is a const-type?



_Code quote:_
```XML
        let generic_args = context.get_type_info(ty.clone())?.long_id.generic_args;
        let [GenericArg::Type(inner_ty), ..] = generic_args.as_slice() else {
            return Err(SpecializationError::UnsupportedGenericArg);
        };
```

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4624)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4624)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4624)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4624)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4624)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 125 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4624#-NmA_Cor2w-6Gm7WSCug:-NmAenKB71yYuBZlpq1p:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0db845d74d613ab684c0df1c5da8da94e4b19b78/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L125)):*
> ```XML
>             [_] => return Err(SpecializationError::UnsupportedGenericArg),
>             _ => return Err(SpecializationError::WrongNumberOfGenericArgs),
>         };
> ```

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 129 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4624#-NmA_SMaEi1TtlyYKueE:-NmAen_j-FncyzF_p4Lt:bqmjwcz) ([raw file](https://github.com/starkware-libs/cairo/blob/0db845d74d613ab684c0df1c5da8da94e4b19b78/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L129)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

where is the validation this is a const-type?
</blockquote></details>

Added.
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4624#-Nm8MqFR47GtpdXK3oqF:-NmkI_dv1LJTIWQURFCx:b-4sel7o) ([raw file](https://github.com/starkware-libs/cairo/blob/0e45736eca381d702f8b910230c3c50d2cd4f3ee/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L159)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe just use the "type" + "value" args, and just make sure that the "type" has a valid range?
</blockquote></details>

I don't have a nice way to get the type info, as it is not a concept in the sierra to casm phase.
I can simply return the values and rely solely on the sierra checks.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4624)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4624#-Nm8MqFR47GtpdXK3oqF:-NmkTkRL8TIYY3ovieni:b-oa8fvp) ([raw file](https://github.com/starkware-libs/cairo/blob/0e45736eca381d702f8b910230c3c50d2cd4f3ee/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L159)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

I don't have a nice way to get the type info, as it is not a concept in the sierra to casm phase.
I can simply return the values and rely solely on the sierra checks.
</blockquote></details>

removing this still sounds more sensible, as you won't be able to validate recursion in any case.
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler_test.rs` line 914 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4624#-NmkTrpg9u3su2nEyzNR:-NmkTrpg9u3su2nEyzNS:b-dsds9j) ([raw file](https://github.com/starkware-libs/cairo/blob/5a659a873dc333699d2316b8b97e7e26c2fc4605/crates/cairo-lang-sierra-to-casm/src/compiler_test.rs#L914)):*
> ```XML
>         "Non constable const type.")]
> #[test_case(indoc! {"
>         type u8 = u8;
> ```

use a type for which it isn't legal.
such as ECPoint

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4624)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4624#-Nm8MqFR47GtpdXK3oqF:-NmkWtZu9Aur7u-jwWuK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0e45736eca381d702f8b910230c3c50d2cd4f3ee/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L159)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

removing this still sounds more sensible, as you won't be able to validate recursion in any case.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler_test.rs` line 914 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4624#-NmkTrpg9u3su2nEyzNR:-NmkWt641-grCIjAvvhV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5a659a873dc333699d2316b8b97e7e26c2fc4605/crates/cairo-lang-sierra-to-casm/src/compiler_test.rs#L914)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

use a type for which it isn't legal.
such as ECPoint
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4624#-:-NmkZtwr1M1t80bsibJH:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4624)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4624)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
