### PR TITLE
Support PanicDestruct inside the PanicDestruct impl.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6220)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/borrow_check/mod.rs` line 257 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6220#-O4Zm7sb7-jqi_q_Sgtn:-O4Zm7sb7-jqi_q_Sgto:bs9jrmp) ([raw file](https://github.com/starkware-libs/cairo/blob/ca84aa4ab90fd823ef48b04792412f3a88a21774/crates/cairo-lang-lowering/src/borrow_check/mod.rs#L257)):*
> ```XML
>         let mut info = match vars {
>             [panic_var, _ret_var]
>                 if self.lowered.variables[panic_var.var_id].ty == self.panic_ty =>
> ```

another option is to add

self.is_panic_destruct_fn.



_Code quote:_
```XML
       if self.lowered.variables[panic_var.var_id].ty == self.panic_ty =>
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/borrow_check/mod.rs` line 257 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6220#-O4Zm7sb7-jqi_q_Sgtn:-O4_2EKk2le6JRA9X4pl:b-7tfmjp) ([raw file](https://github.com/starkware-libs/cairo/blob/ca84aa4ab90fd823ef48b04792412f3a88a21774/crates/cairo-lang-lowering/src/borrow_check/mod.rs#L257)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

another option is to add

self.is_panic_destruct_fn.
</blockquote></details>

added

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6220)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/destructs.rs` line 264 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6220#-O4_AA2p9YUXO-GAiF8e:-O4_AA2p9YUXO-GAiF8f:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/02636ba912c17b022a652043b860440371d2342f/crates/cairo-lang-lowering/src/destructs.rs#L264)):*
> ```XML
>             info.aux =
>                 PanicState::EndsWithPanic(vec![PanicLocation::PanicVar { statement_location }]);
>         }
> ```





_Suggestion:_
```XML
        // In the case of a `panic_destruct` the auto added destructs should be `panic_destruct` calls.
        if self.is_panic_destruct_fn {
            info.aux =
                PanicState::EndsWithPanic(vec![PanicLocation::PanicVar { statement_location }]);
        }
```
___
*[`crates/cairo-lang-lowering/src/borrow_check/mod.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6220#-O4_AZX71JmVEw5sl7rn:-O4_AZX71JmVEw5sl7ro:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/02636ba912c17b022a652043b860440371d2342f/crates/cairo-lang-lowering/src/borrow_check/mod.rs#L36)):*
> ```XML
>     destruct_fn: TraitFunctionId,
>     panic_destruct_fn: TraitFunctionId,
>     is_destruct_fn: bool,
> ```





_Suggestion:_
```XML
    is_panic_destruct_fn: bool,
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6220)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/destructs.rs` line 264 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6220#-O4_AA2p9YUXO-GAiF8e:-O4_DiqB71sOYvOVESlZ:bd5m4ib) ([raw file](https://github.com/starkware-libs/cairo/blob/02636ba912c17b022a652043b860440371d2342f/crates/cairo-lang-lowering/src/destructs.rs#L264)):*
> ```XML
>             info.aux =
>                 PanicState::EndsWithPanic(vec![PanicLocation::PanicVar { statement_location }]);
>         }
> ```

The change allows using panic_destruct; it does not prevent the usage of Drop/Destruct.
___
*[`crates/cairo-lang-lowering/src/borrow_check/mod.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6220#-O4_AZX71JmVEw5sl7rn:-O4_BeN63BJHc7C73Hv1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/02636ba912c17b022a652043b860440371d2342f/crates/cairo-lang-lowering/src/borrow_check/mod.rs#L36)):*
> ```XML
>     destruct_fn: TraitFunctionId,
>     panic_destruct_fn: TraitFunctionId,
>     is_destruct_fn: bool,
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6220#-:-O4_Lm_g65FVkoQSZQpN:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6220)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/test_data/destruct` line 133 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6220#-O4_XVQw6_3HQQELFIA_:-O4_XVQx0qrDp6xgmj7a:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6620ad08fdec861c20f191cdfde5a709d2671a1b/crates/cairo-lang-lowering/src/test_data/destruct#L133)):*
> ```
>     #[inline(never)]
>     fn panic_destruct(self: B, ref panic: Panic) nopanic {
>         let B { a } = self;
> ```





_Suggestion:_
```
        let B { a: _ } = self;
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6220)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/test_data/destruct` line 133 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6220#-O4_XVQw6_3HQQELFIA_:-O4_YhV_4Hajt9M4asaT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6620ad08fdec861c20f191cdfde5a709d2671a1b/crates/cairo-lang-lowering/src/test_data/destruct#L133)):*
> ```
>     #[inline(never)]
>     fn panic_destruct(self: B, ref panic: Panic) nopanic {
>         let B { a } = self;
> ```

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/test_data/destruct` line 139 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6220#-O4_Yrh33DYNX1qbyufd:-O4_Yrh33DYNX1qbyufe:b-uat6ly) ([raw file](https://github.com/starkware-libs/cairo/blob/6620ad08fdec861c20f191cdfde5a709d2671a1b/crates/cairo-lang-lowering/src/test_data/destruct#L139)):*
> ```
> //! > semantic_diagnostics
> warning[E0001]: Unused variable. Consider ignoring by prefixing with `_`.
>  --> lib.cairo:20:17
> ```

before the change I got:



_Suggestion:_
```
//! > lowering_diagnostics
error: Variable not dropped.
 --> lib.cairo:20:20
        let B { a: _ } = self;
                   ^
note: Trait has no implementation in context: core::traits::Drop::<test::A>.
note: Trait has no implementation in context: core::traits::Destruct::<test::A>.
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6220#-:-O4_ZbVS0qYyPM5FHA4f:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
