### PR TITLE
Added support for +=, -=, *=, /= and %= operators

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2002)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2002)* status: 0 of 30 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`corelib/traits.cairo` line 10 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2002#-NNAvlgt5E3lEpyjinva:-NNAvlgt5E3lEpyjinvb:b-gdo1co) ([raw file](https://github.com/starkware-libs/cairo/blob/be81f1157c212cb7aa59866607b67c9d380525d1/corelib/traits.cairo#L10)):*
> ```Cairo
>     // TODO(yuval): once default trait function implementation is supported, implement this here
>     // instead of in each impl.
>     fn add_eq(ref self: T, other: T);
> ```

I don't think it should be another method on this trait.
a+=b should be translated to a=Add::add(a,b) IMO.
I don't want the developer to have to implement add_eq.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2002)* status: 0 of 30 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`corelib/traits.cairo` line 10 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2002#-NNAvlgt5E3lEpyjinva:-NNB8j89BdXwLq4rQ104:br0l2yi) ([raw file](https://github.com/starkware-libs/cairo/blob/be81f1157c212cb7aa59866607b67c9d380525d1/corelib/traits.cairo#L10)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I don't think it should be another method on this trait.
a+=b should be translated to a=Add::add(a,b) IMO.
I don't want the developer to have to implement add_eq.
</blockquote></details>

I want it to be default implemented in the trait, once we have default implementations in traits. WDYT?

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2002)* status: 0 of 30 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`corelib/traits.cairo` line 10 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2002#-NNAvlgt5E3lEpyjinva:-NNBfJwT1v97zO-hHzYC:b-853pl8) ([raw file](https://github.com/starkware-libs/cairo/blob/be81f1157c212cb7aa59866607b67c9d380525d1/corelib/traits.cairo#L10)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I want it to be default implemented in the trait, once we have default implementations in traits. WDYT?
</blockquote></details>

I've split it to 2 traits as discussed.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2002)* status: 1 of 30 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`corelib/traits.cairo` line 15 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2002#-NNGqh6s2ofBlMBKbHoO:-NNGqh6s2ofBlMBKbHoP:b-jgl9uc) ([raw file](https://github.com/starkware-libs/cairo/blob/419262d22210f9a90f0fcf2a9e06af9e194b1725/corelib/traits.cairo#L15)):*
> ```Cairo
> // TODO(spapini): When associated types are supported, support the general trait Sub<X, Y>.
> trait Sub<T> {
>     // TODO(yuval): consider changing to self/other.
> ```

On the contrary. It's gpopd that it's not self.
self was a limitation of rust.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2002)* status: 1 of 30 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`corelib/traits.cairo` line 15 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2002#-NNGqh6s2ofBlMBKbHoO:-NNH0YrW0YBgWQGpMc8E:b-hfpv0l) ([raw file](https://github.com/starkware-libs/cairo/blob/419262d22210f9a90f0fcf2a9e06af9e194b1725/corelib/traits.cairo#L15)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

On the contrary. It's gpopd that it's not self.
self was a limitation of rust.
</blockquote></details>

removed



_Code quote:_
```Cairo
// TODO(yuval): consider changing to self/other.
```

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 30 files at r1, 2 of 7 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2002)* status: 9 of 30 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 261 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2002#-NNfKfTE9AQ7sI54wPIK:-NNfKfTE9AQ7sI54wPIL:bm60oqc) ([raw file](https://github.com/starkware-libs/cairo/blob/02c54014be7330fe31b06289bd27edc883ca0825/crates/cairo-lang-semantic/src/expr/compute.rs#L261)):*
> ```XML
>         return dot_expr(ctx, lexpr, rhs_syntax, stable_ptr);
>     }
>     if matches!(
> ```

I'd rather not include specific matches on binary operators here if not needed. Try to infer the mutability from the signatuer (like in self).

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 17 of 30 files at r1, 3 of 7 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2002)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2002)* status: 11 of 32 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 261 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2002#-NNfKfTE9AQ7sI54wPIK:-NNqbQci1aysPqJ5Y8Az:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/02c54014be7330fe31b06289bd27edc883ca0825/crates/cairo-lang-semantic/src/expr/compute.rs#L261)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I'd rather not include specific matches on binary operators here if not needed. Try to infer the mutability from the signatuer (like in self).
</blockquote></details>

Done.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2002)* status: 11 of 30 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2002#-NNqb_pO2sDhuSqwWtdE:-NNqb_pO2sDhuSqwWtdF:b-3yf84a) (no related file):*
change target branch

___

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 16 of 19 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2002#-:-NO3y8RY-ixwX2GgZXK5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 16 of 16 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2002)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2002)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
