### PR TITLE
LS: add support for struct members

### PR DESCRIPTION
**Pull request by piotmag769**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6145)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6145)* status: 4 of 10 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lang/inspect/defs.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6145#-O3axbX-5TTaC84k7fiE:-O3axbX07C34YSSDf7cH:b-8sh9xx) ([raw file](https://github.com/starkware-libs/cairo/blob/3d9313213128afaf6eb7c7c8fb3dfb0b3b8f9fb3/crates/cairo-lang-language-server/src/lang/inspect/defs.rs#L26)):*
> ```XML
> use crate::{find_definition, ResolvedItem};
> 
> type StructDef = ItemDef;
> ```

explain the redefinition.

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6145)* status: 4 of 10 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lang/inspect/defs.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6145#-O3b3Fas0py_j5R49c0Q:-O3b3Fas0py_j5R49c0R:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/3d9313213128afaf6eb7c7c8fb3dfb0b3b8f9fb3/crates/cairo-lang-language-server/src/lang/inspect/defs.rs#L37)):*
> ```XML
>     ExprInlineMacro(String),
>     Member((MemberId, StructDef)),
> }
> ```





_Suggestion:_
```XML
/// Keeps information about the symbol that is being searched for/inspected.
///
/// This is an ephemeral data structure.
/// Do not store it in any kind of state.
pub enum SymbolDef {
    Item(ItemDef),
    Variable(VariableDef),
    ExprInlineMacro(String),
    Member(MemberDef),
}

pub enum MemberDef {
    member: MemberId,
    struct: ItemDef,
}
```

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 4 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6145)* status: 7 of 10 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, and @piotmag769)

___
*[`crates/cairo-lang-doc/src/db.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6145#-O3b3h5D6DU5iBzjUyyy:-O3b3h5D6DU5iBzjUyyz:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/3d9313213128afaf6eb7c7c8fb3dfb0b3b8f9fb3/crates/cairo-lang-doc/src/db.rs#L13)):*
> ```XML
> 
> /// Item which documentation can be fetched from source code.
> #[derive(Clone, Debug, Hash, Eq, PartialEq)]
> ```





_Suggestion:_
```XML
#[derive(Copy, Clone, Debug, Hash, Eq, PartialEq)]
```

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6145)* status: 7 of 10 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

___
*[`crates/cairo-lang-doc/src/db.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6145#-O3b3h5D6DU5iBzjUyyy:-O3b7o1e9bZbMf3wwXzN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3d9313213128afaf6eb7c7c8fb3dfb0b3b8f9fb3/crates/cairo-lang-doc/src/db.rs#L13)):*
> ```XML
> 
> /// Item which documentation can be fetched from source code.
> #[derive(Clone, Debug, Hash, Eq, PartialEq)]
> ```

Done.
___
*[`crates/cairo-lang-language-server/src/lang/inspect/defs.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6145#-O3axbX-5TTaC84k7fiE:-O3b7pSz7GiN8IFY-era:b-w5ckpu) ([raw file](https://github.com/starkware-libs/cairo/blob/3d9313213128afaf6eb7c7c8fb3dfb0b3b8f9fb3/crates/cairo-lang-language-server/src/lang/inspect/defs.rs#L26)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

explain the redefinition.
</blockquote></details>

Not relevant anymore.
___
*[`crates/cairo-lang-language-server/src/lang/inspect/defs.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6145#-O3b3Fas0py_j5R49c0Q:-O3b87r2EcN-60v_Lvrx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3d9313213128afaf6eb7c7c8fb3dfb0b3b8f9fb3/crates/cairo-lang-language-server/src/lang/inspect/defs.rs#L37)):*
> ```XML
>     ExprInlineMacro(String),
>     Member((MemberId, StructDef)),
> }
> ```

Done.

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 5 of 10 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6145)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lang/inspect/defs.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6145#-O3b8c_TE1nbky_gbHqx:-O3b8c_TE1nbky_gbHqy:begjmi6) ([raw file](https://github.com/starkware-libs/cairo/blob/3d9313213128afaf6eb7c7c8fb3dfb0b3b8f9fb3/crates/cairo-lang-language-server/src/lang/inspect/defs.rs#L141)):*
> ```XML
>         contexts
>             .chain(this)
>             .map(|item| db.get_item_signature(DocumentableItemId::LookupItem(item)))
> ```

Implement `From<T> for DocumentableItemId` for all variants.
___
*[`crates/cairo-lang-language-server/src/lang/inspect/defs.rs` line 37 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6145#-O3bBgu96XSHq_6Lq9_i:-O3bBgu96XSHq_6Lq9_j:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/0fdcf99c83fa1da166aed89768a7440394c4c466/crates/cairo-lang-language-server/src/lang/inspect/defs.rs#L37)):*
> ```XML
> }
> 
> pub struct MemberDef {
> ```

doc
___
*[`crates/cairo-lang-language-server/src/lang/inspect/defs.rs` line 39 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6145#-O3bBj5w2WCq6fAdDCex:-O3bBj5w2WCq6fAdDCey:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0fdcf99c83fa1da166aed89768a7440394c4c466/crates/cairo-lang-language-server/src/lang/inspect/defs.rs#L39)):*
> ```XML
> pub struct MemberDef {
>     pub member: MemberId,
>     pub r#struct: ItemDef,
> ```





_Suggestion:_
```XML
structure
```

**Review by mkaput — COMMENTED** [review]
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6145)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6145)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, and @piotmag769)

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6145)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, and @mkaput)

___
*[`crates/cairo-lang-language-server/src/lang/inspect/defs.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6145#-O3b8c_TE1nbky_gbHqx:-O3bs18bA475PcZPPRCL:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3d9313213128afaf6eb7c7c8fb3dfb0b3b8f9fb3/crates/cairo-lang-language-server/src/lang/inspect/defs.rs#L141)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Implement `From<T> for DocumentableItemId` for all variants.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lang/inspect/defs.rs` line 37 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6145#-O3bBgu96XSHq_6Lq9_i:-O3bq5vY8UxSdMx3IwcO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0fdcf99c83fa1da166aed89768a7440394c4c466/crates/cairo-lang-language-server/src/lang/inspect/defs.rs#L37)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lang/inspect/defs.rs` line 39 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6145#-O3bBj5w2WCq6fAdDCex:-O3bq5EY33fTHxE2v5Fo:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0fdcf99c83fa1da166aed89768a7440394c4c466/crates/cairo-lang-language-server/src/lang/inspect/defs.rs#L39)):*
> ```XML
> pub struct MemberDef {
>     pub member: MemberId,
>     pub r#struct: ItemDef,
> ```

Done.

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6145)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)

**Pull request merged**
