### PR TITLE
Fixed lowering of match statement such that the expression in the otherwise pattern is lowered once.

### PR DESCRIPTION
**Pull request by TomerStarkware**
… lowering block for user code

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4681)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4681)* status: 0 of 19 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/inline/test_data/inline` line 80 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4681#-Nmq4dLM3DxyfiLqNNGK:-Nmq4dLM3DxyfiLqNNGL:bac6iz1) ([raw file](https://github.com/starkware-libs/cairo/blob/7b0c7a006e87dac956147c82ff90abbc28d8e3f4/crates/cairo-lang-lowering/src/inline/test_data/inline#L80)):*
> ```
>         Option::None => val2,
>     }
> }
> ```

non `|` or `_` matches should not have changed.



_Code quote:_
```
    match val {
        Option::Some(x) => x,
        Option::None => val2,
    }
}
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4681)* status: 0 of 19 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/inline/test_data/inline` line 80 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4681#-Nmq4dLM3DxyfiLqNNGK:-NmqGfEL1thnkuxZPRUq:bb0bike) ([raw file](https://github.com/starkware-libs/cairo/blob/7b0c7a006e87dac956147c82ff90abbc28d8e3f4/crates/cairo-lang-lowering/src/inline/test_data/inline#L80)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

non `|` or `_` matches should not have changed.
</blockquote></details>

Now only variables' Id change,

**Comment by ilyalesokhin-starkware** [comment]
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4681#-NmyL4KfClx-PSy5YZJk):*
what is 'on lowering'?



_Code quote:_
```
in on lowering block for user code
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1299 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4681#-NmyZS564fNEuNNic8mr:-NmyZS564fNEuNNic8ms:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a25a308976728b35dab6e21f01fda41aeda979ed/crates/cairo-lang-lowering/src/lower/mod.rs#L1299)):*
> ```XML
> 
> /// Groups match arms of different variants to their corresponding arms blocks and lowers the lower
> /// the arms expression.
> ```





_Suggestion:_
```XML
/// Groups match arms of different variants to their corresponding arms blocks and lowers
/// the arms expression.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/test_data/match` line 416 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4681#-Nmy_pSM6QwJ9y0sMiVM:-Nmy_pSNB-ckiazd2c2M:b-o28vrw) ([raw file](https://github.com/starkware-libs/cairo/blob/a25a308976728b35dab6e21f01fda41aeda979ed/crates/cairo-lang-lowering/src/test_data/match#L416)):*
> ```
>  --> lib.cairo:2:9
>   match felt252_is_zero(5) {};
>         ^****************^
> ```

why does the error apper twice now?



_Code quote:_
```
error: Enum variant `NonZero` not covered.
 --> lib.cairo:2:9
  match felt252_is_zero(5) {};
        ^****************^
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/test_data/match` line 523 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4681#-Nmya4mhBRfzGsZ8pyr7:-Nmya4mhBRfzGsZ8pyr8:b2ni2nk) ([raw file](https://github.com/starkware-libs/cairo/blob/a25a308976728b35dab6e21f01fda41aeda979ed/crates/cairo-lang-lowering/src/test_data/match#L523)):*
> ```
>  --> lib.cairo:5:17
>   Four: (felt252),
>                 ^
> ```

fix



_Code quote:_
```
 --> lib.cairo:5:17
  Four: (felt252),
                ^
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1317 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4681#-Nmyaf_u6O-0CC_XbwDP:-Nmyaf_u6O-0CC_XbwDQ:bcz8cs) ([raw file](https://github.com/starkware-libs/cairo/blob/a25a308976728b35dab6e21f01fda41aeda979ed/crates/cairo-lang-lowering/src/lower/mod.rs#L1317)):*
> ```XML
>                     (lowering_inner_pattern_result, subscope)
>                 })
>                 .unzip();
> ```

Why unzip? are they used separately?



_Code quote:_
```XML
  .unzip();
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1331 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4681#-NmyhLo-8nXx2j0L2MJN:-NmyhLo09rvHjtxF3MLB:bfd1wb1) ([raw file](https://github.com/starkware-libs/cairo/blob/a25a308976728b35dab6e21f01fda41aeda979ed/crates/cairo-lang-lowering/src/lower/mod.rs#L1331)):*
> ```XML
>                 }
>                 .map_err(LoweringFlowError::Failed);
>             }
> ```

what happens if you don't do this special case?



_Code quote:_
```XML
            // If the arm has only one pattern, there is no need to create a parent scope.
            if subscopes.len() == 1 {
                let subscope = subscopes.pop().unwrap();
                let lowering_inner_pattern_result = lowering_inner_pattern_results.pop().unwrap();
                return match lowering_inner_pattern_result {
                    Ok(_) => {
                        // Lower the arm expression.
                        lower_tail_expr(ctx, subscope, arm.expression)
                    }
                    Err(err) => lowering_flow_error_to_sealed_block(ctx, subscope, err),
                }
                .map_err(LoweringFlowError::Failed);
            }
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1272 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4681#-Nmyn7qW4vqGOQ9zrmWg:-Nmyn7qW4vqGOQ9zrmWh:bo7ftmd) ([raw file](https://github.com/starkware-libs/cairo/blob/a25a308976728b35dab6e21f01fda41aeda979ed/crates/cairo-lang-lowering/src/lower/mod.rs#L1272)):*
> ```XML
>                      type"
>                 ),
>             };
> ```

Why is the logic here split from the pattern related logic in `group_match_arms`?



_Code quote:_
```XML
            let lowering_inner_pattern_result = match pattern {
                Pattern::EnumVariant(PatternEnumVariant {
                    inner_pattern: Some(inner_pattern),
                    ..
                }) => lower_single_pattern(
                    ctx,
                    &mut subscope,
                    ctx.function_body.patterns[*inner_pattern].clone(),
                    variant_expr,
                ),
                Pattern::EnumVariant(PatternEnumVariant { inner_pattern: None, .. })
                | Pattern::Otherwise(_) => Ok(()),
                _ => unreachable!(
                    "function `get_variant_to_arm_map` should have reported every other pattern \
                     type"
                ),
            };
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4681)* status: 0 of 19 files reviewed, 8 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4681#-NmyL4KfClx-PSy5YZJk):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what is 'on lowering'?
</blockquote></details>

one
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1299 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4681#-NmyZS564fNEuNNic8mr:-Nmym1mw-vqfqEY1eCBe:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a25a308976728b35dab6e21f01fda41aeda979ed/crates/cairo-lang-lowering/src/lower/mod.rs#L1299)):*
> ```XML
> 
> /// Groups match arms of different variants to their corresponding arms blocks and lowers the lower
> /// the arms expression.
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1317 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4681#-Nmyaf_u6O-0CC_XbwDP:-Nmyn0mnDVBj8jN9f047:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a25a308976728b35dab6e21f01fda41aeda979ed/crates/cairo-lang-lowering/src/lower/mod.rs#L1317)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why unzip? are they used separately?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1331 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4681#-NmyhLo-8nXx2j0L2MJN:-NmykWk61K1E1VkqwmSr:b-dis02z) ([raw file](https://github.com/starkware-libs/cairo/blob/a25a308976728b35dab6e21f01fda41aeda979ed/crates/cairo-lang-lowering/src/lower/mod.rs#L1331)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what happens if you don't do this special case?
</blockquote></details>

I believe after optimization code should be identical, but more tests change without it
___
*[`crates/cairo-lang-lowering/src/test_data/match` line 416 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4681#-Nmy_pSM6QwJ9y0sMiVM:-NmykGzP4ET2OWljt-5H:bg1d92i) ([raw file](https://github.com/starkware-libs/cairo/blob/a25a308976728b35dab6e21f01fda41aeda979ed/crates/cairo-lang-lowering/src/test_data/match#L416)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why does the error apper twice now?
</blockquote></details>

I had a bug in old code where extern match would not show all missing arms, 
now both show, like regular enum
___
*[`crates/cairo-lang-lowering/src/test_data/match` line 523 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4681#-Nmya4mhBRfzGsZ8pyr7:-Nmyn6dx33uWoc1RSrmK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a25a308976728b35dab6e21f01fda41aeda979ed/crates/cairo-lang-lowering/src/test_data/match#L523)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

fix
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 19 files at r1, 16 of 17 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4681)* status: 17 of 19 files reviewed, 9 unresolved discussions (waiting on @orizi and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/test_data/match` line 504 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4681#-NmyaKu9ELbn75UwP8YE:-NmyaKu9ELbn75UwP8YF:bzfsdek) ([raw file](https://github.com/starkware-libs/cairo/blob/a25a308976728b35dab6e21f01fda41aeda979ed/crates/cairo-lang-lowering/src/test_data/match#L504)):*
> ```
>     _ => 3,
>     A::Two(_) => 4,
>     A::Three(_) => 5,
> ```

are we planning on adding an `unreachable ` warning?



_Code quote:_
```
    A::Two(_) => 4,
    A::Three(_) => 5,
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4681)* status: 17 of 19 files reviewed, 10 unresolved discussions (waiting on @orizi and @TomerStarkware)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4681#-NmyrGQ-66C9fkxF-qke):*




_Suggestion:_
```
Fixed lowering of match statement such that the expression in the otherwise pattern is lowered once.
```
___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4681#-NmyL4KfClx-PSy5YZJk):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

one
</blockquote></details>

sorry still not clear enough, see below.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1335 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4681#-Nmyrw__9XdZokwUZk1m:-Nmyrw_a5sVlGVV9e6bg:b7hq7ne) ([raw file](https://github.com/starkware-libs/cairo/blob/e9a0e1f0163d3efd0b86aa131eff23adf6e235d5/crates/cairo-lang-lowering/src/lower/mod.rs#L1335)):*
> ```XML
> 
>             // really a parent block builder
>             let mut outer_subscope = lowering_inner_pattern_results_and_subscopes[0]
> ```

why is the first subscope special?



_Code quote:_
```XML
owering_inner_pattern_results_and_subscopes[0]
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1335 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4681#-Nmyrw__9XdZokwUZk1m:-NmysNV8BXWRch6T5A8U:b-nyze92) ([raw file](https://github.com/starkware-libs/cairo/blob/e9a0e1f0163d3efd0b86aa131eff23adf6e235d5/crates/cairo-lang-lowering/src/lower/mod.rs#L1335)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why is the first subscope special?
</blockquote></details>

`outer_subscope` should be a child of the parent block right?

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4681)* status: 17 of 19 files reviewed, 11 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4681#-NmyrGQ-66C9fkxF-qke):*
Done.
___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4681#-NmyL4KfClx-PSy5YZJk):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

sorry still not clear enough, see below.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1272 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4681#-Nmyn7qW4vqGOQ9zrmWg:-Nmz7Xkm6tIeFef__38U:b-xeorfa) ([raw file](https://github.com/starkware-libs/cairo/blob/a25a308976728b35dab6e21f01fda41aeda979ed/crates/cairo-lang-lowering/src/lower/mod.rs#L1272)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why is the logic here split from the pattern related logic in `group_match_arms`?
</blockquote></details>

it is different for extern enum, and value enum

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 19 files at r1, 16 of 17 files at r2, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4681)* status: 18 of 19 files reviewed, 10 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4681)* status: 18 of 19 files reviewed, 10 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1335 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4681#-Nmyrw__9XdZokwUZk1m:-Nmzhbbi-aPKJ6Yhv3cY:bum736a) ([raw file](https://github.com/starkware-libs/cairo/blob/e9a0e1f0163d3efd0b86aa131eff23adf6e235d5/crates/cairo-lang-lowering/src/lower/mod.rs#L1335)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

`outer_subscope` should be a child of the parent block right?
</blockquote></details>

the first is not special they should all have the same 'changed member path', I just need one of them.

yes outer subscope is logically the child of the parent block but since I need the same semantic, making it a sibling works
___
*[`crates/cairo-lang-lowering/src/test_data/match` line 504 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4681#-NmyaKu9ELbn75UwP8YE:-Nmzi9oK3y7Hp_MqTWl8:b-9h4epi) ([raw file](https://github.com/starkware-libs/cairo/blob/a25a308976728b35dab6e21f01fda41aeda979ed/crates/cairo-lang-lowering/src/test_data/match#L504)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

are we planning on adding an `unreachable ` warning?
</blockquote></details>

No, it should stay an error

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1335 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4681#-Nmyrw__9XdZokwUZk1m:-Nn2nYNRAorbOPZejJKw:bhvntcs) ([raw file](https://github.com/starkware-libs/cairo/blob/e9a0e1f0163d3efd0b86aa131eff23adf6e235d5/crates/cairo-lang-lowering/src/lower/mod.rs#L1335)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

the first is not special they should all have the same 'changed member path', I just need one of them.

yes outer subscope is logically the child of the parent block but since I need the same semantic, making it a sibling works
</blockquote></details>

can you improve the comment.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4681)* status: 18 of 19 files reviewed, 5 unresolved discussions (waiting on @orizi and @TomerStarkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4681#-:-Nn4-M9d8uyWvPz2pkTU:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4681)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1335 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4681#-Nmyrw__9XdZokwUZk1m:-Nn453W7Bn9nCi3YIMUZ:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/e9a0e1f0163d3efd0b86aa131eff23adf6e235d5/crates/cairo-lang-lowering/src/lower/mod.rs#L1335)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

can you improve the comment.
</blockquote></details>

?

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4681)* status: 18 of 19 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1335 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4681#-Nmyrw__9XdZokwUZk1m:-Nn4YtUX7PnC5MW9oWpX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e9a0e1f0163d3efd0b86aa131eff23adf6e235d5/crates/cairo-lang-lowering/src/lower/mod.rs#L1335)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4681)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4681#-:-Nn82brt0wYvoQMwU9qI:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
