### PR TITLE
Continue dict_squash refactor: SquashDictInnerLoop.

### PR DESCRIPTION
**Pull request by liorgold2**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2545)

### CODE REVIEW

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2545)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs` line 682 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2545#-NQtZOAV1RUd3MeHBZqL:-NQtZOAV1RUd3MeHBZqM:b-z2i5f1) ([raw file](https://github.com/starkware-libs/cairo/blob/c00fc5217e0a4c00344e9a2b69c3dbfe7bacdbf6/crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs#L682)):*
> ```XML
> 
> struct SquashDictInnerLoopArgs {
>     prev_loop_locals_range_check_ptr: Var,
> ```

Do I really need all of them? Most of them only appear in the rescope.

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2545)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs` line 682 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2545#-NQtZOAV1RUd3MeHBZqL:-NQtxiu44nfRnmcYWYPN:b-x3a2f7) ([raw file](https://github.com/starkware-libs/cairo/blob/04c368ef9e804a501f69279374d56366c26060a8/crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs#L682)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Do I really need all of them? Most of them only appear in the rescope.
</blockquote></details>

They need to live past the rescope, so yes.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs` line 750 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2545#-NQty1JF1jEK3HHhVu3M:-NQty1JF1jEK3HHhVu3N:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/04c368ef9e804a501f69279374d56366c26060a8/crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs#L750)):*
> ```XML
>         tempvar inner_prev_loop_locals_access_ptr = loop_locals_access_ptr;
>         tempvar inner_prev_loop_locals_value = loop_locals_value;
>         tempvar inner_prev_loop_locals_range_check_ptr = loop_locals_range_check_ptr;
> ```


___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs` line 757 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2545#-NQtyCu08SfrkY6AjQxq:-NQtyCu08SfrkY6AjQxr:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/04c368ef9e804a501f69279374d56366c26060a8/crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs#L757)):*
> ```XML
>             prev_loop_locals_access_ptr = inner_prev_loop_locals_access_ptr,
>             prev_loop_locals_value = inner_prev_loop_locals_value,
>             prev_loop_locals_range_check_ptr = inner_prev_loop_locals_range_check_ptr,
> ```





_Suggestion:_
```XML
            prev_loop_locals_access_ptr = loop_locals_access_ptr,
            prev_loop_locals_value = loop_locals_value,
            prev_loop_locals_range_check_ptr = loop_locals_range_check_ptr,
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs` line 766 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2545#-NQtxu4u3MJWPtKaF0gI:-NQtxu4u3MJWPtKaF0gJ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/04c368ef9e804a501f69279374d56366c26060a8/crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs#L766)):*
> ```XML
>             squash_dict_inner_arg_squashed_dict_end = squash_dict_inner_arg_squashed_dict_end,
>             squash_dict_inner_arg_big_keys = squash_dict_inner_arg_big_keys,
>             squash_dict_inner_arg_squashed_dict_end = squash_dict_inner_arg_squashed_dict_end,
> ```

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2545#-:-NQu0pU42PA6rEDjMa1L:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2545)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs` line 757 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2545#-NQtyCu08SfrkY6AjQxq:-NQuAI-p5wzIjTD7yFXm:buc17ql) ([raw file](https://github.com/starkware-libs/cairo/blob/04c368ef9e804a501f69279374d56366c26060a8/crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs#L757)):*
> ```XML
>             prev_loop_locals_access_ptr = inner_prev_loop_locals_access_ptr,
>             prev_loop_locals_value = inner_prev_loop_locals_value,
>             prev_loop_locals_range_check_ptr = inner_prev_loop_locals_range_check_ptr,
> ```

Will this generate tempvars?
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs` line 766 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2545#-NQtxu4u3MJWPtKaF0gI:-NQuAFJI0fw_LvCTPqbI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/04c368ef9e804a501f69279374d56366c26060a8/crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs#L766)):*
> ```XML
>             squash_dict_inner_arg_squashed_dict_end = squash_dict_inner_arg_squashed_dict_end,
>             squash_dict_inner_arg_big_keys = squash_dict_inner_arg_big_keys,
>             squash_dict_inner_arg_squashed_dict_end = squash_dict_inner_arg_squashed_dict_end,
> ```

Done.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2545)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs` line 757 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2545#-NQtyCu08SfrkY6AjQxq:-NQuB4Fk5DafBBSOW050:b-5h53c4) ([raw file](https://github.com/starkware-libs/cairo/blob/04c368ef9e804a501f69279374d56366c26060a8/crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs#L757)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Will this generate tempvars?
</blockquote></details>

No, it only says the the var on the left should have the value of the var on the right. It is later asserted that all the state merged in some point have the same value for all the variables in the two states.

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2545)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
