### PR TITLE
Add match_optimizer.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2386)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
I'm still debugging it, but I would like to see your inputs if you see anything wrong.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2386#-:-NPuyZlA5-gdX1Er3SFu:bjs9pmp)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @orizi and @spapinistarkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, 8 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2386)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2386#-NPuzYT0A8GDOkZQmrf4:-NPuzYT0A8GDOkZQmrf5:b2ni2nk) ([raw file](https://github.com/starkware-libs/cairo/blob/9b8255bf4cc1fdf8e1423518efe2866626446524/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L13)):*
> ```XML
> };
> 
> /// Order the blocks in a lowered function topologically.
> ```

fix



_Code quote:_
```XML
/// Order the blocks in a lowered function topologically.
```
___
*[`crates/cairo-lang-lowering/src/optimizations/test_data/option` line 10 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2386#-NPv0G9G0-NJMa4iqdSJ:-NPv0G9G0-NJMa4iqdSK:b-2sxk4h) ([raw file](https://github.com/starkware-libs/cairo/blob/9b8255bf4cc1fdf8e1423518efe2866626446524/crates/cairo-lang-lowering/src/optimizations/test_data/option#L10)):*
> ```
>   match bar(a) {
>     Option::Some(x) => x,
>     Option::None(()) => {
> ```

maybe do something simpler instead? i don't think there's a need to rely on inlining:
```
extern fn get_option() -> Option<u16>;

fn foo() -> Option<u64> {
   let v = get_option();
   let v = match v {
        Option::Some(_) => Option::Some(1_u32),
        Option::Nome(_) => Option::Nome(()),
   };
   match v {
        Option::Some(_) => Option::Some(1_u64),
        Option::Nome(_) => Option::Nome(()),
   }
}
```



_Code quote:_
```
//! > function
fn foo(a: felt) -> u16 {
  match bar(a) {
    Option::Some(x) => x,
    Option::None(()) => {
        17_u16
    },
  }
}

//! > function_name
foo

//! > module_code
use option::Option;
use option::OptionTrait;
use integer::u16_try_from_felt;

#[inline(always)]
fn bar(a: felt) -> Option<u16> {
  u16_try_from_felt(a)
}
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2386)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2386#-NPvMxlK5ZJGghuCyzKA:-NPvMxlLB4TOdN1F6XDS:b-4qn9p2) ([raw file](https://github.com/starkware-libs/cairo/blob/9b8255bf4cc1fdf8e1423518efe2866626446524/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L90)):*
> ```XML
> 
>             for (dst, src) in remapping.iter() {
>                 let key = *info.remapping.get(dst).unwrap_or(dst);
> ```

Rename. Consider this:



_Suggestion:_
```XML
dst_after_match
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2386)* status: 9 of 10 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2386#-NPvN6eqDEyLUGf6bwEG:-NPvN6eqDEyLUGf6bwEH:b-u8vxj7) ([raw file](https://github.com/starkware-libs/cairo/blob/9b8255bf4cc1fdf8e1423518efe2866626446524/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L90)):*
> ```XML
> 
>             for (dst, src) in remapping.iter() {
>                 let key = *info.remapping.get(dst).unwrap_or(dst);
> ```

Consider renaming



_Suggestion:_
```XML
remapping_until_match
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2386)* status: 9 of 10 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2386#-NPvMxlK5ZJGghuCyzKA:-NPvNBxtAu-t73g2y1Vp:b-kmqehp) ([raw file](https://github.com/starkware-libs/cairo/blob/9b8255bf4cc1fdf8e1423518efe2866626446524/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L90)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Rename. Consider this:
</blockquote></details>

or maybe dst_at_match

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2386)* status: 9 of 10 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 99 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2386#-NPvNLH-A5HrEQdapjHX:-NPvNLH-A5HrEQdapjHY:basbwsh) ([raw file](https://github.com/starkware-libs/cairo/blob/9b8255bf4cc1fdf8e1423518efe2866626446524/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L99)):*
> ```XML
>     }
> 
>     fn visit_block_start(
> ```

Doesn't this have a deafult empty impl at the trait?



_Code quote:_
```XML
visit_block_start
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2386)* status: 9 of 10 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 137 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2386#-NPvNabPDSfziJnMxi5x:-NPvNabPDSfziJnMxi5y:b-ns63kl) ([raw file](https://github.com/starkware-libs/cairo/blob/9b8255bf4cc1fdf8e1423518efe2866626446524/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L137)):*
> ```XML
>         _data: &VariableId,
>     ) -> Self::Info {
>         unreachable!("Panics should have been stripped in a previous phase.")
> ```

I think None is good here too, and we might move the panic phase.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2386#-NPvMxlK5ZJGghuCyzKA:-NPvOCd8D9pd3TXAFfJw:b-isz2o3) ([raw file](https://github.com/starkware-libs/cairo/blob/9b8255bf4cc1fdf8e1423518efe2866626446524/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L90)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

or maybe dst_at_match
</blockquote></details>

what match?
dst_at_remapping?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2386#-NPvN6eqDEyLUGf6bwEG:-NPvOudO1aAw-EL_5ccb:bl1z9vu) ([raw file](https://github.com/starkware-libs/cairo/blob/9b8255bf4cc1fdf8e1423518efe2866626446524/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L90)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Consider renaming
</blockquote></details>

Why is it the remapping_until_match?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2386#-NPvN6eqDEyLUGf6bwEG:-NPvP-XXAMZIuRJLZ5Nq:bjzl4x7) ([raw file](https://github.com/starkware-libs/cairo/blob/9b8255bf4cc1fdf8e1423518efe2866626446524/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L90)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why is it the remapping_until_match?
</blockquote></details>

there could be 5 diffrent remappings before the match.

**Review by spapinistarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2386)* status: all files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2386#-NPvN6eqDEyLUGf6bwEG:-NPvPEWC1nx9vMQ-eerJ:b3aaybc) ([raw file](https://github.com/starkware-libs/cairo/blob/9b8255bf4cc1fdf8e1423518efe2866626446524/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L90)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

there could be 5 diffrent remappings before the match.
</blockquote></details>

Yeah, but how would you describe *this* remapping? From what I understand, you are aggregating the remapping to be the accumulated remapping from the current point until the "info" point - the point of the next match.
Can you describe it in another way?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2386)* status: 8 of 11 files reviewed, 3 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2386#-NPuzYT0A8GDOkZQmrf4:-NPv_QE5D73C1V5XtYGO:b-1se9pq) ([raw file](https://github.com/starkware-libs/cairo/blob/9b8255bf4cc1fdf8e1423518efe2866626446524/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L13)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix
</blockquote></details>

Not fixed yet, working on the comment.
___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2386#-NPvN6eqDEyLUGf6bwEG:-NPvTsnI2jAh1Ns_OI6B:bwnhart) ([raw file](https://github.com/starkware-libs/cairo/blob/9b8255bf4cc1fdf8e1423518efe2866626446524/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L90)):*
> aggregating
aggregated_remapping?
___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 99 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2386#-NPvNLH-A5HrEQdapjHX:-NPvXNaiCKPNjDwr-T_e:b-7rl0iw) ([raw file](https://github.com/starkware-libs/cairo/blob/9b8255bf4cc1fdf8e1423518efe2866626446524/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L99)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Doesn't this have a deafult empty impl at the trait?
</blockquote></details>

done?
___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 137 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2386#-NPvNabPDSfziJnMxi5x:-NPvTXCX69UsS5V-sXqX:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/9b8255bf4cc1fdf8e1423518efe2866626446524/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L137)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I think None is good here too, and we might move the panic phase.
</blockquote></details>

done

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2386)* status: 8 of 11 files reviewed, 3 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/test_data/option` line 10 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2386#-NPv0G9G0-NJMa4iqdSJ:-NPv_WqM9LLhcLP5wAwG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9b8255bf4cc1fdf8e1423518efe2866626446524/crates/cairo-lang-lowering/src/optimizations/test_data/option#L10)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe do something simpler instead? i don't think there's a need to rely on inlining:
```
extern fn get_option() -> Option<u16>;

fn foo() -> Option<u64> {
   let v = get_option();
   let v = match v {
        Option::Some(_) => Option::Some(1_u32),
        Option::Nome(_) => Option::Nome(()),
   };
   match v {
        Option::Some(_) => Option::Some(1_u64),
        Option::Nome(_) => Option::Nome(()),
   }
}
```
</blockquote></details>

Done.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2386)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/test_data/option` line 107 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2386#-NPw2f256fBYDmn0Idwf:-NPw2f256fBYDmn0Idwg:b-5ly7i6) ([raw file](https://github.com/starkware-libs/cairo/blob/5412bf4c4e36be6087fe6c0eccee55d038383529/crates/cairo-lang-lowering/src/optimizations/test_data/option#L107)):*
> ```
>   Goto(blk5, {v3 -> v4})
> 
> blk3:
> ```

Can I see this after your unreachable rmeoval optimization?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2386)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/test_data/option` line 107 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2386#-NPw2f256fBYDmn0Idwf:-NPw3ybZClm4Wtx5--Vs:b5pkqhx) ([raw file](https://github.com/starkware-libs/cairo/blob/5412bf4c4e36be6087fe6c0eccee55d038383529/crates/cairo-lang-lowering/src/optimizations/test_data/option#L107)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Can I see this after your unreachable rmeoval optimization?
</blockquote></details>

do you want to have both, before and after the unreachable removal? or just after?

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2386)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/test_data/option` line 107 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2386#-NPw2f256fBYDmn0Idwf:-NPw5AYw8TH587jRZpaj:bw0yezx) ([raw file](https://github.com/starkware-libs/cairo/blob/5412bf4c4e36be6087fe6c0eccee55d038383529/crates/cairo-lang-lowering/src/optimizations/test_data/option#L107)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

do you want to have both, before and after the unreachable removal? or just after?
</blockquote></details>

just after

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/test_data/option` line 107 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2386#-NPw2f256fBYDmn0Idwf:-NPw9Ctj9Pfl26i6CZ5Y:bo2i5f) ([raw file](https://github.com/starkware-libs/cairo/blob/5412bf4c4e36be6087fe6c0eccee55d038383529/crates/cairo-lang-lowering/src/optimizations/test_data/option#L107)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I mean, it's jjust rebasing this PR over main, isnt it?
</blockquote></details>

no, currently this test does not call topo_sort after the optimization.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2386)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/test_data/option` line 61 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2386#-NPw9Nuh8q50xOBWcIO6:-NPw9Nuh8q50xOBWcIO7:b-littu8) ([raw file](https://github.com/starkware-libs/cairo/blob/5412bf4c4e36be6087fe6c0eccee55d038383529/crates/cairo-lang-lowering/src/optimizations/test_data/option#L61)):*
> ```
> 
> blk4:
> Inputs: v5: core::integer::u16
> ```

I want to remove this input and move it to the match, does that make sense?



_Code quote:_
```
Inputs: v5: core::integer::u16
```

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2386)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/test_data/option` line 107 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2386#-NPw2f256fBYDmn0Idwf:-NPwDqOY5PqdqxAkh2AG:by7mfed) ([raw file](https://github.com/starkware-libs/cairo/blob/5412bf4c4e36be6087fe6c0eccee55d038383529/crates/cairo-lang-lowering/src/optimizations/test_data/option#L107)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

no, currently this test does not call topo_sort after the optimization.
</blockquote></details>

Can you?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2386)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/test_data/option` line 61 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2386#-NPw9Nuh8q50xOBWcIO6:-NPwHVZp2OAzk7hSsrjn:b2nhswy) ([raw file](https://github.com/starkware-libs/cairo/blob/5412bf4c4e36be6087fe6c0eccee55d038383529/crates/cairo-lang-lowering/src/optimizations/test_data/option#L61)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I want to remove this input and move it to the match, does that make sense?
</blockquote></details>

Yes

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2386)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/test_data/option` line 107 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2386#-NPw2f256fBYDmn0Idwf:-NPwPtlOCFcplt5JIyLa:b8ihu1s) ([raw file](https://github.com/starkware-libs/cairo/blob/5412bf4c4e36be6087fe6c0eccee55d038383529/crates/cairo-lang-lowering/src/optimizations/test_data/option#L107)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I can, but I think the test will be harder to review in this way.
</blockquote></details>

Ok, so add another test that lets me see we they are optimized out

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2386)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2386)* status: 8 of 11 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/test_data/option` line 107 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2386#-NPw2f256fBYDmn0Idwf:-NPwgwR6CmsLGW7zYzPn:bsuskg7) ([raw file](https://github.com/starkware-libs/cairo/blob/5412bf4c4e36be6087fe6c0eccee55d038383529/crates/cairo-lang-lowering/src/optimizations/test_data/option#L107)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Ok, so add another test that lets me see we they are optimized out
</blockquote></details>

Changed the test to do both match_optimize + topo sort.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2386#-:-NPwhfk8CUnSbucoCQtH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2386#-:-NPyGyBS3fkiMsJGEUdt:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
