### PR TITLE
Even better highlighting

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3755)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3744** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3744" target="_blank">Graphite</a> 
    * **PR #3745** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3745" target="_blank">Graphite</a> 
      * **PR #3746** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3746" target="_blank">Graphite</a> 
        * **PR #3747** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3747" target="_blank">Graphite</a> 
          * **PR #3748** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3748" target="_blank">Graphite</a> 
            * **PR #3749** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3749" target="_blank">Graphite</a> 
              * **PR #3750** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3750" target="_blank">Graphite</a> 
                * **PR #3751** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3751" target="_blank">Graphite</a> 
                  * **PR #3752** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3752" target="_blank">Graphite</a> 
                    * **PR #3753** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3753" target="_blank">Graphite</a> 
                      * **PR #3754** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3754" target="_blank">Graphite</a> 
                        * **PR #3755** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3755" target="_blank">Graphite</a>  👈
                          * **PR #3756** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3756" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/3755?utm_source=stack-comment).

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3744** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3744" target="_blank">Graphite</a> 
    * **PR #3745** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3745" target="_blank">Graphite</a> 
      * **PR #3746** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3746" target="_blank">Graphite</a> 
        * **PR #3747** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3747" target="_blank">Graphite</a> 
          * **PR #3748** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3748" target="_blank">Graphite</a> 
            * **PR #3749** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3749" target="_blank">Graphite</a> 
              * **PR #3750** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3750" target="_blank">Graphite</a> 
                * **PR #3751** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3751" target="_blank">Graphite</a> 
                  * **PR #3752** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3752" target="_blank">Graphite</a> 
                    * **PR #3753** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3753" target="_blank">Graphite</a> 
                      * **PR #3754** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3754" target="_blank">Graphite</a> 
                        * **PR #3755** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3755" target="_blank">Graphite</a>  👈
                          * **PR #3756** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3756" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/3755?utm_source=stack-comment).

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3755)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-language-server/src/semantic_highlighting/token_kind.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3755#-NaBRN9J--eGlxwQE5sI:-NaBRN9J--eGlxwQE5sJ:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/42d862beaf6f9e726266169e4b84315be6c078ce/crates/cairo-lang-language-server/src/semantic_highlighting/token_kind.rs#L90)):*
> ```XML
> 
>             match node.kind(syntax_db) {
>                 // SyntaxKind::ExprPath if node.parent().map(|x|x.kind(syntax_db)) ==
> ```

?



_Code quote:_
```XML
                // SyntaxKind::ExprPath if node.parent().map(|x|x.kind(syntax_db)) ==
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3755#-:-NaCTqz94acwCA7Du8Zz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
