### PR TITLE
Add macro insert_value_to_cellref and use it.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1688)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1688)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1688#-NLGGdr3B0a48Sgj9Xbe:-NLGGdr48jQMLF8IHiRv:b-brv37o) (no related file):*
TODO: Change target branch.

___

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1688#-:-NLGHK185j1y7R9TzYPM:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-casm/src/run.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1688#-NLGHCSEBkBgXKMrH0t9:-NLGHCSFDP-BhuP6LV37:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/cc7484c6a1edb6d1a3be7e704b44c7d244eec881/crates/cairo-lang-casm/src/run.rs#L106)):*
> ```XML
> }
> 
> macro_rules! insert_value_to_cellref {
> ```

doc



_Code quote:_
```XML
macro_rules! insert_value_to_cellref {
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1688)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1688)* status: all files reviewed, 1 unresolved discussion

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1688)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
