### PR TITLE
Add remaining `assert_xx!` comparison test macros

### PR DESCRIPTION
**Pull request by iamvukasin**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4936)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4936)* status: all files reviewed, 1 unresolved discussion (waiting on @iamvukasin)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4936#-Nprt4y0B2Z_UdNAz7Zm:-Nprt4y0B2Z_UdNAz7Zn:b1dmduz) (no related file):*
do you know why these don't exist in rust - and why is our situation different?

___

**Comment by iamvukasin** [comment]
TBH initially I didn't check if and why Rust didn't support all of them, but I did now. As they [found out](https://github.com/rust-lang/rfcs/pull/1662#issuecomment-235427394), these asserts are not used frequently. I don't have any data to prove if Cairo ones would or wouldn't be used more, but based on my experience of writing Cairo tests daily, they can be useful, especially since generic `assert` and `assert!` are not that helpful. Many of my tests are based on balance/timestamp checkings and it is helpful when you know why your assert is failing (and which values are being checked).

In an ideal world, this could be a standalone helper library like [`all_asserts`](https://docs.rs/all_asserts/latest/all_asserts/index.html). I wouldn't bother opening a PR for this if Cairo had a straightforward way of defining custom macros.

**Review by orizi — CHANGES_REQUESTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4936#-:-NpsxXFH3Kd7oEXgV_y4:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @iamvukasin)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4936#-NpsxXd08BoibD-Qj2TU:-NpsxXd08BoibD-Qj2TV:b-uuj1x0) (no related file):*
@gilbens-starkware for 2nd eye.

___

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4936)* status: all files reviewed, 1 unresolved discussion (waiting on @iamvukasin)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4936#-:-Npt0TQa6iD2FowFMBEq:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @iamvukasin)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4936)* status: all files reviewed, 1 unresolved discussion (waiting on @iamvukasin)

___
*[`corelib/src/test/testing_test.cairo` line 84 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4936#-NptAHG85S52dPb1s0if:-NptAHG85S52dPb1s0ig:b-hjamob) ([raw file](https://github.com/starkware-libs/cairo/blob/55caf96654859d2fa72f5f86ac20f7af01988700/corelib/src/test/testing_test.cairo#L84)):*
> ```Cairo
>     assert_ge!(2, 1);
>     assert_ge!(2, 2);
> }
> ```

add types - as felt252s aren't ordered.



_Code quote:_
```Cairo
#[test]
fn test_assert_lt_with_description() {
    assert_lt!(1, 2, "Description");
}

#[test]
fn test_assert_lt_no_description() {
    assert_lt!(1, 2);
}

#[test]
fn test_assert_le_with_description() {
    assert_le!(1, 2, "Description");
    assert_le!(1, 1, "Description");
}

#[test]
fn test_assert_le_no_description() {
    assert_le!(1, 2);
    assert_le!(1, 1);
}

#[test]
fn test_assert_gt_with_description() {
    assert_gt!(2, 1, "Description");
}

#[test]
fn test_assert_gt_no_description() {
    assert_gt!(2, 1);
}

#[test]
fn test_assert_ge_with_description() {
    assert_ge!(2, 1, "Description");
    assert_ge!(2, 2, "Description");
}

#[test]
fn test_assert_ge_no_description() {
    assert_ge!(2, 1);
    assert_ge!(2, 2);
}
```

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4936)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @iamvukasin)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4936)* status: all files reviewed, 1 unresolved discussion (waiting on @iamvukasin)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4936#-NqNUtbm-thAr3qD6a1u:-NqNUtbnCypgcyuoohlX:b-ompbi4) (no related file):*
Please rebase and make sure tests pass, these didn't pass since we approved.

___

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4936)* status: all files reviewed, 2 unresolved discussions (waiting on @iamvukasin)

___
*[`corelib/src/test/testing_test.cairo` line 43 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4936#-NqNX0xGB4o9hVTmgTRt:-NqNX0xHD9aiQyWUUPeM:b-sz0afd) ([raw file](https://github.com/starkware-libs/cairo/blob/2d5fe6bc7f1e60d9c9bb524a8379cc8e2ef21332/corelib/src/test/testing_test.cairo#L43)):*
> ```Cairo
> 
> #[test]
> fn test_assert_lt_with_description() {
> ```

It is possibly due to the test being u256, just change to u8 and check the tests are fine.

**Comment by iamvukasin** [comment]
Done. Had to decrease `available_gas` as it was failing even with `u8`.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4936#-:-NqXurWzCu03taqaKSr6:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @iamvukasin)

**Pull request merged**
