### PR TITLE
Added support for `Self::` in trait and impl contexts

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5218)

### CODE REVIEW

**Comment by yuvalsw** [comment]
change target branch

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5218)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 315 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5218#-NsTmN_mExmkQZkGgQsG:-NsTmN_mExmkQZkGgQsH:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/c2240de71cee178d530bbcdd253d64b9580d754a/crates/cairo-lang-semantic/src/resolve/mod.rs#L315)):*
> ```XML
>         }
> 
>         // if let Some(base_module) = self.handle_self_segment(diagnostics, segments) {
> ```

.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5218)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 315 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5218#-NsTmN_mExmkQZkGgQsG:-NsgD8HzAyPZvArOkfaO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c2240de71cee178d530bbcdd253d64b9580d754a/crates/cairo-lang-semantic/src/resolve/mod.rs#L315)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5218)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 916 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5218#-NsgOmRP1vr0VZtWzICj:-NsgOmRP1vr0VZtWzICk:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2c852bfc8e84582c363fd18e97bc552210b954fb/crates/cairo-lang-semantic/src/items/tests/trait#L916)):*
> ```
>       Self::foo2()
>    }
>    fn foo2() -> u32 { 3 }
> ```





_Suggestion:_
```
   }
   fn foo2() -> u16 { 3 }
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5218#-:-Nsj5xr-7u02eZpnlD_s:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5218#-:-NsmP3Sx6dZwhOwhHbau:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
