### PR TITLE
Added print for ByteArray

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4294)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r1, 3 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4294)* status: 3 of 19 files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/debug.cairo` line 132 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4294#-NhRnNSd8tCJFDqhkab4:-NhRnNSd8tCJFDqhkab5:bn7pzf7) ([raw file](https://github.com/starkware-libs/cairo/blob/7750202f75614d4daad88e5a67adf44adb2f3050/corelib/src/debug.cairo#L132)):*
> ```Cairo
>         print(serialized)
>     }
> }
> ```

i think this should just be an unrelated function.



_Code quote:_
```Cairo
impl ByteArrayPrintImpl of PrintTrait<@ByteArray> {
    fn print(self: @ByteArray) {
        let mut serialized = array![byte_array::BYTE_ARRAY_MAGIC];
        self.serialize(ref serialized);
        print(serialized)
    }
}
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4294)* status: 2 of 19 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/debug.cairo` line 132 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4294#-NhRnNSd8tCJFDqhkab4:-NhSHhcS1Vwvapp-_aOr:b-2colb) ([raw file](https://github.com/starkware-libs/cairo/blob/7750202f75614d4daad88e5a67adf44adb2f3050/corelib/src/debug.cairo#L132)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i think this should just be an unrelated function.
</blockquote></details>

I don't mind, but all other prints so far has x.print().
Removing for now as it's easier to add than to remove.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4294)* status: 3 of 19 files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`-- commits` line 8 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4294#-NhVCb1rEBJ0qsZ6fKTh):*
leave only one commit.



_Code quote:_
```
New commits in r2 on 10/23/2023 at 4:45 PM by ArielElp:
- df22d08: add verify_signature function for secp curves (#4120)

New commits in r3 on 10/23/2023 at 4:45 PM by ilyalesokhin-starkware:
- b193746: Enable byte_array_test. (#4286)

New commits in r4 on 10/23/2023 at 4:55 PM:
- 99fadc3: Fixed `as_cairo_short_string` (#4293)
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4294)* status: 3 of 19 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`-- commits` line 8 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4294#-NhVCb1rEBJ0qsZ6fKTh):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

leave only one commit.
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 4 of 11 files at r5, 1 of 2 files at r6, 11 of 11 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4294)* status: 18 of 19 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-utils/src/byte_array.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4294#-NhRmT93349Q23-z4KsI:-NhVxFEr-beXVaFJeM3g:b-ljynnc) ([raw file](https://github.com/starkware-libs/cairo/blob/7750202f75614d4daad88e5a67adf44adb2f3050/crates/cairo-lang-utils/src/byte_array.rs#L1)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Is this the right place for this? Any suggestion for a better place?
</blockquote></details>

Maybe leave it in the original, since it only has actual runtime implications for the panic, here it is just use as a helper for debug purposes.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4294)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`corelib/src/byte_array.cairo` line 14 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4294#-Nh_o40l3zDKpHvqDf6p:-Nh_nXJC80UbCbuf8J2m:b9qnymr) ([raw file](https://github.com/starkware-libs/cairo/blob/d7b3acf17c31dfadfaa81965c32861340819fa2a/corelib/src/byte_array.cairo#L14)):*
> ```Cairo
> use zeroable::NonZeroIntoImpl;
> 
> const BYTE_ARRAY_MAGIC: felt252 = 0x46a6158a16a947e5916b2a2ca68501a45e93d7110e81aa2d6438b1c57c879a3;
> ```

add a doc describing what is this magic for.



_Code quote:_
```Cairo
BYTE_ARRAY_MAGIC
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4294)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/byte_array.cairo` line 14 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4294#-Nh_o40l3zDKpHvqDf6p:-Nhan4Xf3l1wJDFJqD8d:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d7b3acf17c31dfadfaa81965c32861340819fa2a/corelib/src/byte_array.cairo#L14)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add a doc describing what is this magic for.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4294#-:-Nhat5Z9-WdcDxFqFYyh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
