### PR TITLE
Added support for u128 and bool storage vars.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1630)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/plugin.rs` line 421 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1630#-NKrmH9m0GNW1QOsnVGm:-NKrmH9m0GNW1QOsnVGn:b-pb44rm) ([raw file](https://github.com/starkware-libs/cairo/blob/3a502911a36a2418e57fa4ea4d3724c6070d0e71/crates/cairo-lang-starknet/src/plugin.rs#L421)):*
> ```XML
>                     }}
>                     fn write(value: {type_name}) {{
>                         let value = {convert_from};
> ```

inline



_Code quote:_
```XML
let value = {convert_from};
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1630)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 404 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1630#-NKrmT7lECjOTZV5ZLVB:-NKrmT7lECjOTZV5ZLVC:b-7k2443) ([raw file](https://github.com/starkware-libs/cairo/blob/3a502911a36a2418e57fa4ea4d3724c6070d0e71/crates/cairo-lang-starknet/src/plugin.rs#L404)):*
> ```XML
>             formatdoc!(
>                 "
>                 mod {name} {{
> ```

revet



_Code quote:_
```XML
{name}
```
___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 405 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1630#-NKrmadL9x450omYdKjB:-NKrmadL9x450omYdKjC:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/3a502911a36a2418e57fa4ea4d3724c6070d0e71/crates/cairo-lang-starknet/src/plugin.rs#L405)):*
> ```XML
>                 "
>                 mod {name} {{
>                     fn read() -> {type_name} {{
> ```





_Suggestion:_
```XML
 $type_name$
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1630)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 377 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1630#-NKs0C492v3iWYs6R5CS:-NKs4xAQ83yKPWyawGJt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b87e111cbc6703b5b6c336b30118fec39e59df3b/crates/cairo-lang-starknet/src/plugin.rs#L377)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

move inside handle_simple_storage_var
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 380 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1630#-NKs-fKF4Vx4ez7E8NCS:-NKs4evS2S2Bds7rcw--:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b87e111cbc6703b5b6c336b30118fec39e59df3b/crates/cairo-lang-starknet/src/plugin.rs#L380)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Inline.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 399 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1630#-NKs08Q10Z1H9zfFBvUY:-NKs4xqK8Mff8W3_78eG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b87e111cbc6703b5b6c336b30118fec39e59df3b/crates/cairo-lang-starknet/src/plugin.rs#L399)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

move inside handle_simple_storage_var
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 6 files at r2, 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1630#-:-NKs5L8g6SuSHAsw-dMb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
