### PR TITLE
Parser support for while expr.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4659)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 12 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4659)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1617 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4659#-Nm_mnjm4rTTbyKqOyBt:-Nm_mnjm4rTTbyKqOyBu:b-bem9l2) ([raw file](https://github.com/starkware-libs/cairo/blob/cdb37f24422a8618e312cb85f41bb636de530990/crates/cairo-lang-parser/src/parser.rs#L1617)):*
> ```XML
> 
>     /// Assumes the current token is `While`.
>     /// Expected pattern: `loop expr <block>`.
> ```

this is still a loop.



_Code quote:_
```XML
    /// Assumes the current token is `While`.
    /// Expected pattern: `loop expr <block>`.
```
___
*[`crates/cairo-lang-syntax-codegen/src/cairo_spec.rs` line 302 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4659#-Nm_nMiQ9iVGYBkSAZDF:-Nm_nMiQ9iVGYBkSAZDG:b-kinq1g) ([raw file](https://github.com/starkware-libs/cairo/blob/cdb37f24422a8618e312cb85f41bb636de530990/crates/cairo-lang-syntax-codegen/src/cairo_spec.rs#L302)):*
> ```XML
>         .node("Return")
>         .node("Break")
>         .node("While")
> ```

why is while not the same as loop?
shouldn't it be a block type?



_Code quote:_
```XML
        .node("While")
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-syntax-codegen/src/cairo_spec.rs` line 302 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4659#-Nm_nMiQ9iVGYBkSAZDF:-Nm_r-Q00TSMtW7YGieO:bxqby0q) ([raw file](https://github.com/starkware-libs/cairo/blob/cdb37f24422a8618e312cb85f41bb636de530990/crates/cairo-lang-syntax-codegen/src/cairo_spec.rs#L302)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why is while not the same as loop?
shouldn't it be a block type?
</blockquote></details>

a loop is an Expr while `While`is a statement.
See:
https://doc.rust-lang.org/error_codes/E0571.html

What is a block type?

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 10 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4659)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 162 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4659#-Nmfh8_U-jFSPJsqBluY:-Nmfh8_U-jFSPJsqBluZ:btdrng1) ([raw file](https://github.com/starkware-libs/cairo/blob/f1eea85e1bc75fd3473c7570fdbd8fb04aa1feb8/crates/cairo-lang-lowering/src/lower/mod.rs#L162)):*
> ```XML
> // TODO(spapini): Unite with `lower_function`.
> pub fn lower_loop_function(
>     encapsulating_ctx: &mut EncapsulatingLoweringContext<'_>,
> ```

are the changes here related to the PR?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-parser/src/parser.rs` line 1617 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4659#-Nm_mnjm4rTTbyKqOyBt:-Nmfj_Tv0UexeE5mQ9bb:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/cdb37f24422a8618e312cb85f41bb636de530990/crates/cairo-lang-parser/src/parser.rs#L1617)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is still a loop.
</blockquote></details>

done

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 13 files at r1, 6 of 11 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4659)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 162 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4659#-Nmfh8_U-jFSPJsqBluY:-NmfjmX455xV8lIq_jcW:b-81taoq) ([raw file](https://github.com/starkware-libs/cairo/blob/f1eea85e1bc75fd3473c7570fdbd8fb04aa1feb8/crates/cairo-lang-lowering/src/lower/mod.rs#L162)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

are the changes here related to the PR?
</blockquote></details>

reverted.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4659#-:-Nmfk2Fz2z-iyOVOlNIZ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
