### PR TITLE
Renamed SyscallPtr -> System

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1304)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1304)* status: 1 of 15 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/casm/src/hints/mod.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1304#-NJ5jr__8rEzzmNhQEY2:-NJ5jr__8rEzzmNhQEY3:bo33ce9) ([raw file](https://github.com/starkware-libs/cairo/blob/bca9b8b54b265793b27702a5282d0334035f4d60/crates/casm/src/hints/mod.rs#L130)):*
> ```XML
>             Hint::DictSquashHints { hint_index } => dict_squash::fmt_hint_by_index(f, *hint_index)?,
>             Hint::SystemCall { system } => {
>                 write!(f, "syscall_handler.syscall(segments=segments, system={})", system)?
> ```

I'm not sure we want to change it in the hint.



_Code quote:_
```XML
 system={}
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1304)* status: 1 of 15 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/casm/src/hints/mod.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1304#-NJ5jr__8rEzzmNhQEY2:-NJ6AUjlC7cTC4sBFkMW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bca9b8b54b265793b27702a5282d0334035f4d60/crates/casm/src/hints/mod.rs#L130)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I'm not sure we want to change it in the hint.
</blockquote></details>

Done.



_Code quote:_
```XML
syscall_ptr
```

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 12 of 15 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1304#-:-NJAdu8u6lM5DsVngDrX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 6 of 7 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1304)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @yuvalsw)

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 6 of 7 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1304)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1304)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
