### PR TITLE
Add storage vec indexing.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5992)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5992)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`corelib/src/starknet/storage.cairo` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5992#-O1QPfJI7Nk-w6PDVX8Z:-O1QPfJI7Nk-w6PDVX8_:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2eb254e4cc39703ec5763707bbf6a9f71cbf7aca/corelib/src/starknet/storage.cairo#L12)):*
> ```Cairo
>     Vec, VecTrait, MutableVecTrait, VecIndexView, MutableVecIndexView, PathableVecIndexView,
>     PathableMutableVecIndexView
> };
> ```





_Suggestion:_
```Cairo
pub use vec::{Vec, VecTrait, MutableVecTrait};
```
___
*[`corelib/src/starknet/storage/vec.cairo` line 175 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5992#-O1QPZ3Q58pyheFU36xN:-O1QPZ3Q58pyheFU36xO:be9csmk) ([raw file](https://github.com/starkware-libs/cairo/blob/2eb254e4cc39703ec5763707bbf6a9f71cbf7aca/corelib/src/starknet/storage/vec.cairo#L175)):*
> ```Cairo
>         (*self).as_path().at(index)
>     }
> }
> ```

if the issue is this not being found in context - 
you can probably just depend on the trait supplying the `at` function.



_Suggestion:_
```Cairo
impl VecIndexView<T> of core::ops::IndexView<StoragePath<Vec<T>>, u64> {
    type Target = StoragePath<T>;
    fn index(self: @StoragePath<Vec<T>>, index: u64) -> Self::Target {
        (*self).at(index)
    }
}

impl MutableVecIndexView<T> of core::ops::IndexView<StoragePath<Mutable<Vec<T>>>, u64> {
    type Target = StoragePath<Mutable<T>>;
    fn index(self: @StoragePath<Mutable<Vec<T>>>, index: u64) -> Self::Target {
        (*self).at(index)
    }
}

impl PathableVecIndexView<
    T,
    +Copy<T>,
    +Drop<T>,
    impl PathImpl: StorageAsPath<T>,
    impl VecTraitImpl: VecTrait<StoragePath<PathImpl::Value>>
> of core::ops::IndexView<T, u64> {
    type Target = StoragePath<VecTraitImpl::ElementType>;
    fn index(self: @T, index: u64) -> Self::Target {
        (*self).as_path().at(index)
    }
}

impl PathableMutableVecIndexView<
    T,
    +Drop<T>,
    +Copy<T>,
    impl PathImpl: StorageAsPath<T>,
    impl VecTraitImpl: MutableVecTrait<StoragePath<PathImpl::Value>>
> of core::ops::IndexView<T, u64> {
    type Target = StoragePath<Mutable<VecTraitImpl::ElementType>>;
    fn index(self: @T, index: u64) -> Self::Target {
        (*self).as_path().at(index)
    }
}
```
___
*[`crates/cairo-lang-starknet/cairo_level_tests/storage_access.cairo` line 155 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5992#-O1QQCg00iQewxUmtqff:-O1QQCg1134RwcZkJDD8:b-jjbga) ([raw file](https://github.com/starkware-libs/cairo/blob/2eb254e4cc39703ec5763707bbf6a9f71cbf7aca/crates/cairo-lang-starknet/cairo_level_tests/storage_access.cairo#L155)):*
> ```Cairo
>     #[external(v0)]
>     pub fn get_vec_element(self: @ContractState, index: u64) -> u32 {
>         self.vecs.vec[index].read()
> ```

continuing the question - why was this found?
if due to the `use` in `storage.cairo` so just add the non-pub `impl` there.



_Code quote:_
```Cairo
    pub fn get_vec_element(self: @ContractState, index: u64) -> u32 {
        self.vecs.vec[index].read()
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5992)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/starknet/storage.cairo` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5992#-O1QPfJI7Nk-w6PDVX8Z:-O1QbcXI32_QvSlYw8Bt:bq0zy6s) ([raw file](https://github.com/starkware-libs/cairo/blob/2eb254e4cc39703ec5763707bbf6a9f71cbf7aca/corelib/src/starknet/storage.cairo#L12)):*
> ```Cairo
>     Vec, VecTrait, MutableVecTrait, VecIndexView, MutableVecIndexView, PathableVecIndexView,
>     PathableMutableVecIndexView
> };
> ```

Done.
Added non-pub.
___
*[`corelib/src/starknet/storage/vec.cairo` line 175 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5992#-O1QPZ3Q58pyheFU36xN:-O1Qbg6z0AYuCKuKekQX:b-epuorh) ([raw file](https://github.com/starkware-libs/cairo/blob/2eb254e4cc39703ec5763707bbf6a9f71cbf7aca/corelib/src/starknet/storage/vec.cairo#L175)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

if the issue is this not being found in context - 
you can probably just depend on the trait supplying the `at` function.
</blockquote></details>

Changed to `pub(crate)`
___
*[`crates/cairo-lang-starknet/cairo_level_tests/storage_access.cairo` line 155 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5992#-O1QQCg00iQewxUmtqff:-O1QbkHY3vQCDiq6w4EI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2eb254e4cc39703ec5763707bbf6a9f71cbf7aca/crates/cairo-lang-starknet/cairo_level_tests/storage_access.cairo#L155)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

continuing the question - why was this found?
if due to the `use` in `storage.cairo` so just add the non-pub `impl` there.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5992)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`corelib/src/starknet/storage.cairo` line 9 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5992#-O1QmE_y0JMyG_AGrSgy:-O1QmE_y0JMyG_AGrSgz:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7fc7b22cb5ae1fd84d007682a7d1d0afcd4a1986/corelib/src/starknet/storage.cairo#L9)):*
> ```Cairo
> 
> mod vec;
> pub use vec::{Vec, VecTrait, MutableVecTrait,};
> ```





_Suggestion:_
```Cairo
pub use vec::{Vec, VecTrait, MutableVecTrait};
```
___
*[`corelib/src/starknet/storage/vec.cairo` line 175 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5992#-O1QPZ3Q58pyheFU36xN:-O1QmNgKCKMT-qvj_uus:b-5fwmxs) ([raw file](https://github.com/starkware-libs/cairo/blob/2eb254e4cc39703ec5763707bbf6a9f71cbf7aca/corelib/src/starknet/storage/vec.cairo#L175)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Changed to `pub(crate)`
</blockquote></details>

usual pub is fine - as the module isn't pub.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5992)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/starknet/storage.cairo` line 9 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5992#-O1QmE_y0JMyG_AGrSgy:-O1QnFHI0SjK5se5szhg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7fc7b22cb5ae1fd84d007682a7d1d0afcd4a1986/corelib/src/starknet/storage.cairo#L9)):*
> ```Cairo
> 
> mod vec;
> pub use vec::{Vec, VecTrait, MutableVecTrait,};
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5992#-:-O1Qr06Q4v136ZDbODI0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
