### PR TITLE
Handlng zero sized locals.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4414)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4414#-NjaLc9O-pKzKWSCfBlo:-NjaLc9O-pKzKWSCfBlp:b-75ywm7) ([raw file](https://github.com/starkware-libs/cairo/blob/f08931ec92726f87aa4d1b95fc9d6379fa1e6eda/crates/cairo-lang-sierra-generator/src/local_variables.rs#L59)):*
> ```XML
>                 let info = db.get_type_info(db.get_concrete_type_id(var.ty).ok()?).ok()?;
>                 if info.zero_sized { Some(id) } else { None }
>             })
> ```

why is this needed?



_Code quote:_
```XML
            // All empty variables are not ap based.
            lowered_function.variables.iter().filter_map(|(id, var)| {
                let info = db.get_type_info(db.get_concrete_type_id(var.ty).ok()?).ok()?;
                if info.zero_sized { Some(id) } else { None }
            })
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 297 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4414#-NjaLfr8Cxdx_HT4NC49:-NjaLfr8Cxdx_HT4NC4A:b-vm75yi) ([raw file](https://github.com/starkware-libs/cairo/blob/f08931ec92726f87aa4d1b95fc9d6379fa1e6eda/crates/cairo-lang-sierra-generator/src/local_variables.rs#L297)):*
> ```XML
>                 | OutputVarReferenceInfo::NewLocalVar
>                 | OutputVarReferenceInfo::ZeroSized => {
>                     self.non_ap_based.insert(*var);
> ```

does this miss things?



_Code quote:_
```XML
                | OutputVarReferenceInfo::ZeroSized => {
                    self.non_ap_based.insert(*var);
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4414)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4414#-NjaLc9O-pKzKWSCfBlo:-NjaMYmG3AgyYyApvRUJ:b-710glg) ([raw file](https://github.com/starkware-libs/cairo/blob/f08931ec92726f87aa4d1b95fc9d6379fa1e6eda/crates/cairo-lang-sierra-generator/src/local_variables.rs#L59)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why is this needed?
</blockquote></details>

since we need all  zero sized variables to be dropped.
a variable merged from  a branch where it is used, is stored in one branch and not dropped in the other.
The issue test crashes.
___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 297 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4414#-NjaLfr8Cxdx_HT4NC49:-NjaMVfrAZQ4FTfielny:b-jotlo7) ([raw file](https://github.com/starkware-libs/cairo/blob/f08931ec92726f87aa4d1b95fc9d6379fa1e6eda/crates/cairo-lang-sierra-generator/src/local_variables.rs#L297)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

does this miss things?
</blockquote></details>

yes - since merge does not catch it.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4414#-NjaLc9O-pKzKWSCfBlo:-NjaNoff3qH00N_mszqY:bif7h46) ([raw file](https://github.com/starkware-libs/cairo/blob/f08931ec92726f87aa4d1b95fc9d6379fa1e6eda/crates/cairo-lang-sierra-generator/src/local_variables.rs#L59)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

since we need all  zero sized variables to be dropped.
a variable merged from  a branch where it is used, is stored in one branch and not dropped in the other.
The issue test crashes.
</blockquote></details>

why do we need all zero sized variables to be dropped?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 297 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4414#-NjaLfr8Cxdx_HT4NC49:-NjaO78aAJ3tBQ96K3NR:bhd1sh3) ([raw file](https://github.com/starkware-libs/cairo/blob/f08931ec92726f87aa4d1b95fc9d6379fa1e6eda/crates/cairo-lang-sierra-generator/src/local_variables.rs#L297)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

yes - since merge does not catch it.
</blockquote></details>

does not catch what?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4414)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4414#-NjaLc9O-pKzKWSCfBlo:-Njad2MSDNblbPxnxLxi:b-1c6alc) ([raw file](https://github.com/starkware-libs/cairo/blob/a025eb15386d3170da2b319628d145e9ee8ef196/crates/cairo-lang-sierra-generator/src/local_variables.rs#L59)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why do we need all zero sized variables to be dropped?
</blockquote></details>

since we need all variables to be dropped.
zero sized variables are treated as temporary variables when merged (all other merged introduced variables ARE always tempvars at the end of the stack).
Therefore 0 sized require special handling.
___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 297 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4414#-NjaLfr8Cxdx_HT4NC49:-NjadMB_8j0wa1Q4Idk0:b81qr8k) ([raw file](https://github.com/starkware-libs/cairo/blob/a025eb15386d3170da2b319628d145e9ee8ef196/crates/cairo-lang-sierra-generator/src/local_variables.rs#L297)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

does not catch what?
</blockquote></details>

merge assumes all is temp var - zero sized included.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 297 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4414#-NjaLfr8Cxdx_HT4NC49:-NjayZbT124MMHt4FJD5:bmvqgnw) ([raw file](https://github.com/starkware-libs/cairo/blob/a025eb15386d3170da2b319628d145e9ee8ef196/crates/cairo-lang-sierra-generator/src/local_variables.rs#L297)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

merge assumes all is temp var - zero sized included.
</blockquote></details>

wdyt about only hanlind remapped variables?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4414)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 297 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4414#-NjaLfr8Cxdx_HT4NC49:-NjayyyfE_Oy5RZsdCU6:b-6dyjr1) ([raw file](https://github.com/starkware-libs/cairo/blob/a025eb15386d3170da2b319628d145e9ee8ef196/crates/cairo-lang-sierra-generator/src/local_variables.rs#L297)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

wdyt about only hanlind remapped variables?
</blockquote></details>

https://reviewable.io/reviews/starkware-libs/cairo/4418

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4414)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 297 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4414#-NjaLfr8Cxdx_HT4NC49:-NjbAgfo6wm0TlIvGKhc:bcm22ak) ([raw file](https://github.com/starkware-libs/cairo/blob/a025eb15386d3170da2b319628d145e9ee8ef196/crates/cairo-lang-sierra-generator/src/local_variables.rs#L297)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

https://reviewable.io/reviews/starkware-libs/cairo/4418
</blockquote></details>

I'm also ok with you approach, but I think it is less in the spirt of rest of the code.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4414)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 297 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4414#-NjaLfr8Cxdx_HT4NC49:-NjbKJcz4WnxojpXGi1H:b-reb5we) ([raw file](https://github.com/starkware-libs/cairo/blob/a025eb15386d3170da2b319628d145e9ee8ef196/crates/cairo-lang-sierra-generator/src/local_variables.rs#L297)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I'm also ok with you approach, but I think it is less in the spirt of rest of the code.
</blockquote></details>

i'm fine with it, i think the code is built to handle logically temporary values, so any way to ignore them is fine with me.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 297 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4414#-NjaLfr8Cxdx_HT4NC49:-NjbNB6y47xXCrTrOvzq:b-cey13n) ([raw file](https://github.com/starkware-libs/cairo/blob/a025eb15386d3170da2b319628d145e9ee8ef196/crates/cairo-lang-sierra-generator/src/local_variables.rs#L297)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i'm fine with it, i think the code is built to handle logically temporary values, so any way to ignore them is fine with me.
</blockquote></details>

what do you mean by "logically temporary values"?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4414)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 297 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4414#-NjaLfr8Cxdx_HT4NC49:-NjbNg4b2t-SxXYD84Im:blyj1nn) ([raw file](https://github.com/starkware-libs/cairo/blob/a025eb15386d3170da2b319628d145e9ee8ef196/crates/cairo-lang-sierra-generator/src/local_variables.rs#L297)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what do you mean by "logically temporary values"?
</blockquote></details>

i mean to exclude empty vars.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4414#-:-NjbQSzi2xTyVr8cgVwU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4414#-:-NjbSLuaBytc6XlfOQnm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4414)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
