### PR TITLE
Remove le libfuncs

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2992)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2991** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2991" target="_blank">Graphite</a> 
    * **PR #2992** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2992" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2992?utm_source=stack-comment).

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 5 of 15 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2992)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2992)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`tests/e2e_test_data/libfuncs/u32` line 205 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2992#-NULt0jR4MBCRng-loBA:-NULt0jR4MBCRng-loBB:b-o0pson) ([raw file](https://github.com/starkware-libs/cairo/blob/95d89923c25865a3ddca0c3f83a8596f7880cde2/tests/e2e_test_data/libfuncs/u32#L205)):*
> ```
> //! > cairo
> fn foo(a: u32, b: u32) -> bool {
>     a <= b
> ```

Addd the missing cairo test `assert(1_u8 <= 4_u8, '1 <= 4');`

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2992#-:-NUM_nLp7LmYYwbNAKBN:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @liorgold2)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2992)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`corelib/src/test/integer_test.cairo` line 23 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2992#-NUM_wlp3-lUM_YBFodT:-NUM_wlqCsshHkMmLYZW:b-nm8hay) ([raw file](https://github.com/starkware-libs/cairo/blob/302077744bc89d5166426eb59392b2f1b361458c/corelib/src/test/integer_test.cairo#L23)):*
> ```Cairo
>     assert(!(4_u8 < 4_u8), '!(4 < 4)');
>     assert(4_u8 <= 4_u8, '4 <= 4');
>     assert(1_u8 <= 4_u8, '1 <= 4');
> ```

This line exists above (if I'm not mistaken).

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 12 files at r2, 2 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2992)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`corelib/src/integer.cairo` line 208 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2992#-NUMao6jCjmM1XBG-Vkf:-NUMao6jCjmM1XBG-Vkg:b-jk7u05) ([raw file](https://github.com/starkware-libs/cairo/blob/302077744bc89d5166426eb59392b2f1b361458c/corelib/src/integer.cairo#L208)):*
> ```Cairo
>     #[inline(always)]
>     fn ge(lhs: u128, rhs: u128) -> bool {
>         u128_overflowing_sub(lhs, rhs).into_is_ok()
> ```

Consider (not sure if it's better)



_Suggestion:_
```Cairo
rhs <= lhs
```

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 2 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2992)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 5 of 15 files at r1, 1 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2992)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2992)* status: 13 of 19 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @liorgold2)

___
*[`corelib/src/integer.cairo` line 208 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2992#-NUMao6jCjmM1XBG-Vkf:-NUMiTv59722LdqZbcLZ:bln3stx) ([raw file](https://github.com/starkware-libs/cairo/blob/302077744bc89d5166426eb59392b2f1b361458c/corelib/src/integer.cairo#L208)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Consider (not sure if it's better)
</blockquote></details>

I think this way is more symmetric.
___
*[`corelib/src/test/integer_test.cairo` line 23 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2992#-NUM_wlp3-lUM_YBFodT:-NUMifk0-u6eovBDfN2P:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/302077744bc89d5166426eb59392b2f1b361458c/corelib/src/test/integer_test.cairo#L23)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

This line exists above (if I'm not mistaken).
</blockquote></details>

Done.

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2992#-:-NUNMyiB7O0tRWUm3W7F:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`corelib/src/test/integer_test.cairo` line 23 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2992#-NUNMr6A1q-BrgyIVBFk:-NUNMr6A1q-BrgyIVBFl:b-ryurz) ([raw file](https://github.com/starkware-libs/cairo/blob/8ed97185b5b4d3d9c0a95376abf983db6fb95ce8/corelib/src/test/integer_test.cairo#L23)):*
> ```Cairo
>     assert(!(4_u8 < 4_u8), '!(4 < 4)');
>     assert(5_u8 <= 5_u8, '5 <= 5');
>     assert(!(5_u8 <= 4_u8), '!(5 <= 8)');
> ```

(non-blocking)



_Suggestion:_
```Cairo
    assert(!(5_u8 <= 4_u8), '!(5 <= 4)');
```

**Review by liorgold2 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2992)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by liorgold2 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2992)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
