### PR TITLE
Added logic for graph algorithms post monomorphization

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2080)

### CODE REVIEW

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2080)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2080#-NNpnnEm1l-nxLXUSP9b:-NNpnnEm1l-nxLXUSP9c:b-3yf84a) (no related file):*
change target branch

___

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2080)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/graph_algorithms/concrete_function_node.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2080#-NPM69Wg7tkyUEgx-whC:-NPM69Wg7tkyUEgx-whD:b-rdema2) ([raw file](https://github.com/starkware-libs/cairo/blob/1a1bab552d4052df953b1d76d0e5f0f663cf8d86/crates/cairo-lang-lowering/src/graph_algorithms/concrete_function_node.rs#L29)):*
> ```XML
>     }
> }
> impl<'a> SccAwareGraphNode for ConcreteFunctionWithBodyNode<'a> {
> ```

We discussed this once, but I think this should be just a GraphNode on another (wrapper) type. No need to this trait.



_Code quote:_
```XML
SccAwareGraphNode
```

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2080)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/graph_algorithms/concrete_function_node.rs` line 37 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2080#-NPktxMmAQCfeytylqg0:-NPktxMmAQCfeytylqg1:ba3dfna) ([raw file](https://github.com/starkware-libs/cairo/blob/c8c9f6f1eb76a5c39c82193aeac7d6ca7e34387f/crates/cairo-lang-lowering/src/graph_algorithms/concrete_function_node.rs#L37)):*
> ```XML
> SccGraphNode<ConcreteFunctionWithBodyNode>
> 
> // A node in the SCC-aware-graph. That is - the graph where a node's neighbors are only the subset
> ```

Remove?

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2080)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/graph_algorithms/concrete_function_node.rs` line 37 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2080#-NPktxMmAQCfeytylqg0:-NPl-Rko8MKRBx1tIfRn:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c8c9f6f1eb76a5c39c82193aeac7d6ca7e34387f/crates/cairo-lang-lowering/src/graph_algorithms/concrete_function_node.rs#L37)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 8 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2080#-:-NPl67U30SkSMRMAf3Rb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
