### PR TITLE
Compute the circuits infos once.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5508)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5508)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/lib.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5508#-NxBu-EG0p4R_RqjK4wK:-NxBu-EG0p4R_RqjK4wL:b-xqkac3) ([raw file](https://github.com/starkware-libs/cairo/blob/19e8a955b4d5fb2bad18f7ca47460aa031a513e2/crates/cairo-lang-sierra-to-casm/src/lib.rs#L22)):*
> ```XML
> pub mod test_utils;
> 
> /// Information in the program level required for compiling an invocation.
> ```

why did this need to go to the top module?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-to-casm/src/lib.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5508#-NxBu-EG0p4R_RqjK4wK:-NxBxF4W3Xhb4xT_tBd1:b-m1dnu7) ([raw file](https://github.com/starkware-libs/cairo/blob/19e8a955b4d5fb2bad18f7ca47460aa031a513e2/crates/cairo-lang-sierra-to-casm/src/lib.rs#L22)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why did this need to go to the top module?
</blockquote></details>

because CircuitsInfo is defined in the top module.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5508)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/lib.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5508#-NxBu-EG0p4R_RqjK4wK:-NxC3b9QAMEkugcc6w8u:bbkgs8b) ([raw file](https://github.com/starkware-libs/cairo/blob/19e8a955b4d5fb2bad18f7ca47460aa031a513e2/crates/cairo-lang-sierra-to-casm/src/lib.rs#L22)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

because CircuitsInfo is defined in the top module.
</blockquote></details>

why does it mean it should be here?
it can still use it where it was before.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5508)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/lib.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5508#-NxBu-EG0p4R_RqjK4wK:-NxC7oo8CvSy_SZ92uto:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/19e8a955b4d5fb2bad18f7ca47460aa031a513e2/crates/cairo-lang-sierra-to-casm/src/lib.rs#L22)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why does it mean it should be here?
it can still use it where it was before.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5508#-:-NxC7y0f7V6GoGOLxVIS:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
