### PR TITLE
Add starknet_keccak.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1173)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
the python code is here:
https://github.com/starkware-industries/starkware/blob/f7ce90c489b900bfa11c725a3197da6c6c025be7/src/starkware/starknet/public/abi.py#L38

I'm not sure what types I should use

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1173#-:-NI6ivSY9Z-TdM0FTzm5:b-ym1aja)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/starknet/src/contract.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1173#-NI6j-qI2efd07J2l5pk:-NI6j-qI2efd07J2l5pl:b-83uo62) ([raw file](https://github.com/starkware-libs/cairo/blob/385fd4386511e3078cd871e14be927a57c706e98/crates/starknet/src/contract.rs#L24)):*
> ```XML
> 
> /// A variant of eth-keccak that computes a value that fits in a StarkNet field element.
> pub fn starknet_keccak(data: &[u8]) -> BigUint {
> ```

I could use &str, but we typically store function names as SmolStr
and you cant pass SmolStr as str



_Code quote:_
```XML
&[u8]
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1173#-:-NI7Ethn75NQS-a_qOci:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/starknet/Cargo.toml` line 20 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1173#-NI7EQTiBoJpAYEbppjV:-NI7EQTiBoJpAYEbppjW:b-fveatl) ([raw file](https://github.com/starkware-libs/cairo/blob/385fd4386511e3078cd871e14be927a57c706e98/crates/starknet/Cargo.toml#L20)):*
> ```TOML
> sierra_gas = { path = "../sierra_gas" }
> sierra_to_casm = { path = "../sierra_to_casm" }
> sha3 = "0.10.6"
> ```

use workspace.



_Code quote:_
```TOML
sha3 = "0.10.6"
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1173)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/starknet/Cargo.toml` line 20 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1173#-NI7EQTiBoJpAYEbppjV:-NIBanI49x3Mcw5WDgKl:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/385fd4386511e3078cd871e14be927a57c706e98/crates/starknet/Cargo.toml#L20)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

use workspace.
</blockquote></details>

Done.



_Code quote:_
```TOML
sha3 = "0.10.6"
```

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1173)* status: all files reviewed, 1 unresolved discussion

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1173)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1173)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
