### PR TITLE
Add an ownable-erc20 contract.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4130)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4130)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/test_data/ownable_erc20.cairo` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4130#-NfG8BOY4RjoW0CEUBCs:-NfG8BOY4RjoW0CEUBCt:bpqjsog) ([raw file](https://github.com/starkware-libs/cairo/blob/bc4d5e706c5e7670bcfa0ddb54d510a0951f32a2/crates/cairo-lang-starknet/test_data/ownable_erc20.cairo#L1)):*
> ```Cairo
> // The ERC20 and Ownable components are duplicates of the ones in `with_erc20` and `with_ownable` files.
> ```

Add to this comment that there is more code in "// End of copied components."
___
*[`crates/cairo-lang-starknet/test_data/ownable_erc20.cairo` line 295 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4130#-NfG8a0T4gH04HFyR5Nh:-NfG8a0T4gH04HFyR5Ni:b-riojz7) ([raw file](https://github.com/starkware-libs/cairo/blob/bc4d5e706c5e7670bcfa0ddb54d510a0951f32a2/crates/cairo-lang-starknet/test_data/ownable_erc20.cairo#L295)):*
> ```Cairo
>     #[abi(per_item)]
>     #[generate_trait]
>     impl Impl of Trait {
> ```

meaningful names please



_Code quote:_
```Cairo
impl Impl of Trait 
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4130)* status: 3 of 10 files reviewed, 2 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-starknet/test_data/ownable_erc20.cairo` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4130#-NfG8BOY4RjoW0CEUBCs:-NfH0S-I2OcWhqG1sIr8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bc4d5e706c5e7670bcfa0ddb54d510a0951f32a2/crates/cairo-lang-starknet/test_data/ownable_erc20.cairo#L1)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Add to this comment that there is more code in "// End of copied components."
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/test_data/ownable_erc20.cairo` line 295 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4130#-NfG8a0T4gH04HFyR5Nh:-NfH0svH4gT35j2jB7dW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bc4d5e706c5e7670bcfa0ddb54d510a0951f32a2/crates/cairo-lang-starknet/test_data/ownable_erc20.cairo#L295)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

meaningful names please
</blockquote></details>

Done.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4130)* status: 3 of 10 files reviewed, 3 unresolved discussions (waiting on @orizi and @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4130#-NfH3r5H1QrFDlqg7NrM:-NfH3r5H1QrFDlqg7NrN:bjf44aw) (no related file):*
change target branch.

___

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4130#-:-NfH9l4-E1ha4MiWs573:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4130#-:-NfIY5zTC-_cLlnv-5o9:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4130)* status: all files reviewed, 1 unresolved discussion

**Review by yuvalsw — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4130)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Pull request merged**
