### PR TITLE
storage access component

### PR DESCRIPTION
**Pull request by Tomer-StarkWare**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5959)

### CODE REVIEW

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5959)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @orizi and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/components/storage_accesses.cairo` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5959#-O0x4RjI9J9Izzt_U1lY:-O0x4RjJ792TnCsMB9Sy:b-zc6bhi) ([raw file](https://github.com/starkware-libs/cairo/blob/0b05fef526249e91a97f2199a5c1c834363fde14/crates/cairo-lang-starknet/cairo_level_tests/components/storage_accesses.cairo#L32)):*
> ```Cairo
> }
> 
> #[starknet::component]
> ```

Add a contract that will use this component.



_Code quote:_
```Cairo
#[starknet::component]
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5959)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/components/storage_accesses.cairo` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5959#-O0xCmF89iazvHbodVpR:-O0xCmF89iazvHbodVpS:b-r6zodb) ([raw file](https://github.com/starkware-libs/cairo/blob/0b05fef526249e91a97f2199a5c1c834363fde14/crates/cairo-lang-starknet/cairo_level_tests/components/storage_accesses.cairo#L2)):*
> ```Cairo
> use starknet::ContractAddress;
> use starknet::storage::{StoragePathEntry, Map};
> ```

make the test clear about what it is actually testing.

in other words - remove most of the logic of the interface and probably rename it to something simple.

currently i am not fully sure what am i trying to check.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/components/storage_accesses.cairo` line 30 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5959#-O0xC_cO72jEF4-YxE-o:-O0xC_cO72jEF4-YxE-p:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0b05fef526249e91a97f2199a5c1c834363fde14/crates/cairo-lang-starknet/cairo_level_tests/components/storage_accesses.cairo#L30)):*
> ```Cairo
>     balances: Map::<ContractAddress, u256>,
>     allowances: Map::<ContractAddress, Map<ContractAddress, u256>>,
> }
> ```





_Suggestion:_
```Cairo
#[starknet::storage_node]
struct TransactionInfo {
    balances: Map<ContractAddress, u256>,
    allowances: Map<ContractAddress, Map<ContractAddress, u256>>,
}
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5959)* status: 2 of 20 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/components/storage_accesses.cairo` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5959#-O0xCmF89iazvHbodVpR:-O0xIcyP7asq6sbDOuLV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0b05fef526249e91a97f2199a5c1c834363fde14/crates/cairo-lang-starknet/cairo_level_tests/components/storage_accesses.cairo#L2)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

make the test clear about what it is actually testing.

in other words - remove most of the logic of the interface and probably rename it to something simple.

currently i am not fully sure what am i trying to check.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/components/storage_accesses.cairo` line 30 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5959#-O0xC_cO72jEF4-YxE-o:-O0xH0R8BnoUTnHRHAFR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0b05fef526249e91a97f2199a5c1c834363fde14/crates/cairo-lang-starknet/cairo_level_tests/components/storage_accesses.cairo#L30)):*
> ```Cairo
>     balances: Map::<ContractAddress, u256>,
>     allowances: Map::<ContractAddress, Map<ContractAddress, u256>>,
> }
> ```

Done.

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5959)* status: 2 of 20 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/components/storage_accesses.cairo` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5959#-O0x4RjI9J9Izzt_U1lY:-O1CNlvr3BJiSPmx8b7M:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0b05fef526249e91a97f2199a5c1c834363fde14/crates/cairo-lang-starknet/cairo_level_tests/components/storage_accesses.cairo#L32)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Add a contract that will use this component.
</blockquote></details>

Done.

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5959)* status: 2 of 20 files reviewed, 4 unresolved discussions (waiting on @orizi and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/components/ownable_mini.cairo` line 16 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5959#-O1CRgkoAA8rMC4YWH__:-O1CRgkoAA8rMC4YWH_a:b-2uc5ym) ([raw file](https://github.com/starkware-libs/cairo/blob/5c5f4323e487ed22c881e52beadb8968802db5bc/crates/cairo-lang-starknet/cairo_level_tests/components/ownable_mini.cairo#L16)):*
> ```Cairo
> #[starknet::embeddable]
> pub impl TransferImpl<
>     TContractState, impl X: starknet::storage::HasStorage<TContractState, OwnableStorage>, +Drop<TContractState>
> ```

Same below.



_Suggestion:_
```Cairo
pub impl TransferImpl<
    TContractState, +starknet::storage::HasStorage<TContractState, OwnableStorage>, +Drop<TContractState>
```
___
*[`crates/cairo-lang-starknet/cairo_level_tests/contracts/with_ownable_mini.cairo` line 11 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5959#-O1CRaWk5JJBuKQ5SrWv:-O1CRaWk5JJBuKQ5SrWw:b-cq1a7h) ([raw file](https://github.com/starkware-libs/cairo/blob/5c5f4323e487ed22c881e52beadb8968802db5bc/crates/cairo-lang-starknet/cairo_level_tests/contracts/with_ownable_mini.cairo#L11)):*
> ```Cairo
>         ownable: ownable_mini::OwnableStorage,
>         balance: u128,
>         
> ```

run cairo fmt.



_Code quote:_
```Cairo
·······
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5959)* status: 1 of 20 files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5959#-O1CUplX1X-1wBGHhWu0:-O1CUplX1X-1wBGHhWu1:b-nhbqmg) (no related file):*
work on `dev-v2.7.0`

___
___
*[`corelib/src/starknet/storage.cairo` line 379 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5959#-O1CUbnK6gbYl4Zzlta9:-O1CUbnK6gbYl4ZzltaA:b-mvcbck) ([raw file](https://github.com/starkware-libs/cairo/blob/e6d831cfcd0b482153f3022e35034be9e3b2d439/corelib/src/starknet/storage.cairo#L379)):*
> ```Cairo
> 
> /// A trait for creating a storage node from a storage path.
> pub trait HasStorage<
> ```

doc is wrong.
doc members as well.

move this to the example for the time being, until we are sure this is the efficient way.

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5959)* status: 1 of 20 files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/components/ownable_mini.cairo` line 16 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5959#-O1CRgkoAA8rMC4YWH__:-O1CUbV54zVhZuL9ALwp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5c5f4323e487ed22c881e52beadb8968802db5bc/crates/cairo-lang-starknet/cairo_level_tests/components/ownable_mini.cairo#L16)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Same below.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/contracts/with_ownable_mini.cairo` line 11 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5959#-O1CRaWk5JJBuKQ5SrWv:-O1CU_Pw2KtbgEnOy4Ai:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5c5f4323e487ed22c881e52beadb8968802db5bc/crates/cairo-lang-starknet/cairo_level_tests/contracts/with_ownable_mini.cairo#L11)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

run cairo fmt.
</blockquote></details>

Done.
___
*[`corelib/src/starknet/storage.cairo` line 379 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5959#-O1CUbnK6gbYl4Zzlta9:-O1G8lgsC1w0fGdpBN12:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e6d831cfcd0b482153f3022e35034be9e3b2d439/corelib/src/starknet/storage.cairo#L379)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc is wrong.
doc members as well.

move this to the example for the time being, until we are sure this is the efficient way.
</blockquote></details>

Done.

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5959)* status: 1 of 133 files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware, @mkaput, @orizi, and @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5959#-O1CUplX1X-1wBGHhWu0:-O1GA_Oj3FxtoYDF-MIk:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

work on `dev-v2.7.0`
</blockquote></details>

Done.

___

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5959)* status: 1 of 133 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`-- commits` line 4 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5959#-O1GT1RMEbru0hH7iQkd):*
change target to dev-v2.7.0

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5959)* status: 1 of 133 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`-- commits` line 4 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5959#-O1GT1RMEbru0hH7iQkd):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

change target to dev-v2.7.0
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 13 of 18 files at r3, 1 of 5 files at r4, 3 of 4 files at r5, 1 of 115 files at r6, 114 of 114 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5959)* status: all files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/contracts/with_ownable_mini.cairo` line 7 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5959#-O1Gg0Pw2dM4AwQZaeXv:-O1Gg0Pw2dM4AwQZaeXw:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/22024b372411a76345d88f9ef948c96baadbd7ef/crates/cairo-lang-starknet/cairo_level_tests/contracts/with_ownable_mini.cairo#L7)):*
> ```Cairo
>     use starknet::ContractAddress;
>     use starknet::storage::{StorageAsPath, StorageNode, MutableStorageNode};
>     #[storage]
> ```





_Suggestion:_
```Cairo
    use starknet::storage::{StorageAsPath, StorageNode, MutableStorageNode};

    #[storage]
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5959)* status: all files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/contracts/with_ownable_mini.cairo` line 7 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5959#-O1Gg0Pw2dM4AwQZaeXv:-O1Gq63_EM2rYx62UUck:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/22024b372411a76345d88f9ef948c96baadbd7ef/crates/cairo-lang-starknet/cairo_level_tests/contracts/with_ownable_mini.cairo#L7)):*
> ```Cairo
>     use starknet::ContractAddress;
>     use starknet::storage::{StorageAsPath, StorageNode, MutableStorageNode};
>     #[storage]
> ```

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5959)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

**Pull request merged**
