### PR TITLE
Adding option to fetch a classes json file from node rpc calls.

### PR DESCRIPTION
**Pull request by Tomer-StarkWare**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5594)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5594)* status: all files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 170 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5594#-NyMhmi44WEzQ08yGIh6:-NyMhmi44WEzQ08yGIh7:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f2bd3d936e63bc7dc2458475b3339a1d02ca002e/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L170)):*
> ```XML
> 
>     // If class_info_output_file is provided, fill the contract class info to the file.
>     // Otherwise, return the reporst of the processing classes.
> ```





_Suggestion:_
```XML
    // If class_info_output_file is provided, dump all contract class infos into the file.
    // Otherwise, generate a report for the classes analysis.
```
___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 179 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5594#-NyMhX9xBUFAXHsCS8D0:-NyMhX9xBUFAXHsCS8D1:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f2bd3d936e63bc7dc2458475b3339a1d02ca002e/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L179)):*
> ```XML
>         };
> 
>         spawn_class_processors(classes_rx, results_tx, class_bar.clone(), config);
> ```





_Suggestion:_
```XML
    class_bar.set_style(get_style("Process classes"));

    let (classes_tx, classes_rx) = async_channel::bounded(256);
    let config: Arc<RunConfig> = Arc::new(RunConfig {
        list_selector,
        override_version,
        max_bytecode_size: args.max_bytecode_size,
    });

    // If fullnode_url is provided, we spawn the contract class info from the fullnode.
    // Otherwise, we spawn the contract class info from the input files.
    if let Some(fullnode_url) = args.fullnode_url {
        assert!(args.input_files.is_empty(), "two different sources of classes provided.");
        let (class_hashes_tx, class_hashes_rx) = async_channel::bounded(128);
        spawn_block_class_hashes_retrievers(
            args.start_block.with_context(|| "no start block provided")?,
            args.end_block.with_context(|| "no end block provided")?,
            class_hashes_tx,
            fullnode_url.clone(),
            reader_bar.clone(),
            class_bar.clone(),
        );
        spawn_classes_from_class_hashes(class_hashes_rx, classes_tx, fullnode_url);
    } else {
        // Setting up results of class recompilation.
        let mut input_readers =
            spawn_input_file_readers(args.input_files, classes_tx, reader_bar.clone());
        while let Some(result) = input_readers.join_next().await {
            result.with_context(|| "Failed to join file reader.")??;
        }
    }

    // If class_info_output_file is provided, fill the contract class info to the file.
    // Otherwise, return the reporst of the processing classes.
    if let Some(class_info_output_file) = args.class_info_output_file {
        fill_class_info_to_file(classes_rx, class_bar, &class_info_output_file).await
    } else {
        let (results_tx, results_rx) = async_channel::bounded(128);
        let results_handler = {
            let class_bar = class_bar.clone();
            tokio::spawn(async move { collect_result(results_rx, class_bar).await })
        };

        spawn_class_processors(classes_rx, results_tx, class_bar.clone(), config);
```
___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 515 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5594#-NyMiYye6n1AoHYU2MyT:-NyMiYye6n1AoHYU2MyU:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f2bd3d936e63bc7dc2458475b3339a1d02ca002e/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L515)):*
> ```XML
> }
> 
> /// Given a class hash, retrieves the ContractClassInfo from the state.
> ```





_Suggestion:_
```XML
/// Given a class hash, retrieves the matching ContractClassInfo.
```
___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 520 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5594#-NyMig-o-XxwDfHKQlF8:-NyMig-pDX_-xQRsXEou:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f2bd3d936e63bc7dc2458475b3339a1d02ca002e/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L520)):*
> ```XML
>     classes_tx: &async_channel::Sender<ContractClassInfo>,
>     url: String,
> ) {
> ```





_Suggestion:_
```XML
    classes_tx: &async_channel::Sender<ContractClassInfo>,
    url: &str,
) {
```
___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 552 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5594#-NyMiRVkAiBPTjX0QF8H:-NyMiRVkAiBPTjX0QF8I:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f2bd3d936e63bc7dc2458475b3339a1d02ca002e/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L552)):*
> ```XML
> }
> 
> /// Spawns tasks that retrieve the ContractClassInfo from the state.
> ```





_Suggestion:_
```XML
/// Spawns tasks that retrieve ContractClassInfos from a class hash.
```
___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 565 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5594#-NyMiji45eeKIYb0Ei6Q:-NyMiji45eeKIYb0Ei6R:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f2bd3d936e63bc7dc2458475b3339a1d02ca002e/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L565)):*
> ```XML
>             while let Ok(class_hashes) = class_hashes_rx.recv().await {
>                 retrieve_class_from_class_hash(class_hashes, &classes_tx, url.clone()).await;
>             }
> ```





_Suggestion:_
```XML
                retrieve_class_from_class_hash(class_hashes, &classes_tx, &url).await;
            }
```
___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 571 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5594#-NyMi8HcBBO7UW44Iguw:-NyMi8HcBBO7UW44Igux:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f2bd3d936e63bc7dc2458475b3339a1d02ca002e/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L571)):*
> ```XML
> 
> /// Fills the contract classes info to the provided file.
> async fn fill_class_info_to_file(
> ```





_Suggestion:_
```XML
/// Dumps the classes info from `classes_rx` to the provided file in json format.
async fn dump_class_infos_into_json(
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5594#-:-NyOxbdxCTocPxUZ_Akx:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5594)* status: all files reviewed, 4 unresolved discussions (waiting on @Tomer-StarkWare)

___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5594#-NyOzmz21g2qpV8MvZcg:-NyOzmz21g2qpV8MvZch:bt4tn8b) ([raw file](https://github.com/starkware-libs/cairo/blob/3c59cf77ecd6b69d559be071952a770182813562/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L28)):*
> ```XML
> /// 1. If class_info_output_file is provided, it writes the classes to the file.
> /// 2. If class_info_output_file is not provided, it returns the report of the runs over the
> ///    processes of the classes.
> ```

I think that if you'll use `//` instead of `///` it won't get to the generated `--help`, but verify this.



_Suggestion:_
```XML
/// 2. If class_info_output_file is not provided, it returns the report of the runs over the
///    processes of the classes.
// TODO(TomerC): Use ArgGroup to enforce these using Clap.
```
___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 146 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5594#-NyP-r2G1bf9vJv0rQ-A:-NyP-r2G1bf9vJv0rQ-B:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/3c59cf77ecd6b69d559be071952a770182813562/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L146)):*
> ```XML
> 
>     // If fullnode_url is provided, we spawn the contract class info from the fullnode.
>     // Otherwise, we spawn the contract class info from the input files.
> ```





_Suggestion:_
```XML
    // If fullnode_url is provided, we retrieve the contract class info from the fullnode.
    // Otherwise, we read the contract class info from the input files.
```

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5594#-:-NyP1pEbDjmJQhhX73H-:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @Tomer-StarkWare)

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5594)* status: all files reviewed, 4 unresolved discussions (waiting on @Tomer-StarkWare)

**Review by gilbens-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5594)* status: all files reviewed, 2 unresolved discussions (waiting on @Tomer-StarkWare)

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5594)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 170 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5594#-NyMhmi44WEzQ08yGIh6:-NyOp4DS3fMsf8_084S-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f2bd3d936e63bc7dc2458475b3339a1d02ca002e/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L170)):*
> ```XML
> 
>     // If class_info_output_file is provided, fill the contract class info to the file.
>     // Otherwise, return the reporst of the processing classes.
> ```

Done.
___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 179 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5594#-NyMhX9xBUFAXHsCS8D0:-NyOpByWDCqBNG0rzjoe:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f2bd3d936e63bc7dc2458475b3339a1d02ca002e/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L179)):*
> ```XML
>         };
> 
>         spawn_class_processors(classes_rx, results_tx, class_bar.clone(), config);
> ```

Done.
___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 515 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5594#-NyMiYye6n1AoHYU2MyT:-NyOpIqfEEwIf5BBjPSn:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f2bd3d936e63bc7dc2458475b3339a1d02ca002e/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L515)):*
> ```XML
> }
> 
> /// Given a class hash, retrieves the ContractClassInfo from the state.
> ```

Done.
___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 520 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5594#-NyMig-o-XxwDfHKQlF8:-NyOpVCa2kUKMng2OrUL:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f2bd3d936e63bc7dc2458475b3339a1d02ca002e/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L520)):*
> ```XML
>     classes_tx: &async_channel::Sender<ContractClassInfo>,
>     url: String,
> ) {
> ```

Done.
___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 552 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5594#-NyMiRVkAiBPTjX0QF8H:-NyOp_JvCuszB8L94tFj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f2bd3d936e63bc7dc2458475b3339a1d02ca002e/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L552)):*
> ```XML
> }
> 
> /// Spawns tasks that retrieve the ContractClassInfo from the state.
> ```

Done.
___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 565 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5594#-NyMiji45eeKIYb0Ei6Q:-NyOpfGA7z_NI3R8a4g0:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f2bd3d936e63bc7dc2458475b3339a1d02ca002e/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L565)):*
> ```XML
>             while let Ok(class_hashes) = class_hashes_rx.recv().await {
>                 retrieve_class_from_class_hash(class_hashes, &classes_tx, url.clone()).await;
>             }
> ```

Done.
___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 571 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5594#-NyMi8HcBBO7UW44Iguw:-NyOpsVO8gMdWe0RqkrH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f2bd3d936e63bc7dc2458475b3339a1d02ca002e/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L571)):*
> ```XML
> 
> /// Fills the contract classes info to the provided file.
> async fn fill_class_info_to_file(
> ```

Done.
___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5594#-NyOzmz21g2qpV8MvZcg:-NyP1L9nCrfB2FUs482m:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3c59cf77ecd6b69d559be071952a770182813562/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L28)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

I think that if you'll use `//` instead of `///` it won't get to the generated `--help`, but verify this.
</blockquote></details>

Done.
___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 146 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5594#-NyP-r2G1bf9vJv0rQ-A:-NyP0z9t7l0AGR9hoH-b:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3c59cf77ecd6b69d559be071952a770182813562/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L146)):*
> ```XML
> 
>     // If fullnode_url is provided, we spawn the contract class info from the fullnode.
>     // Otherwise, we spawn the contract class info from the input files.
> ```

Done.

**Pull request merged**
