### PR TITLE
Fix u256 construction docs.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2859)

### CODE REVIEW

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2859#-:-NTIzI5BBDkGWJ4j7HvR:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/integer-types.adoc` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2859#-NTIymNzAyzw5nD8018H:-NTIymNzAyzw5nD8018I:bvz3a8i) ([raw file](https://github.com/starkware-libs/cairo/blob/e33286a66ebc3fe433a98f81b7b193b348698c46/docs/reference/src/components/cairo/modules/language_constructs/pages/integer-types.adoc#L28)):*
> ```AsciiDoc
>     let y = 0xff_u64;
>     // let z = 10_u256; // Error: u256 literals are not supported
>     let z: u256 = u256 { low: 10_u128, high: 0_u128 } // 10 in u256 type
> ```

I prefer to have high first - I guess it's debatable though.



_Code quote:_
```AsciiDoc
low: 10_u128, high: 0_u128
```

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2859)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`corelib/src/starknet/syscalls.cairo` line 25 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2859#-NTT9fH75ssYbzSpchx9:-NTT9fH75ssYbzSpchxA:b2myfib) ([raw file](https://github.com/starkware-libs/cairo/blob/b69a9e5fd7e99670590b5c7cd6dd2929361d79a0/corelib/src/starknet/syscalls.cairo#L25)):*
> ```Cairo
>     calldata: Span<felt252>,
>     deploy_from_zero: bool,
> ) -> SyscallResult<(ContractAddress, Span < felt252 >)> implicits(GasBuiltin, System) nopanic;
> ```

remove file from PR.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2859)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`corelib/src/starknet/syscalls.cairo` line 25 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2859#-NTT9fH75ssYbzSpchx9:-NTT9x_H9cciuUNdwLI7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b69a9e5fd7e99670590b5c7cd6dd2929361d79a0/corelib/src/starknet/syscalls.cairo#L25)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

remove file from PR.
</blockquote></details>

Done.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2859#-:-NTTgo-W-lflLn-_MFME:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
