### PR TITLE
Keep track of locations in SemanticLoweringMapping.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3702)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3702)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 494 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3702#-N_dL7boEI0gt1_KshuK:-N_dL7boEI0gt1_KshuL:b-fwjxnn) ([raw file](https://github.com/starkware-libs/cairo/blob/6970c37147ae5fcd7cd00ee1a4e519357fdd402b/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L494)):*
> ```
>  --> lib.cairo:12:10
>   return x;
>          ^
> ```

This is a regression that I need to fix.



_Code quote:_
```
  return x;
         ^
```

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3702)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 494 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3702#-N_dL7boEI0gt1_KshuK:-N_dN3Md5NceYKCTi2NU:b-cg2coe) ([raw file](https://github.com/starkware-libs/cairo/blob/6970c37147ae5fcd7cd00ee1a4e519357fdd402b/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L494)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

But I'm not quite sure how.

v3 here:
(v6: test::MyStruct) <- struct_construct(v5{`x.a`}, v3{`x`})

refers to the original `x`, not the `x` in the return statement.
</blockquote></details>

but why isn't the `var usage` the `x` in the return statement? - this is the definition - not the usage.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 494 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3702#-N_dL7boEI0gt1_KshuK:-N_dO21w5DsCr4bl8gks:b-jbe0hz) ([raw file](https://github.com/starkware-libs/cairo/blob/6970c37147ae5fcd7cd00ee1a4e519357fdd402b/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L494)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

but why isn't the `var usage` the `x` in the return statement? - this is the definition - not the usage.
</blockquote></details>

The error is on v3, not v6.



_Code snippet:_
```
  (v6: test::MyStruct) <- struct_construct(v5{`x.a`}, v3{`x`})
End:
  Return(v6)
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3702)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 494 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3702#-N_dL7boEI0gt1_KshuK:-N_dPw2a8o_jL8zy2Nc0:b-r4anu0) ([raw file](https://github.com/starkware-libs/cairo/blob/6970c37147ae5fcd7cd00ee1a4e519357fdd402b/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L494)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

The error is on v3, not v6.
</blockquote></details>

true - but isn't the error caused by the statement?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 494 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3702#-N_dL7boEI0gt1_KshuK:-N_dQ9HPAvU24svGLmkk:b-n6s2rz) ([raw file](https://github.com/starkware-libs/cairo/blob/6970c37147ae5fcd7cd00ee1a4e519357fdd402b/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L494)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

true - but isn't the error caused by the statement?
</blockquote></details>

The error is caused by seconds argument to struct construct.

The lowering does not keep track of the fact that `struct_construct` was created by the return statement.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 494 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3702#-N_dL7boEI0gt1_KshuK:-N_dRTg-ADL5uuI35eCL:b6bqgnl) ([raw file](https://github.com/starkware-libs/cairo/blob/6970c37147ae5fcd7cd00ee1a4e519357fdd402b/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L494)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't know if it is well defined.
</blockquote></details>

btw, the usage location of the return is correct:
https://github.com/starkware-libs/cairo/blob/f006688fc3eb9b4ce56c1dd8a451ed3520debb20/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L512

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3702)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 494 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3702#-N_dL7boEI0gt1_KshuK:-N_dozhPDXG0xA4JV4au:b-vku9ps) ([raw file](https://github.com/starkware-libs/cairo/blob/6970c37147ae5fcd7cd00ee1a4e519357fdd402b/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L494)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

btw, the usage location of the return is correct:
https://github.com/starkware-libs/cairo/blob/f006688fc3eb9b4ce56c1dd8a451ed3520debb20/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L512
</blockquote></details>

I see your point.
but if we have
invalidate(self.a)
we want the location to be self.a, right?

Maybe we want to make this location optional and in the None case, use the location of the var causing the reconstruction?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3702)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/block_builder.rs` line 350 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3702#-N_hAjVe3zFAMx4MXFxJ:-N_hAjVfCvZI92ARAHv6:bw07rl) ([raw file](https://github.com/starkware-libs/cairo/blob/6970c37147ae5fcd7cd00ee1a4e519357fdd402b/crates/cairo-lang-lowering/src/lower/block_builder.rs#L350)):*
> ```XML
>                 .map(|var_id| VarUsage { var_id, location: self.location })
>                 .collect_vec(),
>             ty,
> ```

The goal of the PR is that if you update self.a and self.b
you'll get
(v14: test::MyStruct) <\- struct\_construct(v10{\`self.a\`}, v3{\`self.b\`})
instead of
(v14: test::MyStruct) <\- struct\_construct(v10{\`self\`}, v3{\`self\`})



_Code quote:_
```XML
            inputs: members
                .into_iter()
                .map(|var_id| VarUsage { var_id, location: self.location })
                .collect_vec(),
            ty,
```

**Comment by ilyalesokhin-starkware** [comment]
Currently this changes makes the error locations wose.

**Pull request closed without merging**
