### PR TITLE
match_optimization: Add support for additional remapping (not enabled yet).

### PR DESCRIPTION
**Pull request by liorgold2**
**Stack**:
- #6337
- #6339 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6339)

### CODE REVIEW

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6339)* status: 0 of 1 files reviewed, 1 unresolved discussion

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6339#-O5rYBqN2FkBNmpOLYVe:-O5rYBqN2FkBNmpOLYVf:b7efrru) ([raw file](https://github.com/starkware-libs/cairo/blob/21baa5bad81361d1db3ca5127796e66eef964696/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L146)):*
> ```XML
>         new_block_remapping.insert(orig_var, VarUsage { var_id: *arm_var, location: *location });
>         for (var, new_var) in renamed_vars.iter() {
>             new_block_remapping.insert(*new_var, VarUsage { var_id: *var, location: *location });
> ```

Is the location here correct?

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6339)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @liorgold2)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6339#-O5rYBqN2FkBNmpOLYVe:-O5vyo3p77EpIcs-qGWZ:b-cgz9nl) ([raw file](https://github.com/starkware-libs/cairo/blob/21baa5bad81361d1db3ca5127796e66eef964696/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L146)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Is the location here correct?
</blockquote></details>

seems fine to me - it just points to the original location of the match.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 58 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6339#-O5wY3oS5Mr62lofX619:-O5wY3oS5Mr62lofX61A:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/579d20fa5c8cb107ad13c95f42df4114f04a4aec/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L58)):*
> ```XML
> 
>     // Track variable renaming that results from applying the fixes below.
>     // For each match arm and variable that is remapped (prior to the match),
> ```





_Suggestion:_
```XML
  // For each (variable_id, arm_idx) pair that is remapped (prior to the match),
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 159 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6339#-O5wYrNk4e5jcmn5u_Es:-O5wYrNk4e5jcmn5u_Et:bfkzk1p) ([raw file](https://github.com/starkware-libs/cairo/blob/579d20fa5c8cb107ad13c95f42df4114f04a4aec/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L159)):*
> ```XML
>             let block = &mut lowered.blocks[block_id];
>             *block = var_renamer.rebuild_block(block);
>         }
> ```

The same block could be rebuilt multiple times this way.

Maybe we should rebuild all the blocks at the end?



_Code quote:_
```XML
        // Apply the variable renaming to the reachable blocks.
        for block_id in reachable_blocks {
            let block = &mut lowered.blocks[block_id];
            *block = var_renamer.rebuild_block(block);
        }
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6339)* status: all files reviewed, 3 unresolved discussions (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6339)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 58 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6339#-O5wY3oS5Mr62lofX619:-O5xFqDsB26-l-Kcec_6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f94009e14398944c81aa8251ec554a89f1b5848a/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L58)):*
> ```XML
> 
>     // Track variable renaming that results from applying the fixes below.
>     // For each match arm and variable that is remapped (prior to the match),
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 159 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6339#-O5wYrNk4e5jcmn5u_Es:-O5xFre89QSr6qIZn0Ap:bxkktny) ([raw file](https://github.com/starkware-libs/cairo/blob/f94009e14398944c81aa8251ec554a89f1b5848a/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L159)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

The same block could be rebuilt multiple times this way.

Maybe we should rebuild all the blocks at the end?
</blockquote></details>

Decided not to do it right now, since it'll complicate the code.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6339#-:-O5xHcZS94Ba_LxYy9Jb:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6339#-:-O5xVF-D7jA4jIbF_l6F:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
