### PR TITLE
Fix lowering bug

### PR DESCRIPTION
**Pull request by yuvalsw**
of not lazy-evaluating enum libfunc result when
not using the result of the libfunc call

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1258)

### CODE REVIEW

**Review by spapinistarkware — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1258)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @yuvalsw)

___
*[`crates/lowering/src/lower.rs` line 222 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1258#-NIl1-So05vkE3HjOVHC:-NIl1-So05vkE3HjOVHD:b-6fueqh) ([raw file](https://github.com/starkware-libs/cairo/blob/550c75eaba3ee3e68e845bf30b9a71b94cde231f/crates/lowering/src/lower.rs#L222)):*
> ```XML
>             // The LoweredExpr must be evaluated now to push/bring back variables in case it is
>             // LoweredExpr::ExternEnum.
>             if let LoweredExpr::ExternEnum(x) = lowered_expr {
> ```

This seems prone to bugs if we add more variant to LoweredExpr. Maybe always call .var()? If not, use an exhaustive match.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1258)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @spapinistarkware)

___
*[`crates/lowering/src/lower.rs` line 222 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1258#-NIl1-So05vkE3HjOVHC:-NIlekNZCduXowVfIGdr:b-op091q) ([raw file](https://github.com/starkware-libs/cairo/blob/550c75eaba3ee3e68e845bf30b9a71b94cde231f/crates/lowering/src/lower.rs#L222)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This seems prone to bugs if we add more variant to LoweredExpr. Maybe always call .var()? If not, use an exhaustive match.
</blockquote></details>

I called .var() always at first, but then it added a struct_construct sierra statement for an unused tuple in one of the tests. WDYT?

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1258)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @spapinistarkware)

___
*[`crates/lowering/src/lower.rs` line 222 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1258#-NIl1-So05vkE3HjOVHC:-NJFpcTV9G1bjma8V4u5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/550c75eaba3ee3e68e845bf30b9a71b94cde231f/crates/lowering/src/lower.rs#L222)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

As @spapinistarkware mentions, the other option is to simply have an exhaustive match for now.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1258#-:-NJFxLHd6k9-o7THNcDM:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by yuvalsw — COMMENTED** [review]
> Dismissed @spapinistarkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1258)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1258)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1258)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
