### PR TITLE
Index impls by head

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2443)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2443** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2443" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2443?utm_source=stack-comment).

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2443)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware, @spapinistarkware, and @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQK3ZrZ-wYPiS-QRuDD:-NQK3ZrZ-wYPiS-QRuDE:b-7zun92) (no related file):*
Head needs to be defined in order for this to be clear

___
___
*[`crates/cairo-lang-semantic/src/types.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQK3Sv4BtR3LGIvIyIs:-NQK3Sv4BtR3LGIvIyIt:b2nhdkj) ([raw file](https://github.com/starkware-libs/cairo/blob/7c800d197696b5d065e4a1f3901976f1bdbb0ea5/crates/cairo-lang-semantic/src/types.rs#L113)):*
> ```XML
> 
> #[derive(Clone, Debug, Hash, PartialEq, Eq)]
> pub enum TypeHead {
> ```

Doc

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2443)* status: 3 of 4 files reviewed, 13 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 390 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQK4Pqy0SpUmRAurRFm:-NQK4Pqy0SpUmRAurRFn:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7c800d197696b5d065e4a1f3901976f1bdbb0ea5/crates/cairo-lang-semantic/src/db.rs#L390)):*
> ```XML
>         trait_function_id: TraitFunctionId,
>     ) -> Maybe<Option<ImplFunctionId>>;
>     /// Returns candidate [ImplDefId]s for a specific lookup constraint.
> ```





_Suggestion:_
```XML
specific trait lookup constraint
```
___
*[`crates/cairo-lang-semantic/src/db.rs` line 392 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQK2kiJD9ripW3BtGEW:-NQK2kiJD9ripW3BtGEX:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7c800d197696b5d065e4a1f3901976f1bdbb0ea5/crates/cairo-lang-semantic/src/db.rs#L392)):*
> ```XML
>     /// Returns candidate [ImplDefId]s for a specific lookup constraint.
>     #[salsa::invoke(items::imp::module_impls_ids_for_trait_info)]
>     fn module_impls_ids_for_trait_info(
> ```





_Suggestion:_
```XML
module_impl_ids_for_trait_info
```
___
*[`crates/cairo-lang-semantic/src/types.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQK544306lrTTNR0c6v:-NQK544306lrTTNR0c6w:b-r08v83) ([raw file](https://github.com/starkware-libs/cairo/blob/7c800d197696b5d065e4a1f3901976f1bdbb0ea5/crates/cairo-lang-semantic/src/types.rs#L68)):*
> ```XML
>     }
> 
>     pub fn head(&self, db: &dyn SemanticGroup) -> Option<TypeHead> {
> ```

doc also here - what is a head of a type?
___
*[`crates/cairo-lang-semantic/src/types.rs` line 91 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQK5I_E5evqe4BY8ao3:-NQK5I_E5evqe4BY8ao4:b-ecz2xr) ([raw file](https://github.com/starkware-libs/cairo/blob/7c800d197696b5d065e4a1f3901976f1bdbb0ea5/crates/cairo-lang-semantic/src/types.rs#L91)):*
> ```XML
>         }
>     }
>     pub fn head(&self, db: &dyn SemanticGroup) -> Option<TypeHead> {
> ```

same doc here.
___
*[`crates/cairo-lang-semantic/src/types.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQK5Uo3Eh-Qmv6js-KF:-NQK5Uo3Eh-Qmv6js-KG:b-7i98qs) ([raw file](https://github.com/starkware-libs/cairo/blob/7c800d197696b5d065e4a1f3901976f1bdbb0ea5/crates/cairo-lang-semantic/src/types.rs#L97)):*
> ```XML
>             TypeLongId::Snapshot(inner) => TypeHead::Snapshot(Box::new(inner.head(db)?)),
>             TypeLongId::GenericParameter(_) => return None,
>             TypeLongId::Var(_) => return None,
> ```

unite



_Code quote:_
```XML
            TypeLongId::GenericParameter(_) => return None,
            TypeLongId::Var(_) => return None,
            TypeLongId::Missing(_) => return None,
```
___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQK6JCEDx4hJD03OPyn:-NQK6JCEDx4hJD03OPyo:btbyt99) ([raw file](https://github.com/starkware-libs/cairo/blob/7c800d197696b5d065e4a1f3901976f1bdbb0ea5/crates/cairo-lang-semantic/src/items/generics.rs#L44)):*
> ```XML
>         }
>     }
>     pub fn head(&self, db: &dyn SemanticGroup) -> Option<GenericArgumentHead> {
> ```

doc - what does none mean?
___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQK5rgt1jtEX0c27Nsc:-NQK5rgt1jtEX0c27Nsd:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/7c800d197696b5d065e4a1f3901976f1bdbb0ea5/crates/cairo-lang-semantic/src/items/generics.rs#L67)):*
> ```XML
> 
> #[derive(Clone, Debug, Hash, PartialEq, Eq)]
> pub enum GenericArgumentHead {
> ```

doc
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 110 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQK6G_q49Vp8KvqL4Z3:-NQK6G_q49Vp8KvqL4Z4:btbyt99) ([raw file](https://github.com/starkware-libs/cairo/blob/7c800d197696b5d065e4a1f3901976f1bdbb0ea5/crates/cairo-lang-semantic/src/items/imp.rs#L110)):*
> ```XML
> }
> impl ImplId {
>     pub fn head(&self, db: &dyn SemanticGroup) -> Option<ImplHead> {
> ```

doc - what does none mean?
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQK6DQF-OLLJbj3X8gJ:-NQK6DQF-OLLJbj3X8gK:b-7i98qs) ([raw file](https://github.com/starkware-libs/cairo/blob/7c800d197696b5d065e4a1f3901976f1bdbb0ea5/crates/cairo-lang-semantic/src/items/imp.rs#L114)):*
> ```XML
>             ImplId::Concrete(concrete) => ImplHead::Concrete(concrete.impl_def_id(db)),
>             ImplId::GenericParameter(_) => return None,
>             ImplId::ImplVar(_) => return None,
> ```

unite



_Code quote:_
```XML
            ImplId::GenericParameter(_) => return None,
            ImplId::ImplVar(_) => return None,
```
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 133 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQK6VdC0aaHCVpSWU1R:-NQK6VdC0aaHCVpSWU1S:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/7c800d197696b5d065e4a1f3901976f1bdbb0ea5/crates/cairo-lang-semantic/src/items/imp.rs#L133)):*
> ```XML
> 
> #[derive(Clone, Debug, Hash, PartialEq, Eq)]
> pub enum ImplHead {
> ```

doc
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 542 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQK6s8Y6cEx_Fwxy-vI:-NQK6s8Y6cEx_Fwxy-vJ:bpsta9w) ([raw file](https://github.com/starkware-libs/cairo/blob/7c800d197696b5d065e4a1f3901976f1bdbb0ea5/crates/cairo-lang-semantic/src/items/imp.rs#L542)):*
> ```XML
> 
> #[derive(Clone, Debug, Hash, PartialEq, Eq)]
> pub struct TraitLookupConstraint {
> ```

I stopped reviewing here. Please doc everything.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2443)* status: 3 of 4 files reviewed, 8 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQK3ZrZ-wYPiS-QRuDD:-NQKBbyA1jQ7mSDThC6f:b-1cpayq) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Head needs to be defined in order for this to be clear
</blockquote></details>

Is this better?

___
___
*[`crates/cairo-lang-semantic/src/db.rs` line 392 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQK2kiJD9ripW3BtGEW:-NQK9Go-4POu-iEKh8BP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7c800d197696b5d065e4a1f3901976f1bdbb0ea5/crates/cairo-lang-semantic/src/db.rs#L392)):*
> ```XML
>     /// Returns candidate [ImplDefId]s for a specific lookup constraint.
>     #[salsa::invoke(items::imp::module_impls_ids_for_trait_info)]
>     fn module_impls_ids_for_trait_info(
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/types.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQK544306lrTTNR0c6v:-NQKAF112hS5Zr67NT22:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7c800d197696b5d065e4a1f3901976f1bdbb0ea5/crates/cairo-lang-semantic/src/types.rs#L68)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

doc also here - what is a head of a type?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/types.rs` line 91 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQK5I_E5evqe4BY8ao3:-NQKANAv0AAXpqQ5qY6g:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7c800d197696b5d065e4a1f3901976f1bdbb0ea5/crates/cairo-lang-semantic/src/types.rs#L91)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

same doc here.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/types.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQK3Sv4BtR3LGIvIyIs:-NQKARBQA1zB8940DZwe:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7c800d197696b5d065e4a1f3901976f1bdbb0ea5/crates/cairo-lang-semantic/src/types.rs#L113)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQK5rgt1jtEX0c27Nsc:-NQKB7kN6ZIBQlR-f76S:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7c800d197696b5d065e4a1f3901976f1bdbb0ea5/crates/cairo-lang-semantic/src/items/generics.rs#L67)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 133 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQK6VdC0aaHCVpSWU1R:-NQKBHmaEcb3nKSqQq9g:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7c800d197696b5d065e4a1f3901976f1bdbb0ea5/crates/cairo-lang-semantic/src/items/imp.rs#L133)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 542 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQK6s8Y6cEx_Fwxy-vI:-NQKBY17BfXNNMJkc91Z:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7c800d197696b5d065e4a1f3901976f1bdbb0ea5/crates/cairo-lang-semantic/src/items/imp.rs#L542)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I stopped reviewing here. Please doc everything.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2443#-:-NQKCfNR8fmCLLRxySIq:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 7 unresolved discussions (waiting on @ilyalesokhin-starkware and @yuvalsw)

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2443)* status: all files reviewed (commit messages unreviewed), 13 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 94 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQKMJLp9JwtJ47O1tVU:-NQKMJLp9JwtJ47O1tVV:b-vhow3s) ([raw file](https://github.com/starkware-libs/cairo/blob/97b975e40c2d63f7a1ebae5027b9936b273fcbfa/crates/cairo-lang-semantic/src/types.rs#L94)):*
> ```XML
> 
>     /// Returns the [TypeHead] for a type if available.
>     pub fn head(&self, db: &dyn SemanticGroup) -> Option<TypeHead> {
> ```

doc - when is none returned?
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 549 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQKNZClAc7QXTiGUXB7:-NQKNZClAc7QXTiGUXB8:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/97b975e40c2d63f7a1ebae5027b9936b273fcbfa/crates/cairo-lang-semantic/src/items/imp.rs#L549)):*
> ```XML
> pub struct TraitLookupConstraint {
>     trait_id: TraitId,
>     first_generic_constraint: HeadContraint,
> ```

doc
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 552 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQKOO0h9hBbOeDi5FVs:-NQKOO0h9hBbOeDi5FVt:bu1kce3) ([raw file](https://github.com/starkware-libs/cairo/blob/97b975e40c2d63f7a1ebae5027b9936b273fcbfa/crates/cairo-lang-semantic/src/items/imp.rs#L552)):*
> ```XML
> }
> 
> /// A lookup constraint on a [GenericArgumentHead] that is not based on current inference state.
> ```

constraint on a list of generic arguments?



_Code quote:_
```XML
 A lookup constraint on a [GenericArgumentHead] 
```
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 555 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQKN8w6DAdL0HsEvH7l:-NQKN8w6DAdL0HsEvH7m:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/97b975e40c2d63f7a1ebae5027b9936b273fcbfa/crates/cairo-lang-semantic/src/items/imp.rs#L555)):*
> ```XML
> /// This is used for caching queries.
> #[derive(Clone, Debug, Hash, PartialEq, Eq)]
> pub enum HeadContraint {
> ```





_Suggestion:_
```XML
HeadConstraint
```
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 555 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQKN__mDTMNA5NFx9vU:-NQKN__mDTMNA5NFx9vV:benh18z) ([raw file](https://github.com/starkware-libs/cairo/blob/97b975e40c2d63f7a1ebae5027b9936b273fcbfa/crates/cairo-lang-semantic/src/items/imp.rs#L555)):*
> ```XML
> /// This is used for caching queries.
> #[derive(Clone, Debug, Hash, PartialEq, Eq)]
> pub enum HeadContraint {
> ```

doc variants.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 557 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQKRgydAfj6kCMhS0rX:-NQKRgydAfj6kCMhS0rY:b8o3w3d) ([raw file](https://github.com/starkware-libs/cairo/blob/97b975e40c2d63f7a1ebae5027b9936b273fcbfa/crates/cairo-lang-semantic/src/items/imp.rs#L557)):*
> ```XML
> pub enum HeadContraint {
>     NoConstraint,
>     FirstGenericConstraint(GenericArgumentHead),
> ```

Explain why you only look at the first generic arg.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 562 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQKRSjT7cw7bTwFuU0J:-NQKRSjW6S0z5gYA8RZA:bfihq38) ([raw file](https://github.com/starkware-libs/cairo/blob/97b975e40c2d63f7a1ebae5027b9936b273fcbfa/crates/cairo-lang-semantic/src/items/imp.rs#L562)):*
> ```XML
> 
> /// Query implementation of [crate::db::SemanticGroup::module_impl_ids_for_trait_info].
> pub fn module_impl_ids_for_trait_info(
> ```

As discussed f2f:

s/info/filter/
s/lookup_constraint/filter/

*everywhere*
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 577 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQKPBjGDas_ilo3JwNP:-NQKPBjGDas_ilo3JwNQ:b3fyswy) ([raw file](https://github.com/starkware-libs/cairo/blob/97b975e40c2d63f7a1ebae5027b9936b273fcbfa/crates/cairo-lang-semantic/src/items/imp.rs#L577)):*
> ```XML
>     // TODO(spapini): Index better.
>     for impl_def_id in impls {
>         let item_ok = impl_fits_trait_info(db, impl_def_id, trait_lookup_constraint.clone());
> ```

why clone? Can't you pass a &?



_Code quote:_
```XML
 trait_lookup_constraint.clone()
```
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 578 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQKPIPk1gUwCvkp4Bol:-NQKPIPk1gUwCvkp4Bom:b-apet5n) ([raw file](https://github.com/starkware-libs/cairo/blob/97b975e40c2d63f7a1ebae5027b9936b273fcbfa/crates/cairo-lang-semantic/src/items/imp.rs#L578)):*
> ```XML
>     for impl_def_id in impls {
>         let item_ok = impl_fits_trait_info(db, impl_def_id, trait_lookup_constraint.clone());
>         if let Ok(true) = item_ok {
> ```

inline var



_Code quote:_
```XML
item_ok
```
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 586 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQKP3EQ96-p9SLd_Fiv:-NQKP3EQ96-p9SLd_Fiw:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/97b975e40c2d63f7a1ebae5027b9936b273fcbfa/crates/cairo-lang-semantic/src/items/imp.rs#L586)):*
> ```XML
> }
> 
> fn impl_fits_trait_info(
> ```

doc
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 601 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQKQHKQD4ZppKrsm0Fk:-NQKQHKQD4ZppKrsm0Fl:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/97b975e40c2d63f7a1ebae5027b9936b273fcbfa/crates/cairo-lang-semantic/src/items/imp.rs#L601)):*
> ```XML
>         HeadContraint::FirstGenericConstraint(constraint_head) => {
>             if let Some(first_generic) = first_generic {
>                 if let Some(first_generic_head) = first_generic.head(db) {
> ```





_Suggestion:_
```XML
            let Some(first_generic) = first_generic else {
                return Ok(false);
            }

             if let Some(first_generic_head) = first_generic.head(db) {
                 first_generic_head == constraint_head
             } else {
                 true
             }
    
```

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2443)* status: all files reviewed, 12 unresolved discussions (waiting on @ilyalesokhin-starkware, @spapinistarkware, and @yuvalsw)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2443)* status: 1 of 4 files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 549 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQKNZClAc7QXTiGUXB7:-NQLEIyr-tm0ugkqZkbm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/97b975e40c2d63f7a1ebae5027b9936b273fcbfa/crates/cairo-lang-semantic/src/items/imp.rs#L549)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 552 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQKOO0h9hBbOeDi5FVs:-NQLEKW--x03G73mU_03:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/97b975e40c2d63f7a1ebae5027b9936b273fcbfa/crates/cairo-lang-semantic/src/items/imp.rs#L552)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

constraint on a list of generic arguments?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 555 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQKN__mDTMNA5NFx9vU:-NQLEcJx5XuZEb0wLizj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/97b975e40c2d63f7a1ebae5027b9936b273fcbfa/crates/cairo-lang-semantic/src/items/imp.rs#L555)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

doc variants.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 557 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQKRgydAfj6kCMhS0rX:-NQLEcr0ExhuCkKr4ZIR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/97b975e40c2d63f7a1ebae5027b9936b273fcbfa/crates/cairo-lang-semantic/src/items/imp.rs#L557)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Explain why you only look at the first generic arg.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 562 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQKRSjT7cw7bTwFuU0J:-NQLF2DYAwXOQcHUgCxK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/97b975e40c2d63f7a1ebae5027b9936b273fcbfa/crates/cairo-lang-semantic/src/items/imp.rs#L562)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

As discussed f2f:

s/info/filter/
s/lookup_constraint/filter/

*everywhere*
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 586 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQKP3EQ96-p9SLd_Fiv:-NQLHXcg2FaeO9F34MDg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/97b975e40c2d63f7a1ebae5027b9936b273fcbfa/crates/cairo-lang-semantic/src/items/imp.rs#L586)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2443#-:-NQLP4kBD0xkVGB1iu-X:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 557 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQLOBsSCuagCNLHrC5H:-NQLOBsSCuagCNLHrC5I:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a96ddfa7449fd6c87fd73dc0495d5de3afc463b4/crates/cairo-lang-semantic/src/items/imp.rs#L557)):*
> ```XML
> #[derive(Clone, Debug, Hash, PartialEq, Eq)]
> pub enum GenericsHeadFilter {
>     /// No filter is applied. When nothing is known about th generics, this will lead to a
> ```





_Suggestion:_
```XML
the generics,
```
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 568 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQLOPR00BT9r0iccOLp:-NQLOPR00BT9r0iccOLq:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a96ddfa7449fd6c87fd73dc0495d5de3afc463b4/crates/cairo-lang-semantic/src/items/imp.rs#L568)):*
> ```XML
> 
> /// Query implementation of [crate::db::SemanticGroup::module_impl_ids_for_trait_info].
> pub fn module_impl_ids_for_trait_info(
> ```





_Suggestion:_
```XML
module_impl_ids_for_trait_filter
```
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 604 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2443#-NQLOpQt2n8iWqmkRb-r:-NQLOpQt2n8iWqmkRb-s:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/a96ddfa7449fd6c87fd73dc0495d5de3afc463b4/crates/cairo-lang-semantic/src/items/imp.rs#L604)):*
> ```XML
>     Ok(match &trait_filter.generics_filter {
>         GenericsHeadFilter::NoFilter => true,
>         GenericsHeadFilter::FirstGenericFilter(constraint_head) => {
> ```





_Suggestion:_
```XML
filter
```

**Pull request merged**
