### PR TITLE
Removing direct emit from components.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #4019
- #4013
- #3993
- #4020 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4020)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4020)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 415 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4020#-NdeIBgzBGORwS41UAIZ:-NdeIBgzBGORwS41UAI_:b-isa1ws) ([raw file](https://github.com/starkware-libs/cairo/blob/c2d62a1c9250d1d94939452078f5e5cd26c45725/crates/cairo-lang-starknet/src/plugin/events.rs#L415)):*
> ```XML
>     }
> 
>     data.event_code = RewriteNode::interpolate_patched(
> ```

I think it's better to move this to the contract-specific generation. Here only add the empty event code if needed.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4020)* status: 2 of 17 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 415 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4020#-NdeIBgzBGORwS41UAIZ:-NdeUyV6AR6q9OI8ppfL:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c2d62a1c9250d1d94939452078f5e5cd26c45725/crates/cairo-lang-starknet/src/plugin/events.rs#L415)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I think it's better to move this to the contract-specific generation. Here only add the empty event code if needed.
</blockquote></details>

Done.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4020)* status: all files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 400 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4020#-NdeaPhDBv3u3U2I9m3H:-NdeaPhDBv3u3U2I9m3I:bguyrgi) ([raw file](https://github.com/starkware-libs/cairo/blob/089c7d0db9f1f46c9c854d86e70827e17d543d9a/crates/cairo-lang-starknet/src/plugin/events.rs#L400)):*
> ```XML
> 
> /// Returns the event-emitter code for a contract.
> pub fn event_emitter_code() -> String {
> ```

move to contract.rs
___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 407 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4020#-NdebFgvD4KC_xUGfQ3G:-NdebFgvD4KC_xUGfQ3H:b-geh5fb) ([raw file](https://github.com/starkware-libs/cairo/blob/089c7d0db9f1f46c9c854d86e70827e17d543d9a/crates/cairo-lang-starknet/src/plugin/events.rs#L407)):*
> ```XML
>                 {full_state_struct_name},
>                 {EVENT_TYPE_NAME},
>             > {{
> ```

why did you break this line?



_Code quote:_
```XML
            impl {state_struct_name}EventEmitter{generic_arg_str} of starknet::event::EventEmitter<
                {full_state_struct_name},
                {EVENT_TYPE_NAME},
            > {{
```
___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 425 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4020#-Nde_EjU-f-gWA_i33-b:-Nde_EjU-f-gWA_i33-c:b-v6m1h) ([raw file](https://github.com/starkware-libs/cairo/blob/089c7d0db9f1f46c9c854d86e70827e17d543d9a/crates/cairo-lang-starknet/src/plugin/events.rs#L425)):*
> ```XML
>             state_struct_name = StarknetModuleKind::Contract.get_state_struct_name(),
>             generic_arg_str = StarknetModuleKind::Contract.get_generic_arg_str(),
>             full_state_struct_name = StarknetModuleKind::Contract.get_full_state_struct_name(),
> ```

I suggest to simply write "Contract" in the text now that it's not generic.



_Code quote:_
```XML
            state_struct_name = StarknetModuleKind::Contract.get_state_struct_name(),
            generic_arg_str = StarknetModuleKind::Contract.get_generic_arg_str(),
            full_state_struct_name = StarknetModuleKind::Contract.get_full_state_struct_name(),
```
___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 431 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4020#-Ndec-6d8sCbdnFZjH6S:-Ndec-6d8sCbdnFZjH6T:b-z6e4jk) ([raw file](https://github.com/starkware-libs/cairo/blob/089c7d0db9f1f46c9c854d86e70827e17d543d9a/crates/cairo-lang-starknet/src/plugin/events.rs#L431)):*
> ```XML
> 
> /// Generates the required empty event code if required.
> pub fn generate_empty_event_code(data: &mut StarknetModuleCommonGenerationData, has_event: bool) {
> ```

I would simply call it from outside, only if !has_event, and remove all the if-else from here.



_Code quote:_
```XML
nData, has_event: bool) {
```
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 185 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4020#-NdebRnE513yUTs3JIIh:-NdebRnE513yUTs3JIIi:b-l5btrx) ([raw file](https://github.com/starkware-libs/cairo/blob/089c7d0db9f1f46c9c854d86e70827e17d543d9a/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L185)):*
> ```XML
>                 ("test_config".to_string(), self.test_config),
>                 ("entry_points_code".to_string(), self.entry_points_code.into_rewrite_node()),
>                 ("event_emitter".to_string(), RewriteNode::Text(event_emitter_code())),
> ```

To consolidate with the rest, please add event_emitter as a member in the ContractGenerationData and set it from event_emitter_code(), which should be renamed to generate_event_emitter_code()

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 16 of 16 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4020#-:-NdfLLlkE3ggme4P47gV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4020)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 185 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4020#-NdebRnE513yUTs3JIIh:-NdiM7MGBmCCMNBp8a0b:bn8igac) ([raw file](https://github.com/starkware-libs/cairo/blob/089c7d0db9f1f46c9c854d86e70827e17d543d9a/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L185)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

To consolidate with the rest, please add event_emitter as a member in the ContractGenerationData and set it from event_emitter_code(), which should be renamed to generate_event_emitter_code()
</blockquote></details>

made it a constant, so it makes less sense to make it a member.

**Pull request merged**
