### PR TITLE
Added automatic addition of withdraw_gas calls in cycles

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2560)

### CODE REVIEW

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2560)* status: 13 of 20 files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`corelib/src/lib.cairo` line 198 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2560#-NQzQNLg6XjcdBaqzPKN:-NQzZi2T4Hg9ZDmBlq0t:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/34040f2f490d86150089ddbe4a5f12ffbaf43adb/corelib/src/lib.cairo#L198)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Revert file, these are not top level by design.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/add_withdraw_gas/mod.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2560#-NQzTsyDAmvikwvgbNnt:-NQzZb5I7yWl9QNC2QWF:b-7zi8tj) ([raw file](https://github.com/starkware-libs/cairo/blob/34040f2f490d86150089ddbe4a5f12ffbaf43adb/crates/cairo-lang-lowering/src/add_withdraw_gas/mod.rs#L44)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Attempt to be only dependent on the inner location of the decl, without the usages
</blockquote></details>

WDYM?

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2560)* status: 14 of 20 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/add_withdraw_gas/mod.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2560#-NQzTsyDAmvikwvgbNnt:-NR-CZ0p3QDvEyw_PiFq:bf6ulw1) ([raw file](https://github.com/starkware-libs/cairo/blob/34040f2f490d86150089ddbe4a5f12ffbaf43adb/crates/cairo-lang-lowering/src/add_withdraw_gas/mod.rs#L44)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

WDYM?
</blockquote></details>

Exactly what you did now

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2560)* status: 14 of 20 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`examples/lib.cairo` line 8 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2560#-NR-Qs2O306kOdIlW20g:-NR-Qs2O306kOdIlW20h:b-hcpynd) ([raw file](https://github.com/starkware-libs/cairo/blob/ee2eb0dae790ba225b62adcc263da849ee441cfc/examples/lib.cairo#L8)):*
> ```Cairo
> mod fib_caller;
> mod fib_counter;
> mod fib_gas;
> ```

Deleted since all have gas now?
___
*[`tests/test_data/fib_auto_gas.casm` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2560#-NR-R0Ff5xomYEkS53P5:-NR-R0Ff5xomYEkS53P6:bt5hn6d) ([raw file](https://github.com/starkware-libs/cairo/blob/8a2846ea2f03795cc85a2d295152480532e1c81d/tests/test_data/fib_auto_gas.casm#L1)):*
> ```
> %{ memory[ap + 0] = 2170 <= memory[fp + -6] %}
> ```

Where's the original file?

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2560)* status: 14 of 20 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`tests/examples_test.rs` line 136 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2560#-NR2Upm34OCDajQW-hCn:-NR2Upm34OCDajQW-hCo:b-gxuzen) ([raw file](https://github.com/starkware-libs/cairo/blob/a29cbe1aeb2a6bd7c8bb59fbf1a2de6075867078/tests/examples_test.rs#L136)):*
> ```XML
> #[case::corelib_usage("corelib_usage", false)]
> #[case::hash_chain("hash_chain", false)]
> #[case::hash_chain_gas("hash_chain_gas", true)]
> ```

move this to the other gas example, and remove the bool



_Code quote:_
```XML
#[case::hash_chain_gas("hash_chain_gas", true)]
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2560)* status: 14 of 20 files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`examples/lib.cairo` line 8 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2560#-NR-Qs2O306kOdIlW20g:-NR2RL2w0FWe1uRS_srf:bz0u3nm) ([raw file](https://github.com/starkware-libs/cairo/blob/ee2eb0dae790ba225b62adcc263da849ee441cfc/examples/lib.cairo#L8)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Deleted since all have gas now?
</blockquote></details>

I used fib.cairo instead, once with the flag unset, and once with the flag set (which is equivalent to the previous fib_gas).
___
*[`tests/examples_test.rs` line 136 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2560#-NR2Upm34OCDajQW-hCn:-NR2_7SyDXNMMkr8uQkz:bswll4p) ([raw file](https://github.com/starkware-libs/cairo/blob/a29cbe1aeb2a6bd7c8bb59fbf1a2de6075867078/tests/examples_test.rs#L136)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

move this to the other gas example, and remove the bool
</blockquote></details>

There is a difference - most don't need gas at all (false bool here). hash_chain_gas can't be automatically added as it uses withdraw_gas_all. And the other test adds withdraw_gas automatically.
I can remove the bool by splitting to another test (1 - no gas, 2 - manual gas, 3 - auto gas).
___
*[`tests/test_data/fib_auto_gas.casm` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2560#-NR-R0Ff5xomYEkS53P5:-NR2SOYw8c0jFzVNGSLn:b-h3i6qm) ([raw file](https://github.com/starkware-libs/cairo/blob/8a2846ea2f03795cc85a2d295152480532e1c81d/tests/test_data/fib_auto_gas.casm#L1)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Where's the original file?
</blockquote></details>

Thanks. Now deleted (both fib_gas.sierra and fib_gas.casm)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2560)* status: 17 of 20 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware and @yuvalsw)

___
*[`tests/examples_test.rs` line 116 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2560#-NR2bO-88PRkjqstcbau:-NR2bO-88PRkjqstcbav:bfohsi3) ([raw file](https://github.com/starkware-libs/cairo/blob/a29cbe1aeb2a6bd7c8bb59fbf1a2de6075867078/tests/examples_test.rs#L116)):*
> ```XML
> fn cairo_to_sierra_auto_gas(#[case] name: &str, example_dir_data: &ExampleDirData) {
>     compare_contents_or_fix(
>         &format!("{name}_auto_gas"),
> ```

just so the test files would remain the same



_Suggestion:_
```XML
        &format!("{name}_gas"),
```
___
*[`tests/examples_test.rs` line 136 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2560#-NR2Upm34OCDajQW-hCn:-NR2aHMTAVss4nLn5cMp:b-e2mxv4) ([raw file](https://github.com/starkware-libs/cairo/blob/a29cbe1aeb2a6bd7c8bb59fbf1a2de6075867078/tests/examples_test.rs#L136)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

There is a difference - most don't need gas at all (false bool here). hash_chain_gas can't be automatically added as it uses withdraw_gas_all. And the other test adds withdraw_gas automatically.
I can remove the bool by splitting to another test (1 - no gas, 2 - manual gas, 3 - auto gas).
</blockquote></details>

you should add all gas types - but i guess this is a followup pr.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2560)* status: 16 of 20 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`tests/examples_test.rs` line 116 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2560#-NR2bO-88PRkjqstcbau:-NR36xF19lJLe0XyuovR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a29cbe1aeb2a6bd7c8bb59fbf1a2de6075867078/tests/examples_test.rs#L116)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

just so the test files would remain the same
</blockquote></details>

Done.
___
*[`tests/examples_test.rs` line 136 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2560#-NR2Upm34OCDajQW-hCn:-NR36XzdEzAZjOe5YjL0:b-81la7d) ([raw file](https://github.com/starkware-libs/cairo/blob/a29cbe1aeb2a6bd7c8bb59fbf1a2de6075867078/tests/examples_test.rs#L136)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you should add all gas types - but i guess this is a followup pr.
</blockquote></details>

Right

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, 3 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2560#-:-NR3CO6n7H9hxfwpfr0g:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2560)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 142 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2560#-NR3VVop1rMgY3es-GdJ:-NR3VVop1rMgY3es-GdK:b-e79muu) ([raw file](https://github.com/starkware-libs/cairo/blob/5c45c3500e10154bf4659c678f54294599ea3461/crates/cairo-lang-lowering/src/lower/context.rs#L142)):*
> ```XML
> 
>     /// Creates a new variable according to the context.
>     fn create_new_var(&self, req: VarRequest) -> Variable {
> ```

maybe rename and just call it directly? (instead of `new_var_external_arena`)



_Suggestion:_
```XML
fn unallocated_new_var(&self, req: VarRequest) -> Variable {
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2560)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/add_withdraw_gas/mod.rs` line 94 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2560#-NR3Vs2w9ftt8_WYr7ev:-NR3Vs2w9ftt8_WYr7ew:b-8oli0s) ([raw file](https://github.com/starkware-libs/cairo/blob/5c45c3500e10154bf4659c678f54294599ea3461/crates/cairo-lang-lowering/src/add_withdraw_gas/mod.rs#L94)):*
> ```XML
>     let lowering_context = lowering_builder.ctx()?;
> 
>     let new_array_var = lowering_context.new_var_external_arena(
> ```

can you explain (and doc) why is this need all around here?



_Code quote:_
```XML
new_var_external_arena
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2560)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/add_withdraw_gas/mod.rs` line 94 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2560#-NR3Vs2w9ftt8_WYr7ev:-NR44Ln31lbiu1DwBEAp:bd64g53) ([raw file](https://github.com/starkware-libs/cairo/blob/5c45c3500e10154bf4659c678f54294599ea3461/crates/cairo-lang-lowering/src/add_withdraw_gas/mod.rs#L94)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can you explain (and doc) why is this need all around here?
</blockquote></details>

The .ctx() creates a new arena with no variables.
normal .new_var() would add variables to it and won't affect `lowered`. This would panic in next phases when trying to access the "wrong" arena.
This function asks to add the new variables to the given arena. The context is needed to be able to create the variable with its type info according to the function.

Do you feel like this/some of this explanation should be here or on the new_var_external_arena function?
Also - I can split the addition of `new_var_external_arena` to a separate PR if that helps (I needed it because of the rebase - it made creation of new variables more difficult without a lowering context).
___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 142 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2560#-NR3VVop1rMgY3es-GdJ:-NR46EV3DDvwlWmCLPFY:bm5bi3c) ([raw file](https://github.com/starkware-libs/cairo/blob/5c45c3500e10154bf4659c678f54294599ea3461/crates/cairo-lang-lowering/src/lower/context.rs#L142)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe rename and just call it directly? (instead of `new_var_external_arena`)
</blockquote></details>

I think the name remain correct as pub too. I changes as suggested - not sure if it looks better though.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2560#-:-NR4EfM-3Be_PRgen6Kl:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/add_withdraw_gas/mod.rs` line 94 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2560#-NR3Vs2w9ftt8_WYr7ev:-NR4EO0v-dwgTQXnuNdq:b-gm0rb8) ([raw file](https://github.com/starkware-libs/cairo/blob/5c45c3500e10154bf4659c678f54294599ea3461/crates/cairo-lang-lowering/src/add_withdraw_gas/mod.rs#L94)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

The .ctx() creates a new arena with no variables.
normal .new_var() would add variables to it and won't affect `lowered`. This would panic in next phases when trying to access the "wrong" arena.
This function asks to add the new variables to the given arena. The context is needed to be able to create the variable with its type info according to the function.

Do you feel like this/some of this explanation should be here or on the new_var_external_arena function?
Also - I can split the addition of `new_var_external_arena` to a separate PR if that helps (I needed it because of the rebase - it made creation of new variables more difficult without a lowering context).
</blockquote></details>

no need for the split - just add here a single doc line describing why you add it directly.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2560)* status: 20 of 21 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/add_withdraw_gas/mod.rs` line 94 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2560#-NR3Vs2w9ftt8_WYr7ev:-NRSNNBy9d44DNuQMRCN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5c45c3500e10154bf4659c678f54294599ea3461/crates/cairo-lang-lowering/src/add_withdraw_gas/mod.rs#L94)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no need for the split - just add here a single doc line describing why you add it directly.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2560)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
