### PR TITLE
Enabled errors on unused variables.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #4462
- #4459
- #4457 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4457)

### CODE REVIEW

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4457)* status: 0 of 53 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4457#-Njvlva91riZEyS-z8wW:-Njvlva91riZEyS-z8wX:b-1uf6dk) (no related file):*
Errors? Has this been discussed with the community members, and has feedback been gathered about this idea?

I believe most languages implement this as warnings; the only language I know that emits fatal errors is Golang, so I expect this to be a rather unexpected behaviour.

My personal feedback is that this should be a warning, as I tend to often leave unfinished code and run tests over it. But I'm happy to hear others voice!

___

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4457)* status: 0 of 53 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @mkaput)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4457#-Njvlva91riZEyS-z8wW:-Njvn21F6tWRwBMH2PUM:b-d9r194) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Errors? Has this been discussed with the community members, and has feedback been gathered about this idea?

I believe most languages implement this as warnings; the only language I know that emits fatal errors is Golang, so I expect this to be a rather unexpected behaviour.

My personal feedback is that this should be a warning, as I tend to often leave unfinished code and run tests over it. But I'm happy to hear others voice!
</blockquote></details>

since it is very easy to prevent the error (just adding an `_` before) - I see no reason for this to not be an error.
warning are currently not a concept we have - and i see no reason to add it just for that.

___

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 53 of 53 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4457#-:-NjvoX7_4EMfYjKtGQmQ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4457)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4457#-Njvlva91riZEyS-z8wW:-NjvnueF0Ktb9rs-z11s:bqevces) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

since it is very easy to prevent the error (just adding an `_` before) - I see no reason for this to not be an error.
warning are currently not a concept we have - and i see no reason to add it just for that.
</blockquote></details>

I understand the implementation reasons for this, but I just want to say, that even this simple fix with `_` requires manual work in the code. It will have a tendency to kick the developer out of their flow of thought (for example, in the scenario I outlined in the previous comment). That's a subtle UX inconvenience, that may affect users' perception of the language.

I, honestly, strongly suggest gathering community feedback before releasing this.

___

**Comment by milancermak** [comment]
100% agree with what Marek said. This shouldn't be an error.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4457)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4457#-Njvlva91riZEyS-z8wW:-Njvu1pO1zVTylfOWHAy:b-sc756v) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I understand the implementation reasons for this, but I just want to say, that even this simple fix with `_` requires manual work in the code. It will have a tendency to kick the developer out of their flow of thought (for example, in the scenario I outlined in the previous comment). That's a subtle UX inconvenience, that may affect users' perception of the language.

I, honestly, strongly suggest gathering community feedback before releasing this.
</blockquote></details>

makes sense - pre-adding a warning concept.

___

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4457)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4457#-Njvlva91riZEyS-z8wW:-Njvy7wy46K4nNt1fpjM:b-d1w28p) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

makes sense - pre-adding a warning concept.
</blockquote></details>

happens in the following PR.
the PR after it will be removing the edition dependency from it.
scarb wrapper will need to support skipping the diagnostics for these cases.

___

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 53 of 53 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4457#-:-Njw7Sfq19-JTQc7lIzV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by gilbens-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4457)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
