### PR TITLE
Add fill_circuit_input.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5505)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5505)* status: 8 of 9 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/circuit.cairo` line 27 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5505#-NwtSH9r3_9ZNo3BjpF0:-NwtSH9r3_9ZNo3BjpF1:bbzetod) ([raw file](https://github.com/starkware-libs/cairo/blob/b9d697adfd332e2021ccbb1c3102e8354db20391/corelib/src/circuit.cairo#L27)):*
> ```Cairo
> /// Fill an input in the circuit instance's data.
> extern fn fill_circuit_input<C>(
>     accumulator: CircuitInputAccumulator<C>, value: [u96; 4]
> ```

maybe add the `RangeCheck96Guarantee` type - with just an implementation for cast from u96?
this would be as efficient without a need for `fill_circuit_input` duplication.



_Code quote:_
```Cairo
    accumulator: CircuitInputAccumulator<C>, value: [u96; 4]
```
___
*[`corelib/src/test/circuit_test.cairo` line 27 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5505#-NwtQm55CPhp2vyY69ob:-NwtQm55CPhp2vyY69oc:b-myj1nb) ([raw file](https://github.com/starkware-libs/cairo/blob/b9d697adfd332e2021ccbb1c3102e8354db20391/corelib/src/test/circuit_test.cairo#L27)):*
> ```Cairo
> use core::circuit::{
>     AddModGate, fill_circuit_input, FillInputResult, CircuitInputAccumulator, init_circuit_data
> };
> ```

any reason not to merge with the other `use`s?



_Code quote:_
```Cairo
use core::circuit::{
    AddModGate, fill_circuit_input, FillInputResult, CircuitInputAccumulator, init_circuit_data
};
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5505#-NwtT-NsE5_ymhedBnT_:-NwtT-NsE5_ymhedBnTa:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b9d697adfd332e2021ccbb1c3102e8354db20391/crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs#L11)):*
> ```XML
> 
> // The number of limbs used to represent a single value in the circuit.
> const VALUE_SIZE: usize = 4;
> ```





_Suggestion:_
```XML
/// The number of limbs used to represent a single value in the circuit.
const VALUE_SIZE: usize = 4;
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5505#-NwtUN4VB84647BCK4Vr:-NwtUN4VB84647BCK4Vs:bxoyhr1) ([raw file](https://github.com/starkware-libs/cairo/blob/b9d697adfd332e2021ccbb1c3102e8354db20391/crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs#L77)):*
> ```XML
>         jump More if new_len != 0;
>         jump Failure;
>         More:
> ```

if we use the end_ptr for comparison it would generate code without the 4 imm here - which would be a bit smaller - no?



_Code quote:_
```XML
        tempvar new_ptr = ptr;
        tempvar new_len = len - element_size;
        jump More if new_len != 0;
        jump Failure;
        More:
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5505)* status: 8 of 9 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/test/circuit_test.cairo` line 27 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5505#-NwtQm55CPhp2vyY69ob:-NwtZJi1Br_R2Kw4POP1:brpmqc3) ([raw file](https://github.com/starkware-libs/cairo/blob/b9d697adfd332e2021ccbb1c3102e8354db20391/corelib/src/test/circuit_test.cairo#L27)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

any reason not to merge with the other `use`s?
</blockquote></details>

removed.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5505#-NwtT-NsE5_ymhedBnT_:-NwtZIPR0ZIO9Qa-6TlN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b9d697adfd332e2021ccbb1c3102e8354db20391/crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs#L11)):*
> ```XML
> 
> // The number of limbs used to represent a single value in the circuit.
> const VALUE_SIZE: usize = 4;
> ```

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5505#-NwtUN4VB84647BCK4Vr:-NwtZJ1O-yS3XkXT14Bf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b9d697adfd332e2021ccbb1c3102e8354db20391/crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs#L77)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

if we use the end_ptr for comparison it would generate code without the 4 imm here - which would be a bit smaller - no?
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5505)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs` line 67 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5505#-Nwtb_LEAU0a1uNmvnCx:-Nwtb_LEAU0a1uNmvnCy:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8f22ff09b558af19aca433bec55c527b2c9746ef/crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs#L67)):*
> ```XML
>         buffer(elem.cells.len() as i16) start;
>         deref end;
>     };
> ```





_Suggestion:_
```XML
    let mut casm_builder = CasmBuilder::default();
    add_input_variables! {casm_builder,
        buffer(elem.cells.len() as i16) start;
        deref end;
    };
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5505)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/circuit.cairo` line 27 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5505#-NwtSH9r3_9ZNo3BjpF0:-Nx6Scbi-zfqY672-1Gq:bpymbr3) ([raw file](https://github.com/starkware-libs/cairo/blob/b9d697adfd332e2021ccbb1c3102e8354db20391/corelib/src/circuit.cairo#L27)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe add the `RangeCheck96Guarantee` type - with just an implementation for cast from u96?
this would be as efficient without a need for `fill_circuit_input` duplication.
</blockquote></details>

we've decided to do it later, right?
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs` line 67 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5505#-Nwtb_LEAU0a1uNmvnCx:-Nx6SfAU1JKFBk0aRub1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8f22ff09b558af19aca433bec55c527b2c9746ef/crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs#L67)):*
> ```XML
>         buffer(elem.cells.len() as i16) start;
>         deref end;
>     };
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5505)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/circuit.cairo` line 26 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5505#-Nx6VknU2dlJt2da97b7:-Nx6VknVBFo86ywYv_NR:b-y6495d) ([raw file](https://github.com/starkware-libs/cairo/blob/990eda69360d6878d75b019e02f8c530089f5240/corelib/src/circuit.cairo#L26)):*
> ```Cairo
> 
> /// Fill an input in the circuit instance's data.
> // TODO(ilya): Condider using RangeCheck96Guarantee for the inputs.
> ```

even if we decide to postpone actually doing it for later - we should probably just have a simple libfunc for converting u96s into it directly (as it requires no actual code), but can wait for now.



_Suggestion:_
```Cairo
// TODO(ilya): Consider using RangeCheck96Guarantee for the inputs.
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5505#-:-Nx6cTSHEPtKWvPs0_pb:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
