### PR TITLE
Update contributing: CAIRO_FIX_TESTS flag

### PR DESCRIPTION
**Pull request by gaetbout**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2179)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2179)* status: all files reviewed, 1 unresolved discussion (waiting on @gaetbout)

___
*[`docs/CONTRIBUTING.md` line 23 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2179#-NOZarYJBanzTvxtlagj:-NOZarYK67AzqoomSHBm:b-badfoy) ([raw file](https://github.com/starkware-libs/cairo/blob/1e8576428c5f278ec987a54fa93266ccc909de79/docs/CONTRIBUTING.md#L23)):*
> ```Markdown
> 
> If you have a lot of failing tests when running:  
> `cargo test`  
> ```

These are weird whitespaces. Are those windows \r\n ? Can you make it normal?

**Comment by gaetbout** [comment]
The two spaces at the end of a line are just there to force the line break.
Is this what you were referring to?

**Review by spapinistarkware — COMMENTED** [review]
Oh, I see! thanks.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2179#-:-NO_1Izy9ego5WxBoloK:bhzsqk)* status: all files reviewed, 1 unresolved discussion (waiting on @gaetbout)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2179#-:-NO_1LjF8BcdoJ5oA0oz:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gaetbout)

**Pull request merged**
