### PR TITLE
Added documentation of structs

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3101)

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3101)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3101)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/structs.adoc` line 96 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3101#-NV-kRiz37aeUkz2KPrn:-NV01VTX1S4XmUaZNcGq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/86e0d45f7a302d76dfc9adfe125ce15d1cd36b05/docs/reference/src/components/cairo/modules/language_constructs/pages/structs.adoc#L96)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

also mention that multiple assignments of fields cost (at a single context) causes only a single restructure.
</blockquote></details>

Done.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3101)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/structs.adoc` line 102 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3101#-NV06QP-Ei8VLCTzlGA7:-NV0BmTS1Es0YGEjgbZX:b-me3uiv) ([raw file](https://github.com/starkware-libs/cairo/blob/739cbc0245a41b1ab19222abcc6747df55427647/docs/reference/src/components/cairo/modules/language_constructs/pages/structs.adoc#L102)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it doesn't copy the struct memory twice - it restructures it exactly once.
</blockquote></details>

Tried to rephrase, PTAL

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3101#-:-NV0DqLbBjox-b-1L4Wb:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3101)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
