### PR TITLE
LS: New Project Model MVP

### PR DESCRIPTION
**Pull request by mkaput**
**Stack**:
- #6034
- #6009 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
> Reviewed 10 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6009)* status: 10 of 11 files reviewed, 5 unresolved discussions (waiting on @Draggu and @mkaput)

___
*[`crates/cairo-lang-language-server/src/project/db.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6009#-O1VV7N-DYmBztnd-3dU:-O1VV7N-DYmBztnd-3dV:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c8e295e15ca0c9765773a7467290d96f931bba1e/crates/cairo-lang-language-server/src/project/db.rs#L103)):*
> ```XML
>     /// Set up database input according to the current state of projects.
> 
>     pub fn apply(&self, db: &mut AnalysisDatabase) {
> ```





_Suggestion:_
```XML
    /// Set up database input according to the current state of projects.
    pub fn apply(&self, db: &mut AnalysisDatabase) {
```
___
*[`crates/cairo-lang-language-server/src/project/db.rs` line 142 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6009#-O1VV5_g6Xg8dmNvNKq4:-O1VV5_g6Xg8dmNvNKq5:bb7f2bf) ([raw file](https://github.com/starkware-libs/cairo/blob/c8e295e15ca0c9765773a7467290d96f931bba1e/crates/cairo-lang-language-server/src/project/db.rs#L142)):*
> ```XML
> }
> 
> fn is_cairo_file(path: &Path) -> bool {
> ```

doc.
___
*[`crates/cairo-lang-language-server/src/project/main.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6009#-O1VViWmA7aQVrx20wWS:-O1VViWnBVI2IwIMZNzR:b-31gwab) ([raw file](https://github.com/starkware-libs/cairo/blob/c8e295e15ca0c9765773a7467290d96f931bba1e/crates/cairo-lang-language-server/src/project/main.rs#L20)):*
> ```XML
>     lookup_intern_project,
>     intern_project
> );
> ```

add `Ord` specifically here.



_Code quote:_
```XML
define_short_id!(
    ProjectId,
    ProjectManifestPath,
    LsProjectsGroup,
    lookup_intern_project,
    intern_project
);
```
___
*[`crates/cairo-lang-language-server/src/project/main.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6009#-O1VWC-J7GpL-un3iuIu:-O1VWC-J7GpL-un3iuIv:bql08s4) ([raw file](https://github.com/starkware-libs/cairo/blob/c8e295e15ca0c9765773a7467290d96f931bba1e/crates/cairo-lang-language-server/src/project/main.rs#L36)):*
> ```XML
>     /// This list is highly dynamic and must be maintained externally to the query system.
>     #[salsa::input]
>     fn open_projects(&self) -> Arc<BTreeSet<ProjectId>>;
> ```

Using OrderedHashSet is probably going to be good enough.
assuming this list does not get reordered all the time.



_Code quote:_
```XML
    fn open_projects(&self) -> Arc<BTreeSet<ProjectId>>;
```
___
*[`crates/cairo-lang-utils/src/lib.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6009#-O1VUwNX0unwj3cjDeKT:-O1VUwNX0unwj3cjDeKU:b-hfpv23) ([raw file](https://github.com/starkware-libs/cairo/blob/c8e295e15ca0c9765773a7467290d96f931bba1e/crates/cairo-lang-utils/src/lib.rs#L103)):*
> ```XML
> macro_rules! define_short_id {
>     ($short_id:ident, $long_id:path, $db:ident, $lookup:ident, $intern:ident) => {
>         #[derive(Copy, Clone, Debug, Hash, PartialEq, Eq, PartialOrd, Ord)]
> ```

remove.

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6009)* status: 7 of 11 files reviewed, 5 unresolved discussions (waiting on @Draggu and @orizi)

___
*[`crates/cairo-lang-language-server/src/project/db.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6009#-O1VV7N-DYmBztnd-3dU:-O1WfYY1C-vGNuHeBLjU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bfc4647aae3e83916481afd2ab8d324b67b42187/crates/cairo-lang-language-server/src/project/db.rs#L103)):*
> ```XML
>     /// Set up database input according to the current state of projects.
> 
>     pub fn apply(&self, db: &mut AnalysisDatabase) {
> ```

Done.
___
*[`crates/cairo-lang-language-server/src/project/db.rs` line 142 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6009#-O1VV5_g6Xg8dmNvNKq4:-O1Wgd7W9CxcfqZhOBfa:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bfc4647aae3e83916481afd2ab8d324b67b42187/crates/cairo-lang-language-server/src/project/db.rs#L142)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/project/main.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6009#-O1VViWmA7aQVrx20wWS:-O1WfucxAM1jESrmApBc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bfc4647aae3e83916481afd2ab8d324b67b42187/crates/cairo-lang-language-server/src/project/main.rs#L20)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add `Ord` specifically here.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/project/main.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6009#-O1VWC-J7GpL-un3iuIu:-O1Wfuux6RTjGn3C_QkY:bz5py0o) ([raw file](https://github.com/starkware-libs/cairo/blob/bfc4647aae3e83916481afd2ab8d324b67b42187/crates/cairo-lang-language-server/src/project/main.rs#L36)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Using OrderedHashSet is probably going to be good enough.
assuming this list does not get reordered all the time.
</blockquote></details>

Good idea! Done.
___
*[`crates/cairo-lang-utils/src/lib.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6009#-O1VUwNX0unwj3cjDeKT:-O1Wfj6i1h_YaVzM_MUm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bfc4647aae3e83916481afd2ab8d324b67b42187/crates/cairo-lang-utils/src/lib.rs#L103)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6009#-:-O1Wp5Le8-kAW4VT5pDD:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Draggu)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6009)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Draggu)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6009#-:-O3R5XB55G7D8y-0ZJxZ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Draggu)

**Pull request closed without merging**
