### PR TITLE
Change array_get to return a box.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2495)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 9 of 13 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2495)* status: 10 of 13 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`corelib/src/array.cairo` line 12 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2495#-NQ_kbzE5gL9-RxYjhNq:-NQ_kbzE5gL9-RxYjhNr:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/06374811a4f92cb5fc2a591e9433bb15a05bce86/corelib/src/array.cairo#L12)):*
> ```Cairo
>     arr: @Array<T>, index: usize
> ) -> Option<Box<@T>> implicits(RangeCheck) nopanic;
> extern fn array_len<T>(arr: @Array<T>) -> usize nopanic;
> ```





_Suggestion:_
```Cairo
) -> Option<Box<@T>> implicits(RangeCheck) nopanic;
extern fn array_len<T>(arr: @Array<T>) -> usize nopanic;

trait ArrayTrait<T> {
    fn new() -> Array<T>;
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 209 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2495#-NQ_lpZ28ec_vmK78_g5:-NQ_lpZ28ec_vmK78_g6:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/06374811a4f92cb5fc2a591e9433bb15a05bce86/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L209)):*
> ```XML
>                     OutputVarInfo {
>                         ty: boxed_ty(context, snapshot_ty(context, ty)?)?,
>                         ref_info: OutputVarReferenceInfo::NewTempVar { idx: Some(0) },
> ```





_Suggestion:_
```XML
                        ty: boxed_ty(context, snapshot_ty(context, ty)?)?,
                        ref_info: OutputVarReferenceInfo::Deferred(...Generic),
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/array.rs` line 159 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2495#-NQ_lfOF2y0cqxv4X-3S:-NQ_lfOF2y0cqxv4X-3T:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/06374811a4f92cb5fc2a591e9433bb15a05bce86/crates/cairo-lang-sierra-to-casm/src/invocations/array.rs#L159)):*
> ```XML
>         assert offset_length_diff = *(range_check++);
>         // Compute address of target cell.
>         tempvar target_cell = arr_start + element_offset_in_cells;
> ```





_Suggestion:_
```XML
        // The start address of target cells.
        let target_cell = arr_start + element_offset_in_cells;
    };
    let failure_handle = get_non_fallthrough_statement_id(&builder);
    Ok(builder.build_from_casm_builder(
        casm_builder,
        [
            ("Fallthrough", &[&[range_check], &[target_cell]], None),
            ("FailureHandle", &[&[range_check]], Some(failure_handle)),
        ],
        CostValidationInfo {
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2495)* status: 10 of 13 files reviewed, 3 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 209 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2495#-NQ_lpZ28ec_vmK78_g5:-NQ_xHqb3EuAwRPDZJmj:b-h9f0vi) ([raw file](https://github.com/starkware-libs/cairo/blob/06374811a4f92cb5fc2a591e9433bb15a05bce86/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L209)):*
> ```XML
>                     OutputVarInfo {
>                         ty: boxed_ty(context, snapshot_ty(context, ty)?)?,
>                         ref_info: OutputVarReferenceInfo::NewTempVar { idx: Some(0) },
> ```

its written to a tempvar here:
https://github.com/starkware-libs/cairo/blob/06374811a4f92cb5fc2a591e9433bb15a05bce86/crates/cairo-lang-sierra-to-casm/src/invocations/array.rs#L159

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2495)* status: all files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2495)* status: 7 of 15 files reviewed, 3 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`corelib/src/array.cairo` line 12 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2495#-NQ_kbzE5gL9-RxYjhNq:-NQdLBWE1deRZKeC4-oi:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/06374811a4f92cb5fc2a591e9433bb15a05bce86/corelib/src/array.cairo#L12)):*
> ```Cairo
>     arr: @Array<T>, index: usize
> ) -> Option<Box<@T>> implicits(RangeCheck) nopanic;
> extern fn array_len<T>(arr: @Array<T>) -> usize nopanic;
> ```

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/array.rs` line 159 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2495#-NQ_lfOF2y0cqxv4X-3S:-NQdLGMtBOgWYQMUYiaK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/06374811a4f92cb5fc2a591e9433bb15a05bce86/crates/cairo-lang-sierra-to-casm/src/invocations/array.rs#L159)):*
> ```XML
>         assert offset_length_diff = *(range_check++);
>         // Compute address of target cell.
>         tempvar target_cell = arr_start + element_offset_in_cells;
> ```

Done.

**Pull request merged**
