### PR TITLE
feat: Implement One Trait Analogous to Rust's in Cairo

### PR DESCRIPTION
**Pull request by neotheprogramist**
Fixing https://github.com/starkware-libs/cairo/issues/3881

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3891)

### CODE REVIEW

**Review by LucasLvy — CHANGES_REQUESTED** [review]

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3891)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @LucasLvy and @neotheprogramist)

___
*[`corelib/src/one.cairo` line 9 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3891#-Nbtwt3J9hGbG2c5FK_8:-Nbtwt3J9hGbG2c5FK_9:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/33c527dba6e856dbedf57a660bf435727910ae09/corelib/src/one.cairo#L9)):*
> ```Cairo
>     fn is_one(self: T) -> bool;
>     /// Returns whether self is not equal to 1, the multiplicative identity element.
>     fn is_non_one(self: T) -> bool;
> ```





_Suggestion:_
```Cairo
    /// Returns whether self is equal to 1, the multiplicative identity element.
    fn is_one(self: @T) -> bool;
    /// Returns whether self is not equal to 1, the multiplicative identity element.
    fn is_non_one(self: @T) -> bool;
```

**Review by LucasLvy — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3891#-:-NcMNuyh6KSJWU6iajSR:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @neotheprogramist and @orizi)

**Comment by neotheprogramist** [comment]
> > Reviewed all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3891)_ status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @LucasLvy and @neotheprogramist)
> 
> _[`corelib/src/one.cairo` line 9 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3891#-Nbtwt3J9hGbG2c5FK_8:-Nbtwt3J9hGbG2c5FK_9:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/33c527dba6e856dbedf57a660bf435727910ae09/corelib/src/one.cairo#L9)):_
> 
> > ```cairo
> >     fn is_one(self: T) -> bool;
> >     /// Returns whether self is not equal to 1, the multiplicative identity element.
> >     fn is_non_one(self: T) -> bool;
> > ```
> 
> _Suggestion:_
> 
> ```cairo
>     /// Returns whether self is equal to 1, the multiplicative identity element.
>     fn is_one(self: @T) -> bool;
>     /// Returns whether self is not equal to 1, the multiplicative identity element.
>     fn is_non_one(self: @T) -> bool;
> ```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3891)* status: all files reviewed, 3 unresolved discussions (waiting on @neotheprogramist)

___
*[`corelib/src/one.cairo` line 3 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3891#-NcXeMnX6UGW8QCSGn-8:-NcXeMnX6UGW8QCSGn-9:b-spzh5m) ([raw file](https://github.com/starkware-libs/cairo/blob/16813180f61e85259e087a36e95a65c2710b6f6b/corelib/src/one.cairo#L3)):*
> ```Cairo
> // === One ===
> 
> trait One<T> {
> ```

i thing we should think more about where to actually put this file - as we want to add zero as a substitute for Zeroable as well.
___
*[`corelib/src/one.cairo` line 9 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3891#-NcXeYC0AaSufkLMpeBl:-NcXeYC0AaSufkLMpeBm:bubrgkr) ([raw file](https://github.com/starkware-libs/cairo/blob/16813180f61e85259e087a36e95a65c2710b6f6b/corelib/src/one.cairo#L9)):*
> ```Cairo
>     fn is_one(self: @T) -> bool;
>     /// Returns whether self is not equal to 1, the multiplicative identity element.
>     fn is_non_one(self: @T) -> bool;
> ```

let us remove for now - and be similar to rust (rust has a set function as well, but it is less relevant for our case)



_Code quote:_
```Cairo
    /// Returns whether self is not equal to 1, the multiplicative identity element.
    fn is_non_one(self: @T) -> bool;
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3891)* status: all files reviewed, 4 unresolved discussions (waiting on @neotheprogramist)

___
*[`corelib/src/one.cairo` line 3 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3891#-NcXeqZk4cO63k4GSuDp:-NcXeqZk4cO63k4GSuDq:biwrre3) ([raw file](https://github.com/starkware-libs/cairo/blob/16813180f61e85259e087a36e95a65c2710b6f6b/corelib/src/one.cairo#L3)):*
> ```Cairo
> // === One ===
> 
> trait One<T> {
> ```

and maybe also to match the general meaning of `1`ness?



_Suggestion:_
```Cairo
trait One<T, impl MulT: Mul<T>> {
```

**Review by neotheprogramist — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3891)* status: all files reviewed, 4 unresolved discussions (waiting on @LucasLvy and @orizi)

___
*[`corelib/src/integer.cairo` line 1871 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3891#gh-1293273953:-Nc14gPsEtp35wmh5f9G:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0859e532c8b53fc09f57a93f4e33f2f7a2d66a6e/corelib/src/integer.cairo#L1871)):*
<details><summary><i>Previously, LucasLvy (Lucas @ StarkWare) wrote…</i></summary><blockquote>

Inline this as well
</blockquote></details>

Done.
___
*[`corelib/src/one.cairo` line 9 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3891#-Nbtwt3J9hGbG2c5FK_8:-Nc14lDK72vcWFRZEnin:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/33c527dba6e856dbedf57a660bf435727910ae09/corelib/src/one.cairo#L9)):*
> ```Cairo
>     fn is_one(self: T) -> bool;
>     /// Returns whether self is not equal to 1, the multiplicative identity element.
>     fn is_non_one(self: T) -> bool;
> ```

Done.
___
*[`corelib/src/one.cairo` line 3 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3891#-NcXeMnX6UGW8QCSGn-8:-NchR9Sy8VTk4hKQHaFb:b1sb0g2) ([raw file](https://github.com/starkware-libs/cairo/blob/16813180f61e85259e087a36e95a65c2710b6f6b/corelib/src/one.cairo#L3)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i thing we should think more about where to actually put this file - as we want to add zero as a substitute for Zeroable as well.
</blockquote></details>

We may put the content of this file into integer.cairo file https://github.com/starkware-libs/cairo/blob/main/corelib/src/integer.cairo
I can also make the same for Zeroable - name a trait Zero and put it into the integer.cairo file

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3891)* status: all files reviewed, 5 unresolved discussions (waiting on @LucasLvy and @neotheprogramist)

___
*[`corelib/src/lib.cairo` line 324 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3891#-NcuzoPnBgVWl1IxVFaV:-NcuzoPnBgVWl1IxVFaW:b-4ahp9p) ([raw file](https://github.com/starkware-libs/cairo/blob/16813180f61e85259e087a36e95a65c2710b6f6b/corelib/src/lib.cairo#L324)):*
> ```Cairo
> // One.
> mod one;
> use one::One;
> ```

don't reexport in any case.



_Code quote:_
```Cairo
use one::One;
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3891)* status: all files reviewed, 5 unresolved discussions (waiting on @LucasLvy and @neotheprogramist)

___
*[`corelib/src/one.cairo` line 3 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3891#-NcXeMnX6UGW8QCSGn-8:-Ncuzwew87SonRgAFfso:blc6dbk) ([raw file](https://github.com/starkware-libs/cairo/blob/16813180f61e85259e087a36e95a65c2710b6f6b/corelib/src/one.cairo#L3)):*
<details><summary><i>Previously, neotheprogramist (Paweł) wrote…</i></summary><blockquote>

We may put the content of this file into integer.cairo file https://github.com/starkware-libs/cairo/blob/main/corelib/src/integer.cairo
I can also make the same for Zeroable - name a trait Zero and put it into the integer.cairo file
</blockquote></details>

maybe create a dir `num/traits`, and put both there?
Then will probably port all other numeric traits to there as well.

**Pull request closed without merging**
