### PR TITLE
feat: ok_or

### LINKED ISSUE #4063: feat:  `ok_or` Option<T> method
# Feature Request

**Describe the Feature Request**
Implement a method on the Option type that transforms the `Option<T>` into a [`Result<T, E>`], mapping [`Some(v)`] to [`Ok(v)`] and [`None`] to [`Err(err)`].

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**
```rust
    /// Arguments passed to `ok_or` are eagerly evaluated; if you are passing the
    /// result of a function call, it is recommended to use [`ok_or_else`], which is
    /// lazily evaluated.
    ///
    /// [`Ok(v)`]: Ok
    /// [`Err(err)`]: Err
    /// [`Some(v)`]: Some
    /// [`ok_or_else`]: Option::ok_or_else
    /// ```
    #[inline(always)]
    fn ok_or<E>(self: Option<T>, err: E) -> Result<T, E> {
        match self {
            Some(v) => Ok(v),
            None => Err(err),
        }
    }
```

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by enitrat**
Closes #4063 

Implements an `ok_or` method that transforms an Option<T> to Result<T, E>

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4066)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4066)* status: all files reviewed, 2 unresolved discussions (waiting on @enitrat)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4066#-NeI9vu144-v1ImGgfBu:-NeI9vu25jZ0afaH37_C:b-zuc8l) (no related file):*
2nd eye @yuvalsw 

___
___
*[`corelib/src/option.cairo` line 16 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4066#-NeI90DY0GX0WVFV7AOh:-NeI90DY0GX0WVFV7AOi:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b6237ba4cacad3878c71de86b8f6f22171e795b4/corelib/src/option.cairo#L16)):*
> ```Cairo
>     /// If `val` is `Option::Some(x)`, returns `x`. Otherwise, panics.
>     fn unwrap(self: Option<T>) -> T;
>     /// Transforms the `Option<T>` into a `Result<T, E>`, mapping `Option::Some(v)` to `Result::Ok(v)` and `Option::None` to Result::Err(err)`.
> ```





_Suggestion:_
```Cairo
    /// Transforms the `Option<T>` into a `Result<T, E>`, mapping `Option::Some(v)` to
    /// `Result::Ok(v)` and `Option::None` to Result::Err(err)`.
```

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4066)* status: all files reviewed, 4 unresolved discussions (waiting on @enitrat)

___
*[`corelib/src/option.cairo` line 16 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4066#-NeIfara73O30iIqQSQK:-NeIfara73O30iIqQSQL:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b6237ba4cacad3878c71de86b8f6f22171e795b4/corelib/src/option.cairo#L16)):*
> ```Cairo
>     /// If `val` is `Option::Some(x)`, returns `x`. Otherwise, panics.
>     fn unwrap(self: Option<T>) -> T;
>     /// Transforms the `Option<T>` into a `Result<T, E>`, mapping `Option::Some(v)` to `Result::Ok(v)` and `Option::None` to Result::Err(err)`.
> ```





_Suggestion:_
```Cairo
ption::None` to `Result::Err(err)`.
```
___
*[`corelib/src/option.cairo` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4066#-NeIgGkJDxg4yCQ5ojBh:-NeIgGkJDxg4yCQ5ojBi:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b6237ba4cacad3878c71de86b8f6f22171e795b4/corelib/src/option.cairo#L17)):*
> ```Cairo
>     fn unwrap(self: Option<T>) -> T;
>     /// Transforms the `Option<T>` into a `Result<T, E>`, mapping `Option::Some(v)` to `Result::Ok(v)` and `Option::None` to Result::Err(err)`.
>     fn ok_or<+Drop<E>>(self: Option<T>, err: E) -> Result<T, E>;
> ```





_Suggestion:_
```Cairo
n ok_or<E, +Drop<E>>(self: Opti
```

**Comment by enitrat** [comment]
Suggestions applied

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4066)* status: all files reviewed, 3 unresolved discussions (waiting on @enitrat)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4066#-NeIkB0D7HCPgK8_3gp5:-NeIkB0EEQMiPbz9ugT_:braejpp) (no related file):*
Please fix tests
(for the #[inline(always)] thing, probably replace with just #[inline])

___

**Comment by enitrat** [comment]
> Please fix tests

Done! 

What happens when we use #[inline] on a generic function? Does it inline it if possible at compile time?

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4066)* status: all files reviewed, 1 unresolved discussion (waiting on @enitrat)

**Review by yuvalsw — APPROVED** [review]
indeed. It can't be guaranteed before compilation as it depends on the generics, and thus can't have #[inline(always)]

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4066#-:-NednmAB0MhjRDmqrB52:bolqsn9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enitrat)

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4066#-:-NedodOb1qejn1l6McFu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enitrat)

**Pull request merged**
