### PR TITLE
u512 divmod by u256 audit fixes

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #3507
- #3506 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3506)

### CODE REVIEW

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3506#-:-NYr9_Zh9p2P8i3r9C0T:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3506)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 93 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3506#-NYrvhEh-ugSvNnBxUWE:-NYrvhEh-ugSvNnBxUWF:b4lc5gb) ([raw file](https://github.com/starkware-libs/cairo/blob/16789be63d66664dfad28606d4f8d47b74e4bae5/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L93)):*
> ```XML
>         // Aligning the branches.
>         ap += 2;
>         tempvar _unused;
> ```

Why are the `tempvar` necessary?
___
*[`tests/e2e_test_data/libfuncs/u512` line 38 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3506#-NYrtvPs4gp9rH9Uf1-Y:-NYrtvPs4gp9rH9Uf1-Z:b-79ns8c) ([raw file](https://github.com/starkware-libs/cairo/blob/16789be63d66664dfad28606d4f8d47b74e4bae5/tests/e2e_test_data/libfuncs/u512#L38)):*
> ```
> ap += 2;
> [ap + -3] = [[fp + -9] + 6];
> ap += 10;
> ```

Now that I look at it again - this can be saved as well: just do `ap += 10` in one branch and `ap += 12` in the other.



_Code quote:_
```
ap += 10;
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3506)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 93 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3506#-NYrvhEh-ugSvNnBxUWE:-NYrw05J5680BAp4GX87:b-asf8s7) ([raw file](https://github.com/starkware-libs/cairo/blob/16789be63d66664dfad28606d4f8d47b74e4bae5/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L93)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Why are the `tempvar` necessary?
</blockquote></details>

you need to both allocate vars and advance ap.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3506)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @liorgold2)

___
*[`tests/e2e_test_data/libfuncs/u512` line 38 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3506#-NYrtvPs4gp9rH9Uf1-Y:-NYrwFrr3xy9O3kD-TV2:bq3fwnq) ([raw file](https://github.com/starkware-libs/cairo/blob/16789be63d66664dfad28606d4f8d47b74e4bae5/tests/e2e_test_data/libfuncs/u512#L38)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Now that I look at it again - this can be saved as well: just do `ap += 10` in one branch and `ap += 12` in the other.
</blockquote></details>

please elaborate

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3506)* status: 3 of 5 files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 100 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3506#-NYrwWsu1OCQVkweD8XX:-NYrwWsu1OCQVkweD8XY:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/16789be63d66664dfad28606d4f8d47b74e4bae5/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L100)):*
> ```XML
>     // Do basic calculations.
>     casm_build_extend! {casm_builder,
>         // Allocating AP change for the hints.
> ```





_Suggestion:_
```XML
// Allocate memory cells for the hints.
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 123 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3506#-NYrwkFoB_DYEVfF8rli:-NYrwkFoB_DYEVfF8rlj:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/16789be63d66664dfad28606d4f8d47b74e4bae5/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L123)):*
> ```XML
>         tempvar part0 = q0d0_low + remainder0;
>         tempvar part1 = part0 - dividend0;
>         // leftover is in range:
> ```





_Suggestion:_
```XML
// leftover is an integer in range:
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 123 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3506#-NYrx6t61ad01kYD2w-U:-NYrx6t61ad01kYD2w-V:bvzdv39) ([raw file](https://github.com/starkware-libs/cairo/blob/16789be63d66664dfad28606d4f8d47b74e4bae5/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L123)):*
> ```XML
>         tempvar part0 = q0d0_low + remainder0;
>         tempvar part1 = part0 - dividend0;
>         // leftover is in range:
> ```

I suggest moving this comment one line below (so that it'll document the `leftover = leftover*leftover`). Same below.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 124 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3506#-NYrwoJT5IIstauK9DEw:-NYrwoJT5IIstauK9DEx:bo5cpot) ([raw file](https://github.com/starkware-libs/cairo/blob/16789be63d66664dfad28606d4f8d47b74e4bae5/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L124)):*
> ```XML
>         tempvar part1 = part0 - dividend0;
>         // leftover is in range:
>         // [(0 * 2 - u128::MAX) / u128_limit, (u128::MAX * 2 - 0) / u128_limit] ==> [0, 1].
> ```

Nice :)
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 133 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3506#-NYrwvp3Ew37TGxY7_9A:-NYrwvp3Ew37TGxY7_9B:bqubbnt) ([raw file](https://github.com/starkware-libs/cairo/blob/16789be63d66664dfad28606d4f8d47b74e4bae5/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L133)):*
> ```XML
>         tempvar part3 = part2 + remainder1;
>         tempvar part4 = part3 - dividend1;
>         // leftover is in range:
> ```

Similarly here and below.

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3506)* status: all files reviewed, 6 unresolved discussions (waiting on @orizi)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3506)* status: all files reviewed, 6 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 101 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3506#-NYrxm-v9AVgYWnwFoA8:-NYrxm-v9AVgYWnwFoA9:b-vjr8if) ([raw file](https://github.com/starkware-libs/cairo/blob/2fa011af45a8cd3523e035c14e6799230ce0c29f/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L101)):*
> ```XML
>     casm_build_extend! {casm_builder,
>         // Allocating AP change for the hints.
>         ap += 10;
> ```

This is what I meant below. (if it works)



_Suggestion:_
```XML
        jump HighDiff if diff1 != 0;
        tempvar diff0 = divisor0 - remainder0;
        tempvar diff0_min_1 = diff0 - one;
        assert diff0_min_1 = *(range_check++);
        // Allocate memory cells for the hints.
        ap += 10;
        jump After;
    HighDiff:
        // Allocate memory cells for the hints.
        ap += 12;
        // Aligning the branches.
        tempvar _unused;
        tempvar _unused;
        assert diff1 = *(range_check++);
    After:
    }
    // Do basic calculations.
    casm_build_extend! {casm_builder,
```
___
*[`tests/e2e_test_data/libfuncs/u512` line 38 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3506#-NYrtvPs4gp9rH9Uf1-Y:-NYrxbXY-xIgNC1rD8Ws:bcu6tyc) ([raw file](https://github.com/starkware-libs/cairo/blob/16789be63d66664dfad28606d4f8d47b74e4bae5/tests/e2e_test_data/libfuncs/u512#L38)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

please elaborate
</blockquote></details>

np. Added a comment in the rs file.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3506)* status: 3 of 5 files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware and @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 93 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3506#-NYrvhEh-ugSvNnBxUWE:-NYryaGCBD0semaYyy6U:buv2r6n) ([raw file](https://github.com/starkware-libs/cairo/blob/16789be63d66664dfad28606d4f8d47b74e4bae5/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L93)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you need to both allocate vars and advance ap.
</blockquote></details>

updated in a better way.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 100 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3506#-NYrwWsu1OCQVkweD8XX:-NYryrqwAk8j9Ok9n1wQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/16789be63d66664dfad28606d4f8d47b74e4bae5/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L100)):*
> ```XML
>     // Do basic calculations.
>     casm_build_extend! {casm_builder,
>         // Allocating AP change for the hints.
> ```

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 123 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3506#-NYrwkFoB_DYEVfF8rli:-NYryyiaDPjrYQysR6BX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/16789be63d66664dfad28606d4f8d47b74e4bae5/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L123)):*
> ```XML
>         tempvar part0 = q0d0_low + remainder0;
>         tempvar part1 = part0 - dividend0;
>         // leftover is in range:
> ```

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 123 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3506#-NYrx6t61ad01kYD2w-U:-NYrz6lk2YXG-DA4J_Y0:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/16789be63d66664dfad28606d4f8d47b74e4bae5/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L123)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

I suggest moving this comment one line below (so that it'll document the `leftover = leftover*leftover`). Same below.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 133 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3506#-NYrwvp3Ew37TGxY7_9A:-NYrzAKS2FQy5DlmC64t:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/16789be63d66664dfad28606d4f8d47b74e4bae5/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L133)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Similarly here and below.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 101 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3506#-NYrxm-v9AVgYWnwFoA8:-NYryis1BufA_7gkxfC3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2fa011af45a8cd3523e035c14e6799230ce0c29f/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L101)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

This is what I meant below. (if it works)
</blockquote></details>

Done.
___
*[`tests/e2e_test_data/libfuncs/u512` line 38 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3506#-NYrtvPs4gp9rH9Uf1-Y:-NYryd6KCs7NUP9Al_rM:b-33di0d) ([raw file](https://github.com/starkware-libs/cairo/blob/16789be63d66664dfad28606d4f8d47b74e4bae5/tests/e2e_test_data/libfuncs/u512#L38)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

np. Added a comment in the rs file.
</blockquote></details>

understood and Done.

**Review by liorgold2 — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3506)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 93 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3506#-NYrvhEh-ugSvNnBxUWE:-NYtACW63nOujrCrw8TS:bb70w76) ([raw file](https://github.com/starkware-libs/cairo/blob/16789be63d66664dfad28606d4f8d47b74e4bae5/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L93)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

updated in a better way.
</blockquote></details>

Nice
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 86 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3506#-NYtAGhH6WYsmJgijJWj:-NYtAGhH6WYsmJgijJWk:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/990453aab5d151f14865aa95a23bae8a65f9faed/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L86)):*
> ```XML
>         tempvar diff1 = divisor1 - remainder1;
> 
>         // Allocating memory cells for the hints,
> ```





_Suggestion:_
```XML
// Allocate memory cells for the hints,
```

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3506#-:-NYtBLujD9t4ViVxUT6b:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3506)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3506)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3506)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
