### PR TITLE
Add get_block_hash_syscall skeleton to syscalls and libfuncs.

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3228)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 714 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3228#-NW77gV82jY3K4A4MQJw:-NW77gV82jY3K4A4MQJx:b-8aq104) ([raw file](https://github.com/starkware-libs/cairo/blob/edc8b49c0c2ea90a0a609d7ad45311919a6b67f6/crates/cairo-lang-runner/src/casm_run/mod.rs#L714)):*
> ```XML
>         block_number: u64,
>     ) -> Result<SyscallResult, HintError> {
>         // TODO(Arni, 28/5/2023): Replace the temporary return value with the required value.
> ```

Here is the point of discussion from Monday - 22/5/2023.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3228)* status: 4 of 9 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 714 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3228#-NW77gV82jY3K4A4MQJw:-NW7BxKh6mYB4Ls3qirH:b-5jmln3) ([raw file](https://github.com/starkware-libs/cairo/blob/edc8b49c0c2ea90a0a609d7ad45311919a6b67f6/crates/cairo-lang-runner/src/casm_run/mod.rs#L714)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Here is the point of discussion from Monday - 22/5/2023.
</blockquote></details>

if it is some storage read - and no actual OS support - this should still be a contract call.

aside from this - the pr structure is fine.
___
*[`crates/cairo-lang-sierra-gas/src/starknet_libfunc_cost_base.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3228#-NW7BXZUDKJRtfm4IDlG:-NW7BXZVAHcWSyuchlEx:bqxre8v) ([raw file](https://github.com/starkware-libs/cairo/blob/edc8b49c0c2ea90a0a609d7ad45311919a6b67f6/crates/cairo-lang-sierra-gas/src/starknet_libfunc_cost_base.rs#L42)):*
> ```XML
>         // TODO(Arni, 28/5/2023): Fix to the correct cost. For now aligned with the cost of
>         // StorageRead.
>         StarkNetConcreteLibfunc::GetBlockHash(_) => syscall_cost(2),
> ```

this is validated - cost is calculated by arg count only.



_Suggestion:_
```XML
        StarkNetConcreteLibfunc::GetBlockHash(_) => syscall_cost(1),
```

**Comment by ArniStarkware** [comment]
*[`crates/cairo-lang-sierra-gas/src/starknet_libfunc_cost_base.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3228#-NW7BXZUDKJRtfm4IDlG:-NW7EhFn9wfXOayPXV-9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/edc8b49c0c2ea90a0a609d7ad45311919a6b67f6/crates/cairo-lang-sierra-gas/src/starknet_libfunc_cost_base.rs#L42)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is validated - cost is calculated by arg count only.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3228)* status: 5 of 9 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 718 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3228#-NWBzUQt6CCAOjxRRtMk:-NWBzUQt6CCAOjxRRtMl:b-hf8co1) ([raw file](https://github.com/starkware-libs/cairo/blob/a49d8f3e77d81fd088a173b39795514ebba9c5e9/crates/cairo-lang-runner/src/casm_run/mod.rs#L718)):*
> ```XML
>         //      One design suggestion - to preform a storage read. Have an arbitrary, hardcoded
>         //      (For example, addr=1) contain the mapping from block number to block hash.
>         Ok(SyscallResult::Success(vec![0.into()]))
> ```

can you add a better placeholder impl?
either some random value based on the block number or just:
`fail_syscall!(b"GET_BLOCK_HASH_UNIMPLEMENTED");`



_Code quote:_
```XML
        // TODO(Arni, 28/5/2023): Replace the temporary return value with the required value.
        //      One design suggestion - to preform a storage read. Have an arbitrary, hardcoded
        //      (For example, addr=1) contain the mapping from block number to block hash.
        Ok(SyscallResult::Success(vec![0.into()]))
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1, 2 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3228)* status: 7 of 11 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/getter.rs` line 172 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3228#-NWCeYcC5A_ochTgn5d1:-NWCeYcC5A_ochTgn5d2:by70mxj) ([raw file](https://github.com/starkware-libs/cairo/blob/9a9f5e5c799037ebe480c9a56152cd1bec0aaf8a/crates/cairo-lang-sierra/src/extensions/modules/starknet/getter.rs#L172)):*
> ```XML
> #[derive(Default)]
> pub struct GetBlockHashTrait {}
> impl GetterTraitsEx for GetBlockHashTrait {
> ```

this isn't a getter - this should be implemented more like `storage_read`.



_Code quote:_
```XML
impl GetterTraitsEx for GetBlockHashTrait
```

**Comment by ArniStarkware** [comment]
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 718 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3228#-NWBzUQt6CCAOjxRRtMk:-NWCg2FrDLX8Yddvbkx1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a49d8f3e77d81fd088a173b39795514ebba9c5e9/crates/cairo-lang-runner/src/casm_run/mod.rs#L718)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can you add a better placeholder impl?
either some random value based on the block number or just:
`fail_syscall!(b"GET_BLOCK_HASH_UNIMPLEMENTED");`
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3228)* status: 7 of 11 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3228#-NWWGa7M3evkiahEN0f9:-NWWGa7M3evkiahEN0fA:b-39krwo) (no related file):*
also - add a test with
```
#[should_panic(expected: ('Out of gas', 'GET_BLOCK_HASH_UNIMPLEMENTED', ))]
```
in the `cairo_level_tests` library.

___
___
*[`tests/e2e_test_data/libfuncs/starknet/syscalls` line 83 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3228#-NW7LfKI18FxZspI3QQk:-NWWGtRq-r7Q1eBK7xfs:br0448a) ([raw file](https://github.com/starkware-libs/cairo/blob/6934e33f059843862407d863dddf64795c76f880/tests/e2e_test_data/libfuncs/starknet/syscalls#L83)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

adding the test is about as easy as adding the todo :)
</blockquote></details>

this test is definitely not valid yet (probably because of the other requested changes)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 9 files at r1, 1 of 2 files at r3, 2 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3228)* status: all files reviewed, 4 unresolved discussions (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/getter.rs` line 172 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3228#-NWCeYcC5A_ochTgn5d1:-NWacYaF0RZXNr3C3UEU:b-wnfmk9) ([raw file](https://github.com/starkware-libs/cairo/blob/9a9f5e5c799037ebe480c9a56152cd1bec0aaf8a/crates/cairo-lang-sierra/src/extensions/modules/starknet/getter.rs#L172)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this isn't a getter - this should be implemented more like `storage_read`.
</blockquote></details>

Done. Removed.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3228)* status: all files reviewed, 4 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/storage.rs` line 233 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3228#-NWbJ-SPEpDondQqDBh8:-NWbJ-SPEpDondQqDBh9:b-4oaqq5) ([raw file](https://github.com/starkware-libs/cairo/blob/b22f3fe4412ac87c42729a2b856fe22627e846d9/crates/cairo-lang-sierra/src/extensions/modules/starknet/storage.rs#L233)):*
> ```XML
>         context: &dyn SignatureSpecializationContext,
>     ) -> Result<Vec<crate::ids::ConcreteTypeId>, SpecializationError> {
>         Ok(vec> ```

The input is u64, the output is felt252, fix all.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/interoperability.cairo` line 169 at r5 ([raw file](https://github.com/starkware-libs/cairo/blob/b22f3fe4412ac87c42729a2b856fe22627e846d9/crates/cairo-lang-starknet/cairo_level_tests/interoperability.cairo#L169)):*
> ```Cairo
> 
> // #[test]
> // #[should_panic(expected: ('Out of gas', 'GET_BLOCK_HASH_UNIMPLEMENTED', ))]
> ```

Uncomment

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3228)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
*[`tests/e2e_test_data/libfuncs/starknet/syscalls` line 83 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3228#-NW7LfKI18FxZspI3QQk:-NWbTlh1-TQBLGAvegaS:b-4d29k3) ([raw file](https://github.com/starkware-libs/cairo/blob/6934e33f059843862407d863dddf64795c76f880/tests/e2e_test_data/libfuncs/starknet/syscalls#L83)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this test is definitely not valid yet (probably because of the other requested changes)
</blockquote></details>

Done! Finally

**Comment by ArniStarkware** [comment]
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/storage.rs` line 233 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3228#-NWbJ-SPEpDondQqDBh8:-NWbTggJ6QXOEZztjYuu:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b22f3fe4412ac87c42729a2b856fe22627e846d9/crates/cairo-lang-sierra/src/extensions/modules/starknet/storage.rs#L233)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

The input is u64, the output is felt252, fix all.
</blockquote></details>

Done.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3228)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3228#-NWWGa7M3evkiahEN0f9:-NWacpJCCYZbJLQxu_dU:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

also - add a test with
```
#[should_panic(expected: ('Out of gas', 'GET_BLOCK_HASH_UNIMPLEMENTED', ))]
```
in the `cairo_level_tests` library.
</blockquote></details>

Done.

___
___
*[`crates/cairo-lang-starknet/cairo_level_tests/interoperability.cairo` line 169 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3228#-NWbJBd115EGV5dhJyM2:-NWbjr0d4JPFLjccHX85:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b22f3fe4412ac87c42729a2b856fe22627e846d9/crates/cairo-lang-starknet/cairo_level_tests/interoperability.cairo#L169)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Uncomment 
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3228)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/interoperability.cairo` line 169 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3228#-NWbJBd115EGV5dhJyM2:-NWbq5Ti6DtXbAcUBzH3:bmmcuuj) ([raw file](https://github.com/starkware-libs/cairo/blob/b22f3fe4412ac87c42729a2b856fe22627e846d9/crates/cairo-lang-starknet/cairo_level_tests/interoperability.cairo#L169)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think unwrapping and 'should_panic' would be nicer for when you actually add an implementation

**Comment by ArniStarkware** [comment]
*[`crates/cairo-lang-starknet/cairo_level_tests/interoperability.cairo` line 169 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3228#-NWbJBd115EGV5dhJyM2:-NWc6TzaDga95EOR37cx:bp75csj) ([raw file](https://github.com/starkware-libs/cairo/blob/b22f3fe4412ac87c42729a2b856fe22627e846d9/crates/cairo-lang-starknet/cairo_level_tests/interoperability.cairo#L169)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I think unwrapping and 'should_panic' would be nicer for when you actually add an implementation 
</blockquote></details>

Now with nicer `should_panic`.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3228#-:-NWcALV9B_wSTUUm69F0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 9 files at r1, 1 of 1 files at r2, 2 of 4 files at r4, 3 of 6 files at r5, 2 of 3 files at r6, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3228#-:-NWfJWAx9N7g51PAACG3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
