### PR TITLE
add impl items in impls

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5755)

### CODE REVIEW

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5755)* status: 5 of 9 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 941 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5755#-Nzx7wfK9tul4-X1iYqg:-NzxBJiW20zFL0_vJLmt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/441931cffb4ed098014a034a397c21f0b4b3e100/crates/cairo-lang-semantic/src/db.rs#L941)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5755)* status: 8 of 9 files reviewed, 4 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1941 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5755#-NzxCaVk9XvFfqjO_Se-:-NzxCaVk9XvFfqjO_Se0:barrg1m) ([raw file](https://github.com/starkware-libs/cairo/blob/a97e756949a59b5588223201bb72916c05ca1521/crates/cairo-lang-semantic/src/items/imp.rs#L1941)):*
> ```XML
>     let resolved_impl_concrete_trait =
>         impl_data.resolved_impl.and_then(|imp| imp.concrete_trait(db));
>     let _ = (|| -> Result<(), DiagnosticAdded> {
> ```

properly doc
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1993 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5755#-NzxCYda8CMByqYxWEP_:-NzxCYda8CMByqYxWEPa:b-l8xggc) ([raw file](https://github.com/starkware-libs/cairo/blob/a97e756949a59b5588223201bb72916c05ca1521/crates/cairo-lang-semantic/src/items/imp.rs#L1993)):*
> ```XML
>     let resolved_impl_concrete_trait =
>         impl_data.resolved_impl.and_then(|imp| imp.concrete_trait(db));
>     let _ = (|| -> Result<(), DiagnosticAdded> {
> ```

properly doc.
___
*[`crates/cairo-lang-semantic/src/items/impl_alias.rs` line 46 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5755#-NzxCFuE736Wfbp-aTaQ:-NzxCFuE736Wfbp-aTaR:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/a97e756949a59b5588223201bb72916c05ca1521/crates/cairo-lang-semantic/src/items/impl_alias.rs#L46)):*
> ```XML
> }
> 
> pub fn impl_alias_semantic_data_helper(
> ```

doc
___
*[`crates/cairo-lang-semantic/src/items/impl_alias.rs` line 108 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5755#-NzxCH9UByl_b3rG3Gb6:-NzxCH9UByl_b3rG3Gb7:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/a97e756949a59b5588223201bb72916c05ca1521/crates/cairo-lang-semantic/src/items/impl_alias.rs#L108)):*
> ```XML
> }
> 
> pub fn impl_alias_semantic_data_cycle_helper(
> ```

doc

**Review by orizi — COMMENTED** [review]
> Reviewed 5 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5755)* status: 8 of 9 files reviewed, 4 unresolved discussions (waiting on @TomerStarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5755)* status: all files reviewed, 4 unresolved discussions (waiting on @TomerStarkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5755)* status: 8 of 9 files reviewed, 4 unresolved discussions (waiting on @mkaput and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1993 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5755#-NzxCYda8CMByqYxWEP_:-O-FaBhN3oxIPJZJNQ4Z:b-f21dg3) ([raw file](https://github.com/starkware-libs/cairo/blob/a97e756949a59b5588223201bb72916c05ca1521/crates/cairo-lang-semantic/src/items/imp.rs#L1993)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

properly doc.
</blockquote></details>

consider using this crate instead of the doc https://docs.rs/iife/latest/iife/

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5755)* status: all files reviewed, 2 unresolved discussions (waiting on @mkaput and @TomerStarkware)

**Review by mkaput — COMMENTED** [review]
> Reviewed 1 of 9 files at r1, 4 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5755)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1993 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5755#-NzxCYda8CMByqYxWEP_:-O-Fl2Qa7R_FThWvTZaK:b34qz3t) ([raw file](https://github.com/starkware-libs/cairo/blob/a97e756949a59b5588223201bb72916c05ca1521/crates/cairo-lang-semantic/src/items/imp.rs#L1993)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

consider using this crate instead of the doc https://docs.rs/iife/latest/iife/
</blockquote></details>

TBH I wouldn't pull a crate (extra compilation cost) just for this pattern, which is rare but pretty obvious.

Also the macro there is like 4 lines of core, you can copy-paste it into our utils if you reallly need.

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 1 of 9 files at r1, 1 of 6 files at r4, 1 of 2 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5755#-:-O-FlWhw7FPM5KyXix6l:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi and @TomerStarkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5755)* status: all files reviewed, 2 unresolved discussions (waiting on @mkaput and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1993 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5755#-NzxCYda8CMByqYxWEP_:-O-FoEH8CMcJ9q4p0GEv:b-u6eddu) ([raw file](https://github.com/starkware-libs/cairo/blob/a97e756949a59b5588223201bb72916c05ca1521/crates/cairo-lang-semantic/src/items/imp.rs#L1993)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

TBH I wouldn't pull a crate (extra compilation cost) just for this pattern, which is rare but pretty obvious.

Also the macro there is like 4 lines of core, you can copy-paste it into our utils if you reallly need.
</blockquote></details>

the pattern is really not obvious actually - it is generally very unclear without the comment, and the macro makes it clear.

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5755)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 4 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5755)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @mkaput and @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5755)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1941 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5755#-NzxCaVk9XvFfqjO_Se-:-O-FYqRE5fRKMpiG3kaM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a97e756949a59b5588223201bb72916c05ca1521/crates/cairo-lang-semantic/src/items/imp.rs#L1941)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

properly doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1993 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5755#-NzxCYda8CMByqYxWEP_:-O-puCRP3SGI_LIO4w4d:b2ni1bp) ([raw file](https://github.com/starkware-libs/cairo/blob/a97e756949a59b5588223201bb72916c05ca1521/crates/cairo-lang-semantic/src/items/imp.rs#L1993)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the pattern is really not obvious actually - it is generally very unclear without the comment, and the macro makes it clear.
</blockquote></details>

f2f
___
*[`crates/cairo-lang-semantic/src/items/impl_alias.rs` line 46 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5755#-NzxCFuE736Wfbp-aTaQ:-O-FZ2VT-NefKdvYBAvL:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a97e756949a59b5588223201bb72916c05ca1521/crates/cairo-lang-semantic/src/items/impl_alias.rs#L46)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5755#-:-O-pvb6k2CAOssn4PwIL:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
