### PR TITLE
Added `recover_public_key` to secp256k1

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2928)

### CODE REVIEW

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2928)* status: 0 of 1 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2928#-NToKqDfEYntX7ZzVeHn:-NToKqDfEYntX7ZzVeHo:bagld1g) (no related file):*
change target branch to main

___

**Review by yuvalsw — COMMENTED** [review]
Hi
IIUC, you don't have `v` or `y_parity`.
In that case, one option is to call the function twice, once with false and once with true, and verify that one of them succeeded.
It'll be great if you send a PR that exposes this functionality (this is Cairo1 code). This might be possible to do even more efficiently than calling the function twice.

Please share if you have anything else in mind.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2928#-:-NUHIrb18fmQG5UGI4Vs:bl8704b)* status: 0 of 1 files reviewed, 1 unresolved discussion

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2928)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/starknet/secp256k1.cairo` line 22 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2928#-NV9ET6r-QmL8LSZzsnh:-NV9ET6r-QmL8LSZzsni:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ddf18171664381b182977fa6f3b1233e955cb1a2/corelib/src/starknet/secp256k1.cairo#L22)):*
> ```Cairo
> fn get_N() -> u256 {
>     u256 { high: 0xfffffffffffffffffffffffffffffffe, low: 0xbaaedce6af48a03bbfd25e8cd0364141 }
> }
> ```





_Suggestion:_
```Cairo
// TODO(yuval): change to constant once u256 constants are supported.
fn get_N() -> u256 {
    0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141
}
```
___
*[`corelib/src/starknet/secp256k1.cairo` line 58 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2928#-NV9EzHI9mzjQRcTpMMd:-NV9EzHI9mzjQRcTpMMe:bir5ggo) ([raw file](https://github.com/starkware-libs/cairo/blob/ddf18171664381b182977fa6f3b1233e955cb1a2/corelib/src/starknet/secp256k1.cairo#L58)):*
> ```Cairo
>     msg_hash: u256, r: u256, s: u256, y_parity: bool
> ) -> Option<Secp256K1EcPoint> {
>     let r_point = secp256k1_ec_get_point_from_x_syscall(x: r, :y_parity).expect('SYSCALL_FAILED')?;
> ```

i think this is probably preferred.

(and everywhere)



_Suggestion:_
```Cairo
.unwrap_syscall()?;
```

**Comment by Lukasz2891** [comment]
hi ;) What's the status of this PR? Is someone working on it? When do you expect to have it finished?

**Review by yuvalsw — COMMENTED** [review]
good timing :)
Just finished working on some preliminary work needed for this and other secp functionality. Should be submitted very soon.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2928#-:-NViFFtkDauvpdDKRXQ-:brw9xfl)* status: 0 of 326 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/starknet/secp256k1.cairo` line 22 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2928#-NV9ET6r-QmL8LSZzsnh:-NVP4xEB8-J61ViUOnkc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ddf18171664381b182977fa6f3b1233e955cb1a2/corelib/src/starknet/secp256k1.cairo#L22)):*
> ```Cairo
> fn get_N() -> u256 {
>     u256 { high: 0xfffffffffffffffffffffffffffffffe, low: 0xbaaedce6af48a03bbfd25e8cd0364141 }
> }
> ```

Done.
___
*[`corelib/src/starknet/secp256k1.cairo` line 58 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2928#-NV9EzHI9mzjQRcTpMMd:-NVP5KOhB0Md59yUqJeb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ddf18171664381b182977fa6f3b1233e955cb1a2/corelib/src/starknet/secp256k1.cairo#L58)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i think this is probably preferred.

(and everywhere)
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 326 of 326 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2928)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/starknet/secp256k1.cairo` line 18 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2928#-NViR-nG4wzb38O6I3SY:-NViR-nG4wzb38O6I3SZ:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/9810032d1d6b2a2ea96869a2493d31ef1655bffc/corelib/src/starknet/secp256k1.cairo#L18)):*
> ```Cairo
> 
> // TODO(yuval): change to constant once u256 constants are supported.
> /// N = 0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141
> ```

remove



_Code quote:_
```Cairo
/// N = 0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2928)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/starknet/secp256k1.cairo` line 18 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2928#-NViR-nG4wzb38O6I3SY:-NVicRVg94rgyyU_ltPZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9810032d1d6b2a2ea96869a2493d31ef1655bffc/corelib/src/starknet/secp256k1.cairo#L18)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2928)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/starknet/secp256k1.cairo` line 66 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2928#-NVig0IKARg4ZW4OjUOJ:-NVig0IL5oBkQygMj446:b-krb8id) ([raw file](https://github.com/starkware-libs/cairo/blob/b3ae54afccad537f2af833b7aef4a2e2c180701f/corelib/src/starknet/secp256k1.cairo#L66)):*
> ```Cairo
> 
>     let u1 = u256_div_mod_n(msg_hash, r, get_N());
>     let minus_u1 = secp256k1_ec_negate_scalar(u1);
> ```

Consider inlining and removing the function

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2928)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/starknet/secp256k1.cairo` line 66 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2928#-NVig0IKARg4ZW4OjUOJ:-NVikDt_63KcMvtD92B3:b-v814ok) ([raw file](https://github.com/starkware-libs/cairo/blob/b3ae54afccad537f2af833b7aef4a2e2c180701f/corelib/src/starknet/secp256k1.cairo#L66)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Consider inlining and removing the function 
</blockquote></details>

I think this is a bit easier to follow (documents a bit more), and might be useful for more functions (but not sure). I submit it this way. LMK if you want a followup to change, I have no strong objection...

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2928)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2928#-NVilk5s1DWmaFMag8Lp:-NVilk5s1DWmaFMag8Lq:b7dovze) (no related file):*
please add a recovery example test.

___

**Comment by yuvalsw** [comment]
change target branch

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2928)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 324 of 326 files at r4, 1 of 4 files at r9, 6 of 10 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2928)* status: 331 of 335 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`examples/secp256k1.cairo` line 44 at r10](https://reviewable.io/reviews/starkware-libs/cairo/2928#-NW166A767WxmRBJAxUs:-NW166A767WxmRBJAxUt:b-24qjeu) ([raw file](https://github.com/starkware-libs/cairo/blob/b0b7cc24ca5438da459aeca713eddc957ab73509/examples/secp256k1.cairo#L44)):*
> ```Cairo
> /// Returns a valid message hash and its signature for testing.
> fn get_message_and_signature() -> (u256, u256, u256, bool, u256, u256) {
>     // TODO(yg): change golden values to hex.
> ```

any reason to not already do that?



_Code quote:_
```Cairo
    // TODO(yg): change golden values to hex.
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2928)* status: 330 of 336 files reviewed, 2 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2928#-NVilk5s1DWmaFMag8Lp:-NW3AixgBuFGikdBJk9P:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

please add a recovery example test.
</blockquote></details>

Done.

___
___
*[`examples/secp256k1.cairo` line 44 at r10](https://reviewable.io/reviews/starkware-libs/cairo/2928#-NW166A767WxmRBJAxUs:-NW3AmXPCdXBKMzxQyqV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b0b7cc24ca5438da459aeca713eddc957ab73509/examples/secp256k1.cairo#L44)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

any reason to not already do that?
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2928)* status: 331 of 336 files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`scripts/cairo_test.sh` line 5 at r11](https://reviewable.io/reviews/starkware-libs/cairo/2928#-NW6GrkA13txIAPW1r9p:-NW6GrkA13txIAPW1r9q:bjfxq1s) ([raw file](https://github.com/starkware-libs/cairo/blob/fe0887a39c5fd51667256cc356505923bad10ce3/scripts/cairo_test.sh#L5)):*
> ```Shell
> cargo run --bin cairo-test -- corelib/ && \
> cargo run --bin cairo-test -- tests/bug_samples/ --starknet && \
> cargo run --bin cairo-test -- examples/ --starknet
> ```

just move the `example` into `cairo_level_tests/lib.rs` and revert this.



_Code quote:_
```Shell
cargo run --bin cairo-test -- examples/ --starknet
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 6 files at r11, 3 of 3 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2928#-:-NW70S_B7qVdsjeV1T4A:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
