### PR TITLE
Added selector inline macro for starknet.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #3948
- #3936
- #3935
- #3934
- #3933
- #3922
- #3921
- #3920
- #3919
- #3912 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3912)

### CODE REVIEW

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3912)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-compiler/src/db.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3912#-Nby2wbsDqAbLVIPVNtQ:-Nby2wbsDqAbLVIPVNtR:bl23lwx) ([raw file](https://github.com/starkware-libs/cairo/blob/a0c56cc1107c61426cc88f549c379c47c503c043/crates/cairo-lang-compiler/src/db.rs#L103)):*
> ```XML
>     pub fn with_inline_macro_plugin(
>         &mut self,
>         name: impl Into<String>,
> ```

why not just &str ? Less stuff to monomorphize for Rust compiler



_Suggestion:_
```XML
&str
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3912)* status: 14 of 18 files reviewed, 1 unresolved discussion (waiting on @mkaput and @spapinistarkware)

___
*[`crates/cairo-lang-compiler/src/db.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3912#-Nby2wbsDqAbLVIPVNtQ:-NbzO2xiAGGrf84WgwAT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/81a37cc78252ec5ec1dc9f9239fd14dec5d46542/crates/cairo-lang-compiler/src/db.rs#L103)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

why not just &str ? Less stuff to monomorphize for Rust compiler
</blockquote></details>

Done.

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3912)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/inline_macros/selector.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3912#-Nc11H9S5wDmYBK7Hj3Z:-Nc11H9S5wDmYBK7Hj3_:b-44azv1) ([raw file](https://github.com/starkware-libs/cairo/blob/d62fa488b509e19073475a7b3a9dace77567d227/crates/cairo-lang-starknet/src/inline_macros/selector.rs#L9)):*
> ```XML
> 
> /// Macro for expanding a selector to a string literal.
> #[derive(Debug)]
> ```

May I ask you to add this impl? I am relying on having `T: Default` bounds in Scarb code: https://github.com/software-mansion/scarb/blob/bf927194941f6c0ce62677e7e2ef4f9122489ff6/scarb/src/compiler/plugin/builtin.rs#L24



_Suggestion:_
```XML
#[derive(Debug, Default)]
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3912)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/inline_macros/selector.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3912#-Nc11H9S5wDmYBK7Hj3Z:-Nc15Cum1HA3-9oNq2VD:b-l4bmif) ([raw file](https://github.com/starkware-libs/cairo/blob/d62fa488b509e19073475a7b3a9dace77567d227/crates/cairo-lang-starknet/src/inline_macros/selector.rs#L9)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

May I ask you to add this impl? I am relying on having `T: Default` bounds in Scarb code: https://github.com/software-mansion/scarb/blob/bf927194941f6c0ce62677e7e2ef4f9122489ff6/scarb/src/compiler/plugin/builtin.rs#L24
</blockquote></details>

if at some point we'd have plugins that requires params - how would you support it?
or all params for such plugins would ahve to be salsa db inputs? (as they are for cfg for example)

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3912)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/inline_macros/selector.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3912#-Nc11H9S5wDmYBK7Hj3Z:-Nc16e3MA9b36W_No1jH:b-ia8i0z) ([raw file](https://github.com/starkware-libs/cairo/blob/d62fa488b509e19073475a7b3a9dace77567d227/crates/cairo-lang-starknet/src/inline_macros/selector.rs#L9)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

if at some point we'd have plugins that requires params - how would you support it?
or all params for such plugins would ahve to be salsa db inputs? (as they are for cfg for example)
</blockquote></details>

Pull stuff from salsa. I can't see any other way to pass params to plugins when they'll be written as packages, especially because I believe the constructor will have to be representable as `extern "C"`.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3912)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/inline_macros/selector.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3912#-Nc11H9S5wDmYBK7Hj3Z:-Nc1EB8T2lT6jQvIlsTS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d62fa488b509e19073475a7b3a9dace77567d227/crates/cairo-lang-starknet/src/inline_macros/selector.rs#L9)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Pull stuff from salsa. I can't see any other way to pass params to plugins when they'll be written as packages, especially because I believe the constructor will have to be representable as `extern "C"`.
</blockquote></details>

Done.

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3912#-:-Nc1GFyz7p5PRSYvtGcd:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3912)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by mkaput — APPROVED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3912)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 6 of 18 files at r1, 2 of 4 files at r2, 1 of 1 files at r3, 4 of 8 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3912)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/inline_macros/selector.rs` line 28 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3912#-NcRBZ7R0zRsKkl97Hk1:-NcRBZ7R0zRsKkl97Hk2:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/498ef50ea2826cb103fdd1baff8ff89b430964a6/crates/cairo-lang-starknet/src/inline_macros/selector.rs#L28)):*
> ```XML
>             let diagnostics = vec![PluginDiagnostic {
>                 stable_ptr: syntax.stable_ptr().untyped(),
>                 message: "selector macro must have a single argument".to_string(),
> ```





_Suggestion:_
```XML
Selector
```

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3912#-:-NcRCrZ71JWgZF5p0VHj:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3912)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3912)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
