### PR TITLE
Support lowering of while loops.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4680)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4680)* status: 1 of 10 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/lower/generated_test.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4680#-NmpzlNu09FNMmQ94n0H:-NmpzlNu09FNMmQ94n0I:b7qjhqj) ([raw file](https://github.com/starkware-libs/cairo/blob/2d025df15cfbd4674c9bfb4e2c3307c1944c62af/crates/cairo-lang-lowering/src/lower/generated_test.rs#L50)):*
> ```XML
>         .unwrap();
> 
>         let lowering = db
> ```

this is mixed from the other PR - isn't it?
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 158 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4680#-NmpzpVY9iBbKCsnnJEp:-NmpzpVY9iBbKCsnnJEq:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/2d025df15cfbd4674c9bfb4e2c3307c1944c62af/crates/cairo-lang-lowering/src/lower/mod.rs#L158)):*
> ```XML
> }
> 
> pub fn lower_while_loop(
> ```

doc
___
*[`crates/cairo-lang-lowering/src/lower/usage.rs` line 182 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4680#-Nmq3t3k2mH0kIcIOB5a:-Nmq3t3k2mH0kIcIOB5b:b-z83ivf) ([raw file](https://github.com/starkware-libs/cairo/blob/2d025df15cfbd4674c9bfb4e2c3307c1944c62af/crates/cairo-lang-lowering/src/lower/usage.rs#L182)):*
> ```XML
>                     current.changes.insert(path.clone(), expr.clone());
>                 }
>                 self.block_usages.insert(expr_id, usage);
> ```

extract to function.



_Code quote:_
```XML
                for (path, expr) in usage.usage.iter() {
                    current.usage.insert(path.clone(), expr.clone());
                }
                for (path, expr) in usage.changes.iter() {
                    current.changes.insert(path.clone(), expr.clone());
                }
                self.block_usages.insert(expr_id, usage);
```
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2320 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4680#-Nmq-kUf9FR2u4ighTWe:-Nmq-kUf9FR2u4ighTWf:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2d025df15cfbd4674c9bfb4e2c3307c1944c62af/crates/cairo-lang-semantic/src/expr/compute.rs#L2320)):*
> ```XML
> 
>         ast::Statement::Missing(_) => todo!(),
>     };
> ```





_Suggestion:_
```XML
                }
            };
            semantic::Statement::Break(semantic::StatementBreak {
                expr_option,
                stable_ptr: syntax.stable_ptr(),
            })
        }
        ast::Statement::Missing(_) => todo!(),
    };
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4680)* status: 0 of 10 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/generated_test.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4680#-NmpzlNu09FNMmQ94n0H:-NmywHueBmVvvI7xassd:b2nign6) ([raw file](https://github.com/starkware-libs/cairo/blob/2d025df15cfbd4674c9bfb4e2c3307c1944c62af/crates/cairo-lang-lowering/src/lower/generated_test.rs#L50)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is mixed from the other PR - isn't it?
</blockquote></details>

yes
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 158 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4680#-NmpzpVY9iBbKCsnnJEp:-NmywgOW443lspO2ahsM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2d025df15cfbd4674c9bfb4e2c3307c1944c62af/crates/cairo-lang-lowering/src/lower/mod.rs#L158)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/usage.rs` line 182 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4680#-Nmq3t3k2mH0kIcIOB5a:-Nmz4DDDBwjgKZ2orPYB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2d025df15cfbd4674c9bfb4e2c3307c1944c62af/crates/cairo-lang-lowering/src/lower/usage.rs#L182)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

extract to function.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2320 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4680#-Nmq-kUf9FR2u4ighTWe:-Nmz7mc70sC7CypEp1zL:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2d025df15cfbd4674c9bfb4e2c3307c1944c62af/crates/cairo-lang-semantic/src/expr/compute.rs#L2320)):*
> ```XML
> 
>         ast::Statement::Missing(_) => todo!(),
>     };
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 10 files at r1, 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4680)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/lower/usage.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4680#-NmzA_b_9UhLtNHWHZTg:-NmzA_b_9UhLtNHWHZTh:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2aa011031597d7b9aa354aaea49962e604705e06/crates/cairo-lang-lowering/src/lower/usage.rs#L64)):*
> ```XML
> 
> impl Usage {
>     // Adds the usage and changes from 'usage' to self, Ignoring `introductions`.
> ```





_Suggestion:_
```XML
impl Usage {
    /// Adds the usage and changes from 'usage' to self, Ignoring `introductions`.
```
___
*[`crates/cairo-lang-lowering/src/lower/usage.rs` line 150 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4680#-NmzBGrt746Jjsr9NZoW:-NmzBGru21y-mncMuCuT:b-wsrwyq) ([raw file](https://github.com/starkware-libs/cairo/blob/2aa011031597d7b9aa354aaea49962e604705e06/crates/cairo-lang-lowering/src/lower/usage.rs#L150)):*
> ```XML
>                             break;
>                         }
>                     }
> ```

aren't the pruning stages required for the while loop as well?
(the condition and the block part might do similar stuff)



_Code quote:_
```XML
                    // Prune usages that are members of other usages.
                    let mut current_path = member_path.clone();
                    while let MemberPath::Member { parent, .. } = current_path {
                        current_path = *parent.clone();
                        if usage.usage.contains_key(&current_path) {
                            usage.usage.swap_remove(&member_path);
                            break;
                        }
                    }
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/usage.rs` line 150 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4680#-NmzBGrt746Jjsr9NZoW:-Nn-KYYa-0hmjzafpCM1:b909oqq) ([raw file](https://github.com/starkware-libs/cairo/blob/2aa011031597d7b9aa354aaea49962e604705e06/crates/cairo-lang-lowering/src/lower/usage.rs#L150)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

aren't the pruning stages required for the while loop as well?
(the condition and the block part might do similar stuff)
</blockquote></details>

I guess, but I'm not sure how to model this detail.

should I add a finalize_usage() function?

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4680)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/lower/usage.rs` line 150 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4680#-NmzBGrt746Jjsr9NZoW:-Nn-XRgb5BdLoOTlYaSM:b-xjap53) ([raw file](https://github.com/starkware-libs/cairo/blob/2aa011031597d7b9aa354aaea49962e604705e06/crates/cairo-lang-lowering/src/lower/usage.rs#L150)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I guess, but I'm not sure how to model this detail.

should I add a finalize_usage() function?
</blockquote></details>

sounds reasonable.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/usage.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4680#-NmzA_b_9UhLtNHWHZTg:-NmzEUOzCwE32_0I14-w:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2aa011031597d7b9aa354aaea49962e604705e06/crates/cairo-lang-lowering/src/lower/usage.rs#L64)):*
> ```XML
> 
> impl Usage {
>     // Adds the usage and changes from 'usage' to self, Ignoring `introductions`.
> ```

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4680)* status: 7 of 10 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/usage.rs` line 150 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4680#-NmzBGrt746Jjsr9NZoW:-Nn2zJJyEsQD7EFDQ5J-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2aa011031597d7b9aa354aaea49962e604705e06/crates/cairo-lang-lowering/src/lower/usage.rs#L150)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

sounds reasonable.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4680)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/lower/usage.rs` line 76 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4680#-Nn3Tiwi3KtFmuQGWbBw:-Nn3Tiwi3KtFmuQGWbBx:b-oami7l) ([raw file](https://github.com/starkware-libs/cairo/blob/c108f2ec548b168665fe346feb958a06497fa559/crates/cairo-lang-lowering/src/lower/usage.rs#L76)):*
> ```XML
>     /// Removes usage that was introduced current block and usage that is already covered
>     /// by containing variables.
>     pub fn finalize(&mut self) {
> ```

seems to make just a bit more sense for me.



_Suggestion:_
```XML
    pub fn finalize_as_scope(&mut self) {
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4680)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/usage.rs` line 76 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4680#-Nn3Tiwi3KtFmuQGWbBw:-Nn3oyqu-3Y8G41YG8NC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c108f2ec548b168665fe346feb958a06497fa559/crates/cairo-lang-lowering/src/lower/usage.rs#L76)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

seems to make just a bit more sense for me.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4680#-:-Nn3vE18BqnCytYzZ-nn:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
