### PR TITLE
Add OptimizationConfig.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4552)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4552)* status: 4 of 6 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 275 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4552#-NlXEahL-6RHLXV7PalS:-NlXEahL-6RHLXV7PalT:bljob9k) ([raw file](https://github.com/starkware-libs/cairo/blob/59e9fc84612d384d60602ca7d3a67671885750e0/crates/cairo-lang-lowering/src/db.rs#L275)):*
> ```XML
>     ) -> Maybe<OrderedHashSet<ids::ConcreteFunctionWithBodyId>>;
> 
>     /// Returns the feedback-vertex-set of the given concrete-function SCC-representative. A
> ```

fix doc
___
*[`crates/cairo-lang-lowering/src/db.rs` line 285 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4552#-NlXFgmKEzeudmuXPvNI:-NlXFgmKEzeudmuXPvNJ:b-lznxpa) ([raw file](https://github.com/starkware-libs/cairo/blob/59e9fc84612d384d60602ca7d3a67671885750e0/crates/cairo-lang-lowering/src/db.rs#L285)):*
> ```XML
> 
> pub fn init_lowering_group(db: &mut (dyn LoweringGroup + 'static)) {
>     // Initialize inputs.
> ```

i don't understand this doc.
___
*[`crates/cairo-lang-lowering/src/db.rs` line 287 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4552#-NlXFqYBBuy0Q_neG9Dv:-NlXFqYBBuy0Q_neG9Dw:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/59e9fc84612d384d60602ca7d3a67671885750e0/crates/cairo-lang-lowering/src/db.rs#L287)):*
> ```XML
>     // Initialize inputs.
>     db.set_optimization_config(Arc::new(OptimizationConfig {
>         moveable_functions: ["bool_not_impl"].into_iter().map(|s| s.into()).collect(),
> ```





_Suggestion:_
```XML
        moveable_functions: vec!["bool_not_impl".to_string()],
```
___
*[`crates/cairo-lang-lowering/src/optimizations/config.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4552#-NlXF4R38MbYfP1VCLaA:-NlXF4R49As-y4lHJ22f:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/59e9fc84612d384d60602ca7d3a67671885750e0/crates/cairo-lang-lowering/src/optimizations/config.rs#L11)):*
> ```XML
> 
> #[derive(Debug, Eq, PartialEq, Clone)]
> pub struct OptimizationConfig {
> ```

doc
___
*[`crates/cairo-lang-lowering/src/optimizations/config.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4552#-NlXF-uM8ZDNweiGqgwf:-NlXF-uM8ZDNweiGqgwg:b3svjfm) ([raw file](https://github.com/starkware-libs/cairo/blob/59e9fc84612d384d60602ca7d3a67671885750e0/crates/cairo-lang-lowering/src/optimizations/config.rs#L15)):*
> ```XML
> }
> 
> pub fn priv_movable_function_ids(db: &dyn LoweringGroup) -> Arc<UnorderedHashSet<FunctionId>> {
> ```

why is this priv? you are using it directly and normally.
the priv would probably be when you fully transform the entire optimization config - and you parse it only once - but you'd call it from various different other queries.
___
*[`crates/cairo-lang-sierra-generator/src/test_utils.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4552#-NlXG0XUAz8m5SRQ6UVm:-NlXG0XUAz8m5SRQ6UVn:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/59e9fc84612d384d60602ca7d3a67671885750e0/crates/cairo-lang-sierra-generator/src/test_utils.rs#L69)):*
> ```XML
>         // Disable moving of functions to simplify tests writing.
>         res.set_optimization_config(Arc::new(OptimizationConfig {
>             moveable_functions: [].into_iter().collect(),
> ```





_Suggestion:_
```XML
            moveable_functions: vec![],
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/db.rs` line 285 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4552#-NlXFgmKEzeudmuXPvNI:-NlXJ4eRBoJLuY7JBxjJ:be8nhy7) ([raw file](https://github.com/starkware-libs/cairo/blob/59e9fc84612d384d60602ca7d3a67671885750e0/crates/cairo-lang-lowering/src/db.rs#L285)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i don't understand this doc.
</blockquote></details>

That is what written elsewhere:
https://github.com/starkware-libs/cairo/blob/4e6006fd3e8c062d7b8314398810f1fbf7cb3f3d/crates/cairo-lang-filesystem/src/db.rs#L139

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4552)* status: 4 of 6 files reviewed, 6 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 285 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4552#-NlXFgmKEzeudmuXPvNI:-NlXJ86u4Szdecg6Q2Pe:b-2z55pp) ([raw file](https://github.com/starkware-libs/cairo/blob/59e9fc84612d384d60602ca7d3a67671885750e0/crates/cairo-lang-lowering/src/db.rs#L285)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

That is what written elsewhere:
https://github.com/starkware-libs/cairo/blob/4e6006fd3e8c062d7b8314398810f1fbf7cb3f3d/crates/cairo-lang-filesystem/src/db.rs#L139
</blockquote></details>

I can remove it.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/config.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4552#-NlXF-uM8ZDNweiGqgwf:-NlXObcG5BakWbe7rOoE:bgqqlns) ([raw file](https://github.com/starkware-libs/cairo/blob/59e9fc84612d384d60602ca7d3a67671885750e0/crates/cairo-lang-lowering/src/optimizations/config.rs#L15)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why is this priv? you are using it directly and normally.
the priv would probably be when you fully transform the entire optimization config - and you parse it only once - but you'd call it from various different other queries.
</blockquote></details>

I thought priv means the user is not supposed to call it.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4552)* status: 4 of 6 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 285 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4552#-NlXFgmKEzeudmuXPvNI:-NlXP7IMBgwx-haJosUV:b-6d25im) ([raw file](https://github.com/starkware-libs/cairo/blob/59e9fc84612d384d60602ca7d3a67671885750e0/crates/cairo-lang-lowering/src/db.rs#L285)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I can remove it.
</blockquote></details>

please do.
___
*[`crates/cairo-lang-lowering/src/optimizations/config.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4552#-NlXF-uM8ZDNweiGqgwf:-NlXPDIp9f3lcD6sXu-V:b-fraq0d) ([raw file](https://github.com/starkware-libs/cairo/blob/59e9fc84612d384d60602ca7d3a67671885750e0/crates/cairo-lang-lowering/src/optimizations/config.rs#L15)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I thought priv means the user is not supposed to call it.
</blockquote></details>

you are the user - priv is what we don't expect to use out of the basic local db queries impls.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4552)* status: 1 of 7 files reviewed, 6 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 275 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4552#-NlXEahL-6RHLXV7PalS:-NlXQMw2C9o0iaRhTl0c:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/59e9fc84612d384d60602ca7d3a67671885750e0/crates/cairo-lang-lowering/src/db.rs#L275)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/db.rs` line 285 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4552#-NlXFgmKEzeudmuXPvNI:-NlXQSpB-bg3wsWrf2g9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/59e9fc84612d384d60602ca7d3a67671885750e0/crates/cairo-lang-lowering/src/db.rs#L285)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

please do.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/db.rs` line 287 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4552#-NlXFqYBBuy0Q_neG9Dv:-NlXQ5Pn-nUcmME_0-rm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/59e9fc84612d384d60602ca7d3a67671885750e0/crates/cairo-lang-lowering/src/db.rs#L287)):*
> ```XML
>     // Initialize inputs.
>     db.set_optimization_config(Arc::new(OptimizationConfig {
>         moveable_functions: ["bool_not_impl"].into_iter().map(|s| s.into()).collect(),
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/optimizations/config.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4552#-NlXF4R38MbYfP1VCLaA:-NlXPxmXDsisBMxJp0WZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/59e9fc84612d384d60602ca7d3a67671885750e0/crates/cairo-lang-lowering/src/optimizations/config.rs#L11)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/config.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4552#-NlXF-uM8ZDNweiGqgwf:-NlXQyEy3eYjscShTZys:b7jdeen) ([raw file](https://github.com/starkware-libs/cairo/blob/59e9fc84612d384d60602ca7d3a67671885750e0/crates/cairo-lang-lowering/src/optimizations/config.rs#L15)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you are the user - priv is what we don't expect to use out of the basic local db queries impls.
</blockquote></details>

I have no idea what is:
"basic local db queries impls"

I add '_priv' as the query is there for caching purposes and I don't consider it as an API of the db.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4552)* status: 1 of 7 files reviewed, 6 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/test_utils.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4552#-NlXG0XUAz8m5SRQ6UVm:-NlXQxue9YkZutoniqpV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/59e9fc84612d384d60602ca7d3a67671885750e0/crates/cairo-lang-sierra-generator/src/test_utils.rs#L69)):*
> ```XML
>         // Disable moving of functions to simplify tests writing.
>         res.set_optimization_config(Arc::new(OptimizationConfig {
>             moveable_functions: [].into_iter().collect(),
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4552)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/config.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4552#-NlXF-uM8ZDNweiGqgwf:-NlXVEsjBBK2oq9_MqmN:bfkiplm) ([raw file](https://github.com/starkware-libs/cairo/blob/59e9fc84612d384d60602ca7d3a67671885750e0/crates/cairo-lang-lowering/src/optimizations/config.rs#L15)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I have no idea what is:
"basic local db queries impls"

I add '_priv' as the query is there for caching purposes and I don't consider it as an API of the db.
</blockquote></details>

but it is the interface of the db - you call it by the client 'reorder_statement'

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/config.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4552#-NlXF-uM8ZDNweiGqgwf:-NlXVlrl1JYOaaYVjrCm:b-derl6z) ([raw file](https://github.com/starkware-libs/cairo/blob/59e9fc84612d384d60602ca7d3a67671885750e0/crates/cairo-lang-lowering/src/optimizations/config.rs#L15)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

but it is the interface of the db - you call it by the client 'reorder_statement'
</blockquote></details>

All the `priv` functions are in the interface of the db and called by other queries...

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4552)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/config.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4552#-NlXF-uM8ZDNweiGqgwf:-NlXYC-6CVgeouOEVlYN:bucyzw8) ([raw file](https://github.com/starkware-libs/cairo/blob/59e9fc84612d384d60602ca7d3a67671885750e0/crates/cairo-lang-lowering/src/optimizations/config.rs#L15)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

All the `priv` functions are in the interface of the db and called by other queries...
</blockquote></details>

almost all queries are called by others.
`priv` generally are used for the cases where you would have made the function non-`pub` - but since there are no private methods in traits - and db queries are trait based - `priv_` is added for doc.
In all other examples - it is either used locally to implement data fetching queries near it (e.g.  semantic item queries, where we have a struct with all data, and a set of other queries just calling the priv and returning one of its fields) - or supposed to be that - but we have a todo to stop using them.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/config.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4552#-NlXF-uM8ZDNweiGqgwf:-NlXZTkNBGKfJkJXinI_:b-vv79nl) ([raw file](https://github.com/starkware-libs/cairo/blob/59e9fc84612d384d60602ca7d3a67671885750e0/crates/cairo-lang-lowering/src/optimizations/config.rs#L15)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

almost all queries are called by others.
`priv` generally are used for the cases where you would have made the function non-`pub` - but since there are no private methods in traits - and db queries are trait based - `priv_` is added for doc.
In all other examples - it is either used locally to implement data fetching queries near it (e.g.  semantic item queries, where we have a struct with all data, and a set of other queries just calling the priv and returning one of its fields) - or supposed to be that - but we have a todo to stop using them.
</blockquote></details>

I think this falls under the "non-`pub`" case. 
Let's discuss f2f.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4552)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4552)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/config.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4552#-NlXF4R38MbYfP1VCLaA:-NlXlr3sBHS8louXp9PQ:byxmpbd) ([raw file](https://github.com/starkware-libs/cairo/blob/59e9fc84612d384d60602ca7d3a67671885750e0/crates/cairo-lang-lowering/src/optimizations/config.rs#L11)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

And the struct itself.
___
*[`crates/cairo-lang-lowering/src/optimizations/config.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4552#-NlXbAvF3bbT1TmJyXuN:-NlXbAvF3bbT1TmJyXuO:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b5702cb9afdd7be5140f3b1b0db8ea3b0bd16e54/crates/cairo-lang-lowering/src/optimizations/config.rs#L13)):*
> ```XML
> pub struct OptimizationConfig {
>     // A list of functions that can be moved during the reorder_statements optimization.
>     pub moveable_functions: Vec<String>,
> ```





_Suggestion:_
```XML
pub struct OptimizationConfig {
    /// A list of functions that can be moved during the reorder_statements optimization.
    pub moveable_functions: Vec<String>,
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4552)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/config.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4552#-NlXF4R38MbYfP1VCLaA:-NlXpqRIDPvqpnlF9xqR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/59e9fc84612d384d60602ca7d3a67671885750e0/crates/cairo-lang-lowering/src/optimizations/config.rs#L11)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

And the struct itself.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/optimizations/config.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4552#-NlXbAvF3bbT1TmJyXuN:-NlXpqD69IrQSJ3SrGl-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b5702cb9afdd7be5140f3b1b0db8ea3b0bd16e54/crates/cairo-lang-lowering/src/optimizations/config.rs#L13)):*
> ```XML
> pub struct OptimizationConfig {
>     // A list of functions that can be moved during the reorder_statements optimization.
>     pub moveable_functions: Vec<String>,
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4552#-:-NlXqgePA9ZmJzzJGtVh:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
