### PR TITLE
LS: Fix state snapshots in diagnostics

### PR DESCRIPTION
**Pull request by Draggu**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6330)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6330)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 385 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6330#-O5mc2q4AizAy3L0NnP6:-O5mc2q4AizAy3L0NnP7:bsec0gv) ([raw file](https://github.com/starkware-libs/cairo/blob/e822f9485eee388dea8b3b214fd2f8cd7bf65260/crates/cairo-lang-language-server/src/lib.rs#L385)):*
> ```XML
>         let mut processed_modules: HashSet<ModuleId> = HashSet::default();
> 
>         // db snapshot is not clone so make more here
> ```

unclear.



_Code quote:_
```XML
// db snapshot is not clone so make more here
```

**Review by Draggu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6330)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 385 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6330#-O5mc2q4AizAy3L0NnP6:-O5mdxqK26J8IPAtRnVE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e822f9485eee388dea8b3b214fd2f8cd7bf65260/crates/cairo-lang-language-server/src/lib.rs#L385)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

unclear.
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6330)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @Arcticae, @mkaput, and @piotmag769)

**Review by piotmag769 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6330#-:-O5mvmB8DX6q57M_AwNK:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @mkaput)

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6330#-:-O5n2lxaDJRsUcUKyJC6:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6330#-:-O5vSmSqBlneX6lTAg-p:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae)

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6330)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae)

**Review by Arcticae — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6330#-:-O60UEXH4BO0DmOyx0-B:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Draggu)

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6330)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Draggu)

**Pull request closed without merging**
