### PR TITLE
Add span libfuncs

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3236)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3236)* status: 2 of 14 files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @spapinistarkware)

___
*[`corelib/src/array.cairo` line 23 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NWCiMoq8EzOlGv-ET36:-NWCiMoq8EzOlGv-ET37:bln76c2) ([raw file](https://github.com/starkware-libs/cairo/blob/d5b82ffe359a616438da360b8a2b5011ddb94ec9/corelib/src/array.cairo#L23)):*
> ```Cairo
> extern fn array_len<T>(arr: @Array<T>) -> usize nopanic;
> extern fn array_to_span<T>(arr: Array<T>) -> span::Span<T> nopanic;
> extern fn snapshot_array_as_span<T>(arr: @Array<T>) -> span::Span<@T> nopanic;
> ```

just to match the existing functionalities names.



_Suggestion:_
```Cairo
extern fn array_to_span<T>(arr: Array<T>) -> span::Span<T> nopanic;
extern fn array_snapshot_to_span<T>(arr: @Array<T>) -> span::Span<@T> nopanic;
```

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 14 files at r1, 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3236)* status: 2 of 14 files reviewed, 3 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`corelib/src/span.cairo` line 16 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NWDTdPa6m_oqUacgg4L:-NWDTdPa6m_oqUacgg4M:b-e96lbb) ([raw file](https://github.com/starkware-libs/cairo/blob/1e9d4634c7739a72dd96fe2b1b1db99b79a10300/corelib/src/span.cairo#L16)):*
> ```Cairo
> #[panic_with('Index out of bounds', span_at)]
> extern fn span_get<T>(
>     span: Span<@T>, index: usize
> ```

1. Is `@T` better than writing `T` and requiring `Copy<T>` (I know we currently can't require `Copy<T>` in extern functions, let's ignore this)
2. Should you get `Span<@T>` or `@Span<@T>` or `@Span<T>`? How do they differ, and which is the most easy to use?
___
*[`corelib/src/span.cairo` line 26 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NWDT5YT65RpmFmkzn3d:-NWDT5YU9CG4RRQjm0E7:b-ep80n7) ([raw file](https://github.com/starkware-libs/cairo/blob/1e9d4634c7739a72dd96fe2b1b1db99b79a10300/corelib/src/span.cairo#L26)):*
> ```Cairo
> 
> trait SpanTrait<T> {
>     fn pop_front(ref self: Span<T>) -> Option<T> nopanic;
> ```

Document all functions inside the trait. Separate them with blank lines.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3236)* status: 2 of 14 files reviewed, 5 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`corelib/src/span.cairo` line 30 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NWDVYenDAVyUtSV74Ah:-NWDVYenDAVyUtSV74Ai:bri8xap) ([raw file](https://github.com/starkware-libs/cairo/blob/1e9d4634c7739a72dd96fe2b1b1db99b79a10300/corelib/src/span.cairo#L30)):*
> ```Cairo
>     fn pop_back(ref self: Span<T>) -> Option<T> nopanic;
>     fn pop_back_consume(self: Span<T>) -> Option<(Span<T>, T)> nopanic;
>     fn get(self: Span<@T>, index: usize) -> Option<Box<@T>>;
> ```

Same question here (but here we can require `Copy<T>`).
Why no `nopanic` here?
___
*[`corelib/src/span.cairo` line 36 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NWDWIP26jquYgn8ySWw:-NWDWIP26jquYgn8ySWx:b9uyb16) ([raw file](https://github.com/starkware-libs/cairo/blob/1e9d4634c7739a72dd96fe2b1b1db99b79a10300/corelib/src/span.cairo#L36)):*
> ```Cairo
>     fn is_empty(self: @Span<T>) -> bool;
>     fn as_snap(self: @Span<T>) -> Span<@T>;
>     fn as_desnap(self: Span<@T>) -> @Span<T>;
> ```

Should the parameter be `@Span<@T>`? (will allow more usecases?)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3236)* status: 3 of 14 files reviewed, 7 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`corelib/src/span.cairo` line 85 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NWDXTnkDrvJ4BGylBTA:-NWDXTnkDrvJ4BGylBTB:b-eadfuv) ([raw file](https://github.com/starkware-libs/cairo/blob/1e9d4634c7739a72dd96fe2b1b1db99b79a10300/corelib/src/span.cairo#L85)):*
> ```Cairo
>     #[inline(always)]
>     fn is_empty(self: @Span<T>) -> bool {
>         self.len() == 0_usize
> ```

Why not just `0`?



_Code quote:_
```Cairo
0_usize
```
___
*[`corelib/src/span.cairo` line 98 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NWDXanO5dHIZ6BdPrui:-NWDXanO5dHIZ6BdPruj:b-rb3r39) ([raw file](https://github.com/starkware-libs/cairo/blob/1e9d4634c7739a72dd96fe2b1b1db99b79a10300/corelib/src/span.cairo#L98)):*
> ```Cairo
>     #[inline(never)]
>     fn index(self: @Span<T>, index: usize) -> T {
>         *span_at(self.as_snap(), index).unbox()
> ```

Isn't it `SpanImpl::at`?

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3236)* status: 4 of 14 files reviewed, 7 unresolved discussions (waiting on @orizi and @spapinistarkware)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 14 files at r1, 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3236)* status: 6 of 14 files reviewed, 9 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 456 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NWDbyXrDsgrckLt-zVY:-NWDbyXrDsgrckLt-zVZ:b8hcmdp) ([raw file](https://github.com/starkware-libs/cairo/blob/1e9d4634c7739a72dd96fe2b1b1db99b79a10300/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L456)):*
> ```XML
>         let arr_ty = context.get_wrapped_concrete_type(ArrayType::id(), ty.clone())?;
>         let snapshot_arr_ty = snapshot_ty(context, arr_ty)?;
>         let snapshot_ty = snapshot_ty(context, ty)?;
> ```

I think you can merge this with the next line. It may be slightly more readable.
___
*[`tests/e2e_test_data/libfuncs/array` line 921 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NWDcI8kDjAtCiWbbYps:-NWDcI8kDjAtCiWbbYpt:bjezfav) ([raw file](https://github.com/starkware-libs/cairo/blob/1e9d4634c7739a72dd96fe2b1b1db99b79a10300/tests/e2e_test_data/libfuncs/array#L921)):*
> ```
> //! > cairo
> fn foo(arr: Array<usize>) -> span::Span<usize> {
>     array::array_to_span(arr)
> ```

I suggest using the wrapping function here instead of the libfunc. The test is almost empty as it is, I think we'll gain from making it slightly more testing-y.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3236)* status: 7 of 14 files reviewed, 9 unresolved discussions (waiting on @liorgold2, @orizi, @span, and @t)

___
*[`corelib/src/span.cairo` line 16 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NWDTdPa6m_oqUacgg4L:-NWD_U7G9A-tP3U5yGoV:buhmp0q) ([raw file](https://github.com/starkware-libs/cairo/blob/1e9d4634c7739a72dd96fe2b1b1db99b79a10300/corelib/src/span.cairo#L16)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

1. Is `@T` better than writing `T` and requiring `Copy<T>` (I know we currently can't require `Copy<T>` in extern functions, let's ignore this)
2. Should you get `Span<@T>` or `@Span<@T>` or `@Span<T>`? How do they differ, and which is the most easy to use?
</blockquote></details>

1.
a. It's powerful enough to also allow getting on Copy Ts:
If T is Copy, I can take Span<T> into @Span<T> into Span<@T>, get @T, and deref. Sierra wise, this only costed one libfunc, and casm is free. So, I still retain all the abilities.
b. I can do it now without trait changes:)
c. That said, it might be better to extend this to any Copy<T>, seemse better. Do you tihnk it's worth it?
2.
a. Note that he functions below make @ and Span commutative, so they are all kind of the same. 
b. No reason to get @Span<@T>, since it's Span<@T> is Copy.
c. @Span<T> is closer to what we really want which is Span<T:Copy>
___
*[`corelib/src/span.cairo` line 26 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NWDT5YT65RpmFmkzn3d:-NWDet9d9N8qL6m48hrK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1e9d4634c7739a72dd96fe2b1b1db99b79a10300/corelib/src/span.cairo#L26)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Document all functions inside the trait. Separate them with blank lines.
</blockquote></details>

Done.
___
*[`corelib/src/span.cairo` line 30 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NWDVYenDAVyUtSV74Ah:-NWDfENb13UYWn0Mz8Ys:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1e9d4634c7739a72dd96fe2b1b1db99b79a10300/corelib/src/span.cairo#L30)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Same question here (but here we can require `Copy<T>`).
Why no `nopanic` here?
</blockquote></details>

Done.
___
*[`corelib/src/span.cairo` line 36 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NWDWIP26jquYgn8ySWw:-NWDcUklDzTV_RCsIkhG:b-imc8nw) ([raw file](https://github.com/starkware-libs/cairo/blob/1e9d4634c7739a72dd96fe2b1b1db99b79a10300/corelib/src/span.cairo#L36)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Should the parameter be `@Span<@T>`? (will allow more usecases?)
</blockquote></details>

Span<@T> is Copy, so there is no realy need to add another snapshot, right?
___
*[`corelib/src/span.cairo` line 85 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NWDXTnkDrvJ4BGylBTA:-NWDctDu9dz5SLksviJO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1e9d4634c7739a72dd96fe2b1b1db99b79a10300/corelib/src/span.cairo#L85)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Why not just `0`?
</blockquote></details>

Done.
___
*[`corelib/src/span.cairo` line 98 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NWDXanO5dHIZ6BdPrui:-NWDdKsZ3r_ODzDekK1c:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1e9d4634c7739a72dd96fe2b1b1db99b79a10300/corelib/src/span.cairo#L98)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Isn't it `SpanImpl::at`?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 436 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NWDbi895LO521VLZXCX:-NWDdiru7YykOImVTtYE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1e9d4634c7739a72dd96fe2b1b1db99b79a10300/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L436)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

`get_array_ty` (create if we don't have one)
</blockquote></details>

Done.
___
*[`tests/e2e_test_data/libfuncs/array` line 921 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NWDcI8kDjAtCiWbbYps:-NWDdvKz9LVGaxXTxeMi:bhdsslr) ([raw file](https://github.com/starkware-libs/cairo/blob/1e9d4634c7739a72dd96fe2b1b1db99b79a10300/tests/e2e_test_data/libfuncs/array#L921)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

I suggest using the wrapping function here instead of the libfunc. The test is almost empty as it is, I think we'll gain from making it slightly more testing-y.
</blockquote></details>

I think the e2e../libfuncs tests should be resetved for just libfuncs, and see exactly their casm.
We have cairo level tests for high level code, and examples test for non libfunc code.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3236)* status: 5 of 14 files reviewed, 9 unresolved discussions (waiting on @orizi, @span, @spapinistarkware, and @t)

___
*[`corelib/src/span.cairo` line 26 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NWDT5YT65RpmFmkzn3d:-NX53ZNV8OWZmeuyL9VW:b-cgwcwf) ([raw file](https://github.com/starkware-libs/cairo/blob/1e9d4634c7739a72dd96fe2b1b1db99b79a10300/corelib/src/span.cairo#L26)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

 > Separate them with blank lines.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3236)* status: 5 of 14 files reviewed, 7 unresolved discussions (waiting on @orizi, @span, @spapinistarkware, and @t)

___
*[`corelib/src/span.cairo` line 16 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NWDTdPa6m_oqUacgg4L:-NX53nw49N0rfF_9iBI2:blyvek0) ([raw file](https://github.com/starkware-libs/cairo/blob/1e9d4634c7739a72dd96fe2b1b1db99b79a10300/corelib/src/span.cairo#L16)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

1.
a. It's powerful enough to also allow getting on Copy Ts:
If T is Copy, I can take Span<T> into @Span<T> into Span<@T>, get @T, and deref. Sierra wise, this only costed one libfunc, and casm is free. So, I still retain all the abilities.
b. I can do it now without trait changes:)
c. That said, it might be better to extend this to any Copy<T>, seemse better. Do you tihnk it's worth it?
2.
a. Note that he functions below make @ and Span commutative, so they are all kind of the same. 
b. No reason to get @Span<@T>, since it's Span<@T> is Copy.
c. @Span<T> is closer to what we really want which is Span<T:Copy>
</blockquote></details>

I know they are commutative, I want to understand which is better - let's discuss f2f.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3236)* status: 5 of 14 files reviewed, 8 unresolved discussions (waiting on @orizi, @span, @spapinistarkware, and @t)

___
*[`corelib/src/span.cairo` line 26 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NX54Aze4m9ujHoEjP29:-NX54Aze4m9ujHoEjP2A:b-lll80j) ([raw file](https://github.com/starkware-libs/cairo/blob/40f9357c3496fa0806af5b48d43a06c94799a385/corelib/src/span.cairo#L26)):*
> ```Cairo
> 
> trait SpanTrait<T> {
>     // Pops the first element off the span, returning it, or None if empty.
> ```

`off` or `of`? Spell checker says `of`.
Fix below simialrly.



_Suggestion:_
```Cairo
 // Pops the first element of the span, and returns it, or None if empty.
```

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3236)* status: 5 of 14 files reviewed, 12 unresolved discussions (waiting on @orizi, @span, @spapinistarkware, and @t)

___
*[`corelib/src/span.cairo` line 36 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NWDWIP26jquYgn8ySWw:-NX55LhFBf-_hLaaZaqm:b-skpvct) ([raw file](https://github.com/starkware-libs/cairo/blob/1e9d4634c7739a72dd96fe2b1b1db99b79a10300/corelib/src/span.cairo#L36)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Span<@T> is Copy, so there is no realy need to add another snapshot, right?
</blockquote></details>

If I have `x` of type `@Span<@T>`, will `x.as_desnap()` works or will I need `(*x).as_desnap()`?
Same question for `self: Span<@T>` and for `self: @Span<@T>`.
___
*[`corelib/src/span.cairo` line 36 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NX54no51dfBXk3fmtT0:-NX54no51dfBXk3fmtT1:b-qmjysr) ([raw file](https://github.com/starkware-libs/cairo/blob/40f9357c3496fa0806af5b48d43a06c94799a385/corelib/src/span.cairo#L36)):*
> ```Cairo
>     // Consumes the span if empty.
>     fn pop_back_consume(self: Span<T>) -> Option<(Span<T>, T)> nopanic;
>     // Gets the element at the given index, or None if out of bounds.
> ```

Fix below similarly.



_Suggestion:_
```Cairo
 // Returns the element at the given index, or None if the index is out of bounds.
```
___
*[`corelib/src/span.cairo` line 42 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NX551WS--z1ic39wDnt:-NX551WS--z1ic39wDnu:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/40f9357c3496fa0806af5b48d43a06c94799a385/corelib/src/span.cairo#L42)):*
> ```Cairo
>     // Gets a slice of the span. Panics if out of bounds.
>     fn slice(self: Span<@T>, start: usize, length: usize) -> Span<@T>;
>     // Gets the length of the span.
> ```





_Suggestion:_
```Cairo
// Returns the number of elements in the span.
```
___
*[`corelib/src/span.cairo` line 46 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NX558bLBCYd72RRS1E7:-NX558bLBCYd72RRS1E8:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/40f9357c3496fa0806af5b48d43a06c94799a385/corelib/src/span.cairo#L46)):*
> ```Cairo
>     // Returns true if the span is empty.
>     fn is_empty(self: @Span<T>) -> bool;
>     // Converts a snapshot span to a span.
> ```





_Suggestion:_
```Cairo
// Converts a snapshot span to a span of snapshots.
```
___
*[`corelib/src/span.cairo` line 48 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NX55BYwDbmmiubPkWED:-NX55BYwDbmmiubPkWEE:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/40f9357c3496fa0806af5b48d43a06c94799a385/corelib/src/span.cairo#L48)):*
> ```Cairo
>     // Converts a snapshot span to a span.
>     fn as_snap(self: @Span<T>) -> Span<@T> nopanic;
>     // Converts a span to a snapshot span.
> ```





_Suggestion:_
```Cairo
// Converts a span of snapshots to a snapshot span.
```

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3236)* status: 7 of 14 files reviewed, 11 unresolved discussions (waiting on @orizi, @span, @spapinistarkware, and @t)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3236)* status: 7 of 14 files reviewed, 11 unresolved discussions (waiting on @orizi, @span, @spapinistarkware, and @t)

___
*[`tests/e2e_test_data/libfuncs/array` line 921 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NWDcI8kDjAtCiWbbYps:-NX59SEP9ogl1LPNXy4I:bsu11u0) ([raw file](https://github.com/starkware-libs/cairo/blob/1e9d4634c7739a72dd96fe2b1b1db99b79a10300/tests/e2e_test_data/libfuncs/array#L921)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I think the e2e../libfuncs tests should be resetved for just libfuncs, and see exactly their casm.
We have cairo level tests for high level code, and examples test for non libfunc code.
</blockquote></details>

I want to see that it doesn't generate unnecessary casm code. What test is doing that?
I also think that if it indeed doesn't generate unnecessary casm code then it falls under the definition of testing the libfunc and I'm ok with it breaking if we break something like the inlining.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3236)* status: 7 of 14 files reviewed, 12 unresolved discussions (waiting on @orizi, @span, @spapinistarkware, and @t)

___
*[`tests/e2e_test_data/libfuncs/span` line 263 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NX59wjN184BPqmPA6Tl:-NX59wjN184BPqmPA6Tm:bfsj7n8) ([raw file](https://github.com/starkware-libs/cairo/blob/40f9357c3496fa0806af5b48d43a06c94799a385/tests/e2e_test_data/libfuncs/span#L263)):*
> ```
> 
> //! > cairo
> fn foo(span: span::Span<@usize>, index: usize) -> Option<Box<@usize>>{
> ```

If I have `Span<usize>` can I call `get`? If so how does it look?

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3236)* status: 8 of 14 files reviewed, 15 unresolved discussions (waiting on @orizi, @span, @spapinistarkware, and @t)

___
*[`tests/e2e_test_data/libfuncs/span` line 263 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NX5AJu3EeUqYn8aYFGP:-NX5AJu3EeUqYn8aYFGQ:b-in7qex) ([raw file](https://github.com/starkware-libs/cairo/blob/40f9357c3496fa0806af5b48d43a06c94799a385/tests/e2e_test_data/libfuncs/span#L263)):*
> ```
> 
> //! > cairo
> fn foo(span: span::Span<@usize>, index: usize) -> Option<Box<@usize>>{
> ```

Missing some tests like `array_get libfunc on larger element`.
Also `array_get libfunc on a non duppable type` - but I don't understand what this one is testing...
___
*[`tests/e2e_test_data/libfuncs/span` line 328 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NX5AnTv-DmHA-JjKwlN:-NX5AnTv-DmHA-JjKwlO:b-mqnsfb) ([raw file](https://github.com/starkware-libs/cairo/blob/40f9357c3496fa0806af5b48d43a06c94799a385/tests/e2e_test_data/libfuncs/span#L328)):*
> ```
> //! > ==========================================================================
> 
> //! > span_slice libfunc
> ```

Same here re. missing test for larger elements.
___
*[`tests/e2e_test_data/libfuncs/span` line 401 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NX5AxqW4YXJpOiBHoi3:-NX5AxqW4YXJpOiBHoi4:brhumzt) ([raw file](https://github.com/starkware-libs/cairo/blob/40f9357c3496fa0806af5b48d43a06c94799a385/tests/e2e_test_data/libfuncs/span#L401)):*
> ```
> //! > ==========================================================================
> 
> //! > span_len libfunc
> ```

Same here.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3236)* status: 9 of 14 files reviewed, 21 unresolved discussions (waiting on @orizi, @span, @spapinistarkware, and @t)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 64 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NXALS8n6BEy8vMEvc4L:-NXALS8n6BEy8vMEvc4M:b-2o3r8v) ([raw file](https://github.com/starkware-libs/cairo/blob/40f9357c3496fa0806af5b48d43a06c94799a385/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L64)):*
> ```XML
>         ty: ConcreteTypeId,
>     ) -> Result<LibfuncSignature, SpecializationError> {
>         let span_ty = get_span_ty(context, ty)?;
> ```

Consider merging the two lines (or even putting this directly in the first argument).
___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 113 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NXAMe16AfOuR0fyzOG7:-NXAMe16AfOuR0fyzOG8:b-5lihrc) ([raw file](https://github.com/starkware-libs/cairo/blob/40f9357c3496fa0806af5b48d43a06c94799a385/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L113)):*
> ```XML
>                     vars: vecOutputVarInfo {
>                         ty: span_ty,
>                         ref_info: OutputVarReferenceInfo::Deferred(DeferredOutputKind::AddConst {
> ```

Not same as param?
___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 127 at r3 ([raw file](https://github.com/starkware-libs/cairo/blob/40f9357c3496fa0806af5b48d43a06c94799a385/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L127)):*
> ```XML
> pub type SpanPopFrontLibfunc = WrapSignatureAndTypeGenericLibfunc<SpanPopFrontLibfuncWrapped>;
> 
> /// Libfunc for popping the first value from the beginning of a span.
> ```

Explain the difference from `span_pop_front`.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 207 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NXANktsCned9Zu1NeVg:-NXANktsCned9Zu1NeVh:b9qxfe3) ([raw file](https://github.com/starkware-libs/cairo/blob/40f9357c3496fa0806af5b48d43a06c94799a385/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L207)):*
> ```XML
>                     vars: vecOutputVarInfo {
>                         ty: span_ty,
>                         ref_info: OutputVarReferenceInfo::Deferred(DeferredOutputKind::AddConst {
> ```

Same as param?
___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 276 at r3 ([raw file](https://github.com/starkware-libs/cairo/blob/40f9357c3496fa0806af5b48d43a06c94799a385/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L276)):*
> ```XML
>     ) -> Result<LibfuncSignature, SpecializationError> {
>         let snapshot_ty = snapshot_ty(context, ty)?;
>         let span_ty = get_span_ty(context, snapshot_ty.clone())?;
> ```





_Suggestion:_
```XML
let span_snapshot_ty = get_span_ty(context, snapshot_ty.clone())?;
```

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3236)* status: 9 of 14 files reviewed, 23 unresolved discussions (waiting on @orizi, @span, @spapinistarkware, and @t)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 328 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NXAPco81DKdlbKuL-lM:-NXAPco81DKdlbKuL-lN:b-e6fkao) ([raw file](https://github.com/starkware-libs/cairo/blob/40f9357c3496fa0806af5b48d43a06c94799a385/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L328)):*
> ```XML
>         ty: ConcreteTypeId,
>     ) -> Result<LibfuncSignature, SpecializationError> {
>         let snapshot_ty = snapshot_ty(context, ty)?;
> ```

Is it ok that the var name is the same as the function name?
___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 329 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NXAPYNz2cS7aaZyRxlV:-NXAPYNz2cS7aaZyRxlW:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/40f9357c3496fa0806af5b48d43a06c94799a385/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L329)):*
> ```XML
>     ) -> Result<LibfuncSignature, SpecializationError> {
>         let snapshot_ty = snapshot_ty(context, ty)?;
>         let span_type = get_span_ty(context, snapshot_ty)?;
> ```





_Suggestion:_
```XML
let span_snapshot_ty = get_span_ty(context, snapshot_ty)?;
```

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3236)* status: 9 of 14 files reviewed, 24 unresolved discussions (waiting on @orizi, @span, @spapinistarkware, and @t)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 377 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NXAQNSw3uzLUU0gkQKl:-NXAQNSw3uzLUU0gkQKm:bhoo0pb) ([raw file](https://github.com/starkware-libs/cairo/blob/40f9357c3496fa0806af5b48d43a06c94799a385/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L377)):*
> ```XML
> pub struct SnapshotSpanToSpanLibfuncWrapped {}
> impl SignatureAndTypeGenericLibfunc for SnapshotSpanToSpanLibfuncWrapped {
>     const STR_ID: &'static str = "span_snapshot_to_span";
> ```

The name is confusing. E.g., the first parameter below is called `snapshot_span`.
I think it should be `snapshot_span_to_span_snapshot` - which reads as `@ Span -> Span @`.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3236)* status: 9 of 14 files reviewed, 25 unresolved discussions (waiting on @orizi, @span, @spapinistarkware, and @t)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 387 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NXASGm-674bXvw6C3h4:-NXASGm-674bXvw6C3h5:bafcbrl) ([raw file](https://github.com/starkware-libs/cairo/blob/40f9357c3496fa0806af5b48d43a06c94799a385/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L387)):*
> ```XML
>         let snapshot_span_ty = snapshot_ty(context, span_ty)?;
>         let snapshot_ty = snapshot_ty(context, ty)?;
>         let span_snapshot_ty = get_span_ty(context, snapshot_ty)?;
> ```

I think this is more readable.



_Suggestion:_
```XML
        let snapshot_span_ty = snapshot_ty(context, get_span_ty(context, ty.clone())?)?;
        let span_snapshot_ty = get_span_ty(context, snapshot_ty(context, ty)?)?;
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 399 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3236#-NXASCTkA2ldRl88nIF0:-NXASCTkA2ldRl88nIF1:brhumzt) ([raw file](https://github.com/starkware-libs/cairo/blob/40f9357c3496fa0806af5b48d43a06c94799a385/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L399)):*
> ```XML
> pub struct SpanToSnapshotSpanLibfuncWrapped {}
> impl SignatureAndTypeGenericLibfunc for SpanToSnapshotSpanLibfuncWrapped {
>     const STR_ID: &'static str = "span_to_span_snapshot";
> ```

Same here.

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3236)* status: 10 of 14 files reviewed, 27 unresolved discussions (waiting on @orizi, @span, @spapinistarkware, and @t)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3236)* status: 11 of 14 files reviewed, 27 unresolved discussions (waiting on @orizi, @span, @spapinistarkware, and @t)

**Pull request closed without merging**
