### PR TITLE
Add const type, and use it for felt252.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
**Stack**:
- #4624
- #4623
- #4583 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4583)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 7 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4583)* status: 7 of 14 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/const_type.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4583#-NlsNPH85AHbgU-z1_Ha:-NlsNPH85AHbgU-z1_Hb:bsnx7hi) ([raw file](https://github.com/starkware-libs/cairo/blob/af9d5b8dd13f91be51aa0f03d0e6cd5ceb765777/crates/cairo-lang-sierra-to-casm/src/invocations/const_type.rs#L12)):*
> ```XML
> use crate::relocations::{Relocation, RelocationEntry};
> 
> /// Builds instructions for Sierra felt252_const operations.
> ```

fix doc.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/const_type.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4583#-NlsNV6dCSvhUptqg8Tw:-NlsNV6dCSvhUptqg8Tx:b-l6mkjh) ([raw file](https://github.com/starkware-libs/cairo/blob/af9d5b8dd13f91be51aa0f03d0e6cd5ceb765777/crates/cairo-lang-sierra-to-casm/src/invocations/const_type.rs#L18)):*
> ```XML
> ) -> Result<CompiledInvocation, InvocationError> {
>     match libfunc {
>         ConstConcreteLibfunc::IntoFelt252(libfunc) => build_into_felt252(libfunc, builder),
> ```

rename
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/const_type.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4583#-NlsNRwZ0LvO51nSXpRM:-NlsNRwZ0LvO51nSXpRN:b-l6mkjh) ([raw file](https://github.com/starkware-libs/cairo/blob/af9d5b8dd13f91be51aa0f03d0e6cd5ceb765777/crates/cairo-lang-sierra-to-casm/src/invocations/const_type.rs#L22)):*
> ```XML
> }
> 
> pub fn build_into_felt252(
> ```

rename
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/const_type.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4583#-NlsNcAB47HCquYXaR63:-NlsNcAB47HCquYXaR64:bb0xnat) ([raw file](https://github.com/starkware-libs/cairo/blob/af9d5b8dd13f91be51aa0f03d0e6cd5ceb765777/crates/cairo-lang-sierra-to-casm/src/invocations/const_type.rs#L30)):*
> ```XML
>     builder.const_segment_info.insert(const_type.clone());
>     let ctx = casm! {
>         // The relocation will point the `call` to the `ret;` instruction that prepends the relevant const.
> ```

long  line
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/const_type.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4583#-NlsNelB9490Asx4CthX:-NlsNelB9490Asx4CthY:b-eav4az) ([raw file](https://github.com/starkware-libs/cairo/blob/af9d5b8dd13f91be51aa0f03d0e6cd5ceb765777/crates/cairo-lang-sierra-to-casm/src/invocations/const_type.rs#L32)):*
> ```XML
>         // The relocation will point the `call` to the `ret;` instruction that prepends the relevant const.
>         call rel 0;
>         // The relocation table will change the address to `[ap - 1]` (which now contains `pc`) + the const offset, i.e. the const address.
> ```

lone line
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/const_type.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4583#-NlsOd3o1q_hTd5ZmV-n:-NlsOd3o1q_hTd5ZmV-o:b-3ves6t) ([raw file](https://github.com/starkware-libs/cairo/blob/af9d5b8dd13f91be51aa0f03d0e6cd5ceb765777/crates/cairo-lang-sierra-to-casm/src/invocations/const_type.rs#L33)):*
> ```XML
>         call rel 0;
>         // The relocation table will change the address to `[ap - 1]` (which now contains `pc`) + the const offset, i.e. the const address.
>         [ap] = [ap - 1] + 1, ap++;
> ```

in general unstored - [ap] + `constant offset` could have been returned - is this somehow possible?
(then you'd have ap-change 2 - and cost 2 steps only)



_Code quote:_
```XML
 [ap] = [ap - 1] + 1, ap++;
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs` line 247 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4583#-NlsNDUeDh0DFuuQoECM:-NlsNDUf1Cixmcq5lhmU:b-dcrvil) ([raw file](https://github.com/starkware-libs/cairo/blob/af9d5b8dd13f91be51aa0f03d0e6cd5ceb765777/crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs#L247)):*
> ```XML
>         call rel 0;
>         // After calling an empty function, `[ap - 1]` contains the current `pc`.
>         // Using the relocations below, the immediate value (`offset`) will be changed so that it will
> ```

long line

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4583)* status: 6 of 15 files reviewed, 7 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/const_type.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4583#-NlsNPH85AHbgU-z1_Ha:-Nlx3jJL-h_P8od9Y7WY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/af9d5b8dd13f91be51aa0f03d0e6cd5ceb765777/crates/cairo-lang-sierra-to-casm/src/invocations/const_type.rs#L12)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix doc.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/const_type.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4583#-NlsNV6dCSvhUptqg8Tw:-Nlx3jjV0MKV-FtIBJJs:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/af9d5b8dd13f91be51aa0f03d0e6cd5ceb765777/crates/cairo-lang-sierra-to-casm/src/invocations/const_type.rs#L18)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rename
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/const_type.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4583#-NlsNRwZ0LvO51nSXpRM:-Nlx3kKq44-7dQvM9iAU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/af9d5b8dd13f91be51aa0f03d0e6cd5ceb765777/crates/cairo-lang-sierra-to-casm/src/invocations/const_type.rs#L22)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rename
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/const_type.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4583#-NlsNcAB47HCquYXaR63:-Nlx40Ll9xlq1000dcKn:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/af9d5b8dd13f91be51aa0f03d0e6cd5ceb765777/crates/cairo-lang-sierra-to-casm/src/invocations/const_type.rs#L30)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

long  line
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/const_type.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4583#-NlsNelB9490Asx4CthX:-Nlx40sQ1T54GbAoE5Oz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/af9d5b8dd13f91be51aa0f03d0e6cd5ceb765777/crates/cairo-lang-sierra-to-casm/src/invocations/const_type.rs#L32)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

lone line
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/const_type.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4583#-NlsOd3o1q_hTd5ZmV-n:-Nlx78Ph70CcC-XtNp_Y:b-hce471) ([raw file](https://github.com/starkware-libs/cairo/blob/af9d5b8dd13f91be51aa0f03d0e6cd5ceb765777/crates/cairo-lang-sierra-to-casm/src/invocations/const_type.rs#L33)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

in general unstored - [ap] + `constant offset` could have been returned - is this somehow possible?
(then you'd have ap-change 2 - and cost 2 steps only)
</blockquote></details>

Added todo.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs` line 247 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4583#-NlsNDUeDh0DFuuQoECM:-Nlx5KTXEPdvDi9aR55x:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/af9d5b8dd13f91be51aa0f03d0e6cd5ceb765777/crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs#L247)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

long line
</blockquote></details>

Done.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4583)* status: 8 of 15 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 54 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4583#-Nlx7_a24iBcwQuhE3Cc:-NlxJwGI9lNL94ZU3IK7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2f57e66a29efeee47e882be4ad38474b845f814d/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L54)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

be more defensive - this cannot be store - but let us make sure this cannot have a usable instance.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 114 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4583#-NlxBiRSEwOZWOSJz3s_:-Nm0AxZW6NUFL7_M4qlK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2f57e66a29efeee47e882be4ad38474b845f814d/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L114)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

for all `unwrap`s - explain why would never happen.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/const_type.rs` line 22 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4583#-Nlx8yEZ53Zr_6Hn_65F:-Nm0AydA6Lm5sIMZv4t4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2f57e66a29efeee47e882be4ad38474b845f814d/crates/cairo-lang-sierra-to-casm/src/invocations/const_type.rs#L22)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

try finding a better name - "into" implies conversion.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-type-size/src/lib.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4583#-Nlx9_4o8vAO4-qGtKBk:-NlxGb3D786DAxXdPHKs:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2f57e66a29efeee47e882be4ad38474b845f814d/crates/cairo-lang-sierra-type-size/src/lib.rs#L74)):*
> ```XML
>                 Some(size)
>             }
>             CoreTypeConcrete::Const(_) => Some(0),
> ```

Done.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4583)* status: 8 of 15 files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 57 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4583#-Nm0WPnh22ZNLaNquBoC:-Nm0WPnh22ZNLaNquBoD:b4b5l9x) ([raw file](https://github.com/starkware-libs/cairo/blob/8271017d027b85745359a175d787f0dc7c60fb84/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L57)):*
> ```XML
>     ConstDataMismatch,
>     #[error("#Unsupported const type: todo")]
>     UnsupportedConstType,
> ```

Fixing these



_Code quote:_
```XML
    #[error("#Const data mismatch: todo")]
    ConstDataMismatch,
    #[error("#Unsupported const type: todo")]
    UnsupportedConstType,
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 14 files at r1, 5 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4583)* status: 14 of 15 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 91 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4583#-Nm0WJPk5bVnhjKKcfvk:-Nm0WJPk5bVnhjKKcfvl:bjc3xcv) ([raw file](https://github.com/starkware-libs/cairo/blob/8271017d027b85745359a175d787f0dc7c60fb84/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L91)):*
> ```XML
> pub struct ConstAsBoxLibfuncWrapped {}
> impl ConstAsBoxLibfuncWrapped {
>     // A zero-input function that returns a box of the const value according to the generic arg type
> ```

this is not the place for this doc.
Possibly this is the structs doc.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4583#-:-Nm0palA9a9FJ9Es3J2j:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4583)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 132 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4583#-NmajtPz0EiGBWo88VyY:-NmajtPz0EiGBWo88VyZ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/4e417cbf6360f2060f8a49bb9b1cc764098bd9bb/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L132)):*
> ```XML
> }
> /// The data of a single const in the const segment.
> #[derive(Debug, Eq, PartialEq, Default)]
> ```





_Suggestion:_
```XML
}

/// The data of a single const in the const segment.
#[derive(Debug, Eq, PartialEq, Default)]
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4583)* status: 14 of 15 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 50 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4583#-NmbYP056nRaF-h_exOq:-NmbYP063DCd0bi71kJg:b67mu1v) ([raw file](https://github.com/starkware-libs/cairo/blob/e0a0ba93e7a934f0466efb72e32d15602a3595de/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L50)):*
> ```XML
>             .ok_or(SpecializationError::UnsupportedGenericArg)?;
>         // Extract the rest of the arguments as the inner data.
>         // TODO(Gil): Validate that the inner data matches the inner type.
> ```

don't you already know it by construction?

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4583)* status: 14 of 15 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 91 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4583#-Nm0WJPk5bVnhjKKcfvk:-Nmjvr0e8hjmn4yfoGdd:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8271017d027b85745359a175d787f0dc7c60fb84/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L91)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is not the place for this doc.
Possibly this is the structs doc.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 50 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4583#-NmbYP056nRaF-h_exOq:-NmjvJ5fBa4kqfLK5-L0:b-8yhl77) ([raw file](https://github.com/starkware-libs/cairo/blob/e0a0ba93e7a934f0466efb72e32d15602a3595de/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L50)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

don't you already know it by construction?
</blockquote></details>

Only in #4624 when `extract_bounds` is used.
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 132 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4583#-NmajtPz0EiGBWo88VyY:-Nmjw66yAzrSbbTNUsrS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4e417cbf6360f2060f8a49bb9b1cc764098bd9bb/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L132)):*
> ```XML
> }
> /// The data of a single const in the const segment.
> #[derive(Debug, Eq, PartialEq, Default)]
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4583)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 72 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4583#-Nmk0k5KDqwoxVObRBGS:-Nmk0k5KDqwoxVObRBGT:b2ngwfe) ([raw file](https://github.com/starkware-libs/cairo/blob/6b55a47382a126c14bfb94b5f30734bfd38724ba/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L72)):*
> ```XML
>     }
> }
> ```

///
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler_test.rs` line 903 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4583#-Nmk0wAf352O1CmhC2y-:-Nmk0wAf352O1CmhC2y0:b-yee3r) ([raw file](https://github.com/starkware-libs/cairo/blob/4e417cbf6360f2060f8a49bb9b1cc764098bd9bb/crates/cairo-lang-sierra-to-casm/src/compiler_test.rs#L903)):*
> ```XML
> #[test_case(indoc! {"
>             type felt252 = felt252;
>             type const<felt252, 5, 3> = const<felt252, 5, 3>;
> ```

Do it on another type instead.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4583)* status: 13 of 15 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 72 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4583#-Nmk0k5KDqwoxVObRBGS:-NmkBtwA81KAxUVVvMZX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6b55a47382a126c14bfb94b5f30734bfd38724ba/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L72)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

///
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler_test.rs` line 903 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4583#-Nmk0wAf352O1CmhC2y-:-NmkBu8f1J3OqaPx1OtF:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4e417cbf6360f2060f8a49bb9b1cc764098bd9bb/crates/cairo-lang-sierra-to-casm/src/compiler_test.rs#L903)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Do it on another type instead.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4583#-:-NmkTPuI3NptT_x5J47D:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4583)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Comment by gilbens-starkware** [comment]
✓ Commit merged in pull request [#4624](https://github.com/starkware-libs/cairo/pull/4624)

**Pull request merged**
