### PR TITLE
added support for underscore pattern in match on tuples

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4996)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4996)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/lower_match.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4996#-NpooLNR968HSvUJ4aUR:-NpooLNR968HSvUJ4aUS:b-de1eee) ([raw file](https://github.com/starkware-libs/cairo/blob/a979a71873c403f890431ad564b83e41d06858fc/crates/cairo-lang-lowering/src/lower/lower_match.rs#L105)):*
> ```XML
>                 )));
>             };
>             //
> ```

I believe some push was missed.



_Code quote:_
```XML
            //
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4996)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/lower_match.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4996#-NpooLNR968HSvUJ4aUR:-NpotS8s9csrCBqzv_un:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/a979a71873c403f890431ad564b83e41d06858fc/crates/cairo-lang-lowering/src/lower/lower_match.rs#L105)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I believe some push was missed.
</blockquote></details>

Done

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4996)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/test_data/match` line 1510 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4996#-NpovsG62vlnUIAr6boS:-NpovsG62vlnUIAr6boT:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e96ebf6f01fab76fde017bddd414a24d4f988f32/crates/cairo-lang-lowering/src/test_data/match#L1510)):*
> ```
>         (true,true) => 1,
>         _ => 2
>     }
> ```





_Suggestion:_
```
fn foo() -> felt252 {
    match (true, false) {
        (true, true) => 1,
        _ => 2
    }
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4996)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4996#-:-NpsaqfbCZ5JNQ27dVxm:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4996)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
