### PR TITLE
LS: Make database swapping use benefits of new architecture

### PR DESCRIPTION
**Pull request by mkaput**

### CODE REVIEW

**Comment by lotem-starkware** [comment]
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6495)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6495#-:-O9HCPK7EryXZUpQnp9e:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @piotmag769)

**Review by piotmag769 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6495#-:-O9HZtKO5Fmwi7caa7_J:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)

**Review by Arcticae — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6495)* status: all files reviewed, 1 unresolved discussion (waiting on @Draggu and @mkaput)

___
*[`crates/cairo-lang-language-server/src/lang/db/swapper.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6495#-O9JRiKB3u4KsIr1BHMW:-O9JRiKB3u4KsIr1BHMX:b-mi82nq) ([raw file](https://github.com/starkware-libs/cairo/blob/30bc7fc0013199fa4e034bdfcd5c96ccdffcb974/crates/cairo-lang-language-server/src/lang/db/swapper.rs#L29)):*
> ```XML
> ///
> /// The new database has a clean state.
> /// It is expected that diagnostics will be refreshed on it as quickly as possible.
> ```

What happens if this contract is not satisified?

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6495)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae and @Draggu)

___
*[`crates/cairo-lang-language-server/src/lang/db/swapper.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6495#-O9JRiKB3u4KsIr1BHMW:-O9JSmUTC80FeSbHIIFi:b-7o36xx) ([raw file](https://github.com/starkware-libs/cairo/blob/30bc7fc0013199fa4e034bdfcd5c96ccdffcb974/crates/cairo-lang-language-server/src/lang/db/swapper.rs#L29)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

What happens if this contract is not satisified?
</blockquote></details>

diagnostics would be recomputed on first mutation, so that could cause UX delays

**Comment by Arcticae** [comment]
*[`crates/cairo-lang-language-server/src/lang/db/swapper.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6495#-O9JRiKB3u4KsIr1BHMW:-O9JTL9b7Nrrk42P9EYT:b-2b2dsv) ([raw file](https://github.com/starkware-libs/cairo/blob/30bc7fc0013199fa4e034bdfcd5c96ccdffcb974/crates/cairo-lang-language-server/src/lang/db/swapper.rs#L29)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

diagnostics would be recomputed on first mutation, so that could cause UX delays
</blockquote></details>

not obvious to the reader, if we want to dive this deep in the explanation :stuck_out_tongue:

**Review by piotmag769 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6495)* status: all files reviewed, 2 unresolved discussions (waiting on @Draggu and @mkaput)

___
*[`crates/cairo-lang-language-server/src/lang/db/swapper.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6495#-O9JuFhw3ucBsKBfFyzW:-O9JuFhw3ucBsKBfFyzX:b-37fkwi) ([raw file](https://github.com/starkware-libs/cairo/blob/30bc7fc0013199fa4e034bdfcd5c96ccdffcb974/crates/cairo-lang-language-server/src/lang/db/swapper.rs#L63)):*
> ```XML
>             new_db
>         }) else {
>             return;
> ```

Shouldn't we `error!` log here? Btw I don't see a case where this could panic actually, we have mutable reference to the db

**Review by Draggu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6495)* status: all files reviewed, 5 unresolved discussions (waiting on @mkaput)

___
*[`crates/cairo-lang-language-server/src/lang/db/swapper.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6495#-O9KC_x7CQKNSgK8GdhT:-O9KC_x7CQKNSgK8GdhU:b-fn68bi) ([raw file](https://github.com/starkware-libs/cairo/blob/30bc7fc0013199fa4e034bdfcd5c96ccdffcb974/crates/cairo-lang-language-server/src/lang/db/swapper.rs#L52)):*
> ```XML
>         tricks: &Tricks,
>     ) {
>         let Ok(elapsed) = self.last_replace.elapsed() else { return };
> ```

This can fail only if system time went backward, shouldn't we at least `error!`/`debug!` here?
___
*[`crates/cairo-lang-language-server/src/lang/db/swapper.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6495#-O9KC312C9a4XSuQNaRv:-O9KC312C9a4XSuQNaRw:b-oo9oy1) ([raw file](https://github.com/starkware-libs/cairo/blob/30bc7fc0013199fa4e034bdfcd5c96ccdffcb974/crates/cairo-lang-language-server/src/lang/db/swapper.rs#L74)):*
> ```XML
> /// Makes sure that all open files exist in the new db, with their current changes.
> #[tracing::instrument(level = "trace", skip_all)]
> fn ensure_exists_in_db<'a>(
> ```

why not a part of `AnalysisDatabaseSwapper`?
___
*[`crates/cairo-lang-language-server/src/lang/db/swapper.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6495#-O9KCLuS0IV4GE3xsDe5:-O9KCLuS0IV4GE3xsDe6:bipqi12) ([raw file](https://github.com/starkware-libs/cairo/blob/30bc7fc0013199fa4e034bdfcd5c96ccdffcb974/crates/cairo-lang-language-server/src/lang/db/swapper.rs#L82)):*
> /// Makes sure that all open files exist in the new db, with their current changes.

How does this ensure that file exists in db?

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6495)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae and @Draggu)

___
*[`crates/cairo-lang-language-server/src/lang/db/swapper.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6495#-O9JRiKB3u4KsIr1BHMW:-O9JlszWDTaGlHtb4d1L:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/30bc7fc0013199fa4e034bdfcd5c96ccdffcb974/crates/cairo-lang-language-server/src/lang/db/swapper.rs#L29)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

not obvious to the reader, if we want to dive this deep in the explanation :stuck_out_tongue:
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lang/db/swapper.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6495#-O9KC_x7CQKNSgK8GdhT:-O9KNuM98FiYd40-4k9j:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/30bc7fc0013199fa4e034bdfcd5c96ccdffcb974/crates/cairo-lang-language-server/src/lang/db/swapper.rs#L52)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

This can fail only if system time went backward, shouldn't we at least `error!`/`debug!` here?
</blockquote></details>

Done
___
*[`crates/cairo-lang-language-server/src/lang/db/swapper.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6495#-O9JuFhw3ucBsKBfFyzW:-O9KNj928QOWi1LJ6OjR:beu7a8t) ([raw file](https://github.com/starkware-libs/cairo/blob/30bc7fc0013199fa4e034bdfcd5c96ccdffcb974/crates/cairo-lang-language-server/src/lang/db/swapper.rs#L63)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Shouldn't we `error!` log here? Btw I don't see a case where this could panic actually, we have mutable reference to the db
</blockquote></details>

1. Added error.
2. I'm just protecting ourselves from compiler bugs (unwanted unwrap calls)
___
*[`crates/cairo-lang-language-server/src/lang/db/swapper.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6495#-O9KC312C9a4XSuQNaRv:-O9KMxTV3P5dLykrQIMm:bcyhy5w) ([raw file](https://github.com/starkware-libs/cairo/blob/30bc7fc0013199fa4e034bdfcd5c96ccdffcb974/crates/cairo-lang-language-server/src/lang/db/swapper.rs#L74)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

why not a part of `AnalysisDatabaseSwapper`?
</blockquote></details>

it doesn't make use of the swapper's state, so it doesn't have to be a method

and I avoid putting non-self functions in struct impls if not needed, it brings no value except adding `Self::` noise everywhere
___
*[`crates/cairo-lang-language-server/src/lang/db/swapper.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6495#-O9KCLuS0IV4GE3xsDe5:-O9KNJca9lmk3Y0E9JNc:blqh9j) ([raw file](https://github.com/starkware-libs/cairo/blob/30bc7fc0013199fa4e034bdfcd5c96ccdffcb974/crates/cairo-lang-language-server/src/lang/db/swapper.rs#L82)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

> /// Makes sure that all open files exist in the new db, with their current changes.

How does this ensure that file exists in db?
</blockquote></details>

```rust
            v this is pulling FileLongId from old DB
file_id.lookup_intern(old_db).intern(new_db)
                                  ^ this is putting it in a new DB making it exist there
```

**Review by Draggu — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6495)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lang/db/swapper.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6495#-O9KCLuS0IV4GE3xsDe5:-O9KZZOg2H8iFgTK9Raa:bm8sdnl) ([raw file](https://github.com/starkware-libs/cairo/blob/30bc7fc0013199fa4e034bdfcd5c96ccdffcb974/crates/cairo-lang-language-server/src/lang/db/swapper.rs#L82)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

```rust
            v this is pulling FileLongId from old DB
file_id.lookup_intern(old_db).intern(new_db)
                                  ^ this is putting it in a new DB making it exist there
```
</blockquote></details>

I had in mind this `continue`,  case in which file didn't exist in `old_db` we skips it in new one. Im not sure if this is correct, also it is inconsistent with mentioned comment

**Review by piotmag769 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6495)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae and @mkaput)

**Review by Arcticae — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6495)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6495)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lang/db/swapper.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6495#-O9KCLuS0IV4GE3xsDe5:-O9PgAx1-Xz1RjAnO4h8:b87vwzo) ([raw file](https://github.com/starkware-libs/cairo/blob/30bc7fc0013199fa4e034bdfcd5c96ccdffcb974/crates/cairo-lang-language-server/src/lang/db/swapper.rs#L82)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

I had in mind this `continue`,  case in which file didn't exist in `old_db` we skips it in new one. Im not sure if this is correct, also it is inconsistent with mentioned comment
</blockquote></details>

Added an explanation comment.

**Pull request merged**
