### PR TITLE
Coupons: Add function::Coupon to semantic.

### PR DESCRIPTION
**Pull request by liorgold2**
**Stack**:
- #4573
- #4572
- #4571
- #4570 ⬅
- #4569

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4570)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 9 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4570)* status: 9 of 13 files reviewed, 3 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-semantic/src/expr/inference/conform.rs` line 397 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4570#-NlmhZ3b199GxiaG5H99:-NlmhZ3b199GxiaG5H9A:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d7bffa6bec3de384a1d503492200d74eeea33990/crates/cairo-lang-semantic/src/expr/inference/conform.rs#L397)):*
> ```XML
>             }
>         };
>         false
> ```





_Suggestion:_
```XML
        self.generic_args_contain_var(&generic_args, var) ||
        matches!(
            function.generic_function,
            GenericFunctionId::Impl(impl_generic_function_id)
            if self.impl_contains_var(&impl_generic_function_id.impl_id, var)
        )
```
___
*[`crates/cairo-lang-semantic/src/expr/inference/solver.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4570#-NlmjYq866JJcJZm2w6k:-NlmjYq90oMQdSAU4na_:b-8rabcj) ([raw file](https://github.com/starkware-libs/cairo/blob/d7bffa6bec3de384a1d503492200d74eeea33990/crates/cairo-lang-semantic/src/expr/inference/solver.rs#L101)):*
> ```XML
>                         .insert_module(concrete.generic_type(db).module_file_id(db.upcast()).0);
>                 }
>                 TypeLongId::Coupon(function_id) => {
> ```

Why do we need coupons and not just types here?
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 693 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4570#-Nlmh54_3zG6Rzn_J739:-Nlmh54_3zG6Rzn_J73A:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d7bffa6bec3de384a1d503492200d74eeea33990/crates/cairo-lang-semantic/src/items/imp.rs#L693)):*
> ```XML
>         }
>         TypeLongId::Missing(diag_added) => {
>             return Err(diag_added);
> ```





_Suggestion:_
```XML
        TypeLongId::Coupon(_) => vec![],
        TypeLongId::Missing(diag_added) => {
            return Err(diag_added);
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4570)* status: 9 of 13 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/inference/conform.rs` line 397 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4570#-NlmhZ3b199GxiaG5H99:-NlnNt9R7X3yKbvKN8iT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d7bffa6bec3de384a1d503492200d74eeea33990/crates/cairo-lang-semantic/src/expr/inference/conform.rs#L397)):*
> ```XML
>             }
>         };
>         false
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/inference/solver.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4570#-NlmjYq866JJcJZm2w6k:-NlnNxlv3OJucZYhNUTA:b-7skhg0) ([raw file](https://github.com/starkware-libs/cairo/blob/d7bffa6bec3de384a1d503492200d74eeea33990/crates/cairo-lang-semantic/src/expr/inference/solver.rs#L101)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Why do we need coupons and not just types here?
</blockquote></details>

To find impls on the Coupon object. This code looks next to the function.
For example, we'll look for `Drop<foo::Coupon>` next to `foo`.

Removing this code gives:
```diff
+error: Trait has no implementation in context: core::traits::Drop::<test::m::bar::Coupon>
+ --> lib.cairo:15:5
+    use_drop(x);
+    ^******^
```
in one of the `coupon` semantic tests.

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4570)* status: 9 of 13 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 693 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4570#-Nlmh54_3zG6Rzn_J739:-NlnOyReBpHUxS8ltJYm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d7bffa6bec3de384a1d503492200d74eeea33990/crates/cairo-lang-semantic/src/items/imp.rs#L693)):*
> ```XML
>         }
>         TypeLongId::Missing(diag_added) => {
>             return Err(diag_added);
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 13 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4570#-:-NlqIaqV96yZjwfjMUX5:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
