### PR TITLE
Add index operator syntax.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2366)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2366)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 616 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2366#-NPmRbsz4Nqw4Ta5tlWc:-NPmRbt-3cAbeaKD2SZt:bddcpyc) ([raw file](https://github.com/starkware-libs/cairo/blob/6df5e87b84c845ca94a7202e729d36024bc8e56d/crates/cairo-lang-parser/src/parser.rs#L616)):*
> ```XML
>             } else if self.peek().kind == SyntaxKind::TerminalLBrack {
>                 let lbrack = self.take::<TerminalLBrack>();
>                 let index_expr = self.parse_expr();
> ```

consider forbidding lbrace.
Add a test with lbrace inside the index expr to find out if it might be problematic.



_Code quote:_
```XML
try_parse_expr_limited
```
___
*[`crates/cairo-lang-parser/src/parser.rs` line 618 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2366#-NPmRmSY67IPHChF_Vbz:-NPmRmSY67IPHChF_Vc-:b-9og5sp) ([raw file](https://github.com/starkware-libs/cairo/blob/6df5e87b84c845ca94a7202e729d36024bc8e56d/crates/cairo-lang-parser/src/parser.rs#L618)):*
> ```XML
>                 let index_expr = self.parse_expr();
>                 let rbrack = self.parse_token::<TerminalRBrack>();
>                 expr = ExprAtIndex::new_green(self.db, expr, lbrack, index_expr, rbrack).into();
> ```

Consider renaming - this may be used in the future for ranges (slices) too.



_Code quote:_
```XML
ExprAtIndex
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2366#-:-NPmXXwh7_f-5mTsqO1d:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 616 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2366#-NPmRbsz4Nqw4Ta5tlWc:-NPmX0be0Dkn4wEpOYGT:b-t1qdju) ([raw file](https://github.com/starkware-libs/cairo/blob/6df5e87b84c845ca94a7202e729d36024bc8e56d/crates/cairo-lang-parser/src/parser.rs#L616)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

consider forbidding lbrace.
Add a test with lbrace inside the index expr to find out if it might be problematic.

</blockquote></details>

why should an lbrace be an issue? shouldn't this be capable of being a block?

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2366)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 616 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2366#-NPmRbsz4Nqw4Ta5tlWc:-NPwQsLD-BR0N9-BkyKb:banch2s) ([raw file](https://github.com/starkware-libs/cairo/blob/6df5e87b84c845ca94a7202e729d36024bc8e56d/crates/cairo-lang-parser/src/parser.rs#L616)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why should an lbrace be an issue? shouldn't this be capable of being a block?
</blockquote></details>

I am not sure if it would be an issue. It is in some places. A test would make it clear if it might be an issue.

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2366)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2366)* status: 2 of 9 files reviewed, 2 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 616 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2366#-NPmRbsz4Nqw4Ta5tlWc:-NQ-JbkB0Rz2G5OVc1df:bv1ucnm) ([raw file](https://github.com/starkware-libs/cairo/blob/6df5e87b84c845ca94a7202e729d36024bc8e56d/crates/cairo-lang-parser/src/parser.rs#L616)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I am not sure if it would be an issue. It is in some places. A test would make it clear if it might be an issue.
</blockquote></details>

Added, also, maybe more interesting a test for a[a[1]]. Done.
___
*[`crates/cairo-lang-parser/src/parser.rs` line 618 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2366#-NPmRmSY67IPHChF_Vbz:-NQ-Jk6I934GvjxIr18c:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6df5e87b84c845ca94a7202e729d36024bc8e56d/crates/cairo-lang-parser/src/parser.rs#L618)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Consider renaming - this may be used in the future for ranges (slices) too.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2366#-:-NQ-MZsJ0khGTL13dNja:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2366#-:-NQ0Gm3RC4rMqPLvl0M2:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-parser/src/parser_test_data/exprs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2366#-NQ0GOIi0T3m6PbBDgqd:-NQ0GOIi0T3m6PbBDgqe:bfha6l7) ([raw file](https://github.com/starkware-libs/cairo/blob/cc68e2f4317eb11e6d63938ddf8dac92a69aa561/crates/cairo-lang-parser/src/parser_test_data/exprs#L33)):*
> ```
> //! > ==========================================================================
> 
> //! > Test index operator
> ```

Why not in the tests with the printed AST?

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2366)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser_test_data/exprs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2366#-NQ0GOIi0T3m6PbBDgqd:-NQ0wgq69BJW1YGqDzxK:b-ytfh9j) ([raw file](https://github.com/starkware-libs/cairo/blob/cc68e2f4317eb11e6d63938ddf8dac92a69aa561/crates/cairo-lang-parser/src/parser_test_data/exprs#L33)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Why not in the tests with the printed AST?
</blockquote></details>

No special reason, the exprs tests are using the get_diagnostics runner, and it seems weird to change it for all the exprs tests or to put it in it's own file.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2366)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-parser/src/parser_test_data/exprs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2366#-NQ0GOIi0T3m6PbBDgqd:-NQ0yRwW2bVTzPHFhDFz:b-xk1ant) ([raw file](https://github.com/starkware-libs/cairo/blob/cc68e2f4317eb11e6d63938ddf8dac92a69aa561/crates/cairo-lang-parser/src/parser_test_data/exprs#L33)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

No special reason, the exprs tests are using the get_diagnostics runner, and it seems weird to change it for all the exprs tests or to put it in it's own file.
</blockquote></details>

I would like a test showing the new field in cairo_spec in the relevant tree.
It's fine to put in an "array" file. Maybe there will be more tests there in the future, but even if not, it's fine.

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2366)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2366#-:-NQ19HEZ8uyntS6bCECh:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-parser/src/parser_test_data/array` line 1 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2366#-NQ18i4b8KVLFmLbrd62:-NQ18i4b8KVLFmLbrd63:b-3k9r9m) ([raw file](https://github.com/starkware-libs/cairo/blob/24658c1d9d3bfb51d01cc966f338f5e6fc60ddaa/crates/cairo-lang-parser/src/parser_test_data/array#L1)):*
> ```
> //! > Test function call syntax tree
> ```

Thanks for adding the test.
Last requests:
1. Please separate to 4 small tests.
2. Add ExprPath, ExprBlock, ExprBinary to ignored_kinds to reduce the output to focus on the indexing.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2366)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2366)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
