### PR TITLE
Remove allowed libfuncs from ContractClass and add option to pass it …

### PR DESCRIPTION
**Pull request by gilbens-starkware**
…as a file.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2205)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2205)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/src/allowed_libfuncs.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2205#-NOhy0ghDSEeaSC-o4Ic:-NOhy0ghDSEeaSC-o4Id:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/d41b050ef5d2d4cc4d32b2338f1cb8d4fa0d5def/crates/cairo-lang-starknet/src/allowed_libfuncs.rs#L28)):*
> ```XML
>     UnsupportedLibfunc { invalid_libfunc: String, allowed_libfuncs_list_name: String },
> }
> ```

doc



_Code quote:_
```XML
pub enum ListSelector {
```
___
*[`crates/cairo-lang-starknet/src/starknet_sierra_compile.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2205#-NOhyY5Z0xHp3gYmSLGL:-NOhyY5Z0xHp3gYmSLGM:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/d41b050ef5d2d4cc4d32b2338f1cb8d4fa0d5def/crates/cairo-lang-starknet/src/starknet_sierra_compile.rs#L22)):*
> ```XML
>     allowed_libfuncs_list_name: Option<String>,
>     #[arg(long)]
>     allowed_libfuncs_list_file: Option<String>,
> ```

doc



_Code quote:_
```XML
    #[arg(long)]
    allowed_libfuncs_list_file: Option<String>,
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2205)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/allowed_libfuncs.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2205#-NOhy0ghDSEeaSC-o4Ic:-NOi0CPz-DNH13N1Nd0Y:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d41b050ef5d2d4cc4d32b2338f1cb8d4fa0d5def/crates/cairo-lang-starknet/src/allowed_libfuncs.rs#L28)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/starknet_sierra_compile.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2205#-NOhyY5Z0xHp3gYmSLGL:-NOi0AQP7go3eXrot7OG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d41b050ef5d2d4cc4d32b2338f1cb8d4fa0d5def/crates/cairo-lang-starknet/src/starknet_sierra_compile.rs#L22)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2205#-:-NOi0N5F6PtPtJU9nDs_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2205#-:-NOi6HSNCNYFmrJMW1-2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2205)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
