### PR TITLE
Added NonZero to const folding.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #5253
- #5241 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5241)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/test_data/while` line 155 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5241#-Nsqkdrl5qQ6Tl2cM0ui:-Nsqkdrl5qQ6Tl2cM0uj:bqwf7cz) ([raw file](https://github.com/starkware-libs/cairo/blob/0cca09f524ddc79b7717d76dfbc7a58647644c02/crates/cairo-lang-lowering/src/lower/test_data/while#L155)):*
> ```
> 
> //! > function
> fn foo(ref arr: Array<felt252>, mut x: felt252) -> felt252 {
> ```

why did you change it?



_Code quote:_
```
fn foo(ref arr: Array<felt252>, mut x: felt252) -> felt252 {
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5241)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5241)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/lower/test_data/while` line 155 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5241#-Nsqkdrl5qQ6Tl2cM0ui:-NsqmAewAhlCAkVyg49p:biqn9xw) ([raw file](https://github.com/starkware-libs/cairo/blob/e0aaa57afb721799af32cc0df54cd5bc82f53f4e/crates/cairo-lang-lowering/src/lower/test_data/while#L155)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why did you change it?
</blockquote></details>

to prevent const folding. (also all other changes)

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5241#-:-Nsr8Dee9O2DgSzTdVv8:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
