### PR TITLE
Handling Visibility Use Star Semantic

### PR DESCRIPTION
**Pull request by Tomer-StarkWare**

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6714)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 252 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6714#-OCDXiZuD7PtABH60vtP:-OCDXiZuD7PtABH60vtQ:b-lw24iu) ([raw file](https://github.com/starkware-libs/cairo/blob/9a5f8a338a5a057a79c8677cd1f64d06cb172148/crates/cairo-lang-semantic/src/resolve/mod.rs#L252)):*
> ```XML
>     accessible_modules: OrderedHashSet<(ModuleId, ModuleId)>,
>     // TODO(Tomer-StarkWare): consider changing the from all_modules to inaccessible_modules
>     all_modules: OrderedHashSet<ModuleId>,
> ```

doc all.



_Code quote:_
```XML
struct ImportedModules {
    accessible_modules: OrderedHashSet<(ModuleId, ModuleId)>,
    // TODO(Tomer-StarkWare): consider changing the from all_modules to inaccessible_modules
    all_modules: OrderedHashSet<ModuleId>,
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6714)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 1159 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6714#-OCDZKlbDBXhK4hamQkD:-OCDZKlbDBXhK4hamQkE:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9a5f8a338a5a057a79c8677cd1f64d06cb172148/crates/cairo-lang-semantic/src/resolve/mod.rs#L1159)):*
> ```XML
>                 false => UseStarResult::InaccessiblePath,
>             },
>             None => UseStarResult::PathNotFound,
> ```





_Suggestion:_
```XML
            Some(item_info) => if is_accessible {
                UseStarResult::UniquePathFound(item_info)
            } else { UseStarResult::InaccessiblePath },
            None => UseStarResult::PathNotFound,
```
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 1163 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6714#-OCDZDBz4eEVtm_klaMD:-OCDZDBz4eEVtm_klaME:bb7f2bf) ([raw file](https://github.com/starkware-libs/cairo/blob/9a5f8a338a5a057a79c8677cd1f64d06cb172148/crates/cairo-lang-semantic/src/resolve/mod.rs#L1163)):*
> ```XML
>     }
> 
>     fn resolve_item_in_imported_module(
> ```

doc.
___
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/tests` line 1108 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6714#-OCDZvBqCZmEgjmJlfAU:-OCDZvBqCZmEgjmJlfAV:bvhlcq9) ([raw file](https://github.com/starkware-libs/cairo/blob/9a5f8a338a5a057a79c8677cd1f64d06cb172148/crates/cairo-lang-semantic/src/diagnostic_test_data/tests#L1108)):*
> ```
> mod c {
>     mod d {
>         pub use super::super::a::b::*;
> ```

where is the error caused by `b` not being accesible?



_Code quote:_
```
        pub use super::super::a::b::*;
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6714)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/tests` line 1108 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6714#-OCDZvBqCZmEgjmJlfAU:-OCSDdU48tft5sZM1r1l:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9a5f8a338a5a057a79c8677cd1f64d06cb172148/crates/cairo-lang-semantic/src/diagnostic_test_data/tests#L1108)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

where is the error caused by `b` not being accesible?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 252 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6714#-OCDXiZuD7PtABH60vtP:-OCSEEd9-HK3BzOh5ayK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9a5f8a338a5a057a79c8677cd1f64d06cb172148/crates/cairo-lang-semantic/src/resolve/mod.rs#L252)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc all.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 1163 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6714#-OCDZDBz4eEVtm_klaMD:-OCSFlG09i3TFXyD1gaR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9a5f8a338a5a057a79c8677cd1f64d06cb172148/crates/cairo-lang-semantic/src/resolve/mod.rs#L1163)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 1159 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6714#-OCDZKlbDBXhK4hamQkD:-OCDdArk91s1J_WzdGLr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9a5f8a338a5a057a79c8677cd1f64d06cb172148/crates/cairo-lang-semantic/src/resolve/mod.rs#L1159)):*
> ```XML
>                 false => UseStarResult::InaccessiblePath,
>             },
>             None => UseStarResult::PathNotFound,
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6714)* status: 1 of 7 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 1142 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6714#-OCScmDC9K2OnCfWIsVw:-OCScmDC9K2OnCfWIsVx:buol0uu) ([raw file](https://github.com/starkware-libs/cairo/blob/b2ce385a49768aaf30c67a81f975c2788bf21423/crates/cairo-lang-semantic/src/diagnostic.rs#L1142)):*
> ```XML
>     AmbiguousPath(Vec<ModuleItemId>),
>     UseStarEmptyPath,
>     InaccessiblePath,
> ```

use existing `ItemNotVisible(ModuleItemId),` instead.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6714)* status: 1 of 7 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 1671 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6714#-OCSe1YL2ziUzQfxM2Mo:-OCSe1YM-HvzSp96IpmC:bwu3um3) ([raw file](https://github.com/starkware-libs/cairo/blob/b2ce385a49768aaf30c67a81f975c2788bf21423/crates/cairo-lang-semantic/src/resolve/mod.rs#L1671)):*
> ```XML
>         identifier: &ast::TerminalIdentifier,
>         item_info: &ModuleItemInfo,
>     ) -> bool {
> ```

all functions that add diagnostics should not return a bool - and be called `validate_*`

you should probably have an inner function just returning whether it is visible to make sure everything properly works.
and make the `validate_` function call it.



_Code quote:_
```XML
    ) -> bool {
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6714)* status: 1 of 7 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 1142 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6714#-OCScmDC9K2OnCfWIsVw:-OCSk13a0If0z32SPK6F:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b2ce385a49768aaf30c67a81f975c2788bf21423/crates/cairo-lang-semantic/src/diagnostic.rs#L1142)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

use existing `ItemNotVisible(ModuleItemId),` instead.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 1671 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6714#-OCSe1YL2ziUzQfxM2Mo:-OCSr4Xx46lVoOP9Ty2t:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b2ce385a49768aaf30c67a81f975c2788bf21423/crates/cairo-lang-semantic/src/resolve/mod.rs#L1671)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

all functions that add diagnostics should not return a bool - and be called `validate_*`

you should probably have an inner function just returning whether it is visible to make sure everything properly works.
and make the `validate_` function call it.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 3 of 5 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6714)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 1119 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6714#-OCSs8_sA97K8A0qL7O5:-OCSs8_t04bxtUrP5NU_:b-eez8r8) ([raw file](https://github.com/starkware-libs/cairo/blob/5c65ddba46ec9af79206973a7b974edf1761a9d3/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L1119)):*
> ```
> //! > ==========================================================================
> 
> //! > Testing use star imported non public module
> ```

add `crate-setting` in all the new tests.
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 1186 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6714#-OCSsVg79WEUrDIU2eOq:-OCSsVg79WEUrDIU2eOr:brg1orp) ([raw file](https://github.com/starkware-libs/cairo/blob/5c65ddba46ec9af79206973a7b974edf1761a9d3/crates/cairo-lang-semantic/src/resolve/mod.rs#L1186)):*
> ```XML
> 
>     /// Returns the modules that are imported with `use *` in the current module.
>     fn module_use_star_modules(&self, module_id: ModuleId) -> ImportedModules {
> ```

add some comments in the function about the different parts of it.
___
*[`crates/cairo-lang-semantic/src/items/module.rs` line 146 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6714#-OCSsJyB35E2JwvfEJSb:-OCSsJyB35E2JwvfEJSc:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/5c65ddba46ec9af79206973a7b974edf1761a9d3/crates/cairo-lang-semantic/src/items/module.rs#L146)):*
> ```XML
> }
> 
> pub fn get_module_global_uses(
> ```

doc

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6714)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 1119 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6714#-OCSs8_sA97K8A0qL7O5:-OCT4M9mAizXG2qtI5Ya:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5c65ddba46ec9af79206973a7b974edf1761a9d3/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L1119)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add `crate-setting` in all the new tests.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/module.rs` line 146 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6714#-OCSsJyB35E2JwvfEJSb:-OCT4_PN-Ee2yv9o5hjN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5c65ddba46ec9af79206973a7b974edf1761a9d3/crates/cairo-lang-semantic/src/items/module.rs#L146)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 1186 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6714#-OCSsVg79WEUrDIU2eOq:-OCT5K7UDjNdbpPCqja0:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5c65ddba46ec9af79206973a7b974edf1761a9d3/crates/cairo-lang-semantic/src/resolve/mod.rs#L1186)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add some comments in the function about the different parts of it.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6714#-:-OCT6qDl1A42Sep53Xtq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6714)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
