### PR TITLE
Add profiling of circuit usage.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5860)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5860)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`examples/circuit.cairo` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5860#-O08QbQ4DvnIK7UHIXhe:-O08QbQ5-6fCEGz9V3gx:b-ka2h7m) ([raw file](https://github.com/starkware-libs/cairo/blob/98283632ee66af97a92f7a82b51c5ad4d2ee582c/examples/circuit.cairo#L9)):*
> ```Cairo
> 
> 
> pub fn eval_circuit() -> u384 {
> ```

any reason to not inline this in the `circuit` test file?

**Comment by ilyalesokhin-starkware** [comment]
*[`examples/circuit.cairo` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5860#-O08QbQ4DvnIK7UHIXhe:-O0JG_QA5u-glCayuJyF:boxq8e6) ([raw file](https://github.com/starkware-libs/cairo/blob/98283632ee66af97a92f7a82b51c5ad4d2ee582c/examples/circuit.cairo#L9)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

any reason to not inline this in the `circuit` test file?
</blockquote></details>

I didn't know it was possible.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5860)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`examples/circuit.cairo` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5860#-O08QbQ4DvnIK7UHIXhe:-O0JGdsG5cyOtmQu79kt:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/98283632ee66af97a92f7a82b51c5ad4d2ee582c/examples/circuit.cairo#L9)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I didn't know it was possible.
</blockquote></details>

Done

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5860)* status: 2 of 88 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @mkaput)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5860#-O0JI4e80hZWu4QnK6a5:-O0JI4e80hZWu4QnK6a6:b-ffwyof) (no related file):*
let move to 2.7.0.

___

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r2, 85 of 85 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5860#-:-O0JWO6nCHQODvYaawa7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Review by mkaput — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5860)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
