### PR TITLE
Add Add trait

### PR DESCRIPTION
**Pull request by spapinistarkware**
commit-id:52dc9a9b

### CODE REVIEW

**Review by spapinistarkware — COMMENTED** [review]
There iss extra cost, which is cause by the extra callblock we have today in inlining

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1850#-:-NMP7vlK8PX56CFAkm06:b3iaut0)* status: 0 of 53 files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 49 of 53 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1850)* status: 49 of 53 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 444 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1850#-NMPAifd6EJwgexiYuEo:-NMPAifd6EJwgexiYuEp:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/990eb9f08902e791ebc629fa5538b09640f65271/crates/cairo-lang-semantic/src/corelib.rs#L444)):*
> ```XML
> }
> 
> fn get_core_trait_function_infer(
> ```

doc



_Code quote:_
```XML
fn get_core_trait_function_infer(
```
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1475 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1850#-NMPB0gL76MjmVfK31Py:-NMPB0gL76MjmVfK31Pz:bejokwv) ([raw file](https://github.com/starkware-libs/cairo/blob/990eb9f08902e791ebc629fa5538b09640f65271/crates/cairo-lang-semantic/src/expr/compute.rs#L1475)):*
> ```XML
>         eprintln!(
>             "A {:?}  {:?}  {:?}",
>             function_id.debug(ctx.db.elongate()),
> ```

leftover?



_Code quote:_
```XML
        eprintln!(
            "A {:?}  {:?}  {:?}",
            function_id.debug(ctx.db.elongate()),
            arg_typ.debug(ctx.db.elongate()),
            param_typ.debug(ctx.db.elongate())
        );
```
___
*[`tests/test_data/fib_u128.sierra` line 125 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1850#-NMPTSNICduzHq97YtZL:-NMPTSNICduzHq97YtZM:b-zf016m) ([raw file](https://github.com/starkware-libs/cairo/blob/990eb9f08902e791ebc629fa5538b09640f65271/tests/test_data/fib_u128.sierra#L125)):*
> ```
> jump() { 82() };
> branch_align() -> ();
> enum_init<core::PanicResult::<core::integer::u128>, 1>([9]) -> ([11]);
> ```

that seems like more than the extra block.



_Code quote:_
```
enum_match<core::PanicResult::<core::integer::u128>>([4]) { 73([8]) 76([9]) };
branch_align() -> ();
store_temp<u128>([8]) -> ([10]);
jump() { 82() };
branch_align() -> ();
enum_init<core::PanicResult::<core::integer::u128>, 1>([9]) -> ([11]);
store_temp<RangeCheck>([3]) -> ([12]);
store_temp<core::PanicResult::<core::integer::u128>>([11]) -> ([11]);
rename<core::PanicResult::<core::integer::u128>>([11]) -> ([13]);
return([12], [13]);
enum_init<core::PanicResult::<core::integer::u128>, 0>([10]) -> ([14]);
store_temp<RangeCheck>([3]) -> ([15]);
store_temp<core::PanicResult::<core::integer::u128>>([14]) -> ([14]);
rename<core::PanicResult::<core::integer::u128>>([14]) -> ([16]);
return([15], [16]);
store_temp<RangeCheck>([0]) -> ([5]);
store_temp<u128>([1]) -> ([6]);
store_temp<u128>([2]) -> ([7]);
function_call<user@core::integer::u128_checked_sub>([5], [6], [7]) -> ([3], [4]);
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1850)* status: 39 of 54 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 444 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1850#-NMPAifd6EJwgexiYuEo:-NMSSAlf1O9XR_2BIyYE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/990eb9f08902e791ebc629fa5538b09640f65271/crates/cairo-lang-semantic/src/corelib.rs#L444)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1475 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1850#-NMPB0gL76MjmVfK31Py:-NMSSGMV2GMVKwMUU6iP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/990eb9f08902e791ebc629fa5538b09640f65271/crates/cairo-lang-semantic/src/expr/compute.rs#L1475)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

leftover?
</blockquote></details>

Done.
___
*[`tests/test_data/fib_u128.sierra` line 125 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1850#-NMPTSNICduzHq97YtZL:-NMSUsdz1lG-WXxDaUgl:b-f4qxmu) ([raw file](https://github.com/starkware-libs/cairo/blob/990eb9f08902e791ebc629fa5538b09640f65271/tests/test_data/fib_u128.sierra#L125)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

that seems like more than the extra block.
</blockquote></details>

Right... There is an extra user function :( `fib -> U128Add::add -> u128_add`

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 53 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1850#-:-NMUV65I5TCxO4BLBTMe:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1850)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
