### PR TITLE
Preparation for supporting multiple gas token types.

### PR DESCRIPTION
**Pull request by liorgold2**
commit-id:81e0bff0

---

**Stack**:
- #1183
- #1169
- #1168
- #1167
- #1166 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1166#-:-NI7KzZZ8kAalQ8jPkTz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1166#-:-NI7TwnE34egx-LR1Eev:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1166)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1166)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
