### PR TITLE
Fix offset_in_builtin_costs.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2127)

### CODE REVIEW

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2127)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/builtin_cost.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2127#-NOFCQdL3Ipko68z4nfg:-NOFCQdM0Ay95YALChCl:bn533mq) ([raw file](https://github.com/starkware-libs/cairo/blob/07688b7add63b3c97642bc0592be0945c6eef213/crates/cairo-lang-sierra/src/extensions/modules/builtin_cost.rs#L61)):*
> ```XML
>             CostTokenType::Pedersen => 0,
>             // CostTokenType::RangeCheck (unused) => 1,
>             // CostTokenType::Ecdsa => 2,
> ```

We don't support Ecdsa in Cairo1 (no completeness).

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2127)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/builtin_cost.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2127#-NOFCYBg-Pwl7Aoy4Erb:-NOFCYBg-Pwl7Aoy4Erc:b-7c612j) ([raw file](https://github.com/starkware-libs/cairo/blob/07688b7add63b3c97642bc0592be0945c6eef213/crates/cairo-lang-sierra/src/extensions/modules/builtin_cost.rs#L60)):*
> ```XML
>             }
>             CostTokenType::Pedersen => 0,
>             // CostTokenType::RangeCheck (unused) => 1,
> ```

Why do you have range check here?

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2127)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2127)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @liorgold2)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/builtin_cost.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2127#-NOFCYBg-Pwl7Aoy4Erb:-NOFCozY66Y6Z2idyrxw:b-esa4l4) ([raw file](https://github.com/starkware-libs/cairo/blob/07688b7add63b3c97642bc0592be0945c6eef213/crates/cairo-lang-sierra/src/extensions/modules/builtin_cost.rs#L60)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Why do you have range check here?
</blockquote></details>

Consistent builtin order through the OS.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2127)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/builtin_cost.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2127#-NOFCQdL3Ipko68z4nfg:-NOFDC-PCqep54Ajhm4n:b-qqf7z8) ([raw file](https://github.com/starkware-libs/cairo/blob/07688b7add63b3c97642bc0592be0945c6eef213/crates/cairo-lang-sierra/src/extensions/modules/builtin_cost.rs#L61)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

same as above.
</blockquote></details>

But ECDSA will eventually be removed. So I don't think this is a good idea.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2127)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/builtin_cost.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2127#-NOFDKzM2kWUxIRcFlVa:-NOFDKzM2kWUxIRcFlVb:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/07688b7add63b3c97642bc0592be0945c6eef213/crates/cairo-lang-sierra/src/extensions/modules/builtin_cost.rs#L60)):*
> ```XML
>             }
>             CostTokenType::Pedersen => 0,
>             // CostTokenType::RangeCheck (unused) => 1,
> ```

.



_Suggestion:_
```XML
            // RangeCheck (unused) => 1,
```

**Comment by ilyalesokhin-starkware** [comment]
We've decided to omit range_check and ecdsa from the list so the current offsets are ok.

**Pull request closed without merging**
