### PR TITLE
Collect diagnostics in parallel

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5999)

### CODE REVIEW

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5999#-:-O1RKmHb8gGE9OHybP51:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5999)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 108 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5999#-O1RKoly4gBSysBh66Pm:-O1RKoly4gBSysBh66Pn:b-3cf8fm) ([raw file](https://github.com/starkware-libs/cairo/blob/2ed257062118895f84459a490eac7dd4943baa63/crates/cairo-lang-compiler/src/diagnostics.rs#L108)):*
> ```XML
> 
>         // Collect diagnostics in parallel.
>         for crate_id in crates.clone() {
> ```

I think we'll need an ability to constrain the amount of parallelization in Scarb tests to get deterministic outputs, cc @maciektr ?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 108 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5999#-O1RKoly4gBSysBh66Pm:-O1RO_es2iXJSfKVStog:b-dup6us) ([raw file](https://github.com/starkware-libs/cairo/blob/2ed257062118895f84459a490eac7dd4943baa63/crates/cairo-lang-compiler/src/diagnostics.rs#L108)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I think we'll need an ability to constrain the amount of parallelization in Scarb tests to get deterministic outputs, cc @maciektr ?
</blockquote></details>

I only fill out the queries here, and I collect the diagnostics in deterministic order.

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5999)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5999)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5999#-O1voG-P8Ov8a4vkqg1F:-O1voG-P8Ov8a4vkqg1G:b-otlqw4) ([raw file](https://github.com/starkware-libs/cairo/blob/2ed257062118895f84459a490eac7dd4943baa63/crates/cairo-lang-compiler/src/diagnostics.rs#L130)):*
> ```XML
>                 }
>             });
>         }
> ```

i think this probably needs to be external to this function - so not everyone will have to use it.



_Code quote:_
```XML
        // Collect diagnostics in parallel.
        for crate_id in crates.clone() {
            let snapshot = salsa::ParallelDatabase::snapshot(db);
            rayon::spawn(move || {
                let db = &*snapshot;

                let crate_modules = (*db.crate_modules(crate_id)).clone();
                for module_id in crate_modules {
                    let snapshot = salsa::ParallelDatabase::snapshot(db);
                    rayon::spawn(move || {
                        let db = &*snapshot;
                        for file_id in
                            db.module_files(module_id).unwrap_or_default().iter().copied()
                        {
                            db.file_syntax_diagnostics(file_id);
                        }

                        let _ = db.module_semantic_diagnostics(module_id);

                        let _ = db.module_lowering_diagnostics(module_id);
                    });
                }
            });
        }
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5999)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5999#-O1voG-P8Ov8a4vkqg1F:-O1zCRc06MCEWGbfW6DT:by14730) ([raw file](https://github.com/starkware-libs/cairo/blob/2ed257062118895f84459a490eac7dd4943baa63/crates/cairo-lang-compiler/src/diagnostics.rs#L130)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i think this probably needs to be external to this function - so not everyone will have to use it.
</blockquote></details>

It would force me to duplicate the following logic:



_Code snippet:_
```XML
let crates = if self.crate_ids.is_empty() { db.crates() } else { self.crate_ids.clone() };
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5999)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @mkaput)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5999#-O1voG-P8Ov8a4vkqg1F:-O1zSjlo3oGRDmXathXZ:bbuuomw) ([raw file](https://github.com/starkware-libs/cairo/blob/2ed257062118895f84459a490eac7dd4943baa63/crates/cairo-lang-compiler/src/diagnostics.rs#L130)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

It would force me to duplicate the following logic:
</blockquote></details>

you can at least just export it to a method.
___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 173 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5999#-O1zSz9j4hQ0EzxmAhhi:-O1zSz9j4hQ0EzxmAhhj:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e67fd4826c2b0627b83ef3173142d86094bc9f93/crates/cairo-lang-compiler/src/diagnostics.rs#L173)):*
> ```XML
>     }
> 
>     /// spawns threads to compute the diagnostics queries.
> ```





_Suggestion:_
```XML
    /// Spawns threads to compute the diagnostics queries, making sure later calls for these queries would be faster as the queries were already computed.
```

**Review by mkaput — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5999)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5999#-O1voG-P8Ov8a4vkqg1F:-O1zcdWs8ni5FffOHlpn:b-skpuld) ([raw file](https://github.com/starkware-libs/cairo/blob/2ed257062118895f84459a490eac7dd4943baa63/crates/cairo-lang-compiler/src/diagnostics.rs#L130)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you can at least just export it to a method.
</blockquote></details>

as an user of this crate I'd rather expect this to be a configuration option rather than separate set of functions

the fact that parallelism happens here is an implementation detail than API boundary imho

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5999)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5999#-O1voG-P8Ov8a4vkqg1F:-O1zcno3C7H3ZUgmXuXk:basvne8) ([raw file](https://github.com/starkware-libs/cairo/blob/2ed257062118895f84459a490eac7dd4943baa63/crates/cairo-lang-compiler/src/diagnostics.rs#L130)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

as an user of this crate I'd rather expect this to be a configuration option rather than separate set of functions

the fact that parallelism happens here is an implementation detail than API boundary imho
</blockquote></details>

esp. I think if you set max parallelism to 1, rayon becomes quite transparent?

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5999)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 174 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5999#-O1zd1Ru0jK9LUSPYKeU:-O1zd1Rv75GshPUGj9xj:be17zcf) ([raw file](https://github.com/starkware-libs/cairo/blob/e67fd4826c2b0627b83ef3173142d86094bc9f93/crates/cairo-lang-compiler/src/diagnostics.rs#L174)):*
> ```XML
> 
>     /// spawns threads to compute the diagnostics queries.
>     pub fn warm_up_diagnostics(&self, db: &RootDatabase) {
> ```

Does this have to become API boundary? What's the consequence of not calling this method?

**Review by mkaput — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5999)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5999)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @mkaput)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5999#-O1voG-P8Ov8a4vkqg1F:-O1zdR8rEiV2ITzWxOa9:b-ayafwn) ([raw file](https://github.com/starkware-libs/cairo/blob/2ed257062118895f84459a490eac7dd4943baa63/crates/cairo-lang-compiler/src/diagnostics.rs#L130)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

esp. I think if you set max parallelism to 1, rayon becomes quite transparent?
</blockquote></details>

the parallelism is through warming up the db - not through the actual call - so it does not make sense as a configuration.
in the end - the exact same code is called.
the only question is was the db previously handeled.
___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 174 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5999#-O1zd1Ru0jK9LUSPYKeU:-O1zdmCHC5isGAbgC8Z_:balm6vz) ([raw file](https://github.com/starkware-libs/cairo/blob/e67fd4826c2b0627b83ef3173142d86094bc9f93/crates/cairo-lang-compiler/src/diagnostics.rs#L174)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Does this have to become API boundary? What's the consequence of not calling this method?
</blockquote></details>

it is only `warmup` - nothing would occur differently.

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5999)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5999#-O1voG-P8Ov8a4vkqg1F:-O1zeus5E1R-3QAZgMf_:b-b8mckw) ([raw file](https://github.com/starkware-libs/cairo/blob/2ed257062118895f84459a490eac7dd4943baa63/crates/cairo-lang-compiler/src/diagnostics.rs#L130)):*
> the parallelism is through warming up the db

TBH to me as potential user this sounds counterintuitive. But I think I'm getting away from original clue of this thread so let's ignore this comment in this thread

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5999)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @mkaput)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 174 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5999#-O1zd1Ru0jK9LUSPYKeU:-O1zfO-00ztAqpm2f700:b-92tmfr) ([raw file](https://github.com/starkware-libs/cairo/blob/e67fd4826c2b0627b83ef3173142d86094bc9f93/crates/cairo-lang-compiler/src/diagnostics.rs#L174)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

So why do we need this method at all? Why do we need to add new stuff to public API? Why could it not be done under the hood automatically?

I think answers to all this questions should at least be included in documentation for this function :)
</blockquote></details>

indeed - but in any case - definitely *should not* happen automatically under the hood - we have no need for a function that does more than the strictly required minimum - as adding the parallelisation adds a significant cost that should not happen automatically.

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5999)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 174 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5999#-O1zd1Ru0jK9LUSPYKeU:-O1zfw16ExHLjBPDmcYy:b-bsyfz3) ([raw file](https://github.com/starkware-libs/cairo/blob/e67fd4826c2b0627b83ef3173142d86094bc9f93/crates/cairo-lang-compiler/src/diagnostics.rs#L174)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

indeed - but in any case - definitely *should not* happen automatically under the hood - we have no need for a function that does more than the strictly required minimum - as adding the parallelisation adds a significant cost that should not happen automatically.
</blockquote></details>

understood. please, please document this in code for other people

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5999#-O1voG-P8Ov8a4vkqg1F:-O1zp2LU97BwjFpjGLkZ:b-z2rfo7) ([raw file](https://github.com/starkware-libs/cairo/blob/2ed257062118895f84459a490eac7dd4943baa63/crates/cairo-lang-compiler/src/diagnostics.rs#L130)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

> the parallelism is through warming up the db

TBH to me as potential user this sounds counterintuitive. But I think I'm getting away from original clue of this thread so let's ignore this comment in this thread
</blockquote></details>

I don't think doing the parallelization at the crate level is a good idea.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 174 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5999#-O1zd1Ru0jK9LUSPYKeU:-O1zpIoP31aozDNEaGqZ:blzxhg8) ([raw file](https://github.com/starkware-libs/cairo/blob/e67fd4826c2b0627b83ef3173142d86094bc9f93/crates/cairo-lang-compiler/src/diagnostics.rs#L174)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

understood. please, please document this in code for other people
</blockquote></details>

What would you like to document?
The fact that there is no consequence to not calling this function?

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5999)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 174 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5999#-O1zd1Ru0jK9LUSPYKeU:-O1zsRgX5wFyhAi62jZ2:bt96869) ([raw file](https://github.com/starkware-libs/cairo/blob/e67fd4826c2b0627b83ef3173142d86094bc9f93/crates/cairo-lang-compiler/src/diagnostics.rs#L174)):*
> So why do we need this method at all? Why do we need to add new stuff to public API? Why could it not be done under the hood automatically?

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5999)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 174 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5999#-O1zd1Ru0jK9LUSPYKeU:-O1zsWtr8rpuI1ES2XtU:b-kd9t2h) ([raw file](https://github.com/starkware-libs/cairo/blob/e67fd4826c2b0627b83ef3173142d86094bc9f93/crates/cairo-lang-compiler/src/diagnostics.rs#L174)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

> So why do we need this method at all? Why do we need to add new stuff to public API? Why could it not be done under the hood automatically?
</blockquote></details>

and what actually “warming up” mean because this is not obvious

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 174 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5999#-O1zd1Ru0jK9LUSPYKeU:-O1ztyFP5IwZU3ziVJtC:b8z5pmi) ([raw file](https://github.com/starkware-libs/cairo/blob/e67fd4826c2b0627b83ef3173142d86094bc9f93/crates/cairo-lang-compiler/src/diagnostics.rs#L174)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

and what actually “warming up” mean because this is not obvious
</blockquote></details>

I prefer someone who doesn't understand it not to use this api.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5999)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 173 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5999#-O1zSz9j4hQ0EzxmAhhi:-O1ztuZb2Ct20jn0--l0:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e67fd4826c2b0627b83ef3173142d86094bc9f93/crates/cairo-lang-compiler/src/diagnostics.rs#L173)):*
> ```XML
>     }
> 
>     /// spawns threads to compute the diagnostics queries.
> ```

Done.

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5999)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 174 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5999#-O1zd1Ru0jK9LUSPYKeU:-O1zwhEN9Q8S2TnXwRpn:bw2xsz4) ([raw file](https://github.com/starkware-libs/cairo/blob/e67fd4826c2b0627b83ef3173142d86094bc9f93/crates/cairo-lang-compiler/src/diagnostics.rs#L174)):*
> I prefer someone who doesn't understand it not to use this api.

I see that you made this `pub(crate)`, so at least my argument for API is now kind of solved. But don't you think that the fact that I asked these questions isn't meaning that probably anybody looking at this code in future wouldn't be probable to also ask them?

To be precise, I'd expect having a separate paragraph answering each topic, but do as you wish here.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 174 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5999#-O1zd1Ru0jK9LUSPYKeU:-O2-1-717Z4Tx1L7Bw6w:b-7syvik) ([raw file](https://github.com/starkware-libs/cairo/blob/e67fd4826c2b0627b83ef3173142d86094bc9f93/crates/cairo-lang-compiler/src/diagnostics.rs#L174)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

> I prefer someone who doesn't understand it not to use this api.

I see that you made this `pub(crate)`, so at least my argument for API is now kind of solved. But don't you think that the fact that I asked these questions isn't meaning that probably anybody looking at this code in future wouldn't be probable to also ask them?

To be precise, I'd expect having a separate paragraph answering each topic, but do as you wish here.
</blockquote></details>

I want it to be a non-api member functions, I don't want people to use it.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5999)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 100 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5999#-O2-1yPu4IYUbW_v_zg3:-O2-1yPu4IYUbW_v_zg4:bb7f2bf) ([raw file](https://github.com/starkware-libs/cairo/blob/fe72d372d3a2eb2c48edfa638d13e1665a4cebc8/crates/cairo-lang-compiler/src/diagnostics.rs#L100)):*
> ```XML
>     }
> 
>     fn get_creates_on_interest(&self, db: &RootDatabase) -> Vec<CrateId> {
> ```

doc.
___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 100 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5999#-O2-22_J-MmElEfkWmXB:-O2-22_J-MmElEfkWmXC:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/fe72d372d3a2eb2c48edfa638d13e1665a4cebc8/crates/cairo-lang-compiler/src/diagnostics.rs#L100)):*
> ```XML
>     }
> 
>     fn get_creates_on_interest(&self, db: &RootDatabase) -> Vec<CrateId> {
> ```





_Suggestion:_
```XML
    fn crates_of_interest(&self, db: &RootDatabase) -> Vec<CrateId> {
```

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5999)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 174 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5999#-O1zd1Ru0jK9LUSPYKeU:-O2-2qYi2QkU1o6CidTA:b-z3fsly) ([raw file](https://github.com/starkware-libs/cairo/blob/e67fd4826c2b0627b83ef3173142d86094bc9f93/crates/cairo-lang-compiler/src/diagnostics.rs#L174)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I want it to be a non-api member functions, I don't want people to use it.
</blockquote></details>

I understand you, but now I'm talking about the perspective of a dev who is trying to contribute to this codebase

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5999)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 100 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5999#-O2-22_J-MmElEfkWmXB:-O2-3DVmDUYEKObMpjcb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fe72d372d3a2eb2c48edfa638d13e1665a4cebc8/crates/cairo-lang-compiler/src/diagnostics.rs#L100)):*
> ```XML
>     }
> 
>     fn get_creates_on_interest(&self, db: &RootDatabase) -> Vec<CrateId> {
> ```

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5999)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 100 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5999#-O2-1yPu4IYUbW_v_zg3:-O2-3LE856Waju21ytMj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fe72d372d3a2eb2c48edfa638d13e1665a4cebc8/crates/cairo-lang-compiler/src/diagnostics.rs#L100)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5999#-:-O2-6VLo0hZOvseKvmMG:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by mkaput — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5999)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
