### PR TITLE
Refactor syntax-gen.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #6465
- #6464 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6464)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-syntax-codegen/src/generator.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6464#-O8ekffW5u2ZeRaB2r87:-O8ekffX5Y4ZUtCgVOzP:bs5dxat) ([raw file](https://github.com/starkware-libs/cairo/blob/f05654e8faef14f0b89cebb34dbf33afdabbf077/crates/cairo-lang-syntax-codegen/src/generator.rs#L117)):*
> ```XML
> }
> 
> fn name_tokens<'a, 'b>(
> ```

Do you need different lifetimes?



_Code quote:_
```XML
'a, 'b
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-syntax-codegen/src/generator.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6464#-O8eky_4DiAwlEeAhb14:-O8eky_4DiAwlEeAhb15:b1gfp7z) ([raw file](https://github.com/starkware-libs/cairo/blob/f05654e8faef14f0b89cebb34dbf33afdabbf077/crates/cairo-lang-syntax-codegen/src/generator.rs#L119)):*
> ```XML
> fn name_tokens<'a, 'b>(
>     spec: &'a [Node],
>     predicate: impl Fn(&NodeKind) -> bool,
> ```

document the purpose of the predicate?



_Code quote:_
```XML
    predicate: impl Fn(&NodeKind) -> bool,
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6464)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-syntax-codegen/src/generator.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6464#-O8ekffW5u2ZeRaB2r87:-O8gtsQM7zjJZIJ9HUn-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f05654e8faef14f0b89cebb34dbf33afdabbf077/crates/cairo-lang-syntax-codegen/src/generator.rs#L117)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Do you need different lifetimes?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-syntax-codegen/src/generator.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6464#-O8eky_4DiAwlEeAhb14:-O8gttpOCbGXMJhQqZQx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f05654e8faef14f0b89cebb34dbf33afdabbf077/crates/cairo-lang-syntax-codegen/src/generator.rs#L119)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

document the purpose of the predicate?
</blockquote></details>

Done.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6464#-:-O8pGOFY9tZ7v-2ULpE8:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Pull request merged**
