### PR TITLE
Made arguments to functions in run injected through vm and not code.

### PR DESCRIPTION
**Pull request by orizi**

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
yes - the args (including the gas builtin) are just not a part of the code - but their size is allocated in code, and the VM fills them.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6489#-:-O9Fvf7JEfDh36LzL6Gs:b-iio4k3)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware and @ilyalesokhin-starkware)

**Comment by lotem-starkware** [comment]
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6489)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-runner/src/lib.rs` line 672 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6489#-O9himuB-hXvfbU65rIi:-O9himuCCNvmLCTgVu4E:b-19ultw) ([raw file](https://github.com/starkware-libs/cairo/blob/b9046996f85e03446a9637900aff43061b510e48/crates/cairo-lang-runner/src/lib.rs#L672)):*
> ```XML
>                 let offset = ap_offset - used_args;
>                 for _ in 0..*ty_size {
>                     casm_extend!(ctx, [ap + 0] = [ap - offset], ap++;);
> ```

can't you put the `ap_offset += params_size;` before the builtins instead of copying the parameters??



_Code quote:_
```XML
casm_extend!(ctx, [ap + 0] = [ap - offset], ap++;);
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6489)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

**Review by ilyalesokhin-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6489)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-runner/src/lib.rs` line 651 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6489#-O9nOM0GDXoy4MfdXMeg:-O9nOM0H8aBHNPxxt54a:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b9046996f85e03446a9637900aff43061b510e48/crates/cairo-lang-runner/src/lib.rs#L651)):*
> ```XML
>         let mut used_args = 0;
>         for ty in param_types {
>             let (generic_ty, ty_size) = ty;
> ```





_Suggestion:_
```XML
        for (generic_ty, ty_size) in param_types {
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-runner/src/lib.rs` line 671 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6489#-O9nOcLT2Upba71ZINHr:-O9nOcLU4qxs8VIfcxkh:b-4in7nz) ([raw file](https://github.com/starkware-libs/cairo/blob/b9046996f85e03446a9637900aff43061b510e48/crates/cairo-lang-runner/src/lib.rs#L671)):*
> ```XML
>             } else {
>                 let offset = ap_offset - used_args;
>                 for _ in 0..*ty_size {
> ```

do you support a param that is not a felt on an array? 
size > 1?



_Code quote:_
```XML
ty_size
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6489#-:-O9nN-lSDsdCFN5FQsRe:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6489)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 651 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6489#-O9nOM0GDXoy4MfdXMeg:-O9oQJk6-jARoO5kDIaR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b9046996f85e03446a9637900aff43061b510e48/crates/cairo-lang-runner/src/lib.rs#L651)):*
> ```XML
>         let mut used_args = 0;
>         for ty in param_types {
>             let (generic_ty, ty_size) = ty;
> ```

Done.
___
*[`crates/cairo-lang-runner/src/lib.rs` line 671 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6489#-O9nOcLT2Upba71ZINHr:-O9oQRO0AjqKexLnWlOW:bbzsrwi) ([raw file](https://github.com/starkware-libs/cairo/blob/b9046996f85e03446a9637900aff43061b510e48/crates/cairo-lang-runner/src/lib.rs#L671)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

do you support a param that is not a felt on an array? 
size > 1?
</blockquote></details>

yes - structs that hold multiple such elements fully work.

**Review by ilyalesokhin-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6489)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @gilbens-starkware and @piotmag769)

**Pull request merged**
