### PR TITLE
Used casm builder for builtin-cost.

### PR DESCRIPTION
**Pull request by orizi**
Fixes ap-change to be constant by it as well.

commit-id:6ded66af

---

**Stack**:
- #1369
- #1368
- #1367
- #1366
- #1365 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1365)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`tests/test_data/hash_chain_gas.casm` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1365#-NJ_jxF6AGlJZRseKo7H:-NJ_jxF6AGlJZRseKo7I:b2sif5) ([raw file](https://github.com/starkware-libs/cairo/blob/b9e50cf0065bb65f48987aa9f3463a6bd1c71a41/tests/test_data/hash_chain_gas.casm#L9)):*
> ```
> [ap + 0] = 0, ap++;
> ret;
> [ap + 1] = [[fp + -3] + 0], ap++;
> ```

This is weird. Why does it start from `1` instead of `0`?
I'd be happier if there weren't any changes in the casm in this PR, and all the optimizations were in a different PR.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1365)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`tests/test_data/hash_chain_gas.casm` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1365#-NJ_kZXOBZy5rH_C5Kj1:-NJ_kZXOBZy5rH_C5Kj2:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/b9e50cf0065bb65f48987aa9f3463a6bd1c71a41/tests/test_data/hash_chain_gas.casm#L14)):*
> ```
> jmp rel 8 if [ap + 1] != 0, ap++;
> [fp + -6] = [ap + 1] + [ap + -1], ap++;
> [ap + 1] = [ap + 0] + 340282366920938463463374607431768211456, ap++;
> ```

?

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1365)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`tests/test_data/hash_chain_gas.casm` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1365#-NJ_jxF6AGlJZRseKo7H:-NJ_khyaBKrX7F1Fk1SQ:by45e5l) ([raw file](https://github.com/starkware-libs/cairo/blob/b9e50cf0065bb65f48987aa9f3463a6bd1c71a41/tests/test_data/hash_chain_gas.casm#L9)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

This is weird. Why does it start from `1` instead of `0`?
I'd be happier if there weren't any changes in the casm in this PR, and all the optimizations were in a different PR.
</blockquote></details>

I invested a lot of time checking that the previous code was complete & sound. Since the changes are not trivial, it will require re-checking this.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1365)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/sierra_gas/src/core_libfunc_cost_base.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1365#-NJ_l1Mu9OMqYalbq647:-NJ_l1Mu9OMqYalbq648:b-7cy6lx) ([raw file](https://github.com/starkware-libs/cairo/blob/b9e50cf0065bb65f48987aa9f3463a6bd1c71a41/crates/sierra_gas/src/core_libfunc_cost_base.rs#L112)):*
> ```XML
>                 .reduce(|x, y| ops.add(x, y));
>             // Compute the (maximal) number of steps for the computation of the requested cost.
>             let compute_requested_cost_steps = BuiltinCostGetGasLibFunc::max_write_steps() as i32;
> ```

What do you mean by `write`?



_Code quote:_
```XML
write
```

**Review by liorgold2 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1365)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/sierra/src/extensions/modules/builtin_cost.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1365#-NJ_pKme8L6TQk_f3ENV:-NJ_pKme8L6TQk_f3ENW:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b9e50cf0065bb65f48987aa9f3463a6bd1c71a41/crates/sierra/src/extensions/modules/builtin_cost.rs#L82)):*
> ```XML
> impl BuiltinCostGetGasLibFunc {
>     /// Returns the maximal number of steps required for the computation of the requested cost.
>     /// All the step also include an AP Change.
> ```





_Suggestion:_
```XML
    /// The number of steps is also the change in `ap` (every step includes `ap++`).
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1365)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @liorgold2)

___
*[`crates/sierra/src/extensions/modules/builtin_cost.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1365#-NJ_pKme8L6TQk_f3ENV:-NJ_st6-5DbEbcFymYt9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b9e50cf0065bb65f48987aa9f3463a6bd1c71a41/crates/sierra/src/extensions/modules/builtin_cost.rs#L82)):*
> ```XML
> impl BuiltinCostGetGasLibFunc {
>     /// Returns the maximal number of steps required for the computation of the requested cost.
>     /// All the step also include an AP Change.
> ```

Done.
___
*[`crates/sierra_gas/src/core_libfunc_cost_base.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1365#-NJ_l1Mu9OMqYalbq647:-NJ_sTb81LBHDL0M0M9Z:bmhlyxn) ([raw file](https://github.com/starkware-libs/cairo/blob/b9e50cf0065bb65f48987aa9f3463a6bd1c71a41/crates/sierra_gas/src/core_libfunc_cost_base.rs#L112)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

What do you mean by `write`?
</blockquote></details>

if you have a good suggestion for name - that would be appreciated.
___
*[`tests/test_data/hash_chain_gas.casm` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1365#-NJ_jxF6AGlJZRseKo7H:-NJ_rRaO7PkEKaLkjK-u:b-bvziy9) ([raw file](https://github.com/starkware-libs/cairo/blob/b9e50cf0065bb65f48987aa9f3463a6bd1c71a41/tests/test_data/hash_chain_gas.casm#L9)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

I invested a lot of time checking that the previous code was complete & sound. Since the changes are not trivial, it will require re-checking this.
</blockquote></details>

no reason to write the original immediate at no point, it can just be added in the steps of the sum (so in the first part we use when summing, we just add the know immedidate of the steps - refund.

will try anyway.
___
*[`tests/test_data/hash_chain_gas.casm` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1365#-NJ_kZXOBZy5rH_C5Kj1:-NJ_s1ji3Rkh_kRc_8C6:b1qcv5r) ([raw file](https://github.com/starkware-libs/cairo/blob/b9e50cf0065bb65f48987aa9f3463a6bd1c71a41/tests/test_data/hash_chain_gas.casm#L14)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

?
</blockquote></details>

in case of an underflow - we just add 2**128 and range check
(similarly to as we do in sub)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1365)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`tests/test_data/hash_chain_gas.casm` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1365#-NJ_jxF6AGlJZRseKo7H:-NJacs1A1SnXSLZc2YWK:bkf4r3q) ([raw file](https://github.com/starkware-libs/cairo/blob/b9e50cf0065bb65f48987aa9f3463a6bd1c71a41/tests/test_data/hash_chain_gas.casm#L9)):*
Non-blocking

> no reason to write the original immediate at no point

Agreed (although, I'd be happy to see this optimization in a different PR)

But it seems to me you're skipping a cell (where do you use `[ap]`?)

**Review by orizi — COMMENTED** [review]
> Dismissed @liorgold2 from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1365)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @gilbens-starkware and @liorgold2)

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1365)* status: 1 of 5 files reviewed, all discussions resolved (waiting on @liorgold2)

___
*[`crates/sierra_gas/src/core_libfunc_cost_base.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1365#-NJ_l1Mu9OMqYalbq647:-NJdX4SY6hB_iTB3-ERC:b-wia3qj) ([raw file](https://github.com/starkware-libs/cairo/blob/b9e50cf0065bb65f48987aa9f3463a6bd1c71a41/crates/sierra_gas/src/core_libfunc_cost_base.rs#L112)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

if you have a good suggestion for name - that would be appreciated.
</blockquote></details>

maybe `max_cost_computation_steps` or `max_computation_steps`?

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1365#-:-NJdaFux-oMltRDomLK-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1365)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
