### PR TITLE
Added support for includable_as attribute in component

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3945)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3945)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs` line 253 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3945#-NcNJqPiAxHgs9FaYLyx:-NcNJqPiAxHgs9FaYLyy:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/08a6d4bc5bba11d444a92ce7a4073a783e8ab6b8/crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs#L253)):*
> ```XML
> }
> 
> fn handle_component_includable_as_impl_function(
> ```

doc
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs` line 277 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3945#-NcNK5SI9GAQ6_nvWWNd:-NcNK5SI9GAQ6_nvWWNe:b83ia81) ([raw file](https://github.com/starkware-libs/cairo/blob/08a6d4bc5bba11d444a92ce7a4073a783e8ab6b8/crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs#L277)):*
> ```XML
>         return None;
>     };
>     // TODO(yg): do this better? (allow whitespaces...)
> ```

don't we already have similar code for view vs external functions in contracts?

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3945)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3945#-NcNJAFqAu50kHE4hQvi:-NcNQQE5EdIBwLWyW2d0:b-37x6k4) ([raw file](https://github.com/starkware-libs/cairo/blob/08a6d4bc5bba11d444a92ce7a4073a783e8ab6b8/crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs#L120)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you'd gonna have a compilation failure in any case - i think we should solve this with just a good diagnostics remappings (since there may be valid values such as "HasComponent  <    TContractState >" which would not work.
</blockquote></details>

This is the todo above... The only problem is that it doesn't allow whitespaces (and :: actually). I think it's ok to start with (we have it in more places for now), then we can improve it if we want.

I think we want to avoid normal compilation errors here, as it would point to generated code which might be confusing.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs` line 253 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3945#-NcNJqPiAxHgs9FaYLyx:-NcNRIZJD0WrH8dzjpt9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/08a6d4bc5bba11d444a92ce7a4073a783e8ab6b8/crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs#L253)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs` line 277 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3945#-NcNK5SI9GAQ6_nvWWNd:-NcNSpXd2DEiDbWAD99B:bzasvah) ([raw file](https://github.com/starkware-libs/cairo/blob/08a6d4bc5bba11d444a92ce7a4073a783e8ab6b8/crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs#L277)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

don't we already have similar code for view vs external functions in contracts?
</blockquote></details>

I guess you are talking about `get_function_signature_inputs_and_mutability`? It relies on semantic data so I can't use it here.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3945)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3945#-NcNJAFqAu50kHE4hQvi:-NcNdUpX-y0Gj7cGWQhH:bt9uyxs) ([raw file](https://github.com/starkware-libs/cairo/blob/08a6d4bc5bba11d444a92ce7a4073a783e8ab6b8/crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs#L120)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

This is the todo above... The only problem is that it doesn't allow whitespaces (and :: actually). I think it's ok to start with (we have it in more places for now), then we can improve it if we want.

I think we want to avoid normal compilation errors here, as it would point to generated code which might be confusing.
</blockquote></details>

ok for now - fix the todo to not include `?`.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3945)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3945#-NcNJAFqAu50kHE4hQvi:-NcNl36B0uoTszM2_0H_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/08a6d4bc5bba11d444a92ce7a4073a783e8ab6b8/crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs#L120)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

ok for now - fix the todo to not include `?`.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3945#-:-NcQAHQZ1AX2rXbDs2Q2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
