### PR TITLE
Feat: Default trait for Array/Dict

### LINKED ISSUE #3046: feat: Default trait
Add the Default trait, similar to rust

### PR DESCRIPTION
**Pull request by wraitii**
Fixes #3046 

This does two things:
- Leverage the existing `Default` trait instead of adding a custom method to ArrayTrait/Felt252DictTrait
- ~~Use that trait to create a simple `new` function that makes code leaner.~~

~~If the `new` function isn't desired, I'll remove it, but I think it's overall a good readability improvement.~~

NB: There is a `new` in BoxTrait that takes an argument. I haven't changed that.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3048)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3048)* status: 0 of 35 files reviewed, 1 unresolved discussion (waiting on @wraitii)

___
*[`corelib/src/lib.cairo` line 11 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3048#-NUpOp5B4MqD824v1g7u:-NUpOp5B4MqD824v1g7v:bz5k2m4) ([raw file](https://github.com/starkware-libs/cairo/blob/e5de0556c17f34e2d1a959966a26c19f92048dbf/corelib/src/lib.cairo#L11)):*
> ```Cairo
> 
> fn new<T, impl TDefault: Default<T>>() -> T {
>     Default::default()
> ```

name is "too useful" - i have no issues with the fn itself - but i think we need a bit of a longer name at the very least.
(and the fact that `Default::default()` would work seems to me to make it less necessary as well)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 2 of 35 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3048)* status: 2 of 35 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/lib.cairo` line 11 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3048#-NUpOp5B4MqD824v1g7u:-NUu5Rf7-CW1PFKpGxbf:bicsof4) ([raw file](https://github.com/starkware-libs/cairo/blob/e5de0556c17f34e2d1a959966a26c19f92048dbf/corelib/src/lib.cairo#L11)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

name is "too useful" - i have no issues with the fn itself - but i think we need a bit of a longer name at the very least.
(and the fact that `Default::default()` would work seems to me to make it less necessary as well)
</blockquote></details>

I don't like this function either. We can use `Default::default()`

**Review by wraitii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3048)* status: 2 of 35 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`corelib/src/lib.cairo` line 11 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3048#-NUpOp5B4MqD824v1g7u:-NUuB9Iu1oqukmWx1QP3:b-v5154x) ([raw file](https://github.com/starkware-libs/cairo/blob/e5de0556c17f34e2d1a959966a26c19f92048dbf/corelib/src/lib.cairo#L11)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I don't like this function either. We can use `Default::default()`
</blockquote></details>

I've removed the function.
I think a shortened form could be useful (perhaps just `default()`), but that would be mostly sidestepped if we had something like `vec![]`

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 21 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3048)* status: 7 of 35 files reviewed, 2 unresolved discussions (waiting on @orizi and @wraitii)

___
*[`corelib/src/debug.cairo` line 24 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3048#-NUvbP2zCeOX2MbxFiwI:-NUvbP3-8MWSoWsyj6wV:b-z4g4r5) ([raw file](https://github.com/starkware-libs/cairo/blob/804a2dda93e4c3842c017b91d3f513e91b5ac316/corelib/src/debug.cairo#L24)):*
> ```Cairo
> 
> fn print_felt252(message: felt252) {
>     let mut arr = Default::default();
> ```

How does this actually work? With no type annotations, it can't know we want an array.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 12 of 35 files at r1, 18 of 21 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3048)* status: 35 of 36 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware and @wraitii)

___
*[`corelib/src/traits.cairo` line 132 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3048#-NVcGSu--_loiMYG3Nhe:-NVcGSu--_loiMYG3Nhf:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/045293b19cdb9f156c1048250d30c641b57609b8/corelib/src/traits.cairo#L132)):*
> ```Cairo
>         @Default::default()
>     }
> }
> ```





_Suggestion:_
```Cairo
impl SnapshotDefault<T, impl TDefault: Default<T>, impl TDrop: Drop<T>> of Default<@T> {
    #[inline(always)]
    fn default() -> @T {
        @Default::default()
    }
}
```

**Review by wraitii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3048)* status: 35 of 36 files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`corelib/src/traits.cairo` line 132 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3048#-NVcGSu--_loiMYG3Nhe:-NVe--ws3YTd1Jp9uzjn:b-896fjx) ([raw file](https://github.com/starkware-libs/cairo/blob/045293b19cdb9f156c1048250d30c641b57609b8/corelib/src/traits.cairo#L132)):*
> ```Cairo
>         @Default::default()
>     }
> }
> ```

Done

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3048#-:-NVxFpAb5gcvzFawr3F7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wraitii)

**Comment by spapinistarkware** [comment]
Looks like there are conflicts. If you resolve them, I'll merge

**Review by orizi — APPROVED** [review]
> Reviewed 16 of 16 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3048)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wraitii)

**Review by orizi — APPROVED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3048)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wraitii)

**Comment by lambda-0x** [comment]
wouldn't it be better to have both `ArrayTrait::new()` and `Default::default()` because when `default` is used and type is not annotated manually it, reader would need to infer the type by looking at the variable usage. 

And I like being more explicit way more. similar to rust where there is `default` but people still prefer to use `new` methods defined on type over default.

**Pull request merged**
