### PR TITLE
Added support for Nz-mul-Nz remaining Nz.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #5716
- #5715 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5715)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 201 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5715#-NzbPvMq1mqJ9seThSbC:-NzbPvMq1mqJ9seThSbD:b-g04cfb) ([raw file](https://github.com/starkware-libs/cairo/blob/3c5e5ac5efb1ba74a544b1e0f4ffe4bab2e0ac5c/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L201)):*
> ```XML
>         }
>         let quotient_min = lhs_range.lower / (&rhs_range.upper - 1);
>         let quotient_max = (&lhs_range.upper - 1) / std::cmp::max(rhs_range.lower, BigInt::one());
> ```

why was this changed?



_Code quote:_
```XML
     let quotient_max = (&lhs_range.upper - 1) / std::cmp::max(rhs_range.lower, BigInt::one());
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5715)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 201 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5715#-NzbPvMq1mqJ9seThSbC:-NzbQwtqENrFgKs8tsf5:b6lcvzr) ([raw file](https://github.com/starkware-libs/cairo/blob/00b5dc0356f2a13054f842873e1d5b55504bf3f5/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L201)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why was this changed?
</blockquote></details>

wrong change should be part of the div-rem branch.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 268 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5715#-NzclxW-5_69uPNi2ZSh:-NzclxW-5_69uPNi2ZSi:byceema) ([raw file](https://github.com/starkware-libs/cairo/blob/098c3c13f26a14f52d5b9e53c90b70fb9d64b800/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L268)):*
> ```XML
>     pub fn try_new(lhs: &Range, rhs: &Range) -> Option<Self> {
>         let prime = Felt252::prime().to_bigint().unwrap();
>         let q_max = (&lhs.upper - 1) / std::cmp::max(&rhs.lower, &BigInt::one());
> ```

move to the correct PR



_Code quote:_
```XML
std::cmp::max(&rhs.lower, &BigInt::one())
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5715)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 268 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5715#-NzclxW-5_69uPNi2ZSh:-NzcomAW81WYKYhyjsmS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/098c3c13f26a14f52d5b9e53c90b70fb9d64b800/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L268)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

move to the correct PR
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5715#-:-NzcxhkG27Pr7DGxo2vn:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
