### PR TITLE
Use sequential block_ids.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2227)

### CODE REVIEW

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2227#-:-NOoaAd98pFmGQKlkdkW:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 285 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2227#-NOo_H1S16pkzQKcKk4y:-NOo_H1S16pkzQKcKk4z:beqwj9x) ([raw file](https://github.com/starkware-libs/cairo/blob/edb337c6b433f3de6f1ffa3d1c2575164365cd94/crates/cairo-lang-lowering/src/inline/mod.rs#L285)):*
> ```XML
>     }
> 
>     /// Renames a var from lowered.blocks to the a new block_id.
> ```

fix comment, consider renaming?
// Translates a block id from the original lowering representation to the equivalent id in the new lowering representation.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2227)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 285 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2227#-NOo_H1S16pkzQKcKk4y:-NOobppK2IVFFdZJgfZx:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/edb337c6b433f3de6f1ffa3d1c2575164365cd94/crates/cairo-lang-lowering/src/inline/mod.rs#L285)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

fix comment, consider renaming?
// Translates a block id from the original lowering representation to the equivalent id in the new lowering representation.
</blockquote></details>

done.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2227#-:-NOoctnc5c5wUauohCof:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 276 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2227#-NOoce7yBHUnrrz8DC50:-NOoce7yBHUnrrz8DC51:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/fdb5be78c6727bcab1a83dd02d30961bcfcb9687/crates/cairo-lang-lowering/src/inline/mod.rs#L276)):*
> ```XML
>     /// Maps a var id from the original lowering representation to the equivalent id in the
>     /// new lowering representation.
>     /// if the variable wasn't assigned an id yet, a new id is assigned and stored for future
> ```





_Suggestion:_
```XML
    /// if the variable wasn't assigned an id yet, a new id is assigned.
```
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 298 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2227#-NOocr4Y4JACe9jdGynP:-NOocr4Y4JACe9jdGynQ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/fdb5be78c6727bcab1a83dd02d30961bcfcb9687/crates/cairo-lang-lowering/src/inline/mod.rs#L298)):*
> ```XML
>     }
> 
>     /// Apply map_var_id to all the variable in the `remapping`.
> ```





_Suggestion:_
```XML
   /// Applies map_var_id to all the variable in the `remapping`.
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2227#-:-NOodZbc3E4ItPP9WSJf:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Pull request merged**
