### PR TITLE
Prevented compilation of bad merges of non-stack variables.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #3186
- #3185
- #3184
- #3183
- #3170 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3170)

### CODE REVIEW

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3170#-:-NVZxz2V0QZDk7YUVCYs:bnfp4nl)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @orizi)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3170)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 207 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3170#-NV_619t6qSRv8g-qJ2N:-NV_619t6qSRv8g-qJ2O:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5d56748a72bafa29fc09ad0dfe81870bca2e344c/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L207)):*
> ```XML
>                 return false;
>             }
>             // Check if the non-stack variable case.
> ```





_Suggestion:_
```XML
            // Check the case of a variable not in the stack.
```
___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 210 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3170#-NV_6Kgz0SeBHLCNBjNc:-NV_6Kgz0SeBHLCNBjNd:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5d56748a72bafa29fc09ad0dfe81870bca2e344c/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L210)):*
> ```XML
>             if stack_idx.is_none() {
>                 // We consider empty variables as ap dependent, since we don't know their actual
>                 // source.
> ```





_Suggestion:_
```XML
                // We consider empty variables as ap-dependent since we don't know their actual
                // source.
```

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3170)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 220 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3170#-NV_NdQfAj6GQwa3g_Ym:-NV_NdQfAj6GQwa3g_Yn:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a5b1cb6cf2c47faf7a5cfaa35e7f97eb883568ee/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L220)):*
> ```XML
>                 if is_ap_dependent {
>                     // Ap tracking must be enabled when merging non-stack ap-dependent variables.
>                     if matches!(actual.environment.ap_tracking, ApTracking::Enabled { .. }) {
> ```





_Suggestion:_
```XML
                    if !matches!(actual.environment.ap_tracking, ApTracking::Enabled { .. }) {
```

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3170)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi and @spapinistarkware)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3170)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 208 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3170#-NVZx-KfCu3Vi4-EUkDw:-NV_6EPD1v_vgTiUke9F:b-p7dvvm) ([raw file](https://github.com/starkware-libs/cairo/blob/e4f0bb9aca9bef0d0aca9be856cb91001648bf36/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L208)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this would be somewhat dangerous if we ever add an additional check afterwards.
</blockquote></details>

I agree with Ori - since the loop is doing more than just this `if`, "early continue" is dangerous.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3170)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 220 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3170#-NV_NdQfAj6GQwa3g_Ym:-NV_jIfY1z7dKxP5Of-t:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a5b1cb6cf2c47faf7a5cfaa35e7f97eb883568ee/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L220)):*
> ```XML
>                 if is_ap_dependent {
>                     // Ap tracking must be enabled when merging non-stack ap-dependent variables.
>                     if matches!(actual.environment.ap_tracking, ApTracking::Enabled { .. }) {
> ```

Done.

**Review by liorgold2 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3170)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3170)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3170#-NVZwu8w-5gjMSFgeYgB:-NVc3fCH4Gka7edLawyI:b-4guyb8) ([raw file](https://github.com/starkware-libs/cairo/blob/e4f0bb9aca9bef0d0aca9be856cb91001648bf36/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L213)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

I understand the first one, not this one. If it's not ap_dependent we can always merge it. It can even be before the stack check.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3170)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3170#-NVZwu8w-5gjMSFgeYgB:-NVcCkCa2Qc4lHWmRZ2u:b2gvpo0) ([raw file](https://github.com/starkware-libs/cairo/blob/e4f0bb9aca9bef0d0aca9be856cb91001648bf36/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L213)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I understand the first one, not this one. If it's not ap_dependent we can always merge it. It can even be before the stack check.
</blockquote></details>

it is the same issue - i don't know if someone would add another check after this if - and this would hide it.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3170)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 208 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3170#-NVZx-KfCu3Vi4-EUkDw:-NVcUAHqAwnJhwgW6rm8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e4f0bb9aca9bef0d0aca9be856cb91001648bf36/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L208)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

I agree with Ori - since the loop is doing more than just this `if`, "early continue" is dangerous.
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3170#-:-NVcrLlb973QPEobaRRA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3170)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 423 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3170#-NViygc5BSouOuwyF6tw:-NViygc5BSouOuwyF6tx:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/30609e100408de48b04cfd9ce863eab070353b32/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L423)):*
> ```XML
> }
> 
> /// Returns whether or not `actual` and `expected` references for the same var are consistent.
> ```





_Suggestion:_
```XML
/// Returns whether or not the references `actual` and `expected` are consistent and can be merged
/// in a way that will be re-compilable.
```
___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 438 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3170#-NVizHMNEDaUW1wg7p-e:-NVizHMNEDaUW1wg7p-f:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/30609e100408de48b04cfd9ce863eab070353b32/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L438)):*
> ```XML
>     // Check if the variable can be merged.
> 
>     // If the variable is on stack it can always be merged.
> ```

.



_Suggestion:_
```XML
 // If the variable is on the stack, it can always be merged.
```

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3170)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 429 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3170#-NVizZzV-frETYujFXmL:-NVizZzW5NzJp5Jy_hMR:b5jlqu9) ([raw file](https://github.com/starkware-libs/cairo/blob/30609e100408de48b04cfd9ce863eab070353b32/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L429)):*
> ```XML
>     ap_tracking_enabled: bool,
> ) -> bool {
>     // Check if the variable doesn't match on type, expression or stack information.
> ```

Move this if out of this function (it'll improve readability. Shahar is ok with it)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3170)* status: all files reviewed, 3 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 423 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3170#-NViygc5BSouOuwyF6tw:-NVj3e0A51p82aY7bC_m:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/30609e100408de48b04cfd9ce863eab070353b32/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L423)):*
> ```XML
> }
> 
> /// Returns whether or not `actual` and `expected` references for the same var are consistent.
> ```

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 429 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3170#-NVizZzV-frETYujFXmL:-NVj3dlP-UMHzi_TvIak:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/30609e100408de48b04cfd9ce863eab070353b32/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L429)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Move this if out of this function (it'll improve readability. Shahar is ok with it)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 438 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3170#-NVizHMNEDaUW1wg7p-e:-NVj3wy963_dma9vd7XF:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/30609e100408de48b04cfd9ce863eab070353b32/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L438)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by liorgold2 — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3170)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
