### PR TITLE
Add storage node mutable variant.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5929)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5929)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin/storage_node.rs` line 270 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5929#-O0mNVQR0lRehk2dRY3f:-O0mNVQR0lRehk2dRY3g:bsnx7hi) ([raw file](https://github.com/starkware-libs/cairo/blob/b7205560febdd15b30aac705ecae589304b8c29f/crates/cairo-lang-starknet/src/plugin/storage_node.rs#L270)):*
> ```XML
> }
> 
> /// Generates the trait and impl for a storage node.
> ```

fix doc.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5929)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin/storage_node.rs` line 270 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5929#-O0mgu807Do54F34661q:-O0mgu810vThEZdYBJhs:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/199b8d61165a6ddab31686532e99f6118f3fb595/crates/cairo-lang-starknet/src/plugin/storage_node.rs#L270)):*
> ```XML
> }
> 
> /// Generates the storage node structs (two variants, mutable and immutable) and their contrtor
> ```

?



_Code quote:_
```XML
contrtor
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5929)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/storage_node.rs` line 270 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5929#-O0mgu807Do54F34661q:-O0mkJCQEbMRDJohNPoF:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c489eaeda5ae750a59612f54c79733af802d6a33/crates/cairo-lang-starknet/src/plugin/storage_node.rs#L270)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5929#-:-O0mkvdl8JbgKshpu-Me:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
