### PR TITLE
Unite Structured representation with Flat

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2342)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2342** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2342" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2342?utm_source=stack-comment).

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 31 of 31 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2342#-:-NPWW9zJ5aSq9u24HgAc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 31 of 31 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2342#-:-NPWyB8fAXj1StdSo3qY:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/objects/blocks.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2342#-NPWwsydDWLYRvN9nDgG:-NPWwsydDWLYRvN9nDgH:bfev5j) ([raw file](https://github.com/starkware-libs/cairo/blob/1b4997a8c4f1bbab1e06cc0d063589a3d5d827f2/crates/cairo-lang-lowering/src/objects/blocks.rs#L106)):*
> ```XML
> 
> pub type StructuredBlocks = Blocks<StructuredBlock>;
> pub type FlatBlocks = Blocks<FlatBlock>;
> ```

Now that we only really use one type of Block in Blocks, do we want to keep it generic?
___
*[`crates/cairo-lang-sierra-generator/src/block_generator.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2342#-NPWxegH8_g1UJj_oEhF:-NPWxegH8_g1UJj_oEhG:buzu9fu) ([raw file](https://github.com/starkware-libs/cairo/blob/9eca8fce11751ae9764a5e712c7ae6ff13e3455a/crates/cairo-lang-sierra-generator/src/block_generator.rs#L106)):*
> ```XML
>             unreachable!("Panics should have been stripped in a previous phase.")
>         }
>         lowering::FlatBlockEnd::Goto(block_id, remapping) => {
> ```

you renamed this from target_block_id. Please revert as there is another param called block_id. You also used `target_block_id` below.



_Code quote:_
```XML
block_id
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2342)* status: 13 of 31 files reviewed, 1 unresolved discussion (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/objects/blocks.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2342#-NPWwsydDWLYRvN9nDgG:-NPXKRL84ID8idCKsYH_:bpm4tjl) ([raw file](https://github.com/starkware-libs/cairo/blob/1b4997a8c4f1bbab1e06cc0d063589a3d5d827f2/crates/cairo-lang-lowering/src/objects/blocks.rs#L106)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Now that we only really use one type of Block in Blocks, do we want to keep it generic?
</blockquote></details>

Maybe if it stays this way enough time then we can remove. But maybe we will have something else?

**Review by orizi — COMMENTED** [review]
> Reviewed 17 of 18 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2342)* status: 30 of 31 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
> Reviewed 16 of 18 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2342)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2342)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
