### PR TITLE
added libfunc for converting homogenous tuples to span

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4861)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4861)* status: 0 of 13 files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

___
*[`corelib/src/test/array_test.cairo` line 4 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4861#-Nogqo5p773gwUMGtKDt:-Nogqo5p773gwUMGtKDu:bq4n25a) ([raw file](https://github.com/starkware-libs/cairo/blob/0771424c36ee27d4756beb7a9e3f25af4ed92e2a/corelib/src/test/array_test.cairo#L4)):*
> ```Cairo
> 
> 
> extern fn span_from_tuple<T>(struct_like: Box<@T>) -> @Array<felt252> nopanic;
> ```

move this to end of the file.
___
*[`corelib/src/test/array_test.cairo` line 18 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4861#-NogqZUl3l9jtSKoWoZj:-NogqZUl3l9jtSKoWoZk:b-itk106) ([raw file](https://github.com/starkware-libs/cairo/blob/0771424c36ee27d4756beb7a9e3f25af4ed92e2a/corelib/src/test/array_test.cairo#L18)):*
> ```Cairo
>     assert_eq(span[1], @20, 'Unexpected element');
>     assert_eq(span[2], @30, 'Unexpected element');
> }
> ```

Add another test with a more complex struct.



_Suggestion:_
```Cairo
#[test]
fn test_span_from_tuple_felt252s() {
    let span = span_from_tuple(BoxTrait::new(@A { a: 10, b: 20, c: 30 }));
    assert_eq(span[0], @10, 'Unexpected element');
    assert_eq(span[1], @20, 'Unexpected element');
    assert_eq(span[2], @30, 'Unexpected element');
}
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4861)* status: 0 of 13 files reviewed, 8 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/core.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4861#-Nogqzja-ZJUuMoieCV2:-Nogqzja-ZJUuMoieCV3:b-ec24hg) ([raw file](https://github.com/starkware-libs/cairo/blob/baa8f467cca6bffae38b36547f77009de99f577f/crates/cairo-lang-sierra/src/extensions/core.rs#L86)):*
> ```XML
>         Pedersen(PedersenType),
>         Poseidon(PoseidonType),
>         Span(SpanType),
> ```

should probably happen - but not as part of this PR.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/array.rs` line 54 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4861#-Nogr5ir6YBIxtHAjch3:-Nogr5ir6YBIxtHAjch4:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/0771424c36ee27d4756beb7a9e3f25af4ed92e2a/crates/cairo-lang-sierra-to-casm/src/invocations/array.rs#L54)):*
> ```XML
> }
> 
> fn build_span_from_tuple(
> ```

doc
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/array.rs` line 58 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4861#-NogrF0ICeHxx0Uf8Gby:-NogrF0ICeHxx0Uf8Gbz:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0771424c36ee27d4756beb7a9e3f25af4ed92e2a/crates/cairo-lang-sierra-to-casm/src/invocations/array.rs#L58)):*
> ```XML
>     ty: &ConcreteTypeId,
> ) -> Result<CompiledInvocation, InvocationError> {
>     let [elem_ptr] = builder.try_get_single_cells()?;
> ```





_Suggestion:_
```XML
    let [start_ptr] = builder.try_get_single_cells()?;
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/array.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4861#-Nogr8Bh7BpMrjqT0I0T:-Nogr8Bh7BpMrjqT0I0U:b794ss1) ([raw file](https://github.com/starkware-libs/cairo/blob/0771424c36ee27d4756beb7a9e3f25af4ed92e2a/crates/cairo-lang-sierra-to-casm/src/invocations/array.rs#L59)):*
> ```XML
> ) -> Result<CompiledInvocation, InvocationError> {
>     let [elem_ptr] = builder.try_get_single_cells()?;
>     let size = builder.program_info.type_sizes[ty];
> ```

use longer name.
size of what?
___
*[`crates/cairo-lang-sierra-type-size/src/lib.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4861#-NogrKOdAseZRonDeUG8:-NogrKOdAseZRonDeUG9:b88473x) ([raw file](https://github.com/starkware-libs/cairo/blob/baa8f467cca6bffae38b36547f77009de99f577f/crates/cairo-lang-sierra-type-size/src/lib.rs#L50)):*
> ```XML
>             | CoreTypeConcrete::BoundedInt(_) => Some(1),
>             CoreTypeConcrete::Array(_)
>             | CoreTypeConcrete::Span(_)
> ```

here as well.
___
*[`tests/e2e_test_data/libfuncs/array` line 877 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4861#-NogrSMO-Rk6SQm-x-We:-NogrSMO-Rk6SQm-x-Wf:b-y03hza) ([raw file](https://github.com/starkware-libs/cairo/blob/0771424c36ee27d4756beb7a9e3f25af4ed92e2a/tests/e2e_test_data/libfuncs/array#L877)):*
> ```
> fn foo(x1:A) -> @Array<felt252> {
>     span_from_tuple(BoxTrait::new(@x1))
> }
> ```

tests here should test the libfunc with as few other stuff as possible.



_Suggestion:_
```
extern fn span_from_tuple<T>(struct_like: Box<@T>) -> @Array<felt252> nopanic;

struct A {
    a: felt252,
    b: felt252,
    c: felt252,
}

fn foo(value: Box<@A>) -> @Array<felt252> {
    span_from_tuple(value)
}
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4861)* status: 0 of 13 files reviewed, 8 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/test/array_test.cairo` line 4 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4861#-Nogqo5p773gwUMGtKDt:-NokG00MEIpleAYaghn-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0771424c36ee27d4756beb7a9e3f25af4ed92e2a/corelib/src/test/array_test.cairo#L4)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

move this to end of the file.
</blockquote></details>

Done.
___
*[`corelib/src/test/array_test.cairo` line 18 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4861#-NogqZUl3l9jtSKoWoZj:-NokG-Zi88QJDrXJfVE8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0771424c36ee27d4756beb7a9e3f25af4ed92e2a/corelib/src/test/array_test.cairo#L18)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Add another test with a more complex struct.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/array.rs` line 54 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4861#-Nogr5ir6YBIxtHAjch3:-NokJIIE5JygtHtFzPMz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0771424c36ee27d4756beb7a9e3f25af4ed92e2a/crates/cairo-lang-sierra-to-casm/src/invocations/array.rs#L54)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/array.rs` line 58 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4861#-NogrF0ICeHxx0Uf8Gby:-NokJSv9ARcoGPfjkTWG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0771424c36ee27d4756beb7a9e3f25af4ed92e2a/crates/cairo-lang-sierra-to-casm/src/invocations/array.rs#L58)):*
> ```XML
>     ty: &ConcreteTypeId,
> ) -> Result<CompiledInvocation, InvocationError> {
>     let [elem_ptr] = builder.try_get_single_cells()?;
> ```

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/array.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4861#-Nogr8Bh7BpMrjqT0I0T:-NokJYUP8swfJiScI2iZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0771424c36ee27d4756beb7a9e3f25af4ed92e2a/crates/cairo-lang-sierra-to-casm/src/invocations/array.rs#L59)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

use longer name.
size of what?
</blockquote></details>

Done.
___
*[`tests/e2e_test_data/libfuncs/array` line 877 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4861#-NogrSMO-Rk6SQm-x-We:-NokKYVl46pKZZ58KoIN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0771424c36ee27d4756beb7a9e3f25af4ed92e2a/tests/e2e_test_data/libfuncs/array#L877)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

tests here should test the libfunc with as few other stuff as possible.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/core.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4861#-Nogqzja-ZJUuMoieCV2:-NokGhSg5_iKboF5pI5t:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/baa8f467cca6bffae38b36547f77009de99f577f/crates/cairo-lang-sierra/src/extensions/core.rs#L86)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

should probably happen - but not as part of this PR.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-type-size/src/lib.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4861#-NogrKOdAseZRonDeUG8:-NokJZfw4Xpu5Nf_doT_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/baa8f467cca6bffae38b36547f77009de99f577f/crates/cairo-lang-sierra-type-size/src/lib.rs#L50)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

here as well.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 11 files at r1, 1 of 4 files at r2, 6 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4861)* status: 9 of 13 files reviewed, 9 unresolved discussions (waiting on @TomerStarkware)

___
*[`corelib/src/test/array_test.cairo` line 147 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4861#-NokN2bmEVNEkOiGNSx1:-NokN2bmEVNEkOiGNSx2:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6d60e4b14bfc2ae761517b9f558a7fa308e5e09b/corelib/src/test/array_test.cairo#L147)):*
> ```Cairo
>     assert_eq(span[1], @A { a: 40, b: 50, c: 60 }, 'Unexpected element');
>     assert_eq(span[2], @A { a: 70, b: 80, c: 90 }, 'Unexpected element');
> }
> ```





_Suggestion:_
```Cairo
mod span_from_tuple_felt252 {
    extern fn span_from_tuple<T>(struct_like: Box<@T>) -> @Array<felt252> nopanic;
}

mod span_from_tuple_A {
    extern fn span_from_tuple<T>(struct_like: Box<@T>) -> @Array<(felt252, felt252, felt252)> nopanic;
}

#[test]
fn test_span_from_tuple_felt252() {
    let span = span_from_tuple_felt252::span_from_tuple(BoxTrait::new(@(10. 20. 30)));
    assert!(*span[0] == 10);
    assert!(*span[1] == 20);
    assert!(*span[2] == 30);
}

#[test]
fn test_span_from_tuple_A() {
    let multi_tuple = ((10, 20, 30), (40, 50, 60), (70, 80, 90));
    let span: @Array<A> = span_from_tuple_A::span_from_tuple(BoxTrait::new(@multi_tuple));
    assert!(*span[0] == (10, 20, 30));
    assert!(*span[1] == (40, 50, 60));
    assert!(*span[2] == (70, 80, 90));
}
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 89 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4861#-NokOiyb4mmSS_C4Mn1h:-NokOiyb4mmSS_C4Mn1i:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/6d60e4b14bfc2ae761517b9f558a7fa308e5e09b/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L89)):*
> ```XML
> 
> #[derive(Default)]
> pub struct SpanFromTupleLibfuncWrapped;
> ```

doc
___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 125 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4861#-NokQeRvC3msF3579nDj:-NokQeRvC3msF3579nDk:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6d60e4b14bfc2ae761517b9f558a7fa308e5e09b/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L125)):*
> ```XML
>             SierraApChange::Known { new_vars_only: false },
>         ))
>     }
> ```





_Suggestion:_
```XML
        Ok(LibfuncSignature::new_non_branch(
            vec![input_ty],
            vec![OutputVarInfo {
                ty: snapshot_ty(
                    context,
                    context.get_wrapped_concrete_type(ArrayType::id(), member_type.clone())?,
                )?,
                ref_info: OutputVarReferenceInfo::Deferred(DeferredOutputKind::AddConst {
                    param_idx: 0,
                },
            }],
            SierraApChange::Known { new_vars_only: true },
        ))
    }
```
___
*[`crates/cairo-lang-sierra-ap-change/src/core_libfunc_ap_change.rs` line 67 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4861#-NokPR8e1zAj0Dg5KW4S:-NokPR8e1zAj0Dg5KW4T:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6d60e4b14bfc2ae761517b9f558a7fa308e5e09b/crates/cairo-lang-sierra-ap-change/src/core_libfunc_ap_change.rs#L67)):*
> ```XML
>         Array(libfunc) => match libfunc {
>             ArrayConcreteLibfunc::New(_) => vec![ApChange::Known(1)],
>             ArrayConcreteLibfunc::SpanFromTuple(_) => vec![ApChange::Known(1)],
> ```





_Suggestion:_
```XML
            ArrayConcreteLibfunc::SpanFromTuple(_) => vec![ApChange::Known(0)],
```
___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 234 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4861#-NokPSuF9t0gr836RQ6D:-NokPSuF9t0gr836RQ6E:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6d60e4b14bfc2ae761517b9f558a7fa308e5e09b/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L234)):*
> ```XML
>         Array(libfunc) => match libfunc {
>             ArrayConcreteLibfunc::New(_) => vec![ConstCost::steps(1).into()],
>             ArrayConcreteLibfunc::SpanFromTuple(_) => vec![ConstCost::steps(1).into()],
> ```





_Suggestion:_
```XML
            ArrayConcreteLibfunc::SpanFromTuple(_) => vec![ConstCost::steps(0).into()],
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/array.rs` line 55 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4861#-NokPX1e46TiR7ROJCim:-NokPX1e46TiR7ROJCin:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6d60e4b14bfc2ae761517b9f558a7fa308e5e09b/crates/cairo-lang-sierra-to-casm/src/invocations/array.rs#L55)):*
> ```XML
> 
> // Builds instruction for creating a span from a box of a tuple.
> fn build_span_from_tuple(
> ```





_Suggestion:_
```XML
// Builds instructions for converting a box of a struct containing only the same type as members into a span of that type.
fn build_span_from_tuple(
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/array.rs` line 60 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4861#-NokQ-8P7SJocuQfkqsM:-NokQ-8P7SJocuQfkqsN:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6d60e4b14bfc2ae761517b9f558a7fa308e5e09b/crates/cairo-lang-sierra-to-casm/src/invocations/array.rs#L60)):*
> ```XML
> ) -> Result<CompiledInvocation, InvocationError> {
>     let [start_ptr] = builder.try_get_single_cells()?;
>     let size_of_tuple = builder.program_info.type_sizes[ty];
> ```





_Suggestion:_
```XML
    let full_struct_size = builder.program_info.type_sizes[ty];
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/array.rs` line 76 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4861#-NokQ4Bj18TU4cmD_rQy:-NokQ4Bj18TU4cmD_rQz:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6d60e4b14bfc2ae761517b9f558a7fa308e5e09b/crates/cairo-lang-sierra-to-casm/src/invocations/array.rs#L76)):*
> ```XML
>         [("Fallthrough", &[&[arr_start, arr_end]], None)],
>         Default::default(),
>     ))
> ```





_Suggestion:_
```XML
    add_input_variables! {casm_builder,
        deref start_ptr;
    };
    casm_build_extend! {casm_builder,
        let arr_start = start_ptr;
        // As the actual size of the span is exactly the same as the wrapping struct.
        const span_size_in_cells = full_struct_size;
        let arr_end = arr_start + size;
    };
    Ok(builder.build_from_casm_builder(
        casm_builder,
        [("Fallthrough", &[&[arr_start, arr_end]], None)],
        Default::default(),
    ))
```
___
*[`tests/e2e_test_data/libfuncs/array` line 872 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4861#-NokQSoC0vy6bUvyPLJD:-NokQSoC0vy6bUvyPLJE:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6d60e4b14bfc2ae761517b9f558a7fa308e5e09b/tests/e2e_test_data/libfuncs/array#L872)):*
> ```
> fn foo(x1:Box<@(felt252,felt252,felt252)>) -> @Array<felt252> {
>     span_from_tuple(x1)
> }
> ```





_Suggestion:_
```
extern fn span_from_tuple<T>(struct_like: Box<@T>) -> @Array<felt252> nopanic;

fn foo(x1:Box<@(felt252, felt252, felt252)>) -> @Array<felt252> {
    span_from_tuple(x1)
}
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4861)* status: 9 of 13 files reviewed, 10 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 110 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4861#-NokRBDI0nGAz2a8kB9z:-NokRBDI0nGAz2a8kBA-:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/6d60e4b14bfc2ae761517b9f558a7fa308e5e09b/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L110)):*
> ```XML
>                 return Err(SpecializationError::UnsupportedGenericArg);
>             }
>         }
> ```

.



_Suggestion:_
```XML
        // Validate all members are of the same type.
        for (ty1, ty2)  in struct_type.members.iter().tuple_windows() {
            if ty1 != ty2 {
                return Err(SpecializationError::UnsupportedGenericArg);
            }
        }
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r1, 5 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4861)* status: 12 of 13 files reviewed, 3 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 90 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4861#-NokXWxK3zZp_JyT8puG:-NokXWxK3zZp_JyT8puH:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/84f2b4ff0985511f081c83d51087e80ba213d600/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L90)):*
> ```XML
> }
> 
> /// Libfunc for creating a span from a box of tuple.
> ```





_Suggestion:_
```XML
/// Libfunc for creating a span from a box of struct of members of the same type.
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 115 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4861#-NokXfzBBr9i6tbxB4EW:-NokXfzC31A21-_e-bv_:b8ryg74) ([raw file](https://github.com/starkware-libs/cairo/blob/84f2b4ff0985511f081c83d51087e80ba213d600/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L115)):*
> ```XML
>         let input_ty = box_ty(context, snapshot_ty(context, ty)?)?;
>         let member_type =
>             struct_type.members.first().ok_or(SpecializationError::UnsupportedGenericArg)?;
> ```

oh sorry - if you must extract it in any case - just do the iteration.



_Code quote:_
```XML
        let member_type =
            struct_type.members.first().ok_or(SpecializationError::UnsupportedGenericArg)?;
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4861#-:-NokcpBn4op2UK0BcjDr:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
