### PR TITLE
Added withdraw_gas tests or stubs.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3320)

### CODE REVIEW

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3320)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @orizi, and @spapinistarkware)

___
*[`tests/e2e_test_data/libfuncs/gas` line 93 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3320#-NXH-VAO0uh1nnsYD6U-:-NXH-VAO0uh1nnsYD6U0:b-ylbe9z) ([raw file](https://github.com/starkware-libs/cairo/blob/3f43153883ee10b45ff12d16c5f1886bbb69f2af/tests/e2e_test_data/libfuncs/gas#L93)):*
> ```
> //! > cairo
> fn foo() -> Option::<()> {
>     // TODO(orizi): use gas::withdraw_gas once it automatically adds the builtin costs.
> ```

What do you mean by this TODO? It's already using withdraw_gas.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3320)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware, @orizi, and @spapinistarkware)

___
*[`tests/e2e_test_data/libfuncs/gas` line 275 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3320#-NXH29V4E5dfwCGcq2hp:-NXH29V4E5dfwCGcq2hq:bf8q4il) ([raw file](https://github.com/starkware-libs/cairo/blob/3f43153883ee10b45ff12d16c5f1886bbb69f2af/tests/e2e_test_data/libfuncs/gas#L275)):*
> ```
> fn foo() -> Option::<()> {
>     // TODO(orizi): use gas::withdraw_gas once it automatically adds the builtin costs.
>     gas::withdraw_gas_all(gas::get_builtin_costs())?;
> ```

Use one of the builtins twice (to check the case `2*`, which is different than 1)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3320)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware, @orizi, and @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3320)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware, @liorgold2, and @spapinistarkware)

___
*[`tests/e2e_test_data/libfuncs/gas` line 93 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3320#-NXH-VAO0uh1nnsYD6U-:-NXHwLmlE2_pmiPuzpM4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3f43153883ee10b45ff12d16c5f1886bbb69f2af/tests/e2e_test_data/libfuncs/gas#L93)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

What do you mean by this TODO? It's already using withdraw_gas.
</blockquote></details>

Done.
___
*[`tests/e2e_test_data/libfuncs/gas` line 275 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3320#-NXH29V4E5dfwCGcq2hp:-NXHwCZ422QiyVjuVCyq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3f43153883ee10b45ff12d16c5f1886bbb69f2af/tests/e2e_test_data/libfuncs/gas#L275)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Use one of the builtins twice (to check the case `2*`, which is different than 1)
</blockquote></details>

Done.

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3320#-:-NXJieBR0hPNK_zmJ0tC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware and @spapinistarkware)

**Pull request merged**
