### PR TITLE
Added algorithm to calculate feedback-vertex-set

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2071)

### CODE REVIEW

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2071)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2071#-NNmQX6J4_-__whbXNN6:-NNmQX6J4_-__whbXNN7:be4x7vm) (no related file):*
don't delete branch

___

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2071)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-utils/src/graph_algos/feedback_set.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2071#-NNpMRdB9s4iNCKmHPym:-NNpMRdB9s4iNCKmHPyn:b-seas10) ([raw file](https://github.com/starkware-libs/cairo/blob/b6834de6ddea82bcff83360ebaffcb96bdc79b92/crates/cairo-lang-utils/src/graph_algos/feedback_set.rs#L9)):*
> ```XML
> mod feedback_set_test;
> 
> /// Context for the feedback-set algorithm.
> ```

Add some module level doc about what is the feedback set problem and why we need it.
___
*[`crates/cairo-lang-utils/src/graph_algos/feedback_set_test.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2071#-NNpRVub04omHye5Hpbs:-NNpRVub04omHye5Hpbt:b-x39ab3) ([raw file](https://github.com/starkware-libs/cairo/blob/b6834de6ddea82bcff83360ebaffcb96bdc79b92/crates/cairo-lang-utils/src/graph_algos/feedback_set_test.rs#L32)):*
> ```XML
>     }
> }
> impl SccAwareGraphNode for IntegerNode {
> ```

Suggestion:
```
struct SccIntegerNode(IntegerNode);
impl GraphNode for SccIntegerNode {
  ...
}
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2071)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-utils/src/graph_algos/feedback_set.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2071#-NNpMRdB9s4iNCKmHPym:-NNqELzJC9jbgTB5Elwx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/84e812619e12b4b7a702004566275843e8b80d2a/crates/cairo-lang-utils/src/graph_algos/feedback_set.rs#L9)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Add some module level doc about what is the feedback set problem and why we need it.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-utils/src/graph_algos/feedback_set_test.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2071#-NNpRVub04omHye5Hpbs:-NNqEmZj9QDw17qCoVJ5:b-jtujwf) ([raw file](https://github.com/starkware-libs/cairo/blob/84e812619e12b4b7a702004566275843e8b80d2a/crates/cairo-lang-utils/src/graph_algos/feedback_set_test.rs#L32)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Suggestion:
```
struct SccIntegerNode(IntegerNode);
impl GraphNode for SccIntegerNode {
  ...
}
```
</blockquote></details>

why? I only use one type in this test - IntegerNode, and it need to impl SccAwareGraphNode to run feedback_set algo.
(at least before the potential separation we discussed f2f. If I choose to do it later, this will not be required anyway).

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2071)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-utils/src/graph_algos/feedback_set_test.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2071#-NNpRVub04omHye5Hpbs:-NOIumLk3fW5Qnw5IQ0C:bu89a2y) ([raw file](https://github.com/starkware-libs/cairo/blob/84e812619e12b4b7a702004566275843e8b80d2a/crates/cairo-lang-utils/src/graph_algos/feedback_set_test.rs#L32)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

why? I only use one type in this test - IntegerNode, and it need to impl SccAwareGraphNode to run feedback_set algo.
(at least before the potential separation we discussed f2f. If I choose to do it later, this will not be required anyway).
</blockquote></details>

This suggestion *is* about what we discussed f2f:) It is wierd to have another trait SccAwareGraphNode, when it's really just a graph node.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2071)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-utils/src/graph_algos/feedback_set_test.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2071#-NNpRVub04omHye5Hpbs:-NPHge-u2h0TT04WRwN9:bl43g0v) ([raw file](https://github.com/starkware-libs/cairo/blob/84e812619e12b4b7a702004566275843e8b80d2a/crates/cairo-lang-utils/src/graph_algos/feedback_set_test.rs#L32)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This suggestion *is* about what we discussed f2f:) It is wierd to have another trait SccAwareGraphNode, when it's really just a graph node.
</blockquote></details>

Let's submit it this way, then consider this change in the future.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2071)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-utils/src/graph_algos/feedback_set_test.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2071#-NNpRVub04omHye5Hpbs:-NPM6Y9L37UECuRD5v9b:brv8i5d) ([raw file](https://github.com/starkware-libs/cairo/blob/84e812619e12b4b7a702004566275843e8b80d2a/crates/cairo-lang-utils/src/graph_algos/feedback_set_test.rs#L32)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Let's submit it this way, then consider this change in the future.
</blockquote></details>

This is the same as telling me "no", right? I'd rather discuss this again f2f

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2071)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-utils/src/graph_algos/feedback_set_test.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2071#-NNpRVub04omHye5Hpbs:-NPXTVrsBMIQonah5_Q4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/84e812619e12b4b7a702004566275843e8b80d2a/crates/cairo-lang-utils/src/graph_algos/feedback_set_test.rs#L32)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This is the same as telling me "no", right? I'd rather discuss this again f2f
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2071#-:-NPktso56c0_tD5VpARp:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
