### PR TITLE
Fix and unify list styles

### PR DESCRIPTION
**Pull request by microbecode**
Minor cosmetic fixes to lists and unify their usage.

Tried to find all similar issues in the docs.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2811)

### CODE REVIEW

**Review by JameStark — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2811#-:-NTT21FU8qjjyLFZ8bGl:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved

**Review by JameStark — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2811)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @microbecode)

**Comment by microbecode** [comment]
Hmm still missing official approval, @JameStark . Thanks.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2811#-:-NU5GB_g0zvpgUSrJsLM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @microbecode)

**Pull request merged**
