### PR TITLE
Added Hash/Store/Serde to types in corelib

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4001)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4001)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/integer.cairo` line 1303 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4001#-NdPWtAJ1OSNW_wpV33S:-NdPWtAJ1OSNW_wpV33T:b-2p7i77) ([raw file](https://github.com/starkware-libs/cairo/blob/1cd1d242883787392f38f5a775ab045b5e2201f3/corelib/src/integer.cairo#L1303)):*
> ```Cairo
> }
> 
> #[derive(Copy, Drop, PartialEq, Serde)]
> ```

We try to not add starknet stuff to the core lib (pending actual separation).
___
*[`corelib/src/starknet/eth_address.cairo` line 39 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4001#-NdPWhl8D-sA0E5t0PXn:-NdPWhl8D-sA0E5t0PXo:bpsyqie) ([raw file](https://github.com/starkware-libs/cairo/blob/1cd1d242883787392f38f5a775ab045b5e2201f3/corelib/src/starknet/eth_address.cairo#L39)):*
> ```Cairo
>     }
> }
> impl EthAddressSerde of Serde<EthAddress> {
> ```

This includes a validation, now is dropped.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4001)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/integer.cairo` line 1303 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4001#-NdPWtAJ1OSNW_wpV33S:-NdQIwhKAS5LABvB6n0R:bnxy5ps) ([raw file](https://github.com/starkware-libs/cairo/blob/1cd1d242883787392f38f5a775ab045b5e2201f3/corelib/src/integer.cairo#L1303)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

We try to not add starknet stuff to the core lib (pending actual separation).
</blockquote></details>

This means devs can't use it in maps as keys. Not the biggest loss ever for u512, but still.
Also, u256 does the same (derive(starknet::Store))
___
*[`corelib/src/starknet/eth_address.cairo` line 39 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4001#-NdPWhl8D-sA0E5t0PXn:-NdUR9n2DBAQ822zvuq0:b-g0teva) ([raw file](https://github.com/starkware-libs/cairo/blob/1cd1d242883787392f38f5a775ab045b5e2201f3/corelib/src/starknet/eth_address.cairo#L39)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

This includes a validation, now is dropped.
</blockquote></details>

Good catch, reverted.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4001)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/integer.cairo` line 1303 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4001#-NdPWtAJ1OSNW_wpV33S:-NdUl0Dh0Ba1QTbewpYE:b-ykfzni) ([raw file](https://github.com/starkware-libs/cairo/blob/1cd1d242883787392f38f5a775ab045b5e2201f3/corelib/src/integer.cairo#L1303)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

This means devs can't use it in maps as keys. Not the biggest loss ever for u512, but still.
Also, u256 does the same (derive(starknet::Store))
</blockquote></details>

Actually just as value.
Impl for store should just appear near the trait if required.
u256 is indeed one of the things that should change
___
*[`corelib/src/starknet/secp256_trait.cairo` line 10 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4001#-NdUlLWD7jhcvZ4waJRE:-NdUlLWD7jhcvZ4waJRF:b53cj3k) ([raw file](https://github.com/starkware-libs/cairo/blob/fe13da24beaea78a4e25abbe710126c08fcc8229/corelib/src/starknet/secp256_trait.cairo#L10)):*
> ```Cairo
> 
> /// Secp256{k/r}1 ECDSA signature.
> #[derive(Copy, Drop, PartialEq, Serde, starknet::Store, Hash)]
> ```

Same thing about starknet.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4001)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/integer.cairo` line 1303 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4001#-NdPWtAJ1OSNW_wpV33S:-NdUzmY_-ZQYJhUhUrOC:b-95q8q9) ([raw file](https://github.com/starkware-libs/cairo/blob/1cd1d242883787392f38f5a775ab045b5e2201f3/corelib/src/integer.cairo#L1303)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Actually just as value.
Impl for store should just appear near the trait if required.
u256 is indeed one of the things that should change
</blockquote></details>

So, until we remove it, don't we want them synced?
___
*[`corelib/src/starknet/secp256_trait.cairo` line 10 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4001#-NdUlLWD7jhcvZ4waJRE:-NdUzvCc6Fi4_g5tSoIz:b40s37q) ([raw file](https://github.com/starkware-libs/cairo/blob/fe13da24beaea78a4e25abbe710126c08fcc8229/corelib/src/starknet/secp256_trait.cairo#L10)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Same thing about starknet.
</blockquote></details>

This is not a change, I only added Hash. Removing it might break stuff so should at least be part of a different PR in some release branch

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4001)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`corelib/src/integer.cairo` line 1303 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4001#-NdPWtAJ1OSNW_wpV33S:-NdVYuz-6mdKHLKgAObs:bgre15d) ([raw file](https://github.com/starkware-libs/cairo/blob/1cd1d242883787392f38f5a775ab045b5e2201f3/corelib/src/integer.cairo#L1303)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

So, until we remove it, don't we want them synced?
</blockquote></details>

No need to layer any extra mistakes.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4001)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/integer.cairo` line 1303 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4001#-NdPWtAJ1OSNW_wpV33S:-NdVfV2q9eBobRvfHkn1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1cd1d242883787392f38f5a775ab045b5e2201f3/corelib/src/integer.cairo#L1303)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

No need to layer any extra mistakes.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4001#-:-NdVvzxy8BPQ8bSXtH5Z:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
