### PR TITLE
Moved EthAddress to core::starknet lib

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2913)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2913)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`corelib/src/starknet/eth_address.cairo` line 11 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2913#-NTiABkUBPOoWmJ5pT6U:-NTiABkUBPOoWmJ5pT6V:b4u7wxo) ([raw file](https://github.com/starkware-libs/cairo/blob/30c0d8848a17704db088bb2c63912cade3edf634/corelib/src/starknet/eth_address.cairo#L11)):*
> ```Cairo
> #[derive(Copy, Drop)]
> struct EthAddress {
>     address: felt252, 
> ```

There's a whitespace here. How come formatter didn't catch it?



_Code quote:_
```Cairo
·
```

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2913)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2913#-:-NTiAKN32SSwSI6nLSQr:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Dismissed @spapinistarkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2913)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
