### PR TITLE
Add ec_point_zero() libfunc.

### PR DESCRIPTION
**Pull request by liorgold2**
commit-id:034c8da0

---

**Stack**:
- #1950
- #1949
- #1948
- #1947
- #1946 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1946#-:-NMt6C7A2v-Fq4lvV1RJ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/ec.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1946#-NMt62se0SYX-XummLs2:-NMt62se0SYX-XummLs3:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/47c4bf8f32516465ac9b139bd4ac2ed6bc6d06f1/crates/cairo-lang-sierra/src/extensions/modules/ec.rs#L78)):*
> ```XML
>             vec![OutputVarInfo {
>                 ty: ecpoint_ty,
>                 ref_info: OutputVarReferenceInfo::Deferred(DeferredOutputKind::Generic),
> ```





_Suggestion:_
```XML
                ref_info: OutputVarReferenceInfo::Deferred(DeferredOutputKind::Const),
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1946)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/ec.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1946#-NMt62se0SYX-XummLs2:-NMtLKBs9qptLY5gc4_z:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/efd9cda41aa81ec80ac1d3beb81db6ecc78d12a1/crates/cairo-lang-sierra/src/extensions/modules/ec.rs#L78)):*
> ```XML
>             vec![OutputVarInfo {
>                 ty: ecpoint_ty,
>                 ref_info: OutputVarReferenceInfo::Deferred(DeferredOutputKind::Generic),
> ```

Done.

**Review by orizi — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1946)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1946)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
