### PR TITLE
LS: fix `cfg`s

### PR DESCRIPTION
**Pull request by piotmag769**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6180)

### CODE REVIEW

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6180)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/src/project/scarb.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6180#-O3rYmXlBdy1XWCneiql:-O3rYmXlBdy1XWCneiqm:bk4z6tr) ([raw file](https://github.com/starkware-libs/cairo/blob/e48e50b5ce158bb5920eab6fb93674fc374464c1/crates/cairo-lang-language-server/src/project/scarb.rs#L60)):*
> ```XML
>                 edition: scarb_package_edition(&package, crate_name),
>                 cfg_set: cfg_set_from_scarb
>                     .map(|cfg_set| cfg_set.union(&AnalysisDatabase::initial_cfg_set())),
> ```

If it is not `None` it overrides global cfg settings, that's why it has to be done this way

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6180)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/project/scarb.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6180#-O3rZApIC25CdlvlOp24:-O3rZApIC25CdlvlOp25:b-2js7qi) ([raw file](https://github.com/starkware-libs/cairo/blob/e48e50b5ce158bb5920eab6fb93674fc374464c1/crates/cairo-lang-language-server/src/project/scarb.rs#L60)):*
> ```XML
>                 edition: scarb_package_edition(&package, crate_name),
>                 cfg_set: cfg_set_from_scarb
>                     .map(|cfg_set| cfg_set.union(&AnalysisDatabase::initial_cfg_set())),
> ```

This is weird, you are patching all compilation units to provide the following cfg_sets which is not entirely correct.

I think the problem is in the logic which selects the compilation unit to analyse: it's not always picking the test one.

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6180)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/src/project/scarb.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6180#-O3rZApIC25CdlvlOp24:-O46CQjm4tTlHHGd5DKU:b-am8qhr) ([raw file](https://github.com/starkware-libs/cairo/blob/e48e50b5ce158bb5920eab6fb93674fc374464c1/crates/cairo-lang-language-server/src/project/scarb.rs#L60)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

This is weird, you are patching all compilation units to provide the following cfg_sets which is not entirely correct.

I think the problem is in the logic which selects the compilation unit to analyse: it's not always picking the test one.
</blockquote></details>

Picking a test one doesn't solve the issue, let's discuss it offline

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6180)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lang/db/mod.rs` line 62 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6180#-O4eKLHP7SIT-sJeKOBq:-O4eKLHP7SIT-sJeKOBr:b-41hl8b) ([raw file](https://github.com/starkware-libs/cairo/blob/ad860d93e6e73203e418ad6cd3102ee723d7ed7b/crates/cairo-lang-language-server/src/lang/db/mod.rs#L62)):*
> ```XML
>     /// Returns the [`CfgSet`] that should be assumed in the initial database state.
>     fn initial_cfg_set() -> CfgSet {
>         CfgSet::from_iter([Cfg::name("test"), Cfg::kv("target", "test")])
> ```

By moving this to scarb code, you're breaking cairo_project.toml-based projects and detached files. I think this is the reason hover test changed. Please revert.
___
*[`crates/cairo-lang-language-server/src/project/crate_data.rs` line 96 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6180#-O4eJsW40tyejMTyLvlU:-O4eJsW40tyejMTyLvlV:bascbiz) ([raw file](https://github.com/starkware-libs/cairo/blob/d90ec325dee08a4b4ef2b4db9077a8a38a915a08/crates/cairo-lang-language-server/src/project/crate_data.rs#L96)):*
> ```XML
>     // Inject virtual lib file wrapper.
>     db.as_files_group_mut()
>         .override_file_content(file_id, Some(format!("{file_content}\nmod {file_stem};").into()));
> ```

hmm this approach has a problem that it does not deallocate modules that disappear (for example, file was renamed or deleted entirely)

I think what should happen is you collect all integration test units, and explicitly group them and then inject a vector of file stems
___
*[`crates/cairo-lang-language-server/tests/test_data/hover/starknet.txt` line 56 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6180#-O4eKB9GB4hIPjwp5UJ4:-O4eKB9GB4hIPjwp5UJ5:bhtsqzp) ([raw file](https://github.com/starkware-libs/cairo/blob/d90ec325dee08a4b4ef2b4db9077a8a38a915a08/crates/cairo-lang-language-server/tests/test_data/hover/starknet.txt#L56)):*
> ```help
> use Balance::contr<caret>act_state_for_testing;
> // = highlight
> No highlight information.
> ```

this shouldn't change

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6180)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/src/lang/db/mod.rs` line 62 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6180#-O4eKLHP7SIT-sJeKOBq:-O4eLtikCyz-XN815Puy:ble6fci) ([raw file](https://github.com/starkware-libs/cairo/blob/ad860d93e6e73203e418ad6cd3102ee723d7ed7b/crates/cairo-lang-language-server/src/lang/db/mod.rs#L62)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

By moving this to scarb code, you're breaking cairo_project.toml-based projects and detached files. I think this is the reason hover test changed. Please revert.
</blockquote></details>

Forgot about it, right
___
*[`crates/cairo-lang-language-server/src/project/crate_data.rs` line 96 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6180#-O4eJsW40tyejMTyLvlU:-O4eM1apB5GIQxpCqRFN:becw5hk) ([raw file](https://github.com/starkware-libs/cairo/blob/d90ec325dee08a4b4ef2b4db9077a8a38a915a08/crates/cairo-lang-language-server/src/project/crate_data.rs#L96)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

hmm this approach has a problem that it does not deallocate modules that disappear (for example, file was renamed or deleted entirely)

I think what should happen is you collect all integration test units, and explicitly group them and then inject a vector of file stems
</blockquote></details>

Good catch, will do
___
*[`crates/cairo-lang-language-server/tests/test_data/hover/starknet.txt` line 56 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6180#-O4eKB9GB4hIPjwp5UJ4:-O4eM6_q1N38UqqjNkLD:bdf3q0p) ([raw file](https://github.com/starkware-libs/cairo/blob/d90ec325dee08a4b4ef2b4db9077a8a38a915a08/crates/cairo-lang-language-server/tests/test_data/hover/starknet.txt#L56)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

this shouldn't change
</blockquote></details>

Will change

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6180)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, and @mkaput)

___
*[`crates/cairo-lang-language-server/src/project/scarb.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6180#-O3rYmXlBdy1XWCneiql:-O4kEzcLA5PtLaqt_gBG:b4yy7wp) ([raw file](https://github.com/starkware-libs/cairo/blob/e48e50b5ce158bb5920eab6fb93674fc374464c1/crates/cairo-lang-language-server/src/project/scarb.rs#L60)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

If it is not `None` it overrides global cfg settings, that's why it has to be done this way
</blockquote></details>

this sounds like it should be an actual comment.

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6180)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, and @mkaput)

___
*[`crates/cairo-lang-language-server/src/lang/db/mod.rs` line 62 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6180#-O4eKLHP7SIT-sJeKOBq:-O4gQmF238X3qV72rEN3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ad860d93e6e73203e418ad6cd3102ee723d7ed7b/crates/cairo-lang-language-server/src/lang/db/mod.rs#L62)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Forgot about it, right
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/project/crate_data.rs` line 96 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6180#-O4eJsW40tyejMTyLvlU:-O4gQo0I11uy2k5zRdHg:bdnwuxh) ([raw file](https://github.com/starkware-libs/cairo/blob/d90ec325dee08a4b4ef2b4db9077a8a38a915a08/crates/cairo-lang-language-server/src/project/crate_data.rs#L96)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Good catch, will do
</blockquote></details>

Done, resolved a few metadata issues on the way. The solution is really hacky though :/
___
*[`crates/cairo-lang-language-server/src/project/scarb.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6180#-O3rYmXlBdy1XWCneiql:-O4pkH9j9it50Ty-uiJ8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e48e50b5ce158bb5920eab6fb93674fc374464c1/crates/cairo-lang-language-server/src/project/scarb.rs#L60)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this sounds like it should be an actual comment.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/tests/test_data/hover/starknet.txt` line 56 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6180#-O4eKB9GB4hIPjwp5UJ4:-O4gQnMwCOFpDQeqqn_D:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d90ec325dee08a4b4ef2b4db9077a8a38a915a08/crates/cairo-lang-language-server/tests/test_data/hover/starknet.txt#L56)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Will change
</blockquote></details>

Done.

**Review by mkaput — APPROVED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6180)* status: all files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/project/crate_data.rs` line 103 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6180#-O4tWd3f2_BFmVP9D8LY:-O4tWd3f2_BFmVP9D8LZ:b2ni8l0) ([raw file](https://github.com/starkware-libs/cairo/blob/01091ce8df33c9d952178b9d6e6e0c6c1ba6ebff/crates/cairo-lang-language-server/src/project/crate_data.rs#L103)):*
> ```XML
>     for stem in file_stems {
>         file_content.push_str(&format!("mod {stem};\n"))
>     }
> ```

nit



_Suggestion:_
```XML
    let file_content = file_stems
        .iter()
        .map(|stem| format!("mod {stem};"))
        .collect::<Vec<_>>()
        .join("\n");
```
___
*[`crates/cairo-lang-language-server/src/project/crate_data.rs` line 130 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6180#-O4t_byl8Xsm5d19Nhte:-O4t_byl8Xsm5d19Nhtf:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/01091ce8df33c9d952178b9d6e6e0c6c1ba6ebff/crates/cairo-lang-language-server/src/project/crate_data.rs#L130)):*
> ```XML
>         .collect::<Option<_>>();
> 
>     names
> ```





_Suggestion:_
```XML
    content
        .lines()
        .filter(|line| !line.is_empty())
        .map(|line| Some(line.strip_prefix("mod ")?.strip_suffix(';')?.into()))
        .collect::<Option<Vec<_>>>()
```
___
*[`crates/cairo-lang-language-server/src/project/scarb.rs` line 53 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6180#-O4tasyL1whIAfncR07X:-O4tasyL1whIAfncR07Y:brb3j6v) ([raw file](https://github.com/starkware-libs/cairo/blob/01091ce8df33c9d952178b9d6e6e0c6c1ba6ebff/crates/cairo-lang-language-server/src/project/scarb.rs#L53)):*
> ```XML
>                     .repr
>                     .split("_integrationtest")
>                     .collect_vec()
> ```

nit, we tend to avoid `collect_vec` in favour of std-native style



_Suggestion:_
```XML
.collect::<Vec<_>>()
```
___
*[`crates/cairo-lang-language-server/src/project/scarb.rs` line 55 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6180#-O4tcHZbDnzA-XDiHsGJ:-O4tcHZc-1C6JvW6F_eb:b-ot94xs) ([raw file](https://github.com/starkware-libs/cairo/blob/01091ce8df33c9d952178b9d6e6e0c6c1ba6ebff/crates/cairo-lang-language-server/src/project/scarb.rs#L55)):*
> ```XML
>                     .collect_vec()
>                     .first()
>                     .unwrap()
> ```

maybe just `continue` here instead of potentially panic in pathological case?
___
*[`crates/cairo-lang-language-server/src/project/scarb.rs` line 269 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6180#-O4taAA-6P7tw_ZmtIlO:-O4taAA-6P7tw_ZmtIlP:b2ni8l0) ([raw file](https://github.com/starkware-libs/cairo/blob/01091ce8df33c9d952178b9d6e6e0c6c1ba6ebff/crates/cairo-lang-language-server/src/project/scarb.rs#L269)):*
> ```XML
> fn is_integration_test_cu(compilation_unit: &CompilationUnitMetadata) -> bool {
>     compilation_unit.target.kind == "test"
>         && compilation_unit.target.params.get("test-type") == Some(&json!("integration"))
> ```

nit



_Suggestion:_
```XML
compilation_unit.target.params.get("test-type").and_then(Value::as_str) == Some("integration")
```

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6180)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, and @mkaput)

___
*[`crates/cairo-lang-language-server/src/project/crate_data.rs` line 130 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6180#-O4t_byl8Xsm5d19Nhte:-O4z72QQ85MgOvxaQJcU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/01091ce8df33c9d952178b9d6e6e0c6c1ba6ebff/crates/cairo-lang-language-server/src/project/crate_data.rs#L130)):*
> ```XML
>         .collect::<Option<_>>();
> 
>     names
> ```

Done.
___
*[`crates/cairo-lang-language-server/src/project/scarb.rs` line 55 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6180#-O4tcHZbDnzA-XDiHsGJ:-O4zAzQjDVOhYd-oAKyA:b-cqptki) ([raw file](https://github.com/starkware-libs/cairo/blob/01091ce8df33c9d952178b9d6e6e0c6c1ba6ebff/crates/cairo-lang-language-server/src/project/scarb.rs#L55)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

maybe just `continue` here instead of potentially panic in pathological case?
</blockquote></details>

It seems that it cannot return an empty `Vec` ever, tested more pathological cases like splitting string with itself or splitting empty string

https://doc.rust-lang.org/std/primitive.str.html#method.split

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6180)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, and @mkaput)

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6180)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lang/inspect/crates.rs` line 32 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6180#-O5ChETUBRiYvAbF63iV:-O5ChETUBRiYvAbF63iW:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/213bea2786fc1f7defdfcf182d07a9c3ab5744b2/crates/cairo-lang-language-server/src/lang/inspect/crates.rs#L32)):*
> ```XML
>         "#,
>         name = cr.name,
>         source_path = cr.source_paths().into_iter().map(|path| path.display().to_string()).collect_vec(),
> ```





_Suggestion:_
```XML
.collect::<Vec<_>>()
```
___
*[`crates/cairo-lang-language-server/src/project/scarb.rs` line 55 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6180#-O4tcHZbDnzA-XDiHsGJ:-O5Ch3Z_CNdEEpevNSVC:bn8wxp1) ([raw file](https://github.com/starkware-libs/cairo/blob/01091ce8df33c9d952178b9d6e6e0c6c1ba6ebff/crates/cairo-lang-language-server/src/project/scarb.rs#L55)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

It seems that it cannot return an empty `Vec` ever, tested more pathological cases like splitting string with itself or splitting empty string

https://doc.rust-lang.org/std/primitive.str.html#method.split
</blockquote></details>

So please leave a `NOTE` comment with this explanation in source code :)

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6180)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, and @mkaput)

___
*[`crates/cairo-lang-language-server/src/lang/inspect/crates.rs` line 32 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6180#-O5ChETUBRiYvAbF63iV:-O5CtX5i8FnUEjO--u6Y:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/213bea2786fc1f7defdfcf182d07a9c3ab5744b2/crates/cairo-lang-language-server/src/lang/inspect/crates.rs#L32)):*
> ```XML
>         "#,
>         name = cr.name,
>         source_path = cr.source_paths().into_iter().map(|path| path.display().to_string()).collect_vec(),
> ```

Done.
___
*[`crates/cairo-lang-language-server/src/project/scarb.rs` line 55 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6180#-O4tcHZbDnzA-XDiHsGJ:-O5CtXpY4zAKYHXqt6Q-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/01091ce8df33c9d952178b9d6e6e0c6c1ba6ebff/crates/cairo-lang-language-server/src/project/scarb.rs#L55)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

So please leave a `NOTE` comment with this explanation in source code :)
</blockquote></details>

Done.

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6180)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, and @mkaput)

**Review by mkaput — COMMENTED** [review]
> Reviewed 1 of 2 files at r7, 1 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6180)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @piotmag769)

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6180#-:-O5D7nMsBYTgQ3epDE3C:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)

___
*[`crates/cairo-lang-language-server/src/project/scarb.rs` line 92 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6180#-O5D7oWz7l4Tjgj3kop8:-O5D7oX-6bTxjTCGf9eS:bswknq3) ([raw file](https://github.com/starkware-libs/cairo/blob/98c089f4a21b6f76e580b16beb7528cc6803e625/crates/cairo-lang-language-server/src/project/scarb.rs#L92)):*
> ```XML
>             let cfg_set = if metadata.workspace.members.contains(&component.package) {
>                 cfg_set_from_scarb
>                     // If `cfg_set` is not `None`, it overrides global cfg settings.
> ```

This makes sense to me.

**Review by Draggu — APPROVED** [review]
:lgtm:

> Reviewed 2 of 5 files at r3, 1 of 2 files at r4, 1 of 2 files at r6, 1 of 2 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6180#-:-O5DRzfvD03YqwXrYsS4:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae)

**Pull request merged**
