### PR TITLE
Refactored const-folding.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #6085
- #6084
- #6083
- #6071
- #6070 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6070)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6070)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/const_folding.rs` line 179 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6070#-O2dbNIX83WAQ3Gp3a09:-O2dbNIX83WAQ3Gp3a0A:bx65zz1) ([raw file](https://github.com/starkware-libs/cairo/blob/e939cef85c6f5fcd607025d5079d6d2bc99d3b0a/crates/cairo-lang-lowering/src/optimizations/const_folding.rs#L179)):*
> ```XML
>     nz_fns: UnorderedHashSet<FunctionId>,
>     /// The storage access module.
>     storage_access_module: ModuleHelper<'a>,
> ```

Consider making these a sub-struct.



_Code quote:_
```XML
    // The required ids for optimizations.
    /// The `felt252_sub` libfunc.
    felt_sub: FunctionId,
    /// The `into_box` libfunc.
    into_box: ExternFunctionId,
    /// The `upcast` libfunc.
    upcast: ExternFunctionId,
    /// The `storage_base_address_from_felt252` libfunc.
    storage_base_address_from_felt252: FunctionId,
    /// The set of functions that check if a number is zero.
    nz_fns: UnorderedHashSet<FunctionId>,
    /// The storage access module.
    storage_access_module: ModuleHelper<'a>,
```

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6070)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/const_folding.rs` line 337 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6070#-O2tl6KD6WTNCZvncoMz:-O2tl6KEBwJno9_Apo0V:b-pc8ne0) ([raw file](https://github.com/starkware-libs/cairo/blob/d9ffee0f902ccc9eebf9b114c5722cb6cbff3420/crates/cairo-lang-lowering/src/optimizations/const_folding.rs#L337)):*
> ```XML
>     /// The storage access module.
>     storage_access_module: ModuleHelper<'a>,
> }
> ```

Maybe it should really be static with `once_cell::Lazy`?



_Code quote:_
```XML
/// Holds static information about libfuncs required for the optimization.
struct LibfuncInfo<'a> {
    /// The `felt252_sub` libfunc.
    felt_sub: FunctionId,
    /// The `into_box` libfunc.
    into_box: ExternFunctionId,
    /// The `upcast` libfunc.
    upcast: ExternFunctionId,
    /// The `storage_base_address_from_felt252` libfunc.
    storage_base_address_from_felt252: FunctionId,
    /// The set of functions that check if a number is zero.
    nz_fns: UnorderedHashSet<FunctionId>,
    /// The storage access module.
    storage_access_module: ModuleHelper<'a>,
}
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6070)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/const_folding.rs` line 337 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6070#-O2tl6KD6WTNCZvncoMz:-O2uGDdnBRip97s10cK-:bi1egjn) ([raw file](https://github.com/starkware-libs/cairo/blob/20bba5d2817836f464128903288e62c73e63cc36/crates/cairo-lang-lowering/src/optimizations/const_folding.rs#L337)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Maybe it should really be static with `once_cell::Lazy`?
</blockquote></details>

cannot be - but can become a db query - but will get to it when actually required.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6070#-:-O2v--wq56gsRG8Y7bl6:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
