### PR TITLE
LS: Allow parametrizing completion tests behaviour

### PR DESCRIPTION
**Pull request by integraledelebesgue**
**Stack**:
- #6566
- #6565
- #6567
- #6563 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by integraledelebesgue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6563)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6563#-OAYfLNK3neEYJoZixDV:-OAYfLNK3neEYJoZixDW:bzgrtwt) (no related file):*
This is a temporary solution which I will enhance soon.

___

**Review by piotmag769 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6563#-:-OA__L5c1Qmf_JadBA98:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6563)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @integraledelebesgue, and @orizi)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6563#-OAqPntP9rvA9SD970mT):*
Wdyt?



_Suggestion:_
```
- 4e09b88: LS: Allow parameterizing completion tests behaviour

  commit-id:46f1dadf
```

**Review by integraledelebesgue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6563)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6563#-OAqPntP9rvA9SD970mT):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Wdyt?
</blockquote></details>

Very good idea :)

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6563#-:-OAqaLyXE3ttFOvU13r7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @orizi)

**Review by mkaput — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6563)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @orizi)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6563#-:-OAx8a-m3yLfXpRuOuDj:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6563)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)

**Review by Draggu — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6563#-:-OB5AlwP3xI_7Q-wLrYX:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae)

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6563)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae)

**Comment by integraledelebesgue** [comment]
✓ Commit merged in pull request [#6566](https://github.com/starkware-libs/cairo/pull/6566)

**Comment by integraledelebesgue** [comment]
✓ Commit merged in pull request [#6567](https://github.com/starkware-libs/cairo/pull/6567)

**Pull request merged**
