### PR TITLE
Remapping optimization

### PR DESCRIPTION
**Pull request by spapinistarkware**
**Stack**:
- #2284
- #2283
- #2282
- #2257
- #2254
- #2253 ⬅
- #2252
- #2245

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2253)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2253)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/remappings.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2253#-NOxn5Jb2PuG00n0FIZ9:-NOxn5Jc4FrUgr911sfb:bhpfkdh) ([raw file](https://github.com/starkware-libs/cairo/blob/ff24071a4a06a31d980ad2ba8358b84e1ed3da2d/crates/cairo-lang-lowering/src/optimizations/remappings.rs#L17)):*
> ```XML
> use crate::{BlockId, FlatBlockEnd, FlatLowered, VarRemapping, VariableId};
> 
> pub fn visit_remappings<F: FnMut(&mut VarRemapping)>(lowered: &mut FlatLowered, mut f: F) {
> ```

remove unused pubs and doc all structs and functions.



_Code quote:_
```XML
pub fn visit_remappings<F: FnMut(&mut VarRemapping)>(lowered: &mut FlatLowered, mut f: F) {
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2253)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2253)* status: all files reviewed, 5 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/remappings.rs` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2253#-NOzedkc93BzOXB7KbEZ:-NOzedkc93BzOXB7KbE_:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7c0710d94492b4f21775ad064246605812ce4a99/crates/cairo-lang-lowering/src/optimizations/remappings.rs#L3)):*
> ```XML
> //! Remove unnecessary remappings of variables optimization.
> //! At each convergance, we have one or more branches with remappings of variables.
> //! A destination variable `dest` introduced by the remappings must be remapped at every branch
> ```





_Suggestion:_
```XML
//! Remove unnecessary remappings of variable optimizations.
//! At each convergance, we have one or more branches with remappings of variables.
//! A destination variable `dest` introduced by the remappings must be remapped at every branch
//! `b_i` by mapping a source variable `src_i->dest`.
//! We require that every use of `dest` refers to the correct `src_i`.
//! This means that the remappings to `dest` are not necessary in these cases:
//! 1. There is no flow that uses the "value" of `dest` after the convergence.
//! 2. All the `src_i` variables get the same "value".
```
___
*[`crates/cairo-lang-lowering/src/optimizations/remappings.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2253#-NOzf7gL-FfFVKzzId7z:-NOzf7gL-FfFVKzzId8-:b-rb324u) ([raw file](https://github.com/starkware-libs/cairo/blob/7c0710d94492b4f21775ad064246605812ce4a99/crates/cairo-lang-lowering/src/optimizations/remappings.rs#L17)):*
> ```XML
> use crate::{BlockId, FlatBlockEnd, FlatLowered, VarRemapping, VariableId};
> 
> pub fn visit_remappings<F: FnMut(&mut VarRemapping)>(lowered: &mut FlatLowered, mut f: F) {
> ```

why is `f` mut?



_Code quote:_
```XML
mut f: F
```
___
*[`crates/cairo-lang-lowering/src/optimizations/remappings.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2253#-NOzfOItDk4yCzFqsvXB:-NOzfOItDk4yCzFqsvXC:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7c0710d94492b4f21775ad064246605812ce4a99/crates/cairo-lang-lowering/src/optimizations/remappings.rs#L79)):*
> ```XML
>             ctx.dest_to_srcs.entry(*dst).or_default().push(*src);
>         }
>     });
> ```





_Suggestion:_
```XML
    // Find cond 1 (see file comment).
    let mut ctx = Context::default();
    visit_remappings(lowered, |remapping| {
        for (dst, src) in remapping.iter() {
            ctx.dest_to_srcs.entry(*dst).or_default().push(*src);
        }
    });

    // Find cond 2  (see file comment).
```
___
*[`crates/cairo-lang-lowering/src/optimizations/remappings.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2253#-NOzfVAdA8ba_HVKimka:-NOzfVAdA8ba_HVKimkb:b4ya9j9) ([raw file](https://github.com/starkware-libs/cairo/blob/7c0710d94492b4f21775ad064246605812ce4a99/crates/cairo-lang-lowering/src/optimizations/remappings.rs#L105)):*
> ```XML
>     // Fix.
>     for block in lowered.blocks.0.iter_mut() {
>         *block = ctx.rebuild_block(block);
> ```

Fix/Do :)



_Code quote:_
```XML
    // Fix.
    for block in lowered.blocks.0.iter_mut() {
        *block = ctx.rebuild_block(block);
    }

    // TODO: consider pruning variables.
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2253)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/optimizations/remappings.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2253#-NOxn5Jb2PuG00n0FIZ9:-NPC_GCVDhF_APtH-aSb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7c0710d94492b4f21775ad064246605812ce4a99/crates/cairo-lang-lowering/src/optimizations/remappings.rs#L17)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove unused pubs and doc all structs and functions.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/optimizations/remappings.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2253#-NOzf7gL-FfFVKzzId7z:-NPC_JSx8PvjnOkTFZMa:b-j976r8) ([raw file](https://github.com/starkware-libs/cairo/blob/7c0710d94492b4f21775ad064246605812ce4a99/crates/cairo-lang-lowering/src/optimizations/remappings.rs#L17)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

why is `f` mut?
</blockquote></details>

FnMut is the most general callback, and it mutates the object on call.
___
*[`crates/cairo-lang-lowering/src/optimizations/remappings.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2253#-NOzfVAdA8ba_HVKimka:-NPC_fC05xMc5oBSEN18:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7c0710d94492b4f21775ad064246605812ce4a99/crates/cairo-lang-lowering/src/optimizations/remappings.rs#L105)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Fix/Do :)
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2253#-:-NPCrntnCuYGAQWeTkth:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

**Pull request closed without merging**
