### PR TITLE
Remove callsite

### PR DESCRIPTION
**Pull request by spapinistarkware**
**Stack**:
- #2284
- #2283
- #2282
- #2257
- #2254 ⬅
- #2253
- #2252
- #2245

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2254)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 31 of 94 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2254)* status: 31 of 94 files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/analysis.rs` line 91 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOxnlG4Cej5tbur5Wk4:-NOxnlG4Cej5tbur5Wk5:buznniu) ([raw file](https://github.com/starkware-libs/cairo/blob/8402783900f47970faba86509e44ac10c341645a/crates/cairo-lang-lowering/src/borrow_check/analysis.rs#L91)):*
> ```XML
>         let statement_location = (block_id, self.lowered.blocks[block_id].statements.len());
>         match block_end {
>             FlatBlockEnd::NotSet => todo!(),
> ```

i think



_Suggestion:_
```XML
            FlatBlockEnd::NotSet => unreachable!(),
```
___
*[`crates/cairo-lang-lowering/src/panic/mod.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOxo-SrEl4h8wqBdpNJ:-NOxo-SsA5mfzUOZx0no:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/8402783900f47970faba86509e44ac10c341645a/crates/cairo-lang-lowering/src/panic/mod.rs#L81)):*
> ```XML
> }
> 
> fn handle_block(
> ```

doc



_Code quote:_
```XML
fn handle_block(
```
___
*[`crates/cairo-lang-sierra-generator/src/block_generator_test_data/early_return` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOxoO-KBJn7FCKpQZov:-NOxoO-LDYBtBF28U72x:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/8402783900f47970faba86509e44ac10c341645a/crates/cairo-lang-sierra-generator/src/block_generator_test_data/early_return#L35)):*
> ```
> drop<NonZero<felt>>([0]) -> ()
> PushValues() -> ()
> jump() { label2() }
> ```

?



_Code quote:_
```
jump() { label2() }
```
___
*[`crates/cairo-lang-sierra-generator/src/block_generator_test_data/match` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOxocvY8LF45SrzmyhX:-NOxocvY8LF45SrzmyhY:b-k52win) ([raw file](https://github.com/starkware-libs/cairo/blob/8402783900f47970faba86509e44ac10c341645a/crates/cairo-lang-sierra-generator/src/block_generator_test_data/match#L35)):*
> ```
> felt_const<3>() -> ([2])
> PushValues([2]: felt) -> ([3]*)
> jump() { label2() }
> ```

seems wrong



_Code quote:_
```
PushValues([2]: felt) -> ([3]*)
jump() { label2() }
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2254)* status: 31 of 94 files reviewed, 5 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/inline` line 111 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOy1el74ypO3frcllyn:-NOy1el74ypO3frcllyo:b-cduuns) ([raw file](https://github.com/starkware-libs/cairo/blob/8402783900f47970faba86509e44ac10c341645a/crates/cairo-lang-sierra-generator/src/function_generator_test_data/inline#L111)):*
> ```
> enum_init<core::option::Option::<@core::felt>, 0>([4]) -> ([6])
> store_temp<RangeCheck>([3]) -> ([7])
> dup<RangeCheck>([7]) -> ([7], [3])
> ```

this definitely should not happen. 



_Code quote:_
```
dup<RangeCheck>([7]) -> ([7], [3])
```

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 36 of 94 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2254)* status: 38 of 94 files reviewed, 23 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/analysis.rs` line 91 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOxnlG4Cej5tbur5Wk4:-NOzThu60MmigsQkuenO:b32v57) ([raw file](https://github.com/starkware-libs/cairo/blob/8402783900f47970faba86509e44ac10c341645a/crates/cairo-lang-lowering/src/borrow_check/analysis.rs#L91)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i think
</blockquote></details>

+1
___
*[`crates/cairo-lang-lowering/src/borrow_check/analysis.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOzTPKh0fZ7SvJF4gs6:-NOzTPKiE4iw1YMW4sYG:b-6nsrrt) ([raw file](https://github.com/starkware-libs/cairo/blob/fe82890e5560ea3dee86985d633971ee0eda1095/crates/cairo-lang-lowering/src/borrow_check/analysis.rs#L61)):*
> ```XML
> 
>         // Find real block ending.
>         // This indirection and traverse_from_next_split() will removed when lowering is using
> ```

There are still "real blocks" here. Do you want to remove them in a future PR or in this one?
I find it confusing to have this "real" words here where there isn't RealBlock anymore.



_Code quote:_
```XML
        // This indirection and traverse_from_next_split() will removed when lowering is using
        // Gotos.
```
___
*[`crates/cairo-lang-lowering/src/borrow_check/analysis.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOzU3Dm8sSA4Hkmee8u:-NOzU3Dm8sSA4Hkmee8v:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/fe82890e5560ea3dee86985d633971ee0eda1095/crates/cairo-lang-lowering/src/borrow_check/analysis.rs#L105)):*
> ```XML
>     // Note: When lowering uses Gotos, this will be merged with get_block_end_info().
>     /// Gets the analysis info from the next branching statement in a block.
>     /// A [BlockId] ends in either a branching statement (e.g. match) or a [FlatBlockEnd].
> ```





_Suggestion:_
```XML
A block ends in eithe
```
___
*[`crates/cairo-lang-lowering/src/inline/test_data/inline` line 943 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOzUYqNCNLrGfEvEoeQ:-NOzUYqNCNLrGfEvEoeR:b-w4wvcm) ([raw file](https://github.com/starkware-libs/cairo/blob/fe82890e5560ea3dee86985d633971ee0eda1095/crates/cairo-lang-lowering/src/inline/test_data/inline#L943)):*
> ```
> //! > ==========================================================================
> 
> //! > Test match where is there a goto in one arm and callsite in another.
> ```

can you please fix?



_Code quote:_
```
atch where is there a goto in one arm and callsite in another.
```
___
*[`crates/cairo-lang-lowering/src/inline/test_data/inline` line 949 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOzUo3D09nK4FOJgPPu:-NOzUo3D09nK4FOJgPPv:b-q5y7m1) ([raw file](https://github.com/starkware-libs/cairo/blob/fe82890e5560ea3dee86985d633971ee0eda1095/crates/cairo-lang-lowering/src/inline/test_data/inline#L949)):*
> ```
> // A panicable function can have a block with a low `block_id` with a match_arm that goes
> // to a higher 'block_id'.
> // We want to test this outside of the root block as the root block is rebuild last.
> ```

This also doesn't make sense anymore.
___
*[`crates/cairo-lang-lowering/src/inline/test_data/inline` line 990 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOzVKmy-3r1jMNneEHU:-NOzVKmy-3r1jMNneEHV:b44z21i) ([raw file](https://github.com/starkware-libs/cairo/blob/fe82890e5560ea3dee86985d633971ee0eda1095/crates/cairo-lang-lowering/src/inline/test_data/inline#L990)):*
> ```
>   Fallthrough(blk1, {})
> 
> blk1:
> ```

Why is your change adding new blocks?
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 300 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOzVfMRDMBip0eVziKR:-NOzVfMRDMBip0eVziKS:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/fe82890e5560ea3dee86985d633971ee0eda1095/crates/cairo-lang-lowering/src/lower/scope.rs#L300)):*
> ```XML
> }
> impl SealedBlockBuilder {
>     /// Given the extra information needed, returns the ID of the final block id.
> ```





_Suggestion:_
```XML
needed, returns the ID of the final block.
```
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 304 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOzVc976aqTKUsIzHQA:-NOzVc986rhPBVTHehnk:b-93h0jg) ([raw file](https://github.com/starkware-libs/cairo/blob/fe82890e5560ea3dee86985d633971ee0eda1095/crates/cairo-lang-lowering/src/lower/scope.rs#L304)):*
> ```XML
>         self,
>         ctx: &mut LoweringContext<'_>,
>         target: Option<BlockId>,
> ```

doc what target is.
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 331 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOzVncV1-8ITKYQrre5:-NOzVncV1-8ITKYQrre6:bwq7ljm) ([raw file](https://github.com/starkware-libs/cairo/blob/fe82890e5560ea3dee86985d633971ee0eda1095/crates/cairo-lang-lowering/src/lower/scope.rs#L331)):*
> ```XML
>                 let block_id = scope.block_id;
>                 scope
>                     .finalize(ctx, StructuredBlockEnd::Goto { target: target.unwrap(), remapping });
> ```

Why get an option and then unwrap it?



_Code quote:_
```XML
arget.unwrap(), 
```
___
*[`crates/cairo-lang-lowering/src/panic/mod.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOzYwtf2S7ZvKEFOOgw:-NOzYwtf2S7ZvKEFOOgx:b-b5ifhi) ([raw file](https://github.com/starkware-libs/cairo/blob/fe82890e5560ea3dee86985d633971ee0eda1095/crates/cairo-lang-lowering/src/panic/mod.rs#L90)):*
> ```XML
>         block_ctx.update_refs(&stmt.ref_updates);
>         if let Some(continuation_block) = block_ctx.handle_statement(&stmt)? {
>             // Last statement was a match, so we can end with unreachable.
> ```

fallthrough?



_Code quote:_
```XML
unreachable
```
___
*[`crates/cairo-lang-lowering/src/panic/mod.rs` line 100 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOz_Rg7BoNMxtPOpctN:-NOz_Rg7BoNMxtPOpctO:bh0uuko) ([raw file](https://github.com/starkware-libs/cairo/blob/fe82890e5560ea3dee86985d633971ee0eda1095/crates/cairo-lang-lowering/src/panic/mod.rs#L100)):*
> ```XML
>             // Append the rest of this block to the continuation block
>             let block_to_edit = &mut ctx.block_queue[continuation_block.0 - ctx.flat_blocks.len()];
>             block_to_edit.statements.extend(block.statements.drain(i + 1..));
> ```

extend the rest of the statements to the end of the continuation block? I am not sure I follow. Can you elaborate?
___
*[`crates/cairo-lang-lowering/src/panic/mod.rs` line 151 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOzYV2i26jA9byyJmgp:-NOzYV2j4G_UEkdBUJva:b-c8rv68) ([raw file](https://github.com/starkware-libs/cairo/blob/fe82890e5560ea3dee86985d633971ee0eda1095/crates/cairo-lang-lowering/src/panic/mod.rs#L151)):*
> ```XML
>     }
> 
>     /// Handles a statement. Returns the continuation block if needed.
> ```

please explain what a continuation block is, and when it's "needed"
___
*[`crates/cairo-lang-lowering/src/panic/mod.rs` line 183 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOz_qnW49eiAf7XXXb8:-NOz_qnW49eiAf7XXXb9:bfuhg7b) ([raw file](https://github.com/starkware-libs/cairo/blob/fe82890e5560ea3dee86985d633971ee0eda1095/crates/cairo-lang-lowering/src/panic/mod.rs#L183)):*
> ```XML
>     }
> 
>     fn handle_call_panic(&mut self, call: &StatementCall) -> BlockId {
> ```

please doc.
___
*[`crates/cairo-lang-lowering/src/panic/mod.rs` line 215 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOzaNwf8-CJSVWBE0IS:-NOzaNwf8-CJSVWBE0IT:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/fe82890e5560ea3dee86985d633971ee0eda1095/crates/cairo-lang-lowering/src/panic/mod.rs#L215)):*
> ```XML
> 
>         let block_continuation = self.ctx.enqueue_block(StructuredBlock {
>             initial_refs: self.current_refs.clone(),
> ```





_Suggestion:_
```XML
        let block_continuation = self.ctx.enqueue_block(StructuredBlock {
            initial_refs: self.current_refs.clone(),
            ..StructuredBlock::default()
        });
```
___
*[`crates/cairo-lang-lowering/src/panic/mod.rs` line 234 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOzao7o1hj-pNd_oQSk:-NOzao7o1hj-pNd_oQSl:b-bjcg0x) ([raw file](https://github.com/starkware-libs/cairo/blob/fe82890e5560ea3dee86985d633971ee0eda1095/crates/cairo-lang-lowering/src/panic/mod.rs#L234)):*
> ```XML
>         });
> 
>         // It gets returned at this function to let the caller know that.
> ```

I don't understand this sentence.
___
*[`crates/cairo-lang-sierra-generator/src/block_generator.rs` line 157 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOzbX_28m9P2o7v5diw:-NOzbX_28m9P2o7v5dix:b-s92f09) ([raw file](https://github.com/starkware-libs/cairo/blob/fe82890e5560ea3dee86985d633971ee0eda1095/crates/cairo-lang-sierra-generator/src/block_generator.rs#L157)):*
> ```XML
>     for (idx, (output, inner_output)) in remapping.iter().enumerate() {
>         let _use_location = UseLocation { statement_location, idx };
>         let should_dup = false; //should_dup(context, &use_location);
> ```

leftover from debugging?
___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 413 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOzc4pw6w7d7H-WK9zD:-NOzc4pw6w7d7H-WK9zE:b6xdcvj) ([raw file](https://github.com/starkware-libs/cairo/blob/fe82890e5560ea3dee86985d633971ee0eda1095/crates/cairo-lang-sierra-generator/src/local_variables.rs#L413)):*
> ```XML
>     fn mark_outputs_as_temporary(
>         &mut self,
>         _lowered_function: &FlatLowered,
> ```

can this be removed?
___
*[`crates/cairo-lang-sierra-generator/src/block_generator_test_data/early_return` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOxoO-KBJn7FCKpQZov:-NOzcHXC5OXk0hHYJ2a4:b32v57) ([raw file](https://github.com/starkware-libs/cairo/blob/8402783900f47970faba86509e44ac10c341645a/crates/cairo-lang-sierra-generator/src/block_generator_test_data/early_return#L35)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

+1
___
*[`crates/cairo-lang-sierra-generator/src/block_generator_test_data/match` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOxocvY8LF45SrzmyhX:-NOzcUf154m5H55T9sbq:bj0vffh) ([raw file](https://github.com/starkware-libs/cairo/blob/8402783900f47970faba86509e44ac10c341645a/crates/cairo-lang-sierra-generator/src/block_generator_test_data/match#L35)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

seems wrong
</blockquote></details>

There is no label2. Same below...
___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/inline` line 66 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOzccp36ShMD2nT1zWU:-NOzccp36ShMD2nT1zWV:bl88b5) ([raw file](https://github.com/starkware-libs/cairo/blob/fe82890e5560ea3dee86985d633971ee0eda1095/crates/cairo-lang-sierra-generator/src/function_generator_test_data/inline#L66)):*
> ```
> jump() { label7() }
> label2:
> label7:
> ```

Same here. Seems like you have an off-by-one or something else
___
*[`tests/e2e_test_data/libfuncs/array` line 182 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOzdFEW5EUZ5v5gVHCx:-NOzdFEW5EUZ5v5gVHCy:b-z8cps5) ([raw file](https://github.com/starkware-libs/cairo/blob/fe82890e5560ea3dee86985d633971ee0eda1095/tests/e2e_test_data/libfuncs/array#L182)):*
> ```
> store_temp<Array<felt>>([3]) -> ([5]);
> store_temp<core::option::Option::<core::felt>>([8]) -> ([6]);
> jump() { 12() };
> ```

oh no! why did we get this back?
This is a Sierra "jump-rel-1". It translates to the casm "jmp rel 2" above.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2254)* status: 4 of 94 files reviewed, 13 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/borrow_check/analysis.rs` line 91 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOxnlG4Cej5tbur5Wk4:-NPCa-5B8HBVXnzjbFnr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8402783900f47970faba86509e44ac10c341645a/crates/cairo-lang-lowering/src/borrow_check/analysis.rs#L91)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/borrow_check/analysis.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOzTPKh0fZ7SvJF4gs6:-NPC_wp2CUwzO6EBdqsi:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fe82890e5560ea3dee86985d633971ee0eda1095/crates/cairo-lang-lowering/src/borrow_check/analysis.rs#L61)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

There are still "real blocks" here. Do you want to remove them in a future PR or in this one?
I find it confusing to have this "real" words here where there isn't RealBlock anymore.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/inline/test_data/inline` line 949 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOzUo3D09nK4FOJgPPu:-NPCaTDID6qseqcHkPza:b-4n89wa) ([raw file](https://github.com/starkware-libs/cairo/blob/fe82890e5560ea3dee86985d633971ee0eda1095/crates/cairo-lang-lowering/src/inline/test_data/inline#L949)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

This also doesn't make sense anymore.
</blockquote></details>

I think it makes sense.
___
*[`crates/cairo-lang-lowering/src/inline/test_data/inline` line 990 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOzVKmy-3r1jMNneEHU:-NPCbg3bD4s_7BtXELUb:b-qq1ojk) ([raw file](https://github.com/starkware-libs/cairo/blob/fe82890e5560ea3dee86985d633971ee0eda1095/crates/cairo-lang-lowering/src/inline/test_data/inline#L990)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Why is your change adding new blocks?
</blockquote></details>

Panic phase had to break the block



_Code quote:_
```
  () <- match_enum(v5) {
    PanicResult::Ok => blk1,
    PanicResult::Err => blk2,
  }
```
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 331 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOzVncV1-8ITKYQrre5:-NPCccR50bWoEtGq6JtR:b-w5trfj) ([raw file](https://github.com/starkware-libs/cairo/blob/fe82890e5560ea3dee86985d633971ee0eda1095/crates/cairo-lang-lowering/src/lower/scope.rs#L331)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Why get an option and then unwrap it?
</blockquote></details>

Only in the GotoCallsite case.
target will be None only if all the branches are not GotoCallsite
___
*[`crates/cairo-lang-lowering/src/panic/mod.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOxo-SrEl4h8wqBdpNJ:-NPCd5hl47SLdaE-ZEw_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8402783900f47970faba86509e44ac10c341645a/crates/cairo-lang-lowering/src/panic/mod.rs#L81)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/panic/mod.rs` line 100 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOz_Rg7BoNMxtPOpctN:-NPCdfJlDuF3GB519jvB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fe82890e5560ea3dee86985d633971ee0eda1095/crates/cairo-lang-lowering/src/panic/mod.rs#L100)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

extend the rest of the statements to the end of the continuation block? I am not sure I follow. Can you elaborate?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/panic/mod.rs` line 151 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOzYV2i26jA9byyJmgp:-NPCe0x76JZ_ntQwPRuX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fe82890e5560ea3dee86985d633971ee0eda1095/crates/cairo-lang-lowering/src/panic/mod.rs#L151)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

please explain what a continuation block is, and when it's "needed"
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/panic/mod.rs` line 215 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOzaNwf8-CJSVWBE0IS:-NPCeCOp34j8eEp1_Aqv:b-wac8hn) ([raw file](https://github.com/starkware-libs/cairo/blob/fe82890e5560ea3dee86985d633971ee0eda1095/crates/cairo-lang-lowering/src/panic/mod.rs#L215)):*
> ```XML
> 
>         let block_continuation = self.ctx.enqueue_block(StructuredBlock {
>             initial_refs: self.current_refs.clone(),
> ```

Noted. This way, when adding a new field, this will have to be revisited by the developer.
___
*[`crates/cairo-lang-lowering/src/panic/mod.rs` line 234 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOzao7o1hj-pNd_oQSk:-NPCeTIC4wy57OTuaaia:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fe82890e5560ea3dee86985d633971ee0eda1095/crates/cairo-lang-lowering/src/panic/mod.rs#L234)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I don't understand this sentence.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 413 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOzc4pw6w7d7H-WK9zD:-NPCehez57R76LmvlMpF:b8zq29l) ([raw file](https://github.com/starkware-libs/cairo/blob/fe82890e5560ea3dee86985d633971ee0eda1095/crates/cairo-lang-sierra-generator/src/local_variables.rs#L413)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

can this be removed?
</blockquote></details>

Yes, in a following PR.
___
*[`crates/cairo-lang-sierra-generator/src/block_generator_test_data/early_return` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOxoO-KBJn7FCKpQZov:-NPCekrGCOSIe8maQCid:b-xqwzz3) ([raw file](https://github.com/starkware-libs/cairo/blob/8402783900f47970faba86509e44ac10c341645a/crates/cairo-lang-sierra-generator/src/block_generator_test_data/early_return#L35)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

+1
</blockquote></details>

Extra goto, since the last match arm is not a Fallthrough.. Will be removed later.
___
*[`crates/cairo-lang-sierra-generator/src/block_generator_test_data/match` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOxocvY8LF45SrzmyhX:-NPCq9xSCyjMCZq8dtmQ:b5ert67) ([raw file](https://github.com/starkware-libs/cairo/blob/8402783900f47970faba86509e44ac10c341645a/crates/cairo-lang-sierra-generator/src/block_generator_test_data/match#L35)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

There is no label2. Same below...
</blockquote></details>

All of these are wrong, sinec nothing works until the very last PR. I moved the fixes there.
Done.
___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/inline` line 111 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOy1el74ypO3frcllyn:-NPCqBTiAU-3qHWw3cc4:b5ert67) ([raw file](https://github.com/starkware-libs/cairo/blob/8402783900f47970faba86509e44ac10c341645a/crates/cairo-lang-sierra-generator/src/function_generator_test_data/inline#L111)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this definitely should not happen. 
</blockquote></details>

All of these are wrong, sinec nothing works until the very last PR. I moved the fixes there.
Done.
___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/inline` line 66 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOzccp36ShMD2nT1zWU:-NPCqB8Q2wRbop-kJWXJ:b5ert67) ([raw file](https://github.com/starkware-libs/cairo/blob/fe82890e5560ea3dee86985d633971ee0eda1095/crates/cairo-lang-sierra-generator/src/function_generator_test_data/inline#L66)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Same here. Seems like you have an off-by-one or something else
</blockquote></details>

All of these are wrong, sinec nothing works until the very last PR. I moved the fixes there.
Done.
___
*[`tests/e2e_test_data/libfuncs/array` line 182 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOzdFEW5EUZ5v5gVHCx:-NPCqNhWCUhGxWGWHQM-:b-wel7f3) ([raw file](https://github.com/starkware-libs/cairo/blob/fe82890e5560ea3dee86985d633971ee0eda1095/tests/e2e_test_data/libfuncs/array#L182)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

oh no! why did we get this back?
This is a Sierra "jump-rel-1". It translates to the casm "jmp rel 2" above.
</blockquote></details>

Extra goto:( Ill make a PR after all of these are merged.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 90 of 90 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2254#-:-NPCt2xf3B9GHD1iEujp:bnfp4nl)* status: all files reviewed, 11 unresolved discussions (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 81 of 90 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2254)* status: all files reviewed, 5 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/analysis.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOzTPKh0fZ7SvJF4gs6:-NPD0HaT7uv4A7lf_YOn:b-tafl2c) ([raw file](https://github.com/starkware-libs/cairo/blob/fe82890e5560ea3dee86985d633971ee0eda1095/crates/cairo-lang-lowering/src/borrow_check/analysis.rs#L61)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Remove other leftovers of "real"
___
*[`crates/cairo-lang-lowering/src/inline/test_data/inline` line 949 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NOzUo3D09nK4FOJgPPu:-NPD0DKI7Sq1viFmlTTz:bkqvyot) ([raw file](https://github.com/starkware-libs/cairo/blob/fe82890e5560ea3dee86985d633971ee0eda1095/crates/cairo-lang-lowering/src/inline/test_data/inline#L949)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I think it makes sense.
</blockquote></details>

OK, s/root/last/
___
*[`crates/cairo-lang-lowering/src/inline/test_data/inline` line 943 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NPCwv-k5RrZ4DIIEWte:-NPCwv-k5RrZ4DIIEWtf:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/832de8f82d488517f0d03393177f7efc642095be/crates/cairo-lang-lowering/src/inline/test_data/inline#L943)):*
> ```
> //! > ==========================================================================
> 
> //! > Test match where is there is a return in one branch.
> ```





_Suggestion:_
```
 where there is a return
```
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 302 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NPCxc9d9ZbZRWwSW6-0:-NPCxc9d9ZbZRWwSW6-1:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/832de8f82d488517f0d03393177f7efc642095be/crates/cairo-lang-lowering/src/lower/scope.rs#L302)):*
> ```XML
>     /// Given the extra information needed, returns the ID of the final block.
>     /// This information includes the semantic remapping of variables and the target block to jump
>     /// to.
> ```





_Suggestion:_
```XML
    /// This information includes the semantic remapping of variables and the target block to jump
    /// to, in case this block is a GOTO.
```
___
*[`crates/cairo-lang-lowering/src/panic/mod.rs` line 92 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NPCy5A81JftwPLBzGzK:-NPCy5A81JftwPLBzGzL:b-kpygvx) ([raw file](https://github.com/starkware-libs/cairo/blob/832de8f82d488517f0d03393177f7efc642095be/crates/cairo-lang-lowering/src/panic/mod.rs#L92)):*
> ```XML
> 
>             // TODO(spapini): End with unreachable instead of a fallback.
>             // Last statement was a match. End with fallback just to maintain structure of blocks.
> ```

twice:
s/fallback/fallthrough/



_Code quote:_
```XML
            // TODO(spapini): End with unreachable instead of a fallback.
            // Last statement was a match. End with fallback just to maintain structure of blocks.
```
___
*[`crates/cairo-lang-lowering/src/panic/mod.rs` line 101 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NPCyTt1-AjEqHZZMRRI:-NPCyTt1-AjEqHZZMRRJ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/832de8f82d488517f0d03393177f7efc642095be/crates/cairo-lang-lowering/src/panic/mod.rs#L101)):*
> ```XML
>             );
> 
>             // The rest of the statements in this block have not been handled yet, and should be
> ```





_Suggestion:_
```XML
            // The rest of the statements in this block have not been handled yet, and should be
            // handled as a part of the continuation block - the second block in the "split".
```
___
*[`crates/cairo-lang-lowering/src/panic/mod.rs` line 158 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2254#-NPCywO36SiQWjcID1Fm:-NPCywO36SiQWjcID1Fn:b6uu0l4) ([raw file](https://github.com/starkware-libs/cairo/blob/832de8f82d488517f0d03393177f7efc642095be/crates/cairo-lang-lowering/src/panic/mod.rs#L158)):*
> ```XML
>     /// The continuation block happens when a panic match is added, and the block
>     /// need to be split. The continuation block is the second block in the "split".
>     /// This function already creates this second block (partially), and returns it.
> ```

WDYM by "partially"?



_Code quote:_
```XML
(partially
```

**Pull request closed without merging**
