### PR TITLE
Added ecdsa recovery.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #3728
- #3691 ⬅
- #3690

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3691)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/test/ec_test.cairo` line 135 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3691#-Na0iqrTADIyzvRlmjb_:-Na0iqrTADIyzvRlmjba:bfoheiv) ([raw file](https://github.com/starkware-libs/cairo/blob/90cb912d22ef3a514d2570a0a5db1b9024d8ade5/corelib/src/test/ec_test.cairo#L135)):*
> ```Cairo
>         ),
>         'ecdsa returned false'
>     );
> ```

please just check that ecdsa::recover_public_key(
                :message_hash, :signature_r, :signature_s, y_parity: true
            ) 
returns the public key.



_Code quote:_
```Cairo
    assert(
        ecdsa::check_ecdsa_signature(
            :message_hash,
            public_key: ecdsa::recover_public_key(
                :message_hash, :signature_r, :signature_s, y_parity: true
            )
                .unwrap(),
            :signature_r,
            :signature_s
        ),
        'ecdsa returned false'
    );
```

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/ecdsa.cairo` line 130 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3691#-Na0jAZO4e4H-ofwbmlt:-Na0jAZO4e4H-ofwbmlu:b-40kwvj) ([raw file](https://github.com/starkware-libs/cairo/blob/90cb912d22ef3a514d2570a0a5db1b9024d8ade5/corelib/src/ecdsa.cairo#L130)):*
> ```Cairo
>     //   zG +/- rQ = +/- sR.
>     // 
>     // Since this is a recovery, and we've bound R's parity we can find values such that:
> ```

what does that mean?



_Code quote:_
```Cairo
we've bound R's parity
```

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/ecdsa.cairo` line 131 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3691#-Na0jSd--G4R-hWVafbH:-Na0jSd--G4R-hWVafbI:b-zfnlkm) ([raw file](https://github.com/starkware-libs/cairo/blob/90cb912d22ef3a514d2570a0a5db1b9024d8ade5/corelib/src/ecdsa.cairo#L131)):*
> ```Cairo
>     // 
>     // Since this is a recovery, and we've bound R's parity we can find values such that:
>     //   zG +/- rQ = sR.
> ```

There is no `+/-` in the code.



_Code quote:_
```Cairo
zG +/- rQ = sR.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/ecdsa.cairo` line 131 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3691#-Na0jSd--G4R-hWVafbH:-Na0jfAL-zWkkWguzfWx:bq5ibu1) ([raw file](https://github.com/starkware-libs/cairo/blob/90cb912d22ef3a514d2570a0a5db1b9024d8ade5/corelib/src/ecdsa.cairo#L131)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

There is no `+/-` in the code.
</blockquote></details>

the formula is the same as here:
https://github.com/starkware-libs/cairo/blob/1edcc130fe701820016f9f4af754543b16bfbf67/corelib/src/starknet/secp256_trait.cairo#L60

right?

**Comment by orizi** [comment]
Closing pull request: commit has gone away

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3691)* status: 0 of 2 files reviewed, 3 unresolved discussions

___
*[`corelib/src/ecdsa.cairo` line 130 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3691#-Na0jAZO4e4H-ofwbmlt:-Na1Tl_e8PGzJQYRTEB0:b-9u6jsr) ([raw file](https://github.com/starkware-libs/cairo/blob/90cb912d22ef3a514d2570a0a5db1b9024d8ade5/corelib/src/ecdsa.cairo#L130)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what does that mean?
</blockquote></details>

this is a recovery function - so the parity of y (which is Q.y) is determined from the inputs.
so there's no need for +/- there, as the caller decide on the sign.
___
*[`corelib/src/ecdsa.cairo` line 131 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3691#-Na0jSd--G4R-hWVafbH:-Na1U7Ls6AeiMnDyAd_J:bc5bury) ([raw file](https://github.com/starkware-libs/cairo/blob/90cb912d22ef3a514d2570a0a5db1b9024d8ade5/corelib/src/ecdsa.cairo#L131)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

the formula is the same as here:
https://github.com/starkware-libs/cairo/blob/1edcc130fe701820016f9f4af754543b16bfbf67/corelib/src/starknet/secp256_trait.cairo#L60

right?
</blockquote></details>

the next couple of lines exactly explicitly removes the +/- from the formula.

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/ecdsa.cairo` line 130 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3691#-Na0jAZO4e4H-ofwbmlt:-Na1l6At56VsvYjVwKod:bs9tdt1) ([raw file](https://github.com/starkware-libs/cairo/blob/90cb912d22ef3a514d2570a0a5db1b9024d8ade5/corelib/src/ecdsa.cairo#L130)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is a recovery function - so the parity of y (which is Q.y) is determined from the inputs.
so there's no need for +/- there, as the caller decide on the sign.
</blockquote></details>

I have no idea
what "bound R's parity" means.

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/ecdsa.cairo` line 131 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3691#-Na0jSd--G4R-hWVafbH:-Na1lXxTBrUAi-QGb9dl:bisgz4w) ([raw file](https://github.com/starkware-libs/cairo/blob/90cb912d22ef3a514d2570a0a5db1b9024d8ade5/corelib/src/ecdsa.cairo#L131)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the next couple of lines exactly explicitly removes the +/- from the formula.
</blockquote></details>

can't you define Q to be the correct point and remove the +/-?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3691)* status: 0 of 2 files reviewed, 3 unresolved discussions

___
*[`corelib/src/ecdsa.cairo` line 130 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3691#-Na0jAZO4e4H-ofwbmlt:-Na1oOPxC3qak3Ak-AOa:bebddq5) ([raw file](https://github.com/starkware-libs/cairo/blob/90cb912d22ef3a514d2570a0a5db1b9024d8ade5/corelib/src/ecdsa.cairo#L130)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I have no idea
what "bound R's parity" means.
</blockquote></details>

the +/- of rQ corresponds to the y_parity of the signature.
but it does seem my fix is in the wrong direction.
will fix in the open pr.
___
*[`corelib/src/ecdsa.cairo` line 131 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3691#-Na0jSd--G4R-hWVafbH:-Na1pDIfB7opfl7EW_Kz:b-nt8khj) ([raw file](https://github.com/starkware-libs/cairo/blob/90cb912d22ef3a514d2570a0a5db1b9024d8ade5/corelib/src/ecdsa.cairo#L131)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

can't you define Q to be the correct point and remove the +/-?
</blockquote></details>

no there are 2 +/- i can remove only one of them.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3691)* status: 0 of 2 files reviewed, 3 unresolved discussions

___
*[`corelib/src/test/ec_test.cairo` line 135 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3691#-Na0iqrTADIyzvRlmjb_:-Na1pRRRCI9nPTeF9H-V:bbxpued) ([raw file](https://github.com/starkware-libs/cairo/blob/90cb912d22ef3a514d2570a0a5db1b9024d8ade5/corelib/src/test/ec_test.cairo#L135)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

please just check that ecdsa::recover_public_key(
                :message_hash, :signature_r, :signature_s, y_parity: true
            ) 
returns the public key.
</blockquote></details>

it should return a valid public key - which is what i'm checking.

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/ecdsa.cairo` line 131 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3691#-Na0jSd--G4R-hWVafbH:-Na1q99N6Zsl-bZddpOA:b-tsj6oq) ([raw file](https://github.com/starkware-libs/cairo/blob/90cb912d22ef3a514d2570a0a5db1b9024d8ade5/corelib/src/ecdsa.cairo#L131)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no there are 2 +/- i can remove only one of them.
</blockquote></details>

why can't you write:

rQ = sR - zG?

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/test/ec_test.cairo` line 135 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3691#-Na0iqrTADIyzvRlmjb_:-Na1r2R94ZVpRchGHLt7:bmwnqpm) ([raw file](https://github.com/starkware-libs/cairo/blob/90cb912d22ef3a514d2570a0a5db1b9024d8ade5/corelib/src/test/ec_test.cairo#L135)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it should return a valid public key - which is what i'm checking.
</blockquote></details>

it should recover the public key.

you are checking additional stuff about the public key.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3691)* status: 0 of 2 files reviewed, 3 unresolved discussions

___
*[`corelib/src/ecdsa.cairo` line 131 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3691#-Na0jSd--G4R-hWVafbH:-Na1rzMuD1iMeogHadmh:bt327d3) ([raw file](https://github.com/starkware-libs/cairo/blob/90cb912d22ef3a514d2570a0a5db1b9024d8ade5/corelib/src/ecdsa.cairo#L131)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why can't you write:

rQ = sR - zG?
</blockquote></details>

there are 2 +- in the formula - the input only removes one, the .x possibly remove the other.
___
*[`corelib/src/test/ec_test.cairo` line 135 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3691#-Na0iqrTADIyzvRlmjb_:-Na1sAwK1DfStsaWdMWe:bf7zkvf) ([raw file](https://github.com/starkware-libs/cairo/blob/90cb912d22ef3a514d2570a0a5db1b9024d8ade5/corelib/src/test/ec_test.cairo#L135)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it should recover the public key.

you are checking additional stuff about the public key.
</blockquote></details>

i'm checking that signature with it is valid - that is all.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3691)* status: 0 of 2 files reviewed, 3 unresolved discussions

___
*[`corelib/src/ecdsa.cairo` line 130 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3691#-Na0jAZO4e4H-ofwbmlt:-Na1t7gF0pXd1PJrjQCg:b9z476w) ([raw file](https://github.com/starkware-libs/cairo/blob/90cb912d22ef3a514d2570a0a5db1b9024d8ade5/corelib/src/ecdsa.cairo#L130)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the +/- of rQ corresponds to the y_parity of the signature.
but it does seem my fix is in the wrong direction.
will fix in the open pr.
</blockquote></details>

oh - got confused - i was already correct about y_parity being `R`s partity.

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/ecdsa.cairo` line 131 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3691#-Na0jSd--G4R-hWVafbH:-Na1umMxCVjwDXjpyXSx:blk6dz2) ([raw file](https://github.com/starkware-libs/cairo/blob/90cb912d22ef3a514d2570a0a5db1b9024d8ade5/corelib/src/ecdsa.cairo#L131)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

there are 2 +- in the formula - the input only removes one, the .x possibly remove the other.
</blockquote></details>

Why can't you define Q.y to be the correct one?

**Pull request closed without merging**
