### PR TITLE
Fix inference of impls

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2456)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2456** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2456" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2456?utm_source=stack-comment).

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2456)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/inference` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2456#-NQP9h_F0i1075Th8HRV:-NQP9h_F0i1075Th8HRW:bmpd226) ([raw file](https://github.com/starkware-libs/cairo/blob/93d99a0d43885b90d085405cf9258e6d568eccfa/crates/cairo-lang-semantic/src/expr/test_data/inference#L3)):*
> ```
> //! > Test return type inference
> 
> //! > test_runner_name
> ```

why all the test deletion?



_Code quote:_
```
//! > Test return type inference

//! > test_runner_name
test_function_diagnostics
```
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 693 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2456#-NQP9saC9avGmlQj2M_h:-NQP9saC9avGmlQj2M_i:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e4134bda3f8bb8acef7b9cf746813640699d6f7d/crates/cairo-lang-semantic/src/items/imp.rs#L693)):*
> ```XML
>     stable_ptr: SyntaxStablePtrId,
> ) -> Maybe<bool> {
>     // TODO(spapini); Fix this to *really* find out it an impl exists. Right now, we can have
> ```





_Suggestion:_
```XML
) -> Maybe<bool> {
    // TODO(spapini); Fix this to *really* find out if an impl exists. Right now, we can have
    // leftover variables.
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2456)* status: 10 of 12 files reviewed, 2 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/inference` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2456#-NQP9h_F0i1075Th8HRV:-NQTlS273ASRtZsT7NYc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/93d99a0d43885b90d085405cf9258e6d568eccfa/crates/cairo-lang-semantic/src/expr/test_data/inference#L3)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why all the test deletion?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 693 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2456#-NQP9saC9avGmlQj2M_h:-NQTlStaBBO_iDzpvlH1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e4134bda3f8bb8acef7b9cf746813640699d6f7d/crates/cairo-lang-semantic/src/items/imp.rs#L693)):*
> ```XML
>     stable_ptr: SyntaxStablePtrId,
> ) -> Maybe<bool> {
>     // TODO(spapini); Fix this to *really* find out it an impl exists. Right now, we can have
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2456#-:-NQU-Hhp0AqSgdF4-oAf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
