### PR TITLE
Better missing gas argument message for cairo-run.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2842)

### CODE REVIEW

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2842)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/cli.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2842#-NTCG4PH9uhtf4Xq1KMz:-NTCG4PH9uhtf4Xq1KN-:bpmwc5y) ([raw file](https://github.com/starkware-libs/cairo/blob/f2bb0c13e0758f66feb309a71102d3d77fd333f6/crates/cairo-lang-runner/src/cli.rs#L59)):*
> ```XML
>         })
>     {
>         anyhow::bail!("Program requires gas counter, please provide `available_gas` argument.");
> ```

Perhaps --available_gas ?

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2842)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2842)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2842#-:-NTCI7BAD6w1g5-Rjcsz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
