### PR TITLE
Allowed to get the diagnostics mappings in the LS.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6276)

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6276)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6276#-O58C_6RDEgoJpLiZmA8:-O58C_6RDEgoJpLiZmA9:bnz7al) (no related file):*
@mkaput tested by hand.
any ideas about proper testing? this is, by definition, dependent on possibly unstable ids.

___

**Review by piotmag769 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6276)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/src/env_config.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6276#-O5CpgBoBWnQssaM3geN:-O5CpgBoBWnQssaM3geO:b-6k2h55) ([raw file](https://github.com/starkware-libs/cairo/blob/f1280b6b77c2d403914e8e77357429201586fd81/crates/cairo-lang-language-server/src/env_config.rs#L32)):*
> ```XML
> }
> 
> /// Whether to generate LS tracing profile in the opened project directory.
> ```

I don't think this description is accurate, how is tracing profile == non-deduplicated diagnostics? You generate the tracing anyways
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/lsp.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6276#-O5Cr-KNEsEAcID0vbJ5:-O5Cr-KNEsEAcID0vbJ6:bagkoe7) ([raw file](https://github.com/starkware-libs/cairo/blob/f1280b6b77c2d403914e8e77357429201586fd81/crates/cairo-lang-language-server/src/lang/diagnostics/lsp.rs#L88)):*
> ```XML
>             }
>             related_info.push(DiagnosticRelatedInformation {
>                 location: Location { uri: db.url_for_file(mapped.file_id), range: mapped_range },
> ```

Isn't it the location we return? If so, why add a note about it, the mapped range will already point to this

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6276)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/env_config.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6276#-O5CpgBoBWnQssaM3geN:-O5CsUch-bKwFK05X7dQ:buldhkg) ([raw file](https://github.com/starkware-libs/cairo/blob/f1280b6b77c2d403914e8e77357429201586fd81/crates/cairo-lang-language-server/src/env_config.rs#L32)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

I don't think this description is accurate, how is tracing profile == non-deduplicated diagnostics? You generate the tracing anyways
</blockquote></details>

you are correct - it is accidentally copied comment.
Done.
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/lsp.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6276#-O5Cr-KNEsEAcID0vbJ5:-O5CsgC5E9rgQIzITEpJ:bde2zw) ([raw file](https://github.com/starkware-libs/cairo/blob/f1280b6b77c2d403914e8e77357429201586fd81/crates/cairo-lang-language-server/src/lang/diagnostics/lsp.rs#L88)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Isn't it the location we return? If so, why add a note about it, the mapped range will already point to this
</blockquote></details>

Good catch once again.
Done.

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6276)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6276#-O5DIDvF-VaUJq58-M-M:-O5DIDvG7PWvIgcW1zAo:b-ko3e9o) (no related file):*
I have no idea what this PR brings to the table. Please elaborate.

___
___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6276#-O5DIwao40fKqaFDKpJm):*
What are `mappings`?
___
*[`crates/cairo-lang-language-server/src/env_config.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6276#-O5DIuMT5PPFChSSNTeO:-O5DIuMT5PPFChSSNTeP:bvqy1h7) ([raw file](https://github.com/starkware-libs/cairo/blob/33730b9b3d0f44282608250ac7c8cc8e96cee77d/crates/cairo-lang-language-server/src/env_config.rs#L34)):*
> ```XML
> /// Whether to include the diagnostic mapping as a note for all diagnostic locations.
> pub fn include_diag_mapping() -> bool {
>     env::var_os(CAIRO_LS_INCLUDE_DIAG_MAPPING).map(env_to_bool).unwrap_or_default()
> ```

Why is this enabled by environment variable (which means that this is probably for our use as we do not expect regular users to ever touch these)?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6276)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6276#-O5DIDvF-VaUJq58-M-M:-O5DK5xC4aY4ti8fbmuI:b-kb9325) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I have no idea what this PR brings to the table. Please elaborate.
</blockquote></details>

power users write code that is heavily reliant on generated code - when there are errors - mapping makes the received code sometime too restrictive.

___
___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6276#-O5DIwao40fKqaFDKpJm):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

What are `mappings`?
</blockquote></details>

the thing that causes everything to point to actual user code instead of some internal virtual files.
___
*[`crates/cairo-lang-language-server/src/env_config.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6276#-O5DIuMT5PPFChSSNTeO:-O5DKU0k17bPqtm_0NE3:b-kb9325) ([raw file](https://github.com/starkware-libs/cairo/blob/33730b9b3d0f44282608250ac7c8cc8e96cee77d/crates/cairo-lang-language-server/src/env_config.rs#L34)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Why is this enabled by environment variable (which means that this is probably for our use as we do not expect regular users to ever touch these)?
</blockquote></details>

power users write code that is heavily reliant on generated code - when there are errors - mapping makes the received code sometime too restrictive.

**Review by piotmag769 — APPROVED** [review]
:lgtm: to unblock, discuss it with @mkaput 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6276#-:-O5DcgasBfg1_SQBXGFo:bht9aaz)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, and @mkaput)

**Review by piotmag769 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6276)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, and @mkaput)

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6276)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6276#-O58C_6RDEgoJpLiZmA8:-O5DuHHF5DzvYx3I21zs:bne5mj4) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

@mkaput tested by hand.
any ideas about proper testing? this is, by definition, dependent on possibly unstable ids.
</blockquote></details>

we have deterministic diagnostics emission (per file), aren't we?

if so then I think it should be totally fine to just dump vector of diagnostics as-is to the fixture, with separate files going to separate test file sections

___
___
*[`crates/cairo-lang-language-server/src/env_config.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6276#-O5DIuMT5PPFChSSNTeO:-O5Dyhvi7K6jKg83ehTI:bfg54fh) ([raw file](https://github.com/starkware-libs/cairo/blob/33730b9b3d0f44282608250ac7c8cc8e96cee77d/crates/cairo-lang-language-server/src/env_config.rs#L34)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

power users write code that is heavily reliant on generated code - when there are errors - mapping makes the received code sometime too restrictive.
</blockquote></details>

gotcha

so it looks like env vars are not the place to store this configuration. this should be kept in editor's settings (`workspace/configuration` request). we are wrapping all of this in this object: https://github.com/starkware-libs/cairo/blob/a39bf32abed0003a92f155e823d9cf8752ee0cc4/crates/cairo-lang-language-server/src/config.rs#L23 + there's pairing stuff in vscode's `package.json` to define the settings. please use this mechanism

don't bother with regenerating diagnostics on config change if this would happen overly complicated (give yourself 15 minutes budget for this); otherwise please make an issue (and attach it to our board by adding the `ide` label) so this won't be forgotten.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6276)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6276#-O58C_6RDEgoJpLiZmA8:-O5E-eHKBoU3XOlfov0B:bcu4k0g) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

we have deterministic diagnostics emission (per file), aren't we?

if so then I think it should be totally fine to just dump vector of diagnostics as-is to the fixture, with separate files going to separate test file sections
</blockquote></details>

the diagnostics are - but the generated file-ids are not - and these are part of the vfs path.

___
___
*[`crates/cairo-lang-language-server/src/env_config.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6276#-O5DIuMT5PPFChSSNTeO:-O5ELY7XDhsylTH9sIHR:bmfxpif) ([raw file](https://github.com/starkware-libs/cairo/blob/33730b9b3d0f44282608250ac7c8cc8e96cee77d/crates/cairo-lang-language-server/src/env_config.rs#L34)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

gotcha

so it looks like env vars are not the place to store this configuration. this should be kept in editor's settings (`workspace/configuration` request). we are wrapping all of this in this object: https://github.com/starkware-libs/cairo/blob/a39bf32abed0003a92f155e823d9cf8752ee0cc4/crates/cairo-lang-language-server/src/config.rs#L23 + there's pairing stuff in vscode's `package.json` to define the settings. please use this mechanism

don't bother with regenerating diagnostics on config change if this would happen overly complicated (give yourself 15 minutes budget for this); otherwise please make an issue (and attach it to our board by adding the `ide` label) so this won't be forgotten.
</blockquote></details>

Done.

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6276)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6276#-O58C_6RDEgoJpLiZmA8:-O5Hn8n89GKJCz0ne1Pe:bplk88t) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the diagnostics are - but the generated file-ids are not - and these are part of the vfs path.
</blockquote></details>

these files have plugin-defined file names, do I recall correctly? could we use them?

I remember there is something that has format `path[nondeterministic id]`; perhaps just assuming some prefix (like everything until `[`, or first 10 characters) could give enough stable precision for our purpose?

___
___
*[`vscode-cairo/package.json` line 124 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6276#-O5HnvTRDkmo0MVR9Nkb:-O5HnvTRDkmo0MVR9Nkc:brtw73k) ([raw file](https://github.com/starkware-libs/cairo/blob/f871dc24b56e2bc48077089e915e0085010c0fee/vscode-cairo/package.json#L124)):*
> ```JSON
>             "description": "Enable getting unmapped diagnostics information.",
>             "scope": "window"
>           },
> ```

config item name & description are not descriptive IMO (I can only understand these because of the context I gained by reviewing this PR).

here is something that comes to my mind, but please don't hesitate to propose something yet different



_Suggestion:_
```JSON
          "cairo1.traceMacroDiagnostics": {
            "type": "boolean",
            "description": "Attach additional information to diagnostics coming from macros, providing diagnostic source in macro generated code.",
            "scope": "window"
          },
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6276)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, and @mkaput)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6276#-O58C_6RDEgoJpLiZmA8:-O5HsshM9TNrBKWI9cns:biaatb0) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

these files have plugin-defined file names, do I recall correctly? could we use them?

I remember there is something that has format `path[nondeterministic id]`; perhaps just assuming some prefix (like everything until `[`, or first 10 characters) could give enough stable precision for our purpose?
</blockquote></details>

nothing in the area of this testing framework area supports that..

___
___
*[`vscode-cairo/package.json` line 124 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6276#-O5HnvTRDkmo0MVR9Nkb:-O5HwqYf26DHqFxzrtCJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f871dc24b56e2bc48077089e915e0085010c0fee/vscode-cairo/package.json#L124)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

config item name & description are not descriptive IMO (I can only understand these because of the context I gained by reviewing this PR).

here is something that comes to my mind, but please don't hesitate to propose something yet different
</blockquote></details>

Done.

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 3 of 5 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6276#-:-O5IB5de4ER29oqdcKdO:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6276#-O58C_6RDEgoJpLiZmA8:-O5IARvFCnHLDbsSjAY9:b-vsvv0x) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

nothing in the area of this testing framework area supports that..
</blockquote></details>

discussed offline. let's do that as separate task: #6291 

___

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 1 of 5 files at r3, 3 of 5 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6276)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
