### PR TITLE
add diagnostic for inconsistant mutability between or matches

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4711)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4711)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 850 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4711#-Nn4wf7fBVL--HpBwDwF:-Nn4wf7g7vHk6g_fAdom:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/741f37ea6c872e9b5eda3552757b157dc469936e/crates/cairo-lang-semantic/src/expr/compute.rs#L850)):*
> ```XML
>                                             .report(pattern_syntax, InconsistentBinding);
>                                     }
>                                 }
> ```





_Suggestion:_
```XML
                                    let get_location = || variable
                                                .var
                                                .stable_ptr(db.upcast())
                                                .lookup(db.upcast());
                                    let var = entry.get();
                                    let expected_ty = *var;
                                    
                                    if expected_ty != variable.var.ty {
                                        new_ctx.diagnostics.report(
                                            &get_location(),
                                            WrongType {
                                                expected_ty
                                                actual_ty: variable.var.ty,
                                            },
                                        );
                                    } else if var.is_mut != variable.var.is_mut {
                                        new_ctx
                                            .diagnostics
                                            .report(&get_location(), InconsistentBinding);
                                    }
                                }
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4711)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 850 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4711#-Nn4wf7fBVL--HpBwDwF:-Nn6Luws-Swri_I8OPLh:b-fmbfma) ([raw file](https://github.com/starkware-libs/cairo/blob/741f37ea6c872e9b5eda3552757b157dc469936e/crates/cairo-lang-semantic/src/expr/compute.rs#L850)):*
> ```XML
>                                             .report(pattern_syntax, InconsistentBinding);
>                                     }
>                                 }
> ```

why do I need the closure? 
did without for now

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4711)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 850 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4711#-Nn4wf7fBVL--HpBwDwF:-Nn6ftke5Wu3LCCt6qtG:bitofw7) ([raw file](https://github.com/starkware-libs/cairo/blob/741f37ea6c872e9b5eda3552757b157dc469936e/crates/cairo-lang-semantic/src/expr/compute.rs#L850)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

why do I need the closure? 
did without for now
</blockquote></details>

added the closure to not do a lookup when not actually requested.
add it.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4711)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 850 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4711#-Nn4wf7fBVL--HpBwDwF:-Nn8HsfY8fuu9a2kzDHn:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/741f37ea6c872e9b5eda3552757b157dc469936e/crates/cairo-lang-semantic/src/expr/compute.rs#L850)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

added the closure to not do a lookup when not actually requested.
add it.
</blockquote></details>

done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4711#-:-Nn8PuCQCdaDOCy5i_37:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4711)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
