### PR TITLE
Add tests to sierra location tests.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4891)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4891)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-sierra-generator/src/statements_locations_test.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4891#-NoqfzIu45Xwn9oGgMAR:-NoqfzIu45Xwn9oGgMAS:bylzc2z) ([raw file](https://github.com/starkware-libs/cairo/blob/c7274521d990cda0746c134118396569e5257fab/crates/cairo-lang-sierra-generator/src/statements_locations_test.rs#L71)):*
> ```XML
>     "src/statement_location_test_data",
>     {
>         tests: "tests",
> ```

leave the same name - rename in another PR.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4891)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi and @TomerStarkware)

___
*[`crates/cairo-lang-sierra-generator/src/statements_locations_test.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4891#-NoqfzIu45Xwn9oGgMAR:-NoqgAiL8S-sv4AwIn6U:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c7274521d990cda0746c134118396569e5257fab/crates/cairo-lang-sierra-generator/src/statements_locations_test.rs#L71)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

leave the same name - rename in another PR.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4891#-:-NoqhK0BApXleBKx4vhI:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-sierra-generator/src/statement_location_test_data/simple` line 214 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4891#-NoqhF8J9kARlks23R4k:-NoqhF8J9kARlks23R4l:b9dzynu) ([raw file](https://github.com/starkware-libs/cairo/blob/519c5d49e06dfbeaf67ce4ad47528d8317872826/crates/cairo-lang-sierra-generator/src/statement_location_test_data/simple#L214)):*
> ```
> //! > sierra_gen_diagnostics
> 
> //! > sierra_code
> ```

Fix output name in another PR.

**Review by TomerStarkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4891#-:-NoqhkHV-W93AKD-CtMB:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4891)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4891)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
