### PR TITLE
Add dict doc.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3085)

### CODE REVIEW

**Review by JameStark — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3085)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/felt252dict.adoc` line 47 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3085#-NUzlBb267rqY8FoDI-L:-NUzlBb267rqY8FoDI-M:bekvcnj) ([raw file](https://github.com/starkware-libs/cairo/blob/5b9c84a3c9e7b7e13dc494d985c10a9e494f1662/docs/reference/src/components/cairo/modules/language_constructs/pages/felt252dict.adoc#L47)):*
> ```AsciiDoc
> 
> Dictionaries are automatically destroyed when they go out of scope. However, the destruction
> process of a dictionary is not trivial, and the Destruct trait is implemented for `Felt252Dict``.
> ```

`Destruct`



_Code quote:_
```AsciiDoc
Destruct
```

**Review by JameStark — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3085)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/felt252dict.adoc` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3085#-NUzlGtL4Jv3j6NBPnly:-NUzlGtL4Jv3j6NBPnlz:bekvcnj) ([raw file](https://github.com/starkware-libs/cairo/blob/5b9c84a3c9e7b7e13dc494d985c10a9e494f1662/docs/reference/src/components/cairo/modules/language_constructs/pages/felt252dict.adoc#L48)):*
> ```AsciiDoc
> Dictionaries are automatically destroyed when they go out of scope. However, the destruction
> process of a dictionary is not trivial, and the Destruct trait is implemented for `Felt252Dict``.
> This means that Destruct must be derived for any type that contains a dictionary. For more
> ```

`Destruct`

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3085)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @JameStark and @orizi)

___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/felt252dict.adoc` line 47 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3085#-NUzlBb267rqY8FoDI-L:-NUzmbypAmeWyQi3jltV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5b9c84a3c9e7b7e13dc494d985c10a9e494f1662/docs/reference/src/components/cairo/modules/language_constructs/pages/felt252dict.adoc#L47)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

`Destruct`
</blockquote></details>

Done.
___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/felt252dict.adoc` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3085#-NUzlGtL4Jv3j6NBPnly:-NUzmbcD5B-T3fz-yyeK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5b9c84a3c9e7b7e13dc494d985c10a9e494f1662/docs/reference/src/components/cairo/modules/language_constructs/pages/felt252dict.adoc#L48)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

`Destruct`
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3085)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @JameStark)

___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/felt252dict.adoc` line 7 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3085#-NUzvprM4DCcDtPMFoha:-NUzvprM4DCcDtPMFohb:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/4ee0aeaa77339ffc10c0b0a927888a1bce7e522c/docs/reference/src/components/cairo/modules/language_constructs/pages/felt252dict.adoc#L7)):*
> ```AsciiDoc
> The `nullable<T>` type enables the dictionary to contain more complex types.
> 
> By default, the value `0`, or value logicaly equivalent to `0`, is returned for non-existing keys.
> ```





_Suggestion:_
```AsciiDoc
logically
```

**Review by JameStark — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3085)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3085)* status: all files reviewed, 3 unresolved discussions (waiting on @JameStark and @orizi)

___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/felt252dict.adoc` line 7 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3085#-NUzvprM4DCcDtPMFoha:-NV-1N2R5thnYyOBaNog:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4ee0aeaa77339ffc10c0b0a927888a1bce7e522c/docs/reference/src/components/cairo/modules/language_constructs/pages/felt252dict.adoc#L7)):*
> ```AsciiDoc
> The `nullable<T>` type enables the dictionary to contain more complex types.
> 
> By default, the value `0`, or value logicaly equivalent to `0`, is returned for non-existing keys.
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3085#-:-NV-1_V8Bdgn6E3M0O6J:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @JameStark)

**Pull request merged**
