### PR TITLE
Change mutable_* to *_mut.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6028)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6028)* status: 6 of 17 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin/storage_node.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6028#-O1vP8iaBSFrfPe04x-u:-O1vP8iaBSFrfPe04x-v:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/908d7c47957f6473e6ea7b41f7ef1f79f22fd71d/crates/cairo-lang-starknet/src/plugin/storage_node.rs#L141)):*
> ```XML
>     fn mutable_suffix(&self) -> String {
>         if self.is_mutable { "_mut".to_string() } else { "".to_string() }
>     }
> ```





_Suggestion:_
```XML
    /// Returns the mutable prefix of camelcase names.
    fn mutable_camelcase(&self) -> &'static str {
        if self.is_mutable { "Mutable" } else { "" }
    }
    /// Returns the mutable suffix for functions.
    fn mutable_suffix(&self) -> &'static str {
        if self.is_mutable { "_mut" } else { "" }
    }
```

**Review by orizi — COMMENTED** [review]
> Reviewed 11 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6028)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6028)* status: 17 of 21 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/storage_node.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6028#-O1vP8iaBSFrfPe04x-u:-O1vQZZ0-kD4ui1AxfLf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/908d7c47957f6473e6ea7b41f7ef1f79f22fd71d/crates/cairo-lang-starknet/src/plugin/storage_node.rs#L141)):*
> ```XML
>     fn mutable_suffix(&self) -> String {
>         if self.is_mutable { "_mut".to_string() } else { "".to_string() }
>     }
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6028#-:-O1vREQ4BOkwC4yRjw-Z:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
