### PR TITLE
Make  storage member address based.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
**Stack**:
- #5587
- #5586 ⬅
- #5585

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5586)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 24 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5586)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 278 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5586#-NyFc6HE7cd_oxpBoq4f:-NyFc6HE7cd_oxpBoq4g:b-o7ywv1) ([raw file](https://github.com/starkware-libs/cairo/blob/497b382634e9d64b7359f98d9a95a301abe6b170/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L278)):*
> ```
> 
> //! > ==========================================================================
> ```

why deleted?

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5586)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 278 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5586#-NyFc6HE7cd_oxpBoq4f:-NyFdF4v-yY4ywcvCDKh:b-lu2hy7) ([raw file](https://github.com/starkware-libs/cairo/blob/497b382634e9d64b7359f98d9a95a301abe6b170/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L278)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why deleted?
</blockquote></details>

`Map` is now a valid type. The `type not found` diagnostic was due to lack of `use starknet::storage::Map`, and map being directly used in the generated code. In the new generated code it is not used so there are no diagnostics.
I can reproduce something similar, but it'll just test the `use` not really something contract related.

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5586)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5586#-:-NyFf6eI3845Z-yHbwtJ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5586)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
