### PR TITLE
Add `Edition::latest`

### PR DESCRIPTION
**Pull request by mkaput**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4380)

### CODE REVIEW

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4380)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4380#-NinB8zHEbnDyPfuQovi:-NinB8zI6N8km8eMUDyd:b-n5tnr2) ([raw file](https://github.com/starkware-libs/cairo/blob/0fab1a9ddab8aab8cc36b34aa22a0f34b900c923/crates/cairo-lang-filesystem/src/db.rs#L55)):*
> ```XML
>     /// This Cairo edition is recommended for use in new projects and, in case of existing projects,
>     /// to migrate to when possible.
>     pub const fn latest() -> Self {
> ```

marking this as `const` so that this can be used in constant-expressions (like `static` initializers)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4380)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mkaput)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4380#-NinHNiz6q4__jKQ6Dli:-NinHNiz6q4__jKQ6Dlj:bqxb7w9) ([raw file](https://github.com/starkware-libs/cairo/blob/0fab1a9ddab8aab8cc36b34aa22a0f34b900c923/crates/cairo-lang-filesystem/src/db.rs#L54)):*
> ```XML
>     ///
>     /// This Cairo edition is recommended for use in new projects and, in case of existing projects,
>     /// to migrate to when possible.
> ```

do note that on scarb - `latest` shouldn't be allowed as a configuration for something that may have dependencies. (the idea is that this shouldn't break libraries a user uses, and if a lib is configured as latest, it would break users.)



_Code quote:_
```XML
    /// This Cairo edition is recommended for use in new projects and, in case of existing projects,
    /// to migrate to when possible.
```
___
*[`crates/cairo-lang-filesystem/src/db.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4380#-NinB8zHEbnDyPfuQovi:-NinHFrV857vW__xT7ah:b-ox1a1v) ([raw file](https://github.com/starkware-libs/cairo/blob/0fab1a9ddab8aab8cc36b34aa22a0f34b900c923/crates/cairo-lang-filesystem/src/db.rs#L55)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

marking this as `const` so that this can be used in constant-expressions (like `static` initializers)
</blockquote></details>

Fine with me.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4380#-:-NinHoZb6Z4YdZSbDsCv:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4380)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4380#-NinHNiz6q4__jKQ6Dli:-NinKjlVDqwrFbSye3Sl:bdky1q8) ([raw file](https://github.com/starkware-libs/cairo/blob/0fab1a9ddab8aab8cc36b34aa22a0f34b900c923/crates/cairo-lang-filesystem/src/db.rs#L54)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

do note that on scarb - `latest` shouldn't be allowed as a configuration for something that may have dependencies. (the idea is that this shouldn't break libraries a user uses, and if a lib is configured as latest, it would break users.)
</blockquote></details>

I don't follow. Do you mean that the following will not compile?

1. package A is 2023_01
2. package B is 2023_10
3. A depends on B

or do you mean vice versa, i.e. B depends on A?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4380)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4380#-NinHNiz6q4__jKQ6Dli:-NinLC7gBo6PktJihUmP:b-rewj8h) ([raw file](https://github.com/starkware-libs/cairo/blob/0fab1a9ddab8aab8cc36b34aa22a0f34b900c923/crates/cairo-lang-filesystem/src/db.rs#L54)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I don't follow. Do you mean that the following will not compile?

1. package A is 2023_01
2. package B is 2023_10
3. A depends on B

or do you mean vice versa, i.e. B depends on A?
</blockquote></details>

both would work:
My issue is with:
-   package A is 2023_01
-   package B is `latest`
-   A depends on B
Just saying `latest` shouldn't be an option for such a project.
`scarb update edition` or whatever is fine with me - just not having `latest` as the config.

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4380)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4380#-NinHNiz6q4__jKQ6Dli:-NinMnmX9JHXM4OzXHd7:bxh9sh2) ([raw file](https://github.com/starkware-libs/cairo/blob/0fab1a9ddab8aab8cc36b34aa22a0f34b900c923/crates/cairo-lang-filesystem/src/db.rs#L54)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

both would work:
My issue is with:
-   package A is 2023_01
-   package B is `latest`
-   A depends on B
Just saying `latest` shouldn't be an option for such a project.
`scarb update edition` or whatever is fine with me - just not having `latest` as the config.
</blockquote></details>

Ahh okay. No, that's not going to happen. We're not adding `latest` option here.

I apologize for not telling my motivation. We're going to use this field in `scarb new` and other places; when we want to say: “here you have the edition we recommend you to use”.

I've actually been thinking about naming this method `recommended`, perhaps that's the better word. Wdyt? Would it be more readable for you?

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4380)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mkaput)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4380#-NinHNiz6q4__jKQ6Dli:-NinZvgTBdaL_6u7h8tn:b-cvs2nx) ([raw file](https://github.com/starkware-libs/cairo/blob/0fab1a9ddab8aab8cc36b34aa22a0f34b900c923/crates/cairo-lang-filesystem/src/db.rs#L54)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Ahh okay. No, that's not going to happen. We're not adding `latest` option here.

I apologize for not telling my motivation. We're going to use this field in `scarb new` and other places; when we want to say: “here you have the edition we recommend you to use”.

I've actually been thinking about naming this method `recommended`, perhaps that's the better word. Wdyt? Would it be more readable for you?
</blockquote></details>

What *it is* is better than*why it is* for a name, so here latest is probably still best.

**Pull request merged**
