### PR TITLE
Added abi failure + warning for account contract functions.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #4599
- #4598
- #4597
- #4575 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4575)

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4575)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/src/abi.rs` line 261 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4575#-NlrrCnv3wcqYuuZ-4Rk:-Nls2GhQCI2VwLLKg9Eq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bc44841bbf2b406e3fdc18baa23caaa965ad5d51/crates/cairo-lang-starknet/src/abi.rs#L261)):*
> ```XML
>                 .find_attr(db, CONTRACT_ATTR)?
>                 .into_iter()
>                 .any(|attr| !attr.args.is_empty())
> ```

Done.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4575#-:-Nlw5y3W2dOFO8ga3jrZ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4575#-:-NlwXvccD8M_q1z6txyR:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4575)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4575)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
