### PR TITLE
E2E test for EC libfuncs

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
Signed-off-by: Dori Medini <dori@starkware.co>

commit-id:93967f14

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1755)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1755)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @orizi)

___
*[`tests/e2e_test_data/libfuncs/ec` line 108 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1755#-NL_auxfA3-N36sc0SF_:-NL_auxfA3-N36sc0SFa:b-uy27ao) ([raw file](https://github.com/starkware-libs/cairo/blob/cf86dd13954acddc00588ecee64a6c237d5e6556/tests/e2e_test_data/libfuncs/ec#L108)):*
> ```
> %{ memory[ap + 0] = segments.add() %}
> ap += 1;
> [ap + 0] = 2037172927806520182083, ap++;
> ```

this is the `'not on EC'` string I think



_Code quote:_
```
2037172927806520182083
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1755)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`tests/e2e_test_data/libfuncs/ec` line 249 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1755#-NL_dQUf4INNJRoa7NLv:-NL_dQUf4INNJRoa7NLw:b5tq0z4) ([raw file](https://github.com/starkware-libs/cairo/blob/cf86dd13954acddc00588ecee64a6c237d5e6556/tests/e2e_test_data/libfuncs/ec#L249)):*
> ```
>     y2 = x**3 + ALPHA * x + BETA
>     return x, sympy.ntheory.residue_ntheory.sqrt_mod(
>         y2, PRIME, all_roots=True
> ```

@orizi we don't care if this code doesn't actually work...? I.e. the `ALPHA`, `BETA` and `PRIME` constants may not be defined



_Code quote:_
```
%{
def try_sample_point() -> Tuple[int, int]:
    x = random.randrange(PRIME)
    y2 = x**3 + ALPHA * x + BETA
    return x, sympy.ntheory.residue_ntheory.sqrt_mod(
        y2, PRIME, all_roots=True
    )
x, y = try_sample_point()
while y is None:
    x, y = try_sample_point()
(memory[ap + 0], memory[ap + 1]) = x, y
%}
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1755)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`tests/e2e_test_data/libfuncs/ec` line 596 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1755#-NL_dtgA2mhdWB5Ljqqt:-NL_dtgA2mhdWB5Ljqqu:bpjpdlo) ([raw file](https://github.com/starkware-libs/cairo/blob/cf86dd13954acddc00588ecee64a6c237d5e6556/tests/e2e_test_data/libfuncs/ec#L596)):*
> ```
> //! > ==========================================================================
> 
> //! > ec_try_op libfunc
> ```

@orizi this function (and `ec_op`) are user functions, do they also need an E2E test?



_Code quote:_
```
ec_try_op
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1755)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`tests/e2e_test_data/libfuncs/ec` line 249 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1755#-NL_dQUf4INNJRoa7NLv:-NL_fPS4At8vkm7B_yse:b-i6ih2d) ([raw file](https://github.com/starkware-libs/cairo/blob/cf86dd13954acddc00588ecee64a6c237d5e6556/tests/e2e_test_data/libfuncs/ec#L249)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@orizi we don't care if this code doesn't actually work...? I.e. the `ALPHA`, `BETA` and `PRIME` constants may not be defined
</blockquote></details>

we should care - test in playground if these are defined.
___
*[`tests/e2e_test_data/libfuncs/ec` line 596 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1755#-NL_dtgA2mhdWB5Ljqqt:-NL_faYU8uF0F6ycnllY:b-rrjgqu) ([raw file](https://github.com/starkware-libs/cairo/blob/cf86dd13954acddc00588ecee64a6c237d5e6556/tests/e2e_test_data/libfuncs/ec#L596)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@orizi this function (and `ec_op`) are user functions, do they also need an E2E test?
</blockquote></details>

no - this is only for libfuncs.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1755)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`tests/e2e_test_data/libfuncs/ec` line 412 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1755#-NL_gpkO26do7l3Zl5zC:-NL_gpkO26do7l3Zl5zD:b9t3maj) ([raw file](https://github.com/starkware-libs/cairo/blob/b83d7826e9b437b94ace8d318693b9d37234ea5f/tests/e2e_test_data/libfuncs/ec#L412)):*
> ```
> 
> //! > ec_finalize_state libfunc
> ```

remove - not a libfunc.



_Code quote:_
```
//! > ec_finalize_state libfunc
```
___
*[`tests/e2e_test_data/libfuncs/ec` line 596 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1755#-NL_h-sY-Vq98qPb5Cle:-NL_h-sY-Vq98qPb5Clf:b9t3maj) ([raw file](https://github.com/starkware-libs/cairo/blob/b83d7826e9b437b94ace8d318693b9d37234ea5f/tests/e2e_test_data/libfuncs/ec#L596)):*
> ```
> //! > ==========================================================================
> 
> //! > ec_try_op libfunc
> ```

remove - not a libfunc.



_Code quote:_
```
//! > ec_try_op libfunc
```
___
*[`tests/e2e_test_data/libfuncs/ec` line 604 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1755#-NL_gx7UD4d-n8TOAA8R:-NL_gx7UD4d-n8TOAA8S:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/b83d7826e9b437b94ace8d318693b9d37234ea5f/tests/e2e_test_data/libfuncs/ec#L604)):*
> ```
> 
> //! > cairo
> fn foo(p: EcPoint, m: felt, q: EcPoint) -> Option::<EcPoint> implicits(EcOp) {
> ```

remove



_Code quote:_
```
implicits(EcOp) 
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1755)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1755)* status: all files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1755)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1755)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`tests/e2e_test_data/libfuncs/ec` line 412 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1755#-NL_gpkO26do7l3Zl5zC:-NL_iS2yE2R7x-6xHDjP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b83d7826e9b437b94ace8d318693b9d37234ea5f/tests/e2e_test_data/libfuncs/ec#L412)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove - not a libfunc.
</blockquote></details>

Done.
___
*[`tests/e2e_test_data/libfuncs/ec` line 596 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1755#-NL_h-sY-Vq98qPb5Cle:-NL_iYYpENIal-z4YNVs:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b83d7826e9b437b94ace8d318693b9d37234ea5f/tests/e2e_test_data/libfuncs/ec#L596)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove - not a libfunc.
</blockquote></details>

Done.
___
*[`tests/e2e_test_data/libfuncs/ec` line 604 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1755#-NL_gx7UD4d-n8TOAA8R:-NL_ifiRE7Cl1vy_O-n3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b83d7826e9b437b94ace8d318693b9d37234ea5f/tests/e2e_test_data/libfuncs/ec#L604)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1755#-:-NL_k9Xk4X6c_uhtKyPk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1755)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @orizi)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1755)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
