### PR TITLE
Add CircuitInfo.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5488)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5488)* status: 1 of 8 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/circuit.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5488#-NwibCwgEngBWqo-vVT3:-NwibCwgEngBWqo-vVT4:b-qhq22e) ([raw file](https://github.com/starkware-libs/cairo/blob/f25bc18921d630e56a81a651e475aa5a63694fce/crates/cairo-lang-sierra/src/extensions/modules/circuit.rs#L65)):*
> ```XML
> }
> 
> /// Defines an input for a circuit.
> ```

re-add removed doc.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 20 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5488)* status: 4 of 21 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5488#-NwictAh6o8LmShH9v0c):*
resplit the PR.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5488)* status: 1 of 21 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5488#-NwictAh6o8LmShH9v0c):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

resplit the PR.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 8 files at r1, 5 of 20 files at r2, 14 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5488#-:-NwigJcW0TNXi-ThcaJq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
