### PR TITLE
Added forwarding of attributes in generated structs and enums.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #6743
- #6739 ⬅
- #6738

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by piotmag769 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6739)* status: 0 of 40 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @gilbens-starkware, @integraledelebesgue, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/src/config.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6739#-OCd5-B_1buIP4NGt5Od:-OCd5-Ba-Uf3Mp8Z1nwI:bthni8) ([raw file](https://github.com/starkware-libs/cairo/blob/4c50d3d886d4fc0a3971613956c69a144278a613/crates/cairo-lang-language-server/src/config.rs#L45)):*
> ```XML
>     /// The property is set by the user under the `cairo1.enableProcMacros` key in client
>     /// configuration.
>     pub enable_proc_macros: bool,
> ```

Rebase pls

**Review by orizi — COMMENTED** [review]
> Reviewed 24 of 24 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6739)* status: 24 of 40 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @gilbens-starkware, @integraledelebesgue, and @mkaput)

**Review by Arcticae — APPROVED** [review]
:lgtm: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6739#-:-OCd9iXv025P7I2EQdPs:bg7igkv)* status: 24 of 40 files reviewed, all discussions resolved (waiting on @Draggu, @gilbens-starkware, @integraledelebesgue, and @mkaput)

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 16 of 16 files at r1, 24 of 24 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6739)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
