### PR TITLE
Fixed ByteArray bug.

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4179)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4179#-:-Nfk3CPLCt6SyOE0-zpF:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/expr/objects.rs` line 396 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4179#-Nfk31YZ65puZVtKjeQu:-Nfk31Y_9-lN2OzHGTye:b-qs6903) ([raw file](https://github.com/starkware-libs/cairo/blob/4e3ed4e6324f2318a3d16dcb175e7ec22f82eaef/crates/cairo-lang-semantic/src/expr/objects.rs#L396)):*
> ```XML
>     pub value: BigInt,
>     #[hide_field_debug_with_db]
>     pub numeric_impl: ImplId,
> ```

was this not just never used?



_Code quote:_
```XML
    #[hide_field_debug_with_db]
    pub numeric_impl: ImplId,
```

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4179)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4179)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/objects.rs` line 396 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4179#-Nfk31YZ65puZVtKjeQu:-NfomNIfDhYkRgb_VcF9:b-pb9bue) ([raw file](https://github.com/starkware-libs/cairo/blob/4e3ed4e6324f2318a3d16dcb175e7ec22f82eaef/crates/cairo-lang-semantic/src/expr/objects.rs#L396)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

was this not just never used?
</blockquote></details>

indeed

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4179)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
