### PR TITLE
Change macro syntax to be token tree based and fix legacy macros.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
**Stack**:
- #6308 ⬅
- #6307

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6308)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6308)* status: 0 of 47 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-defs/src/plugin_utils.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6308#-O5RpgRwA8pbhqYTfmF8:-O5RpgRwA8pbhqYTfmF9:bxehlt5) ([raw file](https://github.com/starkware-libs/cairo/blob/2b6101096d77c4ea78e1896bb1d58da9b2731faa/crates/cairo-lang-defs/src/plugin_utils.rs#L77)):*
> ```XML
> pub fn not_legacy_macro_diagnostic(stable_ptr: SyntaxStablePtrId) -> PluginDiagnostic {
>     PluginDiagnostic::error(stable_ptr, "Macro can not be parsed as legacy macro.".to_string())
> }
> ```

remove and return as part of a `Result` when trying to convert.



_Code quote:_
```XML
pub fn not_legacy_macro_diagnostic(stable_ptr: SyntaxStablePtrId) -> PluginDiagnostic {
    PluginDiagnostic::error(stable_ptr, "Macro can not be parsed as legacy macro.".to_string())
}
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 47 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6308)* status: 4 of 47 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, and @piotmag769)

___
*[`corelib/src/test/keccak_test.cairo` line 37 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6308#-O5SZGen6qtxe-htQvqp:-O5SZGen6qtxe-htQvqq:b-ptraxx) ([raw file](https://github.com/starkware-libs/cairo/blob/89318c45d3515e598fc367d78594b90ca626412b/corelib/src/test/keccak_test.cairo#L37)):*
> ```Cairo
> fn test_keccak_u64() {
>     let mut input =
>         array![
> ```

awaiting fmt fix.

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 13 of 47 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6308)* status: 16 of 47 files reviewed, 6 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @maciektr, and @piotmag769)

___
*[`crates/cairo-lang-language-server/tests/e2e/support/mock_client.rs` line 273 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6308#-O5Tr5FE3dtyLQ0RPKbU:-O5Tr5FE3dtyLQ0RPKbV:b9hoq2n) ([raw file](https://github.com/starkware-libs/cairo/blob/cb819637619796640b680a1fbf78ee156bf11fb6/crates/cairo-lang-language-server/tests/e2e/support/mock_client.rs#L273)):*
> ```XML
> =======
>         const TIMEOUT: Duration = Duration::from_secs(4 * 60);
> >>>>>>> 8ceeb7726 (Change macro syntax to be token tree based and fix legacy macros.)
> ```

merge conflict
___
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 888 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6308#-O5TrBkF8T1sDIy_YCOc:-O5TrBkF8T1sDIy_YCOd:b-bjavyi) ([raw file](https://github.com/starkware-libs/cairo/blob/cb819637619796640b680a1fbf78ee156bf11fb6/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L888)):*
> ```
> note: the variable needs to be dropped due to the potential panic here:
>   --> lib.cairo:3:14
> struct MyStruct {
> ```

looks very off
___
*[`crates/cairo-lang-parser/src/parser.rs` line 44 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6308#-O5TrFzVEtjsCTxGayPl:-O5TrFzVEtjsCTxGayPm:b9hoq2n) ([raw file](https://github.com/starkware-libs/cairo/blob/cb819637619796640b680a1fbf78ee156bf11fb6/crates/cairo-lang-parser/src/parser.rs#L44)):*
> ```XML
>     /// The width of the current terminal being handled.
>     pub(crate) current_width: TextWidth,
> >>>>>>> 8ceeb7726 (Change macro syntax to be token tree based and fix legacy macros.)
> ```

merge conflict
___
*[`crates/cairo-lang-syntax/src/node/kind.rs` line 120 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6308#-O5TrO9V1QtxA5gTHXqU:-O5TrO9V1QtxA5gTHXqV:b9hoq2n) ([raw file](https://github.com/starkware-libs/cairo/blob/cb819637619796640b680a1fbf78ee156bf11fb6/crates/cairo-lang-syntax/src/node/kind.rs#L120)):*
> ```XML
>     ItemHeaderDoc,
> =======
> >>>>>>> 8ceeb7726 (Change macro syntax to be token tree based and fix legacy macros.)
> ```

merge conflict

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 32 of 47 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6308)* status: all files reviewed, 7 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @maciektr, and @piotmag769)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/contracts/circuit_contract.cairo` line 38 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6308#-O5Tt1fe--LtIZsRq6O3:-O5Tt1fe--LtIZsRq6O4:b-hiws9u) ([raw file](https://github.com/starkware-libs/cairo/blob/cb819637619796640b680a1fbf78ee156bf11fb6/crates/cairo-lang-starknet/cairo_level_tests/contracts/circuit_contract.cairo#L38)):*
> ```Cairo
>             match (inv,).new_inputs().next([3, 0, 0, 0]).next([6, 0, 0, 0]).done().eval(modulus) {
>             Result::Ok(outputs) => { outputs },
>             Result::Err(_) => { panic!("Expected success")      }
> ```

cairofmt did this whitespace change? :O

**Pull request closed without merging**
