### PR TITLE
Added escaping for short strings.

### PR DESCRIPTION
**Pull request by Alon-Ti**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1401)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1401)* status: 4 of 8 files reviewed, 1 unresolved discussion (waiting on @Alon-Ti)

___
*[`crates/semantic/src/expr/test.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1401#-NJhp_ONCw2UiNAa4HG6:-NJhp_ONCw2UiNAa4HG7:b-wjiuhr) ([raw file](https://github.com/starkware-libs/cairo/blob/134f4362cdeca36eeb3f8e9df3d75d48fcd027df/crates/semantic/src/expr/test.rs#L48)):*
> ```XML
> #[test_case(r"'\''", 39, "felt")]
> #[test_case(r"'\x12\x34'_u128", 0x1234, "u128")]
> fn test_expr_literal(expr: &str, value: i128, ty_name: &str) {
> ```

Add '\\' test - this should work, but currently I believe it won't

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1401)* status: 4 of 8 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/semantic/src/expr/test.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1401#-NJhp_ONCw2UiNAa4HG6:-NJj8EzO3UJp-wwkyOHE:by0340r) ([raw file](https://github.com/starkware-libs/cairo/blob/134f4362cdeca36eeb3f8e9df3d75d48fcd027df/crates/semantic/src/expr/test.rs#L48)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Add '\\' test - this should work, but currently I believe it won't 
</blockquote></details>

Why should it work? This string is missing its right delimiter, this is how Rust interprets it for example.

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1401)* status: 7 of 8 files reviewed, all discussions resolved

___
*[`crates/semantic/src/expr/test.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1401#-NJhp_ONCw2UiNAa4HG6:-NJjHhaW5EV3wm4ZZci-:boq4ef5) ([raw file](https://github.com/starkware-libs/cairo/blob/134f4362cdeca36eeb3f8e9df3d75d48fcd027df/crates/semantic/src/expr/test.rs#L48)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

Why should it work? This string is missing its right delimiter, this is how Rust interprets it for example.
</blockquote></details>

maybe i missed it (but originally seeing, i though you missed the handling of \\ in the lexer.

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1401#-:-NJjIE1Y38K4aFw8NMZl:bnfp4nl)* status: 7 of 8 files reviewed, all discussions resolved

**Review by Alon-Ti — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1401)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Alon-Ti)

**Pull request merged**
