### PR TITLE
compute_costs: Add WalletInfo in preparation for handling redeposits.

### PR DESCRIPTION
**Pull request by liorgold2**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3054)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3054)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-gas/src/compute_costs.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3054#-NUpe0Y1Cxt3t3B-gR1B:-NUpe0Y28HzKUxKioW4B:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/98fd631e06f699eb653ba210f7c1fd1a5fdc5fbf/crates/cairo-lang-sierra-gas/src/compute_costs.rs#L171)):*
> ```XML
> 
> #[derive(Clone, Debug, Default)]
> pub struct WalletInfo<CostType: CostTypeTrait> {
> ```

doc
___
*[`crates/cairo-lang-sierra-gas/src/compute_costs.rs` line 189 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3054#-NUpeY0g0WEVv0ZdaW2H:-NUpeY0g0WEVv0ZdaW2I:b2bg4mz) ([raw file](https://github.com/starkware-libs/cairo/blob/98fd631e06f699eb653ba210f7c1fd1a5fdc5fbf/crates/cairo-lang-sierra-gas/src/compute_costs.rs#L189)):*
> ```XML
>     /// Returns the value, assuming there are no used cost variables (panics otherwise).
>     // TODO(lior): Support cost variables - currently this function is identical to `get_value()`.
>     fn get_pure_value(self) -> CostType {
> ```

maybe `get_final_value`?

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3054)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3054)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-gas/src/compute_costs.rs` line 189 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3054#-NUpeY0g0WEVv0ZdaW2H:-NUpfU8v2j7kvslyVMfe:bg09rhq) ([raw file](https://github.com/starkware-libs/cairo/blob/98fd631e06f699eb653ba210f7c1fd1a5fdc5fbf/crates/cairo-lang-sierra-gas/src/compute_costs.rs#L189)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe `get_final_value`?
</blockquote></details>

Final doesn't fully capture the meaning, `get_value()` could have been called `get_final_value()`. The difference is that `get_pure_value` makes sure it's independent of any variables (unlike final which indicates that the assignment was completed, here there's no assignment)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3054#-:-NUpihXaCkfFBMi_l4_7:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-gas/src/compute_costs.rs` line 189 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3054#-NUpeY0g0WEVv0ZdaW2H:-NUpiJef99jKCplY_zAq:b-jjjocz) ([raw file](https://github.com/starkware-libs/cairo/blob/98fd631e06f699eb653ba210f7c1fd1a5fdc5fbf/crates/cairo-lang-sierra-gas/src/compute_costs.rs#L189)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Final doesn't fully capture the meaning, `get_value()` could have been called `get_final_value()`. The difference is that `get_pure_value` makes sure it's independent of any variables (unlike final which indicates that the assignment was completed, here there's no assignment)
</blockquote></details>

i don't think `pure` really captures the meaning - as it isn't really clear in what way it is pure.
resolving anyway - but we can probably improve this.

**Pull request merged**
