### PR TITLE
Fixed parsing of attributes

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2891)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2891)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 160 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2891#-NTi1dHP9pWf260gkNeK:-NTi1dHP9pWf260gkNeL:b-hawxd6) ([raw file](https://github.com/starkware-libs/cairo/blob/4740eaf7cde6bcd0e826edf2e61ed6d41064aee8/crates/cairo-lang-parser/src/parser.rs#L160)):*
> ```XML
>                 if has_attrs {
>                     Some(
>                         self.create_and_report_missing::<Item>(
> ```

What does this actually produce? Do we have a missing Item node?



_Code quote:_
```XML
self.create_and_report_missing::<Item>(
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2891)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 160 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2891#-NTi1dHP9pWf260gkNeK:-NTnAGTCB34nRJ5Hshan:bpn686p) ([raw file](https://github.com/starkware-libs/cairo/blob/4740eaf7cde6bcd0e826edf2e61ed6d41064aee8/crates/cairo-lang-parser/src/parser.rs#L160)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

What does this actually produce? Do we have a missing Item node?
</blockquote></details>

Thanks, I forgot to add it. Same for TraitItem.
Also added tests

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 1 of 7 files at r3, 1 of 1 files at r4, 6 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2891)* status: 12 of 20 files reviewed, 6 unresolved discussions (waiting on @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2891#-NUHZ2464uNc94uAInfC:-NUHZ2464uNc94uAInfD:bjx85ku) (no related file):*
Can you please add a missing item in one of the parser tests that show the ast?

___
___
*[`crates/cairo-lang-defs/src/db.rs` line 421 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2891#-NUHY7TO-tsuQ792EVs_:-NUHY7TP1jkM7FGpnmuq:b-m3pnub) ([raw file](https://github.com/starkware-libs/cairo/blob/2e217371973a188eb074599209e8bc41b57c51ba/crates/cairo-lang-defs/src/db.rs#L421)):*
> ```XML
>                     ModuleItemId::ImplAlias(item_id)
>                 }
>                 ast::Item::Missing(_) => unimplemented!(),
> ```

Dont panic
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 441 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2891#-NUHYtLw0TbUVpt9is3-:-NUHYtLw0TbUVpt9is30:bb73xfv) ([raw file](https://github.com/starkware-libs/cairo/blob/2e217371973a188eb074599209e8bc41b57c51ba/crates/cairo-lang-semantic/src/items/imp.rs#L441)):*
> ```XML
>                     impl_item_names.insert(impl_function_id.name(defs_db));
>                 }
>                 Item::Missing(_) => unimplemented!(),
> ```

Same
___
*[`crates/cairo-lang-semantic/src/items/trt.rs` line 234 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2891#-NUHYutz8dDBwkzF-Fhn:-NUHYutz8dDBwkzF-Fho:bb73xfv) ([raw file](https://github.com/starkware-libs/cairo/blob/2e217371973a188eb074599209e8bc41b57c51ba/crates/cairo-lang-semantic/src/items/trt.rs#L234)):*
> ```XML
>                     );
>                 }
>                 ast::TraitItem::Missing(_) => unimplemented!(),
> ```

Same
___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 87 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2891#-NUHYwlu7YsizHxzRyp5:-NUHYwlu7YsizHxzRyp6:bb73xfv) ([raw file](https://github.com/starkware-libs/cairo/blob/2e217371973a188eb074599209e8bc41b57c51ba/crates/cairo-lang-starknet/src/plugin/contract.rs#L87)):*
> ```XML
>             | ast::Item::FreeFunction(_) => None,
>             ast::Item::ImplAlias(_) => todo!(),
>             ast::Item::Missing(_) => unimplemented!(),
> ```

Same
___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 133 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2891#-NUHYyW15e7sjystjB7O:-NUHYyW2-j49xRYKNc7Z:bb73xfv) ([raw file](https://github.com/starkware-libs/cairo/blob/2e217371973a188eb074599209e8bc41b57c51ba/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L133)):*
> ```XML
>                 ));
>             }
>             ast::TraitItem::Missing(_) => unimplemented!(),
> ```

Same

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2891)* status: 7 of 22 files reviewed, 6 unresolved discussions (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2891#-NUHZ2464uNc94uAInfC:-NUH_thk8zMsI3YdA2wb:b-896fix) (no related file):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Can you please add a missing item in one of the parser tests that show the ast?
</blockquote></details>

Done.

___
___
*[`crates/cairo-lang-defs/src/db.rs` line 421 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2891#-NUHY7TO-tsuQ792EVs_:-NUHgmrMAkqzErf5EGCk:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2e217371973a188eb074599209e8bc41b57c51ba/crates/cairo-lang-defs/src/db.rs#L421)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Dont panic
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 441 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2891#-NUHYtLw0TbUVpt9is3-:-NUHh75n1tBkwYfz5eMP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2e217371973a188eb074599209e8bc41b57c51ba/crates/cairo-lang-semantic/src/items/imp.rs#L441)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Same
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/trt.rs` line 234 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2891#-NUHYutz8dDBwkzF-Fhn:-NUHhJ6E2nUnFSmuOyNU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2e217371973a188eb074599209e8bc41b57c51ba/crates/cairo-lang-semantic/src/items/trt.rs#L234)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Same
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 87 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2891#-NUHYwlu7YsizHxzRyp5:-NUHhSJy4OuDL0ENGDiz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2e217371973a188eb074599209e8bc41b57c51ba/crates/cairo-lang-starknet/src/plugin/contract.rs#L87)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Same
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 133 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2891#-NUHYyW15e7sjystjB7O:-NUHhZFWEzzylJMyVX4j:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2e217371973a188eb074599209e8bc41b57c51ba/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L133)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Same
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 15 of 15 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2891#-:-NUv9xKX3EG-htYGzBzE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
