### PR TITLE
VSCode: New README and made marketplace page finally acceptable

### LINKED ISSUE #3305: dev: Documentation for installing vs-code extension
image
I was confused for a bit as to what file was being referred to when installing the extension. I saw "from the directory of this file" but what confused as to what "this file" referred to. I wanted it to be explicit so others don't get confused the same way. I'll send a PR if it sounds reasonable.

### LINKED ISSUE #5616: Add git instructions to vscode plugin info
I was following the instructions posted at the below URL to install the Cairo plugin in VS Code, but kept getting an error when running the command "vsce package" that it couldn't locate package.json.  It took me a while to figure that that I had to run the following commands:

```
sudo npm install --global @vscode/vsce
git clone https://github.com/starkware-libs/cairo.git
cd cairo/vscode-cairo
npm install
vsce package
code --install-extension cairo1*.vsix
```

Note that I added the 2nd and 3rd lines which is missing in your instructions.  The is the URL I am referring to:

[https://marketplace.visualstudio.com/items?itemName=starkware.cairo1](https://marketplace.visualstudio.com/items?itemName=starkware.cairo1)

### PR DESCRIPTION
**Pull request by mkaput**
fix #3305
fix #5616

---

**Stack**:
- #5704
- #5703
- #5687 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5687)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5687)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)

___
*[`vscode-cairo/README.md` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5687#-Nz55IVW-ryGKCXv6rAZ:-Nz55IVW-ryGKCXv6rA_:b-xjoi2x) ([raw file](https://github.com/starkware-libs/cairo/blob/1d505b6d1bd7bbb6ce9688cb89d23284f62c78cc/vscode-cairo/README.md#L18)):*
> ```Markdown
> 
> ```
> sudo npm install --global @vscode/vsce
> ```

shouldn't we still have the local config for development somewhere?

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5687)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`vscode-cairo/README.md` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5687#-Nz55IVW-ryGKCXv6rAZ:-Nz56DaRE8wfCfBKDJ_7:b-mxsivb) ([raw file](https://github.com/starkware-libs/cairo/blob/1d505b6d1bd7bbb6ce9688cb89d23284f62c78cc/vscode-cairo/README.md#L18)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

shouldn't we still have the local config for development somewhere?
</blockquote></details>

Hmm, definitely not here because we don't want this information to be shown in the marketplace, as this confuses users (see #3305 and #5616)

Anyway, were you using these steps? Because I did not, and instead I've been running the extension via debugger all the time.

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5687#-:-Nz57Szv1_uMl8026BUX:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5687)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Pull request merged**
