### PR TITLE
LS: Cancel background tasks when terminating

### PR DESCRIPTION
**Pull request by mkaput**

### CODE REVIEW

**Comment by mkaput** [comment]
before:
before

after:
after

see how quicker we are terminating the process now

**Review by Draggu — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6609#-:-OBB1mtC8Ase2ckASNMP:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 297 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6609#-OBB1dWu-3VkyBOOhEtY:-OBB1dWu-3VkyBOOhEtZ:b-vrnv01) ([raw file](https://github.com/starkware-libs/cairo/blob/9b59928b37ad31ed5f31bde71d311d417ceecd1b/crates/cairo-lang-language-server/src/lib.rs#L297)):*
> ```XML
>             let result = Self::event_loop(&connection, scheduler);
> 
>             // Report a synthetic low durability write to the database to trigger cancellation
> ```

Redundant with code



_Code quote:_
```XML
Report a synthetic low durability write to the database
```

**Review by piotmag769 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6609#-:-OBBNEwf3TZTh2O-XV47:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @mkaput, and @orizi)

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6609)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 297 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6609#-OBB1dWu-3VkyBOOhEtY:-OBBSK_JEoYbZsvlaQMT:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/9b59928b37ad31ed5f31bde71d311d417ceecd1b/crates/cairo-lang-language-server/src/lib.rs#L297)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

Redundant with code
</blockquote></details>

Done

**Pull request merged**
