### PR TITLE
Added test for diagnostics of inline-inline modules...

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1464)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/defs/src/db.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1464#-NK7n19L8keMSuqht3qG:-NK7n19L8keMSuqht3qH:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/1ae20ccc9a3c2332992c895e6bb2be056cfdb0d1/crates/defs/src/db.rs#L148)):*
> ```XML
> }
> 
> /// Appends all the modules under the given module, including recursively.
> ```





_Suggestion:_
```XML
including nested modules
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/defs/src/db.rs` line 332 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1464#-NK7n9FwCVjjnsWOaOj7:-NK7n9FwCVjjnsWOaOj8:b-nvkbhc) ([raw file](https://github.com/starkware-libs/cairo/blob/1ae20ccc9a3c2332992c895e6bb2be056cfdb0d1/crates/defs/src/db.rs#L332)):*
> ```XML
> 
> /// Finds all the *direct* submodules of a module - both explicit (using the "mod x" syntax) and
> /// virtual submodules, generated by macro plugins. To get all the submodules recursively, use
> ```

Those are not returned



_Code quote:_
```XML
virtual submodules
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1464)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/semantic/src/db.rs` line 702 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1464#-NK7ni9MBX32N-20-5Tu:-NK7ni9MBX32N-20-5Tv:b-34fx5r) ([raw file](https://github.com/starkware-libs/cairo/blob/1ae20ccc9a3c2332992c895e6bb2be056cfdb0d1/crates/semantic/src/db.rs#L702)):*
> ```XML
>     for submodule_id in submodules.iter() {
>         diagnostics.extend(db.module_semantic_diagnostics(*submodule_id).unwrap());
>     }
> ```

Should the file not found error be here?
https://github.com/starkware-libs/cairo/blob/2cd21aa447ffd1f5d75356b2a391aa632c902023/crates/compiler/src/diagnostics.rs#L31

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1464)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/semantic/src/db.rs` line 694 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1464#-NK7oYuvB1uWtT3nHn3_:-NK7oYuvB1uWtT3nHn3a:b1y219x) ([raw file](https://github.com/starkware-libs/cairo/blob/1ae20ccc9a3c2332992c895e6bb2be056cfdb0d1/crates/semantic/src/db.rs#L694)):*
> ```XML
> 
> /// Gets the diagnostics for all the modules (including nested) in the given crate.
> pub fn get_crate_semantic_diagnostics(
> ```

there is some overlap with
https://github.com/starkware-libs/cairo/blob/2cd21aa447ffd1f5d75356b2a391aa632c902023/crates/compiler/src/diagnostics.rs#L17



_Code quote:_
```XML
get_crate_semantic_diagnostics
```

**Review by bbrandtom — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1464#-:-NK8FOrH7HEg_1fDBvMz:bg7igkv)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1464)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/defs/src/db.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1464#-NK7n19L8keMSuqht3qG:-NK8B0WxBD4WlJyck2lY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1ae20ccc9a3c2332992c895e6bb2be056cfdb0d1/crates/defs/src/db.rs#L148)):*
> ```XML
> }
> 
> /// Appends all the modules under the given module, including recursively.
> ```

Done.
___
*[`crates/defs/src/db.rs` line 332 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1464#-NK7n9FwCVjjnsWOaOj7:-NK8Fw7d0wtlExtSTich:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1ae20ccc9a3c2332992c895e6bb2be056cfdb0d1/crates/defs/src/db.rs#L332)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Those are not returned
</blockquote></details>

Done.



_Code quote:_
```XML
virtual submodules
```
___
*[`crates/semantic/src/db.rs` line 694 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1464#-NK7oYuvB1uWtT3nHn3_:-NK8Ffpk3jKBg6vicqg_:b-6nfpm1) ([raw file](https://github.com/starkware-libs/cairo/blob/1ae20ccc9a3c2332992c895e6bb2be056cfdb0d1/crates/semantic/src/db.rs#L694)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

there is some overlap with
https://github.com/starkware-libs/cairo/blob/2cd21aa447ffd1f5d75356b2a391aa632c902023/crates/compiler/src/diagnostics.rs#L17
</blockquote></details>

Moved to test_utils
___
*[`crates/semantic/src/db.rs` line 702 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1464#-NK7ni9MBX32N-20-5Tu:-NK8Fb9n0G8DZLaxpDZI:b-b8ppoh) ([raw file](https://github.com/starkware-libs/cairo/blob/1ae20ccc9a3c2332992c895e6bb2be056cfdb0d1/crates/semantic/src/db.rs#L702)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Should the file not found error be here?
https://github.com/starkware-libs/cairo/blob/2cd21aa447ffd1f5d75356b2a391aa632c902023/crates/compiler/src/diagnostics.rs#L31
</blockquote></details>

As discussed - it's not semantic

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1464#-:-NK8HklSEUa4pYQFBORq:bnfp4nl)* status: 3 of 5 files reviewed, all discussions resolved

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 1 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1464#-:-NK8f6m16JS2M-aJIRI-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1464)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 2 of 4 files at r3, 1 of 2 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1464)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
