### PR TITLE
VSCode: Extract standalone CairoLS logic to `StandaloneLS` class

### PR DESCRIPTION
**Pull request by mkaput**
**Stack**:
- #5015
- #5014
- #5013 ⬅
- #5012
- #4976
- #4975
- #4974
- #4973

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5013)

### CODE REVIEW

**Review by Arcticae — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5013)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`vscode-cairo/src/cairols.ts` line 171 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5013#-Nq8qkuc0dTjhq2iA5u9:-Nq8qkuc0dTjhq2iA5uA:babpchz) ([raw file](https://github.com/starkware-libs/cairo/blob/b6da7263b8f5b3ea9e2f397790a6dbb53b89059c/vscode-cairo/src/cairols.ts#L171)):*
> ```XML
>       serverExecutable = ls.languageServerExecutable();
>     } catch (e) {
>       ctx.log.error(`${e}`);
> ```

Why is this error caught and logged here, and below other one is thrown? 
___
*[`vscode-cairo/src/standalonels.ts` line 26 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5013#-Nq8q_H-B9z1IZhdFe_V:-Nq8q_H-B9z1IZhdFe_W:b2u8id9) ([raw file](https://github.com/starkware-libs/cairo/blob/b6da7263b8f5b3ea9e2f397790a6dbb53b89059c/vscode-cairo/src/standalonels.ts#L26)):*
> ```XML
>       // TODO(mkaput): Config should probably be scoped to workspace folder.
>       // Check config for language server path.
>       let configPath = ctx.config.get("languageServerPath");
> ```

I kind of dislike the triple check on the same variable, readability suffers from this. Can't this be re-written with some logical ops instead to make code more shallow?
___
*[`vscode-cairo/src/standalonels.ts` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5013#-Nq8qU367Yj218Fs-4Qh:-Nq8qU367Yj218Fs-4Qi:b3cwtp2) ([raw file](https://github.com/starkware-libs/cairo/blob/b6da7263b8f5b3ea9e2f397790a6dbb53b89059c/vscode-cairo/src/standalonels.ts#L32)):*
> ```XML
>           ctx.log.debug(`using CairoLS from config: ${configPath}`);
>           return configPath;
>         } else {
> ```

Unnecessary `else`
___
*[`vscode-cairo/src/standalonels.ts` line 63 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5013#-Nq8q4Ik9I_iOJ3ZJpkG:-Nq8q4Ik9I_iOJ3ZJpkH:b-q7u3cu) ([raw file](https://github.com/starkware-libs/cairo/blob/b6da7263b8f5b3ea9e2f397790a6dbb53b89059c/vscode-cairo/src/standalonels.ts#L63)):*
> ```XML
>     const cwd = this.workspaceFolder?.uri.fsPath;
>     if (cwd != undefined) {
>       exec.options.cwd = cwd;
> ```

Instead of condition and nested assignment



_Suggestion:_
```XML
 exec.options.cwd ||= cwd
```
___
*[`vscode-cairo/src/standalonels.ts` line 95 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5013#-Nq8pq1pDQtqRXX2JiL2:-Nq8pq1pDQtqRXX2JiL3:b-pcb7an) ([raw file](https://github.com/starkware-libs/cairo/blob/b6da7263b8f5b3ea9e2f397790a6dbb53b89059c/vscode-cairo/src/standalonels.ts#L95)):*
> ```XML
>     }
> 
>     root = path.basename(root);
> ```

won't this crash if it's sufficiently high in the folder tree?

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5013)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @Arcticae and @orizi)

___
*[`vscode-cairo/src/cairols.ts` line 171 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5013#-Nq8qkuc0dTjhq2iA5u9:-NqRfnD6-1OcCwIppQkJ:b-e236mp) ([raw file](https://github.com/starkware-libs/cairo/blob/e954503c4b53cc78fca8b9645959b59222b20ab5/vscode-cairo/src/cairols.ts#L171)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

Why is this error caught and logged here, and below other one is thrown?
</blockquote></details>

I agree that this ended up being convoluted, but I think the problem is more systematic, and it'd be better to solve it in a separate PR which I'll push after this stack is merged (to reduce CI overhead) Wdyt?
___
*[`vscode-cairo/src/standalonels.ts` line 26 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5013#-Nq8q_H-B9z1IZhdFe_V:-NqRXvm-9ijfUPbnUYMw:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e954503c4b53cc78fca8b9645959b59222b20ab5/vscode-cairo/src/standalonels.ts#L26)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

I kind of dislike the triple check on the same variable, readability suffers from this. Can't this be re-written with some logical ops instead to make code more shallow?
</blockquote></details>

Done.
___
*[`vscode-cairo/src/standalonels.ts` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5013#-Nq8qU367Yj218Fs-4Qh:-NqRY5AK5aqatsdW9fVb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e954503c4b53cc78fca8b9645959b59222b20ab5/vscode-cairo/src/standalonels.ts#L32)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

Unnecessary `else`
</blockquote></details>

Done.
___
*[`vscode-cairo/src/standalonels.ts` line 63 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5013#-Nq8q4Ik9I_iOJ3ZJpkG:-NqRZGpf8lCV1pHfOfgw:b-6ji19f) ([raw file](https://github.com/starkware-libs/cairo/blob/e954503c4b53cc78fca8b9645959b59222b20ab5/vscode-cairo/src/standalonels.ts#L63)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

Instead of condition and nested assignment
</blockquote></details>

`exec.options.cwd?: string` so I cannot assign `undefined` to it :/ hence this unstylish code
___
*[`vscode-cairo/src/standalonels.ts` line 95 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5013#-Nq8pq1pDQtqRXX2JiL2:-NqRZSR8D4RYsEa86n1L:bgpavu5) ([raw file](https://github.com/starkware-libs/cairo/blob/e954503c4b53cc78fca8b9645959b59222b20ab5/vscode-cairo/src/standalonels.ts#L95)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

won't this crash if it's sufficiently high in the folder tree?
</blockquote></details>

it will, but this logic is only used by Cairo devs so we can always quickfix it if needed and nobody had a need for it yet

**Review by Arcticae — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5013)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`vscode-cairo/src/cairols.ts` line 171 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5013#-Nq8qkuc0dTjhq2iA5u9:-NqRiNHH84rbVcfDoP7r:b-p4qfje) ([raw file](https://github.com/starkware-libs/cairo/blob/e954503c4b53cc78fca8b9645959b59222b20ab5/vscode-cairo/src/cairols.ts#L171)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I agree that this ended up being convoluted, but I think the problem is more systematic, and it'd be better to solve it in a separate PR which I'll push after this stack is merged (to reduce CI overhead) Wdyt?
</blockquote></details>

i'm ok with this approach :thumbsup:

**Review by Arcticae — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5013#-:-NqRjY4n8W0aoWtcEcUF:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5013#-:-NqWxZ9k8GUHkYU44LUc:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Pull request merged**
