### PR TITLE
Improved CI to only run affected tests

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2858)

### CODE REVIEW

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2858)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @mkaput)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2858#-NTIFjBT0vCBBFLGlZBc:-NTIJ8VR5VbU9LpB99M_:b-wljvol) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

How does this handle situation where change in syntax breaks semantic model tests?
</blockquote></details>

There are dependencies defined (currently manually, in the future hopefully directly through Cargo.toml).
The semantic crate tests are configured to run if one of the dependent crates changes, e.g. syntax.
See in detect_job_deps:
```
  add_job_to_run(
    "semantic",
    modifiedDeps,
    [
      "debug",
      "defs",
      "diagnostics",
      "filesystem",
      "parser",
      "plugins",
      "proc-macros",
      "syntax",
      "test-utils",
      "utils",
    ],
    jobsToRun
  );
```

___

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2858)* status: 0 of 5 files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2858#-NTIFjBT0vCBBFLGlZBc:-NTIMUBi5ZlgpK6R0za7:b-vs1prh) (no related file):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

There are dependencies defined (currently manually, in the future hopefully directly through Cargo.toml).
The semantic crate tests are configured to run if one of the dependent crates changes, e.g. syntax.
See in detect_job_deps:
```
  add_job_to_run(
    "semantic",
    modifiedDeps,
    [
      "debug",
      "defs",
      "diagnostics",
      "filesystem",
      "parser",
      "plugins",
      "proc-macros",
      "syntax",
      "test-utils",
      "utils",
    ],
    jobsToRun
  );
```
</blockquote></details>

Looks good!

___

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2858)* status: 0 of 120 files reviewed, 1 unresolved discussion (waiting on @liorgold2, @orizi, and @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2858#-NTSwDdC86gmRVoBRrC4:-NTSwDdC86gmRVoBRrC5:b2kglz7) (no related file):*
Do we want a single job to build, and only then run tests on the resultin artifacts?

___

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2858)* status: 0 of 120 files reviewed, 1 unresolved discussion (waiting on @liorgold2, @orizi, and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2858#-NTSwDdC86gmRVoBRrC4:-NTT9-c8ALc8zazKJ10o:b-achhng) (no related file):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Do we want a single job to build, and only then run tests on the resultin artifacts?
</blockquote></details>

Is this a suggestion?
This is not what's done here. The single job only detects dependencies according to changed files. Then it runs "cargo test -p" for the dependent packages. No separation currently between build and test.

___

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2858)* status: 0 of 123 files reviewed, 2 unresolved discussions (waiting on @liorgold2, @orizi, and @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2858#-NUv6Q_8DqF0HKso4Chk:-NUv6Q_8DqF0HKso4Chl:b-3hf1tv) (no related file):*
I don't really like this, and I think @orizi and @liorgold2 don't either.
Let's wait with this.

___

**Pull request closed without merging**
