### PR TITLE
support for match out of order for enums

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4536)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4536)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1032 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4536#-NlNLOdk-GJ7SCMtGB2f:-NlNLOdk-GJ7SCMtGB2g:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/53bf8c7369ff962defd55b56c6942e53bd9b8ad0/crates/cairo-lang-lowering/src/lower/mod.rs#L1032)):*
> ```XML
>         })
>         .collect();
>     let variant_map = variant_map?;
> ```





_Suggestion:_
```XML
            Ok((enum_pattern.variant.clone(), (enum_pattern, arm_index)))
        })
        .collect::<Result<Vec<_>,_>>()?;
```
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1117 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4536#-NlNLahq9YMyDja03Q7X:-NlNLahq9YMyDja03Q7Y:bl2tflh) ([raw file](https://github.com/starkware-libs/cairo/blob/53bf8c7369ff962defd55b56c6942e53bd9b8ad0/crates/cairo-lang-lowering/src/lower/mod.rs#L1117)):*
> ```XML
>         ));
>     }
>     // Merge arm blocks.
> ```

is this exactly the same?
extract to function.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4536)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/test_data/match` line 485 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4536#-NlNLwOA62KEHvqa8BUD:-NlNLwOB3w8t8KOkChZY:b9b9676) ([raw file](https://github.com/starkware-libs/cairo/blob/53bf8c7369ff962defd55b56c6942e53bd9b8ad0/crates/cairo-lang-lowering/src/test_data/match#L485)):*
> ```
> //! > ==========================================================================
> 
> //! > Test out of order extern match arm.
> ```

is there a place testing non-diagnostics?
is it this file?



_Code quote:_
```
Test out of order extern match arm.
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4536)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1032 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4536#-NlNLOdk-GJ7SCMtGB2f:-NlNevsx77osgxW75NzY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/53bf8c7369ff962defd55b56c6942e53bd9b8ad0/crates/cairo-lang-lowering/src/lower/mod.rs#L1032)):*
> ```XML
>         })
>         .collect();
>     let variant_map = variant_map?;
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1117 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4536#-NlNLahq9YMyDja03Q7X:-NlNjDmyCUG6PjS7c58X:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/53bf8c7369ff962defd55b56c6942e53bd9b8ad0/crates/cairo-lang-lowering/src/lower/mod.rs#L1117)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is this exactly the same?
extract to function.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/test_data/match` line 485 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4536#-NlNLwOA62KEHvqa8BUD:-NlSMJoq7ZytaPOnN827:b-73xncr) ([raw file](https://github.com/starkware-libs/cairo/blob/53bf8c7369ff962defd55b56c6942e53bd9b8ad0/crates/cairo-lang-lowering/src/test_data/match#L485)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is there a place testing non-diagnostics?
is it this file?
</blockquote></details>

add number to differentiate the blocks

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4536)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 983 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4536#-NlSe_xN70vMiCT-cU-t:-NlSe_xN70vMiCT-cU-u:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5462204b7265c8035e7013a9be8ea8359ea4c8c1/crates/cairo-lang-lowering/src/lower/mod.rs#L983)):*
> ```XML
> }
> 
> // get an unordered map of variants to their corresponding arm index
> ```





_Suggestion:_
```XML
/// Returns a map from variants to their corresponding arm index.
```
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1011 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4536#-NlSera6Bq2Yy6F2kUtS:-NlSera6Bq2Yy6F2kUtT:b-6gcvea) ([raw file](https://github.com/starkware-libs/cairo/blob/5462204b7265c8035e7013a9be8ea8359ea4c8c1/crates/cairo-lang-lowering/src/lower/mod.rs#L1011)):*
> ```XML
>             Ok((enum_pattern.variant.clone(), (enum_pattern, arm_index)))
>         })
>         .collect::<Result<UnorderedHashMap<_, _>, _>>()
> ```

Is this required? (due to the function ret value)



_Suggestion:_
```XML
            Ok((enum_pattern.variant.clone(), (enum_pattern, arm_index)))
        })
        .collect()
```
___
*[`examples/fib.cairo` line 13 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4536#-NlSfCDsEqi3MmoWYkKJ:-NlSfCDsEqi3MmoWYkKK:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/5462204b7265c8035e7013a9be8ea8359ea4c8c1/examples/fib.cairo#L13)):*
> ```Cairo
>         A::One(_) => { 1 },
>     }
> }
> ```

remove



_Code quote:_
```Cairo
fn foo(a: A) -> felt252 {
    match a {
        A::Two(_) => { 2 },
        A::One(_) => { 1 },
    }
}
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4536)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 983 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4536#-NlSe_xN70vMiCT-cU-t:-NlSixtZ4dc6Xtzq_Ssd:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5462204b7265c8035e7013a9be8ea8359ea4c8c1/crates/cairo-lang-lowering/src/lower/mod.rs#L983)):*
> ```XML
> }
> 
> // get an unordered map of variants to their corresponding arm index
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1011 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4536#-NlSera6Bq2Yy6F2kUtS:-NlSiyI08JBkT5G2pvVP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5462204b7265c8035e7013a9be8ea8359ea4c8c1/crates/cairo-lang-lowering/src/lower/mod.rs#L1011)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Is this required? (due to the function ret value)
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4536#-:-NlTaIkIEbxpBdnam8_U:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4536)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
