### PR TITLE
Improve tests and fix bugs.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5765)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5765)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/casm_run/circuit.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5765#-O-0LOBtEl72EB9srszI:-O-0LOBtEl72EB9srszJ:b24jjcm) ([raw file](https://github.com/starkware-libs/cairo/blob/089214ac3cf8389cb65c0bc6498d53ec0912ced9/crates/cairo-lang-runner/src/casm_run/circuit.rs#L81)):*
> ```XML
>                         index,
>                         (res + &self.modulus - rhs).mod_floor(&self.modulus),
>                     );
> ```

Before this change, I got:

"Cannot subtract b from a because b is larger than a."



_Code quote:_
```XML
                    self.write_addmod_value(
                        index,
                        (res + &self.modulus - rhs).mod_floor(&self.modulus),
                    );
```

**Review by orizi — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5765)* status: all files reviewed, 1 unresolved discussion

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5765#-:-O-0QQ319aWR2qWzP7T2:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5765)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
