### PR TITLE
Rename ec_state_finalize -> ec_state_try_finalize_nz.

### PR DESCRIPTION
**Pull request by liorgold2**
commit-id:c0411ece

---

**Stack**:
- #1950
- #1949
- #1948
- #1947 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1947#-:-NMt6X2gC_bzlwmhve5F:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1947#-NMt6OPz97oKGZvtWLKs):*
maybe?



_Suggestion:_
```
ec_state_try_finalize
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1947)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1947#-NMt6OPz97oKGZvtWLKs):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe?
</blockquote></details>

"try" doesn't fit here, since 0 is a valid result, it's not a failure. Happy to consider other suggestions :)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1947)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1947#-NMt6OPz97oKGZvtWLKs):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

"try" doesn't fit here, since 0 is a valid result, it's not a failure. Happy to consider other suggestions :)
</blockquote></details>

try_finalize_nz?



_Code quote (from corelib/ec.cairo):_
```Cairo
Option::<NonZeroEcPoint> nopanic;
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1947)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1947#-NMt6OPz97oKGZvtWLKs):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

try_finalize_nz?
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1947)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1947)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1947)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
