### PR TITLE
Added u256_div_mod_n

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3190)

### CODE REVIEW

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3190)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/integer.cairo` line 1224 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3190#-NVj2gT28hw22rAwGWpm:-NVjUOas5likPWUKiZKZ:be2x52j) ([raw file](https://github.com/starkware-libs/cairo/blob/64f7b1fd7f0d084a95cda2ae8c80686ef32c9193/corelib/src/integer.cairo#L1224)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i think this should be in math
</blockquote></details>

It's only for u256, as opposed to the others in math, currently.
If you still think it should be there, I can move it. LMK

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3190)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3190)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @orizi)

___
*[`corelib/src/integer.cairo` line 1224 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3190#-NVj2gT28hw22rAwGWpm:-NVjcKJ19Rc4HuOyARZ7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/64f7b1fd7f0d084a95cda2ae8c80686ef32c9193/corelib/src/integer.cairo#L1224)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I think it still is better (since if and when we'll make it work for others, it will be there anyway)
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3190)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
