### PR TITLE
tuples and fixedsizearray break line updated

### PR DESCRIPTION
**Pull request by dean-starkware**

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6611)* status: 0 of 35 files reviewed, 1 unresolved discussion (waiting on @dean-starkware and @gilbens-starkware)

___
*[`corelib/src/integer.cairo` line 1104 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6611#-OBK5tJ_1XEJc8uPXAqJ:-OBK5tJa7v19FvD1Wg8S:b-iprdsx) ([raw file](https://github.com/starkware-libs/cairo/blob/531b343b4ae8aeb9bd0d02ae7825349fdd0c5189/corelib/src/integer.cairo#L1104)):*
> ```Cairo
>     lhs: u512, rhs: NonZero<u256>,
> ) -> (
>     u512, u256, U128MulGuarantee, U128MulGuarantee, U128MulGuarantee, U128MulGuarantee,
> ```

the default configuration should probably not cause this.

**Review by dean-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6611)* status: 0 of 35 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`corelib/src/integer.cairo` line 1104 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6611#-OBK5tJ_1XEJc8uPXAqJ:-OBKD7KS-N1L2-dZq855:b-x2gx93) ([raw file](https://github.com/starkware-libs/cairo/blob/531b343b4ae8aeb9bd0d02ae7825349fdd0c5189/corelib/src/integer.cairo#L1104)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the default configuration should probably not cause this.
</blockquote></details>

The default is set to the following:
Tuples- Single line breakpoint.
Fixed size array- Single line breakpoint.

One can set the config to be "Line by line" instead.
Do you wish to set the default for the tuple case to be line by line?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6611)* status: 0 of 35 files reviewed, 1 unresolved discussion (waiting on @dean-starkware and @gilbens-starkware)

___
*[`corelib/src/integer.cairo` line 1104 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6611#-OBK5tJ_1XEJc8uPXAqJ:-OBKHyEPBybhNVjOWKQ3:bb7sa0c) ([raw file](https://github.com/starkware-libs/cairo/blob/531b343b4ae8aeb9bd0d02ae7825349fdd0c5189/corelib/src/integer.cairo#L1104)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

The default is set to the following:
Tuples- Single line breakpoint.
Fixed size array- Single line breakpoint.

One can set the config to be "Line by line" instead.
Do you wish to set the default for the tuple case to be line by line?
</blockquote></details>

yes.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6611)* status: 0 of 35 files reviewed, 2 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`corelib/src/metaprogramming.cairo` line 324 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6611#-OBKI5_E1TwgM36g421o:-OBKI5_E1TwgM36g421p:b-uwojvf) ([raw file](https://github.com/starkware-libs/cairo/blob/37d02cbc55939b0e65655f8b655f2e28ff5fb270/corelib/src/metaprogramming.cairo#L324)):*
> ```Cairo
>     fn reconstruct(head: T, rest: [T; 1]) -> [T; 2] nopanic {
>         let [e1] = rest;
>         [head,
> ```

opposite default as well.

**Review by dean-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6611)* status: 0 of 35 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`corelib/src/integer.cairo` line 1104 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6611#-OBK5tJ_1XEJc8uPXAqJ:-OBL5lNw7elbVSAoQJ0K:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/531b343b4ae8aeb9bd0d02ae7825349fdd0c5189/corelib/src/integer.cairo#L1104)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

yes.
</blockquote></details>

Done.
___
*[`corelib/src/metaprogramming.cairo` line 324 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6611#-OBKI5_E1TwgM36g421o:-OBL5kt-0-laeASBxRfr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/37d02cbc55939b0e65655f8b655f2e28ff5fb270/corelib/src/metaprogramming.cairo#L324)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

opposite default as well.
</blockquote></details>

Done.

**Review by dean-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6611)* status: 33 of 35 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-formatter/src/lib.rs` line 62 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6611#-OBL8zdOB9XtkRuHGxyJ:-OBLBNx_3nb-tJUbdFwN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/077634d102bc198f16bdf26c941a26078cc94a63/crates/cairo-lang-formatter/src/lib.rs#L62)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/bin/cairo-format/src/main.rs` line 52 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6611#-OBL8Qzl7S9qWhmUF9ks:-OBLAZRK8DTTIgwxDO4D:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/077634d102bc198f16bdf26c941a26078cc94a63/crates/bin/cairo-format/src/main.rs#L52)):*
> ```XML
>     /// each array item on a new line, or 'line-by-line' to keep items on a single line (if
>     /// space permits). Defaults to line-by-line.
>     #[arg(long, default_value_t = true)]
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6611#-:-OBLfbCHEbb4Jt5c8cZd:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
