### PR TITLE
Added deprecated attribute.

### PR DESCRIPTION
**Pull request by orizi**
Some refactoring of parsing unstable attr to support.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5383)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5383)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 435 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5383#-Nv717Eg1IziN5_phr_9:-Nv717Eh9WZRT-LwFVFc:bjsc42b) ([raw file](https://github.com/starkware-libs/cairo/blob/4e75931d96ad776b819c4b310c519ff42c0d4494/crates/cairo-lang-semantic/src/diagnostic.rs#L435)):*
> ```XML
>             SemanticDiagnosticKind::DeprecatedFeature { feature_name, note } => {
>                 format!(
>                     r#"Usage of deprecated feature `{feature_name}` with no `#[feature({feature_name})]` attribute.{}"#,
> ```

Long line



_Code quote:_
```XML
                format!(
                    r#"Usage of deprecated feature `{feature_name}` with no `#[feature({feature_name})]` attribute.{}"#,
```
___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 991 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5383#-Nv75WmlBTb0cStdHu36:-Nv75WmlBTb0cStdHu37:b-laigur) ([raw file](https://github.com/starkware-libs/cairo/blob/4e75931d96ad776b819c4b310c519ff42c0d4494/crates/cairo-lang-semantic/src/diagnostic.rs#L991)):*
> ```XML
>         note: Option<SmolStr>,
>     },
>     FeatureMarkerDiagnostic(FeatureMarkerDiagnostic),
> ```

Consider using `thiserror` with `#[from]` I think it does something similar.



_Code quote:_
```XML
FeatureMarkerDiagnostic(FeatureMarkerDiagnostic),
```
___
*[`crates/cairo-lang-syntax/src/attribute/consts.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5383#-Nv756N34l6lofCGowl9:-Nv756N34l6lofCGowlA:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/4e75931d96ad776b819c4b310c519ff42c0d4494/crates/cairo-lang-syntax/src/attribute/consts.rs#L14)):*
> ```XML
> pub const MUST_USE_ATTR: &str = "must_use";
> 
> /// An attribute to define an itema as unstable. Usage of these items will result in a warning,
> ```





_Suggestion:_
```XML
/ An attribute to define an item as unstable
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5383)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 991 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5383#-Nv75WmlBTb0cStdHu36:-Nv77_90ElTQeESzeJXT:b1qmnvb) ([raw file](https://github.com/starkware-libs/cairo/blob/4e75931d96ad776b819c4b310c519ff42c0d4494/crates/cairo-lang-semantic/src/diagnostic.rs#L991)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Consider using `thiserror` with `#[from]` I think it does something similar.
</blockquote></details>

diagnostics are not `thiserror` based.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5383#-:-Nv7APMWCg5p9fs-NqPY:bnfp4nl)* status: 5 of 6 files reviewed, all discussions resolved

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5383)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
