### PR TITLE
Refactored diagnostics mapping to be more generic.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #4451
- #4449
- #4444 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4444)

### CODE REVIEW

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4444)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/diagnostic.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4444#-Njqa_nJ0Nletz20Fc7O:-Njqa_nJ0Nletz20Fc7P:bulefj1) ([raw file](https://github.com/starkware-libs/cairo/blob/245beeac25fd7215acb7e3524de11167e9b71233/crates/cairo-lang-lowering/src/diagnostic.rs#L120)):*
> ```XML
> 
>     fn map_plugin_diagnostic(&self, _db: &Self::DbType, _location: DiagnosticLocation) -> Self {
>         todo!()
> ```

Add some explanation.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4444)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-lowering/src/diagnostic.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4444#-Njqa_nJ0Nletz20Fc7O:-Njqe-NE5BrSIkaVUcdm:b-mk2mqz) ([raw file](https://github.com/starkware-libs/cairo/blob/245beeac25fd7215acb7e3524de11167e9b71233/crates/cairo-lang-lowering/src/diagnostic.rs#L120)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Add some explanation.
</blockquote></details>

this is the following PR.

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4444)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4444#-:-Njqf6sp8pW-h1ZmjsUl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
