### PR TITLE
Add an ERC20 component example.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4091)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4091)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ArielElp, @gilbens-starkware, and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_erc20` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4091#-NehUk034pn8nJ-v3I3J:-NehUk034pn8nJ-v3I3K:bnopz24) ([raw file](https://github.com/starkware-libs/cairo/blob/b1fe8bb37e890263554cdd817633d1fc08fcd2e7/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_erc20#L28)):*
> ```
> }
> 
> trait ERC20HelperTrait<TCS> {
> ```

any reason for this to be out of module?

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4091)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @ArielElp, @orizi, and @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4091#-Nej4BhXA9DwGOkAGNzq:-Nej4BhYDp4BzEe2LoBO:b-tmwjk4) (no related file):*
Change target

___

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 8 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4091)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, and @yuvalsw)

___
*[`crates/cairo-lang-starknet/test_data/with_erc20.cairo` line 20 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4091#-NekoDTU3lE5c-1LJ-2N:-NekoDTU3lE5c-1LJ-2O:boz8jze) ([raw file](https://github.com/starkware-libs/cairo/blob/9e94a4f3d102a8cab22a94d3cc85dbd90de72f8c/crates/cairo-lang-starknet/test_data/with_erc20.cairo#L20)):*
> ```Cairo
> }
> 
> trait ERC20HelperTrait<TCS> {
> ```

does it make any sense for this to be out of the component?

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4091)* status: 3 of 10 files reviewed, 2 unresolved discussions (waiting on @ArielElp, @orizi, and @yuvalsw)

___
*[`crates/cairo-lang-starknet/test_data/with_erc20.cairo` line 20 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4091#-NekoDTU3lE5c-1LJ-2N:-NemA_ja0G0_eTUbdayU:b-fyo93) ([raw file](https://github.com/starkware-libs/cairo/blob/9e94a4f3d102a8cab22a94d3cc85dbd90de72f8c/crates/cairo-lang-starknet/test_data/with_erc20.cairo#L20)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

does it make any sense for this to be out of the component?
</blockquote></details>

No, no reason, moved it.

**Review by orizi — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4091#-:-NemCHx3E3xmLYT7OVvo:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_erc20` line 31 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4091#-NemCVwB3DCiJ-y0R2nl:-NemCVwB3DCiJ-y0R2nm:b-7u5lzm) ([raw file](https://github.com/starkware-libs/cairo/blob/cdf94c8471b7f41e640dfc250f255914b3b79ee7/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_erc20#L31)):*
> ```
> }
> 
> trait ERC20HelperTrait<TCS> {
> ```

it is still outside.

consider making it a `generate_trait` as it is just for an helper impl.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4091)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @ArielElp, @orizi, and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_erc20` line 31 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4091#-NemCVwB3DCiJ-y0R2nl:-NemQ2vcE1no0AgB2YYX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cdf94c8471b7f41e640dfc250f255914b3b79ee7/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_erc20#L31)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it is still outside.

consider making it a `generate_trait` as it is just for an helper impl.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4091#-:-NemTdw76Qgvio1QxmOB:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp and @yuvalsw)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4091)* status: 2 of 102 files reviewed, 5 unresolved discussions (waiting on @ArielElp, @orizi, and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_erc20` line 68 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4091#-NemfshKBNrSVyy0Gher:-NerQmHY192t1WfHNtGl:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0548e1be624628f4ba25260830b1ec548f25d1bb/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_erc20#L68)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I think currently all functions inside should be marked external(v0), shouldn't they?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_erc20` line 240 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4091#-Nemhq_g5Mexw01OgEzC:-NerR5xZA_3mzWl0w70i:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0548e1be624628f4ba25260830b1ec548f25d1bb/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_erc20#L240)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

or Constructor{Impl, Trait}
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_erc20` line 244 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4091#-NemhnZv03CbY4TptgY_:-NerR6JIEJDQOux9JTi8:b6xv586) ([raw file](https://github.com/starkware-libs/cairo/blob/0548e1be624628f4ba25260830b1ec548f25d1bb/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_erc20#L244)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

why the underscores?
</blockquote></details>

We have it also in the regular ERC20 implementation, the open zeppelin's Solidity implementation of ERC20 also have it and I think it taken from there.
Question is do we want to use this convention to be somewhat similar to Solidity contracts?

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4091)* status: 2 of 102 files reviewed, 4 unresolved discussions (waiting on @ArielElp, @orizi, and @yuvalsw)

___
*[`crates/cairo-lang-starknet/test_data/with_erc20.contract_class.json` line 2266 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4091#-NemjZNP9ajfCEJhdjMv:-NerXUKs1NnQPir4m5Ia:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0548e1be624628f4ba25260830b1ec548f25d1bb/crates/cairo-lang-starknet/test_data/with_erc20.contract_class.json#L2266)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

you currently need the #[external(v0)] in the `embeddable_as` for the functions to show here.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 8 of 100 files at r7, 92 of 92 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4091)* status: all files reviewed, 4 unresolved discussions (waiting on @ArielElp and @yuvalsw)

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 8 of 100 files at r7, 92 of 92 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4091)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp and @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_erc20` line 244 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4091#-NemhnZv03CbY4TptgY_:-NermudZ52IuoZJioweH:b11z96c) ([raw file](https://github.com/starkware-libs/cairo/blob/0548e1be624628f4ba25260830b1ec548f25d1bb/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_erc20#L244)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

We have it also in the regular ERC20 implementation, the open zeppelin's Solidity implementation of ERC20 also have it and I think it taken from there.
Question is do we want to use this convention to be somewhat similar to Solidity contracts?
</blockquote></details>

Both I and Ori are OK with it not being like solidity. Seems like it came from an older version where there was a collision between these names and the module name. 
Make sure that when removing these, nothing changes in the ABI.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4091)* status: 99 of 102 files reviewed, 1 unresolved discussion (waiting on @ArielElp, @orizi, and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_erc20` line 244 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4091#-NemhnZv03CbY4TptgY_:-NertRwT7eSxKHzu01RJ:br1kl1x) ([raw file](https://github.com/starkware-libs/cairo/blob/0548e1be624628f4ba25260830b1ec548f25d1bb/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_erc20#L244)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I changed it in the ctor as well, nothing changed up to the names.

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4091)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp and @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
> Reviewed 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4091)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp)

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4091#-:-NerwcpZ5MX_Ss5_2ZPb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4091)* status: 98 of 102 files reviewed, 1 unresolved discussion (waiting on @ArielElp, @gilbens-starkware, and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_erc20` line 247 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4091#-Nes535E8lW1LpYQzHOO:-Nes535FA8C2vp94DVfl:b163czm) ([raw file](https://github.com/starkware-libs/cairo/blob/24cd6a40e1dedec0d120b586a02a3d99e60cb89b/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_erc20#L247)):*
> ```
>     #[embed(v0)]
>     #[generate_trait]
>     impl CtorImpl of CtorTrait {
> ```

why remove this? in reality we want this - it is just that it would be in `#[abi(embed_v0)]`



_Code quote:_
```
    #[embed(v0)]
    #[generate_trait]
    impl CtorImpl of CtorTrait {
```

**Review by orizi — APPROVED** [review]
> Reviewed 4 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4091)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_erc20` line 247 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4091#-Nes535E8lW1LpYQzHOO:-NesqBIPEy-mCyYCb8L9:b-op3wid) ([raw file](https://github.com/starkware-libs/cairo/blob/24cd6a40e1dedec0d120b586a02a3d99e60cb89b/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_erc20#L247)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Because `#[abi(embed_v0)]` now forbids per item attrs, so I had to change it to `#[abi(per_item)]` which seemed weird for just one item.
Anyway, changed it back.
</blockquote></details>

We want to discourage free function based declarations - so we want an impl in our examples always.

**Pull request merged**
