### PR TITLE
Avoid using `shift_remove`.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
Keep moved variables in VarState::Removed instead.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4234)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4234)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 238 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4234#-NgJBhRx15KBFbhe5_jF:-NgJBhRx15KBFbhe5_jG:bag3wll) ([raw file](https://github.com/starkware-libs/cairo/blob/270cb98495ea4d72c5fbdbdf2ed500040250d1f3/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L238)):*
> ```XML
>                 unreachable!("Unknown state for variable `{arg}`.")
>             }
>         };
> ```

extract to func.



_Code quote:_
```XML
        let var_state = match state.variables.entry(arg.clone()) {
            indexmap::map::Entry::Occupied(mut e) => {
                std::mem::replace(e.get_mut(), VarState::Moved)
            }
            indexmap::map::Entry::Vacant(_) => {
                unreachable!("Unknown state for variable `{arg}`.")
            }
        };
```
___
*[`crates/cairo-lang-sierra-generator/src/store_variables/state.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4234#-NgJBmdX0Jxl09cVpeJO:-NgJBmdX0Jxl09cVpeJP:bbjt5g1) ([raw file](https://github.com/starkware-libs/cairo/blob/270cb98495ea4d72c5fbdbdf2ed500040250d1f3/crates/cairo-lang-sierra-generator/src/store_variables/state.rs#L42)):*
> ```XML
>     LocalVar,
>     /// The variable was previously moved and may not be used.
>     Moved,
> ```

maybe just "Removed" as this is about marking the element as not actually in the set.
also add the "why" this exists to the doc here.



_Code quote:_
```XML
    /// The variable was previously moved and may not be used.
    Moved,
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/store_variables/state.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4234#-NgJBmdX0Jxl09cVpeJO:-NgJCm_6BDIf7sRoiMlN:bnxozfp) ([raw file](https://github.com/starkware-libs/cairo/blob/270cb98495ea4d72c5fbdbdf2ed500040250d1f3/crates/cairo-lang-sierra-generator/src/store_variables/state.rs#L42)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe just "Removed" as this is about marking the element as not actually in the set.
also add the "why" this exists to the doc here.
</blockquote></details>

Moved is consistent with the borrow checker.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4234)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/state.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4234#-NgJBmdX0Jxl09cVpeJO:-NgJDKkJC6bY3-oCLh5h:b7z2xj6) ([raw file](https://github.com/starkware-libs/cairo/blob/270cb98495ea4d72c5fbdbdf2ed500040250d1f3/crates/cairo-lang-sierra-generator/src/store_variables/state.rs#L42)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Moved is consistent with the borrow checker.
</blockquote></details>

moved is just any usage - your usage was specific removal from the map.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4234)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 238 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4234#-NgJBhRx15KBFbhe5_jF:-NgJGiWF7N3yX3O9tbkl:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/270cb98495ea4d72c5fbdbdf2ed500040250d1f3/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L238)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

extract to func.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/store_variables/state.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4234#-NgJBmdX0Jxl09cVpeJO:-NgJGj748rPteKKj_HiP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/270cb98495ea4d72c5fbdbdf2ed500040250d1f3/crates/cairo-lang-sierra-generator/src/store_variables/state.rs#L42)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

moved is just any usage - your usage was specific removal from the map.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4234#-:-NgJGxFj5e1iNKRrQgfn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4234)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4234)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4234)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
