### PR TITLE
Add stable_location various ids.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3371)

### CODE REVIEW

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3371#-:-NXjZvtX4txAZtf94a6H:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-defs/src/ids.rs` line 130 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3371#-NXjYk9mEAkvpDh8enJq:-NXjYk9mEAkvpDh8enJr:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/65a84f36292c903407e1e97b5e8057fd125b0c36/crates/cairo-lang-defs/src/ids.rs#L130)):*
> ```XML
>             fn stable_location(&self, db: &dyn DefsGroup) -> StableLocation {
>                 let long_id = db.$lookup(*self);
>                 StableLocation {module_file_id : long_id.0, stable_ptr: long_id.1.untyped()}
> ```





_Suggestion:_
```XML
                let (module_file_id, stable_ptr) = db.$lookup(*self);
                StableLocation { module_file_id, stable_ptr: stable_ptr.untyped() }
```
___
*[`crates/cairo-lang-lowering/src/ids.rs` line 189 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3371#-NXjZUOsC2-rlZRExA8Y:-NXjZUOsC2-rlZRExA8Z:b-pb44rm) ([raw file](https://github.com/starkware-libs/cairo/blob/65a84f36292c903407e1e97b5e8057fd125b0c36/crates/cairo-lang-lowering/src/ids.rs#L189)):*
> ```XML
>     }
>     pub fn stable_location(&self, db: &dyn LoweringGroup) -> StableLocation {
>         let semantic_db = db.upcast();
> ```

inline
___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 246 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3371#-NXjZgmi0xh-cBOwXzip:-NXjZgmi0xh-cBOwXziq:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/65a84f36292c903407e1e97b5e8057fd125b0c36/crates/cairo-lang-semantic/src/items/functions.rs#L246)):*
> ```XML
>         match self {
>             GenericFunctionWithBodyId::Free(free) => free.stable_location(db.upcast()),
>             GenericFunctionWithBodyId::Impl(imp) => imp.function.stable_location(db.upcast()),
> ```





_Suggestion:_
```XML
            GenericFunctionWithBodyId::Free(free_function) => free_function.stable_location(db.upcast()),
            GenericFunctionWithBodyId::Impl(impl_function) => impl_function.function.stable_location(db.upcast()),
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/ids.rs` line 189 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3371#-NXjZUOsC2-rlZRExA8Y:-NXjahAC0pHgDJg4Ia1x:b6axlkx) ([raw file](https://github.com/starkware-libs/cairo/blob/65a84f36292c903407e1e97b5e8057fd125b0c36/crates/cairo-lang-lowering/src/ids.rs#L189)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

inline
</blockquote></details>

It is used twice.

what is the heuristic for deciding?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3371)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 246 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3371#-NXjZgmi0xh-cBOwXzip:-NXjepBOCPKpHzvAEtuL:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/65a84f36292c903407e1e97b5e8057fd125b0c36/crates/cairo-lang-semantic/src/items/functions.rs#L246)):*
> ```XML
>         match self {
>             GenericFunctionWithBodyId::Free(free) => free.stable_location(db.upcast()),
>             GenericFunctionWithBodyId::Impl(imp) => imp.function.stable_location(db.upcast()),
> ```

done.

**Review by yuvalsw — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3371)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-defs/src/ids.rs` line 130 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3371#-NXjiLh_-P520LgHWaGa:-NXjiLh_-P520LgHWaGb:bclu6l0) ([raw file](https://github.com/starkware-libs/cairo/blob/e833324c87fea48a1f5c5129fdaeac778b015216/crates/cairo-lang-defs/src/ids.rs#L130)):*
> ```XML
>             fn stable_location(&self, db: &dyn DefsGroup) -> StableLocation {
>                 let $long_id(module_file_id, stable_ptr) = db.$lookup(*self);
>                 StableLocation {module_file_id, stable_ptr: stable_ptr.untyped()}
> ```

Please fix spaces in the followup PR (as this is already in queue)



_Suggestion:_
```XML
{ module_file_id, stable_ptr: stable_ptr.untyped() }
```
___
*[`crates/cairo-lang-lowering/src/ids.rs` line 189 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3371#-NXjZUOsC2-rlZRExA8Y:-NXji6vCDhNWH5rLP1HU:b-s68jjr) ([raw file](https://github.com/starkware-libs/cairo/blob/65a84f36292c903407e1e97b5e8057fd125b0c36/crates/cairo-lang-lowering/src/ids.rs#L189)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

It is used twice.

what is the heuristic for deciding?
</blockquote></details>

it's used once - the 2 uses are in different arms

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/ids.rs` line 189 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3371#-NXjZUOsC2-rlZRExA8Y:-NXjinnn1PP7aI6JZKh9:b-k8av5e) ([raw file](https://github.com/starkware-libs/cairo/blob/65a84f36292c903407e1e97b5e8057fd125b0c36/crates/cairo-lang-lowering/src/ids.rs#L189)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

it's used once - the 2 uses are in different arms
</blockquote></details>

why does it matter that the usage is is different arms?

**Pull request merged**
