### PR TITLE
LS: Proc macro disable option in config

### PR DESCRIPTION
**Pull request by Draggu**

### CODE REVIEW

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6706)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, and @orizi)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6706#-OCCaWztA6cUyiHW3lBT:-OCCaWztA6cUyiHW3lBU:bpc0gvv) (no related file):*
where is `package.json` stuff ?
___
*[`crates/cairo-lang-language-server/src/config.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6706#-OCCajHo2-9VbVR2b1yZ:-OCCajHo2-9VbVR2b1y_:bb7t1qr) ([raw file](https://github.com/starkware-libs/cairo/blob/9af0f399348088a2f8958d25824140099eb17319/crates/cairo-lang-language-server/src/config.rs#L50)):*
> ```XML
>     /// - `None`: Temporarily behaves like `false` until the configuration is loaded from the
>     ///   client. This prevents the server from starting prematurely.
>     pub disable_proc_macros: Option<bool>,
> ```

you can remove this negation and it'll be functionally equivalent.
also, you unwrap that option and assume default value here (`false` for now). this is what also Piotr M suggested anyhow



_Suggestion:_
```XML
    pub enable_proc_macros: bool,
```
___
*[`crates/cairo-lang-language-server/src/config.rs` line 109 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6706#-OCCbhzf1gCF8JogBZSj:-OCCbhzf1gCF8JogBZSk:b-koz6j5) ([raw file](https://github.com/starkware-libs/cairo/blob/9af0f399348088a2f8958d25824140099eb17319/crates/cairo-lang-language-server/src/config.rs#L109)):*
> ```XML
>                 debug!("reloaded configuration: {:#?}", state.config);
> 
>                 state.proc_macro_controller.initialize_once(&mut state.db, &state.config);
> ```

I would rather make this a post-sync-hook than hardwire it here, wdyt?

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6706)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, and @orizi)

___
*[`crates/cairo-lang-language-server/src/config.rs` line 109 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6706#-OCCbhzf1gCF8JogBZSj:-OCD9eGDDgmMQXe7xaRc:buxbq2o) ([raw file](https://github.com/starkware-libs/cairo/blob/9af0f399348088a2f8958d25824140099eb17319/crates/cairo-lang-language-server/src/config.rs#L109)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I would rather make this a post-sync-hook than hardwire it here, wdyt?
</blockquote></details>

@Arcticae requested otherwise (and imo it's right, otherwise you have to keep the `Option<bool>`, you have weird post syscall hook, imo it's bad

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6706)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, and @orizi)

___
*[`crates/cairo-lang-language-server/src/config.rs` line 109 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6706#-OCCbhzf1gCF8JogBZSj:-OCDPR2A-4nKlvzx04oe:b-3qau1) ([raw file](https://github.com/starkware-libs/cairo/blob/9af0f399348088a2f8958d25824140099eb17319/crates/cairo-lang-language-server/src/config.rs#L109)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

@Arcticae requested otherwise (and imo it's right, otherwise you have to keep the `Option<bool>`, you have weird post syscall hook, imo it's bad
</blockquote></details>

hmm so maybe ProcMacroController should have a `on_config_change` function and call initialize from it?

**Review by Draggu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6706)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @Arcticae, @integraledelebesgue, @mkaput, @orizi, and @piotmag769)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6706#-OCCaWztA6cUyiHW3lBT:-OCDwEBH1idFcOfgsZoG:b-896fix) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

where is `package.json` stuff ?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/config.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6706#-OC94xfLCx4_DZjQmEsD:-OCDwF7UBdg20A_6MimZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9af0f399348088a2f8958d25824140099eb17319/crates/cairo-lang-language-server/src/config.rs#L48)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

No longer needed now
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/config.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6706#-OCCajHo2-9VbVR2b1yZ:-OCDwElW4hGm8jWqLnlc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9af0f399348088a2f8958d25824140099eb17319/crates/cairo-lang-language-server/src/config.rs#L50)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

you can remove this negation and it'll be functionally equivalent.
also, you unwrap that option and assume default value here (`false` for now). this is what also Piotr M suggested anyhow
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/config.rs` line 109 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6706#-OCCbhzf1gCF8JogBZSj:-OCDwFhW1wfiZbXLH2jk:bhx623o) ([raw file](https://github.com/starkware-libs/cairo/blob/9af0f399348088a2f8958d25824140099eb17319/crates/cairo-lang-language-server/src/config.rs#L109)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

hmm so maybe ProcMacroController should have a `on_config_change` function and call initialize from it?
</blockquote></details>

Can not see any benefit from it. simply calling initialize after config is loaded is enough and very clear what is happening.

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6706)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/config.rs` line 109 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6706#-OCCbhzf1gCF8JogBZSj:-OCIAHVw3agiynDZ5Jh9:bljgmvn) ([raw file](https://github.com/starkware-libs/cairo/blob/9af0f399348088a2f8958d25824140099eb17319/crates/cairo-lang-language-server/src/config.rs#L109)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

Can not see any benefit from it. simply calling initialize after config is loaded is enough and very clear what is happening.
</blockquote></details>

you miss one information though: by reading procmacrocontroller code you cannot learn that it is doing something in reaction to code changes
___
*[`vscode-cairo/package.json` line 148 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6706#-OCIAduuEpcp-o92nsS6:-OCIAduv3BwCbfYNsNft:ba40ddb) ([raw file](https://github.com/starkware-libs/cairo/blob/18476fa5f6d86f6f531339c830632faf84cf25a0/vscode-cairo/package.json#L148)):*
> ```JSON
>             "type": "boolean",
>             "default": true,
>             "description": "Resolve procedural macros with Scarb",
> ```

1. missing dot
2. too technical
3. I'm not sure info about Scarb is crucial here, esp. given that you cannot use procmacros outside Scarb projects



_Suggestion:_
```JSON
"description": "Enable support for procedural macros.",
```

**Review by Draggu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6706)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @integraledelebesgue, @mkaput, @orizi, and @piotmag769)

___
*[`vscode-cairo/package.json` line 148 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6706#-OCIAduuEpcp-o92nsS6:-OCY8AlDEUAyRuNmJCZS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/18476fa5f6d86f6f531339c830632faf84cf25a0/vscode-cairo/package.json#L148)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

1. missing dot
2. too technical
3. I'm not sure info about Scarb is crucial here, esp. given that you cannot use procmacros outside Scarb projects
</blockquote></details>

Done.

**Review by mkaput — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6706)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @integraledelebesgue, @orizi, and @piotmag769)

**Review by Draggu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6706)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @integraledelebesgue, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/config.rs` line 109 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6706#-OCCbhzf1gCF8JogBZSj:-OCZ6sc25MD2MNUSy6u0:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9af0f399348088a2f8958d25824140099eb17319/crates/cairo-lang-language-server/src/config.rs#L109)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

you miss one information though: by reading procmacrocontroller code you cannot learn that it is doing something in reaction to code changes
</blockquote></details>

Done.

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6706#-:-OCbokLJ-8auC7bKSG1y:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @integraledelebesgue, and @orizi)

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6706)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
