### PR TITLE
Renamed Starknet ABI attributes.

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4113)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 12 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4113)* status: 12 of 14 files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/abi.rs` line 660 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4113#-Ner6SVXBDPXLil9MzZ0:-Ner6SVXBDPXLil9MzZ1:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/1994d884461c783967415bfcbbf26529d54c63cb/crates/cairo-lang-starknet/src/abi.rs#L660)):*
> ```XML
> }
> 
> /// Checks whether the impl is marked with #[abi(embed)], or the old equivalent #[external].
> ```





_Suggestion:_
```XML
`#[abi(embed_v0)]`
```
___
*[`crates/cairo-lang-starknet/src/plugin/consts.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4113#-Ner5qJJBpPbh5cT4oGl:-Ner5qJJBpPbh5cT4oGm:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/1994d884461c783967415bfcbbf26529d54c63cb/crates/cairo-lang-starknet/src/plugin/consts.rs#L44)):*
> ```XML
> pub const ABI_ATTR: &str = "abi";
> pub const ABI_ATTR_PER_ITEM_ARG: &str = "per_item";
> pub const ABI_ATTR_EMBED_ARG: &str = "embed_v0";
> ```





_Suggestion:_
```XML
pub const ABI_ATTR_EMBED_V0_ARG: &str = "embed_v0";
```
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 441 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4113#-Ner5S59D6Orgy_kb_6o:-Ner5S59D6Orgy_kb_6p:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/1994d884461c783967415bfcbbf26529d54c63cb/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L441)):*
> ```XML
>     imp.has_attr_with_arg(db, ABI_ATTR, ABI_ATTR_EMBED_ARG)
>         || has_v0_attribute(db, diagnostics, imp, EXTERNAL_ATTR)
> }
> ```





_Suggestion:_
```XML
/// Checks whether the impl is marked with `#[abi(embed_v0)]`, or the old equivalent `#[external]`.
fn is_impl_abi_embed(
    db: &dyn SyntaxGroup,
    diagnostics: &mut Vec<PluginDiagnostic>,
    imp: &ast::ItemImpl,
) -> bool {
    imp.has_attr_with_arg(db, ABI_ATTR, ABI_ATTR_EMBED_ARG)
        || has_v0_attribute(db, diagnostics, imp, EXTERNAL_ATTR)
}
```
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 443 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4113#-Ner5ZvtBwaFPSCEeW-y:-Ner5ZvtBwaFPSCEeW-z:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/1994d884461c783967415bfcbbf26529d54c63cb/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L443)):*
> ```XML
> }
> 
> /// Checks whether the impl is marked with #[abi(per_item)].
> ```





_Suggestion:_
```XML
`#[abi(per_item)]`.
```

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4113)* status: all files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4113)* status: 10 of 14 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/abi.rs` line 660 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4113#-Ner6SVXBDPXLil9MzZ0:-NerKv6s7MR9b4N84NXU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1994d884461c783967415bfcbbf26529d54c63cb/crates/cairo-lang-starknet/src/abi.rs#L660)):*
> ```XML
> }
> 
> /// Checks whether the impl is marked with #[abi(embed)], or the old equivalent #[external].
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/consts.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4113#-Ner5qJJBpPbh5cT4oGl:-NerL1C24WTgmgsUffRI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1994d884461c783967415bfcbbf26529d54c63cb/crates/cairo-lang-starknet/src/plugin/consts.rs#L44)):*
> ```XML
> pub const ABI_ATTR: &str = "abi";
> pub const ABI_ATTR_PER_ITEM_ARG: &str = "per_item";
> pub const ABI_ATTR_EMBED_ARG: &str = "embed_v0";
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 441 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4113#-Ner5S59D6Orgy_kb_6o:-NerL41J889pKPyY_Vs4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1994d884461c783967415bfcbbf26529d54c63cb/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L441)):*
> ```XML
>     imp.has_attr_with_arg(db, ABI_ATTR, ABI_ATTR_EMBED_ARG)
>         || has_v0_attribute(db, diagnostics, imp, EXTERNAL_ATTR)
> }
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 443 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4113#-Ner5ZvtBwaFPSCEeW-y:-NerLHgNAHRYFlsY0Kf9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1994d884461c783967415bfcbbf26529d54c63cb/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L443)):*
> ```XML
> }
> 
> /// Checks whether the impl is marked with #[abi(per_item)].
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4113#-:-NerO4Xu4_t0gNV7JAFO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4113#-:-NerZhgDEqc9zS-IuGiZ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/mod.rs` line 74 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4113#-NerZcXA-eO2zvWtbAbr:-NerZcXB0Z0ekPoD70IE:bb7onj7) ([raw file](https://github.com/starkware-libs/cairo/blob/2c93213de2c320376aef2a399906e77afb61db7d/crates/cairo-lang-starknet/src/plugin/mod.rs#L74)):*
> ```XML
>             RAW_OUTPUT_ATTR.to_string(),
>             STORAGE_ATTR.to_string(),
>             ABI_ATTR.to_string(),
> ```

sort



_Code quote:_
```XML
            ABI_ATTR.to_string(),
```

**Pull request merged**
