### PR TITLE
Paths

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2705)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2691** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2691" target="_blank">Graphite</a> 
    * **PR #2692** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2692" target="_blank">Graphite</a> 
      * **PR #2705** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2705" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2705?utm_source=stack-comment).

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2705)* status: all files reviewed, 14 unresolved discussions (waiting on @spapinistarkware)

___
*[`docs/reference/src/path.adoc` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2705#-NS6Nxa9Bs60gkA4_hBW:-NS6Nxa9Bs60gkA4_hBX:b-8a6x37) ([raw file](https://github.com/starkware-libs/cairo/blob/4af699a8a0713dfe4d31fe7b120f3cc04cbd410c/docs/reference/src/path.adoc#L3)):*
> ```AsciiDoc
> = Path
> 
> A path is a sequence of one or more path segments logically separated by a namespace qualifier (::).
> ```

why *logically* separated?



_Code quote:_
```AsciiDoc
logically separated
```
___
*[`docs/reference/src/path.adoc` line 5 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2705#-NS6O9eC5kX9hB4z7j-h:-NS6O9eC5kX9hB4z7j-i:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/4af699a8a0713dfe4d31fe7b120f3cc04cbd410c/docs/reference/src/path.adoc#L5)):*
> ```AsciiDoc
> A path is a sequence of one or more path segments logically separated by a namespace qualifier (::).
> If a path consists of only one segment, it refers to either an link:items.adoc[item] or a
> link:variable.adoc[variable] in a local scope.
> ```

?



_Suggestion:_
```AsciiDoc
n the local
```
___
*[`docs/reference/src/path.adoc` line 8 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2705#-NS6OLa61XPLM3EyFs9I:-NS6OLa61XPLM3EyFs9J:b-v8zf4z) ([raw file](https://github.com/starkware-libs/cairo/blob/4af699a8a0713dfe4d31fe7b120f3cc04cbd410c/docs/reference/src/path.adoc#L8)):*
> ```AsciiDoc
> If a path has multiple segments, it always refers to an item.
> 
> Two examples of simple paths consisting of only identifier segments:
> ```

this term was not defined before.



_Code quote:_
```AsciiDoc
 identifier segments:
```
___
*[`docs/reference/src/path.adoc` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2705#-NS6OX3J3ERqw3Uh48ko:-NS6OX3J3ERqw3Uh48kp:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/4af699a8a0713dfe4d31fe7b120f3cc04cbd410c/docs/reference/src/path.adoc#L18)):*
> ```AsciiDoc
> 
> == Generic paths
> A Generic path is composed of segments which are identifiers, e.g. `x::y::z`. If refers to an item.
> ```





_Suggestion:_
```AsciiDoc
:z`. It refers to an
```
___
*[`docs/reference/src/path.adoc` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2705#-NS6OePgA3DpJaUUU6zv:-NS6OePgA3DpJaUUU6zw:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/4af699a8a0713dfe4d31fe7b120f3cc04cbd410c/docs/reference/src/path.adoc#L18)):*
> ```AsciiDoc
> 
> == Generic paths
> A Generic path is composed of segments which are identifiers, e.g. `x::y::z`. If refers to an item.
> ```





_Suggestion:_
```AsciiDoc
A generic 
```
___
*[`docs/reference/src/path.adoc` line 25 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2705#-NS6OrZw3AyRUiNrbc8A:-NS6OrZw3AyRUiNrbc8B:bohzs14) ([raw file](https://github.com/starkware-libs/cairo/blob/4af699a8a0713dfe4d31fe7b120f3cc04cbd410c/docs/reference/src/path.adoc#L25)):*
> ```AsciiDoc
> 
> == Path resolution
> The path is resolved by looking up the first identifier in the current scope, then recursively in
> ```

please stress that it doesn't look in parent modules (which might be though as parent scopes).



_Code quote:_
```AsciiDoc
r in the current scope, then recursively in
```
___
*[`docs/reference/src/path.adoc` line 27 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2705#-NS6PCVaAH9mObh6aDX0:-NS6PCVaAH9mObh6aDX1:borjscu) ([raw file](https://github.com/starkware-libs/cairo/blob/4af699a8a0713dfe4d31fe7b120f3cc04cbd410c/docs/reference/src/path.adoc#L27)):*
> ```AsciiDoc
> The path is resolved by looking up the first identifier in the current scope, then recursively in
> the parent scopes, and lastly in the core module. Then, the second identifier is looked up in the
> scope of the first identifier, and so on. If the path is not resolved, the compiler will report
> ```

Also add somewhere something like "if the first identifier represents a scope". If it's not, the path is invalid.
Also - what is a scope? here scope includes modules. In the previous sentence it's not.



_Suggestion:_
```AsciiDoc
scope represented by the first identifier
```
___
*[`docs/reference/src/path.adoc` line 27 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2705#-NS6PgZl8Rj0pMBZBMIf:-NS6PgZl8Rj0pMBZBMIg:bjc3n3c) ([raw file](https://github.com/starkware-libs/cairo/blob/4af699a8a0713dfe4d31fe7b120f3cc04cbd410c/docs/reference/src/path.adoc#L27)):*
> ```AsciiDoc
> The path is resolved by looking up the first identifier in the current scope, then recursively in
> the parent scopes, and lastly in the core module. Then, the second identifier is looked up in the
> scope of the first identifier, and so on. If the path is not resolved, the compiler will report
> ```

again - what does it mean?



_Code quote:_
```AsciiDoc
If the path is not resolved
```
___
*[`docs/reference/src/path.adoc` line 27 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2705#-NS6PlKd0jtS3GXy8a3F:-NS6PlKd0jtS3GXy8a3G:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/4af699a8a0713dfe4d31fe7b120f3cc04cbd410c/docs/reference/src/path.adoc#L27)):*
> ```AsciiDoc
> The path is resolved by looking up the first identifier in the current scope, then recursively in
> the parent scopes, and lastly in the core module. Then, the second identifier is looked up in the
> scope of the first identifier, and so on. If the path is not resolved, the compiler will report
> ```





_Suggestion:_
```AsciiDoc
scope of the first identifier, and so on. If the path is not resolved, the compiler reports
an error.
```
___
*[`docs/reference/src/path.adoc` line 31 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2705#-NS6U1H8EUHSPA6fSTx0:-NS6U1H8EUHSPA6fSTx1:baninpz) ([raw file](https://github.com/starkware-libs/cairo/blob/4af699a8a0713dfe4d31fe7b120f3cc04cbd410c/docs/reference/src/path.adoc#L31)):*
> ```AsciiDoc
> 
> == Concrete paths
> Concrete paths are composed of concrete segments, which may be followed by a
> ```

not defined



_Code quote:_
```AsciiDoc
 concrete segments
```
___
*[`docs/reference/src/path.adoc` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2705#-NS6PxiI5veX7g00M4z-:-NS6PxiI5veX7g00M4z0:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/4af699a8a0713dfe4d31fe7b120f3cc04cbd410c/docs/reference/src/path.adoc#L37)):*
> ```AsciiDoc
> IDENT[[::]<generic-args>]
> ```
> The additional `::` is mandatory where ambiguity would otherwise arise, such as expressions.
> ```





_Suggestion:_
```AsciiDoc
 such as in expression
```
___
*[`docs/reference/src/path.adoc` line 40 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2705#-NS6TWvb5GaARxdDEXpE:-NS6TWvb5GaARxdDEXpF:b-esqbgf) ([raw file](https://github.com/starkware-libs/cairo/blob/4af699a8a0713dfe4d31fe7b120f3cc04cbd410c/docs/reference/src/path.adoc#L40)):*
> ```AsciiDoc
> For example, `x::<u32>::y<u32>::z` is a concrete path.
> A concrete path refers to a concrete item (e.g. a function, type, etc.).
> When the generic arguments clause is not provided, or less generic arguments are provided than
> ```

elaborate

Also add an example.



_Code quote:_
```AsciiDoc
or less generic arguments
```
___
*[`docs/reference/src/path.adoc` line 41 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2705#-NS6TaJf0F1BGDYIUeBk:-NS6TaJf0F1BGDYIUeBl:b8dra7) ([raw file](https://github.com/starkware-libs/cairo/blob/4af699a8a0713dfe4d31fe7b120f3cc04cbd410c/docs/reference/src/path.adoc#L41)):*
> ```AsciiDoc
> A concrete path refers to a concrete item (e.g. a function, type, etc.).
> When the generic arguments clause is not provided, or less generic arguments are provided than
> the item expects, the compiler will link:inference.adoc[infer] the missing generic arguments.
> ```

or maybe "tries to infer"?



_Suggestion:_
```AsciiDoc
the compiler link:inference.adoc[infers] the missing generic ar
```
___
*[`docs/reference/src/path.adoc` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2705#-NS6ToMrBMyLuBWxXw9b:-NS6ToMrBMyLuBWxXw9c:bkljgoj) ([raw file](https://github.com/starkware-libs/cairo/blob/4af699a8a0713dfe4d31fe7b120f3cc04cbd410c/docs/reference/src/path.adoc#L46)):*
> ```AsciiDoc
> 
> * Expressions
> * Type / Trait expressions
> ```

not clear.



_Code quote:_
```AsciiDoc
* Expressions
* Type / Trait expressions
```

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2705)* status: all files reviewed, 10 unresolved discussions (waiting on @spapinistarkware)

___
*[`docs/reference/src/path.adoc` line 41 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2705#-NS6TaJf0F1BGDYIUeBk:-NSABa2R8EjXgiBv5S00:b1bsiwa) ([raw file](https://github.com/starkware-libs/cairo/blob/eb43ccac0cb9309a30194ff759434496b515b518/docs/reference/src/path.adoc#L41)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I think infers is simpler and better here.
</blockquote></details>

this was my suggestion...
___
*[`docs/reference/src/path.adoc` line 24 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2705#-NSA9Z0Z7aLD8jB4TbSy:-NSA9Z0Z7aLD8jB4TbSz:bj25nig) ([raw file](https://github.com/starkware-libs/cairo/blob/7bcd2da20d71764ae98529e2184ba4b565e81fe7/docs/reference/src/path.adoc#L24)):*
> ```AsciiDoc
> * Enum variant pattern.
> 
> == Path resolution
> ```

This is much better now, but I am still not sure it's perfect as the term scope is used twice with different meanings.

If you can come up with 2 different terms, define them and use them consistently - this would be best. If not - a clarification might be needed every time.
___
*[`docs/reference/src/path.adoc` line 25 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2705#-NSA8qD1AzJNzk3J1-8-:-NSA8qD1AzJNzk3J1-80:bdjgu5) ([raw file](https://github.com/starkware-libs/cairo/blob/7bcd2da20d71764ae98529e2184ba4b565e81fe7/docs/reference/src/path.adoc#L25)):*
> ```AsciiDoc
> 
> == Path resolution
> The path is resolved by looking up the first identifier in the current local scope. This include
> ```

maybe segment? Or identifier segment?



_Code quote:_
```AsciiDoc
identifier
```
___
*[`docs/reference/src/path.adoc` line 25 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2705#-NSA9IU703VJwOSSnUN3:-NSA9IU703VJwOSSnUN4:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7bcd2da20d71764ae98529e2184ba4b565e81fe7/docs/reference/src/path.adoc#L25)):*
> ```AsciiDoc
> 
> == Path resolution
> The path is resolved by looking up the first identifier in the current local scope. This include
> ```





_Suggestion:_
```AsciiDoc
The path is resolved by looking up the first identifier in the current local scope. This includes
local variables and generic parameters defined in containing items.
If not found, it is looked up in the current module and lastly in the core module.
Note that it is not looked up in the parent module.
```
___
*[`docs/reference/src/path.adoc` line 26 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2705#-NSAADR0D9UVXTXZwku2:-NSAADR0D9UVXTXZwku3:b-2l78aq) ([raw file](https://github.com/starkware-libs/cairo/blob/7bcd2da20d71764ae98529e2184ba4b565e81fe7/docs/reference/src/path.adoc#L26)):*
> ```AsciiDoc
> == Path resolution
> The path is resolved by looking up the first identifier in the current local scope. This include
> local variables and generic parameters defined in containing items.
> ```

also here - this is mostly clear, but can be interpreted as parent modules too, as they may be items (in the case of inline module).



_Code quote:_
```AsciiDoc
 containing items.
```
___
*[`docs/reference/src/path.adoc` line 52 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2705#-NSAC4_LE3hC6rTWw5ah:-NSAC4_LE3hC6rTWw5ai:b-m4gaui) ([raw file](https://github.com/starkware-libs/cairo/blob/7bcd2da20d71764ae98529e2184ba4b565e81fe7/docs/reference/src/path.adoc#L52)):*
> ```AsciiDoc
>     foo::<bool, bool>(false, true); // OK
>     foo::<bool, _>(false, true);    // OK, B is inferred to be bool
>     foo::<bool>(false, true);       // OK, B is inferred to be bool
> ```

suggestion - to cover a little bit more, change the second arg to be 3_u32 or similar.



_Code quote:_
```AsciiDoc
fn foo<A, B>(a: A, b: B) { ... }

fn main() {
    foo::<bool, bool>(false, true); // OK
    foo::<bool, _>(false, true);    // OK, B is inferred to be bool
    foo::<bool>(false, true);       // OK, B is inferred to be bool
    foo(false, true);               // OK, A and B are inferred to be bool
}
```
```
___
*[`docs/reference/src/path.adoc` line 59 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2705#-NSAEuiDAZGgREe25lOc:-NSAEuiDAZGgREe25lOd:blqowbh) ([raw file](https://github.com/starkware-libs/cairo/blob/7bcd2da20d71764ae98529e2184ba4b565e81fe7/docs/reference/src/path.adoc#L59)):*
> ```AsciiDoc
> Concrete paths are used at:
> 
> * Expressions - e.g. function calls.
> ```

link, or todo to add link.
Maybe also add a concrete example "like core::integer::u128_const<3>"
___
*[`docs/reference/src/path.adoc` line 62 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2705#-NSAIiXvBGj9caxRr5SR:-NSAIiXvBGj9caxRr5SS:b-umaczm) ([raw file](https://github.com/starkware-libs/cairo/blob/7bcd2da20d71764ae98529e2184ba4b565e81fe7/docs/reference/src/path.adoc#L62)):*
> ```AsciiDoc
> * Type expressions - e.g. link:let-statement.adoc[let] statement type clause, or generic type
>     arguments.
> * Trait expressions - e.g. Following the `of` keyword in an link:traits.adoc[impl] definition, or
> ```

I think you should add concrete  (preferably real) examples



_Code quote:_
```AsciiDoc
* Type expressions - e.g. link:let-statement.adoc[let] statement type clause, or generic type
    arguments.
* Trait expressions - e.g. Following the `of` keyword in an link:traits.adoc[impl] definition, or
    after the `:` in a link:generics.adoc[generic] impl argument.
```
___
*[`docs/reference/src/path.adoc` line 63 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2705#-NSAIdQm6tqM2ZctWGJd:-NSAIdQm6tqM2ZctWGJe:b7t6kme) ([raw file](https://github.com/starkware-libs/cairo/blob/7bcd2da20d71764ae98529e2184ba4b565e81fe7/docs/reference/src/path.adoc#L63)):*
> ```AsciiDoc
>     arguments.
> * Trait expressions - e.g. Following the `of` keyword in an link:traits.adoc[impl] definition, or
>     after the `:` in a link:generics.adoc[generic] impl argument.
> ```

I think we should call it "impl generic argument"



_Code quote:_
```AsciiDoc
a link:generics.adoc[generic] impl argument.
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2705)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

___
*[`docs/reference/src/path.adoc` line 24 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2705#-NSA9Z0Z7aLD8jB4TbSy:-NSB1NIv2cpanIdA_3Q3:b-6cjepr) ([raw file](https://github.com/starkware-libs/cairo/blob/7bcd2da20d71764ae98529e2184ba4b565e81fe7/docs/reference/src/path.adoc#L24)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

This is much better now, but I am still not sure it's perfect as the term scope is used twice with different meanings.

If you can come up with 2 different terms, define them and use them consistently - this would be best. If not - a clarification might be needed every time.
</blockquote></details>

I don't think the meaning are different
___
*[`docs/reference/src/path.adoc` line 26 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2705#-NSAADR0D9UVXTXZwku2:-NSB1hQ748EczzOlDDCO:bff58te) ([raw file](https://github.com/starkware-libs/cairo/blob/7bcd2da20d71764ae98529e2184ba4b565e81fe7/docs/reference/src/path.adoc#L26)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

also here - this is mostly clear, but can be interpreted as parent modules too, as they may be items (in the case of inline module).
</blockquote></details>

I think it's pretty clear, and adding more tet would only make it ahrder to read. You can suggest concrete changes.
___
*[`docs/reference/src/path.adoc` line 59 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2705#-NSAEuiDAZGgREe25lOc:-NSB2j550T6G-vHmNoEi:b4zh41i) ([raw file](https://github.com/starkware-libs/cairo/blob/7bcd2da20d71764ae98529e2184ba4b565e81fe7/docs/reference/src/path.adoc#L59)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

link, or todo to add link.
Maybe also add a concrete example "like core::integer::u128_const<3>"
</blockquote></details>

I don't want an example from corelib, since it will be coupled with it, and needed to be changed together.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2705)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`docs/reference/src/path.adoc` line 26 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2705#-NSAADR0D9UVXTXZwku2:-NSBVnH73KHRO753_PQB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7bcd2da20d71764ae98529e2184ba4b565e81fe7/docs/reference/src/path.adoc#L26)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

My suggestion:

The path is resolved by looking up the first segment identifier in the current local scope. This includes local variables and generic parameters defined in containing items, up to the module level. If not found, it is looked up in the core module. Note that it is not looked up in the containing modules. If the found item has a scope (e.g. a module or an enum) then the second identifier is looked up inside this scope, and so on.
</blockquote></details>

Done.
___
*[`docs/reference/src/path.adoc` line 68 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2705#-NSBOxwuCsZRExkSmD5q:-NSBWyIX9_-44FaGAuBC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/945c4183bba16dc4734ccdabde929bbea10809ea/docs/reference/src/path.adoc#L68)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

this is incomplete
</blockquote></details>

Done.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2705#-:-NSZytVUEVFtznlnrOh5:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`docs/reference/src/path.adoc` line 55 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2705#-NSZypAi9u2bbzdVRXSN:-NSZypAjBYY3qHGU5ZvM:b6i6dkk) ([raw file](https://github.com/starkware-libs/cairo/blob/53c7412c82c95b294e2f650d288aac8377d43ce8/docs/reference/src/path.adoc#L55)):*
> ```AsciiDoc
> ```rust
> foo::bar::<bool>() // Function call expression
> Option::<bool>::Some(true) // Enum variant expression
> ```

for consistency, please put those in bullets too



_Code quote:_
```AsciiDoc
foo::bar::<bool>() // Function call expression
Option::<bool>::Some(true) // Enum variant expression
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2705)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`docs/reference/src/path.adoc` line 55 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2705#-NSZypAi9u2bbzdVRXSN:-NS_-isBAiDQB0XNS53r:b16gm0n) ([raw file](https://github.com/starkware-libs/cairo/blob/53c7412c82c95b294e2f650d288aac8377d43ce8/docs/reference/src/path.adoc#L55)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

for consistency, please put those in bullets too
</blockquote></details>

It's not a new bullet, it's an example of the current bullet, like below

**Review by yuvalsw — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2705)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`docs/reference/src/path.adoc` line 55 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2705#-NSZypAi9u2bbzdVRXSN:-NS_1-2q6Fy7z7luAELA:bichsc4) ([raw file](https://github.com/starkware-libs/cairo/blob/53c7412c82c95b294e2f650d288aac8377d43ce8/docs/reference/src/path.adoc#L55)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

It's not a new bullet, it's an example of the current bullet, like below
</blockquote></details>

I meant subbullets, like the "-"s below (- `let x: Option<bool> = None; // Let statement type clause`)

**Pull request merged**
