### PR TITLE
Added semantic analyzer plugins support.

### PR DESCRIPTION
**Pull request by orizi**
Moved plugin-suite definition to semantic to support this.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4480)

### CODE REVIEW

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4480)* status: 4 of 12 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/test_utils.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4480#-NkEvRBe4t-wtDM3UfY3:-NkEvRBe4t-wtDM3UfY4:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/5bff2f7305d0b8cf66f5103d40bd817f4e469de3/crates/cairo-lang-lowering/src/test_utils.rs#L46)):*
> ```XML
>     res.set_macro_plugins(suite.plugins);
>     res.set_inline_macro_plugins(suite.inline_macro_plugins.into());
>     res.set_analyzer_plugins(vec![]);
> ```





_Suggestion:_
```XML
suite.analyzer_plugins
```
___
*[`crates/cairo-lang-semantic/src/plugin.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4480#-NkEyRLL9xZe5REgeZFn:-NkEyRLL9xZe5REgeZFo:b9kpuww) ([raw file](https://github.com/starkware-libs/cairo/blob/5bff2f7305d0b8cf66f5103d40bd817f4e469de3/crates/cairo-lang-semantic/src/plugin.rs#L9)):*
> ```XML
> use crate::db::SemanticGroup;
> 
> /// A trait for a macro plugin: external plugin that generates additional code for items.
> ```

Wrong doc



_Code quote:_
```XML
/// A trait for a macro plugin: external plugin that generates additional code for items.
```
___
*[`crates/cairo-lang-semantic/src/plugin.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4480#-NkEzcAkBXjNQiLgnR-q:-NkEzcAkBXjNQiLgnR-r:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/5bff2f7305d0b8cf66f5103d40bd817f4e469de3/crates/cairo-lang-semantic/src/plugin.rs#L51)):*
> ```XML
>     pub fn add(&mut self, suite: PluginSuite) -> &mut Self {
>         self.plugins.extend(suite.plugins);
>         self.inline_macro_plugins.extend(suite.inline_macro_plugins);
> ```





_Suggestion:_
```XML
self.inline_macro_plugins.extend(suite.inline_macro_plugins);
self.analyzer_plugins.extend(suite.analyzer_plugins);
```

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4480)* status: 6 of 12 files reviewed, 6 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/plugin.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4480#-NkF-5ToDruvNKw70LuZ:-NkF-5ToDruvNKw70Lu_:b-a157id) ([raw file](https://github.com/starkware-libs/cairo/blob/5bff2f7305d0b8cf66f5103d40bd817f4e469de3/crates/cairo-lang-semantic/src/plugin.rs#L24)):*
> ```XML
>     pub analyzer_plugins: Vec<Arc<dyn AnalyzerPlugin>>,
> }
> impl PluginSuite {
> ```

Shouldn't we add `add_analyzer` etc?



_Code quote:_
```XML
mpl PluginSuite {
```
___
*[`crates/cairo-lang-semantic/src/test_utils.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4480#-NkF-0qM-asIlLA_T_Oo:-NkF-0qM-asIlLA_T_Op:b-nefzi6) ([raw file](https://github.com/starkware-libs/cairo/blob/5bff2f7305d0b8cf66f5103d40bd817f4e469de3/crates/cairo-lang-semantic/src/test_utils.rs#L45)):*
> ```XML
>         res.set_macro_plugins(suite.plugins);
>         res.set_inline_macro_plugins(suite.inline_macro_plugins.into());
>         res.set_analyzer_plugins(vec![]);
> ```

suite.analyzer_plugins



_Code quote:_
```XML
vec![]
```
___
*[`crates/cairo-lang-sierra-generator/src/test_utils.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4480#-NkF-Eo3DOYvcYBnkG2S:-NkF-Eo4816gUWCfHueW:b-ya81ng) ([raw file](https://github.com/starkware-libs/cairo/blob/5bff2f7305d0b8cf66f5103d40bd817f4e469de3/crates/cairo-lang-sierra-generator/src/test_utils.rs#L64)):*
> ```XML
>         res.set_macro_plugins(suite.plugins);
>         res.set_inline_macro_plugins(suite.inline_macro_plugins.into());
>         res.set_analyzer_plugins(vec![]);
> ```

Same as above



_Code quote:_
```XML
vec![]
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4480)* status: 6 of 12 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-lowering/src/test_utils.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4480#-NkEvRBe4t-wtDM3UfY3:-NkF-JKB3iY1XpQdwU9k:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5bff2f7305d0b8cf66f5103d40bd817f4e469de3/crates/cairo-lang-lowering/src/test_utils.rs#L46)):*
> ```XML
>     res.set_macro_plugins(suite.plugins);
>     res.set_inline_macro_plugins(suite.inline_macro_plugins.into());
>     res.set_analyzer_plugins(vec![]);
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/plugin.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4480#-NkEzcAkBXjNQiLgnR-q:-NkF0Gz2ApYWmjuYMYRh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5bff2f7305d0b8cf66f5103d40bd817f4e469de3/crates/cairo-lang-semantic/src/plugin.rs#L51)):*
> ```XML
>     pub fn add(&mut self, suite: PluginSuite) -> &mut Self {
>         self.plugins.extend(suite.plugins);
>         self.inline_macro_plugins.extend(suite.inline_macro_plugins);
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/test_utils.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4480#-NkF-0qM-asIlLA_T_Oo:-NkF0I03BejxWx8RukRg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5bff2f7305d0b8cf66f5103d40bd817f4e469de3/crates/cairo-lang-semantic/src/test_utils.rs#L45)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

suite.analyzer_plugins
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/test_utils.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4480#-NkF-Eo3DOYvcYBnkG2S:-NkF0jHkA_KJOGL-gmBI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5bff2f7305d0b8cf66f5103d40bd817f4e469de3/crates/cairo-lang-sierra-generator/src/test_utils.rs#L64)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 12 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4480#-:-NkF0yGT1xPzFyisEfH5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
