### PR TITLE
Handling basic audit comments.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #3507
- #3506
- #3504 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3504)

### CODE REVIEW

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3504#-:-NYqqbZDC6DPVHgWfUCq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3504)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned128.rs` line 473 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3504#-NYrtL3J84uPnA19HgAm:-NYrtL3J84uPnA19HgAn:b3aorb6) ([raw file](https://github.com/starkware-libs/cairo/blob/004ef87e1e5162644ece8a12c2efbe08efe9e9ef/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned128.rs#L473)):*
> ```XML
>         const shift_inverse =
>             -BigInt::from_str_radix("800000000000011000000000000000000", 16).unwrap();
>         tempvar result = temp * shift_inverse;
> ```

and changed to `deferred`.



_Suggestion:_
```XML
let result = temp * shift_inverse;
```

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3504)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`tests/e2e_test_data/libfuncs/u128` line 557 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3504#-NYrtQt82PSvG_WmAjPH:-NYrtQt82PSvG_WmAjPI:b-ooekb) ([raw file](https://github.com/starkware-libs/cairo/blob/004ef87e1e5162644ece8a12c2efbe08efe9e9ef/tests/e2e_test_data/libfuncs/u128#L557)):*
> ```
> [ap + 0] = [ap + -1] * -2722258935367507787987227068238114324480, ap++;
> [ap + 0] = [fp + -4] + 20, ap++;
> [ap + 0] = [ap + -2], ap++;
> ```

One instruction should disappear here.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3504)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned128.rs` line 473 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3504#-NYrtL3J84uPnA19HgAm:-NYrvugQ7XAFow95CJOj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/004ef87e1e5162644ece8a12c2efbe08efe9e9ef/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned128.rs#L473)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

and changed to `deferred`.
</blockquote></details>

Done.
___
*[`tests/e2e_test_data/libfuncs/u128` line 557 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3504#-NYrtQt82PSvG_WmAjPH:-NYrvu9O4CvUe6AKZXg2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/004ef87e1e5162644ece8a12c2efbe08efe9e9ef/tests/e2e_test_data/libfuncs/u128#L557)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

One instruction should disappear here.
</blockquote></details>

Done.

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3504#-:-NYryWO79vHXJQaRm10N:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3504#-:-NYvLjSDCBHtdf5GRXyi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
