### PR TITLE
Added libfunc bytes31_const

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3607)

### CODE REVIEW

**Comment by yuvalsw** [comment]
Change target branch

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3607)* status: 3 of 10 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/bytes31.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3607#-NZeORx_5QqHXxeH0dz-:-NZeORx_5QqHXxeH0dz0:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/77a87a0b7b83dfd9acfb799287631920a1f418cf/crates/cairo-lang-sierra/src/extensions/modules/bytes31.rs#L40)):*
> ```XML
> #[derive(Default)]
> pub struct Bytes31ConstLibfunc {}
> impl NamedLibfunc for Bytes31ConstLibfunc {
> ```





_Suggestion:_
```XML
#[derive(Default)]
pub struct Bytes31ConstLibfunc {}
impl ConstGenLibfunc for Bytes31ConstLibfunc {
    
    #[derive(Default)]
pub struct Bytes31ConstLibfuncWrapped {}
impl ConstGenLibfunc for Bytes31ConstLibfuncWrapped {
    const STR_ID: &'static str = "bytes31_const";
    const GENERIC_TYPE_ID: GenericTypeId = <Bytes31Type as NoGenericArgsGenericType>::ID;

    fn bound() -> BigInt {
        BigInt::from(2).pow(248)
    }
}

pub type Bytes31ConstLibfunc = WrapConstGenLibfunc<Bytes31ConstLibfuncWrapped>;
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3607)* status: 3 of 10 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/bytes31.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3607#-NZeORx_5QqHXxeH0dz-:-NZefvzJ6oaNQhvqFAuw:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/77a87a0b7b83dfd9acfb799287631920a1f418cf/crates/cairo-lang-sierra/src/extensions/modules/bytes31.rs#L40)):*
> ```XML
> #[derive(Default)]
> pub struct Bytes31ConstLibfunc {}
> impl NamedLibfunc for Bytes31ConstLibfunc {
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 10 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3607#-:-NZeoGVB1EJgv_AKd33j:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/bytes31.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3607#-NZeo7C-BoAr7OgbkTsu:-NZeo7C-BoAr7OgbkTsv:b67muhi) ([raw file](https://github.com/starkware-libs/cairo/blob/f87f25e5d7fffd46038d35b404bc18ebb5bf6708/crates/cairo-lang-sierra/src/extensions/modules/bytes31.rs#L55)):*
> ```XML
>         &self.signature
>     }
> }
> ```

i think you can delete this.



_Code quote:_
```XML
pub struct Bytes31ConstConcreteLibfunc {
    pub c: BigInt,
    pub signature: LibfuncSignature,
}
impl SignatureBasedConcreteLibfunc for Bytes31ConstConcreteLibfunc {
    fn signature(&self) -> &LibfuncSignature {
        &self.signature
    }
}
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3607)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/bytes31.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3607#-NZeo7C-BoAr7OgbkTsu:-NZevQqz1J-1gJUwrxnM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f87f25e5d7fffd46038d35b404bc18ebb5bf6708/crates/cairo-lang-sierra/src/extensions/modules/bytes31.rs#L55)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i think you can delete this.
</blockquote></details>

Done.

**Pull request merged**
