### PR TITLE
Remove global `implicits_precedence` from RootDatabase and replace it with tagging of `#[external]` functions within `StarknetPlugin`

### LINKED ISSUE #2651: dev:  Remove global `implicits_precedence` from RootDatabase and replace it with tagging of `#[external]` functions within `StarknetPlugin`
As title says. This has been discussed with Cairo team privately and we agreed upon trying this approach.

### PR DESCRIPTION
**Pull request by mkaput**
fix #2651

---

**Stack**:
- #2960
- #2959
- #2958 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2958)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2958)* status: 0 of 21 files reviewed, 1 unresolved discussion (waiting on @mkaput, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/test_data/erc20.sierra` line 2322 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2958#-NUL-hvC7nNvmZtaeJfF:-NUL-hvC7nNvmZtaeJfG:b-f6etxk) ([raw file](https://github.com/starkware-libs/cairo/blob/05a57e6e2db25a6fbdc95583abbf3444271add51/crates/cairo-lang-starknet/test_data/erc20.sierra#L2322)):*
> ```
> branch_align() -> ();
> struct_deconstruct<Tuple<ContractAddress>>([11]) -> ([13]);
> store_temp<RangeCheck>([0]) -> ([19]);
> ```

why did the order change? are those internal functions?



_Code quote:_
```
store_temp<RangeCheck>([0]) -> ([19]);
```

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2958)* status: 0 of 21 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/test_data/erc20.sierra` line 2322 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2958#-NUL-hvC7nNvmZtaeJfF:-NUQKsUI0g1aWtWgjkgK:bmusvyu) ([raw file](https://github.com/starkware-libs/cairo/blob/05a57e6e2db25a6fbdc95583abbf3444271add51/crates/cairo-lang-starknet/test_data/erc20.sierra#L2322)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why did the order change? are those internal functions?
</blockquote></details>

yes they are internal, I have checked it and no external function has changed the order

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 8 of 21 files at r1, 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2958#-:-NUQXASC6J2mVt8nnRI7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by ilyalesokhin-starkware — APPROVED** [review]

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2958)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
