### PR TITLE
fix warnings and lints

### PR DESCRIPTION
**Pull request by thor314**
Fixes a few lints and warnings. 
- cargo clippy --fix
- ? operator
- lint by hand

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5030)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5030)* status: all files reviewed, 1 unresolved discussion (waiting on @thor314)

___
*[`crates/cairo-lang-sierra-ap-change/src/compute.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5030#-Nq4i2O63qi4xpshPRXB:-Nq4i2O63qi4xpshPRXC:b-3ihs7q) ([raw file](https://github.com/starkware-libs/cairo/blob/e6a93f237dfce8a6f5a40d50cb16f5a9f22c043c/crates/cairo-lang-sierra-ap-change/src/compute.rs#L40)):*
> ```XML
> enum ApTrackingBase {
>     FunctionStart(FunctionId),
>     #[allow(dead_code)]
> ```

why is it deadcode for you?



_Code quote:_
```XML
    #[allow(dead_code)]
```

**Comment by thor314** [comment]
@orizi 
clippy flags the enum variant as unused. This indicates that the enum variant is not directly consumed. A grep for the variant shows that it's used in one place, so this warning may be a linting bug, rather than a bug in the library. I can comment it as such if helpful.

**Review by orizi — CHANGES_REQUESTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5030#-:-NqYppMr56DH5toePQFC:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @thor314)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5030#-NqYpqpQ97OAvkTk3b4l:-NqYpqpQ97OAvkTk3b4m:b3l5gbm) (no related file):*
@gilbens-starkware for 2nd eye

___

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5030#-:-Nqawk9U5v7u5OJhGuK3:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @thor314)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5030)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @thor314)

**Pull request merged**
