### PR TITLE
pub fn starknet_compile

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3074)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3074)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @zuphitf)

___
*[`crates/cairo-lang-starknet/src/cli.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3074#-NUzC4bp52xEK5KFofXn:-NUzC4bp52xEK5KFofXo:b-r0rtx5) ([raw file](https://github.com/starkware-libs/cairo/blob/d58807dcacffd8bd0529a656abfc01b35d8e86bf/crates/cairo-lang-starknet/src/cli.rs#L34)):*
> ```XML
> 
> /// Compile Starknet crate (or specific contract in the crate).
> pub fn starknet_compile(
> ```

Why do you need this function? Can't you use compile_path?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3074)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware and @zuphitf)

___
*[`crates/cairo-lang-starknet/src/cli.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3074#-NUzC4bp52xEK5KFofXn:-NUzCjoB67H8Rk8CO-4r:blj932p) ([raw file](https://github.com/starkware-libs/cairo/blob/d58807dcacffd8bd0529a656abfc01b35d8e86bf/crates/cairo-lang-starknet/src/cli.rs#L34)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Why do you need this function? Can't you use compile_path?
</blockquote></details>

What about sierra compatibility validation?
It's also nice to put the `serde` logic somewhere IMO

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3074)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware and @zuphitf)

___
*[`crates/cairo-lang-starknet/src/cli.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3074#-NUzC4bp52xEK5KFofXn:-NUzDCDUAr21oRLoCusM:b-yaowuo) ([raw file](https://github.com/starkware-libs/cairo/blob/d58807dcacffd8bd0529a656abfc01b35d8e86bf/crates/cairo-lang-starknet/src/cli.rs#L34)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

What about sierra compatibility validation?
It's also nice to put the `serde` logic somewhere IMO
</blockquote></details>

(moved out of CLI)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3074)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @zuphitf)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:
Please wait for @orizi 's approval

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3074#-:-NUzJXLBC4PVgnNNP0hN:bncviup)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zuphitf)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3074)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @zuphitf)

___
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 257 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3074#-NUzLCBE0mJBuF1MtdCs:-NUzLCBFDeiXhPeGLo_5:bm4fck3) ([raw file](https://github.com/starkware-libs/cairo/blob/3c262d1e8e18dbc4db90e81ea60c3463216f8a4b/crates/cairo-lang-starknet/src/contract_class.rs#L257)):*
> ```XML
> /// Compile Starknet crate (or specific contract in the crate).
> pub fn starknet_compile(
>     crate_path: PathBuf,
> ```

Get the list selector as an argument here instead of building it.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3074)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @zuphitf)

___
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 257 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3074#-NUzLCBE0mJBuF1MtdCs:-NUzg9FGDCW52zcZ3L9n:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3c262d1e8e18dbc4db90e81ea60c3463216f8a4b/crates/cairo-lang-starknet/src/contract_class.rs#L257)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Get the list selector as an argument here instead of building it.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3074#-:-NUzmetf8Lmz-lvHMcl6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zuphitf)

**Pull request merged**
