### PR TITLE
validated negative impls of generated impls

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6490)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6490)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 965 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6490#-O9F9qoC6uoAPHWCybyW:-O9F9qoC6uoAPHWCybyX:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7982feb388b60f4235bd4b140167becf08b90774/crates/cairo-lang-semantic/src/expr/inference.rs#L965)):*
> ```XML
>         };
> 
>         //
> ```


___
*[`crates/cairo-lang-semantic/src/expr/inference/infers.rs` line 147 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6490#-O9F9U45BKyuIZQIpmr8:-O9F9U45BKyuIZQIpmr9:b7v8fuu) ([raw file](https://github.com/starkware-libs/cairo/blob/7982feb388b60f4235bd4b140167becf08b90774/crates/cairo-lang-semantic/src/expr/inference/infers.rs#L147)):*
> ```XML
>             UninferredImpl::GeneratedImpl(generated_impl) => {
>                 let long_id = generated_impl.lookup_intern(self.db);
>                 self.infer_generic_args(&long_id.generic_params[..], lookup_context, stable_ptr)?;
> ```

doc why ignoring the returned values is fine.



_Code quote:_
```XML
                self.infer_generic_args(&long_id.generic_params[..], lookup_context, stable_ptr)?;
```
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 352 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6490#-O9F9Z6OCr2q8wemyPDm:-O9F9Z6OCr2q8wemyPDn:blki33a) ([raw file](https://github.com/starkware-libs/cairo/blob/7982feb388b60f4235bd4b140167becf08b90774/crates/cairo-lang-semantic/src/items/imp.rs#L352)):*
> ```XML
> pub struct GeneratedImplLongId {
>     pub concrete_trait: ConcreteTraitId,
>     /// The generic arguments used by the generated impl, typically impls and negative impls.
> ```

fix doc - and additionally explain why params specifically and not args.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6490)* status: 3 of 10 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 965 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6490#-O9F9qoC6uoAPHWCybyW:-O9FF1PLBGCFYohtVeZ4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7982feb388b60f4235bd4b140167becf08b90774/crates/cairo-lang-semantic/src/expr/inference.rs#L965)):*
> ```XML
>         };
> 
>         //
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 998 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6490#-O9FAl7RAAT82hZt4neA:-O9FeOCW7dA2R_svLcSr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7982feb388b60f4235bd4b140167becf08b90774/crates/cairo-lang-semantic/src/expr/inference.rs#L998)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

consider extracting to function and calling it to avoid the above `.collect()` calls.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/inference/infers.rs` line 147 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6490#-O9F9U45BKyuIZQIpmr8:-O9FFMOS-4Hz7WMTHI7q:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7982feb388b60f4235bd4b140167becf08b90774/crates/cairo-lang-semantic/src/expr/inference/infers.rs#L147)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc why ignoring the returned values is fine.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 352 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6490#-O9F9Z6OCr2q8wemyPDm:-O9FFU4N7KPQNSG6-P65:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7982feb388b60f4235bd4b140167becf08b90774/crates/cairo-lang-semantic/src/items/imp.rs#L352)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix doc - and additionally explain why params specifically and not args.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6490)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference/infers.rs` line 149 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6490#-O9FvCj8-neOvL3dN7kS:-O9FvCj8-neOvL3dN7kT:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/04734319c8ad71aeda310b5af8d5bfcdd44ee8c6/crates/cairo-lang-semantic/src/expr/inference/infers.rs#L149)):*
> ```XML
> 
>                 // we never use the generic args of the generated impl, so we don't need to save
>                 // them. we only make sure they can be inferred.
> ```





_Suggestion:_
```XML
                // Only making sure the args can be inferred - as they are unused later.
```
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_impl` line 1241 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6490#-O9FvZK43s1jx3bfuxpv:-O9FvZK43s1jx3bfuxpw:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/04734319c8ad71aeda310b5af8d5bfcdd44ee8c6/crates/cairo-lang-semantic/src/items/tests/trait_impl#L1241)):*
> ```
> //! > expected_diagnostics
> 
> //! > ==========================================================================
> ```





_Suggestion:_
```
//! > ==========================================================================
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6490)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6490)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/items/tests/trait_impl` line 1280 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6490#-O9G1n5b21y3QnDcpX6v:-O9G1n5b21y3QnDcpX6w:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/04734319c8ad71aeda310b5af8d5bfcdd44ee8c6/crates/cairo-lang-semantic/src/items/tests/trait_impl#L1280)):*
> ```
>         bar(2_u32)
>     }
> }
> ```





_Suggestion:_
```
trait InnerTrait<R> {
    type X;
    fn foo() -> Self::X;
}

trait OuterTrait<Y> {
    impl Inner: InnerTrait<Y>;
}
impl OuterImpl<T, impl I: InnerTrait<T>> of OuterTrait<T> {}


mod my_mod {
    // Implementing `InnerTrait` for all types.
    impl MyInner<T> of super::InnerTrait<T> {
        type X = u16;
        fn foo() -> u16 {
            5
        }
    }
    fn requires_outer<T, impl O: super::OuterTrait<T>>(_x: T) -> O::Inner::X {
        O::Inner::foo()
    }
    fn infers_outer_by_inner() -> u16 {
        requires_outer(2_u32)
    }
}
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6490)* status: 4 of 10 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @ilyalesokhin-starkware, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-semantic/src/expr/inference/infers.rs` line 149 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6490#-O9FvCj8-neOvL3dN7kS:-O9by_8B6luG04rDNUW5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/04734319c8ad71aeda310b5af8d5bfcdd44ee8c6/crates/cairo-lang-semantic/src/expr/inference/infers.rs#L149)):*
> ```XML
> 
>                 // we never use the generic args of the generated impl, so we don't need to save
>                 // them. we only make sure they can be inferred.
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_impl` line 1241 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6490#-O9FvZK43s1jx3bfuxpv:-O9bysDl2pG6K9ycOmFy:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/04734319c8ad71aeda310b5af8d5bfcdd44ee8c6/crates/cairo-lang-semantic/src/items/tests/trait_impl#L1241)):*
> ```
> //! > expected_diagnostics
> 
> //! > ==========================================================================
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_impl` line 1280 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6490#-O9G1n5b21y3QnDcpX6v:-O9bzvJqBsW2eBMu6VNZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/04734319c8ad71aeda310b5af8d5bfcdd44ee8c6/crates/cairo-lang-semantic/src/items/tests/trait_impl#L1280)):*
> ```
>         bar(2_u32)
>     }
> }
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6490#-:-O9d5PqR9xpMaSductLd:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, @ilyalesokhin-starkware, @mkaput, and @piotmag769)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/inference/infers.rs` line 148 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6490#-O9nt-5sCuMzz-79fFW5:-O9nt-5sCuMzz-79fFW6:b-kpwanm) ([raw file](https://github.com/starkware-libs/cairo/blob/258e1a2fd7c02619dd2a0198df4807ae72877124/crates/cairo-lang-semantic/src/expr/inference/infers.rs#L148)):*
> ```XML
>                 let long_id = generated_impl.lookup_intern(self.db);
> 
>                 // Only making sure the args can be inferred - as they are unused later.
> ```

they could be used by the impl, I'm not sure this is a good idea



_Code quote:_
```XML
     // Only making sure the args can be inferred - as they are unused later.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 353 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6490#-O9nt7uzD-ja-ueijEWU:-O9nt7uzD-ja-ueijEWV:b20ce9p) ([raw file](https://github.com/starkware-libs/cairo/blob/258e1a2fd7c02619dd2a0198df4807ae72877124/crates/cairo-lang-semantic/src/items/imp.rs#L353)):*
> ```XML
>     pub concrete_trait: ConcreteTraitId,
>     /// The generic params required for the impl. Typically impls and negative impls.
>     /// We save the params and not the args so we can infer the args when needed.
> ```

Didn't you write that they are unused?



_Code quote:_
```XML
  /// We save the params and not the args so we can infer the args when needed.
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6490)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6490)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference/infers.rs` line 148 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6490#-O9nt-5sCuMzz-79fFW5:-O9ntz0v0BsD-33y9QoU:b-hw5pqc) ([raw file](https://github.com/starkware-libs/cairo/blob/258e1a2fd7c02619dd2a0198df4807ae72877124/crates/cairo-lang-semantic/src/expr/inference/infers.rs#L148)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

they could be used by the impl, I'm not sure this is a good idea
</blockquote></details>

The return value of `self.infer_generic_args`  was never used.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 353 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6490#-O9nt7uzD-ja-ueijEWU:-O9nuGyE0KFhEPqqs_AI:b-h34h1l) ([raw file](https://github.com/starkware-libs/cairo/blob/258e1a2fd7c02619dd2a0198df4807ae72877124/crates/cairo-lang-semantic/src/items/imp.rs#L353)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Didn't you write that they are unused?
</blockquote></details>

The member generic_args was not used; now I need the generic params to infer negative impls

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/inference/infers.rs` line 148 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6490#-O9nt-5sCuMzz-79fFW5:-O9ny0OeEMX0VH5UnrI2:byyksv8) ([raw file](https://github.com/starkware-libs/cairo/blob/258e1a2fd7c02619dd2a0198df4807ae72877124/crates/cairo-lang-semantic/src/expr/inference/infers.rs#L148)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

The return value of `self.infer_generic_args`  was never used.
</blockquote></details>

it was stored in the ` GeneratedImplLongId` and could be used by the implementation.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 929 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6490#-O9nzHnaCbA5YQbVhC3Z:-O9nzHnaCbA5YQbVhC3_:b-b8q7s5) ([raw file](https://github.com/starkware-libs/cairo/blob/258e1a2fd7c02619dd2a0198df4807ae72877124/crates/cairo-lang-semantic/src/expr/inference.rs#L929)):*
> ```XML
>     /// Validate that the given impl is valid based on its negative impls arguments.
>     /// Returns `SolutionSet::Unique(canonical_impl)` if the impl is valid and
>     /// SolutionSet::Ambiguous(...) otherwise.
> ```

fix the documentation



_Code quote:_
```XML
    /// Validate that the given impl is valid based on its negative impls arguments.
    /// Returns `SolutionSet::Unique(canonical_impl)` if the impl is valid and
    /// SolutionSet::Ambiguous(...) otherwise.
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6490)* status: all files reviewed, 4 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 939 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6490#-O9nyxXE41g5erNB4iA6:-O9nyxXF7jcSFYuXyLwT:b58r0b9) ([raw file](https://github.com/starkware-libs/cairo/blob/258e1a2fd7c02619dd2a0198df4807ae72877124/crates/cairo-lang-semantic/src/expr/inference.rs#L939)):*
> ```XML
>             canonical_impl: CanonicalImpl,
>             lookup_context: &ImplLookupContext,
>             concrete_traits: impl Iterator<Item = Maybe<ConcreteTraitId>>,
> ```

This argument is the negative simple, right?



_Suggestion:_
```XML
   negative_impls: impl Iterator<Item = Maybe<ConcreteTraitId>>,
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6490)* status: all files reviewed, 4 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 353 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6490#-O9nt7uzD-ja-ueijEWU:-O9nzlKA2CluIBIjhF5I:b-pdvpm7) ([raw file](https://github.com/starkware-libs/cairo/blob/258e1a2fd7c02619dd2a0198df4807ae72877124/crates/cairo-lang-semantic/src/items/imp.rs#L353)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

The member generic_args was not used; now I need the generic params to infer negative impls
</blockquote></details>

I find it strange that the generated impl has parameter rather than arguments.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6490)* status: all files reviewed, 4 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 353 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6490#-O9nt7uzD-ja-ueijEWU:-O9o-0HBCpmGHFjLV_1A:b-rra7rt) ([raw file](https://github.com/starkware-libs/cairo/blob/258e1a2fd7c02619dd2a0198df4807ae72877124/crates/cairo-lang-semantic/src/items/imp.rs#L353)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I find it strange that the generated impl has parameter rather than arguments.
</blockquote></details>

If it is just an implementation detail, you might as well only put the negative impls here and fix the comment.

Having 1 comments saying that the arguments are unused and another comment saying that you are saving the parameters in order to infer them is confusing.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6490)* status: 9 of 10 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 929 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6490#-O9nzHnaCbA5YQbVhC3Z:-O9oPdcdADalWmq4Sy2T:b-9a7byp) ([raw file](https://github.com/starkware-libs/cairo/blob/258e1a2fd7c02619dd2a0198df4807ae72877124/crates/cairo-lang-semantic/src/expr/inference.rs#L929)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

fix the documentation
</blockquote></details>

How is it different, I have only added generated impls, but the function should still work the same
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 939 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6490#-O9nyxXE41g5erNB4iA6:-O9oQAIzCXzl759O_Uim:b-q0zdn7) ([raw file](https://github.com/starkware-libs/cairo/blob/258e1a2fd7c02619dd2a0198df4807ae72877124/crates/cairo-lang-semantic/src/expr/inference.rs#L939)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

This argument is the negative simple, right?
</blockquote></details>

used negative\_impls\_concrete\_traits
___
*[`crates/cairo-lang-semantic/src/expr/inference/infers.rs` line 148 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6490#-O9nt-5sCuMzz-79fFW5:-O9o73tz7UW68pzHchFG:bppvhr1) ([raw file](https://github.com/starkware-libs/cairo/blob/258e1a2fd7c02619dd2a0198df4807ae72877124/crates/cairo-lang-semantic/src/expr/inference/infers.rs#L148)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it was stored in the ` GeneratedImplLongId` and could be used by the implementation.
</blockquote></details>

I don't understand the variable was never used previously
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 353 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6490#-O9nt7uzD-ja-ueijEWU:-O9oQN9-9MbVr6cXQ2i9:b-bwivnk) ([raw file](https://github.com/starkware-libs/cairo/blob/258e1a2fd7c02619dd2a0198df4807ae72877124/crates/cairo-lang-semantic/src/items/imp.rs#L353)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

If it is just an implementation detail, you might as well only put the negative impls here and fix the comment.

Having 1 comments saying that the arguments are unused and another comment saying that you are saving the parameters in order to infer them is confusing.
</blockquote></details>

Concrete impls have a refrence to their impldef which has a reference to the generic params.
So I think generated impls should have access to their generic params as well, we can also add the generic args to generated impls but currently we do not use them.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 929 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6490#-O9nzHnaCbA5YQbVhC3Z:-OAC5Mvk30iisx8uRtUa:b1o1ebi) ([raw file](https://github.com/starkware-libs/cairo/blob/258e1a2fd7c02619dd2a0198df4807ae72877124/crates/cairo-lang-semantic/src/expr/inference.rs#L929)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

How is it different, I have only added generated impls, but the function should still work the same
</blockquote></details>

my bad, for some reason I thought this is the documentation of ` validate_no_solution_set`

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 935 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6490#-OAC793T45yEojmKoelK:-OAC793T45yEojmKoelL:bbwbdj9) ([raw file](https://github.com/starkware-libs/cairo/blob/2979f4f6cd5f9b00685f86e4a581854445206aee/crates/cairo-lang-semantic/src/expr/inference.rs#L935)):*
> ```XML
>         canonical_impl: CanonicalImpl,
>     ) -> InferenceResult<SolutionSet<CanonicalImpl>> {
>         fn validate_no_solution_set(
> ```

Can you document it?



_Code quote:_
```XML
  fn validate_no_solution_set(
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/inference/infers.rs` line 148 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6490#-O9nt-5sCuMzz-79fFW5:-OAC7HwYE1YFXdNEnPjx:bkeib5j) ([raw file](https://github.com/starkware-libs/cairo/blob/258e1a2fd7c02619dd2a0198df4807ae72877124/crates/cairo-lang-semantic/src/expr/inference/infers.rs#L148)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

I don't understand the variable was never used previously
</blockquote></details>

It was not used, but the implementation could use them.
I guess I'm ok with removing it for now.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 353 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6490#-O9nt7uzD-ja-ueijEWU:-OAC86eC9z2B8ABUovD7:b-wj2hav) ([raw file](https://github.com/starkware-libs/cairo/blob/258e1a2fd7c02619dd2a0198df4807ae72877124/crates/cairo-lang-semantic/src/items/imp.rs#L353)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

Concrete impls have a refrence to their impldef which has a reference to the generic params.
So I think generated impls should have access to their generic params as well, we can also add the generic args to generated impls but currently we do not use them.
</blockquote></details>

ok.
Can you update to the comment and mention that this is used for validating the negative impls.

Saying "infer the args when needed" make one wonder why you didn't save the inferred argument in the first place.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 1 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6490)* status: 9 of 10 files reviewed, 4 unresolved discussions (waiting on @orizi and @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6490)* status: 8 of 10 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 929 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6490#-O9nzHnaCbA5YQbVhC3Z:-OACE5qbEy7-KOjT2pyK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/258e1a2fd7c02619dd2a0198df4807ae72877124/crates/cairo-lang-semantic/src/expr/inference.rs#L929)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

my bad, for some reason I thought this is the documentation of ` validate_no_solution_set`
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 935 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6490#-OAC793T45yEojmKoelK:-OACGT9b-WJ6AYwNXP2R:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2979f4f6cd5f9b00685f86e4a581854445206aee/crates/cairo-lang-semantic/src/expr/inference.rs#L935)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Can you document it?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 353 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6490#-O9nt7uzD-ja-ueijEWU:-OACH73-6HiXhxg6TErD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/258e1a2fd7c02619dd2a0198df4807ae72877124/crates/cairo-lang-semantic/src/items/imp.rs#L353)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

ok.
Can you update to the comment and mention that this is used for validating the negative impls.

Saying "infer the args when needed" make one wonder why you didn't save the inferred argument in the first place.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 2 of 7 files at r1, 4 of 6 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6490)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6490#-:-OAH29MvDpxkQ60QtTwI:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
