### PR TITLE
Made sierra type size i16.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:b7192c58

---

**Stack**:
- #1374
- #1356
- #1355 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1355)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @orizi and @yuvalsw)

___
*[`crates/sierra/src/extensions/types.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1355#-NJYjaI2-dnLhFDMVKdM:-NJYjaI3C8zfVGdY0qRf:b-co0yc1) ([raw file](https://github.com/starkware-libs/cairo/blob/d757c87c56ae514db43e57d40dc5e36bf5866b4d/crates/sierra/src/extensions/types.rs#L117)):*
> ```XML
>     pub duplicatable: bool,
>     /// The size of an element of this type.
>     pub size: i16,
> ```

why not u16?



_Code quote:_
```XML
i16
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1355)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`crates/sierra/src/extensions/types.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1355#-NJYjaI2-dnLhFDMVKdM:-NJZ2Odj-B5q6FXndyhQ:bp4lbkx) ([raw file](https://github.com/starkware-libs/cairo/blob/d757c87c56ae514db43e57d40dc5e36bf5866b4d/crates/sierra/src/extensions/types.rs#L117)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why not u16?
</blockquote></details>

since this is the max positive offset we support.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1355#-:-NJZHss2DonNewxwNjmb:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1355)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
