### PR TITLE
Added debug option to formatting.

### PR DESCRIPTION
**Pull request by orizi**
Includes adding a Debug derive.

---

**Stack**:
- #4361
- #4359
- #4358
- #4357 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4357)

### CODE REVIEW

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4357)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/fmt.cairo` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4357#-NiYaId7Cxg43is3BxRM:-NiYaId7Cxg43is3BxRN:buwxo9b) ([raw file](https://github.com/starkware-libs/cairo/blob/b82f2456a26824f0b2e6c4041de57e6b8386350d/corelib/src/fmt.cairo#L46)):*
> ```Cairo
> /// A trait for debug formatting, using the empty format ("{:?}").
> trait Debug<T> {
>     fn fmt(self: @T, ref f: Formatter) -> Result<(), Error>;
> ```

I know that this is the same in rust, but maybe we should consider calling the function `debug_fmt` as this will collide with `Display::fmt` if someone will call it as a method.
But I guess we can always add wrappers with other names.
___
*[`crates/cairo-lang-semantic/src/inline_macros/write.rs` line 173 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4357#-NiYcFca3ylly9OIpIJ1:-NiYcFca3ylly9OIpIJ2:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b82f2456a26824f0b2e6c4041de57e6b8386350d/crates/cairo-lang-semantic/src/inline_macros/write.rs#L173)):*
> ```XML
>                     diagnostics.push(PluginDiagnostic {
>                         stable_ptr: self.format_string_arg.as_syntax_node().stable_ptr(),
>                         message: "Invalid format string: expected `}` or variable name."
> ```





_Suggestion:_
```XML
 or variable name, or formatting modifiers."
```
___
*[`crates/cairo-lang-semantic/src/inline_macros/write.rs` line 389 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4357#-NiYf-dq95F7EqT0GN5R:-NiYf-dq95F7EqT0GN5S:b-p0y487) ([raw file](https://github.com/starkware-libs/cairo/blob/b82f2456a26824f0b2e6c4041de57e6b8386350d/crates/cairo-lang-semantic/src/inline_macros/write.rs#L389)):*
> ```XML
>                 }
>             }
>             break;
> ```

This means that there was no `}`, i.e. this is working:
```
write!(f, "{:?", ba);
```



_Code quote:_
```XML
break;
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4357)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`corelib/src/fmt.cairo` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4357#-NiYaId7Cxg43is3BxRM:-NiYgLJH9scjGtlHKxNn:b-f2twv5) ([raw file](https://github.com/starkware-libs/cairo/blob/b82f2456a26824f0b2e6c4041de57e6b8386350d/corelib/src/fmt.cairo#L46)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

I know that this is the same in rust, but maybe we should consider calling the function `debug_fmt` as this will collide with `Display::fmt` if someone will call it as a method.
But I guess we can always add wrappers with other names.
</blockquote></details>

adding other methods would be preferable IMO.
___
*[`crates/cairo-lang-semantic/src/inline_macros/write.rs` line 389 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4357#-NiYf-dq95F7EqT0GN5R:-NiYhFyB4ChbHpXrYuwL:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b82f2456a26824f0b2e6c4041de57e6b8386350d/crates/cairo-lang-semantic/src/inline_macros/write.rs#L389)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

This means that there was no `}`, i.e. this is working:
```
write!(f, "{:?", ba);
```
</blockquote></details>

Done.

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4357)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4357#-:-NiYoXXV4lCwDIDwSADj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
