### PR TITLE
Rename Storage to ContractState

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3358)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3358** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3358" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/3358?utm_source=stack-comment).

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 42 of 42 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3358)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware and @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3358#-NXeDVs2EHpQXB-WrSdb:-NXeDVs2EHpQXB-WrSdc:b2hks24) (no related file):*
why are there sierra json binary changes?

___

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3358)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3358#-NXeDVs2EHpQXB-WrSdb:-NXeMPgVA_jOk7_r3bDj:b-cl9exr) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why are there sierra json binary changes?
</blockquote></details>

You tell me

___

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3358)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware and @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3358#-NXeDVs2EHpQXB-WrSdb:-NXeMjfu3dkvmGxMYUGC:b9tpc1p) (no related file):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

You tell me
</blockquote></details>

i don't know - that is why i ask.

___

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3358)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3358#-NXeDVs2EHpQXB-WrSdb:-NXeMtks1gmFnBIuBwQS:bshqjtx) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i don't know - that is why i ask.
</blockquote></details>

I dont know how sierralization looks like. You can see the sierra changes though - they are just names

___

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3358#-:-NXeNmDn5sH8m4seL2Uv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3358#-NXeDVs2EHpQXB-WrSdb:-NXeNeuHArAoCT-DO2Oy:b-bwfnky) (no related file):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I dont know how sierralization looks like. You can see the sierra changes though - they are just names
</blockquote></details>

oh - it is the user types - which are hashes on the names when they are too long - so all good.

___

**Review by orizi — APPROVED** [review]
> Reviewed 18 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3358)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
