### PR TITLE
Added plugin to allow marking a function as runnable.

### PR DESCRIPTION
**Pull request by orizi**
This creates a wrapper for running it, deserializing the inputs and
serializing the outputs.

---

**Stack**:
- #6579
- #6578
- #6576 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6576)* status: 7 of 10 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @ilyalesokhin-starkware, and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6576#-OAqXuB8BLRXnJTyGZIq:-OAqXuB8BLRXnJTyGZIr:bp420vq) (no related file):*
Shouldn't this mark wrappers as `#[executable]`?

___

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6576)* status: 5 of 10 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @ilyalesokhin-starkware, and @mkaput)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6576#-OAqXuB8BLRXnJTyGZIq:-OAqi7PL0ub28Pq-bixE:bfyrldt) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Shouldn't this mark wrappers as `#[executable]`?
</blockquote></details>

this kinda sounds too much like a x86 binary.

i am completely open to suggestions.

___

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 1 of 8 files at r1, 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6576)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @mkaput)

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6576)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6576#-OAqXuB8BLRXnJTyGZIq:-OArOfKr02UxvPlmBFWN:b-w68ppu) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this kinda sounds too much like a x86 binary.

i am completely open to suggestions.
</blockquote></details>

OK. I think that a) I forgot how things are done and b) you misunderstood me :sweat_smile: 

What I meant: shouldn't `#[runnable]` be registered here? https://github.com/starkware-libs/cairo/blob/6c0f14b85241dd276a9d34b53aa90e9970bb3cd6/crates/cairo-lang-defs/src/plugin.rs#L128

___

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6576)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @mkaput)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6576#-OAqXuB8BLRXnJTyGZIq:-OArSUS52ouzmPkiR5EV:bkmbrmg) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

OK. I think that a) I forgot how things are done and b) you misunderstood me :sweat_smile: 

What I meant: shouldn't `#[runnable]` be registered here? https://github.com/starkware-libs/cairo/blob/6c0f14b85241dd276a9d34b53aa90e9970bb3cd6/crates/cairo-lang-defs/src/plugin.rs#L128
</blockquote></details>

Yeah, will add, as it will make the next part easier.
But this will become important only when we actually export the runnable into an artifact.

___

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6576)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6576#-OAqXuB8BLRXnJTyGZIq:-OArWejV6IAUjF2m_Osv:b-8eofx6) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Yeah, will add, as it will make the next part easier.
But this will become important only when we actually export the runnable into an artifact.
</blockquote></details>

True, but I didn't want this to be forgotten :)

___

**Pull request merged**
