### PR TITLE
Added high level syntax and tests for slice

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2720)

### CODE REVIEW

**Comment by orizi** [comment]
Current dependencies on/for this PR:
* 04-04-Fixed_slice_size_to_be_the_correct_limiting_size
  * **PR #2720** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo2/2720" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo2/2720?utm_source=stack-comment).

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2720)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`corelib/src/test/array_test.cairo` line 70 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2720#-NSZiWQY9hK7_NxknLQX:-NSZiWQY9hK7_NxknLQY:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/f367811caab4b2c183dc725424765951c7633104/corelib/src/test/array_test.cairo#L70)):*
> ```Cairo
>     assert(span.slice(0_usize, 2_usize).len() == 2_u32, 'Unexpected span length.');
>     assert(*span.slice(0_usize, 2_usize)[0_usize] == 10, 'Unexpected Element.');
>     assert(span.slice(0_usize, 1_usize).len() == 1_u32, 'Unexpected span length.');
> ```

remove



_Code quote:_
```Cairo
_usize
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2720)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`corelib/src/test/array_test.cairo` line 70 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2720#-NSZiWQY9hK7_NxknLQX:-NSZom5Z06CEF_kM3ij1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f367811caab4b2c183dc725424765951c7633104/corelib/src/test/array_test.cairo#L70)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2720)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2720#-:-NSZu7r76UTg3hRqN8GS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2720)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
