### PR TITLE
Improve macro coloring in language server.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4053)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4053#-:-Ne75XU8-NO-AAm6iIav:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4053)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-language-server/src/semantic_highlighting/token_kind.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4053#-Ne75ZWt7aTKlWTcfii4:-Ne75ZWt7aTKlWTcfii5:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/5980c6cd52f9090ea529ccdce886f622d917ac6e/crates/cairo-lang-language-server/src/semantic_highlighting/token_kind.rs#L55)):*
> ```XML
>                 if matches!(
>                     grandparent_kind(syntax_db, &node),
>                     Some(SyntaxKind::ExprInlineMacro) | Some(SyntaxKind::ItemInlineMacro)
> ```

.



_Suggestion:_
```XML
                    Some(SyntaxKind::ExprInlineMacro | SyntaxKind::ItemInlineMacro)
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4053)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-language-server/src/semantic_highlighting/token_kind.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4053#-Ne75ZWt7aTKlWTcfii4:-Ne786Lv-InU9XlVOrZ2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5980c6cd52f9090ea529ccdce886f622d917ac6e/crates/cairo-lang-language-server/src/semantic_highlighting/token_kind.rs#L55)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4053)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4053)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4053)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
