### PR TITLE
Added semantic QuerryAttr trait

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3376)

### CODE REVIEW

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3376)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/abi.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3376#-NXnS9U00lt-2DroJkod:-NXnS9U00lt-2DroJkoe:b-1hhycs) ([raw file](https://github.com/starkware-libs/cairo/blob/607aa5aa05c92685c09f28f2dc15e48087d0e73f/crates/cairo-lang-starknet/src/abi.rs#L78)):*
> ```XML
>         let mut storage_type = None;
>         for (id, strct) in db.module_structs(module_id).unwrap_or_default() {
>             if strct.name(db.upcast()).text(db.upcast()) == "Storage" {
> ```

name can be extracted from id



_Code quote:_
```XML
trct.name(db.upcast()).text(db.upcast()) 
```
___
*[`crates/cairo-lang-starknet/src/abi.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3376#-NXnRhKF4edrYG7KAQng:-NXnRhKF4edrYG7KAQnh:b-nlaiol) ([raw file](https://github.com/starkware-libs/cairo/blob/607aa5aa05c92685c09f28f2dc15e48087d0e73f/crates/cairo-lang-starknet/src/abi.rs#L121)):*
> ```XML
>         // Add external functions, constructor and L1 handlers to ABI.
>         let mut ctor = None;
>         for (id, _) in db.module_free_functions(module_id).unwrap_or_default() {
> ```

This query depends on the AST. I suggest using module_items() and matching, for all loops on this function



_Code quote:_
```XML
module_free_functions
```
___
*[`crates/cairo-lang-starknet/src/abi.rs` line 144 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3376#-NXnRvCa2mEMxVcWMtWu:-NXnRvCa2mEMxVcWMtWv:bmtysdz) ([raw file](https://github.com/starkware-libs/cairo/blob/607aa5aa05c92685c09f28f2dc15e48087d0e73f/crates/cairo-lang-starknet/src/abi.rs#L144)):*
> ```XML
>         // Add events.
>         for (id, enm) in db.module_enums(module_id).unwrap_or_default() {
>             if enm.name(db.upcast()).text(db.upcast()) == "Event"
> ```

You can extract the name from id instead of ast.



_Code quote:_
```XML
enm.name
```

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3376)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/items/attribute.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3376#-NXnXKK89ZEKkTdUuonF:-NXnXKK89ZEKkTdUuonG:blrutv9) ([raw file](https://github.com/starkware-libs/cairo/blob/607aa5aa05c92685c09f28f2dc15e48087d0e73f/crates/cairo-lang-semantic/src/items/attribute.rs#L34)):*
> ```XML
> 
> /// Trait for querying attributes of semantic items.
> pub trait QueryAttrs {
> ```

It bothers me a bit that this trait has the same name as the one in syntax. It can be confusing



_Code quote:_
```XML
QueryAttrs {
```

**Comment by yuvalsw** [comment]
*[`crates/cairo-lang-semantic/src/items/attribute.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3376#-NXnXKK89ZEKkTdUuonF:-NXnXUSpDOzX4TOY_bUG:b4jqrvl) ([raw file](https://github.com/starkware-libs/cairo/blob/607aa5aa05c92685c09f28f2dc15e48087d0e73f/crates/cairo-lang-semantic/src/items/attribute.rs#L34)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

It bothers me a bit that this trait has the same name as the one in syntax. It can be confusing
</blockquote></details>

Any suggestion? SemanticQueryAttrs?

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3376)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/items/attribute.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3376#-NXnXKK89ZEKkTdUuonF:-NXnXcIcBmzc6Qqpi6LB:b32wwp) ([raw file](https://github.com/starkware-libs/cairo/blob/607aa5aa05c92685c09f28f2dc15e48087d0e73f/crates/cairo-lang-semantic/src/items/attribute.rs#L34)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Any suggestion? SemanticQueryAttrs?
</blockquote></details>

sg

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3376)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/items/attribute.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3376#-NXnXKK89ZEKkTdUuonF:-NXnYwuA4KS254XV6NYQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/607aa5aa05c92685c09f28f2dc15e48087d0e73f/crates/cairo-lang-semantic/src/items/attribute.rs#L34)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

sg
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/abi.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3376#-NXnRhKF4edrYG7KAQng:-NXnY_sY7gu8oLz3hVk6:b-lzepel) ([raw file](https://github.com/starkware-libs/cairo/blob/607aa5aa05c92685c09f28f2dc15e48087d0e73f/crates/cairo-lang-starknet/src/abi.rs#L121)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This query depends on the AST. I suggest using module_items() and matching, for all loops on this function
</blockquote></details>

Agreed, adding in another PR on top of this one. Added a TODO for now.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3376#-:-NXncU2BDNDglavdyAud:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3376)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3376#-NXncTHX8cG8ShI3HPug:-NXncTHX8cG8ShI3HPuh:b-3yf84a) (no related file):*
change target branch

___

**Pull request merged**
