### PR TITLE
Added .at() for ByteArray

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3794)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3794)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/byte_array.cairo` line 189 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3794#-Naej4el0iA1Qw-EzVnC:-Naej4em4VehcwPi1skF:b-turedb) ([raw file](https://github.com/starkware-libs/cairo/blob/9b5cb8ae348b7ba8cb381f99b1e91072a3bc6650/corelib/src/byte_array.cairo#L189)):*
> ```Cairo
> 
>     // Returns the byte at the given index, or None if the index is out of bounds.
>     fn at(self: @ByteArray, index: usize) -> Option<u8> {
> ```

add IndexView impl.
___
*[`corelib/src/bytes_31.cairo` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3794#-Naek-C53c5tvJGeAEai:-Naek-C53c5tvJGeAEaj:b-qtldz4) ([raw file](https://github.com/starkware-libs/cairo/blob/9b5cb8ae348b7ba8cb381f99b1e91072a3bc6650/corelib/src/bytes_31.cairo#L18)):*
> ```Cairo
> 
> #[generate_trait]
> impl Bytes31Impl of Bytes31Trait {
> ```

IndexView as well.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3794)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/byte_array.cairo` line 189 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3794#-Naej4el0iA1Qw-EzVnC:-Naf-3oi6uSPkYzKe-Qn:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9b5cb8ae348b7ba8cb381f99b1e91072a3bc6650/corelib/src/byte_array.cairo#L189)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add IndexView impl.
</blockquote></details>

Done.
___
*[`corelib/src/bytes_31.cairo` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3794#-Naek-C53c5tvJGeAEai:-Naf-4D4Ap-35genRI7j:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9b5cb8ae348b7ba8cb381f99b1e91072a3bc6650/corelib/src/bytes_31.cairo#L18)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

IndexView as well.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3794#-:-Nag2Wta7McXo8f3Jp0I:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3794)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
