### PR TITLE
Add ownable component abi tests.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4105)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4105)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @orizi and @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4105#-Nen1nS38Wh8e6l7Pbp6:-Nen1nS38Wh8e6l7Pbp7:b-ouoqi) (no related file):*
Change target branch

___

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4105#-:-Nen68OYByKSULhqQTqg:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4105)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_ownable` line 80 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4105#-NenBEJc4nPQNo-LjEa7:-NercfxC7sjUIiTojXXK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/82626d421dfd733eb38d1814832f479703fb9278/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_ownable#L80)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

blank line
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/test_data/with_ownable.cairo` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4105#-NenBTE63fbhuYdGaOL1:-NercwDNBk8xoVuX6Ggp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/82626d421dfd733eb38d1814832f479703fb9278/crates/cairo-lang-starknet/test_data/with_ownable.cairo#L35)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Needs to be external unless you remove from the interface.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/test_data/with_ownable.cairo` line 74 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4105#-NenCFQ47PNlwwITMKB9:-NercyBn3d2I8PLPsFeG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/82626d421dfd733eb38d1814832f479703fb9278/crates/cairo-lang-starknet/test_data/with_ownable.cairo#L74)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

meaningful names please
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4105)* status: all files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4105#-:-NerqPHkC8BtlZJofdwq:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_ownable` line 15 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4105#-Nerpi_P12gZewGOVjW4:-Nerpi_P12gZewGOVjW5:boqb32x) ([raw file](https://github.com/starkware-libs/cairo/blob/8ceca795f396be8272fc6b259f7c84ca54d99bd9/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_ownable#L15)):*
> ```
> 
> #[starknet::interface]
> trait TransferTrait<TCS> {
> ```

why the change to TCS?
I think TContractState is more readable (I actually want to change it everywhere in our code base)

**Review by yuvalsw — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4105)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Pull request merged**
