### PR TITLE
resolved impl impl

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5839)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 12 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5839)* status: 12 of 13 files reviewed, 4 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference/conform.rs` line 547 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5839#-O-px8Zf0D48GwK5_4Ny:-O-px8Zg8qkJNeuTxd_s:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/4ede6bdca66237dab5f869d06c7d02479a75c78c/crates/cairo-lang-semantic/src/expr/inference/conform.rs#L547)):*
> ```XML
>     }
> 
>     pub fn reduce_impl_impl(
> ```

doc
___
*[`crates/cairo-lang-semantic/src/expr/inference/infers.rs` line 456 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5839#-O-pxGX_3-_DrKjbEb21:-O-pxGX_3-_DrKjbEb22:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/4ede6bdca66237dab5f869d06c7d02479a75c78c/crates/cairo-lang-semantic/src/expr/inference/infers.rs#L456)):*
> ```XML
>     }
>     /// Infers the impl to be substituted instead of a trait for a given trait impl.
>     /// Returns the resulting impl impl.
> ```





_Suggestion:_
```XML
        ImplConstantId::new(impl_id, concrete_trait_constant.trait_constant(self.db), self.db)
    }
    
    /// Infers the impl to be substituted instead of a trait for a given trait impl.
    /// Returns the resulting impl impl.
```
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 203 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5839#-O-pxLXj0Xpvk99myr1R:-O-pxLXj0Xpvk99myr1S:b2ni2nk) ([raw file](https://github.com/starkware-libs/cairo/blob/4ede6bdca66237dab5f869d06c7d02479a75c78c/crates/cairo-lang-semantic/src/items/imp.rs#L203)):*
> ```XML
>             }
>             ImplLongId::ImplImpl(impl_impl) => format!(
>                 "ImplVar({})",
> ```

fix
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 232 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5839#-O-py1qx5envMNaApD-W:-O-py1qy0Nz-hBqiWx-O:b-4jnqj) ([raw file](https://github.com/starkware-libs/cairo/blob/4ede6bdca66237dab5f869d06c7d02479a75c78c/crates/cairo-lang-semantic/src/items/imp.rs#L232)):*
> ```XML
>             ImplLongId::GenericParameter(_) => true,
>             ImplLongId::ImplVar(_) => false,
>             ImplLongId::ImplImpl(_) | ImplLongId::TraitImpl(_) => false,
> ```

is `TraitImpl` not always var free?



_Code quote:_
```XML
            ImplLongId::Concrete(concrete_impl_id) => concrete_impl_id.is_var_free(db),
            ImplLongId::GenericParameter(_) => true,
            ImplLongId::ImplVar(_) => false,
            ImplLongId::ImplImpl(_) | ImplLongId::TraitImpl(_) => false,
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5839)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/inference/conform.rs` line 547 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5839#-O-px8Zf0D48GwK5_4Ny:-O-q-JxbCIVVjZtm3AiV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4ede6bdca66237dab5f869d06c7d02479a75c78c/crates/cairo-lang-semantic/src/expr/inference/conform.rs#L547)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/inference/infers.rs` line 456 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5839#-O-pxGX_3-_DrKjbEb21:-O-q-OpE2xkpN770Ls4G:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4ede6bdca66237dab5f869d06c7d02479a75c78c/crates/cairo-lang-semantic/src/expr/inference/infers.rs#L456)):*
> ```XML
>     }
>     /// Infers the impl to be substituted instead of a trait for a given trait impl.
>     /// Returns the resulting impl impl.
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 232 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5839#-O-py1qx5envMNaApD-W:-O-q0EApBo3NEXFYRk2y:b-80fsbl) ([raw file](https://github.com/starkware-libs/cairo/blob/4ede6bdca66237dab5f869d06c7d02479a75c78c/crates/cairo-lang-semantic/src/items/imp.rs#L232)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is `TraitImpl` not always var free?
</blockquote></details>

what if the trait has var generic params? and TraitType also returns not var free

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5839)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 232 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5839#-O-py1qx5envMNaApD-W:-O-q22MG8sVTl3gx577C:bs7if2o) ([raw file](https://github.com/starkware-libs/cairo/blob/4ede6bdca66237dab5f869d06c7d02479a75c78c/crates/cairo-lang-semantic/src/items/imp.rs#L232)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

what if the trait has var generic params? and TraitType also returns not var free
</blockquote></details>

trait impl is only generated from `Self` - so can't have vars.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5839)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 203 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5839#-O-pxLXj0Xpvk99myr1R:-O-q0c9rDMTZWZiKRnMK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4ede6bdca66237dab5f869d06c7d02479a75c78c/crates/cairo-lang-semantic/src/items/imp.rs#L203)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 232 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5839#-O-py1qx5envMNaApD-W:-O-q6w7ZBXYjZUzbjE4Z:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4ede6bdca66237dab5f869d06c7d02479a75c78c/crates/cairo-lang-semantic/src/items/imp.rs#L232)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

trait impl is only generated from `Self` - so can't have vars.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5839)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request closed without merging**
