### PR TITLE
Return statement source location when compiling to Sierra.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
**Stack**:
- #4878
- #4877
- #4876
- #4854
- #4853 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4853)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4853)* status: 2 of 11 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/bin/cairo-run/src/main.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4853#-Nofotxj91H3Lpz3SNvX:-Nofotxk1sbpPnKSDe8S:b-y4djsc) ([raw file](https://github.com/starkware-libs/cairo/blob/e220f092184c85f89e47ea65c488627c96da439e/crates/bin/cairo-run/src/main.rs#L64)):*
> ```XML
>         .to_option()
>         .with_context(|| "Compilation failed without any diagnostics.")?
>         .0;
> ```

and everywhere.



_Suggestion:_
```XML
    let (sierra_program, _statement_locations) = db
        .get_sierra_program(main_crate_ids.clone())
        .to_option()
        .with_context(|| "Compilation failed without any diagnostics.")?;
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 11 files at r1, 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4853)* status: 3 of 11 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4853)* status: 2 of 11 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/bin/cairo-run/src/main.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4853#-Nofotxj91H3Lpz3SNvX:-Nogg6XJ4eLBl7HamW0w:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e220f092184c85f89e47ea65c488627c96da439e/crates/bin/cairo-run/src/main.rs#L64)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

and everywhere.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4853#-:-Nogi6u_0kqzW0vJM3Om:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4853)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
