### PR TITLE
LS: Limit module import completion to visible members

### PR DESCRIPTION
**Pull request by integraledelebesgue**

### CODE REVIEW

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6566)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @integraledelebesgue, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/tests/test_data/completions/module_items.txt` line 18 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6566#-OAqZbIk7KN3QDa2YVYz:-OAqZbIk7KN3QDa2YVZ-:bcm0ebr) ([raw file](https://github.com/starkware-libs/cairo/blob/d2ba3602f59b401d7d53b424662c075c35530d4e/crates/cairo-lang-language-server/tests/test_data/completions/module_items.txt#L18)):*
> ```help
>         fn some_method(self: @T);
>     }
>     
> ```

please trim whitespace in empty lines

**Review by integraledelebesgue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6566)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/tests/test_data/completions/module_items.txt` line 18 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6566#-OAqZbIk7KN3QDa2YVYz:-OArLfSpDQblcLRS_-GE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d2ba3602f59b401d7d53b424662c075c35530d4e/crates/cairo-lang-language-server/tests/test_data/completions/module_items.txt#L18)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

please trim whitespace in empty lines
</blockquote></details>

Done.

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6566#-:-OAvQe8_6wwceBaYa8Q2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6566#-:-OAx8x226mWNBg0oQFe8:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @piotmag769)

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6566)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @piotmag769)

**Review by piotmag769 — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6566#-:-OB0m4vZEcioidYnWYeg:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, and @integraledelebesgue)

___
*[`crates/cairo-lang-language-server/tests/test_data/completions/module_items.txt` line 51 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6566#-OB0wRB14Pq2Mmp8w-lu:-OB0wRB14Pq2Mmp8w-lv:b-vj3cl) ([raw file](https://github.com/starkware-libs/cairo/blob/10fd176b44b1f96600e6cfd70e0437c97714b050/crates/cairo-lang-language-server/tests/test_data/completions/module_items.txt#L51)):*
> ```help
> use non_exporting_module::<caret>
> --------------------------
> Completion: core
> ```

Is that supposed to happen?
___
*[`crates/cairo-lang-language-server/tests/test_data/completions/module_items.txt` line 61 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6566#-OB0w9ZnB8ebAPcL1e_8:-OB0w9ZnB8ebAPcL1e_9:bn48mps) ([raw file](https://github.com/starkware-libs/cairo/blob/10fd176b44b1f96600e6cfd70e0437c97714b050/crates/cairo-lang-language-server/tests/test_data/completions/module_items.txt#L61)):*
> ```help
> Completion: nested_module
> --------------------------
> Completion:
> ```

Why are there empty completions?

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6566)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, and @integraledelebesgue)

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6566)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, and @integraledelebesgue)

**Review by integraledelebesgue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6566)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, and @piotmag769)

___
*[`crates/cairo-lang-language-server/tests/test_data/completions/module_items.txt` line 51 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6566#-OB0wRB14Pq2Mmp8w-lu:-OBASNbJ4B-ohvOYxLfK:bpklld8) ([raw file](https://github.com/starkware-libs/cairo/blob/10fd176b44b1f96600e6cfd70e0437c97714b050/crates/cairo-lang-language-server/tests/test_data/completions/module_items.txt#L51)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Is that supposed to happen?
</blockquote></details>

That's a [`generic_completions`](https://github.com/starkware-libs/cairo/blob/10fd176b44b1f96600e6cfd70e0437c97714b050/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L31) output which occurs because [this check](https://github.com/starkware-libs/cairo/blob/10fd176b44b1f96600e6cfd70e0437c97714b050/crates/cairo-lang-language-server/src/ide/completion/mod.rs#L45) fails
___
*[`crates/cairo-lang-language-server/tests/test_data/completions/module_items.txt` line 61 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6566#-OB0w9ZnB8ebAPcL1e_8:-OBATF171jIUxxR1ggoU:b4wvoow) ([raw file](https://github.com/starkware-libs/cairo/blob/10fd176b44b1f96600e6cfd70e0437c97714b050/crates/cairo-lang-language-server/tests/test_data/completions/module_items.txt#L61)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Why are there empty completions?
</blockquote></details>

These are module items obtained [here](https://github.com/starkware-libs/cairo/blob/10fd176b44b1f96600e6cfd70e0437c97714b050/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L46). I don't know why they are empty though

**Review by piotmag769 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6566)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, and @mkaput)

___
*[`crates/cairo-lang-language-server/tests/test_data/completions/module_items.txt` line 51 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6566#-OB0wRB14Pq2Mmp8w-lu:-OBdmEo18vWids-ODkj-:b-yrphu7) ([raw file](https://github.com/starkware-libs/cairo/blob/10fd176b44b1f96600e6cfd70e0437c97714b050/crates/cairo-lang-language-server/tests/test_data/completions/module_items.txt#L51)):*
<details><summary><i>Previously, integraledelebesgue (Jan Smółka) wrote…</i></summary><blockquote>

That's a [`generic_completions`](https://github.com/starkware-libs/cairo/blob/10fd176b44b1f96600e6cfd70e0437c97714b050/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L31) output which occurs because [this check](https://github.com/starkware-libs/cairo/blob/10fd176b44b1f96600e6cfd70e0437c97714b050/crates/cairo-lang-language-server/src/ide/completion/mod.rs#L45) fails
</blockquote></details>

Is it right? It doesn't seems so. Maybe we should have an issue for that? cc @mkaput 
___
*[`crates/cairo-lang-language-server/tests/test_data/completions/module_items.txt` line 61 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6566#-OB0w9ZnB8ebAPcL1e_8:-OBdmXzSD51jqyf0qiA6:b-snkco1) ([raw file](https://github.com/starkware-libs/cairo/blob/10fd176b44b1f96600e6cfd70e0437c97714b050/crates/cairo-lang-language-server/tests/test_data/completions/module_items.txt#L61)):*
<details><summary><i>Previously, integraledelebesgue (Jan Smółka) wrote…</i></summary><blockquote>

These are module items obtained [here](https://github.com/starkware-libs/cairo/blob/10fd176b44b1f96600e6cfd70e0437c97714b050/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L46). I don't know why they are empty though
</blockquote></details>

Please create an issue for that :pray:

**Review by integraledelebesgue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6566)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-language-server/tests/test_data/completions/module_items.txt` line 51 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6566#-OB0wRB14Pq2Mmp8w-lu:-OBexyHw7lfHY1PrzSaU:b-eahnvg) ([raw file](https://github.com/starkware-libs/cairo/blob/10fd176b44b1f96600e6cfd70e0437c97714b050/crates/cairo-lang-language-server/tests/test_data/completions/module_items.txt#L51)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Is it right? It doesn't seems so. Maybe we should have an issue for that? cc @mkaput
</blockquote></details>

Done  - problem was caused by the fixture itself (lacking semicolons on ends of lines)
___
*[`crates/cairo-lang-language-server/tests/test_data/completions/module_items.txt` line 61 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6566#-OB0w9ZnB8ebAPcL1e_8:-OBeyFBc85khF1RshKmd:b3rrnzm) ([raw file](https://github.com/starkware-libs/cairo/blob/10fd176b44b1f96600e6cfd70e0437c97714b050/crates/cairo-lang-language-server/tests/test_data/completions/module_items.txt#L61)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Please create an issue for that :pray:
</blockquote></details>

Done - same reason as above :)

**Review by piotmag769 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6566#-:-OBf0j0B1YazT9QYDsQ3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)

**Review by mkaput — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6566)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)

**Review by mkaput — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6566)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)

**Pull request merged**
