### PR TITLE
Commit all Antora files for Cairo 1

### PR DESCRIPTION
**Pull request by JameStark**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2716)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 253 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2716)* status: 5 of 253 files reviewed, 1 unresolved discussion (waiting on @JameStark)

___
*[`docs/reference/src/antora-playbook.yml` line 30 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2716#-NSBik5x7RYAWJMoNI3d:-NSBik5x7RYAWJMoNI3e:bbk13x0) ([raw file](https://github.com/starkware-libs/cairo/blob/333f9e320b7bd6dbf5bcb346cd7b3420e7bbc1d4/docs/reference/src/antora-playbook.yml#L30)):*
> ```YAML
>   - provider: fs
>     path: ./public_html/
>     clean: true
> ```

add newline - unless this breaks things.



_Code quote:_
```YAML
    path: ./public_html/
    clean: true
```

**Review by JameStark — COMMENTED** [review]
> Reviewed 242 of 253 files at r1, 11 of 11 files at r2, 31 of 31 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2716)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`docs/reference/src/antora-playbook.yml` line 30 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2716#-NSBik5x7RYAWJMoNI3d:-NSBp9PX4yEWPIWWIO3x:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/333f9e320b7bd6dbf5bcb346cd7b3420e7bbc1d4/docs/reference/src/antora-playbook.yml#L30)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add newline - unless this breaks things.
</blockquote></details>

Done.

**Review by JameStark — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2716)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by JameStark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2716)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`docs/reference/src/antora-playbook.yml` line 30 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2716#-NSBik5x7RYAWJMoNI3d:-NSBpsA56LXxYjNcI5Xw:bytrzk6) ([raw file](https://github.com/starkware-libs/cairo/blob/333f9e320b7bd6dbf5bcb346cd7b3420e7bbc1d4/docs/reference/src/antora-playbook.yml#L30)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@orizi

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2716)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JameStark)

**Review by spapinistarkware — COMMENTED** [review]
You deleted existing doc and didnt add it. for example functions.adoc. Please make sure you dont undo docs we are adding

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2716#-:-NSBxx1j54J52kevrJmt:b-fby9eq)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JameStark)

**Review by JameStark — COMMENTED** [review]
These were duplicate files. 

The new location for them should be in this dir:
cairo/docs/reference/src/cairo/modules/ROOT/pages/ (so that they work with Antora)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2716#-:-NSC9erm-0iLHvH7LTq0:bai8jlj)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JameStark)

**Review by orizi — APPROVED** [review]
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2716)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JameStark)

**Review by spapinistarkware — COMMENTED** [review]
Look again. You deleted functions but didnt add them under the new directory.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2716#-:-NSCcvOr2NVDCilpkyLQ:b-h012xs)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JameStark)

**Review by JameStark — COMMENTED** [review]
My mistake. I will go back and cross reference the two dirs and make sure everything is copied across to the new location

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2716#-:-NSCdrn0Dkt7uUiBVNrf:b10846v)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JameStark)

**Review by JameStark — COMMENTED** [review]
> Reviewed 6 of 6 files at r5, 11 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2716)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JameStark)

**Review by JameStark — COMMENTED** [review]
All recently added files have been moved to the Antora file structure: 
cairo/docs/reference/src/cairo/modules/ROOT/pages/

This should be as expected now @spapinistarkware 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2716#-:-NSFFbfk3gk8lBjj9YjN:bmbt04x)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JameStark)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 31 of 31 files at r3, 1 of 1 files at r4, 6 of 6 files at r5, 11 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2716#-:-NSFGqQz06K0Pmlg1Nda:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JameStark)

**Pull request merged**
