### PR TITLE
Fixed plugins to be able to affect the same virtual module.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:a00d504f

---

**Stack**:
- #1094
- #1080
- #1077
- #1076 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1076)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/defs/src/db.rs` line 241 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1076#-NHrnzeu1xpXfQIP4ZiO:-NHrnzeu1xpXfQIP4ZiP:bw1yp4g) ([raw file](https://github.com/starkware-libs/cairo/blob/11c1c9ca99d6c0705e9bc8a6debf3a1c212c33a1/crates/defs/src/db.rs#L241)):*
> ```XML
>         for item_ast in db.module_syntax(module_id)?.items(syntax_db).elements(syntax_db) {
>             let Some((name, content)) = plugin.generate_code(db.upcast(), item_ast) else {continue};
>             match virtual_modules.entry((module_id, name)) {
> ```

This is always the same in this scope, why is it part of the key?



_Code quote:_
```XML
module_id
```
___
*[`crates/defs/src/db.rs` line 241 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1076#-NHroEHEEBM84vpD6FXl:-NHroEHEEBM84vpD6FXm:blzflzn) ([raw file](https://github.com/starkware-libs/cairo/blob/11c1c9ca99d6c0705e9bc8a6debf3a1c212c33a1/crates/defs/src/db.rs#L241)):*
> ```XML
>         for item_ast in db.module_syntax(module_id)?.items(syntax_db).elements(syntax_db) {
>             let Some((name, content)) = plugin.generate_code(db.upcast(), item_ast) else {continue};
>             match virtual_modules.entry((module_id, name)) {
> ```

I don't think this is enouh isolation. I would also isolate by plugin.



_Code quote:_
```XML
name
```

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1076)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1076)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/defs/src/db.rs` line 241 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1076#-NHrnzeu1xpXfQIP4ZiO:-NHrtHl2EVhAgfcZL3EK:b-tp8qu3) ([raw file](https://github.com/starkware-libs/cairo/blob/a51d023b3eed7d67fe61b2dd4f279acf97243dc1/crates/defs/src/db.rs#L241)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This is always the same in this scope, why is it part of the key?
</blockquote></details>

you are correct - haven't notived - fixing.
___
*[`crates/defs/src/db.rs` line 241 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1076#-NHroEHEEBM84vpD6FXl:-NHrtMor2Z6H5_TvB8uK:b-8e54om) ([raw file](https://github.com/starkware-libs/cairo/blob/a51d023b3eed7d67fe61b2dd4f279acf97243dc1/crates/defs/src/db.rs#L241)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I don't think this is enouh isolation. I would also isolate by plugin.
</blockquote></details>

but this way different plugins would override each other.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1076#-:-NHsh2-j17kVaXipiT83:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
