### PR TITLE
Add tuple types documentation.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3100)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3100)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/tuple-types.adoc` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3100#-NV-juTb9GV0sCptK_OP:-NV-juTb9GV0sCptK_OQ:bm0hv7) ([raw file](https://github.com/starkware-libs/cairo/blob/29ee3363abfdeda2b2df74fbdbeb01ce9dfbcbef/docs/reference/src/components/cairo/modules/language_constructs/pages/tuple-types.adoc#L12)):*
> ```AsciiDoc
> () // Unit type.
> (u32, u256)
> (felt252, u16, Option<u8>)
> ```

add the single element tuple as well.



_Suggestion:_
```AsciiDoc
(u128,)
(u32, u256)
(felt252, u16, Option<u8>)
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3100)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/tuple-types.adoc` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3100#-NV-juTb9GV0sCptK_OP:-NV-ltGOCWRO4_CCOGBF:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/29ee3363abfdeda2b2df74fbdbeb01ce9dfbcbef/docs/reference/src/components/cairo/modules/language_constructs/pages/tuple-types.adoc#L12)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add the single element tuple as well.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3100)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3100)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3100)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3100#-:-NV3TGQc2FSJJbo76zNn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3100)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
