### PR TITLE
cast ints to bouneded_ints in match statements

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4889)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4889)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 2121 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4889#-NoqUfof52vgA06kzp6e:-NoqUfof52vgA06kzp6f:b-l6mkjh) ([raw file](https://github.com/starkware-libs/cairo/blob/3edaa85ffa5dfba4baac02261124b4ff73c63a47/crates/cairo-lang-lowering/src/lower/mod.rs#L2121)):*
> ```XML
> /// Lowers an expression of type [semantic::ExprMatch] where the matched expression is a felt252.
> /// using an index enum to create a jump table.
> fn lower_expr_match_felt252(
> ```

rename

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4889)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 2121 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4889#-NoqUfof52vgA06kzp6e:-NoqXIdxEOI6xMxcKe_u:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3edaa85ffa5dfba4baac02261124b4ff73c63a47/crates/cairo-lang-lowering/src/lower/mod.rs#L2121)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rename
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4889)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 2129 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4889#-Noqa5KD5n5YlB7zon6T:-Noqa5KD5n5YlB7zon6U:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2f51d4046c6fec0c839c843293383f5b3c7c7fab/crates/cairo-lang-lowering/src/lower/mod.rs#L2129)):*
> ```XML
>     convert_function: Option<FunctionId>,
> ) -> LoweringResult<LoweredExpr> {
>     log::trace!("Lowering a match-felt252 expression.");
> ```





_Suggestion:_
```XML
/// Lowers an expression of type [semantic::ExprMatch] where the matched expression is a numeric
/// type. If the matched expression is not felt252 and the matched is performed using an if-else
/// construct, the expression is converted into felt252 using `into_felt252`.
fn lower_expr_match_numeric(
    ctx: &mut LoweringContext<'_, '_>,
    expr: &semantic::ExprMatch,
    match_input: VarUsage,
    builder: &mut BlockBuilder,
    into_felt252: Option<FunctionId>,
) -> LoweringResult<LoweredExpr> {
    log::trace!("Lowering a match-felt252 expression.");
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4889)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 2129 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4889#-Noqa5KD5n5YlB7zon6T:-NoqdZmi41TZARu0guHJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2f51d4046c6fec0c839c843293383f5b3c7c7fab/crates/cairo-lang-lowering/src/lower/mod.rs#L2129)):*
> ```XML
>     convert_function: Option<FunctionId>,
> ) -> LoweringResult<LoweredExpr> {
>     log::trace!("Lowering a match-felt252 expression.");
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4889#-:-NoqfZmb9iqXXsOdZt5B:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
