### PR TITLE
LS: Add "fill struct fields" code action

### PR DESCRIPTION
**Pull request by integraledelebesgue**
**Stack**:
- #6566
- #6565 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by integraledelebesgue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6565)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6565#-OAYczzxEI2gAo7_9f1C:-OAYczzxEI2gAo7_9f1D:b-i7oqa4) (no related file):*
I'm still working on this feature and e2e tests for it.

___

**Review by piotmag769 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6565)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/src/ide/code_actions/mod.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6565#-OA_d2VrEhOI_DEQ1g-M:-OA_d2VrEhOI_DEQ1g-N:b-ag2wpb) ([raw file](https://github.com/starkware-libs/cairo/blob/c8120436c11243fc7d8b7ac9636aae7a71025186/crates/cairo-lang-language-server/src/ide/code_actions/mod.rs#L34)):*
> ```XML
>     );
>     actions.extend(
>         fill_struct_members::fill_struct_members(db, node.clone(), &params)
> ```

Shouldn't it be based on a diagnostic like in the loop above? This way you don't have to redetermine if it's needed.
Will require assigning error code to `SemanticDiagnosticKind::MissingMember` in `SemanticDiagnosticKind::error_code`

**Review by mkaput — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6565)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, and @orizi)

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6565)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, and @orizi)

___
*[`crates/cairo-lang-language-server/src/ide/code_actions/fill_struct_members.rs` line 47 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6565#-OArSQmsDJxiTZX1JndI:-OArQdK4DS6RkPOBsrgv:bj3jdjx) ([raw file](https://github.com/starkware-libs/cairo/blob/70595cd0401104388c381d501ef016449893ff9e/crates/cairo-lang-language-server/src/ide/code_actions/fill_struct_members.rs#L47)):*
> ```XML
>     // We will heuristically indent all subsequent arguments identically
>     // to how the first of them is indented.
>     let indentation = first_argument
> ```

I think let's avoid doing any heuristics here, so that we won't accumulate cruft. I have an idea for a generic algorithm for formatting textedits and we should just implement it if we decide to format these.

**Review by mkaput — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6565)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, and @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6565)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @mkaput, and @piotmag769)

**Review by integraledelebesgue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6565)* status: 1 of 7 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/code_actions/mod.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6565#-OA_d2VrEhOI_DEQ1g-M:-OAxJn6LATXrHeZIaWmw:b-7844fg) ([raw file](https://github.com/starkware-libs/cairo/blob/c8120436c11243fc7d8b7ac9636aae7a71025186/crates/cairo-lang-language-server/src/ide/code_actions/mod.rs#L34)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Shouldn't it be based on a diagnostic like in the loop above? This way you don't have to redetermine if it's needed.
Will require assigning error code to `SemanticDiagnosticKind::MissingMember` in `SemanticDiagnosticKind::error_code`
</blockquote></details>

Sure, I introduced new diagnostic code and included it in the implementation. My code action works a bit different than other actions. Every missing member produces a distinct diagnostic - they need to be collected and "debounced"
___
*[`crates/cairo-lang-language-server/src/ide/code_actions/fill_struct_members.rs` line 47 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6565#-OArSQmsDJxiTZX1JndI:-OAxJL2bBoZKPhSl49fU:b-pshkzh) ([raw file](https://github.com/starkware-libs/cairo/blob/70595cd0401104388c381d501ef016449893ff9e/crates/cairo-lang-language-server/src/ide/code_actions/fill_struct_members.rs#L47)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I think let's avoid doing any heuristics here, so that we won't accumulate cruft. I have an idea for a generic algorithm for formatting textedits and we should just implement it if we decide to format these.
</blockquote></details>

I simplified my implementation. Now it performs only necessary edits without heuristics related to formatting

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6565)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/code_actions/mod.rs` line 33 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6565#-OB-SjQF9fAFeFpOgh09:-OB-SjQF9fAFeFpOgh0A:b9v5b4d) ([raw file](https://github.com/starkware-libs/cairo/blob/388f717356dcd5556068df85866be1b7c867154c/crates/cairo-lang-language-server/src/ide/code_actions/mod.rs#L33)):*
> ```XML
>         expand_macro::expand_macro(db, node.clone()).into_iter().map(CodeActionOrCommand::from),
>     );
>     actions.extend(
> ```

you should rather expand this function now: https://github.com/starkware-libs/cairo/blob/02fca5c68442cff93a0858c4743c673386e0290d/crates/cairo-lang-language-server/src/ide/code_actions/mod.rs#L33-L78

**Review by integraledelebesgue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6565)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/code_actions/mod.rs` line 33 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6565#-OB-SjQF9fAFeFpOgh09:-OB-djiFDxO20kbedp7u:b-yol97c) ([raw file](https://github.com/starkware-libs/cairo/blob/388f717356dcd5556068df85866be1b7c867154c/crates/cairo-lang-language-server/src/ide/code_actions/mod.rs#L33)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

you should rather expand this function now: https://github.com/starkware-libs/cairo/blob/02fca5c68442cff93a0858c4743c673386e0290d/crates/cairo-lang-language-server/src/ide/code_actions/mod.rs#L33-L78
</blockquote></details>

As I already written [here](https://reviewable.io/reviews/starkware-libs/cairo/6565#-OA_d2VrEhOI_DEQ1g-M), handlng diagnostics the way this funtion does doesn't really work in my case - one struct to complete requires filtering out a few related diagnostics.
I can rebuild this function to process a whole list of diagnostics

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 2 of 6 files at r5.
> Dismissed @mkaput from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6565#-:-OB-ihNSCfhhqiGR_gx6:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/code_actions/mod.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6565#-OA_d2VrEhOI_DEQ1g-M:-OB-i6et8-l2it9dfoih:b-pbv59n) ([raw file](https://github.com/starkware-libs/cairo/blob/c8120436c11243fc7d8b7ac9636aae7a71025186/crates/cairo-lang-language-server/src/ide/code_actions/mod.rs#L34)):*
<details><summary><i>Previously, integraledelebesgue (Jan Smółka) wrote…</i></summary><blockquote>

Sure, I introduced new diagnostic code and included it in the implementation. My code action works a bit different than other actions. Every missing member produces a distinct diagnostic - they need to be collected and "debounced"
</blockquote></details>

OK, your point makes sense. I am starting to think we're getting into smelly code by having two ways of adding actions here, and this `action fn * extend` approach appears to be more scalable than `get_code_actions_for_diagnostic`. Migrating `get_code_actions_for_diagnostic` into this `extend` pattern? If it's ok, then I'll create an issue.
___
*[`crates/cairo-lang-language-server/src/ide/code_actions/mod.rs` line 33 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6565#-OB-SjQF9fAFeFpOgh09:-OB-fO8C7xkuLcGuD-Db:bwopi3p) ([raw file](https://github.com/starkware-libs/cairo/blob/388f717356dcd5556068df85866be1b7c867154c/crates/cairo-lang-language-server/src/ide/code_actions/mod.rs#L33)):*
<details><summary><i>Previously, integraledelebesgue (Jan Smółka) wrote…</i></summary><blockquote>

As I already written [here](https://reviewable.io/reviews/starkware-libs/cairo/6565#-OA_d2VrEhOI_DEQ1g-M), handlng diagnostics the way this funtion does doesn't really work in my case - one struct to complete requires filtering out a few related diagnostics.
I can rebuild this function to process a whole list of diagnostics
</blockquote></details>

oh, I didn't read that thread, sorry :sweat_smile: will continue there

**Review by integraledelebesgue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6565)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/code_actions/mod.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6565#-OA_d2VrEhOI_DEQ1g-M:-OB00XGlBkiCs51DX3nQ:b-pr3lg4) ([raw file](https://github.com/starkware-libs/cairo/blob/c8120436c11243fc7d8b7ac9636aae7a71025186/crates/cairo-lang-language-server/src/ide/code_actions/mod.rs#L34)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

OK, your point makes sense. I am starting to think we're getting into smelly code by having two ways of adding actions here, and this `action fn * extend` approach appears to be more scalable than `get_code_actions_for_diagnostic`. Migrating `get_code_actions_for_diagnostic` into this `extend` pattern? If it's ok, then I'll create an issue.
</blockquote></details>

In the meantime I redesigned `get_code_actions_for_diagnostic` - now it's more flexible. Please have a look and let me know if that's a good solution

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6565#-:-OB0HO4Q7XdoR6HJ9jdI:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/code_actions/mod.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6565#-OA_d2VrEhOI_DEQ1g-M:-OB0HGctBRLTpv4PTymD:b-bx9r6x) ([raw file](https://github.com/starkware-libs/cairo/blob/c8120436c11243fc7d8b7ac9636aae7a71025186/crates/cairo-lang-language-server/src/ide/code_actions/mod.rs#L34)):*
<details><summary><i>Previously, integraledelebesgue (Jan Smółka) wrote…</i></summary><blockquote>

In the meantime I redesigned `get_code_actions_for_diagnostic` - now it's more flexible. Please have a look and let me know if that's a good solution
</blockquote></details>

looks good as well!

**Review by mkaput — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6565)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, and @piotmag769)

**Review by piotmag769 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r5, 1 of 1 files at r6, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6565)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, and @integraledelebesgue)

___
*[`crates/cairo-lang-language-server/src/ide/code_actions/mod.rs` line 39 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6565#-OB0ZFDI5AatdV1pt58C:-OB0ZFDI5AatdV1pt58D:b4je7w0) ([raw file](https://github.com/starkware-libs/cairo/blob/5b02f1dd8df44b8e1f321bd60b3a612fffc55bd8/crates/cairo-lang-language-server/src/ide/code_actions/mod.rs#L39)):*
> ```XML
> 
> /// Extracts [`Diagnostic`] code if it's given as a string, returns None otherwise.
> fn resolve_code(diagnostic: &Diagnostic) -> Option<&str> {
> ```

1. Should be defined below `get_code_actions_for_diagnostics`
2. Doesn't resolve anything, more like `extract_diagnostic_code`
___
*[`crates/cairo-lang-language-server/src/ide/code_actions/mod.rs` line 43 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6565#-OB0___71gT42uIkNDSm:-OB0___71gT42uIkNDSn:b-jq8lcr) ([raw file](https://github.com/starkware-libs/cairo/blob/5b02f1dd8df44b8e1f321bd60b3a612fffc55bd8/crates/cairo-lang-language-server/src/ide/code_actions/mod.rs#L43)):*
> ```XML
>         Some(NumberOrString::String(code)) => Some(code),
>         Some(NumberOrString::Number(code)) => {
>             debug!("diagnostic code is not a string: `{code}`");
> ```

`warn` imo? Shouldn't happen I guess
___
*[`crates/cairo-lang-language-server/src/ide/code_actions/mod.rs` line 47 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6565#-OB0_z7IA2rKaK5p4KAM:-OB0_z7IA2rKaK5p4KAN:b-e1zadx) ([raw file](https://github.com/starkware-libs/cairo/blob/5b02f1dd8df44b8e1f321bd60b3a612fffc55bd8/crates/cairo-lang-language-server/src/ide/code_actions/mod.rs#L47)):*
> ```XML
>         }
>         None => {
>             debug!("diagnostic code is missing");
> ```

Not worth logging it, most diagnostics don't have codes
___
*[`crates/cairo-lang-language-server/tests/test_data/code_actions/fill_struct_fields.txt` line 57 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6565#-OB0c9PB6PSZCNO02Ncs:-OB0c9PB6PSZCNO02Nct:bpfjr6e) ([raw file](https://github.com/starkware-libs/cairo/blob/5b02f1dd8df44b8e1f321bd60b3a612fffc55bd8/crates/cairo-lang-language-server/tests/test_data/code_actions/fill_struct_fields.txt#L57)):*
> ```help
> Add new text: " x: (), y: (), z: ()"
> At: Range { start: Position { line: 14, character: 24 }, end: Position { line: 14, character: 24 } }
> Title: Rename to `_  `
> ```

This shouldn't appear here :thinking:

**Review by piotmag769 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6565)* status: all files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, and @integraledelebesgue)

___
*[`crates/cairo-lang-language-server/src/ide/code_actions/fill_struct_fields.rs` line 40 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6565#-OB0eJcK5UnWRK0wVB6b:-OB0eJcK5UnWRK0wVB6c:bl4j3gn) ([raw file](https://github.com/starkware-libs/cairo/blob/5b02f1dd8df44b8e1f321bd60b3a612fffc55bd8/crates/cairo-lang-language-server/src/ide/code_actions/fill_struct_fields.rs#L40)):*
> ```XML
> 
>     let concrete_struct_id = constructor_semantic.concrete_struct_id;
>     let struct_parent_module_id = concrete_struct_id.struct_id(db).parent_module(db);
> ```

Please extract stuff closer to where it is actually used. Reading the code I have to jump to find references

**Review by integraledelebesgue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6565)* status: 5 of 7 files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/code_actions/fill_struct_fields.rs` line 40 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6565#-OB0eJcK5UnWRK0wVB6b:-OBAdxDt6nZfsPl3Ep5P:bs8a1ox) ([raw file](https://github.com/starkware-libs/cairo/blob/5b02f1dd8df44b8e1f321bd60b3a612fffc55bd8/crates/cairo-lang-language-server/src/ide/code_actions/fill_struct_fields.rs#L40)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Please extract stuff closer to where it is actually used. Reading the code I have to jump to find references
</blockquote></details>

I reorganized stuff as far as topological order allows :)
___
*[`crates/cairo-lang-language-server/src/ide/code_actions/mod.rs` line 39 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6565#-OB0ZFDI5AatdV1pt58C:-OBAe1ik0-21F98tXipQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5b02f1dd8df44b8e1f321bd60b3a612fffc55bd8/crates/cairo-lang-language-server/src/ide/code_actions/mod.rs#L39)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

1. Should be defined below `get_code_actions_for_diagnostics`
2. Doesn't resolve anything, more like `extract_diagnostic_code`
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/ide/code_actions/mod.rs` line 43 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6565#-OB0___71gT42uIkNDSm:-OBAe20c7b9s95TruxXN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5b02f1dd8df44b8e1f321bd60b3a612fffc55bd8/crates/cairo-lang-language-server/src/ide/code_actions/mod.rs#L43)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

`warn` imo? Shouldn't happen I guess
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/ide/code_actions/mod.rs` line 47 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6565#-OB0_z7IA2rKaK5p4KAM:-OBAe2ZH7DLPI5SQy4E7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5b02f1dd8df44b8e1f321bd60b3a612fffc55bd8/crates/cairo-lang-language-server/src/ide/code_actions/mod.rs#L47)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Not worth logging it, most diagnostics don't have codes
</blockquote></details>

Done.

**Review by integraledelebesgue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6565)* status: 4 of 7 files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-language-server/tests/test_data/code_actions/fill_struct_fields.txt` line 57 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6565#-OB0c9PB6PSZCNO02Ncs:-OBAeC7rDjFDlaD4DWwJ:b57bmfn) ([raw file](https://github.com/starkware-libs/cairo/blob/5b02f1dd8df44b8e1f321bd60b3a612fffc55bd8/crates/cairo-lang-language-server/tests/test_data/code_actions/fill_struct_fields.txt#L57)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

This shouldn't appear here :thinking:
</blockquote></details>

Indeed - I changed variable names to not generate "unused variable" diangostics

**Review by mkaput — APPROVED** [review]
> Reviewed 2 of 2 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6565)* status: all files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, and @piotmag769)

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 1 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6565)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, and @integraledelebesgue)

___
*[`crates/cairo-lang-language-server/src/ide/code_actions/fill_struct_fields.rs` line 75 at r10](https://reviewable.io/reviews/starkware-libs/cairo/6565#-OBebQn081nnuPOEh66c:-OBebQn081nnuPOEh66d:btvljlc) ([raw file](https://github.com/starkware-libs/cairo/blob/f0428b665c5ce54f44e79fe853a23f4cf0023b52/crates/cairo-lang-language-server/src/ide/code_actions/fill_struct_fields.rs#L75)):*
> ```XML
>     let struct_parent_module_id = concrete_struct_id.struct_id(db).parent_module(db);
> 
>     let arguments_to_complete = concrete_struct_members(db, concrete_struct_id)
> ```

This is a query, use it as one



_Suggestion:_
```XML
db.concrete_struct_members(concrete_struct_id)
```

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6565)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, and @integraledelebesgue)

**Review by integraledelebesgue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6565)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/code_actions/fill_struct_fields.rs` line 36 at r10](https://reviewable.io/reviews/starkware-libs/cairo/6565#-OBeY9zU8NoxdX1fzKfZ:-OBf1xhr5zMk0oTuETk7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f0428b665c5ce54f44e79fe853a23f4cf0023b52/crates/cairo-lang-language-server/src/ide/code_actions/fill_struct_fields.rs#L36)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Prob worth logging an error here, it should never happen
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/ide/code_actions/fill_struct_fields.rs` line 75 at r10](https://reviewable.io/reviews/starkware-libs/cairo/6565#-OBebQn081nnuPOEh66c:-OBf1xCkB1HMhZoIpnp2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f0428b665c5ce54f44e79fe853a23f4cf0023b52/crates/cairo-lang-language-server/src/ide/code_actions/fill_struct_fields.rs#L75)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

This is a query, use it as one
</blockquote></details>

Done.

**Review by piotmag769 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6565)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)

**Review by mkaput — APPROVED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6565)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)

**Review by mkaput — APPROVED** [review]
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6565)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)

**Comment by integraledelebesgue** [comment]
✓ Commit merged in pull request [#6566](https://github.com/starkware-libs/cairo/pull/6566)

**Pull request merged**
