### PR TITLE
Find imported contracts

### PR DESCRIPTION
**Pull request by maciektr**
This change is meant to allow users to compile contracts imported from cairo dependencies.

In case of Cairo projects that use Cairo packages defining some contracts as dependencies, we want to allow users to deploy contracts from those dependencies within their own project. For that, we need to have a mechanism that allows their compilation.  

This PR suggests compiling contracts that are imported with `use` directive within a Cairo project.

This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3524)

### CODE REVIEW

**Review by mkaput — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3524)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @maciektr and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3524#-NYvvWjs1sZJx5pEUhQ7:-NYvvWjs1sZJx5pEUhQ8:ba46ocv) (no related file):*
Please write in issue description what is this for, because while I do know, the rest of us probably does not :) 

___

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3524)* status: all files reviewed, 2 unresolved discussions (waiting on @maciektr and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/contract_test.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3524#-NYvxU0CDhlWqLDQhApz:-NYvxU0CDhlWqLDQhAq-:b-edmhue) ([raw file](https://github.com/starkware-libs/cairo/blob/475df78925d29d74c940f00eaf01f760432cff5d/crates/cairo-lang-starknet/src/contract_test.rs#L114)):*
> ```XML
>     );
>     let contracts = find_contracts(db, &[second_crate_id]);
>     assert_eq!(contracts.len(), 2);
> ```

Are you able to match contract names here? To make sure that `ThirdContract` is the one missing here

**Review by maciektr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3524)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @mkaput and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/contract_test.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3524#-NYvxU0CDhlWqLDQhApz:-NYw2mvAEasbK9erRXeZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/475df78925d29d74c940f00eaf01f760432cff5d/crates/cairo-lang-starknet/src/contract_test.rs#L114)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Are you able to match contract names here? To make sure that `ThirdContract` is the one missing here
</blockquote></details>

Done.

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3524#-:-NYw43XrA2egKpqomeji:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @maciektr and @spapinistarkware)

**Comment by maciektr** [comment]
This change is meant to allow users to compile contracts imported from cairo dependencies. 

In case of Cairo projects that use Cairo packages defining some contracts as dependencies, we want to allow users to deploy contracts from those dependencies within their own project. For that, we need to have a mechanism that allows their compilation. 
This PR suggests compiling contracts that are imported with `use` directive within a Cairo project.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3524)* status: all files reviewed, 6 unresolved discussions (waiting on @maciektr and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/test_utils.rs` line 104 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3524#-NYwBdsSCK1LgMpjA2hz:-NYwBdsSCK1LgMpjA2i-:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c53f080623c1de7fbfcdeb85d393e9cf4e459935/crates/cairo-lang-semantic/src/test_utils.rs#L104)):*
> ```XML
>     content: &str,
>     name: &str,
>     path: &str,
> ```





_Suggestion:_
```XML
    crate_name: &str,
    crate_root_path: &str,
```
___
*[`crates/cairo-lang-starknet/src/contract.rs` line 59 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3524#-NYwBGWeEq_T2UyO1U58:-NYwBGWeEq_T2UyO1U59:b-pb44rm) ([raw file](https://github.com/starkware-libs/cairo/blob/c53f080623c1de7fbfcdeb85d393e9cf4e459935/crates/cairo-lang-starknet/src/contract.rs#L59)):*
> ```XML
>     let mut modules: HashSet<ModuleId> = HashSet::new();
>     for crate_id in crate_ids {
>         let crate_modules = db.crate_modules(*crate_id);
> ```

inline



_Code quote:_
```XML
let crate_modules
```
___
*[`crates/cairo-lang-starknet/src/contract.rs` line 64 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3524#-NYwAopM8S1BR9luebuK:-NYwAopNCVAy99Kig7C_:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c53f080623c1de7fbfcdeb85d393e9cf4e459935/crates/cairo-lang-starknet/src/contract.rs#L64)):*
> ```XML
>             modules.insert(*module_id);
>             // Find contracts imported in the module.
>             let use_ids = db.module_uses_ids(*module_id).unwrap();
> ```





_Suggestion:_
```XML
le_uses_ids(*module_id).unwrap_or_default();
```
___
*[`crates/cairo-lang-starknet/src/contract.rs` line 64 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3524#-NYwBIkwAFSpbMKIGp2Q:-NYwBIkwAFSpbMKIGp2R:b-pb44rm) ([raw file](https://github.com/starkware-libs/cairo/blob/c53f080623c1de7fbfcdeb85d393e9cf4e459935/crates/cairo-lang-starknet/src/contract.rs#L64)):*
> ```XML
>             modules.insert(*module_id);
>             // Find contracts imported in the module.
>             let use_ids = db.module_uses_ids(*module_id).unwrap();
> ```

inline



_Code quote:_
```XML
let use_ids
```
___
*[`crates/cairo-lang-starknet/src/contract.rs` line 77 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3524#-NYwB-1P4TONe_GtLeMe:-NYwB-1P4TONe_GtLeMf:b-6d25h5) ([raw file](https://github.com/starkware-libs/cairo/blob/c53f080623c1de7fbfcdeb85d393e9cf4e459935/crates/cairo-lang-starknet/src/contract.rs#L77)):*
> ```XML
> }
> 
> fn find_module_contracts(db: &dyn SemanticGroup, module_id: ModuleId) -> Vec<ContractDeclaration> {
> ```

please doc
___
*[`crates/cairo-lang-starknet/src/contract_test.rs` line 99 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3524#-NYw9UfkCF_z1NzejRNh:-NYw9UfkCF_z1NzejRNi:b-5w0gsr) ([raw file](https://github.com/starkware-libs/cairo/blob/c53f080623c1de7fbfcdeb85d393e9cf4e459935/crates/cairo-lang-starknet/src/contract_test.rs#L99)):*
> ```XML
> 
>             #[starknet::contract]
>             mod SecondContract {
> ```

Can you add some usage of FirstContract in here so that the use would make sense?

**Comment by maciektr** [comment]
*[`crates/cairo-lang-starknet/src/contract_test.rs` line 99 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3524#-NYw9UfkCF_z1NzejRNh:-NYwE4tG3XySjTAiE7Z_:b-9so00b) ([raw file](https://github.com/starkware-libs/cairo/blob/c53f080623c1de7fbfcdeb85d393e9cf4e459935/crates/cairo-lang-starknet/src/contract_test.rs#L99)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Can you add some usage of FirstContract in here so that the use would make sense?
</blockquote></details>

We do not intend to use this contract here in the Cairo code. 
We want to compile it, so that we can deploy it without modifications.

For instance, as Cairo developer I am working on a project with some contracts I have developed. 
I want to deploy those contracts, as well as some contract from `OpenZeppelin/cairo-contracts` repo. 
Right now, I need to clone the repo manually, compile it, deploy the contract. Then get back to my project and repeat. 
What I want to do, is to import the OpenZeppelin as dependency in Scarb:
```
[dependencies]
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git" }
``` 
Then indicate that I want to compile this contract, by importing it to my project.
Then simply run `scarb build` and deploy. 

For that we need to make imported (with use keyword) contracts findable during project compilation.

**Review by maciektr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3524)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @mkaput, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/contract.rs` line 64 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3524#-NYwAopM8S1BR9luebuK:-NYwViULCc8yADJwsar6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c53f080623c1de7fbfcdeb85d393e9cf4e459935/crates/cairo-lang-starknet/src/contract.rs#L64)):*
> ```XML
>             modules.insert(*module_id);
>             // Find contracts imported in the module.
>             let use_ids = db.module_uses_ids(*module_id).unwrap();
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/contract.rs` line 77 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3524#-NYwB-1P4TONe_GtLeMe:-NYwWn1k17PVUbsnHJE_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c53f080623c1de7fbfcdeb85d393e9cf4e459935/crates/cairo-lang-starknet/src/contract.rs#L77)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

please doc
</blockquote></details>

Done.

**Review by mkaput — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3524)* status: all files reviewed, 3 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3524)* status: all files reviewed, 3 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3524)* status: all files reviewed, 2 unresolved discussions (waiting on @maciektr and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/contract.rs` line 55 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3524#-NYwv2vk2wPxQRHnoUkY:-NYwv2vk2wPxQRHnoUkZ:b-hq4j7b) ([raw file](https://github.com/starkware-libs/cairo/blob/64e66ae5f95bbe3ada819ba8f356e3f3ff8184fc/crates/cairo-lang-starknet/src/contract.rs#L55)):*
> ```XML
> 
> /// Finds the inline modules annotated as contracts in the given crate_ids and
> /// returns the corresponding ContractDeclarations.
> ```

update this to be clear about also adding `use`s, not only inline modules.



_Code quote:_
```XML
/// Finds the inline modules annotated as contracts in the given crate_ids and
/// returns the corresponding ContractDeclarations.
```
___
*[`crates/cairo-lang-starknet/src/contract_test.rs` line 99 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3524#-NYw9UfkCF_z1NzejRNh:-NYwwM9p55l2v4bT1D9y:btuydro) ([raw file](https://github.com/starkware-libs/cairo/blob/c53f080623c1de7fbfcdeb85d393e9cf4e459935/crates/cairo-lang-starknet/src/contract_test.rs#L99)):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

We do not intend to use this contract here in the Cairo code. 
We want to compile it, so that we can deploy it without modifications.

For instance, as Cairo developer I am working on a project with some contracts I have developed. 
I want to deploy those contracts, as well as some contract from `OpenZeppelin/cairo-contracts` repo. 
Right now, I need to clone the repo manually, compile it, deploy the contract. Then get back to my project and repeat. 
What I want to do, is to import the OpenZeppelin as dependency in Scarb:
```
[dependencies]
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git" }
``` 
Then indicate that I want to compile this contract, by importing it to my project.
Then simply run `scarb build` and deploy. 

For that we need to make imported (with use keyword) contracts findable during project compilation. 
</blockquote></details>

I understand, but can you please elaborate on why you would want it as a dependency if you don't use it at all?
If they are completely separate, it makes sense to me to deploy them separately. If they do have a dependency, I'd expect to see it being used in the code.
Am I missing something?

**Review by maciektr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3524)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @mkaput, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/contract.rs` line 55 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3524#-NYwv2vk2wPxQRHnoUkY:-NZ0h-v5BE9PJjhD-uuZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/64e66ae5f95bbe3ada819ba8f356e3f3ff8184fc/crates/cairo-lang-starknet/src/contract.rs#L55)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

update this to be clear about also adding `use`s, not only inline modules.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/contract_test.rs` line 99 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3524#-NYw9UfkCF_z1NzejRNh:-NZ0gmES93TY5HcPkFi_:b5l9kop) ([raw file](https://github.com/starkware-libs/cairo/blob/c53f080623c1de7fbfcdeb85d393e9cf4e459935/crates/cairo-lang-starknet/src/contract_test.rs#L99)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I understand, but can you please elaborate on why you would want it as a dependency if you don't use it at all?
If they are completely separate, it makes sense to me to deploy them separately. If they do have a dependency, I'd expect to see it being used in the code.
Am I missing something?
</blockquote></details>

Well, this can be a better developer experience to let Scarb manage the dependencies of the project, rather than doing this manually. 

I know protostar team had an important use case for this feature as well, I will discuss again internally and get back to you.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3524)* status: all files reviewed, 2 unresolved discussions (waiting on @maciektr and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/contract.rs` line 55 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3524#-NZ1Qr2a38Epc2DesaTu:-NZ1Qr2a38Epc2DesaTv:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/028b76ed98943579762af97756a8321002b564b0/crates/cairo-lang-starknet/src/contract.rs#L55)):*
> ```XML
> 
> /// Finds the inline modules and uses annotated as contracts in the given crate_ids and
> /// returns the corresponding ContractDeclarations.
> ```





_Suggestion:_
```XML
/// Finds the inline modules annotated as contracts and `use`s of modules that are annotated as contracts in the given crate_ids and
/// returns the corresponding ContractDeclarations.
```
___
*[`crates/cairo-lang-starknet/src/contract_test.rs` line 99 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3524#-NYw9UfkCF_z1NzejRNh:-NZ1R6oq98y3yccxBECZ:boh534w) ([raw file](https://github.com/starkware-libs/cairo/blob/c53f080623c1de7fbfcdeb85d393e9cf4e459935/crates/cairo-lang-starknet/src/contract_test.rs#L99)):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

Well, this can be a better developer experience to let Scarb manage the dependencies of the project, rather than doing this manually. 

I know protostar team had an important use case for this feature as well, I will discuss again internally and get back to you. 
</blockquote></details>

Thanks, please comment here to bring this back to my attention set once you have the use case.

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3524)* status: all files reviewed, 2 unresolved discussions (waiting on @maciektr, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/contract_test.rs` line 99 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3524#-NYw9UfkCF_z1NzejRNh:-NZ1hWu750TaYSrrBUwt:b-wxedig) ([raw file](https://github.com/starkware-libs/cairo/blob/c53f080623c1de7fbfcdeb85d393e9cf4e459935/crates/cairo-lang-starknet/src/contract_test.rs#L99)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Thanks, please comment here to bring this back to my attention set once you have the use case.
</blockquote></details>

In case of Protostar we would like to be able to compile contracts defined in dependencies using Scarb and this PR is the first step in this direction. The reason for it is the option to declare and deploy those contracts in Protostar tests and test interactions between them. In the Rust version of Protostar we rely fully on Scarb when it comes to contract compilation. Without this change users would be unable to declare and deploy any contracts that are not defined in the main package.

Assume the following situation:
1. A - main package containing ContractA.
2. B - dependency package of A containing ContractB.
3. I want to write a test in which I declare and deploy both ContractA and ContractB.
```rust
#[test]
fn test() {
  // ...
  let adreess_A = deploy_contract("ContractA", @calldata_A);
  let adreess_B = deploy_contract("ContractB", @calldata_B);
  // ...
}
```
Rust version of Protostar uses `scarb build` to compile the contracts under the hood before test execution. To declare it on the fresh Starknet instance we use for testing we need a compiled code of the contract. Therefore, without the ability to compile contracts defined in dependencies, the second `deploy_contract` call would fail.

**Comment by maciektr** [comment]
*[`crates/cairo-lang-starknet/src/contract.rs` line 55 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3524#-NZ1Qr2a38Epc2DesaTu:-NZ2NyNIAxTl7w8glndA:b44ehs7) ([raw file](https://github.com/starkware-libs/cairo/blob/028b76ed98943579762af97756a8321002b564b0/crates/cairo-lang-starknet/src/contract.rs#L55)):*
> ```XML
> 
> /// Finds the inline modules and uses annotated as contracts in the given crate_ids and
> /// returns the corresponding ContractDeclarations.
> ```

Sorry, thanks for suggestion! 
Done.

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3524)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/contract_test.rs` line 99 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3524#-NYw9UfkCF_z1NzejRNh:-NZ4p69d2X2CTg4CMmFW:b-1vio2j) ([raw file](https://github.com/starkware-libs/cairo/blob/c53f080623c1de7fbfcdeb85d393e9cf4e459935/crates/cairo-lang-starknet/src/contract_test.rs#L99)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

In case of Protostar we would like to be able to compile contracts defined in dependencies using Scarb and this PR is the first step in this direction. The reason for it is the option to declare and deploy those contracts in Protostar tests and test interactions between them. In the Rust version of Protostar we rely fully on Scarb when it comes to contract compilation. Without this change users would be unable to declare and deploy any contracts that are not defined in the main package.

Assume the following situation:
1. A - main package containing ContractA.
2. B - dependency package of A containing ContractB.
3. I want to write a test in which I declare and deploy both ContractA and ContractB.
```rust
#[test]
fn test() {
  // ...
  let adreess_A = deploy_contract("ContractA", @calldata_A);
  let adreess_B = deploy_contract("ContractB", @calldata_B);
  // ...
}
```
Rust version of Protostar uses `scarb build` to compile the contracts under the hood before test execution. To declare it on the fresh Starknet instance we use for testing we need a compiled code of the contract. Therefore, without the ability to compile contracts defined in dependencies, the second `deploy_contract` call would fail.
</blockquote></details>

It's important to note that this is independent of Scarb itself. This fact is an implementation detail, and a similar issue would pop up if we just used the compiler as a bare library. That's because the way how we would wire crates into a compilation unit, that would happen under the hood, would end up being the same: we just need for a possibility to re-export contracts from the _main_ crate.

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3524)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/contract_test.rs` line 99 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3524#-NYw9UfkCF_z1NzejRNh:-NZ4q4xqEtT0TXWaVVoB:bhn4kuw) ([raw file](https://github.com/starkware-libs/cairo/blob/c53f080623c1de7fbfcdeb85d393e9cf4e459935/crates/cairo-lang-starknet/src/contract_test.rs#L99)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

It's important to note that this is independent of Scarb itself. This fact is an implementation detail, and a similar issue would pop up if we just used the compiler as a bare library. That's because the way how we would wire crates into a compilation unit, that would happen under the hood, would end up being the same: we just need for a possibility to re-export contracts from the _main_ crate.
</blockquote></details>

(we actually started with prototyping this PR within `scarb build` and thought: _hey, that would make it inconsistent with pure compiler, we need to upstream that_ :sweat_smile: )

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3524)* status: all files reviewed, 1 unresolved discussion (waiting on @maciektr, @mkaput, @piotmag769, and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/contract_test.rs` line 99 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3524#-NYw9UfkCF_z1NzejRNh:-NZKl5uQ9v4-cc1qpBYr:b-u6f6pq) ([raw file](https://github.com/starkware-libs/cairo/blob/c53f080623c1de7fbfcdeb85d393e9cf4e459935/crates/cairo-lang-starknet/src/contract_test.rs#L99)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

(we actually started with prototyping this PR within `scarb build` and thought: _hey, that would make it inconsistent with pure compiler, we need to upstream that_ :sweat_smile: )
</blockquote></details>

I completely get the purpose of this PR.
I was asking for adding some dependent logic in the test.
I still don't see a use case where A depends on B but doesn't use it in any way - why does it depend on it, then?

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3524)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/contract_test.rs` line 99 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3524#-NYw9UfkCF_z1NzejRNh:-NZMQFysAeHOCCnt7CMK:bilbsqg) ([raw file](https://github.com/starkware-libs/cairo/blob/c53f080623c1de7fbfcdeb85d393e9cf4e459935/crates/cairo-lang-starknet/src/contract_test.rs#L99)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I completely get the purpose of this PR.
I was asking for adding some dependent logic in the test.
I still don't see a use case where A depends on B but doesn't use it in any way - why does it depend on it, then?
</blockquote></details>

Doesn't my example satisfy the case where A depends on B but the package A itself doesn't use B in any way besides using the compiled contract B?

**Comment by maciektr** [comment]
replaced with https://github.com/software-mansion/scarb/pull/458

**Pull request closed without merging**
