### PR TITLE
Formatter: Add support for non optional break line points. (Formatter…

### PR DESCRIPTION
**Pull request by gilbens-starkware**
… temporary broken).

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1442)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1442)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1442#-NJtHuI14sv_rG8wFUUW:-NJtHuI2B3M1_OGGE1_2:b-brv37o) (no related file):*
TODO: Change target branch.

___

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1442)* status: all files reviewed, 11 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/formatter/src/formatter.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1442#-NKEDDg67XE6IBUrabGR:-NKEDDg67XE6IBUrabGS:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/136d930c42daccfd5abf688713daac6b396ef7ba/crates/formatter/src/formatter.rs#L53)):*
> ```XML
>     pub break_indentation: BreakLinePointIndentation,
>     /// Indicates if a breakpoint is optional. An optional breakpoint will be broken only if the
>     /// line is too long. A non-optional breakpoint will always be broken.
> ```





_Suggestion:_
```XML
    /// Indicates whether a breakpoint is optional. An optional breakpoint may be broken only if the
    /// line is too long. A non-optional breakpoint is always broken.
```
___
*[`crates/formatter/src/formatter.rs` line 255 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1442#-NKEDyKo64MCl_rO6Lyw:-NKEDyKp9jKunMOhZdSa:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/136d930c42daccfd5abf688713daac6b396ef7ba/crates/formatter/src/formatter.rs#L255)):*
> ```XML
>         }
>     }
>     /// Repeatedly calls break_line_tree until each line length is less than max_width.
> ```





_Suggestion:_
```XML
break_line_tree_single_level
```
___
*[`crates/formatter/src/formatter.rs` line 255 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1442#-NKEE2o8AKJcuBmUWT4P:-NKEE2o9B5X3MsBu4Bb-:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/136d930c42daccfd5abf688713daac6b396ef7ba/crates/formatter/src/formatter.rs#L255)):*
> ```XML
>         }
>     }
>     /// Repeatedly calls break_line_tree until each line length is less than max_width.
> ```





_Suggestion:_
```XML
 `max_line_width`
```
___
*[`crates/formatter/src/formatter.rs` line 267 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1442#-NKEELIgEvz-xdg6eAM-:-NKEELIgEvz-xdg6eAM0:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/136d930c42daccfd5abf688713daac6b396ef7ba/crates/formatter/src/formatter.rs#L267)):*
> ```XML
>         }
>         let mut sub_builders = self.break_line_tree_single_level(max_line_width, tab_size);
>         // If the line was not broken into several lines (i.e. only one sub_builder), unprotect a
> ```





_Suggestion:_
```XML
        // If the line was not broken into several lines (i.e. only one sub_builder), open the highest precedence
        // protected zone and try to break again.
```
___
*[`crates/formatter/src/formatter.rs` line 273 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1442#-NKEGfLu1Um739P8awPd:-NKEGfLu1Um739P8awPe:bbxckd) ([raw file](https://github.com/starkware-libs/cairo/blob/136d930c42daccfd5abf688713daac6b396ef7ba/crates/formatter/src/formatter.rs#L273)):*
> ```XML
>                 sub_builders = sub_builders[0]
>                     .open_protected_zone()
>                     .break_line_tree_single_level(max_line_width, tab_size);
> ```

please revisit. Maybe you need to break_line_tree_single_level multiple times before/after each open?
Anyway - document.



_Code quote:_
```XML
            if sub_builders[0].contains_protected_zone() {
                sub_builders = sub_builders[0]
                    .open_protected_zone()
                    .break_line_tree_single_level(max_line_width, tab_size);
            } else if sub_builders[0].contains_break_line_points() {
```
___
*[`crates/formatter/src/formatter.rs` line 274 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1442#-NKEKnSb4QOTUclb8N3g:-NKEKnSb4QOTUclb8N3h:bpob5ms) ([raw file](https://github.com/starkware-libs/cairo/blob/136d930c42daccfd5abf688713daac6b396ef7ba/crates/formatter/src/formatter.rs#L274)):*
> ```XML
>                     .open_protected_zone()
>                     .break_line_tree_single_level(max_line_width, tab_size);
>             } else if sub_builders[0].contains_break_line_points() {
> ```

try to avoid contains and then break. Change break to return whether or not it broke something or not. If not - break (the while loop). This is more efficient.



_Code quote:_
```XML
contains_break_line_points
```
___
*[`crates/formatter/src/formatter.rs` line 278 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1442#-NKEF95O-QU1Ui6zKwPN:-NKEF95O-QU1Ui6zKwPO:b3wkwt) ([raw file](https://github.com/starkware-libs/cairo/blob/136d930c42daccfd5abf688713daac6b396ef7ba/crates/formatter/src/formatter.rs#L278)):*
> ```XML
>                     sub_builders[0].break_line_tree_single_level(max_line_width, tab_size);
>             } else {
>                 // All break line points were broken or ignored.
> ```

ignored - why?



_Suggestion:_
```XML
/ All break line points were already broken or ignored.
```
___
*[`crates/formatter/src/formatter.rs` line 302 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1442#-NKEHsme-wvizmeroNJ2:-NKEHsme-wvizmeroNJ3:b-glikst) ([raw file](https://github.com/starkware-libs/cairo/blob/136d930c42daccfd5abf688713daac6b396ef7ba/crates/formatter/src/formatter.rs#L302)):*
> ```XML
>         let break_line_point_properties =
>             extract_matches!(&self.children[breaking_positions[0]], LineComponent::BreakLinePoint);
>         if self.width() <= max_line_width && break_line_point_properties.is_optional {
> ```

as discussed f2f - consider a small refactor - one function that doesn't know about the precedences of breakpoints and only asks another function to break all the existing breakpoints. each time it opens a protected zone if needed and asks the other function to break all the breakpoints for it.



_Code quote:_
```XML
            extract_matches!(&self.children[breaking_positions[0]], LineComponent::BreakLinePoint);
        if self.width() <= max_line_width && break_line_point_properties.is_optional {
            return vec![
                self.remove_optional_break_line_point(break_line_point_properties.precedence),
            ];
        }
```
___
*[`crates/formatter/src/formatter.rs` line 438 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1442#-NKEJbwT6fgurmOMcjre:-NKEJbwT6fgurmOMcjrf:b5c97up) ([raw file](https://github.com/starkware-libs/cairo/blob/136d930c42daccfd5abf688713daac6b396ef7ba/crates/formatter/src/formatter.rs#L438)):*
> ```XML
>         self.children.iter().any(|child| matches!(child, LineComponent::BreakLinePoint(_)))
>     }
>     // Removes all the break line points with a given precedence.
> ```

You can also remove all the optional breakpoints. Change the name and doc accordingly.



_Code quote:_
```XML
/ Removes all the break line points with a given precedence.
```
___
*[`crates/formatter/src/formatter.rs` line 446 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1442#-NKEKIK23OU7-0hG7or-:-NKEKIK23OU7-0hG7or0:bt8ca5j) ([raw file](https://github.com/starkware-libs/cairo/blob/136d930c42daccfd5abf688713daac6b396ef7ba/crates/formatter/src/formatter.rs#L446)):*
> ```XML
>                 .map(|child| match child {
>                     LineComponent::BreakLinePoint(node_properties)
>                         if node_properties.precedence == precedence =>
> ```

and is_optional



_Code quote:_
```XML
if node_properties.precedence == precedence =>
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1442)* status: all files reviewed, 7 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/formatter/src/formatter.rs` line 255 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1442#-NKEDyKo64MCl_rO6Lyw:-NKJ9UwRCG2qQO2rdUpS:b-6so8d0) ([raw file](https://github.com/starkware-libs/cairo/blob/136d930c42daccfd5abf688713daac6b396ef7ba/crates/formatter/src/formatter.rs#L255)):*
> ```XML
>         }
>     }
>     /// Repeatedly calls break_line_tree until each line length is less than max_width.
> ```

It's not single level, it calls itself recursively until no break options remains.
___
*[`crates/formatter/src/formatter.rs` line 273 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1442#-NKEGfLu1Um739P8awPd:-NKJ9sUACzqd_8N0r_FZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/136d930c42daccfd5abf688713daac6b396ef7ba/crates/formatter/src/formatter.rs#L273)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

please revisit. Maybe you need to break_line_tree_single_level multiple times before/after each open?
Anyway - document.
</blockquote></details>

Done.
___
*[`crates/formatter/src/formatter.rs` line 274 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1442#-NKEKnSb4QOTUclb8N3g:-NKJCa_42l1aDTBK4X7T:b7h0z4a) ([raw file](https://github.com/starkware-libs/cairo/blob/136d930c42daccfd5abf688713daac6b396ef7ba/crates/formatter/src/formatter.rs#L274)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

try to avoid contains and then break. Change break to return whether or not it broke something or not. If not - break (the while loop). This is more efficient.
</blockquote></details>

Added todo, I'll add it when I'll improve the complexity.
___
*[`crates/formatter/src/formatter.rs` line 278 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1442#-NKEF95O-QU1Ui6zKwPN:-NKJDMeS72uuE3tQKhiB:b-4h6je4) ([raw file](https://github.com/starkware-libs/cairo/blob/136d930c42daccfd5abf688713daac6b396ef7ba/crates/formatter/src/formatter.rs#L278)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

ignored - why?
</blockquote></details>

Ignored as in optional break point that was removed. Changed to removed.
___
*[`crates/formatter/src/formatter.rs` line 302 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1442#-NKEHsme-wvizmeroNJ2:-NKJDwddAtaIwb5oU4_3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/136d930c42daccfd5abf688713daac6b396ef7ba/crates/formatter/src/formatter.rs#L302)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

as discussed f2f - consider a small refactor - one function that doesn't know about the precedences of breakpoints and only asks another function to break all the existing breakpoints. each time it opens a protected zone if needed and asks the other function to break all the breakpoints for it.
</blockquote></details>

Done.
___
*[`crates/formatter/src/formatter.rs` line 446 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1442#-NKEKIK23OU7-0hG7or-:-NKJE6nF0oD3HqNcF4-0:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/136d930c42daccfd5abf688713daac6b396ef7ba/crates/formatter/src/formatter.rs#L446)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

and is_optional
</blockquote></details>

Done.

**Review by yuvalsw — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1442)* status: all files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/formatter/src/formatter.rs` line 255 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1442#-NKEDyKo64MCl_rO6Lyw:-NKOE1sk3ZfUnN3qNQyS:bc6dg05) ([raw file](https://github.com/starkware-libs/cairo/blob/136d930c42daccfd5abf688713daac6b396ef7ba/crates/formatter/src/formatter.rs#L255)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

It's not single level, it calls itself recursively until no break options remains.
</blockquote></details>

So please explicitly add the word "recursively"
___
*[`crates/formatter/src/formatter.rs` line 272 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1442#-NKOEOLg0qc_CaFqs2xs:-NKOEOLg0qc_CaFqs2xt:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0ae09c502a0143b6709fa5354bac51c99c414a88/crates/formatter/src/formatter.rs#L272)):*
> ```XML
>             // Break the line according to the break_line_points.
>             // TODO(Gil): remove the "contains_break_line_points" and return from the breaking
>             // function if there are more break points to break.
> ```





_Suggestion:_
```XML
whether it broke any break points
```
___
*[`crates/formatter/src/formatter.rs` line 277 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1442#-NKOEzvb9k4SqA-E6t-D:-NKOEzvb9k4SqA-E6t-E:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0ae09c502a0143b6709fa5354bac51c99c414a88/crates/formatter/src/formatter.rs#L277)):*
> ```XML
>                     sub_builders[0].break_line_tree_single_level(max_line_width, tab_size)
>             // No break_line_points, open the highest precedence protected zone.
>             } else if sub_builders[0].contains_protected_zone() {
> ```





_Suggestion:_
```XML
            } else if sub_builders[0].contains_protected_zone() {
                // No break_line_points, open the highest precedence protected zone.
                sub_builders = vec![sub_builders[0].open_protected_zone()];
            } else {
```
___
*[`crates/formatter/src/formatter.rs` line 302 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1442#-NKOJ-jT7_r4nQ3sPY0d:-NKOJ-jU48aNxndrRKab:b-htoi78) ([raw file](https://github.com/starkware-libs/cairo/blob/0ae09c502a0143b6709fa5354bac51c99c414a88/crates/formatter/src/formatter.rs#L302)):*
> ```XML
>             return vec![self.clone()];
>         }
>         let break_line_point_properties =
> ```

return this from get_current_break_positions



_Code quote:_
```XML
 break_line_point_properties
```

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1442#-:-NKOJB5X5DfmrEhF8C01:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware)

**Review by yuvalsw — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1442)* status: all files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/formatter/src/formatter.rs` line 217 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1442#-NKhhj8b2rntJbJAJKTG:-NKhhj8b2rntJbJAJKTH:bmsykxv) ([raw file](https://github.com/starkware-libs/cairo/blob/3bb0e71cc61035dd1692e219f480941e0e96a811/crates/formatter/src/formatter.rs#L217)):*
> ```XML
>     /// Returns the minimum break line point precedence from within all the break line points
>     /// which are a direct child of this tree, or None if there are no such break line points.
>     fn get_min_break_properties(&self) -> Option<BreakLinePointProperties> {
> ```

Suggestion.
Also change the comment to say "highest precedence" instead of "minimum"



_Suggestion:_
```XML
get_next_break_properties
```
___
*[`crates/formatter/src/formatter.rs` line 246 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1442#-NKhi5DNCWFQOIGFemJE:-NKhi5DNCWFQOIGFemJF:b-2bjwll) ([raw file](https://github.com/starkware-libs/cairo/blob/3bb0e71cc61035dd1692e219f480941e0e96a811/crates/formatter/src/formatter.rs#L246)):*
> ```XML
>     }
>     /// Returns a vector of the positions of all the break line point children which have the
>     /// minimum precedence from within all the break line point children.
> ```

here too.
Also update according to the new return type.



_Code quote:_
```XML
minimum
```
___
*[`crates/formatter/src/formatter.rs` line 249 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1442#-NKicVrH3GdOzenAimH4:-NKicVrH3GdOzenAimH5:b-xkta4v) ([raw file](https://github.com/starkware-libs/cairo/blob/3bb0e71cc61035dd1692e219f480941e0e96a811/crates/formatter/src/formatter.rs#L249)):*
> ```XML
>     fn get_current_break_positions(&self) -> Option<(Vec<usize>, BreakLinePointProperties)> {
>         self.get_min_break_properties().map(|properties| {
>             (self.get_break_point_indices_by_precedence(properties.precedence), properties)
> ```

This function looks unnecessary - it returns properties and a function of properties. Consider inlining its logic (see if it turns out nicer).



_Code quote:_
```XML
        self.get_min_break_properties().map(|properties| {
            (self.get_break_point_indices_by_precedence(properties.precedence), properties)
```

**Review by yuvalsw — APPROVED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1442)* status: all files reviewed, 1 unresolved discussion

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1442#-:-NMUWc7n2c1qA3ELyWfD:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1442)* status: all files reviewed, 1 unresolved discussion

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1442)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
