### PR TITLE
Expose `run_tests` in test runner

### PR DESCRIPTION
**Pull request by karol-bisztyga**
Can we expose this function as a public one? We need this in protostar. Thanks.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3126)

### CODE REVIEW

**Comment by karol-bisztyga** [comment]
@mkaput 🙏

**Review by mkaput — APPROVED** [review]
:lgtm:, need approval from @orizi or @spapinistarkware 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3126#-:-NVhw3iM3xutz1Won_im:b-quft72)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karol-bisztyga)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3126#-:-NVi2kVcErEGS5hXZtSX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Comment by mkaput** [comment]
🤔 
image

**Pull request merged**
