### PR TITLE
Added a variable based builder for casm.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:3945e4f4

---

**Stack**:
- #1328
- #1324
- #1322
- #1321
- #1320
- #1319 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1319)* status: all files reviewed, 10 unresolved discussions (waiting on @gilbens-starkware, @liorgold2, and @orizi)

___
*[`crates/casm/src/builder.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1319#-NJF5FQ20oNUgWKU2TBS:-NJF5FQ20oNUgWKU2TBT:bz26s97) ([raw file](https://github.com/starkware-libs/cairo/blob/79338fdda6f01a4f0f0962ba26c6ab9670af8f2c/crates/casm/src/builder.rs#L59)):*
> ```XML
>     /// Merges states, validating that the states are mergable.
>     fn merge(&mut self, other: &Self) {
>         assert_eq!(self.ap_change, other.ap_change, "Merged branches not aligned on AP change.");
> ```

this looks like you're validating, but not merging (`self.vars` remains the same). If this is intended please rename the function



_Code quote:_
```XML
    /// Merges states, validating that the states are mergable.
    fn merge(&mut self, other: &Self) {
        assert_eq!(self.ap_change, other.ap_change, "Merged branches not aligned on AP change.");
        assert_eq!(
            self.allocated, other.allocated,
            "Merged branches not aligned on number of allocations."
        );
        self.vars.retain(|var, value| {
            other
                .vars
                .get(var)
                .map(|x| assert_eq!(x, value, "Var mismatch between branches."))
                .is_some()
        });
    }
```
___
*[`crates/casm/src/builder.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1319#-NJF7HYC1G6UzlSbtltR:-NJF7HYC1G6UzlSbtltS:b-khotjd) ([raw file](https://github.com/starkware-libs/cairo/blob/79338fdda6f01a4f0f0962ba26c6ab9670af8f2c/crates/casm/src/builder.rs#L104)):*
> ```XML
>     statements: Vec<Statement>,
>     /// The current set of added hints.
>     next_hints: Vec<Hint>,
> ```

why the `next_`?



_Code quote:_
```XML
next_hints
```
___
*[`crates/casm/src/builder.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1319#-NJF7dDx2ywxD1lm3CJC:-NJF7dDx2ywxD1lm3CJD:b-pmy7b) ([raw file](https://github.com/starkware-libs/cairo/blob/79338fdda6f01a4f0f0962ba26c6ab9670af8f2c/crates/casm/src/builder.rs#L119)):*
> ```XML
>         );
>         self.main_state.validate_finality();
>         for state in self.label_state.values() {
> ```

why do the states at each label have to be final?
can we not reach a situation where we are at a label, but AP still needs to be increased before we leave the current context?



_Code quote:_
```XML
        for state in self.label_state.values() {
            state.validate_finality();
        }
```
___
*[`crates/casm/src/builder.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1319#-NJF9KX1-gHqfuv4c2rF:-NJF9KX1-gHqfuv4c2rG:b-4ugv4l) ([raw file](https://github.com/starkware-libs/cairo/blob/79338fdda6f01a4f0f0962ba26c6ab9670af8f2c/crates/casm/src/builder.rs#L123)):*
> ```XML
>         }
>         let mut label_offsets = HashMap::<String, usize>::default();
>         let mut offset = 0;
> ```

I would put this logic in a `compute_label_offsets` function, I think it deserves a name (IMO, so non-blocking)



_Code quote:_
```XML
        let mut label_offsets = HashMap::<String, usize>::default();
        let mut offset = 0;
        for statement in &self.statements {
            match statement {
                Statement::Final(inst) | Statement::Jump(_, inst) => {
                    offset += inst.body.op_size();
                }
                Statement::Label(name) => {
                    label_offsets.insert(name.clone(), offset);
                }
            }
        }
```
___
*[`crates/casm/src/builder.rs` line 156 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1319#-NJF9oHW4bXh45mBuPJi:-NJF9oHW4bXh45mBuPJj:bx0ho8k) ([raw file](https://github.com/starkware-libs/cairo/blob/79338fdda6f01a4f0f0962ba26c6ab9670af8f2c/crates/casm/src/builder.rs#L156)):*
> ```XML
>                                 ..
>                             }) => {
>                                 *value += label_offset - offset;
> ```

why `+=` and not `=`?
probably related: what if the `JumpInstruction` has `relative == false`? shouldn't it be handled differently?



_Code quote:_
```XML
*value += label_offset - offset;
```
___
*[`crates/casm/src/builder.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1319#-NJFAQQk1QAUoz-cxoFl:-NJFAQQk1QAUoz-cxoFm:b-q877ua) ([raw file](https://github.com/starkware-libs/cairo/blob/79338fdda6f01a4f0f0962ba26c6ab9670af8f2c/crates/casm/src/builder.rs#L168)):*
> ```XML
>                     instructions.push(inst);
>                 }
>                 Statement::Label(name) => {
> ```

if you're removing every label  you see from `self.label_state`, in what situation will the returned `CasmBuildResult` contain a non-empty `label_state`?



_Code quote:_
```XML
                Statement::Label(name) => {
                    self.label_state.remove(&name);
                }
```
___
*[`crates/casm/src/builder.rs` line 189 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1319#-NJFApKr9d_U91Mpx6Bp:-NJFApKr9d_U91Mpx6Bq:bb7phvt) ([raw file](https://github.com/starkware-libs/cairo/blob/79338fdda6f01a4f0f0962ba26c6ab9670af8f2c/crates/casm/src/builder.rs#L189)):*
> ```XML
>     }
> 
>     /// Allocates a new varialbe in memory.
> ```

typo



_Suggestion:_
```XML
variable
```
___
*[`crates/casm/src/builder.rs` line 240 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1319#-NJFDvzy0dmZpaFG-p-M:-NJFDvzy0dmZpaFG-p-N:b-ofesqg) ([raw file](https://github.com/starkware-libs/cairo/blob/79338fdda6f01a4f0f0962ba26c6ab9670af8f2c/crates/casm/src/builder.rs#L240)):*
> ```XML
>     }
> 
>     /// Returns a variable that is the sum of `lhs` and `rhs`.
> ```

not sum - any bin op



_Code quote:_
```XML
sum
```
___
*[`crates/casm/src/builder.rs` line 317 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1319#-NJFFGwt388vnaN1wqFX:-NJFFGwt388vnaN1wqFY:b-twmmls) ([raw file](https://github.com/starkware-libs/cairo/blob/79338fdda6f01a4f0f0962ba26c6ab9670af8f2c/crates/casm/src/builder.rs#L317)):*
> ```XML
>     /// Returns `var`s value, with fixed ap if `fix` is true.
>     fn get_value(&self, var: Var, fix: bool) -> ResOperand {
>         if fix { self.main_state.get_fixed(var) } else { self.main_state.get_value(var) }
> ```

I think "fixed" is a confusing term here - you mean "AP is changed to be correct" right? Maybe `get_adjusted`? and `fix` should be `adjust_ap`?
Because `fix` can mean "don't change"



_Code quote:_
```XML
get_fixed
```
___
*[`crates/casm/src/builder_test.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1319#-NJFHWgECCcgqsl1TThi:-NJFHWgF0iZ6Nht58FBB:b-mupiol) ([raw file](https://github.com/starkware-libs/cairo/blob/79338fdda6f01a4f0f0962ba26c6ab9670af8f2c/crates/casm/src/builder_test.rs#L1)):*
> ```XML
> use indoc::indoc;
> ```

please add a positive and a negative test for state-merges in labels

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1319)* status: all files reviewed, 9 unresolved discussions (waiting on @gilbens-starkware, @liorgold2, and @orizi)

___
*[`crates/casm/src/builder.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1319#-NJF5FQ20oNUgWKU2TBS:-NJFKlUr1H4520W4zK0y:b-tn6c85) ([raw file](https://github.com/starkware-libs/cairo/blob/79338fdda6f01a4f0f0962ba26c6ab9670af8f2c/crates/casm/src/builder.rs#L59)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

self.vars does not remain the same - retain removes variables from it.
</blockquote></details>

Yes I understand that but `merge` indicates the result will contain a union, not an intersection. A rename would do (intersect? reduce?)
___
*[`crates/casm/src/builder.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1319#-NJF7dDx2ywxD1lm3CJC:-NJFLI6K3QAeMtDGf4_I:b9nid9f) ([raw file](https://github.com/starkware-libs/cairo/blob/79338fdda6f01a4f0f0962ba26c6ab9670af8f2c/crates/casm/src/builder.rs#L119)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

not during build - during build i expect all allocated variables to be valid - meaning they would be ap - x, and not anything ilegal.
</blockquote></details>

I thought the label states represent the state *the moment we reach the label*, i.e. maybe there are more ap-increasing instructions ahead. If this is not the case, what do the label states represent? what state?
___
*[`crates/casm/src/builder.rs` line 156 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1319#-NJF9oHW4bXh45mBuPJi:-NJFLY9RAc4EvtA21iV6:b-x5rtnw) ([raw file](https://github.com/starkware-libs/cairo/blob/79338fdda6f01a4f0f0962ba26c6ab9670af8f2c/crates/casm/src/builder.rs#L156)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

`relative` case is not relevant += as otherwise i would need to create a new BigInt.
</blockquote></details>

you are implicitly assuming `*value` is zero though, maybe add a comment / assert?
___
*[`crates/casm/src/builder.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1319#-NJFAQQk1QAUoz-cxoFl:-NJFLeM45EAa80y6RviF:bsz6bfe) ([raw file](https://github.com/starkware-libs/cairo/blob/79338fdda6f01a4f0f0962ba26c6ab9670af8f2c/crates/casm/src/builder.rs#L168)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

in case the label did not appear - you would see an example in the test and in the next pr.
</blockquote></details>

ah right, for relocations... gotcha

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1319)* status: 1 of 3 files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware, @gilbens-starkware, and @liorgold2)

___
*[`crates/casm/src/builder.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1319#-NJF5FQ20oNUgWKU2TBS:-NJFYc_HAOfg3RZnumLB:b5006wt) ([raw file](https://github.com/starkware-libs/cairo/blob/79338fdda6f01a4f0f0962ba26c6ab9670af8f2c/crates/casm/src/builder.rs#L59)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Yes I understand that but `merge` indicates the result will contain a union, not an intersection. A rename would do (intersect? reduce?)
</blockquote></details>

sure - intersect sounds good enough.
___
*[`crates/casm/src/builder.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1319#-NJF7dDx2ywxD1lm3CJC:-NJFYEaW9t_a7AdJfjv1:b-l4fc6c) ([raw file](https://github.com/starkware-libs/cairo/blob/79338fdda6f01a4f0f0962ba26c6ab9670af8f2c/crates/casm/src/builder.rs#L119)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I thought the label states represent the state *the moment we reach the label*, i.e. maybe there are more ap-increasing instructions ahead. If this is not the case, what do the label states represent? what state?
</blockquote></details>

it is at the moment we reach the label - it was a mistake checking here - moved the test to just the final labels.
___
*[`crates/casm/src/builder.rs` line 156 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1319#-NJF9oHW4bXh45mBuPJi:-NJFY6kI2Nhyl7kF_2Qv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/79338fdda6f01a4f0f0962ba26c6ab9670af8f2c/crates/casm/src/builder.rs#L156)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you are implicitly assuming `*value` is zero though, maybe add a comment / assert?
</blockquote></details>

Done.
___
*[`crates/casm/src/builder.rs` line 240 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1319#-NJFDvzy0dmZpaFG-p-M:-NJFZwSA2iOupkSv0vjH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/79338fdda6f01a4f0f0962ba26c6ab9670af8f2c/crates/casm/src/builder.rs#L240)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

not sum - any bin op
</blockquote></details>

Done.
___
*[`crates/casm/src/builder.rs` line 317 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1319#-NJFFGwt388vnaN1wqFX:-NJFZzkA34FEdIlittrI:b32wwp) ([raw file](https://github.com/starkware-libs/cairo/blob/79338fdda6f01a4f0f0962ba26c6ab9670af8f2c/crates/casm/src/builder.rs#L317)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think "fixed" is a confusing term here - you mean "AP is changed to be correct" right? Maybe `get_adjusted`? and `fix` should be `adjust_ap`?
Because `fix` can mean "don't change"
</blockquote></details>

sg

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1319)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @liorgold2, and @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1319)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @gilbens-starkware, and @liorgold2)

___
*[`crates/casm/src/builder_test.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1319#-NJFHWgECCcgqsl1TThi:-NJFc-eHDmwEXaazQfl0:b-fejfv7) ([raw file](https://github.com/starkware-libs/cairo/blob/79338fdda6f01a4f0f0962ba26c6ab9670af8f2c/crates/casm/src/builder_test.rs#L1)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please add a positive and a negative test for state-merges in labels
</blockquote></details>

adding as a tail pr - since this is much more comfortable with macros.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1319#-:-NJFfk5_7Oe7OQXvKizO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware and @liorgold2)

**Pull request merged**
