### PR TITLE
Always break blocks while inlining.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2060)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2060)* status: 0 of 22 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/block_generator_test_data/function_call` line 41 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2060#-NNknqjb758a8Uwx0-W8:-NNknqjb758a8Uwx0-W9:b-4dv6h3) ([raw file](https://github.com/starkware-libs/cairo/blob/e93ec3467f1c89fe1847bc1b2e532bb2d3b1a16f/crates/cairo-lang-sierra-generator/src/block_generator_test_data/function_call#L41)):*
> ```
> felt_add([9], [10]) -> ([8])
> PushValues([3]: MyStruct, [4]: felt, [8]: felt) -> ([13], [14], [15])
> function_call<user@test::bar>([13], [14], [15]) -> ([11], [12])
> ```

This test prints only the root block.
And this code is located in a different block.

Can I just remove the second call from the test?



_Code quote:_
```
PushValues([3]: MyStruct, [4]: felt, [8]: felt) -> ([13], [14], [15])
function_call<user@test::bar>([13], [14], [15]) -> ([11], [12])
drop<MyStruct>([11]) -> ()
drop<felt>([12]) -> ()
struct_construct<Unit>() -> ([16])
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2060)* status: 0 of 22 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/block_generator_test_data/function_call` line 41 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2060#-NNknqjb758a8Uwx0-W8:-NNkqKKCE75zPWWX8Myd:b-ndrgkz) ([raw file](https://github.com/starkware-libs/cairo/blob/e93ec3467f1c89fe1847bc1b2e532bb2d3b1a16f/crates/cairo-lang-sierra-generator/src/block_generator_test_data/function_call#L41)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

This test prints only the root block.
And this code is located in a different block.

Can I just remove the second call from the test?
</blockquote></details>

I replaced the call to 
`FeltAdd::add` with `felt_add`
but it is a bit ugly

**Review by orizi — APPROVED** [review]
> Reviewed 21 of 21 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2060)* status: all files reviewed, 1 unresolved discussion

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2060#-:-NNksC5GAYwlxfLmh543:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 20 of 21 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2060)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
