### PR TITLE
Compute statements_functions_map_for_tests only when profiling.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6161)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6161#-:-O3gwTR39u7tydE6hdsW:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @piotmag769)

**Review by piotmag769 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6161#-:-O3gz1J1DDvPb5HPaMen:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 200 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6161#-O3gz53x2Pv49fPqeGyf:-O3gz53y0-7blLER-rTf:b-oaswip) ([raw file](https://github.com/starkware-libs/cairo/blob/8b0a33b9f62c950db5159632e3ca001d2f8de30e/crates/cairo-lang-test-plugin/src/lib.rs#L200)):*
> ```XML
>     pub function_set_costs: OrderedHashMap<FunctionId, OrderedHashMap<CostTokenType, i32>>,
>     pub named_tests: Vec<(String, TestConfig)>,
>     /// An optional map between sierra statement index and the stable location that generated it.
> ```

Incorrect comment

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 200 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6161#-O3gz53x2Pv49fPqeGyf:-O3h0jiu4QPoRwxjThoR:b-aial3e) ([raw file](https://github.com/starkware-libs/cairo/blob/8b0a33b9f62c950db5159632e3ca001d2f8de30e/crates/cairo-lang-test-plugin/src/lib.rs#L200)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Incorrect comment
</blockquote></details>

why is it incorrect?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 200 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6161#-O3gz53x2Pv49fPqeGyf:-O3h1Bo-1Pyv67LBeeUI:bma46mm) ([raw file](https://github.com/starkware-libs/cairo/blob/8b0a33b9f62c950db5159632e3ca001d2f8de30e/crates/cairo-lang-test-plugin/src/lib.rs#L200)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why is it incorrect?
</blockquote></details>

https://github.com/starkware-libs/cairo/blob/021408a9d509087e2cd49755130f4265fa11379a/crates/cairo-lang-sierra-generator/src/statements_locations.rs#L159

**Review by piotmag769 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6161)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 200 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6161#-O3gz53x2Pv49fPqeGyf:-O3h2XAj2C6xkSegXDRE:b-skihzt) ([raw file](https://github.com/starkware-libs/cairo/blob/8b0a33b9f62c950db5159632e3ca001d2f8de30e/crates/cairo-lang-test-plugin/src/lib.rs#L200)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

https://github.com/starkware-libs/cairo/blob/021408a9d509087e2cd49755130f4265fa11379a/crates/cairo-lang-sierra-generator/src/statements_locations.rs#L159
</blockquote></details>

Oh, this comment is outdated, forgot to update it when I changed the key to `Vec<StableLocation>`. It should be plural form - "locations".

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6161)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi and @piotmag769)

___
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 200 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6161#-O3gz53x2Pv49fPqeGyf:-O3h5h_a2s9EwcaR4pg6:bmjdjpx) ([raw file](https://github.com/starkware-libs/cairo/blob/8b0a33b9f62c950db5159632e3ca001d2f8de30e/crates/cairo-lang-test-plugin/src/lib.rs#L200)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Oh, this comment is outdated, forgot to update it when I changed the key to `Vec<StableLocation>`. It should be plural form - "locations".
</blockquote></details>

Is it better now?

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6161)* status: all files reviewed, 1 unresolved discussion (waiting on @piotmag769)

**Review by piotmag769 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6161)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
