### PR TITLE
Handle use star in the formatter.

### PR DESCRIPTION
**Pull request by Tomer-StarkWare**

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6559)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @dean-starkware, @gilbens-starkware, and @Tomer-StarkWare)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1126 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6559#-OAXTJ9K0argC7bEiez3:-OAXTJ9K0argC7bEiez4:bgk1nzn) ([raw file](https://github.com/starkware-libs/cairo/blob/ff28973fe31be62ea0c4d3579520abe95504098e/crates/cairo-lang-formatter/src/formatter_impl.rs#L1126)):*
> ```XML
> 
>         // Case for Leaf, Single vs Star: star paths are always ordered before others.
>         (UsePath::Leaf(_) | UsePath::Single(_), UsePath::Star(_)) => Ordering::Greater,
> ```

should win against `Multi` as well.
And useless doc.



_Suggestion:_
```XML
        // Star is always considered first.
        (UsePath::Star(_), UsePath::Star(_)) => Ordering::Equal,
        (UsePath::Star(_), _) => Ordering::Less,
        (_, UsePath::Star(_)) => Ordering::Greater,
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1168 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6559#-OAXTfeU9KM_P1zeYlFF:-OAXTfeU9KM_P1zeYlFG:bevwek7) ([raw file](https://github.com/starkware-libs/cairo/blob/ff28973fe31be62ea0c4d3579520abe95504098e/crates/cairo-lang-formatter/src/formatter_impl.rs#L1168)):*
> ```XML
>                 })
>                 .cloned(),
>             UsePath::Star(star) => Some(UsePath::Star(star)),
> ```

function removed in another PR.

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6559)* status: all files reviewed, 2 unresolved discussions (waiting on @dean-starkware, @gilbens-starkware, and @Tomer-StarkWare)

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6559)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @dean-starkware, @gilbens-starkware, and @orizi)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1126 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6559#-OAXTJ9K0argC7bEiez3:-OAXc_IlC6KeiqIJcP-L:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ff28973fe31be62ea0c4d3579520abe95504098e/crates/cairo-lang-formatter/src/formatter_impl.rs#L1126)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

should win against `Multi` as well.
And useless doc.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1168 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6559#-OAXTfeU9KM_P1zeYlFF:-OAXcmIp6fyRuYm9ItD0:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ff28973fe31be62ea0c4d3579520abe95504098e/crates/cairo-lang-formatter/src/formatter_impl.rs#L1168)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

function removed in another PR.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6559)* status: all files reviewed, 2 unresolved discussions (waiting on @dean-starkware, @gilbens-starkware, and @Tomer-StarkWare)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1024 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6559#-OAXequG94P8DQICVmv6:-OAXequG94P8DQICVmv7:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/3d145849a2bc4192fc927057e95896247220d912/crates/cairo-lang-formatter/src/formatter_impl.rs#L1024)):*
> ```XML
>         (_, UsePath::Multi(_)) => {
>             Ordering::Less
>         }
> ```





_Suggestion:_
```XML
        // Case for multi is always after other types of paths.
        (UsePath::Multi(_), _) => Ordering::Greater,
        (_, UsePath::Multi(_)) => Ordering::Less,
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1078 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6559#-OAXf-dl01Fz7Cx17Oxe:-OAXf-dm6H5OwsSr2bAm:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/3d145849a2bc4192fc927057e95896247220d912/crates/cairo-lang-formatter/src/formatter_impl.rs#L1078)):*
> ```XML
>         (UsePath::Star(_), _) => Ordering::Less,
> 
>         (_, UsePath::Star(_)) => Ordering::Greater,
> ```





_Suggestion:_
```XML
        (UsePath::Star(_), UsePath::Star(_)) => Ordering::Equal,
        (UsePath::Star(_), _) => Ordering::Less,
        (_, UsePath::Star(_)) => Ordering::Greater,
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6559)* status: all files reviewed, 2 unresolved discussions (waiting on @dean-starkware, @gilbens-starkware, and @Tomer-StarkWare)

**Review by dean-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6559)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware, @orizi, and @Tomer-StarkWare)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1024 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6559#-OAXequG94P8DQICVmv6:-OAa1GHp41Nne8TL4G9Y:b-tj0s81) ([raw file](https://github.com/starkware-libs/cairo/blob/3d145849a2bc4192fc927057e95896247220d912/crates/cairo-lang-formatter/src/formatter_impl.rs#L1024)):*
> ```XML
>         (_, UsePath::Multi(_)) => {
>             Ordering::Less
>         }
> ```

I'm not sure it will work. What about the case of Multi VS Multi, for example.

**Review by dean-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6559)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1078 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6559#-OAXf-dl01Fz7Cx17Oxe:-OAb1OnC-B82_Oswz-VC:bfjualh) ([raw file](https://github.com/starkware-libs/cairo/blob/3d145849a2bc4192fc927057e95896247220d912/crates/cairo-lang-formatter/src/formatter_impl.rs#L1078)):*
> ```XML
>         (UsePath::Star(_), _) => Ordering::Less,
> 
>         (_, UsePath::Star(_)) => Ordering::Greater,
> ```

In second thought, "*" should be last, as this is the case in Rust.

**Review by dean-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6559)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6559)* status: all files reviewed, 2 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1024 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6559#-OAXequG94P8DQICVmv6:-OAhsrUj6GlHyRUzcZ-_:b-y9gtd) ([raw file](https://github.com/starkware-libs/cairo/blob/3d145849a2bc4192fc927057e95896247220d912/crates/cairo-lang-formatter/src/formatter_impl.rs#L1024)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

I'm not sure it will work. What about the case of Multi VS Multi, for example.
</blockquote></details>

Multi vs Multi is handled first - so it will work.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6559)* status: all files reviewed, 2 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1078 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6559#-OAXf-dl01Fz7Cx17Oxe:-OAht-BS3NhUpX_zCAyd:bl6d3ky) ([raw file](https://github.com/starkware-libs/cairo/blob/3d145849a2bc4192fc927057e95896247220d912/crates/cairo-lang-formatter/src/formatter_impl.rs#L1078)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

In second thought, "*" should be last, as this is the case in Rust.
</blockquote></details>

note this comment is about the whitespace.
but to your point - i'm really ok with Star being first - will make it very clear it exists.

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6559)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1024 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6559#-OAXequG94P8DQICVmv6:-OAl3x1NCtoKOLBTPGqM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3d145849a2bc4192fc927057e95896247220d912/crates/cairo-lang-formatter/src/formatter_impl.rs#L1024)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Multi vs Multi is handled first - so it will work.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1078 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6559#-OAXf-dl01Fz7Cx17Oxe:-OAl3wn-82H9feqVLWXQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3d145849a2bc4192fc927057e95896247220d912/crates/cairo-lang-formatter/src/formatter_impl.rs#L1078)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

note this comment is about the whitespace.
but to your point - i'm really ok with Star being first - will make it very clear it exists.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6559#-:-OAm8BsRAkWAJEo41j_V:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by dean-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6559)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6559)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 7 files at r1, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6559#-:-OBUyhdX8BkXbVA4coCX:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Tomer-StarkWare)

**Review by orizi — APPROVED** [review]
> Reviewed 13 of 251 files at r7, 238 of 238 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6559)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

**Pull request merged**
