### PR TITLE
PartialEq takes snapshot

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3067)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3067** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3067" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/3067?utm_source=stack-comment).

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 12 of 39 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3067)* status: 11 of 39 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/duplicate.rs` line 31 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3067#-NV3DrZoCPcJqGd1ZtrM:-NV3DrZoCPcJqGd1ZtrN:b-nyxx6t) ([raw file](https://github.com/starkware-libs/cairo/blob/b37783672c9001dd8622057f561cc242bac43d91/crates/cairo-lang-sierra/src/extensions/modules/duplicate.rs#L31)):*
> ```XML
>                 allow_add_const: false,
>                 allow_const: true,
>             }],
> ```

note that this sort of fix can only be merged into `sierra-v1.1.0` since it may generate sierra code that won't be valid in the current starknet.

also - any reason not to `with_allow_deferred`?



_Suggestion:_
```XML
            vec![ParamSignature::new(ty.clone()).with_allow_const()],
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/mem.rs` line 140 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3067#-NV3EtJ90SRjpNoQ0D4X:-NV3EtJ90SRjpNoQ0D4Y:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b37783672c9001dd8622057f561cc242bac43d91/crates/cairo-lang-sierra/src/extensions/modules/mem.rs#L140)):*
> ```XML
>                 allow_add_const: true,
>                 allow_const: true,
>             }],
> ```





_Suggestion:_
```XML
            vec![ParamSignature::new(ty.clone()).with_allow_deferred().with_allow_add_const().with_allow_const()],
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 8 of 39 files at r1, 1 of 1 files at r2, 10 of 13 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3067)* status: 27 of 39 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-starknet/test_data/minimal_contract.sierra` line 71 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3067#-NVZ15UY5ixE_cuvYA4p:-NVZ15UY5ixE_cuvYA4q:b-dbxzc4) ([raw file](https://github.com/starkware-libs/cairo/blob/c1ad723b7bc0686310f85bed32ecb93d75b915d4/crates/cairo-lang-starknet/test_data/minimal_contract.sierra#L71)):*
> ```
> drop<u32>([13]) -> ();
> rename<u32>([11]) -> ([15]);
> rename<u32>([14]) -> ([16]);
> ```

why was this code created?



_Code quote:_
```
snapshot_take<u32>([9]) -> ([10], [11]);
drop<u32>([10]) -> ();
u32_const<0>() -> ([12]);
snapshot_take<u32>([12]) -> ([13], [14]);
drop<u32>([13]) -> ();
rename<u32>([11]) -> ([15]);
rename<u32>([14]) -> ([16]);
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3067)* status: 27 of 39 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-starknet/test_data/minimal_contract.sierra` line 71 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3067#-NVZ15UY5ixE_cuvYA4p:-NVZrGAyE8qccEgVChxL:b-r0k5zg) ([raw file](https://github.com/starkware-libs/cairo/blob/c1ad723b7bc0686310f85bed32ecb93d75b915d4/crates/cairo-lang-starknet/test_data/minimal_contract.sierra#L71)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

When we compare x==0, what happens is:
```
eq(@x,@0)
```
which after inlining is
```
u32_eq(*@x,*@0)
```

So, we get extra snapshot_Take and drop.
</blockquote></details>

we probably need to make sierra gen not add all of these lines - as they are not required.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3067)* status: 27 of 39 files reviewed, 2 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3067#-NV_5Kex9VztqPw3HoPu:-NV_5Kex9VztqPw3HoPv:b-i2ulak) (no related file):*
TODO: Try to remove *@x automatically in lowering

___

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 9 of 39 files at r1, 2 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3067)* status: 38 of 39 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3067#-NVhdYfv32lOhh6719rP:-NVhdYfv32lOhh6719rQ:b-mgqpdx) (no related file):*
why is there a casm change?

___

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3067)* status: 38 of 39 files reviewed, 2 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3067#-NVhdYfv32lOhh6719rP:-NVhfRRQAWcDkdcWmHJG:b-t5tzsv) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why is there a casm change?
</blockquote></details>

1. Some places we saved a store_temp thanks to using snapshots.
2. Somer places the match optimization didnt work because of added snapshot statements

___

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3067#-:-NVhlzwo5oawsSYXAj9-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Pull request merged**
