### PR TITLE
Add bitwise costs

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
Signed-off-by: Dori Medini <dori@starkware.co>

commit-id:2425e499

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1629)

### CODE REVIEW

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1629)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/cairo-sierra/src/extensions/modules/builtin_cost.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1629#-NKryMdR1yQ-4D9ByTvn:-NKryMdR1yQ-4D9ByTvo:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e4f4ea4b548199b367f83265e335c0a1bb9d55b0/crates/cairo-sierra/src/extensions/modules/builtin_cost.rs#L49)):*
> ```XML
>             CostTokenType::Step => panic!("offset_in_builtin_costs is not supported for 'Step'."),
>             CostTokenType::Pedersen => 0,
>             CostTokenType::Bitwise => 0,
> ```





_Suggestion:_
```XML
CostTokenType::Bitwise => 1,
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1629)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-sierra/src/extensions/modules/builtin_cost.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1629#-NKryMdR1yQ-4D9ByTvn:-NKvjFcz-4l_MxUXaxUk:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e4f4ea4b548199b367f83265e335c0a1bb9d55b0/crates/cairo-sierra/src/extensions/modules/builtin_cost.rs#L49)):*
> ```XML
>             CostTokenType::Step => panic!("offset_in_builtin_costs is not supported for 'Step'."),
>             CostTokenType::Pedersen => 0,
>             CostTokenType::Bitwise => 0,
> ```

Done.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1629)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @liorgold2)

___
*[`crates/cairo-sierra/src/extensions/modules/builtin_cost.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1629#-NKvkpHp5bY1Xu7MAQpb:-NKvkpHp5bY1Xu7MAQpc:b-h3h3i) ([raw file](https://github.com/starkware-libs/cairo/blob/f1ecb3aebb913c98bdf1dd5c81b5a8d52c60ea4f/crates/cairo-sierra/src/extensions/modules/builtin_cost.rs#L28)):*
> ```XML
> impl CostTokenType {
>     pub fn iter() -> std::slice::Iter<'static, Self> {
>         [CostTokenType::Step, CostTokenType::Pedersen, CostTokenType::Bitwise].iter()
> ```

@liorgold2 this too, right?



_Code quote:_
```XML
 CostTokenType::Bitwis
```

**Review by liorgold2 — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1629)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1629#-NLBtBbw-rN4KD-W_gVM:-NLBtBbw-rN4KD-W_gVN:b-jqe43a) (no related file):*
Please add an e2e test (`tests/e2e_test_data/libfuncs/`) in a separate PR. You should see the cost reflected there.

___

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1629#-:-NLBtQj05gd8lNkA3g8G:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1629)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1629#-NLBtBbw-rN4KD-W_gVM:-NLGXg9W5EKb9D_RZEFP:b21kqwq) (no related file):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Please add an e2e test (`tests/e2e_test_data/libfuncs/`) in a separate PR. You should see the cost reflected there.
</blockquote></details>

Done: https://reviewable.io/reviews/starkware-libs/cairo/1689

___

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1629#-:-NLKb6UR47RSlEqkeHcQ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1629)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Pull request merged**
