### PR TITLE
GeneratedImpl generic args.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6201)

### CODE REVIEW

**Review by TomerStarkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6201)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/inference/infers.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6201#-O49bxNf7aKZpFMjZzN-:-O49bxNg7xDkr446ZZAm:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/443bf0b17f3e0c622368d612e200f8a5ff737e14/crates/cairo-lang-semantic/src/expr/inference/infers.rs#L155)):*
> ```XML
>                     )?,
>                 }))
>                 .intern(self.db)
> ```





_Suggestion:_
```XML
                let long_id = generated_impl.lookup_intern(self.db);
                ImplLongId::GeneratedImpl(GeneratedImplLongId {
                    concrete_trait: long_id.concrete_trait,
                    generic_args: self.infer_generic_args(
                        &long_id.generic_params[..],
                        lookup_context,
                        stable_ptr,
                    )?,
                }.intern(self.db))
                .intern(self.db)
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6201)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference/infers.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6201#-O49bxNf7aKZpFMjZzN-:-O49inMY8P2ggtJEJgxN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ab3addfc4f81c8788f266961411e743705da4658/crates/cairo-lang-semantic/src/expr/inference/infers.rs#L155)):*
> ```XML
>                     )?,
>                 }))
>                 .intern(self.db)
> ```

Done.

**Review by TomerStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6201)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/inference/infers.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6201#-O49bxNf7aKZpFMjZzN-:-O49oTCG1YVw-U_M_dm9:b-b5e0fp) ([raw file](https://github.com/starkware-libs/cairo/blob/ab3addfc4f81c8788f266961411e743705da4658/crates/cairo-lang-semantic/src/expr/inference/infers.rs#L155)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I dont see it

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/inference/infers.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6201#-O49bxNf7aKZpFMjZzN-:-O49rc-60Tc878HK76a2:bwzbmh7) ([raw file](https://github.com/starkware-libs/cairo/blob/4f7de3fad2d5314e41918350086f4fa4858b8d10/crates/cairo-lang-semantic/src/expr/inference/infers.rs#L155)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

I dont see it
</blockquote></details>

not sure why it wasn't pushed :(

**Review by TomerStarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6201#-:-O49rz_28p198VcFSpjo:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6201)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 268 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6201#-O49syt42jhvsJWAQW7C:-O49syt42jhvsJWAQW7D:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ce0f94f38e8a21030258cd026a2d2b7acbb2aa5f/crates/cairo-lang-semantic/src/items/imp.rs#L268)):*
> ```XML
>             ImplLongId::ImplImpl(impl_impl) => write!(f, "{:?}", impl_impl.debug(db)),
>             ImplLongId::TraitImpl(trait_impl) => write!(f, "{:?}", trait_impl.debug(db)),
>             ImplLongId::GeneratedImpl(generated_impl) => generated_impl.fmt(f, db),
> ```





_Suggestion:_
```XML
            ImplLongId::GeneratedImpl(generated_impl) => write!(f, generated_impl.debug(db)),
```
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1575 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6201#-O49tAQ4AeAEgmTBYdyb:-O49tAQ53cEfWKBjQZWA:b-5ae9kc) ([raw file](https://github.com/starkware-libs/cairo/blob/ce0f94f38e8a21030258cd026a2d2b7acbb2aa5f/crates/cairo-lang-semantic/src/items/imp.rs#L1575)):*
> ```XML
> }
> 
> define_short_id!(
> ```

doc all

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1575 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6201#-O49tAQ4AeAEgmTBYdyb:-O4AAJew8nE78FNI9e_X:b9yb3ns) ([raw file](https://github.com/starkware-libs/cairo/blob/ce0f94f38e8a21030258cd026a2d2b7acbb2aa5f/crates/cairo-lang-semantic/src/items/imp.rs#L1575)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc all
</blockquote></details>

none of the ids are documented, e.g.:
https://github.com/starkware-libs/cairo/blob/443bf0b17f3e0c622368d612e200f8a5ff737e14/crates/cairo-lang-semantic/src/items/imp.rs#L274

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1575 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6201#-O49tAQ4AeAEgmTBYdyb:-O4AAltD7uoN8BdiOv75:bwf5fsu) ([raw file](https://github.com/starkware-libs/cairo/blob/ce0f94f38e8a21030258cd026a2d2b7acbb2aa5f/crates/cairo-lang-semantic/src/items/imp.rs#L1575)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

none of the ids are documented, e.g.:
https://github.com/starkware-libs/cairo/blob/443bf0b17f3e0c622368d612e200f8a5ff737e14/crates/cairo-lang-semantic/src/items/imp.rs#L274
</blockquote></details>

Should I just move the comment from `UninferredGeneratedImplLongId` to here?

Can you elaborate on the kind of documentation that you want?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6201)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1615 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6201#-O4ABogI4qOYMT2Y2KW3:-O4ABogI4qOYMT2Y2KW4:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ce0f94f38e8a21030258cd026a2d2b7acbb2aa5f/crates/cairo-lang-semantic/src/items/imp.rs#L1615)):*
> ```XML
>         self.concrete_trait.fmt(f, db)
>     }
> }
> ```





_Suggestion:_
```XML
impl UninferredGeneratedImplId {
    pub fn concrete_trait(self, db: &dyn SemanticGroup) -> ConcreteTraitId {
        db.lookup_intern_uninferred_generated_impl(self).concrete_trait
    }

    pub fn trait_id(&self, db: &dyn SemanticGroup) -> TraitId {
        self.concrete_trait(db).trait_id(db)
    }
}

/// Generated impls before inference, see GeneratedImplLongId for more details.
#[derive(Clone, Debug, Hash, PartialEq, Eq, SemanticObject)]
pub struct UninferredGeneratedImplLongId {
    pub concrete_trait: ConcreteTraitId,
    pub generic_params: Vec<GenericParam>,
}

impl DebugWithDb<dyn SemanticGroup> for UninferredGeneratedImplLongId {
    fn fmt(
        &self,
        f: &mut std::fmt::Formatter<'_>,
        db: &(dyn SemanticGroup + 'static),
    ) -> std::fmt::Result {
        write!(f, "Generated {:?}", self.concrete_trait.debug(db));
    }
}
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1575 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6201#-O49tAQ4AeAEgmTBYdyb:-O4ADfGD777Q0xeqZRlX:byvmyit) ([raw file](https://github.com/starkware-libs/cairo/blob/ce0f94f38e8a21030258cd026a2d2b7acbb2aa5f/crates/cairo-lang-semantic/src/items/imp.rs#L1575)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Should I just move the comment from `UninferredGeneratedImplLongId` to here?

Can you elaborate on the kind of documentation that you want?
</blockquote></details>

I think it is less clear.

I can write 
/// short id for UninferredGeneratedImplLongId, but it feels rather dumb.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6201#-:-O4B8_isAfwvXrBdkrb0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
