### PR TITLE
Added crate specific configuration.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #4311
- #4306
- #4305
- #4304
- #4301
- #4299 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4299)

### CODE REVIEW

**Review by mkaput — APPROVED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4299)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4299#-NhaTBkm6zaDQaN5Dv54:-NhaTBkm6zaDQaN5Dv55:b-53dlsg) ([raw file](https://github.com/starkware-libs/cairo/blob/24077a0e5372290f7758521172ad932a9e1158ed/crates/cairo-lang-filesystem/src/db.rs#L27)):*
> ```XML
> impl CrateConfiguration {
>     /// Returns a new configuration.
>     pub fn new(root: Directory) -> Self {
> ```

wdyt? would be more informative I think



_Suggestion:_
```XML
default_for_root
```

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4299)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 4 of 13 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4299)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4299#-NhfR62LDSaxwNiuSbBi:-NhfR62LDSaxwNiuSbBj:bvcte9c) ([raw file](https://github.com/starkware-libs/cairo/blob/c64ccc1c791082d03692ef079f1a457503140c85/crates/cairo-lang-filesystem/src/db.rs#L27)):*
> ```XML
> impl CrateConfiguration {
>     /// Returns a new configuration.
>     pub fn default_for_root(root: Directory) -> Self {
> ```

why not call it `new`? And then when you'll have more flags, do `CrateConfiguration::new(root).with_flag_a().with_flag_b(2);`?
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 763 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4299#-NhfS-l55HBd1p3LZtH4:-NhfS-l55HBd1p3LZtH5:bf0a315) ([raw file](https://github.com/starkware-libs/cairo/blob/c64ccc1c791082d03692ef079f1a457503140c85/crates/cairo-lang-semantic/src/resolve/mod.rs#L763)):*
> ```XML
>         // module.
>         let crate_id = self.db.intern_crate(CrateLongId::Real(ident));
>         // TODO(spapini): Use a better interface to check if the crate exists (not using `dir`).
> ```

is this still relevant?



_Code quote:_
```XML
// TODO(spapini): Use a better interface to check if the crate exists (not using `dir`)
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4299)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4299#-NhfR62LDSaxwNiuSbBi:-NhfsKEa6Olr1ZOJz85j:b-q06tq6) ([raw file](https://github.com/starkware-libs/cairo/blob/c64ccc1c791082d03692ef079f1a457503140c85/crates/cairo-lang-filesystem/src/db.rs#L27)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

why not call it `new`? And then when you'll have more flags, do `CrateConfiguration::new(root).with_flag_a().with_flag_b(2);`?
</blockquote></details>

this is not designed to be a builder - the other ways are mostly for various testing.
we mostly build this from Scarb.toml and cairo_project.toml, and there it will be built directly.
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 763 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4299#-NhfS-l55HBd1p3LZtH4:-Nhfshth5ceuaFG2PmDf:bqnvrkj) ([raw file](https://github.com/starkware-libs/cairo/blob/c64ccc1c791082d03692ef079f1a457503140c85/crates/cairo-lang-semantic/src/resolve/mod.rs#L763)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

is this still relevant?
</blockquote></details>

yes - it really checks if the actual name exists as a directory AFAIU.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4299)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @mkaput and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 763 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4299#-NhfS-l55HBd1p3LZtH4:-NhftzJf0F9o2w3fEu0w:b-vo7lmb) ([raw file](https://github.com/starkware-libs/cairo/blob/c64ccc1c791082d03692ef079f1a457503140c85/crates/cairo-lang-semantic/src/resolve/mod.rs#L763)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

yes - it really checks if the actual name exists as a directory AFAIU.
</blockquote></details>

nm - deleted it.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4299)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4299#-NhfR62LDSaxwNiuSbBi:-NhgAPi_DEFHMehNELnW:bkz9g1w) ([raw file](https://github.com/starkware-libs/cairo/blob/c64ccc1c791082d03692ef079f1a457503140c85/crates/cairo-lang-filesystem/src/db.rs#L27)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is not designed to be a builder - the other ways are mostly for various testing.
we mostly build this from Scarb.toml and cairo_project.toml, and there it will be built directly.
</blockquote></details>

I still don't see why not to call it `new`. This is the standard way of calling constructors with parameters.
https://rust-lang.github.io/api-guidelines/naming.html
You can call it `with_root`, but I think it doesn't make sense as you always need to pass the root.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4299)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4299#-NhfR62LDSaxwNiuSbBi:-NhgEBJF2ismHMVxTOvI:bhwgkqf) ([raw file](https://github.com/starkware-libs/cairo/blob/c64ccc1c791082d03692ef079f1a457503140c85/crates/cairo-lang-filesystem/src/db.rs#L27)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I still don't see why not to call it `new`. This is the standard way of calling constructors with parameters.
https://rust-lang.github.io/api-guidelines/naming.html
You can call it `with_root`, but I think it doesn't make sense as you always need to pass the root.
</blockquote></details>

I originally called it new - but this should be the non-trivial way to create the type - if i call it new, the only place that actually creates it as it should be created (which is 2 PRs down the line) won't call it that way. (and the corresponding caller in scarb)

**Comment by yuvalsw** [comment]
*[`crates/cairo-lang-filesystem/src/db.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4299#-NhfR62LDSaxwNiuSbBi:-NhgGJsZEA19XDie-fdi:b-wpt1ir) ([raw file](https://github.com/starkware-libs/cairo/blob/c64ccc1c791082d03692ef079f1a457503140c85/crates/cairo-lang-filesystem/src/db.rs#L27)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I originally called it new - but this should be the non-trivial way to create the type - if i call it new, the only place that actually creates it as it should be created (which is 2 PRs down the line) won't call it that way. (and the corresponding caller in scarb)
</blockquote></details>

I'll TAL at the next PRs to see. I thought root is the required parameter and thus it should be the most trivial way to create a config.

**Review by mkaput — APPROVED** [review]
> Reviewed 9 of 9 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4299)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4299#-:-NhzruzHEHhwqvilQJr8:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4299#-NhfR62LDSaxwNiuSbBi:-NhzrIdM1hnwENH_0RIL:b-g430hp) ([raw file](https://github.com/starkware-libs/cairo/blob/c64ccc1c791082d03692ef079f1a457503140c85/crates/cairo-lang-filesystem/src/db.rs#L27)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I'll TAL at the next PRs to see. I thought root is the required parameter and thus it should be the most trivial way to create a config.
</blockquote></details>

The uses I see down the line are: 1 added in the next PR, and then remove in the PR after it. So Eventually no use. If this is the case, you can just remove this function. If you think it's still needed, I still think it should be called `new`. Anyway, unblocking as I'm also OK with it if you choose to leave this name.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4299)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4299#-NhfR62LDSaxwNiuSbBi:-NhztesI9PbJKG0Nqsd_:bof4ykl) ([raw file](https://github.com/starkware-libs/cairo/blob/c64ccc1c791082d03692ef079f1a457503140c85/crates/cairo-lang-filesystem/src/db.rs#L27)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

The uses I see down the line are: 1 added in the next PR, and then remove in the PR after it. So Eventually no use. If this is the case, you can just remove this function. If you think it's still needed, I still think it should be called `new`. Anyway, unblocking as I'm also OK with it if you choose to leave this name.
</blockquote></details>

it is used in all the tests,as the default version.
The main usage is the one that is changed.
leaving as is for now, as this can be easily changed.

**Pull request merged**
