### PR TITLE
Added panicable attribute.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:0ecb1b4c

---

**Stack**:
- #1094
- #1080
- #1077 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 7 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1077#-:-NHrqoYkDgJJoL_ozF8v:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/parser/src/utils.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1077#-NHrqQ6j0GW55NZvzQCD:-NHrqQ6j0GW55NZvzQCE:b8towdy) ([raw file](https://github.com/starkware-libs/cairo/blob/35f50cb7713c791b9345a8f6a60a921ee9db6011/crates/parser/src/utils.rs#L57)):*
> ```XML
> 
> /// Get all the text under a semantic node.
> pub fn get_node_text(db: &dyn SyntaxGroup, syntax_node: &SyntaxNode) -> String {
> ```

Should this be a method on SyntaxNode?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1077)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/parser/src/utils.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1077#-NHrqQ6j0GW55NZvzQCD:-NHruLhj9E00ECcv0Mug:b-wxtaqu) ([raw file](https://github.com/starkware-libs/cairo/blob/a7d4476387c349adab03598c547ed505842beaab/crates/parser/src/utils.rs#L57)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Should this be a method on SyntaxNode?
</blockquote></details>

not sure - adding a todo.
and added a pr at the tail removing it.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1077#-:-NHsh4vk-s78dxVNTpVp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1077)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1077)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
