### PR TITLE
Rename burn_gas to branch_align, and use it more minimally.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:0d36e79c

---

**Stack**:
- #1281
- #1280
- #1279
- #1278
- #1277 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 14 of 35 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1277)* status: 14 of 35 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/sierra_generator/src/block_generator.rs` line 240 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1277#-NIxcEhIAz71bj1XTnN9:-NIxcEhIAz71bj1XTnNA:b-aiyrv7) ([raw file](https://github.com/starkware-libs/cairo/blob/53da95ec81e2c72567f29fd86474c02812172fd2/crates/sierra_generator/src/block_generator.rs#L240)):*
> ```XML
>         }
>         // Add branch_align to equalize gas costs across the merging paths.
>         statements.push(simple_statement(branch_align_libfunc_id(context.get_db()), &[], &[]));
> ```

Not sure you'll be able to advance `ap` at this point. It won't work with the stack optimization.
Maybe we're ok with it.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 35 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1277)* status: 18 of 35 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/sierra/src/extensions/modules/branch_align.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1277#-NIxfHmV-Nj4RauUvne1:-NIxfHmWDJaQi4i-OdPp:b-g4ks6s) ([raw file](https://github.com/starkware-libs/cairo/blob/53da95ec81e2c72567f29fd86474c02812172fd2/crates/sierra/src/extensions/modules/branch_align.rs#L19)):*
> ```XML
>         _context: &dyn SignatureSpecializationContext,
>     ) -> Result<LibFuncSignature, SpecializationError> {
>         Ok(LibFuncSignature::new_non_branch(vec![], vec![], SierraApChange::Known(0)))
> ```

Put a TODO to change `SierraApChange::Known(0)` to something else. We should discuss what exactly.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 35 of 35 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1277#-:-NIzfEqfDFaQQ_ZxpYxV:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1277)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`crates/sierra/src/extensions/modules/branch_align.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1277#-NIxfHmV-Nj4RauUvne1:-NJ-JLheClGrrpU_MLL1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/53da95ec81e2c72567f29fd86474c02812172fd2/crates/sierra/src/extensions/modules/branch_align.rs#L19)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Put a TODO to change `SierraApChange::Known(0)` to something else. We should discuss what exactly.
</blockquote></details>

Done.
___
*[`crates/sierra_generator/src/block_generator.rs` line 240 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1277#-NIxcEhIAz71bj1XTnN9:-NJ-IGix9WrVhdr21VFN:ba4ahdu) ([raw file](https://github.com/starkware-libs/cairo/blob/53da95ec81e2c72567f29fd86474c02812172fd2/crates/sierra_generator/src/block_generator.rs#L240)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Not sure you'll be able to advance `ap` at this point. It won't work with the stack optimization.
Maybe we're ok with it.
</blockquote></details>

it is better than the current state - as the alignment is after the pushes - here at least these are before the pushes.

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1277)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 35 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1277#-:-NJ06FWV81yTdbY4PcKp:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by liorgold2 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1277)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1277)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
