### PR TITLE
Made StableLocation optional

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2551)

### CODE REVIEW

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2551)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2551#-NQump2f8Lq1sQxl8cwb:-NQump2gChrF0TNZx3Fg:b-3yf84a) (no related file):*
change target branch

___

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2551)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`-- commits` line 3 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2551#-NQy6TcHDqXktKbFxaFp):*
rebase



_Code quote:_
```
- 858c536: Added compilation flags
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2551)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`-- commits` line 3 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2551#-NQy6TcHDqXktKbFxaFp):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rebase
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2551)* status: 0 of 11 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-defs/src/diagnostic_utils.rs` line 17 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2551#-NQyNDWPDD7BroAnyvef:-NQyNDWPDD7BroAnyveg:bwmmvb1) ([raw file](https://github.com/starkware-libs/cairo/blob/462a894a040becd946290eb5b047aa3465bc54c4/crates/cairo-lang-defs/src/diagnostic_utils.rs#L17)):*
> ```XML
>     Some(StableLocationSome),
> }
> impl StableLocation {
> ```

maybe call this `StableLocationOption` - as this is what it is - and keep the original name?



_Code quote:_
```XML
StableLocation
```
___
*[`crates/cairo-lang-defs/src/diagnostic_utils.rs` line 47 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2551#-NQyN9vc1eVkKXrp6I09:-NQyN9vc1eVkKXrp6I0A:b303itg) ([raw file](https://github.com/starkware-libs/cairo/blob/462a894a040becd946290eb5b047aa3465bc54c4/crates/cairo-lang-defs/src/diagnostic_utils.rs#L47)):*
> ```XML
>     }
> 
>     /// Returns the [DiagnosticLocation] that corresponds to the [StableLocationInner].
> ```

do you mean:



_Suggestion:_
```XML
StableLocationSome
```

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2551)* status: 8 of 11 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2551)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2551)* status: 5 of 18 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-defs/src/diagnostic_utils.rs` line 17 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2551#-NQyNDWPDD7BroAnyvef:-NQygnWP2yn_LOy2vTDv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/462a894a040becd946290eb5b047aa3465bc54c4/crates/cairo-lang-defs/src/diagnostic_utils.rs#L17)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I wanted this to be the common, external one, so I wanted it to have the simple/basic name.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 13 of 13 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2551#-:-NQz4OjF3BpaDp0DXf95:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
