### PR TITLE
Added semantic model of trait types

### PR DESCRIPTION
**Pull request by yuvalsw**
commit-id:3e19a902

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4699)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 8 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4699)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-defs/src/ids.rs` line 630 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4699#-NnDPoZK3XtMWxIL5Db-:-NnDPoZK3XtMWxIL5Db0:b9lddnc) ([raw file](https://github.com/starkware-libs/cairo/blob/fd10d1ebcdcceb7700cd274c7a21555ba84e858b/crates/cairo-lang-defs/src/ids.rs#L630)):*
> ```XML
>         TypeAlias(ModuleTypeAliasId),
>         ImplAlias(ImplAliasId),
>         TraitType(TraitTypeId),
> ```

this is used in both module level and trait level?



_Code quote:_
```XML
        TraitType(TraitTypeId),
```
___
*[`crates/cairo-lang-semantic/src/items/trt.rs` line 500 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4699#-NnDS4dF6LIClj2K3nwN:-NnDS4dF6LIClj2K3nwO:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/fd10d1ebcdcceb7700cd274c7a21555ba84e858b/crates/cairo-lang-semantic/src/items/trt.rs#L500)):*
> ```XML
> 
>     if !generic_params_node.is_empty(syntax_db) {
>         diagnostics.report(
> ```





_Suggestion:_
```XML
    // TODO(yuval): support generics in impls (including validation), then remove this.
    // Generic parameters are not yet supported, make sure there are none.
    if !generic_params_node.is_empty(syntax_db) {
        diagnostics.report(
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4699)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-defs/src/ids.rs` line 630 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4699#-NnDPoZK3XtMWxIL5Db-:-NnDnDDwAWcs_wHhtZzO:b9ogs0v) ([raw file](https://github.com/starkware-libs/cairo/blob/fd10d1ebcdcceb7700cd274c7a21555ba84e858b/crates/cairo-lang-defs/src/ids.rs#L630)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is used in both module level and trait level?
</blockquote></details>

No, this is for the trait level, hence the name TraitType.
In a module there is no type, but type-alias, and for it we have the other variant TypeAlias.
In the future I'll make this hierarchical (split first to module/trait/impl and then the item kind)
___
*[`crates/cairo-lang-semantic/src/items/trt.rs` line 500 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4699#-NnDS4dF6LIClj2K3nwN:-NnDnyxqD8HWDfaWDCJh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fd10d1ebcdcceb7700cd274c7a21555ba84e858b/crates/cairo-lang-semantic/src/items/trt.rs#L500)):*
> ```XML
> 
>     if !generic_params_node.is_empty(syntax_db) {
>         diagnostics.report(
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4699#-:-NnDvwGx5uVR_vOtvtFf:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4699)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
