### PR TITLE
Add type checks to sturct construct destructure optimizations.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4938)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4938#-:-NpE-rNb5dNAozKncyDK:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
Not needed.
Was already checked by the semantic module.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4938)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/return_optimization_test.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4938#-NqTRD3JAkJuKX_hkRgD:-NqTRD3JAkJuKX_hkRgE:brumu9t) ([raw file](https://github.com/starkware-libs/cairo/blob/43831a774884910392f626f64cf6f52d5ea2d5c7/crates/cairo-lang-lowering/src/optimizations/return_optimization_test.rs#L50)):*
> ```XML
>     before = lower_panics(db, function_id, &before).unwrap();
>     reorganize_blocks(&mut before);
>     optimize_remappings(&mut before);
> ```

this was also a bug
optimize_remappings should come first



_Code quote:_
```XML
    reorganize_blocks(&mut before);
    optimize_remappings(&mut before);
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4938#-:-NqTRkNyEwgQcD4SFwVj:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4938)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
