### PR TITLE
Fail sooner when modifying a text node

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2299)

### CODE REVIEW

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2299)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2299#-NPHuYop0TU9MVBxeL5J:-NPHuYop0TU9MVBxeL5K:b-3yf84a) (no related file):*
change target branch

___

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2299#-:-NPHz4vF0nTSZbS0dn09:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/patcher.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2299#-NPHyx2O-XGXQbnBRvGI:-NPHyx2O-XGXQbnBRvGJ:b-josuq5) ([raw file](https://github.com/starkware-libs/cairo/blob/8c618f00a8de4e077f34c3e024d9d153ef58532c/crates/cairo-lang-semantic/src/patcher.rs#L106)):*
> ```XML
>             }
>             RewriteNode::Modified(modified) => modified,
>             RewriteNode::Text(_) => unreachable!(),
> ```

this can be caused by bad plugin development code, so add a more descriptive panic string.



_Code quote:_
```XML
unreachable!(),
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2299)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2299)* status: 0 of 113 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2299#-NPHuYop0TU9MVBxeL5J:-NPIiGsg10g6cjdZxpEh:blgy7wd) (no related file):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

change target branch
</blockquote></details>

rebase again - something went wrong.

___

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 6 files at r4, 112 of 112 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2299)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2299)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/patcher.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2299#-NPHyx2O-XGXQbnBRvGI:-NPIsbQCApO_vNw53mQy:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8c618f00a8de4e077f34c3e024d9d153ef58532c/crates/cairo-lang-semantic/src/patcher.rs#L106)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this can be caused by bad plugin development code, so add a more descriptive panic string.
</blockquote></details>

Done.

**Pull request merged**
