### PR TITLE
feat: wrapping traits

### PR DESCRIPTION
**Pull request by enitrat**
Added traits for wrapping arithmetic operations, based on the overflowing operations.
Removed reexporting from the `ops` module, to only have it at the `num::traits` level.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5175)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5175)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @enitrat)

___
*[`corelib/src/integer.cairo` line 3013 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5175#-NrqbCCR7nULsfazBsgL:-NrqbCCR7nULsfazBsgM:b-biiyts) ([raw file](https://github.com/starkware-libs/cairo/blob/8203d47977de98c67fa84a2f48b872fb0a400099/corelib/src/integer.cairo#L3013)):*
> ```Cairo
> 
> /// WrappingAdd implementations
> impl TWrappingAdd<T, +core::num::traits::OverflowingAdd<T>> of core::num::traits::WrappingAdd<T> {
> ```

for must types these implementations are less efficient than direct implementations currently.
the generic implementation will actually block efficient implementation - which is a problem.

**Review by enitrat — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5175)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/integer.cairo` line 3013 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5175#-NrqbCCR7nULsfazBsgL:-NruUgb03HsyeN3n7Vi5:b-1c1mbt) ([raw file](https://github.com/starkware-libs/cairo/blob/8203d47977de98c67fa84a2f48b872fb0a400099/corelib/src/integer.cairo#L3013)):*
> the generic implementation will actually block efficient implementation

I'm not sure I understand: what's the problem with this approach and why would it make it less effician than adding these in an internal module if I reexport it with impl aliases?

**Review by enitrat — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5175)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/integer.cairo` line 3013 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5175#-NrqbCCR7nULsfazBsgL:-Nrumfs56cMJP_yeLUYL:bjjtu27) ([raw file](https://github.com/starkware-libs/cairo/blob/8203d47977de98c67fa84a2f48b872fb0a400099/corelib/src/integer.cairo#L3013)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

for example - for multiplication - the implementation would have just been wide mult + masking, but this already does more - and this implementation catches all, so cannot be improved.

may be ok just because it is within integer.cairo - but i still rather be more careful here.
</blockquote></details>

Ok - got it. If I understand well I should rewrite them directly instead of being overflow_based, because there are extra unused return parameters adding unnecessary extra steps and we should aim for efficiency.

I can just write the full implementation directly instead of relying on Overflowing traits if that's better.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5175#-:-NryELFc3YuX0yU81r66:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @enitrat)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5175#-NryEMcuB2onJzZkV0no:-NryEMcuB2onJzZkV0np:b-uuj1x0) (no related file):*
@gilbens-starkware for 2nd eye.

___

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5175#-:-Ns2TpwD2Sj5whINslpW:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @enitrat)

**Pull request merged**
