### PR TITLE
Add FunctionDeclaration.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1489)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1489)* status: 0 of 20 files reviewed, 1 unresolved discussion (waiting on @orizi, @spapinistarkware, and @yuvalsw)

___
*[`crates/syntax_codegen/src/cairo_spec.rs` line 324 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1489#-NKDRDTG8C1rF-DszOlk:-NKDRDTG8C1rF-DszOll:bl6nug1) ([raw file](https://github.com/starkware-libs/cairo/blob/af1170e9e61c588df1829e95be645fcf52e2864f/crates/syntax_codegen/src/cairo_spec.rs#L324)):*
> ```XML
>         )
>     .add_separated_list("AttributeArgList", "Expr", "TerminalComma")
>     .add_struct(StructBuilder::new("FunctionDeclaration")
> ```

Should I fix trait function in the same PR?



_Code quote:_
```XML
   .add_struct(StructBuilder::new("FunctionDeclaration")
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1489)* status: 0 of 22 files reviewed, 1 unresolved discussion (waiting on @orizi, @spapinistarkware, and @yuvalsw)

___
*[`crates/syntax_codegen/src/cairo_spec.rs` line 324 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1489#-NKDRDTG8C1rF-DszOlk:-NKDVKyrDEnPBYcmI4EB:b-zgcjbw) ([raw file](https://github.com/starkware-libs/cairo/blob/af1170e9e61c588df1829e95be645fcf52e2864f/crates/syntax_codegen/src/cairo_spec.rs#L324)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Should I fix trait function in the same PR?
</blockquote></details>

nvm, it was rather simple.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 13 of 20 files at r1, 4 of 7 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1489)* status: all files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @spapinistarkware)

___
*[`crates/parser/src/parser.rs` line 384 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1489#-NKDcDdsBiRPnXqIh85L:-NKDcDdsBiRPnXqIh85M:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7aa2b95d5e06dce86eb0ce7c1ab647875631fe8e/crates/parser/src/parser.rs#L384)):*
> ```XML
> 
>     /// Assumes the current token is Function.
>     /// Expected pattern: `<FunctionSignature><Block>`
> ```





_Suggestion:_
```XML
Expected pattern: `<FunctionDeclaration><Block>
```
___
*[`crates/parser/src/parser.rs` line 422 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1489#-NKDcQjO-UYUIYYwHKkh:-NKDcQjO-UYUIYYwHKki:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7aa2b95d5e06dce86eb0ce7c1ab647875631fe8e/crates/parser/src/parser.rs#L422)):*
> ```XML
> 
>     /// Assumes the current token is Function.
>     /// Expected pattern: `<FunctionSignature><SemiColon>`
> ```





_Suggestion:_
```XML
Expected pattern: `<FunctionDeclaration><SemiColon>`
```
___
*[`crates/semantic/src/items/imp.rs` line 434 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1489#-NKDdOYp-tN_oFu5j8qu:-NKDdOYp-tN_oFu5j8qv:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7aa2b95d5e06dce86eb0ce7c1ab647875631fe8e/crates/semantic/src/items/imp.rs#L434)):*
> ```XML
>         &mut diagnostics,
>         module_file_id,
>         &declaration.generic_params(db.upcast()),
> ```





_Suggestion:_
```XML
declaration.generic_params(syntax_db),
```
___
*[`crates/starknet/src/plugin.rs` line 198 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1489#-NKDdYb68e-5ACh-bhXP:-NKDdYb68e-5ACh-bhXQ:b-afadoo) ([raw file](https://github.com/starkware-libs/cairo/blob/7aa2b95d5e06dce86eb0ce7c1ab647875631fe8e/crates/starknet/src/plugin.rs#L198)):*
> ```XML
>     let param_names_tokens = join(arg_names.into_iter(), ", ");
> 
>     let declaration = function.declaration(db);
> ```

consider inlining



_Code quote:_
```XML
let declaration
```
___
*[`crates/syntax/src/node/helpers.rs` line 103 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1489#-NKDbbl33XqVeBvh7SFt:-NKDbbl40gHA6rPEGFDv:bo6gck) ([raw file](https://github.com/starkware-libs/cairo/blob/7aa2b95d5e06dce86eb0ce7c1ab647875631fe8e/crates/syntax/src/node/helpers.rs#L103)):*
> ```XML
> 
> impl ItemFreeFunctionPtr {
>     pub fn name_green(self, db: &dyn SyntaxGroup) -> TerminalIdentifierGreen {
> ```

add a trait NameGreen or something. Also impl it for ItemExternFunction



_Code quote:_
```XML
impl FunctionDeclarationGreen {
    pub fn name_green(self, db: &dyn SyntaxGroup) -> TerminalIdentifierGreen {
        TerminalIdentifierGreen(
            db.lookup_intern_green(self.0).children()[FunctionDeclaration::INDEX_NAME],
        )
    }
}

impl ItemFreeFunctionPtr {
    pub fn name_green(self, db: &dyn SyntaxGroup) -> TerminalIdentifierGreen {
        self.declaration_green(db).name_green(db)
    }
}

impl TraitItemFunctionPtr {
    pub fn name_green(self, db: &dyn SyntaxGroup) -> TerminalIdentifierGreen {
        self.declaration_green(db).name_green(db)
    }
}
```
___
*[`crates/syntax_codegen/src/cairo_spec.rs` line 339 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1489#-NKDbDML-yltEjunxr5k:-NKDbDML-yltEjunxr5l:bps1s89) ([raw file](https://github.com/starkware-libs/cairo/blob/7aa2b95d5e06dce86eb0ce7c1ab647875631fe8e/crates/syntax_codegen/src/cairo_spec.rs#L339)):*
> ```XML
>         .node("extern_kw", "TerminalExtern")
>         .node("function_kw", "TerminalFunction")
>         .key_node("name", "TerminalIdentifier")
> ```

here too



_Code quote:_
```XML
        .node("function_kw", "TerminalFunction")
        .key_node("name", "TerminalIdentifier")
        .node("generic_params", "OptionWrappedGenericParamList")
        .node("signature", "FunctionSignature")
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1489)* status: 11 of 24 files reviewed, 3 unresolved discussions (waiting on @orizi, @spapinistarkware, and @yuvalsw)

___
*[`crates/parser/src/parser.rs` line 384 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1489#-NKDcDdsBiRPnXqIh85L:-NKDmGrzCCUVNxBtzv98:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/7aa2b95d5e06dce86eb0ce7c1ab647875631fe8e/crates/parser/src/parser.rs#L384)):*
> ```XML
> 
>     /// Assumes the current token is Function.
>     /// Expected pattern: `<FunctionSignature><Block>`
> ```

done
___
*[`crates/parser/src/parser.rs` line 422 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1489#-NKDcQjO-UYUIYYwHKkh:-NKDmI7b6-CBhLkzt6wo:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/7aa2b95d5e06dce86eb0ce7c1ab647875631fe8e/crates/parser/src/parser.rs#L422)):*
> ```XML
> 
>     /// Assumes the current token is Function.
>     /// Expected pattern: `<FunctionSignature><SemiColon>`
> ```

done
___
*[`crates/semantic/src/items/imp.rs` line 434 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1489#-NKDdOYp-tN_oFu5j8qu:-NKDmSjmDgk4oIkGB8kk:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/7aa2b95d5e06dce86eb0ce7c1ab647875631fe8e/crates/semantic/src/items/imp.rs#L434)):*
> ```XML
>         &mut diagnostics,
>         module_file_id,
>         &declaration.generic_params(db.upcast()),
> ```

done
___
*[`crates/syntax/src/node/helpers.rs` line 103 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1489#-NKDbbl33XqVeBvh7SFt:-NKDlBki8GIqlxnh3YXZ:b-x13h9l) ([raw file](https://github.com/starkware-libs/cairo/blob/7aa2b95d5e06dce86eb0ce7c1ab647875631fe8e/crates/syntax/src/node/helpers.rs#L103)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

add a trait NameGreen or something. Also impl it for ItemExternFunction
</blockquote></details>

Done.

but what is the benefit?
___
*[`crates/syntax_codegen/src/cairo_spec.rs` line 339 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1489#-NKDbDML-yltEjunxr5k:-NKDkl4xD8caFvJ4qaGP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7aa2b95d5e06dce86eb0ce7c1ab647875631fe8e/crates/syntax_codegen/src/cairo_spec.rs#L339)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

here too
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1489)* status: 11 of 24 files reviewed, 2 unresolved discussions (waiting on @orizi, @spapinistarkware, and @yuvalsw)

___
*[`crates/starknet/src/plugin.rs` line 198 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1489#-NKDdYb68e-5ACh-bhXP:-NKDoKodEpLBaf4C6x_J:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/7aa2b95d5e06dce86eb0ce7c1ab647875631fe8e/crates/starknet/src/plugin.rs#L198)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

consider inlining
</blockquote></details>

done.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 13 of 13 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1489#-:-NKDqRxiETw7wBCLOxam:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @spapinistarkware)

___
*[`crates/plugins/src/panicable.rs` line 26 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1489#-NKDp6Iv0f_e09egdw2n:-NKDp6Iv0f_e09egdw2o:b-brxd01) ([raw file](https://github.com/starkware-libs/cairo/blob/f25702764e8b9865127b1daed4bd2b14d0bbfe8d/crates/plugins/src/panicable.rs#L26)):*
> ```XML
>         };
> 
>         generate_panicable_code(db, declaration.name(db), declaration.signature(db), attributes)
> ```

TOK
Consider passing the declaration as a single arg.



_Code quote:_
```XML
generate_panicable_code
```
___
*[`crates/syntax/src/node/helpers.rs` line 103 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1489#-NKDbbl33XqVeBvh7SFt:-NKDqEIR-TD_-1Z7IYsp:bnc1uqm) ([raw file](https://github.com/starkware-libs/cairo/blob/7aa2b95d5e06dce86eb0ce7c1ab647875631fe8e/crates/syntax/src/node/helpers.rs#L103)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Done.

but what is the benefit?
</blockquote></details>

That the API remains consistent - can't change in one without noticing the others
___
*[`crates/syntax/src/node/helpers.rs` line 96 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1489#-NKDq5aKB2u2-aDAONWE:-NKDq5aKB2u2-aDAONWF:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/f25702764e8b9865127b1daed4bd2b14d0bbfe8d/crates/syntax/src/node/helpers.rs#L96)):*
> ```XML
> 
> pub trait NameGreen {
>     fn name_green(self, db: &dyn SyntaxGroup) -> TerminalIdentifierGreen;
> ```

doc



_Code quote:_
```XML
pub trait NameGreen {
    fn name_green(self, db: &dyn SyntaxGroup) -> TerminalIdentifierGreen;
}
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1489)* status: 22 of 24 files reviewed, all discussions resolved (waiting on @orizi, @spapinistarkware, and @yuvalsw)

___
*[`crates/plugins/src/panicable.rs` line 26 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1489#-NKDp6Iv0f_e09egdw2n:-NKDsyhD-Q7epev2Zt79:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/f25702764e8b9865127b1daed4bd2b14d0bbfe8d/crates/plugins/src/panicable.rs#L26)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

TOK
Consider passing the declaration as a single arg.
</blockquote></details>

done.
___
*[`crates/syntax/src/node/helpers.rs` line 96 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1489#-NKDq5aKB2u2-aDAONWE:-NKDrN_G6DkotxGBc8v1:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/f25702764e8b9865127b1daed4bd2b14d0bbfe8d/crates/syntax/src/node/helpers.rs#L96)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

doc
</blockquote></details>

done

**Review by yuvalsw — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1489)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware, @orizi, and @spapinistarkware)

___
*[`crates/syntax/src/node/helpers.rs` line 95 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1489#-NKDtDYO1_DS5B3lnC2N:-NKDtDYP3WBVzpbVsXqz:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a06a60bb7775e090ea2374247ec80c081780c8fd/crates/syntax/src/node/helpers.rs#L95)):*
> ```XML
> }
> 
> // Returns the TerminalIdentifierGreen of the `name` node.
> ```





_Suggestion:_
```XML
/// Returns
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1489)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi and @spapinistarkware)

___
*[`crates/syntax/src/node/helpers.rs` line 95 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1489#-NKDtDYO1_DS5B3lnC2N:-NKDucED2ywzAZMKwsRC:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/a06a60bb7775e090ea2374247ec80c081780c8fd/crates/syntax/src/node/helpers.rs#L95)):*
> ```XML
> }
> 
> // Returns the TerminalIdentifierGreen of the `name` node.
> ```

done.

**Review by yuvalsw — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1489)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware, @orizi, and @spapinistarkware)

___
*[`crates/syntax/src/node/helpers.rs` line 97 at r6](https://reviewable.io/reviews/starkware-libs/cairo/1489#-NKDyv8g0XEBwfeeJNrM:-NKDyv8g0XEBwfeeJNrN:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/153f376a71bcf979527108fc1419cc742a7e4703/crates/syntax/src/node/helpers.rs#L97)):*
> ```XML
> // Trait for ast object with a name terminal.
> pub trait NameGreen {
>     // Returns the TerminalIdentifierGreen of the `name` node.
> ```





_Suggestion:_
```XML
/// Trait for ast object with a name terminal.
pub trait NameGreen {
    /// Returns the TerminalIdentifierGreen of the `name` node.
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1489)* status: 22 of 24 files reviewed, all discussions resolved (waiting on @orizi, @spapinistarkware, and @yuvalsw)

___
*[`crates/syntax/src/node/helpers.rs` line 97 at r6](https://reviewable.io/reviews/starkware-libs/cairo/1489#-NKDyv8g0XEBwfeeJNrM:-NKEIncP4u8LjWQ-cbr4:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/153f376a71bcf979527108fc1419cc742a7e4703/crates/syntax/src/node/helpers.rs#L97)):*
> ```XML
> // Trait for ast object with a name terminal.
> pub trait NameGreen {
>     // Returns the TerminalIdentifierGreen of the `name` node.
> ```

done.

**Review by yuvalsw — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1489)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi and @spapinistarkware)

**Pull request merged**
