### PR TITLE
Add panic phase

### PR DESCRIPTION
**Pull request by spapinistarkware**
commit-id:f4d3b4e6

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 7 of 35 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1711)* status: 7 of 35 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLLtL_TEdYCEHApW7_F:-NLLtL_TEdYCEHApW7_G:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/ee3fabf048f760ef77d053e3d9ea38d874b35558/crates/cairo-lang-lowering/src/lower/scope.rs#L61)):*
> ```XML
>     /// Returns from the function. The value is a vector of the vars to be returned (not dropped).
>     Return { refs: Vec<LivingVar>, returns: Vec<LivingVar> },
>     /// TODO.
> ```

doc



_Code quote:_
```XML
    /// TODO.
```
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 256 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLLtUPp1ZwsmJpk2NJI:-NLLtUPp1ZwsmJpk2NJJ:bljob9k) ([raw file](https://github.com/starkware-libs/cairo/blob/ee3fabf048f760ef77d053e3d9ea38d874b35558/crates/cairo-lang-lowering/src/lower/scope.rs#L256)):*
> ```XML
>     /// Returns from the function.
>     Return { refs: Vec<UsableVariable>, returns: Vec<UsableVariable> },
>     /// Returns from the function.
> ```

fix doc



_Code quote:_
```XML
    /// Returns from the function.
```
___
*[`crates/cairo-lang-lowering/src/panic/mod.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLLuBGI3QsFvW5O6lIV:-NLLuBGI3QsFvW5O6lIW:b-4j0or6) ([raw file](https://github.com/starkware-libs/cairo/blob/ee3fabf048f760ef77d053e3d9ea38d874b35558/crates/cairo-lang-lowering/src/panic/mod.rs#L20)):*
> ```XML
> };
> 
> pub fn lower_panics(
> ```

doc
split into parts - this function is quite long.



_Code quote:_
```XML
pub fn lower_panics(
```
___
*[`crates/cairo-lang-lowering/src/panic/mod.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLLvIl96RTKvYO91txS:-NLLvIl96RTKvYO91txT:b-gbwhsz) ([raw file](https://github.com/starkware-libs/cairo/blob/ee3fabf048f760ef77d053e3d9ea38d874b35558/crates/cairo-lang-lowering/src/panic/mod.rs#L104)):*
> ```XML
> 
>                             let data_var = ctx.new_var(err_ty);
>                             // TODO: Fix refs.
> ```

add asignee.
explain what is the issue.



_Code quote:_
```XML
                            // TODO: Fix refs.
```
___
*[`crates/cairo-lang-lowering/src/panic/mod.rs` line 152 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLLv4FU6bKJP9eTuNAT:-NLLv4FU6bKJP9eTuNAU:b-qmlpbu) ([raw file](https://github.com/starkware-libs/cairo/blob/ee3fabf048f760ef77d053e3d9ea38d874b35558/crates/cairo-lang-lowering/src/panic/mod.rs#L152)):*
> ```XML
>             StructuredBlockEnd::Return { refs, returns } => {
>                 assert_eq!(
>                     returns.len(),
> ```

does this assume a unit type will always be included?



_Code quote:_
```XML
                assert_eq!(
                    returns.len(),
                    1,
                    "Panicable functions should be non-extern and thus have only 1 expr variables"
                );
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 35 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1711)* status: 34 of 35 files reviewed, 6 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 267 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLLwdGVCqZ2Zi0_Z9Gv:-NLLwdGVCqZ2Zi0_Z9Gw:bs21lrx) ([raw file](https://github.com/starkware-libs/cairo/blob/ee3fabf048f760ef77d053e3d9ea38d874b35558/crates/cairo-lang-lowering/src/lower/context.rs#L267)):*
> ```XML
>         refs: Vec<LivingVar>,
>         data: LivingVar,
>     },
> ```

why are those considered errors, this is very strange.



_Code quote:_
```XML
    Return {
        refs: Vec<LivingVar>,
        returns: Vec<LivingVar>,
    },
    Panic {
        refs: Vec<LivingVar>,
        data: LivingVar,
    },
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1711)* status: 34 of 35 files reviewed, 7 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLLwu2oC027r9JceWYu:-NLLwu2oC027r9JceWYv:b-tf4kco) ([raw file](https://github.com/starkware-libs/cairo/blob/ee3fabf048f760ef77d053e3d9ea38d874b35558/crates/cairo-lang-lowering/src/lower/mod.rs#L119)):*
> ```XML
> 
>         // If flow is not reachable anymore, no need to continue emitting statements.
>         let Err(err) = lowered_stmt else { continue; };
> ```

you are continuing in case there is no error, right?

doesn't that contradict the comment?



_Code quote:_
```XML
  let Err(err) = lowered_stmt else { continue; };
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1711)* status: 34 of 35 files reviewed, 8 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 217 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLLxiew-WkQvQGUNAvC:-NLLxiexDsMw1IR9HUR2:bwz3x3s) ([raw file](https://github.com/starkware-libs/cairo/blob/ee3fabf048f760ef77d053e3d9ea38d874b35558/crates/cairo-lang-lowering/src/lower/mod.rs#L217)):*
> ```XML
> // TODO(spapini): Use scope.current_refs.
> /// Returns the return variables, prefixed by the reference params. Wraps with PanicResult if
> /// needed.
> ```

is the part about PanicResult still true?

where is it done?



_Code quote:_
```XML
/// Returns the return variables, prefixed by the reference params. Wraps with PanicResult if
/// needed.
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1711)* status: 30 of 37 files reviewed, 8 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 267 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLLwdGVCqZ2Zi0_Z9Gv:-NLM305g6HpCUk4NBrx8:bxn4aog) ([raw file](https://github.com/starkware-libs/cairo/blob/ee3fabf048f760ef77d053e3d9ea38d874b35558/crates/cairo-lang-lowering/src/lower/context.rs#L267)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why are those considered errors, this is very strange.
</blockquote></details>

It's a FlowError. It's kind of abusing the Result and `?` mechanism, but whenever we have one of these, teh regular flow of expression computation should stop.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLLwu2oC027r9JceWYu:-NLM3FvO7-NHHVGUacqp:b-jybeyd) ([raw file](https://github.com/starkware-libs/cairo/blob/ee3fabf048f760ef77d053e3d9ea38d874b35558/crates/cairo-lang-lowering/src/lower/mod.rs#L119)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

you are continuing in case there is no error, right?

doesn't that contradict the comment?
</blockquote></details>

No error, means it is reachable.
If this statment passes to the next one, it means we have a flow error, and thus we are unreachable, and then, we don't need to continue with the loop.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 217 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLLxiew-WkQvQGUNAvC:-NLM3Wee7v9JEcdZwzch:b-knkl0z) ([raw file](https://github.com/starkware-libs/cairo/blob/ee3fabf048f760ef77d053e3d9ea38d874b35558/crates/cairo-lang-lowering/src/lower/mod.rs#L217)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

is the part about PanicResult still true?

where is it done?
</blockquote></details>

No. Thanks.
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLLtL_TEdYCEHApW7_F:-NLM42Z5DlcIfBozRvNY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ee3fabf048f760ef77d053e3d9ea38d874b35558/crates/cairo-lang-lowering/src/lower/scope.rs#L61)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 256 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLLtUPp1ZwsmJpk2NJI:-NLM56_mE42pyLPDEWua:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ee3fabf048f760ef77d053e3d9ea38d874b35558/crates/cairo-lang-lowering/src/lower/scope.rs#L256)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/panic/mod.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLLuBGI3QsFvW5O6lIV:-NLM55vc9dnuPYzgmZwt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ee3fabf048f760ef77d053e3d9ea38d874b35558/crates/cairo-lang-lowering/src/panic/mod.rs#L20)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
split into parts - this function is quite long.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/panic/mod.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLLvIl96RTKvYO91txS:-NLM4F9gCkiPaMmMGgrw:bze417e) ([raw file](https://github.com/starkware-libs/cairo/blob/ee3fabf048f760ef77d053e3d9ea38d874b35558/crates/cairo-lang-lowering/src/panic/mod.rs#L104)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add asignee.
explain what is the issue.
</blockquote></details>

Stale.
___
*[`crates/cairo-lang-lowering/src/panic/mod.rs` line 152 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLLv4FU6bKJP9eTuNAT:-NLM4LOL7i8Bh4TWuiEn:bc6nqwv) ([raw file](https://github.com/starkware-libs/cairo/blob/ee3fabf048f760ef77d053e3d9ea38d874b35558/crates/cairo-lang-lowering/src/panic/mod.rs#L152)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

does this assume a unit type will always be included?
</blockquote></details>

Yes. This is currently the behaviour though.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLLwu2oC027r9JceWYu:-NLM5v2N9Q74aSF7R1WT:b-rxlums) ([raw file](https://github.com/starkware-libs/cairo/blob/ee3fabf048f760ef77d053e3d9ea38d874b35558/crates/cairo-lang-lowering/src/lower/mod.rs#L119)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

No error, means it is reachable.
If this statment passes to the next one, it means we have a flow error, and thus we are unreachable, and then, we don't need to continue with the loop.
</blockquote></details>

why does error mean it is reachable?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLM6Qhf2fGXV9uge8Q4:-NLM6Qhf2fGXV9uge8Q5:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/832fcdcad2dac133723a33b13d369d715278a807/crates/cairo-lang-lowering/src/lower/scope.rs#L60)):*
> ```XML
>     /// expression).
>     Callsite(Option<LivingVar>),
>     /// Returns from the function. `refs` are the reverence variables (including implicits).
> ```





_Suggestion:_
```XML
reference
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLM6VAR6KiZn38RNUg5:-NLM6VAR6KiZn38RNUg6:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/832fcdcad2dac133723a33b13d369d715278a807/crates/cairo-lang-lowering/src/lower/scope.rs#L64)):*
> ```XML
>     /// functions).
>     Return { refs: Vec<LivingVar>, returns: Vec<LivingVar> },
>     /// Exits the function with a panic. `refs` are the reverence variables (including implicits).
> ```





_Suggestion:_
```XML
reference
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1711)* status: 35 of 37 files reviewed, 8 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLM6EZT6VMoL1Pr5ckh:-NLM6EZT6VMoL1Pr5cki:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/832fcdcad2dac133723a33b13d369d715278a807/crates/cairo-lang-lowering/src/lower/scope.rs#L61)):*
> ```XML
>     Callsite(Option<LivingVar>),
>     /// Returns from the function. `refs` are the reverence variables (including implicits).
>     /// `returns` are the regular return variables (1 for a user function, maybe more for external
> ```





_Suggestion:_
```XML
    /// Returns from the function. `refs` are the reference variables (including implicits).
    /// `returns` are the regular return variables (1 for a user function, maybe more for external
```
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLM6H-AA2X4DmjmML8w:-NLM6H-AA2X4DmjmML8x:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/832fcdcad2dac133723a33b13d369d715278a807/crates/cairo-lang-lowering/src/lower/scope.rs#L64)):*
> ```XML
>     /// functions).
>     Return { refs: Vec<LivingVar>, returns: Vec<LivingVar> },
>     /// Exits the function with a panic. `refs` are the reverence variables (including implicits).
> ```





_Suggestion:_
```XML
    /// Exits the function with a panic. `refs` are the reference variables (including implicits).
    /// `data` is the variable of the felt array with the panic data.
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1711)* status: 35 of 37 files reviewed, 8 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/panic/mod.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLM6byP25_tmvRYjxmD:-NLM6byP25_tmvRYjxmE:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/832fcdcad2dac133723a33b13d369d715278a807/crates/cairo-lang-lowering/src/panic/mod.rs#L21)):*
> ```XML
> };
> 
> pub fn lower_panics(
> ```

doc



_Code quote:_
```XML
pub fn lower_panics(
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1711)* status: 35 of 37 files reviewed, 8 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-generator/src/lifetime_test_data/match` line 141 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLM80Es3J4TB56pSGWo:-NLM80Es3J4TB56pSGWp:b-ukpkrx) ([raw file](https://github.com/starkware-libs/cairo/blob/832fcdcad2dac133723a33b13d369d715278a807/crates/cairo-lang-sierra-generator/src/lifetime_test_data/match#L141)):*
> ```
>   (v6: ()) <- struct_construct()
> End:
>   Return(v6)
> ```

did you have to fix that in the same PR?



_Code quote:_
```
 Return(v6)
```

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1711)* status: all files reviewed, 8 unresolved discussions (waiting on @spapinistarkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/panic/mod.rs` line 30 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLPCV7LAfTonSYkrpVv:-NLPCV7LAfTonSYkrpVw:b73za4o) ([raw file](https://github.com/starkware-libs/cairo/blob/832fcdcad2dac133723a33b13d369d715278a807/crates/cairo-lang-lowering/src/panic/mod.rs#L30)):*
> ```XML
>     ctx.variables = lowered.variables.clone();
> 
>     // Skip this phase for non panicable functions.
> ```

btw, for early return you don't need the reference information?



_Suggestion:_
```XML
 // non panicable functions, the conversion from structured to flat is trivial.
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 16 of 35 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1711)* status: all files reviewed, 11 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 267 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLLwdGVCqZ2Zi0_Z9Gv:-NLPIW3DC63R2ZdLwl8K:b-i0t3s0) ([raw file](https://github.com/starkware-libs/cairo/blob/ee3fabf048f760ef77d053e3d9ea38d874b35558/crates/cairo-lang-lowering/src/lower/context.rs#L267)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

It's a FlowError. It's kind of abusing the Result and `?` mechanism, but whenever we have one of these, teh regular flow of expression computation should stop.
</blockquote></details>

Can you give an example where this is useful?

in all the cases I found you could have return Ok(...) 



_Code quote:_
```XML
LoweringFlowError
```
___
*[`crates/cairo-lang-lowering/src/panic/mod.rs` line 148 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLPFHzj2UWXAgIvyaWQ:-NLPFHzj2UWXAgIvyaWR:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/832fcdcad2dac133723a33b13d369d715278a807/crates/cairo-lang-lowering/src/panic/mod.rs#L148)):*
> ```XML
>         // Extract return variable.
>         let mut outputs = call.outputs.clone();
>         let inner_value_var = outputs.pop().unwrap();
> ```





_Suggestion:_
```XML
orig_return_type
```
___
*[`crates/cairo-lang-lowering/src/panic/mod.rs` line 176 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLPEcZP5_S2xgpM6YX9:-NLPEcZP5_S2xgpM6YXA:b-wazrpv) ([raw file](https://github.com/starkware-libs/cairo/blob/832fcdcad2dac133723a33b13d369d715278a807/crates/cairo-lang-lowering/src/panic/mod.rs#L176)):*
> ```XML
>             self.db().upcast(),
>             "PanicResult",
>             vec![GenericArgumentId::Type(ty)],
> ```

This pattern repeats twice, can you make it a function?



_Code quote:_
```XML
        let call_ok_variant = get_enum_concrete_variant(
            self.db().upcast(),
            "PanicResult",
            vec![GenericArgumentId::Type(ty)],
            "Ok",
        );
        let call_err_variant = get_enum_concrete_variant(
            self.db().upcast(),
            "PanicResult",
            vec![GenericArgumentId::Type(ty)],
            "Err",
        );
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1711)* status: 35 of 37 files reviewed, 11 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 267 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLLwdGVCqZ2Zi0_Z9Gv:-NLPc6khExQ41vuuiyPx:b-katkr6) ([raw file](https://github.com/starkware-libs/cairo/blob/ee3fabf048f760ef77d053e3d9ea38d874b35558/crates/cairo-lang-lowering/src/lower/context.rs#L267)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Can you give an example where this is useful?

in all the cases I found you could have return Ok(...) 
</blockquote></details>

When you do this: 5 + {return x;}
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLLwu2oC027r9JceWYu:-NLPcE0hCT2gNJY4WSm_:b-1yse90) ([raw file](https://github.com/starkware-libs/cairo/blob/ee3fabf048f760ef77d053e3d9ea38d874b35558/crates/cairo-lang-lowering/src/lower/mod.rs#L119)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why does error mean it is reachable?
</blockquote></details>

LoweringFlowError is either Failed, Return, Panic or Unreachable. Failed means there is a real diagnostic somewhere. Others just means we got to a point that makes the current computation unreachable, like `5 + {panic();}`
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLM6Qhf2fGXV9uge8Q4:-NLPculP-xxn_Z3kyzhk:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/832fcdcad2dac133723a33b13d369d715278a807/crates/cairo-lang-lowering/src/lower/scope.rs#L60)):*
> ```XML
>     /// expression).
>     Callsite(Option<LivingVar>),
>     /// Returns from the function. `refs` are the reverence variables (including implicits).
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLM6EZT6VMoL1Pr5ckh:-NLPcvWfBs4pz3idGArU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/832fcdcad2dac133723a33b13d369d715278a807/crates/cairo-lang-lowering/src/lower/scope.rs#L61)):*
> ```XML
>     Callsite(Option<LivingVar>),
>     /// Returns from the function. `refs` are the reverence variables (including implicits).
>     /// `returns` are the regular return variables (1 for a user function, maybe more for external
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLM6VAR6KiZn38RNUg5:-NLPcwmI8tK1Hbeqgylo:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/832fcdcad2dac133723a33b13d369d715278a807/crates/cairo-lang-lowering/src/lower/scope.rs#L64)):*
> ```XML
>     /// functions).
>     Return { refs: Vec<LivingVar>, returns: Vec<LivingVar> },
>     /// Exits the function with a panic. `refs` are the reverence variables (including implicits).
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLM6H-AA2X4DmjmML8w:-NLPcx9lCVO0jLVK0JbH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/832fcdcad2dac133723a33b13d369d715278a807/crates/cairo-lang-lowering/src/lower/scope.rs#L64)):*
> ```XML
>     /// functions).
>     Return { refs: Vec<LivingVar>, returns: Vec<LivingVar> },
>     /// Exits the function with a panic. `refs` are the reverence variables (including implicits).
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/panic/mod.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLM6byP25_tmvRYjxmD:-NLPdCc20DMctTdbJGp8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/832fcdcad2dac133723a33b13d369d715278a807/crates/cairo-lang-lowering/src/panic/mod.rs#L21)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/panic/mod.rs` line 30 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLPCV7LAfTonSYkrpVv:-NLPdE7t3DXkyMevlQ_K:b-pfvmst) ([raw file](https://github.com/starkware-libs/cairo/blob/832fcdcad2dac133723a33b13d369d715278a807/crates/cairo-lang-lowering/src/panic/mod.rs#L30)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

btw, for early return you don't need the reference information?
</blockquote></details>

If I want to add early returns, then yes, I need the extra info.

Noted.
___
*[`crates/cairo-lang-lowering/src/panic/mod.rs` line 148 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLPFHzj2UWXAgIvyaWQ:-NLPddR58b9DCK9Zbrdt:b-bjpj7a) ([raw file](https://github.com/starkware-libs/cairo/blob/832fcdcad2dac133723a33b13d369d715278a807/crates/cairo-lang-lowering/src/panic/mod.rs#L148)):*
> ```XML
>         // Extract return variable.
>         let mut outputs = call.outputs.clone();
>         let inner_value_var = outputs.pop().unwrap();
> ```

Better?
___
*[`crates/cairo-lang-lowering/src/panic/mod.rs` line 176 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLPEcZP5_S2xgpM6YX9:-NLPeTaC2cecjxPVsNB3:b8go0a5) ([raw file](https://github.com/starkware-libs/cairo/blob/832fcdcad2dac133723a33b13d369d715278a807/crates/cairo-lang-lowering/src/panic/mod.rs#L176)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

This pattern repeats twice, can you make it a function?
</blockquote></details>

It's already one function call. I made it a bit shorter. Is this better?
___
*[`crates/cairo-lang-sierra-generator/src/lifetime_test_data/match` line 141 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLM80Es3J4TB56pSGWo:-NLPeZsa4XCwTi88rEt6:b2nhky0) ([raw file](https://github.com/starkware-libs/cairo/blob/832fcdcad2dac133723a33b13d369d715278a807/crates/cairo-lang-sierra-generator/src/lifetime_test_data/match#L141)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

did you have to fix that in the same PR?
</blockquote></details>

No.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/panic/mod.rs` line 176 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLPEcZP5_S2xgpM6YX9:-NLPj-uRBBZBODVRuEuF:bn2pvqg) ([raw file](https://github.com/starkware-libs/cairo/blob/832fcdcad2dac133723a33b13d369d715278a807/crates/cairo-lang-lowering/src/panic/mod.rs#L176)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

It's already one function call. I made it a bit shorter. Is this better?
</blockquote></details>

I mean a function that return both variants.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/lifetime_test_data/match` line 141 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLM80Es3J4TB56pSGWo:-NLPjISn5qu13iIcVbcn:bhgly4v) ([raw file](https://github.com/starkware-libs/cairo/blob/832fcdcad2dac133723a33b13d369d715278a807/crates/cairo-lang-sierra-generator/src/lifetime_test_data/match#L141)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

No.
</blockquote></details>

it would have been easier to review as a separate PR.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1711#-NLLwu2oC027r9JceWYu:-NLPlez4355hlW1ZQviS:b3mj061) ([raw file](https://github.com/starkware-libs/cairo/blob/ee3fabf048f760ef77d053e3d9ea38d874b35558/crates/cairo-lang-lowering/src/lower/mod.rs#L119)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

LoweringFlowError is either Failed, Return, Panic or Unreachable. Failed means there is a real diagnostic somewhere. Others just means we got to a point that makes the current computation unreachable, like `5 + {panic();}`
</blockquote></details>

I don't like it, but its not blocking.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 11 of 35 files at r1, 1 of 7 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1711#-:-NLPo8gUBnTsJ_P6ElVE:bnfp4nl)* status: 36 of 37 files reviewed, 4 unresolved discussions (waiting on @orizi and @spapinistarkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1711#-:-NLPq8_09ATKL2i7FsDB:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1711)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 30 of 35 files at r1, 5 of 7 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1711)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
