### PR TITLE
Made system argument implicit in storage_read and storage_write sysca…

### PR DESCRIPTION
**Pull request by yuvalsw**
…lls and in contract entry points

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1488)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1488)* status: 4 of 15 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/starknet/src/plugin_test_data/contract` line 49 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1488#-NKDRtXZD9tPmx2OcKP4:-NKDRtXZD9tPmx2OcKP5:bjyw1ov) ([raw file](https://github.com/starkware-libs/cairo/blob/94ab019f8898875746831f61ba62fff979eecc59/crates/starknet/src/plugin_test_data/contract#L49)):*
> ```
>                 panic(array::array_new::<felt>());
>             }
>             let mut __arg_system: felt = match array::array_at::<felt>(data, 0_u128) {
> ```

Remove the System argument from the contract.



_Code quote:_
```
__arg_system
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1488)* status: 4 of 15 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/starknet/src/plugin_test_data/contract` line 49 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1488#-NKDRtXZD9tPmx2OcKP4:-NKDSG4QCaQC2sQAcm4H:b-28g78s) ([raw file](https://github.com/starkware-libs/cairo/blob/94ab019f8898875746831f61ba62fff979eecc59/crates/starknet/src/plugin_test_data/contract#L49)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Remove the System argument from the contract.
</blockquote></details>

https://github.com/starkware-libs/cairo/blob/d90ca0ac47985396a2448071d5a33ad488bf85d3/crates/starknet/src/plugin_test_data/contract#L14

+ is it possible to format this file?

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1488)* status: 4 of 15 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/starknet/src/plugin_test_data/contract` line 49 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1488#-NKDRtXZD9tPmx2OcKP4:-NKDTBuK1fXXAIIyErri:b9ikjry) ([raw file](https://github.com/starkware-libs/cairo/blob/94ab019f8898875746831f61ba62fff979eecc59/crates/starknet/src/plugin_test_data/contract#L49)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

https://github.com/starkware-libs/cairo/blob/d90ca0ac47985396a2448071d5a33ad488bf85d3/crates/starknet/src/plugin_test_data/contract#L14

+ is it possible to format this file?
</blockquote></details>

1. Done.
2. What's wrong with the formatting?

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1488)* status: 3 of 15 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/starknet/src/plugin_test_data/contract` line 10 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1488#-NKDWJo10558eG4tmPdR:-NKDWJo10558eG4tmPdS:bmh9pn5) ([raw file](https://github.com/starkware-libs/cairo/blob/a967589b5d67c1346171ed09bbe96b4c3b8e6710/crates/starknet/src/plugin_test_data/contract#L10)):*
> ```
> mod TestContract {
> fn internal_func() -> felt {
>     1
> ```

please indent.



_Code quote:_
```
fn internal_func() -> felt {
    1
}

#[view]
fn get_something(ref arg: felt, num: felt) -> felt {
    1
}
#[external]
fn set_something(ref arg: felt, num: felt) {
}
}
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1488)* status: 3 of 15 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/starknet/src/plugin_test_data/contract` line 49 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1488#-NKDRtXZD9tPmx2OcKP4:-NKDWMBr32JcMYSjWad5:b-e5fzww) ([raw file](https://github.com/starkware-libs/cairo/blob/94ab019f8898875746831f61ba62fff979eecc59/crates/starknet/src/plugin_test_data/contract#L49)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

1. Done.
2. What's wrong with the formatting?

</blockquote></details>

2. no indentation of module items.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1488)* status: 3 of 15 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/starknet/src/plugin_test_data/contract` line 49 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1488#-NKDRtXZD9tPmx2OcKP4:-NKDeJLhDPiGjKe4VhWq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/94ab019f8898875746831f61ba62fff979eecc59/crates/starknet/src/plugin_test_data/contract#L49)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

2. no indentation of module items.
</blockquote></details>

Done.
___
*[`crates/starknet/src/plugin_test_data/contract` line 10 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1488#-NKDWJo10558eG4tmPdR:-NKDeIiY607XWf_5eSzm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a967589b5d67c1346171ed09bbe96b4c3b8e6710/crates/starknet/src/plugin_test_data/contract#L10)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

please indent.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 10 of 15 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1488#-:-NKDgsI69_Doahebcsgl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
