### PR TITLE
Use Star Impl Handling

### PR DESCRIPTION
**Pull request by Tomer-StarkWare**

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6765)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 1263 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6765#-OCmQ2H101HHCtD45ONK:-OCmQ2H101HHCtD45ONL:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c3d45cba4ab601ca5d9d9da54f0ca30081a01979/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L1263)):*
> ```
> //! > ==========================================================================
> 
> //! > Testing use star impl import
> ```





_Suggestion:_
```
//! > Testing use star import trait by impl.
```
___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 1321 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6765#-OCmQCPy4Y5j5h_exKQS:-OCmQCPy4Y5j5h_exKQT:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c3d45cba4ab601ca5d9d9da54f0ca30081a01979/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L1321)):*
> ```
> //! > ==========================================================================
> 
> //! > Testing use star struct import with trait
> ```





_Suggestion:_
```
//! > Testing use star struct import import trait.
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6765)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 1263 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6765#-OCmQ2H101HHCtD45ONK:-OCm_Iqh7N2Becu4g7FU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c3d45cba4ab601ca5d9d9da54f0ca30081a01979/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L1263)):*
> ```
> //! > ==========================================================================
> 
> //! > Testing use star impl import
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 1321 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6765#-OCmQCPy4Y5j5h_exKQS:-OCmZcfNAvCdfbZiy0FE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c3d45cba4ab601ca5d9d9da54f0ca30081a01979/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L1321)):*
> ```
> //! > ==========================================================================
> 
> //! > Testing use star struct import with trait
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6765)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1365 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6765#-OCmaNxU6MC7l_TqJbkS:-OCmaNxU6MC7l_TqJbkT:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/1b83dc8852f5be44f643c9ecb08838d707d27b3c/crates/cairo-lang-semantic/src/items/imp.rs#L1365)):*
> ```XML
>             uninferred_impls.insert(curr_uniferred_impl);
>         }
>     }
> ```





_Suggestion:_
```XML
    for (user_module, containing_module) in &db.priv_module_use_star_modules(module_id).accessible {
        if let Ok(star_module_uninferred_impls) = module_impl_ids(db, *user_module, *containing_module) {
            uninferred_impls.extend(star_module_uninferred_impls);
        }
    }
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6765)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 1321 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6765#-OCmbIufB9e9BdjvN_7j:-OCmbIufB9e9BdjvN_7k:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/1b83dc8852f5be44f643c9ecb08838d707d27b3c/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L1321)):*
> ```
> //! > ==========================================================================
> 
> //! > Testing use star struct import trait.
> ```





_Suggestion:_
```
//! > struct import impl through use star.
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6765)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 1321 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6765#-OCmbIufB9e9BdjvN_7j:-OCmcFXT1tBVCNWlM1PY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1b83dc8852f5be44f643c9ecb08838d707d27b3c/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L1321)):*
> ```
> //! > ==========================================================================
> 
> //! > Testing use star struct import trait.
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1365 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6765#-OCmaNxU6MC7l_TqJbkS:-OCmbB1s6Xb3i8RB6Rh2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1b83dc8852f5be44f643c9ecb08838d707d27b3c/crates/cairo-lang-semantic/src/items/imp.rs#L1365)):*
> ```XML
>             uninferred_impls.insert(curr_uniferred_impl);
>         }
>     }
> ```

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6765)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6765)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @gilbens-starkware, @integraledelebesgue, @mkaput, @piotmag769, and @Tomer-StarkWare)

___
*[`crates/cairo-lang-language-server/tests/test_data/code_actions/missing_trait.txt` line 111 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6765#-OCmhaG2CoGhvveWF0h1:-OCmhaG2CoGhvveWF0h2:b-q8nwtj) ([raw file](https://github.com/starkware-libs/cairo/blob/0d9de394455f51edb3ff93f2f5e9699859e5760b/crates/cairo-lang-language-server/tests/test_data/code_actions/missing_trait.txt#L111)):*
> ```help
>         x.some_me<caret>thod();
> Title: Import super::ATrait1
> Add new text: "use super::ATrait1;
> ```

discuss with gil.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6765#-:-OCmnuTTDMsypvKzFYGn:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, @gilbens-starkware, @integraledelebesgue, @mkaput, and @piotmag769)

**Pull request merged**
