### PR TITLE
Generic params semantic model

### PR DESCRIPTION
**Pull request by spapinistarkware**
commit-id:61590926

---

**Stack**:
- #2054
- #2053 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2053#-:-NNfq34u9ow4MT7qP8ft:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/resolve_path.rs` line 180 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2053#-NNfpydh4LHq6bQ_wFsF:-NNfpydh4LHq6bQ_wFsG:b-toku8a) ([raw file](https://github.com/starkware-libs/cairo/blob/221c434c2f255b406f8383f2776f0ef7a68cc069/crates/cairo-lang-semantic/src/resolve_path.rs#L180)):*
> ```XML
>     }
> 
>     pub fn add_generic_param(&mut self, generic_param: GenericParam) {
> ```

doc (include why this exists)



_Code quote:_
```XML
    pub fn add_generic_param(&mut self, generic_param: GenericParam) {
```
___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2053#-NNfoq752N_-b-1oow1M:-NNfoq752N_-b-1oow1N:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/221c434c2f255b406f8383f2776f0ef7a68cc069/crates/cairo-lang-semantic/src/items/generics.rs#L171)):*
> ```XML
> }
> 
> fn semantic_from_generic_param_ast(
> ```

doc



_Code quote:_
```XML
semantic_from_generic_param_ast(
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2053)* status: 19 of 21 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/resolve_path.rs` line 180 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2053#-NNfpydh4LHq6bQ_wFsF:-NNftEuk3kgg966-SQPc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/221c434c2f255b406f8383f2776f0ef7a68cc069/crates/cairo-lang-semantic/src/resolve_path.rs#L180)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc (include why this exists)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2053#-NNfoq752N_-b-1oow1M:-NNftR8HENc9XDr1QA9T:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/221c434c2f255b406f8383f2776f0ef7a68cc069/crates/cairo-lang-semantic/src/items/generics.rs#L171)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2053)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 19 of 21 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2053)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
