### PR TITLE
LS: Add an ability to generate tracing flamecharts

### PR DESCRIPTION
**Pull request by mkaput**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5201)

### CODE REVIEW

**Comment by mkaput** [comment]
Example flamegraph:

ls

It really would benefit from having tracing instrumentation within the compiler, though I would rather not spam `#[tracing::instrument]` calls virtually everywhere. I think this could be doable by forking Salsa and doing spans there, but I'm not motivated to make such a bold move yet.

**Review by orizi — APPROVED** [review]
i think since salsa is a query system - tracing over it is likely to be almost entirely useless.
having this limited to the LS part still makes more sense to me.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5201#-:-NsAYgEDD8YjjUgSoC66:b-i62v2s)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Review by mkaput — COMMENTED** [review]
> i think since salsa is a query system - tracing over it is likely to be almost entirely useless.  
> having this limited to the LS part still makes more sense to me.

I suspect that particular queries that are called in `refresh_diagnostics` are rather short, and the overall duration of this execution is so long because of the number of queries executed. That's why I don't feel motivated enough to hook tracing into Salsa, but who knows what will happen in the future :upside_down_face: So I wanted to leave a trace of this thought.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5201#-:-NsDFVOp3xHrt-6Sg7cr:bl9ynce)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5201)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Pull request merged**
