### PR TITLE
Made plugin correctly handle spaces in diagnostics.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #3993
- #3992 ⬅
- #3989

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3992)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3992)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/utils.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3992#-NdA9aKC4rRRIoXpHTlF:-NdA9aKC4rRRIoXpHTlG:b-7wa0ua) ([raw file](https://github.com/starkware-libs/cairo/blob/94fa21cfb47491c4da1fd0c03b0f87871d35f086/crates/cairo-lang-starknet/src/plugin/utils.rs#L52)):*
> ```XML
> /// Returns true if `type_ast` matches `$name$<$arg$>`.
> /// Does not resolve paths, type aliases or named generics.
> pub fn is_name_with_arg_type_expr(
> ```

as suggested in the previous PR - have this as a method of Expr. If not - rename to is_expr_name_with_arg
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs` line 367 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3992#-NdAArFNDiMJfRhISEYs:-NdAArFNDiMJfRhISEYt:by4wcc8) ([raw file](https://github.com/starkware-libs/cairo/blob/94fa21cfb47491c4da1fd0c03b0f87871d35f086/crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs#L367)):*
> ```XML
> }
> 
> /// Returns whether the given parameter is valid as the first parameter of a function in an impl
> ```

sounds like a boolean. Please describe the return value



_Code quote:_
```XML
Returns whether
```

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3992)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3992)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs` line 367 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3992#-NdAArFNDiMJfRhISEYs:-NdAfhM-7e9YVbNa5LRz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/94fa21cfb47491c4da1fd0c03b0f87871d35f086/crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs#L367)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

sounds like a boolean. Please describe the return value
</blockquote></details>

Done.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3992#-:-NdB-wx31mUWrzQyuCjT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
