### PR TITLE
Made storage read use the builder - bug fixing on the way.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:97eecc70

---

**Stack**:
- #1391
- #1386 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1386#-:-NJdYoEs9aIAcVnE07or:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/sierra_to_casm/src/invocations/starknet/storage.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1386#-NJdXWVI0njJKNInc7SC:-NJdXWVI0njJKNInc7SD:brovtcw) ([raw file](https://github.com/starkware-libs/cairo/blob/459d956e870f9b66bd0cb96ee985bcced775eef0/crates/sierra_to_casm/src/invocations/starknet/storage.rs#L51)):*
> ```XML
>         a: system_base,
>         b: deref_or_immediate!(system_offset),
>     }));
> ```

Consider defining the res_operand once and cloning it.



_Code quote:_
```XML
    let original_system = casm_builder.add_var(ResOperand::BinOp(BinOpOperand {
        op: Operation::Add,
        a: system_base,
        b: deref_or_immediate!(system_offset),
    }));
```
___
*[`crates/sierra_to_casm/src/invocations/starknet/storage.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1386#-NJdYFCI9lTNfuANHj0Z:-NJdYFCI9lTNfuANHj0_:bcefv09) ([raw file](https://github.com/starkware-libs/cairo/blob/459d956e870f9b66bd0cb96ee985bcced775eef0/crates/sierra_to_casm/src/invocations/starknet/storage.rs#L65)):*
> ```XML
> 
>     let CasmBuildResult { instructions, fallthrough_state, .. } = casm_builder.build();
>     // TODO(orizi): Extract the assertion out of the libfunc implementation.
> ```

Are you talking about:
 assert *(system++) = read_value;



_Suggestion:_
```XML
Extract the last assertion out of the libfunc implementation.
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1386)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/sierra_to_casm/src/invocations/starknet/storage.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1386#-NJdXWVI0njJKNInc7SC:-NJdfS4b97uJiD4OcHlk:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fdee65e32d18eb2a9ad06e1fab01ab5cd35e564a/crates/sierra_to_casm/src/invocations/starknet/storage.rs#L51)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Consider defining the res_operand once and cloning it.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1386#-:-NJe56pt90bsKcfHyWc_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1386)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
