### PR TITLE
Fix semantic error in test.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2993)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2993)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/inline/test_data/inline` line 83 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2993#-NUL_AmO0VKf5NLhSLiw:-NUL_AmP3itDAqugzUzN:b9hwh9k) ([raw file](https://github.com/starkware-libs/cairo/blob/f37f25dc00cf0f94b16d2e2a9d97e7a276ccab56/crates/cairo-lang-lowering/src/inline/test_data/inline#L83)):*
> ```
> 
> //! > comments
> //TODO(spapini): try to inline this anyway.
> ```

What kind of an inline test is this? Did you mean to add a `#[inline]` attribute?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2993)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/test_data/inline` line 83 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2993#-NUL_AmO0VKf5NLhSLiw:-NULkAkWEHwxukA-zBLf:b-mvv2sx) ([raw file](https://github.com/starkware-libs/cairo/blob/f37f25dc00cf0f94b16d2e2a9d97e7a276ccab56/crates/cairo-lang-lowering/src/inline/test_data/inline#L83)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

What kind of an inline test is this? Did you mean to add a `#[inline]` attribute?
</blockquote></details>

yes, thanks.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2993)* status: 0 of 2 files reviewed, all discussions resolved

___
*[`crates/cairo-lang-lowering/src/inline/test_data/inline` line 83 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2993#-NUL_AmO0VKf5NLhSLiw:-NUMnE8UAI8zljwy4Otx:b371bw2) ([raw file](https://github.com/starkware-libs/cairo/blob/f37f25dc00cf0f94b16d2e2a9d97e7a276ccab56/crates/cairo-lang-lowering/src/inline/test_data/inline#L83)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

yes, thanks.
</blockquote></details>

Remove my TODO:)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2993#-:-NUQcEje3GsasKSMZmaf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2993)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
