### PR TITLE
Now capable of reordering additional stmts.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3696)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/local_variables_test_data/construct_enum` line 38 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3696#-N_bYVBsCTqafb92Hl_Y:-N_bYVBsCTqafb92Hl_Z:b-m5th7k) ([raw file](https://github.com/starkware-libs/cairo/blob/0001582cd9d455664a241a315516e25992a2e570/crates/cairo-lang-sierra-generator/src/local_variables_test_data/construct_enum#L38)):*
> ```
> 
> //! > local_variables
> v1
> ```

you broke the test.



_Code quote:_
```
v1
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 14 of 38 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3696)* status: 14 of 38 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/lifetime_test_data/enum` line 92 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3696#-N_bYDarAu8kcg9W27pV:-N_bYDarAu8kcg9W27pW:b1sbaxk) ([raw file](https://github.com/starkware-libs/cairo/blob/0001582cd9d455664a241a315516e25992a2e570/crates/cairo-lang-sierra-generator/src/lifetime_test_data/enum#L92)):*
> ```
> PostStatement((BlockId(2), 2)): v12
> PostStatement((BlockId(1), 3)): v8
> PostStatement((BlockId(1), 1)): v6
> ```

Note that you've somewhat changed the test.
Not sure how to fix it though.



_Code quote:_
```
PostStatement((BlockId(3), 1)): v17
PostStatement((BlockId(2), 2)): v12
PostStatement((BlockId(1), 3)): v8
PostStatement((BlockId(1), 1)): v6
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/local_variables_test_data/struct` line 89 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3696#-N_bYmiwArBboEJFhBeO:-N_bYmiwArBboEJFhBeP:b-h440oz) ([raw file](https://github.com/starkware-libs/cairo/blob/0001582cd9d455664a241a315516e25992a2e570/crates/cairo-lang-sierra-generator/src/local_variables_test_data/struct#L89)):*
> ```
> 
> //! > local_variables
> v2
> ```

the test is broken.



_Code quote:_
```
v2
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 38 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3696)* status: 17 of 38 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`tests/test_data/enum_flow.sierra` line 63 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3696#-N_bZgKB0zR7-bqFTokP:-N_bZgKB0zR7-bqFTokQ:bwk321b) ([raw file](https://github.com/starkware-libs/cairo/blob/0001582cd9d455664a241a315516e25992a2e570/tests/test_data/enum_flow.sierra#L63)):*
> ```
> drop<felt252>([18]) -> ();
> felt252_const<30>() -> ([20]);
> enum_init<examples::enum_flow::MyEnumGeneric::<(), core::felt252>, 0>([20]) -> ([21]);
> ```

seems like you've somewhat broke this test case.



_Code quote:_
```
enum_init<examples::enum_flow::MyEnumGeneric::<(), core::felt252>, 0>([20]) -> ([21]);
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3696)* status: 17 of 38 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/local_variables_test_data/construct_enum` line 38 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3696#-N_bYVBsCTqafb92Hl_Y:-N_bdz8j8yG_3euLVQ8R:b-95294y) ([raw file](https://github.com/starkware-libs/cairo/blob/0001582cd9d455664a241a315516e25992a2e570/crates/cairo-lang-sierra-generator/src/local_variables_test_data/construct_enum#L38)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

you broke the test.
</blockquote></details>

none of the tests were broken - the issue is that the optimization changes the meaning of the tests.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/local_variables_test_data/construct_enum` line 38 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3696#-N_bYVBsCTqafb92Hl_Y:-N_bnKqw9FQcYNnwYAGg:b-2o1con) ([raw file](https://github.com/starkware-libs/cairo/blob/0001582cd9d455664a241a315516e25992a2e570/crates/cairo-lang-sierra-generator/src/local_variables_test_data/construct_enum#L38)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

none of the tests were broken - the issue is that the optimization changes the meaning of the tests.
</blockquote></details>

this test is clear testing that x is assigned a local variable.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3696)* status: 17 of 38 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/local_variables_test_data/construct_enum` line 38 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3696#-N_bYVBsCTqafb92Hl_Y:-N_bu9Px0zNEPVh3vCY7:b-nea34u) ([raw file](https://github.com/starkware-libs/cairo/blob/0001582cd9d455664a241a315516e25992a2e570/crates/cairo-lang-sierra-generator/src/local_variables_test_data/construct_enum#L38)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

this test is clear testing that x is assigned a local variable.
</blockquote></details>

true - but it no longer needs to be assigned to a local variable.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3696)* status: 10 of 38 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/local_variables_test_data/struct` line 89 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3696#-N_bYmiwArBboEJFhBeO:-N_nFyRU3wBh-IwTYDKg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0001582cd9d455664a241a315516e25992a2e570/crates/cairo-lang-sierra-generator/src/local_variables_test_data/struct#L89)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

the test is broken.
</blockquote></details>

Done.
___
*[`tests/test_data/enum_flow.sierra` line 63 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3696#-N_bZgKB0zR7-bqFTokP:-N_nG0C0ESZzZOmz9EJa:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0001582cd9d455664a241a315516e25992a2e570/tests/test_data/enum_flow.sierra#L63)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

seems like you've somewhat broke this test case.
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/test_data/enums` line 8 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3696#-Na0JXic7dwq3mjwqkr-:-Na0JXic7dwq3mjwqkr0:b-b972xs) ([raw file](https://github.com/starkware-libs/cairo/blob/4ea9a63a286e3d6fb7be18e304f4e6d8b2df8bec/crates/cairo-lang-lowering/src/test_data/enums#L8)):*
> ```
> //! > function
> fn foo(a: felt252) -> MyEnum {
>     immovable(true);
> ```

consider adding DoNotOptimize to std lib.
similar to:
https://github.com/google/benchmark/blob/e451e50e9b8af453f076dec10bd6890847f1624e/include/benchmark/benchmark.h#L349-L356



_Code quote:_
```
immovable
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 10 of 38 files at r1, 19 of 20 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3696)* status: 37 of 38 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/test_data/generics` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3696#-Na0HoYKCkCn_TnkR6lN:-Na0HoYKCkCn_TnkR6lO:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/4ea9a63a286e3d6fb7be18e304f4e6d8b2df8bec/crates/cairo-lang-lowering/src/test_data/generics#L1)):*
> ```
> //! > Test extern function calling.
> ```





_Suggestion:_
```
Test calling trait function.
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3696)* status: 37 of 38 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/test_data/enums` line 8 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3696#-Na0JXic7dwq3mjwqkr-:-Na0NPL71-bKM5_UOtjE:b7z4i7v) ([raw file](https://github.com/starkware-libs/cairo/blob/4ea9a63a286e3d6fb7be18e304f4e6d8b2df8bec/crates/cairo-lang-lowering/src/test_data/enums#L8)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

consider adding DoNotOptimize to std lib.
similar to:
https://github.com/google/benchmark/blob/e451e50e9b8af453f076dec10bd6890847f1624e/include/benchmark/benchmark.h#L349-L356
</blockquote></details>

i don't think this can work for us just yet - as this has additional costs - the function call itself.
we probably need to add an actual extern to perform this - and this is not for this PR.
___
*[`crates/cairo-lang-lowering/src/test_data/generics` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3696#-Na0HoYKCkCn_TnkR6lN:-Na0OlmSAS4TqMV9_OqK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4ea9a63a286e3d6fb7be18e304f4e6d8b2df8bec/crates/cairo-lang-lowering/src/test_data/generics#L1)):*
> ```
> //! > Test extern function calling.
> ```

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 20 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3696#-:-Na0P4a75RpnVtUeG4ie:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @orizi)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 15 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3696)* status: 25 of 38 files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3696)* status: 26 of 38 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 15 of 15 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3696)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
