### PR TITLE
Add Statement -> Source locations mappings to sierra debug info

### PR DESCRIPTION
**Pull request by MaksymilianDemitraszek**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6144)

### CODE REVIEW

**Comment by MaksymilianDemitraszek** [comment]
This PR is a foundation for https://github.com/software-mansion/scarb/pull/1506. 
This mapping, and the one introduced for cairo-profiler, are going to be used by a new tool we are working on, cairo-coverage.

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 7 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6144)* status: 7 of 8 files reviewed, 7 unresolved discussions (waiting on @MaksymilianDemitraszek)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6144#-O3YuwIEAv0WDsUPTnh9:-O3YuwIEAv0WDsUPTnhA:b-rzvdln) (no related file):*
Please correctly handle the compiler config in `compile_prepared_db_program_artifact` too (Scarb uses it for `lib` target, I know we don't really need it, but this way Scarb will be consistent when adding mappings to artifacts)

___
___
*[`crates/cairo-lang-compiler/src/lib.rs` line 278 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6144#-O3Ype469Z5J2eT7sqfh:-O3Ype469Z5J2eT7sqfi:bfkdcj6) ([raw file](https://github.com/starkware-libs/cairo/blob/2a595ab8fdad8c8ead794e4e57b628ef9380ee6b/crates/cairo-lang-compiler/src/lib.rs#L278)):*
> ```XML
>     }
> 
>     let mut annotations = if add_statements_functions {
> ```

[nit] Would be more readable to start with `let mut annotations = Annotations::default()`
___
*[`crates/cairo-lang-sierra-generator/src/statements_code_locations.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6144#-O3YtYjGBSDPhHTQxw4g:-O3YtYjGBSDPhHTQxw4h:butifqa) ([raw file](https://github.com/starkware-libs/cairo/blob/2a595ab8fdad8c8ead794e4e57b628ef9380ee6b/crates/cairo-lang-sierra-generator/src/statements_code_locations.rs#L12)):*
> ```XML
> 
> #[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
> pub struct SourceCodeLocation {
> ```

Seems like equivalent of `TextPosition` which seems stable (unchanged from 08/2022)
___
*[`crates/cairo-lang-sierra-generator/src/statements_code_locations.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6144#-O3Yq7Cp0_3m_TFjckhs:-O3Yq7Cp0_3m_TFjckht:b-t8eocb) ([raw file](https://github.com/starkware-libs/cairo/blob/2a595ab8fdad8c8ead794e4e57b628ef9380ee6b/crates/cairo-lang-sierra-generator/src/statements_code_locations.rs#L25)):*
> ```XML
> }
> 
> /// The mapping from sierra statement index to fully qualified Cairo path of the Cairo function TODO
> ```

TODO, incorrect comment
___
*[`crates/cairo-lang-sierra-generator/src/statements_locations.rs` line 149 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6144#-O3YwR4t4eeN98xCitz1:-O3YwR4t4eeN98xCitz2:b-iridmp) ([raw file](https://github.com/starkware-libs/cairo/blob/2a595ab8fdad8c8ead794e4e57b628ef9380ee6b/crates/cairo-lang-sierra-generator/src/statements_locations.rs#L149)):*
> ```XML
>     let file_full_path = location.file_id(db.upcast()).full_path(db.upcast());
>     let location = location.diagnostic_location(db.upcast());
>     let position = location.span.position_in_file(db.upcast(), location.file_id);
> ```

If you want it to map to the actual user code then call `user_location` at the end of this line. If you want the mapping to point to the location AFTER macro expansion etc. then keep in mind `file_full_path` in your code is a real file path even for `VirtualFile`
___
*[`crates/cairo-lang-starknet/src/compile.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6144#-O3YrO3y15HPb5_qB1gm:-O3YrO3y15HPb5_qB1gn:bglglrq) ([raw file](https://github.com/starkware-libs/cairo/blob/2a595ab8fdad8c8ead794e4e57b628ef9380ee6b/crates/cairo-lang-starknet/src/compile.rs#L151)):*
> ```XML
>     };
> 
>     let mut annotations = if compiler_config.add_statements_functions {
> ```

Vide supra
___
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 133 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6144#-O3YrSq8-XckCGTzPGRq:-O3YrSq8-XckCGTzPGRr:bglglrq) ([raw file](https://github.com/starkware-libs/cairo/blob/2a595ab8fdad8c8ead794e4e57b628ef9380ee6b/crates/cairo-lang-test-plugin/src/lib.rs#L133)):*
> ```XML
>     replacer.enrich_function_names(&mut sierra_program);
> 
>     let (mut annotations, statements_functions_for_tests) =
> ```

Vide supra

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6144)* status: all files reviewed, 7 unresolved discussions (waiting on @MaksymilianDemitraszek)

**Review by piotmag769 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6144)* status: all files reviewed, 7 unresolved discussions (waiting on @MaksymilianDemitraszek)

___
*[`crates/cairo-lang-sierra-generator/src/statements_locations.rs` line 149 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6144#-O3YwR4t4eeN98xCitz1:-O3ZFvuw3TCRP9ZrR28u:boxyfh) ([raw file](https://github.com/starkware-libs/cairo/blob/2a595ab8fdad8c8ead794e4e57b628ef9380ee6b/crates/cairo-lang-sierra-generator/src/statements_locations.rs#L149)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

If you want it to map to the actual user code then call `user_location` at the end of this line. If you want the mapping to point to the location AFTER macro expansion etc. then keep in mind `file_full_path` in your code is a real file path even for `VirtualFile`
</blockquote></details>

I remember our discussion now: since you don't want original user location here, you shouldn't use `FileId::full_path` above: it will always return the path of the closest parent of `VirtualFile` that is  of variant `OnDisk`, effectively making the mapping incorrect

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6144)* status: all files reviewed, 3 unresolved discussions (waiting on @MaksymilianDemitraszek)

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6144)* status: 3 of 8 files reviewed, 3 unresolved discussions (waiting on @MaksymilianDemitraszek)

___
*[`crates/cairo-lang-sierra-generator/src/statements_code_locations.rs` line 26 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6144#-O3bNyqDDDxCSchyqjnW:-O3bNyqDDDxCSchyqjnX:b-hsq40i) ([raw file](https://github.com/starkware-libs/cairo/blob/7561f16a80e6024f684b65a8a5cd816aca03ff49/crates/cairo-lang-sierra-generator/src/statements_code_locations.rs#L26)):*
> ```XML
> /// The mapping between sierra statement indexes and lines in cairo code
> /// (if obtainable) which caused the statement to be generated. Should be created using
> /// [`crate::statements_locations::StatementsLocations::extract_statements_functions`].
> ```

Still incorrect (wrong function)
___
*[`crates/cairo-lang-sierra-generator/src/statements_locations.rs` line 149 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6144#-O3YwR4t4eeN98xCitz1:-O3bO99I3Aw63gKAoti6:b-9npmeh) ([raw file](https://github.com/starkware-libs/cairo/blob/2a595ab8fdad8c8ead794e4e57b628ef9380ee6b/crates/cairo-lang-sierra-generator/src/statements_locations.rs#L149)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

I remember our discussion now: since you don't want original user location here, you shouldn't use `FileId::full_path` above: it will always return the path of the closest parent of `VirtualFile` that is  of variant `OnDisk`, effectively making the mapping incorrect
</blockquote></details>

As discussed offline, my first comment was correct, just use `user_location` here
___
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 133 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6144#-O3bRVhmC6K_60saqagJ:-O3bRVhmC6K_60saqagK:b-cnkzr2) ([raw file](https://github.com/starkware-libs/cairo/blob/7561f16a80e6024f684b65a8a5cd816aca03ff49/crates/cairo-lang-test-plugin/src/lib.rs#L133)):*
> ```XML
>     replacer.enrich_function_names(&mut sierra_program);
> 
>     let statements_functions_for_tests = Some(debug_info.statements_locations.get_statements_functions_map_for_tests(db));
> ```

Please keep the logic (produce it only if `add_statements_functions` is true).

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6144)* status: all files reviewed, 3 unresolved discussions (waiting on @MaksymilianDemitraszek)

**Review by MaksymilianDemitraszek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6144)* status: all files reviewed, 2 unresolved discussions (waiting on @piotmag769)

___
*[`crates/cairo-lang-compiler/src/lib.rs` line 278 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6144#-O3Ype469Z5J2eT7sqfh:-O3azXw04l4hndr_m8-k:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2a595ab8fdad8c8ead794e4e57b628ef9380ee6b/crates/cairo-lang-compiler/src/lib.rs#L278)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

[nit] Would be more readable to start with `let mut annotations = Annotations::default()`
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/statements_code_locations.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6144#-O3YtYjGBSDPhHTQxw4g:-O3azasb4arFKeV5a2rB:bjkzpkf) ([raw file](https://github.com/starkware-libs/cairo/blob/2a595ab8fdad8c8ead794e4e57b628ef9380ee6b/crates/cairo-lang-sierra-generator/src/statements_code_locations.rs#L12)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Seems like equivalent of `TextPosition` which seems stable (unchanged from 08/2022)
</blockquote></details>

I know, I made a concious decision to not expose the internal structures. 
___
*[`crates/cairo-lang-sierra-generator/src/statements_code_locations.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6144#-O3Yq7Cp0_3m_TFjckhs:-O3bKZdy2jG_FB--cbgL:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2a595ab8fdad8c8ead794e4e57b628ef9380ee6b/crates/cairo-lang-sierra-generator/src/statements_code_locations.rs#L25)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

TODO, incorrect comment
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/statements_code_locations.rs` line 26 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6144#-O3bNyqDDDxCSchyqjnW:-O3be8784h1zepRkPRbc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7561f16a80e6024f684b65a8a5cd816aca03ff49/crates/cairo-lang-sierra-generator/src/statements_code_locations.rs#L26)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Still incorrect (wrong function)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/compile.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6144#-O3YrO3y15HPb5_qB1gm:-O3azVm9CDOHSCKFTXM-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2a595ab8fdad8c8ead794e4e57b628ef9380ee6b/crates/cairo-lang-starknet/src/compile.rs#L151)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Vide supra
</blockquote></details>

Done.
___
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 133 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6144#-O3YrSq8-XckCGTzPGRq:-O3azUef0mg1tf6SGBOd:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2a595ab8fdad8c8ead794e4e57b628ef9380ee6b/crates/cairo-lang-test-plugin/src/lib.rs#L133)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Vide supra
</blockquote></details>

Done.

**Review by MaksymilianDemitraszek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6144)* status: all files reviewed, 2 unresolved discussions (waiting on @piotmag769)

___
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 133 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6144#-O3bRVhmC6K_60saqagJ:-O3bg6g71P-T5oY9AvTo:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7561f16a80e6024f684b65a8a5cd816aca03ff49/crates/cairo-lang-test-plugin/src/lib.rs#L133)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Please keep the logic (produce it only if `add_statements_functions` is true).
</blockquote></details>

Done.

**Review by piotmag769 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6144#-:-O3bosgq58ardpGThxHN:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r1, 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6144)* status: all files reviewed, 1 unresolved discussion (waiting on @MaksymilianDemitraszek)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6144#-O3bz_Rs7nqkMHwTdAhf:-O3bz_Rt-LM8zV5Rw68L:bmmere) (no related file):*
@ilyalesokhin-starkware 

___
___
*[`crates/cairo-lang-sierra-generator/src/statements_locations.rs` line 143 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6144#-O3bzMjh9lFVim2gg7ps:-O3bzMjiETA0iNK9UIkh:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/e512d6dd152eb0d470c8604979ff411eee26a355/crates/cairo-lang-sierra-generator/src/statements_locations.rs#L143)):*
> ```XML
> }
> 
> pub fn maybe_code_location(
> ```

doc

**Review by MaksymilianDemitraszek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6144)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @orizi and @piotmag769)

___
*[`crates/cairo-lang-sierra-generator/src/statements_locations.rs` line 143 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6144#-O3bzMjh9lFVim2gg7ps:-O3c168Y0c3P1PpfkfQV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e512d6dd152eb0d470c8604979ff411eee26a355/crates/cairo-lang-sierra-generator/src/statements_locations.rs#L143)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 4 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6144)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MaksymilianDemitraszek)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6144#-O3bz_Rs7nqkMHwTdAhf:-O3hXR2TCw7TL41QaVed:b6sarx4) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

@ilyalesokhin-starkware
</blockquote></details>

@ilyalesokhin-starkware please have a look as well.

___

**Review by orizi — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 1 of 8 files at r1, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6144#-:-O3w3i017RYgoHBJ4e2h:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @MaksymilianDemitraszek)

___
*[`crates/cairo-lang-sierra-generator/src/statements_code_locations.rs` line 9 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6144#-O3w3oqZCZlpAYgTsKW0:-O3w3oqZCZlpAYgTsKW1:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/a3d4681e24f730a3f2d561ec129dcff5e01fc3c9/crates/cairo-lang-sierra-generator/src/statements_code_locations.rs#L9)):*
> ```XML
> 
> #[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
> pub struct SourceFileFullPath(pub String);
> ```

doc
___
*[`crates/cairo-lang-sierra-generator/src/statements_code_locations.rs` line 12 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6144#-O3w3pT1AjrytWmFkrs1:-O3w3pT1AjrytWmFkrs2:b-301l6m) ([raw file](https://github.com/starkware-libs/cairo/blob/a3d4681e24f730a3f2d561ec129dcff5e01fc3c9/crates/cairo-lang-sierra-generator/src/statements_code_locations.rs#L12)):*
> ```XML
> 
> #[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
> pub struct SourceCodeLocation {
> ```

doc struct
___
*[`crates/cairo-lang-sierra-generator/src/statements_code_locations.rs` line 20 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6144#-O3w3qWC2Q90vP2bZQc-:-O3w3qWC2Q90vP2bZQc0:b56z60i) ([raw file](https://github.com/starkware-libs/cairo/blob/a3d4681e24f730a3f2d561ec129dcff5e01fc3c9/crates/cairo-lang-sierra-generator/src/statements_code_locations.rs#L20)):*
> ```XML
> 
> #[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
> pub struct SourceCodeSpan {
> ```

doc struct and members
___
*[`crates/cairo-lang-sierra-generator/src/statements_code_locations.rs` line 25 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6144#-O3w3sl80W4IQFs7msBV:-O3w3sl80W4IQFs7msBW:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a3d4681e24f730a3f2d561ec129dcff5e01fc3c9/crates/cairo-lang-sierra-generator/src/statements_code_locations.rs#L25)):*
> ```XML
> }
> /// The mapping between sierra statement indexes and locations in cairo code
> /// (if obtainable) which caused the statement to be generated. Should be created using
> ```





_Suggestion:_
```XML
    pub end: SourceCodeLocation,
}

/// The mapping between sierra statement indexes and locations in cairo code
/// (if obtainable) which caused the statement to be generated. Should be created using
```
___
*[`crates/cairo-lang-sierra-generator/src/statements_locations.rs` line 161 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6144#-O3w40iM1_jLnywCxcHU:-O3w40iM1_jLnywCxcHV:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a3d4681e24f730a3f2d561ec129dcff5e01fc3c9/crates/cairo-lang-sierra-generator/src/statements_locations.rs#L161)):*
> ```XML
>     } else {
>         None
>     }
> ```





_Suggestion:_
```XML
    let position = location.span.position_in_file(db.upcast(), location.file_id)?;
    let source_location = SourceCodeSpan {
        start: SourceCodeLocation { col: position.start.col, line: position.start.line },
        end: SourceCodeLocation { col: position.start.col, line: position.start.line },
    };

    Some((SourceFileFullPath(file_full_path), source_location))
```

**Review by MaksymilianDemitraszek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6144)* status: 4 of 8 files reviewed, 5 unresolved discussions (waiting on @orizi and @piotmag769)

___
*[`crates/cairo-lang-sierra-generator/src/statements_code_locations.rs` line 9 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6144#-O3w3oqZCZlpAYgTsKW0:-O4e0CLc8LN4Ix5sZ43B:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a3d4681e24f730a3f2d561ec129dcff5e01fc3c9/crates/cairo-lang-sierra-generator/src/statements_code_locations.rs#L9)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/statements_code_locations.rs` line 12 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6144#-O3w3pT1AjrytWmFkrs1:-O4e0DLR3p4ocoYvbfVa:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a3d4681e24f730a3f2d561ec129dcff5e01fc3c9/crates/cairo-lang-sierra-generator/src/statements_code_locations.rs#L12)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc struct
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/statements_code_locations.rs` line 20 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6144#-O3w3qWC2Q90vP2bZQc-:-O4e8l0Z89TG06va0NJw:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a3d4681e24f730a3f2d561ec129dcff5e01fc3c9/crates/cairo-lang-sierra-generator/src/statements_code_locations.rs#L20)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc struct and members
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/statements_code_locations.rs` line 25 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6144#-O3w3sl80W4IQFs7msBV:-O4e0UOoEB6QPl-BS1XT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a3d4681e24f730a3f2d561ec129dcff5e01fc3c9/crates/cairo-lang-sierra-generator/src/statements_code_locations.rs#L25)):*
> ```XML
> }
> /// The mapping between sierra statement indexes and locations in cairo code
> /// (if obtainable) which caused the statement to be generated. Should be created using
> ```

Done.
___
*[`crates/cairo-lang-sierra-generator/src/statements_locations.rs` line 161 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6144#-O3w40iM1_jLnywCxcHU:-O4e9Fug1Z-hc4Vbipkn:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a3d4681e24f730a3f2d561ec129dcff5e01fc3c9/crates/cairo-lang-sierra-generator/src/statements_locations.rs#L161)):*
> ```XML
>     } else {
>         None
>     }
> ```

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 8 files at r1, 2 of 4 files at r4, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6144#-:-O4eAbY75WK9nVDNkl0S:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @orizi)

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6144)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MaksymilianDemitraszek)

**Pull request merged**
