### PR TITLE
Smoothed diagnostics refresh to not happen for every keystroke.

### PR DESCRIPTION
**Pull request by orizi**
Now only starts after previous one was done.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6155)

### CODE REVIEW

**Review by piotmag769 — COMMENTED** [review]
Checked it and it doesn't really feel smoother from user perspective imo

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6155#-:-O3cy8Lp4xgoFCW1bnCp:bdd830b)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @mkaput)

**Review by orizi — COMMENTED** [review]
How large was the project you used it on?
And what was the effect you've actually seen?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6155#-:-O3ddlZn7S8hq97Wzmhd:bu93ga6)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @mkaput)

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6155)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, and @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 336 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6155#-O3fmOkO0UlBhDBi6Wpe:-O3fmOkO0UlBhDBi6Wpf:bpuy6oy) ([raw file](https://github.com/starkware-libs/cairo/blob/a037015fd81c13e48fe64579b9aa8a372c19d264/crates/cairo-lang-language-server/src/lib.rs#L336)):*
> ```XML
>         // Making sure only a single set refreshes diagnostics as the same time.
>         // This way, following small updates to the db would not cause refreshes per sub-change.
>         let _lock = self.refresh_lock.lock().await;
> ```

I'm afraid that this lock may end up being contested too heavily. Do you have a [profile file](https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-language-server/CONTRIBUTING.md#profiling) generated before and after this change?

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6155)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, and @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 334 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6155#-O3fmhkq6MCDjhyCjWQ-:-O3fmhkq6MCDjhyCjWQ0:bmdxtjo) ([raw file](https://github.com/starkware-libs/cairo/blob/a037015fd81c13e48fe64579b9aa8a372c19d264/crates/cairo-lang-language-server/src/lib.rs#L334)):*
> ```XML
>     #[tracing::instrument(level = "debug", skip_all)]
>     async fn refresh_diagnostics(&self) -> LSPResult<()> {
>         // Making sure only a single set refreshes diagnostics as the same time.
> ```

Please add a TODO comment on me to remove this lock when cancellation will be implemented (#6131)

**Review by mkaput — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6155)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, and @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6155)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, and @mkaput)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 334 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6155#-O3fmhkq6MCDjhyCjWQ-:-O3fn0ZB9A0-vMApGN5o:bls18em) ([raw file](https://github.com/starkware-libs/cairo/blob/a037015fd81c13e48fe64579b9aa8a372c19d264/crates/cairo-lang-language-server/src/lib.rs#L334)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Please add a TODO comment on me to remove this lock when cancellation will be implemented (#6131)
</blockquote></details>

even if cancellation is implemented - i'm not sure it should be removed - still no reason for a 2 diag refreshes to be running at the same time.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 336 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6155#-O3fmOkO0UlBhDBi6Wpe:-O3fnJzoDTwT_0kd2onT:b-vor7re) ([raw file](https://github.com/starkware-libs/cairo/blob/a037015fd81c13e48fe64579b9aa8a372c19d264/crates/cairo-lang-language-server/src/lib.rs#L336)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I'm afraid that this lock may end up being contested too heavily. Do you have a [profile file](https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-language-server/CONTRIBUTING.md#profiling) generated before and after this change?
</blockquote></details>

i do not - i'm trying to find an actual example test project.
but do note this will have no actual effect currently - the `db` is locked all the time right after, so this basically does nothing.
we possibly may want to have only a single waiter at a point (as 2 waiters are useless, as the 2nd one would do exactly the same),.

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6155)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, and @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 334 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6155#-O3fmhkq6MCDjhyCjWQ-:-O3fr9_nCie6lA1ju3-4:b-e6ghzc) ([raw file](https://github.com/starkware-libs/cairo/blob/a037015fd81c13e48fe64579b9aa8a372c19d264/crates/cairo-lang-language-server/src/lib.rs#L334)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

even if cancellation is implemented - i'm not sure it should be removed - still no reason for a 2 diag refreshes to be running at the same time.
</blockquote></details>

I think it can be removed because with cancellation we'll be able to very quickly detect "oh, I'm running out-of-date DB snapshot, so I have to abandon this run", so even if this will be called in parallel, each irrelevant parallel execution will promptly terminate.

Now, this lock will indeed serialize runs of `refresh_diagnostics`, but each run will still do a full pass over the entire codebase which will take time even if it hits cache, and will contend for further locks.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 336 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6155#-O3fmOkO0UlBhDBi6Wpe:-O3fs0LY0KDczjHMCuID:b-fyqez) ([raw file](https://github.com/starkware-libs/cairo/blob/a037015fd81c13e48fe64579b9aa8a372c19d264/crates/cairo-lang-language-server/src/lib.rs#L336)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i do not - i'm trying to find an actual example test project.
but do note this will have no actual effect currently - the `db` is locked all the time right after, so this basically does nothing.
we possibly may want to have only a single waiter at a point (as 2 waiters are useless, as the 2nd one would do exactly the same),.
</blockquote></details>

1. Open Zeppelin Contracts are my benchmark for such things
2. Yeah, we should use database snapshots here

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6155)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, and @mkaput)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 334 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6155#-O3fmhkq6MCDjhyCjWQ-:-O3hBSGUBzMtiywZn0Q5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a037015fd81c13e48fe64579b9aa8a372c19d264/crates/cairo-lang-language-server/src/lib.rs#L334)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I think it can be removed because with cancellation we'll be able to very quickly detect "oh, I'm running out-of-date DB snapshot, so I have to abandon this run", so even if this will be called in parallel, each irrelevant parallel execution will promptly terminate.

Now, this lock will indeed serialize runs of `refresh_diagnostics`, but each run will still do a full pass over the entire codebase which will take time even if it hits cache, and will contend for further locks.
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
Looks much better now.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6155#-:-O3lRqRq4EfBGd_XtfId:bk17i86)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, and @mkaput)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 336 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6155#-O3fmOkO0UlBhDBi6Wpe:-O3lL1ni0bVv2tVo2uRu:bl2lj7o) ([raw file](https://github.com/starkware-libs/cairo/blob/a037015fd81c13e48fe64579b9aa8a372c19d264/crates/cairo-lang-language-server/src/lib.rs#L336)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

1. Open Zeppelin Contracts are my benchmark for such things
2. Yeah, we should use database snapshots here
</blockquote></details>

Used another project - but in any case - everything looks much better.
profile comparison as well.

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6155)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, and @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 343 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6155#-O3mS49t3R1dRWTlVbR6:-O3mS49t3R1dRWTlVbR7:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f8a78da935bf6864951436ce687a9ff50978b720/crates/cairo-lang-language-server/src/lib.rs#L343)):*
> ```XML
>         // together before querying the database, as well as releasing extra threads waiting to
>         // start diagnostics updates. TODO(orizi): Consider removing when request
>         // cancellation is supported.
> ```





_Suggestion:_
```XML
        // Making sure only a single thread is refreshing diagnostics at a time, and that at most
        // one thread is waiting to start refreshing. This allows changed to be grouped
        // together before querying the database, as well as releasing extra threads waiting to
        // start diagnostics updates.
        // TODO(orizi): Consider removing when request cancellation is supported.
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6155)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, and @mkaput)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 343 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6155#-O3mS49t3R1dRWTlVbR6:-O3mT39O2ngaE4EU_nig:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f8a78da935bf6864951436ce687a9ff50978b720/crates/cairo-lang-language-server/src/lib.rs#L343)):*
> ```XML
>         // together before querying the database, as well as releasing extra threads waiting to
>         // start diagnostics updates. TODO(orizi): Consider removing when request
>         // cancellation is supported.
> ```

Done.

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6155#-:-O3mTKiz5r1L7oRT3o3-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)

**Pull request merged**
