### PR TITLE
Unify setup_project flow for folders.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1889)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1889#-:-NMZVxmJ-gk_wkidDI2l:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-compiler/src/project.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1889#-NMc7sZk6AODZGXj7tH1:-NMc7sZk6AODZGXj7tH2:bti41xk) ([raw file](https://github.com/starkware-libs/cairo/blob/06dc12ee61acf9d41064d3068d122a95b8022578/crates/cairo-lang-compiler/src/project.rs#L41)):*
> ```XML
>     let file_stemp = path.file_stem().and_then(OsStr::to_str).ok_or_else(bad_path_err)?;
>     if file_stemp == "lib" {
>         return setup_project(db, path.parent().ok_or_else(bad_path_err)?);
> ```

This looks for a project, file.

I don't know if that what we want :(



_Code quote:_
```XML
 return setup_project(db, path.parent().ok_or_else(bad_path_err)?);
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-compiler/src/project.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1889#-NMc7sZk6AODZGXj7tH1:-NMc7xmC-6Rd3DYua_qD:b-l8hgzu) ([raw file](https://github.com/starkware-libs/cairo/blob/06dc12ee61acf9d41064d3068d122a95b8022578/crates/cairo-lang-compiler/src/project.rs#L41)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

This looks for a project, file.

I don't know if that what we want :(
</blockquote></details>

though I guess it is better than the current situation.

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1889)* status: all files reviewed, 1 unresolved discussion

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1889)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1889#-NMcBfMLDL-TlfvlLhUp:-NMcBfMLDL-TlfvlLhUq:b-vluj7r) (no related file):*
I'll just chime in here. In general, I find this change very good, but I'd like to point out that I am thinking with @maciektr on hiding this function behind `RootDatabaseBuilder` (#1824) in future PR :)

___

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1889)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1889#-NMcBfMLDL-TlfvlLhUp:-NMcE0LJ0VYY7D_CL02W:b-od48h) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I'll just chime in here. In general, I find this change very good, but I'd like to point out that I am thinking with @maciektr on hiding this function behind `RootDatabaseBuilder` (#1824) in future PR :)
</blockquote></details>

Another option is to print an error and ask the user to remove the `/lib.cairo` from the path.
but it raises the question if the compiler should do this for you.

___

**Comment by ilyalesokhin-starkware** [comment]
replaced by #1897 until we have a better idea.

**Comment by maciektr** [comment]
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Another option is to print an error and ask the user to remove the `/lib.cairo` from the path.
but it raises the question if the compiler should do this for you.

</blockquote></details>

@ilyalesokhin-starkware As we will be closing the https://github.com/starkware-libs/cairo/pull/1932, should there be any changes that are still worth introducing as of now in the area of project setup?

**Pull request closed without merging**
