### PR TITLE
Add circuits consts to ConstsInfo.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5514)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5514)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 272 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5514#-NxIdLw3Dl2-OqmDMCXd:-NxIdLw3Dl2-OqmDMCXe:bggmxjv) ([raw file](https://github.com/starkware-libs/cairo/blob/f6c4160ad4533d5bd097cd386f9a1f7829c2cf9a/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L272)):*
> ```XML
>             }
> 
>             // TODO(ilya): give the user the ability to control the segment id.
> ```

any reason to not just have a segment per circuit?
as we assume these are going to be rather large - no?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5514)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 272 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5514#-NxIdLw3Dl2-OqmDMCXd:-NxMujRh6PH0dLzZBus4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f6c4160ad4533d5bd097cd386f9a1f7829c2cf9a/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L272)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

any reason to not just have a segment per circuit?
as we assume these are going to be rather large - no?
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5514#-:-NxNBTlI7YNLe54eZs1D:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 228 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5514#-NxNAzMuCWgJGLmuI6i3:-NxNAzMuCWgJGLmuI6i4:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7f8b7994b67fda120baf420b1c459e6d1dabd284/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L228)):*
> ```XML
> 
>     // Maps a circuit to its segment id.
>     pub circuit_segments: OrderedHashMap<ConcreteTypeId, u32>,
> ```





_Suggestion:_
```XML
    /// Maps a circuit to its segment id.
    pub circuit_segments: OrderedHashMap<ConcreteTypeId, u32>,
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5514)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 228 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5514#-NxNAzMuCWgJGLmuI6i3:-NxNCTVN8QwWRPrUG-lU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7f8b7994b67fda120baf420b1c459e6d1dabd284/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L228)):*
> ```XML
> 
>     // Maps a circuit to its segment id.
>     pub circuit_segments: OrderedHashMap<ConcreteTypeId, u32>,
> ```

Done.

**Pull request merged**
