### PR TITLE
Refactor optimize_matches not to use `target_blocks`.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5129)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5129)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5129#-NrUPhzc-Zx0y567nJyM:-NrUPhzc-Zx0y567nJyN:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7e5ad75600d8dc6364b597a35b82d4752000be33/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L34)):*
> ```XML
>     let mut next_block_id = BlockId(lowered.blocks.len());
> 
>     // Fixes were added in reverse order, so we apply them in revese.
> ```





_Suggestion:_
```XML
    // Fixes were added in reverse order, so we apply them in reverse.
```
___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5129#-NrUPdKB5MBGcUp4_mM1:-NrUPdKB5MBGcUp4_mM2:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7e5ad75600d8dc6364b597a35b82d4752000be33/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L62)):*
> ```XML
> 
>         //  IF `arm.block` was not fixed before, fix it not to jump directly to blocks that have
>         // incoming gotos and add remapping for merge.
> ```





_Suggestion:_
```XML
        //  If `arm.block` was not fixed before, fix it not to jump directly to blocks that have
        // incoming gotos and add remapping for merge.
```
___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 161 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5129#-NrUPu9T1OJn5mkx10GO:-NrUPu9T1OJn5mkx10GP:b-tptp7j) ([raw file](https://github.com/starkware-libs/cairo/blob/7e5ad75600d8dc6364b597a35b82d4752000be33/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L161)):*
> ```XML
>     /// The block That we want to jump to.
>     match_block: BlockId,
>     arm_idx: usize,
> ```

doc and remove empty line.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5129)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5129#-NrUPhzc-Zx0y567nJyM:-NrUU6uO3LHtDfRorLpO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7e5ad75600d8dc6364b597a35b82d4752000be33/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L34)):*
> ```XML
>     let mut next_block_id = BlockId(lowered.blocks.len());
> 
>     // Fixes were added in reverse order, so we apply them in revese.
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5129)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 165 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5129#-NrUvYNU9-322uQDvrJZ:-NrUvYNU9-322uQDvrJ_:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/cb85c85880974c8edb47af084c2c00e6d795b241/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L165)):*
> ```XML
>     arm_idx: usize,
>     // The target block to jump to.
>     target_block: BlockId,
> ```





_Suggestion:_
```XML
    arm_idx: usize,
    /// The target block to jump to.
    target_block: BlockId,
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5129)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs` line 165 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5129#-NrUvYNU9-322uQDvrJZ:-NrUzjJu87DwR7edudiZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cb85c85880974c8edb47af084c2c00e6d795b241/crates/cairo-lang-lowering/src/optimizations/match_optimizer.rs#L165)):*
> ```XML
>     arm_idx: usize,
>     // The target block to jump to.
>     target_block: BlockId,
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5129#-:-NrV0LKR6yM26csSfVyh:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
