### PR TITLE
Add note to drops due to divergence.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3717)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 293 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3717#-N_lpNvG-nQMHjAu81Vq:-N_lpNvG-nQMHjAu81Vr:b-jj343d) ([raw file](https://github.com/starkware-libs/cairo/blob/b1edf31f0e5ef9eff56cc129ce9a22c2ff49fae4/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L293)):*
> ```
>   --> lib.cairo:3:4
>    1 + 1;
>    ^***^
> ```

I can give a better error message if I only handle the panic case.



_Code quote:_
```
note: variable need to be dropped before:
  --> lib.cairo:3:4
   1 + 1;
   ^***^
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 113 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3717#-N_lrcC46cATreJUagq2:-N_lrcC46cATreJUagq3:bmufxxf) ([raw file](https://github.com/starkware-libs/cairo/blob/b1edf31f0e5ef9eff56cc129ce9a22c2ff49fae4/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L113)):*
> ```
>   --> lib.cairo:9:3
>   if true {
>   ^*******^
> ```

I've decided not to give this note.



_Code quote:_
```
note: variable need to be dropped before:
  --> lib.cairo:9:3
  if true {
  ^*******^
```

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3717)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 113 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3717#-N_lrcC46cATreJUagq2:-N_lu8QH-M2Skw5S5CQj:b-ywjiwe) ([raw file](https://github.com/starkware-libs/cairo/blob/b1edf31f0e5ef9eff56cc129ce9a22c2ff49fae4/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L113)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I've decided not to give this note.
</blockquote></details>

i think this is the "end of block" issue again - you still want  this warning - it is just less clear.
as the issue is the merge.
___
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 293 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3717#-N_lpNvG-nQMHjAu81Vq:-N_ls0PwDMG9GcPLkbfR:bpu8za) ([raw file](https://github.com/starkware-libs/cairo/blob/b1edf31f0e5ef9eff56cc129ce9a22c2ff49fae4/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L293)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I can give a better error message if I only handle the panic case.
</blockquote></details>

this already looks pretty great.
If you want a better error for the panic case - you can just add additional information on Option<LocationId>

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 113 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3717#-N_lrcC46cATreJUagq2:-N_lv4Dt7ZARnvCZGFrm:b-ywlsze) ([raw file](https://github.com/starkware-libs/cairo/blob/b1edf31f0e5ef9eff56cc129ce9a22c2ff49fae4/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L113)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i think this is the "end of block" issue again - you still want  this warning - it is just less clear.
as the issue is the merge.
</blockquote></details>

It is this issue.

but lest say you have an if with an early return.
do we want a note with the location of the 'if' or is visible enough to the user that there is control flow divergence?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 293 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3717#-N_lpNvG-nQMHjAu81Vq:-N_lvQ2AEDArBi4TDP0D:bnlt5ur) ([raw file](https://github.com/starkware-libs/cairo/blob/b1edf31f0e5ef9eff56cc129ce9a22c2ff49fae4/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L293)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this already looks pretty great.
If you want a better error for the panic case - you can just add additional information on Option<LocationId>
</blockquote></details>

Yes, the question is if we want to do that of if divergence is visible enough.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3717)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 293 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3717#-N_lpNvG-nQMHjAu81Vq:-N_lvmvF1-iZZ0vjkh4p:b-ris62j) ([raw file](https://github.com/starkware-libs/cairo/blob/b1edf31f0e5ef9eff56cc129ce9a22c2ff49fae4/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L293)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Yes, the question is if we want to do that of if divergence is visible enough.
</blockquote></details>

Ok, I guess I'll do add the extra information.

it is useful, especially in the case of compiler bugs.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3717)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 113 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3717#-N_lrcC46cATreJUagq2:-N_m-jAF14aWKvdneqoh:bxbu8wq) ([raw file](https://github.com/starkware-libs/cairo/blob/b1edf31f0e5ef9eff56cc129ce9a22c2ff49fae4/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L113)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

It is this issue.

but lest say you have an if with an early return.
do we want a note with the location of the 'if' or is visible enough to the user that there is control flow divergence?
</blockquote></details>

i think if we have an issue  in the 14th divergence in the function - it would be very difficult to find.
so pointing to the block still sounds better for me.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3717#-:-N_mFjwZ-7JZ5gb3G-qy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
