### PR TITLE
Add an option to refernce a returned variable in casm_builder.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1590)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1590)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-casm/src/builder.rs` line 480 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1590#-NKhWUcW6ENRKckDCEe9:-NKhWUcW6ENRKckDCEeA:b9ufc7w) ([raw file](https://github.com/starkware-libs/cairo/blob/cbb0d4f0d26a5cc15129b7bf334f07153f138030/crates/cairo-casm/src/builder.rs#L480)):*
> ```XML
>     /// Adds a variable referencing a variable returned from a function. Must be called directly
>     /// after a call statement. returned_index_var is the index of the returned var from the end of
>     /// the returned vars list (zero-indexed), i.e. the last returned var index is 0.
> ```

Some questions:
Should we assert that the vars are created right after a call to a function?
Should the i'th var from the end be i (as it is now) or -i?
___
*[`crates/cairo-casm/src/builder.rs` line 674 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1590#-NKhX0AW5xNXNaXtNP3V:-NKhX0AW5xNXNaXtNP3W:b-xypm2r) ([raw file](https://github.com/starkware-libs/cairo/blob/cbb0d4f0d26a5cc15129b7bf334f07153f138030/crates/cairo-casm/src/builder.rs#L674)):*
> ```XML
>         $crate::casm_build_extend!($builder, $($tok)*)
>     };
>     ($builder:ident, let $dst:ident = returned [ $index:expr ] ; $($tok:tt)*) => {
> ```

Another question:
This syntax prevent the use of a buffer named returned, and idea for a better syntax?

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1590#-:-NKi0zu_1Wouf9hn44-Y:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-casm/src/builder.rs` line 696 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1590#-NKi0MUf4NWiUs1IKp6b:-NKi0MUf4NWiUs1IKp6c:btnjd58) ([raw file](https://github.com/starkware-libs/cairo/blob/2fcb1fd57a903e4115a0ddb318b56562f12f91c2/crates/cairo-casm/src/builder.rs#L696)):*
> ```XML
>     ($builder:ident, call $target:ident; $($tok:tt)*) => {
>         $builder.call(std::stringify!($target).to_owned());
>         $crate::casm_build_extend!($builder, $($tok)*)
> ```

you can probably remove this - is there a reason not to?



_Code quote:_
```XML
    ($builder:ident, call $target:ident; $($tok:tt)*) => {
        $builder.call(std::stringify!($target).to_owned());
        $crate::casm_build_extend!($builder, $($tok)*)
    };
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1590#-:-NKleOvD4ItthWw3ZUXR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1590)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1590)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

___
*[`crates/cairo-casm/src/builder.rs` line 696 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1590#-NKi0MUf4NWiUs1IKp6b:-NKlaZmvDWp0ESBQsHGY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2fcb1fd57a903e4115a0ddb318b56562f12f91c2/crates/cairo-casm/src/builder.rs#L696)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you can probably remove this - is there a reason not to?
</blockquote></details>

Done.

**Pull request merged**
