### PR TITLE
Add generic params stand alone semantic model.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3360)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, 5 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3360)* status: 8 of 14 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/generics` line 122 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3360#-NXomgu4EKypPxhB9384:-NXomgu4EKypPxhB9385:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/d025589cacb2ab5ade9abbb97551e668d5ca1c3a/crates/cairo-lang-semantic/src/expr/test_data/generics#L122)):*
> ```
>  --> lib.cairo:1:35
> fn bar<A, const B: usize, impl C: MyTrait::<felt252>>(){}
>                                   ^*****^
> ```

remove



_Code quote:_
```
error: Not a trait.
 --> lib.cairo:1:35
fn bar<A, const B: usize, impl C: MyTrait::<felt252>>(){}
                                  ^****************^

error: Trait not found.
 --> lib.cairo:1:35
fn bar<A, const B: usize, impl C: MyTrait::<felt252>>(){}
                                  ^*****^
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3360)* status: 7 of 14 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/generics` line 122 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3360#-NXomgu4EKypPxhB9384:-NXtUlW0-ERD2zAm1csa:b-td9t58) ([raw file](https://github.com/starkware-libs/cairo/blob/d025589cacb2ab5ade9abbb97551e668d5ca1c3a/crates/cairo-lang-semantic/src/expr/test_data/generics#L122)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done, but not sure about the way I did it. It was raised twice because the path was evaluated both in the computation of the generic param itself, and now also when filtering the other required impls. In the latter I now collect the diagnostics into a temporary diagnostics object which is ignored as it is evaluated twice.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3360)* status: 8 of 14 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 209 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3360#-NXtXaPDAclhHaCjbZXf:-NXtXaPDAclhHaCjbZXg:bw83iy6) ([raw file](https://github.com/starkware-libs/cairo/blob/45b12357f5e7aa36f98219de8adb36d07aedcdc8/crates/cairo-lang-semantic/src/items/generics.rs#L209)):*
> ```XML
>                     }
>                 }
>                 let dummy_diagnostics = &mut SemanticDiagnostics::new(module_file_id);
> ```

doc why you don't need to propagate diags.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3360)* status: 8 of 14 files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 209 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3360#-NXtXaPDAclhHaCjbZXf:-NXtbtYnEnRc5RUKj8a2:bobnbhy) ([raw file](https://github.com/starkware-libs/cairo/blob/45b12357f5e7aa36f98219de8adb36d07aedcdc8/crates/cairo-lang-semantic/src/items/generics.rs#L209)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc why you don't need to propagate diags.
</blockquote></details>

This was not relevant, removed. The other place is documented.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3360)* status: 10 of 15 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 199 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3360#-NXxyT7i45ibW50uERhS:-NXxyT7i45ibW50uERhT:b-78ihi3) ([raw file](https://github.com/starkware-libs/cairo/blob/67a5922d039e7fc3bc7f92def16d377c998efc68/crates/cairo-lang-semantic/src/items/generics.rs#L199)):*
> ```XML
>                     continue;
>                 }
>                 // Filter impls which are not required by the current impl to avoid cycles.
> ```

Do we need to do this logic to prevent cycles?
What about just adding the generic param id to the resolver, and there, fetch the semantic model only when requested? And add a cycle handling query.



_Code quote:_
```XML
avoid cycles
```

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3360)* status: 10 of 15 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`tests/bug_samples/generic_cycles.cairo` line 5 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3360#-NXxzKTS3ha7iG4mj8r1:-NXxzKTS3ha7iG4mj8r2:bqujbyh) ([raw file](https://github.com/starkware-libs/cairo/blob/67a5922d039e7fc3bc7f92def16d377c998efc68/tests/bug_samples/generic_cycles.cairo#L5)):*
> ```Cairo
> 
> struct B<T, impl Timpl1: ATrait<T>, impl Timpl2: ATrait2<T>> {
>     t: T, 
> ```

Here too



_Code quote:_
```Cairo
·
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3360)* status: 4 of 17 files reviewed, 5 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/generics` line 307 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3360#-NXxyyws7OBP0BESKT36:-NYCoqa1En5vY8b4PTVo:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/67a5922d039e7fc3bc7f92def16d377c998efc68/crates/cairo-lang-semantic/src/expr/test_data/generics#L307)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Remove whitespace
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/generics` line 330 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3360#-NXxz4WEBMtlCz0WdX1R:-NYCp12T8XL5LZnDlA3n:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/67a5922d039e7fc3bc7f92def16d377c998efc68/crates/cairo-lang-semantic/src/expr/test_data/generics#L330)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Here too
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 165 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3360#-NXxxL-y3gzWC4n0KE8S:-NYOM1jY1Am7qvfXjKge:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/67a5922d039e7fc3bc7f92def16d377c998efc68/crates/cairo-lang-semantic/src/items/generics.rs#L165)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

There is no need to go through the generic_item to get the generic_params syntax. If you look at the implementation of generic_item(), you can see it just goes to the parent a few times. Make a similar function that does to the parent less time.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 199 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3360#-NXxyT7i45ibW50uERhS:-NYOM2QF7S9f73UGDO_t:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/67a5922d039e7fc3bc7f92def16d377c998efc68/crates/cairo-lang-semantic/src/items/generics.rs#L199)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Do we need to do this logic to prevent cycles?
What about just adding the generic param id to the resolver, and there, fetch the semantic model only when requested? And add a cycle handling query.
</blockquote></details>

Done.
___
*[`tests/bug_samples/generic_cycles.cairo` line 5 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3360#-NXxzKTS3ha7iG4mj8r1:-NYCp3Fa8r9QsCkOLu6m:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/67a5922d039e7fc3bc7f92def16d377c998efc68/tests/bug_samples/generic_cycles.cairo#L5)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Here too
</blockquote></details>

Done.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3360)* status: 4 of 17 files reviewed, 6 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 783 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3360#-NYONHi2Dz9NnyAPjU-A:-NYONHi2Dz9NnyAPjU-B:bczz9hb) ([raw file](https://github.com/starkware-libs/cairo/blob/fbfc8468deef0506558d535b6b89906845f8b834/crates/cairo-lang-semantic/src/resolve/mod.rs#L783)):*
> ```XML
>         ImplLookupContext::new(
>             self.module_file_id.0,
>             self.generic_params.values().copied().collect(),
> ```

In here, I ignore the unresolved generic params since trying to resolve all of then will cause unnecessary cycles.

**Review by gilbens-starkware — COMMENTED** [review]
> Dismissed @spapinistarkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3360)* status: 4 of 17 files reviewed, 6 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 199 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3360#-NXxyT7i45ibW50uERhS:-NYPj4wsAS1pu0FS4LrS:b-q3oto7) ([raw file](https://github.com/starkware-libs/cairo/blob/67a5922d039e7fc3bc7f92def16d377c998efc68/crates/cairo-lang-semantic/src/items/generics.rs#L199)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I did this change but reverted it. The problem is the resolver `impl_lookup_context` function. It returns all the generic params in context. Ignoring the unresolved generic params in this function cause some resolving failures, and fetching all the params semantic models naturally cause cycles.
I tried to add a filter similar to this to the `impl_lookup_context` function, but it requires a similar logic to this in many places, and in some places it is not at all clear what the filter should be, while in here it is relatively simple and not scattered all over.
I think that maybe we should remove the  `impl_lookup_context`, and fetch the relevant generic params in each place separately and not rely on them already being in the resolver, wdyt?

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3360)* status: 4 of 17 files reviewed, 5 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 300 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3360#-NYSR4M02CUZW0d-WJJ2:-NYSSS_i22BCg_9ebnUT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6855c38ba24dcfee2cb6f0e1affbec891013a5d1/crates/cairo-lang-semantic/src/items/generics.rs#L300)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Insetad of importing items under ast, qualify them with `ast::`
</blockquote></details>

Done.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3360)* status: 4 of 17 files reviewed, 5 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 199 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3360#-NXxyT7i45ibW50uERhS:-NYSSv_BEMzKsgGae4cS:b-8cqfsq) ([raw file](https://github.com/starkware-libs/cairo/blob/67a5922d039e7fc3bc7f92def16d377c998efc68/crates/cairo-lang-semantic/src/items/generics.rs#L199)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Something similar, I think the ImplLookupContext should only contain 
</blockquote></details>

It seems like this sentence is cut down in the middle.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3360)* status: 0 of 18 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 152 at r11](https://reviewable.io/reviews/starkware-libs/cairo/3360#-NYXnmlbB56wBHmqgHxC:-NYXnmlbB56wBHmqgHxD:b-ak7ttb) ([raw file](https://github.com/starkware-libs/cairo/blob/c6156e4e5b20800baa902d904ab49a5b54def2a5/crates/cairo-lang-semantic/src/items/generics.rs#L152)):*
> ```XML
>     generic_param_id: GenericParamId,
> ) -> Maybe<GenericParam> {
>     let generic_item = generic_param_id.generic_item(db.upcast());
> ```

Don't go through item

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3360)* status: 0 of 19 files reviewed, 4 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 152 at r11](https://reviewable.io/reviews/starkware-libs/cairo/3360#-NYXnmlbB56wBHmqgHxC:-NYZuICz4rM0F-kFgINo:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c6156e4e5b20800baa902d904ab49a5b54def2a5/crates/cairo-lang-semantic/src/items/generics.rs#L152)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Don't go through item
</blockquote></details>

Done.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3360)* status: 0 of 19 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 94 at r11](https://reviewable.io/reviews/starkware-libs/cairo/3360#-NYmwyu-DGiqbyC4jcEY:-NYmwyu-DGiqbyC4jcEZ:bxm46pj) ([raw file](https://github.com/starkware-libs/cairo/blob/c6156e4e5b20800baa902d904ab49a5b54def2a5/crates/cairo-lang-semantic/src/resolve/mod.rs#L94)):*
> ```XML
>     // Generic parameters accessible to the resolver.
>     generic_params: OrderedHashMap<SmolStr, GenericParam>,
>     unresolved_generic_params: OrderedHashMap<SmolStr, GenericParamId>,
> ```

I don't understand why we ened this.
Resolver is only using the ids. Why can't we just make generic_params a map to ids?

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3360)* status: 0 of 19 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 230 at r12](https://reviewable.io/reviews/starkware-libs/cairo/3360#-NYmxFDy4sNpWkUJ1iFK:-NYmxFDy4sNpWkUJ1iFL:by5vr36) ([raw file](https://github.com/starkware-libs/cairo/blob/cc5275243caf902655f14d46a2093cb1ebc9a3ce/crates/cairo-lang-semantic/src/items/generics.rs#L230)):*
> ```XML
>                     // cause a cycle. However the GenericParamId is needed for the impl lookup
>                     // context.
>                     resolver.add_unresolved_generic_param(cur_generic_param_id);
> ```

I don't thing we need this logic. Check my comment on resovler/mod.rs

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3360)* status: 0 of 19 files reviewed, 5 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 230 at r12](https://reviewable.io/reviews/starkware-libs/cairo/3360#-NYmxFDy4sNpWkUJ1iFK:-NYnVZQT8hZUCzgjvNGX:b-owists) ([raw file](https://github.com/starkware-libs/cairo/blob/cc5275243caf902655f14d46a2093cb1ebc9a3ce/crates/cairo-lang-semantic/src/items/generics.rs#L230)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I don't thing we need this logic. Check my comment on resovler/mod.rs
</blockquote></details>

You are right. Done.
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 94 at r11](https://reviewable.io/reviews/starkware-libs/cairo/3360#-NYmwyu-DGiqbyC4jcEY:-NYnVKKT3nj3qEfJ4H4p:bgkpbqq) ([raw file](https://github.com/starkware-libs/cairo/blob/c6156e4e5b20800baa902d904ab49a5b54def2a5/crates/cairo-lang-semantic/src/resolve/mod.rs#L94)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I don't understand why we ened this.
Resolver is only using the ids. Why can't we just make generic_params a map to ids?
</blockquote></details>

There was another place where we used the generic params, not the ids, I removed it. Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 11 files at r6, 11 of 16 files at r10, 1 of 1 files at r11, 4 of 7 files at r12, 5 of 5 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3360)* status: all files reviewed, 5 unresolved discussions (waiting on @spapinistarkware)

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 16 files at r10, 2 of 5 files at r13.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3360)* status: all files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 161 at r13](https://reviewable.io/reviews/starkware-libs/cairo/3360#-NYqMUqK3JvRESSvs3za:-NYqMUqLEPAyyYi5mIU9:bdv8dq4) ([raw file](https://github.com/starkware-libs/cairo/blob/547c26bcdf0fbdd3e53939a8ad9983a344d01274/crates/cairo-lang-semantic/src/items/generics.rs#L161)):*
> ```XML
>     db: &dyn SemanticGroup,
>     generic_param_id: GenericParamId,
>     allow_consts: bool,
> ```

What is this allow_consts, why do we need it?
___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 230 at r13](https://reviewable.io/reviews/starkware-libs/cairo/3360#-NYqNHuM5YZljvnW3OiN:-NYqNHuM5YZljvnW3OiO:bjo7skc) ([raw file](https://github.com/starkware-libs/cairo/blob/547c26bcdf0fbdd3e53939a8ad9983a344d01274/crates/cairo-lang-semantic/src/items/generics.rs#L230)):*
> ```XML
>         &generic_param_syntax,
>         allow_consts,
>     );
> ```

resolvers always have to be finalized, to make sure we are not left with uninferred variables 
___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 253 at r13](https://reviewable.io/reviews/starkware-libs/cairo/3360#-NYqI8iq-laHudqsfR4d:-NYqI8iq-laHudqsfR4e:b479hmu) ([raw file](https://github.com/starkware-libs/cairo/blob/547c26bcdf0fbdd3e53939a8ad9983a344d01274/crates/cairo-lang-semantic/src/items/generics.rs#L253)):*
> ```XML
> }
> 
> /// Returns the resolver data of the parent generic item if exist.
> ```

It would be nice if this function was a method on LookupItemId.
___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 360 at r13](https://reviewable.io/reviews/starkware-libs/cairo/3360#-NYqIR4Z1BDLjjWKQXEq:-NYqIR4Z1BDLjjWKQXEr:bf9mgg0) ([raw file](https://github.com/starkware-libs/cairo/blob/547c26bcdf0fbdd3e53939a8ad9983a344d01274/crates/cairo-lang-semantic/src/items/generics.rs#L360)):*
> ```XML
>                 ));
>                 let generic_param_data = db.generic_param_data(generic_param_id, allow_consts)?;
>                 let generic_param = generic_param_data.generic_param;
> ```

I think it's better to use the selector query for just the the param semantic model

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3360)* status: all files reviewed, 6 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 161 at r13](https://reviewable.io/reviews/starkware-libs/cairo/3360#-NYqMUqK3JvRESSvs3za:-NYqP7dk6ecpu4ksgVTY:bsq1pxt) ([raw file](https://github.com/starkware-libs/cairo/blob/547c26bcdf0fbdd3e53939a8ad9983a344d01274/crates/cairo-lang-semantic/src/items/generics.rs#L161)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

What is this allow_consts, why do we need it?
</blockquote></details>

Not sure TBH, it existed before, it seems that consts generics are allowed only in `extern_functions`.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3360)* status: 17 of 21 files reviewed, 5 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 230 at r13](https://reviewable.io/reviews/starkware-libs/cairo/3360#-NYqNHuM5YZljvnW3OiN:-NYtKczz35kUq-p1-g8v:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/547c26bcdf0fbdd3e53939a8ad9983a344d01274/crates/cairo-lang-semantic/src/items/generics.rs#L230)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

resolvers always have to be finalized, to make sure we are not left with uninferred variables 
</blockquote></details>

Done.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3360)* status: 17 of 21 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 161 at r13](https://reviewable.io/reviews/starkware-libs/cairo/3360#-NYqMUqK3JvRESSvs3za:-NYqgMrpAFmP4IbKkRX2:b-68n7a0) ([raw file](https://github.com/starkware-libs/cairo/blob/547c26bcdf0fbdd3e53939a8ad9983a344d01274/crates/cairo-lang-semantic/src/items/generics.rs#L161)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Not sure TBH, it existed before, it seems that consts generics are allowed only in `extern_functions`.
</blockquote></details>

That sounds right, but I'm not sure why this trickles all the way to the query

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3360)* status: 17 of 21 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 632 at r14](https://reviewable.io/reviews/starkware-libs/cairo/3360#-NYvRh7T58sLo1ePNHc5:-NYvRh7T58sLo1ePNHc6:bl1cf27) ([raw file](https://github.com/starkware-libs/cairo/blob/58fa90e1a762943e6523de5c353763944182aded/crates/cairo-lang-semantic/src/resolve/mod.rs#L632)):*
> ```XML
> 
>         // If a generic param with this name is found, use it.
>         if let Some(generic_param) = self.data.generic_params.get(&ident) {
> ```

Is this an id? if so, please rename



_Suggestion:_
```XML
generic_param_id
```

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 16 files at r10, 1 of 5 files at r13, 1 of 4 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3360)* status: 18 of 21 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/lookup_item.rs` line 50 at r14](https://reviewable.io/reviews/starkware-libs/cairo/3360#-NYvTPqz63Bkm8FKbdjq:-NYvTPr-4FtTVnwrKSxD:bqk0otm) ([raw file](https://github.com/starkware-libs/cairo/blob/58fa90e1a762943e6523de5c353763944182aded/crates/cairo-lang-semantic/src/lookup_item.rs#L50)):*
> ```XML
>                 Ok(Some(resolver_data))
>             }
>             LookupItemId::ModuleItem(_) => Ok(None),
> ```

I suggest returning ResolverData::default() here.
___
*[`crates/cairo-lang-semantic/src/expr/inference/infers.rs` line 108 at r14](https://reviewable.io/reviews/starkware-libs/cairo/3360#-NYvTYNo0XLWbNu1rVDW:-NYvTYNo0XLWbNu1rVDX:b-gjxtyu) ([raw file](https://github.com/starkware-libs/cairo/blob/58fa90e1a762943e6523de5c353763944182aded/crates/cairo-lang-semantic/src/expr/inference/infers.rs#L108)):*
> ```XML
>                 let param = self
>                     .db
>                     .generic_param_semantic(param_id, false)
> ```

It's weird that I have to specify allow_consts: false, here. The semantic model of the parameter id doesn't actually depend on allow_consts.
WDYT about inferring allow_consts in the generic_param_semantic query itself, according to the parent item kind?



_Code quote:_
```XML
, false
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3360)* status: 18 of 21 files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/items/enm.rs` line 54 at r14](https://reviewable.io/reviews/starkware-libs/cairo/3360#-NYvUCIQ3XMIiJhUfFB_:-NYvUCIQ3XMIiJhUfFBa:bhhsa9s) ([raw file](https://github.com/starkware-libs/cairo/blob/58fa90e1a762943e6523de5c353763944182aded/crates/cairo-lang-semantic/src/items/enm.rs#L54)):*
> ```XML
>     let generic_params_data = db.enum_generic_params_data(enum_id)?;
>     let mut resolver = Resolver::with_data(db, (*generic_params_data.resolver_data).clone());
>     diagnostics.diagnostics.extend(generic_params_data.diagnostics);
> ```

Another approach would have been to not aggregate the diagnostic of the generic params here, but to collect it in module_diagnostics like other items. The benefit of this is that if only the diagnostics oc the generic params changed, we won't need to recompute the semantic model of the enum here.



_Code quote:_
```XML
generic_params_data.diagnostics
```

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r14.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3360)* status: 19 of 21 files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware and @orizi)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3360)* status: 19 of 21 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 360 at r13](https://reviewable.io/reviews/starkware-libs/cairo/3360#-NYqIR4Z1BDLjjWKQXEq:-NYvWfs33-v9ypxzH6RI:b2ni8w0) ([raw file](https://github.com/starkware-libs/cairo/blob/547c26bcdf0fbdd3e53939a8ad9983a344d01274/crates/cairo-lang-semantic/src/items/generics.rs#L360)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I think it's better to use the selector query for just the the param semantic model
</blockquote></details>

nvm

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 16 files at r10, 12 of 14 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3360)* status: 19 of 21 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/items/structure.rs` line 115 at r15](https://reviewable.io/reviews/starkware-libs/cairo/3360#-NZ-aWJF0QqKVNws-T7F:-NZ-aWJF0QqKVNws-T7G:b-x5yd7x) ([raw file](https://github.com/starkware-libs/cairo/blob/6d2ac5e0757f9f6af2003d02f19da2d7a46c56a8/crates/cairo-lang-semantic/src/items/structure.rs#L115)):*
> ```XML
>         &struct_ast.generic_params(db.upcast()),
>     )?;
>     let generic_params = resolver.inference().rewrite(generic_params).no_err();
> ```

You are not finalizing the inference. Every place you create a Resolver, you should finalize it, sho we won't have uninferred variables. Maybe we can enforce it better in the future...

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 11 files at r6, 2 of 16 files at r10, 1 of 1 files at r11, 2 of 14 files at r15.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3360)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3360)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/items/structure.rs` line 115 at r15](https://reviewable.io/reviews/starkware-libs/cairo/3360#-NZ-aWJF0QqKVNws-T7F:-NZ-xxPJ1ii1fFwSoVih:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6d2ac5e0757f9f6af2003d02f19da2d7a46c56a8/crates/cairo-lang-semantic/src/items/structure.rs#L115)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

You are not finalizing the inference. Every place you create a Resolver, you should finalize it, sho we won't have uninferred variables. Maybe we can enforce it better in the future...
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3360#-:-NZ0aS4JAWMOaYeOfWyw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
