### PR TITLE
Add sierra const structs.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
**Stack**:
- #4706
- #4703 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4703)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4703)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4703#-Nn3dLVy2hrMPgIui6C2:-Nn3dLVy2hrMPgIui6C3:b-bipgjf) ([raw file](https://github.com/starkware-libs/cairo/blob/870b9cafa5457b3a1a5a4ed72a186c11a14a7917/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L114)):*
> ```XML
>                 return Err(SpecializationError::UnsupportedGenericArg);
>             }
>         }
> ```

extract to fn.



_Code quote:_
```XML
        let mut struct_args_iter = inner_type_info.long_id.generic_args.iter();
        // The first arg of a struct is the struct type, so skip it.
        struct_args_iter.next();
        if struct_args_iter.len() != inner_data.len() {
            return Err(SpecializationError::WrongNumberOfGenericArgs);
        }
        for (struct_arg, const_arg) in struct_args_iter.zip_eq(inner_data.iter()) {
            if let (GenericArg::Type(struct_arg_ty), GenericArg::Type(const_arg_ty)) =
                (struct_arg, const_arg)
            {
                // Validate that the const_arg_ty is a const representing the struct_arg_ty.
                let const_arg_type_info = context.get_type_info(const_arg_ty.clone())?;
                if const_arg_type_info.long_id.generic_id != ConstType::ID {
                    return Err(SpecializationError::UnsupportedGenericArg);
                }
                let (GenericArg::Type(const_arg_inner_ty), const_arg_inner_data) =
                    &const_arg_type_info
                        .long_id
                        .generic_args
                        .split_first()
                        .ok_or(SpecializationError::UnsupportedGenericArg)?
                else {
                    return Err(SpecializationError::UnsupportedGenericArg);
                };
                // Validate that the const_arg_inner_ty is the same as the corresponding
                // struct_arg_ty.
                if struct_arg_ty != const_arg_inner_ty {
                    return Err(SpecializationError::UnsupportedGenericArg);
                }
                // Recursively validate the const_arg_inner_data.
                validate_const_data(context, const_arg_inner_ty, const_arg_inner_data)?;
            } else {
                return Err(SpecializationError::UnsupportedGenericArg);
            }
        }
```
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4703#-Nn3eGU_DoPsaEEIAdbw:-Nn3eGU_DoPsaEEIAdbx:b-a512o5) ([raw file](https://github.com/starkware-libs/cairo/blob/870b9cafa5457b3a1a5a4ed72a186c11a14a7917/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L181)):*
> ```XML
>             })
>             .collect(),
>     }
> ```

split to inner function adding to a continous vector - avoid direct recursion.



_Code quote:_
```XML
/// Gets a concrete type, if it is a const type returns a vector of the values to be stored in the
/// const segment.
pub fn extract_const_value(
    registry: &ProgramRegistry<CoreType, CoreLibfunc>,
    ty: &ConcreteTypeId,
) -> Result<Vec<BigInt>, CompilationError> {
    //
    let const_type =
        if let cairo_lang_sierra::extensions::core::CoreTypeConcrete::Const(const_type) =
            registry.get_type(ty).unwrap()
        {
            const_type
        } else {
            return Err(CompilationError::UnsupportedConstType);
        };
    let inner_type = registry
        .get_type(&const_type.inner_ty)
        .map_err(|_| CompilationError::UnsupportedConstType)?;
    match inner_type {
        // Recursively extract the values of members.
        cairo_lang_sierra::extensions::core::CoreTypeConcrete::Struct(_) => Ok(const_type
            .inner_data
            .iter()
            .flat_map(|arg| match arg {
                GenericArg::Type(ty) => extract_const_value(registry, ty),
                _ => Err(CompilationError::ConstDataMismatch),
            })
            .flatten()
            .collect()),
        _ => const_type
            .inner_data
            .iter()
            .map(|arg| match arg {
                GenericArg::Value(value) => Ok(value.clone()),
                _ => Err(CompilationError::ConstDataMismatch),
            })
            .collect(),
    }
```
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler_test.rs` line 488 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4703#-Nn3dYSQ6WAvdY_hfDbD:-Nn3dYSQ6WAvdY_hfDbE:baezwqb) ([raw file](https://github.com/starkware-libs/cairo/blob/870b9cafa5457b3a1a5a4ed72a186c11a14a7917/crates/cairo-lang-sierra-to-casm/src/compiler_test.rs#L488)):*
> ```XML
>     type const<felt252, 5> = const<felt252, 5>;
>     type const<felt252, 17> = const<felt252, 17>;
>     type const<Tuple<felt252, felt252>, const<felt252, 5>, const<felt252, 17>> = const<Tuple<felt252, felt252>, const<felt252, 5>, const<felt252, 17>>; 
> ```

make lines shorter.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4703)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4703#-Nn3dLVy2hrMPgIui6C2:-Nn3iwhkE-53v7RDDOMf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/870b9cafa5457b3a1a5a4ed72a186c11a14a7917/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L114)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

extract to fn.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4703#-Nn3eGU_DoPsaEEIAdbw:-Nn3opuO57qw0lKc3-KH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/870b9cafa5457b3a1a5a4ed72a186c11a14a7917/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L181)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

split to inner function adding to a continous vector - avoid direct recursion.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler_test.rs` line 488 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4703#-Nn3dYSQ6WAvdY_hfDbD:-Nn3oqMs3lLcvsXt-RJx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/870b9cafa5457b3a1a5a4ed72a186c11a14a7917/crates/cairo-lang-sierra-to-casm/src/compiler_test.rs#L488)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

make lines shorter.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4703)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 94 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4703#-Nn3vO0tDMoWqIBr8Gmp:-Nn3vO0tDMoWqIBr8Gmq:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/a80baf9781e47bca3eb21a0030fbba79b340eba2/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L94)):*
> ```XML
> }
> 
> fn validate_const_struct_data(
> ```

doc
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 155 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4703#-Nn3vntJ6QJiqWnX_Hy0:-Nn3vntJ6QJiqWnX_Hy1:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/a80baf9781e47bca3eb21a0030fbba79b340eba2/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L155)):*
> ```XML
> }
> 
> fn extract_const_value_inner(
> ```

doc

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4703)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 108 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4703#-Nn3xBkF-F_7LDpVv6Qx:-Nn3xBkF-F_7LDpVv6Qy:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/a80baf9781e47bca3eb21a0030fbba79b340eba2/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L108)):*
> ```XML
>         if let (GenericArg::Type(struct_arg_ty), GenericArg::Type(const_arg_ty)) =
>             (struct_arg, const_arg)
>         {
> ```

.



_Suggestion:_
```XML
        let (GenericArg::Type(struct_arg_ty), GenericArg::Type(const_arg_ty)) =
            (struct_arg, const_arg) else { ... }
        {
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4703)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 191 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4703#-Nn3yMUk7Ky1Gjo91kve:-Nn3yMUk7Ky1Gjo91kvf:b-3xsp2g) ([raw file](https://github.com/starkware-libs/cairo/blob/a80baf9781e47bca3eb21a0030fbba79b340eba2/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L191)):*
> ```XML
>                 .collect::<Result<Vec<BigInt>, CompilationError>>()?,
>         ),
>     };
> ```

avoid recursion:
(not exactly - but close enough)



_Suggestion:_
```XML
    let const_type =
        if let cairo_lang_sierra::extensions::core::CoreTypeConcrete::Const(const_type) =
            registry.get_type(ty).unwrap()
        {
            const_type
        } else {
            return Err(CompilationError::UnsupportedConstType);
        };
    let inner_type = registry
        .get_type(&const_type.inner_ty)
        .map_err(|_| CompilationError::UnsupportedConstType)?;
    let mut stack = vec![(const_type, inner_type)];
    while let Some((const_type, inner_type)) = stack.pop() {
    match inner_type {
        // Recursively extract the values of members.
        cairo_lang_sierra::extensions::core::CoreTypeConcrete::Struct(_) => {
            for arg in const_type.inner_data.iter().rev() {
                match arg {
                    GenericArg::Type(ty) => extract_const_value_inner(registry, ty, values)?,
                    _ => return Err(CompilationError::ConstDataMismatch),
                }
            }
        }
    }
        _ => values.extend(
            const_type
                .inner_data
                .iter()
                .map(|arg| match arg {
                    GenericArg::Value(value) => Ok(value.clone()),
                    _ => Err(CompilationError::ConstDataMismatch),
                })
                .collect::<Result<Vec<BigInt>, CompilationError>>()?,
        ),
    };
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4703)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 164 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4703#-Nn4Sev45R4CSptYh6td:-Nn4Sev45R4CSptYh6te:bljob9k) ([raw file](https://github.com/starkware-libs/cairo/blob/604e9dac27e0d468be98436b99100c5ce8e1a11f/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L164)):*
> ```XML
>         match inner_type {
>             cairo_lang_sierra::extensions::core::CoreTypeConcrete::Struct(_) => {
>                 // Recursively extract the values of members.
> ```

fix doc



_Code quote:_
```XML
/ Recursively extract the values of members.
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4703)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 94 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4703#-Nn3vO0tDMoWqIBr8Gmp:-Nn42IW7Eq6qoEdtUIuD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a80baf9781e47bca3eb21a0030fbba79b340eba2/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L94)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 108 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4703#-Nn3xBkF-F_7LDpVv6Qx:-Nn42Im5EoIt0ouybPNm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a80baf9781e47bca3eb21a0030fbba79b340eba2/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L108)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 155 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4703#-Nn3vntJ6QJiqWnX_Hy0:-Nn4AMX03HTCfFqzvWZU:b1m4q2v) ([raw file](https://github.com/starkware-libs/cairo/blob/a80baf9781e47bca3eb21a0030fbba79b340eba2/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L155)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done. I removed the inner function as it is no longer necessary.
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 191 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4703#-Nn3yMUk7Ky1Gjo91kve:-Nn4AKJ87DtbeZHEFGrE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a80baf9781e47bca3eb21a0030fbba79b340eba2/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L191)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

avoid recursion:
(not exactly - but close enough)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 164 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4703#-Nn4Sev45R4CSptYh6td:-Nn4W-Y8-UHNzrv8TtK7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/604e9dac27e0d468be98436b99100c5ce8e1a11f/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L164)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix doc
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4703#-:-Nn4XaBd9Ya49eHI44vd:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Comment by gilbens-starkware** [comment]
✓ Commit merged in pull request [#4706](https://github.com/starkware-libs/cairo/pull/4706)

**Pull request merged**
