### PR TITLE
Bumped version to 2.3.1.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4320)

### CODE REVIEW

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 67 of 67 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4320#-:-NhzCjhmBJtlprsNMRDm:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/method` line 174 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4320#-NhzDLwb6ijsvMOw48mi:-NhzDLwb6ijsvMOw48mj:b-cq1qab) ([raw file](https://github.com/starkware-libs/cairo/blob/0c67a87fb24131f21fd4b8709b88e15eaeaf18de/crates/cairo-lang-semantic/src/expr/test_data/method#L174)):*
> ```
>     ^*^
> ```

Doesn't seems related.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4320)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/method` line 174 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4320#-NhzDLwb6ijsvMOw48mi:-Nhzlsog0IbdYgc6Lca8:b-2lzeo2) ([raw file](https://github.com/starkware-libs/cairo/blob/0c67a87fb24131f21fd4b8709b88e15eaeaf18de/crates/cairo-lang-semantic/src/expr/test_data/method#L174)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Doesn't seems related.
</blockquote></details>

this is what happens when the test fixer is ran.
reverting.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 67 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4320)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4320)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4320)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
