### PR TITLE
add support for expressions in const generic arguments

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5189)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5189)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 770 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5189#-Ns41IpID891b0z7MOg8:-Ns41IpID891b0z7MOg9:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/bccf2dffd9014802cf685215f7105afb30b00ffe/crates/cairo-lang-lowering/src/lower/mod.rs#L770)):*
> ```XML
>             )
>         })
>         .unwrap_or(ConstValue::Missing(skip_diagnostic()));
> ```





_Suggestion:_
```XML
        .map_err(|err| {
            ctx.diagnostics.report(stable_ptr, LoweringDiagnosticKind::LiteralError(err))
        })
        .unwrap_or_else(ConstValue::Missing);
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5189)* status: 2 of 7 files reviewed, 4 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/generics` line 567 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5189#-Ns426622Ub0i4nRHr9_:-Ns426622Ub0i4nRHr9a:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/bccf2dffd9014802cf685215f7105afb30b00ffe/crates/cairo-lang-semantic/src/expr/test_data/generics#L567)):*
> ```
> //! > function
> fn foo() {
>     bar::<{1+2}>();
> ```





_Suggestion:_
```
    bar::<{ 1 + 2 }>();
```
___
*[`crates/cairo-lang-semantic/src/expr/test_data/generics` line 589 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5189#-Ns428eDBN1xl31lEg44:-Ns428eDBN1xl31lEg45:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/bccf2dffd9014802cf685215f7105afb30b00ffe/crates/cairo-lang-semantic/src/expr/test_data/generics#L589)):*
> ```
> //! > function
> fn foo() {
>     let _s :S<{1-2}> = bar();
> ```





_Suggestion:_
```
    let _s: S<{ 1 - 2 }> = bar();
```
___
*[`crates/cairo-lang-semantic/src/expr/test_data/generics` line 601 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5189#-Ns42DKQEzq5GD5XtApC:-Ns42DKQEzq5GD5XtApD:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/bccf2dffd9014802cf685215f7105afb30b00ffe/crates/cairo-lang-semantic/src/expr/test_data/generics#L601)):*
> ```
> mod A {
>     fn f() {
>         let x: super::S<{super::k+9}> = super::bar();
> ```





_Suggestion:_
```
extern fn bar() -> S<{ 3 + 8 }> nopanic;
const K: felt252 = 98;
mod A {
    fn f() {
        let x: super::S<{ super::K + 9 }> = super::bar();
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5189)* status: 2 of 7 files reviewed, 5 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5189#-Ns42U-J1kXZxvNuLu75:-Ns42U-J1kXZxvNuLu76:bl9168a) ([raw file](https://github.com/starkware-libs/cairo/blob/bccf2dffd9014802cf685215f7105afb30b00ffe/crates/cairo-lang-semantic/src/items/constant.rs#L132)):*
> ```XML
> pub fn evaluate_const_expr_and_resolve(
>     db: &dyn SemanticGroup,
>     ctx: &mut ComputationContext,
> ```

and doc



_Suggestion:_
```XML
        resolver_data,
    })
}

pub fn evaluate_const_expr_and_resolve(
    db: &dyn SemanticGroup,
    ctx: &mut ComputationContext,
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5189)* status: 6 of 7 files reviewed, 6 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 1003 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5189#-Ns42qRyEqsJoXOtDOv7:-Ns42qRyEqsJoXOtDOv8:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/bccf2dffd9014802cf685215f7105afb30b00ffe/crates/cairo-lang-semantic/src/resolve/mod.rs#L1003)):*
> ```XML
>                 // to inference finalization and use inference here. This will become more relevant
>                 // when we support constant expressions, which need inference.
>                 // TODO(mkaput): This is a dumb heuristic, the expr here should be const-evaluated.
> ```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5189)* status: all files reviewed, 6 unresolved discussions (waiting on @TomerStarkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5189)* status: 6 of 8 files reviewed, 9 unresolved discussions (waiting on @TomerStarkware)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5189#-Ns44xhQCRSN4Xn0_RD0):*




_Suggestion:_
```
- dd5b4e9: add support for expressions in const generic arguments
```
___
*[`corelib/src/internal.cairo` line 19 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5189#-Ns44uqu0x-ig8zTE_h4:-Ns44uqu0x-ig8zTE_h5:b-l6hdjr) ([raw file](https://github.com/starkware-libs/cairo/blob/dd5b4e96b31b5184b8f4d94fa8592c3dd235d767/corelib/src/internal.cairo#L19)):*
> ```Cairo
>         let x: super::S<{ super::k + 9 }> = super::bar();
>     }
> }
> ```

revert



_Code quote:_
```Cairo
extern type S<const N: felt252>;
extern fn bar()->S<{3 + 8}> nopanic;
const k : felt252 = 98;
mod A {
    fn f() {
        let x: super::S<{ super::k + 9 }> = super::bar();
    }
}
```
___
*[`crates/cairo-lang-semantic/src/expr/test_data/generics` line 606 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5189#-Ns453KBBM3X3389P8vb:-Ns453KBBM3X3389P8vc:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/dd5b4e96b31b5184b8f4d94fa8592c3dd235d767/crates/cairo-lang-semantic/src/expr/test_data/generics#L606)):*
> ```
> 
> 
> //! > function_body
> ```





_Suggestion:_
```
    }
}

//! > function_body
```
___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 131 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5189#-Ns4563j5AbMNL_xOt9H:-Ns4563j5AbMNL_xOt9I:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/dd5b4e96b31b5184b8f4d94fa8592c3dd235d767/crates/cairo-lang-semantic/src/items/constant.rs#L131)):*
> ```XML
> }
> 
> /// resolves the given const expression and evaluates its value.
> ```





_Suggestion:_
```XML
/// Resolves the given const expression and evaluates its value.
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5189)* status: all files reviewed, 8 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/internal.cairo` line 19 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5189#-Ns44uqu0x-ig8zTE_h4:-Ns45nSfCNClvY0h5ea7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/dd5b4e96b31b5184b8f4d94fa8592c3dd235d767/corelib/src/internal.cairo#L19)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

revert
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/generics` line 601 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5189#-Ns42DKQEzq5GD5XtApC:-Ns46ILs0KkjC_du9tWj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bccf2dffd9014802cf685215f7105afb30b00ffe/crates/cairo-lang-semantic/src/expr/test_data/generics#L601)):*
> ```
> mod A {
>     fn f() {
>         let x: super::S<{super::k+9}> = super::bar();
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5189#-Ns42U-J1kXZxvNuLu75:-Ns46PBT93QVxpvKhzam:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bccf2dffd9014802cf685215f7105afb30b00ffe/crates/cairo-lang-semantic/src/items/constant.rs#L132)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

and doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 131 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5189#-Ns4563j5AbMNL_xOt9H:-Ns46P_F5XCnIj9rJ_iH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/dd5b4e96b31b5184b8f4d94fa8592c3dd235d767/crates/cairo-lang-semantic/src/items/constant.rs#L131)):*
> ```XML
> }
> 
> /// resolves the given const expression and evaluates its value.
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 1003 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5189#-Ns42qRyEqsJoXOtDOv7:-Ns43KKQ2do1HCZ0cTnD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bccf2dffd9014802cf685215f7105afb30b00ffe/crates/cairo-lang-semantic/src/resolve/mod.rs#L1003)):*
> ```XML
>                 // to inference finalization and use inference here. This will become more relevant
>                 // when we support constant expressions, which need inference.
>                 // TODO(mkaput): This is a dumb heuristic, the expr here should be const-evaluated.
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5189)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/generics` line 589 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5189#-Ns46zcMCgw5pO0IuSgc:-Ns46zcN7SSv2uGhyduE:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2b23f809933d17b225406786d0ea9055f6ba5c3b/crates/cairo-lang-semantic/src/expr/test_data/generics#L589)):*
> ```
> //! > function
> fn foo() {
>     let _s : S<{ 1 - 2 }> = bar();
> ```





_Suggestion:_
```
    let _s: S<{ 1 - 2 }> = bar();
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5189)* status: all files reviewed, 3 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/generics` line 597 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5189#-Ns47bCl7rBez7J1KJLr:-Ns47bCl7rBez7J1KJLs:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e64b65c35c1f6546b32b53817bcab4d2a1481d73/crates/cairo-lang-semantic/src/expr/test_data/generics#L597)):*
> ```
> //! > module_code
> extern type S<const N: felt252>;
> extern fn bar() -> S<{ 3 + 8 }>;
> ```





_Suggestion:_
```
extern fn bar() -> S<{ 3 + 8 }> nopanic;
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5189)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

___
*[`corelib/src/internal.cairo` line 11 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5189#-Ns4BWcz3fYvXmtzkoev:-Ns4BWcz3fYvXmtzkoew:b-l6hdjr) ([raw file](https://github.com/starkware-libs/cairo/blob/f3a7eb280db9859b79cc8dcdf1401a8771d29f72/corelib/src/internal.cairo#L11)):*
> ```Cairo
> 
> extern type BoundedInt<const MIN: felt252, const MAX: felt252>;
> dsfsafsafdas
> ```

revert

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5189)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5189)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/generics` line 589 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5189#-Ns46zcMCgw5pO0IuSgc:-Ns4CfGvAyjxhZ48cD83:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2b23f809933d17b225406786d0ea9055f6ba5c3b/crates/cairo-lang-semantic/src/expr/test_data/generics#L589)):*
> ```
> //! > function
> fn foo() {
>     let _s : S<{ 1 - 2 }> = bar();
> ```

Done.

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5189)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5189#-:-Ns7RwRv0euAlWX2Fj5A:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
