### PR TITLE
Generalize demands

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2230)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2230#-:-NOog4QC3AO6L0oIjqCd:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2230)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2230)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/mod.rs` line 58 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2230#-NOohYV9-3lJhpj7XpBq:-NOohYV9-3lJhpj7XpBr:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/b3e4006c94ba97199979ae94c54d0b538fcc4681/crates/cairo-lang-lowering/src/borrow_check/mod.rs#L58)):*
> ```XML
> 
> /// The position associated with the demand reporting. This is provided at every demand computation,
> /// and passed to th4e reported when needed. This is used here to specify if we want diagnostics
> ```

?



_Suggestion:_
```XML
/// The position associated with the demand reporting. This is provided at every demand computation,
/// and passed to be reported when needed. This is used here to specify if we want diagnostics
/// to be reported at the location or not.
#[derive(Copy, Clone)]
enum ReportPosition {
    Report,
    // Currently some reporting is disabled, since Drop is not properly implemented everywhere.
    // TODO(spapini): Fix this.
    DoNotReport,
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2230)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2230)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/borrow_check/mod.rs` line 58 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2230#-NOohYV9-3lJhpj7XpBq:-NOoiBEB4yYUN4xxRsy4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b3e4006c94ba97199979ae94c54d0b538fcc4681/crates/cairo-lang-lowering/src/borrow_check/mod.rs#L58)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2230)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2230)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
