### PR TITLE
Packing code words by divmod, not aligning to bits

### PR DESCRIPTION
**Pull request by orizi**
Reduces size by another 5 percent.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2656)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2656)* status: 2 of 9 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/felt252_vec_compression.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2656#-NRmV1A17F26zKKibUGV:-NRmV1A28WrA5gQcFTru:bxgchwb) ([raw file](https://github.com/starkware-libs/cairo/blob/4341b8326899b2eabc33dd3e8558f1505bcfc3dd/crates/cairo-lang-starknet/src/felt252_vec_compression.rs#L48)):*
> ```XML
>         for _ in 0..curr_words {
>             let (remaining, code_word) = v.div_mod_floor(&code_len);
>             result.extend(
> ```

why not push?



_Suggestion:_
```XML
result.push
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2656)* status: 2 of 9 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/felt252_vec_compression.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2656#-NRmW8xl9KDqfhFpptpI:-NRmW8xl9KDqfhFpptpJ:bws8jcx) ([raw file](https://github.com/starkware-libs/cairo/blob/4341b8326899b2eabc33dd3e8558f1505bcfc3dd/crates/cairo-lang-starknet/src/felt252_vec_compression.rs#L56)):*
> ```XML
>         remaining_unpacked_size -= curr_words;
>     }
>     if remaining_unpacked_size == 0 { Some(()) } else { None }
> ```

when does this happen?



_Code quote:_
```XML
None
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2656)* status: 1 of 9 files reviewed, all discussions resolved

___
*[`crates/cairo-lang-starknet/src/felt252_vec_compression.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2656#-NRmW8xl9KDqfhFpptpI:-NRmqSua6U_7WRTMhioN:b-kqzmq) ([raw file](https://github.com/starkware-libs/cairo/blob/4341b8326899b2eabc33dd3e8558f1505bcfc3dd/crates/cairo-lang-starknet/src/felt252_vec_compression.rs#L56)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

when the given result size is larger than the number of given words
</blockquote></details>

If it is redundant why do we serialize it? sanity?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2656)* status: 1 of 9 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/felt252_vec_compression.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2656#-NRmW8xl9KDqfhFpptpI:-NRmtEUFBTTgiT6JsWGV:bm5d9ax) ([raw file](https://github.com/starkware-libs/cairo/blob/4341b8326899b2eabc33dd3e8558f1505bcfc3dd/crates/cairo-lang-starknet/src/felt252_vec_compression.rs#L56)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

If it is redundant why do we serialize it? sanity?
</blockquote></details>

this is the deserialization - so we need to check sanity here.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 9 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2656#-:-NS0-gbKB4PNs6ke_bMM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/felt252_vec_compression.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2656#-NRmW8xl9KDqfhFpptpI:-NS0-deT0aR_jerL1FoZ:b-8if7uj) ([raw file](https://github.com/starkware-libs/cairo/blob/4341b8326899b2eabc33dd3e8558f1505bcfc3dd/crates/cairo-lang-starknet/src/felt252_vec_compression.rs#L56)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is the deserialization - so we need to check sanity here.
</blockquote></details>

it is not clear, but ok.

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2656)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2656)* status: 1 of 9 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 6 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2656)* status: 7 of 9 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2656)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
