### PR TITLE
allowed_diagnostics->expect_diagnostics to support enforcing diagnostics

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4029)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
why does the test runner name include its arguments:
//! > test_runner_name
ExpandContractTestRunner(expect_diagnostics: false)

> Reviewed 1 of 57 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4029#-:-NdjcedR7VJnG-7MVz6U:b-nh7zb6)* status: 1 of 57 files reviewed, all discussions resolved

**Review by yuvalsw — COMMENTED** [review]
We can talk about it f2f, anyway it's not new in this PR.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4029#-:-NdkVM832K3WSzOxXoCw:b1d8jpl)* status: 1 of 57 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — APPROVED** [review]
I think 'test_runner_name' should be renamed, but we can do it later.

> Reviewed 35 of 57 files at r1, 25 of 25 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4029#-:-Ne6tLrQ-ASw-2UbF-RQ:b-87gm6a)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4029#-:-Ne6tSYk2Lu72tBC_m0k:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
