### PR TITLE
Added casts from unsinged integers to bytes31

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3606)

### CODE REVIEW

**Comment by yuvalsw** [comment]
Change target branch

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3606)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3606#-NZeP3xC1ndfpgqE_Wf1:-NZeP3xC1ndfpgqE_Wf2:b9yx10u) (no related file):*
delay this PR for now as this changes the meaning of an existing libfunc.

___

**Comment by yuvalsw** [comment]
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

delay this PR for now as this changes the meaning of an existing libfunc.
</blockquote></details>

I split the libfunc part to another PR

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3606#-:-NZenlpg0KnrzjHJ13bS:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Pull request merged**
