### PR TITLE
Avoid pushing zero-sized variables.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4275)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4275)* status: 0 of 32 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/test_data/new_syntax_test_contract__counter_contract.sierra` line 1658 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4275#-Nh0csPY4JzFaI4ogU5F:-Nh0csPZ4c3fJyc13YEP:bb3s0kd) ([raw file](https://github.com/starkware-libs/cairo/blob/547e0a1bd08e4cd5ebaa2f19a5aeceb490559864/crates/cairo-lang-starknet/test_data/new_syntax_test_contract__counter_contract.sierra#L1658)):*
> ```
> rename<Array<felt252>>([7]) -> ([10]); // 1328
> rename<Array<felt252>>([8]) -> ([11]); // 1329
> jump() { 1365() }; // 1330
> ```

the `store_temp`s before the jump were changed to `rename`s and now the code fails sierra to casm.



_Code quote:_
```
function_call<user@cairo_level_tests::contracts::new_syntax_test_contract::test_component::EventIsEvent::append_keys_and_data>([3], [1], [2]) -> ([7], [8], [9]); // 1326
drop<Unit>([9]) -> (); // 1327
rename<Array<felt252>>([7]) -> ([10]); // 1328
rename<Array<felt252>>([8]) -> ([11]); // 1329
jump() { 1365() }; // 1330
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4275)* status: 0 of 32 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/test_data/new_syntax_test_contract__counter_contract.sierra` line 1658 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4275#-Nh0csPY4JzFaI4ogU5F:-Nh0sl3t4kQFzlNJ0VqA:b-hsfftq) ([raw file](https://github.com/starkware-libs/cairo/blob/547e0a1bd08e4cd5ebaa2f19a5aeceb490559864/crates/cairo-lang-starknet/test_data/new_syntax_test_contract__counter_contract.sierra#L1658)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

the `store_temp`s before the jump were changed to `rename`s and now the code fails sierra to casm.
</blockquote></details>

See
https://reviewable.io/reviews/starkware-libs/cairo/4276

**Review by orizi — COMMENTED** [review]
> Reviewed 31 of 32 files at r1, 21 of 21 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4275)* status: 52 of 53 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/test_data/new_syntax_test_contract__counter_contract.sierra` line 1658 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4275#-Nh0csPY4JzFaI4ogU5F:-Nh2s33w5m76Z5JElWcT:b21lx5g) ([raw file](https://github.com/starkware-libs/cairo/blob/547e0a1bd08e4cd5ebaa2f19a5aeceb490559864/crates/cairo-lang-starknet/test_data/new_syntax_test_contract__counter_contract.sierra#L1658)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

See
https://reviewable.io/reviews/starkware-libs/cairo/4276
</blockquote></details>

so why don't i see the tests failing?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/test_data/new_syntax_test_contract__counter_contract.sierra` line 1658 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4275#-Nh0csPY4JzFaI4ogU5F:-Nh2xABg1HKP_Bg7mrsZ:bwmconl) ([raw file](https://github.com/starkware-libs/cairo/blob/547e0a1bd08e4cd5ebaa2f19a5aeceb490559864/crates/cairo-lang-starknet/test_data/new_syntax_test_contract__counter_contract.sierra#L1658)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

so why don't i see the tests failing?
</blockquote></details>

I'ved rebased this on top of the fix.
you can look at the previous ci run.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 32 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4275#-:-Nh2xtUt7r8Q0QVrPE1l:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
We need to merge
https://reviewable.io/reviews/starkware-libs/cairo/4276#-
first.
Note that is changes sierra_to_casm.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4275#-:-Nh2zm2tCjMEZ-DnfnZY:bj3sq1v)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request closed without merging**
