### PR TITLE
Support future block in inlining.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2180)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2180)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 267 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2180#-NOijoeR4pdmpDT-1J8R:-NOijoeR4pdmpDT-1J8S:b731377) ([raw file](https://github.com/starkware-libs/cairo/blob/9fdbe290e86311baa8a095fbcb609df81ce2fc44/crates/cairo-lang-lowering/src/inline/mod.rs#L267)):*
> ```XML
>     ctx: &'a mut LoweringContext<'b>,
>     lowered: &'a FlatLowered,
>     /// A Queue of blocks on which we want to apply the FunctionInlinerRewriter.
> ```

doc the fact that you take and return it as part of the process.



_Code quote:_
```XML
    lowered: &'a FlatLowered,
    /// A Queue of blocks on which we want to apply the FunctionInlinerRewriter.
    block_queue: BlockQueue,
```
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 288 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2180#-NOijekl6R72LOYoNZFL:-NOijekl6R72LOYoNZFM:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/9fdbe290e86311baa8a095fbcb609df81ce2fc44/crates/cairo-lang-lowering/src/inline/mod.rs#L288)):*
> ```XML
> 
>     fn rename_block(&mut self, old_block_id: &BlockId) -> BlockId {
>         if let Some(block_id) = self.renamed_blocks.get(old_block_id) {
> ```

doc



_Code quote:_
```XML
    fn rename_block(&mut self, old_block_id: &BlockId) -> BlockId {
```

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2180#-:-NOijyXeExOpW9PXGJkL:bnfp4nl)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2180)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 267 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2180#-NOijoeR4pdmpDT-1J8R:-NOitNxB1zo6zLUqO1PA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9fdbe290e86311baa8a095fbcb609df81ce2fc44/crates/cairo-lang-lowering/src/inline/mod.rs#L267)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc the fact that you take and return it as part of the process.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 288 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2180#-NOijekl6R72LOYoNZFL:-NOitNeZ-EqgAgoMr8RE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9fdbe290e86311baa8a095fbcb609df81ce2fc44/crates/cairo-lang-lowering/src/inline/mod.rs#L288)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2180)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 290 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2180#-NOizNtREUp5viNcC7lc:-NOizNtREUp5viNcC7ld:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/86290bc0ccb6b6383d6c3cf9fe9c5060754562cd/crates/cairo-lang-lowering/src/inline/mod.rs#L290)):*
> ```XML
> 
>     /// Renames a var from lowered.blocks, if the block wasn't assigned an id yet,
>     /// the block is rebuild in the new context and assigned an id.
> ```





_Suggestion:_
```XML
    /// Renames a var from lowered.blocks, if the block wasn't assigned an id yet,
    /// the block is rebuilt in the new context and assigned an id.
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2180)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2180)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
