### PR TITLE
added support for expression with const generic params at the semanti…

### PR DESCRIPTION
**Pull request by TomerStarkware**
…c level

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5198)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5198)* status: 3 of 17 files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/test_data/generics` line 189 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5198#-Ns9CfKS9h3D7REwccI8:-Ns9CfKS9h3D7REwccI9:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/285b536758fafc872be2ac6fe75b764e7b07a0c3/crates/cairo-lang-lowering/src/test_data/generics#L189)):*
> ```
> //! > ==========================================================================
> 
> //! > genric param in expression
> ```





_Suggestion:_
```
//! > generic param in expression
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 9 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5198)* status: 12 of 17 files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/test_data/generics` line 212 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5198#-Ns9E3Zc-Wq5xppjxc2w:-Ns9E3Zc-Wq5xppjxc2x:b-e14dhi) ([raw file](https://github.com/starkware-libs/cairo/blob/285b536758fafc872be2ac6fe75b764e7b07a0c3/crates/cairo-lang-lowering/src/test_data/generics#L212)):*
> ```
> error: Unsupported feature.
>  --> lib.cairo:2:5
>     N + 5
> ```

why does this error appear?

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5198)* status: 13 of 17 files reviewed, 3 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/generics` line 615 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5198#-Ns9EaOG6EUAMXeSVJbu:-Ns9EaOG6EUAMXeSVJbv:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/285b536758fafc872be2ac6fe75b764e7b07a0c3/crates/cairo-lang-semantic/src/expr/test_data/generics#L615)):*
> ```
> //! > ==========================================================================
> 
> //! > genric param in expression
> ```





_Suggestion:_
```
//! > generic param in expression
```

**Review by orizi — COMMENTED** [review]
> Reviewed 4 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5198)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5198)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5198#-:-NsCkMj-11puGWtUjdui:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5198)* status: 18 of 20 files reviewed, 5 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 953 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5198#-NsDgRxY4bsy7KoD8R0w:-NsDgRxZ1FGvXGUuZcjY:b-dd56xw) ([raw file](https://github.com/starkware-libs/cairo/blob/1cece9c803b9b724179f207a6232b0d39b844de7/crates/cairo-lang-lowering/src/lower/mod.rs#L953)):*
> ```XML
>     builder: &mut BlockBuilder,
> ) -> LoweringResult<LoweredExpr> {
>     log::trace!("Lowering a constant: {:?}", expr.debug(&ctx.expr_formatter));
> ```

Fix trace string
___
*[`crates/cairo-lang-lowering/src/test_data/generics` line 204 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5198#-NsDgmxjCuunNv7jT5eH:-NsDgmxjCuunNv7jT5eI:b-3j951m) ([raw file](https://github.com/starkware-libs/cairo/blob/1cece9c803b9b724179f207a6232b0d39b844de7/crates/cairo-lang-lowering/src/test_data/generics#L204)):*
> ```
> //! > module_code
> fn bar<const N: felt252>() -> felt252 {
>     N+5
> ```

Revert fmt
___
*[`crates/cairo-lang-lowering/src/test_data/generics` line 210 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5198#-NsDgk4x0StpcuETZWlB:-NsDgk4x0StpcuETZWlC:b88njbg) ([raw file](https://github.com/starkware-libs/cairo/blob/1cece9c803b9b724179f207a6232b0d39b844de7/crates/cairo-lang-lowering/src/test_data/generics#L210)):*
> ```
> error: This expression is not supported as constant.
>  --> lib.cairo:5:11
>     bar::<N>()
> ```

Split the test
___
*[`crates/cairo-lang-semantic/src/items/fmt.rs` line 42 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5198#-NsDhAu67LMtKtSMuWIG:-NsDhAu67LMtKtSMuWIH:b-lfsroj) ([raw file](https://github.com/starkware-libs/cairo/blob/1cece9c803b9b724179f207a6232b0d39b844de7/crates/cairo-lang-semantic/src/items/fmt.rs#L42)):*
> ```XML
>             }
>             ConstValue::Missing(_) => write!(f, "missing"),
>             ConstValue::Generic(param) => param.fmt(f, db),
> ```

Replace order
___
*[`crates/cairo-lang-sierra-generator/src/utils.rs` line 214 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5198#-NsDhRMK8HHq012GUg0v:-NsDhRMK8HHq012GUg0w:ba4ikhi) ([raw file](https://github.com/starkware-libs/cairo/blob/1cece9c803b9b724179f207a6232b0d39b844de7/crates/cairo-lang-sierra-generator/src/utils.rs#L214)):*
> ```XML
>                     unreachable!("Should be handled by `const_libfunc_id_by_type`.")
>                 }
>                 ConstValue::Missing(_) => unreachable!("Should be caught by the lowering."),
> ```

Reorder

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5198)* status: 18 of 20 files reviewed, 5 unresolved discussions (waiting on @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5198)* status: all files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 953 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5198#-NsDgRxY4bsy7KoD8R0w:-NsDrUmjAVVyAtSyDU7n:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1cece9c803b9b724179f207a6232b0d39b844de7/crates/cairo-lang-lowering/src/lower/mod.rs#L953)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Fix trace string
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/test_data/generics` line 204 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5198#-NsDgmxjCuunNv7jT5eH:-NsDsSK67fcfLy-yYsJM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1cece9c803b9b724179f207a6232b0d39b844de7/crates/cairo-lang-lowering/src/test_data/generics#L204)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Revert fmt
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/test_data/generics` line 210 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5198#-NsDgk4x0StpcuETZWlB:-NsDsPgMDDU3I0d8SN9f:b-gy0iia) ([raw file](https://github.com/starkware-libs/cairo/blob/1cece9c803b9b724179f207a6232b0d39b844de7/crates/cairo-lang-lowering/src/test_data/generics#L210)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Split the test
</blockquote></details>

removed in this pr
___
*[`crates/cairo-lang-semantic/src/items/fmt.rs` line 42 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5198#-NsDhAu67LMtKtSMuWIG:-NsDsFCR0r60qDc8Dpgi:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1cece9c803b9b724179f207a6232b0d39b844de7/crates/cairo-lang-semantic/src/items/fmt.rs#L42)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Replace order
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5198)* status: all files reviewed, 3 unresolved discussions (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5198#-:-NsDv0N69M2EqlZ-4HBv:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
