### PR TITLE
Refactored write test, and added read test.

### PR DESCRIPTION
**Pull request by orizi**
fixed inline to support, and made util print the display instead of
debug version of the casm.

commit-id:816de35f

---

**Stack**:
- #1391
- #1386
- #1385 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1385)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/sierra_to_casm/src/invocations/test_utils.rs` line 207 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1385#-NJeGGHgEd_CCFWksZKl:-NJeGGHgEd_CCFWksZKm:b5747ag) ([raw file](https://github.com/starkware-libs/cairo/blob/76c7e29bad9c82bdc00ea585654e50408c6c366d/crates/sierra_to_casm/src/invocations/test_utils.rs#L207)):*
> ```XML
> }
> impl std::fmt::Debug for ReducedCompiledInvocation {
>     fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
> ```

can you add a test.



_Code quote:_
```XML
fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result 
```
___
*[`crates/sierra_to_casm/src/invocations/starknet/storage_test.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1385#-NJeGzQQ8hT8nDdbCdr5:-NJeGzQQ8hT8nDdbCdr6:bhs12tq) ([raw file](https://github.com/starkware-libs/cairo/blob/76c7e29bad9c82bdc00ea585654e50408c6c366d/crates/sierra_to_casm/src/invocations/starknet/storage_test.rs#L51)):*
> ```XML
>         ReducedCompiledInvocation {
>             instructions: casm! {
>                 [ap + 0] = 8038072152842849266968829064307u128, ap++;
> ```

how did you pick the type?



_Code quote:_
```XML
u128
```

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1385#-:-NJeTNQPCy0WlS9KCljC:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/sierra_to_casm/src/invocations/test_utils.rs` line 207 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1385#-NJeGGHgEd_CCFWksZKl:-NJeT6pP2TREUrWKV_EA:b-ogh25j) ([raw file](https://github.com/starkware-libs/cairo/blob/b1b18a888074e42fe3d614ff4b1bcf7ef98a78d7/crates/sierra_to_casm/src/invocations/test_utils.rs#L207)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is just for the testing - so really no reason for it - it is just nicer for when a test fails.
</blockquote></details>

if it had a test it would have been easier to review.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1385)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/sierra_to_casm/src/invocations/test_utils.rs` line 207 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1385#-NJeGGHgEd_CCFWksZKl:-NJeV4ES8Km5Uo8I0dWA:b13x02y) ([raw file](https://github.com/starkware-libs/cairo/blob/b1b18a888074e42fe3d614ff4b1bcf7ef98a78d7/crates/sierra_to_casm/src/invocations/test_utils.rs#L207)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

if it had a test it would have been easier to review.
</blockquote></details>

understood - but writing tests for something that someone might decide to change on a dime is not necessary.

**Review by ilyalesokhin-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1385)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
