### PR TITLE
Member borrowing

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2348)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2342** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2342" target="_blank">Graphite</a> 
    * **PR #2347** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2347" target="_blank">Graphite</a> 
      * **PR #2348** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2348" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2348?utm_source=stack-comment).

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r1, 4 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2348)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/refs.rs` line 8 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2348#-NPYB1OX4meJ6JxoNz6a:-NPYB1OX4meJ6JxoNz6b:b-5ae9kc) ([raw file](https://github.com/starkware-libs/cairo/blob/ae24f92ad7762e6b2237af0417a4707e6992d3b4/crates/cairo-lang-lowering/src/lower/refs.rs#L8)):*
> ```XML
> 
> use crate::VariableId;
> ```

doc all
___
*[`crates/cairo-lang-semantic/src/resolve_path.rs` line 917 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2348#-NPYFO--EF7iE8J0_pJJ:-NPYFO--EF7iE8J0_pJK:bmckd3x) ([raw file](https://github.com/starkware-libs/cairo/blob/ae24f92ad7762e6b2237af0417a4707e6992d3b4/crates/cairo-lang-semantic/src/resolve_path.rs#L917)):*
> ```XML
>                     match arg {
>                         ExprFunctionCallArg::Reference(ref_arg) => {
>                             self.reduce_ref_arg(diagnostics, ref_arg)?
> ```

kinda surprised clippy doesn't complain.



_Suggestion:_
```XML
                    if let ExprFunctionCallArg::Reference(ref_arg) = arg {
                        self.reduce_ref_arg(diagnostics, ref_arg)?
                    }
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2348)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/refs.rs` line 8 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2348#-NPYB1OX4meJ6JxoNz6a:-NPl9DWd3ENVpganDtRz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ae24f92ad7762e6b2237af0417a4707e6992d3b4/crates/cairo-lang-lowering/src/lower/refs.rs#L8)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc all
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/resolve_path.rs` line 917 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2348#-NPYFO--EF7iE8J0_pJJ:-NPl97RnD7UdKzB9dgfF:b-einc7i) ([raw file](https://github.com/starkware-libs/cairo/blob/ae24f92ad7762e6b2237af0417a4707e6992d3b4/crates/cairo-lang-semantic/src/resolve_path.rs#L917)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

kinda surprised clippy doesn't complain.
</blockquote></details>

Noted. I want this to be exahustive.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2348#-:-NPlS9iK5XiDoUkCn7pq:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/refs.rs` line 56 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2348#-NPlQnU17zCP6XgXVhex:-NPlQnU2Eb8sdvjvHpWx:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/e92a7d2c6b2dee48a81ece32ad30162dfbf70792/crates/cairo-lang-lowering/src/lower/refs.rs#L56)):*
> ```XML
>         value: &mut Value,
>     ) -> Option<VariableId> {
>         eprintln!("assemble_value {value:?}");
> ```

remove



_Code quote:_
```XML
        eprintln!("assemble_value {value:?}");
```
___
*[`crates/cairo-lang-lowering/src/lower/refs.rs` line 77 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2348#-NPlQq_m3tGgmzmdFsZi:-NPlQq_m3tGgmzmdFsZj:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/e92a7d2c6b2dee48a81ece32ad30162dfbf70792/crates/cairo-lang-lowering/src/lower/refs.rs#L77)):*
> ```XML
>         member_path: &VarMemberPath,
>     ) -> Option<&mut Value> {
>         eprintln!("break_into_value {member_path:?}");
> ```

remove



_Code quote:_
```XML
        eprintln!("break_into_value {member_path:?}");
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2348)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/refs.rs` line 56 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2348#-NPlQnU17zCP6XgXVhex:-NPldfUt-z-3iX6_UG-H:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e92a7d2c6b2dee48a81ece32ad30162dfbf70792/crates/cairo-lang-lowering/src/lower/refs.rs#L56)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/refs.rs` line 77 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2348#-NPlQq_m3tGgmzmdFsZi:-NPldfzj-1pqBuZlbnZ-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e92a7d2c6b2dee48a81ece32ad30162dfbf70792/crates/cairo-lang-lowering/src/lower/refs.rs#L77)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 9 files at r1, 1 of 6 files at r2, 7 of 8 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2348)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2348)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
