### PR TITLE
added while-let in lowering

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5054)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5054)* status: 2 of 10 files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 252 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5054#-NqTOZG53Qzi3hdL7oX6:-NqTOZG53Qzi3hdL7oX7:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/368e456d1b13205cf23b0ba04c75ff4a140463ff/crates/cairo-lang-lowering/src/lower/mod.rs#L252)):*
> ```XML
> }
> /// Lowers an expression of type if where the condition is of type [semantic::Condition::Let].
> pub fn lower_expr_while_let(
> ```





_Suggestion:_
```XML

/// Lowers an expression of type if where the condition is of type [semantic::Condition::Let].
pub fn lower_expr_while_let(
```
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 312 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5054#-NqTOa3e97HNCgwYI9d1:-NqTOa3e97HNCgwYI9d2:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/368e456d1b13205cf23b0ba04c75ff4a140463ff/crates/cairo-lang-lowering/src/lower/mod.rs#L312)):*
> ```XML
>     )
> }
> /// Lowers a loop inner function into [FlatLowered].
> ```





_Suggestion:_
```XML
}

/// Lowers a loop inner function into [FlatLowered].
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5054)* status: 2 of 10 files reviewed, 3 unresolved discussions (waiting on @TomerStarkware)

___
*[`examples/triangle_while.cairo` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5054#-NqTOstA7WwiJSt-uA3g:-NqTOstA7WwiJSt-uA3h:b-fzcz6k) ([raw file](https://github.com/starkware-libs/cairo/blob/368e456d1b13205cf23b0ba04c75ff4a140463ff/examples/triangle_while.cairo#L1)):*
> ```Cairo
> fn triangle_while(n: felt252) -> felt252 {
> ```

since we have cairo tests - just add it as a proper cairo test.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5054)* status: 2 of 12 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 252 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5054#-NqTOZG53Qzi3hdL7oX6:-NqVACs_7FNjBYyMSRdY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/368e456d1b13205cf23b0ba04c75ff4a140463ff/crates/cairo-lang-lowering/src/lower/mod.rs#L252)):*
> ```XML
> }
> /// Lowers an expression of type if where the condition is of type [semantic::Condition::Let].
> pub fn lower_expr_while_let(
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 312 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5054#-NqTOa3e97HNCgwYI9d1:-NqVAE9E1-aCB-GNEeLn:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/368e456d1b13205cf23b0ba04c75ff4a140463ff/crates/cairo-lang-lowering/src/lower/mod.rs#L312)):*
> ```XML
>     )
> }
> /// Lowers a loop inner function into [FlatLowered].
> ```

Done.
___
*[`examples/triangle_while.cairo` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5054#-NqTOstA7WwiJSt-uA3g:-NqVAGxD7fi6PqHgOHd8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/368e456d1b13205cf23b0ba04c75ff4a140463ff/examples/triangle_while.cairo#L1)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

since we have cairo tests - just add it as a proper cairo test.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5054)* status: 3 of 12 files reviewed, 4 unresolved discussions (waiting on @TomerStarkware)

___
*[`corelib/src/test/while_test.cairo` line 40 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5054#-NqWt8QpBuRb8HC1F-fw:-NqWt8Qq18cWu8L4OF1N:brwmmsn) ([raw file](https://github.com/starkware-libs/cairo/blob/9df4c31e97439bcd922f8558754da672ae784ecc/corelib/src/test/while_test.cairo#L40)):*
> ```Cairo
>     assert_eq!(i, 10);
>     assert_eq!(j, 5);
> }
> ```

test something more minor - 
decide what parts you are trying to test and name a test testing is specifically for each part.



_Code quote:_
```Cairo
fn triangle_while(n: felt252) -> felt252 {
    let mut arr = array![];
    let mut i = 1;
    while i != n + 1 {
        arr.append(i);
        i += 1;
    };
    let mut sum = 0;
    while let Option::Some(x) = arr.pop_front() {
        sum += x;
    };
    sum
}

#[test]
fn test_triangle_while() {
    assert_eq!(triangle_while(10), 55);
    assert_eq!(triangle_while(20), 210);
}

#[test]
fn test_outer_loop_break() {
    let mut i = 0;
    let mut j = 0;
    while let true =
        i != 10 {
            j = 0;
            while let true = j != 10 {
                if j == 5 {
                    break;
                }
                j += 1;
            };
            i += 1;
        };
    assert_eq!(i, 10);
    assert_eq!(j, 5);
}
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5054)* status: 3 of 12 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/test/while_test.cairo` line 40 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5054#-NqWt8QpBuRb8HC1F-fw:-NqX5yOUECUxdGZsWC99:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9df4c31e97439bcd922f8558754da672ae784ecc/corelib/src/test/while_test.cairo#L40)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

test something more minor - 
decide what parts you are trying to test and name a test testing is specifically for each part.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5054)* status: 3 of 12 files reviewed, 4 unresolved discussions (waiting on @TomerStarkware)

___
*[`corelib/src/test/while_test.cairo` line 17 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5054#-NqXBOXO1YJaQRdk9HNP:-NqXBOXO1YJaQRdk9HNQ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7c72181a8eb382ab1db73eb6da2f9dc91a7ab19d/corelib/src/test/while_test.cairo#L17)):*
> ```Cairo
>     let mut arr2 = array![];
>     assert_eq!(array_sum(ref arr2), 0);
> }
> ```





_Suggestion:_
```Cairo
fn array_sum(mut arr: Array<felt252>) -> felt252 {
    let mut sum = 0;
    while let Option::Some(x) = arr.pop_front() {
        sum += x;
    };
    sum
}

#[test]
fn test_while_let() {
    assert_eq!(array_sum(array![1, 2, 3, 4], 10);
    assert_eq!(array_sum(array![], 0);
}
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 10 files at r1, 7 of 9 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5054)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5054)* status: 11 of 13 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/test/while_test.cairo` line 17 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5054#-NqXBOXO1YJaQRdk9HNP:-NqXPNlp7MXpHGwyjED4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7c72181a8eb382ab1db73eb6da2f9dc91a7ab19d/corelib/src/test/while_test.cairo#L17)):*
> ```Cairo
>     let mut arr2 = array![];
>     assert_eq!(array_sum(ref arr2), 0);
> }
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5054)* status: 11 of 13 files reviewed, 3 unresolved discussions (waiting on @TomerStarkware)

___
*[`corelib/src/test/while_test.cairo` line 12 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5054#-NqXPxjRAY9OgLQKw3L2:-NqXPxjRAY9OgLQKw3L3:bhv7muy) ([raw file](https://github.com/starkware-libs/cairo/blob/e8f9a41c9db9188335f73a3fbff2ef4e7bec7706/corelib/src/test/while_test.cairo#L12)):*
> ```Cairo
> 
> #[test]
> fn sum_array() {
> ```

name the test on what you are trying to test - you are not trying to test the concept of array summation.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5054)* status: 11 of 13 files reviewed, 3 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-casm/src/hints/test.rs` line 13 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5054#-NqXQ8JU5ZS1sr2tQjAn:-NqXQ8JU5ZS1sr2tQjAo:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/e8f9a41c9db9188335f73a3fbff2ef4e7bec7706/crates/cairo-lang-casm/src/hints/test.rs#L13)):*
> ```XML
>     let hint = CoreHint::AllocSegment { dst };
>     let x = vec![1, 2];
>     x.into_iter()
> ```

?



_Code quote:_
```XML
    let x = vec![1, 2];
    x.into_iter()
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5054)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5054)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/test/while_test.cairo` line 12 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5054#-NqXPxjRAY9OgLQKw3L2:-NqXeApQ9B33-vxKyugJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e8f9a41c9db9188335f73a3fbff2ef4e7bec7706/corelib/src/test/while_test.cairo#L12)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

name the test on what you are trying to test - you are not trying to test the concept of array summation.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-casm/src/hints/test.rs` line 13 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5054#-NqXQ8JU5ZS1sr2tQjAn:-NqXdlMa3VaCRXiWTXwT:b-9unw5o) ([raw file](https://github.com/starkware-libs/cairo/blob/e8f9a41c9db9188335f73a3fbff2ef4e7bec7706/crates/cairo-lang-casm/src/hints/test.rs#L13)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

deleted

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5054#-:-NqXvaacBiVXSE_C3lAe:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
