### PR TITLE
Add generics handling to trait/impl types

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5476)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 38 of 40 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5476)* status: 38 of 40 files reviewed, 6 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/ec.cairo` line 127 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5476#-NwJcxZo43J1Z6ydhaO3:-NwJcxZo43J1Z6ydhaO4:bs6hgm1) ([raw file](https://github.com/starkware-libs/cairo/blob/50e8ff5c5c1b1da64691c9db1eb17d887356100e/corelib/src/ec.cairo#L127)):*
> ```Cairo
>     #[inline(always)]
>     fn new(x: felt252, y: felt252) -> Option<EcPoint> {
>         Option::Some(Self::new_nz(:x, :y)?.into())
> ```

this sort of changes mean that we need the `Self::` diag to be a warning and not an error.



_Code quote:_
```Cairo
        Option::Some(Self::new_nz(:x, :y)?.into())
```
___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 782 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5476#-NwJcK4y9GMsufgdW3pP:-NwJcK4y9GMsufgdW3pQ:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/50e8ff5c5c1b1da64691c9db1eb17d887356100e/crates/cairo-lang-semantic/src/items/functions.rs#L782)):*
> ```XML
> 
>     // // If the generic impl of the impl function is not concrete, nothing to implize.
>     // let Some(concrete_impl_id) =
> ```

.
___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5476#-NwJdPuc60cho4YsLJEi:-NwJdPuc60cho4YsLJEj:byii1s8) ([raw file](https://github.com/starkware-libs/cairo/blob/50e8ff5c5c1b1da64691c9db1eb17d887356100e/crates/cairo-lang-semantic/src/items/generics.rs#L141)):*
> ```XML
>     }
>     /// Returns the generic param as a generic argument.
>     pub fn as_arg(&self, db: &dyn SemanticGroup) -> GenericArgumentId {
> ```

reimplement `generic_params_to_args` in functions.rs using this.
___
*[`crates/cairo-lang-semantic/src/items/test.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5476#-NwJcZbp8vnI6ZgOAReF:-NwJcZbp8vnI6ZgOAReG:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/50e8ff5c5c1b1da64691c9db1eb17d887356100e/crates/cairo-lang-semantic/src/items/test.rs#L15)):*
> ```XML
>         trait_: "trait",
>         trait_type: "trait_type",
>         trait_type2: "trait_type2",
> ```

.
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 1301 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5476#-NwJcogL4RcsGZEyEBew:-NwJcogL4RcsGZEyEBex:bd71ltb) ([raw file](https://github.com/starkware-libs/cairo/blob/50e8ff5c5c1b1da64691c9db1eb17d887356100e/crates/cairo-lang-semantic/src/resolve/mod.rs#L1301)):*
> ```XML
>             == current_segment_concrete_trait_id.generic_args(self.db)
>         {
>             return Err(diagnostics.report_by_ptr(segment_stable_ptr, TraitItemForbiddenInItsImpl));
> ```

not need to `Err` on adding these diagnostics.



_Code quote:_
```XML
            return Err(diagnostics.report_by_ptr(segment_stable_ptr, TraitItemForbiddenInItsImpl));
```
___
*[`crates/cairo-lang-syntax/src/node/helpers.rs` line 600 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5476#-NwJe-wPEx2VhDxpmgMJ:-NwJe-wPEx2VhDxpmgMK:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/50e8ff5c5c1b1da64691c9db1eb17d887356100e/crates/cairo-lang-syntax/src/node/helpers.rs#L600)):*
> ```XML
> }
> 
> pub trait HasGenericArgValue {
> ```

doc

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 40 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5476)* status: 39 of 40 files reviewed, 6 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 340 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5476#-NwJzpKvAMnVAQ0Xsyeb:-NwJzpKvAMnVAQ0Xsyec:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/a63da56c243941f9c8e2bca8f7bcaf553ecacb58/crates/cairo-lang-semantic/src/items/tests/trait_type#L340)):*
> ```
> 
> //! > TODO(yuval):
> Check diag "Candidate impl test::MyImpl::<?0> has an unused generic parameter"
> ```

?



_Code quote:_
```
Check diag "Candidate impl test::MyImpl::<?0> has an unused generic parameter"
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5476)* status: 32 of 40 files reviewed, 6 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/ec.cairo` line 127 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5476#-NwJcxZo43J1Z6ydhaO3:-NwK1y1U188l9EciQdSs:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/50e8ff5c5c1b1da64691c9db1eb17d887356100e/corelib/src/ec.cairo#L127)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this sort of changes mean that we need the `Self::` diag to be a warning and not an error.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 782 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5476#-NwJcK4y9GMsufgdW3pP:-NwJw0Yu-8SCuUrGEWFR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/50e8ff5c5c1b1da64691c9db1eb17d887356100e/crates/cairo-lang-semantic/src/items/functions.rs#L782)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5476#-NwJdPuc60cho4YsLJEi:-NwJwOHhCKy60OfODrvw:b-vjk0ak) ([raw file](https://github.com/starkware-libs/cairo/blob/50e8ff5c5c1b1da64691c9db1eb17d887356100e/crates/cairo-lang-semantic/src/items/generics.rs#L141)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

reimplement `generic_params_to_args` in functions.rs using this.
</blockquote></details>

Done. + moved it here.
___
*[`crates/cairo-lang-semantic/src/items/tests/trait_type` line 340 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5476#-NwJzpKvAMnVAQ0Xsyeb:-NwK1wW56-S00w0IYN5G:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a63da56c243941f9c8e2bca8f7bcaf553ecacb58/crates/cairo-lang-semantic/src/items/tests/trait_type#L340)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 1301 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5476#-NwJcogL4RcsGZEyEBew:-NwK1x8g18qJ5tKXQJwC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/50e8ff5c5c1b1da64691c9db1eb17d887356100e/crates/cairo-lang-semantic/src/resolve/mod.rs#L1301)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

not need to `Err` on adding these diagnostics.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/test.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5476#-NwJcZbp8vnI6ZgOAReF:-NwJxCD70eYSM3R6JzsF:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/50e8ff5c5c1b1da64691c9db1eb17d887356100e/crates/cairo-lang-semantic/src/items/test.rs#L15)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-syntax/src/node/helpers.rs` line 600 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5476#-NwJe-wPEx2VhDxpmgMJ:-NwJxRme22HdTYZDU8PO:brpmqc3) ([raw file](https://github.com/starkware-libs/cairo/blob/50e8ff5c5c1b1da64691c9db1eb17d887356100e/crates/cairo-lang-syntax/src/node/helpers.rs#L600)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

removed.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5476)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 542 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5476#-NwK3UCz1acCZAtM0emm:-NwK3UD-AzmFiH3242j3:bb5sv3l) ([raw file](https://github.com/starkware-libs/cairo/blob/1d508df2598f37fa22d6ad4b5832dcff0ae2fec4/crates/cairo-lang-semantic/src/resolve/mod.rs#L542)):*
> ```XML
>                 // TODO(yuval): on a breaking version change, consider changing warning diagnostics
>                 // to error diagnostics. Currently we ignore the returned result (`.ok()`), but if
>                 // changed to errors, we should fail on it (`?`).
> ```

remove - should ignore in any case - as it give the maximal amount of information - as we CAN handle.

the forbid name of the function still is completely sensible IMO.



_Code quote:_
```XML
                // TODO(yuval): on a breaking version change, consider changing warning diagnostics
                // to error diagnostics. Currently we ignore the returned result (`.ok()`), but if
                // changed to errors, we should fail on it (`?`).
```

**Comment by yuvalsw** [comment]
change target branch

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5476)* status: 35 of 40 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 542 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5476#-NwK3UCz1acCZAtM0emm:-NwK5WP51UeeNC9Hfjx6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1d508df2598f37fa22d6ad4b5832dcff0ae2fec4/crates/cairo-lang-semantic/src/resolve/mod.rs#L542)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove - should ignore in any case - as it give the maximal amount of information - as we CAN handle.

the forbid name of the function still is completely sensible IMO.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5476#-:-NwK7RYmDoeWgl95Ifre:bnfp4nl)* status: 39 of 40 files reviewed, 1 unresolved discussion

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 4 files at r4, 13 of 13 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5476)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5476)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
