### PR TITLE
LS: Clean up server capabilities declaration code

### PR DESCRIPTION
**Pull request by mkaput**
This PR implements a `server_capabilities` macro that unclutters the logic in this file. It also regroups capability definitions by concern instead of by kind, which should prevent forgetting updating one kind of
 capability without updating another one.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6348)

### CODE REVIEW

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6348)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lsp/capabilities/server.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6348#-O5wq_V62ws3CPkHkvL4:-O5wq_V62ws3CPkHkvL5:bu2xnbl) ([raw file](https://github.com/starkware-libs/cairo/blob/93a5238f6b2eef614e4abde743391524546aebec/crates/cairo-lang-language-server/src/lsp/capabilities/server.rs#L44)):*
> ```XML
> }
> 
> macro_rules! server_capabilities {
> ```

For reference, this is result of expanding this macro:

```rust
fn collect_server_capabilities_impl(
    client_capabilities: &ClientCapabilities
) -> ServerCapabilities {
    let mut capabilities = ServerCapabilities::default();

    {
        if !ClientCapabilities::text_document_synchronization_dynamic_registration(client_capabilities) {
            capabilities.text_document_sync = Some((TextDocumentSyncCapability::Options(TextDocumentSyncOptions {
                open_close: Some(true),
                change: Some(TextDocumentSyncKind::FULL),
                will_save: Some(false),
                will_save_wait_until: Some(false),
                save: Some(TextDocumentSyncSaveOptions::SaveOptions(SaveOptions {
                    include_text: Some(false),
                })),
            })));
        }
    }
    {
        if !ClientCapabilities::did_change_watched_files_dynamic_registration(client_capabilities) {}
    }
    {
        if !ClientCapabilities::completion_dynamic_registration(client_capabilities) {
            let completion_options = (CompletionOptions {
                resolve_provider: Some(false),
                trigger_characters: Some(vec![".".to_string(), ":".to_string()]),
                all_commit_characters: None,
                work_done_progress_options: Default::default(),
                completion_item: None,
            });
            capabilities.completion_provider = Some(completion_options);
        }
    }
    {
        if !ClientCapabilities::execute_command_dynamic_registration(client_capabilities) {
            let execute_command_options = (ExecuteCommandOptions {
                commands: vec!["cairo.reload".to_string()],
                work_done_progress_options: Default::default(),
            });
            capabilities.execute_command_provider = Some(execute_command_options);
        }
    }
    {
        if !ClientCapabilities::semantic_tokens_dynamic_registration(client_capabilities) {
            let semantic_tokens_options = (SemanticTokensOptions {
                legend: SemanticTokensLegend {
                    token_types: SemanticTokenKind::legend(),
                    token_modifiers: vec![],
                },
                full: Some(SemanticTokensFullOptions::Bool(true)),
                ..SemanticTokensOptions::default()
            });
            capabilities.semantic_tokens_provider = Some((semantic_tokens_options.into()));
        }
    }
    {
        if !ClientCapabilities::formatting_dynamic_registration(client_capabilities) {
            capabilities.document_formatting_provider = Some((OneOf::Left(true)));
        }
    }
    {
        if !ClientCapabilities::hover_dynamic_registration(client_capabilities) {
            capabilities.hover_provider = Some((HoverProviderCapability::Simple(true)));
        }
    }
    {
        if !ClientCapabilities::definition_dynamic_registration(client_capabilities) {
            capabilities.definition_provider = Some((OneOf::Left(true)));
        }
    }
    {
        if !ClientCapabilities::code_action_dynamic_registration(client_capabilities) {
            capabilities.code_action_provider = Some((CodeActionProviderCapability::Simple(true)));
        }
    }

    capabilities
}
fn collect_dynamic_registrations_impl(
    client_capabilities: &ClientCapabilities
) -> Vec<Registration> {
    let mut registrations = Vec::new();

    if ClientCapabilities::text_document_synchronization_dynamic_registration(client_capabilities) {
        registrations.push(Registration {
            id: "textDocument/didOpen".to_string(),
            method: "textDocument/didOpen".to_string(),
            register_options: Some(
                serde_json::to_value(&(text_document_registration_options())).unwrap()
            ),
        });
        registrations.push(Registration {
            id: "textDocument/didChange".to_string(),
            method: "textDocument/didChange".to_string(),
            register_options: Some(
                serde_json::to_value(&(TextDocumentChangeRegistrationOptions {
                    document_selector: text_document_registration_options().document_selector,
                    sync_kind: 1,   // TextDocumentSyncKind::FULL 
                })).unwrap()
            ),
        });
        registrations.push(Registration {
            id: "textDocument/didSave".to_string(),
            method: "textDocument/didSave".to_string(),
            register_options: Some(
                serde_json::to_value(&(TextDocumentSaveRegistrationOptions {
                    include_text: Some(false),
                    text_document_registration_options: text_document_registration_options(),
                })).unwrap()
            ),
        });
        registrations.push(Registration {
            id: "textDocument/didClose".to_string(),
            method: "textDocument/didClose".to_string(),
            register_options: Some(
                serde_json::to_value(&(text_document_registration_options())).unwrap()
            ),
        });
    }
    if ClientCapabilities::did_change_watched_files_dynamic_registration(client_capabilities) {
        registrations.push(Registration {
            id: "workspace/didChangeWatchedFiles".to_string(),
            method: "workspace/didChangeWatchedFiles".to_string(),
            register_options: Some(
                serde_json::to_value(&(DidChangeWatchedFilesRegistrationOptions {
                    watchers: ["/**/*.cairo", "/**/Scarb.toml", "/**/Scarb.lock", "/**/cairo_project.toml"]
                        .map(|glob_pattern| FileSystemWatcher {
                            glob_pattern: GlobPattern::String(glob_pattern.to_string()),
                            kind: None,
                        })
                        .into(),
                })).unwrap()
            ),
        });
    }
    if ClientCapabilities::completion_dynamic_registration(client_capabilities) {
        let completion_options = (CompletionOptions {
            resolve_provider: Some(false),
            trigger_characters: Some(vec![".".to_string(), ":".to_string()]),
            all_commit_characters: None,
            work_done_progress_options: Default::default(),
            completion_item: None,
        });
        registrations.push(Registration {
            id: "textDocument/completion".to_string(),
            method: "textDocument/completion".to_string(),
            register_options: Some(
                serde_json::to_value(&(CompletionRegistrationOptions {
                    text_document_registration_options: text_document_registration_options(),
                    completion_options,
                })).unwrap()
            ),
        });
    }
    if ClientCapabilities::execute_command_dynamic_registration(client_capabilities) {
        let execute_command_options = (ExecuteCommandOptions {
            commands: vec!["cairo.reload".to_string()],
            work_done_progress_options: Default::default(),
        });
        registrations.push(Registration {
            id: "workspace/executeCommand".to_string(),
            method: "workspace/executeCommand".to_string(),
            register_options: Some(
                serde_json::to_value(&(ExecuteCommandRegistrationOptions {
                    commands: execute_command_options.commands.clone(),
                    execute_command_options,
                })).unwrap()
            ),
        });
    }
    if ClientCapabilities::semantic_tokens_dynamic_registration(client_capabilities) {
        let semantic_tokens_options = (SemanticTokensOptions {
            legend: SemanticTokensLegend {
                token_types: SemanticTokenKind::legend(),
                token_modifiers: vec![],
            },
            full: Some(SemanticTokensFullOptions::Bool(true)),
            ..SemanticTokensOptions::default()
        });
        registrations.push(Registration {
            id: "textDocument/semanticTokens".to_string(),
            method: "textDocument/semanticTokens".to_string(),
            register_options: Some(
                serde_json::to_value(&(SemanticTokensRegistrationOptions {
                    text_document_registration_options: text_document_registration_options(),
                    semantic_tokens_options,
                    static_registration_options: Default::default(),
                })).unwrap()
            ),
        });
    }
    if ClientCapabilities::formatting_dynamic_registration(client_capabilities) {
        registrations.push(Registration {
            id: "textDocument/formatting".to_string(),
            method: "textDocument/formatting".to_string(),
            register_options: Some(
                serde_json::to_value(&(DocumentFormattingRegistrationOptions {
                    text_document_registration_options: text_document_registration_options(),
                    document_formatting_options: Default::default(),
                })).unwrap()
            ),
        });
    }
    if ClientCapabilities::hover_dynamic_registration(client_capabilities) {
        registrations.push(Registration {
            id: "textDocument/hover".to_string(),
            method: "textDocument/hover".to_string(),
            register_options: Some(
                serde_json::to_value(&(HoverRegistrationOptions {
                    text_document_registration_options: text_document_registration_options(),
                    hover_options: Default::default(),
                })).unwrap()
            ),
        });
    }
    if ClientCapabilities::definition_dynamic_registration(client_capabilities) {
        registrations.push(Registration {
            id: "textDocument/definition".to_string(),
            method: "textDocument/definition".to_string(),
            register_options: Some(
                serde_json::to_value(&(DefinitionRegistrationOptions {
                    text_document_registration_options: text_document_registration_options(),
                    definition_options: DefinitionOptions {
                        work_done_progress_options: Default::default(),
                    },
                })).unwrap()
            ),
        });
    }
    if ClientCapabilities::code_action_dynamic_registration(client_capabilities) {
        registrations.push(Registration {
            id: "textDocument/codeAction".to_string(),
            method: "textDocument/codeAction".to_string(),
            register_options: Some(
                serde_json::to_value(&(CodeActionRegistrationOptions {
                    text_document_registration_options: text_document_registration_options(),
                    code_action_options: Default::default(),
                })).unwrap()
            ),
        });
    }

    registrations
}
```

**Review by piotmag769 — COMMENTED** [review]
I'm sorry but it is not more readable imo xD

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6348#-:-O5x9J0M8XHE7vwZvVxa:bxfrvnw)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @orizi)

**Review by mkaput — COMMENTED** [review]
I don't know how. The trick here is that both kinds are not matching 1:1, we need a way to express the bindings somehow in code and this is what this macro tries to accomplish.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6348#-:-O60ensO32uWMlZkXq5p:b-2bb92u)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @Draggu and @orizi)

**Review by mkaput — COMMENTED** [review]
The only contact point actually is the client capability that is related to the feature + for some capabilities, we can share some values (see the `let` constructs)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6348#-:-O60fH7-CqjF45XbB972:b-8a5k8u)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @Draggu and @orizi)

**Review by Draggu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6348)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-language-server/src/lsp/capabilities/server.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6348#-O617yvtE9yAgx8BdOIa:-O617yvtE9yAgx8BdOIb:bbmfdu9) ([raw file](https://github.com/starkware-libs/cairo/blob/93a5238f6b2eef614e4abde743391524546aebec/crates/cairo-lang-language-server/src/lsp/capabilities/server.rs#L44)):*
> ```XML
> }
> 
> macro_rules! server_capabilities {
> ```

Can we at least move this to new file and document it as its not clear why we need this macro?

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6348)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Draggu and @orizi)

___
*[`crates/cairo-lang-language-server/src/lsp/capabilities/server.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6348#-O617yvtE9yAgx8BdOIa:-O62-sTDBuNtjtFrTMzE:b-b1nlb7) ([raw file](https://github.com/starkware-libs/cairo/blob/93a5238f6b2eef614e4abde743391524546aebec/crates/cairo-lang-language-server/src/lsp/capabilities/server.rs#L44)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

Can we at least move this to new file and document it as its not clear why we need this macro?
</blockquote></details>

I disagree with separate file, it's used only here.

I can doc this, but I see the consensus is to drop this PR, so should I close it?

**Review by mkaput — COMMENTED** [review]
I tried to work out better impls and failed to do so (reached my time budget for this). Closing.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6348#-:-O67ciE62hTYBOvBiuQo:b-150suo)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Draggu and @orizi)

**Pull request closed without merging**
