### PR TITLE
Inline macro refactor

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3782)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3782** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3782" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/3782?utm_source=stack-comment).

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 34 of 62 files at r1, 1 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3782)* status: 35 of 62 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-filesystem/src/ids.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3782#-NaM_pUbBynOXHwEc1wc:-NaM_pUbBynOXHwEc1wd:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/5242a1a39f3aae4f11819c41d8c3951e3bf5066b/crates/cairo-lang-filesystem/src/ids.rs#L47)):*
> ```XML
> }
> #[derive(Clone, Debug, Hash, PartialEq, Eq)]
> pub enum FileKind {
> ```

doc
___
*[`crates/cairo-lang-parser/src/db.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3782#-NaMaGPT4elmEr1PAWcv:-NaMaGPU0RhIz1ZdSjld:bljob9k) ([raw file](https://github.com/starkware-libs/cairo/blob/5242a1a39f3aae4f11819c41d8c3951e3bf5066b/crates/cairo-lang-parser/src/db.rs#L27)):*
> ```XML
>     /// Parses a file and returns its AST.
>     fn file_module_syntax(&self, file_id: FileId) -> Maybe<SyntaxFile>;
>     /// Parses a file and returns its AST.
> ```

fix doc

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3782)* status: 57 of 63 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-filesystem/src/ids.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3782#-NaM_pUbBynOXHwEc1wc:-NaNHEd9BynZYo6ARlKf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5242a1a39f3aae4f11819c41d8c3951e3bf5066b/crates/cairo-lang-filesystem/src/ids.rs#L47)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/db.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3782#-NaMaGPT4elmEr1PAWcv:-NaNHHZ86Do-L422QAH5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5242a1a39f3aae4f11819c41d8c3951e3bf5066b/crates/cairo-lang-parser/src/db.rs#L27)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix doc
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 62 files at r1, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3782#-:-NaQrCe6Cid1ybRoPCxD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3782)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Comment by milancermak** [comment]
It looks like this PR broke the `inline_macros` tests (and potentially macro functionality?). The suite is commented out, but if I put it back in and run it, I get the following:

```
running 1 test
thread 'test::expand_plugin::inline_macros' panicked at 'assertion failed: `(left == right)`: Test "Test consteval_int! macro" failed.
In /Users/m/projects/my-cairo-forks/cairo/crates/cairo-lang-plugins/src/test_data/inline_macros:1.
Rerun with CAIRO_FIX_TESTS=1 to fix.

Diff < left / right > :
 const a: felt252 = 0;
 
 
<const b: felt252 = consteval_int!(4 + 5);
>const b: felt252 = 9;
 
 
 const c: felt252 = 4 + 5;
 
 
<const d: felt252 = consteval_int!(23 + 4 * 5 + (4 + 5) / 2);
>const d: felt252 = 47;
 
 
<const e: u8 = consteval_int!(255 + 1 - 1);
>const e: u8 = 255;

', crates/cairo-lang-test-utils/src/parse_test_file.rs:322:17
```

**Pull request merged**
