### PR TITLE
Use BigIntAsHex for Immediate values.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2548)

### CODE REVIEW

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 4 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2548)* status: 4 of 18 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-casm/src/builder.rs` line 348 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2548#-NQu72Zo3cZCp6VSdE7_:-NQu72Zo3cZCp6VSdE7a:be6wc3d) ([raw file](https://github.com/starkware-libs/cairo/blob/fd69cc2403ec9c69f8d0bfc2a7add594ab255f5d/crates/cairo-lang-casm/src/builder.rs#L348)):*
> ```XML
>         let instruction = self.get_instruction(
>             InstructionBody::AddAp(AddApInstruction {
>                 operand: ResOperand::Immediate(BigIntAsHex { value: BigInt::from(size) }),
> ```

Why not implement `into()`?

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 13 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2548)* status: 17 of 18 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-utils/src/bigint.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2548#-NQu8DBu1U2IM6I7STr5:-NQu8DBu1U2IM6I7STr6:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/fd69cc2403ec9c69f8d0bfc2a7add594ab255f5d/crates/cairo-lang-utils/src/bigint.rs#L73)):*
> ```XML
>     let s = &String::deserialize(deserializer)?;
>     match s.strip_prefix('-') {
>         Some(num_no_minus) => {
> ```





_Suggestion:_
```XML
        Some(abs_value) => {
            Ok(deserialize_from_str::<D>(abs_value)?.to_bigint().unwrap().neg())
        }
```

**Review by liorgold2 — APPROVED** [review]
> Reviewed 1 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2548)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-utils/src/bigint_test.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2548#-NQu8dP6DVLUl3md755l:-NQu8dP6DVLUl3md755m:b-fhn7p9) ([raw file](https://github.com/starkware-libs/cairo/blob/fd69cc2403ec9c69f8d0bfc2a7add594ab255f5d/crates/cairo-lang-utils/src/bigint_test.rs#L26)):*
> ```XML
>     );
> 
>     assert_eq!(num, serde_json::from_str(&serialized).unwrap())
> ```

Add positive case, and BigUint tests.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2548)* status: 13 of 18 files reviewed, all discussions resolved (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-utils/src/bigint_test.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2548#-NQu8dP6DVLUl3md755l:-NQuGkAr8EcDFjClmZFs:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/fd69cc2403ec9c69f8d0bfc2a7add594ab255f5d/crates/cairo-lang-utils/src/bigint_test.rs#L26)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Add positive case, and BigUint tests.
</blockquote></details>

done

**Review by liorgold2 — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2548)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2548#-:-NQuIERTC7D3MR7vqcJ6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
