### PR TITLE
Add single_value_type query.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4794)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4794)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 430 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4794#-No6oh6GE_iv8kqdzd93:-No6oh6GE_iv8kqdzd94:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/608a6a263476c299461f46cdb745ba7ca66248ce/crates/cairo-lang-semantic/src/types.rs#L430)):*
> ```XML
> }
> 
> pub fn single_value_type(db: &dyn SemanticGroup, ty: TypeId) -> Maybe<bool> {
> ```





_Suggestion:_
```XML
/// Query implementation of [crate::db::SemanticGroup::single_value_type].
pub fn single_value_type(db: &dyn SemanticGroup, ty: TypeId) -> Maybe<bool> {
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4794)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 434 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4794#-No6ovsqDyvtcONshVfE:-No6ovsqDyvtcONshVfF:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/608a6a263476c299461f46cdb745ba7ca66248ce/crates/cairo-lang-semantic/src/types.rs#L434)):*
> ```XML
>         semantic::TypeLongId::Concrete(concrete_type_id) => match concrete_type_id {
>             ConcreteTypeId::Struct(id) => db.struct_members(id.struct_id(db))?.is_empty(),
>             ConcreteTypeId::Enum(id) => {
> ```





_Suggestion:_
```XML
        semantic::TypeLongId::Concrete(concrete_type_id) => match concrete_type_id {
            ConcreteTypeId::Struct(id) => {
                for member in db.struct_members(id.struct_id(db))? {
                    if !db.single_value_type(member.ty)? {
                        return Ok(false);
                    }
                }
                true
            },
            ConcreteTypeId::Enum(id) => {
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4794)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 430 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4794#-No6oh6GE_iv8kqdzd93:-No6t7egCYt2W9K7SEtN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/608a6a263476c299461f46cdb745ba7ca66248ce/crates/cairo-lang-semantic/src/types.rs#L430)):*
> ```XML
> }
> 
> pub fn single_value_type(db: &dyn SemanticGroup, ty: TypeId) -> Maybe<bool> {
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/types.rs` line 434 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4794#-No6ovsqDyvtcONshVfE:-No6t7Tj4Fu6bn60HbQ1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/608a6a263476c299461f46cdb745ba7ca66248ce/crates/cairo-lang-semantic/src/types.rs#L434)):*
> ```XML
>         semantic::TypeLongId::Concrete(concrete_type_id) => match concrete_type_id {
>             ConcreteTypeId::Struct(id) => db.struct_members(id.struct_id(db))?.is_empty(),
>             ConcreteTypeId::Enum(id) => {
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4794#-:-No6tvIz0HywCDUiGv9_:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
