### PR TITLE
Add --single-file flag

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3533)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3533)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`README.md` line 92 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3533#-NZ-hcTCCAQJw1jhF4T5:-NZ-hcTCCAQJw1jhF4T6:baho6ru) ([raw file](https://github.com/starkware-libs/cairo/blob/d4e018c56b83acf39f56591a1263d5a676f285dc/README.md#L92)):*
> ```Markdown
> Or specify the contract path if multiple contracts are defined in the same project:
> ```bash
> cargo run --bin starknet-compile -- --single-file /path/to/input/crate /path/to/output.json --contract-path path::to::contract
> ```

this one's input was already a crate.



_Suggestion:_
```Markdown
cargo run --bin starknet-compile -- /path/to/input/crate /path/to/output.json --contract-path path::to::contract
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3533)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`README.md` line 92 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3533#-NZ-hcTCCAQJw1jhF4T5:-NZ-lgJJ26cl9IuMTJir:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d4e018c56b83acf39f56591a1263d5a676f285dc/README.md#L92)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this one's input was already a crate.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3533#-:-NZ-lomi59O5yL4Rs953:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Comment by FabijanC** [comment]
How is this breaking change to be handled semver-wise? Will it require a major version increment? Or are those only reserved for language-level breaking changes (not the CLI-tool-level breaking changes)?

**Pull request merged**
