### PR TITLE
Pass var usage in inputs.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3532)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 12 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3532)* status: 12 of 22 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/implicits/mod.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3532#-NZ-gy0OCbBBR_0H3XiB:-NZ-gy0OCbBBR_0H3XiC:bm6ncgp) ([raw file](https://github.com/starkware-libs/cairo/blob/f7b8a040a6d0b774ec1bd7674537c8a1fb8d141f/crates/cairo-lang-lowering/src/implicits/mod.rs#L114)):*
> ```XML
>             let callee_implicits = ctx.db.function_implicits(stmt.function)?;
> 
>             // TODO(ilya): Add metadata.
> ```

what metadata?



_Code quote:_
```XML
// TODO(ilya): Add metadata.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/implicits/mod.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3532#-NZ-gy0OCbBBR_0H3XiB:-NZ-hX6R0wxnXDRDfIDG:b-amxf4g) ([raw file](https://github.com/starkware-libs/cairo/blob/f7b8a040a6d0b774ec1bd7674537c8a1fb8d141f/crates/cairo-lang-lowering/src/implicits/mod.rs#L114)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

what metadata?
</blockquote></details>

I'm going to replace it with 



_Code snippet:_
```XML
 let location = stmt.location.with_auto_generation_note(ctx.db, "implicts");
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3532)* status: 10 of 24 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/implicits/mod.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3532#-NZ-gy0OCbBBR_0H3XiB:-NZ-hwwU3ZWMthoI2D7G:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/f7b8a040a6d0b774ec1bd7674537c8a1fb8d141f/crates/cairo-lang-lowering/src/implicits/mod.rs#L114)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I'm going to replace it with 
</blockquote></details>

done

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3532)* status: 12 of 24 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/ids.rs` line 355 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3532#-NZ-iySQ1SnkemzX_Pml:-NZ-iySQ1SnkemzX_Pmm:b2wqon9) ([raw file](https://github.com/starkware-libs/cairo/blob/a9c1e5df95d70877d66612d595af106868d98e87/crates/cairo-lang-lowering/src/ids.rs#L355)):*
> ```XML
>         &self,
>         db: &dyn LoweringGroup,
>         logic_name: &str,
> ```

is this related?



_Code quote:_
```XML
   logic_name: &str,
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/ids.rs` line 355 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3532#-NZ-iySQ1SnkemzX_Pml:-NZ-jJb33iXa5Km7hMyT:b-xqpbkx) ([raw file](https://github.com/starkware-libs/cairo/blob/a9c1e5df95d70877d66612d595af106868d98e87/crates/cairo-lang-lowering/src/ids.rs#L355)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is this related?
</blockquote></details>

I noticed that it is more convient to pass a &str here
do you want me to do it as a separate PR?

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 10 of 22 files at r1, 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3532)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/implicits/mod.rs` line 162 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3532#-NZ-kAkL5CVhheBeS6yY:-NZ-kAkL5CVhheBeS6yZ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a9c1e5df95d70877d66612d595af106868d98e87/crates/cairo-lang-lowering/src/implicits/mod.rs#L162)):*
> ```XML
>             MatchInfo::Extern(stmt) => {
>                 let callee_implicits = ctx.db.function_implicits(stmt.function)?;
>                 let location = stmt.location.with_auto_generation_note(ctx.db, "implicit");
> ```





_Suggestion:_
```XML
                let callee_implicits = ctx.db.function_implicits(stmt.function)?;
                let location = stmt.location.with_auto_generation_note(ctx.db, "implicits");
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3532)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/implicits/mod.rs` line 162 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3532#-NZ-kAkL5CVhheBeS6yY:-NZ-kbvI4-fi4ioCMiEe:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a9c1e5df95d70877d66612d595af106868d98e87/crates/cairo-lang-lowering/src/implicits/mod.rs#L162)):*
> ```XML
>             MatchInfo::Extern(stmt) => {
>                 let callee_implicits = ctx.db.function_implicits(stmt.function)?;
>                 let location = stmt.location.with_auto_generation_note(ctx.db, "implicit");
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3532#-:-NZ-m3d6179yaUZabZIc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/ids.rs` line 355 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3532#-NZ-iySQ1SnkemzX_Pml:-NZ-lwY38_wkmzBkonC4:bxyhs86) ([raw file](https://github.com/starkware-libs/cairo/blob/a9c1e5df95d70877d66612d595af106868d98e87/crates/cairo-lang-lowering/src/ids.rs#L355)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I noticed that it is more convient to pass a &str here
do you want me to do it as a separate PR?


</blockquote></details>

no - seen the changes later and deleted the comment.

**Pull request merged**
