### PR TITLE
Defined EcPoint type and implemented creation libfunc

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
Signed-off-by: Dori Medini <dori@starkware.co>

commit-id:69d212b4

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1518)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 10 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1518)* status: 10 of 12 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`corelib/lib.cairo` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1518#-NKJKpj54N1iDJzG4dsV:-NKJKpj54N1iDJzG4dsW:b-hldgqz) ([raw file](https://github.com/starkware-libs/cairo/blob/187715f014cc33e40cb96eb2a8a82d65faa4ecee/corelib/lib.cairo#L56)):*
> ```Cairo
> 
> // EC.
> extern type EcPoint;
> ```

put all under mod ec.



_Code quote:_
```Cairo
// EC.
extern type EcPoint;
extern fn create_ec_point(x: felt, y: felt) -> Result::<EcPoint, ()> nopanic;
```
___
*[`corelib/lib.cairo` line 57 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1518#-NKJLLepARsJxZpC23ij:-NKJLLepARsJxZpC23ik:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/187715f014cc33e40cb96eb2a8a82d65faa4ecee/corelib/lib.cairo#L57)):*
> ```Cairo
> // EC.
> extern type EcPoint;
> extern fn create_ec_point(x: felt, y: felt) -> Result::<EcPoint, ()> nopanic;
> ```





_Suggestion:_
```Cairo
#[panic_with('ec: Not a valid point', ec_point_from_felts)]
extern fn ec_point_try_from_felts(x: felt, y: felt) -> Option::<EcPoint> nopanic;
```
___
*[`corelib/test.cairo` line 39 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1518#-NKJL6LPBW2LcitrVRHJ:-NKJL6LPBW2LcitrVRHK:b-gv6gh7) ([raw file](https://github.com/starkware-libs/cairo/blob/187715f014cc33e40cb96eb2a8a82d65faa4ecee/corelib/test.cairo#L39)):*
> ```Cairo
>     let beta_plus_2 = 3141592653589793238462643383279502884197169399375105820974944592307816406667;
>     let beta_p2_root = 2487829544412206244690656897973144572467842667075005257202960243805141046681;
>     match create_ec_point(1, beta_p2_root) {
> ```

should work.



_Suggestion:_
```Cairo
    // Beta + 2 is a square, and for x = 1 and alpha = 1, x^3 + alpha * x + beta = beta + 2.
    let beta_plus_2 = 3141592653589793238462643383279502884197169399375105820974944592307816406667;
    let beta_p2_root = 2487829544412206244690656897973144572467842667075005257202960243805141046681;
    match create_ec_point(1, beta_p2_root) {
        Result::Ok(_) => {},
        Result::Err(_) => panic(array_new::<felt>()),
    };
```
___
*[`corelib/test.cairo` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1518#-NKJMCoa58T9qmpQ0XJc:-NKJMCoa58T9qmpQ0XJd:b-8s5wgt) ([raw file](https://github.com/starkware-libs/cairo/blob/187715f014cc33e40cb96eb2a8a82d65faa4ecee/corelib/test.cairo#L42)):*
> ```Cairo
>         Result::Ok(_) => 0,
>         Result::Err(_) => panic(array_new::<felt>()),
>     };
> ```

after the panicable change:



_Suggestion:_
```Cairo
#[test]
fn test_ec_operations() {
    // Beta + 2 is a square, and for x = 1 and alpha = 1, x^3 + alpha * x + beta = beta + 2.
    let beta_plus_2 = 3141592653589793238462643383279502884197169399375105820974944592307816406667;
    let beta_p2_root = 2487829544412206244690656897973144572467842667075005257202960243805141046681;
    ec_point_from_felts(1, beta_p2_root);
}
```
___
*[`corelib/test.cairo` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1518#-NKJMNS41P0GGDEExW_i:-NKJMNS41P0GGDEExW_j:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/187715f014cc33e40cb96eb2a8a82d65faa4ecee/corelib/test.cairo#L46)):*
> ```Cairo
> 
> #[test]
> #[should_panic]
> ```





_Suggestion:_
```Cairo
#[test]
#[should_panic]
fn test_bad_ec_point_creation() {
    ec_point_from_felts(0, 0);
}
```
___
*[`crates/sierra/src/extensions/modules/ec.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1518#-NKJMTfy7hFNs-xToGQi:-NKJMTfy7hFNs-xToGQj:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/187715f014cc33e40cb96eb2a8a82d65faa4ecee/crates/sierra/src/extensions/modules/ec.rs#L14)):*
> ```XML
> 
> #[derive(Default)]
> pub struct EcOpType {}
> ```

doc



_Code quote:_
```XML
EcOpType
```
___
*[`crates/sierra_to_casm/src/invocations/ec.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1518#-NKJO5K0DULGePTwSrc7:-NKJO5K0DULGePTwSrc8:b-aavybs) ([raw file](https://github.com/starkware-libs/cairo/blob/187715f014cc33e40cb96eb2a8a82d65faa4ecee/crates/sierra_to_casm/src/invocations/ec.rs#L45)):*
> ```XML
>     let y = casm_builder.add_var(ResOperand::Deref(y));
> 
>     // As an optimization we assume the alpha value of the curve is 1. Assert this is the case.
> ```

you define it here - this does not actually make sense;
just add a comment stating that ALPHA is 1.

and remove the `get alpha` definitions all around.



_Code quote:_
```XML
    // As an optimization we assume the alpha value of the curve is 1. Assert this is the case.
    assert!(get_alpha() == BigInt::from(1), "Alpha must be 1.");
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1518)* status: 10 of 12 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware and @orizi)

___
*[`corelib/lib.cairo` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1518#-NKJKpj54N1iDJzG4dsV:-NKJR5El6MwzNPTlSWoY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/187715f014cc33e40cb96eb2a8a82d65faa4ecee/corelib/lib.cairo#L56)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

put all under mod ec.
</blockquote></details>

Done.



_Code quote:_
```Cairo
extern type EcPoint;
```
___
*[`corelib/lib.cairo` line 57 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1518#-NKJLLepARsJxZpC23ij:-NKJRSOI8PK3umhKhgvB:b-rul59x) ([raw file](https://github.com/starkware-libs/cairo/blob/187715f014cc33e40cb96eb2a8a82d65faa4ecee/corelib/lib.cairo#L57)):*
> ```Cairo
> // EC.
> extern type EcPoint;
> extern fn create_ec_point(x: felt, y: felt) -> Result::<EcPoint, ()> nopanic;
> ```

Done.
`'ec: Not a valid point'` is over 15 chars, changed to `'not on EC'`
___
*[`corelib/test.cairo` line 39 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1518#-NKJL6LPBW2LcitrVRHJ:-NKJRZ1m2MhzhHBMZ8Dj:b-fierkv) ([raw file](https://github.com/starkware-libs/cairo/blob/187715f014cc33e40cb96eb2a8a82d65faa4ecee/corelib/test.cairo#L39)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

should work.
</blockquote></details>

Irrelevant now
___
*[`corelib/test.cairo` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1518#-NKJMCoa58T9qmpQ0XJc:-NKJRY_K-W5Xcqek12me:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/187715f014cc33e40cb96eb2a8a82d65faa4ecee/corelib/test.cairo#L42)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

after the panicable change:
</blockquote></details>

Done.
___
*[`corelib/test.cairo` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1518#-NKJMNS41P0GGDEExW_i:-NKJRdGJCaKjEAEgcXK8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/187715f014cc33e40cb96eb2a8a82d65faa4ecee/corelib/test.cairo#L46)):*
> ```Cairo
> 
> #[test]
> #[should_panic]
> ```

Done.
___
*[`crates/sierra/src/extensions/modules/ec.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1518#-NKJMTfy7hFNs-xToGQi:-NKJQNUP8ghTJcb--sQz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/187715f014cc33e40cb96eb2a8a82d65faa4ecee/crates/sierra/src/extensions/modules/ec.rs#L14)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/sierra_to_casm/src/invocations/ec.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1518#-NKJO5K0DULGePTwSrc7:-NKJQigW972QETRS4YA3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/187715f014cc33e40cb96eb2a8a82d65faa4ecee/crates/sierra_to_casm/src/invocations/ec.rs#L45)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you define it here - this does not actually make sense;
just add a comment stating that ALPHA is 1.

and remove the `get alpha` definitions all around.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1518)* status: 9 of 13 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/sierra/src/extensions/modules/ec.rs` line 56 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1518#-NKJko8P468lxloe4HrB:-NKJko8P468lxloe4HrC:b8f26yp) ([raw file](https://github.com/starkware-libs/cairo/blob/c5897a83f252a9cf6ac27b31efd7507669f34139/crates/sierra/src/extensions/modules/ec.rs#L56)):*
> ```XML
>                 ParamSignature::new(felt_ty.clone()),
>                 ParamSignature::new(felt_ty),
>             ],
> ```

you allocate vars here - so this changes the stack not only with new vars.



_Suggestion:_
```XML
    ) -> Result<LibFuncSignature, SpecializationError> {
        let felt_ty = context.get_concrete_type(FeltType::id(), &[])?;
        Ok(LibFuncSignature {
            param_signatures: vec![
                ParamSignature::new(felt_ty.clone()),
                ParamSignature::new(felt_ty),
            ],
            branch_signatures: vec![
                BranchSignature {
                    vars: vec![OutputVarInfo {
                        ty: context.get_concrete_type(EcPointType::id(), &[])?,
                        ref_info: OutputVarReferenceInfo::Deferred(DeferredOutputKind::Generic),
                    }],
                    ap_change: SierraApChange::Known { new_vars_only: false },
                },
                BranchSignature {
                    vars: vec![],
                    ap_change: SierraApChange::Known { new_vars_only: false },
                },
            ],
            fallthrough: Some(0),
        })
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 12 files at r1, 3 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1518)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1518)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/sierra/src/extensions/modules/ec.rs` line 56 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1518#-NKJko8P468lxloe4HrB:-NKMqzlw4Z6x0smeM8SD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c5897a83f252a9cf6ac27b31efd7507669f34139/crates/sierra/src/extensions/modules/ec.rs#L56)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you allocate vars here - so this changes the stack not only with new vars.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1518#-:-NKMxVGX6tBL9hR5NFh2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
