### PR TITLE
Orizi/dict felt252 for bool and non copy nullable

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4340)

### CODE REVIEW

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 10 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4340)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @liorgold2, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4340#-NiE-7mk55FPdunvhve7:-NiE-7mk55FPdunvhve8:b-82yqra) ([raw file](https://github.com/starkware-libs/cairo/blob/93f7da57ac96e501ccf9d260d567ab29405aeeed/crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs#L76)):*
> ```XML
>                     info.zero_sized
>                 })
>         }
> ```

Add doc. It's not that clear why the first arg is skipped and why at most 3 args.



_Code quote:_
```XML
        id if id == EnumType::id() => {
            generic_args.len() <= 3
                && generic_args.into_iter().skip(1).all(|arg| {
                    let GenericArg::Type(ty) = arg else {
                        return false;
                    };
                    let Ok(info) = context.get_type_info(ty) else {
                        return false;
                    };
                    info.zero_sized
                })
        }
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4340)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @liorgold2, and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4340#-NiE-7mk55FPdunvhve7:-NiEUl46BLGX04kar1xq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/93f7da57ac96e501ccf9d260d567ab29405aeeed/crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs#L76)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Add doc. It's not that clear why the first arg is skipped and why at most 3 args.
</blockquote></details>

Done.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 9 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4340)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs` line 67 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4340#-NiYzxmu03yqRDi6eBh9:-NiYzxmu03yqRDi6eBhA:b-5qhjle) ([raw file](https://github.com/starkware-libs/cairo/blob/b26017f7b70df4dfd6d5eedca6a073d46afb3e14/crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs#L67)):*
> ```XML
>         id if id == EnumType::id() => {
>             // Enums with 2 or less variant has variant indicator 0 as a valid indicator.
>             // (the additional arg is the user type).
> ```

```
// Zero is not a valid value for enums with 3 or more variants, so they cannot be used in a dict (whose default value is zero).
```



_Code quote:_
```XML
            // Enums with 2 or less variant has variant indicator 0 as a valid indicator.
            // (the additional arg is the user type).
```

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4340)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4340#-NiZ-P6Q6SqTsUp4AyW2:-NiZ-P6Q6SqTsUp4AyW3:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/b26017f7b70df4dfd6d5eedca6a073d46afb3e14/crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs#L69)):*
> ```XML
>             // (the additional arg is the user type).
>             generic_args.len() <= 3
>                 // All contained types must be 0 size so the size would only be 1.
> ```

.



_Suggestion:_
```XML
               // All contained types must be 0-sized, so the total size will be exactly 1.
```

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4340)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs` line 68 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4340#-NiZ-ZqF1zqaB4dmCpm6:-NiZ-ZqF1zqaB4dmCpm7:b-18x6ru) ([raw file](https://github.com/starkware-libs/cairo/blob/b26017f7b70df4dfd6d5eedca6a073d46afb3e14/crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs#L68)):*
> ```XML
>             // Enums with 2 or less variant has variant indicator 0 as a valid indicator.
>             // (the additional arg is the user type).
>             generic_args.len() <= 3
> ```

Check len >= 1.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4340)* status: 9 of 11 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4340#-NiZ1b8I6PlvadwYB6tM:-NiZ1b8I6PlvadwYB6tN:bkcpyr8) ([raw file](https://github.com/starkware-libs/cairo/blob/b26017f7b70df4dfd6d5eedca6a073d46afb3e14/crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs#L42)):*
> ```XML
> }
> 
> fn specialize_with_dict_value_param(
> ```

Document and mention where it used.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4340)* status: 9 of 11 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware, @liorgold2, and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs` line 67 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4340#-NiYzxmu03yqRDi6eBh9:-NiZ-Pwq6rIa_pRbtwtB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b26017f7b70df4dfd6d5eedca6a073d46afb3e14/crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs#L67)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

```
// Zero is not a valid value for enums with 3 or more variants, so they cannot be used in a dict (whose default value is zero).
```
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs` line 68 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4340#-NiZ-ZqF1zqaB4dmCpm6:-NiZ10N2B76yWAmf1PcP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b26017f7b70df4dfd6d5eedca6a073d46afb3e14/crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs#L68)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Check len >= 1.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4340#-NiZ-P6Q6SqTsUp4AyW2:-NiZ1158DQ8-ilJ0nKZR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b26017f7b70df4dfd6d5eedca6a073d46afb3e14/crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs#L69)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4340)* status: 9 of 11 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware, @liorgold2, and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4340#-NiZ1b8I6PlvadwYB6tM:-NiZ1mQrAOa-zC9V9ash:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b26017f7b70df4dfd6d5eedca6a073d46afb3e14/crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs#L42)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Document and mention where it used.
</blockquote></details>

Done.

**Pull request merged**
