### PR TITLE
Restructure VariableLifetimeResult::drops so that it can be used to a…

### PR DESCRIPTION
**Pull request by liorgold2**
…dd the drop statements.

commit-id:d1c17414

---

**Stack**:
- #1563
- #1562
- #1561
- #1556
- #1555
- #1554
- #1553
- #1552 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1552#-:-NKPyEOM4EQQy2Wv0hNx:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-sierra-generator/src/lifetime.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1552#-NKPy1-_9204Wes7rwsm:-NKPy1-_9204Wes7rwsn:bljob9k) ([raw file](https://github.com/starkware-libs/cairo/blob/fbebb8b2fa3f9f5c0ef9f996f223a06ed1e65798/crates/cairo-sierra-generator/src/lifetime.rs#L33)):*
> ```XML
>     last_use: OrderedHashMap<VariableId, Vec<StatementLocation>>,
>     /// A map from [VariableId] to the statements where it should be dropped.
>     drops: OrderedHashMap<DropLocation, Vec<VariableId>>,
> ```

fix doc



_Code quote:_
```XML
/// A map from [VariableId] to the statements where it should be dropped.
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1552)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-sierra-generator/src/lifetime.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1552#-NKPy1-_9204Wes7rwsm:-NKRmnCM7uzN8Hn4Mvw4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fbebb8b2fa3f9f5c0ef9f996f223a06ed1e65798/crates/cairo-sierra-generator/src/lifetime.rs#L33)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix doc
</blockquote></details>

Done.

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1552)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1552)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by liorgold2 — COMMENTED** [review]
> Dismissed @orizi from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1552)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
