### PR TITLE
Orizi/sierra update validation

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4383)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4383#-NioZcff4OyEk1nlG-LD:-NioZcff4OyEk1nlG-LE:b-eurkta) ([raw file](https://github.com/starkware-libs/cairo/blob/4a30efd6db8e35077e31257142ef6de6258dab7e/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L30)):*
> ```XML
>     /// Add pythonic hints.
>     #[arg(long, default_value_t = false)]
>     add_pythonic_hints: bool,
> ```

What does this do?



_Code quote:_
```XML
    #[arg(long, default_value_t = false)]
    add_pythonic_hints: bool,
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4383#-NioZx2l9uuwr5-VigKy:-NioZx2l9uuwr5-VigKz:bocvbkz) ([raw file](https://github.com/starkware-libs/cairo/blob/4a30efd6db8e35077e31257142ef6de6258dab7e/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L103)):*
> ```XML
>             CasmContractClass::from_contract_class(contract_class, args.add_pythonic_hints)
>         else {
>             report.lock().unwrap().compilation_failures.push(sierra_class.compiled_class_hash);
> ```

maybe you should push the sierra_class_hash?



_Code quote:_
```XML
sierra_class.compiled_class_hash
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4383)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4383#-NioZcff4OyEk1nlG-LD:-NipLKBS8snE_1d-tUrg:bkq8kyo) ([raw file](https://github.com/starkware-libs/cairo/blob/4a30efd6db8e35077e31257142ef6de6258dab7e/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L30)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

What does this do?
</blockquote></details>

removing for now - as probably not interesting.
___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4383#-NioZx2l9uuwr5-VigKy:-NipLIy76OL606R1BDin:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4a30efd6db8e35077e31257142ef6de6258dab7e/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L103)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

maybe you should push the sierra_class_hash?
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4383#-:-Nj2mgCSCkgMUwsNj9_9:bnfp4nl)* status: 5 of 6 files reviewed, all discussions resolved

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4383)* status: 5 of 6 files reviewed, all discussions resolved

**Pull request merged**
