### PR TITLE
Renamed refund_gas -> redeposit_gas

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2499)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 9 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2499)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/allowed_libfuncs_lists/experimental_v0.1.0.json` line 68 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2499#-NQ_wXEcELw9SES_7SDt:-NQ_wXEcELw9SES_7SDu:bb7onj7) ([raw file](https://github.com/starkware-libs/cairo/blob/3bbac16b805078b5deaae86dc5bab7af5777e1a2/crates/cairo-lang-starknet/src/allowed_libfuncs_lists/experimental_v0.1.0.json#L68)):*
> ```JSON
>         "nullable_from_box",
>         "pedersen",
>         "redeposit_gas",
> ```

sort



_Code quote:_
```JSON
        "nullable_from_box",
        "pedersen",
        "redeposit_gas",
        "rename",
```
___
*[`crates/cairo-lang-starknet/src/allowed_libfuncs_lists/testnet_v0.1.0.json` line 57 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2499#-NQ_wYWLAJI9jfl3KeSN:-NQ_wYWLAJI9jfl3KeSO:bb7onj7) ([raw file](https://github.com/starkware-libs/cairo/blob/3bbac16b805078b5deaae86dc5bab7af5777e1a2/crates/cairo-lang-starknet/src/allowed_libfuncs_lists/testnet_v0.1.0.json#L57)):*
> ```JSON
>                 "nullable_from_box",
>                 "pedersen",
>                 "redeposit_gas",
> ```

sort



_Code quote:_
```JSON
                "null",
                "nullable_from_box",
                "pedersen",
                "redeposit_gas",
                "rename",
```

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2499)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2499)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/allowed_libfuncs_lists/experimental_v0.1.0.json` line 68 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2499#-NQ_wXEcELw9SES_7SDt:-NQdaWEjDeDIgGpQj-re:b-jmrnkn) ([raw file](https://github.com/starkware-libs/cairo/blob/3bbac16b805078b5deaae86dc5bab7af5777e1a2/crates/cairo-lang-starknet/src/allowed_libfuncs_lists/experimental_v0.1.0.json#L68)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

sort
</blockquote></details>

It's already sorted
___
*[`crates/cairo-lang-starknet/src/allowed_libfuncs_lists/testnet_v0.1.0.json` line 57 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2499#-NQ_wYWLAJI9jfl3KeSN:-NQdaYwW99qDDY2mIVn-:b-jmrnkn) ([raw file](https://github.com/starkware-libs/cairo/blob/3bbac16b805078b5deaae86dc5bab7af5777e1a2/crates/cairo-lang-starknet/src/allowed_libfuncs_lists/testnet_v0.1.0.json#L57)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

sort
</blockquote></details>

It's already sorted

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2499)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
