### PR TITLE
Changed gas optimization order.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #2596
- #2594
- #2586
- #2580
- #2579
- #2577
- #2574
- #2573 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2573)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2573)* status: 4 of 8 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 140 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2573#-NRRW_hy9ngLvgY0VFt6:-NRRW_hz8WfmPk16yOau:b-507mkl) ([raw file](https://github.com/starkware-libs/cairo/blob/aab5438b87604ff6cc6b041ef0cd3b0ee39ccc2c/crates/cairo-lang-sierra-gas/src/lib.rs#L140)):*
> ```XML
>         .funcs
>         .iter()
>         .filter(|f| function_set_costs.contains_key(&f.id))
> ```

why are those the `non_set_cost_func_ids`? also those are entry points, not ids, right?



_Code quote:_
```XML
 .filter(|f| function_set_costs.contains_key(&f.id))
```
___
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 157 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2573#-NRRaKklBFR0GBAcDOO8:-NRRaKkm2PaO2joC5KlM:bde261a) ([raw file](https://github.com/starkware-libs/cairo/blob/aab5438b87604ff6cc6b041ef0cd3b0ee39ccc2c/crates/cairo-lang-sierra-gas/src/lib.rs#L157)):*
> ```XML
>     let mut function_costs = OrderedHashMap::default();
>     for (token_type, token_equations) in equations {
>         let mut minimization_vars = vec![vec![], vec![]];
> ```

can you document?



_Code quote:_
```XML
let mut minimization_vars = vec![vec![], vec![]];
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2573)* status: 4 of 8 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 140 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2573#-NRRW_hy9ngLvgY0VFt6:-NRRmjgsCVrN3Z_tK69u:bdq0wlr) ([raw file](https://github.com/starkware-libs/cairo/blob/aab5438b87604ff6cc6b041ef0cd3b0ee39ccc2c/crates/cairo-lang-sierra-gas/src/lib.rs#L140)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why are those the `non_set_cost_func_ids`? also those are entry points, not ids, right?
</blockquote></details>

these are ids - of functions that do not have set costs (so in this case, non-entry points)
___
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 157 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2573#-NRRaKklBFR0GBAcDOO8:-NRRnsNA1G4BAgnsTkAZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/aab5438b87604ff6cc6b041ef0cd3b0ee39ccc2c/crates/cairo-lang-sierra-gas/src/lib.rs#L157)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

can you document?
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 140 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2573#-NRRW_hy9ngLvgY0VFt6:-NRRol5l0XIKByivgA82:bpq53kv) ([raw file](https://github.com/starkware-libs/cairo/blob/aab5438b87604ff6cc6b041ef0cd3b0ee39ccc2c/crates/cairo-lang-sierra-gas/src/lib.rs#L140)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

these are ids - of functions that do not have set costs (so in this case, non-entry points)
</blockquote></details>

Does 'function_set_costs' have functions with set or non_set costs?

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2573)* status: 4 of 8 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 157 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2573#-NRRaKklBFR0GBAcDOO8:-NRRp0sh4CDNt3xnRmhF:b-f9qwcb) ([raw file](https://github.com/starkware-libs/cairo/blob/aab5438b87604ff6cc6b041ef0cd3b0ee39ccc2c/crates/cairo-lang-sierra-gas/src/lib.rs#L157)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Why do 'Function costs' have "actual cost to the user"?
All the entry points have a fixed cost, right?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2573)* status: 4 of 8 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 140 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2573#-NRRW_hy9ngLvgY0VFt6:-NRRqGOT6Fh0URv6u9Ux:bq98vyx) ([raw file](https://github.com/starkware-libs/cairo/blob/aab5438b87604ff6cc6b041ef0cd3b0ee39ccc2c/crates/cairo-lang-sierra-gas/src/lib.rs#L140)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Does 'function_set_costs' have functions with set or non_set costs?
</blockquote></details>

oh yeah - got confused there - good catch, fixing.
___
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 157 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2573#-NRRaKklBFR0GBAcDOO8:-NRRqSTgBhP3piSzXVT4:beq4w69) ([raw file](https://github.com/starkware-libs/cairo/blob/aab5438b87604ff6cc6b041ef0cd3b0ee39ccc2c/crates/cairo-lang-sierra-gas/src/lib.rs#L157)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why do 'Function costs' have "actual cost to the user"?
All the entry points have a fixed cost, right?
</blockquote></details>

bad optimization has actual costs to the user - updating.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 2 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2573)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2573)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 140 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2573#-NRRW_hy9ngLvgY0VFt6:-NRSIeinDRNC64aNQ4NJ:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/aab5438b87604ff6cc6b041ef0cd3b0ee39ccc2c/crates/cairo-lang-sierra-gas/src/lib.rs#L140)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

oh yeah - got confused there - good catch, fixing.
</blockquote></details>

Done
___
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 157 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2573#-NRRaKklBFR0GBAcDOO8:-NRSIg5tEtHjZUTV8SPV:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/aab5438b87604ff6cc6b041ef0cd3b0ee39ccc2c/crates/cairo-lang-sierra-gas/src/lib.rs#L157)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

bad optimization has actual costs to the user - updating.
</blockquote></details>

Done

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 185 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2573#-NRSL_6P5H3Nr7opkNDm:-NRSL_6P5H3Nr7opkNDn:bemq58e) ([raw file](https://github.com/starkware-libs/cairo/blob/f3ec806422787a9cc87d155233c8700d4ce62f15/crates/cairo-lang-sierra-gas/src/lib.rs#L185)):*
> ```XML
>                     }
>                 }
>                 Var::StatementFuture(idx, _) if non_set_cost_func_entry_points.contains(idx) => 0,
> ```

What happens if you don't minimize that?
I think minimizing WithdrawGas should have priority over minimizing function gas.



_Code quote:_
```XML
    Var::StatementFuture(idx, _) if non_set_cost_func_entry_points.contains(idx) => 0,
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2573)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 185 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2573#-NRSL_6P5H3Nr7opkNDm:-NRSMRFzEj9dRofzOA2T:bup9iyu) ([raw file](https://github.com/starkware-libs/cairo/blob/f3ec806422787a9cc87d155233c8700d4ce62f15/crates/cairo-lang-sierra-gas/src/lib.rs#L185)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

What happens if you don't minimize that?
I think minimizing WithdrawGas should have priority over minimizing function gas.
</blockquote></details>

it will be enough if all functions are recursive - or at least getting called after some `get gas` call - but if not - it won't actually be minimized, and adding code in another place may change it's meaning.
minimizing on both for this case should be fine.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 185 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2573#-NRSL_6P5H3Nr7opkNDm:-NRSNdOC1Cu8W62iisMN:beimr2n) ([raw file](https://github.com/starkware-libs/cairo/blob/f3ec806422787a9cc87d155233c8700d4ce62f15/crates/cairo-lang-sierra-gas/src/lib.rs#L185)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it will be enough if all functions are recursive - or at least getting called after some `get gas` call - but if not - it won't actually be minimized, and adding code in another place may change it's meaning.
minimizing on both for this case should be fine.
</blockquote></details>

I disagree.
with this target the optimizer can pick either of the following options:
1. function costs 500 gas and withdraws 0.
2. function costs 10 gas and withdraws 490.

We want to prefer option 1.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2573)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 185 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2573#-NRSL_6P5H3Nr7opkNDm:-NRSUaWl5aodGuG4elSj:b-pqpp3h) ([raw file](https://github.com/starkware-libs/cairo/blob/f3ec806422787a9cc87d155233c8700d4ce62f15/crates/cairo-lang-sierra-gas/src/lib.rs#L185)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I disagree.
with this target the optimizer can pick either of the following options:
1. function costs 500 gas and withdraws 0.
2. function costs 10 gas and withdraws 490.

We want to prefer option 1.
</blockquote></details>

your example is impossible - note that withdraw is a branch - therefore - the failure branch would be the actual cost of the function - so we would prefer the second option.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 185 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2573#-NRSL_6P5H3Nr7opkNDm:-NRSY4-66eePZTVaJ0w8:b-835b1p) ([raw file](https://github.com/starkware-libs/cairo/blob/f3ec806422787a9cc87d155233c8700d4ce62f15/crates/cairo-lang-sierra-gas/src/lib.rs#L185)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

your example is impossible - note that withdraw is a branch - therefore - the failure branch would be the actual cost of the function - so we would prefer the second option.
</blockquote></details>

in my example, the cost of the failure branch = function cost = 10, why is that impossible?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2573)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 185 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2573#-NRSL_6P5H3Nr7opkNDm:-NRSZWO54YBArJV1Zbtf:b2ytcvr) ([raw file](https://github.com/starkware-libs/cairo/blob/f3ec806422787a9cc87d155233c8700d4ce62f15/crates/cairo-lang-sierra-gas/src/lib.rs#L185)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

in my example, the cost of the failure branch = function cost = 10, why is that impossible?
</blockquote></details>

so you'd definitely still prefer option 2 - and option 1 is still not valid - as it takes 500.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2573)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 185 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2573#-NRSL_6P5H3Nr7opkNDm:-NRSZrxA3Yqoj6i8XdJ8:bcbdiuc) ([raw file](https://github.com/starkware-libs/cairo/blob/f3ec806422787a9cc87d155233c8700d4ce62f15/crates/cairo-lang-sierra-gas/src/lib.rs#L185)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

so you'd definitely still prefer option 2 - and option 1 is still not valid - as it takes 500. 
</blockquote></details>

why is it invalid?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2573)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 185 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2573#-NRSL_6P5H3Nr7opkNDm:-NRS__yGD-Q6FWKe7NyM:brngwev) ([raw file](https://github.com/starkware-libs/cairo/blob/f3ec806422787a9cc87d155233c8700d4ce62f15/crates/cairo-lang-sierra-gas/src/lib.rs#L185)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why is it invalid?
</blockquote></details>

function cost can either be 10 or 500.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2573)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 159 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2573#-NRSmMkv2QnIj6L99Jr5:-NRSmMkv2QnIj6L99Jr6:b-x2rtlv) ([raw file](https://github.com/starkware-libs/cairo/blob/d91e68b8110c4774410edbf557fd1ea9f27c177d/crates/cairo-lang-sierra-gas/src/lib.rs#L159)):*
> ```XML
>         // Setting up minimization vars with two ranks.
>         // Function costs and withdraw variables are minimized first (since bad optimization will
>         // incur actual costs to the user), and then branch alignment variables.
> ```

Add:

Note that minimizing over all variables does not work
in the following example:

fn bar {
   burn_gas()
}


fn foo {
   bar();
   match {
      A => burn_gas()
      B => burn_gas()
      C => burn_gas()
   }
}

The solver will prefer to increase the price of burn in order to decrease
the solutions for the burn_gas() in foo.



_Suggestion:_
```XML
        // Setting up minimization vars with two ranks.
        // Function costs and withdraw variables are minimized first (since bad optimization will
        // incur actual costs to the user), and then branch alignment variables.
        
        
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2573)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 159 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2573#-NRSmMkv2QnIj6L99Jr5:-NRSuaT6COkAXmvRH4Ga:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d91e68b8110c4774410edbf557fd1ea9f27c177d/crates/cairo-lang-sierra-gas/src/lib.rs#L159)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Add:

Note that minimizing over all variables does not work
in the following example:

fn bar {
   burn_gas()
}


fn foo {
   bar();
   match {
      A => burn_gas()
      B => burn_gas()
      C => burn_gas()
   }
}

The solver will prefer to increase the price of burn in order to decrease
the solutions for the burn_gas() in foo.
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 167 at r6](https://reviewable.io/reviews/starkware-libs/cairo/2573#-NRSxSjZ3HeAiVSyh2nx:-NRSxSjZ3HeAiVSyh2ny:brmob4a) ([raw file](https://github.com/starkware-libs/cairo/blob/f0f1879ba1e39ead8be9a45bee57642cacaab349/crates/cairo-lang-sierra-gas/src/lib.rs#L167)):*
> ```XML
>         //   function's value would be reduced (since it may be called from another point as well).
>         //   Therefore we should optimize over function costs before optimizing over branch aligns.
>         // * In cases where we have a function with an unset cost - that call `withdraw_gas` we can
> ```

doesn’t that mean you consume more gas in the case of recursion?



_Code quote:_
```XML
        // * In cases where we have a function with an unset cost - that call `withdraw_gas` we can
        //   decide to make the function pricier to reduce the amount of withdrawn gas. Therefore we
        //   should optimize over function costs before optimizing over withdraw variables.
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2573)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 167 at r6](https://reviewable.io/reviews/starkware-libs/cairo/2573#-NRSxSjZ3HeAiVSyh2nx:-NRSykYx8iUU-JBN2ug3:b3tf4xv) ([raw file](https://github.com/starkware-libs/cairo/blob/f0f1879ba1e39ead8be9a45bee57642cacaab349/crates/cairo-lang-sierra-gas/src/lib.rs#L167)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

doesn’t that mean you consume more gas in the case of recursion?
</blockquote></details>

in case of recursion you don't have any degree of freedom - this is the case where you do - the function isn't recursive.

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2573)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
