### PR TITLE
LS: asynchronous project update

### PR DESCRIPTION
**Pull request by piotmag769**

### CODE REVIEW

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6749)* status: all files reviewed, 6 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/project/mod.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6749#-OCgINMO7lDncuGRGbs1:-OCgINMO7lDncuGRGbs2:b-xgddxh) ([raw file](https://github.com/starkware-libs/cairo/blob/1b2c53cc6b6455b1151bf5951396134c0e1c9c35/crates/cairo-lang-language-server/src/project/mod.rs#L38)):*
> ```XML
>     }
> 
>     pub fn init_channels_and_spawn_thread(
> ```

it looks to me like you can now merge these two functions into just a variant of `new` that spawns threads, just like DiagnosticsController does. avoiding these `OnceCell` will be very good

it should be straightforward, I think, to save the receiver in `ProjectController` and somehow access it in the main event loop

note: and yes, :facepalm: I just realised that I wrote a `new` function that does spawning



_Code quote:_
```XML
    pub fn new() -> Self {
        ProjectController { requests_sender: Default::default(), thread: Default::default() }
    }

    pub fn init_channels_and_spawn_thread(
```
___
*[`crates/cairo-lang-language-server/src/project/mod.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6749#-OCgJV_FDEptd4DrttvR:-OCgHX5hBKw3yih5vETU:buo8b07) ([raw file](https://github.com/starkware-libs/cairo/blob/1b2c53cc6b6455b1151bf5951396134c0e1c9c35/crates/cairo-lang-language-server/src/project/mod.rs#L67)):*
> ```XML
>     }
> 
>     pub fn handle_update(state: &mut State, notifier: Notifier, project_update: ProjectUpdate) {
> ```

I know you're just moving stuff but can you please doc?
___
*[`crates/cairo-lang-language-server/src/project/mod.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6749#-OCgJbgr4ggqcTrnfGp7:-OCgJbgr4ggqcTrnfGp8:b-1l0q8x) ([raw file](https://github.com/starkware-libs/cairo/blob/1b2c53cc6b6455b1151bf5951396134c0e1c9c35/crates/cairo-lang-language-server/src/project/mod.rs#L67)):*
> ```XML
>     }
> 
>     pub fn handle_update(state: &mut State, notifier: Notifier, project_update: ProjectUpdate) {
> ```

also maybe add tracing instrument here?
___
*[`crates/cairo-lang-language-server/src/project/mod.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6749#-OCgJ95o20NLN9o5upAo:-OCgJ95o20NLN9o5upAp:bei9o1a) ([raw file](https://github.com/starkware-libs/cairo/blob/1b2c53cc6b6455b1151bf5951396134c0e1c9c35/crates/cairo-lang-language-server/src/project/mod.rs#L109)):*
> ```XML
>             .expect("requests sender should have been set")
>             .send(request)
>             // TODO maybe error?
> ```

yes I think this could be a log error
___
*[`crates/cairo-lang-language-server/src/project/mod.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6749#-OCgJSL0ACWybHQFrWcN:-OCgI4bW0dULuhYyVVFy:buo8b07) ([raw file](https://github.com/starkware-libs/cairo/blob/1b2c53cc6b6455b1151bf5951396134c0e1c9c35/crates/cairo-lang-language-server/src/project/mod.rs#L114)):*
> ```XML
> }
> 
> pub enum ProjectUpdate {
> ```

I know you're just moving stuff but can you please doc?
___
*[`crates/cairo-lang-language-server/src/project/mod.rs` line 210 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6749#-OCgIF4z7dKwvrIZ3gUV:-OCgIF4z7dKwvrIZ3gUW:b-v5ag0w) ([raw file](https://github.com/starkware-libs/cairo/blob/1b2c53cc6b6455b1151bf5951396134c0e1c9c35/crates/cairo-lang-language-server/src/project/mod.rs#L210)):*
> ```XML
>         self.project_updates_sender
>             .send(project_update)
>             // TODO maybe error?
> ```

I think it's fine because it's programmers error to skip the init call

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6749)* status: all files reviewed, 6 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/src/project/mod.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6749#-OCgINMO7lDncuGRGbs1:-OCgLsq16FyfUZ2-Us7Z:b1g2rz4) ([raw file](https://github.com/starkware-libs/cairo/blob/1b2c53cc6b6455b1151bf5951396134c0e1c9c35/crates/cairo-lang-language-server/src/project/mod.rs#L38)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

it looks to me like you can now merge these two functions into just a variant of `new` that spawns threads, just like DiagnosticsController does. avoiding these `OnceCell` will be very good

it should be straightforward, I think, to save the receiver in `ProjectController` and somehow access it in the main event loop

note: and yes, :facepalm: I just realised that I wrote a `new` function that does spawning
</blockquote></details>

I wish I could, but then I would have to use `OnceCell` to `State` since it is where `ProjectController` is initialised (and I need the update receiver channel only in the main loop). Alternatively I could have a channel hanging somewhere in the state or intermediate structure like `ProjectControllerHandle` which is also quite bad. LMK what is the best approach in your opinion.

 I could do some weird tricks making sure it is all typesafe and pretty like transitioning between `PartiallyInitializedState` -> `State` and use type families and stuff, but I doubt that this is what we want xD

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6749)* status: all files reviewed, 6 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/project/mod.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6749#-OCgINMO7lDncuGRGbs1:-OCgNtuQE7Jp-xLL78bj:b-4448xk) ([raw file](https://github.com/starkware-libs/cairo/blob/1b2c53cc6b6455b1151bf5951396134c0e1c9c35/crates/cairo-lang-language-server/src/project/mod.rs#L38)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

I wish I could, but then I would have to use `OnceCell` to `State` since it is where `ProjectController` is initialised (and I need the update receiver channel only in the main loop). Alternatively I could have a channel hanging somewhere in the state or intermediate structure like `ProjectControllerHandle` which is also quite bad. LMK what is the best approach in your opinion.

 I could do some weird tricks making sure it is all typesafe and pretty like transitioning between `PartiallyInitializedState` -> `State` and use type families and stuff, but I doubt that this is what we want xD
</blockquote></details>

`Receiver: Clone` so you can easily store it in state and just expose a method that clones it (I actually think the same could be done in proc macros now)

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6749)* status: 4 of 5 files reviewed, 6 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/src/project/mod.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6749#-OCgJbgr4ggqcTrnfGp7:-OCgNMB89OnPMSc9aQHd:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1b2c53cc6b6455b1151bf5951396134c0e1c9c35/crates/cairo-lang-language-server/src/project/mod.rs#L67)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

also maybe add tracing instrument here?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/project/mod.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6749#-OCgJV_FDEptd4DrttvR:-OCgOAUI4GUa25raSpC8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1b2c53cc6b6455b1151bf5951396134c0e1c9c35/crates/cairo-lang-language-server/src/project/mod.rs#L67)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I know you're just moving stuff but can you please doc?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/project/mod.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6749#-OCgJ95o20NLN9o5upAo:-OCgSC-i18_Br52Knnup:b6zz3hq) ([raw file](https://github.com/starkware-libs/cairo/blob/1b2c53cc6b6455b1151bf5951396134c0e1c9c35/crates/cairo-lang-language-server/src/project/mod.rs#L109)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

yes I think this could be a log error
</blockquote></details>

Agree, but we should still `expect` here, no? If it happens we are doomed anyway since we won't be able to load any new project
___
*[`crates/cairo-lang-language-server/src/project/mod.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6749#-OCgJSL0ACWybHQFrWcN:-OCgUMHyBFl5BC2jojaq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1b2c53cc6b6455b1151bf5951396134c0e1c9c35/crates/cairo-lang-language-server/src/project/mod.rs#L114)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I know you're just moving stuff but can you please doc?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/project/mod.rs` line 210 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6749#-OCgIF4z7dKwvrIZ3gUV:-OCgS3xvAz2NncD_zoGc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1b2c53cc6b6455b1151bf5951396134c0e1c9c35/crates/cairo-lang-language-server/src/project/mod.rs#L210)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I think it's fine because it's programmers error to skip the init call
</blockquote></details>

Done.

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6749)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/project/mod.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6749#-OCgJ95o20NLN9o5upAo:-OCgmSUV1LdoSbSLlE5f:b-9e4jrc) ([raw file](https://github.com/starkware-libs/cairo/blob/1b2c53cc6b6455b1151bf5951396134c0e1c9c35/crates/cairo-lang-language-server/src/project/mod.rs#L109)):*
> since we won't be able to load any new project

I know

> but we should still `expect` here, no?

that's the part I'm not 100% sure. it kinda makes sense because this should eventually cause LS to crash, but I wonder if we could just restart this thread or smth internally

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6749)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/src/project/mod.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6749#-OCgINMO7lDncuGRGbs1:-OChBJK_7u75Fujl8bP8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1b2c53cc6b6455b1151bf5951396134c0e1c9c35/crates/cairo-lang-language-server/src/project/mod.rs#L38)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

`Receiver: Clone` so you can easily store it in state and just expose a method that clones it (I actually think the same could be done in proc macros now)
</blockquote></details>

Done.

**Review by Draggu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6749)* status: 4 of 5 files reviewed, 7 unresolved discussions (waiting on @Arcticae, @integraledelebesgue, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/project/mod.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6749#-OCgJ95o20NLN9o5upAo:-OChUM6p757m7ODDKFEO:b392xk0) ([raw file](https://github.com/starkware-libs/cairo/blob/1b2c53cc6b6455b1151bf5951396134c0e1c9c35/crates/cairo-lang-language-server/src/project/mod.rs#L109)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

> since we won't be able to load any new project

I know

> but we should still `expect` here, no?

that's the part I'm not 100% sure. it kinda makes sense because this should eventually cause LS to crash, but I wonder if we could just restart this thread or smth internally
</blockquote></details>

Agree we should `error!` here, `expect` seems fine to me.
___
*[`crates/cairo-lang-language-server/src/project/mod.rs` line 58 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6749#-OChUopiBEG4_7fa8EMb:-OChUopiBEG4_7fa8EMc:b-otbrg5) ([raw file](https://github.com/starkware-libs/cairo/blob/9b62452f8180f6fd4107d6fed08cc4d8933a7630/crates/cairo-lang-language-server/src/project/mod.rs#L58)):*
> ```XML
>     }
> 
>     pub fn update_project_for_file(&self, file_path: PathBuf) {
> ```

This does not update project, only schedule this for later, rename please.
___
*[`crates/cairo-lang-language-server/src/project/mod.rs` line 62 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6749#-OChUbT16n9P79huSHed:-OChUbT27TutUtraZn1W:bc6rsfu) ([raw file](https://github.com/starkware-libs/cairo/blob/9b62452f8180f6fd4107d6fed08cc4d8933a7630/crates/cairo-lang-language-server/src/project/mod.rs#L62)):*
> ```XML
>     }
> 
>     pub fn clear_loaded_workspaces(&self) {
> ```

This does not clear workspaces, only schedule this for later, rename please.
___
*[`crates/cairo-lang-language-server/src/project/mod.rs` line 140 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6749#-OChU4bz-TEED5DlpJOz:-OChU4bz-TEED5DlpJP-:b-uhnjsa) ([raw file](https://github.com/starkware-libs/cairo/blob/9b62452f8180f6fd4107d6fed08cc4d8933a7630/crates/cairo-lang-language-server/src/project/mod.rs#L140)):*
> ```XML
>         scarb_toolchain: ScarbToolchain,
>     ) -> JoinHandle {
>         let mut this = Self {
> ```

Instead of `mut` we can consume it in the event loop, up to you.
___
*[`crates/cairo-lang-language-server/src/project/mod.rs` line 155 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6749#-OChTo4u-K27C5z6h0iA:-OChTo4v8gQcKqMdLGUX:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9b62452f8180f6fd4107d6fed08cc4d8933a7630/crates/cairo-lang-language-server/src/project/mod.rs#L155)):*
> ```XML
>     /// Runs project controller's event loop.
>     fn event_loop(&mut self) {
>         while let Ok(request) = self.requests_receiver.recv() {
> ```





_Suggestion:_
```XML
for request in self.requests_receiver
```
___
*[`crates/cairo-lang-language-server/src/project/mod.rs` line 173 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6749#-OChVQ2Q5H9L2dGjLu5y:-OChVQ2Q5H9L2dGjLu5z:btgpyzy) ([raw file](https://github.com/starkware-libs/cairo/blob/9b62452f8180f6fd4107d6fed08cc4d8933a7630/crates/cairo-lang-language-server/src/project/mod.rs#L173)):*
> ```XML
>     /// It is meant to be run only in the background thread.
>     #[tracing::instrument(skip_all)]
>     fn send_project_update_for_file(&mut self, file_path: &Path) {
> ```

We can make 2 methods of this, first calculating, second sending, up to you.

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6749)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/src/project/mod.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6749#-OCgJ95o20NLN9o5upAo:-OChi4AqDj544AXpKFHU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1b2c53cc6b6455b1151bf5951396134c0e1c9c35/crates/cairo-lang-language-server/src/project/mod.rs#L109)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

Agree we should `error!` here, `expect` seems fine to me.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/project/mod.rs` line 58 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6749#-OChUopiBEG4_7fa8EMb:-OChjHSR-BS51yH5-3xL:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9b62452f8180f6fd4107d6fed08cc4d8933a7630/crates/cairo-lang-language-server/src/project/mod.rs#L58)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

This does not update project, only schedule this for later, rename please.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/project/mod.rs` line 62 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6749#-OChUbT16n9P79huSHed:-OChjHeDEby2ATZrode7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9b62452f8180f6fd4107d6fed08cc4d8933a7630/crates/cairo-lang-language-server/src/project/mod.rs#L62)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

This does not clear workspaces, only schedule this for later, rename please.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/project/mod.rs` line 155 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6749#-OChTo4u-K27C5z6h0iA:-OChjSDUB7uXjJXaAFMP:b-pwxx0q) ([raw file](https://github.com/starkware-libs/cairo/blob/9b62452f8180f6fd4107d6fed08cc4d8933a7630/crates/cairo-lang-language-server/src/project/mod.rs#L155)):*
> ```XML
>     /// Runs project controller's event loop.
>     fn event_loop(&mut self) {
>         while let Ok(request) = self.requests_receiver.recv() {
> ```

The current one is clearer for me

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6749)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @mkaput, and @orizi)

**Review by Draggu — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6749#-:-OCiH7drCAUvmq6dqVGm:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @integraledelebesgue, @mkaput, and @orizi)

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6749)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @integraledelebesgue, and @orizi)

___
*[`crates/cairo-lang-language-server/src/project/mod.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6749#-OCgJ95o20NLN9o5upAo:-OCltNEv3LCdlp1f9qNK:bwdgoax) ([raw file](https://github.com/starkware-libs/cairo/blob/1b2c53cc6b6455b1151bf5951396134c0e1c9c35/crates/cairo-lang-language-server/src/project/mod.rs#L109)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

but if we panic then we get the log anyway from the panic hook. it's unnecessary to do both imo

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6749)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @integraledelebesgue, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/src/project/mod.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6749#-OCgJ95o20NLN9o5upAo:-OCnF5l64krbPujUI5TI:b9pvyc0) ([raw file](https://github.com/starkware-libs/cairo/blob/1b2c53cc6b6455b1151bf5951396134c0e1c9c35/crates/cairo-lang-language-server/src/project/mod.rs#L109)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

but if we panic then we get the log anyway from the panic hook. it's unnecessary to do both imo
</blockquote></details>

Done in new repo https://github.com/software-mansion/cairols/pull/2

**Comment by piotmag769** [comment]
Closing in favour of https://github.com/software-mansion/cairols/pull/2

**Pull request closed without merging**
