### PR TITLE
Handle segment arena loop saving builtins

### PR DESCRIPTION
**Pull request by orizi**

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6844)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-runnable-utils/src/builder.rs` line 505 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6844#-ODeSZOm1lHU73NDwj4D:-ODeSZOn-DXcrZpjLhAv:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/de1e3ccd58e74b4f5cd0b53e4cd97c05d8778cc1/crates/cairo-lang-runnable-utils/src/builder.rs#L505)):*
> ```XML
>             casm_build_extend!(ctx, tempvar _cell = local_cell;);
>         }
>         for ((_, var), local_expr) in zip(builtin_vars.iter_mut(), locals) {
> ```

?



_Suggestion:_
```XML
zip_eq
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-runnable-utils/src/builder.rs` line 503 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6844#-ODeSv3IAdB8kMdLOiEr:-ODeSv3J9mwJ_Ev2JhM_:b-7syh4g) ([raw file](https://github.com/starkware-libs/cairo/blob/de1e3ccd58e74b4f5cd0b53e4cd97c05d8778cc1/crates/cairo-lang-runnable-utils/src/builder.rs#L503)):*
> ```XML
>         for _ in 0..return_data.len() {
>             let local_cell = ctx.add_var(locals.next().unwrap().clone());
>             casm_build_extend!(ctx, tempvar _cell = local_cell;);
> ```

What is happening here?



_Code quote:_
```XML
casm_build_extend!(ctx, tempvar _cell = local_cell;);
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6844)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-runnable-utils/src/builder.rs` line 503 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6844#-ODeSv3IAdB8kMdLOiEr:-ODefv1x9A518E_YD8pl:b-huo4b2) ([raw file](https://github.com/starkware-libs/cairo/blob/de1e3ccd58e74b4f5cd0b53e4cd97c05d8778cc1/crates/cairo-lang-runnable-utils/src/builder.rs#L503)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

What is happening here?
</blockquote></details>

result variables are copied back to after the function.
not relevant for our case - as it is empty.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6844)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-runnable-utils/src/builder.rs` line 505 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6844#-ODeSZOm1lHU73NDwj4D:-ODeiih4EbBuz6oXU8o7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/de1e3ccd58e74b4f5cd0b53e4cd97c05d8778cc1/crates/cairo-lang-runnable-utils/src/builder.rs#L505)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-runnable-utils/src/builder.rs` line 503 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6844#-ODeSv3IAdB8kMdLOiEr:-ODfbMrBCP1RgtyLjxWz:bejv05v) ([raw file](https://github.com/starkware-libs/cairo/blob/de1e3ccd58e74b4f5cd0b53e4cd97c05d8778cc1/crates/cairo-lang-runnable-utils/src/builder.rs#L503)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

result variables are copied back to after the function.
not relevant for our case - as it is empty.
</blockquote></details>

Why do we need to copy all the result variables?
can't we write the to the output segment?

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6844)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-runnable-utils/src/builder.rs` line 503 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6844#-ODeSv3IAdB8kMdLOiEr:-ODfbppX1eiOVNG3y6Qi:b-omho52) ([raw file](https://github.com/starkware-libs/cairo/blob/de1e3ccd58e74b4f5cd0b53e4cd97c05d8778cc1/crates/cairo-lang-runnable-utils/src/builder.rs#L503)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why do we need to copy all the result variables?
can't we write the to the output segment?
</blockquote></details>

in the non-`outputting_function` we don't have it.
and in the `outputting_function` case - we have empty `return_data`

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-runnable-utils/src/builder.rs` line 316 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6844#-ODfhaZp3X6_3pt5bX5l:-ODfhaZp3X6_3pt5bX5m:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/c651150d1168008a15f5ce8088ad1766204690b8/crates/cairo-lang-runnable-utils/src/builder.rs#L316)):*
> ```XML
>             local_exprs.push(ctx.get_value(local, false));
>         };
>         // Return value already handled into output ptr in `outputting_function` case.
> ```

?



_Code quote:_
```XML
 already handled
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-runnable-utils/src/builder.rs` line 313 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6844#-ODfi-9EBP_gQ-UNjUrB:-ODfi-9EBP_gQ-UNjUrC:bvfb0bq) ([raw file](https://github.com/starkware-libs/cairo/blob/c651150d1168008a15f5ce8088ad1766204690b8/crates/cairo-lang-runnable-utils/src/builder.rs#L313)):*
> ```XML
>     if has_post_calculation_loop {
>         let mut allocate_cell = || {
>             casm_build_extend!(ctx, localvar local;);
> ```

where are you allocating values to the locals?



_Code quote:_
```XML
casm_build_extend!(ctx, localvar local;);
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-runnable-utils/src/builder.rs` line 469 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6844#-ODjdrHm-vTNYjqLMID_:-ODjdrHm-vTNYjqLMIDa:bxqlt0n) ([raw file](https://github.com/starkware-libs/cairo/blob/5189f586b47d0dada34add65cdd3f79a7497d9dc/crates/cairo-lang-runnable-utils/src/builder.rs#L469)):*
> ```XML
>         // Storing local data on FP - as we have a loop now:
>         for (cell, local_expr) in zip_eq(
>             chain!(&return_data, builtin_vars.iter().filter_map(non_segment_arena_var)).cloned(),
> ```

can you define 
ret_values_iter =    chain!(&return_data, builtin_vars.iter().filter_map(non_segment_arena_var)).

or something like that?



_Code quote:_
```XML
    chain!(&return_data, builtin_vars.iter().filter_map(non_segment_arena_var)).
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6844)* status: 0 of 4 files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-runnable-utils/src/builder.rs` line 469 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6844#-ODjdanW1bdcRF3Rh6IL:-ODje5Ac6X4EM6IdfeKs:b-tlo1nw) ([raw file](https://github.com/starkware-libs/cairo/blob/5189f586b47d0dada34add65cdd3f79a7497d9dc/crates/cairo-lang-runnable-utils/src/builder.rs#L469)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Shouldn't this be skipped in the `outputting_function` case?
</blockquote></details>

adding a comment that this is empty.
___
*[`crates/cairo-lang-runnable-utils/src/builder.rs` line 469 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6844#-ODjdrHm-vTNYjqLMID_:-ODjeM6A2_gQ6ctu1q4r:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5189f586b47d0dada34add65cdd3f79a7497d9dc/crates/cairo-lang-runnable-utils/src/builder.rs#L469)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

can you define 
ret_values_iter =    chain!(&return_data, builtin_vars.iter().filter_map(non_segment_arena_var)).

or something like that?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runnable-utils/src/builder.rs` line 317 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6844#-ODjd9ZRETVIuxViYAJf:-ODje3Bq4Gn8KT83Pa_J:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5189f586b47d0dada34add65cdd3f79a7497d9dc/crates/cairo-lang-runnable-utils/src/builder.rs#L317)):*
> ```XML
>         };
>         // In `outputting_function` case, no need to copy the result to the end, as it was already
>         // handled as the output ptr.
> ```

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r5, 1 of 2 files at r6, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6844#-:-ODkh4X08toJs-ldaXPq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
