### PR TITLE
Custom handling for StructDeconstructLibfunc.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4307)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4307)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/stack_tracking` line 50 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4307#-NheiMja8gyFIv1CKzjs:-NheiMja8gyFIv1CKzjt:b-zifj5z) ([raw file](https://github.com/starkware-libs/cairo/blob/08cbe43e10bdc5584e277f191c82ecb363ad66c8/crates/cairo-lang-sierra-generator/src/function_generator_test_data/stack_tracking#L50)):*
> ```
>     drop::<felt252>(b);
>     tuple
> }
> ```

I belive that this is quite rare in practice, so it is okay to lose track of the item here.



_Code quote:_
```
//! > Test that we lose track of the original stack item after `struct_deconstruct`.

//! > test_runner_name
test_function_generator

//! > function
fn foo() -> (felt252, felt252) {
    let tuple = get_val();
    let (a, b) = tuple;
    // Call drop explicitly to avoid the `struct_deconstruct` above from being optimized out.
    drop::<felt252>(b);
    tuple
}
```

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4307)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/known_stack.rs` line 166 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4307#-Nhex2Is6NsRrE-aWFvT:-Nhex2Is6NsRrE-aWFvU:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/d28dbf4b213138dd4d54a6b9495a10d60894edd9/crates/cairo-lang-sierra-generator/src/store_variables/known_stack.rs#L166)):*
> ```XML
>     }
> 
>     pub fn deconstruct_variable(
> ```

doc
___
*[`crates/cairo-lang-sierra-generator/src/store_variables/known_stack.rs` line 182 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4307#-NhexFxLDkdYK7uI9Ooj:-NhexFxLDkdYK7uI9Ook:bvyidr7) ([raw file](https://github.com/starkware-libs/cairo/blob/d28dbf4b213138dd4d54a6b9495a10d60894edd9/crates/cairo-lang-sierra-generator/src/store_variables/known_stack.rs#L182)):*
> ```XML
>                 // at that place.
>                 // We lose track of the of the fact that the original variable is still on the
>                 // stack but that situation is quite rare.
> ```

won't keeping track of "range" instead of "index" solve this issue?
(the handling done per index would be done for the start and the end values)



_Code quote:_
```XML
                // Invalidate all the variable at `input_idx` and insert `n_outputs`
                // at that place.
                // We lose track of the of the fact that the original variable is still on the
                // stack but that situation is quite rare.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/store_variables/known_stack.rs` line 182 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4307#-NhexFxLDkdYK7uI9Ooj:-NheyJj820mfLAw_uua_:bmj29e9) ([raw file](https://github.com/starkware-libs/cairo/blob/d28dbf4b213138dd4d54a6b9495a10d60894edd9/crates/cairo-lang-sierra-generator/src/store_variables/known_stack.rs#L182)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

won't keeping track of "range" instead of "index" solve this issue?
(the handling done per index would be done for the start and the end values)
</blockquote></details>

Maybe, but it is a large change and I'm not sure it is worth the effort.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4307)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/known_stack.rs` line 182 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4307#-NhexFxLDkdYK7uI9Ooj:-Nhfrx0m7xtL2PUr469e:b-ras4iz) ([raw file](https://github.com/starkware-libs/cairo/blob/d28dbf4b213138dd4d54a6b9495a10d60894edd9/crates/cairo-lang-sierra-generator/src/store_variables/known_stack.rs#L182)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Maybe, but it is a large change and I'm not sure it is worth the effort.
</blockquote></details>

in anycase - even if it isn't worth it - add a TODO consider.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4307)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/known_stack.rs` line 166 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4307#-Nhex2Is6NsRrE-aWFvT:-NhuYuvU73oHSw2JyM8J:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d28dbf4b213138dd4d54a6b9495a10d60894edd9/crates/cairo-lang-sierra-generator/src/store_variables/known_stack.rs#L166)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/store_variables/known_stack.rs` line 182 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4307#-NhexFxLDkdYK7uI9Ooj:-NhuYvLD2NAqQaDlDVwf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d28dbf4b213138dd4d54a6b9495a10d60894edd9/crates/cairo-lang-sierra-generator/src/store_variables/known_stack.rs#L182)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

in anycase - even if it isn't worth it - add a TODO consider.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4307#-:-NhuZY4y7UgoRToPkzTo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
