### PR TITLE
Reduced uint128 support only to the min required building blocks.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:139cb509

---

**Stack**:
- #1232
- #1231
- #1230
- #1229
- #1228
- #1227
- #1205
- #1204
- #1201 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1201)* status: 0 of 16 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/integer.cairo` line 20 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1201#-NIRsVjODjqq-CacVgO0:-NIRsVjODjqq-CacVgO1:bfzj97) ([raw file](https://github.com/starkware-libs/cairo/blob/791c2237eb4a7a0764e5b22af0b4f2e20e94fdb0/corelib/integer.cairo#L20)):*
> ```Cairo
>     b: uint128
> ) -> Result::<uint128, uint128> implicits(rc: RangeCheck) nopanic;
> extern func uint128_overflow_mul(
> ```

Should this return a pair(high, low)?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1201)* status: 0 of 16 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`corelib/integer.cairo` line 20 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1201#-NIRsVjODjqq-CacVgO0:-NISHpCr2s7Z2JgLG4_5:b84opkv) ([raw file](https://github.com/starkware-libs/cairo/blob/791c2237eb4a7a0764e5b22af0b4f2e20e94fdb0/corelib/integer.cairo#L20)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Should this return a pair(high, low)?
</blockquote></details>

will add a user function called "uint128_overflowing_{add,sub,mul}" that would return a bool as in rust.
any ideas of how to name the underlying result based extern that does simulate this boolean using a result?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1201)* status: 0 of 16 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`corelib/integer.cairo` line 20 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1201#-NIRsVjODjqq-CacVgO0:-NITEypkDFSY-__rVrYc:b-40ykmx) ([raw file](https://github.com/starkware-libs/cairo/blob/791c2237eb4a7a0764e5b22af0b4f2e20e94fdb0/corelib/integer.cairo#L20)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

will add a user function called "uint128_overflowing_{add,sub,mul}" that would return a bool as in rust.
any ideas of how to name the underlying result based extern that does simulate this boolean using a result?
</blockquote></details>

will be fixed in the bottom pr of this stack anyway.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 7 of 16 files at r1, 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1201#-:-NIawyYZCwXA6PGFageQ:bnfp4nl)* status: 11 of 16 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 4 of 16 files at r1, 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1201)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> Dismissed @spapinistarkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1201)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1201)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
