### PR TITLE
Span refactor to correctly handle unicode

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1987)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1987#-:-NN5i9Hp3XUA8mvR1Apg:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-filesystem/src/span.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1987#-NN5gycM-0LcdjaeJ6IU:-NN5gycM-0LcdjaeJ6IV:b-9im1qf) ([raw file](https://github.com/starkware-libs/cairo/blob/51402fd36ace43bb76df401102be21faf0b43b30/crates/cairo-lang-filesystem/src/span.rs#L23)):*
> ```XML
>         Self(s.len() as u32)
>     }
>     pub fn new_for_testing(value: u32) -> Self {
> ```

is this the best rusty way to do this?



_Code quote:_
```XML
new_for_testing
```

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 3 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1987)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-diagnostics/src/diagnostics_test.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1987#-NN6R4u1DIQmqe12WwZc:-NN6R4u1DIQmqe12WwZd:b2ni8l0) ([raw file](https://github.com/starkware-libs/cairo/blob/51402fd36ace43bb76df401102be21faf0b43b30/crates/cairo-lang-diagnostics/src/diagnostics_test.rs#L28)):*
> ```XML
>             file_id: self.file_id,
>             span: TextSpan {
>                 start: TextOffset::default().add_width(TextWidth::new_for_testing(0)),
> ```

nit



_Suggestion:_
```XML
            span: TextSpan::new_for_testing(0, 6),
```

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 21 of 22 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1987)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1987)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-filesystem/src/span.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1987#-NN5gycM-0LcdjaeJ6IU:-NNAuJgYEmxVrEcJp6O1:bmris2a) ([raw file](https://github.com/starkware-libs/cairo/blob/51402fd36ace43bb76df401102be21faf0b43b30/crates/cairo-lang-filesystem/src/span.rs#L23)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is this the best rusty way to do this?
</blockquote></details>

Don't know, but it's good enough for now.

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1987)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1987)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-diagnostics/src/diagnostics_test.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1987#-NN6R4u1DIQmqe12WwZc:-NNAxTgi8w9oJOfCQOje:bwygxsx) ([raw file](https://github.com/starkware-libs/cairo/blob/51402fd36ace43bb76df401102be21faf0b43b30/crates/cairo-lang-diagnostics/src/diagnostics_test.rs#L28)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

nit
</blockquote></details>

Noted.

**Pull request merged**
