### PR TITLE
Refactored out validation number is in range.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:f053a148

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1866)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs` line 211 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1866#-NMXTfkU4qN2yh1Bqk_p:-NMXTfkU4qN2yh1Bqk_q:b-mnid7p) ([raw file](https://github.com/starkware-libs/cairo/blob/715529c6425cfdd2f87f41cad37ce4bfbce14a05/crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs#L211)):*
> ```XML
>                 // x < 2**128 && x != 2**128 - 1 ==> x < 2**128 - 1
>                 assert x = *(range_check++);
>                 assert diff = x - u128_limit_minus_1;
> ```

can't you allocate diff here?

why do you need to accept it as input?



_Code quote:_
```XML
assert diff = x - u128_limit_minus_1;
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1866)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs` line 211 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1866#-NMXTfkU4qN2yh1Bqk_p:-NMXmlbu-kbJRSW_6VAu:b-bnmpwg) ([raw file](https://github.com/starkware-libs/cairo/blob/5bb8e0f93696558a3363e5e0ef39e81a0f737af1/crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs#L211)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

can't you allocate diff here?

why do you need to accept it as input?
</blockquote></details>

no - otherwise the caller cannot set the memory layout of the outputs.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1866)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs` line 211 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1866#-NMXTfkU4qN2yh1Bqk_p:-NMXnjHLDAbLOQztSplH:biwoj1k) ([raw file](https://github.com/starkware-libs/cairo/blob/5bb8e0f93696558a3363e5e0ef39e81a0f737af1/crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs#L211)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no - otherwise the caller cannot set the memory layout of the outputs.
</blockquote></details>

please document that diff is an aux var that is only used in the K=2 case.



_Code quote:_
```XML
[x, y, x_part, y_fixed]: [Var; 4],
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1866)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs` line 211 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1866#-NMXTfkU4qN2yh1Bqk_p:-NMXsVJk7tg19tcvesdR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5bb8e0f93696558a3363e5e0ef39e81a0f737af1/crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs#L211)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

please document that diff is an aux var that is only used in the K=2 case.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1866#-:-NMXxhaG3yrMYe0uzGpw:bnfp4nl)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs` line 177 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1866#-NMXvofd5tkJNBNjGXmF:-NMXvofd5tkJNBNjGXmG:bqsp5tq) ([raw file](https://github.com/starkware-libs/cairo/blob/e1ef2fad73fd909dc0ca64d39592aa964cc58665/crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs#L177)):*
> ```XML
>     value: Var,
>     range_check: Var,
>     calc_vars: &[Var],
> ```

consider



_Suggestion:_
```XML
auxiliary_vars
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1866)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1866)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1866)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1866)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 1 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1866)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1866)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
