### PR TITLE
const in semantic: Add skeleton code (not implemented yet).

### PR DESCRIPTION
**Pull request by liorgold2**
commit-id:ab0d7e6b

---

**Stack**:
- #1758
- #1751 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1751#-:-NLa6onv786Z8l3gK7-9:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/const` line 15 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1751#-NLa6h-c0el5TuRaWAVY:-NLa6h-c0el5TuRaWAVZ:bzbdqsc) ([raw file](https://github.com/starkware-libs/cairo/blob/8d70ce3915e01b4adad50361453db642a478048e/crates/cairo-lang-semantic/src/expr/test_data/const#L15)):*
> ```
> 
> //! > module_code
> const MyConst: felt = 0x1234;
> ```

Consider using captial snake case



_Suggestion:_
```
MY_CONST
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1751)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/const` line 15 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1751#-NLa6h-c0el5TuRaWAVY:-NLaNOMx5ji8MvypKtMm:b-6ta9xg) ([raw file](https://github.com/starkware-libs/cairo/blob/8d70ce3915e01b4adad50361453db642a478048e/crates/cairo-lang-semantic/src/expr/test_data/const#L15)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Consider using captial snake case
</blockquote></details>

Right. Thanks.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1751)* status: all files reviewed, 6 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 84 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1751#-NLaSPMp5vXPuE18ez7X:-NLaSPMp5vXPuE18ez7Y:b-y03br0) ([raw file](https://github.com/starkware-libs/cairo/blob/2386e3be1f74858457573e21125c4326eb38bbab/crates/cairo-lang-semantic/src/db.rs#L84)):*
> ```XML
>     // Const.
>     // ====
>     /// Private query to compute data about a constant declaration.
> ```

it has its value, it's a definition



_Suggestion:_
```XML
    /// Private query to compute data about a constant definition.
    #[salsa::invoke(items::const_::priv_const_semantic_data)]
    fn priv_const_semantic_data(&self, const_id: ConstId) -> Maybe<items::const_::ConstData>;
    /// Returns the semantic diagnostics of a constant definition.
    #[salsa::invoke(items::const_::const_semantic_diagnostics)]
    fn const_semantic_diagnostics(&self, const_id: ConstId) -> Diagnostics<SemanticDiagnostic>;
```
___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 418 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1751#-NLaSb7X5wmcQPwU9nwD:-NLaSb7X5wmcQPwU9nwE:bshcfob) ([raw file](https://github.com/starkware-libs/cairo/blob/2386e3be1f74858457573e21125c4326eb38bbab/crates/cairo-lang-semantic/src/diagnostic.rs#L418)):*
> ```XML
>             }
>             SemanticDiagnosticKind::ConstantsAreNotSupported => {
>                 "Constant declarations are not supported yet.".into()
> ```

definitions



_Code quote:_
```XML
declarations
```
___
*[`crates/cairo-lang-semantic/src/items/const_.rs` line 11 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1751#-NLaTMb5DnwXzgHBQIR9:-NLaTMb5DnwXzgHBQIRA:bhy6n7a) ([raw file](https://github.com/starkware-libs/cairo/blob/2386e3be1f74858457573e21125c4326eb38bbab/crates/cairo-lang-semantic/src/items/const_.rs#L11)):*
> ```XML
> 
> // TODO(lior): Add a test.
> // #[cfg(test)]
> ```

You can add it now, empty, with a TODO to add tests there. Then you won't have submitted commented code



_Code quote:_
```XML
// TODO(lior): Add a test.
// #[cfg(test)]
// #[path = "const_test.rs"]
// mod test;
```
___
*[`crates/cairo-lang-semantic/src/items/const_.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1751#-NLaTWxz4HAttPQvA6j7:-NLaTWxz4HAttPQvA6j8:b-nfxl0f) ([raw file](https://github.com/starkware-libs/cairo/blob/2386e3be1f74858457573e21125c4326eb38bbab/crates/cairo-lang-semantic/src/items/const_.rs#L17)):*
> ```XML
> #[derive(Clone, Debug, PartialEq, Eq, DebugWithDb)]
> #[debug_db(dyn SemanticGroup + 'static)]
> pub struct ConstData {
> ```

doc.
Also, I prefer "ConstantData"
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 240 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1751#-NLaTxnzBRngOCqYN2rx:-NLaTxnzBRngOCqYN2ry:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2386e3be1f74858457573e21125c4326eb38bbab/crates/cairo-lang-semantic/src/items/imp.rs#L240)):*
> ```XML
>         for item in body.items(syntax_db).elements(syntax_db) {
>             match item {
>                 Item::Const(const_) => {
> ```





_Suggestion:_
```XML
::Const(constant)
```
___
*[`crates/cairo-lang-semantic/src/items/mod.rs` line 2 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1751#-NLaU3XeAnSWCgTHeoMv:-NLaU3XeAnSWCgTHeoMw:b8iawme) ([raw file](https://github.com/starkware-libs/cairo/blob/2386e3be1f74858457573e21125c4326eb38bbab/crates/cairo-lang-semantic/src/items/mod.rs#L2)):*
> ```XML
> pub mod attribute;
> pub mod const_;
> ```

"constant" would spare the need for the underscore.



_Code quote:_
```XML
const_
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1751)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 240 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1751#-NLaTxnzBRngOCqYN2rx:-NLadl7vEk0MaimVRxLO:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/2386e3be1f74858457573e21125c4326eb38bbab/crates/cairo-lang-semantic/src/items/imp.rs#L240)):*
> ```XML
>         for item in body.items(syntax_db).elements(syntax_db) {
>             match item {
>                 Item::Const(const_) => {
> ```

Done

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1751#-:-NLb6HpSEijZdNsBZl2_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1751)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
