### PR TITLE
Fix entry point builtin list.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
1. Use snake case.
2. remove GasBuiltin from list.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1477)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1477)* status: 4 of 7 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/starknet/src/casm_contract_class.rs` line 131 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1477#-NK8ov_-A_FfvT4UbT82:-NK8ov_-A_FfvT4UbT83:bnxbke0) ([raw file](https://github.com/starkware-libs/cairo/blob/411a2714b2bf5cf5cd6b61847d1c3477e0283cc4/crates/starknet/src/casm_contract_class.rs#L131)):*
> ```XML
>             // TODO(ilya): Check that the last argument is PanicResult.
>             assert_eq!(
>                 leftover[..2].iter().map(|type_id| name_by_short_id.get(&type_id.id)).collect_vec(),
> ```

shouldn't this return a Result?



_Code quote:_
```XML
            // TODO(ilya): Check that the last argument is PanicResult.
            assert_eq!(
                leftover[..2].iter().map(|type_id| name_by_short_id.get(&type_id.id)).collect_vec(),
                [Some(&"gas_builtin"), Some(&"system")],
            );
```
___
*[`crates/starknet/src/contract_class.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1477#-NK8nbbM25qje71K74TU:-NK8nbbM25qje71K74TV:b-rtagwg) ([raw file](https://github.com/starkware-libs/cairo/blob/411a2714b2bf5cf5cd6b61847d1c3477e0283cc4/crates/starknet/src/contract_class.rs#L46)):*
> ```XML
>     pub entry_points_by_type: ContractEntryPoints,
>     pub abi: abi::Contract,
>     
> ```

delete
___
*[`examples/fib.cairo` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1477#-NK8njxo1ohU1BWQnql4:-NK8njxo1ohU1BWQnql5:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/411a2714b2bf5cf5cd6b61847d1c3477e0283cc4/examples/fib.cairo#L9)):*
> ```Cairo
> }
> 
> func fib(a: felt, b: felt, n: felt) -> felt {
> ```

?



_Code quote:_
```Cairo


func fib(a: felt, b: felt, n: felt) -> felt {
    match n {
        0 => a + 3,
        _ => fib(b, a + b, n - 1),
    }
}
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1477)* status: 3 of 7 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/starknet/src/casm_contract_class.rs` line 131 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1477#-NK8ov_-A_FfvT4UbT82:-NK8u6IW8KHleW7468rn:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/411a2714b2bf5cf5cd6b61847d1c3477e0283cc4/crates/starknet/src/casm_contract_class.rs#L131)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

shouldn't this return a Result?
</blockquote></details>

Done.
___
*[`crates/starknet/src/contract_class.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1477#-NK8nbbM25qje71K74TU:-NK8u6gPBhYHHUJYFzMr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/411a2714b2bf5cf5cd6b61847d1c3477e0283cc4/crates/starknet/src/contract_class.rs#L46)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1477)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/starknet/src/casm_contract_class.rs` line 133 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1477#-NK8vA-k14hffX-367C0:-NK8vA-k14hffX-367C1:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/bb0b42a467549e8d18bbd88e581834a9a64d7288/crates/starknet/src/casm_contract_class.rs#L133)):*
> ```XML
>             // TODO(ilya): Check that the last argument is PanicResult.
>             if leftover[..2].iter().map(|type_id| name_by_short_id.get(&type_id.id)).collect_vec()
>                 != [Some(&"gas_builtin"), Some(&"system")]
> ```





_Suggestion:_
```XML
            if !itertools::equals(leftover[..2].iter().map(|type_id| name_by_short_id.get(&type_id.id)), [Some(&"gas_builtin"), Some(&"system")])
```

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1477#-:-NK8vVwh34sKmoRYhEiD:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1477)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`examples/fib.cairo` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1477#-NK8njxo1ohU1BWQnql4:-NK8wJH_5PTHaprv9tPf:bvth56w) ([raw file](https://github.com/starkware-libs/cairo/blob/411a2714b2bf5cf5cd6b61847d1c3477e0283cc4/examples/fib.cairo#L9)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

reverted

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1477)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/starknet/src/casm_contract_class.rs` line 133 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1477#-NK8vA-k14hffX-367C0:-NK8zusTAKE0Scw_DgzD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8941a78038c3192a47024843ca3ff4ae608acd5b/crates/starknet/src/casm_contract_class.rs#L133)):*
> ```XML
>             // TODO(ilya): Check that the last argument is PanicResult.
>             if leftover[..2].iter().map(|type_id| name_by_short_id.get(&type_id.id)).collect_vec()
>                 != [Some(&"gas_builtin"), Some(&"system")]
> ```

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1477)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`crates/starknet/src/casm_contract_class.rs` line 133 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1477#-NK9-3rS7RqJZ8x5YCiX:-NK9-3rT7xT7GGvCWh_1:b-lavs3j) ([raw file](https://github.com/starkware-libs/cairo/blob/85c1cbc61bd94197949182903360eb40bf97432c/crates/starknet/src/casm_contract_class.rs#L133)):*
> ```XML
>             if !itertools::equal(
>                 leftover[..2].iter().map(|type_id| name_by_short_id.get(&type_id.id)),
>                 [Some(&"gas_builtin"), Some(&"system")].into_iter(),
> ```

i don't think this is required.



_Code quote:_
```XML
.into_iter(),
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1477)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/starknet/src/casm_contract_class.rs` line 133 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1477#-NK9-3rS7RqJZ8x5YCiX:-NK9-jmM4-n27zZi1aNI:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/85c1cbc61bd94197949182903360eb40bf97432c/crates/starknet/src/casm_contract_class.rs#L133)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i don't think this is required.
</blockquote></details>

done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 3 of 7 files at r1, 1 of 4 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1477)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
