### PR TITLE
Added div-rem for BoundedInts.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #5393
- #5389
- #5388 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5388)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 162 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5388#-Nv5clXZA5cqra-O2g2u:-Nv5clXZA5cqra-O2g2v:b-3yjqv3) ([raw file](https://github.com/starkware-libs/cairo/blob/2e9811397059d83416f07a57b5695dd2b34be493/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L162)):*
> ```XML
>         // Supporting only division of a non-negative number by a positive number.
>         // TODO(orizi): Consider relaxing the constraint, and defining the div_rem of negatives.
>         if lhs_range.lower.is_negative() || !rhs_range.lower.is_positive() {
> ```

Isn't this the same condition?



_Suggestion:_
```XML
if !rhs_range.lower.is_positive() {
```

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5388#-:-Nv5f0US1pLtnna9N5O5:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5388)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 162 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5388#-Nv5clXZA5cqra-O2g2u:-Nv6G-qOB2Sd3-2ezxUW:bls5lqy) ([raw file](https://github.com/starkware-libs/cairo/blob/2e9811397059d83416f07a57b5695dd2b34be493/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L162)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Isn't this the same condition?
</blockquote></details>

discussed f2f.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5388#-:-Nv791-DC1CVL0kRQSoo:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
