### PR TITLE
Move read test file logic to test utils and use it in expand contract…

### PR DESCRIPTION
**Pull request by gilbens-starkware**
… test.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4097)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4097#-:-Nekn7wP7UxPoh3bajM7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4097)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4097)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-parser/src/parser_test.rs` line 113 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4097#-NeluH86AQSlGbH0m8id:-NeluH875KVRKlJoFvDm:b-vymbtc) ([raw file](https://github.com/starkware-libs/cairo/blob/22937bd52c803fc4e19b3372d08eff96ea8b792e/crates/cairo-lang-parser/src/parser_test.rs#L113)):*
> ```XML
> ) -> (SyntaxNode, String) {
>     let (file_path, cairo_code) =
>         if let Some((path, content)) = parse_maybe_file_input(&inputs["cairo_code"]) {
> ```

change/wrap this function to return the content anyway - either if it's in a file or directly there.
so it should return `(String, Option<String>)` (content, Option<path>).
Or, it can get the default path to use, and return `(String, String)`

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4097)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser_test.rs` line 113 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4097#-NeluH86AQSlGbH0m8id:-Nem1D753MYMxzajWZ2r:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/af0367a4e8fa34773390498343824b0acc698044/crates/cairo-lang-parser/src/parser_test.rs#L113)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

change/wrap this function to return the content anyway - either if it's in a file or directly there.
so it should return `(String, Option<String>)` (content, Option<path>).
Or, it can get the default path to use, and return `(String, String)`
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4097)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4097#-:-Nemb_771A3iROZUZiG3:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-test-utils/src/lib.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4097#-Nemb4Gh4vky4KQmgERI:-Nemb4Gh4vky4KQmgERJ:bj6043l) ([raw file](https://github.com/starkware-libs/cairo/blob/a0bc864395a578b1ed15e5db840fe61d9dfb4fb9/crates/cairo-lang-test-utils/src/lib.rs#L80)):*
> ```XML
> /// file and returns the file path and content, otherwise, it returns the input and a default dummy
> /// path.
> pub fn parse_maybe_file_input(input: &str) -> (String, String) {
> ```

Please rename. Suggestion:
get_direct_or_file_content

I thought of "dummy_file.cairo" as a param to this function, but I guess it's OK for now. We can change in the future if needed.



_Code quote:_
```XML
parse_maybe_file_input
```

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4097)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
