### PR TITLE
Add Sierra entry points.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1157)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1157)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/starknet/src/contract_class.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1157#-NI2oFvv2Z81w8uFQfOo:-NI2oFvwDQA9lAumfrzD:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/87eb4651b58fb47cee2d049009637051b5a6bcb1/crates/starknet/src/contract_class.rs#L100)):*
> ```XML
>     };
> 
>     let impl_id = db.lookup_intern_concrete_impl(concrete_impl_id).impl_id;
> ```





_Suggestion:_
```XML
concrete_impl_id
```

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1157)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/starknet/src/contract_class.rs` line 126 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1157#-NI2oZOE6OHk1hQp1ise:-NI2oZOE6OHk1hQp1isf:bd068yi) ([raw file](https://github.com/starkware-libs/cairo/blob/87eb4651b58fb47cee2d049009637051b5a6bcb1/crates/starknet/src/contract_class.rs#L126)):*
> ```XML
> fn get_entry_points(
>     db: &mut RootDatabase,
>     impl_id: defs::ids::ImplId,
> ```

Pass only module here



_Code quote:_
```XML
impl_id: defs::ids::ImplId
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1157)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/starknet/src/contract_class.rs` line 124 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1157#-NI3WcViCMs2gIS6Ybwd:-NI3WcVj8i6Zomg4RdP3:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/87eb4651b58fb47cee2d049009637051b5a6bcb1/crates/starknet/src/contract_class.rs#L124)):*
> ```XML
> }
> 
> fn get_entry_points(
> ```

doc



_Code quote:_
```XML
get_entry_points
```
___
*[`crates/starknet/src/contract_class.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1157#-NI3Wl0A9vrHaBybUOII:-NI3Wl0BD26erwhNA9oG:bd1fs5r) ([raw file](https://github.com/starkware-libs/cairo/blob/87eb4651b58fb47cee2d049009637051b5a6bcb1/crates/starknet/src/contract_class.rs#L137)):*
> ```XML
>             .with_context(|| "{function_name} not found.")?;
> 
>         let free_func_id = extract_matches!(item, ModuleItemId::FreeFunction);
> ```

if it wasn't validated already



_Suggestion:_
```XML
let free_func_id = try_extract_matches!(item, ModuleItemId::FreeFunction).with_context(|| ....)?;
```

**Review by orizi — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1157)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1157)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/starknet/src/contract_class.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1157#-NI2oFvv2Z81w8uFQfOo:-NI6HyH36a8UWxi8O5wa:b-d3kakd) ([raw file](https://github.com/starkware-libs/cairo/blob/87eb4651b58fb47cee2d049009637051b5a6bcb1/crates/starknet/src/contract_class.rs#L100)):*
> ```XML
>     };
> 
>     let impl_id = db.lookup_intern_concrete_impl(concrete_impl_id).impl_id;
> ```

It is an imple id
___
*[`crates/starknet/src/contract_class.rs` line 124 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1157#-NI3WcViCMs2gIS6Ybwd:-NI6O7lu1y0OJy93P4jM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/87eb4651b58fb47cee2d049009637051b5a6bcb1/crates/starknet/src/contract_class.rs#L124)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/starknet/src/contract_class.rs` line 126 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1157#-NI2oZOE6OHk1hQp1ise:-NI6Kg0F3C4NTI6d3G6Q:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/87eb4651b58fb47cee2d049009637051b5a6bcb1/crates/starknet/src/contract_class.rs#L126)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Pass only module here
</blockquote></details>

Done.
___
*[`crates/starknet/src/contract_class.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1157#-NI3Wl0A9vrHaBybUOII:-NI6MAar1MNNYmcIIEUW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/87eb4651b58fb47cee2d049009637051b5a6bcb1/crates/starknet/src/contract_class.rs#L137)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

if it wasn't validated already
</blockquote></details>

Done.

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1157)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @orizi)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1157#-:-NI6tukR5upGdj5Us5C5:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @orizi)

**Review by spapinistarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1157)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1157)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1157)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/starknet/src/contract_class_test.rs` line 111 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1157#-NI7H9wM6Ac_oMWRVhbf:-NI7H9wN005M2YQm-Wzd:bdan6vk) ([raw file](https://github.com/starkware-libs/cairo/blob/b7fa26343ae7f10ac29a3daf2fc93ad844f48562/crates/starknet/src/contract_class_test.rs#L111)):*
> ```XML
>               {
>                 "selector": "0x0",
>                 "function_id": 0
> ```

It seems that this is not stable :(



_Code quote:_
```XML
0
```

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1157)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1157)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
