### PR TITLE
Impl function generics

### PR DESCRIPTION
**Pull request by spapinistarkware**
commit-id:c2e58af2

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1905)* status: 4 of 10 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/resolve_path.rs` line 214 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1905#-NMdNILoCM3f9-oXxZIZ:-NMdNILoCM3f9-oXxZI_:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/7dcdae6344abc66cfb614e484b65752a12af3114/crates/cairo-lang-semantic/src/resolve_path.rs#L214)):*
> ```XML
>     }
> 
>     pub fn resolve_segment(
> ```

doc



_Code quote:_
```XML
    pub fn resolve_segment(
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1905#-:-NMdNrUZ0nuXx1s3mdVc:bnfp4nl)* status: 6 of 10 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1905)* status: 6 of 10 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/resolve_path.rs` line 214 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1905#-NMdNILoCM3f9-oXxZIZ:-NMdNvrm6n-iCXhqWCk9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7dcdae6344abc66cfb614e484b65752a12af3114/crates/cairo-lang-semantic/src/resolve_path.rs#L214)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 4 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1905)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1905)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1905)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 5 of 10 files at r1, 1 of 3 files at r2, 2 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1905)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1905)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
