### PR TITLE
Add inline macro plugin and use it for consteval_int.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3497)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3497)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-plugins/src/plugins/inline_macro_plugin.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3497#-NYmlYWAEKwMwPyIdPPn:-NYmlYWAEKwMwPyIdPPo:b-5ae9kc) ([raw file](https://github.com/starkware-libs/cairo/blob/7612f7c00fa1ece15452a440455700d9001d3472/crates/cairo-lang-plugins/src/plugins/inline_macro_plugin.rs#L16)):*
> ```XML
> 
> #[derive(Debug, Default)]
> pub struct MacroExpanderData {
> ```

doc all

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3497#-:-NYmzcVjAktIhViA9o0o:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3497)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-plugins/src/plugins/inline_macro_plugin.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3497#-NYmlYWAEKwMwPyIdPPn:-NYnZo2wCmeuP9yWRxIJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7612f7c00fa1ece15452a440455700d9001d3472/crates/cairo-lang-plugins/src/plugins/inline_macro_plugin.rs#L16)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc all
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3497)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-plugins/src/plugins/inline_macro_plugin.rs` line 37 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3497#-NYoaqG38UIsiWteviyz:-NYoaqG38UIsiWteviz-:b-9dttjb) ([raw file](https://github.com/starkware-libs/cairo/blob/53dad6d0020476bf47ba6ab37cab3e5bb59648a5/crates/cairo-lang-plugins/src/plugins/inline_macro_plugin.rs#L37)):*
> ```XML
>     match macro_name {
>         "consteval_int" => Some(Box::new(ConstevalIntMacro)),
>         "identity" => Some(Box::new(inline_macros::identity::IdentityMacro)),
> ```

remove this.
___
*[`crates/cairo-lang-plugins/src/test_data/inline_macros` line 20 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3497#-NYob5SoClESQFJIgSF8:-NYob5SoClESQFJIgSF9:b-60uy04) ([raw file](https://github.com/starkware-libs/cairo/blob/53dad6d0020476bf47ba6ab37cab3e5bb59648a5/crates/cairo-lang-plugins/src/test_data/inline_macros#L20)):*
> ```
> const a: felt252 = 0;
> ```

why the extra lines?

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3497)* status: 4 of 8 files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-plugins/src/plugins/inline_macro_plugin.rs` line 37 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3497#-NYoaqG38UIsiWteviyz:-NYqXBOO-eAkc6cAJfPE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/53dad6d0020476bf47ba6ab37cab3e5bb59648a5/crates/cairo-lang-plugins/src/plugins/inline_macro_plugin.rs#L37)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove this.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-plugins/src/test_data/inline_macros` line 20 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3497#-NYob5SoClESQFJIgSF8:-NYqXE5d9fnt-RXnylAz:b-uvyo5m) ([raw file](https://github.com/starkware-libs/cairo/blob/53dad6d0020476bf47ba6ab37cab3e5bb59648a5/crates/cairo-lang-plugins/src/test_data/inline_macros#L20)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why the extra lines?
</blockquote></details>

One from the plugin, one because the test function prints the items with `\n` in between (it is required for other plugins).

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3497#-:-NYqfFjq3k3_ZttwqL30:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3497)* status: 5 of 24 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3497#-NYxkzE-Be8mb1w9DnYa:-NYxkzE-Be8mb1w9DnYb:b-fkm92f) (no related file):*
fix base - currently unreadable.

___

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3497)* status: 5 of 24 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3497#-NYxkzE-Be8mb1w9DnYa:-NZ-deAMCf68RQ6z40B4:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix base - currently unreadable.
</blockquote></details>

Done.

___

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 3 files at r4, 1 of 17 files at r5, 16 of 16 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3497)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
