### PR TITLE
add type in use statements

### PR DESCRIPTION
**Pull request by Tomer-StarkWare**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6372)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6372)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 3615 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6372#-O6NXYbY0NOlZt-TLh6O:-O6NXYbY0NOlZt-TLh6P:bbrv6pg) ([raw file](https://github.com/starkware-libs/cairo/blob/cbeaf611730ac88719f7941ab71182eb4635814e/crates/cairo-lang-semantic/src/expr/compute.rs#L3615)):*
> ```XML
>                                 add_item_to_statement_environment(ctx, name, var_def, stable_ptr);
>                             }
>                             ResolvedGenericItem::GenericTypeAlias(type_id) => {
> ```

this can't work this way - this is an type alias item - not a type.
this expects to get proper generic params on usage - you currently assume you get the actual final type.



_Suggestion:_
```XML
ResolvedGenericItem::GenericTypeAlias(type_alias_id) => {
```
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 3625 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6372#-O6NXRRS-vkKFNtTysrO:-O6NXRRS-vkKFNtTysrP:b-ppg424) ([raw file](https://github.com/starkware-libs/cairo/blob/cbeaf611730ac88719f7941ab71182eb4635814e/crates/cairo-lang-semantic/src/expr/compute.rs#L3625)):*
> ```XML
>                             | ResolvedGenericItem::GenericFunction(_)
>                             | ResolvedGenericItem::TraitFunction(_)
>                             | ResolvedGenericItem::GenericType(_)
> ```

this one is actually simpler.



_Code quote:_
```XML
                            | ResolvedGenericItem::GenericType(_)
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6372)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 3625 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6372#-O6NXRRS-vkKFNtTysrO:-O6e7z2730lFWXdKEO4l:b-87hbi0) ([raw file](https://github.com/starkware-libs/cairo/blob/cbeaf611730ac88719f7941ab71182eb4635814e/crates/cairo-lang-semantic/src/expr/compute.rs#L3625)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this one is actually simpler.
</blockquote></details>

Great

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6372)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 3615 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6372#-O6NXYbY0NOlZt-TLh6O:-O6e9awz0g3ZUs9e_LDM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cbeaf611730ac88719f7941ab71182eb4635814e/crates/cairo-lang-semantic/src/expr/compute.rs#L3615)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this can't work this way - this is an type alias item - not a type.
this expects to get proper generic params on usage - you currently assume you get the actual final type.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6372)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 3615 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6372#-O6NXYbY0NOlZt-TLh6O:-O6llkcoCqSArXE0gqby:b-651bzl) ([raw file](https://github.com/starkware-libs/cairo/blob/cbeaf611730ac88719f7941ab71182eb4635814e/crates/cairo-lang-semantic/src/expr/compute.rs#L3615)):*
<details><summary><i>Previously, Tomer-StarkWare (TomerC-StarkWare) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

as i stated - this can't work this way - the local definition of type alias needs to be scrapped for the time being.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 3625 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6372#-O6NXRRS-vkKFNtTysrO:-O6lluvnBskZibAgyXkp:b-f81s0x) ([raw file](https://github.com/starkware-libs/cairo/blob/cbeaf611730ac88719f7941ab71182eb4635814e/crates/cairo-lang-semantic/src/expr/compute.rs#L3625)):*
<details><summary><i>Previously, Tomer-StarkWare (TomerC-StarkWare) wrote…</i></summary><blockquote>

Great
</blockquote></details>

do another PR  that actually does only that.

**Pull request closed without merging**
