### PR TITLE
Add resolver data on semantic models of items

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2885)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2885** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2885" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2885?utm_source=stack-comment).

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2885)* status: 0 of 17 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2885#-NTRCvSjBK6KQDenKNz7:-NTRCvSjBK6KQDenKNz8:b-hue618) (no related file):*
Start of scope refactor

___

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2885#-:-NTRmJhH9TCJUjJywlFR:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2885)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
