### PR TITLE
Support negative impls in parser.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4460)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4460)* status: 0 of 14 files reviewed, 1 unresolved discussion

___
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/neg_impl` line 27 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4460#-Njw6exn-4EYCb4u8hkc:-Njw6exn-4EYCb4u8hkd:bjobgdr) ([raw file](https://github.com/starkware-libs/cairo/blob/cdcf4b91aa72c7403ec496f1b7ae07e8af77b7e0/crates/cairo-lang-semantic/src/diagnostic_test_data/neg_impl#L27)):*
> ```
> error: Negative impls are not supported in this context.
>  --> lib.cairo:1:38
> pub trait Bad<T, -NegImpl, +Drop<T>, -Drop<T>> {
> ```

Do we want to enforce that negative impls must be last?



_Code quote:_
```
-NegImpl, +Drop<T>
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 13 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4460)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/neg_impl` line 27 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4460#-Njw6exn-4EYCb4u8hkc:-NjwH8-HCoKszkrWov7z:b-9o7xuc) ([raw file](https://github.com/starkware-libs/cairo/blob/cdcf4b91aa72c7403ec496f1b7ae07e8af77b7e0/crates/cairo-lang-semantic/src/diagnostic_test_data/neg_impl#L27)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Do we want to enforce that negative impls must be last?
</blockquote></details>

hmm - lets hold on that for now - i think it is fine that you'd have to be named if you use them non-last.
___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 397 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4460#-NjwHJVaDAbgXVz6Xpz-:-NjwHJVaDAbgXVz6Xpz0:b-eyp3dq) ([raw file](https://github.com/starkware-libs/cairo/blob/cdcf4b91aa72c7403ec496f1b7ae07e8af77b7e0/crates/cairo-lang-semantic/src/items/generics.rs#L397)):*
> ```XML
>         }
>         ast::GenericParam::NegativeImpl(_) => {
>             unreachable!("This should be unreachable.")
> ```

Have a why instead of rephrasing the `unreachable` part.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4460)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/neg_impl` line 27 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4460#-Njw6exn-4EYCb4u8hkc:-NjwSIhb-G2b04zQVeKW:b-unc937) ([raw file](https://github.com/starkware-libs/cairo/blob/cdcf4b91aa72c7403ec496f1b7ae07e8af77b7e0/crates/cairo-lang-semantic/src/diagnostic_test_data/neg_impl#L27)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

hmm - lets hold on that for now - i think it is fine that you'd have to be named if you use them non-last.
</blockquote></details>

Ok, so annonymouls can't follow negative impls, right?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 397 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4460#-NjwHJVaDAbgXVz6Xpz-:-NjwSWIvDkzwPDa_gK7O:b-p0w2pu) ([raw file](https://github.com/starkware-libs/cairo/blob/cdcf4b91aa72c7403ec496f1b7ae07e8af77b7e0/crates/cairo-lang-semantic/src/items/generics.rs#L397)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Have a why instead of rephrasing the `unreachable` part.
</blockquote></details>

is the following ok:
Negative impls are not considered as semantic parameters as they don't accept arguments.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4460)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/neg_impl` line 27 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4460#-Njw6exn-4EYCb4u8hkc:-NjwmIg_AQuUZVM8qCfu:bxd1i6p) ([raw file](https://github.com/starkware-libs/cairo/blob/cdcf4b91aa72c7403ec496f1b7ae07e8af77b7e0/crates/cairo-lang-semantic/src/diagnostic_test_data/neg_impl#L27)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Ok, so annonymouls can't follow negative impls, right?
</blockquote></details>

they can - but if you pass them as args you'd need to do something like:
`Trait<felt252, _, SomeImpl>`
___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 397 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4460#-NjwHJVaDAbgXVz6Xpz-:-NjwmeS8EU08buc-4TnF:b-27n403) ([raw file](https://github.com/starkware-libs/cairo/blob/cdcf4b91aa72c7403ec496f1b7ae07e8af77b7e0/crates/cairo-lang-semantic/src/items/generics.rs#L397)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

is the following ok:
Negative impls are not considered as semantic parameters as they don't accept arguments.
</blockquote></details>

this explains `why` you don't want to support it here - not what handles it to make sure this is never reached.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 397 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4460#-NjwHJVaDAbgXVz6Xpz-:-Njwvy_g-M7uyUvtIU5S:bcezgm0) ([raw file](https://github.com/starkware-libs/cairo/blob/cdcf4b91aa72c7403ec496f1b7ae07e8af77b7e0/crates/cairo-lang-semantic/src/items/generics.rs#L397)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this explains `why` you don't want to support it here - not what handles it to make sure this is never reached.
</blockquote></details>

removed `unreachable!`

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4460)* status: 17 of 20 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 63 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4460#-NkB18a_-x4clzacjwSB:-NkEn6ta5WNuFh-vuNe-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9493e0943285b8df7a05c369c71ab9cfe8955319/crates/cairo-lang-semantic/src/items/generics.rs#L63)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is possibly unreachable (after semantic support) - but please make sure.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4460)* status: 17 of 20 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 751 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4460#-NkB0z942TZp7ZkkMJ7g:-NkEne3J05MDItuciz2N:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9493e0943285b8df7a05c369c71ab9cfe8955319/crates/cairo-lang-semantic/src/resolve/mod.rs#L751)):*
> ```XML
>                 GenericKind::NegImpl => {
>                     return None;
>                 }
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4460)* status: 19 of 20 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/neg_impl` line 4 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4460#-NkEy_vD5yexOuTnFJVZ:-NkEy_vD5yexOuTnFJV_:b-q6yf9q) ([raw file](https://github.com/starkware-libs/cairo/blob/834bdcbc52ab34dc4aa6e7651daf99e5a36152ac/crates/cairo-lang-semantic/src/diagnostic_test_data/neg_impl#L4)):*
> ```
> 
> //! > test_comments
> // TODO(spapini): Remove duplicated diagnostics.
> ```

which duplicated diagnostics?
___
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/neg_impl` line 48 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4460#-NkEymOG3qNEZLo9iD0W:-NkEymOG3qNEZLo9iD0X:bkkabe1) ([raw file](https://github.com/starkware-libs/cairo/blob/834bdcbc52ab34dc4aa6e7651daf99e5a36152ac/crates/cairo-lang-semantic/src/diagnostic_test_data/neg_impl#L48)):*
> ```
>                     ^******^
> 
> error: Only `_` is a valid for neg impls
> ```

they aren't? or just - not yet?
___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 63 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4460#-NkEyvcVBe1Gh5yPq3h_:-NkEyvcVBe1Gh5yPq3ha:b-43989t) ([raw file](https://github.com/starkware-libs/cairo/blob/834bdcbc52ab34dc4aa6e7651daf99e5a36152ac/crates/cairo-lang-semantic/src/items/generics.rs#L63)):*
> ```XML
>             GenericArgumentId::Literal(_) => GenericArgumentHead::Const,
>             GenericArgumentId::Impl(impl_id) => GenericArgumentHead::Impl(impl_id.head(db)?),
>             // TODO(ilya): Do we need filtering for negative impls?
> ```

Please make sure you remove this by the end of this PR stack.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/neg_impl` line 48 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4460#-NkEymOG3qNEZLo9iD0W:-NkF-Ys38GYT8B6ybJCm:brckj1x) ([raw file](https://github.com/starkware-libs/cairo/blob/834bdcbc52ab34dc4aa6e7651daf99e5a36152ac/crates/cairo-lang-semantic/src/diagnostic_test_data/neg_impl#L48)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

they aren't? or just - not yet?
</blockquote></details>

Only `_` is a valid

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 63 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4460#-NkEyvcVBe1Gh5yPq3h_:-NkF-do99lBxpdgOUDf6:b-q1p9zj) ([raw file](https://github.com/starkware-libs/cairo/blob/834bdcbc52ab34dc4aa6e7651daf99e5a36152ac/crates/cairo-lang-semantic/src/items/generics.rs#L63)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Please make sure you remove this by the end of this PR stack.
</blockquote></details>

why?

how can I tell if filtering is needed?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4460)* status: 19 of 20 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/neg_impl` line 48 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4460#-NkEymOG3qNEZLo9iD0W:-NkFA7lj19_2hIaTT_w8:bls5lqy) ([raw file](https://github.com/starkware-libs/cairo/blob/834bdcbc52ab34dc4aa6e7651daf99e5a36152ac/crates/cairo-lang-semantic/src/diagnostic_test_data/neg_impl#L48)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why not?
</blockquote></details>

discussed f2f.
___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 63 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4460#-NkEyvcVBe1Gh5yPq3h_:-NkFHIaV-e4qEoOITUwG:bls5lqy) ([raw file](https://github.com/starkware-libs/cairo/blob/834bdcbc52ab34dc4aa6e7651daf99e5a36152ac/crates/cairo-lang-semantic/src/items/generics.rs#L63)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

When is a candidate viable?
</blockquote></details>

discussed f2f.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4460)* status: 16 of 20 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/neg_impl` line 48 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4460#-NkEymOG3qNEZLo9iD0W:-NkFPsg4-xB8VM63QZ45:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/834bdcbc52ab34dc4aa6e7651daf99e5a36152ac/crates/cairo-lang-semantic/src/diagnostic_test_data/neg_impl#L48)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

discussed f2f.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4460#-:-NkFX8WFBANjIbPWDBTl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4460)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
