### PR TITLE
Linear types

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2688)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2685** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2685" target="_blank">Graphite</a> 
    * **PR #2688** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2688" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2688?utm_source=stack-comment).

**Comment by ilyalesokhin-starkware** [comment]
*[`docs/reference/src/linear-types.adoc` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2688#-NS117i700r2UBHchv2T:-NS117i700r2UBHchv2U:b-10hyq6) ([raw file](https://github.com/starkware-libs/cairo/blob/b2679edc672d3194674c4a0f11600073776e1e4e/docs/reference/src/linear-types.adoc#L19)):*
> ```AsciiDoc
> ```
> 
> To allow a value to be used multiple times, the `Copy` trait must be implemented for it.
> ```

I think you should also mention Clone.
and say that Copy allows implicit Clone.



_Code quote:_
```AsciiDoc
To allow a value to be used multiple times, the `Copy` trait must be implemented for it.
For example, the following code compiles:
```

**Comment by ilyalesokhin-starkware** [comment]
*[`docs/reference/src/linear-types.adoc` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2688#-NS11QIz58GwIRDfir7b:-NS11QIz58GwIRDfir7c:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b2679edc672d3194674c4a0f11600073776e1e4e/docs/reference/src/linear-types.adoc#L36)):*
> ```AsciiDoc
> 
> == Variable dropping.
> An unmoved variable may not go out of scope. For example, the following code does not compile:
> ```





_Suggestion:_
```AsciiDoc
A variable of a type that does not implement Drop.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`docs/reference/src/linear-types.adoc` line 63 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2688#-NS14V2_-PGKynUPhFHX:-NS14V2_-PGKynUPhFHY:bpidep6) ([raw file](https://github.com/starkware-libs/cairo/blob/b2679edc672d3194674c4a0f11600073776e1e4e/docs/reference/src/linear-types.adoc#L63)):*
> ```AsciiDoc
> For example, a value containing a `Dict` cannot be dropped, but we can still deconstruct it by
> squashing it with `.squash()`.
> This can be done by implementing or deriving the `Destruct` trait, which will be called
> ```

the relation ship between Destruct and squash is not clear.



_Code quote:_
```AsciiDoc
`Destruct` trait,
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2688)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @ilyalesokhin-starkware)

___
*[`docs/reference/src/linear-types.adoc` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2688#-NS117i700r2UBHchv2T:-NS14oB-9Hld-H9G36js:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b2679edc672d3194674c4a0f11600073776e1e4e/docs/reference/src/linear-types.adoc#L19)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I think you should also mention Clone.
and say that Copy allows implicit Clone.
</blockquote></details>

Done.
___
*[`docs/reference/src/linear-types.adoc` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2688#-NS11QIz58GwIRDfir7b:-NS14iHq5nDLaHw5-SH1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b2679edc672d3194674c4a0f11600073776e1e4e/docs/reference/src/linear-types.adoc#L36)):*
> ```AsciiDoc
> 
> == Variable dropping.
> An unmoved variable may not go out of scope. For example, the following code does not compile:
> ```

Done.
___
*[`docs/reference/src/linear-types.adoc` line 63 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2688#-NS14V2_-PGKynUPhFHX:-NS14nGH0boEzqv-queX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b2679edc672d3194674c4a0f11600073776e1e4e/docs/reference/src/linear-types.adoc#L63)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

the relation ship between Destruct and squash is not clear.
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`docs/reference/src/linear-types.adoc` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2688#-NS11QIz58GwIRDfir7b:-NS15DaU9iSGmUK13Mjw:bxbssjt) ([raw file](https://github.com/starkware-libs/cairo/blob/b2679edc672d3194674c4a0f11600073776e1e4e/docs/reference/src/linear-types.adoc#L36)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

what is an unmoved variable?



_Code quote:_
```AsciiDoc
unmoved va
```

**Comment by ilyalesokhin-starkware** [comment]
*[`docs/reference/src/linear-types.adoc` line 74 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2688#-NS16Dl3DBUa1HDv__-5:-NS16Dl3DBUa1HDv__-6:b-mqg1cd) ([raw file](https://github.com/starkware-libs/cairo/blob/05a17f47789d3fc44ba6f7d8b9c8b139079d2f09/docs/reference/src/linear-types.adoc#L74)):*
> ```AsciiDoc
> 
> ```rust
> #[derive(Destruct)]
> ```

What happens when you derive from Destruct?

Does it call Destruct on all the inner fields.

Mention that each type implements drop also implements destruct.



_Code quote:_
```AsciiDoc
#[derive(Destruct)]
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2688)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @ilyalesokhin-starkware)

___
*[`docs/reference/src/linear-types.adoc` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2688#-NS11QIz58GwIRDfir7b:-NS16oOjBVVWf9YBxy0_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b2679edc672d3194674c4a0f11600073776e1e4e/docs/reference/src/linear-types.adoc#L36)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what is an unmoved variable?
</blockquote></details>

Done.
___
*[`docs/reference/src/linear-types.adoc` line 74 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2688#-NS16Dl3DBUa1HDv__-5:-NS176GA38t22nlfDKzo:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/05a17f47789d3fc44ba6f7d8b9c8b139079d2f09/docs/reference/src/linear-types.adoc#L74)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

What happens when you derive from Destruct?

Does it call Destruct on all the inner fields.

Mention that each type implements drop also implements destruct.
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`docs/reference/src/linear-types.adoc` line 107 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2688#-NS19XOeC2OTnADKvb4x:-NS19XOf96z0Ekmk7R0D:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/05a17f47789d3fc44ba6f7d8b9c8b139079d2f09/docs/reference/src/linear-types.adoc#L107)):*
> ```AsciiDoc
>         (e.g. `impl TCopy: Copy<T>`).
> * How to avoid "Value was not dropped" errors?
>     * Find the corresponding function that
> ```





_Suggestion:_
```AsciiDoc
Find a function that can be used to destroy.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`docs/reference/src/linear-types.adoc` line 112 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2688#-NS19qVnDGIiGUYBrDXv:-NS19qVnDGIiGUYBrDXw:bsui5v9) ([raw file](https://github.com/starkware-libs/cairo/blob/05a17f47789d3fc44ba6f7d8b9c8b139079d2f09/docs/reference/src/linear-types.adoc#L112)):*
> ```AsciiDoc
>     * For structs, deconstruct them using `let A { .. } = a;`.
>     * For enums, deconstruct them using `match`.
>     * In particular, for the 'never' type, match like this: `match x {}`.
> ```

when is this used?



_Code quote:_
```AsciiDoc
 * In particular, for the 'never' type, match like this: `match x {}`.
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2688)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware and @ilyalesokhin-starkware)

___
*[`docs/reference/src/linear-types.adoc` line 112 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2688#-NS19qVnDGIiGUYBrDXv:-NS1BCO26u9kU51Fqluh:b-7au113) ([raw file](https://github.com/starkware-libs/cairo/blob/05a17f47789d3fc44ba6f7d8b9c8b139079d2f09/docs/reference/src/linear-types.adoc#L112)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

when is this used?
</blockquote></details>

When you have the never type, and don't do anything with it, for example:
```
impl MyClone of Clone<A>{
  fn clone(@self: A) -> A {
    match panic_with_felt(5) {}
  }
}
```

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2688#-:-NS1BdaVBSstGk_0JIe8:bnfp4nl)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2688)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`docs/reference/src/linear-types.adoc` line 107 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2688#-NS19XOeC2OTnADKvb4x:-NS1DMxq7qNWlQ3djlUU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/05a17f47789d3fc44ba6f7d8b9c8b139079d2f09/docs/reference/src/linear-types.adoc#L107)):*
> ```AsciiDoc
>         (e.g. `impl TCopy: Copy<T>`).
> * How to avoid "Value was not dropped" errors?
>     * Find the corresponding function that
> ```

Done.

**Pull request merged**
