### PR TITLE
Coupons: Add __coupon__ argument to function call (ignored in lowering).

### PR DESCRIPTION
**Pull request by liorgold2**
**Stack**:
- #4602
- #4601 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4601)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4601)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/coupon` line 8 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4601#-Nm0oxqd4LOjnq1lsqjY:-Nm0oxqd4LOjnq1lsqjZ:b-emsb1c) ([raw file](https://github.com/starkware-libs/cairo/blob/330d59faf5164bc28e445697a9734d19bddf7d66/crates/cairo-lang-semantic/src/expr/semantic_test_data/coupon#L8)):*
> ```
> //! > module_code
> fn foo(x: u8) {6;}
> fn get_coupon() -> foo::Coupon {}
> ```

to avoid the error.



_Suggestion:_
```
extern fn get_coupon() -> foo::Coupon nopanic;
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4601)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/coupon` line 8 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4601#-Nm0oxqd4LOjnq1lsqjY:-Nm0q2He3yncKfVi7NUK:b-qtl4bs) ([raw file](https://github.com/starkware-libs/cairo/blob/330d59faf5164bc28e445697a9734d19bddf7d66/crates/cairo-lang-semantic/src/expr/semantic_test_data/coupon#L8)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

to avoid the error.
</blockquote></details>

Done. Nice.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4601#-:-Nm0sVMvB4Jz4GmwCxJT:bnfp4nl)* status: 14 of 15 files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4601)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @liorgold2)

**Pull request merged**
