### PR TITLE
Introduce `ExprInlineMacro` expression

### PR DESCRIPTION
**Pull request by tarrencev**
Updates spec to include `ExprInlineMacro` to support `print!(...)` syntax.

commit-id:a366d0c3

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2770)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2770)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @tarrencev)

___
*[`crates/cairo-lang-syntax-codegen/src/cairo_spec.rs` line 186 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2770#-NSpX3zK8Ch18efXfFAE:-NSpX3zK8Ch18efXfFAF:b-mzsgg5) ([raw file](https://github.com/starkware-libs/cairo/blob/c2e4df7af448bd049b438ea22c1139a2b8f1bdcc/crates/cairo-lang-syntax-codegen/src/cairo_spec.rs#L186)):*
> ```XML
>         .node("name", "TerminalIdentifier")
>         .node("bang", "TerminalNot")
>         .node("arguments", "ArgListParenthesized")
> ```

I don't think this is the right node to use. We want a token tree i believe 
Add an enum node TokenTree that is either Braces, Parenthesis or a TerminalAny.
For example, braces node will be

Lbrace
TotkentreeList
Rbrace.

Add a new terminal-and-token for TokenAny.

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2770)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-syntax-codegen/src/cairo_spec.rs` line 186 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2770#-NSpX3zK8Ch18efXfFAE:-NSpYgNm45I-wu_IS-lV:b-qwc58q) ([raw file](https://github.com/starkware-libs/cairo/blob/c2e4df7af448bd049b438ea22c1139a2b8f1bdcc/crates/cairo-lang-syntax-codegen/src/cairo_spec.rs#L186)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I don't think this is the right node to use. We want a token tree i believe 
Add an enum node TokenTree that is either Braces, Parenthesis or a TerminalAny.
For example, braces node will be

Lbrace
TotkentreeList
Rbrace.

Add a new terminal-and-token for TokenAny.
</blockquote></details>

Token trees are more complex beasts than this, especially parser-wise, that's why I have ignored them in my attributes work. I think initially, we could be fine with having really function-like macros...

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2770)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

**Comment by spapinistarkware** [comment]
https://doc.rust-lang.org/proc_macro/enum.TokenTree.html

Seems easy enough.
Changing later would mean breaking changes, and I see no reason to do that.

It's *really* easy to do token tree.

**Review by tarrencev — COMMENTED** [review]
Ok taking a look!

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2770#-:-NSqeSwe2eZJv-zZWQUE:b7e2ow6)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @mkaput and @spapinistarkware)

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2770)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @mkaput and @tarrencev)

___
*[`crates/cairo-lang-syntax-codegen/src/cairo_spec.rs` line 207 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2770#-NSrKQho82l8ofS7u9zA:-NSrKQho82l8ofS7u9zB:bkz2v8y) ([raw file](https://github.com/starkware-libs/cairo/blob/bec9058df2a4fd791d4b036f9fddb14ee62573d9/crates/cairo-lang-syntax-codegen/src/cairo_spec.rs#L207)):*
> ```XML
>         .node("name", "TerminalIdentifier")
>         .node("bang", "TerminalNot")
>         .node("arguments", "ArgListParenthesized")
> ```

TokenTree

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2770)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @mkaput and @tarrencev)

___
*[`crates/cairo-lang-syntax-codegen/src/cairo_spec.rs` line 134 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2770#-NSrKVOMEF64ocyJicTy:-NSrKVOMEF64ocyJicTz:bldmeq6) ([raw file](https://github.com/starkware-libs/cairo/blob/bec9058df2a4fd791d4b036f9fddb14ee62573d9/crates/cairo-lang-syntax-codegen/src/cairo_spec.rs#L134)):*
> ```XML
>         .node("rparen", "TerminalRParen")
>     )
>     .add_separated_list("TokenTreeItems", "Expr", "TerminalComma")
> ```

Expr -> TerminalAny.
Add it below with the other terminals.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2770)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @mkaput and @tarrencev)

___
*[`crates/cairo-lang-syntax-codegen/src/cairo_spec.rs` line 133 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2770#-NSt47mxDvPJ8OyieVj5:-NSt47myAXoYSvEJ2KrP:bu9hhb0) ([raw file](https://github.com/starkware-libs/cairo/blob/300e11c744cbeeb69e7c517402e43a47b0c9d0cb/crates/cairo-lang-syntax-codegen/src/cairo_spec.rs#L133)):*
> ```XML
>         .node("args", "ArgList")
>         .node("rparen", "TerminalRParen")
>     )
> ```

Use a regular list, not a separated list

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2770)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @mkaput and @tarrencev)

**Review by mkaput — COMMENTED** [review]
I will still stand against token trees: they seem to be easy on the surface -- but only for the compiler! With them, macros will have to come up with their own Cairo parser if they would like to process anything more complex in their arguments, see `syn` and `darling` crates in Rust. Token trees are also harder to grasp by editors, stuff like selection expanding, code completion etc. is harder because again, you lose a lot of syntactic meaning.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2770#-:-NStTKD0CLNVXGPnP0Go:b-1eq92)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware and @tarrencev)

**Review by spapinistarkware — COMMENTED** [review]
Ok, I'm convinced. Sorry for the back and forth @tarrencev. Can you revert it to a simple arg list?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2770#-:-NStfjFIBlva_i-uQRwo:bmioc0c)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @mkaput and @tarrencev)

**Review by mkaput — COMMENTED** [review]
To note, technically we could redo our parser to be also able to work on token streams (so that for Cairo the same parser would fulfil the roles of rustc's parser and `syn` crate), but this definitely is a topic for future consideration, not for this PR :smiley: 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2770#-:-NSthe3HAWb45yw5AL91:b-wvewwi)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware and @tarrencev)

**Review by tarrencev — COMMENTED** [review]
Ok I've reverted to the original implementation 😄

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2770#-:-NSuF5mw-86bGJK9FUA_:b-ofsb67)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @mkaput and @spapinistarkware)

**Review by mkaput — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2770#-:-NSuFmISAvunQ8GPAdqx:bnfp4nl)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware and @tarrencev)

**Review by mkaput — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2770)* status: all files reviewed, 3 unresolved discussions (waiting on @spapinistarkware and @tarrencev)

**Review by mkaput — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2770)* status: all files reviewed, 3 unresolved discussions (waiting on @mkaput, @spapinistarkware, and @tarrencev)

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2770)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mkaput and @spapinistarkware)

**Review by spapinistarkware — APPROVED** [review]

**Pull request merged**
