### PR TITLE
Fix diagnostics for length 1 cycles.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2307)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2307)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/tests` line 212 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2307#-NPMQkVS2Hw_QFPihNli:-NPMQkVS2Hw_QFPihNlj:b418t46) ([raw file](https://github.com/starkware-libs/cairo/blob/4fc3601a9f1f801009c2e34cdb5e9ef537b75591/crates/cairo-lang-semantic/src/diagnostic_test_data/tests#L212)):*
> ```
> error: Identifier not found.
>  --> lib.cairo:1:5
> use self;
> ```

do we support `self` in use? if so this is an annoying special case :(



_Code quote:_
```
self;
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2307#-:-NPMQvKd2o-C4vFI_ydl:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2307)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/items/us.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2307#-NPMWicT3uRrdSH5jnJm:-NPMWicT3uRrdSH5jnJn:b-imw1no) ([raw file](https://github.com/starkware-libs/cairo/blob/4fc3601a9f1f801009c2e34cdb5e9ef537b75591/crates/cairo-lang-semantic/src/items/us.rs#L59)):*
> ```XML
>             SemanticDiagnosticKind::PathNotFound(NotFoundItemType::Identifier)
>         } else {
>             SemanticDiagnosticKind::UseCycle
> ```

I'm not sure how to test this.

Apparently there is no cycle in:
mod A {
  use A::c;
}

mod B {
  use A::c; 
}
use A::c;



_Code quote:_
```XML
  SemanticDiagnosticKind::UseCycle
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/items/us.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2307#-NPMWicT3uRrdSH5jnJm:-NPMlbfh9L9P-6GR9vWM:bl32g9a) ([raw file](https://github.com/starkware-libs/cairo/blob/4fc3601a9f1f801009c2e34cdb5e9ef537b75591/crates/cairo-lang-semantic/src/items/us.rs#L59)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I'm not sure how to test this.

Apparently there is no cycle in:
mod A {
  use A::c;
}

mod B {
  use A::c; 
}
use A::c;


</blockquote></details>

I was unable to test this from the testing framework as the diagnostics is on the inner modules.
but it works from the command line.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2307)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/tests` line 212 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2307#-NPMQkVS2Hw_QFPihNli:-NPMm8dO19lU2bY5ztQv:brpmqc3) ([raw file](https://github.com/starkware-libs/cairo/blob/4fc3601a9f1f801009c2e34cdb5e9ef537b75591/crates/cairo-lang-semantic/src/diagnostic_test_data/tests#L212)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

do we support `self` in use? if so this is an annoying special case :(
</blockquote></details>

removed.
___
*[`crates/cairo-lang-semantic/src/items/us.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2307#-NPMWicT3uRrdSH5jnJm:-NPMn09E3zxuLwEp3FrE:bezd3uk) ([raw file](https://github.com/starkware-libs/cairo/blob/4fc3601a9f1f801009c2e34cdb5e9ef537b75591/crates/cairo-lang-semantic/src/items/us.rs#L59)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I was unable to test this from the testing framework as the diagnostics is on the inner modules.
but it works from the command line.
</blockquote></details>

nvm, found a way to trigger the diagnostics.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2307)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/tests` line 212 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2307#-NPMQkVS2Hw_QFPihNli:-NPMn8RE03GI71NI7n8V:b-b3yx9g) ([raw file](https://github.com/starkware-libs/cairo/blob/4fc3601a9f1f801009c2e34cdb5e9ef537b75591/crates/cairo-lang-semantic/src/diagnostic_test_data/tests#L212)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

removed.
</blockquote></details>

fixed the test.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2307)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2307)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/tests` line 236 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2307#-NPMoYGp9E4o7IS-RhPK:-NPMoYGp9E4o7IS-RhPL:b-oz8wiu) ([raw file](https://github.com/starkware-libs/cairo/blob/47334664950e96f90f25c7b86aba2ae663f38a2d/crates/cairo-lang-semantic/src/diagnostic_test_data/tests#L236)):*
> ```
> 
> //! > expected_diagnostics
> error: Identifier not found.
> ```

Should this be `crate not found`?



_Code quote:_
```
Identifier not found
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2307)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/tests` line 236 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2307#-NPMoYGp9E4o7IS-RhPK:-NPMouT_AVsDgVYV6iad:bgiqhz) ([raw file](https://github.com/starkware-libs/cairo/blob/47334664950e96f90f25c7b86aba2ae663f38a2d/crates/cairo-lang-semantic/src/diagnostic_test_data/tests#L236)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Should this be `crate not found`?
</blockquote></details>

rust give:

error[E0432]: unresolved import `abc`
   --> crates/cairo-lang-semantic/src/diagnostic.rs:796:5
    |
796 | use abc;
    |     ^^^ no external crate `abc`



_Code quote:_
```
use bad_module_name;
```

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2307#-:-NPNPJNV2md6ezOUhbWq:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2307)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/tests` line 236 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2307#-NPMoYGp9E4o7IS-RhPK:-NPNQGRa14B4w6vl4hw6:bku0ect) ([raw file](https://github.com/starkware-libs/cairo/blob/47334664950e96f90f25c7b86aba2ae663f38a2d/crates/cairo-lang-semantic/src/diagnostic_test_data/tests#L236)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

rust give:

error[E0432]: unresolved import `abc`
   --> crates/cairo-lang-semantic/src/diagnostic.rs:796:5
    |
796 | use abc;
    |     ^^^ no external crate `abc`
</blockquote></details>

I think it may be nice - but it requires understanding why you can't find the path, but this isn't trivial.
I find it fine for now

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2307)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/tests` line 236 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2307#-NPMoYGp9E4o7IS-RhPK:-NPNSgHK6wkVoS0kScSc:b-1icz0y) ([raw file](https://github.com/starkware-libs/cairo/blob/47334664950e96f90f25c7b86aba2ae663f38a2d/crates/cairo-lang-semantic/src/diagnostic_test_data/tests#L236)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I think it may be nice - but it requires understanding why you can't find the path, but this isn't trivial.
I find it fine for now
</blockquote></details>

The suggestion is to always give that error for cycles of length 1.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2307)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
