### PR TITLE
Add TxInfo struct.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2145)

### CODE REVIEW

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2145)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`corelib/starknet.cairo` line 11 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2145#-NOOsRBe6ewj9OiRf4ba:-NOOsRBe6ewj9OiRf4bb:b-ucq43n) ([raw file](https://github.com/starkware-libs/cairo/blob/ff5656eae7f3aa1c42175efa96f466e669d65a66/corelib/starknet.cairo#L11)):*
> ```Cairo
> extern type ContractAddress;
> 
> struct TxInfo {
> ```

Implement Copy and Drop - this would have caught the completeness issue with the array.
___
*[`corelib/starknet.cairo` line 25 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2145#-NOOsHa42Two2URkAgOV:-NOOsHa42Two2URkAgOW:b-elkr0g) ([raw file](https://github.com/starkware-libs/cairo/blob/ff5656eae7f3aa1c42175efa96f466e669d65a66/corelib/starknet.cairo#L25)):*
> ```Cairo
> 
>     // The signature of the transaction.
>     signature: Array::<felt>,
> ```

This should be a span, not an array. People shouldn't be allowed to push values to it.

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/starknet.cairo` line 11 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2145#-NOOsRBe6ewj9OiRf4ba:-NOOsvO6DNxPPHqAqMkm:b-tbso0b) ([raw file](https://github.com/starkware-libs/cairo/blob/ff5656eae7f3aa1c42175efa96f466e669d65a66/corelib/starknet.cairo#L11)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Implement Copy and Drop - this would have caught the completeness issue with the array.
</blockquote></details>

what is the completeness issue with the array.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2145)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

___
*[`corelib/starknet.cairo` line 25 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2145#-NOOsHa42Two2URkAgOV:-NOOszfe81jJ7JCL7sIY:b-mzdwb3) ([raw file](https://github.com/starkware-libs/cairo/blob/ff5656eae7f3aa1c42175efa96f466e669d65a66/corelib/starknet.cairo#L25)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

This should be a span, not an array. People shouldn't be allowed to push values to it.
</blockquote></details>

we don't have a span :(

how to do you want to proceed?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2145)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

___
*[`corelib/starknet.cairo` line 11 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2145#-NOOsRBe6ewj9OiRf4ba:-NOcYicc2W1E3CJvplww:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/ff5656eae7f3aa1c42175efa96f466e669d65a66/corelib/starknet.cairo#L11)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what is the completeness issue with the array.
</blockquote></details>

?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2145)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

___
*[`corelib/starknet.cairo` line 11 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2145#-NOOsRBe6ewj9OiRf4ba:-NOcZ0a82BBr-DSzAxV5:bwogwk3) ([raw file](https://github.com/starkware-libs/cairo/blob/ff5656eae7f3aa1c42175efa96f466e669d65a66/corelib/starknet.cairo#L11)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

?
</blockquote></details>

+ how do I implement them?

just
#[derive(Copy, Drop)] 
above the struct?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2145)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

___
*[`corelib/starknet.cairo` line 11 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2145#-NOOsRBe6ewj9OiRf4ba:-NOcdriPC25M-N1tMkgb:brfte7w) ([raw file](https://github.com/starkware-libs/cairo/blob/ff5656eae7f3aa1c42175efa96f466e669d65a66/corelib/starknet.cairo#L11)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

+ how do I implement them?

just
#[derive(Copy, Drop)] 
above the struct?
</blockquote></details>

it give me:
error: Invalid copy trait implementation.
 --> impls:1:1
impl TxInfoCopy of Copy::<TxInfo>;
^********************************^

error: Invalid drop trait implementation.
 --> impls:2:1
impl TxInfoDrop of Drop::<TxInfo>;
^********************************^

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2145)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`corelib/starknet.cairo` line 11 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2145#-NOOsRBe6ewj9OiRf4ba:-NOdZYKxCLKgm8PCvz0J:b-yc7nmu) ([raw file](https://github.com/starkware-libs/cairo/blob/ff5656eae7f3aa1c42175efa96f466e669d65a66/corelib/starknet.cairo#L11)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it give me:
error: Invalid copy trait implementation.
 --> impls:1:1
impl TxInfoCopy of Copy::<TxInfo>;
^********************************^

error: Invalid drop trait implementation.
 --> impls:2:1
impl TxInfoDrop of Drop::<TxInfo>;
^********************************^
</blockquote></details>

There is a requiement we have Drop and Dup for all fields. Is it fulfilled?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2145)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

___
*[`corelib/starknet.cairo` line 11 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2145#-NOOsRBe6ewj9OiRf4ba:-NOdej7Z6M__EQYt3M8y:b-a7hwva) ([raw file](https://github.com/starkware-libs/cairo/blob/ff5656eae7f3aa1c42175efa96f466e669d65a66/corelib/starknet.cairo#L11)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

There is a requiement we have Drop and Dup for all fields. Is it fulfilled?
</blockquote></details>

Now it is.

though I have to add that it is not clear from the error message

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2145)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

___
*[`corelib/starknet.cairo` line 25 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2145#-NOOsHa42Two2URkAgOV:-NOdenrj8CCZ9ka0f55p:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/ff5656eae7f3aa1c42175efa96f466e669d65a66/corelib/starknet.cairo#L25)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

we don't have a span :(

how to do you want to proceed?
</blockquote></details>

done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2145#-:-NOdryO73iDSNGplZn6d:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2)

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2145#-:-NOe9ciDC5XgO2mE2yEn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
