### PR TITLE
Define FunctionWithBodyId with define_language_element_id_as_enum!.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1756)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1756)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/implicits.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1756#-NLa5G3v6ng2wsCBOB2r:-NLa5G3wE4P49O9_7bqZ:bpprovr) ([raw file](https://github.com/starkware-libs/cairo/blob/436db8cc9cae07fcde51e4a2c238a73f2f060977/crates/cairo-lang-lowering/src/lower/implicits.rs#L24)):*
> ```XML
>                 (FunctionWithBodyId::Free(x), FunctionWithBodyId::Free(y)) => x.cmp(y),
>                 (FunctionWithBodyId::Impl(x), FunctionWithBodyId::Impl(y)) => x.cmp(y),
>                 (FunctionWithBodyId::Free(_), FunctionWithBodyId::Impl(_)) => Ordering::Less,
> ```

can you add a function in FunctionWithBodyId that returns a pair maybe? Free can get 0 and impl 1 for the first item, and the actual ID will be the second.

(otherwise, if/when we add more variants, this match will increase a by lot)



_Code quote:_
```XML
            .min_by(|x, y| match (x, y) {
                (FunctionWithBodyId::Free(x), FunctionWithBodyId::Free(y)) => x.cmp(y),
                (FunctionWithBodyId::Impl(x), FunctionWithBodyId::Impl(y)) => x.cmp(y),
                (FunctionWithBodyId::Free(_), FunctionWithBodyId::Impl(_)) => Ordering::Less,
                (FunctionWithBodyId::Impl(_), FunctionWithBodyId::Free(_)) => Ordering::Greater,
            })
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/implicits.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1756#-NLa5G3v6ng2wsCBOB2r:-NLa731HCCoD4V3Vfllx:b-247l0v) ([raw file](https://github.com/starkware-libs/cairo/blob/436db8cc9cae07fcde51e4a2c238a73f2f060977/crates/cairo-lang-lowering/src/lower/implicits.rs#L24)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

can you add a function in FunctionWithBodyId that returns a pair maybe? Free can get 0 and impl 1 for the first item, and the actual ID will be the second.

(otherwise, if/when we add more variants, this match will increase a by lot)
</blockquote></details>

It will give you incentive to remove this code

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1756)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/implicits.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1756#-NLa5G3v6ng2wsCBOB2r:-NLaAJhh4Vi-AsBEfQ6S:bozyi8i) ([raw file](https://github.com/starkware-libs/cairo/blob/436db8cc9cae07fcde51e4a2c238a73f2f060977/crates/cairo-lang-lowering/src/lower/implicits.rs#L24)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

It will give you incentive to remove this code
</blockquote></details>

why is it bad? You anyway use the ordering of the salsa IDs here

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/implicits.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1756#-NLa5G3v6ng2wsCBOB2r:-NLo4qDeDfSIH0KweZr2:b-vee01p) ([raw file](https://github.com/starkware-libs/cairo/blob/436db8cc9cae07fcde51e4a2c238a73f2f060977/crates/cairo-lang-lowering/src/lower/implicits.rs#L24)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

why is it bad? You anyway use the ordering of the salsa IDs here
</blockquote></details>


I don't think we want it to be easy to compare SalsaIds.

Note that you put the TODO:
// TODO(yuval): remove PartialOrd, Ord once ordering stably in `function_scc_representative`

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1756)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/lower/implicits.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1756#-NLa5G3v6ng2wsCBOB2r:-NLotFwK1m_W7rUK8N1s:b-chy1dq) ([raw file](https://github.com/starkware-libs/cairo/blob/436db8cc9cae07fcde51e4a2c238a73f2f060977/crates/cairo-lang-lowering/src/lower/implicits.rs#L24)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>


I don't think we want it to be easy to compare SalsaIds.

Note that you put the TODO:
// TODO(yuval): remove PartialOrd, Ord once ordering stably in `function_scc_representative`
</blockquote></details>

I'm going to remove the ord on free_functions and add a getter to the salsa_id.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1756)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/implicits.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1756#-NLa5G3v6ng2wsCBOB2r:-NLp9nx05uFOd0JFpOT6:bxbg7xf) ([raw file](https://github.com/starkware-libs/cairo/blob/436db8cc9cae07fcde51e4a2c238a73f2f060977/crates/cairo-lang-lowering/src/lower/implicits.rs#L24)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I'm going to remove the ord on free_functions and add a getter to the salsa_id.
</blockquote></details>

Returning to you until this is done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1756)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/lower/implicits.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1756#-NLa5G3v6ng2wsCBOB2r:-NLtKx951GswalGaK89c:bgeh00d) ([raw file](https://github.com/starkware-libs/cairo/blob/436db8cc9cae07fcde51e4a2c238a73f2f060977/crates/cairo-lang-lowering/src/lower/implicits.rs#L24)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Returning to you until this is done.
</blockquote></details>

back to you.

I aggree that we don't want to have 9 cases here, but lets cross that bridge when we get there.

I think this PR is an improvement over the current situation.

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1756)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1756#-:-NLtiYwx2abdRRYy9ODt:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-defs/src/ids.rs` line 236 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1756#-NLthtLm309ZBiTNMMA5:-NLthtLm309ZBiTNMMA6:b2ngwfe) ([raw file](https://github.com/starkware-libs/cairo/blob/d274b9dc89254de6236ca5b578d0efe065f8cbf7/crates/cairo-lang-defs/src/ids.rs#L236)):*
> ```XML
> }
> 
> // A trait for getting the internal salsa::InternId of a short id object.
> ```

///

**Review by yuvalsw — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1756)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Pull request merged**
