### PR TITLE
Added a compiler version field to compiled sierra code.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2996)

### CODE REVIEW

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2996)* status: 10 of 15 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2996)* status: 11 of 15 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/felt252_serde.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2996#-NUMJvGp9Z7yH6v5mgAk:-NUMJvGp9Z7yH6v5mgAl:b5ia2l5) ([raw file](https://github.com/starkware-libs/cairo/blob/b810075c664c9ed3a45d33ad29e741d198d6159f/crates/cairo-lang-starknet/src/felt252_serde.rs#L73)):*
> ```XML
> }
> 
> /// Deserializes a Sierra program from a slice of felt252s.
> ```

Add something like:



_Suggestion:_
```XML
/// Deserializes a Sierra program from a slice of felt252s.
///
/// Returns (sierra_version_id, compiler_version_id, program).
/// See [crate::compiler_version::VersionId].
```

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 15 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2996)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/felt252_serde_test.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2996#-NUMKIuV2mWfLDk4BxTg:-NUMKIuV2mWfLDk4BxTh:b-c87f8w) ([raw file](https://github.com/starkware-libs/cairo/blob/b810075c664c9ed3a45d33ad29e741d198d6159f/crates/cairo-lang-starknet/src/felt252_serde_test.rs#L26)):*
> ```XML
>         sierra_from_felt252s(
>             &sierra_to_felt252s(
>                 compiler_version::current_sierra_version_id(),
> ```

Put dummy values here, since this is the serde test. Specifically, they should be different to make sure they are not flipped.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2996)* status: 12 of 15 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-starknet/src/felt252_serde.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2996#-NUMJvGp9Z7yH6v5mgAk:-NUMLeWQ0OkKsHVvs-5q:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b810075c664c9ed3a45d33ad29e741d198d6159f/crates/cairo-lang-starknet/src/felt252_serde.rs#L73)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Add something like:
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/felt252_serde_test.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2996#-NUMKIuV2mWfLDk4BxTg:-NUMNHeM5awOOncb2sSn:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b810075c664c9ed3a45d33ad29e741d198d6159f/crates/cairo-lang-starknet/src/felt252_serde_test.rs#L26)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Put dummy values here, since this is the serde test. Specifically, they should be different to make sure they are not flipped.
</blockquote></details>

Done.

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2996#-:-NUM_0NjDCJN6RgirhTa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
