### PR TITLE
Basic snapshot capabilities

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2089)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2089)* status: all files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 279 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2089#-NNqp4bwEH_OycH_79zZ:-NNqp4bwEH_OycH_79z_:besl56y) ([raw file](https://github.com/starkware-libs/cairo/blob/f89346dbe7e165fd46515c5a75c18a4b27c86601/crates/cairo-lang-semantic/src/corelib.rs#L279)):*
> ```XML
>         UnaryOperator::Not(_) => return unsupported_operator("!"),
> 
>         UnaryOperator::At(_) => unreachable!(),
> ```

add why.



_Code quote:_
```XML
        UnaryOperator::At(_) => unreachable!(),
```
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 487 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2089#-NNqptWJCX5AetCzGcyQ:-NNqptWJCX5AetCzGcyR:bq65sbg) ([raw file](https://github.com/starkware-libs/cairo/blob/f89346dbe7e165fd46515c5a75c18a4b27c86601/crates/cairo-lang-semantic/src/items/imp.rs#L487)):*
> ```XML
>         }
>         TypeLongId::Tuple(tys) => tys,
>         TypeLongId::Snapshot(_) => vec![],
> ```

are you sure this won't require forwarding on the wrapped type?



_Code quote:_
```XML
        TypeLongId::Snapshot(_) => vec![],
```
___
*[`crates/cairo-lang-sierra-generator/src/lifetime.rs` line 185 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2089#-NNqre15DEXRoRQDXIzI:-NNqre15DEXRoRQDXIzJ:bybat4s) ([raw file](https://github.com/starkware-libs/cairo/blob/f89346dbe7e165fd46515c5a75c18a4b27c86601/crates/cairo-lang-sierra-generator/src/lifetime.rs#L185)):*
> ```XML
>             | lowering::Statement::StructDestructure(_)
>             | lowering::Statement::EnumConstruct(_)
>             | lowering::Statement::Snapshot(_) => {}
> ```

this should still require dups and drops.



_Code quote:_
```XML
            | lowering::Statement::Snapshot(_) => {}
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2089)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 279 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2089#-NNqp4bwEH_OycH_79zZ:-NO3pVxb5DuMjt0TQogG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f89346dbe7e165fd46515c5a75c18a4b27c86601/crates/cairo-lang-semantic/src/corelib.rs#L279)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add why.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 487 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2089#-NNqptWJCX5AetCzGcyQ:-NO3pbRb7SHP_QvV1H-s:b-84z0ef) ([raw file](https://github.com/starkware-libs/cairo/blob/f89346dbe7e165fd46515c5a75c18a4b27c86601/crates/cairo-lang-semantic/src/items/imp.rs#L487)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

are you sure this won't require forwarding on the wrapped type?
</blockquote></details>

Yes. This function Dupability of inner type doesn't affect the dupability of the snapshot.
___
*[`crates/cairo-lang-sierra-generator/src/lifetime.rs` line 185 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2089#-NNqre15DEXRoRQDXIzI:-NO3puzBBEXOUXePef9C:b8guvg9) ([raw file](https://github.com/starkware-libs/cairo/blob/f89346dbe7e165fd46515c5a75c18a4b27c86601/crates/cairo-lang-sierra-generator/src/lifetime.rs#L185)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this should still require dups and drops.
</blockquote></details>

Why is introducing Similar to call, this is handled generically by statement.outputs and statement.inputs

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2089#-:-NO3ydm63f5Wro3EUEB_:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2089)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
Only reviewed part of the files...

> Reviewed 8 of 26 files at r1, 2 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2089#-:-NO40PQNDzMx4Jc1Bz-X:bw949gc)* status: all files reviewed, 6 unresolved discussions

___
*[`crates/cairo-lang-parser/src/operators.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2089#-NO3wBS6B-ojZlWbZk7a:-NO3wBS6B-ojZlWbZk7b:bdlz6wt) ([raw file](https://github.com/starkware-libs/cairo/blob/635f9e27d622b5628bddb6ea988fdbb1a16af273/crates/cairo-lang-parser/src/operators.rs#L16)):*
> ```XML
>         SyntaxKind::TerminalDot => Some(0),
> 
>         // TODO(yuval): support unary-only/non-binary operators. "not" can't be binary.
> ```

please remove this todo



_Code quote:_
```XML
SyntaxKind::TerminalNot
```
___
*[`crates/cairo-lang-parser/src/operators.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2089#-NO3wNe48baF3z-XmFye:-NO3wNe48baF3z-XmFyf:b-r7ybkg) ([raw file](https://github.com/starkware-libs/cairo/blob/635f9e27d622b5628bddb6ea988fdbb1a16af273/crates/cairo-lang-parser/src/operators.rs#L17)):*
> ```XML
> 
>         // TODO(yuval): support unary-only/non-binary operators. "not" can't be binary.
>         SyntaxKind::TerminalAt | SyntaxKind::TerminalNot => Some(1),
> ```

Add to the if in try_parse_binary_operator to avoid it as a binary operator. Please also add a test to make sure "a @ b" is not supported.



_Code quote:_
```XML
SyntaxKind::TerminalAt
```
___
*[`crates/cairo-lang-parser/src/parser.rs` line 569 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2089#-NO3xebHBccVGczg6DhE:-NO3xebHBccVGczg6DhF:b-dapr1x) ([raw file](https://github.com/starkware-libs/cairo/blob/635f9e27d622b5628bddb6ea988fdbb1a16af273/crates/cairo-lang-parser/src/parser.rs#L569)):*
> ```XML
>     }
>     /// Assumes the current token is a unary operator, and returns a GreenId of the operator.
>     fn parse_unary_operator(&mut self) -> UnaryOperatorGreen {
> ```

shouldn't this be named expect.*?



_Code quote:_
```XML
parse_unary_operator
```
___
*[`crates/cairo-lang-parser/src/parser.rs` line 684 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2089#-NO3xks26G4E0CDs8bH-:-NO3xks26G4E0CDs8bH0:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/635f9e27d622b5628bddb6ea988fdbb1a16af273/crates/cairo-lang-parser/src/parser.rs#L684)):*
> ```XML
>         match self.peek().kind {
>             SyntaxKind::TerminalAt => {
>                 let op = self.parse_unary_operator();
> ```





_Suggestion:_
```XML
self.take::<TerminalAt>().into()
```
___
*[`crates/cairo-lang-parser/src/parser.rs` line 687 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2089#-NO3yXY25A8y9d1OFC-Q:-NO3yXY25A8y9d1OFC-R:b5d5tsf) ([raw file](https://github.com/starkware-libs/cairo/blob/635f9e27d622b5628bddb6ea988fdbb1a16af273/crates/cairo-lang-parser/src/parser.rs#L687)):*
> ```XML
>                 let expr = self.try_parse_type_expr().unwrap_or_else(|| {
>                     self.create_and_report_missing::<Expr>(
>                         ParserDiagnosticKind::MissingTypeExpression,
> ```

so if we have:
`let x: @3 = 5;`
we have a "missing type expression" diagnostic?
I think it's not missing but wrong/invalid/malformed
___
*[`crates/cairo-lang-semantic/src/types.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2089#-NO4-ASP1TtkUCItoIag:-NO4-ASP1TtkUCItoIah:b-6d25h5) ([raw file](https://github.com/starkware-libs/cairo/blob/635f9e27d622b5628bddb6ea988fdbb1a16af273/crates/cairo-lang-semantic/src/types.rs#L62)):*
> ```XML
>     /// during inference.
>     Tuple(Vec<TypeId>),
>     Snapshot(TypeId),
> ```

please doc

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2089)* status: all files reviewed, 4 unresolved discussions

___
*[`crates/cairo-lang-parser/src/operators.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2089#-NO3wNe48baF3z-XmFye:-NO42Qj0-BYOpjNAAes9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/635f9e27d622b5628bddb6ea988fdbb1a16af273/crates/cairo-lang-parser/src/operators.rs#L17)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Add to the if in try_parse_binary_operator to avoid it as a binary operator. Please also add a test to make sure "a @ b" is not supported.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser.rs` line 684 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2089#-NO3xks26G4E0CDs8bH-:-NO42liO9TNB7Cfg-YZL:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/635f9e27d622b5628bddb6ea988fdbb1a16af273/crates/cairo-lang-parser/src/parser.rs#L684)):*
> ```XML
>         match self.peek().kind {
>             SyntaxKind::TerminalAt => {
>                 let op = self.parse_unary_operator();
> ```

Done.
___
*[`crates/cairo-lang-parser/src/parser.rs` line 687 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2089#-NO3yXY25A8y9d1OFC-Q:-NO43Ht-7GJZQ1L__o7A:b-h9tf60) ([raw file](https://github.com/starkware-libs/cairo/blob/635f9e27d622b5628bddb6ea988fdbb1a16af273/crates/cairo-lang-parser/src/parser.rs#L687)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

so if we have:
`let x: @3 = 5;`
we have a "missing type expression" diagnostic?
I think it's not missing but wrong/invalid/malformed
</blockquote></details>

It's the same error we have in case of `let x: 3`, in try_parse_type_lcuase

**Pull request merged**
