### PR TITLE
Support eval_circuit failure.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5709)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 9 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5709)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/circuit.rs` line 776 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5709#-NzXYed-3b3wP5JaM87e:-NzXYed-3b3wP5JaM87f:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ac796941c13c86a0bfd8adcc5fcbf99364ff8a03/crates/cairo-lang-sierra/src/extensions/modules/circuit.rs#L776)):*
> ```XML
>                                 DeferredOutputKind::AddConst { param_idx: 1 },
>                             ),
>                         },
> ```





_Suggestion:_
```XML
                        OutputVarInfo::new_builtin(add_mod_builtin_ty.clone(), 0),
                        OutputVarInfo::new_builtin(mul_mod_builtin_ty.clone(), 1),
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/circuit.rs` line 799 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5709#-NzXYsK24a_TTQ7WU9xR:-NzXYsK24a_TTQ7WU9xS:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ac796941c13c86a0bfd8adcc5fcbf99364ff8a03/crates/cairo-lang-sierra/src/extensions/modules/circuit.rs#L799)):*
> ```XML
>                                 DeferredOutputKind::AddConst { param_idx: 1 },
>                             ),
>                         },
> ```





_Suggestion:_
```XML
                        OutputVarInfo::new_builtin(add_mod_builtin_ty, 0),
                        OutputVarInfo::new_builtin(mul_mod_builtin_ty, 1),
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs` line 255 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5709#-NzXclGY-iHSeXdD7pMW:-NzXclGY-iHSeXdD7pMX:b-ppjbdk) ([raw file](https://github.com/starkware-libs/cairo/blob/ac796941c13c86a0bfd8adcc5fcbf99364ff8a03/crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs#L255)):*
> ```XML
>         let failure_mul_mod = mul_mod + mul_mod_usage;
> 
>     };
> ```

should I remove this and always consume all the mul gates?



_Code quote:_
```XML
        jump Success;
    };

    casm_build_extend! {casm_builder,
        Failure:

        const instance_size = BUILTIN_INSTANCE_SIZE;
        tempvar mul_mod_usage = computed_gates * instance_size;
        let failure_mul_mod = mul_mod + mul_mod_usage;

    };
```

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5709)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs` line 255 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5709#-NzXclGY-iHSeXdD7pMW:-NzXle3s0fZkMA2lroTL:b-613lsh) ([raw file](https://github.com/starkware-libs/cairo/blob/ac796941c13c86a0bfd8adcc5fcbf99364ff8a03/crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs#L255)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

should I remove this and always consume all the mul gates?
</blockquote></details>

sounds reasonable to me (this would also make it an actual const).
and you can return an internal handle to reuse it for the failure guarantee gate.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5709)* status: 4 of 10 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs` line 255 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5709#-NzXclGY-iHSeXdD7pMW:-NzXygCc23OBexGY6_h-:b-17mnvy) ([raw file](https://github.com/starkware-libs/cairo/blob/ac796941c13c86a0bfd8adcc5fcbf99364ff8a03/crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs#L255)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

sounds reasonable to me (this would also make it an actual const).
and you can return an internal handle to reuse it for the failure guarantee gate.
</blockquote></details>

let do this in a future PR.

**Pull request merged**
