### PR TITLE
Add signature getter for trait const and type item type

### PR DESCRIPTION
**Pull request by wawel37**
Related to [#1437](https://github.com/software-mansion/scarb/issues/1437) in scarb

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6386)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6386)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, @piotmag769, and @wawel37)

___
*[`crates/cairo-lang-doc/src/db.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6386#-O7-kVOX6ooEa7N3Jmmo:-O7-kVOYAV_7f_bl40Q2:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/4123acec1ec1a788701855f5d478a9f3c343befc/crates/cairo-lang-doc/src/db.rs#L143)):*
> ```XML
> 
>             format!("{} {}", children[1], children[2..].join(""))
>         }
> ```





_Suggestion:_
```XML
        SyntaxKind::TraitItemConstant | SyntaxKind::TraitItemType => {
            let children = db.get_children(syntax_node.clone());
            let get_text = |node| node.clone().get_text_without_trivia(db.upcast());
            format!("{} {}", get_text(&children[1]), children[2..].iter().map(get_text).join(""))
        }
```

**Review by piotmag769 — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6386)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @wawel37)

**Review by wawel37 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6386)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

___
*[`crates/cairo-lang-doc/src/db.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6386#-O7-kVOX6ooEa7N3Jmmo:-O73ZQvD4uOHyAfYC1Kg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4123acec1ec1a788701855f5d478a9f3c343befc/crates/cairo-lang-doc/src/db.rs#L143)):*
> ```XML
> 
>             format!("{} {}", children[1], children[2..].join(""))
>         }
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6386#-:-O73cGly7EkA1R4iGkmn:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @Arcticae, @Draggu, and @mkaput)

**Pull request merged**
