### PR TITLE
Refactoring hint processor to move the gas counter around.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2934)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2934)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2934#-NU1NsMzE-0MGQdzBbCg:-NU1NsMzE-0MGQdzBbCh:b-xlvl9) (no related file):*
Can you also add a simple test for failing gas in interoperability.cairo? Just to cover this flow.

___
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 269 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2934#-NU1NNeJ6mN2hociWPms:-NU1NNeJ6mN2hociWPmt:b-z42oee) ([raw file](https://github.com/starkware-libs/cairo/blob/ba1cca7858cddc6a006fc1cd6431a3f1827106fe/crates/cairo-lang-runner/src/casm_run/mod.rs#L269)):*
> ```XML
>                 let mut check_handle_oog =
>                     |res_offset: u32,
>                      handler: &mut dyn FnMut(
> ```

Can you doc these parameters?
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 425 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2934#-NU1NXUB8gfSv-jDlokQ:-NU1NXUB8gfSv-jDlokR:b-gbp0n0) ([raw file](https://github.com/starkware-libs/cairo/blob/ba1cca7858cddc6a006fc1cd6431a3f1827106fe/crates/cairo-lang-runner/src/casm_run/mod.rs#L425)):*
> ```XML
>                 } else if selector == "Deploy".as_bytes() {
>                     check_handle_oog(7, &mut |vm, gas_counter| {
>                         deduct_gas!(gas_counter, 50);
> ```

Is 50 correct? If not, fix or leave the TODO:)
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 511 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2934#-NU1NjTu4jwM65FaEYic:-NU1NjTu4jwM65FaEYid:buo9nmt) ([raw file](https://github.com/starkware-libs/cairo/blob/ba1cca7858cddc6a006fc1cd6431a3f1827106fe/crates/cairo-lang-runner/src/casm_run/mod.rs#L511)):*
> ```XML
>                 } else if selector == "CallContract".as_bytes() {
>                     check_handle_oog(6, &mut |vm, gas_counter| {
>                         deduct_gas!(gas_counter, 50);
> ```

Same here

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2934)* status: all files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 425 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2934#-NU1NXUB8gfSv-jDlokQ:-NU1OMKz9aXatQi4z3vJ:buddzhi) ([raw file](https://github.com/starkware-libs/cairo/blob/ba1cca7858cddc6a006fc1cd6431a3f1827106fe/crates/cairo-lang-runner/src/casm_run/mod.rs#L425)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Is 50 correct? If not, fix or leave the TODO:)
</blockquote></details>

these are not exactly "correct or incorrect" it is our simulation - these are the sort of decisions that may change - but not necessarily by us.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 511 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2934#-NU1NjTu4jwM65FaEYic:-NU1OY7XB-Lk7klfoQEm:bymeb5x) ([raw file](https://github.com/starkware-libs/cairo/blob/ba1cca7858cddc6a006fc1cd6431a3f1827106fe/crates/cairo-lang-runner/src/casm_run/mod.rs#L511)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

same - so still not really sure.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2934)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 269 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2934#-NU1NNeJ6mN2hociWPms:-NU1RuAN0Cf9yl9DRECt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ba1cca7858cddc6a006fc1cd6431a3f1827106fe/crates/cairo-lang-runner/src/casm_run/mod.rs#L269)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Can you doc these parameters?
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2934)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2934#-NU1NsMzE-0MGQdzBbCg:-NU1RvKz0GxgbQk_pSbf:b-896fix) (no related file):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Can you also add a simple test for failing gas in interoperability.cairo? Just to cover this flow.
</blockquote></details>

Done.

___

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2934)* status: 1 of 2 files reviewed, all discussions resolved

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2934#-:-NU1SqkM0dJdcjf5tVOO:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2934)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2934)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2934)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
