### PR TITLE
Add Generated Impl

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6149)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 9 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6149)* status: 9 of 11 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference/solver.rs` line 158 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6149#-O3bQzpt5tE82IE6tsxg:-O3bQzpt5tE82IE6tsxh:bxjr8pa) ([raw file](https://github.com/starkware-libs/cairo/blob/fe63b76c390e65bcb2d1c116c5c24319104eb241/crates/cairo-lang-semantic/src/expr/inference/solver.rs#L158)):*
> ```XML
>                 // &lookup_context).ok()
>             }
>         }
> ```

probably just remove.



_Code quote:_
```XML
        if canonical_trait.0.trait_id(db) == panic_destruct_trait(db) {
            let ty =
                extract_matches!(canonical_trait.0.generic_args(db)[0], GenericArgumentId::Type);
            if let TypeLongId::Closure(_) = db.lookup_intern_type(ty) {
                eprintln!("PanicDestruct trait with closure type: {:?}", ty.debug(db.elongate()));
                // UninferredImpl::ClosureDestructor(())
                //                  CandidateSolver::new(db, canonical_trait, candidate,
                // &lookup_context).ok()
            }
        }
```
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 308 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6149#-O3bRNjf-qKie1s-PiC0:-O3bRNjg2Gq3PichmLdp:b97zl4t) ([raw file](https://github.com/starkware-libs/cairo/blob/fe63b76c390e65bcb2d1c116c5c24319104eb241/crates/cairo-lang-semantic/src/items/imp.rs#L308)):*
> ```XML
> 
> #[derive(Copy, Clone, Debug, Hash, PartialEq, Eq, SemanticObject)]
> pub struct GeneratedImplId {
> ```

doc.

does it not require knowing where the did we get the impl from?
___
*[`crates/cairo-lang-semantic/src/items/trt.rs` line 111 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6149#-O3bRmZU3V0vkmpMnO34:-O3bRmZU3V0vkmpMnO35:bsnx7hi) ([raw file](https://github.com/starkware-libs/cairo/blob/fe63b76c390e65bcb2d1c116c5c24319104eb241/crates/cairo-lang-semantic/src/items/trt.rs#L111)):*
> ```XML
>     }
> 
>     /// Returns true if the `impl` does not depend on any generics.
> ```

fix doc.
___
*[`crates/cairo-lang-semantic/src/items/trt.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6149#-O3bRoD8ErqX5qRjo3PX:-O3bRoD8ErqX5qRjo3PY:bsnx7hi) ([raw file](https://github.com/starkware-libs/cairo/blob/fe63b76c390e65bcb2d1c116c5c24319104eb241/crates/cairo-lang-semantic/src/items/trt.rs#L119)):*
> ```XML
>     }
>     /// Returns true if the `impl` does not depend on impl or type variables.
>     pub fn is_var_free(&self, db: &dyn SemanticGroup) -> bool {
> ```

fix doc.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 308 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6149#-O3bRNjf-qKie1s-PiC0:-O3bTcoD2XSiR-ofgua2:b-5mlr0j) ([raw file](https://github.com/starkware-libs/cairo/blob/fe63b76c390e65bcb2d1c116c5c24319104eb241/crates/cairo-lang-semantic/src/items/imp.rs#L308)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc.

does it not require knowing where the did we get the impl from?
</blockquote></details>

I would expect concrete_trait to have at most 1 generated impl, so I'm not sure I need to track its origin.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6149)* status: 10 of 11 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 308 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6149#-O3bRNjf-qKie1s-PiC0:-O3bVxzHBSYwPa-0X_Xf:b7o43ui) ([raw file](https://github.com/starkware-libs/cairo/blob/fe63b76c390e65bcb2d1c116c5c24319104eb241/crates/cairo-lang-semantic/src/items/imp.rs#L308)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I would expect concrete_trait to have at most 1 generated impl, so I'm not sure I need to track its origin.
</blockquote></details>

ok - still doc.

in the doc include the fact that it is clear which impl exactly is generatedm and why.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6149#-:-O3bjThw3X7BRt_I16xQ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 1153 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6149#-O3bU5s0A2tk2JzZCqa-:-O3bjNgRAEWY9sam9lcY:bm862q8) ([raw file](https://github.com/starkware-libs/cairo/blob/fe63b76c390e65bcb2d1c116c5c24319104eb241/crates/cairo-lang-semantic/src/expr/inference.rs#L1153)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

need to `implize` associated type
</blockquote></details>

right, we can do it when we add support for associated types in generated impls.

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6149)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6149)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 308 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6149#-O3bRNjf-qKie1s-PiC0:-O3bjKpr7o5rDNHtvdyN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fe63b76c390e65bcb2d1c116c5c24319104eb241/crates/cairo-lang-semantic/src/items/imp.rs#L308)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

ok - still doc.

in the doc include the fact that it is clear which impl exactly is generatedm and why.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/trt.rs` line 111 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6149#-O3bRmZU3V0vkmpMnO34:-O3bUCPH6jlc9Lxbd1uV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fe63b76c390e65bcb2d1c116c5c24319104eb241/crates/cairo-lang-semantic/src/items/trt.rs#L111)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix doc.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/trt.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6149#-O3bRoD8ErqX5qRjo3PX:-O3bUCFo6l1PaTOYGtnJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fe63b76c390e65bcb2d1c116c5c24319104eb241/crates/cairo-lang-semantic/src/items/trt.rs#L119)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix doc.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/inference/solver.rs` line 158 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6149#-O3bQzpt5tE82IE6tsxg:-O3bcLRVDGK5puctESg9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fe63b76c390e65bcb2d1c116c5c24319104eb241/crates/cairo-lang-semantic/src/expr/inference/solver.rs#L158)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

probably just remove.
</blockquote></details>

Done.

**Review by TomerStarkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6149#-:-O3buyl12A7TUWECz9yD:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
