### PR TITLE
Implement bool-NOT

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
Signed-off-by: Dori Medini <dori@starkware.co>

---

**Stack**:
- #1326 ⬅
- #1325

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1326)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 7 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1326)* status: 7 of 12 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/sierra_ap_change/src/core_libfunc_ap_change.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1326#-NJFknXzA9tgPwv3_F8a:-NJFknY-DpYwvORbG-Eu:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ffb34aaee4790685928307bbb320b41547034b19/crates/sierra_ap_change/src/core_libfunc_ap_change.rs#L29)):*
> ```XML
>         CoreConcreteLibFunc::Bool(libfunc) => match libfunc {
>             BoolConcreteLibFunc::And(_) => vec![ApChange::Known(0)],
>             BoolConcreteLibFunc::Not(_) => vec![ApChange::Known(1)],
> ```





_Suggestion:_
```XML
            BoolConcreteLibFunc::Not(_) => vec![ApChange::Known(0)],
```
___
*[`crates/sierra_gas/src/core_libfunc_cost_base.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1326#-NJFkt-h5Z7wwA9_vpOZ:-NJFkt-h5Z7wwA9_vpO_:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ffb34aaee4790685928307bbb320b41547034b19/crates/sierra_gas/src/core_libfunc_cost_base.rs#L59)):*
> ```XML
>         }
>         Bool(BoolConcreteLibFunc::And(_)) => vec![ops.const_cost(0)],
>         Bool(BoolConcreteLibFunc::Not(_)) => vec![ops.const_cost(1)],
> ```





_Suggestion:_
```XML
        Bool(BoolConcreteLibFunc::Not(_)) => vec![ops.const_cost(0)],
```
___
*[`crates/sierra_to_casm/src/invocations/boolean.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1326#-NJFl4aXCqv2ONQQXhsu:-NJFl4aXCqv2ONQQXhsv:by1yvjg) ([raw file](https://github.com/starkware-libs/cairo/blob/ffb34aaee4790685928307bbb320b41547034b19/crates/sierra_to_casm/src/invocations/boolean.rs#L71)):*
> ```XML
>         [[ReferenceExpression::from_cell(CellExpression::BinOp(BinOpExpression {
>             op: FeltBinaryOperator::Sub,
>             a: ap_cell_ref(-1),
> ```

output = input + (PRIME - 1)



_Code quote:_
```XML
    Ok(builder.build(
        casm! { [ap + 0] = 1, ap++; }.instructions,
        vec![],
        [[ReferenceExpression::from_cell(CellExpression::BinOp(BinOpExpression {
            op: FeltBinaryOperator::Sub,
            a: ap_cell_ref(-1),
            b: DerefOrImmediate::from(a),
        }))]
        .into_iter()]
        .into_iter(),
    ))
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1326)* status: 7 of 12 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/sierra_to_casm/src/invocations/boolean.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1326#-NJFl4aXCqv2ONQQXhsu:-NJFqYop63hfnz8ty6EX:b-gs2sps) ([raw file](https://github.com/starkware-libs/cairo/blob/ffb34aaee4790685928307bbb320b41547034b19/crates/sierra_to_casm/src/invocations/boolean.rs#L71)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

output = input + (PRIME - 1)
</blockquote></details>

what?
no: if input is `0` we want the output to be `1` not `-1`, how does your version work?

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1326#-:-NJFrX8tE0NNv5778wFR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

___
*[`crates/sierra_to_casm/src/invocations/boolean.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1326#-NJFl4aXCqv2ONQQXhsu:-NJFr5FX-H_r5D3Y1FT8:b46sadk) ([raw file](https://github.com/starkware-libs/cairo/blob/ffb34aaee4790685928307bbb320b41547034b19/crates/sierra_to_casm/src/invocations/boolean.rs#L71)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what?
no: if input is `0` we want the output to be `1` not `-1`, how does your version work?
</blockquote></details>

it simply don't work - i was mistaken.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1326)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/sierra/src/extensions/modules/boolean.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1326#-NJFsXG_D66GTNfjlRGA:-NJFsXGa7ua8YQjJs-Xz:bsmf3qi) ([raw file](https://github.com/starkware-libs/cairo/blob/ffb34aaee4790685928307bbb320b41547034b19/crates/sierra/src/extensions/modules/boolean.rs#L34)):*
> ```XML
>                 ref_info: OutputVarReferenceInfo::Deferred(DeferredOutputKind::Generic),
>             }],
>             ap_change: SierraApChange::Known { new_vars_only: false },
> ```

just noticed - in the case of `bool_and` this is not correct.
is should be true.



_Code quote:_
```XML
            ap_change: SierraApChange::Known { new_vars_only: false },
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1326)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/sierra_ap_change/src/core_libfunc_ap_change.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1326#-NJFknXzA9tgPwv3_F8a:-NJFyMv89KS_nLoBFwO9:b-b6d7gw) ([raw file](https://github.com/starkware-libs/cairo/blob/ffb34aaee4790685928307bbb320b41547034b19/crates/sierra_ap_change/src/core_libfunc_ap_change.rs#L29)):*
> ```XML
>         CoreConcreteLibFunc::Bool(libfunc) => match libfunc {
>             BoolConcreteLibFunc::And(_) => vec![ApChange::Known(0)],
>             BoolConcreteLibFunc::Not(_) => vec![ApChange::Known(1)],
> ```

not relevant anymore
___
*[`crates/sierra_gas/src/core_libfunc_cost_base.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1326#-NJFkt-h5Z7wwA9_vpOZ:-NJFyKFj57SI0WJYwbUh:b-hdv76k) ([raw file](https://github.com/starkware-libs/cairo/blob/ffb34aaee4790685928307bbb320b41547034b19/crates/sierra_gas/src/core_libfunc_cost_base.rs#L59)):*
> ```XML
>         }
>         Bool(BoolConcreteLibFunc::And(_)) => vec![ops.const_cost(0)],
>         Bool(BoolConcreteLibFunc::Not(_)) => vec![ops.const_cost(1)],
> ```

still relevant? AP is used once

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1326)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/sierra/src/extensions/modules/boolean.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1326#-NJFsXG_D66GTNfjlRGA:-NJFzL_929AS8j0-nX1w:bsmb2ec) ([raw file](https://github.com/starkware-libs/cairo/blob/ffb34aaee4790685928307bbb320b41547034b19/crates/sierra/src/extensions/modules/boolean.rs#L34)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

just noticed - in the case of `bool_and` this is not correct.
is should be true.
</blockquote></details>

When is this true and when is this false? true when new vars are allocated?

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1326)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/sierra/src/extensions/modules/boolean.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1326#-NJFsXG_D66GTNfjlRGA:-NJG2LkM-QGFQaFLP4TT:bglgbo6) ([raw file](https://github.com/starkware-libs/cairo/blob/ffb34aaee4790685928307bbb320b41547034b19/crates/sierra/src/extensions/modules/boolean.rs#L34)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

When is this true and when is this false? true when new vars are allocated?
</blockquote></details>

no - true when there are no ap-changes that are not temp vars that are also returned.
___
*[`crates/sierra_ap_change/src/core_libfunc_ap_change.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1326#-NJFknXzA9tgPwv3_F8a:-NJG2iLd08d-grCTK4x3:bj6k35n) ([raw file](https://github.com/starkware-libs/cairo/blob/ffb34aaee4790685928307bbb320b41547034b19/crates/sierra_ap_change/src/core_libfunc_ap_change.rs#L29)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

not relevant anymore
</blockquote></details>

no - retracted.
___
*[`crates/sierra_gas/src/core_libfunc_cost_base.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1326#-NJFkt-h5Z7wwA9_vpOZ:-NJG2g1Z1B1UDV3WbylT:bpw68cy) ([raw file](https://github.com/starkware-libs/cairo/blob/ffb34aaee4790685928307bbb320b41547034b19/crates/sierra_gas/src/core_libfunc_cost_base.rs#L59)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

still relevant? AP is used once
</blockquote></details>

no - i retracted.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1326)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/sierra/src/extensions/modules/boolean.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1326#-NJFsXG_D66GTNfjlRGA:-NJG59Kl5_IbP3o1Da27:b-9sv5i3) ([raw file](https://github.com/starkware-libs/cairo/blob/ffb34aaee4790685928307bbb320b41547034b19/crates/sierra/src/extensions/modules/boolean.rs#L34)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no - true when there are no ap-changes that are not temp vars that are also returned.
</blockquote></details>

so in the bool-NOT case this should be `false`, because I set `[ap] = 1, ap++;` and I don't return this tempvar.
Fixed in bottom PR

**Pull request closed without merging**
