### PR TITLE
Update CallContract format.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1876)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 9 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1876#-:-NMYHOLJ6OumkVrvnBfv:bnfp4nl)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 197 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1876#-NMYHFNWBcOiWKhazt-Z:-NMYHFNX16EWmM7u59Z3:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2bb649414ac0d218971faa6e383ff734b3583688/crates/cairo-lang-starknet/src/plugin.rs#L197)):*
> ```XML
>             Result::Ok(ret_data) => ret_data,
>             Result::Err(ret_data) => {
>                 panic(ret_data)
> ```





_Suggestion:_
```XML
            Result::Err(revert_reason) => {
                panic(revert_reason)




            },
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1876)* status: 5 of 10 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 197 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1876#-NMYHFNWBcOiWKhazt-Z:-NMYIsNkD7cVLhy3NMY6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2bb649414ac0d218971faa6e383ff734b3583688/crates/cairo-lang-starknet/src/plugin.rs#L197)):*
> ```XML
>             Result::Ok(ret_data) => ret_data,
>             Result::Err(ret_data) => {
>                 panic(ret_data)
> ```

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 6 of 10 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1876)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1876)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
