### PR TITLE
Added mapping storage variable handling to plugin.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:f204e496

---

**Stack**:
- #1658
- #1643 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1643)* status: 5 of 10 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 386 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1643#-NL0KyJjEYzJa4x-7tqf:-NL0TvTIEsm7s5ogO5TA:b52nht4) ([raw file](https://github.com/starkware-libs/cairo/blob/03574402296c654562d1df27df3c661fce794d21/crates/cairo-lang-starknet/src/plugin.rs#L386)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

can you use

if let Some(type_without_prefix)  =  type_name.strip_prefix("Map::<") {
 ...
}
</blockquote></details>

just realized i should probably use the fact this is a path syntax to extract it normally, and with ability for better diags.
___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 390 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1643#-NL0LEmm3PR9atU7J5fI:-NL0ZikODfQbDKWW9Hqd:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/03574402296c654562d1df27df3c661fce794d21/crates/cairo-lang-starknet/src/plugin.rs#L390)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

diganostics?

or at least a TODO?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 392 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1643#-NL0LrAq1iz0tXJYuM6l:-NL0ZiwK5we9GB-BgNWb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/03574402296c654562d1df27df3c661fce794d21/crates/cairo-lang-starknet/src/plugin.rs#L392)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it it possible to find the key_type in the ast?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 401 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1643#-NL0MDb-1Lk7BGyg0Z-h:-NL0ZnxA1fVW_Rz0dz3j:b-n1092g) ([raw file](https://github.com/starkware-libs/cairo/blob/03574402296c654562d1df27df3c661fce794d21/crates/cairo-lang-starknet/src/plugin.rs#L401)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

this code is the same for both matches, right?

can you share it?
</blockquote></details>

only the diag code - not the interpolate.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1643)* status: 7 of 10 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 398 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1643#-NL0fQMa2thU8MEirgOd:-NL0fQMa2thU8MEirgOe:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c05eb1846eddcd70300d027e4622b18abf0cde22/crates/cairo-lang-starknet/src/plugin.rs#L398)):*
> ```XML
>                         ),
>                         (
>                             "key_type_name".to_string(),
> ```





_Suggestion:_
```XML
key_type
```
___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 402 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1643#-NL0fT7GDXUY_9qb63iU:-NL0fT7GDXUY_9qb63iV:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c05eb1846eddcd70300d027e4622b18abf0cde22/crates/cairo-lang-starknet/src/plugin.rs#L402)):*
> ```XML
>                         ),
>                         (
>                             "value_type_name".to_string(),
> ```





_Suggestion:_
```XML
value_type
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1643)* status: 7 of 10 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 398 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1643#-NL0fQMa2thU8MEirgOd:-NL0jKZN3WU6f5UfSOLm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c05eb1846eddcd70300d027e4622b18abf0cde22/crates/cairo-lang-starknet/src/plugin.rs#L398)):*
> ```XML
>                         ),
>                         (
>                             "key_type_name".to_string(),
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 402 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1643#-NL0fT7GDXUY_9qb63iU:-NL0jKm2--v8eGUwh-HG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c05eb1846eddcd70300d027e4622b18abf0cde22/crates/cairo-lang-starknet/src/plugin.rs#L402)):*
> ```XML
>                         ),
>                         (
>                             "value_type_name".to_string(),
> ```

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 10 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1643#-:-NL0lZqT-BrvMoNP2Dyf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
