### PR TITLE
Added conversions of basic types to strings

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3893)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3893)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/to_byte_array.cairo` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3893#-NcGoClrA5jFfPQKA1ni:-NcGoClrA5jFfPQKA1nj:b-j53opj) ([raw file](https://github.com/starkware-libs/cairo/blob/f2a1af5ae1cc0d0e636dea05037d78371f459457/corelib/src/to_byte_array.cairo#L17)):*
> ```Cairo
> trait FormatAsByteArrayBin<T> {
>     fn format_as_byte_array_bin(self: T) -> ByteArray;
> }
> ```

as discussed - merge to a single trait.
and add a `to_string` style trait autoimplemented from this with param 10.



_Code quote:_
```Cairo
trait FormatAsByteArrayHex<T> {
    fn format_as_byte_array_hex(self: T) -> ByteArray;
}
trait FormatAsByteArrayDec<T> {
    fn format_as_byte_array_dec(self: T) -> ByteArray;
}
trait FormatAsByteArrayOct<T> {
    fn format_as_byte_array_oct(self: T) -> ByteArray;
}
trait FormatAsByteArrayBin<T> {
    fn format_as_byte_array_bin(self: T) -> ByteArray;
}
```
___
*[`corelib/src/test/ec_test.cairo` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3893#-NcGno6873_LZK7FYUyK:-NcGno6873_LZK7FYUyL:b-v3q5s9) ([raw file](https://github.com/starkware-libs/cairo/blob/f2a1af5ae1cc0d0e636dea05037d78371f459457/corelib/src/test/ec_test.cairo#L55)):*
> ```Cairo
> 
>     // Compute `p - p`.
>     assert(EcPointTryIntoNonZero::try_into(p - p).is_none(), 'p - p did not return 0.');
> ```

I think not directly using impl names is preferable.



_Suggestion:_
```Cairo
    let p_diff: Option<NonZero<EcPoint>> = (p - p).try_into();
    assert(p_diff.is_none(), 'p - p did not return 0.');
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3893)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/to_byte_array.cairo` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3893#-NcGoClrA5jFfPQKA1ni:-NcbWxGuB0tpFpM9iEPM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f2a1af5ae1cc0d0e636dea05037d78371f459457/corelib/src/to_byte_array.cairo#L17)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

as discussed - merge to a single trait.
and add a `to_string` style trait autoimplemented from this with param 10.
</blockquote></details>

Done.
___
*[`corelib/src/test/ec_test.cairo` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3893#-NcGno6873_LZK7FYUyK:-NcbXgGq5j6j825_YJhH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f2a1af5ae1cc0d0e636dea05037d78371f459457/corelib/src/test/ec_test.cairo#L55)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I think not directly using impl names is preferable.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3893)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/lib.cairo` line 335 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3893#-NcbNwx4DozJFo1hSr8W:-NcbNwx4DozJFo1hSr8X:b2mxura) ([raw file](https://github.com/starkware-libs/cairo/blob/a481f1d31f516f624fd819375b91a4ef57368019/corelib/src/lib.cairo#L335)):*
> ```Cairo
> // to_byte_array.
> mod to_byte_array;
> use to_byte_array::FormatAsByteArray;
> ```

i think we should stop bring these to the crate level for now - we can add these later anyway.



_Code quote:_
```Cairo
use to_byte_array::FormatAsByteArray;
```
___
*[`corelib/src/to_byte_array.cairo` line 7 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3893#-Ncber7pBK7ZLFYnVE97:-Ncber7pBK7ZLFYnVE98:b7nodzb) ([raw file](https://github.com/starkware-libs/cairo/blob/a481f1d31f516f624fd819375b91a4ef57368019/corelib/src/to_byte_array.cairo#L7)):*
> ```Cairo
> 
> trait FormatAsByteArray<T> {
>     fn format_as_byte_array(self: T, base: NonZero<T>) -> ByteArray;
> ```

I'm wondering what is better -
Currently this is a mid-case for performance vs comfort:
Top comfort - only `u8` for `base` (as the values are 2 to 36).
Top performance - directly appending these into an existing byte array.
I'm leaning towards this appending to a byte array (and i'm guessing renaming it accordingly) and maybe having some other auto-implemented extension traits over this.
WDYT?



_Code quote:_
```Cairo
    fn format_as_byte_array(self: T, base: NonZero<T>) -> ByteArray;
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3893)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/to_byte_array.cairo` line 97 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3893#-Ncbg8zpBcnVS1XU_a8D:-Ncbg8zpBcnVS1XU_a8E:b-b9djyn) ([raw file](https://github.com/starkware-libs/cairo/blob/a481f1d31f516f624fd819375b91a4ef57368019/corelib/src/to_byte_array.cairo#L97)):*
> ```Cairo
>         "0o" + result
>     } else if base == 2 {
>         "0b" + result
> ```

I think these probably belong outside as well.
even when printing in a base in rust %x you don't automatically add 0x (unless you do something like %#x)



_Code quote:_
```Cairo
    if base == 16 {
        "0x" + result
    } else if base == 8 {
        "0o" + result
    } else if base == 2 {
        "0b" + result
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3893)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/lib.cairo` line 335 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3893#-NcbNwx4DozJFo1hSr8W:-Ncr9X_K7sW9myjz8ENT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a481f1d31f516f624fd819375b91a4ef57368019/corelib/src/lib.cairo#L335)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i think we should stop bring these to the crate level for now - we can add these later anyway.
</blockquote></details>

Done.
___
*[`corelib/src/to_byte_array.cairo` line 7 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3893#-Ncber7pBK7ZLFYnVE97:-Ncr5amaAyTRPfYoEz5g:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a481f1d31f516f624fd819375b91a4ef57368019/corelib/src/to_byte_array.cairo#L7)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I'm wondering what is better -
Currently this is a mid-case for performance vs comfort:
Top comfort - only `u8` for `base` (as the values are 2 to 36).
Top performance - directly appending these into an existing byte array.
I'm leaning towards this appending to a byte array (and i'm guessing renaming it accordingly) and maybe having some other auto-implemented extension traits over this.
WDYT?
</blockquote></details>

Done.
___
*[`corelib/src/to_byte_array.cairo` line 97 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3893#-Ncbg8zpBcnVS1XU_a8D:-Ncr5cPqCYA8-kUbiHEf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a481f1d31f516f624fd819375b91a4ef57368019/corelib/src/to_byte_array.cairo#L97)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I think these probably belong outside as well.
even when printing in a base in rust %x you don't automatically add 0x (unless you do something like %#x)
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3893)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/ec.cairo` line 172 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3893#-NcrEYgODWkl0wo0JUZq:-NcrEYgODWkl0wo0JUZr:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9359ee2d38863b69b7d217f5727382c20be45972/corelib/src/ec.cairo#L172)):*
> ```Cairo
>     /// Computes the difference between two points on the curve.
>     fn sub(lhs: EcPoint, rhs: EcPoint) -> EcPoint {
>         match EcPointTryIntoNonZero::try_into(rhs) {
> ```





_Suggestion:_
```Cairo
        let nz_point: Option<NonZero<EcPoint>> = rhs.try_into();
        match nz_point {
```
___
*[`corelib/src/to_byte_array.cairo` line 102 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3893#-NcrFifHE9pcOJMzxIrb:-NcrFifHE9pcOJMzxIrc:b7yl0g1) ([raw file](https://github.com/starkware-libs/cairo/blob/9359ee2d38863b69b7d217f5727382c20be45972/corelib/src/to_byte_array.cairo#L102)):*
> ```Cairo
>         self_as_u256.format_as_byte_array(base)
>     }
> }
> ```

make generic based on above trait.



_Code quote:_
```Cairo
// === Impls of FormatAsByteArray ===

impl U8FormatAsByteArray of FormatAsByteArray<u8> {
    fn format_as_byte_array(self: u8, base: NonZero<u8>) -> ByteArray {
        format_as_byte_array(self, base)
    }
}
impl U16FormatAsByteArray of FormatAsByteArray<u16> {
    fn format_as_byte_array(self: u16, base: NonZero<u16>) -> ByteArray {
        format_as_byte_array(self, base)
    }
}
impl U32FormatAsByteArray of FormatAsByteArray<u32> {
    fn format_as_byte_array(self: u32, base: NonZero<u32>) -> ByteArray {
        format_as_byte_array(self, base)
    }
}
impl U64FormatAsByteArray of FormatAsByteArray<u64> {
    fn format_as_byte_array(self: u64, base: NonZero<u64>) -> ByteArray {
        format_as_byte_array(self, base)
    }
}
impl U128FormatAsByteArray of FormatAsByteArray<u128> {
    fn format_as_byte_array(self: u128, base: NonZero<u128>) -> ByteArray {
        format_as_byte_array(self, base)
    }
}
impl U256FormatAsByteArray of FormatAsByteArray<u256> {
    fn format_as_byte_array(self: u256, base: NonZero<u256>) -> ByteArray {
        format_as_byte_array(self, base)
    }
}
impl Felt252FormatAsByteArray of FormatAsByteArray<felt252> {
    fn format_as_byte_array(self: felt252, base: NonZero<felt252>) -> ByteArray {
        let self_as_u256: u256 = self.into();
        let base: felt252 = base.into();
        let base: u256 = base.into();
        let base: NonZero<u256> = base.try_into().unwrap();
        self_as_u256.format_as_byte_array(base)
    }
}
```
___
*[`corelib/src/to_byte_array.cairo` line 123 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3893#-NcrFWQ6-GTGIxoypLCS:-NcrFWQ6-GTGIxoypLCT:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9359ee2d38863b69b7d217f5727382c20be45972/corelib/src/to_byte_array.cairo#L123)):*
> ```Cairo
>     let base: T = base_nz.into();
>     let base: u8 = base.try_into().unwrap();
>     assert(base <= 36, 'base must be <= 36');
> ```





_Suggestion:_
```Cairo
    assert(base >= 2, 'base must be >= 2');
    assert(base <= 36, 'base must be <= 36');
```
___
*[`corelib/src/to_byte_array.cairo` line 185 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3893#-NcrJlqA4JwFfLYmfFGd:-NcrJlqA4JwFfLYmfFGe:b-s062xa) ([raw file](https://github.com/starkware-libs/cairo/blob/9359ee2d38863b69b7d217f5727382c20be45972/corelib/src/to_byte_array.cairo#L185)):*
> ```Cairo
>         digit_as_u8 + '0'
>     } else {
>         digit_as_u8 - 10 + 'A'
> ```

let us be like rust and python for now.



_Suggestion:_
```Cairo
/// Converts a digit (0-9, a-z) to its Ascii representation in a base > 10.
#[inline]
fn get_big_base_digit_representation(digit_as_u8: u8) -> u8 {
    if digit_as_u8 < 10 {
        digit_as_u8 + '0'
    } else {
        digit_as_u8 - 10 + 'a'
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3893)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/ec.cairo` line 172 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3893#-NcrEYgODWkl0wo0JUZq:-NcwwcLqCMcuRYq2GSX9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9359ee2d38863b69b7d217f5727382c20be45972/corelib/src/ec.cairo#L172)):*
> ```Cairo
>     /// Computes the difference between two points on the curve.
>     fn sub(lhs: EcPoint, rhs: EcPoint) -> EcPoint {
>         match EcPointTryIntoNonZero::try_into(rhs) {
> ```

Done.
___
*[`corelib/src/to_byte_array.cairo` line 102 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3893#-NcrFifHE9pcOJMzxIrb:-Ncx-Sit4ew8DrT3vI4s:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9359ee2d38863b69b7d217f5727382c20be45972/corelib/src/to_byte_array.cairo#L102)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

make generic based on above trait.
</blockquote></details>

Done.
___
*[`corelib/src/to_byte_array.cairo` line 123 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3893#-NcrFWQ6-GTGIxoypLCS:-Ncwyxmd5Gjy7UKWiiYF:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9359ee2d38863b69b7d217f5727382c20be45972/corelib/src/to_byte_array.cairo#L123)):*
> ```Cairo
>     let base: T = base_nz.into();
>     let base: u8 = base.try_into().unwrap();
>     assert(base <= 36, 'base must be <= 36');
> ```

Done.
___
*[`corelib/src/to_byte_array.cairo` line 185 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3893#-NcrJlqA4JwFfLYmfFGd:-NcwyxM83OVmN7viG0Cf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9359ee2d38863b69b7d217f5727382c20be45972/corelib/src/to_byte_array.cairo#L185)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

let us be like rust and python for now.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3893#-:-Nd-JX0FDZR-1qEdcCZK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
