### PR TITLE
fix: filter_test_cases

### PR DESCRIPTION
**Pull request by greged93**
Fix issues on the `filter_test_cases` function. The updated function now:
- Updates the `ignore` field to false for ignored test when passing the `ignored` flag.
- Runs all tests when passing the `include-ignored`, regardless of the `ignored` flag.

Adds tests for the `filter_test_cases` to verify the above claims.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5599)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5599)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @greged93)

___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 521 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5599#-NyQzbvj9jpXljiTfJLf:-NyQzbvj9jpXljiTfJLg:bqnrvjx) ([raw file](https://github.com/starkware-libs/cairo/blob/e2e366a9dfb2af5d125d822d1f0c43c2cbb95f4f/crates/cairo-lang-test-runner/src/lib.rs#L521)):*
> ```XML
> }
> 
> #[cfg(test)]
> ```

move all tests to the test.rs file included.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5599)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @greged93)

___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 535 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5599#-NyR1cqZ-6iqCtV1OQGa:-NyR1cqZ-6iqCtV1OQGb:b-imglfr) ([raw file](https://github.com/starkware-libs/cairo/blob/e2e366a9dfb2af5d125d822d1f0c43c2cbb95f4f/crates/cairo-lang-test-runner/src/lib.rs#L535)):*
> ```XML
>                         ignored: false,
>                     },
>                 ),
> ```

consider adding a shorthand to create these pairs.
would make the tests much more concise.



_Code quote:_
```XML
                (
                    String::from("test1"),
                    TestConfig {
                        available_gas: None,
                        expectation: TestExpectation::Success,
                        ignored: false,
                    },
                ),
```
___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 569 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5599#-NyR1WkT16RVqWNDOlyc:-NyR1WkT16RVqWNDOlyd:ber0ntt) ([raw file](https://github.com/starkware-libs/cairo/blob/e2e366a9dfb2af5d125d822d1f0c43c2cbb95f4f/crates/cairo-lang-test-runner/src/lib.rs#L569)):*
> ```XML
>             && lhs.1.available_gas == rhs.1.available_gas
>             && lhs.1.expectation == rhs.1.expectation
>             && lhs.1.ignored == rhs.1.ignored
> ```

adding PartialEq and debug is fine to support testing.



_Code quote:_
```XML
        lhs.0 == rhs.0
            && lhs.1.available_gas == rhs.1.available_gas
            && lhs.1.expectation == rhs.1.expectation
            && lhs.1.ignored == rhs.1.ignored
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5599)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @greged93)

___
*[`crates/cairo-lang-test-runner/src/test.rs` line 214 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5599#-NyRFJ8o76_ikp2SCmjJ:-NyRFJ8o76_ikp2SCmjK:bmo34qq) ([raw file](https://github.com/starkware-libs/cairo/blob/13a6f90804958d0b57d64c9f7a9349fb0bb1212c/crates/cairo-lang-test-runner/src/test.rs#L214)):*
> ```XML
>             TestConfig { available_gas: None, expectation: TestExpectation::Success, ignored },
>         )
>     };
> ```

extract to an actual function.
and remove `test_compilation` function to just run the simple filtered test cases locally.



_Code quote:_
```XML
    let named_test_gen = |name: &str, ignored: bool| {
        (
            String::from(name),
            TestConfig { available_gas: None, expectation: TestExpectation::Success, ignored },
        )
    };
```
___
*[`crates/cairo-lang-test-runner/src/test.rs` line 234 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5599#-NyRFTS84JnlQcxUtvXz:-NyRFTS84JnlQcxUtvY-:b-lex3vx) ([raw file](https://github.com/starkware-libs/cairo/blob/13a6f90804958d0b57d64c9f7a9349fb0bb1212c/crates/cairo-lang-test-runner/src/test.rs#L234)):*
> ```XML
> 
> #[test]
> fn test_filter_test_cases() {
> ```

after the extraction of the above closure into a function, split into different appropriately named tests.

**Review by greged93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5599)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 521 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5599#-NyQzbvj9jpXljiTfJLf:-NyTz6-8-zI-FiW0EBst:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e2e366a9dfb2af5d125d822d1f0c43c2cbb95f4f/crates/cairo-lang-test-runner/src/lib.rs#L521)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

move all tests to the test.rs file included.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 535 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5599#-NyR1cqZ-6iqCtV1OQGa:-NyTz4eREAOkR7MZz6vl:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e2e366a9dfb2af5d125d822d1f0c43c2cbb95f4f/crates/cairo-lang-test-runner/src/lib.rs#L535)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

consider adding a shorthand to create these pairs.
would make the tests much more concise.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 569 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5599#-NyR1WkT16RVqWNDOlyc:-NyTz5n02yBGtzVtTYLS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e2e366a9dfb2af5d125d822d1f0c43c2cbb95f4f/crates/cairo-lang-test-runner/src/lib.rs#L569)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

adding PartialEq and debug is fine to support testing.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-test-runner/src/test.rs` line 214 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5599#-NyRFJ8o76_ikp2SCmjJ:-NyTz8VB4Ur8qEeQspgM:bcda36i) ([raw file](https://github.com/starkware-libs/cairo/blob/13a6f90804958d0b57d64c9f7a9349fb0bb1212c/crates/cairo-lang-test-runner/src/test.rs#L214)):*
> just run the simple filtered test cases locally.

I'm not sure what you mean by that, you want me to initialize the `TestCompilation` instance in each test?
___
*[`crates/cairo-lang-test-runner/src/test.rs` line 234 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5599#-NyRFTS84JnlQcxUtvXz:-NyTzLse90Lnzuymwl77:bem3qpm) ([raw file](https://github.com/starkware-libs/cairo/blob/13a6f90804958d0b57d64c9f7a9349fb0bb1212c/crates/cairo-lang-test-runner/src/test.rs#L234)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

after the extraction of the above closure into a function, split into different appropriately named tests.
</blockquote></details>

Would you want me to split the `test_format_for_panic` test as well?

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5599)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @greged93)

___
*[`crates/cairo-lang-test-runner/src/test.rs` line 214 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5599#-NyRFJ8o76_ikp2SCmjJ:-NyU-b4p6rt-wzVNLixy:b773kgx) ([raw file](https://github.com/starkware-libs/cairo/blob/13a6f90804958d0b57d64c9f7a9349fb0bb1212c/crates/cairo-lang-test-runner/src/test.rs#L214)):*
<details><summary><i>Previously, greged93 wrote…</i></summary><blockquote>

> just run the simple filtered test cases locally.

I'm not sure what you mean by that, you want me to initialize the `TestCompilation` instance in each test?
</blockquote></details>

add
```
fn as_test_compilation(tests: &[(&str, bool)]) { ... }
```
and:
```
assert_eq!(
     filter_test_cases(
          as_test_compilation(&[("test1", false), ("test2", true), ("test3", false)]), false, false, "test"
     ),
     (0, as_test_compilation(&[("test1", false), ("test2", true), ("test3", false)]))
);
```
or something similar.
   
___
*[`crates/cairo-lang-test-runner/src/test.rs` line 234 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5599#-NyRFTS84JnlQcxUtvXz:-NyU07SxBTUHywsoYok1:benaxmg) ([raw file](https://github.com/starkware-libs/cairo/blob/13a6f90804958d0b57d64c9f7a9349fb0bb1212c/crates/cairo-lang-test-runner/src/test.rs#L234)):*
<details><summary><i>Previously, greged93 wrote…</i></summary><blockquote>

Would you want me to split the `test_format_for_panic` test as well?
</blockquote></details>

not in this PR at the very least.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5599)* status: all files reviewed, 2 unresolved discussions (waiting on @greged93)

___
*[`crates/cairo-lang-test-runner/src/test.rs` line 219 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5599#-NyUC584-IvBJkI-tnuO:-NyUC584-IvBJkI-tnuP:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/3aa8fd20b4211f4b1f862bc80094f0dec7861585/crates/cairo-lang-test-runner/src/test.rs#L219)):*
> ```XML
> }
> 
> fn to_named_test(test: &(&str, bool)) -> (String, TestConfig) {
> ```

doc
___
*[`crates/cairo-lang-test-runner/src/test.rs` line 226 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5599#-NyUC4L3EFjh0yUAXWJp:-NyUC4L3EFjh0yUAXWJq:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/3aa8fd20b4211f4b1f862bc80094f0dec7861585/crates/cairo-lang-test-runner/src/test.rs#L226)):*
> ```XML
> }
> 
> fn to_test_compilation(tests: &[(&str, bool)]) -> TestCompilation {
> ```

doc

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5599#-:-NyUH1R-4hNSbIWUStcJ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @greged93)

**Comment by greged93** [comment]
@orizi anything I need to do on this?

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5599)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @greged93)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5599#-NyZOr7w1tX5Pc9N9jfv:-NyZOr7w1tX5Pc9N9jfw:b-uuj1x0) (no related file):*
@gilbens-starkware for 2nd eye.

___

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5599#-:-NyZZIiWEK0WiF_xGQID:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @greged93)

**Pull request merged**
