### PR TITLE
Improved memory usage of sierra-to-casm by not keeping unused data.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #5253
- #5241
- #5240 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5240)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 483 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5240#-NsnBcw94-s9CpsDLd4f:-NsnBcwA9yOBiRt_09Cw:b-exhpe9) ([raw file](https://github.com/starkware-libs/cairo/blob/5d9895fe555644a20afe29167f19a5c77528f1b1/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L483)):*
> ```XML
>                 for ((branch_info, branch_changes), updated_annotations) in
>                     zip_eq(&invocation.branches, compiled_invocation.results)
>                         .zip(all_updated_annotations)
> ```

why is the all_updated_annotations needed?

can't you do
updated_annotations = orig_annotations.clone()?



_Code quote:_
```XML
 .zip(all_updated_annotations)
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5240)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 483 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5240#-NsnBcw94-s9CpsDLd4f:-NsnCDNmDoJvCfSGlOvY:b-4dzbgh) ([raw file](https://github.com/starkware-libs/cairo/blob/5d9895fe555644a20afe29167f19a5c77528f1b1/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L483)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why is the all_updated_annotations needed?

can't you do
updated_annotations = orig_annotations.clone()?
</blockquote></details>

i want to prevent as many clones as possible - most cases we have a single branch, so we need to handle to prevent the clone.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 319 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5240#-NsnD2m9A-dPyOEVCVxn:-NsnD2m9A-dPyOEVCVxo:b-ty3ami) ([raw file](https://github.com/starkware-libs/cairo/blob/5d9895fe555644a20afe29167f19a5c77528f1b1/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L319)):*
> ```XML
>             }
>             let mut tmp = ReferenceExpression::zero_sized();
>             std::mem::swap(&mut tmp, &mut ref_value.expression);
> ```

can you use
std::mem::replace?



_Code quote:_
```XML
   std::mem::swap(&mut tmp, &mut ref_value.expression);
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 483 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5240#-NsnBcw94-s9CpsDLd4f:-NsnDLDa8hzf7Qw-UTpa:b-gj5g4z) ([raw file](https://github.com/starkware-libs/cairo/blob/5d9895fe555644a20afe29167f19a5c77528f1b1/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L483)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i want to prevent as many clones as possible - most cases we have a single branch, so we need to handle to prevent the clone.
</blockquote></details>

can you document this

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5240)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 319 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5240#-NsnD2m9A-dPyOEVCVxn:-NsnDpQ86rRkHGnszRiG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5d9895fe555644a20afe29167f19a5c77528f1b1/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L319)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

can you use
std::mem::replace?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 483 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5240#-NsnBcw94-s9CpsDLd4f:-NsnEofu97p0DISJ2yO3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5d9895fe555644a20afe29167f19a5c77528f1b1/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L483)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

can you document this
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5240)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 483 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5240#-NsnBcw94-s9CpsDLd4f:-NsnIPBl0w5tPIRbn3UD:bbfmqt8) ([raw file](https://github.com/starkware-libs/cairo/blob/5d9895fe555644a20afe29167f19a5c77528f1b1/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L483)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see any comment.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 475 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5240#-Nsqg0CW-l8X8LffWFv3:-Nsqg0CW-l8X8LffWFv4:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/3f7dd652a154e67dfaf3b90de039deea4a3de4bd/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L475)):*
> ```XML
>                 // Since the updated annotations may be very heavy, we want to avoid cloneing them.
>                 // We create a vector for the usage in the loop, and that way we will do clones only
>                 // for more than 1 branch, which is the less common case.
> ```





_Suggestion:_
```XML
                // Using a vector of annotations for the loop allows us to clone the annotations only in the case of more the 1 branch, which is less common.
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5240)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 475 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5240#-Nsqg0CW-l8X8LffWFv3:-NsqlUo24_oFpPT6E4ti:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3f7dd652a154e67dfaf3b90de039deea4a3de4bd/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L475)):*
> ```XML
>                 // Since the updated annotations may be very heavy, we want to avoid cloneing them.
>                 // We create a vector for the usage in the loop, and that way we will do clones only
>                 // for more than 1 branch, which is the less common case.
> ```

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5240#-:-NsqoTw617YOMF6zrhuz:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @orizi)

**Pull request merged**
