### PR TITLE
Support inlining of identity function.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2094)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2094)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 460 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2094#-NNr0vlH2W_5maNnajG1:-NNr0vlH2W_5maNnajG2:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/3d83cdaa4236acd6be61264c3a916836bcfcf6ff/crates/cairo-lang-lowering/src/inline/mod.rs#L460)):*
> ```XML
>         };
> 
>         // TODO(ilya): make var_remapping more efficient and remove the following.
> ```





_Suggestion:_
```XML
        // Try to avoid using output_remapping as it causes more store temps to be generated.
        // TODO(ilya): make var_remapping more efficient and remove the following.
```
___
*[`crates/cairo-lang-lowering/src/inline/test_data/inline_diagnostics` line 45 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2094#-NNr0sxD0GB6byBYreQr:-NNr0sxD0GB6byBYreQs:bezggti) ([raw file](https://github.com/starkware-libs/cairo/blob/bbe74615c88f763f32b3b7ad2963b7cdf726556d/crates/cairo-lang-lowering/src/inline/test_data/inline_diagnostics#L45)):*
> ```
> 
> //! > Test inlining diagnostics for a function an identity function.
> ```

reenable as working.



_Code quote:_
```
//! > Test inlining diagnostics for a function an identity function.

//! > test_function_name
test_function_inlining

//! > function
#[inline(always)]
fn foo(n: felt) -> felt {
  n
}

//! > function_name
foo

//! > module_code

//! > semantic_diagnostics

//! > before
blk0 (root):
Inputs: v0: core::felt
Statements:
End:
  Return(v0)

//! > after
blk0 (root):
Inputs: v0: core::felt
Statements:
End:
  Return(v0)

//! > lowering_diagnostics
error: Inlining of functions that directly returns one of its inputs is not supported.
 --> lib.cairo:1:1
#[inline(always)]
^***************^

//! > ==========================================================================
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2094)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/inline/test_data/inline_diagnostics` line 45 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2094#-NNr0sxD0GB6byBYreQr:-NNr350m9kjn74VIBcJA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bbe74615c88f763f32b3b7ad2963b7cdf726556d/crates/cairo-lang-lowering/src/inline/test_data/inline_diagnostics#L45)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

reenable as working.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2094)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 460 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2094#-NNr0vlH2W_5maNnajG1:-NNr367h4A0cvjq6PUTb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3d83cdaa4236acd6be61264c3a916836bcfcf6ff/crates/cairo-lang-lowering/src/inline/mod.rs#L460)):*
> ```XML
>         };
> 
>         // TODO(ilya): make var_remapping more efficient and remove the following.
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2094#-:-NNr3S3Q38S69iHkpmgi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2094)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
