### PR TITLE
Added enforcement for names for function params on impls.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2845)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2845)* status: 1 of 14 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1148 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2845#-NTCLocaDFLk-B4z7KS9:-NTCLocbAYU7HfFQkkPh:buaxdlr) ([raw file](https://github.com/starkware-libs/cairo/blob/9a27fc3e7e8affdc29130a7b9121ebc152533f4f/crates/cairo-lang-semantic/src/items/imp.rs#L1148)):*
> ```XML
> 
>         if trait_param.name != param.name
>             && param.name.strip_prefix("_") != Some(trait_param.name.as_str())
> ```

I think we should ask around the team again about this. It's really when i, for example, recursive call a method, passing a: in stead of _a:

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 12 of 14 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2845)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2845)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1148 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2845#-NTCLocaDFLk-B4z7KS9:-NTCiusV3ILIUmfDo7PB:b14shq4) ([raw file](https://github.com/starkware-libs/cairo/blob/9a27fc3e7e8affdc29130a7b9121ebc152533f4f/crates/cairo-lang-semantic/src/items/imp.rs#L1148)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I think we should ask around the team again about this. It's really when i, for example, recursive call a method, passing a: in stead of _a:
</blockquote></details>

disallowed for now.
Done

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2845#-:-NTCpUDfBD1DB1CjIt8S:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
