### PR TITLE
Added readme for test runner, as well as updated the general readme.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:48c85d94

---

**Stack**:
- #1507
- #1506 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by bbrandtom — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1506)* status: all files reviewed, 2 unresolved discussions (waiting on @abdelhamidbakhta, @gilbens-starkware, and @orizi)

___
*[`README.md` line 81 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1506#-NKIMc28A2t1hsY2JdmO:-NKIMc28A2t1hsY2JdmP:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6716b8a282e666be339a55658b73a461e16ab3aa/README.md#L81)):*
> ```Markdown
> ```
> 
> Compile Sierra to casm:
> ```





_Suggestion:_
```Markdown
casm (Cairo assembly)
```
___
*[`crates/test_runner/README.md` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1506#-NKIMqwp7diXVov5quLw:-NKIMqwq6c2m5IbiyA3I:b-nkbyxl) ([raw file](https://github.com/starkware-libs/cairo/blob/6716b8a282e666be339a55658b73a461e16ab3aa/crates/test_runner/README.md#L1)):*
> ```Markdown
> # Testing cairo files
> ```

Maybe add a link to this from the main readme?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1506)* status: all files reviewed, 2 unresolved discussions (waiting on @abdelhamidbakhta, @bbrandtom, and @gilbens-starkware)

___
*[`README.md` line 81 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1506#-NKIMc28A2t1hsY2JdmO:-NKIQ5bL2GzobQS8z516:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6716b8a282e666be339a55658b73a461e16ab3aa/README.md#L81)):*
> ```Markdown
> ```
> 
> Compile Sierra to casm:
> ```

Done.
___
*[`crates/test_runner/README.md` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1506#-NKIMqwp7diXVov5quLw:-NKIQ6IYAy1RAhRwXnIN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6716b8a282e666be339a55658b73a461e16ab3aa/crates/test_runner/README.md#L1)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

Maybe add a link to this from the main readme?
</blockquote></details>

Done.

**Review by bbrandtom — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1506#-:-NKIRU3t9rJGkP_qjZ98:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @abdelhamidbakhta and @gilbens-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1506)* status: all files reviewed, 1 unresolved discussion (waiting on @abdelhamidbakhta and @gilbens-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1506)* status: all files reviewed, 1 unresolved discussion (waiting on @abdelhamidbakhta and @gilbens-starkware)

**Review by bbrandtom — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1506)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @abdelhamidbakhta and @gilbens-starkware)

**Pull request merged**
