### PR TITLE
added trait consts

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5431)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5431)* status: all files reviewed, 11 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-defs/src/ids.rs` line 470 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5431#-NvlaZGcD_0gc8VmIRhV:-NvlaZGcD_0gc8VmIRhW:b-tde9v3) ([raw file](https://github.com/starkware-libs/cairo/blob/90fb00689981893a4bf85a135f58e293e655301f/crates/cairo-lang-defs/src/ids.rs#L470)):*
> ```XML
> define_named_language_element_id!(
>     TraitConstId,
>     TraitConstLongId,
> ```

Const -> Constant



_Code quote:_
```XML
    TraitConstId,
    TraitConstLongId,
```
___
*[`crates/cairo-lang-defs/src/ids.rs` line 476 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5431#-NvlagBk-H0-0054J1xp:-NvlagBk-H0-0054J1xq:b-44tpm1) ([raw file](https://github.com/starkware-libs/cairo/blob/90fb00689981893a4bf85a135f58e293e655301f/crates/cairo-lang-defs/src/ids.rs#L476)):*
> ```XML
> impl TraitConstId {
>     pub fn trait_id(&self, db: &dyn DefsGroup) -> TraitId {
>         let TraitConstLongId(module_file_id, ptr) = db.lookup_intern_trait_const(*self);
> ```

please rebase and use .lookup_intern()



_Code quote:_
```XML
.lookup_intern_trait_const(*self)
```
___
*[`crates/cairo-lang-semantic/src/db.rs` line 412 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5431#-Nvlch664XwTqmcr7oaQ:-Nvlch673T1j3Nj2Dhcl:b-ojsf3j) ([raw file](https://github.com/starkware-libs/cairo/blob/90fb00689981893a4bf85a135f58e293e655301f/crates/cairo-lang-semantic/src/db.rs#L412)):*
> ```XML
>     /// Returns the item const with the given name of the given trait, if exists.
>     #[salsa::invoke(items::trt::trait_const_by_name)]
>     fn trait_const_by_name(&self, trait_id: TraitId, name: SmolStr) -> Maybe<Option<TraitConstId>>;
> ```

const -> constant



_Code quote:_
```XML
    /// Returns the consts of a trait.
    #[salsa::invoke(items::trt::trait_consts)]
    fn trait_consts(&self, trait_id: TraitId) -> Maybe<OrderedHashMap<SmolStr, TraitConstId>>;
    /// Returns the item const with the given name of the given trait, if exists.
    #[salsa::invoke(items::trt::trait_const_by_name)]
    fn trait_const_by_name(&self, trait_id: TraitId, name: SmolStr) -> Maybe<Option<TraitConstId>>;
```
___
*[`crates/cairo-lang-semantic/src/db.rs` line 462 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5431#-NvldBgY3wrBIjgSGlgM:-NvldBgY3wrBIjgSGlgN:b-1yzq8d) ([raw file](https://github.com/starkware-libs/cairo/blob/90fb00689981893a4bf85a135f58e293e655301f/crates/cairo-lang-semantic/src/db.rs#L462)):*
> ```XML
>     /// Private query to compute data about a trait const.
>     #[salsa::invoke(items::trt::priv_trait_const_data)]
>     fn priv_trait_const_data(&self, const_id: TraitConstId) -> Maybe<TraitItemConstData>;
> ```

Name all params of type TraitConstId `trait_constant`



_Code quote:_
```XML
    // Trait const.
    // ================
    /// Returns the semantic diagnostics of a trait type.
    #[salsa::invoke(items::trt::trait_const_diagnostics)]
    fn trait_const_diagnostics(
        &self,
        trait_type_id: TraitConstId,
    ) -> Diagnostics<SemanticDiagnostic>;
    /// Returns the attributes of a trait const.
    #[salsa::invoke(items::trt::trait_const_attributes)]
    fn trait_const_attributes(&self, trait_type_id: TraitConstId) -> Maybe<Vec<Attribute>>;
    /// Returns the resolution resolved_items of a trait const.
    #[salsa::invoke(items::trt::trait_const_resolver_data)]
    fn trait_const_resolver_data(&self, trait_const_id: TraitConstId) -> Maybe<Arc<ResolverData>>;
    /// Private query to compute data about a trait const.
    #[salsa::invoke(items::trt::priv_trait_const_data)]
    fn priv_trait_const_data(&self, const_id: TraitConstId) -> Maybe<TraitItemConstData>;
```
___
*[`crates/cairo-lang-semantic/src/items/trt.rs` line 503 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5431#-NvlgywJ-501snMoDQG5:-NvlgywJ-501snMoDQG6:btuq7me) ([raw file](https://github.com/starkware-libs/cairo/blob/90fb00689981893a4bf85a135f58e293e655301f/crates/cairo-lang-semantic/src/items/trt.rs#L503)):*
> ```XML
>         .keys()
>         .map(|const_id| {
>             let const_long_id = db.lookup_intern_trait_const(*const_id);
> ```

lookup_intern after rebase



_Code quote:_
```XML
b.lookup_intern_trait_const(*const
```
___
*[`crates/cairo-lang-semantic/src/items/trt.rs` line 578 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5431#-NvlhDzFDRfy8vOV6BMF:-NvlhDzFDRfy8vOV6BMG:b-ie3jyr) ([raw file](https://github.com/starkware-libs/cairo/blob/90fb00689981893a4bf85a135f58e293e655301f/crates/cairo-lang-semantic/src/items/trt.rs#L578)):*
> ```XML
>                 }
>                 ast::TraitItem::Constant(constant) => {
>                     let trait_const_id = db.intern_trait_const(TraitConstLongId(
> ```

.intern after rebase



_Code quote:_
```XML
intern_trait_const
```
___
*[`crates/cairo-lang-semantic/src/items/trt.rs` line 773 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5431#-NvlhTzLETLevki69Dox:-NvlhTzLETLevki69Doy:b-wzfysj) ([raw file](https://github.com/starkware-libs/cairo/blob/90fb00689981893a4bf85a135f58e293e655301f/crates/cairo-lang-semantic/src/items/trt.rs#L773)):*
> ```XML
> ) -> Maybe<Vec<Attribute>> {
>     Ok(db.priv_trait_const_data(trait_const_id)?.attributes)
> }
> ```

use the full word "constant" where there is no good reason not to.



_Code quote:_
```XML
#[derive(Clone, Debug, PartialEq, Eq, DebugWithDb)]
#[debug_db(dyn SemanticGroup + 'static)]
pub struct TraitItemConstData {
    pub diagnostics: Diagnostics<SemanticDiagnostic>,
    pub ty: TypeId,
    pub attributes: Vec<Attribute>,
    pub resolver_data: Arc<ResolverData>,
}

// --- Selectors ---

pub fn trait_const_diagnostics(
    db: &dyn SemanticGroup,
    trait_const_id: TraitConstId,
) -> Diagnostics<SemanticDiagnostic> {
    db.priv_trait_const_data(trait_const_id).map(|data| data.diagnostics).unwrap_or_default()
}

/// Query implementation of [crate::db::SemanticGroup::trait_const_resolver_data].
pub fn trait_const_resolver_data(
    db: &dyn SemanticGroup,
    trait_const_id: TraitConstId,
) -> Maybe<Arc<ResolverData>> {
    Ok(db.priv_trait_const_data(trait_const_id)?.resolver_data)
}

pub fn trait_const_attributes(
    db: &dyn SemanticGroup,
    trait_const_id: TraitConstId,
) -> Maybe<Vec<Attribute>> {
    Ok(db.priv_trait_const_data(trait_const_id)?.attributes)
}
```
___
*[`crates/cairo-lang-semantic/src/items/trt.rs` line 798 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5431#-Nvljmif1XUcyhZ67KYl:-Nvljmif1XUcyhZ67KYm:b4viwj) ([raw file](https://github.com/starkware-libs/cairo/blob/90fb00689981893a4bf85a135f58e293e655301f/crates/cairo-lang-semantic/src/items/trt.rs#L798)):*
> ```XML
>     for generic_param in trait_generic_params {
>         resolver.add_generic_param(generic_param.id());
>     }
> ```

Why is this needed? The parent resolver you start from is the trait resolver. So you already have all trait's generic params in the resolver. You don't have more generic params in the constant, so probably no need to do anything related to generic params here.



_Code quote:_
```XML
    for generic_param in trait_generic_params {
        resolver.add_generic_param(generic_param.id());
    }
```
___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 798 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5431#-NvlkEdLBBKm54alyt-W:-NvlkEdLBBKm54alyt-X:b-tz2xez) ([raw file](https://github.com/starkware-libs/cairo/blob/90fb00689981893a4bf85a135f58e293e655301f/crates/cairo-lang-semantic/src/items/tests/trait#L798)):*
> ```
>     type X<T>;
>     const Y: usize;
>     const Y: u64;
> ```

This test is about unsupported items. Thus - (1) this is not the place to test multi definition. (2) the existing const Y here should be removed.
___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 837 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5431#-Nvlkbyd8LAAvhZOp7PV:-Nvlkbyd8LAAvhZOp7PW:bkmsc0w) ([raw file](https://github.com/starkware-libs/cairo/blob/90fb00689981893a4bf85a135f58e293e655301f/crates/cairo-lang-semantic/src/items/tests/trait#L837)):*
> ```
>     ^**^
> 
> error: Not all trait items are implemented. Missing: 'Y'.
> ```

This seems unfortunate - we don't want this diag if we have 2 items with the same name but 1 in the impl. See if it can be removed easily (the names should be a set ) - maybe should be fixed in a separate PR.
___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 849 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5431#-NvllVFLEOmvtt8tjd-z:-NvllVFLEOmvtt8tjd0-:by9xgv0) ([raw file](https://github.com/starkware-libs/cairo/blob/90fb00689981893a4bf85a135f58e293e655301f/crates/cairo-lang-semantic/src/items/tests/trait#L849)):*
> ```
> //! > ==========================================================================
> 
> //! > Test type items in trait/impl.
> ```

Add such a test for const.



_Code quote:_
```
 Test type items in trait/impl.
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5431)* status: 1 of 8 files reviewed, 11 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-defs/src/ids.rs` line 470 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5431#-NvlaZGcD_0gc8VmIRhV:-Nvz_UUfEUlEmHkm40zF:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/90fb00689981893a4bf85a135f58e293e655301f/crates/cairo-lang-defs/src/ids.rs#L470)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Const -> Constant
</blockquote></details>

Done.
___
*[`crates/cairo-lang-defs/src/ids.rs` line 476 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5431#-NvlagBk-H0-0054J1xp:-NvzsUdH2SBEddpNGvjP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/90fb00689981893a4bf85a135f58e293e655301f/crates/cairo-lang-defs/src/ids.rs#L476)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

please rebase and use .lookup_intern()
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/db.rs` line 412 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5431#-Nvlch664XwTqmcr7oaQ:-NvzfjQE-fiaPrRvEiz3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/90fb00689981893a4bf85a135f58e293e655301f/crates/cairo-lang-semantic/src/db.rs#L412)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

const -> constant
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/db.rs` line 462 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5431#-NvldBgY3wrBIjgSGlgM:-NvzfjzQ4EjQvKlAvIxh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/90fb00689981893a4bf85a135f58e293e655301f/crates/cairo-lang-semantic/src/db.rs#L462)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Name all params of type TraitConstId `trait_constant`
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/trt.rs` line 503 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5431#-NvlgywJ-501snMoDQG5:-NvzsW7S0w7RoDY_pco3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/90fb00689981893a4bf85a135f58e293e655301f/crates/cairo-lang-semantic/src/items/trt.rs#L503)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

lookup_intern after rebase
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/trt.rs` line 578 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5431#-NvlhDzFDRfy8vOV6BMF:-NvzsWbXAX5_ba7YMCD3:b-el33om) ([raw file](https://github.com/starkware-libs/cairo/blob/90fb00689981893a4bf85a135f58e293e655301f/crates/cairo-lang-semantic/src/items/trt.rs#L578)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

.intern after rebase
</blockquote></details>

Done. ./
___
*[`crates/cairo-lang-semantic/src/items/trt.rs` line 773 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5431#-NvlhTzLETLevki69Dox:-NvzfmmH20Krh8P7bsI2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/90fb00689981893a4bf85a135f58e293e655301f/crates/cairo-lang-semantic/src/items/trt.rs#L773)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

use the full word "constant" where there is no good reason not to.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/trt.rs` line 798 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5431#-Nvljmif1XUcyhZ67KYl:-Nvzg1lA-VsEIP70gqM3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/90fb00689981893a4bf85a135f58e293e655301f/crates/cairo-lang-semantic/src/items/trt.rs#L798)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Why is this needed? The parent resolver you start from is the trait resolver. So you already have all trait's generic params in the resolver. You don't have more generic params in the constant, so probably no need to do anything related to generic params here.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 798 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5431#-NvlkEdLBBKm54alyt-W:-NvzgVkc90DvETJuaRF5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/90fb00689981893a4bf85a135f58e293e655301f/crates/cairo-lang-semantic/src/items/tests/trait#L798)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

This test is about unsupported items. Thus - (1) this is not the place to test multi definition. (2) the existing const Y here should be removed.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 837 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5431#-Nvlkbyd8LAAvhZOp7PV:-NvzusKiC8kJm6ZYOjQI:bplpgd5) ([raw file](https://github.com/starkware-libs/cairo/blob/90fb00689981893a4bf85a135f58e293e655301f/crates/cairo-lang-semantic/src/items/tests/trait#L837)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

This seems unfortunate - we don't want this diag if we have 2 items with the same name but 1 in the impl. See if it can be removed easily (the names should be a set ) - maybe should be fixed in a separate PR.
</blockquote></details>

it is a set, the error comes from the fact that it is unsupported so it is also 'missing' 
___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 849 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5431#-NvllVFLEOmvtt8tjd-z:-Nvzv4qJEY8iqX_2mLcy:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/90fb00689981893a4bf85a135f58e293e655301f/crates/cairo-lang-semantic/src/items/tests/trait#L849)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Add such a test for const.
</blockquote></details>

Done.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5431)* status: all files reviewed, 4 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 473 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5431#-NwDrD3m0-iRMlP3nJYo:-NwDrD3m0-iRMlP3nJYp:bj0hqeb) ([raw file](https://github.com/starkware-libs/cairo/blob/90f1b5be14c49c5ba1c69e68c8927490780a0096/crates/cairo-lang-semantic/src/db.rs#L473)):*
> ```XML
>         &self,
>         constant_id: TraitConstantId,
>     ) -> Maybe<TraitItemConstantData>;
> ```

rename params similarly in implementations.



_Suggestion:_
```XML
    // Trait constants.
    // ================
    /// Returns the semantic diagnostics of a trait type.
    #[salsa::invoke(items::trt::trait_constant_diagnostics)]
    fn trait_constant_diagnostics(
        &self,
        trait_constant: TraitConstantId,
    ) -> Diagnostics<SemanticDiagnostic>;
    /// Returns the attributes of a trait constants.
    #[salsa::invoke(items::trt::trait_constant_attributes)]
    fn trait_constant_attributes(&self, trait_constant: TraitConstantId) -> Maybe<Vec<Attribute>>;
    /// Returns the resolution resolved_items of a trait constants.
    #[salsa::invoke(items::trt::trait_constant_resolver_data)]
    fn trait_constant_resolver_data(
        &self,
        trait_constant: TraitConstantId,
    ) -> Maybe<Arc<ResolverData>>;
    /// Private query to compute data about a trait constant.
    #[salsa::invoke(items::trt::priv_trait_constant_data)]
    fn priv_trait_constant_data(
        &self,
        trait_constant: TraitConstantId,
    ) -> Maybe<TraitItemConstantData>;
```
___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 798 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5431#-NvlkEdLBBKm54alyt-W:-NwDrrAr5hG3rgcc_Bbd:bhnjfaq) ([raw file](https://github.com/starkware-libs/cairo/blob/90fb00689981893a4bf85a135f58e293e655301f/crates/cairo-lang-semantic/src/items/tests/trait#L798)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

(1) it doesn't mean multi definition should not be tested. Just test it in a separate test.
(2) the existing const Y here should be removed.
___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 837 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5431#-Nvlkbyd8LAAvhZOp7PV:-NwDs6RB5q7uN6HrCjHq:bhd0srs) ([raw file](https://github.com/starkware-libs/cairo/blob/90fb00689981893a4bf85a135f58e293e655301f/crates/cairo-lang-semantic/src/items/tests/trait#L837)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

it is a set, the error comes from the fact that it is unsupported so it is also 'missing'
</blockquote></details>

This should be fixed. Either fix it here, if easy, or add a TODO in the relevant place (and in the diagnostics Monday board)
___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 880 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5431#-NwDsaZr2GE7lXVNDU2X:-NwDsaZr2GE7lXVNDU2Y:b-q57v8q) ([raw file](https://github.com/starkware-libs/cairo/blob/90f1b5be14c49c5ba1c69e68c8927490780a0096/crates/cairo-lang-semantic/src/items/tests/trait#L880)):*
> ```
> trait MyTrait {
>     const X: u32;
> }
> ```

add a TODO to add the impl here once it's supported.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5431)* status: 5 of 9 files reviewed, 4 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 473 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5431#-NwDrD3m0-iRMlP3nJYo:-NwEfW1K9DzGiVsNndTp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/90f1b5be14c49c5ba1c69e68c8927490780a0096/crates/cairo-lang-semantic/src/db.rs#L473)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

rename params similarly in implementations.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 798 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5431#-NvlkEdLBBKm54alyt-W:-NwEgHse769aivWXL08E:b61933d) ([raw file](https://github.com/starkware-libs/cairo/blob/90fb00689981893a4bf85a135f58e293e655301f/crates/cairo-lang-semantic/src/items/tests/trait#L798)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

(1) it doesn't mean multi definition should not be tested. Just test it in a separate test.
(2) the existing const Y here should be removed.
</blockquote></details>

(1) done
(2) it is unsupported for consts 
___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 837 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5431#-Nvlkbyd8LAAvhZOp7PV:-NwElsRdEBLscqwjokkR:botmf4x) ([raw file](https://github.com/starkware-libs/cairo/blob/90fb00689981893a4bf85a135f58e293e655301f/crates/cairo-lang-semantic/src/items/tests/trait#L837)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

This should be fixed. Either fix it here, if easy, or add a TODO in the relevant place (and in the diagnostics Monday board)
</blockquote></details>

added  todo
___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 880 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5431#-NwDsaZr2GE7lXVNDU2X:-NwElsB031ZXqFT4JPDk:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/90f1b5be14c49c5ba1c69e68c8927490780a0096/crates/cairo-lang-semantic/src/items/tests/trait#L880)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

add a TODO to add the impl here once it's supported.
</blockquote></details>

Done.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5431#-:-NwK6kpY3sLqjamxhaub:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
