### PR TITLE
Added ClassHash type and utils.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #2371
- #2369
- #2368 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2368)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 10 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2368)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/interoperability.rs` line 91 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2368#-NPpebpF3r5Qd7-G1LS1:-NPpebpF3r5Qd7-G1LS2:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e656e1d210464cdb87431acb25060c6d4e94ac07/crates/cairo-lang-sierra/src/extensions/modules/starknet/interoperability.rs#L91)):*
> ```XML
> pub type ClassHashConstLibfunc = WrapConstGenLibfunc<ClassHashConstLibfuncWrapped>;
> 
> /// Libfunc for attempting to convert a felt into a contract address.
> ```





_Suggestion:_
```XML
class hash
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/starknet/mod.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2368#-NPpf0lQAiYm-v9FZBm5:-NPpf0lQAiYm-v9FZBm6:bpzb4vx) ([raw file](https://github.com/starkware-libs/cairo/blob/2a54a97008c7aabf2a89d85910da5dd6189eef0c/crates/cairo-lang-sierra-to-casm/src/invocations/starknet/mod.rs#L34)):*
> ```XML
>     match libfunc {
>         StarkNetConcreteLibfunc::ContractAddressConst(libfunc) => {
>             build_contract_address_const(builder, libfunc)
> ```

did you delete this funciton?



_Code quote:_
```XML
build_contract_address_const
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2368)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/starknet/mod.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2368#-NPpf0lQAiYm-v9FZBm5:-NPpmokmEc3fED7MNXF6:bb49ii6) ([raw file](https://github.com/starkware-libs/cairo/blob/2a54a97008c7aabf2a89d85910da5dd6189eef0c/crates/cairo-lang-sierra-to-casm/src/invocations/starknet/mod.rs#L34)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

did you delete this funciton?
</blockquote></details>

yes - as i removed it to be used here for both addresses.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2368)* status: 7 of 11 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/interoperability.rs` line 91 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2368#-NPpebpF3r5Qd7-G1LS1:-NPpq2JlDMKjFEWiadja:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e656e1d210464cdb87431acb25060c6d4e94ac07/crates/cairo-lang-sierra/src/extensions/modules/starknet/interoperability.rs#L91)):*
> ```XML
> pub type ClassHashConstLibfunc = WrapConstGenLibfunc<ClassHashConstLibfuncWrapped>;
> 
> /// Libfunc for attempting to convert a felt into a contract address.
> ```

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 11 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2368#-:-NPps0NUBiNuwj6LW9rn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
