### PR TITLE
Add ImplVar

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2374)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2374** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2374" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2374?utm_source=stack-comment).

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2374)* status: 26 of 27 files reviewed, 1 unresolved discussion (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/items/trt.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2374#-NPq3iPh-0F41Ja8aIQ3:-NPqMKziD9P-HZJEiXsi:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9b8e27001843f232d580cb578c36d645a45b6a1f/crates/cairo-lang-semantic/src/items/trt.rs#L43)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2374)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2374#-:-NPqMpmN8bLH1hginF-1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 18 of 21 files at r1, 1 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2374)* status: all files reviewed, 17 unresolved discussions

___
*[`crates/cairo-lang-lowering/src/scc/mod.rs` line 72 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2374#-NPqPxmt4wy8xmyyDmqx:-NPqPxmt4wy8xmyyDmqy:b9nfwpo) ([raw file](https://github.com/starkware-libs/cairo/blob/e708ffbddb5ae3cafbfda88ee9d304ec71a0b5f2/crates/cairo-lang-lowering/src/scc/mod.rs#L72)):*
> ```XML
>         }
>         GenericFunctionId::Impl(impl_generic_function) => {
>             let impl_function = impl_generic_function.impl_function(db.upcast())?.unwrap();
> ```

expect with a descriptive message



_Code quote:_
```XML
unwrap()
```
___
*[`crates/cairo-lang-lowering/src/scc/mod.rs` line 108 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2374#-NPqQE8K5JjKFbCsKP7D:-NPqQE8K5JjKFbCsKP7E:b-pa9hww) ([raw file](https://github.com/starkware-libs/cairo/blob/e708ffbddb5ae3cafbfda88ee9d304ec71a0b5f2/crates/cairo-lang-lowering/src/scc/mod.rs#L108)):*
> ```XML
>                     // For an impl function, call this method recursively. To avoid cycles, first
>                     // check that the callee is not in this function's SCC.
>                     let impl_function = impl_generic_function.impl_function(db.upcast())?.unwrap();
> ```

same - expect.
Also below - at least 2 more times?



_Code quote:_
```XML
.unwrap(
```
___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 352 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2374#-NPqRWfX7EPnmi3ZbTZm:-NPqRWfX7EPnmi3ZbTZn:b-pb44rm) ([raw file](https://github.com/starkware-libs/cairo/blob/e708ffbddb5ae3cafbfda88ee9d304ec71a0b5f2/crates/cairo-lang-semantic/src/corelib.rs#L352)):*
> ```XML
>     }
>     .unwrap_or_else(|| panic!("{impl_name} is not an impl."));
>     let concrete_impl =
> ```

inline
___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 360 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2374#-NPqRLTo6INUg4fClySO:-NPqRLTo6INUg4fClySP:b-r24op3) ([raw file](https://github.com/starkware-libs/cairo/blob/e708ffbddb5ae3cafbfda88ee9d304ec71a0b5f2/crates/cairo-lang-semantic/src/corelib.rs#L360)):*
> ```XML
>         .ok()
>         .and_then(|functions| functions.get(&method_name).cloned())
>         .unwrap_or_else(|| panic!("no {method_name} in {impl_name}."));
> ```

you now look in the trait.



_Code quote:_
```XML
impl_name
```
___
*[`crates/cairo-lang-semantic/src/types.rs` line 427 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2374#-NPq_ki30MfryvtJ52VC:-NPq_ki30MfryvtJ52VD:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e708ffbddb5ae3cafbfda88ee9d304ec71a0b5f2/crates/cairo-lang-semantic/src/types.rs#L427)):*
> ```XML
> }
> 
> /// Substituted generics in a [ConcreteImplId].
> ```





_Suggestion:_
```XML
Substitutes generics
```
___
*[`crates/cairo-lang-semantic/src/types.rs` line 427 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2374#-NPq_v8vAvRe4-KY9rcI:-NPq_v8vAvRe4-KY9rcJ:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/e708ffbddb5ae3cafbfda88ee9d304ec71a0b5f2/crates/cairo-lang-semantic/src/types.rs#L427)):*
> ```XML
> }
> 
> /// Substituted generics in a [ConcreteImplId].
> ```

?



_Code quote:_
```XML
n a [ConcreteImplId].
```
___
*[`crates/cairo-lang-semantic/src/types.rs` line 447 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2374#-NPqa3xZ77xdbx3Zxfw3:-NPqa3xZ77xdbx3Zxfw4:b-24qbpi) ([raw file](https://github.com/starkware-libs/cairo/blob/e708ffbddb5ae3cafbfda88ee9d304ec71a0b5f2/crates/cairo-lang-semantic/src/types.rs#L447)):*
> ```XML
> }
> 
> /// Substituted generics in a [ConcreteImplId].
> ```

ConcreteImplId?



_Suggestion:_
```XML
Substitutes generics in a [ConcreteImplId].
```
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 33 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2374#-NPqaMS65hV8e9s66ECj:-NPqaMS79Q556EBfM_2V:b-2ht3vo) ([raw file](https://github.com/starkware-libs/cairo/blob/e708ffbddb5ae3cafbfda88ee9d304ec71a0b5f2/crates/cairo-lang-semantic/src/expr/inference.rs#L33)):*
> ```XML
> #[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
> pub struct ImplVar {
>     pub id: usize,
> ```

what is id? why usize?
___
*[`crates/cairo-lang-semantic/src/items/function_with_body.rs` line 170 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2374#-NPqb_s19LZEgGY7RkHB:-NPqb_s19LZEgGY7RkHC:bm1kumz) ([raw file](https://github.com/starkware-libs/cairo/blob/e708ffbddb5ae3cafbfda88ee9d304ec71a0b5f2/crates/cairo-lang-semantic/src/items/function_with_body.rs#L170)):*
> ```XML
>         .into_iter()
>         .map(|function_id| function_id.try_get_function_with_body_id(db))
>         .collect::<Maybe<Option<Vec<_>>>>()?
> ```

vec<Option> ?



_Code quote:_
```XML
Option<Vec
```
___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 29 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2374#-NPqbgcG0CmlMpUAqAbM:-NPqbgcH6ovKaGLR0Oiv:b-jlmcj6) ([raw file](https://github.com/starkware-libs/cairo/blob/e708ffbddb5ae3cafbfda88ee9d304ec71a0b5f2/crates/cairo-lang-semantic/src/items/functions.rs#L29)):*
> ```XML
> };
> 
> /// A generic function of a concrete impl.
> ```

update



_Code quote:_
```XML
of a concrete impl
```
___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 33 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2374#-NPqbn-n4kqXHDCxIpVU:-NPqbn-n4kqXHDCxIpVV:bi6fpd8) ([raw file](https://github.com/starkware-libs/cairo/blob/e708ffbddb5ae3cafbfda88ee9d304ec71a0b5f2/crates/cairo-lang-semantic/src/items/functions.rs#L33)):*
> ```XML
> pub struct ImplGenericFunctionId {
>     pub impl_id: ImplId,
>     pub function: TraitFunctionId,
> ```

please add a TODO to makes these private and have a ctor that verifies the impl impls the trait that is relevant for the function.



_Code quote:_
```XML
    pub impl_id: ImplId,
    pub function: TraitFunctionId,
```
___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 53 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2374#-NPqcJrm7GjwlEnL-kQD:-NPqcJrm7GjwlEnL-kQE:b-jlmcj6) ([raw file](https://github.com/starkware-libs/cairo/blob/e708ffbddb5ae3cafbfda88ee9d304ec71a0b5f2/crates/cairo-lang-semantic/src/items/functions.rs#L53)):*
> ```XML
>     /// A generic extern function.
>     Extern(ExternFunctionId),
>     /// A generic function of a concrete impl.
> ```

update



_Code quote:_
```XML
A generic function of a concrete impl
```
___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 128 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2374#-NPqdYYK5jCkSTRtjnvK:-NPqdYYK5jCkSTRtjnvL:b-37u38f) ([raw file](https://github.com/starkware-libs/cairo/blob/e708ffbddb5ae3cafbfda88ee9d304ec71a0b5f2/crates/cairo-lang-semantic/src/items/functions.rs#L128)):*
> ```XML
>             GenericFunctionId::Impl(id) => {
>                 // Note: Only the trait title is returned.
>                 Ok(FunctionTitleId::Trait(id.function))
> ```

consider returning the concrete impl function title if the impl is concrete.
And/Or - if it's only used in the language server - move this logic there.
___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 219 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2374#-NPqeI_K5PCyXdLs2eFa:-NPqeI_K5PCyXdLs2eFb:b4kzxvn) ([raw file](https://github.com/starkware-libs/cairo/blob/e708ffbddb5ae3cafbfda88ee9d304ec71a0b5f2/crates/cairo-lang-semantic/src/items/functions.rs#L219)):*
> ```XML
>             GenericFunctionId::Impl(impl_generic_function_id) => {
>                 if let Some(impl_function) = impl_generic_function_id.impl_function(db)? {
>                     Ok(Some(FunctionWithBodyId::Impl(impl_function)))
> ```

move OKs out of the outmost match



_Code quote:_
```XML
Ok
```
___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 254 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2374#-NPqf4Pd--2qL7EbPzWQ:-NPqf4Pd--2qL7EbPzWR:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e708ffbddb5ae3cafbfda88ee9d304ec71a0b5f2/crates/cairo-lang-semantic/src/items/functions.rs#L254)):*
> ```XML
>                     function,
>                 )? else {
>                     return Ok(None);
> ```





_Suggestion:_
```XML
                if let Some(impl_function) = db.impl_function_by_trait_function(
                    concrete_impl_id.impl_def_id(db),
                    function,
                )? {
                    GenericFunctionWithBodyId::Impl(ImplGenericFunctionWithBodyId {
                    concrete_impl_id,
                    function: impl_function,
                })} else {
                    Ok(None)
                }
                
```
___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 261 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2374#-NPqfGnC8b5zya8hwnD1:-NPqfGnC8b5zya8hwnD2:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e708ffbddb5ae3cafbfda88ee9d304ec71a0b5f2/crates/cairo-lang-semantic/src/items/functions.rs#L261)):*
> ```XML
>                 })
>             }
>             _ => return Ok(None),
> ```





_Suggestion:_
```XML
Ok(None),
```
___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 375 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2374#-NPqfRr71iMQjqffIeBw:-NPqfRr71iMQjqffIeBx:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e708ffbddb5ae3cafbfda88ee9d304ec71a0b5f2/crates/cairo-lang-semantic/src/items/functions.rs#L375)):*
> ```XML
>         };
>         Ok(Some(db.intern_concrete_function_with_body(ConcreteFunctionWithBody {
>             generic_function,
> ```





_Suggestion:_
```XML
        Ok(if let Some(generic_function) = GenericFunctionWithBodyId::from_generic(
            db,
            self.generic_function,
        )? {
            Some(db.intern_concrete_function_with_body(ConcreteFunctionWithBody {
            generic_function,
            generic_args: self.generic_args.clone(),
        }))
            } else {
            None
        })
```

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 1 of 21 files at r1, 6 of 7 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2374)* status: all files reviewed, 17 unresolved discussions

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2374)* status: all files reviewed, 5 unresolved discussions

___
*[`crates/cairo-lang-semantic/src/types.rs` line 427 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2374#-NPq_v8vAvRe4-KY9rcI:-NPwAo5T9XI6lpz9Rcck:b2u5xe2) ([raw file](https://github.com/starkware-libs/cairo/blob/e708ffbddb5ae3cafbfda88ee9d304ec71a0b5f2/crates/cairo-lang-semantic/src/types.rs#L427)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

?
</blockquote></details>

This will be gone in a few PRs.
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 33 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2374#-NPqaMS65hV8e9s66ECj:-NPwAv4H-m4v8OXSqS9X:bxb0kje) ([raw file](https://github.com/starkware-libs/cairo/blob/e708ffbddb5ae3cafbfda88ee9d304ec71a0b5f2/crates/cairo-lang-semantic/src/expr/inference.rs#L33)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

what is id? why usize?
</blockquote></details>

Same as TypeVar.
___
*[`crates/cairo-lang-semantic/src/items/function_with_body.rs` line 170 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2374#-NPqb_s19LZEgGY7RkHB:-NPw7vdt5YP2tSQbCddL:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e708ffbddb5ae3cafbfda88ee9d304ec71a0b5f2/crates/cairo-lang-semantic/src/items/function_with_body.rs#L170)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

vec<Option> ?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 254 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2374#-NPqf4Pd--2qL7EbPzWQ:-NPw9XJj9mceUzoFxYs6:b43qgkx) ([raw file](https://github.com/starkware-libs/cairo/blob/e708ffbddb5ae3cafbfda88ee9d304ec71a0b5f2/crates/cairo-lang-semantic/src/items/functions.rs#L254)):*
> ```XML
>                     function,
>                 )? else {
>                     return Ok(None);
> ```

Noted. Early return is better IMO.
___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 261 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2374#-NPqfGnC8b5zya8hwnD1:-NPw9lZD8xlUtGLbYu-8:b-74v7wp) ([raw file](https://github.com/starkware-libs/cairo/blob/e708ffbddb5ae3cafbfda88ee9d304ec71a0b5f2/crates/cairo-lang-semantic/src/items/functions.rs#L261)):*
> ```XML
>                 })
>             }
>             _ => return Ok(None),
> ```

Other branches would need to be wrapped with Some.
___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 375 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2374#-NPqfRr71iMQjqffIeBw:-NPwA-CYDlzfh9VmTs2L:bwygxsx) ([raw file](https://github.com/starkware-libs/cairo/blob/e708ffbddb5ae3cafbfda88ee9d304ec71a0b5f2/crates/cairo-lang-semantic/src/items/functions.rs#L375)):*
> ```XML
>         };
>         Ok(Some(db.intern_concrete_function_with_body(ConcreteFunctionWithBody {
>             generic_function,
> ```

Noted.

**Pull request merged**
