### PR TITLE
Add call_contract_syscall.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1425)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1425)* status: 9 of 10 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`crates/sierra_to_casm/src/invocations/starknet/interoperability.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1425#-NJokCAu2SFwQuoIW0Wj:-NJokCAu2SFwQuoIW0Wk:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/54eb9b3c5175ed97027d152bd745f0ee7bd25c25/crates/sierra_to_casm/src/invocations/starknet/interoperability.rs#L28)):*
> ```XML
> 
>     let concrete_array_type = &libfunc.signature().param_signatures[2].ty;
>     let (gas_builtin, original_system, contract_address, call_data) = match builder.refs {
> ```





_Suggestion:_
```XML
    let (gas_builtin, system, contract_address, call_data) = match builder.refs {
```
___
*[`crates/sierra_to_casm/src/invocations/starknet/interoperability.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1425#-NJokE8L9U9CMlwWkGnW:-NJokE8M69BalhqSyU9_:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/54eb9b3c5175ed97027d152bd745f0ee7bd25c25/crates/sierra_to_casm/src/invocations/starknet/interoperability.rs#L58)):*
> ```XML
>     let selector_imm = casm_builder.add_var(ResOperand::Immediate(selector_imm));
>     let gas_builtin = casm_builder.add_var(ResOperand::Deref(gas_builtin));
>     let contract_address = casm_builder.add_var(ResOperand::Deref(contract_address));
> ```





_Suggestion:_
```XML
    let mut casm_builder = CasmBuilder::default();
    let system = casm_builder.add_var(system);
    let selector_imm = casm_builder.add_var(ResOperand::Immediate(selector_imm));
    let gas_builtin = casm_builder.add_var(ResOperand::Deref(gas_builtin));
    let contract_address = casm_builder.add_var(ResOperand::Deref(contract_address));
    let call_data_start = casm_builder.add_var(ResOperand::Deref(call_data.start));
    let call_data_end = casm_builder.add_var(ResOperand::Deref(call_data.end));
    casm_build_extend! {casm_builder,
        tempvar selector;
        assert selector = selector_imm;
        let original_system = system;
        assert *(system++) = selector;
         assert *(system++) = gas_builtin;
        assert *(system++) = contract_address;
        assert *(system++) = call_data_start;
        assert *(system++) = call_data_end;
        hint SystemCall { system: original_system };

        let updated_gas_builtin = *(system++);
        // `revert_reason` is 0 on success, nonzero on failure/revert.
        tempvar revert_reason;
        assert *(system++) = revert_reason;
        let res_start = *(system++);
        let res_end = *(system++);
        jump Failure if revert_reason != 0;
    };
```
___
*[`crates/sierra_to_casm/src/invocations/starknet/interoperability_test.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1425#-NJooX_P84gPjecu38m_:-NJooX_P84gPjecu38ma:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/54eb9b3c5175ed97027d152bd745f0ee7bd25c25/crates/sierra_to_casm/src/invocations/starknet/interoperability_test.rs#L18)):*
> ```XML
>     let gas_builtin = deref!([fp + 1]);
>     let system = deref!([fp + 2]);
>     let contract_address = deref!([fp + 3]);
> ```





_Suggestion:_
```XML
    let gas_builtin = ref_expr!([fp + 1]);
    let system = ref_expr!([fp + 2]);
    let contract_address = ref_expr!([fp + 3]);
    let call_data = ref_expr!(deref!([fp + 5]), deref!([fp + 6]));
    assert_eq!(
        compile_libfunc("call_contract_syscall", vec![gas_builtin, system, contract_address]),
```
___
*[`crates/sierra_to_casm/src/invocations/starknet/interoperability_test.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1425#-NJopJH4CyVVSx8gE145:-NJopJH4CyVVSx8gE146:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/54eb9b3c5175ed97027d152bd745f0ee7bd25c25/crates/sierra_to_casm/src/invocations/starknet/interoperability_test.rs#L57)):*
> ```XML
>                         ref_expr!([[fp + 2] + 5]),
>                         ref_expr!([fp + 2] + 9),
>                         ReferenceExpression {
> ```





_Suggestion:_
```XML
                        ref_expr!([[fp + 2] + 7], [[fp + 2] + 8]),
```
___
*[`crates/sierra_to_casm/src/invocations/starknet/interoperability_test.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1425#-NJopSCn4WsYOrl-_8ZI:-NJopSCn4WsYOrl-_8ZJ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/54eb9b3c5175ed97027d152bd745f0ee7bd25c25/crates/sierra_to_casm/src/invocations/starknet/interoperability_test.rs#L72)):*
> ```XML
>                         ref_expr!([fp + 2] + 9),
>                         ref_expr!([ap - 1]),
>                         ReferenceExpression {
> ```





_Suggestion:_
```XML
                        ref_expr!([[fp + 2] + 7], [[fp + 2] + 8]),
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1425)* status: all files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @yuvalsw)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/sierra_to_casm/src/invocations/starknet/interoperability_test.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1425#-NJooX_P84gPjecu38m_:-NJozPmN9dciY_53F72W:b-pxxgri) ([raw file](https://github.com/starkware-libs/cairo/blob/54eb9b3c5175ed97027d152bd745f0ee7bd25c25/crates/sierra_to_casm/src/invocations/starknet/interoperability_test.rs#L18)):*
> ```XML
>     let gas_builtin = deref!([fp + 1]);
>     let system = deref!([fp + 2]);
>     let contract_address = deref!([fp + 3]);
> ```

I won't be able to use the refer experts in the casm macro.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1425)* status: 8 of 10 files reviewed, 5 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/sierra_to_casm/src/invocations/starknet/interoperability.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1425#-NJokCAu2SFwQuoIW0Wj:-NJozDZGAxaUIQ8ev5UP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/54eb9b3c5175ed97027d152bd745f0ee7bd25c25/crates/sierra_to_casm/src/invocations/starknet/interoperability.rs#L28)):*
> ```XML
> 
>     let concrete_array_type = &libfunc.signature().param_signatures[2].ty;
>     let (gas_builtin, original_system, contract_address, call_data) = match builder.refs {
> ```

Done.
___
*[`crates/sierra_to_casm/src/invocations/starknet/interoperability.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1425#-NJokE8L9U9CMlwWkGnW:-NJozE4o5gw3W0ZVJCjZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/54eb9b3c5175ed97027d152bd745f0ee7bd25c25/crates/sierra_to_casm/src/invocations/starknet/interoperability.rs#L58)):*
> ```XML
>     let selector_imm = casm_builder.add_var(ResOperand::Immediate(selector_imm));
>     let gas_builtin = casm_builder.add_var(ResOperand::Deref(gas_builtin));
>     let contract_address = casm_builder.add_var(ResOperand::Deref(contract_address));
> ```

Done.
___
*[`crates/sierra_to_casm/src/invocations/starknet/interoperability_test.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1425#-NJopJH4CyVVSx8gE145:-NJozaZVEX8xm9CVUozN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/54eb9b3c5175ed97027d152bd745f0ee7bd25c25/crates/sierra_to_casm/src/invocations/starknet/interoperability_test.rs#L57)):*
> ```XML
>                         ref_expr!([[fp + 2] + 5]),
>                         ref_expr!([fp + 2] + 9),
>                         ReferenceExpression {
> ```

Done.
___
*[`crates/sierra_to_casm/src/invocations/starknet/interoperability_test.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1425#-NJopSCn4WsYOrl-_8ZI:-NJozaG2AccFQFtm5vTR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/54eb9b3c5175ed97027d152bd745f0ee7bd25c25/crates/sierra_to_casm/src/invocations/starknet/interoperability_test.rs#L72)):*
> ```XML
>                         ref_expr!([fp + 2] + 9),
>                         ref_expr!([ap - 1]),
>                         ReferenceExpression {
> ```

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1425)* status: 8 of 11 files reviewed, 5 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/sierra_to_casm/src/invocations/starknet/interoperability_test.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1425#-NJooX_P84gPjecu38m_:-NJp6MMRCcolT6osPUd_:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/54eb9b3c5175ed97027d152bd745f0ee7bd25c25/crates/sierra_to_casm/src/invocations/starknet/interoperability_test.rs#L18)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I won't be able to use the refer experts in the casm macro.
</blockquote></details>

done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1425#-:-NJp9uHZAC6Z88ya_wVQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
