### PR TITLE
Fix sub-list

### PR DESCRIPTION
**Pull request by gaetbout**
Fixing sub-list alignement in documentation

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2697)

### CODE REVIEW

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2697#-:-NSHXUcRCyKB_2T71_pa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gaetbout)

**Review by spapinistarkware — APPROVED** [review]
The file has moved, can u please update the pr?
Also , please put someone as a reviewer when u open a pr, so we wont miss it. Me or orizi

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2697#-:-NSHXWLw9-LAXc-hDJUJ:b-klkz8m)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gaetbout)

**Comment by gaetbout** [comment]
@spapinistarkware 
Done 👍

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2697#-:-NSH_w-J8olrumEA8pve:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gaetbout)

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2697)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gaetbout)

**Pull request merged**
