### PR TITLE
Inference queues

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3347)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3347** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3347" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/3347?utm_source=stack-comment).

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 22 of 33 files at r1, 5 of 5 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3347)* status: all files reviewed, 9 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 115 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3347#-NXcdW6eCq8LKaQXDR-S:-NXcdW6eCq8LKaQXDR-T:b-t0lo7g) ([raw file](https://github.com/starkware-libs/cairo/blob/fe7e2942d63393e552d72293dc96024587e1f1dc/crates/cairo-lang-semantic/src/expr/inference.rs#L115)):*
> ```XML
>     ConstInferenceNotSupported,
> 
>     // TODO: These are only used for external interface.
> ```

assign



_Code quote:_
```XML
    // TODO: These are only used for external interface.
```
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 167 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3347#-NXcdcpW4hyfWOk72rJT:-NXcdcpW4hyfWOk72rJU:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/fe7e2942d63393e552d72293dc96024587e1f1dc/crates/cairo-lang-semantic/src/expr/inference.rs#L167)):*
> ```XML
>             InferenceError::Failed(diagnostic_added) => *diagnostic_added,
>             // TODO(spapini): Better save the DiagnosticAdded on the variable.
>             // InferenceError::AlreadyReported => skip_diagnostic(),
> ```

?



_Code quote:_
```XML
// InferenceError::AlreadyReported => skip_diagnostic(),
```
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 488 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3347#-NXceF110-zvq26LiQIa:-NXceF110-zvq26LiQIb:b-t0lo7g) ([raw file](https://github.com/starkware-libs/cairo/blob/fe7e2942d63393e552d72293dc96024587e1f1dc/crates/cairo-lang-semantic/src/expr/inference.rs#L488)):*
> ```XML
>         mut lookup_context: ImplLookupContext,
>     ) -> InferenceResult<SolutionSet<(CanonicalImpl, CanonicalMapping)>> {
>         // TODO: This is done twice.
> ```

assign



_Code quote:_
```XML
/ TODO: This is done twice.
```
___
*[`crates/cairo-lang-semantic/src/expr/inference/canonic.rs` line 207 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3347#-NXcerXM2UQw8A329mBe:-NXcerXM2UQw8A329mBf:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/fe7e2942d63393e552d72293dc96024587e1f1dc/crates/cairo-lang-semantic/src/expr/inference/canonic.rs#L207)):*
> ```XML
> }
> 
> // Mapper rewriter. Maps variables according to a given [VarMapping].
> ```





_Suggestion:_
```XML
/// Mapper rewriter. Maps variables according to a given [VarMapping].
```
___
*[`crates/cairo-lang-semantic/src/expr/inference/conform.rs` line 14 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3347#-NXcezNe4J8DdjA70ofv:-NXcezNf54G8d2lNqJjG:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/fe7e2942d63393e552d72293dc96024587e1f1dc/crates/cairo-lang-semantic/src/expr/inference/conform.rs#L14)):*
> ```XML
> };
> 
> pub trait InferenceConform {
> ```

doc
___
*[`crates/cairo-lang-semantic/src/expr/inference/infers.rs` line 18 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3347#-NXcfAtD3W0cBCbN5_6G:-NXcfAtD3W0cBCbN5_6H:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/fe7e2942d63393e552d72293dc96024587e1f1dc/crates/cairo-lang-semantic/src/expr/inference/infers.rs#L18)):*
> ```XML
> };
> 
> pub trait InferenceEmbeddings {
> ```

doc
___
*[`crates/cairo-lang-semantic/src/expr/test_data/method` line 109 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3347#-NXcfiwO7Z5k3mopok5L:-NXcfiwO7Z5k3mopok5M:b-84z1fx) ([raw file](https://github.com/starkware-libs/cairo/blob/fe7e2942d63393e552d72293dc96024587e1f1dc/crates/cairo-lang-semantic/src/expr/test_data/method#L109)):*
> ```
>       ^***********************^
> 
> error: Candidate impl test::AnotherOptionTraitImpl::<core::felt252> has a free variable
> ```

i don't think this is understandable - can you make this clearer?



_Code quote:_
```
a free variable
```
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1113 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3347#-NXcgFWY5-de3_DHVyum:-NXcgFWY5-de3_DHVyun:b-t0lo7g) ([raw file](https://github.com/starkware-libs/cairo/blob/fe7e2942d63393e552d72293dc96024587e1f1dc/crates/cairo-lang-semantic/src/items/imp.rs#L1113)):*
> ```XML
>     // Check fully resolved.
>     if let Some((stable_ptr, inference_err)) = resolver.inference().finalize() {
>         // TODO: Better location.
> ```

assign
___
*[`crates/cairo-lang-semantic/src/items/trt.rs` line 227 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3347#-NXcgPDQ7mOMuk_iEPjq:-NXcgPDQ7mOMuk_iEPjr:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/fe7e2942d63393e552d72293dc96024587e1f1dc/crates/cairo-lang-semantic/src/items/trt.rs#L227)):*
> ```XML
>     // Check fully resolved.
>     if let Some((stable_ptr, inference_err)) = resolver.inference().finalize() {
>         // TODO: Better location.
> ```

doc

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3347)* status: all files reviewed, 9 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 115 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3347#-NXcdW6eCq8LKaQXDR-S:-NXcpfxH6mdg8NurqkWv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fe7e2942d63393e552d72293dc96024587e1f1dc/crates/cairo-lang-semantic/src/expr/inference.rs#L115)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

assign
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 167 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3347#-NXcdcpW4hyfWOk72rJT:-NXcplMz9N1zRjykMfgh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fe7e2942d63393e552d72293dc96024587e1f1dc/crates/cairo-lang-semantic/src/expr/inference.rs#L167)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 488 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3347#-NXceF110-zvq26LiQIa:-NXcpxjn8p1AaNwzNmaz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fe7e2942d63393e552d72293dc96024587e1f1dc/crates/cairo-lang-semantic/src/expr/inference.rs#L488)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

assign
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/inference/canonic.rs` line 207 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3347#-NXcerXM2UQw8A329mBe:-NXcq0N_A-KzHXwObuNg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fe7e2942d63393e552d72293dc96024587e1f1dc/crates/cairo-lang-semantic/src/expr/inference/canonic.rs#L207)):*
> ```XML
> }
> 
> // Mapper rewriter. Maps variables according to a given [VarMapping].
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/inference/conform.rs` line 14 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3347#-NXcezNe4J8DdjA70ofv:-NXcq8UF6hmJCYZ_LiYT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fe7e2942d63393e552d72293dc96024587e1f1dc/crates/cairo-lang-semantic/src/expr/inference/conform.rs#L14)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/inference/infers.rs` line 18 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3347#-NXcfAtD3W0cBCbN5_6G:-NXcqOUC1eScI_xpXdQn:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fe7e2942d63393e552d72293dc96024587e1f1dc/crates/cairo-lang-semantic/src/expr/inference/infers.rs#L18)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/method` line 109 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3347#-NXcfiwO7Z5k3mopok5L:-NXcs4ih7D6c4REzK_j-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fe7e2942d63393e552d72293dc96024587e1f1dc/crates/cairo-lang-semantic/src/expr/test_data/method#L109)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i don't think this is understandable - can you make this clearer?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1113 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3347#-NXcgFWY5-de3_DHVyum:-NXcsH0sEWyt-RVZJU7Y:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fe7e2942d63393e552d72293dc96024587e1f1dc/crates/cairo-lang-semantic/src/items/imp.rs#L1113)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

assign
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/trt.rs` line 227 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3347#-NXcgPDQ7mOMuk_iEPjq:-NXcsFUc5dO0IKH-UxIZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fe7e2942d63393e552d72293dc96024587e1f1dc/crates/cairo-lang-semantic/src/items/trt.rs#L227)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3347)* status: 30 of 34 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference/solver.rs` line 51 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3347#-NXcy0Bz2987jfeuSm-J:-NXcy0Bz2987jfeuSm-K:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/212a2c1dd5a49e6e08398914b2414b9a7d5c1bb8/crates/cairo-lang-semantic/src/expr/inference/solver.rs#L51)):*
> ```XML
>             Ambiguity::FreeVariable { impl_id, var: _ } => {
>                 format!(
>                     "Candidate impl {:?} has a free variable with no constraints.",
> ```





_Suggestion:_
```XML
Candidate impl {:?} has a generic param with no constraints.
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 8 files at r4, 1 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3347)* status: 31 of 34 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3347)* status: 33 of 34 files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3347#-:-NXcybr3BlsL3aUamAh2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
