### PR TITLE
fixed error on unsupported matched types

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4814)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4814)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/diagnostic.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4814#-NoGPFsj2dUiVcO8pg4T:-NoGPFsj2dUiVcO8pg4U:b-2teimb) ([raw file](https://github.com/starkware-libs/cairo/blob/b2d635890e9ea7c2bf43fd9df1113392d3360cdf/crates/cairo-lang-lowering/src/diagnostic.rs#L57)):*
> ```XML
>                 "Cannot desnap a non copyable type.".into()
>             }
>             LoweringDiagnosticKind::UnsupportedMatchedType(matched_type) => format!("Unsupported matched type. Type: `{}`.", matched_type)
> ```

format and fix clippy.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4814)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/diagnostic.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4814#-NoGPFsj2dUiVcO8pg4T:-NoGVEM5EosnAnrAslmO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b2d635890e9ea7c2bf43fd9df1113392d3360cdf/crates/cairo-lang-lowering/src/diagnostic.rs#L57)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

format and fix clippy.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4814)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/diagnostic.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4814#-NoGWw6YAo6ZA_Ux94YL:-NoGWw6YAo6ZA_Ux94YM:beartuj) ([raw file](https://github.com/starkware-libs/cairo/blob/3e720f4a345467eb92712acafd0c63bf337c91eb/crates/cairo-lang-lowering/src/diagnostic.rs#L57)):*
> ```XML
>                 "Cannot desnap a non copyable type.".into()
>             }
>             LoweringDiagnosticKind::UnsupportedMatchedType(matched_type) => format!("Unsupported matched type. Type: `{}`.", matched_type),
> ```

i don't know what is going with the formatter - but this is not valid.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4814)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4814)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/diagnostic.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4814#-NoGWw6YAo6ZA_Ux94YL:-NoG_BDy9Gge9BIgPxYJ:b-wndck3) ([raw file](https://github.com/starkware-libs/cairo/blob/3e720f4a345467eb92712acafd0c63bf337c91eb/crates/cairo-lang-lowering/src/diagnostic.rs#L57)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i don't know what is going with the formatter - but this is not valid.
</blockquote></details>

is it just line length?

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4814#-:-NoGcd2X4YZNIPX24I6r:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4814)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
