### PR TITLE
Fix attribute parsing with only an identifier after.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4407)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4407)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 2245 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4407#-NjHNpXmEMTbY36bdMOD:-NjHNpXmEMTbY36bdMOE:brf5s7v) ([raw file](https://github.com/starkware-libs/cairo/blob/fb55ebd2a233944df98261c3f0e11a52ed93c08e/crates/cairo-lang-parser/src/parser.rs#L2245)):*
> ```XML
> 
> 
>     // Skips a taken node, from the current offset adjusted to include the current token. Use it if the skipped node was the last to be taken.
> ```

make actual doc.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4407)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 2245 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4407#-NjHNpXmEMTbY36bdMOD:-NjHf5YXABlpUk0RYx28:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fb55ebd2a233944df98261c3f0e11a52ed93c08e/crates/cairo-lang-parser/src/parser.rs#L2245)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

make actual doc.
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4407)* status: 0 of 2 files reviewed, 1 unresolved discussion

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4407#-:-NjI30Hc2ri283IPIfl7:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved

**Pull request merged**
