### PR TITLE
add storage sub components

### PR DESCRIPTION
**Pull request by Tomer-StarkWare**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5950)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5950)* status: 4 of 8 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`corelib/src/starknet/storage.cairo` line 147 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5950#-O0sMbIc-5gxdhRYDKMB:-O0sMbIc-5gxdhRYDKMC:bqa288f) ([raw file](https://github.com/starkware-libs/cairo/blob/08025bc630a2d4308d83718a409c819ceacf1cb1/corelib/src/starknet/storage.cairo#L147)):*
> ```Cairo
> pub struct StoragePath<T> {
>     pub hash_state: StoragePathHashState,
> }
> ```

why do these require pub?

we might need a function - but no reason for the user to read directly.



_Code quote:_
```Cairo
pub struct StoragePath<T> {
    pub hash_state: StoragePathHashState,
}
```
___
*[`corelib/src/starknet/storage.cairo` line 440 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5950#-O0sMdTDCvUeeiJmd6Y9:-O0sMdTE0hyCH_FFKBh8:b-7jl271) ([raw file](https://github.com/starkware-libs/cairo/blob/08025bc630a2d4308d83718a409c819ceacf1cb1/corelib/src/starknet/storage.cairo#L440)):*
> ```Cairo
> /// A struct for delaying the creation of a storage path, used for lazy evaluation in storage nodes.
> pub struct PendingStoragePath<T> {
>     pub hash_state: StoragePathHashState,
> ```

same.

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5950)* status: 4 of 8 files reviewed, 3 unresolved discussions (waiting on @orizi and @Tomer-StarkWare)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5950#-O0sT3Dj5W3NVDqe1bBA):*
Change to fit the commit.



_Code quote:_
```
add storage sub components
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5950)* status: 4 of 8 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/contracts/erc20_new.cairo` line 41 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5950#-O0sV8s73yAK6PIT1DqM:-O0sV8s73yAK6PIT1DqN:boyu9yq) ([raw file](https://github.com/starkware-libs/cairo/blob/08025bc630a2d4308d83718a409c819ceacf1cb1/crates/cairo-lang-starknet/cairo_level_tests/contracts/erc20_new.cairo#L41)):*
> ```Cairo
> 
> #[starknet::contract]
> mod erc_20_new {
> ```

this is just a contract.

what i would expect instead would be a component, used (not implemented using #[starknet::contract]).

all the implementation should happen out of the module.

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5950)* status: 1 of 9 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5950#-O0sT3Dj5W3NVDqe1bBA):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Change to fit the commit.
</blockquote></details>

Done.
___
*[`corelib/src/starknet/storage.cairo` line 147 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5950#-O0sMbIc-5gxdhRYDKMB:-O0soIuTAh0GBnuom3nH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/08025bc630a2d4308d83718a409c819ceacf1cb1/corelib/src/starknet/storage.cairo#L147)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why do these require pub?

we might need a function - but no reason for the user to read directly.
</blockquote></details>

Done.
___
*[`corelib/src/starknet/storage.cairo` line 440 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5950#-O0sMdTDCvUeeiJmd6Y9:-O0soL0DETxVaixEDnc0:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/08025bc630a2d4308d83718a409c819ceacf1cb1/corelib/src/starknet/storage.cairo#L440)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

same.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5950)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`corelib/src/starknet/storage.cairo` line 458 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5950#-O0sqY6-3pSSfc754Dyy:-O0sqY6-3pSSfc754Dyz:b-v5tyee) ([raw file](https://github.com/starkware-libs/cairo/blob/1a4d2d492b1e0849d11af8b8ee9dcdf38e28f276/corelib/src/starknet/storage.cairo#L458)):*
> ```Cairo
> /// A trait for creating a `PendingStoragePath` from a hash state and a key.
> pub trait PendingStoragePathTrait<T> {
>     fn new(hash_state: StoragePathHashState, pending_key: felt252) -> PendingStoragePath<T>;
> ```

can you just get a `StoragePath` here to avoid the `StoragePathProperties` trait?



_Code quote:_
```Cairo
StoragePathHashState
```
___
*[`crates/cairo-lang-starknet/cairo_level_tests/contracts/erc20_new.cairo` line 2 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5950#-O0srFkbEYnlrSAw7A-h:-O0srFkbEYnlrSAw7A-i:bq52qcc) ([raw file](https://github.com/starkware-libs/cairo/blob/1a4d2d492b1e0849d11af8b8ee9dcdf38e28f276/crates/cairo-lang-starknet/cairo_level_tests/contracts/erc20_new.cairo#L2)):*
> ```Cairo
> use starknet::ContractAddress;
> use starknet::storage::{StoragePathEntry, Map};
> ```

if this is just a simple test for an external usage - make it much much simpler than a full erc20.

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5950)* status: 2 of 9 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`corelib/src/starknet/storage.cairo` line 458 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5950#-O0sqY6-3pSSfc754Dyy:-O0tBPFiBI8R6FMDj6Cc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1a4d2d492b1e0849d11af8b8ee9dcdf38e28f276/corelib/src/starknet/storage.cairo#L458)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can you just get a `StoragePath` here to avoid the `StoragePathProperties` trait?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/contracts/erc20_new.cairo` line 2 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5950#-O0srFkbEYnlrSAw7A-h:-O0tBOFZ-cHNwD6KPDdM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1a4d2d492b1e0849d11af8b8ee9dcdf38e28f276/crates/cairo-lang-starknet/cairo_level_tests/contracts/erc20_new.cairo#L2)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

if this is just a simple test for an external usage - make it much much simpler than a full erc20.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5950)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`corelib/src/starknet/storage.cairo` line 150 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5950#-O0tCazjAVWz6x2Hvj7k:-O0tCazjAVWz6x2Hvj7l:b-k6yroc) ([raw file](https://github.com/starkware-libs/cairo/blob/38bbcc233eb5408e6e615ba68fbc3a2c5e4e1dac/corelib/src/starknet/storage.cairo#L150)):*
> ```Cairo
> 
> /// A trait for the properties of a storage path.
> pub trait StoragePathProperties<T> {
> ```

remove the unused trait.

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5950)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`corelib/src/starknet/storage.cairo` line 150 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5950#-O0tCazjAVWz6x2Hvj7k:-O0tLOOn9Wy71A91PUiK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/38bbcc233eb5408e6e615ba68fbc3a2c5e4e1dac/corelib/src/starknet/storage.cairo#L150)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove the unused trait.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5950#-:-O0tLorBC-6rAIBAvEXU:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5950#-:-O0wSaLZ54V1uG2oy5K3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Tomer-StarkWare)

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 2 of 8 files at r1, 2 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5950)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @orizi and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/contracts.cairo` line 15 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5950#-O0wVdxsADH3s5qEVy3k:-O0wVdxt7qpLWM4wW-ZF:b-jqri9w) ([raw file](https://github.com/starkware-libs/cairo/blob/fc4d537e9bcebec5b73a453c6af85055ca23f1ec/crates/cairo-lang-starknet/cairo_level_tests/contracts.cairo#L15)):*
> ```Cairo
> mod upgradable_counter;
> mod mintable;
> mod erc20_new;
> ```

This is no longer an erc20.



_Suggestion:_
```Cairo
mod storage_acceesses;
```

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5950)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @orizi and @Tomer-StarkWare)

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5950)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/contracts.cairo` line 15 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5950#-O0wVdxsADH3s5qEVy3k:-O0wbWYM62IYaM6jR0WI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fc4d537e9bcebec5b73a453c6af85055ca23f1ec/crates/cairo-lang-starknet/cairo_level_tests/contracts.cairo#L15)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

This is no longer an erc20.
</blockquote></details>

Done.

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5950)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Tomer-StarkWare)

**Pull request merged**
