### PR TITLE
Remove instructions from dict squash inner loop.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2549)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2549)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2549#-NQu1o_67jsExPlpXWE9:-NQu1o_67jsExPlpXWEA:b-lefas8) (no related file):*
Change target branch.

___

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2549#-:-NQuTQFJ0Ku1YFfLEYui:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Review by liorgold2 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2549)* status: all files reviewed, 1 unresolved discussion

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2549)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

**Review by liorgold2 — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2549)* status: all files reviewed, 1 unresolved discussion

**Review by liorgold2 — APPROVED** [review]
> Dismissed @gilbens-starkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2549)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by liorgold2 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2549)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2549#-:-NQuaoCf8MZTYe3xJkhN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
