### PR TITLE
Added ABI test with components

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4090)

### CODE REVIEW

**Comment by yuvalsw** [comment]
change target

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4090)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/upgradable_counter` line 181 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4090#-Neh52XL-fx-3GL1aiVH:-Neh52XL-fx-3GL1aiVI:bb76mu4) ([raw file](https://github.com/starkware-libs/cairo/blob/e02ccab82750a0a6d62e7ea7287611970a6bbee6/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/upgradable_counter#L181)):*
> ```
>         CounterIncreased: CounterIncreased,
>         CounterDecreased: CounterDecreased,
>         UpgradableEvent: super::upgradable::Event
> ```

Why?

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4090)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

**Comment by yuvalsw** [comment]
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/upgradable_counter` line 181 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4090#-Neh52XL-fx-3GL1aiVH:-NehrpT4CNt_qCKyRq5A:bvth56w) ([raw file](https://github.com/starkware-libs/cairo/blob/e02ccab82750a0a6d62e7ea7287611970a6bbee6/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/upgradable_counter#L181)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Why?
</blockquote></details>

reverted

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4090#-:-NehsCX79atd2vQvu7xr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
