### PR TITLE
Made pedersen use the casm builder.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:acffd868

---

**Stack**:
- #1407
- #1406
- #1405
- #1404 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1404)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/sierra_to_casm/src/invocations/pedersen.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1404#-NJiojsa4b76INvbdjtv:-NJiojsa4b76INvbdjtw:bpds9km) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a1affa4fbb2ba781daff3c6b2287d76677c816/crates/sierra_to_casm/src/invocations/pedersen.rs#L56)):*
> ```XML
>         b: deref_or_immediate!(pedersen_offset),
>     });
>     let pedersen = casm_builder.add_var(original_pedersen.clone());
> ```

This looks like the only pedersen var you actually use. Why not use `original_pedersen` directly? and what is `_original_pedersen` for?



_Code quote:_
```XML
pedersen
```
___
*[`crates/sierra_to_casm/src/invocations/pedersen.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1404#-NJioPdv4QniAyKJ4L9f:-NJioPdv4QniAyKJ4L9g:b-cbt3sp) ([raw file](https://github.com/starkware-libs/cairo/blob/a4a1affa4fbb2ba781daff3c6b2287d76677c816/crates/sierra_to_casm/src/invocations/pedersen.rs#L76)):*
> ```XML
>         vec![],
>         [
>             // Success branch - return (gas builtin, system)
> ```

neither of these builtins seem to be involved, and there is no failure branch... copied comment?



_Code quote:_
```XML
// Success branch - return (gas builtin, system)
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1404)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/sierra_to_casm/src/invocations/pedersen.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1404#-NJiojsa4b76INvbdjtv:-NJj0f-yAmc60-Ld-Uqh:b-7c360n) ([raw file](https://github.com/starkware-libs/cairo/blob/8668118a91933248c0addc50e0a30240d9098f3b/crates/sierra_to_casm/src/invocations/pedersen.rs#L56)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

This looks like the only pedersen var you actually use. Why not use `original_pedersen` directly? and what is `_original_pedersen` for?
</blockquote></details>

ah, original_pedersen is a ResOperand and pedersen is a Var. Still, I don't see why you need both

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1404)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/sierra_to_casm/src/invocations/pedersen.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1404#-NJiojsa4b76INvbdjtv:-NJj8gXJ6YvTLK1XCtds:b-spi9jo) ([raw file](https://github.com/starkware-libs/cairo/blob/beea2d8076ba08873cf4367d44b18f05f0988a64/crates/sierra_to_casm/src/invocations/pedersen.rs#L56)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ah, original_pedersen is a ResOperand and pedersen is a Var. Still, I don't see why you need both
</blockquote></details>

one is advanced and the other is not - as the call to the builtin is on the original start point.
___
*[`crates/sierra_to_casm/src/invocations/pedersen.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1404#-NJioPdv4QniAyKJ4L9f:-NJj8foe3eQ5SWhskd8g:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/beea2d8076ba08873cf4367d44b18f05f0988a64/crates/sierra_to_casm/src/invocations/pedersen.rs#L76)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

neither of these builtins seem to be involved, and there is no failure branch... copied comment?
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1404)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/sierra_to_casm/src/invocations/pedersen.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1404#-NJioPdv4QniAyKJ4L9f:-NJj9Jbj2QUe92mw_ID8:ba0ycjm) ([raw file](https://github.com/starkware-libs/cairo/blob/beea2d8076ba08873cf4367d44b18f05f0988a64/crates/sierra_to_casm/src/invocations/pedersen.rs#L76)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Done.
</blockquote></details>

still here, did you push?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1404)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/sierra_to_casm/src/invocations/pedersen.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1404#-NJioPdv4QniAyKJ4L9f:-NJjGeOjDP-m5mAzSRfn:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/beea2d8076ba08873cf4367d44b18f05f0988a64/crates/sierra_to_casm/src/invocations/pedersen.rs#L76)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

still here, did you push?
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1404#-:-NJjI-ao1AhR7tFk5b_2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
