### PR TITLE
Added warning diagnostics severity.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #4462
- #4459 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4459)

### CODE REVIEW

**Review by mkaput — COMMENTED** [review]
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4459)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-diagnostics/src/diagnostics.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4459#-Njw7gqu9on9iTzNhNsW:-Njw7gqu9on9iTzNhNsX:b-9l9f3y) ([raw file](https://github.com/starkware-libs/cairo/blob/bd0f0b11e3ed8f3828bbb8ef7d2047dafcf465fa/crates/cairo-lang-diagnostics/src/diagnostics.rs#L17)):*
> ```XML
> 
> /// The severity of a diagnostic.
> #[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
> ```

Ord & PartialOrd may come handy here (Warning < Error). Getting the severity of a collection of diagnostics would then be just calling `max` over them.
___
*[`crates/cairo-lang-diagnostics/src/diagnostics.rs` line 208 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4459#-Njw8FVtDPtbhzxArtLn:-Njw8FVu0Zzzyz-OOg6a:b-jja6j) ([raw file](https://github.com/starkware-libs/cairo/blob/bd0f0b11e3ed8f3828bbb8ef7d2047dafcf465fa/crates/cairo-lang-diagnostics/src/diagnostics.rs#L208)):*
> ```XML
> 
>     /// Returns Ok(()) if there are no errors, or an error handle if there are.
>     pub fn is_error_free(&self) -> Maybe<()> {
> ```

nit, `is_` prefix suggests this returns `bool`, while actually this is a condition check/validator/assertion.



_Suggestion:_
```XML
check_error_free
```

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 4 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4459)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 686 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4459#-NjwJgQI46dZQmQvLBRK:-NjwJgQJBbamX_A97NY6:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0fa3bb8a0e60ea8dc77112e3c6f4fdf0c688df50/crates/cairo-lang-language-server/src/lib.rs#L686)):*
> ```XML
>             if db.file_syntax_diagnostics(file).check_error_free().is_err() {
>                 return None;
>             }
> ```





_Suggestion:_
```XML
            if db.file_syntax_diagnostics(file).check_error_free().ok()?;
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4459)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-diagnostics/src/diagnostics.rs` line 196 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4459#-NjwO4Zt4AMfDFeWoMyH:-NjwO4Zt4AMfDFeWoMyI:b6ncg0u) ([raw file](https://github.com/starkware-libs/cairo/blob/ba0226365c28cb793a6dff6923439bca75dd6a20/crates/cairo-lang-diagnostics/src/diagnostics.rs#L196)):*
> ```XML
>     location: DiagnosticLocation,
> ) -> String {
>     format!("error: {message}\n --> {:?}\n", location.debug(db))
> ```

Print error/warning according to the severity.



_Code quote:_
```XML
format!("error: {message}\n --> {:?}\n", location.debug(db))
```

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4459#-:-NjwYZ1JCPAqBFJr84SF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by mkaput — APPROVED** [review]
> Reviewed 2 of 4 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4459)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
