### PR TITLE
Instead of asserting on A and B values, directly calculating these.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1939)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1939)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs` line 172 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1939#-NMw3oV5C7FQQPMLNljL:-NMw3oV5C7FQQPMLNljM:b-58v) ([raw file](https://github.com/starkware-libs/cairo/blob/f6dc9d952f9a75fa906d37c42104ebc0d3e00e65/crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs#L172)):*
> ```XML
> ///
> /// As long as A <= B, every number in the range can be represented.
> /// So provided `K` must supply such A and B.
> ```

Please rephrase.



_Code quote:_
```XML
So provided `K` must supply such A and B.
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1939)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs` line 172 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1939#-NMw3oV5C7FQQPMLNljL:-NMwKRCO5u59HftoQc8U:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f6dc9d952f9a75fa906d37c42104ebc0d3e00e65/crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs#L172)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Please rephrase.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1939)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs` line 172 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1939#-NMwMQkC7BeuthyCJRv-:-NMwMQkC7BeuthyCJRv0:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f3b1bd73c6ccdaa79f405ea4092830a37f139486/crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs#L172)):*
> ```XML
> ///
> /// As long as A <= B, every number in the range can be represented.
> /// We assert A and B generated by the provided `K` parameter fit this criteria.
> ```





_Suggestion:_
```XML
We assert that the A and B generated by the provided `K` parameter fit these criteria.
```

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1939#-:-NMwMf8a0fEoT09cNvcE:bnfp4nl)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1939)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs` line 172 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1939#-NMwMQkC7BeuthyCJRv-:-NMwNfY_D4Z3_37illUR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f3b1bd73c6ccdaa79f405ea4092830a37f139486/crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs#L172)):*
> ```XML
> ///
> /// As long as A <= B, every number in the range can be represented.
> /// We assert A and B generated by the provided `K` parameter fit this criteria.
> ```

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1939)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1939)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
