### PR TITLE
Add drop and copy impls

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2500)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2500** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2500" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2500?utm_source=stack-comment).

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2500)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`corelib/src/result.cairo` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2500#-NQ_wFks5c0flCbIuQc7:-NQ_wFks5c0flCbIuQc8:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/bc56d44866fe460591bb7e1c613882f8e509fa3f/corelib/src/result.cairo#L61)):*
> ```Cairo
> }
> 
> // Impls for common generic types
> ```

.



_Suggestion:_
```Cairo
// Impls for generic types
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2500)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/result.cairo` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2500#-NQ_wFks5c0flCbIuQc7:-NQ_x7GKB6uOjGET1DNy:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bc56d44866fe460591bb7e1c613882f8e509fa3f/corelib/src/result.cairo#L61)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2500)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2500)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2500)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
