### PR TITLE
Added support for div-rem const folding.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #6454
- #6453
- #6436
- #6435
- #6434
- #6433 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6433)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6433)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/const_folding.rs` line 229 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6433#-O8VZUGr6pCeri98Zsjt:-O8VZUGw8WdfPsgzLwWA:b-egp82m) ([raw file](https://github.com/starkware-libs/cairo/blob/9bc1305b1ad153a4e394c05f7168a942ed5a7e88/crates/cairo-lang-lowering/src/optimizations/const_folding.rs#L229)):*
> ```XML
>         &mut self,
>         stmt: &mut StatementCall,
>     ) -> Option<(StatementConst, Option<StatementConst>)> {
> ```

Isn't a potentially empty vec of additional consts more expressive in this case?



_Suggestion:_
```XML
Vec<StatementConst>
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6433)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/const_folding.rs` line 229 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6433#-O8VZUGr6pCeri98Zsjt:-O8VeRAECNloyYZize83:b470efi) ([raw file](https://github.com/starkware-libs/cairo/blob/9bc1305b1ad153a4e394c05f7168a942ed5a7e88/crates/cairo-lang-lowering/src/optimizations/const_folding.rs#L229)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Isn't a potentially empty vec of additional consts more expressive in this case?
</blockquote></details>

maybe just adding the `additionals` vec as a parameter.
returning a vec entitled more.

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6433)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/const_folding.rs` line 229 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6433#-O8VZUGr6pCeri98Zsjt:-O8VjgAT97qI3blJ3LuH:b-uq7jgo) ([raw file](https://github.com/starkware-libs/cairo/blob/9bc1305b1ad153a4e394c05f7168a942ed5a7e88/crates/cairo-lang-lowering/src/optimizations/const_folding.rs#L229)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe just adding the `additionals` vec as a parameter.
returning a vec entitled more.
</blockquote></details>

I'm fine with any of these

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6433)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/const_folding.rs` line 229 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6433#-O8VZUGr6pCeri98Zsjt:-O8VjxP9DAndITt4NSPF:b-rr5edg) ([raw file](https://github.com/starkware-libs/cairo/blob/9bc1305b1ad153a4e394c05f7168a942ed5a7e88/crates/cairo-lang-lowering/src/optimizations/const_folding.rs#L229)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

I'm fine with any of these
</blockquote></details>

But yes, a vec parameter seems good, as the output simply extends a vec anyway

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6433)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/const_folding.rs` line 229 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6433#-O8VZUGr6pCeri98Zsjt:-O8VkErp0oysxMGz60tf:b-1zdchj) ([raw file](https://github.com/starkware-libs/cairo/blob/9bc1305b1ad153a4e394c05f7168a942ed5a7e88/crates/cairo-lang-lowering/src/optimizations/const_folding.rs#L229)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

But yes, a vec parameter seems good, as the output simply extends a vec anyway
</blockquote></details>

it is somewhat of a discrepancy with the other `block-end` handler.
(and there we directly add to the block statements - which is somewhat better than prepending) 
but will do anyway.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6433#-:-O8W-zL1-Z3paxYIlo5m:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
