### PR TITLE
Refactored and added allow features into all relevant `Resolver::new`

### PR DESCRIPTION
**Pull request by orizi**
commit-id:f0e8cf49

---

**Stack**:
- #5653 ⬅
- #5651
- #5642

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5653)

### CODE REVIEW

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5653)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @Tomer-StarkWare)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5653#-NytkCxN1sFnwGnk6LXC:-NytkCxN1sFnwGnk6LXD:bmdh9l1) (no related file):*
Nothing but free functions is tested at the moment, can you add some tests?

___

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5653)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @Tomer-StarkWare)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5653#-NytkCxN1sFnwGnk6LXC:-NytqUnI7079wINyDs5L:b-896fix) (no related file):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Nothing but free functions is tested at the moment, can you add some tests?
</blockquote></details>

Done.

___

**Review by TomerStarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5653#-:-Nyu28Aj4VrfROJkWDyC:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @Tomer-StarkWare)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5653)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/tests` line 565 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5653#-Nyu1S7hEX4a2FpgWlqL:-Nyu1S7hEX4a2FpgWlqM:b-qzpewr) ([raw file](https://github.com/starkware-libs/cairo/blob/69e70c6fc6a80488f7d5e4562f6a4e9cf43e81dd/crates/cairo-lang-semantic/src/diagnostic_test_data/tests#L565)):*
> ```
> enum AllowedEnumMember {
>     variant: DisallowedType,
> }
> ```

I think this should work too?



_Suggestion:_
```
enum AllowedEnumMember {
    variant: DisallowedType,
}

mod foo {
   #[unstable(feature: "unstable-inner-trait")]
  trait UnstableInnerTrait;
}

#[feature("unstable-inner-trait")]
use foo::UnstableInnerTrait;

impl AlloweInnerdUnstableImpl of UnstableInnerTrait;
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5653)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/tests` line 565 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5653#-Nyu1S7hEX4a2FpgWlqL:-Nyu5nFW1nG9tC1zA1Jb:bl9thj) ([raw file](https://github.com/starkware-libs/cairo/blob/69e70c6fc6a80488f7d5e4562f6a4e9cf43e81dd/crates/cairo-lang-semantic/src/diagnostic_test_data/tests#L565)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

I think this should work too?
</blockquote></details>

it maybe should - but it won't for now.
i'm totally fine with needing to allow this in module context for now.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5653#-:-Nyu6AyI34z34azu1yuu:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Tomer-StarkWare)

**Pull request merged**
