### PR TITLE
Updating readme to include rust configuration.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:fec3f91b

---

**Stack**:
- #1506
- #1505
- #1483 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by bbrandtom — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1483)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @abdelhamidbakhta and @orizi)

___
*[`README.md` line 74 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1483#-NKHdXhl0kzomu0xWkS1:-NKHdXhl0kzomu0xWkS2:b-8k29v9) ([raw file](https://github.com/starkware-libs/cairo/blob/70864255be4547b9a42904afaa48f7e0b675103a/README.md#L74)):*
> ```Markdown
> ```
> 
> ### Compile and running Cairo files
> ```

Is there a way to only compile?
Is there a way to pass inputs to the run?



_Suggestion:_
```Markdown
Compiling
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1483)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @abdelhamidbakhta and @bbrandtom)

___
*[`README.md` line 74 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1483#-NKHdXhl0kzomu0xWkS1:-NKHipx3D6dAtu_fUmQo:b-bdwy5m) ([raw file](https://github.com/starkware-libs/cairo/blob/a38290215dde3bafb758afb2fec2725f19ed4582/README.md#L74)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

Is there a way to only compile?
Is there a way to pass inputs to the run?
</blockquote></details>

no - this is only supporting pure mains for the time being.

but you can write whatever tests you'd want and run tests on them.

**Review by bbrandtom — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1483#-:-NKHlBLv9TK19ciBwLoa:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @abdelhamidbakhta)

___
*[`README.md` line 74 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1483#-NKHdXhl0kzomu0xWkS1:-NKHl3HF45PCD9YBYv98:b-9vuagv) ([raw file](https://github.com/starkware-libs/cairo/blob/a38290215dde3bafb758afb2fec2725f19ed4582/README.md#L74)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no - this is only supporting pure mains for the time being.

but you can write whatever tests you'd want and run tests on them.
</blockquote></details>

Also no for only compiling? Ok let's move this discussion to Slack and create a different PR if needed.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1483)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @abdelhamidbakhta)

___
*[`README.md` line 74 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1483#-NKHdXhl0kzomu0xWkS1:-NKHmF2R2t7KHECaRmOK:b-shirk5) ([raw file](https://github.com/starkware-libs/cairo/blob/a38290215dde3bafb758afb2fec2725f19ed4582/README.md#L74)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

Also no for only compiling? Ok let's move this discussion to Slack and create a different PR if needed.
</blockquote></details>

there's an ability to compile - so i'll add some more.

**Pull request merged**
