### PR TITLE
Remove EventEnumVariantTypeMismatch error.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4059)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4059)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4059#-Ne8XKl4Da8F4F6aEApW:-Ne8XKl4Da8F4F6aEApX:b2rtrq3) (no related file):*
@ArielElp 

___

**Review by yuvalsw — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4059)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4059#-Ne8XKl4Da8F4F6aEApW:-NeDRi8P200yYT9fCo1b:bjeg0fw) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

please respond :)
</blockquote></details>

LGTM code-wise. Waiting for Ariel to comment on the feature.

___

**Review by ArielElp — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4059)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by ArielElp — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4059#-:-NeafmPV8UqJ-E5_JcNZ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4059)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 1 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4059#-:-Near-Ph-egji4YLEz3v:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
