### PR TITLE
added impl for copy and drop traits for fixed_size_array

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5237)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 7 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5237)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @orizi and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/fixed_size_array` line 235 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5237#-Nsh3EqX3gTtdE_TF1rE:-Nsh3EqY9NxtIDuLHSZp:brhg7ee) ([raw file](https://github.com/starkware-libs/cairo/blob/b2a986f17eb8f09b8d2bcb1c42683c0349dfc258/crates/cairo-lang-semantic/src/expr/test_data/fixed_size_array#L235)):*
> ```
>  --> lib.cairo:2:4
>    [0;N]
>    ^***^
> ```

Add new line.



_Suggestion:_
```
   ^***^
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5237)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5237#-Nsh3KBw0IWobrgmVQJZ:-Nsh3KBw0IWobrgmVQJ_:b-l6u88n) (no related file):*
rebase

___

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5237)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/fixed_size_array` line 227 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5237#-Nsh3uJF7RB9pgIjtkwN:-Nsh3uJH93-wsfL7xtnK:b-oafb5i) ([raw file](https://github.com/starkware-libs/cairo/blob/e30c34964629b7430b7bdb49d570b0f0d100adfe/crates/cairo-lang-semantic/src/expr/test_data/fixed_size_array#L227)):*
> ```
> 
> //! > module_code
> fn bar<const N: usize>() -> [felt252;N]{
> ```

Fmt all code.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5237)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`corelib/src/traits.cairo` line 315 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5237#-Nsh4KUC0BmB-yOYRntC:-Nsh4KUC0BmB-yOYRntD:b-olxh23) ([raw file](https://github.com/starkware-libs/cairo/blob/e30c34964629b7430b7bdb49d570b0f0d100adfe/corelib/src/traits.cairo#L315)):*
> ```Cairo
> 
> impl FixedArrayDrop<T, +Drop<T>, const N: u32> of Drop<[T; N]>;
> impl FixedArrayCopy<T, +Copy<T>, const N: u32> of Copy<[T; N]>;
> ```

FixedSizedArray
___
*[`corelib/src/test/array_test.cairo` line 155 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5237#-Nsh433i40fE2iH6xTtv:-Nsh433i40fE2iH6xTtw:b-91vjay) ([raw file](https://github.com/starkware-libs/cairo/blob/e30c34964629b7430b7bdb49d570b0f0d100adfe/corelib/src/test/array_test.cairo#L155)):*
> ```Cairo
>     assert_eq!(z, 12);
> }
> fn consume<const N: usize>(_arr: [felt252; N]) {}
> ```

Add empty lines.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 8 files at r1, 1 of 13 files at r3, 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5237#-:-NshPzdk6ITB-cp7vvBp:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5237)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5237)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5237)* status: 16 of 17 files reviewed, all discussions resolved (waiting on @orizi)

___
*[`corelib/src/traits.cairo` line 315 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5237#-Nsh4KUC0BmB-yOYRntC:-NshFB2x3LRzCEZiKURW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e30c34964629b7430b7bdb49d570b0f0d100adfe/corelib/src/traits.cairo#L315)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

FixedSizedArray
</blockquote></details>

Done.
___
*[`corelib/src/test/array_test.cairo` line 155 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5237#-Nsh433i40fE2iH6xTtv:-NshFIh0AtHhrCdWQmUg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e30c34964629b7430b7bdb49d570b0f0d100adfe/corelib/src/test/array_test.cairo#L155)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Add empty lines.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/fixed_size_array` line 227 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5237#-Nsh3uJF7RB9pgIjtkwN:-NshFWo70nxSx829fKUJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e30c34964629b7430b7bdb49d570b0f0d100adfe/crates/cairo-lang-semantic/src/expr/test_data/fixed_size_array#L227)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Fmt all code.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5237)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5237)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
