### PR TITLE
Added include attribute for starknet plugin.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3613)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3613)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/test_data/test_contract.cairo` line 26 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3613#-Na5oRV0AvNhzg43Rr1-:-Na5oRV0AvNhzg43Rr10:b-4rh1mx) ([raw file](https://github.com/starkware-libs/cairo/blob/8a4559511e71d73ddb51c22104059cf5fe39b1da/crates/cairo-lang-starknet/test_data/test_contract.cairo#L26)):*
> ```Cairo
>     #[include(v0)]
>     #[generate_trait]
>     impl Impl of Trait {
> ```

Can we also test constructor?

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3613#-:-Na5oVssA1xB5aQ9uwvW:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3613)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-starknet/test_data/test_contract.cairo` line 26 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3613#-Na5oRV0AvNhzg43Rr1-:-Na6LmDMEiteLbYOfB_G:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8a4559511e71d73ddb51c22104059cf5fe39b1da/crates/cairo-lang-starknet/test_data/test_contract.cairo#L26)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Can we also test constructor?
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3613)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
