### PR TITLE
Add notes to locations.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3446)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3446)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @liorgold2, @orizi, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/test.rs` line 214 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3446#-NYM_e3O7xLyZeslg2mz:-NYM_e3O7xLyZeslg2n-:b-31gsmj) ([raw file](https://github.com/starkware-libs/cairo/blob/369f6e034ff4c354b3fb8d11982c1711bcda5720/crates/cairo-lang-lowering/src/test.rs#L214)):*
> ```XML
>  --> lib.cairo:1:1
> fn test_func() { let mut a = 5; {
> ^*******************************^
> ```

in the future we can refactor i



_Suggestion:_
```XML
error: Cannot inline a function that might call itself.
 --> lib.cairo:1:1
fn test_func() { let mut a = 5; {
^*******************************^

note: This error occurred while compiling auto-generated withdraw_gas, while compiling auto-generated destructor.
```

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3446)* status: all files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware, @liorgold2, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/diagnostic.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3446#-NYN1RkN6iJBCdv6sHSk:-NYN1RkN6iJBCdv6sHSl:b25fxgh) ([raw file](https://github.com/starkware-libs/cairo/blob/369f6e034ff4c354b3fb8d11982c1711bcda5720/crates/cairo-lang-lowering/src/diagnostic.rs#L52)):*
> ```XML
> 
>     fn format(&self, db: &Self::DbType) -> String {
>         let msg: smol_str::SmolStr = match &self.kind {
> ```

1. use?
2. Why does it have to be smolstr and not String? You have double into()



_Code quote:_
```XML
smol_str::SmolStr
```
___
*[`crates/cairo-lang-lowering/src/diagnostic.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3446#-NYN1kFw-fGFDgDpqOm2:-NYN1kFw-fGFDgDpqOm3:b-i8uqcg) ([raw file](https://github.com/starkware-libs/cairo/blob/369f6e034ff4c354b3fb8d11982c1711bcda5720/crates/cairo-lang-lowering/src/diagnostic.rs#L98)):*
> ```XML
>         let arr = [msg];
> 
>         itertools::chain!(self.location.notes.iter(), arr.iter()).join(",\n")
> ```

Is this the best way to append msg in the end of the notes vec?
___
*[`crates/cairo-lang-lowering/src/ids.rs` line 343 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3446#-NYN3vnpC9sEUfJkecBq:-NYN3vnpC9sEUfJkecBr:b-2cgl3a) ([raw file](https://github.com/starkware-libs/cairo/blob/369f6e034ff4c354b3fb8d11982c1711bcda5720/crates/cairo-lang-lowering/src/ids.rs#L343)):*
> ```XML
>     }
> 
>     pub fn with_note(&self, db: &dyn LoweringGroup, note: smol_str::SmolStr) -> LocationId {
> ```

please doc both
___
*[`crates/cairo-lang-lowering/src/ids.rs` line 350 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3446#-NYN41WKDB3Nhv3TF87s:-NYN41WLATX0VrEfPXO0:bb7q04d) ([raw file](https://github.com/starkware-libs/cairo/blob/369f6e034ff4c354b3fb8d11982c1711bcda5720/crates/cairo-lang-lowering/src/ids.rs#L350)):*
> ```XML
>         &self,
>         db: &dyn LoweringGroup,
>         logic_name: smol_str::SmolStr,
> ```

use?



_Code quote:_
```XML
smol_str::SmolStr
```
___
*[`crates/cairo-lang-lowering/src/objects.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3446#-NYN4DqM7Yp9wz8TBc2t:-NYN4DqN-PMZyeRvDl8Q:b-bfp28v) ([raw file](https://github.com/starkware-libs/cairo/blob/369f6e034ff4c354b3fb8d11982c1711bcda5720/crates/cairo-lang-lowering/src/objects.rs#L30)):*
> ```XML
>     /// The stable location of the object.
>     pub stable_location: StableLocation,
>     pub notes: Vec<smol_str::SmolStr>,
> ```

doc (both what note is, and what order they are in the vec), use SmolStr
___
*[`crates/cairo-lang-lowering/src/objects.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3446#-NYN4cQpB3USd_ux8DLT:-NYN4cQpB3USd_ux8DLU:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/369f6e034ff4c354b3fb8d11982c1711bcda5720/crates/cairo-lang-lowering/src/objects.rs#L37)):*
> ```XML
>     }
> 
>     pub fn with_note(mut self, note: smol_str::SmolStr) -> Self {
> ```

doc
___
*[`crates/cairo-lang-lowering/src/test.rs` line 214 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3446#-NYM_e3O7xLyZeslg2mz:-NYN5MhM2dQeoEeueXG4:b-rvp8ve) ([raw file](https://github.com/starkware-libs/cairo/blob/369f6e034ff4c354b3fb8d11982c1711bcda5720/crates/cairo-lang-lowering/src/test.rs#L214)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

in the future we can refactor i
</blockquote></details>

Looks good, add a TODO?
It's good to first see the error and then the notes
___
*[`crates/cairo-lang-lowering/src/add_withdraw_gas/mod.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3446#-NYN5WNO3rt5-QWGWEpE:-NYN5WNO3rt5-QWGWEpF:b-hfpv1m) ([raw file](https://github.com/starkware-libs/cairo/blob/369f6e034ff4c354b3fb8d11982c1711bcda5720/crates/cairo-lang-lowering/src/add_withdraw_gas/mod.rs#L39)):*
> ```XML
>     lowered: &mut FlatLowered,
> ) -> Maybe<()> {
>     // TODO(ilya): Add metadata
> ```

remove?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/diagnostic.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3446#-NYN1kFw-fGFDgDpqOm2:-NYNNAam6KlNGQvekVzF:bs2dpjr) ([raw file](https://github.com/starkware-libs/cairo/blob/369f6e034ff4c354b3fb8d11982c1711bcda5720/crates/cairo-lang-lowering/src/diagnostic.rs#L98)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Is this the best way to append msg in the end of the notes vec?
</blockquote></details>

best in what metric?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3446)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @liorgold2, @orizi, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/ids.rs` line 343 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3446#-NYN3vnpC9sEUfJkecBq:-NYNdJxE2A2lnbZT0dx3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/369f6e034ff4c354b3fb8d11982c1711bcda5720/crates/cairo-lang-lowering/src/ids.rs#L343)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

please doc both
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/objects.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3446#-NYN4cQpB3USd_ux8DLT:-NYNigjDBkxJBNKi6Jlw:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/369f6e034ff4c354b3fb8d11982c1711bcda5720/crates/cairo-lang-lowering/src/objects.rs#L37)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

doc
</blockquote></details>

done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3446)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @liorgold2, @orizi, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/diagnostic.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3446#-NYN1RkN6iJBCdv6sHSk:-NYONwFV2S0ai7WKcL8e:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/369f6e034ff4c354b3fb8d11982c1711bcda5720/crates/cairo-lang-lowering/src/diagnostic.rs#L52)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

1. use?
2. Why does it have to be smolstr and not String? You have double into()
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/test.rs` line 214 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3446#-NYM_e3O7xLyZeslg2mz:-NYONz47EtIR4pGQgqpy:b-knv1ek) ([raw file](https://github.com/starkware-libs/cairo/blob/369f6e034ff4c354b3fb8d11982c1711bcda5720/crates/cairo-lang-lowering/src/test.rs#L214)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Looks good, add a TODO?
It's good to first see the error and then the notes
</blockquote></details>

added a todo.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3446#-:-NYRxmU763C3YcCwj3aJ:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware, @liorgold2, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/objects.rs` line 32 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3446#-NYRwQAJ64hk1dyUZqGb:-NYRwQAK4j9LKREIpBmU:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/162eee40140a4882329885912e42b3b45526f5f3/crates/cairo-lang-lowering/src/objects.rs#L32)):*
> ```XML
>     /// Additional notes about the origin of the object, for example if the object was
>     /// auto-generated by the compiler.
>     /// When there is nesting, inner notes are appended to to end of the vector.
> ```





_Suggestion:_
```XML
pended to the end of the ve
```
___
*[`crates/cairo-lang-lowering/src/objects.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3446#-NYRwW4S4t0HGeuEMFDx:-NYRwW4S4t0HGeuEMFDy:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/162eee40140a4882329885912e42b3b45526f5f3/crates/cairo-lang-lowering/src/objects.rs#L40)):*
> ```XML
>     }
> 
>     // Returns a new Location that includes a note.
> ```





_Suggestion:_
```XML
   /// Returns a new Location t
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/objects.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3446#-NYRwW4S4t0HGeuEMFDx:-NYS498RCNQqN7LTu40q:b9dfuu3) ([raw file](https://github.com/starkware-libs/cairo/blob/162eee40140a4882329885912e42b3b45526f5f3/crates/cairo-lang-lowering/src/objects.rs#L40)):*
> ```XML
>     }
> 
>     // Returns a new Location that includes a note.
> ```

Rephrased.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3446)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @liorgold2, @orizi, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/objects.rs` line 32 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3446#-NYRwQAJ64hk1dyUZqGb:-NYS1tQHAG7VVZjHFEBD:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/162eee40140a4882329885912e42b3b45526f5f3/crates/cairo-lang-lowering/src/objects.rs#L32)):*
> ```XML
>     /// Additional notes about the origin of the object, for example if the object was
>     /// auto-generated by the compiler.
>     /// When there is nesting, inner notes are appended to to end of the vector.
> ```

done

**Review by yuvalsw — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3446)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware, @liorgold2, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/objects.rs` line 40 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3446#-NYSC5Rc6Cka0qdn90Q8:-NYSC5Rc6Cka0qdn90Q9:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0a1eedcf4405d563de53ee0531d338a1413ec59c/crates/cairo-lang-lowering/src/objects.rs#L40)):*
> ```XML
>     }
> 
>     /// Returns a new Location that with the given note as the inner most note.
> ```





_Suggestion:_
```XML
/// Creates a new Location with the given note as the inner most note
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3446)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @liorgold2, @orizi, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/objects.rs` line 40 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3446#-NYSC5Rc6Cka0qdn90Q8:-NYSXKg62XHHpgOK4M3X:b-7rotgk) ([raw file](https://github.com/starkware-libs/cairo/blob/0a1eedcf4405d563de53ee0531d338a1413ec59c/crates/cairo-lang-lowering/src/objects.rs#L40)):*
> ```XML
>     }
> 
>     /// Returns a new Location that with the given note as the inner most note.
> ```

dione

**Pull request merged**
