### PR TITLE
Refactored the builder to be simpler to build and extract results.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:2897e698

---

**Stack**:
- #1465
- #1462
- #1460 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1460)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1460)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/casm/src/builder.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1460#-NK7lj5t65_9aNPpukYE:-NK7lj5t65_9aNPpukYF:b9x64ro) ([raw file](https://github.com/starkware-libs/cairo/blob/7854a18102c8bc1cf3935f39b448b4f1fb5b4b20/crates/casm/src/builder.rs#L125)):*
> ```XML
>         let label_offsets = self.compute_label_offsets();
>         if self.reachable {
>             self.label_state.insert("Fallthrough".to_owned(), self.main_state);
> ```

Not entirely related to this PR, but maybe we want to assert that there are no user defined label named "Fallthrough"?
___
*[`crates/casm/src/builder_test.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1460#-NK7m82h0mXI2eB988Zm:-NK7m82h0mXI2eB988Zn:brq5abp) ([raw file](https://github.com/starkware-libs/cairo/blob/7854a18102c8bc1cf3935f39b448b4f1fb5b4b20/crates/casm/src/builder_test.rs#L21)):*
> ```XML
>     };
>     let CasmBuildResult { instructions, branches: [(state, awaiting_relocations)] } =
>         builder.build(["Fallthrough"]);
> ```

Consider renaming build to `build_branches(branch_names)` and then`build()` should simply call `build_branches(["Fallthrough"])`.
Or maybe simply add `build_simple` or `build_default` for the fallthrough only case.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1460#-:-NK7pJLP-m992C-UaU0R:bnfp4nl)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1460)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/casm/src/builder.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1460#-NK7lj5t65_9aNPpukYE:-NK7ycr-21E2OonxNc1r:bq3role) ([raw file](https://github.com/starkware-libs/cairo/blob/7854a18102c8bc1cf3935f39b448b4f1fb5b4b20/crates/casm/src/builder.rs#L125)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Not entirely related to this PR, but maybe we want to assert that there are no user defined label named "Fallthrough"?
</blockquote></details>

this will be automatically validated - as the insertion will fail.
___
*[`crates/casm/src/builder_test.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1460#-NK7m82h0mXI2eB988Zm:-NK7ypLd3-FEQTyATrTz:bvu6s03) ([raw file](https://github.com/starkware-libs/cairo/blob/7854a18102c8bc1cf3935f39b448b4f1fb5b4b20/crates/casm/src/builder_test.rs#L21)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Consider renaming build to `build_branches(branch_names)` and then`build()` should simply call `build_branches(["Fallthrough"])`.
Or maybe simply add `build_simple` or `build_default` for the fallthrough only case.
</blockquote></details>

since in the next pr we merge this into the framework - i think i rather not.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1460)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
