### PR TITLE
Removed `unreachable` block end

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2337)

### CODE REVIEW

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2337)* status: 0 of 17 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2337#-NPSynFD6xclYZ0SJ7pi:-NPSynFD6xclYZ0SJ7pj:b-3yf84a) (no related file):*
change target branch

___

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2337#-:-NPT-rS672q7MCD2RdgE:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 10 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2337#-:-NPT0weJ2-HfkkSYAt3q:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2337)* status: all files reviewed, 1 unresolved discussion

**Review by orizi — APPROVED** [review]
> Reviewed 18 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2337)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
