### PR TITLE
Refactor sierra gen.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
generate_block_code -> generate_block_body_code
generate_block_code_and_push_values -> generate_block_code Use the new generate_block_code in get_function_code.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2000)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2000)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/block_generator.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2000#-NN7I_Y--VZRJcORmWSC:-NN7I_Y01P8N_v95hI3w:bxcimzh) ([raw file](https://github.com/starkware-libs/cairo/blob/f9687c7e9ac9b88d3b54b81225b57167bee03a46/crates/cairo-lang-sierra-generator/src/block_generator.rs#L84)):*
> ```XML
> /// the given `binds` variables.
> ///
> /// Returns a list of Sierra statements and a boolean indicating whether the block may continue to
> ```

FlatBlockEnd::Goto may "continue to the next instruction" but it does not fallthrough to the next instruction.



_Code quote:_
```XML
the block may continue to
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2000#-:-NN7_Wby1jiJSpUfex0h:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @liorgold2)

___
*[`crates/cairo-lang-sierra-generator/src/block_generator.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2000#-NN7I_Y--VZRJcORmWSC:-NN7Zz6fAqi0jZTAW18t:b-tp84pe) ([raw file](https://github.com/starkware-libs/cairo/blob/f9687c7e9ac9b88d3b54b81225b57167bee03a46/crates/cairo-lang-sierra-generator/src/block_generator.rs#L84)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

FlatBlockEnd::Goto may "continue to the next instruction" but it does not fallthrough to the next instruction.
</blockquote></details>

so is the change in doc correct?
___
*[`crates/cairo-lang-sierra-generator/src/function_generator.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2000#-NN7_N3W9dGSrLsvCiFl:-NN7_N3W9dGSrLsvCiFm:bof6g3t) ([raw file](https://github.com/starkware-libs/cairo/blob/f9687c7e9ac9b88d3b54b81225b57167bee03a46/crates/cairo-lang-sierra-generator/src/function_generator.rs#L95)):*
> ```XML
>     match &block.end {
>         lowering::FlatBlockEnd::Callsite(_) => panic!("Root block may not end with callsite."),
>         lowering::FlatBlockEnd::Return(returned_variables) => {
> ```

this was already generated for all root blocks since they must return internally?



_Code quote:_
```XML


    // Generate the return statement if necessary.
    let return_statement_location: StatementLocation = (block_id, block.statements.len());
    match &block.end {
        lowering::FlatBlockEnd::Callsite(_) => panic!("Root block may not end with callsite."),
        lowering::FlatBlockEnd::Return(returned_variables) => {
            statements.extend(generate_return_code(
                &mut context,
                returned_variables,
                &return_statement_location,
            )?);
        }
        lowering::FlatBlockEnd::Unreachable => {}
    };
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/block_generator.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2000#-NN7I_Y--VZRJcORmWSC:-NN7aZTBEtrcIZXmhqiU:bj636ae) ([raw file](https://github.com/starkware-libs/cairo/blob/f9687c7e9ac9b88d3b54b81225b57167bee03a46/crates/cairo-lang-sierra-generator/src/block_generator.rs#L84)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

so is the change in doc correct?
</blockquote></details>

Yes.
The original comment is also correct in this PR, but once I add FlatBlockEnd::Goto the old comment is going to be wrong while the new comment is correct.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/function_generator.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2000#-NN7_N3W9dGSrLsvCiFl:-NN7avMC1HGlBw3_Z8IP:b-4mi774) ([raw file](https://github.com/starkware-libs/cairo/blob/f9687c7e9ac9b88d3b54b81225b57167bee03a46/crates/cairo-lang-sierra-generator/src/function_generator.rs#L95)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this was already generated for all root blocks since they must return internally?
</blockquote></details>

There is only 1 root block per function.

The FlatBlockEnd::Callsite(_) case is caught above.

The FlatBlockEnd::Return and FlatBlockEnd::Unreachable cases are handled the same for internal blocks.

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2000)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2000)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
