### PR TITLE
panic location.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3527)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3527)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 387 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3527#-NYw-VOz4d7z4C8ZYNKu:-NYw-VOz4d7z4C8ZYNKv:b-74vsw7) ([raw file](https://github.com/starkware-libs/cairo/blob/df532a9286aba6eca1c2110350657e5287a8091d/crates/cairo-lang-lowering/src/lower/context.rs#L387)):*
> ```XML
>     /// Computation failure. A corresponding diagnostic should be emitted.
>     Failed(DiagnosticAdded),
>     Panic(VariableId, LocationId),
> ```

Should this return VarUsage?

as this var is going to be used.



_Suggestion:_
```XML
Panic(VarUsage),
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3527)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 387 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3527#-NYw-VOz4d7z4C8ZYNKu:-NYxVwNc2XlwITxCBDIM:b-aahp44) ([raw file](https://github.com/starkware-libs/cairo/blob/df532a9286aba6eca1c2110350657e5287a8091d/crates/cairo-lang-lowering/src/lower/context.rs#L387)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Should this return VarUsage?

as this var is going to be used.
</blockquote></details>

why was location returned only for `return` to begin with?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3527)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 387 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3527#-NYw-VOz4d7z4C8ZYNKu:-NYxcVk24_tIhKpaXRts:b-qeu7g7) ([raw file](https://github.com/starkware-libs/cairo/blob/df532a9286aba6eca1c2110350657e5287a8091d/crates/cairo-lang-lowering/src/lower/context.rs#L387)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't know.

But is it relevant to my question?
</blockquote></details>

yes - because if this should return VarUsage - so should Return.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 387 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3527#-NYw-VOz4d7z4C8ZYNKu:-NZ-t8RD5LBYlx6W-_aO:b-xmuadq) ([raw file](https://github.com/starkware-libs/cairo/blob/df532a9286aba6eca1c2110350657e5287a8091d/crates/cairo-lang-lowering/src/lower/context.rs#L387)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

yes - because if this should return VarUsage - so should Return.
</blockquote></details>

Ok, I'm keeping it as two fields, like in the return case.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3527#-:-NZ-tRyz7MF34qIdPvmV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
