### PR TITLE
Add declaration and implementation of from_nullable() libfunc.

### PR DESCRIPTION
**Pull request by liorgold2**
commit-id:9e58e5d0

---

**Stack**:
- #1459
- #1454 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1454#-:-NK3w9Nj2EjqkdWZTAZ8:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/sierra/src/extensions/modules/nullable.rs` line 110 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1454#-NK3upjV22-AZB9e3_sN:-NK3upjW5rKsuI03CB8y:bht6rdn) ([raw file](https://github.com/starkware-libs/cairo/blob/ca8b49f41a1615af36c1c54167ec69727d623ee1/crates/sierra/src/extensions/modules/nullable.rs#L110)):*
> ```XML
> pub type IntoNullableLibFunc = WrapSignatureAndTypeGenericLibFunc<IntoNullableLibFuncWrapped>;
> 
> /// LibFunc for converting `Nullable<T>` to `Option<Box<T>>`.
> ```

Fix doc - as this is not exact

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1454)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/sierra/src/extensions/modules/nullable.rs` line 110 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1454#-NK3upjV22-AZB9e3_sN:-NK7nn6ADBt4xWKJgHST:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ca8b49f41a1615af36c1c54167ec69727d623ee1/crates/sierra/src/extensions/modules/nullable.rs#L110)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Fix doc - as this is not exact
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1454)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1454)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1454)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1454)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 2 of 3 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1454)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
