### PR TITLE
added default values for match on numeric optimization dependant on th…

### PR DESCRIPTION
**Pull request by TomerStarkware**
…e type of the matched expression

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5009)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5009)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/lower_match.rs` line 1230 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5009#-NpyjDeK3xbnQQ5rUb-S:-NpyjDeK3xbnQQ5rUb-T:bobczu6) ([raw file](https://github.com/starkware-libs/cairo/blob/df6f18aea15e28d056dfe765653ce7cc72db130e/crates/cairo-lang-lowering/src/lower/lower_match.rs#L1230)):*
> ```XML
>             _ => panic!("Wrong type flag `{flag:?}`."),
>         })
>         .unwrap_or(default)
> ```

add in the doc that currently that means < 2**128 possible values.



_Suggestion:_
```XML
    is_small_type: bool,
) -> usize {
    // For felt252 the number of steps with if-else is 2 * min(n, number_of_arms) + 2 and 11~13 for
    // jump table for bounded_int the number of steps with if-else is 2 * min(n, number_of_arms) + 6
    // and 9~12 for jump table.
    let default_threshold = if is_bounded_int { 5 } else { 8 };
    ctx.db
        .get_flag(FlagId::new(ctx.db.upcast(), "numeric_match_optimization_min_arms_threshold"))
        .map(|flag| match *flag {
            Flag::NumericMatchOptimizationMinArmsThreshold(threshold) => threshold,
            _ => panic!("Wrong type flag `{flag:?}`."),
        })
        .unwrap_or(default_threshold)
```
___
*[`crates/cairo-lang-lowering/src/test_data/match` line 1513 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5009#-NpykKYF3F5lHEDpKBne:-NpykKYF3F5lHEDpKBnf:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/df6f18aea15e28d056dfe765653ce7cc72db130e/crates/cairo-lang-lowering/src/test_data/match#L1513)):*
> ```
>         3 => 4,
>         4=> 5,
>         _ => 6
> ```





_Suggestion:_
```
        3 => 4,
        4 => 5,
        _ => 6
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5009)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/lower_match.rs` line 1230 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5009#-NpyjDeK3xbnQQ5rUb-S:-NpywMNi6o29DSquK4Rk:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/df6f18aea15e28d056dfe765653ce7cc72db130e/crates/cairo-lang-lowering/src/lower/lower_match.rs#L1230)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add in the doc that currently that means < 2**128 possible values.
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5009)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5009)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/lower_match.rs` line 1215 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5009#-Npyy-IxAh0zg49Xvu1R:-Npz2Aqs5jDXMRdbHa1y:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5859b9ab5af582e2af438587a91a23b94a257fe9/crates/cairo-lang-lowering/src/lower/lower_match.rs#L1215)):*
> ```XML
> /// Returns the threshold for the number of arms for optimising numeric match expressions, by using
> /// a jump table instead of an if-else construct.
> /// is_small_type means the matched type has < 2**128 possible values.
> ```

Done.

**Pull request merged**
