### PR TITLE
Refactored const libfuncs by extracting `build_single_cell_const`.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #2455
- #2505
- #2520
- #2501 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2501)

### CODE REVIEW

**Review by ilyalesokhin-starkware — APPROVED** [review]
not sure about the motivation, but lgtm.

> Reviewed 30 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2501#-:-NQdTIUM8fKB_zITjqM2:b-fpj03u)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2501#-:-NQdjvyVBAo7T8FYxJfR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 25 of 28 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2501)* status: 27 of 30 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 28 of 28 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2501)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`tests/bug_samples/inconsistent_gas.cairo` line 9 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2501#-NQeHZcrC1NPRzVXk7qD:-NQeHZcrC1NPRzVXk7qE:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/f52a265546b20fd93f5e7e31c5444efbe57ce3fd/tests/bug_samples/inconsistent_gas.cairo#L9)):*
> ```Cairo
>     use starknet::syscalls::emit_event_syscall;
>     use starknet::StorageAddress;
>     use starknet::storage_access::address_domain_onchain;
> ```

?



_Code quote:_
```Cairo
use starknet::storage_access::address_domain_onchain;
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs` line 40 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2501#-NQeHl8dAL6YMb_1XRih:-NQeHl8dAL6YMb_1XRii:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f52a265546b20fd93f5e7e31c5444efbe57ce3fd/crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs#L40)):*
> ```XML
> pub fn build_single_cell_const(
>     builder: CompiledInvocationBuilder<'_>,
>     value: BigInt,
> ```





_Suggestion:_
```XML
value: &BigInt,
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2501)* status: 26 of 30 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs` line 40 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2501#-NQeHl8dAL6YMb_1XRih:-NQeIDPbCSjXjbsGxd5r:bfk66gn) ([raw file](https://github.com/starkware-libs/cairo/blob/f52a265546b20fd93f5e7e31c5444efbe57ce3fd/crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs#L40)):*
> ```XML
> pub fn build_single_cell_const(
>     builder: CompiledInvocationBuilder<'_>,
>     value: BigInt,
> ```

why? it is cloned anyway.

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2501)* status: 28 of 30 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`tests/bug_samples/inconsistent_gas.cairo` line 9 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2501#-NQeHZcrC1NPRzVXk7qD:-NQeJ0PC6uCWwfdlcRgu:b-a7584a) ([raw file](https://github.com/starkware-libs/cairo/blob/f52a265546b20fd93f5e7e31c5444efbe57ce3fd/tests/bug_samples/inconsistent_gas.cairo#L9)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
Reverted

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs` line 40 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2501#-NQeHl8dAL6YMb_1XRih:-NQeKgWw4Mqlzwy7SluM:b-qtqpz9) ([raw file](https://github.com/starkware-libs/cairo/blob/f52a265546b20fd93f5e7e31c5444efbe57ce3fd/crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs#L40)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why? it is cloned anyway.
</blockquote></details>

You clone it in the two call sites.

But I guess your solution is more flexable.

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 1 of 28 files at r4, 3 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2501)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
