### PR TITLE
Added another prelude config.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #4311
- #4306
- #4305 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4305)

### CODE REVIEW

**Review by mkaput — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4305)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4305#-NhlBATT2Mujwr-oMlGe:-NhlBATUARaTFhTdGg8x:b-dm2o1f) ([raw file](https://github.com/starkware-libs/cairo/blob/8839b76b75e61db1ad30896cc9a6b7d865ab14b5/crates/cairo-lang-filesystem/src/db.rs#L44)):*
> ```XML
>     #[default]
>     V0,
>     V2023_10,
> ```

This way it would look like an ISO date :)



_Suggestion:_
```XML
    #[serde(rename = "2023-10")]
    V2023_10,
```

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4305)* status: all files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/prelude/v2023_10.cairo` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4305#-NhvRq7Z7eIb2MeJkxBj:-NhvRq7_5MndktryEN_T:b493vcc) ([raw file](https://github.com/starkware-libs/cairo/blob/529a7e6461df84b505833b157512135dc180913e/corelib/src/prelude/v2023_10.cairo#L1)):*
> ```Cairo
> use core::{RangeCheck, SegmentArena, assert, bool, drop, dup, felt252, panic_with_felt252, usize};
> ```

I am not sure we want that, we want people to stop using it directly.



_Code quote:_
```Cairo
panic_with_felt252
```
___
*[`corelib/src/prelude/v2023_10.cairo` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4305#-NhvRy4OC0oQF61HdI8Q:-NhvRy4OC0oQF61HdI8R:brvwhib) ([raw file](https://github.com/starkware-libs/cairo/blob/529a7e6461df84b505833b157512135dc180913e/corelib/src/prelude/v2023_10.cairo#L1)):*
> ```Cairo
> use core::{RangeCheck, SegmentArena, assert, bool, drop, dup, felt252, panic_with_felt252, usize};
> ```

can we move to a module of its own?

Same for bool



_Code quote:_
```Cairo
felt252
```
___
*[`corelib/src/prelude/v2023_10.cairo` line 11 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4305#-NhvSD1x0eNjGg-tzubQ:-NhvSD1x0eNjGg-tzubR:bjtzvg2) ([raw file](https://github.com/starkware-libs/cairo/blob/529a7e6461df84b505833b157512135dc180913e/corelib/src/prelude/v2023_10.cairo#L11)):*
> ```Cairo
> use core::gas::{BuiltinCosts, GasBuiltin};
> use core::integer::{Bitwise, i128, i16, i32, i64, i8, u128, u16, u256, u32, u64, u8};
> use core::internal;
> ```

I don't think we want this one.
___
*[`corelib/src/prelude/v2023_10.cairo` line 22 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4305#-NhvSpCz5KiQrD3ZOYVa:-NhvSpCz5KiQrD3ZOYVb:b-c4fwo0) ([raw file](https://github.com/starkware-libs/cairo/blob/529a7e6461df84b505833b157512135dc180913e/corelib/src/prelude/v2023_10.cairo#L22)):*
> ```Cairo
> use core::serde::Serde;
> use core::{starknet, starknet::System};
> use core::string::StringLiteral;
> ```

do we need that but not NumericLiteral?
___
*[`corelib/src/prelude/v2023_10.cairo` line 23 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4305#-NhvSz6V40TOfw61AtK5:-NhvSz6V40TOfw61AtK6:bkm5see) ([raw file](https://github.com/starkware-libs/cairo/blob/529a7e6461df84b505833b157512135dc180913e/corelib/src/prelude/v2023_10.cairo#L23)):*
> ```Cairo
> use core::{starknet, starknet::System};
> use core::string::StringLiteral;
> use core::testing;
> ```

is it needed?

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4305)* status: all files reviewed, 6 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/prelude/v2023_10.cairo` line 0 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4305#-Nhv_w3q0QdefA7mM7EG:-Nhv_w3rBoalvjS1A5fk:b-1rnst7) ([raw file](https://github.com/starkware-libs/cairo/blob/529a7e6461df84b505833b157512135dc180913e/corelib/src/prelude/v2023_10.cairo#L0)):*
how about never and debug::PrintTrait? Don't we want them?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4305)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @mkaput and @yuvalsw)

___
*[`corelib/src/prelude/v2023_10.cairo` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4305#-NhvRy4OC0oQF61HdI8Q:-Nhvm5I12Ddxz6WmsPkA:b-l9xbc5) ([raw file](https://github.com/starkware-libs/cairo/blob/3e4abcf126229cedde35c6319fbab0d9efb0f241/corelib/src/prelude/v2023_10.cairo#L1)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

can we move to a module of its own?

Same for bool
</blockquote></details>

we probably can - but not related to this pr.
___
*[`corelib/src/prelude/v2023_10.cairo` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4305#-NhvRq7Z7eIb2MeJkxBj:-NhvmOJHD1GX7rakpA8O:b-zajp72) ([raw file](https://github.com/starkware-libs/cairo/blob/3e4abcf126229cedde35c6319fbab0d9efb0f241/corelib/src/prelude/v2023_10.cairo#L1)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I am not sure we want that, we want people to stop using it directly.
</blockquote></details>

correct - same for dup and drop.
___
*[`corelib/src/prelude/v2023_10.cairo` line 11 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4305#-NhvSD1x0eNjGg-tzubQ:-Nhw1knn0S2ItOQixnvF:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3e4abcf126229cedde35c6319fbab0d9efb0f241/corelib/src/prelude/v2023_10.cairo#L11)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I don't think we want this one.
</blockquote></details>

Done.
___
*[`corelib/src/prelude/v2023_10.cairo` line 22 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4305#-NhvSpCz5KiQrD3ZOYVa:-NhvvTTFAvoYZRQIfuQU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3e4abcf126229cedde35c6319fbab0d9efb0f241/corelib/src/prelude/v2023_10.cairo#L22)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

do we need that but not NumericLiteral?
</blockquote></details>

Done.
___
*[`corelib/src/prelude/v2023_10.cairo` line 23 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4305#-NhvSz6V40TOfw61AtK5:-NhvvlkWDmeG3JS_6zCe:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3e4abcf126229cedde35c6319fbab0d9efb0f241/corelib/src/prelude/v2023_10.cairo#L23)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

is it needed?
</blockquote></details>

Done.
___
*[`corelib/src/prelude/v2023_10.cairo` line  at r2](https://reviewable.io/reviews/starkware-libs/cairo/4305#-Nhv_w3q0QdefA7mM7EG:-Nhvledf49Tt9VFwb-l6:bi4cvgw) ([raw file](https://github.com/starkware-libs/cairo/blob/3e4abcf126229cedde35c6319fbab0d9efb0f241/corelib/src/prelude/v2023_10.cairo#L)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

how about never and debug::PrintTrait? Don't we want them?
</blockquote></details>

`never` isn't actually required by users - they shouldn't really have function returning these in a normal case.
`PrintTrait` should not be used soon enough and would be replaced with format! and so on.

**Review by mkaput — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4305)* status: all files reviewed, 6 unresolved discussions (waiting on @yuvalsw)

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4305)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/prelude/v2023_10.cairo` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4305#-NhvRy4OC0oQF61HdI8Q:-Nhzw7ET4L_of_hibm3q:b-cy2i) ([raw file](https://github.com/starkware-libs/cairo/blob/3e4abcf126229cedde35c6319fbab0d9efb0f241/corelib/src/prelude/v2023_10.cairo#L1)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

we probably can - but not related to this pr.
</blockquote></details>

Thought that this is a good opportunity and we wouldn't want to make a new version only for moving them. Though we can do it in a separate PR in this version, before users start using it.
If you agree - can you please add a TODO?

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4305)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4305)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`corelib/src/prelude/v2023_10.cairo` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4305#-NhvRy4OC0oQF61HdI8Q:-Ni-uwhgCKDJWxsmzS9P:b-q2obht) ([raw file](https://github.com/starkware-libs/cairo/blob/3e4abcf126229cedde35c6319fbab0d9efb0f241/corelib/src/prelude/v2023_10.cairo#L1)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Thought that this is a good opportunity and we wouldn't want to make a new version only for moving them. Though we can do it in a separate PR in this version, before users start using it.
If you agree - can you please add a TODO?
</blockquote></details>

I don't think i understand what do you mean - this is the prelude. moving things into module may happen in the corelib, but this isn't for a todo here.

**Review by mkaput — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4305)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4305#-:-Ni48Z4H1UE2RRtulbwN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4305)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by yuvalsw — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4305)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by yuvalsw — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4305)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
