### PR TITLE
Add storage path update trait.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
**Stack**:
- #5974
- #5973 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5973)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5973)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5973#-O1C8jqLABaORZwSfxWk:-O1C8jqLABaORZwSfxWl:bhezfui) (no related file):*
move to dev-v2.7.0

___
___
*[`corelib/src/starknet/storage.cairo` line 171 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5973#-O1C8ixj4usSLizfnjdW:-O1C8ixk0-_1zWQLIVIn:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/1099363718520cb880f2bfd9bc8d4eb0875e7897/corelib/src/starknet/storage.cairo#L171)):*
> ```Cairo
> }
> 
> trait StoragePathUpdateTrait<T, Key> {
> ```

doc

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5973)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @mkaput, @orizi, and @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5973#-O1C8jqLABaORZwSfxWk:-O1CIORa3LzPxFDFS_jY:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

move to dev-v2.7.0
</blockquote></details>

Done.

___
___
*[`corelib/src/starknet/storage.cairo` line 171 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5973#-O1C8ixj4usSLizfnjdW:-O1CIOw31LXZXwrA_pJf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1099363718520cb880f2bfd9bc8d4eb0875e7897/corelib/src/starknet/storage.cairo#L171)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5973)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware, @mkaput, and @piotmag769)

___
*[`corelib/src/starknet/storage.cairo` line 174 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5973#-O1CJYJj1AzPC1cp8RU6:-O1CJYJj1AzPC1cp8RU7:b-jqzhv3) ([raw file](https://github.com/starkware-libs/cairo/blob/24c52a7e57b959ef02058c7372e80cbc8753dd15/corelib/src/starknet/storage.cairo#L174)):*
> ```Cairo
> /// hash state, usually the generic type of the storage path should be changed, however, this is not
> /// done here, and `into` should be called to convert the storage path to the new type.
> trait StoragePathUpdateTrait<T, Key> {
> ```

why separate this?
this sounds likely to mistakenly convert between types.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5973)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @mkaput, @orizi, and @piotmag769)

___
*[`corelib/src/starknet/storage.cairo` line 174 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5973#-O1CJYJj1AzPC1cp8RU6:-O1CLRQ5-76sOsUuw4M6:b60ev87) ([raw file](https://github.com/starkware-libs/cairo/blob/24c52a7e57b959ef02058c7372e80cbc8753dd15/corelib/src/starknet/storage.cairo#L174)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why separate this?
this sounds likely to mistakenly convert between types.
</blockquote></details>

So change the return type to `StoragePath<S>`?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5973)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware, @mkaput, and @piotmag769)

___
*[`corelib/src/starknet/storage.cairo` line 174 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5973#-O1CJYJj1AzPC1cp8RU6:-O1CM3Rd5WYc3ArAG8Je:b1suzpe) ([raw file](https://github.com/starkware-libs/cairo/blob/24c52a7e57b959ef02058c7372e80cbc8753dd15/corelib/src/starknet/storage.cairo#L174)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

So change the return type to `StoragePath<S>`?
</blockquote></details>

possibly getting the `Value` as part of the trait itself as well.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5973)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @mkaput, @orizi, and @piotmag769)

___
*[`corelib/src/starknet/storage.cairo` line 174 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5973#-O1CJYJj1AzPC1cp8RU6:-O1CWnmxDaEhy0_QV9id:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/24c52a7e57b959ef02058c7372e80cbc8753dd15/corelib/src/starknet/storage.cairo#L174)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

possibly getting the `Value` as part of the trait itself as well.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5973)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware, @mkaput, and @piotmag769)

___
*[`corelib/src/starknet/storage.cairo` line 174 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5973#-O1CYOo91V-khAHEN3FP:-O1CYOo91V-khAHEN3FQ:b-oekxyk) ([raw file](https://github.com/starkware-libs/cairo/blob/0f7603e30221ab188bbb8aeca9673bfdbe71fdd0/corelib/src/starknet/storage.cairo#L174)):*
> ```Cairo
> /// hash state, usually the generic type of the storage path should be changed, however, this is not
> /// done here, and `into` should be called to convert the storage path to the new type.
> trait StoragePathUpdateTrait<S, T, Key> {
> ```

`Key` type name is confusing a bit now.
especially with `value: Key` later.
Probably requires longer name or all 3 generics.



_Code quote:_
```Cairo
trait StoragePathUpdateTrait<S, T, Key> {
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5973)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @mkaput, @orizi, and @piotmag769)

___
*[`corelib/src/starknet/storage.cairo` line 174 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5973#-O1CYOo91V-khAHEN3FP:-O1CaLcu4UwLV5Ic7Bp7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0f7603e30221ab188bbb8aeca9673bfdbe71fdd0/corelib/src/starknet/storage.cairo#L174)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

`Key` type name is confusing a bit now.
especially with `value: Key` later.
Probably requires longer name or all 3 generics.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5973#-:-O1CbrC1BhIBkNEvPeWJ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput and @piotmag769)

**Pull request merged**
