### PR TITLE
added impls in traits

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5718)

### CODE REVIEW

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5718)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 519 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5718#-NzYr0qf7YPV0zFV7iAh:-Nz_HffjBRrZ9yuEK-Zz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b5d269561cdbca1ad7983281ee81bbdd1fe6de1a/crates/cairo-lang-semantic/src/items/tests/trait#L519)):*
> ```
>     type X = u32;
>     const C: u32 = 3;
> ///TODO(TomerStarkware): add one impl when it is supported.
> ```

Done.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5718)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 519 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5718#-NzYr0qf7YPV0zFV7iAh:-Nz_IitZ9CRz5exDsHaw:bvzyjz0) ([raw file](https://github.com/starkware-libs/cairo/blob/b5d269561cdbca1ad7983281ee81bbdd1fe6de1a/crates/cairo-lang-semantic/src/items/tests/trait#L519)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

its a but with the formatter

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5718)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 519 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5718#-NzYr0qf7YPV0zFV7iAh:-Nzb5iUp43sa_OcT5YJp:bwd7jmk) ([raw file](https://github.com/starkware-libs/cairo/blob/b5d269561cdbca1ad7983281ee81bbdd1fe6de1a/crates/cairo-lang-semantic/src/items/tests/trait#L519)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

its a but with the formatter
</blockquote></details>

you still have 3 for some reason.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5718)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 519 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5718#-NzYr0qf7YPV0zFV7iAh:-NzbQ2Q15oGvExMSIu-T:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b5d269561cdbca1ad7983281ee81bbdd1fe6de1a/crates/cairo-lang-semantic/src/items/tests/trait#L519)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you still have 3 for some reason.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5718)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 490 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5718#-NzbReL81LmITJVNQFYY:-NzbReL81LmITJVNQFYZ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/3cbb41c4c4a6416c986962115d5a48f876bee080/crates/cairo-lang-semantic/src/items/tests/trait#L490)):*
> ```
>     type X = u32;
>     const C: u32 = 3;
>     //TODO(TomerStarkware): add one impl when it is supported.
> ```





_Suggestion:_
```
    // TODO(TomerStarkware): add one impl when it is supported.
```
___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 519 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5718#-NzbRgPj6KGQnIOWvjgz:-NzbRgPj6KGQnIOWvjh-:bps1s89) ([raw file](https://github.com/starkware-libs/cairo/blob/3cbb41c4c4a6416c986962115d5a48f876bee080/crates/cairo-lang-semantic/src/items/tests/trait#L519)):*
> ```
>     type X = u32;
>     const C: u32 = 3;
> ///TODO(TomerStarkware): add one impl when it is supported.
> ```

here too

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5718#-:-Nzb_Q_jEAhiJ1K_egcA:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5718)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 490 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5718#-NzbReL81LmITJVNQFYY:-NzbXosiDyHHzJqodXOU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3cbb41c4c4a6416c986962115d5a48f876bee080/crates/cairo-lang-semantic/src/items/tests/trait#L490)):*
> ```
>     type X = u32;
>     const C: u32 = 3;
>     //TODO(TomerStarkware): add one impl when it is supported.
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 519 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5718#-NzbRgPj6KGQnIOWvjgz:-NzbXq6S2Bmhqts7lbth:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3cbb41c4c4a6416c986962115d5a48f876bee080/crates/cairo-lang-semantic/src/items/tests/trait#L519)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

here too
</blockquote></details>

Done.

**Pull request merged**
