### PR TITLE
Merge sierra minor update into coupons

### PR DESCRIPTION
**Pull request by liorgold2**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4662)

### CODE REVIEW

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 121 of 121 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4662)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 121 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4662)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4662#-NmcMHaI-DwIlbnzjKve:-NmcMHaI-DwIlbnzjKvf:bpuekkr) (no related file):*
target branch should be coupons, not main.

___

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4662)* status: 75 of 326 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4662#-NmcMHaI-DwIlbnzjKve:-NmeqjDGBYwNfIQ4mea9:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

target branch should be coupons, not main.
</blockquote></details>

Done.

___

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4662)* status: 71 of 326 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4662#-NmcMHaI-DwIlbnzjKve:-Nmf4Mgi4X2T72GeBuGu:b9xb0ik) (no related file):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I can't seem to look at just the conflict resolutions.

___

**Pull request closed without merging**
