### PR TITLE
Minor refactor of test framework, making compilation somewhat faster.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #1559 ⬅
- #1558
- #1557

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1559)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1559)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-test-utils/src/parse_test_file.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1559#-NKRoAsW6IKCKVcfVn69:-NKRoAsW6IKCKVcfVn6A:b-fy784i) ([raw file](https://github.com/starkware-libs/cairo/blob/f65ed853c6cbdbbf7f3b23e55e6d5d26799b29f7/crates/cairo-test-utils/src/parse_test_file.rs#L195)):*
> ```XML
>         #[test_log::test]
>         fn $test_name() -> Result<(), std::io::Error> {
>             let base_dir = env!("CARGO_MANIFEST_DIR");
> ```

This actually takes the directory at compile time, I'm not usre we want this outside rust tests.



_Code quote:_
```XML
env!("CARGO_MANIFEST_DIR");
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1559)* status: 5 of 7 files reviewed, all discussions resolved

___
*[`crates/cairo-test-utils/src/parse_test_file.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1559#-NKRoAsW6IKCKVcfVn69:-NKRoLAO2i00lsLPWYip:b-nbulop) ([raw file](https://github.com/starkware-libs/cairo/blob/f65ed853c6cbdbbf7f3b23e55e6d5d26799b29f7/crates/cairo-test-utils/src/parse_test_file.rs#L195)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This actually takes the directory at compile time, I'm not usre we want this outside rust tests.
</blockquote></details>

Oh, it is a rust test. nvm

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1559#-:-NKRojg129XaHT9ps3JI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Comment by orizi** [comment]
Closing pull request: commit has gone away

**Pull request closed without merging**
