### PR TITLE
Improve return_optimization.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4781)

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
> Reviewed 26 of 38 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4781)* status: 26 of 38 files reviewed, all discussions resolved

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4781)* status: 9 of 38 files reviewed, 8 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/return_optimization.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4781#-NnsPWOJA2RR2m3MkYDS:-NnsX77y1WmyC-QKg0yy:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/81a9e5c28004609fe2addfb8a86df5ec91c70f61/crates/cairo-lang-lowering/src/optimizations/return_optimization.rs#L18)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Fix doc
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4781)* status: 9 of 38 files reviewed, 8 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/return_optimization.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4781#-NnsPk0kD1wvjiOsfhf7:-Nnstg7L0s8DVrMWoQVm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/81a9e5c28004609fe2addfb8a86df5ec91c70f61/crates/cairo-lang-lowering/src/optimizations/return_optimization.rs#L59)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/optimizations/return_optimization.rs` line 209 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4781#-NnsSvo4AO4hBPH_0sF7:-NnsthkzBDwSWA5a07cm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/81a9e5c28004609fe2addfb8a86df5ec91c70f61/crates/cairo-lang-lowering/src/optimizations/return_optimization.rs#L209)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/optimizations/return_optimization.rs` line 222 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4781#-NnsSxCw3sRvPAQ699Ed:-NnstiOH4lIFTGXgd9Lk:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/81a9e5c28004609fe2addfb8a86df5ec91c70f61/crates/cairo-lang-lowering/src/optimizations/return_optimization.rs#L222)):*
> ```XML
>     }
> 
>     // Replaces occurrences of `var_id` with `var_info`.
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/optimizations/return_optimization.rs` line 229 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4781#-NnsT-8L1GvpXWhmUKZa:-NnstilA3igndjlP4sKp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/81a9e5c28004609fe2addfb8a86df5ec91c70f61/crates/cairo-lang-lowering/src/optimizations/return_optimization.rs#L229)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/optimizations/return_optimization.rs` line 233 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4781#-NnsT-tGA7foGDoe5twv:-NnstjGe7pNf6CJ3A0hx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/81a9e5c28004609fe2addfb8a86df5ec91c70f61/crates/cairo-lang-lowering/src/optimizations/return_optimization.rs#L233)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/optimizations/return_optimization.rs` line 244 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4781#-NnsT2Ic2OLOjv4srYay:-NnstjoGDtzUzes0W5k6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/81a9e5c28004609fe2addfb8a86df5ec91c70f61/crates/cairo-lang-lowering/src/optimizations/return_optimization.rs#L244)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/optimizations/return_optimization.rs` line 255 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4781#-NnsT3rUE2leHQa7PjM7:-NnstkQb-ePgZwX0gLuN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/81a9e5c28004609fe2addfb8a86df5ec91c70f61/crates/cairo-lang-lowering/src/optimizations/return_optimization.rs#L255)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4781)* status: 9 of 38 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/return_optimization.rs` line 17 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4781#-NnsyS0l-315PVMNtt-Q:-NnsyS0l-315PVMNtt-R:b-fr2zgm) ([raw file](https://github.com/starkware-libs/cairo/blob/c37f9b86ac81a277fa9c94cc98e2c65a59e748ed/crates/cairo-lang-lowering/src/optimizations/return_optimization.rs#L17)):*
> ```XML
> };
> 
> /// adds early returns when applicable.
> ```

add more high level algorithm doc.



_Suggestion:_
```XML
/// Adds early returns when applicable.
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 13 of 29 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4781)* status: 23 of 38 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/test_data/cycles` line 39 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4781#-NnszeP4CeBuxiigPTA7:-NnszeP4CeBuxiigPTA8:brcsq4h) ([raw file](https://github.com/starkware-libs/cairo/blob/c355437b637c09fbc07f9b01362d8959dc932f8c/crates/cairo-lang-lowering/src/test_data/cycles#L39)):*
> ```
>   (v23: core::RangeCheck, v24: core::gas::GasBuiltin, v9: core::panics::PanicResult::<((),)>) <- test::foo(v19, v20, v0)
> End:
>   Match(match_enum(v9) {
> ```

isn't the return here the correct one?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/test_data/cycles` line 39 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4781#-NnszeP4CeBuxiigPTA7:-Nnt0L_lDV2l3Bp-GAmD:b8r2hqo) ([raw file](https://github.com/starkware-libs/cairo/blob/c355437b637c09fbc07f9b01362d8959dc932f8c/crates/cairo-lang-lowering/src/test_data/cycles#L39)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

isn't the return here the correct one?
</blockquote></details>

Yes, but v14 is not a unit, so the current logic does not support it here.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/test_data/cycles` line 39 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4781#-NnszeP4CeBuxiigPTA7:-Nnt0L_lDV2l3Bp-GAmD:b8r2hqo) ([raw file](https://github.com/starkware-libs/cairo/blob/c355437b637c09fbc07f9b01362d8959dc932f8c/crates/cairo-lang-lowering/src/test_data/cycles#L39)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

isn't the return here the correct one?
</blockquote></details>

Yes, but v14 is not a unit, so the current logic does not support it here.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4781)* status: 22 of 38 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/return_optimization.rs` line 17 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4781#-NnsyS0l-315PVMNtt-Q:-Nnt1TtkDcZ_D5iHXQke:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c37f9b86ac81a277fa9c94cc98e2c65a59e748ed/crates/cairo-lang-lowering/src/optimizations/return_optimization.rs#L17)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add more high level algorithm doc.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 15 of 29 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4781)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/return_optimization.rs` line 17 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4781#-NnsyS0l-315PVMNtt-Q:-Nnt67Wr09XoditWL4aO:bjllpnh) ([raw file](https://github.com/starkware-libs/cairo/blob/c37f9b86ac81a277fa9c94cc98e2c65a59e748ed/crates/cairo-lang-lowering/src/optimizations/return_optimization.rs#L17)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Add more doc.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4781)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/return_optimization.rs` line 17 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4781#-NnsyS0l-315PVMNtt-Q:-Nnt75c7Ab0S7RsQWcvL:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c37f9b86ac81a277fa9c94cc98e2c65a59e748ed/crates/cairo-lang-lowering/src/optimizations/return_optimization.rs#L17)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Add more doc.
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4781)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4781#-:-NntD_1G3iRiF0J_WnLG:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Pull request merged**
