### PR TITLE
Added support for minus literals in const items.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #4013
- #4027 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4027)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4027)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1883 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4027#-NdkcLx0BeEp7VdzbJKV:-NdkcLx0BeEp7VdzbJKW:b86qci9) ([raw file](https://github.com/starkware-libs/cairo/blob/bb0afda5781d6704f658a6e050aa64a6f733d6b1/crates/cairo-lang-semantic/src/expr/compute.rs#L1883)):*
> ```XML
>     if signature.panicable
>         // Minus literals are a special case, since we know these cannot actually panic, and can occur out of functions. Checking their range is valid occurs at a later stage.
>         && try_extract_minus_literal(ctx.db, &ctx.exprs, &expr_function_call).is_none()
> ```

why did you change the order?
___
*[`crates/cairo-lang-semantic/src/expr/test_data/constant` line 134 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4027#-NdkaIhj3wGnSiCODWpo:-NdkaIhj3wGnSiCODWpp:b-tw2nrj) ([raw file](https://github.com/starkware-libs/cairo/blob/bb0afda5781d6704f658a6e050aa64a6f733d6b1/crates/cairo-lang-semantic/src/expr/test_data/constant#L134)):*
> ```
> 
> //! > test_runner_name
> test_function_diagnostics
> ```

please add allow_diagnostics/expect_diagnostics (depending on whether my PR changing it is already in or not). Also in the next test.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/constant` line 161 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4027#-NdkabkeDq_RK6Q8we8f:-NdkabkeDq_RK6Q8we8g:b-j8l772) ([raw file](https://github.com/starkware-libs/cairo/blob/bb0afda5781d6704f658a6e050aa64a6f733d6b1/crates/cairo-lang-semantic/src/expr/test_data/constant#L161)):*
> ```
> foo
> 
> //! > module_code
> ```

add out of range positive values?
0x80, 0x8000

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4027)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/constant` line 129 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4027#-Ndkgta09EsF93e5VrTR:-Ndkgta09EsF93e5VrTS:b-io4ac9) ([raw file](https://github.com/starkware-libs/cairo/blob/bb0afda5781d6704f658a6e050aa64a6f733d6b1/crates/cairo-lang-semantic/src/expr/test_data/constant#L129)):*
> ```
>                         ^*^
> 
> //! > ==========================================================================
> ```

Can you add a test calling it from a nopanic function?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4027)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1883 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4027#-NdkcLx0BeEp7VdzbJKV:-Ndo91vy6vgOhG1TGcAB:b-4ufln6) ([raw file](https://github.com/starkware-libs/cairo/blob/bb0afda5781d6704f658a6e050aa64a6f733d6b1/crates/cairo-lang-semantic/src/expr/compute.rs#L1883)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

why did you change the order?
</blockquote></details>

now it prevents asking for `get_signature?` which fails out of function (so this is required for const items)
___
*[`crates/cairo-lang-semantic/src/expr/test_data/constant` line 129 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4027#-Ndkgta09EsF93e5VrTR:-NdoAbGF2kk8smWmX194:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bb0afda5781d6704f658a6e050aa64a6f733d6b1/crates/cairo-lang-semantic/src/expr/test_data/constant#L129)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Can you add a test calling it from a nopanic function?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/constant` line 134 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4027#-NdkaIhj3wGnSiCODWpo:-NdoAHuA-PJX6U_axlAK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bb0afda5781d6704f658a6e050aa64a6f733d6b1/crates/cairo-lang-semantic/src/expr/test_data/constant#L134)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

please add allow_diagnostics/expect_diagnostics (depending on whether my PR changing it is already in or not). Also in the next test.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/constant` line 161 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4027#-NdkabkeDq_RK6Q8we8f:-NdoAIsG7uR3_1DCevxL:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bb0afda5781d6704f658a6e050aa64a6f733d6b1/crates/cairo-lang-semantic/src/expr/test_data/constant#L161)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

add out of range positive values?
0x80, 0x8000
</blockquote></details>

Done.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4027#-:-Ndyjcm34ojWu-AyODmB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1883 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4027#-NdkcLx0BeEp7VdzbJKV:-NdyiQF662RdWS_xoKzr:bhnwdau) ([raw file](https://github.com/starkware-libs/cairo/blob/bb0afda5781d6704f658a6e050aa64a6f733d6b1/crates/cairo-lang-semantic/src/expr/compute.rs#L1883)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

now it prevents asking for `get_signature?` which fails out of function (so this is required for const items)
</blockquote></details>

OK.
But this becomes a little complicated. I suggest to export to a function is_??_panicable, and document each term inside it. As in something like:

// first check if this is a literal.
if !try_extract_minus_literal(...) {
   return false;
}
// The rest of the cases can only happen inside a function...
...

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4027#-:-NdzoB50-npX59V-cmvv:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1889 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4027#-NdznzT8751wSduMhhve:-NdznzT8751wSduMhhvf:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d6251550ab5b1e3aa386a5ef0e2e30dcd31fe44d/crates/cairo-lang-semantic/src/expr/compute.rs#L1889)):*
> ```XML
> }
> 
> /// Checks a panicable function is called from a disallowed context.
> ```





_Suggestion:_
```XML
// Checks if a panicable functio
```
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1900 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4027#-NdznxdH6IyPpflKNVip:-NdznxdH6IyPpflKNViq:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d6251550ab5b1e3aa386a5ef0e2e30dcd31fe44d/crates/cairo-lang-semantic/src/expr/compute.rs#L1900)):*
> ```XML
>     }
>     // If this is not from within a context of a function - e.g. a const item, we will exit with an
>     // error here., as this is a call with bad context.
> ```





_Suggestion:_
```XML
    // If this is not from within a context of a function - e.g. a const item, we will exit with an
    // error here, as this is a call with bad context.
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4027)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
