### PR TITLE
Parallelize tests in CI

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3073)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3073** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3073" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/3073?utm_source=stack-comment).

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3073)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3073#-NUz8rQL5iyAzspkufOt:-NUz8rQL5iyAzspkufOu:b-dlxx42) (no related file):*
FYI `nextest` has partitioning, maybe this could help? https://nexte.st/book/partitioning.html, at least the workflow won't have to enumerate all crates

___

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3073)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3073#-NUz8rQL5iyAzspkufOt:-NUzFbV61uq3_ti0VyMT:b9zdw8c) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

FYI `nextest` has partitioning, maybe this could help? https://nexte.st/book/partitioning.html, at least the workflow won't have to enumerate all crates
</blockquote></details>

Just tried it. A downside I see is that all workers need to build all the test artifacts, which makes it slower

___

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3073)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3073#-NUz8rQL5iyAzspkufOt:-NUzIx7-0JYpO9tkSfTs:b-cd4ld4) (no related file):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Just tried it. A downside I see is that all workers need to build all the test artifacts, which makes it slower
</blockquote></details>

I did however use it to partition that slowest crate tests :) Thanks

___

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3073)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3073#-NUz8rQL5iyAzspkufOt:-NUzLkab47Kvcsn8ljW3:b8z0zvv) (no related file):*
> A downside I see is that all workers need to build all the test artifacts, which makes it slower

I think there was a trick to build artefacts once and run tests in parallel...

___

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3073)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3073#-NUz8rQL5iyAzspkufOt:-NUzLyvc66i0g7e37ErI:bsle71n) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

> A downside I see is that all workers need to build all the test artifacts, which makes it slower

I think there was a trick to build artefacts once and run tests in parallel...
</blockquote></details>

https://nexte.st/book/partitioning.html#reusing-builds

___

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3073)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3073#-NUz8rQL5iyAzspkufOt:-NUzUSFf4XA7cuUxPpAi:b-ppc6oa) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

https://nexte.st/book/partitioning.html#reusing-builds
</blockquote></details>

Like I said, I already did that, and it was super slow

___

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3073#-:-NUzVyrB0tqEqcczkEK9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
