### PR TITLE
add get_class_hash_at_syscall

### PR DESCRIPTION
**Pull request by dean-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6407)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6407)* status: 8 of 9 files reviewed, 4 unresolved discussions (waiting on @dean-starkware)

___
*[`corelib/src/starknet.cairo` line 29 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6407#-O7U-BRP7kJqq7X5iwOX:-O7U-BRP7kJqq7X5iwOY:b-xl8gvk) ([raw file](https://github.com/starkware-libs/cairo/blob/5ffae46de486838d214adbb839efb17d7dbde260/corelib/src/starknet.cairo#L29)):*
> ```Cairo
>     call_contract_syscall, deploy_syscall, emit_event_syscall, get_block_hash_syscall,
>     get_execution_info_syscall, library_call_syscall, send_message_to_l1_syscall,
>     storage_read_syscall, storage_write_syscall, replace_class_syscall, keccak_syscall,get_class_hash_at_syscall
> ```

`./scripts/cairo_fmt.sh`



_Code quote:_
```Cairo
    get_execution_info_syscall, library_call_syscall, send_message_to_l1_syscall,
    storage_read_syscall, storage_write_syscall, replace_class_syscall, keccak_syscall,get_class_hash_at_syscall
```
___
*[`crates/cairo-lang-starknet/cairo_level_tests/replace_class_test.cairo` line 92 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6407#-O7U0epcB4uNM_9Ly2X0:-O7U0epcB4uNM_9Ly2X1:b8j8em8) ([raw file](https://github.com/starkware-libs/cairo/blob/5ffae46de486838d214adbb839efb17d7dbde260/crates/cairo-lang-starknet/cairo_level_tests/replace_class_test.cairo#L92)):*
> ```Cairo
> #[test]
> fn test_class_hash_at_syscall() {
>     use starknet::syscalls::get_class_hash_at_syscall;
> ```

add the `use` on top.



_Code quote:_
```Cairo
    use starknet::syscalls::get_class_hash_at_syscall;
```
___
*[`crates/cairo-lang-starknet/cairo_level_tests/replace_class_test.cairo` line 108 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6407#-O7U1aRm8HEcbAR-T5wR:-O7U1aRm8HEcbAR-T5wS:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5ffae46de486838d214adbb839efb17d7dbde260/crates/cairo-lang-starknet/cairo_level_tests/replace_class_test.cairo#L108)):*
> ```Cairo
>     // Check that the class hash returned by the syscall matches the expected class hash.
>     let expected_class_hash: ClassHash = contract_a::TEST_CLASS_HASH.try_into().unwrap();
>     assert_eq!(class_hash_result.unwrap_syscall(), expected_class_hash);
> ```





_Suggestion:_
```Cairo
    let a_class_hash = contract_a::TEST_CLASS_HASH.try_into().unwrap();
    // Deploy ContractA with 100 in the storage.
    let (address0, _) = deploy_syscall(
        class_hash: a_class_hash,
        contract_address_salt: 0,
        calldata: [100].span(),
        deploy_from_zero: false
    )
        .unwrap();

    assert_eq!(get_class_hash_at_syscall(address0), Result::Ok(a_class_hash));
    // Replace its class hash to Class B.
    let mut contract0 = IWithReplaceDispatcher { contract_address: address0 };
    let b_class_hash = contract_b::TEST_CLASS_HASH.try_into().unwrap();
    assert_eq!(get_class_hash_at_syscall(address0), Result::Ok(b_class_hash));

    
```
___
*[`crates/cairo-lang-starknet/cairo_level_tests/replace_class_test.cairo` line 121 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6407#-O7U0qHP3fhocFp1zgFP:-O7U0qHP3fhocFp1zgFQ:b-igv6pk) ([raw file](https://github.com/starkware-libs/cairo/blob/5ffae46de486838d214adbb839efb17d7dbde260/crates/cairo-lang-starknet/cairo_level_tests/replace_class_test.cairo#L121)):*
> ```Cairo
>     // Try to get the class hash at the invalid address, expecting the syscall to panic.
>     let _ = get_class_hash_at_syscall(invalid_address).unwrap_syscall();
> }
> ```

delete test - as the result itself is wrong.

add instead a test of calling on undeployed contract. returning 0.



_Code quote:_
```Cairo
#[test]
#[should_panic(expected = "CLASS_HASH_NOT_FOUND")]
fn test_class_hash_at_syscall_invalid_address() {
    use starknet::syscalls::get_class_hash_at_syscall;

    // Use an invalid contract address that should cause the syscall to fail.
    let invalid_address = 999999u64.into();

    // Try to get the class hash at the invalid address, expecting the syscall to panic.
    let _ = get_class_hash_at_syscall(invalid_address).unwrap_syscall();
}
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6407)* status: 8 of 9 files reviewed, 6 unresolved discussions (waiting on @dean-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6407#-O7Yj_6o-h12HJaUMD3t:-O7Yj_6o-h12HJaUMD3u:bhwp15b) (no related file):*
note that your tests fail - since you didn't add a handler for the new syscall at:
`crates/cairo-lang-runner/src/casm_run/mod.rs:800`

___
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/starknet/mod.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6407#-O7Yk2bY6eM-XHtUDSvV:-O7Yk2bY6eM-XHtUDSvW:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5ffae46de486838d214adbb839efb17d7dbde260/crates/cairo-lang-sierra-to-casm/src/invocations/starknet/mod.rs#L88)):*
> ```XML
>         StarkNetConcreteLibfunc::GetClassHashAt(_) => {
>             build_syscalls(builder, "GetClassHashAt", [1], [1])
>         }
> ```





_Suggestion:_
```XML
        StarkNetConcreteLibfunc::GetClassHashAt(_) => {
            build_syscalls(builder, "GetClassHashAt", [1], [1])
        }
        StarkNetConcreteLibfunc::SendMessageToL1(_) => {
            build_syscalls(builder, "SendMessageToL1", [1, 2], [])
        }
        StarkNetConcreteLibfunc::Testing(libfunc) => testing::build(libfunc, builder),
        StarkNetConcreteLibfunc::Secp256(libfunc) => secp256::build(libfunc, builder),
```

**Review by dean-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6407)* status: 8 of 9 files reviewed, 6 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6407#-O7Yj_6o-h12HJaUMD3t:-O7YksHbAkHUki75PlHd:b-4ds50w) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

note that your tests fail - since you didn't add a handler for the new syscall at:
`crates/cairo-lang-runner/src/casm_run/mod.rs:800`
</blockquote></details>

Yes, thanks for letting me know.
Before updating this, I'm trying to get a better understanding of what I'm actually doing, and the process itself.
Will fix it asap.

___

**Review by dean-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6407)* status: 8 of 9 files reviewed, 6 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6407#-O7Yj_6o-h12HJaUMD3t:-O7Yl9jgDPIDqyrR-ez1:bp5o4c7) (no related file):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

Yes, thanks for letting me know.
Before updating this, I'm trying to get a better understanding of what I'm actually doing, and the process itself.
Will fix it asap.
</blockquote></details>

Let me know if you prefer that I will get done with it sooner than later.

___

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6407)* status: all files reviewed, 6 unresolved discussions (waiting on @dean-starkware)

**Review by dean-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6407)* status: all files reviewed, 6 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/replace_class_test.cairo` line 92 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6407#-O7U0epcB4uNM_9Ly2X0:-O7YpppO2Zwe03eXjVwC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5ffae46de486838d214adbb839efb17d7dbde260/crates/cairo-lang-starknet/cairo_level_tests/replace_class_test.cairo#L92)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add the `use` on top.
</blockquote></details>

Done.

**Review by dean-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6407)* status: all files reviewed, 6 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/replace_class_test.cairo` line 108 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6407#-O7U1aRm8HEcbAR-T5wR:-O7YqxbU35lg_MNbvLc9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5ffae46de486838d214adbb839efb17d7dbde260/crates/cairo-lang-starknet/cairo_level_tests/replace_class_test.cairo#L108)):*
> ```Cairo
>     // Check that the class hash returned by the syscall matches the expected class hash.
>     let expected_class_hash: ClassHash = contract_a::TEST_CLASS_HASH.try_into().unwrap();
>     assert_eq!(class_hash_result.unwrap_syscall(), expected_class_hash);
> ```

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6407)* status: all files reviewed, 4 unresolved discussions (waiting on @dean-starkware)

**Review by dean-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6407)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/starknet.cairo` line 29 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6407#-O7U-BRP7kJqq7X5iwOX:-O7ZFeV5428HlMPkgH6m:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5ffae46de486838d214adbb839efb17d7dbde260/corelib/src/starknet.cairo#L29)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

`./scripts/cairo_fmt.sh`
</blockquote></details>

Done.

**Review by dean-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6407)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/starknet/mod.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6407#-O7Yk2bY6eM-XHtUDSvV:-O7ZGPLs1SkzGCQhQOpz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5ffae46de486838d214adbb839efb17d7dbde260/crates/cairo-lang-sierra-to-casm/src/invocations/starknet/mod.rs#L88)):*
> ```XML
>         StarkNetConcreteLibfunc::GetClassHashAt(_) => {
>             build_syscalls(builder, "GetClassHashAt", [1], [1])
>         }
> ```

Done.

**Review by dean-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6407)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/replace_class_test.cairo` line 121 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6407#-O7U0qHP3fhocFp1zgFP:-O7ZHoYwEP4tuPxsC-VV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5ffae46de486838d214adbb839efb17d7dbde260/crates/cairo-lang-starknet/cairo_level_tests/replace_class_test.cairo#L121)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

delete test - as the result itself is wrong.

add instead a test of calling on undeployed contract. returning 0.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6407)* status: 7 of 10 files reviewed, 4 unresolved discussions (waiting on @dean-starkware)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1133 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6407#-O7ZJcKWCDZ089rB1KNc:-O7ZJcKWCDZ089rB1KNd:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/4ff34a6503d3f344d00e509a6a5acdafaf3bc0f8/crates/cairo-lang-runner/src/casm_run/mod.rs#L1133)):*
> ```XML
>         };
> 
>         Ok(SyscallResult::Success(vec![MaybeRelocatable::Int(class_hash.clone())]))
> ```





_Suggestion:_
```XML
        let class_hash = self.starknet_state.deployed_contracts.get(&contract_address)
            .cloned().unwrap_or_else(Felt252::zero)
        Ok(SyscallResult::Success(vec![MaybeRelocatable::Int(class_hash)]))
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6407)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @dean-starkware)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1133 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6407#-O7ZJcKWCDZ089rB1KNc:-O7ZKlaQ919Jw6ffASXR:bbd1d7a) ([raw file](https://github.com/starkware-libs/cairo/blob/4ff34a6503d3f344d00e509a6a5acdafaf3bc0f8/crates/cairo-lang-runner/src/casm_run/mod.rs#L1133)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

Already changed it.
</blockquote></details>

no you haven't.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/replace_class_test.cairo` line 114 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6407#-O7ZKXoeActOTBCuTRSf:-O7ZKXoeActOTBCuTRSg:b-hfpv23) ([raw file](https://github.com/starkware-libs/cairo/blob/4ff34a6503d3f344d00e509a6a5acdafaf3bc0f8/crates/cairo-lang-starknet/cairo_level_tests/replace_class_test.cairo#L114)):*
> ```Cairo
> #[test]
> fn test_class_hash_at_syscall_undeployed_contract() {
>     use starknet::syscalls::get_class_hash_at_syscall;
> ```

remove.



_Code quote:_
```Cairo
    use starknet::syscalls::get_class_hash_at_syscall;
```
___
*[`crates/cairo-lang-starknet/cairo_level_tests/replace_class_test.cairo` line 119 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6407#-O7ZKVgk0YnKxgCWFxvb:-O7ZKVgk0YnKxgCWFxvc:bzi3h7o) ([raw file](https://github.com/starkware-libs/cairo/blob/4ff34a6503d3f344d00e509a6a5acdafaf3bc0f8/crates/cairo-lang-starknet/cairo_level_tests/replace_class_test.cairo#L119)):*
> ```Cairo
>     // Try to get the class hash at the undeployed contract address, expecting a return value of 0.
>     let class_hash = get_class_hash_at_syscall(undeployed_contract_address).unwrap_syscall();
>     assert_eq!(class_hash, 0);
> ```

don't unwrap.
check result eq - like the other test.



_Code quote:_
```Cairo
    let class_hash = get_class_hash_at_syscall(undeployed_contract_address).unwrap_syscall();
    assert_eq!(class_hash, 0);
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6407)* status: 9 of 11 files reviewed, 4 unresolved discussions (waiting on @dean-starkware)

___
*[`crates/cairo-lang-starknet-classes/src/allowed_libfuncs_lists/all.json` line 255 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6407#-O7ZR3WS68l4VjD6ZjtS:-O7ZR3WS68l4VjD6ZjtT:b-ay9n31) ([raw file](https://github.com/starkware-libs/cairo/blob/c67550958046c5b0ecdbe47e39721c2683f2c67a/crates/cairo-lang-starknet-classes/src/allowed_libfuncs_lists/all.json#L255)):*
> ```JSON
>         "withdraw_gas_all"
>     ]
> }
> ```

add endline.

**Review by dean-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6407)* status: 9 of 11 files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1133 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6407#-O7ZJcKWCDZ089rB1KNc:-O7bxP8t-pz7ZgRU2BHi:b-krmyal) ([raw file](https://github.com/starkware-libs/cairo/blob/4ff34a6503d3f344d00e509a6a5acdafaf3bc0f8/crates/cairo-lang-runner/src/casm_run/mod.rs#L1133)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no you haven't.
</blockquote></details>

I'm confused. I'm sure I did. Can you check again please?
___
*[`crates/cairo-lang-starknet/cairo_level_tests/replace_class_test.cairo` line 114 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6407#-O7ZKXoeActOTBCuTRSf:-O7bxvgKDBDv4Ut6KPpr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4ff34a6503d3f344d00e509a6a5acdafaf3bc0f8/crates/cairo-lang-starknet/cairo_level_tests/replace_class_test.cairo#L114)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/replace_class_test.cairo` line 119 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6407#-O7ZKVgk0YnKxgCWFxvb:-O7bxwJsEBTdPd81rapG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4ff34a6503d3f344d00e509a6a5acdafaf3bc0f8/crates/cairo-lang-starknet/cairo_level_tests/replace_class_test.cairo#L119)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

don't unwrap.
check result eq - like the other test.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet-classes/src/allowed_libfuncs_lists/all.json` line 255 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6407#-O7bxVYA3CZoJCsSQX6z:-O7bxVYA3CZoJCsSQX7-:b6224oo) ([raw file](https://github.com/starkware-libs/cairo/blob/c67550958046c5b0ecdbe47e39721c2683f2c67a/crates/cairo-lang-starknet-classes/src/allowed_libfuncs_lists/all.json#L255)):*
> ```JSON
>         "withdraw_gas_all"
>     ]
> }
> ```

It's not clear where. Please explain.

**Review by dean-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6407)* status: 9 of 11 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet-classes/src/allowed_libfuncs_lists/all.json` line 255 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6407#-O7ZR3WS68l4VjD6ZjtS:-O7by56428lXOAjCOWEN:b6224oo) ([raw file](https://github.com/starkware-libs/cairo/blob/c67550958046c5b0ecdbe47e39721c2683f2c67a/crates/cairo-lang-starknet-classes/src/allowed_libfuncs_lists/all.json#L255)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add endline.
</blockquote></details>

It's not clear where. Please explain.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6407)* status: 10 of 11 files reviewed, 4 unresolved discussions (waiting on @dean-starkware)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1133 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6407#-O7ZJcKWCDZ089rB1KNc:-O7cCuY67tHVCptyI5Yr:b-kp5yy2) ([raw file](https://github.com/starkware-libs/cairo/blob/4ff34a6503d3f344d00e509a6a5acdafaf3bc0f8/crates/cairo-lang-runner/src/casm_run/mod.rs#L1133)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

I'm confused. I'm sure I did. Can you check again please?
</blockquote></details>

now you have.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/replace_class_test.cairo` line 118 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6407#-O7cD0Jr5PNH3OkXHG8p:-O7cD0Jr5PNH3OkXHG8q:b-9f8l1f) ([raw file](https://github.com/starkware-libs/cairo/blob/33c2c6cd4334bb15a56be0f61399d888bc1ff9d0/crates/cairo-lang-starknet/cairo_level_tests/replace_class_test.cairo#L118)):*
> ```Cairo
>     // Try to get the class hash at the undeployed contract address, expecting a return value of 0.
>     let result = get_class_hash_at_syscall(undeployed_contract_address);
>     assert_eq!(result, Ok(0));
> ```

this requires casting to `ConstractAddress` and `ClassHash` - make sure to run:
`./scripts/starknet_test.sh`.



_Code quote:_
```Cairo
    // Use an address that does not have a contract deployed.
    let undeployed_contract_address = 123456; // This should be a valid but undeployed address.
    // Try to get the class hash at the undeployed contract address, expecting a return value of 0.
    let result = get_class_hash_at_syscall(undeployed_contract_address);
    assert_eq!(result, Ok(0));
```
___
*[`crates/cairo-lang-starknet-classes/src/allowed_libfuncs_lists/all.json` line 255 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6407#-O7ZR3WS68l4VjD6ZjtS:-O7cDAJ34z8y1FB6X1RQ:b-mx8rtm) ([raw file](https://github.com/starkware-libs/cairo/blob/c67550958046c5b0ecdbe47e39721c2683f2c67a/crates/cairo-lang-starknet-classes/src/allowed_libfuncs_lists/all.json#L255)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

It's not clear where. Please explain.
</blockquote></details>

you removed the last `\n` of the file - re-add it.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6407)* status: all files reviewed, 4 unresolved discussions (waiting on @dean-starkware)

**Review by dean-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6407)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1133 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6407#-O7ZJcKWCDZ089rB1KNc:-O7cgsES41B9tvGsUIHY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4ff34a6503d3f344d00e509a6a5acdafaf3bc0f8/crates/cairo-lang-runner/src/casm_run/mod.rs#L1133)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

now you have.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/replace_class_test.cairo` line 118 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6407#-O7cD0Jr5PNH3OkXHG8p:-O7dNjkB64U4oPlT7u0G:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/33c2c6cd4334bb15a56be0f61399d888bc1ff9d0/crates/cairo-lang-starknet/cairo_level_tests/replace_class_test.cairo#L118)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this requires casting to `ConstractAddress` and `ClassHash` - make sure to run:
`./scripts/starknet_test.sh`.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet-classes/src/allowed_libfuncs_lists/all.json` line 255 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6407#-O7ZR3WS68l4VjD6ZjtS:-O7chAAY3M_X63UZMJJM:bwhli46) ([raw file](https://github.com/starkware-libs/cairo/blob/c67550958046c5b0ecdbe47e39721c2683f2c67a/crates/cairo-lang-starknet-classes/src/allowed_libfuncs_lists/all.json#L255)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you removed the last `\n` of the file - re-add it.
</blockquote></details>

I didn't remove it.
I doubled check and it's the same as before.
The formatter doesn't allowed it either.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6407)* status: all files reviewed, 1 unresolved discussion (waiting on @dean-starkware)

___
*[`crates/cairo-lang-starknet-classes/src/allowed_libfuncs_lists/all.json` line 255 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6407#-O7ZR3WS68l4VjD6ZjtS:-O7ddQE2-NJw45IrC1uY:b-6vssxa) ([raw file](https://github.com/starkware-libs/cairo/blob/c67550958046c5b0ecdbe47e39721c2683f2c67a/crates/cairo-lang-starknet-classes/src/allowed_libfuncs_lists/all.json#L255)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

I didn't remove it.
I doubled check and it's the same as before.
The formatter doesn't allowed it either.
</blockquote></details>

it is changed.
you need to properly set your vscode.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6407#-:-O7h4-f18wvkCuO1m17p:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dean-starkware)

**Pull request merged**
