### PR TITLE
corelib: circuit related utils improvements

### PR DESCRIPTION
**Pull request by feltroidprime**
circuit.cairo 
- Implement `One` for u384 
- Uses `panic_with_felt252` instead of `panic!` macro (this significantly reduces bytecode) in `next` and `done`

metaprogramming.cairo
- Support up to 16 outputs. Useful/needed for Kakarot's ec_pairing.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6482)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6482)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @feltroidprime)

___
*[`corelib/src/circuit.cairo` line 278 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6482#-O93mCf44QaY8Ff_pXAB:-O93mCf44QaY8Ff_pXAC:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0f90aff863251e4acfa7bf76369ed286fe92a66d/corelib/src/circuit.cairo#L278)):*
> ```Cairo
>         match self {
>             AddInputResult::Done(data) => data,
>             AddInputResult::More(_) => panic_with_felt252('Not all inputs have been filled'),
> ```





_Suggestion:_
```Cairo
            ),
            AddInputResult::Done(_) => core::panic_with_felt252('All inputs have been filled'),
        }
    }
    // Inlining to make sure possibly huge `C` won't be in a user function name.
    #[inline]
    fn done(self: AddInputResult<C>) -> CircuitData<C> {
        match self {
            AddInputResult::Done(data) => data,
            AddInputResult::More(_) => core::panic_with_felt252('Not all inputs have been filled'),
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6482#-:-O93ofYwBpRNOw6qQjdM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @feltroidprime)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6482)* status: all files reviewed, 1 unresolved discussion (waiting on @feltroidprime)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6482#-O93r41H6KXEp01cn1I7:-O93r41I1pREqXGqxVzv:b-h1kqrf) (no related file):*
please run fixer for all tests.
`CAIRO_FIX_TESTS=1 cargo t --profile=ci-dev`

___

**Review by orizi — COMMENTED** [review]
> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6482)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @feltroidprime)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6482#-O949GHE8X9kraRln1Py:-O949GHE8X9kraRln1Pz:b-1yejuw) (no related file):*
@ilyalesokhin-starkware for second eye.

___

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6482)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @feltroidprime)

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6482)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @feltroidprime)

**Comment by feltroidprime** [comment]
Thank you!

**Pull request merged**
