### PR TITLE
Create api for diagnostics ensure with no need for lowering group

### PR DESCRIPTION
**Pull request by wawel37**
We decided to create a diagnostics' api, that doesn't require a LoweringGroup db, as without it, the diagnostic performence is much more better. For more information, [click here](https://github.com/software-mansion/scarb/pull/1590).

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6440)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6440)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mkaput and @wawel37)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6440#-O823Qz8Ev3pD5a-TuQm:-O823Qz8Ev3pD5a-TuQn:b-rkuu1q) (no related file):*
please explain more - and not that there are some missing diagnostics if this is skipped.

___

**Comment by maciektr** [comment]
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

please explain more - and not that there are some missing diagnostics if this is skipped.
</blockquote></details>

@orizi It is expected to be used by `scarb-doc` which does not need `LoweringGroup`. The intention is to be able to calculate diagnostics without adding lowering group just for this purpose.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6440)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @maciektr and @mkaput)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6440#-O823Qz8Ev3pD5a-TuQm:-O82FUrB05Hb9VkcUPHz:b1u9nyl) (no related file):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

@orizi It is expected to be used by `scarb-doc` which does not need `LoweringGroup`. The intention is to be able to calculate diagnostics without adding lowering group just for this purpose.
</blockquote></details>

can you try setting up the db with - "add_withdraw_gas" flag as `false`? i think that is the cause for the extra time.

___

**Comment by maciektr** [comment]
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can you try setting up the db with - "add_withdraw_gas" flag as `false`? i think that is the cause for the extra time.
</blockquote></details>

Hmm , I have tried setting 
```
        let add_withdraw_gas_flag_id = FlagId::new(db.upcast(), "add_withdraw_gas");
        db.set_flag(
            add_withdraw_gas_flag_id,
            Some(Arc::new(Flag::AddWithdrawGas(false))),
        );

        db.set_optimization_config(Arc::new(
            OptimizationConfig::default().with_inlining_strategy(InliningStrategy::Avoid),
        ));

```
and did not see any real difference in benchmarks.

To be honest, the time penalty is a one thing, but would you advise adding the `LoweringGroup` to the database only in order to calculate diagnostics? :thinking: I may be wrong, but it just don't seem like an enough reason to do so.

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6440)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @maciektr and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6440#-O823Qz8Ev3pD5a-TuQm:-O85cFXO-9BVn9ornRh7:b-xigc17) (no related file):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

Hmm , I have tried setting 
```
        let add_withdraw_gas_flag_id = FlagId::new(db.upcast(), "add_withdraw_gas");
        db.set_flag(
            add_withdraw_gas_flag_id,
            Some(Arc::new(Flag::AddWithdrawGas(false))),
        );

        db.set_optimization_config(Arc::new(
            OptimizationConfig::default().with_inlining_strategy(InliningStrategy::Avoid),
        ));

```
and did not see any real difference in benchmarks.

To be honest, the time penalty is a one thing, but would you advise adding the `LoweringGroup` to the database only in order to calculate diagnostics? :thinking: I may be wrong, but it just don't seem like an enough reason to do so.
</blockquote></details>

yeah I think being able to skip `LoweringGroup` should be fine. scarb doc is only an example of a tool from a class of stuff that do not need deep semantic analysis

___

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6440#-:-O85chPBAFEmwNt9uxrl:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6440)* status: all files reviewed, 2 unresolved discussions (waiting on @wawel37)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 249 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6440#-O86-5nh0b67mLhjiEcs:-O86-5nh0b67mLhjiEct:b-pnxpan) ([raw file](https://github.com/starkware-libs/cairo/blob/41c3e9ff0e0d345e0723c265dd5904ee323c8a4b/crates/cairo-lang-compiler/src/diagnostics.rs#L249)):*
> ```XML
>     /// Ignores all the diagnostics related to LoweringGroup.
>     /// Returns `Err` if diagnostics were found.
>     pub fn ensure_without_lowering_group(
> ```

i don't like this name - or the concept - i think you should just have a configuration of which level of diagnostics you want to get - and just get diagnostics up to that point.
the "without" part is weird.

**Comment by maciektr** [comment]
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 249 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6440#-O86-5nh0b67mLhjiEcs:-O86Juvy8ZU_8lm5gJyO:bgit05d) ([raw file](https://github.com/starkware-libs/cairo/blob/41c3e9ff0e0d345e0723c265dd5904ee323c8a4b/crates/cairo-lang-compiler/src/diagnostics.rs#L249)):*
> i think you should just have a configuration of which level of diagnostics you want to get

Wouldn't we still be forced to add the `LoweringGroup` to the database, just to make type system happy?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6440)* status: all files reviewed, 1 unresolved discussion (waiting on @maciektr)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 249 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6440#-O86-5nh0b67mLhjiEcs:-O86KqGr5aztpUYSHIwa:b-kh0i8z) ([raw file](https://github.com/starkware-libs/cairo/blob/41c3e9ff0e0d345e0723c265dd5904ee323c8a4b/crates/cairo-lang-compiler/src/diagnostics.rs#L249)):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

> i think you should just have a configuration of which level of diagnostics you want to get

Wouldn't we still be forced to add the `LoweringGroup` to the database, just to make type system happy?
</blockquote></details>

no - it is all about the queries you actually call.
if you won't call the lowering-diags queries - they won't be called.

**Review by wawel37 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6440)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 249 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6440#-O86-5nh0b67mLhjiEcs:-O86KWE_0VVtC-c-QZqU:b6hquih) ([raw file](https://github.com/starkware-libs/cairo/blob/41c3e9ff0e0d345e0723c265dd5904ee323c8a4b/crates/cairo-lang-compiler/src/diagnostics.rs#L249)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no - it is all about the queries you actually call.
if you won't call the lowering-diags queries - they won't be called.
</blockquote></details>

But is it a good idea to use the LoweringGroup within the scarb doc, even if we don't need any of the queries from the group? It will be added there just to make diagnostics run with only LoweringGroup (and make it a little bit cleaner code on the diagnostic api side). What do you think?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6440)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @maciektr, @mkaput, and @wawel37)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 249 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6440#-O86-5nh0b67mLhjiEcs:-O86MaB-7s_Eg_t8RLgU:bw8lq1r) ([raw file](https://github.com/starkware-libs/cairo/blob/41c3e9ff0e0d345e0723c265dd5904ee323c8a4b/crates/cairo-lang-compiler/src/diagnostics.rs#L249)):*
<details><summary><i>Previously, wawel37 (Mateusz Kowalski) wrote…</i></summary><blockquote>

But is it a good idea to use the LoweringGroup within the scarb doc, even if we don't need any of the queries from the group? It will be added there just to make diagnostics run with only LoweringGroup (and make it a little bit cleaner code on the diagnostic api side). What do you think?
</blockquote></details>

it is already dependent on it assuming we use the `cairo-lang-compiler` crate - unless it is split it is already dependent.

in general - if you only want top level items `cairo-lang-defs` should be enough. only parser level diagnostics should actually be of any issue to you.

**Comment by maciektr** [comment]
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 249 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6440#-O86-5nh0b67mLhjiEcs:-O86O69kAHCcGSl2WbYm:b-qz9tms) ([raw file](https://github.com/starkware-libs/cairo/blob/41c3e9ff0e0d345e0723c265dd5904ee323c8a4b/crates/cairo-lang-compiler/src/diagnostics.rs#L249)):*
> it is already dependent on it assuming we use the `cairo-lang-compiler` crate

Scarb doc is not doing that. It only relies on queries from `DocGroup` (and dependant groups, up to the semantic one)  - https://github.com/software-mansion/scarb/blob/0366ff08f58e5b554aed840b952cc3f7637347a3/extensions/scarb-doc/src/db.rs#L22-L29

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6440)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @maciektr, @mkaput, and @wawel37)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 249 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6440#-O86-5nh0b67mLhjiEcs:-O86OuNo-G29qxthtFxL:b-4j69py) ([raw file](https://github.com/starkware-libs/cairo/blob/41c3e9ff0e0d345e0723c265dd5904ee323c8a4b/crates/cairo-lang-compiler/src/diagnostics.rs#L249)):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

> it is already dependent on it assuming we use the `cairo-lang-compiler` crate

Scarb doc is not doing that. It only relies on queries from `DocGroup` (and dependant groups, up to the semantic one)  - https://github.com/software-mansion/scarb/blob/0366ff08f58e5b554aed840b952cc3f7637347a3/extensions/scarb-doc/src/db.rs#L22-L29
</blockquote></details>

so you can probably just run it without the `ensure` part - and it would still be fine.
if for some reason it fails - only then call the diagnostics.

everything would be much faster that way (in the good case).

**Comment by maciektr** [comment]
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 249 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6440#-O86-5nh0b67mLhjiEcs:-O86VOOE8L72VuUVzHf8:b-vubjfa) ([raw file](https://github.com/starkware-libs/cairo/blob/41c3e9ff0e0d345e0723c265dd5904ee323c8a4b/crates/cairo-lang-compiler/src/diagnostics.rs#L249)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

so you can probably just run it without the `ensure` part - and it would still be fine.
if for some reason it fails - only then call the diagnostics.

everything would be much faster that way (in the good case).
</blockquote></details>

Hmm, good point! 
By `only then call diagnostics` you still mean with `check` or something else? :thinking:

**Review by wawel37 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6440)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @maciektr, @mkaput, and @orizi)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 249 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6440#-O86-5nh0b67mLhjiEcs:-O86V64p0CQXc1UBkdht:b-fjjjlx) ([raw file](https://github.com/starkware-libs/cairo/blob/41c3e9ff0e0d345e0723c265dd5904ee323c8a4b/crates/cairo-lang-compiler/src/diagnostics.rs#L249)):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

Hmm, good point! 
By `only then call diagnostics` you still mean with `check` or something else? :thinking:
</blockquote></details>

Do you mean we should run queries, and if any of them fails, only then call the `ensure`?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6440)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @maciektr, @mkaput, and @wawel37)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 249 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6440#-O86-5nh0b67mLhjiEcs:-O86a2w-4aMj1EbMGAca:b-1vijnr) ([raw file](https://github.com/starkware-libs/cairo/blob/41c3e9ff0e0d345e0723c265dd5904ee323c8a4b/crates/cairo-lang-compiler/src/diagnostics.rs#L249)):*
<details><summary><i>Previously, wawel37 (Mateusz Kowalski) wrote…</i></summary><blockquote>

Do you mean we should run queries, and if any of them fails, only then call the `ensure`?
</blockquote></details>

Exactly

**Review by mkaput — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6440)* status: all files reviewed, 1 unresolved discussion (waiting on @maciektr and @wawel37)

**Review by wawel37 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6440)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 249 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6440#-O86-5nh0b67mLhjiEcs:-O8B_Ivi-fUVKPpA9TYu:b-9jg4f5) ([raw file](https://github.com/starkware-libs/cairo/blob/41c3e9ff0e0d345e0723c265dd5904ee323c8a4b/crates/cairo-lang-compiler/src/diagnostics.rs#L249)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Exactly
</blockquote></details>

As I tried to make it run only on queries error, i noticed that sometimes queries will run without an error even with wrong code, for example:
```
/// test comment
fn main() {
    println!("Hello world!");
    wrong code
}

```

And if we skip the `ensure` when there aren't any errors from queries, we won't display any errors. Running `cargo doc` with same code results in diagnostics error. I don't think that generating docs with the wrong code is a good idea. Is it guaranteed for queries to be correct after queries haven't thrown any errors but the diagnostics have?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6440)* status: all files reviewed, 1 unresolved discussion (waiting on @maciektr and @wawel37)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 249 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6440#-O86-5nh0b67mLhjiEcs:-O8BbfXd3wggUO7jWciv:bqdmsv1) ([raw file](https://github.com/starkware-libs/cairo/blob/41c3e9ff0e0d345e0723c265dd5904ee323c8a4b/crates/cairo-lang-compiler/src/diagnostics.rs#L249)):*
<details><summary><i>Previously, wawel37 (Mateusz Kowalski) wrote…</i></summary><blockquote>

As I tried to make it run only on queries error, i noticed that sometimes queries will run without an error even with wrong code, for example:
```
/// test comment
fn main() {
    println!("Hello world!");
    wrong code
}

```

And if we skip the `ensure` when there aren't any errors from queries, we won't display any errors. Running `cargo doc` with same code results in diagnostics error. I don't think that generating docs with the wrong code is a good idea. Is it guaranteed for queries to be correct after queries haven't thrown any errors but the diagnostics have?
</blockquote></details>

this is an  inconsistency - either you don't care about diagnostics - and then just get the best result you can - and if you fail - return the diagnostics (that probably caused the issue).
or you care about diagnostics - and you should return all of them.

being under the assumption that someone exporting docs actually compiled their projects sounds ok with me.

**Review by wawel37 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6440)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 249 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6440#-O86-5nh0b67mLhjiEcs:-O8C1pf29JVKJmM-mrR-:b-cgp90d) ([raw file](https://github.com/starkware-libs/cairo/blob/41c3e9ff0e0d345e0723c265dd5904ee323c8a4b/crates/cairo-lang-compiler/src/diagnostics.rs#L249)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is an  inconsistency - either you don't care about diagnostics - and then just get the best result you can - and if you fail - return the diagnostics (that probably caused the issue).
or you care about diagnostics - and you should return all of them.

being under the assumption that someone exporting docs actually compiled their projects sounds ok with me.
</blockquote></details>

Done. Made it configurable on the `DiagnosticsReporter` level.

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6440)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi and @wawel37)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 76 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6440#-O8COZew1sQN0DYL_BCZ:-O8COZew1sQN0DYL_BC_:b-gr8l72) ([raw file](https://github.com/starkware-libs/cairo/blob/79c42fb5643843e6342585b69f5dc40ccbed9e84/crates/cairo-lang-compiler/src/diagnostics.rs#L76)):*
> ```XML
>     pub fn callback(
>         callback: impl FnMut(FormattedDiagnosticEntry) + 'a,
>         include_lowering_diagnostics: bool,
> ```

that's a bad pattern, this standalone `true`/`false` will be very unreadable in code; and also you can't pursue a notion of "default" value

also adding param here is a breaking API change 

You should do a (pseudo-) builder pattern here:

```rs
DiagnosticsReporter::callback(..).skip_lowering_diagnostics()
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6440)* status: all files reviewed, 3 unresolved discussions (waiting on @wawel37)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 191 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6440#-O8DxdDrB7AeeU1YZ-jh:-O8DxdDs16-_JKN_U382:b-2vf320) ([raw file](https://github.com/starkware-libs/cairo/blob/79c42fb5643843e6342585b69f5dc40ccbed9e84/crates/cairo-lang-compiler/src/diagnostics.rs#L191)):*
> ```XML
>                         self.check_diag_group(db.upcast(), group, ignore_warnings_in_crate);
>                 }
>                 if self.include_lowering_diagnostics {
> ```

i think flipping the flag is more sensible.
optionally instead - just make it into a DiagLevel enum - (Syntax, Semantic, Full)



_Suggestion:_
```XML
                if self.skip_lowering_diagnostics {
                    continue;
                }
```

**Review by wawel37 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6440)* status: all files reviewed, 2 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 76 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6440#-O8COZew1sQN0DYL_BCZ:-O8GTzcL5fK34gaEzlb9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/79c42fb5643843e6342585b69f5dc40ccbed9e84/crates/cairo-lang-compiler/src/diagnostics.rs#L76)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

that's a bad pattern, this standalone `true`/`false` will be very unreadable in code; and also you can't pursue a notion of "default" value

also adding param here is a breaking API change 

You should do a (pseudo-) builder pattern here:

```rs
DiagnosticsReporter::callback(..).skip_lowering_diagnostics()
```
</blockquote></details>

Done.
___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 191 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6440#-O8DxdDrB7AeeU1YZ-jh:-O8GTj5J8pk2MQ-pkhzd:bhi53uq) ([raw file](https://github.com/starkware-libs/cairo/blob/79c42fb5643843e6342585b69f5dc40ccbed9e84/crates/cairo-lang-compiler/src/diagnostics.rs#L191)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i think flipping the flag is more sensible.
optionally instead - just make it into a DiagLevel enum - (Syntax, Semantic, Full)
</blockquote></details>

Done. Will leave only the skip for lowering group for now, because no one will use another levels right now.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6440#-:-O8H2R6t0FQhMW5PQPwj:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)

**Review by mkaput — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6440)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wawel37)

**Pull request merged**
