### PR TITLE
add verify_signature function for secp curves

### PR DESCRIPTION
**Pull request by ArielElp**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4120)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/starknet/secp256_trait.cairo` line 83 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4120#-Nh0PbjIDNi48RQB9534:-Nh0PbjIDNi48RQB9535:b-h89qzv) ([raw file](https://github.com/starkware-libs/cairo/blob/1ab92eb722fafa24691c6c18c1506e7ca2dee49b/corelib/src/starknet/secp256_trait.cairo#L83)):*
> ```Cairo
> 
>     let (x, y) = sum.get_coordinates().unwrap_syscall();
>     return Result::Ok(x == r);
> ```

I find this a bit strange.

why not
Result::Err('Invalid signature')

also, no need to `return` here



_Suggestion:_
```Cairo
Result::Ok(x == r);
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4120)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @ArielElp and @orizi)

___
*[`corelib/src/starknet/secp256r1.cairo` line 44 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4120#-Nh0Q4To0PfYR9qBbOQ3:-Nh0Q4TpEYiRL5O223WA:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/1ab92eb722fafa24691c6c18c1506e7ca2dee49b/corelib/src/starknet/secp256r1.cairo#L44)):*
> ```Cairo
>         } else {
>             return secp256r1_get_point_from_x_syscall(x, true);
>         }
> ```





_Suggestion:_
```Cairo
secp256_ec_new_syscall(x, y)
```

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4120)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`corelib/src/starknet/secp256_trait.cairo` line 83 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4120#-Nh0PbjIDNi48RQB9534:-Nh5XaPJ7M9Jkh3UZxKa:buxu9yj) ([raw file](https://github.com/starkware-libs/cairo/blob/1ab92eb722fafa24691c6c18c1506e7ca2dee49b/corelib/src/starknet/secp256_trait.cairo#L83)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I find this a bit strange.

why not
Result::Err('Invalid signature')

also, no need to `return` here
</blockquote></details>

renamed to is_valid_signature, now returns bool
___
*[`corelib/src/starknet/secp256r1.cairo` line 44 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4120#-Nh0Q4To0PfYR9qBbOQ3:-Nh5WyrH5jsr1_tvhq4q:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1ab92eb722fafa24691c6c18c1506e7ca2dee49b/corelib/src/starknet/secp256r1.cairo#L44)):*
> ```Cairo
>         } else {
>             return secp256r1_get_point_from_x_syscall(x, true);
>         }
> ```

Done.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4120)* status: all files reviewed, 3 unresolved discussions (waiting on @ArielElp and @orizi)

___
*[`corelib/src/starknet/secp256k1.cairo` line 82 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4120#-Nh6GhV216LCrJiMnd9K:-Nh6GhV33HYUrIoINGMu:by2dvbi) ([raw file](https://github.com/starkware-libs/cairo/blob/e1ad2588b5147c6a8092bc59bdb86a60c24ad135/corelib/src/starknet/secp256k1.cairo#L82)):*
> ```Cairo
> ) -> SyscallResult<(u256, u256)> implicits(GasBuiltin, System) nopanic;
> 
> /// Asserts that a Secp256 ECDSA signature is valid.
> ```

Fix the comment.



_Code quote:_
```Cairo
// Asserts that a Secp256 ECDSA signature is valid.
```
___
*[`corelib/src/starknet/secp256k1.cairo` line 92 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4120#-Nh6GxGs5-N1gDIeWiKx:-Nh6GxGs5-N1gDIeWiKy:b2ni2nk) ([raw file](https://github.com/starkware-libs/cairo/blob/e1ad2588b5147c6a8092bc59bdb86a60c24ad135/corelib/src/starknet/secp256k1.cairo#L92)):*
> ```Cairo
> }
> 
> /// Checks a Secp256 ECDSA signature.
> ```

fix



_Code quote:_
```Cairo
 Checks a Secp256 ECDSA signature.
```
___
*[`corelib/src/starknet/secp256k1.cairo` line 96 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4120#-Nh6Gz0zEj9cPUFEk41i:-Nh6Gz0zEj9cPUFEk41j:bp6wrlv) ([raw file](https://github.com/starkware-libs/cairo/blob/e1ad2588b5147c6a8092bc59bdb86a60c24ad135/corelib/src/starknet/secp256k1.cairo#L96)):*
> ```Cairo
> /// where N is the size of the curve.
> /// Returns a Result with an error string if the signature is invalid.
> fn is_eth_signature_valid(
> ```

consider moving the etherium related logic to eth.cairo.



_Code quote:_
```Cairo
is_eth_signature_valid
```

**Review by ArielElp — COMMENTED** [review]
> Reviewed 1 of 5 files at r2, 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4120)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`corelib/src/starknet/secp256k1.cairo` line 82 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4120#-Nh6GhV216LCrJiMnd9K:-NhBCBvt2BZoqRlpXU8g:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e1ad2588b5147c6a8092bc59bdb86a60c24ad135/corelib/src/starknet/secp256k1.cairo#L82)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Fix the comment.
</blockquote></details>

Done.
___
*[`corelib/src/starknet/secp256k1.cairo` line 92 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4120#-Nh6GxGs5-N1gDIeWiKx:-NhBCTDCBwJeohuMZ9AD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e1ad2588b5147c6a8092bc59bdb86a60c24ad135/corelib/src/starknet/secp256k1.cairo#L92)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

fix
</blockquote></details>

Done.
___
*[`corelib/src/starknet/secp256k1.cairo` line 96 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4120#-Nh6Gz0zEj9cPUFEk41i:-NhBGsBP2X66M-7OxZBB:bdlrg84) ([raw file](https://github.com/starkware-libs/cairo/blob/e1ad2588b5147c6a8092bc59bdb86a60c24ad135/corelib/src/starknet/secp256k1.cairo#L96)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

consider moving the etherium related logic to eth.cairo.
</blockquote></details>

Moved to ethereum_signature.cairo (ideally we'd have eth.cairo with both address and signature but I don't want to move eth address as well, so IMO it's good enough)

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4120#-:-NhLVt3r9b4I9yMExOBE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
