### PR TITLE
Add build_storage_address_const.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1293)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1293#-:-NJ0VxLD1TazYh0WsYj-:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/sierra_to_casm/src/invocations/starknet/mod.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1293#-NJ0VRTpEaLWHr25jqcy:-NJ0VRTqDzCC32QnwEVS:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/d500286e54be370e7b607a1145b12a57ea385d69/crates/sierra_to_casm/src/invocations/starknet/mod.rs#L27)):*
> ```XML
> }
> 
> fn build_storage_address_const(
> ```

doc



_Code quote:_
```XML
 build_storage_address_const
```
___
*[`crates/sierra_to_casm/src/invocations/starknet/mod.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1293#-NJ0VgFdAFRCk2n7gyKT:-NJ0VgFdAFRCk2n7gyKU:bufee46) ([raw file](https://github.com/starkware-libs/cairo/blob/d500286e54be370e7b607a1145b12a57ea385d69/crates/sierra_to_casm/src/invocations/starknet/mod.rs#L31)):*
> ```XML
>     libfunc: &StorageAddressConstConcreteLibFunc,
> ) -> Result<CompiledInvocation, InvocationError> {
>     // 2 ** 251 - 256;
> ```

if works:



_Suggestion:_
```XML
    let addr_bound = (BigInt::from(1) << 251) - 256;
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1293)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/sierra_to_casm/src/invocations/starknet/mod.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1293#-NJ0VgFdAFRCk2n7gyKT:-NJ0WiUbEVa_mf89gH57:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d500286e54be370e7b607a1145b12a57ea385d69/crates/sierra_to_casm/src/invocations/starknet/mod.rs#L31)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

if works:
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1293)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/sierra_to_casm/src/invocations/starknet/mod.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1293#-NJ0VRTpEaLWHr25jqcy:-NJ0X9du8HN3J6lSgEHl:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d500286e54be370e7b607a1145b12a57ea385d69/crates/sierra_to_casm/src/invocations/starknet/mod.rs#L27)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1293)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1293)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
