### PR TITLE
Feat/ Adding support for cloning array

### PR DESCRIPTION
**Pull request by gaetbout**
Until there is support for generic impl, at least here it is. the support for felt and array of felt copy

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2328)

### CODE REVIEW

**Comment by gaetbout** [comment]
Stuck with:
```
error: Trait has no implementation in context: core::clone::CloneTrait::<T>
 --> clone.cairo:18:9
        clone_loop(self.span(), ref response);
```
:(

**Comment by gaetbout** [comment]
@spapinistarkware 
Would you know what I should impl to make the first clone more generic:
```
impl FeltCloneImpl of CloneTrait::<felt> {
    fn clone(self: @felt) -> felt {
        *self
    }
}
```

Also regarding the ArrayImpl I'm facing another issue:
```
error: Trait has no implementation in context: core::clone::CloneTrait::<T>
 --> clone.cairo:18:9
        clone_loop(self.span(), ref response);
```
Would you have any idea?
Thanks in advance

**Comment by spapinistarkware** [comment]
You can impl it for every copyable thing:

impl ImplCopyClone<T, impl TCopy: Copy::<T>> {...}

As for the second issue, you probably need to add the generic param "impl TClone: Clone::<T>"

Also, maybe rename CloneTrait to Clone

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2328)* status: all files reviewed, 1 unresolved discussion (waiting on @gaetbout)

___
*[`corelib/src/clone.cairo` line 5 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2328#-NQFOWFO-lBI3wAIS26k:-NQFOWFO-lBI3wAIS26l:bewecdx) ([raw file](https://github.com/starkware-libs/cairo/blob/b6332f2736ef145fb2027fabfc50de9ef6121209/corelib/src/clone.cairo#L5)):*
> ```Cairo
> use gas::get_gas;
> 
> trait CloneTrait<T> {
> ```

Rename to Clone

**Review by spapinistarkware — COMMENTED** [review]
Hmm, I see you did that. I'll check the inference thing, but for now, you can pass the impl explicitly when calling clone_loop

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2328#-:-NQFP_0J3qC3V7I8hVc3:bbj8x9k)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @gaetbout)

**Comment by Philonoist** [comment]
Mind applying this fix?
```
```
--- a/crates/cairo-lang-semantic/src/items/function_with_body.rs
+++ b/crates/cairo-lang-semantic/src/items/function_with_body.rs
@@ -73,7 +73,9 @@ pub fn function_with_body_generic_params(
             db.free_function_generic_params(free_function_id)
         }
         FunctionWithBodyId::Impl(impl_function_id) => {
-            db.impl_function_generic_params(impl_function_id)
+            let mut res = db.impl_def_generic_params(impl_function_id.impl_def_id(db.upcast()))?;
+            res.extend(db.impl_function_generic_params(impl_function_id)?);
+            Ok(res)
         }
     }
 }

**Comment by Philonoist** [comment]
Next diff:
```
--- a/crates/cairo-lang-semantic/src/items/imp.rs
+++ b/crates/cairo-lang-semantic/src/items/imp.rs
@@ -1057,6 +1057,9 @@ pub fn priv_impl_function_body_data(
     // Compute declaration semantic.
     let declaration = db.priv_impl_function_declaration_data(impl_function_id)?;
     let mut resolver = Resolver::new_with_inference(db, module_file_id);
+    for generic_param in db.impl_def_generic_params(impl_def_id)? {
+        resolver.add_generic_param(generic_param);
+    }
     for generic_param in declaration.function_declaration_data.generic_params {
         resolver.add_generic_param(generic_param);
     }

```

**Pull request closed without merging**
