### PR TITLE
Added BitNot operation.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3021)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3021)* status: 5 of 14 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-parser/src/lexer.rs` line 376 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3021#-NUWB5ZjAQyVX7n1I7L5:-NUWB5ZjAQyVX7n1I7L6:b-ekm59t) ([raw file](https://github.com/starkware-libs/cairo/blob/f8dd784de7d49a156c00678c222280b54580361a/crates/cairo-lang-parser/src/lexer.rs#L376)):*
> ```XML
>     LT,
>     Not,
>     Tilde,
> ```

Our token are not named bang, dash, etc... They are baned Not, Minus, after the math operation. If we wanna be consistent, this should be BitNot or BitwiseNot.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 9 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3021#-:-NUWBSSmExxg6WGusyjb:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3021)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-parser/src/lexer.rs` line 376 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3021#-NUWB5ZjAQyVX7n1I7L5:-NUWCqWV3jEmn6R6BiM-:bs26url) ([raw file](https://github.com/starkware-libs/cairo/blob/f8dd784de7d49a156c00678c222280b54580361a/crates/cairo-lang-parser/src/lexer.rs#L376)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Our token are not named bang, dash, etc... They are baned Not, Minus, after the math operation. If we wanna be consistent, this should be BitNot or BitwiseNot.
</blockquote></details>

i'm not really sure what is better in this case - do you really think `BitNot` is clearer?

**Comment by spapinistarkware** [comment]
> > _[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3021)_ status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)
> 
> _[`crates/cairo-lang-parser/src/lexer.rs` line 376 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3021#-NUWB5ZjAQyVX7n1I7L5:-NUWCqWV3jEmn6R6BiM-:bs26url) ([raw file](https://github.com/starkware-libs/cairo/blob/f8dd784de7d49a156c00678c222280b54580361a/crates/cairo-lang-parser/src/lexer.rs#L376)):_
> 
> Previously, spapinistarkware (Shahar Papini) wrote…
> i'm not really sure what is better in this case - do you really think `BitNot` is clearer?

I dunno, but I'd rather be consistent

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3021)* status: 4 of 14 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-parser/src/lexer.rs` line 376 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3021#-NUWB5ZjAQyVX7n1I7L5:-NUWGdVf6NzQNZqIwxX6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f8dd784de7d49a156c00678c222280b54580361a/crates/cairo-lang-parser/src/lexer.rs#L376)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I dunno, but I'd rather be consistent 
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3021)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
