### PR TITLE
Fix dispatcher.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1903)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1903)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin_test_data/dispatcher` line 33 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1903#-NMdCM1BDvruAeb3bWmu:-NMdCM1CExwPR5jIxY7g:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2e0b8637c68d51887f881ab17b4cf7cf490e07a4/crates/cairo-lang-starknet/src/plugin_test_data/dispatcher#L33)):*
> ```
> mod IContractDispatcher {
>     use starknet::SyscallResultTrait;
>     use starknet::SyscallResultTraitImpl;
> ```





_Suggestion:_
```
    use starknet::SyscallResultTrait;
    use starknet::SyscallResultTraitImpl;
    use result::ResultTrait;
    use result::ResultTraitImpl;

        fn get_something(contract_address: ContractAddress, arg: felt, num: felt) -> felt {
        let mut calldata = array_new();
        serde::Serde::<felt>::serialize(ref calldata, arg);
        serde::Serde::<felt>::serialize(ref calldata, num);

        let mut ret_data = starknet::call_contract_syscall(
            contract_address,
            calldata,
        ).unwrap_syscall();

        serde::Serde::<felt>::deserialize(ref ret_data).expect('Returned data too short');
    }
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/plugin_test_data/dispatcher` line 33 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1903#-NMdCM1BDvruAeb3bWmu:-NMdNRBe7gHUdScMZITG:brgrkzc) ([raw file](https://github.com/starkware-libs/cairo/blob/2e0b8637c68d51887f881ab17b4cf7cf490e07a4/crates/cairo-lang-starknet/src/plugin_test_data/dispatcher#L33)):*
> ```
> mod IContractDispatcher {
>     use starknet::SyscallResultTrait;
>     use starknet::SyscallResultTraitImpl;
> ```

deserialize returns option, not result.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1903)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin_test_data/dispatcher` line 33 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1903#-NMdCM1BDvruAeb3bWmu:-NMdOA1U8nrrC5myIBgW:bxnd5k9) ([raw file](https://github.com/starkware-libs/cairo/blob/2e0b8637c68d51887f881ab17b4cf7cf490e07a4/crates/cairo-lang-starknet/src/plugin_test_data/dispatcher#L33)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

deserialize returns option, not result.
</blockquote></details>

so option::OptionTrait{Impl,} instead

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1903)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin_test_data/dispatcher` line 33 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1903#-NMdCM1BDvruAeb3bWmu:-NMdP5gf9m8DpbUV9GB7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2e0b8637c68d51887f881ab17b4cf7cf490e07a4/crates/cairo-lang-starknet/src/plugin_test_data/dispatcher#L33)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

so option::OptionTrait{Impl,} instead
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1903#-:-NMdP_51-BDe9EXvJJVa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
