### PR TITLE
Avoid adding zero sized variables to stack.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4276)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 34 of 34 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4276)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/stack_tracking` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4276#-Nh2jOoi0TUj7KW-oMjd:-Nh2jOoi0TUj7KW-oMje:brd3ycy) ([raw file](https://github.com/starkware-libs/cairo/blob/95f01872c56b09979a7d713133d2db4eb727eb07/crates/cairo-lang-sierra-generator/src/function_generator_test_data/stack_tracking#L36)):*
> ```
> store_temp<u32>([2]) -> ([2])
> function_call<user@test::test_func>([1], [2]) -> ([3])
> store_temp<Unit>([3]) -> ([3])
> ```

why is this added now?
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler_test.rs` line 416 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4276#-Nh2jlMc4rpkyXgpcjet:-Nh2jlMc4rpkyXgpcjeu:b95wj3) ([raw file](https://github.com/starkware-libs/cairo/blob/95f01872c56b09979a7d713133d2db4eb727eb07/crates/cairo-lang-sierra-to-casm/src/compiler_test.rs#L416)):*
> ```XML
> 
>             struct_construct<Unit>() -> ([33]); // 10
>             felt252_const<1>() -> ([1]); // 12
> ```

line number are wrong here.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4276)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/stack_tracking` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4276#-Nh2jOoi0TUj7KW-oMjd:-Nh2xMQ-0f1PU8OOHOQV:bmy8tor) ([raw file](https://github.com/starkware-libs/cairo/blob/95f01872c56b09979a7d713133d2db4eb727eb07/crates/cairo-lang-sierra-generator/src/function_generator_test_data/stack_tracking#L36)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why is this added now?
</blockquote></details>

Because it is returned as deferred so it need to pushed. the next PR is going to remove it.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4276)* status: 33 of 34 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler_test.rs` line 416 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4276#-Nh2jlMc4rpkyXgpcjet:-Nh2yuv23lKbOEhsXzE9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/95f01872c56b09979a7d713133d2db4eb727eb07/crates/cairo-lang-sierra-to-casm/src/compiler_test.rs#L416)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

line number are wrong here.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4276)* status: 33 of 34 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/function_call.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4276#-Nh3-6gR-pC-oLx8fZB7:-Nh3-6gR-pC-oLx8fZB8:bjd8vh0) ([raw file](https://github.com/starkware-libs/cairo/blob/b3859c0004b8e4abdfff57f80416c30c45671692/crates/cairo-lang-sierra/src/extensions/modules/function_call.rs#L33)):*
> ```XML
>                             Ok(OutputVarInfo {
>                                 ty: ty.clone(),
>                                 ref_info: if context.get_type_info(ty.clone())?.zero_sized {
> ```

Do we want to make this change only for Sierra 1.4?



_Code quote:_
```XML
ref_info: if context.get_type_info(ty.clone())?.zero_sized {
```

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4276)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/function_call.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4276#-Nh3-6gR-pC-oLx8fZB7:-Nh3-s-T8GfAndr1ZrdU:b9gfph) ([raw file](https://github.com/starkware-libs/cairo/blob/b3859c0004b8e4abdfff57f80416c30c45671692/crates/cairo-lang-sierra/src/extensions/modules/function_call.rs#L33)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Do we want to make this change only for Sierra 1.4?
</blockquote></details>

It is fine, if since this only has sierra gen implications.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra/src/extensions/modules/function_call.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4276#-Nh3-6gR-pC-oLx8fZB7:-Nh30jmGATeznESzaGdi:bxz3eub) ([raw file](https://github.com/starkware-libs/cairo/blob/b3859c0004b8e4abdfff57f80416c30c45671692/crates/cairo-lang-sierra/src/extensions/modules/function_call.rs#L33)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

It is fine, if since this only has sierra gen implications.
</blockquote></details>

It also effect sierra_to_casm, but as far as I can tell it is more relaxed with this change rather then more strict.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra/src/extensions/modules/function_call.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4276#-Nh3-6gR-pC-oLx8fZB7:-Nh3284M1CYewwr4jasX:b-mx02hm) ([raw file](https://github.com/starkware-libs/cairo/blob/b3859c0004b8e4abdfff57f80416c30c45671692/crates/cairo-lang-sierra/src/extensions/modules/function_call.rs#L33)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

It also effect sierra_to_casm, but as far as I can tell it is more relaxed with this change rather then more strict.
</blockquote></details>

https://github.com/starkware-libs/cairo/blob/0a3e9dec15c2a853559d233247a253871e7bb35a/crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs#L209

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4276)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/function_call.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4276#-Nh3-6gR-pC-oLx8fZB7:-Nh37zg-4xocPhG3T2xQ:bxelwy1) ([raw file](https://github.com/starkware-libs/cairo/blob/b3859c0004b8e4abdfff57f80416c30c45671692/crates/cairo-lang-sierra/src/extensions/modules/function_call.rs#L33)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Wasn't it that the only usage for the types here is in sierra generator?
</blockquote></details>

No, I was wrong.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4276)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/function_call.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4276#-Nh3-6gR-pC-oLx8fZB7:-Nh385Cx80MC1psFczSg:b-g2rt11) ([raw file](https://github.com/starkware-libs/cairo/blob/b3859c0004b8e4abdfff57f80416c30c45671692/crates/cairo-lang-sierra/src/extensions/modules/function_call.rs#L33)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

No, I was wrong.
</blockquote></details>

It was the case at some point, but apparently, it changed.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4276)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/function_call.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4276#-Nh3-6gR-pC-oLx8fZB7:-Nh4qklq0RVbuGZG7YEw:b-o4px4s) ([raw file](https://github.com/starkware-libs/cairo/blob/b3859c0004b8e4abdfff57f80416c30c45671692/crates/cairo-lang-sierra/src/extensions/modules/function_call.rs#L33)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

It was the case at some point, but apparently, it changed.
</blockquote></details>

so this *can* be merged only into `sierra-minor-update`.
consider solutions that still store the unit types to avoid the need for further audit.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4276)* status: 14 of 35 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/function_call.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4276#-Nh3-6gR-pC-oLx8fZB7:-NhM_RAOBM4hB5FTly5U:b-e8i38e) ([raw file](https://github.com/starkware-libs/cairo/blob/b3859c0004b8e4abdfff57f80416c30c45671692/crates/cairo-lang-sierra/src/extensions/modules/function_call.rs#L33)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

so this *can* be merged only into `sierra-minor-update`.
consider solutions that still store the unit types to avoid the need for further audit.
</blockquote></details>

Moved to `sierra-minor-update`.

Not sure about the other solution.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 21 of 21 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4276)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/function_call.rs` line 39 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4276#-NhMhBWo0JX3V_lvXvPC:-NhMhBWo0JX3V_lvXvPD:b-lnon2c) ([raw file](https://github.com/starkware-libs/cairo/blob/d531d013cb827820866bb42f93b940701091a6ab/crates/cairo-lang-sierra/src/extensions/modules/function_call.rs#L39)):*
> ```XML
>                                     OutputVarReferenceInfo::NewTempVar { idx: stack_idx - 1 }
>                                 },
>                             })
> ```

consider:



_Suggestion:_
```XML
        let mut curr_stack_idx = 0;
        let mut get_stack_idx = || {
            let idx = curr_stack_idx;
            curr_stack_idx += 1;
            curr_stack_idx
        };
        match args {
            [GenericArg::UserFunc(function_id)] => {
                let signature = context.get_function_signature(function_id)?;
                let ap_change = context.get_function_ap_change(function_id)?;
                Ok(LibfuncSignature::new_non_branch(
                    signature.param_types.clone(),
                    signature
                        .ret_types
                        .iter()
                        .map(|ty| {
                            Ok(OutputVarInfo {
                                ty: ty.clone(),
                                ref_info: if context.get_type_info(ty.clone())?.zero_sized {
                                    OutputVarReferenceInfo::SimpleDerefs
                                } else {
                                    OutputVarReferenceInfo::NewTempVar { idx: get_stack_idx() }
                                },
                            })
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/mem.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4276#-NhMh_33E7P9D3GVTNoO:-NhMh_34CyKx_tgD1RxR:b-fy4nbl) ([raw file](https://github.com/starkware-libs/cairo/blob/d531d013cb827820866bb42f93b940701091a6ab/crates/cairo-lang-sierra/src/extensions/modules/mem.rs#L51)):*
> ```XML
>                 ty,
>                 ref_info: if type_info.zero_sized {
>                     OutputVarReferenceInfo::SimpleDerefs
> ```

How about `Unit` on this side as well?

**Pull request closed without merging**
