### PR TITLE
Some internal audit fixes.

### PR DESCRIPTION
**Pull request by liorgold2**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3847)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3847)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs` line 269 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3847#-NbDp5pjAYZ6dGMPxgdN:-NbDp5pjAYZ6dGMPxgdO:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/34ea6da2c0773ed45042ebcba2210317e7482864/crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs#L269)):*
> ```XML
> /// Builds a libfunc that tries to convert a felt252 to type with values in the range
> /// `[0, 2**num_bits)`.
> /// Assumption: num_bits > 128.
> ```





_Suggestion:_
```XML
/// Builds a libfunc that tries to convert a felt252 to type with values in the range
/// `[0, 2**num_bits)`.
/// Assumption: num_bits <= 128.
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/signed.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3847#-NbDpFlUCAKbFcZ60QK8:-NbDpFlV8iLxoMxpD279:bum2rmh) ([raw file](https://github.com/starkware-libs/cairo/blob/34ea6da2c0773ed45042ebcba2210317e7482864/crates/cairo-lang-sierra-to-casm/src/invocations/int/signed.rs#L99)):*
> ```XML
>     ] = builder.invocation.branches.as_slice()
>     else {
>         // TODO(orizi): this should be an error instead of panic.
> ```

why? this would be much more difficult to debug if a failure returned.
a failure should already occur in the signature checking stage.



_Code quote:_
```XML
        // TODO(orizi): this should be an error instead of panic.
```

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3847)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3847)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs` line 269 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3847#-NbDp5pjAYZ6dGMPxgdN:-NbJB5tR7dc1iAuULUS0:bu03fk2) ([raw file](https://github.com/starkware-libs/cairo/blob/34ea6da2c0773ed45042ebcba2210317e7482864/crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs#L269)):*
> ```XML
> /// Builds a libfunc that tries to convert a felt252 to type with values in the range
> /// `[0, 2**num_bits)`.
> /// Assumption: num_bits > 128.
> ```

Actually, this works only for `> 128`.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/signed.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3847#-NbDpFlUCAKbFcZ60QK8:-NbJBZx_2-1dRfJ1JP2-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/34ea6da2c0773ed45042ebcba2210317e7482864/crates/cairo-lang-sierra-to-casm/src/invocations/int/signed.rs#L99)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why? this would be much more difficult to debug if a failure returned.
a failure should already occur in the signature checking stage.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3847#-:-NbJBnLW6yv5P6hFx6Ki:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

**Pull request merged**
