### PR TITLE
Make deref lookup stop early if member is found.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
**Stack**:
- #5830
- #5841
- #5834 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5834)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5834)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1544 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5834#-O-oKD4L1-_Ku4dY3qxP:-O-oKD4M79--W6O5vnh3:b-l6hdjr) ([raw file](https://github.com/starkware-libs/cairo/blob/42a4384f8e2a76dc47833cd5d2f44f09e70c2405/crates/cairo-lang-semantic/src/expr/compute.rs#L1544)):*
> ```XML
>             .unwrap_or_else(skip_diagnostic));
>             eprintln!("Diagnostic: {}", ctx.diagnostics.clone().build().format(ctx.db.elongate()));
>             return x;
> ```

revert



_Code quote:_
```XML
            eprintln!(
                "No implementation of function: {:?} for type {:?}",
                func_name,
                self_ty.debug(ctx.db.elongate())
            );
            let x = Err(no_implementation_diagnostic(
                self_ty,
                func_name,
                TraitInferenceErrors { traits_and_errors: inference_errors },
            )
            .map(|diag| ctx.diagnostics.report(method_syntax, diag))
            .unwrap_or_else(skip_diagnostic));
            eprintln!("Diagnostic: {}", ctx.diagnostics.clone().build().format(ctx.db.elongate()));
            return x;
```
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2491 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5834#-O-oKKaC5Rz44dl8Hi-U:-O-oKKaC5Rz44dl8Hi-V:b-3jvjmb) ([raw file](https://github.com/starkware-libs/cairo/blob/42a4384f8e2a76dc47833cd5d2f44f09e70c2405/crates/cairo-lang-semantic/src/expr/compute.rs#L2491)):*
> ```XML
>     mut expr: ExprAndId,
>     stable_ptr: ast::ExprPtr,
>     accessed_member_name: Option<SmolStr>,
> ```

why option?



_Code quote:_
```XML
    accessed_member_name: Option<SmolStr>,
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5834)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1544 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5834#-O-oKD4L1-_Ku4dY3qxP:-O-ohXJT7061CNoKMW4g:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/42a4384f8e2a76dc47833cd5d2f44f09e70c2405/crates/cairo-lang-semantic/src/expr/compute.rs#L1544)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

revert
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2491 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5834#-O-oKKaC5Rz44dl8Hi-U:-O-oWDr1D8XFDbFHDdyG:b18xm8f) ([raw file](https://github.com/starkware-libs/cairo/blob/42a4384f8e2a76dc47833cd5d2f44f09e70c2405/crates/cairo-lang-semantic/src/expr/compute.rs#L2491)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why option?
</blockquote></details>

For when it'll be used in the language server, i can make it not optional for now.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5834)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2491 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5834#-O-oKKaC5Rz44dl8Hi-U:-O-ol3EQE3sJg8n-25dA:b7fpnjw) ([raw file](https://github.com/starkware-libs/cairo/blob/42a4384f8e2a76dc47833cd5d2f44f09e70c2405/crates/cairo-lang-semantic/src/expr/compute.rs#L2491)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

For when it'll be used in the language server, i can make it not optional for now.
</blockquote></details>

so doc it.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5834)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2491 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5834#-O-oKKaC5Rz44dl8Hi-U:-O-q4OHk5LKYRMk5sQEc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/42a4384f8e2a76dc47833cd5d2f44f09e70c2405/crates/cairo-lang-semantic/src/expr/compute.rs#L2491)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

so doc it.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5834#-:-O-q55xIDbJXIFYCRDTt:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
