### PR TITLE
Added proper jump and branch alignment validations.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #4622 ⬅
- #4596

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4622)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra/src/program_registry.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4622#-NmPu34B5JN2QE86m6ne:-NmPu34B5JN2QE86m6nf:bsukev3) ([raw file](https://github.com/starkware-libs/cairo/blob/4b5cb367de98851be213adc2598e933b8c502203/crates/cairo-lang-sierra/src/program_registry.rs#L213)):*
> ```XML
>                             dst: next,
>                         }));
>                     }
> ```

Why is that a problem?



_Code quote:_
```XML
                    if next.0 < i {
                        return Err(Box::new(ProgramRegistryError::BranchBackwards {
                            src: curr,
                            dst: next,
                        }));
                    }
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4622)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/program_registry.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4622#-NmPu34B5JN2QE86m6ne:-NmPwu8B5k5Rx3Fh-SPS:b-nci6ug) ([raw file](https://github.com/starkware-libs/cairo/blob/4b5cb367de98851be213adc2598e933b8c502203/crates/cairo-lang-sierra/src/program_registry.rs#L213)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why is that a problem?
</blockquote></details>

sierra-to-casm relies on it implicitly, so this makes it explicit here.
Backwards branches (not including non-conditional branches) means a statement can be introduced not through a followthrough or a function entry point.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4622)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/program_registry.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4622#-NmQ9yrICB5jko0rdrUO:-NmQ9yrICB5jko0rdrUP:b-glxpv0) ([raw file](https://github.com/starkware-libs/cairo/blob/4b5cb367de98851be213adc2598e933b8c502203/crates/cairo-lang-sierra/src/program_registry.rs#L155)):*
> ```XML
>             }
>         }
>         let mut branches = HashMap::<StatementIdx, StatementIdx>::default();
> ```

What is this mapping?



_Code quote:_
```XML
 let mut branches = HashMap::<StatementIdx, StatementIdx>::default();
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4622)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/program_registry.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4622#-NmQ9yrICB5jko0rdrUO:-NmQIS4mBmNX3DhlIWlo:bj5xgpn) ([raw file](https://github.com/starkware-libs/cairo/blob/4b5cb367de98851be213adc2598e933b8c502203/crates/cairo-lang-sierra/src/program_registry.rs#L155)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

What is this mapping?
</blockquote></details>

added doc.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra/src/program_registry.rs` line 156 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4622#-NmQw8vA2VTSw99OXxYp:-NmQw8vA2VTSw99OXxYq:b-vwi6l9) ([raw file](https://github.com/starkware-libs/cairo/blob/70823baa8d9891ccee11351d1893f49843f02cbd/crates/cairo-lang-sierra/src/program_registry.rs#L156)):*
> ```XML
>         }
>         // A branches map, mapping from a destination statement to the statement that jumps to it.
>         // Assuming branches into branch alignments only, this should be a bijection.
> ```

is jump a branch or not in this context?



_Code quote:_
```XML
 // Assuming branches into branch alignments only, this should be a bijection.
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4622)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/program_registry.rs` line 156 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4622#-NmQw8vA2VTSw99OXxYp:-NmR5r3b2546FzJdxGdu:bmlnfmo) ([raw file](https://github.com/starkware-libs/cairo/blob/70823baa8d9891ccee11351d1893f49843f02cbd/crates/cairo-lang-sierra/src/program_registry.rs#L156)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

is jump a branch or not in this context?
</blockquote></details>

jump does not jump into branch align - so no.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra/src/program_registry.rs` line 209 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4622#-NmR7G-i4pNsVAk6pm-I:-NmR7G-i4pNsVAk6pm-J:b-jlkbbd) ([raw file](https://github.com/starkware-libs/cairo/blob/50a18d06d31c95c20567882d91c1a0532c26abbe/crates/cairo-lang-sierra/src/program_registry.rs#L209)):*
> ```XML
>             if !matches!(libfunc_branch.ap_change, SierraApChange::BranchAlign) {
>                 if let Some(prev) = branches.get(&index) {
>                     return Err(Box::new(ProgramRegistryError::BranchNotToBranchAlign {
> ```

This does not have to be a branch according to the definition above, right?



_Code quote:_
```XML
BranchNotToBranchAlign
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra/src/program_registry.rs` line 156 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4622#-NmR7a8_9hEDIU9-qvcG:-NmR7a8_9hEDIU9-qvcH:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/50a18d06d31c95c20567882d91c1a0532c26abbe/crates/cairo-lang-sierra/src/program_registry.rs#L156)):*
> ```XML
>             }
>         }
>         // A branches map, mapping from a destination statement to the statement that jumps to it.
> ```





_Suggestion:_
```XML
   // A branch map, mapping from a statement with multiple branch destination to branchAlign
   // statement.
   // A branchAlign statement may be reachable from at most 1 statement.
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4622)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/program_registry.rs` line 156 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4622#-NmR7a8_9hEDIU9-qvcG:-NmRRe9r3iNoDmfEdMkQ:b8yb0ul) ([raw file](https://github.com/starkware-libs/cairo/blob/50a18d06d31c95c20567882d91c1a0532c26abbe/crates/cairo-lang-sierra/src/program_registry.rs#L156)):*
> ```XML
>             }
>         }
>         // A branches map, mapping from a destination statement to the statement that jumps to it.
> ```

this is a bit incorrect - but will try to update a bit.
___
*[`crates/cairo-lang-sierra/src/program_registry.rs` line 209 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4622#-NmR7G-i4pNsVAk6pm-I:-NmRRjmf0qpeITOKkpky:b-1w8a5a) ([raw file](https://github.com/starkware-libs/cairo/blob/50a18d06d31c95c20567882d91c1a0532c26abbe/crates/cairo-lang-sierra/src/program_registry.rs#L209)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

This does not have to be a branch according to the definition above, right?
</blockquote></details>

anything pointed to must be a branch align.
so if we find anything in this map it is a jump to non-branch align.

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4622)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4622#-:-NmV0MgZ9y8krDrIckoe:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
