### PR TITLE
Support underscore in generic arguments.

### PR DESCRIPTION
**Pull request by liorgold2**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2444)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2444)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-semantic/src/resolve_path.rs` line 782 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2444#-NQFS7uZC4srgVOvUTti:-NQFS7uZC4srgVOvUTtj:bxr1wfj) ([raw file](https://github.com/starkware-libs/cairo/blob/fddd929a15fe08cde06b7b60d2437fd1f0acb3c1/crates/cairo-lang-semantic/src/resolve_path.rs#L782)):*
> ```XML
>                 match generic_param {
>                     GenericParam::Type(_) => {
>                         if let ast::Expr::Underscore(_) = generic_arg_syntax {
> ```

You want this logic out side the match I believe, so it will also work for impl generic params

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2444)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @liorgold2)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2444#-NQFSj9n1NAmOLbC-XZ1:-NQFSj9n1NAmOLbC-XZ2:b-vewcwe) (no related file):*
TODOOK: dont add underscore to Expr. Create a new GenericArg syntax node instead.

___

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2444)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/resolve_path.rs` line 782 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2444#-NQFS7uZC4srgVOvUTti:-NQFr-6DA3YIedS38IqB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fddd929a15fe08cde06b7b60d2437fd1f0acb3c1/crates/cairo-lang-semantic/src/resolve_path.rs#L782)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

You want this logic out side the match I believe, so it will also work for impl generic params
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 4 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2444)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2444#-NQFSj9n1NAmOLbC-XZ1:-NQFrlMIDS9Fk1bGI7m0:b-l9fdwf) (no related file):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

TODOOK: dont add underscore to Expr. Create a new GenericArg syntax node instead.
</blockquote></details>

And please add this TODO

___

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2444)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2444)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2444#-NQFSj9n1NAmOLbC-XZ1:-NQJrYuJ2VBddLbGEfDI:b-896fix) (no related file):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

And please add this TODO
</blockquote></details>

Done.

___

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2444#-:-NQJzwx97-agAprIf6TX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
