### PR TITLE
Add a test for the deserialization cost of `__validate__`.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4584)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4584)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/abi_dispatchers_tests.cairo` line 73 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4584#-Nlrbs7Z8UatVEQljZvk:-Nlrbs7Z8UatVEQljZvl:b-r7iw36) ([raw file](https://github.com/starkware-libs/cairo/blob/eac7be2c119bdc51e60775c4b1e050283ecdd6d3/crates/cairo-lang-starknet/cairo_level_tests/abi_dispatchers_tests.cairo#L73)):*
> ```Cairo
> #[test]
> #[available_gas(236520)]
> // Tests the serialization and deserialize of the arguments to `__validate__`.
> ```

i think this should come before the attributes.



_Code quote:_
```Cairo
// Tests the serialization and deserialize of the arguments to `__validate__`.
```
___
*[`crates/cairo-lang-starknet/cairo_level_tests/abi_dispatchers_tests.cairo` line 102 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4584#-Nlrc8H_CJGIRcgzDG9u:-Nlrc8H_CJGIRcgzDG9v:b-s91c19) ([raw file](https://github.com/starkware-libs/cairo/blob/eac7be2c119bdc51e60775c4b1e050283ecdd6d3/crates/cairo-lang-starknet/cairo_level_tests/abi_dispatchers_tests.cairo#L102)):*
> ```Cairo
> 
>     test_contract::__wrapper____validate__(serialized(calls));
> }
> ```

if you also want to make sure at least a certain amount was consumed - i think this will work:



_Suggestion:_
```Cairo
    test_contract::__wrapper____validate__(serialized(calls));
    let final_gas = testing::get_available_gas();
    assert!(final_gas < SOME_VALUE, "Unexpected final amount of gas `{final_gas}`.");
}
```

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4584)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/abi_dispatchers_tests.cairo` line 73 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4584#-NlsFftU90v8INQ9WtMU:-NlsFftU90v8INQ9WtMV:b-r1ex9a) ([raw file](https://github.com/starkware-libs/cairo/blob/4ed429dd1f398beb82df86c972033fc3915bcc8f/crates/cairo-lang-starknet/cairo_level_tests/abi_dispatchers_tests.cairo#L73)):*
> ```Cairo
> // Tests the serialization and deserialize of the arguments to `__validate__`.
> #[test]
> #[available_gas(500000)]
> ```

do note that the constants costs of the test functions are reduced to begin with - so the diff between calls to `get_available_gas` are only about unknown gas reduction (for example, the 100 steps of the validate call are probably part of the constant cost)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4584)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/abi_dispatchers_tests.cairo` line 73 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4584#-NlsFftU90v8INQ9WtMU:-NlvpOEZAYt38vCYb2Rg:b-gsfic4) ([raw file](https://github.com/starkware-libs/cairo/blob/4ed429dd1f398beb82df86c972033fc3915bcc8f/crates/cairo-lang-starknet/cairo_level_tests/abi_dispatchers_tests.cairo#L73)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

do note that the constants costs of the test functions are reduced to begin with - so the diff between calls to `get_available_gas` are only about unknown gas reduction (for example, the 100 steps of the validate call are probably part of the constant cost)
</blockquote></details>

aren't we trying to minimize the fixed gas costs when there is a withdraw_gas call?

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4584)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/abi_dispatchers_tests.cairo` line 73 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4584#-NlsFftU90v8INQ9WtMU:-NlvqT6I9yjNRxhW1G-p:b-7bmu18) ([raw file](https://github.com/starkware-libs/cairo/blob/4ed429dd1f398beb82df86c972033fc3915bcc8f/crates/cairo-lang-starknet/cairo_level_tests/abi_dispatchers_tests.cairo#L73)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

aren't we trying to minimize the fixed gas costs when there is a withdraw_gas call?
</blockquote></details>

we are - what i'm saying is that i'm not sure you are checking *exactly* what you want to - possibly only checking some approximation.

**Pull request merged**
