### PR TITLE
Add ApTracking enum for Environment::ap_tracking.

### PR DESCRIPTION
**Pull request by liorgold2**
**Stack**:
- #3169
- #3154
- #3151
- #3150
- #3149 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3149)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3149#-:-NVVALZ65y9dEojryWb0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3149)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3149#-NVZ4tW663XfpQ0d0aZ8:-NVZ4tW663XfpQ0d0aZ9:bx82xwr) ([raw file](https://github.com/starkware-libs/cairo/blob/329bffb104222aec270afa200991466d8227385c/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L83)):*
> ```XML
>     },
>     #[error(
>         "#{statement_idx}: Invalid Ap change annotation. expected: {expected:?} got: {actual:?}."
> ```

Consider rephrasing. Something like:
```
Ap change annotation does not correspond to tracked ap change from entrypoint. Expected tracking: {}. Actual tracking: {}.
```

Also, consider holding the expected ApChange and actual ApTracking.
___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 404 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3149#-NVZ4cY8EtYAs33Vmg9x:-NVZ4cY8EtYAs33Vmg9y:b-rvve2q) ([raw file](https://github.com/starkware-libs/cairo/blob/329bffb104222aec270afa200991466d8227385c/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L404)):*
> ```XML
>                 let expected_ap_tracking = ApTracking::Enabled { ap_change: *x };
>                 if annotations.environment.ap_tracking_base != Some(func.entry_point)
>                     || expected_ap_tracking != annotations.environment.ap_tracking
> ```

Swap so it corresponds to the previous line of (actual != expected)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3149)* status: all files reviewed, 3 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 342 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3149#-NVZ5xpbA19WiXIEKszN:-NVZ5xpbA19WiXIEKszO:bqajwad) ([raw file](https://github.com/starkware-libs/cairo/blob/329bffb104222aec270afa200991466d8227385c/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L342)):*
> ```XML
>                     });
>                 }
>                 ApTracking::Enabled { ap_change: 0 }
> ```

It kinda scares me that this line is not right next to the base change.
Can we perhaps make ap_tracking_base mutable, and assign to it?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3149)* status: all files reviewed, 3 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 342 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3149#-NVZ5xpbA19WiXIEKszN:-NVZ7YBR8XWt2xSS5QqB:b-ekub4b) ([raw file](https://github.com/starkware-libs/cairo/blob/329bffb104222aec270afa200991466d8227385c/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L342)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

It kinda scares me that this line is not right next to the base change.
Can we perhaps make ap_tracking_base mutable, and assign to it?
</blockquote></details>

Actually, I see you did something better in the next PR

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3149)* status: all files reviewed, 3 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 404 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3149#-NVZ4cY8EtYAs33Vmg9x:-NVZ7zY743RZzQpxOHVD:b-ekub4b) ([raw file](https://github.com/starkware-libs/cairo/blob/329bffb104222aec270afa200991466d8227385c/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L404)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Swap so it corresponds to the previous line of (actual != expected)
</blockquote></details>

Actually, I see you did something better in the next PR

**Review by spapinistarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3149)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3149)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3149#-NVZ4tW663XfpQ0d0aZ8:-NVZqjIR9v_BsHy3clxi:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/27396909300b0ff1c95d2afe06c68b78f39ce3f2/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L83)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Consider rephrasing. Something like:
```
Ap change annotation does not correspond to tracked ap change from entrypoint. Expected tracking: {}. Actual tracking: {}.
```

Also, consider holding the expected ApChange and actual ApTracking.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/environment/ap_tracking.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3149#-NVZ6rv-5VDa-0aKFvSS:-NVZqlu617aLB9Q2iR7V:b-9880sh) ([raw file](https://github.com/starkware-libs/cairo/blob/27396909300b0ff1c95d2afe06c68b78f39ce3f2/crates/cairo-lang-sierra-to-casm/src/environment/ap_tracking.rs#L8)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

it would make more sens if this was ApTrackingChange. This would mean ApTrackingChange to need to hold the ap change as well:
Enable/Disable/Known(usize)
</blockquote></details>

This is for another PR.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3149)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3149)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
