### PR TITLE
Enable inlining.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1787)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1787#-:-NLz2FZ48BB7OpjkLAgS:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1787#-NLz1jH6-QMTBqQXOBpK:-NLz1jH6-QMTBqQXOBpL:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/48d4e3eaafd1bcf1009059bd7553309d4c0bbb35/crates/cairo-lang-lowering/src/db.rs#L46)):*
> ```XML
>     ) -> Maybe<Arc<FlatLowered>>;
> 
>     /// Computes the final lowered representation (after all the internal transformation).
> ```





_Suggestion:_
```XML
    /// Computes the final lowered representation (after all the internal transformations).
```
___
*[`crates/cairo-lang-sierra-generator/src/block_generator_test.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1787#-NLz1rliB0fqmYjoR6pc:-NLz1rliB0fqmYjoR6pd:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/48d4e3eaafd1bcf1009059bd7553309d4c0bbb35/crates/cairo-lang-sierra-generator/src/block_generator_test.rs#L38)):*
> ```XML
>     let lowered_structured =
>         db.function_with_body_lowered_structured(test_function.function_id).unwrap();
>     let lowered = db.function_with_body_lowered_flat_with_inlining(test_function.function_id).unwrap();
> ```

?



_Suggestion:_
```XML
    let lowered = db.function_with_body_lowered_final(test_function.function_id).unwrap();
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1787)* status: 4 of 9 files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1787#-NLz1jH6-QMTBqQXOBpK:-NLz31B_B_Ug_IpZNgM2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/48d4e3eaafd1bcf1009059bd7553309d4c0bbb35/crates/cairo-lang-lowering/src/db.rs#L46)):*
> ```XML
>     ) -> Maybe<Arc<FlatLowered>>;
> 
>     /// Computes the final lowered representation (after all the internal transformation).
> ```

Done.
___
*[`crates/cairo-lang-sierra-generator/src/block_generator_test.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1787#-NLz1rliB0fqmYjoR6pc:-NLz3CCn8wRF3uuFqo-9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/48d4e3eaafd1bcf1009059bd7553309d4c0bbb35/crates/cairo-lang-sierra-generator/src/block_generator_test.rs#L38)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1787)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1787)* status: 2 of 11 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/test.rs` line 60 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1787#-NLzOou04EK3ajpiTMEa:-NLzOou04EK3ajpiTMEb:b-fbkwbw) ([raw file](https://github.com/starkware-libs/cairo/blob/e63fc37a4d6aa7c9586514a9d439898b345cf603/crates/cairo-lang-lowering/src/test.rs#L60)):*
> ```XML
>             format!("{:?}", structured_lowered.debug(&lowered_formatter)),
>         ),
>         ("lowering_flat".into(), format!("{:?}", lowered.debug(&lowered_formatter))),
> ```

Do I need to rename this? to what?

lowered?



_Code quote:_
```XML
lowering_flat
```

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 8 files at r1, 9 of 9 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1787#-:-NLzPTKMCKN2tuOd4uVP:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 8 files at r1, 4 of 9 files at r3, 2 of 2 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1787)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
