### PR TITLE
Change StarkNet to Starknet

### PR DESCRIPTION
**Pull request by kongtaoxing**
Changes the spelling of "StarkNet" from "StarkNet" to "Starknet" everywhere in the doc and code annotations following the recommendations in [this SNIP](https://community.starknet.io/t/snip-naming-convention-starknet-not-starknet).

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2107)

### CODE REVIEW

**Review by kongtaoxing — COMMENTED** [review]
Reviewed by myself

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 12 of 15 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2107#-:-NOF4Eh_8ecQWx_ks99p:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kongtaoxing)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2107#-:-NOF_SLw18lz6ASLedaa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kongtaoxing)

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2107)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kongtaoxing)

**Pull request merged**
