### PR TITLE
Methods

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3084)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3083** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3083" target="_blank">Graphite</a> 
    * **PR #3084** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3084" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/3084?utm_source=stack-comment).

**Review by JameStark — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3084)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/method-calls.adoc` line 4 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3084#-NUzhVm3-UIPwCQSyLt6:-NUzhVm3-UIPwCQSyLt7:bem8efz) ([raw file](https://github.com/starkware-libs/cairo/blob/72b252468b5edd91dda92468bd116a00e85afc1f/docs/reference/src/components/cairo/modules/language_constructs/pages/method-calls.adoc#L4)):*
> ```AsciiDoc
> A method call is an expression of the form `expr.method(arguments...)`.
> This expression is roughly equivalent to `method(expr, arguments...)`.
> Differences:
> ```

The differences between the two are:

**Review by JameStark — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3084)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3084)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @JameStark and @orizi)

___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/method-calls.adoc` line 4 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3084#-NUzhVm3-UIPwCQSyLt6:-NUzihw9CUz3Hn_Ix_dp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/72b252468b5edd91dda92468bd116a00e85afc1f/docs/reference/src/components/cairo/modules/language_constructs/pages/method-calls.adoc#L4)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

The differences between the two are:
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3084#-:-NUzvOIo2gm16iKSE7Vw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
