### PR TITLE
Make sub pointers depend on DeriveStorage.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5890)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5890)* status: 4 of 19 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`corelib/src/starknet/storage.cairo` line 529 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5890#-O0GRsY--3Uz46ufYVtK:-O0GRsY--3Uz46ufYVtL:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/032d76f182510c6f853e1ea07221cb052ea461df/corelib/src/starknet/storage.cairo#L529)):*
> ```Cairo
> #[feature("simple-storage-layout")]
> impl u256SubPointersImpl<
>     impl i: starknet::storage_access::SimpleStorageLayout<u256>
> ```





_Suggestion:_
```Cairo
    +starknet::storage_access::SimpleStorageLayout<u256>
```
___
*[`corelib/src/starknet/storage_access.cairo` line 99 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5890#-O0GSAnR9ZaYAG3QVRm2:-O0GSAnR9ZaYAG3QVRm3:b-wcis0r) ([raw file](https://github.com/starkware-libs/cairo/blob/032d76f182510c6f853e1ea07221cb052ea461df/corelib/src/starknet/storage_access.cairo#L99)):*
> ```Cairo
>     note: "Manually implementing `SimpleStorageLayout` is not advised. Use #[derive(Store)] instead."
> )]
> pub trait SimpleStorageLayout<T> {}
> ```

so that the error would actually be clear.



_Suggestion:_
```Cairo
pub trait DeriveStorage<T> {}
```

**Review by orizi — COMMENTED** [review]
> Reviewed 15 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5890)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5890)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/starknet/storage.cairo` line 529 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5890#-O0GRsY--3Uz46ufYVtK:-O0IJARKDhbIVursYHBY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/032d76f182510c6f853e1ea07221cb052ea461df/corelib/src/starknet/storage.cairo#L529)):*
> ```Cairo
> #[feature("simple-storage-layout")]
> impl u256SubPointersImpl<
>     impl i: starknet::storage_access::SimpleStorageLayout<u256>
> ```

Done.
___
*[`corelib/src/starknet/storage_access.cairo` line 99 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5890#-O0GSAnR9ZaYAG3QVRm2:-O0IJvGq-TcnPgje9vE6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/032d76f182510c6f853e1ea07221cb052ea461df/corelib/src/starknet/storage_access.cairo#L99)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

so that the error would actually be clear.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5890)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin/consts.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5890#-O0INZzq2D_3oY94ap9S:-O0INZzq2D_3oY94ap9T:bkrwfjh) ([raw file](https://github.com/starkware-libs/cairo/blob/0be7eb5089c01c226de22081a106c9e098a9ea44/crates/cairo-lang-starknet/src/plugin/consts.rs#L24)):*
> ```XML
> pub const EVENT_TRAIT: &str = "starknet::Event";
> pub const STORE_TRAIT: &str = "starknet::Store";
> pub const SIMPLE_STORAGE_LAYOUT_TRAIT: &str = "starknet::storage_access::DeriveStorage";
> ```

rename constant.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5890)* status: 18 of 19 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/consts.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5890#-O0INZzq2D_3oY94ap9S:-O0LIQmx62-mdJTf9tpR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0be7eb5089c01c226de22081a106c9e098a9ea44/crates/cairo-lang-starknet/src/plugin/consts.rs#L24)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rename constant.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5890#-:-O0LQI9H30crMRnoEqJZ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5890)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5890#-O0Os5a_64RBt6jWcuOI):*
reword.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5890)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5890#-O0Os5a_64RBt6jWcuOI):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

reword.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5890#-:-O0c99rVCu0YgCvuoIKS:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
