### PR TITLE
Add ContractAddressToFelt.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2087)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2087#-:-NNqi4m5C1Rt_X3-KQi7:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/interoperability.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2087#-NNqhhuV5PVarkr0Xvks:-NNqhhuV5PVarkr0Xvkt:b1ibvm7) ([raw file](https://github.com/starkware-libs/cairo/blob/9133729426889d0ab6fb83c0ce0d319b99cdafdf/crates/cairo-lang-sierra/src/extensions/modules/starknet/interoperability.rs#L102)):*
> ```XML
>     ) -> Result<LibfuncSignature, SpecializationError> {
>         Ok(LibfuncSignature::new_non_branch(
>             vec![context.get_concrete_type(ContractAddressType::id(), &[])?],
> ```

since you return the exact same data?



_Suggestion:_
```XML
        Ok(LibfuncSignature::new_non_branch_ex(
            vec![ParamSignature {
                    ty: context.get_concrete_type(ContractAddressType::id(), &[])?],
                    allow_deferred: true,
                    allow_add_const: true,
                    allow_const: true,
            }]
            vec![OutputVarInfo {
                ty: context.get_concrete_type(FeltType::id(), &[])?,
                ref_info: OutputVarReferenceInfo::SameAsParam { param_idx: 0 },
            }],
            SierraApChange::Known { new_vars_only: true },
        ))
    }
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2087)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/interoperability.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2087#-NNqhhuV5PVarkr0Xvks:-NNqnG1R4F2LcsQPjf9V:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9133729426889d0ab6fb83c0ce0d319b99cdafdf/crates/cairo-lang-sierra/src/extensions/modules/starknet/interoperability.rs#L102)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

since you return the exact same data?
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 6 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2087)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2087)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2087)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
