### PR TITLE
Moved `defs` plugins files to be based on external files.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #6227
- #6225 ⬅
- #6224
- #6223

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6225)

### CODE REVIEW

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 8 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6225)* status: 8 of 12 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @gilbens-starkware, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6225#-O4eb7Ao9VloqcddNpkw:-O4eb7Ao9VloqcddNpkx:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/405e9dcf85134d05bfdca9e0765bdb4b2180db95/crates/cairo-lang-filesystem/src/db.rs#L115)):*
> ```XML
>     /// Returns the virtual file matching the external id.
>     fn ext_as_virtual(&self, _external_id: salsa::InternId) -> VirtualFile {
>         panic!("Should not be called, unless specifically implemented!");
> ```





_Suggestion:_
```XML
unreachable
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6225)* status: 8 of 12 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6225#-O4eb7Ao9VloqcddNpkw:-O4ekvSZ9PbLryRcUmD1:b-ukqqa1) ([raw file](https://github.com/starkware-libs/cairo/blob/405e9dcf85134d05bfdca9e0765bdb4b2180db95/crates/cairo-lang-filesystem/src/db.rs#L115)):*
> ```XML
>     /// Returns the virtual file matching the external id.
>     fn ext_as_virtual(&self, _external_id: salsa::InternId) -> VirtualFile {
>         panic!("Should not be called, unless specifically implemented!");
> ```

it is reachable with bad config - definitely should be panic and not unreachable.

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 4 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6225)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-defs/src/ids.rs` line 308 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6225#-O4f-aj5Auenuwdrt82s:-O4f-aj5Auenuwdrt82t:bvc12cj) ([raw file](https://github.com/starkware-libs/cairo/blob/405e9dcf85134d05bfdca9e0765bdb4b2180db95/crates/cairo-lang-defs/src/ids.rs#L308)):*
> ```XML
> /// An id for a file defined out of the filesystem crate.
> #[derive(Clone, Debug, Hash, PartialEq, Eq)]
> pub struct ExtFileLongId(pub ModuleId, pub SyntaxStablePtrId, pub SmolStr);
> ```

use struct format. from bare declaration I have no idea that that `SmolStr` stores



_Suggestion:_
```XML
pub struct ExtFileLongId {
    pub module: ModuleId,
    pub whose_stable_ptr?: SyntaxStablePtrId,
    pub what_is_this?: SmolStr
}
```
___
*[`crates/cairo-lang-defs/src/ids.rs` line 309 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6225#-O4f-RNQEUjL40JMxvRz:-O4f-RNQEUjL40JMxvS-:b-5x5xv6) ([raw file](https://github.com/starkware-libs/cairo/blob/405e9dcf85134d05bfdca9e0765bdb4b2180db95/crates/cairo-lang-defs/src/ids.rs#L309)):*
> ```XML
> #[derive(Clone, Debug, Hash, PartialEq, Eq)]
> pub struct ExtFileLongId(pub ModuleId, pub SyntaxStablePtrId, pub SmolStr);
> define_short_id!(ExtFileId, ExtFileLongId, DefsGroup, lookup_intern_ext_file, intern_ext_file);
> ```

TBH the choice of term `external` is pretty confusing to my eyes. I doubt this can ever be used for other purposed than storing plugin-generated content, so perhaps should all these types names reflect this?



_Suggestion:_
```XML
#[derive(Clone, Debug, Hash, PartialEq, Eq)]
pub struct PluginGeneratedFileLongId(pub ModuleId, pub SyntaxStablePtrId, pub SmolStr);
define_short_id!(PluginGeneratedFileId, PluginGeneratedFileLongId, DefsGroup, lookup_intern_plugin_generated_file, intern_plugin_generated_file);
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6225)* status: 10 of 12 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-defs/src/ids.rs` line 308 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6225#-O4f-aj5Auenuwdrt82s:-O4f6zWbBItvbc4yOqA5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/405e9dcf85134d05bfdca9e0765bdb4b2180db95/crates/cairo-lang-defs/src/ids.rs#L308)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

use struct format. from bare declaration I have no idea that that `SmolStr` stores
</blockquote></details>

Done.
___
*[`crates/cairo-lang-defs/src/ids.rs` line 309 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6225#-O4f-RNQEUjL40JMxvRz:-O4f4YbM5rk1yKWtGKoT:b-76oxcl) ([raw file](https://github.com/starkware-libs/cairo/blob/405e9dcf85134d05bfdca9e0765bdb4b2180db95/crates/cairo-lang-defs/src/ids.rs#L309)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

TBH the choice of term `external` is pretty confusing to my eyes. I doubt this can ever be used for other purposed than storing plugin-generated content, so perhaps should all these types names reflect this?
</blockquote></details>

possibly wrong - it very well may be generated for other sort of generated file - but for the time being this would work out.

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 10 of 12 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6225)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-defs/src/db.rs` line 621 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6225#-O4gedWC1PyvXs7UF-AD:-O4gedWD2QaolxMT9pkS:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/09ddce6b4786d02c84b2315bf32e5a37aeb01c40/crates/cairo-lang-defs/src/db.rs#L621)):*
> ```XML
>     };
> 
>     let mut files = OrderedHashMap::<_, _>::default();
> ```





_Suggestion:_
```XML
let mut files = OrderedHashMap:::default();
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6225)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-defs/src/db.rs` line 621 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6225#-O4gedWC1PyvXs7UF-AD:-O4hsBEuBkhI2d4_jk6d:b-sywrxs) ([raw file](https://github.com/starkware-libs/cairo/blob/09ddce6b4786d02c84b2315bf32e5a37aeb01c40/crates/cairo-lang-defs/src/db.rs#L621)):*
> ```XML
>     };
> 
>     let mut files = OrderedHashMap::<_, _>::default();
> ```

this would not compile.

**Review by mkaput — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6225)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @gilbens-starkware, and @piotmag769)

___
*[`crates/cairo-lang-defs/src/ids.rs` line 309 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6225#-O4f-RNQEUjL40JMxvRz:-O4ix9jK3WlkLLn4Z_cn:bmretyk) ([raw file](https://github.com/starkware-libs/cairo/blob/405e9dcf85134d05bfdca9e0765bdb4b2180db95/crates/cairo-lang-defs/src/ids.rs#L309)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

possibly wrong - it very well may be generated for other sort of generated file - but for the time being this would work out.
</blockquote></details>

a) it could, but we can think about this when this happens
b) it took me a time to understand what actually `external` means => this was a confusing term :/

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6225#-:-O4jFBIx2b79M4d6kwS6:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @piotmag769)

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6225)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @piotmag769)

**Pull request merged**
