### PR TITLE
Added generic functions from impl-alias into the abi.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3889)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3889)* status: all files reviewed, 16 unresolved discussions (waiting on @orizi)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3889#-NcNXM4tDIQd2aSyBD5L):*
?



_Suggestion:_
```
om impl-alias i
```
___
*[`crates/cairo-lang-starknet/src/contract.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3889#-NcNY5BQEKS96dN-eG7s:-NcNY5BQEKS96dN-eG7t:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/03309890c68af029753e2831b636f4c5ae7f2e8c/crates/cairo-lang-starknet/src/contract.rs#L113)):*
> ```XML
> 
> /// Returns the ABI functions in a given module.
> /// Assumes the given module is a generated at a contract context.
> ```





_Suggestion:_
```XML
/// Returns the ABI functions of a given contract.
/// Assumes the given module is a contract module.
```
___
*[`crates/cairo-lang-starknet/src/contract.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3889#-NcNYf2b7EIlefDbtVrj:-NcNYf2b7EIlefDbtVrk:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/03309890c68af029753e2831b636f4c5ae7f2e8c/crates/cairo-lang-starknet/src/contract.rs#L128)):*
> ```XML
> /// Returns the ABI functions in a given module in the contract.
> fn get_contract_module_abi_functions(
>     db: &dyn SemanticGroup,
> ```





_Suggestion:_
```XML
/// Returns the ABI functions in a given internal module in the contract.
fn get_contract_internal_module_abi_functions(
    db: &dyn SemanticGroup,
```
___
*[`crates/cairo-lang-starknet/src/contract.rs` line 169 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3889#-NcNZFKLDBlWRUStPpyN:-NcNZFKMAVcTjvyWs4To:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/03309890c68af029753e2831b636f4c5ae7f2e8c/crates/cairo-lang-starknet/src/contract.rs#L169)):*
> ```XML
> }
> 
> /// Returns the module id of the submodule of module.
> ```





_Suggestion:_
```XML
turns the module id of the submodule of a module
```
___
*[`crates/cairo-lang-starknet/src/contract.rs` line 170 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3889#-NcNZIr25X99VGmAKQhx:-NcNZIr25X99VGmAKQhy:b-uup3cr) ([raw file](https://github.com/starkware-libs/cairo/blob/03309890c68af029753e2831b636f4c5ae7f2e8c/crates/cairo-lang-starknet/src/contract.rs#L170)):*
> ```XML
> 
> /// Returns the module id of the submodule of module.
> fn get_submodule_id(
> ```

Please move this helper function to the bottom
___
*[`crates/cairo-lang-starknet/src/contract.rs` line 188 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3889#-NcN_7BgBFuI8yte87eV:-NcN_7BgBFuI8yte87eW:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/03309890c68af029753e2831b636f4c5ae7f2e8c/crates/cairo-lang-starknet/src/contract.rs#L188)):*
> ```XML
> }
> 
> /// Returns the abi functions of the impl aliases for the given contract.
> ```





_Suggestion:_
```XML
// Returns the abi functions of the impl aliases included in the given contract.
```
___
*[`crates/cairo-lang-starknet/src/contract.rs` line 192 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3889#-NcN_TvEACqhwHh9gC5V:-NcN_TvEACqhwHh9gC5W:b7kwaxw) ([raw file](https://github.com/starkware-libs/cairo/blob/03309890c68af029753e2831b636f4c5ae7f2e8c/crates/cairo-lang-starknet/src/contract.rs#L192)):*
> ```XML
>     db: &dyn SemanticGroup,
>     contract: &ContractDeclaration,
>     module_prefix: &str,
> ```

Please doc this param



_Code quote:_
```XML
module_prefix: &str,
```
___
*[`crates/cairo-lang-starknet/src/contract.rs` line 202 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3889#-NcNc9o62yftSdzCmlr2:-NcNc9o74r7KxUS-3cRT:b-3hmm95) ([raw file](https://github.com/starkware-libs/cairo/blob/03309890c68af029753e2831b636f4c5ae7f2e8c/crates/cairo-lang-starknet/src/contract.rs#L202)):*
> ```XML
>         .module_impl_aliases(generated_module_id)
>         .to_option()
>         .with_context(|| "Failed to get external module uses.")?
> ```

fix message



_Code quote:_
```XML
ailed to get external module uses.
```
___
*[`crates/cairo-lang-starknet/src/contract.rs` line 205 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3889#-NcNdGnD6PRpZT9fEdC4:-NcNdGnD6PRpZT9fEdC5:b2enybs) ([raw file](https://github.com/starkware-libs/cairo/blob/03309890c68af029753e2831b636f4c5ae7f2e8c/crates/cairo-lang-starknet/src/contract.rs#L205)):*
> ```XML
>         .iter()
>     {
>         let resolver_data = db.impl_alias_resolver_data(*impl_alias_id).unwrap();
> ```

Don't you need to handle the error?
Same for another unwrap() below.



_Code quote:_
```XML
.unwrap();
```
___
*[`crates/cairo-lang-starknet/src/contract.rs` line 216 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3889#-NcNdjVH69rVglTDbVRl:-NcNdjVH69rVglTDbVRm:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/03309890c68af029753e2831b636f4c5ae7f2e8c/crates/cairo-lang-starknet/src/contract.rs#L216)):*
> ```XML
>         );
> 
>         let elements = impl_alias.impl_path(syntax_db).elements(syntax_db);
> ```





_Suggestion:_
```XML
impl_path_elements
```
___
*[`crates/cairo-lang-starknet/src/contract.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3889#-NcNexY960M3LZbLctwk:-NcNexYAAh_83iqK0OMW:b-4yzmjt) ([raw file](https://github.com/starkware-libs/cairo/blob/03309890c68af029753e2831b636f4c5ae7f2e8c/crates/cairo-lang-starknet/src/contract.rs#L226)):*
> ```XML
>             ),
>             ast::PathSegment::Simple(segment) => (segment.ident(syntax_db).text(syntax_db), vec![]),
>         };
> ```

As in the other PR:
`let impl_name = impl_final_part.identifier_ast(db);` separately.

You also have .generic_args() instead of the match.



_Code quote:_
```XML
        let (impl_name, generic_args) = match impl_final_part {
            ast::PathSegment::WithGenericArgs(segment) => (
                segment.ident(syntax_db).text(syntax_db),
                segment.generic_args(syntax_db).generic_args(syntax_db).elements(syntax_db),
            ),
            ast::PathSegment::Simple(segment) => (segment.ident(syntax_db).text(syntax_db), vec![]),
        };
```
___
*[`crates/cairo-lang-starknet/src/contract.rs` line 233 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3889#-NcNhK-5068oSRTeuVoq:-NcNhK-5068oSRTeuVor:b-bpfh1b) ([raw file](https://github.com/starkware-libs/cairo/blob/03309890c68af029753e2831b636f4c5ae7f2e8c/crates/cairo-lang-starknet/src/contract.rs#L233)):*
> ```XML
>                 NotFoundItemType::Identifier,
>             )
>             .unwrap()
> ```

This would crash if someone writes a wrong path, wouldn't it?
___
*[`crates/cairo-lang-starknet/src/contract.rs` line 235 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3889#-NcNgzmO4FwG4IduDhfT:-NcNgzmO4FwG4IduDhfU:bvxlr8p) ([raw file](https://github.com/starkware-libs/cairo/blob/03309890c68af029753e2831b636f4c5ae7f2e8c/crates/cairo-lang-starknet/src/contract.rs#L235)):*
> ```XML
>             .unwrap()
>         else {
>             unreachable!("impl must be within some module.");
> ```

This would happen if someone writes:
impl bla = path::to::some::trait::<...>

woudn't it?
___
*[`crates/cairo-lang-starknet/src/contract.rs` line 244 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3889#-NcNjAT06Nn_IcwoCEky:-NcNjAT06Nn_IcwoCEkz:b23snjw) ([raw file](https://github.com/starkware-libs/cairo/blob/03309890c68af029753e2831b636f4c5ae7f2e8c/crates/cairo-lang-starknet/src/contract.rs#L244)):*
> ```XML
>                         &mut diagnostics,
>                         impl_alias.stable_ptr().untyped(),
>                         GenericFunctionId::Free(f),
> ```

isn't f of type `Aliased<FreeFunctionId>`?
Also - I don't see the use of the alias.



_Code quote:_
```XML
(f
```
___
*[`crates/cairo-lang-starknet/src/contract.rs` line 249 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3889#-NcNjn3qCDJ1aBYjWhQH:-NcNjn3qCDJ1aBYjWhQI:bfmswvx) ([raw file](https://github.com/starkware-libs/cairo/blob/03309890c68af029753e2831b636f4c5ae7f2e8c/crates/cairo-lang-starknet/src/contract.rs#L249)):*
> ```XML
>                     .to_option()?
>                     .get_concrete(db)
>                     .body(db)
> ```

why do you need the body?



_Code quote:_
```XML
.body(db)
```
___
*[`crates/cairo-lang-starknet/src/contract.rs` line 260 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3889#-NcNk_I7-VlnB73bc9pr:-NcNk_I7-VlnB73bc9ps:b-6bjg78) ([raw file](https://github.com/starkware-libs/cairo/blob/03309890c68af029753e2831b636f4c5ae7f2e8c/crates/cairo-lang-starknet/src/contract.rs#L260)):*
> ```XML
>         }
>     }
>     diagnostics.build().expect_with_db(db.elongate(), "could not put generics onto the wrappers.");
> ```

I don't get this error



_Code quote:_
```XML
could not put generics onto the wrappers
```

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3889)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/contract.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3889#-NcNYf2b7EIlefDbtVrj:-NcRJpL06Op3dtyhzyx6:b-60bsl4) ([raw file](https://github.com/starkware-libs/cairo/blob/03309890c68af029753e2831b636f4c5ae7f2e8c/crates/cairo-lang-starknet/src/contract.rs#L128)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Done.
</blockquote></details>

suggested to also rename the function name. I think contract_module is confusing with the main module of the contrat itself.
___
*[`crates/cairo-lang-starknet/src/contract.rs` line 235 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3889#-NcNgzmO4FwG4IduDhfT:-NcRQbj32LBV5MUdDP0P:bq26iuz) ([raw file](https://github.com/starkware-libs/cairo/blob/03309890c68af029753e2831b636f4c5ae7f2e8c/crates/cairo-lang-starknet/src/contract.rs#L235)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

The `<>` is still part of the last part.

[crates/cairo-lang-starknet/test_data/test_contract.sierra.json](https://vscode.dev/github/starkware-libs/cairo2/blob/main/crates/cairo-lang-parser/test_data/expected_results/test1_tree_no_trivia#L701)
</blockquote></details>

I meant this expects the resolved path to be a module. If it turns out to be a trait for example, then we'll get to the else and the unreachable.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3889)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/contract.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3889#-NcNYf2b7EIlefDbtVrj:-NcRaCjgBHtC3aVosvpf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/03309890c68af029753e2831b636f4c5ae7f2e8c/crates/cairo-lang-starknet/src/contract.rs#L128)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

suggested to also rename the function name. I think contract_module is confusing with the main module of the contrat itself.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/contract.rs` line 235 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3889#-NcNgzmO4FwG4IduDhfT:-NcRaIv4CuzKjqjW34Sj:b-ol47sa) ([raw file](https://github.com/starkware-libs/cairo/blob/03309890c68af029753e2831b636f4c5ae7f2e8c/crates/cairo-lang-starknet/src/contract.rs#L235)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I meant this expects the resolved path to be a module. If it turns out to be a trait for example, then we'll get to the else and the unreachable.
</blockquote></details>

this would fail at the semantic stage.
but changing to internal error.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3889#-:-NcS4RsT9soNAPqy_rkz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
