### PR TITLE
Changed debug::print to print hex values

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3377)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3377)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1737 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3377#-NXiz0SXAYWrBfORu32X:-NXiz0SXAYWrBfORu32Y:b-1logu) ([raw file](https://github.com/starkware-libs/cairo/blob/83c89f9e8de1a15507b061b90b2e614c877f4a0d/crates/cairo-lang-runner/src/casm_run/mod.rs#L1737)):*
> ```XML
>                 } else {
>                     println!("[DEBUG]\t{:<31}\t(raw: 0x{:X}) ", ' ', value.to_bigint());
>                 }
> ```

if the second one cries (as it has for me for some reason)
just extract `let raw = value.to_bigint();`



_Suggestion:_
```XML
                let value = vm.get_integer(curr)?;
                if let Some(shortstring) = as_cairo_short_string(&value) {
                    println!("[DEBUG]\t{shortstring: <31}\t(raw: {:#x})", value.to_bigint());
                } else {
                    println!("[DEBUG]\t{:<31}\t(raw: {:#x}) ", ' ', value.to_bigint());
                }
```

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3377)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Comment by parketh** [comment]
Is there a way to continue printing values as decimals following this update? In our case decimals are more relevant than hex for debugging

**Comment by yuvalsw** [comment]
Hey, please see this:
https://github.com/starkware-libs/cairo/issues/3459

**Comment by parketh** [comment]
What about printing decimal values rather than short strings? Is there a different print method to support this?

**Pull request merged**
