### PR TITLE
Avoid `generate_push_values_statement_for_remapping` for a fallthroug…

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
…h with no goto's.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2110)

### CODE REVIEW

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2110)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/block_generator.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2110#-NO5C1ki2C7k9h8T3kef:-NO5C1ki2C7k9h8T3keg:b-xfimzg) ([raw file](https://github.com/starkware-libs/cairo/blob/0138065659c946ae83e452dd530c244aef418c75/crates/cairo-lang-sierra-generator/src/block_generator.rs#L122)):*
> ```XML
>             } else {
>                 // There are no Goto's into this block so we can use var_remapping
>                 // instead of `generate_push_values_statement_for_remapping`.
> ```

Not sure what you mean by `var_remapping` in the comment.



_Suggestion:_
```XML
                // There are no goto's leading to this block, so we can use var_remapping
                // instead of `generate_push_values_statement_for_remapping`.
```
___
*[`crates/cairo-lang-sierra-generator/src/expr_generator_context.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2110#-NO5CSExCBHAAqI-Rnxe:-NO5CSExCBHAAqI-Rnxf:b-muhk4j) ([raw file](https://github.com/starkware-libs/cairo/blob/0138065659c946ae83e452dd530c244aef418c75/crates/cairo-lang-sierra-generator/src/expr_generator_context.rs#L76)):*
> ```XML
>     }
> 
>     /// Maps a lowering variable to a sierra variable.
> ```

You have `lowering_var_id` twice in the second line.



_Suggestion:_
```XML
    /// Maps a lowering variable to the given Sierra variable.
    /// I.e., every instance of `lowering_var_id` is replaced by lowering_var_id.
```
___
*[`crates/cairo-lang-sierra-generator/src/expr_generator_context.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2110#-NO5Ci_E-Fu63D0qSKg6:-NO5Ci_E-Fu63D0qSKg7:bke7wg6) ([raw file](https://github.com/starkware-libs/cairo/blob/0138065659c946ae83e452dd530c244aef418c75/crates/cairo-lang-sierra-generator/src/expr_generator_context.rs#L77)):*
> ```XML
> 
>     /// Maps a lowering variable to a sierra variable.
>     /// I.e. every instance of `lowering_var_id` is replaced by lowering_var_id.
> ```

Add an example of when this is used (e.g., you can mention something like "instead of renaming").
___
*[`crates/cairo-lang-sierra-generator/src/expr_generator_context.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2110#-NO5CMEYBm6QaK4BuBTu:-NO5CMEYBm6QaK4BuBTv:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0138065659c946ae83e452dd530c244aef418c75/crates/cairo-lang-sierra-generator/src/expr_generator_context.rs#L78)):*
> ```XML
>     /// Maps a lowering variable to a sierra variable.
>     /// I.e. every instance of `lowering_var_id` is replaced by lowering_var_id.
>     pub fn add_variables_mapping(
> ```





_Suggestion:_
```XML
pub fn add_variable_mapping(
```
___
*[`crates/cairo-lang-sierra-generator/src/expr_generator_context.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2110#-NO5C_m5DLspD9O_6qJe:-NO5C_m5DLspD9O_6qJf:b-7rl03v) ([raw file](https://github.com/starkware-libs/cairo/blob/0138065659c946ae83e452dd530c244aef418c75/crates/cairo-lang-sierra-generator/src/expr_generator_context.rs#L83)):*
> ```XML
>         sierra_var_id: cairo_lang_sierra::ids::VarId,
>     ) {
>         self.variables.insert(SierraGenVar::LoweringVar(lowering_var_id), sierra_var_id);
> ```

Assert that the result of the insert is None/false/true - whatever is required to make sure it didn't override anything.



_Code quote:_
```XML
 self.variables.insert(SierraGenVar::LoweringVar(lowering_var_id), sierra_var_id);
```

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2110)* status: all files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2110)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-generator/src/block_generator.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2110#-NO5C1ki2C7k9h8T3kef:-NO5EtxhBpCFAxCN8hgu:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0138065659c946ae83e452dd530c244aef418c75/crates/cairo-lang-sierra-generator/src/block_generator.rs#L122)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Not sure what you mean by `var_remapping` in the comment.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/expr_generator_context.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2110#-NO5Ci_E-Fu63D0qSKg6:-NO5ORWl-7TafhOrkxLr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0138065659c946ae83e452dd530c244aef418c75/crates/cairo-lang-sierra-generator/src/expr_generator_context.rs#L77)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Add an example of when this is used (e.g., you can mention something like "instead of renaming").
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/expr_generator_context.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2110#-NO5CMEYBm6QaK4BuBTu:-NO5P94h1sgoHskpYddk:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0138065659c946ae83e452dd530c244aef418c75/crates/cairo-lang-sierra-generator/src/expr_generator_context.rs#L78)):*
> ```XML
>     /// Maps a lowering variable to a sierra variable.
>     /// I.e. every instance of `lowering_var_id` is replaced by lowering_var_id.
>     pub fn add_variables_mapping(
> ```

Done.
___
*[`crates/cairo-lang-sierra-generator/src/expr_generator_context.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2110#-NO5C_m5DLspD9O_6qJe:-NO5P9dQ-Go6RU5BglBh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0138065659c946ae83e452dd530c244aef418c75/crates/cairo-lang-sierra-generator/src/expr_generator_context.rs#L83)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Assert that the result of the insert is None/false/true - whatever is required to make sure it didn't override anything.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2110)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-generator/src/expr_generator_context.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2110#-NO5CSExCBHAAqI-Rnxe:-NO5i3XO9hWWrw5Ks44B:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0138065659c946ae83e452dd530c244aef418c75/crates/cairo-lang-sierra-generator/src/expr_generator_context.rs#L76)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

You have `lowering_var_id` twice in the second line.
</blockquote></details>

Done.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2110)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/expr_generator_context.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2110#-NO5C_m5DLspD9O_6qJe:-NODz7IO5wc41AFiPeUF:b-pei3it) ([raw file](https://github.com/starkware-libs/cairo/blob/0138065659c946ae83e452dd530c244aef418c75/crates/cairo-lang-sierra-generator/src/expr_generator_context.rs#L83)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Use `assert!(....is_none(), "...");`

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2110)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/expr_generator_context.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2110#-NO5C_m5DLspD9O_6qJe:-NOE3VQP4pjL5382RDXa:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0138065659c946ae83e452dd530c244aef418c75/crates/cairo-lang-sierra-generator/src/expr_generator_context.rs#L83)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Use `assert!(....is_none(), "...");`
</blockquote></details>

Done.

**Review by liorgold2 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2110)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2110#-:-NOF_DchCrza7SZGvLPn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2110)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
