### PR TITLE
Add statement attribute declaration to macro plugins.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4386)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4386)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4386#-NiodC9G2mUI7-wLro-o:-NiodC9G2mUI7-wLro-p:b-lefas8) (no related file):*
Change target branch.

___

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4386)* status: 0 of 14 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-plugins/src/plugins/fmt_config.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4386#-NipPDJI5da6-AcNFWwt:-NipPDJI5da6-AcNFWwu:b-fxmlmo) ([raw file](https://github.com/starkware-libs/cairo/blob/eb7849364a0f27f5a0e883578d467ca84244598a/crates/cairo-lang-plugins/src/plugins/fmt_config.rs#L11)):*
> ```XML
> const FMT_SKIP_ATTR: &str = "cairofmt::skip";
> 
> impl MacroPlugin for FormatterConfigPlugin {
> ```

rather have it in the default list - no need for a formatter plugin that doesn't actually do any actions to exist.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4386)* status: 0 of 14 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-plugins/src/plugins/fmt_config.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4386#-NipPDJI5da6-AcNFWwt:-Nj1pqP_BJnfYWJGdAb9:b-3jqmpl) ([raw file](https://github.com/starkware-libs/cairo/blob/eb7849364a0f27f5a0e883578d467ca84244598a/crates/cairo-lang-plugins/src/plugins/fmt_config.rs#L11)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rather have it in the default list - no need for a formatter plugin that doesn't actually do any actions to exist.
</blockquote></details>

Done. 
Maybe we want to drop this pr altogether and add it if there will be syntax attributes with content?
The only such attribute I can think off is `cfg`.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4386)* status: 0 of 14 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-plugins/src/plugins/fmt_config.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4386#-NipPDJI5da6-AcNFWwt:-Nj4RgTMBE_4Awih_fMw:b9vpxap) ([raw file](https://github.com/starkware-libs/cairo/blob/eb7849364a0f27f5a0e883578d467ca84244598a/crates/cairo-lang-plugins/src/plugins/fmt_config.rs#L11)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Done. 
Maybe we want to drop this pr altogether and add it if there will be syntax attributes with content?
The only such attribute I can think off is `cfg`.
</blockquote></details>

i'm for dropping it.

**Pull request closed without merging**
