### PR TITLE
Implement alloc box hint in the hint proccessor.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1810)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1810)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`corelib/test.cairo` line 420 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1810#-NM3vriECZD8lEz20RrC:-NM3vriF9d05wJ0epMlO:b1e3xu2) ([raw file](https://github.com/starkware-libs/cairo/blob/0a673f47f9431f7769167b30f5de45fba533caab/corelib/test.cairo#L420)):*
> ```Cairo
>     array_append::<felt>(arr, 11);
>     array_append::<felt>(arr, 12);
>     let boxed_arr = into_box::<Array::<felt>>(arr);
> ```

simplify - this should not include array.



_Code quote:_
```Cairo
    let x = 10;
    let boxed_x = into_box::<felt>(x);
    let mut arr = array_new::<felt>();
    array_append::<felt>(arr, 11);
    array_append::<felt>(arr, 12);
    let boxed_arr = into_box::<Array::<felt>>(arr);
    let y = 13;
    let boxed_y = into_box::<felt>(y);
    assert(unbox::<felt>(boxed_x)==10, 'x == 10');
    let mut unboxed_arr = unbox::<Array::<felt>>(boxed_arr);
    match array_at::<felt>(unboxed_arr, 0_u128) {
        Option::Some(x) => {assert(x == 11, 'arr[0] == 11');},
        Option::None(()) => {
            let mut data = array_new::<felt>();
            array_append::<felt>(data, 'array index OOB');
            panic(data)
        },
    }
    match array_at::<felt>(unboxed_arr, 1_u128) {
        Option::Some(x) => {assert(x == 12, 'arr[0] == 12');},
        Option::None(()) => {
            let mut data = array_new::<felt>();
            array_append::<felt>(data, 'array index OOB');
            panic(data)
        },
    }
    match array_at::<felt>(unboxed_arr, 2_u128) {
        Option::Some(x) => {
            let mut data = array_new::<felt>();
            array_append::<felt>(data, 'array index not OOB');
            panic(data)
        },
        Option::None(()) => {},
    }
    assert(unbox::<felt>(boxed_y)==13, 'y == 13');
```
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1810#-NM3w0gB-0x5EOL8vjTp:-NM3w0gB-0x5EOL8vjTq:b-69wsyh) ([raw file](https://github.com/starkware-libs/cairo/blob/0a673f47f9431f7769167b30f5de45fba533caab/crates/cairo-lang-runner/src/casm_run/mod.rs#L117)):*
> ```XML
> }
> 
> /// Execution scope for boxed variables memory management.
> ```

remove references to box.



_Code quote:_
```XML
/// Execution scope for boxed variables memory management.
struct BoxMemoryExecScope {
    /// The first free address for boxed variables.
    free_address: Relocatable,
```
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1810#-NM3vz5K45CbCzHMNT4d:-NM3vz5K45CbCzHMNT4e:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0a673f47f9431f7769167b30f5de45fba533caab/crates/cairo-lang-runner/src/casm_run/mod.rs#L120)):*
> ```XML
> struct BoxMemoryExecScope {
>     /// The first free address for boxed variables.
>     free_address: Relocatable,
> ```





_Suggestion:_
```XML
    next_address: Relocatable,
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1810)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`corelib/test.cairo` line 420 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1810#-NM3vriECZD8lEz20RrC:-NM4-iKg0211m7mtlgha:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0a673f47f9431f7769167b30f5de45fba533caab/corelib/test.cairo#L420)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

simplify - this should not include array.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1810#-NM3w0gB-0x5EOL8vjTp:-NM40SHqDjHzKZTp9-tM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0a673f47f9431f7769167b30f5de45fba533caab/crates/cairo-lang-runner/src/casm_run/mod.rs#L117)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove references to box.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1810#-NM3vz5K45CbCzHMNT4d:-NM40SWDAf0uu7HqnNkp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0a673f47f9431f7769167b30f5de45fba533caab/crates/cairo-lang-runner/src/casm_run/mod.rs#L120)):*
> ```XML
> struct BoxMemoryExecScope {
>     /// The first free address for boxed variables.
>     free_address: Relocatable,
> ```

Done.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1810)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1810#-NM42RAl3mvZh1e2vvCA:-NM42RAl3mvZh1e2vvCB:b-lefas8) (no related file):*
Change target branch.

___

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1810)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`corelib/test.cairo` line 414 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1810#-NM4Slzg4SYgrp9TLhkW:-NM4aP2p990gnnQDCq7k:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/06d8463caf62763c02c5f14a6e60416887b5c388/corelib/test.cairo#L414)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

split into different tests.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1810#-:-NM4hjqQB--Af43Tz8H6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
