### PR TITLE
Search asdf directories for scarb executable

### PR DESCRIPTION
**Pull request by szymmis**
Sometimes due to specific setup (like having custom ASDF_DATA_DIR variable) asdf scarb shim might not available through PATH variable. To solve this problem we can look for the executable in asdf directories as a fallback. Concept based on [what intellij does](https://github.com/JetBrains/intellij-community/blob/d81e9a70bc6ea0576646354c77fe0e25393db26a/platform/lang-impl/src/com/intellij/openapi/projectRoots/impl/JavaHomeFinderBasic.java#L359) when looking for java.

Worth noting that asdf is not supported on Windows machines outside WSL so when win32 platform is detected we just return undefined.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3665)

### CODE REVIEW

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3665)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware and @szymmis)

___
*[`vscode-cairo/src/extension.ts` line 111 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3665#-N_8hIvYALD3T0o5ah0R:-N_8hIvYALD3T0o5ah0S:btq9wan) ([raw file](https://github.com/starkware-libs/cairo/blob/a1dae998c2d1fbe8ee9a456d3fb33d4128ca246d/vscode-cairo/src/extension.ts#L111)):*
> ```XML
>   if (os.platform() === "win32") return undefined;
> 
>   const asdfDataDir = process.env.ASDF_DATA_DIR ?? `${process.env.HOME}/.asdf`;
> ```

+ I think I'd bail out (return undefined from this function) if HOME is empty



_Suggestion:_
```XML
path.join(process.env.HOME, ".asdf")
```
___
*[`vscode-cairo/src/extension.ts` line 117 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3665#-N_8h2Xa-WJjVfOGg4v0:-N_8h2Xa-WJjVfOGg4v1:b2nhkus) ([raw file](https://github.com/starkware-libs/cairo/blob/a1dae998c2d1fbe8ee9a456d3fb33d4128ca246d/vscode-cairo/src/extension.ts#L117)):*
> ```XML
>     .access(scarbExecutablePath, fs.constants.X_OK)
>     .then(() => scarbExecutablePath)
>     .catch(() => undefined);
> ```

Nit



_Suggestion:_
```XML
  try {
    return await fs.promises.access(scarbExecutablePath, fs.constants.X_OK);
  } catch _e {
    return undefined;
  }
```

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3665#-:-N_90LO49wpcyYCATcFm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3665#-:-Na6j7Ug3SL7b3BhOMIc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @szymmis)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3665#-:-NaCJWshDUR-DZV8Wj-b:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @szymmis)

**Pull request merged**
