### PR TITLE
LS: Add `Scheduler::local` utility

### PR DESCRIPTION
**Pull request by mkaput**
Co-authored-by: Piotr Figiela <77412592+draggu@users.noreply.github.com>

---

**Stack**:
- #6495
- #6494
- #6493 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Comment by lotem-starkware** [comment]
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6493)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6493#-:-O9HAYmS30uDnYr3tVAU:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @piotmag769)

**Review by piotmag769 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6493#-:-O9HEMdpBi7Fl_tmwEi_:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)

**Review by Arcticae — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6493#-:-O9JYxhXBMec2K3y6Boo:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Draggu)

**Review by Draggu — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6493#-:-O9K99S6CKvmClmFSAya:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Pull request merged**
