### PR TITLE
Move state outside of AddStoreVariableStatements.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This allows us to call AddStoreVariableStatements methods while holding a reference to variables in the state.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4214)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/store_variables/test.rs` line 597 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4214#-NfzNJSd9qOEq2Qu-XLg:-NfzNJSd9qOEq2Qu-XLh:bneokks) ([raw file](https://github.com/starkware-libs/cairo/blob/775b4f84e705293ded7b7cc203650eb983246842/crates/cairo-lang-sierra-generator/src/store_variables/test.rs#L597)):*
> ```XML
>     let statements: Vec<pre_sierra::Statement> = vec![
>         dummy_push_values(&db, &[("0", "100"), ("1", "101")]),
>         dummy_push_values(&db, &[("100", "200"), ("101", "201"), ("2", "202"), ("3", "203")]),
> ```

Let me know if you want me to try to create a smaller PR that catches that issue.

I wasn't able to do it in 10 min :)



_Code quote:_
```XML
  dummy_push_values(&db, &[("100", "200"), ("101", "201"), ("2", "202"), ("3", "203")]),
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4214)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4214#-NfzQLtF-1GbFeks77Y3:-NfzQLtG5XG7DtYa-yN2:baotgh6) ([raw file](https://github.com/starkware-libs/cairo/blob/5378983ad5bb0fffaeef1580104e3f63a942e81a/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L73)):*
> ```XML
>         None => State::default(),
>     }
> }
> ```

isn't calling `state.unwrap_or_default()` does the same thing?



_Code quote:_
```XML
pub fn unwrap_state(state: Option<State>) -> State {
    match state {
        Some(state) => state,
        None => State::default(),
    }
}
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4214)* status: 1 of 30 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4214#-Ng2_bBV2bJVS7kSayhy:-Ng2_bBV2bJVS7kSayhz:boxa6iu) (no related file):*
why the storing of possibly dropped variables is in a reverse order now?

___

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4214)* status: 1 of 30 files reviewed, 3 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4214#-Ng2_bBV2bJVS7kSayhy:-NgDl8ee3MWHlE4SIvtj:b2snfqe) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why the storing of possibly dropped variables is in a reverse order now?
</blockquote></details>

because we were using swap_remove.

___
___
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4214#-NfzQLtF-1GbFeks77Y3:-NgDltRYB2BkgRsaa1yV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5378983ad5bb0fffaeef1580104e3f63a942e81a/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L73)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

isn't calling `state.unwrap_or_default()` does the same thing?
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 28 of 28 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4214)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 99 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4214#-NgEK4s49u_yabLR3gs8:-NgEK4s49u_yabLR3gs9:b-ca7p7k) ([raw file](https://github.com/starkware-libs/cairo/blob/54b0695a58e4f82270663750925295665ca7763d/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L99)):*
> ```XML
>         statement: pre_sierra::Statement,
>         get_lib_func_signature: &GetLibfuncInfo,
>     ) -> Option<State>
> ```

Probably needs to be VariablesState or something similar, as now it is less clear than before.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4214)* status: 28 of 31 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 99 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4214#-NgEK4s49u_yabLR3gs8:-NgIDsNsEZdp5NrkL80Y:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/54b0695a58e4f82270663750925295665ca7763d/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L99)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Probably needs to be VariablesState or something similar, as now it is less clear than before.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4214#-:-NgIHidi5MLHy4fu1gMh:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`tests/e2e_test_data/libfuncs/poseidon` line 176 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4214#-NgIDznUBEfoeZMY4XmF:-NgIHZekEO7NPycn5alL:b-namhek) ([raw file](https://github.com/starkware-libs/cairo/blob/363fb5af66c48f60c352a8103e2e4781d121f3fc/tests/e2e_test_data/libfuncs/poseidon#L176)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

currently 
struct_construct<core::poseidon::HashState>([4], [5], [6], [8]) -> ([9]); // 5
followed by 
struct_deconstruct<core::poseidon::HashState>([9]) -> ([14], [15], [16], [17]); // 8
causes us to lose the state of the variables and assume that they are all deferred :(
</blockquote></details>

The sounds like a future optimization.

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4214)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
