### PR TITLE
Made module_data private

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1510)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 10 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1510)* status: 10 of 16 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/semantic/src/items/strct.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1510#-NKIr0zx3EMgUfV9rJ9l:-NKIr0zx3EMgUfV9rJ9m:b-1x517n) ([raw file](https://github.com/starkware-libs/cairo/blob/32fbe222bc5eb4cd7df011a4f4ad86ad9af3825c/crates/semantic/src/items/strct.rs#L79)):*
> ```XML
> /// Query implementation of [crate::db::SemanticGroup::priv_struct_semantic_data].
> pub fn priv_struct_semantic_data(db: &dyn SemanticGroup, struct_id: StructId) -> Maybe<StructData> {
>     // TODO(spapini): When asts are rooted on items, don't query module_data directly. Use a
> ```

Fix TODOs



_Code quote:_
```XML
asts are rooted
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1510)* status: 8 of 16 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/semantic/src/items/strct.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1510#-NKIr0zx3EMgUfV9rJ9l:-NKNwG1x6u6wCCVfczic:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/32fbe222bc5eb4cd7df011a4f4ad86ad9af3825c/crates/semantic/src/items/strct.rs#L79)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Fix TODOs
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 33 of 33 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1510#-:-NKO9ChBBXgSlQfCxH6T:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1510)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
