### PR TITLE
Fix statements functions for inline macros

### PR DESCRIPTION
**Pull request by piotmag769**
Before this a mapping for e.g. `array![1, 2, 3]` would have empty relative path

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5360)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5360)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @piotmag769)

___
*[`crates/cairo-lang-sierra-generator/src/statements_locations.rs` line 110 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5360#-Nuds4bcAywktOqsVMuK:-Nuds4bcAywktOqsVMuL:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b2fc4cf8cd93b587f8579e4dd86d185d23a9aaf9/crates/cairo-lang-sierra-generator/src/statements_locations.rs#L110)):*
> ```XML
> 
>     // If the statement is not located in a function, and it is located a generated file it is
>     // probably located in a code block generated by a macro like `array`, `panic` etc.
> ```





_Suggestion:_
```XML
    // probably located in a code block generated by an inline macro such as `array!` or `panic!`.
```

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5360)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/statements_locations.rs` line 110 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5360#-Nuds4bcAywktOqsVMuK:-NudtHnc85tDQN5UJ_7e:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b2fc4cf8cd93b587f8579e4dd86d185d23a9aaf9/crates/cairo-lang-sierra-generator/src/statements_locations.rs#L110)):*
> ```XML
> 
>     // If the statement is not located in a function, and it is located a generated file it is
>     // probably located in a code block generated by a macro like `array`, `panic` etc.
> ```

Done.

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5360)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/statements_locations.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5360#-Nudv1sH9Lt2Xy37T_sE:-Nudvj8I-LQlZ93hi-dp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c07351b2581a414d3a52f932fde1710e761d0cae/crates/cairo-lang-sierra-generator/src/statements_locations.rs#L110)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the etc i redundent.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5360#-:-NudwEHp3pvqXCejUHqa:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @piotmag769)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5360#-:-Nue-eKp3sskRj4d8Er2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @piotmag769)

**Pull request merged**
