### PR TITLE
Changed Starknet plugin to use pathcer.

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1598)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-starknet/src/plugin.rs` line 232 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1598#-NKlEzRz1p81JXrqkK-l:-NKlEzRz1p81JXrqkK-m:b-75ywm7) ([raw file](https://github.com/starkware-libs/cairo/blob/7d3f4746cdcffe3de3e7cc08ce47a9176a21df92/crates/cairo-starknet/src/plugin.rs#L232)):*
> ```XML
>     let mut diagnostics = vec![];
> 
>     let contract_name = RewriteNode::Copied(module_ast.name(db).token(db).as_syntax_node());
> ```

why is this needed?



_Code quote:_
```XML
token(db)
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1598)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-starknet/src/plugin.rs` line 244 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1598#-NKlEWd71tCGVbxKyVCx:-NKlEWd71tCGVbxKyVCy:bf2q47m) ([raw file](https://github.com/starkware-libs/cairo/blob/7d3f4746cdcffe3de3e7cc08ce47a9176a21df92/crates/cairo-starknet/src/plugin.rs#L244)):*
> ```XML
>                     || item_function.has_attr(db, VIEW_ATTR) =>
>             {
>                 external_declarations.push(RewriteNode::Modified(ModifiedNode {
> ```

This removes the attribute.

Add a todo to keep track of the attribute.



_Code quote:_
```XML
external_declarations.push(RewriteNode::Modified(ModifiedNode {
```
___
*[`crates/cairo-starknet/src/plugin.rs` line 281 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1598#-NKlFAVbBImLpIhM1xxQ:-NKlFAVbBImLpIhM1xxR:b-gtn8m4) ([raw file](https://github.com/starkware-libs/cairo/blob/7d3f4746cdcffe3de3e7cc08ce47a9176a21df92/crates/cairo-starknet/src/plugin.rs#L281)):*
> ```XML
>                     $generated_external_functions$
>                 }}
>             }}
> ```

why is the storage code not part of the generated module?



_Suggestion:_
```XML
            mod $contract_name$ {{
                $original_items$
                trait {ABI_TRAIT} {{
                    $external_declarations$
                }}

                mod {EXTERNAL_MODULE} {{
                    $generated_external_functions$
                }}
                
                $storage_code$
            }}
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1598)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1598)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-starknet/src/plugin.rs` line 232 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1598#-NKlEzRz1p81JXrqkK-l:-NKm0hUl40D2b0yKySM9:bymmwc5) ([raw file](https://github.com/starkware-libs/cairo/blob/7d3f4746cdcffe3de3e7cc08ce47a9176a21df92/crates/cairo-starknet/src/plugin.rs#L232)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why is this needed?
</blockquote></details>

I inlined it, if this is what you meant.
___
*[`crates/cairo-starknet/src/plugin.rs` line 244 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1598#-NKlEWd71tCGVbxKyVCx:-NKm1pQE0nSjx81q26tS:b-isg1u1) ([raw file](https://github.com/starkware-libs/cairo/blob/7d3f4746cdcffe3de3e7cc08ce47a9176a21df92/crates/cairo-starknet/src/plugin.rs#L244)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

This removes the attribute.

Add a todo to keep track of the attribute.


</blockquote></details>

This is for creating the ABI, I think I don't want to keep the rest of the attributes on the ABI declarations.
___
*[`crates/cairo-starknet/src/plugin.rs` line 281 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1598#-NKlFAVbBImLpIhM1xxQ:-NKm07Rk229JmU95PfMp:b-3fhv3t) ([raw file](https://github.com/starkware-libs/cairo/blob/7d3f4746cdcffe3de3e7cc08ce47a9176a21df92/crates/cairo-starknet/src/plugin.rs#L281)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why is the storage code not part of the generated module?
</blockquote></details>

this is a separate PR.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-starknet/src/plugin.rs` line 244 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1598#-NKlEWd71tCGVbxKyVCx:-NKm48hD13brr5_cWuBM:bxa6d7) ([raw file](https://github.com/starkware-libs/cairo/blob/7d3f4746cdcffe3de3e7cc08ce47a9176a21df92/crates/cairo-starknet/src/plugin.rs#L244)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

This is for creating the ABI, I think I don't want to keep the rest of the attributes on the ABI declarations.
</blockquote></details>

how do you know if a function is external or view in the abi? I guess we lack that feature?

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1598)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-starknet/src/plugin.rs` line 328 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1598#-NKm4NfD6s-djMtO8vXH:-NKm4NfEEsI2Dzrsm7ZX:b-l9wp41) ([raw file](https://github.com/starkware-libs/cairo/blob/866517dd14940aae1a6b10d57341c09662ba650c/crates/cairo-starknet/src/plugin.rs#L328)):*
> ```XML
>             (
>                 "contract_name".to_string(),
>                 RewriteNode::Copied(module_ast.name(db).token(db).as_syntax_node()),
> ```

why is the token necessary?



_Suggestion:_
```XML
module_ast.name(db).as_syntax_node()
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1598)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-starknet/src/plugin.rs` line 232 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1598#-NKlEzRz1p81JXrqkK-l:-NKm4RNK1bwobM9mhZSK:b2z1dv5) ([raw file](https://github.com/starkware-libs/cairo/blob/7d3f4746cdcffe3de3e7cc08ce47a9176a21df92/crates/cairo-starknet/src/plugin.rs#L232)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I inlined it, if this is what you meant.
</blockquote></details>

not really.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1598)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-starknet/src/plugin.rs` line 232 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1598#-NKlEzRz1p81JXrqkK-l:-NKm4kOOBM51W93gCrbB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7d3f4746cdcffe3de3e7cc08ce47a9176a21df92/crates/cairo-starknet/src/plugin.rs#L232)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

not really.
</blockquote></details>

Done.
___
*[`crates/cairo-starknet/src/plugin.rs` line 244 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1598#-NKlEWd71tCGVbxKyVCx:-NKm4ny9EUEQX5Qh2qZa:b-nhivzt) ([raw file](https://github.com/starkware-libs/cairo/blob/7d3f4746cdcffe3de3e7cc08ce47a9176a21df92/crates/cairo-starknet/src/plugin.rs#L244)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

how do you know if a function is external or view in the abi? I guess we lack that feature?
</blockquote></details>

Oh, keep track of this. OK, I added a TODO.
___
*[`crates/cairo-starknet/src/plugin.rs` line 328 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1598#-NKm4NfD6s-djMtO8vXH:-NKm5nTa7lmlj6QqYOsB:br1d4g3) ([raw file](https://github.com/starkware-libs/cairo/blob/866517dd14940aae1a6b10d57341c09662ba650c/crates/cairo-starknet/src/plugin.rs#L328)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why is the token necessary?
</blockquote></details>

it was to remove the trivia, before adding the formatting. With formatting it is not important.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1598#-:-NKmApvH68bgz3G45m_4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
