### PR TITLE
Improved performance for ecdsa.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4985)

### CODE REVIEW

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4985)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`corelib/src/ec.cairo` line 92 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4985#-NpnMUsN3ss8WM5RjrqC:-NpnMUsO7xHwsTj-rZu1:bb74c0o) ([raw file](https://github.com/starkware-libs/cairo/blob/e28ccf6561a20e9516ade54d0c7cef627534e283/corelib/src/ec.cairo#L92)):*
> ```Cairo
>         ec_state_add(ref self, :p);
>     }
>     /// Adds a point to the computation.
> ```

Subs



_Code quote:_
```Cairo
Adds
```
___
*[`corelib/src/ec.cairo` line 129 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4985#-NpnMmym4FOg96D-lhPd:-NpnMmym4FOg96D-lhPe:b-2uc5ym) ([raw file](https://github.com/starkware-libs/cairo/blob/e28ccf6561a20e9516ade54d0c7cef627534e283/corelib/src/ec.cairo#L129)):*
> ```Cairo
>         Option::Some(EcPointTrait::new_nz(:x, :y)?.into())
>     }
>     /// Creates a new EC point from its (x, y) coordinates.
> ```

Same below.



_Suggestion:_
```Cairo
new NonZero EC
```

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4985)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4985)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @ilyalesokhin-starkware)

___
*[`corelib/src/ec.cairo` line 92 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4985#-NpnMUsN3ss8WM5RjrqC:-NpnNroiAKEhPoslseuL:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e28ccf6561a20e9516ade54d0c7cef627534e283/corelib/src/ec.cairo#L92)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Subs
</blockquote></details>

Done.
___
*[`corelib/src/ec.cairo` line 129 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4985#-NpnMmym4FOg96D-lhPd:-NpnNs860yX0wcxfQJeO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e28ccf6561a20e9516ade54d0c7cef627534e283/corelib/src/ec.cairo#L129)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Same below.
</blockquote></details>

Done.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4985#-:-NpnPiUt5N2Y47CRXgXO:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4985)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/ecdsa.cairo` line 95 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4985#-NpoMbL5DD-XEJARr31u:-NpoMbL5DD-XEJARr31v:b-afxc9t) ([raw file](https://github.com/starkware-libs/cairo/blob/58700f5040b02931e034d9e6dd447f6a5949f116/corelib/src/ecdsa.cairo#L95)):*
> ```Cairo
> 
>     // Check the `(zG + rQ).x = sR.x` case.
>     let mut zG_plus_eQ_state = zG_state.clone();
> ```

why clone?



_Code quote:_
```Cairo
let mut zG_plus_eQ_state = zG_state.clone();
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4985)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/ecdsa.cairo` line 82 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4985#-NpoMQeC8mehX9IAJhFf:-NpoPOW022YK16zFFv3g:b-tars5w) ([raw file](https://github.com/starkware-libs/cairo/blob/58700f5040b02931e034d9e6dd447f6a5949f116/corelib/src/ecdsa.cairo#L82)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why clone instead of creating a new one?
</blockquote></details>

much cheaper - it is copyable - but would not like to let people use without noting the differences.

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/ecdsa.cairo` line 95 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4985#-NpoMbL5DD-XEJARr31u:-NpoQXYjD3R9ha1TCoGU:b-hrhklf) ([raw file](https://github.com/starkware-libs/cairo/blob/58700f5040b02931e034d9e6dd447f6a5949f116/corelib/src/ecdsa.cairo#L95)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why clone?
</blockquote></details>

nvm I see that you are using it twice.

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/ecdsa.cairo` line 108 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4985#-NpoQi5n6oBOJj-tNkEL:-NpoQi5oC8Ny-KO8A5Mr:b-cpobk) ([raw file](https://github.com/starkware-libs/cairo/blob/58700f5040b02931e034d9e6dd447f6a5949f116/corelib/src/ecdsa.cairo#L108)):*
> ```Cairo
> 
>     // Check the `(zG - rQ).x = sR.x` case.
>     let mut zG_minus_eQ_state = zG_state.clone();
> ```

Do you need to clone here? isn't this the last use?



_Code quote:_
```Cairo
zG_state.clone();
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4985)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/ecdsa.cairo` line 108 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4985#-NpoQi5n6oBOJj-tNkEL:-NpoSwMfB2HPW9FVr5ta:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/58700f5040b02931e034d9e6dd447f6a5949f116/corelib/src/ecdsa.cairo#L108)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Do you need to clone here? isn't this the last use?
</blockquote></details>

Done.

**Pull request merged**
