### PR TITLE
Add try_unpack_deref_with_offset and use it in build_pedersen_hash.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1219)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1219)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware, @liorgold2, and @yuvalsw)

___
*[`crates/sierra_to_casm/src/invocations/pedersen.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1219#-NIXhRRGC8SS6BZgeZqB:-NIXhRRGC8SS6BZgeZqC:b-19i1z9) ([raw file](https://github.com/starkware-libs/cairo/blob/fb52247b64bdeb4ed2c92cc480404de6f1537423/crates/sierra_to_casm/src/invocations/pedersen.rs#L50)):*
> ```XML
>     };
> 
>     if pedersen_offset > i16::MAX - 2 {
> ```

The pedersen offset can advance by 3, so shouldn't this be `pedersen_offset > i16::MAX - 3`?



_Code quote:_
```XML
if pedersen_offset > i16::MAX - 2
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1219)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @liorgold2, and @yuvalsw)

___
*[`crates/sierra_to_casm/src/invocations/pedersen.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1219#-NIXhRRGC8SS6BZgeZqB:-NIXi5cp76Uj8uZyfN20:b71kbx1) ([raw file](https://github.com/starkware-libs/cairo/blob/fb52247b64bdeb4ed2c92cc480404de6f1537423/crates/sierra_to_casm/src/invocations/pedersen.rs#L50)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

The pedersen offset can advance by 3, so shouldn't this be `pedersen_offset > i16::MAX - 3`?
</blockquote></details>

the code here only assumes that pedersen_offset + 2 <= i16::MAX .

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1219#-:-NIaRP-e2EzH-IV0fbZ0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware, @liorgold2, and @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1219#-:-NIabky4CWssPnYk2Pw4:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @ilyalesokhin-starkware, and @liorgold2)

___
*[`crates/sierra_to_casm/src/invocations/pedersen.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1219#-NIab8noB8WawP_fl6wn:-NIab8noB8WawP_fl6wo:b-625e7) ([raw file](https://github.com/starkware-libs/cairo/blob/04b5d77f81eca52966b4a2f1044e3719b09170ad/crates/sierra_to_casm/src/invocations/pedersen.rs#L51)):*
> ```XML
> 
>     if pedersen_offset > i16::MAX - 2 {
>         return Err(InvocationError::InvalidReferenceExpressionForArgument);
> ```

try to add test for failure here

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1219)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @liorgold2, and @yuvalsw)

___
*[`crates/sierra_to_casm/src/invocations/pedersen.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1219#-NIab8noB8WawP_fl6wn:-NIaeFc45WzebzjKxM19:b5d2vlk) ([raw file](https://github.com/starkware-libs/cairo/blob/04b5d77f81eca52966b4a2f1044e3719b09170ad/crates/sierra_to_casm/src/invocations/pedersen.rs#L51)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

try to add test for failure here
</blockquote></details>

seperate PR.

**Review by yuvalsw — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1219)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
