### PR TITLE
Move name into 'Parameter' struct.

### PR DESCRIPTION
**Pull request by liorgold2**
commit-id:8d219ca4

---

**Stack**:
- #1669
- #1668
- #1667 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1667#-:-NL5Zac090FxrBkwgDff:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1667)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/semantic.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1667#-NLKzjhj5fzF6unEB0fD:-NLL5B6071UQiugofx3-:btk84bg) ([raw file](https://github.com/starkware-libs/cairo/blob/ba4f05c0438afea3f20a6d5f3866b46b736c6c8b/crates/cairo-lang-semantic/src/semantic.rs#L44)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

`_` is not a parameter, it's a PatternOtherwise. Why do we need an Option here?
</blockquote></details>

`_` in the context of unnamed parameter.
See my changes to `ast_param_to_semantic`. It seems that we create the Parameter struct also when the name is `_`. Also, see test in #1668.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1667)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-semantic/src/semantic.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1667#-NLKzjhj5fzF6unEB0fD:-NLL9Vkg61itHaRHu3te:b-8pc5ta) ([raw file](https://github.com/starkware-libs/cairo/blob/ba4f05c0438afea3f20a6d5f3866b46b736c6c8b/crates/cairo-lang-semantic/src/semantic.rs#L44)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

`_` in the context of unnamed parameter.
See my changes to `ast_param_to_semantic`. It seems that we create the Parameter struct also when the name is `_`. Also, see test in #1668.
</blockquote></details>

Can we huddle over this?

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1667)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/semantic.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1667#-NLKzjhj5fzF6unEB0fD:-NLQQheNEIi4zH0azQVK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ba4f05c0438afea3f20a6d5f3866b46b736c6c8b/crates/cairo-lang-semantic/src/semantic.rs#L44)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Can we huddle over this?
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1667#-:-NLQWWiUBQ9Rum4n69gh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
