### PR TITLE
Merge remote-tracking branch 'origin/main' into 'sierra-minor-update'.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4285)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4285)* status: 1 of 9 files reviewed, all discussions resolved

**Review by ilyalesokhin-starkware — COMMENTED** [review]
Check r1 -> r2.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4285#-:-NhLBwSlBzM6gTPhX_8m:bn4mc9v)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @orizi and @yuvalsw)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 9 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4285#-:-NhLSoOkAaM5iM9xhGib:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4285)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1, 4 of 5 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4285)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/test/byte_array_test.cairo` line 478 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4285#-NhMGHavA-7Z1DKeTssp:-NhMGHavA-7Z1DKeTssq:b-nc2zsu) ([raw file](https://github.com/starkware-libs/cairo/blob/893ff84d5f503b882b0b3c511e792ba050419a93/corelib/src/test/byte_array_test.cairo#L478)):*
> ```Cairo
> 
> #[test]
> fn test_serde() {
> ```

defined twice.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4285)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @orizi and @yuvalsw)

___
*[`corelib/src/test/byte_array_test.cairo` line 478 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4285#-NhMGHavA-7Z1DKeTssp:-NhMKaYXE3Zy3S037IV2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/893ff84d5f503b882b0b3c511e792ba050419a93/corelib/src/test/byte_array_test.cairo#L478)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

defined twice.
</blockquote></details>

Done.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 1 of 9 files at r1, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4285#-:-NhMSi4AD0ieCDklKgf_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
