### PR TITLE
Moved contract expand tests into subdir

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3853)

### CODE REVIEW

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3853)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3853#-NbFDaMpERcRnPLSdiym:-NbFDaMpERcRnPLSdiyn:b7a62h7) (no related file):*
The new files are here, but I don't see them removed from the original location.

___

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3853)* status: 12 of 22 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3853#-NbFDaMpERcRnPLSdiym:-NbFbSFN2_0nffU9QXBp:b-896fix) (no related file):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

The new files are here, but I don't see them removed from the original location.
</blockquote></details>

Done.

___

**Review by orizi — APPROVED** [review]
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3853)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by yuvalsw — COMMENTED** [review]
> Dismissed @gilbens-starkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3853)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
