### PR TITLE
Add `pop_l2_to_l1_message` cheatcode

### PR DESCRIPTION
**Pull request by 0xChqrles**
Following the same implementation logic than `pop_log` cheatcode, this one allows to test L2 to L1 messaging feature.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3783)

### CODE REVIEW

**Comment by 0xChqrles** [comment]
👉👈

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3783)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @0xChqrles)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3783#-NaodspT6GdYEibzXUdl:-NaodspT6GdYEibzXUdm:b-miijju) ([raw file](https://github.com/starkware-libs/cairo/blob/b5eca3ad755e293626860c33f6dbd5f30ba89c4a/crates/cairo-lang-runner/src/casm_run/mod.rs#L135)):*
> ```XML
>     logs: HashMap<Felt252, VecDeque<Log>>,
>     /// A mapping from contract address to messages sent to L1.
>     l2_to_l1_messages: HashMap<Felt252, VecDeque<L2ToL1Message>>,
> ```

and add a structure containing both queues.



_Suggestion:_
```XML
    /// A mapping from contract address to logs.
    logs: HashMap<Felt252, ContractLogs>,
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3783)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @0xChqrles and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/l2_to_l1_messages.cairo` line 143 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3783#-Naoei8VAzg8YPzZrxRh:-Naoei8VAzg8YPzZrxRi:bk7b011) ([raw file](https://github.com/starkware-libs/cairo/blob/b5eca3ad755e293626860c33f6dbd5f30ba89c4a/crates/cairo-lang-starknet/cairo_level_tests/l2_to_l1_messages.cairo#L143)):*
> ```Cairo
>         !(*lhs == *rhs)
>     }
> }
> ```

rebase and remove - now exists in main.



_Code quote:_
```Cairo
impl SpanPartialEq<T, impl TPartialEq: PartialEq<T>, impl TCopy: Copy<T>, impl TDrop: Drop<T>> of PartialEq<Span<T>> {
    fn eq(lhs: @Span<T>, rhs: @Span<T>) -> bool {
        if ((*lhs).len() != (*rhs).len()) {
            // diff len

            false
        } else {
            // same len, we compare array content

            let mut eq = true;
            let mut i: usize = 0;
            let len = (*lhs).len();

            loop {
                if (i >= len) {
                    break;
                } else if (*(*lhs).at(i) != *(*rhs).at(i)) {
                    eq = false;
                    break;
                }

                i += 1;
            };

            eq
        }
    }

    fn ne(lhs: @Span<T>, rhs: @Span<T>) -> bool {
        !(*lhs == *rhs)
    }
}
```
___
*[`crates/cairo-lang-starknet/cairo_level_tests/l2_to_l1_messages.cairo` line 166 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3783#-NaoesdzAdX_lHxv6JG4:-NaoesdzAdX_lHxv6JG5:b-mn4ubj) ([raw file](https://github.com/starkware-libs/cairo/blob/b5eca3ad755e293626860c33f6dbd5f30ba89c4a/crates/cairo-lang-starknet/cairo_level_tests/l2_to_l1_messages.cairo#L166)):*
> ```Cairo
>         payload.span()
>     }
> }
> ```

make it a simple function - not a trait - as it is not really related.



_Suggestion:_
```Cairo
// generate_payload(n) -> [0, 1, 2, ..., n]
fn generate_payload(self: u128) -> Array<felt252> {
    let mut payload = array![];

    let mut i: u128 = 0;
    loop {
        if (i > *self) {
            break;
        }
        payload.append(i.into());
        i += 1;
    };
    payload
}
```

**Comment by 0xChqrles** [comment]
> and add a structure containing both queues.

Done.

**Comment by 0xChqrles** [comment]
> rebase and remove - now exists in main.

I can't find this impl in the corelib :/

**Review by orizi — COMMENTED** [review]
please answer in reviewable - so we'd be on the same thread.
Also - was just merged.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3783#-:-Napet7dCaY0-KSMcKlL:b-6w419w)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @0xChqrles and @spapinistarkware)

**Review by 0xChqrles — COMMENTED** [review]
Ok ! sorry 😅

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3783#-:-NapjKH2-kIw-wBD28ri:bvpgc89)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3783#-NaodspT6GdYEibzXUdl:-NapgOIh1kjzrN29nToi:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b5eca3ad755e293626860c33f6dbd5f30ba89c4a/crates/cairo-lang-runner/src/casm_run/mod.rs#L135)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

and add a structure containing both queues.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/l2_to_l1_messages.cairo` line 143 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3783#-Naoei8VAzg8YPzZrxRh:-NapjFDV47P9Yx9U6YJD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b5eca3ad755e293626860c33f6dbd5f30ba89c4a/crates/cairo-lang-starknet/cairo_level_tests/l2_to_l1_messages.cairo#L143)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rebase and remove - now exists in main.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/l2_to_l1_messages.cairo` line 166 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3783#-NaoesdzAdX_lHxv6JG4:-NapjFyw59AqJR9gv6rH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b5eca3ad755e293626860c33f6dbd5f30ba89c4a/crates/cairo-lang-starknet/cairo_level_tests/l2_to_l1_messages.cairo#L166)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

make it a simple function - not a trait - as it is not really related.
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3783)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @0xChqrles and @spapinistarkware)

**Review by 0xChqrles — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3783)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`corelib/src/starknet/testing.cairo` line 1 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3783#-Napqga72lMfzj-DpSvs:-Naq-7WF5P85cPnxiWFs:b4ioqzq) ([raw file](https://github.com/starkware-libs/cairo/blob/1d1e4de2e25e58267309634627672270a601875d/corelib/src/starknet/testing.cairo#L1)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why was this added?
</blockquote></details>

I initially planned to use `EthAddress` for `to_address` type before realising `felt252` would be better for the moment. Then I Just forgot to remove the import ^^
___
*[`crates/cairo-lang-starknet/cairo_level_tests/l2_to_l1_messages.cairo` line 60 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3783#-NapqnfxDXslExQTKtJ8:-Naq0Flo5Y3b2iA8MRYO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1d1e4de2e25e58267309634627672270a601875d/crates/cairo-lang-starknet/cairo_level_tests/l2_to_l1_messages.cairo#L60)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

put this out of the contract module - and not inside a trait.
this is just a helper function.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3783)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
:lgtm:
@spapinistarkware for 2nd eye.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3783#-:-Naq0xYe06b8Nhs2LFhH:bgvo56v)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by 0xChqrles — COMMENTED** [review]
okk it's done :ok_hand: 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3783#-:-NaqcxQa0VnF-QXx9IhA:b-gpsniv)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @orizi)

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, 2 of 3 files at r2, 1 of 1 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3783)* status: all files reviewed, 5 unresolved discussions (waiting on @0xChqrles)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/l2_to_l1_messages.cairo` line 10 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3783#-NatuQvRA03W2tp1Pvvq:-NatuQvRA03W2tp1Pvvr:b22lrd7) ([raw file](https://github.com/starkware-libs/cairo/blob/57e774b0853eba6f0e80d5fd2abecd92b3a0f908/crates/cairo-lang-starknet/cairo_level_tests/l2_to_l1_messages.cairo#L10)):*
> ```Cairo
> use test::test_utils::{ assert_eq, assert_ne };
> 
> // locals
> ```

Remove line
___
*[`crates/cairo-lang-starknet/cairo_level_tests/l2_to_l1_messages.cairo` line 18 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3783#-NatuPsh4DrnpPbfvm0X:-NatuPsh4DrnpPbfvm0Y:b22lrd7) ([raw file](https://github.com/starkware-libs/cairo/blob/57e774b0853eba6f0e80d5fd2abecd92b3a0f908/crates/cairo-lang-starknet/cairo_level_tests/l2_to_l1_messages.cairo#L18)):*
> ```Cairo
>     use array::ArrayTrait;
> 
>     // locals
> ```

Remove line
___
*[`crates/cairo-lang-starknet/cairo_level_tests/l2_to_l1_messages.cairo` line 47 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3783#-NatuIqr0rZlBoBGDgfK:-NatuIqr0rZlBoBGDgfL:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/57e774b0853eba6f0e80d5fd2abecd92b3a0f908/crates/cairo-lang-starknet/cairo_level_tests/l2_to_l1_messages.cairo#L47)):*
> ```Cairo
> 
> 
> // generate_payload(n) -> [0, 1, 2, ..., n]
> ```





_Suggestion:_
```Cairo
 Generates the array [0, 1, 2, ..., n]
```
___
*[`crates/cairo-lang-starknet/cairo_level_tests/l2_to_l1_messages.cairo` line 64 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3783#-NatuEOY7nlkZjdazklk:-NatuEOZ1EVncuU0Ib0V:bsasmda) ([raw file](https://github.com/starkware-libs/cairo/blob/57e774b0853eba6f0e80d5fd2abecd92b3a0f908/crates/cairo-lang-starknet/cairo_level_tests/l2_to_l1_messages.cairo#L64)):*
> ```Cairo
> }
> 
> //
> ```

Remove these 3 lines
___
*[`crates/cairo-lang-starknet/cairo_level_tests/l2_to_l1_messages.cairo` line 78 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3783#-Natu9ixEgIxPpFPBSp6:-Natu9ixEgIxPpFPBSp7:b-6jxt8y) ([raw file](https://github.com/starkware-libs/cairo/blob/57e774b0853eba6f0e80d5fd2abecd92b3a0f908/crates/cairo-lang-starknet/cairo_level_tests/l2_to_l1_messages.cairo#L78)):*
> ```Cairo
>     testing::set_contract_address(contract_address);
> 
>     // send messages
> ```

Use Capital at the beginning of a sentence, and end with ".", on all comments.

**Review by spapinistarkware — COMMENTED** [review]
Great, now fix the CI :)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3783#-:-NatupXB5j9H7lQdnXOh:b-ng25sn)* status: all files reviewed, 5 unresolved discussions (waiting on @0xChqrles)

**Review by 0xChqrles — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3783)* status: 3 of 6 files reviewed, 5 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/l2_to_l1_messages.cairo` line 10 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3783#-NatuQvRA03W2tp1Pvvq:-Naub29g-Eiu_0Jho6vo:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/57e774b0853eba6f0e80d5fd2abecd92b3a0f908/crates/cairo-lang-starknet/cairo_level_tests/l2_to_l1_messages.cairo#L10)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Remove line
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/l2_to_l1_messages.cairo` line 18 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3783#-NatuPsh4DrnpPbfvm0X:-Naub1lgBQcfqfmAMymW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/57e774b0853eba6f0e80d5fd2abecd92b3a0f908/crates/cairo-lang-starknet/cairo_level_tests/l2_to_l1_messages.cairo#L18)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Remove line
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/l2_to_l1_messages.cairo` line 47 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3783#-NatuIqr0rZlBoBGDgfK:-Naub1Q5DLZY_UlfTMQ7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/57e774b0853eba6f0e80d5fd2abecd92b3a0f908/crates/cairo-lang-starknet/cairo_level_tests/l2_to_l1_messages.cairo#L47)):*
> ```Cairo
> 
> 
> // generate_payload(n) -> [0, 1, 2, ..., n]
> ```

Done.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/l2_to_l1_messages.cairo` line 64 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3783#-NatuEOY7nlkZjdazklk:-Naub6dP6H3LqUXIzFFc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/57e774b0853eba6f0e80d5fd2abecd92b3a0f908/crates/cairo-lang-starknet/cairo_level_tests/l2_to_l1_messages.cairo#L64)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Remove these 3 lines
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/l2_to_l1_messages.cairo` line 78 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3783#-Natu9ixEgIxPpFPBSp6:-NaubGrqCE6fXflLPjzP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/57e774b0853eba6f0e80d5fd2abecd92b3a0f908/crates/cairo-lang-starknet/cairo_level_tests/l2_to_l1_messages.cairo#L78)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Use Capital at the beginning of a sentence, and end with ".", on all comments.
</blockquote></details>

Done.

**Review by 0xChqrles — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3783#-:-Nawt3X19Cn-Op6pwXmo:b-896fix)* status: 3 of 6 files reviewed, 5 unresolved discussions (waiting on @orizi and @spapinistarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3783)* status: all files reviewed, 5 unresolved discussions (waiting on @spapinistarkware)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3783#-:-NbJ80o717cNUTvlQ-aC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @0xChqrles)

**Pull request merged**
