### PR TITLE
Add initial references to StructuredBlock

### PR DESCRIPTION
**Pull request by spapinistarkware**
commit-id:c7eabc3d

---

**Stack**:
- #1659
- #1656 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1656)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1656#-NL0OsLK9-4rB9_SjnDc:-NL0OsLK9-4rB9_SjnDd:b13hmha) ([raw file](https://github.com/starkware-libs/cairo/blob/90dd4951727a1bf90b305c5ca2488ffac71257e7/crates/cairo-lang-lowering/src/lower/scope.rs#L23)):*
> ```XML
> #[derive(Default)]
> pub struct BlockScope {
>     current_refs: Vec<Option<VariableId>>,
> ```

document.



_Code quote:_
```XML
 current_refs: Vec<Option<VariableId>>,
```
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1656#-NL0PRTn150yqxc8gt-F:-NL0PRTn150yqxc8gt-G:buhl2gx) ([raw file](https://github.com/starkware-libs/cairo/blob/90dd4951727a1bf90b305c5ca2488ffac71257e7/crates/cairo-lang-lowering/src/lower/scope.rs#L82)):*
> ```XML
>         {
>             let index = ctx.implicits.len() + implicit_index;
>             ctx.variables[var.var_id()].ref_indices.insert(index);
> ```

what is an index of a reference variable?

I read the description here:
https://github.com/starkware-libs/cairo/blob/45c80201d2158f345d57db5ba0628f1292aad17c/crates/cairo-lang-lowering/src/objects.rs#L112

and I still don't get it.



_Code quote:_
```XML
ref_indices
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1656)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/fmt.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1656#-NL0Pu9p4R50fhS5oOLE:-NL0Pu9p4R50fhS5oOLF:b-nnobc8) ([raw file](https://github.com/starkware-libs/cairo/blob/90dd4951727a1bf90b305c5ca2488ffac71257e7/crates/cairo-lang-lowering/src/fmt.rs#L58)):*
> ```XML
>                 write!(f, ",")?;
>             }
>         }
> ```

Can  I see the result in a test?



_Code quote:_
```XML
        write!(f, "Initial refs:")?;
        let mut refs = self.initial_refs.iter().peekable();
        while let Some(var) = refs.next() {
            write!(f, " ")?;
            format_var_with_ty(*var, f, ctx)?;
            if refs.peek().is_some() {
                write!(f, ",")?;
            }
        }
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1656)* status: 2 of 32 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/fmt.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1656#-NL0Pu9p4R50fhS5oOLE:-NL0lbN1Dk_lDQxjGuTj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/90dd4951727a1bf90b305c5ca2488ffac71257e7/crates/cairo-lang-lowering/src/fmt.rs#L58)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Can  I see the result in a test?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1656#-NL0OsLK9-4rB9_SjnDc:-NL0bsqjEo9EjqQST5KD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/90dd4951727a1bf90b305c5ca2488ffac71257e7/crates/cairo-lang-lowering/src/lower/scope.rs#L23)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

document.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1656)* status: 2 of 32 files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1656#-NL0n2F91IJBrhQ8VNNN:-NL0n2F91IJBrhQ8VNNO:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/90dd4951727a1bf90b305c5ca2488ffac71257e7/crates/cairo-lang-lowering/src/lower/scope.rs#L75)):*
> ```XML
>         var: LivingVar,
>     ) {
>         if let Some((implicit_index, _)) = ctx
> ```

?



_Suggestion:_
```XML
ref_index
```
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1656#-NL0nJuIDwBKCoauU8na:-NL0nJuIDwBKCoauU8nb:b-pm94j6) ([raw file](https://github.com/starkware-libs/cairo/blob/90dd4951727a1bf90b305c5ca2488ffac71257e7/crates/cairo-lang-lowering/src/lower/scope.rs#L81)):*
> ```XML
>             .find(|(_, ref_semantic_var_id)| **ref_semantic_var_id == semantic_var_id)
>         {
>             let index = ctx.implicits.len() + implicit_index;
> ```

How are the implicits variables handled?



_Code quote:_
```XML
 let index = ctx.implicits.len() + implicit_index;
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1656)* status: 2 of 32 files reviewed, 3 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 453 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1656#-NL0niJJ97-_fBcY9eEP:-NL0niJJ97-_fBcY9eEQ:bca597j) ([raw file](https://github.com/starkware-libs/cairo/blob/90dd4951727a1bf90b305c5ca2488ffac71257e7/crates/cairo-lang-lowering/src/lower/scope.rs#L453)):*
> ```XML
>     ) -> Maybe<BlockSealed> {
>         let block_sealed = borrow_as_box(self, |merger| {
>             let current_refs = if let Some(parent) = merger.parent_scope.as_ref() {
> ```

can you add type annotation?



_Code quote:_
```XML
current_refs 
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 15 of 30 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1656)* status: 17 of 32 files reviewed, 4 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/test.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1656#-NL0p9BP3_WSV60DoCzi:-NL0p9BP3_WSV60DoCzj:b-h2rdni) ([raw file](https://github.com/starkware-libs/cairo/blob/398c1f6705b15b582286133806346d311e4d35e9/crates/cairo-lang-lowering/src/test.rs#L55)):*
> ```XML
>             format!("{:?}", structured_lowered.debug(&lowered_formatter)),
>         ),
>         ("lowering_flat".into(), format!("{:?}", flat_lowered.debug(&lowered_formatter))),
> ```

is there an example where lowering_structured != lowering_flat (when ignoring Initial refs)? 



_Code quote:_
```XML
            "lowering_structured".into(),
            format!("{:?}", structured_lowered.debug(&lowered_formatter)),
        ),
        ("lowering_flat".into(), format!("{:?}", flat_lowered.debug(&lowered_formatter))),
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1656)* status: 17 of 32 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/test.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1656#-NL0p9BP3_WSV60DoCzi:-NL0pigZ3JtFN1Y24Wvt:bmd9scb) ([raw file](https://github.com/starkware-libs/cairo/blob/398c1f6705b15b582286133806346d311e4d35e9/crates/cairo-lang-lowering/src/test.rs#L55)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

is there an example where lowering_structured != lowering_flat (when ignoring Initial refs)? 
</blockquote></details>

Right now they are the same. After I add the panic stage, they will start to diverge.
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1656#-NL0nJuIDwBKCoauU8na:-NL0pVfbBPRgmkdGyd94:bu0j0ss) ([raw file](https://github.com/starkware-libs/cairo/blob/90dd4951727a1bf90b305c5ca2488ffac71257e7/crates/cairo-lang-lowering/src/lower/scope.rs#L81)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

How are the implicits variables handled?
</blockquote></details>

in put_implicit()

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1656)* status: 17 of 32 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1656#-NL0n2F91IJBrhQ8VNNN:-NL0q7TE-z5JZgU3Eym2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/90dd4951727a1bf90b305c5ca2488ffac71257e7/crates/cairo-lang-lowering/src/lower/scope.rs#L75)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 453 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1656#-NL0niJJ97-_fBcY9eEP:-NL0q83w9-bUguYzFfp3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/90dd4951727a1bf90b305c5ca2488ffac71257e7/crates/cairo-lang-lowering/src/lower/scope.rs#L453)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

can you add type annotation?
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 7 of 30 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1656)* status: 25 of 32 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/test_data/extern` line 360 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1656#-NL0r4iF12Dr8F1SGbrX:-NL0r4iF12Dr8F1SGbrY:b7v0ta8) ([raw file](https://github.com/starkware-libs/cairo/blob/f66ffc23e4ea1e9232c10151ebd8b50ab44a8f7d/crates/cairo-lang-lowering/src/test_data/extern#L360)):*
> ```
> Statements:
>   (v19[r0]: core::RangeCheck, v20[r1]: core::felt, v18: test::MyEnum) <- match test::f(v0, v1, v2) {
>     (v3, v4, v5) => blk0,
> ```

what append here?



_Code quote:_
```
(v3, v4, v5) => blk0,
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1656)* status: 16 of 32 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/test_data/extern` line 360 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1656#-NL0r4iF12Dr8F1SGbrX:-NL0sp9h6rV8xAxNJ6hI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f66ffc23e4ea1e9232c10151ebd8b50ab44a8f7d/crates/cairo-lang-lowering/src/test_data/extern#L360)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what append here?
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 8 of 30 files at r2, 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1656#-:-NL0wbCc2uqBHGzOa6L8:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 30 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1656#-:-NL1PljW7eRboubTvv-X:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1656)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by ilyalesokhin-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1656)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/test_data/error_propagate` line 61 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1656#-NLKV-sJ4Nzj_KHmdILl:-NLKV-sJ4Nzj_KHmdILm:bs3n04n) ([raw file](https://github.com/starkware-libs/cairo/blob/7dde9c6969554ae107c663db7f73b59b9ea77ff5/crates/cairo-lang-lowering/src/test_data/error_propagate#L61)):*
> ```
>   }
>   (v8: core::integer::u128) <- match_enum(v4) {
>     Result::Ok => blk2,
> ```

is it possible to print the block inputs here?



_Code quote:_
```
blk2,
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1656)* status: 24 of 32 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/test_data/error_propagate` line 61 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1656#-NLKV-sJ4Nzj_KHmdILl:-NLKiHm89iLsWRe5Fi2z:b-yeyfwf) ([raw file](https://github.com/starkware-libs/cairo/blob/7dde9c6969554ae107c663db7f73b59b9ea77ff5/crates/cairo-lang-lowering/src/test_data/error_propagate#L61)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

is it possible to print the block inputs here?
</blockquote></details>

Possible. Harder. Is it necessary?

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, 14 of 30 files at r2, 1 of 1 files at r3, 7 of 10 files at r4, 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1656)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/test_data/error_propagate` line 61 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1656#-NLKV-sJ4Nzj_KHmdILl:-NLKieGH-CceOss-si54:b-tqa5r) ([raw file](https://github.com/starkware-libs/cairo/blob/7dde9c6969554ae107c663db7f73b59b9ea77ff5/crates/cairo-lang-lowering/src/test_data/error_propagate#L61)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Possible. Harder. Is it necessary?
</blockquote></details>

I put this as non blocking. But it is nice to have.

**Pull request merged**
