### PR TITLE
Add dict squash to the hint processor.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1713)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1713)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-runner/src/casm_run/dict_manager.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1713#-NLM37ZVCBBMdtEns0Wd:-NLM37ZVCBBMdtEns0We:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/603f5903a74970e9e886c12d6a3af2c5821ad3b1/crates/cairo-lang-runner/src/casm_run/dict_manager.rs#L92)):*
> ```XML
>         self.keys.last().cloned()
>     }
>     /// Returns and removes the current key, and its access indices. Should be called when only the
> ```





_Suggestion:_
```XML
}

/// Helper object for the managment of dict_squash hints.
#[derive(Default, Debug)]
pub struct DictSquashExecScope {
    /// A map from key to the list of indices accessing it, each list in reverse order.
    pub access_indices: HashMap<BigInt, Vec<BigInt>>,
    /// Descending list of keys.
    pub keys: Vec<BigInt>,
}
impl DictSquashExecScope {
    /// Returns the current key to process.
    pub fn current_key(&self) -> Option<BigInt> {
        self.keys.last().cloned()
    }
    
    /// Returns and removes the current key, and its access indices. Should be called when only the
    /// last key access is in the corresponding indices list.
    pub fn pop_current_key(&mut self) -> Option<BigInt> {
        let key_accesses = self.access_indices.remove(&self.current_key().unwrap());
        assert!(
            key_accesses.unwrap().len() == 1,
            "Key popped but not all accesses were processed."
        );
        self.keys.pop()
    }
    
    /// Returns a reference to the access indices list of the current key.
    pub fn current_access_indices(&mut self) -> Option<&mut Vec<BigInt>> {
        let current_key = self.current_key()?;
        self.access_indices.get_mut(&current_key)
    }
    
    /// Returns a reference to the last index in the current access indices list.
    pub fn current_access_index(&mut self) -> Option<&BigInt> {
        self.current_access_indices()?.last()
    }
    
    /// Returns and removes the current access index.
    pub fn pop_current_access_index(&mut self) -> Option<BigInt> {
        self.current_access_indices()?.pop()
    }
}
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1713)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/casm_run/dict_manager.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1713#-NLM37ZVCBBMdtEns0Wd:-NLQ4XkM9PEZW7MlPrKB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/603f5903a74970e9e886c12d6a3af2c5821ad3b1/crates/cairo-lang-runner/src/casm_run/dict_manager.rs#L92)):*
> ```XML
>         self.keys.last().cloned()
>     }
>     /// Returns and removes the current key, and its access indices. Should be called when only the
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1713#-:-NLQ5y2C9cVgy43SgxET:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1713)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
