### PR TITLE
Use Core::Result for EvalCircuitResult.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5853)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5853)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/test/circuit_test.cairo` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5853#-O08QEaL8MFy_WN8UkcM:-O08QEaL8MFy_WN8UkcN:b-nlutic) ([raw file](https://github.com/starkware-libs/cairo/blob/7fdc5697ed5fe044987203fb8e785ff4c93db8ce/corelib/src/test/circuit_test.cairo#L42)):*
> ```Cairo
>         Result::Ok(outputs) => { outputs },
>         Result::Err(_) => { panic!("Expected success") }
>     };
> ```

maybe?



_Suggestion:_
```Cairo
            .eval(modulus).unwrap();
```
___
*[`corelib/src/test/circuit_test.cairo` line 57 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5853#-O08QJ-G3N1UIFqamLH7:-O08QJ-HDk5BXsLNw2yk:b88473x) ([raw file](https://github.com/starkware-libs/cairo/blob/7fdc5697ed5fe044987203fb8e785ff4c93db8ce/corelib/src/test/circuit_test.cairo#L57)):*
> ```Cairo
> 
>     let modulus = TryInto::<_, CircuitModulus>::try_into([55, 0, 0, 0]).unwrap();
>     match (out0,).new_inputs().next([11, 0, 0, 0]).done().eval(modulus) {
> ```

here as well.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5853)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1881 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5853#-O08QMjI0kx-jo-b6FGT:-O08QMjI0kx-jo-b6FGU:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/7fdc5697ed5fe044987203fb8e785ff4c93db8ce/crates/cairo-lang-semantic/src/expr/compute.rs#L1881)):*
> ```XML
>             return Err(match long_ty {
>                 TypeLongId::Var(_) => skip_diagnostic(),
> ```

?

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5853)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/test/circuit_test.cairo` line 57 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5853#-O08QJ-G3N1UIFqamLH7:-O08fZf03aHhpn965NUX:bnh4bop) ([raw file](https://github.com/starkware-libs/cairo/blob/7fdc5697ed5fe044987203fb8e785ff4c93db8ce/corelib/src/test/circuit_test.cairo#L57)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

here as well.
</blockquote></details>

(with unwrap_err)

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/test/circuit_test.cairo` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5853#-O08QEaL8MFy_WN8UkcM:-O08eWEcE2fFPTDtWsCp:b-cc6jy5) ([raw file](https://github.com/starkware-libs/cairo/blob/7fdc5697ed5fe044987203fb8e785ff4c93db8ce/corelib/src/test/circuit_test.cairo#L42)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe?
</blockquote></details>

unwrap requires
+Drop<E>

I can try to change it to
+Destruct<E>
in a separate PR.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5853#-:-O08lt-Y5kbK5ZWzDnEq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1881 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5853#-O08QMjI0kx-jo-b6FGT:-O08eXFnDsHQqNVXA0JP:b-81taoq) ([raw file](https://github.com/starkware-libs/cairo/blob/7fdc5697ed5fe044987203fb8e785ff4c93db8ce/crates/cairo-lang-semantic/src/expr/compute.rs#L1881)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

reverted.

**Pull request merged**
