### PR TITLE
Fixed lowering of match statement such that the expression in or patterns is lowered once.

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4713)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4713)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1128 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4713#-Nn8s-9A9ni4WuJowTN-:-Nn8s-9BBF9HccT2U3jc:b8scffm) ([raw file](https://github.com/starkware-libs/cairo/blob/70119f9584e5cc5030bfdc07ca88f3a3c3241948/crates/cairo-lang-lowering/src/lower/mod.rs#L1128)):*
> ```XML
>     ctx: &mut LoweringContext<'_, '_>,
>     arms: &[semantic::MatchArm],
> ) -> Option<(usize, usize)> {
> ```

Fix doc.
Possibly make the return value a named struct as well.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1157 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4713#-Nn8wAhT3OOGhsNKeM3P:-Nn8wAhU4l8tD1J5Z075:bb73xfv) ([raw file](https://github.com/starkware-libs/cairo/blob/70119f9584e5cc5030bfdc07ca88f3a3c3241948/crates/cairo-lang-lowering/src/lower/mod.rs#L1157)):*
> ```XML
>     arms: impl Iterator<Item = &'a semantic::MatchArm>,
>     concrete_enum_id: semantic::ConcreteEnumId,
> ) -> LoweringResult<UnorderedHashMap<semantic::ConcreteVariant, (usize, usize)>> {
> ```

Same

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4713)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1128 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4713#-Nn8s-9A9ni4WuJowTN-:-Nn9-zDo2ZoAyPO5RpyJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/70119f9584e5cc5030bfdc07ca88f3a3c3241948/crates/cairo-lang-lowering/src/lower/mod.rs#L1128)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Fix doc.
Possibly make the return value a named struct as well.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1157 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4713#-Nn8wAhT3OOGhsNKeM3P:-Nn9-z1N-V1figQaO7Hf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/70119f9584e5cc5030bfdc07ca88f3a3c3241948/crates/cairo-lang-lowering/src/lower/mod.rs#L1157)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Same
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4713)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1125 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4713#-Nn9Smj1EGYCSYYKOkVL:-Nn9Smj1EGYCSYYKOkVM:bf9dh3k) ([raw file](https://github.com/starkware-libs/cairo/blob/82576d614645f45da2894594a12d43cb05498eab/crates/cairo-lang-lowering/src/lower/mod.rs#L1125)):*
> ```XML
> 
> /// The arm and pattern indices of a pattern in a match arm with an  or list.
> struct PatternIndex {
> ```

this is a bad name.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4713)* status: 1 of 10 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1131 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4713#-Nn9X1f4DUS-ebTTYwBP:-Nn9X1f4DUS-ebTTYwBQ:b-5qbzt) ([raw file](https://github.com/starkware-libs/cairo/blob/3751b6ab43f7ccf31053504fe781aa2d64c63005/crates/cairo-lang-lowering/src/lower/mod.rs#L1131)):*
> ```XML
> 
> /// Returns an option containing the PatternIndex of the underscore pattern, if it exists.
> fn get_underscore_pattern_index(
> ```

rename and fix doc.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1478 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4713#-Nn9Xmom0LQVKGB-cZX9:-Nn9Xmom0LQVKGB-cZXA:bppsw4z) ([raw file](https://github.com/starkware-libs/cairo/blob/3751b6ab43f7ccf31053504fe781aa2d64c63005/crates/cairo-lang-lowering/src/lower/mod.rs#L1478)):*
> ```XML
>                 .into_iter()
>                 .map(|(lowering_inner_pattern_result, subscope)| {
>                     let pattern = &ctx.function_body.patterns[arm.patterns[0]];
> ```

why is 0 fine here?
if it is an arbitrary choice - doc.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1622 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4713#-Nn9Y-mY5exahXjoBP9C:-Nn9Y-mY5exahXjoBP9D:bezlfvl) ([raw file](https://github.com/starkware-libs/cairo/blob/3751b6ab43f7ccf31053504fe781aa2d64c63005/crates/cairo-lang-lowering/src/lower/mod.rs#L1622)):*
> ```XML
>         expr.arms.last().unwrap().patterns.len() == 1,
>         "Only one pattern per arm is supported."
>     );
> ```

will it compile and crash here? or is it otherwise protected?
if not - diagnostic.



_Code quote:_
```XML
    assert!(
        expr.arms.last().unwrap().patterns.len() == 1,
        "Only one pattern per arm is supported."
    );
```
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 816 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4713#-Nn9YPvRC__hSa0kBMsS:-Nn9YPvRC__hSa0kBMsT:byg81ph) ([raw file](https://github.com/starkware-libs/cairo/blob/3751b6ab43f7ccf31053504fe781aa2d64c63005/crates/cairo-lang-semantic/src/expr/compute.rs#L816)):*
> ```XML
>                 // Typecheck pattern, and introduce the new variables to the subscope.
>                 // Note that if the arm expr is a block, there will be *another* subscope
>                 // for it.
> ```

is it actualy only a block?
`A::B | A::C => 3,`



_Code quote:_
```XML
                // Typecheck pattern, and introduce the new variables to the subscope.
                // Note that if the arm expr is a block, there will be *another* subscope
                // for it.
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4713)* status: 2 of 10 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1478 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4713#-Nn9Xmom0LQVKGB-cZX9:-NnApZ1z8lIlqqLDOVAf:bk235ih) ([raw file](https://github.com/starkware-libs/cairo/blob/3751b6ab43f7ccf31053504fe781aa2d64c63005/crates/cairo-lang-lowering/src/lower/mod.rs#L1478)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

It is used for the location of the block that destructs the pattern (and creates the variables) 
I am not sure if that location is important, if it is i guess it will be better to forward the correct pattern location to 
group\_match\_arms function
</blockquote></details>

Ok, so doc
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1622 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4713#-Nn9Y-mY5exahXjoBP9C:-NnApc4w43ABLy_qZQkt:bdmjvrd) ([raw file](https://github.com/starkware-libs/cairo/blob/3751b6ab43f7ccf31053504fe781aa2d64c63005/crates/cairo-lang-lowering/src/lower/mod.rs#L1622)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

it will crash, but diagnostic might also break existing code, I am currently working on a fix in another pr
</blockquote></details>

Diagnostic is better, there's no existing code based on release based on it.
If you have a working PR on it, a Todo is fine.
Panic is obviously a worse break of existing code than a diag.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4713)* status: 2 of 10 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 816 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4713#-Nn9YPvRC__hSa0kBMsS:-NnAq4334rmxR-iFPxwG:bow3szs) ([raw file](https://github.com/starkware-libs/cairo/blob/3751b6ab43f7ccf31053504fe781aa2d64c63005/crates/cairo-lang-semantic/src/expr/compute.rs#L816)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

semantically yes,
I think this is what the error refers to
</blockquote></details>

I am referring to the doc. It is incorrect.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4713)* status: 1 of 11 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1131 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4713#-Nn9X1f4DUS-ebTTYwBP:-NnE3WVo1XhUphjhKNWz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3751b6ab43f7ccf31053504fe781aa2d64c63005/crates/cairo-lang-lowering/src/lower/mod.rs#L1131)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rename and fix doc.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1478 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4713#-Nn9Xmom0LQVKGB-cZX9:-NnE3YVHCso_Tby4xWwV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3751b6ab43f7ccf31053504fe781aa2d64c63005/crates/cairo-lang-lowering/src/lower/mod.rs#L1478)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Ok, so doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1622 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4713#-Nn9Y-mY5exahXjoBP9C:-NnE3qtkDYOSA9vUDsN0:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3751b6ab43f7ccf31053504fe781aa2d64c63005/crates/cairo-lang-lowering/src/lower/mod.rs#L1622)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Diagnostic is better, there's no existing code based on release based on it.
If you have a working PR on it, a Todo is fine.
Panic is obviously a worse break of existing code than a diag.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 816 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4713#-Nn9YPvRC__hSa0kBMsS:-NnDvDou5OgI_ZmdiVYb:b-acwtmh) ([raw file](https://github.com/starkware-libs/cairo/blob/3751b6ab43f7ccf31053504fe781aa2d64c63005/crates/cairo-lang-semantic/src/expr/compute.rs#L816)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I am referring to the doc. It is incorrect.
</blockquote></details>

I don't understand, In the semantic level there is only one block created per arm ( unless the arm expr is also a block) ,
changed the comment a bit, but I don't think this is the error you meant.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4713)* status: 3 of 11 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 816 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4713#-Nn9YPvRC__hSa0kBMsS:-NnEGL6W64xAjcshebcT:b897lqp) ([raw file](https://github.com/starkware-libs/cairo/blob/3751b6ab43f7ccf31053504fe781aa2d64c63005/crates/cairo-lang-semantic/src/expr/compute.rs#L816)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

I don't understand, In the semantic level there is only one block created per arm ( unless the arm expr is also a block) ,
changed the comment a bit, but I don't think this is the error you meant.
</blockquote></details>

you keep saying block - my example is that this is not necessarily a block - it is an expression.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4713)* status: 3 of 11 files reviewed, all discussions resolved (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 816 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4713#-Nn9YPvRC__hSa0kBMsS:-NnEGVQb8Eawxd4K5tsl:b-mqitv5) ([raw file](https://github.com/starkware-libs/cairo/blob/3751b6ab43f7ccf31053504fe781aa2d64c63005/crates/cairo-lang-semantic/src/expr/compute.rs#L816)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you keep saying block - my example is that this is not necessarily a block - it is an expression.
</blockquote></details>

oh - i misunderstood the doc.

**Review by orizi — APPROVED** [review]
> Reviewed 7 of 10 files at r1, 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4713)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/match` line 539 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4713#-NnEHDsq19gO3qexe7ME:-NnEHDsq19gO3qexe7MF:b-akhluo) ([raw file](https://github.com/starkware-libs/cairo/blob/26d768c1df9b27f8d2882d1e7e0e002f4fcd5213/crates/cairo-lang-semantic/src/expr/semantic_test_data/match#L539)):*
> ```
>                         ty: <missing>,
>                     },
>                 ),
> ```

why did this disappear?



_Code quote:_
```
                expression: Missing(
                    ExprMissing {
                        ty: <missing>,
                    },
                ),
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4713)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 816 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4713#-Nn9YPvRC__hSa0kBMsS:-NnEN_vFA81VbaKMjHnv:b-f8oa7x) ([raw file](https://github.com/starkware-libs/cairo/blob/3751b6ab43f7ccf31053504fe781aa2d64c63005/crates/cairo-lang-semantic/src/expr/compute.rs#L816)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

oh - i misunderstood the doc.
</blockquote></details>

so the doc is correct right now?
___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/match` line 539 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4713#-NnEHDsq19gO3qexe7ME:-NnEN-nuENfl533EqSwl:b-di3r32) ([raw file](https://github.com/starkware-libs/cairo/blob/26d768c1df9b27f8d2882d1e7e0e002f4fcd5213/crates/cairo-lang-semantic/src/expr/semantic_test_data/match#L539)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why did this disappear?
</blockquote></details>

Before i created to separate arm, each had a missing variable so the arm expression type could not be computed,
Now there is one block with both variables.
Of course, there is still an error that the patterns mismatch, but the arm expression "believes" it has both variables

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4713)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1443 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4713#-NnZmtw0-KUHPwJ5uBzQ:-NnZmtw0-KUHPwJ5uBzR:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/eae4825d83b4eb83b602aff10b47a4ca9643e5ea/crates/cairo-lang-lowering/src/lower/mod.rs#L1443)):*
> ```XML
>     varinats_block_builders
>         .into_iter()
>         .sorted_by(|(arm_index_1, _, _), (arm_index_2, _, _)| arm_index_1.cmp(arm_index_2))
> ```





_Suggestion:_
```XML
        .sorted_by_key(|(arm_index, _, _)| arm_index)
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4713)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1443 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4713#-NnZmtw0-KUHPwJ5uBzQ:-Nn_CRdr3gF2q9jHFOCA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/eae4825d83b4eb83b602aff10b47a4ca9643e5ea/crates/cairo-lang-lowering/src/lower/mod.rs#L1443)):*
> ```XML
>     varinats_block_builders
>         .into_iter()
>         .sorted_by(|(arm_index_1, _, _), (arm_index_2, _, _)| arm_index_1.cmp(arm_index_2))
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4713#-:-Nn_ZqdP95BRkbhF0TBh:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4713)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
