### PR TITLE
Changed the protocol of starknet attributes

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4118)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 8 of 12 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4118)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/abi.rs` line 179 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4118#-Netecow5K3jTdfxufrr:-Netecow5K3jTdfxufrs:b-8l32ng) ([raw file](https://github.com/starkware-libs/cairo/blob/f5cdea4786ddab7c4c7c53be23f72afa7d5de4aa/crates/cairo-lang-starknet/src/abi.rs#L179)):*
> ```XML
>             let is_of_interface = db.impl_def_trait(impl_def)?.has_attr(db, INTERFACE_ATTR)?;
>             // TODO(v3): deprecate this.
>             // TODO(YG): v0?
> ```

These validations  happens at the syntax stage, no?

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4118)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/abi.rs` line 179 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4118#-Netecow5K3jTdfxufrr:-NfFKqsN8VSdTvzW6C1H:b2nign6) ([raw file](https://github.com/starkware-libs/cairo/blob/f5cdea4786ddab7c4c7c53be23f72afa7d5de4aa/crates/cairo-lang-starknet/src/abi.rs#L179)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

These validations  happens at the syntax stage, no?
</blockquote></details>

yes

**Review by orizi — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4118)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4118#-:-NfFSNch5xOy2vL-C633:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4118)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
