### PR TITLE
Derive StorageAccess for EthAddress and abi Dispatcher builtin types

### PR DESCRIPTION
**Pull request by maciejka**
Derive StorageAccess impl for Starknet builtin types: `u256`, `EthAddress`, `Dispatcher` using `derive(storage_access::StorageAccess)`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3247)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3247)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @maciejka)

___
*[`corelib/src/integer.cairo` line 929 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3247#-NWWI-Ie4ZgkVtjEHStJ:-NWWI-Ie4ZgkVtjEHStK:b-h1s19t) ([raw file](https://github.com/starkware-libs/cairo/blob/3d898aef665612f60e648ae20e924fe9ec623cf7/corelib/src/integer.cairo#L929)):*
> ```Cairo
> }
> 
> #[derive(Copy, Drop, PartialEq, Serde, storage_access::StorageAccess)]
> ```

this implementation is less efficient than the original - for core types i'd rather incur the extra implementation cost than the overhead.



_Code quote:_
```Cairo
, storage_access::StorageAccess
```
___
*[`corelib/src/starknet/eth_address.cairo` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3247#-NWWIJq1ASIHW2KTCRcS:-NWWIJq1ASIHW2KTCRcT:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/3d898aef665612f60e648ae20e924fe9ec623cf7/corelib/src/starknet/eth_address.cairo#L14)):*
> ```Cairo
>     fn try_into(self: felt252) -> Option<EthAddress> {
>         // TODO(yuval): change to a constant once u256 literals are supported.
>         let ETH_ADDRESS_BOUND = 1461501637330902918203684832716283019655932542976_u256; // 2 ** 160
> ```





_Suggestion:_
```Cairo
0x10000000000000000000000000000000000000000
```
___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 166 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3247#-NWWIkEb2FaYTyig0kD-:-NWWIkEb2FaYTyig0kD0:b-a3vjbh) ([raw file](https://github.com/starkware-libs/cairo/blob/3d898aef665612f60e648ae20e924fe9ec623cf7/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L166)):*
> ```XML
>             struct {library_caller_name} {{
>                 class_hash: starknet::ClassHash,
>             }}
> ```

adding these as storage access seems kinda weird to me - although i understand the sentiment.
@spapinistarkware WDYT? 



_Code quote:_
```XML
            #[derive(Copy, Drop, storage_access::StorageAccess)]
            struct {contract_caller_name} {{
                contract_address: starknet::ContractAddress,
            }}

            impl {contract_caller_name}Impl of {dispatcher_name}::<{contract_caller_name}> {{
            $contract_caller_method_impls$
            }}

            #[derive(Copy, Drop, storage_access::StorageAccess)]
            struct {library_caller_name} {{
                class_hash: starknet::ClassHash,
            }}
```

**Comment by maciejka** [comment]
> > ```cairo
> > #[derive(Copy, Drop, PartialEq, Serde, storage_access::StorageAccess)]
> > ```
> 
> this implementation is less efficient than the original - for core types i'd rather incur the extra implementation cost than the overhead.
> 
Because is uses `read/write_at_offset_internal` instead of `read/write` for the first `field`?
It should be possible to make `derive(, storage_access::StorageAccess)` generate code that is as efficient as manually generated one.

**Review by orizi — COMMENTED** [review]
so do so - and only after move to this impl.

> Reviewed 2 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3247#-:-NWWoNVE45Lksmd7itKB:b-vgfk7k)* status: 2 of 10 files reviewed, 2 unresolved discussions (waiting on @maciejka)

**Comment by maciejka** [comment]
> so do so - and only after move to this impl.

StorageAccess derivation optimization: https://github.com/starkware-libs/cairo/pull/3259

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 9 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3247#-:-NWmB1an1KpqS_xo-Hj5:bnfp4nl)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @maciejka)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3247)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciejka)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3247#-:-NWmKf9z69eBeMRuF81_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciejka)

**Pull request merged**
