### PR TITLE
Moved generated storage module of contracts into the module itself

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1604)

### CODE REVIEW

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1604)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1604#-NKmC9WY2gk4QXuKAcI6:-NKmC9WY2gk4QXuKAcI7:b-3yf84a) (no related file):*
change target branch

___

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1604)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-starknet/src/plugin_test_data/hello_starknet` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1604#-NKmDNfHEGAFSTn9C1Op:-NKmDNfHEGAFSTn9C1Oq:b3qok7z) ([raw file](https://github.com/starkware-libs/cairo/blob/287bf8dd52e6dd330e4d5f727dc85edf60f30a9f/crates/cairo-starknet/src/plugin_test_data/hello_starknet#L55)):*
> ```
>             )
>         }
>     }
> ```

consider adding a line break.



_Suggestion:_
```
    }
    
    trait __abi {
```

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1604#-:-NKmDRJGBNG7BX9hbSRk:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1604)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-starknet/src/plugin_test_data/hello_starknet` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1604#-NKmDNfHEGAFSTn9C1Op:-NKmEPQlEFQYtJaEUsWV:bkm91u8) ([raw file](https://github.com/starkware-libs/cairo/blob/287bf8dd52e6dd330e4d5f727dc85edf60f30a9f/crates/cairo-starknet/src/plugin_test_data/hello_starknet#L55)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

consider adding a line break.
</blockquote></details>

This is tricky - the formatter output for line break is not consistent - it depends on the input. Thus if I add a line break here I might have multiple line breaks which is ugly. We need to deal with it better, but for now I thought it's best to have only a singlelinebreak sometimes and not 3 linebreaks sometimes.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 11 files at r2, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1604#-:-NKmFt8a3z52i8pTNaB9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 3 of 10 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1604)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1604)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1604)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
