### PR TITLE
Added u8_from_felt.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:58710e84

---

**Stack**:
- #1866
- #1864
- #1863 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1863)* status: 2 of 9 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/uint.rs` line 212 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1863#-NMTeZ8S0kuIXz20_16p:-NMTeZ8S0kuIXz20_16q:br1mbls) ([raw file](https://github.com/starkware-libs/cairo/blob/0e5a5026f69f996e35ac472c6f6f2147b1fa0719/crates/cairo-lang-sierra-to-casm/src/invocations/uint.rs#L212)):*
> ```XML
>         jump IsSmall if is_small != 0;
>         tempvar res = value - limit;
>         // Here we want to make sure that `addr` > LIMIT and `res` < LIMIT,
> ```

fix comment.

why is there a PRIME  there?



_Suggestion:_
```XML
        // Here we want to make sure that `value` > LIMIT and `res` < LIMIT,
        // for that it is enough to show that `res` < PRIME - LIMIT.
        // We use the method described above with (A, B) = divmod(PRIME - LIMIT, 2**128 - 1)
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1863)* status: 2 of 9 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/uint.rs` line 212 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1863#-NMTeZ8S0kuIXz20_16p:-NMTfJbf8CzNgf4rkAUn:bnzrhgm) ([raw file](https://github.com/starkware-libs/cairo/blob/0e5a5026f69f996e35ac472c6f6f2147b1fa0719/crates/cairo-lang-sierra-to-casm/src/invocations/uint.rs#L212)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

fix comment.

why is there a PRIME  there?
</blockquote></details>

because the prime is the felt's prime.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-to-casm/src/invocations/uint.rs` line 212 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1863#-NMTeZ8S0kuIXz20_16p:-NMUlfjQECX_T_9mxCD2:b-1lf62t) ([raw file](https://github.com/starkware-libs/cairo/blob/0e5a5026f69f996e35ac472c6f6f2147b1fa0719/crates/cairo-lang-sierra-to-casm/src/invocations/uint.rs#L212)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

because the prime is the felt's prime.
</blockquote></details>

if 

 value = prime -1 then you are in this case but `res` > LIMIT.

I think you want to show something else.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1863)* status: 2 of 9 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/uint.rs` line 212 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1863#-NMTeZ8S0kuIXz20_16p:-NMUtSRP3GvTOE2DRNl7:b-omgwgy) ([raw file](https://github.com/starkware-libs/cairo/blob/0e5a5026f69f996e35ac472c6f6f2147b1fa0719/crates/cairo-lang-sierra-to-casm/src/invocations/uint.rs#L212)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

if 

 value = prime -1 then you are in this case but `res` > LIMIT.

I think you want to show something else.
</blockquote></details>

i don't understand what you are talking about.



_Code quote:_
```XML
 shifted_value
```

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 9 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1863#-:-NMXOwkH9ADjyjS17qSl:bnfp4nl)* status: 5 of 9 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/uint.rs` line 237 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1863#-NMXO9u0-TKVMXK5zxJp:-NMXO9u0-TKVMXK5zxJq:bm8a0ld) ([raw file](https://github.com/starkware-libs/cairo/blob/6587527484d44e890fce11eb51ad28613807fa46/crates/cairo-lang-sierra-to-casm/src/invocations/uint.rs#L237)):*
> ```XML
>         const fixer_limit = (u128::MAX - LIMIT + 1);
>         tempvar value_upper_limit = value + fixer_limit;
>         assert value_upper_limit = *(range_check++);
> ```

please add a comment

value + 2**128 - limit + 1 < 2**128 ==> value <= limit



_Code quote:_
```XML
        const fixer_limit = (u128::MAX - LIMIT + 1);
        tempvar value_upper_limit = value + fixer_limit;
        assert value_upper_limit = *(range_check++);
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1863)* status: 4 of 9 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/uint.rs` line 237 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1863#-NMXO9u0-TKVMXK5zxJp:-NMXlw2b9Sc_4AcckM5w:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6587527484d44e890fce11eb51ad28613807fa46/crates/cairo-lang-sierra-to-casm/src/invocations/uint.rs#L237)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

please add a comment

value + 2**128 - limit + 1 < 2**128 ==> value <= limit
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 4 of 9 files at r1, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1863)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
