### PR TITLE
Add intersperse to ModifiedNode

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4164)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4164)* status: 1 of 14 files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4164#-Nfdti3I9CMyaHEKBVMi:-Nfdti3I9CMyaHEKBVMj:b35eo7b) (no related file):*
i think just adding an `interspersed` function in `RewriteNode` is enough to remove a repeating call for `RewriteNode::new_modified(interspersed(....).collect())`- but the rest are just unneeded vector generation without a major addition to clarity.

___
___
*[`crates/cairo-lang-starknet/src/plugin/embeddable.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4164#-NfdqE5lACZdY5D4ERda:-NfdqE5lACZdY5D4ERdb:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/53619d196b7f15fccbfca6e6bf728238fe7fc3e3/crates/cairo-lang-starknet/src/plugin/embeddable.rs#L80)):*
> ```XML
>                 "::<$generic_args$>",
>                 &[("generic_args".to_string(), generic_args)].into(),
>             );
> ```





_Suggestion:_
```XML
            let generic_args = ModifiedNode::new_modified(
                chain!(
                    [RewriteNode::text("::<")],
                    intersperse(
                        chain!(
                            [RewriteNode::text(GENERIC_CONTRACT_STATE_NAME)],
                            elements.map(|param| {
                                param
                                    .name(db)
                                    .map(|name| RewriteNode::new_trimmed(name.as_syntax_node()))
                                    .unwrap_or_else(|| RewriteNode::text("_"))
                            })
                        ),
                        RewriteNode::text(", "),
                    ),
                    [RewriteNode::text(">")],
                ).collect()
            )
```
___
*[`crates/cairo-lang-starknet/src/plugin/storage.rs` line 283 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4164#-NfaYA-J28ER7IC0zSkU:-NfaYA-K6C6f4XFSiNlh:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/53619d196b7f15fccbfca6e6bf728238fe7fc3e3/crates/cairo-lang-starknet/src/plugin/storage.rs#L283)):*
> ```XML
>                     )
>                     .intersperse(RewriteNode::Text("::".to_string()))
>                     .into();
> ```





_Suggestion:_
```XML
                    let component_path = RewriteNode::interspersed(
                        path_prefix
                            .iter()
                            .map(|segment| RewriteNode::new_trimmed(segment.as_syntax_node())),
                        RewriteNode::text("::")
                    )
                    .intersperse(RewriteNode::Text("::".to_string()));
```
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs` line 367 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4164#-NfdsmIUExORJy4sWbFA:-NfdsmIUExORJy4sWbFB:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/53619d196b7f15fccbfca6e6bf728238fe7fc3e3/crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs#L367)):*
> ```XML
>     )
>     .insert_child(0, RewriteNode::Text(format!("{callsite_modifier}component")))
>     .intersperse(RewriteNode::Text(", ".to_string()));
> ```





_Suggestion:_
```XML
    let args_node = RewriteNode::interspersed(
        chain!(
            [RewriteNode::Text(format!("{callsite_modifier}component"))],
            rest_params.into_iter().map(|p| RewriteNode::Copied(p.name(db).as_syntax_node())),
        ),
        RewriteNode::text(", ")
    );
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4164)* status: 0 of 14 files reviewed, 4 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4164#-Nfdti3I9CMyaHEKBVMi:-NfejQIhElQ379XNUvBw:belppmn) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i think just adding an `interspersed` function in `RewriteNode` is enough to remove a repeating call for `RewriteNode::new_modified(interspersed(....).collect())`- but the rest are just unneeded vector generation without a major addition to clarity.
</blockquote></details>

changed to RewriteNode::interspersed() to create a new RewriteNode without creating intermediate vectors.

___
___
*[`crates/cairo-lang-starknet/src/plugin/embeddable.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4164#-NfdqE5lACZdY5D4ERda:-NfejPie9MEV6nsY0rKv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/53619d196b7f15fccbfca6e6bf728238fe7fc3e3/crates/cairo-lang-starknet/src/plugin/embeddable.rs#L80)):*
> ```XML
>                 "::<$generic_args$>",
>                 &[("generic_args".to_string(), generic_args)].into(),
>             );
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/storage.rs` line 283 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4164#-NfaYA-J28ER7IC0zSkU:-Nfeilgn--UnVtyFASjm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/53619d196b7f15fccbfca6e6bf728238fe7fc3e3/crates/cairo-lang-starknet/src/plugin/storage.rs#L283)):*
> ```XML
>                     )
>                     .intersperse(RewriteNode::Text("::".to_string()))
>                     .into();
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs` line 367 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4164#-NfdsmIUExORJy4sWbFA:-NfejOXqDN0IYBBph84M:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/53619d196b7f15fccbfca6e6bf728238fe7fc3e3/crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs#L367)):*
> ```XML
>     )
>     .insert_child(0, RewriteNode::Text(format!("{callsite_modifier}component")))
>     .intersperse(RewriteNode::Text(", ".to_string()));
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 14 files at r1, 5 of 8 files at r2, 4 of 18 files at r3, 13 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4164)* status: 17 of 18 files reviewed, 5 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-defs/src/patcher.rs` line 216 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4164#-Nfet6wT01iMO754HbP0:-Nfet6wT01iMO754HbP1:b-edqo60) ([raw file](https://github.com/starkware-libs/cairo/blob/c5466ca03ade2c09f56a18f40ad4cca45a606d49/crates/cairo-lang-defs/src/patcher.rs#L216)):*
> ```XML
> }
> impl ModifiedNode {
>     pub fn empty() -> Self {
> ```

Revert this - as unused.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs` line 311 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4164#-NfewfTMEbwWFrRv6yRM:-NfewfTMEbwWFrRv6yRN:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9c3be5ead8ff4f440f5745131170794c7ce05be9/crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs#L311)):*
> ```XML
>     .intersperse(RewriteNode::text("::"))
>     .into()
> }
> ```





_Suggestion:_
```XML
    RewriteNode::intersperse(
        chain!(
            prefix.iter().map(|x| RewriteNode::new_trimmed(x.as_syntax_node())),
            [last_without_generics],
        ),
        RewriteNode::text("::"),
    )
}
```
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs` line 398 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4164#-Nfex2u18c4bermYLUQd:-Nfex2u28EUceOOsVmwW:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9c3be5ead8ff4f440f5745131170794c7ce05be9/crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs#L398)):*
> ```XML
>             ("impl_path".to_string(), impl_path),
>             ("function_name".to_string(), function_name),
>             ("args_node".to_string(), args_node.into()),
> ```





_Suggestion:_
```XML
            ("args_node".to_string(), args_node),
```
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 525 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4164#-Nfex8rCDJ-LVMlfknSw:-Nfex8rCDJ-LVMlfknSx:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9c3be5ead8ff4f440f5745131170794c7ce05be9/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L525)):*
> ```XML
>     )
>     .intersperse(RewriteNode::text("::"))
>     .into();
> ```





_Suggestion:_
```XML
    let impl_module = RewriteNode::intersperse(
        impl_module
            .iter()
            .map(|segment| RewriteNode::new_trimmed(segment.as_syntax_node())),
        RewriteNode::text("::")
    );
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4164)* status: 17 of 18 files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-defs/src/patcher.rs` line 216 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4164#-Nfet6wT01iMO754HbP0:-NffB1iB5IpF-CKhQHJz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c5466ca03ade2c09f56a18f40ad4cca45a606d49/crates/cairo-lang-defs/src/patcher.rs#L216)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Revert this - as unused.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs` line 311 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4164#-NfewfTMEbwWFrRv6yRM:-NffBLig8Q4J-xr3svbq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9c3be5ead8ff4f440f5745131170794c7ce05be9/crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs#L311)):*
> ```XML
>     .intersperse(RewriteNode::text("::"))
>     .into()
> }
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs` line 398 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4164#-Nfex2u18c4bermYLUQd:-NffBUDN149FJ55c6u9i:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9c3be5ead8ff4f440f5745131170794c7ce05be9/crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs#L398)):*
> ```XML
>             ("impl_path".to_string(), impl_path),
>             ("function_name".to_string(), function_name),
>             ("args_node".to_string(), args_node.into()),
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 525 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4164#-Nfex8rCDJ-LVMlfknSw:-NffBpIZDRa5Kk43XWx9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9c3be5ead8ff4f440f5745131170794c7ce05be9/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L525)):*
> ```XML
>     )
>     .intersperse(RewriteNode::text("::"))
>     .into();
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4164#-:-NffOEor9G6wBD4zhaqU:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4164)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4164)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
