### PR TITLE
Add captured values to closure types.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6187)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6187)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 416 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6187#-O4EgfIk-i7hW8U_yvdq:-O4EgfIk-i7hW8U_yvdr:b-mjg97x) ([raw file](https://github.com/starkware-libs/cairo/blob/4f8d4ff1207dc47456dc297e4dae6f1757a8326a/crates/cairo-lang-semantic/src/types.rs#L416)):*
> ```XML
>     pub param_tys: Vec<TypeId>,
>     pub ret_ty: TypeId,
>     /// The set of types captured by the closure, we use vector as the fields needs to be hashable.
> ```

note specifically the fact that the type are deduped, and WHY you want this list.
deduped types are weird with a very specific reason.

**Review by TomerStarkware — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6187)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6187)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 416 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6187#-O4EgfIk-i7hW8U_yvdq:-O4EpIrd-v0pt6oZMTST:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4f8d4ff1207dc47456dc297e4dae6f1757a8326a/crates/cairo-lang-semantic/src/types.rs#L416)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

note specifically the fact that the type are deduped, and WHY you want this list.
deduped types are weird with a very specific reason.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6187#-:-O4EpnH740wT5RE5C0AG:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
