### PR TITLE
Add addmod and mulmod builtins.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5523)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5523)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/circuit.cairo` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5523#-NxRVC0H1_4jP6IvgM11:-NxRVC0H1_4jP6IvgM12:b-xwfchw) ([raw file](https://github.com/starkware-libs/cairo/blob/1d62ba1b72cc7a09f8c690f071a8d51b17a4ba13/corelib/src/circuit.cairo#L13)):*
> ```Cairo
> pub extern type RangeCheck96;
> pub extern type AddModBuiltin;
> pub extern type MulModBuiltin;
> ```

maybe?
(the current only builtin with such a name is the gas builtin)



_Suggestion:_
```Cairo
pub extern type CircuitAddMod;
pub extern type CircuitMulMod;
```

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/circuit.cairo` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5523#-NxRVC0H1_4jP6IvgM11:-NxRY9xAA2mrlHCHxnDK:b6j7nsm) ([raw file](https://github.com/starkware-libs/cairo/blob/1d62ba1b72cc7a09f8c690f071a8d51b17a4ba13/corelib/src/circuit.cairo#L13)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe?
(the current only builtin with such a name is the gas builtin)
</blockquote></details>

We have the following code:
https://github.com/starkware-libs/cairo/blob/e5f05e75c6960786d36fddad898e954c97e89d33/crates/cairo-lang-starknet-classes/src/casm_contract_class.rs#L514

Which requires the types to be called
AddMod and MulMod, but I guess we could add indirection there to fix the names.

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5523)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5523)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/circuit.cairo` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5523#-NxRVC0H1_4jP6IvgM11:-NxR_Rn17xYbUELzTvrW:b-gafhpy) ([raw file](https://github.com/starkware-libs/cairo/blob/1d62ba1b72cc7a09f8c690f071a8d51b17a4ba13/corelib/src/circuit.cairo#L13)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

We have the following code:
https://github.com/starkware-libs/cairo/blob/e5f05e75c6960786d36fddad898e954c97e89d33/crates/cairo-lang-starknet-classes/src/casm_contract_class.rs#L514

Which requires the types to be called
AddMod and MulMod, but I guess we could add indirection there to fix the names.
</blockquote></details>

so it doesn't work in any case.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5523)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/circuit.cairo` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5523#-NxRVC0H1_4jP6IvgM11:-NxRozZm4vfBbSe0ikNC:b-s7vgag) ([raw file](https://github.com/starkware-libs/cairo/blob/1d62ba1b72cc7a09f8c690f071a8d51b17a4ba13/corelib/src/circuit.cairo#L13)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

so it doesn't work in any case.
</blockquote></details>

so for now probably `AddMod` `MulMod`.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5523)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/circuit.cairo` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5523#-NxRVC0H1_4jP6IvgM11:-NxRvIxh9mp9Cm5JyrSt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1d62ba1b72cc7a09f8c690f071a8d51b17a4ba13/corelib/src/circuit.cairo#L13)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

so for now probably `AddMod` `MulMod`.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5523#-:-NxS11A156buaEWoWU7P:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
