### PR TITLE
interned impl id

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5773)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 8 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5773)* status: 8 of 18 files reviewed, 1 unresolved discussion (waiting on @mkaput and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 1194 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5773#-O-1jjwn221-XKjOvi5x:-O-1jjwoBFFgzTzpTP0c:b89lymz) ([raw file](https://github.com/starkware-libs/cairo/blob/0ad0b61ed573649ff98fbe2c37f4038d2c5ee78c/crates/cairo-lang-semantic/src/expr/inference.rs#L1194)):*
> ```XML
>             }
>         }
>         if value.clone().intern(self.db).is_var_free(self.db) {
> ```

make is_var_free and is_fully_concrete work on LongId as well.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 8 of 18 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5773)* status: all files reviewed, 5 unresolved discussions (waiting on @mkaput and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference/canonic.rs` line 320 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5773#-O-FcD0uCkD8a4AidDgw:-O-FcD0uCkD8a4AidDgx:bpdaghm) ([raw file](https://github.com/starkware-libs/cairo/blob/cbefe98be4d14a62c8124496ec1b5f4f3cefc0ef/crates/cairo-lang-semantic/src/expr/inference/canonic.rs#L320)):*
> ```XML
> impl<'a, 'b> SemanticRewriter<ImplLongId, NoError> for Embedder<'a, 'b> {
>     fn internal_rewrite(&mut self, value: &mut ImplLongId) -> Result<RewriteResult, NoError> {
>         let ImplLongId::ImplVar(var_id) = value else {
> ```

move this check to a rewrite impl for `ImplId`.
___
*[`crates/cairo-lang-semantic/src/expr/inference/canonic.rs` line 335 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5773#-O-FautXEivcryA96j71:-O-FautXEivcryA96j72:b-183pjx) ([raw file](https://github.com/starkware-libs/cairo/blob/cbefe98be4d14a62c8124496ec1b5f4f3cefc0ef/crates/cairo-lang-semantic/src/expr/inference/canonic.rs#L335)):*
> ```XML
>         });
>         let x = self.inference.impl_vars[new_id.0].clone().intern(self.get_db());
>         *value = ImplLongId::ImplVar(x);
> ```

why is the clone required?

ImplVar::clone accepts `&self` sot eh line should have been the same.



_Code quote:_
```XML
        let x = self.inference.impl_vars[new_id.0].clone().intern(self.get_db());
        *value = ImplLongId::ImplVar(x);
```
___
*[`crates/cairo-lang-semantic/src/expr/inference/canonic.rs` line 366 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5773#-O-FcZjm3YAILUa2LFGc:-O-FcZjm3YAILUa2LFGd:b-ggnely) ([raw file](https://github.com/starkware-libs/cairo/blob/cbefe98be4d14a62c8124496ec1b5f4f3cefc0ef/crates/cairo-lang-semantic/src/expr/inference/canonic.rs#L366)):*
> ```XML
>     }
> }
> add_basic_rewrites!(<'a>, Mapper<'a>, MapperError, @exclude TypeLongId TypeId ImplLongId ConstValue);
> ```

100 chars limit.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 204 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5773#-O-FbsLZ1gvzIPoEQcrf:-O-FbsLZ1gvzIPoEQcrg:b-qlwb6e) ([raw file](https://github.com/starkware-libs/cairo/blob/cbefe98be4d14a62c8124496ec1b5f4f3cefc0ef/crates/cairo-lang-semantic/src/items/imp.rs#L204)):*
> ```XML
>         }
>     }
>     pub fn is_var_free(&self, db: &dyn SemanticGroup) -> bool {
> ```

add the relevant doc here as well.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 211 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5773#-O-FbpdaEcNzePibDk6Z:-O-FbpdaEcNzePibDk6_:b-qlwb6e) ([raw file](https://github.com/starkware-libs/cairo/blob/cbefe98be4d14a62c8124496ec1b5f4f3cefc0ef/crates/cairo-lang-semantic/src/items/imp.rs#L211)):*
> ```XML
>         }
>     }
>     pub fn is_fully_concrete(&self, db: &dyn SemanticGroup) -> bool {
> ```

add the relevant doc here as well.

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 15 of 18 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5773#-:-O-FlzGeASWNx9TkhMZj:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5773)* status: 16 of 18 files reviewed, 5 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/inference/canonic.rs` line 320 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5773#-O-FcD0uCkD8a4AidDgw:-O-ksI7Z7K_lhsoNFNeS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cbefe98be4d14a62c8124496ec1b5f4f3cefc0ef/crates/cairo-lang-semantic/src/expr/inference/canonic.rs#L320)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

move this check to a rewrite impl for `ImplId`.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/inference/canonic.rs` line 335 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5773#-O-FautXEivcryA96j71:-O-ksZ1L7gQOUZc_QWzl:bebcd86) ([raw file](https://github.com/starkware-libs/cairo/blob/cbefe98be4d14a62c8124496ec1b5f4f3cefc0ef/crates/cairo-lang-semantic/src/expr/inference/canonic.rs#L335)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why is the clone required?

ImplVar::clone accepts `&self` sot eh line should have been the same.
</blockquote></details>

Done.  it will still call clone function though
___
*[`crates/cairo-lang-semantic/src/expr/inference/canonic.rs` line 366 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5773#-O-FcZjm3YAILUa2LFGc:-O-ksdQU9RcDK2vC-xzo:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cbefe98be4d14a62c8124496ec1b5f4f3cefc0ef/crates/cairo-lang-semantic/src/expr/inference/canonic.rs#L366)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

100 chars limit.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 204 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5773#-O-FbsLZ1gvzIPoEQcrf:-O-ksnuMCJiSmRkufYk-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cbefe98be4d14a62c8124496ec1b5f4f3cefc0ef/crates/cairo-lang-semantic/src/items/imp.rs#L204)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add the relevant doc here as well.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 211 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5773#-O-FbpdaEcNzePibDk6Z:-O-ksvFkEm0If8fX1EWV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cbefe98be4d14a62c8124496ec1b5f4f3cefc0ef/crates/cairo-lang-semantic/src/items/imp.rs#L211)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add the relevant doc here as well.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5773#-:-O-oa_qy9t3gs0AflVaE:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5773)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
