### PR TITLE
Keep track of binding location in SemanticLoweringMapping.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3646)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/block_builder.rs` line 267 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3646#-N_E4d3X7ZoeZB4YNYfD:-N_E4d3X7ZoeZB4YNYfE:b-mn2oe5) ([raw file](https://github.com/starkware-libs/cairo/blob/87b81392461aa6256fe787830ca76a3ef1734cff/crates/cairo-lang-lowering/src/lower/block_builder.rs#L267)):*
> ```XML
> pub struct SemanticRemapping {
>     expr: Option<VariableId>,
>     semantics: OrderedHashMap<semantic::VarId, VarUsage>,
> ```

Does this make sense?

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3646#-:-N_E6BI21NFR-Vv4BAXR:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/block_builder.rs` line 267 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3646#-N_E4d3X7ZoeZB4YNYfD:-N_E5dDa1Y64InXgJvI7:bx3525w) ([raw file](https://github.com/starkware-libs/cairo/blob/87b81392461aa6256fe787830ca76a3ef1734cff/crates/cairo-lang-lowering/src/lower/block_builder.rs#L267)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Does this make sense?
</blockquote></details>

if each variable in the semantic model matches a var usage for lowering - yes.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3646)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 332 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3646#-N_E9ivrCmFGn3mJbvUM:-N_E9ivrCmFGn3mJbvUN:b-u1dphf) ([raw file](https://github.com/starkware-libs/cairo/blob/fe11bd69cf7c0365ae0d60d3cc445a0cec7fae02/crates/cairo-lang-lowering/src/lower/context.rs#L332)):*
> ```XML
>                     let var_usage = ctx.new_var_usage(VarRequest {
>                         ty: member_path.ty(),
>                         location: self.location,
> ```

What location should I use here?
the member path or self.location?



_Code quote:_
```XML
 location: self.location,
```

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3646)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 332 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3646#-N_E9ivrCmFGn3mJbvUM:-N_EEBL07GZ_ts2b_acA:b1xaj9j) ([raw file](https://github.com/starkware-libs/cairo/blob/fe11bd69cf7c0365ae0d60d3cc445a0cec7fae02/crates/cairo-lang-lowering/src/lower/context.rs#L332)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

What location should I use here?
the member path or self.location?
</blockquote></details>

i think the member itself would be more specific.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 332 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3646#-N_E9ivrCmFGn3mJbvUM:-N_EGC_MEMyu24m3FQwg:b-grcx4a) ([raw file](https://github.com/starkware-libs/cairo/blob/fe11bd69cf7c0365ae0d60d3cc445a0cec7fae02/crates/cairo-lang-lowering/src/lower/context.rs#L332)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i think the member itself would be more specific.
</blockquote></details>

I'm not sure if the member_path is in the definition or the callsite.

**Comment by ilyalesokhin-starkware** [comment]
Wrong approach.

when we have
self.a = 5;

The BlockStructRecomposer should keep the location
`self.a`
not 
`5`

**Pull request closed without merging**
