### PR TITLE
fix: fix parity-scale-codec hint index

### PR DESCRIPTION
**Pull request by dan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5985)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5985)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5985#-O1N-CPD06wlyNrV1Lqi:-O1N-CPD06wlyNrV1Lqj:b-ua8feh) (no related file):*
so it would be in the next release - target `dev-v2.7.0` instead.

___
___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 288 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5985#-O1N-3aZ8LkD-PaiPeJc:-O1N-3aZ8LkD-PaiPeJd:b-6qbrnl) ([raw file](https://github.com/starkware-libs/cairo/blob/42cfe293eb45f00772c68a49b320e5cedc472249/crates/cairo-lang-casm/src/hints/mod.rs#L288)):*
> ```XML
>     },
> 
>     #[cfg_attr(feature = "parity-scale-codec", codec(index = 28))]
> ```

maybe just makes this the 29 - or is it already committed to 28 here?



_Code quote:_
```XML
    #[cfg_attr(feature = "parity-scale-codec", codec(index = 28))]
```

**Review by dan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5985)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 288 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5985#-O1N-3aZ8LkD-PaiPeJc:-O1N3jQx1CcNjmnXB5kc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/42cfe293eb45f00772c68a49b320e5cedc472249/crates/cairo-lang-casm/src/hints/mod.rs#L288)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe just makes this the 29 - or is it already committed to 28 here?
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5985)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

**Review by dan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5985)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5985#-O1N-CPD06wlyNrV1Lqi:-O1N592a2GqGlRNRwSlP:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

so it would be in the next release - target `dev-v2.7.0` instead.
</blockquote></details>

Done.

___

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5985#-:-O1N5nKa1Emml6o1D1NQ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by dan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5985)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`-- commits` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5985#-O1N65To8rFajSnUW2Jv):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rebase and make sure you only have the single relevant commit.
</blockquote></details>

Done.

**Pull request merged**
