### PR TITLE
Add branch_inversion optimization.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3604)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3604)* status: 0 of 27 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/test.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3604#-NZaZdCr77AlBbaOjx4M:-NZaZdCr77AlBbaOjx4N:b-5klmql) ([raw file](https://github.com/starkware-libs/cairo/blob/3a4e18f8ed88e0542ae333da72378101ff00859c/crates/cairo-lang-lowering/src/test.rs#L143)):*
> ```XML
> 
>     let mut after_branch_inversion = after_reorder_statements1.clone();
>     branch_inversion(&db, &mut after_branch_inversion);
> ```

print new phase



_Code quote:_
```XML
    let mut after_branch_inversion = after_reorder_statements1.clone();
    branch_inversion(&db, &mut after_branch_inversion);
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/test_data/hello_starknet.sierra` line 181 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3604#-NZa_EPSC5gbJgK8gOAY:-NZa_EPSC5gbJgK8gOAZ:b-3vt77q) ([raw file](https://github.com/starkware-libs/cairo/blob/3a4e18f8ed88e0542ae333da72378101ff00859c/crates/cairo-lang-starknet/test_data/hello_starknet.sierra#L181)):*
> ```
> enum_init<core::bool, 1>([25]) -> ([26]);
> store_temp<core::bool>([26]) -> ([24]);
> enum_match<core::bool>([24]) { fallthrough([27]) 49([28]) };
> ```

need to check why there is no match_optimization here.



_Code quote:_
```
enum_init<core::bool, 1>([25]) -> ([26]);
store_temp<core::bool>([26]) -> ([24]);
enum_match<core::bool>([24]) { fallthrough([27]) 49([28]) };
```

**Review by orizi — COMMENTED** [review]
> Reviewed 27 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3604)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 24 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3604)* status: 7 of 28 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 351 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3604#-NZaabKL0z3nyRv07Thp:-NZaabKL0z3nyRv07Thq:b-8hg1ma) ([raw file](https://github.com/starkware-libs/cairo/blob/d072fc310e78d2a7125e0b3d02c1a07de541162d/crates/cairo-lang-lowering/src/db.rs#L351)):*
> ```XML
>     optimize_remappings(&mut lowered);
>     reorder_statements(db, &mut lowered);
>     branch_inversion(db, &mut lowered);
> ```

doc why somewhere

**Comment by ilyalesokhin-starkware** [comment]
*[`tests/test_data/testing.sierra` line 15 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3604#-NZf4AscCXtN1GCppFFc:-NZf4AscCXtN1GCppFFd:bvs28uy) ([raw file](https://github.com/starkware-libs/cairo/blob/565a0a25e0453f6a96cd64b65a596e45878533ec/tests/test_data/testing.sierra#L15)):*
> ```
> 
> struct_construct<Unit>() -> ([0]);
> struct_construct<Tuple<Unit>>([0]) -> ([1]);
> ```

This test is almost entirely optimized out now
https://github.com/starkware-libs/cairo/blob/62d94330d6dd06c210499e931fc0a9e964b8633a/examples/testing.cairo#L4



_Code quote:_
```
struct_construct<Tuple<Unit>>([0]) -> ([1]);
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/test.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3604#-NZaZdCr77AlBbaOjx4M:-NZf3x7-1Ldecua2LhsD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3a4e18f8ed88e0542ae333da72378101ff00859c/crates/cairo-lang-lowering/src/test.rs#L143)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

print new phase
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3604)* status: 0 of 29 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 351 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3604#-NZaabKL0z3nyRv07Thp:-NZf4vW-2YG7INPGM41x:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d072fc310e78d2a7125e0b3d02c1a07de541162d/crates/cairo-lang-lowering/src/db.rs#L351)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc why somewhere
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 21 of 24 files at r2, 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3604#-:-NZf8S2Y89oqJXcYnyt_:bnfp4nl)* status: 27 of 29 files reviewed, 1 unresolved discussion

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3604)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
