### PR TITLE
Updated builder allowing ref variables, and used them for storage write.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:afeead95

---

**Stack**:
- #1386
- #1385
- #1384 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1384)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/sierra_to_casm/src/invocations/starknet/storage.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1384#-NJd_HL0D_Udg7lKYrtm:-NJd_HL0D_Udg7lKYrtn:btj9zbx) ([raw file](https://github.com/starkware-libs/cairo/blob/f5fbf5cd1bc855029dd0e29adb568a748d0be6cd/crates/sierra_to_casm/src/invocations/starknet/storage.rs#L161)):*
> ```XML
>             vec![
>                 ReferenceExpression::from_cell(CellExpression::from_res_operand(
>                     fallthrough_state.get_adjusted(updated_gas_builtin),
> ```

why not label_state["Failure"]?



_Code quote:_
```XML
fallthrough_state
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1384)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/casm/src/builder.rs` line 482 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1384#-NJdai7TBmZn6GjGY0ei:-NJdai7TBmZn6GjGY0ej:bryiw59) ([raw file](https://github.com/starkware-libs/cairo/blob/f5fbf5cd1bc855029dd0e29adb568a748d0be6cd/crates/casm/src/builder.rs#L482)):*
> ```XML
>     };
>     ($builder:ident, ref $dst:ident = $a:ident * $b:ident; $($tok:tt)*) => {
>         let $dst = $builder.bin_op($crate::operand::Operation::Mul, $a, $b);
> ```

can you add tests for those?



_Code quote:_
```XML
    };
    ($builder:ident, ref $dst:ident = $a:ident + $b:ident; $($tok:tt)*) => {
        let $dst = $builder.bin_op($crate::operand::Operation::Add, $a, $b);
        $crate::casm_build_extend!($builder, $($tok)*)
    };
    ($builder:ident, ref $dst:ident = $a:ident * $b:ident; $($tok:tt)*) => {
        let $dst = $builder.bin_op($crate::operand::Operation::Mul, $a, $b);
        $crate::casm_build_extend!($builder, $($tok)*)
    };
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1384)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/sierra_to_casm/src/invocations/starknet/storage.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1384#-NJd_HL0D_Udg7lKYrtm:-NJddw5S7futmRjHR5G0:b8wtenu) ([raw file](https://github.com/starkware-libs/cairo/blob/f5fbf5cd1bc855029dd0e29adb568a748d0be6cd/crates/sierra_to_casm/src/invocations/starknet/storage.rs#L161)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why not label_state["Failure"]?
</blockquote></details>

nice catch - works only because of alignment.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1384#-:-NJeFjCkD9btGJvc5j5n:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1384)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
