### PR TITLE
Added ability to get ap_change variables at post-gas calculation.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:3bf5cf93

---

**Stack**:
- #1951
- #1957
- #1943
- #1942 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1942)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1942#-NMwmP51A2n-2lkaYqBr:-NMwmP51A2n-2lkaYqBs:b-q3zowl) ([raw file](https://github.com/starkware-libs/cairo/blob/5a1493074478a1b6e0bd69c0fdce27c2cfd017a4/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L62)):*
> ```XML
>     /// `get_gas_all`).
>     fn token_usages(&self, token_type: CostTokenType) -> usize;
>     /// Provides the ap change variable value of the current statement.
> ```

Consider splitting this trait, as discussed

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 5 files at r1, 4 of 27 files at r2, 23 of 23 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1942#-:-NMx_5j910UKp2cOai1x:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1942)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by spapinistarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1942)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
