### PR TITLE
 refactor lowering match logic to use optional pattern and body expres…

### PR DESCRIPTION
**Pull request by TomerStarkware**
…sion in match arms

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4987)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 12 files at r3, 84 of 84 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4987)* status: 85 of 87 files reviewed, 3 unresolved discussions (waiting on @TomerStarkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4987#-NpnoTvo53xK_UaHW3tl):*




_Suggestion:_
```
- 7e87f59: refactor lowering match logic to use optional pattern and body expression in match arms
```
___
*[`crates/cairo-lang-lowering/src/diagnostic.rs` line 192 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4987#-NpnvABrEdxtfIi5AQn1:-NpnvABrEdxtfIi5AQn2:b-dn3qkc) ([raw file](https://github.com/starkware-libs/cairo/blob/8f5cbe48f2b878decad3cbb1c86c770134821e59/crates/cairo-lang-lowering/src/diagnostic.rs#L192)):*
> ```XML
> 
> #[derive(Clone, Debug, Eq, Hash, PartialEq)]
> pub enum MatchDiagnostic {
> ```

Add a `    fn format(&self, db: &Self::DbType) -> String {`
function here at call it from the wrapping diag.
___
*[`crates/cairo-lang-lowering/src/lower/lower_match.rs` line 45 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4987#-NpnvSGME5F_E3Ry913f:-NpnvSGME5F_E3Ry913g:bimpr0a) ([raw file](https://github.com/starkware-libs/cairo/blob/8f5cbe48f2b878decad3cbb1c86c770134821e59/crates/cairo-lang-lowering/src/lower/lower_match.rs#L45)):*
> ```XML
> 
> /// Information about the enum of a match statement. See [extract_concrete_enum].
> struct ExtractedEnumDetails {
> ```

this did more than move.

Split PR into move and refactor. not both on same PR.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4987)* status: 84 of 87 files reviewed, 4 unresolved discussions (waiting on @TomerStarkware)

___
*[`-- commits` line 3 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4987#-NpoPfoi625Xd40HxKWI):*
are the seperate 3 commits intended?

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4987)* status: 75 of 87 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4987#-NpnoTvo53xK_UaHW3tl):*
Done.
___
*[`-- commits` line 3 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4987#-NpoPfoi625Xd40HxKWI):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

are the seperate 3 commits intended?
</blockquote></details>

No
___
*[`crates/cairo-lang-lowering/src/diagnostic.rs` line 192 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4987#-NpnvABrEdxtfIi5AQn1:-NpoYRJP76UhqfjP69bm:bryhizo) ([raw file](https://github.com/starkware-libs/cairo/blob/dfbc2aeaa7448a6f137ffa7a5321926575676fe6/crates/cairo-lang-lowering/src/diagnostic.rs#L192)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Add a `    fn format(&self, db: &Self::DbType) -> String {`
function here at call it from the wrapping diag.
</blockquote></details>

done (without db)
___
*[`crates/cairo-lang-lowering/src/lower/lower_match.rs` line 45 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4987#-NpnvSGME5F_E3Ry913f:-NpoYVJ08HoX_MQZYicF:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/dfbc2aeaa7448a6f137ffa7a5321926575676fe6/crates/cairo-lang-lowering/src/lower/lower_match.rs#L45)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this did more than move.

Split PR into move and refactor. not both on same PR.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4987)* status: 76 of 87 files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/diagnostic.rs` line 177 at r8](https://reviewable.io/reviews/starkware-libs/cairo/4987#-NpodM_iA0kRrzgFg33N:-NpodM_j5WQKpefCVxfL:b-b8rr99) ([raw file](https://github.com/starkware-libs/cairo/blob/55d13271dfe76bae58f1ceecdbaa84119c70e88f/crates/cairo-lang-lowering/src/diagnostic.rs#L177)):*
> ```XML
> 
>     UnreachableMatchArm,
>     MissingMatchArm(String),
> ```

Add todo to get rid of strings here.



_Code quote:_
```XML
    MissingMatchArm(String),
```
___
*[`crates/cairo-lang-lowering/src/lower/lower_match.rs` line 535 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4987#-NpodSgcDyJEMtAUBDs4:-NpodSgcDyJEMtAUBDs5:b-93sr0r) ([raw file](https://github.com/starkware-libs/cairo/blob/503eced616086f152888f7d5adc328a812f1bd7d/crates/cairo-lang-lowering/src/lower/lower_match.rs#L535)):*
> ```XML
>     Ok(match_info)
> }
> struct TupleInfo {
> ```

add spaces and docs everywhere.

**Review by orizi — COMMENTED** [review]
> Reviewed 10 of 10 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4987)* status: 86 of 87 files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4987)* status: 85 of 87 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/diagnostic.rs` line 177 at r8](https://reviewable.io/reviews/starkware-libs/cairo/4987#-NpodM_iA0kRrzgFg33N:-Npot8p50UnhfM0HdyoH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/55d13271dfe76bae58f1ceecdbaa84119c70e88f/crates/cairo-lang-lowering/src/diagnostic.rs#L177)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Add todo to get rid of strings here.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/lower_match.rs` line 535 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4987#-NpodSgcDyJEMtAUBDs4:-Npot9bA-szrROYhLcI0:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/503eced616086f152888f7d5adc328a812f1bd7d/crates/cairo-lang-lowering/src/lower/lower_match.rs#L535)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add spaces and docs everywhere.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4987)* status: 85 of 87 files reviewed, 3 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/diagnostic.rs` line 171 at r9](https://reviewable.io/reviews/starkware-libs/cairo/4987#-NpouRc00-PtH4UHGE2C:-NpouRc00-PtH4UHGE2D:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/3d2aea2beb1cffa2ee376e9a0873c528c3c83e97/crates/cairo-lang-lowering/src/diagnostic.rs#L171)):*
> ```XML
> #[derive(Clone, Debug, Eq, Hash, PartialEq)]
> pub enum MatchDiagnostic {
>     /// TODO(TomerStarkware: get rid of the string and pass the type information directly.)
> ```





_Suggestion:_
```XML
    /// TODO(TomerStarkware): Get rid of the string and pass the type information directly.
```

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4987)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4987)* status: all files reviewed, 3 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/lower_match.rs` line 63 at r9](https://reviewable.io/reviews/starkware-libs/cairo/4987#-Npoug2V8n11nxmGErRU:-Npoug2V8n11nxmGErRV:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/3d2aea2beb1cffa2ee376e9a0873c528c3c83e97/crates/cairo-lang-lowering/src/lower/lower_match.rs#L63)):*
> ```XML
> }
> /// Extracts concrete enum and variants from a match expression. Assumes it is indeed a concrete
> /// enum.
> ```





_Suggestion:_
```XML
}

/// Extracts concrete enum and variants from a match expression. Assumes it is indeed a concrete
/// enum.
```
___
*[`crates/cairo-lang-lowering/src/lower/lower_match.rs` line 136 at r9](https://reviewable.io/reviews/starkware-libs/cairo/4987#-NpovJGjEQI1Ta_vSJFV:-NpovJGjEQI1Ta_vSJFW:bg1qmkc) ([raw file](https://github.com/starkware-libs/cairo/blob/3d2aea2beb1cffa2ee376e9a0873c528c3c83e97/crates/cairo-lang-lowering/src/lower/lower_match.rs#L136)):*
> ```XML
>             if arm.patterns.is_empty() {
>                 return Some(PatternPath { arm_index, pattern_index: usize::MAX });
>             }
> ```

don't put illegal values.



_Code quote:_
```XML
                return Some(PatternPath { arm_index, pattern_index: usize::MAX });
            }
```

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4987)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4987)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4987#-:-Npp00IY6wMQ0gZJNM9b:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
