### PR TITLE
Parse loops

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2600)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2599** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2599" target="_blank">Graphite</a> 
    * **PR #2600** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2600" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2600?utm_source=stack-comment).

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2600#-:-NRSvRrv-hHlmF63T_ki:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Comment by spapinistarkware** [comment]
@spapinistarkware queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2600).

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2600)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Comment by spapinistarkware** [comment]
[Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2600) failed to merge this pull request for an unknown reason. Try your merge again, or report a bug if you see this consistently.

**Comment by spapinistarkware** [comment]
@spapinistarkware queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2600).

**Comment by spapinistarkware** [comment]
[Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2600) failed to merge this pull request for an unknown reason. Try your merge again, or report a bug if you see this consistently.

**Comment by spapinistarkware** [comment]
@spapinistarkware queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2600).

**Comment by spapinistarkware** [comment]
[Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2600) failed to merge this pull request for an unknown reason. Try your merge again, or report a bug if you see this consistently.

**Comment by spapinistarkware** [comment]
@spapinistarkware queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2600).

**Comment by spapinistarkware** [comment]
[Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2600) failed to merge this pull request for an unknown reason. Try your merge again, or report a bug if you see this consistently.

**Pull request merged**
