### PR TITLE
Updated sierra ap-change finding to be based on final lowering.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6258)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/ap_change.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6258#-O4st_V40z_l9U_6yRnC:-O4st_V55eEto_TwDz_k:b-5jrzqf) ([raw file](https://github.com/starkware-libs/cairo/blob/826f3d6a68b2268e3204bbdfc216202345d3853a/crates/cairo-lang-sierra-generator/src/ap_change.rs#L20)):*
> ```XML
>     function_id: ConcreteFunctionWithBodyId,
> ) -> Maybe<SierraApChange> {
>     // The implementation of get_ap_change() may call this function recursively. To guarantee no
> ```

Maybe we should just add cycle handling to the function?



_Code quote:_
```XML
 // salsa query cycles are created, we first verify that there are no cycles.
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6258)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6258)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/ap_change.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6258#-O4st_V40z_l9U_6yRnC:-O4strmkAdu4cFNI1ied:bed5eaj) ([raw file](https://github.com/starkware-libs/cairo/blob/826f3d6a68b2268e3204bbdfc216202345d3853a/crates/cairo-lang-sierra-generator/src/ap_change.rs#L20)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Maybe we should just add cycle handling to the function?
</blockquote></details>

if we do that - this won't be the function that is actually the entry into the salsa-cycle - it would probably be a random function that generates the sierra code.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6258#-:-O4svl6sBgsT4wdTsze5:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @orizi)

**Review by mkaput — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6258)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @piotmag769)

**Pull request merged**
