### PR TITLE
Improve sierra-compile error message.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2276)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2276)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/cli.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2276#-NPC7QI2A9P9IHSEYvsh:-NPC7QI2A9P9IHSEYvsi:bw1etxe) ([raw file](https://github.com/starkware-libs/cairo/blob/d790832adc6615198d67a3892bb9039b795d22c6/crates/cairo-lang-sierra-to-casm/src/cli.rs#L28)):*
> ```XML
>     let sierra_code = fs::read_to_string(args.file).with_context(|| "Could not read file!")?;
>     let Ok(program) = ProgramParser::new().parse(&sierra_code) else {
>         anyhow::bail!(indoc!{
> ```

or something



_Suggestion:_
```XML
    let Ok(program) = ProgramParser::new().parse(&sierra_code) else {
        anyhow::bail!(indoc!{"
            Failed to parse sierra program.
            If you are trying to compile a starknet contract you should use `starknet-sierra-compile`.
        "});
    };
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-to-casm/src/cli.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2276#-NPC7QI2A9P9IHSEYvsh:-NPC7pl6AnPeAyl947ng:bnlyam5) ([raw file](https://github.com/starkware-libs/cairo/blob/d790832adc6615198d67a3892bb9039b795d22c6/crates/cairo-lang-sierra-to-casm/src/cli.rs#L28)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

or something
</blockquote></details>

The second line does not fit.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2276)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/cli.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2276#-NPC7QI2A9P9IHSEYvsh:-NPC9BTZ8NUpfgZzGF8_:b-px8mql) ([raw file](https://github.com/starkware-libs/cairo/blob/d790832adc6615198d67a3892bb9039b795d22c6/crates/cairo-lang-sierra-to-casm/src/cli.rs#L28)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

The second line does not fit.
</blockquote></details>

so don't use indoc.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-to-casm/src/cli.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2276#-NPC7QI2A9P9IHSEYvsh:-NPCAEzc34MxwxZo73k7:b-1tdlim) ([raw file](https://github.com/starkware-libs/cairo/blob/d790832adc6615198d67a3892bb9039b795d22c6/crates/cairo-lang-sierra-to-casm/src/cli.rs#L28)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

so don't use indoc.
</blockquote></details>

and have 0 indenation?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2276)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/cli.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2276#-NPC7QI2A9P9IHSEYvsh:-NPCJJqv-3AXnU84m0kH:b2t47vu) ([raw file](https://github.com/starkware-libs/cairo/blob/d790832adc6615198d67a3892bb9039b795d22c6/crates/cairo-lang-sierra-to-casm/src/cli.rs#L28)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

and have 0 indenation?
</blockquote></details>

indoc's idea is to make better identation - not worse.
all i want here is to have the string look normal as an argument.
___
*[`crates/cairo-lang-sierra-to-casm/src/cli.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2276#-NPCJ_yN3TzGPnJ06Vwc:-NPCJ_yN3TzGPnJ06Vwd:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6a95f9ae8464617f759d8ae7c71bddac5bb789a9/crates/cairo-lang-sierra-to-casm/src/cli.rs#L29)):*
> ```XML
>     let Ok(program) = ProgramParser::new().parse(&sierra_code) else { anyhow::bail!(indoc!{"
>         Failed to parse sierra program.
>         If you are trying to compile a starknet contract you should use `starknet-sierra-compile`."
> ```





_Suggestion:_
```XML
       Note: for compiling starknet contracts use `starknet-sierra-compile`."
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2276)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/cli.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2276#-NPC7QI2A9P9IHSEYvsh:-NPCLI-u7BbfSh9PiOqV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d790832adc6615198d67a3892bb9039b795d22c6/crates/cairo-lang-sierra-to-casm/src/cli.rs#L28)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

indoc's idea is to make better identation - not worse.
all i want here is to have the string look normal as an argument.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/cli.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2276#-NPCJ_yN3TzGPnJ06Vwc:-NPCLGvl1e2C72Y2ppD0:b-s54w3b) ([raw file](https://github.com/starkware-libs/cairo/blob/6a95f9ae8464617f759d8ae7c71bddac5bb789a9/crates/cairo-lang-sierra-to-casm/src/cli.rs#L29)):*
>  Note: for compiling starknet contracts use `starknet-sierra-compile`."
rephrased.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2276#-:-NPCM4MY8C24PSGuinA_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
