### PR TITLE
Added FunctionWithBody and semantic model for impl function definitions

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1728)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 10 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1728)* status: 10 of 17 files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 433 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1728#-NLQii4m5UWi65sS1RYF:-NLQii4m5UWi65sS1RYG:b-8kvd6a) ([raw file](https://github.com/starkware-libs/cairo/blob/83426d16dc30447e4b81b5af710dc93b77be31d9/crates/cairo-lang-semantic/src/db.rs#L433)):*
> ```XML
>         function_id: FunctionWithBodyId,
>     ) -> Maybe<Vec<FunctionId>>;
>     /// Returns the nonextern function direct callees of a function with a body (i.e. excluding
> ```

Why do you exclude extern here?



_Code quote:_
```XML
nonextern
```
___
*[`crates/cairo-lang-semantic/src/db.rs` line 685 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1728#-NLQjWi91ccQEXY3AW0f:-NLQjWi91ccQEXY3AW0g:b-bi219o) ([raw file](https://github.com/starkware-libs/cairo/blob/83426d16dc30447e4b81b5af710dc93b77be31d9/crates/cairo-lang-semantic/src/db.rs#L685)):*
> ```XML
>                 diagnostics.extend(db.trait_semantic_diagnostics(*trait_id));
>             }
>             ModuleItemId::Impl(impl_id) => {
> ```

Do we need to add the diagnostics of impl functions here?
___
*[`crates/cairo-lang-semantic/src/db.rs` line 822 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1728#-NLQj_nH224757D9hnhw:-NLQj_nH224757D9hnhx:blitsgb) ([raw file](https://github.com/starkware-libs/cairo/blob/83426d16dc30447e4b81b5af710dc93b77be31d9/crates/cairo-lang-semantic/src/db.rs#L822)):*
> ```XML
> 
> fn get_resolver_lookbacks(id: LookupItemId, db: &dyn SemanticGroup) -> Vec<Arc<ResolvedLookback>> {
>     match id {
> ```

You should add the resolver fo impl function definition here.

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1728)* status: 11 of 17 files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1728)* status: 9 of 17 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 433 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1728#-NLQii4m5UWi65sS1RYF:-NLV00emBbUKYRGdCZ5E:bkxy9oh) ([raw file](https://github.com/starkware-libs/cairo/blob/83426d16dc30447e4b81b5af710dc93b77be31d9/crates/cairo-lang-semantic/src/db.rs#L433)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Why do you exclude extern here?
</blockquote></details>

It's not new. I have 2 queries - one to get all the direct callees, and one to get all but extern funcs. The reason is that when I recurse, I only need to get into functions with body. It existed before but was called free_function_definition_direct_free_function_callees when we didn't have impl functions.
___
*[`crates/cairo-lang-semantic/src/db.rs` line 685 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1728#-NLQjWi91ccQEXY3AW0f:-NLV1oVA7hrvyd9s0Ghz:b-th1vh1) ([raw file](https://github.com/starkware-libs/cairo/blob/83426d16dc30447e4b81b5af710dc93b77be31d9/crates/cairo-lang-semantic/src/db.rs#L685)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Do we need to add the diagnostics of impl functions here?
</blockquote></details>

It's included in impl_semantic_definition_diagnostics 



_Code quote:_
```XML
impl_semantic_definition_diagnostics
```
___
*[`crates/cairo-lang-semantic/src/db.rs` line 822 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1728#-NLQj_nH224757D9hnhw:-NLV2ICV9ULj-nUTk6nh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/83426d16dc30447e4b81b5af710dc93b77be31d9/crates/cairo-lang-semantic/src/db.rs#L822)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

You should add the resolver fo impl function definition here.
</blockquote></details>

Done.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1728)* status: 9 of 17 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 433 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1728#-NLQii4m5UWi65sS1RYF:-NLVUagSBY9wnEQ-04O3:b-tiekcy) ([raw file](https://github.com/starkware-libs/cairo/blob/83426d16dc30447e4b81b5af710dc93b77be31d9/crates/cairo-lang-semantic/src/db.rs#L433)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

It's not new. I have 2 queries - one to get all the direct callees, and one to get all but extern funcs. The reason is that when I recurse, I only need to get into functions with body. It existed before but was called free_function_definition_direct_free_function_callees when we didn't have impl functions.
</blockquote></details>

Change to function with body



_Code quote:_
```XML
nonextern
```

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 6 of 17 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1728)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 13 of 17 files at r1, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1728)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1728)* status: 5 of 18 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1728#-NLX0ukK2WGRbtrAQ6jD:-NLX0ukL3rpLAgrz3YeY:be4x7vm) (no related file):*
don't delete branch

___

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 12 of 13 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1728)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
