### PR TITLE
derive PanicDestruct

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3234)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3232** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3232" target="_blank">Graphite</a> 
    * **PR #3233** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3233" target="_blank">Graphite</a> 
      * **PR #3234** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3234" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/3234?utm_source=stack-comment).

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3234)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 285 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3234#-NWCO57g42GC21h6qKE8:-NWCO57h3XNjiOrtLuAk:b-dqyxyv) ([raw file](https://github.com/starkware-libs/cairo/blob/872d740d7a8f3e73ce7c5cc9b88a3942a0e36d97/crates/cairo-lang-plugins/src/plugins/derive.rs#L285)):*
> ```XML
>                     }}
>                 ", variants.iter().map(|variant| {
>                 format!("{name}::{variant}(x) => traits::PanicDestruct::panic_destruct(x, ref panic),")
> ```

100 chars



_Code quote:_
```XML
                ", variants.iter().map(|variant| {
                format!("{name}::{variant}(x) => traits::PanicDestruct::panic_destruct(x, ref panic),")
```
___
*[`crates/cairo-lang-plugins/src/test_data/derive` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3234#-NWCOE8E6jTFaO-jNu2Y:-NWCOE8E6jTFaO-jNu2Z:blpm80d) ([raw file](https://github.com/starkware-libs/cairo/blob/872d740d7a8f3e73ce7c5cc9b88a3942a0e36d97/crates/cairo-lang-plugins/src/test_data/derive#L19)):*
> ```
> }
> 
> #[derive(Copy, Destruct, PanicDestruct)]
> ```

isn't having both dangerous?



_Code quote:_
```
Destruct, PanicDestruct
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3234)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 285 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3234#-NWCO57g42GC21h6qKE8:-NXd0aua2bQMZC7mMaXT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/526c0503e0ee170199d96b56e7bd74a9971f3d75/crates/cairo-lang-plugins/src/plugins/derive.rs#L285)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

100 chars
</blockquote></details>

Done.
___
*[`crates/cairo-lang-plugins/src/test_data/derive` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3234#-NWCOE8E6jTFaO-jNu2Y:-NXd0dSt60nHd9wroR37:b-y38spk) ([raw file](https://github.com/starkware-libs/cairo/blob/526c0503e0ee170199d96b56e7bd74a9971f3d75/crates/cairo-lang-plugins/src/test_data/derive#L19)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

isn't having both dangerous?
</blockquote></details>

It is.
Also Copy and Clone.
Also Drop and Destruct.
We should probably enforce it in the derive.
But I guess it's out of scope for this PR?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3234)* status: 0 of 2 files reviewed, 1 unresolved discussion

___
*[`crates/cairo-lang-plugins/src/test_data/derive` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3234#-NWCOE8E6jTFaO-jNu2Y:-NXdaVUxDBaYVW86JCA7:b614ydr) ([raw file](https://github.com/starkware-libs/cairo/blob/526c0503e0ee170199d96b56e7bd74a9971f3d75/crates/cairo-lang-plugins/src/test_data/derive#L19)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

It is.
Also Copy and Clone.
Also Drop and Destruct.
We should probably enforce it in the derive.
But I guess it's out of scope for this PR?
</blockquote></details>

either that - or making sure to fail if we find 2 matching impls of the same trait.
but i guess so.

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3234#-:-NXp9lZ1D1sZuxSPrB30:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
