### PR TITLE
Split GenericFunctionId and FunctionSignatureId

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1784)

### CODE REVIEW

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1784)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1784)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1784#-NLzPz-E2ZFDi32KcjNY:-NLzPz-E2ZFDi32KcjNZ:b-cvqrxt) ([raw file](https://github.com/starkware-libs/cairo/blob/c67638cd5ab51b2df5a2db735e935b2232459cb8/crates/cairo-lang-semantic/src/items/functions.rs#L26)):*
> ```XML
> 
> #[derive(Copy, Clone, Debug, Hash, PartialEq, Eq)]
> pub struct ConcreteImplGenericFunctionIc {
> ```

I see what you did there



_Suggestion:_
```XML
Id
```
___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 31 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1784#-NLzQFU4CZlELEV4lYij:-NLzQFU4CZlELEV4lYik:b-w7ijn9) ([raw file](https://github.com/starkware-libs/cairo/blob/c67638cd5ab51b2df5a2db735e935b2232459cb8/crates/cairo-lang-semantic/src/items/functions.rs#L31)):*
> ```XML
> }
> 
> /// The ID of a generic function that can be concretized.
> ```

is this a typo?



_Code quote:_
```XML
oncretized
```

**Review by yuvalsw — COMMENTED** [review]
> Dismissed @spapinistarkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1784)* status: 14 of 24 files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 4 of 17 files at r1, 10 of 18 files at r2, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1784)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1784#-:-NLziwurETdTRMWDLYD5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1784)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
