### PR TITLE
Add self to storage

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3044)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3042** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3042" target="_blank">Graphite</a> 
    * **PR #3044** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3044" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/3044?utm_source=stack-comment).

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 7 of 40 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3044)* status: 7 of 40 files reviewed, 3 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3044#-NUfSFjgEazgtIhxFPkM:-NUfSFjgEazgtIhxFPkN:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/b33c6a0466c6c656bd072c53141930fe334e55fb/crates/cairo-lang-starknet/src/plugin/contract.rs#L89)):*
> ```XML
>         .is_some()
>         {
>             // extra_uses
> ```

?
___
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3044#-NUfSqfN2NDCI_GC117R:-NUfSqfN2NDCI_GC117S:b-t0lo7g) ([raw file](https://github.com/starkware-libs/cairo/blob/b33c6a0466c6c656bd072c53141930fe334e55fb/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L83)):*
> ```XML
>     let is_snapshot = matches!(first_param.type_clause(db).ty(db), ast::Expr::Unary(_));
>     // TODO: Check modifiers and type.
> ```

assign
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contract` line 165 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3044#-NUfTcg6CIhYawl5rlaB:-NUfTcg6CIhYawl5rlaC:b82o5de) ([raw file](https://github.com/starkware-libs/cairo/blob/b33c6a0466c6c656bd072c53141930fe334e55fb/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contract#L165)):*
> ```
> error: Plugin diagnostic: `raw_output` functions must get a self param.
>  --> lib.cairo:18:21
>     fn set_something(ref arg: felt252, num: felt252) {}
> ```

fix contract.
all others as well.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 15 of 40 files at r1, 21 of 21 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3044#-:-NUmoG_W1kitRuyM2JJw:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/diagnostics` line 148 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3044#-NUmmtlMC5Zwt37hggbH:-NUmmtlMC5Zwt37hggbI:b-b1iaec) ([raw file](https://github.com/starkware-libs/cairo/blob/104e55f3fc3a0e52aeb791b38d524fdbb48c9dfa/crates/cairo-lang-starknet/src/plugin/plugin_test_data/diagnostics#L148)):*
> ```
>     const TEST_CLASS_HASH: felt252 = 1329057522279442750040840779564221850018406246217508409165568018196634259776;
>     #[derive(Copy, Drop)]
> struct Storage {
> ```

fix indent
___
*[`crates/cairo-lang-starknet/test_data/hello_starknet.cairo` line 10 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3044#-NUmno3n7DHPjr5fT8SS:-NUmno3n7DHPjr5fT8ST:b-mmehnj) ([raw file](https://github.com/starkware-libs/cairo/blob/104e55f3fc3a0e52aeb791b38d524fdbb48c9dfa/crates/cairo-lang-starknet/test_data/hello_starknet.cairo#L10)):*
> ```Cairo
>     #[external]
>     fn increase_balance(ref self: Storage, amount: felt252) {
>         // TODO(spapini):  Remove explicit snapshot when snapshot member borrowing is fixed.
> ```

i dont see the explicit here.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3044)* status: all files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3044#-NUpFevYBk5BDYpr1_BR:-NUpFevYBk5BDYpr1_BS:b4ekqv5) (no related file):*
Casm files shouldn't change in this PR.
I suspect they were changed because `unsafe_new_storage>()` was not inlined.

___

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3044)* status: 13 of 40 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/diagnostics` line 148 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3044#-NUmmtlMC5Zwt37hggbH:-NUpRKGB7zetIldiat1b:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/104e55f3fc3a0e52aeb791b38d524fdbb48c9dfa/crates/cairo-lang-starknet/src/plugin/plugin_test_data/diagnostics#L148)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix indent
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/test_data/hello_starknet.cairo` line 10 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3044#-NUmno3n7DHPjr5fT8SS:-NUpRL_z6qLQdI_Wc1g6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/104e55f3fc3a0e52aeb791b38d524fdbb48c9dfa/crates/cairo-lang-starknet/test_data/hello_starknet.cairo#L10)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i dont see the explicit here.
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 11 of 27 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3044)* status: 24 of 40 files reviewed, 2 unresolved discussions (waiting on @liorgold2)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3044#-NUpFevYBk5BDYpr1_BR:-NUpdJZr-ns7_HCXYwSv:b-lbkpjs) (no related file):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Casm files shouldn't change in this PR.
I suspect they were changed because `unsafe_new_storage>()` was not inlined.
</blockquote></details>

(after the fix) there are still some changes in the casm files.

___

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3044)* status: 16 of 40 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3044#-NUpFevYBk5BDYpr1_BR:-NUqO2Q06dgOPqeVA16A:bzb5r9c) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

(after the fix) there are still some changes in the casm files.
</blockquote></details>

Seems that some trivial functions (such as get_balance()) were auto-inlined before, but now are not.

___

**Review by orizi — COMMENTED** [review]
> Reviewed 6 of 20 files at r4, 8 of 20 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3044)* status: 24 of 40 files reviewed, 2 unresolved discussions (waiting on @liorgold2)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3044#-NUpFevYBk5BDYpr1_BR:-NUqnQQKCwroXfosR7jA:bny6h80) (no related file):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Seems that some trivial functions (such as get_balance()) were auto-inlined before, but now are not.
</blockquote></details>

so what do you suggest we do?
(I assume this changed because the function stopped being a single line function at the lowering level)

___

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3044)* status: 24 of 40 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3044#-NUpFevYBk5BDYpr1_BR:-NUpMAf82Z8DoPS0MjvB:b-9xpf40) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

so what do you suggest we do?
(I assume this changed because the function stopped being a single line function at the lowering level)
</blockquote></details>

I sugegst doing nothing about it.

___

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 27 files at r3, 12 of 20 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3044#-:-NUv-4kY-ZB6EYj9U2lK:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3044)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3044#-NUpFevYBk5BDYpr1_BR:-NUzKNkfBC9PBUATNn0w:blacuf3) (no related file):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I sugegst doing nothing about it.
</blockquote></details>

I expect such PR to not change the casm files.
The other option is that you go over all the changes and make sure they're expected...

___

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 40 files at r1, 1 of 21 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3044)* status: all files reviewed, 5 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/lookup_item.rs` line 70 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3044#-NUzLGUiBw0yUCHztXiS:-NUzLGUiBw0yUCHztXiT:bj7g1nw) ([raw file](https://github.com/starkware-libs/cairo/blob/359a7d956b25c3c0d9bf72ebff005f8daa33dde3/crates/cairo-lang-semantic/src/lookup_item.rs#L70)):*
> ```XML
> impl HasResolverData for SubmoduleId {
>     fn resolver_data(&self, _db: &dyn SemanticGroup) -> Maybe<Arc<ResolverData>> {
>         let module_id = ModuleId::Submodule(*self);
> ```

What changed here?
___
*[`crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo` line 27 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3044#-NUzLccyAC_MCjCTd70a:-NUzLccyAC_MCjCTd70b:b-uri44z) ([raw file](https://github.com/starkware-libs/cairo/blob/359a7d956b25c3c0d9bf72ebff005f8daa33dde3/crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo#L27)):*
> ```Cairo
> 
>     #[view]
>     fn get_plus_2(self: @Storage, a: felt252) -> felt252 {
> ```

What's the error you get if you forget to put `self` here?
___
*[`crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo` line 32 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3044#-NUzLZRhDCjJ1zHbBeBD:-NUzLYIX9qsCggBy2ka4:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/359a7d956b25c3c0d9bf72ebff005f8daa33dde3/crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo#L32)):*
> ```Cairo
> 
>     #[view]
>     fn spend_all_gas(self: @Storage, ) {
> ```

.



_Suggestion:_
```Cairo
 fn spend_all_gas(self: @Storage) {
```
___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 336 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3044#-NUzMCai0V-pnnqnghUm:-NUzMCai0V-pnnqnghUn:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/359a7d956b25c3c0d9bf72ebff005f8daa33dde3/crates/cairo-lang-starknet/src/plugin/contract.rs#L336)):*
> ```XML
>     } else {
>         diagnostics.push(PluginDiagnostic {
>             message: "An L1 handler must have the 'from_address' parameter.".to_string(),
> ```





_Suggestion:_
```XML
message: "An L1 handler must have the 'from_address' as its second parameter.".to_string(),
```

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 21 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3044)* status: all files reviewed, 8 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 71 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3044#-NUzMWTs-iR2az9Us6GD:-NUzMWTs-iR2az9Us6GE:b-bnr3tx) ([raw file](https://github.com/starkware-libs/cairo/blob/359a7d956b25c3c0d9bf72ebff005f8daa33dde3/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L71)):*
> ```XML
>     let Some(first_param) = params.next() else {
>         return Err(vec![PluginDiagnostic{
>             message: format!("`{RAW_OUTPUT_ATTR}` functions must get a self param."),
> ```

Do we use ` or ' in error messages?



_Suggestion:_
```XML
`{RAW_OUTPUT_ATTR}` functions must get a 'self' parameter.
```
___
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 77 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3044#-NUzMhdJ8N9kysw3LIFZ:-NUzMhdJ8N9kysw3LIF_:brhumzt) ([raw file](https://github.com/starkware-libs/cairo/blob/359a7d956b25c3c0d9bf72ebff005f8daa33dde3/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L77)):*
> ```XML
>     if first_param.name(db).text(db) != "self" {
>         return Err(vecPluginDiagnostic {
>             message: format!("`{RAW_OUTPUT_ATTR}` functions must get a self param."),
> ```

Same here.
___
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 160 at r5 ([raw file](https://github.com/starkware-libs/cairo/blob/359a7d956b25c3c0d9bf72ebff005f8daa33dde3/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L160)):*
> ```XML
>             "{let_res}$wrapped_name$({storage_arg}, {arg_names_str});
>             let mut arr = array::array_new();
>             // References.$ref_appends$
> ```

What do these comment do?

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 20 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3044)* status: all files reviewed, 9 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contract` line 79 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3044#-NUzPXPVE-Zh94u9rYk3:-NUzPXPVE-Zh94u9rYk4:bj7g1nw) ([raw file](https://github.com/starkware-libs/cairo/blob/359a7d956b25c3c0d9bf72ebff005f8daa33dde3/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contract#L79)):*
> ```
>     ) {}
> 
>     const TEST_CLASS_HASH: felt252 = 732696006930423679076351915598725357828400392043738509448233963348236196924;
> ```

What changed here?

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3044)* status: all files reviewed, 8 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contract` line 79 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3044#-NUzPXPVE-Zh94u9rYk3:-NUzPdTBBctpWGtgFF_z:b-tatwal) ([raw file](https://github.com/starkware-libs/cairo/blob/359a7d956b25c3c0d9bf72ebff005f8daa33dde3/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contract#L79)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

What changed here?
</blockquote></details>

Never mind.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 40 files at r1, 1 of 27 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3044)* status: all files reviewed, 10 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 28 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3044#-NUzPqE73rNly0pB_Ip9:-NUzPqE73rNly0pB_IpA:bcgjvre) ([raw file](https://github.com/starkware-libs/cairo/blob/359a7d956b25c3c0d9bf72ebff005f8daa33dde3/crates/cairo-lang-starknet/test_data/account.cairo#L28)):*
> ```Cairo
>     }
> 
>     trait StorageTrait {
> ```

Why this change?
___
*[`crates/cairo-lang-starknet/test_data/erc20.cairo` line 107 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3044#-NUzQFkrCJiGg0VtLnkc:-NUzQFks8l9gVxQkZDIp:bcgjvre) ([raw file](https://github.com/starkware-libs/cairo/blob/359a7d956b25c3c0d9bf72ebff005f8daa33dde3/crates/cairo-lang-starknet/test_data/erc20.cairo#L107)):*
> ```Cairo
>     }
> 
>     trait StorageTrait {
> ```

Why this change?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3044)* status: all files reviewed, 10 unresolved discussions (waiting on @liorgold2)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3044#-NUpFevYBk5BDYpr1_BR:-NVxGjWf7vQfuyx0hzHp:b-nu4z1t) (no related file):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

I expect such PR to not change the casm files.
The other option is that you go over all the changes and make sure they're expected...
</blockquote></details>

I have. I explained why the happened.

___

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3044)* status: 18 of 40 files reviewed, 10 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-semantic/src/lookup_item.rs` line 70 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3044#-NUzLGUiBw0yUCHztXiS:-NVxGwsh8WeTY2xOPmrv:b-r5bbyi) ([raw file](https://github.com/starkware-libs/cairo/blob/359a7d956b25c3c0d9bf72ebff005f8daa33dde3/crates/cairo-lang-semantic/src/lookup_item.rs#L70)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

What changed here?
</blockquote></details>

It was a mistake. we returned the containing module of this submodule, instead of the submodule itself.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo` line 27 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3044#-NUzLccyAC_MCjCTd70a:-NVxHd59E2TEWIx1qaSz:b8l9g3w) ([raw file](https://github.com/starkware-libs/cairo/blob/359a7d956b25c3c0d9bf72ebff005f8daa33dde3/crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo#L27)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

What's the error you get if you forget to put `self` here?
</blockquote></details>

```view functions must get a self param```
___
*[`crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo` line 32 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3044#-NUzLZRhDCjJ1zHbBeBD:-NVxIctkARFI9bvrJi9Z:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/359a7d956b25c3c0d9bf72ebff005f8daa33dde3/crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo#L32)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 336 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3044#-NUzMCai0V-pnnqnghUm:-NVxI1q7D_ROJn0CsG-Q:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/359a7d956b25c3c0d9bf72ebff005f8daa33dde3/crates/cairo-lang-starknet/src/plugin/contract.rs#L336)):*
> ```XML
>     } else {
>         diagnostics.push(PluginDiagnostic {
>             message: "An L1 handler must have the 'from_address' parameter.".to_string(),
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 71 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3044#-NUzMWTs-iR2az9Us6GD:-NVxHybVDdWczX_KZb9Q:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/359a7d956b25c3c0d9bf72ebff005f8daa33dde3/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L71)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Do we use ` or ' in error messages?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 77 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3044#-NUzMhdJ8N9kysw3LIFZ:-NVxHysoBfc4xqxzEFdM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/359a7d956b25c3c0d9bf72ebff005f8daa33dde3/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L77)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 160 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3044#-NUzNFnA1vViYEJj5A37:-NVxILEvEFC4B8F8Y1wp:bxvh9mz) ([raw file](https://github.com/starkware-libs/cairo/blob/359a7d956b25c3c0d9bf72ebff005f8daa33dde3/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L160)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

What do these comment do?
</blockquote></details>

The comment ends after `References.`. There is a newline in the next thing. same for `Result.`
___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 28 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3044#-NUzPqE73rNly0pB_Ip9:-NVxIiCPC-6UImKzPdd0:b-2mpq4) ([raw file](https://github.com/starkware-libs/cairo/blob/359a7d956b25c3c0d9bf72ebff005f8daa33dde3/crates/cairo-lang-starknet/test_data/account.cairo#L28)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Why this change?
</blockquote></details>

`validate_transaction` needs another parameter (of type `Storage`). It made sense for it to be `self` as well.
___
*[`crates/cairo-lang-starknet/test_data/erc20.cairo` line 107 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3044#-NUzQFkrCJiGg0VtLnkc:-NVxIuYO9MXlLhs7vtUt:b2nreh6) ([raw file](https://github.com/starkware-libs/cairo/blob/359a7d956b25c3c0d9bf72ebff005f8daa33dde3/crates/cairo-lang-starknet/test_data/erc20.cairo#L107)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Why this change?
</blockquote></details>

Same as above.

**Review by orizi — APPROVED** [review]
> Reviewed 21 of 22 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3044)* status: all files reviewed, 10 unresolved discussions (waiting on @liorgold2)

**Pull request merged**
