### PR TITLE
Added syntax and parsing for impl impl-items

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4642)

### CODE REVIEW

**Comment by yuvalsw** [comment]
change target branch

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4642)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4642#-NmR6xjVB4eISgCRtiHR:-NmR6xjVB4eISgCRtiHS:bho2s9) (no related file):*
awaiting rebase and item rename.

___

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 10 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4642)* status: 8 of 11 files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 879 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4642#-NmRZj3R7wzuFpx67V6M:-NmRZj3R7wzuFpx67V6N:b2lwf1p) ([raw file](https://github.com/starkware-libs/cairo/blob/e2e950a90ce3b20675e3b11da6ac01d0ea284c9a/crates/cairo-lang-parser/src/parser.rs#L879)):*
> ```XML
>         match self.expect_impl_inner(attributes, visibility, true) {
>             ImplItemOrAlias::Alias(green) => green.into(),
>             ImplItemOrAlias::Item(_) => unreachable!(),
> ```

add some text in the macro
___
*[`crates/cairo-lang-syntax-codegen/src/cairo_spec.rs` line 584 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4642#-NmR_a1l2uSNuXMwnaeE:-NmR_a1l2uSNuXMwnaeF:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/e2e950a90ce3b20675e3b11da6ac01d0ea284c9a/crates/cairo-lang-syntax-codegen/src/cairo_spec.rs#L584)):*
> ```XML
>     )
>     .add_struct(StructBuilder::new("ImplItemMissing"))
>     // TODO(yg): remove.
> ```

.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4642)* status: 4 of 11 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 879 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4642#-NmRZj3R7wzuFpx67V6M:-NmRa1az7TdfWTTkCW3_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e2e950a90ce3b20675e3b11da6ac01d0ea284c9a/crates/cairo-lang-parser/src/parser.rs#L879)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add some text in the macro
</blockquote></details>

Done.
___
*[`crates/cairo-lang-syntax-codegen/src/cairo_spec.rs` line 584 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4642#-NmR_a1l2uSNuXMwnaeE:-NmRaCMB5CywFF1lDkY0:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e2e950a90ce3b20675e3b11da6ac01d0ea284c9a/crates/cairo-lang-syntax-codegen/src/cairo_spec.rs#L584)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4642#-:-NmRbSfk-8wbLILq4wi9:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
