### PR TITLE
Cost computation: Set no_eq_solver=true in sierra-compile and runner.

### PR DESCRIPTION
**Pull request by liorgold2**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4228)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4228#-:-NgEQ6Qj2OYpdqyD1JR3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4228#-:-NgEQ9uuElF8Zt13SecH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4228)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4228#-NgISXY31u4nG1AUq1At:-NgISXY31u4nG1AUq1Au:b-dvpft8) (no related file):*
Should we port this change to Scarb? Affected lines are copy-pasted there

___

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4228)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4228#-NgISXY31u4nG1AUq1At:-NgISdrd9WsqAAB72p4Y:bhmhbag) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Should we port this change to Scarb? Affected lines are copy-pasted there
</blockquote></details>

@orizi @liorgold2 

___

**Review by orizi — APPROVED** [review]
Yes, but not now, as this will be only in the next sierra minor release.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4228#-:-NgIqNAT8WfKdM6Jdl0Z:b-2kk57w)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4228)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4228#-NgISXY31u4nG1AUq1At:-NgIqXiWAdRBJDTYKwrF:b-2kk57w) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

@orizi @liorgold2
</blockquote></details>

Yes, but not now, as this will be only in the next sierra minor release.

___

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4228)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4228#-NgISXY31u4nG1AUq1At:-NgIqfc0DL21U4Yl_k9h:b-tk275n) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Yes, but not now, as this will be only in the next sierra minor release.
</blockquote></details>

Do we target for this to happen in 2.3.0 or later?

___

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4228)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4228#-NgISXY31u4nG1AUq1At:-NgIsRY2DOx9h--0Ko8b:b-x61611) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Do we target for this to happen in 2.3.0 or later?
</blockquote></details>

Later, 2.3.0 has no sierra updates.

___

**Pull request merged**
