### PR TITLE
Lowering: Move refindex from Variable to Statement

### PR DESCRIPTION
**Pull request by spapinistarkware**
commit-id:267e9d84

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1659)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/objects.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1659#-NL0uOxgDtXIhB4ix6nk:-NL0uOxgDtXIhB4ix6nl:b-427009) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb110b20be9dcb0aad3036a740f5eddf3c45eb1/crates/cairo-lang-lowering/src/objects.rs#L150)):*
> ```XML
> 
> #[derive(Clone, Debug, PartialEq, Eq)]
> pub struct StructuredStatement {
> ```

I know that naming is hard.

but why is
statement + ref_changes a StructuredStatement?



_Code quote:_
```XML
StructuredStatement 
```
___
*[`crates/cairo-lang-lowering/src/objects.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1659#-NL0uBMT2Y5r5QM5ruSV:-NL0uBMU42puGdGgxjiq:b-qfuhv7) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb110b20be9dcb0aad3036a740f5eddf3c45eb1/crates/cairo-lang-lowering/src/objects.rs#L153)):*
> ```XML
>     pub statement: Statement,
>     // TODO(spapini): Wrap ref index in a type.
>     pub ref_changes: OrderedHashMap<usize, VariableId>,
> ```

You don't mention deletes here, right?
 + document.



_Suggestion:_
```XML
ref_updates
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1659)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/objects.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1659#-NL0uOxgDtXIhB4ix6nk:-NL0uZgTB0fqjai9Ktxg:b1qpugb) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb110b20be9dcb0aad3036a740f5eddf3c45eb1/crates/cairo-lang-lowering/src/objects.rs#L150)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I know that naming is hard.

but why is
statement + ref_changes a StructuredStatement?

</blockquote></details>

Currenty there are 2 representations here. Structured and Flat. Me an Ori spent like 30 minutes tryint to come up with names.

Eveything else is named accordingly. Things in the first repr are Structured, and in the second Flat.
___
*[`crates/cairo-lang-lowering/src/objects.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1659#-NL0uBMT2Y5r5QM5ruSV:-NL0un3K53O73-QlMuR_:b-a8k3rf) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb110b20be9dcb0aad3036a740f5eddf3c45eb1/crates/cairo-lang-lowering/src/objects.rs#L153)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

You don't mention deletes here, right?
 + document.

</blockquote></details>

Next PR?

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1659)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1659#-NL0uuTt911GHXwzcYUv:-NL0uuTt911GHXwzcYUw:b2eekad) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb110b20be9dcb0aad3036a740f5eddf3c45eb1/crates/cairo-lang-lowering/src/lower/scope.rs#L83)):*
> ```XML
>         {
>             let index = ctx.implicits.len() + ref_index;
>             if let Some(stmt) = self.statements.last_mut() {
> ```

how do you know that you need to update the last statement?



_Code quote:_
```XML
self.statements.last_mut() 
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1659)* status: 1 of 8 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/objects.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1659#-NL0vw6W9YqLcuNDQyV1:-NL0vw6W9YqLcuNDQyV2:b8t0zlf) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb110b20be9dcb0aad3036a740f5eddf3c45eb1/crates/cairo-lang-lowering/src/objects.rs#L153)):*
> ```XML
>     pub statement: Statement,
>     // TODO(spapini): Wrap ref index in a type.
>     pub ref_changes: OrderedHashMap<usize, VariableId>,
> ```

Are the changes enougth? didn'y you talk about keeping track of all the reference in every statement?



_Code quote:_
```XML
pub ref_changes: OrderedHashMap<usize, VariableId>,
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/objects.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1659#-NL0vw6W9YqLcuNDQyV1:-NL18IN3B4JPk1Kxyamw:b4m1qxx) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb110b20be9dcb0aad3036a740f5eddf3c45eb1/crates/cairo-lang-lowering/src/objects.rs#L153)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Are the changes enougth? didn'y you talk about keeping track of all the reference in every statement?
</blockquote></details>

please document that this is immediatly after the statement and add an example.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1659)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/objects.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1659#-NL0vw6W9YqLcuNDQyV1:-NLKzQk88uHRp_22BzBW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb110b20be9dcb0aad3036a740f5eddf3c45eb1/crates/cairo-lang-lowering/src/objects.rs#L153)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

please document that this is immediatly after the statement and add an example.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1659#-NL0uuTt911GHXwzcYUv:-NL0wwL1CXp6ykiEJ0aF:b-whe17) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb110b20be9dcb0aad3036a740f5eddf3c45eb1/crates/cairo-lang-lowering/src/lower/scope.rs#L83)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

how do you know that you need to update the last statement?
</blockquote></details>

There are statement, and between statement there are ref bindings. e.g.
```
foo(ref x){
y = f()
x=y
y=z
g(x)
}
```

Since my output is only statements, the question is where to put the bindings.
It makes sense to me to put the changes on the last statement, or on the initial_ref_changes.
___
*[`crates/cairo-lang-lowering/src/lower/scope/generators.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1659#-NL0vKBkDmpdMX8PKmAd:-NLKzOe5DOnX6UT8MHwo:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb110b20be9dcb0aad3036a740f5eddf3c45eb1/crates/cairo-lang-lowering/src/lower/scope/generators.rs#L181)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't like the usage of into here.

maybe
StructuredStatement::WithoutRefUpdates(statement)?

</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1659)* status: all files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 168 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1659#-NLLA6jJ2eY_IidhKUiU:-NLLA6jKCTryg7Q1-ctC:b-hfpv23) ([raw file](https://github.com/starkware-libs/cairo/blob/4ede3e7413224661c7583c137f05a9bbc0bd9565/crates/cairo-lang-lowering/src/lower/scope.rs#L168)):*
> ```XML
> 
>     pub fn push_statement(&mut self, stmt: Statement) {
>         println!("stmt: {:?}", stmt);
> ```

remove.



_Code quote:_
```XML
 println!("stmt: {:?}", stmt);
```
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 173 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1659#-NLLA95s9ZG6qUGpfJog:-NLLA95s9ZG6qUGpfJoh:b-hfpv23) ([raw file](https://github.com/starkware-libs/cairo/blob/4ede3e7413224661c7583c137f05a9bbc0bd9565/crates/cairo-lang-lowering/src/lower/scope.rs#L173)):*
> ```XML
> 
>     pub fn finalize_statement(&mut self) {
>         println!("finalize");
> ```

remove.



_Code quote:_
```XML
  println!("finalize");
```
___
*[`crates/cairo-lang-lowering/src/lower/scope/generators.rs` line 100 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1659#-NLLBCy166DNTvoMxv2h:-NLLBCy166DNTvoMxv2i:b-wnpyo8) ([raw file](https://github.com/starkware-libs/cairo/blob/4ede3e7413224661c7583c137f05a9bbc0bd9565/crates/cairo-lang-lowering/src/lower/scope/generators.rs#L100)):*
> ```XML
> 
> /// Generator for [StatementCallBlock].
> /// Note that scope.finalize_statement() must be manually called after ref bindings.
> ```

I think.



_Suggestion:_
```XML
 called manually 
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1659)* status: all files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1659#-NL0uuTt911GHXwzcYUv:-NLLBeTt0NFtBcVykqPg:bmlsbh3) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb110b20be9dcb0aad3036a740f5eddf3c45eb1/crates/cairo-lang-lowering/src/lower/scope.rs#L83)):*
> initial_ref_changes
Is there a situation where initial_ref_changes changes?

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1659)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/test_data/rebindings` line 9 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1659#-NLLXL9-9WfQqH2K3EOC:-NLLXL9-9WfQqH2K3EOD:b-fh3osg) ([raw file](https://github.com/starkware-libs/cairo/blob/7d32cd3ac946a3b2cf7ad6d50c5902f32a1a6ef8/crates/cairo-lang-lowering/src/test_data/rebindings#L9)):*
> ```
> fn foo(ref a: felt, b: felt) {
>     a = b;
>     bar()
> ```

What happens if there are renames after bar?



_Suggestion:_
```
 a = bar()
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1659)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/test_data/rebindings` line 9 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1659#-NLLXL9-9WfQqH2K3EOC:-NLLYpXn6WWiYtwI5YdT:bxfq1e6) ([raw file](https://github.com/starkware-libs/cairo/blob/7d32cd3ac946a3b2cf7ad6d50c5902f32a1a6ef8/crates/cairo-lang-lowering/src/test_data/rebindings#L9)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

What happens if there are renames after bar?
</blockquote></details>

They will be discarded, which is ok.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1659)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/test_data/rebindings` line 9 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1659#-NLLXL9-9WfQqH2K3EOC:-NLLZ0L4ETbZTDp5tXqe:b8vlf4a) ([raw file](https://github.com/starkware-libs/cairo/blob/7d32cd3ac946a3b2cf7ad6d50c5902f32a1a6ef8/crates/cairo-lang-lowering/src/test_data/rebindings#L9)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

They will be discarded, which is ok.
</blockquote></details>

Not that it will be on the ScopeEnd::Return

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1659)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/test_data/rebindings` line 9 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1659#-NLLXL9-9WfQqH2K3EOC:-NLLZDa853BrIHXN3z4z:b-83od59) ([raw file](https://github.com/starkware-libs/cairo/blob/7d32cd3ac946a3b2cf7ad6d50c5902f32a1a6ef8/crates/cairo-lang-lowering/src/test_data/rebindings#L9)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Not that it will be on the ScopeEnd::Return
</blockquote></details>

Note*

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 8 files at r1, 6 of 9 files at r3, 4 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1659)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
