### PR TITLE
Split sierra version and allowed libfuncs.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2055)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 10 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2055)* status: 10 of 14 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/cli.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2055#-NNgHWDeDuJs0151RV-5:-NNgHWDeDuJs0151RV-6:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/97abe5b06ec8110c33d568c58a8405f9b2c1f319/crates/cairo-lang-starknet/src/cli.rs#L23)):*
> ```XML
>     /// The allowed libfuncs list to use (default: most recent audited list).
>     #[arg(short, long)]
>     allowed_libfuncs_list_name: Option<String>,
> ```





_Suggestion:_
```XML
    #[arg(long)]
    allowed_libfuncs_list_name: Option<String>,
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2055)* status: 9 of 14 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/cli.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2055#-NNgHWDeDuJs0151RV-5:-NNgMsRs6hZBDl4nV0Y2:bsnkq1h) ([raw file](https://github.com/starkware-libs/cairo/blob/97abe5b06ec8110c33d568c58a8405f9b2c1f319/crates/cairo-lang-starknet/src/cli.rs#L23)):*
> ```XML
>     /// The allowed libfuncs list to use (default: most recent audited list).
>     #[arg(short, long)]
>     allowed_libfuncs_list_name: Option<String>,
> ```

Done.
But if we only allow the long name this name is too long. I thought maybe `libfuncs_list` but it seems ambiguous to me, WDYT?

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 14 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2055)* status: 11 of 14 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 68 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2055#-NNkjjUFCg0V90Gu1ktH:-NNkjjUGErp9k5ujrWcx:bnf4tz5) ([raw file](https://github.com/starkware-libs/cairo/blob/0a45a9340700c25a2dfe27f7c596a479593f6540/crates/cairo-lang-starknet/src/contract_class.rs#L68)):*
> ```XML
>                 return Err(AllowedLibfuncsError::UnsupportedLibfunc {
>                     invalid_libfunc: match self
>                         .sierra_program_debug_info
> ```

Do we have to use the debug info here?



_Code quote:_
```XML
 .sierra_program_debug_info
```

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 14 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2055)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/cli.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2055#-NNgHWDeDuJs0151RV-5:-NNgNzdx0NHTlfQCD9VD:b7nesl1) ([raw file](https://github.com/starkware-libs/cairo/blob/97abe5b06ec8110c33d568c58a8405f9b2c1f319/crates/cairo-lang-starknet/src/cli.rs#L23)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Done.
But if we only allow the long name this name is too long. I thought maybe `libfuncs_list` but it seems ambiguous to me, WDYT? 
</blockquote></details>

the short name would be `-a` which is really meaningless
___
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 68 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2055#-NNkjjUFCg0V90Gu1ktH:-NNkmXg55gAu5BXDEjzn:b-dplsny) ([raw file](https://github.com/starkware-libs/cairo/blob/0a45a9340700c25a2dfe27f7c596a479593f6540/crates/cairo-lang-starknet/src/contract_class.rs#L68)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Do we have to use the debug info here?
</blockquote></details>

agreed - you should probably use the generic id directly in the err-msg.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 10 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2055#-:-NNqJEce1rcd__qp4XLz:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2055)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 68 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2055#-NNkjjUFCg0V90Gu1ktH:-NNqSNxy3QnH9_vU8Lwd:bvtogs2) ([raw file](https://github.com/starkware-libs/cairo/blob/0a45a9340700c25a2dfe27f7c596a479593f6540/crates/cairo-lang-starknet/src/contract_class.rs#L68)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

agreed - you should probably use the generic id directly in the err-msg.
</blockquote></details>

It's not a must, we can always use the generic id as Ori suggested, but it's not really readable for the user.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2055#-:-NO5YTPA1sDH8SrLkIbC:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2055#-:-NO5fwTq9OMskOFnm7we:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2055)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2055)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
