### PR TITLE
Make Felt252Serde::deserialize more efficient.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5126)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 36 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5126)* status: 2 of 36 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/array.cairo` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5126#-NrG5_0H1bJqXFTFTvud:-NrG5_0H1bJqXFTFTvue:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/46cffbcecbeb15fcd4568c56a07defdf06559be5/corelib/src/array.cairo#L17)):*
> ```Cairo
> extern fn array_pop_front_consume<T>(arr: Array<T>) -> Option<(Array<T>, Box<T>)> nopanic;
> pub extern fn array_snapshot_pop_front<T>(ref arr: @Array<T>) -> Option<Box<@T>> nopanic;
> extern fn array_snapshot_pop_back<T>(ref arr: @Array<T>) -> Option<Box<@T>> nopanic;
> ```





_Suggestion:_
```Cairo
extern fn array_pop_front_consume<T>(arr: Array<T>) -> Option<(Array<T>, Box<T>)> nopanic;
pub(crate) extern fn array_snapshot_pop_front<T>(ref arr: @Array<T>) -> Option<Box<@T>> nopanic;
extern fn array_snapshot_pop_back<T>(ref arr: @Array<T>) -> Option<Box<@T>> nopanic;
```
___
*[`corelib/src/array.cairo` line 135 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5126#-NrG5b64DTSDBLCmGYq3:-NrG5b64DTSDBLCmGYq4:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/46cffbcecbeb15fcd4568c56a07defdf06559be5/corelib/src/array.cairo#L135)):*
> ```Cairo
> // Span.
> pub struct Span<T> {
>     pub snapshot: @Array<T>
> ```





_Suggestion:_
```Cairo
    pub(crate) snapshot: @Array<T>
```

**Review by orizi — COMMENTED** [review]
> Reviewed 16 of 36 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5126)* status: 18 of 36 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 18 of 36 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5126#-:-NrG6kMp00hXZAmp4Bp0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5126)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/array.cairo` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5126#-NrG5_0H1bJqXFTFTvud:-NrG6A_71AChv979UUUK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/46cffbcecbeb15fcd4568c56a07defdf06559be5/corelib/src/array.cairo#L17)):*
> ```Cairo
> extern fn array_pop_front_consume<T>(arr: Array<T>) -> Option<(Array<T>, Box<T>)> nopanic;
> pub extern fn array_snapshot_pop_front<T>(ref arr: @Array<T>) -> Option<Box<@T>> nopanic;
> extern fn array_snapshot_pop_back<T>(ref arr: @Array<T>) -> Option<Box<@T>> nopanic;
> ```

Done.
___
*[`corelib/src/array.cairo` line 135 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5126#-NrG5b64DTSDBLCmGYq3:-NrG6AycCJT5cgkGDeh9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/46cffbcecbeb15fcd4568c56a07defdf06559be5/corelib/src/array.cairo#L135)):*
> ```Cairo
> // Span.
> pub struct Span<T> {
>     pub snapshot: @Array<T>
> ```

Done.

**Pull request merged**
