### PR TITLE
Added SyscallResult and unwrap_syscall member.

### PR DESCRIPTION
**Pull request by orizi**
Using them wherever possible.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1885)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1885)* status: 7 of 17 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/starknet.cairo` line 125 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1885#-NMZMZUg1ElXoIVR0VpZ:-NMZMZUh-n1UbnfIRct4:b-jafz5c) ([raw file](https://github.com/starkware-libs/cairo/blob/95388cb3691431870269cb7dbb151cb07fbf0357/corelib/starknet.cairo#L125)):*
> ```Cairo
> }
> 
> /// The result type for a simple syscall.
> ```

why simple?



_Suggestion:_
```Cairo
syscall
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1885)* status: 7 of 17 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/starknet.cairo` line 133 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1885#-NMZNPCI4Iq5BiW4tScx:-NMZNPCI4Iq5BiW4tScy:blmsuqy) ([raw file](https://github.com/starkware-libs/cairo/blob/95388cb3691431870269cb7dbb151cb07fbf0357/corelib/starknet.cairo#L133)):*
> ```Cairo
> }
> impl SyscallResultTraitImpl<T> of SyscallResultTrait::<T> {
>     fn unwrap_syscall(self: SyscallResult::<T>) -> T {
> ```

Does it make sense to always inline it?



_Code quote:_
```Cairo
 fn unwrap_syscall(self: SyscallResult::<T>) -> T
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1885)* status: 7 of 17 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/starknet.cairo` line 125 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1885#-NMZMZUg1ElXoIVR0VpZ:-NMZNcDd7bjYOaXVXvAV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/95388cb3691431870269cb7dbb151cb07fbf0357/corelib/starknet.cairo#L125)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why simple?
</blockquote></details>

Done.
___
*[`corelib/starknet.cairo` line 133 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1885#-NMZNPCI4Iq5BiW4tScx:-NMZNfck7QCVGHY7FNRr:b-185qaf) ([raw file](https://github.com/starkware-libs/cairo/blob/95388cb3691431870269cb7dbb151cb07fbf0357/corelib/starknet.cairo#L133)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Does it make sense to always inline it?
</blockquote></details>

it may makes sense - but it is not supported yet anyway.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 9 of 17 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1885#-:-NMZOUwz0APDx8P7KDnG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
