### PR TITLE
Add Generated Closure Drop, Destruct or PanicDestruct.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6209)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6209)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference/solver.rs` line 252 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6209#-O4FOD8sAkBwOchmTzBY:-O4FOD8sAkBwOchmTzBZ:b2nhdkj) ([raw file](https://github.com/starkware-libs/cairo/blob/a0490b417efd2f7ffe2e69cb7e928b8d94d15d0e/crates/cairo-lang-semantic/src/expr/inference/solver.rs#L252)):*
> ```XML
> }
> 
> fn add_generated_impl(
> ```

Doc

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6209)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/closure` line 23 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6209#-O4FePka1xruQkycGdyC:-O4FePka1xruQkycGdyD:baln6bz) ([raw file](https://github.com/starkware-libs/cairo/blob/ee6e9a91d68effd370b4bbb26a270052366e86e9/crates/cairo-lang-lowering/src/borrow_check/test_data/closure#L23)):*
> ```
> error: Unsupported feature.
>  --> lib.cairo:2:5
>     |b: u32| {
> ```

add Destruct and PanicDestruct tests.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/inference/solver.rs` line 252 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6209#-O4FOD8sAkBwOchmTzBY:-O4JjNtkElyj_q7KIl4c:b-ddemxj) ([raw file](https://github.com/starkware-libs/cairo/blob/a0490b417efd2f7ffe2e69cb7e928b8d94d15d0e/crates/cairo-lang-semantic/src/expr/inference/solver.rs#L252)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Doc
</blockquote></details>

done + moved.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6209)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @orizi and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/closure` line 23 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6209#-O4FePka1xruQkycGdyC:-O4JjLCT8Kl-vRgNdeAs:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ee6e9a91d68effd370b4bbb26a270052366e86e9/crates/cairo-lang-lowering/src/borrow_check/test_data/closure#L23)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add Destruct and PanicDestruct tests.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6209#-:-O4JkFr88z-236aiPjKg:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
