### PR TITLE
Added panic info on failures in cairo tests.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:de276472

---

**Stack**:
- #1416
- #1415
- #1414 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1414)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @Alon-Ti and @orizi)

___
*[`crates/test_runner/src/cli.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1414#-NJnzhXCAjliBz-TK9Uu:-NJnzhXCAjliBz-TK9Uv:bds8iir) ([raw file](https://github.com/starkware-libs/cairo/blob/f7a7a802fb4e450f15e43d5d77cc79e570f3ea61/crates/test_runner/src/cli.rs#L101)):*
> ```XML
>                         let mut is_end = false;
>                         let mut as_string = String::default();
>                         if bytes.iter().all(|byte| {
> ```

This seems useful. I suggest making a util to extract a string.



_Code quote:_
```XML
                    for value in &values {
                        let bytes = value.to_bytes_be().1;
                        let mut is_end = false;
                        let mut as_string = String::default();
                        if bytes.iter().all(|byte| {
                            if *byte == 0 {
                                is_end = true;
                                true
                            } else if is_end || !byte.is_ascii() {
                                false
                            } else {
                                as_string.push(*byte as char);
                                true
                            }
                        }) {
                            print!("{value} ('{as_string}'), ");
                        } else {
                            print!("{value}, ",);
                        }
```

**Review by spapinistarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1414)* status: all files reviewed, 1 unresolved discussion (waiting on @Alon-Ti and @orizi)

**Review by spapinistarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1414)* status: all files reviewed, 1 unresolved discussion (waiting on @Alon-Ti and @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1414)* status: all files reviewed, 1 unresolved discussion (waiting on @Alon-Ti and @spapinistarkware)

___
*[`crates/test_runner/src/cli.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1414#-NJnzhXCAjliBz-TK9Uu:-NJo0GM_CwlFER-ux4fH:b-cltfgz) ([raw file](https://github.com/starkware-libs/cairo/blob/b6aac5c99f9c214b8a5d40b280f2f0775aa8bc55/crates/test_runner/src/cli.rs#L101)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This seems useful. I suggest making a util to extract a string.
</blockquote></details>

moving into a function, and adding a todo - as i don't know where exactly is the best place to put this.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1414)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Alon-Ti)

**Pull request merged**
