### PR TITLE
Made name multiple usage errors point at the name itself.

### PR DESCRIPTION
**Pull request by orizi**
this made plugin based errors of named more readable.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2332)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2332)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-defs/src/db.rs` line 584 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2332#-NPSzYRb0L2ZN8j8yI55:-NPSzYRb0L2ZN8j8yI56:b-afhm4p) ([raw file](https://github.com/starkware-libs/cairo/blob/ed8abd02d89f6640a5dde0a59a40f1a81751ead4/crates/cairo-lang-defs/src/db.rs#L584)):*
> ```XML
>                 .last()
>                 .map(|last| last.stable_ptr().untyped())
>                 .unwrap_or_else(|| use_path.stable_ptr().untyped())
> ```

Can you trigger this in a test?



_Code quote:_
```XML
  .unwrap_or_else(|| use_path.stable_ptr().untyped())
```

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2332#-:-NPSzel39Ivl2FATlZ5l:bnfp4nl)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2332)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-defs/src/db.rs` line 584 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2332#-NPSzYRb0L2ZN8j8yI55:-NPSzxSkDRz2yhAhJPQB:b-7m3ayv) ([raw file](https://github.com/starkware-libs/cairo/blob/ed8abd02d89f6640a5dde0a59a40f1a81751ead4/crates/cairo-lang-defs/src/db.rs#L584)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Can you trigger this in a test?
</blockquote></details>

i don't know how to create a use without a path - especially one that collides with another item.
this is just for safety's sake.

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2332)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Pull request merged**
