### PR TITLE
Split generation data: contracts/components

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3929)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 11 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3929)* status: 11 of 12 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/cairo-lang-defs/src/patcher.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3929#-Nc2fUCj1MkZKaC7Q8rq:-Nc2fUCj1MkZKaC7Q8rr:b-e2riz) ([raw file](https://github.com/starkware-libs/cairo/blob/042f99e1f106b55d10b8e5f9fbeea30ae836876f/crates/cairo-lang-defs/src/patcher.rs#L47)):*
> ```XML
>         Self::empty()
>     }
> }
> ```

move under the main impl of the class.

as only the impl without a trait can be right after the declaration (without an empty line)



_Code quote:_
```XML
impl Default for RewriteNode {
    fn default() -> Self {
        Self::empty()
    }
}
```
___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3929#-Nc2fhS77BdtisNMjt1E:-Nc2fhS77BdtisNMjt1F:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/042f99e1f106b55d10b8e5f9fbeea30ae836876f/crates/cairo-lang-starknet/src/plugin/contract.rs#L97)):*
> ```XML
> 
> #[derive(Default)]
> struct ContractGenerationData {
> ```

doc
___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3929#-Nc2gGd_0HucbnKqw8QX:-Nc2gGd_0HucbnKqw8QY:b-wu32dn) ([raw file](https://github.com/starkware-libs/cairo/blob/042f99e1f106b55d10b8e5f9fbeea30ae836876f/crates/cairo-lang-starknet/src/plugin/contract.rs#L123)):*
> ```XML
>         RewriteNode::interpolate_patched(
>             "$common$
> $specific$",
> ```

indoc or



_Suggestion:_
```XML
            "$common$\n$specific$",
```
___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 175 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3929#-Nc2gUbw7aj2hR2SS0UK:-Nc2gUbw7aj2hR2SS0UL:becye2x) ([raw file](https://github.com/starkware-libs/cairo/blob/042f99e1f106b55d10b8e5f9fbeea30ae836876f/crates/cairo-lang-starknet/src/plugin/contract.rs#L175)):*
> ```XML
>         );
>         RewriteNode::interpolate_patched(
>             "$test_config$
> ```

indoc

or just add another function in RewriteNode::join(Iter, sep)

and use it around.
___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 384 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3929#-Nc2fy_iCKojH2ppwRjD:-Nc2fy_iCKojH2ppwRjE:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/042f99e1f106b55d10b8e5f9fbeea30ae836876f/crates/cairo-lang-starknet/src/plugin/contract.rs#L384)):*
> ```XML
> }
> 
> fn handle_component_item(
> ```

doc

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3929)* status: 11 of 12 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-defs/src/patcher.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3929#-Nc2fUCj1MkZKaC7Q8rq:-NcH1Om_EnVooV4QQFLZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/042f99e1f106b55d10b8e5f9fbeea30ae836876f/crates/cairo-lang-defs/src/patcher.rs#L47)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

move under the main impl of the class.

as only the impl without a trait can be right after the declaration (without an empty line)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3929#-Nc2fhS77BdtisNMjt1E:-NcH26Nz-r7_lSyH7qLk:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/042f99e1f106b55d10b8e5f9fbeea30ae836876f/crates/cairo-lang-starknet/src/plugin/contract.rs#L97)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3929#-Nc2gGd_0HucbnKqw8QX:-NcH2AsG360c4ZZ1-SlV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/042f99e1f106b55d10b8e5f9fbeea30ae836876f/crates/cairo-lang-starknet/src/plugin/contract.rs#L123)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

indoc or
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 175 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3929#-Nc2gUbw7aj2hR2SS0UK:-NcH3mzR0_QPRFs5hS9G:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/042f99e1f106b55d10b8e5f9fbeea30ae836876f/crates/cairo-lang-starknet/src/plugin/contract.rs#L175)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

indoc

or just add another function in RewriteNode::join(Iter, sep)

and use it around.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 384 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3929#-Nc2fy_iCKojH2ppwRjD:-NcHCEH36PVZ1cPv-ysc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/042f99e1f106b55d10b8e5f9fbeea30ae836876f/crates/cairo-lang-starknet/src/plugin/contract.rs#L384)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3929#-:-NcHE49sCgDq_8RgjCFt:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3929)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
