### PR TITLE
Add default trait.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2677)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2677)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`corelib/src/integer.cairo` line 1140 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2677#-NS-imn57eeqma7X6nR2:-NS-imn57eeqma7X6nR3:b-sbv6g7) ([raw file](https://github.com/starkware-libs/cairo/blob/d70ca52ceba78337dca80f76e903d1583b39b302/corelib/src/integer.cairo#L1140)):*
> ```Cairo
> 
> impl Felt252Default of Default::<felt252> {
>     #[inline(always)]
> ```

not part of integer lib.



_Code quote:_
```Cairo
/// Default values

impl Felt252Default of Default::<felt252> {
    #[inline(always)]
    fn default() -> felt252 nopanic {
        0
    }
}
```

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2677)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2677)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/integer.cairo` line 1140 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2677#-NS-imn57eeqma7X6nR2:-NS-l0Y292HrVA7q85Dx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d70ca52ceba78337dca80f76e903d1583b39b302/corelib/src/integer.cairo#L1140)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

not part of integer lib.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2677)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`corelib/src/traits.cairo` line 113 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2677#-NS-qUQHD0tBBZ-L3keW:-NS-qUQHD0tBBZ-L3keX:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/eb2fc9d4b63bbabf66decf60aafb2c345d882111/corelib/src/traits.cairo#L113)):*
> ```Cairo
> }
> 
> trait Default<T> {
> ```

.



_Suggestion:_
```Cairo
trait Default<T> {
    fn default() -> T;
}
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2677)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/traits.cairo` line 113 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2677#-NS-qUQHD0tBBZ-L3keW:-NS-rUnw2DTO8BRugCKi:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/eb2fc9d4b63bbabf66decf60aafb2c345d882111/corelib/src/traits.cairo#L113)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2677#-:-NS-tFzhCnxVVGkgjkyn:bnfp4nl)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
