### PR TITLE
Fix binary name.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1640)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1640)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-syntax-codegen/src/golden_test.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1640#-NKvxVFMExFc1Byka7_C:-NKvxVFMExFc1Byka7_D:b-ebofjy) ([raw file](https://github.com/starkware-libs/cairo/blob/8644d98164dc3f21e9dc7f35257a1a7392aff27b/crates/cairo-lang-syntax-codegen/src/golden_test.rs#L14)):*
> ```XML
>             panic!(
>                 "Some files are not up to date. Please run `cargo run --bin \
>                  cairo-lang-generate-syntax`"
> ```

is the binary name change intentional?



_Code quote:_
```XML
cairo-lang-generate-syntax
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1640)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-syntax-codegen/src/golden_test.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1640#-NKvxVFMExFc1Byka7_C:-NKvxniY-kSLUP8aqb6t:b-l1n93t) ([raw file](https://github.com/starkware-libs/cairo/blob/8644d98164dc3f21e9dc7f35257a1a7392aff27b/crates/cairo-lang-syntax-codegen/src/golden_test.rs#L14)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

is the binary name change intentional?
</blockquote></details>

@spapinistarkware

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1640#-:-NKw4M6D6Knbw2NbSObn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1640)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-syntax-codegen/src/golden_test.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1640#-NKvxVFMExFc1Byka7_C:-NKwAORu43DQjCYWPI0h:b-n5ms1u) ([raw file](https://github.com/starkware-libs/cairo/blob/8644d98164dc3f21e9dc7f35257a1a7392aff27b/crates/cairo-lang-syntax-codegen/src/golden_test.rs#L14)):*
> cairo-lang-generate-syntax
reverted the binary name change.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1640)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
