### PR TITLE
Add cairo_keccak_uint256s.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2916)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
Decided on a different approch

**Comment by ilyalesokhin-starkware** [comment]
went back to this approch.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2916)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`corelib/src/test/keccak_test.cairo` line 39 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2916#-NTrc4O65GWB8DoR2x5z:-NTrc4O65GWB8DoR2x6-:bvj3wht) ([raw file](https://github.com/starkware-libs/cairo/blob/b7d795c3569cde304fabdbf0f830f0c4abc183af/corelib/src/test/keccak_test.cairo#L39)):*
> ```Cairo
>     input.append(u256 { low: 1, high: 0 });
> 
>     assert(input.len() == 1, 'Wrong input length');
> ```

i don't think this is relevant for the test.



_Code quote:_
```Cairo
    assert(input.len() == 1, 'Wrong input length');
```
___
*[`corelib/src/test/keccak_test.cairo` line 49 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2916#-NTrc89SDr5BAXj5qaaL:-NTrc89SDr5BAXj5qaaM:b-n9qbk7) ([raw file](https://github.com/starkware-libs/cairo/blob/b7d795c3569cde304fabdbf0f830f0c4abc183af/corelib/src/test/keccak_test.cairo#L49)):*
> ```Cairo
>     input.append(u256 { low: 4, high: 0 });
> 
>     assert(input.len() == 4, 'Wrong input length');
> ```

so is this.



_Code quote:_
```Cairo
    assert(input.len() == 4, 'Wrong input length');
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2916)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`corelib/src/test/keccak_test.cairo` line 39 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2916#-NTrc4O65GWB8DoR2x5z:-NUFtVhs-rmiHqqrSkpu:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b7d795c3569cde304fabdbf0f830f0c4abc183af/corelib/src/test/keccak_test.cairo#L39)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i don't think this is relevant for the test.
</blockquote></details>

Done.
___
*[`corelib/src/test/keccak_test.cairo` line 49 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2916#-NTrc89SDr5BAXj5qaaL:-NUFtWSN2QYkjUkGvLCH:bo2eeh7) ([raw file](https://github.com/starkware-libs/cairo/blob/b7d795c3569cde304fabdbf0f830f0c4abc183af/corelib/src/test/keccak_test.cairo#L49)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

so is this.
</blockquote></details>

I thought it made it easier to understand what is the input the the keccak.

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2916)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2916#-:-NUGu52l1KZUUM9MreQx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
