### PR TITLE
Refactored hints formatting for simpler usage.

### PR DESCRIPTION
**Pull request by orizi**
Fixed dict hints on the way.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1697)

### CODE REVIEW

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1697#-:-NLH3M1y2bflRPWoscLB:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 455 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1697#-NLH33Eq6D3E4vjYxbYn:-NLH33Er8c5CfCs7cKau:b7ss6dt) ([raw file](https://github.com/starkware-libs/cairo/blob/86461a9d97d92a2aad5f10efde5b6b742c727bbb/crates/cairo-lang-casm/src/hints/mod.rs#L455)):*
> ```XML
>                 f,
>                 "
>                     
> ```

Whitespaces

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1697)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1697)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1697)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
