### PR TITLE
Add contract test based on the contracts crate.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4206)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4206)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-plugins/src/lib.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4206#-Nfv0Wb_27ECTkJ29y4U:-Nfv0Wb_27ECTkJ29y4V:b-abmcwk) ([raw file](https://github.com/starkware-libs/cairo/blob/e9ec02ff2d931d58b4f2e837ddea52a81d7b42ac/crates/cairo-lang-plugins/src/lib.rs#L9)):*
> ```XML
> 
> pub mod plugins;
> pub mod test_utils;
> ```

add testing feature.



_Code quote:_
```XML
pub mod test_utils;
```
___
*[`crates/cairo-lang-plugins/src/test_utils.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4206#-Nfv0lcsB3kd_TKczftF:-Nfv0lcsB3kd_TKczftG:b4b0tqv) ([raw file](https://github.com/starkware-libs/cairo/blob/e9ec02ff2d931d58b4f2e837ddea52a81d7b42ac/crates/cairo-lang-plugins/src/test_utils.rs#L45)):*
> ```XML
>             }
>         } else if let ModuleItemId::Use(use_id) = item_id {
>             let mut use_item = use_id.stable_ptr(db).lookup(syntax_db).as_syntax_node();
> ```

doc here why you do this.
___
*[`crates/cairo-lang-starknet/src/test_utils.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4206#-Nfv12CM9xF3RoSz5psZ:-Nfv12CM9xF3RoSz5ps_:b-vpb1l0) ([raw file](https://github.com/starkware-libs/cairo/blob/e9ec02ff2d931d58b4f2e837ddea52a81d7b42ac/crates/cairo-lang-starknet/src/test_utils.rs#L41)):*
> ```XML
> 
> /// Salsa database configured to find the corelib, and the contracts crate. When reused by different
> /// tests should be able to use the cached queries that rely on the corelib's code, which vastly
> ```

this is true for all queries - not just the corelib queries.



_Code quote:_
```XML
cached queries that rely on the corelib's code
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4206)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4206)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-plugins/src/lib.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4206#-Nfv0Wb_27ECTkJ29y4U:-Nfv2qM56o98fRvJNOtj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e9ec02ff2d931d58b4f2e837ddea52a81d7b42ac/crates/cairo-lang-plugins/src/lib.rs#L9)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add testing feature.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-plugins/src/test_utils.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4206#-Nfv0lcsB3kd_TKczftF:-Nfv3E9E3ylZTD97UVII:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e9ec02ff2d931d58b4f2e837ddea52a81d7b42ac/crates/cairo-lang-plugins/src/test_utils.rs#L45)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc here why you do this.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/test_utils.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4206#-Nfv12CM9xF3RoSz5psZ:-Nfv3ZdS8YHTIWbWlZKh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e9ec02ff2d931d58b4f2e837ddea52a81d7b42ac/crates/cairo-lang-starknet/src/test_utils.rs#L41)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is true for all queries - not just the corelib queries.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4206)* status: 8 of 12 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-plugins/src/test_utils.rs` line 18 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4206#-Nfv4wcF2VH6hjpxh0o0:-Nfv4wcF2VH6hjpxh0o1:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ce42b9b0f37404689efeb17e063624772b0f57bd/crates/cairo-lang-plugins/src/test_utils.rs#L18)):*
> ```XML
>     let mut output = String::new();
>     // A collection of all the use statements in the module.
>     let mut uses_list = OrderedHashSet::default();
> ```





_Suggestion:_
```XML
    let mut uses_list = UnorderedHashSet::default();
```
___
*[`crates/cairo-lang-plugins/src/test_utils.rs` line 64 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4206#-Nfv4_Si9UDCi7kwilK4:-Nfv4_Si9UDCi7kwilK5:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ce42b9b0f37404689efeb17e063624772b0f57bd/crates/cairo-lang-plugins/src/test_utils.rs#L64)):*
> ```XML
>     let use_statements =
>         uses_list.iter().map(|use_statement| use_statement.get_text(syntax_db)).join("");
>     use_statements + &output
> ```





_Suggestion:_
```XML
            }
            if uses_list.insert(use_item) {
                output.push_str(&use_item.get_text(syntax_db));
            }
            continue;
        }
        let syntax_item = item_id.untyped_stable_ptr(db);
        // Output other items as is.
        output.push_str(&syntax_item.lookup(syntax_db).get_text(syntax_db));
    }
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4206)* status: 9 of 12 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4206)* status: 8 of 12 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-plugins/src/test_utils.rs` line 18 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4206#-Nfv4wcF2VH6hjpxh0o0:-NfwMmnKDuWH0ZokmnJS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ce42b9b0f37404689efeb17e063624772b0f57bd/crates/cairo-lang-plugins/src/test_utils.rs#L18)):*
> ```XML
>     let mut output = String::new();
>     // A collection of all the use statements in the module.
>     let mut uses_list = OrderedHashSet::default();
> ```

Done.
___
*[`crates/cairo-lang-plugins/src/test_utils.rs` line 64 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4206#-Nfv4_Si9UDCi7kwilK4:-NfwMnJlD6KSag7W85t2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ce42b9b0f37404689efeb17e063624772b0f57bd/crates/cairo-lang-plugins/src/test_utils.rs#L64)):*
> ```XML
>     let use_statements =
>         uses_list.iter().map(|use_statement| use_statement.get_text(syntax_db)).join("");
>     use_statements + &output
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4206#-:-NfwcZCq0vYkju9DdPwI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4206)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
