### PR TITLE
Improve diagnostics before '{'.

### PR DESCRIPTION
**Pull request by liorgold2**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1597)

### CODE REVIEW

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1597)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-parser/src/parser.rs` line 777 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1597#-NKlxI1g3LqPbJbeTykN:-NKlxI1g3LqPbJbeTykO:bbtef01) ([raw file](https://github.com/starkware-libs/cairo/blob/17366769f56a8522dd7beb6b1bca62cddfe07f57/crates/cairo-parser/src/parser.rs#L777)):*
> ```XML
>         let skipped_tokens = self.skip_until(is_of_kind!(lbrace, top_level, block));
> 
>         if let Some(span) = skipped_tokens {
> ```

I'm worried someone will call skip_until without having a diagnostic.
Consider making skip_until report by itself.
Or perhaps return a Result so rust will tell you you need to handle it?

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1597)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1597)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-parser/src/parser.rs` line 777 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1597#-NKlxI1g3LqPbJbeTykN:-NKm7BKVBBBPAnv1bfPN:by95173) ([raw file](https://github.com/starkware-libs/cairo/blob/31d1539b3245f428a7c4dea389e2e24ff15cd42e/crates/cairo-parser/src/parser.rs#L777)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I'm worried someone will call skip_until without having a diagnostic.
Consider making skip_until report by itself.
Or perhaps return a Result so rust will tell you you need to handle it?
</blockquote></details>

The previous version of my code reported the error inside, but this is more limiting since I want to be able to control the diagnostic according to whether `lbrace` succeeded or not.
Changed to `Result`.

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1597)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1597#-:-NKr7VsF-SvhVRHPN9bQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
