### PR TITLE
Updated `UnorderedHashMap::merge`.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #5303
- #5292
- #5291 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5291)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5291)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-utils/src/unordered_hash_map.rs` line 289 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5291#-NtUy8WUCz8I2yG7K2d0:-NtUy8WUCz8I2yG7K2d1:b3inshx) ([raw file](https://github.com/starkware-libs/cairo/blob/cc45eb832365cf4554eb0acb95d364b331a35af3/crates/cairo-lang-utils/src/unordered_hash_map.rs#L289)):*
> ```XML
>     where
>         BH: Clone,
>         HandleDuplicate: Fn(&mut Value, &Value, &Key),
> ```

IMO key should be first
___
*[`crates/cairo-lang-utils/src/unordered_hash_map.rs` line 296 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5291#-NtUzGmD9KlwlR6fmR38:-NtUzGmD9KlwlR6fmR39:b-dj8r51) ([raw file](https://github.com/starkware-libs/cairo/blob/cc45eb832365cf4554eb0acb95d364b331a35af3/crates/cairo-lang-utils/src/unordered_hash_map.rs#L296)):*
> ```XML
>             match self.0.entry(key.clone()) {
>                 Entry::Occupied(mut e) => {
>                     handle_duplicate(e.get_mut(), value, key);
> ```

why not let handle_duplicate only select the value? Then you edit here instead of making this the responsibility of the caller.
(and then first param of Handle_duplicate should not be mut)

Only thing I can think of is that you may need to clone the value even if you want to leave it as is. But if this is the problem - you can have the return type of handle_duplicate Option<Value> and return None in case you want not to change. It's a little less trivial to understand, but mostly reduces the "work" the writer of the caller needs to do (as they don't need to handle the map itself, only the values).



_Suggestion:_
```XML
                    *e.get_mut() = handle_duplicate(e.get(), value, key);
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5291)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-utils/src/unordered_hash_map.rs` line 289 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5291#-NtUy8WUCz8I2yG7K2d0:-NtV3I-v7vGe9cpC5AJy:b-ppdrxy) ([raw file](https://github.com/starkware-libs/cairo/blob/cc45eb832365cf4554eb0acb95d364b331a35af3/crates/cairo-lang-utils/src/unordered_hash_map.rs#L289)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

IMO key should be first
</blockquote></details>

weird with the mutability (that should still exist IMO)
___
*[`crates/cairo-lang-utils/src/unordered_hash_map.rs` line 296 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5291#-NtUzGmD9KlwlR6fmR38:-NtV37oM-5KF93bpUve3:b-ri20as) ([raw file](https://github.com/starkware-libs/cairo/blob/cc45eb832365cf4554eb0acb95d364b331a35af3/crates/cairo-lang-utils/src/unordered_hash_map.rs#L296)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

why not let handle_duplicate only select the value? Then you edit here instead of making this the responsibility of the caller.
(and then first param of Handle_duplicate should not be mut)

Only thing I can think of is that you may need to clone the value even if you want to leave it as is. But if this is the problem - you can have the return type of handle_duplicate Option<Value> and return None in case you want not to change. It's a little less trivial to understand, but mostly reduces the "work" the writer of the caller needs to do (as they don't need to handle the map itself, only the values).
</blockquote></details>

this requires a clone that wasn't required - when we are doing an inplace edit.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5291)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-utils/src/unordered_hash_map.rs` line 286 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5291#-NtV74DA0GgkCKVK6aEs:-NtV74DA0GgkCKVK6aEt:b-w2o2qi) ([raw file](https://github.com/starkware-libs/cairo/blob/cc45eb832365cf4554eb0acb95d364b331a35af3/crates/cairo-lang-utils/src/unordered_hash_map.rs#L286)):*
> ```XML
>     /// Merges the map with another map. If a key is present in both maps, the given handler
>     /// function is used to combine the values.
>     pub fn merge<HandleDuplicate>(&mut self, other: &Self, handle_duplicate: HandleDuplicate)
> ```

please add test/s
___
*[`crates/cairo-lang-utils/src/unordered_hash_map.rs` line 289 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5291#-NtUy8WUCz8I2yG7K2d0:-NtV7KzI9Vv9BksKsj5j:bxo7fyt) ([raw file](https://github.com/starkware-libs/cairo/blob/cc45eb832365cf4554eb0acb95d364b331a35af3/crates/cairo-lang-utils/src/unordered_hash_map.rs#L289)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

but reordering the mut to be last instead.
</blockquote></details>

Isn't that also weird? That the value of self is after the value of other? May be confusing to the user
___
*[`crates/cairo-lang-utils/src/unordered_hash_map.rs` line 296 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5291#-NtUzGmD9KlwlR6fmR38:-NtV4p7UEvXm8ljmn_7k:buxbo2b) ([raw file](https://github.com/starkware-libs/cairo/blob/cc45eb832365cf4554eb0acb95d364b331a35af3/crates/cairo-lang-utils/src/unordered_hash_map.rs#L296)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this requires a clone that wasn't required - when we are doing an inplace edit.
</blockquote></details>

When we are actively editing (that is, setting a new value for the entry), the clone is needed anyway, unless you move from `other`, in which case it should be &mut or consumed.
If you want to leave the value as is it requires the extra clone, but I suggested a solution (that you may or may not like) in the first comment.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5291)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-utils/src/unordered_hash_map.rs` line 296 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5291#-NtUzGmD9KlwlR6fmR38:-NtV9fYv1CrgDByxmU3o:b-8g7eyo) ([raw file](https://github.com/starkware-libs/cairo/blob/cc45eb832365cf4554eb0acb95d364b331a35af3/crates/cairo-lang-utils/src/unordered_hash_map.rs#L296)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

When we are actively editing (that is, setting a new value for the entry), the clone is needed anyway, unless you move from `other`, in which case it should be &mut or consumed.
If you want to leave the value as is it requires the extra clone, but I suggested a solution (that you may or may not like) in the first comment.
</blockquote></details>

a clone is not required if you are doing any type of partial edit - and it would be required here for that as well.

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5291)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-utils/src/unordered_hash_map.rs` line 296 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5291#-NtUzGmD9KlwlR6fmR38:-NtVC6Q73HQXkk0ZcvkZ:bhipfnc) ([raw file](https://github.com/starkware-libs/cairo/blob/cc45eb832365cf4554eb0acb95d364b331a35af3/crates/cairo-lang-utils/src/unordered_hash_map.rs#L296)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

a clone is not required if you are doing any type of partial edit - and it would be required here for that as well.
</blockquote></details>

Yeah, you are right about partial edits to the existing value.
Not sure it's needed for this PR, but maybe an additional version of merge with other moved (other: Self) would be nice for whoever wants to avoid clones and doesn't need other after this use.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5291)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-utils/src/unordered_hash_map.rs` line 286 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5291#-NtV74DA0GgkCKVK6aEs:-NtVHjvt6N4ey4AjOrgm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cc45eb832365cf4554eb0acb95d364b331a35af3/crates/cairo-lang-utils/src/unordered_hash_map.rs#L286)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

please add test/s
</blockquote></details>

Done.
___
*[`crates/cairo-lang-utils/src/unordered_hash_map.rs` line 289 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5291#-NtUy8WUCz8I2yG7K2d0:-NtV9rOq9CMVWyr5SKqY:b3dn8le) ([raw file](https://github.com/starkware-libs/cairo/blob/cc45eb832365cf4554eb0acb95d364b331a35af3/crates/cairo-lang-utils/src/unordered_hash_map.rs#L289)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Isn't that also weird? That the value of self is after the value of other? May be confusing to the user
</blockquote></details>

used the builtin OccupiedEntry instead.
___
*[`crates/cairo-lang-utils/src/unordered_hash_map.rs` line 296 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5291#-NtUzGmD9KlwlR6fmR38:-NtVHwoMCT74QxOCtHxM:b3dn8le) ([raw file](https://github.com/starkware-libs/cairo/blob/cc45eb832365cf4554eb0acb95d364b331a35af3/crates/cairo-lang-utils/src/unordered_hash_map.rs#L296)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Yeah, you are right about partial edits to the existing value.
Not sure it's needed for this PR, but maybe an additional version of merge with other moved (other: Self) would be nice for whoever wants to avoid clones and doesn't need other after this use.
</blockquote></details>

used the builtin OccupiedEntry instead.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5291)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-utils/src/unordered_hash_map.rs` line 296 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5291#-NtUzGmD9KlwlR6fmR38:-NtVizT69O0oD70DrUuF:b-huv82w) ([raw file](https://github.com/starkware-libs/cairo/blob/cc45eb832365cf4554eb0acb95d364b331a35af3/crates/cairo-lang-utils/src/unordered_hash_map.rs#L296)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

used the builtin OccupiedEntry instead.
</blockquote></details>

Nice! (but it's unrelated to offering a version that consumes `other`).
___
*[`crates/cairo-lang-utils/src/unordered_hash_map.rs` line 292 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5291#-NtVjUJP1LNcSqibgkL-:-NtVjUJQ-QOO_eb1lVJg:b98i1oq) ([raw file](https://github.com/starkware-libs/cairo/blob/39dcfa2d694394b204b9bde5675deeb84852b429/crates/cairo-lang-utils/src/unordered_hash_map.rs#L292)):*
> ```XML
>     where
>         BH: Clone,
>         HandleDuplicate: Fn(OccupiedEntry<'_, Key, Value>, &Value),
> ```

shouldn't the occupied entry be &mut now?



_Suggestion:_
```XML
te: Fn(&mut OccupiedEntry<'_, Key, Value>, &Value)
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5291)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-utils/src/unordered_hash_map.rs` line 296 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5291#-NtUzGmD9KlwlR6fmR38:-NtVl23r7WnaXVIUeBfx:blf9cgi) ([raw file](https://github.com/starkware-libs/cairo/blob/cc45eb832365cf4554eb0acb95d364b331a35af3/crates/cairo-lang-utils/src/unordered_hash_map.rs#L296)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Nice! (but it's unrelated to offering a version that consumes `other`).
</blockquote></details>

rather not add it without it being used in any case.
___
*[`crates/cairo-lang-utils/src/unordered_hash_map.rs` line 292 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5291#-NtVjUJP1LNcSqibgkL-:-NtVlB0f-VIGfiJaSluc:b-4dg7di) ([raw file](https://github.com/starkware-libs/cairo/blob/39dcfa2d694394b204b9bde5675deeb84852b429/crates/cairo-lang-utils/src/unordered_hash_map.rs#L292)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

shouldn't the occupied entry be &mut now?
</blockquote></details>

this adds an additional deref - this holds the lifetime of the entry as is.

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5291)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-utils/src/unordered_hash_map.rs` line 289 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5291#-NtVx2qY-24qC7A7r3Yd:-NtVx2qY-24qC7A7r3Ye:by03f5r) ([raw file](https://github.com/starkware-libs/cairo/blob/2945c49d39ea816193b77895d5583f98e58f512e/crates/cairo-lang-utils/src/unordered_hash_map.rs#L289)):*
> ```XML
>     /// Merges the map with another map. If a key is present in both maps, the given handler
>     /// function is used to combine the values.
>     pub fn merge<HandleDuplicate>(&mut self, other: &Self, handle_duplicate: HandleDuplicate)
> ```

FYI usually if you pass a callback into collection method, they tend to have `_with` suffix, i.e. `merge_with`

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5291#-:-NtW5PmPBGhYisQpwvgG:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
