### PR TITLE
Add support in lowering for inlining functions with an early return.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
The implementation relies on FlatBlockEnd:Goto and it is not implemented in sierra gen yet.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1969)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1969)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1969#-NN0lPso4It8H7pXa2n5:-NN0lPso4It8H7pXa2n6:b-yrwsy4) ([raw file](https://github.com/starkware-libs/cairo/blob/35ebd4d2285cd2877012cd20027273e547938562/crates/cairo-lang-lowering/src/inline/mod.rs#L104)):*
> ```XML
> 
>                 info.has_early_return = true;
>                 return Ok(info);
> ```

Unfourently this doesn't work.

Sierra gen tries to compile that code even though I have diagnostics :(



_Code quote:_
```XML
return Ok(info);
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1969)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1969#-NN0lPso4It8H7pXa2n5:-NN0sufwALm8hpYVAtKU:b2hedtg) ([raw file](https://github.com/starkware-libs/cairo/blob/35ebd4d2285cd2877012cd20027273e547938562/crates/cairo-lang-lowering/src/inline/mod.rs#L104)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Unfourently this doesn't work.

Sierra gen tries to compile that code even though I have diagnostics :(
</blockquote></details>

It is a bit annoying that the following is the only sierra_gen check.
https://github.com/starkware-libs/cairo/blob/27af19f21fe51dd05fdc668a65b680236c1bce4e/crates/cairo-lang-sierra-generator/src/function_generator.rs#L53

do we want to consider putting an error in the root if there are inlining issues?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1969)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1969#-NN0lPso4It8H7pXa2n5:-NN1RBtNBTm_DiXlTBwV:b-sleilv) ([raw file](https://github.com/starkware-libs/cairo/blob/35ebd4d2285cd2877012cd20027273e547938562/crates/cairo-lang-lowering/src/inline/mod.rs#L104)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

It is a bit annoying that the following is the only sierra_gen check.
https://github.com/starkware-libs/cairo/blob/27af19f21fe51dd05fdc668a65b680236c1bce4e/crates/cairo-lang-sierra-generator/src/function_generator.rs#L53

do we want to consider putting an error in the root if there are inlining issues?
</blockquote></details>

We can do the following:
https://reviewable.io/reviews/starkware-libs/cairo/1975

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1969)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1969#-NN0lPso4It8H7pXa2n5:-NN1YjRb5sBxqJylWrmw:bb7ohn6) ([raw file](https://github.com/starkware-libs/cairo/blob/35ebd4d2285cd2877012cd20027273e547938562/crates/cairo-lang-lowering/src/inline/mod.rs#L104)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

We can do the following:
https://reviewable.io/reviews/starkware-libs/cairo/1975
</blockquote></details>

sgtm
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 253 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1969#-NN0l3cW7TH3ZFeVqbXV:-NN0l3cW7TH3ZFeVqbXW:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/176c2293f722387d7911cb18dfd8d9b8ea273960/crates/cairo-lang-lowering/src/inline/mod.rs#L253)):*
> ```XML
>     }
> 
>     pub fn update_remapping(&mut self, remapping: &VarRemapping) -> VarRemapping {
> ```

doc



_Code quote:_
```XML
    pub fn update_remapping(&mut self, remapping: &VarRemapping) -> VarRemapping {
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 10 files at r1, 7 of 9 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1969)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1969)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 198 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1969#-NN5fF1j2R2j0Ij8dP7x:-NN5fF1j2R2j0Ij8dP7y:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f957150523f33f86537864e9543f4f8e871555e7/crates/cairo-lang-lowering/src/inline/mod.rs#L198)):*
> ```XML
>     }
> 
>     // Consumes all the statement in the stack.
> ```





_Suggestion:_
```XML
statements
```
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 200 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1969#-NN5fIfz-sonRYRsSu2W:-NN5fIg-CjKqqOyUzA9t:bbnkueh) ([raw file](https://github.com/starkware-libs/cairo/blob/f957150523f33f86537864e9543f4f8e871555e7/crates/cairo-lang-lowering/src/inline/mod.rs#L200)):*
> ```XML
>     // Consumes all the statement in the stack.
>     fn consume(&mut self) -> Vec<Statement> {
>         let res = self.stack.iter().cloned().rev().collect_vec();
> ```

It's wierd to clone and then clear. Try drain.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1969)* status: all files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 372 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1969#-NN5fzMuDz4XYg0hPlsJ:-NN5fzMuDz4XYg0hPlsK:b2ni2nk) ([raw file](https://github.com/starkware-libs/cairo/blob/f957150523f33f86537864e9543f4f8e871555e7/crates/cairo-lang-lowering/src/inline/mod.rs#L372)):*
> ```XML
>                         // current block after the call instruction.
> 
>                         // Create a new block with all the instructions that instructions following
> ```

fix

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1969)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 253 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1969#-NN0l3cW7TH3ZFeVqbXV:-NN6A_-DCmirK9YEoTeD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/176c2293f722387d7911cb18dfd8d9b8ea273960/crates/cairo-lang-lowering/src/inline/mod.rs#L253)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.



_Code quote:_
```XML
 fn update_remapping(&mut self, remapping: &VarRe
```
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 198 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1969#-NN5fF1j2R2j0Ij8dP7x:-NN6AP0c-gvfQwbRH3kl:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f957150523f33f86537864e9543f4f8e871555e7/crates/cairo-lang-lowering/src/inline/mod.rs#L198)):*
> ```XML
>     }
> 
>     // Consumes all the statement in the stack.
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 200 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1969#-NN5fIfz-sonRYRsSu2W:-NN6APSH8Ou_pwjCxE7E:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/f957150523f33f86537864e9543f4f8e871555e7/crates/cairo-lang-lowering/src/inline/mod.rs#L200)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

It's wierd to clone and then clear. Try drain.
</blockquote></details>

done.
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 372 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1969#-NN5fzMuDz4XYg0hPlsJ:-NN6Ahyb9LO91nnqSYWc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f957150523f33f86537864e9543f4f8e871555e7/crates/cairo-lang-lowering/src/inline/mod.rs#L372)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

fix
</blockquote></details>

Done.



_Code quote:_
```XML
   // Create a new block with all the ins
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1969)* status: 7 of 10 files reviewed, 4 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/test_data/inline` line 319 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1969#-NN6RU938rHXboQM8xeo:-NN6RU938rHXboQM8xep:b-g64627) ([raw file](https://github.com/starkware-libs/cairo/blob/4ddf1c211acb31fdb512e438ecc5d1ef2a39936b/crates/cairo-lang-lowering/src/inline/test_data/inline#L319)):*
> ```
> 
> //! > after
> blk0 (root):
> ```

The root was removed because this code is currently invalid (not supported by sierra_get)



_Code quote:_
```
 (root)
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1969)* status: all files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 380 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1969#-NN6SqA7BDe1NnXJqCw8:-NN6SqA7BDe1NnXJqCw9:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d0073db9c5a7459d5a8ac61887e0c3747f74da57/crates/cairo-lang-lowering/src/inline/mod.rs#L380)):*
> ```XML
>                         // current block after the call instruction.
> 
>                         // Create a new block with all the instructions that follow
> ```





_Suggestion:_
```XML
                        // Create a new block with all the instructions that follow the call instruction.
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1969)* status: 9 of 10 files reviewed, 4 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 380 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1969#-NN6SqA7BDe1NnXJqCw8:-NN6XGNkC2wcXFvMTSw4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d0073db9c5a7459d5a8ac61887e0c3747f74da57/crates/cairo-lang-lowering/src/inline/mod.rs#L380)):*
> ```XML
>                         // current block after the call instruction.
> 
>                         // Create a new block with all the instructions that follow
> ```

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1969)* status: all files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/inline/test_data/inline` line 347 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1969#-NN7A2qR973I--Eo2ccd:-NN7A2qR973I--Eo2cce:b-cb136) ([raw file](https://github.com/starkware-libs/cairo/blob/d322d9ebb9d95e101c9a685710cd9bd0ca8bcb04/crates/cairo-lang-lowering/src/inline/test_data/inline#L347)):*
> ```
> Statements:
> End:
>   Callsite({})
> ```

I think that it is ok to have a Callsite, even though there is a goto.

It will return to the callsite of the fallthrough case.



_Code quote:_
```
Callsite({})
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1969)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/test_data/inline` line 347 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1969#-NN7A2qR973I--Eo2ccd:-NN7DMGxEsEOnauRiUBn:b-ei4eoi) ([raw file](https://github.com/starkware-libs/cairo/blob/d322d9ebb9d95e101c9a685710cd9bd0ca8bcb04/crates/cairo-lang-lowering/src/inline/test_data/inline#L347)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I think that it is ok to have a Callsite, even though there is a goto.

It will return to the callsite of the fallthrough case.
</blockquote></details>

This is the sierra code:

label0:
felt_const<2>() -> ([1])
dup<felt>([0]) -> ([0], [3])
felt_sub([3], [1]) -> ([2])
store_temp<felt>([2]) -> ([2])
felt_is_zero([2]) { fallthrough() label1([4]) }
branch_align() -> ()
felt_is_zero([0]) { fallthrough() label3([5]) }
branch_align() -> ()
felt_const<1>() -> ([6])
store_temp<felt>([6]) -> ([7])
jump() { label5() }
label3:
branch_align() -> ()
drop<NonZero<felt>>([5]) -> ()
drop<felt>([7]) -> ()
label4:
felt_const<0>() -> ([7])
label5:
store_temp<felt>([7]) -> ([8])
jump() { label2() }
label1:
branch_align() -> ()
drop<NonZero<felt>>([4]) -> ()
drop<felt>([7]) -> ()
store_temp<felt>([0]) -> ([8])
label2:
rename<felt>([8]) -> ([9])
return([9])



_Code quote:_
```
 Callsite({v3 -> v5})
```

**Review by orizi — APPROVED** [review]
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1969)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 4 of 9 files at r2, 1 of 3 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1969)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
