### PR TITLE
Allow moving of felt ops.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4539)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 16 files at r1, 26 of 30 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4539)* status: 27 of 31 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 286 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4539#-NlbY2ULAttxhl9G1_fy:-NlbY2ULAttxhl9G1_fz:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/41bfaa9342bf773dedd4a9fcc5d6fe7223a6d1a3/crates/cairo-lang-lowering/src/db.rs#L286)):*
> ```XML
> pub fn init_lowering_group(db: &mut (dyn LoweringGroup + 'static)) {
>     let mut moveable_functions: Vec<String> = ["bool_not_impl", "felt252_add", "felt252_sub"]
>         .into_iter()
> ```





_Suggestion:_
```XML
    let mut moveable_functions: Vec<String> = ["bool_not_impl", "felt252_add", "felt252_sub", "felt252_mul", "felt252_div"]
        .into_iter()
```
___
*[`crates/cairo-lang-lowering/src/db.rs` line 300 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4539#-NlbYIaZ7WzdC-PwwMCD:-NlbYIaZ7WzdC-PwwMCE:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/41bfaa9342bf773dedd4a9fcc5d6fe7223a6d1a3/crates/cairo-lang-lowering/src/db.rs#L300)):*
> ```XML
>     for ty in ["u8", "u16", "u32", "u64", "u128"] {
>         moveable_functions.extend(ops_from_type(ty));
>     }
> ```





_Suggestion:_
```XML
    let ops_from_unsigned_type = |ty: &str| {
        [
            format!("integer::{}_overflowing_add", ty),
            format!("integer::{}_overflowing_sub", ty),
            format!("integer::{}_safe_divmod", ty),
        ]
    };

    for ty in ["u8", "u16", "u32", "u64", "u128"] {
        moveable_functions.extend(ops_from_unsigned_type(ty));
    }
    let ops_from_signed_type = |ty: &str| {
        [
            format!("integer::{}_overflowing_add_impl", ty),
            format!("integer::{}_overflowing_sub_impl", ty),
            format!("integer::{}_diff", ty),
        ]
    };

    for ty in ["i8", "i16", "i32", "i64", "i128"] {
        moveable_functions.extend(ops_from_signed_type(ty));
    }
    
    for ty in ["i8", "i16", "i32", "i64", "u8", "u16", "u32", "u64", "u128"] {
        format!("integer::{}_wide_mul", ty),
    }
```
___
*[`crates/cairo-lang-lowering/src/optimizations/config.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4539#-NlbS_au8uMGwKVKTIM4:-NlbS_au8uMGwKVKTIM5:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/41bfaa9342bf773dedd4a9fcc5d6fe7223a6d1a3/crates/cairo-lang-lowering/src/optimizations/config.rs#L37)):*
> ```XML
>                 corelib::get_function_id(semantic_db, module, path_item.into(), vec![]),
>             ));
>         }
> ```





_Suggestion:_
```XML
                    .unwrap_or_else(|| panic!("module not found: {}", path_item));
                continue;
            }

            return db.intern_lowering_function(FunctionLongId::Semantic(
                corelib::get_function_id(semantic_db, module, path_item.into(), vec![]),
            ));
        }
```
___
*[`tests/e2e_test_data/metadata_computation` line 750 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4539#-NlbVum43ztThntUQ_8_:-NlbVum43ztThntUQ_8a:b-wtsvfq) ([raw file](https://github.com/starkware-libs/cairo/blob/41bfaa9342bf773dedd4a9fcc5d6fe7223a6d1a3/tests/e2e_test_data/metadata_computation#L750)):*
> ```
>         1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1;
>         1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1;
>         1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1;
> ```

this needs to remain as heavy - the optimization breaks the test.



_Code quote:_
```
        1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1;
        1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1;
        1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1;
        1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1;
        1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1;
        1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1;
        1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1;
        1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1;
        1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1;
```
___
*[`tests/e2e_test_data/libfuncs/felt252` line 47 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4539#-NlbXRmZ5FFpMSZal7Hf:-NlbXRmZ5FFpMSZal7Hg:b-2sv3gz) ([raw file](https://github.com/starkware-libs/cairo/blob/289fa618c298529929ea67dc7bb4daa07f7686ed/tests/e2e_test_data/libfuncs/felt252#L47)):*
> ```
> //! > cairo
> fn foo(a: felt252, b: felt252) -> felt252 {
>     let _x = felt252_add(a, b);
> ```

this is supposed to check that only the "store" action actually performs the add.



_Code quote:_
```
    let _x = felt252_add(a, b);
```

**Comment by ilyalesokhin-starkware** [comment]
*[`tests/e2e_test_data/libfuncs/felt252` line 47 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4539#-NlbXRmZ5FFpMSZal7Hf:-Nlc330d9qIiQOEmtWls:b-j2pa35) ([raw file](https://github.com/starkware-libs/cairo/blob/289fa618c298529929ea67dc7bb4daa07f7686ed/tests/e2e_test_data/libfuncs/felt252#L47)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is supposed to check that only the "store" action actually performs the add.
</blockquote></details>

do you want to disable optimizations in `SmallE2ETestRunner`?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4539)* status: 27 of 31 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`tests/e2e_test_data/libfuncs/felt252` line 47 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4539#-NlbXRmZ5FFpMSZal7Hf:-Nlc5HfG0zL2Ky7Lj1w5:b-7dsp5y) ([raw file](https://github.com/starkware-libs/cairo/blob/289fa618c298529929ea67dc7bb4daa07f7686ed/tests/e2e_test_data/libfuncs/felt252#L47)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

do you want to disable optimizations in `SmallE2ETestRunner`?
</blockquote></details>

this is probably a good solution here - as we assume almost direct Cairo to sierra mapping.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4539)* status: 26 of 35 files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 286 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4539#-NlbY2ULAttxhl9G1_fy:-Nlc3I3F2tDlPnUPBg5s:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/41bfaa9342bf773dedd4a9fcc5d6fe7223a6d1a3/crates/cairo-lang-lowering/src/db.rs#L286)):*
> ```XML
> pub fn init_lowering_group(db: &mut (dyn LoweringGroup + 'static)) {
>     let mut moveable_functions: Vec<String> = ["bool_not_impl", "felt252_add", "felt252_sub"]
>         .into_iter()
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/db.rs` line 300 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4539#-NlbYIaZ7WzdC-PwwMCD:-Nlc3KLg3zyrfqmeak78:b-efac0z) ([raw file](https://github.com/starkware-libs/cairo/blob/41bfaa9342bf773dedd4a9fcc5d6fe7223a6d1a3/crates/cairo-lang-lowering/src/db.rs#L300)):*
> ```XML
>     for ty in ["u8", "u16", "u32", "u64", "u128"] {
>         moveable_functions.extend(ops_from_type(ty));
>     }
> ```

removed, I've realized that most of those are extern matches and not libfunc calls.
___
*[`crates/cairo-lang-lowering/src/optimizations/config.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4539#-NlbS_au8uMGwKVKTIM4:-Nlc4QdaEXE3HblF7Z59:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/41bfaa9342bf773dedd4a9fcc5d6fe7223a6d1a3/crates/cairo-lang-lowering/src/optimizations/config.rs#L37)):*
> ```XML
>                 corelib::get_function_id(semantic_db, module, path_item.into(), vec![]),
>             ));
>         }
> ```

Done.
___
*[`tests/e2e_test_data/metadata_computation` line 750 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4539#-NlbVum43ztThntUQ_8_:-NlcPbdi7oHMTwTjZVje:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/41bfaa9342bf773dedd4a9fcc5d6fe7223a6d1a3/tests/e2e_test_data/metadata_computation#L750)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this needs to remain as heavy - the optimization breaks the test.
</blockquote></details>

Done.
___
*[`tests/e2e_test_data/libfuncs/felt252` line 47 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4539#-NlbXRmZ5FFpMSZal7Hf:-NlcPaOK5fR5debBj4BB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/289fa618c298529929ea67dc7bb4daa07f7686ed/tests/e2e_test_data/libfuncs/felt252#L47)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is probably a good solution here - as we assume almost direct Cairo to sierra mapping.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4539)* status: 31 of 35 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/config.rs` line 18 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4539#-NlcQInT9zghRbyMpwGD:-NlcQInT9zghRbyMpwGE:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/5454253761052844b72216b72e08a5fd131d8290/crates/cairo-lang-lowering/src/optimizations/config.rs#L18)):*
> ```XML
> 
> impl OptimizationConfig {
>     // Testing configuration that makes it easier to write test.
> ```





_Suggestion:_
```XML
    /// Testing configuration that makes it easier to write test.
```
___
*[`crates/cairo-lang-lowering/src/optimizations/config.rs` line 19 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4539#-NlcQTvW9etYINNFuoHU:-NlcQTvW9etYINNFuoHV:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/5454253761052844b72216b72e08a5fd131d8290/crates/cairo-lang-lowering/src/optimizations/config.rs#L19)):*
> ```XML
> impl OptimizationConfig {
>     // Testing configuration that makes it easier to write test.
>     pub fn testing() -> Self {
> ```

?



_Suggestion:_
```XML
    pub fn no_movable_functions() -> Self {
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/config.rs` line 19 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4539#-NlcQTvW9etYINNFuoHU:-NlcTFw10rUEpc-sI93E:bzwcu8) ([raw file](https://github.com/starkware-libs/cairo/blob/5454253761052844b72216b72e08a5fd131d8290/crates/cairo-lang-lowering/src/optimizations/config.rs#L19)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

it is harder to document and I feel that this change will be reverted in the future.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4539)* status: 33 of 35 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/config.rs` line 19 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4539#-NlcQTvW9etYINNFuoHU:-NlcaSidC6zGc22vXg33:boj4ex1) ([raw file](https://github.com/starkware-libs/cairo/blob/5454253761052844b72216b72e08a5fd131d8290/crates/cairo-lang-lowering/src/optimizations/config.rs#L19)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it is harder to document and I feel that this change will be reverted in the future.
</blockquote></details>

it is easier to document - different tests are very likely to require different things.
`testing` is weird to me as i don't know why is it different at all - or why not all tests use it.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4539)* status: 32 of 35 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/config.rs` line 18 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4539#-NlcQInT9zghRbyMpwGD:-NlcdKSCBFggiLbX3S-7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5454253761052844b72216b72e08a5fd131d8290/crates/cairo-lang-lowering/src/optimizations/config.rs#L18)):*
> ```XML
> 
> impl OptimizationConfig {
>     // Testing configuration that makes it easier to write test.
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/optimizations/config.rs` line 19 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4539#-NlcQTvW9etYINNFuoHU:-NlcdKjz8-nJeoW2bxah:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5454253761052844b72216b72e08a5fd131d8290/crates/cairo-lang-lowering/src/optimizations/config.rs#L19)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it is easier to document - different tests are very likely to require different things.
`testing` is weird to me as i don't know why is it different at all - or why not all tests use it.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 8 files at r4, 1 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4539#-:-Nlce9pi3eDT_o9R8Ton:bnfp4nl)* status: 33 of 35 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4539)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Pull request merged**
