### PR TITLE
Inferred literal types

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2725)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2725** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2725" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2725?utm_source=stack-comment).

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 28 of 28 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2725)* status: all files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1247 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2725#-NSKADIOB0N6o5FGIIml:-NSKADIOB0N6o5FGIImm:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/d04448ec39d7c5ed4a55f92f5cc6cba6b88df4ad/crates/cairo-lang-semantic/src/expr/compute.rs#L1247)):*
> ```XML
> }
> 
> fn new_literal_expr(
> ```

doc



_Code quote:_
```XML
new_literal_expr(
```
___
*[`crates/cairo-lang-semantic/src/expr/test_data/inference` line 160 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2725#-NSKAO6W8WVRGVcHXlzv:-NSKAO6W8WVRGVcHXlzw:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d04448ec39d7c5ed4a55f92f5cc6cba6b88df4ad/crates/cairo-lang-semantic/src/expr/test_data/inference#L160)):*
> ```
> 
> //! > expected_diagnostics
> error: Trait has no implementation in context: core::integer::NumericLiteral::<core::never>
> ```





_Suggestion:_
```
//! > function
fn foo() -> never {
    5_felt252
}

//! > function_name
foo

//! > module_code

//! > expected_diagnostics
error: Trait has no implementation in context: core::integer::NumericLiteral::<core::never>
 --> lib.cairo:2:5
    5
```
___
*[`crates/cairo-lang-semantic/src/expr/test_data/literal` line 102 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2725#-NSKAXRT6tcGvo97bOhR:-NSKAXRT6tcGvo97bOhS:b-3se30x) ([raw file](https://github.com/starkware-libs/cairo/blob/8002fba2917146f242472d9147c564d1b6930ba2/crates/cairo-lang-semantic/src/expr/test_data/literal#L102)):*
> ```
>             ^*******^
> 
> error: The value does not fit within the range of type core::integer::u32.
> ```

why have these disapeared?



_Code quote:_
```
error: The value does not fit within the range of type core::integer::u16.
 --> lib.cairo:3:13
    let a = 65536_u16;
            ^*******^

error: The value does not fit within the range of type core::integer::u32.
 --> lib.cairo:4:13
    let a = 4294967296_u32;
            ^************^

error: The value does not fit within the range of type core::integer::u64.
 --> lib.cairo:5:13
    let b = 18446744073709551616_u64;
            ^**********************^

error: The value does not fit within the range of type core::integer::u128.
 --> lib.cairo:6:13
    let c = 340282366920938463463374607431768211456_u128;
            ^******************************************^

error: The value does not fit within the range of type core::felt252.
 --> lib.cairo:7:13
    let d = 0x800000000000011000000000000000000000000000000000000000000000001;
            ^***************************************************************^
```
___
*[`crates/cairo-lang-semantic/src/expr/test_data/literal` line 157 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2725#-NSKAaF-BjnNFOeH_mbc:-NSKAaF-BjnNFOeH_mbd:b-tchtvq) ([raw file](https://github.com/starkware-libs/cairo/blob/8002fba2917146f242472d9147c564d1b6930ba2/crates/cairo-lang-semantic/src/expr/test_data/literal#L157)):*
> ```
> error: The value does not fit within the range of type core::integer::u32.
>  --> lib.cairo:4:13
>     let b = 'abcda'_u32;
> ```

these as well



_Code quote:_
```
error: The value does not fit within the range of type core::integer::u16.
 --> lib.cairo:3:13
    let a = 'aba'_u16;
            ^*******^

error: The value does not fit within the range of type core::integer::u32.
 --> lib.cairo:4:13
    let b = 'abcda'_u32;
            ^*********^

error: The value does not fit within the range of type core::integer::u64.
 --> lib.cairo:5:13
    let b = 'abcdabcda'_u64;
            ^*************^

error: The value does not fit within the range of type core::integer::u128.
 --> lib.cairo:6:13
    let c = 'abcdabcdabcdabcda'_u128;
            ^**********************^

error: The value does not fit within the range of type core::felt252.
 --> lib.cairo:7:13
    let d = 'abcdabcdabcdabcdabcdabcdabcdabcd';
            ^********************************^
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2725)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1247 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2725#-NSKADIOB0N6o5FGIIml:-NSZTuZvDjqC-Ah-VbX6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d04448ec39d7c5ed4a55f92f5cc6cba6b88df4ad/crates/cairo-lang-semantic/src/expr/compute.rs#L1247)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/inference` line 160 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2725#-NSKAO6W8WVRGVcHXlzv:-NSZUDfuEHE47KS-3lMq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d04448ec39d7c5ed4a55f92f5cc6cba6b88df4ad/crates/cairo-lang-semantic/src/expr/test_data/inference#L160)):*
> ```
> 
> //! > expected_diagnostics
> error: Trait has no implementation in context: core::integer::NumericLiteral::<core::never>
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/literal` line 102 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2725#-NSKAXRT6tcGvo97bOhR:-NSZTmT09H2PiY8XDS-d:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8002fba2917146f242472d9147c564d1b6930ba2/crates/cairo-lang-semantic/src/expr/test_data/literal#L102)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why have these disapeared?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/literal` line 157 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2725#-NSKAaF-BjnNFOeH_mbc:-NSZTmwj6aR3ADgJ7l4D:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8002fba2917146f242472d9147c564d1b6930ba2/crates/cairo-lang-semantic/src/expr/test_data/literal#L157)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

these as well
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2725#-:-NSZVI9x5VOYixPQqaaS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
