### PR TITLE
LS: Proc macro server failed notification

### PR DESCRIPTION
**Pull request by Draggu**
**Stack**:
- #6706
- #6705 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by piotmag769 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6705#-:-OC91nSZAm8D88S9kqzn:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @integraledelebesgue, @mkaput, and @orizi)

___
*[`vscode-cairo/src/cairols.ts` line 161 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6705#-OC92jwTE8r1DduPPMd9:-OC92jwTE8r1DduPPMdA:biig3td) ([raw file](https://github.com/starkware-libs/cairo/blob/1501481a97bdaf515821f8c8bf2323058cc9c6f2/vscode-cairo/src/cairols.ts#L161)):*
> ```XML
> 
>       await vscode.window.showErrorMessage(
>         errorMessage == "NoMoreRetries" ? noMoreRetries : spawnFail,
> ```

Should be a switch imo and "NoMoreRetries" should be coded as a const

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6705)* status: all files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, and @orizi)

___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/controller.rs` line 68 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6705#-OCI5xMZ4_mgQb9WA5HV:-OCI5xMZ4_mgQb9WA5HW:by7fgkj) ([raw file](https://github.com/starkware-libs/cairo/blob/2b821bd4b7e2bda1ac005e0fa3a06ffd8920fc67/crates/cairo-lang-language-server/src/lang/proc_macros/controller.rs#L68)):*
> ```XML
>     }
> 
>     pub fn new(notifier: Notifier, scarb: ScarbToolchain) -> Self {
> ```

nit, we used to put notifier after scarb toolchain everywhere
___
*[`vscode-cairo/src/cairols.ts` line 156 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6705#-OCI45ss9WjAfyQ3gNB0:-OCI45ss9WjAfyQ3gNB1:b-wbol0m) ([raw file](https://github.com/starkware-libs/cairo/blob/2b821bd4b7e2bda1ac005e0fa3a06ffd8920fc67/vscode-cairo/src/cairols.ts#L156)):*
> ```XML
>     async (errorMessage) => {
>       const noMoreRetries =
>         "Starting proc-macro-server failed 5 times in 3 minutes, no more action will be taken";
> ```

there numbers should come from the LS instead of being hardcoded
___
*[`vscode-cairo/src/cairols.ts` line 156 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6705#-OCI4ByP52gH0jr7a59s:-OCI4ByP52gH0jr7a59t:bf4flw3) ([raw file](https://github.com/starkware-libs/cairo/blob/2b821bd4b7e2bda1ac005e0fa3a06ffd8920fc67/vscode-cairo/src/cairols.ts#L156)):*
> ```XML
>     async (errorMessage) => {
>       const noMoreRetries =
>         "Starting proc-macro-server failed 5 times in 3 minutes, no more action will be taken";
> ```

as an user I will immediately ask: "what do you mean by 'action'?". 

https://developers.google.com/tech-writing/error-messages#this\_course\_in\_ten\_seconds
___
*[`vscode-cairo/src/cairols.ts` line 158 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6705#-OCI4HZc633AyHpHQqEo:-OCI4HZc633AyHpHQqEp:bnvdqtc) ([raw file](https://github.com/starkware-libs/cairo/blob/2b821bd4b7e2bda1ac005e0fa3a06ffd8920fc67/vscode-cairo/src/cairols.ts#L158)):*
> ```XML
>         "Starting proc-macro-server failed 5 times in 3 minutes, no more action will be taken";
>       const spawnFail =
>         "Starting proc-macro-server with `scarb proc-macro-server` failed, no more action will be taken";
> ```

this was an implementation detail



_Suggestion:_
```XML
"Starting proc-macro-server failed, no more action will be taken";
```

**Review by Draggu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6705)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @Arcticae, @integraledelebesgue, @mkaput, @orizi, and @piotmag769)

___
*[`vscode-cairo/src/cairols.ts` line 156 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6705#-OCI45ss9WjAfyQ3gNB0:-OCJCsEBBDafWZq3kExI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2b821bd4b7e2bda1ac005e0fa3a06ffd8920fc67/vscode-cairo/src/cairols.ts#L156)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

there numbers should come from the LS instead of being hardcoded
</blockquote></details>

Done.
___
*[`vscode-cairo/src/cairols.ts` line 156 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6705#-OCI4ByP52gH0jr7a59s:-OCJDdbi4iDWNcggWL-Z:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2b821bd4b7e2bda1ac005e0fa3a06ffd8920fc67/vscode-cairo/src/cairols.ts#L156)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

as an user I will immediately ask: "what do you mean by 'action'?". 

https://developers.google.com/tech-writing/error-messages#this\_course\_in\_ten\_seconds
</blockquote></details>

Done.
___
*[`vscode-cairo/src/cairols.ts` line 158 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6705#-OCI4HZc633AyHpHQqEo:-OCJDdsP5OoJoKIDqYOF:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2b821bd4b7e2bda1ac005e0fa3a06ffd8920fc67/vscode-cairo/src/cairols.ts#L158)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

this was an implementation detail
</blockquote></details>

Done.
___
*[`vscode-cairo/src/cairols.ts` line 161 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6705#-OCIuVTiCQbA96tICq2G:-OCJDgYF7xoICZ6YLxSG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2b821bd4b7e2bda1ac005e0fa3a06ffd8920fc67/vscode-cairo/src/cairols.ts#L161)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

Unrecognized error message shouldn't be displayed, you have to verify it at runtime since RPC can send whatever it wants here
</blockquote></details>

Done.

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6705)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, and @orizi)

___
*[`vscode-cairo/src/cairols.ts` line 157 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6705#-OCXxBoa-L4Up-cD5sn_:-OCXxBoa-L4Up-cD5sna:b-lbhbps) ([raw file](https://github.com/starkware-libs/cairo/blob/e93bed7cc10cadf2667f9174a89d17f750761215/vscode-cairo/src/cairols.ts#L157)):*
> ```XML
>       if (errorMessage === "spawnFail") {
>         await vscode.window.showErrorMessage(
>           "Starting proc-macro-server failed, the proc-macro-server will not be restarted. See the output for more information",
> ```

Please add information that procedular macros will not be analysed or smth like this
___
*[`crates/cairo-lang-language-server/src/lsp/ext.rs` line 68 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6705#-OCXwyc_Duog5IxGiYFe:-OCXwyc_Duog5IxGiYFf:bmioe8d) ([raw file](https://github.com/starkware-libs/cairo/blob/e93bed7cc10cadf2667f9174a89d17f750761215/crates/cairo-lang-language-server/src/lsp/ext.rs#L68)):*
> ```XML
> 
> #[derive(Debug, Serialize, Deserialize)]
> #[serde(rename_all = "camelCase", rename_all_fields = "camelCase")]
> ```

use internally tagged enum representation: https://serde.rs/enum-representations.html#internally-tagged

this will also make your TS code much, much simpler, because you'll be able to use plain old `switch` statement without `default` branch
___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/controller.rs` line 96 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6705#-OCXvs5VCTdw6S8AWcRM:-OCXvs5VCTdw6S8AWcRN:bfvaodq) ([raw file](https://github.com/starkware-libs/cairo/blob/e93bed7cc10cadf2667f9174a89d17f750761215/crates/cairo-lang-language-server/src/lang/proc_macros/controller.rs#L96)):*
> ```XML
>         if !self.try_initialize(db) {
>             self.fatal_failed(db, ProcMacroServerInitializationFailedParams::NoMoreRetries {
>                 retries: 5,
> ```

are you able to pull this from ratelimiter? or at least use constants that will be shared?

**Review by Draggu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6705)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @Arcticae, @integraledelebesgue, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/controller.rs` line 96 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6705#-OCXvs5VCTdw6S8AWcRM:-OCY6OTqC77A7YBtbdlK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e93bed7cc10cadf2667f9174a89d17f750761215/crates/cairo-lang-language-server/src/lang/proc_macros/controller.rs#L96)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

are you able to pull this from ratelimiter? or at least use constants that will be shared?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lsp/ext.rs` line 68 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6705#-OCXwyc_Duog5IxGiYFe:-OCY7IKJDYCFxq4KRnkj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e93bed7cc10cadf2667f9174a89d17f750761215/crates/cairo-lang-language-server/src/lsp/ext.rs#L68)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

use internally tagged enum representation: https://serde.rs/enum-representations.html#internally-tagged

this will also make your TS code much, much simpler, because you'll be able to use plain old `switch` statement without `default` branch
</blockquote></details>

Done.
___
*[`vscode-cairo/src/cairols.ts` line 157 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6705#-OCXxBoa-L4Up-cD5sn_:-OCY7kgd0i0d23GDd0UB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e93bed7cc10cadf2667f9174a89d17f750761215/vscode-cairo/src/cairols.ts#L157)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Please add information that procedular macros will not be analysed or smth like this
</blockquote></details>

Done.

**Review by Draggu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6705)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @integraledelebesgue, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/src/lsp/ext.rs` line 68 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6705#-OCYloln2KwNP1wgW2iv:-OCZ6x0Z1qyuqXBQbQqV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/59d177a1edf07b538c6388a8cb2b8d3bf38866d0/crates/cairo-lang-language-server/src/lsp/ext.rs#L68)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

type is often a keyword etc. wdyt?
</blockquote></details>

Done.

**Review by piotmag769 — APPROVED** [review]
> Reviewed 1 of 4 files at r3, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6705)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @mkaput, and @orizi)

___
*[`vscode-cairo/src/cairols.ts` line 160 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6705#-OCZzSmg52kfXX7YNgTp:-OCZzSmg52kfXX7YNgTq:b-b87i60) ([raw file](https://github.com/starkware-libs/cairo/blob/86aee1cf8c35b1145bd45be416e7d4ad56237007/vscode-cairo/src/cairols.ts#L160)):*
> ```XML
> 
>           await vscode.window.showErrorMessage(
>             `Starting proc-macro-server failed ${retries} times in ${inMinutes} minutes, the proc-macro-server will not be restarted. Procedural macros will not be analyzed. See the output for more information`,
> ```

[nit] we can add go to output button in both cases

**Review by Arcticae — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6705#-:-OCc7iCcEDsOY8yWnIUp:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @Draggu, @integraledelebesgue, and @orizi)

**Review by Arcticae — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6705#-:-OCc8jyt9qRdJP2TCWpp:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Draggu, @integraledelebesgue, and @orizi)

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6705)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
