### PR TITLE
Audit comments

### PR DESCRIPTION
**Pull request by liorgold2**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5647)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5647)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/array.rs` line 484 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5647#-Nyt4wq30UQuhBPBKJTE:-Nyt4wq30UQuhBPBKJTF:bxe9a1z) ([raw file](https://github.com/starkware-libs/cairo/blob/21c070ebe6ed8cc8eb1221dc6efdccfd90e4fed5/crates/cairo-lang-sierra-to-casm/src/invocations/array.rs#L484)):*
> ```XML
>         let arr_start_popped = arr_start + popped_size;
>         tempvar has_enough_elements;
>         // TODO: Why not use the regular TestLessThanOrEqual hint on `popped_size <= end - start`?
> ```

Can't, as the hint system only accepts ResOperand, so no minus support.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5647)* status: 0 of 7 files reviewed, 11 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 179 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5647#-NytPHiRCG4jomvNL-Q8:-NytPHiRCG4jomvNL-Q9:b-p1male) ([raw file](https://github.com/starkware-libs/cairo/blob/21c070ebe6ed8cc8eb1221dc6efdccfd90e4fed5/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L179)):*
> ```XML
>                 ParamSignature::new(range_check_type.clone()).with_allow_add_const(),
>                 ParamSignature::new(lhs.clone()),
>                 // Maybe rhs should be NonZero<Range<>>?
> ```

so we need a non-fallible wrap_nz function for this?



_Code quote:_
```XML
                // Maybe rhs should be NonZero<Range<>>?
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 238 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5647#-NytQrMX3YOR06TdM2eY:-NytQrMX3YOR06TdM2eZ:bxfbuwr) ([raw file](https://github.com/starkware-libs/cairo/blob/21c070ebe6ed8cc8eb1221dc6efdccfd90e4fed5/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L238)):*
> ```XML
>     ///
>     /// Assumption: `lhs` is non-negative and `rhs` is positive.
>     // TODO: rename to try_new.
> ```

done.
https://reviewable.io/reviews/starkware-libs/cairo/5651
___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 246 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5647#-NytQsNn2hOCD7TQSMHN:-NytPyKO8JXNMUyFb7Nz:bxfbuwr) ([raw file](https://github.com/starkware-libs/cairo/blob/21c070ebe6ed8cc8eb1221dc6efdccfd90e4fed5/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L246)):*
> ```XML
>         require(q_max < u128_limit)?;
>         // `r` is range checked in all algorithm variants, so `lhs.upper` must be at most `2**128`.
>         // TODO: Can lhs.upper be `2**128 + 1`?
> ```

done.
https://reviewable.io/reviews/starkware-libs/cairo/5651
___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 256 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5647#-NytQu-j6a6w_RNU7SOV:-NytQu-j6a6w_RNU7SOW:buae4r) ([raw file](https://github.com/starkware-libs/cairo/blob/21c070ebe6ed8cc8eb1221dc6efdccfd90e4fed5/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L256)):*
> ```XML
>         }
>         let root = lhs.upper.sqrt();
>         // TODO: Add explicit check that root < 2**128.
> ```

but why is it necessary?
___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 285 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5647#-NytRhsT1EAC1dxaLBsX:-NytRhsT1EAC1dxaLBsY:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/21c070ebe6ed8cc8eb1221dc6efdccfd90e4fed5/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L285)):*
> ```XML
>         }?;
>         let range = Range::from_type(context, ty.clone())?;
>         // TODO: rename ot low_range and high_range.
> ```

done
___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 286 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5647#-NytRdsCBK7g_MTyAQ4n:-NytRdsCBK7g_MTyAQ4o:b66etqh) ([raw file](https://github.com/starkware-libs/cairo/blob/21c070ebe6ed8cc8eb1221dc6efdccfd90e4fed5/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L286)):*
> ```XML
>         let range = Range::from_type(context, ty.clone())?;
>         // TODO: rename ot low_range and high_range.
>         // TODO: Check that range.lower < boundary < range.upper.
> ```

the following >= 1 checks it already - isn;t it?
___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 290 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5647#-NytRTmG9t7M_adBCRvB:-NytRTmG9t7M_adBCRvC:b-68ppni) ([raw file](https://github.com/starkware-libs/cairo/blob/21c070ebe6ed8cc8eb1221dc6efdccfd90e4fed5/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L290)):*
> ```XML
>         let over_range = Range::half_open(boundary.clone(), range.upper);
>         require(
>             // TODO: size() is always >= 1 (the check should be before Range::half_open).
> ```

this would mean we need to make all range building fallible.
(additionally means we don't need to add the previous requested check)
___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs` line 210 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5647#-NytRmCc7ZPAEnnR_grb:-NytRmCc7ZPAEnnR_grc:b-nsj367) ([raw file](https://github.com/starkware-libs/cairo/blob/21c070ebe6ed8cc8eb1221dc6efdccfd90e4fed5/crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs#L210)):*
> ```XML
>         context: &dyn SignatureSpecializationContext,
>     ) -> Result<LibfuncSignature, SpecializationError> {
>         // TODO: Why do we need the handle, if we are allowing to cast Box<...> to it?
> ```

allows the OS to vastly change the implementation, with only adding a cost at the wrapper libfuncs.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/felt252.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5647#-NytSDyzEWZuyean9Hd5:-NytSDyzEWZuyean9Hd6:b-jrwtwi) ([raw file](https://github.com/starkware-libs/cairo/blob/21c070ebe6ed8cc8eb1221dc6efdccfd90e4fed5/crates/cairo-lang-sierra-to-casm/src/invocations/felt252.rs#L48)):*
> ```XML
>     add_input_variables! {casm_builder,
>         deref a;
>         deref_or_immediate b; // TODO: Signature doesn't allow it ATM.
> ```

for bounded int only - you say we want to change it?
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5647#-NytSJyg5HUQHW-_drId:-NytSJyg5HUQHW-_drIe:b8akwcw) ([raw file](https://github.com/starkware-libs/cairo/blob/21c070ebe6ed8cc8eb1221dc6efdccfd90e4fed5/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L60)):*
> ```XML
>         BoundedIntDivRemAlgorithm::KnownSmallLhs(_) => 4,
>     };
>     // TODO: What is the argument of buffer? and what is the relation to the (3, 4, 4) range checks
> ```

the slack for the allowed change - so it would be 3 for 4 range checks.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5647)* status: 0 of 7 files reviewed, 13 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 566 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5647#-Nyzw9if2qVApQmI7F7a:-Nyzw9if2qVApQmI7F7b:bpct4i7) ([raw file](https://github.com/starkware-libs/cairo/blob/21c070ebe6ed8cc8eb1221dc6efdccfd90e4fed5/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L566)):*
> ```XML
>                     vars: vec>                         OutputVarInfo::new_builtin(range_check_ty, 0),
>                         // Note that it's duplicatable.
> ```

i think it is better for parity sake.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 256 at r1 ([raw file](https://github.com/starkware-libs/cairo/blob/21c070ebe6ed8cc8eb1221dc6efdccfd90e4fed5/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L256)):*
> ```XML
>         }
>         let root = lhs.upper.sqrt();
>         // TODO: Add explicit check that root < 2**128.
> ```

done
___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 286 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5647#-NyzsJIuCXK4UKxCklGu:-NyzsJIuCXK4UKxCklGv:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/21c070ebe6ed8cc8eb1221dc6efdccfd90e4fed5/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L286)):*
> ```XML
>         let range = Range::from_type(context, ty.clone())?;
>         // TODO: rename ot low_range and high_range.
>         // TODO: Check that range.lower < boundary < range.upper.
> ```

done
___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 290 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5647#-NyzsHntC10maq7CYLgD:-NyzsHntC10maq7CYLgE:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/21c070ebe6ed8cc8eb1221dc6efdccfd90e4fed5/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L290)):*
> ```XML
>         let over_range = Range::half_open(boundary.clone(), range.upper);
>         require(
>             // TODO: size() is always >= 1 (the check should be before Range::half_open).
> ```

done
___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs` line 210 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5647#-NyzuA6w1RmBevDBwlR4:-NyzuA6x9Uu_9EsGMBBd:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/21c070ebe6ed8cc8eb1221dc6efdccfd90e4fed5/crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs#L210)):*
> ```XML
>         context: &dyn SignatureSpecializationContext,
>     ) -> Result<LibfuncSignature, SpecializationError> {
>         // TODO: Why do we need the handle, if we are allowing to cast Box<...> to it?
> ```

done
___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs` line 230 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5647#-NyzuDi72_hd2gbt9e-8:-NyzuDi72_hd2gbt9e-9:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/21c070ebe6ed8cc8eb1221dc6efdccfd90e4fed5/crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs#L230)):*
> ```XML
>         context: &dyn SignatureSpecializationContext,
>     ) -> Result<LibfuncSignature, SpecializationError> {
>         // TODO: Same here.
> ```

done
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/felt252.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5647#-Nyzv2zKBRZRr5UvieCU:-Nyzv2zKBRZRr5UvieCV:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/21c070ebe6ed8cc8eb1221dc6efdccfd90e4fed5/crates/cairo-lang-sierra-to-casm/src/invocations/felt252.rs#L48)):*
> ```XML
>     add_input_variables! {casm_builder,
>         deref a;
>         deref_or_immediate b; // TODO: Signature doesn't allow it ATM.
> ```

done
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5647#-Nyzw3XMBgNQWWKzOjDG:-Nyzw3XN2xQbEfSSbaNu:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/21c070ebe6ed8cc8eb1221dc6efdccfd90e4fed5/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L60)):*
> ```XML
>         BoundedIntDivRemAlgorithm::KnownSmallLhs(_) => 4,
>     };
>     // TODO: What is the argument of buffer? and what is the relation to the (3, 4, 4) range checks
> ```

done

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5647)* status: 0 of 7 files reviewed, 14 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5647#-Nz-CHrOAJ1EhnG4XL5D:-Nz-CHrOAJ1EhnG4XL5E:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/21c070ebe6ed8cc8eb1221dc6efdccfd90e4fed5/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L143)):*
> ```XML
>                 // We can now guess which whether `b` or `q` is small enough and verify.
>                 const limiter_bound = lhs_upper_sqrt.clone();
>                 // TODO: Why not q <= limiter_bound?
> ```

done

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5647)* status: 0 of 7 files reviewed, 15 unresolved discussions (waiting on @liorgold2)

___
*[`corelib/src/test/integer_test.cairo` line 2018 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5647#-NzXsumz6jOqTok6A37v:-NzXsumz6jOqTok6A37w:bnquhwo) ([raw file](https://github.com/starkware-libs/cairo/blob/21c070ebe6ed8cc8eb1221dc6efdccfd90e4fed5/corelib/src/test/integer_test.cairo#L2018)):*
> ```Cairo
>     }
> 
>     type OurType = BoundedInt<1, 0x1000000000000000000000000000001000000000000000000000000000001>;
> ```

fixed and merged.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 525 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5647#-NzXvWa_2hacrk4zMxP7:-NzXvWa_2hacrk4zMxP8:b-us86vn) ([raw file](https://github.com/starkware-libs/cairo/blob/21c070ebe6ed8cc8eb1221dc6efdccfd90e4fed5/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L525)):*
> ```XML
>         args: &[GenericArg],
>     ) -> Result<LibfuncSignature, SpecializationError> {
>         // TODO: Shouldn't this function get a struct like `tuple_from_span`?
> ```

this would require getting generic arg `T` type instead of a `const C: usize` is this what we want?
___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 179 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5647#-NytPHiRCG4jomvNL-Q8:-NzXtU_U5Bsp5cSKakpZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/21c070ebe6ed8cc8eb1221dc6efdccfd90e4fed5/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L179)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

so we need a non-fallible wrap_nz function for this?
</blockquote></details>

Done.

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 2 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5647)* status: 2 of 7 files reviewed, 15 unresolved discussions (waiting on @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5647)* status: 2 of 7 files reviewed, 16 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 179 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5647#-NzwMoPR3j1vZenkwP0W:-NzwMoPR3j1vZenkwP0X:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/21c070ebe6ed8cc8eb1221dc6efdccfd90e4fed5/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L179)):*
> ```XML
>                 ParamSignature::new(range_check_type.clone()).with_allow_add_const(),
>                 ParamSignature::new(lhs.clone()),
>                 // Maybe rhs should be NonZero<Range<>>?
> ```

done.

**Pull request closed without merging**
