### PR TITLE
Removed warnings for deprecated contract attributes.

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4108)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4108)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4108#-NenFAvF5ENApYCHulUr:-NenFAvF5ENApYCHulUs:b-x3nl2h) ([raw file](https://github.com/starkware-libs/cairo/blob/c2b6a3fe0cdd6c2c3115e048f0c88e6ccf9a188e/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L17)):*
> ```XML
> pub fn handle_trait(db: &dyn SyntaxGroup, trait_ast: ast::ItemTrait) -> PluginResult {
>     if trait_ast.has_attr(db, DEPRECATED_ABI_ATTR) {
>         return PluginResult {
> ```

Even if ABI is allowed, it should still be disallowed here 
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/mod.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4108#-NenF6Xt74QlzWixkyCT:-NenF6Xt74QlzWixkyCU:b-kxtsxq) ([raw file](https://github.com/starkware-libs/cairo/blob/c2b6a3fe0cdd6c2c3115e048f0c88e6ccf9a188e/crates/cairo-lang-starknet/src/plugin/starknet_module/mod.rs#L94)):*
> ```XML
> /// Handles a contract/component module item.
> pub(super) fn handle_module(db: &dyn SyntaxGroup, module_ast: ast::ItemModule) -> PluginResult {
>     if module_ast.has_attr(db, DEPRECATED_CONTRACT_ATTR) {
> ```

Why remove this?

**Comment by yuvalsw** [comment]
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/mod.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4108#-NenF6Xt74QlzWixkyCT:-NenIFBj-PrMaSNUcB4n:bm8f38o) ([raw file](https://github.com/starkware-libs/cairo/blob/c2b6a3fe0cdd6c2c3115e048f0c88e6ccf9a188e/crates/cairo-lang-starknet/src/plugin/starknet_module/mod.rs#L94)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Why remove this?
</blockquote></details>

It's very old. I was to help confusion with the old attrs, which are now very old. Doesn't seem to be necessary anymore and adds redundant code.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4108)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4108#-NenFAvF5ENApYCHulUr:-NenIgO1E2DDNHj6u_d3:bbygolp) ([raw file](https://github.com/starkware-libs/cairo/blob/c2b6a3fe0cdd6c2c3115e048f0c88e6ccf9a188e/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L17)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

The removed logic was only to help users who confused with the old attr. It now does nothing, like any other attr here. (will return in the if below)
</blockquote></details>

It would still help the old users - this is on a trait.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4108)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/mod.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4108#-NenF6Xt74QlzWixkyCT:-NenItap4SSZKAgtMYWi:b9ntaiy) ([raw file](https://github.com/starkware-libs/cairo/blob/c2b6a3fe0cdd6c2c3115e048f0c88e6ccf9a188e/crates/cairo-lang-starknet/src/plugin/starknet_module/mod.rs#L94)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

It's very old. I was to help confusion with the old attrs, which are now very old. Doesn't seem to be necessary anymore and adds redundant code.
</blockquote></details>

We still need to help users, we don't know if these are users updating from the oldest version

**Pull request closed without merging**
