### PR TITLE
Added non-base storage address.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:afb4ec96

---

**Stack**:
- #1805
- #1803
- #1802 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1802)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1802)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`tests/e2e_test_data/libfuncs/starknet/storage` line 84 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1802#-NM3CyzaARE8NL5y8Enn:-NM3CyzaARE8NL5y8Eno:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/3691ee6b05c0c3c0be63490a28e950d8b866e88f/tests/e2e_test_data/libfuncs/starknet/storage#L84)):*
> ```
> //! > cairo
> fn foo(addr: felt) -> starknet::StorageBaseAddress {
>     starknet::storage_base_address_from_felt(addr)
> ```





_Suggestion:_
```
 storage_base_address_from_base_and_offset
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1802)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`tests/e2e_test_data/libfuncs/starknet/storage` line 84 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1802#-NM3CyzaARE8NL5y8Enn:-NM3WIoW9gjarS_-xNsx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3691ee6b05c0c3c0be63490a28e950d8b866e88f/tests/e2e_test_data/libfuncs/starknet/storage#L84)):*
> ```
> //! > cairo
> fn foo(addr: felt) -> starknet::StorageBaseAddress {
>     starknet::storage_base_address_from_felt(addr)
> ```

Done.



_Code quote:_
```
storage_base_address_from_base_and_offset
```

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1802#-:-NM3hti89EnAi5fXLb5x:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1802)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
