### PR TITLE
Add EmptyDemandReporter.

### PR DESCRIPTION
**Pull request by liorgold2**
**Stack**:
- #6328
- #6327 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6327)

### CODE REVIEW

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6327#-:-O5lZmA05KyKjlw9ofsX:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6327)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-lowering/src/borrow_check/demand.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6327#-O5lh2aJ7s3FjBOnn26T:-O5lh2aJ7s3FjBOnn26U:b-cnxe7y) ([raw file](https://github.com/starkware-libs/cairo/blob/b08ad360e187f60f282e6a63ddfbd0ea4671ed27/crates/cairo-lang-lowering/src/borrow_check/demand.rs#L28)):*
> ```XML
>     type IntroducePosition = ();
>     type UsePosition = ();
> }
> ```

what's the usecase?



_Code quote:_
```XML
pub struct EmptyDemandReporter {}

impl<Var> DemandReporter<Var> for EmptyDemandReporter {
    type IntroducePosition = ();
    type UsePosition = ();
}
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6327)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/borrow_check/demand.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6327#-O5lh2aJ7s3FjBOnn26T:-O5m_xH74EqV1FbV92ZM:b3dxzb5) ([raw file](https://github.com/starkware-libs/cairo/blob/b08ad360e187f60f282e6a63ddfbd0ea4671ed27/crates/cairo-lang-lowering/src/borrow_check/demand.rs#L28)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

what's the usecase?
</blockquote></details>

See the other file. Instead of relying on `self` and implementing a naive `DemandReporter`. You don't really need a reporter there.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6327#-:-O5mbVivEjOhagPi4sh_:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @liorgold2)

**Pull request merged**
