### PR TITLE
add support for match on none felt252 numeric values

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4764)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4764)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1223 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4764#-NngkZn4CELhRXXO-car:-NngkZn4CELhRXXO-cas:bub6vq3) ([raw file](https://github.com/starkware-libs/cairo/blob/cadb43d428d3fdc5317bc00a2212107489c119d0/crates/cairo-lang-lowering/src/lower/mod.rs#L1223)):*
> ```XML
>     let ty = matched_expr.ty();
> 
>     if ty == ctx.db.core_felt252_ty() {
> ```

can you make sure (in a test) what happens when we have typed literals? e.g.
```
match 5_u32 {
   0_felt252 => {}
   _ => {}
}
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4764)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1223 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4764#-NngkZn4CELhRXXO-car:-Nnhz_J_8HvdoUn8ooWT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cadb43d428d3fdc5317bc00a2212107489c119d0/crates/cairo-lang-lowering/src/lower/mod.rs#L1223)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can you make sure (in a test) what happens when we have typed literals? e.g.
```
match 5_u32 {
   0_felt252 => {}
   _ => {}
}
```
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4764)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`examples/fib_match.cairo` line 2 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4764#-Nni0diJ2HayqDu6JLgm:-Nni0diJ2HayqDu6JLgn:bdr4mma) ([raw file](https://github.com/starkware-libs/cairo/blob/f157aaaf06238e3b1507e77e1df2103f9a261347/examples/fib_match.cairo#L2)):*
> ```Cairo
> // Calculates fib...
> fn fib(n: u32) -> u32 {
> ```

revert to felt - this makes it much more difficult to read the resulting code.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4764)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/test_data/match` line 298 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4764#-Nni0plh0NPXbWNXy_f4:-Nni0pli2fCCZYITNcst:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f157aaaf06238e3b1507e77e1df2103f9a261347/crates/cairo-lang-lowering/src/test_data/match#L298)):*
> ```
> 
>         
>         _ => 9,
> ```





_Suggestion:_
```
        0_u8 => 7,
        1_u8 | 2_u8 => 8,
        _ => 9,
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4764)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/test_data/match` line 388 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4764#-Nni0tvB2nmE5oh-2WUb:-Nni0tvB2nmE5oh-2WUc:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/f157aaaf06238e3b1507e77e1df2103f9a261347/crates/cairo-lang-lowering/src/test_data/match#L388)):*
> ```
> 
>         
>         _ => 9,
> ```

.



_Suggestion:_
```
        1_felt252 | 2_u8 => 8,
        _ => 9,
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4764)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/test_data/match` line 298 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4764#-Nni0plh0NPXbWNXy_f4:-NniDC-n5E2bEHZgGRGd:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f157aaaf06238e3b1507e77e1df2103f9a261347/crates/cairo-lang-lowering/src/test_data/match#L298)):*
> ```
> 
>         
>         _ => 9,
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/test_data/match` line 388 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4764#-Nni0tvB2nmE5oh-2WUb:-NniDCpt-62wZS9CpWKe:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f157aaaf06238e3b1507e77e1df2103f9a261347/crates/cairo-lang-lowering/src/test_data/match#L388)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`examples/fib_match.cairo` line 2 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4764#-Nni0diJ2HayqDu6JLgm:-NniDiXd8GHW6DeMJiAh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f157aaaf06238e3b1507e77e1df2103f9a261347/examples/fib_match.cairo#L2)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

revert to felt - this makes it much more difficult to read the resulting code.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 5 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4764)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1590 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4764#-NniE9xp-hhavJkN3Akx:-NniE9xq54tH_18kDWDU:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/73fdb4e9620dfcef370c77a3dfe7090e8ef76a94/crates/cairo-lang-lowering/src/lower/mod.rs#L1590)):*
> ```XML
>         let ret_ty = corelib::core_felt252_ty(ctx.db.upcast());
>         // TODO(TomerStarkware): use the same type of literal as the input, without the cast to
>         // felt252.
> ```





_Suggestion:_
```XML
        // TODO(TomerStarkware): Use the same type of literal as the input, without the cast to
        // felt252.
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4764)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1590 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4764#-NniE9xp-hhavJkN3Akx:-NniF7x30C-1TcWtGU-w:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/73fdb4e9620dfcef370c77a3dfe7090e8ef76a94/crates/cairo-lang-lowering/src/lower/mod.rs#L1590)):*
> ```XML
>         let ret_ty = corelib::core_felt252_ty(ctx.db.upcast());
>         // TODO(TomerStarkware): use the same type of literal as the input, without the cast to
>         // felt252.
> ```

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4764)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
