### PR TITLE
Add var_ids to MatchArm.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2425)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 13 of 36 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2425)* status: 13 of 36 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`corelib/src/array.cairo` line 7 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2425#-NQ4JBmu6od5i6K6Ik9U:-NQ4JBmu6od5i6K6Ik9V:b-zhhsx1) ([raw file](https://github.com/starkware-libs/cairo/blob/16dd52fb8ee2f2023ca2606140d2b490b3e24262/corelib/src/array.cairo#L7)):*
> ```Cairo
> extern fn array_snapshot_pop_front<T>(ref arr: @Array<T>) -> Option<@T> nopanic;
> #[panic_with('Index out of bounds', array_at)]
> #[inline(always)]
> ```

This is not related

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 21 of 36 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2425)* status: 26 of 36 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 267 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2425#-NQ4LcmBEWLUWP7yoVUZ:-NQ4LcmBEWLUWP7yoVU_:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/deff6fe409dad32dca0a4b4d77260364cd2b1cc3/crates/cairo-lang-lowering/src/lower/context.rs#L267)):*
> ```XML
>                             subscope.add_input(ctx, VarRequest { ty, location: self.location })
>                         })
>                         .collect();
> ```





_Suggestion:_
```XML
collect_vec
```
___
*[`crates/cairo-lang-lowering/src/lower/lower_if.rs` line 189 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2425#-NQ4LS7C0PraHberQ9to:-NQ4LS7C0PraHberQ9tp:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/deff6fe409dad32dca0a4b4d77260364cd2b1cc3/crates/cairo-lang-lowering/src/lower/lower_if.rs#L189)):*
> ```XML
> /// Lowers an optional else block. If the else block is missing it is replaced with a block
> /// returning a unit.
> /// Return the else block input variable and the sealed block builder of the else block.
> ```





_Suggestion:_
```XML
Returns
```
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 613 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2425#-NQ4Jt9V9_I_u61wiy9Y:-NQ4Jt9V9_I_u61wiy9Z:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/16dd52fb8ee2f2023ca2606140d2b490b3e24262/crates/cairo-lang-lowering/src/lower/mod.rs#L613)):*
> ```XML
>                 .into_iter()
>                 .map(|ty| subscope.add_input(ctx, VarRequest { ty, location }))
>                 .collect();
> ```





_Suggestion:_
```XML
collect_vec
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2425)* status: 26 of 36 files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`corelib/src/array.cairo` line 7 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2425#-NQ4JBmu6od5i6K6Ik9U:-NQ4Nfur98e3dGLFCOTr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/16dd52fb8ee2f2023ca2606140d2b490b3e24262/corelib/src/array.cairo#L7)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

This is not related 
</blockquote></details>

Done.



_Code quote (from crates/cairo-lang-lowering/src/lower/context.rs):_
```XML
 subscope.add_input(ctx, VarRequest { ty, location: self.location 
```
___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 267 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2425#-NQ4LcmBEWLUWP7yoVUZ:-NQ4NhGLEn7aYx14DoP7:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/deff6fe409dad32dca0a4b4d77260364cd2b1cc3/crates/cairo-lang-lowering/src/lower/context.rs#L267)):*
> ```XML
>                             subscope.add_input(ctx, VarRequest { ty, location: self.location })
>                         })
>                         .collect();
> ```

done
___
*[`crates/cairo-lang-lowering/src/lower/lower_if.rs` line 189 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2425#-NQ4LS7C0PraHberQ9to:-NQ4NZNEDy9am5c_svIB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/deff6fe409dad32dca0a4b4d77260364cd2b1cc3/crates/cairo-lang-lowering/src/lower/lower_if.rs#L189)):*
> ```XML
> /// Lowers an optional else block. If the else block is missing it is replaced with a block
> /// returning a unit.
> /// Return the else block input variable and the sealed block builder of the else block.
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 613 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2425#-NQ4Jt9V9_I_u61wiy9Y:-NQ4Ni71EBjmgU8AAzoS:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/16dd52fb8ee2f2023ca2606140d2b490b3e24262/crates/cairo-lang-lowering/src/lower/mod.rs#L613)):*
> ```XML
>                 .into_iter()
>                 .map(|ty| subscope.add_input(ctx, VarRequest { ty, location }))
>                 .collect();
> ```

done

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 14 of 36 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2425)* status: 32 of 36 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`corelib/src/array.cairo` line 37 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2425#-NQ4Odjr2_-BHKPX4BAv:-NQ4Odjr2_-BHKPX4BAw:bd5say7) ([raw file](https://github.com/starkware-libs/cairo/blob/255d66c50fcdc1e8671f79e888b5ccb805cb4366/corelib/src/array.cairo#L37)):*
> ```Cairo
>         array_get(self, index)
>     }
>     #[inline(always)]
> ```

I meant the entire file

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2425)* status: 34 of 36 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2425#-:-NQ4TwzH2JPATQCUtQ8e:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2425#-:-NQ4pyjbAzPJMRvksoZB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
