### PR TITLE
Added `println!` inline macro

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4332)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4332)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/inline_macros/print.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4332#-Ni8_zFZATcS3EwooG6J:-Ni8_zFZATcS3EwooG6K:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/9cedca0d41ea2779ba8d05fda781ec99fe958126/crates/cairo-lang-semantic/src/inline_macros/print.rs#L112)):*
> ```XML
> }
> 
> fn get_macro_name(with_newline: bool) -> &'static str {
> ```

doc

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4332)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/inline_macros/print.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4332#-Ni8_zFZATcS3EwooG6J:-Ni8vbFkCOI-RRHziOff:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9cedca0d41ea2779ba8d05fda781ec99fe958126/crates/cairo-lang-semantic/src/inline_macros/print.rs#L112)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4332#-:-Ni91jGb5p_CeoXAFqvq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4332)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
