### PR TITLE
Formatter add comment component (Formatter temporary broken)

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1583)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1583)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/formatter/src/formatter.rs` line 217 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1583#-NKjHpMv2kPPPopkAq-7:-NKjHpMv2kPPPopkAq-8:bq7015f) ([raw file](https://github.com/starkware-libs/cairo/blob/85a29d8a40de48622b5e98ec01b47d44f0b9f7c2/crates/formatter/src/formatter.rs#L217)):*
> ```XML
>     }
>     /// Appends a comment to the line.
>     pub fn push_comment(&mut self, content: &str, is_leading: bool) {
> ```

I don't understand - when is a comment leading? We only have // comments which mean the whole line after it is a comment (besides the \n).
Can you please add a test for the cases you covered in this PR?
___
*[`crates/formatter/src/formatter.rs` line 632 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1583#-NKjHB9q3kmwbz_BWQTe:-NKjHB9rDOanNBmDQxkf:b-2vjubm) ([raw file](https://github.com/starkware-libs/cairo/blob/85a29d8a40de48622b5e98ec01b47d44f0b9f7c2/crates/formatter/src/formatter.rs#L632)):*
> ```XML
>         trivia: syntax::node::ast::Trivia,
>         mut allowed_newlines: usize,
>         is_leading: bool,
> ```

is this only relevant for comments? What should be the value for other trivia types?

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1583)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/formatter/src/formatter.rs` line 217 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1583#-NKjHpMv2kPPPopkAq-7:-NKrXwmH11aorBmwogPA:b6i8v1a) ([raw file](https://github.com/starkware-libs/cairo/blob/85a29d8a40de48622b5e98ec01b47d44f0b9f7c2/crates/formatter/src/formatter.rs#L217)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I don't understand - when is a comment leading? We only have // comments which mean the whole line after it is a comment (besides the \n).
Can you please add a test for the cases you covered in this PR?
</blockquote></details>

Leading comments are whole line comments which prepends the line, and trailing are comments after a line., e.g
```
// Leading
fn foo() {
    let x = 1; // Trailing.
}
```
It is called like that because of the leading and trailing trivia it belongs to. Got any better name?
___
*[`crates/formatter/src/formatter.rs` line 632 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1583#-NKjHB9q3kmwbz_BWQTe:-NKrYjtZ6PcKamn9EWup:b-9zmxai) ([raw file](https://github.com/starkware-libs/cairo/blob/85a29d8a40de48622b5e98ec01b47d44f0b9f7c2/crates/formatter/src/formatter.rs#L632)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

is this only relevant for comments? What should be the value for other trivia types?
</blockquote></details>

Other trivia types are whitespaces and newlines, and they are ignored.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1583)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/formatter/src/formatter.rs` line 217 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1583#-NKjHpMv2kPPPopkAq-7:-NKrb42pAwZeK9x64e_D:b8ow7vu) ([raw file](https://github.com/starkware-libs/cairo/blob/85a29d8a40de48622b5e98ec01b47d44f0b9f7c2/crates/formatter/src/formatter.rs#L217)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Leading comments are whole line comments which prepends the line, and trailing are comments after a line., e.g
```
// Leading
fn foo() {
    let x = 1; // Trailing.
}
```
It is called like that because of the leading and trailing trivia it belongs to. Got any better name?
</blockquote></details>

And it is tested in test1.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1583)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/formatter/src/formatter.rs` line 217 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1583#-NKjHpMv2kPPPopkAq-7:-NKxM-2yDtCnA2HNfqCA:b-ieio33) ([raw file](https://github.com/starkware-libs/cairo/blob/85a29d8a40de48622b5e98ec01b47d44f0b9f7c2/crates/formatter/src/formatter.rs#L217)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

And it is tested in test1.
</blockquote></details>

As discussed f2f, let's change this with breaking the line after a comment (non optional break points)

**Pull request closed without merging**
