### PR TITLE
Use match instead of an `if` chain

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4067)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4067)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-language-server/src/semantic_highlighting/token_kind.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4067#-NeHefJIAzfce1MTOb-Q:-NeHefJIAzfce1MTOb-R:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b4a921c748b3d5072ddaef4acc4fc2f511b0df2c/crates/cairo-lang-language-server/src/semantic_highlighting/token_kind.rs#L96)):*
> ```XML
>             {
>                 return Some(SemanticTokenKind::Class);
>             }
> ```





_Suggestion:_
```XML
            SyntaxKind::ItemInlineMacro => return Some(SemanticTokenKind::InlineMacro),
            SyntaxKind::AliasClause => return Some(SemanticTokenKind::Class),
            _ if ast::Item::is_variant(parent_kind) => return Some(SemanticTokenKind::Class),
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-language-server/src/semantic_highlighting/token_kind.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4067#-NeHefJIAzfce1MTOb-Q:-NeHgipD4XmKYvymAlhD:b-df2jge) ([raw file](https://github.com/starkware-libs/cairo/blob/b4a921c748b3d5072ddaef4acc4fc2f511b0df2c/crates/cairo-lang-language-server/src/semantic_highlighting/token_kind.rs#L96)):*
> ```XML
>             {
>                 return Some(SemanticTokenKind::Class);
>             }
> ```

Why split the two cases?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4067)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-language-server/src/semantic_highlighting/token_kind.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4067#-NeHefJIAzfce1MTOb-Q:-NeHhsoM1TxaIwbWSNKV:bvvmem) ([raw file](https://github.com/starkware-libs/cairo/blob/b4a921c748b3d5072ddaef4acc4fc2f511b0df2c/crates/cairo-lang-language-server/src/semantic_highlighting/token_kind.rs#L96)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why split the two cases?
</blockquote></details>

doing an `| matches!` within a match seems weirder to me

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4067)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-language-server/src/semantic_highlighting/token_kind.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4067#-NeHefJIAzfce1MTOb-Q:-NeHihOl6Ssw9sx6M4KV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b4a921c748b3d5072ddaef4acc4fc2f511b0df2c/crates/cairo-lang-language-server/src/semantic_highlighting/token_kind.rs#L96)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doing an `| matches!` within a match seems weirder to me
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4067#-:-NeHlN2lAB167sx6LI10:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
