### PR TITLE
Add pythonic run_circuit hint.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5792)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5792)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 819 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5792#-O-G_0l031Kum8MhSUEB:-O-G_0l031Kum8MhSUEC:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9ccbf33ac54efcd65962564b883adbe8d1009080/crates/cairo-lang-casm/src/hints/mod.rs#L819)):*
> ```XML
>                 }
>             }
>         }
> ```





_Suggestion:_
```XML
                formatdoc! {"
                
                from starkware.cairo.lang.builtins.modulo.mod_builtin_runner import run_circuit

                memory{computed_gates_out} = run_circuit(
                    memory=memory,
                    values_ptr={values_ptr},
                    add_mod_builtin={add_mod_builtin},
                    n_add_mods={n_add_mods},
                    mul_mod_builtin={mul_mod_builtin},
                    n_mul_mods={n_mul_mods},
                    modulus_ptr={modulus_ptr},
                )
                "}
            }
        }
```
___
*[`tests/e2e_test_data/libfuncs/circuit` line 297 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5792#-O-G_Cfq9x95xMvLwnrp:-O-G_Cfq9x95xMvLwnrq:btstx81) ([raw file](https://github.com/starkware-libs/cairo/blob/9ccbf33ac54efcd65962564b883adbe8d1009080/tests/e2e_test_data/libfuncs/circuit#L297)):*
> ```
> %{ from starkware.cairo.lang.builtins.modulo.mod_builtin_runner import run_circuit
> 
> memory[ap + 0] = run_circuit(
> ```

the above suggestion should cause this.



_Suggestion:_
```
[fp + -9] = [[fp + -12] + 5];
%{
from starkware.cairo.lang.builtins.modulo.mod_builtin_runner import run_circuit

memory[ap + 0] = run_circuit(
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5792#-:-O-UsrYzCzL6hfz8oszt:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5792)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 819 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5792#-O-G_0l031Kum8MhSUEB:-O-UlmzS8itIYJjgIkKC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9ccbf33ac54efcd65962564b883adbe8d1009080/crates/cairo-lang-casm/src/hints/mod.rs#L819)):*
> ```XML
>                 }
>             }
>         }
> ```

Done.

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5792)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5792#-:-O-_HqB_852QHtC7mKVu:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
