### PR TITLE
Assign missing to all unassigned type_vars.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5328)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5328)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 548 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5328#-NtuFOD89pwzv88KIqir:-NtuFOD89pwzv88KIqis:brhx1dy) ([raw file](https://github.com/starkware-libs/cairo/blob/daafa1c97012406d0badcacc235a3b52676383c1/crates/cairo-lang-semantic/src/expr/inference.rs#L548)):*
> ```XML
>         );
>         let (var, err) = self.first_undetermined_variable()?;
>         let ty_missing = TypeId::missing(self.db, skip_diagnostic());
> ```

do why the skip is ok.



_Code quote:_
```XML
        let ty_missing = TypeId::missing(self.db, skip_diagnostic());
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5328)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 548 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5328#-NtuFOD89pwzv88KIqir:-NuTuHYB29EGwzqCDKVL:bce9xas) ([raw file](https://github.com/starkware-libs/cairo/blob/daafa1c97012406d0badcacc235a3b52676383c1/crates/cairo-lang-semantic/src/expr/inference.rs#L548)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

do why the skip is ok.
</blockquote></details>

moved after the diagnostic reporting.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5328)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 612 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5328#-NuU1Djt9aAwtyyYCSuk:-NuU1Dju06G2KwOF3pA3:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b0eec77d3b8aa2385eb713a14b31da6e4af3dc07/crates/cairo-lang-semantic/src/expr/inference.rs#L612)):*
> ```XML
> 
>     /// Finalizes the inference and report diagnostics if there are any errors.
>     /// All the remaining type var are replace with a missing type.
> ```





_Suggestion:_
```XML
    /// All the remaining type vars are mapped to the `missing` type, to prevent additional diagnostics.
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5328)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/inference.rs` line 612 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5328#-NuU1Djt9aAwtyyYCSuk:-NuXVIsw4O2RVMcNhThy:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b0eec77d3b8aa2385eb713a14b31da6e4af3dc07/crates/cairo-lang-semantic/src/expr/inference.rs#L612)):*
> ```XML
> 
>     /// Finalizes the inference and report diagnostics if there are any errors.
>     /// All the remaining type var are replace with a missing type.
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5328#-:-NuYfEor9tJ8ah_pMRDh:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
