### PR TITLE
Used default code in e2e tests result.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4650)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4650)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`tests/e2e_test.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4650#-NmVwW4u0xEfexb8Arwy:-NmVwW4v6sM_N2wGMkd7:bp94w9o) ([raw file](https://github.com/starkware-libs/cairo/blob/a30c5bdbaf37700f1854aae70dc8e081c558519e/tests/e2e_test.rs#L213)):*
> ```XML
>         metadata_config.linear_gas_solver = false;
>         metadata_config.linear_ap_change_solver = false;
>         let metadata_with_solver = calc_metadata(&sierra_program, metadata_config).unwrap();
> ```

rename with/no to with_<solver_name>



_Code quote:_
```XML
metadata_with_solver
```

**Review by yuvalsw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4650)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4650#-:-NmVxZvo7P_tVIScxZ7G:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4650)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
