### PR TITLE
Const in Statements Semantic support

### PR DESCRIPTION
**Pull request by Tomer-StarkWare**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6299)

### CODE REVIEW

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6299#-:-O5Muj7y2xUY8qEMJkkv:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 9 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6299)* status: 14 of 15 files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, @piotmag769, and @Tomer-StarkWare)

___
*[`corelib/src/test/language_features/const_test.cairo` line 144 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6299#-O5N-7yb9Vbg3zKbsfLA:-O5N-7yb9Vbg3zKbsfLB:b-ws9pi9) ([raw file](https://github.com/starkware-libs/cairo/blob/c5062031bdfbba82460b3add42108e4e64a76993/corelib/src/test/language_features/const_test.cairo#L144)):*
> ```Cairo
>     }
>     assert!(Y == 4);
> }
> ```

Add test for shadowing of a global const.



_Code quote:_
```Cairo
#[test]
fn test_const_shadowing() {
    const Y: u8 = 4_u8;
    {
        const Y: u8 = 2;
        assert!(Y == 2);
    }
    assert!(Y == 4);
}
```
___
*[`crates/cairo-lang-semantic/src/semantic.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6299#-O5N-_8900jRdsLFnm2G:-O5N-_8900jRdsLFnm2H:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c5062031bdfbba82460b3add42108e4e64a76993/crates/cairo-lang-semantic/src/semantic.rs#L45)):*
> ```XML
> }
> 
> /// Semantic model of a constant.
> ```





_Suggestion:_
```XML
/// Semantic model of a local constant.
```
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 3492 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6299#-O5N-sDc4i3Radbk2r68:-O5N-sDc4i3Radbk2r69:b-bbvidg) ([raw file](https://github.com/starkware-libs/cairo/blob/c5062031bdfbba82460b3add42108e4e64a76993/crates/cairo-lang-semantic/src/expr/compute.rs#L3492)):*
> ```XML
>                     })
>                 }
>                 ast::ModuleItem::Module(_) => unreachable!("Module type not supported."),
> ```

And for all the others as well.



_Suggestion:_
```XML
("Modules are not supported inside a function."),
```
___
*[`crates/cairo-lang-semantic/src/expr/objects.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6299#-O5N0FW46tj1ME9czKEL:-O5N0FW46tj1ME9czKEM:bxah4l7) ([raw file](https://github.com/starkware-libs/cairo/blob/c5062031bdfbba82460b3add42108e4e64a76993/crates/cairo-lang-semantic/src/expr/objects.rs#L128)):*
> ```XML
> #[debug_db(ExprFormatter<'a>)]
> pub struct StatementItem {
>     pub expr: ExprId,
> ```

Why it holds an expr?



_Code quote:_
```XML
pub expr: ExprId,
```
___
*[`crates/cairo-lang-semantic/src/expr/test_data/constant` line 317 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6299#-O5N0ST9DgGcwfCgwiJe:-O5N0ST9DgGcwfCgwiJf:b-13xxas) ([raw file](https://github.com/starkware-libs/cairo/blob/c5062031bdfbba82460b3add42108e4e64a76993/crates/cairo-lang-semantic/src/expr/test_data/constant#L317)):*
> ```
> //! > ==========================================================================
> 
> //! > const in block
> ```

Add tests for a const and a variable with the same name.



_Code quote:_
```
//! > ==========================================================================

//! > const in block
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6299)* status: 14 of 15 files reviewed, 6 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @piotmag769, and @Tomer-StarkWare)

___
*[`corelib/src/test/language_features/const_test.cairo` line 136 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6299#-O5N5Er71kSOFAD8jLzL:-O5N5Er71kSOFAD8jLzM:b3qal0x) ([raw file](https://github.com/starkware-libs/cairo/blob/cc48e951fbed2be6783935d81d88ab09c78f08f8/corelib/src/test/language_features/const_test.cairo#L136)):*
> ```Cairo
> }
> 
> #[test]
> ```

move to new file `block_level_items_test.cairo`

**Review by mkaput — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6299)* status: all files reviewed, 6 unresolved discussions (waiting on @Arcticae, @Draggu, @piotmag769, and @Tomer-StarkWare)

**Review by mkaput — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6299)* status: all files reviewed, 6 unresolved discussions (waiting on @Arcticae, @Draggu, @piotmag769, and @Tomer-StarkWare)

**Review by Draggu — APPROVED** [review]
:lgtm:

> Reviewed 14 of 15 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6299#-:-O5NAbek7TYXzQQNaU37:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @Arcticae, @piotmag769, and @Tomer-StarkWare)

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6299)* status: 12 of 18 files reviewed, 6 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, and @mkaput)

___
*[`corelib/src/test/language_features/const_test.cairo` line 144 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6299#-O5N-7yb9Vbg3zKbsfLA:-O5OWGXB57ZwNqPUDP5_:bbrlkl1) ([raw file](https://github.com/starkware-libs/cairo/blob/c5062031bdfbba82460b3add42108e4e64a76993/corelib/src/test/language_features/const_test.cairo#L144)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i don't see it in the new test file.
</blockquote></details>

It is in cairo-lang-semantic/src/expr/semantic_test_data/const.
Attached is a photo of the relevant code here:

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6299)* status: 12 of 18 files reviewed, 6 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, and @Tomer-StarkWare)

___
*[`corelib/src/test/language_features/const_test.cairo` line 144 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6299#-O5N-7yb9Vbg3zKbsfLA:-O5ObP4868DlCFPcO-FA:bl7laog) ([raw file](https://github.com/starkware-libs/cairo/blob/c5062031bdfbba82460b3add42108e4e64a76993/corelib/src/test/language_features/const_test.cairo#L144)):*
<details><summary><i>Previously, Tomer-StarkWare (TomerC-StarkWare) wrote…</i></summary><blockquote>

It is in cairo-lang-semantic/src/expr/semantic_test_data/const.
Attached is a photo of the relevant code here:

</blockquote></details>

the simple cairo level tests that test behaviour should still be added.
clearer and may check more various behaviour.

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6299)* status: 12 of 18 files reviewed, 6 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, and @orizi)

___
*[`corelib/src/test/language_features/block_level_items_test.cairo` line 3 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6299#-O5OUEocBdprcfeZ73Jf:-O5RppPK-wQPp-QnFKyS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f939f1b31dcbf8dfca045c9fd407493810b11af3/corelib/src/test/language_features/block_level_items_test.cairo#L3)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can you separate into actual test cases?
giving name that specifies what you test would make this clearer as well.
</blockquote></details>

Done.
___
*[`corelib/src/test/language_features/const_test.cairo` line 144 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6299#-O5N-7yb9Vbg3zKbsfLA:-O5Rqupm9kVSsiPpFJUC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c5062031bdfbba82460b3add42108e4e64a76993/corelib/src/test/language_features/const_test.cairo#L144)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the simple cairo level tests that test behaviour should still be added.
clearer and may check more various behaviour.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6299)* status: 12 of 18 files reviewed, 8 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, and @Tomer-StarkWare)

___
*[`crates/cairo-lang-defs/src/db.rs` line 90 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6299#-O5RtF0z8KX9Z9DxBma-:-O5RtF0z8KX9Z9DxBma0:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7e952cf51f8ee20fcf7ec0891ce88010491c0126/crates/cairo-lang-defs/src/db.rs#L90)):*
> ```XML
>     fn intern_plugin_generated_file(&self, id: PluginGeneratedFileLongId) -> PluginGeneratedFileId;
>     #[salsa::interned]
>     fn intern_local_const(&self, id: LocalConstLongId) -> LocalConstId;
> ```





_Suggestion:_
```XML
    #[salsa::interned]
    fn intern_local_var(&self, id: LocalVarLongId) -> LocalVarId;
    #[salsa::interned]
    fn intern_local_const(&self, id: LocalConstLongId) -> LocalConstId;
    #[salsa::interned]
    fn intern_plugin_generated_file(&self, id: PluginGeneratedFileLongId) -> PluginGeneratedFileId;
```
___
*[`crates/cairo-lang-defs/src/ids.rs` line 966 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6299#-O5RtINU7U2rTK5YCQz9:-O5RtINU7U2rTK5YCQzA:bersr1d) ([raw file](https://github.com/starkware-libs/cairo/blob/7e952cf51f8ee20fcf7ec0891ce88010491c0126/crates/cairo-lang-defs/src/ids.rs#L966)):*
> ```XML
>         let syntax_db = db.upcast();
>         let LocalConstLongId(module_file_id, ptr) = self;
>         let text = ptr.lookup(syntax_db).text(syntax_db);
> ```

add todo to have a better debug path. (to include the function)
___
*[`crates/cairo-lang-semantic/src/semantic.rs` line 107 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6299#-O5RuKlA8X_Vfq232LM2:-O5RuKlA8X_Vfq232LM3:b-974bni) ([raw file](https://github.com/starkware-libs/cairo/blob/7e952cf51f8ee20fcf7ec0891ce88010491c0126/crates/cairo-lang-semantic/src/semantic.rs#L107)):*
> ```XML
>         match self {
>             Binding::LocalVar(local) => local.ty,
>             Binding::LocalConst(local) => db.lookup_intern_const_value(local.value).ty(db).unwrap(),
> ```

rather not have an unwrap here.

probably just add the type into the `LocalConst` struct and look it up when creating.



_Code quote:_
```XML
db.lookup_intern_const_value(local.value).ty(db).unwrap()
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6299)* status: 12 of 18 files reviewed, 8 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, and @orizi)

___
*[`crates/cairo-lang-defs/src/db.rs` line 90 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6299#-O5RtF0z8KX9Z9DxBma-:-O5RvVhR0KcurCs7tWct:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7e952cf51f8ee20fcf7ec0891ce88010491c0126/crates/cairo-lang-defs/src/db.rs#L90)):*
> ```XML
>     fn intern_plugin_generated_file(&self, id: PluginGeneratedFileLongId) -> PluginGeneratedFileId;
>     #[salsa::interned]
>     fn intern_local_const(&self, id: LocalConstLongId) -> LocalConstId;
> ```

Done.
___
*[`crates/cairo-lang-defs/src/ids.rs` line 966 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6299#-O5RtINU7U2rTK5YCQz9:-O5RvlYPCal3jJfBN0zS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7e952cf51f8ee20fcf7ec0891ce88010491c0126/crates/cairo-lang-defs/src/ids.rs#L966)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add todo to have a better debug path. (to include the function)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/semantic.rs` line 107 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6299#-O5RuKlA8X_Vfq232LM2:-O5RxZKC3LBTkkzC6SWK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7e952cf51f8ee20fcf7ec0891ce88010491c0126/crates/cairo-lang-semantic/src/semantic.rs#L107)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rather not have an unwrap here.

probably just add the type into the `LocalConst` struct and look it up when creating.
</blockquote></details>

Done.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 15 files at r1, 1 of 1 files at r2, 3 of 6 files at r3, 4 of 6 files at r4, 2 of 2 files at r5, 5 of 6 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6299#-:-O5S3auc40cPp2G7ybo1:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @orizi, and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 3484 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6299#-O5S2nBv2UQDbFN0bo0f:-O5S2nBv2UQDbFN0bo0g:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/fd183d63f47b187b5a12e16854da9e0e627639ec/crates/cairo-lang-semantic/src/expr/compute.rs#L3484)):*
> ```XML
>                     )
>                     .intern(ctx.db);
>                     // db.lookup_intern_const_value(local.value).ty(db).unwrap()
> ```

remove



_Code quote:_
```XML
// db.lookup_intern_const_value(local.value).ty(db).unwrap()
```

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 1 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6299)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @orizi, and @Tomer-StarkWare)

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6299)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @gilbens-starkware, and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 3484 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6299#-O5S2nBv2UQDbFN0bo0f:-O5S4kvI1DlptgvpMsdI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fd183d63f47b187b5a12e16854da9e0e627639ec/crates/cairo-lang-semantic/src/expr/compute.rs#L3484)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6299)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @Arcticae and @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 15 files at r1, 1 of 6 files at r6, 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6299)* status: all files reviewed, 5 unresolved discussions (waiting on @Arcticae and @Tomer-StarkWare)

___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 110 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6299#-O5SGzLe3hQm1wJuXjZm:-O5SGzLf8zSlM0uQW1VJ:bsnx7hi) ([raw file](https://github.com/starkware-libs/cairo/blob/d70c8f59bc4b32944e2b5e19a79c8dab3c8e1b61/crates/cairo-lang-lowering/src/lower/context.rs#L110)):*
> ```XML
>     /// Semantic model for current function body.
>     pub function_body: Arc<semantic::FunctionBody>,
>     /// Definitions encountered for semantic variables.
> ```

fix doc.



_Code quote:_
```XML
    /// Definitions encountered for semantic variables.
```
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 207 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6299#-O5SHvEU8iiumi6kOHNG:-O5SHvEU8iiumi6kOHNH:b-d2hz89) ([raw file](https://github.com/starkware-libs/cairo/blob/d70c8f59bc4b32944e2b5e19a79c8dab3c8e1b61/crates/cairo-lang-semantic/src/expr/compute.rs#L207)):*
> ```XML
> 
>     /// Adds warning for unused variables if required.
>     fn add_unused_variable_warning(&mut self, var_name: &str, var: &Binding) {
> ```

fix doc and names.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 3074 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6299#-O5SHUxf8u0QVr5nJE3k:-O5SHUxf8u0QVr5nJE3l:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d70c8f59bc4b32944e2b5e19a79c8dab3c8e1b61/crates/cairo-lang-semantic/src/expr/compute.rs#L3074)):*
> ```XML
>                     ty: local_const.value.lookup_intern(ctx.db).ty(ctx.db).unwrap(),
>                     stable_ptr,
>                 })),
> ```





_Suggestion:_
```XML
                Binding::LocalConst(local_const) => Some(Expr::Constant(ExprConstant {
                    const_value_id: local_const.value,
                    ty: local_const.ty,
                    stable_ptr,
                })),
```
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 3491 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6299#-O5SGGQo8B2i_exoT0PW:-O5SGGQo8B2i_exoT0PX:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d70c8f59bc4b32944e2b5e19a79c8dab3c8e1b61/crates/cairo-lang-semantic/src/expr/compute.rs#L3491)):*
> ```XML
>                             ty: rhs_resolved_expr.ty(db.upcast())?,
>                         }),
>                     ) {
> ```





_Suggestion:_
```XML
                    );
                    let name_syntax = const_syntax.name(syntax_db);
                    let rhs_id = LocalConstLongId(
                        ctx.resolver.module_file_id,
                        name_syntax.stable_ptr(),
                    )
                    .intern(ctx.db);
                    let name = const_syntax.name(syntax_db).text(db.upcast());
                    if let Some(old_var) = ctx.environment.variables.insert(
                        name,
                        Binding::LocalConst(LocalConstant {
                            id: rhs_id,
                            value: db.intern_const_value(rhs_resolved_expr.clone()),
                            ty: rhs_resolved_expr.ty(db.upcast())?,
                        }),
                    ) {
```
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 3509 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6299#-O5SFT0g2ecWlzW2z1md:-O5SFT0g2ecWlzW2z1me:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d70c8f59bc4b32944e2b5e19a79c8dab3c8e1b61/crates/cairo-lang-semantic/src/expr/compute.rs#L3509)):*
> ```XML
>                                 ));
>                             }
>                         }
> ```





_Suggestion:_
```XML
                        let name = const_syntax.name(syntax_db).text(db.upcast());
                        return Err(ctx.diagnostics.report(
                            stmt_item_syntax.stable_ptr(),
                            match old_var {
                                Binding::LocalConst(_) => MultipleConstantDefinition(name),
                                Binding::LocalVar(_) | Binding::Param(_) => MultipleDefinitionforConstantVariable(name),
                            },
                        ));
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6299)* status: all files reviewed, 5 unresolved discussions (waiting on @Arcticae and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 110 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6299#-O5SGzLe3hQm1wJuXjZm:-O5SJp_40-Uk6e-hzq46:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d70c8f59bc4b32944e2b5e19a79c8dab3c8e1b61/crates/cairo-lang-lowering/src/lower/context.rs#L110)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix doc.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 207 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6299#-O5SHvEU8iiumi6kOHNG:-O5SK9tV-RM7GYohSJG2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d70c8f59bc4b32944e2b5e19a79c8dab3c8e1b61/crates/cairo-lang-semantic/src/expr/compute.rs#L207)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix doc and names.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 3074 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6299#-O5SHUxf8u0QVr5nJE3k:-O5SKIKy8v-xgKfXTIIC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d70c8f59bc4b32944e2b5e19a79c8dab3c8e1b61/crates/cairo-lang-semantic/src/expr/compute.rs#L3074)):*
> ```XML
>                     ty: local_const.value.lookup_intern(ctx.db).ty(ctx.db).unwrap(),
>                     stable_ptr,
>                 })),
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 3491 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6299#-O5SGGQo8B2i_exoT0PW:-O5SKURJ61qTZELG27Gi:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d70c8f59bc4b32944e2b5e19a79c8dab3c8e1b61/crates/cairo-lang-semantic/src/expr/compute.rs#L3491)):*
> ```XML
>                             ty: rhs_resolved_expr.ty(db.upcast())?,
>                         }),
>                     ) {
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 3509 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6299#-O5SFT0g2ecWlzW2z1md:-O5SKge8CZ2UtoV62fbH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d70c8f59bc4b32944e2b5e19a79c8dab3c8e1b61/crates/cairo-lang-semantic/src/expr/compute.rs#L3509)):*
> ```XML
>                                 ));
>                             }
>                         }
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 15 files at r1, 1 of 6 files at r3, 1 of 6 files at r6, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6299)* status: all files reviewed, 5 unresolved discussions (waiting on @Arcticae and @Tomer-StarkWare)

___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 112 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6299#-O5SL0ygAtfrX9rHNSrD:-O5SL0ygAtfrX9rHNSrE:b-u0xnhb) ([raw file](https://github.com/starkware-libs/cairo/blob/86d1cf20714493bb064a3f5b852818891051fd39/crates/cairo-lang-lowering/src/lower/context.rs#L112)):*
> ```XML
>     /// Definitions encountered for semantic bindings.
>     // TODO(spapini): consider moving to semantic model.
>     pub semantic_defs: UnorderedHashMap<semantic::VarId, semantic::Binding>,
> ```

now i notice it is in lowering - would consts won't actually appear here.

fix doc to actually reflect that.



_Code quote:_
```XML
    pub semantic_defs: UnorderedHashMap<semantic::VarId, semantic::Binding>,
```
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 3331 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6299#-O5SLcsw25tbtq9GpZPH:-O5SLcsw25tbtq9GpZPI:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/86d1cf20714493bb064a3f5b852818891051fd39/crates/cairo-lang-semantic/src/expr/compute.rs#L3331)):*
> ```XML
>                             ctx.add_unused_binding_warning(&v.name, &old_var);
>                         }
>                     }
> ```





_Suggestion:_
```XML
                    if matches!(old_var, Binding::LocalConst(_)) {
                        return Err(ctx.diagnostics.report(
                            v.stable_ptr,
                            MultipleDefinitionforConstantVariable(v.name.clone()),
                        ));
                    }
                    ctx.add_unused_binding_warning(&v.name, &old_var);
```
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 3501 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6299#-O5SLvWcD96Oh_8IPx0W:-O5SLvWcD96Oh_8IPx0X:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/86d1cf20714493bb064a3f5b852818891051fd39/crates/cairo-lang-semantic/src/expr/compute.rs#L3501)):*
> ```XML
>                                 }
>                             },
>                         ));
> ```





_Suggestion:_
```XML
                    let name_syntax = const_syntax.name(syntax_db);
                    let rhs_id =
                        LocalConstLongId(ctx.resolver.module_file_id, name_syntax.stable_ptr())
                            .intern(ctx.db);
                    let name = const_syntax.name(syntax_db).text(db.upcast());
                    if let Some(old_var) = ctx.environment.variables.insert(
                        name.clone(),
                        Binding::LocalConst(LocalConstant {
                            id: rhs_id,
                            value: db.intern_const_value(rhs_resolved_expr.clone()),
                            ty: rhs_resolved_expr.ty(db.upcast())?,
                        }),
                    ) {
                        return Err(ctx.diagnostics.report(
                            stmt_item_syntax.stable_ptr(),
                            match old_var {
                                Binding::LocalConst(_) => MultipleConstantDefinition(name),
                                Binding::LocalVar(_) | Binding::Param(_) => {
                                    MultipleDefinitionforConstantVariable(name)
                                }
                            },
                        ));
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6299)* status: 16 of 19 files reviewed, 5 unresolved discussions (waiting on @Arcticae and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 112 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6299#-O5SL0ygAtfrX9rHNSrD:-O5SfDgI6GyR2o-uMiPC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/86d1cf20714493bb064a3f5b852818891051fd39/crates/cairo-lang-lowering/src/lower/context.rs#L112)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

now i notice it is in lowering - would consts won't actually appear here.

fix doc to actually reflect that.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 3331 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6299#-O5SLcsw25tbtq9GpZPH:-O5Sdryv8vv0-sxLyjGO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/86d1cf20714493bb064a3f5b852818891051fd39/crates/cairo-lang-semantic/src/expr/compute.rs#L3331)):*
> ```XML
>                             ctx.add_unused_binding_warning(&v.name, &old_var);
>                         }
>                     }
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 3501 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6299#-O5SLvWcD96Oh_8IPx0W:-O5Se1g_10PYBG7524JR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/86d1cf20714493bb064a3f5b852818891051fd39/crates/cairo-lang-semantic/src/expr/compute.rs#L3501)):*
> ```XML
>                                 }
>                             },
>                         ));
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6299)* status: 18 of 19 files reviewed, 1 unresolved discussion (waiting on @Arcticae and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/items/us.rs` line 49 at r10](https://reviewable.io/reviews/starkware-libs/cairo/6299#-O5SgExm5TI_QivlKlxe:-O5SgExm5TI_QivlKlxf:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/cda29477336005d75a4fbf408ce7a84e17ad92ab/crates/cairo-lang-semantic/src/items/us.rs#L49)):*
> ```XML
> }
> 
> mod x {
> ```

?

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6299)* status: 18 of 19 files reviewed, 1 unresolved discussion (waiting on @Arcticae and @orizi)

___
*[`crates/cairo-lang-semantic/src/items/us.rs` line 49 at r10](https://reviewable.io/reviews/starkware-libs/cairo/6299#-O5SgExm5TI_QivlKlxe:-O5SgcNL2P-6pKxNTw9e:bgw90a1) ([raw file](https://github.com/starkware-libs/cairo/blob/cda29477336005d75a4fbf408ce7a84e17ad92ab/crates/cairo-lang-semantic/src/items/us.rs#L49)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

Checkout mistake

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6299#-:-O5SilnR7WRD9NPn8y3s:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae)

**Pull request merged**
