### PR TITLE
Made sierragen prepare arguments for branch functions as well.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:e2e0c3e6

---

**Stack**:
- #1303
- #1302 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1302)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1302)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/sierra_generator/src/store_variables/test.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1302#-NJ5AmXYDcKvp0po0NgK:-NJ5AmXYDcKvp0po0NgL:bigoxes) ([raw file](https://github.com/starkware-libs/cairo/blob/7ee9ba5b435bad4ce4870a65401b67a10a5b477f/crates/sierra_generator/src/store_variables/test.rs#L116)):*
> ```XML
>             fallthrough: Some(1),
>         },
>         "branch_with_param" => LibFuncSignature {
> ```

Why not merge it with `branch`? Why do we need both?
(nonblocking)
___
*[`crates/sierra_generator/src/store_variables/test.rs` line 219 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1302#-NJ5B7ML7c5LGp-KTHx3:-NJ5B7ML7c5LGp-KTHx4:b-qu0j7m) ([raw file](https://github.com/starkware-libs/cairo/blob/7ee9ba5b435bad4ce4870a65401b67a10a5b477f/crates/sierra_generator/src/store_variables/test.rs#L219)):*
> ```XML
>         dummy_simple_statement(&db, "felt_add", &["0", "1"], &["2"]),
>         dummy_simple_branch(&db, "branch_with_param", &["2"], 0),
>         dummy_return_statement(&[]),
> ```

You can remove this line.

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1302#-:-NJ5BCQC2jjuyGr4nx75:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi and @yuvalsw)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1302)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @yuvalsw)

___
*[`crates/sierra_generator/src/store_variables/test.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1302#-NJ5AmXYDcKvp0po0NgK:-NJ5E1fI6-_oE98rDSYo:b-k0sohp) ([raw file](https://github.com/starkware-libs/cairo/blob/7ee9ba5b435bad4ce4870a65401b67a10a5b477f/crates/sierra_generator/src/store_variables/test.rs#L116)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Why not merge it with `branch`? Why do we need both?
(nonblocking)
</blockquote></details>

because it expects params - i don't want to have the extra information for the irrelevant tests.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1302)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
