### PR TITLE
Add bool::then_some function

### PR DESCRIPTION
**Pull request by LucasLvy**
Converts a bool in an option

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4529)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4529)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @LucasLvy)

___
*[`corelib/src/lib.cairo` line 18 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4529#-NlObaCB7YubdkJ69k0e:-NlObaCC-3KCKu4pwfqT:busehmb) ([raw file](https://github.com/starkware-libs/cairo/blob/db19efa03ad8fa155e300b82c1107201c3592d0e/corelib/src/lib.cairo#L18)):*
> ```Cairo
> }
> 
> impl BoolSerde of Serde<bool> {
> ```

Don't move now any of the existing impls, just create the new one in the new file.

**Comment by LucasLvy** [comment]
should be good now

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4529)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @LucasLvy)

___
*[`corelib/src/boolean.cairo` line 2 at r8](https://reviewable.io/reviews/starkware-libs/cairo/4529#-NlS6Px_E978um_U7iYc:-NlS6PxaAPfCEvzyfH0t:bn4be5b) ([raw file](https://github.com/starkware-libs/cairo/blob/6410403d751ccfd16b1c292540c0946467e47356/corelib/src/boolean.cairo#L2)):*
> ```Cairo
> #[generate_trait]
> pub impl ThenSome<T, +Drop<T>> of ThenSomeTrait<T> {
> ```

no reason the next added functions won't be added here.



_Suggestion:_
```Cairo
pub impl BoolImpl<T, +Drop<T>> of BoolTrait<T> {
```
___
*[`corelib/src/lib.cairo` line 101 at r8](https://reviewable.io/reviews/starkware-libs/cairo/4529#-NlS6ZgO99nhB6AXSAUe:-NlS6ZgO99nhB6AXSAUf:b-hfpv23) ([raw file](https://github.com/starkware-libs/cairo/blob/6410403d751ccfd16b1c292540c0946467e47356/corelib/src/lib.cairo#L101)):*
> ```Cairo
> }
> pub mod boolean;
> use boolean::ThenSome;
> ```

remove.



_Code quote:_
```Cairo
use boolean::ThenSome;
```

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4529#-:-Nm4e__P1-cESly5fIxR:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @LucasLvy)

**Review by orizi — COMMENTED** [review]
> Reviewed 10 of 11 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4529)* status: 11 of 12 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r9, 11 of 11 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4529#-:-Nnr-tTW5Buu9n7CdQ56:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @LucasLvy)

**Pull request merged**
