### PR TITLE
Handle unknown statement attributes.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4385)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4385)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4385#-Niod5bv1t2dDcbbFipu:-Niod5bv1t2dDcbbFipv:b-lefas8) (no related file):*
Change target branch.

___

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4385)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-defs/src/db.rs` line 194 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4385#-NipOMmN-q3R4Nw19_qX:-NipOMmN-q3R4Nw19_qY:b-u65415) ([raw file](https://github.com/starkware-libs/cairo/blob/b1d10cbf778a9d8cee22930dd8c88229ea516851/crates/cairo-lang-defs/src/db.rs#L194)):*
> ```XML
> fn allowed_statement_attributes(_db: &dyn DefsGroup) -> Arc<OrderedHashSet<String>> {
>     let all_attributes = OrderedHashSet::from_iter(["cairofmt::skip".into()]);
>     // TODO: Add the attributes from the plugins.
> ```

assign TODO.
or drop it - as no plugin currently even knows how to look at statements.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2154 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4385#-NipOkc6-2-tuxOsYOG6:-NipOkc6-2-tuxOsYOG7:b-mytre3) ([raw file](https://github.com/starkware-libs/cairo/blob/b1d10cbf778a9d8cee22930dd8c88229ea516851/crates/cairo-lang-semantic/src/expr/compute.rs#L2154)):*
> ```XML
>     ctx: &mut ComputationContext<'_>,
>     syntax: &ast::Statement,
> ) -> Maybe<()> {
> ```

this function can't seem to actually fail.
remove err option if so.



_Code quote:_
```XML
Maybe<()>
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4385)* status: 0 of 24 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-defs/src/db.rs` line 194 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4385#-NipOMmN-q3R4Nw19_qX:-Nj1mj4JEUxxoCPHjvbq:b4gbj46) ([raw file](https://github.com/starkware-libs/cairo/blob/b1d10cbf778a9d8cee22930dd8c88229ea516851/crates/cairo-lang-defs/src/db.rs#L194)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

assign TODO.
or drop it - as no plugin currently even knows how to look at statements.
</blockquote></details>

Done.
Added it knowing i'll do it in the next pr so haven't even noticed it.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2154 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4385#-NipOkc6-2-tuxOsYOG6:-Nj1mh3SEff0KXIB4mwQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b1d10cbf778a9d8cee22930dd8c88229ea516851/crates/cairo-lang-semantic/src/expr/compute.rs#L2154)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this function can't seem to actually fail.
remove err option if so.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r3, 21 of 21 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4385)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-defs/src/db.rs` line 179 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4385#-Nj7sPr8C2qvngqqIsj4:-Nj7sPr8C2qvngqqIsj5:b-jkgmyi) ([raw file](https://github.com/starkware-libs/cairo/blob/873b3e987616c48e8c0cb97ac13188c05a2f3d94/crates/cairo-lang-defs/src/db.rs#L179)):*
> ```XML
> }
> 
> pub const FMT_SKIP_ATTR: &str = "cairofmt::skip";
> ```

I really don't like it here.

Ideas for a better shared place?



_Code quote:_
```XML
pub const FMT_SKIP_ATTR: &str = "cairofmt::skip";
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4385)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-defs/src/db.rs` line 179 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4385#-Nj7sPr8C2qvngqqIsj4:-NjMWOeT6vdGT8Y9XFxk:bi7xasn) ([raw file](https://github.com/starkware-libs/cairo/blob/873b3e987616c48e8c0cb97ac13188c05a2f3d94/crates/cairo-lang-defs/src/db.rs#L179)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I really don't like it here.

Ideas for a better shared place?
</blockquote></details>

Maybe cairo-lang-defs/plugin.rs?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4385)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-defs/src/db.rs` line 179 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4385#-Nj7sPr8C2qvngqqIsj4:-NjMcdgg30pAjV4fBsIc:bbt4jo4) ([raw file](https://github.com/starkware-libs/cairo/blob/873b3e987616c48e8c0cb97ac13188c05a2f3d94/crates/cairo-lang-defs/src/db.rs#L179)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Maybe cairo-lang-defs/plugin.rs?
</blockquote></details>

it isn't a plugin - so this doesn't make sense.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4385)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-defs/src/db.rs` line 179 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4385#-Nj7sPr8C2qvngqqIsj4:-NjMuTUE82Mr6KlhVYKD:b550668) ([raw file](https://github.com/starkware-libs/cairo/blob/873b3e987616c48e8c0cb97ac13188c05a2f3d94/crates/cairo-lang-defs/src/db.rs#L179)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it isn't a plugin - so this doesn't make sense.
</blockquote></details>

So either in the formatter or just no const?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4385)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-defs/src/db.rs` line 179 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4385#-Nj7sPr8C2qvngqqIsj4:-NjN-zxdDsfQUzPOL2ga:b-3g8ght) ([raw file](https://github.com/starkware-libs/cairo/blob/873b3e987616c48e8c0cb97ac13188c05a2f3d94/crates/cairo-lang-defs/src/db.rs#L179)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

So either in the formatter or just no const?
</blockquote></details>

hmm - maybe just add it in a `constants.rs` file in the `defs` crate.
we can also move all the other constants here to there.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4385)* status: 23 of 26 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-defs/src/db.rs` line 179 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4385#-Nj7sPr8C2qvngqqIsj4:-NjN1Ti1EFbRTtlE1TbS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/873b3e987616c48e8c0cb97ac13188c05a2f3d94/crates/cairo-lang-defs/src/db.rs#L179)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

hmm - maybe just add it in a `constants.rs` file in the `defs` crate.
we can also move all the other constants here to there.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4385#-:-NjN3HT462AGQfFJmDT1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4385)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
