### PR TITLE
Enable return_optimization.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4758)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4758)* status: 0 of 51 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 375 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4758#-Nn_6_EZ1T2vQo_uHW76:-Nn_6_EZ1T2vQo_uHW77:b-nmbk00) ([raw file](https://github.com/starkware-libs/cairo/blob/443aadd573012d7d8c5d119368d6a7b59f5b6a02/crates/cairo-lang-lowering/src/db.rs#L375)):*
> ```XML
>     add_withdraw_gas(db, function, &mut lowered)?;
>     lowered = lower_panics(db, function, &lowered)?;
>     return_optimization(db, &mut lowered);
> ```

Putting it here helped eliminate the extra code due to panic handling.

Adding another call later didn't improve the code.



_Code quote:_
```XML
    lowered = lower_panics(db, function, &lowered)?;
    return_optimization(db, &mut lowered);
```

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4758)* status: 0 of 51 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 375 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4758#-Nn_6_EZ1T2vQo_uHW76:-Nn_ZeC75qNKf60DqluU:bb02alb) ([raw file](https://github.com/starkware-libs/cairo/blob/443aadd573012d7d8c5d119368d6a7b59f5b6a02/crates/cairo-lang-lowering/src/db.rs#L375)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Putting it here helped eliminate the extra code due to panic handling.

Adding another call later didn't improve the code.
</blockquote></details>

what would happen with an additional call before the panic handling?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/db.rs` line 375 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4758#-Nn_6_EZ1T2vQo_uHW76:-NnbkRI77-aHgh2Hw0YT:b-uci44p) ([raw file](https://github.com/starkware-libs/cairo/blob/443aadd573012d7d8c5d119368d6a7b59f5b6a02/crates/cairo-lang-lowering/src/db.rs#L375)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

what would happen with an additional call before the panic handling?
</blockquote></details>

didn't do anything, why do you think it should?

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 51 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4758)* status: 7 of 52 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 375 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4758#-Nn_6_EZ1T2vQo_uHW76:-NncxTGD5UGI06dixgla:b-cxvhno) ([raw file](https://github.com/starkware-libs/cairo/blob/443aadd573012d7d8c5d119368d6a7b59f5b6a02/crates/cairo-lang-lowering/src/db.rs#L375)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

didn't do anything, why do you think it should?
</blockquote></details>

I was wondering if it would make some error propagation mre efficient.
___
*[`crates/cairo-lang-lowering/src/test.rs` line 160 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4758#-NncxdV83KjxPyJtO4LT:-NncxdV97VBAH4hyn9bG:byp6rt5) ([raw file](https://github.com/starkware-libs/cairo/blob/05a0da7bae1a180aeb4f567b137df91ba1029608/crates/cairo-lang-lowering/src/test.rs#L160)):*
> ```XML
>     apply_stage("after_optimize_remappings2", &optimize_remappings);
>     apply_stage("after_reorder_statements3", &|lowered| reorder_statements(&db, lowered));
> ```

Revert

**Review by orizi — COMMENTED** [review]
> Reviewed 24 of 51 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4758)* status: 31 of 52 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 12 of 51 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4758)* status: 43 of 52 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 8 of 51 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4758)* status: 51 of 52 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4758)* status: 50 of 52 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/test.rs` line 160 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4758#-NncxdV83KjxPyJtO4LT:-Nnd1y7ODRqs0BeIa68U:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/05a0da7bae1a180aeb4f567b137df91ba1029608/crates/cairo-lang-lowering/src/test.rs#L160)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Revert
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4758)* status: 50 of 52 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/test_data/test_syscalls.json` line  at r2](https://reviewable.io/reviews/starkware-libs/cairo/4758#-Nnd-pWO1zQJ3gWy8fYX:-Nnd24UEA9v2V9XfxsJV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/05a0da7bae1a180aeb4f567b137df91ba1029608/crates/cairo-lang-starknet/test_data/test_syscalls.json#L)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

What is this file?
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4758#-:-Nnd3Voz-rcbG4S_3tt6:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
