### PR TITLE
add verify diagnostics expectation to lowering test

### PR DESCRIPTION
**Pull request by dean-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6385)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6385)* status: 1 of 30 files reviewed, 1 unresolved discussion (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-lowering/src/test_data/arm_pattern_destructure` line 392 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6385#-O6zqnFH1a42welyQnwF:-O6zqnFH1a42welyQnwG:b-3fmmep) ([raw file](https://github.com/starkware-libs/cairo/blob/09468650514ff5b2797f91b17ce2396eaec4d9b2/crates/cairo-lang-lowering/src/test_data/arm_pattern_destructure#L392)):*
> ```
> 
> //! > test_runner_name
> test_function_lowering(expect_diagnostics: true)
> ```

this doesn't seem correct.



_Code quote:_
```
//! > test_runner_name
test_function_lowering(expect_diagnostics: true)
```

**Review by dean-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6385)* status: 1 of 31 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/test_data/arm_pattern_destructure` line 392 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6385#-O6zqnFH1a42welyQnwF:-O739WdDBzYnj9g5iFcI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/09468650514ff5b2797f91b17ce2396eaec4d9b2/crates/cairo-lang-lowering/src/test_data/arm_pattern_destructure#L392)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this doesn't seem correct.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 29 of 29 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6385#-:-O73SGeY53wUU3XrAaQd:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by dean-starkware — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6385#-:-O73nLVODiPFeQ00O-F2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
