### PR TITLE
feat: expose deserialize version id from sierra program

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5977)

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5977)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/cairo-lang-starknet-classes/src/contract_class.rs` line 126 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5977#-O1IyHN61HeOojpbw1gi:-O1IyHN61HeOojpbw1gj:b-gqvjst) ([raw file](https://github.com/starkware-libs/cairo/blob/7e00c2c55cb3aecbad21eae0246f3015dcf35760/crates/cairo-lang-starknet-classes/src/contract_class.rs#L126)):*
> ```XML
> }
> 
> /// Deserializes the Version ids from a given Sierra program.
> ```

you are given the sierra program as felts stream - make the doc , function name (and possibly the param name) reflect that.
___
*[`crates/cairo-lang-starknet-classes/src/felt252_serde.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5977#-O1Iy9eF90mNooSVk7ZF:-O1Iy9eF90mNooSVk7ZG:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/7e00c2c55cb3aecbad21eae0246f3015dcf35760/crates/cairo-lang-starknet-classes/src/felt252_serde.rs#L84)):*
> ```XML
> }
> 
> pub fn sierra_version_id_from_felts(
> ```

doc

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5977)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet-classes/src/contract_class.rs` line 126 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5977#-O1IyHN61HeOojpbw1gi:-O1LTwUWCBiU9AG3WHeI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7e00c2c55cb3aecbad21eae0246f3015dcf35760/crates/cairo-lang-starknet-classes/src/contract_class.rs#L126)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you are given the sierra program as felts stream - make the doc , function name (and possibly the param name) reflect that.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet-classes/src/felt252_serde.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5977#-O1Iy9eF90mNooSVk7ZF:-O1LTLk68g4uPSkd8u2-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7e00c2c55cb3aecbad21eae0246f3015dcf35760/crates/cairo-lang-starknet-classes/src/felt252_serde.rs#L84)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5977)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5977#-O1Lj_EX68m6OgO9WYTw:-O1Lj_EX68m6OgO9WYTx:b-w09ti) (no related file):*
do you need this for the next release? if so - make target branch `dev-v2.7.0`.

___

**Comment by ArniStarkware** [comment]
*[`crates/cairo-lang-starknet-classes/src/contract_class.rs` line 126 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5977#-O1Lb88o3Evvz7zjM-KS:-O1LirU20vmuWpRfM75l:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7eec3c6910232dfd5e88587dfc11ad8d284f31cb/crates/cairo-lang-starknet-classes/src/contract_class.rs#L126)):*
> ```XML
> }
> 
> /// Deserializes a Sierra program from a slice of felt252s.
> ```

Done.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5977)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5977#-O1Lj_EX68m6OgO9WYTw:-O1LpKZsDpXkRaMPQ6bc:b-4izkyp) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

do you need this for the next release? if so - make target branch `dev-v2.7.0`.
</blockquote></details>

Done.

Thank you!

___

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5977#-:-O1LtWo45XE5ifX7ah_o:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
