### PR TITLE
Cache node children.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4247)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-syntax/src/node/mod.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4247#-NgTz-OQ8yJM0JsSbNbz:-NgTz-OQ8yJM0JsSbNc-:bhpmizk) ([raw file](https://github.com/starkware-libs/cairo/blob/9fab18dcc15506642e040065a37abefbb1bb657c/crates/cairo-lang-syntax/src/node/mod.rs#L86)):*
> ```XML
>         TextSpan { start, end }
>     }
>     pub fn children<'db>(&self, db: &'db dyn SyntaxGroup) -> SyntaxNodeChildIterator<'db> {
> ```

I've tried removing this function in a single PR.
If you think this PR is too large I can split it.



_Code quote:_
```XML
 pub fn children<'db>(&self, db: &'db dyn SyntaxGroup) -> SyntaxNodeChildIterator<'db>
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4247)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-syntax/src/node/db.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4247#-NgU3w_o9u2Od4xKurfU:-NgU3w_p4DZzVVei3Etf:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/5b76235dac23bb42e9a7eb51e9e99bf4c2457b60/crates/cairo-lang-syntax/src/node/db.rs#L20)):*
> ```XML
>     fn intern_stable_ptr(&self, field: SyntaxStablePtr) -> SyntaxStablePtrId;
> 
>     fn get_children(&self, node: SyntaxNode) -> Arc<Vec<SyntaxNode>>;
> ```

doc

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4247)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-syntax/src/node/db.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4247#-NgU3w_o9u2Od4xKurfU:-NgXPH8a3wWVCwMt8IAj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5b76235dac23bb42e9a7eb51e9e99bf4c2457b60/crates/cairo-lang-syntax/src/node/db.rs#L20)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4247)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-syntax/src/node/db.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4247#-NgU3w_o9u2Od4xKurfU:-NgXUxXn29AtjGiqi-cj:b-76b6bc) ([raw file](https://github.com/starkware-libs/cairo/blob/5b76235dac23bb42e9a7eb51e9e99bf4c2457b60/crates/cairo-lang-syntax/src/node/db.rs#L20)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Three ///

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4247)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-syntax/src/node/db.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4247#-NgU3w_o9u2Od4xKurfU:-NgXWWHBESUeT6M6i62O:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5b76235dac23bb42e9a7eb51e9e99bf4c2457b60/crates/cairo-lang-syntax/src/node/db.rs#L20)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Three ///
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4247#-:-NgXaBx20pdJrUsSc6xy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
