### PR TITLE
Add storage_node.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
**Stack**:
- #5586
- #5585
- #5534 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5534)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5534)* status: 3 of 7 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`corelib/src/starknet/storage.cairo` line 175 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5534#-NxSuZZQ8RnNdHnWoC8P:-NxSuZZQ8RnNdHnWoC8Q:b-ay9n31) ([raw file](https://github.com/starkware-libs/cairo/blob/b86e467738b5052c7c67af62ff65cf1a665b0a63/corelib/src/starknet/storage.cairo#L175)):*
> ```Cairo
>     type NodeType;
>     fn storage_node(self: StoragePath<T>) -> Self::NodeType;
> }
> ```

add endline.
___
*[`crates/cairo-lang-starknet/src/plugin/storage.rs` line 363 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5534#-NxSv6wgCdTOjpBGWJnG:-NxSv6wgCdTOjpBGWJnH:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/b86e467738b5052c7c67af62ff65cf1a665b0a63/crates/cairo-lang-starknet/src/plugin/storage.rs#L363)):*
> ```XML
> }
> 
> fn get_substorage_member_code(
> ```

doc
___
*[`crates/cairo-lang-starknet/src/plugin/storage_node.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5534#-NxSvE1F5AcCTGbg3A0t:-NxSvE1F5AcCTGbg3A0u:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/b86e467738b5052c7c67af62ff65cf1a665b0a63/crates/cairo-lang-starknet/src/plugin/storage_node.rs#L121)):*
> ```XML
> 
>     // let struct_name = struct_ast.name(db).text(db);
>     // let struct_fields = struct_ast.members(db).elements(db);
> ```

.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5534)* status: 2 of 8 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/storage.rs` line 363 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5534#-NxSv6wgCdTOjpBGWJnG:-Nxfr-Pg0_1EVsZOMG-s:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/966f630e5f193b76996ed20f0338e402dc61247f/crates/cairo-lang-starknet/src/plugin/storage.rs#L363)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/storage_node.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5534#-NxSvE1F5AcCTGbg3A0t:-Nxfr-e80cwYZDRBqKB8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/966f630e5f193b76996ed20f0338e402dc61247f/crates/cairo-lang-starknet/src/plugin/storage_node.rs#L121)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5534)* status: 2 of 8 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/starknet/storage.cairo` line 175 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5534#-NxSuZZQ8RnNdHnWoC8P:-Nxfr6Mx94Wq7dkrXSyi:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/966f630e5f193b76996ed20f0338e402dc61247f/corelib/src/starknet/storage.cairo#L175)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add endline.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5534)* status: 4 of 8 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin/storage_node.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5534#-NxfqvRX85lbA42cB2c9:-NxfqvRY-7JyI7zVgB1f:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/046ff510a08d899b86630d8b801910b567a05e2b/crates/cairo-lang-starknet/src/plugin/storage_node.rs#L36)):*
> ```XML
> ///     fn storage_node(self: StoragePath<BalancePair>) -> BalancePairStorageNode {
> ///         // Should be somehow lazy constructed, i.e. the hash_state should be updated only when
> ///         // the inner fields are accessed. Can be done if we revert to methods (i.e.`.balance1()`).         
> ```

.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_component_diagnostics` line 1052 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5534#-NxfrPfSEbjSkPWz2scI:-NxfrPfSEbjSkPWz2scJ:bp4g7ic) ([raw file](https://github.com/starkware-libs/cairo/blob/046ff510a08d899b86630d8b801910b567a05e2b/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_component_diagnostics#L1052)):*
> ```
>         non_component: usize,
>         // non-v0 substorage member.
>         #[substorage(v1)]
> ```

we assumed this would just be totally removed instead - right?



_Code quote:_
```
        #[substorage(v1)]
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5534)* status: 4 of 8 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/storage_node.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5534#-NxfqvRX85lbA42cB2c9:-NxfsnKZ0UKEw3rSxOzi:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/046ff510a08d899b86630d8b801910b567a05e2b/crates/cairo-lang-starknet/src/plugin/storage_node.rs#L36)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_component_diagnostics` line 1052 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5534#-NxfrPfSEbjSkPWz2scI:-Nxfso8j3y8MJQ0JVP4x:bhfv6r5) ([raw file](https://github.com/starkware-libs/cairo/blob/046ff510a08d899b86630d8b801910b567a05e2b/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_component_diagnostics#L1052)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

we assumed this would just be totally removed instead - right?
</blockquote></details>

Maybe after deref

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5534)* status: 4 of 8 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/new_storage_interface` line 43 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5534#-Nxg0yCkDgWbl2PNy3ni:-Nxg0yCkDgWbl2PNy3nj:bixnas9) ([raw file](https://github.com/starkware-libs/cairo/blob/62ba0fc43c72977fa9790c15e82af395caa50ebe/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/new_storage_interface#L43)):*
> ```
>         // TODO(Gil): Decide on the attribute name.
>         #[substorage]
>         balance_pair: BalancePair,
> ```

no need of substorage trait.
for now would just require the extra `deref()` call.



_Code quote:_
```
        // TODO(Gil): Decide on the attribute name.
        #[substorage]
        balance_pair: BalancePair,
```
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_component_diagnostics` line 1052 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5534#-NxfrPfSEbjSkPWz2scI:-Nxg1HFOA5ZTUMdEbRHk:bon4ss9) ([raw file](https://github.com/starkware-libs/cairo/blob/046ff510a08d899b86630d8b801910b567a05e2b/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_component_diagnostics#L1052)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Maybe after deref
</blockquote></details>

i don't see why - just have a longer syntax still.
add an explicit additional function for accessing this.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 20 of 24 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5534)* status: 22 of 29 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware)

___
*[`corelib/src/starknet/storage_access.cairo` line 60 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5534#-Ny0jhrI40zX6gXuKeNt:-Ny0jhrI40zX6gXuKeNu:b-86fyuv) ([raw file](https://github.com/starkware-libs/cairo/blob/b82036996f1dbb4d04440f2964d4957bcf277fb7/corelib/src/starknet/storage_access.cairo#L60)):*
> ```Cairo
> }
> 
> #[inline(always)]
> ```

Into.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 26 files at r4, 1 of 24 files at r5, 3 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5534)* status: 26 of 29 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin/storage_node.rs` line 15 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5534#-Ny1QZlw5etOR5faGxM6:-Ny1QZlw5etOR5faGxM7:bcf6ee3) ([raw file](https://github.com/starkware-libs/cairo/blob/16549e3deec133903abcf7a9a1ebfd9fdedcf023/crates/cairo-lang-starknet/src/plugin/storage_node.rs#L15)):*
> ```XML
> #[non_exhaustive]
> /// Generates a trait and impl of updating a storage path of a struct to access each of its members
> /// (i.e. there will be a function for each member of the struct).
> ```

Doc should be above the attrs.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5534)* status: 23 of 29 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/storage_node.rs` line 15 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5534#-Ny1QZlw5etOR5faGxM6:-NyEdoI08f8fRFp3eTeR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/16549e3deec133903abcf7a9a1ebfd9fdedcf023/crates/cairo-lang-starknet/src/plugin/storage_node.rs#L15)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Doc should be above the attrs.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/new_storage_interface` line 43 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5534#-Nxg0yCkDgWbl2PNy3ni:-Ny0eJnX7AuEHHeBLcgh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/62ba0fc43c72977fa9790c15e82af395caa50ebe/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/new_storage_interface#L43)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no need of substorage trait.
for now would just require the extra `deref()` call.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_component_diagnostics` line 1052 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5534#-NxfrPfSEbjSkPWz2scI:-Ny0eIjgE56VpI8byuG8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/046ff510a08d899b86630d8b801910b567a05e2b/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_component_diagnostics#L1052)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i don't see why - just have a longer syntax still.
add an explicit additional function for accessing this.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r7, 2 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5534)* status: 26 of 29 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_component_diagnostics` line 1052 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5534#-NxfrPfSEbjSkPWz2scI:-NyElTSZ3DFdhx41oqeE:b21f6l4) ([raw file](https://github.com/starkware-libs/cairo/blob/046ff510a08d899b86630d8b801910b567a05e2b/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_component_diagnostics#L1052)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

no it isn't.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5534)* status: 26 of 29 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_component_diagnostics` line 1052 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5534#-NxfrPfSEbjSkPWz2scI:-NyEvgrN1jOkidJzBYb6:bwvyox4) ([raw file](https://github.com/starkware-libs/cairo/blob/046ff510a08d899b86630d8b801910b567a05e2b/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_component_diagnostics#L1052)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no it isn't.
</blockquote></details>

Reverted

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5534#-:-NyFLl6DEPC6a9dyQ9mK:bnfp4nl)* status: 27 of 29 files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5534)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
