### PR TITLE
Added assert_eq! test macro.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #4361
- #4359
- #4358 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4358)

### CODE REVIEW

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 31 of 32 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4358)* status: 31 of 32 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/test/byte_array_test.cairo` line 390 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4358#-NiYgeYJ--yNgvbuB-YZ:-NiYgeYJ--yNgvbuB-Y_:b8fuq5l) ([raw file](https://github.com/starkware-libs/cairo/blob/d959a12f9e13b37ea775ba70dcc46b8899d66a38/corelib/src/test/byte_array_test.cairo#L390)):*
> ```Cairo
>     assert_ne(@ba_rev, @ba_rev.rev(), 'ba_rev == ba_rev.rev()');
>     assert_eq!(ba, ba_rev.rev());
>     assert_eq!(palindrome.rev(), palindrome);
> ```

Not that it matter much, but why the order is flipped?



_Code quote:_
```Cairo
(palindrome.rev(), palindrome
```
___
*[`corelib/src/test/testing_test.cairo` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4358#-NiYtgy55rURNz2_2pX1:-NiYtgy55rURNz2_2pX2:b-i2q3qp) ([raw file](https://github.com/starkware-libs/cairo/blob/d959a12f9e13b37ea775ba70dcc46b8899d66a38/corelib/src/test/testing_test.cairo#L35)):*
> ```Cairo
> fn test_assert_eq_no_description() {
>     assert_eq!(1, 2);
> }
> ```

Please add something like:
```
assert_eq!(1, 2, "{}!={}", 1, 2);
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4358)* status: 31 of 32 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 170 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4358#-NiYvik47YVf9KzEj9lD:-NiYvik47YVf9KzEj9lE:b-nytedx) ([raw file](https://github.com/starkware-libs/cairo/blob/d959a12f9e13b37ea775ba70dcc46b8899d66a38/crates/cairo-lang-test-plugin/src/lib.rs#L170)):*
> ```XML
>     suite
>         .add_plugin::<TestPlugin>()
>         .add_inline_macro_plugin::<inline_macros::assert_eq::AssertEqMacro>();
> ```

It may be confusing that `assert_eq` is only for testing while `assert` is in the base suite.



_Code quote:_
```XML
.add_inline_macro_plugin::<inline_macros::assert_eq::AssertEqMacro>();
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4358)* status: 31 of 32 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`corelib/src/test/byte_array_test.cairo` line 390 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4358#-NiYgeYJ--yNgvbuB-YZ:-NiYwI5r6poECJijnyd_:b-xtcqo3) ([raw file](https://github.com/starkware-libs/cairo/blob/d959a12f9e13b37ea775ba70dcc46b8899d66a38/corelib/src/test/byte_array_test.cairo#L390)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Not that it matter much, but why the order is flipped?
</blockquote></details>

oh - fixed the base issue - can revert this.
___
*[`corelib/src/test/testing_test.cairo` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4358#-NiYtgy55rURNz2_2pX1:-NiYxBt_CUn2SSaWCYGd:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d959a12f9e13b37ea775ba70dcc46b8899d66a38/corelib/src/test/testing_test.cairo#L35)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Please add something like:
```
assert_eq!(1, 2, "{}!={}", 1, 2);
```
</blockquote></details>

Done.
___
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 170 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4358#-NiYvik47YVf9KzEj9lD:-NiYxDhR8_AgxG7T4_Tq:b-bl8c8z) ([raw file](https://github.com/starkware-libs/cairo/blob/d959a12f9e13b37ea775ba70dcc46b8899d66a38/crates/cairo-lang-test-plugin/src/lib.rs#L170)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

It may be confusing that `assert_eq` is only for testing while `assert` is in the base suite.
</blockquote></details>

we can move it later - but for now, rather not have user code rely on the actual provided value of the assert_eq assertion.
assert is much more simple string wise.

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 1 of 32 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4358)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4358#-:-NiZ-KPhBIMcvpCVULcD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
