### PR TITLE
Removed extra var from push duplications.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:a8f0d122

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
LGTM, but please wait for another LGTM from someone more familiar with this parts.

> Reviewed 44 of 47 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2052#-:-NNkEaXj4WJkpqIxdb6Y:b-r29rjh)* status: all files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware, @liorgold2, and @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/block_generator.rs` line 317 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2052#-NNk76rx18H3T8lB9k2m:-NNk76rx18H3T8lB9k2n:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/087877cc87c5fe8583adb3bb7c137347158ca7cf/crates/cairo-lang-sierra-generator/src/block_generator.rs#L317)):*
> ```XML
> }
> 
> /// Returns if the variable at the given location should not be duplicated.
> ```





_Suggestion:_
```XML
should 
```
___
*[`crates/cairo-lang-sierra-generator/src/test_utils.rs` line 196 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2052#-NNk7hgG-zGRF5PNhBmW:-NNk7hgG-zGRF5PNhBmX:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/087877cc87c5fe8583adb3bb7c137347158ca7cf/crates/cairo-lang-sierra-generator/src/test_utils.rs#L196)):*
> ```XML
> }
> 
> /// Same as [dummy_push_values] except that it also accepts value for `dup_var`.
> ```





_Suggestion:_
```XML
accepts a value for `dup`
```
___
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 253 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2052#-NNk8gSR5gNg9tnHuOYb:-NNk8gSR5gNg9tnHuOYc:b-3qnc53) ([raw file](https://github.com/starkware-libs/cairo/blob/087877cc87c5fe8583adb3bb7c137347158ca7cf/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L253)):*
> ```XML
> 
>     /// Adds a store_temp() or store_local() instruction for the given deferred variable after is
>     /// was already removed from the `deferred_variables` map.
> ```

suggestion



_Suggestion:_
```XML
    /// Adds a store_temp() or store_local() instruction for the given deferred variable assuming that it
    /// was already removed from the `deferred_variables` map.
```
___
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 296 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2052#-NNkAqQe1bvIbhLkmrAj:-NNkAqQe1bvIbhLkmrAk:b-m7j0gs) ([raw file](https://github.com/starkware-libs/cairo/blob/087877cc87c5fe8583adb3bb7c137347158ca7cf/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L296)):*
> ```XML
>                     if self.store_deferred_ex(var, var_on_stack, deferred_info) {
>                         if *dup {
>                             self.dup(var_on_stack, var, ty);
> ```

should it be: ?
if not - please explain. If yes - I think returning true here does the same and is a bit clearer.



_Suggestion:_
```XML
self.dup(var, var_on_stack, ty);
```
___
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 413 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2052#-NNkC3Sg9iMZ70wOJmXi:-NNkByUY-26TNy2SaSB5:b-drdclh) ([raw file](https://github.com/starkware-libs/cairo/blob/087877cc87c5fe8583adb3bb7c137347158ca7cf/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L413)):*
> ```XML
>     }
> 
>     fn store_local(
> ```

taxing: please add documentation to store_temp, store_local

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 47 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2052)* status: all files reviewed, 6 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/pre_sierra.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2052#-NNkF3oF15iYjtkXjP7P:-NNkF3oF15iYjtkXjP7Q:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/087877cc87c5fe8583adb3bb7c137347158ca7cf/crates/cairo-lang-sierra-generator/src/pre_sierra.rs#L92)):*
> ```XML
>     /// The type of the variable.
>     pub ty: ConcreteTypeId,
>     /// Indicates whether the variable should be duplicated before pushing it.
> ```





_Suggestion:_
```XML
 it is pushed.
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 14 of 47 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2052)* status: 44 of 48 files reviewed, 4 unresolved discussions (waiting on @liorgold2, @orizi, and @yuvalsw)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 314 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2052#-NNkIkhY4oqoW44xTVtL:-NNkIkhY4oqoW44xTVtM:bsur5gx) ([raw file](https://github.com/starkware-libs/cairo/blob/087877cc87c5fe8583adb3bb7c137347158ca7cf/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L314)):*
> ```XML
>                     self.rename_var(var, var_on_stack, ty);
>                 }
>             } else {
> ```

!should_rename => store temp is needed?

Maybe we should rename it?



_Code quote:_
```XML
} else {
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2052)* status: 44 of 48 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware, @liorgold2, and @yuvalsw)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 314 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2052#-NNkIkhY4oqoW44xTVtL:-NNkK4-45Qt5-SaiQ1sa:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/087877cc87c5fe8583adb3bb7c137347158ca7cf/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L314)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

!should_rename => store temp is needed?

Maybe we should rename it?

</blockquote></details>

Done.

**Review by yuvalsw — APPROVED** [review]
> Reviewed 3 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2052)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware, @liorgold2, and @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 253 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2052#-NNk8gSR5gNg9tnHuOYb:-NNkKc_T6BkdDTQjL20v:b-wytaht) ([raw file](https://github.com/starkware-libs/cairo/blob/087877cc87c5fe8583adb3bb7c137347158ca7cf/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L253)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it don't assume that - it would work anyway - it would just be a bad idea.
</blockquote></details>

So the documentation is still wrong. Maybe "Adds a store_temp() or store_local() instruction for the given deferred variable. Normally, it is done after the variable was already removed from the `deferred_variables` map."
Or s/Normally, it is/should be/

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2052)* status: all files reviewed, 3 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 268 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2052#-NNkNaBU6v0BtfHzMiIS:-NNkNaBU6v0BtfHzMiIT:bmtpvv0) ([raw file](https://github.com/starkware-libs/cairo/blob/f06377ed168782c8cb205d5d2f3203579f843474/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L268)):*
> ```XML
>         &mut self,
>         var: &sierra::ids::VarId,
>         var_on_stack: &sierra::ids::VarId,
> ```

why is var_on_stack relevent? for store_temp but not store_local?



_Code quote:_
```XML
  var_on_stack: &sierra::ids::VarId,
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 7 of 47 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2052)* status: all files reviewed, 3 unresolved discussions (waiting on @liorgold2 and @orizi)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 14 of 47 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2052)* status: all files reviewed, 3 unresolved discussions (waiting on @liorgold2 and @orizi)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 47 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2052)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2052)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @liorgold2)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 268 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2052#-NNkNaBU6v0BtfHzMiIS:-NNkNm_e11HfyDfQbVr9:bldrcsa) ([raw file](https://github.com/starkware-libs/cairo/blob/f06377ed168782c8cb205d5d2f3203579f843474/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L268)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why is var_on_stack relevent? for store_temp but not store_local?
</blockquote></details>

because for store local there's no var on the push stack.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2052)* status: 47 of 48 files reviewed, 1 unresolved discussion (waiting on @liorgold2, @orizi, and @yuvalsw)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 268 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2052#-NNkNaBU6v0BtfHzMiIS:-NNkPywTBimlvQmzs14N:b-g24j56) ([raw file](https://github.com/starkware-libs/cairo/blob/f06377ed168782c8cb205d5d2f3203579f843474/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L268)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

because for store local there's no var on the push stack.
</blockquote></details>

I don't understand.

You could reaname
var -> dst
var_on_stack -> src.


why is it the case that 
for store_local you always have src=dst, but for store_temp they may differ?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2052)* status: 47 of 48 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware, @liorgold2, and @yuvalsw)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 268 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2052#-NNkNaBU6v0BtfHzMiIS:-NNkQLuv7hesIjcW2a8W:bsqbcgf) ([raw file](https://github.com/starkware-libs/cairo/blob/f06377ed168782c8cb205d5d2f3203579f843474/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L268)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't understand.

You could reaname
var -> dst
var_on_stack -> src.


why is it the case that 
for store_local you always have src=dst, but for store_temp they may differ?

</blockquote></details>

my aim is trying to write to a variable on stack - but if i store locally - i don't want to write to it.
so i don't want to use the stack variable in that case.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2052#-:-NNkbeJY1V5_L-VBWgeP:bnfp4nl)* status: 47 of 48 files reviewed, all discussions resolved (waiting on @liorgold2 and @yuvalsw)

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2052)* status: 47 of 48 files reviewed, all discussions resolved (waiting on @liorgold2 and @yuvalsw)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2052)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
