### PR TITLE
Fixed all new clippy warnings.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3964)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-parser/src/parser.rs` line 1275 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3964#-Ncq222b24x3yl601lQ-:-Ncq222b24x3yl601lQ0:btjyaai) ([raw file](https://github.com/starkware-libs/cairo/blob/9f44109a11c2c2f2a077dcedafdece47dbcd185b/crates/cairo-lang-parser/src/parser.rs#L1275)):*
> ```XML
>         }
> 
>         if matches!(self.peek().kind, rbrace!() | top_level!() | SyntaxKind::TerminalEndOfFile) {
> ```

what happend here?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3964)* status: 0 of 17 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1275 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3964#-Ncq222b24x3yl601lQ-:-Ncq32MP07ncrGDMKh-z:b-k1txfz) ([raw file](https://github.com/starkware-libs/cairo/blob/9f44109a11c2c2f2a077dcedafdece47dbcd185b/crates/cairo-lang-parser/src/parser.rs#L1275)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what happend here?
</blockquote></details>

new clippy asks to not create a closure and use it in the same line.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 486 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3964#-Ncq4G200GidHUOV5zVE:-Ncq4G200GidHUOV5zVF:bjvqngw) ([raw file](https://github.com/starkware-libs/cairo/blob/98af2f86dfd19a75a8ebe7870e4f69b57fdeb756/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L486)):*
> ```XML
>         if matches!(self.state_opt.as_mut(), None) {
>             return self.state_opt.as_mut().unwrap();
>         }
> ```

why was this here in the first place?



_Code quote:_
```XML
        if matches!(self.state_opt.as_mut(), None) {
            return self.state_opt.as_mut().unwrap();
        }
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3964)* status: 0 of 17 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/store_variables/mod.rs` line 486 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3964#-Ncq4G200GidHUOV5zVE:-Ncq4vBw7_PBROj7q3ER:b1k8f7c) ([raw file](https://github.com/starkware-libs/cairo/blob/98af2f86dfd19a75a8ebe7870e4f69b57fdeb756/crates/cairo-lang-sierra-generator/src/store_variables/mod.rs#L486)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why was this here in the first place?
</blockquote></details>

no idea - this is a minimal effort to remove the clippy warnings

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 13 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3964)* status: 13 of 17 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1275 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3964#-Ncq9EE0D1Cz0Dr5KO1-:-Ncq9EE0D1Cz0Dr5KO10:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9f44109a11c2c2f2a077dcedafdece47dbcd185b/crates/cairo-lang-parser/src/parser.rs#L1275)):*
> ```XML
>         }
> 
>         if matches!(self.peek().kind, rbrace!() | top_level!() | SyntaxKind::TerminalEndOfFile) {
> ```





_Suggestion:_
```XML
let is_rbrace_or_top_level = is_of_kind!(rbrace, top_level);
if is_rbrace_or_top_level(self.peek().kind) {
```

**Comment by ilyalesokhin-starkware** [comment]
Please fix my comment before merging.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3964#-:-Ncq9Y2Q5iXwXYo94PBy:bnfp4nl)* status: 13 of 17 files reviewed, 2 unresolved discussions (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3964)* status: 13 of 17 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1275 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3964#-Ncq9EE0D1Cz0Dr5KO1-:-NcqCngr23wFelw8pZCK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9f44109a11c2c2f2a077dcedafdece47dbcd185b/crates/cairo-lang-parser/src/parser.rs#L1275)):*
> ```XML
>         }
> 
>         if matches!(self.peek().kind, rbrace!() | top_level!() | SyntaxKind::TerminalEndOfFile) {
> ```

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 17 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3964)* status: 14 of 17 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3964)* status: 14 of 17 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Pull request merged**
