### PR TITLE
Change CallResult to hold VarUsage vectors.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3585)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3585)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 206 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3585#-NZUjb82-edBAu8uA3XM:-NZUjb82-edBAu8uA3XN:bqsp5tq) ([raw file](https://github.com/starkware-libs/cairo/blob/7228027c09d495365e86f6022a36e6d56e329453/crates/cairo-lang-lowering/src/lower/context.rs#L206)):*
> ```XML
>         let location = req.location;
> 
>         VarUsage { var_id: self.variables.new_var(req), location }
> ```

consider



_Suggestion:_
```XML
        VarUsage { var_id: self.variables.new_var(req), location: req.location }
```

**Review by orizi — CHANGES_REQUESTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3585#-:-NZUjit9C5o-IcMftd88:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 206 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3585#-NZUjb82-edBAu8uA3XM:-NZUlNCo-njxukLwpTYF:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/7228027c09d495365e86f6022a36e6d56e329453/crates/cairo-lang-lowering/src/lower/context.rs#L206)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

consider
</blockquote></details>





_Code snippet:_
```XML
206 |         VarUsage { var_id: self.variables.new_var(req), location: req.location }
    |                                                   ---             ^^^^^^^^^^^^ value used here after move
    |                                                   |
    |                                                   value moved here
```

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3585)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
