### PR TITLE
Feat/support empty variants

### PR DESCRIPTION
**Pull request by neotheprogramist**
Currently, when using an enum with an empty variant (e.g., A: ()), we are required to match arms with the empty parentheses included. For example:
```rust
enum MyEnum {
   A: (),
   B: usize
}

fn foo(e: MyEnum) {
   match e {
      A(_) => {...}, // Currently we need "A(_) => " or "A(()) => "
      B(x) => {...}
   }
}
```

It would be useful to allow for the removal of () from the enum variant itself. Currently, we need to write A: (),. I propose that we allow for simple declarations, like A,.
```rust
enum MyEnum {
   A, // Proposed syntax
   B: usize
}
```

I propose enhancing the match arm to allow matching without the parentheses, as shown below:
```rust
fn foo(e: MyEnum) {
   match e {
      A => {...}, // Proposed syntax
      B(x) => {...}
   }
}
```

This would lead to cleaner and more intuitive code.
This will enhance code readability and make it more straightforward to use enums with empty variants in Rust.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3569)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 19 files at r1, 19 of 45 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3569)* status: 23 of 55 files reviewed, 1 unresolved discussion (waiting on @neotheprogramist)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3569#-NZQcERj0PrWbKsfVbLc:-NZQcERj0PrWbKsfVbLd:b-ucu6za) (no related file):*
Can you please revert the unrelated format changes?
Would make it easier to check.
(If you want to improve the formatting, feel free to suggest in another PR, the changes does look good)

___

**Comment by neotheprogramist** [comment]
> > Reviewed 4 of 19 files at r1, 19 of 45 files at r3, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3569)_ status: 23 of 55 files reviewed, 1 unresolved discussion (waiting on @neotheprogramist)
> 
> _[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3569#-NZQcERj0PrWbKsfVbLc:-NZQcERj0PrWbKsfVbLd:b-ucu6za) (no related file):_ Can you please revert the unrelated format changes? Would make it easier to check. (If you want to improve the formatting, feel free to suggest in another PR, the changes does look good)

Done :)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 19 files at r1, 4 of 45 files at r3, 41 of 41 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3569)* status: all files reviewed, 2 unresolved discussions (waiting on @neotheprogramist)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 1358 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3569#-NZUVvL8EaDf5mdhz0RG:-NZUVvL8EaDf5mdhz0RH:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/587a820163120e1579d40c3f8ec9cb6a78c1a69e/crates/cairo-lang-parser/src/parser.rs#L1358)):*
> ```XML
>                                 OptionPatternEnumInnerPatternEmpty::new_green(self.db).into(),
>                             )
>                             .into(),
> ```





_Suggestion:_
```XML
                        // If the path has more than 1 element assume it's a simplified Enum variant
                        // Eg. MyEnum::A(()) ~ MyEnum::A
                        // Multi-element path identifiers aren't allowed, for now this mechanism is
                        // sufficient.
                        match children.len() {
                            // 0 => return None, - unreachable
                            1 => path.into(),
                            _ => PatternEnum::new_green(
                                self.db,
                                path,
                                OptionPatternEnumInnerPatternEmpty::new_green(self.db).into(),
                            )
                            .into(),
```
___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 157 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3569#-NZUX44AB0MgWqMF8k44:-NZUX44AB0MgWqMF8k45:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/587a820163120e1579d40c3f8ec9cb6a78c1a69e/crates/cairo-lang-starknet/src/plugin/events.rs#L157)):*
> ```XML
> }
> 
> fn get_field_enum_kind(
> ```

doc

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3569)* status: all files reviewed, 3 unresolved discussions (waiting on @neotheprogramist)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3569#-NZUXbrP8iWRbruXwP5k:-NZUXbrP8iWRbruXwP5l:bcmk7d9) (no related file):*
also - change usages of empty enums variants in the corelib so we'd see there are no changes.

___

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3569#-:-NZVOfTIADBwdOqhJLl3:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @neotheprogramist)

**Review by orizi — COMMENTED** [review]
waiting for @spapinistarkware to approve as well.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3569#-:-NZVOhelAXHk8Nib8i7M:b-403vnr)* status: all files reviewed, 1 unresolved discussion (waiting on @neotheprogramist)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3569)* status: 64 of 65 files reviewed, 1 unresolved discussion (waiting on @neotheprogramist)

___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 164 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3569#-NZVPrwO609A8crbwfN7:-NZVPrwO609A8crbwfN8:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6b9bbdad009259ca0c030af229049142c624ff69/crates/cairo-lang-starknet/src/plugin/events.rs#L164)):*
> ```XML
>     Retrieves the field kind for a given enum variant, indicating how the field should be serialized.
>     See [EventFieldKind].
> */
> ```





_Suggestion:_
```XML
/// Retrieves the field kind for a given struct member, indicating how the field should be serialized.
/// See [EventFieldKind].
fn get_field_kind_for_member(
    db: &dyn SyntaxGroup,
    diagnostics: &mut Vec<PluginDiagnostic>,
    member: &ast::Member,
    default
}

/// Retrieves the field kind for a given enum variant, indicating how the field should be serialized.
/// See [EventFieldKind].
```

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 19 files at r1, 4 of 45 files at r3, 36 of 41 files at r4, 5 of 12 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3569)* status: 14 of 74 files reviewed, 2 unresolved discussions (waiting on @neotheprogramist and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1050 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3569#-NZVQl_45kHk1Oo_IK9l:-NZVQl_45kHk1Oo_IK9m:b-ul2df1) ([raw file](https://github.com/starkware-libs/cairo/blob/66f0be4259a227c6bd5a5a51af83ef2dc3bb1b45/crates/cairo-lang-semantic/src/expr/compute.rs#L1050)):*
> ```XML
>                         key_fields: vec![],
>                         index: 0,
>                     })),
> ```

This is a problem, since you are generating a stable pointer for a non existing syntax element. When the LSP will try to fetch it, it will panic.
We have an invariatn today that all stable pointers are real.
I suggest making inner_pattern inside Pattern::EnumVariant an Option.



_Code quote:_
```XML
                    stable_ptr: PatternTuplePtr(ctx.db.intern_stable_ptr(SyntaxStablePtr::Child {
                        parent: enum_pattern.stable_ptr().0,
                        kind: SyntaxKind::PatternTuple,
                        key_fields: vec![],
                        index: 0,
                    })),
```

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 19 files at r1, 1 of 41 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3569)* status: 14 of 74 files reviewed, 2 unresolved discussions (waiting on @neotheprogramist and @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 60 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3569)* status: 17 of 74 files reviewed, 2 unresolved discussions (waiting on @neotheprogramist and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3569#-NZQcERj0PrWbKsfVbLc:-NZW5CbgC-nmtJOcBknd:b-yg80ow) (no related file):*
<details><summary><i>Previously, neotheprogramist (Paweł) wrote…</i></summary><blockquote>

Done :)
</blockquote></details>

Try maybe running ./scripts/rust_fmt.sh - should be configured to be the same as the repo fmt.

___

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 14 of 60 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3569)* status: 31 of 74 files reviewed, 3 unresolved discussions (waiting on @neotheprogramist and @spapinistarkware)

___
*[`crates/bin/sierra-compile/src/main.rs` line 32 at r8](https://reviewable.io/reviews/starkware-libs/cairo/3569#-NZWSVhs-HVJigBBjmcC:-NZWSVhtDMgT17uMg5ws:b-7h5vzz) ([raw file](https://github.com/starkware-libs/cairo/blob/301edebc5768407afdfe3bd091d0f87adbe71185/crates/bin/sierra-compile/src/main.rs#L32)):*
> ```XML
>             Note: StarkNet contracts should be compiled with `starknet-sierra-compile`."
>         })
>     };
> ```

unrelated.



_Code quote:_
```XML
        })
    };
```

**Comment by neotheprogramist** [comment]
> > Reviewed 2 of 19 files at r1, 4 of 45 files at r3, 36 of 41 files at r4, 5 of 12 files at r5.
> > _[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3569)_ status: 14 of 74 files reviewed, 2 unresolved discussions (waiting on @neotheprogramist and @orizi)
> 
> _[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1050 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3569#-NZVQl_45kHk1Oo_IK9l:-NZVQl_45kHk1Oo_IK9m:b-ul2df1) ([raw file](https://github.com/starkware-libs/cairo/blob/66f0be4259a227c6bd5a5a51af83ef2dc3bb1b45/crates/cairo-lang-semantic/src/expr/compute.rs#L1050)):_
> 
> > ```
> >                         key_fields: vec![],
> >                         index: 0,
> >                     })),
> > ```
> 
> This is a problem, since you are generating a stable pointer for a non existing syntax element. When the LSP will try to fetch it, it will panic. We have an invariatn today that all stable pointers are real. I suggest making inner_pattern inside Pattern::EnumVariant an Option.
> 
> _Code quote:_
> 
> ```
>                     stable_ptr: PatternTuplePtr(ctx.db.intern_stable_ptr(SyntaxStablePtr::Child {
>                         parent: enum_pattern.stable_ptr().0,
>                         kind: SyntaxKind::PatternTuple,
>                         key_fields: vec![],
>                         index: 0,
>                     })),
> ```

Fixed

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 13 of 60 files at r11, 1 of 8 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3569)* status: 26 of 76 files reviewed, 4 unresolved discussions (waiting on @neotheprogramist and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3569#-NZQcERj0PrWbKsfVbLc:-NZ_-yQe9LJuAMjRECvF:b-q3yqgn) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Try maybe running ./scripts/rust_fmt.sh - should be configured to be the same as the repo fmt.
</blockquote></details>

Please revert unrelated fmt changes again 

___

**Comment by neotheprogramist** [comment]
> 

Reverted

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3569)* status: 26 of 76 files reviewed, 4 unresolved discussions (waiting on @neotheprogramist and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3569#-NZQcERj0PrWbKsfVbLc:-NZ_QXEd28E9TCZwfrbB:boherp) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Please revert unrelated fmt changes again 
</blockquote></details>

can you please tell us what way you are running the rustfmt - and we'll do a different PR improving it?
it seems you consistently still have the additional rustfmt changes.

___

**Comment by neotheprogramist** [comment]
> > _[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3569)_ status: 26 of 76 files reviewed, 4 unresolved discussions (waiting on @neotheprogramist and @spapinistarkware)
> 
> _[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3569#-NZQcERj0PrWbKsfVbLc:-NZ_QXEd28E9TCZwfrbB:boherp) (no related file):_
> Previously, orizi wrote…
> 
> can you please tell us what way you are running the rustfmt - and we'll do a different PR improving it? it seems you consistently still have the additional rustfmt changes.

I am running `cargo fmt` simply or rust_fmt.sh script from scripts folder

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 60 files at r11, 2 of 8 files at r12.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3569)* status: 29 of 76 files reviewed, 3 unresolved discussions (waiting on @neotheprogramist and @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3569)* status: 29 of 76 files reviewed, 3 unresolved discussions (waiting on @neotheprogramist and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3569#-NZQcERj0PrWbKsfVbLc:-NZ_j0te9zzuM_WZBnIZ:b111te0) (no related file):*
<details><summary><i>Previously, neotheprogramist (Paweł) wrote…</i></summary><blockquote>

I am running `cargo fmt` simply or rust_fmt.sh script from scripts folder.
But what is the problem with formatting, does that break something?
I have used Ctrl + Shift + i in vs code as well, because I like to have everything formatted during code development.
Apologize for that, this is my first PR and I didn't know you prefer unformatted code

</blockquote></details>

we definitely do prefer formatted code (it is a part of our CI) - it is just that we don't want to have unrelated format fixes in a PR.
for some reason - our rustfmt does less than what your rustfmt does (specifically `let ... else { .. }` statements.
so 2 options:
1. find how to fix our rustfmt to behave like yours in another PR.
2. just submit another PR with your changes - so these won't be in this PR.

___

**Comment by neotheprogramist** [comment]
> > _[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3569)_ status: 29 of 76 files reviewed, 3 unresolved discussions (waiting on @neotheprogramist and @spapinistarkware)
> 
> _[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3569#-NZQcERj0PrWbKsfVbLc:-NZ_j0te9zzuM_WZBnIZ:b111te0) (no related file):_
> Previously, neotheprogramist (Paweł) wrote…
> 
> > I am running `cargo fmt` simply or rust_fmt.sh script from scripts folder.
> > But what is the problem with formatting, does that break something?
> > I have used Ctrl + Shift + i in vs code as well, because I like to have everything formatted during code development.
> > Apologize for that, this is my first PR and I didn't know you prefer unformatted code
> 
> we definitely do prefer formatted code (it is a part of our CI) - it is just that we don't want to have unrelated format fixes in a PR. for some reason - our rustfmt does less than what your rustfmt does (specifically `let ... else { .. }` statements. so 2 options:
> 
>     1. find how to fix our rustfmt to behave like yours in another PR.
> 
>     2. just submit another PR with your changes - so these won't be in this PR.

I see, do you mean that thanks to that PR will be more self explanatory?
I have reverted the changes.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r12, 1 of 3 files at r13, 59 of 59 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3569)* status: all files reviewed, 5 unresolved discussions (waiting on @neotheprogramist)

___
*[`crates/bin/sierra-compile/src/main.rs` line 31 at r15](https://reviewable.io/reviews/starkware-libs/cairo/3569#-NZaVpRuDT2rSVFaQ926:-NZaVpRuDT2rSVFaQ927:b8j3xsp) ([raw file](https://github.com/starkware-libs/cairo/blob/62656bc125e5b212bd12b6fbd95c447c5ae3e8b5/crates/bin/sierra-compile/src/main.rs#L31)):*
> ```XML
>             Failed to parse sierra program.
>             Note: StarkNet contracts should be compiled with `starknet-sierra-compile`."
>     })};
> ```

please revert.



_Code quote:_
```XML
        anyhow::bail!(indoc!{"
            Failed to parse sierra program.
            Note: StarkNet contracts should be compiled with `starknet-sierra-compile`."
    })};
```
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 868 at r15](https://reviewable.io/reviews/starkware-libs/cairo/3569#-NZa6IRx578qvTbu5Cy1:-NZa6IRx578qvTbu5Cy2:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b129786c2f7c0f1d1d78bf013baa485763058ff4/crates/cairo-lang-lowering/src/lower/mod.rs#L868)):*
> ```XML
>                     
> 
>                     lower_single_pattern(ctx, &mut subscope, inner_pattern, variant_expr)
> ```





_Suggestion:_
```XML
                        LoweredExpr::AtVariable(VarUsage { var_id, location: pattern_location });

                    lower_single_pattern(ctx, &mut subscope, inner_pattern, variant_expr)
```
___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 126 at r15](https://reviewable.io/reviews/starkware-libs/cairo/3569#-NZaVL8F8k5d3ZFxGHc3:-NZaVL8F8k5d3ZFxGHc4:b1yby4v) ([raw file](https://github.com/starkware-libs/cairo/blob/b129786c2f7c0f1d1d78bf013baa485763058ff4/crates/cairo-lang-starknet/src/plugin/events.rs#L126)):*
> ```XML
> }
> 
> /// Retrieves the field kind for a given struct member, indicating how the field should be serialized.
> ```

line too long



_Code quote:_
```XML
/// Retrieves the field kind for a given struct member, indicating how the field should be serialized.
```
___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 160 at r15](https://reviewable.io/reviews/starkware-libs/cairo/3569#-NZaVHZw9a45yMv64mSP:-NZaVHZw9a45yMv64mSQ:b-agtnr5) ([raw file](https://github.com/starkware-libs/cairo/blob/b129786c2f7c0f1d1d78bf013baa485763058ff4/crates/cairo-lang-starknet/src/plugin/events.rs#L160)):*
> ```XML
> 
> /// Retrieves the field kind for a given enum variant, indicating how the field should be serialized.
> /// See [EventFieldKind].
> ```

line too long.



_Code quote:_
```XML
/// Retrieves the field kind for a given enum variant, indicating how the field should be serialized.
/// See [EventFieldKind].
```
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/diagnostics` line 185 at r15](https://reviewable.io/reviews/starkware-libs/cairo/3569#-NZaVPkZ8djvcrTOG-GJ:-NZaVPkZ8djvcrTOG-GK:b-k9865s) ([raw file](https://github.com/starkware-libs/cairo/blob/62656bc125e5b212bd12b6fbd95c447c5ae3e8b5/crates/cairo-lang-starknet/src/plugin/plugin_test_data/diagnostics#L185)):*
> ```
> //! > ==========================================================================
> 
> //! > Test invalid constractor name.
> ```

why would this test disappear?



_Code quote:_
```
//! > Test invalid constractor name.
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 8 files at r12.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3569)* status: all files reviewed, 5 unresolved discussions (waiting on @neotheprogramist)

**Review by orizi — COMMENTED** [review]
> Reviewed 4 of 4 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3569)* status: all files reviewed, 1 unresolved discussion (waiting on @neotheprogramist and @spapinistarkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3569#-:-NZahhFIBPgvJrjMqVof:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @neotheprogramist and @spapinistarkware)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3569)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 21 of 21 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3569)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 7 of 19 files at r1, 1 of 8 files at r12, 1 of 3 files at r13, 37 of 59 files at r15, 3 of 4 files at r16, 21 of 21 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3569)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @neotheprogramist)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3569#-:-NZf_f6g-cvPDErKMnQU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @neotheprogramist)

**Review by orizi — APPROVED** [review]
> Reviewed 7 of 12 files at r18, 2 of 2 files at r19, 2 of 2 files at r20, 12 of 12 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3569)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @neotheprogramist)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3569)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @neotheprogramist)

**Pull request merged**
