### PR TITLE
Fix cfg attribute for TEST_CLASS_HASH

### PR DESCRIPTION
**Pull request by maciektr**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5219)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5219)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @maciektr and @mkaput)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5219#-NsOnEQh6XTFZbo1qBWf:-NsOnEQh6XTFZbo1qBWg:b-ikfktk) (no related file):*
target 2.6.2 instead.

___

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 11 of 11 files at r2, 57 of 57 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5219#-:-NsOolhQCdIPNDShMvWF:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @maciektr and @mkaput)

**Review by mkaput — CHANGES_REQUESTED** [review]
Have you verified this works with Foundry ?

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5219)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @maciektr)

**Review by mkaput — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5219#-:-NsRytJwC_sVZNCRZeVP:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @maciektr)

**Pull request merged**
