### PR TITLE
Made `withdraw_gas` support cases to get gas for builtins as well.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2989)

### CODE REVIEW

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2989)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`tests/e2e_test_data/libfuncs/withdraw_gas_all` line 431 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2989#-NUzIdGJ6pa8ApYUqJO5:-NUzIdGJ6pa8ApYUqJO6:b4g9elu) ([raw file](https://github.com/starkware-libs/cairo/blob/c689120841a4d1bf841c2e5bc17d3587fa3d9238/tests/e2e_test_data/libfuncs/withdraw_gas_all#L431)):*
> ```
> test::foo@0([0]: RangeCheck, [1]: GasBuiltin, [2]: Pedersen, [3]: Bitwise, [4]: BuiltinCosts) -> (RangeCheck, GasBuiltin, Pedersen, Bitwise, core::option::Option::<()>);
> 
> //! > ==========================================================================
> ```

There's a `gas` test file. I think you should use it.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2989)* status: 0 of 13 files reviewed, 2 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2989#-NUzV1LK2S3JSngrjHxs:-NUzV1LK2S3JSngrjHxt:b-qo79eu) (no related file):*
Change target branch to `sierra-v1.1.0`

___

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2989)* status: 0 of 14 files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`tests/e2e_test_data/libfuncs/withdraw_gas_all` line 431 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2989#-NUzIdGJ6pa8ApYUqJO5:-NV0CtLeEHNYlC3Kal4D:b-8ucrrk) ([raw file](https://github.com/starkware-libs/cairo/blob/c689120841a4d1bf841c2e5bc17d3587fa3d9238/tests/e2e_test_data/libfuncs/withdraw_gas_all#L431)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

There's a `gas` test file. I think you should use it.
</blockquote></details>

these isn't a gas file - but it makes sense to rename this one to `gas`.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2989)* status: 1 of 15 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`tests/e2e_test_data/libfuncs/gas` line 605 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2989#-NXGOYZ_9d8yYL_3evgP:-NXGOYZ_9d8yYL_3evgQ:b-xyw03y) ([raw file](https://github.com/starkware-libs/cairo/blob/52c6387d4b11e191cde49e8c7564082b1de0043a/tests/e2e_test_data/libfuncs/gas#L605)):*
> ```
> call rel 39;
> [ap + 0] = [ap + -1] + 38, ap++;
> [ap + 0] = [[ap + -4] + 0], ap++;
> ```

What is `[ap - 4]`?



_Code quote:_
```
[ap + -4] 
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2989)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`tests/e2e_test_data/libfuncs/gas` line 605 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2989#-NXGOYZ_9d8yYL_3evgP:-NXJm1k-7G5wvUTSczj7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/52c6387d4b11e191cde49e8c7564082b1de0043a/tests/e2e_test_data/libfuncs/gas#L605)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

What is `[ap - 4]`?
</blockquote></details>

Done.

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 13 files at r1, 1 of 9 files at r2, 3 of 11 files at r3, 6 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2989)* status: 9 of 15 files reviewed, all discussions resolved

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2989)* status: 10 of 15 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-gas/src/compute_costs.rs` line 88 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2989#-NXtKh0NAj4NxqDE3as1:-NXtKh0NAj4NxqDE3as2:b-eqcden) ([raw file](https://github.com/starkware-libs/cairo/blob/d234d98f187e7d5f758247e08d934478b1cd8d35/crates/cairo-lang-sierra-gas/src/compute_costs.rs#L88)):*
> ```XML
>     for (branch_info, branch_cost) in zip_eq(&invocation.branches, libfunc_cost) {
>         match branch_cost {
>             BranchCost::FunctionCall { function, .. } => {
> ```

I'm not sure about this change. Sometimes it helps to see what you don't enforce and not just the things you check. Also, if an additional field will be added the compiler will not give an error here and we may forget to update here.
(Shahar also said the previous version is better)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2989)* status: 11 of 15 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-gas/src/compute_costs.rs` line 437 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2989#-NXtLVyN1B3vLeFHrlKp:-NXtLVyO-x6c_yVu_9n3:b-v0jp20) ([raw file](https://github.com/starkware-libs/cairo/blob/d234d98f187e7d5f758247e08d934478b1cd8d35/crates/cairo-lang-sierra-gas/src/compute_costs.rs#L437)):*
> ```XML
>                 wallet_at_fn(&function.entry_point).get_pure_value()
>             }
>             BranchCost::WithdrawGas { success: true, .. } => {
> ```

I don't like this either. It makes the code more difficult to read (as now WithdrawGas appears twice).

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2989)* status: 11 of 15 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 366 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2989#-NXtNNxE4lvGMcR4vDot:-NXtNNxE4lvGMcR4vDou:b-j958aj) ([raw file](https://github.com/starkware-libs/cairo/blob/d234d98f187e7d5f758247e08d934478b1cd8d35/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L366)):*
> ```XML
>                 let extra_failure_cost =
>                     if with_builtin_costs || cost_computation > 0 { 2 } else { 1 };
>                 let extra_failure_cost = if success { 0 } else { extra_failure_cost };
> ```

Either move to a nested `if` (combine with the previous line) or move to `let mut steps = ...` and `steps += ...` and `if (!success) { steps += ... }`.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2989)* status: 11 of 15 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 418 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2989#-NXtNnnA8oOQbZXDwowp:-NXtNnnA8oOQbZXDwowq:bxdvhvv) ([raw file](https://github.com/starkware-libs/cairo/blob/d234d98f187e7d5f758247e08d934478b1cd8d35/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L418)):*
> ```XML
>             }
>             BranchCost::BranchAlign => statement_vars_cost(ops, CostTokenType::iter_precost()),
>             BranchCost::WithdrawGas { success: true, .. } => {
> ```

Revert here as well.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2989)* status: 11 of 15 files reviewed, 7 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs` line 42 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2989#-NXtQZkb4MYAQr5fFGIM:-NXtQZkb4MYAQr5fFGIN:b8zkdmg) ([raw file](https://github.com/starkware-libs/cairo/blob/d234d98f187e7d5f758247e08d934478b1cd8d35/crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs#L42)):*
> ```XML
>     };
>     let variable_values = &builder.program_info.metadata.gas_info.variable_values;
>     // Checking if we need to fetch the builtin cost table.
> ```

Add a blank line above this line.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs` line 42 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2989#-NXtQclo7r342RKC5vu7:-NXtQclo7r342RKC5vu8:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d234d98f187e7d5f758247e08d934478b1cd8d35/crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs#L42)):*
> ```XML
>     };
>     let variable_values = &builder.program_info.metadata.gas_info.variable_values;
>     // Checking if we need to fetch the builtin cost table.
> ```





_Suggestion:_
```XML
// Check if we need to fetch the builtin cost table.
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs` line 208 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2989#-NXtPzMI9tixJ981fHlH:-NXtPzMI9tixJ981fHlI:b-76v7gs) ([raw file](https://github.com/starkware-libs/cairo/blob/d234d98f187e7d5f758247e08d934478b1cd8d35/crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs#L208)):*
> ```XML
>         assert updated_gas = *(range_check++);
>     };
>     Ok(builder.build_from_casm_builder_ex(
> ```

First time we're using this function :) Let's hope it works :)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2989)* status: 11 of 15 files reviewed, 7 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-gas/src/compute_costs.rs` line 88 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2989#-NXtKh0NAj4NxqDE3as1:-NXtPYVRBjmNCRAgdwjJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d234d98f187e7d5f758247e08d934478b1cd8d35/crates/cairo-lang-sierra-gas/src/compute_costs.rs#L88)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

I'm not sure about this change. Sometimes it helps to see what you don't enforce and not just the things you check. Also, if an additional field will be added the compiler will not give an error here and we may forget to update here.
(Shahar also said the previous version is better)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-gas/src/compute_costs.rs` line 437 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2989#-NXtLVyN1B3vLeFHrlKp:-NXtOd8o2g7OjE4g_VII:b-l76dcl) ([raw file](https://github.com/starkware-libs/cairo/blob/d234d98f187e7d5f758247e08d934478b1cd8d35/crates/cairo-lang-sierra-gas/src/compute_costs.rs#L437)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

I don't like this either. It makes the code more difficult to read (as now WithdrawGas appears twice).
</blockquote></details>

I find it shorter and nicer - but ok.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2989)* status: 10 of 15 files reviewed, 8 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs` line 47 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2989#-NXtRDYA8ilaeDc9waZs:-NXtUzxMBRdZ_xss2yMV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d234d98f187e7d5f758247e08d934478b1cd8d35/crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs#L47)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Let's put the `1` in a constant.
</blockquote></details>

Done.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2989)* status: 10 of 15 files reviewed, 9 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 363 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2989#-NXtVkYeDMgX_psR6hOP:-NXtVkYeDMgX_psR6hOQ:b-8utl4l) ([raw file](https://github.com/starkware-libs/cairo/blob/88ee98e67381a5a3bf263817e8775364b274829e/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L363)):*
> ```XML
>                     })
>                     .into_or_panic();
>                 let base_cost = if !with_builtin_costs && cost_computation > 0 { 7 } else { 3 };
> ```

I want to rewrite this code, let's discuss f2f.

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 13 files at r1, 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2989)* status: 12 of 15 files reviewed, 8 unresolved discussions (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2989)* status: 12 of 15 files reviewed, 8 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 363 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2989#-NXtVkYeDMgX_psR6hOP:-NXtWwOhCIXJO2aY6Xss:b9ebvz1) ([raw file](https://github.com/starkware-libs/cairo/blob/88ee98e67381a5a3bf263817e8775364b274829e/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L363)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

I want to rewrite this code, let's discuss f2f.
</blockquote></details>

after the pr that makes `withdraw_gas_all` optimized as well - this code would be simpler.
can this be postponed to then?

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 8 files at r4, 1 of 3 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2989#-:-NXxpKi45qAelc7cLt3-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 364 at r7](https://reviewable.io/reviews/starkware-libs/cairo/2989#-NXxoaPW2YDT_51OSA3_:-NXxoaPX0yuFJ1PHq4Ge:b-31e326) ([raw file](https://github.com/starkware-libs/cairo/blob/3cae7d78ce19524512159ffd50ac59384bd72871/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L364)):*
> ```XML
>                     .into_or_panic();
>                 let mut steps = 3 + cost_computation;
>                 if !with_builtin_costs && cost_computation > 0 {
> ```

Missing the comments we added.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2989)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 364 at r7](https://reviewable.io/reviews/starkware-libs/cairo/2989#-NXxoaPW2YDT_51OSA3_:-NXxrEIP2CUJ7VN216r9:b-ukv3zj) ([raw file](https://github.com/starkware-libs/cairo/blob/3cae7d78ce19524512159ffd50ac59384bd72871/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L364)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Missing the comments we added.
</blockquote></details>

yeah - somehow disappeared - adding

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2989)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
