### PR TITLE
Updating the Diagnostics Pointer in wrong type for contract.

### PR DESCRIPTION
**Pull request by Tomer-StarkWare**

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6849)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6849#-ODfGV0j-FwuTLSXhkf-:-ODfGV0j-FwuTLSXhkf0:bgk1jl8) ([raw file](https://github.com/starkware-libs/cairo/blob/e669a7bae292c342a49a6e4a2648a451078580d6/crates/cairo-lang-starknet/src/analyzer.rs#L84)):*
> ```XML
>                 err.location(db)
>                     .unwrap_or_else(|| contract.submodule_id.stable_ptr(db.upcast()).untyped()),
>                 format!("Failed to generate ABI: {err}"),
> ```

if you were supplied with location - you should still use it.



_Code quote:_
```XML
                err.location(db)
                    .unwrap_or_else(|| contract.submodule_id.stable_ptr(db.upcast()).untyped()),
                format!("Failed to generate ABI: {err}"),
```
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/interfaces` line 1729 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6849#-ODfGKFc-KvObA1tDaML:-ODfGKFc-KvObA1tDaMM:bcrty0g) ([raw file](https://github.com/starkware-libs/cairo/blob/e669a7bae292c342a49a6e4a2648a451078580d6/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/interfaces#L1729)):*
> ```
> warning: Plugin diagnostic: Failed to generate ABI: Duplicate entry point: 'foo'. This is not currently supported.
>  --> lib.cairo:56:5
>     #[abi(embed_v0)]
> ```

this is definitely a degregation.
___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6849#-ODfF-141ZfmHxTdjzhL:-ODfF-141ZfmHxTdjzhM:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/19a9b1c9617174d6630c3063d1a4cfc5429eb4ea/crates/cairo-lang-starknet/src/analyzer.rs#L88)):*
> ```XML
>                     break;
>                 }
>             }
> ```





_Suggestion:_
```XML
            let mut contract_stable_ptr = if let Some(attr) = contract.module_id().find_attr(db, CONTRACT_ATTR) {
                attr.stable_ptr.untyped()
                } else {
                contract.submodule_id.stable_ptr(db.upcast()).untyped()
            };
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6849)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6849#-ODfGV0j-FwuTLSXhkf-:-ODhGhts2gniP3SEWiB4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e669a7bae292c342a49a6e4a2648a451078580d6/crates/cairo-lang-starknet/src/analyzer.rs#L84)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

if you were supplied with location - you should still use it.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/interfaces` line 1729 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6849#-ODfGKFc-KvObA1tDaML:-ODhJnUFCDc9l2N5GMFr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e669a7bae292c342a49a6e4a2648a451078580d6/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/interfaces#L1729)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is definitely a degregation.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6849#-ODfF-141ZfmHxTdjzhL:-ODhG6BGARnz4jgXTcrJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/19a9b1c9617174d6630c3063d1a4cfc5429eb4ea/crates/cairo-lang-starknet/src/analyzer.rs#L88)):*
> ```XML
>                     break;
>                 }
>             }
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6849)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6849#-ODjP3I71-p7o7sL1s_s:-ODjP3I8B6lQmCk1eFjJ:bd1118t) (no related file):*
do you have any example that is still mapped to full contract?
(As this didn't change any diags)
___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 91 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6849#-ODjOaos-uGyxCmRLPEH:-ODjOaos-uGyxCmRLPEI:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2e14e22c1832621139cabd90a6df4a065d8b4c6b/crates/cairo-lang-starknet/src/analyzer.rs#L91)):*
> ```XML
>                 err.location(db).unwrap_or(contract_stable_ptr),
>                 format!("Failed to generate ABI: {err}"),
>             ));
> ```





_Suggestion:_
```XML
            let location = err.location(db).unwrap_or_else(
                || if let Ok(Some(attr)) = contract.module_id().find_attr(db, CONTRACT_ATTR) {
                    attr.stable_ptr.untyped()
                } else {
                    contract.submodule_id.stable_ptr(db.upcast()).untyped()
                });

            diagnostics.push(PluginDiagnostic::warning(
                location, format!("Failed to generate ABI: {err}")
            ));
```

**Review by Tomer-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6849)* status: 0 of 120 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6849#-ODjP3I71-p7o7sL1s_s:-OE8ad3X3GtdD3kgIA6w:b388a6l) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

do you have any example that is still mapped to full contract?
(As this didn't change any diags)
</blockquote></details>

Yes, I rebased it on top of the PR with the multi-line diagnostic support, now the changes are visible
___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 91 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6849#-ODjOaos-uGyxCmRLPEH:-ODjYbpMCeKhBvKUN3Cq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2e14e22c1832621139cabd90a6df4a065d8b4c6b/crates/cairo-lang-starknet/src/analyzer.rs#L91)):*
> ```XML
>                 err.location(db).unwrap_or(contract_stable_ptr),
>                 format!("Failed to generate ABI: {err}"),
>             ));
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6849#-:-OEAGQukD-4D1-wzr0cm:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6849)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
