### PR TITLE
UnorderedHashMap::{iter_sorted, aggregate_by}

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4799)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4799)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-utils/src/unordered_hash_map.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4799#-No96sGmC_Ks3p7bT67R:-No96sGmC_Ks3p7bT67S:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ff8aaf10eebce50d81a1c750ab2db194d083e6f9/crates/cairo-lang-utils/src/unordered_hash_map.rs#L24)):*
> ```XML
> #[derive(Clone, Debug)]
> pub struct UnorderedHashMap<Key, Value, BH = RandomState>(HashMap<Key, Value, BH>);
> #[cfg(not(feature = "std"))]
> ```





_Suggestion:_
```XML
use itertools::Itertools;

/// A hash map that does not care about the order of insertion.
/// In particular, it does not support iterating, in order to guarantee deterministic compilation.
/// It does support aggregation which can be used in intermediate computations (see `aggregate_by`).
/// For an iterable version see [OrderedHashMap](crate::ordered_hash_map::OrderedHashMap).
#[cfg(feature = "std")]
#[derive(Clone, Debug)]
pub struct UnorderedHashMap<Key, Value, BH = RandomState>(HashMap<Key, Value, BH>);
#[cfg(not(feature = "std"))]
```
___
*[`crates/cairo-lang-utils/src/unordered_hash_map.rs` line 170 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4799#-No97CsrA6t6ix71ADmY:-No97CsrA6t6ix71ADmZ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ff8aaf10eebce50d81a1c750ab2db194d083e6f9/crates/cairo-lang-utils/src/unordered_hash_map.rs#L170)):*
> ```XML
>             acc
>         })
>     }
> ```





_Suggestion:_
```XML
    #[cfg(feature = "std")]
    pub fn aggregate_by<TargetKey: Eq + Hash, TargetValue: Clone>(
        &self,
        mapping_function: impl Fn(&Key) -> TargetKey,
        reduce_function: impl Fn(TargetValue, &Value) -> TargetValue,
        default_value: &TargetValue,
    ) -> UnorderedHashMap<TargetKey, TargetValue> {
        self.0.iter().fold(UnorderedHashMap::<TargetKey, Value>::new(), |mut acc, (key, value)| {
            let new_key = mapping_function(key);
            match acc.entry(new_key) {
                std::collections::hash_map::Entry::Occupied(mut occupied) => {
                    let new_value = reduce_function(occupied.get(), value);
                    *occupied.get_mut() = new_value;
                }
                std::collections::hash_map::Entry::Vacant(vacant) => {
                    let new_value = reduce_function(default_value.clone(), value);
                    vacant.insert(new_value);
                }
            };
            acc
        })
    }
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4799)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-utils/src/unordered_hash_map.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4799#-No96sGmC_Ks3p7bT67R:-NoAkjib22KG7217pcW-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ff8aaf10eebce50d81a1c750ab2db194d083e6f9/crates/cairo-lang-utils/src/unordered_hash_map.rs#L24)):*
> ```XML
> #[derive(Clone, Debug)]
> pub struct UnorderedHashMap<Key, Value, BH = RandomState>(HashMap<Key, Value, BH>);
> #[cfg(not(feature = "std"))]
> ```

Done.
___
*[`crates/cairo-lang-utils/src/unordered_hash_map.rs` line 170 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4799#-No97CsrA6t6ix71ADmY:-NoAvbPLEmGJjOAdDH24:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ff8aaf10eebce50d81a1c750ab2db194d083e6f9/crates/cairo-lang-utils/src/unordered_hash_map.rs#L170)):*
> ```XML
>             acc
>         })
>     }
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4799#-:-NoBvo7U356Rog7Lq7QA:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4799)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
