### PR TITLE
Add `SyntaxNode::lookup_position`

### PR DESCRIPTION
**Pull request by mkaput**
**Stack**:
- #5569
- #5562 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5562)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5562)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @mkaput)

___
*[`crates/cairo-lang-syntax/src/node/mod.rs` line 162 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5562#-Nxvgy0v4E5Sz-iXLk-0:-Nxvg5Dw9MkuGI98ZQld:b-9ors2u) ([raw file](https://github.com/starkware-libs/cairo/blob/dddbd824946c9e1932acec24d307fdb76e37f8d0/crates/cairo-lang-syntax/src/node/mod.rs#L162)):*
> ```XML
> 
>     /// Lookups a syntax node using a position.
>     pub fn lookup_position(&self, db: &dyn SyntaxGroup, position: TextPosition) -> SyntaxNode {
> ```

I'm not sure this makes sense as a function - as this will make the user not notice the cases where the position itself is non sensible (which is only checked by the conversion attempt)

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5562)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-syntax/src/node/mod.rs` line 162 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5562#-Nxvgy0v4E5Sz-iXLk-0:-NxvwX1a5FGsoWshbg1m:bpzjn9t) ([raw file](https://github.com/starkware-libs/cairo/blob/dddbd824946c9e1932acec24d307fdb76e37f8d0/crates/cairo-lang-syntax/src/node/mod.rs#L162)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I'm not sure this makes sense as a function - as this will make the user not notice the cases where the position itself is non sensible (which is only checked by the conversion attempt)
</blockquote></details>

Good catch! In general, the bad cases are: 1) position line is > count of lines in the file, 2) column line is > length of the line.

The case 1) is sensible because this code is kind of “truncating” the position to the end of the file, like `lookup_offset` does. The case 2) is indeed wrong here, and I actually need to fix it to be correct!

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5562)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @mkaput)

___
*[`crates/cairo-lang-syntax/src/node/mod.rs` line 162 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5562#-Nxvgy0v4E5Sz-iXLk-0:-Nxw6_eL6ReDrzIX2A9_:b-gt0muh) ([raw file](https://github.com/starkware-libs/cairo/blob/aa60a3fce3cd8c69860eae74cc8d83b554fd5fb8/crates/cairo-lang-syntax/src/node/mod.rs#L162)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Good catch! In general, the bad cases are: 1) position line is > count of lines in the file, 2) column line is > length of the line.

The case 1) is sensible because this code is kind of “truncating” the position to the end of the file, like `lookup_offset` does. The case 2) is indeed wrong here, and I actually need to fix it to be correct!
</blockquote></details>

awaiting update :)

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5562)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-syntax/src/node/mod.rs` line 162 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5562#-Nxvgy0v4E5Sz-iXLk-0:-Ny-OP9o04XtmbFNqpaA:bbv944) ([raw file](https://github.com/starkware-libs/cairo/blob/0871f1bf0d0938a7bd41cc8a9de40fb72402b31b/crates/cairo-lang-syntax/src/node/mod.rs#L162)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

awaiting update :)
</blockquote></details>

Done in https://github.com/starkware-libs/cairo/pull/5569

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5562#-:-Ny-PTC80ApCrNBXkkDM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Pull request merged**
