### PR TITLE
Added support for generic traits/impls and lookup in corelib

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1825)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 50 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1825)* status: 4 of 50 files reviewed, 4 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`corelib/lib.cairo` line 64 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1825#-NMCNbwx-fWCatymw_nu:-NMCNbwyByQTC3O7Swrl:buk7qm2) ([raw file](https://github.com/starkware-libs/cairo/blob/c1ca267170c5a5175959fb750c0a1d7c5deb54f2/corelib/lib.cairo#L64)):*
> ```Cairo
> // TODO(yuval): there are still issues with looking up impls with generics. This is a temporary
> // demonstration of being able to use traits in the corelib. We need to add generic args and use
> // impls for all binary operators.
> ```

Then perhaps we should wait until inference with addind Add?
___
*[`crates/cairo-lang-lowering/src/inline/test_data/inline` line 66 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1825#-NMCOFTl7LdB0ti1X2dp:-NMCOFTl7LdB0ti1X2dq:b-xs4lpt) ([raw file](https://github.com/starkware-libs/cairo/blob/c1ca267170c5a5175959fb750c0a1d7c5deb54f2/crates/cairo-lang-lowering/src/inline/test_data/inline#L66)):*
> ```
> 
> //! > semantic_diagnostics
> error: Function is declared as nopanic but calls a function that may panic.
> ```

This is an issue. I don't want felt add to be panicable.
I hate panics....

The check of panics should occur on impl function.
Can you add nopanic to the impl for felt?
___
*[`crates/cairo-lang-semantic/src/corelib.rs` line 385 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1825#-NMCM02kBqqR2E4WjViI:-NMCM02kBqqR2E4WjViJ:b-qcb0tb) ([raw file](https://github.com/starkware-libs/cairo/blob/c1ca267170c5a5175959fb750c0a1d7c5deb54f2/crates/cairo-lang-semantic/src/corelib.rs#L385)):*
> ```XML
>     let trait_id = extract_matches!(module_item_id, ModuleItemId::Trait);
>     // TODO(yuval): generic_args
>     let concrete_trait_id =
> ```

After my inference PR, we can pass inference.new_var() as a generic arg
___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 534 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1825#-NMCN0gJ0COk3YiVTpUA:-NMCN0gJ0COk3YiVTpUB:bbnfuae) ([raw file](https://github.com/starkware-libs/cairo/blob/c1ca267170c5a5175959fb750c0a1d7c5deb54f2/crates/cairo-lang-semantic/src/diagnostic.rs#L534)):*
> ```XML
>         actual_ty: semantic::TypeId,
>         /// Indicates whether the wrong type is for a param or for a return type of a function.
>         param_or_return_type: ParamOrReturnType,
> ```

Why are you uniting the kinds like this? A good rule of thumb is that you shouldn't have flag variables that alter the flow  So, consumers having to consume this, will need to make some if based in it.
If you wanna avoid rewriting fields, use a struct for them.

Another possibility is to remove this info altogether. Is there really a difference between variable assignment and return type?

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1825)* status: 4 of 50 files reviewed, 6 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/resolve_path.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1825#-NMCPbUfCde24tnxTLCX:-NMCPbUfCde24tnxTLCY:b-sxb6cn) ([raw file](https://github.com/starkware-libs/cairo/blob/c1ca267170c5a5175959fb750c0a1d7c5deb54f2/crates/cairo-lang-semantic/src/resolve_path.rs#L159)):*
> ```XML
>         generic_params: &[GenericParamId],
>     ) -> Self {
>         // TODO(yuval): check that we don't repeat generic params. Note it can also happen between
> ```

How can this happen? Also, It's not good, but can it lead to errors?
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 726 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1825#-NMCRiZ5DC2BY26XOLlI:-NMCRiZ5DC2BY26XOLlJ:b-y37yhh) ([raw file](https://github.com/starkware-libs/cairo/blob/c1ca267170c5a5175959fb750c0a1d7c5deb54f2/crates/cairo-lang-semantic/src/items/imp.rs#L726)):*
> ```XML
>     concrete_trait: ConcreteTraitId,
>     potential_diag_params: PotentialDiagParams,
> ) {
> ```

I don't think this is necessary. Can't you use substitute generic params on the trait signature and then verify equalities?

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1825)* status: 4 of 50 files reviewed, 7 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/items/trt.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1825#-NMCRwLjAWXDRVn6pBR3:-NMCRwLjAWXDRVn6pBR4:bbutf2u) ([raw file](https://github.com/starkware-libs/cairo/blob/c1ca267170c5a5175959fb750c0a1d7c5deb54f2/crates/cairo-lang-semantic/src/items/trt.rs#L40)):*
> ```XML
>     }
> 
>     // TODO(yuval): This is currently super inefficient - it calculates the whole mapping each time,
> ```

Why not use substitute_generic_params? Like in functions.

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1825)* status: 4 of 50 files reviewed, 7 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 534 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1825#-NMCN0gJ0COk3YiVTpUA:-NML3-goDA7sAfZZXOCY:b-5eq2hi) ([raw file](https://github.com/starkware-libs/cairo/blob/c1ca267170c5a5175959fb750c0a1d7c5deb54f2/crates/cairo-lang-semantic/src/diagnostic.rs#L534)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Why are you uniting the kinds like this? A good rule of thumb is that you shouldn't have flag variables that alter the flow  So, consumers having to consume this, will need to make some if based in it.
If you wanna avoid rewriting fields, use a struct for them.

Another possibility is to remove this info altogether. Is there really a difference between variable assignment and return type?
</blockquote></details>

No, there is no difference. This is exactly why I united them. I am ok with removing the first word of the diagnostic of both.
___
*[`crates/cairo-lang-semantic/src/resolve_path.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1825#-NMCPbUfCde24tnxTLCX:-NML3W4u51lXLY98gvmk:b6fh59f) ([raw file](https://github.com/starkware-libs/cairo/blob/c1ca267170c5a5175959fb750c0a1d7c5deb54f2/crates/cairo-lang-semantic/src/resolve_path.rs#L159)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

How can this happen? Also, It's not good, but can it lead to errors?
</blockquote></details>

See the test for how it can happen. We need to think through what errors it could lead. My hunch is that we need to forbid it anyway. No good can come from it.

**Pull request closed without merging**
