### PR TITLE
Add Signature struct.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3596)

### CODE REVIEW

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3596#-:-NZZyzSvDT9zabK794Ry:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`corelib/src/starknet/secp256_trait.cairo` line 24 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3596#-NZZwhl651fqjQ_vBcuq:-NZZwhl651fqjQ_vBcur:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/19dc4136b6a4dec92ac2724eedd7f18ea1fe4619/corelib/src/starknet/secp256_trait.cairo#L24)):*
> ```Cairo
> /// Creates an ECDSA signature from the v, r and s values.
> fn signature_from_vrs(v: u32, r: u256, s: u256) -> Signature {
>     Signature { r: r, s: s, y_parity: v % 2 == 1,  }
> ```





_Suggestion:_
```Cairo
r, s, y_parity: v % 2 == 1,
```
___
*[`corelib/src/starknet/secp256_trait.cairo` line 54 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3596#-NZZx3FxEkaPMMhPFrc_:-NZZx3FxEkaPMMhPFrca:b-gczlrg) ([raw file](https://github.com/starkware-libs/cairo/blob/19dc4136b6a4dec92ac2724eedd7f18ea1fe4619/corelib/src/starknet/secp256_trait.cairo#L54)):*
> ```Cairo
>     msg_hash: u256, signature: Signature
> ) -> Option<Secp256Point> {
>     let r = signature.r;
> ```

consider deconstructing in the beginning:
let {r, s, y_parity } = signature;
___
*[`corelib/src/starknet/secp256_trait.cairo` line 91 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3596#-NZZxL-s3gP7uieljUU6:-NZZxL-s3gP7uieljUU7:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/19dc4136b6a4dec92ac2724eedd7f18ea1fe4619/corelib/src/starknet/secp256_trait.cairo#L91)):*
> ```Cairo
> 
> /// Verifies a Secp256 ECDSA signature.
> /// Also verifies that r and s are in the range (0, N), where N is the size of the curve.
> ```





_Suggestion:_
```Cairo
 that signature.r and signature.s are in the range (
```
___
*[`corelib/src/test/secp256k1_test.cairo` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3596#-NZZxtJW1HRedwZnMyyO:-NZZxtJW1HRedwZnMyyP:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/19dc4136b6a4dec92ac2724eedd7f18ea1fe4619/corelib/src/test/secp256k1_test.cairo#L42)):*
> ```Cairo
>     let signature = signature_from_vrs(v, r, s);
> 
>     assert(signature == Signature { r, s, y_parity: v % 2 == 1 }, 'Wrong result');
> ```





_Suggestion:_
```Cairo
y_parity: false
```
___
*[`corelib/src/test/secp256k1_test.cairo` line 53 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3596#-NZZyWLLAGu3Cfx4lyJd:-NZZyWLLAGu3Cfx4lyJe:b-kob0yh) ([raw file](https://github.com/starkware-libs/cairo/blob/19dc4136b6a4dec92ac2724eedd7f18ea1fe4619/corelib/src/test/secp256k1_test.cairo#L53)):*
> ```Cairo
>     let (public_key_x, public_key_y) = if y_parity {
>         (
>             0xa9a02d48081294b9bb0d8740d70d3607feb20876964d432846d9b9100b91eefd,
> ```

Did you check that this is the case in which r_y is odd?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3596)* status: all files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3596#-NZ_0APiDGtVHz6WRUo_:-NZ_0APiDGtVHz6WRUoa:b-g05let) (no related file):*
It seems the r1 test is not included for some reason 

___

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/test/secp256k1_test.cairo` line 53 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3596#-NZZyWLLAGu3Cfx4lyJd:-NZ_7RZk1nMZ1Qm9cbu4:b-pswlpt) ([raw file](https://github.com/starkware-libs/cairo/blob/19dc4136b6a4dec92ac2724eedd7f18ea1fe4619/corelib/src/test/secp256k1_test.cairo#L53)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Did you check that this is the case in which r_y is odd?
</blockquote></details>

I didn't change the test coverage.

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/test/secp256k1_test.cairo` line 53 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3596#-NZZyWLLAGu3Cfx4lyJd:-NZ_7dGX-_8asoC6cDyp:bp5z4jw) ([raw file](https://github.com/starkware-libs/cairo/blob/19dc4136b6a4dec92ac2724eedd7f18ea1fe4619/corelib/src/test/secp256k1_test.cairo#L53)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I didn't change the test coverage.
</blockquote></details>

actually, I'm not sure.

was there a case that was covered only by test_secp256k1_recover_public_key_u32?

**Comment by yuvalsw** [comment]
*[`corelib/src/test/secp256k1_test.cairo` line 53 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3596#-NZZyWLLAGu3Cfx4lyJd:-NZ_D9uQ3-nY_ttGxDRw:bz22m96) ([raw file](https://github.com/starkware-libs/cairo/blob/19dc4136b6a4dec92ac2724eedd7f18ea1fe4619/corelib/src/test/secp256k1_test.cairo#L53)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

actually, I'm not sure.

was there a case that was covered only by test_secp256k1_recover_public_key_u32?
</blockquote></details>

No, it checked the same cases, but using the _u32 version. This is equivalent to you doing the same thing, just building the signature using from_vrs.

The comment probably fits the other PR better

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/test/secp256k1_test.cairo` line 53 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3596#-NZZyWLLAGu3Cfx4lyJd:-NZ_FgSh2SmiBLqN3HB4:b-a7a1r5) ([raw file](https://github.com/starkware-libs/cairo/blob/19dc4136b6a4dec92ac2724eedd7f18ea1fe4619/corelib/src/test/secp256k1_test.cairo#L53)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

No, it checked the same cases, but using the _u32 version. This is equivalent to you doing the same thing, just building the signature using from_vrs.

The comment probably fits the other PR better
</blockquote></details>

I removed this test entirely as I felt it was redundant.

**Review by yuvalsw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3596)* status: all files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3596)* status: all files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3596#-NZ_0APiDGtVHz6WRUo_:-NZ_Qz6g-56xOjKGSa1j:b-l5r7zq) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

It seems the r1 test is not included for some reason 
</blockquote></details>

ok - please rebase and then you'll need to fix the r1 test as well.

___

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3596)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @yuvalsw)

___
*[`corelib/src/starknet/secp256_trait.cairo` line 54 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3596#-NZZx3FxEkaPMMhPFrc_:-NZ_ciNHEqylFwr2icOn:b-r18wie) ([raw file](https://github.com/starkware-libs/cairo/blob/19dc4136b6a4dec92ac2724eedd7f18ea1fe4619/corelib/src/starknet/secp256_trait.cairo#L54)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

consider deconstructing in the beginning:
let {r, s, y_parity } = signature;
</blockquote></details>

done, thanks.
___
*[`corelib/src/test/secp256k1_test.cairo` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3596#-NZZxtJW1HRedwZnMyyO:-NZ_dXuu6vM_zm3n8hoB:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/19dc4136b6a4dec92ac2724eedd7f18ea1fe4619/corelib/src/test/secp256k1_test.cairo#L42)):*
> ```Cairo
>     let signature = signature_from_vrs(v, r, s);
> 
>     assert(signature == Signature { r, s, y_parity: v % 2 == 1 }, 'Wrong result');
> ```

done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3596#-:-NZ_iCpLCvA1mbHMf9FF:bnfp4nl)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3596)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @orizi and @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3596#-NZ_0APiDGtVHz6WRUo_:-NZ_kDC67NMWcH-iAjck:b-7rl0jd) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

ok - please rebase and then you'll need to fix the r1 test as well.
</blockquote></details>

done.

___

**Pull request merged**
