### PR TITLE
Add an item macro.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3877)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3877)* status: all files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 734 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NbTvSmn2jVPOkq0npbx:-NbTvSmn2jVPOkq0npby:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/45c61add4afa2fbc86a0a85cbd32c24415c56b48/crates/cairo-lang-parser/src/parser.rs#L734)):*
> ```XML
>     }
> 
>     /// Returns a GreenId of a node with a ItemInitMacro kind (see
> ```





_Suggestion:_
```XML
 node with an ItemInlineMacro kind 
```
___
*[`crates/cairo-lang-parser/src/parser.rs` line 737 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NbTugou2fbd8Ifg7wy4:-NbTugou2fbd8Ifg7wy5:brk0mj) ([raw file](https://github.com/starkware-libs/cairo/blob/45c61add4afa2fbc86a0a85cbd32c24415c56b48/crates/cairo-lang-parser/src/parser.rs#L737)):*
> ```XML
>     /// [syntax::node::ast::ItemInlineMacro]), or None if a macro can't be parsed.
>     fn try_parse_item_macro(&mut self) -> Option<ItemInlineMacroGreen> {
>         let macro_name = self.try_parse_identifier()?;
> ```

There are 2 problems here:
1. it takes the identifier token, even if it doesn't eventually turn out to be an inline macro.
2. You use parse_token::<TerminalNot> as if you know it's gonna be there. This would return a missing token if not...
___
*[`crates/cairo-lang-parser/test_data/cairo_files/test1.cairo` line 60 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NbTvagDCLFe1zKnooPY:-NbTvagDCLFe1zKnooPZ:bhvhg8t) ([raw file](https://github.com/starkware-libs/cairo/blob/45c61add4afa2fbc86a0a85cbd32c24415c56b48/crates/cairo-lang-parser/test_data/cairo_files/test1.cairo#L60)):*
> ```Cairo
> type Generic<T> = super::other::OtherGeneric::<T>;
> 
> inline_item_macro!(x, y, z);
> ```

why not in a specific test with partial tree?

Also - add another test of an identifier without a bang after it.
___
*[`crates/cairo-lang-parser/test_data/expected_results/test2_tree_no_trivia` line 345 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NbTw56cEwuhxSYNUuEm:-NbTw56cEwuhxSYNUuEn:bkwlbdm) ([raw file](https://github.com/starkware-libs/cairo/blob/45c61add4afa2fbc86a0a85cbd32c24415c56b48/crates/cairo-lang-parser/test_data/expected_results/test2_tree_no_trivia#L345)):*
> ```
>     │       ├── bang: Missing
>     │       ├── arguments: Missing []
>     │       └── semicolon: Missing
> ```

here is an example of the problem I mentioned above.



_Code quote:_
```
    │   ├── child #3 (kind: ItemInlineMacro)
    │   │   ├── name (kind: TokenIdentifier): 'skipped'
    │   │   ├── bang: Missing
    │   │   ├── arguments: Missing []
    │   │   └── semicolon: Missing
    │   └── child #4 (kind: ItemInlineMacro)
    │       ├── name (kind: TokenIdentifier): 'tokens'
    │       ├── bang: Missing
    │       ├── arguments: Missing []
    │       └── semicolon: Missing
```
___
*[`crates/cairo-lang-syntax/src/node/helpers.rs` line 267 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NbTwQKZA0npVkExCNvD:-NbTwQKZA0npVkExCNvE:bbfx11f) ([raw file](https://github.com/starkware-libs/cairo/blob/45c61add4afa2fbc86a0a85cbd32c24415c56b48/crates/cairo-lang-syntax/src/node/helpers.rs#L267)):*
> ```XML
>             Item::TypeAlias(item) => item.attributes_elements(db),
>             Item::Missing(_) => vec![],
>             Item::InlineMacro(_) => vec![],
> ```

Isn't it possible to add attributes to inline macros?
___
*[`crates/cairo-lang-syntax-codegen/src/cairo_spec.rs` line 502 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NbTxJU99VYbvpCSgOXW:-NbTxJUABqYyvJwbBl9D:bndr92k) ([raw file](https://github.com/starkware-libs/cairo/blob/45c61add4afa2fbc86a0a85cbd32c24415c56b48/crates/cairo-lang-syntax-codegen/src/cairo_spec.rs#L502)):*
> ```XML
>         .node("name", "TerminalIdentifier")
>         .node("bang", "TerminalNot")
>         .node("arguments", "WrappedExprList")
> ```

Is it intentional that we support all kinds of brackets? If it is - add a test with [] and {} as well.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3877)* status: all files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 737 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NcNKKX-3-CoGe6iCz0-:-NcNKKX-3-CoGe6iCz00:b-41e1p2) ([raw file](https://github.com/starkware-libs/cairo/blob/6a479f6e013ef2b35249c8d7cab1f17b2ae635ed/crates/cairo-lang-parser/src/parser.rs#L737)):*
> ```XML
>             bang,
>             wrapped_expr_list,
>             semicolon,
> ```

the names should match the param names



_Suggestion:_
```XML
            attributes,
            name,
            bang,
            arguments,
            semicolon,
```
___
*[`crates/cairo-lang-parser/src/parser_test_data/item_macro` line 0 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NcNO30uD4lZg7-vWSeb:-NcNO30uD4lZg7-vWSec:b-7bqofc) ([raw file](https://github.com/starkware-libs/cairo/blob/6a479f6e013ef2b35249c8d7cab1f17b2ae635ed/crates/cairo-lang-parser/src/parser_test_data/item_macro#L0)):*
1. Rename the file to item_inline_macro
2. Add a test of a missing bang (e.g. "inline_macro(1,2,3)")
___
*[`crates/cairo-lang-parser/src/parser_test_data/item_macro` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NcNLPt2BZHZh51U5gPa:-NcNLPt2BZHZh51U5gPb:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6a479f6e013ef2b35249c8d7cab1f17b2ae635ed/crates/cairo-lang-parser/src/parser_test_data/item_macro#L1)):*
> ```
> //! > Test an ItemInlineMacro with parenthesis syntax tree
> ```





_Suggestion:_
```
parentheses
```
___
*[`crates/cairo-lang-parser/test_data/expected_results/test2_tree_no_trivia` line 357 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NcNMMOHDghqwl9SnKQ3:-NcNMMOHDghqwl9SnKQ4:b-r2eep8) ([raw file](https://github.com/starkware-libs/cairo/blob/6a479f6e013ef2b35249c8d7cab1f17b2ae635ed/crates/cairo-lang-parser/test_data/expected_results/test2_tree_no_trivia#L357)):*
> ```
>                ^
> 
> error: Missing token TerminalNot.
> ```

Need to change to TerminalBang (in a prior PR), it's confusing here with "not".



_Code quote:_
```
TerminalNot
```
___
*[`crates/cairo-lang-parser/test_data/expected_results/test2_tree_no_trivia` line 359 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NcNMZ3N1Sn_iJ8UYFUi:-NcNMZ3OEfq7s4Y_qXTt:b-ucf5qj) ([raw file](https://github.com/starkware-libs/cairo/blob/6a479f6e013ef2b35249c8d7cab1f17b2ae635ed/crates/cairo-lang-parser/test_data/expected_results/test2_tree_no_trivia#L359)):*
> ```
> error: Missing token TerminalNot.
>  --> test2.cairo:30:8
> skipped tokens
> ```

Now that they aren't skipped, can you change to "bad tokens"?



_Code quote:_
```
skipped tokens
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3877)* status: 6 of 21 files reviewed, 2 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-parser/test_data/expected_results/test2_tree_no_trivia` line 357 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NcNMMOHDghqwl9SnKQ3:-NcObNjJ1MC4a1xX0U47:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6a479f6e013ef2b35249c8d7cab1f17b2ae635ed/crates/cairo-lang-parser/test_data/expected_results/test2_tree_no_trivia#L357)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Need to change to TerminalBang (in a prior PR), it's confusing here with "not".
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/item_macro` line  at r2](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NcNO30uD4lZg7-vWSeb:-NcR1oo_7E90nWMxqGh5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6a479f6e013ef2b35249c8d7cab1f17b2ae635ed/crates/cairo-lang-parser/src/parser_test_data/item_macro#L)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

1. Rename the file to item_inline_macro
2. Add a test of a missing bang (e.g. "inline_macro(1,2,3)")
</blockquote></details>

Done.

**Comment by yuvalsw** [comment]
*[`crates/cairo-lang-parser/src/parser_test_data/attribute_errors` line 137 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NcS4C2VAdmqIBDJSvrB:-NcS4C2VAdmqIBDJSvrC:bcnq83x) ([raw file](https://github.com/starkware-libs/cairo/blob/fc6794a5d87cded9d0aa74258fe46f3aaaeaff7c/crates/cairo-lang-parser/src/parser_test_data/attribute_errors#L137)):*
> ```
> //! > cairo_code
> #[aaa]
> [bbb]
> ```

make it skipped, as discussed

**Review by yuvalsw — COMMENTED** [review]
> Reviewed 15 of 15 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3877)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-parser/src/parser_test_data/attribute_errors` line 68 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NcRezJr1hM2RY0Kv_oQ:-NcRezJr1hM2RY0Kv_oR:bx6d64s) ([raw file](https://github.com/starkware-libs/cairo/blob/fc6794a5d87cded9d0aa74258fe46f3aaaeaff7c/crates/cairo-lang-parser/src/parser_test_data/attribute_errors#L68)):*
> ```
> 
> //! > test_runner_name
> test_partial_parser_tree(allow_diagnostics: true)
> ```

Please add to all



_Code quote:_
```
(allow_diagnostics: true)
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3877)* status: 6 of 22 files reviewed, 1 unresolved discussion (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser_test_data/attribute_errors` line 137 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NcS4C2VAdmqIBDJSvrB:-NcZMQvW0q8RFVB1_9yR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fc6794a5d87cded9d0aa74258fe46f3aaaeaff7c/crates/cairo-lang-parser/src/parser_test_data/attribute_errors#L137)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

make it skipped, as discussed
</blockquote></details>

Done.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3877)* status: all files reviewed, 8 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 208 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NcaRq5ZDuBwqrdmwy7q:-NcaRq5ZDuBwqrdmwy7r:b2m1ibl) ([raw file](https://github.com/starkware-libs/cairo/blob/c2ec2b6dcce366afb11adbb1ea51a04bf1f581e4/crates/cairo-lang-parser/src/parser.rs#L208)):*
> ```XML
>                 // We take the identifier to check if the next token is a `!`. If it is, we assume
>                 // that a macro is following and handle it similarly to any other
>                 // top-level item. If not we skip the identifier. TODO(Gil):
> ```

1. add: "`take_raw` is used here since it's not yet known whether the token is going to be `take`n or `skip`ped."
2. TODO in a separate line.
___
*[`crates/cairo-lang-parser/src/parser.rs` line 213 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NcaRarl5f8hWeSyCGrV:-NcaRarl5f8hWeSyCGrW:b-8rlzqc) ([raw file](https://github.com/starkware-libs/cairo/blob/c2ec2b6dcce366afb11adbb1ea51a04bf1f581e4/crates/cairo-lang-parser/src/parser.rs#L213)):*
> ```XML
>                 match self.peek().kind {
>                     SyntaxKind::TerminalNot => {
>                         let macro_name = self.add_trivia_to_terminal::<TerminalIdentifier>(ident);
> ```

please state that this is the completion of `take` and that below is the completion of `skip`.
___
*[`crates/cairo-lang-parser/src/parser.rs` line 223 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NcaSO546Kn5xC4RvoRL:-NcaSO546Kn5xC4RvoRM:b-nge6s3) ([raw file](https://github.com/starkware-libs/cairo/blob/c2ec2b6dcce366afb11adbb1ea51a04bf1f581e4/crates/cairo-lang-parser/src/parser.rs#L223)):*
> ```XML
>                             },
>                         );
>                         Err(TryParseFailure::DoNothing)
> ```

add:
// The token is already skipped, so it should not be skipped in the caller.
___
*[`crates/cairo-lang-parser/src/parser.rs` line 2106 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NcaSzfW7TLLEHMXh-vU:-NcaSzfW7TLLEHMXh-vV:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c2ec2b6dcce366afb11adbb1ea51a04bf1f581e4/crates/cairo-lang-parser/src/parser.rs#L2106)):*
> ```XML
> 
>     /// Appends the given terminal to the pending trivia and reports a diagnostic. Used for skipping
>     /// a taken token.
> ```





_Suggestion:_
```XML
a taken (`take_raw`) token.
```
___
*[`crates/cairo-lang-parser/src/parser.rs` line 215 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3877#-Ncaai8G3HyP9kWWTAWP:-Ncaai8G3HyP9kWWTAWQ:baxwxsy) ([raw file](https://github.com/starkware-libs/cairo/blob/0f3ea7bf0fbedc8b803ef513f19094f3ddca83f0/crates/cairo-lang-parser/src/parser.rs#L215)):*
> ```XML
>                         let macro_name = self.add_trivia_to_terminal::<TerminalIdentifier>(ident);
>                         Ok(self.expect_item_inline_macro(attributes, macro_name).into())
>                     }
> ```

suggestion: to have a "did you mean macro" thing as I suggested below, we can match here for a lparen, in which case we still skip as in the _ arm, but also add another "did you mean macro" diagnostic.
___
*[`crates/cairo-lang-parser/src/parser_test_data/item_inline_macro` line 311 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NcaY8wmAic4X-S7RYD3:-NcaY8wmAic4X-S7RYD4:be2zoys) ([raw file](https://github.com/starkware-libs/cairo/blob/c2ec2b6dcce366afb11adbb1ea51a04bf1f581e4/crates/cairo-lang-parser/src/parser_test_data/item_inline_macro#L311)):*
> ```
> //! > expected_tree
> └── root (kind: SyntaxFile)
>     ├── items (kind: ItemList)
> ```

make this the top_level_kind
same below



_Code quote:_
```
 ItemList)
```
___
*[`crates/cairo-lang-parser/src/parser_test_data/item_inline_macro` line 318 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NcaY3aCCfyDiZ3c-Br1:-NcaY3aCCfyDiZ3c-Br2:b-kklj4g) ([raw file](https://github.com/starkware-libs/cairo/blob/c2ec2b6dcce366afb11adbb1ea51a04bf1f581e4/crates/cairo-lang-parser/src/parser_test_data/item_inline_macro#L318)):*
> ```
>     │   │   ├── arguments: Missing []
>     │   │   └── semicolon: Missing
>     │   └── child #1 (kind: FunctionWithBody)
> ```

add to ignored_kinds
same below



_Code quote:_
```
FunctionWithBody
```
___
*[`crates/cairo-lang-parser/src/parser_test_data/item_inline_macro` line 483 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NcaYwTe38Y5hu5DkP9T:-NcaYwTe38Y5hu5DkP9U:blixz31) ([raw file](https://github.com/starkware-libs/cairo/blob/0f3ea7bf0fbedc8b803ef513f19094f3ddca83f0/crates/cairo-lang-parser/src/parser_test_data/item_inline_macro#L483)):*
> ```
>  --> dummy_file.cairo:1:1
> identifier(x)
> ^********^
> ```

This is not great, we'd like a "did you mean macro" thing here. But I'm not sure we can currently do it well without the better lookahead mechanism



_Code quote:_
```
error: Skipped tokens. Expected: Const/Module/Use/FreeFunction/ExternFunction/ExternType/Trait/Impl/Struct/Enum/TypeAlias/InlineMacro.
 --> dummy_file.cairo:1:1
identifier(x)
^********^
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3877)* status: all files reviewed, 5 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 208 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NcaRq5ZDuBwqrdmwy7q:-NcaeqD6EBNXnDI2gqS_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c2ec2b6dcce366afb11adbb1ea51a04bf1f581e4/crates/cairo-lang-parser/src/parser.rs#L208)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

1. add: "`take_raw` is used here since it's not yet known whether the token is going to be `take`n or `skip`ped."
2. TODO in a separate line.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser.rs` line 213 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NcaRarl5f8hWeSyCGrV:-Ncaf8B330ehISeU9Ote:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c2ec2b6dcce366afb11adbb1ea51a04bf1f581e4/crates/cairo-lang-parser/src/parser.rs#L213)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

please state that this is the completion of `take` and that below is the completion of `skip`.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser.rs` line 223 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NcaSO546Kn5xC4RvoRL:-Ncaky6v5VgLqygNb3uB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c2ec2b6dcce366afb11adbb1ea51a04bf1f581e4/crates/cairo-lang-parser/src/parser.rs#L223)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

add:
// The token is already skipped, so it should not be skipped in the caller.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser.rs` line 2106 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NcaSzfW7TLLEHMXh-vU:-Ncal4HdDyJQy_T8OHjY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c2ec2b6dcce366afb11adbb1ea51a04bf1f581e4/crates/cairo-lang-parser/src/parser.rs#L2106)):*
> ```XML
> 
>     /// Appends the given terminal to the pending trivia and reports a diagnostic. Used for skipping
>     /// a taken token.
> ```

Done.
___
*[`crates/cairo-lang-parser/src/parser.rs` line 215 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3877#-Ncaai8G3HyP9kWWTAWP:-NcakrrH8qrCZJUEn5sd:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0f3ea7bf0fbedc8b803ef513f19094f3ddca83f0/crates/cairo-lang-parser/src/parser.rs#L215)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

suggestion: to have a "did you mean macro" thing as I suggested below, we can match here for a lparen, in which case we still skip as in the _ arm, but also add another "did you mean macro" diagnostic.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/item_inline_macro` line 483 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NcaYwTe38Y5hu5DkP9T:-NcalXgf0OHIh4jbMXm6:bek9485) ([raw file](https://github.com/starkware-libs/cairo/blob/0f3ea7bf0fbedc8b803ef513f19094f3ddca83f0/crates/cairo-lang-parser/src/parser_test_data/item_inline_macro#L483)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

This is not great, we'd like a "did you mean macro" thing here. But I'm not sure we can currently do it well without the better lookahead mechanism
</blockquote></details>

Done.
It wasn't hard to add since the identifier is taken and we can check if the next token is a paren, however we check if the paren is closed or use to arg list.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3877)* status: all files reviewed, 8 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-parser/src/diagnostic.rs` line 65 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NcbGXfW5teiFGjRx7m0:-NcbGXfW5teiFGjRx7m1:b-xsxrfp) ([raw file](https://github.com/starkware-libs/cairo/blob/50bc2d31921bdbc3f155c3632a6505859695f48a/crates/cairo-lang-parser/src/diagnostic.rs#L65)):*
> ```XML
>                                                             brackets, or braces."
>                 .to_string(),
>             ParserDiagnosticKind::ItemInlineMacroWithoutBang { identifier, paren_type } => {
> ```

bracket is considered the group name for those: https://en.wikipedia.org/wiki/Bracket



_Code quote:_
```XML
paren
```
___
*[`crates/cairo-lang-parser/src/diagnostic.rs` line 83 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3877#-Ncb9Wmy0MtzvssUQj3S:-Ncb9Wmy0MtzvssUQj3T:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/50bc2d31921bdbc3f155c3632a6505859695f48a/crates/cairo-lang-parser/src/diagnostic.rs#L83)):*
> ```XML
>                     }
>                 )
>             }
> ```





_Suggestion:_
```XML
            ParserDiagnosticKind::ItemInlineMacroWithoutBang { identifier, paren_type } => {
                let (left, right) = match paren_type {
                    SyntaxKind::TerminalLParen => ("(", ")")
                    SyntaxKind::TerminalLBrack => ("[","]")
                    SyntaxKind::TerminalLBrace => ("{","}")
                    _ => "",
                };
                format!(
                    "Expected a bang ('!') after the identifier '{identifier}' to start an inline \
                     macro.\n
                    Did you mean to write `{identifier}!{left}...{right}'?",
                )
            }
```
___
*[`crates/cairo-lang-parser/src/parser.rs` line 211 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NcbA6_D3I3YXC-43tOD:-NcbA6_D3I3YXC-43tOE:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/50bc2d31921bdbc3f155c3632a6505859695f48a/crates/cairo-lang-parser/src/parser.rs#L211)):*
> ```XML
>                 // since it is not yet known if the identifier will be taken as a part of a macro,
>                 // or skipped.
>                 //
> ```





_Suggestion:_
```XML
                // top-level item. If not we skip the identifier. 'take_raw' is used here
                // since it is not yet known if the identifier would be taken as a part of a macro,
                // or skipped.
                //
```
___
*[`crates/cairo-lang-parser/src/parser.rs` line 237 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NcbDDBL2P5xXUbG9fij:-NcbDDBL2P5xXUbG9fik:b-6i93ka) ([raw file](https://github.com/starkware-libs/cairo/blob/50bc2d31921bdbc3f155c3632a6505859695f48a/crates/cairo-lang-parser/src/parser.rs#L237)):*
> ```XML
>                                     end: self.offset.add_width(self.current_width),
>                                 },
>                             });
> ```

I think that in this case we should parse a macro. So: complete *take*ing the identifier, and call expect_item_inline_macro with a missing terminal not.
(make sure to not report missing for the !, as we have this custom error now)

With this, it would make more sense to put the opening-bracket condition above in the arm guard.
___
*[`crates/cairo-lang-parser/src/parser_test_data/item_inline_macro` line 483 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NcaYwTe38Y5hu5DkP9T:-NcbFeDw6aMDUPpLZHkq:b-cul95o) ([raw file](https://github.com/starkware-libs/cairo/blob/0f3ea7bf0fbedc8b803ef513f19094f3ddca83f0/crates/cairo-lang-parser/src/parser_test_data/item_inline_macro#L483)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Done.
It wasn't hard to add since the identifier is taken and we can check if the next token is a paren, however we check if the paren is closed or use to arg list.
</blockquote></details>

yes, but this is the same as we do if there was a ! there. We simply "guess" here that the user meant to right the ! and put it there for them (along with the error).
___
*[`crates/cairo-lang-parser/src/parser_test_data/item_inline_macro` line 184 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NcbFCES5yarHEHBFxjn:-NcbFCES5yarHEHBFxjo:b-s678ik) ([raw file](https://github.com/starkware-libs/cairo/blob/50bc2d31921bdbc3f155c3632a6505859695f48a/crates/cairo-lang-parser/src/parser_test_data/item_inline_macro#L184)):*
> ```
> 
> //! > cairo_code
> inline_macro(1,2,3);
> ```

please remove 3, it just too many errors which don't help too much to the purpose of the test.



_Code quote:_
```
inline_macro(1,2,3);
```
___
*[`crates/cairo-lang-parser/src/parser_test_data/item_inline_macro` line 186 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NcbDykg7udipwWOdQi2:-NcbDykg7udipwWOdQi3:bue42nw) ([raw file](https://github.com/starkware-libs/cairo/blob/50bc2d31921bdbc3f155c3632a6505859695f48a/crates/cairo-lang-parser/src/parser_test_data/item_inline_macro#L186)):*
> ```
> inline_macro(1,2,3);
> inline_macro[];
> inline_macro{};
> ```

separate test for each please



_Code quote:_
```
inline_macro[];
inline_macro{};
```
___
*[`crates/cairo-lang-parser/src/parser_test_data/item_inline_macro` line 194 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NcbEylRDs7fRHc1EpwO:-NcbEylRDs7fRHc1EpwP:b-3qnc53) ([raw file](https://github.com/starkware-libs/cairo/blob/50bc2d31921bdbc3f155c3632a6505859695f48a/crates/cairo-lang-parser/src/parser_test_data/item_inline_macro#L194)):*
> ```
> 
> //! > expected_diagnostics
> error: Expected a bang ('!') after the identifier 'inline_macro' to start an inline macro.
> ```

suggestion



_Suggestion:_
```
Expected a `!` after the identifier 
```
___
*[`crates/cairo-lang-parser/src/parser_test_data/item_inline_macro` line 196 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NcbE5d15S4GFs5tvz2v:-NcbE5d15S4GFs5tvz2w:b9injr1) ([raw file](https://github.com/starkware-libs/cairo/blob/50bc2d31921bdbc3f155c3632a6505859695f48a/crates/cairo-lang-parser/src/parser_test_data/item_inline_macro#L196)):*
> ```
> error: Expected a bang ('!') after the identifier 'inline_macro' to start an inline macro.
> 
>                     Did you mean to write `inline_macro!(...)'?
> ```

Maybe "did you forget a `!` after 'inline_macro'?"

Also, I would remove the '\n's and whitespaces.



_Code quote:_
```
Did you mean to write `inline_macro!(...)'?
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3877)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-parser/src/diagnostic.rs` line 65 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NcbGXfW5teiFGjRx7m0:-NcbllxmBaBIkDK_jJyr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/50bc2d31921bdbc3f155c3632a6505859695f48a/crates/cairo-lang-parser/src/diagnostic.rs#L65)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

bracket is considered the group name for those: https://en.wikipedia.org/wiki/Bracket
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser.rs` line 237 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NcbDDBL2P5xXUbG9fij:-NcnNWEI1VmAi5VpGtmv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/50bc2d31921bdbc3f155c3632a6505859695f48a/crates/cairo-lang-parser/src/parser.rs#L237)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I think that in this case we should parse a macro. So: complete *take*ing the identifier, and call expect_item_inline_macro with a missing terminal not.
(make sure to not report missing for the !, as we have this custom error now)

With this, it would make more sense to put the opening-bracket condition above in the arm guard.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/item_inline_macro` line 186 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NcbDykg7udipwWOdQi2:-NcnOAJv82J0eghMeMgq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/50bc2d31921bdbc3f155c3632a6505859695f48a/crates/cairo-lang-parser/src/parser_test_data/item_inline_macro#L186)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

separate test for each please
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/item_inline_macro` line 196 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NcbE5d15S4GFs5tvz2v:-NcnOUvvB0Z0InNR8GAc:b-ms4crl) ([raw file](https://github.com/starkware-libs/cairo/blob/50bc2d31921bdbc3f155c3632a6505859695f48a/crates/cairo-lang-parser/src/parser_test_data/item_inline_macro#L196)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Maybe "did you forget a `!` after 'inline_macro'?"

Also, I would remove the '\n's and whitespaces.
</blockquote></details>

I think it is less clear if the whole statement won't appear.

**Review by yuvalsw — COMMENTED** [review]
Merged in https://github.com/starkware-libs/cairo/pull/3966 with a minor fix over this.

> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3877#-:-NcqvoaKCwV2BihNXDjA:b43j5lc)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3877)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3877#-NcqyR5E9oqdwVejC3uc:-NcqyR5E9oqdwVejC3ud:b-7919dh) (no related file):*
Merged - removing this from my attention list.

___

**Comment by yuvalsw** [comment]
Merged in https://github.com/starkware-libs/cairo/pull/3966 with a minor fix over this.

**Pull request closed without merging**
