### PR TITLE
Document match expressions.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3082)

### CODE REVIEW

**Review by JameStark — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3082)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/match-expressions.adoc` line 10 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3082#-NUziVqrBA8uXYdMlClq:-NUziVqrBA8uXYdMlClr:b-ypfl2a) ([raw file](https://github.com/starkware-libs/cairo/blob/2190d356f6891a221d97edfac220578554dddc80/docs/reference/src/components/cairo/modules/language_constructs/pages/match-expressions.adoc#L10)):*
> ```AsciiDoc
> A match expression starts with the link:keywords.adoc[keyword] 'match'
> followed by an expression and a list of arms.
> Each arm begins with a link:patterns.adoc[pattern] which is followed by the '=>' operator, an
> ```

Use ``



_Code quote:_
```AsciiDoc
'=>'
```

**Review by JameStark — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3082)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/match-expressions.adoc` line 16 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3082#-NUzifKvBL2nkomdrgt8:-NUzifKvBL2nkomdrgt9:b-ypfl2a) ([raw file](https://github.com/starkware-libs/cairo/blob/2190d356f6891a221d97edfac220578554dddc80/docs/reference/src/components/cairo/modules/language_constructs/pages/match-expressions.adoc#L16)):*
> ```AsciiDoc
> The pattern in a given arm may introduce link:variables.adoc[variables] that can be used in
> expression of the said arm.
> If the pattern contains variables that are unused in the expression, then the wildcard '_' can be \
> ```

Use ``



_Code quote:_
```AsciiDoc
'_'
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3082)* status: all files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware and @JameStark)

___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/match-expressions.adoc` line 23 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3082#-NV-0HAx3hmo938y22GU:-NV-0HAx3hmo938y22GV:bhc3cub) ([raw file](https://github.com/starkware-libs/cairo/blob/a972352500ea96a7e69bfe74ae6df83240cd09f5/docs/reference/src/components/cairo/modules/language_constructs/pages/match-expressions.adoc#L23)):*
> ```AsciiDoc
> A match expression is evaluated by evaluating the expression and then matching the value against
> the patterns in the arms in order. The first arm whose pattern matches the value of the expression
> is executed and the result of the expression in the arm is returned as the result of the match.
> ```

we currently don't support non-exhaustive matching, and variants must be matched at declaration order.



_Code quote:_
```AsciiDoc
the patterns in the arms in order. The first arm whose pattern matches the value of the expression
is executed and the result of the expression in the arm is returned as the result of the match.
```
___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/match-expressions.adoc` line 26 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3082#-NV-0UVp-Xiw21IhQ2HL:-NV-0UVp-Xiw21IhQ2HM:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a972352500ea96a7e69bfe74ae6df83240cd09f5/docs/reference/src/components/cairo/modules/language_constructs/pages/match-expressions.adoc#L26)):*
> ```AsciiDoc
> [Note]
> ====
> All the arms that don't break the control flow must evalutate to the same type.
> ```





_Suggestion:_
```AsciiDoc
All the arms that don't break the control flow must evaluate to the same type.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/match-expressions.adoc` line 23 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3082#-NV-0HAx3hmo938y22GU:-NV-1CNdEleouaRbdt4o:b-3qpfie) ([raw file](https://github.com/starkware-libs/cairo/blob/a972352500ea96a7e69bfe74ae6df83240cd09f5/docs/reference/src/components/cairo/modules/language_constructs/pages/match-expressions.adoc#L23)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

we currently don't support non-exhaustive matching, and variants must be matched at declaration order.
</blockquote></details>

It is mentioned below.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3082)* status: all files reviewed, 7 unresolved discussions (waiting on @JameStark and @orizi)

___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/match-expressions.adoc` line 26 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3082#-NUzivRuEcb7qFFPZU0D:-NV-1KZY2mSvGuMjJhmZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2190d356f6891a221d97edfac220578554dddc80/docs/reference/src/components/cairo/modules/language_constructs/pages/match-expressions.adoc#L26)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

We can highlight notes using this syntax

[NOTE]
====
Expressions in all the arms must evalutate to the same type.

An exception to the rule above is an arm breaks the control flow and either
link:return-expression.adoc[returns] or link:panic.adoc[panics].
====
</blockquote></details>

Done.
___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/match-expressions.adoc` line 26 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3082#-NV-0UVp-Xiw21IhQ2HL:-NV-1KAU8-FvIW_7MPYP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a972352500ea96a7e69bfe74ae6df83240cd09f5/docs/reference/src/components/cairo/modules/language_constructs/pages/match-expressions.adoc#L26)):*
> ```AsciiDoc
> [Note]
> ====
> All the arms that don't break the control flow must evalutate to the same type.
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3082)* status: 1 of 2 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware and @JameStark)

___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/match-expressions.adoc` line 23 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3082#-NV-0HAx3hmo938y22GU:-NV-1elVBvyV70HZPvCV:b-5l0fu1) ([raw file](https://github.com/starkware-libs/cairo/blob/a972352500ea96a7e69bfe74ae6df83240cd09f5/docs/reference/src/components/cairo/modules/language_constructs/pages/match-expressions.adoc#L23)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

It is mentioned below.
</blockquote></details>

maybe it is - but i'm yet to know if we can know that we'd support the `first` arm that matches.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3082)* status: all files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware and @JameStark)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3082)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/match-expressions.adoc` line 23 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3082#-NV-0HAx3hmo938y22GU:-NV-BUeFBRgFljztWAts:b5e6cc4) ([raw file](https://github.com/starkware-libs/cairo/blob/a972352500ea96a7e69bfe74ae6df83240cd09f5/docs/reference/src/components/cairo/modules/language_constructs/pages/match-expressions.adoc#L23)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe it is - but i'm yet to know if we can know that we'd support the `first` arm that matches.
</blockquote></details>

It is needed to explain the match on felt252.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3082)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3082#-:-NV-hXevDr_iqd4bRgBM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
