### PR TITLE
Use deref in storage access, and refactor storage.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5857)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 74 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5857)* status: 6 of 74 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware)

___
*[`corelib/src/ops/deref.cairo` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5857#-O08IbGKBKS3n0bNYKk7:-O08IbGKBKS3n0bNYKk8:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ce42dc50efd98b26bbe5899ea709b16fda74eb25/corelib/src/ops/deref.cairo#L18)):*
> ```Cairo
> 
> /// A helper trait for dereferencing a snapshot of a type. Should not be implemented for copyable
> /// types.
> ```





_Suggestion:_
```Cairo
/// A helper trait for dereferencing a snapshot of a type. Would not be used for copyable
/// types.
```
___
*[`corelib/src/ops/deref.cairo` line 25 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5857#-O08IWRz06Wah5URGeyB:-O08IWS-957zmnGAMtTa:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ce42dc50efd98b26bbe5899ea709b16fda74eb25/corelib/src/ops/deref.cairo#L25)):*
> ```Cairo
> 
> /// Implementation of Deref for snapshots that implement SnapshotDeref.
> impl SnapshotDerefHelper<T, +SnapshotDeref<T>> of Deref<@T> {
> ```





_Suggestion:_
```Cairo
impl SnapshotDerefHelper<T, +SnapshotDeref<T>, -Copy<T>> of Deref<@T> {
```
___
*[`corelib/src/starknet/storage.cairo` line 204 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5857#-O08JZ_bAw7xajFq6OfK:-O08JZ_bAw7xajFq6OfL:b-507jvc) ([raw file](https://github.com/starkware-libs/cairo/blob/ce42dc50efd98b26bbe5899ea709b16fda74eb25/corelib/src/starknet/storage.cairo#L204)):*
> ```Cairo
>     type Key;
>     type Value;
> }
> ```

also consider adding a TODO to add a Hash associated impl for Key instead.



_Suggestion:_
```Cairo
/// A trait for making a map like type support implement the `StoragePathEntry` trait.
trait EntryInfo<T> {
    type Key;
    type Value;
}
```
___
*[`corelib/src/starknet/storage.cairo` line 214 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5857#-O08JjNU4ris_CFEKrdK:-O08JjNU4ris_CFEKrdL:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ce42dc50efd98b26bbe5899ea709b16fda74eb25/corelib/src/starknet/storage.cairo#L214)):*
> ```Cairo
> impl EntryableStoragePathEntry<
>     T, +Entryable<T>, +core::hash::Hash<Entryable::<T>::Key, StoragePathHashState>
> > of StoragePathEntry<StoragePath<T>> {
> ```





_Suggestion:_
```Cairo
/// Implement `StoragePathEntry` for types with `EntryInfo` if their key implements `Hash`.
impl EntryableStoragePathEntry<
    T, +Entryable<T>, +core::hash::Hash<Entryable::<T>::Key, StoragePathHashState>
> of StoragePathEntry<StoragePath<T>> {
```
___
*[`corelib/src/starknet/storage.cairo` line 239 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5857#-O08K9fM1BKvA2uvEa8L:-O08K9fM1BKvA2uvEa8M:b-4hn2ah) ([raw file](https://github.com/starkware-libs/cairo/blob/ce42dc50efd98b26bbe5899ea709b16fda74eb25/corelib/src/starknet/storage.cairo#L239)):*
> ```Cairo
>     type Key = EntryImpl::Key;
>     type Value = Mutable<EntryImpl::Value>;
>     #[inline(always)]
> ```

remove if has no effect.
(as well as anywhere else)



_Code quote:_
```Cairo
    #[inline(always)]
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 74 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5857)* status: 36 of 74 files reviewed, 8 unresolved discussions (waiting on @gilbens-starkware)

___
*[`tests/bug_samples/issue3153.cairo` line 87 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5857#-O08NkG0864jZzunH-hZ:-O08NkG0864jZzunH-h_:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/ce42dc50efd98b26bbe5899ea709b16fda74eb25/tests/bug_samples/issue3153.cairo#L87)):*
> ```Cairo
> mod test_contract {
>     use super::Proposal;
> ```

?
___
*[`tests/bug_samples/issue3345.cairo` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5857#-O08NlDY1kMHWOupmk2Y:-O08NlDY1kMHWOupmk2Z:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/ce42dc50efd98b26bbe5899ea709b16fda74eb25/tests/bug_samples/issue3345.cairo#L17)):*
> ```Cairo
>     use super::ITree;
> ```

?

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 74 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5857)* status: 38 of 74 files reviewed, 10 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5857#-O08Pkps5ZFwhX3nKF8f:-O08Pkps5ZFwhX3nKF8g:b-63rwij) ([raw file](https://github.com/starkware-libs/cairo/blob/ce42dc50efd98b26bbe5899ea709b16fda74eb25/crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs#L39)):*
> ```XML
>                 StorableStoragePointerReadAccess, StorableStoragePointerWriteAccess
>             };
>             use starknet::storage::Map as LegacyMap;
> ```

add a todo to a deprecation here.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 211 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5857#-O08Pqj16JIE-20jLDU4:-O08Pqj16JIE-20jLDU5:b87ujoz) ([raw file](https://github.com/starkware-libs/cairo/blob/ce42dc50efd98b26bbe5899ea709b16fda74eb25/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L211)):*
> ```XML
>                     StorableStoragePointerReadAccess, StorableStoragePointerWriteAccess
>                 }};
>                 use starknet::storage::Map as LegacyMap;
> ```

todo deperacated.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5857)* status: 38 of 74 files reviewed, 10 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/ops/deref.cairo` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5857#-O08IbGKBKS3n0bNYKk7:-O08SUOZ2vf4xO6vPxhN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ce42dc50efd98b26bbe5899ea709b16fda74eb25/corelib/src/ops/deref.cairo#L18)):*
> ```Cairo
> 
> /// A helper trait for dereferencing a snapshot of a type. Should not be implemented for copyable
> /// types.
> ```

Done.
___
*[`corelib/src/ops/deref.cairo` line 25 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5857#-O08IWRz06Wah5URGeyB:-O08SUez0RyZTPQD9156:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ce42dc50efd98b26bbe5899ea709b16fda74eb25/corelib/src/ops/deref.cairo#L25)):*
> ```Cairo
> 
> /// Implementation of Deref for snapshots that implement SnapshotDeref.
> impl SnapshotDerefHelper<T, +SnapshotDeref<T>> of Deref<@T> {
> ```

Done.
___
*[`corelib/src/starknet/storage.cairo` line 204 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5857#-O08JZ_bAw7xajFq6OfK:-O08QifP7bK_kA3eZd8-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ce42dc50efd98b26bbe5899ea709b16fda74eb25/corelib/src/starknet/storage.cairo#L204)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

also consider adding a TODO to add a Hash associated impl for Key instead.
</blockquote></details>

Done.
___
*[`corelib/src/starknet/storage.cairo` line 214 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5857#-O08JjNU4ris_CFEKrdK:-O08QiUiDQJqDrUj0v9E:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ce42dc50efd98b26bbe5899ea709b16fda74eb25/corelib/src/starknet/storage.cairo#L214)):*
> ```Cairo
> impl EntryableStoragePathEntry<
>     T, +Entryable<T>, +core::hash::Hash<Entryable::<T>::Key, StoragePathHashState>
> > of StoragePathEntry<StoragePath<T>> {
> ```

Done.
___
*[`corelib/src/starknet/storage.cairo` line 239 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5857#-O08K9fM1BKvA2uvEa8L:-O08RHO13JmdRFE4_H-U:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ce42dc50efd98b26bbe5899ea709b16fda74eb25/corelib/src/starknet/storage.cairo#L239)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove if has no effect.
(as well as anywhere else)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5857#-O08Pkps5ZFwhX3nKF8f:-O08Ra_E1wPKm30uubpt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ce42dc50efd98b26bbe5899ea709b16fda74eb25/crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs#L39)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add a todo to a deprecation here.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 211 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5857#-O08Pqj16JIE-20jLDU4:-O08RbeoDQtxMnAGHHw4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ce42dc50efd98b26bbe5899ea709b16fda74eb25/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L211)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

todo deperacated.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/test_data/account__account.sierra` line 1032 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5857#-O08NN854gi3MNqhhCvZ:-O08SmePBvXeGRr8Dpzo:bcjhaqo) ([raw file](https://github.com/starkware-libs/cairo/blob/4c43ba3bf0cfc5debc6e63939fa24992846197ca/crates/cairo-lang-starknet/test_data/account__account.sierra#L1032)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is a lost const - shouldn't happen.
</blockquote></details>

Not sure I understand.
___
*[`tests/bug_samples/issue3153.cairo` line 87 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5857#-O08NkG0864jZzunH-hZ:-O08RtDK3I0SRu3QJ1Gf:b-wkep5y) ([raw file](https://github.com/starkware-libs/cairo/blob/ce42dc50efd98b26bbe5899ea709b16fda74eb25/tests/bug_samples/issue3153.cairo#L87)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

I added a temporary `use LegacyMap` here, removed it with a bad search and replace, and then fixed only in the regular contract and forgot about the issues.
___
*[`tests/bug_samples/issue3345.cairo` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5857#-O08NlDY1kMHWOupmk2Y:-O08SW0l3Vz0y2j1KXsm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ce42dc50efd98b26bbe5899ea709b16fda74eb25/tests/bug_samples/issue3345.cairo#L17)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 4 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5857)* status: 38 of 74 files reviewed, 3 unresolved discussions

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5857)* status: 40 of 74 files reviewed, 1 unresolved discussion

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5857)* status: 40 of 74 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/test_data/account__account.sierra` line 1032 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5857#-O08NN854gi3MNqhhCvZ:-O08U4uD7Fs-lvEuWcKy:b5jsm2i) ([raw file](https://github.com/starkware-libs/cairo/blob/4c43ba3bf0cfc5debc6e63939fa24992846197ca/crates/cairo-lang-starknet/test_data/account__account.sierra#L1032)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Not sure I understand.
</blockquote></details>

the previous constant was an address - now a conversion occurs.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5857)* status: 39 of 74 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/test_data/account__account.sierra` line 1032 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5857#-O08NN854gi3MNqhhCvZ:-O09EmCC0-Ob9xx4f0Bv:b-7g6inw) ([raw file](https://github.com/starkware-libs/cairo/blob/4c43ba3bf0cfc5debc6e63939fa24992846197ca/crates/cairo-lang-starknet/test_data/account__account.sierra#L1032)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the previous constant was an address - now a conversion occurs.
</blockquote></details>

Added a todo.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 34 of 74 files at r1, 27 of 27 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5857)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/test_data/mintable.cairo` line 75 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5857#-O09NmFb0R9DtI18Dz0r:-O09NmFb0R9DtI18Dz0s:b-l6hdjr) ([raw file](https://github.com/starkware-libs/cairo/blob/d8dee11321f291bdfeb9c3ddc40ef6e4386dcb2a/crates/cairo-lang-starknet/test_data/mintable.cairo#L75)):*
> ```Cairo
>     use starknet::{ContractAddress, get_caller_address, contract_address_const};
> ```

revert

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5857#-:-O09QC9tCFPI10fbjhUP:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 18 of 18 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5857)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 26 of 26 files at r5, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5857#-:-O09eT8w7rwXEUaEnHrQ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5857)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
