### PR TITLE
Added is_must_use methods

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4593)

### CODE REVIEW

**Comment by yuvalsw** [comment]
change target branch

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4593)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 191 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4593#-NlwhMSiEbVrzDe3LuZT:-NlwhMSiEbVrzDe3LuZU:b4iu88u) ([raw file](https://github.com/starkware-libs/cairo/blob/6e16e2b123c3c92a48ae829b504cf8060ec2c31e/crates/cairo-lang-semantic/src/types.rs#L191)):*
> ```XML
>         }
>     }
>     pub fn is_must_use(&self, db: &dyn SemanticGroup) -> Maybe<bool> {
> ```

doc it means "has the attribute `must_use`.
___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4593#-NlwhWB69-BZDnXtDpV2:-NlwhWB69-BZDnXtDpV3:b-7ropln) ([raw file](https://github.com/starkware-libs/cairo/blob/6e16e2b123c3c92a48ae829b504cf8060ec2c31e/crates/cairo-lang-semantic/src/items/functions.rs#L146)):*
> ```XML
>         }
>     }
>     pub fn is_must_use(&self, db: &dyn SemanticGroup) -> Maybe<bool> {
> ```

ditto

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4593)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 191 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4593#-NlwhMSiEbVrzDe3LuZT:-NlwqH5-69WqJMG4vDWE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6e16e2b123c3c92a48ae829b504cf8060ec2c31e/crates/cairo-lang-semantic/src/types.rs#L191)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc it means "has the attribute `must_use`.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4593#-NlwhWB69-BZDnXtDpV2:-NlwqHPf2S3u-QEgv2FH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6e16e2b123c3c92a48ae829b504cf8060ec2c31e/crates/cairo-lang-semantic/src/items/functions.rs#L146)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4593#-:-Nlwz34CElCTFQikEvub:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
