### PR TITLE
feat: add PartialOrdSnap impl

### LINKED ISSUE #5646: feat: add a `PartialOrdSnap` impl in the corelib
# Feature Request

My problem is that `+PartialOrd<T>` currently doesn't imply `+PartialOrd<@T>`. Which is inconsistent because it is implied for `PartialEq`. 
The reason being this specific impl:
https://github.com/starkware-libs/cairo/blob/68b7072783c7963e4ca17c88d9928dd5dc12db96/corelib/src/traits.cairo#L61-L65

I think this should be extended to `PartialOrd` for sure and most likely to other traits in the corelib, like `Add` and so on.

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

No. It is quite simple and will do for a great set of OnlyDust contributions, once the lib owner decides which trait are concerned

### PR DESCRIPTION
**Pull request by tdelabro**
closes #5646 until we address #5694

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5723)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5723)* status: all files reviewed, 1 unresolved discussion (waiting on @tdelabro)

___
*[`corelib/src/traits.cairo` line 122 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5723#-NzYshZg8XMZ2Cl4bQZU:-NzYshZg8XMZ2Cl4bQZV:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ef4aac2fc017c4996d951bb789923cd40a703a5c/corelib/src/traits.cairo#L122)):*
> ```Cairo
>     }
>     
> }
> ```





_Suggestion:_
```Cairo
        PartialOrd::<T>::gt(*lhs, *rhs)
    }
}
```

**Review by tdelabro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5723)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/traits.cairo` line 122 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5723#-NzYshZg8XMZ2Cl4bQZU:-NzZA9icCreHFIXVUmRy:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ef4aac2fc017c4996d951bb789923cd40a703a5c/corelib/src/traits.cairo#L122)):*
> ```Cairo
>     }
>     
> }
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5723#-:-Nzb5ukG53QCAFFX_AFp:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tdelabro)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5723)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5723#-Nzb60vJ9nnTSQOqnsFU:-Nzb60vJ9nnTSQOqnsFV:b-uuj1x0) (no related file):*
@gilbens-starkware for 2nd eye.

___

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5723#-:-NzbQR1j4cHtzNk6Atrx:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tdelabro)

**Pull request merged**
