### PR TITLE
Update visit_remappings to only visit reachable blocks.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2542)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
currently, this PR has no effect because I moved toposort before optimize_remappings, but I want to go back to the previous order.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2542#-:-NQszEsdEmRBvmzSo7kw:b-k4mgsv)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @orizi and @spapinistarkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2542)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/remappings.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2542#-NQuKGF38SExpqVQjZnJ:-NQuKGF38SExpqVQjZnK:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f1bf83b00577120eaabc4b59b406a693eca8585c/crates/cairo-lang-lowering/src/optimizations/remappings.rs#L19)):*
> ```XML
> fn visit_remappings<F: FnMut(&VarRemapping)>(lowered: &mut FlatLowered, mut f: F) {
>     let mut stack = vec![BlockId::root()];
>     let mut visitied = vec![false; lowered.blocks.len()];
> ```





_Suggestion:_
```XML
 let mut visited = vec![false; lowered.blocks.len()];
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2542)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/remappings.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2542#-NQuKGF38SExpqVQjZnJ:-NQuh1147He5Qmt4-Jl6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f1bf83b00577120eaabc4b59b406a693eca8585c/crates/cairo-lang-lowering/src/optimizations/remappings.rs#L19)):*
> ```XML
> fn visit_remappings<F: FnMut(&VarRemapping)>(lowered: &mut FlatLowered, mut f: F) {
>     let mut stack = vec![BlockId::root()];
>     let mut visitied = vec![false; lowered.blocks.len()];
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2542#-:-NQwi0Z6DkOTk0GCuUDf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
