### PR TITLE
Pass Call::calldata as a Span.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4620)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4620)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @ArielElp and @orizi)

___
*[`corelib/src/starknet/account.cairo` line 7 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4620#-NmBMV516QTmI51UjVMe:-NmBMV516QTmI51UjVMf:blszugi) ([raw file](https://github.com/starkware-libs/cairo/blob/efeb898a65fc3cf38afb0e7508d94e012a2878f5/corelib/src/starknet/account.cairo#L7)):*
> ```Cairo
>     pub to: ContractAddress,
>     pub selector: felt252,
>     pub calldata: Span<felt252>
> ```

@ArielElp  can we merge this change?



_Code quote:_
```Cairo
   pub calldata: Span<felt252>
```

**Review by ArielElp — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4620)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

___
*[`corelib/src/starknet/account.cairo` line 7 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4620#-NmBMV516QTmI51UjVMe:-Nnr8m_O6qWWQmKLYtS4:b2nign6) ([raw file](https://github.com/starkware-libs/cairo/blob/efeb898a65fc3cf38afb0e7508d94e012a2878f5/corelib/src/starknet/account.cairo#L7)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

@ArielElp  can we merge this change?
</blockquote></details>

yes

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4620)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4620#-:-No5z0Kx3NCGvkYhfXqa:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
