### PR TITLE
Added line number to sierra printing.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3902)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 63 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3902)* status: 3 of 63 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/fmt.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3902#-NbsEUPT9OsF9MQG4ort:-NbsEUPT9OsF9MQG4oru:bnyrbu8) ([raw file](https://github.com/starkware-libs/cairo/blob/d82c82f208bfa59dfeef5ac829e1045606ac1fec/crates/cairo-lang-sierra/src/fmt.rs#L26)):*
> ```XML
>         writeln!(f)?;
>         for (i, statement) in self.statements.iter().enumerate() {
>             writeln!(f, "{statement}; // {i}")?;
> ```

Can we do the following:



_Suggestion:_
```XML
writeln!(f, "{i}: {statement};")?;
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3902)* status: 3 of 63 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/fmt.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3902#-NbsEUPT9OsF9MQG4ort:-NbsIxzj7tGym0uiJXXj:bbscy1d) ([raw file](https://github.com/starkware-libs/cairo/blob/d82c82f208bfa59dfeef5ac829e1045606ac1fec/crates/cairo-lang-sierra/src/fmt.rs#L26)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Can we do the following:
</blockquote></details>

No, as it won't be parsable by the parser. So it has to be a comment.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-sierra/src/fmt.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3902#-NbsEUPT9OsF9MQG4ort:-NbsK9ZD2Q3vTSUmYpDK:bxdjtir) ([raw file](https://github.com/starkware-libs/cairo/blob/d82c82f208bfa59dfeef5ac829e1045606ac1fec/crates/cairo-lang-sierra/src/fmt.rs#L26)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

No, as it won't be parsable by the parser. So it has to be a comment.
</blockquote></details>

you could fix the parser...

but I guess we might have backward compatibility issues.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 60 of 63 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3902#-:-Nbs_l5j9ipZHy6GHu8M:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3902)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/fmt.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3902#-NbsEUPT9OsF9MQG4ort:-Nbsiyp-2z-uuGD2-WFQ:b-1vijnd) ([raw file](https://github.com/starkware-libs/cairo/blob/d82c82f208bfa59dfeef5ac829e1045606ac1fec/crates/cairo-lang-sierra/src/fmt.rs#L26)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

you could fix the parser...

but I guess we might have backward compatibility issues.
</blockquote></details>

Exactly.

**Pull request merged**
