### PR TITLE
Added indirect impl support for inference.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4420)

### CODE REVIEW

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4420)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/items/impl_alias.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4420#-NjcDXkU1o4zN1URMcld:-NjcDXkU1o4zN1URMcle:b-fz5ei9) ([raw file](https://github.com/starkware-libs/cairo/blob/9951f4f8877b717faa506c5274f7eb5f829ea174/crates/cairo-lang-semantic/src/items/impl_alias.rs#L223)):*
> ```XML
>     _impl_alias_id: &ImplAliasId,
> ) -> Maybe<ImplDefId> {
>     Err(skip_diagnostic())
> ```

Explain why it's ok.
___
*[`tests/bug_samples/lib.cairo` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4420#-NjcDTVU6qW7SivWVDJo:-NjcDTVU6qW7SivWVDJp:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9951f4f8877b717faa506c5274f7eb5f829ea174/tests/bug_samples/lib.cairo#L2)):*
> ```Cairo
> mod ecdsa_completeness;
> mod indirect_impl;
> ```





_Suggestion:_
```Cairo
indirect_impl_alias;
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4420)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/items/impl_alias.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4420#-NjcDXkU1o4zN1URMcld:-NjcHmua7mKcH9QVWIOJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9951f4f8877b717faa506c5274f7eb5f829ea174/crates/cairo-lang-semantic/src/items/impl_alias.rs#L223)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Explain why it's ok.
</blockquote></details>

Done.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4420#-:-NjcJlz76nJOvKIYfEWN:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 926 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4420#-NjcJTRf1MyYcuVWx_Bi:-NjcJTRf1MyYcuVWx_Bj:b-f3fwf) ([raw file](https://github.com/starkware-libs/cairo/blob/032b7fb6e0a1526ea9d76793c74e8770bff73d8e/crates/cairo-lang-semantic/src/items/imp.rs#L926)):*
> ```XML
>         res.insert(UninferredImpl::GenericParam(*generic_param_id));
>     }
>     for module_id in chain!(lookup_context.modules.iter().map(|x| &x.0)) {
> ```

Shouldn't it be in another pr?
And I guess the prelude module is added to the context somewhere else?

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4420)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4420)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 926 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4420#-NjcJTRf1MyYcuVWx_Bi:-NjcK3oCDZg38hCvAv5j:bwc3jkp) ([raw file](https://github.com/starkware-libs/cairo/blob/032b7fb6e0a1526ea9d76793c74e8770bff73d8e/crates/cairo-lang-semantic/src/items/imp.rs#L926)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Shouldn't it be in another pr?
And I guess the prelude module is added to the context somewhere else?
</blockquote></details>

it isn't - but in the corelib all impls are either next to the trait or next to the type.

**Review by gilbens-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4420)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 926 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4420#-NjcJTRf1MyYcuVWx_Bi:-NjcOSzd-kU4Mghwppm7:b-dxcbts) ([raw file](https://github.com/starkware-libs/cairo/blob/032b7fb6e0a1526ea9d76793c74e8770bff73d8e/crates/cairo-lang-semantic/src/items/imp.rs#L926)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it isn't - but in the corelib all impls are either next to the trait or next to the type.
</blockquote></details>

Makes sense.

**Pull request merged**
