### PR TITLE
Add semantic module for while loops.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4666)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 959 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4666#-Nmf70H04aHKZOZRneTt:-Nmf70H04aHKZOZRneTu:b-vsyvf5) ([raw file](https://github.com/starkware-libs/cairo/blob/730300fd1be13913c3eff26d201cd917b3b14d10/crates/cairo-lang-semantic/src/expr/compute.rs#L959)):*
> ```XML
>         body,
>         ty: extract_matches!(loop_ctx, LoopContext::Loop).get_final_type(),
>         stable_ptr: syntax.stable_ptr().into(),
> ```

Note that before this PR I used the location of the Loop rather then then location of the block here.



_Code quote:_
```XML
syntax.stable_ptr().into()
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4666)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4666#-NmfP68K5n93RPqZFSJ8:-NmfP68K5n93RPqZFSJ9:b86cv1u) ([raw file](https://github.com/starkware-libs/cairo/blob/730300fd1be13913c3eff26d201cd917b3b14d10/crates/cairo-lang-semantic/src/expr/compute.rs#L101)):*
> ```XML
> enum LoopContext {
>     /// Not inside a loop
>     None,
> ```

I'm assuming handling for different loops is going to be similar - probably having the Option outside would be better.



_Code quote:_
```XML
    /// Not inside a loop
    None,
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4666)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4666#-NmfP68K5n93RPqZFSJ8:-NmkThuh34jU-azCxOeM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/730300fd1be13913c3eff26d201cd917b3b14d10/crates/cairo-lang-semantic/src/expr/compute.rs#L101)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I'm assuming handling for different loops is going to be similar - probably having the Option outside would be better.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r2, 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4666)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 593 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4666#-NmkU9Rc7S3l39NUCd3T:-NmkU9Rc7S3l39NUCd3U:b-9lz7yl) ([raw file](https://github.com/starkware-libs/cairo/blob/aa0890ec2d64bf83398adce49e205779c62a5a43/crates/cairo-lang-semantic/src/diagnostic.rs#L593)):*
> ```XML
>                 "`break` only allowed inside a `loop`.".into()
>             }
>             SemanticDiagnosticKind::BreakWithValueOnlyAllowedInsideALoop => {
> ```

don't we already have an error for the basic type mismatch?
or you are just trying to be more exact?
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2325 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4666#-NmkWFGQB5k-d93yIRGe:-NmkWFGQB5k-d93yIRGf:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/aa0890ec2d64bf83398adce49e205779c62a5a43/crates/cairo-lang-semantic/src/expr/compute.rs#L2325)):*
> ```XML
> }
> 
> fn compute_bool_condition(
> ```

doc

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 593 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4666#-NmkU9Rc7S3l39NUCd3T:-NmkapWe43KuW1-WDSMH:b-no18pn) ([raw file](https://github.com/starkware-libs/cairo/blob/aa0890ec2d64bf83398adce49e205779c62a5a43/crates/cairo-lang-semantic/src/diagnostic.rs#L593)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

don't we already have an error for the basic type mismatch?
or you are just trying to be more exact?
</blockquote></details>

rust does not allow break ();



_Code snippet:_
```XML
50 |         while true {
   |         ---------- you can't `break` with a value in a `while` loop
51 |             break ();
   |             ^^^^^^^^ can only break with a value inside `loop` or breakable block
   |
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4666#-:-NmkbMR61NRgs1XY3Evv:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4666)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2326 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4666#-NmkoWc85WuqBMoJy0MP:-NmkoWc85WuqBMoJy0MQ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ad0c073acd70f863eb0a15c0aa78281f9f4f7f45/crates/cairo-lang-semantic/src/expr/compute.rs#L2326)):*
> ```XML
> 
> // Computes the semantic model of an expression and reports diaganostics if
> // the expession does not evaluate to a boolean value.
> ```





_Suggestion:_
```XML
/// Computes the semantic model of an expression and reports diaganostics if
/// the expession does not evaluate to a boolean value.
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4666)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4666#-:-NmkrX6x0CxOfeMWT8Iv:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
