### PR TITLE
Fix allowed features for generic param resolving.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
**Stack**:
- #5890
- #5889
- #5888 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5888)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5888)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5888#-O0GQq2--4vmxhHbfYqr:-O0GQq2--4vmxhHbfYqs:b-tm1660) (no related file):*
add previously failing test.

___
___
*[`crates/cairo-lang-defs/src/ids.rs` line 320 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5888#-O0GRFv37ea-Z2wD2noK:-O0GRFv37ea-Z2wD2noL:b-wzuczt) ([raw file](https://github.com/starkware-libs/cairo/blob/a7d3f3719d6cd4ea4853b7d4f45d408f8e34713c/crates/cairo-lang-defs/src/ids.rs#L320)):*
> ```XML
> 
> impl ModuleItemId {
>     pub fn as_syntax_node(&self, db: &dyn DefsGroup) -> SyntaxNode {
> ```

could you have just called `stable_ptr` from the outside?

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5888)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5888#-O0GQq2--4vmxhHbfYqr:-O0IInvoDYAvAa1Xm3pO:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add previously failing test.
</blockquote></details>

Done.

___
___
*[`crates/cairo-lang-defs/src/ids.rs` line 320 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5888#-O0GRFv37ea-Z2wD2noK:-O0ICWdr8O5kC59pfyzk:bait2xm) ([raw file](https://github.com/starkware-libs/cairo/blob/a7d3f3719d6cd4ea4853b7d4f45d408f8e34713c/crates/cairo-lang-defs/src/ids.rs#L320)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

could you have just called `stable_ptr` from the outside?
</blockquote></details>

No, just `untyped_stable_ptr` and then if we want to convert it to typed one we'll have to do something similar to this.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5888)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-defs/src/ids.rs` line 320 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5888#-O0GRFv37ea-Z2wD2noK:-O0IN9G77drfcXsTBk16:b-sydhxq) ([raw file](https://github.com/starkware-libs/cairo/blob/a7d3f3719d6cd4ea4853b7d4f45d408f8e34713c/crates/cairo-lang-defs/src/ids.rs#L320)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

No, just `untyped_stable_ptr` and then if we want to convert it to typed one we'll have to do something similar to this.
</blockquote></details>

but you don't need it type now - do you?
___
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/tests` line 592 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5888#-O0INOr55lF22ufk9vVm:-O0INOr55lF22ufk9vVn:b-pijkim) ([raw file](https://github.com/starkware-libs/cairo/blob/11f5ada32db097ee2beac011ad65758cf02bfc25/crates/cairo-lang-semantic/src/diagnostic_test_data/tests#L592)):*
> ```
> error: The name `BadATraitImpl` is defined multiple times.
>  --> lib.cairo:45:6
> impl BadATraitImpl<+UnstableTrait> of ATrait;
> ```

remove diag

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5888)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-defs/src/ids.rs` line 320 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5888#-O0GRFv37ea-Z2wD2noK:-O0KXh_E0zfpRCL7LbxP:bse0buz) ([raw file](https://github.com/starkware-libs/cairo/blob/a7d3f3719d6cd4ea4853b7d4f45d408f8e34713c/crates/cairo-lang-defs/src/ids.rs#L320)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

but you don't need it type now - do you?
</blockquote></details>

I do, not all syntax kind implement `QueryAttrs`. 
___
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/tests` line 592 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5888#-O0INOr55lF22ufk9vVm:-O0LI2ttCj-S4Zp2y7sr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/11f5ada32db097ee2beac011ad65758cf02bfc25/crates/cairo-lang-semantic/src/diagnostic_test_data/tests#L592)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove diag
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5888)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 296 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5888#-O0LPrw--rpNBjByfxKb:-O0LPrw--rpNBjByfxKc:b-v985qp) ([raw file](https://github.com/starkware-libs/cairo/blob/53038d6db840b73c0b374c4d4bfe96f3ee69660f/crates/cairo-lang-semantic/src/items/generics.rs#L296)):*
> ```XML
>     resolver.set_allowed_features(
>         &lookup_item,
>         &lookup_item.as_syntax_node(db.upcast()),
> ```

and remove all the rest.

also - consider just using this inside the `set_allowed_features` function.
but probably not for this PR.



_Suggestion:_
```XML
        &lookup_item.untyped_stable_ptr(db.upcast()).lookup(db)
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5888)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 296 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5888#-O0LPrw--rpNBjByfxKb:-O0NoYPx-DkHLw3qcgIJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/53038d6db840b73c0b374c4d4bfe96f3ee69660f/crates/cairo-lang-semantic/src/items/generics.rs#L296)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

and remove all the rest.

also - consider just using this inside the `set_allowed_features` function.
but probably not for this PR.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5888#-:-O0NxkjE7LmB7p7_pD3l:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

**Pull request merged**
