### PR TITLE
LS: Explicitly ignore `Cancel` & `SetTrace` without polluting logs

### PR DESCRIPTION
**Pull request by mkaput**

### CODE REVIEW

**Review by piotmag769 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6518#-:-O9zCTRx65cCSeFpxuW8:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @orizi)

**Review by Draggu — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6518)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/src/server/routing/mod.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6518#-OA24pwdEfZ-uOXG5Qkv:-OA24pwdEfZ-uOXG5Qkw:b-rfai1h) ([raw file](https://github.com/starkware-libs/cairo/blob/c39c30db8ef8d0e08cf296027702aa07066ceed1/crates/cairo-lang-language-server/src/server/routing/mod.rs#L97)):*
> ```XML
>         DidSaveTextDocument::METHOD => local_notification_task::<DidSaveTextDocument>(notification),
> 
>         // Ignore these notifications as they are meaningless for CairoLS.
> ```

Can we explain here that LS know when to cancel on its own, without being notified by the client? Additionally, we ignore tracing settings because increasing it will quickly lead to overwhelmingly large traces. This would be more useful than only stating that these are meaningless.
___
*[`crates/cairo-lang-language-server/src/server/routing/mod.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6518#-OA24hbt9ASexvQ2M09D:-OA24hbt9ASexvQ2M09E:b-8hfmtk) ([raw file](https://github.com/starkware-libs/cairo/blob/7a7602f78707cf2e6013bfe9258e557ef884ebc0/crates/cairo-lang-language-server/src/server/routing/mod.rs#L99)):*
> ```XML
>         method => {
>             warn!("received notification {method} which does not have a handler");
> ```

Please keep these lines
___
*[`crates/cairo-lang-language-server/src/server/routing/mod.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6518#-OA26E663wpdBzrY7yzp:-OA26E663wpdBzrY7yzq:buo9nmt) ([raw file](https://github.com/starkware-libs/cairo/blob/7a7602f78707cf2e6013bfe9258e557ef884ebc0/crates/cairo-lang-language-server/src/server/routing/mod.rs#L105)):*
> ```XML
>     .unwrap_or_else(|error| {
>         error!("encountered error when routing notification: {error}");
> ```

Same here

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6518)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/server/routing/mod.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6518#-OA24pwdEfZ-uOXG5Qkv:-OA2EHhLBnfMO8hYnGgg:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/c39c30db8ef8d0e08cf296027702aa07066ceed1/crates/cairo-lang-language-server/src/server/routing/mod.rs#L97)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

Can we explain here that LS know when to cancel on its own, without being notified by the client? Additionally, we ignore tracing settings because increasing it will quickly lead to overwhelmingly large traces. This would be more useful than only stating that these are meaningless.
</blockquote></details>

Done

**Review by Draggu — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6518#-:-OA2FqaM7xgvLPiHoRUN:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @Arcticae, @orizi, and @piotmag769)

**Pull request merged**
