### PR TITLE
Add AddModGate.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5495)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5495)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/circuit.cairo` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5495#-NwnltRD47m2bZ-kctO2:-NwnltRD47m2bZ-kctO3:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/5c9e223d277018cc0c3a7c2f43d1f3d1f54018cd/corelib/src/circuit.cairo#L3)):*
> ```Cairo
> 
> 
> pub fn circuit_add<S, T, +CircuitElementTrait<S>, +CircuitElementTrait<T>,>(
> ```

doc
___
*[`corelib/src/circuit.cairo` line 7 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5495#-Nwnlxiq-upGZM-1v_uP:-Nwnlxiq-upGZM-1v_uQ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5c9e223d277018cc0c3a7c2f43d1f3d1f54018cd/corelib/src/circuit.cairo#L7)):*
> ```Cairo
> ) -> CircuitElement::<AddModGate<S, T>> {
>     CircuitElement::<AddModGate<S, T>> {}
> }
> ```





_Suggestion:_
```Cairo
pub fn circuit_add<Lhs, Rhs, +CircuitElementTrait<Lhs>, +CircuitElementTrait<Rhs>>(
    lhs: CircuitElement<Lhs>, rhs: CircuitElement<Rhs>
) -> CircuitElement::<AddModGate<Lhs, Rhs>> {
    CircuitElement::<AddModGate<Lhs, Rhs>> {}
}
```
___
*[`corelib/src/circuit.cairo` line 26 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5495#-Nwnls6W-yL-ncYLQU57:-Nwnls6W-yL-ncYLQU58:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5c9e223d277018cc0c3a7c2f43d1f3d1f54018cd/corelib/src/circuit.cairo#L26)):*
> ```Cairo
> 
> // Type for accumulating inputs into the circuit instance's data.
> extern type CircuitInputAccumulator<C>;
> ```





_Suggestion:_
```Cairo
/// Defines an input for a circuit.
#[phantom]
pub extern type CircuitInput<const N: usize>;
/// Defines an Addmod gate in a circuit.
#[phantom]
extern type AddModGate<Lhs, Rhs>;


/// Initializes the input data for running an instance of the circuit.
extern fn init_circuit_data<C>() -> CircuitInputAccumulator<C> implicits(RangeCheck96) nopanic;

/// Type for accumulating inputs into the circuit instance's data.
extern type CircuitInputAccumulator<C>;
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5495)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/circuit.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5495#-NwnmWsF2La5knNWA-Ag:-NwnmWsF2La5knNWA-Ah:b-ny6g03) ([raw file](https://github.com/starkware-libs/cairo/blob/5c9e223d277018cc0c3a7c2f43d1f3d1f54018cd/crates/cairo-lang-sierra/src/extensions/modules/circuit.rs#L105)):*
> ```XML
> }
> 
> /// Add mod gate type.
> ```

add some more info - "represents the action of adding two fields elements in the circuits builtin"
___
*[`crates/cairo-lang-sierra/src/extensions/modules/circuit.rs` line 139 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5495#-Nwnmkig7KHBUuDf9jpA:-Nwnmkig7KHBUuDf9jpB:bauez9n) ([raw file](https://github.com/starkware-libs/cairo/blob/5c9e223d277018cc0c3a7c2f43d1f3d1f54018cd/crates/cairo-lang-sierra/src/extensions/modules/circuit.rs#L139)):*
> ```XML
>                 return Err(SpecializationError::UnsupportedGenericArg);
>             }
>         }
> ```

this can already be exported into a function IMO.
maybe even the entire function.



_Code quote:_
```XML
        if args.len() != 2 {
            return Err(SpecializationError::WrongNumberOfGenericArgs);
        }

        for garg in args {
            // Note that its enough to check the topmost types as they validate their children.
            if !is_circuit_component(context, garg)? {
                return Err(SpecializationError::UnsupportedGenericArg);
            }
        }
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5495)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/circuit.cairo` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5495#-NwnltRD47m2bZ-kctO2:-NwnosjV5SvGMfjfS0ai:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5c9e223d277018cc0c3a7c2f43d1f3d1f54018cd/corelib/src/circuit.cairo#L3)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`corelib/src/circuit.cairo` line 7 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5495#-Nwnlxiq-upGZM-1v_uP:-NwnmmKlBPv5f3t-GCOa:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5c9e223d277018cc0c3a7c2f43d1f3d1f54018cd/corelib/src/circuit.cairo#L7)):*
> ```Cairo
> ) -> CircuitElement::<AddModGate<S, T>> {
>     CircuitElement::<AddModGate<S, T>> {}
> }
> ```

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5495)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/circuit.cairo` line 26 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5495#-Nwnls6W-yL-ncYLQU57:-Nwnp2TE7fJZfAlarhY7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5c9e223d277018cc0c3a7c2f43d1f3d1f54018cd/corelib/src/circuit.cairo#L26)):*
> ```Cairo
> 
> // Type for accumulating inputs into the circuit instance's data.
> extern type CircuitInputAccumulator<C>;
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5495)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/circuit.rs` line 48 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5495#-Nwnq1ML5Xphe29VumMw:-Nwnq1ML5Xphe29VumMx:bqsp5tq) ([raw file](https://github.com/starkware-libs/cairo/blob/137940a81be1d3ff3ca278ae4f53969af1544d4d/crates/cairo-lang-sierra/src/extensions/modules/circuit.rs#L48)):*
> ```XML
>         return Ok(true);
>     }
>     Ok(false)
> ```

consider



_Suggestion:_
```XML
    Ok([CircuitInput::ID, AddModGate::ID].contains(&long_id.generic_id))
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5495)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/circuit.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5495#-NwnmWsF2La5knNWA-Ag:-Nwnwlid2mVlO86vQr-b:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5c9e223d277018cc0c3a7c2f43d1f3d1f54018cd/crates/cairo-lang-sierra/src/extensions/modules/circuit.rs#L105)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add some more info - "represents the action of adding two fields elements in the circuits builtin"
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/circuit.rs` line 139 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5495#-Nwnmkig7KHBUuDf9jpA:-Nwo0_RQ4A08xAyvnOkP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5c9e223d277018cc0c3a7c2f43d1f3d1f54018cd/crates/cairo-lang-sierra/src/extensions/modules/circuit.rs#L139)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this can already be exported into a function IMO.
maybe even the entire function.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/circuit.rs` line 48 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5495#-Nwnq1ML5Xphe29VumMw:-Nwnwl7W6yvMDuZvFLNM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/137940a81be1d3ff3ca278ae4f53969af1544d4d/crates/cairo-lang-sierra/src/extensions/modules/circuit.rs#L48)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

consider
</blockquote></details>

Done.

**Pull request merged**
