### PR TITLE
Add early stop for fully concrete types.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5342)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
I guess this makes sense only after #5340.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5342#-:-NuNmmu25sVt7BFca2j5:b-cwz7xd)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5342#-:-NuNyVCC47mOdF7P0TmA:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5342)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/substitution.rs` line 430 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5342#-NuOBZT6-CdRbSD9zz3D:-NuOBZT6-CdRbSD9zz3E:b-j1kkt0) ([raw file](https://github.com/starkware-libs/cairo/blob/0dbb2aab4a3bf871183bbd47e222cfde0f1c8aa9/crates/cairo-lang-semantic/src/substitution.rs#L430)):*
> ```XML
>         if value.is_fully_concrete(self.db) {
>             return Ok(RewriteResult::NoChange);
>         }
> ```

just preventing a useless query.



_Suggestion:_
```XML
        if let ImplId::GenericParameter(generic_param) = value {
            if let Some(generic_arg) = self.substitution.get(generic_param) {
                *value = *extract_matches!(generic_arg, GenericArgumentId::Impl);
                // TODO(GIL): Reduce and check for cycles when the substitution is created.
                // Substitution is guaranteed to not contain its own variables.
                return Ok(RewriteResult::Modified);
            }
        } else if value.is_fully_concrete(self.db) {
            return Ok(RewriteResult::NoChange);
        }
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5342#-:-NuOkY6TAw9TD8ixGuyG:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
