### PR TITLE
feat: derive serde for dispatchers

### LINKED ISSUE #3240: feat: implement Serde for dispatchers
# Feature Request

**Describe the Feature Request**

It would be great if the Cairo compiler could implement the `Serde` trait for contract and library dispatchers to be able to pass it as calldata when doing contract or library call syscalls. This is to make inner calls more convenient, for example:

So for Contract A and B, Instead of this
```Rust

const EXECUTE_ENTRYPOINT: felt252 = 0x0240060cdb34fcc260f41eac7474ee1d7c80b7e3607daff9ac67c7ea2ebb1c44; // hash("execute")

#[external]
fn execute(class_hash: starknet::ClassHash, world: starknet::ContractAddress, calldata: Span<felt252>) -> Span<felt252> {
    let mut calldata_arr = calldata.snapshot.clone();
    calldata_arr.append(world_address.into());

    let res = starknet::syscalls::library_call_syscall(
        class_hash, EXECUTE_ENTRYPOINT, calldata_arr.span()
    ).unwrap_syscall();
    res
}
```

```Rust
#[external]
fn execute(world_address: starknet::ContractAddress) {
    world = IWorldDispatcher { contract_address: world_address }; // Instantiate IWorldDispatcher
    world.foo("bar"); // Call foo
}
```

It could be good to do this
```Rust
#[external]
fn execute(class_hash: starknet::ClassHash, world: IWorldDispatcher, calldata: Span<felt252>) -> Span<felt252> {
  let mut calldata_arr = calldata.snapshot.clone();
  world.serialize(ref calldata_arr);

  let res = starknet::syscalls::library_call_syscall(
      class_hash, EXECUTE_ENTRYPOINT, calldata_arr.span()
  ).unwrap_syscall();
  res
}
```

```Rust
#[external]
fn execute(world: IWorldDispatcher) {
    world.foo("bar"); // Call foo directly
}
```

**Describe Preferred Solution**

In this [file](https://github.com/starkware-libs/cairo/blob/9203b803f13061506068d472aa67e190eb5cf67e/crates/cairo-lang-starknet/src/plugin/dispatcher.rs), derive Serde for contract and library dispatchers like so

```Rust
#[derive(Copy, Copy, Serde)]
struct {contract_caller_name}
    contract_address: starknet::ContractAddress,
}}

#[derive(Copy, Drop, Serde)]
struct {library_caller_name} {{
    class_hash: starknet::ClassHash,
}}
```
**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by ftupas**
Hello there, this small pr does the following
- derive Serde for contract and library dispatchers
- add test for dispatcher serde
- fix #3240

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3241)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3241)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ftupas)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo` line 17 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3241#-NWqI-si7EIZ7UtE0qO7:-NWqI-si7EIZ7UtE0qO8:bse09y2) ([raw file](https://github.com/starkware-libs/cairo/blob/777aacb4f7d810c7ddcd993da0a314f9c9904564/crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo#L17)):*
> ```Cairo
> 
> #[abi]
> trait ITestContract {
> ```

if you are adding this only for the serde test - can you make this into a much simple abi?



_Code quote:_
```Cairo
#[abi]
trait ITestContract {
```

**Comment by ftupas** [comment]
> > Reviewed 2 of 3 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3241)_ status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ftupas)
> 
> _[`crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo` line 17 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3241#-NWqI-si7EIZ7UtE0qO7:-NWqI-si7EIZ7UtE0qO8:bse09y2) ([raw file](https://github.com/starkware-libs/cairo/blob/777aacb4f7d810c7ddcd993da0a314f9c9904564/crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo#L17)):_
> 
> > ```cairo
> > #[abi]
> > trait ITestContract {
> > ```
> 
> if you are adding this only for the serde test - can you make this into a much simple abi?
> 
> _Code quote:_
> 
> ```cairo
> #[abi]
> trait ITestContract {
> ```

Thanks for the review and feedback @orizi ! I've just updated this to a simpler abi, much less clutter thanks!

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3241#-:-NWqQmeZBuRl8Whq4LEk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ftupas)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3241#-:-NWqZ_A83kto-s5WnSFx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ftupas)

**Pull request merged**
