### PR TITLE
Merge dev v2.6.4 into main

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5775)

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
> Reviewed 49 of 49 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5775)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput and @TomerStarkware)

**Review by TomerStarkware — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5775#-:-O-1cxer3nu1BKcAg0D7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, 13 of 13 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5775)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Review by orizi — COMMENTED** [review]
> Reviewed 13 of 13 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5775)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Pull request merged**
