### PR TITLE
Add logic to add missing fallthroughs.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2279)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2279)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/flow/mod.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2279#-NPCcLe3DIMKrx_eX7VN:-NPCcLe3DIMKrx_eX7VO:b-9xstz6) ([raw file](https://github.com/starkware-libs/cairo/blob/0c040faf42acd4b2caceddade5b4531275900af0/crates/cairo-lang-lowering/src/flow/mod.rs#L13)):*
> ```XML
> 
>     // Toplogically sorted block ids.
>     output: Vec<BlockId>,
> ```

I cane replace `incoming_edges` with `visited` and remove output, but I want to use those in the future.



_Code quote:_
```XML
    /// Number of incoming edges to each block, indexed by block id.
    incoming_edges: Vec<usize>,

    // Toplogically sorted block ids.
    output: Vec<BlockId>,
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2279)* status: 1 of 9 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/flow/mod.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2279#-NPCczL59_rk_BeZClaY:-NPCczL59_rk_BeZClaZ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0c040faf42acd4b2caceddade5b4531275900af0/crates/cairo-lang-lowering/src/flow/mod.rs#L10)):*
> ```XML
> 
>     /// Number of incoming edges to each block, indexed by block id.
>     incoming_edges: Vec<usize>,
> ```





_Suggestion:_
```XML
    visited_incoming_edges: Vec<usize>,
```
___
*[`crates/cairo-lang-lowering/src/flow/mod.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2279#-NPCcLe3DIMKrx_eX7VN:-NPCcrWqDv7B-v3Kxcv6:b-785l8s) ([raw file](https://github.com/starkware-libs/cairo/blob/0c040faf42acd4b2caceddade5b4531275900af0/crates/cairo-lang-lowering/src/flow/mod.rs#L13)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I cane replace `incoming_edges` with `visited` and remove output, but I want to use those in the future.
</blockquote></details>

you want to use them for what?
___
*[`crates/cairo-lang-lowering/src/flow/mod.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2279#-NPCd4Xx5KC2r_vz_P12:-NPCd4Xx5KC2r_vz_P13:b-ditm3n) ([raw file](https://github.com/starkware-libs/cairo/blob/0c040faf42acd4b2caceddade5b4531275900af0/crates/cairo-lang-lowering/src/flow/mod.rs#L20)):*
> ```XML
>     pub fn visit(&mut self, block_id: &BlockId) {
>         let incoming_edges = &mut self.incoming_edges[block_id.0];
>         *incoming_edges += 1;
> ```

this way it is more clear this is the first access IMO.



_Suggestion:_
```XML
        let incoming_edges = &mut self.incoming_edges[block_id.0];
        if *incoming_edges == 0 {
            self.stack.push(*block_id);
        }
        *incoming_edges += 1;
    }
```
___
*[`crates/cairo-lang-lowering/src/flow/mod.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2279#-NPCdqInAuOXUkO-FKLp:-NPCdqInAuOXUkO-FKLq:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/0c040faf42acd4b2caceddade5b4531275900af0/crates/cairo-lang-lowering/src/flow/mod.rs#L87)):*
> ```XML
> }
> 
> pub fn add_fallthroughs(flat_lowered: &mut FlatLowered) {
> ```

doc



_Code quote:_
```XML
pub fn add_fallthroughs(flat_lowered: &mut FlatLowered) {
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/flow/mod.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2279#-NPCcLe3DIMKrx_eX7VN:-NPCfaP52SdANONVCz05:b-ftsrp7) ([raw file](https://github.com/starkware-libs/cairo/blob/0c040faf42acd4b2caceddade5b4531275900af0/crates/cairo-lang-lowering/src/flow/mod.rs#L13)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you want to use them for what?
</blockquote></details>

 // TODO(ilya): Merge blocks that fallthrough into a block with a single incoming_edge.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/flow/mod.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2279#-NPCczL59_rk_BeZClaY:-NPCfW2w8uSPF_OJaXtF:bf3mb8u) ([raw file](https://github.com/starkware-libs/cairo/blob/0c040faf42acd4b2caceddade5b4531275900af0/crates/cairo-lang-lowering/src/flow/mod.rs#L10)):*
> ```XML
> 
>     /// Number of incoming edges to each block, indexed by block id.
>     incoming_edges: Vec<usize>,
> ```

after the algorithm completes it holds the number of incoming edged.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2279)* status: 1 of 9 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/flow/mod.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2279#-NPCczL59_rk_BeZClaY:-NPChXPG3hu5tvnCWx9_:bnf7vnx) ([raw file](https://github.com/starkware-libs/cairo/blob/0c040faf42acd4b2caceddade5b4531275900af0/crates/cairo-lang-lowering/src/flow/mod.rs#L10)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

after the algorithm completes it holds the number of incoming edged.
</blockquote></details>

but the context is for the algorithm - and this is a management field - not a result field.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2279)* status: 1 of 10 files reviewed, 3 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/flow/mod.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2279#-NPCczL59_rk_BeZClaY:-NPCkTeW9378Ygz3J_qM:byemyio) ([raw file](https://github.com/starkware-libs/cairo/blob/0c040faf42acd4b2caceddade5b4531275900af0/crates/cairo-lang-lowering/src/flow/mod.rs#L10)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

but the context is for the algorithm - and this is a management field - not a result field.
</blockquote></details>

made the code less generic.
___
*[`crates/cairo-lang-lowering/src/flow/mod.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2279#-NPCd4Xx5KC2r_vz_P12:-NPCkWR93aCdepYf4MQQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0c040faf42acd4b2caceddade5b4531275900af0/crates/cairo-lang-lowering/src/flow/mod.rs#L20)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this way it is more clear this is the first access IMO.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/flow/mod.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2279#-NPCdqInAuOXUkO-FKLp:-NPCkWuUCf5Zp0hHfqJ5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0c040faf42acd4b2caceddade5b4531275900af0/crates/cairo-lang-lowering/src/flow/mod.rs#L87)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2279)* status: 1 of 10 files reviewed, 4 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-sierra-generator/src/lifetime.rs` line 198 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2279#-NPCkhijBxAeG8SqAR6P:-NPCkhijBxAeG8SqAR6Q:b-9ee9h2) ([raw file](https://github.com/starkware-libs/cairo/blob/0c040faf42acd4b2caceddade5b4531275900af0/crates/cairo-lang-sierra-generator/src/lifetime.rs#L198)):*
> ```XML
>                     .arms
>                     .iter()
>                     .rev()
> ```

Moved to a seperate PR:
https://reviewable.io/reviews/starkware-libs/cairo/2280#-



_Code quote:_
```XML
.rev()
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2279)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/flow/mod.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2279#-NPCnDrC1uykMxrJKsS_:-NPCnDrC1uykMxrJKsSa:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/498fdae5837e672c1392631e39e5867e55654dbe/crates/cairo-lang-lowering/src/flow/mod.rs#L25)):*
> ```XML
>         self.visited.resize(flat_lowered.blocks.len(), false);
>         let mut has_fallthorugh = vec![];
>         has_fallthorugh.resize(flat_lowered.blocks.len(), false);
> ```





_Suggestion:_
```XML
        let mut has_fallthorugh = vec![flat_lowered.blocks.len(), false];
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2279)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/flow/mod.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2279#-NPCnDrC1uykMxrJKsS_:-NPCuEnmC_kVdXZHzuYP:b-r18wie) ([raw file](https://github.com/starkware-libs/cairo/blob/498fdae5837e672c1392631e39e5867e55654dbe/crates/cairo-lang-lowering/src/flow/mod.rs#L25)):*
> ```XML
>         self.visited.resize(flat_lowered.blocks.len(), false);
>         let mut has_fallthorugh = vec![];
>         has_fallthorugh.resize(flat_lowered.blocks.len(), false);
> ```

done, thanks.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2279#-:-NPCvmbs6attzl_pJEbv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 7 of 9 files at r1, 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2279#-:-NPD5jUw8ggyNb0pzNyX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2279)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2279)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/inline/test.rs` line 42 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2279#-NPDCHR4C34CAI9P5cEg:-NPDCHR4C34CAI9P5cEh:br5eaig) ([raw file](https://github.com/starkware-libs/cairo/blob/8dd5c2ed7ed0e3b9a2c50033e04aab2e46e4ee20/crates/cairo-lang-lowering/src/inline/test.rs#L42)):*
> ```XML
>     let lowering_diagnostics = db.module_lowering_diagnostics(test_function.module_id).unwrap();
>     apply_inlining(db, test_function.function_id, &mut after).unwrap();
>     add_fallthroughs(&mut after);
> ```

Should I call optimize_remappings here?

It is a bit strange that we are not consistent with concrete_function_with_body_lowered here.



_Code quote:_
```XML
  add_fallthroughs(&mut after);
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2279)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/inline/test.rs` line 42 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2279#-NPDCHR4C34CAI9P5cEg:-NPDEUTu5kjEbQOuz0q2:b2vdhsc) ([raw file](https://github.com/starkware-libs/cairo/blob/8dd5c2ed7ed0e3b9a2c50033e04aab2e46e4ee20/crates/cairo-lang-lowering/src/inline/test.rs#L42)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Should I call optimize_remappings here?

It is a bit strange that we are not consistent with concrete_function_with_body_lowered here.

</blockquote></details>

another option is not to call add_fallthroughs here,
but then I would need a separate test for that.

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2279)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/inline/test.rs` line 42 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2279#-NPDCHR4C34CAI9P5cEg:-NPDEWSr-SdUqLYJNIAA:b-iufud4) ([raw file](https://github.com/starkware-libs/cairo/blob/8dd5c2ed7ed0e3b9a2c50033e04aab2e46e4ee20/crates/cairo-lang-lowering/src/inline/test.rs#L42)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

another option is not to call add_fallthroughs here,
but then I would need a separate test for that.
</blockquote></details>

we probably should - feel free to add.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2279)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/flow/mod.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2279#-NPCcLe3DIMKrx_eX7VN:-NPDF81rEezLvcyp7VJq:b-aehm6a) ([raw file](https://github.com/starkware-libs/cairo/blob/0c040faf42acd4b2caceddade5b4531275900af0/crates/cairo-lang-lowering/src/flow/mod.rs#L13)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

 // TODO(ilya): Merge blocks that fallthrough into a block with a single incoming_edge.
</blockquote></details>

This should be its own phase under optimizations IMO, wdyt?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2279)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/flow/mod.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2279#-NPCcLe3DIMKrx_eX7VN:-NPDFXCy4ODHEllCm7ze:buhkij3) ([raw file](https://github.com/starkware-libs/cairo/blob/0c040faf42acd4b2caceddade5b4531275900af0/crates/cairo-lang-lowering/src/flow/mod.rs#L13)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This should be its own phase under optimizations IMO, wdyt?
</blockquote></details>

Both require toplogical sort, feels wasteful.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2279)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/flow/mod.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2279#-NPCcLe3DIMKrx_eX7VN:-NPDFnjs8XXGWQ7ErL28:b-x5ct4f) ([raw file](https://github.com/starkware-libs/cairo/blob/0c040faf42acd4b2caceddade5b4531275900af0/crates/cairo-lang-lowering/src/flow/mod.rs#L13)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Both require toplogical sort, feels wasteful.
</blockquote></details>

I guess I can split the toplogical sort from the
(Add FlatBlockEnd::Fallthrough + merge blocks) phase.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2279)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @orizi, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/inline/test.rs` line 42 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2279#-NPDCHR4C34CAI9P5cEg:-NPDHAws5jHyvrei4nme:b-jkau8v) ([raw file](https://github.com/starkware-libs/cairo/blob/8dd5c2ed7ed0e3b9a2c50033e04aab2e46e4ee20/crates/cairo-lang-lowering/src/inline/test.rs#L42)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

we probably should - feel free to add.
</blockquote></details>

I've decided to keep it as is for now.

I'll add a seperate test for add_fallthroughs once that phase will have more logic.

**Pull request merged**
