### PR TITLE
Support capturing variables in a closure.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6087)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6087)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/closure` line 26 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6087#-O2xscUz41pyH4n2Sg97:-O2xscV-60kndcRQb0x0:b-dr8jcy) ([raw file](https://github.com/starkware-libs/cairo/blob/d09191f63fc9e4f1fed323b2006d2f3b004c128c/crates/cairo-lang-lowering/src/borrow_check/test_data/closure#L26)):*
> ```
>     ^********^
> note: Trait has no implementation in context: core::traits::Drop::<{closure@lib.cairo:2:5: 2:13}>.
> note: Trait has no implementation in context: core::traits::Destruct::<{closure@lib.cairo:2:5: 2:13}>.
> ```

Any idea on how I could add a destructor for closures?



_Code quote:_
```
note: Trait has no implementation in context: core::traits::Destruct::<{closure@lib.cairo:2:5: 2:13}>.
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6087)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/closure` line 26 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6087#-O2xscUz41pyH4n2Sg97:-O2xvjSd1n8Ryv22Vp69:b-cu5ln8) ([raw file](https://github.com/starkware-libs/cairo/blob/d09191f63fc9e4f1fed323b2006d2f3b004c128c/crates/cairo-lang-lowering/src/borrow_check/test_data/closure#L26)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Any idea on how I could add a destructor for closures?
</blockquote></details>

we probably need to have some sort of special implementation for Destruct as well (similar to how `Fn` has a special implementation by the capture statement).

Another half option is that the `Fn*` traits would have impl items - demanding having `Destruct` in the case of FnOnce.

another question is - do we need `Destruct` for any of the other closure types?
as both `Fn` and `FnMut` should return the captured values to the outside context upon closure "destruct".

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6087)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/closure` line 26 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6087#-O2xscUz41pyH4n2Sg97:-O2yWECY92Qsy7WBa0-Y:b-jrxtrf) ([raw file](https://github.com/starkware-libs/cairo/blob/d09191f63fc9e4f1fed323b2006d2f3b004c128c/crates/cairo-lang-lowering/src/borrow_check/test_data/closure#L26)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

In this PR, I invalidate the closure only if one of the captured variables is used.
</blockquote></details>

Got it, so I guess we just need to auto add destruct impl when needed here, which is a new concept for us.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/closure` line 26 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6087#-O2xscUz41pyH4n2Sg97:-O31L4YNCABSQ_TUBEH4:bssjoiv) ([raw file](https://github.com/starkware-libs/cairo/blob/d09191f63fc9e4f1fed323b2006d2f3b004c128c/crates/cairo-lang-lowering/src/borrow_check/test_data/closure#L26)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Got it, so I guess we just need to auto add destruct impl when needed here, which is a new concept for us.
</blockquote></details>

We also need to figure out whether to Destruct or PanicDestruct.

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6087)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/closure` line 26 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6087#-O2xscUz41pyH4n2Sg97:-O31kOZpAq-FtY0DIVvk:bd1ly39) ([raw file](https://github.com/starkware-libs/cairo/blob/d09191f63fc9e4f1fed323b2006d2f3b004c128c/crates/cairo-lang-lowering/src/borrow_check/test_data/closure#L26)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

We also need to figure out whether to Destruct or PanicDestruct.
</blockquote></details>

As part of the "understanding which one we need"? If so, than yes.
___
*[`crates/cairo-lang-lowering/src/lower/block_builder.rs` line 259 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6087#-O31kmYGCdV4yVh7eisX:-O31kmYGCdV4yVh7eisY:b2nhdkj) ([raw file](https://github.com/starkware-libs/cairo/blob/d09191f63fc9e4f1fed323b2006d2f3b004c128c/crates/cairo-lang-lowering/src/lower/block_builder.rs#L259)):*
> ```XML
>     }
> 
>     pub fn capture(
> ```

Doc
___
*[`crates/cairo-lang-lowering/src/lower/refs.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6087#-O31lvlK09oxSSccuxss:-O31lvlL5l5g-uIFNrGO:b2nhdkj) ([raw file](https://github.com/starkware-libs/cairo/blob/d09191f63fc9e4f1fed323b2006d2f3b004c128c/crates/cairo-lang-lowering/src/lower/refs.rs#L15)):*
> ```XML
> 
> #[derive(Clone, Debug)]
> pub struct ClosureInfo {
> ```

Doc
___
*[`crates/cairo-lang-lowering/src/lower/refs.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6087#-O31l0690wDMHLCyFJH9:-O31l0690wDMHLCyFJHA:bm2pb5r) ([raw file](https://github.com/starkware-libs/cairo/blob/d09191f63fc9e4f1fed323b2006d2f3b004c128c/crates/cairo-lang-lowering/src/lower/refs.rs#L26)):*
> ```XML
>     scattered: OrderedHashMap<MemberPath, Value>,
>     pub captured_vars: UnorderedHashMap<MemberPath, usize>,
>     pub closures: Vec<Option<ClosureInfo>>,
> ```

Doc, specifically to explain the Vec Option.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6087)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @orizi and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/block_builder.rs` line 259 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6087#-O31kmYGCdV4yVh7eisX:-O3Blr-kBooR_AlEGsyQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d09191f63fc9e4f1fed323b2006d2f3b004c128c/crates/cairo-lang-lowering/src/lower/block_builder.rs#L259)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/refs.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6087#-O31lvlK09oxSSccuxss:-O3BlrWs1ljfkKdHw0dg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d09191f63fc9e4f1fed323b2006d2f3b004c128c/crates/cairo-lang-lowering/src/lower/refs.rs#L15)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/refs.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6087#-O31l0690wDMHLCyFJH9:-O3Bls0N9kMM5tV6URXY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d09191f63fc9e4f1fed323b2006d2f3b004c128c/crates/cairo-lang-lowering/src/lower/refs.rs#L26)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Doc, specifically to explain the Vec Option.
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6087)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/refs.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6087#-O3BmEXv2ADe_7h-fgyW:-O3BmEXv2ADe_7h-fgyX:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/764d77f64b6e51d1dd54290ecd32eb0db283e4f8/crates/cairo-lang-lowering/src/lower/refs.rs#L14)):*
> ```XML
> use crate::VariableId;
> 
> //  Information about members captured by the closure and thier types.
> ```





_Suggestion:_
```XML
//  Information about members captured by the closure and their types.
```

**Review by TomerStarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6087#-:-O3BoQWn3_eBxzXe2Yk7:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6087#-:-O3BpfeD0mdLEwGMKX48:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6087)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6087)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/lower/refs.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6087#-O3BmEXv2ADe_7h-fgyW:-O3BoVEcETN0wXhEUNVx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/764d77f64b6e51d1dd54290ecd32eb0db283e4f8/crates/cairo-lang-lowering/src/lower/refs.rs#L14)):*
> ```XML
> use crate::VariableId;
> 
> //  Information about members captured by the closure and thier types.
> ```

Done.

**Pull request merged**
