### PR TITLE
Fix a bug with store of partial params.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2433)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2433)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @liorgold2)

___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 219 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2433#-NQ5pk3783l4IRoRee-E:-NQ5pk3783l4IRoRee-F:bze3dkr) ([raw file](https://github.com/starkware-libs/cairo/blob/e0a606c6e8e862098c8a71d3c6c15eced89c85c6/crates/cairo-lang-sierra-generator/src/local_variables.rs#L219)):*
> ```XML
>             match output_info.ref_info {
>                 OutputVarReferenceInfo::SameAsParam { param_idx } => {
>                     self.aliases.insert(*var, input_vars[param_idx]);
> ```

Maybe we need the relationship between the vars anyway?
Does it not hinder any existing code?
___
*[`tests/bug_samples/partial_param_local.cairo` line 5 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2433#-NQ5pM1OD7Yau79z1stY:-NQ5pM1PB3eM7EbKxsMD:b5qlxxo) ([raw file](https://github.com/starkware-libs/cairo/blob/e0a606c6e8e862098c8a71d3c6c15eced89c85c6/tests/bug_samples/partial_param_local.cairo#L5)):*
> ```Cairo
> }
> 
> #[test]
> ```

Add a test in the locals lib

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2433)* status: 16 of 17 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/local_variables.rs` line 219 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2433#-NQ5pk3783l4IRoRee-E:-NQ6-Fil8EBht7ABVWY-:b-ywnaev) ([raw file](https://github.com/starkware-libs/cairo/blob/e0a606c6e8e862098c8a71d3c6c15eced89c85c6/crates/cairo-lang-sierra-generator/src/local_variables.rs#L219)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Maybe we need the relationship between the vars anyway?
Does it not hinder any existing code?
</blockquote></details>

This statement as it is does not make sense, it states that the member var is the same as the parent struct.
I've looked where the aliases are used and it makes sense that it will be applied only for SameAsParam.
It change only the contracts examples, but the changes seems logical, but i'd like if you can TAL at the changes of one of the contracts (all are very similar).
___
*[`tests/bug_samples/partial_param_local.cairo` line 5 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2433#-NQ5pM1OD7Yau79z1stY:-NQ69cBx7wEJ4UG_wW3n:b-mqv80c) ([raw file](https://github.com/starkware-libs/cairo/blob/e0a606c6e8e862098c8a71d3c6c15eced89c85c6/tests/bug_samples/partial_param_local.cairo#L5)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Add a test in the locals lib
</blockquote></details>

Done, but I'll keep this as the locals lib tests only test the lowered code.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2433)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2433)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
