### PR TITLE
Removed rayon from validation, and reading inputs by chunks.

### PR DESCRIPTION
**Pull request by orizi**
Including support for multiple file inputs.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5556)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 188 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5556#-NyERGcY0M82K9aCRbZh:-NyERGcZ-fnL9JRy8GD1:bhgtub9) ([raw file](https://github.com/starkware-libs/cairo/blob/cc137994c0fc4a96cfdb53d3a0140a0cc9dbaf10/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L188)):*
> ```XML
>             b']' => break,
>             _ => return Err(anyhow::anyhow!("Invalid header")),
>         }
> ```

what is this? can you document?



_Code quote:_
```XML
        match next_byte {
            b'[' | b',' => {}
            b' ' | b'\n' => continue,
            b']' => break,
            _ => return Err(anyhow::anyhow!("Invalid header")),
        }
```

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5556#-:-NyERmdJBPTWo6_XRgQ-:bnfp4nl)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi and @Tomer-StarkWare)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5556)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @Tomer-StarkWare)

___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 188 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5556#-NyERGcY0M82K9aCRbZh:-NyEUpGc4OV3LiB0oqCY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cc137994c0fc4a96cfdb53d3a0140a0cc9dbaf10/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L188)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what is this? can you document?
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 188 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5556#-NyERGcY0M82K9aCRbZh:-NyEphEB4Blh1ack-Rc1:b-rcjf67) ([raw file](https://github.com/starkware-libs/cairo/blob/cc137994c0fc4a96cfdb53d3a0140a0cc9dbaf10/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L188)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Done.
</blockquote></details>

How come you didn't need it in the old implementation?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5556)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware and @Tomer-StarkWare)

___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 188 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5556#-NyERGcY0M82K9aCRbZh:-NyEsIbW0FnqzTFQy0Py:bis2oju) ([raw file](https://github.com/starkware-libs/cairo/blob/cc137994c0fc4a96cfdb53d3a0140a0cc9dbaf10/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L188)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

How come you didn't need it in the old implementation?
</blockquote></details>

we read the entire file back then - now we read it in a streaming manner.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 188 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5556#-NyERGcY0M82K9aCRbZh:-NyEu0Cg8Kb0yrMkqOgH:bggjq7z) ([raw file](https://github.com/starkware-libs/cairo/blob/cc137994c0fc4a96cfdb53d3a0140a0cc9dbaf10/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L188)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

we read the entire file back then - now we read it in a streaming manner.
</blockquote></details>

How do you make sure the readers don't interfere with each other?

What happens if 1 reader reads a couple of bytes from the middle of a class that another reader is reading?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5556)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware and @Tomer-StarkWare)

___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 188 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5556#-NyERGcY0M82K9aCRbZh:-NyEuN_fBhiKQitVfCCd:b-h29z8i) ([raw file](https://github.com/starkware-libs/cairo/blob/cc137994c0fc4a96cfdb53d3a0140a0cc9dbaf10/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L188)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

How do you make sure the readers don't interfere with each other?

What happens if 1 reader reads a couple of bytes from the middle of a class that another reader is reading?
</blockquote></details>

different files.
one file is read only by a single reader.

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5556)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @Tomer-StarkWare)

**Pull request merged**
