### PR TITLE
Use postinline_direct_callees for needs_withdraw_gas feedback set.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4153)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4153)* status: all files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 359 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4153#-NfLTPbk72cGV2Ody59A:-NfLTPbk72cGV2Ody59B:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/4e9c432289ef10eb042233f7256709122059f8d7/crates/cairo-lang-lowering/src/db.rs#L359)):*
> ```XML
>     let mut lowered = (*db.priv_concrete_function_with_body_postinline_lowered(function)?).clone();
> 
>     apply_inlining(db, function, &mut lowered)?;
> ```

remove
___
*[`crates/cairo-lang-lowering/src/db.rs` line 431 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4153#-NfLTspf7pxBYolCD5PW:-NfLTspf7pxBYolCD5PX:b74wfca) ([raw file](https://github.com/starkware-libs/cairo/blob/4e9c432289ef10eb042233f7256709122059f8d7/crates/cairo-lang-lowering/src/db.rs#L431)):*
> ```XML
>         }
>     }
>     Ok(direct_callees)
> ```

extract to a helper function



_Code quote:_
```XML
    for (_, block) in &lowered_function.blocks {
        for statement in &block.statements {
            if let Statement::Call(statement_call) = statement {
                direct_callees.push(statement_call.function);
            }
        }
        if let FlatBlockEnd::Match { info: MatchInfo::Extern(s) } = &block.end {
            direct_callees.push(s.function);
        }
    }
    Ok(direct_callees)
```
___
*[`crates/cairo-lang-lowering/src/db.rs` line 465 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4153#-NfLU3MH2dyX-PrjtkS6:-NfLU3MH2dyX-PrjtkS7:bv9agr0) ([raw file](https://github.com/starkware-libs/cairo/blob/4e9c432289ef10eb042233f7256709122059f8d7/crates/cairo-lang-lowering/src/db.rs#L465)):*
> ```XML
>         .into_iter()
>         .flatten()
>         .collect_vec())
> ```

extract to a helper function, use 3 times.



_Code quote:_
```XML
        .into_iter()
        .map(|concrete| concrete.body(db.upcast()))
        .collect::<Maybe<Vec<_>>>()?
        .into_iter()
        .flatten()
        .collect_vec())
```
___
*[`crates/cairo-lang-lowering/src/graph_algorithms/concrete_function_postiniline_node.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4153#-NfLXYcuDxRLfVsKW4ds:-NfLXYcuDxRLfVsKW4dt:b-xo5sd) ([raw file](https://github.com/starkware-libs/cairo/blob/2e8142b67a4312c830aea1bb9e34631bf0e39a5d/crates/cairo-lang-lowering/src/graph_algorithms/concrete_function_postiniline_node.rs#L19)):*
> ```XML
>     fn get_neighbors(&self) -> Vec<Self> {
>         let Ok(direct_callees) =
>             self.db.concrete_function_with_body_direct_callees_with_body(self.function_id)
> ```

is this function still used?



_Code quote:_
```XML
concrete_function_with_body_direct_callees_with_body
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/graph_algorithms/concrete_function_postiniline_node.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4153#-NfLXYcuDxRLfVsKW4ds:-NfL_Wad2lvAHXRN7znh:b-3wxlng) ([raw file](https://github.com/starkware-libs/cairo/blob/2e8142b67a4312c830aea1bb9e34631bf0e39a5d/crates/cairo-lang-lowering/src/graph_algorithms/concrete_function_postiniline_node.rs#L19)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

is this function still used?
</blockquote></details>

it us used by `contains\_cycle`

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4153)* status: 6 of 9 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 465 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4153#-NfLU3MH2dyX-PrjtkS6:-NfLaXkR8vT61rdU1N9s:b-qtk76e) ([raw file](https://github.com/starkware-libs/cairo/blob/4e9c432289ef10eb042233f7256709122059f8d7/crates/cairo-lang-lowering/src/db.rs#L465)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

extract to a helper function, use 3 times.
</blockquote></details>

only used 2 time now :)
___
*[`crates/cairo-lang-lowering/src/graph_algorithms/concrete_function_postiniline_node.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4153#-NfLXYcuDxRLfVsKW4ds:-NfLaUvU7LE7ttBaLDvx:brpmqc3) ([raw file](https://github.com/starkware-libs/cairo/blob/2e8142b67a4312c830aea1bb9e34631bf0e39a5d/crates/cairo-lang-lowering/src/graph_algorithms/concrete_function_postiniline_node.rs#L19)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it us used by `contains\_cycle`
</blockquote></details>

removed.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/db.rs` line 465 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4153#-NfLU3MH2dyX-PrjtkS6:-NfLbsoVBWkLkO7_U_Wn:b2ni8w0) ([raw file](https://github.com/starkware-libs/cairo/blob/4e9c432289ef10eb042233f7256709122059f8d7/crates/cairo-lang-lowering/src/db.rs#L465)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

only used 2 time now :)
</blockquote></details>

nvm

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/graph_algorithms/concrete_function_postiniline_node.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4153#-NfLXYcuDxRLfVsKW4ds:-NfLbu9-3T90zMNdATNP:bh84rpb) ([raw file](https://github.com/starkware-libs/cairo/blob/2e8142b67a4312c830aea1bb9e34631bf0e39a5d/crates/cairo-lang-lowering/src/graph_algorithms/concrete_function_postiniline_node.rs#L19)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

removed.
</blockquote></details>

looks like it is nessiary.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4153)* status: 6 of 9 files reviewed, 5 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 359 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4153#-NfLTPbk72cGV2Ody59A:-NfdZrdQ6al2cB-Hew5i:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4e9c432289ef10eb042233f7256709122059f8d7/crates/cairo-lang-lowering/src/db.rs#L359)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/db.rs` line 431 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4153#-NfLTspf7pxBYolCD5PW:-NfdZtHI3J6vHHLzfeDK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4e9c432289ef10eb042233f7256709122059f8d7/crates/cairo-lang-lowering/src/db.rs#L431)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

extract to a helper function
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4153#-:-Nfdppan2Hd-0PZfzlPx:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4153)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 413 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4153#-NfeL81k-Vj7RsjVQS0C:-NfeL81k-Vj7RsjVQS0D:bfuhg7b) ([raw file](https://github.com/starkware-libs/cairo/blob/9529e32a3baa66253f7378b2ddf7d7e30275f2da/crates/cairo-lang-lowering/src/db.rs#L413)):*
> ```XML
> }
> 
> fn get_direct_callees(lowered_function: &FlatLowered) -> Vec<ids::FunctionId> {
> ```

please doc.
___
*[`crates/cairo-lang-lowering/src/db.rs` line 444 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4153#-NfeLbAmBM-R0xFatHOQ:-NfeLbAmBM-R0xFatHOR:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/9529e32a3baa66253f7378b2ddf7d7e30275f2da/crates/cairo-lang-lowering/src/db.rs#L444)):*
> ```XML
> }
> 
> fn functions_with_body_from_function_ids(
> ```

doc

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4153)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 413 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4153#-NfeL81k-Vj7RsjVQS0C:-NfedBnm81wPJBEOOqFY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9529e32a3baa66253f7378b2ddf7d7e30275f2da/crates/cairo-lang-lowering/src/db.rs#L413)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

please doc.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/db.rs` line 444 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4153#-NfeLbAmBM-R0xFatHOQ:-NfedErN5KcQgZIDnxr9:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/9529e32a3baa66253f7378b2ddf7d7e30275f2da/crates/cairo-lang-lowering/src/db.rs#L444)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

doc
</blockquote></details>

done

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4153)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 426 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4153#-NfefzpyAHwbCM1cOqU8:-NfefzpyAHwbCM1cOqU9:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/580261c6ec12318af0c6aba1e36d9d9811e7c2b1/crates/cairo-lang-lowering/src/db.rs#L426)):*
> ```XML
>         }
>     }
>     Ok(direct_callees)
> ```





_Suggestion:_
```XML
    Ok(get_direct_callees(&db.priv_concrete_function_with_body_lowered_flat(function_id)?))
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4153)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 426 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4153#-NfefzpyAHwbCM1cOqU8:-NfeihlF6VimtkEWkTrb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/580261c6ec12318af0c6aba1e36d9d9811e7c2b1/crates/cairo-lang-lowering/src/db.rs#L426)):*
> ```XML
>         }
>     }
>     Ok(direct_callees)
> ```

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4153)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4153#-:-Nfetsz44vV3rkPURQsl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
