### PR TITLE
Keep track of aliases instead of copying use sites.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4997)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/cancel_ops.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4997#-Npoz4Iq2r-K4iq9vP76:-Npoz4Iq2r-K4iq9vP77:b-gkc2qa) ([raw file](https://github.com/starkware-libs/cairo/blob/2789b60a15223b465841d88888d23c9c3e27946d/crates/cairo-lang-lowering/src/optimizations/cancel_ops.rs#L88)):*
> ```XML
>         // Move `from` used sites to `to` to allow the optimization to be applied to them.
>         if let Some(from_use_sites) = self.use_sites.remove(&from) {
>             self.use_sites.entry(to).or_default().extend(from_use_sites);
> ```

Keeping track of aliases instead of copying the use site allows me to also keep track of the alias variable id.



_Code quote:_
```XML
        // Move `from` used sites to `to` to allow the optimization to be applied to them.
        if let Some(from_use_sites) = self.use_sites.remove(&from) {
            self.use_sites.entry(to).or_default().extend(from_use_sites);
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4997)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/cancel_ops.rs` line 129 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4997#-Npp-GooApYvPseVgucY:-Npp-GooApYvPseVgucZ:b-kf9u63) ([raw file](https://github.com/starkware-libs/cairo/blob/8f28f1f75b3d69f722840386ce5d55c2c63bcd86/crates/cairo-lang-lowering/src/optimizations/cancel_ops.rs#L129)):*
> ```XML
>                 entry.insert(aliases);
>             }
>         }
> ```

unless the ordering is important within aliases.



_Suggestion:_
```XML
        self.aliases.entry(to).or_default().extend(chain!(
            [from], get_entry_as_slice(&self.aliases, &from).iter().copied()));
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4997)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/cancel_ops.rs` line 129 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4997#-Npp-GooApYvPseVgucY:-Npp0Mhg3XTpCRyzDRyF:b-qznwuf) ([raw file](https://github.com/starkware-libs/cairo/blob/8f28f1f75b3d69f722840386ce5d55c2c63bcd86/crates/cairo-lang-lowering/src/optimizations/cancel_ops.rs#L129)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

unless the ordering is important within aliases.
</blockquote></details>

It doesn't work, you borrow self.aliases  twice :(

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/cancel_ops.rs` line 129 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4997#-Npp-GooApYvPseVgucY:-Npp0SnGCCbRWBfiX9Xn:bqce097) ([raw file](https://github.com/starkware-libs/cairo/blob/8f28f1f75b3d69f722840386ce5d55c2c63bcd86/crates/cairo-lang-lowering/src/optimizations/cancel_ops.rs#L129)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

It doesn't work, you borrow self.aliases  twice :(
</blockquote></details>

we should start using unsafe rust :)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4997#-:-Npp1-Jw-AlJXyx7jzpn:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4997)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4997#-Npp1NXC5WeE0i_XNGpM:-Npp1NXC5WeE0i_XNGpN:btygqh6) (no related file):*
this changes code apparently - do you know why?

___

**Comment by ilyalesokhin-starkware** [comment]
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this changes code apparently - do you know why?
</blockquote></details>

Can you point me to the code that changed?

Maybe it is because of the `remove` here:
https://github.com/starkware-libs/cairo/blob/133ee0e5b2f1ef12696fce781212a201e3018b2b/crates/cairo-lang-lowering/src/optimizations/cancel_ops.rs#L87

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4997)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4997#-Npp1NXC5WeE0i_XNGpM:-NppAszWC82xXlLfoBiR:b-bcxlle) (no related file):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Can you point me to the code that changed?

Maybe it is because of the `remove` here:
https://github.com/starkware-libs/cairo/blob/133ee0e5b2f1ef12696fce781212a201e3018b2b/crates/cairo-lang-lowering/src/optimizations/cancel_ops.rs#L87
</blockquote></details>

before there was a failing test - where the profiling changed - but now i don't see it.

___

**Pull request merged**
