### PR TITLE
Move literal parsing logic to syntax crate and use it everywhere possible

### PR DESCRIPTION
**Pull request by mkaput**
**Stack**:
- #2780 ⬅
- #2803
- #2814

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2780)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 10 of 14 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2780)* status: 10 of 14 files reviewed, 1 unresolved discussion (waiting on @mkaput and @spapinistarkware)

___
*[`crates/cairo-lang-syntax/src/node/literal_value.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2780#-NSpjuzN0zoA94-qr5s4:-NSpjuzN0zoA94-qr5s5:b-actekd) ([raw file](https://github.com/starkware-libs/cairo/blob/23079419b067014baba8288e23f55597cc2ce936/crates/cairo-lang-syntax/src/node/literal_value.rs#L49)):*
> ```XML
> 
>     /// Interpret this token/terminal as a [`Felt252`] number.
>     fn felt252_value(&self, db: &dyn SyntaxGroup) -> LiteralValueResult<Felt252> {
> ```

remove Felt252 dep from the syntax crate.



_Code quote:_
```XML
    /// Interpret this token/terminal as a [`Felt252`] number.
    fn felt252_value(&self, db: &dyn SyntaxGroup) -> LiteralValueResult<Felt252> {
        self.bigint_value(db).map(Felt252::new)
    }
```

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2780)* status: 9 of 14 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-syntax/src/node/literal_value.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2780#-NSpjuzN0zoA94-qr5s4:-NStaQox8FcPrWQ9OyXg:b-tkdmy3) ([raw file](https://github.com/starkware-libs/cairo/blob/23079419b067014baba8288e23f55597cc2ce936/crates/cairo-lang-syntax/src/node/literal_value.rs#L49)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove Felt252 dep from the syntax crate.
</blockquote></details>

may I ask why?

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2780)* status: 10 of 14 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-syntax/src/node/literal_value.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2780#-NSpjuzN0zoA94-qr5s4:-NStrnEj5mjmkAYDSlqo:b-umgw4s) ([raw file](https://github.com/starkware-libs/cairo/blob/23079419b067014baba8288e23f55597cc2ce936/crates/cairo-lang-syntax/src/node/literal_value.rs#L49)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

because i don't want the high level crates be dependent on a casm level library.
</blockquote></details>

Done.

OK, it's debatable to me, but it's not super important as this method is just a shortcut used only by test crate currently

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2780)* status: 9 of 14 files reviewed, 1 unresolved discussion (waiting on @mkaput and @spapinistarkware)

___
*[`crates/cairo-lang-syntax/src/node/literal_value.rs` line 11 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2780#-NStu1ea-mSVTZt2DU8u:-NStu1ea-mSVTZt2DU8v:b-4d0r0d) ([raw file](https://github.com/starkware-libs/cairo/blob/35feee7ed961d3eea1252e56b983089a819da289/crates/cairo-lang-syntax/src/node/literal_value.rs#L11)):*
> ```XML
> 
> /// Error type returned from literal value traits methods.
> #[derive(thiserror::Error, Debug)]
> ```

if you get this error at the syntax stage - shouldn't you just add diagnostic to it at that stage?



_Code quote:_
```XML
/// Error type returned from literal value traits methods.
#[derive(thiserror::Error, Debug)]
pub enum LiteralValueError {
    #[error("Invalid numeric literal.")]
    ParseBigIntError(#[from] num_bigint::ParseBigIntError),
    #[error("Invalid string escaping:\n{0}")]
    UnescapeError(#[from] unescaper::Error),
    #[error("Short strings can only include ASCII characters.")]
    ShortStringMustBeAscii,
}
```

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2780)* status: 9 of 14 files reviewed, 1 unresolved discussion (waiting on @mkaput, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-syntax/src/node/literal_value.rs` line 11 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2780#-NStu1ea-mSVTZt2DU8u:-NStv2J419EnQlJJyQwk:bhenfue) ([raw file](https://github.com/starkware-libs/cairo/blob/35feee7ed961d3eea1252e56b983089a819da289/crates/cairo-lang-syntax/src/node/literal_value.rs#L11)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

if you get this error at the syntax stage - shouldn't you just add diagnostic to it at that stage?
</blockquote></details>

Hmm, good catch. I'll investigate it. I'm afraid there may be some cases when invalid literal is totally fine because for example it is ignored or smth.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, 9 of 15 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2780)* status: 11 of 17 files reviewed, 1 unresolved discussion (waiting on @mkaput and @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 5 of 15 files at r6, 4 of 4 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2780)* status: all files reviewed, 2 unresolved discussions (waiting on @mkaput and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2780#-NT28QTv2Zbx6Ew8hrjP:-NT28QTv2Zbx6Ew8hrjQ:b-hndyi8) (no related file):*
so where are the diagnostics added now?

___

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2780)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2780#-NT28QTv2Zbx6Ew8hrjP:-NT3HbLADKKLB5xKr1Ia:bk3h2hd) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

so where are the diagnostics added now?
</blockquote></details>

I am going to add them in #2803 

___
___
*[`crates/cairo-lang-syntax/src/node/literal_value.rs` line 11 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2780#-NStu1ea-mSVTZt2DU8u:-NT3HiP93SGxzsyP65qa:bk3h2hd) ([raw file](https://github.com/starkware-libs/cairo/blob/35feee7ed961d3eea1252e56b983089a819da289/crates/cairo-lang-syntax/src/node/literal_value.rs#L11)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Hmm, good catch. I'll investigate it. I'm afraid there may be some cases when invalid literal is totally fine because for example it is ignored or smth.
</blockquote></details>

I am going to add them in #2803

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2780)* status: 10 of 17 files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2780#-NT28QTv2Zbx6Ew8hrjP:-NTDgEcB8phhNEVGhUm8:bb6un1j) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I am going to add them in #2803 
</blockquote></details>

Done

___

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2780)* status: 10 of 17 files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-syntax/src/node/literal_value.rs` line 11 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2780#-NStu1ea-mSVTZt2DU8u:-NTDgH9W451lhLl3jI78:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/35feee7ed961d3eea1252e56b983089a819da289/crates/cairo-lang-syntax/src/node/literal_value.rs#L11)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I am going to add them in #2803 
</blockquote></details>

Done

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2780#-:-NTEB3jV8f61jXCcelps:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
