### PR TITLE
added closure impl

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6098)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 307 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6098#-O3CAPEkDwWRxHFpgDaW:-O3CAPEmBpo2Yq-42ZYT:b4xfkng) ([raw file](https://github.com/starkware-libs/cairo/blob/bc8cbe3de11b43131bd491d95182be68893ac399/crates/cairo-lang-semantic/src/items/imp.rs#L307)):*
> ```XML
>     pub args: Vec<TypeId>,
>     pub ret: TypeId,
> }
> ```

what do you thing about?
you can deduce all the information from the ConcreteTraitId, right?



_Suggestion:_
```XML
pub struct GeneratedImplId {
    pub trait_id: ConcreteTraitId,
}
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6098)* status: 2 of 11 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 307 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6098#-O3CAPEkDwWRxHFpgDaW:-O3ChGTQDQ3SLY2wiMdN:b-5ldxji) ([raw file](https://github.com/starkware-libs/cairo/blob/bc8cbe3de11b43131bd491d95182be68893ac399/crates/cairo-lang-semantic/src/items/imp.rs#L307)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what do you thing about?
you can deduce all the information from the ConcreteTraitId, right?
</blockquote></details>

the return type is not in the concrete trait,

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 307 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6098#-O3CAPEkDwWRxHFpgDaW:-O3ClPDq81Z4WVA0fuDf:b-ixz3bb) ([raw file](https://github.com/starkware-libs/cairo/blob/bc8cbe3de11b43131bd491d95182be68893ac399/crates/cairo-lang-semantic/src/items/imp.rs#L307)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

the return type is not in the concrete trait,
</blockquote></details>

The concrete trait is generic in the closure type which has the return type.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r1, 4 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6098)* status: 5 of 19 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`corelib/src/lib.cairo` line 379 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6098#-O3aoRsm9pSylB4_Zp8g:-O3aoRsm9pSylB4_Zp8h:b-hay66z) ([raw file](https://github.com/starkware-libs/cairo/blob/ad4afc10bb6a733da0ae3afd270e12e07fa1863e/corelib/src/lib.cairo#L379)):*
> ```Cairo
> pub mod iter;
> 
> /// Function.
> ```

revert.
___
*[`corelib/src/ops.cairo` line 11 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6098#-O3aoUfKD3aSv5QB8ZUM:-O3aoUfKD3aSv5QB8ZUN:b-d2gnva) ([raw file](https://github.com/starkware-libs/cairo/blob/ad4afc10bb6a733da0ae3afd270e12e07fa1863e/corelib/src/ops.cairo#L11)):*
> ```Cairo
> pub use deref::DerefMut;
> 
> pub mod function;
> ```

should the mod be pub?

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 15 files at r2, 15 of 15 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6098)* status: all files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6098)* status: 17 of 19 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`corelib/src/lib.cairo` line 379 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6098#-O3aoRsm9pSylB4_Zp8g:-O3ls5Gy7yWDLImhmJZX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ad4afc10bb6a733da0ae3afd270e12e07fa1863e/corelib/src/lib.cairo#L379)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

revert.
</blockquote></details>

Done.
___
*[`corelib/src/ops.cairo` line 11 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6098#-O3aoUfKD3aSv5QB8ZUM:-O3ls5us0jBJwbeMPKvZ:b32wsm) ([raw file](https://github.com/starkware-libs/cairo/blob/ad4afc10bb6a733da0ae3afd270e12e07fa1863e/corelib/src/ops.cairo#L11)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

should the mod be pub?
</blockquote></details>

no
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 307 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6098#-O3CAPEkDwWRxHFpgDaW:-O3jRSKc2zrZ-q8yJlZ4:b-hm0ll1) ([raw file](https://github.com/starkware-libs/cairo/blob/bc8cbe3de11b43131bd491d95182be68893ac399/crates/cairo-lang-semantic/src/items/imp.rs#L307)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

The concrete trait is generic in the closure type which has the return type.
</blockquote></details>

rebased
___
*[`corelib/src/function/traits/functions.cairo` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6098#-O37-XpQBvE21SExy2u3:-O3lvthZ4TnuAF0Ayuzo:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bc8cbe3de11b43131bd491d95182be68893ac399/corelib/src/function/traits/functions.cairo#L2)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc.
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6098)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6098)* status: 18 of 19 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`corelib/src/lib.cairo` line 379 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6098#-O3aoRsm9pSylB4_Zp8g:-O3m6ns81SaiL9tegzIe:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ad4afc10bb6a733da0ae3afd270e12e07fa1863e/corelib/src/lib.cairo#L379)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

not pushed.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6098#-:-O3mEo1u3yX6AhFppvmx:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6098)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1489 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6098#-O4AYDGo6wh3IZl3oZM_:-O4AYDGo6wh3IZl3oZMa:bho1v2i) ([raw file](https://github.com/starkware-libs/cairo/blob/2c2901ca3134577a890db3b7b7c2e5903f678016/crates/cairo-lang-semantic/src/items/imp.rs#L1489)):*
> ```XML
>             UninferredImpl::ImplImpl(impl_impl_id) => impl_impl_id.impl_id.into(),
>             UninferredImpl::GeneratedImpl(_) => {
>                 // GeneratedImpl are not looked up inside module.
> ```

I don't understand the comment.

Maybe something like I my suggestion



_Suggestion:_
```XML
  // GeneratedImpls do not extend the lookup context.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1647 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6098#-O4AYpX213eIAWJbawGi:-O4AYpX213eIAWJbawGj:b-5vzhgs) ([raw file](https://github.com/starkware-libs/cairo/blob/2c2901ca3134577a890db3b7b7c2e5903f678016/crates/cairo-lang-semantic/src/items/imp.rs#L1647)):*
> ```XML
>     filter: &TraitFilter,
> ) -> Option<UninferredImpl> {
>     if concrete_trait_id.trait_id(db) != filter.trait_id {
> ```

when can it not be the case?



_Code quote:_
```XML
if concrete_trait_id.trait_id(db) != filter.trait_id {
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6098)* status: 18 of 19 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1489 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6098#-O4AYDGo6wh3IZl3oZM_:-O4As-r_-nH6fMzj-KQ_:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/2c2901ca3134577a890db3b7b7c2e5903f678016/crates/cairo-lang-semantic/src/items/imp.rs#L1489)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't understand the comment.

Maybe something like I my suggestion
</blockquote></details>

done
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1647 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6098#-O4AYpX213eIAWJbawGi:-O4As_eZ03SCSfCa3lk-:bbfrznx) ([raw file](https://github.com/starkware-libs/cairo/blob/2c2901ca3134577a890db3b7b7c2e5903f678016/crates/cairo-lang-semantic/src/items/imp.rs#L1647)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

when can it not be the case?
</blockquote></details>

it cannot

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 7 of 11 files at r1, 1 of 15 files at r2, 9 of 15 files at r4, 1 of 2 files at r5, 2 of 3 files at r6, 1 of 1 files at r7, 2 of 2 files at r8, 6 of 6 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6098#-:-O4FzI1d9owSsrxZ_G09:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
