### PR TITLE
added validation for generic params of impl functions

### PR DESCRIPTION
**Pull request by TomerStarkware**

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6934)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 3169 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6934#-OF4H3f80BKzeLGrx0mL:-OF4H3f80BKzeLGrx0mM:bcxzg2l) ([raw file](https://github.com/starkware-libs/cairo/blob/2b0ac293f86efcf44b2d25aa2fe0f51f24484588/crates/cairo-lang-semantic/src/items/imp.rs#L3169)):*
> ```XML
>         }
>         match (generic_param, trait_generic_param) {
>             (GenericParam::Type(_), GenericParam::Type(_)) => {}
> ```

we should probably validate names here as well.
(same as we do in non-generic fn params)



_Code quote:_
```XML
            (GenericParam::Type(_), GenericParam::Type(_)) => {}
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6934)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 3169 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6934#-OF4H3f80BKzeLGrx0mL:-OF4e1rL25RBenD6JNxy:bjqf8br) ([raw file](https://github.com/starkware-libs/cairo/blob/2b0ac293f86efcf44b2d25aa2fe0f51f24484588/crates/cairo-lang-semantic/src/items/imp.rs#L3169)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

we should probably validate names here as well.
(same as we do in non-generic fn params)
</blockquote></details>

isn't it the validation I added in 5 lines above or you mean something else?

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6934)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 3169 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6934#-OF4H3f80BKzeLGrx0mL:-OF6C8oj6UjGyX4EOO5q:bpzamq6) ([raw file](https://github.com/starkware-libs/cairo/blob/2b0ac293f86efcf44b2d25aa2fe0f51f24484588/crates/cairo-lang-semantic/src/items/imp.rs#L3169)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

isn't it the validation I added in 5 lines above or you mean something else?
</blockquote></details>

no - i just missed it.
___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 1302 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6934#-OF6CJvP3gLQwWMQuyB3:-OF6CJvP3gLQwWMQuyB4:b-3mjial) ([raw file](https://github.com/starkware-libs/cairo/blob/f7a84b41175601c10c4907a7de5c8e359a2a793e/crates/cairo-lang-semantic/src/items/tests/trait#L1302)):*
> ```
> //! > ==========================================================================
> 
> //! > cycle with anonymous impl with impl alias instead of trait.
> ```

this test are deleted?

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6934)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/items/tests/trait` line 1302 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6934#-OF6CJvP3gLQwWMQuyB3:-OFI3XD1AEnx1y_WdsxS:bvth56w) ([raw file](https://github.com/starkware-libs/cairo/blob/e1338393d5f78c3c672360411119bd9c0224f79a/crates/cairo-lang-semantic/src/items/tests/trait#L1302)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this test are deleted?
</blockquote></details>

reverted

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6934#-:-OFKdD_g8cGoc-SiTFkQ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
