### PR TITLE
Refactored addresses update, and updating these for constructor.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #3897
- #3896 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3896)

### CODE REVIEW

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3896#-:-NbrsTka7IQiUvTYhlfZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 883 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3896#-NbrtYOR4Ln4boJjctEd:-NbrtYOR4Ln4boJjctEe:b-28y84) ([raw file](https://github.com/starkware-libs/cairo/blob/e43c9fdf83dbcc5b6fdfbc67d34ddc78a92a3b1a/crates/cairo-lang-runner/src/casm_run/mod.rs#L883)):*
> ```XML
>         let (res_data_start, res_data_end) = if let Some(constructor) = &contract_info.constructor {
>             let old_addrs =
>                 self.starknet_state.open_caller_context(deployed_contract_address.clone());
> ```

this should be based on `deploy\_from\_zero`
https://github.com/starkware-industries/starkware/blob/afdb639f5ed71322630c6f4c48d8cc2065bd0ece/src/starkware/starknet/core/os/execution/execute_syscalls.cairo#L472



_Code quote:_
```XML
deployed_contract_address.clone()
```

**Review by ilyalesokhin-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3896)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3896)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 883 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3896#-NbrtYOR4Ln4boJjctEd:-NbrvMSE-tUs3NrCyZZ7:b-bb0z0c) ([raw file](https://github.com/starkware-libs/cairo/blob/e43c9fdf83dbcc5b6fdfbc67d34ddc78a92a3b1a/crates/cairo-lang-runner/src/casm_run/mod.rs#L883)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

this should be based on `deploy\_from\_zero`
https://github.com/starkware-industries/starkware/blob/afdb639f5ed71322630c6f4c48d8cc2065bd0ece/src/starkware/starknet/core/os/execution/execute_syscalls.cairo#L472
</blockquote></details>

next pr.

**Pull request merged**
