### PR TITLE
Fix lifetime bug.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2198)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2198)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware, @liorgold2, and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-generator/src/lifetime.rs` line 147 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2198#-NOeRPybBFYkBUbzgnZw:-NOeRPybBFYkBUbzgnZx:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6eaac160b689ef4afd79963e1047c460b137fc50/crates/cairo-lang-sierra-generator/src/lifetime.rs#L147)):*
> ```XML
>             inner_find_variable_lifetime(context, *target_block_id, state);
>             if context.block_state.insert(*target_block_id, state.clone()).is_some() {
>                 panic!("block {target_block_id:?} lifetime was computed more than once.")
> ```





_Suggestion:_
```XML
            assert!(context.block_state.insert(*target_block_id, state.clone()).is_none(), {
                "block {target_block_id:?} lifetime was computed more than once.")
```

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2198#-:-NOeUDFc8viPQg3P8ycL:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @liorgold2)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2198)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/lifetime.rs` line 147 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2198#-NOeRPybBFYkBUbzgnZw:-NOhiIHz2t864RsZjmrR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6eaac160b689ef4afd79963e1047c460b137fc50/crates/cairo-lang-sierra-generator/src/lifetime.rs#L147)):*
> ```XML
>             inner_find_variable_lifetime(context, *target_block_id, state);
>             if context.block_state.insert(*target_block_id, state.clone()).is_some() {
>                 panic!("block {target_block_id:?} lifetime was computed more than once.")
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2198#-:-NOhnTq5-yZeyuldhGXZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
