### PR TITLE
Prevented starknet plugin from code generation on items not on config.

### LINKED ISSUE #4897: bug: code annotated with cfg(test) included in build
# Bug Report

**Cairo version:** 

2.5.0 (was fine in 2.2.0)

**Current behavior:**

Contract that includes implementation annotated with `#[cfg(test)]` doesn't compile.
Works fine when running `scarb test`

**Related code:**

Code example:

```
#[cfg(test)]
#[starknet::interface]
trait ITests<TContractState> {
    fn set_value(ref self: TContractState, value: felt252);
}


#[starknet::contract]
mod MyContract {
    #[storage]
    struct Storage {
        value: felt252
    }

    #[cfg(test)]
    #[abi(embed_v0)]
    impl TestsImpl of super::ITests<ContractState> {
        fn set_value(ref self: ContractState, value: felt252) {
            self.value.write(value);
        }
    }
}
```

`scarb build` output:

```
error: Plugin diagnostic: Identifier not found.
 --> ...cairo:121:10
    impl TestsImpl of super::ITests<ContractState> {
         ^*******^


error: Identifier not found.
 --> ...cairo[contract]:24:20
        use super::TestsImpl;
                   ^*******^
```

### PR DESCRIPTION
**Pull request by orizi**
Fixes #4897

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4909)

### CODE REVIEW

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4909)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @orizi, and @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4909#-Nox153qCKRzItm4MIRD:-Nox153qCKRzItm4MIRE:b-hyp6ww) (no related file):*
I don't want to block the work on this, but I am super afraid of this change. It's just a matter of time when similar situation will pop in a different plugin or something. Shouldn't there be a way to do some kind of plugin recursion?

___

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4909)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @mkaput, and @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4909#-Nox153qCKRzItm4MIRD:-NoxGHhy6eEJqJYOX4SN:b-yg4ar) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I don't want to block the work on this, but I am super afraid of this change. It's just a matter of time when similar situation will pop in a different plugin or something. Shouldn't there be a way to do some kind of plugin recursion?
</blockquote></details>

There is already recursion, but we originally run on text.

___

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4909)* status: all files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware, @mkaput, and @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs` line 54 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4909#-NozFkPLEkkoFY8HIHt3:-NozFkPLEkkoFY8HIHt4:bgtrtq) ([raw file](https://github.com/starkware-libs/cairo/blob/c821a4ee3c6191f3b04824a3e2da05a314c506cb/crates/cairo-lang-starknet/src/plugin/starknet_module/component.rs#L54)):*
> ```XML
> pub(super) fn generate_component_specific_code(
>     db: &dyn SyntaxGroup,
>     metadata: &MacroPluginMetadata<'_>,
> ```

move after diagnostics
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 302 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4909#-NozGKGm7bCqNzBw5L6_:-NozGKGm7bCqNzBw5L6a:b5c28eb) ([raw file](https://github.com/starkware-libs/cairo/blob/c821a4ee3c6191f3b04824a3e2da05a314c506cb/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L302)):*
> ```XML
> pub(super) fn generate_contract_specific_code(
>     db: &dyn SyntaxGroup,
>     metadata: &MacroPluginMetadata<'_>,
> ```

after diagnostics
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/mod.rs` line 179 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4909#-NozGOF9053brejAVm1Z:-NozGOF9053brejAVm1_:b-j7y3na) ([raw file](https://github.com/starkware-libs/cairo/blob/c821a4ee3c6191f3b04824a3e2da05a314c506cb/crates/cairo-lang-starknet/src/plugin/starknet_module/mod.rs#L179)):*
> ```XML
>     let mut extra_uses = OrderedHashMap::default();
>     for item in body.items(db).elements(db) {
>         if should_drop(db, metadata.cfg_set, &item, &mut vec![]) {
> ```

Let's add an non-dropped-items iteration function, and add a note comment on the original .items() that it should not be used for plugins directly.
This will also mostly resolve Marek's concern.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 7 of 10 files at r3, 3 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4909)* status: all files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 59 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4909#-Np-WJjk0ha4ybTNrgCm:-Np-WJjk0ha4ybTNrgCn:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/cd32c7a90b34cacb00278bc84f23f6a4ddcef7d7/crates/cairo-lang-plugins/src/plugins/config.rs#L59)):*
> ```XML
> }
> 
> /// Iterator over items in a scope that would remain in config.
> ```





_Suggestion:_
```XML
/// Iterator over the items that are included in the given config set, among the given items.
```
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 60 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4909#-Np-WozF8EsDDa-rhRn5:-Np-WozF8EsDDa-rhRn6:b-ahj24l) ([raw file](https://github.com/starkware-libs/cairo/blob/cd32c7a90b34cacb00278bc84f23f6a4ddcef7d7/crates/cairo-lang-plugins/src/plugins/config.rs#L60)):*
> ```XML
> 
> /// Iterator over items in a scope that would remain in config.
> pub struct InCfg<'a, ScopeItem: QueryAttrs, ScopeItems: Iterator<Item = ScopeItem>> {
> ```

The word "scope" everywhere is not necessary if you get the list (iterator) of items as a param.
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 60 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4909#-Np-bj2g9sHEwQNInVW2:-Np-bj2g9sHEwQNInVW3:b65f7cb) ([raw file](https://github.com/starkware-libs/cairo/blob/cd32c7a90b34cacb00278bc84f23f6a4ddcef7d7/crates/cairo-lang-plugins/src/plugins/config.rs#L60)):*
> ```XML
> 
> /// Iterator over items in a scope that would remain in config.
> pub struct InCfg<'a, ScopeItem: QueryAttrs, ScopeItems: Iterator<Item = ScopeItem>> {
> ```

Better name please?



_Code quote:_
```XML
InCfg
```
___
*[`crates/cairo-lang-starknet/src/plugin/embeddable.rs` line 121 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4909#-Np-cheg9mXZ6xrHRmJS:-Np-chehB6ZQ6IpNP1Y5:b-w8mwcl) ([raw file](https://github.com/starkware-libs/cairo/blob/cd32c7a90b34cacb00278bc84f23f6a4ddcef7d7/crates/cairo-lang-starknet/src/plugin/embeddable.rs#L121)):*
> ```XML
>     };
>     let mut data = EntryPointsGenerationData::default();
>     for item in InCfg::new(db, metadata.cfg_set, body.items(db).elements(db)) {
> ```

Would be nice to have it like this



_Suggestion:_
```XML
  for item in InCfg::new(db, metadata.cfg_set, body) {
```
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/mod.rs` line 179 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4909#-NozGOF9053brejAVm1Z:-Np-csp_9OBOwM_kpB5d:bgpwime) ([raw file](https://github.com/starkware-libs/cairo/blob/c821a4ee3c6191f3b04824a3e2da05a314c506cb/crates/cairo-lang-starknet/src/plugin/starknet_module/mod.rs#L179)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can you also do the note-comment part from above?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4909)* status: 3 of 13 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 60 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4909#-Np-WozF8EsDDa-rhRn5:-Np0C00B3dpnQ3ok5GFN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cd32c7a90b34cacb00278bc84f23f6a4ddcef7d7/crates/cairo-lang-plugins/src/plugins/config.rs#L60)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

The word "scope" everywhere is not necessary if you get the list (iterator) of items as a param.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 60 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4909#-Np-bj2g9sHEwQNInVW2:-Np0C0InBMrMrmnJG8AT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cd32c7a90b34cacb00278bc84f23f6a4ddcef7d7/crates/cairo-lang-plugins/src/plugins/config.rs#L60)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Better name please?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/embeddable.rs` line 121 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4909#-Np-cheg9mXZ6xrHRmJS:-Np0C6RdCEhHgVM0WeM6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cd32c7a90b34cacb00278bc84f23f6a4ddcef7d7/crates/cairo-lang-starknet/src/plugin/embeddable.rs#L121)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Would be nice to have it like this
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/mod.rs` line 179 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4909#-NozGOF9053brejAVm1Z:-Np0CB7612jAqbAhFJPu:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/c821a4ee3c6191f3b04824a3e2da05a314c506cb/crates/cairo-lang-starknet/src/plugin/starknet_module/mod.rs#L179)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Can you also do the note-comment part from above?
</blockquote></details>

?

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4909)* status: all files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 59 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4909#-Np0OTot5HnOWd_PxVnN:-Np0OTouAg09MoolowJy:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/4d3aec5f3733086715727cd2cbac9e8c66ac2658/crates/cairo-lang-plugins/src/plugins/config.rs#L59)):*
> ```XML
> }
> 
> /// Iterator over the items that are included in the given config set, among the given items.
> ```





_Suggestion:_
```XML
ven config set, among the given items in `iterator`.
```
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 60 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4909#-Np0QND68S6_o1jKYn5t:-Np0QND68S6_o1jKYn5u:b-30g64n) ([raw file](https://github.com/starkware-libs/cairo/blob/4d3aec5f3733086715727cd2cbac9e8c66ac2658/crates/cairo-lang-plugins/src/plugins/config.rs#L60)):*
> ```XML
> 
> /// Iterator over the items that are included in the given config set, among the given items.
> pub struct ItemsInCfg<'a, Item: QueryAttrs> {
> ```

does it still need to be pub?



_Code quote:_
```XML
pub 
```
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 69 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4909#-Np0Pemh5hn97CKRtGq5:-Np0Pemh5hn97CKRtGq6:b9vnjfb) ([raw file](https://github.com/starkware-libs/cairo/blob/4d3aec5f3733086715727cd2cbac9e8c66ac2658/crates/cairo-lang-plugins/src/plugins/config.rs#L69)):*
> ```XML
>         Self { db, cfg_set, iterator: items.into_iter() }
>     }
> }
> ```

if my default implementation suggestion (below) applies, then this is used only once and can be removed.
Even if not, I don't see its value as it simply assigns all the values (and the ctor can be more readable with named args).



_Code quote:_
```XML
impl<'a, Item: QueryAttrs> ItemsInCfg<'a, Item> {
    fn new(db: &'a dyn SyntaxGroup, cfg_set: &'a CfgSet, items: Vec<Item>) -> Self {
        Self { db, cfg_set, iterator: items.into_iter() }
    }
}
```
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 99 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4909#-Np0OxGo7nOxUzygMgSq:-Np0OxGo7nOxUzygMgSr:b8aljkr) ([raw file](https://github.com/starkware-libs/cairo/blob/4d3aec5f3733086715727cd2cbac9e8c66ac2658/crates/cairo-lang-plugins/src/plugins/config.rs#L99)):*
> ```XML
>         cfg_set: &'a CfgSet,
>     ) -> ItemsInCfg<'a, Self::Item> {
>         ItemsInCfg::new(db, cfg_set, self.items(db).elements(db))
> ```

I think this function impl can be moved to the trait (as it's the same for all), and then the impls are very short (only the `type Item` required).



_Code quote:_
```XML
ItemsInCfg::new(db, cfg_set, self.items(db).elements(db))
```
___
*[`crates/cairo-lang-starknet/src/plugin/embeddable.rs` line 121 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4909#-Np-cheg9mXZ6xrHRmJS:-Np0QIBg2icVdU223kcy:bszm2f7) ([raw file](https://github.com/starkware-libs/cairo/blob/cd32c7a90b34cacb00278bc84f23f6a4ddcef7d7/crates/cairo-lang-starknet/src/plugin/embeddable.rs#L121)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Much better!
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/mod.rs` line 179 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4909#-NozGOF9053brejAVm1Z:-Np0Ql0pDOqk7JFO4EsM:bnmc3l6) ([raw file](https://github.com/starkware-libs/cairo/blob/c821a4ee3c6191f3b04824a3e2da05a314c506cb/crates/cairo-lang-starknet/src/plugin/starknet_module/mod.rs#L179)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

"and add a note comment on the original .items() that it should not be used for plugins directly."
So that anyone who may want to do it and want to use .items() directly will (probably) see the comment which will point them to the good way to do it.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4909)* status: all files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 60 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4909#-Np0QND68S6_o1jKYn5t:-Np0_dBv1jvcnC3hNEQo:b4snyh7) ([raw file](https://github.com/starkware-libs/cairo/blob/4d3aec5f3733086715727cd2cbac9e8c66ac2658/crates/cairo-lang-plugins/src/plugins/config.rs#L60)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

does it still need to be pub?
</blockquote></details>

yes - it is returned by the trait function.
___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/mod.rs` line 179 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4909#-NozGOF9053brejAVm1Z:-Np0aanEC3Jfa7yRoSQx:bx2cdt4) ([raw file](https://github.com/starkware-libs/cairo/blob/c821a4ee3c6191f3b04824a3e2da05a314c506cb/crates/cairo-lang-starknet/src/plugin/starknet_module/mod.rs#L179)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

"and add a note comment on the original .items() that it should not be used for plugins directly."
So that anyone who may want to do it and want to use .items() directly will (probably) see the comment which will point them to the good way to do it.
</blockquote></details>

it is on the generated ast code...

also - in general we need it just for elements where we go up and then back down.
when processing others - we always use `config` plugin first - and only then other plugins - so we won't process non-config elements.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4909)* status: 6 of 15 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 69 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4909#-Np0Pemh5hn97CKRtGq5:-Np0ka_N2fJ5l0Z-2dAl:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4d3aec5f3733086715727cd2cbac9e8c66ac2658/crates/cairo-lang-plugins/src/plugins/config.rs#L69)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

if my default implementation suggestion (below) applies, then this is used only once and can be removed.
Even if not, I don't see its value as it simply assigns all the values (and the ctor can be more readable with named args).
</blockquote></details>

Done.
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 99 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4909#-Np0OxGo7nOxUzygMgSq:-Np0kbB2BDTvhtpnCiyU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4d3aec5f3733086715727cd2cbac9e8c66ac2658/crates/cairo-lang-plugins/src/plugins/config.rs#L99)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I think this function impl can be moved to the trait (as it's the same for all), and then the impls are very short (only the `type Item` required).
</blockquote></details>

Done.

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 3 of 10 files at r6, 9 of 9 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4909)* status: all files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4909#-:-NpF3fXz4TCglX9kg6-D:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

**Review by yuvalsw — CHANGES_REQUESTED** [review]
As discussed f2f, please re-check all places - we don't need the filtered iter when we are traversing the tree only through impls, traits and the current (sub)module. If we potentially go through another submodule, we might have the problem and need the filtered iter.

> Reviewed 7 of 9 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4909#-:-NpFJ52mBl7QbyNeha13:b-hdy3hl)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 69 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4909#-Np0Pemh5hn97CKRtGq5:-NpFDAsA84eZn19sEiBT:bxecfv9) ([raw file](https://github.com/starkware-libs/cairo/blob/4d3aec5f3733086715727cd2cbac9e8c66ac2658/crates/cairo-lang-plugins/src/plugins/config.rs#L69)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I still see it. I meant ::new() can be removed. It is used once.
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 82 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4909#-NpFCk6y-f6CRmTdGLfo:-NpFCk6y-f6CRmTdGLfp:b-diivpt) ([raw file](https://github.com/starkware-libs/cairo/blob/764ce49f6872b3a7123d381dc3bdec830ec2895f/crates/cairo-lang-plugins/src/plugins/config.rs#L82)):*
> ```XML
> /// Trait for AST nodes that contain items, providing an iterator over the items that are included
> /// in the cfg.
> pub trait HasItemsInCfgEx {
> ```

why ex?
___
*[`crates/cairo-lang-syntax/src/node/helpers.rs` line 564 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4909#-NpFBNoZ01xv5TNS0R4-:-NpFBNoZ01xv5TNS0R40:b-3qnc53) ([raw file](https://github.com/starkware-libs/cairo/blob/764ce49f6872b3a7123d381dc3bdec830ec2895f/crates/cairo-lang-syntax/src/node/helpers.rs#L564)):*
> ```XML
> }
> 
> /// Trait for getting the items of a node that contains items as a vector.
> ```

suggestion



_Suggestion:_
```XML
/// Trait for getting the items of a body-item (an item that contains items), as a vector.
```
___
*[`crates/cairo-lang-syntax/src/node/helpers.rs` line 571 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4909#-NpFC1ArDqGcjlr8YuNH:-NpFC1ArDqGcjlr8YuNI:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/764ce49f6872b3a7123d381dc3bdec830ec2895f/crates/cairo-lang-syntax/src/node/helpers.rs#L571)):*
> ```XML
>     /// Use with caution, as this will include items that may be filtered out by plugins.
>     /// Do note that plugins that directly ran on this node without going up on the syntax tree may
>     /// assume that out of config items were already filtered out.
> ```





_Suggestion:_
```XML
    /// Returns the items of the body-item as a vector.
    /// Use with caution, as this includes items that may be filtered out by plugins.
    /// Do note that plugins that directly run on this body-item without going/checking up on the syntax tree may
    /// assume that e.g. out-of-config items were already filtered out.
```

**Comment by yuvalsw** [comment]
Also, please doc it where you don't use the filtered iter. Until we fix it in a better way (e.g. allow generation of code inside an item and not only beside it), we need to make sure that new plugins (that will copy code from existing ones) will note this issue and handle it correctly. Use a one sentence summary of our conversation to explain the rule and its rational.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4909)* status: 13 of 15 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 69 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4909#-Np0Pemh5hn97CKRtGq5:-NpFK3bu-n312AoOwd47:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4d3aec5f3733086715727cd2cbac9e8c66ac2658/crates/cairo-lang-plugins/src/plugins/config.rs#L69)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I still see it. I meant ::new() can be removed. It is used once.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 82 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4909#-NpFCk6y-f6CRmTdGLfo:-NpFK5u0EERY9ouakfJf:b-mdc4ad) ([raw file](https://github.com/starkware-libs/cairo/blob/764ce49f6872b3a7123d381dc3bdec830ec2895f/crates/cairo-lang-plugins/src/plugins/config.rs#L82)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

why ex?
</blockquote></details>

It is a general marker for externsion trait.

**Review by orizi — COMMENTED** [review]
that seems to me like comments without a clear effect.
i think the doc on the actual function should suffice - if not we should call the function an `extremely_long_documenting_name`.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4909#-:-NpFN8PI-1AhFBV-Yj__:b-uejnlo)* status: 13 of 15 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
I meant something like:
in items_vec(): doc when it's ok to use and when it's not. E.g.: don't use on an item that is not the original plugin's context, unless you are sure that while traversing the AST to get to it from the original plugin's context, you did not go through another submodule.

This explains when to use it. But then also explain why it's ok to use it when you do - the same as when you use .unwrap() when you're sure it won't panic.
Note that even with this, one might use .items().elements() and miss this potential bug.

It took a conversation of a few minutes for us to conclude the exact cases, a future plugin writer is probably not going to get into the details but copy from another plugin. I think it's worth helping to prevent this bug.

> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4909#-:-NpFcFRW0xRnYN-xdYCw:bc9uvd3)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 82 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4909#-NpFCk6y-f6CRmTdGLfo:-NpFbS1BDaAK3d0vIyil:bfnwbrd) ([raw file](https://github.com/starkware-libs/cairo/blob/764ce49f6872b3a7123d381dc3bdec830ec2895f/crates/cairo-lang-plugins/src/plugins/config.rs#L82)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

It is a general marker for externsion trait.
</blockquote></details>

I don't think AaaEx it is needed when there is no Aaa, but ok

**Review by orizi — COMMENTED** [review]
true - but having this in every usage makes no sense - having this in the doc - does.
If we wanna make sure we have this doc at every usage, we need to have a bad name instead.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4909#-:-NpFeEr4D0dVK0dZuWwJ:b-ep9yuv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by yuvalsw — APPROVED** [review]
There are only 4 uses: dispatcher, embeddable, generate_trait (go through items of impl/trait) and in starknet_module/mod.rs (which looks specifically for a struct).
I meant adding something like:
// OK to use `.items_vec()` as `x` is a trait. See `items_vec` for more details.

Also adding the comment on items_vec itself is important. See my suggestion above.

> Reviewed 2 of 9 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4909#-:-NpFqtLCDNuVOU6QFJWI:b-k7sr5n)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4909)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-syntax/src/node/helpers.rs` line 572 at r8](https://reviewable.io/reviews/starkware-libs/cairo/4909#-NpFsKQw7CcjAU8WItjb:-NpFsKQw7CcjAU8WItjc:be6afym) ([raw file](https://github.com/starkware-libs/cairo/blob/16dd96851f82f7bd0c14c95262aa0bf3bc58f36d/crates/cairo-lang-syntax/src/node/helpers.rs#L572)):*
> ```XML
>     /// Do note that plugins that directly run on this body-item without going/checking up on the
>     /// syntax tree may assume that e.g. out-of-config items were already filtered out.
>     fn items_vec(&self, db: &dyn SyntaxGroup) -> Vec<Self::Item>;
> ```

adding a blocking comment here as my other comment is nonblocking.

**Review by orizi — COMMENTED** [review]
as we discussed - for general usage - it is already correct - we are just adding a comment - that you say should be copied everywhere.
if it should be copied everywhere - it should be part of the name. if it shouldn't (which is what I think) the name should remain as is, and the doc on the function should be enough.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4909#-:-NpFu-lIDoP5RX_T0qpm:banc9gd)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4909)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-syntax/src/node/helpers.rs` line 572 at r8](https://reviewable.io/reviews/starkware-libs/cairo/4909#-NpFsKQw7CcjAU8WItjb:-NpFuR4c4yrZmh5SVzEp:bdi0j9o) ([raw file](https://github.com/starkware-libs/cairo/blob/16dd96851f82f7bd0c14c95262aa0bf3bc58f36d/crates/cairo-lang-syntax/src/node/helpers.rs#L572)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

adding a blocking comment here as my other comment is nonblocking.
</blockquote></details>

answered.

**Review by yuvalsw — COMMENTED** [review]
I didn't say it should be copied everywhere, but that the usages need to explain why it's ok to use, in each case. Again, the same as you would doc where you use .unwrap() and you know it won't panic.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4909#-:-NpGAj_22jATbSGDyhig:bkkw43i)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
i see no differentiation between places where you would add this - and places where you won't - and the reasoning in all places would be the same, unlike the unwrap case.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4909#-:-NpGB9Zx6xSaOLo6pvDw:bnm8l48)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4909)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-syntax/src/node/helpers.rs` line 572 at r8](https://reviewable.io/reviews/starkware-libs/cairo/4909#-NpFsKQw7CcjAU8WItjb:-NpGD5kD5Mxj3vp7gmDq:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/16dd96851f82f7bd0c14c95262aa0bf3bc58f36d/crates/cairo-lang-syntax/src/node/helpers.rs#L572)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

answered.
</blockquote></details>

.

**Review by yuvalsw — APPROVED** [review]
The reasoning is not the same. One is a trait, one is an impl, in another one you look specifically for a struct. In the future there may be one where it's a submodule, but for some reason you know it's ok.
Anyway, as discussed f2f, unblocking as I don't see this discussion converging.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4909#-:-NpGD6pzAf1ROVNMIxCl:b-hur37g)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4909#-:-NpGDXFo5Gvu4n0hiM7z:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
