### PR TITLE
Deploy and call failures

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2917)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2917** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2917" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2917?utm_source=stack-comment).

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/cairo_level_tests/interoperability.cairo` line 64 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2917#-NTi2MYB5h8BwA9WgtLY:-NTi2MYB5h8BwA9WgtLZ:b32vlc) ([raw file](https://github.com/starkware-libs/cairo/blob/f3f15789348a6e6acc457908c7c85e306af7da32/crates/cairo-lang-starknet/cairo_level_tests/interoperability.cairo#L64)):*
> ```Cairo
>     calldata.append(100);
>     let mut err = deploy_syscall(5.try_into().unwrap(), 0, calldata.span(), false).unwrap_err();
>     assert(err.pop_front().unwrap() == 'CLASS_HASH_NOT_FOUND', 'err == "CLASS_HASH_NOT_FOUND"');
> ```

?



_Suggestion:_
```Cairo
err != "CLASS_HASH_NOT_FOUND"'
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 586 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2917#-NTi2oBlE7T2gGi82faR:-NTi2oBlE7T2gGi82faS:bb7r2f0) ([raw file](https://github.com/starkware-libs/cairo/blob/f3f15789348a6e6acc457908c7c85e306af7da32/crates/cairo-lang-runner/src/casm_run/mod.rs#L586)):*
> ```XML
>                         // Call constructor if it exists.
>                         let res_data = if let Some(constructor) = &contract_info.constructor {
>                             // Replace the contract address in the context.
> ```

why?



_Code quote:_
```XML
 // Replace the contract address in the context.
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2917)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 602 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2917#-NTi6YZS7RqAgkyh6Jfz:-NTi6YZS7RqAgkyh6Jg-:b-gidoi3) ([raw file](https://github.com/starkware-libs/cairo/blob/f3f15789348a6e6acc457908c7c85e306af7da32/crates/cairo-lang-runner/src/casm_run/mod.rs#L602)):*
> ```XML
>                                     &[Arg::Array(values)],
>                                     // TODO(spapini): Assign the correct gas amount here.
>                                     Some(10000000000),
> ```

why can't you do it in this PR?



_Code quote:_
```XML
                                    // TODO(spapini): Assign the correct gas amount here.
                                    Some(10000000000),
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2917)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 586 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2917#-NTi2oBlE7T2gGi82faR:-NTi8aKG4ZYJPqhS-9Xa:bw0znxl) ([raw file](https://github.com/starkware-libs/cairo/blob/f3f15789348a6e6acc457908c7c85e306af7da32/crates/cairo-lang-runner/src/casm_run/mod.rs#L586)):*
> Replace the contract address in the context.
So that the current contract address will be the deployed on.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 602 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2917#-NTi6YZS7RqAgkyh6Jfz:-NTi8moo-n1zpsNxx7ep:btmpgmt) ([raw file](https://github.com/starkware-libs/cairo/blob/f3f15789348a6e6acc457908c7c85e306af7da32/crates/cairo-lang-runner/src/casm_run/mod.rs#L602)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why can't you do it in this PR?
</blockquote></details>

It's a bit more work, since check_handle_oog doesnt expose the gas, or how to change it.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/interoperability.cairo` line 64 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2917#-NTi2MYB5h8BwA9WgtLY:-NTiA2cn-ymm59gpIRiU:b-x8pelz) ([raw file](https://github.com/starkware-libs/cairo/blob/f3f15789348a6e6acc457908c7c85e306af7da32/crates/cairo-lang-starknet/cairo_level_tests/interoperability.cairo#L64)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

?
</blockquote></details>

This would be inconsistent with all the other cairo tests.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2917#-:-NTiBXUlE-mVrUAh7iBr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
