### PR TITLE
enable disallowing lists to end with a trailing with seperator

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4452)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4452)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-parser/src/diagnostic.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4452#-NjrX9mL71uUQBUiv8cQ:-NjrX9mL71uUQBUiv8cR:b71ehr2) ([raw file](https://github.com/starkware-libs/cairo/blob/2b1c784be09ed0fe164c633d95a7052edbdac808/crates/cairo-lang-parser/src/diagnostic.rs#L116)):*
> ```XML
>                 "Missing tokens. Expected a statement after attributes.".to_string()
>             }
>             ParserDiagnosticKind::DisallowedTrailingSeperator => {
> ```

Be more specific - there is only one disallowed type
___
*[`crates/cairo-lang-parser/src/parser.rs` line 2278 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4452#-NjrXHKQAX9A5HKwjqmp:-NjrXHKQAX9A5HKwjqmq:b-1lsokn) ([raw file](https://github.com/starkware-libs/cairo/blob/2b1c784be09ed0fe164c633d95a7052edbdac808/crates/cairo-lang-parser/src/parser.rs#L2278)):*
> ```XML
>         try_parse_list_element: fn(&mut Self) -> TryParseResult<Element::Green>,
>         should_stop: fn(SyntaxKind) -> bool,
>         expected_element: &'static str,
> ```

Provide only one optional param', this is redundant.

**Review by gilbens-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4452)* status: all files reviewed, 5 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 2279 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4452#-NjvSAWT4cSUqzRL8Mvb:-NjvSAWT4cSUqzRL8Mvc:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/3926eb963579e44dd5e815b926c5cb63048e1a7d/crates/cairo-lang-parser/src/parser.rs#L2279)):*
> ```XML
>         should_stop: fn(SyntaxKind) -> bool,
>         expected_element: &'static str,
>         allow_trailing_seperator: Option<ParserDiagnosticKind>,
> ```





_Suggestion:_
```XML
forbid_trailing_seperator
```
___
*[`crates/cairo-lang-parser/src/parser.rs` line 2288 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4452#-NjvS2l-8LbhKzRSzZ5C:-NjvS2l-8LbhKzRSzZ5D:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/3926eb963579e44dd5e815b926c5cb63048e1a7d/crates/cairo-lang-parser/src/parser.rs#L2288)):*
> ```XML
>             match try_parse_list_element(self) {
>                 Err(_) if should_stop(self.peek().kind) => {
>                     if let (Some(missing_kind), true) =
> ```





_Suggestion:_
```XML
diagnostic_kind
```
___
*[`crates/cairo-lang-parser/src/parser.rs` line 2323 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4452#-NjvU2WM58t_11Ss269m:-NjvU2WM58t_11Ss269n:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/3926eb963579e44dd5e815b926c5cb63048e1a7d/crates/cairo-lang-parser/src/parser.rs#L2323)):*
> ```XML
>         children
>     }
>     /// Calls parse_separated_list_inner with trailing seperator enabled
> ```





_Suggestion:_
```XML
    }

    /// Calls parse_separated_list_inner with trailing seperator enabled.
```

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4452)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @TomerStarkware)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4452)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 2279 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4452#-NjvSAWT4cSUqzRL8Mvb:-NkErfad1aRV-CIt4ByT:b9hblsv) ([raw file](https://github.com/starkware-libs/cairo/blob/3926eb963579e44dd5e815b926c5cb63048e1a7d/crates/cairo-lang-parser/src/parser.rs#L2279)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

Ori wanted a single variable of type option for the flag and the diagnostic kind, so I think allow_trailing _separator is easier to understand
</blockquote></details>

The single variable is fine. However, the `Some` variant of this param means that we forbid trailing separator and the `None` allows it, so I think that the param should be named `forbid_trailing_seperator`.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4452#-:-NkL4tlS4AzVpyzyvIWY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4452)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4452#-:-NlS1ntPAcZ8Wmohh69H:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
