### PR TITLE
Added storage access traits and used it in plugin.

### PR DESCRIPTION
**Pull request by orizi**
commit-id:6fbf9b3f

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1848)* status: 2 of 13 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1848#-NMOPrlKEreVUO0l3P75:-NMOPrlLCOxVWOzNIMJC:b-ovzyw2) (no related file):*
The casm grew. Is this because we cannot inline panicable functions yet?

___

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 11 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1848#-:-NMOQ-7iBhfkm4249mUG:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1848)* status: 6 of 13 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1848#-NMOPrlKEreVUO0l3P75:-NMOW4iI97pA9udqdoUY:b-kpsk9s) (no related file):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

The casm grew. Is this because we cannot inline panicable functions yet?
</blockquote></details>

added as much inlining as possible for now - the rest pending on this.

___

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1848)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
