### PR TITLE
Allow for warning only tests.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5864)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5864)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/tests` line 739 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5864#-O094MfD4FadTa-llkOW:-O094MfE3ll3V31IfA-I:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/93f5d0757300144bdb3670b67ff5abd382140128/crates/cairo-lang-semantic/src/diagnostic_test_data/tests#L739)):*
> ```
> 
> //! > test_runner_name
> test_expr_diagnostics(expect_diagnostics: warnings )
> ```





_Suggestion:_
```
test_expr_diagnostics(expect_diagnostics: warnings_only)
```
___
*[`crates/cairo-lang-test-utils/src/lib.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5864#-O094USC5fWKrWz0Dy8I:-O094USC5fWKrWz0Dy8J:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/93f5d0757300144bdb3670b67ff5abd382140128/crates/cairo-lang-test-utils/src/lib.rs#L106)):*
> ```XML
>         "false" => ExpectDiagnostics::None,
>         "true" => ExpectDiagnostics::Any,
>         "warnings" => ExpectDiagnostics::Warnings,
> ```





_Suggestion:_
```XML
        "warnings_only" => ExpectDiagnostics::Warnings,
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5864)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-test-utils/src/lib.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5864#-O096pAQ1CMRppb9BI2p:-O096pAQ1CMRppb9BI2q:b-qx4dc4) ([raw file](https://github.com/starkware-libs/cairo/blob/c8b9800b18387874f06af708bcfcd7e3692479ba/crates/cairo-lang-test-utils/src/lib.rs#L69)):*
> ```XML
>             if !has_diagnostics {
>                 return Some(
>                     "`expect_diagnostics` is 'warnings', but no diagnostics were generated.\n"
> ```

only (and bellow)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5864)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-test-utils/src/lib.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5864#-O096pAQ1CMRppb9BI2p:-O097GDB1UCpw8juhu0S:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c8b9800b18387874f06af708bcfcd7e3692479ba/crates/cairo-lang-test-utils/src/lib.rs#L69)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

only (and bellow)
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5864#-:-O09870uBKuM4ukmtqAr:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
