### PR TITLE
LS: multi-root workspace support

### PR DESCRIPTION
**Pull request by Arcticae**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6395)

### CODE REVIEW

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6395)* status: 11 of 14 files reviewed, 10 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`vscode-cairo/src/cairols.ts` line 267 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6395#-O8Ar3Ha2vtjevKqvLua:-O8Ar3Ha2vtjevKqvLub:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/153760866fecd16907784e3e95887645799e1f9b/vscode-cairo/src/cairols.ts#L267)):*
> ```XML
>     ...logEnv,
>     ...extraEnv,
>   };
> ```





_Suggestion:_
```XML
  const workspaceEnv = {
    CAIRO_LS_WORKSPACE_FOLDER: workspaceFolder.uri.fsPath
  };
  
  const logEnv = {
    CAIRO_LS_LOG: buildEnvFilter(ctx),
    RUST_BACKTRACE: "1",
  };

  const extraEnv = ctx.config.get("languageServerExtraEnv");

  serverExecutable.options ??= {};
  serverExecutable.options.env = {
    // Inherit env from parent process.
    ...process.env,
    ...(serverExecutable.options.env ?? {}),
    ...workspaceEnv,
    ...logEnv,
    ...extraEnv,
  };
```

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 3 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6395)* status: all files reviewed, 21 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`vscode-cairo/src/client.ts` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6395#-O98sb8Z0ZZPHjSmGxn0:-O98sb8Z0ZZPHjSmGxn1:b-72za30) ([raw file](https://github.com/starkware-libs/cairo/blob/153760866fecd16907784e3e95887645799e1f9b/vscode-cairo/src/client.ts#L9)):*
> ```XML
> export type WorkspacePath = string;
> export type ClientsMap = Map<WorkspacePath, lc.LanguageClient>;
> const clients: ClientsMap = new Map();
> ```

shouldn't this be put in `Context` so that we will ensure this state is recreated on extension reactivation?
___
*[`vscode-cairo/src/client.ts` line 26 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6395#-O98tSrA3C93q5N6dxyr:-O98tSrA3C93q5N6dxys:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/153760866fecd16907784e3e95887645799e1f9b/vscode-cairo/src/client.ts#L26)):*
> ```XML
>     const workspaceName = pathComponents[1];
>     if (!workspaceName) {
>       throw new Error(`Could not extract workspace name from path: ${uri.path}`);
> ```





_Suggestion:_
```XML
throw new Error(`could not extract workspace name from path: ${uri.path}`);
```
___
*[`vscode-cairo/src/client.ts` line 29 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6395#-O98uTLFAqSjLW3Ijd-A:-O98uTLFAqSjLW3Ijd-B:b-x8tos4) ([raw file](https://github.com/starkware-libs/cairo/blob/153760866fecd16907784e3e95887645799e1f9b/vscode-cairo/src/client.ts#L29)):*
> ```XML
>     }
>     matchFunction = ([k]) => {
>       return k.endsWith(workspaceName);
> ```

1. I don't think workspace name is unique, say what happens when I open `openzeppelin/cairo-contracts` and `software-mansion/cairo-contracts` in a single window?
2. I have suspicions this code is prone to problems when one workspace name is a prefix/suffix of another, say two workspaces: `core` and `ekubo-core`
___
*[`vscode-cairo/src/client.ts` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6395#-O98swuQEgZT3LyAas8j:-O98swuQEgZT3LyAas8k:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/153760866fecd16907784e3e95887645799e1f9b/vscode-cairo/src/client.ts#L56)):*
> ```XML
>     () => undefined,
>   );
> }
> ```





_Suggestion:_
```XML
export async function stopAllClients(): Promise<void> {
  await Promise.all(Array.from(clients.values()).map((client) => client.stop()));
}
```
___
*[`vscode-cairo/src/extension.ts` line 47 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6395#-O98rbcED5i3H1o2Rqf0:-O98rbcED5i3H1o2Rqf1:b-dz828i) ([raw file](https://github.com/starkware-libs/cairo/blob/153760866fecd16907784e3e95887645799e1f9b/vscode-cairo/src/extension.ts#L47)):*
> ```XML
>   }
>   return folder;
> }
> ```

consider extracting all this logic to some black-box entity, say `WorkspaceManager` to avoid polluting this file. just moving this to `client.ts` (together with code added to `activate`) could also be fine
___
*[`vscode-cairo/src/extension.ts` line 62 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6395#-O98rp7m7uff0bXFPPnL:-O98rp7m7uff0bXFPPnM:bpvq89e) ([raw file](https://github.com/starkware-libs/cairo/blob/153760866fecd16907784e3e95887645799e1f9b/vscode-cairo/src/extension.ts#L62)):*
> ```XML
> 
>   async function didOpenTextDocument(document: vscode.TextDocument): Promise<void> {
>     // We are only interested in language mode text
> ```

doesn't this refer to plaintext files? of so, this comment is misleading
___
*[`vscode-cairo/src/extension.ts` line 66 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6395#-O98pfvGAwR6Tw7vZR-c:-O98pfvGAwR6Tw7vZR-d:bpuzk4q) ([raw file](https://github.com/starkware-libs/cairo/blob/153760866fecd16907784e3e95887645799e1f9b/vscode-cairo/src/extension.ts#L66)):*
> ```XML
>       return;
>     }
>     const uri = document.uri;
> ```

variable used only once, quite superfluous
___
*[`vscode-cairo/src/extension.ts` line 72 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6395#-O98inDj4qVu88W3qhNU:-O98inDj4qVu88W3qhNV:b7bi25w) ([raw file](https://github.com/starkware-libs/cairo/blob/153760866fecd16907784e3e95887645799e1f9b/vscode-cairo/src/extension.ts#L72)):*
> ```XML
>     // Files outside a folder
>     // TODO(arcticae): Those should probably be handled with a "default client"
>     // it is unclear on how it should work exactly
> ```

by making an indent here, some TODO highlighting tools (ekhem IntelliJ) will catch up that this line is a continuation



_Suggestion:_
```XML
    // TODO(arcticae): Those should probably be handled with a "default client"
    //   it is unclear on how it should work exactly.
```
___
*[`vscode-cairo/src/extension.ts` line 88 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6395#-O98r1iJ0kkPycZNN3OO:-O98r1iJ0kkPycZNN3OP:be0l93s) ([raw file](https://github.com/starkware-libs/cairo/blob/153760866fecd16907784e3e95887645799e1f9b/vscode-cairo/src/extension.ts#L88)):*
> ```XML
>       deleteClient(folder);
>     }
>   });
> ```

onDidOpenTextDocument and onDidChangeWorkspaceFolders return disposables that I guess we need to register

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6395)* status: all files reviewed, 21 unresolved discussions (waiting on @Arcticae, @Draggu, and @piotmag769)

**Comment by Arcticae** [comment]
Closing because other solution was chosen for this problem (implementation in progress)

**Pull request closed without merging**
