### PR TITLE
Supported modifying trimmed nodes

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2295)

### CODE REVIEW

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2295)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2295#-NPHtLGREMbANjELDIus:-NPHtLGREMbANjELDIut:b-3yf84a) (no related file):*
change target branch

___

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2295)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/patcher.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2295#-NPHx6MI9trs-IHSFTrj:-NPHx6MI9trs-IHSFTrk:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a31384eff0ad670aac45218ab91e7e440e912120/crates/cairo-lang-semantic/src/patcher.rs#L53)):*
> ```XML
>                 let mut right_idx = 0;
>                 for (idx, child) in node.children(db).enumerate() {
>                     if child.width(db) != TextWidth::default() {
> ```





_Suggestion:_
```XML
                let Some(left_idx) = node.children(db).position(|child| child.width(db) != TextWidth::default()) else {                    
                    *self = RewriteNode::Modified(ModifiedNode { children: None });
                    return extract_matches!(self, RewriteNode::Modified);
                };
                let right_idx = node.children(db).rposition(|child| child.width(db) != TextWidth::default()).unwrap();
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2295)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/patcher.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2295#-NPHx6MI9trs-IHSFTrj:-NPIIre79SxfWD8mg6eD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a31384eff0ad670aac45218ab91e7e440e912120/crates/cairo-lang-semantic/src/patcher.rs#L53)):*
> ```XML
>                 let mut right_idx = 0;
>                 for (idx, child) in node.children(db).enumerate() {
>                     if child.width(db) != TextWidth::default() {
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2295#-:-NPIKK58C6sa5ZJjyi4U:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
