### PR TITLE
Refactor Call generator to accept Vec<VarUsage> for the inputs.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3413)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3413)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 442 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3413#-NXsuGHJ-lMn9Fhl9VgB:-NXsuGHJ-lMn9Fhl9VgC:bljob9k) ([raw file](https://github.com/starkware-libs/cairo/blob/06d54e28c13219c8b29babc225f4c1ba73932a9d/crates/cairo-lang-lowering/src/lower/mod.rs#L442)):*
> ```XML
> }
> 
> /// Lowers a semantic expression.
> ```

fix doc
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 450 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3413#-NXsu1GnB5Hheayr2JJ-:-NXsu1GnB5Hheayr2JJ0:bybf0fl) ([raw file](https://github.com/starkware-libs/cairo/blob/06d54e28c13219c8b29babc225f4c1ba73932a9d/crates/cairo-lang-lowering/src/lower/mod.rs#L450)):*
> ```XML
>     Ok(VarUsage {
>         var_id: lower_expr(ctx, builder, expr_id)?.var(ctx, builder)?,
>         location: ctx.get_location(ctx.function_body.exprs[expr_id].stable_ptr().untyped()),
> ```

isn't this the declaration of the var and not the usage?



_Code quote:_
```XML
ocation: ctx.get_location(ctx.function_body.exprs[expr_id].stable_ptr().untyped()),
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3413)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 442 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3413#-NXsuGHJ-lMn9Fhl9VgB:-NYCJ7SN0laNL7RRjavt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/06d54e28c13219c8b29babc225f4c1ba73932a9d/crates/cairo-lang-lowering/src/lower/mod.rs#L442)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix doc
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3413#-:-NYCtXZfETZsaj3CjwwK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3413)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
