### PR TITLE
Add SingleOutputCircuit.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5490)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5490)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/circuit.cairo` line 26 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5490#-NwjDqmJ6VMm_Ja65_jw:-NwjDqmJ6VMm_Ja65_jx:b-jis97v) ([raw file](https://github.com/starkware-libs/cairo/blob/93e9b48e7878d0f5f62eca363e6c670944aaebca/corelib/src/circuit.cairo#L26)):*
> ```Cairo
> 
> /// A marker trait for keeping track of which types are circuit elements.
> pub(crate) trait CircuitElementTrait<T> {}
> ```

this trait possibly needs to be pub - to allow partial calculation description in a function.
___
*[`corelib/src/circuit.cairo` line 30 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5490#-NwjDiPL-nvwI1FiKe6e:-NwjDiPL-nvwI1FiKe6f:b-2kenar) ([raw file](https://github.com/starkware-libs/cairo/blob/93e9b48e7878d0f5f62eca363e6c670944aaebca/corelib/src/circuit.cairo#L30)):*
> ```Cairo
> 
> 
> pub trait CircuitDefinition<Wrapped> {
> ```

doc trait.

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/circuit.cairo` line 26 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5490#-NwjDqmJ6VMm_Ja65_jw:-NwjFm7w80MMbCS3-jtv:b-6f8kx8) ([raw file](https://github.com/starkware-libs/cairo/blob/93e9b48e7878d0f5f62eca363e6c670944aaebca/corelib/src/circuit.cairo#L26)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this trait possibly needs to be pub - to allow partial calculation description in a function.
</blockquote></details>

how would the user use this trait?

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/src/circuit.cairo` line 26 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5490#-NwjDqmJ6VMm_Ja65_jw:-NwjFxqm6EEIF4wvH1Q_:bideter) ([raw file](https://github.com/starkware-libs/cairo/blob/93e9b48e7878d0f5f62eca363e6c670944aaebca/corelib/src/circuit.cairo#L26)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

how would the user use this trait?
</blockquote></details>

nvm, I guess you mean  a generic function that takes circuit_elements as inputs.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5490)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/circuit.cairo` line 26 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5490#-NwjDqmJ6VMm_Ja65_jw:-NwjGbytDS3ze7d-HcH8:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/93e9b48e7878d0f5f62eca363e6c670944aaebca/corelib/src/circuit.cairo#L26)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

nvm, I guess you mean  a generic function that takes circuit_elements as inputs.
</blockquote></details>

done
___
*[`corelib/src/circuit.cairo` line 30 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5490#-NwjDiPL-nvwI1FiKe6e:-NwjGbLTEssQiKpFiAhq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/93e9b48e7878d0f5f62eca363e6c670944aaebca/corelib/src/circuit.cairo#L30)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc trait.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5490)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/circuit.cairo` line 26 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5490#-NwjDqmJ6VMm_Ja65_jw:-NwjGtXSBtlgnzqQf9fa:b689xr) ([raw file](https://github.com/starkware-libs/cairo/blob/93e9b48e7878d0f5f62eca363e6c670944aaebca/corelib/src/circuit.cairo#L26)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

done
</blockquote></details>

add `pub`.
___
*[`corelib/src/circuit.cairo` line 37 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5490#-NwjH3IR0pwnMffX8p7X:-NwjH3IR0pwnMffX8p7Y:b-41vd4i) ([raw file](https://github.com/starkware-libs/cairo/blob/5ccf00fce82c26ecfdc3026177138adee5ff828b/corelib/src/circuit.cairo#L37)):*
> ```Cairo
> }
> 
> pub impl SingleOutputCircuit<Out0> of CircuitDefinition<(CircuitElement<Out0>,)> {
> ```

remove the pub for the impl - shouldn't be required.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5490)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/circuit.cairo` line 26 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5490#-NwjDqmJ6VMm_Ja65_jw:-NwmqUSk95twJAuapR-Y:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/93e9b48e7878d0f5f62eca363e6c670944aaebca/corelib/src/circuit.cairo#L26)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add `pub`.
</blockquote></details>

Done.
___
*[`corelib/src/circuit.cairo` line 37 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5490#-NwjH3IR0pwnMffX8p7X:-NwmqjLT7iKhOU7DYbsD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5ccf00fce82c26ecfdc3026177138adee5ff828b/corelib/src/circuit.cairo#L37)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove the pub for the impl - shouldn't be required.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5490#-:-NwnIyrk2N5MZ5vwk6ur:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
