### PR TITLE
alloc_locals should returns all cells.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #3186
- #3185
- #3184 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3184)

### CODE REVIEW

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3184)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/mem.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3184#-NVjBzhZD-Gjtr2I9OP0:-NVjBzhZD-Gjtr2I9OP1:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a9b80224549aef14d3af640ef0ced9053cfbc4d9/crates/cairo-lang-sierra-to-casm/src/invocations/mem.rs#L44)):*
> ```XML
> }
> 
> /// Returns a store instruction. Helper function for store_temp and store_local.
> ```





_Suggestion:_
```XML
/// Returns a store instruction. Helper function for store_temp and store_local.
///
/// Note that for `dst_cells`, `ap` increases by 1 after every store, so in order to write
/// two consecutive cells, `dst_cells` should be `[ap, ap]` and not `[ap, ap + 1]`.
/// On the other hand, the function adjust the ap-change in the cells of `src_expr`.
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/mem.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3184#-NVjBWYC3wFC1PRJUH8K:-NVjBWYC3wFC1PRJUH8L:b3reo55) ([raw file](https://github.com/starkware-libs/cairo/blob/a9b80224549aef14d3af640ef0ced9053cfbc4d9/crates/cairo-lang-sierra-to-casm/src/invocations/mem.rs#L116)):*
> ```XML
>     let dst_cells = dst_expr.cells.iter().map(|c| *extract_matches!(c, CellExpression::Deref));
>     let instructions = get_store_instructions(&builder, ty, dst_cells, src_expr)?;
>     let dst_expr = dst_expr.clone();
> ```

Is this line needed? Why not `dst_expr.clone()` in the line below?

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3184)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3184)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/mem.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3184#-NVjBzhZD-Gjtr2I9OP0:-NVjZ7nJExsmkcXzRENA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0d0079c41c0b59ce6af7fd90ac1eaf3663cd48d6/crates/cairo-lang-sierra-to-casm/src/invocations/mem.rs#L44)):*
> ```XML
> }
> 
> /// Returns a store instruction. Helper function for store_temp and store_local.
> ```

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/mem.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3184#-NVjBWYC3wFC1PRJUH8K:-NVjW1zI8jpldBpdA9jZ:b7hx9lo) ([raw file](https://github.com/starkware-libs/cairo/blob/0d0079c41c0b59ce6af7fd90ac1eaf3663cd48d6/crates/cairo-lang-sierra-to-casm/src/invocations/mem.rs#L116)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Is this line needed? Why not `dst_expr.clone()` in the line below?
</blockquote></details>

Borrow checker (dst_expr is a ref from builder)

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3184#-:-NVn69sE1Gh-QqTP-Nqr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by liorgold2 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3184)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/mem.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3184#-NVn6DeA6bHdCZnILxlu:-NVn6DeA6bHdCZnILxlv:b-6jdydy) ([raw file](https://github.com/starkware-libs/cairo/blob/1174188791ce1f8cb29aeed2223f01e7682b8200/crates/cairo-lang-sierra-to-casm/src/invocations/mem.rs#L48)):*
> ```XML
> /// Note that for `dst_cells`, `ap` increases by 1 after every store, so in order to write
> /// two consecutive cells, `dst_cells` should be `[ap, ap]` and not `[ap, ap + 1]`.
> /// On the other hand, the function adjust the ap-change in the cells of `src_expr`.
> ```

(nonblocking)



_Suggestion:_
```XML
/// On the other hand, the function adjusts the ap-change in the cells of `src_expr`.
```

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3184)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
