### PR TITLE
squash_dict: Remove unnecessary local variable.

### PR DESCRIPTION
**Pull request by liorgold2**
**Stack**:
- #2824
- #2823
- #2802
- #2775 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2775)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2775)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs` line 176 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2775#-NStYqlF5O-HCx3j6W3v:-NStYqlF5O-HCx3j6W3w:bn6icx5) ([raw file](https://github.com/starkware-libs/cairo/blob/cb55361290adf6b94004c6a737faab228cdf5042/crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs#L176)):*
> ```XML
>             localvar dict_index;
>             localvar dict_accesses_len;
>             localvar local_gas_builtin = dict_destruct_arg_gas_builtin;
> ```

It is unnecessary when writing Cairo code since it is wrapped in a function, but I think it using squash directly in Sierra will, when the gas builting is tempvar, will be invalid no?

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2775)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2775)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs` line 176 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2775#-NStYqlF5O-HCx3j6W3v:-NSw_oMT5cY5-dxPUWLk:budctlb) ([raw file](https://github.com/starkware-libs/cairo/blob/cb55361290adf6b94004c6a737faab228cdf5042/crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs#L176)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

It is unnecessary when writing Cairo code since it is wrapped in a function, but I think it using squash directly in Sierra will, when the gas builting is tempvar, will be invalid no?
</blockquote></details>

This is inside `DestructDict` which is always a function on its own, so IIUC it's okay. Is this true?

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2775)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2775)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2775#-:-NT621TT7-w_kKR-_yCT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs` line 176 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2775#-NStYqlF5O-HCx3j6W3v:-NT61xs25CZ4IoFDmLIN:brqcc0z) ([raw file](https://github.com/starkware-libs/cairo/blob/cb55361290adf6b94004c6a737faab228cdf5042/crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs#L176)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

This is inside `DestructDict` which is always a function on its own, so IIUC it's okay. Is this true?
</blockquote></details>

Yes, that's okay.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2775)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
