### PR TITLE
Added support for `mod.cairo` as module.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5817)

### CODE REVIEW

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5817)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5817#-O-aK2GyEjyxAdyZqNIu:-O-aK2GyEjyxAdyZqNIv:bh0ptao) (no related file):*
What's the motivation behind this? This is adding a new way of writing module files and will bring the same problem one has in Rust: there are two parallel styles and community cannot settle on one style :/

___

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5817)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @mkaput)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5817#-O-aK2GyEjyxAdyZqNIu:-O-aLXodCN2qfS1HAV_W:b-dspwbo) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

What's the motivation behind this? This is adding a new way of writing module files and will bring the same problem one has in Rust: there are two parallel styles and community cannot settle on one style :/
</blockquote></details>

the motivation is that this is the better way - so the root reason is the same.

___

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5817)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5817#-O-aK2GyEjyxAdyZqNIu:-O-aNGju37U_iGEMcoxq:bo2v0tz) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the motivation is that this is the better way - so the root reason is the same.
</blockquote></details>

Have you thought about deprecating the old style (say in new edition), so that we won't have the same hurdle that Rust has?

___

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-filesystem/src/ids.rs` line 180 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5817#-O-aWCZl1587t1A040ul:-O-aWCZmAYYE0tUnMYJz:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/466eb293ad834ac1dc3cfb09ea897e99ba5ffead/crates/cairo-lang-filesystem/src/ids.rs#L180)):*
> ```XML
>                 let dir_file_path =
>                     base_path.join(FILE_MODULE_NAME).with_extension(CAIRO_FILE_EXTENSION);
>                 // println!("dir_file_path: {:?}", dir_file_path);
> ```

remove



_Code quote:_
```XML
// println!("dir_file_path: {:?}", dir_file_path);
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5817)* status: 11 of 13 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @mkaput)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5817#-O-aK2GyEjyxAdyZqNIu:-O-al-b8DTbpjHiqmWeb:b-t3e5rq) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Have you thought about deprecating the old style (say in new edition), so that we won't have the same hurdle that Rust has?
</blockquote></details>

that sounds like a good idea - at least making it configurable - and changing the default in editions (while at the end deprecating in a version) 

___

**Review by mkaput — APPROVED** [review]
> Reviewed 12 of 13 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5817)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5817)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5817#-O-aK2GyEjyxAdyZqNIu:-O-bTAm04DfN4yhlOFyV:b-pxqze5) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

that sounds like a good idea - at least making it configurable - and changing the default in editions (while at the end deprecating in a version)
</blockquote></details>

hmm - not really - if we don't support both - we need to block the ability to declare non-inline modules in non dir files.
not trivial at all, and still dependent on existance of other files in the filesystem.

___

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5817)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5817#-O-aK2GyEjyxAdyZqNIu:-O-eMmp76x4WwxQ7fEH5:bc7ux40) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

hmm - not really - if we don't support both - we need to block the ability to declare non-inline modules in non dir files.
not trivial at all, and still dependent on existance of other files in the filesystem.
</blockquote></details>

old Rust used to emit errors if it spotted non-inline module in non-dir file, so I think the only tricky part here could be hooking diagnostics into this logic? out of curiosity: what's not trivial here?



___

**Pull request closed without merging**
