### PR TITLE
allow generic impl in extern functions

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5285)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5285)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @TomerStarkware and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/items/extern_function.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5285#-NtQGdfp3aT5rcX9puQf:-NtQGdfp3aT5rcX9puQg:bfrm0ir) ([raw file](https://github.com/starkware-libs/cairo/blob/ba74ab11b8c678f97bf3e12d7145f7e01abd1eb1/crates/cairo-lang-semantic/src/items/extern_function.rs#L94)):*
> ```XML
>             ExternItemWithImplGenericsNotSupported,
>         );
>     }
> ```

still ensure these are the last of the generics - otherwise ordering is weird.



_Code quote:_
```XML
    if let Some(param) = generic_params.iter().find(|param| param.kind() == GenericKind::Impl) {
        diagnostics.report_by_ptr(
            param.stable_ptr(db.upcast()).untyped(),
            ExternItemWithImplGenericsNotSupported,
        );
    }
```
___
*[`crates/cairo-lang-sierra-generator/src/utils.rs` line 402 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5285#-NtQGLjgBhcjRy8dR4-o:-NtQGLjgBhcjRy8dR4-p:b29n1rs) ([raw file](https://github.com/starkware-libs/cairo/blob/c6453c6566660b34ae4cd3bd9f04376151081302/crates/cairo-lang-sierra-generator/src/utils.rs#L402)):*
> ```XML
>                 )))
>             }
>             semantic::GenericArgumentId::Impl(_) => {}
> ```

doc the fact we specifically ignore here including the reasoning.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5285)* status: all files reviewed, 7 unresolved discussions (waiting on @orizi and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 567 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5285#-NtV1ved-alIqdUTmWVT:-NtV1ved-alIqdUTmWVU:b-mf5spa) ([raw file](https://github.com/starkware-libs/cairo/blob/c6453c6566660b34ae4cd3bd9f04376151081302/crates/cairo-lang-semantic/src/diagnostic.rs#L567)):*
> ```XML
>             }
>             SemanticDiagnosticKind::DivisionByZero => "Division by zero.".into(),
>             SemanticDiagnosticKind::ExternItemWithImplGenericsNotSupported => {
> ```

please rename the error too.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/generics` line 146 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5285#-NtV4HBy7XcBEnNTX7_Y:-NtV4HBy7XcBEnNTX7_Z:bu1c7me) ([raw file](https://github.com/starkware-libs/cairo/blob/c6453c6566660b34ae4cd3bd9f04376151081302/crates/cairo-lang-semantic/src/expr/test_data/generics#L146)):*
> ```
> impl MyImpl of MyTrait::<felt252> {}
> fn bar<impl C: MyTrait::<felt252>>(){}
> extern fn hoo<impl C: MyTrait::<felt252>>() nopanic;
> ```

Please add 2 extern types here: one with generic impl (invalid) and one with non-impl generics (valid)
___
*[`crates/cairo-lang-semantic/src/items/extern_function.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5285#-NtQGdfp3aT5rcX9puQf:-NtV2Lvu8PwcCpHZzMQH:b-uy4gme) ([raw file](https://github.com/starkware-libs/cairo/blob/ba74ab11b8c678f97bf3e12d7145f7e01abd1eb1/crates/cairo-lang-semantic/src/items/extern_function.rs#L94)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

still ensure these are the last of the generics - otherwise ordering is weird.
</blockquote></details>

+1
And have a dedicated error for it
___
*[`crates/cairo-lang-sierra-generator/src/utils.rs` line 402 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5285#-NtQGLjgBhcjRy8dR4-o:-NtV2k3E86f2F6lQKaaX:b-tckx1f) ([raw file](https://github.com/starkware-libs/cairo/blob/c6453c6566660b34ae4cd3bd9f04376151081302/crates/cairo-lang-sierra-generator/src/utils.rs#L402)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc the fact we specifically ignore here including the reasoning.
</blockquote></details>

Also ensure here these are the last generic parameters, otherwise it's invalid.
___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/generics` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5285#-NtV3Kqs4jzkVsariWqy:-NtV3Kqs4jzkVsariWqz:b2nh8oq) ([raw file](https://github.com/starkware-libs/cairo/blob/c6453c6566660b34ae4cd3bd9f04376151081302/crates/cairo-lang-sierra-generator/src/function_generator_test_data/generics#L1)):*
> ```
> //! > Test that accessing a member of a struct does not cause all the struct to be stored.
> ```

???



_Code quote:_
```
> Test that accessing a member of a struct does not cause all the struct to be stored.
```
___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/generics` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5285#-NtV3xV-5pylAJW1WRXG:-NtV3xV-5pylAJW1WRXH:b-lmxckz) ([raw file](https://github.com/starkware-libs/cairo/blob/c6453c6566660b34ae4cd3bd9f04376151081302/crates/cairo-lang-sierra-generator/src/function_generator_test_data/generics#L3)):*
> ```
> //! > Test that accessing a member of a struct does not cause all the struct to be stored.
> 
> //! > Test that generic impls are allowed in extern functions.
> ```

Add 2 more tests:
1. generic impls are not allowed if they are not last.
2. generic impls are not supported in extern types.
___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/generics` line 27 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5285#-NtV3cd0-ri5nrxacDey:-NtV3cd118TcPzSOEw_-:bfpd4fp) ([raw file](https://github.com/starkware-libs/cairo/blob/c6453c6566660b34ae4cd3bd9f04376151081302/crates/cairo-lang-sierra-generator/src/function_generator_test_data/generics#L27)):*
> ```
> impl Inner1 of Inner<(felt252, felt252, felt252)>{
>   type inner = felt252;
> }
> ```

The test is too complicated. Minimise it to test your use case. It should not be specifically related to the scenario that rose the need for this change.



_Code quote:_
```
//! > function
fn foo() -> @Array<felt252> {
  span_from_tuple(BoxTrait::new(@(10, 20, 30)))
}

//! > function_name
foo

//! > module_code
pub extern fn span_from_tuple<T, impl T_Inner: Inner<T>, +Copy<T>>(
  struct_like: Box<@T>
) -> @Array<felt252> nopanic;

trait Inner<T> {
  type inner;
}

impl Inner1 of Inner<(felt252, felt252, felt252)>{
  type inner = felt252;
}
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5285)* status: 4 of 7 files reviewed, 10 unresolved discussions (waiting on @TomerStarkware and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 571 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5285#-NtVemU4EgPEyBXvcFq8:-NtVemU4EgPEyBXvcFq9:bxb8c8w) ([raw file](https://github.com/starkware-libs/cairo/blob/56902f9e7a4ebab8c85bb4d6cd545a237377b5a9/crates/cairo-lang-semantic/src/diagnostic.rs#L571)):*
> ```XML
>             }
>             SemanticDiagnosticKind::ExternFunctionsWithNonLastImplGenericsNotSupported => {
>                 "Impl generics in extern functions must be the last parameters".into()
> ```

Easier to point at the non-impl params IMO.



_Suggestion:_
```XML
                "Non-impl generics following an impl generic in extern fn".into()
```
___
*[`crates/cairo-lang-semantic/src/items/extern_function.rs` line 100 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5285#-NtVfEu1CQwdNEmK8zTJ:-NtVfEu1CQwdNEmK8zTK:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c820141f819969c2257a6bfcfd6a90660c345044/crates/cairo-lang-semantic/src/items/extern_function.rs#L100)):*
> ```XML
>             );
>         }
>     }
> ```





_Suggestion:_
```XML
    let mut got_generic_impl = false;
    for param in &generic_params {
        if param.kind() == GenericKind::Impl {
            got_generic_impl = true;
        } else if got_generic_impl {
            diagnostics.report_by_ptr(
                param.stable_ptr(db.upcast()).untyped(),
                ExternFunctionsGenericArgsNonImplFollowingImpl,
            );
        }
    }
```
___
*[`crates/cairo-lang-sierra-generator/src/utils.rs` line 402 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5285#-NtQGLjgBhcjRy8dR4-o:-NtVg9km2OlB5_ofq2aq:b-yo3gce) ([raw file](https://github.com/starkware-libs/cairo/blob/c6453c6566660b34ae4cd3bd9f04376151081302/crates/cairo-lang-sierra-generator/src/utils.rs#L402)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Also ensure here these are the last generic parameters, otherwise it's invalid.
</blockquote></details>

i think since we validate in diagnostics - a comment is enough.
___
*[`crates/cairo-lang-sierra-generator/src/utils.rs` line 404 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5285#-NtVgJas-HeQ7HddwQQz:-NtVgJas-HeQ7HddwQR-:b-w1baly) ([raw file](https://github.com/starkware-libs/cairo/blob/56902f9e7a4ebab8c85bb4d6cd545a237377b5a9/crates/cairo-lang-sierra-generator/src/utils.rs#L404)):*
> ```XML
>                 }
>                 generic_args.push(GenericArg::Value(extract_matches!(
>                     db.lookup_intern_const_value(*value_id),
> ```

or simply remove the validation completely.



_Suggestion:_
```XML
            semantic::GenericArgumentId::Type(ty) => {
                assert!(!seen_impl_generic, "Impl generics must be last.");
                // TODO(lior): How should the following unwrap() be handled?
                generic_args.push(GenericArg::Type(db.get_concrete_type_id(*ty).unwrap()))
            }
            semantic::GenericArgumentId::Constant(value_id) => {
                assert!(!seen_impl_generic, "Impl generics must be last.");
                generic_args.push(GenericArg::Value(extract_matches!(
                    db.lookup_intern_const_value(*value_id),
```

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5285)* status: all files reviewed, 11 unresolved discussions (waiting on @orizi and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 571 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5285#-NtW7RnM0fjfJvNhqxPN:-NtW7RnM0fjfJvNhqxPO:b-oealbx) ([raw file](https://github.com/starkware-libs/cairo/blob/41372037d2b7e180176020543f0591cf37b4edb5/crates/cairo-lang-semantic/src/diagnostic.rs#L571)):*
> ```XML
>             }
>             SemanticDiagnosticKind::ExternFunctionsGenericArgsNonImplFollowingImpl => {
>                 "Non-impl generics following an impl generic in extern fn".into()
> ```

or "Non-impl generics are not supported following/after an impl generic in an extern function."



_Suggestion:_
```XML
Non-impl generics following an impl generic in an extern function are not supported."
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5285)* status: 2 of 7 files reviewed, 7 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 567 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5285#-NtVkVINA_Wq8QFA8tS5:-NtW7q0k0msn6H-QIdEn:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c588981d88b9231670a001162889bceccdbbb600/crates/cairo-lang-semantic/src/diagnostic.rs#L567)):*
> ```XML
>             }
>             SemanticDiagnosticKind::DivisionByZero => "Division by zero.".into(),
>             SemanticDiagnosticKind::ExternTypesWithImplGenericsNotSupported => {
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 568 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5285#-NtW1sNh5SUI6ydLgXKq:-NtW7qNy6xazV571Y0d2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c588981d88b9231670a001162889bceccdbbb600/crates/cairo-lang-semantic/src/diagnostic.rs#L568)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Add `.` in the end of both errors.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 570 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5285#-NtVn2f020RIkC-frx8s:-NtW7uEPE_20hUMVlCpQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c588981d88b9231670a001162889bceccdbbb600/crates/cairo-lang-semantic/src/diagnostic.rs#L570)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

suggestion
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 571 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5285#-NtW7RnM0fjfJvNhqxPN:-NtW8CMBDIIjb5FC9FYh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/41372037d2b7e180176020543f0591cf37b4edb5/crates/cairo-lang-semantic/src/diagnostic.rs#L571)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

or "Non-impl generics are not supported following/after an impl generic in an extern function."
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/extern_function.rs` line 82 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5285#-NtW399C94c6jypWLEQr:-NtWK1apAEqincsMLXws:b-k4z1wq) ([raw file](https://github.com/starkware-libs/cairo/blob/c588981d88b9231670a001162889bceccdbbb600/crates/cairo-lang-semantic/src/items/extern_function.rs#L82)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

The validation (as Ori suggested) can be done inside semantic_generic_params (with an extra boolean), to avoid the extra pass of the params.
</blockquote></details>

as discussed
___
*[`crates/cairo-lang-sierra-generator/src/utils.rs` line 404 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5285#-NtVgJas-HeQ7HddwQQz:-NtW4k7QBeHXRo-uQL66:b-3zxeti) ([raw file](https://github.com/starkware-libs/cairo/blob/56902f9e7a4ebab8c85bb4d6cd545a237377b5a9/crates/cairo-lang-sierra-generator/src/utils.rs#L404)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

or simply remove the validation completely.
</blockquote></details>

changed to assert
___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/generics` line 15 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5285#-NtW4QRuAeXjoDdiJ3Uz:-NtWIhBmA15nNuAcnAD0:bhmaiae) ([raw file](https://github.com/starkware-libs/cairo/blob/c588981d88b9231670a001162889bceccdbbb600/crates/cairo-lang-sierra-generator/src/function_generator_test_data/generics#L15)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Much better, but simplifying more:
</blockquote></details>

I want to return to be in the test though

**Review by orizi — APPROVED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5285)* status: all files reviewed, 7 unresolved discussions (waiting on @yuvalsw)

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5285)* status: all files reviewed, 3 unresolved discussions (waiting on @array and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 1044 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5285#-NtXGIawEq_gwBPEs61Q:-NtXGIawEq_gwBPEs61R:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/432e9599596bc3b38295958941f3c8a9ad82aba4/crates/cairo-lang-semantic/src/diagnostic.rs#L1044)):*
> ```XML
>     DivisionByZero,
>     ExternTypeWithImplGenericsNotSupported,
>     ImplGenericsAfterNonImplGenericsInEsternFunction,
> ```





_Suggestion:_
```XML
sInExter
```
___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/generics` line 15 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5285#-NtW4QRuAeXjoDdiJ3Uz:-NtXGdoW7wVXDownT8Zo:b4tgcmi) ([raw file](https://github.com/starkware-libs/cairo/blob/c588981d88b9231670a001162889bceccdbbb600/crates/cairo-lang-sierra-generator/src/function_generator_test_data/generics#L15)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

I want to return to be in the test though
</blockquote></details>

Why? And anyway, why specifically @Array<felt252>? Use as simple types as you can to achieve the purpose of the test.
___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/generics` line 15 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5285#-NtXGsDq4SXKsmRY2KRI:-NtXGsDrE8RZo6Uvh3k-:b-xzsqe8) ([raw file](https://github.com/starkware-libs/cairo/blob/432e9599596bc3b38295958941f3c8a9ad82aba4/crates/cairo-lang-sierra-generator/src/function_generator_test_data/generics#L15)):*
> ```
> 
> //! > module_code
> extern fn span_from_tuple<T, +Copy<T>>(x: Box<@T>) -> @Array<felt252> nopanic;
> ```

BTW, you said the name must be an existing name? If not, change please (to e.g. foo), if yes - add a comment saying this is the name only because you must have an existing name.



_Code quote:_
```
span_from_tuple
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5285)* status: all files reviewed, 2 unresolved discussions (waiting on @array and @yuvalsw)

___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/generics` line 15 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5285#-NtW4QRuAeXjoDdiJ3Uz:-Ntjof3q0eYrBYiezOCn:ba5iz7o) ([raw file](https://github.com/starkware-libs/cairo/blob/c588981d88b9231670a001162889bceccdbbb600/crates/cairo-lang-sierra-generator/src/function_generator_test_data/generics#L15)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Why? And anyway, why specifically @Array<felt252>? Use as simple types as you can to achieve the purpose of the test.
</blockquote></details>

This is the return type of the actual libfunc though.
___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/generics` line 15 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5285#-NtXGsDq4SXKsmRY2KRI:-NtjzR4q8JLVsVsusnZc:be1yyn7) ([raw file](https://github.com/starkware-libs/cairo/blob/432e9599596bc3b38295958941f3c8a9ad82aba4/crates/cairo-lang-sierra-generator/src/function_generator_test_data/generics#L15)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

BTW, you said the name must be an existing name? If not, change please (to e.g. foo), if yes - add a comment saying this is the name only because you must have an existing name.
</blockquote></details>

It needs to be the same name in all sierra-gen tests as it looks for the name from the sierra crate

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5285)* status: all files reviewed, 2 unresolved discussions (waiting on @array and @yuvalsw)

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5285)* status: all files reviewed, 2 unresolved discussions (waiting on @array and @TomerStarkware)

___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/generics` line 15 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5285#-NtW4QRuAeXjoDdiJ3Uz:-NtkVIxpANCXzukD9qHe:begofsx) ([raw file](https://github.com/starkware-libs/cairo/blob/c588981d88b9231670a001162889bceccdbbb600/crates/cairo-lang-sierra-generator/src/function_generator_test_data/generics#L15)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

This is the return type of the actual libfunc though.
</blockquote></details>

I understand. Does it have to be the same (for the test)?
If it does - ok, and again, explain in the comment.
If it does not - please change. The test is not for the specific libfunc but for a libfunc. If you insist on also testing your specific libfunc (maybe because there is something special about it), you can add another test.
___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/generics` line 15 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5285#-NtXGsDq4SXKsmRY2KRI:-NtkV4ka5xfTbIAJ91xh:bbc89mf) ([raw file](https://github.com/starkware-libs/cairo/blob/432e9599596bc3b38295958941f3c8a9ad82aba4/crates/cairo-lang-sierra-generator/src/function_generator_test_data/generics#L15)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

It needs to be the same name in all sierra-gen tests as it looks for the name from the sierra crate
</blockquote></details>

"if yes - add a comment saying this is the name only because you must have an existing name."

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5285)* status: all files reviewed, 2 unresolved discussions (waiting on @array and @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5285)* status: all files reviewed, 2 unresolved discussions (waiting on @array and @yuvalsw)

___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/generics` line 15 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5285#-NtW4QRuAeXjoDdiJ3Uz:-NtlFJrT0W8Hdbzin_5y:barwz13) ([raw file](https://github.com/starkware-libs/cairo/blob/c588981d88b9231670a001162889bceccdbbb600/crates/cairo-lang-sierra-generator/src/function_generator_test_data/generics#L15)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I understand. Does it have to be the same (for the test)?
If it does - ok, and again, explain in the comment.
If it does not - please change. The test is not for the specific libfunc but for a libfunc. If you insist on also testing your specific libfunc (maybe because there is something special about it), you can add another test.
</blockquote></details>

I don't understand the comment, it doesn't make sense to wrong type there.
___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/generics` line 15 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5285#-NtXGsDq4SXKsmRY2KRI:-NtlFJXZ6h2-U2M2FNd3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/432e9599596bc3b38295958941f3c8a9ad82aba4/crates/cairo-lang-sierra-generator/src/function_generator_test_data/generics#L15)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

"if yes - add a comment saying this is the name only because you must have an existing name."
</blockquote></details>

Done.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5285#-:-NtoN4x63RZzUmosswiP:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @array)

___
*[`crates/cairo-lang-sierra-generator/src/function_generator_test_data/generics` line 15 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5285#-NtW4QRuAeXjoDdiJ3Uz:-NtoMpeb1MD9QYHc9qdc:b3ocp5i) ([raw file](https://github.com/starkware-libs/cairo/blob/c588981d88b9231670a001162889bceccdbbb600/crates/cairo-lang-sierra-generator/src/function_generator_test_data/generics#L15)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

I don't understand the comment, it doesn't make sense to wrong type there.
</blockquote></details>

As discussed f2f, signature has to be the same. Resolving.

**Pull request merged**
