### PR TITLE
u256_sqrt audit fixes.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3507)

### CODE REVIEW

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3507#-:-NYrDytp1Yjt82UEJJY2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3507)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned256.rs` line 307 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3507#-NYrz6bSEOwjHAVtx7pr:-NYrz6bSEOwjHAVtx7ps:b5ia2l5) ([raw file](https://github.com/starkware-libs/cairo/blob/cd5e8a191aea99b01da1c455bde20e995e72dafe/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned256.rs#L307)):*
> ```XML
> 
>         // Verify the hint consistency and ranges.
>         // Assert range on sqrt limbs.
> ```

Add something like:



_Suggestion:_
```XML
// Assert range on sqrt limbs.
// Note that for an honest prover we have 0 <= sqrt0, sqrt1 < 2**64.
// But for soundness it is sufficient to check that 0 <= sqrt0, sqrt1 and sqrt0 + sqrt1 < 2**65,
// which guarantees that 0 <= sqrt0, sqrt1 < 2**65.
```

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3507)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3507)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3507)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned256.rs` line 307 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3507#-NYrz6bSEOwjHAVtx7pr:-NYs045ADBbibBSn_-SY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cd5e8a191aea99b01da1c455bde20e995e72dafe/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned256.rs#L307)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Add something like:
</blockquote></details>

Done.

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3507#-:-NYtD9oKDOp92HP4s0Ls:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3507#-:-NYvR1LM0IRWIePXTti0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
