### PR TITLE
Add SierraApChange::BranchAlign

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1790)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1790#-:-NM-JwPf2luwt_PX0YIA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1790)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra/src/extensions/lib_func.rs` line 387 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1790#-NM2T_7F9Jk2jxlz2oxU:-NM2T_7F9Jk2jxlz2oxV:bun9pl3) ([raw file](https://github.com/starkware-libs/cairo/blob/eb22d6acd892805784200e5bffbc4157e144f1ca/crates/cairo-lang-sierra/src/extensions/lib_func.rs#L387)):*
> ```XML
>     /// The lib func aligns the `ap` change across branches.
>     /// The `ap` change is know during compilation.
>     ApAlign,
> ```

Maybe I should call it BranchAlign?

I'm going to use it to identify BranchAlign instructions.



_Code quote:_
```XML
ApAlign
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1790)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/lib_func.rs` line 387 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1790#-NM2T_7F9Jk2jxlz2oxU:-NMNieVxCMhKnaVJ211W:brythjh) ([raw file](https://github.com/starkware-libs/cairo/blob/eb22d6acd892805784200e5bffbc4157e144f1ca/crates/cairo-lang-sierra/src/extensions/lib_func.rs#L387)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Maybe I should call it BranchAlign?

I'm going to use it to identify BranchAlign instructions.
</blockquote></details>

renamed.

**Review by orizi — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1790)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

**Pull request merged**
