### PR TITLE
allow const generics for extern types

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4354)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4354)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @gilbens-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/test_data/tests` line 305 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4354#-NiaR1CV2M_y9PbO5vuv:-NiaR1CV2M_y9PbO5vuw:bsyx9dj) ([raw file](https://github.com/starkware-libs/cairo/blob/42a46ea2c55c684b23d8747c377b2e4c596c23ff/crates/cairo-lang-lowering/src/test_data/tests#L305)):*
> ```
> 
> //! > semantic_diagnostics
> error: Const generic args are not allowed in this context.
> ```

Add a non extern type instead to keep diagnostic.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4354)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/test_data/tests` line 305 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4354#-NiaR1CV2M_y9PbO5vuv:-NidWWP38eGC7pG6jrmA:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/42a46ea2c55c684b23d8747c377b2e4c596c23ff/crates/cairo-lang-lowering/src/test_data/tests#L305)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Add a non extern type instead to keep diagnostic.
</blockquote></details>

Done

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4354#-:-NifzJEc3EVBK6Lzghbj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4354#-:-Nii03y_6JkN1CYWqX7s:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
