### PR TITLE
Improve error message for failed metadata

### PR DESCRIPTION
**Pull request by piotmag769**

### CODE REVIEW

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6598#-:-OB14Yt88NPs_2RaoZpy:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`vscode-cairo/src/cairols.ts` line 123 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6598#-OB14Wxn7IDwzAzBFiqd:-OB14Wxn7IDwzAzBFiqe:b2ni8l0) ([raw file](https://github.com/starkware-libs/cairo/blob/3306ae1f72223a2aef2df4dfefe001347adc7d77/vscode-cairo/src/cairols.ts#L123)):*
> ```XML
> 
>     const selectedValue = await vscode.window.showErrorMessage(
>       "Scarb metadata failed. Check if your project builds correctly via `scarb build`",
> ```

nit



_Suggestion:_
```XML
"Scarb metadata failed. Check if your project builds correctly via `scarb build`."
```

**Review by Draggu — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6598)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @orizi, and @piotmag769)

___
*[`vscode-cairo/src/cairols.ts` line 123 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6598#-OB14yAuDEq_SKQS0KTn:-OB14yAvETzErqxO9m6t:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/3306ae1f72223a2aef2df4dfefe001347adc7d77/vscode-cairo/src/cairols.ts#L123)):*
> ```XML
> 
>     const selectedValue = await vscode.window.showErrorMessage(
>       "Scarb metadata failed. Check if your project builds correctly via `scarb build`",
> ```





_Suggestion:_
```XML
`scarb metadata`
```

**Review by piotmag769 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6598)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

___
*[`vscode-cairo/src/cairols.ts` line 123 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6598#-OB14yAuDEq_SKQS0KTn:-OB15L1xAD1mwbjLS0dz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3306ae1f72223a2aef2df4dfefe001347adc7d77/vscode-cairo/src/cairols.ts#L123)):*
> ```XML
> 
>     const selectedValue = await vscode.window.showErrorMessage(
>       "Scarb metadata failed. Check if your project builds correctly via `scarb build`",
> ```

Done.

**Review by Draggu — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6598#-:-OB15NvB9Y2JDUDYa-Iz:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @orizi)

**Pull request merged**
