### PR TITLE
Add compute_postcost_info().

### PR DESCRIPTION
**Pull request by liorgold2**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4138)

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4138)* status: 11 of 12 files reviewed, all discussions resolved

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4138)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-gas/src/compute_costs.rs` line 480 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4138#-NfHAdD61Ahlmc3VUOLz:-NfHAdD61Ahlmc3VUOM-:b-5ej5o0) ([raw file](https://github.com/starkware-libs/cairo/blob/75e308cd57420ddc6809c8fe288cc76e10795171/crates/cairo-lang-sierra-gas/src/compute_costs.rs#L480)):*
> ```XML
>             }
>             BranchCost::RedepositGas => 0,
>         };
> ```

can you export the duplicated code?



_Code quote:_
```XML
        let branch_cost_val = match branch_cost {
            BranchCost::Regular { const_cost, pre_cost: _ } => const_cost.cost(),
            BranchCost::BranchAlign => {
                let ap_change = (self.get_ap_change_fn)(idx);
                if ap_change == 0 {
                    0
                } else {
                    ConstCost { steps: 1, holes: ap_change as i32, range_checks: 0 }.cost()
                }
            }
            BranchCost::FunctionCall { const_cost, function } => {
                wallet_at_fn(&function.entry_point).value + const_cost.cost()
            }
            BranchCost::WithdrawGas { const_cost, success, with_builtin_costs } => {
                let cost = self.compute_withdraw_gas_cost(idx, const_cost, *with_builtin_costs);

                // If withdraw_gas succeeds, we don't need to take
                // future_wallet_value into account, so we simply return.
                if *success {
                    return WalletInfo::from(cost);
                }
                cost
            }
            BranchCost::RedepositGas => 0,
        };
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4138)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-gas/src/compute_costs.rs` line 480 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4138#-NfHAdD61Ahlmc3VUOLz:-NfKPQGr3Msm7RipR6iw:b-un7t6h) ([raw file](https://github.com/starkware-libs/cairo/blob/75e308cd57420ddc6809c8fe288cc76e10795171/crates/cairo-lang-sierra-gas/src/compute_costs.rs#L480)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can you export the duplicated code?
</blockquote></details>

The code in `core_libfunc_postcost` is not similar enough: it uses `ops` and variables which I don't need here.
Also, it will hopefully be removed/changed once we remove the equation solver.

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4138#-:-NfKRUvW4m9StRugtkyr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
