### PR TITLE
Coupons: small refactor.

### PR DESCRIPTION
**Pull request by liorgold2**
**Stack**:
- #4615
- #4614 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4614)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4614)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/function_call.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4614#-Nm5thJF44C9N592iL_7:-Nm5thJF44C9N592iL_8:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/d72dcc29df7b87c9c176557fddd916cd6f7f385f/crates/cairo-lang-sierra/src/extensions/modules/function_call.rs#L73)):*
> ```XML
>         let [GenericArg::UserFunc(function_id)] = args else {
>             return Err(SpecializationError::UnsupportedGenericArg);
>         };
> ```





_Suggestion:_
```XML
        let function_id = args_as_single_user_func(args)?;
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4614)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/function_call.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4614#-Nm5thJF44C9N592iL_7:-Nm5zpqED2RMey_nHfKq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d72dcc29df7b87c9c176557fddd916cd6f7f385f/crates/cairo-lang-sierra/src/extensions/modules/function_call.rs#L73)):*
> ```XML
>         let [GenericArg::UserFunc(function_id)] = args else {
>             return Err(SpecializationError::UnsupportedGenericArg);
>         };
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4614#-:-Nm64p_x9oCHzl5tkBQi:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4614)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4614)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
