### PR TITLE
Orizi/merge v2.0.0 into main

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3584)

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 44 files at r9, 2 of 2 files at r10, 23 of 38 files at r13, 38 of 38 files at r14.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3584)* status: 42 of 65 files reviewed, all discussions resolved (waiting on @gilbens-starkware and @spapinistarkware)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 44 files at r9, 2 of 2 files at r10, 23 of 38 files at r13, 15 of 38 files at r14, 23 of 23 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3584#-:-NZUgLbr02RubAnlOq0m:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3584#-:-NZUh_IV1WRhgFIQcUtE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3584)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 23 files at r15.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3584)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
