### PR TITLE
LS: Add `Scheduler::on_sync_task` mechanism and use it for bookkeeping

### PR DESCRIPTION
**Pull request by mkaput**
Co-authored-by: Piotr Figiela <77412592+draggu@users.noreply.github.com>

---

**Stack**:
- #6495
- #6494 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Comment by lotem-starkware** [comment]
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6494)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6494#-:-O9HBpLYEVLSz_kHfTd-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @piotmag769)

**Review by piotmag769 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6494#-:-O9HNb_15ptS0aHgY77A:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)

**Review by Draggu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6494)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 324 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6494#-O9JnxbxDTPK-vX_gNaY:-O9JnxbxDTPK-vX_gNaZ:bfrtgla) ([raw file](https://github.com/starkware-libs/cairo/blob/1d93b16e5a406866b3697a3a375c7312c3e9fbac/crates/cairo-lang-language-server/src/lib.rs#L324)):*
> ```XML
>             // Refresh diagnostics each time state changes.
>             // Although it is possible to mutate state without affecting the analysis database,
>             // we basically never hit such a case in CairoLS in happy paths.
> ```

Not true, we hit it very often in fact. This is not a big deal though.

**Review by Draggu — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6494)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae and @mkaput)

___
*[`crates/cairo-lang-language-server/src/server/schedule/mod.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6494#-O9K9ubo9Tfmf-dufAfi:-O9K9ubp0TvUHcULiQUw:bsjs6hc) ([raw file](https://github.com/starkware-libs/cairo/blob/1d93b16e5a406866b3697a3a375c7312c3e9fbac/crates/cairo-lang-language-server/src/server/schedule/mod.rs#L109)):*
> ```XML
>     /// All hooks are called right after task execution, in the same thread and with the same
>     /// context.
>     /// This mechanism is useful for doing various bookkeeping on each language server state change,
> ```

In fact it is not guaranteed that state has changed.

**Review by Arcticae — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6494)* status: all files reviewed, 2 unresolved discussions (waiting on @Draggu and @mkaput)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 324 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6494#-O9JnxbxDTPK-vX_gNaY:-O9KDv541PHkJT0t6u4W:b-xeom7l) ([raw file](https://github.com/starkware-libs/cairo/blob/1d93b16e5a406866b3697a3a375c7312c3e9fbac/crates/cairo-lang-language-server/src/lib.rs#L324)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

Not true, we hit it very often in fact. This is not a big deal though.
</blockquote></details>

What are the exact cases?

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6494)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae and @Draggu)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 324 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6494#-O9JnxbxDTPK-vX_gNaY:-O9KKGRu1Ib5JFrkDrvm:bh3b5wg) ([raw file](https://github.com/starkware-libs/cairo/blob/1d93b16e5a406866b3697a3a375c7312c3e9fbac/crates/cairo-lang-language-server/src/lib.rs#L324)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

What are the exact cases?
</blockquote></details>

I have only identified one (but in all `did_` events): if `db.file_for_url` fails then we don't have to recompute diagnostics

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6494)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae and @Draggu)

___
*[`crates/cairo-lang-language-server/src/server/schedule/mod.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6494#-O9K9ubo9Tfmf-dufAfi:-O9KKV9TD1zkL8xQxGy8:bnzziuc) ([raw file](https://github.com/starkware-libs/cairo/blob/1d93b16e5a406866b3697a3a375c7312c3e9fbac/crates/cairo-lang-language-server/src/server/schedule/mod.rs#L109)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

In fact it is not guaranteed that state has changed.
</blockquote></details>

true, but this sentence doesn't imply that, isn't it?

**Review by Draggu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6494)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 324 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6494#-O9JnxbxDTPK-vX_gNaY:-O9KYEff9WA-8tQWUOjg:bgt1yzx) ([raw file](https://github.com/starkware-libs/cairo/blob/1d93b16e5a406866b3697a3a375c7312c3e9fbac/crates/cairo-lang-language-server/src/lib.rs#L324)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I have only identified one (but in all `did_` events): if `db.file_for_url` fails then we don't have to recompute diagnostics
</blockquote></details>

Happened frequently when tested it manually, maybe this was case described by @mkaput.
___
*[`crates/cairo-lang-language-server/src/server/schedule/mod.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6494#-O9K9ubo9Tfmf-dufAfi:-O9KYvx24U5l_batbGgb:bd0wkze) ([raw file](https://github.com/starkware-libs/cairo/blob/1d93b16e5a406866b3697a3a375c7312c3e9fbac/crates/cairo-lang-language-server/src/server/schedule/mod.rs#L109)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

true, but this sentence doesn't imply that, isn't it?
</blockquote></details>

Yes, but can we mention it here that it is not guaranteed?

**Review by piotmag769 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6494)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Pull request merged**
