### PR TITLE
Implement ec_add_to_state

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
Signed-off-by: Dori Medini <dori@starkware.co>

commit-id:f6774bad

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1631)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1631)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/cairo-sierra-to-casm/src/invocations/ec.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1631#-NKrisNmBNlgV7tX0x4r:-NKrisNmBNlgV7tX0x4s:b5dv4nd) ([raw file](https://github.com/starkware-libs/cairo/blob/b3285edc31632b2fd3bce377de5cee0657784dce/crates/cairo-sierra-to-casm/src/invocations/ec.rs#L69)):*
> ```XML
>         // X coordinate is identical; either `p0 + p1` is the point at infinity (not allowed) or
>         // `p0 = p1`, which is also not allowed (doubling). Assert a contradiction.
>         assert diff_x = diff_x + one;
> ```

do inifinite loop instead (a bit smaller final code)



_Suggestion:_
```XML
        InfiniteLoop:
        jump InfiniteLoop;
```
___
*[`crates/cairo-sierra/src/simulation/value.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1631#-NKrhodd5gS4_VNA6WMN:-NKrhodd5gS4_VNA6WMO:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b3285edc31632b2fd3bce377de5cee0657784dce/crates/cairo-sierra/src/simulation/value.rs#L9)):*
> ```XML
> pub enum CoreValue {
>     EcPoint(BigInt, BigInt),
>     EcState(BigInt, BigInt, BigInt),
> ```





_Suggestion:_
```XML
    EcState{rand: EcPoint, point: EcPoint},
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1631)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-sierra-to-casm/src/invocations/ec.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1631#-NKrisNmBNlgV7tX0x4r:-NKrm8Vt5-KCF89tOG2q:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b3285edc31632b2fd3bce377de5cee0657784dce/crates/cairo-sierra-to-casm/src/invocations/ec.rs#L69)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

do inifinite loop instead (a bit smaller final code)
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1631#-:-NKryVRB8Etc7Etm4qGc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 4 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1631)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1631)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs` line 60 at r6](https://reviewable.io/reviews/starkware-libs/cairo/1631#-NKwsQ8w-vni1rlSlyRD:-NKwsQ8x8cGh4To13HO8:b-13etma) ([raw file](https://github.com/starkware-libs/cairo/blob/5253e2e0a0ad0677d6fbf93dba4d274883952337/crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs#L60)):*
> ```XML
> 
>     casm_build_extend! {casm_builder,
>         tempvar result_x;
> ```

allocate these later - these cause the jump loop to contain an ap++.



_Code quote:_
```XML
        tempvar result_x;
        tempvar result_y;
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1631)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs` line 60 at r6](https://reviewable.io/reviews/starkware-libs/cairo/1631#-NKwsQ8w-vni1rlSlyRD:-NKwuOph4e8U0nwbjGj1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5253e2e0a0ad0677d6fbf93dba4d274883952337/crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs#L60)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

allocate these later - these cause the jump loop to contain an ap++.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1631)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
