### PR TITLE
Handle unknown item macros.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3878)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3878)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-defs/src/db.rs` line 456 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3878#-NbTtEwk8IhLIjtIw5zD:-NbTtEwl2wmCdX8N7FIh:b-9zziqf) ([raw file](https://github.com/starkware-libs/cairo/blob/1cd42a4905570acaf654c7c994f0364af297477d/crates/cairo-lang-defs/src/db.rs#L456)):*
> ```XML
>                     items.push(ModuleItemId::ImplAlias(item_id));
>                 }
>                 ast::Item::InlineMacro(inline_macro_ast) => plugin_diagnostics.push((
> ```

please add a test for me (and others) to understand the effect of this PR.
___
*[`crates/cairo-lang-defs/src/db.rs` line 460 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3878#-NbTtUcr7runtrmCRHjC:-NbTtUcr7runtrmCRHjD:bf6f07r) ([raw file](https://github.com/starkware-libs/cairo/blob/1cd42a4905570acaf654c7c994f0364af297477d/crates/cairo-lang-defs/src/db.rs#L460)):*
> ```XML
>                     PluginDiagnostic {
>                         stable_ptr: inline_macro_ast.stable_ptr().untyped(),
>                         message: "Unknown item macro.".into(),
> ```

please add the word inline in the error message, and also the actual name of the unknown macro.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3878)* status: 1 of 18 files reviewed, 2 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-defs/src/db.rs` line 456 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3878#-NbTtEwk8IhLIjtIw5zD:-Nc2xjwJ-_LbRyztjPvl:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1cd42a4905570acaf654c7c994f0364af297477d/crates/cairo-lang-defs/src/db.rs#L456)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

please add a test for me (and others) to understand the effect of this PR.
</blockquote></details>

Done.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3878)* status: all files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-defs/src/db.rs` line 343 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3878#-NcNOhRuA79zfR3zZ2qE:-NcNOhRuA79zfR3zZ2qF:bejokwv) ([raw file](https://github.com/starkware-libs/cairo/blob/b07166160709ffafa6f6c8b05268eed1e2dd5ce3/crates/cairo-lang-defs/src/db.rs#L343)):*
> ```XML
>                 let result = plugin.generate_code(db.upcast(), item_ast.clone());
>                 for plugin_diag in result.diagnostics {
>                     println!("plugin diag: {:?}", plugin_diag);
> ```

leftover?
___
*[`crates/cairo-lang-defs/src/db.rs` line 461 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3878#-NcNPk9o1bXNWbT1f-xp:-NcNPk9o1bXNWbT1f-xq:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b07166160709ffafa6f6c8b05268eed1e2dd5ce3/crates/cairo-lang-defs/src/db.rs#L461)):*
> ```XML
>                         stable_ptr: inline_macro_ast.stable_ptr().untyped(),
>                         message: format!(
>                             "Unknown inline item macro: {}.",
> ```





_Suggestion:_
```XML
item macro: '{}'.",
```
___
*[`crates/cairo-lang-defs/src/test.rs` line 447 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3878#-NcNPdPDAxcawHVwOxGH:-NcNPdPDAxcawHVwOxGI:b-wvqsqk) ([raw file](https://github.com/starkware-libs/cairo/blob/b07166160709ffafa6f6c8b05268eed1e2dd5ce3/crates/cairo-lang-defs/src/test.rs#L447)):*
> ```XML
> // Test that unknown inline item macros are raising an error.
> #[test]
> fn test_unknown_item_macro() {
> ```

Can you please do this in the (not very) new testing infra?

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3878)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-defs/src/db.rs` line 343 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3878#-NcNOhRuA79zfR3zZ2qE:-NcR8Br61-4k4Urqcp2u:b-av023g) ([raw file](https://github.com/starkware-libs/cairo/blob/b07166160709ffafa6f6c8b05268eed1e2dd5ce3/crates/cairo-lang-defs/src/db.rs#L343)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

leftover?
</blockquote></details>

Yes, removed.
___
*[`crates/cairo-lang-defs/src/test.rs` line 447 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3878#-NcNPdPDAxcawHVwOxGH:-NcR8hbQ9bMXh4jk6g_Z:bnzxcfu) ([raw file](https://github.com/starkware-libs/cairo/blob/b07166160709ffafa6f6c8b05268eed1e2dd5ce3/crates/cairo-lang-defs/src/test.rs#L447)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Can you please do this in the (not very) new testing infra?
</blockquote></details>

All the `defs` crate tests are not using it,i'll refactor all of them together in a different PR.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3878)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-parser/src/parser_test_data/attribute_errors` line 130 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3878#-NcXTGv98jlIyAspnJOP:-NcXTGvA3ARb0v_c-17M:b-l6mkjh) ([raw file](https://github.com/starkware-libs/cairo/blob/2b5d8bb2c135757c13de65c6f6b88708375bf5ff/crates/cairo-lang-parser/src/parser_test_data/attribute_errors#L130)):*
> ```
> //! > ==========================================================================
> 
> //! > Test repeated attributed literals.
> ```

rename



_Code quote:_
```
st repeated attributed literals.
```
___
*[`crates/cairo-lang-parser/src/parser_test_data/attribute_errors` line 138 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3878#-NcXTJKU-USQYkGCuIxF:-NcXTJKU-USQYkGCuIxG:b-94209i) ([raw file](https://github.com/starkware-libs/cairo/blob/2b5d8bb2c135757c13de65c6f6b88708375bf5ff/crates/cairo-lang-parser/src/parser_test_data/attribute_errors#L138)):*
> ```
> #[aaa]
> [bbb]
> #[ccc]
> ```

Can you please add a valid item here to remove unrelated errors?
___
*[`crates/cairo-lang-parser/src/parser_test_data/attribute_errors` line 156 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3878#-NcXTWBRAVYrFLybRt3m:-NcXTWBRAVYrFLybRt3n:b2ljsmt) ([raw file](https://github.com/starkware-libs/cairo/blob/2b5d8bb2c135757c13de65c6f6b88708375bf5ff/crates/cairo-lang-parser/src/parser_test_data/attribute_errors#L156)):*
> ```
> ^
> 
> error: Missing token TerminalBang.
> ```

This is not rebased? This should be skipped.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3878)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser_test_data/attribute_errors` line 130 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3878#-NcXTGv98jlIyAspnJOP:-NcZQCig-ZyBlzCdqwQa:b-iqzshd) ([raw file](https://github.com/starkware-libs/cairo/blob/2b5d8bb2c135757c13de65c6f6b88708375bf5ff/crates/cairo-lang-parser/src/parser_test_data/attribute_errors#L130)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

rename
</blockquote></details>

This file is not part of the pr, it was shown because it was not rebased.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 18 files at r3, 14 of 14 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3878#-:-NcaQa6n60_8GziJN9OW:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 14 of 14 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3878#-:-NcabZqZ225zcGjf3yHT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by yuvalsw — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3878)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by yuvalsw — APPROVED** [review]
Merged in https://github.com/starkware-libs/cairo/pull/3968, only rebased.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3878#-:-NcqyUHNEMxkrwTXZ9Jp:bdb720f)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Comment by yuvalsw** [comment]
Merged in https://github.com/starkware-libs/cairo/pull/3968, only rebased

**Pull request closed without merging**
