### PR TITLE
Added test cases for uints eq.

### PR DESCRIPTION
**Pull request by amosStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2156)

### CODE REVIEW

**Review by amosStarkware — COMMENTED** [review]
+reviewer:@dorimedini-starkware 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2156#-:-NOKtuqE67gRDoV1gwg8:b-hz3kb8)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2156#-:-NOLLTB6BuIhJvZ8HUfn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2156)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`tests/e2e_test_data/libfuncs/u8` line 274 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2156#-NOOTzWo1sw8NbxqfV8V:-NOOTzWo1sw8NbxqfV8W:bbrxmos) ([raw file](https://github.com/starkware-libs/cairo/blob/d071cba199200ce0d9dd924576e516bd0a36d4fd/tests/e2e_test_data/libfuncs/u8#L274)):*
> ```
> //! > test_comments
> //! Different cases of a,b produce different code. This is why u8_eq has multiple e2e tests.
> //! This case produces the same code as the case (a deref, b immediate).
> ```

@dorimedini-starkware fixed a mistake here with the comments



_Code quote:_
```
//! This case produces the same code as the case (a deref, b immediate).
```

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2156#-:-NOOX3K86W66A8elhGGy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
