### PR TITLE
Updated doc of `format` inline macros.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5955)

### CODE REVIEW

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5955)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/inline_macros/format.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5955#-O0wtNjG3P8rP6hRCoKh:-O0wtNjG3P8rP6hRCoKi:b41572v) ([raw file](https://github.com/starkware-libs/cairo/blob/7788370bbe0deb561ccce08422a9bb037ac73a8f/crates/cairo-lang-semantic/src/inline_macros/format.rs#L82)):*
> ```XML
>             A common use for `format!` is concatenation and interpolation of strings. The same convention is used with `print!` and `write!` macros, depending on the intended destination of the ByteArray.
> 
>             # Panics
> ```

Hmm, we need to establish a convention of heading levels. I see that H1 is used in `std::print!` in Rust, but for example I tend to use H2 in my code and I saw this in other documentation pieces (for example [tokio](https://docs.rs/tokio/latest/src/tokio/lib.rs.html#1-690) is doing this totally randomly to my eyes).

I checked that `cargo doc` actually emits H2 here, so it looks like some processing is happening there, so perhaps `cairo-lang-doc` has to also do some kind of processing here?

cc @piotmag769 @Arcticae
___
*[`crates/cairo-lang-semantic/src/inline_macros/print.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5955#-O0wuvAfD0gqX73gZzM4:-O0wuvAfD0gqX73gZzM5:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/7788370bbe0deb561ccce08422a9bb037ac73a8f/crates/cairo-lang-semantic/src/inline_macros/print.rs#L33)):*
> ```XML
>             indoc! {r#"
>             Prints to the standard output.
>             Equivalent to the println! macro except that a newline is not printed at the end of \
> ```





_Suggestion:_
```XML
`println!`
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5955)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @gilbens-starkware, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-semantic/src/inline_macros/format.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5955#-O0wtNjG3P8rP6hRCoKh:-O0xmXQx78yGLfm6m82F:b-unr8xu) ([raw file](https://github.com/starkware-libs/cairo/blob/7788370bbe0deb561ccce08422a9bb037ac73a8f/crates/cairo-lang-semantic/src/inline_macros/format.rs#L82)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Hmm, we need to establish a convention of heading levels. I see that H1 is used in `std::print!` in Rust, but for example I tend to use H2 in my code and I saw this in other documentation pieces (for example [tokio](https://docs.rs/tokio/latest/src/tokio/lib.rs.html#1-690) is doing this totally randomly to my eyes).

I checked that `cargo doc` actually emits H2 here, so it looks like some processing is happening there, so perhaps `cairo-lang-doc` has to also do some kind of processing here?

cc @piotmag769 @Arcticae
</blockquote></details>

any operative suggestions?
(otherwise, we can easily fix in the future)
___
*[`crates/cairo-lang-semantic/src/inline_macros/print.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5955#-O0wuvAfD0gqX73gZzM4:-O0xmWkiAx659UiRQmcu:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7788370bbe0deb561ccce08422a9bb037ac73a8f/crates/cairo-lang-semantic/src/inline_macros/print.rs#L33)):*
> ```XML
>             indoc! {r#"
>             Prints to the standard output.
>             Equivalent to the println! macro except that a newline is not printed at the end of \
> ```

Done.

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5955#-:-O0xox_GCZher9EL-O-p:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/inline_macros/format.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5955#-O0wtNjG3P8rP6hRCoKh:-O0xokvvEshBN2FIVVQm:b-2ecup2) ([raw file](https://github.com/starkware-libs/cairo/blob/7788370bbe0deb561ccce08422a9bb037ac73a8f/crates/cairo-lang-semantic/src/inline_macros/format.rs#L82)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

any operative suggestions?
(otherwise, we can easily fix in the future)
</blockquote></details>

Fix in the future. This is fine here, it's just a problem for LS and `scarb doc` now (H1 headers are h u g e in VSCode in hovers)

**Review by piotmag769 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5955)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by piotmag769 — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5955)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
