### PR TITLE
SemanticPlugin static

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1516)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1516)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1516#-NKJKi1XBbaFI4uFByBV:-NKJKi1XBbaFI4uFByBW:b5icwjj) (no related file):*
can you please add more data about why is this required?

___

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1516)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/compiler/src/db.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1516#-NKJR4aT-cEDGh0uu6v3:-NKJR4aT-cEDGh0uu6v4:by8lm26) ([raw file](https://github.com/starkware-libs/cairo/blob/ba2d3d692cf2b4445ea47fcc78e491395b42dedd/crates/compiler/src/db.rs#L72)):*
> ```XML
>     }
> }
> impl Elongate for RootDatabase {
> ```

Document.



_Code quote:_
```XML
Elongate
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1516)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1516#-NKJKi1XBbaFI4uFByBV:-NKMpowT1AY5B4l8ZS4I:bumevut) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can you please add more data about why is this required?
</blockquote></details>

This let's you use diagnostic.format(), which required `dyn SemanticGroup+'static`.

___

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1516)* status: 2 of 9 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/compiler/src/db.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1516#-NKJR4aT-cEDGh0uu6v3:-NKMsUNm0-g9sVTsQ79e:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ba2d3d692cf2b4445ea47fcc78e491395b42dedd/crates/compiler/src/db.rs#L72)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Document.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1516#-:-NKMxgKACqGUCrLvZApP:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 9 files at r1, 1 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1516#-:-NKMyhUxEkxZyLuVaadD:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1516)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1516)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
