### PR TITLE
Added contract_address_is_zero libfunc

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2604)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2604)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2604#-NRTlQFM63Ykdl-rVM-a:-NRTlQFM63Ykdl-rVM-b:b-u7t3iz) (no related file):*
Is this required for the NonZero wrap? If not - close pr, as this can be achieved using felt conversion and compare to 0

___

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2604)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2604#-NRTlQFM63Ykdl-rVM-a:-NRTmsV14bsKYgDShUdP:bvwme96) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Is this required for the NonZero wrap? If not - close pr, as this can be achieved using felt conversion and compare to 0
</blockquote></details>

Indeed, it is used in the following PR by the nonzero wrap.

___

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2604)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2604#-NRTlQFM63Ykdl-rVM-a:-NRWg_Bg41yW_T-jNRc2:b-he6gic) (no related file):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Indeed, it is used in the following PR by the nonzero wrap.
</blockquote></details>

why do you need a NonZero<ContractAddress>?

___

**Review by orizi — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2604)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Pull request closed without merging**
