### PR TITLE
'Pow' operator

### PR DESCRIPTION
**Pull request by wraitii**
This is mostly intended for use in the `consteval_int!` macro, but could work in general.

Allows writing:

```const some_bitmask: felt252 = consteval_int!(2**128 - 1);```
 and the likes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3408)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3408)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @wraitii)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3408#-NYYQrR7EDx2M4uwdLXw:-NYYQrR7EDx2M4uwdLXx:b-cszlbk) (no related file):*
i have no issue with the trait - but i'm not sure we want to operator.
if it is for the consteval_int! - finding the method call for pow being called would work as well.

___

**Comment by wraitii** [comment]
@orizi Hm, to be honest this seems somewhat problematic to me.
The raw AST that plugins get is not really aware of traits or anything like that, hence `3.add(5)` wouldn't be parsed correctly where `3 + 5` would. Adding `.pow()` is possible, but I feel like it introduces a weird edge-case in something that otherwise would behave quite normally.

One option that would be more sane would be a `pow!()` macro.

**Review by orizi — COMMENTED** [review]
`3.add(5)` would be parsed correctly - it just won't be aware of the trait itself.
since this is all wrapped by a macro it can still be caught.
I see no particular difference between this and a `pow!` macro - besides just adding an additional macro.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3408#-:-NYkwv504y2tGWFgGIb9:bssh1bj)* status: 0 of 13 files reviewed, 1 unresolved discussion

**Review by wraitii — COMMENTED** [review]
Just to add some clarity, I didn't mean that it wouldn't 'parsed' correctly on the AST level but more semantically.
The implementation here for `consteval_int!` understands `3.pow(4)` and `3 + 4` but not `3.add(4)`

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3408#-:-NYrdbgiB6dQ_JMrHegh:bszjlg2)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 13 files at r1, 11 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3408)* status: 12 of 14 files reviewed, 2 unresolved discussions (waiting on @wraitii)

___
*[`corelib/src/traits.cairo` line 44 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3408#-NYrwT7eCadQahAoykbd:-NYrwT7eCadQahAoykbe:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/eee7009cfce739f3bb68217f6ca6cf4fa1dff466/corelib/src/traits.cairo#L44)):*
> ```Cairo
> trait Pow<T> {
>     fn pow(lhs: T, rhs: T) -> T;
> }
> ```





_Suggestion:_
```Cairo

trait Pow<T, S> {
    fn pow(lhs: T, rhs: S) -> T;
}
```

**Review by wraitii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3408)* status: 12 of 14 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/traits.cairo` line 44 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3408#-NYrwT7eCadQahAoykbd:-NYs3Its7OlHk3KUQ06v:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/eee7009cfce739f3bb68217f6ca6cf4fa1dff466/corelib/src/traits.cairo#L44)):*
> ```Cairo
> trait Pow<T> {
>     fn pow(lhs: T, rhs: T) -> T;
> }
> ```

Done.

**Pull request closed without merging**
