### PR TITLE
Refactor gas invocations.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4702)

### CODE REVIEW

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4702)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs` line 202 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4702#-Nn3QnNnAtgxb7w0gVbG:-Nn3QnNnAtgxb7w0gVbH:b9oezrw) ([raw file](https://github.com/starkware-libs/cairo/blob/a3a925db8bdb8341764079f32adf214d666ee41a/crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs#L202)):*
> ```XML
> }
> 
> /// Adds the code for calculating the total requested count of gas to update the counter with.
> ```

Add `Returns ...` and explain what are the two results.

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4702)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4702)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs` line 202 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4702#-Nn3QnNnAtgxb7w0gVbG:-Nn3VmQX8HVH9HlLE4sr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a3a925db8bdb8341764079f32adf214d666ee41a/crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs#L202)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Add `Returns ...` and explain what are the two results.
</blockquote></details>

Done.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4702)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs` line 204 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4702#-Nn3_AUc9Xzyf09s4k86:-Nn3_AUc9Xzyf09s4k87:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/89f89985abc4ec422b91c7caae29bcdf148fe10b/crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs#L204)):*
> ```XML
> /// Adds the code for calculating the total requested count of gas to update the counter with.
> /// Returns the requested const cost requested and a variable containing the amount to update the
> /// gas counter with.
> ```





_Suggestion:_
```XML
/// Returns the requested *const* cost and a variable containing the amount to update the
/// gas counter with (total cost).
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4702)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs` line 204 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4702#-Nn3_AUc9Xzyf09s4k86:-Nn3cZ2K2a9Xf9PqMGm3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/89f89985abc4ec422b91c7caae29bcdf148fe10b/crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs#L204)):*
> ```XML
> /// Adds the code for calculating the total requested count of gas to update the counter with.
> /// Returns the requested const cost requested and a variable containing the amount to update the
> /// gas counter with.
> ```

Done.

**Review by liorgold2 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4702)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4702#-:-Nn3f5HvA6yBjnz4pEli:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
