### PR TITLE
Add const folding optimization.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4554)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4554)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/const_folding.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4554#-NlXkpaxCPPpbq_ioOm9:-NlXkpaxCPPpbq_ioOmA:biir2ec) ([raw file](https://github.com/starkware-libs/cairo/blob/51df7c53f85bb0f85b6f5f8af89685228db74430/crates/cairo-lang-lowering/src/optimizations/const_folding.rs#L18)):*
> ```XML
> };
> 
> // We keep track of two var states:
> ```

Doc with /// and doc the variants directly.
___
*[`crates/cairo-lang-lowering/src/optimizations/const_folding.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4554#-NlY-Ct7-HN8FVkvI81P:-NlY-Ct7-HN8FVkvI81Q:bjqyqek) ([raw file](https://github.com/starkware-libs/cairo/blob/bb23a091897cbd2687f2d6b7eac61acb4abf0a21/crates/cairo-lang-lowering/src/optimizations/const_folding.rs#L33)):*
> ```XML
>     }
> 
>     let mut var_states = HashMap::new();
> ```

this is alive across blocks - how do we know for sure this is fine?
or if we have the same variable it is the result of a merge?
Also - are we assuming anything about the sorting of the blocks?
___
*[`crates/cairo-lang-lowering/src/optimizations/const_folding.rs` line 73 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4554#-NlXzUw43y5MOCu6YalE:-NlXzUw43y5MOCu6YalF:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/bb23a091897cbd2687f2d6b7eac61acb4abf0a21/crates/cairo-lang-lowering/src/optimizations/const_folding.rs#L73)):*
> ```XML
>                     }
> 
>                     // (a - 0) can be repalced by a.
> ```





_Suggestion:_
```XML
                    // (a - 0) can be replaced by a.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/optimizations/const_folding.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4554#-NlY-Ct7-HN8FVkvI81P:-NlY1W098tM-LlCsnfYu:bgzb86i) ([raw file](https://github.com/starkware-libs/cairo/blob/bb23a091897cbd2687f2d6b7eac61acb4abf0a21/crates/cairo-lang-lowering/src/optimizations/const_folding.rs#L33)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is alive across blocks - how do we know for sure this is fine?
or if we have the same variable it is the result of a merge?
Also - are we assuming anything about the sorting of the blocks?
</blockquote></details>

I can clear it.

but its we assume ssa.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4554)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/const_folding.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4554#-NlXkpaxCPPpbq_ioOm9:-NlYQr4H4GtOi78_CN2F:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/51df7c53f85bb0f85b6f5f8af89685228db74430/crates/cairo-lang-lowering/src/optimizations/const_folding.rs#L18)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Doc with /// and doc the variants directly.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/optimizations/const_folding.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4554#-NlY-Ct7-HN8FVkvI81P:-NlYRJV32krON3X5pei3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bb23a091897cbd2687f2d6b7eac61acb4abf0a21/crates/cairo-lang-lowering/src/optimizations/const_folding.rs#L33)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

shouldn't clear - but add doc as discussed.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/optimizations/const_folding.rs` line 73 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4554#-NlXzUw43y5MOCu6YalE:-NlYRKA27jbPisvC_74s:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bb23a091897cbd2687f2d6b7eac61acb4abf0a21/crates/cairo-lang-lowering/src/optimizations/const_folding.rs#L73)):*
> ```XML
>                     }
> 
>                     // (a - 0) can be repalced by a.
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4554)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/const_folding.rs` line 25 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4554#-NlYeG3M2artU_vuI_gL:-NlYeG3NB6CArKuXfegI:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/27d50e159587d33cfbe8027dd4e63832ff5b1635/crates/cairo-lang-lowering/src/optimizations/const_folding.rs#L25)):*
> ```XML
>     Literal(BigInt),
>     Var(VarUsage),
> }
> ```





_Suggestion:_
```XML
/// "Add some description of what it is"
/// Note: We don't keep track of snap/desnap as we assume that they are cancelled out before usage.
enum VarState {
    /// The variable is a literal value.
    Literal(BigInt),
    /// The variable can be replaced by another variable.
    Var(VarUsage),
}
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4554)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/const_folding.rs` line 25 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4554#-NlYeG3M2artU_vuI_gL:-Nlb9C3lAELd3QAyjRvK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/27d50e159587d33cfbe8027dd4e63832ff5b1635/crates/cairo-lang-lowering/src/optimizations/const_folding.rs#L25)):*
> ```XML
>     Literal(BigInt),
>     Var(VarUsage),
> }
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4554#-:-Nlb9mJq6u28aPHvIvan:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
