### PR TITLE
feat: Zero and One traits

### LINKED ISSUE #4236: feat: public `Zero` and `One`traits
# Feature Request
Following the discussion in #4037, I propose to implement the `Zero` and `One` traits to be used externally.
An implementation of `One` has already been proposed in #3891 but there haven't been any updates for a few months.

**Describe the Feature Request**

Therefore, I propose to continue the work and to create a `num/traits` dir, and add the `Zero` and `One` traits. 

**Describe Preferred Solution**
These traits would have an impl generic over `T, +Oneable<T>` and `T, +Zeroable<T>` to avoid code duplication - and for the types that don't implement `Oneable` or `Zeroable` like `felt252`, we can write custom impls.

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by enitrat**
Continues the work started in #3891
Closes #4236

- [x] Created a `num` directory with `traits.cairo` file
- [x] Added a `One` trait, and implementations for `uints`, `ints` and `felt252`
- [x] Added a `Zero` trait, and implementations for `uints`, `ints` and `felt252`
- [x] Made the `Zeroable` trait generically implemented from the `Zero` trait
- [x] Made the `Oneable` trait generically implemented from the `One` trait

Questions:

- Should I split them into `num/traits/one.cairo` and `num/traits/zero.cairo`?
- Should I bring other numeric traits inside this dir

Starknet tests are failing but I'm not sure why.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4254)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4254)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @enitrat)

___
*[`corelib/src/num/traits.cairo` line 6 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4254#-Ngw_QCGAGj2Hb73PRTN:-Ngw_QCGAGj2Hb73PRTO:b-oschig) ([raw file](https://github.com/starkware-libs/cairo/blob/edbca1b7fd090e713a86c7998ef6178a67cf0d88/corelib/src/num/traits.cairo#L6)):*
> ```Cairo
>     /// Returns the multiplicative identity element of Self, 0.
>     #[inline(always)]
>     fn zero() -> T;
> ```

doesn't do anything here.
and generally avoid unless you have a specific issue (for example, making a current test contract be less efficient)



_Suggestion:_
```Cairo
trait Zero<T> {
    /// Returns the multiplicative identity element of Self, 0.
    fn zero() -> T;
```
___
*[`corelib/src/num/traits.cairo` line 15 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4254#-Ngw_tZ0DOkVR1d926I5:-Ngw_tZ0DOkVR1d926I6:b-vtovpl) ([raw file](https://github.com/starkware-libs/cairo/blob/edbca1b7fd090e713a86c7998ef6178a67cf0d88/corelib/src/num/traits.cairo#L15)):*
> ```Cairo
> impl Felt252Zero of Zero<felt252> {
>     #[inline(always)]
>     fn zero() -> felt252 {
> ```

this is already inlined by heuristic.



_Suggestion:_
```Cairo
    fn zero() -> felt252 {
```

**Comment by enitrat** [comment]
Removed `#[inline(always)]` for `zero()` and `one()` functions

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4254#-:-NgxTZqSAQbHfhf5LNTs:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @enitrat)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4254#-NgxTbLN16X26ZqMlMXT:-NgxTbLN16X26ZqMlMXU:bpx0xxa) (no related file):*
@yuvalsw for 2nd eye.

___

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4254)* status: all files reviewed, 7 unresolved discussions (waiting on @enitrat)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4254#-Nh1JiZzAqwwVNlF1f-c:-Nh1JiZzAqwwVNlF1f-d:bjilq2o) (no related file):*
Please split into `num/traits/one.cairo` and `num/traits/zero.cairo` as suggested, and re-export them in num/traits.cairo (e.g. `use one::One;`).

___
___
*[`corelib/src/math.cairo` line 132 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4254#-NgyIEUz1qvZrLoIFM4O:-NgyIEUz1qvZrLoIFM4P:bwuz7d2) ([raw file](https://github.com/starkware-libs/cairo/blob/215297b2d8123fd5406fd49ecf266e4ed6537af3/corelib/src/math.cairo#L132)):*
> ```Cairo
> }
> 
> impl TOneableImpl<T, +One<T>, +Drop<T>> of Oneable<T> {
> ```

I think you should +Copy<T> here too, we don't want any such impl to be consuming.
___
*[`corelib/src/zeroable.cairo` line 13 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4254#-NgyI_3d0nvLGFxJXDM8:-NgyI_3d0nvLGFxJXDM9:b-2guby3) ([raw file](https://github.com/starkware-libs/cairo/blob/215297b2d8123fd5406fd49ecf266e4ed6537af3/corelib/src/zeroable.cairo#L13)):*
> ```Cairo
> }
> 
> impl ZeroableImpl<T, +Zero<T>, +Drop<T>> of Zeroable<T> {
> ```

same here
___
*[`corelib/src/num/traits.cairo` line 3 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4254#-NgyIhTp7QRoB8sPfc2y:-NgyIhTp7QRoB8sPfc2z:b-c0ro5a) ([raw file](https://github.com/starkware-libs/cairo/blob/215297b2d8123fd5406fd49ecf266e4ed6537af3/corelib/src/num/traits.cairo#L3)):*
> ```Cairo
> // === Zero ===
> 
> trait Zero<T> {
> ```

please doc. Same for `One`
___
*[`corelib/src/num/traits.cairo` line 9 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4254#-NgyIqX65TT5vzNYb3Ld:-NgyIqX65TT5vzNYb3Le:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/215297b2d8123fd5406fd49ecf266e4ed6537af3/corelib/src/num/traits.cairo#L9)):*
> ```Cairo
>     fn is_zero(self: @T) -> bool;
>     /// Returns whether self is not equal to 0, the multiplicative identity element.
>     fn is_non_zero(self: @T) -> bool;
> ```





_Suggestion:_
```Cairo
    /// Returns the additive identity element of Self, 0.
    fn zero() -> T;
    /// Returns whether self is equal to 0, the additive identity element.
    fn is_zero(self: @T) -> bool;
    /// Returns whether self is not equal to 0, the additive identity element.
    fn is_non_zero(self: @T) -> bool;
```
___
*[`corelib/src/num/traits.cairo` line 12 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4254#-Nh1Hw2L6vyyd3ilmqxS:-Nh1Hw2L6vyyd3ilmqxT:b-gjswnp) ([raw file](https://github.com/starkware-libs/cairo/blob/215297b2d8123fd5406fd49ecf266e4ed6537af3/corelib/src/num/traits.cairo#L12)):*
> ```Cairo
> }
> 
> impl Felt252Zero of Zero<felt252> {
> ```

Please move the impls to the module where the type is defined and not here. E.g. for `uints` move to integer.cairo.



_Code quote:_
```Cairo
impl Felt252Zero of Zero<felt252> {
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4254)* status: 4 of 8 files reviewed, 8 unresolved discussions (waiting on @enitrat and @yuvalsw)

___
*[`corelib/src/lib.cairo` line 8 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4254#-Nh2kOxx3GI7d3J_LEsC:-Nh2kOxx3GI7d3J_LEsD:bl0rk35) ([raw file](https://github.com/starkware-libs/cairo/blob/7f022b618b2bc19f8ff532b85efd4ba34279fa30/corelib/src/lib.cairo#L8)):*
> ```Cairo
> };
> use serde::Serde;
> use num::traits::{Zero, One};
> ```

remove this use - as this exports this as core::One - which we shouldn't.

**Comment by enitrat** [comment]
Removed import of `num::traits::{Zero,One}` in `lib.cairo`
Referred to the full path of `num::traits::Zero` and `num::traits::One` in the impl for `felt252` in `lib.cairo` instead

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4254)* status: 5 of 8 files reviewed, 8 unresolved discussions (waiting on @enitrat and @yuvalsw)

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4254)* status: all files reviewed, 7 unresolved discussions (waiting on @enitrat)

___
*[`corelib/src/integer.cairo` line 7 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4254#-Nh6035I8tugBY_m_L5W:-Nh6035I8tugBY_m_L5X:b-tprmrm) ([raw file](https://github.com/starkware-libs/cairo/blob/bbad4cb3d9eadadf9938f76f45767c2e0affdbf4/corelib/src/integer.cairo#L7)):*
> ```Cairo
> use array::ArrayTrait;
> use array::SpanTrait;
> use num::traits::{Zero, One};
> ```

this also re-exports it from here. Better fully qualify in the usage instead.
___
*[`corelib/src/lib.cairo` line 211 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4254#-Nh69ort9_Nf5AKHbAm5:-Nh69ort9_Nf5AKHbAm6:b-nbpp2b) ([raw file](https://github.com/starkware-libs/cairo/blob/bbad4cb3d9eadadf9938f76f45767c2e0affdbf4/corelib/src/lib.cairo#L211)):*
> ```Cairo
> 
> 
> impl Felt252Zero of num::traits::Zero<felt252> {
> ```

please move these to felt252.cairo (create it). Felt stuff should be in a dedicated module. We can't yet move items that are here as it would break existing code, but new items should be there.
Thanks!

**Comment by enitrat** [comment]
- Removed import of `{Zero,One}` in `integer.cairo` and used full paths
- Moved `Felt252{Zero,One}` to `felt252.cairo`

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4254)* status: all files reviewed, 6 unresolved discussions (waiting on @enitrat)

**Comment by enitrat** [comment]
> would be slightly better to use the specific impl directly and not the trait.

Done. 

Also, I noticed that I was importing `One` in `math.cairo` and `Zero` in `Zeroable`. For consistency with previous reviews, I used explicit full paths instead.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
Good catch, thanks. Hope this is the last iteration :)

> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4254#-:-Nh7UMAg5BBB6VLL63Fe:b-ojbsdb)* status: all files reviewed, 1 unresolved discussion (waiting on @enitrat)

___
*[`corelib/src/math.cairo` line 143 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4254#-Nh7U3D64lqC_dO_KvkZ:-Nh7U3D64lqC_dO_Kvk_:b-apj5so) ([raw file](https://github.com/starkware-libs/cairo/blob/d6754d1128fef575c121f59e4d10e167d9c44634/corelib/src/math.cairo#L143)):*
> ```Cairo
>         num::traits::One::is_non_one(@self)
>     }
> }
> ```

same in zeroable



_Suggestion:_
```Cairo
impl TOneableImpl<T, impl OneImpl: num::traits::One<T>, +Drop<T>, +Copy<T>> of Oneable<T> {
    fn one() -> T {
        OneImpl::one()
    }
    #[inline(always)]
    fn is_one(self: T) -> bool {
        OneImpl::is_one(@self)
    }
    #[inline(always)]
    fn is_non_one(self: T) -> bool {
        OneImpl::is_non_one(@self)
    }
}
```

**Comment by enitrat** [comment]
Done, should be all good now, thanks for taking the time!

**Review by yuvalsw — APPROVED** [review]
LGTM, but CI fails. Please check and fix.

> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4254#-:-Nh7serNBlJh4T19q3F_:bfrsirb)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enitrat)

**Comment by enitrat** [comment]
CI fails after moving felt impls to `felt_252.cairo`. Because these impls are not part of the prelude, they're not found by the generic `TZeroableImpl` - and thus `Zeroable<felt252>` can't be used as it used to before.
The following code is erroneous:
```rust
    #[inline(always)]
    fn is_zero(self: EthAddress) -> bool {
        self.address.is_zero()
    }
```
--> 
```shell
Method `is_zero` not found on type "core::felt252". Did you import the correct trait and impl?
```
One solution would be this

```rust
use felt_252::{Felt252Zero};

    //...
    #[inline(always)]
    fn is_zero(self: EthAddress) -> bool {
        zeroable::TZeroableImpl::<felt252>::is_zero(self.address)
    }
```    

But I'm not sure if it's the best approach.

**Review by yuvalsw — APPROVED** [review]
The third approach SG. Also note:
1. you must rename felt252.cairo to e.g. felt_252.cairo. Otherwise there would be a conflict with the type name.
2. You need to add felt_252 as a module in lib.cairo.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4254#-:-NhMAnlcEHhYZRL8mH_P:b2oxvz3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enitrat)

**Comment by enitrat** [comment]
Added `impl Felt252Zeroable = zeroable::TZeroableImpl<felt252>;` in `felt_252.cairo`.
Explicitly used this impl in `class_hash`, `contract_address`, and `eth_address` files with:
```rust
    #[inline(always)]
    fn is_zero(self: EthAddress) -> bool {
        felt_252::Felt252Zeroable::is_zero(self.address)
    }
```

**Review by yuvalsw — APPROVED** [review]
That is true, but as you realised, it's currently impossible to remove it from the prelude. We are working on solutions to do that. For now we have some workarounds.

What I meant is to have the generic impl (TZeroableImpl) "hidden" (in a module), and instantiate impl aliases of it with the concrete relevant types, each in its relevant module. A similar approach is used in into_felt252_based::HashImpl, you can take a look there.
This will mean that Zeroable will not be implemented (in context) for any type that implements Zero, but only for the types for which there is an impl alias with them as the generic argument.
For now, there will indeed be ambiguity between Zeroable and Zero for the types already implementing Zeroable, so you can't use Zero for such types. What would be possible is to use it in generic implementations, e.g. `fn something<T, +Zero<T>>(t: T) { ... t.is_zero() ... }`.

I feel like it's not super clear what needs to be done here, so let me try to elaborate:
1. Put the generic impl of Zeroable in an inline module.
2. Have impl aliases with the relevant type for all the types that already implement Zeroable (like you did).
3. Leave Zero as is.
4. Same for One.

> Reviewed 2 of 5 files at r8, 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4254#-:-NhQsimqAomVuKcwpekn:b-dmsz7p)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enitrat)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4254)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enitrat)

___
*[`corelib/src/zeroable.cairo` line 24 at r9](https://reviewable.io/reviews/starkware-libs/cairo/4254#-NhVE01VE_g5xXEAOx7g:-NhVE01VE_g5xXEAOx7h:b6uuhja) ([raw file](https://github.com/starkware-libs/cairo/blob/849c327c8a01ffb7ce76f09cfc8f2ec151240615/corelib/src/zeroable.cairo#L24)):*
> ```Cairo
>         ZeroImpl::is_non_zero(@self)
>     }
> }
> ```

as this currently causes `Zeroable` to be available whenever `Zero` is available, so `is_zero` is always ambiguous - we can do this instead:

(this would provide backwards compatility for *only* what we already provided without causing collisions in the general case)

Do the same for Oneable.
(just saw yuval wrote the same thing, but this is some more info, so leaving here)



_Suggestion:_
```Cairo
mod zero_based {
impl ZeroableImpl<T, impl ZeroImpl: num::traits::Zero<T>, +Drop<T>, +Copy<T>> of Zeroable<T> {
    fn zero() -> T {
        ZeroImpl::zero()
    }
    #[inline(always)]
    fn is_zero(self: T) -> bool {
        ZeroImpl::is_zero(@self)
    }
    #[inline(always)]
    fn is_non_zero(self: T) -> bool {
        ZeroImpl::is_non_zero(@self)
    }
}
}
/// In the files this originally existed in:
impl U8Zeroable = zero_based::ZeroableImpl<u8, integer::U8Zero>;
impl U16Zeroable = zero_based::ZeroableImpl<u16, integer::U16Zero>;
impl U32Zeroable = zero_based::ZeroableImpl<u32, integer::U32Zero>;
impl U64Zeroable = zero_based::ZeroableImpl<u64, integer::U64Zero>;
impl U128Zeroable = zero_based::ZeroableImpl<u128, integer::U128Zero>;
impl U256Zeroable = zero_based::ZeroableImpl<u256, integer::U256Zero>;
```

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4254)* status: all files reviewed, 7 unresolved discussions (waiting on @enitrat)

___
*[`.tool-versions` line 0 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4254#-NhbUO0r4sq7CMkWPlsw:-NhbUO0s1uUyZAmkSgi0:b562r1x) ([raw file](https://github.com/starkware-libs/cairo/blob/650cb56e8afec0f2ad7784f539019ad362687ccf/.tool-versions#L0)):*
this is unrelated.
___
*[`corelib/src/integer.cairo` line 2332 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4254#-NhbUq9h6jRlezT1uO-Z:-NhbUq9h6jRlezT1uO-_:b504dpi) ([raw file](https://github.com/starkware-libs/cairo/blob/650cb56e8afec0f2ad7784f539019ad362687ccf/corelib/src/integer.cairo#L2332)):*
> ```Cairo
> 
> // Zero trait implementations
> impl U8Zero of num::traits::Zero<u8> {
> ```

BTW, you can use the same method for these impls. Impl it once, generically and hidden in an inner module here, and then have impl aliases. It would be shorter.

Same for One.
___
*[`corelib/src/math.cairo` line 131 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4254#-NhbXPtv3Cx__C-5X0uO:-NhbXPtv3Cx__C-5X0uP:b-l47zyh) ([raw file](https://github.com/starkware-libs/cairo/blob/650cb56e8afec0f2ad7784f539019ad362687ccf/corelib/src/math.cairo#L131)):*
> ```Cairo
> }
> 
> impl TOneableImpl<T, impl OneImpl: num::traits::One<T>, +Drop<T>, +Copy<T>> of Oneable<T> {
> ```

do the same for oneable. "Hidden" generic impl plus impl aliases.
___
*[`corelib/src/zeroable.cairo` line 28 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4254#-NhbWjQ12k7nTwjGcZfk:-NhbVvWf4AXHDkAquo2S:b-xg09ii) ([raw file](https://github.com/starkware-libs/cairo/blob/650cb56e8afec0f2ad7784f539019ad362687ccf/corelib/src/zeroable.cairo#L28)):*
> ```Cairo
> }
> 
> impl ContractAddressZeroable = zeroable::zero_based::ZeroableImpl<felt252, felt_252::Felt252Zero>;
> ```

Remove, I see it's already in contract_address.cairo, and correctly (here you accidentally use felt252).



_Code quote:_
```Cairo
impl ContractAddressZeroable = zeroable::zero_based::ZeroableImpl<felt252, felt_252::Felt252Zero>;
```
___
*[`corelib/src/starknet/class_hash.cairo` line 40 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4254#-NhbWKF77mnLwINj4sxj:-NhbWKF77mnLwINj4sxk:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/650cb56e8afec0f2ad7784f539019ad362687ccf/corelib/src/starknet/class_hash.cairo#L40)):*
> ```Cairo
> }
> 
> impl ContractAddressZeroable = zeroable::zero_based::ZeroableImpl<ClassHash, ClassHashZero>;
> ```





_Suggestion:_
```Cairo
ClassHashZeroable
```
___
*[`corelib/src/starknet/contract_address.cairo` line 42 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4254#-NhbWPq5-Rzj84Md0ILc:-NhbWPq5-Rzj84Md0ILd:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/650cb56e8afec0f2ad7784f539019ad362687ccf/corelib/src/starknet/contract_address.cairo#L42)):*
> ```Cairo
> }
> 
> impl ContractAddressZeroable = zeroable::zero_based::ZeroableImpl<ContractAddress,ContractAddressZero>;
> ```





_Suggestion:_
```Cairo
ContractAddress, ContractAddre
```
___
*[`corelib/src/felt_252.cairo` line 33 at r8](https://reviewable.io/reviews/starkware-libs/cairo/4254#-NhbX5fZAnUZozolxa4p:-NhbX5fZAnUZozolxa4q:b-1y81no) ([raw file](https://github.com/starkware-libs/cairo/blob/82178e875e1bbcc2eb8c747dd2185b16aa13d519/corelib/src/felt_252.cairo#L33)):*
> ```Cairo
> }
> 
> impl Felt252Zeroable = zeroable::TZeroableImpl<felt252>;
> ```

An impl for felt existed , use an impl alias instead here.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4254)* status: all files reviewed, 2 unresolved discussions (waiting on @enitrat)

___
*[`.tool-versions` line  at r10](https://reviewable.io/reviews/starkware-libs/cairo/4254#-NhbUO0r4sq7CMkWPlsw:-NhboDa48YJ7Sqwe9fEO:b-1ezyce) ([raw file](https://github.com/starkware-libs/cairo/blob/650cb56e8afec0f2ad7784f539019ad362687ccf/.tool-versions#L)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I still see it.
___
*[`corelib/src/integer.cairo` line 2332 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4254#-NhbUq9h6jRlezT1uO-Z:-NhfPxtM8fH9xnB_D8r-:b-moo64w) ([raw file](https://github.com/starkware-libs/cairo/blob/650cb56e8afec0f2ad7784f539019ad362687ccf/corelib/src/integer.cairo#L2332)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

I don't think I can because I cannot create generic numeric literals. Or I didn't understand what you suggested, but I don't see how I can create a generic impl for `Zero` and `One`.
</blockquote></details>

Ah, you are right, it's not currently possible.

**Review by enitrat — COMMENTED** [review]
Should be good now, sorry for the troubles - I finally understood how reviewable works which makes thing easier indeed.

I still have this CI problem I raised above.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4254#-:-Nhfg9q9EnqWvIMiA4A7:beo36f9)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`.tool-versions` line  at r10](https://reviewable.io/reviews/starkware-libs/cairo/4254#-NhbUO0r4sq7CMkWPlsw:-Nhfg2gWBqGfr2dn7cwW:b6twlmf) ([raw file](https://github.com/starkware-libs/cairo/blob/650cb56e8afec0f2ad7784f539019ad362687ccf/.tool-versions#L)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I still see it.
</blockquote></details>

Done. For some reason it reappeard :thinking:

**Review by yuvalsw — CHANGES_REQUESTED** [review]
Yes, please update the expected test files with: `CAIRO_FIX_TESTS=1 cargo test -p starknet`.
We'll review the changes to make sure they look good.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4254#-:-NhfspDg3zrBm6QDZCoN:b-rfr16r)* status: all files reviewed, 1 unresolved discussion (waiting on @enitrat)

___
*[`.tool-versions` line  at r10](https://reviewable.io/reviews/starkware-libs/cairo/4254#-NhbUO0r4sq7CMkWPlsw:-Nhfp8Rp-RhRKHi6m6bl:b-bsn05a) ([raw file](https://github.com/starkware-libs/cairo/blob/650cb56e8afec0f2ad7784f539019ad362687ccf/.tool-versions#L)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

Done. For some reason it reappeard :thinking:
</blockquote></details>

I still see it :(

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 15 of 15 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4254#-:-Nhg6xkQAKmVEA5QMXIL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enitrat)

**Comment by yuvalsw** [comment]
Seems like you need to rebase.

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 7 files at r3, 1 of 2 files at r4, 1 of 5 files at r8, 1 of 4 files at r9, 3 of 7 files at r10, 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4254)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enitrat)

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 15 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4254)* status: 15 of 28 files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
> Reviewed 15 of 15 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4254)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enitrat)

**Pull request merged**
