### PR TITLE
Return diagnostics severity in formatter parsing errors

### PR DESCRIPTION
**Pull request by maciektr**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4527)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4527)* status: all files reviewed, 2 unresolved discussions (waiting on @maciektr)

___
*[`crates/cairo-lang-formatter/src/cairo_formatter.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4527#-Nl3ojP_Bw1fg-JdpONB:-Nl3ojP_Bw1fg-JdpONC:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/dc55ecd69ffb87a524008e6daa7fec788471e3b5/crates/cairo-lang-formatter/src/cairo_formatter.rs#L101)):*
> ```XML
> 
> #[derive(Debug, Error)]
> pub struct ParsingError(Vec<FormattedDiagnosticEntry>);
> ```

doc
___
*[`crates/cairo-lang-formatter/src/cairo_formatter.rs` line 196 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4527#-Nl3oQCg1kPNw5NxUvSl:-Nl3oQCg1kPNw5NxUvSm:b-picheq) ([raw file](https://github.com/starkware-libs/cairo/blob/dc55ecd69ffb87a524008e6daa7fec788471e3b5/crates/cairo-lang-formatter/src/cairo_formatter.rs#L196)):*
> ```XML
>     let (syntax_root, diagnostics) = get_syntax_root_and_diagnostics(&db, file_id, &original_text);
>     if diagnostics.check_error_free().is_err() {
>         // bail!(diagnostics.format(&db));
> ```

remove old.

**Comment by maciektr** [comment]
*[`crates/cairo-lang-formatter/src/cairo_formatter.rs` line 196 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4527#-Nl3oQCg1kPNw5NxUvSl:-Nl3rMoa8DfMJtYkXUUf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/dc55ecd69ffb87a524008e6daa7fec788471e3b5/crates/cairo-lang-formatter/src/cairo_formatter.rs#L196)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove old.
</blockquote></details>

Done.

**Comment by maciektr** [comment]
*[`crates/cairo-lang-formatter/src/cairo_formatter.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4527#-Nl3ojP_Bw1fg-JdpONB:-Nl3rNhL1owVwmwSh0y9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/dc55ecd69ffb87a524008e6daa7fec788471e3b5/crates/cairo-lang-formatter/src/cairo_formatter.rs#L101)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4527#-:-Nl3wPhd1DBmClelNMcV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciektr)

**Pull request merged**
