### PR TITLE
Insert right paren after cursor when completing funciton/method calls

### LINKED ISSUE #5935: Insert right paren after cursor when completing funciton/method calls
Currently, LS is completing functions/methods like this:

```rust
// before
x.<caret>

// after
x.foo(<caret>
```

Change this to work as following:

```rust
// before
x.<caret>

// after
x.foo(<caret>)
```

Code to update:

https://github.com/starkware-libs/cairo/blob/cdaceb909ccf0644b7e385669d2c48417ceb90d4/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L285

### PR DESCRIPTION
**Pull request by RuneRogue**
New PR

Fixed #5935

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6345)

### CODE REVIEW

**Comment by RuneRogue** [comment]
Continuing #6320

**Review by RuneRogue — COMMENTED** [review]
I have figured out the reason of having different test data . It is because of giving space between parentheses . First visit test/e2e/completions.rs line 62 - 67  . You can see that whenever there will be change in the "additional_text_edits" , It is going to print 'Text edit: ' . That's why we were getting different test data . 

Also One more thing that I have noticed that in test data 'Text edit: ' was printed for every function that should not be happen . Because our idea is to give space b/w parentheses whenever there is a parameter . But catch was , most of function have 'self' , '&self' and '&mut self' as argument . so our code was giving space between parentheses for every function . So i excluded those 3 parameters because that value will not be passed by users right?! So after excluding those function , our code logic will give space between parentheses only for those function that accept some value . 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6345#-:-O5tQBWL08um0xoNPELh:b-juk0et)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6345)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @piotmag769, and @RuneRogue)

___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 258 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6345#-O5tmSYX59KNCusc7B6m:-O5tmSYY1bZ29WMHeze0:b-r6ylkl) ([raw file](https://github.com/starkware-libs/cairo/blob/e625a5cd2d4b0c4941c591216fcf0f65977dd7d8/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L258)):*
> ```XML
> 
> /// Returns a completion item for a method.
> fn is_self_param(param: &Parameter) -> bool {
> ```

wrong doc. fix.
___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 259 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6345#-O5tmXmI5CY22wMQY953:-O5tmXmI5CY22wMQY954:bqen3t1) ([raw file](https://github.com/starkware-libs/cairo/blob/e625a5cd2d4b0c4941c591216fcf0f65977dd7d8/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L259)):*
> ```XML
> /// Returns a completion item for a method.
> fn is_self_param(param: &Parameter) -> bool {
>     param.name == "self" || param.name == "&self" || param.name == "&mut self"
> ```

these don't actually exist in cairo.



_Code quote:_
```XML
 || param.name == "&self" || param.name == "&mut self"
```

**Review by RuneRogue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6345)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 259 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6345#-O5tmXmI5CY22wMQY953:-O5uR0YVB45_LUd512De:btcdonf) ([raw file](https://github.com/starkware-libs/cairo/blob/e625a5cd2d4b0c4941c591216fcf0f65977dd7d8/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L259)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

these don't actually exist in cairo.
</blockquote></details>

What should I do? Remove that condition to check for self  ? Will they properly work for all type of function? Because Some function does not required to pass parameters value explicitly right?  We only have to add space for those function which required to give parameters value by user.

**Review by RuneRogue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6345)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 259 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6345#-O5tmXmI5CY22wMQY953:-O5uYHGTD0_A6Xu4xzra:btbrz5i) ([raw file](https://github.com/starkware-libs/cairo/blob/e625a5cd2d4b0c4941c591216fcf0f65977dd7d8/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L259)):*
<details><summary><i>Previously, RuneRogue (Priyank Makwana) wrote…</i></summary><blockquote>

What should I do? Remove that condition to check for self  ? Will they properly work for all type of function? Because Some function does not required to pass parameters value explicitly right?  We only have to add space for those function which required to give parameters value by user.
</blockquote></details>

For example is_zero() function from cairo library. 
We use it as 'value.is_zero() ' right? For that we don't have to pass parameters. 

But in library it is defined like this 

pub(crate) impl Felt252Zero of crate::num::traits::Zero<felt252> {
    fn zero() -> felt252 {
        0
    }

    #[inline]
    fn is_zero(self: @felt252) -> bool {
        *self == Self::zero()
    }

    #[inline]
    fn is_non_zero(self: @felt252) -> bool {
        !self.is_zero()
    }
}


So our code is interpret self : @felt252 as parameters and it add space between parentheses.

**Review by RuneRogue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6345)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 259 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6345#-O5tmXmI5CY22wMQY953:-O5ujGRm6lim3gv-IKyG:bpdj9nc) ([raw file](https://github.com/starkware-libs/cairo/blob/e625a5cd2d4b0c4941c591216fcf0f65977dd7d8/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L259)):*
<details><summary><i>Previously, RuneRogue (Priyank Makwana) wrote…</i></summary><blockquote>

For example is_zero() function from cairo library. 
We use it as 'value.is_zero() ' right? For that we don't have to pass parameters. 

But in library it is defined like this 

pub(crate) impl Felt252Zero of crate::num::traits::Zero<felt252> {
    fn zero() -> felt252 {
        0
    }

    #[inline]
    fn is_zero(self: @felt252) -> bool {
        *self == Self::zero()
    }

    #[inline]
    fn is_non_zero(self: @felt252) -> bool {
        !self.is_zero()
    }
}


So our code is interpret self : @felt252 as parameters and it add space between parentheses.
</blockquote></details>

So may be this will solve our problem

    if !signature.params.is_empty() && signature.params.iter().any(|param| param.name != "self") 

What do you think?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6345)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @piotmag769, and @RuneRogue)

___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 259 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6345#-O5tmXmI5CY22wMQY953:-O5vSCAHDjIO4--RBEeR:b-n153kp) ([raw file](https://github.com/starkware-libs/cairo/blob/e625a5cd2d4b0c4941c591216fcf0f65977dd7d8/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L259)):*
<details><summary><i>Previously, RuneRogue (Priyank Makwana) wrote…</i></summary><blockquote>

So may be this will solve our problem

    if !signature.params.is_empty() && signature.params.iter().any(|param| param.name != "self") 

What do you think?
</blockquote></details>

more like:
```
let is_method = signature.params.first().filter(|p|p.name == "self").is_some();
```

**Review by RuneRogue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6345)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 259 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6345#-O5tmXmI5CY22wMQY953:-O5viinR6vQdV_cSZoJE:b74z11k) ([raw file](https://github.com/starkware-libs/cairo/blob/e625a5cd2d4b0c4941c591216fcf0f65977dd7d8/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L259)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

more like:
```
let is_method = signature.params.first().filter(|p|p.name == "self").is_some();
```
</blockquote></details>

It's not giving output we want because in methods_text_edits.txt , you can for first test we have provided first parameter as self so in that space will not be added because we excluded function having first parameter as self   but it should have space between parentheses but it is having two parameters .

fn some_method(self: @felt252, param1: i32, param2: String) {}

**Review by RuneRogue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6345)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 259 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6345#-O5tmXmI5CY22wMQY953:-O5vkWIr-mMMEcCDgVDQ:b-skxedi) ([raw file](https://github.com/starkware-libs/cairo/blob/e625a5cd2d4b0c4941c591216fcf0f65977dd7d8/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L259)):*
<details><summary><i>Previously, RuneRogue (Priyank Makwana) wrote…</i></summary><blockquote>

It's not giving output we want because in methods_text_edits.txt , you can for first test we have provided first parameter as self so in that space will not be added because we excluded function having first parameter as self   but it should have space between parentheses but it is having two parameters .

fn some_method(self: @felt252, param1: i32, param2: String) {}
</blockquote></details>

I have updated code . it is providing the perfect output we want .

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6345)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

**Review by mkaput — COMMENTED** [review]
Hey! Could you please move your changes back to #6320? This will make us-as-reviewers' life so much easier because we'd like to have a diff what's changed between this and that PR. Thank you :pray: 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6345#-:-O5xfeZ58DH1L-fy2e3q:b-um3r4j)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @piotmag769)

**Review by RuneRogue — COMMENTED** [review]
I have reverted this PR as same old #6320 PR . I mean this PR contains test data that was different from the current main branch . And now #6320 contains all the latest updates . Now you can check #6320 for updates and #6345 for difference check .

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6345#-:-O5yKRN70PnFkuiFaHQ2:b-6d3rte)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @piotmag769)

**Review by mkaput — COMMENTED** [review]
Sorry, I do not understand what you're trying to do here :disappointed: Closing this PR, let's do everything in #6320 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6345#-:-O65HQAG1ZiFG6hde20W:b4ljtq6)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @piotmag769)

**Comment by RuneRogue** [comment]
I have made two different PR so you can differentiate the changes i have  nade. # 6320 is updated PR you can review it and tell me if there are any changes. This one was old code that is giving unexpected test data.
@mkaput

**Pull request closed without merging**
