### PR TITLE
Add missing trait quick fix.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
**Stack**:
- #6091
- #6060 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6060)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6060)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @ArielElp, @mkaput, and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6060#-O2VGJ7k9QKj6CQPKq5r:-O2VGJ7k9QKj6CQPKq5s:bh0gv9k) (no related file):*
Not sure how to trigger the quick fix from tests, will look it up and add tests.

___
___
*[`crates/cairo-lang-language-server/src/ide/utils.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6060#-O2VGUVQ9cIO9W1Wds03:-O2VGUVR6C6yN3g64MRa:bfk3s6u) ([raw file](https://github.com/starkware-libs/cairo/blob/44e8a32e54b34a85507ea09ec72c48c45fa82b5f/crates/cairo-lang-language-server/src/ide/utils.rs#L80)):*
> ```XML
>         return Some(true);
>     }
>     // TODO(Gil): Check if the trait is visible, and return the path of the visible use item.
> ```

The code in this file is moved from completions.rs except this todo.



_Code quote:_
```XML
 // TODO(Gil): Check if the trait is visible, and return the path of the visible use item.
```

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 6 of 10 files at r2, 2 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6060)* status: 9 of 14 files reviewed, 2 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/tests/e2e/code_actions.rs` line 15 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6060#-O2iy1SG68jZxAJ_oXJJ:-O2iy1SG68jZxAJ_oXJK:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/16d723cdb2d52341976e172dd24e3ff7a34264e8/crates/cairo-lang-language-server/tests/e2e/code_actions.rs#L15)):*
> ```XML
>     "tests/test_data/code_actions",
>     {
>         basic: "missing_trait.txt",
> ```





_Suggestion:_
```XML
missing_trait
```

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 8 of 10 files at r2, 2 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6060)* status: 12 of 14 files reviewed, 2 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6060#-O2VGJ7k9QKj6CQPKq5r:-O2dPcpBA5ySZQlBKfv5:b8kcxco) (no related file):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Not sure how to trigger the quick fix from tests, will look it up and add tests.
</blockquote></details>

My guess is that you need to extend the base client capabilities for tests and use `MockClient::send_request("textDocument/codeAction")`

___
___
*[`crates/cairo-lang-language-server/src/ide/utils.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6060#-O2VGUVQ9cIO9W1Wds03:-O2eGQ3u6xhYiBp6LqG9:b-3r3j2n) ([raw file](https://github.com/starkware-libs/cairo/blob/44e8a32e54b34a85507ea09ec72c48c45fa82b5f/crates/cairo-lang-language-server/src/ide/utils.rs#L80)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

The code in this file is moved from completions.rs except this todo.
</blockquote></details>

So for now we are fine with the quick fix potentially not fixing (for edition >= `2023_11`), do I get it right?
___
*[`crates/cairo-lang-language-server/src/ide/code_actions/add_missing_trait.rs` line 35 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6060#-O2jr9RE0E2tY8Y78ReH:-O2jr9RF36RrmkaUyCzf:b-iq76lc) ([raw file](https://github.com/starkware-libs/cairo/blob/16d723cdb2d52341976e172dd24e3ff7a34264e8/crates/cairo-lang-language-server/src/ide/code_actions/add_missing_trait.rs#L35)):*
> ```XML
> /// Returns a list of code actions to add missing traits to the current module, or `None` if the
> /// type is missing.
> fn missing_traits_actions(
> ```

Looks good, but prob worth to rereview by someone more knowledgable about the compiler

**Review by piotmag769 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6060#-:-O2jtB_19NnvjJ-xIUjU:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, and @orizi)

___
*[`crates/cairo-lang-language-server/tests/e2e/code_actions.rs` line 111 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6060#-O2jufC936CuwKIO25or:-O2jufC936CuwKIO25os:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/16d723cdb2d52341976e172dd24e3ff7a34264e8/crates/cairo-lang-language-server/tests/e2e/code_actions.rs#L111)):*
> ```XML
>                 for edit in edits {
>                     result.push_str(&format!(
>                         "Add new text: \"{}\"\nAt: {:?}",
> ```





_Suggestion:_
```XML
                        "Add new text: \"{}\"\nAt: {:?}\n",
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6060)* status: 12 of 14 files reviewed, 3 unresolved discussions (waiting on @ArielElp, @mkaput, @orizi, and @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6060#-O2VGJ7k9QKj6CQPKq5r:-O2s7C30A-DovcKntHhg:bmt5den) (no related file):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

My guess is that you need to extend the base client capabilities for tests and use `MockClient::send_request("textDocument/codeAction")`
</blockquote></details>

Yes, already figured it out and added tests.

___
___
*[`crates/cairo-lang-language-server/src/ide/utils.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6060#-O2VGUVQ9cIO9W1Wds03:-O2s7lb-CyNV2T9dfCOM:bcyqr5w) ([raw file](https://github.com/starkware-libs/cairo/blob/44e8a32e54b34a85507ea09ec72c48c45fa82b5f/crates/cairo-lang-language-server/src/ide/utils.rs#L80)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

So for now we are fine with the quick fix potentially not fixing (for edition >= `2023_11`), do I get it right?
</blockquote></details>

Yes, at least it tells the user what trait he should add.
___
*[`crates/cairo-lang-language-server/src/ide/code_actions/add_missing_trait.rs` line 35 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6060#-O2jr9RE0E2tY8Y78ReH:-O2s7ts2AAZTwRPDB17E:bytrzk6) ([raw file](https://github.com/starkware-libs/cairo/blob/16d723cdb2d52341976e172dd24e3ff7a34264e8/crates/cairo-lang-language-server/src/ide/code_actions/add_missing_trait.rs#L35)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Looks good, but prob worth to rereview by someone more knowledgable about the compiler
</blockquote></details>

@orizi 
___
*[`crates/cairo-lang-language-server/tests/e2e/code_actions.rs` line 15 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6060#-O2iy1SG68jZxAJ_oXJJ:-O2s8QIo8eGkU6VcDNL1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/16d723cdb2d52341976e172dd24e3ff7a34264e8/crates/cairo-lang-language-server/tests/e2e/code_actions.rs#L15)):*
> ```XML
>     "tests/test_data/code_actions",
>     {
>         basic: "missing_trait.txt",
> ```

Done.
___
*[`crates/cairo-lang-language-server/tests/e2e/code_actions.rs` line 111 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6060#-O2jufC936CuwKIO25or:-O2s8QdL7rfncMCb2mUV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/16d723cdb2d52341976e172dd24e3ff7a34264e8/crates/cairo-lang-language-server/tests/e2e/code_actions.rs#L111)):*
> ```XML
>                 for edit in edits {
>                     result.push_str(&format!(
>                         "Add new text: \"{}\"\nAt: {:?}",
> ```

Done.

**Review by piotmag769 — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6060)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp, @mkaput, and @orizi)

**Review by gilbens-starkware — COMMENTED** [review]
Fixed the trait visibility issue.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6060#-:-O3-NIrq6VHa0bwbwyUt:b-rdb2un)* status: 12 of 17 files reviewed, 1 unresolved discussion (waiting on @ArielElp, @mkaput, @orizi, and @piotmag769)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r1, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6060#-:-O31m2Up1z01XOD3WH3s:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp and @mkaput)

**Review by piotmag769 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6060)* status: all files reviewed, 2 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, and @mkaput)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 1499 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6060#-O31t9yJ16JhZRH2l8OW:-O31t9yJ16JhZRH2l8OX:bsrr1ge) ([raw file](https://github.com/starkware-libs/cairo/blob/a4b9408f93fd421ee5734ebc84ce267768e80a63/crates/cairo-lang-semantic/src/db.rs#L1499)):*
> ```XML
>     /// `include_parent` is true, the parent module of `module_id` is also considered.
>     #[salsa::invoke(lsp_helpers::visible_traits_in_module)]
>     fn visible_traits_in_module(
> ```

Something gone wrong while rebasing (should be in the other PR)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6060)* status: all files reviewed, 2 unresolved discussions (waiting on @ArielElp, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 1499 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6060#-O31t9yJ16JhZRH2l8OW:-O32FcP79-C_d5yuqOaH:beehm7i) ([raw file](https://github.com/starkware-libs/cairo/blob/a4b9408f93fd421ee5734ebc84ce267768e80a63/crates/cairo-lang-semantic/src/db.rs#L1499)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Something gone wrong while rebasing (should be in the other PR)
</blockquote></details>

No, that's intentional, fixing the non-visible traits import. It affected both the import from quick fix (fixed here) and the import from completions (fixed in the other PR).

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 4 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6060)* status: all files reviewed, 2 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, and @mkaput)

___
*[`crates/cairo-lang-language-server/tests/test_data/code_actions/missing_trait.txt` line 140 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6060#-O33pWMc0XDRMSOkXBlE:-O33pWMc0XDRMSOkXBlF:b-pz7vx6) ([raw file](https://github.com/starkware-libs/cairo/blob/a4b9408f93fd421ee5734ebc84ce267768e80a63/crates/cairo-lang-language-server/tests/test_data/code_actions/missing_trait.txt#L140)):*
> ```help
> mod hidden_trait {
> 
>     trait ATrait1<T> {
> ```

The trait itself isn't visible though, am I right? So it actually suggests an import that is not working. Don't see this as a big deal since the `use` will be highlighted as incorrect.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6060)* status: all files reviewed, 2 unresolved discussions (waiting on @ArielElp, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-language-server/tests/test_data/code_actions/missing_trait.txt` line 140 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6060#-O33pWMc0XDRMSOkXBlE:-O362vk90fIUHfU-VsjW:b-ae5u71) ([raw file](https://github.com/starkware-libs/cairo/blob/a4b9408f93fd421ee5734ebc84ce267768e80a63/crates/cairo-lang-language-server/tests/test_data/code_actions/missing_trait.txt#L140)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

The trait itself isn't visible though, am I right? So it actually suggests an import that is not working. Don't see this as a big deal since the `use` will be highlighted as incorrect.
</blockquote></details>

Yes, you are write, the use will be highlighted, and in the context of `inner_mod` we don't know about it. But that wasn't the test I intended to write, fixed it.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6060#-:-O36jivl94C8_gHvdxDB:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ArielElp, @mkaput, and @piotmag769)

**Review by mkaput — APPROVED** [review]
I haven't reviewed this fully yet. :lgtm: to unblock but will review soon and please address in another PR

> Reviewed 1 of 6 files at r1, 1 of 10 files at r2, 1 of 2 files at r5, 3 of 5 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6060#-:-O36ltliB08YaFsVZP8b:b-xn7ua)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp and @piotmag769)

**Review by piotmag769 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6060#-:-O36tPFsA6hSiY5dLr7C:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArielElp)

**Pull request merged**
