### PR TITLE
Add Generated destructors.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6219)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/test_data/closure` line 110 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6219#-O4ZQq2j7lJTzk-NO9Kk:-O4ZQq2j7lJTzk-NO9Kl:bxbzth7) ([raw file](https://github.com/starkware-libs/cairo/blob/460e69f690f247e49b3610ab9330f4bfa3e264b0/crates/cairo-lang-lowering/src/lower/test_data/closure#L110)):*
> ```
>     ^**^
> note: Trait has no implementation in context: core::traits::Drop::<test::PanicDestructable>.
> note: Trait has no implementation in context: core::traits::Destruct::<test::PanicDestructable>.
> ```

Still checking where this is coming from.



_Code quote:_
```
error: Variable not dropped.
 --> lib.cairo:10:5
    || {
    ^**^
note: Trait has no implementation in context: core::traits::Drop::<test::PanicDestructable>.
note: Trait has no implementation in context: core::traits::Destruct::<test::PanicDestructable>.
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6219)* status: 2 of 8 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/block_builder.rs` line 394 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6219#-O4ZRBJnEhYvyjqXo8IK:-O4ZRBJnEhYvyjqXo8IL:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/460e69f690f247e49b3610ab9330f4bfa3e264b0/crates/cairo-lang-lowering/src/lower/block_builder.rs#L394)):*
> ```XML
>     }
> 
>     pub fn destructure_closure(
> ```

doc
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1682 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6219#-O4ZRYWX4R0K2gUNu5dz:-O4ZRYWYAtJUtE6FPNBd:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/460e69f690f247e49b3610ab9330f4bfa3e264b0/crates/cairo-lang-lowering/src/lower/mod.rs#L1682)):*
> ```XML
> }
> 
> fn add_capture_destruct_impl(
> ```

doc
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1694 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6219#-O4ZRnmu9SJ2MNRuT1jo:-O4ZRnmu9SJ2MNRuT1jp:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/460e69f690f247e49b3610ab9330f4bfa3e264b0/crates/cairo-lang-lowering/src/lower/mod.rs#L1694)):*
> ```XML
>     else {
>         return Ok(());
>     };
> ```





_Suggestion:_
```XML
    let capture_var = &ctx.variables.variables[capture_var_usage.var_id];
    // Skipping generation for the case of `Drop`.
    let Some(Ok(impl_id)) = [&capture_var.destruct_impl, &capture_var.panic_destruct_impl]
        .iter()
        .find(|infer_result| infer_result.is_ok())
    else {
        return Ok(());
    };
```
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1732 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6219#-O4ZRadf9ynLIErd1zcZ:-O4ZRadg21bt2xRTPZH3:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/460e69f690f247e49b3610ab9330f4bfa3e264b0/crates/cairo-lang-lowering/src/lower/mod.rs#L1732)):*
> ```XML
> }
> 
> fn get_destruct_lowering(
> ```

doc
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1757 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6219#-O4ZSb6C16SdtTLhmf6s:-O4ZSb6C16SdtTLhmf6t:b-cgnwc1) ([raw file](https://github.com/starkware-libs/cairo/blob/460e69f690f247e49b3610ab9330f4bfa3e264b0/crates/cairo-lang-lowering/src/lower/mod.rs#L1757)):*
> ```XML
>         ty: unit_ty(ctx.db.upcast()),
>         location: location_id,
>     }
> ```

this is just the setup of the returned unit type?



_Code quote:_
```XML
    let var_usage = generators::StructConstruct {
        inputs: vec![],
        ty: unit_ty(ctx.db.upcast()),
        location: location_id,
    }
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1757 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6219#-O4ZSb6C16SdtTLhmf6s:-O4ZWx_O44wMW9ii0AgT:b2nign6) ([raw file](https://github.com/starkware-libs/cairo/blob/460e69f690f247e49b3610ab9330f4bfa3e264b0/crates/cairo-lang-lowering/src/lower/mod.rs#L1757)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is just the setup of the returned unit type?
</blockquote></details>

yes

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6219)* status: 1 of 9 files reviewed, 5 unresolved discussions (waiting on @orizi and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/block_builder.rs` line 394 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6219#-O4ZRBJnEhYvyjqXo8IK:-O4ZZ5Ls315UXa_sj3zn:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/460e69f690f247e49b3610ab9330f4bfa3e264b0/crates/cairo-lang-lowering/src/lower/block_builder.rs#L394)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1682 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6219#-O4ZRYWX4R0K2gUNu5dz:-O4ZWlgi3mNNRPhz4RmZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/460e69f690f247e49b3610ab9330f4bfa3e264b0/crates/cairo-lang-lowering/src/lower/mod.rs#L1682)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1694 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6219#-O4ZRnmu9SJ2MNRuT1jo:-O4ZWd-z39OfNayBekGS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/460e69f690f247e49b3610ab9330f4bfa3e264b0/crates/cairo-lang-lowering/src/lower/mod.rs#L1694)):*
> ```XML
>     else {
>         return Ok(());
>     };
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1732 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6219#-O4ZRadf9ynLIErd1zcZ:-O4ZWun68IMDw44rxBh0:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/460e69f690f247e49b3610ab9330f4bfa3e264b0/crates/cairo-lang-lowering/src/lower/mod.rs#L1732)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r1, 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6219)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/test_data/closure` line 95 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6219#-O4ZZg4hDjkEEipQUfU6:-O4ZZg4i2Q2xPgm0zRzE:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/142be8964eae40f01c74398f6e19e48aebb50997/crates/cairo-lang-lowering/src/lower/test_data/closure#L95)):*
> ```
>         let PanicDestructable { } = self;
>     }
> }
> ```





_Suggestion:_
```
impl PanicDestructForDestruct of PanicDestruct<PanicDestructable> {
    fn panic_destruct(self: PanicDestructable, ref panic: Panic) nopanic {
        let PanicDestructable { } = self;
    }
}
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6219)* status: 6 of 9 files reviewed, 1 unresolved discussion (waiting on @orizi and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/test_data/closure` line 95 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6219#-O4ZZg4hDjkEEipQUfU6:-O4Z_RBZ3EEcgTyY4J6G:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/142be8964eae40f01c74398f6e19e48aebb50997/crates/cairo-lang-lowering/src/lower/test_data/closure#L95)):*
> ```
>         let PanicDestructable { } = self;
>     }
> }
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, 1 of 4 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6219)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/test_data/closure` line 110 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6219#-O4ZQq2j7lJTzk-NO9Kk:-O4ZgxJc5tCs2TnDv6i_:bmqlmng) ([raw file](https://github.com/starkware-libs/cairo/blob/460e69f690f247e49b3610ab9330f4bfa3e264b0/crates/cairo-lang-lowering/src/lower/test_data/closure#L110)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Still checking where this is coming from.
</blockquote></details>

any thoughts?
___
*[`crates/cairo-lang-lowering/src/lower/test_data/closure` line 95 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6219#-O4ZZg4hDjkEEipQUfU6:-O4ZguAU279XMByz8J7r:b-lkx7gw) ([raw file](https://github.com/starkware-libs/cairo/blob/142be8964eae40f01c74398f6e19e48aebb50997/crates/cairo-lang-lowering/src/lower/test_data/closure#L95)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

probably not pushed.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/test_data/closure` line 110 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6219#-O4ZQq2j7lJTzk-NO9Kk:-O4ZldkP0Gc1EBBTAXXS:bptdudv) ([raw file](https://github.com/starkware-libs/cairo/blob/460e69f690f247e49b3610ab9330f4bfa3e264b0/crates/cairo-lang-lowering/src/lower/test_data/closure#L110)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

any thoughts?
</blockquote></details>

It comes from the borrower checker.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/test_data/closure` line 110 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6219#-O4ZQq2j7lJTzk-NO9Kk:-O4Zm29w6gebSzgoV58k:b-6dxb8q) ([raw file](https://github.com/starkware-libs/cairo/blob/460e69f690f247e49b3610ab9330f4bfa3e264b0/crates/cairo-lang-lowering/src/lower/test_data/closure#L110)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

It comes from the borrower checker.
</blockquote></details>

https://reviewable.io/reviews/starkware-libs/cairo/6220

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6219)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @TomerStarkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6219#-:-O4ZmGBw8yw850tPDS4_:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @TomerStarkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6219)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @orizi and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/test_data/closure` line 95 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6219#-O4ZZg4hDjkEEipQUfU6:-O4Zm_iw26vSr5_5qL_4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/142be8964eae40f01c74398f6e19e48aebb50997/crates/cairo-lang-lowering/src/lower/test_data/closure#L95)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

probably not pushed.
</blockquote></details>

Done.

**Pull request merged**
