### PR TITLE
Made version a part of crate ids.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6406)

### CODE REVIEW

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6406#-:-O7U2QK98yMtV7VjRMv-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

**Review by Arcticae — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6406)* status: 10 of 13 files reviewed, 1 unresolved discussion (waiting on @Draggu, @gilbens-starkware, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-compiler/src/project.rs` line 142 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6406#-O7UCx1n0_WmigrHn9kX:-O7UCx1n0_WmigrHn9kY:b-pq59td) ([raw file](https://github.com/starkware-libs/cairo/blob/8fe0913ecec2498d5f41a22f15c0c3307cc09d27/crates/cairo-lang-compiler/src/project.rs#L142)):*
> ```XML
>             let crate_settings = config.content.crates_config.get(&name);
>             let version =
>                 if name == CORELIB_CRATE_NAME { None } else { crate_settings.version.clone() };
> ```

Isn't the corelib version fixed for a given compiler release?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6406)* status: 10 of 13 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-compiler/src/project.rs` line 142 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6406#-O7UCx1n0_WmigrHn9kX:-O7UWkNE9d7SM514vdCx:brep7rb) ([raw file](https://github.com/starkware-libs/cairo/blob/8fe0913ecec2498d5f41a22f15c0c3307cc09d27/crates/cairo-lang-compiler/src/project.rs#L142)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

Isn't the corelib version fixed for a given compiler release?
</blockquote></details>

it is - but it is set up for many different places.
also - it would probably break our codelib validity validation if we add a version to it.

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6406)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

**Review by Arcticae — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6406#-:-O81T05K1g0-YcO8wcQW:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Draggu, @mkaput, and @piotmag769)

**Review by piotmag769 — APPROVED** [review]
:lgtm:

> Reviewed 10 of 13 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6406#-:-O82zquw7CqnNR7rABzJ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Draggu and @mkaput)

**Pull request merged**
