### PR TITLE
feat: Make Serde non-owning

### LINKED ISSUE #2955: feat: Make Serde non-owning
Change the Serde trait, and make serialize() has this signature:
```
fn serialize(self:@T, ref output: Array<felt252>);
```
instead of 
```
fn serialize(ref output: Array<felt252>, input: T);
```

This has 2 outcomes:
* serialize needs only the non-owning verison `@T`.
* serialize cna be used as a method on T.

change it in traits.cairo, and fix everything that fails.

### PR DESCRIPTION
**Pull request by wraitii**
Fix #2955 

Change the `Serde` trait's `serialize` to be a non-owning method.

Some details:
- Cairo corelib was updated to use `.serialize` as a method for cleaner code, this required some `use serde::Serde`
- rust plugins were updated, but were kept as free functions. Otherwise, one has to `use serde::Serde` somewhere which seems like it would lead to trouble. In particular, `use` can't be used in `impl`.
- I haven't really changed `block_generator_test_data/serialization`, under the assumption that this would keep the test more valid.
- There is a bug in user_defined_types's `TestContract` following #2845 , this PR fixes it.

As a final note, I am wondering if the method should be renamed to `serialize_into` maybe ?

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2961)

### CODE REVIEW

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 35 of 35 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2961#-:-NU6O3LC9j-AZd-vyfXS:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @wraitii)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo` line 188 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2961#-NU6NlzZ4bTGKMaXw_tV:-NU6NlzZ4bTGKMaXw_tW:bn0aqo8) ([raw file](https://github.com/starkware-libs/cairo/blob/08feb5afd3d003671ed867f1e7672cc05f480e47/crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo#L188)):*
> ```Cairo
> fn write_read_large_value() {
>     let mut args = ArrayTrait::new();
>     serde::Serde::serialize(u256 { low: 1_u128, high: 2_u128 }, ref args);
> ```

Shouldn't this be snapshotted?

**Review by wraitii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2961)* status: 31 of 36 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo` line 188 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2961#-NU6NlzZ4bTGKMaXw_tV:-NU6qncqAV1AM81UUELO:b-q21kcj) ([raw file](https://github.com/starkware-libs/cairo/blob/08feb5afd3d003671ed867f1e7672cc05f480e47/crates/cairo-lang-starknet/cairo_level_tests/contract_tests.cairo#L188)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Shouldn't this be snapshotted?
</blockquote></details>

It should, in fact this whole cairo-test file contained some errors as I hadn't noticed `scripts/starknet_test.sh`.
I've fixed them.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2961)* status: all files reviewed, 2 unresolved discussions (waiting on @wraitii)

___
*[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 269 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2961#-NU7ASLQDRtZFICKTZ1N:-NU7ASLQDRtZFICKTZ1O:bz28438) ([raw file](https://github.com/starkware-libs/cairo/blob/623a5c0fb2a3f9a1bfd2c0c6026927a47d34cc28/crates/cairo-lang-plugins/src/plugins/derive.rs#L269)):*
> ```XML
>                     impl {name}Serde of serde::Serde::<{name}> {{
>                         fn serialize(self: @{name}, ref output: array::Array<felt252>) {{
>                             match *self {{
> ```

Don't use desnap here. It requires the enum to implement Copy.
You can match on self - a snapshot of an enum. You get the snapshot of the variant at each btsnch
___
*[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 284 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2961#-NU7B1E90_M-GNWAdTfm:-NU7B1EAE2gl2Tcpw9Sl:b-bwq5zf) ([raw file](https://github.com/starkware-libs/cairo/blob/623a5c0fb2a3f9a1bfd2c0c6026927a47d34cc28/crates/cairo-lang-plugins/src/plugins/derive.rs#L284)):*
> ```XML
>                 variants.iter().enumerate().map(|(idx, variant)| {
>                     format!(
>                         "{name}::{variant}(x) => serde::Serde::serialize(@({idx}, x), ref output),",
> ```

And then u can remove the snapshot operator here

**Review by wraitii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2961)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 269 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2961#-NU7ASLQDRtZFICKTZ1N:-NU7Ho154evky0EBmYbO:b-9w9hhs) ([raw file](https://github.com/starkware-libs/cairo/blob/623a5c0fb2a3f9a1bfd2c0c6026927a47d34cc28/crates/cairo-lang-plugins/src/plugins/derive.rs#L269)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Don't use desnap here. It requires the enum to implement Copy.
You can match on self - a snapshot of an enum. You get the snapshot of the variant at each btsnch
</blockquote></details>

See below, but makes sense to me.
___
*[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 284 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2961#-NU7B1E90_M-GNWAdTfm:-NU7Hr3S02floQ2iweUb:b-5x2lq5) ([raw file](https://github.com/starkware-libs/cairo/blob/623a5c0fb2a3f9a1bfd2c0c6026927a47d34cc28/crates/cairo-lang-plugins/src/plugins/derive.rs#L284)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

And then u can remove the snapshot operator here 
</blockquote></details>

I'm having trouble getting that to work. If I just remove the snapshot operator in `match self` earlier, then I get the error below.
I tried adding or removing snapshots, but nothing seems to really work, and I get other errors.
The 3rd snippet in particular seems like it should work ? 



_Code snippet (i):_
```XML
error: Trait has no implementation in context: core::serde::Serde::<(?1, @())>
 --> impls:6:49
            EnumForSerde::A(x) => serde::Serde::serialize(@(0, x), ref output),
```



_Code snippet (ii):_
```XML
error: Unexpected argument type. Expected: "@?0", found: "(?1, @())".
 --> impls:6:59
            EnumForSerde::A(x) => serde::Serde::serialize((0, x), ref output),
```



_Code snippet (iii):_
```XML
error: Trait has no implementation in context: core::serde::Serde::<(@?1, @())>
 --> impls:6:49
            EnumForSerde::A(x) => serde::Serde::serialize(@(@0, x), ref output),
                                                ^*******^
```

**Review by wraitii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2961)* status: 34 of 36 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 284 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2961#-NU7B1E90_M-GNWAdTfm:-NUB-Kx-53oXbzNx727A:bquq12q) ([raw file](https://github.com/starkware-libs/cairo/blob/623a5c0fb2a3f9a1bfd2c0c6026927a47d34cc28/crates/cairo-lang-plugins/src/plugins/derive.rs#L284)):*
<details><summary><i>Previously, wraitii (Lancelot de Ferrière) wrote…</i></summary><blockquote>

I'm having trouble getting that to work. If I just remove the snapshot operator in `match self` earlier, then I get the error below.
I tried adding or removing snapshots, but nothing seems to really work, and I get other errors.
The 3rd snippet in particular seems like it should work ? 
</blockquote></details>

Updated on the latest draft, I now store the index first, then store the value separately (seems perhaps neater anyways?)

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2961)* status: 34 of 36 files reviewed, 1 unresolved discussion (waiting on @wraitii)

___
*[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 284 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2961#-NU7B1E90_M-GNWAdTfm:-NUBvf475CdI6ORsg_nw:b-msjbb7) ([raw file](https://github.com/starkware-libs/cairo/blob/623a5c0fb2a3f9a1bfd2c0c6026927a47d34cc28/crates/cairo-lang-plugins/src/plugins/derive.rs#L284)):*
<details><summary><i>Previously, wraitii (Lancelot de Ferrière) wrote…</i></summary><blockquote>

Updated on the latest draft, I now store the index first, then store the value separately (seems perhaps neater anyways?)
</blockquote></details>

The current code looks like an infinite loop. You are serializing self. Am I missing something?
Can you add a test that actually serialized an enum with derive?

**Review by wraitii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2961)* status: 34 of 36 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 284 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2961#-NU7B1E90_M-GNWAdTfm:-NUC6xVQ4jgBGubp92Px:biw4e2z) ([raw file](https://github.com/starkware-libs/cairo/blob/623a5c0fb2a3f9a1bfd2c0c6026927a47d34cc28/crates/cairo-lang-plugins/src/plugins/derive.rs#L284)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

The current code looks like an infinite loop. You are serializing self. Am I missing something?
Can you add a test that actually serialized an enum with derive?
</blockquote></details>

Err no you're correct, I wrote the right thing initially and then forgot that `x` isn't the same fix in both cases so I merged them incorrectly.
Should now work correctly.

Do you mean a cairo-test ? There is already a derive test (TwoVariantEnum) in `derive`

**Comment by spapinistarkware** [comment]
> > _[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2961)_ status: 34 of 36 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)
> 
> _[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 284 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2961#-NU7B1E90_M-GNWAdTfm:-NUC6xVQ4jgBGubp92Px:biw4e2z) ([raw file](https://github.com/starkware-libs/cairo/blob/623a5c0fb2a3f9a1bfd2c0c6026927a47d34cc28/crates/cairo-lang-plugins/src/plugins/derive.rs#L284)):_
> 
> Previously, spapinistarkware (Shahar Papini) wrote…
> Err no you're correct, I wrote the right thing initially and then forgot that `x` isn't the same fix in both cases so I merged them incorrectly. Should now work correctly.
> 
> Do you mean a cairo-test ? There is already a derive test (TwoVariantEnum) in `derive`

How did the test not catch the mistake?

**Review by wraitii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2961)* status: 34 of 36 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 284 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2961#-NU7B1E90_M-GNWAdTfm:-NUCBS8bBdg-twEduERV:bet2ku5) ([raw file](https://github.com/starkware-libs/cairo/blob/623a5c0fb2a3f9a1bfd2c0c6026927a47d34cc28/crates/cairo-lang-plugins/src/plugins/derive.rs#L284)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

How did the test not catch the mistake?
</blockquote></details>

The `derive` tests only check the expansion of the code is 'as expected' - and I had manually changed it to look like what it was indeed doing, since I didn't notice the mistake in the expanded code either.
As far as I can tell they don't try to compile or actually run the code, hence why I'm asking about cairo-level-tests

**Comment by spapinistarkware** [comment]
> > _[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2961)_ status: 34 of 36 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)
> 
> _[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 284 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2961#-NU7B1E90_M-GNWAdTfm:-NUCBS8bBdg-twEduERV:bet2ku5) ([raw file](https://github.com/starkware-libs/cairo/blob/623a5c0fb2a3f9a1bfd2c0c6026927a47d34cc28/crates/cairo-lang-plugins/src/plugins/derive.rs#L284)):_
> 
> Previously, spapinistarkware (Shahar Papini) wrote…
> The `derive` tests only check the expansion of the code is 'as expected' - and I had manually changed it to look like what it was indeed doing, since I didn't notice the mistake in the expanded code either. As far as I can tell they don't try to compile or actually run the code, hence why I'm asking about cairo-level-tests

Gotcha, so please add a cairo level test with the issue number under bug_samples :) you can serialize and deserialize.

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2961)* status: all files reviewed, 1 unresolved discussion (waiting on @wraitii)

**Comment by wraitii** [comment]
Had to rebase on top of #2938 as I had to explicit which casting I wanted in `corelibe/serde.cairo`

Added a test for a simple struct / enum serialisation. I checked that it failed with the infinite loop version (it did), and now works.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2961#-:-NUH9tXQ97mOmyTZwK6f:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @wraitii)

___
*[`corelib/src/serde.cairo` line 62 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2961#-NUH9j3c11U2HTm3c4Wh:-NUH9j3c11U2HTm3c4Wi:b-9m795q) ([raw file](https://github.com/starkware-libs/cairo/blob/a3fd197f18c1bc375ba8559cc8251d7ee7951aa6/corelib/src/serde.cairo#L62)):*
> ```Cairo
> impl U64Serde of Serde<u64> {
>     fn serialize(self: @u64, ref output: Array<felt252>) {
>         Into::<u64, felt252>::into(*self).serialize(ref output);
> ```

Is this required, or did u just add for explicitness (which I agree with)?

**Review by wraitii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2961)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`corelib/src/serde.cairo` line 62 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2961#-NUH9j3c11U2HTm3c4Wh:-NUHA2Lg185HMBOTziWM:b-iud86j) ([raw file](https://github.com/starkware-libs/cairo/blob/a3fd197f18c1bc375ba8559cc8251d7ee7951aa6/corelib/src/serde.cairo#L62)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Is this required, or did u just add for explicitness (which I agree with)?
</blockquote></details>

It is required, the type system doesn't seem clever enough to understand that we want this variant of 'into', I guess because there is also into<u64, u128> since the Integer-casting PR.

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2961)* status: all files reviewed, 1 unresolved discussion (waiting on @wraitii)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2961#-:-NUHWUXa4S2n-WQv6pQj:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @wraitii)

**Review by wraitii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2961)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-plugins/src/plugins/derive.rs` line 284 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2961#-NU7B1E90_M-GNWAdTfm:-NUHQv6tBoKZ7KO5NwYv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/623a5c0fb2a3f9a1bfd2c0c6026927a47d34cc28/crates/cairo-lang-plugins/src/plugins/derive.rs#L284)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Gotcha, so please add a cairo level test with the issue number under bug_samples :) you can serialize and deserialize.
</blockquote></details>

Done.

**Pull request merged**
