### PR TITLE
Separate gas solving

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1880)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1880)* status: 2 of 10 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1880#-NMYdKNf431GV9qhC603:-NMYdKNf431GV9qhC604:b-sgutay) ([raw file](https://github.com/starkware-libs/cairo/blob/ff0101ea2043add26c585453c7c4b606ac482c51/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L56)):*
> ```XML
> }
> 
> /// Returns some cost value for a libfunc - a helper function to implement costing both for creating
> ```

update doc



_Code quote:_
```XML
/// Returns some cost value for a libfunc - a helper function to implement costing both for creating
/// gas equations and getting actual gas usage after having a solution.
```
___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1880#-NMYdMA548T0TnKVSnYo:-NMYdMA548T0TnKVSnYp:bq8sxan) ([raw file](https://github.com/starkware-libs/cairo/blob/ff0101ea2043add26c585453c7c4b606ac482c51/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L94)):*
> ```XML
>     }
> }
> /// Returns some cost value for a libfunc - a helper function to implement costing both for creating
> ```

and update doc



_Suggestion:_
```XML
}

/// Returns some cost value for a libfunc - a helper function to implement costing both for creating
/// gas equations and getting actual gas usage after having a solution.
```
___
*[`crates/cairo-lang-sierra-gas/src/gas_info.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1880#-NMYdapt6isx5UnnFALs:-NMYdapt6isx5UnnFALt:bo4vv8q) ([raw file](https://github.com/starkware-libs/cairo/blob/ff0101ea2043add26c585453c7c4b606ac482c51/crates/cairo-lang-sierra-gas/src/gas_info.rs#L19)):*
> ```XML
> impl GasInfo {
>     pub fn add(mut self, mut other: GasInfo) -> GasInfo {
>         let variable_values = chain!(self.variable_values.keys(), other.variable_values.keys())
> ```

look at the add_map util.



_Code quote:_
```XML
    pub fn add(mut self, mut other: GasInfo) -> GasInfo {
        let variable_values = chain!(self.variable_values.keys(), other.variable_values.keys())
```

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1880)* status: 2 of 10 files reviewed, 6 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1880#-NMYdmj17lNmjBKkrFoW:-NMYdmj17lNmjBKkrFoX:b-jlmcj6) ([raw file](https://github.com/starkware-libs/cairo/blob/ff0101ea2043add26c585453c7c4b606ac482c51/crates/cairo-lang-sierra-gas/src/lib.rs#L48)):*
> ```XML
> }
> 
> /// Calculates gas information for a given program.
> ```

update



_Code quote:_
```XML
/// Calculates gas information for a given program.
```
___
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1880#-NMYdniC9RGjnBW2lzM-:-NMYdniC9RGjnBW2lzM0:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/ff0101ea2043add26c585453c7c4b606ac482c51/crates/cairo-lang-sierra-gas/src/lib.rs#L72)):*
> ```XML
> }
> 
> pub fn calc_gas_postcost_info(
> ```

doc



_Code quote:_
```XML
pub fn calc_gas_postcost_info(
```
___
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1880#-NMYdp1m5kt3XznRaq-J:-NMYdp1m5kt3XznRaq-K:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/ff0101ea2043add26c585453c7c4b606ac482c51/crates/cairo-lang-sierra-gas/src/lib.rs#L95)):*
> ```XML
> }
> 
> fn calc_gas_info_inner<
> ```

doc



_Code quote:_
```XML
fn calc_gas_info_inner<
```

**Review by orizi — COMMENTED** [review]
> Reviewed 6 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1880)* status: 9 of 10 files reviewed, 6 unresolved discussions (waiting on @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1880)* status: all files reviewed, 6 unresolved discussions (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1880)* status: 7 of 10 files reviewed, 6 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1880#-NMYdKNf431GV9qhC603:-NMYgyjMEmLlJfcScIqE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ff0101ea2043add26c585453c7c4b606ac482c51/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L56)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

update doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1880#-NMYdMA548T0TnKVSnYo:-NMYgzT2CjFfBgAETS0i:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ff0101ea2043add26c585453c7c4b606ac482c51/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L94)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

and update doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-gas/src/gas_info.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1880#-NMYdapt6isx5UnnFALs:-NMYhNh-1oAb7Ry48nVP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ff0101ea2043add26c585453c7c4b606ac482c51/crates/cairo-lang-sierra-gas/src/gas_info.rs#L19)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

look at the add_map util.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1880#-NMYdmj17lNmjBKkrFoW:-NMYhX2_69viG2z5_p8z:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ff0101ea2043add26c585453c7c4b606ac482c51/crates/cairo-lang-sierra-gas/src/lib.rs#L48)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

update
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1880#-NMYdniC9RGjnBW2lzM-:-NMYhXJn90W0QxGPPWaH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ff0101ea2043add26c585453c7c4b606ac482c51/crates/cairo-lang-sierra-gas/src/lib.rs#L72)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-gas/src/lib.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1880#-NMYdp1m5kt3XznRaq-J:-NMYheS53MGmi_AUHtAf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ff0101ea2043add26c585453c7c4b606ac482c51/crates/cairo-lang-sierra-gas/src/lib.rs#L95)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1880#-:-NMYj2qGA61NnucPfYFg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 3 of 10 files at r1, 1 of 3 files at r3, 2 of 3 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1880)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — COMMENTED** [review]
> Reviewed 2 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1880)* status: all files reviewed, 4 unresolved discussions

___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 41 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1880#-NMZ8Sfo82G51SZC2p-G:-NMZ8Sfo82G51SZC2p-H:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/4c02ffa012001e5fd0860e5f0a14fc99abf081b8/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L41)):*
> ```XML
>     fn const_cost_token(&self, value: i32, token_type: CostTokenType) -> Self::CostType;
>     /// Gets a cost for the content of a function.
>     fn function_cost(&mut self, function: &Function) -> Self::CostType;
> ```

remove



_Code quote:_
```XML
    /// Gets a cost for the content of a function.
    fn function_cost(&mut self, function: &Function) -> Self::CostType;
```
___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 42 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1880#-NMZ8Qzo060aelEoO1O0:-NMZ8Qzo060aelEoO1O1:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/4c02ffa012001e5fd0860e5f0a14fc99abf081b8/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L42)):*
> ```XML
>     /// Gets a cost for the content of a function.
>     fn function_cost(&mut self, function: &Function) -> Self::CostType;
>     /// Gets a cost for the content of a function.
> ```





_Suggestion:_
```XML
    /// Gets a token cost for the content of a function.
```
___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 74 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1880#-NMZ7_MD4HVgJDBpu9RB:-NMZ7_MD4HVgJDBpu9RC:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/4c02ffa012001e5fd0860e5f0a14fc99abf081b8/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L74)):*
> ```XML
>         FunctionCall(FunctionCallConcreteLibfunc { function, .. }) => {
>             // let func_content_cost = ops.function_cost(function);
>             // vec![func_content_cost]
> ```

remove



_Code quote:_
```XML
            // let func_content_cost = ops.function_cost(function);
            // vec![func_content_cost]
```
___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 123 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1880#-NMZ7cjSBX_G25ql-otL:-NMZ7cjSBX_G25ql-otM:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/4c02ffa012001e5fd0860e5f0a14fc99abf081b8/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L123)):*
> ```XML
>         FunctionCall(FunctionCallConcreteLibfunc { function, .. }) => {
>             // let func_content_cost = ops.function_cost(function);
>             // vec![ops.add(ops.const_cost(2), func_content_cost)]
> ```

remove



_Code quote:_
```XML
            // let func_content_cost = ops.function_cost(function);
            // vec![ops.add(ops.const_cost(2), func_content_cost)]
```

**Pull request merged**
