### PR TITLE
Added fmt for signed int.

### PR DESCRIPTION
**Pull request by orizi**
Closes issue #5298 .

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5308)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5308)* status: all files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`corelib/src/fmt.cairo` line 38 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5308#-NtXHrMwDnglcXEOmK3e:-NtXHrMwDnglcXEOmK3f:bieirpf) ([raw file](https://github.com/starkware-libs/cairo/blob/19fd76fa4282f12225d0603cf0b36a21ed37b786/corelib/src/fmt.cairo#L38)):*
> ```Cairo
> > of Display<Signed> {
>     fn fmt(self: @Signed, ref f: Formatter) -> Result<(), Error> {
>         let (abs, sign) = (*self).abs_and_sign();
> ```

doesn't `.` desnap?



_Suggestion:_
```Cairo
self.abs_and_sign()
```
___
*[`corelib/src/fmt.cairo` line 42 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5308#-NtXI2De0B42bqi4PnZ8:-NtXI2De0B42bqi4PnZ9:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/19fd76fa4282f12225d0603cf0b36a21ed37b786/corelib/src/fmt.cairo#L42)):*
> ```Cairo
>             write!(f, "-")?;
>         }
>         Display::fmt(@abs, ref f)
> ```





_Suggestion:_
```Cairo
(@abs).fmt(ref f)
```
___
*[`corelib/src/fmt.cairo` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5308#-NtXIvhb7mu21t5geMpw:-NtXIvhb7mu21t5geMpx:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/19fd76fa4282f12225d0603cf0b36a21ed37b786/corelib/src/fmt.cairo#L94)):*
> ```Cairo
> > of Debug<Signed> {
>     fn fmt(self: @Signed, ref f: Formatter) -> Result<(), Error> {
>         Display::fmt(self, ref f)
> ```





_Suggestion:_
```Cairo
self.fmt(ref f)
```
___
*[`corelib/src/integer.cairo` line 3048 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5308#-NtXJKibB3_l2JntxWlv:-NtXJKibB3_l2JntxWlw:b-inocjs) ([raw file](https://github.com/starkware-libs/cairo/blob/19fd76fa4282f12225d0603cf0b36a21ed37b786/corelib/src/integer.cairo#L3048)):*
> ```Cairo
> pub(crate) trait AbsAndSign<Signed, Unsigned> {
>     /// Returns the absolute value of the `Signed` value as `Unsigned` and the original sign.
>     fn abs_and_sign(self: Signed) -> (Unsigned, bool);
> ```

Just to make it super explicit - say what sign is true and what sign is false.
___
*[`corelib/src/test/fmt_test.cairo` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5308#-NtXKwDT9wfIYQCmrfZ7:-NtXKwDT9wfIYQCmrfZ8:b-60ltq8) ([raw file](https://github.com/starkware-libs/cairo/blob/19fd76fa4282f12225d0603cf0b36a21ed37b786/corelib/src/test/fmt_test.cairo#L17)):*
> ```Cairo
>     assert(format!("{}", nz_value) == "1", 'non zero bad formatting');
>     assert(
>         format!("{}_{}_{}_{}_{}", 1_i8, 2_i16, 3_i32, 4_i64, 5_i128) == "1_2_3_4_5",
> ```

please add 0

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5308)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`corelib/src/fmt.cairo` line 38 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5308#-NtXHrMwDnglcXEOmK3e:-NtXN5ti2kb8nl1Foogq:bqctj4u) ([raw file](https://github.com/starkware-libs/cairo/blob/19fd76fa4282f12225d0603cf0b36a21ed37b786/corelib/src/fmt.cairo#L38)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

doesn't `.` desnap?
</blockquote></details>

it only snaps - it doesn't desnap.
___
*[`corelib/src/fmt.cairo` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5308#-NtXIvhb7mu21t5geMpw:-NtXND9V7A1ivnijZZHB:b-fzrujr) ([raw file](https://github.com/starkware-libs/cairo/blob/19fd76fa4282f12225d0603cf0b36a21ed37b786/corelib/src/fmt.cairo#L94)):*
> ```Cairo
> > of Debug<Signed> {
>     fn fmt(self: @Signed, ref f: Formatter) -> Result<(), Error> {
>         Display::fmt(self, ref f)
> ```

can't - needs to specifically call the correct fmt.
___
*[`corelib/src/integer.cairo` line 3048 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5308#-NtXJKibB3_l2JntxWlv:-NtXNj9U8QkVnK6iwCzG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/19fd76fa4282f12225d0603cf0b36a21ed37b786/corelib/src/integer.cairo#L3048)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Just to make it super explicit - say what sign is true and what sign is false.
</blockquote></details>

Done.
___
*[`corelib/src/test/fmt_test.cairo` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5308#-NtXKwDT9wfIYQCmrfZ7:-NtXOEQb7HM6IeoOZYA2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/19fd76fa4282f12225d0603cf0b36a21ed37b786/corelib/src/test/fmt_test.cairo#L17)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

please add 0
</blockquote></details>

Done.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5308#-:-NtXREsc3Jco3OZOeK_X:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`corelib/src/fmt.cairo` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5308#-NtXIvhb7mu21t5geMpw:-NtXR293--DXg7hFC1c0:b-u5aria) ([raw file](https://github.com/starkware-libs/cairo/blob/19fd76fa4282f12225d0603cf0b36a21ed37b786/corelib/src/fmt.cairo#L94)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can't - needs to specifically call the correct fmt.
</blockquote></details>

what other formats do you have in context?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5308)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @yuvalsw)

___
*[`corelib/src/fmt.cairo` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5308#-NtXIvhb7mu21t5geMpw:-NtXdzzV7Lg8XVGFyz6X:b-j4mu99) ([raw file](https://github.com/starkware-libs/cairo/blob/19fd76fa4282f12225d0603cf0b36a21ed37b786/corelib/src/fmt.cairo#L94)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

what other formats do you have in context?
</blockquote></details>

The Display vs the Debug

**Review by yuvalsw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5308)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`corelib/src/fmt.cairo` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5308#-NtXIvhb7mu21t5geMpw:-NtjvlZr6RBfVxnWMff5:b-5d05af) ([raw file](https://github.com/starkware-libs/cairo/blob/19fd76fa4282f12225d0603cf0b36a21ed37b786/corelib/src/fmt.cairo#L94)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

The Display vs the Debug
</blockquote></details>

Does it find the Debug that you are currently in (that is, DebugSignedInteger)? If so, it's out of context, but needs to be resolved.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5308)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @yuvalsw)

___
*[`corelib/src/fmt.cairo` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5308#-NtXIvhb7mu21t5geMpw:-NtjwRcq56RxCnmSphxj:b-rbnhlu) ([raw file](https://github.com/starkware-libs/cairo/blob/19fd76fa4282f12225d0603cf0b36a21ed37b786/corelib/src/fmt.cairo#L94)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Does it find the Debug that you are currently in (that is, DebugSignedInteger)? If so, it's out of context, but needs to be resolved.
</blockquote></details>

it finds it - and it is in context.

**Pull request merged**
