### PR TITLE
Prevent adding trait uses to traits in scope from completions menu and add tests.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6142)

### CODE REVIEW

**Comment by mkaput** [comment]
duplicate of #6140?

**Review by gilbens-starkware — COMMENTED** [review]
Yes.
Same as #6140, but over main. Spr created a new branch.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6142#-:-O3XZad6CoCm1fHsngiD:b-d7x87m)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6142#-:-O3X_58N5Mrhy1gy6IbJ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

**Review by mkaput — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6142)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 319 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6142#-O3X_al92_Pe2zGrLgCG:-O3Xg1Z995IG7WpiWN9b:b-uiz0ac) ([raw file](https://github.com/starkware-libs/cairo/blob/60f77ebec4a7ab8cd06198b639d48a7bda564fb8/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L319)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

This unwrap should never fail, right?
</blockquote></details>

Oh good catch! Please return none value here

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6142)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 319 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6142#-O3X_al92_Pe2zGrLgCG:-O3bGqHr5eklVi50pRy2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/60f77ebec4a7ab8cd06198b639d48a7bda564fb8/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L319)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Oh good catch! Please return none value here
</blockquote></details>

Done.

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6142#-:-O3bKL083_btvDuK9pMN:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

**Pull request merged**
