### PR TITLE
Added uint128_eq

### PR DESCRIPTION
**Pull request by amosStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1004)

### CODE REVIEW

**Review by amosStarkware — COMMENTED** [review]
+reviewer:@orizi 
please keep in mind that a lot of this is guesswork on my part, so a thorough review is important

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1004#-:-NJKhv_985rCtzgZC8Gg:b1lcrev)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1004)* status: 4 of 13 files reviewed, 5 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 356 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1004#-NJKuNpa6avV6n8UeD2u:-NJKuNpa6avV6n8UeD2v:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/9ac8ab106dc6d7bad385164825f174ec87cccef4/crates/sierra_to_casm/src/invocations/uint128.rs#L356)):*
> ```XML
> }
> 
> fn build_uint128_eq(
> ```

doc



_Code quote:_
```XML
build_uint128_eq
```
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 361 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1004#-NJKvH8F7oogY0RumWVD:-NJKvH8F7oogY0RumWVE:bzcgylg) ([raw file](https://github.com/starkware-libs/cairo/blob/9ac8ab106dc6d7bad385164825f174ec87cccef4/crates/sierra_to_casm/src/invocations/uint128.rs#L361)):*
> ```XML
>     let (a, b) = match builder.refs {
>         [ReferenceValue { expression: expr_a, .. }, ReferenceValue { expression: expr_b, .. }] => {
>             (try_unpack_deref(expr_a)?, try_unpack_deref(expr_b)?)
> ```

add a following pr to also support all the immediate configurations as well.
(so, a, b, or both may be constants)



_Code quote:_
```XML
) -> Result<CompiledInvocation, InvocationError> {
    let (a, b) = match builder.refs {
        [ReferenceValue { expression: expr_a, .. }, ReferenceValue { expression: expr_b, .. }] => {
            (try_unpack_deref(expr_a)?, try_unpack_deref(expr_b)?)
        }
        refs => {
            return Err(InvocationError::WrongNumberOfArguments {
                expected: 2,
                actual: refs.len(),
            });
        }
    };
```
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 377 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1004#-NJKujM13WwyJUuxufYA:-NJKujM13WwyJUuxufYB:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9ac8ab106dc6d7bad385164825f174ec87cccef4/crates/sierra_to_casm/src/invocations/uint128.rs#L377)):*
> ```XML
>             // res = a - b => (res == 0) <==> (a == b)
>             alloc res;
>             a = res + b;
> ```





_Suggestion:_
```XML
    casm_build_extend! {casm_builder,
            // res = a - b => (res == 0) <==> (a == b)
            alloc diff;
            a = diff + b;

            jump NotEqual if res != 0;
            jump Equal;
        NotEqual:
    };
    let CasmBuildResult {
```
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 384 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1004#-NJKun2p8MjPSdEg3ACq:-NJKun2p8MjPSdEg3ACr:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9ac8ab106dc6d7bad385164825f174ec87cccef4/crates/sierra_to_casm/src/invocations/uint128.rs#L384)):*
> ```XML
>     };
>     let CasmBuildResult {
>         instructions,
> ```





_Suggestion:_
```XML
    let CasmBuildResult {
        instructions,
        awaiting_relocations,
        ..
    } = casm_builder.build();
```
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 390 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1004#-NJKv6Kj4UysskRmLSFL:-NJKv6Kj4UysskRmLSFM:b3hq0uy) ([raw file](https://github.com/starkware-libs/cairo/blob/9ac8ab106dc6d7bad385164825f174ec87cccef4/crates/sierra_to_casm/src/invocations/uint128.rs#L390)):*
> ```XML
>     } = casm_builder.build();
> 
>     let [relocation_index] = &awaiting_relocations[..] else { panic!("Malformed casm builder usage.") };
> ```

add an assertion `TODO(orizi):` like in the other places.



_Code quote:_
```XML
    let [relocation_index] = &awaiting_relocations[..] else { panic!("Malformed casm builder usage.") };
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1004)* status: 8 of 13 files reviewed, 7 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/sierra_to_casm/src/compiler_test.rs` line 217 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1004#-NJKsd7H7Ys4dWOqwl7p:-NJKsd7H7Ys4dWOqwl7q:b-tbt532) ([raw file](https://github.com/starkware-libs/cairo/blob/9ac8ab106dc6d7bad385164825f174ec87cccef4/crates/sierra_to_casm/src/compiler_test.rs#L217)):*
> ```XML
> 
>                 libfunc revoke_ap_tracking = revoke_ap_tracking;
>                 libfunc uint128_eq = uint128_eq;
> ```

I think we don't need to add these tests anymore; the corelib/test.cairo should be enough. @orizi WDYT?



_Code quote:_
```XML
                libfunc revoke_ap_tracking = revoke_ap_tracking;
                libfunc uint128_eq = uint128_eq;

                revoke_ap_tracking() -> ();
                uint128_eq([1], [2]) {fallthrough() 2() };
                return ();

                test_program@0([1]: uint128, [2]: uint128) -> ();
            "}, false, indoc!{"
                [fp + -4] = [ap + 0] + [fp + -3], ap++;
                jmp rel 4 if [ap + -1] != 0;
                jmp rel 2;
                ret;
            "}; "uint128_eq")]
#[test_case(indoc! {"
                type uint128 = uint128;
```
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 379 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1004#-NJKt81d0Xyn-3QS3wvg:-NJKt81d0Xyn-3QS3wvh:be8g813) ([raw file](https://github.com/starkware-libs/cairo/blob/9ac8ab106dc6d7bad385164825f174ec87cccef4/crates/sierra_to_casm/src/invocations/uint128.rs#L379)):*
> ```XML
>             a = res + b;
> 
>             jump NotEqual if res != 0;
> ```

I think you should be able to save a jump statement.
I think the CASM (before relocations) should be:
```
a = [ap] + b, ap++;
jmp rel 0 if [ap-1] != 0;
```
The jmp target should be relocated here for the FALSE case (a != b), and the fallthrough should be the TRUE case



_Code quote:_
```XML
            jump NotEqual if res != 0;
            jump Equal;
        NotEqual:
```

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1004)* status: 8 of 13 files reviewed, 7 unresolved discussions (waiting on @orizi)

___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 379 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1004#-NJKt81d0Xyn-3QS3wvg:-NJL3gV4Eu-VYT1UI35K:b-3v916q) ([raw file](https://github.com/starkware-libs/cairo/blob/9ac8ab106dc6d7bad385164825f174ec87cccef4/crates/sierra_to_casm/src/invocations/uint128.rs#L379)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think you should be able to save a jump statement.
I think the CASM (before relocations) should be:
```
a = [ap] + b, ap++;
jmp rel 0 if [ap-1] != 0;
```
The jmp target should be relocated here for the FALSE case (a != b), and the fallthrough should be the TRUE case
</blockquote></details>

that's what I thought, but @orizi  told me to do the opposite (and this passes the tests)

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1004)* status: 8 of 13 files reviewed, 7 unresolved discussions (waiting on @orizi)

___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 356 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1004#-NJKuNpa6avV6n8UeD2u:-NJL5Q2m6jppqIvwFV6a:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9ac8ab106dc6d7bad385164825f174ec87cccef4/crates/sierra_to_casm/src/invocations/uint128.rs#L356)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 361 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1004#-NJKvH8F7oogY0RumWVD:-NJL8Z303Kd49amEa9zB:b-d7bhn0) ([raw file](https://github.com/starkware-libs/cairo/blob/9ac8ab106dc6d7bad385164825f174ec87cccef4/crates/sierra_to_casm/src/invocations/uint128.rs#L361)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add a following pr to also support all the immediate configurations as well.
(so, a, b, or both may be constants)
</blockquote></details>

will do
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 377 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1004#-NJKujM13WwyJUuxufYA:-NJL5caX1bPKFydY3Mx7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9ac8ab106dc6d7bad385164825f174ec87cccef4/crates/sierra_to_casm/src/invocations/uint128.rs#L377)):*
> ```XML
>             // res = a - b => (res == 0) <==> (a == b)
>             alloc res;
>             a = res + b;
> ```

Done.
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 384 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1004#-NJKun2p8MjPSdEg3ACq:-NJL5e9G0Uujuv4QHlx_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9ac8ab106dc6d7bad385164825f174ec87cccef4/crates/sierra_to_casm/src/invocations/uint128.rs#L384)):*
> ```XML
>     };
>     let CasmBuildResult {
>         instructions,
> ```

Done.
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 390 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1004#-NJKv6Kj4UysskRmLSFL:-NJL8VvH-B2S2XjvsuWR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9ac8ab106dc6d7bad385164825f174ec87cccef4/crates/sierra_to_casm/src/invocations/uint128.rs#L390)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add an assertion `TODO(orizi):` like in the other places.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 13 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1004#-:-NJLCpyV6BPye98iiV9m:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/sierra_to_casm/src/compiler_test.rs` line 217 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1004#-NJKsd7H7Ys4dWOqwl7p:-NJLC8C326G5X1B-2N0g:bk78aby) ([raw file](https://github.com/starkware-libs/cairo/blob/9ac8ab106dc6d7bad385164825f174ec87cccef4/crates/sierra_to_casm/src/compiler_test.rs#L217)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think we don't need to add these tests anymore; the corelib/test.cairo should be enough. @orizi WDYT?
</blockquote></details>

if we do any of these - probably put them at the per libfunc tests instead of here.
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 379 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1004#-NJKt81d0Xyn-3QS3wvg:-NJLCY0I-dEgC6_KbDYJ:b3yj6m3) ([raw file](https://github.com/starkware-libs/cairo/blob/9ac8ab106dc6d7bad385164825f174ec87cccef4/crates/sierra_to_casm/src/invocations/uint128.rs#L379)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

that's what I thought, but @orizi  told me to do the opposite (and this passes the tests)
</blockquote></details>

what you are suggesting is the implementation of uint128_ne - not uint128_eq.

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1004)* status: 12 of 13 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/sierra_to_casm/src/compiler_test.rs` line 217 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1004#-NJKsd7H7Ys4dWOqwl7p:-NJLF_re8Yr2gSECK7lh:bedkmqf) ([raw file](https://github.com/starkware-libs/cairo/blob/9ac8ab106dc6d7bad385164825f174ec87cccef4/crates/sierra_to_casm/src/compiler_test.rs#L217)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

if we do any of these - probably put them at the per libfunc tests instead of here.
</blockquote></details>

Deleted the test. If I should add it anywhere else please tell me.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1004#-:-NJLXYsZ6C2NEAgZmjMx:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1004)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1004#-NJZMS2f8Z2KNYj0R_ay:-NJZMS2f8Z2KNYj0R_az:b6v0woi) (no related file):*
can you please squash this pr into a single commit?

___

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1004)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware)

**Pull request merged**
