### PR TITLE
Add support for goto in sierra gen.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2035)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2035)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @liorgold2)

___
*[`crates/cairo-lang-sierra-generator/src/block_generator.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2035#-NNIad2f9ud_apO1syEK:-NNIad2f9ud_apO1syEL:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/af9452cdd7fd4157252472a5a8e0e5f3abb70bde/crates/cairo-lang-sierra-generator/src/block_generator.rs#L136)):*
> ```XML
>             ));
>             // Here we might reach the next statement through after jumping to
>             // *block_id, but we don't full through into the next statement.
> ```





_Suggestion:_
```XML
            // *block_id, but we don't fallthrough into the next statement.
```
___
*[`crates/cairo-lang-sierra-generator/src/expr_generator_context.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2035#-NNIaoOw02myhmqhDj_0:-NNIaoOw02myhmqhDj_1:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/af9452cdd7fd4157252472a5a8e0e5f3abb70bde/crates/cairo-lang-sierra-generator/src/expr_generator_context.rs#L85)):*
> ```XML
> 
>     // TODO(lior): Consider using stable ids, instead of allocating sequential ids.
>     pub fn alloc_label_id(&mut self) -> pre_sierra::LabelId {
> ```

doc



_Code quote:_
```XML
    pub fn alloc_label_id(&mut self) -> pre_sierra::LabelId {
```
___
*[`crates/cairo-lang-sierra-generator/src/expr_generator_context.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2035#-NNIauyY8sZPEV0fWo4g:-NNIauyY8sZPEV0fWo4h:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/af9452cdd7fd4157252472a5a8e0e5f3abb70bde/crates/cairo-lang-sierra-generator/src/expr_generator_context.rs#L150)):*
> ```XML
> 
> pub fn alloc_label_id(
>     db: &dyn SierraGenGroup,
> ```

doc



_Code quote:_
```XML
pub fn alloc_label_id(
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2035)* status: 10 of 12 files reviewed, 3 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/block_generator.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2035#-NNIad2f9ud_apO1syEK:-NNggK4R0L4FUjOpSzLq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/af9452cdd7fd4157252472a5a8e0e5f3abb70bde/crates/cairo-lang-sierra-generator/src/block_generator.rs#L136)):*
> ```XML
>             ));
>             // Here we might reach the next statement through after jumping to
>             // *block_id, but we don't full through into the next statement.
> ```

Done.
___
*[`crates/cairo-lang-sierra-generator/src/expr_generator_context.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2035#-NNIaoOw02myhmqhDj_0:-NNgh3_e-gpUjB8Yp-n1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/af9452cdd7fd4157252472a5a8e0e5f3abb70bde/crates/cairo-lang-sierra-generator/src/expr_generator_context.rs#L85)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/expr_generator_context.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2035#-NNIauyY8sZPEV0fWo4g:-NNgh3LO7BHVLP8GI7Cf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/af9452cdd7fd4157252472a5a8e0e5f3abb70bde/crates/cairo-lang-sierra-generator/src/expr_generator_context.rs#L150)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2035#-:-NNgmhUQ6t961xqDB--Z:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 9 of 12 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2035)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
