### PR TITLE
Fix enable ap tracking detection bug.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5073)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5073)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5073#-Nqgbe4J160fw6rZIQls):*
add a test.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5073)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5073#-Nqgbe4J160fw6rZIQls):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add a test.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5073)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`tests/bug_samples/enable_ap_tracking_aliasing.cairo` line 16 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5073#-NqgwfQeDCME6NSe8B0z:-NqgwfQeDCME6NSe8B1-:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/02fba64e4fa0450af1cc7051d6a5683d1f970cf0/tests/bug_samples/enable_ap_tracking_aliasing.cairo#L16)):*
> ```Cairo
> #[test]
> #[inline(never)]
> fn test_contract_address_ordering() {
> ```





_Suggestion:_
```Cairo
}

#[test]
fn test_contract_address_ordering() {
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5073#-:-Nqh0FbF8D5lhO9em2P8:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
