### PR TITLE
Generate TEST_CLASS_HASH

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2907)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2907** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2907" target="_blank">Graphite</a>  👈
    * **PR #2908** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2908" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2907?utm_source=stack-comment).

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2907#-:-NTdmCx7-xhJavovQrWc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2907)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 236 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2907#-NTdop3v8Soux68twK-i:-NTdop3v8Soux68twK-j:blesiup) ([raw file](https://github.com/starkware-libs/cairo/blob/2ef9eafb26205fc1d3f25e503322342336ee6343/crates/cairo-lang-starknet/src/plugin/contract.rs#L236)):*
> ```XML
> 
>             $original_items$
>                 const TEST_CLASS_HASH: felt252 = {test_class_hash};
> ```

Maybe make this hex?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2907)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/plugin/contract.rs` line 236 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2907#-NTdop3v8Soux68twK-i:-NTdq-qT4WUV-BM3qa86:bdch3nf) ([raw file](https://github.com/starkware-libs/cairo/blob/2ef9eafb26205fc1d3f25e503322342336ee6343/crates/cairo-lang-starknet/src/plugin/contract.rs#L236)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Maybe make this hex?
</blockquote></details>

I don't think it's important. It's only for testing. People are't supposed to see this, and if they do, they are not supposed to use it outside of the test.

**Pull request merged**
