### PR TITLE
Extract Range into sierra utils.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
**Stack**:
- #4624
- #4623 ⬅
- #4583

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4623)

### CODE REVIEW

**Review by TomerStarkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4623#-:-Nm7-PrJ4dTEBw9aq8fD:bnfp4nl)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4623#-:-Nm70_HgDQhmXy0vBFos:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4623)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Comment by gilbens-starkware** [comment]
✓ Commit merged in pull request [#4624](https://github.com/starkware-libs/cairo/pull/4624)

**Pull request merged**
