### PR TITLE
prevent capturing mutable variables and allow accessing copiable vari…

### PR DESCRIPTION
**Pull request by TomerStarkware**
…ables post closure usage

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6277)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6277)* status: 3 of 7 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/block_builder.rs` line 308 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6277#-O58Q8bbA2WVv4boPumW:-O58Q8bbA2WVv4boPumX:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/701a7718d39c519ea1700601b09e54115dba483a/crates/cairo-lang-lowering/src/lower/block_builder.rs#L308)):*
> ```XML
>                 self.semantics.captured.insert(member.clone(), var_usage.var_id);
>             }
>         }
> ```





_Suggestion:_
```XML
            .collect();

        let var_usage = generators::StructConstruct { inputs, ty: expr.ty, location }
            .add(ctx, &mut self.statements);
        let closure_info = ClosureInfo { members, snapshot_types };

        for (var_usage, member) in zip!(inputs, usage.usage.keys()) {
            if ctx.variables[var_usage.var_id].copyable.is_ok() && !usage.changes.contains_key(member) {
                self.semantics.copiable_captured.insert(member.clone(), var_usage.var_id);
            } else {
                self.semantics.captured.insert(member.clone(), var_usage.var_id);
            }
        }
```
___
*[`crates/cairo-lang-lowering/src/lower/block_builder.rs` line 545 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6277#-O58QkZO4-0MR_L37dj1:-O58QkZO4-0MR_L37dj2:b-xvun4r) ([raw file](https://github.com/starkware-libs/cairo/blob/701a7718d39c519ea1700601b09e54115dba483a/crates/cairo-lang-lowering/src/lower/block_builder.rs#L545)):*
> ```XML
>     fn var(&self, var: VariableId) -> &Variable {
>         &self.ctx.variables[var]
>     }
> ```

this isn't used.



_Code quote:_
```XML
    fn var(&self, var: VariableId) -> &Variable {
        &self.ctx.variables[var]
    }
```
___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 858 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6277#-O58QTyd45XelkFzyUwY:-O58QTyd45XelkFzyUwZ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/701a7718d39c519ea1700601b09e54115dba483a/crates/cairo-lang-semantic/src/diagnostic.rs#L858)):*
> ```XML
>             }
>             SemanticDiagnosticKind::MutableCapturedVariable => {
>                 "Mutable variables cannot be captured by closures".into()
> ```





_Suggestion:_
```XML
                "Mutable variables capture by closure is not supported".into()
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6277)* status: 3 of 7 files reviewed, 4 unresolved discussions (waiting on @orizi and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1648 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6277#-O58SWlT6JCzGszulr1c:-O58SWlT6JCzGszulr1d:b-8ybv0x) ([raw file](https://github.com/starkware-libs/cairo/blob/701a7718d39c519ea1700601b09e54115dba483a/crates/cairo-lang-semantic/src/expr/compute.rs#L1648)):*
> ```XML
> 
>     // TODO(TomerStarkware): Add support for capturing mutable variables when then we have borrow.
>     for (captured_var, expr) in usage.usage.iter().chain(usage.snap_usage.iter()) {
> ```

what about usage. changes? do we support that?



_Code quote:_
```XML
for (captured_var, expr) in usage.usage.iter().chain(usage.snap_usage.iter()) {
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/refs.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6277#-O58Tbeq0LKF52sSZSx7:-O58Tbeq0LKF52sSZSx8:b8ryprn) ([raw file](https://github.com/starkware-libs/cairo/blob/401d7637fe8805140b3f3cb4365f1258322ad935/crates/cairo-lang-lowering/src/lower/refs.rs#L98)):*
> ```XML
>             }
>         }
>     }
> ```

Shouldn't we skip the update if it is a copiable capture?



_Code quote:_
```XML
     self.update(ctx, path, new_var).unwrap();
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6277)* status: 1 of 7 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/block_builder.rs` line 308 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6277#-O58Q8bbA2WVv4boPumW:-O58dfTY34f5mCeAG6di:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/701a7718d39c519ea1700601b09e54115dba483a/crates/cairo-lang-lowering/src/lower/block_builder.rs#L308)):*
> ```XML
>                 self.semantics.captured.insert(member.clone(), var_usage.var_id);
>             }
>         }
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/lower/block_builder.rs` line 545 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6277#-O58QkZO4-0MR_L37dj1:-O58tH933-t2mNdZGeCY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/701a7718d39c519ea1700601b09e54115dba483a/crates/cairo-lang-lowering/src/lower/block_builder.rs#L545)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this isn't used.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/refs.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6277#-O58Tbeq0LKF52sSZSx7:-O58erS1CtAdqBwWT84k:b2nign6) ([raw file](https://github.com/starkware-libs/cairo/blob/401d7637fe8805140b3f3cb4365f1258322ad935/crates/cairo-lang-lowering/src/lower/refs.rs#L98)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Shouldn't we skip the update if it is a copiable capture?
</blockquote></details>

yes
___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 858 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6277#-O58QTyd45XelkFzyUwY:-O58isqM7_Iv5gxN9Q9Q:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/701a7718d39c519ea1700601b09e54115dba483a/crates/cairo-lang-semantic/src/diagnostic.rs#L858)):*
> ```XML
>             }
>             SemanticDiagnosticKind::MutableCapturedVariable => {
>                 "Mutable variables cannot be captured by closures".into()
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1648 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6277#-O58SWlT6JCzGszulr1c:-O58j-ZF0UyCbez31tP-:b-11gngr) ([raw file](https://github.com/starkware-libs/cairo/blob/701a7718d39c519ea1700601b09e54115dba483a/crates/cairo-lang-semantic/src/expr/compute.rs#L1648)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what about usage. changes? do we support that?
</blockquote></details>

no it has the same problem



_Code snippet:_
```XML
let mut x = 0;
let c = || {x=x+1;};
x=1
c();
```

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 3 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6277)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6277#-:-O58v7Gv0fVOWxd0kExm:bnfp4nl)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/refs.rs` line 128 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6277#-O5CD5BpDK_xW0ii6qaf:-O5CD5BpDK_xW0ii6qag:bvk7d9b) ([raw file](https://github.com/starkware-libs/cairo/blob/e5bcb49d268625ffeecd4c42e33ab80ae4fbcf0a/crates/cairo-lang-lowering/src/lower/refs.rs#L128)):*
> ```XML
>     ) -> Option<()> {
>         if self.copiable_captured.get(path).is_some() {
>             // Note, this can only right now if we take a snapshot of the variable (as the snapshot
> ```

fix comment.



_Code quote:_
```XML
this can only right now if we take a snapshot
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 858 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6277#-O5CDO2d5aegyTJYPTVU:-O5CDO2d5aegyTJYPTVV:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e5bcb49d268625ffeecd4c42e33ab80ae4fbcf0a/crates/cairo-lang-semantic/src/diagnostic.rs#L858)):*
> ```XML
>             }
>             SemanticDiagnosticKind::MutableCapturedVariable => {
>                 "Mutable variables capture by closure is not supported".into()
> ```





_Suggestion:_
```XML
Capture of mutable variables in a closure is not supported
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1648 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6277#-O58SWlT6JCzGszulr1c:-O5CDVMMDWqeJYFJVM9l:b-9qsz8) ([raw file](https://github.com/starkware-libs/cairo/blob/701a7718d39c519ea1700601b09e54115dba483a/crates/cairo-lang-semantic/src/expr/compute.rs#L1648)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

no it has the same problem
</blockquote></details>

so you should go over usage.chages as well,  right?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 7 files at r1, 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6277)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @orizi and @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6277)* status: 2 of 7 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/refs.rs` line 128 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6277#-O5CD5BpDK_xW0ii6qaf:-O5FN4fN4yW3NnVkfEqY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e5bcb49d268625ffeecd4c42e33ab80ae4fbcf0a/crates/cairo-lang-lowering/src/lower/refs.rs#L128)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

fix comment.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 858 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6277#-O5CDO2d5aegyTJYPTVU:-O5FLnMT7ciDUuyyGESh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e5bcb49d268625ffeecd4c42e33ab80ae4fbcf0a/crates/cairo-lang-semantic/src/diagnostic.rs#L858)):*
> ```XML
>             }
>             SemanticDiagnosticKind::MutableCapturedVariable => {
>                 "Mutable variables capture by closure is not supported".into()
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1648 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6277#-O58SWlT6JCzGszulr1c:-O5FLu5vBrOJVbDJLe3N:b-inazk5) ([raw file](https://github.com/starkware-libs/cairo/blob/701a7718d39c519ea1700601b09e54115dba483a/crates/cairo-lang-semantic/src/expr/compute.rs#L1648)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

so you should go over usage.chages as well,  right?
</blockquote></details>

isn't changes contained in usage?

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6277)* status: 2 of 7 files reviewed, 3 unresolved discussions (waiting on @orizi and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/refs.rs` line 128 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6277#-O5CD5BpDK_xW0ii6qaf:-O5HXtH22NU9ffv3sxIq:b-ut7np8) ([raw file](https://github.com/starkware-libs/cairo/blob/e5bcb49d268625ffeecd4c42e33ab80ae4fbcf0a/crates/cairo-lang-lowering/src/lower/refs.rs#L128)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see it

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1648 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6277#-O58SWlT6JCzGszulr1c:-O5HXxdLCQirrHCjSpLz:b32wsm) ([raw file](https://github.com/starkware-libs/cairo/blob/701a7718d39c519ea1700601b09e54115dba483a/crates/cairo-lang-semantic/src/expr/compute.rs#L1648)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

isn't changes contained in usage?
</blockquote></details>

no

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6277)* status: 1 of 7 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/refs.rs` line 128 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6277#-O5CD5BpDK_xW0ii6qaf:-O5I3be-70P1lq5NCfvF:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e5bcb49d268625ffeecd4c42e33ab80ae4fbcf0a/crates/cairo-lang-lowering/src/lower/refs.rs#L128)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't see it
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1648 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6277#-O58SWlT6JCzGszulr1c:-O5I2q21EinDCZf7RrAN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/701a7718d39c519ea1700601b09e54115dba483a/crates/cairo-lang-semantic/src/expr/compute.rs#L1648)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

no
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6277#-:-O5IAHQ3B9DK9jqvB3y5:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6277)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6277)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1667 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6277#-O5sFagCEp9WbOesveqI:-O5sFagCEp9WbOesveqJ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e7689719a59fd70b8f014741925dcc86d2070dbf/crates/cairo-lang-semantic/src/expr/compute.rs#L1667)):*
> ```XML
>             ctx.diagnostics.report(expr.stable_ptr(), MutableCapturedVariable);
>         }
>     }
> ```





_Suggestion:_
```XML
    let mut reported = UnorderedHashSet::<_>::default();
    // TODO(TomerStarkware): Add support for capturing mutable variables when then we have borrow.
    for (captured_var, expr) in chain!(&usage.usage, &usage.snap_usage, &usage.changes)
    {
        let Some(var) = ctx.semantic_defs.get(&captured_var.base_var()) else {
            // if the variable is not found in the semantic defs, it is closure parameter.
            continue;
        };

        if var.is_mut() && reported.insert(expr.stable_ptr()) {
            ctx.diagnostics.report(expr.stable_ptr(), MutableCapturedVariable);
        }
    }
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6277)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1667 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6277#-O5sFagCEp9WbOesveqI:-O5sN0Vk5OTlAlyqlebD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e7689719a59fd70b8f014741925dcc86d2070dbf/crates/cairo-lang-semantic/src/expr/compute.rs#L1667)):*
> ```XML
>             ctx.diagnostics.report(expr.stable_ptr(), MutableCapturedVariable);
>         }
>     }
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6277)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1658 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6277#-O5sNcS70di0__gOIbnq:-O5sNcS85gBt1ZCqCMKJ:b-mn45u5) ([raw file](https://github.com/starkware-libs/cairo/blob/f5521427148e0f2c20fbea316459cd8d4b5f50e7/crates/cairo-lang-semantic/src/expr/compute.rs#L1658)):*
> ```XML
>     for (captured_var, expr) in
>         chain!(usage.usage.iter(), usage.snap_usage.iter(), usage.changes.iter())
>     {
> ```

this doesn't work?



_Suggestion:_
```XML
    for (captured_var, expr) in chain!(&usage.usage, &usage.snap_usage, &usage.changes) {
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6277)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1658 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6277#-O5sNcS70di0__gOIbnq:-O5sOate8-9XSIQQW2ln:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f5521427148e0f2c20fbea316459cd8d4b5f50e7/crates/cairo-lang-semantic/src/expr/compute.rs#L1658)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this doesn't work?
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6277#-:-O5sS0xUAhmzAD0tqx7i:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
