### PR TITLE
Allowed add-const for range-check in array_get and array_slice

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3070)

### CODE REVIEW

**Review by orizi — COMMENTED** [review]
we need to add a sierra-v1.1.0 branch and merge this into it - as this may cause generating sierra code that won't compile in the current sierra version.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3070#-:-NUzbrsz3yae_QaAUIXb:b-t4ojap)* status: 0 of 2 files reviewed, all discussions resolved

**Review by yuvalsw — COMMENTED** [review]
I agree we need the new branch for audit reasons.
But I don't think this specific change breaks existing code as it only adds flexibility, and it will compile as there are similar idioms in other libfuncs.

Anyway - created such a branch and changed the target of this PR to it.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3070#-:-NV01eMYDPQztfPcrmTf:b86iuau)* status: 0 of 2 files reviewed, all discussions resolved

**Review by yuvalsw — COMMENTED** [review]
OK, so unless there are other comments, please LGTM so that I can submit to the new branch

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3070#-:-NV0Ahak3WqequAWn386:b-qr80jl)* status: 0 of 2 files reviewed, all discussions resolved

**Review by orizi — COMMENTED** [review]
i just want to add the branch to the protected branches first.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3070#-:-NV0BnPK9EV_MOtWtw0P:bcopd2j)* status: 0 of 2 files reviewed, all discussions resolved

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3070#-:-NV0CaM33cVsKVfzO4nh:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved

**Pull request merged**
