### PR TITLE
Add dict_squash to sierra_to_casm

### PR DESCRIPTION
**Pull request by gilbens-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1110)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
Don't review yet.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1110#-:-NHtk6Zx2HfYls4ScrOK:bsay23d)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @orizi)

**Review by gilbens-starkware — COMMENTED** [review]
Now it's ready.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1110#-:-NI73Ek64WFNnnwotKGe:b-5awad7)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 12 files at r2, 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1110)* status: all files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/casm/src/hints.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1110#-NHxLk8V1Ol_Z9vbtW2C:-NHxLk8V1Ol_Z9vbtW2D:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/060b65feace8b2486647ad49f09f2619253ef359/crates/casm/src/hints.rs#L181)):*
> ```XML
>                     from starkware.cairo.common.dict import DictManager
>                     __dict_manager = DictManager()
>                     
> ```

.
___
*[`crates/casm/src/hints.rs` line 127 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1110#-NI79UhL32GjArLLoztL:-NI79UhL32GjArLLoztM:b1xvp40) ([raw file](https://github.com/starkware-libs/cairo/blob/506c42a4052700030478efba1d58957f831f7090/crates/casm/src/hints.rs#L127)):*
> ```XML
> // Represents hints which uniquely belongs to the dict_squash function.
> #[derive(Debug, Eq, PartialEq, Clone)]
> pub enum DictSquashHint {
> ```

try swapping with some type as discussed f2f.



_Code quote:_
```XML
#[derive(Debug, Eq, PartialEq, Clone)]
pub enum DictSquashHint {
    Hint1,
    Hint2,
    Hint3,
    Hint4,
    Hint5,
    Hint6,
    Hint7,
    Hint8,
    Hint9,
    Hint10,
    Hint11,
    Hint12,
    Hint13,
    Hint14,
    Hint15,
    Hint16,
    Hint17,
}
```
___
*[`crates/sierra_to_casm/src/invocations/dict_felt_to.rs` line 192 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1110#-NHxMVwa-g10tnCaY5K4:-NHxMVwa-g10tnCaY5K5:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/060b65feace8b2486647ad49f09f2619253ef359/crates/sierra_to_casm/src/invocations/dict_felt_to.rs#L192)):*
> ```XML
> }
> 
> fn build_dict_felt_to_squash(
> ```

doc



_Code quote:_
```XML
 build_dict_felt_to_squas
```
___
*[`crates/sierra_to_casm/src/invocations/dict_felt_to.rs` line 218 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1110#-NI7ASMEAomK4HJap6Cg:-NI7ASMEAomK4HJap6Ch:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/506c42a4052700030478efba1d58957f831f7090/crates/sierra_to_casm/src/invocations/dict_felt_to.rs#L218)):*
> ```XML
>     let mut end_expr = dict_view.end;
>     let end_offset = dict_view.end_offset;
>     let prime_over_2_high = BigInt::from_str("3544607988759775765608368578435044694").unwrap();
> ```

doc



_Code quote:_
```XML
    let prime_over_2_high = BigInt::from_str("3544607988759775765608368578435044694").unwrap();
    let prime_over_3_high = BigInt::from_str("5316911983139663648412552867652567041").unwrap();
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1110)* status: 3 of 15 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/casm/src/hints.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1110#-NHxLk8V1Ol_Z9vbtW2C:-NIZFCpg-1bTHy6-uHWF:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/060b65feace8b2486647ad49f09f2619253ef359/crates/casm/src/hints.rs#L181)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

?
___
*[`crates/casm/src/hints.rs` line 127 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1110#-NI79UhL32GjArLLoztL:-NIZFBdtAZBmhSSEigl-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/506c42a4052700030478efba1d58957f831f7090/crates/casm/src/hints.rs#L127)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

try swapping with some type as discussed f2f.
</blockquote></details>

Done.
___
*[`crates/sierra_to_casm/src/invocations/dict_felt_to.rs` line 192 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1110#-NHxMVwa-g10tnCaY5K4:-NIZFPZo2ckFynBElbF3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/060b65feace8b2486647ad49f09f2619253ef359/crates/sierra_to_casm/src/invocations/dict_felt_to.rs#L192)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/sierra_to_casm/src/invocations/dict_felt_to.rs` line 218 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1110#-NI7ASMEAomK4HJap6Cg:-NIZHIMn2nrtR9_sXgzi:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/506c42a4052700030478efba1d58957f831f7090/crates/sierra_to_casm/src/invocations/dict_felt_to.rs#L218)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1110)* status: 3 of 14 files reviewed, 5 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1110#-NIZHacM0x1kqmtELzIB:-NIZHacM0x1kqmtELzIC:b-tm1w2a) (no related file):*
TODO: Change base to main

___

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 10 of 11 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1110#-:-NIaHiVL4m-TEaawrSWZ:bnfp4nl)* status: all files reviewed, 3 unresolved discussions

___
*[`crates/casm/src/hints.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1110#-NHxLk8V1Ol_Z9vbtW2C:-NIaHZWdDgJIuN9m48RL:bjtj3ms) ([raw file](https://github.com/starkware-libs/cairo/blob/060b65feace8b2486647ad49f09f2619253ef359/crates/casm/src/hints.rs#L181)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

?
</blockquote></details>

it was to remove the whitespace.

**Pull request merged**
