### PR TITLE
VSCode: Move Scarb searching logic to the `Scarb` class

### PR DESCRIPTION
**Pull request by mkaput**
**Stack**:
- #5015
- #5014
- #5013
- #5012 ⬅
- #4976
- #4975
- #4974
- #4973

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5012)

### CODE REVIEW

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5012)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae and @orizi)

___
*[`vscode-cairo/src/cairols.ts` line 200 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5012#-Nq8lxv02981j7D5Cwqg:-NqRKulg9rdyWMTJWlI9:b961wdc) ([raw file](https://github.com/starkware-libs/cairo/blob/79c37b2cc7a36812d7d7ba0ad08ea21d67fc58b8/vscode-cairo/src/cairols.ts#L200)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

obsolete interpolation
</blockquote></details>

This is the only way I know to make TypeScript happy. `ctx.log.error(msg: string)`, while `e: unknown`, so I cannot call `.toString()`

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5012)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae and @orizi)

___
*[`vscode-cairo/src/scarb.ts` line 34 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5012#-Nq8misL4xXSqTT_2WVW:-NqRVDXdAQhi09F_l3Uf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/79c37b2cc7a36812d7d7ba0ad08ea21d67fc58b8/vscode-cairo/src/scarb.ts#L34)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

I'd use 3 functions instead of those comments and do `return fromConfig() || fromPath() || fromEnv()`
</blockquote></details>

Done.

**Review by Arcticae — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5012#-:-NqRgnGD27UZ1qFx78Hy:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5012#-:-NqWx7M36xZmOk7BbIqs:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

**Pull request merged**
