### PR TITLE
Orizi/prevent inline macro panic

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3394)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3394)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-casm/src/builder.rs` line 811 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3394#-NXnjy2nB_hzJP8OUjr_:-NXnjy2nB_hzJP8OUjra:byp6rt5) ([raw file](https://github.com/starkware-libs/cairo/blob/73ce07559578b242fdb1b993c8736a7c6626545a/crates/cairo-lang-casm/src/builder.rs#L811)):*
> ```XML
>     };
>     ($builder:ident, fail; $($tok:tt)*) => {
>         $builder.fail();
> ```

Revert

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3394)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3394)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-casm/src/builder.rs` line 811 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3394#-NXnjy2nB_hzJP8OUjr_:-NXnlejeCKTz5e73YrY1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/73ce07559578b242fdb1b993c8736a7c6626545a/crates/cairo-lang-casm/src/builder.rs#L811)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Revert
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3394#-:-NXnm-oSA-gUNe6jGgfk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
