### PR TITLE
Added corelib version validation when loading db.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6204)

### CODE REVIEW

**Review by maciektr — APPROVED** [review]
> Reviewed 7 of 11 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6204)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware and @mkaput)

**Review by piotmag769 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 11 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6204)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @mkaput, and @orizi)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 44 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6204#-O4A2bG17xMOp9bktH2c:-O4A2bG17xMOp9bktH2d:b-h1asxl) ([raw file](https://github.com/starkware-libs/cairo/blob/5abac98577e418f4ce02f66464f4018bdb2087b4/crates/cairo-lang-filesystem/src/db.rs#L44)):*
> ```XML
>     pub edition: Edition,
>     /// The crate's version.
>     pub version: Option<Version>,
> ```

This field is ignored for everything but corelib. Can we instead change `ProjectConfig` to

```rs
pub struct ProjectConfig {
    // ...
    pub corelib: CorelibConfiguration,
   // ...
}

pub struct CorelibConfiguration {
    pub root: Option<Directory>,
    pub version: Version,  // or `Option<Version>`
}
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6204)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 44 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6204#-O4A2bG17xMOp9bktH2c:-O4A49cI9KL6ISwDkg8w:bwiw3si) ([raw file](https://github.com/starkware-libs/cairo/blob/5abac98577e418f4ce02f66464f4018bdb2087b4/crates/cairo-lang-filesystem/src/db.rs#L44)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

This field is ignored for everything but corelib. Can we instead change `ProjectConfig` to

```rs
pub struct ProjectConfig {
    // ...
    pub corelib: CorelibConfiguration,
   // ...
}

pub struct CorelibConfiguration {
    pub root: Option<Directory>,
    pub version: Version,  // or `Option<Version>`
}
```
</blockquote></details>

currently only for it - but i see no good reason to actually separate.

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 2 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6204)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @mkaput, and @orizi)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 44 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6204#-O4A2bG17xMOp9bktH2c:-O4A4ucK6njYlaRplcC6:b3yeqxj) ([raw file](https://github.com/starkware-libs/cairo/blob/5abac98577e418f4ce02f66464f4018bdb2087b4/crates/cairo-lang-filesystem/src/db.rs#L44)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

currently only for it - but i see no good reason to actually separate.
</blockquote></details>

What other crate versions would you want to validate in the compiler? I think everything else should be responsibility of a package manager (Scarb), it mixes abstraction layers

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6204)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 44 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6204#-O4A2bG17xMOp9bktH2c:-O4A5rFD1AKm7rpx90-0:bg13vul) ([raw file](https://github.com/starkware-libs/cairo/blob/5abac98577e418f4ce02f66464f4018bdb2087b4/crates/cairo-lang-filesystem/src/db.rs#L44)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

What other crate versions would you want to validate in the compiler? I think everything else should be responsibility of a package manager (Scarb), it mixes abstraction layers
</blockquote></details>

i don't know what i would have wanted to check - but this specific check is due to the setup possibly changing the configuration.

if i cannot take the version from a specific crate - but only from the corelib - i won't be capable of checking anything.

Additionally, in the future, when `starknet` crate is extracted from `core` - it would require similar checks.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6204)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-compiler/src/db.rs` line 169 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6204#-O4A7N1-6FBez2d1iBFd:-O4A7N1-6FBez2d1iBFe:bv27ikq) ([raw file](https://github.com/starkware-libs/cairo/blob/5abac98577e418f4ce02f66464f4018bdb2087b4/crates/cairo-lang-compiler/src/db.rs#L169)):*
> ```XML
>         if let Some(config) = &self.project_config {
>             update_crate_roots_from_project_config(&mut db, config.as_ref());
>             if let Some(corelib) = &config.corelib {
> ```

@piotmag769  unless you claim the entire validation should only happen due to this setup.

if so - i don't really understand why this isn't being directly solved at scarb level.



_Code quote:_
```XML
            if let Some(corelib) = &config.corelib {
```

**Review by piotmag769 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6204)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @mkaput)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 44 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6204#-O4A2bG17xMOp9bktH2c:-O4A8X6s4DzwueID2gUQ:b-uxnq1h) ([raw file](https://github.com/starkware-libs/cairo/blob/5abac98577e418f4ce02f66464f4018bdb2087b4/crates/cairo-lang-filesystem/src/db.rs#L44)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i don't know what i would have wanted to check - but this specific check is due to the setup possibly changing the configuration.

if i cannot take the version from a specific crate - but only from the corelib - i won't be capable of checking anything.

Additionally, in the future, when `starknet` crate is extracted from `core` - it would require similar checks.
</blockquote></details>

Not a fan of that, but will unblock

**Review by piotmag769 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6204)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware, @mkaput, and @orizi)

___
*[`crates/cairo-lang-compiler/src/db.rs` line 169 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6204#-O4A7N1-6FBez2d1iBFd:-O4A8oJH0vCHX6ObXS7o:byn46nl) ([raw file](https://github.com/starkware-libs/cairo/blob/5abac98577e418f4ce02f66464f4018bdb2087b4/crates/cairo-lang-compiler/src/db.rs#L169)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

@piotmag769  unless you claim the entire validation should only happen due to this setup.

if so - i don't really understand why this isn't being directly solved at scarb level.
</blockquote></details>

This one is solved at Scarb level, so I didn't mean that

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:
:lgtm:

> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6204#-:-O4A4qCz5x18L_Cfq6DP:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput and @orizi)

**Pull request merged**
