### PR TITLE
Use GeneratedFileAuxData rather the attributes to find the generated …

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
…contract.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1927)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1927)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/contract.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1927#-NMhz6Rf7TGWiqrcWvOs:-NMhz6Rf7TGWiqrcWvOt:b-gu6ozt) ([raw file](https://github.com/starkware-libs/cairo/blob/e0c27f441122b270503fefda276d188e9af92743/crates/cairo-lang-starknet/src/contract.rs#L56)):*
> ```XML
>                 let Some(generated_info) = generated_info else { continue; };
>                 let Some(mapper) = generated_info.aux_data.0.as_any(
>                 ).downcast_ref::<DynDiagnosticMapper>() else { continue; };
> ```

Should I rename it to DynAuxData?



_Code quote:_
```XML
DynDiagnosticMapper
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/contract.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1927#-NMhzUep5lKtT0XlqrA2:-NMhzUep5lKtT0XlqrA3:b-1mmvvv) ([raw file](https://github.com/starkware-libs/cairo/blob/e0c27f441122b270503fefda276d188e9af92743/crates/cairo-lang-starknet/src/contract.rs#L52)):*
> ```XML
> 
>             // Note that we skip generated_file_info[0] because we are interested in modules
>             // that the plugin acted on and not modules that were created by the plugin.
> ```

The copy here:
https://github.com/starkware-libs/cairo/blob/87343ebab310a3fa0b7d85692aaf999da16ab4fe/crates/cairo-lang-defs/src/db.rs#L272

Is a bit annoying as it means the StarkNetAuxData is also located on all the submodules that were generated by the plugin.



_Code quote:_
```XML
            // Note that we skip generated_file_info[0] because we are interested in modules
            // that the plugin acted on and not modules that were created by the plugin.
```

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1927#-:-NMi5lEL6lXEROVZsl9P:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/contract.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1927#-NMhzUep5lKtT0XlqrA2:-NMi5VKcCZTKpO43WT6L:b-9blr3s) ([raw file](https://github.com/starkware-libs/cairo/blob/e0c27f441122b270503fefda276d188e9af92743/crates/cairo-lang-starknet/src/contract.rs#L52)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

The copy here:
https://github.com/starkware-libs/cairo/blob/87343ebab310a3fa0b7d85692aaf999da16ab4fe/crates/cairo-lang-defs/src/db.rs#L272

Is a bit annoying as it means the StarkNetAuxData is also located on all the submodules that were generated by the plugin.
</blockquote></details>

I'm not in context right now, Maybe we look at it together on Sunday?
___
*[`crates/cairo-lang-starknet/src/contract.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1927#-NMhz6Rf7TGWiqrcWvOs:-NMi5UQj613rbi4DaNHq:bb74ce2) ([raw file](https://github.com/starkware-libs/cairo/blob/e0c27f441122b270503fefda276d188e9af92743/crates/cairo-lang-starknet/src/contract.rs#L56)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Should I rename it to DynAuxData?
</blockquote></details>

Sure

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1927)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/contract.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1927#-NMhzUep5lKtT0XlqrA2:-NMiBc-q1VvL3xFe6r8X:bwn7fnr) ([raw file](https://github.com/starkware-libs/cairo/blob/e0c27f441122b270503fefda276d188e9af92743/crates/cairo-lang-starknet/src/contract.rs#L52)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I'm not in context right now, Maybe we look at it together on Sunday?
</blockquote></details>

sure, thanks for the review.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1927)* status: all files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/plugin.rs` line 39 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1927#-NN2ZzBR55Yu3rU-C57D:-NN2ZzBR55Yu3rU-C57E:b9ghqjd) ([raw file](https://github.com/starkware-libs/cairo/blob/5eb30df5e190c77317c4d2cd3040a53585cbdb3f/crates/cairo-lang-semantic/src/plugin.rs#L39)):*
> ```XML
> 
> #[derive(Clone, Debug)]
> pub struct DynPluginAuxData(pub Arc<dyn DiagnosticMapper>);
> ```

while you are here - can you please document the struct?
___
*[`crates/cairo-lang-starknet/src/contract.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1927#-NN2fsPr9SKUgHFwi4JQ:-NN2fsPr9SKUgHFwi4JR:b-62hq39) ([raw file](https://github.com/starkware-libs/cairo/blob/5eb30df5e190c77317c4d2cd3040a53585cbdb3f/crates/cairo-lang-starknet/src/contract.rs#L51)):*
> ```XML
> 
>             // Note that we skip generated_file_info[0] because we are interested in modules
>             // that the plugin acted on and not modules that were created by the plugin.
> ```

other way around?
Also (TOK) - maybe the original file should not be in "generated_file_info"?



_Code quote:_
```XML
 that the plugin acted on and not modules that were created by the plugin
```
___
*[`crates/cairo-lang-starknet/src/contract.rs` line 65 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1927#-NN2fnd_2LznsS4REjtt:-NN2fnd_2LznsS4REjtu:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5eb30df5e190c77317c4d2cd3040a53585cbdb3f/crates/cairo-lang-starknet/src/contract.rs#L65)):*
> ```XML
>                         contracts.push(ContractDeclaration { submodule_id });
>                     } else {
>                         panic!("{contract_name} was not found.");
> ```





_Suggestion:_
```XML
Contract `{contract_name}` was not found.
```
___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 42 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1927#-NN2_auv2Ooe6S7J6Y4_:-NN2_auv2Ooe6S7J6Y4a:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/5eb30df5e190c77317c4d2cd3040a53585cbdb3f/crates/cairo-lang-starknet/src/plugin.rs#L42)):*
> ```XML
> #[derive(Debug, PartialEq, Eq)]
> pub struct StarkNetContractAuxData {
>     patches: Patches,
> ```

doc
___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 44 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1927#-NN2_aFX7A8djsQYoddg:-NN2_aFYBWLsS6cLuy9C:b2ngwfe) ([raw file](https://github.com/starkware-libs/cairo/blob/5eb30df5e190c77317c4d2cd3040a53585cbdb3f/crates/cairo-lang-starknet/src/plugin.rs#L44)):*
> ```XML
>     patches: Patches,
> 
>     // A list of contracts that were processed by the plugin.
> ```

///
___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 48 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1927#-NN2_vQyCkibp6rk_Z7C:-NN2_vQyCkibp6rk_Z7D:bzcyg8s) ([raw file](https://github.com/starkware-libs/cairo/blob/5eb30df5e190c77317c4d2cd3040a53585cbdb3f/crates/cairo-lang-starknet/src/plugin.rs#L48)):*
> ```XML
> }
> impl GeneratedFileAuxData for StarkNetContractAuxData {
>     fn as_any(&self) -> &dyn std::any::Any {
> ```

TOK:
Can you please move all this to a separate file? Maybe plugin_utils.rs?
Same for StarkNetABIAuxData.



_Code quote:_
```XML
/// Contract related auxiliary data of the Starknet plugin.
#[derive(Debug, PartialEq, Eq)]
pub struct StarkNetContractAuxData {
    patches: Patches,

    // A list of contracts that were processed by the plugin.
    pub contracts: Vec<smol_str::SmolStr>,
}
impl GeneratedFileAuxData for StarkNetContractAuxData {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn eq(&self, other: &dyn GeneratedFileAuxData) -> bool {
        if let Some(other) = other.as_any().downcast_ref::<Self>() { self == other } else { false }
    }
}
impl AsDynGeneratedFileAuxData for StarkNetContractAuxData {
    fn as_dyn_macro_token(&self) -> &(dyn GeneratedFileAuxData + 'static) {
        self
    }
}
impl DiagnosticMapper for StarkNetContractAuxData {
    fn map_diag(
        &self,
        db: &(dyn SemanticGroup + 'static),
        diag: &dyn std::any::Any,
    ) -> Option<PluginMappedDiagnostic> {
        let Some(diag) = diag.downcast_ref::<SemanticDiagnostic>() else {return None;};
        let span = self
            .patches
            .translate(db.upcast(), diag.stable_location.diagnostic_location(db.upcast()).span)?;
        Some(PluginMappedDiagnostic { span, message: diag.format(db) })
    }
}
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1927)* status: 7 of 12 files reviewed, 2 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/plugin.rs` line 39 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1927#-NN2ZzBR55Yu3rU-C57D:-NN6-HDH9LUKXnZP1M9F:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/5eb30df5e190c77317c4d2cd3040a53585cbdb3f/crates/cairo-lang-semantic/src/plugin.rs#L39)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

while you are here - can you please document the struct?
</blockquote></details>

done.
___
*[`crates/cairo-lang-starknet/src/contract.rs` line 65 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1927#-NN2fnd_2LznsS4REjtt:-NN63n8I2p_l43wrbg7p:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/5eb30df5e190c77317c4d2cd3040a53585cbdb3f/crates/cairo-lang-starknet/src/contract.rs#L65)):*
> ```XML
>                         contracts.push(ContractDeclaration { submodule_id });
>                     } else {
>                         panic!("{contract_name} was not found.");
> ```

done.
___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 42 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1927#-NN2_auv2Ooe6S7J6Y4_:-NN63oQhAAPg2J0ALvoA:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/5eb30df5e190c77317c4d2cd3040a53585cbdb3f/crates/cairo-lang-starknet/src/plugin.rs#L42)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

doc
</blockquote></details>

done
___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 44 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1927#-NN2_aFX7A8djsQYoddg:-NN63q9Q7xzKoKwUIUNF:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/5eb30df5e190c77317c4d2cd3040a53585cbdb3f/crates/cairo-lang-starknet/src/plugin.rs#L44)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

///
</blockquote></details>

done
___
*[`crates/cairo-lang-starknet/src/plugin.rs` line 48 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1927#-NN2_vQyCkibp6rk_Z7C:-NN645qF38XNvWgmkWde:b-l61kgs) ([raw file](https://github.com/starkware-libs/cairo/blob/5eb30df5e190c77317c4d2cd3040a53585cbdb3f/crates/cairo-lang-starknet/src/plugin.rs#L48)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

TOK:
Can you please move all this to a separate file? Maybe plugin_utils.rs?
Same for StarkNetABIAuxData.
</blockquote></details>

added a TODO.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1927)* status: 7 of 12 files reviewed, 2 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/contract.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1927#-NN2fsPr9SKUgHFwi4JQ:-NN68z4yAO6rot3-haBY:bjtyqsq) ([raw file](https://github.com/starkware-libs/cairo/blob/5eb30df5e190c77317c4d2cd3040a53585cbdb3f/crates/cairo-lang-starknet/src/contract.rs#L51)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

other way around?
Also (TOK) - maybe the original file should not be in "generated_file_info"?
</blockquote></details>

I don't understand

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1927)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/plugin.rs` line 20 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1927#-NN6O7Xt1P2g479h3e7A:-NN6O7Xt1P2g479h3e7B:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/00b3fdf4a30dc75b86555da220a47045d36bfa52/crates/cairo-lang-semantic/src/plugin.rs#L20)):*
> ```XML
> /// A trait for Plugins auxiliary data.
> ///
> /// The can assist in mapping plugin generated diagnostics to more readable diagnostics.
> ```





_Suggestion:_
```XML
It can
```
___
*[`crates/cairo-lang-starknet/src/contract.rs` line 65 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1927#-NN2fnd_2LznsS4REjtt:-NN6OILdBnAd7O_B9QrH:bqxwxbn) ([raw file](https://github.com/starkware-libs/cairo/blob/5eb30df5e190c77317c4d2cd3040a53585cbdb3f/crates/cairo-lang-starknet/src/contract.rs#L65)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

done.
</blockquote></details>

You changed the wrong error message.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1927)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/plugin.rs` line 20 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1927#-NN6O7Xt1P2g479h3e7A:-NN6RC8xARH3m-IlZc_y:b37tz7d) ([raw file](https://github.com/starkware-libs/cairo/blob/00b3fdf4a30dc75b86555da220a47045d36bfa52/crates/cairo-lang-semantic/src/plugin.rs#L20)):*
> ```XML
> /// A trait for Plugins auxiliary data.
> ///
> /// The can assist in mapping plugin generated diagnostics to more readable diagnostics.
> ```

I decided to be a bit more explicit.



_Code quote:_
```XML
sist in mapp
```
___
*[`crates/cairo-lang-starknet/src/contract.rs` line 65 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1927#-NN2fnd_2LznsS4REjtt:-NN6RFOR9OPdpKQLfxaN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5eb30df5e190c77317c4d2cd3040a53585cbdb3f/crates/cairo-lang-starknet/src/contract.rs#L65)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

You changed the wrong error message.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1927)* status: 10 of 12 files reviewed, 2 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/plugin.rs` line 20 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1927#-NN6O7Xt1P2g479h3e7A:-NN7Wuvj60jQOro87hk8:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/00b3fdf4a30dc75b86555da220a47045d36bfa52/crates/cairo-lang-semantic/src/plugin.rs#L20)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I decided to be a bit more explicit.
</blockquote></details>

done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1927)* status: 9 of 12 files reviewed, 2 unresolved discussions (waiting on @orizi, @spapinistarkware, and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/contract.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1927#-NN2fsPr9SKUgHFwi4JQ:-NN7Zu0l0dBC4xYz70nh:buzlgzs) ([raw file](https://github.com/starkware-libs/cairo/blob/5eb30df5e190c77317c4d2cd3040a53585cbdb3f/crates/cairo-lang-starknet/src/contract.rs#L51)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't understand
</blockquote></details>

updated the comment.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/contract.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1927#-NN2fsPr9SKUgHFwi4JQ:-NN88F5lDIB1AqWO5dMC:bvi6iqk) ([raw file](https://github.com/starkware-libs/cairo/blob/5eb30df5e190c77317c4d2cd3040a53585cbdb3f/crates/cairo-lang-starknet/src/contract.rs#L51)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Much better - but I still don't understand:
the modules that plugins acted on are at [0]. The ones that are in [k] (k>0) are the ones that were generated by plugins, and not necessarily ones that plugins acted on.
</blockquote></details>

"the modules that plugins acted on are at [0]" does not make sense.

if the module with 'module_id' is in the original code than db.module_generated_file_info(*module_id)?[0] Is None.
if that module with 'module_id' was generated by a plugin than  db.module_generated_file_info(*module_id)?[0] hold the aux info that that was returned by the plugin when it generated the module.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/contract.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1927#-NN2fsPr9SKUgHFwi4JQ:-NN890ob6S64qm54s9Aq:bkf9da1) ([raw file](https://github.com/starkware-libs/cairo/blob/5eb30df5e190c77317c4d2cd3040a53585cbdb3f/crates/cairo-lang-starknet/src/contract.rs#L51)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

"the modules that plugins acted on are at [0]" does not make sense.

if the module with 'module_id' is in the original code than db.module_generated_file_info(*module_id)?[0] Is None.
if that module with 'module_id' was generated by a plugin than  db.module_generated_file_info(*module_id)?[0] hold the aux info that that was returned by the plugin when it generated the module.

</blockquote></details>

If  db.module_generated_file_info(*original_module_id)?[k] is Some(StarkNetContractAuxData) it means that the starknet plugin acted on the module with `original_module_id` and generated some code (Maybe this code has modules and maybe not)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1927)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/contract.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1927#-NN2fsPr9SKUgHFwi4JQ:-NN8Caby6HCjrJkcADBE:b-vzgca5) ([raw file](https://github.com/starkware-libs/cairo/blob/5eb30df5e190c77317c4d2cd3040a53585cbdb3f/crates/cairo-lang-starknet/src/contract.rs#L51)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

If  db.module_generated_file_info(*original_module_id)?[k] is Some(StarkNetContractAuxData) it means that the starknet plugin acted on the module with `original_module_id` and generated some code (Maybe this code has modules and maybe not)
</blockquote></details>

I think I'll just add the following example

mod A {
     #[contract]
     mod B {
          struct Storage {
                 c: felt,
           }
    
     }
}

Than (A, 1)  == (B, 0)  ==  (c, 0) == StarknetAuxInfo
Where the tuple is (module, file_info), and 'B' is the generated 'B' not the original one.

I want to do the lookup B inside A and not inside B or c.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1927)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/contract.rs` line 54 at r7](https://reviewable.io/reviews/starkware-libs/cairo/1927#-NN7jOP67qy3GK6KL0-l:-NNBFjWdB_uKxRy2IraM:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/70344ffe6701eb4d8b1edcf57b3a771fc647f6f7/crates/cairo-lang-starknet/src/contract.rs#L54)):*
> ```XML
>             // places:
>             //   a. db.module_generated_file_info(*module_id)?[k] (with k > 0).
>             //   b. db.module_generated_file_info(*generated_module_id)?[0].
> ```

done.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1927#-:-NNBHG4t5bR5C0Af2ku-:bnfp4nl)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/contract.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1927#-NN2fsPr9SKUgHFwi4JQ:-NNBGrDoAf0TGIHLq7Zq:b-l19eca) ([raw file](https://github.com/starkware-libs/cairo/blob/5eb30df5e190c77317c4d2cd3040a53585cbdb3f/crates/cairo-lang-starknet/src/contract.rs#L51)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I think I'll just add the following example

mod A {
     #[contract]
     mod B {
          struct Storage {
                 c: felt,
           }
    
     }
}

Than (A, 1)  == (B, 0)  ==  (c, 0) == StarknetAuxInfo
Where the tuple is (module, file_info), and 'B' is the generated 'B' not the original one.

I want to do the lookup B inside A and not inside B or c.

</blockquote></details>

OK, this example may be helpful, but c is unnecessary/confusing IMO.
I'd also rephrase that we want to "do the lookup for contracts (B) inside A's generated_file_infos and not inside B's".

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 4 of 9 files at r3, 3 of 5 files at r4, 1 of 1 files at r5, 1 of 2 files at r6, 1 of 2 files at r7, 2 of 2 files at r8, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1927)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
