### PR TITLE
Add safe dispatchers implementation

### PR DESCRIPTION
**Pull request by Arcticae**
This PR adds a _safe_ to call version of dispatchers, which is able to return a `Result` instead of unwrapping instantly, which will enable users to catch and handle errors on their own without the forced unwrap, and with convenience of dispatchers concept.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3591)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3591)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @Arcticae)

___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 352 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3591#-NZ_DNvL5IHzSp-vkDER:-NZ_DNvL5IHzSp-vkDES:b-8mh5dr) ([raw file](https://github.com/starkware-libs/cairo/blob/0d3133eeba336cf2cb2b723e60fff3b16895c85b/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L352)):*
> ```XML
>                     }}
>                 }}
>             }}
> ```

and then probably just merge with original func.



_Suggestion:_
```XML
            "$func_decl$ {{
                let mut {CALLDATA_PARAM_NAME} = traits::Default::default();
                $serialization_code$
                let mut ret_data = starknet::$syscall$(
                    self.$member$,
                    $entry_point_selector$,
                    array::ArrayTrait::span(@{CALLDATA_PARAM_NAME}),
                )?;
                Result::Ok(
                    $deserialization_code$
                )
            }}
```
___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 396 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3591#-NZ_CiFkEuwB7uNRljyt:-NZ_CiFkEuwB7uNRljyu:b-w9rame) ([raw file](https://github.com/starkware-libs/cairo/blob/0d3133eeba336cf2cb2b723e60fff3b16895c85b/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L396)):*
> ```XML
> }
> 
> fn safe_dispatcher_signature(
> ```

doc

also - maybe just add a bool to the original func.
___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 416 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3591#-NZ_CrKABuapWJRiUt_S:-NZ_CrKABuapWJRiUt_T:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0d3133eeba336cf2cb2b723e60fff3b16895c85b/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L416)):*
> ```XML
>         let previous_ret_type = RewriteNode::new_modified(return_type[1..2].into());
>         let new_ret_type = RewriteNode::interpolate_patched(
>             "Result<$ret_type$, Array<felt252>>",
> ```





_Suggestion:_
```XML
        let new_ret_type = RewriteNode::interpolate_patched(
            "starknet::SyscallResult<$ret_type$>",
```

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3591)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae)

___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3591#-NZ_L8hk-K2GTdQFBNen:-NZ_L8hk-K2GTdQFBNeo:b-saituh) ([raw file](https://github.com/starkware-libs/cairo/blob/0d3133eeba336cf2cb2b723e60fff3b16895c85b/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L59)):*
> ```XML
>     let base_name = trait_ast.name(db).text(db);
>     let dispatcher_trait_name = format!("{base_name}DispatcherTrait");
>     let safe_dispatcher_trait_name = format!("{base_name}SafeDispatcherTrait");
> ```

Does this have to be a separate trait? Cannot this just be a `try_*` method in `*DispatcherTrait` itself? I think that would be more idiomatic, at least in Rust terms.

**Review by Arcticae — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3591)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3591#-NZ_L8hk-K2GTdQFBNen:-NZ_PpS69BUYtKUoElTi:bg61wwk) ([raw file](https://github.com/starkware-libs/cairo/blob/0d3133eeba336cf2cb2b723e60fff3b16895c85b/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L59)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Does this have to be a separate trait? Cannot this just be a `try_*` method in `*DispatcherTrait` itself? I think that would be more idiomatic, at least in Rust terms.
</blockquote></details>

I was wondering if that's the way i should do it, i would actually rather prefer that. @orizi you have an opinion on that?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3591)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae and @mkaput)

___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3591#-NZ_L8hk-K2GTdQFBNen:-NZ_kTTW-AVv_J2dLqiQ:b-t9vin7) ([raw file](https://github.com/starkware-libs/cairo/blob/0d3133eeba336cf2cb2b723e60fff3b16895c85b/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L59)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

I was wondering if that's the way i should do it, i would actually rather prefer that. @orizi you have an opinion on that?
</blockquote></details>

i'm not sure myself - in the end it would be nice if the dispatcher would implement the basic ABI trait itself - but i don't know yet.

**Review by Arcticae — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3591)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3591#-NZ_L8hk-K2GTdQFBNen:-NZa3t5K-azI4UuERI6g:b-ipug57) ([raw file](https://github.com/starkware-libs/cairo/blob/0d3133eeba336cf2cb2b723e60fff3b16895c85b/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L59)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i'm not sure myself - in the end it would be nice if the dispatcher would implement the basic ABI trait itself - but i don't know yet.
</blockquote></details>

Our team seems to be pretty confident to leave this as-is (meaning generating 2 separate SafeDispatcher & Dispatcher traits).
___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 352 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3591#-NZ_DNvL5IHzSp-vkDER:-NZa3qGP9lErZr5Wvgvy:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0d3133eeba336cf2cb2b723e60fff3b16895c85b/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L352)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

and then probably just merge with original func.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 396 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3591#-NZ_CiFkEuwB7uNRljyt:-NZa3rO3-zVYttx7lySG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0d3133eeba336cf2cb2b723e60fff3b16895c85b/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L396)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc

also - maybe just add a bool to the original func.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 416 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3591#-NZ_CrKABuapWJRiUt_S:-NZa3roj0sZPo2T40_Ky:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0d3133eeba336cf2cb2b723e60fff3b16895c85b/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L416)):*
> ```XML
>         let previous_ret_type = RewriteNode::new_modified(return_type[1..2].into());
>         let new_ret_type = RewriteNode::interpolate_patched(
>             "Result<$ret_type$, Array<felt252>>",
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3591)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @Arcticae and @mkaput)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/dispatcher` line 99 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3591#-NZa6lDL1gB4yB8DKyQR:-NZa6lDL1gB4yB8DKyQS:bue44la) ([raw file](https://github.com/starkware-libs/cairo/blob/1952e269b342bce96a4ae6a20c015afb98f446b6/crates/cairo-lang-starknet/src/plugin/plugin_test_data/dispatcher#L99)):*
> ```
>     
>             let mut ret_data = starknet::SyscallResultTrait::unwrap_syscall(ret_data);
>             
> ```

try to remove the generated whitespace

**Review by Arcticae — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3591)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/dispatcher` line 99 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3591#-NZa6lDL1gB4yB8DKyQR:-NZaDveK5Lj_5GxnG3od:b8xpwhg) ([raw file](https://github.com/starkware-libs/cairo/blob/1952e269b342bce96a4ae6a20c015afb98f446b6/crates/cairo-lang-starknet/src/plugin/plugin_test_data/dispatcher#L99)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

try to remove the generated whitespace
</blockquote></details>

I had a go at it, formatting is not ideal, but seems close enough now to the normal dispatchers :grimacing: 
LMK if i should dive further into correcting the formatting, although it will require more complicated generation logic

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3591)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @Arcticae and @mkaput)

___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 302 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3591#-NZarbJ294UyQrFuVGX5:-NZarbJ294UyQrFuVGX6:bxmtgvq) ([raw file](https://github.com/starkware-libs/cairo/blob/0263f42a0ed46b82d97a0c5d8285dbe2586e9b69/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L302)):*
> ```XML
>     let deserialization_code = if ret_decode.is_empty() {
>         RewriteNode::Text(String::from(if unwrap {
>             "()\
> ```

it still seems the spacing is completely different than before.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3591)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @Arcticae and @mkaput)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/dispatcher` line 99 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3591#-NZa6lDL1gB4yB8DKyQR:-NZarjQDDWzGXtEJP-v8:batmaml) ([raw file](https://github.com/starkware-libs/cairo/blob/1952e269b342bce96a4ae6a20c015afb98f446b6/crates/cairo-lang-starknet/src/plugin/plugin_test_data/dispatcher#L99)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

I had a go at it, formatting is not ideal, but seems close enough now to the normal dispatchers :grimacing: 
LMK if i should dive further into correcting the formatting, although it will require more complicated generation logic
</blockquote></details>

this stopped looking similarly to a normal function formating

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3591#-:-NZeQ2ftAh3wGmtstbq6:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3591)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Arcticae and @mkaput)

___
*[`crates/cairo-lang-starknet/src/plugin/dispatcher.rs` line 315 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3591#-NZewt8s5JnwnYVExszS:-NZewt8s5JnwnYVExszT:bfhf3dy) ([raw file](https://github.com/starkware-libs/cairo/blob/0d57a80562783090237011d97d6133f91c538bd9/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L315)):*
> ```XML
>             }
>         )
>     };
> ```

i think this should work



_Suggestion:_
```XML

/// Returns the method implementation rewrite node for a declaration.
fn declaration_method_impl(
    func_declaration: RewriteNode,
    entry_point_selector: RewriteNode,
    member: &str,
    syscall: &str,
    serialization_code: Vec<RewriteNode>,
    ret_decode: String,
    unwrap: bool,
) -> RewriteNode {
    let deserialization_code = if ret_decode.is_empty() {
        RewriteNode::Text("()".to_string())
    } else {
        RewriteNode::Text(
            if unwrap {
                ret_decode.clone()
            } else {
                ret_decode.split("\n").map(|x| format!("    {x}")).join("\n")
            }
        )
    };
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3591#-:-NZex5iqEUHbSrWkiRup:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3591)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Arcticae)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3591)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Arcticae)

**Pull request merged**
