### PR TITLE
Added derive for Destruct trait.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #2596
- #2594 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2594)

### CODE REVIEW

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2594)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-plugins/src/test_data/derive` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2594#-NRS61C7AnqRNIjZhNZ8:-NRS61C7AnqRNIjZhNZ9:b-4tdyk8) ([raw file](https://github.com/starkware-libs/cairo/blob/188786131e4de88462606a8b4626736278a8562e/crates/cairo-lang-plugins/src/test_data/derive#L59)):*
> ```
> impl TwoMemberStructDestruct of Destruct::<TwoMemberStruct> {
>     fn destruct(self: TwoMemberStruct) nopanic {
>         self.a.destruct();
> ```

Now, I wonder if .destruct() is the right thing to use here, and not something like ::core::traits::Destruct::destruct, to make sure noone is doing something funny. Probably not that crucial for now, but we should think about it.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2594)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-plugins/src/test_data/derive` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2594#-NRS61C7AnqRNIjZhNZ8:-NRS6Htm5mhIRS960owc:bd7n51n) ([raw file](https://github.com/starkware-libs/cairo/blob/188786131e4de88462606a8b4626736278a8562e/crates/cairo-lang-plugins/src/test_data/derive#L59)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Now, I wonder if .destruct() is the right thing to use here, and not something like ::core::traits::Destruct::destruct, to make sure noone is doing something funny. Probably not that crucial for now, but we should think about it.
</blockquote></details>

Also, it might give a better error message if the trait is not imported?

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2594#-:-NRS6Ptx5RNNOy_bRFaF:bnfp4nl)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2594)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2594)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-plugins/src/test_data/derive` line 59 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2594#-NRS61C7AnqRNIjZhNZ8:-NRT89ZV2EWSOBIbon_5:byj5bc4) ([raw file](https://github.com/starkware-libs/cairo/blob/e489bdf573c1d6673b1ff803d5d2ac0f24813682/crates/cairo-lang-plugins/src/test_data/derive#L59)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Also, it might give a better error message if the trait is not imported?
</blockquote></details>

sg - will use fully qualified name, but without the core:: for now.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2594#-:-NRT_zRE6HiCUM6hYNsc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
