### PR TITLE
Fix `core` edition in `init_dev_corelib`

### PR DESCRIPTION
**Pull request by mkaput**
**Stack**:
- #5987
- #5991 ⬅
- #5986

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5991)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5991)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mkaput)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5991#-O1QQq9g2HDVlThHXDlL:-O1QQq9g2HDVlThHXDlM:b1ejfvj) (no related file):*
target dev-v2.7.0

if must have on main as well - add a cherry-pick PR later.

___

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5991)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5991#-O1QQq9g2HDVlThHXDlL:-O1QWh2_87zdaW80tcrM:bd69rjx) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

target dev-v2.7.0

if must have on main as well - add a cherry-pick PR later.
</blockquote></details>

https://github.com/starkware-libs/cairo/pull/5994

___

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5991)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mkaput)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5991#-O1QQq9g2HDVlThHXDlL:-O1QXoS84prGlAmABgie:b-2fhalc) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

https://github.com/starkware-libs/cairo/pull/5994
</blockquote></details>

close this PR so the next one would an actual cherry-pick.

___

**Comment by mkaput** [comment]
Closing pull request: commit has gone away

**Pull request closed without merging**
