### PR TITLE
Split TestCompilation struct into program and metadata

### PR DESCRIPTION
**Pull request by maciektr**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5803)

### CODE REVIEW

**Review by maciektr — COMMENTED** [review]
Rationale: Some tooling may only care about produced Sierra program and disregard all the cairo-test specific metadata (like Cairo profiler). This change allows for easier decoupling of such tools from the metadata structure (e.g. both can be serialized into separate files).

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5803#-:-O-Kxs-825zRR_Y39Zpp:bt5k6pb)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @mkaput and @orizi)

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5803#-:-O-LAJRT-I9N7Y6lKD0J:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by maciektr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5803)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 144 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5803#-O-LCHLNBWmevREUIAfl:-O-LIKjN9jyoQ9SCl6cX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e29ac497ca0fcf230aed25a4c078b7569c235cf8/crates/cairo-lang-test-plugin/src/lib.rs#L144)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5803#-O-LCJ5s65gHTKlhPfkT:-O-LIKxK2xeCkbQKDnyZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e29ac497ca0fcf230aed25a4c078b7569c235cf8/crates/cairo-lang-test-plugin/src/lib.rs#L150)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 163 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5803#-O-LCS489qnOWOu49Njr:-O-LILVM5gcdfbZSTks1:b-qws1gb) ([raw file](https://github.com/starkware-libs/cairo/blob/e29ac497ca0fcf230aed25a4c078b7569c235cf8/crates/cairo-lang-test-plugin/src/lib.rs#L163)):*
Well, I think it's debatable :D I see it as metadata in a sense that it describes the test cases (from a sierra program), but I also see why you would argue it's not. 
I am happy to change it to other name if you have an idea for one (`TestCompilationConfig`? Whichever you prefer). 


Btw. GPT-4 says it is :laughing: 
> Semantically, is a program configuration seen as metadata?

In the broad sense, metadata is data about data. It provides information about other data, allowing for improved understanding, sorting, and manipulating the primary data.

Program configuration can be seen as a form of metadata from this perspective. It's data that describes how a software program should operate rather than the data the program processes. (...)

So yes, you can consider a program configuration as metadata as it provides additional descriptive and functional information about the program's operation and not about the information being processed by the program itself.

**Comment by maciektr** [comment]
Yes, but the point of this change is to share a single compiled file between the two with the recompilation. I want to separate the universal stuff (ProgramArtifact) on which all the tooling can rely from the cairo-test specific ones that can change from version to version (and we don't really want to deserialize them anywhere other than the cairo-test itself). Do you think it makes sense?

**Review by mkaput — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5803)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5803#-:-O-MWhXv7WArzkFLeF2I:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @maciektr)

**Pull request merged**
