### PR TITLE
Remove dict read/write and replace it by entry calls in the high leve…

### PR DESCRIPTION
**Pull request by gilbens-starkware**
…l trait.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2981)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2981)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2981#-NUHQaB07PRCvezkuCKZ:-NUHQaB07PRCvezkuCK_:b-lefas8) (no related file):*
Change target branch.

___

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2981)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2981#-NUHSUBi2iI9Bxmh4AkD:-NUHSUBj4CuYk3wcSqwj:bvuykhb) (no related file):*
Remove read/write from whitelists.

___
___
*[`corelib/src/dict.cairo` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2981#-NUHSvb32rPRjoIxQOR_:-NUHSvb32rPRjoIxQORa:b-8dauki) ([raw file](https://github.com/starkware-libs/cairo/blob/bf751874a799a06bcc0dc2bc31742ee4c14df948/corelib/src/dict.cairo#L37)):*
> ```Cairo
> impl Felt252DictImpl<T,
> impl TDefault: Felt252DictValue<T>,
> impl TDestruct: Destruct<T>> of Felt252DictTrait<T> {
> ```

Check which function requires this, and why (I know `set` needs it to destruct the previous value).

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2981)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware)

___
*[`corelib/src/dict.cairo` line 41 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2981#-NUHT9fM9Bfy6gkE8xa7:-NUHT9fM9Bfy6gkE8xa8:bt3v5ee) ([raw file](https://github.com/starkware-libs/cairo/blob/bf751874a799a06bcc0dc2bc31742ee4c14df948/corelib/src/dict.cairo#L41)):*
> ```Cairo
>         felt252_dict_new()
>     }
>     #[inline(always)]
> ```

Put a blank line between functions.
___
*[`corelib/src/dict.cairo` line 43 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2981#-NUHTCPVCDS39vMKJVbC:-NUHTCPVCDS39vMKJVbD:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/bf751874a799a06bcc0dc2bc31742ee4c14df948/corelib/src/dict.cairo#L43)):*
> ```Cairo
>     #[inline(always)]
>     fn insert(ref self: Felt252Dict<T>, key: felt252, value: T) {
>         let (entry, prev_value) = felt252_dict_entry_get(self, key);
> ```





_Suggestion:_
```Cairo
        let (entry, _prev_value) = felt252_dict_entry_get(self, key);
```

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2981)* status: 1 of 5 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware)

___
*[`corelib/src/dict.cairo` line 38 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2981#-NUHTgMT7M6aMA8GASvF:-NUHTgMT7M6aMA8GASvG:busjgem) ([raw file](https://github.com/starkware-libs/cairo/blob/bf751874a799a06bcc0dc2bc31742ee4c14df948/corelib/src/dict.cairo#L38)):*
> ```Cairo
> impl TDefault: Felt252DictValue<T>,
> impl TDestruct: Destruct<T>> of Felt252DictTrait<T> {
>     fn new() -> Felt252Dict<T> {
> ```

inline always?
___
*[`corelib/src/dict.cairo` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2981#-NUHTNhWD0fhNXhBB8cN:-NUHTNhX-pSGPEfAR-6T:bzepims) ([raw file](https://github.com/starkware-libs/cairo/blob/bf751874a799a06bcc0dc2bc31742ee4c14df948/corelib/src/dict.cairo#L46)):*
> ```Cairo
>         self = felt252_dict_entry_finalize(entry, value);
>     }
>     /// Notice that this function implicitly requires T to be destructable.
> ```

Explain why.

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2981)* status: 4 of 5 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware)

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2981)* status: 4 of 5 files reviewed, 8 unresolved discussions (waiting on @gilbens-starkware)

___
*[`tests/e2e_test_data/libfuncs/felt252_dict` line 90 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2981#-NUHVPKaDgEbBYq9zzUt:-NUHVPKaDgEbBYq9zzUu:b-gqryup) ([raw file](https://github.com/starkware-libs/cairo/blob/e0549465211403b875d49aa6182430338d12c0a0/tests/e2e_test_data/libfuncs/felt252_dict#L90)):*
> ```
> dict_tracker = __dict_manager.get_tracker(memory[fp + -5])
> memory[memory[fp + -5] + 1] = dict_tracker.data[memory[fp + -4]]
> dict_tracker.current_ptr += 3
> ```

This line is missing.

**Review by liorgold2 — COMMENTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2981)* status: all files reviewed, 8 unresolved discussions (waiting on @gilbens-starkware)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2981)* status: 1 of 14 files reviewed, 8 unresolved discussions (waiting on @liorgold2)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2981#-NUHSUBi2iI9Bxmh4AkD:-NUHWhluC1srgC4gO9K-:b-896fix) (no related file):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Remove read/write from whitelists.
</blockquote></details>

Done.

___
___
*[`corelib/src/dict.cairo` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2981#-NUHSvb32rPRjoIxQOR_:-NUHWrKXCLkemq_gQrv4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bf751874a799a06bcc0dc2bc31742ee4c14df948/corelib/src/dict.cairo#L37)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Check which function requires this, and why (I know `set` needs it to destruct the previous value).
</blockquote></details>

Done.
___
*[`corelib/src/dict.cairo` line 38 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2981#-NUHTgMT7M6aMA8GASvF:-NUHai-mA6gtz3ZkB-ab:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bf751874a799a06bcc0dc2bc31742ee4c14df948/corelib/src/dict.cairo#L38)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

inline always?
</blockquote></details>

Done.
___
*[`corelib/src/dict.cairo` line 41 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2981#-NUHT9fM9Bfy6gkE8xa7:-NUHX8Mh7Ul1wdwKyENO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bf751874a799a06bcc0dc2bc31742ee4c14df948/corelib/src/dict.cairo#L41)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Put a blank line between functions.
</blockquote></details>

Done.
___
*[`corelib/src/dict.cairo` line 43 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2981#-NUHTCPVCDS39vMKJVbC:-NUHXC8kBvIqArbZcwXf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bf751874a799a06bcc0dc2bc31742ee4c14df948/corelib/src/dict.cairo#L43)):*
> ```Cairo
>     #[inline(always)]
>     fn insert(ref self: Felt252Dict<T>, key: felt252, value: T) {
>         let (entry, prev_value) = felt252_dict_entry_get(self, key);
> ```

Done.
___
*[`corelib/src/dict.cairo` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2981#-NUHTNhWD0fhNXhBB8cN:-NUHXBtl6sIOjX5_tfss:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bf751874a799a06bcc0dc2bc31742ee4c14df948/corelib/src/dict.cairo#L46)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Explain why.
</blockquote></details>

Done.
___
*[`tests/e2e_test_data/libfuncs/felt252_dict` line 90 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2981#-NUHVPKaDgEbBYq9zzUt:-NUHajW80XwVrqlue0kW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e0549465211403b875d49aa6182430338d12c0a0/tests/e2e_test_data/libfuncs/felt252_dict#L90)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

This line is missing.
</blockquote></details>

Done.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r2, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2981)* status: all files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 121 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2981#-NUHmqzB9yPJqEFixtMG:-NUHmqzB9yPJqEFixtMH:b-krb45d) ([raw file](https://github.com/starkware-libs/cairo/blob/e0549465211403b875d49aa6182430338d12c0a0/crates/cairo-lang-casm/src/hints/mod.rs#L121)):*
> ```XML
>         segment_arena_ptr: ResOperand,
>     },
>     /// Retrieves and writes the value corresponding to the given dict and key from the vm
> ```

Revert removing them, and mark them as deprecated.
___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 317 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2981#-NUHn4Ax1iQLMcKilyH7:-NUHn4Ax1iQLMcKilyH8:b-wu6acq) ([raw file](https://github.com/starkware-libs/cairo/blob/e0549465211403b875d49aa6182430338d12c0a0/crates/cairo-lang-casm/src/hints/mod.rs#L317)):*
> ```XML
>             }
>             CoreHint::Felt252DictWrite { dict_ptr, key, value } => {
>                 let (dict_ptr, key, value) = (
> ```

Remove the implementation of the old hints, and replace them with `unimplemented` or something like that.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 866 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2981#-NUHlEKz40WBXy6fGa8_:-NUHlEKz40WBXy6fGa8a:b-ddrcm2) ([raw file](https://github.com/starkware-libs/cairo/blob/e0549465211403b875d49aa6182430338d12c0a0/crates/cairo-lang-runner/src/casm_run/mod.rs#L866)):*
> ```XML
>             vm.insert_value((dict_infos_base + 3 * n_dicts)?, new_dict_segment)?;
>         }
>         CoreHint::Felt252DictRead { dict_ptr, key, value_dst } => {
> ```

Don't remove these hints so that we can run contracts that were compiled using previous versions.
___
*[`crates/cairo-lang-starknet/src/allowed_libfuncs_lists/testnet_v0.1.0.json` line 36 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2981#-NUHlubnDkjWIDf9U0rv:-NUHlubnDkjWIDf9U0rw:bshtlk3) ([raw file](https://github.com/starkware-libs/cairo/blob/1f261bcdb5f31b37b29a19b603ed1b530f964719/crates/cairo-lang-starknet/src/allowed_libfuncs_lists/testnet_v0.1.0.json#L36)):*
> ```JSON
>         "felt252_add",
>         "felt252_const",
>         "felt252_dict_new",
> ```

Add `entry_get` and `entry_finalize`.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2981)* status: 10 of 14 files reviewed, 5 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 121 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2981#-NUHmqzB9yPJqEFixtMG:-NUHoSeL9tB-rnEC7tPC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e0549465211403b875d49aa6182430338d12c0a0/crates/cairo-lang-casm/src/hints/mod.rs#L121)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Revert removing them, and mark them as deprecated.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 317 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2981#-NUHn4Ax1iQLMcKilyH7:-NUHoLE54SrIWzy6_S7j:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e0549465211403b875d49aa6182430338d12c0a0/crates/cairo-lang-casm/src/hints/mod.rs#L317)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Remove the implementation of the old hints, and replace them with `unimplemented` or something like that.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/allowed_libfuncs_lists/testnet_v0.1.0.json` line 36 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2981#-NUHlubnDkjWIDf9U0rv:-NUHoKPfAQUon_dc2N9X:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1f261bcdb5f31b37b29a19b603ed1b530f964719/crates/cairo-lang-starknet/src/allowed_libfuncs_lists/testnet_v0.1.0.json#L36)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Add `entry_get` and `entry_finalize`.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 866 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2981#-NUHlEKz40WBXy6fGa8_:-NUHoKtF7xOvDuuMXv9q:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e0549465211403b875d49aa6182430338d12c0a0/crates/cairo-lang-runner/src/casm_run/mod.rs#L866)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Don't remove these hints so that we can run contracts that were compiled using previous versions.
</blockquote></details>

Done.

**Review by liorgold2 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2981)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`corelib/src/dict.cairo` line 31 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2981#-NUIkyZH3krnCyygR8G6:-NUIkyZH3krnCyygR8G7:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a319ff047bc307d35b86c4671ab724bc3b4dc697/corelib/src/dict.cairo#L31)):*
> ```Cairo
>     fn new() -> Felt252Dict<T>;
>     /// Insert requires the destruct trait to be implemented as the previous value is dropped.
>     fn insert<impl TDestruct: Destruct<T>>(ref self: Felt252Dict<T>, key: felt252, value: T);
> ```





_Suggestion:_
```Cairo
    /// Inserts the given value for the given key.
    ///
    /// Requires the `Destruct` trait, as the previous value is dropped.
    fn insert<impl TDestruct: Destruct<T>>(ref self: Felt252Dict<T>, key: felt252, value: T);
    /// Returns a copy of the value at the given key.
    ///
    /// Requires the `Copy` trait.
```
___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 121 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2981#-NUIkguBCoA1xMOeyOtv:-NUIkguBCoA1xMOeyOtw:b-2uc5ym) ([raw file](https://github.com/starkware-libs/cairo/blob/a319ff047bc307d35b86c4671ab724bc3b4dc697/crates/cairo-lang-casm/src/hints/mod.rs#L121)):*
> ```XML
>         segment_arena_ptr: ResOperand,
>     },
>     /// Deprecated. Left for backwards compatibility for deployed contracts.
> ```

Same below.



_Suggestion:_
```XML
    /// Deprecated. Left for backward compatibility of previously deployed contracts.
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2981)* status: 12 of 14 files reviewed, 3 unresolved discussions (waiting on @liorgold2)

___
*[`corelib/src/dict.cairo` line 31 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2981#-NUIkyZH3krnCyygR8G6:-NUL7lxv5vdptmU9mPaK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a319ff047bc307d35b86c4671ab724bc3b4dc697/corelib/src/dict.cairo#L31)):*
> ```Cairo
>     fn new() -> Felt252Dict<T>;
>     /// Insert requires the destruct trait to be implemented as the previous value is dropped.
>     fn insert<impl TDestruct: Destruct<T>>(ref self: Felt252Dict<T>, key: felt252, value: T);
> ```

Done.
___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 121 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2981#-NUIkguBCoA1xMOeyOtv:-NUL7mP10sQKki8P64h-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a319ff047bc307d35b86c4671ab724bc3b4dc697/crates/cairo-lang-casm/src/hints/mod.rs#L121)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Same below.
</blockquote></details>

Done.

**Review by liorgold2 — APPROVED** [review]
> Reviewed 10 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2981)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2981#-:-NULUqr66Lcshk8pRBY_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
