### PR TITLE
Added support for should_panic with a tuple of strings and felts

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4268)

### CODE REVIEW

**Comment by yuvalsw** [comment]
change target

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4268)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-test-plugin/src/test_config.rs` line 197 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4268#-NgxV-Pw8a3da7dFWEKQ:-NgxV-Pw8a3da7dFWEKR:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/fcb233e599bcfa07b2f3fd5ee9f16469f95c63b0/crates/cairo-lang-test-plugin/src/test_config.rs#L197)):*
> ```XML
>         ast::Expr::String(panic_string) => Some(extract_string_panic_bytes(panic_string, db)),
>         _ => None,
>     }
> ```





_Suggestion:_
```XML
        }
        ast::Expr::String(panic_string) => Some(extract_string_panic_bytes(panic_string, db)),
        ast::Expr::Literal(panic_value) => Some(vec![panic_value.numeric_value(db).unwrap_or_default().into()]),
        ast::Expr::ShortString(panic_value) => Some(vec![panic_value.numeric_value(db).unwrap_or_default().into()]),
        _ => None,
    }
```

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4268#-:-Ngxrgt4EXG5l2XU9fKW:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4268)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
