### PR TITLE
Enable negative impls in test crates.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4520)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4520)* status: 6 of 10 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/cairo_project.toml` line 11 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4520#-NkzZKRY8M2T0mKsG4Cj:-NkzZKRY8M2T0mKsG4Ck:b-p9jpu4) ([raw file](https://github.com/starkware-libs/cairo/blob/639d6344ad0c308a020fb1c70dc486e9a296d817/corelib/cairo_project.toml#L11)):*
> ```TOML
> 
> [config.override.core.experimental_features]
> negative_impls = true
> ```

should this work?



_Suggestion:_
```TOML
[config.global]
edition = "2023_11"

[config.global.experimental_features]
negative_impls = true
```
___
*[`crates/cairo-lang-compiler/src/db.rs` line 153 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4520#-NkzZcneCayI6vZ7Ip0e:-NkzZcneCayI6vZ7Ip0f:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/639d6344ad0c308a020fb1c70dc486e9a296d817/crates/cairo-lang-compiler/src/db.rs#L153)):*
> ```XML
>                         root: corelib,
>                         settings: CrateSettings {
>                             edition: Edition::default(),
> ```





_Suggestion:_
```XML
                        settings: CrateSettings {
                            edition: Edition::V202311,
```
___
*[`crates/cairo-lang-filesystem/src/db.rs` line 154 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4520#-NkzZkko804Zimu6TaFb:-NkzZkko804Zimu6TaFc:bipd9yc) ([raw file](https://github.com/starkware-libs/cairo/blob/639d6344ad0c308a020fb1c70dc486e9a296d817/crates/cairo-lang-filesystem/src/db.rs#L154)):*
> ```XML
>             root: core_root_dir,
>             settings: CrateSettings {
>                 edition: Edition::default(),
> ```

202311
___
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/neg_impl` line 36 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4520#-NkzZz7B3PR85kFBrSC1:-NkzZz7B3PR85kFBrSC2:bgxputi) ([raw file](https://github.com/starkware-libs/cairo/blob/e2a0971e64cb7a59a28371f8352cd4dd2b15093d/crates/cairo-lang-semantic/src/diagnostic_test_data/neg_impl#L36)):*
> ```
> //! > expected_diagnostics
> error: Negative impls are supported only inside the core lib.
>  --> lib.cairo:4:18
> ```

don't we want to test the error as well?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-semantic/src/diagnostic_test_data/neg_impl` line 36 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4520#-NkzZz7B3PR85kFBrSC1:-Nl2EB1KA-15MX-YjhMK:bjq2pd5) ([raw file](https://github.com/starkware-libs/cairo/blob/e2a0971e64cb7a59a28371f8352cd4dd2b15093d/crates/cairo-lang-semantic/src/diagnostic_test_data/neg_impl#L36)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

don't we want to test the error as well?
</blockquote></details>

I think it is not worth the effort.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 9 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4520#-:-Nl2KPocBDEnA7jrQULQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`corelib/cairo_project.toml` line 11 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4520#-NkzZKRY8M2T0mKsG4Cj:-Nl2Bxem53Qle7gtOioC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/639d6344ad0c308a020fb1c70dc486e9a296d817/corelib/cairo_project.toml#L11)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

should this work?
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4520)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
