### PR TITLE
feat(corelib): OptionTrait::ok_or_else

### PR DESCRIPTION
**Pull request by julio4**
Transforms the `Option<T>` into a `Result<T, E>`, mapping `Option::Some(v)` to
`Result::Ok(v)` and `Option::None` to `Result::Err(err())`.

Also add missing tests for `OptionTrait::ok_or`

#### Examples

```cairo
assert_eq!(Option::Some('foo').ok_or_else(|| 0), Result::Ok('foo'));

let option: Option<felt252> = Option::None;
assert_eq!(option.ok_or_else(|| 0), Result::Err(0));
```

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6930)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @julio4)

___
*[`corelib/src/option.cairo` line 208 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6930#-OEz6Cvd8C8XbiaimJ8f:-OEz6Cvd8C8XbiaimJ8g:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2a7edf6487c62a77289031389deaa370f4e4427f/corelib/src/option.cairo#L208)):*
> ```Cairo
>         +Destruct<E>,
>         impl func: core::ops::FnOnce<F, ()>[Output: E],
>         +Drop<func::Output>,
> ```





_Suggestion:_
```Cairo
        E,
        F,
        +core::ops::FnOnce<F, ()>[Output: E],
        +Destruct<E>,
        +Drop<F>,
```

**Review by enitrat — COMMENTED** [review]
@julio4 can you add the module-level docs, in the # Methods Overview for the new functions you introduce in the `Option` (or `Result`) please 🙏

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6930#-:-OEzo164AX1n6fV6rGEi:btqlju)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @julio4 and @orizi)

**Comment by julio4** [comment]
*[`corelib/src/option.cairo` line 208 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6930#-OEz6Cvd8C8XbiaimJ8f:-OEzrhVB3-qtUawGDOXY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2a7edf6487c62a77289031389deaa370f4e4427f/corelib/src/option.cairo#L208)):*
> ```Cairo
>         +Destruct<E>,
>         impl func: core::ops::FnOnce<F, ()>[Output: E],
>         +Drop<func::Output>,
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6930#-:-OF0sV8P1yEI2op9vPUd:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @julio4)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6930#-OF0sQCv18viOc6SqyPv:-OF0sQCv18viOc6SqyPw:bl3aonu) (no related file):*
@TomerStarkware for 2nd eye.

**Review by TomerStarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6930#-:-OF1k7PB7ecAo4XFXFIj:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @julio4)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6930)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @julio4)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6930#-OF1ysO3EJg_pev8cIQb:-OF1ysO3EJg_pev8cIQc:b8o690t) (no related file):*
just waiting for @enitrat 's approval.

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6930)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @julio4)

**Pull request merged**
