### PR TITLE
Split contract and component code to different files

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3932)

### CODE REVIEW

**Comment by yuvalsw** [comment]
change target branch

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3932)* status: 1 of 8 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3932#-NcGpCl30X8xgyYO2Qr4:-NcGpCl30X8xgyYO2Qr5:buyuyya) (no related file):*
waiting for the rebase - as some major code is gonna change due to the rebase.

___

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3932)* status: 1 of 8 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3932#-NcGpCl30X8xgyYO2Qr4:-NcINbjIENvHMZppoDLj:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

waiting for the rebase - as some major code is gonna change due to the rebase.
</blockquote></details>

Done.

___

**Review by orizi — COMMENTED** [review]
Nm, got confused be reviewable

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3932#-:-NcLwdQW3jugFypEsTco:bhte124)* status: 1 of 8 files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3932#-:-NcLxk_N8yQKn6sf7Rdq:bnfp4nl)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 88 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3932#-NcLxYir7Q-VDvFt3qqp:-NcLxYir7Q-VDvFt3qqq:b2nhdkj) ([raw file](https://github.com/starkware-libs/cairo/blob/210525bffef370005c54d7d6f93dd0b58122a26b/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L88)):*
> ```XML
> }
> 
> pub(super) fn generate_contract_specific_code(
> ```

Doc

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 8 files at r1, 4 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3932)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3932)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs` line 88 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3932#-NcLxYir7Q-VDvFt3qqp:-NcM8ygdCrf1V4-vI4FA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/210525bffef370005c54d7d6f93dd0b58122a26b/crates/cairo-lang-starknet/src/plugin/starknet_module/contract.rs#L88)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Doc
</blockquote></details>

Done.

**Pull request merged**
