### PR TITLE
Made error message for entry point be dependent on failing var.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3740)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3740#-Na1vzBi25tm0wybT5YG:-Na1vzBi25tm0wybT5YH:b-nkm4un) ([raw file](https://github.com/starkware-libs/cairo/blob/2120669e3cec802dc3714422f3062d1c6bb03d9e/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L95)):*
> ```XML
>             });
>         }
>         let mut input_data_short_err = format!("`{param_name}` failed to deserialize");
> ```

I see that this is not a regression compared to the current state, 
but I'm not sure I like having all those constants in the byecode.



_Suggestion:_
```XML
"failed to deserialize `{param_name}`"
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3740)* status: 0 of 23 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3740#-Na1vzBi25tm0wybT5YG:-Na1x-NM6yPOHbqiDCkv:b-wqlo9z) ([raw file](https://github.com/starkware-libs/cairo/blob/2120669e3cec802dc3714422f3062d1c6bb03d9e/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L95)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I see that this is not a regression compared to the current state, 
but I'm not sure I like having all those constants in the byecode.
</blockquote></details>

i think i prefer having the param name more than the prefix.

the current one was very confusing - we may add "non-provable" info at some point of the future.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3740#-Na1vzBi25tm0wybT5YG:-Na1xuQL6ifF-HU-7u6y:b-azcczy) ([raw file](https://github.com/starkware-libs/cairo/blob/2120669e3cec802dc3714422f3062d1c6bb03d9e/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L95)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i think i prefer having the param name more than the prefix.

the current one was very confusing - we may add "non-provable" info at some point of the future.
</blockquote></details>

"i think i prefer having the param name more than the prefix."
What is the prefix?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3740)* status: 0 of 23 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3740#-Na1vzBi25tm0wybT5YG:-Na1yQ934XdZw6UG-N7u:bq9ntj7) ([raw file](https://github.com/starkware-libs/cairo/blob/2120669e3cec802dc3714422f3062d1c6bb03d9e/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L95)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

"i think i prefer having the param name more than the prefix."
What is the prefix?
</blockquote></details>

i meant before the other part.
I'd rather have:
`'long_long_long_name' failed to des`
than
`failed to deserialize 'long_long_long`

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3740#-Na1vzBi25tm0wybT5YG:-Na1zQGAANq9ePK1Pqn7:b-pcobzb) ([raw file](https://github.com/starkware-libs/cairo/blob/2120669e3cec802dc3714422f3062d1c6bb03d9e/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L95)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i meant before the other part.
I'd rather have:
`'long_long_long_name' failed to des`
than
`failed to deserialize 'long_long_long` 
</blockquote></details>

Ok, I wasn't sure if the former is correct grammatically.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/l1_handler` line 205 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3740#-Na1zbveBLo8vMZNXd9s:-Na1zbveBLo8vMZNXd9t:bu2mxal) ([raw file](https://github.com/starkware-libs/cairo/blob/2120669e3cec802dc3714422f3062d1c6bb03d9e/crates/cairo-lang-starknet/src/plugin/plugin_test_data/l1_handler#L205)):*
> ```
>             
>             let __arg_from_address =
>                 serde::Serde::<u128>::deserialize(ref data).expect('`from_address` failed to deseri');
> ```

This is starnge.



_Code quote:_
```
'`from_address` failed to deseri'
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 3 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3740)* status: 3 of 23 files reviewed, all discussions resolved

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3740#-Na1vzBi25tm0wybT5YG:-Na1zzkA7CzFylOGTu-h:b-dpwk0p) ([raw file](https://github.com/starkware-libs/cairo/blob/2120669e3cec802dc3714422f3062d1c6bb03d9e/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L95)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Ok, I wasn't sure if the former is correct grammatically.
</blockquote></details>

Maybe you should just give the index of the parameter?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3740)* status: 3 of 23 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/l1_handler` line 205 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3740#-Na1zbveBLo8vMZNXd9s:-Na2--kPAYv8QqB7d-Iq:b-jf571s) ([raw file](https://github.com/starkware-libs/cairo/blob/2120669e3cec802dc3714422f3062d1c6bb03d9e/crates/cairo-lang-starknet/src/plugin/plugin_test_data/l1_handler#L205)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

This is starnge.
</blockquote></details>

until we have normal long-string byte arrays - this would still be the easiest way to go.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/l1_handler` line 205 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3740#-Na1zbveBLo8vMZNXd9s:-Na2-p8FA0qWJCaUQR-e:b6zgobs) ([raw file](https://github.com/starkware-libs/cairo/blob/2120669e3cec802dc3714422f3062d1c6bb03d9e/crates/cairo-lang-starknet/src/plugin/plugin_test_data/l1_handler#L205)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

until we have normal long-string byte arrays - this would still be the easiest way to go.
</blockquote></details>

not doing this PR is even easier.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 20 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3740#-:-Na20FsE1LKPAR67lsqy:bnfp4nl)* status: 22 of 23 files reviewed, all discussions resolved (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3740)* status: 22 of 23 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3740#-Na1vzBi25tm0wybT5YG:-Na2-Oe2ENPwEq-VlzfR:b-sq7tz6) ([raw file](https://github.com/starkware-libs/cairo/blob/2120669e3cec802dc3714422f3062d1c6bb03d9e/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L95)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Maybe you should just give the index of the parameter?
</blockquote></details>

i don't really like that idea, but can do - still an improvement i guess.

**Pull request merged**
