### PR TITLE
Added bool or.

### PR DESCRIPTION
**Pull request by amosStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1701)

### CODE REVIEW

**Review by amosStarkware — COMMENTED** [review]
+reviewer:@dorimedini-starkware 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1701#-:-NLM0ZtY0Hot0kCeGfUN:b-hz3kb8)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1701)* status: 1 of 7 files reviewed, 5 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/cairo-lang-sierra/src/simulation/core.rs` line 381 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1701#-NLMB30v1Ike33pJxbCx:-NLQzCeE0saun_LN-gCU:b-r6ujg0) ([raw file](https://github.com/starkware-libs/cairo/blob/7445a45b56d4695f0b51c3eec4fcc024daa15ed1/crates/cairo-lang-sierra/src/simulation/core.rs#L381)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

since this isn't cairo, I think `if a + b > 0 { 1 } else { 0 }` is more readable but non-blocking
</blockquote></details>

Updated to what clippy demanded
___
*[`crates/cairo-lang-sierra/src/simulation/core.rs` line 386 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1701#-NLMBDBb4m54oczowNMV:-NLQzG6g082UkOWg4UEz:b-7jzv7t) ([raw file](https://github.com/starkware-libs/cairo/blob/7445a45b56d4695f0b51c3eec4fcc024daa15ed1/crates/cairo-lang-sierra/src/simulation/core.rs#L386)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is the correct error, right? which you found?
</blockquote></details>

right
___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1701#-NLMBN2Z4k92YqVJU3YU:-NLR-_1q6TzEKGTBwGSK:bgbzw9m) ([raw file](https://github.com/starkware-libs/cairo/blob/7445a45b56d4695f0b51c3eec4fcc024daa15ed1/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L67)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why not `3`? it should be at least the AP change, but why more?
</blockquote></details>

Updated to 2, because `let` now supports subtraction (so I used `let` instead of `tempvar`)
___
*[`tests/e2e_test_data/libfuncs/bool` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1701#-NLMBZh48RhgRyLNj8cf:-NLR1XZx9CIymIZv8QvK:bhohleq) ([raw file](https://github.com/starkware-libs/cairo/blob/7445a45b56d4695f0b51c3eec4fcc024daa15ed1/tests/e2e_test_data/libfuncs/bool#L48)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

does it work without the `mut`?
</blockquote></details>

Yes, removed it.
`Xor` also works without it
___
*[`tests/e2e_test_data/libfuncs/bool` line 62 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1701#-NLR-hYbEo47lapsB8I7:-NLR-hYbEo47lapsB8I8:b-szbrvd) ([raw file](https://github.com/starkware-libs/cairo/blob/7445a45b56d4695f0b51c3eec4fcc024daa15ed1/tests/e2e_test_data/libfuncs/bool#L62)):*
> ```
> 
> //! > function_costs
> test::foo: OrderedHashMap({Step: 5})
> ```

what does Step represent?
the comment says cost but it's not equal to the cost. it's also not always equal to the number of casm lines.



_Code quote:_
```
test::foo: OrderedHashMap({Step: 5})
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1701)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware)

___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1701#-NLMBN2Z4k92YqVJU3YU:-NL_Aq6f6oE8Xvp1YP7X:b-z4v9be) ([raw file](https://github.com/starkware-libs/cairo/blob/7445a45b56d4695f0b51c3eec4fcc024daa15ed1/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L67)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

Updated to 2, because `let` now supports subtraction (so I used `let` instead of `tempvar`)
</blockquote></details>

it's now `3`, you meant `2`?
___
*[`tests/e2e_test_data/libfuncs/bool` line 62 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1701#-NLR-hYbEo47lapsB8I7:-NL_B5zT0vhB71dtqIEf:bgkotae) ([raw file](https://github.com/starkware-libs/cairo/blob/7445a45b56d4695f0b51c3eec4fcc024daa15ed1/tests/e2e_test_data/libfuncs/bool#L62)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

what does Step represent?
the comment says cost but it's not equal to the cost. it's also not always equal to the number of casm lines.
</blockquote></details>

I think it should be proportional to the amount of gas used. and it is equal to the number of CASM lines ATM (`ret` counts)

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1701)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1701#-NLMBN2Z4k92YqVJU3YU:-NLaoVQ03WKYsd_XxBk-:bi5k54e) ([raw file](https://github.com/starkware-libs/cairo/blob/7445a45b56d4695f0b51c3eec4fcc024daa15ed1/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L67)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

it's now `3`, you meant `2`?
</blockquote></details>

yes, Thx
___
*[`tests/e2e_test_data/libfuncs/bool` line 62 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1701#-NLR-hYbEo47lapsB8I7:-NLaoJYo1U_VnF_9FVkf:bcd2gi3) ([raw file](https://github.com/starkware-libs/cairo/blob/7445a45b56d4695f0b51c3eec4fcc024daa15ed1/tests/e2e_test_data/libfuncs/bool#L62)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think it should be proportional to the amount of gas used. and it is equal to the number of CASM lines ATM (`ret` counts)
</blockquote></details>

now it isn't

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1701)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

___
*[`tests/e2e_test_data/libfuncs/bool` line 62 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1701#-NLR-hYbEo47lapsB8I7:-NLpCRrO6yv-r3aLOuOa:bj03bh7) ([raw file](https://github.com/starkware-libs/cairo/blob/7445a45b56d4695f0b51c3eec4fcc024daa15ed1/tests/e2e_test_data/libfuncs/bool#L62)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

now it isn't
</blockquote></details>

hmmm... then I don't know. @orizi , what does the `Step` cost value represent?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1701)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

___
*[`tests/e2e_test_data/libfuncs/bool` line 62 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1701#-NLR-hYbEo47lapsB8I7:-NLt7WHA29G0xajNJ0jQ:bkwgsec) ([raw file](https://github.com/starkware-libs/cairo/blob/7445a45b56d4695f0b51c3eec4fcc024daa15ed1/tests/e2e_test_data/libfuncs/bool#L62)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

hmmm... then I don't know. @orizi , what does the `Step` cost value represent?
</blockquote></details>

3 is correct, ret does not count (it is counted during payment for function call)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1701#-:-NLtyQyp76zyP9BphSpW:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1701)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
