### PR TITLE
resolved impl impl

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5854)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5854)* status: 6 of 13 files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/inference/conform.rs` line 580 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5854#-O04llad0nTUzuztAQCO:-O04llae1yOsP-zbe9o3:b9wgyiu) ([raw file](https://github.com/starkware-libs/cairo/blob/df7e92978ebedf5735bdeee1149c23c553dc3e0c/crates/cairo-lang-semantic/src/expr/inference/conform.rs#L580)):*
> ```XML
>                 .unwrap_or_else(InferenceError::Reported),
>         )
>     }
> ```

revert move.



_Code quote:_
```XML
    /// Sets an error for an impl reduction failure.
    fn set_impl_reduction_error(&mut self, impl_id: ImplId) -> ErrorSet {
        self.set_error(
            impl_id
                .concrete_trait(self.db)
                .map(InferenceError::NoImplsFound)
                .unwrap_or_else(InferenceError::Reported),
        )
    }
```

**Review by orizi — COMMENTED** [review]
> Reviewed 7 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5854)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5854)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/inference/conform.rs` line 580 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5854#-O04llad0nTUzuztAQCO:-O04nwEO6iZgLXG1DOZp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/df7e92978ebedf5735bdeee1149c23c553dc3e0c/crates/cairo-lang-semantic/src/expr/inference/conform.rs#L580)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

revert move.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5854#-:-O04o54rA3Ed0hASVP--:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5854)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5854)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
