### PR TITLE
Made calculating following files recursive.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #6227
- #6225
- #6224 ⬅
- #6223

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6224)

### CODE REVIEW

**Review by mkaput — APPROVED** [review]
@Draggu PTAL

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6224#-:-O4e_z_v1LwYt5ptGlhS:b-kmdxm6)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Draggu and @gilbens-starkware)

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6224)* status: all files reviewed, 1 unresolved discussion (waiting on @Draggu and @orizi)

___
*[`crates/cairo-lang-defs/src/db.rs` line 390 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6224#-O4egRyo20FCyGoyjks_:-O4egRyo20FCyGoyjksa:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/0d5e4f36e5722bbaf4118656e75103a82febea9a/crates/cairo-lang-defs/src/db.rs#L390)):*
> ```XML
> 
> #[derive(Clone, Debug, Eq, PartialEq)]
> pub struct PrivModuleFileData {
> ```

doc



_Code quote:_
```XML
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PrivModuleFileData {
```

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6224#-:-O4gaVPqCt75wc8U_Xg8:bnfp4nl)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @Draggu and @mkaput)

**Review by mkaput — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6224)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @piotmag769)

**Pull request merged**
