### PR TITLE
Delay error reporting.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This in done in preparation for parrallel compilation.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6025)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6025)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-compiler/src/lib.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6025#-O1v42k032kqmDgOUB_x:-O1v42k032kqmDgOUB_y:b-qbjz2m) ([raw file](https://github.com/starkware-libs/cairo/blob/97d0db64b14955d8b06b5b07dd79fe14fe82b911/crates/cairo-lang-compiler/src/lib.rs#L151)):*
> ```XML
>     mut diagnostic_reporter: DiagnosticsReporter<'_>,
> ) -> Result<SierraProgramWithDebug> {
>     diagnostic_reporter.ensure(db)?;
> ```

I want to spawn compilation of the ` requested_function_ids` before this line.



_Code quote:_
```XML
diagnostic_reporter.ensure(db)?;
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6025)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-compiler/src/lib.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6025#-O1v5Ysv0T7BxVx0YJzR:-O1v5Ysv0T7BxVx0YJzS:bb7f2bf) ([raw file](https://github.com/starkware-libs/cairo/blob/97d0db64b14955d8b06b5b07dd79fe14fe82b911/crates/cairo-lang-compiler/src/lib.rs#L146)):*
> ```XML
> }
> 
> pub fn get_sierra_program_for_functions(
> ```

doc.
___
*[`crates/cairo-lang-compiler/src/lib.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6025#-O1v42k032kqmDgOUB_x:-O1v5g8Q2BBYYX_mOUSk:b-ki8mw0) ([raw file](https://github.com/starkware-libs/cairo/blob/97d0db64b14955d8b06b5b07dd79fe14fe82b911/crates/cairo-lang-compiler/src/lib.rs#L151)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I want to spawn compilation of the ` requested_function_ids` before this line.
</blockquote></details>

sounds sensible
___
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6025#-O1v5s4hATgLXjSMIXyi:-O1v5s4hATgLXjSMIXyj:b-z5hdx5) ([raw file](https://github.com/starkware-libs/cairo/blob/97d0db64b14955d8b06b5b07dd79fe14fe82b911/crates/cairo-lang-test-plugin/src/lib.rs#L92)):*
> ```XML
>     };
> 
>     let executable_functions = find_executable_function_ids(db, main_crate_ids.clone());
> ```

Won't we already crash over diagnostics if we have bad results in this stage?



_Code quote:_
```XML
    let executable_functions = find_executable_function_ids(db, main_crate_ids.clone());
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6025#-O1v5s4hATgLXjSMIXyi:-O1vAkwO3janyknM9LJi:bycv4az) ([raw file](https://github.com/starkware-libs/cairo/blob/97d0db64b14955d8b06b5b07dd79fe14fe82b911/crates/cairo-lang-test-plugin/src/lib.rs#L92)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Won't we already crash over diagnostics if we have bad results in this stage?
</blockquote></details>

It does not seem to crash.

though I agree that after this change you have to be more careful when writing the functions that collect the ids.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6025)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-compiler/src/lib.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6025#-O1v5Ysv0T7BxVx0YJzR:-O1vGoim67Oa9UjtKuTh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/97d0db64b14955d8b06b5b07dd79fe14fe82b911/crates/cairo-lang-compiler/src/lib.rs#L146)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc.
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6025)* status: 4 of 6 files reviewed, all discussions resolved

___
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6025#-O1v5s4hATgLXjSMIXyi:-O1vJZYbEBIwqmFBfTIp:bet9e8e) ([raw file](https://github.com/starkware-libs/cairo/blob/97d0db64b14955d8b06b5b07dd79fe14fe82b911/crates/cairo-lang-test-plugin/src/lib.rs#L92)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

It does not seem to crash.

though I agree that after this change you have to be more careful when writing the functions that collect the ids.
</blockquote></details>

Are you sure, including parsing errors?

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6025)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6025#-O1v5s4hATgLXjSMIXyi:-O1vNPP30La_fSbz2zTP:byjjr8s) ([raw file](https://github.com/starkware-libs/cairo/blob/97d0db64b14955d8b06b5b07dd79fe14fe82b911/crates/cairo-lang-test-plugin/src/lib.rs#L92)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Are you sure, including parsing errors?
</blockquote></details>

I tested parsing errors.
also I looked in the function and didn't see unwraps.

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6025#-:-O1vT0LY3Hbc4YxagESp:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
