### PR TITLE
Add fixed array pattern semantic handling.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
commit-id:14b1b097

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5168)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5168)* status: 4 of 7 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 466 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5168#-Nro5l1Y1kxkaYqJRPBQ:-Nro5l1Y1kxkaYqJRPBR:b-dcrvil) ([raw file](https://github.com/starkware-libs/cairo/blob/8d5dd7f7e043c9cf8682c8af3e5c5ed47852f2cc/crates/cairo-lang-semantic/src/diagnostic.rs#L466)):*
> ```XML
>             SemanticDiagnosticKind::UnexpectedFixedSizeArrayPattern { ty } => {
>                 format!(
>                     r#"Unexpected type for fixed size array pattern. "{}" is not a fixed size array."#,
> ```

long line
___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 476 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5168#-Nro5mE-9QGhrbFtdlA4:-Nro5mE09U563eWUxa05:b-dcrvil) ([raw file](https://github.com/starkware-libs/cairo/blob/8d5dd7f7e043c9cf8682c8af3e5c5ed47852f2cc/crates/cairo-lang-semantic/src/diagnostic.rs#L476)):*
> ```XML
>             SemanticDiagnosticKind::WrongNumberOfFixedSizeArrayElements { expected, actual } => {
>                 format!(
>                     r#"Wrong number of fixed size array elements in pattern. Expected: {}. Got: {}."#,
> ```

long line
___
*[`crates/cairo-lang-semantic/src/expr/test_data/pattern` line 204 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5168#-Nro5yBZ6wyNSpiNdHjR:-Nro5yBZ6wyNSpiNdHjS:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8d5dd7f7e043c9cf8682c8af3e5c5ed47852f2cc/crates/cairo-lang-semantic/src/expr/test_data/pattern#L204)):*
> ```
> 
> //! > function
> fn foo(s: (felt252, felt252, felt252) {
> ```





_Suggestion:_
```
fn foo(s: (felt252, felt252, felt252)) {
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5168)* status: 3 of 7 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 466 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5168#-Nro5l1Y1kxkaYqJRPBQ:-Nro7XPN2fZvFSyywgwb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8d5dd7f7e043c9cf8682c8af3e5c5ed47852f2cc/crates/cairo-lang-semantic/src/diagnostic.rs#L466)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

long line
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 476 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5168#-Nro5mE-9QGhrbFtdlA4:-Nro7XaP7kSrvMjr3KgE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8d5dd7f7e043c9cf8682c8af3e5c5ed47852f2cc/crates/cairo-lang-semantic/src/diagnostic.rs#L476)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

long line
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/pattern` line 204 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5168#-Nro5yBZ6wyNSpiNdHjR:-Nro7bOOBSCJSLzjwD5B:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8d5dd7f7e043c9cf8682c8af3e5c5ed47852f2cc/crates/cairo-lang-semantic/src/expr/test_data/pattern#L204)):*
> ```
> 
> //! > function
> fn foo(s: (felt252, felt252, felt252) {
> ```

Done.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5168)* status: 5 of 22 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1709 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5168#-NroFDY99bXQSh3CCqZv:-NrpOgizDicpEe0CSvBE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/64a51c2b7de1a4d61f0ed5d0b73523bcd6c9d692/crates/cairo-lang-semantic/src/expr/compute.rs#L1709)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

move near tuple handling - and extract similar logic if possible.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 17 files at r3, 15 of 15 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5168#-:-NrpUNtf2DjLqZNWOa1G:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
