### PR TITLE
Support constant lookup in modules (path longer than 1 segment).

### PR DESCRIPTION
**Pull request by liorgold2**
commit-id:b9b70f7d

---

**Stack**:
- #1837
- #1836
- #1827 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1827#-:-NME9laU7eCrjTJxcs72:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1827)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1827)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1827#-:-NMMrgX8BydiW7EHps9r:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1208 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1827#-NMMrLQ03a9g_RIzpbJL:-NMMrLQ03a9g_RIzpbJM:b-fongi3) ([raw file](https://github.com/starkware-libs/cairo/blob/065afdc25001444e8635db5c28e6010ca016c9d2/crates/cairo-lang-semantic/src/expr/compute.rs#L1208)):*
> ```XML
> 
>     // Check if this is a variable.
>     if let PathSegment::Simple(ident_segment) = &segments[0] {
> ```

if let [PathSegment::Simple(ident_segment)] = &segment[..] {

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1827)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 1208 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1827#-NMMrLQ03a9g_RIzpbJL:-NMNZDlk7PqFU7j8gRXx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8f01153fed4305aa8ac42087d06f2fcb41f89e5b/crates/cairo-lang-semantic/src/expr/compute.rs#L1208)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

if let [PathSegment::Simple(ident_segment)] = &segment[..] {
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1827)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
