### PR TITLE
Add Reference Values and Branch Changes to CairoProgramDebugInfo

### PR DESCRIPTION
**Pull request by barabanovro**
This PR adds `Reference Values` and `Branch Changes` to `CairoProgramDebugInfo`. New debug information cannot be placed in SierraStatementDebugInfo due to the non-implementable Copy trait for ReferenceValue.

This PR will allow [cairovm.codes](https://cairovm.codes) to display Sierra variables values after program execution.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5152)

### CODE REVIEW

**Comment by mazurroman** [comment]
**More context on why do we need this PR:**

It enables us to display the values of Sierra variables during program execution debugging. I am attaching a 30-second video to demonstrate this. You can try it yourself at [cairovm.codes](https://cairovm.codes/)

https://github.com/starkware-libs/cairo/assets/2983746/4adcd4bc-2b83-4e87-ad27-01bdf0e38371

Having Sierra memory mapping is a crucial prerequisite before advancing to Cairo memory mapping and enabling the inspection of Cairo variables during debugging. This will represent the final step for the cairovm.codes project, making it a tool for anyone wishing to learn Cairo through running and debugging it. We are also in discussions with Ariel from Starkware to make cairovm.codes an official learning tool for Cairo and integrating it into the Cairo website and documentation.

In addition to cairovm.codes, this PR is also important for [Walnut](https://walnut.dev/), where we aim to enable Cairo transaction debugging on Starknet.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5152)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @barabanovro)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 172 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5152#-NrkFjiLE6zekhoGF13h:-NrkFjiLE6zekhoGF13i:biyxh1r) ([raw file](https://github.com/starkware-libs/cairo/blob/f1e310350d665f67ce39224723579fa76a6f5b52/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L172)):*
> ```XML
> /// The debug references and branch changes information of a compilation from Sierra to casm.
> #[derive(Debug, Eq, PartialEq, Clone)]
> pub struct SierraRefsDebugInfo {
> ```

why add it as a separate vector instead of inside the per SierraStatement info?
please move it.



_Code quote:_
```XML
SierraRefsDebugInfo
```

**Comment by barabanovro** [comment]
@orizi,

`SierraStatementDebugInfo` implements the `Copy` trait, but this trait cannot be implemented for `ReferenceValue` and `BranchChanges` because they both have nested `BigInt` fields that do not implement `Copy`. That's why I added them to a separate vector without the `Copy` trait.

**Review by orizi — COMMENTED** [review]
so remove the copy trait - and please open on https://reviewable.io/reviews/starkware-libs/cairo/5152#- so you'd answer in the threads.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5152#-:-Nro3pwLD90VgE-J9gci:bx6o82t)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @barabanovro)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5152)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @barabanovro)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 173 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5152#-Nrp0sI01l3hobiGNbIS:-Nrp0sI14WHCDNOSSsK1:b-efvrsz) ([raw file](https://github.com/starkware-libs/cairo/blob/03b10adb59786061e9115de1c387f5f7c76ac534/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L173)):*
> ```XML
>     pub invoke_refs: Option<Vec<ReferenceValue>>,
>     /// The return references of the sierra statement.
>     pub return_refs: Option<Vec<ReferenceValue>>,
> ```

any reason for Option of vec - vec isn't enough?



_Code quote:_
```XML
    /// The result branch changes of the sierra statement.
    pub result_branch_changes: Option<Vec<BranchChanges>>,
    /// The invoke references of the sierra statement.
    pub invoke_refs: Option<Vec<ReferenceValue>>,
    /// The return references of the sierra statement.
    pub return_refs: Option<Vec<ReferenceValue>>,
```
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 173 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5152#-Nrp15i15j0o6fr5tfRf:-Nrp15i15j0o6fr5tfRg:b-temze1) ([raw file](https://github.com/starkware-libs/cairo/blob/03b10adb59786061e9115de1c387f5f7c76ac534/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L173)):*
> ```XML
>     pub invoke_refs: Option<Vec<ReferenceValue>>,
>     /// The return references of the sierra statement.
>     pub return_refs: Option<Vec<ReferenceValue>>,
> ```

any reason to separate these?



_Code quote:_
```XML
    /// The invoke references of the sierra statement.
    pub invoke_refs: Option<Vec<ReferenceValue>>,
    /// The return references of the sierra statement.
    pub return_refs: Option<Vec<ReferenceValue>>,
```

**Review by barabanovro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5152)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 173 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5152#-Nrp0sI01l3hobiGNbIS:-Nrp7rzv41Br58V6VWLD:baiexpe) ([raw file](https://github.com/starkware-libs/cairo/blob/03b10adb59786061e9115de1c387f5f7c76ac534/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L173)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

any reason for Option of vec - vec isn't enough?
</blockquote></details>

Just vec is enough, I have fixed this.
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 173 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5152#-Nrp15i15j0o6fr5tfRf:-NrpA7Gt-oS6nnAtlToK:b-q65gx9) ([raw file](https://github.com/starkware-libs/cairo/blob/03b10adb59786061e9115de1c387f5f7c76ac534/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L173)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

any reason to separate these?
</blockquote></details>

Actually, there is no reason. I have combined them now.

**Review by orizi — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5152#-:-NrpTxAFC_SxyTUBA7kO:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @barabanovro)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5152#-NrpTy_e6J0XdrGRqqiM:-NrpTy_e6J0XdrGRqqiN:bpx0xxa) (no related file):*
@yuvalsw for 2nd eye.

___

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5152)* status: all files reviewed, 4 unresolved discussions (waiting on @barabanovro)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 172 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5152#-NsI0iPzEg3aV9ykrlWB:-NsI0iPzEg3aV9ykrlWC:bwp3l8y) ([raw file](https://github.com/starkware-libs/cairo/blob/f6ea7d7f804b1d5b4cfb103883d2027eb68bd08e/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L172)):*
> ```XML
>     /// The invoke and return references of the sierra statement.
>     pub ref_values: Vec<ReferenceValue>,
> }
> ```

Feel free to suggest better names for the structs/members.



_Suggestion:_
```XML
/// The debug information of a compilation from Sierra to casm.
#[derive(Debug, Eq, PartialEq, Clone)]
pub struct SierraStatementDebugInfo {
    /// The offset of the sierra statement within the bytecode.
    pub code_offset: usize,
    /// The index of the sierra statement in the instructions vector.
    pub instruction_idx: usize,
    /// Statement-kind-dependent information.
    pub additional_kind_info: StatementKindDebugInfo,
}

/// Additional debug information for a Sierra statement, depending on its kind (invoke/return/dummy).
#[derive(Debug, Eq, PartialEq, Clone)]
enum StatementKindDebugInfo {
    Return: ReturnStatementDebugInfo,
    Invoke: InvokeStatementDebugInfo,
    /// Dummy marker for the end of the program. It is used for a fake statement that contains the final offset (the size of the program code segment).
    EndMarker
}

/// Additional debug information for a return Sierra statement.
#[derive(Debug, Eq, PartialEq, Clone)]
struct ReturnStatementDebugInfo {
    /// The references of a Sierra return statement.
    pub ref_values: Vec<ReferenceValue>,
}

/// Additional debug information for an invoke Sierra statement.
#[derive(Debug, Eq, PartialEq, Clone)]
struct InvokeStatementDebugInfo {
    /// The result branch changes of a Sierra invoke statement.
    pub result_branch_changes: Vec<BranchChanges>,
    /// The references of a Sierra invoke statement.
    pub ref_values: Vec<ReferenceValue>,
}
```
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 335 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5152#-NsI-lgf10lGf6fuQI40:-NsI-lggCEp-Z8wrQY63:bairgqk) ([raw file](https://github.com/starkware-libs/cairo/blob/f6ea7d7f804b1d5b4cfb103883d2027eb68bd08e/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L335)):*
> ```XML
> 
>     // Maps statement_idx to program_offset, result_branch_changes, invoke_refs and return_refs.
>     // The last value (for statement_idx=number-of-statements)
> ```

No need to describe the inner fields...



_Suggestion:_
```XML
    // Maps statement_idx to its debug info.
    // The last value (for statement_idx=number-of-statements)
```
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 337 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5152#-NsI-aJs9Oq5ACdCwOQI:-NsI-aJs9Oq5ACdCwOQJ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f6ea7d7f804b1d5b4cfb103883d2027eb68bd08e/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L337)):*
> ```XML
>     // The last value (for statement_idx=number-of-statements)
>     // contains the final offset (the size of the program code segment).
>     let mut sierra_statement_info: Vec<SierraStatementDebugInfo> =
> ```





_Suggestion:_
```XML
let mut sierra_statement_infos: Vec<SierraStatementDebugInfo> =
```
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 495 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5152#-NsI2s-rCAOZWxjAHIku:-NsI2s-rCAOZWxjAHIkv:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f6ea7d7f804b1d5b4cfb103883d2027eb68bd08e/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L495)):*
> ```XML
>         result_branch_changes: vec![],
>         ref_values: vec![],
>     });
> ```





_Suggestion:_
```XML
    // Push the final offset and index at the end of the vector.
    sierra_statement_info.push(SierraStatementDebugInfo {
        code_offset: program_offset,
        instruction_idx: instructions.len(),
        additional_kind_info: StatementKindDebugInfo::Dummy,
    });
```

**Comment by mazurroman** [comment]
Thank you so much for your review @yuvalsw. Please note that @barabanovro is currently off and will get back to this in ~10 days starting Monday 18th.

**Review by barabanovro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5152)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 172 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5152#-NsI0iPzEg3aV9ykrlWB:-NtFFska4SoXSBZaf5uK:bl533fo) ([raw file](https://github.com/starkware-libs/cairo/blob/f6ea7d7f804b1d5b4cfb103883d2027eb68bd08e/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L172)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Feel free to suggest better names for the structs/members.
</blockquote></details>

I have addressed the requested changes, thank you for your suggestions!
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 337 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5152#-NsI-aJs9Oq5ACdCwOQI:-NtFH1mICQRC5BJ-JGA4:b-qyd3s6) ([raw file](https://github.com/starkware-libs/cairo/blob/f6ea7d7f804b1d5b4cfb103883d2027eb68bd08e/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L337)):*
> ```XML
>     // The last value (for statement_idx=number-of-statements)
>     // contains the final offset (the size of the program code segment).
>     let mut sierra_statement_info: Vec<SierraStatementDebugInfo> =
> ```

Would it be better to keep the `sierra_statement_info` name as we already have in the `CairoProgramDebugInfo` struct?

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5152)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barabanovro)

**Review by barabanovro — COMMENTED** [review]
Hey @orizi, what are the next steps to merge the PR?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5152#-:-NtL6WTRArWCqrdFr6St:bpc3uki)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barabanovro)

**Review by orizi — APPROVED** [review]
it seems this has broken the tests - so please fix.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5152#-:-NtRGtYu1WUfZp0Gpjap:b1ufabq)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barabanovro)

**Review by barabanovro — COMMENTED** [review]
Fixed the issue

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5152#-:-NrpAdji-_O6MICe_End:b-rrd9mv)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5152)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barabanovro)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5152)* status: all files reviewed, 1 unresolved discussion (waiting on @barabanovro)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 452 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5152#-NtV1gxUAMnFl5UxP--t:-NtV1gxUAMnFl5UxP--u:b-si4o5s) ([raw file](https://github.com/starkware-libs/cairo/blob/b95045ccffe0e847f381119fb09a39103f3f78e1/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L452)):*
> ```XML
>                 })?;
> 
>                 sierra_statement_info.push(SierraStatementDebugInfo {
> ```

doesn't the changing of moving the push to after change the entire debug info fields meaning?

**Review by barabanovro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5152)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 452 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5152#-NtV1gxUAMnFl5UxP--t:-NtZISPG6lkz1um6htl7:bpxboa9) ([raw file](https://github.com/starkware-libs/cairo/blob/b95045ccffe0e847f381119fb09a39103f3f78e1/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L452)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doesn't the changing of moving the push to after change the entire debug info fields meaning?
</blockquote></details>

In the previous fix, I adjusted the order of operations so that we push the offsets and debug info **before** incrementing the `program_offset` and extending the `instructions`. This ensures that each statement's debug info is accurately associated with the correct `code_offset` and `instruction_idx`.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5152)* status: all files reviewed, 1 unresolved discussion (waiting on @barabanovro)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 452 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5152#-NtV1gxUAMnFl5UxP--t:-Nt_UjVG38e-CtwwvXo5:bjamcxf) ([raw file](https://github.com/starkware-libs/cairo/blob/b95045ccffe0e847f381119fb09a39103f3f78e1/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L452)):*
<details><summary><i>Previously, barabanovro (Roman) wrote…</i></summary><blockquote>

In the previous fix, I adjusted the order of operations so that we push the offsets and debug info **before** incrementing the `program_offset` and extending the `instructions`. This ensures that each statement's debug info is accurately associated with the correct `code_offset` and `instruction_idx`.
</blockquote></details>

so i'd much rather you'd remove the enum, and just have a `code_offset` range.
this change makes everything much different than previously - without a good enough reason IMO.

**Review by barabanovro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5152)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 452 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5152#-NtV1gxUAMnFl5UxP--t:-Ntow2Bq6OI21-61xshn:b-p6wp9n) ([raw file](https://github.com/starkware-libs/cairo/blob/b95045ccffe0e847f381119fb09a39103f3f78e1/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L452)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

so i'd much rather you'd remove the enum, and just have a `code_offset` range.
this change makes everything much different than previously - without a good enough reason IMO.
</blockquote></details>

The goal of this PR is to include statement `references` and `branch changes` in `CairoProgramDebugInfo`. We use this debug info at [cairovm.codes](https://cairovm.codes/) to display Sierra variables' values. Yuvalsw suggested using an enum to hold this debug information, and it was previously approved. Could you please suggest an approach to include this debug info that aligns better with the current implementation?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5152)* status: all files reviewed, 1 unresolved discussion (waiting on @barabanovro)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 452 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5152#-NtV1gxUAMnFl5UxP--t:-NtqJRZl0RrEF9TB-qjI:bqy2dir) ([raw file](https://github.com/starkware-libs/cairo/blob/b95045ccffe0e847f381119fb09a39103f3f78e1/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L452)):*
<details><summary><i>Previously, barabanovro (Roman) wrote…</i></summary><blockquote>

The goal of this PR is to include statement `references` and `branch changes` in `CairoProgramDebugInfo`. We use this debug info at [cairovm.codes](https://cairovm.codes/) to display Sierra variables' values. Yuvalsw suggested using an enum to hold this debug information, and it was previously approved. Could you please suggest an approach to include this debug info that aligns better with the current implementation?
</blockquote></details>

start_offset and end_offset per statement - and no end marker at all.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5152#-:-NttganADrfpuhjFgOqW:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @barabanovro)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5152)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barabanovro)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5152)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barabanovro)

**Review by barabanovro — COMMENTED** [review]
Hey @orizi, tests failed due to a Rust toolchain installation timeout.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5152#-:-NtyUGhP2s4y6e_RQwtg:br05h46)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barabanovro)

**Pull request merged**
