### PR TITLE
LS: fix panics in `lsp_helper`

### PR DESCRIPTION
**Pull request by piotmag769**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6168)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6168)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-semantic/src/lsp_helpers.rs` line 205 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6168#-O3hVyLP1rhvNKFJ9_eL:-O3hVyLP1rhvNKFJ9_eM:bwptfn5) ([raw file](https://github.com/starkware-libs/cairo/blob/9e52f9360711d7c333fd64fb0c8109c67cb8558f/crates/cairo-lang-semantic/src/lsp_helpers.rs#L205)):*
> ```XML
>     db: &dyn SemanticGroup,
>     module_id: ModuleId,
> ) -> Result<Arc<OrderedHashMap<TraitId, String>>, String> {
> ```

maybe just do it as a `Maybe`?
i don't really like having a `String` error value here.
Specifically since it is for another context.
(The specific error can be given using a trace, i think in general it isn't interesting for the user)



_Suggestion:_
```XML
) -> Maybe<Arc<OrderedHashMap<TraitId, String>>> {
```

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6168)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

___
*[`crates/cairo-lang-semantic/src/lsp_helpers.rs` line 205 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6168#-O3hVyLP1rhvNKFJ9_eL:-O3hXb3R0DmZwth_Fjk6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9e52f9360711d7c333fd64fb0c8109c67cb8558f/crates/cairo-lang-semantic/src/lsp_helpers.rs#L205)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe just do it as a `Maybe`?
i don't really like having a `String` error value here.
Specifically since it is for another context.
(The specific error can be given using a trace, i think in general it isn't interesting for the user)
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6168)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-semantic/src/lsp_helpers.rs` line 205 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6168#-O3hVyLP1rhvNKFJ9_eL:-O3hYIeEBrlEDBJM0JFA:b-fhq7cv) ([raw file](https://github.com/starkware-libs/cairo/blob/9e52f9360711d7c333fd64fb0c8109c67cb8558f/crates/cairo-lang-semantic/src/lsp_helpers.rs#L205)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

sorry - `Option` would be better - didn't realise the functions all returned `Option`.

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6168)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

___
*[`crates/cairo-lang-semantic/src/lsp_helpers.rs` line 205 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6168#-O3hVyLP1rhvNKFJ9_eL:-O3hfICY6WfeeHCSB4I5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9e52f9360711d7c333fd64fb0c8109c67cb8558f/crates/cairo-lang-semantic/src/lsp_helpers.rs#L205)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

sorry - `Option` would be better - didn't realise the functions all returned `Option`.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6168#-:-O3hfS-_5gRcuf3surNm:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @mkaput)

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6168#-:-O3lwp_KE-SKkjwtwfK2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)

**Pull request merged**
