### PR TITLE
Add 2024_07 edition.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
**Stack**:
- #5929
- #5925
- #5924
- #5923 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5923)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5923)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`corelib/src/prelude/v2024_07.cairo` line 65 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5923#-O0h3zy-CsQ08P46d7Ee:-O0h3zy-CsQ08P46d7Ef:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5a8444c7af003aea13d12b8439b538fa247fe488/corelib/src/prelude/v2024_07.cairo#L65)):*
> ```Cairo
> pub use core::traits::IndexView;
> pub use core::zeroable::NonZero;
> pub use core::ops::Deref;
> ```





_Suggestion:_
```Cairo
pub use core::{assert, bool, felt252, usize};

pub use core::array::{Array, ArrayTrait, Span, SpanTrait, ToSpanTrait};
pub use core::box::{Box, BoxTrait};
pub use core::bytes_31::{Bytes31Trait, bytes31};
pub use core::byte_array::{ByteArray, ByteArrayTrait};
pub use core::clone::Clone;
pub use core::dict::Felt252DictTrait;
pub use core::integer::{i128, i16, i32, i64, i8, u128, u16, u256, u32, u64, u8};
pub use core::nullable::{Nullable, NullableTrait};
pub use core::option::{Option, OptionTrait};
pub use core::panics::{Panic, PanicResult, panic};
pub use core::result::{Result, ResultTrait};
pub use core::serde::Serde;
pub use core::{starknet, starknet::System};
pub use core::traits::{
    Add, Copy, Default, Destruct, Div, DivRem, Drop,
    Felt252DictValue, Into, Mul, Neg, Not, PanicDestruct, PartialEq, PartialOrd, Rem, Sub, TryInto
};

pub use core::zeroable::NonZero;
pub use core::ops::Deref;
```
___
*[`crates/cairo-lang-filesystem/src/db.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5923#-O0h3oyY37CIoOkIUZJy:-O0h3oyY37CIoOkIUZJz:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5a8444c7af003aea13d12b8439b538fa247fe488/crates/cairo-lang-filesystem/src/db.rs#L54)):*
> ```XML
> /// editions. Editions may be added to provide features that are not backwards compatible, while
> /// allowing user to opt-in to them, and be ready for later compiler updates.
> #[derive(Clone, Copy, Debug, Default, Hash, PartialEq, Eq, Serialize, Deserialize, PartialOrd)]
> ```





_Suggestion:_
```XML
#[derive(Clone, Copy, Debug, Default, Hash, PartialEq, Eq, Serialize, Deserialize)]
```
___
*[`crates/cairo-lang-filesystem/src/db.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5923#-O0h3kA87a76HZ47ALzs:-O0h3kA87a76HZ47ALzt:bprb7x3) ([raw file](https://github.com/starkware-libs/cairo/blob/5a8444c7af003aea13d12b8439b538fa247fe488/crates/cairo-lang-filesystem/src/db.rs#L92)):*
> ```XML
>     pub fn backwards_compatible_storage(&self) -> bool {
>         self <= &Self::V2023_11
>     }
> ```

Full match instead for the time being.



_Code quote:_
```XML
    /// Whether to ignore visibility modifiers.
    pub fn ignore_visibility(&self) -> bool {
        self <= &Self::V2023_10
    }

    pub fn backwards_compatible_storage(&self) -> bool {
        self <= &Self::V2023_11
    }
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5923)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/prelude/v2024_07.cairo` line 65 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5923#-O0h3zy-CsQ08P46d7Ee:-O0hPaQb4zCXqRLwjCui:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5a8444c7af003aea13d12b8439b538fa247fe488/corelib/src/prelude/v2024_07.cairo#L65)):*
> ```Cairo
> pub use core::traits::IndexView;
> pub use core::zeroable::NonZero;
> pub use core::ops::Deref;
> ```

Done.
___
*[`crates/cairo-lang-filesystem/src/db.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5923#-O0h3oyY37CIoOkIUZJy:-O0hPz7lBOqJtAr47Zy5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5a8444c7af003aea13d12b8439b538fa247fe488/crates/cairo-lang-filesystem/src/db.rs#L54)):*
> ```XML
> /// editions. Editions may be added to provide features that are not backwards compatible, while
> /// allowing user to opt-in to them, and be ready for later compiler updates.
> #[derive(Clone, Copy, Debug, Default, Hash, PartialEq, Eq, Serialize, Deserialize, PartialOrd)]
> ```

Done.
___
*[`crates/cairo-lang-filesystem/src/db.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5923#-O0h3kA87a76HZ47ALzs:-O0hPzVwEegMo8U3pVXp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5a8444c7af003aea13d12b8439b538fa247fe488/crates/cairo-lang-filesystem/src/db.rs#L92)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Full match instead for the time being.
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5923)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 98 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5923#-O0hlB4vAZON5Sxigx-b:-O0hlB4wEPyBRAYmoVsp:b-22wc27) ([raw file](https://github.com/starkware-libs/cairo/blob/0eac98cde318fb5c404dcfd7f72553a3ddb7532d/crates/cairo-lang-filesystem/src/db.rs#L98)):*
> ```XML
>             Self::V2024_07 => false,
>         }
>     }
> ```

remove this from here - add it as a function in the starknet area (as this code area isn't starknet relevant.)



_Code quote:_
```XML
    pub fn backwards_compatible_storage(&self) -> bool {
        match self {
            Self::V2023_01 | Self::V2023_10 | Self::V2023_11 => true,
            Self::V2024_07 => false,
        }
    }
```

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5923)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5923#-:-O0hnOE4AzKlhC8KfIpi:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5923)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
