### PR TITLE
Added const-folding for the downcast libfunc.

### PR DESCRIPTION
**Pull request by orizi**
**Stack**:
- #6085
- #6084
- #6083
- #6071 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6071)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6071)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/test_data/match` line 1500 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6071#-O2eHTEYBA4ge6x7qQio:-O2eHTEYBA4ge6x7qQip:b-v0duql) ([raw file](https://github.com/starkware-libs/cairo/blob/1f515e119d4d2d5a69f4a3195bd96de8419ebe1b/crates/cairo-lang-lowering/src/test_data/match#L1500)):*
> ```
> //! > function
> fn foo(v: u32) -> felt252 {
>     match v {
> ```

Why did you change it?



_Code quote:_
```
fn foo(v: u32) -> felt252 {
    match v {
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6071)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-lowering/src/test_data/match` line 1500 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6071#-O2eHTEYBA4ge6x7qQio:-O2shgNv3HCIfb5hRSYH:bdgeiad) ([raw file](https://github.com/starkware-libs/cairo/blob/1f515e119d4d2d5a69f4a3195bd96de8419ebe1b/crates/cairo-lang-lowering/src/test_data/match#L1500)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Why did you change it?
</blockquote></details>

otherwise the new optimization changes the result. (it is known to be in the `BoundedInt<0, 6>` range

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6071#-:-O2tnKIZ8hJ4ISTJf848:bnfp4nl)* status: 1 of 3 files reviewed, all discussions resolved

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6071)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
