### PR TITLE
Add high level location field to sierra statement.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
**Stack**:
- #4878
- #4877
- #4876
- #4854
- #4853
- #4852 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4852)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4852)* status: 1 of 16 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/pre_sierra.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4852#-NofVzOjC5NbbWamm5fo:-NofVzOjC5NbbWamm5fp:b-g4noi8) ([raw file](https://github.com/starkware-libs/cairo/blob/e80f2f7b9d152e884684105a8c51eea57d909afa/crates/cairo-lang-sierra-generator/src/pre_sierra.rs#L58)):*
> ```XML
> /// Represents a pre-sierra statement - a statement before label-resolution.
> #[derive(Clone, Debug, Eq, PartialEq)]
> pub enum StatementInner {
> ```

bad name and bad doc for name.

if you only care about `Sierra` and `PushValues` to have a location - add it as a field for the variant.

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 16 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4852)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/expr_generator_context.rs` line 99 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4852#-NogcM3-CPPRK6E51t4P:-NogcM3-CPPRK6E51t4Q:bso7fcm) ([raw file](https://github.com/starkware-libs/cairo/blob/249fd2d4ea444f49247cc77958279436ab757946/crates/cairo-lang-sierra-generator/src/expr_generator_context.rs#L99)):*
> ```XML
> 
>     /// Generates a label id and a label statement.
>     // TODO(Gil): Consider returning a `Statement` instead of a `Statement`.
> ```

fix todo

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4852)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/pre_sierra.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4852#-NofVzOjC5NbbWamm5fo:-Nogd9Ki7kGdJGAdKUi0:be61yev) ([raw file](https://github.com/starkware-libs/cairo/blob/e80f2f7b9d152e884684105a8c51eea57d909afa/crates/cairo-lang-sierra-generator/src/pre_sierra.rs#L58)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

bad name and bad doc for name.

if you only care about `Sierra` and `PushValues` to have a location - add it as a field for the variant.
</blockquote></details>

Changed the name.
I don't want to have it in the variants as the variant structs are also used in `sierra::Program`.
I can split the structs into a pure pre-sierra struct.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4852)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4852)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/expr_generator_context.rs` line 99 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4852#-NogcM3-CPPRK6E51t4P:-NokJsLdBx_0HQc1KKZL:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/249fd2d4ea444f49247cc77958279436ab757946/crates/cairo-lang-sierra-generator/src/expr_generator_context.rs#L99)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix todo
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4852#-:-NokL0wRBZlkRVD_4ex8:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4852)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

**Pull request merged**
