### PR TITLE
Add basic storage array.

### PR DESCRIPTION
**Pull request by gilbens-starkware**
**Stack**:
- #5974 ⬅
- #5973

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5974)

### CODE REVIEW

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5974)* status: 0 of 3 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5974#-O1C4eSQ1PiHk1RLU6c8:-O1C4eSQ1PiHk1RLU6c9:b-2pbs3s) (no related file):*
Draft - names and doc tbd.

___

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5974)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @ArielElp and @gilbens-starkware)

___
*[`corelib/src/starknet/storage.cairo` line 670 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5974#-O1C90rc1JAbvu6LuvhQ:-O1C90rc1JAbvu6LuvhR:beouas9) ([raw file](https://github.com/starkware-libs/cairo/blob/39eaba10ee6ef0f393e66db1330bb36c873628f9/corelib/src/starknet/storage.cairo#L670)):*
> ```Cairo
> 
> 
> pub trait StorageArrayTrait<T> {
> ```

doc all.
(also below)
___
*[`corelib/src/starknet/storage.cairo` line 670 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5974#-O1C97LY2K2w3OeDEnMS:-O1C97LY2K2w3OeDEnMT:b4t57fh) ([raw file](https://github.com/starkware-libs/cairo/blob/39eaba10ee6ef0f393e66db1330bb36c873628f9/corelib/src/starknet/storage.cairo#L670)):*
> ```Cairo
> 
> 
> pub trait StorageArrayTrait<T> {
> ```

generate_trait?
(also below)
___
*[`corelib/src/starknet/storage.cairo` line 745 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5974#-O1C9Pq14duMNOAYVcqq:-O1C9Pq14duMNOAYVcqr:bu5qq8i) ([raw file](https://github.com/starkware-libs/cairo/blob/39eaba10ee6ef0f393e66db1330bb36c873628f9/corelib/src/starknet/storage.cairo#L745)):*
> ```Cairo
>         self.as_path().append()
>     }
> }
> ```

emptyline.

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5974)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @ArielElp and @orizi)

___
*[`corelib/src/starknet/storage.cairo` line 670 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5974#-O1C90rc1JAbvu6LuvhQ:-O1CRBIB9R9H3fTwtz5F:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/39eaba10ee6ef0f393e66db1330bb36c873628f9/corelib/src/starknet/storage.cairo#L670)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc all.
(also below)
</blockquote></details>

Done.
___
*[`corelib/src/starknet/storage.cairo` line 670 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5974#-O1C97LY2K2w3OeDEnMS:-O1CRCGBBCANSN3EpZzI:bxmh0px) ([raw file](https://github.com/starkware-libs/cairo/blob/39eaba10ee6ef0f393e66db1330bb36c873628f9/corelib/src/starknet/storage.cairo#L670)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

generate_trait?
(also below)
</blockquote></details>

Doesn't work, I guess because the generic arg and param are not exactly the same, I'll check it out later.
___
*[`corelib/src/starknet/storage.cairo` line 745 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5974#-O1C9Pq14duMNOAYVcqq:-O1CRC7P1nLVy8ENIVDf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/39eaba10ee6ef0f393e66db1330bb36c873628f9/corelib/src/starknet/storage.cairo#L745)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

emptyline.
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5974)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @ArielElp and @gilbens-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5974#-O1C4eSQ1PiHk1RLU6c8:-O1CcDGM-h9nioPBCcK9:b32v57) (no related file):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Draft - names and doc tbd.
</blockquote></details>

+1

___
___
*[`corelib/src/starknet/storage.cairo` line 670 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5974#-O1C97LY2K2w3OeDEnMS:-O1CVAoY6-FUPjj4hvNL:bb2wjw6) ([raw file](https://github.com/starkware-libs/cairo/blob/39eaba10ee6ef0f393e66db1330bb36c873628f9/corelib/src/starknet/storage.cairo#L670)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Doesn't work, I guess because the generic arg and param are not exactly the same, I'll check it out later.
</blockquote></details>

you are correct.
___
*[`corelib/src/starknet/storage.cairo` line 649 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5974#-O1CcMXb6y-zMjHxXwPA:-O1CcMXb6y-zMjHxXwPB:bu98c4v) ([raw file](https://github.com/starkware-libs/cairo/blob/fddae146ba835fa295a188a5041d2068c307d429/corelib/src/starknet/storage.cairo#L649)):*
> ```Cairo
> }
> 
> /// A type to represent an array in storage. The length of the storage is stored in the storage
> ```

maybe should be added to its own submodule file?
(and possibly for `Map` as well)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5974)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @ArielElp and @orizi)

___
*[`corelib/src/starknet/storage.cairo` line 649 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5974#-O1CcMXb6y-zMjHxXwPA:-O1GSr1z0gL6oX7MJOfg:bv2gael) ([raw file](https://github.com/starkware-libs/cairo/blob/fddae146ba835fa295a188a5041d2068c307d429/corelib/src/starknet/storage.cairo#L649)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe should be added to its own submodule file?
(and possibly for `Map` as well)
</blockquote></details>

Done. Will do `Map` in a separate pr.

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5974)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @ArielElp and @gilbens-starkware)

___
*[`-- commits` line 4 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5974#-O1GTIpNDIHcLf0on_89):*
rebase

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5974)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @ArielElp and @orizi)

___
*[`-- commits` line 4 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5974#-O1GTIpNDIHcLf0on_89):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rebase
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5974)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @ArielElp and @gilbens-starkware)

___
*[`corelib/src/starknet/storage.cairo` line 9 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5974#-O1Gg_4DE-7QvnKsOGX3:-O1Gg_4DE-7QvnKsOGX4:bnxcegb) ([raw file](https://github.com/starkware-libs/cairo/blob/02a0d68a683a5413d5452a6e38de8135f5a66775/corelib/src/starknet/storage.cairo#L9)):*
> ```Cairo
> 
> mod array;
> pub use array::{StorageArray, StorageArrayTrait, MutableStorageArrayTrait};
> ```

are we changing to vector?
(as the interface is different enough from our array in any case)



_Code quote:_
```Cairo
mod array;
pub use array::{StorageArray, StorageArrayTrait, MutableStorageArrayTrait};
```
___
*[`crates/cairo-lang-starknet/cairo_level_tests/storage_access.cairo` line 84 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5974#-O1Ggs_S6la62_jq-TRJ:-O1Ggs_S6la62_jq-TRK:ba89zj7) ([raw file](https://github.com/starkware-libs/cairo/blob/02a0d68a683a5413d5452a6e38de8135f5a66775/crates/cairo-lang-starknet/cairo_level_tests/storage_access.cairo#L84)):*
> ```Cairo
> #[starknet::storage_node]
> struct StorageArrays {
>     array: StorageArray<u32>,
> ```

`Array<T>` is equivalent to`Map<u64, T>` value wise?
if so, add direct test accessing members (using `contract_state_for_testing`, and direct assignment and read in one and the other)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5974)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @ArielElp and @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/storage_access.cairo` line 84 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5974#-O1Ggs_S6la62_jq-TRJ:-O1GhDH971p3X8js7cJL:b-tjrrt8) ([raw file](https://github.com/starkware-libs/cairo/blob/02a0d68a683a5413d5452a6e38de8135f5a66775/crates/cairo-lang-starknet/cairo_level_tests/storage_access.cairo#L84)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

`Array<T>` is equivalent to`Map<u64, T>` value wise?
if so, add direct test accessing members (using `contract_state_for_testing`, and direct assignment and read in one and the other)
</blockquote></details>

(i know array has length as well, but ignore it for testing value location wise)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5974)* status: 1 of 6 files reviewed, 4 unresolved discussions (waiting on @ArielElp and @orizi)

___
*[`corelib/src/starknet/storage.cairo` line 9 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5974#-O1Gg_4DE-7QvnKsOGX3:-O1Iss5aDVFmxa4jSOae:bk740ng) ([raw file](https://github.com/starkware-libs/cairo/blob/02a0d68a683a5413d5452a6e38de8135f5a66775/corelib/src/starknet/storage.cairo#L9)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

are we changing to vector?
(as the interface is different enough from our array in any case)
</blockquote></details>

I think that we do. Vector or Vec? And what about append? 
___
*[`crates/cairo-lang-starknet/cairo_level_tests/storage_access.cairo` line 84 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5974#-O1Ggs_S6la62_jq-TRJ:-O1IslQc-tx75Vaqkku5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/02a0d68a683a5413d5452a6e38de8135f5a66775/crates/cairo-lang-starknet/cairo_level_tests/storage_access.cairo#L84)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

(i know array has length as well, but ignore it for testing value location wise)
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5974)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @ArielElp and @gilbens-starkware)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5974)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @ArielElp and @orizi)

___
*[`corelib/src/starknet/storage.cairo` line 9 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5974#-O1Gg_4DE-7QvnKsOGX3:-O1Lh0EYBG6fSKwkdBUS:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/02a0d68a683a5413d5452a6e38de8135f5a66775/corelib/src/starknet/storage.cairo#L9)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

I think that we do. Vector or Vec? And what about append?
</blockquote></details>

Done

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5974)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @ArielElp and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5974#-O1C4eSQ1PiHk1RLU6c8:-O1Lh4IrEdDGoZjyZcni:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

___

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r6, 3 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5974)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @ArielElp and @gilbens-starkware)

___
*[`corelib/src/starknet/storage.cairo` line 9 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5974#-O1Gg_4DE-7QvnKsOGX3:-O1LhCrPEnDsUnJur6Se:bfd9t5j) ([raw file](https://github.com/starkware-libs/cairo/blob/02a0d68a683a5413d5452a6e38de8135f5a66775/corelib/src/starknet/storage.cairo#L9)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Done
</blockquote></details>

if we are going for `Vec` no need for the disabguiation with `Storage` prefix. - just `Vec` like `Map`.

for full name - user can just use `starknet::storage::Vec`.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/collections_test.cairo` line 24 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5974#-O1LhVlB-aWmUuicgj54:-O1LhVlB-aWmUuicgj55:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f7e928edac710cf14407c914eafc1152e18eac80/crates/cairo-lang-starknet/cairo_level_tests/collections_test.cairo#L24)):*
> ```Cairo
>         nested: StorageVec::<StorageVec<u32>>,
>     }
> }
> ```





_Suggestion:_
```Cairo
mod contract_with_map {
    use starknet::storage::Map;
    #[storage]
    struct Storage {
        simple: Map<u64, u32>,
        nested: Map<u64, Map<u64, u32>>,
    }
}

#[starknet::contract]
mod contract_with_vec {
    use starknet::storage::StorageVec;
    #[storage]
    struct Storage {
        simple: StorageVec<u32>,
        nested: StorageVec<StorageVec<u32>>,
    }
}
```
___
*[`crates/cairo-lang-starknet/cairo_level_tests/lib.cairo` line 29 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5974#-O1LhZP79k10BCvSj6BU:-O1LhZP79k10BCvSj6BV:bt006ng) ([raw file](https://github.com/starkware-libs/cairo/blob/f7e928edac710cf14407c914eafc1152e18eac80/crates/cairo-lang-starknet/cairo_level_tests/lib.cairo#L29)):*
> ```Cairo
> mod utils;
> #[cfg(test)]
> mod collections_test;
> ```

empty line

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5974)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @ArielElp and @orizi)

___
*[`corelib/src/starknet/storage.cairo` line 9 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5974#-O1Gg_4DE-7QvnKsOGX3:-O1LiuKh410Kmg5dHEri:b-k345h4) ([raw file](https://github.com/starkware-libs/cairo/blob/02a0d68a683a5413d5452a6e38de8135f5a66775/corelib/src/starknet/storage.cairo#L9)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

if we are going for `Vec` no need for the disabguiation with `Storage` prefix. - just `Vec` like `Map`.

for full name - user can just use `starknet::storage::Vec`.
</blockquote></details>

Done.
Changed also the traits, e.g. `starknet::storage::VecTrait` but not sure if it's better.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/collections_test.cairo` line 24 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5974#-O1LhVlB-aWmUuicgj54:-O1LisqH5iW_RN6Xl0rM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f7e928edac710cf14407c914eafc1152e18eac80/crates/cairo-lang-starknet/cairo_level_tests/collections_test.cairo#L24)):*
> ```Cairo
>         nested: StorageVec::<StorageVec<u32>>,
>     }
> }
> ```

Done.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/lib.cairo` line 29 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5974#-O1LhZP79k10BCvSj6BU:-O1LiCsN6dlovy-FNeeW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f7e928edac710cf14407c914eafc1152e18eac80/crates/cairo-lang-starknet/cairo_level_tests/lib.cairo#L29)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

empty line
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r8, 5 of 5 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5974)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ArielElp and @gilbens-starkware)

___
*[`corelib/src/starknet/storage.cairo` line 9 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5974#-O1Gg_4DE-7QvnKsOGX3:-O1LjBp-7Ju9Rkk2g1zS:b-pufvgi) ([raw file](https://github.com/starkware-libs/cairo/blob/02a0d68a683a5413d5452a6e38de8135f5a66775/corelib/src/starknet/storage.cairo#L9)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Done.
Changed also the traits, e.g. `starknet::storage::VecTrait` but not sure if it's better.
</blockquote></details>

in `Map` is it `MapTrait`? - if so probably revert that specifically.

**Review by orizi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5974)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp and @gilbens-starkware)

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5974)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp and @orizi)

___
*[`corelib/src/starknet/storage.cairo` line 9 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5974#-O1Gg_4DE-7QvnKsOGX3:-O1LjT836iqQwpGwV_zz:b-in24r1) ([raw file](https://github.com/starkware-libs/cairo/blob/02a0d68a683a5413d5452a6e38de8135f5a66775/corelib/src/starknet/storage.cairo#L9)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

in `Map` is it `MapTrait`? - if so probably revert that specifically.
</blockquote></details>

`Map` have only `entry`, so it is named `StoragePathEntry` as the same interface can be implemented for other types, but I don't see any such type for now so maybe It should be changed?

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5974)* status: all files reviewed, 2 unresolved discussions (waiting on @ArielElp and @gilbens-starkware)

___
*[`corelib/src/starknet/storage/vec.cairo` line 45 at r9](https://reviewable.io/reviews/starkware-libs/cairo/5974#-O1Lnud69YFisgpoT4xG:-O1Lnud69YFisgpoT4xH:bhrw62f) ([raw file](https://github.com/starkware-libs/cairo/blob/2b340464f3a93ad52b5faa1fad954e940eed5d36/corelib/src/starknet/storage/vec.cairo#L45)):*
> ```Cairo
>         assert!(index < vec_len, "Index out of bounds");
>         self.update(index)
>     }
> ```

have `get` instead - return option.

`at` would probably be through the `index` trait.



_Code quote:_
```Cairo
    fn at(self: StoragePath<Vec<T>>, index: u64) -> StoragePath<T> {
        let vec_len = self.len();
        assert!(index < vec_len, "Index out of bounds");
        self.update(index)
    }
```

**Review by gilbens-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5974)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @ArielElp and @orizi)

___
*[`corelib/src/starknet/storage/vec.cairo` line 45 at r9](https://reviewable.io/reviews/starkware-libs/cairo/5974#-O1Lnud69YFisgpoT4xG:-O1M7-IC8k_RkuRuZQOK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2b340464f3a93ad52b5faa1fad954e940eed5d36/corelib/src/starknet/storage/vec.cairo#L45)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

have `get` instead - return option.

`at` would probably be through the `index` trait.
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5974#-:-O1MCl5761E_GgUFE2wh:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArielElp)

**Pull request merged**
