### PR TITLE
LS: Refresh diagnostics in separate thread

### LINKED ISSUE #6318: LS: Rework diagnostics locks to bounded queue
Rework current locks to bounded queue with 0 or 1 element. 

- on request push to queue and do NOT wait
- create job in separate thread to pull from queue in loop and recalculate diagnostics

### PR DESCRIPTION
**Pull request by mkaput**
fix #6318

---

**Stack**:
- #6518
- #6517
- #6516
- #6515
- #6508 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by mkaput — COMMENTED** [review]
> Dismissed @Draggu from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6508)* status: 5 of 8 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/server/sync/mod.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/cairo/6508#-O9t8StT2Ksbqhr7HfcU:-O9uCri-4f71U8ZwSEpy:bsmxf0d) ([raw file](https://github.com/starkware-libs/cairo/blob/c4c32e3c74d70259deb1b75958541135a958d09f/crates/cairo-lang-language-server/src/server/sync/mod.rs#L)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

Don't think this should live in `server/` but no strong opinion on this.
</blockquote></details>

there's no better place and I don't want to create `utils` module
___
*[`crates/cairo-lang-language-server/src/server/sync/trigger.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6508#-O9t9Osi6Xsnp-bPv6LS:-O9uCqft26NLlWbIZjgi:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c4c32e3c74d70259deb1b75958541135a958d09f/crates/cairo-lang-language-server/src/server/sync/trigger.rs#L39)):*
> ```XML
> pub fn trigger<T>() -> (Trigger<T>, Actuator<T>) {
>     let inner = Arc::new(Inner { mutex: Mutex::new(State::Pending), condvar: Condvar::new() });
>     (Trigger(Arc::clone(&inner)), Actuator(inner))
> ```

Done.
___
*[`crates/cairo-lang-language-server/src/server/sync/trigger.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6508#-O9t7TZcCJV2OtwHn-EQ:-O9uCnjlE2RITZZrHSdm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c4c32e3c74d70259deb1b75958541135a958d09f/crates/cairo-lang-language-server/src/server/sync/trigger.rs#L122)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

More explicit and readable.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/server/sync/trigger.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6508#-O9t7f4-02S_wZPJnvjV:-O9uCo1jErUqVMQT2ZkF:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c4c32e3c74d70259deb1b75958541135a958d09f/crates/cairo-lang-language-server/src/server/sync/trigger.rs#L123)):*
> ```XML
>                 }
>                 State::Activate(value) => break Some(value),
>                 State::Disconnect => break None,
> ```

Done.

**Review by Draggu — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6508#-:-O9uHW1m4OHyBnQIJI0M:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @orizi, and @piotmag769)

**Review by piotmag769 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 8 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6508#-:-O9yVOk01xrNUtReE1Yf:bnfp4nl)* status: all files reviewed, 10 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/src/server/sync/mod.rs` line 3 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6508#-O9yW2oy4izRFpFksQL8:-O9yW2oy4izRFpFksQL9:b-x394hd) ([raw file](https://github.com/starkware-libs/cairo/blob/161e105fe2d2c1cedea6ac75f4e19959706a7523/crates/cairo-lang-language-server/src/server/sync/mod.rs#L3)):*
> ```XML
> //! Useful synchronisation primitives used in CairoLS.
> 
> pub mod trigger;
> ```

Do you plan to put anything else in this module? If not we could just put the code in `crates/cairo-lang-language-server/src/server/sync.rs`

Also do we really want this code in the`server` module? It is only used in `lang/diagnostics` so imo put it there or in another module
___
*[`crates/cairo-lang-language-server/src/server/sync/trigger.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6508#-O9yX81e1R02TsL3G6GU:-O9yX81e1R02TsL3G6GV:b-l7829n) ([raw file](https://github.com/starkware-libs/cairo/blob/161e105fe2d2c1cedea6ac75f4e19959706a7523/crates/cairo-lang-language-server/src/server/sync/trigger.rs#L23)):*
> ```XML
> ///
> /// Trigger is an in-house synchronisation primitive that allows signalling a single piece of work
> /// to do within a pair of controller and worker threads.
> ```

I think we should describe first what this pattern actually does and then later explain how it can be used. Since it is a primitive I would like to know what it actually does first, without the additional abstraction layer of the potential use case. "allows signalling a single piece of work" can mean anything at this point in the text
___
*[`crates/cairo-lang-language-server/src/server/sync/trigger.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6508#-O9yZ1FN8IUPJDw8jU8Y:-O9yZ1FN8IUPJDw8jU8Z:b-97tzt4) ([raw file](https://github.com/starkware-libs/cairo/blob/161e105fe2d2c1cedea6ac75f4e19959706a7523/crates/cairo-lang-language-server/src/server/sync/trigger.rs#L26)):*
> ```XML
> /// In case multiple pieces of work are sent (_activated the trigger_) before worker thread manages
> /// to process them, only the last one will be processed.
> /// So, this primitive behaves like a 1-bounded synchronous single-producer single-consumer channel,
> ```

This is should be in the first sentence of the explanation imo
___
*[`crates/cairo-lang-language-server/src/server/sync/trigger.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6508#-O9y_1EQAvCuFFicdbXK:-O9y_1EQAvCuFFicdbXL:bdqbrsk) ([raw file](https://github.com/starkware-libs/cairo/blob/161e105fe2d2c1cedea6ac75f4e19959706a7523/crates/cairo-lang-language-server/src/server/sync/trigger.rs#L82)):*
> ```XML
>     Activate(T),
>     Disconnect,
> }
> ```

Triggered/Activated are both fine, just use adjectives/present participles



_Suggestion:_
```XML
enum State<T> {
    Pending,
    Triggered(T),
    Disconnected,
}
```
___
*[`crates/cairo-lang-language-server/src/server/sync/trigger.rs` line 85 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6508#-O9y_I-V2fxOSsGsJDlG:-O9y_I-V2fxOSsGsJDlH:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/161e105fe2d2c1cedea6ac75f4e19959706a7523/crates/cairo-lang-language-server/src/server/sync/trigger.rs#L85)):*
> ```XML
> 
> struct Inner<T> {
>     mutex: Mutex<State<T>>,
> ```





_Suggestion:_
```XML
    state_mutex: Mutex<State<T>>,
```
___
*[`crates/cairo-lang-language-server/src/server/sync/trigger.rs` line 93 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6508#-O9y_bjEEy9JGVT00v9_:-O9y_bjEEy9JGVT00v9a:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/161e105fe2d2c1cedea6ac75f4e19959706a7523/crates/cairo-lang-language-server/src/server/sync/trigger.rs#L93)):*
> ```XML
>         let &Inner { mutex, condvar } = &self;
> 
>         let mut guard = mutex.lock().expect(POISON_PANIC);
> ```





_Suggestion:_
```XML
let mut state_guard = mutex.lock().expect(POISON_PANIC);
```
___
*[`crates/cairo-lang-language-server/src/server/sync/trigger.rs` line 111 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6508#-O9y_l9Z3MwbTxxDAMIy:-O9y_l9Z3MwbTxxDAMIz:bglglrq) ([raw file](https://github.com/starkware-libs/cairo/blob/161e105fe2d2c1cedea6ac75f4e19959706a7523/crates/cairo-lang-language-server/src/server/sync/trigger.rs#L111)):*
> ```XML
>         // This loop is a regular wait-with-condition pattern,
>         // but written in a type and panic-safe manner.
>         let mut guard = mutex.lock().expect(POISON_PANIC);
> ```

Vide supra

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6508)* status: all files reviewed, 14 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6508#-O9yhKH35JmCODMhWUb8:-O9yhKH35JmCODMhWUb9:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/161e105fe2d2c1cedea6ac75f4e19959706a7523/crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs#L23)):*
> ```XML
> pub struct DiagnosticsController {
>     // NOTE: The trigger MUST be dropped before worker's join handle.
>     //   Otherwise, the worker will never be requested to stop.
> ```





_Suggestion:_
```XML
    // NOTE: Order of members matters here!
    //   The trigger MUST be dropped before worker's join handle.
    //   Otherwise, the worker will never drop, thus the worker thread will never join.
```
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6508#-O9ygGYr-gyqTzsXGMNR:-O9ygGYr-gyqTzsXGMNS:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/161e105fe2d2c1cedea6ac75f4e19959706a7523/crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs#L24)):*
> ```XML
>     // NOTE: The trigger MUST be dropped before worker's join handle.
>     //   Otherwise, the worker will never be requested to stop.
>     trigger: trigger::Sender<WorkerArgs>,
> ```





_Suggestion:_
```XML
sender: trigger::Sender<WorkerArgs>,
```
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6508#-O9ygOAH4VFo0rjcAC-s:-O9ygOAH4VFo0rjcAC-t:b-ertjfn) ([raw file](https://github.com/starkware-libs/cairo/blob/161e105fe2d2c1cedea6ac75f4e19959706a7523/crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs#L28)):*
> ```XML
> }
> 
> struct WorkerArgs {
> ```

Can we define it at the end of the file? It seems like an important struct being so far up, but it is just a data wrapper
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6508#-O9yg3tN604FqpY7c_oe:-O9yg3tN604FqpY7c_of:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/161e105fe2d2c1cedea6ac75f4e19959706a7523/crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs#L36)):*
> ```XML
>     /// Creates a new diagnostics controller.
>     pub fn new() -> Self {
>         let (trigger, recv) = trigger();
> ```





_Suggestion:_
```XML
let (sender, receiver) = trigger();
```
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs` line 52 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6508#-O9yh5zg3VEE25O57ap5:-O9yh5zg3VEE25O57ap6:b-hyb55d) ([raw file](https://github.com/starkware-libs/cairo/blob/161e105fe2d2c1cedea6ac75f4e19959706a7523/crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs#L52)):*
> ```XML
> 
>     /// Runs diagnostics controller's event loop.
>     fn control_loop(recv: trigger::Receiver<WorkerArgs>) {
> ```

`recv` looks like a method name



_Suggestion:_
```XML
receiver
```

**Review by mkaput — COMMENTED** [review]
> Dismissed @Draggu from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6508)* status: 3 of 8 files reviewed, 10 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6508#-O9yhKH35JmCODMhWUb8:-O9z8G9_Bsy4Au1L6wRQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/161e105fe2d2c1cedea6ac75f4e19959706a7523/crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs#L23)):*
> ```XML
> pub struct DiagnosticsController {
>     // NOTE: The trigger MUST be dropped before worker's join handle.
>     //   Otherwise, the worker will never be requested to stop.
> ```

Done.
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6508#-O9ygGYr-gyqTzsXGMNR:-O9z6sCVCQwiKbcca-1v:b2trb6p) ([raw file](https://github.com/starkware-libs/cairo/blob/161e105fe2d2c1cedea6ac75f4e19959706a7523/crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs#L24)):*
> ```XML
>     // NOTE: The trigger MUST be dropped before worker's join handle.
>     //   Otherwise, the worker will never be requested to stop.
>     trigger: trigger::Sender<WorkerArgs>,
> ```

imho that's worse name because `sender` by itself is ambiguous.
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6508#-O9ygOAH4VFo0rjcAC-s:-O9z71Ga5fmVzy0XXOfw:b-kqzg8x) ([raw file](https://github.com/starkware-libs/cairo/blob/161e105fe2d2c1cedea6ac75f4e19959706a7523/crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs#L28)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Can we define it at the end of the file? It seems like an important struct being so far up, but it is just a data wrapper
</blockquote></details>

disagree, it would appear after usages which are within `impl DiagnosticController`
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6508#-O9yg3tN604FqpY7c_oe:-O9z7ESB1gLMY4HyrlWN:bsfdxmq) ([raw file](https://github.com/starkware-libs/cairo/blob/161e105fe2d2c1cedea6ac75f4e19959706a7523/crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs#L36)):*
> ```XML
>     /// Creates a new diagnostics controller.
>     pub fn new() -> Self {
>         let (trigger, recv) = trigger();
> ```

1. not changing `trigger` because of the same concern as https://reviewable.io/reviews/starkware-libs/cairo/6508#-O9ygGYr-gyqTzsXGMNR (i'm making use of field shorthand initialization)
2. changed `receiver`
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs` line 52 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6508#-O9yh5zg3VEE25O57ap5:-O9z7RiI82UotKvg5sqs:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/161e105fe2d2c1cedea6ac75f4e19959706a7523/crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs#L52)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

`recv` looks like a method name
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/server/sync/mod.rs` line 3 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6508#-O9yW2oy4izRFpFksQL8:-O9z7TYE15wTwK-pOHcl:b-fp1nje) ([raw file](https://github.com/starkware-libs/cairo/blob/161e105fe2d2c1cedea6ac75f4e19959706a7523/crates/cairo-lang-language-server/src/server/sync/mod.rs#L3)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Do you plan to put anything else in this module? If not we could just put the code in `crates/cairo-lang-language-server/src/server/sync.rs`

Also do we really want this code in the`server` module? It is only used in `lang/diagnostics` so imo put it there or in another module
</blockquote></details>

Moved to diagnostics, though my intuition dislikes it.
___
*[`crates/cairo-lang-language-server/src/server/sync/trigger.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6508#-O9yX81e1R02TsL3G6GU:-O9z8b5W1vd2EwFSuYVp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/161e105fe2d2c1cedea6ac75f4e19959706a7523/crates/cairo-lang-language-server/src/server/sync/trigger.rs#L23)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

I think we should describe first what this pattern actually does and then later explain how it can be used. Since it is a primitive I would like to know what it actually does first, without the additional abstraction layer of the potential use case. "allows signalling a single piece of work" can mean anything at this point in the text
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/server/sync/trigger.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6508#-O9yZ1FN8IUPJDw8jU8Y:-O9z8bGl851CGcXniu_q:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/161e105fe2d2c1cedea6ac75f4e19959706a7523/crates/cairo-lang-language-server/src/server/sync/trigger.rs#L26)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

This is should be in the first sentence of the explanation imo
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/server/sync/trigger.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6508#-O9y_1EQAvCuFFicdbXK:-O9z6btkBzUOmWJDDvae:bcu52gs) ([raw file](https://github.com/starkware-libs/cairo/blob/161e105fe2d2c1cedea6ac75f4e19959706a7523/crates/cairo-lang-language-server/src/server/sync/trigger.rs#L82)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Triggered/Activated are both fine, just use adjectives/present participles
</blockquote></details>

But past tense is misleading here because this is a state **before** activation happens.
___
*[`crates/cairo-lang-language-server/src/server/sync/trigger.rs` line 85 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6508#-O9y_I-V2fxOSsGsJDlG:-O9z7o8q3VZquy_TikXz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/161e105fe2d2c1cedea6ac75f4e19959706a7523/crates/cairo-lang-language-server/src/server/sync/trigger.rs#L85)):*
> ```XML
> 
> struct Inner<T> {
>     mutex: Mutex<State<T>>,
> ```

Done.
___
*[`crates/cairo-lang-language-server/src/server/sync/trigger.rs` line 93 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6508#-O9y_bjEEy9JGVT00v9_:-O9z7odQ0q40zJ892Hoz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/161e105fe2d2c1cedea6ac75f4e19959706a7523/crates/cairo-lang-language-server/src/server/sync/trigger.rs#L93)):*
> ```XML
>         let &Inner { mutex, condvar } = &self;
> 
>         let mut guard = mutex.lock().expect(POISON_PANIC);
> ```

Done.

**Review by mkaput — COMMENTED** [review]
> Dismissed @piotmag769 from 4 discussions.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6508)* status: 3 of 8 files reviewed, 6 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

**Review by piotmag769 — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6508)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6508#-O9yhKH35JmCODMhWUb8:-OA-uJgXAKJvX_FPgftQ:bv1uk6g) ([raw file](https://github.com/starkware-libs/cairo/blob/161e105fe2d2c1cedea6ac75f4e19959706a7523/crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs#L23)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done actually, but unblocking
___
*[`crates/cairo-lang-language-server/src/server/sync/trigger.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6508#-O9y_1EQAvCuFFicdbXK:-OA-vWqtAnYkjq1XWFwi:b-jhfj0a) ([raw file](https://github.com/starkware-libs/cairo/blob/161e105fe2d2c1cedea6ac75f4e19959706a7523/crates/cairo-lang-language-server/src/server/sync/trigger.rs#L82)):*
Isn't it the state after the activation (send)? You even used it in a past tense in the comment above

>  /// In case the trigger is already activated but has not been yet picked up by the receiver,
>   /// the value will overwrite the one buffered.

Unblocking anyways

**Review by mkaput — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6508)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @orizi)

___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6508#-O9yhKH35JmCODMhWUb8:-OA1WPQj1Lll5ornQBgP:b-535swd) ([raw file](https://github.com/starkware-libs/cairo/blob/161e105fe2d2c1cedea6ac75f4e19959706a7523/crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs#L23)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Not done actually, but unblocking
</blockquote></details>

done x2
___
*[`crates/cairo-lang-language-server/src/server/sync/trigger.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6508#-O9y_1EQAvCuFFicdbXK:-OA1clS00MVg7FgQ8r-5:b-1k1jr8) ([raw file](https://github.com/starkware-libs/cairo/blob/161e105fe2d2c1cedea6ac75f4e19959706a7523/crates/cairo-lang-language-server/src/server/sync/trigger.rs#L82)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Isn't it the state after the activation (send)? You even used it in a past tense in the comment above

>  /// In case the trigger is already activated but has not been yet picked up by the receiver,
>   /// the value will overwrite the one buffered.

Unblocking anyways
</blockquote></details>

ah I see your perspective. I was thinking of this all the time from receiver point of view, not the entire thing as a single piece. You're right, your tense is better in that context. Done

**Review by Draggu — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6508#-:-OA2A-iyCC9teoe6wAqq:bnfp4nl)* status: 6 of 8 files reviewed, all discussions resolved (waiting on @Arcticae, @orizi, and @piotmag769)

**Review by Arcticae — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6508#-:-OA2EfS0DOp903hgDAPa:bnfp4nl)* status: 6 of 8 files reviewed, all discussions resolved (waiting on @orizi and @piotmag769)

**Pull request merged**
