### PR TITLE
Rename delay_var_def -> reorder_statements.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3593)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3593)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3593#-NZWQf3J3Qe-cyloA3i9:-NZWQf3J3Qe-cyloA3iA:blvs81d) (no related file):*
the new files are missing.

___

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3593)* status: 8 of 10 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/optimizations/reorder_statements.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3593#-NZWSyIh17sO7DnWUUNB:-NZWSyIh17sO7DnWUUNC:b-l6mkjh) ([raw file](https://github.com/starkware-libs/cairo/blob/d6febce0680b8e05ff066e9fb7af7abd192603b3/crates/cairo-lang-lowering/src/optimizations/reorder_statements.rs#L62)):*
> ```XML
> 
> #[derive(Clone, Default)]
> pub struct DelayDefsInfo {
> ```

rename



_Code quote:_
```XML
 DelayDefsInfo
```
___
*[`crates/cairo-lang-lowering/src/optimizations/reorder_statements.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3593#-NZWSwOu-YoSvBUMXJEe:-NZWSwOu-YoSvBUMXJEf:b-l6mkjh) ([raw file](https://github.com/starkware-libs/cairo/blob/d6febce0680b8e05ff066e9fb7af7abd192603b3/crates/cairo-lang-lowering/src/optimizations/reorder_statements.rs#L69)):*
> ```XML
> }
> 
> pub struct DelayDefsContext<'a> {
> ```

rename

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3593)* status: 8 of 10 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/optimizations/reorder_statements.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3593#-NZWSyIh17sO7DnWUUNB:-NZWVT2_9nqH1gFkWaUA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d6febce0680b8e05ff066e9fb7af7abd192603b3/crates/cairo-lang-lowering/src/optimizations/reorder_statements.rs#L62)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rename
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/optimizations/reorder_statements.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3593#-NZWSwOu-YoSvBUMXJEe:-NZWVTLV2j6IV8Z_bH3e:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d6febce0680b8e05ff066e9fb7af7abd192603b3/crates/cairo-lang-lowering/src/optimizations/reorder_statements.rs#L69)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rename
</blockquote></details>

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3593#-:-NZWWxFCB5OTqDLZxGsB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3593)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
