### PR TITLE
Add StorageReadSysCallLibFunc.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1209)

### CODE REVIEW

**Review by spapinistarkware — DISMISSED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1209)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/sierra/src/extensions/modules/storage.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1209#-NISGEzU2ZHrNtfkWh9t:-NISGEzU2ZHrNtfkWh9u:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/cefad54d9876aa9326e36bbd4b0b43f31eaa070c/crates/sierra/src/extensions/modules/storage.rs#L13)):*
> ```XML
> use crate::program::GenericArg;
> 
> /// Type for StarkNet storage address, a value in the range [0, 2 * *251 - 256).
> ```





_Suggestion:_
```XML
** 
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 6 of 10 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1209)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1209)* status: 7 of 10 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1209#-:-NIbZJ4z72xmLXwJ7hQ2:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/sierra/src/extensions/modules/storage.rs` line 37 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1209#-NIbYXCt8pwN40Hq2nme:-NIbYXCt8pwN40Hq2nmf:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/4aa8dffb9ffd8eb58c4c9eb7c4f19cad9f5b4b65/crates/sierra/src/extensions/modules/storage.rs#L37)):*
> ```XML
> pub struct StorageRead {}
> impl SignatureOnlyGenericLibFunc for StorageRead {
>     const ID: GenericLibFuncId = GenericLibFuncId::new_inline("storage_read_syscall");
> ```

.



_Suggestion:_
```XML
/// LibFunc for a storage read system call.
#[derive(Default)]
pub struct StorageReadLibFunc {}
impl NoGenericArgsGenericLibFunc for StorageReadLibFunc {
    const ID: GenericLibFuncId = GenericLibFuncId::new_inline("storage_read_syscall");

    fn specialize_signature(
        &self,
        context: &dyn SignatureSpecializationContext,
    ) -> Result<LibFuncSignature, SpecializationError> {
        let ty = context.get_concrete_type(StorageAddressType::id(), &[])?;
        Ok(LibFuncSignature::new_non_branch_ex(
            vec![context.get_concrete_type(SyscallPtrType::id(), &[])?],
            vec![OutputVarInfo {
                ty,
                ref_info: OutputVarReferenceInfo::Deferred(DeferredOutputKind::Generic),
            }],
            SierraApChange::Known(0),
        ))
    }
}
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1209)* status: 5 of 10 files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/sierra/src/extensions/modules/storage.rs` line 37 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1209#-NIbYXCt8pwN40Hq2nme:-NIbhMr32d6mfmfppXzB:brcvz58) ([raw file](https://github.com/starkware-libs/cairo/blob/4aa8dffb9ffd8eb58c4c9eb7c4f19cad9f5b4b65/crates/sierra/src/extensions/modules/storage.rs#L37)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
+ other issues :(

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1209#-:-NIbiaqX8Lz6BCv-AOZO:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 10 files at r1, 1 of 4 files at r2, 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1209)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1209)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1209)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r3, 2 of 5 files at r5, 3 of 3 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1209)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by orizi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1209)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 1 of 4 files at r2, 1 of 4 files at r3, 2 of 5 files at r5, 3 of 3 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1209)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
