### PR TITLE
Pattern hint

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3746)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3744** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3744" target="_blank">Graphite</a> 
    * **PR #3745** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3745" target="_blank">Graphite</a> 
      * **PR #3746** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/3746" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/3746?utm_source=stack-comment).

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3746)* status: 3 of 13 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/items/trt.rs` line 671 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3746#-Na6mZDE62nlTVZV0a60:-Na6mZDE62nlTVZV0a61:b-7vmbrj) ([raw file](https://github.com/starkware-libs/cairo/blob/dee1f3837bbb23da58fd6117121fcd7ac14b40e8/crates/cairo-lang-semantic/src/items/trt.rs#L671)):*
> ```XML
>         diagnostics: diagnostics.build(),
>         expr_lookup,
>         pat_lookup,
> ```

all around



_Suggestion:_
```XML
        pattern_lookup,
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3746)* status: 1 of 13 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/items/trt.rs` line 671 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3746#-Na6mZDE62nlTVZV0a60:-Na6u9XV-_oPc_QHulfp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/dee1f3837bbb23da58fd6117121fcd7ac14b40e8/crates/cairo-lang-semantic/src/items/trt.rs#L671)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

all around
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 13 files at r1, 3 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3746)* status: 6 of 13 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 80 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3746#-Na76RxTEsMb0WHbGQYJ:-Na76RxUAuyCI0UyZrOS:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f7562145a7ac248ae9643e0d8d1911c1fa0e1ba2/crates/cairo-lang-semantic/src/expr/compute.rs#L80)):*
> ```XML
>     environment: Box<Environment>,
>     pub exprs: Arena<semantic::Expr>,
>     pub pats: Arena<semantic::Pattern>,
> ```





_Suggestion:_
```XML
patterns
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3746)* status: 9 of 13 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/test_data/match` line 161 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3746#-Na76wlxCCWVKlhvygT_:-Na76wlxCCWVKlhvygTa:b74te3f) ([raw file](https://github.com/starkware-libs/cairo/blob/f7562145a7ac248ae9643e0d8d1911c1fa0e1ba2/crates/cairo-lang-lowering/src/test_data/match#L161)):*
> ```
> error: Only match zero (match ... { 0 => ..., _ => ... }) is currently supported.
>  --> lib.cairo:5:7
>       1 => 7,
> ```

what caused this change?



_Code quote:_
```
1 => 7,
```
___
*[`crates/cairo-lang-semantic/src/items/function_with_body.rs` line 132 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3746#-Na76ikB0zafDNnF-BCY:-Na76ikB0zafDNnF-BCZ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f7562145a7ac248ae9643e0d8d1911c1fa0e1ba2/crates/cairo-lang-semantic/src/items/function_with_body.rs#L132)):*
> ```XML
> pub struct FunctionBody {
>     pub exprs: Arena<semantic::Expr>,
>     pub pats: Arena<semantic::Pattern>,
> ```





_Suggestion:_
```XML
patterns
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3746)* status: 9 of 13 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/test_data/match` line 161 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3746#-Na76wlxCCWVKlhvygT_:-NaAkL7mChpWT5b8y7Xa:b-lu0bj3) ([raw file](https://github.com/starkware-libs/cairo/blob/f7562145a7ac248ae9643e0d8d1911c1fa0e1ba2/crates/cairo-lang-lowering/src/test_data/match#L161)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

what caused this change?
</blockquote></details>

I gave a better location for the error.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 80 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3746#-Na76RxTEsMb0WHbGQYJ:-NaAkJReC1rDxZSXgsmd:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f7562145a7ac248ae9643e0d8d1911c1fa0e1ba2/crates/cairo-lang-semantic/src/expr/compute.rs#L80)):*
> ```XML
>     environment: Box<Environment>,
>     pub exprs: Arena<semantic::Expr>,
>     pub pats: Arena<semantic::Pattern>,
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/items/function_with_body.rs` line 132 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3746#-Na76ikB0zafDNnF-BCY:-NaAkKCRDHSZHOKomcak:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f7562145a7ac248ae9643e0d8d1911c1fa0e1ba2/crates/cairo-lang-semantic/src/items/function_with_body.rs#L132)):*
> ```XML
> pub struct FunctionBody {
>     pub exprs: Arena<semantic::Expr>,
>     pub pats: Arena<semantic::Pattern>,
> ```

Done.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3746#-:-NaAl36NBqyi0a-S5hum:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
