### PR TITLE
Add option for sorting imports in formatter

### LINKED ISSUE #3729: Sort external `mod` and `use` directives in cairo-formatter
# Feature Request (cairo-formatter)

Move external `mod` (defined in other files) and/or `use` lines to the top of the wrapper mod, sorted by some criteria.

**Describe Preferred Solution**

Convert this:

```
#[starknet::contract]
mod ReentrancyMock {
    use starknet::get_contract_address;

    #[storage]
    struct Storage {}

    use starknet::ContractAddress;
}
```

into this:

```
#[starknet::contract]
mod ReentrancyMock {
    use starknet::ContractAddress;
    use starknet::get_contract_address;

    #[storage]
    struct Storage {}
}
```

or this:

```
mod B;
use B::some;
mod C;
mod A;
use something;
use C::some;
```

into this:

```
mod A;
mod B;
mod C;

use something;
use B::some;
use C::some;
```

**Describe Alternatives**

I like alphabetical sort, but we could have a different criteria (like line length), or even a config file allowing us to change criterias.

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by ericnordelo**
Partially fixes #3729

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3778)

### CODE REVIEW

**Comment by ericnordelo** [comment]
@orizi This is the simplest solution I could come up with from the current implementation. It looks like comments on top of use clauses are also associated with the SyntaxNode and moved togheter. Any suggestion for improving the sorting function, or if you think there's a better direction for tackling this, that would be helpful. Also, this simple solution is not addressing merging.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3778)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @ericnordelo)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 630 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3778#-NaKf4oOAIohedz8ToYV:-NaKf4oOAIohedz8ToYW:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/63d7e81c0f04322350d3d711befc7ab0b830b2c1/crates/cairo-lang-formatter/src/formatter_impl.rs#L630)):*
> ```XML
>             children_iter.sort_by(cmp);
>         }
>         for (i, child) in children_iter {
> ```





_Suggestion:_
```XML
        let no_space_after = no_space_after || syntax_node.force_no_space_after(self.db);
        let mut children = syntax_node.children(self.db);
        let n_children = children.len();
        if self.config.sorted {
            children.sort_by_key(|c| MovableNode::new(self.db, c));
        }
        for (i, child) in children {
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 751 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3778#-NaKg1mHDTW6lvGNNl2T:-NaKg1mHDTW6lvGNNl2U:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/63d7e81c0f04322350d3d711befc7ab0b830b2c1/crates/cairo-lang-formatter/src/formatter_impl.rs#L751)):*
> ```XML
>         }
>     }
> }
> ```





_Suggestion:_
```XML
enum MovableNode {
    ItemModule(SmolStr),
    ItemUse(SmolStr),
    Immovable
}
impl MovableNode {
    fn new(db: &dyn SyntaxGroup, node: SyntaxNode) -> Self {
        match node.kind {
            SyntaxKind::ItemModule => {
                let item = ast::ItemModule::from_syntax_node(db, node);
                if matches!(item.body(db), MaybeModuleBody::None(_)) {
                    Self::ItemModule(item.name(db).text(db))
                } else {
                    Self::Immovable
                }
            }
            SyntaxKind::ItemUse => {
                let item = ast::ItemUse::from_syntax_node(db, node);
                let path_segment = match item.use_path(db) {
                    ast::UsePath::Leaf(leaf) => leaf.ident(db),
                    ast::UsePath::Single(single) => single.ident(db),
                    ast::UsePath::Multi(l) => return Self::Immovable,
                };
                Self::ItemUse(path_segment.identifier_ast(db).text(db))
            }
            _ => Self::Immovable,
        }
    }
}

impl Ord for MovableNode {
    fn cmp(&self, other: &Self) -> Ordering {
        match (self.kind, other.kind) {
            (MovableNode::Immovable, _) | (_, MovableNode::Immovable) => Ordering::Equal,
            (MovableNode::ItemModule(a), MovableNode::ItemModule(b)) | (MovableNode::ItemUse(a), MovableNode::ItemUse(b)) => a.cmp(b),
            (MovableNode::ItemModule(_), MovableNode::ItemUse(_)) => Ordering::Less,
            (MovableNode::ItemUse(_), MovableNode::ItemModule(_)) => Ordering::Greater,
        }
    }
}
```
___
*[`crates/cairo-lang-formatter/src/lib.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3778#-NaKeZBA8CNBWZU86fcc:-NaKeZBA8CNBWZU86fcd:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/63d7e81c0f04322350d3d711befc7ab0b830b2c1/crates/cairo-lang-formatter/src/lib.rs#L62)):*
> ```XML
>     tab_size: usize,
>     max_line_length: usize,
>     sorted: bool,
> ```

.



_Suggestion:_
```XML
    sort_module_level_items: bool,
```

**Review by ericnordelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3778)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 630 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3778#-NaKf4oOAIohedz8ToYV:-NaMCDzNCLMQifApmklx:b-o9tgx) ([raw file](https://github.com/starkware-libs/cairo/blob/63d7e81c0f04322350d3d711befc7ab0b830b2c1/crates/cairo-lang-formatter/src/formatter_impl.rs#L630)):*
> ```XML
>             children_iter.sort_by(cmp);
>         }
>         for (i, child) in children_iter {
> ```

Nice! I think we still need to collect into a vector for sorting in place (`SyntaxNodeChildIterator` doesn't implement sort methods).
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 751 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3778#-NaKg1mHDTW6lvGNNl2T:-NaMD-bc0iRrMrvFREdG:b1yryoi) ([raw file](https://github.com/starkware-libs/cairo/blob/63d7e81c0f04322350d3d711befc7ab0b830b2c1/crates/cairo-lang-formatter/src/formatter_impl.rs#L751)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

True so:
```
            (MovableNode::Immovable, MovableNode::Immovable) => Ordering::Equal,
            (MovableNode::ItemModule(a), MovableNode::ItemModule(b)) | (MovableNode::ItemUse(a), MovableNode::ItemUse(b)) => a.cmp(b),
            (_, MovableNode::Immovable) | (MovableNode::ItemModule(_), MovableNode::ItemUse(_)) => Ordering::Less,
            (MovableNode::Immovable, _) | (MovableNode::ItemUse(_), MovableNode::ItemModule(_)) => Ordering::Greater,
```
</blockquote></details>

Great improvement! A couple of things though:
- I think we don't want modules being implemented in place to be sorted. We just wanna move external mods imports (like `mod A;`)
- I think we want to sort use clauses by the full path, not the first path segment.

I'm working on that.
___
*[`crates/cairo-lang-formatter/src/lib.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3778#-NaKeZBA8CNBWZU86fcc:-NaMDfKo21lGX8pz7s3X:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/63d7e81c0f04322350d3d711befc7ab0b830b2c1/crates/cairo-lang-formatter/src/lib.rs#L62)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/test.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3778#-NaLXerr0ZNwANQgERjD:-NaMDjLt8PiH8T5oByuP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0ffaaf15857c9dfa919410720239402ea8f35299/crates/cairo-lang-formatter/src/test.rs#L36)):*
> ```XML
>     "test_data/expected_results/use_sorting.cairo"
> )]
> fn format_and_compare_file(unformatted_filename: &str, expected_filename: &str) {
> ```

Done.
___
*[`crates/cairo-lang-formatter/src/test.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3778#-NaLY0BA6k9Fjcjz3Q6e:-NaMDk69Ci0j35ClFctG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0ffaaf15857c9dfa919410720239402ea8f35299/crates/cairo-lang-formatter/src/test.rs#L51)):*
> ```XML
>     if unformatted_filename.ends_with("use_sorting.cairo") {
>         config.sorted = true;
>     }
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3778)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @ericnordelo and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 751 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3778#-NaKg1mHDTW6lvGNNl2T:-NaMFEDh7kVKmWohW4Bu:b-ijz5dh) ([raw file](https://github.com/starkware-libs/cairo/blob/63d7e81c0f04322350d3d711befc7ab0b830b2c1/crates/cairo-lang-formatter/src/formatter_impl.rs#L751)):*
<details><summary><i>Previously, ericnordelo (Eric Nordelo) wrote…</i></summary><blockquote>

Great improvement! A couple of things though:
- I think we don't want modules being implemented in place to be sorted. We just wanna move external mods imports (like `mod A;`)
- I think we want to sort use clauses by the full path, not the first path segment.

I'm working on that.

</blockquote></details>

that is why i checked if we have a body - and if so made it immovable.

**Review by ericnordelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3778)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 751 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3778#-NaKg1mHDTW6lvGNNl2T:-NaMJJIV14ybPXD0WhTi:bts5aii) ([raw file](https://github.com/starkware-libs/cairo/blob/63d7e81c0f04322350d3d711befc7ab0b830b2c1/crates/cairo-lang-formatter/src/formatter_impl.rs#L751)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

that is why i checked if we have a body - and if so made it immovable.
</blockquote></details>

You are correct, I miss that the first time I checked.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3778)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @ericnordelo and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 630 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3778#-NaKf4oOAIohedz8ToYV:-NaMKseq2yJmFLs4Ru6W:b-kkin8l) ([raw file](https://github.com/starkware-libs/cairo/blob/63d7e81c0f04322350d3d711befc7ab0b830b2c1/crates/cairo-lang-formatter/src/formatter_impl.rs#L630)):*
<details><summary><i>Previously, ericnordelo (Eric Nordelo) wrote…</i></summary><blockquote>

Nice! I think we still need to collect into a vector for sorting in place (`SyntaxNodeChildIterator` doesn't implement sort methods).
</blockquote></details>

you can also just directly use `sorted_by_key` on the iterator.

**Review by ericnordelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3778)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 630 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3778#-NaKf4oOAIohedz8ToYV:-NaMMpnqE-3fWB5hdEUg:brcgqbl) ([raw file](https://github.com/starkware-libs/cairo/blob/63d7e81c0f04322350d3d711befc7ab0b830b2c1/crates/cairo-lang-formatter/src/formatter_impl.rs#L630)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you can also just directly use `sorted_by_key` on the iterator.
</blockquote></details>

Yes, but that doesn't modify in place, and I cannot assign the new iterator to the `SyntaxNodeChildIterator` object.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3778)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @ericnordelo and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 718 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3778#-NaMc_Ry7vodwcSzpncf:-NaMc_Ry7vodwcSzpncg:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/f7ed27d586882f6600ab018276155fb013f82660/crates/cairo-lang-formatter/src/formatter_impl.rs#L718)):*
> ```XML
> 
> #[derive(PartialEq, Eq)]
> enum MovableNode {
> ```

doc
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 729 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3778#-NaMd--N4tzpZ6b9GEsX:-NaMd--N4tzpZ6b9GEsY:b7ekls8) ([raw file](https://github.com/starkware-libs/cairo/blob/f7ed27d586882f6600ab018276155fb013f82660/crates/cairo-lang-formatter/src/formatter_impl.rs#L729)):*
> ```XML
>                 let item = ast::ItemModule::from_syntax_node(db, node.clone());
>                 if matches!(item.body(db), MaybeModuleBody::None(_)) {
>                     Self::ItemModule(item.name(db).text(db).to_string())
> ```

what was wrong about the SmolStr?

**Review by ericnordelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3778)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 718 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3778#-NaMc_Ry7vodwcSzpncf:-NaMqu0_-BRo6HoTHXck:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f7ed27d586882f6600ab018276155fb013f82660/crates/cairo-lang-formatter/src/formatter_impl.rs#L718)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3778)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @ericnordelo and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 736 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3778#-NaQqsO03fX1IABe3NsZ:-NaQqsO03fX1IABe3Ns_:b-qcxljx) ([raw file](https://github.com/starkware-libs/cairo/blob/71ecc24735537c9bf2e0801b7ae8bb00dee313a4/crates/cairo-lang-formatter/src/formatter_impl.rs#L736)):*
> ```XML
>                 }
>             }
>             SyntaxKind::ItemUse => Self::ItemUse(node.clone().get_text_without_trivia(db).into()),
> ```

In my code suggestion i've shown how you can not use `get_text_*` - please do so.
I know it is more complex - but it is more resilient.
(especially that when we get to actually inserting and unpacking `use`s it would have to inspect this.



_Code quote:_
```XML
node.clone().get_text_without_trivia(db).into())
```

**Review by ericnordelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3778)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 736 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3778#-NaQqsO03fX1IABe3NsZ:-NaRNZ1qCfmC_7ATk-c2:b-5zaira) ([raw file](https://github.com/starkware-libs/cairo/blob/71ecc24735537c9bf2e0801b7ae8bb00dee313a4/crates/cairo-lang-formatter/src/formatter_impl.rs#L736)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

In my code suggestion i've shown how you can not use `get_text_*` - please do so.
I know it is more complex - but it is more resilient.
(especially that when we get to actually inserting and unpacking `use`s it would have to inspect this.
</blockquote></details>

No sure what I'm missing, but in your code suggestion only the first part of the path was being catch (the first PathSegment), and we need the full path for comparing. I would've assumed that the `ast::UsePath::Multi` branch would match the `use openzeppelin::introspection::second`, but is not. If you have a solution without using get_text for getting the full use path instead of the first element I'm happy yo use it.

In your suggestion, this was not correctly sorted, because only the first element of the path was checked, I don't know how to get the full path without using get_text.



_Code snippet:_
```XML
use openzeppelin::introspection::second;
use openzeppelin::introspection::first; 
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3778)* status: 3 of 6 files reviewed, all discussions resolved (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 736 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3778#-NaQqsO03fX1IABe3NsZ:-NaRTdJZ0qlVrixc0MAO:bg6qq3b) ([raw file](https://github.com/starkware-libs/cairo/blob/71ecc24735537c9bf2e0801b7ae8bb00dee313a4/crates/cairo-lang-formatter/src/formatter_impl.rs#L736)):*
<details><summary><i>Previously, ericnordelo (Eric Nordelo) wrote…</i></summary><blockquote>

No sure what I'm missing, but in your code suggestion only the first part of the path was being catch (the first PathSegment), and we need the full path for comparing. I would've assumed that the `ast::UsePath::Multi` branch would match the `use openzeppelin::introspection::second`, but is not. If you have a solution without using get_text for getting the full use path instead of the first element I'm happy yo use it.

In your suggestion, this was not correctly sorted, because only the first element of the path was checked, I don't know how to get the full path without using get_text.
</blockquote></details>

You are correct - sorry, but do note it would be the case when we start node merging.

**Review by ericnordelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3778)* status: 3 of 6 files reviewed, all discussions resolved (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 736 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3778#-NaQqsO03fX1IABe3NsZ:-NaRT7la8l5u7l7MEJCV:b-3qz8zu) ([raw file](https://github.com/starkware-libs/cairo/blob/71ecc24735537c9bf2e0801b7ae8bb00dee313a4/crates/cairo-lang-formatter/src/formatter_impl.rs#L736)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

You are correct - sorry, but do note it would be the case when we start node merging.
</blockquote></details>

Got it. I would like to leave merging for a different PR if you agree though (I can and want to work on that as well, but I think having sorting at least would help us a lot. We've been strugling a bit with manually sorting imports in OZ).

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3778)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 736 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3778#-NaQqsO03fX1IABe3NsZ:-NaRXbw_05Volhrbbid_:b-o6rr5s) ([raw file](https://github.com/starkware-libs/cairo/blob/71ecc24735537c9bf2e0801b7ae8bb00dee313a4/crates/cairo-lang-formatter/src/formatter_impl.rs#L736)):*
<details><summary><i>Previously, ericnordelo (Eric Nordelo) wrote…</i></summary><blockquote>

Got it. I would like to leave merging for a different PR if you agree though (I can and want to work on that as well, but I think having sorting at least would help us a lot. We've been strugling a bit with manually sorting imports in OZ). 
</blockquote></details>

totally fine.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3778)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @ericnordelo)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3778#-:-NaRYJMc9rEuCmA18pCN:bnfp4nl)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @ericnordelo)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3778)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ericnordelo)

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3778#-:-Na_bMigD4uu5HCiQYNT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ericnordelo)

**Pull request merged**
