### PR TITLE
U384 serde with 2 felts

### PR DESCRIPTION
**Pull request by shramee**

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6789)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @shramee)

___
*[`corelib/src/circuit.cairo` line 524 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6789#-OD5QwRi8raGGr6VHw77:-OD5QwRjCo5e9KDxvkmW:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ff6a5c882f7aa05798657b37ac91f256c7fc0a9e/corelib/src/circuit.cairo#L524)):*
> ```Cairo
> 
>         Option::Some(u384 { limb0, limb1, limb2, limb3 })
>     }
> ```





_Suggestion:_
```Cairo
    pub fn felt252_try_into_two_u96(value: felt252) -> Option<(u96, u96)> {
        let v: u256 = value.into();
        let (limb1_low32, limb0) = bounded_int::div_rem(v.low, NZ_POW96_TYPED);
        let limb1_high64: BoundedInt<0, { POW64 - 1 }> = downcast(v.high)?;
        let limb1 = bounded_int::add(bounded_int::mul(limb1_high64, POW32_TYPED), limb1_low32);
        Option::Some((limb0, limb1))
    }
```
___
*[`corelib/src/circuit.cairo` line 565 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6789#-OD5SfO6Bsc12eFt8oEg:-OD5SfO77xxMc-1i6DLU:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ff6a5c882f7aa05798657b37ac91f256c7fc0a9e/corelib/src/circuit.cairo#L565)):*
> ```Cairo
>             value.limb2.into() + value.limb3.into() * POW96
>         )
>     }
> ```





_Suggestion:_
```Cairo
    pub fn two_u96_into_felt252(limb0: u96, limb1: u96) -> felt252 {
        limb0.into() + limb1.into() * POW96
    }
```
___
*[`corelib/src/circuit.cairo` line 603 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6789#-OD5T4aq0ETbt3KAAYmV:-OD5T4aq0ETbt3KAAYmW:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ff6a5c882f7aa05798657b37ac91f256c7fc0a9e/corelib/src/circuit.cairo#L603)):*
> ```Cairo
>         output.append(l01);
>         output.append(l23);
>     }
> ```





_Suggestion:_
```Cairo
    fn serialize(self: @u384, ref output: Array<felt252>) {
        output.append(conversions::two_u96_into_felt252(*self.limb0, *self.limb1));
        output.append(conversions::two_u96_into_felt252(*self.limb2, *self.limb3));
    }
```
___
*[`corelib/src/circuit.cairo` line 607 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6789#-OD5Rw1U2j5XW3tcNaWd:-OD5Rw1U2j5XW3tcNaWe:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ff6a5c882f7aa05798657b37ac91f256c7fc0a9e/corelib/src/circuit.cairo#L607)):*
> ```Cairo
>     fn deserialize(ref serialized: Span<felt252>) -> Option<u384> {
>         let [l01, l23] = (*serialized.multi_pop_front::<2>()?).unbox();
>         return conversions::try_from_two_felt252((l01, l23));
> ```





_Suggestion:_
```Cairo
        let [l01, l23] = (*serialized.multi_pop_front::<2>()?).unbox();
        let (limb0, limb1) = conversions::felt252_try_into_two_u96(l01)?;
        let (limb2, limb3) = conversions::felt252_try_into_two_u96(l23)?;
        Ok(u384 { limb0, limb1, limb2, limb3 })
```
___
*[`corelib/src/test/circuit_test.cairo` line 155 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6789#-OD5TggFC6aRG1wKUc8c:-OD5TggFC6aRG1wKUc8d:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ff6a5c882f7aa05798657b37ac91f256c7fc0a9e/corelib/src/test/circuit_test.cairo#L155)):*
> ```Cairo
>     let deserialized_a = Serde::<u384>::deserialize(ref serialized).unwrap();
> 
>     assert!(deserialized_a == a);
> ```





_Suggestion:_
```Cairo
    let value = u384 {
        limb0: 0xb000000cd000000ef0000000,
        limb1: 0x50000006700000089000000a,
        limb2: 0x100000023000000450000000,
        limb3: 0x80000009a000000bc0000000,
    };
    let serialized = array![
        0x50000006700000089000000ab000000cd000000ef0000000,
        0x80000009a000000bc0000000100000023000000450000000,
    ];
    let mut buffer = array![];
    value.serialize(ref buffer);
    assert!(serialized == buffer);

    let mut serialized = serialized.span();
    assert!(Serde::<u384>::deserialize(ref serialized) == Option::Some(value));
```

**Review by orizi — COMMENTED** [review]
waiting for the push to see the diff :)

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6789#-:-OD5pgeC0L_g3XoafE84:b-ucqwtr)* status: all files reviewed, 5 unresolved discussions (waiting on @shramee)

**Comment by shramee** [comment]
Pushed ;)

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6789#-:-OD5r02n3MAsalgfJ_D3:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @shramee)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6789)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shramee)

**Pull request merged**
