### PR TITLE
Add range expressions (parser only).

### PR DESCRIPTION
**Pull request by liorgold2**
**Stack**:
- #6274
- #6273 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6273)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6273)* status: 4 of 11 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @liorgold2)

___
*[`crates/cairo-lang-formatter/test_data/expected_results/linebreaking.cairo` line 115 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6273#-O587dHe0ANB2ycdPlPN:-O587dHe0ANB2ycdPlPO:bthjruu) ([raw file](https://github.com/starkware-libs/cairo/blob/304f8d9aead4bf45428676182c80d9156ba264d4/crates/cairo-lang-formatter/test_data/expected_results/linebreaking.cairo#L115)):*
> ```Cairo
>     for i in 1..2 {}
>     for i in 1 + 2 + 3 + 4 + 1 + 2 + 3 + 4 + 1 + 2 + 3 + 4 + 1 + 2 + 3 + 4 + 1 + 2 + 3 + 4
>         ..1 + 2 + 3 + 4 + 1 + 2 + 3 + 4 + 1 + 2 + 3 + 4 + 1 + 2 + 3 + 4 {}
> ```

should this be legal?
in rust that would be a semantic error.



_Code quote:_
```Cairo
    for i in 1 + 2 + 3 + 4 + 1 + 2 + 3 + 4 + 1 + 2 + 3 + 4 + 1 + 2 + 3 + 4 + 1 + 2 + 3 + 4
        ..1 + 2 + 3 + 4 + 1 + 2 + 3 + 4 + 1 + 2 + 3 + 4 + 1 + 2 + 3 + 4 {}
```

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6273)* status: 4 of 11 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-formatter/test_data/expected_results/linebreaking.cairo` line 115 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6273#-O587dHe0ANB2ycdPlPN:-O58Nkwb2ME8NzOQCVst:b-8jsgpm) ([raw file](https://github.com/starkware-libs/cairo/blob/304f8d9aead4bf45428676182c80d9156ba264d4/crates/cairo-lang-formatter/test_data/expected_results/linebreaking.cairo#L115)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

should this be legal?
in rust that would be a semantic error.
</blockquote></details>

WDYM? I think it compiles in rust.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 7 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6273#-:-O58R9zkEksrDvHGDOXS:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/test_data/expected_results/linebreaking.cairo` line 115 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6273#-O587dHe0ANB2ycdPlPN:-O58R4aR1oUK_h5OmsYj:bb2wjw6) ([raw file](https://github.com/starkware-libs/cairo/blob/304f8d9aead4bf45428676182c80d9156ba264d4/crates/cairo-lang-formatter/test_data/expected_results/linebreaking.cairo#L115)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

WDYM? I think it compiles in rust.
</blockquote></details>

you are correct.

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 9 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6273#-:-O58RXfW1p6F44YUIyoZ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

___
*[`crates/cairo-lang-formatter/test_data/expected_results/linebreaking.cairo` line 115 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6273#-O587dHe0ANB2ycdPlPN:-O58QO2n-iXdyGlPGroN:b-n2qu07) ([raw file](https://github.com/starkware-libs/cairo/blob/304f8d9aead4bf45428676182c80d9156ba264d4/crates/cairo-lang-formatter/test_data/expected_results/linebreaking.cairo#L115)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you are correct.
</blockquote></details>

We can consider enforcing it to simple expression (i.e. literal, identifier, function call or parenthesis).

**Review by gilbens-starkware — APPROVED** [review]
> Reviewed 2 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6273)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
