### PR TITLE
Caching corelib db compilation for tests.

### PR DESCRIPTION
**Pull request by orizi**
Reducing starknet crate test time to 2 minutes and 20 seconds.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3195)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3195)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3195#-NVmzWuMCATc_d_MCkMr:-NVmzWuMCATc_d_MCkMs:b-ilen7k) ([raw file](https://github.com/starkware-libs/cairo/blob/d3ab216231e2878ca324a9a515ca69c428041725/crates/cairo-lang-starknet/src/contract_class.rs#L97)):*
> ```XML
> /// If no contract was specified, verify that there is only one.
> /// Otherwise, return an error.
> pub(crate) fn compile_contract_in_prepared_db(
> ```

Why only in crate?

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3195#-:-NVn-9de8Mt4VMrsEJ7B:bnfp4nl)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3195#-NVmze5A-TCStX5KYqA2:-NVmze5A-TCStX5KYqA3:b-j19t6k) (no related file):*
Does it still make sense to split the tests in CI to 3 partitions? If not, remove it in the workflow yml. Also, make sure it doesn't run eith nextest, since it seems to run each test in a different process. Do the same as the tests crate.

___

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3195)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/contract_class.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3195#-NVmzWuMCATc_d_MCkMr:-NVnOyCIApK0084A5uYS:bxxzmpm) ([raw file](https://github.com/starkware-libs/cairo/blob/d3ab216231e2878ca324a9a515ca69c428041725/crates/cairo-lang-starknet/src/contract_class.rs#L97)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Why only in crate?
</blockquote></details>

didn't want to actually expose this if not used out of tests.

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3195)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3195)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3195#-NVmze5A-TCStX5KYqA2:-NVnR2IH80_rdUCGXYM1:b-896fix) (no related file):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This
</blockquote></details>

Done.

___

**Pull request merged**
