### PR TITLE
feat: pub use

### PR DESCRIPTION
**Pull request by Jinwei1987**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3631)

### CODE REVIEW

**Comment by Jinwei1987** [comment]
@spapinistarkware @orizi this PR is a following up of my previous PR to add pub visibility to items. Please have a review.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3631#-:-NZym5c44W8s09_oO7oy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Jinwei1987)

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3631)* status: all files reviewed, 2 unresolved discussions (waiting on @Jinwei1987)

___
*[`crates/cairo-lang-defs/src/db.rs` line 271 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3631#-N_SMJC329_R3TZVAVUk:-N_SMJC491bLI4CB1kFg:blrieqn) ([raw file](https://github.com/starkware-libs/cairo/blob/6b39cc1acf5dd1bffe95583acae3cee1db7ad63f/crates/cairo-lang-defs/src/db.rs#L271)):*
> ```XML
>     constants: OrderedHashMap<ConstantId, ast::ItemConstant>,
>     submodules: OrderedHashMap<SubmoduleId, ast::ItemModule>,
>     uses: OrderedHashMap<UseId, (ast::Visibility, ast::UsePathLeaf)>,
> ```

This looks different than all the others now. I would rather keep it as it was before, and make a use_visibility() query in the semantic crate, that fetches the parent ItemUse ast.
___
*[`crates/cairo-lang-semantic/src/items/tests/use_` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3631#-N_SM6kS1-tc7EaOqGcq:-N_SM6kS1-tc7EaOqGcr:be20xiw) ([raw file](https://github.com/starkware-libs/cairo/blob/6b39cc1acf5dd1bffe95583acae3cee1db7ad63f/crates/cairo-lang-semantic/src/items/tests/use_#L19)):*
> ```
> //! > expected_diagnostics
> 
> //! > ==========================================================================
> ```

Add a negative test as well.

**Review by Jinwei1987 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3631)* status: 13 of 19 files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-semantic/src/items/tests/use_` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3631#-N_SM6kS1-tc7EaOqGcq:-N_TQaKp9_mYS53ZZRjD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6b39cc1acf5dd1bffe95583acae3cee1db7ad63f/crates/cairo-lang-semantic/src/items/tests/use_#L19)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Add a negative test as well.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-defs/src/db.rs` line 271 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3631#-N_SMJC329_R3TZVAVUk:-N_TQchP1wu8ZA-11yIy:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6b39cc1acf5dd1bffe95583acae3cee1db7ad63f/crates/cairo-lang-defs/src/db.rs#L271)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This looks different than all the others now. I would rather keep it as it was before, and make a use_visibility() query in the semantic crate, that fetches the parent ItemUse ast.
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3631)* status: 18 of 19 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 10 of 15 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3631#-:-Na6Q2sl3vR62Vs-kM-I:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Jinwei1987)

**Pull request merged**
