### PR TITLE
Contract segmentation: Add bytecode_segment_lengths to CasmContractClass.

### PR DESCRIPTION
**Pull request by liorgold2**
**Stack**:
- #4516
- #4515 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4515)

### CODE REVIEW

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4515)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/contract_segmentation.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4515#-NkyG-XI0bggykg9Kx0K:-NkyOwqQ4JlaBw-vs20q:b4b51ec) ([raw file](https://github.com/starkware-libs/cairo/blob/8acc04d0efdbcd7ecabf711b4246056320e315c7/crates/cairo-lang-starknet/src/contract_segmentation.rs#L16)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why not a vec of vecs?
</blockquote></details>

The OS supports any tree. In particular, I want to do some optimizations later. E.g., if a function has one segment then it will be a leaf instead of a node with one child. Same for small functions (as there is a non-negligible overhead in the handling of segments in the OS, compared to computing Poseidon)

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4515)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/src/contract_segmentation.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4515#-NkyFazZDpmRfGTI8wVR:-NkyPejx7C2hBCOr3s0N:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8acc04d0efdbcd7ecabf711b4246056320e315c7/crates/cairo-lang-starknet/src/contract_segmentation.rs#L22)):*
> ```XML
> 
> 
> #[derive(Error, Debug, Eq, PartialEq)]
> ```

Done.

**Review by orizi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4515)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-starknet/src/contract_segmentation.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4515#-NkyG-XI0bggykg9Kx0K:-NkyWpAEDFxaaS9KIUDv:b-567ivw) ([raw file](https://github.com/starkware-libs/cairo/blob/8acc04d0efdbcd7ecabf711b4246056320e315c7/crates/cairo-lang-starknet/src/contract_segmentation.rs#L16)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

The OS supports any tree. In particular, I want to do some optimizations later. E.g., if a function has one segment then it will be a leaf instead of a node with one child. Same for small functions (as there is a non-negligible overhead in the handling of segments in the OS, compared to computing Poseidon)
</blockquote></details>

what i assumed - but please add some doc as to why.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4515#-:-NkyYyAw8CC9Ic4yVwqs:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @liorgold2)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4515)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liorgold2)

**Pull request merged**
