### PR TITLE
LS: Proc macro - scarb code

### PR DESCRIPTION
**Pull request by Draggu**
Code calling dylib is replaced with one calling proc-macro-server. Also `aux_data` is removed as it is useless for LS.

---

**Stack**:
- #6706
- #6705
- #6704
- #6638 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by piotmag769 — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6638#-:-OBVcCoWATLslGTN2qk4:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/plugins/scarb/regular.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6638#-OBVep712AplHyY31nBO:-OBVep712AplHyY31nBP:bs5u6yc) ([raw file](https://github.com/starkware-libs/cairo/blob/6b63f907ef3ed92d1af9819dd0cf1a814798e12c/crates/cairo-lang-language-server/src/lang/proc_macros/plugins/scarb/regular.rs#L30)):*
> ```XML
> }
> 
> fn calculate_metadata(db: &dyn SyntaxGroup, item_ast: ast::ModuleItem) -> TokenStreamMetadata {
> ```

This should be lower (public first)

**Review by Draggu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6638)* status: 3 of 7 files reviewed, all discussions resolved (waiting on @Arcticae, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/plugins/scarb/regular.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6638#-OBVep712AplHyY31nBO:-OBVnceC4fYzH0OvKtbG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6b63f907ef3ed92d1af9819dd0cf1a814798e12c/crates/cairo-lang-language-server/src/lang/proc_macros/plugins/scarb/regular.rs#L30)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

This should be lower (public first)
</blockquote></details>

Done.

**Review by piotmag769 — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6638)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @mkaput, and @orizi)

**Review by mkaput — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6638)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/Cargo.toml` line 29 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6638#-OBiS2Rm4YocDIZf5jDd:-OBiS2Rm4YocDIZf5jDe:b-tkkipp) ([raw file](https://github.com/starkware-libs/cairo/blob/cb0d2d50bde23477b709f255e80d2ed91025ab35/crates/cairo-lang-language-server/Cargo.toml#L29)):*
> ```TOML
> cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.8.4" }
> cairo-lang-macro = "0.1.1"
> # Used in proc-macro code copied from scarb.
> ```

These comments are unnecessary imho: if we use these deps, then we use them, and comments break easily sorting deps

**Review by Arcticae — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6638)* status: 4 of 7 files reviewed, 5 unresolved discussions (waiting on @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/plugins/scarb/inline.rs` line 12 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6638#-OBk266MDup9-0pjn8R5:-OBk266MDup9-0pjn8R6:bi1uo9g) ([raw file](https://github.com/starkware-libs/cairo/blob/cb0d2d50bde23477b709f255e80d2ed91025ab35/crates/cairo-lang-language-server/src/lang/proc_macros/plugins/scarb/inline.rs#L12)):*
> ```XML
> use crate::lang::proc_macros::db::ProcMacroCacheGroup;
> 
> // scarb code
> ```

I would mark where it comes from, for easier exploration and maintainability (perhaps a git permalink also would be nice)
___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/plugins/scarb/mod.rs` line 11 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6638#-OBk2GaLD3BZKvCfzGsQ:-OBk2GaLD3BZKvCfzGsR:b2nregs) ([raw file](https://github.com/starkware-libs/cairo/blob/cb0d2d50bde23477b709f255e80d2ed91025ab35/crates/cairo-lang-language-server/src/lang/proc_macros/plugins/scarb/mod.rs#L11)):*
> ```XML
> pub mod regular;
> 
> // Code from scarb.
> ```

Same as above 
___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/plugins/scarb/regular.rs` line 20 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6638#-OBk2Ipm0QJKUQgFs1qo:-OBk2Ipm0QJKUQgFs1qp:b-ya81ng) ([raw file](https://github.com/starkware-libs/cairo/blob/cb0d2d50bde23477b709f255e80d2ed91025ab35/crates/cairo-lang-language-server/src/lang/proc_macros/plugins/scarb/regular.rs#L20)):*
> ```XML
> use crate::lang::proc_macros::db::ProcMacroCacheGroup;
> 
> // scarb code
> ```

Same as above
___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/plugins/mod.rs` line 12 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6638#-OBjr-P86cn9u7cK4NHm:-OBjr-P86cn9u7cK4NHn:b-8xfjmt) ([raw file](https://github.com/starkware-libs/cairo/blob/cb0d2d50bde23477b709f255e80d2ed91025ab35/crates/cairo-lang-language-server/src/lang/proc_macros/plugins/mod.rs#L12)):*
> ```XML
> // Keep it private.
> mod downcast;
> // Code from scarb.
> ```

Let's not describe it on import

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6638)* status: all files reviewed, 5 unresolved discussions (waiting on @Draggu and @mkaput)

**Review by piotmag769 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 2 files at r4, 2 of 2 files at r5, 6 of 7 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6638)* status: all files reviewed, 5 unresolved discussions (waiting on @Draggu, @integraledelebesgue, and @mkaput)

**Review by Draggu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6638)* status: 3 of 7 files reviewed, 5 unresolved discussions (waiting on @Arcticae, @integraledelebesgue, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/plugins/mod.rs` line 12 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6638#-OBjr-P86cn9u7cK4NHm:-OCDxpjj6-1fAQKbtN4A:b-csw0zf) ([raw file](https://github.com/starkware-libs/cairo/blob/cb0d2d50bde23477b709f255e80d2ed91025ab35/crates/cairo-lang-language-server/src/lang/proc_macros/plugins/mod.rs#L12)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

Let's not describe it on import
</blockquote></details>

I believe this was comment to previous comment.
___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/plugins/scarb/inline.rs` line 12 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6638#-OBk266MDup9-0pjn8R5:-OCDxmwV42GhnFXcyP5w:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cb0d2d50bde23477b709f255e80d2ed91025ab35/crates/cairo-lang-language-server/src/lang/proc_macros/plugins/scarb/inline.rs#L12)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

I would mark where it comes from, for easier exploration and maintainability (perhaps a git permalink also would be nice)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/plugins/scarb/mod.rs` line 11 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6638#-OBk2GaLD3BZKvCfzGsQ:-OCDxnqi8XNGvlMv00FC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cb0d2d50bde23477b709f255e80d2ed91025ab35/crates/cairo-lang-language-server/src/lang/proc_macros/plugins/scarb/mod.rs#L11)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lang/proc_macros/plugins/scarb/regular.rs` line 20 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6638#-OBk2Ipm0QJKUQgFs1qo:-OCDxoEjCd_mdCkM3Ekp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cb0d2d50bde23477b709f255e80d2ed91025ab35/crates/cairo-lang-language-server/src/lang/proc_macros/plugins/scarb/regular.rs#L20)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.

**Review by mkaput — APPROVED** [review]
:lgtm:

> Reviewed 2 of 7 files at r6, 1 of 1 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6638#-:-OCHdm_23WbAd940fX6F:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae and @integraledelebesgue)

**Review by Arcticae — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6638#-:-OCIjU6jBdNjLOi4x0uL:bg7igkv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @integraledelebesgue)

**Review by mkaput — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6638)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @integraledelebesgue)

**Review by mkaput — APPROVED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6638)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @integraledelebesgue)

**Review by mkaput — APPROVED** [review]
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6638)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @integraledelebesgue)

**Review by piotmag769 — COMMENTED** [review]
> Reviewed 3 of 4 files at r8, 1 of 2 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6638)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
