### PR TITLE
Removed old lookup methods

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5442)

### CODE REVIEW

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5442)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5442#-NvlDMHm7th6kHdhY_Qp:-NvlDMHm7th6kHdhY_Qq:b-sniaof) (no related file):*
Remove also `{semantic::items::ConcreteFunctionWithBodyId,lowering::ids::ConcreteFunctionWithBodyId,LocationId,ImplVarId}::get`.

___

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5442#-:-NvletYn2doIa6jeFl3W:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5442)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5442)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5442#-NvlDMHm7th6kHdhY_Qp:-Nvl_vn79ThYxvksHUKP:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Remove also `{semantic::items::ConcreteFunctionWithBodyId,lowering::ids::ConcreteFunctionWithBodyId,LocationId,ImplVarId}::get`.
</blockquote></details>

Done.

___

**Review by orizi — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5442)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)

**Pull request merged**
