### PR TITLE
Made more fine grained borrow checking for branch merges.

### PR DESCRIPTION
**Pull request by orizi**
Fixing #4092.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4124)

### CODE REVIEW

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 9 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4124)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/block_builder.rs` line 251 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4124#-NfFRBwU8dCtKofqUhhB:-NfFRBwU8dCtKofqUhhC:b-ro4o4m) ([raw file](https://github.com/starkware-libs/cairo/blob/4946b5b0b3ae95ae3f2c1ac60d03a55fdff64101/crates/cairo-lang-lowering/src/lower/block_builder.rs#L251)):*
> ```XML
>                 while let Some(v) = queue.pop() {
>                     // If we reached the original member path, it needs to be grouped - so no need
>                     // to continue recursively.
> ```

I think `grouped` is confusing.

Use `restructured` or `gathered`.



_Suggestion:_
```XML
                    // If we reached the original member path, it needs to be restructured - so no need
                    // to continue recursively.
```
___
*[`crates/cairo-lang-lowering/src/lower/block_builder.rs` line 253 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4124#-NfFSNMfEiSiGYqBmsG1:-NfFSNMfEiSiGYqBmsG2:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/4946b5b0b3ae95ae3f2c1ac60d03a55fdff64101/crates/cairo-lang-lowering/src/lower/block_builder.rs#L253)):*
> ```XML
>                     // to continue recursively.
>                     if v != *member_path {
>                         // If it is scattered - adding its members instead of itself.
> ```





_Suggestion:_
```XML
   // If it is scattered - add its members instead of itself, to avoid a possibly unnecessary restructuring. 
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/block_builder.rs` line 247 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4124#-NfFTOmX57jAad3sF9de:-NfFTOmX57jAad3sF9df:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/4946b5b0b3ae95ae3f2c1ac60d03a55fdff64101/crates/cairo-lang-lowering/src/lower/block_builder.rs#L247)):*
> ```XML
>                 // This avoids edge cases regarding de/constructing structs.
>                 // But to make sure we don't needlessly 'use' vars, we add all scattered members of
>                 // the topmost member path to the remapping instead of the topmost itself.
> ```





_Suggestion:_
```XML
                // Consider the topmost member path that contains the changed member, as it might be needed
                // in the merge site.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/refs.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4124#-NfFUei_-xIGbomrB2Bj:-NfFUeia9Xl1Lui9ow-o:b-mdjch8) ([raw file](https://github.com/starkware-libs/cairo/blob/4946b5b0b3ae95ae3f2c1ac60d03a55fdff64101/crates/cairo-lang-lowering/src/lower/refs.rs#L19)):*
> ```XML
> impl SemanticLoweringMapping {
>     /// Returns the topmost member path containing the given member path, or None no such member
>     /// path exists in the mapping.
> ```

you are only going over member paths that were "used", right?



_Suggestion:_
```XML
    /// Returns the topmost used member path containing the given member path, or None no such member
    /// path exists in the mapping.
```

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4124)* status: 9 of 11 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/lower/block_builder.rs` line 253 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4124#-NfFSNMfEiSiGYqBmsG1:-NfFWEqm-8ZnEuB4Q-1c:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4946b5b0b3ae95ae3f2c1ac60d03a55fdff64101/crates/cairo-lang-lowering/src/lower/block_builder.rs#L253)):*
> ```XML
>                     // to continue recursively.
>                     if v != *member_path {
>                         // If it is scattered - adding its members instead of itself.
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/lower/refs.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4124#-NfFUei_-xIGbomrB2Bj:-NfFWIgy5gYPXxqr5DrK:bb7sa0c) ([raw file](https://github.com/starkware-libs/cairo/blob/4946b5b0b3ae95ae3f2c1ac60d03a55fdff64101/crates/cairo-lang-lowering/src/lower/refs.rs#L19)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

you are only going over member paths that were "used", right?
</blockquote></details>

yes.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4124)* status: 9 of 11 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/lower/block_builder.rs` line 247 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4124#-NfFTOmX57jAad3sF9de:-NfFWa7y7az2o4A392sU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4946b5b0b3ae95ae3f2c1ac60d03a55fdff64101/crates/cairo-lang-lowering/src/lower/block_builder.rs#L247)):*
> ```XML
>                 // This avoids edge cases regarding de/constructing structs.
>                 // But to make sure we don't needlessly 'use' vars, we add all scattered members of
>                 // the topmost member path to the remapping instead of the topmost itself.
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/lower/block_builder.rs` line 251 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4124#-NfFRBwU8dCtKofqUhhB:-NfFWa_zAvMZv59wQfNt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4946b5b0b3ae95ae3f2c1ac60d03a55fdff64101/crates/cairo-lang-lowering/src/lower/block_builder.rs#L251)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I think `grouped` is confusing.

Use `restructured` or `gathered`.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4124#-:-NfFWq0x6X3cLB1jfcTx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4124)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/refs.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4124#-NfFYa9I7qO_DCgj-OKm:-NfFYa9J6X1X730J_9_Y:b55cz8n) ([raw file](https://github.com/starkware-libs/cairo/blob/0c9d4720058c7f343393605e25e14c85ecdebc7e/crates/cairo-lang-lowering/src/lower/refs.rs#L20)):*
> ```XML
>     /// Returns the topmost used member path containing the given member path, or None no such
>     /// member path exists in the mapping.
>     pub fn topmost_containing_member_path(
> ```

let's rename the function as well.



_Suggestion:_
```XML
topmost_used_containing_member_path
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/refs.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4124#-NfFYa9I7qO_DCgj-OKm:-NfFfFoj0Y2Ug5G6X7XY:bwu7x28) ([raw file](https://github.com/starkware-libs/cairo/blob/0c9d4720058c7f343393605e25e14c85ecdebc7e/crates/cairo-lang-lowering/src/lower/refs.rs#L20)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is within the mapping - so just changed the doc to say "mapped" instead of used instead.
</blockquote></details>

why not rename the function?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4124)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/lower/refs.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4124#-NfFYa9I7qO_DCgj-OKm:-NfFiPQe7jpTZe1c4fDG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0c9d4720058c7f343393605e25e14c85ecdebc7e/crates/cairo-lang-lowering/src/lower/refs.rs#L20)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why not rename the function?
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4124#-:-NfFicKZ5huaa_eQZnWy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
