### PR TITLE
added lowering of FnOnce Call

### PR DESCRIPTION
**Pull request by TomerStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6278)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/test.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6278#-O5CHWMk9IiDQqW_ojuE:-O5CHWMk9IiDQqW_ojuF:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/83e339222a19a35001c0efbdb53bc87d46bf6245/crates/cairo-lang-lowering/src/test.rs#L34)):*
> ```XML
>         constant :"constant",
>         coupon :"coupon",
>         c11losure :"closure",
> ```





_Suggestion:_
```XML
closure :"closure",
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6278)* status: 5 of 17 files reviewed, 3 unresolved discussions (waiting on @orizi and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/ids.rs` line 262 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6278#-O5CHNkM0ZMWyexCg9OM:-O5CHNkM0ZMWyexCg9ON:b-xvfgr4) ([raw file](https://github.com/starkware-libs/cairo/blob/83e339222a19a35001c0efbdb53bc87d46bf6245/crates/cairo-lang-lowering/src/ids.rs#L262)):*
> ```XML
>                         let concrete_trait = imp.concrete_trait(semantic_db);
>                         if concrete_trait.trait_id(semantic_db)
>                             == semantic::corelib::fn_once_trait(semantic_db)
> ```

can you support destructors as well?



_Code quote:_
```XML
                        if concrete_trait.trait_id(semantic_db)
                            == semantic::corelib::fn_once_trait(semantic_db)
```
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1818 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6278#-O5CI1sD00vjrSqXBxAJ:-O5CI1sD00vjrSqXBxAK:b-q5z4u) ([raw file](https://github.com/starkware-libs/cairo/blob/83e339222a19a35001c0efbdb53bc87d46bf6245/crates/cairo-lang-lowering/src/lower/mod.rs#L1818)):*
> ```XML
> 
>     let root_ok = {
>         let capture_requests = generators::StructDestructure {
> ```

those are var, not request, right?



_Code quote:_
```XML
capture_requests
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6278)* status: 5 of 17 files reviewed, 4 unresolved discussions (waiting on @orizi and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/refs.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6278#-O5CIaYvB0lbN24Q9VSq:-O5CIaYvB0lbN24Q9VSr:b-s44hf7) ([raw file](https://github.com/starkware-libs/cairo/blob/83e339222a19a35001c0efbdb53bc87d46bf6245/crates/cairo-lang-lowering/src/lower/refs.rs#L17)):*
> ```XML
> #[derive(Clone, Debug)]
> pub struct ClosureInfo {
>     // TODO(TomerStarkware): unite copiable members and snapshots into a single map.
> ```

this was done, right?



_Code quote:_
```XML
// TODO(TomerStarkware): unite copiable members and snapshots into a single map.
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6278)* status: 2 of 17 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/ids.rs` line 262 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6278#-O5CHNkM0ZMWyexCg9OM:-O5Ihqoe0MqZIIIkG6Ws:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/83e339222a19a35001c0efbdb53bc87d46bf6245/crates/cairo-lang-lowering/src/ids.rs#L262)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

can you support destructors as well?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/test.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6278#-O5CHWMk9IiDQqW_ojuE:-O5FOUNqDjIXDxrYvMqo:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/83e339222a19a35001c0efbdb53bc87d46bf6245/crates/cairo-lang-lowering/src/test.rs#L34)):*
> ```XML
>         constant :"constant",
>         coupon :"coupon",
>         c11losure :"closure",
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1818 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6278#-O5CI1sD00vjrSqXBxAJ:-O5Ii1wQC14Pq2ziP9z_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/83e339222a19a35001c0efbdb53bc87d46bf6245/crates/cairo-lang-lowering/src/lower/mod.rs#L1818)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

those are var, not request, right?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/refs.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6278#-O5CIaYvB0lbN24Q9VSq:-O5IiE4-3e56uUo3OBUD:b-lsijsx) ([raw file](https://github.com/starkware-libs/cairo/blob/83e339222a19a35001c0efbdb53bc87d46bf6245/crates/cairo-lang-lowering/src/lower/refs.rs#L17)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

this was done, right?
</blockquote></details>

o, I am not sure how to do it since in closure\_call\_function I add the snapshots to the snap_semantics and copiable members go to regular semantics.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6278#-O5IqORTC20ls3MmhiDF:-O5IqORU-hMEbogun7aL:b-hay66i) ([raw file](https://github.com/starkware-libs/cairo/blob/f2198a9ba07ed78f662030f02bb8f16c3e2694f3/crates/cairo-lang-lowering/src/lower/mod.rs#L110)):*
> ```XML
>         block_expr_id,
>     )
>     .unwrap();
> ```

revert?



_Code quote:_
```XML
  .unwrap();
```

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6278)* status: 2 of 17 files reviewed, 8 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`corelib/src/test/closure_test.cairo` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6278#-O5MPzE13mA88iqn3oS0:-O5MPzE13mA88iqn3oS1:b-s95h37) ([raw file](https://github.com/starkware-libs/cairo/blob/f2198a9ba07ed78f662030f02bb8f16c3e2694f3/corelib/src/test/closure_test.cairo#L1)):*
> ```Cairo
> #[test]
> ```

add tests with function expecting FnOnce.
___
*[`corelib/src/test/closure_test.cairo` line 39 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6278#-O5MOVbNDWbt2YpBUk0t:-O5MOVbNDWbt2YpBUk0u:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f2198a9ba07ed78f662030f02bb8f16c3e2694f3/corelib/src/test/closure_test.cairo#L39)):*
> ```Cairo
>     };
>     panic!()
> }
> ```





_Suggestion:_
```Cairo
#[test]
fn closure() {
    let x = 8;
    let c = |a| {
        return x * (a + 3);
        7_felt252
    };
    assert_eq!(c(2), 40);
}

#[derive(Destruct)]
struct DestuctOnly {}

#[test]
fn closure_destruct() {
    let a = DestuctOnly {};
    || {
        let _b = a;
    };
}

#[derive(PanicDestruct)]
struct PanicDestructOnly {}

#[test]
#[should_panic(expected: "outer")]
fn closure_panic_destruct() {
    let a = PanicDestructOnly {};
    || -> () {
        let _b = a;
        panic!("inner")
    };
    panic!("outer")
}
```
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1772 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6278#-O5MP_V18bAni7OYJdNk:-O5MP_V18bAni7OYJdNl:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/f2198a9ba07ed78f662030f02bb8f16c3e2694f3/crates/cairo-lang-lowering/src/lower/mod.rs#L1772)):*
> ```XML
> }
> 
> fn closure_call_function(
> ```

doc

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1804 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6278#-O5MfNhx-y9eaU6ch6Lf:-O5MfNhx-y9eaU6ch6Lg:b-uedj4x) ([raw file](https://github.com/starkware-libs/cairo/blob/f2198a9ba07ed78f662030f02bb8f16c3e2694f3/crates/cairo-lang-lowering/src/lower/mod.rs#L1804)):*
> ```XML
>         encapsulated_ctx.db,
>         semantic_db.concrete_trait_function_signature(concrete_trait_function)?,
>     );
> ```

The signature here has TraitTypes; How are they going to be replaced?



_Code quote:_
```XML
    let signature = Signature::from_semantic(
        encapsulated_ctx.db,
        semantic_db.concrete_trait_function_signature(concrete_trait_function)?,
    );
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6278)* status: 2 of 20 files reviewed, 9 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`corelib/src/test/closure_test.cairo` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6278#-O5MPzE13mA88iqn3oS0:-O5m4JrN8sCUvSFQZ1Cw:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f2198a9ba07ed78f662030f02bb8f16c3e2694f3/corelib/src/test/closure_test.cairo#L1)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add tests with function expecting FnOnce.
</blockquote></details>

Done.
___
*[`corelib/src/test/closure_test.cairo` line 39 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6278#-O5MOVbNDWbt2YpBUk0t:-O5m5SqW3-PHU24bZNRW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f2198a9ba07ed78f662030f02bb8f16c3e2694f3/corelib/src/test/closure_test.cairo#L39)):*
> ```Cairo
>     };
>     panic!()
> }
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6278#-O5IqORTC20ls3MmhiDF:-O5m5fEuDw7LApJfSimo:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f2198a9ba07ed78f662030f02bb8f16c3e2694f3/crates/cairo-lang-lowering/src/lower/mod.rs#L110)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

revert?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1772 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6278#-O5MP_V18bAni7OYJdNk:-O5m6KI88NnjXtPNe64E:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f2198a9ba07ed78f662030f02bb8f16c3e2694f3/crates/cairo-lang-lowering/src/lower/mod.rs#L1772)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1804 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6278#-O5MfNhx-y9eaU6ch6Lf:-O5m6qzh0-8iz5Q8gClE:b-896fiz) ([raw file](https://github.com/starkware-libs/cairo/blob/f2198a9ba07ed78f662030f02bb8f16c3e2694f3/crates/cairo-lang-lowering/src/lower/mod.rs#L1804)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

The signature here has TraitTypes; How are they going to be replaced?
</blockquote></details>

Done,

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6278)* status: 4 of 20 files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`corelib/src/test/closure_test.cairo` line 63 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6278#-O5mN5WdB7eQWvHqV1rx:-O5mN5WdB7eQWvHqV1ry:b78km5l) ([raw file](https://github.com/starkware-libs/cairo/blob/12cef26460a6b7068ed8fd169323862fb116cd01/corelib/src/test/closure_test.cairo#L63)):*
> ```Cairo
>     let f = |x| Option::Some(x);
>     assert_eq!(option_map(Option::Some(2), f), Option::Some(Option::Some(2)));
> }
> ```

why not?



_Suggestion:_
```Cairo
#[test]
fn option_map_test() {
    assert_eq!(option_map(Option::Some(2), |x| x + 3), Option::Some(5));
    assert_eq!(option_map(Option::None, |x| x + 3), Option::None);
    assert_eq!(option_map(Option::Some(2), |x| Option::Some(x)), Option::Some(Option::Some(2)));
}
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6278)* status: 4 of 20 files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`corelib/src/test/closure_test.cairo` line 63 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6278#-O5mN5WdB7eQWvHqV1rx:-O5mTK-14FFGXjj6w75A:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/12cef26460a6b7068ed8fd169323862fb116cd01/corelib/src/test/closure_test.cairo#L63)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why not?
</blockquote></details>

Done.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6278)* status: 5 of 20 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1888 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6278#-O5qem-K41jABQ2YYDXR:-O5qem-K41jABQ2YYDXS:b-afxc9t) ([raw file](https://github.com/starkware-libs/cairo/blob/11e5379be57d20a502f64db0647d4d683d0f65b2/crates/cairo-lang-lowering/src/lower/mod.rs#L1888)):*
> ```XML
>     encapsulated_ctx.lowerings.insert(
>         GeneratedFunctionKey::TraitFunc(function, closure_ty.wrapper_location),
>         lowered.clone(),
> ```

why clone?



_Code quote:_
```XML
.clone()
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1917 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6278#-O5qevjE95VSX4F1q4ol:-O5qevjE95VSX4F1q4om:bcl3pa7) ([raw file](https://github.com/starkware-libs/cairo/blob/11e5379be57d20a502f64db0647d4d683d0f65b2/crates/cairo-lang-lowering/src/lower/mod.rs#L1917)):*
> ```XML
>         builder.semantics.closures.get(&capture_var_usage.var_id).unwrap(),
>     )
>     .unwrap();
> ```

why unwrap?



_Code quote:_
```XML
 .unwrap();
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6278)* status: 4 of 20 files reviewed, 8 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1888 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6278#-O5qem-K41jABQ2YYDXR:-O5qfJk51EAiALlnwnNH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/11e5379be57d20a502f64db0647d4d683d0f65b2/crates/cairo-lang-lowering/src/lower/mod.rs#L1888)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why clone?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1917 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6278#-O5qevjE95VSX4F1q4ol:-O5qfe3R-IgsH2tAJwbf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/11e5379be57d20a502f64db0647d4d683d0f65b2/crates/cairo-lang-lowering/src/lower/mod.rs#L1917)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why unwrap?
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
Can you split this into smaller PRs?

> Reviewed 6 of 17 files at r1, 5 of 8 files at r2, 2 of 7 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6278#-:-O5qjD6M7DgUXXIjFOqZ:b7eg0tw)* status: 15 of 20 files reviewed, 4 unresolved discussions (waiting on @orizi)

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r2, 5 of 5 files at r6, 4 of 7 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6278)* status: all files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`corelib/src/test.cairo` line 41 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6278#-O5w6KKZDiaOISSQQAXd:-O5w6KKZDiaOISSQQAXe:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ccef69ab182ec2e47e268fd4f3e53040248a16f8/corelib/src/test.cairo#L41)):*
> ```Cairo
>     mod trait_test;
>     mod while_test;
> }
> ```





_Suggestion:_
```Cairo
mod circuit_test;
mod clone_test;
mod cmp_test;
mod coupon_test;
mod dict_test;
mod ec_test;
mod felt_test;
mod fmt_test;
mod hash_test;
mod integer_test;
mod keccak_test;
mod math_test;
mod nullable_test;
mod num_test;
mod option_test;
mod plugins_test;
mod print_test;
mod result_test;
mod secp256k1_test;
mod secp256r1_test;
mod sha256_test;
mod test_utils;
mod testing_test;
mod to_byte_array_test;

/// Tests for language features, without mixing implementations within the corelib.
mod language_features {
    mod block_level_items_test;
    mod closure_test;
    mod const_folding_test;
    mod const_test;
    mod for_test;
    mod panics_test;
    mod trait_test;
    mod while_test;
}
```

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6278)* status: 18 of 20 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`corelib/src/test.cairo` line 41 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6278#-O5w6KKZDiaOISSQQAXd:-O5wX0Nb0Pcgw-eLdlWn:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ccef69ab182ec2e47e268fd4f3e53040248a16f8/corelib/src/test.cairo#L41)):*
> ```Cairo
>     mod trait_test;
>     mod while_test;
> }
> ```

Done.

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 17 files at r1, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6278)* status: all files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6278#-:-O5wXku87eUh_5d6BmIY:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6278)* status: all files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1809 at r10](https://reviewable.io/reviews/starkware-libs/cairo/6278#-O60C8Cn-CJsyt_9xfRw:-O60C8Cn-CJsyt_9xfRx:b-gyy92h) ([raw file](https://github.com/starkware-libs/cairo/blob/697a91f072e58e49765d1de207c38c79eba6eb2a/crates/cairo-lang-lowering/src/lower/mod.rs#L1809)):*
> ```XML
>             impl_items: GeneratedImplItems(iter::once((ret_ty, closure_ty.ret_ty)).collect()),
>         }
>         .intern(encapsulated_ctx.db),
> ```

Can you use semantic_db here?



_Code quote:_
```XML
encapsulated_ctx.db
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1855 at r10](https://reviewable.io/reviews/starkware-libs/cairo/6278#-O60CXjc1Uw8yldegFML:-O60CXjc1Uw8yldegFMM:b-8jz13b) ([raw file](https://github.com/starkware-libs/cairo/blob/697a91f072e58e49765d1de207c38c79eba6eb2a/crates/cairo-lang-lowering/src/lower/mod.rs#L1855)):*
> ```XML
>                 .insert(param.clone(), captured_vars[i + closure_info.members.len()]);
>         }
>         let param_requests = generators::StructDestructure {
> ```

why rquests?



_Suggestion:_
```XML
param_vars
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
actually there are a few small fixes required 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6278#-:-O60Fp4X2BBREDdIR1Jb:bo6kfvg)* status: all files reviewed, 3 unresolved discussions (waiting on @TomerStarkware)

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6278)* status: 19 of 20 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1809 at r10](https://reviewable.io/reviews/starkware-libs/cairo/6278#-O60C8Cn-CJsyt_9xfRw:-O60Yv9GDWbJsAYlyR4l:b-el1lkl) ([raw file](https://github.com/starkware-libs/cairo/blob/697a91f072e58e49765d1de207c38c79eba6eb2a/crates/cairo-lang-lowering/src/lower/mod.rs#L1809)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Can you use semantic_db here?
</blockquote></details>

Done.git
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1855 at r10](https://reviewable.io/reviews/starkware-libs/cairo/6278#-O60CXjc1Uw8yldegFML:-O60Yutk4F1PJjwKTyLZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/697a91f072e58e49765d1de207c38c79eba6eb2a/crates/cairo-lang-lowering/src/lower/mod.rs#L1855)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why rquests?
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1855 at r10](https://reviewable.io/reviews/starkware-libs/cairo/6278#-O60CXjc1Uw8yldegFML:-O60_Ohm3-NbGSG4wsgq:b-vr4p06) ([raw file](https://github.com/starkware-libs/cairo/blob/697a91f072e58e49765d1de207c38c79eba6eb2a/crates/cairo-lang-lowering/src/lower/mod.rs#L1855)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see it.

**Review by TomerStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6278)* status: 19 of 20 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1855 at r10](https://reviewable.io/reviews/starkware-libs/cairo/6278#-O60CXjc1Uw8yldegFML:-O60_xl31Hfx4L3vo1ub:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/697a91f072e58e49765d1de207c38c79eba6eb2a/crates/cairo-lang-lowering/src/lower/mod.rs#L1855)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't see it.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6278#-:-O60i8NGE46V5eW_6nyc:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)

**Pull request merged**
