### PR TITLE
Add number of add and mul gates to CircuitDescriptor.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5546)

### CODE REVIEW

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5546#-:-NxfzsLOAqleSEvTkdr2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5546)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`tests/e2e_test_data/libfuncs/circuit` line 175 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5546#-NxgIOVc-l1JkEeiNMub:-NxgIOVc-l1JkEeiNMuc:bcdhlf5) ([raw file](https://github.com/starkware-libs/cairo/blob/0260db89030a63fe9ef47249c742402f0c42a8bf/tests/e2e_test_data/libfuncs/circuit#L175)):*
> ```
> 
> //! > function_costs
> test::foo: OrderedHashMap({Const: 600})
> ```

@orizi  How come I didn't get an error before this fix?



_Code quote:_
```
test::foo: OrderedHashMap({Const: 600})
```

**Review by orizi — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5546)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`tests/e2e_test_data/libfuncs/circuit` line 175 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5546#-NxgIOVc-l1JkEeiNMub:-NxgJ6MpBREeQt0IhwuK:b-7zi8tj) ([raw file](https://github.com/starkware-libs/cairo/blob/0260db89030a63fe9ef47249c742402f0c42a8bf/tests/e2e_test_data/libfuncs/circuit#L175)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

@orizi  How come I didn't get an error before this fix?
</blockquote></details>

WDYM?

**Review by orizi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5546)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`tests/e2e_test_data/libfuncs/circuit` line 175 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5546#-NxgIOVc-l1JkEeiNMub:-NxgJAICEG1WETiNNULf:b-knb8l7) ([raw file](https://github.com/starkware-libs/cairo/blob/0260db89030a63fe9ef47249c742402f0c42a8bf/tests/e2e_test_data/libfuncs/circuit#L175)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

WDYM?
</blockquote></details>

about the number of actual steps?
because it isn't auto calculated from the casm-builder.

**Pull request merged**
