### PR TITLE
Made implicits get the SCC from post baseline optimization stage.

### PR DESCRIPTION
**Pull request by orizi**

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/cairo-lang-lowering/src/test_data/implicits` line 152 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6819#-ODGUFKeCAtpHB9pQaBQ:-ODL-U2F2VzaoqOmuxlz:b5dzxvy) ([raw file](https://github.com/starkware-libs/cairo/blob/5b16fefbf224fea678afd45ca71f6c201eb42394/crates/cairo-lang-lowering/src/test_data/implicits#L152)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Before this fix.
</blockquote></details>

I'm confused is this a functionolity change PR or a rename?

**Review by gilbens-starkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6819#-:-ODL7AjW7eUryEmkA5mo:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/test_data/implicits` line 152 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6819#-ODGUFKeCAtpHB9pQaBQ:-ODL6q8o5TfvjikeEC8L:b-h8n04) ([raw file](https://github.com/starkware-libs/cairo/blob/5b16fefbf224fea678afd45ca71f6c201eb42394/crates/cairo-lang-lowering/src/test_data/implicits#L152)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I'm confused is this a functionolity change PR or a rename?
</blockquote></details>

Line 553 in `db.rs` is a functionality change.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6819#-:-ODLDuSV7IPnRr0Ap7xf:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6819)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/test_data/implicits` line 152 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6819#-ODGUFKeCAtpHB9pQaBQ:-ODLO0Fq9958EdqWi0_a:b-3tecw1) ([raw file](https://github.com/starkware-libs/cairo/blob/5b16fefbf224fea678afd45ca71f6c201eb42394/crates/cairo-lang-lowering/src/test_data/implicits#L152)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Line 553 in `db.rs` is a functionality change.
</blockquote></details>

It is both - I renamed it due to the changed functionality.

**Pull request merged**
