### PR TITLE
Refactored cycle handling to redirect helpers to fetch main function.

### PR DESCRIPTION
**Pull request by orizi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5090)

### CODE REVIEW

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5090)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 269 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5090#-Nr-f_2X6Jh9-wsRgXIR:-Nr-f_2X6Jh9-wsRgXIS:b-xhlugv) ([raw file](https://github.com/starkware-libs/cairo/blob/b3f10ce4b22216e28cb3d78b7b858fea4454b774/crates/cairo-lang-semantic/src/items/imp.rs#L269)):*
> ```XML
>     impl_def_id: &ImplDefId,
> ) -> Maybe<Arc<ResolverData>> {
>     impl_def_resolver_data(db, *impl_def_id)
> ```

These trivial cycle handlers mean cycles are not really handled.
Actually, I think it's worse - previously a cycle would've crash, now it'll just enter an infinite recursion.
Do I miss something?

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5090)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 269 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5090#-Nr-f_2X6Jh9-wsRgXIR:-Nr-iDi26RMCLxI4HSPf:b-2k2yl4) ([raw file](https://github.com/starkware-libs/cairo/blob/b3f10ce4b22216e28cb3d78b7b858fea4454b774/crates/cairo-lang-semantic/src/items/imp.rs#L269)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

These trivial cycle handlers mean cycles are not really handled.
Actually, I think it's worse - previously a cycle would've crash, now it'll just enter an infinite recursion.
Do I miss something?
</blockquote></details>

This exactly starts a cycle at the point where cycles ARE properly addressed.
It call the internal query implementation (NOT as a query) - and the cycle is handled by the priv_ function.

**Review by yuvalsw — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5090)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5090#-Nr-vi9pAuEVSvLcQoGn:-Nr-vi9pAuEVSvLcQoGo:bq64j6i) (no related file):*
BTW, doesn't priv_module_type_alias_generic_params_data need cycle handling?

___
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 269 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5090#-Nr-f_2X6Jh9-wsRgXIR:-Nr-pnd8-2NHGS-p9Gqw:b-1f304l) ([raw file](https://github.com/starkware-libs/cairo/blob/b3f10ce4b22216e28cb3d78b7b858fea4454b774/crates/cairo-lang-semantic/src/items/imp.rs#L269)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

This exactly starts a cycle at the point where cycles ARE properly addressed.
It call the internal query implementation (NOT as a query) - and the cycle is handled by the priv_ function.
</blockquote></details>

Oh, ok, nice.
1. Put this explanation as a comment in each of these trivial cycle handlers as it's not trivial to understand.
2. Is this a common practice with Salsa? It's sounds ok to me, but I am concerned there might be unforeseen consequences.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 298 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5090#-Nr-sePj4db37E-N2tOL:-Nr-sePj4db37E-N2tOM:bypzyul) ([raw file](https://github.com/starkware-libs/cairo/blob/b3f10ce4b22216e28cb3d78b7b858fea4454b774/crates/cairo-lang-semantic/src/items/imp.rs#L298)):*
> ```XML
> 
> /// Trivial cycle handler for [crate::db::SemanticGroup::impl_def_attributes].
> pub fn impl_def_attributes_cycle(
> ```

Why do you add cycle handling for attributes, but not e.g. for `impl_semantic_declaration_diagnostics`?
I'd expect either to handle only what we know might have cycles, or all callers of priv_ queries with proper cycle handling (e.g. `priv_impl_declaration_data`).
My question is what was the logic of choosing which queries should have trivial cycle handling, and my point is I want to make sure we don't forget anything.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5090)* status: all files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5090#-Nr-vi9pAuEVSvLcQoGn:-Nr0xvQN5_zSUYHuOJO1:b-fmhyx5) (no related file):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

BTW, doesn't priv_module_type_alias_generic_params_data need cycle handling?
</blockquote></details>

generic params are different conceptually (as these need to be ready prior to the actual item) - but there might be additional stuff to do there.

___
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 269 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5090#-Nr-f_2X6Jh9-wsRgXIR:-Nr0zhNm7_z5DAVsFc48:bnorbj7) ([raw file](https://github.com/starkware-libs/cairo/blob/b3f10ce4b22216e28cb3d78b7b858fea4454b774/crates/cairo-lang-semantic/src/items/imp.rs#L269)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Oh, ok, nice.
1. Put this explanation as a comment in each of these trivial cycle handlers as it's not trivial to understand.
2. Is this a common practice with Salsa? It's sounds ok to me, but I am concerned there might be unforeseen consequences.
</blockquote></details>

1. Done
2. in salsa2022 - it is very similar to the actual handling - in any case - here this seems to work perfectly (as it is tested), this still seems much better to me than the previous thing we had to do.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 298 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5090#-Nr-sePj4db37E-N2tOL:-Nr1-DRm6g1kOfC_7jgr:b-fknit5) ([raw file](https://github.com/starkware-libs/cairo/blob/b3f10ce4b22216e28cb3d78b7b858fea4454b774/crates/cairo-lang-semantic/src/items/imp.rs#L298)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Why do you add cycle handling for attributes, but not e.g. for `impl_semantic_declaration_diagnostics`?
I'd expect either to handle only what we know might have cycles, or all callers of priv_ queries with proper cycle handling (e.g. `priv_impl_declaration_data`).
My question is what was the logic of choosing which queries should have trivial cycle handling, and my point is I want to make sure we don't forget anything.
</blockquote></details>

adding the handling only for the parts that may cause a recursive call - attributes and diagnostics do not require other calls to attributes and diagnostics (removed attributes as well), unlike the resolve parts.

**Review by yuvalsw — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5090#-:-NrUz7on6uj2NbM95Vx3:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 270 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5090#-NrUhY3jCgsRuedci5eM:-NrUhY3jCgsRuedci5eN:brpnly1) ([raw file](https://github.com/starkware-libs/cairo/blob/d10bed1aadd2e0a9f6b61f8371c051a9b26607f3/crates/cairo-lang-semantic/src/items/imp.rs#L270)):*
> ```XML
>     impl_def_id: &ImplDefId,
> ) -> Maybe<Arc<ResolverData>> {
>     // Forwarding cycle handling to `priv_impl_declaration_data` cycle handler.
> ```

Please add in those "not as a query". This is an important distinction to make, and it's not popping out if one doesn't pay careful attention.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5090)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 270 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5090#-NrUhY3jCgsRuedci5eM:-NrVAHX40PDPazlJb-G9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d10bed1aadd2e0a9f6b61f8371c051a9b26607f3/crates/cairo-lang-semantic/src/items/imp.rs#L270)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Please add in those "not as a query". This is an important distinction to make, and it's not popping out if one doesn't pay careful attention.
</blockquote></details>

Done.

**Review by yuvalsw — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5090)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 270 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5090#-NrUhY3jCgsRuedci5eM:-NrVUlkx6dL2iv9jB2Ww:bnz5t51) ([raw file](https://github.com/starkware-libs/cairo/blob/d10bed1aadd2e0a9f6b61f8371c051a9b26607f3/crates/cairo-lang-semantic/src/items/imp.rs#L270)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Only forgot this instance. unblocking.

**Review by orizi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5090)* status: 8 of 9 files reviewed, all discussions resolved (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 270 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5090#-NrUhY3jCgsRuedci5eM:-NrVZ0ce9prVHN0tYc1B:b-j1v4by) ([raw file](https://github.com/starkware-libs/cairo/blob/d10bed1aadd2e0a9f6b61f8371c051a9b26607f3/crates/cairo-lang-semantic/src/items/imp.rs#L270)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Only forgot this instance. unblocking.
</blockquote></details>

somehow vs-code just didn't save - done.

**Review by orizi — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5090)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

**Pull request merged**
