### PR TITLE
Moved event-related code generation

### PR DESCRIPTION
**Pull request by yuvalsw**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3930)

### CODE REVIEW

**Comment by yuvalsw** [comment]
change target branch

**Review by orizi — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3930)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 413 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3930#-Nc2hEKI54tSoG5oMDjz:-Nc2hEKI54tSoG5oMDk-:b-o8diuf) ([raw file](https://github.com/starkware-libs/cairo/blob/414c8251a31732751fd0f7ce0dd64accf2242b13/crates/cairo-lang-starknet/src/plugin/events.rs#L413)):*
> ```XML
>             $empty_event_code$
>                 impl {state_struct_name}EventEmitter{generic_arg_str} of \
>              EventEmitter<{full_state_struct_name}, Event> {{
> ```

did you make the change that if you have a local impl you don't need to include the trait?



_Code quote:_
```XML
            $empty_event_code$
                impl {state_struct_name}EventEmitter{generic_arg_str} of \
             EventEmitter<{full_state_struct_name}, Event> {{
```
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 179 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3930#-Nc2hU0n3Wradnbkt0hT:-Nc2hU0n3Wradnbkt0hU:bhlgc5n) ([raw file](https://github.com/starkware-libs/cairo/blob/414c8251a31732751fd0f7ce0dd64accf2242b13/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L179)):*
> ```
>         unsafe_new_contract_state()
>     }
>     
> ```

remove if avoidable.



_Code quote:_
```
···
```

**Review by yuvalsw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3930)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/events.rs` line 413 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3930#-Nc2hEKI54tSoG5oMDjz:-NcHCZXu4QgY9uOaASF2:be9nm1m) ([raw file](https://github.com/starkware-libs/cairo/blob/414c8251a31732751fd0f7ce0dd64accf2242b13/crates/cairo-lang-starknet/src/plugin/events.rs#L413)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

did you make the change that if you have a local impl you don't need to include the trait?
</blockquote></details>

Yes, but this is code I just moved. I'll change it in a separate PR
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 179 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3930#-Nc2hU0n3Wradnbkt0hT:-NcHE6tC0QQYnMYtop22:b-2vmrv) ([raw file](https://github.com/starkware-libs/cairo/blob/414c8251a31732751fd0f7ce0dd64accf2242b13/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L179)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove if avoidable.
</blockquote></details>

Probably avoidable, didn't find it now, but will try to do it in a future PR.

**Review by orizi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3930#-:-NcHKbwF-ob_Mjot6aQu:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Review by orizi — APPROVED** [review]
> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3930)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

**Pull request merged**
