### PR TITLE
Fix: typos

### PR DESCRIPTION
**Pull request by omahs**
Fix: typos

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1779)

### CODE REVIEW

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1779#-:-NNfej4d7-wsKOYSGCS9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @omahs)

**Comment by spapinistarkware** [comment]
Can you please resolve conflicts?

**Comment by omahs** [comment]
@spapinistarkware Just updated!

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1779)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @omahs)

**Review by spapinistarkware — APPROVED** [review]
Thanks:)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1779#-:-NNjxD2k09XRA6U30anT:b-hay1wj)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @omahs)

**Pull request merged**
